### ISSUE TITLE
FNX-4707 ⁃ [meta] Main Menu

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#100]
From homescreen (3dot menu)

* Your library
* Settings
* Help

From webpage (floating action/or bottom app bar)

* Help
* Settings
* etc.
* order is based most used action items, e.g. add new tab at bottom, easier access to actions)

**Comment by vesta0** [comment]
Covered in #116

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.
https://docs.google.com/spreadsheets/d/1hQMPbQJUasaijxlOBjwUbXsYhuldBOdZXKO8gQPhcfk/edit?usp=sharing

**Comment by vesta0** [comment]
@mheubusch I noticed that the google doc has a few incomplete items, are there separate issues filed for those and can we close this meta?

**Comment by vesta0** [comment]
Closing this meta as this feature has been built. Any outstanding bugs and enhancements can be filed as separate issues.
