### ISSUE TITLE
Update dynamic toolbar scroll behavior to be based on velocity

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#10008]
### Why/User Benefit/User Problem
The current behavior has several "glitchy" feeling things because we're trying to animate `setVerticalClipping` and the toolbar perfectly with the users dragging. Instead we could opt for only animating to collapsed or expanded after the user has dragged a certain amount. We could also base it on velocity of scroll with a Gesture Recognizer. 

cc @snorp for tracking this :grinning:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-24)

**Comment by sblatz** [comment]
Adding to group triage so Vesta can weigh in on importance of this.

**Comment by boek** [comment]
Closing this as a dup of #10065
