### ISSUE TITLE
add-ons manager: style issue with star icon

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#10002]
### Steps to reproduce
1. open the add-ons manager

### Expected behavior
Both ends of the star icon (user rating) are on one line.

### Actual behavior
While verifying #9710 I noticed a style issue with the star icon. Please have a look at the bottom of the icon:

![](https://user-images.githubusercontent.com/1100614/79497438-fb837e00-8027-11ea-8766-aabe35e46781.png)

It's not symmetric and it makes the alignment issue in #9710 more noticeable.

### Device information
* Android device: OnePlus 7T Pro McLaren Edition, OxygenOS 10.0.7 (Android 10)
* Fenix version: master branch revision 335642d4f452a802da2e83731137c88f79c1ba4c

**Comment by brampitoyo** [comment]
@cadeyrn I’m not sure why this is happening. It’s a very minor issue, regardless. Paging @Amejia481 for comment.

**Comment by AmyYLee** [comment]
@brampitoyo @Amejia481 for follow-up

**Comment by brampitoyo** [comment]
@Amejia481 Do you know if we’re using a star asset that’s pulled from AMO?

Here’s an example of how things can look like if we try using the same star asset as our bookmark star:

<img width="360" src="https://user-images.githubusercontent.com/51007/83996323-f26fb700-a9af-11ea-832a-b343ab370aee.png">

The first example (top) uses the same bookmark star used everywhere else on Fenix, sized default at 24x24dp.

The second example (middle) uses the desktop bookmark star, sized at 16x16dp, with 4dp gap inbetween.

The third example (bottom) uses the Fenix bookmark star, with a little more margin (4dp or 8dp) between the description text and the star area.

I think the bottom example strikes the best balance between reusability and readability, so it’s the approach that I would prefer.

However, I’m also concerned about the fact that the number of users might get too large (7 digits with commas). If this ever happens, then the text would flow to the next line and break the layout. Should I be concerned about this? I think that the number of add-on users on mobile won’t ever be as large as desktop, so this is not a problem in the short or medium term.

What do you think?

**Comment by cadeyrn** [comment]
> However, I’m also concerned about the fact that the number of users might get too large (7 digits with commas). If this ever happens, then the text would flow to the next line and break the layout. Should I be concerned about this? I think that the number of add-on users on mobile won’t ever be as large as desktop, so this is not a problem in the short or medium term.

@brampitoyo These numbers represent the number of reviews not the number of users so I don't think such large numbers will happen anytime soon.

**Comment by Amejia481** [comment]
> @Amejia481 Do you know if we’re using a star asset that’s pulled from AMO?
> 
> Here’s an example of how things can look like if we try using the same star asset as our bookmark star:
> 
> <img alt="" width="360" src="https://user-images.githubusercontent.com/51007/83997037-99a11e00-a9b1-11ea-8792-e5e7d68eb886.png">
> 
> The first example (top) uses the same bookmark star used everywhere else on Fenix, sized default at 24x24dp.
> 
> The second example (middle) uses the desktop bookmark star, sized at 16x16dp, with 4dp gap inbetween.
> 
> The third example (bottom) uses the Fenix bookmark star, with a little more margin (4dp or 8dp) between the description text and the star area.
> 
> I think the bottom example strikes the best balance between reusability and readability, so it’s the approach that I would prefer.
> 
> However, I’m also concerned about the fact that the number of users might get too large (7 digits with commas). If this ever happens, then the text would flow to the next line and break the layout. Should I be concerned about this? I think that the number of add-on users on mobile won’t ever be as large as desktop, so this is not a problem in the short or medium term.
> 
> What do you think?

We are using the stock android image for this component.

**Comment by Amejia481** [comment]
If we need to change the image, we are going to need three versions, full filled, half full, and empty

**Comment by brampitoyo** [comment]
@Amejia481 After thinking about this some more, I wonder whether we can reuse the same `rating-star.svg` icon used on desktop (2.4 KB) and then call it three different times:

- #full = star filled with full color
- #half = half-filled star (full color at left, transparent color at right)
- #empty = star filled with transparent color

Size them at 14dp, and give them a 1dp padding all around (so the “real” dimension is 16dp).

And set the fill colour to:

- Light theme: Ink 80 `#20123A`
- Dark and private themes: Light Grey 5 `#FBFBFE`

And the transparency in the SVG file would take care of the half colouring.

Link to `rating-star.svg`:
https://share.getcloudapp.com/NQugzybG

I also agree with you, that this is a minor polish issue. Using the existing Android icon is perfectly acceptable for now.

**Comment by brampitoyo** [comment]
@Amejia481 Here are the three assets for full, half and empty – the same asset we use on desktop:

- `rating-star-full.svg`: https://share.getcloudapp.com/wbuWeNqY
- `rating-star-half.svg`: https://share.getcloudapp.com/4guj7DGL
- `rating-star-empty.svg`: https://share.getcloudapp.com/YEupvlb4

I’ve set the colour to be compatible with the light theme, but hope that these will also be colourable dark and private themes.

The sizing is the same: 14dp, with 1dp paddings inbetween.

**Comment by Amejia481** [comment]
Thank you :)
We will be adding to our spring planning according to priorities!
