### ISSUE TITLE
FNX-3228 ⁃ [Bug] WebPush messages are not properly delivered

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#10001]
## Steps to reproduce
1. navigate to https://gauntface.github.io/simple-push-demo/
1. make sure "Enable Push Notifications" is disabled
1. toggle "Enable Push Notifications" to be active
1. enter a payload text
1. tap send
1. --> Result 1
1. Connect device to remote debugger
1. copy the network request that triggers a new push notification as cURL 
1. close fenix via android activity manager
1. connect to device via ADB logcat
1. paste cURL command into terminal and send request
1. --> Result 2
1. Launch fenix activity via android launcher
1. use cURL command once more
1. --> Result 3
1. reopen tab with https://gauntface.github.io/simple-push-demo/
1. connect remote debugger to tab
1. issue cURL command again
1. --> Result 4
1. enter payload text
1. tap send
1. --> Result 5

### Expected behavior
1. works as expected

2 - 5. A notification should be created

### Actual behavior
1. logcat shows that fenix is started in the background and that a push message is being processed, but no notification is triggered by the service worker.
1. same result as 2, launching the main activity doesn't change anything.
1. the remote debugger prints the log message "Received push" after the cURL command is issued. This seems to indicate that the message is delivered to the service worker but creating a notification somehow fails.
1. This sometimes didn't trigger the "Received push" log message which seemed to indicate that the push was not delivered to the service worker, but when I tried it again later, it did. So I'm not quite sure about this last one.

### Device information
* Android device: SONY Xperia 10, Android 9
* Fenix version: Nightly 200415 18:00 (Build #21061806)

Mentioning @jonalmeida because I think he worked on this.

**Comment by jonalmeida** [comment]
Thanks for filing @TitanNano ! This is a known issue that is being worked on.

GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1611035

**Comment by TitanNano** [comment]
@jonalmeida aww I see. I only checked here on GitHub for existing reports. Should we keep this open in here too, or should I close it since it's already being tracked on Bugzilla?

**Comment by jonalmeida** [comment]
Let's keep this open to get a sense of what product priority this is for Fenix.

**Comment by TitanNano** [comment]
GeckoView bug has been resolved and the nightly build has propagated down into Fenix. I can confirm that this works now.

**Comment by jonalmeida** [comment]
> GeckoView bug has been resolved and the nightly build has propagated down into Fenix. I can confirm that this works now.

It almost works _too_ well now. 😅

**Comment by jonalmeida** [comment]
For QA, some simplified STR:
 1. Go to https://gauntface.github.io/simple-push-demo/
 2. Toggle the 'Enable Push Notification' on.
 3. Send a notification.
 4. Swipe the app away.
 5. Re-open the tab and send a notification again.

## Expected
 - At 3 and 5, the notification should be sent.

## Actual
 - At only 3 the notification is sent.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200529-101646](https://user-images.githubusercontent.com/51314259/83232449-ddb44780-a195-11ea-8e98-11c097626a06.gif)

**Comment by jonalmeida** [comment]
I filed BZ-1660867 for this since it seems to be a GeckoView bug.
