### ISSUE TITLE
FNX-3227 ⁃ [Bug] instead of dot release, beta version apk of 4.2.1

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#10000]
## Steps to reproduce
https://github.com/mozilla-mobile/fenix/releases/tag/v4.2.1
tap  firefox_preview_v4.2.1_arm.apk

### Expected behavior
download 4.2.1

### Actual behavior
downloaded apk 4.2.1-beta.1 (Build #20941424)

### Device information
* Android device: 5.1
* Fenix version: 4.1

**Comment by cadeyrn** [comment]
Duplicate of #9569.

**Comment by kbrosnan** [comment]
This should be fixed.
