### ISSUE TITLE
FNX-4709 ⁃ Fennec replacement builds to use existing Adjust keys

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1001]
As a release engineer, I want Fennec replacement builds to use the existing Adjust SDK Key secrets

## Dependencies (Added by PM and Eng)
* Depends upon the creation of Fennec replacement builds in the TaskCluster configuration
* Requires an engineer or release engineer to include logic for Fennec builds to download and use existing Fennec keys from our secrets store

## Next Steps 
* After we create the Fennec-typed builds, we will want to ensure the correct Adjust SDK Key is being included in those builds.

### Acceptance Criteria (Added by PM)
* I can validate the keys match the equivalent Fennec builds
* I can track Fenix install referrer links with the same interface used the track Fennec install referrer links

**Comment by vesta0** [comment]
Closing this issue since we are no longer considering this approach. We can re-open if strategy changes.
