### ISSUE TITLE
FNX2-13049 ⁃ [Bug] External links do not work in Dark Reader panel

### ISSUE THREAD

**Issue by kawaiiDango** [mozilla-mobile/fenix#10018]
## Steps to reproduce
* install dark reader
* open a tab, click menu, click dark reader
* tap the donate button. The panel just closes
* tap settings > help. The panel just closes
    1. Expected behavior
The external links should open in a new tab
    1. Actual behavior
The links do not open. Not sure if this is a Firefox issue or an addon issue.
    1. Device information
* Android device: OnePlus 6, Android 10
* Fenix version: Nightly 200416 08:30 (Build #21070840)
39.0.20200415130046, e08fc0017
GV: 77.0a1-20200413034542
AS: 0.57.0

**Comment by s-ankur** [comment]
Hi, this seems to be fixed in latest nightly
