### ISSUE TITLE
FNX-3234 ⁃ [Bug] If you navigate in fullscreen mode, you get trapped in fullscreen mode forever (with browser toolbar missing from that point on)

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#10015]
## Steps to reproduce
1. visit https://climaterwc.com/2020/04/16/residents-iphone-captures-compelling-footage-of-redwood-city-amid-pandemic/
1. Scroll down to the video (at the bottom of the article text, just above the Facebook/Twitter/etc. icons)
1. Click "play"  on the video
1. Click the fullscreen icon at the bottom-right of the video.
1. Click the Vimeo logo at the bottom-right of fullscreened video UI.
--> Note that this triggers a navigation to a normal web page (not intended to be a fullscreen experience)
1. Try to access the browser UI (find the menu, or see if you can figure out how to switch tabs)

### Expected behavior
I should leave fullscreen mode. In particular, my system tray (top of screen, with clock at the left & battery on the right) and Firefox's toolbar (bottom of screen, normally visible when I scroll appropriately) should both reappear.

### Actual behavior
I remain in fullscreen mode -- the Vimeo web page occupies my entire screen. Even if I swipe in from the edge of the screen to reveal my OS "back" button, and tap that button, I'm still in fullscreen mode (Firefox's toolbar is never shown).

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 200414 12:39

**Comment by dholbert** [comment]
Screencast of bug:
https://www.dropbox.com/s/8xxg2h1ry5h9hek/fenix-fullscreen.mp4?dl=0

Notice that my system tray (top of screen) disappears at 0:05 when I enter fullscreen mode. 

EXPECTED RESULTS are that it should *reappear* (and I should exit fullscreen mode) at ~0:07 after I tap the vimeo icon to navigate out of the fullscreen video to the normal vimeo.com webpage.

At 0:16, I swipe in from the edge of my screen which is the Android gesture for "give me back my 'soft' system-level back & home buttons, and also the system tray, as overlays over my current fullscreen content".  But even after I reveal those buttons and tap `back` to return to the site I started at (after 0:17), Fenix is *still* stuck in fullscreen mode with no toolbar.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 4/21 #21121811.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).

**Comment by dholbert** [comment]
Yup, seems fixed for me as well. Thanks!
