### ISSUE TITLE
[Bug] Botton Dynamic Navigation Bar does not hide with a single swipe and does it but leaves white spaces

### ISSUE THREAD

**Issue by serovar** [mozilla-mobile/fenix#10010]
## Steps to reproduce
Go to your feeds on feedbin.com and scroll down with a single swipe or with two in rapid sequence.

### Expected behavior
The bottom navigation bar hides itself leaving way for the webpage content (in this case, the site own bottom bar).

### Actual behavior
The bottom navigation bar doesn't hide itself with a single upward swipe, it only  does it with two in rapid sequence, but in that case it leaves a white space.

![feedbindown](https://user-images.githubusercontent.com/6732420/79517234-e3265a00-804d-11ea-9497-0abba6bb267c.gif)

Similar but not the same of issue #8768.

### Device information
* Android device: Pixel 2 XL, Android 10
* Fenix version: Nightly 200416 18:00 (Build #21071807)

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the 85.0.0-beta.9 Beta build with Sony Xperia Z5 Premium (Android 7.1.1):

https://user-images.githubusercontent.com/40694158/104891363-7f80e280-5979-11eb-813a-fe9d34274672.mp4

**Comment by softvision-miralobontiu** [comment]
I reproduced this issue on the latest RC 86.1.0 build with Sony Xperia Z5 Premium (Android 7.1.1) on instagram.com:

https://user-images.githubusercontent.com/40694158/108682582-29173e80-74f9-11eb-98b8-4144b24f498e.mp4

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this on instagram.com on Beta 87.0.0-beta.1 with Google Pixel (Android 10), but only after enabling "Zoom on all websites" from Settings - Accessibility.

**Comment by mariansima** [comment]
Could not reproduce on Samsung A8 SM-A530F Android 9 Nightly 93.0a1 2021-08-30
