### ISSUE TITLE
FNX-3240 ⁃ [Bug] Allow search suggestions in private sessions overlaps This Time Search With text

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10028]
![Screenshot](https://user-images.githubusercontent.com/46655/79614985-4902f800-80c7-11ea-8f46-b355a6a04b1f.png)UNITO-UNDERSCORE!20200417-152959!

## Steps to reproduce
1. Open private mode for the first time

### Expected behavior
1. "This time search with" appears below "Allow search suggestions..." text

### Actual behavior
1. They overlap each other

### Device information
* Android device: Google Pixel 4

**Comment by ekager** [comment]
Closing for #9550
