### ISSUE TITLE
FNX-3239 ⁃ [Bug] Address bar context menu cannot be dismissed without selecting an option from menu

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10027]
## Steps to reproduce
1. Open Fenix
1. Open any website
1. Tap and hold on address in address bar
1. Do any of: tap meatball menu, press back button, tap on page content, tap on location bar, tap tab switcher

### Expected behavior
Contextual menu should be dismissed.

### Actual behavior
Context menu is not dismissed unless an option is selected from the menu. Fenix appears completely frozen  until this occurs. 

FYI: I cannot reproduce this on my Pixel 2. 

### Device information
* Android device: Moto G XT1031
* Fenix version: latest from play store. 
* Edit: Reproducible only on SDK 22 or below.

**Comment by mcarare** [comment]
@yoasif I assume that device has Android 5 or at most 5.1.1?  I cannot reproduce on SDK 23 or higher but I can reproduce it on 21 & 22.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 4/24 #21150607.
Now you can dismiss the context menu by tapping on the page content, toolbar or overview buttons from your device.

Devices:
- Huawei MediaPad M2 (Android 5.1.1).
