### ISSUE TITLE
FNX-3238 ⁃  can not download  base64 image

### ISSUE THREAD

**Issue by realTomorrow** [mozilla-mobile/fenix#10020]
## Steps to reproduce
google image search page , long press image , "can not download this type file".
firefox can doownload.
&
fenix nightly can download.

### Device information
* Android device: anydevice
* Fenix version: latest

**Comment by realTomorrow** [comment]
firefox can download.
&
fenix night can download.

**Comment by ekager** [comment]
You mean after pressing "Save image" in the context menu for any Google image search image? It throws an error?

**Comment by Amejia481** [comment]
I was able to replicate this issue, QA please help us to verify.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21140603 from 4/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200423-101553](https://user-images.githubusercontent.com/51314259/80070788-39aeff00-854c-11ea-8fc7-e1ec1c314254.gif)
