### ISSUE TITLE
Audio intermittently does not work on chessable.com

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#10039]
## Steps to reproduce
I "installed" Chessable.com, and tried to use the board for training. Installing the site gets rid of the bug where you can't move any pieces because the auto-hiding address bar interferes with drag and drop (which I filed previously and isn't fixed). 

### Expected behavior
Sound works the same as using the website in the normal manner. 

### Actual behavior
Sound no longer works. 

### Device information
* Android device: Pixel 2 XL
* Fenix version: today's Nightly

**Comment by gcp** [comment]
After more experimentation, it looks like sound simply doesn't work intermittently and install vs a regular page does not matter.

The site works correctly in Fennec and Chrome.

**Comment by softvision-miralobontiu** [comment]
@gcp could you retry on the latest Firefox Nightly?
Thank you!
