### ISSUE TITLE
FNX-3243 ⁃ "Follow device theme" no longer switches to Dark mode automatically

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#10036]
## Steps to reproduce
Set Customise > Follow device theme
Switch Android phone between Light and Dark mode (aka Night mode)

### Expected behavior
Fenix switches to dark mode (it did this until a week or two ago)

### Actual behavior
No switch (this new broken behaviour started perhaps 2 weeks ago)

### Device information
Galaxy A40, Android 10, today's Fenix Nightly

**Comment by SS1113** [comment]
Yes, this happens on my device too. The dark mode or the light mode don't automatically switch when the dark mode is enabled or disabled System-wide.

Device: Motorola One Power, Android 10.

Fenix Build: Firefox Preview 4.3.0 (Build #21082025) 
And 
The today's Nightly

**Comment by umerf52** [comment]
I'm also facing this bug.
OnePlus 3T, Android 10 (LOS 17.1, 20200401)
org.mozilla.fenix.nightly, Nightly 200416 08:30

It's daytime (1:40pm) right now, so everything is in light mode
In Phone Settings > Display > Dark Theme = Will turn on automatically at sunset
Fenix is set to follow system theme, but it is currently following light theme.
All other apps that are supposed to follow light mode are in light theme, e.g. Slack etc

**Comment by ygretharekar** [comment]
Hello I am able to reproduce the bug on my device, I would like to work on the solution, thanks.

**Comment by ekager** [comment]
Thanks for bringing this to my attention! I found a fix and should be working after https://github.com/mozilla-mobile/fenix/pull/10074 lands.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 04/23. Devices: Samsung Galaxy Note10 (Android 10) and Xiaomi Redmi Note 8T (Android 9).
