### ISSUE TITLE
Allow user to search within History

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10046]
### Why/User Benefit/User Problem
As a user, I would like to search from my history (like I can in competing browsers like Chrome). 

### What/Requirements
* Search icon in Library History UI. 
* tapping icon should show input field
* typing in input should show pages from history matching my query

### Acceptance Criteria (how do I know when I’m done?)
When there is an icon in the Library History page that allows me to search previously visited pages.

**Comment by Poopooracoocoo** [comment]
i'd love to be able to view a history item in context!

**Comment by Aquind** [comment]
this is a basic feature in browsers for decades!  Please fix this bug/add this feature ;)  *antagonizing

**Comment by Meshikhah** [comment]
This feature is really important and useful. Please prioritize working on this.

**Comment by Poopooracoocoo** [comment]
Firefox 83 for desktop added three shortcuts to the "this time, search with" section so you can search only bookmarks, only tabs, or only history:
![image](https://user-images.githubusercontent.com/51363864/99468796-8bf6b800-2995-11eb-8a88-bfb1f0c285d0.png)
It's a shortcut for * for bookmarks, % for tabs and ^ for history prefixes. You can find this information from the [support article](https://support.mozilla.org/en-US/kb/search-firefox-address-bar)*

So you can search for history by searching in the address bar, search only for history in the address bar by prefixing your query with ^ and by using the history sidebar. Bookmarks and tabs also have 3 ways to search them. 

 \* P.S. If someone from Mozilla sees this, could you let someone who works on the documentation know that there should be some indicator that tells you that you need to sign in to edit?

**Comment by Poopooracoocoo** [comment]
@liuche hi could you contact the peeps who work on SUMO with the above feedback?

**Comment by Jerriy** [comment]
What's the point of showing history if one can't search it?

**Comment by Poopooracoocoo** [comment]
one year anniversary of this issue is coming up soon.

**Comment by Meshikhah** [comment]
Please prioritize working on this basic feature.

**Comment by oversaltedpotatoes** [comment]
I switched to Firefox a couple of months ago and was really baffled when I went to search my history today and discovered it didn't exist. It something I did on a pretty regular basis in Chrome.

**Comment by nbeaver** [comment]
Link to the same issue in the old Bugzilla tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1378026

**Comment by cryptowizard** [comment]
I will clean code and create pull request with this feature, later this week. It's here if someone needs it:
https://github.com/cryptowizard/fenix/tree/feature/search_history

**Comment by Practicalbutterfly5** [comment]
This is the only reason keeping me away from firefox on android.

**Comment by orchidalloy** [comment]
It really goes to show how much they care about the app.

**Comment by Poopooracoocoo** [comment]
<details>
  <summary>off-topic ramble</summary>
I think it's more of a management issue. They're really low on resources. The desktop app seems to have lots of features - save for Chrome-parity features like profiles. The desktop app seems to get features at a much faster pace than Fenix at this point in time too. There are tons of articles that talk about execs and their pay and how development gets cuts. Servo, MDN and Rust often get mentioned in such articles and the same articles also discuss Mozilla's funding. I'm sure the developers themselves care about Fenix, even with stable bot lol
</details>

**Comment by Verdi** [comment]
@rocketsroger The results implementation in nightly includes the append arrow in the results. We shouldn't have that. It can lead to weird situations where it looks like I can navigate to a url but I can't.

**Comment by rocketsroger** [comment]
> @rocketsroger The results implementation in nightly includes the append arrow in the results. We shouldn't have that. It can lead to weird situations where it looks like I can navigate to a url but I can't.

@Verdi Sure, can we have another issue to track this as defect?

**Comment by rocketsroger** [comment]
Created issue to track this issue https://github.com/mozilla-mobile/fenix/issues/24550
