### ISSUE TITLE
[Bug] Ephemeral dialogs should respect Android's Time to take action setting

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#10047]
## Summary
Android 10 has a new Accessibility setting called Time to take action (also known as accessibility timeout) which gives the user some control over how long apps show ephemeral dialogs. This is so that users can keep messages that ask you to take an action on the screen for longer periods of time. The settings are Default, 10 seconds, 30 seconds, 1 minute, and 2 minutes. 

## Steps to reproduce
Open the Android Settings app
Open the Accessibility settings
Open the Time to take action settings
Set it to 2 minutes
Open Fenix. 
Open a tab
Return to the home screen and close the tab

### Expected behavior
The undo close tab dialog, and any other ephemeral dialogs in Fenix, should respect the Time to take action setting and stay open for 2 minutes. 

### Actual behavior
The undo close tab dialog disappears in about 15 seconds. 

### Device information
* Android device: Galaxy S10e
* Fenix version: 4/17

## More info
This was announced in the developer update for Android Q at https://developer.android.com/about/versions/10/features#a11y-timeouts and the developer details can be found here https://developer.android.com/reference/android/view/accessibility/AccessibilityManager#getRecommendedTimeoutMillis(int,%20int)

**Comment by Dunexus** [comment]
This could be the solution to https://github.com/mozilla-mobile/fenix/issues/8998
