### ISSUE TITLE
FNX2-13054 ⁃ Make "Google Search Fixer" available as an add-on within Fenix

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10044]
### Why/User Benefit/User Problem
People want nicer Google SERPs, Google only offers this to Chromium. They are modifying their [UAs manually](https://www.reddit.com/r/firefox/comments/g3tyfu/how_to_switch_user_agents_on_firefox_preview/) to do this, which likely hurts user experience.

### What/Requirements
Make https://addons.mozilla.org/en-US/firefox/addon/google-search-fixer/ available as an add-on in nightly. 

### Acceptance Criteria (how do I know when I’m done?)
If I go to add-ons, I can install this add-on.

**Comment by yoasif** [comment]
Seems like this may be less necessary now. Fenix shows the new search experience for me.

**Comment by yoasif** [comment]
Seems like some people are still seeing the old Google. Reopening for the time being.

**Comment by NotWoods** [comment]
We would like to expand our support to other add-ons but we are not keeping open requests for specific ones. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates. The WebCompat team is also investigating this problem.

**Comment by victor-bayas** [comment]
Available on Nightly
