### ISSUE TITLE
FNX-3247 ⁃ [Bug] Very slow page loading on reddit (around 4x slower than Chromium)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10042]
## Steps to reproduce
1. Navigate to https://www.reddit.com/r/btrfs/

### Expected behavior
Loads in less than 8 seconds with posts (not just the page scaffolding). 

### Actual behavior
Loads page very slowly. 

See profile: https://perfht.ml/2VIHK0U

### Device information
* Android device: Moto G XT1031
* Fenix version: latest nightly from play store

**Comment by mcomella** [comment]
@jeanygong Can you open a bugzilla bug for the platform performance team for this issue?

**Comment by jeanygong** [comment]
I filed a bugzilla for this [](https://bugzilla.mozilla.org/show_bug.cgi?id=1637735)

**Comment by mcomella** [comment]
We're tracking in BZ: no reason to leave this open.
