### ISSUE TITLE
[Bug] Twitter's bottom bar doesn't look properly when Firefox URL bar is on top

### ISSUE THREAD

**Issue by JaviPereira** [mozilla-mobile/fenix#10043]
## Steps to reproduce
Browser version: Firefox Preview v4.3.0

I have the URL bar on top of the interface and when I'm browsing twitter I see what's on pic1, css seems broken. If I use the URL bar on bottom, no problem (pic2). I thought that twitter had css broken, but in fennec this doesn't happen (pic3).

![pic1](https://user-images.githubusercontent.com/63931513/79671672-1a1e7c00-81c4-11ea-8262-412672524845.png)
![pic2](https://user-images.githubusercontent.com/63931513/79671673-1b4fa900-81c4-11ea-9f97-2aed8ddd6c9f.png)
![pic3](https://user-images.githubusercontent.com/63931513/79671675-1be83f80-81c4-11ea-985f-910a404179ae.png)
![version](https://user-images.githubusercontent.com/63931513/79671676-1c80d600-81c4-11ea-9448-065d68f97364.png)

### Expected behavior
Twitter's bottom bar has to be in the bottom.

### Actual behavior
Twitter's bottom bar doesn't look properly.

### Device information
* Android device: Motorola Moto G4 with "/e/" rom
* Fenix version: 4.3.0

**Comment by benediktwinder** [comment]
Same problem on Instagram and various other sites.

**Comment by LaurentiuApahideanSV** [comment]
I am able to reproduce the issue on Firefox Preview 4.3.0 but not on Firefox Preview Nightly 200505.
@JaviPereira Could you download the latest Firefox Preview Nightly from the Google Play store and see if the issue still occurs?

**Comment by JaviPereira** [comment]
I try now and tell you something :blush:

**Comment by JaviPereira** [comment]
Hi!!

I tried with 5.0.0 beta and Nightly 200510 and it works correctly. However, it "jumps" a little bit. I tried with fennec and this does not happen. 

Fenix's jumps gif:
![fenix](https://user-images.githubusercontent.com/63931513/81500961-6f364500-92cd-11ea-8446-a53906fac2cd.gif)

Same test with Fennec:
![fennec](https://user-images.githubusercontent.com/63931513/81500962-71989f00-92cd-11ea-8069-f24ea04a823b.gif)

Regards,
Javi.

**Comment by ekager** [comment]
@sblatz is there an issue for the jumpy bottom content to link to? I couldn't find one with a quick search

**Comment by sblatz** [comment]
@ekager I'm not aware of an issue filed for that. Unfortunately I'm not sure how much we can improve this from the Fenix side. The reason this is happening is because we're calling `setVerticalClipping` while the toolbar animates. Lots of those calls means it feels "jumpy" 😕 since we can never perfectly track it to the dragging of the toolbar

**Comment by yoasif** [comment]
@sblatz I didn't bother trying this in Fennec because others have done that, but Kiwi seems to work just fine in my testing - no jumpiness. Are you saying that this is more of an AC issue - because I don't think it is a site issue (other browsers work okay).

**Comment by sblatz** [comment]
It is a GeckoView issue, @yoasif. This is "expected" due to our GV implementation of handling scrolling the toolbar.

Adding @snorp in case he wants to chime in here / has a different view!

**Comment by yoasif** [comment]
I don't think that jumpiness can really be "expected"; it feels like a GV bug to me based on your explanation. Just wanted to point out that there doesn't seem to be anything intrinsic about the page that seems to cause this issue. 

Sorry if my comment is not very helpful. :disappointed:

**Comment by cosarara** [comment]
> It is a GeckoView issue, @yoasif. This is "expected" due to our GV implementation of handling scrolling the toolbar.
> 
> Adding @snorp in case he wants to chime in here / has a different view!

Is there an open bug report on GV tracking this, then?

**Comment by swiesend** [comment]
I don't think this is expected behaviour, as there are also buttons disappearing.
<p align="middle">
  <img src="https://user-images.githubusercontent.com/3512490/92177365-a7473200-ee40-11ea-864d-46a559fd36f3.png"/ width="40%">
  <img src="https://user-images.githubusercontent.com/3512490/92177370-a9a98c00-ee40-11ea-9e76-ab995e7e5e74.png" width="40%" /> 
</p>
