### ISSUE TITLE
FNX-3253 ⁃ [Bug] Unable to enable disabled add-ons

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#10048]
## Steps to reproduce
Have a disabled add-on from Fennec
Wait months
Get the ability to enable some of the add-ons 

### Expected behavior
Add-ons enabled

### Actual behavior
A notification keeps reminding me about one of my disabled add-ons

### Device information
* Android device: Pixel 4XL
* Fenix version: Nightly

**Comment by Amejia481** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/9994
This should be fixed in master by https://github.com/mozilla-mobile/android-components/commit/24e01300b1e654fb9e2645a904685cbbbc5447b5
