### ISSUE TITLE
[Bug] Unable to add Spiegel.de to homescreen on Sony device running Android 6

### ISSUE THREAD

**Issue by MotoSQ** [mozilla-mobile/fenix#10051]
Hi,
Due to whatever reason, I can't mark a website (e.g. Spiegel.de) as bookmark /link for the start/main screen of the mobile.
Android 6.0.1.  Sony D6503.
Bookmark at startscreen of Firefox Preview  works fine.

Any idea what to do, or workaround?

Beside this, everything absolutely OK. Thanks for the fantastic work
Friedbert 

### Device information
* Android device: ?
* Fenix version: ?

**Comment by hwinnemoe** [comment]
I can not reproduce on exactly the same device and Android version on Nightly 200810 06:01 (Build #2015757105), see this image of the mentioned PWA:

![image](https://user-images.githubusercontent.com/42788925/89823461-cdcfc100-db51-11ea-8d59-2de33942f456.png)
