### ISSUE TITLE
FNX-3258 ⁃ Quick link to report a bug

### ISSUE THREAD

**Issue by theprojectsomething** [mozilla-mobile/fenix#10053]
### Why/User Benefit/User Problem
As a first time FF Mobile bug reporter, it's not entirely clear where this should be done:

* There is a link in the browser UI to 'report a site issue' that sends you to [webcompat.com](https://webcompat.com) (very cool), but it isn't clear if this is purely for reporting specific sites, or is intended as a triage point for browser issues as well.
* Choosing `Settings > About Firefox > Support` opens [Firefox Preview Support](https://support.mozilla.org/en-US/products/firefox-preview?as=u&utm_source=inproduct) in a web portal window. Here you can search for help, explore frequent topics, ask the community or read a featured article. Nothing stands out for bugs. In the page footer the most obvious links are `Mozilla > Source code` and e.g. `Firefox for Developers > Beta for Android`
* The [Firefox for Developers](https://www.mozilla.org/en-US/firefox/channel/android/) page has a couple of intriguing options:
  * "Give us Feedback" links to a happy or sad face .. I believe this was previously available directly from the UI. A possible solution could be to re-include this link.
  * More appealing is "See something that isn't working? Let us know." with a link to [File a bug now](https://bugzilla.mozilla.org/enter_bug.cgi).

I followed all these steps and [filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1631294), only to be told that Firefox Preview issues are tracked here on Github.

### What/Requirements
A settings shortcut to "Report browser issue", to be made available in the preview channels, similar to "Report site issue":

* To slow down over-reporting, this could sit deeper in the UI e.g. under `Settings > About Firefox` (first place I looked anyway)
* Could either link to the happy/sad faces with a secondary option to skip to Github
* OR link directly to Github, with all the account requirements, submission guidelines and issue lookup capabilities to drown out the noise

### Acceptance Criteria (how do I know when I’m done?)
I notice the rare repeating glitch in the preview/beta channel. I decide to be a good citizen and report it. I find the shortcut via the browser UI and am presented with a short form. I know exactly what I mean so I skip the form and click the link to report an issue directly. I search to see if my issue has already been reported (it has, lots of people are having it). I check the status - `Prioritized Bug Backlog`

* thumbs up the issue and return to browsing, content that it will be resolved in an upcoming release.

**Comment by kbrosnan** [comment]
This is not something we have in any of the Firefox products on desktop or mobile. We have an adequate number of external reports.

**Comment by theprojectsomething** [comment]
Hey @kbrosnan there's a submit feedback on Firefox desktop (dev v76.0b5) under `Help > Submit Feedback` which takes you to the "How does Firefox make you feel?" happy/sad faces. This would suffice. Though I'm assuming you actually want/need the feedback?

Also as mentioned the "See something that isn't working? Let us know." link on the Android Firefox developers homepage (which is accessed via the browser settings, albeit as a portal) is redirecting to the wrong bug tracker.
