### ISSUE TITLE
FNX-3260 ⁃ Custom tab: "Open in browser" does not switch to tab.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#10055]
* Open a custom tab (e.g. from Twitter)
* Select "Open in Firefox Nightly"

Expected

* Browser opens and shows tab

Actual

* Browser opens on home screen (with tab added to tabs list)

**Comment by ekager** [comment]
Closing for #9815
@pocmo I had a question there if you have a sec? :)
