### ISSUE TITLE
FNX-3266 ⁃ [Bug] Open settings links as regular links, not custom tabs

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#10064]
Currently our settings links (like in the about page) open up as custom tab links. According to Paul on the SUMO team this makes it difficult to follow advice from the help articles since they talk about doing things in a normal tab. We should update these to just use `openToBrowserAndLoad` instead.

**Comment by ValentinTimisica** [comment]
Reopening this for QA

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fenix Nightly Build 21550609 GV 78.0a1 from 6/3 with Huawei P9 Lite (Android 7), Nexus 5 (Android 6.0.1).

The links from the About Firefox page opens in regular links and not in custom tabs.
@ValentinTimisica I had filed a new issue that might be related https://github.com/mozilla-mobile/fenix/issues/11181.
