### ISSUE TITLE
FNX-3263 ⁃ Browser back button missing from new 'firefox beta' UI

### ISSUE THREAD

**Issue by pm215** [mozilla-mobile/fenix#10060]
Firefox Beta for Android recently switched from the old (Fennec?) UI to the new (Fenix?) one. The old UI had a 'back' button in the browser url bar. The new one seems to be missing it.

Sometimes the android back-arrow seems to do the same job, but not reliably (I can't figure out when it does and doesn't). In any case:

* it doesn't have the long-press-to-show-history feature (cf issue #1048)
* it's in the wrong place (ie unhelpfully at the bottom of the screen rather than up in the toolbar where the rest of the UI is, and in particular where the 'forward' button is)
* at least some of the time it takes you to the list-of-open-tabs page (I think this may be when there is no previous page to go back to? -- but in that situation the 'back' button should just be greyed out and do nothing, as is usual behaviour for web browser back buttons and which matches how the Fenix forward button works.)

When restoring the 'back' button it ought to be actually visible like the old UI, not hidden in a menu option like the 'forward' button is currently (cf issue #4134).

* Android device: Tablet, Huawei Mediapad M5 (CMR-AL09)
* Fenix version: Firefox Beta 75.0.0-beta.4 (build #2015734507)

**Comment by kbrosnan** [comment]
Dupe #4134

**Comment by pm215** [comment]
#4134 asks for options currently in the hamburger menu to move to the top level; but the back button isn't in the hamburger menu at all...

**Comment by kbrosnan** [comment]
That is describing a slightly older design.  We don't have a tablet UI right now and that is the main issue.

**Comment by RogerMito** [comment]
I noticed it too. I'm using this version in a tablet and it's being very annoying. Whenever I want to back or go forward to some page, I need to use Android's buttons or its gestures. Like me, many people have gotten frustrated after this change. Unfortunately, the way out is migrating to older versions or even use another browser :(. I hope you fix it as fast as possible. Thanks.

**Comment by 7wells** [comment]
The official Android release of Firefox 79 was rolled out in Germany on 25 August. There is no back button, either. And all extensions are gone. Currently, there are just 9 extensions available in total. This new version is really bad. I will install my previous version from a Titanium Backup (incl. all nicely working settings and extensions) after a complete deinstallation of the new Firefox version, which is unusable for me.

**Comment by cadeyrn** [comment]
> There is no back button,

There will be a back button in the menu in Firefox 80 and higher. In the meantime you can use the Android back button or gestures navigation in newer Android versions.

>  I will install my previous version

I recommend to take security more seriously. You should never use outdated browsers to browse the web.

**Comment by 7wells** [comment]
Until 80 is here, I might have wandered off to another browser. E.g. the 'Text reflow' extension is mandatory for me, as Firefox is unable to wrap text when zooming. That extension filled that gap but is gone now, too. I wonder how people use a browser that cannot wrap text (natively or with an extension). But I'm getting OT here, sorry. A short word about security, though: I don't do security-relevant stuff on my mobile device.
