### ISSUE TITLE
FNX-3276 ⁃ [Bug] Improperly displayed and moving overlays after opening Fenix from the widget

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10079]
## Prerequisites
The search widget should be added to the device's home screen.

## Steps to reproduce
1. Long tap on any of the featured Top Sites.
1. Put Fenix in background
1. Tap the Search widget 

### Expected behavior
The previously opened overlays shouldn't be displayed after opening a new search session through the widget.

### Actual behavior
Improperly displayed and moving overlays after opening a new search session through 

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
Nightly Build #21120610 from 4/21
Fenix Beta 4.3.0-beta.2 from 4/16

### Notes
❗ Happening after opening the ⋮ Main menu home screen overlay or the Search engines overlay. 
► Video
![20200421-120359](https://user-images.githubusercontent.com/51314259/79848341-a221a300-83c9-11ea-83d8-1a2ce25c5d0b.gif)

**Comment by Diana-Rus** [comment]
Hi, issue is fixed, verified with Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7)
- Verified with menu for top sites
- Verified with menu for search engines
- Verified with the ⋮ Main menu home screen

GIF - Google Pixel 3 XL (Android 9
![20200602-182109](https://user-images.githubusercontent.com/49859863/83540201-a8df2200-a500-11ea-981b-c71a5959f99d.gif))
