### ISSUE TITLE
[Bug] Moving cursor in the text field sometimes takes to the bottom of the page

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10072]
## Steps to reproduce
1. Go to: https://github.com/mozilla-mobile/fenix/issues/new
1. Type in something, select the text input field/Title and try to move the cursor to left and right and a bit to the downside while doing so
1. Observe that it takes to the bottom of the page

### Expected behavior
This action should not take to the bottom of the page. This doesn't happen in the text field of the address bar of Fenix or in Chrome browser's address bar or text input field

### Actual behavior
Takes to the bottom of the page

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: Nightly 200420 06:01 (Build #2015735603) and can also be reproduced on: 4.3.0 (Build #21082025)
![20200421](https://user-images.githubusercontent.com/42088907/79821099-606b0b00-837d-11ea-8ecf-693c9c57c92d.gif)UNITO-UNDERSCORE!083249!

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)
