### ISSUE TITLE
FNX-3269 ⁃ [Bug] Extensions randomly completely stop working

### ISSUE THREAD

**Issue by unixandria-xda** [mozilla-mobile/fenix#10070]
## Steps to reproduce
Use Fenix. Unsure exactly how to reproduce, it's a random occurrence.

### Expected behavior
Extensions that are supported work correctly.

### Actual behavior
All enabled Extensions disappear from 3 dot menu. Going to add-ons in settings leads to a blank page stating "failed to query add-ons". No add-ons do what they're supposed to (eg dark reader not turning pages dark, uBlock not blocking anything)

### Device information
* Android device: OnePlus 7T, OxygenOS 10.0.9 (Android 10, API 28)
* Fenix version: 200420

**Comment by linuxandria** [comment]
Wiping app data temporarily solves the issue, then it randomly occurs again.

**Comment by csadilek** [comment]
@linuxandria Thanks for filing! This is a recent regression. We're working on a fix: https://bugzilla.mozilla.org/show_bug.cgi?id=1631137

**Comment by csadilek** [comment]
A-C: https://github.com/mozilla-mobile/android-components/issues/6702

**Comment by csadilek** [comment]
For QA: The STR for this problem that were reliable for us are in this comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1631137#c7

Fix is on Fenix master, Play store update is still pending.

**Comment by csadilek** [comment]
Latest version in Play Store has the fix now: Nightly 200422 16:13.

**Comment by linuxandria** [comment]
Issue seems resolved on my end, I'll ping here if it reoccurs

**Comment by AndiAJ** [comment]
Hi, as per my findings from [#9994](https://github.com/mozilla-mobile/fenix/issues/9994#issuecomment-618388169) **this issue got fixed**  after updating to the latest **`Nightly Build #2015736177 from 4/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• Samsung Galaxy S7 (Android 7)

**► Video after migrating Fenix GV 77 from 4/16** 
![20200423-150525](https://user-images.githubusercontent.com/51314259/80102128-0899f300-857b-11ea-9366-0c04c5959f74.gif)

**► Video after migrating to the latest Fenix GV 77 from 4/23** ✔️ 
![20200423-150640](https://user-images.githubusercontent.com/51314259/80102265-2e26fc80-857b-11ea-9465-b5a552043c6d.gif)

**Comment by Jaakkonen** [comment]
I'm still experiencing this problem with Firefox Nightly and Preview from Play store.

**Comment by cadeyrn** [comment]
@Jaakkonen What you see in current builds is probably #12399.
