### ISSUE TITLE
FNX-4715 ⁃ Request Desktop Site in a Custom Tab

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1007]
Dependent on https://github.com/mozilla-mobile/android-components/issues/2699

### Acceptance Criteria:
I can open the desktop version of a site that is opened in a custom tab.

**Comment by jonalmeida** [comment]
This should be fixed in tomorrow's A-C 0.54.0 snapshot. (Fenix is currently on 0.53.0)

**Comment by softvision-miralobontiu** [comment]
Verified that "Desktop site" option is available in Custom tabs and works as expected, on the latest build 1.0.1921 (#11440149), with Nexus 5 (Android 6.0.1), Sony Xperia Z5 Premium (Android 7.1.1), Google Pixel (Android 9).
