### ISSUE TITLE
FNX-3270 ⁃ [Bug] Web Telegram PWA has a white space left when the bottom address bar disappear during scroll

### ISSUE THREAD

**Issue by Blaze-Thunder** [mozilla-mobile/fenix#10071]
## Steps to reproduce
Open Web Telegram as a PWA, scroll down. Once the address bar disappears, white space appears

### Expected behavior
There shouldn't be any white space and the PWA content should be displayed normally

### Actual behavior
There is a huge white space left at the place of bottom address bar

### Device information
OnePlus 7 Pro, running latest Firefox nightly 200420 06:01 on Android 10

* Android device: Android 10
* Fenix version: 200420 06:01
![Screenshot](https://user-images.githubusercontent.com/64011423/79819819-5562ab80-837a-11ea-9119-33ede68c18d8.png)UNITO-UNDERSCORE!20200421-081623!

**Comment by sblatz** [comment]
Seems to be some larger issues around when the nav bar is shown in PWA. It really shouldn't even be shown in this case.

**Comment by sblatz** [comment]
Demo of problem behavior: 
![pwa 2020-04-22 15_01_32](https://user-images.githubusercontent.com/4400286/80038863-50e9e000-84ab-11ea-9eb5-7b8779719543.gif)

**Comment by Blaze-Thunder** [comment]
Here is a demo on latest nightly which I updated today via play store.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/64011423/80052667-c042ec80-850a-11ea-8c8c-30db7fc49ad9.gif)

**Comment by sblatz** [comment]
@Blaze-Thunder Thanks for posting that! I believe that's a separate issue and I'm working with GV to get it fixed. The PWA one is one I can fix now, though 😄

**Comment by sblatz** [comment]
@Blaze-Thunder In #8768 we will address the website issue. I'm going to use this issue to address the PWA version of the fix. 

(heads up for QA, please base it off of the steps in this demo https://github.com/mozilla-mobile/fenix/issues/10071#issuecomment-618066737)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 5/7 using OnePlus 5T (Android 9).
I've added Web Telegram as a PWA, scrolled the homescreen, no white space displayed.
In Fenix, however, the white space is still displayed, but as Sawyer mentioned [here](https://github.com/mozilla-mobile/fenix/issues/10071#issuecomment-621407957), it will be fixed in a different issue.

**Comment by Blaze-Thunder** [comment]
Will the fix be delivered late? Because I just downloaded latest Fenix nightly released on 5/7 and still I see the white space on telegram PWA.

**Comment by sblatz** [comment]
@Blaze-Thunder can you send me the screenshot of your About Fenix page and a demo of this bug still happening? I'd also recommend reinstalling the Telegram PWA.

**Comment by Blaze-Thunder** [comment]
@sblatz If we install it on homescreen as an app and open, there is no address bar at all. 
We have to open web telegram in Fenix browser itself. This issue happens then. Attached screenshot of my build and the bug demo on the latest build.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/64011423/81363899-ebfdcf00-90d3-11ea-8063-477d12c84dc3.gif)
![Screenshot_20200508-075114](https://user-images.githubusercontent.com/64011423/81363932-0041cc00-90d4-11ea-954b-4f17c994881e.png)

**Comment by sblatz** [comment]
@Blaze-Thunder As I mentioned, the PWA case is fixed, and the website version is not yet. Please follow #8768 for the web based version of this bug as this is a known issue GeckoView is working on.

**Comment by Blaze-Thunder** [comment]
Got it! Thanks!
