### ISSUE TITLE
[Bug]  Allowing screenshot in private browsing is applied only after reopening the browser

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#10087]
## Steps to reproduce
1. Open cnn.com in private browsing.
1. Go to Private browsing and disable "Allow screenshots in private browsing".
1. Return to the page from step 1 and take a screenshot.

### Expected behavior
Screenshots are not allowed.

### Actual behavior
Screenshots are allowed. Closing and reopening Fenix fixes the issue.

### Device information
* Android device: Xiaomi Mi Pad 2 (Android 5.1)- x86, Huawei MediaPad M2 (Android 5.1.1).
* Fenix version: all

**Comment by mcarare** [comment]
@sflorean Can you please check if this still reproduces for you? I have tested on a Huawei P10 (Android 9) and it works as expected. TY!

**Comment by sflorean** [comment]
@mcarare I am only able to reproduce this on Android 5.

**Comment by softvision-miralobontiu** [comment]
I encountered this issue on the 7/28 Nightly build using Samsung Galaxy Tab A6 (Android 5.1.1), and Xiaomi Mi4i (Android 5.0.2).
Closing and reopening the app doesn't fix the issue.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce the issue on the latest RC build 80.1.3 with Samsung Galaxy Tab S6 (Android 9).
Only after force closing Fenix, it allowed me to take screenshots in private browsing.

**Comment by sflorean** [comment]
Tested on latest Nightly build, and the issue is still reproducible on Huawei MediaPad M2 (Android 5.1.1). Followed the same steps as in description.
