### ISSUE TITLE
FNX-3278 ⁃ [Bug] SeekBar thumb in accessibility settings is cut off at minimum value.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#10083]
## Steps to reproduce
Navigate to the Accessibility Settings and turn off Automatic Font Sizing
Move the Font Size slider control to minimum value.

### Expected behavior
The thumb is displayed in full.

### Actual behavior
The thumb is cut off.

<img src = https://user-images.githubusercontent.com/48995920/79857011-ce432100-83d5-11ea-86b3-70e6a7449b04.png width = 45%>

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 4/28 #21190603.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).
