### ISSUE TITLE
Remove fbclid (social media id) etc. from url when improved tracking protection is turned on

### ISSUE THREAD

**Issue by huuhaa** [mozilla-mobile/fenix#10082]
### Why/User Benefit/User Problem
If goal is to improve tracking, I think it's good idea to give option to remove all those social madia sharing related parts from the url. This would also help to share address of webpage you're on without again sharing those social media id parts. Maybe unnecessary, but I like to share plain working link to article without those, also would like those to be cleaned automatically from url.

### What/Requirements
This would require either new option under improved tracking protection or to be implemented in improved tracking protection itself.

### Acceptance Criteria (how do I know when I’m done?)
Include this as a option under improved tracking protection, if cannot be included to improved tracking protection itself.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-111)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807563

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
