### ISSUE TITLE
FNX-3279 ⁃ [Crash] java.util.FormatFlagsConversionMismatchException

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10085]
## Steps to reproduce
1. Set the app language to Romanian.
1. Go to https://www.itisatrap.org/firefox/its-an-attack.html
    1. Expected behavior
Error page displayed.
    1. Actual behavior
App crashes.
[logs](https://github.com/mozilla-mobile/fenix/files/4509867/attackPage.crash.txt)

### Device information
* Android device:  Nexus 9 (Android 7.1.1)
* Fenix version: Beta 4.3.0-beta2

**Comment by mcarare** [comment]
Submitted fix in pontoon: https://pontoon.mozilla.org/ro/android-l10n/all-resources/?status=translated&search=mozac_browser_errorpages_safe_browsing_malware_uri_message&string=196843

**Comment by sv-ohorvath** [comment]
Verified as fixed on Beta 5.0 and Nightly 4/30.
