### ISSUE TITLE
Common text editing shortcuts that work in other browsers and apps do not work

### ISSUE THREAD

**Issue by witcheslive** [mozilla-mobile/fenix#10099]
## Steps to reproduce
Try to use text editing shortcuts such as ctrl+a, ctrl+c, ctrl+home, ctrl+backspace using a physical keyboard or a third party virtual keyboard such as Messagease that allows use of modifier keys

### Expected behavior
Text editing commands should work, such as select all, copy, go to the beginning, delete last word in the above examples. These shortcuts work in every other app I have tried on Android, especially including Chromium

### Actual behavior
Nothing happens, the keystrokes are ignored

### Device information
* Android device: Samsung Note 9
* Fenix version: 4.2.1

**Comment by makotokato** [comment]
@witcheslive
What's you keyboard/IME do you use?  GBoard or Samsung keyboard?

**Comment by makotokato** [comment]
ctrl+backspace should work on Fenix Nightly.

**Comment by kbrosnan** [comment]
Duplicate #3729
