### ISSUE TITLE
FNX-3282 ⁃ Investigate performance of "Open context menu": "Context Menu on bookmarked page"

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#10096]
Break-out issue from https://github.com/mozilla-mobile/fenix/issues/7380. There are two relevant RC:

* GIVEN Fenix on 2018 (low-end|high-end) Android reference
AND a bookmarked page is loaded
WHEN opening the Context Menu
THEN the Context Menu is rendered in less than 100ms
* GIVEN Fenix on 2018 (low-end|high-end) Android reference
AND the Context Menu is open
AND the current website is bookmarked
WHEN the bookmark button is actioned
THEN the edit bookmark UI renders in less than 250ms

**Comment by mcomella** [comment]
The duration to display the menu used on a web page when the page (apple.com) is not bookmarked is **~76.5ms** (10 runs, max 93ms on first click) on the Pixel 2, `geckoNightlyFennecNightly`.

Then I bookmarked the page, closed the tab, force-stopped the browser, and reopened the page (now bookmarked). The duration to display the menu is **~70.2ms** (10 runs, max 81ms on first click).

Therefore, I conclude **there is no performance problem between displaying the menu when the page is bookmarked and when it is not bookmarked.** The code backs this up: `updateCurrentUrlIsBookmarked` is updated asynchronously when the URL changes rather than right before the menu is created: https://searchfox.org/mozilla-mobile/rev/ad4db7e847aff66fb619889edc8833fcdc59ee0e/fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt#376

---

These measurements exclude the animation which is defined to be 200ms (it is set to Android's default `@android:integer/config_shortAnimTime`).

For completion, The menu used on the homescreen and on a browser tab are different but they both utilize the `MenuButton` API. The homescreen menu does not include "is bookmarked" state which this investigation is focused on. The measurements for this menu are ~54.3ms (10 runs).


To measure the duration, I added the following code to a-c:
```kotlin
diff --git a/components/browser/menu/src/main/java/mozilla/components/browser/menu/view/MenuButton.kt b/components/browser/menu/src/main/java/mozilla/components/browser/menu/view/MenuButton.kt
index 0f2c5eff1..deee24d47 100644
--- a/components/browser/menu/src/main/java/mozilla/components/browser/menu/view/MenuButton.kt
+++ b/components/browser/menu/src/main/java/mozilla/components/browser/menu/view/MenuButton.kt
@@ -6,8 +6,12 @@ package mozilla.components.browser.menu.view
 
 import android.content.Context
 import android.content.res.ColorStateList
+import android.os.Handler
+import android.os.Looper
+import android.os.SystemClock
 import android.util.AttributeSet
 import android.view.View
+import android.view.ViewTreeObserver
 import android.widget.FrameLayout
 import android.widget.ImageView
 import androidx.annotation.ColorInt
@@ -18,6 +22,7 @@ import mozilla.components.browser.menu.BrowserMenu.Orientation
 import mozilla.components.browser.menu.BrowserMenuBuilder
 import mozilla.components.browser.menu.BrowserMenuHighlight
 import mozilla.components.browser.menu.R
+import java.lang.ref.WeakReference
 
 /**
  * A `three-dot` button used for expanding menus.
@@ -67,10 +72,29 @@ class MenuButton @JvmOverloads constructor(
         notificationIconView = findViewById(R.id.notification_dot)
     }
 
+    var onClickMillis = -1L
+
+    private class DrawOnce(view: View, private val onClickMillis: Long) : ViewTreeObserver.OnDrawListener {
+        private val viewWeakReference = WeakReference(view)
+        private val uiHandler = Handler(Looper.getMainLooper())
+
+        override fun onDraw() {
+            uiHandler.post {
+                viewWeakReference.get()?.viewTreeObserver?.removeOnDrawListener(this)
+            }
+            android.util.Log.e("lol", "onDraw ${SystemClock.elapsedRealtime() - onClickMillis}")
+            // Thread.sleep(5000)
+        }
+    }
+
     /**
      * Shows the menu, or dismisses it if already open.
      */
     override fun onClick(v: View) {
+        onClickMillis = SystemClock.elapsedRealtime()
+        android.util.Log.e("lol", "onClick MenuButton")
+        v.viewTreeObserver.addOnDrawListener(DrawOnce(v, onClickMillis))
+
         if (menu != null) {
             menu?.dismiss()
             return
```

---

Remaining actions for this issue:
- Is 76.5ms + a 200ms animation fast enough?
- Investigate menu UI & code to determine if anything else might block creation of the menu
- There is no expected difference in performance between bookmarked and not bookmarked menu performance. Do we also want to check if the menu overall appears fast enough on lower-end devices? i.e. run this test on a low-end device

**Comment by mcomella** [comment]
@ecsmyth In this bug, I'm investigating the performance of the context menu on a bookmarked page. As per my comment above, I determined experimentally that there isn't much of a performance difference (within the noise) and saw that the code backs that up in theory. A few questions:
- On a Pixel 2, the time to draw the first frame of the animation that creates the menu is 76.5ms. It is followed by a 200ms animation. Is 276.5ms to display the menu with its animation within our performance guidelines? More generally, how do animations factor into our performance investigations?
- The RC seems focused on the difference between the duration to display the menu when the current page is bookmarked or not. Should I also test for overall duration? If so, I just need to run this on a low-end device given I already have the code for it

**Comment by mcomella** [comment]
@MarcLeclair Can you remove my methodology in https://github.com/mozilla-mobile/fenix/issues/10096#issuecomment-620247344 ?

**Comment by MarcLeclair** [comment]
The first thing that jumps to me is that in my source code I find that `R.id.icon` is the actual 3 dotted icon in a vertical line. The one in the diff shared above seems to me another image.  Secondly, where did you add the code? in `MenuButton.kt` or did you create a new class? It looks good. I'm thinking though that `onDraw` might be called before the animation has started / ended. Thoughts?

**Comment by mcomella** [comment]
> The first thing that jumps to me is that in my source code I find that R.id.icon is the actual 3 dotted icon in a vertical line. The one in the diff shared above seems to me another image. 

I don't understand. `R.id.icon` here references `mozac_browser_menu_button.xml`.

@MarcLeclair This line is unrelated to my change: did you have a concern that it's manipulating the wrong view? I have validated on click is called correctly for this view.

> where did you add the code? It looks good.

`components/browser/menu/src/main/java/mozilla/components/browser/menu/view/MenuButton.kt` – it's listed at the top of the diff. If you prefer, I can send it all up as commits in the future.

> I'm thinking though that onDraw might be called before the animation has started / ended. Thoughts?

I added a `uiHandler.post { THread.sleep(...) }` to ensure it was called at the right time but I'll double-check.

**Comment by mcomella** [comment]
> > I'm thinking though that onDraw might be called before the animation has started / ended. Thoughts?
>
> I added a uiHandler.post { THread.sleep(...) } to ensure it was called at the right time but I'll double-check.

I added `Thread.sleep(5000) directly to `onDraw` (not the uiHandler) and the animation starts and completes (i.e. it continues to animate even though the UI thread is blocked – I assume it's because it's running in hardware) but future UI events don't work until the sleep completes. The same behavior happens if I add the `Thread.sleep` to the pre draw listener. This implies we need to add the draw listener earlier.

However, given we're adding this draw listener from the View's `onClick` handler that causes the menu to appear, I don't think there is an earlier on draw listener that can run so I think we're forced to assume this is the first draw listener for which the menu appears. Given the animation continues despite the UI thread being blocked, it seems like the menu is acting as a special case (i.e. it doesn't stop when the draw listener is called) so it's this is plausible.

**Comment by mcomella** [comment]
I completely missed the RC in the NFR: I updated comment 0 to reflect the RC. Luckily, my initial work in the bug represents the first RC.

**Comment by MarcLeclair** [comment]
So I was asking for `R.id.Icon` since I saw the `R.id...` in the constructor and its not in my local copy of A-C so I thought you had added it 😄  . I just realized that your code will run for any icon button in the `MenuButton.kt`. So yes it looks good to me, i think your comment about the animation also makes sense.

**Comment by mcomella** [comment]
> GIVEN Fenix on 2018 (low-end|high-end) Android reference
AND a bookmarked page is loaded
WHEN opening the Context Menu
THEN the Context Menu is rendered in less than 100ms

### Final measurements
Thanks to MarcLeclair, I noticed a pattern: the first few invocations are slower than the remaining ones: we theorize this is part JIT and OS-level caching and potentially app-level caching (e.g. lazy view inflation). As such, I'll provide measurements across both first-invocation per process lifetime and over several runs across two devices on a bookmarked apple.com. My fenix commit is 4006501d and my a-c commit is 1d04bb79a with the patch from https://github.com/mozilla-mobile/fenix/issues/10096#issuecomment-620247344

GS5
_Curiously I get 2 `onDraw` calls from my patch when I only expect one. The second one behaves like I expect with the P2 so I use that timing. Note: when I disable animations, I only get one `onDraw` call so I assume a different code path is being used_
- First-invocation per process (3 runs): 272.33ms. N.B.: the first run after install was much higher than the others – 467ms to next highest 316ms – so I omitted it as an outlier.
- Multiple runs (10 runs): 176.3ms

Pixel 2
- First-invocation per process (3 runs): 93.33ms
- Multiple runs, ignoring first (10 runs): 71.30ms

These timings ignore the 200ms animation: there is an open question in https://github.com/mozilla-mobile/fenix/issues/10096#issuecomment-620252846 on how we want to handle that.

**Comment by mcomella** [comment]
> First-invocation per process (3 runs): 272.33ms.

I filed https://github.com/mozilla-mobile/fenix/issues/10356 to improve perf because this does not match our release criteria.

**Comment by mcomella** [comment]
> GIVEN Fenix on 2018 (low-end|high-end) Android reference
AND the Context Menu is open
AND the current website is bookmarked
WHEN the bookmark button is actioned
THEN the edit bookmark UI renders in less than 250ms

I opened two PRs with my measurement code: https://github.com/mozilla-mobile/fenix/pull/10361 & https://github.com/mozilla-mobile/android-components/pull/6845. I'm waiting on MarcLeclair for review before I take measurements.

**Comment by mcomella** [comment]
> GIVEN Fenix on 2018 (low-end|high-end) Android reference
AND the Context Menu is open
AND the current website is bookmarked
WHEN the bookmark button is actioned
THEN the edit bookmark UI renders in less than 250ms

### Final measurements
GS5
- First invocation for process (4 runs): 201.75ms (262ms, 181ms, 158ms, 206ms)
- Multiple runs, ignoring first (10 runs): 158.5ms

Pixel 2
- First invocation for process (3 runs): 59.33ms
- Multiple runs, ignoring first (10 runs): 36.7ms

### Conclusion
The max run time on the GS5 exceeds our RC (262ms vs 250ms) but the average is below it so I think we're okay here: no action required.

---

I completed all the action items for me in this issue: waiting on ecsmyth to continue progress.

**Comment by mcomella** [comment]
> On a Pixel 2, the time to draw the first frame of the animation that creates the menu is 76.5ms. It is followed by a 200ms animation. Is 276.5ms to display the menu with its animation within our performance guidelines? More generally, how do animations factor into our performance investigations?

Triage: we determined time-to-complete animations should be included in the release criteria, i.e. this bug does not meet it. @ecsmyth will take an action item to discuss with the UX team to determine see if we should change the animation speed to better fit the release criteria. They said we don't need to keep the issue open. I'm concerned about forgetting about this issue but when we add perf tests/telemetry for the context menu, I'm sure we'll remember so I"m not too concerned: closing.
