### ISSUE TITLE
Customization for the home screen

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10103]
### Why/User Benefit/User Problem
Some users prefer to set the bookmark or history screen as the start screen. It used to be possible in the old design by disabling top sites in the homepage and set bookmarks/history as default. The new design removed this option by making the start screen uncustomizable.

### What/Requirements
An option to make bookmarks or history screen as the start screen.

### Acceptance Criteria (how do I know when I’m done?)
The option to set the start screen to only show bookmarks or history.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-129)

**Comment by yoasif** [comment]
There is interest in this from the beta audience: https://www.reddit.com/r/firefox/comments/g66ui7/what_just_happened_to_firefox_mobile_home_screen/

**Comment by trin94** [comment]
I would love to see home screen customization coming back :+1:

**Comment by jcosentino** [comment]
Is there any traction on this?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813933

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
