### ISSUE TITLE
[UX] Inconsistency in how modals look and behave

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#10105]
Fenix currently shows two kinds of modals:

### Single tab
Accessed from new tab page → Open tabs menu

![](https://user-images.githubusercontent.com/51007/79932985-d9b04e00-84a2-11ea-9fc2-d94ea2fb8d4d.png)

### Multiple tabs
Accessed from new tab page → Open tabs menu

![](https://user-images.githubusercontent.com/51007/79933026-edf44b00-84a2-11ea-9edd-c9c57c4ae5b4.png)

- - -
### Single tab
Accessed from web view → Main menu

![](https://user-images.githubusercontent.com/51007/79933043-f9e00d00-84a2-11ea-98a7-b4eac5b367b5.png)

### Single tab
Accessed from new tab page → Open tabs menu

![](https://user-images.githubusercontent.com/51007/79933295-c18cfe80-84a3-11ea-9aad-3837a09e9250.png)

### Multiple tabs
Accessed from new tab page → Open tabs menu

![](https://user-images.githubusercontent.com/51007/79933069-082e2900-84a3-11ea-9059-a5724754c8a5.png)

- - -
It seems that these modals all look and behave slightly differently from each other:

* Sometimes there’s no page title
* Sometimes the page title is nudged down the page further
* Sometimes the modal uses a Back icon, and sometimes it uses a Close icon
* The padding between the icon and the heading seems to be narrow
* In one of the share sheets, the scrim looks lighter than the other

Paging @betsymi to record in her UI elements documentation, and @topotropic @AmyYLee too see if/how we want to make the design consistent across the board.

My initial recommendation:

* Always have a page title
* Always use the back button (maybe even on a custom tab?)
* Follow the spacing/padding used on sub-pages like Settings, Bookmarks, History
* Use the same scrim style

Anything else?

- - -
# Additional modals
### On site visit
![](https://user-images.githubusercontent.com/51007/80053781-cae49c80-8571-11ea-8c5f-cb3d58932810.png)

### On tap main menu item: _Add to Home screen_
![](https://user-images.githubusercontent.com/51007/80053810-dfc13000-8571-11ea-9727-07878f053f62.png)

### Android system dialog (appears after both modals above, or on tap main menu item: _Install_)
![](https://user-images.githubusercontent.com/51007/80053889-15661900-8572-11ea-8e29-7cc44927f56c.png)

- - -
### Fenix
![](https://user-images.githubusercontent.com/51007/80054124-945b5180-8572-11ea-8a9a-3b0d62693ca8.png)

### Android System (only on first permission request)
![](https://user-images.githubusercontent.com/51007/80055612-2c0e6f00-8576-11ea-8d1f-1c25e510b830.png)

- - -
## 5. Tracking Protection panel
![](https://user-images.githubusercontent.com/51007/80055623-3c264e80-8576-11ea-90fa-6932eea69348.png)

- - -
## 6. Site information panel
![](https://user-images.githubusercontent.com/51007/80055633-40eb0280-8576-11ea-9d5b-11743c0cd5d4.png)

- - -
## 7. Add/install add-on
![](https://user-images.githubusercontent.com/51007/80055659-506a4b80-8576-11ea-99e7-ff8bcc1585e2.png)

**Comment by AmyYLee** [comment]
@brampitoyo Hi, I agree we should ensure consistency. Since @topotropic is working on the tab tray and rethinking the collections UI, I'm guessing this will impact what we currently have.

**Comment by brampitoyo** [comment]
@AmyYLee Based on our discussion earlier today, I agree that unifying the scrim style would be a good, easy first step to take.

Material Design’s default scrim style is `#000000` @ 32%.

Ours seem to be:

- Light theme: Grey (Dark) 90 `#15141a` to Grey (Dark) 10 `#52525e` @ 96% opacity
- Dark and Private theme: Grey (Dark) 90 `#15141a` to Ink 90 `#1d1133` @96% opacity

I know that all our themes feature these colours:

- Almost black or very light grey, infused with blues and violets
- Neutral surfaces that have slightly cool (blues and violets again) temperatures

What if we simplify our scrim style:

- Solid colour, no gradient
- Reduce opacity to match default Material Design value
- Use a cool colour, instead of neutral black: Ink 90 `#1d1133`
    - @ 32% opacity
    - If a darker shade is desired: @ 48% opacity

**Comment by yoasif** [comment]
@brampitoyo you may also want to consider a bug I opened a while ago about the snackbar UI being used for dialogs: https://github.com/mozilla-mobile/fenix/issues/3752

**Comment by AmyYLee** [comment]
@brampitoyo Wondering if this should be broken out into smaller issues.

**Comment by apbitner** [comment]
After chatting with @AmyYLee and @brampitoyo, we would like the modal scrim to be Ink 90 `#1d1133` at 48% for both light and dark themes
