### ISSUE TITLE
[Bug] Some websites cannot switch to desktop mode correctly

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#10104]
## Steps to reproduce
open https://zhidao.baidu.com/

### Expected behavior
https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly.2020.03.10/latest
In this version, the desktop mode can be displayed normally, and later versions cannot be displayed normally.

![Screenshot](https://user-images.githubusercontent.com/3154109/79932396-03a44900-8480-11ea-95c5-eb7c3221df8e.png)UNITO-UNDERSCORE!2020-04-22-09-45-16-874!UNITO-UNDERSCORE!org mozilla fe!

### Actual behavior
Starting from the March 14th version, it is not possible to switch to desktop mode normally, just changed the viewport

![Screenshot](https://user-images.githubusercontent.com/3154109/79932425-0f900b00-8480-11ea-8687-ce7f29bcf3f9.png)UNITO-UNDERSCORE!2020-04-22-09-45-16-873!UNITO-UNDERSCORE!org mozilla fe!

### Device information
* Android device: ?
* Fenix version: ?

**Comment by BranescuMihai** [comment]
Dev note: There's a method in `GeckoEngineSession` called `toggleDesktopMode`, where we set user agent and viewport. To investigate whether the user agent is not set correctly, on Chrome seems to work ok

**Comment by mcarare** [comment]
The desktop version is not shown for samples-browser or Fennec (current play store version 68.10.0) either.

**Comment by Mugurell** [comment]
This was very hard to pinpoint since it seemed to work on a device but not on another and also changed to working after updating the latest Nightly.

I think the issues is because of the User-Agents used by Gecko and based on the above I think there's an experiment going in GV about user agents.
Not sure how many users would be affected by this or not..

This should be fixed upstream, for which I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1653296

**Comment by bifleming** [comment]
Blocking work in current sprint.

**Comment by bifleming** [comment]
Requested update from GV. The Bugzilla bug has been assigned to WebCompat, and Amedyne has requested an update from them.

**Comment by Mugurell** [comment]
This should be fixed 🥳

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/22 with Samsung Galaxy Note 10 (Android 10).
