### ISSUE TITLE
FNX-3290 ⁃ [Bug] crash on clicking just to the left of the first tab in overview

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10108]
## Steps to reproduce
Open a few tabs
Open overview
Click just to the left of the first tab. Do this a few times

### Expected behavior
Nothing

### Actual behavior
Crash

### Device information
* Android device: Asus Zenfone 
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment]
Seems to be related to #10091

**Comment by mcarare** [comment]
Same as #10091.
