### ISSUE TITLE
[Bug] History items under label "Last 24 hours" are actually "since midnight"

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#10107]
Screenshot below was taken at 12:05am, and all of the browsing history occurred in a span of about 10 minutes. However, "last 24 hours" section only has visits which occurred after midnight.

![](https://user-images.githubusercontent.com/465422/79951227-25c0ab80-842d-11ea-9b28-d44509067aa2.png)

**Comment by grigoryk** [comment]
Three options here:
- we could simply rename this label to "Today"
- if, somehow, "last 24hrs of history" is a desirable slice of history, we can adjust our filtering/queries
- we can do some larger rework of this UI to include more useful categories

FWIW, this is what Desktop has in its "All History" UI:
<img width="195" alt="Screen Shot 2020-04-22 at 12 14 29 AM" src="https://user-images.githubusercontent.com/465422/79951814-3e7d9100-842e-11ea-83ea-937dfdff0acc.png">

**Comment by ekager** [comment]
Cc @betsymi do you want to take a look at this?

**Comment by brampitoyo** [comment]
It seems like “Today” and “Yesterday” gets us closer to a more accurate description – and makes Fenix consistent with desktop – but I’ll leave the final decision to @betsymi.

**Comment by AmyYLee** [comment]
@betsymi - Follow-up?

**Comment by betsymi** [comment]
Sorry, I missed this. `Today` and `Yesterday` is good.

**Comment by sim031999** [comment]
Hello, I would like to work on this!

**Comment by prabhat3108** [comment]
@sim031999 are you working on this or should pick it up?

**Comment by rafalopilowski1** [comment]
@ekager Can I work on this issue?

**Comment by ekager** [comment]
Anyone can pick this up!

**Comment by joc-a** [comment]
I'll pick this up!

**Comment by joc-a** [comment]
#15415

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201009`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20201010-000047](https://user-images.githubusercontent.com/51314259/95551711-fb32d100-0a13-11eb-81ea-cfa7600b04dd.png)
