### ISSUE TITLE
[Fennec/Focus parity] "Show/block web fonts" option

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10102]
[Reported by a beta user](https://www.reddit.com/r/firefox/comments/g5ry8h/rant_at_the_android_preview/).

### Why/User Benefit/User Problem
As a user, I would like to reduce my bandwidth usage and increase my privacy by blocking web fonts. 

### What/Requirements
An option to block web fonts, like in Fennec or Focus. If this were done at a "Site permissions" level, it would be more powerful than the feature in those browsers. That way, I could block web fonts on all sites except those that extensively use icon fonts for example.

### Acceptance Criteria (how do I know when I’m done?)
I am able to block web fonts. Bonus if I can block them by default and enable exceptions on certain sites.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-127)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807115

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
