### ISSUE TITLE
FNX-3296 ⁃ [Bug][a11y] TalkBack-Addons-Snackbar not read when multiple add-ons installed.

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10117]
## Prerequisites
* Have TalkBack enabled
    1. Steps to reproduce

1. Open browser and go to 3 dots Menu/Settings/Add-ons.
1. Install an add on by tapping on the "+" icon.
1. Tap on "Add" button from the notification for adding the add-on.
1. Install the second add-on by tapping on the "+: icon.
1. Tap on "Add" button from the notification for adding the second add-on.
    1. Expected behavior
The "Successfully installed "name of the installed add-on". " snackbar is correctly read by talkback.
    1. Actual behavior
When installing in the same session of a second add-on the snackbar is not read by talkback.
    1. Device information

* Android device: Sony Xperia Z5 (Android 7)
* Fenix version: Nightly 4/22

Note:
It seems to be that it is reproducible when the installation of add-ons is done in the same session of the app.

**Comment by mcarare** [comment]
Closing, as his is no longer an issue, since the confirmation is not shown in a Snackbar anymore.
