### ISSUE TITLE
FNX-3293 ⁃ [Bug] The text selector is barely visible on Light/Dark theme on the login capture panel

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10113]
## Steps to reproduce
1. Launch Fenix.
1. Set the theme on Light or Dark.
1. Access any website and attempt to login.
1. On the `Save login screen` tap on the username or password field and observe the text selector.
    1. Expected behavior
The text selector should be visible.
    1. Actual behavior
The text selector is barely visible on Light/Dark theme on the login capture panel
    1. Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 22/4.**

![20200422-150119](https://user-images.githubusercontent.com/42831109/79980582-fb620300-84ab-11ea-9f9a-c0df2d112693.gif)

**Comment by ValentinTimisica** [comment]
@AmyYLee @brampitoyo can you please tell me the cursor (text selector) color for each of the light/dark themes and private mode?

**Comment by ValentinTimisica** [comment]
I used the following colors for the cursor:
- light theme: #312a64
- dark theme: #9059ff
- private mode: #9059ff

You can check the video from the [PR](https://github.com/mozilla-mobile/fenix/pull/11022).

@brampitoyo @AmyYLee is this ok?

**Comment by AmyYLee** [comment]
> I used the following colors for the cursor:
> 
>     * light theme: #312a64
> 
>     * dark theme: #9059ff
> 
>     * private mode: #9059ff
> 
> 
> You can check the video from the [PR](https://github.com/mozilla-mobile/fenix/pull/11022).
> 
> @brampitoyo @AmyYLee is this ok?

This looks good to me. Thanks!

**Comment by ValentinTimisica** [comment]
Reopening this for QA.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly with Google Pixel 4 XL (10).
Note that the text selector color is displayed correctly according to the [comment](https://github.com/mozilla-mobile/fenix/issues/10113#issuecomment-635800007).
