### ISSUE TITLE
FNX-4718 ⁃ [UX] Decide how back stack should be preserved

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1012]
Currently we have an ever growing stack of pages that piles up every time a user clicks on a link, clicks on the tab button (to go "home"), switching to private mode, etc.

It's possible there is a bit of disconnect between how we internally think of the "home" screen, and how users see it as a "tab switcher" (due to it being a tab icon). Because of this we've had user requests for the back button to take you to your previous tab [when on the home screen](https://github.com/mozilla-mobile/fenix/issues/517).

However, as an engineer, I view this as a "home screen" and thus don't think a back button should ever take me back to the browser view (home is where we start the user, why would back take me forward?). 

Some UX clarification on how this should operate would be great. Perhaps we want to change the "tabs" icon back to a "home" icon for more clarification? I'm sure there are other solutions that would allow us to all align our thinking on this.

**Comment by ekager** [comment]
Also see #570 for more feedback about our home/tabs combined view. If we separated out a new "tabs" view while browsing and "home" was really a "root" navigation, this would probably make the navigation a bit cleaner.

**Comment by topotropic** [comment]
We open a new tab when someone 
- conducts a search from home
- taps on + on home to open a new tab
- opens a bookmarks from Library
- opens a history entry from Library 

Within a tab people can open new links or search for new things, this "tab history" can be navigated by using the Android back button.

I agree that Home is root and using the back button results in backing out of Fenix.

![image(1)](https://user-images.githubusercontent.com/353960/55503783-ad375300-564f-11e9-94d3-247fee500e9f.png)

**Comment by sblatz** [comment]
Thanks, @topotropic! I will verify we're using this flow and if we aren't I will create a follow-up ticket for addressing it 😄

**Comment by sblatz** [comment]
Filed follow-up: https://github.com/mozilla-mobile/fenix/issues/1361. 

@topotropic feel free to close this if you're done :)

**Comment by topotropic** [comment]
Thanks, @sblatz!
