### ISSUE TITLE
FNX-3298 ⁃ [Bug] Heavy janking and slow, stuttery scroll on NYT Amp page

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10121]
## Steps to reproduce
1. Navigate to https://news.google.com/articles/CAIiEAri_DpDDtLZ-UIU98k0rEMqFwgEKg8IACoHCAowjuuKAzCWrzww5oEY?hl=en-US≷=US&ceid=US%3Aen
1. Scroll down page

### Expected behavior
Smooth scroll following finger. 

### Actual behavior
Janky, stuttering scrolling. This is actually better on Fennec on this device. 

Profile: https://perfht.ml/3arXjzl

### Device information
* Android device: Moto G XT1031
* Fenix version: latest nightly

**Comment by mcomella** [comment]
@jeanygong Can we file a platform perf bug for this?

**Comment by jeanygong** [comment]
I filed a bugzilla for this https://bugzilla.mozilla.org/show_bug.cgi?id=1637751

**Comment by yoasif** [comment]
@jeanygong Is there any reason I don't have access to the bz? I filed this bug after all. :)

**Comment by mcomella** [comment]
We're tracking in BZ: no reason to leave this open. It looks like the Fenix team is also tracking this but I don't think it's very actionable for them so I'm going to close it to make less noise for them. 🤞
