### ISSUE TITLE
[Bug] Elements do not have correct colors

### ISSUE THREAD

**Issue by MechJM** [mozilla-mobile/fenix#10123]
## Site with issue and any steps to reproduce
Go to imdb.com and click on a poll. For example:https://m.imdb.com/poll/gNgwwqkyx-A/?ref_=m_nm_po

### Expected behavior
The imdb poll icon, the title of the pool and its description should have a white background. 

### Actual behavior
The elements mentioned previously have a black and a white background, making the title and the first lines of the description hard to see. 
![IMG](https://user-images.githubusercontent.com/56487084/80028273-c7eb9c80-84dc-11ea-8e46-d0402b5f6585.jpg)UNITO-UNDERSCORE!20200422!UNITO-UNDERSCORE!152616!

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No. 

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
No. 

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No. 

### Device information
* Android device: Xiaomi Mi 9T
* Fenix version: Nightly 200422 16:13

**Comment by kbrosnan** [comment]
I only get this behavior when ads are blocked on the page. I can reproduce on Desktop. This is not a Firefox bug. It is a minor website bug.
