### ISSUE TITLE
As a User I want to submit additional information about a crash

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#1013]
This story is about letting users submit additional information to us when a crash report is pending. 

On Desktop we ask how the crash happened (what was the user doing) and even for an optional email address so that we can contact the user to ask more questions. This data is opt-in.

Two examples of how this could work are:

* Google's bug reporter as described on https://developer.android.com/studio/debug/bug-report  is a good example how this UI could look - this will allow a user to give more context to what they were doing when the crash happened.
* Sentry has a 'feedback' feature for Android where they can prompt for additional information before sending the crash report. I am unable to find a good reference to the documentation.

Will require some UX work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-158)

**Comment by bbinto** [comment]
We need to figure out if we want this to the MVP, because that will not only include UX and Eng implementation but also how we handle requests coming in etc.

**Comment by lime124** [comment]
@vesta0 do you want to try to include this for Q3 and group it with #907?

Either way, this is bigger than a bug and is a feature request requiring some design thinking so removing the need ux label.

**Comment by kbrosnan** [comment]
This seems unrelated to #907 which is a dashboard for monitoring stability. This is about allowing users to provide more context around what they are doing when they crash.

**Comment by lime124** [comment]
@kbrosnan if we gather more info about a crash when a person reports it, that would help vesta understand more about the types of crashes. i would also assume it would be reflected in the dashboard in some manner? perhaps i'm totally wrong - feel free to disregard!

**Comment by vesta0** [comment]
I will leave this for @liuche and @sarentz to think about, in terms of what additional information will help the ENG team better diagnose and resolve crashes.

**Comment by st3fan** [comment]
I think the Sentry SDK now also has a feedback mechanism where it can optionally show UI to ask the user what happened. Needs some investigation.

**Comment by vesta0** [comment]
@liuche please determine next steps for this issue and remove 'Feature request` :)

**Comment by lime124** [comment]
if we need any UI for people to add info we'll have to put this in our ux backlog.

**Comment by vesta0** [comment]
This is an ENG requirements not a product requirement so I will defer to @liuche

**Comment by kbrosnan** [comment]
Moving to bz-1811650
