### ISSUE TITLE
FNX-3301 ⁃ Inconsistent background color in Privacy mode in Settings

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#10130]
## Steps to reproduce
1. open Firefox
1. switch to Privacy mode
1. go to Settings

### Expected behavior
Settings are shared between normal and privacy mode. They should have one black background.

### Actual behavior
Background color depends on mode, which is confusing.

### Device information
* Android device: S7 / Android 8
* Fenix version: Nightly 22 Apr

**Comment by sblatz** [comment]
This is intentional and was decided about a year ago. :)
