### ISSUE TITLE
option to reopen private tab as a normal tab

### ISSUE THREAD

**Issue by JVariance** [mozilla-mobile/fenix#10132]
### Why/User Benefit/User Problem
As of today you have to copy-paste every private tabs' address to move it to the (unprivate) home screen.

### What/Requirements
For now I could imagine three ways to manage the described problem.

1. Move link(s) via share menu.
1. Add option on tab swipe (as it behaves with deleting tabs) to move private tab to the home screen.
1. Longpress on tab with possible multi selection and move tab(s) over a menu.

### Acceptance Criteria (how do I know when I’m done?)
When I'm able to move one or more tabs from private mode to (unprivate) home screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-162)

**Comment by s-ankur** [comment]
Duplicate? of #5170

**Comment by WebworkrNet** [comment]
From my personal point of view, such a function should be available across platforms, i.e. independent of the mobile Android platform.

**Comment by pwd-github** [comment]
Given that the development team seem to be so against this idea, would it be possible to have this function available via extensions? 

The feature native to Fenix that opens all links in a private tab has been a godsend for user privacy. But if a user happens to use the browser a lot, it becomes an inconvenience, with requiring users to copy and paste links or log in repeatedly. Some work has clearly happened in regards to tabs (inactive tabs), so if the user can take control themselves with an extension, we can deal with the reluctance to fix this issue ourselves.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807545

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
