### ISSUE TITLE
FNX-3306 ⁃ [Bug] 2FA with NFC hardware key doesn't work.

### ISSUE THREAD

**Issue by kmazurek244** [mozilla-mobile/fenix#10135]
## Steps to reproduce
Login to Google account with hardware key NFC Yubikey with 2FA.

### Expected behavior
Browser waits for hardware nfc interaction and reads output from nfc. 

### Actual behavior
Goes to hw interaction and then immediately to error page. 

### Device information
Samsung S10+ with latest firmware (G975FXXU4CTC9). 

* Android device: yes
* Fenix version: 75.0.0-beta.6

**Comment by Dunexus** [comment]
Isn't this part of https://github.com/mozilla-mobile/fenix/issues/1340 ?

**Comment by eliserichards** [comment]
Closing in favor of #1340.
