### ISSUE TITLE
FNX-3310 ⁃ [Bug] Changing site permissions from the site info panel doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10142]
## Steps to reproduce
1. Go on permission.site.
1. Allow access to all: notification, camera, mic, location
1. Open the site info panel by tapping the lock icon.
1. Tap on the "Allowed" buttons to change all  to "Blocked"
1. Close the panel and tap on all permissions again.
    1. Expected behavior
All return as blocked.
    1. Actual behavior
The blocked permissions are not returned correctly, the panel info changes by itself back to Allowed.
This only seems to happen on permission.site. Even after a page refresh.
It works fine on mapquest or talky.io

![20200423](https://user-images.githubusercontent.com/4037709/80095110-14cc8300-8570-11ea-94ac-9f4322d32c9a.gif)UNITO-UNDERSCORE!143513!

### Device information
* Android device: Pixel 4 (Android 10), HTC Desire (Android 6.0.1)
* Fenix version: Nightly 4/23

**Comment by eliserichards** [comment]
Possibly related to #10145, #10233, #10142, #8626

**Comment by Amejia481** [comment]
@sv-ohorvath would you mind double checking? Thanks :)

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/7** with **Google Pixel 4 XL (10).**

![20200507-114147](https://user-images.githubusercontent.com/42831109/81275169-f54a5580-9059-11ea-9a26-5f81e101fe91.gif)
