### ISSUE TITLE
[Bug] Camera and microphone running notifications are kept after closing the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10145]
## Steps to reproduce
1. Go to talky.io/room
1. Turn on camera and mic.
1. Close the app, removing it from recent apps.
    1. Expected behavior
Cam & mic notifications are removed from the notification bar.
    1. Actual behavior
The notifications are still displayed. Tapping them re-launches the app. The camera/mic are not streaming anymore (you can check by joining the chat room on another device)
    1. Device information

* Android device: Pixel 4 (Android 10), HTC Desire (Android 6.0.1)
* Fenix version: Nightly 4/23, Beta 4.3.0

**Comment by eliserichards** [comment]
Related to #8626.

**Comment by sflorean** [comment]
This is still reproducible on Beta 86.0.0-beta.1 with Huawei P40 (Android 10).
