### ISSUE TITLE
[Bug] Text selection toolbar is positioned over navigation bar

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10147]
## Steps to reproduce
1. Go to a site. I used wikipedia.org/wiki/mozilla
1. Long tap on a word in order to trigger the text toolbar.
1. Tap on "Select All" option.
    1. Expected behavior
The text toolbar does not overlap the navigation bar.
    1. Actual behavior
The text toolbar overlaps the navigation bar.
    1. Device information

* Android device: Sony Xperia Z5 (Android 7)
* Fenix version: Nightly 4/23

Note:

* With Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9) the issue doesn't reproduce.
**GIF**
![20200423-175210](https://user-images.githubusercontent.com/49859863/80116361-8adfe280-858e-11ea-8c3a-5dbfc07445e3.gif)

**Comment by Mugurell** [comment]
I think this is by now resolved.
