### ISSUE TITLE
[Bug] Extensions effect custom tabs but cannot be controlled

### ISSUE THREAD

**Issue by unixandria-xda** [mozilla-mobile/fenix#10143]
## Steps to reproduce
Open a custom tab
Notice an extension needing changed, eg uBlock is breaking a page (* * 3p-script block does that a lot :grinning: )
Go to 3 dot menu
Notice that extensions aren't listed and you have to fully open the browser to make modifications

### Expected behavior
Extensions can be controlled in custom tabs

### Actual behavior
Extensions effect custom tabs but cannot be controlled

### Device information
* Android device: OnePlus 7T, OxygenOS 10.0.9
* Fenix version: 200422

**Comment by s-ankur** [comment]
Related to #9503

**Comment by kbrosnan** [comment]
Closing as a duplicate #9503
