### ISSUE TITLE
FNX3-13679 ⁃ closing "About Fenix" should remove "About Fenix" from session

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1015]
### Steps to reproduce
1. open "About Fenix"
1. press the back button of your device
1. repeat steps 1 and 2
1. repeat steps 1 and 2 again
1. press the home button

### Expected behavior
"Current Session" shows only one "About Fenix" tab.

### Actual behavior
"Current Session" shows three "About Fenix" tabs.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 2b00d1120f5a2dbeb531ccca13c9127feef3c088

**Comment by vesta0** [comment]
Related to #513
