### ISSUE TITLE
FNX-3321 ⁃ [Bug] white screen during page load

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#10158]
My system theme is dark, fenix theme is dark but while loading a dark web page it shows white scree n. While it's disregarded daytime, at nite it burns my eyes out.

![ScreenRecord-2020-04-23-18-33-16](https://user-images.githubusercontent.com/14617699/80135117-6ee93a80-85a8-11ea-86dc-925b2991ca02.gif)

Fenix 4.3.0 (build #21082025)

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/6313
