### ISSUE TITLE
FNX-4721 ⁃ [Meta] Help Section for Users

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1016]
Have a place where user can get help, find more information about the product

### Why/User Benefit/User Problem
* Make user feel safe and secure in case they have a question about our product

### Acceptance Criteria (Added by PM. For EPM to track when a Meta feature is done)
-UX completed
-User stories completed
-Strings written and approved
-QA completed
-Localization done

### What / Requirements (Added by PM and Eng Manager)
Similar to other of our products.

* Direct help button in 3dot menu - going to SUMO Fenix page
* Settings>Mozilla>Help

**Comment by bbinto** [comment]
During our user story meeting on March 21, @shorlander, @topotropic and @mheubusch we agreed that this is a good start for the help section - we will aim for feature parity with our other products and believe that's also how people will know where to find help

**Comment by bbinto** [comment]
Follow-up work after MVP here: #1116

**Comment by bifleming** [comment]
@vesta0 do we not have any dev work to do for MVP?

**Comment by vesta0** [comment]
@lime124 @shorlander please let me know if there is UX required for this or if we are good to just direct users to SUMO page?

**Comment by vesta0** [comment]
Closing this after confirming with @mheubusch about linking to a Sumo page captured here: #1116
