### ISSUE TITLE
FNX-3325 ⁃ Update tab tray multiselect mode

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#10163]
### Why/User Benefit/User Problem
I want to have a consistent experience when multi-selecting list items so that I don't have to adjust to various ways of selecting things.

### What/Requirements
Update multi-select on tab tray to match how it works for History or Bookmarks views. 

### Acceptance Criteria (how do I know when I’m done?)
Multi-select on tab tray to save open tabs to a Collection is consistent to how multi-select on History/Bookmarks view works

https://github.com/mozilla-mobile/fenix/issues/2735

### Flow
https://share.goabstract.com/3704167e-a3eb-4387-aef1-a2f7ce7c1045?mode=design&sha=b1ac1f6f1656e55debc8e8cacbf265644ad16e4f

**Comment by gabrielluong** [comment]
We probably want to bake this ability into the AC Tabs Tray component. We will investigate it some more on the AC side.

**Comment by jonalmeida** [comment]
Using the [RecyclerView selection library ](https://developer.android.com/reference/androidx/recyclerview/selection/package-summary)to implement this feature might be helpful.

**Comment by LaurentiuApahideanSV** [comment]
I have tested the issue on Firefox Preview Nightly 200727 (Build #22090608) using a OnePlus 6T (Android 9) and Huawei P Smart (Android 9). The tabs can be selected in the tabs tray however the "Save tabs to collection" button is missing.

**Comment by topotropic** [comment]
> The tabs can be selected in the tabs tray however the "Save tabs to collection" button is missing.

yes! that's correct, we currently can't display a button in the tab tray. You should see a "[collection icon] SAVE" option in the tab tray top bar though. Thanks!

**Comment by ekager** [comment]
Closing as verified.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Beta 80.0.0-beta.1 (Build #2015754977).
### Device used:
- Huawei MediaPad M3 (Android 7.0)

**Comment by abodea** [comment]
Verified as fixed on **Fenix RC 80.1.0** with **Google Pixel 4 XL (11).**
