### ISSUE TITLE
FNX2-13086 ⁃ [Bug] Top sites favicon unexpectedly disappeared

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#10165]
## Steps to reproduce
* Pin a top site using the 3-dot menu when the page is loaded
* Go to homescreen: observe favicon for top site is present
* (after an unknown duration) Return to homescreen

### Expected behavior
Favicon is still there

### Actual behavior
Favicon is missing and replaced with placeholder letter favicon

### Device information
* Android device: P2
* Fenix version: 75.0.0-beta.6

**Comment by sflorean** [comment]
Tested on Nightly 6/11 and got different behavior for the same site:
- Pocket: opened the already pinned top site link, and added again to the home screen and the favicon is missing and replaced with placeholder letter favicon.
- Ebay, Bing doesn't have a favicon displayed. 
- In some cases, only the icon is displayed without text. 

Devices: Huawei MediaPad M2 (Android 5.1.1), Nokia 6(Android 7.1.1).
![Screenshot_20200612-135654](https://user-images.githubusercontent.com/58466444/84496224-3e26a700-acb5-11ea-813c-e5a68caacbf7.png)
![Screenshot_2020-06-12-12-01-28](https://user-images.githubusercontent.com/58466444/84496289-5c8ca280-acb5-11ea-8e22-a4fb0282f714.png)

**Comment by Mugurell** [comment]
I think mozilla-mobile/android-components#7266 should've resolved this issue also.
Please verify if this is still reproducing or we can close it.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 7/20 with OnePlus 5T (Android 9), Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
