### ISSUE TITLE
Analyze dex load time telemetry

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#10161]
We added the dex load time telemetry https://github.com/mozilla-mobile/fenix/issues/8803. Unfortunately, our analysis is blocked because the `startup-timeline` ping is not being ingested: https://bugzilla.mozilla.org/show_bug.cgi?id=1631491 Once we're unblocked, we should analyze the probe using the original purpose of the probe: is the dex load time negligible across a wide range of devices?

---

Note that the `createAppContext` call is slower in Fenix compared to fennec, via https://github.com/mozilla-mobile/fenix/issues/8979

**Comment by Dexterp37** [comment]
@mcomella please kindly comment on the bug mentioning that this is blocking your work :-)

Also, please note that pings are being ingested, but they are not being processed into tables (as far as I know).

**Comment by mcomella** [comment]
This appears to be unblocked now.

**Comment by mcomella** [comment]
I started an analysis in this dashboard https://sql.telemetry.mozilla.org/dashboard/startup_timeline_framework_start-10161-

However, I discovered some outlier data: the most concerning is that ~3.2% of our start events had the framework take more than 60s to start. This makes me question the implementation and I think we should investigate that before continuing the analysis.

Note to self: when complete, I think we should archive these analyses in our permanent doc collection, kind of how data science can link to a report.

**Comment by mcomella** [comment]
I'm concerned we're not looking at a representative sample of users: e.g. are people intentionally throttling fenix in extreme scenarios? are we looking at representative hardware? etc.

That being said, in the interest of "perfect is the enemy of the good", I wonder if we can use the data as is anyway and take it with a grain of salt? Across all recorded metrics, 69.6% of opens take between 0ms to 200ms (assuming we have minimal absurdly fast outliers) with 3.2%. With that in mind, I wonder if we can assume this is generally a fast operation. We can take this one step further and look by device (e.g. perf on G5 and P2 would give us a better understanding of the numbers – there might be some really slow/fast devices out there).

I'm going to place in Waiting for now because this is less important than #15296. Maybe I'll consult with MarcLeclair and see if the perfect-enemy-good approach seems reasonable because then we can finish this analysis soon.

**Comment by mcomella** [comment]
From the dupe:
> In the the following two profiles we're seeing a big difference in createAppContext and handleBindApplication total running times:
>
>Fennec: https://profiler.firefox.com/public/327373a230b04f58d0936fb60478bb9a84d5ef30/
>Fenix: https://profiler.firefox.com/public/c78aeffd46f820c8e7337c20b4e16bd104cd556e/
>
>Let's investigate if this is consistently true and find out why.

**Comment by mcomella** [comment]
Triage: ecsmyth suggested that we should look at the count of clients who have inflated times to see if this is expected (I wonder if this is related to robolectric or UI testing...? ecsmyth also suggested it could be glean telemetry errors). We should **make a minimal investigation to understand the impact before deciding the investment.** We'll leave this in triage until we clean up the backlog enough to know what to do with it.

**Comment by mcomella** [comment]
I wonder if dividing the data into quantiles like [this query](https://sql.telemetry.mozilla.org/dashboard/fenix-awesomebar-performance?p_w57759_days=30&p_w57759_org_mozilla_fenix=org_mozilla_fenix&p_w57760_days=30&p_w57760_org_mozilla_fenix=org_mozilla_fenix&p_w57761_days=30&p_w57761_org_mozilla_fenix=org_mozilla_fenix&p_w57762_days=30&p_w57762_org_mozilla_fenix=org_mozilla_fenix&p_w57763_days=30&p_w57763_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57764_days=30&p_w57764_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57765_days=30&p_w57765_org_mozilla_fenix=org_mozilla_fenix) would be sufficient to analyze this. It seems like a good way to visualize the data. The query to put data into quantiles seems pretty intense though so not something I could whip up quickly.

**Comment by mcomella** [comment]
The data is now accessible in GLAM so this analysis should be easier.

---

I did a small analysis on the `clock_ticks_per_second` metric for nightly over a week and the number of distinct clients where `clock_ticks_per_second = 100` is 1650x `!= 100`. Queries (not reviewed):
- [clock_ticks_per_second = 100](https://sql.telemetry.mozilla.org/queries/78618/source)
- [clock_ticks_per_second != 100](https://sql.telemetry.mozilla.org/queries/78627/source)

 I think this means **we can discount clients where `clock_ticks_per_second != 100`**, meaning we can remove this probe and `startup_timeline_framework_start_secondary` but perhaps we should re-run the query on Beta or Release data before doing so.

**Comment by mcomella** [comment]
For `clock_ticks_per_second`, we may also wish to double-check that clients only ever send one value: i.e. that the value never changes because that's an assumption I hold.

**Comment by mcomella** [comment]
We're removing this in https://github.com/mozilla-mobile/fenix/issues/20596 so there's no opportunity to analyze this anymore.
