### ISSUE TITLE
FNX-3334 ⁃ Edit logins - duplicates and save criteria

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#10173]
### Acceptance Criteria
* [x] disallow duplicate usernames - `getPotentialDupesIgnoringUsername(login)` in `SyncableLoginsStorage`
* [x] disallow save when password is empty OR dupe is detected
  * [x] gray out save button 
  * [x] button is non-clickable

**Comment by eliserichards** [comment]
See WIP linked PR for updates

**Comment by liuche** [comment]
Hey @eliserichards how is this going? I want to get this into Nightly for testing early, or else we should just skip Release and do a fast-follow.

**Comment by eliserichards** [comment]
## For QA
There are still a few bugs with this depending on the next nightly build of AC (https://github.com/mozilla-mobile/fenix/issues/12651)

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet.
Tested on the 7/20 Nightly build with Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
I was able to save the same password on the same page, following these STR:
1. Go to twitter.com, fill in valid credentials, save them.
2. Verify that the credentials are saved in Logins and passwords.
3. In Logins and passwords, disable the Autofill option.
4. Go to Settings - Delete browsing data, check only Cookies and tap on the Delete browsing data.
5. Close Fenix.
5. Reopen Fenix, and go to the twitter.com page and refill the credentials from step 2.
6. The Save prompt is displayed again and the credentials are saved again - duplicate.

<img src="https://user-images.githubusercontent.com/40694158/87919320-46c28800-ca80-11ea-872f-b3e9daddc7b0.jpg" width="300" height="550" />

**Comment by eliserichards** [comment]
That is a bug with Save and Autofilling credentials. I will file that as a separate ticket. This issue is only applicable for editing a saved login.

**Comment by softvision-miralobontiu** [comment]
Hi @eliserichards,

I've tested again on Beta 80.0.0-beta.1, and on the 7/30 Nightly build with Samsung Galaxy Tab S6 (Android 9), with twitter.com account.

**Using the following STR:**
1. Go to twitter.com and sign in with valid credentials.
2. When asked to save the credentials, tap on "Save".
3. Log out from twitter.com.
4. Delete the auto-filled credentials.
5. Sign in again on twitter.com, with the same credentials.

**Actual results:**
The prompt is displayed again, The user can save again the same credentials. Fenix doesn't recognize the duplicate. There is no grayed out "Save" button (non-clickable).

**Comment by ekager** [comment]
Thanks @softvision-miralobontiu  - we pulled those STR into https://github.com/mozilla-mobile/fenix/issues/12751
