### ISSUE TITLE
FNX-3332 ⁃ Undo closed tab

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#10171]
### Why/User Benefit/User Problem
A user can bring back accidentally closed tabs and it'll be in line with the **desktop UX of Firefox**.

### What/Requirements
There is an entry named "Undo closed tab" in the 3 dot list on Fenix tab overview.
The 3dot menu needs to be always visible and the click on "Undo closed tab" will bring back **every closed tab** from the current session.

### Acceptance Criteria (how do I know when I’m done?)
A user closes 2 tabs and clicks on "Undo closed tab" which brings back the last tab and another click brings back the next tab in the closed tab list.

It needs an internal temp list which is able to store the closed tabs in chronical order.

**Comment by buttercookie42** [comment]
See also #2486.

**Comment by mikeGolf08** [comment]
> See also #2486.

I had a different point of view for implementation but actually a list would be a lot more convenient in comparison to my recommendation.

I close this issue now but the UX team definitely has to take a look at this!

**Comment by Poopooracoocoo** [comment]
Could you reopen this? This is still a feature request and is not a duplicate of that other issue.
