### ISSUE TITLE
FNX-4722 ⁃ Wide, short tab previews give little useful visual info about tab's contents

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#1017]
Fenix has got snapshots in tabs now on the Home screen. The snapshots are slices, very wide but very short top to bottom. They don't give much useful visual information about the page. It's hard to recognise at a glance which tab is which.

For example on Fennec my BBC News page shows about the top 50% of the page, the BBC logo, NEWS etc. Fenix's slice is about 15%, just the chins of two guys accused of a crime. Similarly on github I see a slice, meh, not much useful, four cryptic lines of text.

Is there a better solution than the very wide, short tab slices? I think it would be a start to show the top of the page rather than a middle part, but even then a 15% slice is not much to distinguish one tab from another.

e.g. could you put two tabs side by side like in Fennec and make the tabs much more square and less like wide thin slices. Ugly? You bet. Instead of having text above tab snapshot, make the snapshot cover the cover the whole of the region area and write the URL text over the top of the tab snapshot? makes text harder to read.   Blah blah.

Fennec:-
![Screenshot](https://user-images.githubusercontent.com/40568887/54359522-b89feb80-465a-11e9-9261-c554c1db26ff.jpg)UNITO-UNDERSCORE!20190314-130713!UNITO-UNDERSCORE!Firefox Nightly!

Fenix:-
![Screenshot](https://user-images.githubusercontent.com/40568887/54359510-b2aa0a80-465a-11e9-87ac-c523a6ba6189.jpg)UNITO-UNDERSCORE!20190314-131038!UNITO-UNDERSCORE!Fenix!

**Comment by lime124** [comment]
Hello! We're in the process of making some changes to the concept. I'm going to put this in the icebox for now and when those designs are complete we can revisit this issue to see if it's sill an issue. Thanks!

**Comment by mheubusch** [comment]
we are revisiting open tab cards and will create new stories
