### ISSUE TITLE
FNX-3335 ⁃ Error states for saved logins

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#10172]
Cleanup keyboard actions on the edit login fragment and finalize error states (including dupe usernames).

### For QA :tada:
The PR has more details about what this card does and does not cover. Both this and #10173 are  follow-ups to #9693.

## Acceptance Criteria
* [x] password cannot be empty/null
* [x] username **can be** empty/null
* [x] open keyboard when clicking into editable text fields (this should work)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200622 from 6/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ Username **can** be empty/null
✔️ Password **cannot** be empty/null
✔️ Open keyboard when clicking into editable text fields (this should work)

► Screenshot
![rsz_img_20200622_104507](https://user-images.githubusercontent.com/51314259/85262664-c4da4180-b476-11ea-8944-4b63c509f5d1.jpg)
