### ISSUE TITLE
FNX-3344 ⁃ [Bug] Zooming in on a web page will make the address bar appear

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#10189]
## Steps to reproduce
1. Go to any website that allows scrolling;
1. Scroll down the page until the address bar disappears;
1. Zoom in the page.
    1. Expected behavior
The address bar should not appear when zooming.
    1. Actual behavior
The address bar appears when zooming in on a page.
    1. Device information

* Android device: Huawei MediaPad M3 lite 10 (Android 7.0)
* Fenix version: Preview Nightly 200424 (Build #21150608) GV: 77.0a1-2020042209354

![zoom](https://user-images.githubusercontent.com/50983519/80220904-33547c00-864d-11ea-8f1c-9819dff33cec.gif)

**Comment by Mugurell** [comment]
After https://bugzilla.mozilla.org/show_bug.cgi?id=1627737  and https://github.com/mozilla-mobile/android-components/issues/2930 this should not reproduce anymore.
Please help verify.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200514 (Build #21350608) using a Huawei MediaPad M3 lite 10 (Android 7.0).
