### ISSUE TITLE
FNX-3339 ⁃ [Bug]Can't open youtube by tapping on his icon from the "Open tabs" list if a video was playing

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#10180]
## Steps to reproduce
1. Open youtube.com;
1. Play a video;
1. Go to the tab drawer;
1. Tap on the youtube icon from the "Open tabs" list.

### Expected behavior
The youtube page is opened.

### Actual behavior
The youtube page doesn't open.

### Device information
Android device:

* LG G7 fit (Android 8.1);
* Samsung Galaxy Note 8 (Android 9);
* Google Pixel (Android 10).
* Fenix version: Firefox Preview Nightly 4/24 #21150607.
* Possible a regression from #10091.
* Also, after reopening the tab and going to the tab drawer, the issue disappears.
![20200424](https://user-images.githubusercontent.com/40264165/80185074-6a5a6b80-8614-11ea-957a-94df4d9f09bb.gif)UNITO-UNDERSCORE!100539!

**Comment by mcarare** [comment]
This needs a bit of investigation. The play button, even set to gone still shows up in view hierarchy:
<img width="379" title ="captured with layout inspector" src="https://user-images.githubusercontent.com/48995920/80192178-7861b980-861f-11ea-9d4f-6ab015addbba.png">

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that the issue is fixed using the latest version of Firefox Preview Nightly 4/26 #21171807.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9).
