### ISSUE TITLE
FNX-3349 ⁃ [Bug] Behavior of "back button" is inconsistent when focus is on address bar.

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#10197]
Steps to reproduce. 
Note : I've chosen the search terms "spacex" and "blue origin" just as an example. 
Screen recording - https://www.youtube.com/watch?v=GhLiNPAbw_c
1) Search for "spacex"
2) Now tap the address bar and search for "blue origin"
3) Now tap the address bar again and click the back button (happens at 0:15 in the video)

Expected result -
The "this time search with" menu disappears and goes back to the "blue origin" search results page. 
Actual result -
Sometimes it goes back to the "blue origin" search results page. Sometimes it goes back to the "spacex" search page. Video shows the latter (happens more rarely than the former). 

To reproduce, repeat Step 3 multiple times and note the outcome. 
Version Number : 
Nightly 200424 06:01 (Build #21150608)
39.0.20200422203205, 5491e8f4e
GV: 77.0a1-20200422093542
AS: 0.57.0

**Comment by sv-sdeiac** [comment]
Hi, thanks for your report.
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 4/27 #21180608.

Devices:
- LG G7 fit (Android 8.1);

### Notes
- Not reproducible using Samsung Galaxy Note 8 (Android 9) and Google Pixel (Android 10).

**Comment by Sgt-Miller** [comment]
Hi, can this be made higher priority please? Let's say you are filling a long form and you accidently tap the address bar (easy to happen when it's at the bottom). This small mistake pretty much resets whatever you typed into the form because it will try to go to previous page if you tap the back button..

**Comment by ekager** [comment]
This sounds like it will be fixed by #11871 in the next nightly

**Comment by ekager** [comment]
Closing for #11866
