### ISSUE TITLE
When clicking on the plus button, replace "this time search with" menu with a list of bookmarks/recently visited sites.

### ISSUE THREAD

**Issue by supersonic71** [mozilla-mobile/fenix#10198]
### Why/User Benefit/User Problem
Rarely do most of us change search engines. Even if I want to search wikipedia, I usually google/ddg "search term" + "wiki". That space would be better used by showing a list of top visited sites or bookmarks (like on firefox desktop). 

### What/Requirements
Change suggestion list of empty address bar to how it works in desktop version 

### Acceptance Criteria (how do I know when I’m done?)
When user presses the "plus" button, show topvisited/recentlyvisited/bookmarks in the list.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-238)

**Comment by Poopooracoocoo** [comment]
What does your issue mean now? Fenix has changed quite a bit.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807737

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
