### ISSUE TITLE
[Bug] Long Pressing a tab to add to collections takes you to the bottom

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#10199]
## Steps to reproduce
Create lots of tabs, say 1, 2, 3, ..., 20
Long Press tab 1 (the tab at top of list) to add to collection

### Expected behavior
Screen remains near the first tab

### Actual behavior
Screen scrolls down to the bottom most tab

### Device information
Lenovo K8 Note

* Android device: 8
* Fenix version: Nightly 200424 06:01 (Build #21150608)
39.0.20200422203205, 5491e8f4e
GV: 77.0a1-20200422093542
AS: 0.57.0

**Comment by sv-sdeiac** [comment]
Hi, confirming that this issue is reproducible using the latest version of Firefox Preview Nightly 4/27 #21180608.

Devices:
- LG G7 fit (Android 8.1);
- Samsung Galaxy Note 8 (Android 9);
- Google Pixel (Android 10).

**Comment by topotropic** [comment]
@Sgt-Miller Is this still relevant with the introduction of the dedicated tab tray? Thanks!

**Comment by Sgt-Miller** [comment]
@topotropic even with new tab tray, choosing "save to collection" goes to the bottom of tab list.  

Not a very important issue though

**Comment by topotropic** [comment]
Is this still relevant with the introduction of the new multi-select view? @sv-sdeiac

**Comment by topotropic** [comment]
I can't reproduce this – the tab tray stays in the same position as is after selecting tabs and saving them to a collection. Please feel free to re-open if this is still an issue. Thanks!
