### ISSUE TITLE
FNX-3347 ⁃ [Bug] Private browsing setting can re-enable add-on

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10195]
## Prerequisites
Ublock Origin should be installed and enabled
"Run in private browsing" should not be disabled
Switch to Private Browsing 

## Steps to reproduce
1. Navigate to the Add-ons manager and open uBlock
1. Enable "Run in private browsing" and quickly disable uBlock

### Expected behavior
Ublock should be disabled 

### Actual behavior
Ublock is re-enabled automatically

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: Nightly Build #21150608 from 4/24

### Notes
► Video
![20200424-170116](https://user-images.githubusercontent.com/51314259/80225418-b7a9fd80-8653-11ea-94fe-c5fc15e76f66.gif)

❗ Bumped into an isolated case where it **gets disabled two times**.

## Steps to reproduce
1. Disable "Run in private browsing" 
1. Quickly disable uBlock and exit to the Add-ons manager
1. Open again uBlock

►Video
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51314259/80225903-62222080-8654-11ea-8e5f-8cc2e6510b9a.gif)

Related to #6123

**Comment by Amejia481** [comment]
@AndiAJ  @psymoon landed a related patch, would mind retesting? :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 200504 from 5/4`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200504-112516](https://user-images.githubusercontent.com/51314259/80948326-8622f600-8dfa-11ea-90b0-d54b63e8ebd7.gif)
