### ISSUE TITLE
FNX-443 ⁃ Make search suggestions a user opt-in option in private mode

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1019]
I believe it will make the private mode a little more private. Even Chrome disables search suggestions on private mode. Fenix should follow, probably.

### User Story
As a user, I want the option to disable search suggestions in private mode only.

### Acceptance Criteria
* [ ] Move search suggestions setting to bottom of list
* [ ] Add setting to disable search suggestions in private mode while still getting search suggestions in regular mode. 
* [ ] Add contextual hint (see mock) for private mode search suggestions

Mocks: https://app.goabstract.com/share/e4322cfc-9036-4fbc-b417-5ac7df581b19?mode=design&sha=9fe9a001eabfa8ac0898d9f298791ead964230a5

- - -
EDIT (@sblatz):

* Search suggestions are disabled by default in private mode
* I get the option to toggle them on in the search screen (as an onboarding type message as seen in Focus)

Let's make sure we also consider how this conflicts with the current toggles in the search screen that are global settings.

**Comment by vesta0** [comment]
@bbinto what do you think?

**Comment by yoasif** [comment]
I think it'd be better to have a preference for private mode search engine, a la Brave with  the same toggle we have already for showing search suggestions working independently depending on the browsing mode.

**Comment by bbinto** [comment]
How about we do this similar to what we've done in Focus?

First time, users enter a search term in private browsing, show a prompt to enable/disable search suggestions, and this choice can be toggled under settings > search.

![Screenshot_20190320-123840](https://user-images.githubusercontent.com/122897/54702534-715ba400-4b0d-11e9-8dba-67ec9d5bc802.png)

/cc @topotropic and @brampitoyo

**Comment by joebloggs7657** [comment]
Definitely retain search suggestions or at most give an option to turn off. Private browsing is more so about keeping data private locally on the device rather than (ineffectively) ensurelibg private data handling by websites.

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by julienw** [comment]
As a +1, I was very surprised to get search suggestions in private mode, which means that what I type goes to the search engine. This isn't the case in Firefox/Android, and as far as I know there's even no way to turn it on in that browser.
I'd be super happy to be able to disable this in Fenix!

**Comment by vesta0** [comment]
@lime124  can we re-use the Focus designs for this one? Attached above.

**Comment by vesta0** [comment]
Discussed with the UX team. We can re-use the Focus design for the notification but UX will spend 1-2 hours on wireframe for toggle/setting.

**Comment by lime124** [comment]
FYI - Verdi very recently worked on some settings for private mode on desktop. 

Also this ticket (as sblatz points out in comment 0) will cover a bit of redesign on the search page to organize/group the various settings/options and make it more clear what is doing what.

**Comment by AmyYLee** [comment]
Here is the flow. @jpfaller to review/approve copy.

![Screen Shot 2019-10-04 at 4 56 19 PM](https://user-images.githubusercontent.com/5992746/66346112-6c323b00-e91f-11e9-9619-ce8d358169ab.png)

**Comment by AmyYLee** [comment]
UPDATE: We might want to add another item into this screen as we re-org Settings. Stay tuned.

**Comment by vesta0** [comment]
@AmyYLee should we also have a prompt like the one below for the very first time user searches in private browsing?

![image](https://user-images.githubusercontent.com/42752644/66534847-8d448880-eae5-11e9-9c14-bcffe2d8c09a.png)

**Comment by AmyYLee** [comment]
> @AmyYLee should we also have a prompt like the one below for the very first time user searches in private browsing?
> 
> ![image](https://user-images.githubusercontent.com/42752644/66534847-8d448880-eae5-11e9-9c14-bcffe2d8c09a.png)

Yes we should include that. I'll add it into the spec. @jpfaller Can you review the copy above and see if we need to revise it for Fenix?

**Comment by lime124** [comment]
on track to be completed by end of day tomorrow - though dependent on strings.

**Comment by AmyYLee** [comment]
HI, 
Here is the spec. It's ready for engineering with the exception that the strings need to be reviewed by @mheubusch in this portion (see screenshot below)

<img width="394" alt="Screen Shot 2019-10-11 at 1 17 52 PM" src="https://user-images.githubusercontent.com/5992746/66671393-df8ec200-ec29-11e9-8e94-ef974b9ea0bc.png">

Spec:
https://share.goabstract.com/e4322cfc-9036-4fbc-b417-5ac7df581b19?mode=design&sha=55df3f5a5598c442a978d0268b7574deb0c7ca7d

**Comment by mheubusch** [comment]
Recommended text: 
Allow search suggestions in private sessions?
Firefox Preview will share everything you type in the address bar with your default search engine. Learn more

**Comment by mheubusch** [comment]
@vesta0 Added the needs:sumo label for support with updating the copy at https://support.mozilla.org/en-US/kb/how-search-firefox-preview with a note that search settings now allow you to enable and disable search suggestions in private browsing when you have have enabled them in normal browsing. @AmyYLee can provide the settings panel showing this update.

**Comment by AmyYLee** [comment]
Screens for Sumo:

![Settings Main](https://user-images.githubusercontent.com/5992746/66682695-c72ba100-ec43-11e9-9780-f19b9934d4ab.png)
![Settings - Search Suggestions (Disabled)](https://user-images.githubusercontent.com/5992746/66682696-c7c43780-ec43-11e9-8c00-684e276a4613.png)
![Search Suggestions Prompt](https://user-images.githubusercontent.com/5992746/66682697-c7c43780-ec43-11e9-8392-2306cbd05758.png)
![Settings - Search](https://user-images.githubusercontent.com/5992746/66682698-c7c43780-ec43-11e9-9492-665cc28c3378.png)

**Comment by AmyYLee** [comment]
@sblatz Final Spec: https://share.goabstract.com/e4322cfc-9036-4fbc-b417-5ac7df581b19?mode=design&sha=9fe9a001eabfa8ac0898d9f298791ead964230a5

**Comment by sblatz** [comment]
@AmyYLee This is what the current screen looks like:


<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/66766769-c1aca180-ee63-11e9-9c62-245e2f0973cf.png">

Should we move "show search suggestions" to the bottom of the list to accommodate that checkbox?

**Comment by AmyYLee** [comment]
@sblatz Hi, let's stick to toggles because it's the move obvious in terms of On/Off. I've also added header just above the toggles to break up the two sections. Please move search suggestions to the bottom of the list to accommodate the checkbox. Thanks!
 
![Settings - Search@2x](https://user-images.githubusercontent.com/5992746/66941491-f90e8000-f014-11e9-869a-1dbd51be5b74.png)

**Comment by mcarare** [comment]
@AmyYLee Do we want to show the hint the first time the user opens the search in private, or after he starts typing (the "Fill link from clipboard" disappears at that moment)? 
For the first option, do we want to show it below or above "Fill link from clipboard"?
TY!

**Comment by AmyYLee** [comment]
@mcarare Hi, can we have this show the first time the user starts typing? This is the same as Focus. Thanks

**Comment by softvision-miralobontiu** [comment]
Hi all!
Verified that:
- when searching in private mode, the user is asked to allow or not search suggestions in private mode,
- when search suggestions are denied, there are no more suggestions in private mode,
- users can modify seeing search suggestions in private mode from Settings-Search.
Tested on the latest Nightly build 11/25 with Google Pixel 3 (Android Q), and Huawei P9 Lite (Android 7).

**Comment by bepvte** [comment]
![Screenshot_20191210-103724_Firefox Nightly](https://user-images.githubusercontent.com/8226605/70543929-3a18a180-1b39-11ea-93f4-1f804e8600ef.jpg)
(Uncropped screenshot)
Ive noticed the spacing for this features setting is a bit cramped.

Didn't know if this should go in a new issue or not.

Model: Samsung S10+ (SM-G975U)
Nightly build id: 72.0a1 20191202091209

**Comment by brampitoyo** [comment]
@bepvte Would you be able to file a new issue for this?

My first suggestion, then, is to check whether the spacing of this Search sub-section matches the spacing of all other item under Settings (in general).

If they both match, then it’s not an issue. If they don’t match (ie. somehow this sub-section looks more cramped than other pages within Settings), then we’ll fix it.

Thanks!
