### ISSUE TITLE
[Bug] Unable to browse from webpage

### ISSUE THREAD

**Issue by xudongzheng** [mozilla-mobile/fenix#10207]
## Steps to reproduce
1. Visit https://www.bouncingdvdlogo.com/
1. Click the address bar and browse to another page

### Expected behavior
It's expected that the browser takes me to the new page.

### Actual behavior
The browser is stuck on that page.

### Device information
* Android device: 10
* Fenix version: Firefox Preview 4.3.0 Build 21082025

**Comment by LittleAngelwings** [comment]
Seems to be the same issue like this: https://github.com/mozilla-mobile/fenix/issues/10208
