### ISSUE TITLE
[Bug] Dynamic toolbar not displayed while the page is loading

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#10200]
## Steps to reproduce
1. Go to espn.com or cnn.com. 
1. Scroll the page while it is still loading.
1. Pay attention to the navigation bar.

### Expected behavior
The navigation bar is displayed until the page loads completely, even when the user is scrolling the page down.

### Actual behavior
The navigation bar is not displayed.

### Device information
* Android device:  Nokia 6 (Android 7.1.1), Samsung Galaxy Note10 (Android10).
* Fenix version: Nightly 4/24.

![20200424](https://user-images.githubusercontent.com/58466444/80234223-72d89380-8660-11ea-8c31-a6c1939b2e9e.gif)UNITO-UNDERSCORE!191523!

**Comment by softvision-miralobontiu** [comment]
This issue is reproducible on the Beta 86.0.0-beta.1 build with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by abodea** [comment]
This issue is reproducible on the **Beta 87.0.0-beta.4** build with **Samsung Galaxy Tab A6 (Android 5.1.1).**
