### ISSUE TITLE
FNX-4724 ⁃ [Bug] SettingsFragment IllegalStateException crash

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#10204]
IllegalStateException androidx.fragment.app.Fragment in getViewLifecycleOwner
fatalCan't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8055326/?query=Can%27t%20access%20the%20Fragment%20View%27s%20LifecycleOwner%20when%20getView()%20is%20null%20i.e.,%20before%20onCreateView()%20or%20after%20onDestroyView()

**Comment by danielzgtg** [comment]
This happens to me on "200424 06:01" when I tap the overflow menu item labeled "Settings". This doesn't happen to me on "200427 06:01"

**Comment by ekager** [comment]
Great, glad it's fixed for you in the latest Nightly :) I will close this but continue to monitor the crash stats
