### ISSUE TITLE
FNX-3356 ⁃ [Bug] Some websites don't allow browsing away

### ISSUE THREAD

**Issue by axaxs** [mozilla-mobile/fenix#10208]
## Steps to reproduce
Visit time.gov
Wait a few seconds
Enter a URL or search term into the address bar

### Expected behavior
Search for or visit text in address bar

### Actual behavior
Time.gov site reloads

### Device information
Oneplus 7T, Firefox preview with ublock origin

* Android device: ?
Yes, Android 10
* Fenix version: ?
4.3.0

**Comment by LittleAngelwings** [comment]
Seems to be the same issue like this: https://github.com/mozilla-mobile/fenix/issues/10207

**Comment by eliserichards** [comment]
Closing as duplicate of #10207
