### ISSUE TITLE
FNX-4725 ⁃ there cannot be a swipe-up from bottom gesture

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#1021]
(I also posted this on bugzilla) 

I noticed that although Fenix has the bar at the bottom, it's making the exact same mistake as "Chrome Home": it has a swipe up gesture. Not only does this make scrolling down a frustrating experience (users will accidentally swipe up Fenix's options), but Android now has a swipe-up gesture for going to the home screen, just like newer iPhones, and you'll have a a situation where people will end up on the home screen when the meant to swipe-up Fenix's options and vice versa. Lastly, surely Androids guidelines say apps should avoid having a swipe-up from the bottom gesture because of this issue, so Fenix would be going against Androids guidelines...

If you have a moment, please read this issue on Chrome Home https://bugs.chromium.org/p/chromium/issues/detail?id=726437

I even saw this issue being brought up on Android news sites: from Android Police "Since our screens are only getting bigger, it makes sense to put the most used UI elements right at the bottom of our devices. It also makes sense that a swipe up reveals further actions, **although I fear this might interfere with Android 9 Pie's gesture navigation**." 

https://www.androidpolice.com/2019/03/13/mozillas-upcoming-browser-fenix-packs-a-new-ui-and-fundamental-changes-to-tab-management/

**Comment by lime124** [comment]
Hi! I've added this to our gesture issue to look at the gestures holistically for our release. Thus I am going to close the issue. Thanks for taking the time to provide these details and links that we can use as we design this work. You can find that issue here: #176

**Comment by willfs84** [comment]
Sorry but I had to come back to this because I just saw a post on the Android subreddit about this issue and someone even mentioned Fenix in the comments... 
https://www.reddit.com/r/Android/comments/bw04i5/swipe_up_should_be_reserved_for_the_system_ui/

**Comment by willfs84** [comment]
Just coming back to this because Fenix/Firefox Preview still has the exact same swipe-up problem as Chrome Home does (detailed in the link below). How will Mozilla tackle this issue? Firefox Preview cannot ship like... this https://bugs.chromium.org/p/chromium/issues/detail?id=726437
