### ISSUE TITLE
FNX2-13097 ⁃ [Bug] Task Switcher has multiple instances of Firefox

### ISSUE THREAD

**Issue by ra-hardy** [mozilla-mobile/fenix#10210]
## Steps to reproduce
1. In Firefox, create a home screen shortcut for a website
1. Launch the website from the home screen shortcut
1. Launch the website from the same home screen shortcut

### Expected behavior
In the app's task switcher there should be one instance of Firefox.  Or alternatively there should be one per shortcut and one for the main Firefox instance, so two instances in total as step 3 would reuse the existing instance.

### Actual behavior
There are 3 instances of Firefox in the task switcher.  One is the main Firefox instance, and two for the home screen shortcut.

### Device information
* Android device: Samsung Galaxy S10, Android 10, One UI 2.1
* Fenix version: 75.0.0-beta.6

**Comment by eliserichards** [comment]
Hi @ra-hardy! What website were you visiting on these instances?

**Comment by ra-hardy** [comment]
I can replicate with any site, for example these all produce the same results
https://www.theguardian.com/uk
https://www.theregister.co.uk/
https://news.sky.com/

**Comment by BranescuMihai** [comment]
Tried this out with Samsung S10 and Oneplus 7T Pro, doesn't seem to reproduce anymore. Can QA please retest?

**Comment by LaurentiuApahideanSV** [comment]
I have tested the issue on Firefox Preview Nightly 200727 (Build #22090608) using a OnePlus 6T (Android 9) and Huawei P Smart (Android 9) but was unable to reproduce it.

**Comment by LaurentiuApahideanSV** [comment]
I have tested the issue on Firefox Preview Beta 80.0.0-beta-1 using a OnePlus 6T (Android 9) and Huawei MediaPad M3 (Android 7) but was unable to reproduce it.
