### ISSUE TITLE
FNX-3360 ⁃ [Bug] Firefox crash when switching to tab from home screen shortcut

### ISSUE THREAD

**Issue by ra-hardy** [mozilla-mobile/fenix#10213]
## Steps to reproduce
Close any tabs and instances of Firefox in the phone's task switcher

1. Launch Firefox from a home screen shortcut
1. Launch Firefox from the main app icon
1. Click the tab showing (which is for the website from the shortcut from step 1)

### Expected behavior
Switch to the home screen 'instance' of Firefox.  Or maybe, the tab shouldn't show at all as it's not a tab but a separate instance.

### Actual behavior
Firefox crashes

### Device information
* Android device: Samsung Galaxy S10, Android 10, One UI 2.1
* Fenix version: 75.0.0-beta.6

**Comment by kbrosnan** [comment]
Please provide a crash log by following the directions at https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by eliserichards** [comment]
Closing in favor of #10211
