### ISSUE TITLE
FNX-3361 ⁃ swipe to change tab

### ISSUE THREAD

**Issue by FernandoMiguel** [mozilla-mobile/fenix#10215]
Chrome has this amazing feature that allows to swipe on the url window and switch between open tabs.

could this be considered as a future enhancement for firefox?

**Comment by Dunexus** [comment]
This is tracked by https://github.com/mozilla-mobile/fenix/issues/3481 as part of the [gestures meta](https://github.com/mozilla-mobile/fenix/issues/176)

**Comment by Turbotomate** [comment]
Very good idea. This improves the User Experience by far and saves so much time when switching between often used tabs. 
You should also mark this as a Feature Request.

**Comment by kbrosnan** [comment]
Closing as a duplicate.
