### ISSUE TITLE
FNX-3365 ⁃ Change theme by time

### ISSUE THREAD

**Issue by cathaysia** [mozilla-mobile/fenix#10219]
### Why/User Benefit/User Problem
Fenix's black theme is ok, I like it very much. But my phone have not the black mode, which means I must change by hands.

### What/Requirements
Could add "change theme by time" option?

### Acceptance Criteria (how do I know when I’m done?)
It is not a necessary option, but i hope you can consider this and add it in todo list.

**Comment by kbrosnan** [comment]
Duplicate #4236
