### ISSUE TITLE
Add smart bookmarks

### ISSUE THREAD

**Issue by andreisilv** [mozilla-mobile/fenix#10218]
To reproduce:

* Create a bookmark
* Write in location text box:
  * place:queryType=1&sort=8&maxResults=5

It should query bookmarks and display in a folder like manner the resulting list with the top 5 bookmarks. This is a desktop feature, but would be nice to also have in phone.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-265)

**Comment by kbrosnan** [comment]
This may not be simple as the history/bookmarks store on Android is not an exact copy of the Desktop Places databases. 

Better documentation about the feature behaviors https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Places_query_URIs

**Comment by onemahon** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811815

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
