### ISSUE TITLE
[Bug] Cannot autofill password on some sites

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#10222]
## Steps to reproduce
open https://pan.baidu.com/
（The mobile version cannot add a password, you can add an account on the desktop version, and then sync to the mobile version for testing. And I change general.useragent.override to firefox desktop useragent string.）

https://i.imgur.com/eYgIoAZ.mp4

### Expected behavior
If the password is saved, the username and password should be filled in automatically

### Actual behavior
Only the username is automatically filled

![Screenshot](https://user-images.githubusercontent.com/3154109/80298410-aa5d5200-87be-11ea-9b57-1d670551aa0c.jpg)UNITO-UNDERSCORE!2020-04-26-12-58-23-985!UNITO-UNDERSCORE!org mozilla fi!
![Screenshot](https://user-images.githubusercontent.com/3154109/80298411-ab8e7f00-87be-11ea-9642-a60c050de8c4.jpg)UNITO-UNDERSCORE!2020-04-26-12-58-30-463!UNITO-UNDERSCORE!org mozilla fi!
![Screenshot](https://user-images.githubusercontent.com/3154109/80298412-ac271580-87be-11ea-9b94-d9df0b04d44d.jpg)UNITO-UNDERSCORE!2020-04-26-12-58-40-513!UNITO-UNDERSCORE!org mozilla fi!
![Screenshot](https://user-images.githubusercontent.com/3154109/80298413-acbfac00-87be-11ea-82ec-0fc7c68ec38b.jpg)UNITO-UNDERSCORE!2020-04-26-12-58-47-547!UNITO-UNDERSCORE!org mozilla fi!

**Comment by eliserichards** [comment]
Hi @lindongbin! Can you add the steps that you took to reach this point? 
(e.g. 1. navigate to www.example.com, 2. click on X, ...)

**Comment by hakkikaancaliskan** [comment]
Hi @eliserichards 
I have similar(?) issue if helps #7742
And it's not labeled as Feature:Logins

**Comment by lindongbin** [comment]
> 
> 
> @lindongbin does the password field autofill on desktop?

no, but #5551 can solve the problem indirectly
