### ISSUE TITLE
FNX-3388 ⁃ [Feature request] Hold the Tabs-icon for opening a new tab

### ISSUE THREAD

**Issue by Turbotomate** [mozilla-mobile/fenix#10226]
I thought of a faster way to open a new tab and found, that long-pressing the tabs-icon has no function yet.
Other Browsers, like Samsung Internet, let you open a new tab by holding this icon. This would be a nice addition to the User Experience.

**Comment by topotropic** [comment]
This feature is available in the latest nightly. I'll go ahead and close the issue. Feel free to open a follow-up one if it doesn't align with your expectations. Thanks!
