### ISSUE TITLE
FNX-4726 ⁃ Dependency substitution for android-components

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#1022]
This will allow us to easily develop against a local checkout of `android-components`.

Currently blocked on a-c moving to AndroidX (https://github.com/mozilla-mobile/android-components/issues/842). Also, see similar r-b issue: https://github.com/mozilla-mobile/reference-browser/issues/365

**Comment by grigoryk** [comment]
We _should_ be mostly unblocked here. A-C needs to move to AndroidX but IIUC nothing is in the way of that.

**Comment by sblatz** [comment]
@grigoryk is this still waiting on anything?

**Comment by sblatz** [comment]
I think this is covered by using `mavenLocal`: https://mozac.org/contributing/testing-components-inside-app

**Comment by grigoryk** [comment]
Here are pretty precise instructions on what needs to happen here: https://github.com/mozilla-mobile/reference-browser/issues/365#issuecomment-450453145

Nothing should be blocking this work, just needs to be tested.

**Comment by grigoryk** [comment]
We've had a very traumatic past few weeks trying to do tight iterations across three levels of the stack (a-s -> a-c -> fenix), and not having this done yet has been such a pain. So let's bump this up in priority.

**Comment by grigoryk** [comment]
Actually, I don't know what Fenix labels really mean, so I'll re-add it. In any case, this will be done as part of an a-c sprint.

**Comment by pocmo** [comment]
@grigoryk: @jonalmeida and I both tried that in RB (earlier draft: https://github.com/mozilla-mobile/reference-browser/pull/815) and the result has been horrible. Mostly because:
* 1) You can't get rid of it anymore. Android Studio completely ignores if you remove/reset the substitution.
* 2) It will also do the reverse and add all the app projects into the AC project which has been confusing and unexpected.

**Comment by grigoryk** [comment]
@pocmo i've ran into the same behaviour, and couldn't work around it. So instead went for automating a local publication workflow.

**Comment by masi456** [comment]
I think this does not work for windows, since you have to call "gradlew.bat", not "gradle".
