### ISSUE TITLE
[Bug] Top toolbar interferes with scroll axis locking (horizontal)

### ISSUE THREAD

**Issue by yump** [mozilla-mobile/fenix#10221]
## Steps to reproduce
1. Set toolbar to "top"
1. Pinch-to-zoom, or visit a desktop website that is wider than the viewport, so that horizontal scrolling is possible.
1. Begin scrolling horizontally, so the axis lock should engage.
1. Without lifting your finger, try to scroll vertically.

### Expected behavior
No vertical scrolling should be possible, because the axis should be locked to horizontal, which was the primary direction of the first movement.

### Actual behavior
A limited amount of vertical scrolling is possible, up to the point that the toolbar is completely shown or completely hidden.  Because of this, if you try to horizontally scroll a long line of text, the text jumps up and down.

### Device information
* Android device: Nokia 6.1, Android 10
* Fenix version: 75.0.0-beta.6 (Build #2015735819)

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 4/27 #21180608.

Also, the vertical scrolling is working correctly using top toolbar.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).

**Comment by yump** [comment]
I made a mistake, my device is also running Android 10.

When you say vertical scrolling is working correctly, do you mean you could not reproduce #10220?  I added a screenshot to show what to look for.

**Comment by sv-sdeiac** [comment]
Hi @yump, no, I wanted to say that the vertical scrolling is blocking the right/left movements, which is expected to happen.

**Comment by karlcow** [comment]
This could be a duplicate 
https://github.com/webcompat/web-bugs/issues/50115

**Comment by ChristianCiach** [comment]
I found this bug while searching for a reason for the "scroll axis locking". I want to give Firefox on Android a try again, seeing that there have been many changes over the last few years.

That being said, this "scroll axis locking" is driving me crazy. There is just no way I can ever get used to it. I often zoom into images and then scroll around to see different parts of the zoomed in image. Locking the axis when scrolling makes this very cumbersome.

Is there a way to disable scroll axis locking?

**Comment by yump** [comment]
I re-tested this on the latest nightly.  Horizontal axis lock with top toolbar works... better, now, but has bizarre behavior where, after the axis lock is engaged, aggressive vertical scrolling can partly release the lock, so that only enough vertical scrolling to (un)hide the bar is possible, or the bar gets stuck half-in, half-out of the top edge of the screen.

https://user-images.githubusercontent.com/2214413/109458746-0918db00-7a23-11eb-9a75-8f1486195f51.mp4

**Comment by yump** [comment]
@ChristianCiach On my device, the lock doesn't engage if I start a pan with a large diagonal motion.  I agree that isn't reliable, though.

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 SM-A530F Android 9 Nightly 93.0a1 2021-08-30

**Comment by SoftVision-LorandJanos** [comment]
This issue is not reproducible with the latest Nightly 99.0a1 (Android 11).
Device used: Oppo Reno 6 (Android 11).
