### ISSUE TITLE
FNX-4730 ⁃ [Bug] Ublock-Origin-Icon is cut off

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#10236]
## Steps to reproduce
None. Just look at your Add-ons.

### Expected behavior
It not to be cut off.

### Actual behavior
See Pictures.

### Device information
* Android device: Samsung Galaxy S9
* Fenix version: 4.3.0

![2](https://user-images.githubusercontent.com/59611881/80378085-a9debd00-888b-11ea-8aa3-4a0ca7029aa4.jpeg)
![3](https://user-images.githubusercontent.com/59611881/80378086-aa775380-888b-11ea-9098-01202e926c5a.jpeg)

**Comment by cadeyrn** [comment]
This is already fixed in the Nightly version.

**Comment by Amejia481** [comment]
Thanks for filing the issue, but I agree with @cadeyrn!
 In nightly, now we even using a different background colour.

![image](https://user-images.githubusercontent.com/773158/80384074-6a57a700-8872-11ea-850c-3d238fab3133.png)
