### ISSUE TITLE
FNX-4729 ⁃ [Bug] Permissions not always saved on first run

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10233]
## Steps to reproduce
1. Clear app data
1. Go to webcamtests.com / mapquest.com / permission.site
1. Turn on location / camera
1. Allow permissions and check if they work.
    1. Expected behavior
Location / camera should work.
    1. Actual behavior
There are sometimes errors that location / camera can't be detected on the first run. If you restart the app, you need to allow permissions again and then they'd start working.
This is especially reproducible on webcamtests.com
    1. Device information

* Android device: HTC Desire 820 (Android 6.0.1)
* Fenix version: Nightly 4/27

**Comment by eliserichards** [comment]
Closing in favor of #10142

**Comment by sv-ohorvath** [comment]
@eliserichards I'm not sure these are duplicates. In this bug, location and camera are giving errors on the first attempt to turn them on, not related to changing them after.
