### ISSUE TITLE
FNX-4728 ⁃ why top sites can not sync ?

### ISSUE THREAD

**Issue by kzwr** [mozilla-mobile/fenix#10231]
### Why/User Benefit/User Problem
When i use Firefox Preview on other phone,top sites not auto sync.

### What/Requirements
I hope Firefox Preview can auto sync top sites.

### Acceptance Criteria (how do I know when I’m done?)
Use Firefox Preview on other phone

**Comment by cadeyrn** [comment]
Duplicate of #7936.

**Comment by sv-sdeiac** [comment]
Closed as a duplicate of #7936.
