### ISSUE TITLE
Search engines bar. Replace 'Shortcuts' button with different search engines.

### ISSUE THREAD

**Issue by devebl** [mozilla-mobile/fenix#10234]
### Why/User Benefit/User Problem
This was present in previous version, Currently if you have to search a term with different search engine you will have to - 

1. Click on search engin from 'This time search with' > Enter keyword > Press enter> Search Results

![new2](https://user-images.githubusercontent.com/63951520/80378047-b7ab3700-88b9-11ea-8c93-b2db066285c6.gif)

#### or if you wanted to search with different search engine after typing keyword
1. Type keyword>click on Shortcuts>click on desired search engine>again press enter>search results. 

![New](https://user-images.githubusercontent.com/63951520/80375753-6a799600-88b6-11ea-9284-0069a1a44329.gif)

Where as previously all search engine logos were displayed instead of 'Shortcuts' button. Also once you click on search engine it will instantly show web result.

![old](https://user-images.githubusercontent.com/63951520/80376073-eb389200-88b6-11ea-8f81-3b3c51a905af.gif)

### What/Requirements
* Remove 'This time search with' or replace it with bookmarks #10198  .
* Replace 'Shortcuts' button with different search engines(other than default search engine)
* Once clicked on search engine logo it will show search result, no need to press enter.

### Acceptance Criteria (how do I know when I’m done?)
When I am able to search term with different search engines on one tap.
type search term>click on search engine icon>search results

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-287)

**Comment by zcdunn** [comment]
Yes, please. This is one of my biggest frustrations with Preview

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807736

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
