### ISSUE TITLE
FNX-3381 ⁃ [Bug] Fenix freezes after Opening Link

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#10239]
## Steps to reproduce
It's a little bit complicated:

1. Works in both, private and normal mode. Probably only works, if no other tabs were previously opened (or if all open tabs are closed manually in step 3)
1. Open any link from the outside of Fenix. I'm talking Sharing-to-Fenix or using the search widget. Probably any way that doesn't involve pressing the "open-new-tab-button"
1. Click on the tab-selection-square.
1. Close the Tab
1. Press back on your Android-Back-Button.
1. Enjoy. (now the screen's just white with a [0]-tabs-square at the bottom. If you press your home-button, then re-enter Fenix without properly closing it, you'll see the frozen screen. Alternatively, if you press the tab-button again, then press back AGAIN, you'll get the same freeze. It's really fun, just try it out!)

### Expected behaviour
No "0-Tab-white-screen". No freeze

### Actual behaviour
See pictures.
![11](https://user-images.githubusercontent.com/59611881/80379772-165abb80-888e-11ea-81e9-279ea04c8450.jpeg)
![12](https://user-images.githubusercontent.com/59611881/80379775-16f35200-888e-11ea-918a-e3d5fef02a3a.jpeg)
![13](https://user-images.githubusercontent.com/59611881/80379776-178be880-888e-11ea-92d7-dca3b6a7d995.jpeg)

### Device information
* Android device: Samsung Galaxy S9
* Fenix version: 4.3.0

**Comment by Glitchy-Tozier** [comment]
I assume, it's the way Fenix opens Links from outside, as this doesn't happen when opening a website from within Fenix.

**Comment by eliserichards** [comment]
Hey @Glitchy-Tozier! How often are you seeing this happen? Do you have some examples of the URLs that you are opening?

**Comment by Glitchy-Tozier** [comment]
@eliserichards Any Url. I can replicate it whenever I want.
The most common url is probably the search engine I use, but it works with any link. Youtube, Google, whatever. There just needs to be a tab to close.

**Comment by Glitchy-Tozier** [comment]
It's the same practice as #10211... just that 
1. That guy doesn't know that it doesn't have to be the Home-Screen-Widget.
2. He apparently uses a different last step to show the actual frozen screen. There probably are even more ways of doing the last step. I think, going into Settings and then comming back to Tab-Zero might work too, but I'm not testing it right now.

**Comment by Mugurell** [comment]
Tried to reproduce this on latest Nightly but I couldn't.
@Glitchy-Tozier Can you please confirm if this is still happening on latest Nightly?
A video would also help if so.

**Comment by Glitchy-Tozier** [comment]
@Mugurell This exact way of getting the app to freeze doesn't work anymore as Fenix is closed/suspended by pressing on the back button. (I just tried it out in the regular most up-to-date version of Fenix (5.1.1)). So yes, this path to getting Fenix to freeze seems to be fixed.

Unfortunately, in 5.1.1, there still are other ways to get this to happen by just slightly changing the instructions. See  #11472.

**Comment by Mugurell** [comment]
If QA can confirm this does not reproduce anymore then this can be closed.

**Comment by Glitchy-Tozier** [comment]
I'm sorry but what does QA mean?

**Comment by Mugurell** [comment]
> I'm sorry but what does QA mean?

**Q**uality **A**ssurance
Each ticket must go through a more thorough verification to be sure that an issue is or not is fully resolved.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

❌ It's **still reproducible** using the following STR:
○ **Prerequisites**
Fenix should be closed

○ **Steps to reproduce**
1. Open Gmail
2. Long tap on a link
3. Select "Open in Browser"
4. While the page is loading tap the device **back button**
5. Resume Fenix

○ **Notes**
❗ While stuck with the white screen, the user can use the **pull to refresh feature**, or at least the loading icon is displayed 
If you tap again the **back button** Fenix's home screen is properly displayed 

► Video
![20200619-154021](https://user-images.githubusercontent.com/51314259/85134317-f8ce2080-b244-11ea-9fbd-0f57f059ac0d.gif)


@Mugurell -  Please review and share your thoughts ☺️

**Comment by Glitchy-Tozier** [comment]
Although this might be more similar to #11472 because it requires the user to exit Fenix and revisit it (while this here issue, #10239, works without even leaving the app)

You could copy that comment to #11472 though.

**Comment by Mugurell** [comment]
This should be fixed by the patch from #9144.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build 200624 from 6/24** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200624-130636](https://user-images.githubusercontent.com/51314259/85537980-20463400-b61d-11ea-989b-e5237a5b3f45.gif)

► Video
![20200624-130738](https://user-images.githubusercontent.com/51314259/85538073-37852180-b61d-11ea-9031-102d2e69489d.gif)

► Video
![20200624-130853](https://user-images.githubusercontent.com/51314259/85538360-7f0bad80-b61d-11ea-85ba-062052479aaa.gif)
