### ISSUE TITLE
[Bug] Image doesn't render in its full resolution

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#10232]
## Steps to reproduce
1. Go to https://upload.wikimedia.org/wikipedia/commons/c/c7/Hegassen_scroll.jpg
1. Double tap or zoom in.

### Expected behavior
images should be showing at 100% size with crisp details.

### Actual behavior
blur

### Device information
* Android device: android 10 pixel 2
* Fenix version: Firefox Preview Nightly 200322 (:lizard:: 76.0a1-20200319094444), Chrome Mobile 80.0.3987.149

reproducible on 77.

originally reported on https://github.com/webcompat/web-bugs/issues/50591

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1680347

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
