### ISSUE TITLE
[Feature request] Search engine suggestion to add to Fenix

### ISSUE THREAD

**Issue by gallegonovato** [mozilla-mobile/fenix#10248]
Good afternoon:

First of all, thank you for the great job you're doing with Fenix

I wanted to make a suggestion, if you'll allow me.    I don't know if the original search engines like Twitter, Wikipedia.    They could add or be replaced by Qwant, Startpage or Searx.

Since they are more search engines with more privacy, so to speak.    Especially qwant and Searx

A warm hug and thank you very much for your time and help.

**Comment by liuche** [comment]
Can add custom search engine through Settings > Search engine, or see #8889 for automatically adding them
