### ISSUE TITLE
FNX-3377 ⁃ Label add-ons that are allowed to run in private browsing

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#10244]
Coping from Bram's comment in https://github.com/mozilla-mobile/fenix/issues/6123#issuecomment-619659103

Either way, I do agree that WebExtensions that run in private browsing should be clearly labelled.

I propose doing something similar to desktop: have a small (16×16dp) private browsing icon to the side of the add-on name.

![](https://user-images.githubusercontent.com/51007/80325454-4c497100-8889-11ea-9687-d85db86d5e70.png)

Icon asset: https://dzwonsemrish7.cloudfront.net/items/2D2h3z2m2P3G0Q2a3I0y/private-browsing.svg

**Comment by ValentinTimisica** [comment]
Hello @brampitoyo, I need a feedback regarding the icon color on light/dark theme and private mode.

For the icon background (the circle) I used:
- light theme: #592ACB
- dark theme: #9059FF
- private mode: #9059FF

For the actual icon I used #FFFFFF for all.
You can see the attached screenshots below.

Is this ok? If not, can you please give me the colors for the circle background and the actual icon for each of light/dark theme and private mode?

<table style="width:100%">
  <tr>
    <th>Light theme</th>
    <th>Dark theme</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/52956363/80504352-aaef1780-897b-11ea-8a53-1526ef2e0e20.png" width="300px"/></td>
    <td><img src="https://user-images.githubusercontent.com/52956363/80504403-bb06f700-897b-11ea-9cc4-88bfe9f55518.png" width="300px"/></td>
  </tr>
</table>

<table style="width:100%">
  <tr>
    <th>Private mode</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/52956363/80504443-cb1ed680-897b-11ea-9ba6-b1fed20fc828.png" width="300px"/></td>
  </tr>
</table>

**Comment by brampitoyo** [comment]
Sorry @ValentinTimisica for the overdue feedback!

Yes. The colour you’ve selected works great.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200511 from 5/11`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200511-105950](https://user-images.githubusercontent.com/51314259/81538357-54200f80-9377-11ea-8c0f-2f5fa4d33093.gif)
