### ISSUE TITLE
FNX-3374 ⁃ [Bug] HTTP Basic Authentication dialog is not offered again on submitting invalid credentials

### ISSUE THREAD

**Issue by denschub** [mozilla-mobile/fenix#10247]
## Steps to reproduce
1. Try to access any site requiring HTTP Basic Auth
1. Enter invalid credentials

### Expected behavior
* Authentication dialog is shown again so the user can retry.

### Actual behavior
* Nothing happens and site appears to be loading forever.

### Device information
* Android device: (emulator)
* Fenix version: Nightly 200427 06:01 (Build #21180610)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that this issue is reproducible on https://digitalsorcery.net/custody using the latest version of Firefox Preview Nightly 200506 (Build #21270610).

Devices:
OnePlus 6T (Android 9);
Huawei MediaPad M3 lite 10 (Android 7.0)

**Comment by Amejia481** [comment]
I'm not able to reproduce on pixel 3 Android 10 neither moto g5 Android 7 using

```
Nightly 200705 06:01 (Build #21870613)
AC: 49.0.20200702190156, bafa9299b
GV: 80.0a1-20200702094606
AS: 61.0.7
```

**Comment by Amejia481** [comment]
@denschub would you mind sharing in which emulator did you were testing ? :)

**Comment by denschub** [comment]
Google's android 10 emulator with a play-store enabled AVD created in android studio.

However, this appears to be fine now, yeah. Probably was fixed between April and now. :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200708-113154](https://user-images.githubusercontent.com/51314259/86896809-3c62ce80-c10f-11ea-8a10-35ffd2edce95.gif)
