### ISSUE TITLE
[Bug] Slowed down Icon load animation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10245]
## Steps to reproduce
1. Install HTTPS Everywhere.
1. While it gets verified and installed tap on it (details section is opened)
1. Wait a couple of seconds and tap the device back button
1. Check the featured add-ons icon load

### Expected behavior
The icon load time should be as usual

### Actual behavior
Slower icon load.

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video 
![20200401-140111](https://user-images.githubusercontent.com/51314259/78130649-5f9c2480-7422-11ea-8ddc-fa9c715b53bd.gif)

**Comment by Amejia481** [comment]
This should be fixed in master.
@AndiAJ would you mind verifying if this is still an issue? Thanks in advance :)

**Comment by AndiAJ** [comment]
Hi @Amejia481, I've created a debug build from master and also checked on the latest Nightly build, but it's still reproducible.

I've used the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200428-095928](https://user-images.githubusercontent.com/51314259/80460152-1a451700-893c-11ea-850a-31a9e6f2739d.gif)
