### ISSUE TITLE
[Bug] Pull down to refresh works for any swipes

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#10241]
Interestingly `SwipeRefreshLayout` does not check for only vertical scroll to trigger pull to refresh.

### Expected result
The pull to refresh throbber should only appear for when scrolling down and the webpage is at top.
To be fixed by https://github.com/mozilla-mobile/android-components/issues/8185

### Actual result
- A swipe gesture more on the x axis triggers pull to refresh
- A two finger scale gesture triggers pull to refresh
- A quick scale gesture (one finger double tap and move) triggers pull to refresh
- Descended initiated nested scrolls trigger pull to refresh, for us meaning doubling the throbber with the overscroll shadow.

![SwipeRefreshIssues](https://user-images.githubusercontent.com/11428869/90861540-91dbfd80-e394-11ea-91c5-c0cb5ee96c71.gif)

[video](https://drive.google.com/file/d/1aQPidEnbxYfNxu6KQ4gikUwwoGELahlB/view?usp=sharing)

**Comment by eliserichards** [comment]
Closing in favor or #9766

**Comment by liuche** [comment]
Reopening bc this is a breakout of the meta bug.

**Comment by Mugurell** [comment]
As a note here, this would be easy now to resolve by just reusing the [GestureDetector](https://github.com/mozilla-mobile/android-components/blob/ad258cc61fcb6e62c12167ad8a3b27e04737d88f/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt) from ac but I know @snorp was working on adding back the overscroll effect from GV and also expose much better APIs to know when to show the pull to refresh.

**Comment by Mugurell** [comment]
Adding this to be verified by QA for after the feature is enabled.

**Comment by Diana-Rus** [comment]
Hei @Mugurell  do you have some info when this will be enabled? As of Nightly 9/8 the pull to refresh action is not yet present

**Comment by Mugurell** [comment]
> Hei @Mugurell do you have some info when this will be enabled? As of Nightly 9/8 the pull to refresh action is not yet present

There is no clear schedule.
Hopefully soon, once all this issues are resolved - https://github.com/mozilla-mobile/fenix/issues/9766

**Comment by Diana-Rus** [comment]
Hi, did a check with Google Pixel 3XL (A9) for this issue on a local build, that contained the enable for the pull to refresh functionality.
Scenarios checked:
- A swipe gesture triggers pull to refresh when webpage is at top ✔
- With two fingers on-screen the pull to refresh can be triggered when webpage is at top✔
- When zooming though (one finger double tap and move) won't trigger the pull to refresh ✔
- Scrolling throughout of a webpage won't trigger the pull to refresh ✔ 
      - https://github.com/mozilla-mobile/fenix/issues
      - https://mobile.twitter.com/home
      - uBlock Origin settings -> Filter lists tab
- Should pull to refresh take in consideration iframes, textboxes or other elements ❓ As it is for scrolling in an iframe as an example.
      - At the moment for https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe - the pull to refresh is not triggered neither for iframes nor for textboxes
      - Sometimes for bing.com/covid when tapping on tool tip![image](https://user-images.githubusercontent.com/49859863/92729434-fc240480-f37a-11ea-8b89-b9c8ae431bd5.png) the refresh can be triggered when pulled down.

Note:
- I will remove the qa-needed label until the enable of the meta #9766 is done and can be checked on an official nightly build where all the issues under meta can be checked.

**Comment by Mugurell** [comment]
Based on Diana's comment - https://github.com/mozilla-mobile/fenix/issues/10241#issuecomment-690254408 this is fixed really but if it's not yet verified maybe we can have a definitive verification after adopting GVs new `onTouchEventForDetailResult`
