### ISSUE TITLE
Preview Rebrand Notif Events [Leanplum]

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#10243]
### Why/User Benefit/User Problem
Existing Firefox Preview users will be shown an in-product message letting them know:
a) the app is being rebranded to Firefox Nightly
b) this change could result in increased instability
c) that they can install a separate app (id org.mozilla.firefox_beta) to continue getting early access to new Firefox Android features, but in a more stable environment

To ensure that users understand this change, the Mobile Engagement Marketing team is also planning a Leanplum message to users providing the same information. 

In order to better ensure that this Leanplum notif is complementary, and not redundant/annoying to users, a Leanplum event is requested that fires when users dismiss the notification, or interact with the "Learn More" or "Get Mozilla Firefox Browser" links.

### What/Requirements
An event in Leanplum that tracks all user interactions with the message surface.

The event name should distinguish the placement, i.e. "E_Preview-Nightly-Transition_Interactions"

### Acceptance Criteria (how do I know when I’m done?)
Events are tracked for Leanplum QA users when triggered. Data is accessible in the Leanplum dashboard.

**Comment by amedyne** [comment]
Closing this as we no longer integrate with Leanplum. See #19040.
