### ISSUE TITLE
FNX-3375 ⁃ [Bug] Add-on icons flicker after add-on is installed

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/fenix#10246]
**Steps to reproduce:**

1. Go to Settings - Add-ons
1. Install NoScript add-on and observe the icons of all the add-ons

**Expected behavior**
An animation is displayed while the icons are loading.

**Actual behavior**
The animation flickers upon installing NoScript

**Device information**

* Android devices: Samsung Galaxy S7 Edge (Android 8.0.0)
* Fenix version: 3/26 Nightly build

![fenix flicker](https://user-images.githubusercontent.com/50236075/78123020-38d7f100-7416-11ea-9847-f4cfa36a13af.gif)

**Comment by Amejia481** [comment]
This should be fixed in master.
@acornestean  would you mind verifying if this is still an issue? Thanks in advance :)

**Comment by DanielOrban** [comment]
Hi @Amejia481, **verified as fixed** and marked as closed on the latest Nightly Build #21190604 from 4/28 using the following device:
• Samsung Galaxy S10 Plus (Android 10)
