### ISSUE TITLE
Support "display" web app manifest

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10252]
## Steps to reproduce
1. Go to https://dev.to/
1. Install app
1. Open app

### Expected behavior
Since {{  "display": "standalone"}} from https://dev.to/manifest.json

the app shouldn't show browser chrome.

### Actual behavior
I see the browser toolbar, showing address, meatball menu, etc. 

See also https://developer.mozilla.org/en-US/docs/Web/Manifest/display

### Device information
* Android device: Moto G
* Fenix version: latest nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-316)

**Comment by jonalmeida** [comment]
cc: @kbrosnan

**Comment by kbrosnan** [comment]
@NotWoods what is the expected behavior here?

**Comment by robbah** [comment]
I also have this issue. 

My manifest file has set display: standalone
I found that Firefox mobile is always setting display to 'browser'. Check my debug output when i run my PWA:
```
browser: true
fullscreen: false
standalone: false
minimal-ui: false
```

When i run it on Chrome Mobile, my output is:
```
browser: false
fullscreen: false
standalone: true
minimal-ui: false
```

How is this possible? I am running Firefox Daylight 80.1.2

**Comment by makepanic** [comment]
We hit the same issue.

`matchMedia('(display-mode: standalone)').matches` should return true if the website is installed.

**Comment by dlecan** [comment]
Same issue on https://my.unikname.app with Fenix 83.1.0 or Nightly 202106

`matchMedia('(display-mode: standalone)').matches` returns `false` despite the following manifest:
```json
{
  "name": "My Unikname",
  "short_name": "My Unikname",
  "description": "My unikname app",
  "display": "standalone",
  "start_url": "/app/",
  "orientation": "portrait",
  "background_color": "#313A81",
  "theme_color": "#313A81",
  "scope": "/app/",
  "icons": [
    {
      "src": "/icons/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/icons/icon-256x256.png",
      "sizes": "256x256",
      "type": "image/png"
    },
    {
      "src": "/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```
👉 https://my.unikname.app/manifest.json

More, when "add to home screen", the `name` is not used but asked by Firefox!

**Comment by dlecan** [comment]
@robbah @makepanic what are the URL of your websites?
I'd like to understand the context of this issue.
Thank you

**Comment by robbah** [comment]
> @robbah @makepanic what are the URL of your websites?
> I'd like to understand the context of this issue.
> Thank you

@dlecan 
It is a private web application dev environment: https://cobyplanning.hypeit.nl/
Please let me know when you a finished debugging so i can remove the link.

**Comment by NotWoods** [comment]
@jonalmeida It seems that the issue is we don't support `matchMedia('(display-mode: standalone)')` - aka we don't support the [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/display-mode) properly. This probably requires a hook from GeckoView since its currently unaware what display mode is used.

**Comment by dlecan** [comment]
@robbah thank you! You can remove the link.

1. Your application is installed and loaded perfectly on Firefox 84 in standalone mode:
  No address bar, no browser toolbar...

1. As for other websites, the media query is no supported properly. It seems to be a missing feature, not a bug 😅

The original bug was about the standalone mode, not properly supported on some websites.
@yoasif I just tried to install https://dev.to and now, standalone mode seems to work perfectly with Firefox 84.
Can you confirm?

@NotWoods missing `display-mode` media query should be another issue, shouldn’t it?

**Comment by dlecan** [comment]
> @NotWoods missing display-mode media query should be another issue, shouldn’t it?

Already reported here:
https://github.com/mozilla-mobile/android-components/issues/8584

**Comment by landshut-digital** [comment]
Hello. This problem still exists... Is here a solution ongoing, since its a feature request now?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807431

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
