### ISSUE TITLE
FNX2-13118 ⁃ [Feature Request] Desktop site button on startup

### ISSUE THREAD

**Issue by Flame-0** [mozilla-mobile/fenix#10257]
It's hidden on startup. There should be a desktop site button on startup, such as the Firefox Browser (Mobile).

> ![](https://user-images.githubusercontent.com/40175769/80440000-5e371c80-893a-11ea-86f7-b99345d21222.jpg) ![](https://user-images.githubusercontent.com/40175769/80439932-3778e600-893a-11ea-8b33-e3c3fa754504.jpg)

**Comment by Dunexus** [comment]
What would be the differences between the homescreen in "desktop mode" and the homescreen in "mobile mode" ?

**Comment by lindongbin** [comment]
> 
> 
> What would be the differences between the homescreen in "desktop mode" and the homescreen in "mobile mode" ?

You can directly access the desktop version of the website without having to access the mobile version before switching to the desktop

**Comment by liuche** [comment]
Will dupe to #7039

**Comment by BynariStar** [comment]
Hi, I believe this issue should be retriaged. Issue #7039 suggests a global desktop mode toggle, while this issue requests for a particular tab to be preset to load in desktop mode prior to navigation.
