### ISSUE TITLE
FNX-3389 ⁃ Progressive Web App pop-up interferes with collection of visual metrics -- please provide a method to disable

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla-mobile/fenix#10253]
When loading a site that supports PWA, e.g., https://www.instagram.com, the "Add to Home screen" pop-up is displayed. (attached below).

Unfortunately this interferes with various performance metrics that measure when content is presented to the user. (e.g. SpeedIndex, ContentfulSpeedIndex, etc).

Please provide a method so that this behaviour may be disabled for performance work.
A user preference, if possible, would be ideal.

![](https://user-images.githubusercontent.com/44072237/80024010-6b708900-84ac-11ea-9980-038f97def9a7.png)

**Comment by jonalmeida** [comment]
Moved this back to Fenix based on Tiger's comment above.

**Comment by st3fan** [comment]
I added it to the A-C sprint planning because I think this is a blocker that we can probably quickly resolve.

**Comment by psymoon** [comment]
@acreskeyMoz feel free to re-open this issue if this is still an issue!

**Comment by acreskeyMoz** [comment]
@bdekoz -- no, it's built into Fenix

https://github.com/mozilla-mobile/fenix/commit/5ba9cc6ec9ab729b75f37c79ca5c568013892b9b

Is it not working?
The performancetest mode of fenix has some requirements -- device attached by usb, adb connection:

https://github.com/mozilla-mobile/fenix/blob/82facbfa00b4a701b6919d618df3ee6459bc74b7/app/src/main/java/org/mozilla/fenix/perf/Performance.kt#L42-L56
