### ISSUE TITLE
[Bug] Can't tap on "Sign with Facebook" button with Tracking Protection enabled

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10262]
### Steps to reproduce
1. Access `www.safelanes.org` > `Try it now` > `3-dot menu in top left` > `click user account circle`.
1. On account, sign-in page, click "Sign in with Facebook"
    1. Expected behavior
The user is able to login with Facebook.
    1. Actual behavior
Button text can be highlighted, button text can't be tapped.
    1. Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 4/28.**

![20200428-125056](https://user-images.githubusercontent.com/42831109/80477463-9fd4c100-8954-11ea-9fa0-511d60e1423f.gif)

**Comment by Amejia481** [comment]
The same issue is reproducible in desktop nightly, I will report the issue to privacy team

**Comment by Amejia481** [comment]
Blocks on https://bugzilla.mozilla.org/show_bug.cgi?id=1470298

**Comment by yump** [comment]
Login with Facebook/Google is obviously a tracking mechanism that uses should, in theory, be protected from. But if such logins are widely used, they obviously have to work with the default settings.

Perhaps allow them, and create a new level of tracking protection higher than the default "strict".  Alternately, allow them only on "standard" level and make that the default.  The UI does say that strict tracking protection is expected to break some websites.

**Comment by liuche** [comment]
@amedyne there are 4 open Bugzilla issues linked in the meta. Overall, I think we want people to be able to click on the facebook link to sign in. Is that incompatible with strict ETP? Would it be possible to prioritize this work to ~fenix:p2?

**Comment by Amejia481** [comment]
We recently added the [shimming library](https://groups.google.com/g/mozilla.dev.platform/c/28eWGe4s5a80) on nightly it should help us with these cases, @wisniewskit I was testing on nightly but I still see the FB js error on the JS console, do we have to do something additional for the shimming library to get activated for this site? 

```
Uncaught ReferenceError: FB is not defined
    attemptFacebookLogin https://safelanes.org/dist/core.js:1
    jQuery 2
```

**Comment by englehardt** [comment]
We are tracking breakage bugs not fixed by the Facebook shim under https://bugzilla.mozilla.org/show_bug.cgi?id=1657930.

**Comment by Amejia481** [comment]
Thanks for the clarification!
