### ISSUE TITLE
FNX-3395 ⁃ [Telemetry] PWA

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10261]
#### Description & Product Manager / Data Scientist User Story
As a product manager, I want to know how often users install and run a PWA in Fenix, so I can better understand usage frequency, and use that to prioritize PWA related bugs and polish work. 

#### What questions will you answer with this data?
* Do we make PWA sites easily discoverable?
* How often users install a PWA on their phone’s homescreen?
* How often do users run a PWA site in Fenix?

### Acceptance Criteria
* DS sign off on instrumentation methodology addressing product questions.
* Event pings can be queried via re:dash
* Event pings can be queried via amplitude
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to review the telemetry

#### What probes (suggested, if applicable)
* An event ping when tapping PWA homescreen icons.
* An event ping when tapping the ‘Install’ menu.
  * Distinguish between ‘Install’ PWA vs ‘Add to homescreen’ shortcut.
* An event ping when putting a PWA to the foreground with a time interval from start to finish use.

**Comment by vesta0** [comment]
Here is the [Telemetry Proposal](https://docs.google.com/document/d/17oJNlrDqLqN-mCIj4lj-qOPe5wZDsIM4LFMkiVNMKhQ/edit#) :)

Next step is to [create a JIRA request](https://jira.mozilla.com/browse/DS-191?jql=project%20%3D%20DS%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC) outlining the Dev proposal for DS review.

**Comment by jonalmeida** [comment]
I'm updated (in-line) the JIRA request and this ticket with the dev proposal.

**Comment by grigoryk** [comment]
Let's also make sure we're counting total number of installed PWAs to make it easier to correlate feature usage, as discussed w/ Marissa. That will be supported by https://github.com/mozilla-mobile/android-components/issues/7474

**Comment by eliserichards** [comment]
I'll pull that out into a separate issue for tracking ^

**Comment by vesta0** [comment]
Is this work completed?
