### ISSUE TITLE
FNX-3398 ⁃ [Feature request] [fennec parity] Make Fenix open a new tab when set as "assistance app" like the widget

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#10271]
### Why/User Benefit/User Problem
Fenix's search widget when tapped opens a new tab and brings up the keyboard
If I set Fenix as the assistance app, this does not happen, Fenix just comes to the foreground.
It would be great if the Fenix assistance app gesture worked the same as tapping on the widget

(Fennec does work like this, the assistance gesture brings up a new tab & the keyboard).

Thanks

**Comment by kbrosnan** [comment]
How is this different than #7013 which you also filed?

**Comment by Cheap-Skate** [comment]
Sorry for duplication
