### ISSUE TITLE
FNX-3401 ⁃ [Bug] Sign in from onboarding on Android 5&6 devices loops

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10279]
## Steps to reproduce
1. Make sure you have a clean profile.
1. From the onboarding card, sign in via email with valid credentials.
OR
1. Sign in from Settings - Turn on Sync

### Expected behavior
After the sign-in is done, the user is redirected to the onboarding tour.

### Actual behavior
The user is not redirected. Is stuck on the Manage account page. If "x" or back is tapped, the user is not signed in. If the user selects from the three-dot menu to open the accounts page in Firefox Preview, the "Turn on Sync" page is opened without the user being signed in - it is a constant loop.

### Device information
* Android devices: Samsung Galaxy Tab A6 (Android 5.1.1), OnePlus A3 (Android 6.0.1)
* Fenix version: Beta 5.0.0-beta.1, 
4/29 Nightly @6:09 AM build

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4550506/logcat.txt)

![loop](https://user-images.githubusercontent.com/40694158/80575505-6069ab80-8a0c-11ea-9e8d-6b3d4f356c92.gif)

**Comment by liuche** [comment]
@eoger @grigoryk is this also related to something in AS?

**Comment by liuche** [comment]
Duping to #10277

**Comment by softvision-miralobontiu** [comment]
Hi, verified as fixed on the Debug Build from Master we've just created: 39.0.1, f19856fa4 GV: 77.0a1 20200427094322 AS: 0.58.2 using the following devices:
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy A6 (Android 5.1.1)

**Comment by softvision-miralobontiu** [comment]
Hi, verified as fixed on the Beta 5.0.0-beta.2 build using the following devices:
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy A6 (Android 5.1.1)
• Xiaomi MiPad 2 (Android 5.1)
