### ISSUE TITLE
FNX-3400 ⁃ uBlock Origin's 2 option named "Enter element zapper mode" and "Enter Element picker mode" has stopped working.

### ISSUE THREAD

**Issue by PranavBhattarai** [mozilla-mobile/fenix#10278]
Firefox Preview version: 4.3.0
uBO version: 1.26.2
Proof: I will upload the screencast video eventually. _(I accidentally deleted that video)_

What happened: When I was reading a manga website, then I wanted to remove some portion of the web page, but unfortunately both options which I mentioned in the above title of uBO didn't respond.

Does this action is reproduceable?
Well, it depends. Usually, it works, but **1** out of **4** times it doesn't work.

P.S: I didn't know whether to report this issue over here or on uBO's GitHub page. So, if I did some mistake, then forgive me.

Device: Oneplus 5
OS: Oxygen OS
Android: 9

Proof: https://youtu.be/nM0B3lhavfw 
_(I didn't know where to share it. So, I choosed YouTube. I wish I knew a website like Pastebin where we can paste videos. To make uBO work normally again, at the end of the video, I had to force stop the browser.)_

**Comment by eliserichards** [comment]
Hi @PranavBhattarai! Thanks for the report! If you have a video of this happening that would be great. What is happening when you try to select the uBlock option?

**Comment by PranavBhattarai** [comment]
@Amejia481 I have added a video link, where u can see everything. 

> What is happening when you try to select the uBlock option?
Nothing happens when I select those two options which I have mentioned above. And that's the problem.

**Comment by sflorean** [comment]
Checked on latest Nightly build, with the following devices: OnePlus 5T (Android 9), Nokia 6 (Android 7.1.1), and LG G7 FIT (Android 8) and couldn't reproduce the issue, tried several times. Also, wanted to check the exact link presented in the video, but doesn't seem to work anymore.

**Comment by PranavBhattarai** [comment]
@sflorean
Then close the bug. 
Maybe the update in uBO has fixed this issue already.
