### ISSUE TITLE
FNX-3402 ⁃ [Bug] Crash when signing in through pairing on Android 5&6 devices

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10280]
## Steps to reproduce
1. From the onboarding tour sign in via pairing.
1. Confirm the pairing on both devices.

### Expected behavior
Pairing works and the user is signed in.

### Actual behavior
After the confirmation on both devices is done, Fenix crashes.

### Device information
* Android devices: Samsung Galaxy Tab A6 (Android 5.1.1), x86 Xiaomi MiPad 2 (Android 5.1.1), and Nexus 5 (Android 6.0.1)
* Fenix version: Beta 5.0.0-beta.1,
4/29 Nightly @6:09 AM build
* The same behavior when trying to sign in from Settings - Turn on Sync

[crash.txt](https://github.com/mozilla-mobile/fenix/files/4550557/crash.txt)

![crash](https://user-images.githubusercontent.com/40694158/80576003-18975400-8a0d-11ea-822b-c675e827e376.gif)

**Comment by liuche** [comment]
Same root cause as #10277, so duping.

**Comment by softvision-miralobontiu** [comment]
Hi, verified as fixed on the Debug Build from Master we've just created: 39.0.1, f19856fa4 GV: 77.0a1 20200427094322 AS: 0.58.2 using the following devices:
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy A6 (Android 5.1.1)

**Comment by softvision-miralobontiu** [comment]
Hi, verified as fixed on the Beta 5.0.0-beta.2 build using the following devices:
• Samsung Galaxy A6 (Android 5.1.1)
• Xiaomi MiPad 2 (Android 5.1)
