### ISSUE TITLE
FNX-4734 ⁃ Send Mobile Activation Ping telemetry

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1028]
@vesta0 - This bug should be a Fenix MVP blocker.

Fennec telemetry shows 25% more installs than the Google Play Store does ([bug 1483927](https://bugzilla.mozilla.org/show_bug.cgi?id=1483927)). @fbertsch has specified a new Mobile Activation Ping (in [bug 1501822](https://bugzil.la/1501822)) that includes a hash of the user's Google Ad ID in install/uninstall telemetry to count unique users and avoid double-counting reinstalls. We need to implement this new Mobile Activation Ping for both Fennec ([bug 1534451](https://bugzilla.mozilla.org/show_bug.cgi?id=1534451)) and Fenix.

Google Ad ID can be reset by users. Google's policy requirement is that all apps use this ID in lieu of any others for advertising. We are not using this for advertising so that policy should not apply to us.

fbertsch recommends that Fenix use Glean (and A-C's [Glean component](https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/README.md)). We can then use the "Ping Format" section of the Mobile Activation Ping spec as a guideline for which metrics to implement.

Fenix Mobile Activation Ping spec:
https://docs.google.com/document/d/1mYklPkL1LYnAnjfeyaiqXJ4uuui8r08GCgN30Iod53k/edit

**Comment by vesta0** [comment]
cc @bbinto

**Comment by bbinto** [comment]
Based on my understanding, since integrating with Glean SDK is a must have for MVP, this should be covered with this GH issue https://github.com/mozilla-mobile/fenix/issues/105

**Comment by fbertsch** [comment]
Hi All, we were tracking this in Bugzilla previously. The Data Review [(Bug 15088390](https://bugzilla.mozilla.org/show_bug.cgi?id=1508839) has the most useful information. There is additional information in [Bug 1481220](https://bugzilla.mozilla.org/show_bug.cgi?id=1481220) about the difference between Telemetry and Adjust.

Essentially, BD needs more exact numbers to better predict and find exact activation counts when creating distribution deals. Raw Telemetry numbers aren't good for that kind of analysis.

This issue should be another ping sent by Glean. We just need to track the implementation work (setting up the new Ping in Glean, and loading it with the correct data).

**Comment by cpeterso** [comment]
IIUC, Fenix (or an AC component) can send the Mobile Activation Ping using Glean, but Fennec will require its own implementation (Fennec [bug 1534451](https://bugzilla.mozilla.org/show_bug.cgi?id=1534451)). If Fenix or AC implements this ping first, then Fennec can copy/paste Fenix's code for reading the Google Ad ID and computing the hash.

**Comment by cpeterso** [comment]
I filed A-C issue mozilla-mobile/android-components#2397. We'll probably want this Mobile Activation Ping in other Mozilla apps besides Fenix, so we should implement it in an A-C component. Fennec can just copy/paste the component code if it doesn't use A-C.

**Comment by bbinto** [comment]
For the purpose of this repo/product, I assume we will track the work in the A/C issue that @cpeterso has filed. I am still not clear who the owner is of this request that this should block MVP?

**Comment by vesta0** [comment]
@cpeterso @bbinto sounds like this is covered in the [A-C issue](mozilla-mobile/android-components#2397.). Can we close it?

**Comment by bbinto** [comment]
I agree, @vesta0 - thanks.

**Comment by aranamozilla** [comment]
Please see below the link to requirement document for Fenix mobile activation ping

https://docs.google.com/document/d/1mYklPkL1LYnAnjfeyaiqXJ4uuui8r08GCgN30Iod53k/edit

**Comment by cpeterso** [comment]
I would recommend leaving this Fenix issue open until:
1. Fenix picks up the fixed AC version.
2. Someone verifies that Fenix users' Mobile Activation Pings are successfully showing up in whichever telemetry database they're supposed to go.

**Comment by Dexterp37** [comment]
This is being implemented in #1707 . After asking in #fenix on slack, since no other product is currently using this, it's fine for it to land in Fenix first and then be backported once needed.

**Comment by liuche** [comment]
One more comment here, there's the data review and discussion of Mobile Activation Ping but once it's being used we should move that documentation to be public, either in Glean or here in Fenix.

**Comment by Dexterp37** [comment]
> 
> 
> One more comment here, there's the data review and discussion of Mobile Activation Ping but once it's being used we should move that documentation to be public, either in Glean or here in Fenix.

Agreed. I'll take care of doing this before merging the implementation. We're also adding ping documentation in the implementation PR, I'll flag you there as well, just FYI :)

**Comment by bsurd** [comment]
This has been tested by QA, the activation ping is successfully sent and appears in glean.
