### ISSUE TITLE
FNX-3409 ⁃ [Bug] Tapping on the URL bar from a loaded page doesn't display the "Clear/x" button

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10289]
## Steps to reproduce
1. Load a page.
1. Tap on the URL bar.

### Expected behavior
The page's address is selected and a "Clear/x" button is displayed in the URL bar.

### Actual behavior
The page's address is selected but the "Clear/x" button isn't displayed in the URL bar. If the user edits the address, the "x" is displayed and works properly.

### Device information
* Android device: all
* Fenix version: 4/29 Nightly build, Beta 5.0.0-beta.1
* Reproducible since the 4/24 build
* Not reproducible on the 4/23 Nightly build @6:08 PM

**Comment by codrut-topliceanu** [comment]
AC issue : https://github.com/mozilla-mobile/android-components/issues/6859
related PR : https://github.com/mozilla-mobile/android-components/pull/6860

**Comment by codrut-topliceanu** [comment]
AC PR merged, should be ready for testing.

**Comment by Diana-Rus** [comment]
Hi, issue is fixed, verified on Nightly 5/5 with:
- Google Pixel 3 XL (Android 9)✔️
  -![20200506-155556](https://user-images.githubusercontent.com/49859863/81200748-12851280-8fcd-11ea-984b-098adff63104.gif)
- Samsung Galaxy S9 (Android 8)✔️
  -![20200506-155626](https://user-images.githubusercontent.com/49859863/81200351-84a92780-8fcc-11ea-8467-7835f9ddc38b.gif)
- Sony Xperia Z5 (Android 7)✔️
  -![20200506-160832](https://user-images.githubusercontent.com/49859863/81200942-511acd00-8fcd-11ea-96d7-4e3fd120130b.gif)
