### ISSUE TITLE
FNX-3408 ⁃ [Bug] Video doesn't automatically play with default "Autoplay" setting

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#10287]
## Prerequisites
"Settings > Site permissions > Autoplay > Block audio and video" - set.

## Steps to reproduce
1. Navigate to https://www.apple.com/iphone-11-pro/
1. Observe top video.

### Expected behavior
Video automatically plays.

### Actual behavior
Video does not play. 

### Device information
* Android device: Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density). 
* Fenix version: Firefox Preview Nightly 200427 (:lizard: 77.0a1-20200422093542)

### Note
1. The issue is not reproducible on Chrome and Firefox Release.
1. Setting "Settings > Site permissions > Autoplay > Block audio and video on cellular data only" option, the video plays.
1. This was previously reported here: https://github.com/webcompat/web-bugs/issues/51167
1. Gif attached.

![VideoDoesNotPlay](https://user-images.githubusercontent.com/12184325/80594552-e3e6c500-8a2b-11ea-96d5-3ab662b3a9c9.gif)

**Comment by kbrosnan** [comment]
Dupe #8503
