### ISSUE TITLE
FNX-3411 ⁃ [Bug] Dynamic nav-bar isn't working when toolbar is set to the bottom

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10291]
## Steps to reproduce
1. Go to Settings - Customize and set the toolbar to the bottom.
1. Load any page and scroll up and down observing the nav-bar.

### Expected behavior
The navigation bar is dynamic.

### Actual behavior
The navigation bar is fixed and displayed when scrolling.
When the toolbar is set to the top, the navigation bar is dynamic.

### Device information
* Android device: all
* Fenix version: 4/29 Nightly build and Beta 5.0.0-beta.1

[dynamic.txt](https://github.com/mozilla-mobile/fenix/files/4551764/dynamic.txt)

![](https://user-images.githubusercontent.com/40694158/80598626-50fd5900-8a32-11ea-9f41-4770a2ea0acd.gif)

**Comment by liuche** [comment]
We haven't enabled Dynamic Nav bar on release yet, so we are waiting on #8775 because there are still a few GV issues that are outstanding.
