### ISSUE TITLE
[webcontent] Wrong placemenet of fixed content at the bottom of the screen when the toolbar is set to the top

### ISSUE THREAD

**Issue by rogerespel** [mozilla-mobile/fenix#10295]
Affected site, among many others:
https://aeon.co/essays/why-care-and-the-scare-are-inseparable-when-you-love-someone

Bug only happens when the browser toolbar is configured to the top of the screen.

### Expected behavior
When scrolling down, social sharing buttons from the website appear in a fixed position at the very bottom of the screen, and stay there.

### Actual behavior
Social sharing bar scrolls up about 1cm from the bottom of the screen when the screen is scrolled up.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Bug not present in Firefox for Android.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Bug not present in Chrome for Android.

### Device information
* Android device: Nokia 7 Plus
* Fenix version: 4.3.0

**Comment by Mugurell** [comment]
Thank you for the report @rogerespel !
I think the issue was resolved in the meantime I cannot seem to reproduce it.
Will close the ticket but feel free to leave a comment if you still encounter this.
