### ISSUE TITLE
FNX-3410 ⁃ [Bug] Add-on 'Run in private browsing' option resets when app is restarted

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#10290]
## Steps to reproduce
**Step 1**

* `Settings` -> `Add-ons`
* Have some installed add-ons (or install them now)
* Enter add-on details
* Enable `Run in private browsing` (by default is disabled)
* Close the app
* Open the app and enter again in the same add-on details

**Step 2**

* Close again the app without changing anything
* Open the app and enter in the same add-on details

### Expected behavior
**After Step 1**

* `Run in private browsing` option should be enabled

**After Step 2**

* The same, `Run in private browsing` option should be enabled

### Actual behavior
**After Step 1**

* `Run in private browsing` option is disabled

**After Step 2**

* `Run in private browsing` option is enabled

### Device information
* Samsung Galaxy Note 10: Android 10
* Fenix versions: 
  * latest master
  * Beta 5.0.0-beta.1 from 4/29

### Additional info
* Every time you enable `Run in private browsing` on one of the add-ons and restart the app, all of them are disabled. You have to restart again the app to get the correct enabled state.
* [Video](https://drive.google.com/file/d/1e_dIsoYPGDIXy44Rj1nLoJV-Pp9IwcgH/view?usp=sharing)

**Comment by psymoon** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1634493

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on the latest **`Nightly build 200507 from 5/7`**  using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200507-092727](https://user-images.githubusercontent.com/51314259/81262262-2f116100-9046-11ea-80c5-8d060b9180cd.gif)

**Comment by psymoon** [comment]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1637680

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/12 with the following devices:
- Samsung Galaxy Note 10 (Android 10)
- Nokia 6 (Android 7.1.1)
