### ISSUE TITLE
FNX-3415 ⁃ Bring back "share image"

### ISSUE THREAD

**Issue by rogerespel** [mozilla-mobile/fenix#10298]
### Why/User Benefit/User Problem
Firefox for Android has a long-press menu on images, which includes the "Share Image" feature.  With this users can very easily and quickly share interesting content  (from memes and jokes up to business charts...) through their favorite messenger apps.  Firefox for Android shares the actual image, not the URL, so the image itself gets sent as a message, as it should be.

Firefox Preview currently lacks this option.

### What/Requirements
Ability to share an image directly (not a link to it) through the image's long-press menu.

### Acceptance Criteria (how do I know when I’m done?)
When seamless sharing of memes to whatsapp/hangouts/etc works. Feature parity with Firefox for Android.

**Comment by kbrosnan** [comment]
Dupicate 7458
