### ISSUE TITLE
[Bug] BBC Sounds stops playing

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#10292]
## Steps to reproduce
Open and log into https://www.bbc.co.uk/sounds
Play a radio channel or podcast

### Expected behavior
Radio channel or podcast plays for a substantial length of time

### Actual behavior
Radio channel or podcast starts to play, then about a minute in, the audio is paused and needs to be triggered to play again.

### Device information
Identified in https://support.mozilla.org/en-US/questions/1285325

Also seen on my device:

* Android device: Moto E5, Android 8
* Fenix version: Nightly 200429 06:00 (Build #21200609) 40.0.20200428130031, c5f35b160 CV:77.0a1-20200427094322 A: 0.58.1

Given that this issue requires a website account (that I have), I am happy to help work with people to resolve this.

**Comment by ferdossi** [comment]
Isn't it fixed? I don't have this issue anymore

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 2/23 with Google Pixel 4 XL (11).
I was able to play the radio without problems.
