### ISSUE TITLE
FNX-4735 ⁃ [meta] Pull to refresh

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#103]
As a user, I want to reload a website so I can view the latest version of the site to not miss on any updated information

### Benefit
Provide quick access to refresh current website

### Requirements
Action to let users reload a website

**Comment by bbinto** [comment]
See https://github.com/mozilla-mobile/android-components/issues/1824, closing this

**Comment by pwd-github** [comment]
I saw that this landed a couple days ago, but I'm unable to get it to work.

**Comment by evilcoleslaw** [comment]
@pwd-github 

It's currently hidden behind a compile time flag and disabled.

https://github.com/mozilla-mobile/fenix/issues/3091
