### ISSUE TITLE
[Bug] Google keyboard doesn't always show up in private browsing

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#10302]
> Originally at https://bugzilla.mozilla.org/show_bug.cgi?id=1629900 (with screenshot)

## Steps to reproduce
Using version 200408 6:01 Firefox Preview Nightly.
Android version 9
Phone: LGv30

* Download/Use Google Keyboard.
* Open private browsing in Firefox Preview Nightly.
* Go to website: https://www.postable.com/tmobiletuesdays.
* Pick any card.
* Click the "Start Writing" button.
* Click on any of the value fields.

### Actual results
The keyboard doesn't show up to type with.

### Expected results
The keyboard doesn't show up and you can't type into the value box.

**Comment by eliserichards** [comment]
@st3fan do we know how often is this happening? Is it happening on any other websites? @chris.cushman

**Comment by Diana-Rus** [comment]
Hi, the STR are as follows:
1. Open tab in private mode.
2. Go to https://www.postable.com/
3. Tap on the menu from top left corner.
4. Tap on Browse Cards.
5. Choose one section from the available list.
6. Tap on one of the available cards.
7. Tap on the "Start Writing" button.
8. Tap on the available fields from the form.(Recipient Name, Street Address, Apt, City, State, Zip)

Notes:
The issue does not reproduce with Samsung Galaxy S9 (Android 8) and LG G7 fit (Android 8) on Nightly 5/25 in neither normal nor private mode.
Other tested sites with forms and Gborad installed:
- https://www.postable.com/tmobiletuesdays
**GIF**
![20200525-142401](https://user-images.githubusercontent.com/49859863/82809472-d854b580-9e94-11ea-9d7c-5b35c519cabc.gif)
- https://driedfruits.ro/index.php?route=checkout/checkout
**GIF**
![20200525-115108](https://user-images.githubusercontent.com/49859863/82797178-60c85b80-9e7f-11ea-8b61-9ecaa951f6e8.gif)
- https://www.elefant.ro/checkout/address/
**GIF**
![20200525-120301](https://user-images.githubusercontent.com/49859863/82799532-daae1400-9e82-11ea-8b3c-01f1f5185cf6.gif)
- https://www.w3schools.com/html/html_form_input_types.asp
**GIF**
![20200525-123242](https://user-images.githubusercontent.com/49859863/82800963-35e10600-9e85-11ea-9f83-9ef337e434fd.gif)

**User recording**
![Recording-2020-04-14-10-15-23](https://user-images.githubusercontent.com/49859863/82794188-bf3f0b00-9e7a-11ea-90c6-f680ba25d6c7.gif)
