### ISSUE TITLE
[Feature request] Button to enable fullscreen on any website

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#10303]
> Originally at https://bugzilla.mozilla.org/show_bug.cgi?id=1629629

Go to a website that is too short to go fullscreen by scrolling down

### Actual results
The address bar is still visible, forcing me to scroll even if the site would fit the screen if the browser was fullscreen

### Expected results
I'd expect a button on the Extras > Fullscreen that puts the browser in fullscreen mode, so I can see the full page without the need to scroll

**Comment by eddie-LA** [comment]
This would also fix weird scaling issues with constant fullscreen/unfullscreen on phones with gesture navigation.
Poco F1, Android 10, Firefox Release and Beta exhibit this behaviour
(Chromium-based browsers do not) 
Should I file a bug report about this of there is already a feature request or write here?

**Comment by Mugurell** [comment]
I think the original described issue is a variant of https://bugzilla.mozilla.org/show_bug.cgi?id=1663000 which should have been fixed in the meantime.
Closing this as such.

**Comment by Mugurell** [comment]
@eddie-LA In a quick test on the latest Nightly the images were showing as expected and the previos/next buttons were working as expected.
If you still encounter the issues described here please open a new ticket.
