### ISSUE TITLE
FNX-3424 ⁃ [Bug] dark reader extension not working on Mozilla websites

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#10307]
When opening some pages such as the "what's new in Firefox  nightly" it doesn't properly open in the browser and so it doesn't adhere to using dark reader. And also sometimes when I first open a page, it's still white for a split second.

**Comment by kbrosnan** [comment]
What's new in Firefox is hosted on a Mozilla domain which is not allowed for extension to run. This is the same behavior as desktop.

**Comment by Kreuger** [comment]
Is there a reason for this?

**Comment by kbrosnan** [comment]
Extensions could block a user from getting support or other malicious behavior like install a different extension than the one that the user clicked on.

**Comment by Kreuger** [comment]
OK thanks
