### ISSUE TITLE
Tapping a media notification from a PWA should open the PWA

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10319]
## Steps to reproduce
1. Install and open a PWA with videos (e.g. twitter / digi24.ro)
1. Play a video.
1. Minimize the PWA, tap the media notification from the notification tray.
    1. Expected behavior
The notification should bring the PWA to front.
    1. Actual behavior
Nothing happens.
    1. Device information

* Android device: Nexus 9 (Android 7.1.1)
* Fenix version: Beta 5.0, Nightly 4/30

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-384)

**Comment by grigoryk** [comment]
Requires https://github.com/mozilla-mobile/android-components/issues/3986

**Comment by pocmo** [comment]
@NotWoods You moved this to "Production Ready" on the PWA board. Was this a mistake?

**Comment by NotWoods** [comment]
That column is our "todo soon" list

**Comment by softvision-miralobontiu** [comment]
This is still reproducible on all builds: 2/24 Nightly, beta 87.0.0-beta.1, and RC 86.1.1.

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.4 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on Beta 89.0.0-beta.9 with HTC 10 (Android 8).

**Comment by sflorean** [comment]
This is still reproducible on Fenix builds.

**Comment by AdinaPetridean** [comment]
This issue is still reproducible on the latest Nightly 09.0a1 from 23/11 with One plus 9 Pro (Android 12).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807430

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
