### ISSUE TITLE
FNX-3430 ⁃ [Bug] Content area briefly/blindingly flashes white before turning solid black for pageload, when Android and Fenix both configured for "dark" theme

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#10312]
## Steps to reproduce
1. (optional) Ideally, use a slow network connection (e.g. turn off wifi) - that makes this easier to see in isolation and reason about, since it separates the stages of pageload out over time a bit more.
1. Set your device theme and your Fenix theme both to "dark":

* Android settings | Display | Dark theme: "on"
* Fenix settings | Customize | Theme: "Dark" or "Follow device Theme"

1. In Fenix, open a new Private tab (it doesn't have to be private, but that helps -- this skips the cache, at least for the first load, which makes pageload take longer, which -- per (1) -- makes this bug easier to see in isolation, & reason about).
1. Type in the URL for some site with a dark background, e.g.:
https://spacejam.com/
https://duckduckgo.com/ (renders with a dark background if you have a dark theme)
...and hit "enter".

### Expected behavior
No weird bright flashes.

### Actual behavior
* The "enter URL" pane is nice and dark, initially.
* As I leave the "enter URL" pane, the screen flashes bright white.
* Then the screen immediately turns black again.

This weird blinding flash is disconcerting/unsettling, and it's a rough papercut for your night vision if you're trying to browse in dark mode to rest your eyes.

### Device information
* Android device: Pixel 3
* Fenix version: Firefox Preview Nightly, 200427 06:01 (build #21180609)

**Comment by dholbert** [comment]
As far as I can tell, what's happening here is:
 - When you hit enter to load a URL, some graphical surface gets created which is displayed during pageload.
 - If your android system theme is "dark" (regardless of your Fenix theme), then that surface will be black.
 - However, we show it as bright-white for a fraction of a second before it turns black.
 - It looks like this happens even if Fenix itself is configured for a light theme, but it's particularly noticeable/painful if Fenix has a dark theme, because it means you'll go from a dark page, to a brief instant of bright-white, back to dark.

**Comment by dholbert** [comment]
(Also: I know sometimes this sort of flash can be caused by flash-of-unstyled-content, i.e. the webpage being partially loaded and missing some styles including its background-image or whatever.  That's *not* what's happening here -- this bug is specifically about the coloring of the blank tab-content that's shown while the page is loading, **before** we've received any data for the page at all.)

**Comment by dholbert** [comment]
(Also: the color of the final page actually doesn't matter that much for this bug's reproducibility -- it just makes the flash of white easier to notice, if the pageload happens quickly.)

**Comment by dholbert** [comment]
Screencast coming up, hosted on Dropbox. Here's a screenshot of the video player there, showing the frame of the screencast video (around 0:04) where the background is rendering as bright-white:
![image](https://user-images.githubusercontent.com/426803/80670078-db59b300-8a5a-11ea-9774-a5733bbcb3a1.png)

**Comment by dholbert** [comment]
screencast: https://www.dropbox.com/s/zne4d8tdfwybtnj/flash-of-white.mp4?dl=0
(Basically, the screen flashes white *while the keyboard-disappearing animation is happening, I think?)

**Comment by kbrosnan** [comment]
Duplicate #6313

**Comment by dholbert** [comment]
Indeed, looks like it. Sorry for the dupe-noise, and thanks for taking a look.
