### ISSUE TITLE
A deeper locale differentiation for Leanplum experiments

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#10314]
Based on Jeff's comment from https://github.com/mozilla-mobile/fenix/issues/6836
> I'm seeing inconsistencies between the language codes (apparently non-standard 3 char) used here and the locale codes (standard 2 char lang + region) we actually ship. For example, how are we differentiating messaging and user stats between zh-TW (Traditional Chinese) and zh-CN (Simplified Chinese)? This really is only an issue where we're shipping multiple localizations of the same language (es, zh, and pt) but it's an important distinction for the following reasons:

> It impacts locale conventions users rely on around their language.
It helps to craft the right message in the right language form for the right users.
It ensures we have an accurate picture of our users.

We currently support [these locales](https://github.com/mozilla-mobile/fenix/issues/6836#issuecomment-573098428) irrespective of location.

@lwa-moz I think it's a question for marketing and data if there's need for a deeper targeting / knowledge or if the current locales are enough.

**Comment by st3fan** [comment]
This was moved to the Fennec Migration board but I don't think it belongs there. If there is an issue with the locales that we match on for Leanplum then that is a general Fenix product issue, unrelated to the migration project.

I added the needs-triage label back.

**Comment by Mugurell** [comment]
We've migrated away from Leanplum. Closing.
