### ISSUE TITLE
FNX-3438 ⁃ [Bug] Nightly crashex

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#10328]
## Steps to reproduce
update nightly
start nightly

### Expected behavior
not crash

### Actual behavior
crash

### Device information
* Android device: one plus 5t
* Fenix version: nightly

**Comment by eliserichards** [comment]
Related to #10320

**Comment by TitanNano** [comment]
Probably a dupe of #10334

**Comment by andreicristianpetcu** [comment]
it's fixed now
