### ISSUE TITLE
FNX-3435 ⁃ Tab Tray - Implement Media Play State

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10321]
![](https://user-images.githubusercontent.com/46655/80720873-290a0600-8ac3-11ea-84b8-bbcc95a7eaf3.png)

Specs are here:

https://app.abstract.com/share/31de1afc-87d2-4a9e-9078-4d9d9831b60d?mode=build&sha=8e85755b5a9d41cd40058fab4de1acfd7c36f934

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200529-144804](https://user-images.githubusercontent.com/51314259/83257508-3519de00-a1bd-11ea-8cfb-fdf4e361c4b2.gif)
