### ISSUE TITLE
FNX-16 ⁃ Built-in updater

### ISSUE THREAD

**Issue by ReekyMarko** [mozilla-mobile/fenix#1033]
I'm surprised to see that Fenix is in this early phase a very much usable browser! So much that I actually changed my daily default browser to Fenix.

Would it be possible to create an infrastructure that allows the browser to update itself? Much like the nightly fennec browser already does.

**Comment by Vv2233Bb** [comment]
Currently there is no reason to implement it. Would take time. Not only that it probably would be removed in Google Play store version anyway. For now you should try building Fenix yourself if you haven't tried it yet.

**Comment by ReekyMarko** [comment]
Yeah makes sense. I will leave this issue here because this probably will have to be implemented at some point down the line, possibly when fenix replaces fennec in the nightly channel.

**Comment by vesta0** [comment]
Closing this issue since this has been resolved. Firefox (Fennec) Nightly now ships Fenix builds.
