### ISSUE TITLE
FNX-3440 ⁃ Tab Tray: Implement Undo Snackbar

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10332]
We should port the undo snackbar functionality to the new tab tray.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200518 from 5/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200518-111944](https://user-images.githubusercontent.com/51314259/82191183-d457ef00-98fa-11ea-8a61-fe286f0e6106.gif)
