### ISSUE TITLE
FNX-3445 ⁃ [Bug] Flash when navigating from tab tray to homescreen

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10340]
## Steps to reproduce
-Open a tab
-Close the tab
-Tap on homescreen

### Expected behavior
-Smooth transition

### Actual behavior
-White flash during transition

### Device information
* Android device: Pixel 4
* Fenix version: Tab tray build 1.0.2018

**Comment by gabrielluong** [comment]
Closing this issue this was moved over to Done. I am assuming this is no longer an issue.
