### ISSUE TITLE
FNX-3451 ⁃ Use gesture to navigate between tabs

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10346]
## User Story
As a user, I want to be able to use gestures to navigate between tabs, so I can find and process the information that I need faster. 

## Dependencies
Geckoview

### Acceptance Criteria
* I can use a gesture to navigate between tabs

**Comment by yoasif** [comment]
Maybe a dupe of #396 and #176?

**Comment by Dunexus** [comment]
Yes it is part of https://github.com/mozilla-mobile/fenix/issues/176 meta and was previously tracked by https://github.com/mozilla-mobile/fenix/issues/3481

**Comment by yoasif** [comment]
> Yes it is part of #176 meta and was previously tracked by #3481

You mean https://github.com/mozilla-mobile/fenix/issues/396 ;)
