### ISSUE TITLE
FNX-3450 ⁃ UX: Intuitive navigation between tabs and homescreen

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10345]
## User Story
As a user, I can easily navigate between homescreen and tabs, so I can take advantage of my personalized items on the homescreen for a faster browsing experience.

### Acceptance Criteria
* Navigation between tabs and homescreen is intuitive 
* User doesn't end up confused or with extra clicks to get to where they expect to go

**Comment by darkwing** [comment]
Is this something @topotropic is creating UX for or is this actionable?

**Comment by vesta0** [comment]
I chatted with @topotropic about making sure that the navigation between tabs and homescreen is intuitive navigation and she said she was going to test the current implementation before making any suggestions. It would be cool if she could run a quick user test.

**Comment by liuche** [comment]
Ping @mcomella when feature is stable for perf testing.
