### ISSUE TITLE
FNX-3446 ⁃ Tab Tray: Add "Collections placeholder/description" to the homescreen

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10341]
## User Story
* As a user, I want to learn about Collections on the homescreen, so I can take advantage of this feature. 

Note: The solution doesn't need to be exactly the same as what we have on the homescreen today.

### Acceptance Criteria
* I can see a "collections placeholder/description" on the homescreen.

**Comment by gabrielluong** [comment]
Closing this since the PR has already been landed.
