### ISSUE TITLE
FNX-3447 ⁃ Populate top sites with frequently opened sites

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10342]
### User Story
As a user, I want to see my frequently accessed sites on the homescreen in a useful way, so I can reference them to complete my routine tasks faster. 

### Dependencies
* [ ] https://github.com/mozilla-mobile/android-components/issues/7261
* [x] https://github.com/mozilla/application-services/issues/2163
* [x] https://github.com/mozilla-mobile/android-components/issues/7094

### Acceptance Criteria
* I can disable this feature
* If enabled, I see my frequently accessed sites on my homescreen
* There is a cap on # of automatically generated top sites to avoid cluttering the homescreen
* Users can turn off this feature in settings (just the auto-populated top sites, not the user added ones) (This is a requirement for shipping this feature) 
* I can customize how my top sites show up on the homescreen (e.g. choose how many sites or rows to see)

Nice to have:

* Ability to rename top sites #9548
* Rearrange Top Sites items #8305

**Comment by cadeyrn** [comment]
Can you please make this an optional feature? I really don't want my homescreen cluttered with auto-populated sites. It's always the first thing I disable in new installations of Firefox on desktop systems and Firefox for Android should allow to disable this, too. Thanks!

**Comment by vesta0** [comment]
@cadeyrn thanks for the feedback! I added that to the acceptance criteria.

**Comment by Kreuger** [comment]
I would also like to see some news articles featured like Kiwi Browser has.

**Comment by cadeyrn** [comment]
News articles seems more something for #6416. This issue is about the top site thumbnails - there is no space for a headline or text.

**Comment by liuche** [comment]
This is partly there, and gl can do a demo on 6/5 to decide whether to put this into release, and will need to fix fallout during codefreeze time (40% confidence that good enough right now), or can be a fast-follow after releaese.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

🚩 Flag added 

null

**Comment by binocry** [comment]
hi so will this implemented to fenix?

**Comment by gabrielluong** [comment]
> hi so will this implemented to fenix?

Yes.

**Comment by gabrielluong** [comment]
Feature is currently hidden behind the Secret Menu to display visited sites.

**Comment by Matth7878** [comment]
Having tested it I am wondering if it should not be apart from top sites : they have been limited to 8 (x2) and that's not a lot.
And for people not wanting it it may be easier to turn it off?

Besides it didn't matter for top sites but for frequent sites having a thumbnails instead of an icon would really be better. You may not be as familiar with them than you are with top sites.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200827 (Build #2015760379).
### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by madb1lly** [comment]
Hi @Matth7878,

I agree, I don't know what half of those frequently visited sites are from the icon that's used! 😆

Cheers 🙂
Cheers 🙂

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Preview Beta 81.1.0-beta.1. The patch notes for this build contain this fix but the top sites are not populated with the most visited websites and the Secret settings menu is blank.
### Devices used:
- Huawei MediaPad M3 (Android 7.0)
- OnePlus 6T (Android 9)

**Comment by cadeyrn** [comment]
> The patch notes for this build contain this fix but the top sites are not populated with the most visited websites and the Secret settings menu is blank.

Maybe you have to enable the option in the customize settings as well. It seems to be disabled by default.

**Comment by LaurentiuApahideanSV** [comment]
The option is not present in the Customize Settings menu, I have reopened issue https://github.com/mozilla-mobile/fenix/issues/14119 regarding this.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Beta 81.1.0-beta.2 (Build #2015761657).
### Devices used:
- Huawei MediaPad M3 (Android 7.0)
- OnePlus 6T (Android 9)
