### ISSUE TITLE
FNX-3452 ⁃ [Bug] Intermittent test failure org.mozilla.fenix.perf.StartupHomeActivityLifecycleObserverTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#10348]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=300287785&repo=fenix

[task 2020-04-30T21:05:32.029Z] SUITE: org.mozilla.fenix.perf.StartupHomeActivityLifecycleObserverTest
[task 2020-04-30T21:05:32.029Z]   TEST: WHEN onStop is called THEN the metrics are set and the ping is submitted
[task 2020-04-30T21:05:32.129Z]     I/AssetManager: no overlays.list file found
[task 2020-04-30T21:05:32.329Z]     D [BrowserIcons] Loaded icon (source = GENERATOR): https://mozilla.com
[task 2020-04-30T21:05:32.429Z]   FAILURE
[task 2020-04-30T21:05:32.530Z] 
[task 2020-04-30T21:05:32.530Z] java.lang.AssertionError: Verification failed: number of calls happened not matching exact number of verification sequence
[task 2020-04-30T21:05:32.530Z] 
[task 2020-04-30T21:05:32.530Z] Matchers: 
[task 2020-04-30T21:05:32.530Z] StartupFrameworkStartMeasurement(frameworkStartMeasurement#212).setExpensiveMetric())
[task 2020-04-30T21:05:32.530Z] PingType(startupTimeline#213).submit(null()))

**Comment by eliserichards** [comment]
@mcomella this is a performance test, right?

**Comment by mcomella** [comment]
> @mcomella this is a performance test, right?

In a manner of speaking – we usually say "performance test" to mean a benchmarking test but this is a test for code related to performance. Sorry to be annoying 😅

I added this to the FE perf board for triage.

**Comment by mcomella** [comment]
@Archaeopteryx Do you know how frequently this fails?

**Comment by mcomella** [comment]
This failed once ever according to [this query](https://sql.telemetry.mozilla.org/queries/70708): this doesn't really classify as an intermittent to me so I'm going to close.
