### ISSUE TITLE
FNX-4740 ⁃ Fenix unexpectedly closes in Android Q

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1035]
### Steps to reproduce
Open Fenix.

### Expected behavior
Fenix opens and can be used.

### Actual behavior
After opening the app it minimizes.

### Device information
* Android device: Google Pixel (Android Q Beta)
* Fenix version: 1.0.1911 (#10731207)
* Also reproducible for RB, fennec does not have this issue.
* [Logcat](https://github.com/mozilla-mobile/fenix/files/2971058/log.txt)
* [Video](https://drive.google.com/open?id=1ciZCnYyr0OhRvLN0iOWg7ehkgrif7dJX)

**Comment by cpeterso** [comment]
This crash might be related to GV crash https://bugzilla.mozilla.org/show_bug.cgi?id=1535139

**Comment by kbrosnan** [comment]
This is fixed with current GeckoView builds.
