### ISSUE TITLE
FNX-3459 ⁃ [Bug] Touch area of bottom-most 3-dot context menu items is too small

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#10359]
## Steps to reproduce
* Load a page
* Open 3-dot context menu
* Click just below the bottom-most icons (e.g. bookmarks, share) on the 3-dot context menu

### Expected behavior
Action from context menu occurs

### Actual behavior
Nothing happens

Video: https://drive.google.com/file/d/1gtUWSi59ezqD4ZrjuCwAawxm8desn-pB/view?usp=sharing

Screenshot from the video:
![Screen Shot 2020-05-01 at 15 37 49](https://user-images.githubusercontent.com/759372/80846637-c0558300-8bc1-11ea-94a8-55dfb89aca25.png)

### Device information
* Android device: P2
* Fenix version: 75.0.0-beta.6

**Comment by mcarare** [comment]
Closing as fixed, same issue as https://github.com/mozilla-mobile/fenix/issues/9660.
