### ISSUE TITLE
FNX-4741 ⁃ [Bug] Navigating home from tab tray flashes the browserFragment

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#10351]
![ezgif-6-9ce38633b833](https://user-images.githubusercontent.com/1250545/80824615-ab61fb00-8b93-11ea-81f4-c725828fc2b6.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200511 from 5/11`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200511-174643](https://user-images.githubusercontent.com/51314259/81576152-9154c380-93b0-11ea-840d-f407224038df.gif)
