### ISSUE TITLE
[Request] Please support "Video Background Play Fix" Add-on

### ISSUE THREAD

**Issue by charlieethan** [mozilla-mobile/fenix#10366]
### Why/User Benefit/User Problem
* Some sites do not allow users to play videos in the background or lock screen, like Youtube
    1. What/Requirements
* "Video Background Play Fix" Add-on
* The project of this Add-on on [Github](https://github.com/mozilla/video-bg-play)
* The address of this Add-on on [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/video-background-play-fix/)
    1. Acceptance Criteria (how do I know when I’m done?)
* Can use this Add-on in the next version

**Comment by amkcpu** [comment]
This add-on is actually being recommended as a solution to this problem at support.mozilla.org (see https://support.mozilla.org/en-US/kb/some-videos-wont-play-background).

> As an example, an extension can listen for and intercept visibilitychange and fullscreenchange events so a website will not be able to react to a tab being hidden.
>
>Please visit Video Background Play Fix to see or install an example of such an extension.

**Comment by yoasif** [comment]
This has been enabled in Nightly. 

However it times out after some time on YouTube, likely due to https://github.com/mozilla-mobile/fenix/issues/9691

**Comment by csadilek** [comment]
Closing as add-on is available in Nighty and Beta and will roll out to next release.
