### ISSUE TITLE
FNX-3475 ⁃ [Bug] Tab tray buttons have bad contrast in dark theme with on screen buttons

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10369]
## Steps to reproduce
1. Ensure you have on screen buttons enabled in Android
1. Tap open tabs

### Expected behavior 
update from @topotropic / UX:
Use a divider line in dark_grey_10 between Android buttons and Fenix UI (similar to what we have on content pages).

### Actual behavior
![signal-attachment-2020-05-02-115229](https://user-images.githubusercontent.com/152493/80869176-d5d3b700-8c6c-11ea-9e8f-a5cc4f8b5eb3.png)

The tab tray buttons blend in with the Android buttons. 

### Device information
* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by cadeyrn** [comment]
> There should be some separation between app UI and Android UI.

There is no visual separation on the start screen and no visual separation in the settings. Why should there be a visual separation in the tabs tray? That's unexpected to me. 🤔

**Comment by yoasif** [comment]
> > There should be some separation between app UI and Android UI.
> 
> There is no visual separation on the start screen and no visual separation in the settings. Why should there be a visual separation in the tabs tray? thinking

@cadeyrn It looks very weird to me, especially with https://github.com/mozilla-mobile/fenix/issues/10370 - it just looks like a random assortment of buttons that are stacked above each other. 

Why is there a separation between the toolbar and pages? :smile:

**Comment by topotropic** [comment]
will be addressed with https://github.com/mozilla-mobile/fenix/pull/10326

**Comment by yoasif** [comment]
Thanks @topotropic!
