### ISSUE TITLE
[Feature request] Delete site data for individual sites

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#10363]
Hey guys is it possible that we could be able to delete site data like cookies from individual sites? Sometimes I have an issue with a website and need to clear the cookies but don't want to remove them for every site.

**Comment by Kreuger** [comment]
Hello had there been any progress made for this?

**Comment by Kreuger** [comment]
I was browsing my system and came across where my profile data is stored. In the subfolders from there is /storage/default and inside there are subfolders for every site I have visited. They each contain a file called .Metadata-v, and another folder which has one inside called ls. In there is 2 files. One is data.sqlite and the other is usage. If I delete the folder for this website, would it then allow me to start fresh, in the same way as if I were to delete the data from within the browser itself?

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/9294
