### ISSUE TITLE
FNX-3472 ⁃ Tabs Tray - ability to drag list down to reach top tabs with one hand

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#10367]
### Why/User Benefit/User Problem
Prototype tabs tray. It's hard to reach the topmost tabs one-handed

### What/Requirements
Ability to pull the list downwards so the topmost tabs are within one handed reach. Could fill in the blank space above the list with a Firefox logo. Somewhat like the current Home screen.

### Acceptance Criteria (how do I know when I’m done?)
Can pull list down so can reach all tabs in the list one handed

Thanks!

**Comment by topotropic** [comment]
You can do it with the dedicated tab tray, I'll close this issue – feel free to open a follow-up. Thanks!
