### ISSUE TITLE
Collections should be integrated into Tab Tray

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10372]
### Why/User Benefit/User Problem
As a user, I would like to easily access tabs stored in collections directly from my tab tray. 

### What/Requirements
* I should be able to open tabs from collections in the tab tray
* opening a tab from a collection should not duplicate the tab in my tab tray

Chrome is working on this in Dev and it looks good, although I have issues with it. 

![signal-attachment-2020-05-02-123504](https://user-images.githubusercontent.com/152493/80869979-73c98080-8c71-11ea-92c0-f3e5fdca36e8.png)

### Acceptance Criteria (how do I know when I’m done?)
User does not have to go to about:home to access tabs in collections; they can do it directly from within tab tray.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-448)

**Comment by venetian-ftaires** [comment]
This sounds good yes, collections need to be more integrated into the browsing experience. 

This gained some decent traction/discussion when I mentioned it on r/firefox: https://www.reddit.com/r/firefox/comments/h7kzp4/collections_in_firefox_preview_for_android_great/

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812752

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
