### ISSUE TITLE
[Bug] Push tabs to Android device fails

### ISSUE THREAD

**Issue by Ramzh** [mozilla-mobile/fenix#10379]
## Steps to reproduce
Use Firefox on Desktop and Fenix on Android. Send a tab from Desktop to Android and viceversa for issue #1 (see Actual Behavior). Check History in Firefox Fenix on Android and try to open a site previously visited on Desktop. Firefox Account required and signed in both on Desktop and Android

### Expected behavior
1: 

* Tab should show up immediately if sent from Android to Desktop. 
* Notification on Android should appear immediately if tab is sent from Desktop to Android.

2: Previously visited sites and searches should be able to be visualised in History on the mobile application.

### Actual behavior
1: Firefox can't seem to sync tabs when I send them. Sometimes it does sync to the mobile > desktop but it never syncs desktop > mobile. I have to always go in settings and force sync everything on mobile to show up the notifications and sometimes on desktop to see the new sent tabs from mobile.

2: I cannot see my Firefox desktop history on mobile. Why? Let's say I want to open up a website from my desktop history but I have only my phone with me, how can do it?

### Device information
* PC Desktop: Firefox 75.0 (64-bit)
* Android device: OnePlus 7 Pro - Android 10
* Fenix version: Firefox Preview 4.3.0

**Comment by kbrosnan** [comment]
Does your device have Firebase Cloud Messaging, part of Google Play Services? It is required for [Push on Android](https://mozilla.github.io/application-services/api/push_bridge.html)

**Comment by Ramzh** [comment]
@kbrosnan Yes, it does
