### ISSUE TITLE
FNX-4743 ⁃ Location bar in Twidere Custom Tab has unreadable URL

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1037]
## Steps to reproduce
1. Install Twidere from F-Droid (version 3.7.3)
1. Open a link within a Fenix custom tab - a web URL works for this

### Expected behavior
The location should be easy to read.

### Actual behavior
The location loaded is very hard to read. 

![twidere-fenix](https://user-images.githubusercontent.com/152493/54443123-658b6e80-4716-11e9-9da6-e0abf47a4fd5.png)

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1911 (Build #10741206 :lizard: 67.0a1-20190312095443)

**Comment by sblatz** [comment]
Will be addressed in https://github.com/mozilla-mobile/fenix/issues/668
