### ISSUE TITLE
[Bug] setTimeout and setInterval not honored (under events, possibly)

### ISSUE THREAD

**Issue by vandys** [mozilla-mobile/fenix#10375]
## Steps to reproduce
Web app with a "push to talk" type UI.  Within the touch-down event, an interval starts to display a running time count.

### Expected behavior
The 1 second interval should be called each roughly second, and update the counter.

I've stripped the app down to just this part of the code:

https://vsta.org/andy/bug5/

(I've stripped out the mouse handling, so use a mobile browser, or desktop responsive debug mode.)

### Actual behavior
The interval handler is never called.  Additionally, I notice that a setTimeout on finger up is also never called.  I've verified a proper ID value returned from the setInterval.  No error on console.

If you use desktop--even under responsive debugging--it works correctly.  It also works on Chromium mobile.

### Device information
* Android device: Nextbit Robin, LineageOS Pie (arm64)
* Fenix version: 5.0.0

**Comment by michaeldel** [comment]
I have the exact same issue on Firefox 85.1.1, `setTimeout` stops working on a tab after some time, but it does not happen regularly enough for me to provide more precise contextual information.

As far as I remember refreshing a page or switching tabs did not fix it, and I had to fully close the tab and reopen it at the same URL for `setTimeout` to work again. Maybe originating from a per-tab CPU-usage saving optimization ?
