### ISSUE TITLE
FNX-3481 ⁃ Open new tab via contextual menu on open tabs/tab switcher

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10374]
### Why/User Benefit/User Problem
I would like to quickly open a new tab without needing to move to a new screen. Competing browsers have this feature. 

### What/Requirements
* Long press the tab switcher/open tabs button, menu appears with "new tab, new private tab" options. 
* the user is taken to the new tab

### Acceptance Criteria (how do I know when I’m done?)
Long pressing the button shows a menu from where I can open a new tab and be moved to it without other intermediary steps. 

Like Chrome. 

![signal-attachment-2020-05-02-142104](https://user-images.githubusercontent.com/152493/80872480-33253380-8c80-11ea-9d70-5c2862124afe.png)

**Comment by liuche** [comment]
We could match what is done in other browsers, with some fine tuning during implementation.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build created on 6/12 with GV 79.0a1, AS 60.0.0, using:
- Samsung Galaxy Note 8 (Android 9),
- Sony Xperia Z5 Premium (Android 7.1.1), 
- HTC 10 (Android 8),
- OnePlus 5T (Android 9).
