### ISSUE TITLE
FNX-3477 ⁃ Review top/bottom bar design for tab tray nav

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10370]
## Steps to reproduce
1. Ensure you have on screen buttons enabled in Android
1. Tap open tabs

### Expected behavior
Buttons should not appear directly above Android UI buttons. Some more visually pleasing arrangement. Fennec did a better job here. 

![signal-attachment-2020-05-02-120648](https://user-images.githubusercontent.com/152493/80869252-75914500-8c6d-11ea-8f3d-f536b220a9e5.png)

### Actual behavior
Buttons appear directly above Android UI buttons and aren't laid out as well as Fennec. 

### Device information
* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by cadeyrn** [comment]
I disagree. The buttons are exactly where I expect them, especially as a user of Fenix with the bottom toolbar (default behaviour). The buttons has to be at the bottom to make it easy to use Fenix with one hand - which is one of the main arguments for the bottom toolbar. Your screenshot of Fennec shows the buttons on the top which is definitively not what I want.

**Comment by yoasif** [comment]
@cadeyrn I don't think they have to be on the top, I was just showing an example of something that Fennec did better. 

Here is reference browser, which is similar to Fennec but with the bottom buttons. 

![signal-attachment-2020-05-02-133748](https://user-images.githubusercontent.com/152493/80871364-256caf80-8c7a-11ea-918c-418aa1565a1d.png)

**Comment by cadeyrn** [comment]
> I was just showing an example of something that Fennec did better.

To be honest I don't see anything better, neither in the Fennec nor in the Reference Browser screen. In my opinion the current design is the most balanced design - and it's very similar to the design of the bottom bar in Firefox Lite.

**Comment by yoasif** [comment]
@cadeyrn I said *directly* above and I specifically used the word alignment and not something like placement. 

I'll have to look at Firefox Lite - I have heard bad things about it, but worth a look, I suppose. 

I'm also not entirely sure how the current design is simpler than the reference browser design when the current design puts both the kebab menu and the back button at the top of the screen (a place you dislike), and the reference browser does not.

**Comment by yoasif** [comment]
@cadeyrn Firefox Lite is not like Fenix here. 

The buttons are not aligned with the Android navigation buttons and they also have very clear separation from them by using contrasting background colors. 

![signal-attachment-2020-05-02-135815](https://user-images.githubusercontent.com/152493/80871998-31a63c00-8c7d-11ea-868c-6083b1683171.png)

**Comment by yoasif** [comment]
This has been improved in the latest builds.
