### ISSUE TITLE
FNX-3493 ⁃ Should there be a uniqueness requirement for Top Sites?

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#10386]
### Why/User Benefit/User Problem
If I visit a site and select "Add to top sites", I am able to continue selecting it multiple times, and it does indeed get added to Top Sites every time. This clutters up the Top Sites section with unnecessary duplicates.

### What/Requirements
I feel like the menu option should be hidden/disabled if the current URL is already in Top Sites, or it could refuse to re-add it to Top Sites (with an "already a top site" notification), or prompt the user with "[url] already a top site, want to duplicate it?" choice. 

### Acceptance Criteria (how do I know when I’m done?)
Decision is made on how duplicates are handled for Top Sites and Fenix follows that decision.

**Comment by topotropic** [comment]
Thanks for the feedback!

We can follow the Firefox desktop or iOS pattern here and replace the menu entry for already added top sites to something along the lines of "Remove top site" or "Remove from top sites" cc @betsymi

**Comment by betsymi** [comment]
Menu entry: `Remove from top sites`
Snackbar after this action: `Removed from top sites!`

**Comment by kbrosnan** [comment]
Duplicate #8108
