### ISSUE TITLE
FNX-3490 ⁃ [Telemetry]

### ISSUE THREAD

**Issue by Aurenito** [mozilla-mobile/fenix#10382]
Owner: Product Manager

#### Description & Product Manager / Data Scientist User Story
* As a product owner, I want to know if people type use feature X so I can...

#### Hypothesis
* We believe this feature is useful to users, and successful when
...

#### What probes (suggested, if applicable)
* 

### Acceptance Criteria (Added by PM)
* Event pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by kbrosnan** [comment]
Not a correctly filed issue.
