### ISSUE TITLE
FNX2-13153 ⁃ [Bug] Pressing back on external tab does not go back to previous app

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#10394]
## Steps to reproduce
* Open a link from a third-party app (VIEW intent, not a custom tab!)
* Press "back" button

### Expected behavior
* Tab is closed
* User is returned to third-party app

### Actual behavior
* Tab is closed
* User is returned to home screen.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200716 from 7/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200716-103914](https://user-images.githubusercontent.com/51314259/87642076-b6b7d200-c751-11ea-93ba-130736fe4394.gif)
