### ISSUE TITLE
FNX-3501 ⁃ [Bug] Collections not listed when adding from directly opened tab

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#10393]
## Steps to reproduce
* Browser is closed and not running
* Share a link from an app to Fenix (In my case it is from a reddit app)
* Open menu and select "Save to collection"

### Expected behavior
List of collections show up and I can add the page to an existing collection.

### Actual behavior
List of collections is empty and I only have the option to create a new collection. Note that after going to the home screen and back to the tab, my collections are shown when selecting "Save to collection" again.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 5/19 Nightly build and on Beta 5.1.0-beta.1 with Samsung Galaxy Tab S6 (Android 9), Google Pixel (Android 10), HTC 10 (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).
