### ISSUE TITLE
FNX-3508 ⁃ [Bug] No indication that WebExtensions don't run in private browsing mode

### ISSUE THREAD

**Issue by Rob--W** [mozilla-mobile/fenix#10398]
Related: #6123 (introduced the ability to turn off add-ons in private browsing mode)
Related: #10140 (user confusion)
Related: #10244 (indicator in addon list that shows whether access to private browsing is allowed)

## Steps to reproduce
Install an addon, e.g. uBlock Origin.

### Expected behavior
The user should be notified that the add-on does not have access to private browsing mode, with an opt-in. On Firefox desktop, there is a post-install doorhanger where the user can tick a checkbox to allow access: https://support.mozilla.org/en-US/kb/extensions-private-browsing#w_granting-permission-on-installation

![](https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2019-03-20-06-49-11-13b544.png)

### Actual behavior
There is no indication whatsoever that the newly installed add-on isn't able to access content that runs in private browsing mode.

### Device information
* Android device: ?
* Fenix version: Nightly 200503 06:01 (build #21240608)

**Comment by brampitoyo** [comment]
@eliserichards One of my initial thinking about add-ons and private mode was https://github.com/mozilla-mobile/fenix/issues/6123#issuecomment-619659103:

> I think that many users’ expectation is for add-ons to work everywhere by default [ie. enabled in private mode], but also for those add-ons to not leak data while browsing privately.

@csadilek’s response was https://github.com/mozilla-mobile/fenix/issues/6123#issuecomment-620046041:

> I think defaulting to "false" is the right thing to do here, so users can opt-in, as desired. Having a list of recommended and tested extensions protects us from this somewhat, but it still could become a problem later. So, I'd vote for being conservative and use the same default as Desktop.

At the end of the add-on install process, we’ve shown a non-blocking snackbar. To solve this problem, this snackbar will need to be changed into a blocking modal bottom sheet. This way, users will be given a chance to permit add-ons to run in private mode.

Stay tuned for the design of this modal bottom sheet!

**Comment by brampitoyo** [comment]
@Amejia481 modal bottom sheet mockup attached below.

<img width="360" src="https://user-images.githubusercontent.com/51007/81117233-d9bc4d80-8f7a-11ea-81a1-2aabb48a22dd.png">

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200515 from 5/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200515-111825](https://user-images.githubusercontent.com/51314259/82029228-5b109000-969f-11ea-894a-c6c2abac84ae.gif)
