### ISSUE TITLE
FNX-17 ⁃ As a User I want to easily migrate my data from Fennec to Fenix

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#104]
The answer her could be Firefox Account.

**Comment by telans** [comment]
> The answer her could be Firefox Account.

+1 to the idea of migrating all data, however I'd rather not sign up to *another* pointless (for my use case) service. Copying and pasting a profile or history & bookmark data would be so much simpler and require no account.

**Comment by vesta0** [comment]
We will address this in #879
