### ISSUE TITLE
FNX-3523 ⁃ [Bug] Unable to download PNG image

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#10409]
## Steps to reproduce
1. Go to [this link](https://ourworldindata.org/grapher/total-confirmed-cases-of-covid-19-per-million-people?year=2020-05-04).
1. Tap the download button below the map.
1. Tap "Save as .png".
1. Tap "Download"

### Expected behavior
Downloads a PNG image.

### Actual behavior
Gives a "Firefox Nightly can't download this file type" error.

### Device information
* Android device: Huawei Mate 20, Android 10
* Fenix version: Firefox Preview Nightly 200504 06:01 (Build #21250608)

**Comment by Amejia481** [comment]
The url is pointing at is a blob blob:https://ourworldindata.org/0e9709aa-4b4c-594a-9d85-0a4c6c3e5150

We are following that work on this ticket https://github.com/mozilla-mobile/android-components/issues/1159

**Comment by anotherus3r** [comment]
@Amejia481 Is #10410 maybe related?

**Comment by Amejia481** [comment]
> @Amejia481 Is #10410 maybe related?

Thanks for filing the issue, It's similar but it is a different bug that you have to address we can keep it open!
