### ISSUE TITLE
FNX-3519 ⁃ [Bug] Incorrect touch animation on new tab button

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10406]
## Steps to reproduce
1. Hold the + button (add tab) in bottom toolbar on homescreen
1. Observe shadow

### Expected behavior
Touch animation shows above button

### Actual behavior
Shadow appears behind the button
![Screenshot](https://user-images.githubusercontent.com/33252312/80996578-8db0c200-8e2f-11ea-83ab-6cb96c13136d.png)UNITO-UNDERSCORE!20200504-222535!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus zenfone
* Fenix version: fenix nightly

**Comment by s-ankur** [comment]
Also 3 dot menu on a webpage has a shadow but the three dot menu in overview does not have shadow so there is some inconsistency

**Comment by eliserichards** [comment]
We should investigate if this is just happening in dark mode, or if regular/private browsing modes have the same inconsistency.

**Comment by s-ankur** [comment]
Seems to be an issue in both light and dark modes and PB

**Comment by AmyYLee** [comment]
Hi, this is a bug. The touch target should be on top of the button. The shadow behind the search bar should on when on a website should also be applied to the homescreen search bar in light/dark themes.

**Comment by s-ankur** [comment]
Hi, closing as no longer applicable
