### ISSUE TITLE
FNX-3515 ⁃ [Bug] If you have only one search engine it still shows this time search with option during search

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10401]
## Steps to reproduce
Delete all search engines except one
Open search

### Expected behavior
No prompt

### Actual behavior
This time seach with[the engine im already seaching with] prompt

### Device information
* Android device: Asus Zenfone M1
* Fenix version: fenix Nightly

**Comment by AmyYLee** [comment]
Assigned to @brampitoyo

**Comment by brampitoyo** [comment]
@s-ankur Agreed. If users only have one search engine, it doesn’t make sense to show “This time, search with” on the search screen. In fact, it doesn’t make sense to have the “🔍 Shortcuts” button.

So my recommendation is as follows:

IF only one search engine is installed
THEN don’t show or select “🔍 Shortcuts” button on the search screen

By not displaying the search shortcuts button, the heading “This time, search with” will also not show up.

**Comment by s-ankur** [comment]
@brampitoyo one more suggestion, the search engine that is default shouldnt appear in this time search with, as you are already searching with it

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200707 GV 80, from 7/7 with Google Pixel 2 (Android 9), Huawei P9 Lite (Android 7).
I filed a new issue for the missing "Search engine settings" when there is only one search engine: https://github.com/mozilla-mobile/fenix/issues/12335.
