### ISSUE TITLE
FNX-3521 ⁃ [Bug] Crash on Rapid selection of "Tabs" and three dot menu

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10408]
## Steps to reproduce
Quickly tap on on tabs and three dot menu while a webpage is open
Wrong type of three dot menu appears in the overview 
![Screenshot](https://user-images.githubusercontent.com/33252312/80999721-aa032d80-8e34-11ea-890e-13c8408b30be.png)UNITO-UNDERSCORE!20200504-235503!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

Click on any button and firfox crashes

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment]
Doing the same with the sheild icon and the tabs button directly crashes firefo

**Comment by abodea** [comment]
I re-checked this issue on the latest Nightly from 5/6 with Google Pixel 4 XL (10).
Note that the 3 dot menu is still displayed on the home screen, but the PR for that is not merged. I will confirm this issue once that issue is fixed too.

**Comment by abodea** [comment]
Verified as fixed on latest Nightly 5/7 with Google Pixel 4 XL (10).
