### ISSUE TITLE
FNX3-13884 ⁃ [Bug] Opening app crashes and restarts tablet pc

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#10418]
## Steps to reproduce
Install Firefox Preview app from google play to a tablet, open the app, watch tablet restart.

### Expected behavior
Upon pressing the app icon, It should open the browser. not crash the tablet.

### Actual behavior
I press the FF Preview app icon, it opens white window, then after 5s it crashes the tablet pc into restart. This is the only app or anything that does this _FF Nightly for developers_ vNightly 200505 also does this. Regular FF/chrome and other browsers work normally.

### Device information
* Android device: Sony Xperia Tablet Z LTE (pollux)
* Fenix version: 4.3.0
* OS: LineageOS 15.1 (official, stable)

**Comment by eliserichards** [comment]
Closing as a duplicate #5663 and  https://bugzilla.mozilla.org/show_bug.cgi?id=1604056
