### ISSUE TITLE
FNX-4264 ⁃ [Bug] Downloading jpg from Fx Send not working

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#10421]
(reported by István Szmozsánszky :flaki)

Hey Folks!
Here's what I'm trying to accomplish: send a JPG image file from my desktop to my Fenix Nightly on my phone. 

* I upload the file to Firefox Send, get a link, copy it, paste it into the URL bar and open it
* Right click the tab ~~> send to device~~ > Fenix on Flaki's Phone
* The push notification is received, I open it.
* I click Download on the Firefox Send page.
* Fenix tells me me: `mnl.jpg 0.60MB. Download?`
* I click Download, I immediately get a popup notification briefly displaying: "Firefox Nightly can't download this file type."

I have all links open in Private Mode Fenix, so I tried copying the URL after I receive it and reopening it in non-private mode but it doesn't make a difference, same error.
I checked, I have all permissions allowed for Firefox Nightly. I just tried to update to the latest Nightly from the store but same error also. Running Android 10 on a Pixel 3.

![Screenshot](https://user-images.githubusercontent.com/43795363/81093881-593d1480-8ec8-11ea-882e-f618912b2e92.png)UNITO-UNDERSCORE!20200505-122441!
![Screenshot](https://user-images.githubusercontent.com/43795363/81093885-5c380500-8ec8-11ea-86fe-599f7746bd7f.png)UNITO-UNDERSCORE!20200505-122438!

(and yes if I copy-paste the received link over to Chrome the download works just fine)

**Comment by cadeyrn** [comment]
@eliserichards see also #3336 and https://github.com/mozilla/send/issues/1404.

**Comment by kbrosnan** [comment]
Yes this is a dupe.
