### ISSUE TITLE
FNX-4282 ⁃ [Bug] Browser Toolbar related crashes in 5.0.0 build (PiP)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#10433]
Going through the Sentry issues, and it looks like there are a few that seem to be Browser Toolbar related.

[IllegalStateException](https://sentry.prod.mozaws.net/operations/fenix/issues/8256131/): Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()

[Unable to pause activity ](https://sentry.prod.mozaws.net/operations/fenix/issues/8264980/){org.mozilla.fenix/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity}: kotlin.KotlinNullPointerException and [onFullscreenChanged ](https://sentry.prod.mozaws.net/operations/fenix/issues/8277631/)(2 crashes, may be related)

**Comment by liuche** [comment]
Going to throw a Release Blocker label on here because they seem new, but can be removed pending more information.

**Comment by sblatz** [comment]
I'll investigate this second crash.

**Comment by sblatz** [comment]
These are related to changes we made with picture in picture mode. Currently investigating with Emily. It doesn't seem to happen in PWA or Custom tab which I expected to be the more edge case here. The breadcrumbs point to it being in a normal browsing session, though. Cannot find STR just yet.

**Comment by liuche** [comment]
@sblatz @ekager release-blocker level, or not? If it's turning out to be very hard to repro, I'm fine downgrading it to something less serious and picking it up this upcoming sprint.

**Comment by sblatz** [comment]
It doesn't feel like a release blocker to me. I can't repro. Curious what @ekager thinks? 

It seems like a relatively small % of crashes no?

**Comment by ekager** [comment]
Yeah I can't repro either but a bit concerned about the second  one since it's slightly higher numbers :/
kotlin.KotlinNullPointerException / onFullscreenChanged 

I will look at this this afternoon

**Comment by liuche** [comment]
Okay, I'll bump Fenix to 50% and see if these numbers go up more.

**Comment by ekager** [comment]
Okay [comparing this crash to the Sentry Nightly data crash tail](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7931743/?query=is%3Aunresolved%20KotlinNullPointerException), we think that the `KotlinNullPointerException` is fixed by https://github.com/mozilla-mobile/fenix/commit/38e9b3465975a09e8ef8be0802bbda62c406404c (which was landed right after cutting 5.0).

**Comment by liuche** [comment]
Okay, in that case, I'm going link to #10306 and close this bug. We can reopen if it shows up in 5.13
