### ISSUE TITLE
FNX-4280 ⁃ [Bug] Intermittent Downloads Getting Stuck

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/fenix#10430]
## Steps to reproduce
See: https://appbot.co/apps/2101759-firefox-preview/reviews/1619493243
" Downloads gets stuck most times which gives me data loss as well as my time"

### Device information
* Android device: ?
* Fenix version: ?

**Comment by kglazko** [comment]
Could not reproduce on a Pixel 4 even with big files.

**Comment by Amejia481** [comment]
Related AC change https://github.com/mozilla-mobile/android-components/pull/6894 and Fenix issue https://github.com/mozilla-mobile/fenix/issues/9884#issuecomment-620526820

**Comment by softvision-miralobontiu** [comment]
I cannot reproduce the issue on the latest Nightly from 5/8 with Sony Xperia Z5 Premium (Android 7.1.1). I downloaded multiple files, big and small ones. Everything worked as expected.
I'll remove the qa-needed label, and close the issue.
Feel free to reopen or file a new issue, maybe with a link, if this occurs again.
