### ISSUE TITLE
FNX-4751 ⁃ [Bug] Open links in apps doesn't work on some websites

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10436]
## Steps to reproduce
Have the "Open links in apps" setting tuned on

Go to : https://www.apkmirror.com/apk/mozilla/firefox-preview-nightly-for-developers/firefox-preview-nightly-for-developers-nightly-200505-0600-release/

And click on Play Store icon and notice that it doesn't redirect to the Play Store app but instead it opens the website

And

Go to: https://mobile.twitter.com/anime_kaguya/status/1240565167080931328

Click on YouTube link and notice that it doesn't redirect to the YouTube app but instead opens the website

### Expected behavior
When clicked on the link it should open the corresponding installed apps and not the websites. The links open in apps in Chrome browser

### Actual behavior
Links open in websites instead of installed/corresponding apps

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: 76.0.0-beta.1 (Build #2015737667) 
![20200506](https://user-images.githubusercontent.com/42088907/81145819-9821a780-8f66-11ea-95e9-4cfca45068b1.gif)UNITO-UNDERSCORE!122406!

**Comment by LaurentiuApahideanSV** [comment]
The issue has also been reported here: https://github.com/mozilla-mobile/fenix/issues/9923. I will close this issue as it will he handled there.

**Comment by rocketsroger** [comment]
Confirmed that this is the same issue as https://github.com/mozilla-mobile/fenix/issues/10838.
Closing and track with https://github.com/mozilla-mobile/fenix/issues/10838.  Thanks for bring this to our attention.
