### ISSUE TITLE
FNX3-13890 ⁃ two close buttons in custom tabs

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1043]
### Steps to reproduce
1. open a link in an external app with custom tab support

### Expected behavior
one close button

### Actual behavior
two close buttons

![Screenshot](https://user-images.githubusercontent.com/1100614/54460229-3eaa5800-4769-11e9-8904-2cbeb49966d8.png)UNITO-UNDERSCORE!20190315-212400!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 72b9d4ebdb3f9d9baeb849b3933efdd6eb915cf7

**Comment by sv-ohorvath** [comment]
Verified as fixed on master build 3/18.

**Comment by sv-ohorvath** [comment]
@jonalmeida I tested on a local build. Nightly didn't build since 2 days ago, probably it didn't catch the last build. I notified the team about nightly. Hopefully, it will be fixed soon.

**Comment by jonalmeida** [comment]
@sv-ohorvath thank you! I'll close this back again then since you've verified this locally.
