### ISSUE TITLE
FNX-4285 ⁃ [Feature request] Add the legacy Firefox 3 tabs: topsites, bookmarks, history

### ISSUE THREAD

**Issue by FenixRevival** [mozilla-mobile/fenix#10437]
### Why/User Benefit/User Problem
Faster to switch between top visited websites, bookmarks, history with less touch than now

### What/Requirements
Adding 3 tabs

### Acceptance Criteria (how do I know when I’m done?)
When it works :grinning:

**Comment by eliserichards** [comment]
Hi @Phenix-Feedback! Can you add a little bit more information here? What do mean by "Adding 3 tabs" in the Requirements section? Thanks! 😄

**Comment by kbrosnan** [comment]
They want the swipeable UI that switched between Top Sites, Bookmarks and History/Sync that is present in Fennec. 

This was intentionally changed because it was a hard to use and understand part of the interface. Fenix is not going to have a 1:1 feature set of Fennec.

**Comment by Phenix-Feedback** [comment]
Well, let me disagree about that.
The current Fenix needs more "touch" to get the websites I use everyday, or to go to my bookmarks. That feature of Fennec was a quick way to swipe between top site, bookmarks, and history (though I can understand the later disappearing).

I don't see what was hard to use? I'll be more than glad to have you explain it!

**Comment by kbrosnan** [comment]
That sounds like the top sites feature. You can manually add items right now. There are plans to add an auto-populated list in #10342.

**Comment by FenixRevival** [comment]
@data-sync-user Is it open or close...? I don't understand what's going on, and I wish this could stay open. It was closed arbitrary without any talk in the first place.
