### ISSUE TITLE
FNX-4288 ⁃ [Bug] Yellow Bounding box on certain elements

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10448]
## Steps to reproduce
Go to google.com/chrome
Press the "down arrow" floating button
Scroll back up
![Screenshot](https://user-images.githubusercontent.com/33252312/81216693-d8b30c80-8fca-11ea-85d6-190ffc07c37f.png)UNITO-UNDERSCORE!20200507-002129!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!
This does not happen in chrome

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 5/7 #21280606.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

**Comment by kbrosnan** [comment]
The page says to draw an outline.

```
<link id="js-css" rel="stylesheet" href="/chrome/static/css/main.v2.min.css" as="style" nonce="Gn3jAVgYT3BIchNAfyriuw" data-loadcss="true" media="all" onload="null">

a:focus {
  background: #f1f3f4;
  outline: 4px solid rgba(32, 33, 36, 0.06);
}
a:active,
a:focus {
  outline: auto 2px Highlight;
}
```
