### ISSUE TITLE
FNX-4295 ⁃ Unnecessary element in the address bar

### ISSUE THREAD

**Issue by theartifaktorq** [mozilla-mobile/fenix#10457]
**I think that the button on the right side of the address bar with the "+" symbol is completely unnecessary and should be removed as it does exactly the same function as when we click directly on the address bar _LoL_**

![photo](https://user-images.githubusercontent.com/64933235/81237519-7572ab80-8fc5-11ea-87fc-62456dc2e978.jpg)UNITO-UNDERSCORE!2020-05-06!UNITO-UNDERSCORE!18-03-07!

**Comment by yoasif** [comment]
Issue seems similar to https://github.com/mozilla-mobile/fenix/issues/10368

**Comment by cadeyrn** [comment]
There will no longer be a plus icon with the tabs tray.

**Comment by sv-sdeiac** [comment]
Hi, since this button will no longer be displayed, I'll close this ticket. Thanks.
