### ISSUE TITLE
Menu placement should follow toolbar top/bottom preference in Tab tray

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10454]
## Steps to reproduce
1. Enable Tab tray
1. Ensure toolbar customization preference is "bottom"
1. Tap tab switcher button.

### Expected behavior
The kebab menu should be exactly where it was before I tapped the tab switcher button. 

### Actual behavior
The kebab menu is on the top of the screen. Reference browser does this as expected:

![signal-attachment-2020-05-02-133748](https://user-images.githubusercontent.com/152493/80871364-256caf80-8c7a-11ea-918c-418aa1565a1d.png)

### Device information
* Android device: pixel 2
* Fenix version: latest nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-554)

**Comment by cadeyrn** [comment]
Your proposal is inconsistent to other parts of Fenix like history and bookmarks. Please also note that it's *not* the same menu as on the start screen.

**Comment by yoasif** [comment]
@cadeyrn Frankly, I'm a little surprised to see you disagree with this issue, given your comment here: https://github.com/mozilla-mobile/fenix/issues/1048#issuecomment-624864039

In any case, History and Bookmarks don't *have* a single kebab menu with options for the page that users might want to reach one handed -- they have menus for every item that appears in a list, so there is really no way to prioritize one handed use, or to provide a preference of top or bottom, since it is just a list of items in both places, with *multiple* kebab menus.

**Comment by maverick74** [comment]
I must say I love the disposition of items in @yoasif Screenshot of Reference browser.

Itens like Back, Tabs, Private tabs, New tabs and the menu are right where they should be - at hand!

Would be great to have this in Firefox...

**Comment by Poopooracoocoo** [comment]
This is a feature request. They intentionally designed it that way. 

Also see #14403 for the placement of the new tab button when the toolbar is at the top

and why keep it a tray/drawer/sheet? there are back buttons on android. 
an alternative would be to fully expand the tray #14909

**Comment by eliserichards** [comment]
I changed this from a bug to a feature request since this would be introducing new functionality :) Thanks for catching stalebot before this got lost @yoasif!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812930

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
