### ISSUE TITLE
FNX-4291 ⁃ [Bug] Exiting fullscreen video in PWA causes toolbar to appear and content to be clipped

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#10452]
## Steps to reproduce
1. Open a fullscreen video in PWA
1. Put the app in the background

### Expected behavior
1. Toolbar stays hidden

### Actual behavior
1. Toolbar is force expanded and the web content is clipped improperly

![demo of broken 2020-05-06 14](https://user-images.githubusercontent.com/4400286/81230239-f621af80-8fa5-11ea-8366-5e1d875adf0e.gif)UNITO-UNDERSCORE!29!UNITO-UNDERSCORE!03!

Discovered when working on https://github.com/mozilla-mobile/fenix/issues/10433

**Comment by ricvelozo** [comment]
This happens after switching the open apps as well (not need to be in fullscreen video).

**Comment by sblatz** [comment]
@ricvelozo I believe I fixed that bug a week or so ago (when I filed this one). If you use nightly you shouldn't be encountering it anymore 😄

**Comment by kbrosnan** [comment]
This also breaks in the same way if the user hits the back button or the exit fullscreen button.

**Comment by ekager** [comment]
cc @NotWoods do we have to do anything else here or will https://github.com/mozilla-mobile/android-components/pull/7216 fix this without more work in Fenix?

**Comment by NotWoods** [comment]
https://github.com/mozilla-mobile/android-components/pull/7251 will fix this but will require more work in Fenix

**Comment by ekager** [comment]
Ah I see 👌  TY!

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200619 (Build #2171067).
### Device Used
- Huawei MediaPad M3 (Android 7.0)
