### ISSUE TITLE
FNX-4289 ⁃ [Bug] Custom tab toolbar doesn't have correct theme when private tab is on.

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/fenix#10450]
## Steps to reproduce
1. Open Fenix.
1. Go to Settings ~~> Private browsing~~ > Switch open links in a private tab on.
1. Set Fenix as default browser. Open a custom tab.
1. From a custom tab, open the link in Fenix.

### Expected behavior
Custom tab has private browsing theme enabled in the toolbar.

### Actual behavior
Custom tab has non private browsing theme enabled in the toolbar.

### Device information
* Android device: ?
* Fenix version: ?

**Comment by SL-Lee** [comment]
Is this similar to #9037?

**Comment by ekager** [comment]
Closing for #9037
