### ISSUE TITLE
FNX-4296 ⁃ [Bug] Tab is not responding

### ISSUE THREAD

**Issue by mikeGolf08** [mozilla-mobile/fenix#10458]
## Steps to reproduce
1. Add some top sites
1. Delete all browsing data and restart Fenix
1. Click on a top site
1. Click on the tab overview
1. Click on another top site
... Do it fast and with a couple of sites

### Expected behavior
All webpages are loaded or loading when clicking on the tab.

### Actual behavior
Out of 10 tabs 1 is occasionally not responding and clicking the reload button has no effect as well.

### Device information
* Android device: OnePlus 3T OOS 9.0.6 Android 9
* Fenix version: Nightly 200506 06:01 (Build #21270610)
41.0.20200505190119, cb5fb4ca9
GV: 77.0a1-20200504093644
AS: 0.58.2

**Comment by ekager** [comment]
Thanks for the STR! We should definitely look into this

**Comment by LaurentiuApahideanSV** [comment]
I can no longer reproduce the issue on Firefox Preview Nightly 200611 (Build #21630608).
### Device information

- OnePlus 6T (Android 9)
- Huawei MediaPad M3 lite (Android 7.0)
