### ISSUE TITLE
Tab Switcher icon should be present on Tab tray; tapping it should go back to page

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10455]
Clarifying this request:

* Toolbar is still visible when drawer is open so user can quick tap to open/close drawer

### Why/User Benefit/User Problem
As a user who sometimes wants to glance at open pages (but not switch) or change my mind to change to a new tab, I would like to easily go back to where I was by tapping the same button that brought me to the tab tray, like I can in Chrome or Opera. I also don't need to move my finger/hand to a farther area of the screen than I had initially tapped on. 

### What/Requirements
* Tab switcher (box with number of tabs listed inside it) is present in in the tab tray in the same position as in the toolbar. 
* Tapping the tab switcher button in the tab tray takes the user back where they were previously

### Acceptance Criteria (how do I know when I’m done?)
Tab switcher appears on tab tray, tapping it closes the tab tray and takes the user back to the page they were browsing previously.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-556)

**Comment by buttercookie42** [comment]
> Tab switcher (box with number of tabs listed inside it) is present in in the tab tray in the same position as in the toolbar.

That would conflict with the "New tab" button being in the same position as the tab switcher button, which is one Fennec feature I rather like.

**Comment by yoasif** [comment]
> > Tab switcher (box with number of tabs listed inside it) is present in in the tab tray in the same position as in the toolbar.
> 
> That would conflict with the "New tab" button being in the same position as the tab switcher button, which is one Fennec feature I rather like.

Not disagreeing with you, but this only happens if you are using the bottom toolbar - in the top toolbar, the new tab button appears on the opposite side of the screen. 

I think that that https://github.com/mozilla-mobile/fenix/issues/10374 would solve for what you want.

I think the consistency of the toggle is worth doing what I proposed over Fennec's behavior, especially since this is used even in the Android navigation buttons (the "square" button).

**Comment by buttercookie42** [comment]
A contextual menu means hold to long press, then move the finger to the corresponding menu item - the Fennec approach is just two quick taps.

**Comment by yoasif** [comment]
@buttercookie42 Yes, I know that it isn't exactly the same, but given the inconsistency of the current position of the tab switch icon vs. the new tab icon, I think that is a better solution than the one offered in Fennec or here. 

Additionally, the Fennec approach doesn't actually work for me because I actually have a tab bar in Fennec (must be a DPI thing), so I have a new tab icon above my tab switcher icon, and tapping the tab switcher icon actually puts my finger over a tab. Perhaps not things you are experiencing (the top toolbar in Fenix, the tablet UI in Fennec) but they exist. 

Lastly and more disconcertingly, the Fenix approach is far worse even in the optimal case than Fennec due to https://github.com/mozilla-mobile/fenix/issues/10368 - in Fenix, it merely *looks* like you are opening a new tab with the double tap action, but in reality, it is more of a "+..." action, meaning a "new tab if you complete the steps to open a page". 

This takes *way* longer than actually just opening a tab and any time savings you may have achieved over #10374 is gone by the time you end up entering a url or search query vs. simply opening a new tab. 

Of course, you can do #10374 without doing this issue, but I would continue to posit that the issues (double tap not possible with top toolbar) and consistency benefits (toggle in Android navigation, this is used widely in other Android browsers) make this worth it.

Also keep in mind that there is a real benefit to this being a toggle - imagine if doing `alt-tab/command-tab` twice in your OS caused a new application to appear instead of switching back and forth between the applications you were using - not doing this feels like the promotion of a fairly esoteric power user feature over a benefit to general users to have interfaces that are predictable and forgiving. 

"Oh, I tapped this switcher icon and I just want to go back where I was... oh, I can just tap the same icon again to go back."

I think the power user feature is catered to with the long press personally, and it should become pretty natural for those users pretty quickly - I use the long press to copy URLs out of the address bar all the time now, and I miss it when using another browser. 

I would also bet that the long press action is more accessible (and faster) than asking the user to select the tab switcher, wait for the items on tab tray to be enumerated, then performing the new tab action -- the new tab action is built directly into the switcher instead of opening a whole new panel where the new tab icon happens to be in the same place (in the bottom toolbar mode!) as the tab switcher.

**Comment by AmyYLee** [comment]
Assigning to @topotropic
