### ISSUE TITLE
[Bug] Custom tab share icon looks off-scaled (enlarged)

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/fenix#10451]
## Steps to reproduce
1. Set Fenix as default browser. Open a custom tab.
1. From a custom tab, open the link in Fenix.

### Expected behavior
Share icon doesn't look off-scaled compared to the three dot settings menu icon

### Actual behavior
![Screenshot](https://user-images.githubusercontent.com/3597594/81222277-08a1e600-8fb2-11ea-8fea-287cd73793c4.png)UNITO-UNDERSCORE!20200506-155059!

### Device information
* Android device: ?
* Fenix version: ?

**Comment by sv-sdeiac** [comment]
Hi, I can't reproduce your issue using the latest version of Firefox Preview Nightly 5/7 #21280606.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

@psymoon Can you retest using the latest version of Firefox Preview Nightly? Also, do you have more details about your issue so I can reproduce it?

**Comment by jonalmeida** [comment]
It depends on the third party app that opens a custom tab. The app can give us an icon to show in some cases as well, and we should probably scale it down if needed. I don't think this is our own share icon.

**Comment by Tajnymag** [comment]
I can reproduce the same behavior when opening an article in Feedly. Can confirm that other apps behave correctly.

Firefox should still downscale the icon though.

**Comment by mcarare** [comment]
I cannot find a website where I can reproduce this. Can QA please retest this? Thank you!
!

**Comment by sflorean** [comment]
Tested on the latest Nightly and couldn't reproduce the issue following the exact website from the description (link opened from Gmail). Tested with other websites, without any luck. 
@psymoon this is still reproducible for you? If yes, do you have extra steps?

**Comment by Tajnymag** [comment]
Yup, it's still reproducible. For example in Feedly

![Screenshot_20200928-194904.jpg](https://user-images.githubusercontent.com/3985946/94467875-d80e5300-01c3-11eb-9eab-6b2acff2690f.jpg)

**Comment by sflorean** [comment]
@Tajnymag thank you!
STR:
1. Nightly is set as the default browser.
2. Install Feedly from GP
3. Open an article.
4. Open a link from that article in order to open the Nightly custom tab. 

Results: the share icon is enlarged.

**Comment by ekager** [comment]
AC bug is https://github.com/mozilla-mobile/android-components/issues/4457

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/8 with Samsung Galaxy Note 10 (Android 10).
