### ISSUE TITLE
FNX-4308 ⁃ [Bug] New collections not listed when adding multiple ones from tab

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/fenix#10469]
## Steps to reproduce
Access any page: www.google.com
Tap menu -> Save to collection
Add new collection (example: TestCollection)
Tap menu -> Save to collection

### Expected behavior
TestCollection is displayed in the collection list

### Actual behavior
TestCollection is not displayed in the collection list, this will happen also when there are no collections yet, you will be shown the `Name collection` page every time you try to add from the same tab

### Device information
* Android device: Any
* Fenix version: Latest develop

### Engineering note
This happens because only `HomeFragment` subscribes to collections store, so `BrowserFragment` has no idea something changed.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200625-130211-1](https://user-images.githubusercontent.com/51314259/85700049-b002e580-b6e4-11ea-9c89-d5b78a7d3037.gif)
