### ISSUE TITLE
Bookmarks, History, Downloads should be shown in a tabbed/paned page

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10463]
### Why/User Benefit/User Problem
As a user, I would like to easily find relevant related information about historical data I have created (what used to be in my Library (see https://github.com/mozilla-mobile/fenix/issues/10343) in a discoverable way that doesn't feel cumbersome like the Library did. 

### What/Requirements
* Library, History, Downloads should appear as a tabbed page
* The existing menu items take the user to the tabbed page with the selected page opened
* pressing back exists the entire view

### Acceptance Criteria (how do I know when I’m done?)
I can select "History" in my Fenix menu and get to my bookmarks or downloads in one additional tap. 

See also https://github.com/mozilla-mobile/fenix/issues/7913

This exists in Edge:

![signal-attachment-2020-05-07-012014](https://user-images.githubusercontent.com/152493/81257674-e20b9b80-9001-11ea-9972-bb6795a1b1d8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-575)

**Comment by astarq** [comment]
Vivaldi does this slightly better: 
![Screenshot_20200526-150507_Vivaldi Snapshot](https://user-images.githubusercontent.com/63871973/82910354-76628180-9f62-11ea-8a87-0796b04289a4.png)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812714

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
