### ISSUE TITLE
Option to always allow audio and video autoplay

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10464]
### User Story
As a user, I want to be able to allow audio and video autoplay in my browser or for specific sites, so I can customize how I want to consume my selected media.

### Acceptance Criteria
I can choose to allow audio and video autoplay in my browser. 

### Dependencies:
https://bugzilla.mozilla.org/show_bug.cgi?id=1621825
bz-1647779

### Mocks
https://share.goabstract.com/cdba1651-670e-4412-8721-4d70ca025ffd?collectionLayerId=35603d5c-263c-4c70-b3fe-1ae23bd449c8&mode=design

**Comment by liuche** [comment]
I'm going to remove this one for now @vesta0 because we need to get this prioritized by GV team first (and isn't going to be actionable for Release).
