### ISSUE TITLE
FNX-4305 ⁃ [Bug] Blue dot doesn't appear at all

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10467]
## Steps to reproduce
Navigate to a site with a PWA (e,g, Housing.com) or "Open in app" (e.g. instagram) available

### Expected behavior
-See some sort of indication that PWA or Open in App is available. 
-Be able to easily dismiss the indication/notification. 

### Actual behavior
No obvious indication/notification unless browser toolbar menu is opened. 

### Device information
* Android device: Pixel 4
* Fenix version: Build #21270610

**Comment by ekager** [comment]
I think we changed this behavior on purpose in https://github.com/mozilla-mobile/fenix/issues/7408#issuecomment-587551828

We only highlight these items once each until the user either interacts with them or closes the menu while they are displayed highlighted AFAICT, and the bottom menu icon is only highlighted if any items are highlighted.

**Comment by vesta0** [comment]
@ekager I agree that the behaviour should be as outlined her: https://github.com/mozilla-mobile/fenix/issues/7408#issuecomment-587551828 

However I took this part: 

> The blue dot appears next to the 3-dot icon the first time the user visits a site that supports reader view, open in app, or PWA. This could happen all at once on one page, or over time across multiple supported pages.

to mean that the blue dot will continue to appear the first user visits a NEW site that supports reader view, open in app, PWA.  @apbitner let us know which interpretation is correct. 

The current behaviour in Fenix is as follows: Upon a fresh install Blue dot only appears once per category and never again. So it appears the first time user visits a PWA site, the first time user visits a site that offers "Open in app" and the first time user visits a site that supports reader mode, and never again. This is not ideal user experience.

**Comment by ekager** [comment]
I think eng interpreted "This could happen all at once on one page, or over time across multiple supported pages" to mean if one page has every category - readermode, PWA, open in app etc, that would knock them all out at once. 

Maintaining a list of every new site a user has visited in these categories and then querying that list every time the site changes to decide if we should highlight the menu is going to be an problem eng implementation wise. 

Wondering if we can just revert those changes and always show the highlight if one of these actions is available if we think it's important that users know when actions are available in the menu.

**Comment by vesta0** [comment]
Hey @ekager you are so right, querying a list of sites is just not feasible. 

I like your suggestion of always showing the highlight if one of these actions is available BUT having the notification go away as soon as user interacts with the menu (which wasn't the case during the very first iteration of this). Let's go ahead with that if it make sense.

**Comment by apbitner** [comment]
That sounds good to me. We're exploring replacing the blue dot notification so I'd hate for us to put too much eng effort into this.

**Comment by AaronMT** [comment]
Noticed this issue when attempting to re-enable readability Reader Mode UI tests.

Fresh clean install -> launch browser -> visit a reader capable local asset page -> expected a dot (no dot).

This used to work fine, is Readability not working on local pages?

**Comment by AaronMT** [comment]
Here's a test page:

Load this in a fresh profile in Fenix. First launch, visit:

```HTML
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta charset="utf-8" />
    <title>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt
    </title>
</head>
<body>
<p id="testContent">Page content: lorem ipsum</p>
<h1>
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt
</h1>
<p>
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
</p>
<h2>
    Secondary header
</h2>
<p style="display: none;">
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
</p>
<h2>
    Third header
</h2>
<p hidden="hidden">
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
</p>
</body>
</html>
```

No blue notification dot.

I assume this should work. Test page grabbed from https://github.com/mozilla/readability/tree/master/test/test-pages/missing-paragraphs where the metadata shows it as `readerable = true`

**Comment by ekager** [comment]
Hey @BranescuMihai are you still working on this?

**Comment by AaronMT** [comment]
My issue is that readability is not working at all on first visit https://github.com/mozilla-mobile/fenix/issues/11191

**Comment by apbitner** [comment]
@vesta0 now that reader mode is moving to the address bar, that leaves us with Open in App and Install PWA in the toolbar menu. With Open in App, we are revisiting the overall flow which I believe Michelle has mentioned to you. With PWA's, our latest round of research around social containers indicates there's still a large user education challenge re: PWA's.

I have not seen telemetry for either of these two features but can only presume it's pretty low based on the use case of Open in App, the relatively small % of PWA sites, and the lack of user awareness. Based on this, I suggest we remove the blue dot notification completely for these two remaining features in the toolbar menu, and only let it remain in use for What's New.

**Comment by vesta0** [comment]
@apbitner thanks for the update. I am ok with your recommendation on PWA for now but I'd like to revisit this once we have a better understanding of how often our users look to install a PWA site.

**Comment by BranescuMihai** [comment]
@vesta0 so just to make sure, the actionable part of the task is now: remove the blue dot notification for PWA and Open in App?

**Comment by vesta0** [comment]
Adding the label `waiting` until I re-confirm a couple of things.

**Comment by vesta0** [comment]
Now that #9506 won't be done before code freeze, we should make sure the blue dot DOES appear when it needs to. 

Let's go with the following variation of the behaviour we agreed upon previously:

Show the blue dot only the first time either Open in App or PWA is available on a site AND have the notification go away once the user interacts with it. The bottom menu icon should only be highlighted if any menu items are highlighted.

**Comment by apbitner** [comment]
@vesta0 when you say "user interacts with it" do you mean the only way to get the blue dot to go away for Open in App or PWA is to tap on one of those menu items? We know the majority of our users are not going to install a PWA so I don't think we should force them to just to make the blue dot go away. I think the blue dot should go away after the user has opened the menu instead of forcing them to perform one of those actions.

**Comment by BranescuMihai** [comment]
@vesta0 I also have the same question, I'm not sure what 'interacts' mean. If it means just to see it, then it's the current behaviour. So I'm assuming it means click?

**Comment by vesta0** [comment]
@BranescuMihai thanks for asking for clarification. And I also agree with @apbitner 's recommendation. I will clarify below:

Show the blue dot only the FIRST time either Open in App or PWA is available on a site AND have the notification go away once the user has tapped to open the MENU (not the individual actions)

The bottom menu icon should be highlighted if any menu items are highlighted.

**Comment by liuche** [comment]
Cool, we still want this for release/code freeze on Friday.

**Comment by BranescuMihai** [comment]
@vesta0 here's the [video with the fix](https://drive.google.com/file/d/1V1Nc6NoEJBwporn_6k8aHE-veo66T6Zy/view?usp=sharing). 
We're now always showing the highlight if one of these actions is available, and the notification goes away as soon as user dismisses the menu

**Comment by BranescuMihai** [comment]
@vesta0 as discussed, the behaviour is as follows: Show the dot when a user sees either `Open in App` or `Install`. When the user clicks one of those items, the blue dot notification for that item disappears forever. Menu dismissal doesn't have any effect on the dot anymore

**Comment by vesta0** [comment]
Sounds good, thank you @BranescuMihai

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200625-135950](https://user-images.githubusercontent.com/51314259/85709117-9914c100-b6ed-11ea-9fb5-756cc27d6b35.gif)
