### ISSUE TITLE
FNX-4303 ⁃ [Telemetry] Voice Search

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10465]
**FYI I don't believe we need a DS JIRA request for this one since it's a pretty straightforward event ping.**

### Description & Product Manager / Data Scientist User Story
As a Product Manager, I want to know how often our users choose to use voice search, so I can determine the importance of this use case in addressing a user need, and prioritize future voice features accordingly. 

### What questions will you answer with this data?
How often users use voice search by interacting with the new nav bar mic?
Do users choose to turn this feature off in settings?

### Acceptance Criteria
Event pings can be queried via re:dash
Event pings can be queried via amplitude
We are sending telemetry events for the actions listed in the requirements
We have documented the telemetry
We have asked a data steward to review the telemetry

**Comment by vesta0** [comment]
This is waiting on the feature to be developed first #1216

**Comment by AndiAJ** [comment]
Hi,  **verified as fixed** on the latest **`Nightly Build 200522 from 5/22`** using a Google Pixel 3a (Android 10)
✔️ Toggle state - Ping **c667228c-7255-4ed0-a6ce-90fcefabca87**
✔️ Disable - Ping **fcd61e0f-5095-40c0-b201-38ef6ef75298**
✔️ Enable - Ping **11a94282-3236-4b94-a90f-f8e9314c6c5e** 
✔️ Tap the Voice Search icon from the search fragment - Ping **bb7d8d3d-d4c9-4527-9d7d-c0e5d2567226**
✔️ Tap the Voice Search from the widget - Ping **712b97fd-d9ae-4776-9075-0bc7534e219f**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4667604/searchicon.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2205000)
