### ISSUE TITLE
[Bug] Sharing a tab to a clean profile Fenix build, doesn't display the tab after tapping the tab counter

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#10470]
## Prerequisites
Have Beta 76.0.0-beta.1 installed, and with a clean profile.

## Steps to reproduce
1. On Nightly, have multiple tabs opened (or have an opened collection).
1. Share one tab or multiple tabs to Fenix Beta 76.0.0-beta.1. The user is redirected to Beta.
1. In Beta, tap on the tabs counter.

### Expected behavior
The user is redirected to Beta's homescreen displaying the shared tab as an opened tab.

### Actual behavior
The user is redirected to Beta's onboarding tour. No open tabs are displayed.
Tapping on "Start browsing" or on nav bar, then back, the homescreen is displayed with the shared tab.

### Device information
* Android device: HTC 10 (Android 8), Google Pixel 3 (Android 10), Motorola Moto G6 (Android 8)
* Fenix version: Beta 76.0.0-beta.1, and RC 4.3.0 (#21082025), 5/6 Nightly
* Reproducible using any of the Fenix builds.
* Please see the attached logcat, and GIF, for more details.

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4591256/logcat.txt)

![](https://user-images.githubusercontent.com/40694158/81264399-00958500-904a-11ea-8590-c54b89dd3370.gif)

**Comment by skierpage** [comment]
I just discovered Share > Send to Device > Firefox _(elsewhere)_ . It works great from Firefox on Android to Firefox Nightly on Linux, but it doesn't seem to work at all between my phone and tablet with Firefox for Android. A "Tab sent!" purple bar briefly appears, but the sent tab doesn't appear on the other device when I tap the tab counter or when I view the "home screen". It sounds like this bug but possibly worse.

Firefox Daylight 84.1.2, builds #2015783151 and #2015783147.

**Comment by lobontiumira** [comment]
This issue no longer reproduces on 6/29 Nightly, beta 90.0.0-beta.6 with Google Pixel (Android 10).
