### ISSUE TITLE
[Bug] Can't scroll when the page is taking almost the entire screen

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#10477]
## Steps to reproduce
1. Find a website where the page takes almost the entire screen. For my device, it's https://nitter.net/settings
    1. Expected behavior
You can scroll, because the page doesn't take the entire page
    1. Actual behavior
You are not able to scroll, therefore it's hard to hit the bottom of the page, in this case the "save preferences" button.
    1. Device information

* Android device: Pocophone F1 Android 9
* Fenix version: first time i've noticed Firefox preview nightly: 200424 06:01.21150608, it's still there with latest version (200507 06 01.21280606). Important to note: It doesn't happen with stable version (currently 4.3.0.21082025 on my device).

### Additional information
Here is a GIF showing the difference between regular Firefox version and Firefox Preview Nightly:
https://bug1632998.bmoattachments.org/attachment.cgi?id=9143230
It happens only when the toolbar is set to bottom.

**Comment by Diana-Rus** [comment]
Hi, i also reproduce this issue with Google Pixel 3 XL (Android 9) on Nightly 200507 5/7.
Note:
- I did not reproduced the issue with Beta 76.0.0-beta.1 5/1
- As a temporary solution you can zoom a bit in the page and scroll the page, so that it goes all the way to the bottom.

**Comment by ekager** [comment]
cc @sblatz maybe a recent toolbar behavior regression?

**Comment by B0pol** [comment]
It must be a recent change indeed, because it doesn't happen in version 5.0.
Some browser pages are being affected, see this screenshot:
<img src="https://user-images.githubusercontent.com/58657617/82138378-4a3b5800-9820-11ea-8abc-a114b7596606.png" width="200">

Here, I have the behaviour I previously described: I can't scroll down, buttons at the bottom of the page are hard to click on.

@Diana-Rus said:
> As a temporary solution you can zoom a bit in the page and scroll the page, so that it goes all the way to the bottom.

But you can't zoom on every page, and the page shown on the screenshot above is one of them.

**Comment by liuche** [comment]
This is a problem in Reference Browser too, but has been there for months - I ran into it while playing Monster Dating and could not text any Monsters, it was not a fun game.

**Comment by liuche** [comment]
@sblatz what are things you're thinking of trying for this and #10073? Any things that I should check in with other teams about?

**Comment by sblatz** [comment]
I've left a more up to date comment in that other ticket. Basically I think we need a GV fix, but waiting to hear back. For more info: https://github.com/mozilla-mobile/fenix/issues/10073#issuecomment-639003404

**Comment by sblatz** [comment]
This is waiting on: GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1633322

**Comment by liuche** [comment]
We'd like to get this in before code freeze if possible, but @vesta0 will see how this compares to other things.

**Comment by sblatz** [comment]
I think we will get this "for free" once we get a GV update. So that means on the Fenix side I don't think we have to worry about code freeze deadline!

**Comment by B0pol** [comment]
@sblatz the GV bug has been closed as "RESOLVED FIXED" 8 days ago, bug it's still not fixed in nightly. Isn't gecko view updated every night? Otherwise when will be the next GV update?

**Comment by B0pol** [comment]
Still an issue with bottom nav bar and scroll to hide toolbar. Otherwise it's not reproducible

**Comment by B0pol** [comment]
I can't reproduce too
