### ISSUE TITLE
"Last updated" date in addon details view is not the date of the last update

### ISSUE THREAD

**Issue by Rob--W** [mozilla-mobile/fenix#10489]
## Steps to reproduce
1. Install an older version of uBlock Origin. For example by installing a Fennec-based version of Firefox Beta to install uBlock Origin 1.18.6 and then upgrading to the Fenix-based version of Firefox Beta.
1. Visit Addons > uBlock Origin > Details
1. Look at the "Last updated" date.

### Expected behavior
The shown date should match the last updated date of the version that I had installed, e.g. Mar 13, 2019 for version 1.18.6. This date should be provided by GeckoView (which should take the date from from the `updateDate` field of addon objects from the AddonManager internals).

If the user had not installed any version, showing the date of the most recent update should be fine.

Note: from the details view it was not obvious that an update of a newer version was available. To address that, consider adding two extra rows, "Latest version" + "Latest update at", after "Version"  /"Last updated".

### Actual behavior
It shows "May 7, 2020". This is not what I expected, and not even the date of the most recent version (1.26.2 = Apr 16, 2020). This date seems to directly be derived from the response from AMO (and I filed a bug report for the incorrect `last_updated` date at https://github.com/mozilla/addons-server/issues/14209).

### Device information
* Android device: ?
* Fenix version: Firefox Beta 75-0-0-beta.6 (Build #2015735819), [AC 37.0.5, e5f14c288](https://github.com/mozilla-mobile/android-components/commits/e5f14c288), GV 75.0-20200403064004

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-614)

**Comment by Rob--W** [comment]
This issue is still relevant, and already tracked by https://github.com/mozilla-mobile/android-components/issues/6935

**Comment by Rob--W** [comment]
Still relevant.

**Comment by Rob--W** [comment]
Still relevant.

**Comment by Rob--W** [comment]
Still relevant.

**Comment by csadilek** [comment]
We're unifying and moving all Github issues to Mozilla, and since we already have this under Fenix/WebExtensions I will dupe it to https://bugzilla.mozilla.org/show_bug.cgi?id=1796311 (from https://github.com/mozilla-mobile/android-components/issues/6935), and a link there.
