### ISSUE TITLE
FNX-4320 ⁃ [Bug] Checked radio button "Block audio and video on cellular data only" is unchecked after exiting the menu

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10485]
## Steps to reproduce
1. Go to Settings - Site permissions - Autoplay and select the first radio button "Block audio and video on cellular data only".
1. Exit the Autoplay page, then return to it.

### Expected behavior
The same radio button is selected/checked.

### Actual behavior
None of the options is selected/checked.

### Device information
* Android device: HTC 10 (Android 8), OnePlus 5T (Android 9)
* Fenix version: 5/7 Nightly build

![](https://user-images.githubusercontent.com/40694158/81301712-12931a00-9082-11ea-9f11-6138c9ff0e03.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200511 from 5/11`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200511-095925](https://user-images.githubusercontent.com/51314259/81533234-811bf480-936e-11ea-9912-de1c7f16a3ba.gif)
