### ISSUE TITLE
[Bug] Some websites don't display a name if you add them as a Top Site

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#10484]
## Steps to reproduce
1. Go to: twitch.tv;
1. Open the 3 dot menu;
1. Tap on the "Add to top sites" button;
1. Open the Homescreen page of the app.

### Expected behavior
Twitch icon and name are displayed on the Top Sites list.

### Actual behavior
The name of the site is not displayed for the Twitch home page.

### Device information
Android device: 

* Google Pixel 3 (Android 10);
* Samsung Galaxy Note 8 (Android 9);
* LG G7 fit (Android 8.1);
* Motorola Moto G6 (Android 8).

Fenix version:

* Firefox Preview Nightly 5/7 #21280606.

### Notes
* If you open a specific stream, the name of the stream is displayed on the "Top sites" list.

![Screenshot](https://user-images.githubusercontent.com/40264165/81300213-09a14900-9080-11ea-950f-0eaf6e75732b.png)UNITO-UNDERSCORE!20200507-162851!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-607)

**Comment by ekager** [comment]
Hm can't seem to get this to reproduce on master. Are you still seeing this? Does the title of the page appear in the tab list?

**Comment by sv-ohorvath** [comment]
Still reproducing on Nightly 9/1 and not only with twitch.tv, with many other websites: amazon, pinterest, reddit, time.com, telegraph.co.uk
![Screenshot_20200901-121533](https://user-images.githubusercontent.com/4037709/91833899-faa65e00-ec4f-11ea-8eda-302af6b9418f.png)

**Comment by sv-ohorvath** [comment]
Also related: https://github.com/mozilla-mobile/fenix/issues/14432
When a website's title is not shown in the tabs tray, it won't show in the top sites either.

**Comment by sv-ohorvath** [comment]
> Still reproducing on Nightly 9/1 and not only with twitch.tv, with many other websites: amazon, pinterest, reddit, time.com, telegraph.co.uk

Can't reproduce with these websites anymore, but still reproducible with twitch.tv. The website doesn't show a title in tabs tray either. Weird that the title appears if the top site is shown from history, not pinned.
Workaround: refresh the page, then the title is displayed in the tabs tray & re-add the top site.

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 SM-A530F Android 9 Nightly 93.0a1 2021-08-30 just for the Twitch website
![Screenshot_20210830-141846_Firefox Nightly](https://user-images.githubusercontent.com/89511597/131331778-82780d7e-0019-4945-befe-1d4f41a9c744.jpg)

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 SM-A530F Android 9 Nightly 93.0a1 2021-08-30 albeit that there is a pin icon at least

**Comment by SoftVision-LorandJanos** [comment]
This issue is reproducible with the latest Nightly 99.0a1 (2022-02-28).
Device used: Oppo Reno 6 (Android 11).
