### ISSUE TITLE
FNX-4322 ⁃ [Bug] Sometimes the menu cannot disappear and other operations cannot be performed

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#10488]
## Steps to reproduce
open firefox
(I think it is in the case of logging in the synchronization account, and was in the process of synchronization)

click 3 dot
click bookmark or history

### Expected behavior
The menu disappears and other operations can be performed

### Actual behavior
The menu is always displayed and no other operations can be performed
It cannot be reproduced 100%, but I have encountered many times

https://imgur.com/NBRt1gy.mp4

### Device information
* Android device: ?
* Fenix version: ?
null (Build #2015738867)
41.0.20200506130132, 7d5b3a98a
GV: 77.0-20200504222419
AS: 0.58.2
Thursday 5/7 @ 6:06 AM

**Comment by Diana-Rus** [comment]
Issue related to #10494, the only difference is that in this one is not specified after the amount of time the menu was not accessed.

**Comment by ekager** [comment]
Closing for #10494
