### ISSUE TITLE
[Bug] Fenix app is terminated after zooming in the page a few times

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#10492]
## Steps to reproduce
1. Navigate to https://datastudio.google.com/u/0/reporting/1VgIKMvPGEJ6IW9TF9g4ZB-j-ZyZWyB-r/page/nGDIB?s=rnxK_bdo2z8
1. Zoom in the page a few times and swipe/scroll it.
1. Observe behavior after a few seconds.

### Expected behavior
Page is zoomed in and responsive.

### Actual behavior
Page is zoomed in, but becomes unresponsive and eventually app is terminated.

### Device information
* Android device: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density), Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density)
* Fenix version: Firefox Preview Nightly 200506 (:lizard: 77.0a1-20200504093644)

### Notes:
1. The issue is not reproducible on Chrome and Firefox Release.
1. Attached gif and log.

[FenixTerminated.txt](https://github.com/mozilla-mobile/fenix/files/4593497/FenixTerminated.txt)
![AppTerminated](https://user-images.githubusercontent.com/12184325/81306037-b0d5ae80-9087-11ea-9fbe-a94e7ff2582c.gif)

**Comment by ekager** [comment]
@softvision-oana-arbuzov are you still seeing this in latest Nightly? We updated GV versions and this may have helped. I can't reproduce with master on my Pixel 3. If you can still reproduce, I will file on Bugzilla

**Comment by softvision-oana-arbuzov** [comment]
@ekager I can still reproduce the issue.

**Tested with:**
Browser / Version: Firefox Preview Nightly 200511 (🦎 77.0a1-20200509091423)
Operating System: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density), Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density)
