### ISSUE TITLE
Mitigate annoying sites that stop you from going back

### ISSUE THREAD

**Issue by minutesinch** [mozilla-mobile/fenix#10490]
### Why/User Benefit/User Problem
one of the most annoying things on the internet is websites that hijack your browser. Unfortunately, this isn’t something exclusive to shady websites. You’ve probably run across a  legitimate website that doesn’t let you go to the previous page when you click the Back button. 

You search for something on Google, bing, etc and select a result, but you realize it’s not what you were looking for. When you click the Back button to leave the website it simply refreshes the page or refuses to go back. The only way to leave the page is to mash the Back button repeatedly or open your History and select the previous page.

### What/Requirements
please combating these “history manipulation” tactics. That’s how these websites prevent you from leaving with the Back button. They manipulate your browsing history so going “Back” doesn’t go where you expect.

Mark entries to be skipped on back for history manipulation intervention.

Entries that are added to the back/forward list without the user's intention
are marked to be skipped on subsequent back button invocations.
This CL only adds the bit and subsequent CLs will add metrics and the intervention
logic based on this bit.

### Acceptance Criteria (how do I know when I’m done?)
some ad sites do this, i have forgot they name but you can test it by your own.
if some one know some sites please add comment for this issue.

**Comment by liuche** [comment]
Relevant: #1048 and #10264

**Comment by yoasif** [comment]
Samsung Internet says that they have a mitigation for this, FYI:

https://www.xda-developers.com/samsung-internet-11213-adds-option-prevent-sites-stop-going-back/

https://medium.com/samsung-internet-dev/new-features-in-samsung-internet-beta-7c1485be55bb

**Comment by minutesinch** [comment]
> Samsung Internet says that they have a mitigation for this, FYI:
> 
>     * https://www.xda-developers.com/samsung-internet-11213-adds-option-prevent-sites-stop-going-back/
> 
>     * https://medium.com/samsung-internet-dev/new-features-in-samsung-internet-beta-7c1485be55bb

yes bro they have mitigation even google chrome and chromium have this mitigation.

**Comment by minutesinch** [comment]
i found a site do this annoy.
first go to https://www.shahvani.com then click a random link the site have, you can see the one windows open, and the new page that you clicked  open in new window but the original page you are on open other site named stack patch(xapi.juicyads.com) that manipulate window and dont let you back if your try back button.
please make sure your explore the https://www.shahvani.com to see stack patch(xapi.juicyads.com) and fix the manipulation, also this is not first site do this who know in wild world how much web site do this manipulation?

**Comment by ekager** [comment]
See GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1643554

**Comment by minutesinch** [comment]
> See GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1643554

See GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1636139

**Comment by minutesinch** [comment]
is there any workaround or eta?

**Comment by liuche** [comment]
You should be able to hold the back button to jump back in history, #10264 is in 80.

**Comment by minutesinch** [comment]
its not fixed, in first place problem still exist.

**Comment by minutesinch** [comment]
open the issue
