### ISSUE TITLE
FNX-4756 ⁃ [Meta] Integrate Glean SDK (Core Ping)

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#105]
This Epic is about the basic implementation of the Glean SDK (core pings) only.

Collect information about user and their app usage

See more here: https://docs.google.com/spreadsheets/d/1P2_aGEE9OtjM3x71d0GBhnHDhzxEL02xEHuKn1no23E/edit?ouid=106538102250373429617&usp=sheets_home&ths=true

AC: 

* Core ping per release channel
* Available in Amplitude once probe is created (Frank's team)

**Comment by bbinto** [comment]
Data team will have instrumentation and dash-boarding ready by March 31 (Client API). Barbara to talk to Georg - Mid March 15

**Comment by vesta0** [comment]
All issues listed under this meta have been implemented.
