### ISSUE TITLE
FNX-4333 ⁃ Tab Tray: Save a collection flow

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10503]
## User Story
As a user, I can selects tabs to create a new collection, so I can be more organized and productive.

### Acceptance Criteria
* I can save a collection of select tabs

**Comment by yoasif** [comment]
Seems like a variation of https://github.com/mozilla-mobile/fenix/issues/10371 unless this is not about the old tab selection behavior on home and something different.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200518 from 5/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

❗ The long tap tab feature will be tracked separately in #10371 

► Video
![20200518_150928](https://user-images.githubusercontent.com/51314259/82213399-bc916280-991c-11ea-8e62-c27e2a5a72b9.gif)

► Video
![20200518_151126](https://user-images.githubusercontent.com/51314259/82213876-8a343500-991d-11ea-94ba-c2237403c3c8.gif)
