### ISSUE TITLE
FNX-4453 ⁃ [TabTray] Provide snackbar to go home when tabs added to collection

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#10502]
With moving tabs to a "tab tray" we'll need to tie up these loose ends

WIP

* [ ] When saving a tab(s) to a collection using the new tab tray there is no feedback
  * The old implementation would scroll to the

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly Build 20610 from 6/10`** & **`Beta 5.2.0-beta.1 from 6/10`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200610-123009](https://user-images.githubusercontent.com/51314259/84253958-392cf080-ab19-11ea-9209-e7d6553c70dd.gif)
