### ISSUE TITLE
FNX-4334 ⁃ Homescreen polish

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10505]
## User Story
* As a Fenix user, I want the homescreen to look visually polished, so I know that this is a finished feature and feel encouraged to explore its value. 

### Acceptance Criteria
* Homescreen UI looks intentionally minimalistic. The extra space doesn't give the impression that something is missing.
* The value of homescreen features are clear to me. 

![home](https://user-images.githubusercontent.com/353960/83300425-3caaa880-a1f8-11ea-8af4-a8df5bdc4e58.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 200602 from 6/2`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200602_180137_orgmozillafenixnightly](https://user-images.githubusercontent.com/51314259/83537515-505a5580-a4fd-11ea-81c3-6191f640bbd6.jpg)


![rsz_screenshot_20200602_181128_orgmozillafenixnightly](https://user-images.githubusercontent.com/51314259/83537431-36b90e00-a4fd-11ea-90c5-b4e61fc35356.jpg)
