### ISSUE TITLE
FNX-4330 ⁃ [Bug] Onboarding radio buttons on API < 22 are red

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/fenix#10501]
## Steps to reproduce
Fresh install of the app on old devices API < 22

### Expected behavior
The radio button colors are the regular onboarding ones

### Actual behavior
The radio button is only red

### Device information
* Android device: <22
* Fenix version: Latest Nightly

![](https://user-images.githubusercontent.com/1709373/81323172-a1616000-909d-11ea-9e3b-267feb2ca4f6.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 5/18 Nightly build with Samsung Galaxy Tab A6 (Android 5.1.1).
