### ISSUE TITLE
[UX] Manually create a new login

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#10508]
### Why/User Benefit/User Problem
As a user, I am able to navigate to my saved logins and manually create a new entry.

### Acceptance Criteria (how do I know when I’m done?)
* I can create a new login entry manually

### UX designs
_tbd..._

**Comment by brampitoyo** [comment]
Assigning this issue to @AmyYLee

**Comment by AmyYLee** [comment]
Work is paused until we hear from UR.
