### ISSUE TITLE
FNX-4757 ⁃ Fenix sessions save and close upon opening

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1050]
## Steps to reproduce
1. From the home screen, select a past browsing session.

### Expected behavior
The past browsing session becomes the current session.

### Actual behavior
The past browsing session becomes the current session and then immediately gets closed and saved again.

### Device information
* Android device: Pixel 3 XL
* Fenix version: Build #10760204

**Comment by colintheshots** [comment]
This seems to be a race condition. The old code was blocking on the main thread, so we need to bundle the asynchronous operations to happen in a sequence correctly.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Pixel (Android 9) & HTC Desire 820 (Android 6.0.1). Master build 3/21
