### ISSUE TITLE
Show Fenix pushlog in Google Play "What's New" in Google Play updates

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10512]
As seen on: https://www.reddit.com/r/firefox/comments/gfjb9w/alright_lets_go_to_the_same_old_question_when/

### Why/User Benefit/User Problem
As a user of nightly Fenix builds, I'd like to have an idea of what has changed since the last build so I can test the changes. 

### What/Requirements
* push log should be displayed on Google Play update listing in "What's New"
* each commit should be listed, with the titles of each item shown in full 
* the full list should be linked to on GitHub showing the changelog (especially if there are limits to the text so the requirement above can't be done)

### Acceptance Criteria (how do I know when I’m done?)
User no longer sees "Information not provided by developer" and instead has a description of changes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-637)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813612

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
