### ISSUE TITLE
Cannot search for phrases containing dots or colon, got Address Not Found instead

### ISSUE THREAD

**Issue by Rob--W** [mozilla-mobile/fenix#10516]
## Steps to reproduce
Type "test.whatever" in the location bar and press Enter.

I also tried to explicitly tap on a specific search engine after entering a query.

### Expected behavior
Search result page for "test.whatever" should open.

Or I should at least have been offered a way to specify whether I want to browse or search for the input. Maybe as part of #5403

### Actual behavior
Browser navigates to `http://test.whatever/`, resulting in "Address Not Found".

This is the opposite problem of #4588.

### Device information
* Android device: ?
* Fenix version: Nightly 200508 06:00 (Build #21290607)
41.0.20200507130125, b1f8371fc
GV: 78.0a1-20200505094621
AS: 0.58.2
Also reproducible on Firefox Beta.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-642)

**Comment by ekager** [comment]
Isn't this the same behavior that desktop has?

**Comment by cadeyrn** [comment]
@ekager

> Isn't this the same behavior that desktop has?

Yes - until Firefox 76. But starting with Firefox 76 it's no longer the same behaviour:
https://bugzilla.mozilla.org/show_bug.cgi?id=1080682

**Comment by Rob--W** [comment]
This is not the same as desktop. On desktop I can use my mouse or arrow keys+Enter to open the search result page for a (specific) search engine.

The UX of search from Fenix is worse than desktop and Fennec. Besides this bug and - the linked bugs: if I want to run a search, I have to hit the Enter button. That tiny button is positioned in one of the worst places on the keyboard for single-hand usage.

My bug and the UX issue would be resolved if the search icons/buttons are used to run a search query instead of switching a search engine.

**Comment by kbrosnan** [comment]
To match desktop behavior it should search for things like `site:mozilla.org download`

**Comment by VulumeCode** [comment]
Searches with a colon do not result in in error page, in stead nothing happens. The search bar is closed and your query is forgotten.

I have Scryfall as a search engine, most queries there have a colon in it (eg https://scryfall.com/search?q=type%3Afox). This works fine with "Search Shortcuts" in Firefox desktop.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807735

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
