### ISSUE TITLE
FNX-4356 ⁃ [Bug] Undefined Crash on Android 7 (Nvidia Shield Tablet) when opening / browsing some websites

### ISSUE THREAD

**Issue by Noneatme** [mozilla-mobile/fenix#10528]
## Steps to reproduce
* Open Firefox
* Open example page, for instance: https://eu.onkyo.com/

### Expected behavior
* The tab loads, the site loads and you can browse the webpage

### Actual behavior
* The webpage loads
* While loading / rendering the webpage, Firefox crashes and Android returns to the home screen

### Device information
* Android device: NVIDIA SHIELD Tablet K1 (Android 7)
Kernel Version 3.10.96+
Shield Tablet Software 5.4 (24.29.404.195)
* Fenix version: 4.3.0

These crashes also occur on websites that loads data on the fly via AJAX, for example sites such as DeviantArt after a while. 
Sometimes just the tab crashes, firefox displays a white screen and reloads the tab. But at some cases, even firefox itself crashes. 

It happens on all firefox versions I've tested it so far. Firefox Beta, Nightly and the stable version from the Play Store.

Attached logcat logfile when the crash occurs:

https://gist.github.com/Noneatme/ac75e0875719deaf3a00b2add8ec4e44
https://gist.github.com/Noneatme/dd95934e8c1bb91eb927d2629907347e
https://gist.github.com/Noneatme/759ef6c35a1da7cc0f4fa35c21f5f923

![firefox](https://user-images.githubusercontent.com/6305695/81438105-7f82de80-916c-11ea-9195-7d91b30e7d6f.gif)UNITO-UNDERSCORE!bug!

**Comment by liuche** [comment]
Based on the logs, looks like this is https://bugzilla.mozilla.org/show_bug.cgi?id=1630229

Since I'm tracking this issue in #10517 I'm going to dupe this.

Thank you for filing! Please follow along in the other bug - but the stack traces do indicate this is the right bug.
