### ISSUE TITLE
[Bug] Confusing behavior in site permissions exceptions

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10521]
## Steps to reproduce
Create a site permission exception eg: allow webcamtests.com to use camera
Goto site permissions-> exceptions-> webcamtests->camera
Try to clear the permission
This happens:
![GifMaker](https://user-images.githubusercontent.com/33252312/81419671-27cd7e80-913e-11ea-8a7d-0d42ac46b946.gif)UNITO-UNDERSCORE!lowquality!

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 5/11 #21320625.

It seems that clearing the permission has a weird UI action if any of the options are selected.

Devices:
- Google Pixel 3 (Android 10);
- LG G7 fit (Android 8.1).

**Comment by Diana-Rus** [comment]
Hi, issue is reproducible on Fenix Beta 5.1.0-beta.1 with Sony Xperia Z5 (Android 7).

**Comment by Diana-Rus** [comment]
Reproducible on Firefox Preview Beta 5.2.0-beta.1 with Samsung Galaxy S9 (Android 8).

**Comment by hakkikaancaliskan** [comment]
@ekager should we need to deselect all instead of selecting "blocked" or how it should be?

//This is where this stuff happens.
https://github.com/mozilla-mobile/fenix/blob/704fc6f9833ab41790f3f83a76e6b53dfb333fbc/app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsManageExceptionsPhoneFeatureFragment.kt#L117

**Comment by softvision-miralobontiu** [comment]
This issue is still reproducible on Beta 81.1.0-beta.2 on Samsung Galaxy Tab S6 (Android 9).

**Comment by Diana-Rus** [comment]
Issue reproducible on Firefox Beta 81.1.0-beta.3 with Sony Xperia Z5 (Android 7).

**Comment by abodea** [comment]
Still reproducible on Beta 82.0.0-beta1 with Google Pixel 4 XL (Android 11).
