### ISSUE TITLE
FNX-4350 ⁃ [Bug] Links to Website for both Preview and Preview Nightly are wrong, in Google Play Store

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10522]
## Steps to reproduce
Go to play store, and search for fenix or fenix nightly go down to visit website section
For nightly it links to https://support.mozilla.org/en-US/products/mobile 
For Preview it links to http://www.mozilla.org/ 
It should actually link to https://support.mozilla.org/en-US/products/firefox-preview I think

**Comment by liuche** [comment]
@lwa-moz can you update these links to point to the preview links?

**Comment by lwa-moz** [comment]
Support link for both has been updated to https://support.mozilla.org/products/firefox-preview
