### ISSUE TITLE
[Feature request] Stop GIFs from automatically playing to save mobile internet data

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10535]
### Why/User Benefit/User Problem
As I have seen most of the time GIFs are very large files and they start to load automatically thus they consume a lot of Mobile internet data whether the user wants to play them or not, just today I lost about 250 MB of data in just a few seconds as I didn't know the page contained such large amounts of GIF files. I think there should be a switch or a default behaviour to turn off the autoplay of GIF files as the mobile internet is expensive most of the time. In a sense they are just like the auto-playing videos for me. 

You could provide a play button for playing GIF files individually instead of playing them automatically.

Please consider this feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-666)

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by jonalmeida** [comment]
GIFS are not streamed files like webm or mp44. It's not very clear how useful this feature is along with the technical hurdles of re-requesting the same resource again. We wouldn't be able to know what is considered the "first frame" to display.

Closing as won't fix.
