### ISSUE TITLE
[Bug] Videos crash after the first loop

### ISSUE THREAD

**Issue by vnprak** [mozilla-mobile/fenix#10539]
As this [reddit thread outlines](https://www.reddit.com/r/firefox/comments/eh4fgl/video_related_errors_in_firefox_for_android_no/), after a video loops over once, the HTML5 player then throws either of 3 errors: "no video with supported format and MIME type found", "video can't be played because file is corrupt", or "media could not be played". Issue persists after clearing data and cache and after a clean reinstall. Issue is resolved by setting media.android-media-codec.enabled to false. The user who posted the original thread on Reddit had the issue resolve itself after a week, but another user and I are still having issues, with the two of us both happening to use OnePlus devices (mine is a OnePlus 7 Pro).

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/9218

**Comment by ekager** [comment]
@vnprak are you still seeing this issue?
