### ISSUE TITLE
FNX-4360 ⁃ Delete all site data for one site only

### ISSUE THREAD

**Issue by Dischi** [mozilla-mobile/fenix#10537]
### Why/User Benefit/User Problem
Currently I can only delete all site data. That is too much, sometimes I only want to delete the data of the current site. This is possible for the desktop Firefox

I suggest an option when clicking on the lock icon.

And BTW, Firefox Preview is a great improvement.

**Comment by cadeyrn** [comment]
Duplicate of #10363.
