### ISSUE TITLE
FNX-4372 ⁃ [Bug] Google search does not work

### ISSUE THREAD

**Issue by gitgitgitg** [mozilla-mobile/fenix#10549]
## Steps to reproduce
Install Firefox Preview 5.0 and type "Test" in url bar. On https://www.google.com/search?q=Test&ie=utf-8&oe=utf-8&client=firefox-b-m scroll to end and tap on "More results".

### Expected behavior
More search results should be loaded.

### Actual behavior
Nothing happens.

### Device information
* Android device: 10
* Fenix version: 5.0

**Comment by SS1113** [comment]
I have tried to reproduce the issue but the page results load for me. It may be possible that some extensions are interfering. Have you tried disabling extensions and clearing your browsers cache and cookies?

**Comment by gitgitgitg** [comment]
Thank you. Clearing browsing History and website data solved the problem.
