### ISSUE TITLE
[Bug] Other app's text selection menu "search privately" option can be misleading

### ISSUE THREAD

**Issue by Dustie** [mozilla-mobile/fenix#10543]
## Steps to reproduce
1. Long-press any text
1. Look at popup menu
1. If other browsers are installed they can have a shortcut here
1. Press it and you send the text to that app

### Expected behavior
The popup menu should clearly show what the shortcut does.

### Actual behavior
In the case of Opera you get a "Search privately" menu item, which does not warn that you are about to send data to another app. It would be the opposite of Private. Firefox's own search is hidden in the overflow menu.

![2020-05-06-10-41-27-313ce2](https://user-images.githubusercontent.com/21229918/81496328-1f4c8380-92b7-11ea-83c8-18f9c10d1989.png)

### Device information
* Android device: OnePlus 7T, Android 10
* Fenix version: Newest android version (Firefox preview 75?)

**Comment by ekager** [comment]
Hm I don't think we can change their text but I wonder if we can prioritize our own menu items here
