### ISSUE TITLE
FNX-4365 ⁃ [Bug] Tabs are unloaded from memory too aggressively

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#10542]
## Steps to reproduce
Open a few tabs on a phone with plenty (8GB in my case) of memory.  Switch back to a previous tab (without even switching turning the screen off or opening any other apps).  The previous tabs will often be unloaded from memory and reload upon switching back to them. 

### Expected behavior
Tabs should only be unloaded when the phone has significant memory pressure. 

### Actual behavior
See above 

### Device information
Huawei Mate 20 X

* Android device: ? 
9.1
* Fenix version: ?
Nightly

**Comment by SS1113** [comment]
Seems like duplicate of #9039

**Comment by robsmith11** [comment]
Ah yes, I see they're discussing unloading that happens without backgrounding Firefox now.
