### ISSUE TITLE
FNX-4759 ⁃ Fenix doesn't show up in the Android share sheet

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#1054]
## Steps to reproduce
1. Open any app that allows you to share a link with an Android share intent.

### Expected behavior
1. Seeing Fenix in the list.

### Actual behavior
1. Fenix is not there.

### Device information
* Android device: Android 9
* Fenix version: Nightly (17-03-19)

The fix is to separate the `android.intent.action.SEND` intent into it's own `intent-filter`, similar to how it's done [in R-B](https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/AndroidManifest.xml#L75-L79).

**Comment by sv-ohorvath** [comment]
Verified as fixed on Pixel (Android 9) & HTC Desire 820 (Android 6.0.1). Master build 3/21
