### ISSUE TITLE
FNX-4363 ⁃ Show only the main site in the certificate information

### ISSUE THREAD

**Issue by theartifaktorq** [mozilla-mobile/fenix#10540]
_I think only the main site should be shown when viewing the certificate information of the connection._

**_

> Displaying the full URL is not useful since it is already displayed in the address bar. It is preferable to show only the main site to which the certificate belongs.

_**

![photo](https://user-images.githubusercontent.com/64933235/81482650-37140100-91fe-11ea-8fbe-32c432c070f3.jpg)UNITO-UNDERSCORE!2020-05-09!UNITO-UNDERSCORE!14-05-30!
![photo](https://user-images.githubusercontent.com/64933235/81482651-37ac9780-91fe-11ea-9177-8b6aa483cf24.jpg)UNITO-UNDERSCORE!2020-05-09!UNITO-UNDERSCORE!14-05-32!

**Comment by Matth7878** [comment]
I don't know if it has been considered but full URL is not displayed in custom tabs.
Being able to see it in certificate information is nice.

**Comment by theartifaktorq** [comment]
> I don't know if it has been considered but full URL is not displayed in custom tabs.
> Being able to see it in certificate information is nice.

I don't know if this is under consideration but from my point of view the main url is the one that should be shown as this is how you know that the certificate belongs.

**Comment by cadeyrn** [comment]
@mcarare I saw you wrote a "fix" for this issue. Please note that it was intentional to display the full URL, please see #3809.

**Comment by mcarare** [comment]
@cadeyrn Thank you for your mention, I already saw that in the code. Nevertheless, I do not see any reason we would stray away from the Firefox on mobile and desktop way of showing the site info. 
Maybe UX or @ekager  can help come to a decision?

**Comment by ekager** [comment]
Delegating this decision to UX since we did do this intentionally originally in #3809 but I don't see discussion there about why

**Comment by brampitoyo** [comment]
Correct. This is by design. Since we decided to clean up the address bar by only showing eTLD+1, the only way for users to see the full address is through visiting the Site Information Panel.

**Comment by mcarare** [comment]
@brampitoyo I stil think that showing an irrelevant info for the context (site certificate) is not the best user experience. Especially for cases when the url would be a fairly long one.
 At least, the full url could be shown on press or other means.
