### ISSUE TITLE
[Bug][PiP] The video cannot be seen as the URL and website elements are displayed when a new video starts

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10555]
## Steps to reproduce
1. Launch Fenix.
1. Access YouTube and watch any video.
1. Add the video in PiP.
1. Wait until the next video starts.
    1. Expected behavior
The video is correctly displayed.
    1. Actual behavior
The video cannot be seen as the URL and website elements are displayed when a new video starts
    1. Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 5/11.**

![20200511-141710](https://user-images.githubusercontent.com/42831109/81557080-0fef3800-9394-11ea-8e0a-a0ed053ead0b.gif)

**Comment by sflorean** [comment]
Reproducible on 85.1.3 with Pixel 3 (Android 11).
