### ISSUE TITLE
[Bug Report] Slow PWA Lauch

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10550]
## Steps to reproduce
* open fenix on android
* add any PWA to home screen
* close the browser
* open the pwa from home screen

### Expected behavior
It should lauch PWA almost instatntly

### Actual behavior
It takes minimun 30 seconds to open a even fully offline PWA and meanwhile just shows a blank screen

### Device information
* Android device: Redmi 7 (9.0)
* Fenix version: 5.0

## UPDATE
I tried to disable the add-ons and got a performance enhancement from almost 30 to under 5 seconds PWA launch.

## Note :
```
  Main addon responsible for slow down is UBlock origin.which i love a lot please fix this issue soon.
```

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 5/11 #21320625.

Devices:
- Google Pixel 3 (Android 10);
- Samsung Galaxy Note 8 (Android 9).

**Comment by KWierso** [comment]
For me, sometimes the PWA loads very quickly. Other times, it takes a couple seconds to go from the white splash screen to the PWA content. Other times, it hangs on the white screen, seemingly forever.

I haven't been able to figure out what determines which outcome happens. Killing Fenix from the app info page doesn't seem to fix it. Fenix itself (non-pwa) opens quickly and loads content just fine while the PWA is hung on the white screen.

Pixel 3, I also have uBlock Origin installed.

I can try to grab a performance profile if that's not too hard to set up.

**Comment by klint** [comment]
Also happening to me.
Note that opening in Fenix from the PWA menu does not help. I have to edit the address bar and go to the URL. Then only the page is displayed.

**Comment by astarq** [comment]
Also get this, only when any extensions are installed (without, pwas tend to load quickly)

**Comment by astarq** [comment]
Related to #10689
