### ISSUE TITLE
Overscroll in web content

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1055]
### Why/User Benefit/User Problem
Users like the overscroll glow effect when hitting scroll boundaries in Android. 

### What / Requirements
When a user hits a scroll boundary, Fenix should show a glow showing that the boundary has been reached. 

This can be seen in Webview based Focus.

### Acceptance Criteria (how do I know when I’m done?)
When a user hits a scroll boundary after reaching a scroll boundary, Fenix should show a glow showing that the boundary has been reached.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-689)

**Comment by aneesh98** [comment]
I am a new to open source and I would like to work on this, can I?.

**Comment by kbrosnan** [comment]
This bug does not have a specification it is not ready for development.

**Comment by ekager** [comment]
Closing in favor of dupe #1056

**Comment by ekager** [comment]
Reopening because I misread that this was about the web content and the other was about settings. 
AC issue: mozilla-mobile/android-components#2390
A GV bug is opened here: bugzilla.mozilla.org/show_bug.cgi?id=1536833

**Comment by Mugurell** [comment]
[`OverscrollEdgeEffect`](https://dxr.mozilla.org/mozilla-central/rev/dbabf2e388fa750b4901df8dfab60d8a17a0c5ff/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/OverscrollEdgeEffect.java) already exists in GeckoView (already used in Fennec) and would automatically add such effects to Fenix also once a few quirks I think in GV integration would be resolved.
(snorp's comment - https://github.com/mozilla-mobile/fenix/issues/3262#issuecomment-603854412)
So I think this is what we should concentrate on for this ticket.

**Comment by Mugurell** [comment]
@snorp, following https://github.com/mozilla-mobile/fenix/issues/3262 which would add a pull down to refresh effect and GV integration which would add the overscroll edge effect users would get two independent effects for the same swipe down action. I don't think this is desirable.

Wouldn't it be better if GV would provide an overscroll callback so that consumers like A-C/Fenix would have more control over which such effects appear and how they function?
I'm thinking that the overscroll effect is more of an Android feature, not something that GV should handle, if this matters as another argument for the above..

**Comment by yoasif** [comment]
In Bromite, the pull to refresh gesture doesn't show an overscroll effect. If the user immediately pulls down, they will see an overscroll effect, however.

Just noting that it isn't necessarily true that you will see multiple effects from the same user action at the same time - choices have been made elsewhere.

**Comment by Poopooracoocoo** [comment]
in chromium the glow effect appears when the user scrolls to the top inertially while it pulls to refresh when the finger is still on the screen

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809969

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
