### ISSUE TITLE
FNX-4760 ⁃ Overscroll glow in settings pages

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1056]
### Why/User Benefit/User Problem
Users like the overscroll glow effect when hitting scroll boundaries in Fenix settings pages.

### What / Requirements
When a user hits a scroll boundary, Fenix should show a glow showing that the boundary has been reached. 

This can be seen in Webview based Focus.

### Acceptance Criteria (how do I know when I’m done?)
When a user hits a scroll boundary after reaching a scroll boundary, Fenix should show a glow showing that the boundary has been reached in the settings pages.

**Comment by Vv2233Bb** [comment]
I think it is already there, but white on white isn't that easy to see. So it should be about the darkening of the glow.

**Comment by ekager** [comment]
Thanks for filing!
I have opened an issue in AC (https://github.com/mozilla-mobile/android-components/issues/2390) to see if this is something that can be added there.

**Comment by pocmo** [comment]
Filed GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1536833

**Comment by kbrosnan** [comment]
This was correctly filed as two separate bugs. The settings page is under the control of the Fenix team. The web content requires outside work. Merging them made this confusing.

**Comment by ekager** [comment]
Ah I misread it! Thanks @kbrosnan , reopening #1055, and this should be closed easily by changing the overscroll glow color in light mode in the project.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Pixel (Android 9) & HTC Desire 820 (Android 6.0.1). Master build 3/21
