### ISSUE TITLE
PWA "Add to Home screen" confirmation dialog isn't displayed on certain devices

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#10560]
## Steps to reproduce
1. Go to twitter.com and tap on the main menu.
1. Tap on "Install".

### Expected behavior
An "Add to Home screen" confirmation dialog is displayed, containing the name and icon of the web page.

### Actual behavior
The confirmation dialog isn't displayed. The device home screen is displayed and the new PWA added. 

### Device information
* Android device: Xiaomi Redmi Note 8T (Android 9), OnePlus A3 (Android 6.0.1).
* Fenix version: Nightly 5/11.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-709)

**Comment by NotWoods** [comment]
Unfortunately this is this is totally dependent on the launcher being used. I'm not sure if we can do anything here.

**Comment by AndiAJ** [comment]
Still reproducible on **`Firefox 88.1.2`** using a OnePlus A3 (Android 6.0.1)

**Comment by sflorean** [comment]
Still reproducible on 91 Beta builds with Xiaomi Redmi Note 8T (Android 9).

**Comment by lobontiumira** [comment]
Reproducible also on Sony Xperia z5 Premium (Android 7.1.1), on Beta 91.0.0-beta.5.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807429

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
