### ISSUE TITLE
FNX-4390 ⁃ Make Search Fragment  include AppBarLayout and AwesomeBar in the same XML

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#10568]
Our current Search fragment XML (`fragment_search.xml`) currently includes a `FrameLayout` where we plug in the BrowserBar and a `Constraintlayout` that is used to plug in the AwesomeBar.

However, this means that we `inflate` in the `OnCreateView` in the `SearchFramgnet.kt` and inflate again in both `ToolbarView` and `AwesomeBarView`. By moving both layouts in the `search_fragment` we can reduce some of the inflation time. (on average by ~50-60ms). 

Note for testing: The first click after opening the app is the one that takes >450ms. This is the flow we're testing. I.e: Open the app --> touch the URL bar --> Search Fragment + keyboard is displayed ready to use.  To repeat --> kill the app --> wait 5-10seconds --> repeat

**Comment by mcomella** [comment]
@MarcLeclair Please add a profile.

**Comment by MarcLeclair** [comment]
Here's the profile: https://share.firefox.dev/3gLYxKa

As you can see we have ~4 or 5 traversals. Reducing the depth of our XML file and the use of a framelayout and inflating sequentially in their own files would reduce the number of traversals.
