### ISSUE TITLE
FNX-4396 ⁃ [Bug] Long press/contextual menu on address bar should have borders

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10577]
## Steps to reproduce
1. Open Fenix
1. Long press address bar

### Expected behavior
The menu options that appear should have a border, like other long press menus. 

Good menu looks like:

![signal-attachment-2020-05-11-201739](https://user-images.githubusercontent.com/152493/81624668-c79c3e00-93c4-11ea-9c65-58ab695b6520.png)

### Actual behavior
No borders, causing the menu to become lost in a sea of white. 

![signal-attachment-2020-05-11-201736](https://user-images.githubusercontent.com/152493/81624658-bd7a3f80-93c4-11ea-884e-e1ce0bdff969.png)

### Device information
* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by ekager** [comment]
We should definitely do this. Paging UX for specific colors for the different themes. :)

**Comment by brampitoyo** [comment]
@ekager @yoasif Agreed!

The specific “Above” colour values are as follows:
- Light theme: White `#ffffff`
- Dark theme: Dark Grey 50 `#32313C`
- Private theme: Ink 50 `#291D4F`

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/4. Device: Google Pixel 3 (Android 10) and Nokia 6 (Android 7.1.1).
