### ISSUE TITLE
FNX-4761 ⁃ Cannot open old sessions

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1057]
## Steps to reproduce
1. Open Fenix
1. Tap previous session

### Expected behavior
Previous session is loaded. 

### Actual behavior
Nothing happens.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1912 (Build #10760203 :lizard: 67.0a1-20190312095443)

[logs-2019-03-18-12-42-57.zip](https://github.com/mozilla-mobile/fenix/files/2979261/logs-2019-03-18-12-42-57.zip)

**Comment by Vv2233Bb** [comment]
https://github.com/mozilla-mobile/fenix/pull/1051

**Comment by sv-ohorvath** [comment]
Doesn't reproduce anymore. Closing.
device: Pixel (Android 9)
