### ISSUE TITLE
[Bug] No Leanplum event is firing when default browser is updated to Firefox Beta

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#10574]
## Steps to reproduce
1. Download Firefox Beta but do not make it your default browser
1. Take steps to find device in Leanplum
1. Go into device settings and set Firefox Beta as your default browser
1. Go to device ID profile in Leanplum to view 'milestones' for events and attributes

### Expected behavior
1. Open app
1. Two events are seen under 'milestones' on my device ID: E_Launch_Browser & E_Launch_But_Not_Default_Browser
1. Change default browser to Firefox Beta
1. Event E_Changed_Default_to_Fennec is seen under 'milestones' on my device ID
1. Open app (*Note: this is expected for Fennec, but there should be an event similar to this one for Fenix. i.e. E_Changed_Default_to_Fenix
1. Event E_Launch_Browser is seen under 'milestones' on my device ID

### Actual behavior
1. Open app
1. Two events are seen under 'milestones' on my device ID: E_Launch_Browser & E_Launch_But_Not_Default_Browser
1. Change default browser to Firefox Beta
1. No new event is added to 'milestones' on my device ID
1. Open app
1. Event E_Launch_Browser is seen under 'milestones' on my device ID

### Device information
* Android device: Google Pixel 3
* OS: 10
* Fenix version: Beta 75.0.0-beta.6

**Comment by cbonacuse** [comment]
FYI @lwa-moz & @st3fan

**Comment by st3fan** [comment]
Taking a quick look at the code, it looks like this is not an event that Fenix has implemented.
