### ISSUE TITLE
FNX-4586 ⁃ [UITests] Intermittent ContextMenusTests

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10586]
verifyContextShareLink
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8016584804846223411/executions/bs.d537a6aa28cbc99/testcases/1/test-cases

verifyContextOpenLinkPrivateTab
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8016584804846223411/executions/bs.54bf21bfd92011a8/testcases/1/test-cases

**Comment by AaronMT** [comment]
From a video 
![Screen Shot 2020-05-12 at 9 41 13 AM](https://user-images.githubusercontent.com/102331/81699125-edf9c200-9434-11ea-9edc-9a7f7224647d.png)

Screenshot from a running test on in the Matrix above. Why would a `click` in 

```Kotlin
fun longClickMatchingText(expectedText: String) {
        val mDevice = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
        mDevice.waitNotNull(Until.findObject(text(expectedText)), waitingTime)

        val element = mDevice.findObject(text(expectedText))
        element.click(LongClickDuration.LONG_CLICK_DURATION)
    }
```
Intermittently do a text selection?

**Comment by AaronMT** [comment]
@sv-ohorvath Can you disable these two tests? Thanks.

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath Can you disable these two tests? Thanks.

Sure.

**Comment by sv-ohorvath** [comment]
more context menu tests failing: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6709449113184201127/executions/bs.4704ff2cb2bcc116/test-cases

https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6709449113184201127/executions/bs.6ae0ec1e040a9947/test-cases

**Comment by AaronMT** [comment]
Depends on https://github.com/mozilla-mobile/fenix/issues/10619

**Comment by AaronMT** [comment]
The clipboard tests are hitting a system level widget that appears over the address-bar recommending a search.
![Screen Shot 2020-04-01 at 3 44 46 PM](https://user-images.githubusercontent.com/102331/85621298-0fa0b880-b633-11ea-97b7-03cc54158981.png)

I don't know if there's a way to disable this as it's either OS or Keyboard settings level. Not sure what the widget is even called really?

**Comment by AaronMT** [comment]
Re-enabling all except `verifyContextCopyImageLocation` which still hits the above thing. Might have to just hit X if it's available.
