### ISSUE TITLE
FNX-4401 ⁃ [Bug] Ripple Animation Appears Behind Buttons in The New Tab Tray

### ISSUE THREAD

**Issue by umerf52** [mozilla-mobile/fenix#10589]
## Steps to reproduce
Enable Debug Menu

Turn on the new tab tray
Open the tab tray
Click on any button on the bottom bar

### Expected behavior
The ripple animation should appear on top of the buttons

### Actual behavior
The animation appears behind the bottom bar and is barely visible
![image](https://user-images.githubusercontent.com/20578979/81671464-75115f00-9462-11ea-8b60-55d2f4a9cfc8.png)
In the image, I pressed on the '+' button to open a new tab. Notice how barely the animation is visible.

This occurs in light theme as well. Private browsing is also affected.

### Device information
* Android device: OnePlus 3T, Android 10
* Fenix version: Nightly 200511 06:21 (Build #21320626)

**Comment by sblatz** [comment]
@mcarare if you make traction on this, could you maybe share your findings with this AC ticket? https://github.com/mozilla-mobile/android-components/issues/4673

**Comment by mcarare** [comment]
Closing as the UI has changed.
