### ISSUE TITLE
[UX] Investigate browser gestures

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10585]
This ticket is for UX team to investigate how we might we solve the following user problem:

Problem Statement:
Mobile users are accustomed to using gestures to navigate their mobile apps. Currently, users don't have a fast way of completing common tasks through gestures. 

Most common user requests:

Swipe on nav bar gesture to switch tabs
Swipe to left/right to go page back/forward
Pull to refresh

Research Questions:
-What are the most useful AND expected gestures in a mobile browser?
-What are some user actions that could be made simlper and easier by introducing a gesture?

See meta for various gesture ideas: #176 
GV issue for back/forth navigation [gesture](https://bugzilla.mozilla.org/show_bug.cgi?id=1509249)

**Comment by person808** [comment]
Just a heads up, I'm looking at tackling gestures as my intern project
