### ISSUE TITLE
Investigate Sync Top Sites

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10583]
This ticket is for UX + Sync team to investigate how we might we solve the following user problems:

Problem Statement:
FxA users can't access their Fenix top sites on other FxA enabled devices and vice versa, so they need to create them manually in 2 different places. 

Meta: #7936

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-741)

**Comment by delxg** [comment]
A great alternative to this would be to give us the ability to display a bookmark folder on the homescreen. Bookmarks can already be synchronised and have a much better management UI that top sites.

This and tab sorting are the features I miss most from the old Firefox.

**Comment by jonalmeida** [comment]
Closing for now until we prioritize the meta task.
