### ISSUE TITLE
FNX-4764 ⁃ [Bug] Find bar shows 0/0 when you quickly press next

### ISSUE THREAD

**Issue by hoqogi** [mozilla-mobile/fenix#10588]
## Steps to reproduce
Type something in the bar, press next quickly a few times
![Screenshot](https://user-images.githubusercontent.com/64539966/81666809-2dcba400-944b-11ea-863e-c6dd25481e24.jpg)UNITO-UNDERSCORE!20200512-121958!UNITO-UNDERSCORE!Firefox Preview!

### Expected behavior
Shows the current position, like 5/20

### Actual behavior
0/0

### Device information
* Android device: Samsung S10 Android 10 
* Fenix version: 5 from GP

**Comment by LaurentiuApahideanSV** [comment]
The issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/7953. I will close this issue as it will be handled there.
