### ISSUE TITLE
FNX2-13213 ⁃ Redirect moz://a requests to manifesto

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#10596]
### Why/User Benefit/User Problem
This is in line with Desktop and just a neat little easter egg we could easily add. :egg:

### What/Requirements
Redirect to the locale specific version of the manifesto: https://www.mozilla.org/en-US/about/manifesto/ when a user enters `moz://a` into the Toolbar.

### Acceptance Criteria (how do I know when I’m done?)
Redirection works and internal glee.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 8/26 with Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
Searching for moz://a in the URL bar redirects to https://www.mozilla.org/en-US/about/manifesto/ page.
