### ISSUE TITLE
FNX-4406 ⁃ [Bug] autofill for login/password input manager doesn't work

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#10597]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1635876

User Agent: Mozilla/5.0 (Android 10; Mobile; rv:75.0) Gecko/75.0 Firefox/75.0

Steps to reproduce:

using bitwarden on android
have a entry for laposte.net
go to website on Firefox 75.0.0-beta.6
try to login
no dropdown of bitwarden
go to you android home screen
go back to Firefox
dropdown of bitwarden appear

Actual results:

no dropdown are shown on first load

Expected results:

dropdown of password manager need to be shown

la poste.net is an example, other websites have same behavior, work great on Google chrome or Vivaldi browser

**Comment by abodea** [comment]
Hi, @st3fan I added this https://github.com/mozilla-mobile/fenix/issues/9854 a while ago, maybe it's related to this issue.
It occurs when changing the password manager and somehow is the same behavior no matter the 3rd party manager app.

**Comment by st3fan** [comment]
Closing as a duplicate of #9854
