### ISSUE TITLE
FNX-4765 ⁃ [Meta] Integrate Adjust SDK

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#106]
Setup Adjust SDK similar to our other products.

* [ ] Request data review from @liuche (is this necessary without Adjust for telemetry?)

**Comment by liuche** [comment]
Hey @vesta0, what does the question in the top comment mean "is this necessary without Adjust for telemetry" are you no longer using Adjust for telemetry?

**Comment by vesta0** [comment]
@liuche looks like this was a question from Susheel back in December so I have no context what he meant. I believe we are using Glean for telemetry and Adjust for campaign tracking. Is that right @colintheshots ?

**Comment by liuche** [comment]
Cleaning this up here - moving the Adjust docs from the wiki to the in-code `docs/` folder - see PR for data review.
