### ISSUE TITLE
FNX2-13216 ⁃ Disable "download link" feature, at least for html files

### ISSUE THREAD

**Issue by bepvte** [mozilla-mobile/fenix#10604]
### Why/User Benefit/User Problem
This function usually results in an .html file being downloaded. In my opinion, it is very unlikely that a mobile user would want to archive a page in an .html file. Additionally, this file doesn't open in fenix when selected in a file manager, and the downloaded page is incomplete (not a .mhtml and does not have web assets in a folder). 

In my opinion, this feature does not have much use on a mobile browser. It takes up space in the menu and may not work as expected for downloading files with redirects. I think there should be a discussion about whether its worth keeping.

If downloading web pages is exposed anywhere in Fenix, I think it should be with a built in interface to access them, like #219 suggests. But I also don't think its really that relevant or useful of a feature on a mobile device.

### What/Requirements
Determine the future of the feature.
Either disable it for html files, or make such files open in Fenix, or remove the feature altogether.

### Acceptance Criteria (how do I know when I’m done?)
When the feature either works in a predictable manner, or is removed.

**Comment by yoasif** [comment]
FWIW, Chrome offers the same feature but saves it in a different format:

```
From: <Saved by Blink>
Snapshot-Content-Location: https://en.m.wikipedia.org/wiki/Superliner_(railcar)
Subject: Superliner (railcar) - Wikipedia
Date: Tue, 12 May 2020 20:39:25 -0000
MIME-Version: 1.0
Content-Type: multipart/related;
	type="text/html";
	boundary="----MultipartBoundary--WHbT7aPJmQNiYn6LEDz1caokiyHOWbP2cWRTHkAU29----"
```

Looks like a mht-alike or some other kind of web archive. 

[Superliner (railcar) - Wikipedia.zip](https://github.com/mozilla-mobile/fenix/files/4618385/Superliner.railcar.-.Wikipedia.zip)

It'd be nice if Fenix were to offer a version of this via something like https://addons.mozilla.org/firefox/addon/single-file/ but built in as a first class feature like in Chrome.

**Comment by liuche** [comment]
@kglazko this is the issue I mentioned earlier!

**Comment by kglazko** [comment]
Thank you @liuche ! @vesta0 - what do you think about this?

**Comment by vesta0** [comment]
Was do you mean by "download link" here? Are you talking about either one of these buttons? 

![Screenshot_20200514-123039](https://user-images.githubusercontent.com/42752644/81960541-1a514200-95df-11ea-87f0-fc729dc7466d.png)
![Screenshot_20200514-123207](https://user-images.githubusercontent.com/42752644/81960548-1cb39c00-95df-11ea-9307-bf17365158e0.png)

**Comment by bepvte** [comment]
@vesta0 No, I mean when pressing and holding on a regular link it shows a menu with "Open in new tab" and "Download Link"

**Comment by vesta0** [comment]
Thanks @bepvte 

@kglazko yes please let's go ahead and disable that link for html files at the very least

**Comment by Mugurell** [comment]
This should be ready to test in the next nightly.
Please note that the speculative code added in a-c would result in hiding this option only for urls ending with `htm` / `html`.
At the moment we cannot know for sure if a url is for a webpage or of another type without actually opening a connection to it, which is an expensive operation.
Also note that other major browsers are offering this "Download link" option, for all types of resources, including webpages.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/12 with the following devices:
- Samsung Galaxy Note 10 (Android 10)
- Huawei MediaPad M2 (Android 5.1.1)
The download option is not displayed when long tap on a .html link/page.

**Comment by ohhai** [comment]
I use this sometimes even for html pages. Actually, would like to have "save" option for all links.
Hope it might be reenabled by addon.
