### ISSUE TITLE
[Bug] Reader mode settings - serif / sans serif text is broken in two lines in French

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#10601]
## Steps to reproduce
1. Choose French in language settings (but it could happen with other languages, I haven't tested)
1. Read something where you can enable reader mode. For example, let's take [Apache License v2](https://apache.org/licenses/LICENSE-2.0.txt).
1. Go to appearance settings
    1. Expected behavior
The "Sans serif" and "Serif" text should be in one line (like with english version), or at least (if it's not possible because the word is too long) not have a word broken in two lines like
"Sans
seri
f"
English:
![](https://user-images.githubusercontent.com/58657617/81725345-3cc74c00-9475-11ea-9b2f-9853b9dbfcb8.png)

### Actual behavior
In French, empattement = serif.
We have
"Sans
empattemen
t"
and
"Empatteme
nt"
![](https://user-images.githubusercontent.com/58657617/81725150-f07c0c00-9474-11ea-846e-4a1a92650dc1.png)

### Device information
* Android device: 9
* Fenix version: 5.0, today's nightly (200512)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-773)

**Comment by B0pol** [comment]
Actually you can cut a word in two parts, but there are rules, and **they are broken here**.

--> https://fr.wikipedia.org/wiki/Césure_(typographie) (This page hasn't been translated in english on wikipedia, so you may have to use a translator).

In French, generally you can cut between two syllabe. If the word has a dash, you can cut. If the word has two consonants, you can. So here, I think here it would be cut as empat-
tement (don't forget to add the dash).

Btw, Wikipedia states
> La plupart des logiciels de traitement de texte et de mise en pages comportent un programme de césure automatique s'adaptant à la langue du texte. Mais en l’absence d’un tel logiciel, les coupures automatiques seront totalement évitées, sauf si la langue ou l’écriture l’y autorise. 

--> Most word processing and page layout software includes an automatic hyphenation program that adapts to the language of the text. **However, in the absence of such software, automatic hyphenation will be completely avoided unless the language or writing allows it**.

On top of that, using a newline is more confortable to read than hypenation.

**Comment by B0pol** [comment]
Still an issue

**Comment by B0pol** [comment]
Bump

**Comment by sflorean** [comment]
I was able to reproduce this issue on latest Firefox versions (Beta, Nightly) with Samsung A32 (Android 11).

**Comment by Alexandru2909** [comment]
While investigating this issue, I found that changing the break strategy does not help, neither does autosizing the text. In order for autosizing to work, the height of the view needs to be fixed, but the height of the component inside AC is set to 'wrap-content'. A workaround for this is to set `maxLines` to 1:

![font3](https://user-images.githubusercontent.com/35462038/151309913-715fdcb3-6a81-496d-9c41-d59f42e30568.jpeg)

However, this fix works only for Android >= 8.0 and may produce unexpected behavior for other languages; for example the text in Japanese should include "(Sans-serif)" after the translation, but using `maxLines=1` trims that part.
Another solution that worked for me is lowering the text size down to `20sp`:

![font5](https://user-images.githubusercontent.com/35462038/151310818-f076795c-9fc4-41b0-ba01-7bf78463f5c7.jpeg)
![font4](https://user-images.githubusercontent.com/35462038/151310827-4cd1bac2-b8b5-47be-a916-a088c068feb3.jpeg)

**Comment by cpeterso** [comment]
UX says:

> This looks like an issue with font size that won’t need UX or content input. Eng make the call on changing the font size. Looks like there are some recommendations below.

**Comment by SoftVision-LorandJanos** [comment]
Tested on Oppo Find X5 (Android 12) with the latest Nightly 108.0a1 (2022-10-27) build.
I still have "Empattemet" word not fitted in the same line:
![1666855332232](https://user-images.githubusercontent.com/48829350/198228915-e14484bb-8c6a-46d2-8257-bcdc2ba6a633.JPEG)

**Comment by SoftVision-LorandJanos** [comment]
I managed to reproduce this issue on a Huawei P20 Lite (Android 10) as well.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Beta 110.0b2 build.
Device used: Oppo Find X5 (Android 12).
