### ISSUE TITLE
Bookmarks Menu item should open last viewed bookmark folder

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10606]
### Why/User Benefit/User Problem
As a user, I would like to maintain context when viewing bookmarks in Fenix, especially if I am a switcher where this is a common feature. 

### What/Requirements
1. When I open the bookmarks menu item, I am taken to the last bookmark folder I had viewed
1. Fixing https://github.com/mozilla-mobile/fenix/issues/10462 so that users do not have to descend back to the root of bookmarks when exiting bookmarks

### Acceptance Criteria (how do I know when I’m done?)
If I was last looking at my desktop bookmarks toolbar in Fenix and closed the page and reopen Bookmarks, I am taken back to that folder.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-782)

**Comment by frozenxuan** [comment]
I really think this is a must-have feature UX-wise. Current mechanism is very cumbersome and frustrating to use, took users too many steps to do such a straightforward thing.

An app with good UX design should be able to quickly navigate/guide users to the feature/option/location they demand, this is even more important in mobile platform since the screen is smaller and less UI elements could be displayed at once. Thus UX designers should try to minimize the number of steps to achieve those actions, not the other way around, which sadly isn't the case currently.

**Comment by artella-coding** [comment]
@yoasif completely agree that we need this on android. 4 years ago I posted the same thing for firefox ios at  https://bugzilla.mozilla.org/show_bug.cgi?id=1309018 and https://github.com/mozilla-mobile/firefox-ios/issues/2144 and it was kept open for 2 years and then eventually closed. I hope this ticket does not meet the same fate. Chrome, Brave, and even Edge all implement the feature requested above (that is they remember the last bookmark folder visited, even if they are completely removed from the background and started from scratch). It seems that only Firefox is lacking this feature.

**Comment by artella-coding** [comment]
p.s. another user has also requested for this feature at https://github.com/mozilla-mobile/fenix/issues/4318

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1366435

**Comment by dyura** [comment]
Just to mention, that the current iOS Firefox, at least 105 and newer, correctly opens the last viewed bookmark folder as all other browsers. Only Android Firefox every time opens bookmarks on the initial topmost  level.

**Comment by epigramx** [comment]
Why is this still an issue? It doesn't work on current regular androids. Is there a technical limitation with them?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812713

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
