### ISSUE TITLE
FNX-4419 ⁃ [Bug] PushError$MalformedMessage: Key con is missing in the map.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#10603]
Sentry issue: [FENIX-NIGHTLY-2R7](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7893043/)

We can try to reduce these by using the `aes128gcm` default encoding.

**Comment by jonalmeida** [comment]
The errors for this are going down now with the default set.

**Comment by codrut-topliceanu** [comment]
@jonalmeida 
Crash reappeared on sentry : https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8268894
on org.mozilla.firefox_beta-76.0.0-beta.1
Should I create another issue for this?
