### ISSUE TITLE
FNX-4436 ⁃ [Bug][a11y] Consider increasing contrast of "selected" placeholder text for Bookmarks and History

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#10624]
### Steps to reproduce
1. Install Google Accessibility Scanner and turn it ON.
1. Go to History or Bookmarks.
1. Long tap on one of the entries.
1. Scan the page.

### Expected behavior
No major discrepancies are suggested.

### Actual behavior
A suggestion for text contrast is displayed.
![Screenshot](https://user-images.githubusercontent.com/58466444/81831028-867f6780-9545-11ea-9685-eef5f9c7673d.jpg)UNITO-UNDERSCORE!20200513-180610!UNITO-UNDERSCORE!Accessibility Scanner (1)!

### Device information
* Android device: Samsung Galaxy Note 10 (Android 10).
* Fenix version: Nightly 13/5 and Beta 5.0.0-beta.2.

**Comment by brampitoyo** [comment]
@sflorean Hi Sorina, here’s my thought: since the top app bar is meant to only contain large texts (headers) and graphical objects (icons), I think that it’s ok for the colour contrast value to match WCAG AA (at least 3:1). My suggestion would be to leave the contrast as is.

We’ve used `#592acb` as an accent colour (which would have a contrast ratio of 7.76:1 – passes AAA), but that value was used only on our light theme.

I’m CCing @AmyYLee in case she has any suggestion.

**Comment by AmyYLee** [comment]
@

> @sflorean Hi Sorina, here’s my thought: since the top app bar is meant to only contain large texts (headers) and graphical objects (icons), I think that it’s ok for the colour contrast value to match WCAG AA (at least 3:1). My suggestion would be to leave the contrast as is.
> 
> We’ve used `#592acb` as an accent colour (which would have a contrast ratio of 7.76:1 – passes AAA), but that value was used only on our light theme.
> 
> I’m CCing @AmyYLee in case she has any suggestion.

Hi, 

This is the style guide for dark theme. I would suggest we stick with this unless we change the colour universally across the app. It's been difficult to find a colour that passes contrast test on a dark background and also white text so I'd be cautious to change what we currently have. Thanks
<img width="411" alt="Screen Shot 2020-05-19 at 13 43 56" src="https://user-images.githubusercontent.com/5992746/82360299-2e2de700-99d7-11ea-9792-cb3a5b74bcf6.png">

**Comment by sflorean** [comment]
@AmyYLee @brampitoyo thank you for the context! I'll close the issue.
