### ISSUE TITLE
[Bug] SafeInCloud is not working on Fenix for autofill

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10621]
## Preconditions
Install and set SafeInCloud as the default app for autofill

## Steps to reproduce
1. Launch Fenix and access twitter.com (or any website).
1. Tap on the username or password field in order to autofill.
    1. Expected behavior
The SafeInCloud is displayed as an autofill option when trying to login.
    1. Actual behavior
SafeInCloud is not working on Fenix for autofill
    1. Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 5/13.**

![20200513-144534](https://user-images.githubusercontent.com/42831109/81808801-ed425800-9528-11ea-84b8-38a3a8710471.gif)

**Comment by delia-pop** [comment]
I was not able to reproduce this issue on the latest Nightly from 05/19 or GVE with Google Pixel 6 (Android 12).
On both apps, with SafeInCloud set as default autofill app and a login for Facebook saved, the autofill works as expected.

The current flow is as follows:

1. Tap on the username/password fields.
2. Tap on the "Unlock SafeInCloud" option above the keyboard.
3. Enter the Master Password, select "Search" and select the saved login.
4. Confirm the prompt to assign the card to the website.
5. The selected saved login is now available above the keyboard and if selected, the data is correctly imported.
