### ISSUE TITLE
FNX-4435 ⁃ Switch (Migrated) Fennec Beta back to

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#10626]
Now that (Leanplum) messaging for Old Firefox Beta is finished we need to switch the _Google API Key_ back to the FCM one so that the messaging starts working for migrated users.

@jonalmeida can you confirm that we can use the same key for Beta that we use for FIrefox Preview?

This is a change in the Leanplum dashboard that for example @st3fan can make.

**Comment by jonalmeida** [comment]
@st3fan I verified from prior conversation with relman that the Firebase apps are under the same project and have the same API key.

**Comment by st3fan** [comment]
I switched over the keys for _Firefox Beta_.

cc @cbonacuse

**Comment by cbonacuse** [comment]
Thank you so much for your quick action @st3fan! This is working for us now.
