### ISSUE TITLE
FNX3-14039 ⁃ Default to "desktop site" by default when the app is used on a desktop (Chrome OS/Samsung Dex/Android Q)

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#10631]
>Additionally to supporting resizing, an important feature would be requesting desktop sites by default when run in desktop mode.
>
>Tons of info in https://developer.samsung.com/samsung-dex/modify-optimizing.html and https://developer.samsung.com/samsung-dex/modify-optional.html (see especially _Samsung Mobile Browser_ section in the latter)

_Originally posted by @bergie in https://github.com/mozilla~~mobile/fenix/issues/3107#issuecomment~~613991223_

**Comment by kbrosnan** [comment]
Duplicate #7039

**Comment by szaimen** [comment]
> Duplicate #7039

Not exactly because this issue is about enabling request desktop side as soon as fenix is opened on a desktop environment.

**Comment by NotWoods** [comment]
Re-opening because this is about automatically setting desktop mode as the default instead of exposing the option

**Comment by kbrosnan** [comment]
When #7039 is fixed UX can provide info on when we might want to enable it by default. These issues are similar enough that only one is needed.
