### ISSUE TITLE
FNX-4446 ⁃ [Bug] Crash when tapping on the search bar while a page is loading on Samsung device

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10647]
## Steps to reproduce
1. Open browser and tap on one of the available top site.
1. Tap on the search bar.
    1. Expected behavior
The search bar is moved at the top of the app with the site being highlighted.
    1. Actual behavior
A crash is triggered.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 5/14

Note:

* The crash is not encountered on Google Pixel 3XL (Android 9) nor on Sony Xperia Z5 (Android 7)
* [Samsung - Crash logcat.txt](https://github.com/mozilla-mobile/fenix/files/4628108/Samsung.-.Crash.logcat.txt)
* I will consider an S2 issue as it is a crash although it seems device specific, but please reconsider changing if it's the case. 

GIF:
![20200514-143459](https://user-images.githubusercontent.com/49859863/81932068-cb61d780-95f3-11ea-9034-4c8709e47524.gif)

**Comment by Diana-Rus** [comment]
Hey, it seems that it crashes even after something loads, please check the new gif. It crashes pretty often.
![20200514-152028](https://user-images.githubusercontent.com/49859863/81934590-dfa7d380-95f7-11ea-8ca4-24b8a36e218e.gif)

**Comment by Mugurell** [comment]
Thanks Diana!
This seems like a recent regression caused by https://github.com/mozilla-mobile/android-components/issues/2930 who's goal was to have the url-bar animated just for vertical scrolls and in the process also tried to increase sensitivity for detecting zoom events.

Classic Samsung, it removed an important property in framework.
Will quickly post a follow-up ticket.

**Comment by Mugurell** [comment]
Created https://github.com/mozilla-mobile/android-components/issues/6978.

**Comment by liuche** [comment]
This should be in nightly now, I'll add a QA-needed label.

**Comment by Diana-Rus** [comment]
Hey checked with build Nightly 5/19 and issue is fixed.Verified on Samsung Galaxy S9 (Android 8).

GIF:
![20200519-102339](https://user-images.githubusercontent.com/49859863/82304095-890a1300-99c4-11ea-905d-497edd16ba5f.gif)

Note:
- I did the scenario from bug description, also navigating to a couple of pages to see the loading.
- I have taken into consideration the it can be triggered by scrolling, in order to activate the animation for the url bar or by zooming but it seems that is all good now.
