### ISSUE TITLE
FNX-4444 ⁃ [Bug] Bookmarks always open in a new tab

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#10645]
## Steps to reproduce
Latest Fenix Nightly, Bookmarks is now a separate menu item (thanks!)
While viewing page content in a tab
3 dot menu, bookmarks, tap a bookmark

### Expected behavior
bookmark should open in current tab (I think) overwriting current content

### Actual behavior
bookmark opens in new tab

### Device information
Galaxy A40, Android 10, today's Fenix

**Comment by B0pol** [comment]
I think it's the expected behaviour, not a bug.

**Comment by sv-sdeiac** [comment]
Hi @Cheap-Skate, thanks for your ticket. 
This behavior is intended right now.
Thanks for your time.
