### ISSUE TITLE
FNX-4445 ⁃ [Bug] 2FA recovery codes txt file can’t be download on Fenix

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla-mobile/fenix#10646]
**Build**
Nightly 200513 build #21340609

**Affected platforms**
Android 9

**Steps to reproduce**

1. Launch Firefox and login using a Firefox account.
1. Go to https://accounts.firefox.com/settings
1. Go to 2FA section and tap on "Enable".
1. Scan the QR code and enter the security code provided by the authentication app.
1. Tap on "Download".

**Expected results**
The codes are successfully downloaded. 

**Actual Results**
“Firefox Nightly can’t download this file type” error message is received.

![download erre](https://user-images.githubusercontent.com/18114210/81927528-779fc000-95ec-11ea-99fa-1bbdc138efe9.gif)

**Comment by Amejia481** [comment]
This bug is related to blob urls it should be fixed after this pr lands https://github.com/mozilla-mobile/android-components/pull/6974 and the new ac version with it gets merged into Fenix.

**Comment by Amejia481** [comment]
Now we have support for blob URLs. QA please help us to verify if this website is working as expected.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 5/18 with Google Pixel 4 XL (10).
Note that I was able to download and open the security codes without problems.
