### ISSUE TITLE
[Bug] Browser crashes when playing video on Samsung with Webrender enabled

### ISSUE THREAD

**Issue by Augures01** [mozilla-mobile/fenix#10655]
## Steps to reproduce
1. Set gfx.webrender.all to true and restart browser
1. Open https://dtf.ru/new
1. Find any embedded youtube video
1. Start playing video
1. Crash
If browser not crashed, scroll for another youtube video or refresh page and try again

about:crashes leads me to this page:
https://crash-stats.mozilla.org/report/index/0ae9329c-13c1-4ae7-8f39-199730200514

### Expected behavior
Video played without crashes

### Actual behavior
Browser crashed

### Device information
* Android device: Samsung S6 Edge / Android 7.0 (Exynos 7420 / Mali-T760)
* Fenix version: All Fenix versions affected

**Comment by ekager** [comment]
Filed with WR team: https://bugzilla.mozilla.org/show_bug.cgi?id=1638593

**Comment by kvark** [comment]
@Augures01 does it also crash for other sites, like youtube? or only dtf.ru?

**Comment by Augures01** [comment]
@kvark 
I provide "dtf.ru/new" as fastest way to 100% reproduce this type of crash, because no registration required
It won't crash, when you opens full post on DTF with YouTube video, but if you preview video on "dtf.ru/new" it crashes

I also can 100% reproduce this with mobile version of Dropbox site, when you opens Folder History
Or 100% crash when scrolling [NSFW, registration required] f95zone.to/latest/

**Comment by jamienicol** [comment]
Hi @Augures01 , are you still experiencing this issue?

If so, would you be able to capture a logcat of your device while the crash occurs and attach it to this bug? Thanks.

**Comment by Augures01** [comment]
@jamienicol 
Seems like I can't reproduce crash with youtube embedded videos on dtf.ru/new and with Dropbox folder history https://github.com/mozilla-mobile/fenix/issues/10655#issuecomment-631955863
Or it's now not 100% reproducible and need more tries to crash

Not on the first try as before, but I still can reproduce crash with f95zone.to/latest
https://crash-stats.mozilla.org/report/index/789f5d81-e39e-4ea6-869d-0381a0201211

Logcat (crash starts at line 4053):
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/5680320/logcat.txt)

**Comment by oatastemur** [comment]
As I commented in #17612 this seems to be the default now across all Fenix browsers. Forcing gfx.webrender.force-disabled resolves the issue for me, but that's not an option except on Beta/Nightly builds.

**Comment by jamienicol** [comment]
Hi @Augures01. Sorry this took so long to track down the problem but it should now be fixed in the latest Nightly release, and in an upcoming beta and stable release. Please let us know if you still see this crash

**Comment by kbrosnan** [comment]
Fixed by upstream

**Comment by sflorean** [comment]
Verified as fixed on Nightly 5/7 with Samsung Note 10 (Android 11).
