### ISSUE TITLE
[Bug] maxlength in input field is not checked while typing

### ISSUE THREAD

**Issue by profi248** [mozilla-mobile/fenix#10654]
## Steps to reproduce
* select an input field with maxlength attribute
* type characters over the maxlength limit

### Expected behavior
* user is prevented from typing more characters than the maxlength limit
    1. Actual behavior
* user is able to type over the limit and the string is then truncated to the correct length when field loses focus
    1. Device information
* Android device: Xiaomi Mi A1, Android 10
* Fenix version: 
Nightly 200513 06:01 (Build #21340610)
41.0.20200512130104, 7b7310d14
GV: 78.0a1-20200511094328
AS: 0.58.2

**Comment by ekager** [comment]
Just to confirm - you're talking about an input field in web content? Is there an easy test site to use to confirm this you could share?

**Comment by kostaldavid8** [comment]
Yes, about <input> in website with maxlength attribute.
This is a little site where you can test it: https://kostaldavid8.github.io/firefox-test/input.html

**Comment by softvision-miralobontiu** [comment]
Hi @profi248 
The site provided above is displaying a 404 error. Could you help us with a different example so we can confirm the issue?
Thanks!

**Comment by profi248** [comment]
oops, sorry, the link is fixed now
