### ISSUE TITLE
FNX-4448 ⁃ [Bug] Context menu is not triggered when long pressing the about:support page

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#10653]
## Steps to reproduce
1. Navigate to `about:support` page.
1. Long press the page in order to select/copy text.
1. Observe behavior.

### Expected behavior
The context menu is displayed and text can be selected/copied/shared.

### Actual behavior
The context menu is not triggered, thus text can't be selected/copied/shared.

### Device information
* Android device: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density)
* Fenix version: Firefox Preview Nightly 200513 (:lizard: 78.0a1-20200511094328)

### Notes:
1. The issue is not reproducible on Firefox Release 68.8.0
1. Screenshot attached.

![image](https://user-images.githubusercontent.com/12184325/81946055-8e074500-9607-11ea-939c-4733d63c2d07.png)

**Comment by ekager** [comment]
Filed with GV as https://bugzilla.mozilla.org/show_bug.cgi?id=1638594

**Comment by ekager** [comment]
Looks like a fix landed for this in GV

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200625-093801](https://user-images.githubusercontent.com/51314259/85668985-09a8e700-b6c8-11ea-9429-c930b20b35a2.gif)
