### ISSUE TITLE
FNX2-13229 ⁃ [Bug][a11y] Suggestions for "Appearance" menu - Reader mode

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#10658]
## Steps to reproduce
1. Go to a site with a lot of content (e.g.wikipedia).
1. Enable "Reader view" from the main menu.
1. Open the "Appearance" menu. 
1. Scan the menu.

### Expected behavior
There are no suggestions to make any changes.

### Actual behavior
Suggestions are made to make the item's height from 19dp for "-" and "+" to 48dp.
Suggestions are made to make the item's height from 40x19dp for "Serif" and "Sans Serif" to 48dp.

### Device information
* Android device: Samsung Galaxy Note 10 (Android 10)
* Fenix version: 76.0.0-beta.1, Nightly 5/14.

![Screenshot](https://user-images.githubusercontent.com/58466444/81957358-20faac00-9615-11ea-99e6-454a0afcd82e.jpg)UNITO-UNDERSCORE!20200514-185814!UNITO-UNDERSCORE!Accessibility Scanner!

**Comment by mcarare** [comment]
Can QA please recheck this? It seems to me that the suggestions are made for the toolbar and for website content.
Try testing with toolbar on top and with no links in the website behind the Appearance menu. TY!

**Comment by sflorean** [comment]
Tested again following the suggestions from the comment above, and the issue isn't reproducible. I will close this based on the testing results.

**Comment by mcarare** [comment]
Closing as per https://github.com/mozilla-mobile/fenix/issues/10658#issuecomment-663377346.
