### ISSUE TITLE
FNX-4771 ⁃ Videos don't show up

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#1066]
## Steps to reproduce
Video on the following sites don't show up https://www.vuemastery.com/courses/intro-to-vue-js/vue-instance, https://www.ableton.com/en/blog/juana-molina-sketches-songs/ or https://www.theatlantic.com/video/index/584962/bulgaria-altimir/ 

### Expected behavior
I can see and play the videos

### Actual behavior
Videos don't show up, probably because of Tracking Protection

### Device information
* Android device: ?
* Fenix version: 1.0.1912

**Comment by kbrosnan** [comment]
Disabling tracking protection in reference-browser allows the videos to load. Enabling tracking protection reproduces the behavior mentioned above.

**Comment by vesta0** [comment]
Will be addressed as part of Tracking Protection Epic
