### ISSUE TITLE
Log send tab errors to Sentry

### ISSUE THREAD

**Issue by jdragojevic** [mozilla-mobile/fenix#10662]
### Why/User Benefit/User Problem
Similar to iOS: https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-v250/?query=is%3Aunresolved+send_tab it would be helpful to have some insight on when Send tab errors are encountered in Fenix

### What/Requirements
Log errors that prevent a tab from being received by Fenix

### Acceptance Criteria (how do I know when I’m done?)
Errors are logged to Sentry.

**Comment by ValentinTimisica** [comment]
@jdragojevic some of us don't have access to that link. Can you please give us more info to understand how this is used in iOS?

**Comment by jdragojevic** [comment]
![image](https://user-images.githubusercontent.com/299270/83037883-5090b780-a00a-11ea-8f10-5365c3128c1b.png)

Here's a screenshot, @garvankeeley can give access or more details for what they are sending.

**Comment by liuche** [comment]
Do these rust errors need to go into AC? RustLog landed in master, @ekager to ask @grigoryk about how to do this, and size.

**Comment by liuche** [comment]
I will follow up with the different people mentioned here to cover what and when these errors happen.

**Comment by liuche** [comment]
In iOS, this is the file where these Sync events are logged: https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Extensions/NotificationService/NotificationService.swift#L144

and we'll want to replicate any messages in that file that are sent with `Sentry.shared.send`

**Comment by Mugurell** [comment]
From what I see we only get a boolean for if the "send tab" operation succeeded or not without anyway of knowing the reason of a fail.

I filed https://github.com/mozilla-mobile/android-components/issues/7725 for AC to expose more data from AS which handles the actual sharing of the tab.

In the meantime maybe we could add a Glean metric to track successful / failed send tab operations? @liuche @jdragojevic

**Comment by jdragojevic** [comment]
@Mugurell - thank you for looking into this.  We've recently done work to add more metrics around send tab in Fenix - currently it's in review (https://github.com/mozilla-mobile/android-components/pull/7618) / data review (https://bugzilla.mozilla.org/show_bug.cgi?id=1652902).

**Comment by Mugurell** [comment]
@jdragojevic Thank you!
I see that ticket only intends to add telemetry for when a tab is sent or received.

It would be great if FXA would also log errors and not leave this to clients.
Should I pass if logging errors is possible in FXA with Mark / Grisha?

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

[~eoger@mozilla.com] - may also be able to provide some info on the ideal way to log errors.

**Comment by Mugurell** [comment]
The AC work for this landed.
There are still https://github.com/mozilla-mobile/android-components/issues/8877 and https://github.com/mozilla-mobile/fenix/issues/16339 but with those patches applied locally I see the the reporting working as expected.
Closing as such.
