### ISSUE TITLE
FNX-4588 ⁃ Evaluate effects of new tabs tray on migration

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#10666]
This is a note for us to check that the work on the new tabs tray does not affect migrations.

* Ensure there is no session data lost.
* (Expected) Thumbnails from Fennec are lost.

**Comment by jonalmeida** [comment]
I did some quick tests to make sure a migration isn't affected by the tabs tray. The open tabs in Fennec were still there in Fenix (after enabling the tabs tray from the secret menu).

**Comment by ebalazs-sv** [comment]
I had tested this issue on Nightly Migration Build 2015743089 from 5/29 with Motorola Moto G6 (Android 8) and the opened tabs are kept when enabling or disabling "Use New Tab Tray" setting.

**Comment by st3fan** [comment]
I think we want to test this again when the new tab tray is enabled by default.

**Comment by st3fan** [comment]
Moving this to done since these tests are already part of the test plan and will be run when a build appears where the new tabs tray is enabled.
