### ISSUE TITLE
FNX-4459 ⁃ [Bug] YouTube previews are still shown if images are off

### ISSUE THREAD

**Issue by jidanni** [mozilla-mobile/fenix#10669]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1597033. 

Steps to reproduce:

Turn off images. Then search Google for something.

Actual results:

If some of the Google results have YouTube previews in them you'll see those results' animations still running.

Expected results:

So that's still wasting our data with images.

Note, I have not visited YouTube. I am just talking about the YouTube preview scene within Google search results.

**Comment by ekager** [comment]
Hi @jidanni thanks for filing. Could you be more specific about what you mean by "turn off images"? Is this a Fenix setting you're talking about?

**Comment by jidanni** [comment]
OK it is already fixed!
