### ISSUE TITLE
FNX-4462 ⁃ [Bug] Sign in to see synced bookmarks inflated too many times

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#10674]
### Prerequisites
Don't be logged in into an Fxa account.

### Steps to reproduce
* From Home menu go to `Bookmarks`->`Desktop Bookmarks`
* Press Recents apps button and then select Fenix (you can do this multiple times).

### Expected behavior
* Only one `Sign in to see synced bookmarks` button should appear on the screen.

### Actual behavior
* `Sign in to see synced bookmarks` appears multiple times on the screen.

### Device information
* Android device: Samsung Galaxy Note 10 (Android 10)
* Fenix version: latest from master

### Additional info
* [Video](https://drive.google.com/file/d/1mtS0vnyLLwYYyd_97qBaN5NzIk8J5wGx/view?usp=sharing)

**Comment by ValentinTimisica** [comment]
Reopening this for QA

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fenix Nightly Build 21500607 from 5/29 with Motorola Moto G6 (Android 8) and Pixel 2 (Android 9).

Only one *Sign in to see synced bookmarks* button appear on the screen, when tapping the Recent apps device button and then selecting Fenix.

I will remove the qa:needed label.
