### ISSUE TITLE
FNX-4465 ⁃ [Bug] Application crashes when navigating to `about:processes`

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#10678]
## Steps to reproduce
1. Navigate to `about:processes`.
1. Observe behavior.

### Expected behavior
"Processes Manager" page is displayed.

### Actual behavior
Application crashes and needs to be restarted,

### Device information
* Android device: Firefox Preview Nightly 200514 (:lizard: 78.0a1-20200513094918), Firefox Preview Nightly 200515 (:lizard: 78.0a1-20200513094918), 
* Fenix version: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density), Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density)

### Note
1. Gif attached.
![AppCrashProcesses](https://user-images.githubusercontent.com/12184325/82048624-a89bf580-96bd-11ea-8840-7f3d5b7ef266.gif)
1. about:crashes:
![image](https://user-images.githubusercontent.com/12184325/82048702-c4070080-96bd-11ea-9670-fadfe2dd11c5.png)
1. Reproducible: 10/10

**Comment by kbrosnan** [comment]
This no longer crashes on Nightly using Galaxy S6 and a Pixel 3.

**Comment by softvision-oana-arbuzov** [comment]
I can confirm this, it no longer crashes.
![image](https://user-images.githubusercontent.com/12184325/89040775-f505e180-d34c-11ea-9435-26112f5f1988.png)

**Tested with:**
Browser / Version: Firefox Nightly 200729 (🦎 80.0a1-20200727095125)
Operating System: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density), Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density)
