### ISSUE TITLE
FNX-4464 ⁃ [Bug] Extensions randomly stop working.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10676]
## Steps to reproduce
1. It happens randomly
1. If I find the exact steps to reproduce I'll update the issue.

### Expected behavior
Extensions shouldn't Stop working randomly. Extensions like uBlock Origin and Privacy Badger stop working entirely unless I restart the browser.

### Actual behavior
Extensions stop working randomly

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: 76.0.0-beta.2 (Build #2015740131)

**Comment by SS1113** [comment]
I observed a lot but I cannot seem to find the exact steps to reproduce; it does really happen randomly but I can confirm that since I have installed the `76.0.0-beta.2 (Build #2015740131)` I have experienced this at least 6 to 7 times and after a browser restart the extensions start working again.

**Comment by SS1113** [comment]
I want say that I have not experienced this bug in recent times with `77.0.0-beta.2` and `Nightly 200609 06:00` and with recent builds. Tested on Motorola One Power, Android 10.

**Comment by Amejia481** [comment]
@SS1113  If you encounter the issue please feel free to re-open
