### ISSUE TITLE
[Bug] Top dynamic toolbar should use a custom behavior

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#10686]
When the dynamic toolbar is set at the bottom we use a [BrowserToolbarBottomBehavior](https://github.com/mozilla-mobile/android-components/blob/f8891561284ad13f05a4ea7900174c08d79a0d08/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt) from a-c which knows to ignore zoom gestures and when to ignore scroll gestures also.

When the dynamic toolbar is set at the top we are using one-off default flags to control scrolling without accounting for page structure or user gestures.

Like this (toolbar is animated by inner scrolls, zoom gestures, etc) https://github.com/mozilla-mobile/fenix/issues/2278#issuecomment-629077440

Or like this (toolbar animations prevent webpage panning)
![fenixTopToolbar](https://user-images.githubusercontent.com/11428869/82069226-ac3e7500-96db-11ea-976d-6fd995d66aec.gif)

**Comment by Mugurell** [comment]
Asking @sblatz about the best approach here since I see he worked recently here.
I think the best approach would be to use a similar "BrowserToolbar`Top`Behavior" but it seems like there might be more changes needed.

**Comment by Mugurell** [comment]
Touched on possible solutions with Sawyer.
It's probable that we haven't gone with a similar layoutBehavior for the top toolbar because setDynamicToolbarMaxHeight only clips from the bottom, not the top.
So this warrants more investigations about what the best solution would be.

**Comment by Mugurell** [comment]
Investigated what would be needed and left a comment on AC - https://github.com/mozilla-mobile/android-components/issues/7718#issuecomment-703614597

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 2/9 and Beta 86.0.0-beta.3 from 2/8 with Pixel 2 (Android 9).
I will close this issue and remove the qa:needed label.
