### ISSUE TITLE
[Tab Tray] Show longer titles (on 2 rows)..., to match current Fenix Home Screen

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#10683]
## Steps to reproduce
Activate new Tab Tray secret setting
Open some sites to feed the Tab Tray :grinning:
Move to Tab Tray

### Expected behavior
Titles displayed for sites should be long enough to be meaningful (note that I don't rely on Site Previews where the expected information could not present/readable).
IMHO, the current Fenix Home Page as shown below shows a good example of what the information density should be:

* number of rows (2 rows for the title), space between rows
* font size & color (contrast) differences between titles and URLs.

![image](https://user-images.githubusercontent.com/218971/82315731-06855180-99cc-11ea-9b95-f2144573f8d8.png)

### Actual behavior
Titles displayed for sites are truncated on 1 row each, therefore they are not meaningful at all, as you can see below (same sites as above, in reverse order)

![image](https://user-images.githubusercontent.com/218971/82315786-20bf2f80-99cc-11ea-8266-541e2c99cb23.png)

### Device information
* Android device: 9
* Fenix version: build #2015740403

Thank you and pardon my French :wink:

**Comment by brampitoyo** [comment]
@topotropic Do you have any comment or opinion around longer titles on tab names?

For reference, here are examples of other browsers that display the tab’s page name and URLs in a list view:

**Samsung Internet**
<img width="360" src="https://user-images.githubusercontent.com/51007/82271173-29633600-99cb-11ea-8e53-7b5502a582b5.png">

**UC Mini**
<img width="360" src="https://user-images.githubusercontent.com/51007/82271178-2e27ea00-99cb-11ea-913d-a3e1002111bc.png">

**Yandex Browser**
<img width="360" src="https://user-images.githubusercontent.com/51007/82271344-9d054300-99cb-11ea-9dd4-4c344d75d639.png">

**Comment by klint** [comment]
For the sake of good comparison, I have updated the initial screenshots to match the sites on the other browsers's examples. 
(I hope this help clarify how useful the 3 lines in the current Fenix home page can be... Screenshot vs favicon debate put aside, of course). Thanks

**Comment by yoasif** [comment]
Not really sure about three lines, but two lines is definitely an improvement over the current tab tray.

**Comment by klint** [comment]
Sorry I meant 3 lines including the url itself 😉

**Comment by klint** [comment]
Back on this issue to stress the need of solving it, now that we can have a good experience of site previews in the nightly builds :)
As you can see from the screenshot belows, taken in both light and dark modes, the site previews are not sufficient on their own to easily identify tabs (particularly with numerous tabs in the list. I have 99+).
![image](https://user-images.githubusercontent.com/218971/84999870-ff2fa000-b151-11ea-931a-297148fbd14e.png)

**Comment by AmyYLee** [comment]
@topotropic for follow-up

**Comment by AmyYLee** [comment]
@betsymi @topotropic for follow-up

**Comment by klint** [comment]
Following the PR for issue #11918 moved to nightly recently, it seems that the screenshots shown in the Tab Tray are now reflecting the current screen view of the page when the Tab Tray button was pressed, instead of the top of the page itself (maybe I'm wrong, but I think that before, the tops of pages would be shown in the Tab Tray). Which makes the pages less recognizable imho (the proeminent title on the top the page being absent from the picture).
That is one more reason for displaying a longer and more explicit title :).
Note that this has also been requested on some comments on Google Play.

**Comment by cadeyrn** [comment]
@topotropic Is it really necessary to have such a large gap between title and URL if the title has only one line? As I first saw the screenshot in the pull request for this issue I thought it's a bug in the implementation. I would expect that the spacing between the title and the URL doesn't depened on the number of lines for the title. The whole should be vertically centered so that it always look good. What do you think?

**Comment by topotropic** [comment]
> @topotropic Is it really necessary to have such a large gap between title and URL if the title has only one line? As I first saw the screenshot in the pull request for this issue I thought it's a bug in the implementation. I would expect that the spacing between the title and the URL doesn't depened on the number of lines for the title. The whole should be vertically centered so that it always looks good. What do you think?

Thanks for your feedback. The assumption is that most sites have longer titles and the 1-liner will be a rare case (I'll keep an eye on that). And another point is to keep things starting in the same place for better scan-ability, so all titles have the same top margin, instead of aligning them to the URL.

**Comment by topotropic** [comment]
Ok, I tested it on various screen sizes and realized quickly that the assumption that most titles will span over two lines doesn't hold true. Thanks for the pointer @cadeyrn 

And apologies to this oversight @amkcpu – I'd appreciate it if you could update the implemented design to match the following (so center title and domain with 4dp spacing between them):

<img width="411" alt="image" src="https://user-images.githubusercontent.com/353960/96179604-6824fa00-0f31-11eb-97e7-0045fad16b50.png">

Thank you!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201019`** build using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Screenshot
![rsz_3screenshot_20201019-115554](https://user-images.githubusercontent.com/51314259/96423983-c0dee600-1202-11eb-88b0-16bd17da6bd4.png)
