### ISSUE TITLE
FNX-4469 ⁃ [Bug] alimentarito.revelup.com never finished loading

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#10682]
## Steps to reproduce
Go to https://alimentarito.revelup.com/weborder/?establishment=1#index

### Expected behavior
The side loads as it does in Firefox desktop

### Actual behavior
The site never finishes loading even with tracking protection off

### Device information
Nightly 200515 06:00 (Build #21360611)
42.0.20200514130134, 315591642
GV: 78.0a1-20200513094918
AS: 0.58.2

**Comment by ekager** [comment]
I am able to sucessfully load this page on Nightly + master. I have no add-ons enabled. Is there anything else you've changed in settings or enabled that could impact this load?

**Comment by Amejia481** [comment]
You are right, it looks like was an issue caused by add-on we can close this issue.
