### ISSUE TITLE
FNX-4773 ⁃ As a user I would like to quickly copy a URL from the URL bar

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1068]
## Dependencies (Added by PM and Eng)
* Needs UX Flow. (We could immediately copy what we have from Focus)

## Next Steps 
* Immediate task: Convert user story into an Epic, and link it back to the Meta  (PM)
* Immediate task: Estimate/size user story with points (during backlog grooming)
* User stories need to be assigned to a milestone, e.g backlog, or move into sprint (PM)
* Engineers need to breakdown the user story, size all the individual tasks, and link the tasks to this user story (Done by Eng on Sprint Planning day)

### Acceptance Criteria (Added by PM)
* I can quickly copy a URL form the URL bar

**Comment by boek** [comment]
We can now long click the URL bar to copy the URL to the clipboard!

**Comment by bsurd** [comment]
There are no other issues and copying the URL works as intended.
