### ISSUE TITLE
FNX3-14077 ⁃ [Bug] Select Web apps show blank screen

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#10689]
* [ ] GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1641715

## Steps to reproduce
Launch Firefox Nightly > Navigate to https://crypt.ee/home/ > Install Cryptee when "Add to Homescreen" is replaced with "Install" button in menu > quit Firefox > from your device launcher, open Cryptee.

Two more web apps which seem to have the same (identical) problem are https://newsfeeder.esstudio.site/ and  https://beta-lyricfy.surge.sh/lyrics - obviously just replace Cryptee with these to reproduce. 

Note: this is most likely related to the addons installed. When firefox is fresh out'ta the box, the web app launchs just fine. Installing Ublock or any other addon causes the issue, and the problem persists when the addons are disabled (not uninstalled)

Also this is only for select sites, and I'm no developer but all of those which don't work absolutely must have javascript enabled to run. Sites which work normally are https://bibliogram.art/ and https://nitter.net/
Lyricfy and Cryptee are fully installable while the others are not, in case that's important.

### Expected behavior
The web app loads normally

### Actual behavior
The screen stays blank.

### Device information
* Android device: Samsung Galaxy S8+ (SM-G955F)
* Fenix version: Nightly 200515 07:21

**Comment by jonalmeida** [comment]
When testing this with airhorner.com the PWA loads correctly when the main browser app is still in recent apps launcher. Swipe it away, and re-launch the PWA and it no longer works. Re-open the browser, and the PWA opens again.

Looking at the logs, I see GV is showing the URL as null (might not be related):
```
GeckoSession  D  handleMessage GeckoView:ProgressChanged uri=null
              D  handleMessage GeckoView:PageStart uri=https://airhorner.com/?homescreen=1
              D  handleMessage GeckoView:ProgressChanged uri=null
              D  handleMessage GeckoView:PageStop uri=null
              D  handleMessage GeckoView:SecurityChanged uri=null
              D  handleMessage GeckoView:ProgressChanged uri=null
              D  handleMessage GeckoView:PageStart uri=https://airhorner.com/?homescreen=1
```

**Comment by astarq** [comment]
Same here, I forgot to mention it

**Comment by sv-ohorvath** [comment]
I have a logcat if it helps: 
[log.txt](https://github.com/mozilla-mobile/fenix/files/4695110/log.txt)

**Comment by NotWoods** [comment]
So far I've narrowed down that a change from GeckoView nightly [`"77.0.20200428100141"`](https://maven.mozilla.org/maven2/org/mozilla/geckoview/geckoview-nightly/77.0.20200428100141/geckoview-nightly-77.0.20200428100141.pom) to [`"77.0.20200429095105"`](https://maven.mozilla.org/maven2/org/mozilla/geckoview/geckoview-nightly/77.0.20200429095105/geckoview-nightly-77.0.20200429095105.pom) caused the issue.

Steps to get to the same point:
There are two commits in the AC repo immediately after each other from ~late April:
```
cb03ee8935d40ba22d85848e5ee0227794c7693e
49a09f9f270ccaf4f03773b61f4c64b7b43dc4b5 
```

`ch03ee` works, `49a09f` does not. Running Sample Browser, swiping it out of recents, then launching a PWA gets the correct result in the older commit but just a white screen in the newer commit.

```
git checkout cb03ee8935d40ba22d85848e5ee0227794c7693e # works after running
git checkout 49a09f9f270ccaf4f03773b61f4c64b7b43dc4b5 -- buildSrc/src/main/java/Gecko.kt # breaks after running
```

**Comment by NotWoods** [comment]
Filed BZ-1641715

**Comment by liuche** [comment]
Important, but not for releaes.

**Comment by igalic** [comment]
i don't understand why each PWA isn't a separate sandbox
chrome even makes each PWA a separate application that is separate from the "main" chrome app (or so i hear)

**Comment by Dunexus** [comment]
Chrome creates WebApk to have each PWA as a separate application. They said they will make WebAPK APIs available for other browser years ago but no update ever since.
However, launching PWA in separate container (which allow some sandboxing) is in fenix backlog, see https://github.com/mozilla-mobile/fenix/issues/776

**Comment by astarq** [comment]
Fixed for me, Nightly 200716 18:06 !!
Still present on Beta v79 beta 5
Tested on Android 10

Could someone else verify this?

**Comment by sv-ohorvath** [comment]
Verified with crypt.ee/home and twitter web apps that this is was fixed on Nightly 8/4. And yes, still reproducing on 79.0.2 but surely it will land in the next releases.
