### ISSUE TITLE
FNX-4478 ⁃ [Bug] IllegalArgumentException  Receiver not registered: mozilla.components.feature.downloads.AbstractFetchDownloadService

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#10693]
[Sentry report link](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8381725/?query=is%3Aunresolved%20AbstractFetchDownloadService)

Looks like a crash that has started around 5/10 in Nightly. 

```
RuntimeException

Unable to stop service org.mozilla.fenix.downloads.DownloadService@794bb04: java.lang.IllegalArgumentException: Receiver not registered: 
mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@46708ed
```

```
IllegalArgumentException

Receiver not registered: 
mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@46708ed
```

* Android device: ?
* Fenix version: Nightly 5/10+

**Comment by ekager** [comment]
cc @Amejia481 this seems related to https://github.com/mozilla-mobile/android-components/pull/6902

**Comment by Amejia481** [comment]
This will be addressed here https://github.com/mozilla-mobile/android-components/pull/6954 :)

**Comment by Amejia481** [comment]
This should be fixed on nightly :)

**Comment by sv-ohorvath** [comment]
@Amejia481 Is there a chance you have any STR for this crash?

**Comment by Amejia481** [comment]
Sorry about that.

**STR**:
1. Download a file.
2. Kill the app using the task manager
3. Open the app and download another file.

Before the patch it used to crash in step 3.

**Comment by softvision-miralobontiu** [comment]
We weren't able to reproduce the crash on these last past days with devices having Android versions 5.1, 7.1.1, and 10.
Following the STR from the comment above, I've retested with the latest Nightly build from 6/12 with GV 79.0a1, AS: 60.0.0, using OnePlus 5T (Android 9), and HTC 10 (Android 8), no crashes.
I'll close this issue.
