### ISSUE TITLE
FNX-4775 ⁃ [Bug] Intermittently Failing UI Tests testDownloadPrompt, MediaNotificationTest

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#10708]
I think this is my fault.

I updated some behavior in #10358 to hide the engineView until the first content paint has happened. I did add a line to update UI testing - `verifyPageContent` now should wait til `engineView` is there https://github.com/mozilla-mobile/fenix/pull/10358/files#diff-4814a8099f84520b39319f3367e379d4R76
but now `testDownloadPrompt`, `videoPlaybackSystemNotificationTest`, `tabMediaControlButtonTest` fail intermittently. 

Did I update this wrong? Is there a better way to wait the engineView is visible?

**Comment by ekager** [comment]
Cc @AaronMT is there something else I should have done here?

**Comment by ekager** [comment]
Video here is weird. Looks like the page content does appear and then it time outs trying to verify the page content
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6337539131377699799/executions/bs.def8e0fe331f5c25/videos

**Comment by ekager** [comment]
Example MediaNotificationTest failures https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8466506477583166082/executions/bs.a2feb897991f93e7/test-cases

**Comment by AaronMT** [comment]
Could it be because these pages are loading so fast from local server that there's a race?

**Comment by ekager** [comment]
Reverted #10358 for now
