### ISSUE TITLE
FNX-4486 ⁃ [Bug]  "Open Tabs" in Delete browsing data should use sentence case

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10706]
## Steps to reproduce
1. Open Fenix
1. Go to settings
1. Go to either "Delete browsing data" or "Delete browsing data on quit"

### Expected behavior
I see "Open tabs" as the label for the first checkbox.

This is part of Android's style guide and most of the rest of the app uses this convention: https://developers.google.com/style/capitalization

### Actual behavior
I see "Open Tabs".

### Device information
* Android device: pixel 2
* Fenix version: latest nightly

**Comment by brampitoyo** [comment]
Agreed, @yoasif. Let’s fix this issue.

Since it’s a really minor issue, I won’t formally assign @betsymi to this issue. She’s mentioned here to inform and acknowledge.

**Comment by Diana-Rus** [comment]
Hi, issue is fixed, checked with Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7), no more capitalization of the second word 😊.
 - Verified "Delete browsing data"
 - Verified "Delete browsing data on quit"

Google Pixel 3 XL (Android 9)-"Delete browsing data"- Open tabs
![Screenshot_20200527-190236_Firefox Nightly](https://user-images.githubusercontent.com/49859863/83044759-4cd25480-a04d-11ea-9ae6-cfe2957f7cf1.jpg)

Google Pixel 3 XL (Android 9)-"Delete browsing data on quit"- Open tabs
![Screenshot_20200527-190251_Firefox Nightly](https://user-images.githubusercontent.com/49859863/83044840-670c3280-a04d-11ea-9f1e-8d1573893292.jpg)

Note:
- With this might have come a regression, when changing browser language in a different one than English, "Open tabs" is not translated. I'll make a you new ticket for it an relate it to this one.
