### ISSUE TITLE
Add more information to Download Notification

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [mozilla-mobile/fenix#10703]
### Description
When files are downloaded in Firefox Android, there are no details about the download, like in Firefox Desktop.

It lacks ETA, download speed, how much were just downloaded and progress status.

In Firefox Preview, you should add exactly everything as you would in Firefox Desktop (default setting).

**Here for Firefox Preview download manager + Download Notification under Android:**

* pause/continue/cancel
* download speed
* ETA
* progress status (e.g in percent or bar)
* how much were just downloaded (e.g 19.78 MB from 30.00 MB)

### Version
Android 9

Firefox Preview 5.0.0
https://github.com/mozilla-mobile/fenix/releases/tag/v5.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-912)

**Comment by ekager** [comment]
Download Manager is tracked in #349 
But we can use this issue for more information in the notification

**Comment by lo9-u** [comment]
Here is an example of how it might look for the Firefox Android download notification.

![1](https://user-images.githubusercontent.com/70044005/92256178-ae6b5000-eed3-11ea-9c69-f0ae6353390a.jpg)
![2](https://user-images.githubusercontent.com/70044005/92256192-b2976d80-eed3-11ea-835e-83c560c53080.jpg)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812813

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
