### ISSUE TITLE
[Bug] Closing tab scrolls top list to top

### ISSUE THREAD

**Issue by bytesnz** [mozilla-mobile/fenix#10700]
## Steps to reproduce
1. Go to currently open tabs list
1. Scroll down
1. Close a tab

### Expected behavior
Tabs below closed tab shift up to fill gap

### Actual behavior
Tabs list goes back to the top

### Device information
* Android device: 6.0.1
* Fenix version: 75.0.0-beta.6 

![firefox](https://user-images.githubusercontent.com/1755886/82121480-45759600-9785-11ea-93cd-e5e124d75c5c.gif)

**Comment by ekager** [comment]
This seems to only happen on older API devices. (cannot reproduce on device running Android 10 but can on API 22 emulator)

**Comment by Poopooracoocoo** [comment]
can this still be repro'd?

**Comment by bytesnz** [comment]
> can this still be repro'd?

No. Seems to be fixed now. Is looking very nice.
