### ISSUE TITLE
FNX-4485 ⁃ [Bug] "Automatic Font Sizing" copy in Accessibility settings should use sentence case

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10705]
## Steps to reproduce
1. Go to Settings
1. Tap Accessibility

### Expected behavior
I see "Automatic font sizing" as the label for the first option.

### Actual behavior
I see "Automatic Font Sizing".

### Device information
* Android device: pixel 2
* Fenix version: latest nightly

**Comment by yoasif** [comment]
FYI, this is part of Android's style guide and most of the rest of the app uses this convention: https://developers.google.com/style/capitalization

**Comment by brampitoyo** [comment]
@yoasif I also agree with your string change. CC @betsymi.

**Comment by mcarare** [comment]
This should be fixed along with https://github.com/mozilla-mobile/fenix/issues/10705.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 5/29 with:
- Google Pixel (Android 10),
- Sony Xperia Z5 Premium (Android 7.1.1),
- OnePlus 5T (Android 9, and
- Samsung Galaxy Tab A6 (Android 5.1.1).
