### ISSUE TITLE
FNX-4484 ⁃ Add change the download path

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [mozilla-mobile/fenix#10704]
### Description
In Firefox Preview is not available as in Firefox Desktop.  The possibility to change the download path.

Add this in Firefox Preview.  Create a new category under Settings e.g. Settings -> Downloads

* Download Path
* Always ask me where to save files

### Version
Android 9

Firefox Preview 5.0.0
https://github.com/mozilla-mobile/fenix/releases/tag/v5.0.0

**Comment by cadeyrn** [comment]
Duplicate of #5764.

**Comment by ekager** [comment]
Closing for #5764
