### ISSUE TITLE
FNX-4481 ⁃ [Bug] Top (most recent) tab often gets lost

### ISSUE THREAD

**Issue by wlevine** [mozilla-mobile/fenix#10701]
## Steps to reproduce
1. Keep several tabs open
1. Use your phone like normal (switch back and forth between different apps, open links from other apps in firefox)

### Expected behavior
Firefox should always remember all tabs

### Actual behavior
Sometimes when you return to Firefox, the top tab has been forgotten and is replaced with a blank (about:empty) tab.

This never happened to me with Fennec, but happens quite frequently now with Fenix.

I suspect what is happening is that sometimes the app starts loading the tab, but is interrupted/killed/backgrounded before it can finish loading and then forgets what the tab was.

I am sorry I cannot find a way to reproduce this 100%, but it happens to me so often, I suspect that other people are seeing the same issue

### Device information
* Android device: Sony Xperia X Compact
* Fenix version: 200515

**Comment by ekager** [comment]
Closing for #5478
