### ISSUE TITLE
FNX2-13242 ⁃ [Bug] Dynamic toolbar appears and disappears when scrolling in a textarea

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#10713]
This one is a bit in the papercut department :smile:

## Steps to reproduce
Try to submit a fenix issue from fenix (I.e., open https://github.com/mozilla-mobile/fenix/issues/new?assignees=&labels=%F0%9F%90%9E+bug&template=---bug-report.md&title=%5BBug%5D).

Focus the main textarea.

Scroll down and up _inside the textarea_.

### Expected behavior
Probably the toolbar shouldn't move when scrolling form controls?

### Actual behavior
The toolbar shows up / disappears / everything in between while I'm scrolling the textarea.

### Device information
* Android device: Galaxy A20
* Fenix version: Latest Nightly

**Comment by Mugurell** [comment]
Hello,

Normally the toolbar should not be animated for inner level scrolls.
As a general rule, only if the outer page is scrolling the toolbar should animate.
In this case, with text areas, when there is enough text for them to actually scroll the text indeed the toolbar should not be animated.
But if that text areas are empty, they have nothing to scroll so any up/down events are handled by the outer page and so the toolbar will be animated.
This is the scenario which I think you described
![InnerScrollsVsOutherScrolls](https://user-images.githubusercontent.com/11428869/87513223-09758900-c681-11ea-88a2-790ddec55608.gif)

If this is not the case, like for any UI issues a small video would help.

**Comment by emilio** [comment]
No, I'm pretty sure I was not hitting the textarea limits. But that being said as your video demonstrates this seems to have been fixed along the way.

**Comment by Mugurell** [comment]
Thanks for the update!
There are some quirks with Github indeed, but what I presented should be the expected behavior.
If you have not experienced this issues lately I think we can close this ticket.

**Comment by s-ankur** [comment]
Might be related to #11389

**Comment by Mugurell** [comment]
Thank you for your interest @s-ankur!
11389 being related to the top toolbar is a different issue than this though, as this was reported for the bottom toolbar and there different behaviors for the top / bottom toolbar.
With that being said 11389 is definitely something that should be fixed , I'll try looking into what's needed.

In the meantime, if this is not an issue anymore as per https://github.com/mozilla-mobile/fenix/issues/10713#issuecomment-658705389 I'll close this.

**Comment by Mugurell** [comment]
Closing as per https://github.com/mozilla-mobile/fenix/issues/10713#issuecomment-667820269
