### ISSUE TITLE
FNX-4489 ⁃ [Bug] Can't hit youtube comments button on latest nightly

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#10711]
## Steps to reproduce
Load https://m.youtube.com/watch?v=bGkdRcKKgm8 (for example). Scroll down, then try to hit the comments button to expand the comment section.

### Expected behavior
I see the comments.

### Actual behavior
Nothing. I think this has to do with the dynamic toolbar. This is a very recent regression.

### Device information
* Android device: Samsung Galaxy A20
* Fenix version: Latest Nightly

**Comment by emilio** [comment]
Hmm, I can repro with the toolbar at the top as well.

**Comment by willdurand** [comment]
Same for me, with toolbar at the bottom and at the top. It looks like any button displayed at the very bottom of a page cannot be triggered.. It happens to me on the "insecure page" as well:

![Screenshot_20200517-114559_Firefox_Nightly](https://user-images.githubusercontent.com/217628/82141197-7f51a580-9834-11ea-820f-05a86069a718.png)

I tried to click the "accept" button and we can see that the button above changes its ui state instead (see the dotted rectangle), but I cannot accept the risk right now.

This behavior occurs with the toolbar at the top as well.

**Comment by emilio** [comment]
Seems like a dupe of https://github.com/mozilla-mobile/fenix/issues/10636.
