### ISSUE TITLE
FNX-4492 ⁃ [Bug] Links shared by fenix do not work with PowerTube or Navi, but work with other browsers

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10714]
## Steps to reproduce
Currently, when you share a link with fenix it is shared in the `[Title] [Link]`format. This means that apps which expect only links to be shared in the `[Link]` format (which chrome and many other browsers use) will not work with fenix. For example PowerTube (https://github.com/razar-dev/PowerTube) and Navi (https://github.com/TachibanaGeneralLaboratories/download-navi) do not work with fenix.

**Comment by ekager** [comment]
Closing for #10193
