### ISSUE TITLE
FNX-4495 ⁃ [Bug] Need to go back 2 times when reading news from google to return to the inicial list of google news home screen

### ISSUE THREAD

**Issue by Pixotas** [mozilla-mobile/fenix#10718]
## Steps to reproduce
I usually use google to read some news in my phone. I use Firefox Preview as external application to block ads. With this last version when I click to read one topic of the google news, when I go back It opens the homescreen of Firefox instead of returning to the list of news. So i need to go back twice to get the homescreen list news. (See the gif below)

### Expected behavior
Only go back 1 time to return to the google news list. Before this last bigger update It was fine.

### Device information
* Android device: Huawei P30 Pro - EMUI 9.1.0
* Fenix version: 5.0.0. (Build #21212137)
![Gif Problem](https://user-images.githubusercontent.com/63738804/82157039-fc057380-9876-11ea-9358-a12f3378b0d6.gif)

**Comment by ebalazs-sv** [comment]
This issue is verified as fixed on Nightly Build 200519 from 5/19, with the following devices:
- Google Pixel 3a (Android 10);
- Huawei Mate 20 Lite (Android 9);
- OnePlus A3 (Android 6.0.1);
I will remove the qa:needed. Thanks!
