### ISSUE TITLE
FNX3-14092 ⁃ Desktop mode icon

### ISSUE THREAD

**Issue by DoggoOfSpeed** [mozilla-mobile/fenix#1071]
### Why/User Benefit/User Problem
An icon makes it easier to understand what does an option do. Also looks nicer.

### What / Requirements
Just an icon (possibly from google)

### Acceptance Criteria (how do I know when I’m done?)
When it looks something like this:
![pitch](https://user-images.githubusercontent.com/28051112/54612402-91ce2480-4a61-11e9-935d-2191a4736e22.png)

**Comment by Vv2233Bb** [comment]
The icon can be found in google's open source libraries https://material.io/tools/icons/?icon=desktop_windows&style=outline

**Comment by Scripterr** [comment]
I'm sure mozilla have their own design language i.e. photon which is different from the Google's material design so it doesn't fit well with the other icons of the app and but they can create a new icon based on photon, but it would be good if there would be a desktop icon.

**Comment by bogas04** [comment]
It took me couple of days to realize Desktop Site option actually exists. Somehow the missing icon made me glance over it entirely.

**Comment by ekager** [comment]
@mozilla-mobile/ux did we want the photon deskop icon to be in the menu here?

**Comment by topotropic** [comment]
yes, let's do this

**Comment by NotWoods** [comment]
Desktop mode icon asset: `ic_desktop.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24"
        android:viewportHeight="24">
    <path android:fillColor="?primaryText"
          android:fillType="evenOdd"
          android:pathData="M4 6a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v11h1.5a0.5 0.5 0 0 1 0.5 0.5v1a0.5 0.5 0 0 1-0.5 0.5h-19a0.5 0.5 0 0 1-0.5-0.5v-1a0.5 0.5 0 0 1 0.5-0.5H4V6zm6 11v1h4v-1h-4zM6 7h12v9H6V7z" />
</vector>

```

**Comment by bogas04** [comment]
While icon is available, a UI component with a Switch and Icon is not.

https://github.com/mozilla-mobile/android-components/issues/3715

**Comment by ekager** [comment]
For QA: Please especially verify this on API 21-22 devices to make sure this new asset works there. Thanks!

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/1, both dark and light modes.
Devices verified:
Pixel 3 (Android 9)
Samsung Galaxy Tab A 6 (Android 5.1.1)
HTC Desire 820 (Android 6.0.1)
Mi 4i (Android 5.0.2)
Nexus 5 (Android 6.0.1)
