### ISSUE TITLE
[Bug] Dynamic toolbar gets stuck in an intermediate state on latest nightly

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#10712]
## Steps to reproduce
Scroll in most websites, including this very bug submission page.

### Expected behavior
The toolbar either shows or hides, or if it's supposed to be at this intermediate state, does so smoothly.

### Actual behavior
The toolbar jumps while scrolling instead of animating.

### Device information
* Android device: Galaxy A20
* Fenix version: Latest Nightly

**Comment by Mugurell** [comment]
Hello,
Does this still happen with the latest apps?
If so, can you please post a small video showcasing the issue?

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on the 11/17 Nightly build with Samsung Galaxy Tab S6 (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
@emilio could you please, retry? And even help us with a short video with the issue?

**Comment by emilio** [comment]
I haven't seen this in a while.
