### ISSUE TITLE
[Bug] SharedArrayBuffer no longer available in Nightly

### ISSUE THREAD

**Issue by philip-lamb** [mozilla-mobile/fenix#10722]
## Steps to reproduce
1. Execute `curl -I https://eden.net.nz/test/sab.html` and verify that the COOP & COEP headers are present and correct for SharedArrayBuffer instantiation.
1. Visit https://eden.net.nz/test/sab.html, which contains a single javascript attempt to instantiate a SharedArrayBuffer instance.

### Expected behavior
* SharedArrayBuffer can be instantiated.

### Actual behavior
* Instantiation fails.

### Device information
* Android device: HTC 10, Android v8.0, arm64-v8a
* Fenix version:
  * Nightly 200517 (Build #21380606) - Latest Fenix Nightly build tested with problem present
  * [Nightly 200507 18:00 (Build #21281805)](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly.2020.05.07.revision/eef5cf346922d8a2751fab85eb67e37d159741f2) - First Fenix Nightly build with problem present (Geckoview 78.0a1-20200505094621)

Issue NOT present (i.e. SharedArrayBuffer works OK) in:

* [Fenix Nightly 200507 15:46 (Build #21281554)](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly.2020.05.07.revision/57eb2b9549154db9d58707fcf89593030eddf5ac) - Last Fenix Nightly build without problem present (Geckoview 77.0a1-20200504093644)
* Firefox for macOS Nightly 78.0a1 (2020-05-17)
* Firefox for Windows Nightly 78.0a1 (2020-05-17)

**Comment by philip-lamb** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1619655#c2, since https://bugzilla.mozilla.org/show_bug.cgi?id=1624266 was landed SharedArrayBuffer is disabled unless COEP/COOP is enabled, which is not currently possible on Android at all.

**Comment by kbrosnan** [comment]
Closing in favor of the Bugzilla issues. The core Gecko team is better suited to track those changes/fixes.
