### ISSUE TITLE
FNX-4504 ⁃ [Bug] The details for one saved login are displayed after interrupting and then resuming Fenix

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#10727]
## Steps to reproduce
1. Go to Settings ~~> Logins and passwords~~ > Saved logins;
1. Tap one saved login, in order to see the site, username and password;
1. Tap the device home button;
1. Open Fenix from Recent apps or home screen icon;
1. Observe the displayed details;
    1. Expected behavior
The Logins and passwords section is displayed and the accounts.firefox section is locked.
    1. Actual behavior
The details from the accounts.firefox section are displayed.
    1. Notes
Not reproducible on Fenix Release 5.0.0, GV 76, from 4/30;
Not reproducible for the Saved logins section;
    1. Device information

* Android device: Nexus 5 (Android 6.0.1), Motorola Moto G6 (Android 8);
* Fenix version: Nightly 200518 GV 78, from 5/18.

**Comment by Diana-Rus** [comment]
Hi, issue seems to be fixed, checked with Google Pixel 3 XL (Android 9), Samsung Galaxy S9 (Android 8) and Sony Xperia Z5 (Android 7) on Firefox Preview Nightly 200602 (Build #21540608)

**GIF - Google Pixel 3 XL (Android 9)**
![20200602-170716](https://user-images.githubusercontent.com/49859863/83531266-695f0880-a4f5-11ea-9a8e-f450a45136dc.gif)

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Fenix Beta 77.0.0-beta.2 Build 21570821 GV 77.0 from 6/5 with Motorola Moto G6 (Android 8).
I will reopen the issue.

**Comment by mcarare** [comment]
For QA: Please test on the next nightly or latest master. TY!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200623-111713](https://user-images.githubusercontent.com/51314259/85379463-798e6480-b544-11ea-9ccb-59baced8967a.png)
