### ISSUE TITLE
FNX-4507 ⁃ "dark background and light text extension" needs to be added to Firefox Mobile preview .

### ISSUE THREAD

**Issue by IRainman** [mozilla-mobile/fenix#10729]
I need "dark background and light text extension" because it's fast and add try black theme!!!
Steps to Reproduce:
True black theme by extension it's really need because i didn't want white or sheet green background from very slowly "dark reader" extension

**Comment by ekager** [comment]
Closing for #2139

**Comment by IRainman** [comment]
@ekager thx U!
