### ISSUE TITLE
FNX-4503 ⁃ [Bug] The `Downloaded` text is displayed even when the download was canceled

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10726]
## Steps to reproduce
1. Launch Firefox and login using a Firefox account.
1. Go to https://accounts.firefox.com/settings
1. Go to the 2FA section and tap on "Enable".
1. Scan the QR code and enter the security code provided by the authentication app.
1. Tap on "Download".
1. Tap on `X` button
    1. Expected behavior
The `Downloaded` text should not be displayed when the download was canceled.
    1. Actual behavior
The downloaded text is displayed even when the download was canceled.
    1. Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 5/18.**

![Screenshot](https://user-images.githubusercontent.com/42831109/82190512-c9508f00-98f9-11ea-8566-d6232fee8c6b.png)UNITO-UNDERSCORE!20200518-111748!

**Comment by Amejia481** [comment]
Thanks @abodea for reporting this issue, but the dialog shown in the picture above belongs to website and it's out the control of Fenix, the website is the one controlling text.

I will close the issue but feel free to reopen if you feel it is needed it.
