### ISSUE TITLE
FNX-4505 ⁃ [Bug]Tab Tray: Open tabs favicons are lost after delete-undo action

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10728]
## Prerequisites
Have a couple of open tabs

## Steps to reproduce
From the **Tab Tray**:

1. Swipe left or right to remove a tab
1. Tap the "Undo" button from the confirmation snackbar
1. Tap the 'x' button to remove a tab
1. Tap the "Undo" button from the confirmation snackbar
1. Tap the upper right **⋮ button** from the "Open Tabs" bar
1. Select "Close all tabs" from the overlay
1. Tap the "Undo" button from the confirmation snackbar

### Expected behavior
After each "Undo" action, the tabs should be restored with the corresponding favicons

### Actual behavior
The favicons of the restored websites aren't displayed

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build #200518 from 5/18

### Notes
Noticed while checking #10332 

► Video
![20200518-113546](https://user-images.githubusercontent.com/51314259/82193410-04ed5800-98fe-11ea-9aa2-3c30c84c3ed0.gif)

**Comment by darkwing** [comment]
Thank you for filing @AndiAJ!  The favicons will be gone once we get screenshots, and we aren't shipping without screenshots, so I'm going to close this.
