### ISSUE TITLE
FNX-4500 ⁃ [Bug] The download button remains highlighted on the "Save recovery codes" page

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10723]
## Steps to reproduce
1. Launch Firefox and login using a Firefox account.
1. Go to https://accounts.firefox.com/settings
1. Go to the 2FA section and tap on "Enable".
1. Scan the QR code and enter the security code provided by the authentication app.
1. Tap on "Download".
1. Tap on `X` button
    1. Expected behavior
The `download` button should not be highlighted anymore after dismissing the download prompt.
    1. Actual behavior
The download button remains highlighted on the "Save recovery codes" page.

### Device information
* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 5/18.**

![Screenshot](https://user-images.githubusercontent.com/42831109/82190512-c9508f00-98f9-11ea-8566-d6232fee8c6b.png)UNITO-UNDERSCORE!20200518-111748!

**Comment by Amejia481** [comment]
Thanks @abodea for reporting this issue, but the dialog shown in the picture above belongs to website and it's out the control of Fenix.

I will close the issue but feel free to reopen if you feel it is needed it.
