### ISSUE TITLE
FNX-4506 ⁃ [Bug]Tab Tray: Flicker after undoing the deletion of all open tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10730]
## Prerequisites
Have a couple of open tabs

## Steps to reproduce
From the Tab Tray:

1. Tap the upper right ⋮ button from the "Open Tabs" bar
1. Select "Close all tabs" from the overlay
1. Tap the "Undo" button from the confirmation snackbar

### Expected behavior
The previously deleted open tabs are properly restored

### Actual behavior
The restored open tabs flicker

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build #200518 from 5/18

### Notes
Noticed while checking #10332

► Video
![20200518-115455](https://user-images.githubusercontent.com/51314259/82194190-15520280-98ff-11ea-96d4-fda56408d0cb.gif)

**Comment by jonalmeida** [comment]
I re-tested this and it doesn't seem fixed/related to https://github.com/mozilla-mobile/android-components/issues/7313.

**Comment by topotropic** [comment]
@AndiAJ seems to be fixed, can you verify? Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200708-133743](https://user-images.githubusercontent.com/51314259/86909904-805ecf00-c121-11ea-83f5-21922bd7e803.gif)
