### ISSUE TITLE
[Bug] Searching a language/saved password displays a misplaced "x"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#10737]
## Steps to reproduce
1. Go to Settings - Language and tap on the search icon.
1. Type a few characters and observe the "x" item's position.

### Expected behavior
The "x" is placed at the end of the line.

### Actual behavior
The "x" is in the middle of the line. Even when RTL language is used.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: 5/18 Nightly build
* Note: The same behavior when searching a saved login.

![](https://user-images.githubusercontent.com/40694158/82219442-f6b33200-9925-11ea-92b3-099abc5fcf5f.png)

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Fenix Beta 5.1.0-beta.1 with Samsung Galaxy Tab S3 (Android 8) when searching in Saved logins and in Language.

**Comment by Diana-Rus** [comment]
Reproducible with Beta 5.2.0-beta.1 on Samsung Galaxy S9 (Android 8)

**Comment by softvision-miralobontiu** [comment]
This issue reproduces also on Beta 78.0.1-beta.1 (6.0.0-beta.1) build, on Samsung Galaxy Tab S6 (Android 9).

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta 82.0.0-beta.2 (Build #2105766793) GV 82.0 from 9/29 with Samsung Galaxy Tab S3 (Android 8).

**Comment by softvision-miralobontiu** [comment]
This issue still reproduces on the 1/4 Nightly build with Samsung Galaxy Tab S6 (Android 10).

**Comment by softvision-miralobontiu** [comment]
Reproducible also on Beta 86.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible with Beta 88.0.0-beta.1 with a x86 emulator Nexus 9 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible also with Beta 90.0.0-beta.5, in landscape mode, with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
This still reproduces with OnePlus 5T (Android 10) in landscape mode, on Beta 91.0.0-beta.2.
