### ISSUE TITLE
FNX-4516 ⁃ [Bug]Tab Tray: Collections should remain expanded after leaving the Home screen view

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10739]
## Prerequisites
Have a collection created

## Steps to reproduce
1. Expand the previously created collection
1. Tap the **Tab Tray**
1. Exit back to the Home screen

### Expected behavior
The Collection should remain expanded

### Actual behavior
The Collection doesn't remain expanded

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build #200518 from 5/18

### Notes
► Video
![20200518-162955](https://user-images.githubusercontent.com/51314259/82220257-11d27180-9927-11ea-830b-7b6000653bc8.gif)

**Comment by liuche** [comment]
This doesn't affect with the drawer.
