### ISSUE TITLE
FNX-4513 ⁃ [Bug] Desktop bookmarks not syncing

### ISSUE THREAD

**Issue by marthinwurer** [mozilla-mobile/fenix#10735]
## Steps to reproduce
1. Set up Firefox account to sync with desktop
1. Look at library

### Expected behavior
Bookmarks from desktop should be in library

### Actual behavior
Bookmarks are missing

### Device information
* Android device: S8 Android 9
* Fenix version: 5.0.0 (Build #21212137)
39.0.1, f19856fa4
GV: 76.0-20200424000239
AS: 0.58.2

**Comment by ekager** [comment]
Are you still seeing this bug in the latest Fenix version @marthinwurer ?

**Comment by marthinwurer** [comment]
Looks like it's working! Thanks guys!
