### ISSUE TITLE
FNX-4509 ⁃ [Bug]Tab Tray:  Remove ⋮ button overlay if tab count = 0

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10731]
## Steps to reproduce
From the Tab Tray:

1. Tap the upper right ⋮ button from the "Open Tabs" bar

### Expected behavior
The ⋮ button overlay shouldn't be displayed in the  "Open Tabs" bar

### Actual behavior
The ⋮ button overlay is displayed even if the user doesn't have any open tabs.
No practical use of the overlay options if there are no tabs opened

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: 
Nightly Build #200518 from 5/18

### Notes
► Video
![20200518-125833](https://user-images.githubusercontent.com/51314259/82200335-8695b380-9907-11ea-9390-f0a443fa6c47.gif)

**Comment by yoasif** [comment]
FWIW, Chrome shows a "New Tab" option in the menu at all times. 

I think that makes more sense than removing pieces of the UI - that feels kinda like mystery meat naviagation.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200521 from 5/21`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200521-111609](https://user-images.githubusercontent.com/51314259/82539042-678c6100-9b55-11ea-9826-0ebbb1056883.gif)
