### ISSUE TITLE
FNX2-16124 ⁃ [Bug] Tab Tray: When opening the tabs from a collection the user is not redirected to the "Open Tabs" screen

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#10734]
## Steps to reproduce
1. Launch Fenix and open 2 or more tabs.
1. Save them as a collection.
1. Reach the home screen, expand the collection, tap on the 3 dot menu, and then `Open tabs`.

### Expected behavior
The user is redirected to the `Open Tabs` screen after opening the tabs from a collection.

### Actual behavior
When opening the tabs from a collection the user is not redirected to the "Open Tabs" screen

### Device information
* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 5/18.**

![20200518-155440](https://user-images.githubusercontent.com/42831109/82216431-a0dc8b00-9921-11ea-8694-056b96e169cb.gif)

**Comment by darkwing** [comment]
This has been fixed

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly build 8/13** with **Google Pixel 4 XL (11)**, **Google Pixel 3a (10)**, **OnePlus A3 (6.0.1).**
