### ISSUE TITLE
FNX-4514 ⁃ [Bug]Tab Tray: "Hairline" separator displayed between Top sites and  Collections section

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10736]
## Steps to reproduce
1. Check the Home screen

    1. Expected behavior
No "hairline" separator between the Top sites and Collections section

### Actual behavior
"Hairline" separator displayed between the Top sites and Collections section

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build #200518 from 5/18

### Notes
►  Screenshot
![rsz](https://user-images.githubusercontent.com/51314259/82219454-fa46b900-9925-11ea-8361-e0a0f6c73b98.png)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200518-163048!

**Comment by liuche** [comment]
Homescreen has been redesigned.
