### ISSUE TITLE
[Bug] MediaDevices.getUserMedia() opens "Back facing camera" by default

### ISSUE THREAD

**Issue by georapbox** [mozilla-mobile/fenix#10748]
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1380795

## Steps to reproduce
1. Navigate to [WebRTC basic getUserMedia demo](https://webrtc.github.io/samples/src/content/getusermedia/gum/)
1. Click the "Open camera" button

### Expected behavior
It should prompt to select between "Back facing camera" and "Front facing camera" the same way that Firefox stable does (see screenshot below).
![Screenshot (May 18, 2020 20](https://user-images.githubusercontent.com/6596039/82244632-38ee6a80-994a-11ea-8f92-96702e3ee8e4.png)UNITO-UNDERSCORE!43!UNITO-UNDERSCORE!59)!

### Actual behavior
After giving camera permissions, it does not ask which camera to use, but instead uses the "Back facing camera" by default. All other Chromium based browsers (Chrome, Brave, Vivaldi) do not ask either but they open the "Front facing camera".

### Device information
* Android device: Motorola One (XT1941-4)
* Fenix version: Nightly 200518 06:00 (Build #21390610)

**Comment by kbrosnan** [comment]
This depends on bz-1380795

**Comment by kbrosnan** [comment]
Copying comment 1 from Bugzilla in case it is helpful to website devs.

>As a side-note, commercial face-calling sites like appear.in really should not be relying on browser defaults, instead requesting the user-facing camera explicitly, with the facingMode constraint. [1] - Ironically, Chrome defaulting to the front camera (and not supporting facingMode yet) is liekly why sites aren't doing this right... 

> [1] https://stackoverflow.com/questions/32086122/getusermedia-facingmode/32364912#32364912

**Comment by vesta0** [comment]
@liuche can we prioritize this bug? We should be providing users with the option to select between back and front camera.

**Comment by jhlin** [comment]
GeckoView example app shows the camera selection doorhanger when requesting video. I wonder if there is something Fenix have to do in order to enable it.

**Comment by liuche** [comment]
This landed, so it will be in the next GV Nightly. I'd say we can QA this on Monday 9/21.

**Comment by abodea** [comment]
Re-testest on the latest Nightly build 9/21 with Google Pixel 4 XL (11) and Samsung Galaxy S10+ (10).
Note that I'm still able to reproduce this issue as there is no prompt asking for the `front` or `back` camera.
Also, note that the same behavior is on the following browsers: **Google Chrome**, **Brave**, **Samsung Internet**, **Vivaldi**.
The only browser I was able to select between front and back camera was **Opera**.

Opera
![20200921-101418](https://user-images.githubusercontent.com/42831109/93744837-2ab3a200-fbfb-11ea-9236-e4b781be2a86.gif)
Vivaldi
![20200921-101338](https://user-images.githubusercontent.com/42831109/93744842-2d15fc00-fbfb-11ea-9c30-3a70baeb529b.gif)

For the example from the description, all the above-mentioned browsers never asked for `front` or `back` camera. 
Removing the `eng:qa:needed` until further notice.

**Comment by georapbox** [comment]
Just tested on the latest Nightly build (Build #2015765171). There is no prompt to select the camera if no `facingMode` constraint is set. But at least, it now opens the front facing camera by default.

**Comment by Avijobo** [comment]
Also tested Samsung S20+ with the latest Nightly build (Build #2015765555) on https://test.webrtc.org, there is no camera detected at all.
Works fine on Chrome for Android though. 

See my bug report here too: https://github.com/mozilla-mobile/fenix/issues/15023

**Comment by liuche** [comment]
I think this bug is handled at least to parity standards with Chrome. Adding a dropdown to select the camera should be filed as a feature request.

**Comment by KrasnayaPloshchad** [comment]
> Adding a dropdown to select the camera should be filed as a feature request.

I made it.

**Comment by KrasnayaPloshchad** [comment]
Everyone now can focus on #16121 if there are any change for this.
