### ISSUE TITLE
FNX-4518 ⁃ [Bug]Tab Tray: Collections can be created while in PB

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10741]
## Prerequisites
Open a couple of websites in Private Browsing (separate tabs) 

## Steps to reproduce
1. Tap the Tab Tray
1. Tap the upper right ⋮ button from the "Open Tabs" bar
1. Tap "Save to collection" and proceed with the creation of a new collection
1. Switch to Normal browsing and exit to the Home screen

### Expected behavior
The user shouldn't be able to create collections while in PB

### Actual behavior
The user can create collection while in the **PB Tab Tray**

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build #200518 from 5/18

### Notes
► Video
![20200518-165725-1](https://user-images.githubusercontent.com/51314259/82224803-fff3cd00-992c-11ea-86eb-28b7c9210ba6.gif)

**Comment by topotropic** [comment]
This is fixed. Thanks!
