### ISSUE TITLE
FNX-4525 ⁃ [Bug] Page containing "--" (two dashes) is always open in search engine

### ISSUE THREAD

**Issue by szpak** [mozilla-mobile/fenix#10747]
## Steps to reproduce
1. Type or paste `https://disposable-wide4--solidsoft-blog-disposable.netlify.app/` in the address page (or anything with `--`).
1. Try to open it.

### Expected behavior
The page is open.

### Actual behavior
The address is used as search term in a default search engine.

## Context
That address scheme (with two dashes) is [used by Netlify](https://docs.netlify.com/site-deploys/overview/#definitions) to distinguish the preview versions of a page from the production ones. As a result, I'm not able to check my webpage with Fenix.

### Device information
* Android device: Pixel 3
* Fenix version: 75.0.0-beta.6 (the latest from Google Play)

**Comment by codrut-topliceanu** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/issues/7096 and its PR https://github.com/mozilla-mobile/android-components/pull/7097

**Comment by codrut-topliceanu** [comment]
Relevant AC PR merged and its issue closed. Should be ready for testing.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fenix Nightly 21560608 GV 79.0a1 from 6/4 with Motorola Moto G6 (Android 8).

Typing the page https://disposable-wide4--solidsoft-blog-disposable.netlify.app/ in the address bar opens the website and not as a search term in the default search engine.

I will remove the qa:needed label.
