### ISSUE TITLE
FNX-4520 ⁃ [Bug] Tab Tray: Collection default title numbering isn't incremented

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10743]
## Prerequisites
Have a couple of open tabs

## Steps to reproduce
From the **Tab Tray:**

1. Tap on "Save to collection"
1. Select the desired 
1. Save them to a new collection (don't change the default title)
1. Repeat 2x the first 3 steps
1. Check the name of the created collections

### Expected behavior
Three collections should be created as it follows:
• "Collection 1"
• "Collection 2"
• "Collection 3"

### Actual behavior
Three collections are created as it follows:
• "Collection 1"
• "Collection 1"
• "Collection 1"

The default Collections number should be incremented.

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build #200518 from 5/18

### Notes
► Video
![20200518-174517](https://user-images.githubusercontent.com/51314259/82229166-c1f9a780-9932-11ea-91b6-6ce6432f2e58.gif)

**Comment by liuche** [comment]
Good bug for @person808

**Comment by topotropic** [comment]
Couldn't reproduce – @AndiAJ is this still an issue for you? Thanks!

**Comment by darkwing** [comment]
I couldn't reproduce this either.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200605 from 6/5`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200605-100350](https://user-images.githubusercontent.com/51314259/83847072-48c0c980-a714-11ea-91f3-3cd63f60fab7.gif)
