### ISSUE TITLE
Disable urlbar autocomplete and disable the open tabs under search

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [mozilla-mobile/fenix#10746]
### Description
Hello,

these options are missing under "Settings -> Search"

* Disable urlbar autocomplete (on/off)

Here you can add additional sub options:

1. URL autocomplete from Mozilla (on/off)
1. URL autocomplete from your bookmarks (on/off)
---

* Show the open tabs under the search (on/off)

### Version
Android 9

Firefox Preview 5.0.0
https://github.com/mozilla-mobile/fenix/releases/tag/v5.0.0

**Comment by Osyotr** [comment]
This autocompletion is really annoying.

**Comment by Osyotr** [comment]
See #5745

**Comment by liuche** [comment]
Duping this to #5745
