### ISSUE TITLE
FNX-4528 ⁃ [UITests] Intermittent UI test error: changeBookmarkParentFolderTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#10753]
```
 androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with content description text: is "Menu")
```

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6337539131377699799/executions/bs.68fe240d1cf6c556/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
other bookmarks tests failing for the same reason: 
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7821071944319915264/executions/bs.da5f91d26a6197d3/testcases/1/test-cases

https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5054681088551426089/executions/bs.76a05929bb7e3d7/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Found an explanation and some solutions here: https://stackoverflow.com/questions/32330671/android-espresso-performs-longclick-instead-of-click

**Comment by AaronMT** [comment]
Google recommended a no-op rollback action as well https://issuetracker.google.com/issues/37078920#comment9
