### ISSUE TITLE
FNX-4530 ⁃ [Bug] Intermittent UI test error: refreshPageTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#10755]
Firebase:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6337539131377699799/executions/bs.d6b26c6987e2afe9/testcases/2/test-cases

**Comment by AaronMT** [comment]
This might be fixed with the revert of https://github.com/mozilla-mobile/fenix/commit/32e74aae61bd0ad5d72dcc47b58eb7518e6001cd

**Comment by sv-ohorvath** [comment]
I'm not seeing any new fails on this one in the last few days. Probably fixed already by https://github.com/mozilla-mobile/fenix/commit/32e74aae61bd0ad5d72dcc47b58eb7518e6001cd, if not, failing tests related to verifyPageContent() will be tracked in https://github.com/mozilla-mobile/fenix/issues/10814
