### ISSUE TITLE
FNX-4538 ⁃ [Bug] YouTube is not working properly on Beta 5.1.0-beta 1 on Samsung devices

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10765]
## Steps to reproduce
1. Go to YouTube and select a random video.
1. Select a different video from the list, while the video from step 1 is still playing.

### Expected behavior
The video selected in step 2 is displayed and starts playing.

### Actual behavior
The video from step 1 continues to play, the video selected in step 2 is ignored.

### Device information
* Android devices: Samsung Galaxy Tab S6 (Android 9), Samsung Galaxy S9 (Android 8)
* Not reproducible on Google Pixel 3a (Android 10), Huawei Mate 20 Lite (Android 9), OnePlus A3 (Android 6.0.1), or OnePlus 5T (Android 9)
* Fenix version: Beta 5.1.0-beta.1
* Not reproducible on 5/19 Nightly build

![](https://user-images.githubusercontent.com/40694158/82322864-df387f80-99df-11ea-9fec-d2570c9399b2.gif)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4650143/logcat.txt)

**Comment by Amejia481** [comment]
I have seen this issue happening also in FireFox nightly desktop.

**Comment by ekager** [comment]
I'm not as concerned if this is only happening on Beta and not Nightly. I don't think there's anything we can do to fix this with older GV versions.

**Comment by softvision-miralobontiu** [comment]
The issue no longer reproduces on Beta 5.1.0-beta.3. 
Verified on Samsung Galaxy Tab S6 (Android 9), and Samsung Galaxy Note 8 (Android 9).
I will close this.
