### ISSUE TITLE
Separate Private Mode search engine

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1076]
### Why/User Benefit/User Problem
In Private mode, users may be more sensitive about search suggestions or queries going to their default (unsafe) search provider. 

User may want to use Google most of the time, but may fear IP based coalescing of queries and want to use DuckDuckGo for private mode. 

This feature currently exists in  Brave, as well.

### What / Requirements
* User is able to select a different search engine for private mode queries. 

### Acceptance Criteria (how do I know when I’m done?)
* User can enter private mode and the browser will allow them to type search queries without suggestions that are hidden from their default (unsafe) search provider.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1004)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807555

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
