### ISSUE TITLE
FNX-4535 ⁃ [UITests] Intermittent UI test error in Media Notification tests

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#10762]
Firebase: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5567630782097466087/executions/bs.5312fb393bace0ad/testcases/1/test-cases

**Comment by AaronMT** [comment]
Same fix required as the other @sv-ohorvath the notification shade is open and in view.

**Comment by sv-ohorvath** [comment]
This one has a different error than #10756 and it looks like it is another case of verifyPageContent() failing, which might have been fixed with https://github.com/mozilla-mobile/fenix/pull/10745
I need to re-check the test reports.

**Comment by sv-ohorvath** [comment]
I didn't see media notifications tests fail in the last 2 days. Since this is another case of verifyPageContent() fail, I'll continue investigating on https://github.com/mozilla-mobile/fenix/issues/10642
