### ISSUE TITLE
FNX-4537 ⁃ [Bug] When "Protect Yourself" toggle is deactivated the background color is white, maybe the boarder should be as for radio buttons

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10764]
## Steps to reproduce
1. Open Fenix browser app.
1. From "Onboarding" screen go to "Protect Yourself" section.
1. Disable the toggle.
    1. Expected behavior
The toggles background is displayed correctly.
    1. Actual behavior
The toggles background is white, it does not show the toggles length.
    1. Device information

* Android device: Google Pixel 3a (Android 10), Huawei Mate 20 Lite (Android 9), Sony Xperia Z5 (Android 7)
* Fenix version: Firefox Preview Beta 58.1.0-beta.1 (Build #21400807)

Huawei Mate 20 Lite (Android 9) - GIF
![20200519-130803](https://user-images.githubusercontent.com/49859863/82315176-9aa6e700-99d3-11ea-9b0e-42569b8355b2.gif)

Sony Xperia Z5 (Android 7) - GIF
![20200519-131130](https://user-images.githubusercontent.com/49859863/82315605-346e9400-99d4-11ea-9410-c3ba0ca06bc8.gif)

It seems that is a regression from #7606

**Comment by BMEduard** [comment]
While investigating this issue, I found that the color for the toggle from the [abstract](https://app.abstract.com/share/8feabb36-05ef-4ec0-a05a-e56582a05c5f?mode=design&sha=ad755708a24ae2f9bcc48facb9bdea84a7ca8b17) for the light theme doesn't match the color used by the icons and the standard/strict radio buttons, as it is the case for the other themes. My suggestion is to use the same color, and it would look like the screenshot below. How should I proceed?

<img src = "https://user-images.githubusercontent.com/23737079/82569119-78a29580-9b88-11ea-8f06-8843ec255def.png" width = "300">

**Comment by brampitoyo** [comment]
@BMEduard We should use the same toggle and radio button colours found under Settings, rather than setting our own value. This should apply to both light theme and dark theme onboarding. And in fact, this should apply everywhere in the app. All form elements should have the same accent colours.

I’m tagging @apbitner here so he can review, should my assumption is wrong.

**Comment by BranescuMihai** [comment]
@brampitoyo I agree that the colors should be uniform across the app!

@apbitner so right now the colors used for the on-state on switches in the app are:
Light mode - #312A65
Dark mode - #AB71FF
Private mode - #AA71FF

Should the colors from the new onboarding palette be used everywhere?
Light mode - #592ACB
Dark mode - #9059FF
Private mode - #9059FF

**Comment by apbitner** [comment]
Yes, colors should be uniform, as shown in this [Abstract](https://app.abstract.com/share/8feabb36-05ef-4ec0-a05a-e56582a05c5f?mode=design&sha=ad755708a24ae2f9bcc48facb9bdea84a7ca8b17) which was part of [#7606](https://github.com/mozilla-mobile/fenix/issues/7606)
