### ISSUE TITLE
FNX-4779 ⁃ Switch from engine-gecko-nightly to engine-gecko-beta (GV 67 Beta)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1077]
Fenix MVP will ship GV 67, which just rode from the GV Nightly channel to Beta. Fenix Nightly builds should now use GV 67 **Beta** builds. @pocmo will need to update AC's `engine-gecko-beta` component to use GV 67 Beta. IIUC, Fenix should then get the right GV version by just switching to `engine-gecko-beta`.

When GV 67 rides from the Beta channel to Release (2019-05-14), Fenix will need to switch to a different `engine-gecko` version.

**Comment by pocmo** [comment]
Depends on https://github.com/mozilla-mobile/android-components/issues/2374

**Comment by cpeterso** [comment]
Note that we want Fenix to use `geckoview-beta-armeabi-v7a`, NOT `geckoview-beta-arm64-v8a`. GV 68 Nightly includes the new ARM64 Ion JIT, but GV 67 Beta does not.

**Comment by pocmo** [comment]
@cpeterso You mean we do not want to ship a Fenix ARM64 build?

**Comment by cpeterso** [comment]
Correct. At this time, we do not want to ship ARM64 builds of GV 67. Will users with Fenix ARM64 builds get updated or stuck when a new Fenix ARMv7 update is available with a greater version number?

**Comment by pocmo** [comment]
They should get updated to the ARMv7 build.

**Comment by cpeterso** [comment]
@pocmo - This issue suggesting Fenix switch from engine-gecko-nightly to engine-gecko-beta (GV 67 Beta) is still open, but I just confirmed that Fenix Nightly is using GV 67. Is Fenix using an old GV 67 Nightly version or has this engine-gecko-beta issue already been fixed?

FWIW, we now want Fenix Nightly to use GV 68 Nightly, so we want to WONTFIX this issue. I will file a new bug about switching from GV 67 to GV 68 Nightly.
