### ISSUE TITLE
[Bug] Pull to refresh doesn’t work on any website

### ISSUE THREAD

**Issue by orangesunny** [mozilla-mobile/fenix#10771]
## Steps to reproduce
1. open any website
1. try pull to refresh

### Expected behavior
Pull should refresh the website

### Actual behavior
It is not refreshing nor doing any action.

### Device information
* Android device: Samsung Galaxy S9+
* Fenix version: 5.0.0, all builds so far.

**Comment by cadeyrn** [comment]
Pull to refresh is not yet enabled in release builds.

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

Enabled in #16054
