### ISSUE TITLE
FNX2-13258 ⁃ [Meta] Review Leanplum Integration: Events, Attributes & Deeplinks

### ISSUE THREAD

**Issue by isa-mobile** [mozilla-mobile/fenix#10773]
A stress test was performed by the Mobile Engagement Team to verify Leanplum’s integration on Fenix in preparation for larger multivariate tests in the new environment. 

The stress test was documented [here](https://docs.google.com/document/d/1dYJRQAfPwX4lsF6VHUsMzoM1fq_gL6B7r067jCIb4H8/edit#heading=h.j4nrulvf9qc) and all test details were registered [here](https://docs.google.com/spreadsheets/d/1klobliu3LctV3WFQmP-mAFji7vq9QA4IGRIj-S5azm0/edit#gid=996666354).

### Requirements
[The summarized list with all bugs](https://docs.google.com/spreadsheets/d/1klobliu3LctV3WFQmP-mAFji7vq9QA4IGRIj-S5azm0/edit#gid=1226037869)

### Acceptance Criteria (how do I know when I’m done?)
Events and attributes have been integrated and validated. Plus, the Mobile Engagement Team is informed so they can check on their side.

**Comment by bifleming** [comment]
Work is complete
