### ISSUE TITLE
FNX-4551 ⁃ [Bug] Viewport truncated on penny-arcade

### ISSUE THREAD

**Issue by bholley** [mozilla-mobile/fenix#10780]
## Steps to reproduce
* Visit https://www.penny-arcade.com/comic on today's Fenix nightly.

### Expected behavior
* Page renders normally, as it does on Fenix release.

### Actual behavior
* Viewport is truncated.

This is on a Pixel 2, but @csadilek was also able to reproduce on his device.

**Comment by bholley** [comment]
This issue is at least 9 days old, because I saw it when filing https://github.com/mozilla-mobile/android-components/issues/6985 . I thought they were related but apparently not.

**Comment by csadilek** [comment]
Page renders fine in latest GV example and A-C sample browser.

**Comment by csadilek** [comment]
OK, tracked this down to this call to `setDynamicToolbarMaxHeight` in Fenix: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L598

GV example, A-C sample browser and R-B don't use this which is why we didn't repro there.

**Comment by sblatz** [comment]
Filed a GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1640223

**Comment by csadilek** [comment]
@bholley this works again for me using latest Nightly on the Pixel 3a, would you mind verifying too?

**Comment by bholley** [comment]
LGTM Thanks!
