### ISSUE TITLE
FNX-4780 ⁃ Manage each type of permission

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1078]
### Camera Permissions
As a user, I want to know when websites want access to the camera on my device and want to control whether or not they can have access.

### Acceptance criteria
If I have not given Fenix permission to access my camera, I want Android to prompt me to grant Fenix permission. 
If I allow Fenix permission to access my camera, when I arrive at a site requesting access to my camera I want Fenix to prompt me to grant permission to the site. 
If I grant permission to the site, I want the site to access my camera and I want to see an indication that the site has access in the site control panel.
If I do not grant permission to the site (either by not allowing or not making an explicit decision) I want Fenix to deny access to my camera and I want to see an indication that the site is blocked from access in the site control panel.
If I deny Fenix permission to access my camera, when I arrive at site requesting access to my camera I want Fenix to deny the website access to my camera and I want to see an indication that the site is blocked by Android from access in the site control panel but I do not want to be interrupted by a prompt. 

### Microphone Permissions
As a user, I want to know when websites want access to the microphone on my device and want to control whether or not they can have access.

### Acceptance criteria
If I have not given Fenix permission to access my microphone, I want Android to prompt me to grant Fenix permission. 
If I allow Fenix permission to access my microphone, when I arrive at a site requesting access to my camera I want Fenix to prompt me to grant permission to the site. 
If I grant permission to the site, I want the site to access my microphone and I want to see an indication that the site has access in the site control panel.
If I do not grant permission to the site (either by not allowing or not making an explicit decision) I want Fenix to deny access to my microphone and I want to see an indication that the site is blocked from access in the site control panel.
If I deny Fenix permission to access my microphone, when I arrive at site requesting access to my microphone I want Fenix to deny the website access to my microphone and I want to see an indication that the site is blocked by Android from access in the site control panel.

### Location Permissions
As a user, I want to know when websites want access to my location and want to control whether or not they can have access.

### Acceptance criteria
If I have not given Fenix permission to access my location, I want Android to prompt me to grant Fenix permission. 
If I allow Fenix permission to access my location, when I arrive at a site requesting access to my location I want Fenix to prompt me to grant permission to the site. 
If I grant permission to the site, I want the site to access my location and I want to see an indication that the site has access in the site control panel.
If I do not grant permission to the site (either by not allowing or not making an explicit decision) I want Fenix to deny access to my location and I want to see an indication that the site is blocked from access in the site control panel.
If I deny Fenix permission to access my location, when I arrive at site requesting access to my location I want Fenix to deny the website access and I want to see an indication that the site is blocked by Android from access in the site control panel.

### Notification Permissions
As a user, I want to know when websites want to send me notifications and control whether or not they send them. 

### Acceptance criteria
If I have not given Fenix permission to send me notifications, I want Android to prompt me to grant Fenix permission. 
If I allow Fenix permission to send me notifications, when I arrive at a site requesting access to send me notifications I want Fenix to prompt me to grant permission to the site. 
If I grant permission to the site, I want the site to send me notifications and I want to see an indication that the site has access in the site control panel.
If I do not grant permission to the site (either by not allowing or not making an explicit decision) I want Fenix to deny access to send me notifications and I want to see an indication that the site is blocked from access in the site control panel.
If I deny Fenix permission to send me notifications, when I arrive at site requesting access to my location I want Fenix to deny the website access and I want to see an indication that the site is blocked by Android from access in the site control panel.

Site Permissions Flow: https://whimsical.co/QXGiB45gjs1iniprdrWdBG

![image](https://user-images.githubusercontent.com/773158/54636956-e7083700-4a5d-11e9-9654-62d8b13a41a4.png)

**Comment by rokejulianlockhart** [comment]
Is what https://github.com/mozilla-mobile/fenix/issues/1078#issue-422919797 suggests the current behaviour?
