### ISSUE TITLE
FNX-4556 ⁃ [Bug] Leak at BrowserFragment CoordinatorLayout

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#10784]
## Steps to reproduce
1. Navigate to any page
1. Change the toolbar position from `bottom` to `top` 
1. Navigate to any page
1. Change the toolbar position from `top` to  `bottom`

![Screenshot](https://user-images.githubusercontent.com/773158/82369628-558bb080-99e5-11ea-8569-1af05b8b8b81.png)UNITO-UNDERSCORE!20200519-152715!

[2020-05-19_15-08-42_605.hprof.zip](https://github.com/mozilla-mobile/fenix/files/4652671/2020-05-19_15-08-42_605.hprof.zip)

### Expected behavior
No memory leaks happen

### Actual behavior
2 memory leaks happened

### Device information
1.0.2021 (Build #1)
42.0.20200518130035, f0cb2cca9
GV: 78.0a1-20200517094345
AS: 0.58.2 3:09
Tuesday 5/19 @ 11:57 AM

**Comment by ValentinTimisica** [comment]
Also encountered this leak but with other steps to reproduce.

### Steps to reproduce
- Open the app
- Open a new tab or an existing one
- Tap 3 dot menu and go to `Settings`

### Additional info
- [2020-05-26_18-06-14_482.hprof.zip](https://github.com/mozilla-mobile/fenix/files/4683168/2020-05-26_18-06-14_482.hprof.zip)
- [Screenshot](https://drive.google.com/file/d/1wGqVqdyETBvPqD81sFjeu4tOAYaA30Hf/view?usp=sharing)

**Comment by ekager** [comment]
Thank you for filing :)

**Comment by ekager** [comment]
Closing as fixed
