### ISSUE TITLE
FNX-4558 ⁃ [Bug] Unable to download files from mega

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#10786]
Taken from [this Reddit post](https://www.reddit.com/r/firefox/comments/gi3s23/cant_download_files_from_mega/)

## Steps to reproduce
1. Upload a file to https://mega.nz/
1. Download the file

### Expected behavior
The file should be downloaded

### Actual behavior
Fenix shows an error message.

**Comment by Amejia481** [comment]
This issue was reported on Reddit before we had support for blob uris. Now we have support. QA please help us to verify if this website is working as expected.

**Comment by sflorean** [comment]
Verified this on the latest Nightly 5/21 with Nokia 6 (Android 7.1.1), Samsung Galaxy Note 10 (Android 10), and LG G7 Fit (Android 8.0).
I was able to download pdf, images, apk from mega but didn't work for videos. I didn't get the download notification. 
@Amejia481 should I open a new issue and close this, or is covered already in another bug?

**Comment by Amejia481** [comment]
> Verified this on the latest Nightly 5/21 with Nokia 6 (Android 7.1.1), Samsung Galaxy Note 10 (Android 10), and LG G7 Fit (Android 8.0).
> I was able to download pdf, images, apk from mega but didn't work for videos. I didn't get the download notification.
> @Amejia481 should I open a new issue and close this, or is covered already in another bug?

Yes, please let's open a new issue indicating all the steps to reproduce it

**Comment by sflorean** [comment]
@Amejia481 thank you! filed #10816.
