### ISSUE TITLE
[Bug] The "search in firefox" context menu option doesn't display in my installation

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#10781]
## Steps to reproduce
1. Long press a word, possibly select more words.
1. Click the meatball menu.

### Expected behavior
* `Search using Firefox` should be there 

### Actual behavior
* It's not there.

### Device information
* Android device: Galaxy S10e
* Fenix version: Nightly 200518 06:00 (Build #21390610)

Discussing with @ekager on Slack made me realize that this happens only on one of my 2 installations: the one installed from the Play Store as Firefox Preview Nightly (that I installed before the migation). The one migrated from Fennec (named `Firefox Nightly`) has the option properly.

**Comment by LittleAngelwings** [comment]
Here no problem.. Search with Firefox is there..

Nightly 200521 06:01 (Build #21420607)
43.0.20200520190033, 3aa8dc692
GV: 78.0a1-20200520033931
AS: 0.59.0

![Screenshot_20200521_144905](https://user-images.githubusercontent.com/44252450/82560845-864d2080-9b72-11ea-9afb-e2b5bbd2b5c8.jpg)

.

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on Samsung Galaxy Tab S6 (Android 10)on the 11/17 Nightly build.
@julienw could you, please, retry?

**Comment by julienw** [comment]
Yeah this works fine now. Thanks !
