### ISSUE TITLE
FNX-4781 ⁃ Managing exceptions of a site permissions

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1079]
![](https://user-images.githubusercontent.com/773158/55810451-92346b00-5ab5-11e9-9e7b-24933ebc5d24.png)

**Comment by mheubusch** [comment]
@vesta0 does this one need to move to UX review?

**Comment by sv-ohorvath** [comment]
Verified and no issues found so far. I'll close this.
devices: Pixel, Nexus 5, Galaxy Tab (Android 8)
