### ISSUE TITLE
Intermittent UI test error: testDownloadPrompt

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#10798]
Firebase logs: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6917063598475248963/executions/bs.f0b26acb8fc140bd/testcases/1/test-cases

Test video: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6917063598475248963/executions/bs.f0b26acb8fc140bd/videos

Looks like the download does not start and so the prompt is not shown

**Comment by AaronMT** [comment]
I am thinking this is due to https://github.com/mozilla-mobile/fenix/issues/10619

**Comment by AaronMT** [comment]
There's also this comment which was added I just now noticed (@kglazko)

```// Re-enable to test possible solution in AC 6817.```

https://github.com/mozilla-mobile/fenix/commit/c0c41dfd74954ea7a02d58eca4f43dea769d6bf8

https://github.com/mozilla-mobile/android-components/pull/6817

That might have been a separate issue.

**Comment by AaronMT** [comment]
This seems to be a frequent intermittent. We should probably disable it for now.

**Comment by AaronMT** [comment]
For some reason again `verifyPageContent` triggers a timeout. I just don't know enough about UIAutomator to understand what can fail this.

```HTML
<html>
<body>
    <a href="../resources/Globe.svg" download>Page content: Globe.svg</a>
</body>
</html>
```
```Kotlin
fun verifyPageContent(expectedText: String) {
        val mDevice = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
        mDevice.waitNotNull(Until.findObject(By.textContains(expectedText)), waitingTime)
    }
```

**Comment by sv-ohorvath** [comment]
In an attempt to enable the testDownloadPrompt test, I found that there is another flaky method used to download the file from the test page: BrowserRobot.clickLinkMatchingText. 
So this can't be enabled yet until we find a solution for anything inside the browser view.
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7880546569454411437/executions/bs.a33d251d49a7341f/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Hasn't failed after the fix, closing.
