### ISSUE TITLE
FNX-4568 ⁃ [Bug]Native code crash after adding and opening a PWA

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10795]
## Steps to reproduce
1. Navigate to app.starbucks.com
1. Install it as a PWA
1. Open the PWA

### Expected behavior
Step 2 - Preperly install the PWA
Step3 - The PWA should opened in it's own individual task, as a standalone app

### Actual behavior
Step 2 - native code crash
Step 3 - native code crash

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Beta 5.1.0-beta.1 from 5/19
• Nightly 200520 from 5/20

### Notes
• Crash report after installing the PWA
https://crash-stats.mozilla.org/report/index/664577be-24c9-4bee-8a6f-c3e460200520

• Crash report after trying to open it 
https://crash-stats.mozilla.org/report/index/8d77e0ee-cbfc-4794-895b-bf7de0200520

**Comment by kbrosnan** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1635720

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly Build 200527 from 5/27`** & **`Beta 5.1.0-beta.2  from 5/27`** using a OnePlus A3 (Android 6.0.1)

► Video
![20200527-155652](https://user-images.githubusercontent.com/51314259/83021712-1556ae80-a033-11ea-8ae0-9d43577e75ca.gif)
