### ISSUE TITLE
FNX-4571 ⁃ [Crash] Crash in java.lang.RuntimeException: at android.app.ActivityThread.handleServiceArgs(ActivityThread.java)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10797]
## Steps to reproduce
none yet. Happened while using custom tabs in private mode, in parallel with the app.
After I closed the custom tab, the app didn't appear in the recent apps list anymore and kept crashing in the background.
Crash report: https://crash-stats.mozilla.org/signature/?product=Fenix&version=5.1.0-b&signature=java.lang.RuntimeException%3A%20at%20android.app.ActivityThread.handleServiceArgs%28ActivityThread.java%29&date=%3E%3D2020-05-19T12%3A19%3A00.000Z&date=%3C2020-05-20T12%3A19%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports

### Device information
* Android device: Huawei P20 lite (Android 9)
* Fenix version: 5.1-beta1

**Comment by rvandermeulen** [comment]
This is currently the #5 overall Fenix 5.1.1 topcrash according to Socorro.

**Comment by kbrosnan** [comment]
This has dropped to background levels, 1 crash over all our Beta population for 79.0-beta9.
