### ISSUE TITLE
[Bug] Device name change isn't reflected in the Account Settings UI

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#10792]
## Steps to reproduce
Sign-in to FxA, change the device name in Fenix.

### Expected behavior
Device name changes in the UI, and the change is reflected in other connected clients.

### Actual behavior
Change is reflected in other connected clients, but in Account Settings old name remains until an app restart.

**Comment by ValentinTimisica** [comment]
I'm unable to reproduce the bug. Can someone from QA verify this? Maybe it was fixed in the meantime.

**Comment by abodea** [comment]
I checked this issue on the latest **Nightly 6/22** with **Google Pixel 4 XL (10)**  but I couldn't reproduce the issue.
Note that the name changed fast and no restart was needed.
Removing `eng:qa:needed` until further notice.

**Comment by abodea** [comment]
@ValentinTimisica should we close this as verified?

**Comment by ValentinTimisica** [comment]
If @grigoryk can no longer reproduce the bug we can close the ticket.

**Comment by ekager** [comment]
I am still able to repro on Nightly.

**Comment by ekager** [comment]
There seem to be a few bugs reported about changing the device name in Fenix 
#7199 and #6565 are older variations on the same theme
