### ISSUE TITLE
FNX-4574 ⁃ [Crash] [@ java.lang.RuntimeException: at android.app.ActivityThread.handleStopService(ActivityThread.java) ]

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10801]
## Steps to reproduce
Don't have any.
I had 8 tabs opened, I was playing some videos on YouTube, trying Pip, I put Fenix in the background and it crashed.
I cannot reproduce it again.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 9)
* Fenix version: Beta 5.1.0-beta.1

https://crash-stats.mozilla.org/report/index/90b4d1b2-2679-42c1-a1d4-a81590200520#tab-details

**Comment by kbrosnan** [comment]
BZ 1641046

**Comment by ekager** [comment]
Looks like https://github.com/mozilla-mobile/fenix/issues/10693 ?

**Comment by liuche** [comment]
They look similar in that they're both AbstractDownloadFetchService but are crashing on different things. Let me double check to see if this one is showing up on nightly still.

**Comment by kbrosnan** [comment]
See crashes on GV 20200604092907 ex https://crash-stats.mozilla.org/report/index/fb371f5a-94f4-4b30-8c85-8b4880200608

Though in that time we have had 20200606 and 20200608 build.
