### ISSUE TITLE
FNX-4784 ⁃ [Bug] Sharing page in reader view

### ISSUE THREAD

**Issue by J-Siu** [mozilla-mobile/fenix#10807]
## Steps to reproduce
1. Open https://en.m.wikipedia.org/wiki/Main_Page
1. Switch to reader view
1. Share to a desktop browser (I use FF 76.01 on MacOS)

### Expected behavior
I am not sure if this is suppose to work. I kind of remember page in reader view can't be shared in the past.

### Actual behavior
Desktop FF open url: moz-extension://dfcdea94-f560-452b-b929-e7875334cc93/readerview.html?url=https%3A%2F%2Fen.m.wikipedia.org%2Fwiki%2FMain_Page&id=137438954171

The page is blank.

### Device information
* Android device: oneplue 6t
* Fenix version: 200520 06:01

**Comment by jonalmeida** [comment]
This is a known issue that requires some changes to Gecko and GeckoView before we can tackle it: https://github.com/mozilla-mobile/android-components/issues/2879
