### ISSUE TITLE
FNX-4600 ⁃ [Bug] Login credentials not sorted by default

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#10815]
Created this issue based on @AndiAJ [comment](https://github.com/mozilla-mobile/fenix/issues/9505#issuecomment-631308067).

> Hi, I've re-checked this matter on **`Beta 5.1.0-beta.1`** using the following devices:
> • Google Pixel 3a (Android 10)
> • Huawei Mate 20 Lite (Android 9)
> • OnePlus A3 (Android 6.0.1)
> 
> **It seems that the login credentials aren't properly sorted by default (sorted random)**
> 
> ## 1st scenario Name (A-Z)
> ## Prerequisite:
> Leave the sorting option set to **Name (A-Z) (Sort alphabetically)**
> 
> ## Steps to reproduce:
> 1. Log in to the following websites in this order:
>    • Twitter
>    • Facebook
>    • Yahoo
>    • Instagram
> 2. Check the saved logins
> 
> ## Expected behavior
> The login credentials should be sorted as it follows:
> • Facebook
> • Instagram
> • Yahoo
> • Twitter
> 
> ## Actual behavior
> • Yahoo
> • Facebook
> • Twitter
> • Instagram
> 
> ## Notes
> ❗ Reproducible on the latest Nightly 200520 from 5/20
> ❗ If you select again the Name (A-Z) option the credentials will be properly sorted.
> On the other hand, if you close and re-open Fenix the credentials will be again sorted randomly
> (as per the Actual behaviour)
> 
> ## 2nd Scenario Last used
> ## Prerequisite:
> Clean profile no Login credentials saved.
> Set the sorting option to **Last used**
> 
> ## Steps to reproduce:
> 1. Log in to the following websites in this order:
>    • Twitter
>    • Facebook
>    • Yahoo
>    • Instagram
> 2. Check the saved logins
> 
> ## Expected behavior
> The login credentials should be sorted as it follows:
> • Instagram
> • Yahoo
> • Facebook
> • Twitter
> 
> ## Actual behavior
> • Yahoo
> • Facebook
> • Twitter
> • Instagram
> 
> ## Notes
> ❗ Reproducible on the latest Nightly 200520 from 5/20
> ❗ If you select again the **Last used** option the credentials will be properly sorted.
> On the other hand, if you close and re-open Fenix the credentials will be again sorted randomly
> (as per the Actual behaviour)

**Comment by ValentinTimisica** [comment]
Reopening this for QA

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fenix Nightly Build 21500607 from 5/29 with Motorola Moto G6 (Android 8).
The login credentials are sorted as mentioned in the expected behavior of the 2 scenarios from the description.
I will remove the qa:needed label.
