### ISSUE TITLE
[Bug]  Custom tabs three dot menu follows browser theme not custom tab theme

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10813]
## Steps to reproduce
Keep fenix in normal mode
Open a custom tab from anpther app 
Open three dot menu in custom tab
Repeat the same for Private browsing mode

### Expected behavior
The theme for the custom tab should remain same whatever mode the browser is in

### Actual behavior
![Screenshot](https://user-images.githubusercontent.com/33252312/82534539-d4dbca00-9b34-11ea-9426-a5c05062ee2a.png)UNITO-UNDERSCORE!20200521-125818!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!
![Screenshot](https://user-images.githubusercontent.com/33252312/82534553-da391480-9b34-11ea-955d-5840364ece42.png)UNITO-UNDERSCORE!20200521-125730!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200519 06:00 (Build #21400607)

**Comment by Yajo** [comment]
bot, go to bed.
