### ISSUE TITLE
FNX-4597 ⁃ [Bug] Sometimes I cannot go back when on a webpage unless I press back button a lot of times

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10811]
## Steps to reproduce
Sometimes I cannot go back and I've to press back button a lot of times (close to 6 to 7 times), the behaviour is not consistent sometimes it happens on the same webpage and sometimes it doesn't happen on the same webpage.

Do not have steps to reproduce, it happens randomly and sometimes pressing back works as it should but other times It doesn't work on the same webpage.

### Expected behavior
I should be able to go back if I press back  button once

### Actual behavior
Cannot go back sometimes, and when I restart the browser while keeping the tabs open and relaunch it and open the webpage I cannot go back instead the browser takes me to the homepage of Fenix.

### Device information
* Android device: Motorola One Power, Android 10.
* Fenix version: 5.1.0-beta.1 and Nightly 200519 18:01

**Comment by SS1113** [comment]
I reproduced the issue here after following the link to the issue when on a comment thread: https://github.com/mozilla-mobile/fenix/issues/10436 but I doubt you'll be able to reproduce it as well as it worked again as it should when I gone back clicked on the same link.
![20200522_083140](https://user-images.githubusercontent.com/42088907/82627004-c515c180-9bd8-11ea-8f71-d19f36fe2131.gif)

**Comment by Diana-Rus** [comment]
Hi, the issue has also been reported here #8180 . I will close this as it will he handled there.

**Comment by Diana-Rus** [comment]
Hi, i've tried in Nightly 5/25 on my personal device with motion control - one handed option enabled on news.ycombinator.com and github.com but wasn't able to reproduce the back issue.

Device: Huawei P10
OS: Android 9
EMUI: 9.1.0

**GIF - news.ycombinator.com**
![20200525-185500](https://user-images.githubusercontent.com/49859863/82829497-1913f500-9ebc-11ea-8688-ae044d0be0da.gif)

**GIF - github.com**
![20200525-190802](https://user-images.githubusercontent.com/49859863/82829504-1c0ee580-9ebc-11ea-96c0-ace74c6971bf.gif)

But in case you reproduce the problem, please re-open the ticket.

**Comment by ekager** [comment]
Comment from @SS1113 in #10972

```
1. Go here: https://www.indiatoday.in/india/story/air-india-passenger-tests-coronavirus-positive-1682333-2020-05-27

2. Scroll to the bottom of the page, and to the top again. And stay there for a few seconds (3 to 4 seconds would be enough)

3. Press the back button, observe that it take more than a single press to go back and sometimes it just refuses to go back and sometimes it takes several clicks before it works.

I tried to reopen the existing issue for this but it didn't work.

Edit: If it doesn't work on the first try then try it again.

```
