### ISSUE TITLE
[Bug] Can't download videos from mega.nz

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#10816]
## Steps to reproduce
1. Upload a video to https://mega.nz/
1. Download the video.

### Expected behavior
The video is downloaded.

### Actual behavior
The video is played.

### Notes
Not reproducible on Chrome.

### Device information
* Android device: Nokia 6 (Android 7.1.1), Samsung Galaxy Note 10 (Android 10), and LG G7 Fit (Android 8.0)
* Fenix version: Nightly 5/21.

**Comment by Amejia481** [comment]
This is a webcompac issue the website is sending us a different html depending on the user agent.

You can use this [file](https://mega.nz/file/qYxWkCjb#nnQfPG35WjR7ItBp0Kr5g0NSIBHml1ovFJq1mb7jEjc) to test

For user agents like "**Mozilla/5.0 (Android 10; Mobile; rv:79.0) Gecko/79.0 Firefox/79.0**" the same one use by GV browser, Fenix etc Fennec, the site returns us the button **"OPEN FILE"** that doesn't trigger the download and loads the file.

For user agents like Firefox desktop or Chrome the site returns a different button **"SAVE FILE"** this one trigger the download.
