### ISSUE TITLE
FNX-4614 ⁃ Integrate SyncedTabs feature

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#10834]
A reference implementation exists here: https://github.com/mozilla-mobile/reference-browser/tree/master/app/src/main/java/org/mozilla/reference/browser/tabs/synced

To start:

1. We could copy over the code from Reference Browser to Fenix  (except the `SyncedTabsActivity.kt`).
1. Connect the SyncedTabsFragment to the menu.
1. Fix any references where needed.
1. Follow the Fenix architecture pattern.
1. Update UI to match Fenix history/bookmarks lists
1. Tests!

Designs for an MVP version: https://app.abstract.com/share/cb14ade9-a5a1-4ca9-8012-4350363cf5b4

**Comment by softvision-miralobontiu** [comment]
Verified on the latest Nightly build from 6/4 that:
- the "Synced tabs" option is displayed both in the main three-dot menu and in the page's three-dot menu, in normal mode and private mode:
![synced tabs menu](https://user-images.githubusercontent.com/40694158/83730715-21a1c380-a652-11ea-8697-55b4fc141235.png)

![page menu](https://user-images.githubusercontent.com/40694158/83731133-a7257380-a652-11ea-8df6-26dba985be29.png)

- the UI matches Fenix history/bookmarks lists.
- the user can choose to sync tabs across Firefox connected devices,
- the user can access synced tabs in other connected devices on Fenix:
- the user can access the synced Fenix tabs on the other Firefox connected devices,
- the user sees the suggestions in the awesomebar for sites from the synced tabs.

Tested with OnePlus 5T (Android 5T), Sony Xperia Z5 Premium (Android 7.1.1), and Windows 10.
I've connected both mobile devices and desktop. The synced tabs were displayed correctly on every device.

@jonalmeida can I close the issue or is there anything else that needs to be tested by QA?
Thank you!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200604 from 6/4`**

I've synced the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
• Desktop

► Video from Google Pixel 3a
![20200604-150247](https://user-images.githubusercontent.com/51314259/83756162-53795100-a677-11ea-8c0c-ab04e727d2d9.gif)

► Video from Huawei Mate 20 Lite
![20200604-150938](https://user-images.githubusercontent.com/51314259/83756430-b23eca80-a677-11ea-838d-93770848a7ef.gif)

► Video from OnePlus A3
![20200604-150402](https://user-images.githubusercontent.com/51314259/83756283-84598600-a677-11ea-88f6-c127603b1416.gif)


► Screenshot from the Desktop
![Capturerere](https://user-images.githubusercontent.com/51314259/83755806-c930ed00-a676-11ea-9a50-994be6970e8c.JPG)

**Comment by jonalmeida** [comment]
> the user sees the suggestions in the awesomebar for sites from the synced tabs.

This hasn't been integrated yet, but it can be easily mistaken with history sync. I'll file a separate issue for this integration.

Thank you for verifying @softvision-miralobontiu and @AndiAJ .
