### ISSUE TITLE
FNX-4615 ⁃ [Bug] Intermittent failure of openBookmarkInPrivateTabTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#10836]
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5054681088551426089/executions/bs.76a05929bb7e3d7/test-cases

androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with content description text: is "Menu")

View Hierarchy:
+>PopupDecorView{id=-1, visibility=VISIBLE, width=747, height=1560, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(981,217)(wrapxwrap) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged} ty=APPLICATION_PANEL fmt=TRANSPARENT wanim=0x7f140103 surfaceInsets=Rect(45, 45 - 45, 45) (manual)
fl=SPLIT_TOUCH HARDWARE_ACCELERATED FLAG_LAYOUT_ATTACHED_IN_DECOR
pfl=WILL_NOT_REPLACE_ON_RELAUNCH LAYOUT_CHILD_WINDOW_IN_PARENT_FRAME}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+->PopupBackgroundView{id=-1, visibility=VISIBLE, width=747, height=1560, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@b4efff0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+-->CardView{id=-1, visibility=VISIBLE, width=747, height=1560, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@63e4969, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+--->DynamicWidthRecyclerView{id=2131362486, res-name=mozac_browser_menu_recyclerView, visibility=VISIBLE, width=689, height=1480, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3196fee, tag=null, root-is-layout-requested=false, has-input-connection=false, x=29.0, y=40.0, child-count=13}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@2035c8f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@73c2b1c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=250, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d691325, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=History, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@d309cfa, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=132.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@e332ab, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=332, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@56edd08, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Bookmarks, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@3bcbca1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=264.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@e5b8ec6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=273, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@5a04e87, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add-ons, input-type=0, ime-target=false, has-links=false}
|
+---->ConstraintLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@6294c23, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=396.0, child-count=5}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@ada4520, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatImageView{id=2131362569, res-name=notification_dot, desc=Highlighted, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@6bf5ed9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=11.025001, y=-11.025001}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=270, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@337b09e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=37.0, text=Settings, input-type=0, ime-target=false, has-links=false}
|
+----->AppCompatTextView{id=2131362326, res-name=highlight_text, visibility=INVISIBLE, width=270, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@eba877f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=37.0, text=Settings, input-type=0, ime-target=false, has-links=false}
|
+----->AppCompatImageView{id=2131362255, res-name=end_image, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@5ee934c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@3e0f95, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=528.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@56a38aa, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=531.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@8fa1c9b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=437, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@2179838, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Report site issue, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@7bd1011, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=663.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@48b3576, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=348, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@8d3e777, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Find in page, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@fc9ffe4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=795.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@3519c4d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=419, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@7ed3302, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add to top sites, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@b158413, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=927.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@193650, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=510, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b28b049, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add to Home screen, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@77f7d4e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1059.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@1ca4e6f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131362842, res-name=text, visibility=VISIBLE, width=455, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@fe3677c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Save to collection, input-type=0, ime-target=false, has-links=false}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@3430805, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1191.0, child-count=2}
|
+----->AppCompatImageView{id=2131362355, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@8da205a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->SwitchCompat{id=2131362814, res-name=switch_widget, visibility=VISIBLE, width=535, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@a57628b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=0.0, text=Desktop site, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@9bd7f68, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1323.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@4f11f81, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1326.0, child-count=4}
|
+----->AppCompatImageButton{id=-1, desc=Bookmark, visibility=VISIBLE, width=172, height=66, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@109e826, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0}
|
+----->AppCompatImageButton{id=-1, desc=Share, visibility=VISIBLE, width=172, height=66, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@9579c67, tag=null, root-is-layout-requested=false, has-input-connection=false, x=172.0, y=44.0}
|
+----->AppCompatImageButton{id=-1, desc=Forward, visibility=VISIBLE, width=172, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@a9f2a14, tag=null, root-is-layout-requested=false, has-input-connection=false, x=344.0, y=44.0}
|
+----->AppCompatImageButton{id=-1, desc=Stop, visibility=VISIBLE, width=173, height=66, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@40f32bd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=516.0, y=44.0}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:324)
at org.mozilla.fenix.ui.BookmarksTest.openBookmarkInPrivateTabTest(BookmarksTest.kt:246)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by sv-ohorvath** [comment]
Fixed by https://github.com/mozilla-mobile/fenix/pull/10842.
