### ISSUE TITLE
Use offline voice transcription on Pixels, in Gboard

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10832]
### What is the user problem or growth opportunity you want to see solved?
* increased speed and decreased latency when using voice
* voice commands are more reliable even in spotty networks
* increased privacy since user voices never leave device

### How do you know that this problem exists today? Why is this important?
privacy concerns over voice exist: 

* https://www.cnbc.com/2019/08/28/apple-apologizes-for-listening-to-siri-conversations.html
* https://www.bbc.com/news/technology-50048144

### Who will benefit from it?
* people on spotty networks
* people who prefer not to use online speech recognition 
* pixel owners

- - -
This is the underlying feature: https://ai.googleblog.com/2019/03/an-all-neural-on-device-speech.html

FWIW, this already seems to work on my device (I disabled network connectivity and said something), so the only things that need to change are:

* remove toast when using Google voice input that says voices are being sent online
* ensure that voices are _not_ being sent online
* prefer that voices are not sent online when Gboard is enabled and offline voice transcription is available
* a toggle that disables _online_ transcription 

There are a lot of moving pieces here, but I think that it is worth improving privacy and speed for Pixel owners when available.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1085)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807582

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
