### ISSUE TITLE
FNX-4616 ⁃ [Bug] Align open bookmark behaviour with Firefox desktop

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#10837]
## Steps to reproduce
From an open page:

* Three dot menu
* Bookmarks
* Select a bookmark

### Expected behavior
Bookmark opens in existing tab, as it does in Firefox Desktop.

### Actual behavior
Bookmark opens in new tab.

### Device information
* Android device: Moto E5, Android 8
* Fenix version: Nightly 200519 06:00 (Build #21400606)

**Comment by cadeyrn** [comment]
There was already an issue about this last week where it was confirmed that this is the expected behaviour: #10645.

**Comment by kglazko** [comment]
Closing due to duplicate and confirmation of expected behavior.
