### ISSUE TITLE
FNX-4622 ⁃ Homescreen page shortcuts are opened in Custom tabs and in Fenix after migration

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#10844]
### Preconditions
Have Fennec installed.

### Steps to reproduce
1. Add a few page shortcuts using Fennec;
1. Replace Fennec with Fenix;
1. Tap on the any of the homescreen shortcuts added in step 1;
1. Open Fenix.

### Expected behavior
The homescreen shortcuts are opened in Fenix.

### Actual behavior
The homescreen shortcuts are opened both in custom tabs and Fenix.

###Device information

* Android device: Huawei MediaPad M3 Lite 10 (Android 7.0)
* Fenix version: Beta migration 2 build 03/19

**Comment by ebalazs-sv** [comment]
Verified as fixed on the latest Nightly Migration Build 2015742513 GV 78, from 5/26, with Nexus 5 (Android 6.0.1), Motorola Moto G6 (Android 8), Pixel 2 (Android 9).
The migrated homescreen page shortcuts are opened in Fenix when tapped.
I will move this to Done. Thanks!

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration build 5.1.0-beta.2 with Motorola Moto G6 (Android 8).

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta Migration Build 5.1.0-beta.3 with Motorola Moto G6 (Android 8), Google Pixel 3XL (Android 9), Huawei MediaPad M3 lite (Android 7).
The homescreen shortcuts are opened in Fenix in a new tab.
