### ISSUE TITLE
Want to be able to use different scaling ratios for different websites

### ISSUE THREAD

**Issue by cv0cv0** [mozilla-mobile/fenix#10841]
Just like the latest version of Safari. Each website has a different font size and a different required scaling ratio.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1096)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813225

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
