### ISSUE TITLE
FNX-4619 ⁃ [Bug] Unable to view youtube comments

### ISSUE THREAD

**Issue by Sgt-Miller** [mozilla-mobile/fenix#10840]
## Steps to reproduce
Go to a YouTube video (in browser, not in app).

Scroll down and click on comments

### Expected behavior
It expands and shows the comments

### Actual behavior
Nothing happens or a random video from suggestions starts playing

### Device information
Lenovo note 8

* Android device: 8
* Fenix version: latest firefox preview nightly from play store build 21360611

Ps : long pressing to paste doesn't work in this github issue box. Was trying to paste the full version number.

**Comment by cadeyrn** [comment]
Sounds like #10720.

**Comment by LaurentiuApahideanSV** [comment]
The issue has already been reported here: #10720 . I will close this issue as it will be handled there.
