### ISSUE TITLE
[Bug] [PWA] Some sites do not install PWA with right favicon while favicon is ok as "Top Site"

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#10846]
## Steps to reproduce
* Navigate to https://media.interieur.gouv.fr/deplacement-covid-19
* Add site as "Top site" in Fenix and check that the favicon is on the Top Site shortcut
![image](https://user-images.githubusercontent.com/218971/82656344-e5b73900-9c23-11ea-9be9-af36a9fe063c.png)
* Install site as PWA 

### Expected behavior
The shortcut on device home screen has the same favicon as the "Top Site"

### Actual behavior
The shortcut on device home screen has a default favicon with the initial letter M

### Device information
* Android device: Redmi Note 7 MIUI 11/Android 9
* Fenix version:  #2015741747

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1105)

**Comment by NotWoods** [comment]
It seems like this site doesn't have a valid manifest, so we shouldn't allow it to be used as a PWA.

**Comment by dlecan** [comment]
@NotWoods I can confirm the described behaviour on Fenix 84.1.1 (release)
The Manifest is valid, according to https://manifest-validator.appspot.com/

**Comment by NotWoods** [comment]
The icon paths are invalid in the site's manifest - they point to 404s.

The icons appear to be located in `/attestation-couvre-feu-covid-19/`, but the manifest is located in `r/attestation-couvre-feu-covid-19/favicon/`. As icon paths are relative to the manifest path, icons are loaded from the favicon folder and fail to load.

**Comment by sflorean** [comment]
I was able to reproduce this issue following the steps, but with a different results:
- The PWA icon is displayed correctly
- The top site icon is "M" but after closing/reopening the browser, the icon is updated.
Environment: latest Nightly, LG G7 Fit (Android 8.1)

**Comment by klint** [comment]
The issue is still happening to me on the latest nightly, as described in the fist post (top site favicon is ok, but installed app is only a M char. )
