### ISSUE TITLE
FNX-4787 ⁃ Disable/Re-enable Tracking Protection

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1084]
## User Story
As a user, I want to be able to disable (or re-enable) tracking protection globally, so I can have an unbroken browsing experience and have control over how I view content on the web.

## Dependencies
* UX #1064 

### Acceptance Criteria (Added by PM)
I can access site controls for TP
I can modify site controls so TP is disabled or enabled.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the latest build. 
Devices: Galaxy Tab 3 (Android 8.0), HTC 10 (Android 8.0), HTC Desire 820 (Android 6.0.1)
