### ISSUE TITLE
FNX-4634 ⁃ Tab Tray - Update tab tray colors for private mode

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10859]
After moving to the drawer, we discovered that the tab tray colors reflected the current theme, regardless of looking at private or regular tabs.  In speaking with @topotropic, we decided that we should reflect the dark or light theme only.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200529-130639](https://user-images.githubusercontent.com/51314259/83248485-cc773500-a1ad-11ea-96ea-c53e42982dbf.gif)
