### ISSUE TITLE
FNX-4788 ⁃ Tracking protection for Cryptomining and Fingerprinting

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1085]
## User Story
As a user, I want to be able to be protected from Cryptomining and Fingerprinting so I can browse safely and securely.

### Acceptance Criteria
I am protected from Cryptomining and Fingerprinting by default.
I can disable Tracking Protection for cryptomining and fingerprinting

**Comment by vesta0** [comment]
GV bug for adding protection against Cryptomining and Fingerprinting: https://bugzilla.mozilla.org/show_bug.cgi?id=1530789

**Comment by Amejia481** [comment]
In AC we already provide an api for that `TrackingProtectionPolicy`:

You can select from specific policies like [Cryptomining and Fingerprinting](https://github.com/mozilla-mobile/android-components/blob/a2e8e4f6d4ddc605e03ca53acdb1d2d4b9eb6609/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt#L119):

```kotlin
TrackingProtectionPolicy.select(CRYPTOMINING, FINGERPRINTING)
```

Or just use one of the [grouped policies](https://github.com/mozilla-mobile/android-components/blob/a2e8e4f6d4ddc605e03ca53acdb1d2d4b9eb6609/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt#L164) like:
```kotlin

// AD + ANALYTICS + SOCIAL + TEST + SAFE_BROWSING_ALL
TrackingProtectionPolicy.recommended()

// RECOMMENDED + CRYPTOMINING + FINGERPRINTING + CONTENT
TrackingProtectionPolicy.all()

// NONE
TrackingProtectionPolicy.none()
```

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by vesta0** [comment]
Will add acceptance criteria to main ticket.
