### ISSUE TITLE
FNX-4633 ⁃ [Bug] Unable to backup Ublock Origin settings to file

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#10857]
## Steps to reproduce
Install Ublock Origin > Change some settings, add filters etc. > back in Ublock⁰ dashboard - Settings, select "backup to file"

### Expected behavior
Tapping "Backup to file" asks to download a .txt file with the user's settings

# Actual behavior
No download is provided and the "last backup" time and date is updated to the current time.

### Device information
* Android device: Samsung  Galaxy S8+, Android 9
* Fenix version: 5.1.0-beta.1 (Build #2015741187) + Nightly 200522 06:01 (Build #2015741747)

**Comment by csadilek** [comment]
This is a regression, unfortunately, as https://bugzilla.mozilla.org/show_bug.cgi?id=1626349 had to be re-opened.

**Comment by csadilek** [comment]
This works for me again in latest Nightly (200605 06:01). QA, please verify :).

**Comment by astarq** [comment]
Thank you, it works for me as well! I rejoice!

**Comment by astarq** [comment]
Thats weird, Nightly crashes after the download is completed. At least I can save settings now 😌

**Comment by csadilek** [comment]
Ah yes, we noticed that we still have a problem on Android versions < Q. Patch in progress: https://github.com/mozilla-mobile/android-components/issues/7279

**Comment by astarq** [comment]
Great. I see no problem in closing this then

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200619-135740](https://user-images.githubusercontent.com/51314259/85125904-17c4b680-b235-11ea-82fa-99f08b8037fd.gif)
