### ISSUE TITLE
FNX-4631 ⁃ [Bug] Crash when downloading while having pwa in background

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10855]
## Steps to reproduce
I don't have the exact steps but while doing the below steps i encounter it.:

1. Have daleharvey.github.io/testapp installed as pwa.
1. Open the pwa and tap in the "and Paste" field.
1. Put the pwa in the background.
1. Go to youtube.com.
1. Long tap on a video's summary/title and choose option Download link.
1. Redo step 5
1. Close app.
    1. Expected behavior
The html file of the page is correctly downloaded.
    1. Actual behavior
Crash is present
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 5/22
[Crash-When using PWA.txt](https://github.com/mozilla-mobile/fenix/files/4668806/Crash-When.using.PWA.txt)

**Screenshot from about:crashes**
![Screenshot](https://user-images.githubusercontent.com/49859863/82683485-c6d39980-9c59-11ea-84d4-02eb92844af1.jpg)UNITO-UNDERSCORE!20200522-174237!UNITO-UNDERSCORE!Firefox Nightly-edited2!

**GIF**
![20200522-181804](https://user-images.githubusercontent.com/49859863/82683357-8ecc5680-9c59-11ea-8371-53f4da12de57.gif)

**Comment by Amejia481** [comment]
I this will be addressed when this pr lands https://github.com/mozilla-mobile/android-components/pull/6954

**Comment by kglazko** [comment]
Looks like the above PR was merged on the AC side @Amejia481 - should we have QA look at this?

**Comment by Amejia481** [comment]
Thanks @kglazko, yes it should be ready for QA :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200529-095236](https://user-images.githubusercontent.com/51314259/83230909-4221d780-a193-11ea-9168-596de1723063.gif)
