### ISSUE TITLE
FNX-4630 ⁃ Add a "Close all tabs" in the new tab tray

### ISSUE THREAD

**Issue by FenixRevival** [mozilla-mobile/fenix#10853]
User story: I want to quickly close all opened tabs in the new tab tray.

Step to reproduce:

* Open a few numbers of tabs
* Click on the tab tray
* All the tabs are showing
* Have a little button near [private] : close all opened tab
* (optional) have confirmation window

Firefox Nightly 200522

**Comment by boek** [comment]
Fixed https://github.com/mozilla-mobile/fenix/pull/10869
