### ISSUE TITLE
[Bug] Cannot re-access storage in order to upload a picture in same session

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10852]
## Steps to reproduce
1. Open browser and navigate to smaller-pictures.appspot.com .
1. Tap on the icon from the bottom right corner.
1. Tap back in order to not upload a picture.
1. Tap again on the same icon.
    1. Expected behavior
Local storage opens in order to upload a picture.
    1. Actual behavior
Nothing happens.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL
* Fenix version: Nightly 5/22

**GIF**
![20200522-143808](https://user-images.githubusercontent.com/49859863/82666302-4f444100-9c3e-11ea-8a9e-e1de7e40e218.gif)
Note: After closing and reopening the app the upload from storage can be made.

**Comment by Augures01** [comment]
You can reproduce same behavior when
1. Disable storage permission in system settings for Fenix
2. Try to restore settings for uBlock from file
3. Allow storage permission in prompt
4. Choose backup file
5. No popup info window and you can't restore settings
6. Refresh page
7. Try restore from file
8. Popup confirmation window appears and you can restore settings

Repeat from step 1...
