### ISSUE TITLE
FNX-4640 ⁃ Tab Tray - Implement Three-Dot Menu

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10865]
We need to restore the three-dot functionality to the tab tray.  Menu items should be:

* Save to collection
* Share all tabs
* Close all tabs

Functionality was removed with: https://github.com/mozilla-mobile/fenix/pull/10835

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200529-133556](https://user-images.githubusercontent.com/51314259/83253551-d3a24100-a1b5-11ea-97bf-0177bb6d49c5.gif)
