### ISSUE TITLE
FNX-4639 ⁃ Tab Tray - Implement Snack bar & Undo for closing Tabs

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10864]
With the new tab drawer, we no long show the snackbar after closing a tab.  We should restore this functionality.

**Comment by liuche** [comment]
Filed #10986 for restoring tabs in-place, to match current tabs tray behavior and make "Undo" actually feel like "undoing"

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video Normal Browsing
![20200529-120759](https://user-images.githubusercontent.com/51314259/83242776-9a61d500-a1a5-11ea-9fd4-95b79dbf28dd.gif)

► Video Private Browsing
![20200529-120859](https://user-images.githubusercontent.com/51314259/83242839-ba919400-a1a5-11ea-809a-1ca856c7a57d.gif)
