### ISSUE TITLE
[Bug] Tab tray "default" icon looks like a placeholder

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10874]
## Steps to reproduce
1. Open tab tray

### Expected behavior
The icon for "default" isn't a box that looks unfinished. Reference browser and Fennec uses a better icon here. 

### Actual behavior
The icon is a box that looks like a placeholder. 

![image](https://user-images.githubusercontent.com/152493/82717794-80d40100-9c6c-11ea-9a30-5223925e321c.png)

### Device information
* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by liuche** [comment]
@topotropic is this something that we want to do before release? if so please move to the bugs for release column, otherwise can leave here.

**Comment by cadeyrn** [comment]
I want to add that since this issue was filed the label ("Default", "Private") was removed so it's even more an issue now. Now it looks like a checkbox.

**Comment by topotropic** [comment]
I hope we can fix this issue through https://github.com/mozilla-mobile/fenix/issues/10849

**Comment by topotropic** [comment]
I consider this fixed with https://github.com/mozilla-mobile/fenix/issues/10849
