### ISSUE TITLE
Add "open in background tab" for bookmarks in the bookmarks manager

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#10879]
### What is the user problem or growth opportunity you want to see solved?
The addition of a < Open in background tab > option next to  < Open in new tab > and < Open in private tab > in the Context Menu which appears when a user selects a bookmark(s) from the Bookmark Manager. 

### How do you know that this problem exists today? Why is this important?
When a user has many bookmarks, these can get hidden in subfolders, or just lost in large folders. While browsing these, a user might see one bookmark that they want to open, but they still haven't found the bookmark they were looking for - currently, the user would need to open that bookmark then navigate back to the same subfolder and scroll point - therefore they would benefit from this feature

### Who will benefit from it?
Everyone that uses bookmarks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1148)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812712

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
