### ISSUE TITLE
FNX-4648 ⁃ Tab Tray - Show "Your open tabs will be here" Message

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10877]
When there are no open tabs, we should show the empty tabs message in the tab tray drawer.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_1rsz_screenshot_20200529-114300](https://user-images.githubusercontent.com/51314259/83240784-88cafe00-a1a2-11ea-8a7d-548bbaa3bc99.png)
