### ISSUE TITLE
[Bug] Crash when profiling on XT1031 (logcat attached)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10870]
## Steps to reproduce
1. Connect to device from Firefox desktop (nightly on Linux)
1. Start to profile

### Expected behavior
Profile begins, can collect profile. 

### Actual behavior
Fenix crashes as profiler starts up.

See crash log: https://gist.github.com/yoasif/6ad4e654c02ae17083e0f33d727bc4de

### Device information
* Android device: Moto G XT1031
* Fenix version: latest nightly

**Comment by fluffyemily** [comment]
It looks like this might be the relevant stack: 

```
05-22 17:28:48.543 E/art     (13090): Throwing OutOfMemoryError "Failed to allocate a 536870924 byte allocation with 11475311 free bytes and 79MB until OOM"
05-22 17:28:48.544 W/System.err(13090): java.lang.OutOfMemoryError: Failed to allocate a 536870924 byte allocation with 11475311 free bytes and 79MB until OOM
05-22 17:28:48.544 W/System.err(13090): 	at org.mozilla.gecko.GeckoJavaSampler$SamplingRunnable.<init>(GeckoJavaSampler.java:5)
05-22 17:28:48.544 W/System.err(13090): 	at org.mozilla.gecko.GeckoJavaSampler.start(GeckoJavaSampler.java:6)
05-22 17:28:48.544 W/System.err(13090): 	at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
05-22 17:28:48.544 W/System.err(13090): 	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:91)
```

It doesn't help that is also looks like ACs crash reporting is crashing too.

**Comment by snorp** [comment]
Yeah, I would try not profiling the Java UI thread if you can. You can uncheck that in the settings when you attach.

**Comment by boek** [comment]
@yoasif could you try profiling without the Java UI thread?

**Comment by yoasif** [comment]
@boek I see "Java", nothing about "Java UI" in `about:debugging`.

Is it "Java"?

**Comment by snorp** [comment]
yeah, "Java" is the UI thread.

**Comment by yoasif** [comment]
I was able to successfully capture a profile when disabling Java.

**Comment by mstange** [comment]
This should be fixed now that [bug 1639630](https://bugzilla.mozilla.org/show_bug.cgi?id=1639630) has trickled into Fenix builds. There is also [bug 1641119](https://bugzilla.mozilla.org/show_bug.cgi?id=1641119) on handling the OutOfMemory error more gracefully.
Asif, can you check again? If not, can you comment on bug 1641119?

**Comment by yoasif** [comment]
It still crashes @mstange.

**Comment by yoasif** [comment]
This seems to work now.
