### ISSUE TITLE
FNX-4644 ⁃ [Bug] Inconsistent display of address bar in tab tray depending on address bar position

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#10871]
## Steps to reproduce
1. Set address bar to top
1. Open tab tray
1. Set address bar to bottom.
1. Open tab tray

### Expected behavior
The address bar should be visible when the address bar is set to bottom and tab tray is opened. 

### Actual behavior
The address bar is not visible when address bar is in bottom mode. 

Top:

![image](https://user-images.githubusercontent.com/152493/82711745-4b231e00-9c54-11ea-9e76-ff9dc1eb95b0.png)

Bottom:

![image](https://user-images.githubusercontent.com/152493/82711781-67bf5600-9c54-11ea-8164-fa047f989c23.png)

### Device information
* Android device: Moto G XT1031
* Fenix version: latest nightly

**Comment by ekager** [comment]
You can't use the toolbar anyway at this time, and it adds a ton of complexity to the bottom sheet behavior to show it above the toolbar. I don't think we will do this.

**Comment by yoasif** [comment]
Couldn't the tab tray appear above the android buttons and address bar instead of appearing on a semitransparent layer above the android buttons as currently? @ekager

**Comment by yoasif** [comment]
No one is watching this issue and I'm not sure it really matters.
