### ISSUE TITLE
FNX-4659 ⁃ Fennec migration: Tapping the device back button returns to onboarding migration screen when the "Update complete" is used

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#10885]
## Preconditions:
Have Fennec Beta installed.

## Steps to reproduce
1. Replace Fennec Beta with Fenix Beta;
1. Tap the "Update complete" notification;
1. Tap the device back button;
1. Observe the behavior.
    1. Expected behavior
The app is dismissed.
    1. Actual behavior
The migration onboarding screen is displayed.
    1. Notes:
[Video](https://drive.google.com/open?id=1tEpcD4iqaRaIftrWIweo0eIEy6rQEDTs)
This is reproducible only when the "Update complete" notification is tapped.
When the migration onboarding screen is dismissed by tapping the "Start Firefox" button, this is not reproducible.
Not reproducible on Nightly migration build 9, 02/14 and Beta migration build 1, 02/24
    1. Device information

* Android device: Google Pixel 2 (Android 9); Motorola Nexus 6 (Android 7.1.1);
* Fenix version: Beta migration build 2, 02/27; Nightly migration build 3/3;

**Comment by jonalmeida** [comment]
@ebalazs-sv would it be possible to test this out on a nightly migration build? Since we've tried to fix this bug before, it would be great to know if the fix works fine before we cut a major release build.

**Comment by ebalazs-sv** [comment]
I had tested this on the latest Nightly Migration Build 2015742417 GV 78 with Nexus 5 (Android 6.0.1), Motorola Moto G6 (Android 8), Pixel 2 (Android 9) and the issue is not reproducible.

Tapping the device back button after the "Update complete" notification is used, will exit the app. When reopening Fenix, the onboarding tour is displayed.

I will remove the qa:needed. Thanks!

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration Build 5.1.0-beta.3 with Motorola Moto G6 (Android 8).

**Comment by jonalmeida** [comment]
@liuche it seems the fix for this didn't make it into the beta build, but it landed 8 days ago. I can't find the commit on the 5.1.0 release. 🤔

**Comment by liuche** [comment]
The 5.1 build was cut a couple of weeks ago, so this will go into 5.2. If we wanted this in 5.1 we would have needed to get an uplift flagged for it.

**Comment by jonalmeida** [comment]
Could we have this re-tested on the 5.2 release?

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release Migration 5.2.0 (Build #2015747017), from 6/18 with Motorola Moto G6 (Android 8). 

Tapping the device back button after the "Update complete" notification is used, will exit the app. When reopening Fenix, the onboarding tour is displayed. 

I will remove the qa:needed label.

**Comment by jonalmeida** [comment]
Thanks @ebalazs-sv !
