### ISSUE TITLE
[Bug] Unable to select more than one file in android file manager

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#10883]
## Steps to reproduce
Open any website which allows file sharing, e.g. Instagram.com, send.firefox.com, onedrive.com > try to upload a file using the respective upload button > in the android file manager, select a file > Select another file

### Expected behavior
Both files are now selected

### Actual behavior
The first file is deselected

### More information
Apparently this is a longstanding firefox android bug and was present in Fennec.
Heres a link from a developer asking users to report it: https://crypt.ee/help?article=i-use-firefox-on-android-why-cant-i-select-multiple-files-or-photos-to-upload
Here's a bugzilla link from that article: https://bugzilla.mozilla.org/show_bug.cgi?id=1456557&GoAheadAndLogIn=1

This should be an S1 priority (think that's right) - I'm sure I'm not the only one it's been bugging :unamused: for ages

**Comment by astarq** [comment]
I forgot to name it... 🤪

**Comment by johnozbay** [comment]
I can confirm that this is now fixed, you can now close this! 🎉
Thanks everyone ✌🏻
