### ISSUE TITLE
FNX-4655 ⁃ RegExp, lookbehind assertions

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#10882]
is [ Bug 1367105|https://bugzilla.mozilla.org/show_bug.cgi?id=1367105] implemented on fenix ? if possible provide some info.

**Comment by liuche** [comment]
@leela52452 can you explain what this is, and how you expect to use it? Fenix uses Gecko engine so if Gecko has it, Fenix should have it. However, if there's an API that needs to be exposed, please file in https://github.com/mozilla-mobile/android-components .

**Comment by leela52452** [comment]
hello @liuche 

>  can you explain what this is, and how you expect to use it?

good question. all i know `Notably, Firefox currently does not support lookbehinds, and therefore is not able to perform as many typo fixes as other browsers.` given at [jwb](https://en.m.wikipedia.org/wiki/User:Joeytje50/JWB). see also [some browsers not supporting Regex lookbehinds](https://caniuse.com/#search=lookbehind)
