### ISSUE TITLE
FNX-4663 ⁃ [Bug] Cannot download file from firefox send.

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#10889]
## Steps to reproduce
open and download file
https://send.firefox.com/download/652814b474d44ce8/#oFUR0Dz3Qm9WWyc-L2bnZg

https://i.imgur.com/p3e2FoJ.mp4

### Device information
* Android device: ?
* Fenix version: ?
5.24 pm nightly

**Comment by cadeyrn** [comment]
Duplicate of #3336.
