### ISSUE TITLE
FNX-4790 ⁃ Fenix is OOM killed when playing a podcast

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1088]
## Steps to reproduce
* open a podcast such as http://www.sporkful.com/
* scroll down and play a podcast

### Expected behavior
* podcast plays to completion

### Actual behavior
* Android OOM kills Fenix

### Device information
* Android device: Pixel 3 running Android 9
* Fenix version: March 19th

Playing back the same podcast on Fennec nightly plays to completion.

**Comment by vesta0** [comment]
@sv-ohorvath please confirm this is still an issue.

**Comment by pocmo** [comment]
Preventing that is probably part of the media APIs that we didn't consider for MVP (See AC media project board).

**Comment by sv-ohorvath** [comment]
Bogdan and I tried to reproduce this, on a Pixel and on a Huawei P20. Both worked fine until the screen went to sleep mode and after ~8 mins, the playback was stopped by auto-saving the session and closing the tab. I'm guessing the second part wasn't really planned either?

**Comment by sblatz** [comment]
Sounds like this is blocked on AC?

**Comment by vesta0** [comment]
@sblatz according to this [bug]([url](https://bugzilla.mozilla.org/show_bug.cgi?id=1506957)) we may not need GV work. Could you please investigate?

**Comment by pocmo** [comment]
> Sounds like this is blocked on AC?

Yes, we have a "media"-related AC board here:
https://github.com/orgs/mozilla-mobile/projects/26

**Comment by pocmo** [comment]
Adding QA needed: This is enabled in Nightly builds now. Starting QA process already before enabling it for all builds.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly from 8/23 build 1.0.1934, with Xiaomi MI 8 Lite (Android 9).
