### ISSUE TITLE
[Bug] Links open in new tab

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#10881]
A lot of times especially when using search, if I click on a link it will open in a new tab instead of the current one. I can't find any settings to change this. Normally you would press and hold on a link to get the context menu and choose to open in a new tab.

**Comment by astarq** [comment]
This is usually the choice of the website, not the browser - If you're using Duckduckgo, Bing or Searx, they all have toggles for it. I don't think google does

**Comment by Kreuger** [comment]
I use ddg. I have open links in new tab switched off.

**Comment by Kreuger** [comment]
I use ddg. I have open links in new tab switched off.

**Comment by astarq** [comment]
🤷‍♂️

**Comment by fingerwarrior** [comment]
Clicking on a duckduckgo(ddg) search result opening it in new tab, with the setting turned off in ddg. I can live with that, no biggie.

If I search something in private browsing though, clicking on a ddg result will give me a dialog saying *"Open in app? Your activity may no longer be private"*, the URL, and two options, *Cancel*, which just cancels the prompt and does not open the result at all, and *Open*, which will open the result in normal session, out of the Private browsing. The only way to get around this is to force open all links in a new Private tab by long press and tapping that option.

Running latest build available to me on Play store (200523 06:00 Build#21440607).

Fenix is the default app for opening links.

![ScreenRecord-2020-05-24-10-56-54](https://user-images.githubusercontent.com/8464592/82746498-057a6880-9dae-11ea-9f10-8962a153839d.gif)

**Comment by Kreuger** [comment]
It also does it when I search for stuff on other websites. Like if I search for a song on Ultimate Guitar. When I pick a guitar tab to view, it opens in a new Firefox tab.

**Comment by Kreuger** [comment]
And I have a somewhat related issue in that when I hit the back button on those pages, it will close the browser instead of going back to the previous tab or the list of open tabs.
