### ISSUE TITLE
FNX-4662 ⁃ Customize top sites on homescreen

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#10888]
### User Story
As a user, I want to be able to choose the number/type of top sites visible on my homescreen, so I can personalize my homescreen based on my needs.

### Acceptance Criteria
I can customize how my top sites show up on the homescreen.

UX: please revise the Acceptance Criteria to make them more specific once you have determined the following:

* Do users want the option to disable all top sites (or just the automatically populated ones since the can delete the 3 default top sites manually and they aren't too intrusive)?
* Do users want to choose how many rows of top sites to display on homescreen?

**Comment by brampitoyo** [comment]
Assigning this issue to @topotropic

**Comment by liuche** [comment]
Will timebox and work with Nicole.
