### ISSUE TITLE
FNX-4669 ⁃ Auto password generator similar to desktop version

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#10899]
please add the auto password generator in fenix similar to firefox desktop version.

**Comment by Dunexus** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/5661

**Comment by sheikh-azharuddin** [comment]
> Dupe of #5661

There is no update on that thread since Oct 2019 😕

**Comment by lindongbin** [comment]
Many websites cannot automatically fill in passwords, I think the problem of manually selecting passwords in the input box should be solved first

**Comment by kglazko** [comment]
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/5661. Please continue discussion there.

**Comment by sheikh-azharuddin** [comment]
You cannot close this without any proper update? That case is not updated since October and I don't see any progress.....for the desktop version you are advertising about new password generator feature too much yet this is missing in the android version!

**Comment by sheikh-azharuddin** [comment]
> Closing as a duplicate of #5661. Please continue discussion there.

You cannot close this without any proper update? That case is not updated since October and I don't see any progress.....for the desktop version you are advertising about new password generator feature too much yet this is missing in the android version!
