### ISSUE TITLE
FNX-23 ⁃ Set Up Beta Channel

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#109]
This bug is to keep track of the work needed to get Fenix into Beta. We are going ship the Beta as a separate app with a name TBD and app identifier `org.mozilla.fenix_beta`.

All bugs for Beta can be found under https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+is%3Aissue+label%3Abeta+label%3Amust

**Comment by Sdaswani** [comment]
File here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Release%20Engineering

**Comment by vesta0** [comment]
Won't set up a separate Beta channel for MVP

**Comment by liuche** [comment]
We've made a beta channel on Google Play, but are waiting for some releng cycles to actually get it hooked up to our release build process.

ETA end of Oct. At that point we'll also need to start making 2 release builds, one for the release channel, and one for the beta channel (which will allow QA to test for 2 weeks while it bakes.)

**Comment by liuche** [comment]
Beta channel has been live for 3.0.
