### ISSUE TITLE
FNX-4673 ⁃ [Bug] Closing a single tab via the tab tray leaves the tab in a semi-closed state

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#10905]
## Steps to reproduce
1. Activate the tab tray
1. Open a single website, thus having a single tab in the list
1. Open the tab tray and close the tab

### Expected behavior
The home screen is displayed.

### Actual behavior
The last tab is still visible but not interactive anymore, except for the bottom bar still reacting to scroll events. Any media playback is stopped, in private mode the notification for closing the open private tabs is also removed. Pressing the back button on the device, deactivating the tab tray or backgrounding fenix and open it up again makes the home screen display again.

![fenix](https://user-images.githubusercontent.com/42788925/82837291-ede3d280-9ec8-11ea-907d-a97ae9c1161c.png)

### Device information
* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version:
Nightly 200525 06:01 (Build #2015742321)
43.0.20200520190033, 3aa8dc692
GV: 78.0a1-20200520033931
AS: 0.59.0

**Comment by AndiAJ** [comment]
As per [this fix](https://github.com/mozilla-mobile/fenix/issues/10998#issuecomment-638011105) the above mentioned issue is no longer reproducible  on the latest **`Nightly Build 200603 from 6/3`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

@hwinnemoe - Please review and in case you still encounter any issues please re-open☺️

**Comment by hwinnemoe** [comment]
> @hwinnemoe - Please review and in case you still encounter any issues please re-open☺️

I do not see this anymore on my device, thanks  :)
