### ISSUE TITLE
FNX-4672 ⁃ Customize the 3 dot menu in a horizontal grid layout

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#10901]
The current 3 dots menu is becoming too long if number of add ons added are too many and it kinds of block the web page view.. intrusive.... Please Customize the 3 dot menu in a horizontal grid layout with scroll similar to yandex browser to accommodate more items in an elegant way .

**Comment by psymoon** [comment]
Dupes to https://github.com/mozilla-mobile/fenix/issues/8319.
