### ISSUE TITLE
Web Push notifications should be more noticeable

### ISSUE THREAD

**Issue by grigorig** [mozilla-mobile/fenix#10908]
### What is the user problem or growth opportunity you want to see solved?
Push notifications should get the attention of users. Android has various ways to do this: heads-up notifications, notification LEDs and vibrations. Notification can also be displayed on the lockscreen.

Unfortunately, Fenix right now uses extremely conservative notification settings (no sound, vibration, or notification light), so that notifications are unlikely to be noticed by users and in some configurations are not even displayed on the lockscreen.

### How do you know that this problem exists today? Why is this important?
I'm working on a web application that utilizes push notifications. Fenix' current implementation is practically useless: I want to notify users for auditing purposes and give them a chance to react to specific security events. Users need to react quickly to these events, but that obviously won't work if they won't ever notice the notifications.

### Who will benefit from it?
My use case is quite typical, so I presume everyone that wants or needs push notifications, both web developers and end users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1188)

**Comment by grigorig** [comment]
Here's a simple recommendation after reviewing the implementation in `app/src/main/java/org/mozilla/fenix/session/SessionNotificationService.kt`

* The visbility of notifications should be changed from SECRET to PRIVATE. SECRET notifications are not displayed on lock screens at all if users have set the lock screen to "hide sensitive content", which is a common setting. The default is PRIVATE and it will show a notification without content in this case, which is more reasonable.
* Firefox should add default sound, vibration and/or notification light settings to new notifications. Maybe not all of them if that is considered too annoying, but none is too conservative.

**Comment by grigorig** [comment]
This is basically a regression compared to Fennec, so I don't think the label is fitting.

The changes required to get notifications work similarly to Fennec are really simple. Would it be acceptable at this point if I submit a PR?

**Comment by TitanNano** [comment]
On android 8+ users can adjust all notification settings by them self. On android 7 and lower though it would be better to have more reasonable settings as they can not be changed by the user.

**Comment by grigorig** [comment]
The question is what's reasonable, of course. I think most apps actually enable everything (sound, lights and vibration), and that is usually considered reasonable.

However, I don't think it's controversial to simply restore the behaviour of Fennec.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809276

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
