### ISSUE TITLE
FNX-4671 ⁃ Change WebView

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#10902]
Add option to change webview or fix the webview itself. I don't like your gecko webview because for app based url it never opens the url in the app when viewed in webview unlike chrome/android default webview which immediately open the link in respective app on clicking it inside the webview page. 

Currently in fenix to open the link in the respective app... first click the link (let's say from telegram app) it will open in the Firefox webview, then we have to click open in browser and the we have to access the 3 dot menu and click open in app. So process is too tiresome. Maybe the webview can be fixed so that when clicking open in browser it should open directly in the respective app just the way like Chrome/Android webview works.

**Comment by NotWoods** [comment]
This is a feature called "Custom tabs", and the specific behaviour you're having trouble with can be switched off! Open "Settings", then under "Privacy and security" turn on the "Open links in apps" switch. From then on, all links will open in the native app by default.

**Comment by sheikh-azharuddin** [comment]
Did you read my issue with the example? Or simply closed the issue without reading? Why it gets difficult for you people to accept?

**Comment by st3fan** [comment]
Let's leave this open until we understand the usage pattern.

**Comment by st3fan** [comment]
@sheikh-azharuddin I don't have What's App to try to reproduce this situation. Is there another app where the same behaviour happens?

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin I don't have What's App to try to reproduce this situation. Is there another app where the same behaviour happens?

What about telegram app? Let me give you one example for better understanding-
I have some deals group subscribed in telegram.. they post Amazon and other web site daily deals..when I click the link it opens in firefox webview instead of amazon app even though open links in apps selected. Now to open the link in the app I have to click open link in firefox nightly in webview and then in firefox browser click 3 dot menu and select open link in app.... So you see here data is wasted and also takes time and effort to open a link in respective app.... however this behaviour is different in chrome/android webview. When I click the link it opens in chrome web view but on clicking "open in firefox nightly" it opens directly in the Amazon app without going to the browser.

To reproduce the issue make sure to disable chrome app... I mean if you we are going to make firefox as default browser why use chrome at all so I have disabled it.

**Comment by sheikh-azharuddin** [comment]
Attaching screenshot of chrome and firefox webview...the behaviour is different when clicking open link in browser/open link in firefox nightly in webview....seems more refinement required in firefox webview.
![Firefox webview](https://user-images.githubusercontent.com/58127841/82833996-4312ea80-9eaf-11ea-86d9-097f2cc45c2a.jpg)
![Chrome webview](https://user-images.githubusercontent.com/58127841/82833998-460ddb00-9eaf-11ea-890c-f09caee34fa4.png)

**Comment by rocketsroger** [comment]
@sheikh-azharuddin please review https://github.com/mozilla-mobile/fenix/issues/10906 to confirm that it will fix your issue.

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin please review #10906 to confirm that it will fix your issue.

Thanks Roger and Team.
Yes this will fix my issue 😊

**Comment by rocketsroger** [comment]
> > @sheikh-azharuddin please review #10906 to confirm that it will fix your issue.
> 
> Thanks Roger and Team.
> Yes this will fix my issue 😊

Thanks!  I'll close this issue and track with https://github.com/mozilla-mobile/fenix/issues/10906.

**Comment by sheikh-azharuddin** [comment]
Thanks for adding the feature so fast ...thank you Roger and firefox team♥️😊
