### ISSUE TITLE
FNX-4674 ⁃ Add Open in app option in custom tab

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#10906]
### What is the user problem or growth opportunity you want to see solved?
Currently if the user decides to open the link in a custom tab, they will first have to open the tab in non custom tab Firefox.  Then tap on the toolbar menu to access the "Open in app" action.

### How do you know that this problem exists today? Why is this important?
Issue opened by contributor.

### Who will benefit from it?
Users who frequently reopens links in custom tabs in native apps.

**Comment by rocketsroger** [comment]
Open due to https://github.com/mozilla-mobile/fenix/issues/10902

**Comment by sheikh-azharuddin** [comment]
Thanks for adding the feature...this was so fast😃😊🤩
![Screenshot_20200527-204554](https://user-images.githubusercontent.com/58127841/83039418-af1b5d00-a02d-11ea-82d9-430ae65177c4.jpg)

**Comment by rocketsroger** [comment]
> Thanks for adding the feature...this was so fast😃😊🤩

Thank you for bringing this to our attention.  💯
