### ISSUE TITLE
FNX-4668 ⁃ Security information of the webpage

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#10900]
Please add more security information about the websites such as certificate expiry date , cipher suite details. The current details shown while clicking the lock icon is too less. Maybe a new item can be added under the 3 dot menu  "Security Info/View Website Security" and on clicking that it will reveal all the security details.

**Comment by Dunexus** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/8400

**Comment by mcarare** [comment]
Thank you for the report! This is already on our to do list. Closing this as duplicate of #8400.
