### ISSUE TITLE
[CI] toolchain-linux64-android-gradle-dependencies task is extremely slow

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#10910]
`toolchain-linux64-android-gradle-dependencies` is currently taking 40-60 minutes to run on most CI runs triggered by PR pushes that I've noticed.

In Github UI for the PR, this manifests itself as every single task is `Queued`.

This is quite bad, especially combined with intermittent UI test failures we sometimes see. I've been trying to land a PR for a few days now unsuccessfully (https://github.com/mozilla-mobile/fenix/pull/10812), and the cycles are just so painfully slow.

cc @JohanLorenzo @Callek

**Comment by grigoryk** [comment]
PR in which I bumped into this modified `buildSrc/src/main/java/Dependencies.kt`, which is one of the triggers for rebuilding the toolchain, as defined in `taskcluster/ci/toolchain/android.yml`.

The problem mainly arises when two things happen at once - toolchain task is re-triggered and is slow, and UI tests are flaky and fail. In that situation, things are quite painful as it takes forever to get through the CI cycles, as every re-run needs to eat the cost of the toolchain task.

Some kind of a per-PR cache would help here, it seems. Either a gradle build cache, or the TC cache? I'm not sure how well cache boundaries are defined in practice.

**Comment by pocmo** [comment]
> This is quite bad, especially combined with intermittent UI test failures we sometimes see. I've been trying to land a PR for a few days now unsuccessfully (#10812), and the cycles are just so painfully slow.

I agree that this is painful. I think the worst offender here are the intermittent UI test failures though. We need to get rid of those as best as we can.

We spoke about the build cache yesterday. Another thing I am looking at is reducing our build variants. This should improve the time of the toolchain task too since there will be less variants for it to build/test just to get all dependencies cached.

**Comment by JohanLorenzo** [comment]
I agree with @pocmo, reducing the number of variants will reduce the time taken by this toolchain task. 

> PR in which I bumped into this modified buildSrc/src/main/java/Dependencies.kt, which is one of the triggers for rebuilding the toolchain, as defined in taskcluster/ci/toolchain/android.yml.

👍 

Out of curiosity how often does the team change `Dependencies.kt`?

**Comment by grigoryk** [comment]
@JohanLorenzo can we avoid running the toolchain task on PR pushes?
I vaguely recall that we only cache its outputs for pushes to master, which means IIUC that running it for PR pushes isn't really useful?

**Comment by pocmo** [comment]
That defeats the purpose though, if you run the PR without caches then it needs to download the dependencies and again fails frequently because jcenter and the network are wonky.
