### ISSUE TITLE
[UI Tests] Consider running UI tests using a non-debug build type

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#10914]
Currently we're running UI tests using a debug build type.

It's possible that the application could behave differently when built as `debug`. I ran into this in https://github.com/mozilla-mobile/fenix/pull/10812, where some minor UI will change depending on the build type.

We're shipping non-debug types, so it'll be nice to have the UI tests run against builds that closely mimic final artifacts. Non-debug builds may _probably_ end up running faster in tests, as well.

Currently, we're using `isDebug` check to:

* disable crash reporting
* disable telemetry
* make sure ADJUST_TOKEN isn't set
* enable LeakCanary (and allow toggling it in Preferences)
* skip displaying real `build date` in About screen (speeds up local builds, that's #10812)

**Comment by grigoryk** [comment]
cc @rpappalax - please consider this through a lens of "@grigoryk doesn't know much about UI tests" :)

**Comment by AaronMT** [comment]
@grigoryk We are discussing this this morning. Work is underway to create a test specifically for nightly builds (#10270) however, the objective of these tests is to ensure some sense of stability on master branch. 

Thanks for your comment, this is a good insight that we will further dive into.
