### ISSUE TITLE
FNX-4792 ⁃ Search/URL bar clear button is called "close" in TalkBack

### ISSUE THREAD

**Issue by eeejay** [mozilla-mobile/fenix#1091]
## Steps to reproduce
1. With TalkBack on, start typing a term/url in the homscreen
1. Navigate to right X button.
1. TalkBack calls it "close button"

### Expected behavior
Talkback should call it "clear button"

### Actual behavior
It says "close button". If you double tap to activate it, TalkBack says "cleared text", which is good but obviously confusing when activating a button called "close".

### Device information
* Android device: Pixel
* Fenix version: Nightly

![screen](https://user-images.githubusercontent.com/5764/54649511-bf1dd100-4a67-11e9-9726-5ef831753e87.png)

**Comment by pocmo** [comment]
This string may be defined in AC: https://github.com/mozilla-mobile/android-components/issues/2488

**Comment by pocmo** [comment]
Was fixed in AC.
