### ISSUE TITLE
Failing SettingsPrivacyTest tests when selecting existing session

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#10915]
From the fix in https://github.com/mozilla-mobile/android-components/pull/7054 that finds and selects an open session, some existing functionality with private browsing seems to have changed that is not obvious to me how it should be fixed.

Disabling the following tests in `SettingsPrivacyTest` for now:

* `openExternalLinksInPrivateTest`
* `launchPageShortcutInPrivateModeTest`

cc: @Vishwa-Mozilla @ekager

**Comment by sv-ohorvath** [comment]
Assigning myself to check if I can fix and re-enable the tests.

**Comment by sv-ohorvath** [comment]
The tests had one webpage pre-loaded and then opened the same link from an external source or home-screen shortcut, so the app was selecting the existing session instead of what the test was expecting it to do: open a new private/normal session.
