### ISSUE TITLE
[Bug] No <title> shown with URL redirections

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#10916]
## Steps to reproduce
1. Open a thread from your github notifications
1. Go to main menu (click on the number of tabs you have opened, in the toolbar)
    1. Expected behavior
The title is shown
    1. Actual behavior
No title is shown
    1. Device information

* Android device: 9
* Fenix version: 5.0

### Evidence
On Fenix, from github notifications: ![from](https://user-images.githubusercontent.com/58657617/82886851-6b4e2800-9f47-11ea-90b9-7a2cd7b52f98.png)UNITO-UNDERSCORE!github!UNITO-UNDERSCORE!notifications!

On Firefox desktop, from github notifications: 
![title](https://user-images.githubusercontent.com/58657617/82886898-7e60f800-9f47-11ea-88c5-1397068498a2.png)UNITO-UNDERSCORE!desktop!UNITO-UNDERSCORE!from!UNITO-UNDERSCORE!notifications!
(— Mozilla Firefox at the end is done by the OS).

On Fenix, NOT from notifications (from the list of issues, or direct link): 
![normal](https://user-images.githubusercontent.com/58657617/82886973-9afd3000-9f47-11ea-9214-59c2a53e1b85.png)UNITO-UNDERSCORE!page!
That's what we expect to see

Source code on desktop, title tag, from notifications or not:
![title](https://user-images.githubusercontent.com/58657617/82886994-a2bcd480-9f47-11ea-85c3-fde44b2f3683.png)UNITO-UNDERSCORE!source!

**Comment by B0pol** [comment]
I've noticed on desktop, the link is 
`https://github.com/notifications` 
-> `https://github.com/account/repo/issueOrPull/number?notification_referer_id=aNotificationRefererId` 
-> `https://github.com/account/repo/issueOrPull/number#comment-id-aCommentId`

When you press back button in history, it goes directly to `github.com/notifications`

It seems like the redirection is the issue.

**Comment by B0pol** [comment]
It's not only GitHub, it also happens on Wikipedia, and it's also about redirections.
Onions is redirected to Onion on Wikipedia, and no title is shown. Try yourself: https://en.wikipedia.org/wiki/Onions

**Comment by BranescuMihai** [comment]
Dev note: onLocationChange with `https://en.wikipedia.org/wiki/Onions` (sets title to empty) -> onTitleChange (Onion-Wikipedia, so the final title) -> onLocationChange with `https://en.wikipedia.org/wiki/Onion` (sets title to empty), so at first glance the problem might be that the `onTitleChange` is called before `onLocationChange`

**Comment by B0pol** [comment]
As reported in #14432 , this issue affects all duckduckgo searches

**Comment by jonalmeida** [comment]
> As reported in #14432 , this issue affects all duckduckgo searches

These are two separate bugs that manifest in similar ways. I think we can safely close this since we no longer can reach a case where we show no title and we this newer bug to track the current issue.

**Comment by B0pol** [comment]
Still an issue

**Comment by B0pol** [comment]
Workaround : refresh the page

Related: it seems to happen sometimes even if it's not a redirect (e.g. top site, new tab…). I don't know if it's the same bug or just related

**Comment by B0pol** [comment]
bump
