### ISSUE TITLE
persist desktop site request for homescreen shortcuts

### ISSUE THREAD

**Issue by AlwyNjOshy** [mozilla-mobile/fenix#10926]
https://web.whatsapp.com/

Instead of desktop version website loads on mobile version. I just turn on desktop view and added it home screen. But when i try to open it from home screen book mark it loaded as mobile version and couldn't use. Will you add an option to open it as desktop view if we enable desktop view before "add to home screen" so that settings will saved with that bookmarks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1218)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807097

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
