### ISSUE TITLE
FNX-4690 ⁃ Integrate BrowserThumbnails into the tabs tray

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#10921]
When https://github.com/mozilla-mobile/android-components/issues/7021 lands, we should look at integrating the BrowserThumbnails into the tabs tray.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly Build 200603 from 6/3`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ The screenshots are properly displayed if you open one by one the websites 
► Video
![20200603-151320](https://user-images.githubusercontent.com/51314259/83651653-654cec80-a5c2-11ea-8e79-91fb0117bede.gif)

❓ I've noticed that if you open websites in the background or quickly one by one (don't wait to fully load) the screenshots aren't displayed.
Even if you re-visit the websites the screenshots aren't displayed

**The only way they get update is to refresh each page and wait for it to be loaded
Do you always need to refresh the page to get the screenshots properly displayed?**

**Open quickly websites**
► Video
![20200603-175317](https://user-images.githubusercontent.com/51314259/83654777-3afd2e00-a5c6-11ea-8cbc-ef4433841a47.gif)


**Open in background (long tap + new tab)**
► Video
![20200603-175730](https://user-images.githubusercontent.com/51314259/83655847-85cb7580-a5c7-11ea-9d75-17a11a3ceaef.gif)


@gabrielluong - Could you please review and share your thoughts? ☺️

**Comment by gabrielluong** [comment]
> The only way they get update is to refresh each page and wait for it to be loaded
> Do you always need to refresh the page to get the screenshots properly displayed?

Yes, that is currently how it works. We will be looking to improve it, but right now we capture the screenshot when a page is refreshed. We can run into issues when you do the order of operations too quickly, since the engine is asynchronously capturing the screenshot when the page is finished loaded.
