### ISSUE TITLE
FNX-4794 ⁃ Custom tabs menus should be a short version on the app's menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1093]
Acceptance Criteria:

I want a fewer browser menu options when opening a custom app.
(e.g. Gmail, Twitter, WhatsApp)

- - -
## Steps to reproduce
1. Open a custom tab in the Yelp app.
1. Open the menu.
    1. Expected behavior
According to mockups in #203, the custom tab menu should contain only a short list of items: 
https://user-images.githubusercontent.com/51007/53313497-75d1da00-391e-11e9-91d4-e538e5f18e6c.png
    1. Actual behavior
The full app menu is displayed.
![Screenshot](https://user-images.githubusercontent.com/4037709/54674871-f93db000-4b05-11e9-9171-992cf1546beb.png)UNITO-UNDERSCORE!20190320-105645!

### Device information
* Android device: Huawei Honor 8 (Android 7.0), Nexus 5 (Android 6.0.1), Samsung S8 (Android 9)
* Fenix version: 3/19 build

**Comment by vesta0** [comment]
Should be fixed by #1093

**Comment by bsurd** [comment]
Verified on a Nexus 5, Nexus 6P and HTC 10.
