### ISSUE TITLE
[Bug] Find in page should match words with diacritics

### ISSUE THREAD

**Issue by officiallor** [mozilla-mobile/fenix#10931]
## Steps to reproduce
Greek language has acute accent. For example word "hello" is: γειά. When you search "γεια" instead of "γειά", there will be no results. It's expected if you use equals() but not so helpful after all, because some people don't write it as it should.

### Expected behavior
Search "γεια" and find "γειά" too, or type "τι κανεις" and find "τι κάνεις" too

### Actual behavior
Word not found

### Device information
* Android device: Mi8 Android 10
* Fenix version: ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1224)

**Comment by kbrosnan** [comment]
https://en.wikipedia.org/wiki/Diacritic

**Comment by evilpie** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=202251

**Comment by fice-t** [comment]
I believe this bug has been fixed.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807143

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
