### ISSUE TITLE
FNX3-14273 ⁃ menu items with submenu should look like menu items with submenu

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#10935]
After #8319 has been implemented - could you please add something like a ">" to he "Add-ons" menu item so that it's clear that it contains other menu items?  It would be much clearer that I have to look there for my installed add-ons. For comparison see also how menu items with submenu looks in Fennec (not for add-ons but for other menu items).

**Comment by brampitoyo** [comment]
@cadeyrn I agree that Fennec’s implementation (right chevron arrow) is sensible. Let’s follow that on Firefox Preview.

**Comment by psymoon** [comment]
@cadeyrn this is available in nightly now.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fenix Nightly Build 21550609 GV 78.0a1 from 6/3 with Huawei P9 Lite (Android 7), Nexus 5 (Android 6.0.1).

The right chevron icon, like the one available on Fennec, is displayed next to the Add-ons from the main menu, when there are enabled add-ons in the list.

![20200603_114141](https://user-images.githubusercontent.com/48799384/83615651-82b49300-a58f-11ea-90c7-95861d7db184.gif)

I will remove the qa:needed.
