### ISSUE TITLE
FNX-7651 ⁃ userscript manager addons required

### ISSUE THREAD

**Issue by linmii** [mozilla-mobile/fenix#10944]
Can you please add an addons to manage userscript? like tampermonkey, violentmonkey.

**Comment by SS1113** [comment]
Leaving a comment on the issue #10943 would be great than to create a new issue.

**Comment by linmii** [comment]
> Leaving a comment on the issue #10943 would be great than to create a new issue.

Okay, got it!

**Comment by cadeyrn** [comment]
#10943 was not the first issue with an add-on request, see #10366 for example. If all add-on requests should be handled in one issue (I don't know what Mozilla prefers!) then probably not in #10943 because it's just another one that was created today and not better than this issue.

**Comment by SS1113** [comment]
@cadeyrn I think the less duplicate/similiar issues we create the more good it is.

**Comment by lindongbin** [comment]
It's time to support custom installation of extensions, rather than a few specified extensions.

**Comment by liuche** [comment]
duping to #10943
