### ISSUE TITLE
FNX-4795 ⁃ Integrate string export scripts into the Fenix build process

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#1094]
@Pike Would you mind linking to your work here and adding some hints on how to get that into automation?

**Comment by Pike** [comment]
https://github.com/mozilla-l10n/android-l10n-tooling#exporting is what I use locally.

We might want to tweak the repository and branch handling for automation.

I'd prefer for the automation to be run on each landing on master, and once we add a release branch, also for landing on the release branch.

**Comment by sblatz** [comment]
@boek is this still something we're doing manually right now?

**Comment by boek** [comment]
@Pike above^?

**Comment by Pike** [comment]
Yes. @callek and @tomprince are working on automation here.

**Comment by boek** [comment]
👍 awesome, thank you!

**Comment by Delphine** [comment]
This has been resolved. Please re-open if needed.
