### ISSUE TITLE
Support for Nano Adblocker

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10946]
### What is the user problem or growth opportunity you want to see solved?
Nano Adblocker has some unique features which uBlock Origin doesn't have. And since it is based on uBlock Origin's source code I think it is easier to support it.

### How do you know that this problem exists today? Why is this important?
I can install [Nano Adblocker](https://addons.mozilla.org/en-US/firefox/addon/nano-adblocker-firefox/). it has some unique features which are not found in uBlock Origin like reporting website breakages, anti-adbkock etc. For more info, please refer this [comment](https://github.com/mozilla-mobile/fenix/issues/10943#issuecomment-634503278).

### Who will benefit from it?
Everybody who uses it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1248)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813935

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
