### ISSUE TITLE
Use somethig better than 0.0a1 for the Nightly version

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#10941]
Can we increment this at the start of every sprint, use something like YearWeekNumber or Gecko version? It would help segment out very old crashes in nightly from crash-stats.mozilla.org

**Comment by kbrosnan** [comment]
Example: This AddonManagerException has been fixed for ages but still shows up as the 3rd most common crash. 

* https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=0.0a1
* https://crash-stats.mozilla.org/signature/?product=Fenix&version=0.0a1&signature=%5BINFO%5D%20mozilla.components.feature.addons.AddonManagerException%3A%20at%20mozilla.components.feature.addons.AddonManager.getAddons%28AddonManager.kt%3A56%29&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports

**Comment by eliserichards** [comment]
@liuche would you like to take a look at this? Not sure how simple it would be 🤔

**Comment by kbrosnan** [comment]
Did some looking into this and the 0.0a1 comes from the Socorro code. They don't have the ability to parse `Nightly YYMMDD HH:MM` into a format that they can handle. It would be best to just send the Geckoview version. See https://github.com/mozilla-services/socorro/commit/df7e3e17d5a0c9f4827e09904adf11a65582c956 and bz-1624911

**Comment by pocmo** [comment]
Grabbing this issue: Since we have synchronized versions/trains now (GV 90 <-> A-C 90 <-> Fenix 90), we should be able to align our Nightly versioning too (e.g. like desktop use 90.0a1, 91.0a1, ...).

**Comment by pocmo** [comment]
Landed PR and triggered automation.

Looks like the first 90.0a1 made it safely through automation and was uploaded to Google Play. Let's wait for it to get distributed.

**Comment by pocmo** [comment]
I did a quick some test of the build and it seems to work as expected and shows the new version number. A forced crash was uploaded to Socorro as well. On Google Play the version is currently "In Review". Let's see once it reaches users.

**Comment by pocmo** [comment]
Crash Stats:
https://crash-stats.mozilla.org/search/?product=Fenix&version=90.0a1&date=%3E%3D2021-04-22T09%3A19%3A00.000Z&date=%3C2021-04-29T09%3A19%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature

**Comment by pocmo** [comment]
The version started to show up in Sentry too:
https://sentry.prod.mozaws.net/operations/firefox-nightly/releases/org.mozilla.fenix-90.0a1/

**Comment by pocmo** [comment]
This is all done.

For now 90.0a1 doesn't show up in the version dropdown on crash stats yet, tracked here:

**Comment by Dunexus** [comment]
@pocmo Two consecuitive versions share the same 90.0a1 label. Is this expected ?
I supposed the number should increment to 90.0a2 and so on to maintain uniqueness

![Screenshot_20210501-094014.jpg](https://user-images.githubusercontent.com/13906248/116775167-c050c300-aa61-11eb-901d-03d1e76687fc.jpg)

**Comment by cadeyrn** [comment]
@Dunexus This is exactly the same behaviour as in the desktop Firefox since many years.

**Comment by Dunexus** [comment]
@cadeyrn If several versions are labeled with the exact same label (90.0a1), it can't be used as a identifier. I thought the goal was using this simplier label as a version identifier instead of the date-based label.

**Comment by cadeyrn** [comment]
The build id still different in every nightly build, no?

**Comment by Dunexus** [comment]
Oh ok, my mistake then. I didn't understand the issue.

I thought the goal was to have 90.0a1, 90.0a2, ..., 90.0aX, 91.0a1, 91.0a2 and so on, with each build a different version number

**Comment by pocmo** [comment]
Correct, it will always be `a1` and only the major version will change over time. I think `a2` used to be "Aurora" when it was still around? You are right, with this we will group multiple releases together, e.g. in crash-stats/Sentry, but this is expected and will help us see trends, but is not as fine-grained as a new version every day.
