### ISSUE TITLE
FNX-7333 ⁃ [Bug]Dark reader doesn't work on Linkedin

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10953]
## Prerequisites
Have Dark Reader installed and enabled.

## Steps to reproduce
1. Navigate to [Mozilla's Linkedin page](https://www.linkedin.com/company/mozilla-corporation)
1. Check if Dark Reader works

### Expected behavior
The web site is properly displayed using Dark Reader (Dark mode)

### Actual behavior
Dark Reader doesn't seem to convert the page, it's displayed in default mode (White)

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
:heavy_check_mark: Work on Fennec

► Video Fennec
![20200327-180240](https://user-images.githubusercontent.com/51314259/77776836-4dec0300-7057-11ea-9718-90958fac52c4.gif)

► Video Fenix
![20200327-180132](https://user-images.githubusercontent.com/51314259/77776721-1ed59180-7057-11ea-95df-5405727b36a6.gif)

**Comment by Amejia481** [comment]
QA please help us to validate if this is still an issue

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build 200527 from 5/27`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200527-172125](https://user-images.githubusercontent.com/51314259/83033104-5785ed00-a03f-11ea-944a-3dee079a112b.gif)
