### ISSUE TITLE
As a Developer I want to strings to be linted for every PR

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#1095]

**Comment by sblatz** [comment]
Can you clarify what you mean by this ticket, @st3fan?

**Comment by Pike** [comment]
I think https://github.com/mozilla-mobile/fenix/blob/5630904f93f5b7664bf2beb2fa404a9b97e3eeec/automation/taskcluster/decision_task.py#L73 is this, triggering https://tools.taskcluster.net/groups/VNvKOO9RT36LcaBELEmU6w/tasks/azgTBkriTPm7EFOKF9p_aQ/details.

I think we can mark this resolved.

As a follow-up, I'd love this process to get updated, see https://bugzilla.mozilla.org/show_bug.cgi?id=1548500. CC @callek

**Comment by sblatz** [comment]
@Pike will we get this for free or do we need to have a follow up fenix engineering ticket for that?

**Comment by Pike** [comment]
I'm deferring that question to @Callek.

**Comment by Delphine** [comment]
Can we close this issue now?

**Comment by Callek** [comment]
> As a follow-up, I'd love this process to get updated, see https://bugzilla.mozilla.org/show_bug.cgi?id=1548500. CC @Callek

@Pike , I'm forgetful on where we stood here, do you know offhand if we started doing linting with this stuff or is linting going to be a separate item? -- Or should I discuss with tom?

**Comment by Pike** [comment]
That bug is still open, AFAICT.

I only glanced at the automation setup, and it seems to be much more consistent now. At least between Fenix, A-C and FxTV. From what I see, though, the "how" is modernized, the "what" is still what I had set up.

I didn't dive into the "when" at all ;-)

**Comment by Delphine** [comment]
I am confused as to if this issue is still open or not. It seems like it is?
Unfortunately most of the people in this thread have left. Maybe @st3fan or @escapewindow can help confirm? Thanks

**Comment by escapewindow** [comment]
I don't see any specific string linting task in Fenix. It's possible it happens during some other task, but I'd guess we still need to do this.

**Comment by Delphine** [comment]
@eliserichards Do you happen to know the status of this issue? Should I reach out to someone in particular about this?
