### ISSUE TITLE
FNX2-13311 ⁃ [Bug] [Regression] "Open tabs" is not translated in other languages

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#10957]
## Steps to reproduce
1. Open app
1. Tap on the 3 dot menu and go to Settings/Language.
1. Change the language of the browser. (I changed it to French)
1. Go to either "Delete browsing data" and check "Open tabs" translation.
    1. Expected behavior
"Open tabs" is translated based on the chosen language.
    1. Actual behavior
"Open tabs" is not translated based on the chosen language.
    1. Device information

* Android device: Google Pixel 3XL (Android 9), Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 05/27

Note:

* This does not reproduce with Nightly 5/24.
* This reproduces for  "Open tabs" from "Delete browsing data on quit" as well
* I've also reproduced it with: Spanish,German, Suomi
* I think all the languages have been affected.
* It may be a regression of #10706 

Samsung Galaxy S9 (Android 8) - Delete browsing data on quit
![Screenshot](https://user-images.githubusercontent.com/49859863/83047091-940e1480-a050-11ea-89d1-d1d38a07a938.jpg)UNITO-UNDERSCORE!20200527-190118!UNITO-UNDERSCORE!Firefox Nightly!

Samsung Galaxy S9 (Android 8) - Delete browsing data
![Screenshot](https://user-images.githubusercontent.com/49859863/83047180-ae47f280-a050-11ea-9d5a-c3849fe4170b.jpg)UNITO-UNDERSCORE!20200527-190020!UNITO-UNDERSCORE!Firefox Nightly!

**Comment by Diana-Rus** [comment]
Hi, the same goes with the "Open tabs" string from Account Settings.

**Comment by Delphine** [comment]
I'd need to know what the string ID is here, so I can check if this is expected or not.
I don't know when this landed either, so can't tell if this is a regression - or if the localizer just didn't get to his strings yet.
Please let me know

**Comment by Diana-Rus** [comment]
Hi, re-checked the "Open tabs" option in the meantime and i've seen that is now fixed both on Nightly 7/30 and Beta 80.0.0-beta.1.
I'll close this now as it looks okay. I appreciate you wanted to look into it 😊.

<details closed><summary>Open tabs</summary>
- Account Settings

![Screenshot_20200730-214914_Firefox Beta](https://user-images.githubusercontent.com/49859863/88963891-32b52c80-d2b1-11ea-992f-7174c242c2c6.jpg)
- Delete Browsing Data

![Screenshot_20200730-215016_Firefox Beta](https://user-images.githubusercontent.com/49859863/88963933-406ab200-d2b1-11ea-8fba-f0fa3dc3a8a8.jpg)
- Delete Browsing Data on Quit

![Screenshot_20200730-214957_Firefox Beta](https://user-images.githubusercontent.com/49859863/88963989-5a0bf980-d2b1-11ea-9491-75ef5b32651c.jpg)
</details>

<details closed><summary>Covered languages</summary>
- French
- Spanish
- German
- Suomi
- Japanese
- Albanian
- Romanian
- Chinese (traditional)
</details>

Note; I've seen that for Arabic is not yet translated, it will most probably be treated under this issue #10779.

**Comment by Diana-Rus** [comment]
Will be closing this, same affirmation is still available as the one from the above [comment](https://github.com/mozilla-mobile/fenix/issues/10957#issuecomment-666610187).
