### ISSUE TITLE
[Feature request] Support for refreshing an expired download link in the download manager

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#10950]
### What is the user problem or growth opportunity you want to see solved?
This is really important for me as the large downloads most of the time have time limit to them and after that the links to them expire moreover sometimes the files stop downloading in the middle of nowhere and for no apparent reason and don't and can't be resumed and I have to download the whole file again. Just imagine a 5 GB file was interrupted downloading at 99% and can't be resumed because the link expired! Third-party download managers like [ADM](https://play.google.com/store/apps/details?id=com.dv.adm) make it easy to refresh the expired download links and I can start the download where it stopped and save a lot of mobile data.

None of the browsers I have come across have the link refreshing feature. So this feature would be really really useful if it is implemented in the browser itself

### How do you know that this problem exists today? Why is this important?
Broadband internet doesn't exist everywhere and can't be installed in every situation and by everyone. Everyone who I know is using the mobile internet primarily and it is the only way to go online and it is expensive most of the time. So having a built-in way to refresh expired download links can be really useful if the file is almost downloaded and has been interrupted for for some reason.

### Who will benefit from it?
Users who have limited mobile data plan will definitely benifit from it since the file downloads can be resumed where they were interrupted.

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)
