### ISSUE TITLE
FNX-7321 ⁃ Tab Tray - Improve + Button

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10965]
Updates needed:

* Fix blue border around the add tab button
* Implement content description.

**Comment by abodea** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 4 XL (10)

![20200529-150526-2](https://user-images.githubusercontent.com/42831109/83260348-47e2e180-a1c2-11ea-8136-021d1085557e.gif)
