### ISSUE TITLE
FNX3-14296 ⁃ [Bug] (regression) "Add to Home screen" dialog appears after every reload

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#10969]
### Steps to reproduce
1. open https://www.camp-firefox.de/
1. Press "Continue to website"
1. reload the website
1. repeat the steps 2 and 3 a few times

### Expected behavior
Dialog should not appear every time.

### Actual behavior
Dialog appears after every reload. This is a recent regression.

![Screenshot](https://user-images.githubusercontent.com/1100614/83074883-363ef400-a073-11ea-8509-aafa0698bfd5.jpg)UNITO-UNDERSCORE!20200527-233442!

### Device information
* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision 248237290e9308b85194319b1416c6d4a7153a06

**Comment by ekager** [comment]
This seems annoying, we should fix this.

**Comment by Mugurell** [comment]
Yup, this is a recent regression after https://github.com/mozilla-mobile/fenix/issues/10948.
I was always resetting if the dialog was shown if the user didn't have a pwa installed.
Sorry for that.

**Comment by sheikh-azharuddin** [comment]
Please fix this one...too annoying..got it after updating the browser now... wondering if some people are getting update much earlier than me😓
![Screenshot_20200528-234225](https://user-images.githubusercontent.com/58127841/83177766-2d036500-a10f-11ea-9ea1-11a2643bc2b6.jpg)

**Comment by cadeyrn** [comment]
> Please fix this one

It is already fixed. The fix will be in the next nightly build.

> wondering if some people are getting update much earlier than me😓

I compile the builds myself, that's why I got this bug earlier (but also the bugfix).

**Comment by sheikh-azharuddin** [comment]
> > Please fix this one
> 
> It is already fixed. The fix will be in the next nightly build.
> 
> > wondering if some people are getting update much earlier than me😓
> 
> I compile the builds myself, that's why I got this bug earlier (but also the bugfix).

That's great 👍
Thanks for your prompt response and fix. I have been going through the issues reported daily and it seems you people are too overloaded but you always do manage to fix bugs and add features...keep up your good work😊👍

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200529 from 5/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200529-092619](https://user-images.githubusercontent.com/51314259/83228341-d3db1600-a18e-11ea-9f55-cfb2250a80bb.gif)
