### ISSUE TITLE
FNX-7318 ⁃ [Bug] Tracking protection pop-up appears above tabs tray

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#10968]
## Steps to reproduce
* Load a page
* Open tabs tray

### Expected behavior
No tracking protection pop-up.

### Actual behavior
(sometimes) Tracking protection pop-up appears over tabs tray. iirc, I couldn't dismiss the pop-up except by clicking the X (i.e. I couldn't click outside the pop-up to dismiss)

![Screenshot](https://user-images.githubusercontent.com/759372/83066853-8ccc1400-a01a-11ea-8c51-ff00b0ed74a3.png)UNITO-UNDERSCORE!20200527-084540!

### Device information
* Android device: P2
* Fenix version: upstream/master from yesterday; some commit before 54cb8f0194b2ae80118857c6ce02e4d43de9bb29

**Comment by liuche** [comment]
If the browser isn't focused, don't show the CFR (like if the tabs tray has popped up)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200604 from 6/4`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200604-135401](https://user-images.githubusercontent.com/51314259/83749314-31c69c80-a66c-11ea-9365-9861555122e8.gif)
