### ISSUE TITLE
FNX-11834 ⁃ [Bug] Some PWAs not loading

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#10977]
## Steps to reproduce
1. Install the Twitter PWA.
1. Launch the PWA.
1. Close and launch again if needed.
    1. Expected behavior
The twitter homepage/feed is loading.
    1. Actual behavior
Either a "sorry, something went wrong" message first, then a blank screen, or a blank screen the second time you launch the app. From then on, the PWA is unresponsive.
**logcat:**
[log.txt](https://github.com/mozilla-mobile/fenix/files/4695099/log.txt)

![20200528-131355](https://user-images.githubusercontent.com/4037709/83130447-fb76a380-a0e6-11ea-997e-488de3c98b50.gif)

### Device information
* Android device: Pixel 4 (Android 10), Nexus 6P (Android 8.1, x86 emulator)
* Fenix version: Beta 5.1-beta 2 & Nightly 5/27.

**Comment by sv-ohorvath** [comment]
https://bt-voice-memos.appspot.com/ not loading either, after a second launch.

**Comment by TitanNano** [comment]
@sv-ohorvath might be this: https://github.com/mozilla-mobile/fenix/issues/10689

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath might be this: #10689

thank you, I didn't see it.
