### ISSUE TITLE
FNX-11831 ⁃ Show a list of webistes that are allowed to send notifications

### ISSUE THREAD

**Issue by umerf52** [mozilla-mobile/fenix#10974]
### What is the user problem or growth opportunity you want to see solved?
Recently I started getting notifications from Fenix. These are usually from Instagram (I assume, although I don't have an Instagram account), but I don't have given any permission to post notifications by Instagram. I need a way to concisely see which websites are allowed to post notifications.

### How do you know that this problem exists today? Why is this important?
This would allow users to easily manage their notification preferences and avoid spam notifications.

### Who will benefit from it?
The users who want to keep in check which websites are allowed to send notifications.

**Comment by sheikh-azharuddin** [comment]
Same issue...I have also started getting notification..I guess these are not from instagram...I got one notification from faasoos, one from HDFC twitter, 3 from some photos(maybe instagram). But clicking the notification do nothing...may be they utilize the feature to push notifications from user favourite sites like google do...in all cases user must have a preference to take control of the notification...the firefox logo on the status bar looks really beautiful 😍

**Comment by sheikh-azharuddin** [comment]
Attaching the screenshot for 2 notification- 1 faasoos 1 twitter
![Screenshot_20200528-192708](https://user-images.githubusercontent.com/58127841/83150721-25ca6000-a0eb-11ea-85c0-6cbf6e41602d.jpg)

**Comment by vaindil** [comment]
I have also started getting notifications for random sites. I have never opted into notifications for any site on nightly, so this is a little concerning. Tapping the notification doesn't do anything, so I'm not even sure what site the notification is coming from. This list is really needed so I can disable them.

**Comment by TitanNano** [comment]
Going into `Settings > Site Permissions > Exceptions` shows all sites with any kind of permission.

 @brampitoyo Maybe Fenix could also show a list of sites in the permission Settings page? Under `Settings > Site Permissions > Notifications`

**Comment by cadecairos** [comment]
I'm seeing this too in the Nightly version, regular push notifications that don't indicate where they're from (it looks like a news site), and clicking on it does nothing except open Nightly.

There are no listed exceptions in `Settings > Site Permissions > Notifications` so I'm not sure what's going on or how to stop it without completely blocking the app from notifications in Android.

**Comment by vaindil** [comment]
> Going into `Settings > Site Permissions > Exceptions` shows all sites with any kind of permission.

Maybe I should open a different issue then, because I have four sites in that list, and they all say either "Blocked" or "Ask to allow", yet I'm still getting notifications from some unknown site.

**Comment by sheikh-azharuddin** [comment]
Got it now...these are pushed from my twitter account..just now clicked the notification icon in twitter site and there are all the notification... Maybe firefox testing this feature to push notifications from sites... clicking on it should actually open it but that does not work...

Guys check your twitter account too

**Comment by umerf52** [comment]
> 
> 
> > Going into `Settings > Site Permissions > Exceptions` shows all sites with any kind of permission.
> 
> Maybe I should open a different issue then, because I have four sites in that list, and they all say either "Blocked" or "Ask to allow", yet I'm still getting notifications from some unknown site.

I think that a new issue is necessary since this seems like a bug.

**Comment by TitanNano** [comment]
There are two new issues that will try to address the bugs mentioned here:

1. the missing origin information of the notification https://github.com/mozilla-mobile/fenix/issues/11007
2. notifications beeing delivered without permission https://github.com/mozilla-mobile/android-components/issues/7161

**Comment by jonalmeida** [comment]
I'm marking this as a feature request. When we have these bugs fixed, we still need to have a place to allow/deny the notifications in the site settings screen.

> There are two new issues that will try to address the bugs mentioned here:
> 
>     1. the missing origin information of the notification #11007
> 
>     2. notifications beeing delivered without permission [mozilla-mobile/android-components#7161](https://github.com/mozilla-mobile/android-components/issues/7161)

**Comment by jonalmeida** [comment]
With the above issues resolved, we now have the ability to control WebNotifications from the Site Permissions setting.

If there are more enhancements you think we should add, please file a new feature requests and we'd be happy to take a look!

Below is a screenshot of the settings for a particular test site:

<img width="384" alt="Screen Shot 2020-07-21 at 12 28 25 PM" src="https://user-images.githubusercontent.com/1370580/88080913-b6527900-cb4d-11ea-80c5-97e164a3f8b1.png">
