### ISSUE TITLE
FNX-4797 ⁃ Integrate string import in Fenix Nightly build

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#1098]
Automating the string import.

**Comment by boek** [comment]
Isn't this done already?

**Comment by sblatz** [comment]
@Delphine can you help point me in the right direction of who could explain if this is done or not?

**Comment by Delphine** [comment]
I don't believe this has been automated yet.
@Pike Could you please provide more info about where this is at. I believe you've been having regular discussions about this with the Fenix team, but not sure where that was at

**Comment by Pike** [comment]
@Callek is working on this.

**Comment by sblatz** [comment]
@Callek are you able to provide a status update for us? 😄

**Comment by sblatz** [comment]
From a Slack conversation with @Callek, it sounds like there's not work here to be done on the fenix engineering side. I'm going to remove it from our prioritized backlog because of this :)

**Comment by Callek** [comment]
So the current status is that, yes I am working on it.

We plan to have automation periodically:
* Creating PR's from fenix (and android-components) to the l10n repo for new strings
* Creating PR's with translating strings from the l10n repo to here and android-components
* Ideally having automated merges of the translated strings from the previous PR.

The last bullet point is the most in flux, and comes down mostly to what method we think is best and a sec signoff (and legal signoff if there is a terms of service/contract to do with a business).

We are looking at options like Githubs new Action stuff and things like https://mergify.io though we could also write a custom script with locked down permissions with access to do it as well.

**Comment by Callek** [comment]
> From a Slack conversation with @Callek, it sounds like there's not work here to be done on the fenix engineering side. I'm going to remove it from our prioritized backlog because of this :)

Absolutely correct, there is no expectation that the Fenix engineering team will have to do anything to facilitate this, should that change [I don't expect it will] I'll escalate and get it slotted in and prioritized as a new ask.

**Comment by tomprince** [comment]
I am to have creating PRs with l10n changes deployed this week. The current plan is to handle all automation via https://github.com/mozilla-l10n/android-l10n and won't involve any code changes here. Support for automatic merging is out-of-scope for the current batch of work.

**Comment by sblatz** [comment]
@tomprince is this related to the email @Pike just sent out? 

It seems like we can close this ticket based on that email?

**Comment by Delphine** [comment]
I think we can close this. Please re-open if I'm wrong
