### ISSUE TITLE
FNX-11855 ⁃ bug Launch home when all tabs are closed

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#10998]
## Steps to reproduce
1. Open a bunch of tabs
1. Go to a site
1. Close all open tabs

### Expected behavior
Home screen is displayed

### Actual behavior
I stay on the empty tab tray and see the site (that I just closed) in the background

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200603 from 6/3`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200603-101119](https://user-images.githubusercontent.com/51314259/83607323-ad98ea00-a583-11ea-9a46-4073bb0616d6.gif)

@boek - #11024 is related to this matter
Closing all **Private Open Tabs** while having open tabs in normal browsing will redirect the user to  normal browsing
