### ISSUE TITLE
FNX-11853 ⁃ Add menu to tab tray PBM

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#10996]
Menu has following options:

* Share all tabs
* Close all tabs

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 200602 from 6/2`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200602-175110](https://user-images.githubusercontent.com/51314259/83535016-34a18000-a4fa-11ea-8cb1-284af1c474a5.gif)

For the Undo snackbar issue I've opened #11025
