### ISSUE TITLE
FNX-11851 ⁃ Tab Tray - Not Displaying in Landscape Mode on Pixel 4

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#10994]
I only see the FAB, I don't see the tray at all.

![Screenshot](https://user-images.githubusercontent.com/46655/83175334-5a391e80-a0e1-11ea-9949-4720a6b4b16d.png)UNITO-UNDERSCORE!20200528-124619!

**Comment by LittleAngelwings** [comment]
It's not only on Pixel 4, I have this issue at my Samsung Galaxy Tab A6 SM-T580 and on my Huawei P Smart too.

**Comment by darkwing** [comment]
Closing in favor of: https://github.com/mozilla-mobile/fenix/issues/11031
