### ISSUE TITLE
FNX-11858 ⁃ Tab Tray - Close All Snackbar Displays Behind Tab Tray

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#11001]
Happens in both home screen and browser.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200604 from 6/4`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video Normal tabs
![20200604-142716](https://user-images.githubusercontent.com/51314259/83751958-63416700-a670-11ea-98ee-e1c9be231e8e.gif)

► Video Private Tabs
![20200604-142851](https://user-images.githubusercontent.com/51314259/83752170-bca99600-a670-11ea-936c-fa91de6867b0.gif)
