### ISSUE TITLE
Verify a11y working on Tabs Tray

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11003]
We're mostly using the stock android components so we hope there aren't a lot of problems, but we should validate once this lands fully in Nightly.

cc @asadotzler

**Comment by softvision-miralobontiu** [comment]
I found 2 issues regarding tabs tray having the talkback/voice assistant enabled: #14946, and #14948.

**Comment by mcarare** [comment]
This is an old issue that was also covered in https://github.com/mozilla-mobile/fenix/issues/15922.
