### ISSUE TITLE
Picture in Picture should have fwd and backward button

### ISSUE THREAD

**Issue by jhamukesh998** [mozilla-mobile/fenix#11000]
### What is the user problem or growth opportunity you want to see solved?
Right now to go 10 seconds back on a video, we have to get back to normal mode move back and then again switch to PiP mode. This is time consuming.

### How do you know that this problem exists today? Why is this important?
I have been loyal follower of mozilla firefox

### Who will benefit from it?
Everyone.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1332)

**Comment by B0pol** [comment]
Afaik it's not possible with the current PiP player, they are using android picture in picture mode which isn't customisable, except for version 11 (it's now resizable).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813910

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
