### ISSUE TITLE
When closing the app from private browsing, app should default to open to non-private homescreen

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#11009]
A bug was filed to fix this issue but it looks like it has regressed. 

This is from the original issue filed:

https://github.com/mozilla-mobile/fenix/issues/4780

@sblatz Hi, with the introduction of PBM launcher I think we should modify the behaviour for when Firefox Preview is set in the background (swiped up off the screen). Right now, if the user was last in PBM with tabs opened and backgrounds the app, the private tabs are cleared but it is still set in PBM. The new behaviour would be when the app is in the background in PBM, upon opening the app again, it will default back to non-private browsing mode. Let me know if you have any questions
![2019](https://user-images.githubusercontent.com/5992746/63539915-19283400-c4e9-11e9-8d38-73547cb37d49.jpg)UNITO-UNDERSCORE!08!UNITO-UNDERSCORE!19!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!15!UNITO-UNDERSCORE!23!UNITO-UNDERSCORE!27!UNITO-UNDERSCORE!011!UNITO-UNDERSCORE!0!

_Originally posted by @AmyYLee in https://github.com/mozilla~~mobile/fenix/issues/4780#issuecomment~~524023132_

**Comment by DavidJCobb** [comment]
As an apparent side effect of this bug, the following sequence of steps opens a link in private mode when normal mode would be expected:

- Close Firefox while browsing in private mode.
- View a link in another app, such that Firefox is used to display the page but you're still "in" the other app
- Decide to open the link in Firefox, such that Firefox launches and opens the link in a new tab
