### ISSUE TITLE
Something about obsolete strings that need to be removed (or not)

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#1100]

**Comment by sblatz** [comment]
I think this ticket is referencing that we used to have to keep in old obsoleted strings.

My understanding is that strings can now change, BUT the old identifier must be changed to a new one.

@Delphine can you clarify this process?

**Comment by Pike** [comment]
The docs we have for Firefox apply here, https://firefox-source-docs.mozilla.org/intl/localization.html#string-updates.

Is that good enough? Should we link that up somewhere?

**Comment by kbrosnan** [comment]
This has seemed to outlive its usefulness.
