### ISSUE TITLE
FNX-11864 ⁃ [Bug] origin information missing from push notifications

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#11007]
## Steps to reproduce
1. receive a push notification

### Expected behavior
Notification contains information about the origin that sent the push.

### Actual behavior
Notification does not indicate which origin sent it. 

GV dependant feature request:  https://bugzilla.mozilla.org/show_bug.cgi?id=1642345

Top notification is from Fennec bottom from Fenix.
![123](https://user-images.githubusercontent.com/4500858/83189767-be83ce80-a131-11ea-81e5-6631e656f090.jpg)

### Device information
* Android device: 10.0.0
* Fenix version: Nightly 200527 06:01 (Build #21480608)

**Comment by TitanNano** [comment]
@jonalmeida I believe you are most familiar with the Fenix push integration. 😬️

**Comment by jonalmeida** [comment]
Thanks for filing!

Hmm.. I wonder if we can propagate the `scope` from the push message to the web notification and surface it as the notification "origin".

I'll file a bug for GeckoView request since the web worker that processes the notification doesn't have context on the site origin.

**Comment by snorp** [comment]
We've added a `source` field to the `WebNotification` class in GeckoView. This will be in GeckoView 79 unless we decide to uplift to78.

**Comment by jonalmeida** [comment]
@TitanNano this should be fixed in the next Fenix nightly release (probably tomorrow).

**Comment by sheikh-azharuddin** [comment]
Yeah this is fixed now. Getting the source site name.

![6833](https://user-images.githubusercontent.com/58127841/84586985-0af62c00-ae0b-11ea-9f7e-e8dae0ed844f.png)

**Comment by jonalmeida** [comment]
Closing as fixed.
