### ISSUE TITLE
FNX-11872 ⁃ Switch Default ETP Setting to Standard

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11015]
For experiment change default ETP setting to standard

**Comment by liuche** [comment]
cc @vesta0

**Comment by liuche** [comment]
@ekager can you also confirm for @ecsmyth whether or not changing the default from strict to standard will affect existing users (e.g. they'll see more ads than they did before) or only new users?

**Comment by ekager** [comment]
The way I have it currently will impact all users who haven't intentionally changed their default setting.

If we want to only change new users' settings, I could force it to select standard during onboarding (I'm thinking and not sure how else to identify new users here against users who haven't changed the setting)? The only problem there would be if I force select a setting for them, if we decide to change the default again, they would count as users who have already "changed their default setting" and would not be automatically migrated to a new default.

**Comment by liuche** [comment]
@ekager no let's do it the way originally suggested, which is change that setting for all users who haven't explicitly made a choice.

**Comment by sv-ohorvath** [comment]
Verified on Fenix 5.1.0-beta 3 that user preference is kept and Standard is the default if there is nothing set.
