### ISSUE TITLE
FNX-11874 ⁃ [Bug] youtube video freezes image

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#11017]
## Steps to reproduce
visit youtube video https://m.youtube.com/watch?v=n6QwnzbRUyA

### Expected behavior
video moves

### Actual behavior
sound goes on but video either freezes or loops like a gif of half a second
this started about a week ago

### Device information
* Android device: one plus 5t
* Fenix version: nightly

**Comment by ekager** [comment]
Closing for #10896
