### ISSUE TITLE
FNX-11882 ⁃ [Bug]Tab Tray - Undo snackbar not displayed after Closing all tabs while in Private Mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11025]
## Prerequisite
Have a couple of open tabs in Normal browsing
Have a couple of open tabs in Private browsing

## Steps to reproduce
1. Open the Tabs Tray and switch to the Private Tabs
1. Tap the ⋮ button and select "Close all tabs"

• The user is re-directed to the Open tabs from Normal browsing:

1. Tap the ⋮ button and select "Close all tabs"

### Expected behavior
Step 2: The confirmation snackbar with the "Undo" button **is displayed** 
Step 3: The  "Close all tabs" button **works in Normal browsing**

### Actual behavior
Step 2: The confirmation snackbar with the "Undo" button **is not displayed**
Step 3: The "Close all tabs" button **doesn't work in Normal browsing**

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200529 from 5/29

### Notes
► Video
![20200529-123449](https://user-images.githubusercontent.com/51314259/83245184-0f82d980-a1a9-11ea-900c-8e6521a9746c.gif)

**Comment by darkwing** [comment]
Just tested and this works with Jeff's recent patch.

**Comment by abodea** [comment]
**Verified as fixed** on the latest Nightly build from 6/5 with **Google Pixel 4 XL (10), Samsung Galaxy S7 (7).**
Note that the undo functionality is working correctly.

![20200605-111533](https://user-images.githubusercontent.com/42831109/83854194-09e44100-a71f-11ea-8580-46678127672a.gif)
