### ISSUE TITLE
FNX-4799 ⁃ [UX] Tab crash page

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#1102]
Requirements:

1. New copy for the description since we're saving history and not a private browser
1. How "restoring" a session should look (likely a restore session button similar to close tab, with copy that reflects this)

There's also this question: https://github.com/mozilla-mobile/fenix/issues/1003#issuecomment-474030890

**Comment by brampitoyo** [comment]
Changed the issue name to reflect the fact that this error page appears only when a single tab has crashed – not when the whole app crashed.

**Comment by brampitoyo** [comment]
@sblatz Here’s a mockup for tab crashed page, along with copy that @mheubusch has written:

<img width="360" src="https://user-images.githubusercontent.com/51007/54724430-08893000-4bd0-11e9-91b8-b080ac376142.png">

Inspectable mockup: https://mozilla.invisionapp.com/project/17050512

(Note that the illustration is still a placeholder, but the measurements are correct).

**Comment by sblatz** [comment]
@brampitoyo is `<name>` here the name of the user? If so, how will we know their name if they don't have an account?

**Comment by mheubusch** [comment]
Sorry - its the name of the product - it should be a shortname parameter
thing since we know we can't go into MVP with the name Fenix so if we call
it GeckoView Preview we'll need the ability to change it to Firefox when we
move out of MVP into release.

**Comment by sblatz** [comment]
Thanks for the clarification, I also don't seem to have access to that placeholder image (even when I do inspect mode, there's no asset), are you able to send it to me? :)

**Comment by mheubusch** [comment]
@sblatz did you get the asset you needed for restore tab? Also do you need a new user story/epic for restore session?

**Comment by lime124** [comment]
@mheubusch sean got him all the error page illustrations and strings on friday.

**Comment by sv-ohorvath** [comment]
@mheubusch Hello, it might be just me, but the crash message sounds like the tab can't be restored, although there's still a "restore tab" option.

**Comment by mheubusch** [comment]
@sv-ohorvath not just you. :)  Have someone on my team taking a fresh look at this - thank you.  also, IICR we are handling crash reporting options in the settings, not at the page level but @brampitoyo can confirm.

**Comment by MeridelW** [comment]
Hi  @sv-ohorvath! That copy has indeed been updated (see attachment for latest mock—still a work in progress...for example, button copy should be all caps). The user can indeed "try again" and the copy no longer contradicts this.

As for "send crash report," there is a separate prompt that comes up in the flow for the user to report an issue. This is the only error that has the reporting function as this is the only error that is Mozilla's fault. 
![New content crash message](https://user-images.githubusercontent.com/33848177/55081306-9ac88280-506d-11e9-959b-9d99b0043cb0.png)

**Comment by sblatz** [comment]
This page is currently being displayed when a **tab** crashes. [GV team is working on a feature](https://github.com/mozilla-mobile/fenix/issues/1002#issuecomment-474006830) that would allow a tab to be restored after it has crashed, but right now we can only close it (or choose to reload the page without any history). I don't think a "try again" button being the only option is good, as it does not give a clear indication to the user that they may be forced to just close the tab to get out of the loop.

Do we want to change the behavior of "restore tab" to just reload the URL of the crashed tab with no history?

**Comment by MeridelW** [comment]
@brampitoyo Can you weigh in on this? What's the best way to give the user the option to close the tab? I agree we need this. 

@sblatz What are the implications of reloading **with no history**?

**Comment by sblatz** [comment]
@MeridelW Essentially it would be like they had just started a brand new tab with that page loaded. This means their scroll position, any data entered, any previous history of browsing on that tab would be lost.

**Comment by MeridelW** [comment]
@brampitoyo What are your thoughts on this?

**Comment by brampitoyo** [comment]
@sblatz @MeridelW In earlier mockup, we have options for “Close tab” and “Restore tab”. Shall we use those?

“Restore tab” would make sense only if we can ensure that the tab won’t crash again (and go into a reload-crash-error-reload-crash-error… loop). Otherwise, “Close tab” is a safer bet.

Would starting a brand new tab without saving anything help fix this loop?

**Comment by sblatz** [comment]
@brampitoyo "Restore tab" could attempt to restore once, then would send us back to the same spot, but the user could then press "close tab". Keep in mind that this option is _not yet available_ on the GeckoView side, so we could have "restore tab" just reload the tab's URL with no history, which, if it crashed again, would leave the user in a position to press "close tab" if they think they're in a loop.

**Comment by brampitoyo** [comment]
@sblatz OK. Let’s go with “Close tab” and “Restore tab”, then. This way, the user can try to recover (which is always a preferred option), and can close when recovery fails.

**Comment by brampitoyo** [comment]
@sblatz Please find the new tab crash design (the only change is the inclusion of two buttons: close and restore) here: https://mozilla.invisionapp.com/share/P7R8W1ZWHM6

<img width="360" src="https://user-images.githubusercontent.com/51007/55130386-942a3000-517f-11e9-8715-95cbb3384202.png">

**Comment by sblatz** [comment]
@brampitoyo After some more work on this, it seems we actually don't have the ability to reload the tab *just yet*. I will just use a "close tab" button for now, and will add the "reload tab" when this functionality is [added by the GV team](https://bugzilla.mozilla.org/show_bug.cgi?id=1530770)

**Comment by brampitoyo** [comment]
@sblatz I’ve updated the mockup based on having only a “Close tab” button:

<img width="360" src="https://user-images.githubusercontent.com/51007/55523539-fb7e3d80-56b3-11e9-90f0-f6eabd0c7665.png">

**Comment by brampitoyo** [comment]
Paging @shorlander to review the design above.

**Comment by shorlander** [comment]
Looks good to me. I don't know if we have illustrations in these pages yet, but Sean says we should use fx-fenix_error_9.svg for this.

**Comment by mheubusch** [comment]
@sblatz just a reminder that the actual string is Sorry. <parameter> can't load that page.

**Comment by brampitoyo** [comment]
@shorlander Thanks! Below is the updated mockup containing the latest illustration from Sean:

<img width="360" src="https://user-images.githubusercontent.com/51007/56874806-845c7f00-6a90-11e9-96ef-4590ed6be15d.png">

**Comment by vesta0** [comment]
@mheubusch I believe this can be closed?
