### ISSUE TITLE
FNX-11884 ⁃ [Bug]Tab Tray -  ⋮ button not visible the overlay items are inconsistently displayed while in PB

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11028]
## Prerequisites
Fenix theme should be set to Light
Have a couple of open tabs in Normal browsing
Have a couple of open tabs in Private browsing

## Steps to reproduce
1. Switch to PB
1. Tap the Tabs Tray
1. Check the UI
1. Tap area where the  ⋮ button should be located
1. Check the overlay items

### Expected behavior
The ⋮ button is visible
The ⋮ button overlay items are properly displayed

### Actual behavior
The ⋮ button isn't visible
The ⋮ button overlay items have **black font color**

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200529 from 5/29

### Notes
► Video
![20200529-141223](https://user-images.githubusercontent.com/51314259/83255490-2fba9480-a1b9-11ea-909f-64f3f30e28d0.gif)

**Comment by liuche** [comment]
should have been fixed now

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200605 from 6/5`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200605-095635](https://user-images.githubusercontent.com/51314259/83846431-3eea9680-a713-11ea-8803-09bfe5ce323c.gif)
