### ISSUE TITLE
FNX-11881 ⁃ [Bug]Tab Tray - Closing all open tabs in Private Browsing shouldn't re-direct the user to normal browsing

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11024]
## Prerequisites
Have a couple of open tabs in Normal browsing
Have a couple of open tabs in Private browsing

## Steps to reproduce
1. Open the Tabs Tray and switch to the Private Tabs
1. Tap the ⋮ button and select "Close all tabs"

### Expected behavior
The user should remain in Private Mode
Display the empty PB Tabs Tray

### Actual behavior
The user is re-directed to the Normal Browsing Tabs Tray

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200529 from 5/29

### Notes
► Video
![20200529-122752](https://user-images.githubusercontent.com/51314259/83244435-07766a00-a1a8-11ea-904a-ed915b8cd6c4.gif)

**Comment by liuche** [comment]
This behavior has changed and now we return user to homescreen.

**Comment by AndiAJ** [comment]
Hi @liuche  , I've just checked this matter on the latest **`Nightly Build 200605 from 6/5`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

It's still reproducible, it **re-directs the user to the Normal Browsing Home screen and open tabs**
Shouldn't it return the user only to the Private Browsing Home screen?

► Video
![20200605-102542](https://user-images.githubusercontent.com/51314259/83848852-254b4e00-a717-11ea-816e-d40887f062bc.gif)

**Comment by topotropic** [comment]
> ### Expected behavior
> 
> The user should remain in Private Mode
> Display the empty PB Tabs Tray

@AndiAJ what's the user need behind this? Closing all tabs could be an indicator that people are done with private mode, close the private session and want to continue something in non-private mode.

Other major browsers, also Fennec, redirect people to either the non-private tab tray or the last viewed non-private open tab on closing all private tabs.

**Comment by AndiAJ** [comment]
@topotropic wasn't quite sure, many thanks for clarifying this! ☺️ 

P.S. I've bumped into a new issue #12383 somehow related to this matter
