### ISSUE TITLE
[Bug, maybe?] "Block audio and video" default autoplay setting leads to a large number of bad user experiences

### ISSUE THREAD

**Issue by denschub** [mozilla-mobile/fenix#11027]
Currently, the default autoplay setting appears to be "Block audio and video", which is also the "Recommended" setting. While I like this move for saving bandwidth, we have received a number of reports from users about broken "GIFs" as a result.

Since the default setting also blocks video elements that are muted or playing files that do not contain a audio track, this is rather unexpected, and does not match the behavior on desktop, where we only block autoplaying things that make noise. This leads to sites not expecting to be blocked, and thus not placing any video controls. One example of such a site is the case mentioned in https://github.com/webcompat/web-bugs/issues/53358, where instead of a video, a large black rectangle is visible, which looks broken. Tapping on that element does not start playing the video, and there is no indication that there is supposed to be a media file, and also no indication that we blocked something. (Note that here, we're blocking a video that actually contains audio, but all the other reports I can see on a glance are very NSFW, so.. let's use that as an example for now.) 

There are a lot of autoplay issues filed right now, but I don't think there is one on improving UX. Do we have an idea about possible solutions, that don't lead users to believe something is broken? In my naive world, I could imagine showing a large play icon or something above blocked video elements, where tapping on it actually starts playing the video.

I'll use this report to close our duplicate webcompat reports against for now. If I missed an already existing bug, sorry, please close this as a duplicate! :grinning:

**Comment by karlcow** [comment]
The webcompat issues are accumulating with this issue. 
There's no easy way to activate the video when blocked or even to know in the first place that there is an animated video which has been blocked. See for example. https://github.com/webcompat/web-bugs/issues/58709

**Comment by liuche** [comment]
cc @Amejia481 
and also tagging @apbitner here. Since Media/usability is a focus for Q4, this seems like this could be a good candidate for falling under those areas! Could you see if improving the UX of default media settings is important during your touchpoints with @lime124 ?

**Comment by rsepierre** [comment]
I don't think adding a play logo does the job. I would certainly work for gifs, but there is multiple instances where it wouldnt work : 

- video as a link (video thumbnail)
- video backgrounds

Basicly, any video we are not supposed to interact with
OR videos for which a special interaction has already been set.

I would either enable muted videos autoplay again (if you want to save bandwitch, ban true GIFs)

Or ask for user consent (like you would for webcam / mic / geo) for autoplaying media on the website

**Comment by yaomtc** [comment]
This is no longer an issue for me.

This was my report, whereas now a play button appears on the video, which does play the video. https://github.com/webcompat/web-bugs/issues/53358

**Comment by ksy36** [comment]
This is still an issue in https://github.com/webcompat/web-bugs/issues/73208 where a vimeo video is being blocked by autoplay settings and there is no way to start it since there is no play button.

Link to a video https://player.vimeo.com/video/525440214?background=1&autoplay=1&loop=1&byline=0&title=0 (it rather a gif though).

**Comment by cryolithic** [comment]
My issue (linked above) was with a video that should have been blocked, but was not.

**Comment by denschub** [comment]
\*chirp\*

**Comment by Amejia481** [comment]
We [changed](https://github.com/mozilla-mobile/fenix/pull/20073) the default to be "Block audio only" :)
Is there anything else that we have to address on this bug?

**Comment by denschub** [comment]
Oh! Sorry - I honestly was not even aware of this, that completely slipped my attention. I just poked the stale-bot out of pure subconscious reaction. :)

No, the new default matches what most people expect as far as we can tell. I'll close this issue. Thanks for checking in!

**Comment by Amejia481** [comment]
No problem. Thanks for always keeping an eye opened for webcompact bugs :)
