### ISSUE TITLE
FNX-11890 ⁃ [Bug] Modal dialog on installing sites to home screen

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#11034]
## Steps to reproduce
Since today, I sometimes get modal dialogs while loading a website (in my case, Twitter) that ask me if I want to install the site to my homescreen. I never do, and I do not appreciate the modal dialog. There should be an option for me to dismiss it forever.

### Expected behavior
Don't put up a modal dialog for this -- or offer an option to dismiss the dialog forever (not just once per site).

### Actual behavior
Repeatedly get modal dialogs.

### Device information
* Android device: Pixel 2
* Fenix version: Nightly from the Play Store

**Comment by mcarare** [comment]
This was fixed to show up only once. (See https://github.com/mozilla-mobile/fenix/issues/10969). I will close this, but feel free to reopen it if the issue still persist in the next nightly.

**Comment by djc** [comment]
Once per origin or once per device?

**Comment by mcarare** [comment]
Once per device (/install).
