### ISSUE TITLE
FNX-11888 ⁃ [Bug] Menu has different width in english

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#11032]
## Steps to reproduce
1. Look at the menu when app is set to english 
1. Switch language to german 
1. Check the menu again

### Expected behavior
Menu should be 280dp no matter the language

### Actual behavior
Menu has different width depending on language

**Comment by cadeyrn** [comment]
> Menu should be 280dp no matter the language

A dynamic width of the menu was intentionally introduced in #7157.

**Comment by Mugurell** [comment]
Thank you @cadeyrn !

Indeed, #7157 added the possibility for the menus to grow if they need the space.
There is also #1871 which asks for the menus to be be able to shrink when there would be too much blank space, something that I was planning to work on based on bram's feedback from https://github.com/mozilla-mobile/fenix/issues/10541#issuecomment-635147257 .

**Comment by topotropic** [comment]
That's great, wasn't aware of it. Thanks for pointing it out @cadeyrn!
