### ISSUE TITLE
FNX-11901 ⁃ [Bug] Tabs tray can be dismissed way too easily when dragging it

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#11042]
## Steps to reproduce
1. Launch Fenix.
1. Open a few tabs and access the tab tray.
1. Drag the tab tray menu a little bit down.
    1. Expected behavior
The tab tray menu should be closed/dismissed only when dragging it a little bit more to the bottom.
    1. Actual behavior
Tabs tray can be dismissed way too easily when dragging it.
    1. Device information

* Android device: **Google Pixel 4 XL (10).**
* Fenix version: **Nightly 5/29.**

![20200529-175000-1](https://user-images.githubusercontent.com/42831109/83277451-bf246f80-a1da-11ea-94a1-1547ecc803b1.gif)

**Comment by NotAFile** [comment]
The situation in which this constantly happens to me is when scrolling up the list of tabs. A heartfelt scroll easily leads to over-scrolling and closing the tray. This also happens a lot when I want to check if there are any more tabs open above my current one.

My first thought for preventing this was requiring scrolling and tray dismissal to be seperate touches. In other words, once you scroll the tray some distance, the dismissal action is disabled for the rest of the swipe.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**, on the latest **`Nightly Build 200624 from 6/24`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video

![20200624-095149](https://user-images.githubusercontent.com/51314259/85511008-ce8fb080-b600-11ea-8d66-6571467aa577.gif)
