### ISSUE TITLE
[Bug] Cannot open new tab after closing all private tabs in new tabs tray

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11052]
## Steps to reproduce
* Using new tabs tray...
* Have at least one normal tab open: click tabs tray, click +, enter a URL
* Have at least one private tab open: click tabs tray, click private, click +, enter a URL
* With private tab selected...
* Open tabs tray
* Click X to close last private tab
* Press + FAB to open new tab

### Expected behavior
New tab opens

### Actual behavior
No tabs open: the FAB is unusable until the tabs tray is closed and reopen.

There is also an unexpected tabs tray dismiss animation when the last private tab is closed but that's less concerning.

### Device information
* Android device: P2
* Fenix version: Nightly 200529 06:01

**Comment by yoasif** [comment]
Feels related to me: https://github.com/mozilla-mobile/fenix/issues/10368

**Comment by topotropic** [comment]
@mcomella is this still an issue? Thanks!

**Comment by mcomella** [comment]
No – the current experience is that we return to the homescreen when the last private tab is closed. Closing as WORKSFORME.
