### ISSUE TITLE
[Bug] "Fill link from clipboard" mistakes file extensions for TLDs

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#11055]
## Steps to reproduce
1. Prepare a file without spaces and give it any file extension.
1. Copy the file name to the clipboard.
1. Tap on the address bar in Fenix.
### Expected behavior
Fenix doesn't offer to fill this 'link' from the clipboard.
### Actual behavior
It does.

* Fenix version: 5.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1414)

**Comment by yoasif** [comment]
Sounds like we need PSL like on desktop: https://bugzilla.mozilla.org/show_bug.cgi?id=1080682

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by opusforlife2** [comment]
OI.

**Comment by opusforlife2** [comment]
Somebody gonna get a hurt real bad.

**Comment by opusforlife2** [comment]
Be a men! Do the right thing!

**Comment by Mugurell** [comment]
Reopening for more investigations.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813224

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
