### ISSUE TITLE
FNX-11913 ⁃ [Bug] Video loops over a few milliseconds after clicking through a few YouTube videos

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11054]
## Steps to reproduce
I can't get this to reproduce consistently. 

* Open a video in YouTube, wait maybe a minute
* (if it doesn't reproduce, open a new video and try again)
  * I can't seem to make it reproduce when I'm trying to do so – it comes up in my day-to-day use when I'm watching YouTube in the browser. When I get it to reproduce accidentally, it's usually within the first 5 minutes of opening the browser on the 3rd-5th video I click. Note that I frequently use the double-tap to advance 10s feature of YouTube and this could be related

### Expected behavior
Nothing: video plays

### Actual behavior
The video will start looping a few milliseconds of content (audio is fine). Subsequent interactions with the browser will make it unusable (e.g. content is all black) until I swipe it closed.

Video: https://drive.google.com/file/d/1Wgt6mBdQmRtlT7vIoPdWiYU65ushguaU/view?usp=sharing

### Device information
* Android device: P2
* Fenix version: Nightly 200529
  * I haven't seen this in the migrated Beta build in the play store
  * I've seen this in local Nightly builds from at least few days ago, if not a week or two
  * It reproduces in the Preview Nightly channel

**Comment by mcomella** [comment]
I captured a video of the behavior and added it to the initial comment.

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/10896
