### ISSUE TITLE
FNX-11933 ⁃ [Bug] white flashes everywhere

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11067]
I really tried to enjoy Fenix preview but it's a mess, after enabling dark theme and installing dark reader I still got white flash for link opening in New tab or when opening links from home.
if that isn't enoughto iI also get white flashes when calling Fenix from android recents and also when dismissing keyboard in web forms!!
since I got root i even created a chrome folder with a custom usercontent.css but the white flashes were still there. 
lastly I changed in about:config browser. display.backgroung_color to #000 and Fenix completely ignores that value
please fix it.
I M using laates Fenix nighlty(44.0.20200527130120) on Android 7.1.2

**Comment by ekager** [comment]
Closing for #6313
