### ISSUE TITLE
FNX-11926 ⁃ [Telemetry] ETP setting

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11063]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to know which ETP setting our users prefer so we can better optimize their default privacy settings. 

## What questions will you answer with this data?
-What percentage of users currently have `standard` vs `strict` vs `custom` ETP on?
-How often and what percentage of users change their ETP setting?

Note: I think we need to track ETP setting as a state + add "custom" as a category under the existing "tracking_protection.etp_setting_changed" probe

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by sblatz** [comment]
The bulk of this request is already handled by https://github.com/mozilla-mobile/fenix/pull/11211. I will add `custom` to the `etp_setting_changed` probe :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200611  from 6/11`** using a Google Pixel 3a (Android 10)

✔️  State of the toggle  - Ping 361817c1-d156-4005-902b-347ac32a146a
```
"category": "events",
          "extra": {
            "enabled": "pref_key_tracking_protection",
            "preference_key": "true"
          },
          "name": "preference_toggled"
```

✔️  Switch to **Strict** - Ping ea7b4777-e528-4572-af2a-79fac401c217
  ```
{
          "category": "tracking_protection",
          "extra": {
            "etp_setting": "STRICT"
          },
          "name": "etp_setting_changed"

```

✔️  Metrics with **Strict**- Ping  dfad8b10-afcc-4b9e-95aa-5d2c1fc2cba3
```
"preferences.tracking_protection": [
            "strict"
          ]

```

✔️  Switch to **Standard** - Ping d737bb2e-d155-459f-a38d-8d0bdc5589c9
```
{
          "category": "tracking_protection",
          "extra": {
            "etp_setting": "STANDARD"
          },
          "name": "etp_setting_changed"
```

✔️  Metrics with **Standard** - Ping 70c39e57-a206-48a6-98b7-cc2ec6748140
```
"preferences.tracking_protection": [
            "standard"
```


✔️  Switch to **Custom** - Ping 616a0eb3-2d29-4196-a599-26a843e12103
```
{
          "category": "tracking_protection",
          "extra": {
            "etp_setting": "CUSTOM"
          }
```

✔️  Metrics with **Custom** - Ping 72547367-3af8-4f61-9918-91ab657684f3
```
"preferences.tracking_protection": [
            "custom"
          ]
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/4769457/eetp.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test120611)
