### ISSUE TITLE
FNX-4801 ⁃ Suggestions from HistoryStorageProvider are buggy

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1106]
When I start typing a search and scroll to the bottom to see my history items being suggested they don't seem to be based on what I'm typing (perhaps this is expected behavior, but I find it confusing if so). 

In addition, tapping them sometimes has no effect. About half of them load a URL but the other half just do nothing when I tap them.

**Comment by grigoryk** [comment]
@sblatz does it feel that the results are stale, or just irrelevant? Do you have some specific examples, or STRs? (e.g. visit pages X, Y, Z, type N into awesomebar, see irrelevant result M).

**Comment by sblatz** [comment]
Sorry for the vagueness on the original ticket, I was trying to write it in a hurry.

I think there are a couple issues:
1) The results seem to be duplicate results (if a result result has the same title or URL we likely shouldn't display it a second time)
2) After just one search on a fresh install, there are two suggested items, one of which has no action when I tap on it
3) After I navigate to `mozilla.org` you see the third issue: sometimes the results are just a lot of noise, giving six suggestions, four of which take me to `https://mozilla.org/` (with or without the `www`), and two of which that take me to `https://mozilla.org/en-us`. It just seems like a _lot_ of suggestions that are effectively (or literally) the same.

## Demo
![bug](https://user-images.githubusercontent.com/4400286/54769201-fbfbdc00-4bbd-11e9-9049-4f916be6a308.gif)

**Comment by cadeyrn** [comment]
Sounds related to #465 - The history view in the library has the same issues. Points (1) and (3) of your comments are similar to points (3) and (4) in #465.

**Comment by vesta0** [comment]
Closing as there are individual tickets have been logged:
#1209 
#1331 
#1332
