### ISSUE TITLE
FNX-11931 ⁃ Fenix is not supporting keyboard shortcut

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11069]
Fenix should have support for keyboard shortcut like old Firefox
ctrl+t crtl+amo ctrl+tab and so on..
I M using latest fenix (44.0.20200527130120) on android 7.1.2

**Comment by Dunexus** [comment]
I guess keyboard shortcuts is tracked by https://github.com/mozilla-mobile/fenix/issues/3729

**Comment by ekager** [comment]
Closing for #3729
