### ISSUE TITLE
FNX-11929 ⁃ Bring back old layout when tapping url bar

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11071]
one thing I really miss form old Firefox was the ability to bring both top sites and search when tapping url bar now fenix when tapping url bar just let perform a search. 
even Samsung internet browser copied old Firefox behavior.
please bring it back. 
I M using fenix 44.0.20200527130120 on android 7.1.2

**Comment by Sgt-Miller** [comment]
I agree. There is another bug about this issue so I suggest closing this. https://github.com/mozilla-mobile/fenix/issues/10198

**Comment by ekager** [comment]
Closing for #10198
