### ISSUE TITLE
[Feature Request] add the ability to scroll the text in the address bar to solve the amount of text visible in the adress bar due to #11045

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11074]
The issue #11045 introduces problem of shortened amount of text visible in the adress bar and to add to this when Fenix  starts to support Containers this will add another [icon](https://github.com/mozilla-mobile/android-components/issues/6429) to the  adress bar 

Having the Reader Mode button in the adress bar is intuitive, I can confirm that I have rarely used it or even forgot it's even there. Having it in the address bar will definitely make me use it more instead of having it in the toolbar menu. But I also agree that it'll make text shown in the address bar even shorter.

As for the Open in app I don't think this button should be moved to the adress bar as the Open in app already opens the links in the their respective apps. 
In Chrome browser this is how it works: I click a supported link let's say a Wikipedia article, this'll open the the article in the Wikipedia app (if the open in app setting is enabled) and if I don't want to open the link the Wikipedia app then I'll have to long press the link and open it in another tab, this works really well. And as I have intentionally opened the link in another tab as to not open it in the Wikipedia app I'll know that I have to manually open the link in Wikipedia app by clicking the open in app button in the toolbar menu. 

But the default behaviour of Fenix is to not open the links in apps, and Open in app button has to be shown, in this case developers can add a functionality to scroll the text horizontally to view the whole website adress.

• **_Only show the open in app button in the adress bar when user hasn't enabled the Open in app setting and hide it when the Open in app setting is enabled by the user._**

• **_And to solve the amount of text visible in the adress bar due the Reader Mode button; add the ability to scroll the text. And when Containers support is added this will make it easier to view the whole website adress without having to click on the adress bar to view the whole adress._**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1436)

**Comment by kglazko** [comment]
Seems related to past work in https://github.com/mozilla-mobile/android-components/issues/6324 and could be useful to think about in the feature as we consider abbreviating URLs

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by jonalmeida** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
