### ISSUE TITLE
please bring back old behavior when tapping url bar

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11070]
one thing I really miss form old Firefox was the ability to bring both top sites and search when tapping url bar now fenix when tapping url bar just let perform a search. 
even Samsung internet browser copied old Firefox behavior.
please bring it back. 
I M using fenix 44.0.20200527130120 on android 7.1.2

**Comment by kglazko** [comment]
Just to clarify, are you able to scroll down the list to view history items? We have a similar feature request here that sounds like it could describe your issue: https://github.com/mozilla-mobile/fenix/issues/1161

**Comment by kbrosnan** [comment]
Closing this out as a duplicate of #1161

**Comment by 0xTyagi** [comment]
hi @kbrosnan 

How this issue is duplicate of mentioned  issue.  These are entirely different.
