### ISSUE TITLE
[Bug] datalist not supported

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11088]
## Steps to reproduce
input the beginning of the options in a datalist, [for instance Choco in this one](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist)

### Expected behavior
Chocolate should be displayed 
Video of firefox 76: 
![datalist](https://user-images.githubusercontent.com/58657617/83338339-d12e0d00-a2c3-11ea-95a7-18bdde747c9f.gif)

### Actual behavior
It's not displayed
Video of fenix 5.0:
![](https://user-images.githubusercontent.com/58657617/83338344-d9864800-a2c3-11ea-9ae2-63e5d5b90fbf.gif)

### Device information
* Android device: 9
* Fenix version: 5.0

**Comment by kbrosnan** [comment]
Needs bz-1535985 fixed and it should just work.

**Comment by KaKi87** [comment]
Hello,
Why do both [caniuse](https://caniuse.com/datalist) and the (MDN)[https://developer.mozilla.org/fr/docs/Web/HTML/Element/datalist] say Firefox for Android support `<datalist>` while it's not true ?
Thanks.

**Comment by B0pol** [comment]
Probably because Firefox for android before fenix used to support it

**Comment by phncosta** [comment]
No fix has been done so far. Gonna have to change all of my code implementation just because of this, or just ignore Firefox at all. That's  sad. :(

**Comment by B0pol** [comment]
Bump

**Comment by kbrosnan** [comment]
Closing upstream issue. This bug will be fixed by the Gecko team. There is not any Fenix team work for the feature to be enabled.

**Comment by KaKi87** [comment]
Link please ?

**Comment by cadeyrn** [comment]
@KaKi87 https://bugzilla.mozilla.org/show_bug.cgi?id=1535985 (was already linked in comment 2)

**Comment by finnhvman** [comment]
Bumped into this issue as well, managed to solve it with Lea Verou's Awesomplete: https://projects.verou.me/awesomplete

It was pretty easy to style it and I tweaked a few lines of js for my needs. It's not a full replacement of the native datalist, but better than nothing. The snippet I use for checking if the browser is Firefox Android:

```
if (navigator.userAgent.toLowerCase().includes('firefox') && navigator.userAgent.toLowerCase().includes('android')) {
  // Polyfill here
}
```

Here it is in production: https://featurle.com

**Comment by KaKi87** [comment]
> solve

Workaround.
Solving means fixing datalist.
