### ISSUE TITLE
FNX-11953 ⁃ [Bug] Undo snackbar pushes FAB up in the new tab tray

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#11089]
## Steps to reproduce
* Open a new tab
* Close the tab

### Expected behavior
The FAB stays at the same position

### Actual behavior
The FAB is pushed up by the snackbar, the "undo" button is now at its position. This is counterintuitive, as opening a new tab is a very common action and users will build up muscle memory for tapping that button. Therefore, I believe that the FAB should always have a fixed position on screen.
Also, this violates the [Material Design spec](https://material.io/components/snackbars#behavior):
> Don’t animate other components along with snackbar animations, such as the floating action button.

### Device information
* Android device: Samsung Galaxy A50
* Fenix version: Nightly 200530 06:01

**Comment by astarq** [comment]
The snackbar is also a bit low down, my phone has curved corners and the snackbar is slightly hidden under them now 
Device: Galaxy S8

**Comment by miDeb** [comment]
Fixed by https://github.com/mozilla-mobile/fenix/pull/11930.
