### ISSUE TITLE
[Bug] (regression)(tabs tray) strange shadow of new tab button

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11087]
### Steps to reproduce
1. enable the new tabs tray
1. open the tabs tray

### Expected behavior
good looking new tab button.

### Actual behavior
The shadow of the new tab button looks very strong and is truncated.

![Screenshot](https://user-images.githubusercontent.com/1100614/83336210-c9fe0380-a2b1-11ea-9242-53a5b22643b3.jpg)UNITO-UNDERSCORE!20200530-200819!

### Device information
* Android device: OnePlus 7T Pro McLaren Edition / Android 10
* Fenix version: master branch revision a6e77e3e8f0d01f3d1bf86263fd37cd7692fb58d

**Comment by liuche** [comment]
cc @kbrosnan

**Comment by cadeyrn** [comment]
> For some reason, I don't see a shadow at all.

There were improvements in the meantime so it looks now as in your screenshot. But there is still a shadow and it's still truncated. It's also very noticeable in your screenshot. Look at the top of the Android navigation bar. On the left there is no color difference between the tabs tray and the navigation bar. On the right there is a very strong color difference.

**Comment by yoasif** [comment]
You are right, I see it. I think a shadow needs to be there, but it should look better. :smile:

**Comment by kbrosnan** [comment]
@boek is there any work here or should we close this? Looks like there might be a light reverse gradient going from the bottom right corner of the tabs tray going to the tabs button.

**Comment by topotropic** [comment]
This should be fixed. Thanks!
