### ISSUE TITLE
Share URL as QR

### ISSUE THREAD

**Issue by ArmanHayots** [mozilla-mobile/fenix#11083]
If FF can read QR's, why it can't share them?
I missed it much when want to give guys some link directly from browser instead of sending URL over some messenger.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1449)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810002

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
