### ISSUE TITLE
[Bug] Clicking install button when on a PWA site doesn't do anything

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11096]
## Steps to reproduce
1. Go to: https://mobile.twitter.com/ or any PWA site.
1. Click install button in toolbar menu.
1. Doesn't do anything.

### Expected behavior
It should give a pop-up to add the website to homescreen or add it to the homescreen

### Actual behavior
Doesn't give any pop-up or adds the website to homescreen

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: 5.1.0-beta.3 and Nightly 200530 06:01

**Comment by SS1113** [comment]
@kglazko I want to say that I'm no longer experience this issue with recent builds.

Device: Motorola One Power, Android 10.
Fenix: **`Nightly 200618 18:01`** and **`5.2.0`**.

Thank you!

**Comment by kbrosnan** [comment]
Reporter says that it works for them. Closing
