### ISSUE TITLE
FNX-11960 ⁃ [Bug] Part of the FAB button is hidden beneath the system navigation bar in new tab tray layout

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11095]
## Steps to reproduce
1. Enable the new Tab tray layout
1. Open a tab
1. Close the tab
1. Push the tabs tray upwards
1. Observe that the FAB button is beneath the system's navigation bar

### Expected behavior
Part of the FAB button shouldn't be hidden

### Actual behavior
Part of the FAB button is hidden

### Device information
* Android device: Motorola One Power, Android 10.
* Fenix version: Nightly 200530 06:01
![Screenshot](https://user-images.githubusercontent.com/42088907/83344798-3bae6f80-a2fb-11ea-94fe-c505fb96e3d7.png)UNITO-UNDERSCORE!20200531-101239!

**Comment by boek** [comment]
After doing a little bit of investigation it looks like this could be a vendor specific bug. Do we have anyone with a modern moto device?

**Comment by SS1113** [comment]
@boek I have tested this with another device Xiaomi Mi A2, Android 10 on `Nightly 200608 06:00` and I was unable to reproduce the issue moreover I was unable reproduce it on the Motorola One Power, Android 10; the device it was reproducing on. Perhaps this is because the " Undo closed tab" is not working right now in the `Nightly 200608 06:00`

**Comment by ekager** [comment]
The snackbar should be working in the next nightly. Could you test again when you get it and let us know if you're still seeing this tomorrow? Thanks!

**Comment by SS1113** [comment]
@ekager Yes, definitely!

**Comment by SS1113** [comment]
@boek @ekager The issue is not reproducing on my device anymore. 


Tested on `Nightly 200609 06:00` on Motorola One Power, Android 10. Thanks!

**Comment by ekager** [comment]
Thank you!
