### ISSUE TITLE
[Bug]After logging in, the sync buttons are all gray and cannot be clicked.

### ISSUE THREAD

**Issue by tangzhui** [mozilla-mobile/fenix#11097]
## After logging in, the sync buttons are all gray and cannot be clicked. 
Automatic synchronization in phone settings has been turned on.
![img](https://user-images.githubusercontent.com/59478712/83346183-d5ead380-a34c-11ea-96e3-5174f6f15389.jpeg)UNITO-UNDERSCORE!eggsif!UNITO-UNDERSCORE!9923896281367646-01!

* Android device: xiaomi mix 2s，lineageOS 16.
* Fenix version: every version

**Comment by tangzhui** [comment]
Is there a way to solve this problem？

**Comment by liuche** [comment]
@tangzhui does this happen for a long time? Does it go away after the successful sync?

Eng: Maybe the first sync is running and taking a while? Are we not updating this callback correctly? Not always happening (i assume)

**Comment by liuche** [comment]
This might have been a fix for the bug where changing the engines during sync was disabled for state problems.

If it is, then we need to flag Content for new strings, but this is a release blocker.

**Comment by sblatz** [comment]
@tangzhui Hey! Can you try pressing the "sync now" button? This should fix it for you.

**Comment by tangzhui** [comment]
@sblatz Pressing "sync now" is useless and cannot be synchronized.

**Comment by tangzhui** [comment]
@liuche Only successfully logged into the account, but can not synchronize, not even once.
