### ISSUE TITLE
[Request] Change the wording to use months/dates instead of using "Spring 2020" in "What's New" article

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11105]
Article link: https://support.mozilla.org/en-US/kb/firefox-preview-upgrade-faqs

Clicking What's New in toolbar menu in Firefox Preview takes to the following [article](https://support.mozilla.org/en-US/kb/firefox-preview-upgrade-faqs) and the part of it says:

>Timeline

>If you meet the requirements (Android 5+ and Firefox for Android 59+), the migration from the Firefox for Android Nightly test version to the new Firefox started in early 2020. The Firefox for Android Beta and general release migrations will follow and the _**final migration will occur in Spring 2020.**_

Please change the wording "Spring 2020" to something like months/dates instead as it'll confuse the users who are waiting for the new Firefox for Android release as the Spring season can happen in different months in different parts of the world.

**Comment by ekager** [comment]
CC @jonichan is this something that we want to change?
