### ISSUE TITLE
FNX-11970 ⁃ [Bug] Can't download files from private GitHub repo

### ISSUE THREAD

**Issue by victor-bayas** [mozilla-mobile/fenix#11104]
## Steps to reproduce
1. Browse to a file of a private GitHub repo (works fine with public repos)
1. Long press the raw button and hit download
    1. Expected behavior
The file would download normally
    1. Actual behavior
It says Download Failed
![Screenshot](https://user-images.githubusercontent.com/49411169/83363285-e0619900-a35d-11ea-82a8-00d76262553d.jpg)UNITO-UNDERSCORE!20200531-164144!UNITO-UNDERSCORE!Firefox Nightly!
    1. Device information

* Android device: SM-G970F Android 10
* Fenix version: Nightly 200531 06:00 (Build #21520610)

**Comment by kbrosnan** [comment]
Dupe #7531
