### ISSUE TITLE
[Bug] Stuck image/text in the botton of screen when scrolling

### ISSUE THREAD

**Issue by Pixotas** [mozilla-mobile/fenix#11100]
## Steps to reproduce
Just by scrolling a webpage there's something strange in the bottom of the screen, and then image or text are stuck in a horizontal bar. It happens on several websites. Changing the URL bar to the top doesn't help. (See gif bellow) --> This error only can be recorded with external camera

### Expected behavior
Nothing happening when scrolling

### Device information
Huawei P30 Pro - Android 9 (EMUI 9.1.0)

* Fenix version: 
5.0.0 (Build #2121212137)
Also happens in Nightly 200531 06:00 (Build #21520610)

I have a Asus ZenFon 4 Selfie Pro with android 7.1.1 and I don't have this problem.

![Error Firefox](https://user-images.githubusercontent.com/63738804/83352458-61f7fd80-a343-11ea-9544-21763102da40.gif)

**Comment by SS1113** [comment]
@Pixotas can upload the video file instead of a GIF file? It'll make things more clear. However I do see some strange behaviour. I never saw this on my device, Motorola One Power, Android 10.

**Comment by Pixotas** [comment]
The website of the video is: [https://pplware.sapo.pt/apple/atualizacoes-recentes-do-ipados-trouxeram-problemas-serios-ao-ipad-pro/](url)

Video of the gif: [https://streamable.com/1llq9i](url)

Right now, in that webpage its happening on version 5.0.0 (Build #2121212137) but not in Nightly 200531 06:00 (Build #21520610). Its strange because sometimes I feel that its not a consistent behavior. Sometimes it happens at the beginning of the page other times is when I scroll all way down to the bottom. I don't know if it helps to identify any problem but I cant record that problem if I'm using the software to record the screen from the phone that has the problem -->The final video has no problems. I record it with another phone.

Another website that happens a lot is www.publico.pt for example this link: https://www.publico.pt/2020/05/31/sociedade/noticia/14-mortes-covid19-quatro-concelhos-lisboa-concentram-terco-novos-casos-1918835

But now I realize that in this last link the problem only happens after I block an ad with ublock (yellow bar --> see picture).
I block this ad in my Asus too and it works perfect! So I don't  know what's happening in my Hauwei.

Hope you can help.
![Screenshot_20200531_151552 (2)](https://user-images.githubusercontent.com/63738804/83355058-cb343c80-a354-11ea-8f70-b334f6284398.jpg)
