### ISSUE TITLE
FNX3-14392 ⁃ [Feature Request] Google Search Fixer Add-on

### ISSUE THREAD

**Issue by victor-bayas** [mozilla-mobile/fenix#11101]
### What is the user problem or growth opportunity you want to see solved?
Google serves and old version to Fenix users, this extension https://addons.mozilla.org/en/firefox/addon/google-search-fixer/ sends Chrome user agent to Google searches

### How do you know that this problem exists today? Why is this important?
Users would notice that they receive a distorted Google page and they might stop using Fenix

### Who will benefit from it?
Users who use FF add-ons

**Comment by cadeyrn** [comment]
Duplicate of #10044.
