### ISSUE TITLE
[Bug] Tabs Tray New Tab + Button Back Navigation Feels Off

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11111]
## Steps to reproduce
1. Open tabs tray
1. Press new tab FAB
1. Oops that was a mistake to tap that FAB, press back (and I think accidentally clicking a FAB _is_ a common mistake)

### Expected behavior
Takes me back to browsing and/or tabs tray

### Actual behavior
Exits app

### Device information
* Android device: ?
* Fenix version: ?

**Comment by liuche** [comment]
We can only have one GV open at a time, so this gets kind of tricky.

In terms of IA, this conflicts with how Homescreen works in the stack, maybe can ask UX, but probably not for release.
