### ISSUE TITLE
[Telemetry] Come up with a system for telemetry preferences that are not booleans

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#11119]
Similar to https://github.com/mozilla-mobile/fenix/issues/11118 we'd like for this to both be a toggle event and a metrics ping. Ideally these would follow some relatively generic format we can follow in the future.

**Comment by grigoryk** [comment]
For anyone following along, we'll most likely follow a pattern similar to what's been established in the migration ping - https://github.com/mozilla-mobile/android-components/blob/master/components/support/migration/src/main/java/mozilla/components/support/migration/TelemetryHelpers.kt#L67
