### ISSUE TITLE
FNX-11981 ⁃ [Bug] Remove scroll to tab logic

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#11113]
## Steps to reproduce
1. Open a tab 
1. Switch to private mode from tab switcher

### Expected behavior
1. Private tab is scrolled down a bit, hiding the branding and the private browsing button

### Actual behavior
1. Should stay scrolled to the top

**Comment by darkwing** [comment]
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/10997
