### ISSUE TITLE
FNX-11978 ⁃ JobCancellationException: Job was cancelled

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#11110]
https://sentry.prod.mozaws.net/operations/fenix/issues/8252183/?referrer=github_plugin

```
JobCancellationException: Job was cancelled

[INFO] Job was cancelled
```

**Comment by csadilek** [comment]
@rocketsroger just linking related add-on tickets:
https://github.com/mozilla-mobile/android-components/issues/6820
https://github.com/mozilla-mobile/android-components/issues/6372

**Comment by rocketsroger** [comment]
Thanks for pointing those out.  Looks like all of the events related to this issue is before A-C version `39.0.1`.  Closing since this has been fixed.
