### ISSUE TITLE
FNX-11989 ⁃ [Telemetry] Include state of preferenceToggled events in metrics ping

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#11118]
We would also like to include documentation about the default state of each toggle somewhere in the metrics.md or elsewhere so data science can consult it when doing analysis.

**Comment by AndiAJ** [comment]
Hi @sblatz , I've just checked this matter on the latest **`Nightly build 200611 from 6/11`** using a Google Pixel 3a (Android 10)

| Status  | Description | Notes |
| ------------- | ------------- | ------------- |
| ❓ | "preferences.sync" | Not sure what does it stand for. It's always set to **false**  |
| ✔️ | "preferences.sync_items" | |
| ✔️ | "metrics.toolbar_position" | |
| ✔️ | "preferences.show_search_shortcuts"  | |
| ✔️ | "preferences.show_clipboard_suggestions" | |
| ❌ | pref_key_search_browsing_history  | Not included in the metrics ping |
| ✔️ | "preferences.search_bookmarks" | |
| ❌ | pref_key_show_voice_search  | Not included in the metrics ping |
| ✔️ | "preferences.show_search_suggestions"  | |
| ✔️ | "preferences.search_suggestions_private" | |
| ✔️ | "preferences.open_links_in_a_private_tab" | |
| ✔️ | "preferences.tracking_protection" | |
| ✔️ | "preferences.telemetry" | |
| ✔️ | "preferences.remote_debugging" | |
| ✔️ | "preferences.accessibility_services" |  |

[Logacat](https://github.com/mozilla-mobile/fenix/files/4764070/togles.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test1106000)

[Logcat ("touch exploration")](https://github.com/mozilla-mobile/fenix/files/4764072/togles2.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test1106002)

As per https://github.com/mozilla-mobile/fenix/issues/11118 you've also mentioned the position of the position of the Toolbar, which as you can see is properly displayed in the metrics pings
On the other hand, I've noticed that nothing is displayed regarding the **Theme** setting.
Should this be included?

Please review. ☺️

**Comment by sblatz** [comment]
Thanks for verifying @AndiAJ! Sync sounds right (given you're probably not signed in. If you're singed in to FxA then it should say the items you're syncing, if you'd like to test that portion!)


`pref_key_show_voice_search`, `theme` should be included now! 

I'm putting up a PR now ot include `searchBrowsingHistory` as well.

**Comment by sblatz** [comment]
This is ready to test now!

**Comment by AndiAJ** [comment]
Hi @sblatz , **verified as fixed** on the latest **`Nightly build 200615 from 6/15`** Google Pixel 3a (Android 10)

| Status  | Description |
| ------------- | ------------- |
| ✔️ | "preferences.sync_items" |
| ✔️ | "metrics.toolbar_position" |
| ✔️ | "preferences.theme" |
| ✔️ | "preferences.show_search_shortcuts" |
| ✔️ | "preferences.show_clipboard_suggestions" |
| ✔️ | "preferences.search_browsing_history" |
| ✔️ | "preferences.search_bookmarks" |
| ✔️ | "preferences.show_voice_search" |
| ✔️ | "preferences.show_search_suggestions" |
| ✔️ | "preferences.search_suggestions_private" |
| ✔️ | "preferences.open_links_in_a_private_tab" |
| ✔️ | "preferences.tracking_protection" |
| ✔️ | "preferences.telemetry" |
| ✔️ | "preferences.remote_debugging" |
| ✔️ | "preferences.accessibility_services" |

**• Theme settings**
```
"preferences.theme": [
            "light"
          ]
```


```
"preferences.theme": [
            "dark"
          ]
```

```
"preferences.theme": [
            "system"

          ]
```

Regarding the previously mentioned **`"preferences.sync"`** matter I've opened #11595
