### ISSUE TITLE
FNX-11982 ⁃ Re-think the copy on the no-collections placeholder on the homescreen

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11112]
**Update from UX:**

New copy for when people don't have a collection:

> **Collect the things that matter to you**
> 
> Group together similar searches, sites, and tabs for quick access later.
> 
> [ Save tabs to collection ]

![image](https://user-images.githubusercontent.com/353960/84534708-b52a6280-acea-11ea-9e2f-8c3547a90c45.png)

* when people don't have any open tabs, we hide the button

- - -
original: 

### User Story
As a user, I want the no-collections placeholder to guide me on how to build a collection, so it is easy for me to try out this feature.

### Acceptance Criteria
I know what Collections are and how to build one. 

*Since the "Create Collections" button is no longer on the homescreen, we may want to re-think the no-collections placeholder copy OR consider adding a Create Collections button to homescreen.

![Screenshot](https://user-images.githubusercontent.com/42752644/83430346-80bdc900-a403-11ea-8ec4-8f0953e2ad42.png)UNITO-UNDERSCORE!20200601-122759!

**Comment by vesta0** [comment]
@betsymi this is the issue we chatted about yesterday. We need this copy to make it easier for users to discover and understand Collections.

**Comment by betsymi** [comment]
**Collect the things that matter to you**

Group together similar searches, sites, and tabs for quick access later.

[ Save tabs to collection ]

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200624 from 6/24`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200624-112315](https://user-images.githubusercontent.com/51314259/85522874-e1a97d00-b60e-11ea-8d9e-eb115840ad6c.gif)

@vesta0 & @liuche - I've filled #11877 as there's no practical use of the button if no tabs are open, please review. ☺️

**Comment by betsymi** [comment]
I see the snackbar confirmation says `Tabs saved!` Can we update this to `Collection saved!`

**Comment by AndiAJ** [comment]
Hi @betsymi , just logged #11889 for the snackbar confirmation update.
