### ISSUE TITLE
Control media playback via hardware buttons and other peripheral devices

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#1111]
### User Story
As a user I want to control media playback via hardware buttons and other peripheral devices, so I can conveniently use my browser to consume media

Android devices and peripheral devices (e.g. a bluetooth headset) can have hardware buttons for controlling playback (e.g. play/pause/volume). As a user I want to use those buttons to control the playback of media playing on a website; e.g. pausing the podcast I am listening to.

Technical: [Media Session API](https://developer.android.com/reference/android/media/session/MediaSession)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1489)

**Comment by Mugurell** [comment]
I see play / pause already works.
AC supports this after https://github.com/mozilla-mobile/android-components/issues/1846
GV supports this with https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/MediaElement.html#method.summary

Other actions to support are probably next / previous.
Maybe fast forward / rewind?

I think we'd need to know from UX what actions should be supported
(available media buttons are here - https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/KeyEvent.java#1914)
to then ask GV to expose what's possible to us.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811651

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
