### ISSUE TITLE
FNX2-13358 ⁃ [Bug] [Crash] IllegalStateException: FragmentManager has been destroyed

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#11125]
There's a recent significant spike of this crash in Nightly starting May, 19:
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6457309/

Various cases of this fixed before: https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+FragmentManager+has+been+destroyed+is%3Aclosed

Only known (unresolved) STRs are: https://github.com/mozilla-mobile/fenix/issues/8374

**Comment by liuche** [comment]
I'm going to dupe these to #10709, and I've moved STRs over bc these all have the same crash signature.

**Comment by liuche** [comment]
Did a backout of https://github.com/mozilla-mobile/fenix/commit/d46369696f1d43385f335936f50abb31176845ef on 5.1.1 - however, this means that #10718 will show up again in that build.
On master, #11240 will add some crash checks and then we'll monitor to see if this crash decreases on Nightly.

**Comment by liuche** [comment]
Looks like crashes have decreased greatly on nightly, closing this now!
