### ISSUE TITLE
FNX-12000 ⁃ [Bug] Intermittent org.mozilla.fenix.perf.StartupHomeActivityLifecycleObserverTest java.lang.AssertionError: Verification failed: number of calls happened not matching exact number of verification sequence

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#11129]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=304585027&repo=fenix

[task 2020-06-01T18:46:00.822Z] SUITE: org.mozilla.fenix.perf.StartupHomeActivityLifecycleObserverTest
[task 2020-06-01T18:46:00.822Z]   TEST: WHEN onStop is called THEN the metrics are set and the ping is submitted
[task 2020-06-01T18:46:01.421Z]   FAILURE
[task 2020-06-01T18:46:01.421Z] 
[task 2020-06-01T18:46:01.421Z] java.lang.AssertionError: Verification failed: number of calls happened not matching exact number of verification sequence
[task 2020-06-01T18:46:01.421Z] 
[task 2020-06-01T18:46:01.421Z] Matchers: 
[task 2020-06-01T18:46:01.421Z] StartupFrameworkStartMeasurement(frameworkStartMeasurement#1931).setExpensiveMetric())
[task 2020-06-01T18:46:01.421Z] PingType(startupTimeline#1932).submit(null()))
[task 2020-06-01T18:46:01.421Z] 
[task 2020-06-01T18:46:01.421Z] Calls:
[task 2020-06-01T18:46:01.421Z] 1) StartupFrameworkStartMeasurement(frameworkStartMeasurement#1931).setExpensiveMetric()
[task 2020-06-01T18:46:01.421Z] 
[task 2020-06-01T18:46:01.421Z] Stack traces:
[task 2020-06-01T18:46:01.421Z] 1)                                       io.mockk.impl.InternalPlatform.captureStackTrace  (InternalPlatform.kt:114)

[task 2020-06-01T18:46:01.421Z]                                            io.mockk.impl.stub.MockKStub.handleInvocation   (MockKStub.kt:256)

[task 2020-06-01T18:46:01.421Z]          io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation         (JvmMockFactoryHelper.kt:25)

[task 2020-06-01T18:46:01.421Z]                                   io.mockk.proxy.jvm.advice.Interceptor.call               (Interceptor.kt:20)

[task 2020-06-01T18:46:01.421Z]                 org.mozilla.fenix.perf.StartupFrameworkStartMeasurement.setExpensiveMetric (StartupFrameworkStartMeasurement.kt:62)
[task 2020-06-01T18:46:01.421Z]    org.mozilla.fenix.perf.StartupHomeActivityLifecycleObserver$onStop$1.invokeSuspend      (StartupTimeline.kt:85)

[task 2020-06-01T18:46:01.421Z]                     kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith         (ContinuationImpl.kt:33)

[task 2020-06-01T18:46:01.421Z]                                       kotlinx.coroutines.DispatchedTask.run                (DispatchedTask.kt:56)

[task 2020-06-01T18:46:01.421Z]                        kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely          (CoroutineScheduler.kt:571)

[task 2020-06-01T18:46:01.421Z]                 kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask        (CoroutineScheduler.kt:738)

[task 2020-06-01T18:46:01.421Z]                 kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker          (CoroutineScheduler.kt:678)

[task 2020-06-01T18:46:01.421Z]                 kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run                (CoroutineScheduler.kt:665)

[task 2020-06-01T18:46:01.421Z] 	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:48)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:27)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.MockKDsl.internalVerify(API.kt:118)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.MockKDsl.internalVerify$default(API.kt:109)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.MockKDsl.internalVerifySequence(API.kt:202)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.MockKKt.verifySequence(MockK.kt:226)
[task 2020-06-01T18:46:01.421Z] 	at io.mockk.MockKKt.verifySequence$default(MockK.kt:223)
[task 2020-06-01T18:46:01.422Z] 	at org.mozilla.fenix.perf.StartupHomeActivityLifecycleObserverTest$WHEN onStop is called THEN the metrics are set and the ping is submitted$1.invokeSuspend(StartupHomeActivityLifecycleObserverTest.kt:33)
[task 2020-06-01T18:46:01.422Z] 	at org.mozilla.fenix.perf.StartupHomeActivityLifecycleObserverTest$WHEN onStop is called THEN the metrics are set and the ping is submitted$1.invoke(StartupHomeActivityLifecycleObserverTest.kt)
[task 2020-06-01T18:46:01.422Z] 	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
[task 2020-06-01T18:46:01.422Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2020-06-01T18:46:01.422Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
[task 2020-06-01T18:46:01.422Z] 	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
[task 2020-06-01T18:46:01.422Z] 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:288)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:89)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:82)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
[task 2020-06-01T18:46:01.423Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest$default(TestBuilders.kt:45)
[task 2020-06-01T18:46:01.423Z] 	at org.mozilla.fenix.perf.StartupHomeActivityLifecycleObserverTest.WHEN onStop is called THEN the metrics are set and the ping is submitted(StartupHomeActivityLifecycleObserverTest.kt:31)
[task 2020-06-01T18:46:01.423Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-06-01T18:46:01.423Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-06-01T18:46:01.423Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-06-01T18:46:01.423Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-06-01T18:46:01.424Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-06-01T18:46:01.425Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2020-06-01T18:46:01.425Z] 	at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
[task 2020-06-01T18:46:01.425Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-06-01T18:46:01.425Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2020-06-01T18:46:01.425Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2020-06-01T18:46:01.425Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2020-06-01T18:46:01.425Z] 	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
[task 2020-06-01T18:46:01.425Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-06-01T18:46:01.425Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-06-01T18:46:01.426Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-06-01T18:46:01.426Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-06-01T18:46:01.426Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2020-06-01T18:46:01.426Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2020-06-01T18:46:01.426Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
[task 2020-06-01T18:46:01.426Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2020-06-01T18:46:01.426Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2020-06-01T18:46:01.426Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-06-01T18:46:01.426Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-06-01T18:46:01.426Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2020-06-01T18:46:01.426Z] 	at java.lang.Thread.run(Thread.java:748)

**Comment by mcomella** [comment]
Triage: let's see how often this fails.

Looking at https://sql.telemetry.mozilla.org/queries/70708, it appears to have failed twice in 9 days.

**Comment by mcomella** [comment]
This hasn't failed since 6/10 and only failed those two times: I think we can close as works for me.
