### ISSUE TITLE
[Bug] Tapping on a site notification doesn't open the website

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#11138]
## Steps to reproduce
Allow notifications from a website: Instagram, Reddit, twitter > when you receive a notification, open it

### Expected behavior
Fenix opens the page 

### Actual behavior
If firefox is not in the recent apps, Firefox will open to the homepage. If it is, nothing will happen.

### Device information
* Android device: 9
* Fenix version: Nightly 200602 06:01 (Build #2015743859)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1528)

**Comment by SinTan1729** [comment]
Can confirm that this happens on Android 10 too.

**Comment by jonalmeida** [comment]
Related (or can be closed as a duplicate of): https://github.com/mozilla-mobile/fenix/issues/11007

**Comment by kglazko** [comment]
Closed as duplicate of #11007

**Comment by jonalmeida** [comment]
Re-opening for product input on what we should do here.

**Comment by TitanNano** [comment]
@jonalmeida shouldn't this fire the `notificationclick` event on the sites serviceworker?

**Comment by jonalmeida** [comment]
Yes, it should! Let me keep this as a bug then and figure out the empty case separately. Thanks for catching!

**Comment by jonalmeida** [comment]
A-C bug where this will be investigated: https://github.com/mozilla-mobile/android-components/issues/7477

**Comment by sheikh-azharuddin** [comment]
Hello team
This bug was opened more than a year ago but sadly issue is not fixed...mozilla should focus on the basic features or functions or performance rather than just design elements...🙏😐

**Comment by tzarebczan** [comment]
Running into this as well, would be great to have fixed!

**Comment by eakraml** [comment]
Same here and as it can be seen it is since 2020 in the backlog of https://github.com/orgs/mozilla-mobile/projects/42#card-40627349

**Comment by danbates2** [comment]
Still an issue! Android 8.0 here.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809277

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
