### ISSUE TITLE
FNX-4806 ⁃ Continue media playback while Fenix is in background

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#1113]
### User Story:
As a user I want media playback to continue while the app is in the background; e.g. I want to continue listening to a podcast when switching to another app.

### Acceptance Criteria:
-I can play media in a tab and still hear it after I background the app

**Comment by lime124** [comment]
removed ux label -it's on our radar already as it's part of the Q3 plan

**Comment by sblatz** [comment]
E1 because we just modify this line: https://github.com/mozilla-mobile/fenix/pull/3007

**Comment by pocmo** [comment]
Adding QA needed: This is enabled in Nightly builds now. Starting QA process already before enabling it for all builds.

**Comment by softvision-miralobontiu** [comment]
On the latest Nightly 190821 (#12330640), the following pages play media even when the app is backgrounded: leparisien.fr, soundcloud.com, vimeo.com, but m.youtube.com doesn't.
Tested with OnePlus 5T (Android 9), and Sony Xperia Z2 tablet (Android 6.0.1).

**Comment by pocmo** [comment]
For YouTube that's the behavior the site enforces. For Fennec there's an add-on to circumvent it:
https://addons.mozilla.org/en-US/firefox/addon/video-background-play-fix

**Comment by softvision-miralobontiu** [comment]
Ok, thank you. I will close this issue based on your comment.

**Comment by pocmo** [comment]
I'll reopen this issue as a reminder that this is not enabled for release builds yet (Nightly only).

**Comment by pocmo** [comment]
> I'll reopen this issue as a reminder that this is not enabled for release builds yet (Nightly only).

That's happening here now:
https://github.com/mozilla-mobile/fenix/pull/4898
