### ISSUE TITLE
FNX-12006 ⁃ [Bug] Site titles in Collections are truncated too soon

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#11134]
## Steps to reproduce
Add some sites to a Collection
Expand this Collection
Check the site titles in the Collection

### Expected behavior
Information density should be maximized, and no space should be left unused so that most of the title can be displayed. 

### Actual behavior
As shown on the below image (in red), some space is left unused instead of expanding the site title.

![image](https://user-images.githubusercontent.com/218971/83503813-f25d4c00-a4c3-11ea-8881-a8ed1917ae22.png)

### Device information
* Android device: Redmi Note 7 MIUI 11 Android 9
* Fenix version: #2015743859

**Comment by AmyYLee** [comment]
The line width should match the width of "open tabs" line width. See below. Thanks
<img width="473" alt="Screen Shot 2020-06-02 at 17 42 27" src="https://user-images.githubusercontent.com/5992746/83572932-75989500-a4f8-11ea-85c7-c8f357d72c6b.png">

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 200603 (Build #21550609).

Devices:
OnePlus 6T (Android 9);
Huawei MediaPad M3 lite 10 (Android 7.0)

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 6/22** with **Google Pixel 4 XL (10).**
