### ISSUE TITLE
FNX-12004 ⁃ Restructure home menu

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#11132]
Let's restructure the home menu slightly to match better with the site menu. 

![image](https://user-images.githubusercontent.com/353960/83515831-47a25900-a4d6-11ea-8ed0-fd01a03e4020.png)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/11 with the following devices:
- Huawei MediaPad M2 (Android 5.1.1) 
- Nokia 6(Android 7.1.1) 
 - LG G7 FIT (Android 8) 
- Xiaomi Redmi Note 8T (Android 9) 
- Samsung Galaxy Note 10 (Android 10)
