### ISSUE TITLE
FNX-12009 ⁃ [Bug] Voice search preference is misplaced

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#11136]
The preference is misplaced, between "show search suggestions" and it's sub-setting "show in private sessions.

![](https://user-images.githubusercontent.com/4400286/82589498-1aa68b80-9b51-11ea-8fab-8b79d000bf5b.png)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fenix Nightly Build 21550608 GV 78 from 6/3 with Motorola Moto G6 (Android 8) and Huawei P9 Lite (Android 7).

The "Show voice search" setting is now above the "Show search suggestions" setting.
I will remove the qa:needed label.
