### ISSUE TITLE
FNX-12016 ⁃ List of unavailable add-ons is not refreshed

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#11144]
Related AC issue https://github.com/mozilla-mobile/android-components/issues/6855 

## Preconditions:
Have unavailable add-ons for Fenix Beta added to Fennec Beta.

## Steps to reproduce
1. Replace Fennec Beta with Fenix Beta;
1. Launch Fenix and go to the Add-ons list;
1. Scroll to the end of the list and tap the "Not yet available" section;
1. Delete one add-on from the list and tap the back button;
1. Tap the "Not yet available" and observe add-ons from the list; 
    1. Expected behavior
The deleted add-on is not displayed in the list.
    1. Actual behavior
The deleted add-on is displayed in the list and cannot be deleted, the "Failed to remove" pop-up message is displayed.
    1. Notes:
[Video](https://drive.google.com/open?id=1A81so8pvA8NIgBpm6OxGvc7KwaZ3zCKD)
The list is refreshed after leaving the Add-ons list and then going back.
    1. Device information

* Android device: Nexus 5 (Android 6.0.1); Motorola Moto G6 (Android 8), Huawei MediaPad M3 lite (Android 7).
* Fenix version: Beta migration build 76.0.0-beta.1 from 5/1.

**Comment by Amejia481** [comment]
@Diana-Rus we need to wait for https://github.com/mozilla-mobile/fenix/pull/11142 and test with a nightly build

**Comment by Amejia481** [comment]
This should be fixed on master

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly Migration Build 2015744433 GV 79.0a1 from 6/5 with Motorola Moto G6 (Android 8).
The deleted add-on is removed from the list.
