### ISSUE TITLE
FNX-12021 ⁃ IllegalArgumentExceptionorg.mozilla.geckoview.GeckoWebExecutor: URI scheme must be http or https

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11149]
Sentry report: https://sentry.prod.mozaws.net/operations/fenix/issues/8595438/?query=release%3Aorg.mozilla.fenix-5.1.0

IllegalArgumentExceptionorg.mozilla.geckoview.GeckoWebExecutor in fetch
fatalURI scheme must be http or https

Seen in 5.1 even though it should have been fixed already.

**Comment by ekager** [comment]
Looks like this is similar to https://github.com/mozilla-mobile/android-components/issues/6314 ie that it is the same trace in `AbstractFetchDownloadService`

**Comment by liuche** [comment]
This looks like it landed in AC 38, so it should definitely not be showing up in Fenix 5.1/AC 42.

**Comment by Amejia481** [comment]
It also looks similar to https://github.com/mozilla-mobile/android-components/pull/7160 it could be the case that the user was trying to download a file with a url that contains spaces, we can take a look in next spring

**Comment by ekager** [comment]
@Amejia481 would the sanitizing in https://github.com/mozilla-mobile/android-components/pull/7160 also take care of a URL with spaces?

**Comment by Amejia481** [comment]
In that pr we are only sanitizing in `browser-icons` this issue came from downloads, we should do sanitizing there too :)

**Comment by ekager** [comment]
Duh. 
Filed https://github.com/mozilla-mobile/android-components/issues/7238

**Comment by liuche** [comment]
Will look for this to decline in 5.2 Sentry.

**Comment by liuche** [comment]
Don't see this in 5.2 anymore, closing.
