### ISSUE TITLE
FNX-12018 ⁃ Show PBM CFR after user has accessed PBM multiple times

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#11145]
### User Story
As a user, I want to know that a PBM shortcut is available after I've accessed PBM a few times, because a user accessing PBM multiple times is a sign they may benefit from using a PBM shortcut instead of messaging all users right away.

### Acceptance Criteria
Show the existing PBM CFR on the _third_ time a user accesses PBM.

**Comment by mcarare** [comment]
@apbitner AFAIK this is already implemented this way, with the mention that if you have Focus installed it will be shown the first time you open private browsing.

**Comment by apbitner** [comment]
@mcarare Oh good to know, thank you. I've always had Focus installed so didn't realize it was working this way.
