### ISSUE TITLE
FNX-4807 ⁃ Show which tab is playing audio

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#1114]
### User Story
As a user I want to know which tab is playing audio and be able to pause each tab, so I know where audio is coming from specially when I have multiple tabs open.

### Acceptance Criteria:
-I can see which tab is playing audio
-I can easily pause audio for each tab

**Comment by vesta0** [comment]
@topotropic just a note to think about accessibility of the playback controls (e.g. too close to close tab x)

**Comment by topotropic** [comment]
**inactive (play)** 
- light theme: disabled_light_theme  #6620123A
- dark theme: disabled_dark_theme  #66FBFBFE
- private theme: disabled_private_theme  #66FBFBFE

**active (pause)** 
- light theme: accent_bright_light_theme  (#592ACB)
- dark theme: accent_bright_dark_theme  #592ACB
- private theme: accent_bright_private_theme  #592ACB

[1114-home-tile-with-play-button.pdf](https://github.com/mozilla-mobile/fenix/files/3519303/1114-home-tile-with-play-button.pdf)
[icons.zip](https://github.com/mozilla-mobile/fenix/files/3519237/icons.zip)

**Comment by liuche** [comment]
Questions:
- is this too busy?
- Verify that we have the API to determine which tab is playing.

**Comment by pocmo** [comment]
AC exposed that state already. I filed the linked issue above to add some more convenient helpers to examine that state.

**Comment by topotropic** [comment]
Happy to discuss the design, please ping me!

**Comment by sblatz** [comment]
@vesta0 will we want telemetry for engaging with this feature?

**Comment by sblatz** [comment]
@topotropic are you able to link me to the invision or design file for this? I'd like to see the margins between some of the other views (close button and play button, etc.)

**Comment by vesta0** [comment]
@sblatz I am guessing we can add telemetry for pause/play interaction? Anything else you recommend? I can file a telemetry issue for this + pause/play interaction on the notification.

**Comment by sblatz** [comment]
@vesta0 that sounds sufficient to me!

**Comment by topotropic** [comment]
@vesta0 can we figure out how many open tabs have audio on pause/play simultaneously with telemetry on pause/play interactions?

**Comment by vesta0** [comment]
@topotropic that's interesting, I will look into that.

**Comment by sblatz** [comment]
After some discussion with @topotropic she's going to look a bit into different placement of the play/pause icon. The engineering effort for this is done, and it will take like an E1 to change the placement. That being said, depending on when we get a decision on that this may slip to (very early) next sprint

**Comment by pocmo** [comment]
(Off-topic: We do not have any telemetry for play/pause from the notification. Do we need that? Please file and I'll add the needed hooks).

**Comment by sblatz** [comment]
This is the updated design @topotropic and I have landed on for now: 
<img width=350 src=https://user-images.githubusercontent.com/4400286/64719054-547ca980-d47c-11e9-9848-852e77b58a17.png>

**Comment by sv-ohorvath** [comment]
Verified as fixed on 2.0.0-rc2
