### ISSUE TITLE
FNX-12032 ⁃ [Bug] Tab Tray - Grey Screenshots After Sharing Tabs

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#11156]
## Steps to reproduce
1. Open tab tray
1. From three-dot menu, select Share Tabs
1. Complete the share; I used Email

### Expected behavior
Go back to the tray, nothing changes

### Actual behavior
Go back to the tab tray, no screenshot or favicon, just a grey box.

![Screenshot](https://user-images.githubusercontent.com/46655/83559845-d9ac6080-a4da-11ea-8436-9ec09e446216.png)UNITO-UNDERSCORE!20200602-135654!

### Device information
* Android device: ?
* Fenix version: ?

**Comment by jonalmeida** [comment]
This was the GV bug filed for issues like this which was recently fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1641064

Let's re-test this bug to see if it still happens.

**Comment by jonalmeida** [comment]
We shouldn't be getting incomplete screenshots now. We could probably close this after re-testing after re-testing.

**Comment by AndiAJ** [comment]
Hi, I've just check this matter on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

It seems that the **ESPN tab** is the one affected and it **not reproducible 100% of the times**.
The screenshot is lost but afterwards it gets refreshed and is properly displayed again

► Video
![20200619-094316](https://user-images.githubusercontent.com/51314259/85104895-1a61e480-b212-11ea-8717-966aef3b054a.gif)

@jonalmeida - Please review and advise. ☺️ 
I'll remove the QA needed label until further notice

**Comment by jonalmeida** [comment]
@AndiAJ that should be https://github.com/mozilla-mobile/android-components/issues/7413 which unfortunately looks very similar to this bug.

Closing this as verified for that reason.
