### ISSUE TITLE
FNX2-13370 ⁃ [Bug] "Run in Private Browsing" toggled off by Fenix update

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#11157]
## Steps to reproduce
1. Have "Run in Private Browsing" toggled on for your extensions.
1. Update Fenix (this happened for me for the 4.3 ~~> 5.0 and 5.0~~ > 5.1 updates).
1. Check the toggle for your extensions
    1. Expected behavior
The preference stays toggled on.
    1. Actual behavior
The preference is toggled off.

**Comment by liuche** [comment]
@Amejia481 do you know why this would be happening? Is there some pref that we're not persisting correctly?

**Comment by Amejia481** [comment]
@psymoon could have an idea!

**Comment by psymoon** [comment]
@liuche do we clear shared pref when there's a version upgrade?

**Comment by psymoon** [comment]
@opusforlife2 is this still happening? I can't seem to reproduce this issue.

**Comment by opusforlife2** [comment]
@psymoon I don't think so. Since Preview users have been shifted to Nightly, I update more frequently, and I would have noticed this problem.

**Comment by psymoon** [comment]
@opusforlife2 okay thanks, I will close this issue for now. Feel free to re-open should the issue come up again in the future.
