### ISSUE TITLE
[Bug] Cannot select text in some places

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#11151]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1642073

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0

Steps to reproduce:

```
Open a youtube video
Long press on the video title
```

Actual results:

Nothing

Expected results:

Text in the title is selected

I tested this in both Fennc 68.8.0esr and Firefox Preview 5.0. Also text in the video comments cannot be selected either. Text in video descriptions can be selected normally. Also double tap doesn't select text either, it instead send "click" (or touch?) events to the element.

I can select text in the same place using Chromium

**Comment by ekager** [comment]
I think we should move the Bugzilla bug to the GV component?

**Comment by ekager** [comment]
Possibly related to #10653

**Comment by ekager** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1643210

**Comment by ekager** [comment]
The Bugzilla was closed as invalid
