### ISSUE TITLE
[Bug] Tab Tray - No screenshot or favicon when opening tabs from collection

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#11155]
STR:

1. From the home screen, select "Open in tabs" for any collection
1. Tab tray expands

There are no favicons or screenshots displaying for each site, just a blank white square

![Screenshot](https://user-images.githubusercontent.com/46655/83557220-e333c980-a4d6-11ea-87c5-37b506aa9c08.png)UNITO-UNDERSCORE!20200602-132013!

**Comment by ekager** [comment]
I don't think we restore favicons so until you click into those tabs they won't appear (pretty sure this carried over from old home tabs behavior)

**Comment by darkwing** [comment]
Right, but we need some type of solution.  Maybe a default screenshot or favicon image of some kind.  Any empty square looks weird, like something is broken.
