### ISSUE TITLE
FNX-12039 ⁃ [Telemetry] Validate and document the different "app opened" telemetry

### ISSUE THREAD

**Issue by sraturi** [mozilla-mobile/fenix#11162]
This issue is opened to validate the three open methods (app_icon, custom_tab or link) to open the app, and decide if they are comprehensive or if another method should be defined.

## Description & Product Manager / Data Scientist User Story
"how was the app opened?" (home screen, app link, custom tab)

## What questions will you answer with this data?
Measuring startup performance

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by liuche** [comment]
I think this telemetry is already collected as an event, see `events.app_opened` https://github.com/mozilla-mobile/fenix/blob/master/docs/metrics.md

Does this need to be something different? If so, can you be more specific in comment 0?

**Comment by sraturi** [comment]
Hi @liuche, 

This ticket is intended to verify that the three open methods  (app_icon, custom_tab or link) to open the app are comprehensive or if another method should be defined. 

This also relates to #10616 as to clarify that the metric `events.app_opened` is only for a cold startup (seems like this part is done)

Originally, I left the description as a placeholder until we had a solid idea of the scope for the ticket.

**Comment by sraturi** [comment]
I am going to close this ticket since I could not find any new methods to open the application other than the onces already defined.
