### ISSUE TITLE
FNX-4809 ⁃ User Help Section

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1116]
As a user, I want access to help/support when I am unable to complete a task on Fenix. 

### Requirements:
Need to define help topics/understand frequent questions about problems we can't solve through design and copy in the app.

### Acceptance Criteria:
I can find help/support when I am unable to complete a task in Fenix by tapping on the 3dot menu>Help or  Settings>Help

**Comment by boek** [comment]
For QA:

The sumo page isn't published yet, so the link will take you to a page that tells you it hasn't been approved yet.

**Comment by mheubusch** [comment]
Here is the placeholder link in case you don't  already have it: https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/faq-android

**Comment by vesta0** [comment]
Sumo bug for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1545149

**Comment by sv-ohorvath** [comment]
Removed the QA label for now, since this was verified but has a blocking issue.

**Comment by jonichan** [comment]
Per my chat with Vesta or Betty a couple of weeks ago, I've set this up so users will go to the Firefox Preview KB page (https://support.mozilla.org/en-US/products/firefox-preview) when they go to Settings > Help. This is the same setup we have for Fennec Help.

I think a one-page FAQ might be a dead-end for users and will be difficult to keep it updated/revelant. The KB landing page will allow users to navigate to any Fenix article they want.  Let me know if you think an FAQ page is still preferred. 

The in-product link you have here will automatically redirect to the Firefox Preview KB page.

**Comment by vesta0** [comment]
@jonichan I think this is the right approach and I agree taht we don't need a separate FAQ page. Thank you so much for creating this!

Just a couple of hopefully small requests:

1. Under the Add bookmark section, can we add more details about the Quick Action bar, how it works, and how it looks like? Time permitting, it would be great to also have a separate article about Quick Action Bar and the option to quickly, share, bookmark a page, or enable reader mode when available? 

2. Under the Privacy section, would it be possible to add a new article on Tracking Protection (on by default, and how to add a site to exceptions list)

**Comment by vesta0** [comment]
Hi @jonichan it looks like the final link is different than the placeholder link. Do we need to change that? We have our code freeze today and need to make sure this is link is working in product.

**Comment by jonichan** [comment]
> Hi @jonichan it looks like the final link is different than the placeholder link. Do we need to change that? We have our code freeze today and need to make sure this is link is working in product.

The link you have (https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/faq-android) will redirect to the final link so no need to change things on your end.

**Comment by jonichan** [comment]
> > Hi @jonichan it looks like the final link is different than the placeholder link. Do we need to change that? We have our code freeze today and need to make sure this is link is working in product.
> 
> The link you have (https://support.mozilla.org/1/mobile/%25VERSION%25/%25OS%25/%25LOCALE%25/faq-android) will redirect to the final link so no need to change things on your end.

I don't know why there are %25 showing up in the string, but it should be: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/faq-android

**Comment by boek** [comment]
@jonichan which link should I use? I just updated it to use https://support.mozilla.org/en-US/products/firefox-preview

**Comment by sv-ohorvath** [comment]
The Help pages from the main menu and the settings menu now go to https://support.mozilla.org/en-US/products/firefox-preview. Assuming this is the correct link, this is fixed on the 1.0.0 rc2 build.
