### ISSUE TITLE
FNX-4810 ⁃ Pause media playback in Private Browsing when minimizing the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1117]
As a user I want to have the option to pause media playback in Private Browsing when minimizing the app, so I can protect my private content. 

Acceptance Criteria:
-I have the option to pause media playback in my browser media settings.
-When enabled, I can't hear media playback when I minimize my private browser while playing audio/video.

**Comment by vesta0** [comment]
@sv-ohorvath isn't this the current behaviour?

**Comment by sv-ohorvath** [comment]
No, i.e. soundcoud.com still plays in the background.

**Comment by vesta0** [comment]
@cpeterso is there a related GV API for this?

**Comment by cpeterso** [comment]
> is there a related GV API for this?

To stop media playback, I am told that Fenix needs to call `session.setActive(false)` to when a tab (or the app) is backgrounded. I don't see any calls to `setActive()` in Fenix or AC code, but I did find the AC PR to _remove_ calls the `session.setActive()`: mozilla-mobile/android-components#703

**Comment by cpeterso** [comment]
OTOH, isn't "YouTube continues to play in the background" a feature that we wanted? YouTube plays in the background in Fennec, but not Chrome (unless you pay for YouTube Red).

**Comment by yoasif** [comment]
>OTOH, isn't "YouTube continues to play in the background" a feature that we wanted? YouTube plays in the background in Fennec, but not Chrome (unless you pay for YouTube Red).

Yeah, and I don't know that it makes sense to pause playback if I minimize something. On desktop, for example, minimizing private windows keeps media playback going, so I don't quite understand why this is required for Fenix.

**Comment by vesta0** [comment]
This behaviour is in parity with Fennec. We will re-evaluate whether it needs to change post-mvp.

**Comment by emilio** [comment]
Note that Fenix also keeps playing if you _close_ the app (#1679), not only minimize it. Fennec definitely doesn't do that, and I don't see how that would make sense.

Also, killing the battery is not fun, probably is worth stopping _some_ videos at least... But I agree that's probably more refinement.

**Comment by cpeterso** [comment]
@vesta0 - Given Emilio's description of the problem, I think we should reopen his issue #1679 and fix it for Fenix MVP (using the `session.setActive(false)` steps I [described above](https://github.com/mozilla-mobile/fenix/issues/1117#issuecomment-484168768)). If the Fenix app is no longer accessible in Android's app switcher, there's nowhere for the user to go back and stop the media playback.

As for leaving media playing when the app is backgrounded/minimized (this issue), we might want to add a persistent notification in the notification bar so users can find the app playing audio.

**Comment by agi90** [comment]
The right way to do this in GeckoView is setting [`setSuspendedMediaWhenInactive`][0] to true. 
I don't think Fenix should call `setActive`, sorry for the confusion (my bad).

[0]: https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSessionSettings.html#setSuspendMediaWhenInactive-boolean-

**Comment by grigoryk** [comment]
FWIW, this user story seems like a bug to me. I use my browser as a media player a lot, and having media stop while the app is backgrounded is a problem to fix, not a feature to introduce.

**Comment by grigoryk** [comment]
Let's close this for now, and re-assess if necessary. I'm not sure the "private mode" distinction adds enough subtlety to justify pausing media in the background. Battery concerns are broader and pretty sublte... Feel free to re-open if I'm wrong here.

**Comment by yoasif** [comment]
FYI, Brave is now *advertising* the non private mode version of this as a feature. https://twitter.com/BraveSampson/status/1122950280520269825

**Comment by sv-ohorvath** [comment]
Please note that this was a feature request, not a requirement. 
As an idea why: watching media in private mode is because sometimes you want to keep THAT kind of media private. If you need to close the tab it requires 2 taps, too many for some 😁  I just thought it could be a nice feature for PB only. If you need to keep playback running, you can play it in normal browsing.

**Comment by yoasif** [comment]
It is an interesting idea - would be curious to see how users react. Another wrinkle might be for users who use "always private" browsing (an option on desktop). 

FWIW, Focus pauses video. Fennec in private tabs does not.

**Comment by sebast889** [comment]
Why not add a "Stop playing media when browser is minimized" option so that users can toggle that if they want?

**Comment by vesta0** [comment]
@sebast889 that's a great idea! I added it to the user story.

This is a feature request and it aligns with what Focus does today. We will re-evaluate whether we want to build this as an option in Fenix post-mvp. Keeping it open as a p2 in the backlog.

**Comment by lime124** [comment]
removed ux label -it's on our radar already as it's part of the Q3 plan

**Comment by topotropic** [comment]
@vesta0 what default do we want to support here?

**Comment by vesta0** [comment]
I think we should always default to play and but give our users the option to change that to pause in the settings.

**Comment by pocmo** [comment]
The situation has changed a bit since we are now showing the media notification for private tabs (without any details revealing the website), see:
https://github.com/mozilla-mobile/fenix/issues/4759#issuecomment-524863816

* We default to play.
* The user can pause/resume media from the notification.
* The user can swipe the notification away (if paused).

With that new behavior do we still need a "pause when minimized" functionality? CC @topotropic

**Comment by vesta0** [comment]
@pocmo that's a great point. @topotropic do you have any concerns around this particular use case: User is viewing a private video in private mode, and minimizes the tab in order to maintain their privacy but the media keeps playing until they initiate a second action to either close the private app or pause the media through the notifications.

**Comment by topotropic** [comment]
Sounds good to me, thanks!

**Comment by vesta0** [comment]
Thanks @topotropic just in case my question wasn't clear: the use case I mentioned above may raise some concern with privacy focused users. From a user experience perspective, I was wondering if you thought we were designing in accordance to a privacy centric user's expectation. 

It sounds like you don't think that's an issue, and you are good with the media not being paused in both private browsing and regular browsing. If that's the case, we can close this issue.

**Comment by topotropic** [comment]
Thanks for the clarification, @vesta! 
I believe that this is a legit way to move forward for now and inspect and adapt  long-term
