### ISSUE TITLE
FNX-12055 ⁃ [Bug] The https://www.rbi.org.in/ website is not loading

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#11178]
## Steps to reproduce
1. Go to https://www.rbi.org.in/
    1. Expected behavior
The website loads correctly.
    1. Actual behavior
The website does not load.
    1. Device information

* Android device: OnePlus 6T (Android 9)
* Fenix version: Firefox Nightly 200603 (Build #21550609), Firefox 68.9.0 (see issue https://bugzilla.mozilla.org/show_bug.cgi?id=1642074 for additional information)

**Comment by kbrosnan** [comment]
Webcompat https://webcompat.com/issues/17820
