### ISSUE TITLE
[Bug] Removing from top sites fails sometimes

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11188]
## Steps to reproduce
add the same site a large number of times to top sites
Go to overview and remove the first top site repeatedly
After the first few times the site is not removed from top sites

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that this issue is reproducible using the latest version of Firefox Preview Nightly 200604 (Build #21560609).

Devices:
OnePlus 6T (Android 9);

**Comment by liuche** [comment]
Let's dupe to keep things tidy: #14538
