### ISSUE TITLE
FNX2-13371 ⁃ [Bug] Tab Tray: Spot displayed on the "New tab" floating action button

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11180]
## Steps to reproduce
1. Open the Tabs Tray
1. Check the "New Tab" button

### Expected behavior
No UI issues, properly displayed "New Tab" button

### Actual behavior
A spot get's displayed on "New Tab" button

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: Nightly Build 200603 from 6/3

### Notes
► Screenshots
![rsz](https://user-images.githubusercontent.com/51314259/83630308-44759e80-a5a4-11ea-8a53-21ce2a6d7314.png)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200603-140821!

► Video
![20200603-131925](https://user-images.githubusercontent.com/51314259/83630358-5fe0a980-a5a4-11ea-880d-66fa32a55965.gif)

**Comment by darkwing** [comment]
I can reproduce this, though the "spot" doesn't stay there, it disappears after about 1 second.

**Comment by ekager** [comment]
@darkwing can you still repro?

**Comment by abodea** [comment]
@ekager I'm still able to reproduce this issue on the latest **Nightly 7/13** with **Google Pixel 4 XL (11).**

![20200713-162548](https://user-images.githubusercontent.com/42831109/87311316-c3f17880-c527-11ea-9fa7-fd721c45ca97.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-093350](https://user-images.githubusercontent.com/51314259/91269426-c62e3000-e77f-11ea-9330-729b3dc08024.gif)
