### ISSUE TITLE
Improve performance of async tab load when opening tabs tray

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11185]
**Release criteria** for opening tabs tray: Target 250ms from input to UI rendered. (note: 2x: entry points from browser and home screen are different)

In [our performance analysis](https://github.com/mozilla-mobile/fenix/issues/7512#issuecomment-641621240), we determined the tabs tray appears quickly enough but **the tabs take a long time to appear.** The duration they take to appear seems to at least somewhat tied to the number of tabs opened. **On a GS5 with 8 open tabs, we're at 462ms,** about 212ms longer than we want to be.

We should improve the performance of the async tab loading.

Speculation: perhaps the tabs take so long to appear because they're blocking on getting the tab previews before loading the tabs. If not, I'd expect loading tabs to be fast because it's just a bunch of strings.

If so, this is a problem: it'll get very unperformant with a large number of open tabs. We should load the tabs and asynchronously fetch the tab when they're needed.

- - -
_The original text of this issue is described here._

## Prerequisites
Open more than 10 websites in different tabs

## Steps to reproduce
1. After opening twitter.com (12th tab)
1. Open the Tabs Tary
1. Tap any other open tab
1. Open the Tabs Tary
1. Tap and open another tab
1. Open the Tabs Tary
1. Swipe delete the first 3 open tabs 

### Expected behavior
Steps 4,6: Responsive Tabs Tray, displays properly the open tabs
Step 7: The tabs should be deleted

### Actual behavior
Steps 4,6: Laggy display of the open tabs 
Step 7: Empty space left in the Tabs Tray, 
After a couple of seconds the tabs are displayed again as open and only after a couple of more seconds are properly deleted

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: Nightly Build 200603 from 6/3

### Notes
<details>
    <summary>Web site I've used (dropdown)</summary>

Home - YouTube
https://m.youtube.com/

Vimeo | The high-quality home for video hosting and watching
https://vimeo.com/

Dailymotion - the home for videos that matter
https://www.dailymotion.com/us

SoundCloud - Hear the world’s sounds
https://m.soundcloud.com/

Wikipedia
https://www.wikipedia.org/

Pocket: Explore
https://getpocket.com/explore?src=ff_android&cdn=0

Office 365 Login | Microsoft Office
https://www.office.com/

Microsoft – Pagina de pornire oficială
https://www.microsoft.com/ro-ro/

Internet for people, not profit — Mozilla
https://www.mozilla.org/en-US/exp/

Facebook - Log In or Sign Up
https://m.facebook.com/

Instagram
https://www.instagram.com/

Explore / Twitter
https://mobile.twitter.com/explore

</details>

► Video
![20200603-162214](https://user-images.githubusercontent.com/51314259/83643806-2bc3b380-a5b9-11ea-94ef-505a107672fa.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1606)

**Comment by SS1113** [comment]
@AndiAJ I filed the bug  #11174, do you think this bug is the same as the one I  filed.

**Comment by jonalmeida** [comment]
`BrowserIcons` has a [similar use case](https://searchfox.org/mozilla-mobile/rev/7cfc88aaee89e7c10c9109ddf330ea4c2f9ac9c2/android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt#162-169) to `BrowserThumbnails` that we should try to re-use as well: attempt to load the icon async and cancel the job if the view is detached.

**Comment by mcomella** [comment]
> I'm working on [mozilla-mobile/android-components#7313](https://github.com/mozilla-mobile/android-components/issues/7313) which is to reduce the amount of tabs tray updates we are doing on a thumbnail update, but we should re-test this after that lands.

I retook the numbers and it's improved but still outside of our RC: 423.33ms compared to 462ms originally.

@jonalmeida Can you address the issue?

**Comment by mcomella** [comment]
I retook some numbers given jonalmeida had already made my suggested change. Profile: https://share.firefox.dev/2Y6Ye5F - my brief look shows that we're basically just waiting for inflation and view initialization
- Anecdotally, on P2 with 50 tabs open, the tabs appear fairly quickly (which wasn't the case before)
- On GS5, with 8 tabs, I get 417ms over 4 runs (times: 427, 388, 347, 504)
- On GS5, with 50 something tabs, I get 415ms over 3 runs removing 1 outlier (4 runs total; times: 408, 668, 403, 435)

Looking at the values, it seems like there may be a small impact from the number of tabs but not in a super significant way like before. Otherwise, it seems fairly stable near 400ms. Let me check with esmyth on how we want to prioritize.

**Comment by mcomella** [comment]
Looking at the profile (caveat: it was one run and may not be representative), some areas we might be able to improve upon are (and these may not the lowest hanging fruit):
- Each view inflated in the RecyclerView takes between 6.4ms-24ms https://share.firefox.dev/2Cf0wHh: perhaps we could inflate these asynchronously when inflating the tabs tray and insert them into the RV to save time
- Creating a dialog fragment and attaching everything to it seems to add at least 20ms https://share.firefox.dev/2UPoCP4: in `activityCreated` and `onStart`. If we attached the view to the current view hierarchy, we'd gain performance
- We could inflate the TabsTray and its content asynchronously before the tabs tray button is every clicked

I'm not sure what the best trade-off is between encapsulation and performance.

**Comment by jonalmeida** [comment]
> Each view inflated in the RecyclerView takes between 6.4ms-24ms https://share.firefox.dev/2Cf0wHh: perhaps we could inflate these asynchronously when inflating the tabs tray and insert them into the RV to save time

I like this idea! We can use some simple tricks here by holding a reference to the `Recycler` so that can re-use them after the first creation.

I'm leaving the other suggestions up to the Fenix team that have more knowledge on the ins and outs of how the fragment lifecycle lives in the app.

**Comment by mcomella** [comment]
> Looking at the values, it seems like there may be a small impact from the number of tabs but not in a super significant way like before. Otherwise, it seems fairly stable near 400ms. Let me check with ecsmyth on how we want to prioritize.

@jonalmeida fwiw, ecsmyth wants me to focus on other areas so I don't think this is a high priority if your have other things to look into.

**Comment by jonalmeida** [comment]
Some work has been added to have multiple adapters on the TabsTray which have perceived and runtime perf and we see some [noticeable issues][0] already.

Putting the view pool fix aside for now, we have multiple view pools for each adapter which may make this a more compelling reason to reduce our memory footprint.

For the initial load, we could [wait for the `TabsAdapter` to populate][1] first before we add additional adapters to the `RecyclerView`.

[0]: https://github.com/mozilla-mobile/fenix/pull/13012#issuecomment-665145960
[1]: https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#registerAdapterDataObserver(androidx.recyclerview.widget.RecyclerView.AdapterDataObserver)

**Comment by jonalmeida** [comment]
I'm going to pick this up next week to land the scrolling changes to #13293 that is linked to this issue.

**Comment by buttercookie42** [comment]
Just stumbled across this, too. With Fennec, the tabs tray always populates instantly, whereas with Fenix when the tabs tray pops up, I always see the "Open tabs are shown here" message for at least a split-second (or sometimes a bit longer).

**Comment by samlux04** [comment]
Yes tabs tray so slow to open. Long animation and then a second empty space before tabs appeared. More tabs more longer the tabs tray load. Why can't it be like chrome. Instant tab open even live previews if the tab has video playing. If the thumbnails causing the problem maybe add new tabs tray layout without thumbnail, just website icon and title. Until the tabs tray issue fixed.
The only redeeming quality of Firefox mobile is the addons. The browsing experience is so horrible. So sluggish.

**Comment by MarcLeclair** [comment]
We're going to wait for the compose changes to verify the performance. 

Dependent on:  https://github.com/mozilla-mobile/fenix/issues/21318

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807363

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
