### ISSUE TITLE
FNX-12062 ⁃ [Bug] The search widget prompt is still triggered even when the searches are made in PB (Discoverability Experiment)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#11184]
## Steps to reproduce
1. Launch Fenix.
1. Access PB mode.
1. Perform 3 searches and return to the home screen (the search widget prompt is not displayed).
1. Return to normal browsing.
    1. Expected behavior
The search widget should not be displayed.
    1. Actual behavior
The search widget prompt is still triggered even when the searches are made in PB.
    1. Device information

* Android device: Google Pixel 4 XL (10)
* Fenix version: Latest Debug build (from master).

![20200603-161406](https://user-images.githubusercontent.com/42831109/83641205-e05bd600-a5b5-11ea-8153-142ee9a4edee.gif)

**Comment by sblatz** [comment]
This is working as expected, so long as the prompt is not actually showing on the private browsing screen :)
