### ISSUE TITLE
Add deep link routes to the DeepLinkIntentProcessor

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#11197]
`DeepLinkIntentProcessor` supports a number of links to navigate the user around the app.

The following were identified as missing in a recent test by the Mobile Engagement team.

* [x] `fenix://settings_notifications` — take the user to the notification settings page
* [x] `fenix://settings_privacy` — take the user to the privacy settings page.
* [x] `fenix://settings_search_engine` — take the user to the search engine page, to set the default search engine.
* [ ] ~`fenix://turn_on_sync_email` — take the user to the FxA sign up/sign on via email page (additional to `turn_on_sync`)~
* [x] `fenix://home_collections` — take the user to the home screen to see the list of collections.
* [x] `fenix://home_history` — take the user to the history list.
* [x] `fenix://home_bookmarks` — take the user to the bookmarks list
* [x] `fenix://settings_logins` — take the user to the settings page to do with logins (not the saved logins).

### How do we know this is done:
* [x] Added the routes to `DeepLinkIntentProcessor`
* [x] Add tests to the `DeepLinkIntentProcessorTest`.

**Comment by cbonacuse** [comment]
@jhugman below are other deeplinks that we are requesting:

- [ ] deeplink to home  — take the user to the home screen (**fenix://home exists, but this is documented as existing for homepage settings - can you confirm if this is correct?)

**Comment by cbonacuse** [comment]
@jhugman two more related to the below screenshots:

- [ ] deeplink to ETP settings — take the user to the ETP settings screen within the app
![Screenshot_20200616-184758](https://user-images.githubusercontent.com/60749496/84824277-a6df8d80-afed-11ea-99cf-de7eda4a916f.png)

- [ ] deeplink to add-ons — take the user to the add-ons screen
![Screenshot_20200616-184806](https://user-images.githubusercontent.com/60749496/84824312-b6f76d00-afed-11ea-9b92-801e8ed4c014.png)

**Comment by jhugman** [comment]
@cbonacuse screenshots is a great way to specify where the deep links are meant to go!

**Comment by jhugman** [comment]
* [X] `fenix://settings_tracking_protection` deeplink to ETP settings — take the user to the ETP settings screen within the app: now 
* [X]  `fenix://settings_addon_manager` deeplink to add-ons — take the user to the add-ons screen
* [X] `fenix://home` deeplink to home — take the user to the home screen (** `fenix://home` exists, but this is documented as existing for homepage settings - can you confirm if this is correct?)

@cbonacuse I couldn't tell from your stress test results if you wanted the "turn_on_sync" to go straight to the email signin on or to offer the choice of pairing via scanning a QR code. The first is hard, but the second is already implemented. 
 
<img width="300px" src="https://user-images.githubusercontent.com/99338/85578554-0fec8400-b632-11ea-8446-f61186f89247.png" title="Turn on sync by signing in with your email"> <img width="300px" src="https://user-images.githubusercontent.com/99338/85578549-0f53ed80-b632-11ea-81f1-74c1f2ac7d63.png" title="Offer to pair with your desktop with a magic QR code">

Wasn't sure if you were aware of the existence of the second.

**Comment by cbonacuse** [comment]
Thanks @jhugman - I actually just did the second today myself (pairing via QR code). Let's go that route since it's already implemented, and I think it provides a better experience since the user has a choice.

**Comment by cbonacuse** [comment]
Hi @jhugman & @ekager! I just did UAT on this and sent a push to my Google Pixel 3 device (OS 10, Nightly build 200803) for each deeplink, and all of them just opened the app to my homescreen but didn't land me on any of the specified deeplinks. Is there something I am doing wrong?

**Comment by cbonacuse** [comment]
Update: I forgot we have to add `-nightly` to the deeplink format for Nightly testing, so this worked and resolved most of the issues I was seeing!

The only deeplinks that were not opening the correct destinations were `fenix://home_history` and `fenix://home_bookmarks`. They landed in the app on the homescreen, but did not open the history or bookmarks page, respectively. 

cc: @jhugman @ekager

**Comment by ekager** [comment]
@cbonacuse Great!! Looks like those two are defined as `urls_bookmarks` and `urls_history` - I think we changed them because defining as "home" when we weren't landing on home was confusing.

**Comment by ekager** [comment]
Sorry about that, updated comment 0 as well

**Comment by cbonacuse** [comment]
@ekager no worries! Thanks for the update - that fixed them :) Thank you for your help Emily & @jhugman!
