### ISSUE TITLE
FNX-12071 ⁃ [Bug]Tab Tray: Screenshots are broken after delete+undo

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11192]
## Prerequisites
Have a couples of open tabs

## Steps to reproduce
1. Swipe delete a tab
1. Undo the deletion
1. Close a tab by using the 'x' (close button)
1. Undo the deletion
1. Tap the ⋮ button select "Close all tabs"
1. Undo
1. Check screen shots

### Expected behavior
After each deletion undo, the screenshots should be properly displayed

### Actual behavior
After each deletion undo, it looks like minimized versions screenshots are displayed

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200603 from 6/3

### Notes
► Screenshot
![rsz](https://user-images.githubusercontent.com/51314259/83656223-f2467480-a5c7-11ea-9264-f690130569f5.png)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200603-174407!

► Video
![20200603-174150](https://user-images.githubusercontent.com/51314259/83656284-038f8100-a5c8-11ea-8e01-ebfafcaad8c0.gif)

Related #10921

**Comment by liuche** [comment]
@gabrielluong how do you want thumbnails issues to get tracked? Just in the board, or through a label, or something else?

**Comment by gabrielluong** [comment]
> @gabrielluong how do you want thumbnails issues to get tracked? Just in the board, or through a label, or something else?

Most of the thumbnail issues would be fixed in AC. So, I think for tracking purposes we can put it in the tabs tray board as a stopgap.

**Comment by jonalmeida** [comment]
This was fixed as part of https://github.com/mozilla-mobile/android-components/issues/7352.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly 200618 from 6/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200618-140320](https://user-images.githubusercontent.com/51314259/85013785-d87f6280-b16d-11ea-9293-f62f0fb9ad4b.gif)

► Video
![20200618-140658](https://user-images.githubusercontent.com/51314259/85014237-90147480-b16e-11ea-957e-5f4130e7672d.gif)

**Comment by AndiAJ** [comment]
Hi @jonalmeida , noticed that on **`Fenix 79.0.1-beta.1 from 6/30`** the screenshots are replaced with the placeholder icons after delete + undo
Is this the expected behaviour? please advise

**Comment by jonalmeida** [comment]
@AndiAJ yes, this is expected behaviour. We are deleting the thumbnails on the device.

We have a separate bug to figure out how to keep the thumbnail until after the undo toast is gone. 🙂
