### ISSUE TITLE
[UX] Empty state when waiting for search engines to load

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11195]
As part of #9935 we can't block the main thread to wait for search engines to load, so we are making it async (as part of that bug, not the scope of this bug).

This issue is for the empty state for the Search page (in the case that the search engines haven't loaded).

Should we have text? or a loading icon? Some kind of affordance in the case when **we're waiting for search engines to load off a network call.**

**Comment by AmyYLee** [comment]
Assigned to @brampitoyo

**Comment by brampitoyo** [comment]
@liuche The wait can be longer than 10 seconds. During that period of time, users are likely to want to start a fresh search.

In the small chance that they go to Search Settings, we would also not be able to show anything there.

When we have to wait for search engines to load, I would recommend:

- Set the default search engine to a default that would work in most – unfortunately, not all – scenarios: Google.
- Behave as if the “Shortcuts” button is toggled off. Let’s not show “This time, search with”.
- In fact, let’s excise the “Shortcuts” button from the UI entirely. Don’t show it, until we have fetched a list of locale-specific search engines.

When the search engine have finished loading, I would recommend:

- If the user hasn’t entered anything in the address bar:
    - Show the “Shortcuts” button.
    - Select it – this will show “This time, search with” along with locale-specific search providers
- If the user has entered something in the address bar.
    - Show the “Shortcuts” button.
    - But don’t select it – the user will already be shown keyword suggestions from Google, and we don’t want to interrupt those.

What do you think?

**Comment by brampitoyo** [comment]
Assigning @liuche for follow-up feedback. If my suggestion sounds reasonable, feel free to mark it as ready to implement :-)

**Comment by liuche** [comment]
Ah, thank you @brampitoyo!

cc @sblatz this might be helpful for the #9935, but for longer term - since my understanding from your other comments is that it's not possible to launch the search screen at all because the current SearchFragment has some expectations about search engines.

**Comment by vesta0** [comment]
@liuche @brampitoyo what is the next step here?

**Comment by brampitoyo** [comment]
@liuche @vesta0 My recommendation is to implement the behaviour above in https://github.com/mozilla-mobile/fenix/issues/11195#issuecomment-640390683

**Comment by liuche** [comment]
We talked about this in planning, and there are some changes to how the network call works - we now provide some offline default engines even if the network call has failed.

Could QA test to see if this case still happens? Particularly on slow devices, or bad network conditions. (Or if there is a bug 

If the offline default engines are present and we don't have the "no engines state" then I think we can close this bug.

**Comment by softvision-miralobontiu** [comment]
Hi all!
Verified on slow devices that we don't have the "no engine state" or empty state when the connection is bad or lost.

Environment:
* Xiaomi mi4i (Android 5.0.2), Samsung Galaxy Tab A6 (Android 5.1.1), Sony Xperia Z5 Premium (Android 7.1.1), Nexus 6 (Android 7.1.1), and Huawei MediaPad M2 (Android 5.1.1)
* 10/29 Nightly build
