### ISSUE TITLE
[Bug] Private Tab Downloads not cleared on Close all private tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11190]
## Steps to reproduce
Download something in private tab
Click close all private tabs

### Expected behavior
Private downloads notification goes away

### Actual behavior
It remains, potentially violating privacy

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by Amejia481** [comment]
There is a partial fix on Nighlty now we remove the **completed download notifications** from private tabs when they get closed but we don't stop active downloads as this will require some extra work to make the user aware that we are going to cancel the downloads that will be covered here https://github.com/mozilla-mobile/fenix/issues/18160. QA team and @s-ankur could you help us to confirm. Thanks in advance.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 2/3 with Google Pixel 4 XL (11).
Note that the completed download notification went away when I closed the private tabs.

**Comment by Amejia481** [comment]
Thanks @abodea !

**Comment by s-ankur** [comment]
Hello @Amejia481. Delete browsing data on Quit is supposed to function like private browsing right?

So it does work in private browsing but the downloads are still there on delete browsing data on quit

**Comment by Amejia481** [comment]
> Delete browsing data on Quit

👋🏽 @s-ankur I'm not completely sure how should "Delete browsing data on Quit" work in relation to downloads but you could open a separate bug and we would investigate about it.
