### ISSUE TITLE
FNX-4812 ⁃ [Meta] Shortcuts

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#112]
### Why/User Benefit/User Problem
As a user, I want to quickly use a specific search engine for a search without having to change my default search provider.

### Acceptance Criteria
-UX completed
-User stories completed
-Strings written and approved
-QA completed
-Localization done

### What / Requirements (Added by PM and Eng Manager)
-UX Designs #195 
-User stories

**Comment by st3fan** [comment]
I think from an A-C perspective this is mostly a Fenix-specific feature that we would not create a component for.

**Comment by sblatz** [comment]
<img width="368" alt="screen shot 2019-01-28 at 12 47 37 pm" src="https://user-images.githubusercontent.com/4400286/51865377-e8896e80-22fa-11e9-8b1f-3a8bf0ca980c.png">
