### ISSUE TITLE
FNX-12084 ⁃ Send multiple tabs to a device.

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#11203]
### What is the user problem or growth opportunity you want to see solved?
Not sure.

### How do you know that this problem exists today? Why is this important?
So you have 30 tabs open. You know you want to deal with them on your workstation. Send them to the workstation. Go on, I'll prepare a cup of tea for you meanwhile.

### Who will benefit from it?
Anyone who sends multiple tabs in a row.

**Comment by vesta0** [comment]
You can (1) create a collection with all your tabs and then (2) send the collection to another device through the share screen. Let us know if this addresses what you need.

**Comment by jtagcat** [comment]
Thanks for noting this, but I think it could be a little bit more obvious.

**Comment by vesta0** [comment]
Yes you are absolutely right!
