### ISSUE TITLE
FNX-12086 ⁃ Copy updates for synced tabs

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#11201]
* Update "Synced Tabs" to "Synced tabs" throughout the app
* Update "Tabs" to "Open tabs" in account settings

**Comment by Diana-Rus** [comment]
Hi verified with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) on Firefox Preview Nightly 6/15.
- "Open tabs" in account settings ✔️
![Screenshot_20200615-160911](https://user-images.githubusercontent.com/49859863/84664759-ad0b3680-af27-11ea-81bc-8cbf536145e2.png)

- "Synced tabs" in menu ✔️
![Screenshot_20200615-160945](https://user-images.githubusercontent.com/49859863/84664702-9a90fd00-af27-11ea-97f7-1230e5b5efd1.png)

- "Synced tabs" page title ✔️
![Screenshot_20200615-161006](https://user-images.githubusercontent.com/49859863/84664741-a8468280-af27-11ea-9261-50de81250d51.png)

Note: The "Synced tabs" string is not translated in all the available in browser app languages. I'll create a new ticket for that.
