### ISSUE TITLE
Allow undoing removing a session removed by back press

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#11204]
## Steps to reproduce
Close a page by pressing the back button, ending up on the home page (not in an another app). No undo message.

### Expected behaviour
Undo message is displayed. When pressing back results in an another app, maybe a notification for undo?

* Fenix version: 76.0b8

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1633)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812928

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
