### ISSUE TITLE
Settings: Close tab(s) on successfully sending it.

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#11202]
### What is the user problem or growth opportunity you want to see solved?
Better 'I'll pick it up on the other device'.

### How do you know that this problem exists today? Why is this important?
Pretty much always, I send a tab, then close it. Adding this would reduce the time to send a tab by 1/2 - 2/3.

### Who will benefit from it?
Anyone, who sends tabs often.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1631)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810644

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
