### ISSUE TITLE
Don't reload synced tabs everytime

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#11200]
Right now the synced tabs screen is reloaded on every view – depending on the amount of open tabs on other devices this can take a while. Could we display the screen w/o reloading and then sync on refresh (pull down) or find another way to sync tabs w/o making people wait every time they access synced tabs?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1629)

**Comment by topotropic** [comment]
@grigoryk is this still happening? Thanks!

**Comment by grigoryk** [comment]
Not in the way you describe, but we will wait until the first sync completes during startup before being able to display any synced tabs - they're not persisted to disk, so we loose all that state after a restart and have to refetch it from sync servers.

See https://github.com/mozilla/application-services/issues/3373
and a semi-related synced-tabs UI issue in which we sync sync tabs data every time we switch in and out of ... private tabs! https://github.com/mozilla-mobile/fenix/issues/23199

**Comment by jonalmeida** [comment]
Closing as won't fix since the UX and implementation of the Sync Tabs screen has changed and I think we've largely fixed most of the slow initial sync issues in the tabs tray Sync Tabs UI.
