### ISSUE TITLE
FNX-12104 ⁃ [Bug] webcontent registering clicks higher than where actual tap happens

### ISSUE THREAD

**Issue by Better-hack** [mozilla-mobile/fenix#11217]
## Steps to reproduce
clicked at the very bottom of the screen

### Expected behavior
the click was supposed to happen in the place where the click was

### Actual behavior
click was made above

### Device information
* Android device: honor 10 (android 9.1)
* Fenix version: Nightly 200603 06:00

https://bugzilla.mozilla.org/show_bug.cgi?id=1642538
Short video:
https://drive.google.com/file/d/1Jy9DNwhKhqj7K9Fyqfi2RRYRN9OHy5Q5/view?usp=sharing
Long video:
https://drive.google.com/file/d/1K00uJQcv2jUDzmfhKVf-IY6AWwMuh2V1/view?usp=sharing
I cleaned the cache and checked the version. Version 200603. I will attach links to two videos. The long video shows that in the area at the bottom of the screen the browser does not respond correctly. In the short video, we see that the browser carries a click higher. I think this is due to the "toolbar" / "address bar".

**Comment by liuche** [comment]
Thank you for filing! We're tracking this fix here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1643212
https://bugzilla.mozilla.org/show_bug.cgi?id=1642240

**Comment by liuche** [comment]
I'm going to dupe to this issue: #11189
