### ISSUE TITLE
[Bug] hit testing doesn't reach the right element

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#11215]
## Steps to reproduce
1. Go to https://www.laposte.fr/particulier/outils/trouver-un-point-d-envoi-de-colis-ou-de-retrait?query=94140
1. Tap in the area where the zip code `94140` is displayed
1. A list of one item appears with `94140 Alfortville, France`
1. Tap this item

### Expected behavior
* The input changes with this value
* A map is displayed on this city

### Actual behavior
Nothing is happening

### Device information
* Android device: Pixel 2, Android 10
* Fenix version: Firefox Preview Nightly (Nightly 200603 06:00) Build 21550609 

### Note:
* This is working in chrome
* Expanding the area for the suggestion (padding,margin) so it takes more screen real estate and is not anymore close to the input, and the selection is working.
* Initial webcompat report https://github.com/webcompat/web-bugs/issues/53520

**Comment by ekager** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1643209
