### ISSUE TITLE
Customize which extensions are displayed in the main menu

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#11219]
Common extensions, which I can display on the main menu
Infrequently used extensions can be displayed in submenus
For other main menu items, I hope to customize the items needed to display

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1644)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813936

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
