### ISSUE TITLE
[Bug] hide slash if there is nothing after it (when URL bar is not focused)

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#11212]
Small but worthy change to keep the UI uncluttered: currently when the URL bar is not focused, we hide "https://www." , but if there is a slash at the end (reddit.com/) we don't hide the slash. If there is nothing after the slash, the slash should also be hidden when the URL is not focused. Chrome does this already. Screenshot attached, Chrome is top, Firefox is bottom
![hideifnothingafterslash](https://user-images.githubusercontent.com/47801466/83694179-83681c00-a5c5-11ea-89f8-72aaa9f5b19e.png)

**Comment by AmyYLee** [comment]
This makes sense to me. @brampitoyo to confirm.

**Comment by willfs84** [comment]
And I know I'm not really supposed to do this but since I have your attention here, can you please give this a look when you get the chance? I really miss this :( and I know I'm not alone https://github.com/mozilla-mobile/fenix/issues/9118

**Comment by brampitoyo** [comment]
Yes. This change also makes sense to me. Thanks, @AmyYLee – and thanks @willfs84 for filing this issue!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200921-0946255555](https://user-images.githubusercontent.com/51314259/93739120-2e8df700-fbf0-11ea-87c7-20272438f605.png)
