### ISSUE TITLE
[Bug] lots of crashes

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11218]
on my phone with lineage OS 7.1.2 and snapdragon 652 (Adreno 510 gpu) Firefox nighlty preview is super crashy looking at the minidump folder the problem is always the same:
"GraphicsCriticalError":"|[0][GFX1-]: Failed to create EGLContext!: 0x300c (t=3.02563) ",

**Comment by J-Siu** [comment]
Nightly crash a lot in past 2 days. Not sure about the error, but I did click the report button every time. It is crashing even when the phone is lock. Happen once when I was reading middle of a page.

**Comment by J-Siu** [comment]
The crazy crash not happen for 2 days now.

**Comment by kbrosnan** [comment]
Please provide some crash ID URLs from the crashes you encounter. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by KrasnayaPloshchad** [comment]
I discovered there are numerous complaints for this.

* http://mozilla.com.cn/thread-426276-1-1.html
> 昨天不知道是火狐浏览器自动更新还是我点错了，正在浏览时就变新版本了！以前一直没事，挺好用的，但现在总是崩溃，特别明显就是谷歌账号登录不上，一碰就崩溃，页面输入框也基本不能用，新手不懂，求大神些点意见，只能刷机么？

__Yesterday I don’t know is Firefox Browser automatically updated or I was wrongly clicked, while I was browsing web pages, it was updated to new version! It was no problem in the past, very reliable, but now always crash, especially unable to sign in Google Account, while I click, it crashes, also, the inputbox on the web page is basically unable to use, I’m newbie and I don’t understand, please master-hand give me some advice, only flashing ROM possible?__

> 一样，也遇到这个问题，浏览器时不时就会奔溃

__Me too, (I) also encountered this problem, the browser crashes sometimes.__

> 我也是这种情况，好烦呀

__Me too for this situation, so boring.__

> 看来不是我一个人的问题

__It seems to me that’s not only my problem.__

* http://mozilla.com.cn/thread-426274-1-1.html
> 一直用的火狐浏览器，昨天不知道是按错了还是自己更新了，之后就成这样了，崩溃上百次了，各个网页输入框都出问题，谷歌号登录，一点就崩溃

__ (I) always use Firefox Browser, yesterday I don’t know is wrongly clicked or self updated, then it becomes this, crashed hundreds times, any inputbox on the web page having problem, signing in Google Account, once I click, it crash.__

* http://mozilla.com.cn/thread-426280-1-1.html
> 以前基本不奔溃，这更新后几分钟一次，真的垃圾！

__It was basically no crash in the past, after this update it happened after several minutes, really awful!__

* https://v2ex.com/t/738737

> 18 年的 2000 块的手机，也不知道是手机跟不上了还是为什么

锁屏再进来，必 crash

__A ¥2000 phone bought in 2018, I don’t know is the phone obsolete or any other reason. After coming from lockscreen, it must crash.__

* https://www.v2ex.com/t/702121
> 就是一坨屎，贼容易崩（包括但不限于切换应用时卡住然后闪退，浏览网页时闪退）

__Just a shit, very easy to crash (including but not limited to stack & flash quit while switching between apps, flash quit while browsing web page)

**Comment by KrasnayaPloshchad** [comment]
You can just get crash ID URLs via ⋮ --> Settings --> About Firefox --> Crashes

**Comment by ekager** [comment]
Closing because there aren't any specific crash reports in this bug. Please file new issues with the crash report linked as described above
