### ISSUE TITLE
FNX-12117 ⁃ Highlight ETP value to user

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11229]
### User Story
* As a user, I want to know how Firefox is protecting my privacy when I install Fenix, so I understand the value added to my browsing experience. 

### Acceptance Criteria
See the attached doc for 

* String changes to onboarding
* String changes to ETP settings in the settings menu
* String, interaction, and visual changes to the ETP CFR

**Comment by betsymi** [comment]
### **New onboarding strings**
 Please note the inclusion of terminal punctuation after descriptions. 

❌ Deprecate | Replace with ✅
-- | --
Protect yourself | Automatic privacy
Firefox Nightly helps stop websites from tracking your online | Privacy and security settings block trackers, malware, and companies that follow you.
Standard | Standard (default)
Blocks fewer trackers but allows pages to load normally. | Blocks fewer trackers. Pages will load normally.
Strict (Recommended) | Strict
Blocks more trackers for better protection and performance, but may cause some sites to not work properly | Blocks more trackers, ads, and popups. Pages load faster, but some functionality might not work.

### New settings strings
Please note the inclusion of terminal punctuation after descriptions. 

❌ Deprecate | Replace with ✅
-- | --
Standard | Standard (default)
Pages will load normally, but block fewer trackers. | Blocks fewer trackers. Pages will load normally.
Strict | Strict
Stronger tracking protection and faster performance, but some sites may not work properly. | Blocks more trackers, ads, and popups. Pages load faster, but some functionality might not work.
Custom | Custom
Choose which trackers and scripts to block | Choose which trackers and scripts to block.

### CFR String changes

❌ Deprecate | Replace with ✅
-- | --
Firefox Nightly is blocking trackers on this page when the shield is purple. Tap it to see what’s blocked. | Every time the shield is purple, Firefox has blocked trackers on a site. Tap for more info.

### CFR additional changes

**1. String changes**

- See above

**2. Visual design changes**

- Shield icon appears darker than it should. Icon needs to be on top of the dark overlay.

**3. Interaction changes**

- Tap on CFR opens ETP Panel
- Tap on shield opens ETP Panel

![image](https://user-images.githubusercontent.com/43555492/83785916-9e836c00-a657-11ea-96f8-caa85073c4a9.png)

**Comment by ekager** [comment]
Let's verify all of the above UI changes except `Shield icon appears darker than it should. Icon needs to be on top of the dark overlay` because that is not currently possible.

**Comment by Diana-Rus** [comment]
Hi verified as fixed on Beta 5.2.0-beta.1 GV:78 with:

- Google Pixel 3 XL (Android 9)
- Samsung Galaxy S9 (Android 8)
- Sony Xperia Z5 (Android 7)
- Xiaomi Mi Pad 2 (Android 5.1)- x86

**New Onboarding string for ETP card:**
- Automatic privacy ✅
- Privacy and security settings block trackers, malware, and companies that follow you. ✅
- Standard (default) ✅
- Blocks fewer trackers. Pages will load normally. ✅
- Strict ✅
- Blocks more trackers, ads, and popups. Pages load faster, but some functionality might not work. ✅

**New settings strings:**
- Standard (default) ✅
- Blocks fewer trackers. Pages will load normally. ✅
- Strict ✅
- Blocks more trackers, ads, and popups. Pages load faster, but some functionality might not work. ✅

**CFR String changes:**
- Every time the shield is purple, Firefox has blocked trackers on a site. Tap for more info. (the string has been changed) ✅
- Visual design changes - **not yet modified**
- Interaction changes - Tap on CFR opens ETP Panel ✅
- Interaction changes - Tap on shield opens ETP Panel✅

**New Onboarding string for ETP card - screen**
![Screenshot_20200610-101854_Firefox Preview](https://user-images.githubusercontent.com/49859863/84242747-ec8de900-ab09-11ea-861f-8dc78404306c.jpg)

**New settings strings - screen**
![Screenshot_20200610-102024_Firefox Preview](https://user-images.githubusercontent.com/49859863/84242762-f3b4f700-ab09-11ea-91e0-546074058f0d.jpg)

**CFR String changes - screen**
![Screenshot_20200610-102209_Firefox Preview](https://user-images.githubusercontent.com/49859863/84242773-f7e11480-ab09-11ea-983e-b550fe19d883.jpg)
