### ISSUE TITLE
FNX-12111 ⁃ [Bug] Black screen when tapping the video while playing in landscape mode.

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#11224]
## Steps to reproduce
1. Launch Fenix and go to https://m.youtube.com;
1. Play one video in landscape mode;
1. Tap the screen;
1. Observe the behavior;
    1. Expected behavior
The video on screen buttons are displayed and the video is still playing.
    1. Actual behavior
The video on screen buttons are displayed but the screen turns black while the video is still playing. 
    1. Notes
This is also reproducible on https://m.digi24.ro and https://m.twitch.tv.
![20200604](https://user-images.githubusercontent.com/48799384/83758047-16628e00-a67a-11ea-96db-6eca7eeccf8b.gif)UNITO-UNDERSCORE!152907!

### Device information
* Android device: Motorola Moto G6 (Android 8), Nokia 6 (Android 7.1.1), OnePlus 6T (Android 9);
* Fenix version: Fenix Nightly Build 21560608 GV 79.0a1 from 6/4;

**Comment by karan-kamat** [comment]
Yeah same thing happens with my Xiaomi (Android 9)
![Nightly](https://user-images.githubusercontent.com/59926956/83884167-20f85280-a762-11ea-8839-d52b1eb7bb42.gif)
Has been happening for the past week in both nightly (fenix) and nightly preview

**Comment by ekager** [comment]
Closing for #10896
