### ISSUE TITLE
FNX-12129 ⁃ [Bug] Tab tray tab restore (undo from close) does not show tab on screen

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11236]
## Steps to reproduce
1. Open multiple tabs
1. Open tab tray
1. Close tab
1. undo close

### Expected behavior
The tab that is reopened appears on screen where I can see it without scrolling

### Actual behavior
Tab appears just offscreen

![undo-tab](https://user-images.githubusercontent.com/152493/83798055-a0f2bf80-a671-11ea-805b-10903cd920a9.gif)

### Device information
* Android device: pixel 2
* Fenix version: latest nightly

**Comment by sheikh-azharuddin** [comment]
In new update tab closed undo itself not showing....
