### ISSUE TITLE
FNX-12124 ⁃ [Bug] Site previews behave oddly when scrolling tab tray

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#11232]
## Steps to reproduce
Open several tabs
Go to tab tray
scroll up and down several times

### Expected behavior
Site Previews are displayed correctly

### Actual behavior
The site previews of the sites at the top of the tray are resised oddly or are blank during scroll, then are ok again
See a screen video here: https://photos.app.goo.gl/MHChTNR5etJpYqPz6

### Device information
* Android device: Redmi Note 7 MIUI 11 Android 9
* Fenix version: Migration build #2015744243

**Comment by jonalmeida** [comment]
This should be fixed as well after we removed the [favicon fallback code](https://github.com/mozilla-mobile/fenix/pull/11510/files#diff-280f03be99bd38e9c762d4902adca622L72-L78) from thumbnail previews.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **`Nightly 200618 from 6/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200618-161244](https://user-images.githubusercontent.com/51314259/85027941-28b4ef80-b183-11ea-99ea-7ff14ae4734b.gif)


On the other hand, I've bumped into #11733
