### ISSUE TITLE
UI tests for existing deeplinks

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#11239]
Current manual tests on LeanPlum integration would suggest some deeplinks aren't working.

It is not always clear that this is a missing work in fenix, bugs in fenix, bugs in the LeanPlum SDK or configuration errors in dashboarding with the marketing team.

In order to ameliorate communication between the mobile engagement team and engineering, such a test would be the final stage of sign-off/confirmation of a new event.

This issue is to come up with tests that can

* document and test the deeplinks that are currently supported.
* be obviously extendable when new deeplinks are added.
* be impossible to ignore when new deeplinks are added.

Tasks:

* [x] Add `DeepLinkRobot` to send each of the deep links
* [x] Add a UI test which uses the `DeepLinkRobot` and existing UI test robots to verify that the deep links work.
* [ ] Ensure that UI tests are running on CI.
* [ ] Add a markdown `docs/deeplinks.md` file, to document the routes and the precise effects of the deep links when they're callled.

The `DeepLinkRobot` would have an additional benefit of modularizing existing UI tests.

**Comment by sv-ohorvath** [comment]
@jhugman Found this test has crashed: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7416004993250552039/executions/bs.f20c90bf6e602b3d/test-cases
