### ISSUE TITLE
FNX-12130 ⁃ Firefox Nightly preview crash on Facebook

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11237]
it really frightening that same bug happened to me over a year ago with old Firefox (which I reported of course) and even in Firefox preview is still not fixed.
Firefox preview nightly crashes on Facebook every time looking at the crash report cause is Failed to create Failed to create EGLContext 0x300c

"FramePoisonBase":"9223372036600930304","FramePoisonSize":"4096","GraphicsCriticalError":"|[0][GFX1-]: Failed to create EGLContext!: 0x300c (t=4.33999) |[1][GFX1-]: Failed to create EGLContext!: 0x300c (t=41.9527) |[2][GFX1-]: Failed to create EGLContext!: 0x300c (t=80.115) |[3][GFX1-]: Failed to create EGLContext!: 0x300c (t=96.4895) |[4][GFX1-]: Failed to create EGLContext!: 0x300c (t=116.131) "
honestly I M super disappointed.
my device is running lineage OS 7.1.2 with Adreno 510 gpu.
Good look Firefox bye bye again.

**Comment by liuche** [comment]
Hi @ale82to! Thanks for filing. If you go to `about:crashes` in your Firefox Preview url bar on Nightly, could you share the "socorro" link so we can see what crash this was, and try to fix it?

**Comment by kbrosnan** [comment]
No response from the reporter, closing.
