### ISSUE TITLE
FNX-12131 ⁃ [Bug] Bad styling on Android navigation when Tab Tray is opened from Private home

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11238]
## Steps to reproduce
1. Open Fenix
1. Tap mask icon
1. Open tab tray.

### Expected behavior
Correctly styled android navigation bar.

### Actual behavior
Bad contrast, bad styling on Android navigation bar.

![signal-attachment-2020-06-04-152653](https://user-images.githubusercontent.com/152493/83801890-da2e2e00-a677-11ea-91cc-999155089c20.png)

### Device information
* Android device: pixel 2
* Fenix version: latest nightly

**Comment by cadeyrn** [comment]
Duplicate of #11099.

**Comment by yoasif** [comment]
@cadeyrn thanks!
