### ISSUE TITLE
Integrate Synced Tabs AwesomeBar suggestions

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#11245]
Part of the Synced Tabs feature is to have tabs show up in the awesome bar suggestions.

We should add that here probably: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt

Reference Browser integration: https://github.com/mozilla-mobile/reference-browser/blob/d1792daf0c2cb554b400495d3ebe1b218b56de05/app/src/main/java/org/mozilla/reference/browser/browser/BrowserFragment.kt#L51-L57

A screenshot of what a suggestion looks like from this provider (the last one):
![](https://user-images.githubusercontent.com/1370580/83816218-e2926300-a68f-11ea-9ce1-f6ea9787b7f0.png)

**Comment by hakkikaancaliskan** [comment]
Can I work on this?

**Comment by jonalmeida** [comment]
Re-adding the triage label to figure out what our criteria should be to land this feature (assuming we want it).

**Comment by vesta0** [comment]
Tagging @brampitoyo since he's focused on everything search related. 

Product question is: 
-Do we want to show sync tabs as part of Awesome bar suggestions?
-If we do, how do we want to show sync tabs in the Awesome bar in relation to other types of search suggestions (priority order)
-If we do, how do we want to offer users the option to turn it off?

**Comment by brampitoyo** [comment]
@vesta0 @jonalmeida 

1. Yes. I think that we want to show Synced Tabs on address bar suggestions, alongside other items such as browsing history, bookmarks, open tabs, and top sites.

2. Can we work with Desktop Engineering and use the same algorithm? Does Fennec have a recipe we can re-purpose?

3. To turn this off, users can manually uncheck Settings → Account → Choose what to synchronise → Open tabs

To show or hide open tabs in address bar suggestions, a toggle should be put under Settings → Search → Address bar → Search open tabs [ON/OFF]

- If you turn the toggle ON, the address bar _will_ show open tabs, and _may_ show synced tabs
    - Synced tabs will be shown _only_ if you check “Open tabs” under Account settings
- If you turn this toggle off, the address bar will not show open tabs or synced tabs.
    - However, as long as “Open tabs” is checked under Account settings, you can still see a list of them under Main menu → Synchronised tabs

CC @Verdi for his interest and further comment.

**Comment by hakkikaancaliskan** [comment]
this issue is done

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Beta 82.0.0-beta.1 (Build #2015765523).

### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)
