### ISSUE TITLE
As a user, I would like Fenix to work on our minimum API phones (lint check cleanup)

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1124]
Our current lint report shows a number of unaddressed minor issues, particularly issues with running Fenix on older phones.

https://gistpreview.github.io/?705c10c4d36530f03a5765b6cce92888

In order to maximize compatibility across devices, we must either clear up or mark acceptable each risk from the Android lint checks. This is an important ongoing tech debt task we'll need to perform from time to time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1669)

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report has been closed. Running the linter against current code could be useful.
