### ISSUE TITLE
FNX-12141 ⁃ [Bug] Settings headers are not aligned correctly in RTL layout

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#11246]
## Steps to reproduce
1. Enable "Force RTL layout direction."
1. Tap the overflow menu and select "Settings"

### Expected behavior
Section headers like "Account" and "General" are right aligned and have the correct padding.

### Actual behavior
Section headers are left aligned with zero padding.
![device-2020-06-04-154406](https://user-images.githubusercontent.com/6396431/83817758-735e4400-a67a-11ea-9540-3c08926e295d.png)

### Device information
* Android device: Google Pixel 2 XL (Android 10)
* Fenix version: Nightly 6/4

**Comment by ekager** [comment]
Good catch! Likely a regression from https://github.com/mozilla-mobile/fenix/pull/9603
We should fix the category layout to respond to this correctly.

**Comment by sflorean** [comment]
Tested on Nightly from 6/9 with Google Pixel 3 (Android 10) and Nokia 6 (Android 7.1.1) and I can confirm that the section headers like "Privacy and security" and "General" are right-aligned.
