### ISSUE TITLE
a way to change the emoji font for non-root users

### ISSUE THREAD

**Issue by igalic** [mozilla-mobile/fenix#11255]
### What is the user problem or growth opportunity you want to see solved?
Android users who don't root (but hopefully not brick) their device (void their warranty, lock themselves out of using their bank / insurance app, etc), cannot change their device's fonts, including emoji fonts

as currently it has no effect to specify the fully qualified path of a font in `font.name-list.emoji`, perhaps Firefox should offer to "install" a downloaded font in its own font cache?

### How do you know that this problem exists today? Why is this important?
emoji are how we convey emotion on the internet.
if all you feel is disgust and despair and disappointment when opening the emoji tab on your keyboard, or seeing an emoji in an app or a website, that's really not a good start.

### Who will benefit from it?
anyone who doesn't have root on their android phone

everyone who has feelings but trouble expressing them on the Internet since Google killed off their favourite emoji font

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1681)

**Comment by jonalmeida** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
