### ISSUE TITLE
FNX-12149 ⁃ [Bug] Can't easily see login while editing

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11250]
## Steps to reproduce
(On Nightly)
Go to saved logins
Edit a login

### Expected behavior
Should be able to see login password in order to edit it

### Actual behavior
Login password is obfuscated as dots, clicking the :eye: toggle shows the password, but clicking into the text obfuscates the password as dots again.

Requires a few back and forths in order to actually be able to see the password AND edit it at the same time.

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 6/4

![photo5102845941844650091](https://user-images.githubusercontent.com/1082253/83828886-8717a380-a696-11ea-9604-24401bd2df36.jpg)

**Comment by eliserichards** [comment]
Closing in favor of #10172
