### ISSUE TITLE
FNX-12156 ⁃ [Bug]Tab Tray: Confirmation snackbar not displayed after swipe-delete or tap on the close tab button

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11257]
## Steps to reproduce
1. Open each top site in a different tab
1. Open the Tabs Tray
1. Swipe-delete or tap on the 'x' (close tab button)

### Expected behavior
The confirmation snackbar is displayed

### Actual behavior
No confirmation snackbar displayed

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version:  Nightly Build 200605 from 6/5

### Notes
► Video
![20200605-143239](https://user-images.githubusercontent.com/51314259/83873319-44a8a200-a73c-11ea-92f9-a73bcd9b6734.gif)

**Comment by ekager** [comment]
Should be fixed by #11346

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200609 from 6/9`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video
![20200609-120404](https://user-images.githubusercontent.com/51314259/84130452-f8b37100-aa4b-11ea-903f-bde4540c6819.gif)
