### ISSUE TITLE
[Bug] Media notification from lock screen is not working on twitch.tv and digi24.ro

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#11263]
## Steps to reproduce
1. Launch Fenix and go to https://m.twitch.tv;
1. Tap on a live video;
1. Lock the device. Observe the media notification;
1. Pause/play the playback from the lock screen.
    1. Expected behavior
Pause/play the file using the lock screen media notification works.
    1. Actual behavior
Pause/play the file using the lock screen media notification is not working.
    1. Notes
This is also reproducible on Private Browsing.
![20200605](https://user-images.githubusercontent.com/48799384/83882369-abcd5300-a74a-11ea-80ea-c66239d2eb6f.gif)UNITO-UNDERSCORE!163158!

### Device information
* Android device: Motorola Moto G6 (Android 8);
* Fenix version: Fenix Beta 77.0.0-beta.2 Build 21570821 GV 77.0 from 6/5.

**Comment by codrut-topliceanu** [comment]
I've tested this myself on a Pixel3XL and Pixel4 (Android 10)
I was able to reproduce this issue with twitch.tv on nightly and on Chrome, Opera and Brave, so it seems to be related to the site itself.
On digi24.ro/live it seems to work, at least the notification does, until the site stops buffering in the background and the notification does nothing anymore. (this doesn't happen on other browsers). I'll look into it some more and see if I find any clue as to why this happens.
