### ISSUE TITLE
FNX-12172 ⁃ [Telemetry] Updated Reader mode

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11269]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to know how often users choose to view a page in reader mode, and whether they customize the appearance of their reader mode, so I can determine how discoverable this feature is, and better prioritize enhancing this feature if usage is high. 

## What questions will you answer with this data?
* What % of users switch to reader mode (tap on the reader mode icon) 
* Do they mean to switch to reader mode or is it an accidental tap (how soon after tapping on the reader mode icon do they switch back to regular mode? Tracking both taps to enter and exit reader mode) 

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by AndiAJ** [comment]
Hi **verified as fixed** on the latest **`Nightly build 200615 from 6/15`** using a Google Pixel 3a (Android 10)

Ping **4360c26c-d3c2-4509-9807-b12944ba2efb**

✔️ Reader mode is available
```
        {
          "category": "reader_mode",
          "name": "available",
          "timestamp": 2
        },
```


✔️ Open Reader mode
```
"events": [
        {
          "category": "reader_mode",
          "name": "opened",
          "timestamp": 0
        }
```

✔️ Tap on Appearance
 ```
"category": "events",
          "extra": {
            "item": "reader_mode_appearance"
          },
          "name": "browser_menu_action",
          "timestamp": 8079
        },
        {
          "category": "reader_mode",
          "name": "appearance"
```
[Logcat](https://github.com/mozilla-mobile/fenix/files/4780320/reader.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test150600)
