### ISSUE TITLE
FNX-12166 ⁃ [Bug]Tabs Tray: Empty tabs tray message overlaps with the open tabs before being deleted

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11265]
## Prerequisites
Have a couple of open tabs

## Steps to reproduce
1. Tap the ⋮ 
1. Select "Close all tabs"

### Expected behavior
Smooth transition

### Actual behavior
The empty tabs tray message overlaps with the open tabs before being deleted

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200605 from 6/5

### Notes
► Video
![20200605-163228](https://user-images.githubusercontent.com/51314259/83883243-e8e61500-a74b-11ea-83d7-878a75eb8484.gif)

**Comment by boek** [comment]
This has been fixed

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build 200623 from 6/23** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200623-170537](https://user-images.githubusercontent.com/51314259/85414888-57f9a100-b575-11ea-94ce-ebeb3bc3a024.gif)
