### ISSUE TITLE
FNX-12165 ⁃ [Bug] Crash when downloading an image from smaller-pictures.appspot.com

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#11264]
## Steps to reproduce
1. Open smaller-pictures.appspot.com.
1. Tap the lower right logo to add a photo. 
1. Select a photo from storage.
1. Tap on the lower right logo to download the photo.

### Expected behavior
The download starts without issues.

### Actual behavior
Fenix crashes.

### Device information
* Android devices: all
* Fenix version: 6/5 Nightly, Beta 77.0.0-beta.2 (beta 5.1.1)

[logcat-crash.txt](https://github.com/mozilla-mobile/fenix/files/4736419/logcat-crash.txt)

**Comment by hakkikaancaliskan** [comment]
I've tried on master, debug build and no problem.
<img src="https://user-images.githubusercontent.com/17825767/83886405-bb02cf80-a74f-11ea-91b2-06686daac208.png" width="300">

**Comment by Amejia481** [comment]
Thanks for reporting. I'm unable to simulated the issue. Also I couldn't find any crash stack traces in the logs. @softvision-miralobontiu could you go to "Settings" -> "About Firefox Nightly" -> "Crashes"?  There you can can find the stack trace that can help us to determine issue. Could you send the stack trace please? :)

**Comment by hakkikaancaliskan** [comment]
@Amejia481 I'm able to simulate on 77.0-beta2 on XZ1.
https://crash-stats.mozilla.org/report/index/b666ca18-0dce-414d-94bf-0149d0200605

**Comment by hakkikaancaliskan** [comment]
@Amejia481 Yes, it is.
https://github.com/mozilla-mobile/fenix/issues/9039#issuecomment-638244738

**Comment by Amejia481** [comment]
Thank you :)

**Comment by Amejia481** [comment]
👍

**Comment by hakkikaancaliskan** [comment]
@Amejia481 check my last comment please

**Comment by Amejia481** [comment]
I think I found the issue: The version of geckoview beta that that build is using doesn't have support for blob urls, but the actual version of geckoview beta has.

**Comment by liuche** [comment]
Hi, thanks for the testing here! The 5.1 branch has been so long in releasing (since ~May 18), so it's pretty far behind in a lot of the changes that have since landed.

**Comment by liuche** [comment]
This should be fixed in the 5.2 release going out this week, please re-open if 5.2 does not fix it. This unfortunately will not be rolling out to the 77b build yet until our next release cycle.
