### ISSUE TITLE
FNX-12178 ⁃ [Telemetry] Tabs Tray

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11273]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to understand how our users interact and navigate between tabs, so we can continuously enhance their experience and help them browse and navigate faster and smoother. 

## What questions will you answer with this data?
-What are the most common user flows? (taps on + open a tab, opening an exiting tab, closing a tab, closing the tab tray)
-What % of users have n number of tabs open? (tracking the open tab state) e.g. 80% of users have 1 tab open, 10% have 2 tabs open, etc
-What % of users interact with the tabs tray 3 dot menu to save to a collection, share all tabs, or close all tabs?
-What % of users switch to private mode and open a private tab (taps on the private mode icon and + open a private tap)

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by vesta0** [comment]
Created the request [here](https://docs.google.com/document/d/16coj4ukVw2Lboo_ssuk_ZlNuO3b8aYvPSjgHOwU7VEw/edit#) too as per DS request.

**Comment by sblatz** [comment]
@boek is going to see which of this telemetry we already have. It may just be a matter of porting it over to tabs tray 😄

**Comment by sblatz** [comment]
### Notes

Open the tray
Open an existing tab 
Close an existing tab
Switch between private
Switched to normal
New tab button pressed
New private tab button pressed
3 dot menu opened
Also: save to collection, share all tabs, close all tabs
Tab tray dismissed (by swiping down)
Tag mgorlick for review!
Make sure event names are labelled tabs_tray

**Comment by sblatz** [comment]
Metrics ping event will get added in https://github.com/mozilla-mobile/fenix/issues/11479

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly Build 200629 from 6/30`** and **`Fenix 79.0.1-beta.1 from 6/30`** using a Google Pixel 3a (Android 10)

## ✔️ Nightly Build 200630 from 6/30
| Action  | Status | Ping |
| ------------- | ------------- | ------------- |
|A user opened the tabs tray  | ✔️  | b8b45062-504f-4c76-87fc-328516949250 |
| A user closed the tabs tray (by swiping down) | ✔️ | b8b45062-504f-4c76-87fc-328516949250  |
| A user opened a new tab   | ✔️ | 66f03f36-a17b-4dcc-9b4e-dd9d0085e845  |
| A user opened an existing tab  | ✔️ | a739ccec-05d9-4cb2-933e-da4d967ea6bd  |
| A user closed an existing tab  | ✔️ | 22f0dda6-362d-4806-99fc-3198ba0801b5  |
| A user switched to private mode  | ✔️ | 7a1f089f-dbc3-4be3-b5bf-a180de121f42  |
| A user opened the tabs tray (PB)  | ✔️ | bad99978-0d4f-4b36-9605-4b190a7f87f8 |
| A user closed the tabs tray (by swiping down) (PB)  | ✔️ | c1dd6e4f-aca9-4b73-9159-9a5a5f30efcc |
| A user opened a new private tab (PB) | ✔️ | 734e59e5-a240-4cf1-b7aa-b3398f5eae1a |
| A user opened an existing tab (PB) | ✔️ | d80bd5e3-f8bc-454c-ac60-e18857a7f890  |
| A user closed an existing tab (PB) | ✔️ | 245de194-5175-4847-9180-39c62d370465 |
| A user switched to normal mode  | ✔️ | 9b6967ba-da17-43d2-b75a-67d1c8af4cdd |
| A user opened three three dot menu in the tabs tray  | ✔️ | ad73f565-be47-4692-bf72-d797e6b10e40  |
| A user tapped the save to collection button in the three dot menu within the tabs tray  | ✔️ | 5361f185-77c7-4091-816d-41a028958b32 |
| A user tapped the share all tabs button in the three dot menu within the tabs tray | ✔️ | bd5c457f-199a-46e7-8562-e1d41eb61db3 |
| A user tapped the close all tabs button in the three dot menu within the tabs tray | ✔️ | 0a65ee12-5753-4354-b921-e74be78e0e05 |
| A user opened three three dot menu in the tabs tray (PB)  | ✔️ | a37bfca6-ecf1-4543-a187-2a1f388ce433 |
| A user tapped the share all tabs button in the three dot menu within the tabs tray (PB) | ✔️ | 5062f59b-0974-49bc-badc-068cb610763f |
| A user tapped the close all tabs button in the three dot menu within the tabs tray (PB)  | ✔️ | 96a4288d-c15c-40df-8f59-9afd01af79d4 |

[Logcat](https://github.com/mozilla-mobile/fenix/files/4850777/tbstrng.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t300601)

## ✔️  Fenix 79.0.1-beta.1 from 6/30

| Action  | Status | Ping |
| ------------- | ------------- | ------------- |
|A user opened the tabs tray  | ✔️  | 6b2ab76f-ce97-43f0-805c-68d0e9938241 |
| A user closed the tabs tray (by swiping down) | ✔️ | 6b2ab76f-ce97-43f0-805c-68d0e9938241 |
| A user opened a new tab   | ✔️ | e45dcaf6-bd2c-4ddb-8155-855d85e5826a |
| A user opened an existing tab  | ✔️ | 29e0d938-e904-46d4-9842-2a13b7a74977 |
| A user closed an existing tab  | ✔️ | e9b0ae70-ca1c-47ed-b8fa-f1c2175b1466 |
| A user switched to private mode  | ✔️ | 9ddf6ab7-2e7c-4a94-9e9e-8640312dadcf |
| A user opened the tabs tray (PB)  | ✔️ | 18762008-e877-46d8-9a1a-5cf09e0f811c |
| A user closed the tabs tray (by swiping down) (PB)  | ✔️ | c0ade5c1-41b5-432e-9365-1bf2eb994d0b |
| A user opened a new private tab (PB) | ✔️ | 74b0f058-acaf-4c6e-8534-8b5cf6124b6b |
| A user opened an existing tab (PB) | ✔️ | 1c0cb82e-8388-4d53-b38b-863bf4d04f46 |
| A user closed an existing tab (PB) | ✔️ | ab2d9dbd-f8e1-40d4-a07a-4dfa543621e4 |
| A user switched to normal mode  | ✔️ | f8d85f2e-a027-47fe-9061-174919157af3 |
| A user opened three three dot menu in the tabs tray  | ✔️ | 20d5e9d4-0e39-4dc8-bcfc-451bd9cd07c8 |
| A user tapped the save to collection button in the three dot menu within the tabs tray  | ✔️ | 5f100cb7-41f7-402b-af5c-c8f4f3e3ca98 |
| A user tapped the share all tabs button in the three dot menu within the tabs tray | ✔️ | ecc07fc5-fd34-476a-916d-4eb89be8abbc |
| A user tapped the close all tabs button in the three dot menu within the tabs tray | ✔️ | 820166dd-0c9b-40aa-8ddf-6321a012a359 |
| A user opened three three dot menu in the tabs tray (PB)  | ✔️ | 03f3c01c-558a-4e16-9d71-fd47fdfde353 |
| A user tapped the share all tabs button in the three dot menu within the tabs tray (PB) | ✔️ | 120cf72b-00f5-4642-bd3d-5a5e52b3fdb0 |
| A user tapped the close all tabs button in the three dot menu within the tabs tray (PB)  | ✔️ | 2a28f95-c61c-4a45-909c-d4cf1fe95de8 |

[Logcat](https://github.com/mozilla-mobile/fenix/files/4850903/TTb.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-testMig3006000)
