### ISSUE TITLE
FNX-12183 ⁃ [Bug] Inconsistent punctuation in ETP mode descriptions

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#11279]
## Steps to reproduce
Tap overflow menu > Settings > Enhanced Tracking Protection

### Expected behavior
Descriptions for ETP modes all end with a period or none of them do.

### Actual behavior
"Custom" description does not end with a period but "Standard" and "Strict" do
![Screenshot](https://user-images.githubusercontent.com/6396431/83905599-d1406980-a716-11ea-8e80-0c3ee698aadb.png)UNITO-UNDERSCORE!1591376335!

### Device information
* Android device: Google Pixel 2 XL
* Fenix version: Nightly 6/5

**Comment by ekager** [comment]
This is already being fixed in https://github.com/mozilla-mobile/fenix/pull/11253
