### ISSUE TITLE
FNX-12174 ⁃ [Bug] Tab Tray A11y: Tapping tab tray icon says number of tabs open, nothing more

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#11271]
## Steps to reproduce
1. Enable Talkback
1. Tap on the tab tray icon

### Expected behavior
We should announce something like "Tabs tray" or something that tells the user what's going to happen

### Actual behavior
Hear only the number of tabs open (ex: "1")

**Comment by sflorean** [comment]
Tested on Nightly 6/12 with the following devices:
 - LG G7 FIT (Android 8) 
- Samsung Galaxy Note 10 (Android 10)

Reading: "0 (or the number of tabs opened) open tabs, tap to switch tabs, double-tap to activate".

**Comment by gabrielluong** [comment]
> Tested on Nightly 6/12 with the following devices:
> 
> * LG G7 FIT (Android 8)
> * Samsung Galaxy Note 10 (Android 10)
> 
> Reading: "0 (or the number of tabs opened) open tabs, tap to switch tabs, double-tap to activate".
> This is expected or should "Tabs tray" be included, as expected results are from the description?

cc @darkwing for a response.

**Comment by AndiAJ** [comment]
Hi, As per [11271](https://github.com/mozilla-mobile/fenix/pull/11287/commits/fdab339ae05849c6a9d2dfb62eeb68d3dcd8e0c7) , I'll mark this matter **verified as fixed** on **`Nightly 200618 from 6/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200618_165813_orgmozillafenixnightly](https://user-images.githubusercontent.com/51314259/85030194-d32e1200-b185-11ea-9657-471704e571d4.jpg)

@darkwing -  Please re-open if I'm mistaken. ☺️
