### ISSUE TITLE
FNX-12181 ⁃ [Bug] TextViews on empty ETP Exceptions screen don't respect RTL layout

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#11277]
## Steps to reproduce
1. Enable "Force RTL layout direction."
1. Tap the overflow menu and select Settings > Enhanced Tracking Protection > Exceptions

### Expected behavior
Right aligned text for description and "Learn more" link

### Actual behavior
Left aligned text for description and "Learn more" link

![Screenshot](https://user-images.githubusercontent.com/6396431/83904407-aa813380-a714-11ea-8e63-090786c6c81a.png)UNITO-UNDERSCORE!1591376635!

### Device information
* Android device: Google Pixel 3 emulator (Android 10)
* Fenix version: Nightly 6/5

**Comment by ItielMaN** [comment]
> Seems like #6180, #11246, and this all have the same fix (set `textAlignment` to `viewStart`). I wonder if this appears elsewhere in the settings.

See #7861, originally filed as [bug 1608218](https://bugzilla.mozilla.org/show_bug.cgi?id=1608218) (screenshots included)

**Comment by sflorean** [comment]
Verified as fixed on Nightly from 6/9 with Google Pixel 3 (Android 10) and Nokia 6 (Android 7.1.1).
