### ISSUE TITLE
Investigate and test for AccountObserver events not being fired to LeanPlum

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#11281]
The following were identified as missing in a recent test by the Mobile Engagement team. This is requested to be in market by 8/25/20 (release 80).

* [ ] `E_Sign_Out_FxA`
* [ ] `E_FxA_Signed_In`

It's not clear why these are not firing; some investigation is needed to prove that `onAuthenticated` method is being called or that the LeanPlum is being called but it's losing the event.

This would be a good candidate to be tested in a UI integration test as requested in #11210

**Comment by liuche** [comment]
Hi @cbonacuse we updated the probes the two probes that are here - could you let us know if these two probes are working now?

**Comment by cbonacuse** [comment]
@liuche I just checked in today's Nightly build and they are both working/firing correctly!

**Comment by AndiAJ** [comment]
Hi **verified as fixed** on the latest **`Nightly Build 200908`** using a Google Pixel 3a (Android 10)

Leanplum Device ID **`260a7b7b-a130-49d4-9da9-790cdf4f84e3`**

✔️ Signed in using the sign in card from the onboarding screen
![image](https://user-images.githubusercontent.com/51314259/92478770-52fad400-f1eb-11ea-8a16-b454d78281b4.png)

✔️ Sign out afterwards
![image](https://user-images.githubusercontent.com/51314259/92478835-6c9c1b80-f1eb-11ea-9976-c1dd29b1647e.png)

✔️ Sign in with existing account
![image](https://user-images.githubusercontent.com/51314259/92478998-a4a35e80-f1eb-11ea-837a-52939be265b8.png)

✔️ Sign out afterwards
![image](https://user-images.githubusercontent.com/51314259/92479078-c0a70000-f1eb-11ea-8c0f-adb9470caadc.png)

✔️ Pairing
![image](https://user-images.githubusercontent.com/51314259/92479226-efbd7180-f1eb-11ea-8a25-9945e1bdf725.png)

✔️ Sign out afterwards
![image](https://user-images.githubusercontent.com/51314259/92479281-049a0500-f1ec-11ea-824a-1786298719f8.png)

✔️ Sign up new account
![image](https://user-images.githubusercontent.com/51314259/92479496-475bdd00-f1ec-11ea-9353-59f78b527761.png)

✔️ Sign out afterwards
![image](https://user-images.githubusercontent.com/51314259/92479546-58a4e980-f1ec-11ea-8a84-58ffc114073c.png)
