### ISSUE TITLE
Move Reader Appearance Controls to Customization Fragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#11282]
### Acceptance Criteria
* I do not see "Appearance" in the three dot browser menu
* I do see the Appearance menu under Settings > Customization 

## Specs
https://app.abstract.com/projects/8afc4b50-7667-11e9-94ba-3558f8596822/branches/9d5d5547-e8ad-4209-b8fa-54c1b146729e/collections/a6e23752-c418-4b01-b56c-330eb3994952

**Comment by sblatz** [comment]
Tagging @vesta0 / @apbitner to track this new one :)

**Comment by sblatz** [comment]
This should not be in the sprint since it's now past feature freeze, sorry for the confusion on that.

**Comment by mcarare** [comment]
There is a suggestion to implement a feature similar to Fennec for this  : https://github.com/mozilla-mobile/fenix/issues/11779.

**Comment by topotropic** [comment]
@amedyne when we redesigned Reader View https://github.com/mozilla-mobile/fenix/issues/11045 we broke this issue out but never picked it up again. The "Appearance" entry is not part of Victoria's menu redesign so it would be great if we could pull this into an upcoming sprint. Thanks!

**Comment by eliserichards** [comment]
Victoria's new designs take this into consideration, so we might want to close this in favor of #17971
