### ISSUE TITLE
Refactor TabCounterToolbarButton to use browser store

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#11288]
`TabCounterToolbarButton` is currently using a `SessionManager.observer` to update its count.

We want to get rid of SessionManager observers so we can finish the A-C refactoring to browser state.

Alternatively, see if we can uplift / merge it with the A-C one.

**Comment by pocmo** [comment]
> Alternatively, see if we can uplift / merge it with the A-C one.

Yeah, there is an issue about this on the "upstreaming" board. Would love to do that since otherwise the AC component has no real use if it is only for RB.

**Comment by csadilek** [comment]
Closing for: https://github.com/mozilla-mobile/fenix/issues/8791
