### ISSUE TITLE
FNX-12188 ⁃ [Bug] Memory leak when switching between other apps and fenix

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#11284]
## Steps to reproduce
1. Cold startup Fenix
1. Switch to PBM
1. Open a simple static website like https://example.com
1. Observe RAM usage  in _Running services_ using _Developer options_
1. Repeatedly switch between other apps and fenix, e.g. switching 20 times between Settings and Fenix, thus switching to Fenix 10 times
1. Observe RAM usage again
1. Use _Close private tabs_ to close the single tab
1. Open the static website again
1. Observe RAM usage again

(Sidenote: Switching to PBM just makes it easier for me to observe the RAM usage, but I can reproduce without active PBM.)

### Expected behavior
The RAM usage as reported in _Running services_ using _Developer options_ should be more or less constant.

### Actual behavior
Reported memory usage:
_STR Step, Fenix RAM Usage, Google Play Services RAM Usage_
4, 108 MiB, 56 MiB
6, 199 MiB, 56 MiB
9, 188 MiB, 56 MiB

Same steps, but opening up https://edition.cnn.com
_STR Step, Fenix RAM Usage, Google Play Services RAM Usage_
4, 121 MiB, 55 MiB
6, 208 MiB, 55 MiB

Same steps, but opening up https://edition.cnn.com **and** https://www.bbc.com **and** https://www.nytimes.com
_STR Step, Fenix RAM Usage, Google Play Services RAM Usage_
4, 190 MiB, 55 MiB
6, 264 MiB, 55 MiB

### Device information
* Android device: Sony Xperia Z2, Android 6.0.1 | Nokia 6.1, Android 10 (see [Comment 4](https://github.com/mozilla-mobile/fenix/issues/11284#issuecomment-642573247))
* Fenix version:
Nightly 200611 06:01 (Build #2015745585)
45.0.20200610130052, e5839f921
GV: 79.0a1-20200609092134
AS: 60.0.0

**Comment by hakkikaancaliskan** [comment]
I've applied STR via Android Studio profiler on emulator with current master(01ade6e62ae2893ffadb960e021078a5bd5f5d8f) and saw that ram usage increased up to peak 230mb and after that garbage collected and reduced to 167mb.
![Annotation 2020-06-07 201920](https://user-images.githubusercontent.com/17825767/83975432-a44dab80-a8fc-11ea-8ced-016e2dd6a973.png)

**Comment by mcomella** [comment]
Triage: the FE perf team doesn't traditionally fix memory leaks so adding back to Fenix triage.

**Comment by hwinnemoe** [comment]
I could reproduce the issue on another device.

STR Step, Fenix RAM Usage, Google Play Services RAM Usage
4, 165 MiB, 69 MiB
6, 245 MiB, 69 MiB
9, 256 MiB, 68 MiB

Android device: Nokia 6.1, Android 10
Fenix version:
Nightly 200611 06:01 (Build #2015745585)
45.0.20200610130052, e5839f921
GV: 79.0a1-20200609092134
AS: 60.0.0

This device has WR enabled. I will update the original report accordingly. @hakkikaancaliskan what device did you test the STR on?

**Comment by hakkikaancaliskan** [comment]
> 
> 
> I could reproduce the issue on another device.
> 
> _STR Step, Fenix RAM Usage, Google Play Services RAM Usage_
> 4, 165 MiB, 69 MiB
> 6, 245 MiB, 69 MiB
> 9, 256 MiB, 68 MiB
> 
> Android device: Nokia 6.1, Android 10
> Fenix version:
> Nightly 200611 06:01 (Build #2015745585)
> 45.0.20200610130052, e5839f921
> GV: 79.0a1-20200609092134
> AS: 60.0.0
> 
> This device has WR enabled. I will update the original report accordingly. @hakkikaancaliskan what device did you test the STR on?

Xperia XZ1 Android 10 and api 29 emulator.
I confirmed there is a leak.

**Comment by kbrosnan** [comment]
Collecting this data on `about:memory` should show if this is an issue with Gecko or Fenix.

**Comment by hwinnemoe** [comment]
> 
> 
> Collecting this data on `about:memory` should show if this is an issue with Gecko or Fenix.

@kbrosnan What should I look for in detail?

**Comment by hwinnemoe** [comment]
I did some measurements using about:memory using the following STR:
1. Cold startup Fenix, no Addons activated
2. Switch to PBM
3. Open about:memory
4. Press _Measure_ and copy the log
5. Repeatedly switch between other apps and Fenix, e.g. switching 20 times between Settings and Fenix, thus switching to Fenix 10 times
6. Press _Measure_ and copy the log
7. Use _Close private tabs_ to close the single tab
8. Open about:memory again
9. Press _Measure_ and copy the log

Here are the logs for
- STR Step 4: [11284 STR Step 4.txt](https://github.com/mozilla-mobile/fenix/files/4836565/11284.STR.Step.4.txt)
- STR Step 6: [11284 STR Step 6.txt](https://github.com/mozilla-mobile/fenix/files/4836573/11284.STR.Step.6.txt)
- STR Step 9: [11284 STR Step 9.txt](https://github.com/mozilla-mobile/fenix/files/4836575/11284.STR.Step.9.txt)

This starts to look related to #9065.

**Comment by kbrosnan** [comment]
So this is in Gecko then. BZ-1625499 / #9065 exists for this. I'll copy your findings into Bugzilla so that someone investigating that has more data. Going to close this issue out as upstream.
