### ISSUE TITLE
FNX2-13403 ⁃ Add new LeanPlum E_FxA_New_Signup event

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#11280]
The following were identified as missing in a recent test by the Mobile Engagement team. This is requested to be in market by 8/25/20 (release 80).

* [ ] `E_FxA_New_Signup`

This should be fired when the user completes the signup process to new account, but has not yet logged in.

Tasks:

* [ ] Add mapping to `LeanPlumMetricsService.Event.name` from `Event.SyncAuthSignUp` to `E_FxA_New_Signup`.
* [ ] Add test to show it's being fired (e.g. specified by #11210 )

**Comment by cbonacuse** [comment]
@jhugman I see in the Firefox Preview app within Leanplum that we have an event similar to this listed: E_New_Sign_Up_FxA

Is it possible that this already exists? I believe this was opened because E_FXA_New_Signup had been listed on the documentation, but it does not appear that this exists.

**Comment by jhugman** [comment]
This doesn't seem to exist in Fenix at the moment. The closest we have is `E_Sign_In_FxA`.

**Comment by cbonacuse** [comment]
Thanks for confirming @jhugman. Is this something we are able to create? Or is it not possible to fire an event based on first-time sign-up?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200810 from 8/10`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)


✔️ Google Pixel 3a (Android 10) - device ID **`f376dfe2-df54-4cae-a8df-35b0f67e0fba`**
![image](https://user-images.githubusercontent.com/51314259/89772043-06e44300-db0a-11ea-9b78-9b4c448a1b5b.png)

✔️ Huawei Mate 20 Lite (Android 10) - device ID **`ad49654f-0ceb-45a3-9fa5-d842b2a232b6`**
![image](https://user-images.githubusercontent.com/51314259/89772069-0fd51480-db0a-11ea-92f9-a38070f62700.png)

✔️ OnePlus A3 (Android 6.0.1) - device ID **`9d74e964-d227-43ac-acff-a87df2cecada`**
![image](https://user-images.githubusercontent.com/51314259/89772101-1e233080-db0a-11ea-9128-4e562a2d8dfd.png)
