### ISSUE TITLE
Allow persistent testing webextensions

### ISSUE THREAD

**Issue by dbenjaminmiller** [mozilla-mobile/fenix#11292]
Right now, you can install arbitrary extensions from `web-ext`, which will let you run the extension while attached for debugging. I would like to run an extension and keep it running even when not attached to my computer for debugging: this will allow for easier testing of the extension in everyday browsing situations (since the developer doesn't have to be in debug mode and attached to the computer the whole time). Since the functionality is already there, this should be relatively easy to add (be it by allowing the installation of XPIs manually, or through a permanent option in `web-ext`).

Of course, this is not the same as Fenix being ready for general consumer extension support. This is for extended testing, not ready for the general public.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1724)

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/13059

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/11292
https://github.com/mozilla-mobile/fenix/issues/13059
https://github.com/mozilla-mobile/fenix/issues/18477

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/11292
https://github.com/mozilla-mobile/fenix/issues/18477
https://github.com/mozilla-mobile/fenix/issues/20647
https://github.com/mozilla-mobile/fenix/issues/20736

**Comment by vehosah** [comment]
Now, what are we doing here exactly?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813937

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
