### ISSUE TITLE
web page title cut off

### ISSUE THREAD

**Issue by Rorschach-x** [mozilla-mobile/fenix#11295]
## Steps to reproduce
Go to https://www.dailymail.co.uk/tvshowbiz/article-8390023/amp/Leigh-Francis-issues-emotional-apology-playing-black-people-Bo-Selecta.html

### Expected behavior
Should be able to see complete article title.

### Actual behavior
Top of article is beyond screen and cannot be read.

### Device information
* Android device: ? HD1903 OnePlus one 7T, Android 10
* Fenix version: ?
5.0.0 (Build #21212137)
39.0.1, f19856fa4
GV: 76.0-20200424000239
AS: 0.58.2

**Comment by DavidBE-UK** [comment]
I've been getting this too on several newspaper websites.
