### ISSUE TITLE
Refactor DefaultToolbarMenu to observe session selection via store

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#11290]
`DefaultToolbarMenu` is currently using a `SessionManager.Observer` to detect when a session was selected. This can be done using the store instead.

We want to get rid of SessionManager observers so we can finish the A-C refactoring to browser state.

**Comment by eliserichards** [comment]
The HomeFragment is not using the toolbar in the same way that the browser fragments are. It might be worth consolidating it into one implementation

**Comment by eliserichards** [comment]
The HomeFragment should be refactored to fix this ^, but that should happen in another issue.
