### ISSUE TITLE
FNX-4815 ⁃ [Meta] QR code scanner

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#113]
As a user, I want to be able to use my browser to scan a QR code, so I can access a URL or search term for more information.

### Acceptance Criteria:
-I can easily find my browser QR code scanner
-I can tap on the QR scanner to initiate a scan 
-Once QR code is captured, my browser takes me directly to the URL or search result page.

**Comment by colintheshots** [comment]
This should be an Android component. There are two options: - Use Google Vision API, which requires Google Play Services. OR - Hack up the Zebra Crossing (Zxing) app into a reusable component for creating and scanning barcodes. I think the latter makes sense.

**Comment by pocmo** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/1542

**Comment by DevilzIntheDetailz** [comment]
# ## ### ** _ _ > ` [ - ](url) ` ` _ _ ** @colintheshots @pocmo @vesta0

**Comment by DevilzIntheDetailz** [comment]
Pins & PawNs ('iii') (me`)) know ("ii") am… drowing in salt wAter

**Comment by colintheshots** [comment]
I don't know how far A-C has gotten on this, but I've done this three times in my career from Zebra Crossing (ZXing) and could get this done fast. I believe I could crank out a working QR scanner component in two days. Much of the work would actually be stripping away unneeded code.

**Comment by csadilek** [comment]
A-C has a QR scanner / component now (based on ZXing and using the Camera2 API): https://github.com/mozilla-mobile/android-components/tree/master/components/feature/qr

**Comment by sblatz** [comment]
@vesta0 can we close this? This feature is implemented.
