### ISSUE TITLE
FNX2-13418 ⁃ UI-enhancement: change to fennec behaviour to reach browser tab from the login credentials

### ISSUE THREAD

**Issue by Hubfront** [mozilla-mobile/fenix#11303]
When i need credentials for a login page, after copying the password, i need four "clicks" to navigate back to the tab with login page with fenix. In the case i need username too, the way doubles even to eight "klicks" plus before that, i have to use eight clicks to open the password credentials page again, search again for the login page within it. This is too laborious.

With fennec, after copying the password, i just need two "clicks" to navigate to the tab with login site. if i need user name too, i just have to "click" three times back to the already opened password credentials tab, copy the username and to go back to the tab with login page,. This is much shorter.

Pls revert to fennec behaviour cause it is much more ergonomic.

**Comment by ekager** [comment]
We could possibly improve the experience here by adding a close button on the display login screen so you could quickly get back to the browser (if UX agrees) 

Also interesting to you might be #5551

**Comment by Hubfront** [comment]
This would be an improvement. But it would be more ergonomic to keep the logins open in a tab to switch between page and credentials, like it is with fennec.

**Comment by Hubfront** [comment]
Thanks for the hint. In fact i also consider to make a bug for the problem, that fenix cant offer a dropdown menu in the case, there are more than one account for a website. 

What is even more weird is, that unlike desktop firefox, fenix and fennec arent reliable dewtecting the right login for the site, even if there is only a single login credential stored in its database, and therefore forcing the user to navigate to its credentials manually, to search the login and the password manually like i described above. Desktop firefox already detects a login credential, if its connected to the same domain. Why is that? Is the detection algorythm different for fenix and for PC firefox?

**Comment by AmyYLee** [comment]
@ekager We can change the copy url action to open in browser instead next to the URL (See screenshot)

Also can you update the "copy" icon and use the "open in browser" icon below? Thanks

<img width="373" alt="Screen Shot 2020-07-07 at 12 20 51" src="https://user-images.githubusercontent.com/5992746/86812159-afefd780-c04c-11ea-8cd0-b4f61fa7fa29.png">

open-in-new.svg - https://drive.google.com/file/d/1XzAgS9KdTFus2ua_kiYpdL5jP_sA7AE6/view?usp=sharing
copy.svg - https://drive.google.com/file/d/1u0H3gvA5Dou43ZMzpzWpoH3fvieKCnlk/view?usp=sharing

**Comment by softvision-miralobontiu** [comment]
Verified that the "copy" icon is replaced with the "open in browser" icon on the 7/10 Nightly build with Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
