### ISSUE TITLE
FNX-12214 ⁃ [webcontent] Google news not loading properly

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11306]
## Site with issue and any steps to reproduce
https://news.google.com/topstories?hl=en-IN≷=IN&ceid=IN:en

Most of the time the page does not load after the headlines. Individual articles also loading with delay or sometime not loading after clicking it.

### Expected behavior
Site should load properly and instantly..

### Actual behavior
Site not loading properly and on clicking the articles it is also not loading properly...the circle keeps on rotating and there is no network activity. Probably it simply refusing to use the net to load the content. Works fine in normal Firefox for Android , chrome, edge .

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No effect.also tried disabling the add ons.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Working fine

### Can you reproduce in Chrome (or other non-Mozilla browser)?
Working fine

### Device information
* Android device: ? A10.
* Fenix version: ? 21581807
Issue is there since last many version
![Screenshot](https://user-images.githubusercontent.com/58127841/83960246-0e6f3d80-a876-11ea-8205-72792fdeb18b.jpg)UNITO-UNDERSCORE!20200607-094846!

**Comment by sheikh-azharuddin** [comment]
I got the issue ...
When I am enabling http3 this issue is happening

  network.http.http3.enabled

**Comment by cadeyrn** [comment]
> This raises another question why http3 is not properly working/supported in firefox ?

Because it's not yet finished? Even the specification is still a draft. HTTP/3 is not yet production ready! Why do you think it's disabled by default in all browsers? 🤔

Follow https://bugzilla.mozilla.org/show_bug.cgi?id=1158011 for progress on HTTP/3 support in Firefox.

**Comment by sheikh-azharuddin** [comment]
> > This raises another question why http3 is not properly working/supported in firefox ?
> 
> Because it's not yet finished? Even the specification is still a draft. HTTP/3 is not yet production ready! Why - do you think - it's disabled by default in all browsers? 🤔
> 
> Follow https://bugzilla.mozilla.org/show_bug.cgi?id=1158011 for progress on HTTP/3 support in Firefox.

Good point....thanks for the info
Actually I have subscribed to some tech articles which push articles related to security, network etc and they stated the benefits of http3 and how it can be enabled so I enabled it😅

In some sites like YouTube which supports http3 the browsing and streaming speed has increased whereas it fails in Google news...

Thanks again
