### ISSUE TITLE
Automatically select the whole website address, phone number, dates, etc. when long-pressed on them.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11307]
### What is the user problem or growth opportunity you want to see solved?
On mobile devices the screen space is less than on desktop/laptop computers. Selecting upto the exact point is a bit hard on mobile devices so if items like website address, phone number, dates, etc. are selected completely and automatically when long-pressed on them then it would be really helpful. Chrome browser does this. See the screenshots.

![Screenshot](https://user-images.githubusercontent.com/42088907/83961229-a6722480-a880-11ea-84cb-17667c6eb624.png)UNITO-UNDERSCORE!20200607-104510!
![Screenshot](https://user-images.githubusercontent.com/42088907/83961234-aa05ab80-a880-11ea-8dc6-b75b2f5fb40a.png)UNITO-UNDERSCORE!20200607-104457!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1752)

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809296

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
