### ISSUE TITLE
Allow Fenix Homepage to Scoll down for easy one-hand access

### ISSUE THREAD

**Issue by meter1060** [mozilla-mobile/fenix#11304]
Fenix should allow the user to scroll down to access the homepage icons easier with one hand.

Normal Fenix Homepage:
![Top](https://user-images.githubusercontent.com/2201497/83955935-34acc300-a80d-11ea-8e08-0cddcbb7e0bf.jpg)

Quick mock up allowing the user to scroll down the page:
![Scroll Down](https://user-images.githubusercontent.com/2201497/83955951-5c039000-a80d-11ea-95b1-c44df20a125a.jpg)

Here is the Samsung settings page as an example:
![Example Scroll Down](https://user-images.githubusercontent.com/2201497/83955932-32e2ff80-a80d-11ea-9493-0155a61819db.jpg)
![Example](https://user-images.githubusercontent.com/2201497/83955933-337b9600-a80d-11ea-8933-fb090afa6763.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1749)

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
