### ISSUE TITLE
FNX-4816 ⁃ Fenix covers the whole screen, even the area with  triangle/circle/square

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#1130]
## Steps to reproduce
Install Fenix
Start it

### Expected behavior
One should be able to see the normal Android control buttons below the app.

### Actual behavior
The control buttons are hidden and on top of them there is just white area. The viewport of the browser doesn't end up covering it.

### Device information
* Android device: Honor 7
* Fenix version: 1.0.1912 (Build # 10791212)

**Comment by smaug----** [comment]
Apparently the buttons are there, but the background color is just the same as what the button color is, so one can't see them.

**Comment by ekager** [comment]
This is a theming bug. On certain devices we cannot set every color of the system bar, so we will need to change the theme somehow.

**Comment by boek** [comment]
@smaug---- What version of Android are you running?

**Comment by smaug----** [comment]
6. I don't think one can get anything newer to Honor 7.

**Comment by vesta0** [comment]
@ekager is this the same bug as #1144 ?

**Comment by ekager** [comment]
Yes this should be closed
