### ISSUE TITLE
FNX-12220 ⁃  dark theme for Firefox Android version

### ISSUE THREAD

**Issue by ali267** [mozilla-mobile/fenix#11313]
Hello
Add a dark theme for the entire Firefox   for Firefox Android version :
Menu page, bookmark page list, download list page and ....

**Comment by cadeyrn** [comment]
Fenix already has a dark theme? And what do you mean with "download list page"? There is no "download list" in Fenix. 🤔

**Comment by ekager** [comment]
Closing because we already have a dark theme
