### ISSUE TITLE
FNX-12221 ⁃ Button management tab

### ISSUE THREAD

**Issue by ali267** [mozilla-mobile/fenix#11312]
A suggestion for Firefox Android version:

* Open tabs like Firefox Windows version for Android tablets with screens above 7 inches.
* Optional and custom opening of tabs as a Windows version (at the top of the application screen) or as the current version of Android (in a Button management tab) for phones under 7 inches to the user's liking

**Comment by ali267** [comment]
A suggestion for Firefox Android version:

    Open tabs like Firefox Windows version for Android tablets with screens above 7 inches.
    Optional and custom opening of tabs as a Windows version (at the top of the application screen) or as the current version of Android (in a Button management tab) for phones under 7 inches to the user's liking

**Comment by ekager** [comment]
Closing for #2344 . Does that cover your issue?
