### ISSUE TITLE
 tab management toolbar button Android version

### ISSUE THREAD

**Issue by ali267** [mozilla-mobile/fenix#11316]
Firefox menu Android version: Activate the tab management toolbar button at the bottom of the pages:
The next and previous tab transfer button
Go to the next and previous page
Remove the current tab
Remove all tabs
Remove the rest of the tabs except the current one
Bookmark the current page
Load and pause again
Go to the home page
Open the edges of the bookmarks on the same page as a glass layer (to open a new site on the same page - if we close the layer without selecting a new site, the amount loaded from the previous page will be saved and not lost)
Fever profile (name and address)
Add Speed ​​dials button
Fever counter as part / total 3/50
Add page shortcut for tab

  * This button or toolbar can be opened and closed like a drawer.
  * When closed, move a slider on the screen.
  * When it is open, it can be moved up and down
  * The button can be opened vertically or horizontally.

**Comment by kbrosnan** [comment]
This does not seem like a valid issue. It may be that several issues were reported all together. If this can be clarified in another comment we can reopen this.
