### ISSUE TITLE
FNX-12218 ⁃ [Bug] UX elements at bottom of the screen are unresponsive

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#11310]
## Steps to reproduce
Go to any site with buttons at the bottom of the screen and try to click on them.

### Expected behavior
Clicking the buttons should work like normal

### Actual behavior
Any ux elements are not responsive at all. For example on youtube opening the comment section is impossible:
![ezgif-6-608b13822dde](https://user-images.githubusercontent.com/66154603/83972199-20d19180-a8df-11ea-87a0-3cb29951cd20.gif)

### Device information
* Android device: Huawei Nova 6
* Fenix version: Nightly 200606 18:00 (Build #21581807)
45.0.20200605130045, 4a14e7c6f
GV: 79.0a1-20200604092907
AS: 60.0.0

**Comment by ekager** [comment]
Closing for #10720
