### ISSUE TITLE
FNX-4817 ⁃ Black screen when going to settings

### ISSUE THREAD

**Issue by calixteman** [mozilla-mobile/fenix#1131]
## Steps to reproduce
Open settings from 3 dots menu.
There is a furtive black screen 

### Expected behavior
No black screen

### Device information
* Android device: Huawei Bla L29
* Fenix version: 20190312095443

**Comment by ekager** [comment]
Can reproduce on Pixel. Open settings from browsing and you see flash of black on web content.

**Comment by kbrosnan** [comment]
@calixteman is this still an issue with a current build?

**Comment by sblatz** [comment]
![flash](https://user-images.githubusercontent.com/4400286/62739760-87013580-b9ea-11e9-8568-8684b1943323.gif)

This is still reproducible on my Galaxy S9. That being said, I think there's not really a solution. @cpeterso on the GV team has said this is a known issue but not high priority as it's pretty difficult to fix.

**Comment by sblatz** [comment]
Closing in favor of #1901.
