### ISSUE TITLE
 quick access links Android version

### ISSUE THREAD

**Issue by ali267** [mozilla-mobile/fenix#11311]
Hello
A suggestion for Firefox Android version:
Open Firefox / Homepage Firefox / home page default / Quick access links in matrix and table format:

* Add site link manually: site name and site link
* Firefox menu / button Add site link to quick access links
* Firefox menu / bookmarking button / Add link as quick access to Firefox homepage
* Ability to edit site name and site link in matrix mode
* Add unlimited number of links
* Create folders and link categories
* Sort links by dragging your finger.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1765)

**Comment by ali267** [comment]
Hello
A suggestion for Firefox Android version:
Open Firefox / Homepage Firefox / home page default / Quick access links in matrix and table format:

    Add site link manually: site name and site link
    Firefox menu / button Add site link to quick access links
    Firefox menu / bookmarking button / Add link as quick access to Firefox homepage

    Ability to edit site name and site link in matrix mode
    Add unlimited number of links
    Create folders and link categories
    Sort links by dragging your finger.

**Comment by boek** [comment]
We now have a number of methods to quickly access websites in Fenix.
