### ISSUE TITLE
Know when a new add-on becomes available

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11326]
- [ ] https://github.com/mozilla-mobile/android-components/issues/8742

## User Story
As a user, I want to know when a new recommended/supported add-on becomes available on Fenix.

User problem: 
- Our users don't have a way of knowing when an add-on they want becomes available in Fenix unless they manually check for it all the time. 
- They may have checked the add-ons settings page once (or not at all) and decided it wasn't for them at the time but newly added add-ons may fit their needs.

### Acceptance Criteria
* I know when a new add-on is available
* It's clear to me how to install an add-on

**Comment by lindongbin** [comment]
It’s time to enable the installation of all extensions in the addons store and local, instead of the few extensions you recommend. #11308

**Comment by cadeyrn** [comment]
@lindongbin Please don't hijack issue for unrelated requests.

**Comment by teohhanhui** [comment]
#11308 is about sideloading. AMO support is needed to restore an open marketplace where community extensions can thrive again, not just the few handpicked by Mozilla. #5315 was closed without addressing this issue.

I've tried searching but can't find an issue about bringing back an open AMO for Fenix. Could you point us to one, or should someone open a separate issue?

Thanks.

**Comment by brampitoyo** [comment]
We’ve mocked up designs and strings for this last year, I think. I’m posting the design below.

### New Tab Page or Webpage View

A blue notification dot shows up to mark that something new exists in the Main menu.

<img width="360" src="https://user-images.githubusercontent.com/51007/87621319-a402c480-c774-11ea-8bc4-0e6c8e647abd.png">

### Main menu

The “Add-ons” menu item will have a blue dot and a CFR.

Strings:

- 1 new add-on: New in add-ons: [add-on name]
- 2 new add-ons: New in add-ons: [add-on name] and [add-on name]
- 3 new add-ons: New in add-ons: [add-on name], [add-on name], and [add-on name]

We won’t show more than 3 add-ons at a time, and should make sure that this CFR doesn’t show up too often.

<img width="360" src="https://user-images.githubusercontent.com/51007/87621362-bda40c00-c774-11ea-9d9d-da85da061083.png">

### Add-ons submenu

Inside the “Add-ons” submenu, the “Add-ons manager” menu item will have a blue notification dot. Underneath, the caption is labelled “New add-ons available”.

<img width="360" src="https://user-images.githubusercontent.com/51007/87621463-f8a63f80-c774-11ea-8f44-e19f596fb6d9.png">

### Add-ons Manager

Inside the Add-ons Manager itself, we won’t show anything. Users will quickly notice that new icons have appeared to indicate newly available add-ons.

**Comment by eliserichards** [comment]
We are getting a list from AMO, so AC will know based on the cache when the list has changed. This will have to be checked every time a user gets a new app update that contains new addons

**Comment by eliserichards** [comment]
Open questions: 
* leanplum push notification vs CFR implementation
* engineering work for CFR would be greater. What is the tradeoff of leanplum vs cfr for user messaging?
* no AC work required if we do leanplum

**Comment by vesta0** [comment]
We do not want to do this work using LeanPlum.

**Comment by liuche** [comment]
Complexities in this issue:
- we don't have any existing CFRs that link to the menu (which lives in AC)
- we may not have the API from AC exposed yet, to notify that there are new addons

Will need @csadilek to confirm whether these are the main pieces of work, and to file the AC tickets.

**Comment by csadilek** [comment]
@liuche yes, confirmed :). Here's the A-C issue: https://github.com/mozilla-mobile/android-components/issues/8742

**Comment by bifleming** [comment]
Thinking this might not be something we want to do, given we may go to GA in 2021 (Q1?) Need to talk with Add-ons team.
A/C effort is '5'.  Fenix work is at least '13'.
