### ISSUE TITLE
FNX-4818 ⁃ Fenix screen went completely black (not related to Settings)

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1132]
h2. 
Loaded several websites in Fenix. Used the Center button to scroll through my open windows. When I came back to the browser it was black (see screenshot)

h3. 
No black screen

h3. 
Black screen

h3. 

* Android device: Pixel 3
* Fenix version: 20190312095443
![Screenshot](https://user-images.githubusercontent.com/2171777/54786385-186c3880-4bff-11e9-8aba-ffae157e6f4d.png)UNITO-UNDERSCORE!20190321-170652!

**Comment by colintheshots** [comment]
We clearly have a couple ANRs going on. I managed to trigger one by opening "about:config" the other day.

Google Play shows a few with mozilla.components.feature.session.bundling.SessionBundleStorage.current holding onto a lock for mozilla.components.browser.engine.gecko.GeckoEngineSession.saveState executing in runBlocking on the defaultDispatcher. We shouldn't be using the defaultDispatcher at all and runBlocking should be quite limited in use.

**Comment by mozillamarcia** [comment]
I am having a number of issues with freezing and the app stopping on my Pixel 3. If you want logcats let me know.

**Comment by Remeic** [comment]
This problem also occurs on oneplus 6 with oxygenos, if it can help.

**Comment by bsurd** [comment]
Tried with a OnePlus 5T and Pixel but didn't manage to reproduce this issue or find some better STR for it besides the info mentioned by Marcia.

**Comment by Vv2233Bb** [comment]
What is your build date? I had the same problem. Newer builds fixed it for me.

**Comment by mozillamarcia** [comment]
> What is your build date? I had the same problem. Newer builds fixed it for me.

I don't see the black screen anymore, but I still get frequent freezes which cause me to have to close Fenix and restart. Build info is #10931209. I am ok with closing this out and reopening a separate bug for the app freezing.

**Comment by ekager** [comment]
Thanks @mozillamarcia , let's close this ticket and open a separate bug for app freezing.

**Comment by data-sync-user** [comment]
➤ Colin Lee commented:

We clearly have a couple ANRs going on. I managed to trigger one by opening "about:config" the other day.

Google Play shows a few with mozilla.components.feature.session.bundling.SessionBundleStorage.current holding onto a lock for mozilla.components.browser.engine.gecko.GeckoEngineSession.saveState executing in runBlocking on the defaultDispatcher. We shouldn't be using the defaultDispatcher at all and runBlocking should be quite limited in use.
