### ISSUE TITLE
Press the three-dot menu button to open, and release to make a menu selection

### ISSUE THREAD

**Issue by jl8n** [mozilla-mobile/fenix#11321]
Currently opening the three-dot menu/options menu requires a discrete press and release.

It would be better if a single press were to open the menu, which you could then slide/hover over the menu item you'd like, and then release to make that selection.

This feature is available in most Android apps, and when the feature is missing it can slow down workflow and make the UX feel clunky .

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1778)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809230

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
