### ISSUE TITLE
FNX2-13427 ⁃ Add icon to Iindicate what a swipe tab gesture will do

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11324]
## Steps to reproduce
-Delete a tab by swiping

### Expected behavior
-See a trash can icon or an indication that the tab is being deleted.

### Actual behavior
-No indication of tab being deleted until after it's deleted.

### Device information
* Android device: Pixel 4
* Fenix version: Nightly build 21580628

**Comment by liuche** [comment]
This is a bug to restore the previous Fenix tabs functionality. 

Can we size this and put it at the top of the backlog?

**Comment by ekager** [comment]
WIP Video: https://drive.google.com/file/d/14deF3iEvecTz3Lc5gDUd5jZRj7rSMEV8/view?usp=sharing

For this to work, I had to remove the alpha fade out with the swipe action.
Assuming this looks okay @topotropic - could you help me confirm flat colors for the selected tab background without alphas (currently #1F592ACB for light theme and #529059FF for dark theme). Thank you!

**Comment by topotropic** [comment]
> For this to work, I had to remove the alpha fade out with the swipe action.
> Assuming this looks okay @topotropic - could you help me confirm flat colors for the selected tab background without alphas (currently #1F592ACB for light theme and #529059FF for dark theme).

@AmyYLee looping you in here to replace the alpha colors we currently use. Thank you!

**Comment by AmyYLee** [comment]
> > For this to work, I had to remove the alpha fade out with the swipe action.
> > Assuming this looks okay @topotropic - could you help me confirm flat colors for the selected tab background without alphas (currently #1F592ACB for light theme and #529059FF for dark theme).
> 
> @AmyYLee looping you in here to replace the alpha colors we currently use. Thank you!

@ekager 

Hi, here are the solid versions of the higlight:

Light theme: #E5DFF4
Dark theme: #412E69
Private theme (When we implement Private theme): #422875

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Fenix Nightly Build 200713 from 7/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200713-112708](https://user-images.githubusercontent.com/51314259/87282134-a0fd9f00-c4fc-11ea-8db4-ab1c1f5331b1.gif)
