### ISSUE TITLE
FNX-12235 ⁃ [Bug] Jumpy tab when deleting

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11323]
## Steps to reproduce
-Have 2 tabs open
-Swipe to delete one

### Expected behavior
-Smooth deletion and nothing happening to the other tab

### Actual behavior
-Tab being deleted flashes and the other tab preview flashes as well

### Device information
* Android device: Pixel 4
* Fenix version: Nightly build 21580628

**Note: this doesn't happen all the time. Seems to happen more often if the browser is open for a while. I captured a video that I can show you but I couldn't attach it here.**

**Comment by liuche** [comment]
We can dupe this to the AC bug that has also been added to the release column: https://github.com/mozilla-mobile/android-components/issues/7282
