### ISSUE TITLE
FNX-12249 ⁃ [Bug] Dark Reader no longer works in 200608

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11336]
## Steps to reproduce
1. Install Dark Reader.
1. Visit Wikipedia

### Expected behavior
Page is darkened.

### Actual behavior
No change in page.

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 200608 06:00 (Build #21600606)
45.0.20200607130045, 995dd7b93
GV: 79.0a1-20200606094603
AS: 60.0.0

**Comment by csadilek** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1644297

**Comment by agi90** [comment]
@Gusted no specific issue with Dark Reader, `storage.sync` was broken for all extensions on Android. The fix should be in the latest nightly in the next few days.

**Comment by danielzgtg** [comment]
Temporary workaround (tested on 200611 06:01):

1. Open `about:config`
2. Search for `kinto`
3. [Set `webextensions.storage.sync.kinto` to `true`](https://hg.mozilla.org/integration/autoland/rev/fc977a4eff9e6a1d27b1efdc3e0980bc5958976d#l1.12)

**Comment by igalic** [comment]
4. restart

**Comment by Kreuger** [comment]
Wow thank you. I had gone back to using Kiwi until this was resolved. Now there's no need!

**Comment by sheikh-azharuddin** [comment]
This is fixed now in today's build.

**Comment by Gusted** [comment]
Can confirm as well it's working now.

**Comment by igalic** [comment]
workaround reverted again!

**Comment by csadilek** [comment]
Thanks, everyone. Closing as this works again.

**Comment by unixandria-xda** [comment]
This issue occurs on stable Firefox for Android as well right now. The mentioned preference doesn't exist.

Any idea if there's a solution? I can't use either preview because after w couple launches all extensions disappear and I get failed to query add-ons

**Comment by Gusted** [comment]
Re opened? Just updated to latest nightly and it's just working fine.
