### ISSUE TITLE
FNX2-13431 ⁃ Fenix always creates a GeckoRuntime with no ContentBlocking.Settings

### ISSUE THREAD

**Issue by droeh** [mozilla-mobile/fenix#11333]
This is in relation to the GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1621340 and (closed) AC issue https://github.com/mozilla-mobile/android-components/issues/6193

It appears that Fenix always creates a `GeckoRuntime` with no `ContentBlocking.Settings` supplied by the `GeckoRuntimeSettings`: https://github.com/mozilla-mobile/fenix/blob/master/app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt#L45 -- this means that we effectively set the content blocking settings twice; once to the GV default values, and once to whatever a given Fenix install has chosen as its values. This is a pretty expensive startup perf issue according to the profiling Markus did on the (bugzilla) bug.

I don't think there's anything we can do in GV to fix this; my recommendation would be to update `GeckoProvider.getOrCreateRuntime` to optionally take `ContentBlocking.Settings` (or even `GeckoRuntimeSettings`) and pass them to `GeckoRuntime.create()`.

**Comment by mcomella** [comment]
@Amejia481 What's the status of this bug? I see it was removed from the a-c board but is still assigned.

**Comment by Amejia481** [comment]
I was about to start working on it, but I got sidetracked to https://github.com/mozilla-mobile/fenix/issues/11387 issues as it has a higher priority. As soon we get https://github.com/mozilla-mobile/fenix/issues/11387 done, I will return to this issue :)

**Comment by sraturi** [comment]
According to the [profile](https://perfht.ml/3aaEIsB) by @mstange, Seems like we can avoid unnecessary calls to `readPref` inside `SafeBrowsing`. Which would save us approximately ~130 ms?

**Comment by MarcLeclair** [comment]
@mcomella  (or me) need to review the patch

**Comment by mcomella** [comment]
On my GS5, I took a profile:
- before the change b26e39906db511850e71c9ffe62cbf693d27aca5: https://share.firefox.dev/2PqDikQ
- after the change c143f95819aa34e65017ded6bc519d87c2c8a0e0: https://share.firefox.dev/3fyeSjL

However, I'm not sure how to interpret the results to know if this change had the expected impact. mstange makes some hints in https://bugzilla.mozilla.org/show_bug.cgi?id=1621340#c0. I expected `readPrefs` to disappear but it looks like it's about 20ms faster (granted, this is only the difference between one run) and occurs about 1.3s earlier in startup. I'll NI mstange in the BZ issue to try to figure out what I should look for.

**Comment by jonalmeida** [comment]
Based on @mstange 's verification in [the PR comments](https://github.com/mozilla-mobile/fenix/pull/12432#issuecomment-668924385), we can now close this!

Thanks everyone for helping with this fix!
