### ISSUE TITLE
FNX-12241 ⁃ on Dark mode loading page should be dark until first render

### ISSUE THREAD

**Issue by oshanz** [mozilla-mobile/fenix#11330]
## Steps to reproduce
* set dark mode on from settings
* visit a any web page, on dark themed page its more noticeable
example: https://www.roskilde-festival.dk/en/

### Expected behavior
* until the first render starts, tab background should be dark

### Actual behavior
* page is white on loading screen
![photo](https://user-images.githubusercontent.com/5364479/83999484-76aa4600-a980-11ea-8d25-451a87f0e0b6.jpg)UNITO-UNDERSCORE!2020-06-08!UNITO-UNDERSCORE!12-00-08!

### Device information
* Android device: 7.1.1
* Fenix version: Nightly 200526

**Comment by Dunexus** [comment]
I think this is already tracked by #6313

**Comment by oshanz** [comment]
@Dunexus thanks
