### ISSUE TITLE
FNX-12256 ⁃ [Bug] Swipe to delete tab is not responsive enough

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#11341]
When you swipe to remove a tab it will come back for a brief second before it is actually removed

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200624 from 6/24`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200624-101206](https://user-images.githubusercontent.com/51314259/85514036-457a7880-b604-11ea-83bc-ebc096910291.gif)
