### ISSUE TITLE
Autofill option in text selection toolbar

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-mobile/fenix#11347]
### What is the user problem or growth opportunity you want to see solved?
In other apps, fields that can be auto-filled using android (credentials) auto fill have an "Autofill" item in the text selection toolbar. This allows a user to trigger the autofill app, even if it is not showing up on its own. I would think having it on every password type text input would be simple enough and be comparable to the native behavior.

### How do you know that this problem exists today? Why is this important?
As other issues point out, getting the auto fill prompt from your third party password manager is not always reliable. I am sure there's a bunch of issues to blame here, but as a user I'm used to not always getting the prompt automatically and have found that I can use the "Autofill" action to still trigger the prompt. Sadly Firefox Preview only offers me Paste, so I have to leave Firefox preview, open the password manager app and copy the credentials.

### Who will benefit from it?
Any user using a third party password manager that has reliability issues.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1812)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812449

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
