### ISSUE TITLE
[Bug] Page content is not updated until some interactions

### ISSUE THREAD

**Issue by Augures01** [mozilla-mobile/fenix#11356]
## Steps to reproduce
1. Open https://m.vk.com/like?act=members&object=wall-22822305_1097944
1. Go to bottom
1. Click on "likes" page number (2-3, for example)
1. Click on another page number (but not last page)

Also see [comment:](https://github.com/mozilla-mobile/fenix/issues/11189#issuecomment-640998629)
> One thing I realized is that on Fenix when the step 4 is done, the scroll position keeps at the bottom, whereas on Chrome it's reset to the top for some reasons.

### Expected behavior
Content of page changed without any interaction

### Actual behavior
Sometimes it works as expected
Sometimes no response, until you interact with page (scroll page)

### Device information
* Android device: 7.0 on Samsung S6 Edge
* Fenix version: Looks like all Fenix versions is affected (also old Firefox for Android affected)

**Comment by ekager** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1644599

**Comment by Better-hack** [comment]
I think they have a common source of problems.
There is no response if the button rests at the very bottom. There is a response when just above the bottom and when only half extended. Very strange.
https://drive.google.com/file/d/1KCBck6ynloLFKfXsT2MyWQ3d3F2XMiMa/view?usp=sharing

**Comment by liuche** [comment]
Gecko team found that this is present in Fennec as well, so it's now a P3.
