### ISSUE TITLE
FNX-12267 ⁃ [Bug] Long delay when swiping to close tabs with many tabs open (~100 tabs)

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#11352]
We repurposed this issue to address from https://github.com/mozilla-mobile/fenix/issues/11352#issuecomment-641333389

> After further use, it seems the slowdown is only obvious when a large (~100) number of tabs is open.
>
> There's the same 1.5 second delay every time one swipes a tab to close it.

- - -
The new tab from the latest Nightly is very slow.  It opens quickly but then takes a full 1.5 seconds for the thumbnails to display, which is a major regression.

Device has Android 10 and a Kirin 980.

**Comment by robsmith11** [comment]
After further use, it seems the slowdown is only obvious when a large (~100) number of tabs is open.

There's the same 1.5 second delay every time one swipes a tab to close it.

**Comment by mcomella** [comment]
Triage: we should determine at home many tabs does the delay become a problem.

**Comment by mcomella** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/11438

**Comment by mcomella** [comment]
I can no longer reproduce this on 200616 Nightly. I suspect https://github.com/mozilla-mobile/android-components/issues/7313 fixed the issue. Please reopen if you can still reproduce on the latest Nightly (and I'll keep an eye out for it too).

**Comment by robsmith11** [comment]
Yes, the delay seems to be fixed.

There's now a new problem: to switch tabs, one must always tap the thumbnail twice (first tap is ignored), but I guess that should be in a new issue.

**Comment by cadeyrn** [comment]
@robsmith11 This will be fixed in the next Nightly build.
