### ISSUE TITLE
[Feature:China] Works with and defaults to China FxA/Sync servivces

### ISSUE THREAD

**Issue by bli-mozbj** [mozilla-mobile/fenix#11355]
### What is the user problem or growth opportunity you want to see solved?
Works with and defaults to China FxA
with a toggle to use global FxA, simliar to Firefox for iOS

### How do you know that this problem exists today? Why is this important?
Most Chinese users use China FxA/Sync services

**Comment by rxumoz** [comment]
For reference, UI might be like this
![图片](https://user-images.githubusercontent.com/33616048/84217469-d2024280-aafe-11ea-85a1-2ba306fb963b.png)

If it's possible to use a distribution id in China Build, it might be appropriate to associate the default FxA/Sync settings to distribution ids.
