### ISSUE TITLE
FNX-12270 ⁃ [Bug] Pressing back button when address bar is in focus causes page to go back

### ISSUE THREAD

**Issue by rohshr** [mozilla-mobile/fenix#11354]
## Steps to reproduce
1. Open any webpage (A).
1. From webpage (A), open another webpage (B) from a link within (A).
1. Tap the address bar to open the address bar/search overlay.
1. Press the back button (hardware back button/ Android OS soft back button)

### Expected behavior
The address bar/search overlay should close and should show webpage (B).

### Actual behavior
The address bar/search overlay closes and the browser goes back to webpage (A).

### Device information
* Android device: Samsung Galaxy S7 (Android 8.0)
* Fenix version: Firefox Preview 5.1.1 (Build#21571852) 42.0.1, 5bf46033e

**Comment by miDeb** [comment]
See https://github.com/mozilla-mobile/android-components/issues/3600

**Comment by ekager** [comment]
This should be fixed by #11871 in the next nightly
