### ISSUE TITLE
[Bug] "Report Site Issue" icon does not use correct colors and icons for light and dark themes

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#11367]
## Steps to reproduce
Set Fenix in dark mode
Open Addon submenu in Fenix main menu (in a page)
Check the icon near to "Report Site Issue"

### Expected behavior
Icon is white as other Fenix menu icons

### Actual behavior
Icon is black

### Device information
* Android device: Redmi Note 7 Miui 11 Android 9
* Fenix version: #2015745203

**Comment by hakkikaancaliskan** [comment]
@ekager @mcarare 
https://github.com/mozilla-mobile/android-components/blob/b4f036c83d5f26a592761e302efc008f895de24d/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json#L47
adding here `theme_icons` does nothing (broken feature?), so looks like webcompat team need to change icon with `theme` api with `getCurrent`.
[https://discourse.mozilla.org/t/use-theme-colors-for-svg-favicons/29165/2](https://discourse.mozilla.org/t/use-theme-colors-for-svg-favicons/29165/2)
```
"theme_icons": [{
      "light": "icons/lightbulb.svg",
      "dark": "icons/darkbulb.svg",
      "size": 16
    }, {
      "light": "icons/lightbulb.svg",
      "dark": "icons/darkbulb.svg",
      "size": 32
    }]
```

Is there another way i can do?

**Comment by mcarare** [comment]
cc: @denschub

**Comment by denschub** [comment]
We're also tracking this at https://bugzilla.mozilla.org/show_bug.cgi?id=1644451, fwiw.

**Comment by gabrielluong** [comment]
This is the icon that should be used from https://github.com/mozilla-mobile/fenix/pull/15884#issuecomment-712225770

https://github.com/mozilla-mobile/fenix/files/5402793/Report.Site.Icons.zip

**Comment by klint** [comment]
Hi. any update on that issue? Now that the icon moved to the main menu, the color inconsistency in dark mode is more visible and quite obvious. Thanks ;)

**Comment by klint** [comment]
Hi
Could the be resolved now that the new menu has been implemented? Looks ugly on this new shiny menu... 😋Thanks

**Comment by mcarare** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/10092 for a workaround on AC side.

**Comment by codrut-topliceanu** [comment]
> Opened [mozilla-mobile/android-components#10092](https://github.com/mozilla-mobile/android-components/issues/10092) for a workaround on AC side.

AC fix for this issue has been merged. 
Changes will be reflected in Fenix on AC bump.

**Comment by klint** [comment]
Seems to be fixed on lastest Nightly, thanks a lot.

**Comment by denschub** [comment]
Hey @mcarare, I noticed that we don't get an icon right now, or a placeholder icon:

![Screenshot_20210528-174853_Firefox_Nightly](https://user-images.githubusercontent.com/344777/120024143-0e200300-bfef-11eb-9672-e3b7c5d07dc3.png)

Are you aware of that, and is this related to the patch you submitted 10 days ago, or should I open a new bug?

**Comment by cadeyrn** [comment]
> or should I open a new bug?

There is already #19558.

**Comment by mcarare** [comment]
The report site issue with the light theme will be tracked in https://github.com/mozilla-mobile/fenix/issues/19558.
