### ISSUE TITLE
FNX-12282 ⁃ [Bug] Reorganize "Set as default browser" and "Open links in apps" from Settings

### ISSUE THREAD

**Issue by ValentinTimisica** [mozilla-mobile/fenix#11365]
Created this issue based on @brampitoyo's [comment](https://github.com/mozilla-mobile/fenix/issues/8380#issuecomment-624967123).

> “Open links in app” was originally specced out to be under “Set as default browser” because we didn’t have an “Advanced” section.
> 
> Now that we have the right section to put it (as well as to contain other things), AmyYLee and I thought that we should put “Open links in app” under it.
> 
> So a slightly revised Settings organisation look like this. Note two things:
> 
> * “Set as default browser” is a menu item on the root-level with a toggle. Same position as before: underneath “Language”
> * Similarly, “Open links in apps” is also a menu item on the root-level with a toggle. It has a different position now: in the “Advanced” section, underneath “Add-ons”
> 
> <img alt="" width="360" src="https://user-images.githubusercontent.com/51007/81242538-8a9d1800-9061-11ea-9832-333cb79a814e.png">
> 
> We hope that this helps bring it up to the forefront!

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/11 with the following devices:
- Huawei MediaPad M2 (Android 5.1.1) 
- Nokia 6(Android 7.1.1) 
- Samsung Galaxy Note 10 (Android 10)
