### ISSUE TITLE
FNX-12278 ⁃ [BUG] closing tabs isn't smooth

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#11363]
Steps to reproduce:

1. Open 4 to 5 tabs
1. Try to close by SWIPING
1. here you see bug

Expected Behaviour:
All tabs should close flawlessly when closed by swiping horizontally

Actual Behaviour:
Tabs close after repositioning to normal position.
If tab no. 1 which is on top is closed, bottom tabs do not move up unless we do that manually

Device Info:
Xiaomi Redmi Note 4, Android 7.0,
Fenix version Nightly 200609 06:00 (Build #21610607)
45.0.20200608190110, 8ec16f840
GV: 79.0a1-20200608094842
AS: 60.0.0

**Comment by mcarare** [comment]
Related issue: https://github.com/mozilla-mobile/fenix/issues/11341.

**Comment by RealGJ** [comment]
Now tabs are closing smoothly.
Closing as Fixed in: Nightly 200617 06:00 (Build #21690607)
AC: 45.0.20200616130058, a261a24e5
GV: 79.0a1-20200615092624
AS: 60.0.0
