### ISSUE TITLE
FNX2-15063 ⁃ [Bug]Can't launch on first attempt Fenix geckoNightlyDebug on Huawei Mate 20 Lite (Android 9)

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11364]
## Steps to reproduce
1. Launch Fenix debug build (build variant geckoNightlyDebug)

### Expected behavior
Fenix Debug build should launch properly after install

### Actual behavior
Can't launch Fenix on first try
This error is displayed, and only **after tapping ok for the 5th time Fenix will launch**
**`The app Firefox Preview(process org.mozilla.fenix.debug) has violated its self-enforced StrictMode policy`**

### Device information
* Android device: Huawei Mate 20 Lite (Android 9)
* Fenix version: Fenix Debug build 45.0.20200608190110, 8ec16f840 GV: 79.0a1-20200608094842 AS: 60.0.

### Notes
► Screenshot
![rsz](https://user-images.githubusercontent.com/51314259/84141963-adee2500-aa5c-11ea-9bcb-9d1e0443d787.jpg)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200609!UNITO-UNDERSCORE!140731!UNITO-UNDERSCORE!orgmozillafenixdebug!

@mcomella & @MarcLeclair - Is this related to #10831 ?

**Comment by mcarare** [comment]
Same issue on Huawei P10, Android 9, from logcat:  `android.os.strictmode.DiskReadViolation` in these cases: 
- `        at android.graphics.HwTypefaceUtil.updateFont(HwTypefaceUtil.java:154)
        at android.graphics.Typeface.loadSystemFonts(Typeface.java:1212)`
- ` at android.app.ResourcesManager.getResources(ResourcesManager.java:982)
        at android.app.ContextImpl.createResources(ContextImpl.java:2302)
        at android.app.ContextImpl.createSystemUiContext(ContextImpl.java:2610)
        at android.app.ActivityThread.getSystemUiContext(ActivityThread.java:2631)
        at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5852)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3599)`
- `      at java.lang.Class.getDeclaredMethodInternal(Native Method)
        at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
        at java.lang.Class.getMethod(Class.java:2063)
        at java.lang.Class.getMethod(Class.java:1690)
        at androidx.core.os.TraceCompat.<clinit>(TraceCompat.java:56)
        at androidx.core.os.TraceCompat.beginSection(TraceCompat.java:100)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4403)`

**Comment by MarcLeclair** [comment]
Mhm we just landed stricter strict mode violation. This looks like its a huawei specific thing since I can run this on Px4 and G5 but my P20 is seeing the dialog. Seems like manufacturers have different implementation for their font class ( we did notice this with Samsung and the Px4 initially). An educated guess would be that with different OS "skins" (such as `touchwiz` for samsung) has a different font classes. Not too sure what to do about this one @mcomella

**Comment by cadeyrn** [comment]
> This looks like its a huawei specific thing

It's not only an issue on Huawei devices. I see six of these dialogs on the OnePlus 7T Pro McLaren.

**Comment by MarcLeclair** [comment]
@cadeyrn  I should've edited it, thanks for pointing that out!  I think it's a manufacturer specific issue when there's a wrapper around the base OS (such as touchwiz by samsung) 😄

**Comment by sv-ohorvath** [comment]
@sraturi @MarcLeclair this is still happening and it's on a Pixel 2 virtual device, see: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5775755259756697270/executions/bs.3a35aa14d22c065c/videos

**Comment by sv-ohorvath** [comment]
Still happening on virtual devices and causing automation tests to fail: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8312248502354333158/executions/bs.3cd755354eeaaddc/videos

**Comment by sraturi** [comment]
@sv-ohorvath I'm not able to see the logs.. (LDAP problem...) but I'm running the emulated pixel 2 device with API 28 and don't see any pop-ups? I wonder if its an API thing?

**Comment by sv-ohorvath** [comment]
@sraturi This is what I have from the Firebase logs:
Test log: 
[strictModeLog.txt](https://github.com/mozilla-mobile/fenix/files/5020634/strictModeLog.txt)
The pop-up: 
![strictModePopUp](https://user-images.githubusercontent.com/4037709/89263421-e9ab0280-d639-11ea-8545-1333a8a35e32.png)

**Comment by mcomella** [comment]
@sraturi Did you file a new bug for this issue? i.e. #13368 ? If so, we should close this again.

**Comment by sraturi** [comment]
Hi @mcomella  No #13368  is a seperate issue that I ran into. I was trying to replicate this issue but havent had any luck yet.
