### ISSUE TITLE
FNX2-13441 ⁃ [Bug]Site notification doesn't show full message

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#11375]
I have subscribed to Twitter notifications on preview nightly and when you get notifications from Twitter they aren't shown fully , only first line is shown from that tweet.
While I have Vivaldi(chromium based browser) installed and have Twitter notifications on and they show full tweet in notification panel.
Screenshot for comparison-
![Screenshot](https://user-images.githubusercontent.com/42364681/84167747-24435500-aa66-11ea-81c1-4143bebf6474.png)UNITO-UNDERSCORE!20200609-205105!UNITO-UNDERSCORE!1!

**Comment by AmyYLee** [comment]
@betsymi For recommendation

**Comment by jonalmeida** [comment]
It's not clear to me what strings are needed here. It looks like the bug is that we aren't making the android notification expand for the full text.

I've put up a patch here for this in a-c: https://github.com/mozilla-mobile/android-components/pull/7568

**Comment by betsymi** [comment]
> It's not clear to me what strings are needed here. It looks like the bug is that we aren't making the android notification expand for the full text.
> 
> I've put up a patch here for this in a-c: [mozilla-mobile/android-components#7568](https://github.com/mozilla-mobile/android-components/pull/7568)

That is my understanding as well. I don't think strings are needed.

**Comment by jonalmeida** [comment]
This should be fixed in the latest Nightly with the latest a-c build.

**Comment by jonalmeida** [comment]
@Scripterr thanks for filing this bug before your phone battery died! 🙃

**Comment by Scripterr** [comment]
Thank @jonalmeida , it's fixed in latest nightly build.

**Comment by sflorean** [comment]
Verified as fixed on Firefox Nightly 7/3 with Samsung Galaxy Note 10 (Android 10).
