### ISSUE TITLE
FNX-12287 ⁃ [Bug]Download Dialog inoperational

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#11371]
`DynamicDownloadDialog` which appears `onDownloadStopped` no longer displays size of downloaded file, "open" button no longer works, and its instance is no longer tied to the tab that spawned it.

## Steps to reproduce
1. Go to www.wikipedia.org
1. Long press on wikipedia logo
1. Choose "Save image"
1. Wait for the Download Dialog to appear

### Expected behavior
* "Download completed" should be followed by the size of the file downloaded e.g.: (0.5 MB)
* Pressing "Open" should open the downloaded file
* changing tabs should hide the dialog until returning to its parent tab

### Actual behavior
* "Download completed" is followed by "(null)"
* "Open" button no longer works properly
* Download Dialog instance is no longer tied to the tab that spawned it

### Device information
* Android device: Pixel 3XL & Pixel 4 (Android 10)
* Fenix version: latest nightly

Note: Waiting for https://github.com/mozilla-mobile/android-components/issues/7050 to close

**Comment by Amejia481** [comment]
""Download completed" is followed by "(null)" The null issue will covered by  https://github.com/mozilla-mobile/android-components/issues/7308

**Comment by liuche** [comment]
Maybe this is also related to/causing #11107, where the download size is not showing up, so the download progress is also wrong?

**Comment by codrut-topliceanu** [comment]
I worked on the latest master yesterday and #11107 didn't come up. But I haven't tried google drive download.

**Comment by codrut-topliceanu** [comment]
Needs https://github.com/mozilla-mobile/android-components/pull/7365 to be merged before [PR for this issue](https://github.com/mozilla-mobile/fenix/pull/11518) will be testable.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200619-130939](https://user-images.githubusercontent.com/51314259/85125076-adf7dd00-b233-11ea-9616-765d1588d7f8.gif)
