### ISSUE TITLE
Add lint rule for AppCompatResources instead of ContextCompat

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#11397]
This will prevent crashes like: https://github.com/mozilla-mobile/fenix/pull/11395

**Comment by juan-goncalves** [comment]
Hey @sblatz I can do this

What should be the severity of the issue when detected? (Warning, Error)

I'm thinking on showing an error with a replace suggestion everytime a `ContextCompat.getDawable` or `ContextCompat.getColorStateList` call is detected, as they are the only methods available in the `AppCompatResources` class

**Comment by gabrielluong** [comment]
> Hey @sblatz I can do this
> 
> What should be the severity of the issue when detected? (Warning, Error)
> 
> I'm thinking on showing an error with a replace suggestion everytime a `ContextCompat.getDawable` or `ContextCompat.getColorStateList` call is detected, as they are the only methods available in the `AppCompatResources` class

I think your suggestion sounds good! @ekager any other suggestions?

**Comment by juan-goncalves** [comment]
Great! 
I'll open a PR shortly, I think its ready (let me know if you want anything changed)

![image](https://user-images.githubusercontent.com/10901485/96385812-465f8900-1164-11eb-8aef-917f921162b7.png)
