### ISSUE TITLE
[Bug] Pages render as black screen on Nvidia Shield Tablet

### ISSUE THREAD

**Issue by justinsteffy** [mozilla-mobile/fenix#11394]
## Steps to reproduce
Navigate to any url in the browser. Also applies when opened as a web view in other apps.

### Expected behavior
The page is rendered. This worked up until a couple of weeks ago.

### Actual behavior
The page is completely black.

### Device information
* Android device: Nvidia Shield Tablet,  Android 7.0, Shield tablet software version 5.4
* Fenix version: 5.1.1 (Build 21571851), 42.0.1, 5bf46033e

**Comment by liuche** [comment]
Hi @justinsteffy! That sounds bad, does this happen even with a restart? There's a bug where the screen turns black when full-screening a video #10896 that's now fixed.

Is there any more information you could share about what might be causing this? That way we can try to reproduce and fix it.

**Comment by justinsteffy** [comment]
@liuche sorry but I don't have much more to provide. Here are some steps I just took to test and troubleshoot. To be clear, the issue is that the page content is black all the time for every page in every mode. Its not related to video content. Here is a list of things I tried with no change:

* Reboot
* Disable ublock add on
* Try requesting desktop site
* Close all tabs, try private browsing, etc
* Clear data/cache, uninstall and reinstall leaving all settings default

When navigating to a page the loading bar seems to work as normal and the page is searchable using "Find in page". The entire content area is black.

If you can provide me with some ideas of how to help debug, find log files, or whatever, I'd be happy to help.

**Comment by bitchef** [comment]
Hi,

I am experiencing the same problem but with a slighly different hardware configuration.

**Hardware**: Xiaomi Mipad 1 Tegra k1 32bit
**OS**: Android 7.1.2  [LineageOS 14.1 with Nvidia Shield blobs](https://forum.xda-developers.com/mi-pad/development/lineageos-14-1-t3850621)

I first noticed the problem after updating **Firefox Focus** from **8.3.0** (Build #341281935 🦎 76.0-20200429185419) to **8.4.0** (Build #341610024 🦎 77.0-20200602142841). 
The release note (What's new) for the update states _"Updated Geckoview engine to latest release"_. 

A web search lead me to this thread. I performed more tests with Firefox Preview (fenix) and Firefox Nightly (fennec aurora) to determine when the bug first occured.  I wanted to use Firefox Preview Nightly but couldn't find an armeabi-v7a compatible version on ApkMirror for builds later than [March 11, 2020](https://www.apkmirror.com/apk/mozilla/firefox-preview-nightly-for-developers/firefox-preview-nightly-for-developers-nightly-200311-1801-release/firefox-preview-nightly-for-developers-nightly-200311-1801-2-android-apk-download/) which, by the way, is functional.

I performed the same series of tests as @justinsteffy

* Reboot
* Disable ublock add on
* Try requesting desktop site
* Close all tabs, try private browsing, etc
* Clear data/cache, uninstall and reinstall leaving all settings default

and managed to narrow the search down to the following versions. 

**Firefox Preview (fenix)**

_Last working_
[5.0.0 (Build #21212136)](https://www.apkmirror.com/apk/mozilla/firefox-fenix/firefox-fenix-5-0-0-release/firefox-preview-5-0-0-3-android-apk-download/)
39.0.1, f19856fa4
GV: 76.0-20200424000239
AS: 0.58.2
Thursday 4/30 @ 9:36 PM

_First breaking_
[5.1.0 (Build #21502228)](https://www.apkmirror.com/apk/mozilla/firefox-fenix/firefox-fenix-5-1-0-release/firefox-preview-5-1-0-android-apk-download/)
42.0.1, 5bf46033e
GV: 77.0-20200526221856
AS: 0.58.2
Friday 5/29 @ 10:28 PM

**Firefox Nightly (Fennec Aurora)**

_Last working_
[Nightly 200420 06:01 (Build #2015735601)](https://www.apkmirror.com/apk/mozilla/firefox-nightly-for-developers/firefox-nightly-for-developers-nightly-200420-0601-release/)
39.0.20200418130110, 95d71affe
GV: 77.0a1-20200417100143
AS: 0.57.0
Monday 4/20 @ 6:12 AM

_First breaking_
[Nightly 200422 16:13 (Build #2015736065)](https://www.apkmirror.com/apk/mozilla/firefox-nightly-for-developers/firefox-nightly-for-developers-nightly-200422-0600-release/firefox-nightly-for-developers-nightly-200422-0600-3-android-apk-download/)
39.0.20200422145552, 1ee8c073e
GV: 77.0a1-20200422093542
AS: 0.57.0
Wednesday 4/22 @ 4:17 PM

I hope this helps!

**Comment by philbertasusa** [comment]
Another nvidia sheild user having the same issue

**Comment by ekager** [comment]
Thanks so much for the info, everyone! I [filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1647172) with the GeckoView team.

**Comment by bitchef** [comment]
Thank you for the quick answer, and thank you for your dedication to an open web. 
Glad that my little contribution was (will be?) helpful ;-)

**Comment by gabrielesvelto** [comment]
FYI I managed to reproduce the issue on my tablet and I'm developing a fix. With a bit of luck I might be able to slip it in the next release.

**Comment by gabrielesvelto** [comment]
The corresponding issue on Bugzilla tracking this work is bug [1647172](https://bugzilla.mozilla.org/show_bug.cgi?id=1647172).

**Comment by ekager** [comment]
It usually takes Fenix Nightly a few days after something lands to get a new GV nightly but @justinsteffy @bitchef @philbertasusa can you be on the lookout and let us know if this is fixed after updating nightly this week? Thanks so much for your help!

**Comment by bitchef** [comment]
Fantastic news!  (*＾▽＾)／  Thanks a lot @gabrielesvelto @ekager !

As of today (**2 July 2020 10:50 UTC**) GV 80.0a1 hasn't yet landed. The latest build on the Play Store is still using GV 79.0a1 (see below)

Nightly 200702 06:03 (Build #2015749617)
AC: 49.0.20200701130905, 14d09cc4a
GV: 79.0a1-20200629094229
AS: 61.0.7
Thursday 7/2 @ 6:11 AM

I'll keep you updated as soon as I get an upgraded version. Waiting with bated breath! Thanks again!

**Comment by bitchef** [comment]
Houston, we have a liftoff! \\(＾▽＾)/

I tested a few sites [Hacker News](https://news.ycombinator.com/), [ArsTechnica](https://arstechnica.com/), [BBC News](https://www.bbc.com/news), [NYTimes](https://www.nytimes.com/) and [WaPo](https://www.washingtonpost.com/). 

Glad to report that everything went well:
- pages are rendering. No more black screen!
- links are working.
- text selection, copying, pasting and searching are functional.

Job well done guys and gals! Thanks!

Nightly 200703 06:16 (Build #2015749809)
AC: 49.0.20200702131412, 1cba216b2
GV: 80.0a1-20200701093012
AS: 61.0.7
Friday 7/3 @ 6:23 AM

**Comment by justinsteffy** [comment]
@gabrielesvelto @ekager Also works for me on my shield. Thanks for the quick fix!
