### ISSUE TITLE
FNX-12321 ⁃ Remove GAID from installation ping, and rename the ping to first_session

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11392]
## Description & Product Manager / Data Scientist User Story
from @magorlick:

* [ ] We remove the device_id (GAID) as planned, from the **installation ping** (the activation ping should be unchanged)
* [ ] We change the name of the event from 'installation' to 'first_session'. 

The second change is needed for two reasons.  The moment the event captures is actually NOT the installation event.  Instead, it truly is the first time the app is opened.  This removes ambiguity from the name.  Folks do care about the difference in these two numbers.  Secondly, we need to have an aggressive policy from deleting the data moving forward.  By changing the event name we can simply reject all events with the name 'installation' and accept the first_session telemetry that does not have the device_id.

## What questions will you answer with this data?
This is removing telemetry that we don't need anymore.

## Acceptance Criteria
* [ ] Remove GAID from installation ping
* [ ] Rename `installation` ping to `first_session` and update telemetry

**Comment by sblatz** [comment]
I don't see the GAID in master in the `InstallationPing` I will touch base with Marissa to see if we need to remove from a different build?

**Comment by sblatz** [comment]
Touched base, we just need to push a new build to the Fenix Beta channel once the PMF experiment is over and we'll automatically drop the GAID since it's not in master. I will update the first_session thing though.

**Comment by sblatz** [comment]
Chatting with marissa about this on slack because there's a bug in the glean documentation generation that stops us from having a ping with an underscore OR hyphen in it. (we should be allowed to us hyphens).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly Build 200626 from 6/26 `** and **`Beta 78.0.0-beta.1 from 6/26`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ **`First_session ping `**  - **Nightly installed through a marketing campaign**

```kotlin
{
      "client_info": {
        "android_sdk_version": "29",
        "app_build": "21780613",
        "app_channel": "fenixNightly",
        "app_display_version": "Nightly 200626 06:01",
        "architecture": "arm64-v8a",
        "client_id": "41224a9d-29b3-482e-b49f-e3c4b904e2cb",
        "device_manufacturer": "Google",
        "device_model": "Pixel 3a",
        "first_run_date": "2020-06-26+03:00",
        "locale": "en-US",
        "os": "Android",
        "os_version": "10",
        "telemetry_sdk_build": "31.1.1"
      },
      "metrics": {
        "datetime": {
          "first_session.timestamp": "2020-06-26T11:19:20.946+03:00"
        },
        "string": {
          "first_session.adgroup": "twitter",
          "first_session.campaign": "social",
          "first_session.creative": "fr-gtm",
          "first_session.network": "Product Marketing"
        }
      },
      "ping_info": {
        "end_time": "2020-06-26T11:19+03:00",
        "seq": 0,
        "start_time": "2020-06-26T11:19+03:00"
      }
    }
```
 
✔️ **`First_session ping `**  - **Beta migration Organic install**

```kotlin
{
      "client_info": {
        "android_sdk_version": "28",
        "app_build": "2015748425",
        "app_channel": "fennecBeta",
        "app_display_version": "78.0.0-beta.1",
        "architecture": "arm64-v8a",
        "client_id": "6bb938da-5437-4937-83fa-62abedcd93c1",
        "device_manufacturer": "HUAWEI",
        "device_model": "SNE-LX1",
        "first_run_date": "2020-06-26+03:00",
        "locale": "en-ES",
        "os": "Android",
        "os_version": "9",
        "telemetry_sdk_build": "31.1.1"
      },
      "metrics": {
        "datetime": {
          "first_session.timestamp": "2020-06-26T10:29:22.402+03:00"
        },
        "string": {
          "first_session.adgroup": "",
          "first_session.campaign": "",
          "first_session.creative": "",
          "first_session.network": "Organic"
        }
      },
      "ping_info": {
        "end_time": "2020-06-26T10:29+03:00",
        "seq": 0,
        "start_time": "2020-06-26T10:29+03:00"
      }
    }
```
[Logcat OnePlus](https://github.com/mozilla-mobile/fenix/files/4835874/onepl.txt)
[Glean dashboard - OnePlus A3](https://debug-ping-preview.firebaseapp.com/pings/aj-testMigra2606002)

[Logcat Huawei](https://github.com/mozilla-mobile/fenix/files/4835875/huaw.txt)
[Glean dashboard - Huawei Mate 20 Lite](https://debug-ping-preview.firebaseapp.com/pings/aj-testMigra2606003)

[Logcat Pixel 3a](https://github.com/mozilla-mobile/fenix/files/4835877/pix.txt)
[Glean dashboard - Google Pixel 3a](https://debug-ping-preview.firebaseapp.com/pings/aj-t26060)

As @sblatz mentioned, the GAID (device_id) **was never displayed in the installation ping**. (correct me if I'm wrong ☺️ )
