### ISSUE TITLE
FNX-4821 ⁃ [Meta] Onboarding

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#114]
As a user, I want to learn about key features in Fenix and understand my data privacy rights when I first start using it so I can make the most out of the browser, and feel that Fenix protects my data and respects my rights.

### Requirements (these are product recommendations and could take the form of status onboarding cards or in-app notifications/just-in-time messaging, to be determined by UX)
UX designs: #179 

* Include a “Welcome to Fenix: a fast, private, and seamless browsing experience”. “Fenix puts you in control”, “Firefox is on your side”
* CTA: Log into (or sign up for) your FxA account to use this early access version of the browser.
* Highlight privacy (Protect your data! We are blocking malicious trackers by default, etc)
* Highlight fast (Browsing is faster than ever, improved performance, address bar is at the bottom, smart search bar, enabling search shortcuts, etc)
* Highlight Seamless (intro to Sessions)
* CTA: Make Fenix your default (provide access to default browser setting/toggle)
* Legal requirements:
* Persistent access to privacy notice
* Notify users about the default telemetry state and how to change it

### Acceptance Criteria:
* I can only use Fenix if I sign up for an FxA account.
* I understand how Fenix stands out amongst other browsers.
* I know how to make Fenix my default browser.
* I have access to the user privacy notice
* I know what data I am sharing with Mozilla and how to change it. how to change what data I share with Mozilla

**Comment by bbinto** [comment]
Corresponding UX issue: https://github.com/mozilla-mobile/fenix/issues/179

**Comment by bbinto** [comment]
We should consider using Leanplum for the initial onboarding

**Comment by apbitner** [comment]
InVision :https://mozilla.invisionapp.com/share/XBRNF6MJVUY
