### ISSUE TITLE
Collapse/expand synced devices  in synced tabs UI

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11402]
### What is the user problem or growth opportunity you want to see solved?
I would like to be able to collapse my synced tabs per device so that I can more quickly find the tab I am looking for (if I know which device it exists on). 

### How do you know that this problem exists today? Why is this important?
Right now, I have to scroll past devices that may not be interesting to me. This makes this feature annoying to use since it is an inefficient use of my time.

### Who will benefit from it?
Anyone using multiple sync devices and the synced tabs UI.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1890)

**Comment by amkcpu** [comment]
IIRC, this used to be possible in Fennec.

**Comment by madb1lly** [comment]
Hi @yoasif and @amkcpu,

I completely agree, the current UI is not helpful for untidy and disorganised people like me who might have (ab)used the simple tab groups addon for desktop and now have maybe over 1000 tabs floating around on different devices... 😰

Cheers 🙂

**Comment by jonalmeida** [comment]
This is done by @MozillaNoah , losing as fixed!
