### ISSUE TITLE
FNX-12332 ⁃ Don't add a tab tray, but instead add a website preview onto the tabs within the tab menu.

### ISSUE THREAD

**Issue by fellowish** [mozilla-mobile/fenix#11400]
**The new tab tray in Nightly is rather unintuitive.** The previews of webpages is nice, but it also makes it harder to reach collections and also kind of breaks apart the overall design language of the app (the shape of tabs being similar the bar, and also being similar to collections, etc.).

Instead of making a tab tray which doesn't exactly serve a purpose (that I can tell?) beyond showing a web page in the background (which is already done by the preview within the tabs in the tab tray), add the preview into the current menu for tabs. What I'm requesting here is to preserve these 4 things:

* App design language
* Easy access to collections
* Easy access to search/address bar for new tabs
* Easy access to top sites

I've seen numerous complaints over the tab tray **for not preserving those 4 important parts of the app**, and I believe my idea will accomplish what you're wanting to do with the tab tray in the first place, while preserving all 4 of the above features.

Example:
![image](https://user-images.githubusercontent.com/28973978/84207529-337ece80-aa77-11ea-9e41-8416f29eeccb.png)

**Comment by ekager** [comment]
Thanks for the feedback! We're going to keep improving the tabs tray so stay tuned!
