### ISSUE TITLE
"Open all..." option (Synced tabs, Bookmark Folder, etc)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11404]
### What is the user problem or growth opportunity you want to see solved?
Users should be able to open all of their synced tabs in Fenix in order to quickly restore a session from another device.

### How do you know that this problem exists today? Why is this important?
My Pixel is getting replaced due to a hardware issue. I want to maintain my user data from my previous device, and https://github.com/mozilla-mobile/fenix/issues/2080 is not yet a feature. Google restores also don't restore my session from the cloud.

The closest feature to restore my tabs from my old device is sync, but it is extremely cumbersome to tap 3 times for every tab I want to migrate. I have over 100 tabs in my old device, so that at a minimum, 300 taps on my screen along with the sheer inefficiency of the process. 

### Who will benefit from it?
Anyone who wants to migrate their existing session to a new device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1892)

**Comment by Taknok** [comment]
To be reopened, and I'm out https://github.com/mozilla-mobile/fenix/pull/21212#issuecomment-1254319205

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 108.0a1 from 10/27 with OnePlus 9 Pro (Android 12). "Open all in new tabs" and "Open all in private tabs" options are displayed in Bookmark folders menu.

<img src="https://user-images.githubusercontent.com/108326843/198212014-c8a85f83-bb9f-4367-8660-375c39007561.JPEG" width="50%" />

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Beta 108.0b1.
Device used: Google Pixel 4 (Android 13).
