### ISSUE TITLE
FNX-12340 ⁃ [Bug] Scroll position of tabs tray is lost when switching between normal & private tabs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11406]
## Steps to reproduce
* Open more than a screen full of tabs in the tabs tray
* Select a tab at the bottom
* Open tabs tray
* Switch to private tabs
* Switch to normal tabs

### Expected behavior
Scroll position remains the same

### Actual behavior
Scrolls to top

### Device information
* Android device: P2
* Fenix version: local build, today master 32bfba5b3660bf4c9d8cad1006dd89d9d68142b0

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200625-110744](https://user-images.githubusercontent.com/51314259/85682899-64950b00-b6d5-11ea-9336-f208fc536b36.gif)

**Comment by marcel263** [comment]
@AndiAJ Good day, still this issue fixed for you? Issue reproduces on 97.0a1 (Build #2015852235)
