### ISSUE TITLE
[Feature Request] Swipe down on share sheet to close it

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11410]
Currently I have to press back button to close the share sheet or tap on the empty space. Swipe down on share sheet to close it would make it easier to exit it just like the new Tabs Tray. And it'd also be consistent with the new Tabs Tray behaviour.

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)
