### ISSUE TITLE
[Bug] Animation glitches when closing tabs

### ISSUE THREAD

**Issue by vishalnandagopal** [mozilla-mobile/fenix#11417]
## Steps to reproduce
1. Open few tabs
1. Close them one by one

### Expected behavior
When you close 1 tab by swiping on it sideways, the tab will close and the focus will shift to another tab (the purple color over a current tab) 

### Actual behavior
It glitches, loads the tab back, and then shifts focus.

### Device information
* Android device: Android 10 RN5P ( whyred )
* Fenix version:  Nightly 200609 06:00 (Build #21610607)

**Comment by AlanSanchezP** [comment]
I no longer get this bug on Nightly 200620 06:00 (Build #21720606)
