### ISSUE TITLE
FNX2-13455 ⁃ [SUMO] What's New in Fenix 79.0.0

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11414]
Making this placeholder so we can keep track of what is new in Fenix 6.0, and make sure we have any SUMO articles prepared.

[doc for SUMO team](https://docs.google.com/document/d/1ODx9YUqLk9vlv4KJF_kvdkQWz1q9BvVITtjbAJdK0xc/edit#)

**Comment by kbrosnan** [comment]
Is this useful @liuche?
