### ISSUE TITLE
[Feature:China]Add a notification of privacy&rights in the first launch in China builds

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#11413]
### What is the user problem or growth opportunity you want to see solved?
China government requires all the apps to show privacy notification prominently during the first launch and  users can only use the apps normally after they click the consent button; otherwise if they click the disapproval button, the app should quit.

Here is what we do now in Fennec. Basically we use the content of _about:rights_.
![图片](https://user-images.githubusercontent.com/33616048/84219190-85b90180-ab02-11ea-8f88-995e8e36fc5a.png)

### How do you know that this problem exists today? Why is this important?
It is required by laws and regulations in China.

**Comment by cadeyrn** [comment]
@sheikh-azharuddin What is your problem that you give a thumbs down on almost every isssue about the build for China? 👎 Especially if something is required by the government I have no idea what you expect. Should Mozila ignore the laws? 🤔
