### ISSUE TITLE
[Feature:China]Add China mobile homepage and make it default in China builds

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#11411]
### What is the user problem or growth opportunity you want to see solved?
To add mobile homepage and make it default in China builds as we did in Fennec now.
Here is the mobile homepage screenshot from Fennec.

![图片](https://user-images.githubusercontent.com/33616048/84218476-0aa31b80-ab01-11ea-86e9-d17a990f9e62.png)

### How do you know that this problem exists today? Why is this important?
It is common in China to use a homepage like this picture (screenshot from UC mobile browser). Users are used to this kind of homepage to get what they want immediately.

![图片](https://user-images.githubusercontent.com/33616048/84218319-c31c8f80-ab00-11ea-8f03-5c4af2e7df58.png)

### Who will benefit from it?
Most Chinese users who are used to the homepages containing mobile web portals and contents.

**Comment by pthfdr-42** [comment]
I strongly object this misfeature.
As a Chinese, these advert-and-misinformation-ridden "providers" should never be included in a web browser.
