### ISSUE TITLE
FNX-4823 ⁃ Pages opened from external apps, then dismissed (by hitting back) incorrectly adds the page to session

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1141]
## Steps to reproduce
1. Set Fenix as default browser (likely not required, but makes things easier)
1. Open a page from an external app like Signal 
1. Tap Android "back" navigation
1. Open Fenix

### Expected behavior
The link opened in step 2 in STR is not present in the session.

### Actual behavior
The page opened in step 2 in STR is present in the session.

Fennec does the right thing here - navigating back to Fennec does not show the tab if it was dismissed using the Android back button. 

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1912 (Build #10811220 :lizard: 67.0a1-20190312095443)

**Comment by kbrosnan** [comment]
Sessions has been removed from the product. Created #2110 to deal with this in tabs.
