### ISSUE TITLE
FNX2-13457 ⁃ [Bug] VideoPlayer Controls obscure the content

### ISSUE THREAD

**Issue by Diseaesed** [mozilla-mobile/fenix#11416]
## Steps to reproduce
1.Open any video serving site (eg: YouTube) and play a video.
2.Switch to Fullscreen video mode in Landscape.
3.Interact with the video to bring up the controls(pause,play,scrub bar,etc)

### Expected behavior
The controls show up on a transparent or translucent overlay. The video is visible in the background.

### Actual behavior
The controls show up on a solid (opaque ) black background. They completely hide the playback content.

### Device information
* Android device: Asus Zenfone Max Pro M1 ( X00T ), Samsung M30 
* Fenix version: Currently Nightly 200609 (the bug started appear in the end of the last month)

**Comment by hakkikaancaliskan** [comment]
https://github.com/webcompat/web-bugs/issues/53798

**Comment by Diseaesed** [comment]
> Just to confirm. You need to restart fenix after toggle.
Nice. Works fine now. But doesn't it come at the cost of inability to use the GPU to render the page?

**Comment by hakkikaancaliskan** [comment]
> > Just to confirm. You need to restart fenix after toggle
> 
> Nice. Works fine now. But doesn't it come at the cost of inability to use the GPU to render the page?

Yes but of course this is a "bug". Looks like go to full screen video change in web render broke media controls.

**Comment by hakkikaancaliskan** [comment]
@Diseaesed Can you re-check with latest weekly?
Because it's working now with webrender enabled.

**Comment by hakkikaancaliskan** [comment]
@ekager this was fixed a month ago

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 7/21 with Google Pixel 4 XL (11).
