### ISSUE TITLE
FNX-12362 ⁃ Tab Tray A11y - Tapping new tab button should focus on address bar on Home Screen

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#11428]

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly 200618 from 6/18`** and **`Beta 5.2.0-beta.2 from 6/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200618-111342](https://user-images.githubusercontent.com/51314259/84996033-69960f80-b155-11ea-902a-868e8e830851.gif)
