### ISSUE TITLE
[Bug] When you enter bookmark edit mode, keyboard should be visible, text cursor should be after the text

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#11425]
## Steps to reproduce
1. Create a bookmark.
1. Go to Bookmarks and tap the Edit button.
1. In edit mode, verify the bookmark name text field
    1. Expected behavior
The keyboard is shown automatically, the text cursor is set at the end of the name string, so you can add at the end/erase with ease.
    1. Actual behavior
Keyboard hidden, the text cursor is at the beginning of the text field.
    1. Device information

* Android device: Nexus 9 (Android 7.1.1)
* Fenix version: Nightly 6/10, Beta 5.2.0

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200831`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200831-103124](https://user-images.githubusercontent.com/51314259/91694629-8f885900-eb75-11ea-8ba9-6761db212171.gif)
