### ISSUE TITLE
FNX2-13459 ⁃ [Bug] Tabs Tray: Missing thumbnail content after adding a page to homescreen

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#11421]
* [x] GV https://bugzilla.mozilla.org/show_bug.cgi?id=1641064
* [x] GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1647797 (currently slated for GV 81, listed as P1 though)

## Steps to reproduce
1. Open app and search after twitter.com .
1. Wait for the site to load and for "Add to home screen" dialog box to be displayed.
1. Tap on the "Add to home screen" button.
1. Tap on tabs tray icon.
    1. Expected behavior
The thumbnail displays content.
    1. Actual behavior
The thumbnail does not displays content.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8), Google Pixel 3 XL (Android 9)
* Fenix version: Beta 5.2.0-beta.1 and Nightly 200610

Note;

* The same outcome is present when "Add to homescreen" option is used.
* The thumbnail is not updated when a refresh of the page is made and neither after closing and reopening browser.

**GIF- Samsung Galaxy S9 (Android 8)**
![20200610-155218](https://user-images.githubusercontent.com/49859863/84270519-78683b00-ab33-11ea-9f03-0e8671e5e1cd.gif)

**Comment by jonalmeida** [comment]
Should be fixed when https://github.com/mozilla-mobile/android-components/issues/6905 lands.

**Comment by boek** [comment]
@jonalmeida is this still something that we're planning on landing this week?

**Comment by jonalmeida** [comment]
@gabrielluong is working on this but we need GV help to get past this first: https://github.com/mozilla-mobile/android-components/issues/7413

**Comment by data-sync-user** [comment]
➤ Gabriel Luong commented:

🚩 Flag added 

This is blocked on https://github.com/mozilla-mobile/android-components/issues/7413 ( https://github.com/mozilla-mobile/android-components/issues/7413 ), which is also waiting on GV for https://bugzilla.mozilla.org/show_bug.cgi?id=1647797 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1647797 ) from GV which is currently set for geckoview:m81

**Comment by Diana-Rus** [comment]
Hi, verified as fixed on Nightly 8/26 with:
- Google Pixel 3XL (Android 9)
- Samsung Galaxy S9 (Android 8)
- Sony Xperia Z5 (Android 7)

**Verified with pwa's:** 
- twitter.com
- pinterest.com
- instagram.com
- digikala.com
- Housing.com
- flipboard.com
- makemytrip.com
- yummly.com

**Verified with domains that are added through "Add to homescreen" option:**
- triadvisor.com
- https://www.lancome-usa.com/
- amazon.com
- getpocket.com
- wikipedia.org

<details closed><summary>GIF</summary>

![20200826-113355](https://user-images.githubusercontent.com/49859863/91280866-10b7a880-e790-11ea-871a-b2003f8995ca.gif)
</details>
