### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11427]
Notifying teams:

 - [ ] Send an email to internal teams
 - [ ] Leave a note on forks that we know of

Changes that need to land:

 - [ ] https://github.com/mozilla-mobile/fenix/pull/20457

Manual steps:

 - [ ] Rename the branch on GitHub (@st3fan)
 - [ ] Make necesary changes in our build infrastructure (@bhearsum)
     - https://phabricator.services.mozilla.com/D120966
     - https://github.com/mozilla/treeherder/pull/7224

Verification:

 - [ ] Make sure Nightly builds work
 - [ ] Make sure we pick up string changes
 - [ ] Make sure we pick up new A-C builds
 - [ ] Make sure Pull Requests build/test on TaskCluster
 - [ ] Make sure merges to main build succesfully
 - [ ] Make sure the performance tooling works

**Comment by MasterShifu2002** [comment]
I guess my students will have to call me Main now? 😒

What if I want to apprentice to a skilled craftsman? What would I call him?

Maybe, just maybe, the word isn't the problem, and changing the trunk name is just something you want to do to make yourself feel better for things you are not guilty of.

**Comment by ekager** [comment]
The "master" reference on git can be traced back etymologically to a master/slave reference https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html

We will also be making sure we stop using "blacklist/whitelist". Words matter.

Not sure why you needed to make a GitHub account just to comment on this issue that seemingly does not impact you in the slightest.

**Comment by JohanLorenzo** [comment]
> The "master" reference on git can be traced back etymologically to a master/slave reference https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html

TIL! 

There is some work needed for Releng, but I don't think this has a high complexity. Here's what has to be done:

* The [hook](https://firefox-ci-tc.services.mozilla.com/hooks/project-releng/cron-task-mozilla-mobile-fenix) in charge of watching to [.cron.yml](https://github.com/mozilla-mobile/fenix/blob/6b4c46fdfb9105258d513b7b03465d472c06de60/.cron.yml#L1) has to watch another branch than `master`. This can be done by [making this logic smarter](https://hg.mozilla.org/ci/ci-admin/file/e10374358f8e60bea83b27e7e1685cc08a6153db/src/ciadmin/generate/cron_tasks.py#l74).
 * Then we have to handle what we call "action tasks". These are the tasks that enable reruns and retriggers, for instance. As of now, we monitor the `master` branch. We need to make [this piece smarter too](https://hg.mozilla.org/ci/ci-admin/file/e10374358f8e60bea83b27e7e1685cc08a6153db/src/ciadmin/generate/tcyml.py#l31).
* Then, we need to rename [master-specific scopes](https://hg.mozilla.org/ci/ci-configuration/file/12353c59f69be6f7924adb69bb4e7c004e4edf07/grants.yml#l1024) to refer to `main` instead. That said, that shouldn't be necessary once [bug 1631839](https://bugzilla.mozilla.org/show_bug.cgi?id=1631839) is done. I sent an email out about a month ago and sent a reminder earlier today. If I don't hear any concerns, I'll handle it by the end of this month.

Apart from that, I don't see anything else. @tomprince, do you see anything I might have missed?

**Comment by pocmo** [comment]
From the Focus renaming: We also need to make changes in the `android-l10n(-tooling)` repos to import/export strings from/to `main`

**Comment by jhugman** [comment]
This issue is one year old. Is there any progress we can report publicly? @st3fan @pocmo @mhoye
