### ISSUE TITLE
FNX-12373 ⁃ [Bug] Gecko unexpectedly appears to reload itself after crashes

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11439]
## Steps to reproduce
* Add code to force a crash (I added `throw IllegalStateException()` to `dispatchTouchEvent`)
* Start the app, force the crash

### Expected behavior
Gecko dies when the process dies

### Actual behavior
Gecko appears to restart itself, based on the logs ([full logs](https://github.com/mozilla-mobile/fenix/files/4760340/crash.log)):

```
06-10 10:27:01.886 E/GeckoLibLoad( 6390): Load sqlite start
06-10 10:27:01.887 E/GeckoLibLoad( 6390): Load sqlite done
06-10 10:27:01.888 E/GeckoLibLoad( 6390): Load nss start
06-10 10:27:01.888 E/GeckoLibLoad( 6390): Load nss done
06-10 10:27:01.913 E/GeckoLibLoad( 6390): Loaded libs in 24.797295ms total, 6ms(30ms) user, 9ms(13ms) system, 7(7) faults
06-10 10:27:05.094 E/MessageQueue-JNI( 6390): java.lang.IllegalStateException: lol
06-10 10:27:05.096 E/AndroidRuntime( 6390): java.lang.IllegalStateException: lol
06-10 10:27:05.099 I/mozac/CrashReporter( 6390): Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: lol, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Jun 10 10:27:02 PDT 2020)], uuid=cd5deec6-6d15-4212-b9eb-3ab22a58f7e9)
06-10 10:27:07.558 E/GeckoLibLoad( 6601): Load sqlite start
06-10 10:27:07.560 E/GeckoLibLoad( 6601): Load sqlite done
06-10 10:27:07.560 E/GeckoLibLoad( 6601): Load nss start
06-10 10:27:07.560 E/GeckoLibLoad( 6601): Load nss done
06-10 10:27:07.590 E/GeckoLibLoad( 6601): Loaded libs in 30.465107ms total, 10ms(53ms) user, 6ms(10ms) system, 5(5) faults
```

This could be problematic because it can:

1. cause crash loops (https://github.com/mozilla-mobile/fenix/issues/7376 ?)
1. unnecessarily use device resources

This may be intended behavior though (perhaps we start gecko when we restart the process to use the crash reporter? I assume my debug build shouldn't have the crash reporter enabled though...).

### Device information
* Android device: P2
* Fenix version: master 32bfba5b

- - -
@snorp Is this intended behavior?

**Comment by rocketsroger** [comment]
Issue should be fixed on nightly with A-C `47.0.20200618130101`.  Please verify, thanks

**Comment by AndiAJ** [comment]
Hi, I've just check this matter on the latest **`Nightly Build #200619 from 6/19`** using a Google Pixel 3a (Android 10)

Force crashed Fenix using **`about:crashparent`**
After checking the logs:
✔️ Gecko doesn't seem to reload itself  - NO **`GeckoLibLoad`** displayed in the logs
✔️ The Crash reporter service doesn't seem to be starting Gecko - NO **`GeckoThread: State changed to LAUNCHED`** displayed in the logs

[Logcat](https://github.com/mozilla-mobile/fenix/files/4803414/GVRst.txt)

► Video
![20200619-111900](https://user-images.githubusercontent.com/51314259/85114087-08d40900-b221-11ea-801d-163b0f97abea.gif)

@mcomella & @snorp  - Please review and share your thoughts. ☺️ 

I'll remove the QA needed label until further notice.

**Comment by mcomella** [comment]
I followed the STR in my original comment and can no longer reproduce. This looks good to me. @rocketsroger @AndiAJ Does that mean we should close this bug?
