### ISSUE TITLE
[Bug] Can't download file on postback.

### ISSUE THREAD

**Issue by rafaga12** [mozilla-mobile/fenix#11436]
## Steps to reproduce
1.- Go to this address:
https://dbxtra.net/dbxtra-sample-rws/Report_View.aspx?Id=1357

2.- Verify that the file format is set to PDF (that's the default).

3.- Click in the download button (button at the right of the file format).

### Expected behavior
A PDF file is downloaded.

### Actual behavior
It downloads the HTML code of the page with the name of the PDF file it's supposed to download.

### Device information
* Android device: BlackBerry KeyOne (Android 8.1.0)
* Fenix version: 5.1.1 (Build  #21571852)

### Additional Info
This works as expected on Fennec, as it downloads the actual PDF file.

**Comment by rafaga12** [comment]
I just tested this on:

Fenix version: Nightly 200611 (Build #21630608)

And it doesn't work, it appears to download the file, but when you go to open the file is not an actual PDF file, but the HTML code of the page, in Fennec the downloaded file is an actual PDF file.

**Comment by Amejia481** [comment]
QA team could you please help us to verify is this is still an issue? Thanks in advance.

**Comment by rafaga12** [comment]
I've just tested this and it's working fine. Thanks!

**Comment by ebalazs-sv** [comment]
This issue is not reproducible on the latest Nightly 2/3 with Samsung Galaxy Tab S3 (Android 8).
I will close this issue and remove the qa:needed label.
