### ISSUE TITLE
[Bug] Sometimes tab moves sideways instead of clicking X on tabs tray

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11434]
## Steps to reproduce
* Open tabs tray
* Press X

### Expected behavior
Tab closes. The tabs should be fairly stable towards horizontal gestures

### Actual behavior
With the gestures I do naturally, sometimes (1/6 times?), the tab moves sideways a bit and restores it's position, not closing itself.

(It's hard to reproduce during a screenrecording due to the lowered processing power)

### Device information
* Android device: P2
* Fenix version: Nightly 200610

**Comment by sblatz** [comment]
Is the suggestion here to make the swipe gesture less sensitive? I'm not sure how else to solve this without completely removing the swipe gesture.

**Comment by sblatz** [comment]
Could also be possible that https://github.com/mozilla-mobile/fenix/issues/11324 helps at least visually address this.

**Comment by ekager** [comment]
I think this needs UX feedback to be actionable. It is possible to make the swipe action more/less sensitive but we did this dance on the homescreen going back and forth because it's largely personal preference. Having a 1-1 with eng/UX to test changes out is probably the best way to look into this.

**Comment by sblatz** [comment]
@topotropic, @vesta0 Do you think this is something worth spending some time on right now? Or should we do it at a later date?

**Comment by topotropic** [comment]
> but we did this dance on the homescreen going back and forth because it's largely personal preference

@ekager did we re-use the same values as on home screen for the gesture?

If so and based on your argument above and that it doesn't happen very often (I also couldn't reproduce it) I'd vote for keeping an eye on incoming feedback related to this but don't work on it at this point in time. @vesta0 please chime in if you disagree. Thanks!
