### ISSUE TITLE
[Bug] Remove intermediate state when swiping to close tabs tray

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11433]
## Steps to reproduce
* Open tabs tray
* Make a small, quick gesture to close the tray

### Expected behavior
Tabs tray closes

### Actual behavior
Tabs tray stops in the middle. Video of the behavior: https://drive.google.com/file/d/11uo8HRtzSQ93qwcesv3tjn84VHhl2JNd/view?usp=sharing

### Device information
* Android device: P2
* Fenix version: Nightly 200610

- - -
fwiw, my experience with `BottomSheetBehavior` leads me to believe we have to support all three modes (open, half-open, closed) when using BottomSheetBehavior. If that's true and it's not working for us, we should find an alternative implementation.

**Comment by topotropic** [comment]
Let's close the tab tray on swip down and don't show the half open state. Thanks!
