### ISSUE TITLE
[Bug] Captions/subtitles on YouTube videos missing in fullscreen landscape

### ISSUE THREAD

**Issue by intrnl** [mozilla-mobile/fenix#11432]
## Steps to reproduce
1. Go to any YouTube video with subtitles/captions
1. View it in fullscreen on landscape orientation

I honestly don't know if this is YouTube specific or it applies to all video players. Chrome works, but for me it has a 50/50 chance of messing up the orientation, and not display any subtitles. When it doesn't mess up the orientation, it does show the subtitles in fullscreen mode.

### Expected behavior
Subtitles/captions shows up.

### Actual behavior
Doesn't show at all.

### Device information
* Android device: 10
* Fenix version: Nightly 200610

**Comment by kbrosnan** [comment]
Duplicate #8252
