### ISSUE TITLE
FNX-12372 ⁃ [Bug] Empty space left in tabs tray when swiping to close

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11438]
_This is a break~~out of the second issue originally defined in https://github.com/mozilla~~mobile/fenix/issues/11185. The text of that issue is copied below with irrelevant data crossed out._

## Prerequisites
Open more than 10 websites in different tabs

## Steps to reproduce
1. After opening twitter.com (12th tab)
1. Open the Tabs Tary
1. Tap any other open tab
1. Open the Tabs Tary
1. Tap and open another tab
1. Open the Tabs Tary
1. Swipe delete the first 3 open tabs 

### Expected behavior
~~Steps 4,6: Responsive Tabs Tray, displays properly the open tabs~~
Step 7: The tabs should be deleted

### Actual behavior
~~Steps 4,6: Laggy display of the open tabs ~~
Step 7: Empty space left in the Tabs Tray, 
After a couple of seconds the tabs are displayed again as open and only after a couple of more seconds are properly deleted

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: Nightly Build 200603 from 6/3

### Notes
<details>
    <summary>Web site I've used (dropdown)</summary>

Home - YouTube
https://m.youtube.com/

Vimeo | The high-quality home for video hosting and watching
https://vimeo.com/

Dailymotion - the home for videos that matter
https://www.dailymotion.com/us

SoundCloud - Hear the world’s sounds
https://m.soundcloud.com/

Wikipedia
https://www.wikipedia.org/

Pocket: Explore
https://getpocket.com/explore?src=ff_android&cdn=0

Office 365 Login | Microsoft Office
https://www.office.com/

Microsoft – Pagina de pornire oficială
https://www.microsoft.com/ro-ro/

Internet for people, not profit — Mozilla
https://www.mozilla.org/en-US/exp/

Facebook - Log In or Sign Up
https://m.facebook.com/

Instagram
https://www.instagram.com/

Explore / Twitter
https://mobile.twitter.com/explore

</details>

► Video
![20200603-162214](https://user-images.githubusercontent.com/51314259/83643806-2bc3b380-a5b9-11ea-94ef-505a107672fa.gif)

**Comment by mcomella** [comment]
Maybe dupe https://github.com/mozilla-mobile/fenix/issues/11352: I'll re-evaluate after my tabs tray perf investigations #7512.

**Comment by jonalmeida** [comment]
This was fixed as result of https://github.com/mozilla-mobile/android-components/issues/7313.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly 200618 from 6/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200618-155241](https://user-images.githubusercontent.com/51314259/85023823-e89f3e00-b17d-11ea-9ea2-0a7f9f8b394c.gif)
