### ISSUE TITLE
FNX2-13463 ⁃ [Bug] Undo close tab in tabs tray unexpectedly restores tab to top, offscreen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11431]
## Steps to reproduce
* Open enough tabs so the tabs tray can scroll
* Scroll to the bottom
* Press X to close tab
* Press Undo on snack bar

### Expected behavior
Tab restores in same location it was in before.

### Actual behavior
Tab restores at top, _off-screen_

Video of behavior: https://drive.google.com/file/d/1N2d8tUSJZeOZgMiWR49iYeS9gjapKFro/view?usp=sharing

### Device information
* Android device: P2
* Fenix version: Nightly 200610

**Comment by topotropic** [comment]
> on restore we could scroll to the top of the list because we know that the restored tab will be there. Does that make sense @topotropic ?

yes, thanks! If it's possible to add the tab to the position in the list where it was, that would be even better.

**Comment by yoasif** [comment]
>If it's possible to add the tab to the position in the list where it was, that would be even better.

I think this is what ought to happen. In the situation where the user does:

1. Closes tab
2. scrolls tab list far away from current tab
3. restores tab

We should restore to same position it was prior *and* scroll tab into view.

**Comment by ekager** [comment]
Part 1 of this is done. We now scroll to a restored tab, so let's QA that. 

Opened https://github.com/mozilla-mobile/fenix/issues/12449 for restoring the tab to its previous position

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on **`Firefox Nightly Build 200711 from 7/11`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
