### ISSUE TITLE
FNX-12364 ⁃ [Bug] Difficult to hit X to close last tab on new tabs tray

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11430]
## Steps to reproduce
* Open enough tabs that the tabs tray scrolls
* Scroll to bottom
* Try to close last tab

### Expected behavior
X is easy to hit

### Actual behavior
X is not easy to hit because it's partially covered by the FAB:
![device-2020-06-10-091216](https://user-images.githubusercontent.com/759372/84291896-91a0c580-aafa-11ea-9eab-99c1519b48fd.png)

This presumably breaks accessibility guidelines for hit target size and swiping is probably not a good workaround for folks with motor challenges.

### Device information
* Android device: P2
* Fenix version: Nightly 200610

**Comment by mcarare** [comment]
This is also a problem with closing other tabs, when FAB is on top of close button completely, depending on scroll position.

<img src = https://user-images.githubusercontent.com/48995920/85573072-3b756b80-b63e-11ea-9ddf-6d149cb715a0.png width = 30%>

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**, there's additional space that makes it easier to close the last tab on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video Normal Browsing Tabs
![20200625-115953](https://user-images.githubusercontent.com/51314259/85692412-09b3e180-b6de-11ea-840a-a89198f7a330.gif)

► Video Private Browsing Tabs
![20200625-120800](https://user-images.githubusercontent.com/51314259/85692779-5992a880-b6de-11ea-8fc3-f2b42dfebb5f.gif)
