### ISSUE TITLE
FNX-12376 ⁃ [Telemetry] New tab shortcuts

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#11442]
Follow up for #10374, lets add telemetry probes for the menu items

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly Build 200622 from 6/22`** using a Google Pixel 3a (Android 10)

**• Home screen**
New tab - ❌ 
New Private Tab - ❌  

**• Page view**
✔️ New tab - Ping **01351a07-7c17-4e43-81f2-a800a85eb053**
✔️ New Private Tab - Ping **6a00839b-b3db-489a-8bcc-5dcdb25ed575**
✔️ Close tab - Ping **a22a5225-0ff2-4c70-ba36-ae35aba9cd1c**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4812256/context.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test22060)

@boek - Shouldn't the new tab buttons from the Home screen context menu be also tracked? 

**I'll remove the QA needed label until further notice**

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using a Google Pixel 3a (Android 10)

**• Home fragment** ✔️ 
New tab - Ping 54ef47a8-ce49-4e5a-9d8d-bec125ae4a7c
New Private Tab - Ping 1a4164d3-8035-4cfe-9bd4-2639db69a662

**• Page view Normal Browsing** ✔️ 
New tab - Ping beeb7f81-0fa0-47e5-b924-9c8792da1e41
New Private Tab - Ping 0f320608-4505-42ce-936f-c3767c1d0e55
Close tab - Ping 3d7a207b-96f5-4157-abcf-5e03f7daff18

**• Page view Private Browsing** ✔️ 
New tab - Ping ebe10636-b209-4767-9753-870a8c073a6f
New Private Tab - Ping 2166001a-2e2e-421a-a9e6-943f675c6dbe
Close tab - Ping 24567d0f-0617-4e6e-8075-e2db0367a0b5

[Logcat](https://github.com/mozilla-mobile/fenix/files/4831722/cnt.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test25064)
