### ISSUE TITLE
FNX-4824 ⁃ Android soft buttons invisible due to the colour choice

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#1144]
## Steps to reproduce
Run Fenix.

### Expected behavior
See Android soft buttons.

### Actual behavior
Can't see them.

### Device information
* Android device: HTC One m9
* Fenix version: Latest.

See screenshot: 
![Screenshot](https://user-images.githubusercontent.com/168508/54839902-2fb03200-4ca2-11e9-9311-06915ec6cd85.png)UNITO-UNDERSCORE!20190322-103610!

**Comment by pocmo** [comment]
I have the same issue on a Nexus 5.

**Comment by ehsan** [comment]
I *think* there may be a number on the tab icon which is similarly affected too?  Hard to say.  :-)

**Comment by sv-ohorvath** [comment]
There is a black background now on a Nexus 5 and Honor 8( which had issues before) under the white buttons, but where that background already existed (i.e Huawei P20 lite: see screenshot), buttons are now invisible :)
![Screenshot_20190404-140603](https://user-images.githubusercontent.com/4037709/55559939-e3301200-56f7-11e9-9480-e404a2a73c11.jpg)

**Comment by ekager** [comment]
Ah thanks @sv-ohorvath ! Do you know what API level the P20 is on?

**Comment by sv-ohorvath** [comment]
> Ah thanks @sv-ohorvath ! Do you know what API level the P20 is on?

Android 8.0, API 26

**Comment by ekager** [comment]
Thanks @sv-ohorvath ! 
I added a change that *should* address this, could you recheck those devices next week with the latest master? :)

**Comment by sv-ohorvath** [comment]
It's fixed now on Huawei P20 lite as well. Thanks!
