### ISSUE TITLE
[Bug] (Regression) Blank page redirect

### ISSUE THREAD

**Issue by Augures01** [mozilla-mobile/fenix#11443]
## Steps to reproduce
1. Open https://dtf.ru/sale/146156
1. Click on "Save 70% on Elite Dangerous..." link

### Expected behavior
Site opened
[**Last nightly build without issue: 200414 18:01**](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly.2020.04.14.revision/f6870564732ad0e2cbe459425577486b6af9acf2)

### Actual behavior
Blank page redirect
[**First nightly build with issue: 200415 06:01**](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly.2020.04.15.revision/9a298ea6baf83285bf0fa73a5496cdca882ff6c4)

### Device information
* Android device: 7.0 on Samsung S6 Edge
* Fenix version: All nightlies since 200415 06:01

**Comment by liuche** [comment]
This may be the same issue as ##10838 and the fix for that should come through on Monday. If this is still a problem, please let us know!

**Comment by Augures01** [comment]
> 
> 
> This may be the same issue as ##10838 and the fix for that should come through on Monday. If this is still a problem, please let us know!

Waiting for monday...

![peepoPooPoo](https://cdn.betterttv.net/emote/5c3427a55752683d16e409d1/3x)

**Comment by Augures01** [comment]
@liuche 
So... monday evening
Bug still exists in latest nightly (200629 18:01)

First of all, I don't use "Open in app" feature

I provide additional videos

[Old Fenix version without bug (200414 18:01)](https://www.dropbox.com/s/nz6j4qxb9y7fuqo/Fenix_old.mp4?dl=0)

[Latest Fenix version with bug (200629 18:01)](https://www.dropbox.com/s/qzw6ky6aqagr8pp/Fenix_latest.mp4?dl=0)

**Comment by Augures01** [comment]
Additional info:
All redirects to third-party sites from dtf.ru loads as blank page in new tab. Local dtf.ru to dtf.ru redirects works as expected.

**Comment by siveZ** [comment]
Experiencing this in Firefox for Android v. 79. Makes the browser unusable. Also experiencing the same problem in beta, v. 81. I couldn't reproduce it in Firefox 79 for Windows 10, though

**Comment by Augures01** [comment]
Accidentally noticed today
Fixed since Nightly build 200827 06:01
