### ISSUE TITLE
FNX-12380 ⁃ [Bug] Intl_Locale_LocaleService.GetAppLocalesAsLangTags_lastIsEnUS fails on multilocale builds

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-mobile/fenix#11445]
I'm working on shutting off some unneeded Android builds on autoland to help reduce CI costs. As part of this, I'm moving some test suites from `opt` builds to `shippable` builds. When doing this I discovered this test failure:
```TEST-UNEXPECTED-FAIL | Intl_Locale_LocaleService.GetAppLocalesAsLangTags_lastIsEnUS | Value of: appLocales[len - 1].Equals(lastFallbackLocale)```

It's not clear to me whether this is a real bug or a bug in the test. Full log is on https://treeherder.mozilla.org/#/jobs?repo=try&revision=4aa397de7a9cf2a3e102436f13f501859d8f02f0&selectedTaskRun=O6VsjvrpQ56UMinMKTEFEg-0.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1645045

**Comment by Pike** [comment]
bug 1645045 is closed, I guess this ticket can go, too.
