### ISSUE TITLE
[Meta] Easily access a page from bookmarks and history

### ISSUE THREAD

**Issue by jakefleming156** [mozilla-mobile/fenix#11453]
## User Story
As a user, I want my bookmarks and history conveniently accessible when opening a new tab so I can easily navigate to important or frequently visited web pages.

### Acceptance Criteria
* I can easily open a bookmarks or a page from my history

**Comment by sheikh-azharuddin** [comment]
This option is somewhat present. While searching it automatically takes result from history, bookmarks. However you need to type a keyword. You idea is good they can add 2 buttons history and bookmark in the new tab page beside scan, shortcuts. There is space also left.
![6769](https://user-images.githubusercontent.com/58127841/84340924-60270900-ab91-11ea-82b7-8df8d0789c9f.png)

**Comment by jakefleming156** [comment]
Thank you. That's exactly what I was thinking. There is the space in the
new tab page for easy access to bookmarks and history. And keywords would
still remain a valuable addition too.

**Comment by yoasif** [comment]
@jakefleming156 can you open the product brief doc please?

**Comment by jakefleming156** [comment]
I just changed the link to be viewable. Thanks for letting me know.

**Comment by Cheap-Skate** [comment]
I would really like to be able to see Top Sites when tapping the URL bar, like I can in Fennec. 

It's a constant pain to me. Eg browsing a news site, get lost in the site heirarchy, want to go back to the news site homepage. In Fennex it's easy, I just tap the URL & then the news site's Top Site favicon. In Fenix it's much harder, I usually end up opening a new tab, tap the relevent Top Site, then close the old tab :(

I think your product brief doc covers this issue, :- "As a user, I want my frequently visited sites to be available at the point of making a new search, so I can conveniently and easily navigate to my most used web pages"

But it's not clear that the solution you are sketching out involving extra buttons for History and Bookmarks will give access to Top Sites. Please consider showing Top Sites when tapping the URL bar, like Fennec does! Thanks.

**Comment by ZorroGuevara** [comment]
I agree with @Cheap-Skate it's a regression from Fennec. However, given we still don't have the same tabs as in Fennec, I don't know if this request is possible for now.

**Comment by Matth7878** [comment]
I hope it will show more than just a link to history or favorites. (And without typing anything)

Right now new tab page is useless for me and a pain. It's less annoying (thanks to top sites) but homepage is also somewhat a pain. But it's still not great : I have mainly GitHub sites and all icons are the same and there is barely any text to differentiate them. (I know there is existing issue about that)

In Fennec with homepage showing your top site (not only the one you pinned but also your most frequent sites) and links from your recent history with a tab preview was perfect.
I never had to search or type anything unless I really wanted to search for something on internet.

**Comment by Ansem93** [comment]
I think the best solution would be to have a bookmark bar similar to Samsung browser.
Otherwise I would rather have "shortcuts" showing me my bookmarks + disabling the keyboard. 
This could also be the default behavior:
First tap on address bar: show bookmarks list
Second tap: search/insert url directly

**Comment by ZorroGuevara** [comment]
Is there any progress on that? We've in Beta now, and probably soon in Production. And this is a regression from Legacy Firefox.
I know there are a lot of thing to do, but this is not fully usable as a daily browser for me.

**Comment by rusegithub** [comment]
Yes. Please give us access to bookmarks when we click on the url bar.
