### ISSUE TITLE
FNX2-13472 ⁃ Easy Session Navigation

### ISSUE THREAD

**Issue by jakefleming156** [mozilla-mobile/fenix#11452]
## User Story
As a user, I want an easier way to navigate between pages within a tab so that after navigating through multiple pages I can easily return to any of my previous pages.

### Acceptance Criteria
* Given that I am a user who navigates through multiple pages within a single tab, when I want to return to a previous page that could be between 4 and 20 pages back, I can get there without having to select the back button numerous times and the forward button when I accidentally passed it.

Lots of good feedback here: #1048 

Feature Brief Doc
https://docs.google.com/document/d/1hG61S0L45WqmNKET4ZYwku00Nj1fOxgXSxXVjrmu5Kc/edit?usp=sharing

Feasibility Review Doc
https://docs.google.com/document/d/10xBRkzk2aM2FOuhye_wMgfHiLeC_cYLI3CLEre--urI/edit

**Comment by yoasif** [comment]
@jakefleming156 can you please open access to the Feature Brief Doc?

**Comment by liuche** [comment]
Spike is: Long press back tab history #1048

**Comment by vesta0** [comment]
We will re-introduce the "back" arrow on the toolbar as part of this v1

**Comment by person808** [comment]
There is some additional discussion in https://github.com/mozilla-mobile/fenix/issues/12926

**Comment by brampitoyo** [comment]
I’ve added a secondary research document which looks at how other browsers have implemented their session navigation.

In the short term, we are looking to re-add the back button in the main menu navbar. But in the medium-to-long-term, we could potentially do something more. Let’s think about it a bit.

**Comment by vesta0** [comment]
@brampitoyo thanks for the recommendation. I am marking this as ENG-Ready. Please file a new issue to track any long-term investigation :)

**Comment by brampitoyo** [comment]
I’ve posted a feasibility review document that details the spec for the back button in main menu navbar.

I’m posting the link here, instead of on #12926.

**Comment by person808** [comment]
@vesta0 Just merged the back button as part of #12926. Dont know if we still want to keep this issue open to explore other possibilities in the future?

**Comment by vesta0** [comment]
Thank you @person808 ! I think we can close this issue once it's been QA verified.

**Comment by person808** [comment]
Tab history has been verified in other related issues :)
