### ISSUE TITLE
FNX-4825 ⁃ Fenix icon doesn't show in Google Play Store update

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1145]
## Steps to reproduce
* Perform a nightly update of Fenix

### Actual behavior
* Fenix app is missing from the App Update Window in the Google Play Store

### Device information
* Android device: Pixel 3
* Fenix version: 20190312095433
![Screenshot](https://user-images.githubusercontent.com/2171777/54841642-1f9a5180-4ca6-11e9-86fb-029eb9b2cd59.png)UNITO-UNDERSCORE!20190322-131059!

**Comment by bleonard252** [comment]
When was Fenix added to the store?

**Comment by kbrosnan** [comment]
Invalid. The Icon is white and intentional.
