### ISSUE TITLE
FNX-12385 ⁃ [Bug] Settings: wrong font in Enhanced Tracking Protection details

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#11451]
### Actual behavior
In Settings > Enhanced Tracking Protection, the "Blocked" heading on the details page of the Standard, Strict and Custom mode has the wrong font. The font is in a different style than other headings including the title bar. It becomes evident at the latest when comparing the "e" from "Blocked" and "General".

### Expected behavior
The font should be the same as it is for the other headings of the same kind in the settings.

### Screenshots
* **Comparison**
![Screenshot](https://user-images.githubusercontent.com/61639215/84324669-55607a00-ab79-11ea-9d04-17f3af0d19b2.png)UNITO-UNDERSCORE!20200610-233024!UNITO-UNDERSCORE!Firefox Preview (3)!
![Screenshot](https://user-images.githubusercontent.com/61639215/84324671-55f91080-ab79-11ea-9a7d-ba1e2a0e2e63.png)UNITO-UNDERSCORE!20200610-233026!UNITO-UNDERSCORE!Firefox Preview (3)!
![Screenshot](https://user-images.githubusercontent.com/61639215/84324673-572a3d80-ab79-11ea-86ec-0b5e4e764b7f.png)UNITO-UNDERSCORE!20200610-233030!UNITO-UNDERSCORE!Firefox Preview (3)!
![Screenshot](https://user-images.githubusercontent.com/61639215/84324675-57c2d400-ab79-11ea-8a9d-4d85e0887db1.png)UNITO-UNDERSCORE!20200610-233021!UNITO-UNDERSCORE!Firefox Preview (5)!
![Screenshot](https://user-images.githubusercontent.com/61639215/84324677-58f40100-ab79-11ea-8a78-59b236602aad.png)UNITO-UNDERSCORE!20200610-233021!UNITO-UNDERSCORE!Firefox Preview (6)!
* Enhanced Tracking Protection
![Screenshot](https://user-images.githubusercontent.com/61639215/84323186-9efb9580-ab76-11ea-966e-328fa596e6fe.png)UNITO-UNDERSCORE!20200610-233024!UNITO-UNDERSCORE!Firefox Preview (2)!
![Screenshot](https://user-images.githubusercontent.com/61639215/84323187-a02cc280-ab76-11ea-9242-80c73bc58ea7.png)UNITO-UNDERSCORE!20200610-233026!UNITO-UNDERSCORE!Firefox Preview (2)!
![Screenshot](https://user-images.githubusercontent.com/61639215/84323188-a0c55900-ab76-11ea-91f3-61a437a39330.png)UNITO-UNDERSCORE!20200610-233030!UNITO-UNDERSCORE!Firefox Preview (2)!
* Settings start page
![Screenshot](https://user-images.githubusercontent.com/61639215/84323183-9e62ff00-ab76-11ea-99a9-ac2b210b6192.png)UNITO-UNDERSCORE!20200610-233021!UNITO-UNDERSCORE!Firefox Preview (2)!

### Steps to reproduce
1. Go to Settings > Enhanced Tracking Protection > Info (Standard/Strict/Custom)

### Device information
* Android device: Samsung Galaxy S9+ (SM-G9650/DS)
* Android version: 8.0.0
* Fenix version: 5.1.1

**Comment by AmyYLee** [comment]
This is correct. Please update the "Blocked" headers to Metropolis. Thanks!

**Comment by mcarare** [comment]
This will be tracked in https://github.com/mozilla-mobile/fenix/issues/11835.
