### ISSUE TITLE
[Feature:China]Add tracking about apk source ( from which application store )

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#11458]
### What is the user problem or growth opportunity you want to see solved?
Add a new tracking to get which application store the apk comes from.

### How do you know that this problem exists today? Why is this important?
There are plenty of Android application stores in China and usually we send apks to each of them (at least 10 different application stores). So it is quite useful to track where users' apks come from.

### Who will benefit from it?
This kind of statistics can help us make analysis.

**Comment by kbrosnan** [comment]
Is there a library or service that is used in the China Fennec or is the reporting? Currently Adjust is what is built into the apk is that tool able to meet your needs? 

* https://www.adjust.com/zh/
* https://www.adjust.com/zh/product-updates/simplifying-attribution-for-pre-installed-apps-and-third-party-app-stores/

**Comment by kbrosnan** [comment]
After talking with @st3fan the tooling around [Glean](https://github.com/mozilla/glean/) is better. I have an open question to the Glean team for documentation about what is needed to run your own pipeline for capturing Glean pings.

**Comment by st3fan** [comment]
I think ideally this telemetry goes into the same bucket as regular Firefox? Just like us currently done with Fennec?

What we probably need to add to one of the pings is the "source of install". Right now we assume GPS but we need to introduce a field to identify the specific APK store I think.

**Comment by rxumoz** [comment]
Yes I agree with @st3fan . It will be good enough if we can get this "source of install" statistics from telemetry through sql search.

**Comment by kbrosnan** [comment]
I was unaware that Firefox running in China is able to reliably send data to incoming.telemetry.mozilla.org. I had assumed that Mozilla China had their own copy of the servers to collect telemetry.

**Comment by l-hedgehog** [comment]
This was actually done in #22138 and backported to Fenix 94 in #22371

I've created queries for both [MozillaOnline builds](https://sql.telemetry.mozilla.org/queries/82858) and [CN region](https://sql.telemetry.mozilla.org/queries/82943)
