### ISSUE TITLE
[webcontent] wiki.mozilla.org - Incorrect font style in "Table to contents"

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#11459]
## Site with issue and any steps to reproduce
1. Go to https://wiki.mozilla.org/Platform/GFX/WebRender_Where

### Expected behavior
The toc should have a reasonable size.

### Actual behavior
The toc is being overinflated.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
n/a

### Can you reproduce in Chrome (or other non-Mozilla browser)?

nope

### Device information
* Android device: Android 10 pixel 2
* Fenix version: ? latest fenix nightly preview and 77.

Reported initially on https://github.com/webcompat/web-bugs/issues/53776

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683187

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
