### ISSUE TITLE
[Bug] Searching through voice assistant from the search widget is done through a different search engine than the one set as default

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#11465]
## Steps to reproduce
1. Go to Settings - Search, add a custom search engine, like imdb.com.
1. Set imdb as the default search engine.
1. Browse a page using the new search engine.
1. Delete all the search engines - I remained with DuckDuckGo as default.
1. Add Fenix widget.
1. Tap on the microphone from the search widget.
1. Say a word and observe which search engine performs the search.

### Expected behavior
The search is performed by DuckDuckGo, in this scenario.

### Actual behavior
The search is performed by imdb.

### Device information
* Android devices: Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: 6/11 Nightly build, Beta 5.2.0-beta.1

![](https://user-images.githubusercontent.com/40694158/84369121-106f2e80-abdf-11ea-811e-e9974c5a388c.gif)

**Comment by codrut-topliceanu** [comment]
@kbrosnan I'm still working on the PR for this issue. :D

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue anymore on the latest Nightly build from 9/28, nor on RC 81.1.1, using Samsung Galaxy Tab S9 (Android 10).
I will close this issue.
