### ISSUE TITLE
[Bug] Firefox Preview app disdapears from activities list when in background

### ISSUE THREAD

**Issue by immutable-pro** [mozilla-mobile/fenix#11464]
Hello,

When I'm browsing any website and I change to another application, when I hit the button to display all apps / activities, Firefox Preview isn't there. But when I open it again from the app launcher, it resumes normally. It's the only app showing this behavior and it wasn't happening before. 
I also observed that if you are in the Firefox Preview settings activity, this doesn't happen. 

I'm using OnePlus 7T with the latest stable updates (Android 10) and this build of Firefox Preview:

5.1.1 (Build #21571852)
42.0.1, 5bf46033e
GV: 77.0-20200526221856
AS: 0.58.2

Regards.

**Comment by ekager** [comment]
Hi @immutable-pro are you still seeing this issue?

**Comment by immutable-pro** [comment]
Not anymore. I can't recall what update fixed it. Thank you!
