### ISSUE TITLE
FNX-12410 ⁃ [Bug] When you open links from bookmarks/history, show the tabs tray

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#11468]
## Steps to reproduce
1. Create a few bookmarks and history items.
1. Long tap to select some items.
1. From the multiple selection bar, select to open the items in normal/private tabs.
    1. Expected behavior
You are redirected to the tabs tray, showing the last tabs created.
    1. Actual behavior
You are redirected to an empty homescreen, no indication that tabs are there, besides the tabs counter
    1. Device information

* Android device: any
* Fenix version: Nightly 6/11

**Comment by AndiAJ** [comment]
Hi, noticed this is the "**Ready for QA**" column.
I'll re-check after @darkwing 's PR will be merged ☺️
