### ISSUE TITLE
[Bug] User not visible logged out if "Quit - Cookies" is performed

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#11467]
## Steps to reproduce
1. Go to Twitter and log in.
1. Go to settings-Delete browsing data on Quit - select Cookies.
1. Back on the page from the menu, select Quit.
1. Reopen Fenix and check the user state.

### Expected behavior
The user is logged out.

### Actual behavior
The user picture is displayed, reload is required in order to be logged out.
A message is displayed on Twitter: "Try again. Something went wrong".

### Note
Not reproducible on Fennec with Twitter, the user is logged out and the login page is displayed; but reproducible with Google account (reload is required). 

### Device information
* Android device: Google Pixel (Android 11 beta), Xiaomi Mi Pad 2 (Android 5.1).
* Fenix version: Nightly 6/11, Beta 5.2-beta.1.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1990)

**Comment by SoftVision-LorandJanos** [comment]
Still reproducible on the latest Nightly (2021-12-03).
Device used: Xiaomi Mi11 Lite (Android 11).
