### ISSUE TITLE
FNX2-13483 ⁃ [Bug] Discrepancy in behavior between top and bottom toolbar on feedbin.com

### ISSUE THREAD

**Issue by serovar** [mozilla-mobile/fenix#11471]
## Steps to reproduce
Go to feedbin.com and login with your account, then scroll down through your feeds.

### Expected behavior
When you scroll down, the bottom and the top toolbar have the same behavior (they are dynamic and autohide or they are pinned and do not move).

### Actual behavior
When you scroll down, the bottom toolbar does is pinned and the top toolbar is dynamic.

![feedbin static navbar](https://user-images.githubusercontent.com/6732420/84394434-399eb780-abfd-11ea-935b-424ed51be0a2.gif)

![feedbin top navbar](https://user-images.githubusercontent.com/6732420/84413371-d0c13a80-ac10-11ea-941d-48a8a4d22d8a.gif)

### Device information
* Android device: Pixel 2 XL, Android 10
* Fenix version: Nightly 200611 06:01, Build #2015745587

**Comment by SS1113** [comment]
If I'm understanding correctly, I think this is intended behaviour for some sites according this comment: https://github.com/mozilla-mobile/fenix/issues/10073.

**Comment by serovar** [comment]
Maybe, but in that issue the first post says

> ### Expected behavior
> 
> Shouldn't trigger bottom toolbar

But in a site like feedbin the expected behavior is exactly the opposite (as with every other site that uses a bottom bar, like Twitter to say one), and it handled perfectly fine by every chromium-based browsers without needing to pin the browser toolbar.

**Comment by SS1113** [comment]
@serovar See the comment not the post.
Bottom toolbar also doesn't hide when browsing through GitHub projects but does scroll in other places such as - Issues, Fenix [home page](https://github.com/mozilla-mobile/fenix). 


Don't know if this will remain the case or change in future though.

**Comment by serovar** [comment]
I saw the comment, but my point is that this behavior is not expected on some kind of sites (like on feedbin), and it is now "intended behavior" only because it's a way to solve issues on other sites where instead the autohiding is effectively an unexpected behavior. Moreover, there is a discrepancy between the bottom tab and the top bar behaviors, where the first one is pinned and the second one is dynamic, but I've seen that because of some issues with the top dynamic bar [this behavior is in discussion for it too](https://github.com/mozilla-mobile/fenix/issues/11389#issuecomment-642285691).

I'll rename this issue to underline this discrepancy. I think the issue could be closed if they decide to pin the top bar too on this kind of sites, but that should remain open if the decide to make to top bar dynamic, since it will introduce a different logic in behavior for certain websites (like feedbin).

**Comment by crisalis2** [comment]
The bottom bar not auto-hiding happens in quite a lot of sites for me on the latest Google Play Beta. For example, Twitter and even right now here on Github.

**Comment by liuche** [comment]
I'm going to dupe this to #11389.

To address your comments: the reason the bottom bar isn't hiding is a result of GeckoView not handling embedded content scroll properly - see the linked bug. It's not because the bottom bar is pinned, that is the bug. You can follow along in the Bugzilla bug linked.
