### ISSUE TITLE
[Bug] Weird transition is displayed in settings when opening certain menus

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#11474]
## Steps to reproduce
1. Launch Fenix and reach the settings.
1. Tap on the Language option.
    1. Expected behavior
The "Language" top bar text is displayed only after the transition is done.
    1. Actual behavior
The "Language" top bar text is displayed before the transition is done in settings
    1. Device information

* Android device: Google Pixel 4 XL (10).
* Fenix version: Latest Nightly 6/11 and Beta 5.2.0-beta.

### Note
This issue occurs for the following menus: Language, Delete browsing data, Data collection.
![20200611-182833](https://user-images.githubusercontent.com/42831109/84406422-2ba76180-ac12-11ea-9465-000db6e32d9e.gif)

**Comment by mcarare** [comment]
@sblatz Do you think this is related to animation work you have done? If not, we will further investigate this.

**Comment by sblatz** [comment]
This is almost certainly due to animation work :) This just looks weird because we're not displaying the "enter" animation. It's a quick fix. I'll put up a PR shortly.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on Samsung Galaxy Note 8 (Android 9) on the latest Nightly build from 7/16.

**Comment by hakkikaancaliskan** [comment]
Not reproducible on Android 11, Xperia XZ1, 12/24 Nightly

**Comment by lobontiumira** [comment]
This issue still reproduces on the 6/24 Nightly build with Samsung Galaxy Note 8 (Android 9).
