### ISSUE TITLE
[Translation Fix] Error Report Translation is Misleading in German

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#11473]
## Steps to reproduce
I don't even know how or why the error appears but sometimes something happens in the background and a little Android-notification appears on the top of the screen, saying (translating it myself from German to English) something like "We are sorry, there was an error".
Within this notification, there's a little button imbedded, and it's this button, that was translated misleadingly. It says "Bericht" (=Report)

HOWEVER! While in English this might be fine, in German it heavily implies a noun like "write-up" or  a meaning like "summarize" or "show the report", instead of the action "send report".

### Expected behavior
* I suggest changing "Bericht" (report) to either "Bericht senden" (send report) or "Berichten" (report, the verb) to avoid users feeling tricked into sending the report they actually wanted to look at.
* If the English popup only shows "Report", I, again, suggest changing it to something not misinterpret-able like "Send Report".
* Checking the translation for all available Languages might be a good idea in general.

### Device information
* Android device: Samsung Galaxy S9
* Fenix version: 5.1.1

Great work, Fenix Team!

**Comment by cadeyrn** [comment]
I submitted a suggestion to Pontoon (the translation tool used for Fenix).

**Comment by Glitchy-Tozier** [comment]
Thank you!

**Comment by cadeyrn** [comment]
The string was changed, it's "Melden" now. This issue can be closed.

**Comment by Glitchy-Tozier** [comment]
NIce, I forgot the option of "Melden"!
Is it my job to close the issue or does some Firefox-Person do that?

**Comment by cadeyrn** [comment]
You can close the issue. I don't think a translation change needs the whole QA verification process. And I already tested that the new translation is there.
