### ISSUE TITLE
FNX-12423 ⁃ [Telemetry] Open tabs

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11479]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to know how often our users keep a large number of open tabs so we can prioritize features that helps them organize their open tabs. 

## What questions will you answer with this data?
-Breakdown of % of users against # of open tabs
-Breakdown of how long the same tabs remain open 
-What % of users interact with their existing open tabs on a daily basis?

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by sblatz** [comment]
### Notes
- Add to metrics ping: number_of_tabs_open

-Breakdown of how long the same tabs remain open will **NOT be added**. @vesta0 is that okay? It's a very difficult answer to question.

**Comment by vesta0** [comment]
That's totally fine - it was worth asking :) Thank you!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly Build 200629 from 6/29`** and **`Fenix 78.0.1-beta.1 from 6/27`** using a Google Pixel 3a (Android 10)

#### ✔️ Nightly Build 200629 from 6/29
5 Open tabs - Ping aefd3c00-6c25-4176-9b14-c61b48e88c60
**`"metrics.tabs_open_count": 5`**

10 Open tabs -  Ping a9ed7765-2ded-4138-889e-646762ac6696
**`"metrics.tabs_open_count": 10`**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4845921/ngt.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t2906000)

#### ✔️ Fenix 78.0.1-beta.1 from 6/27
15 Open tabs - Ping af1615ed-7abf-47d0-b624-aad2b73429fb
**`"metrics.tabs_open_count": 15`**

30 Open tabs - Ping ab213036-aeae-4f92-b5ef-65382a8c2a8a
**`"metrics.tabs_open_count": 30`**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4845930/bta.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-testMig29060)
