### ISSUE TITLE
[webcontent] youtube playback issue

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11477]
## Site with issue and any steps to reproduce
After playing any video when trying to play the video again using YouTube refresh icon getting an error as shown in screenshot

### Expected behavior
Video should play again properly

### Actual behavior
Video not playing again and showing an error 

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Same error as fenix.attaching screenshot

### Can you reproduce in Chrome (or other non-Mozilla browser)?
Working fine in chrome

Working fine

### Device information
* Android device: ?A10
* Fenix version: ? Latest build.

![Screenshot](https://user-images.githubusercontent.com/58127841/84422431-863dbf00-ac0c-11ea-8cba-aa55486d5ae8.jpg)UNITO-UNDERSCORE!20200611-231609!
![Screenshot](https://user-images.githubusercontent.com/58127841/84422444-8b027300-ac0c-11ea-9ba5-9f09db766ff8.jpg)UNITO-UNDERSCORE!20200611-232217!

**Comment by sv-ohorvath** [comment]
I also got this error on an Android 5.1 emulator (x86 build) on both Nightly and 80.0.1 RC. Vimeo videos don't play either.
Other devices didn't have the issue, like Pixel 2 (Android 10) emulator and physical device, OnePlus A3 (Android 6), Samsung Galaxy Tab S6 (Android 9),

**Comment by ekager** [comment]
Let's retest and file a Gecko bug if needed

**Comment by AndiAJ** [comment]
Hi, **verified as fixe**d on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201218-135239](https://user-images.githubusercontent.com/51314259/102612064-c0969480-4138-11eb-89ea-85470946265a.gif)
