### ISSUE TITLE
FNX-12421 ⁃ [Telemetry] Toolbar position

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11478]
## Description & Product Manager / Data Scientist User Story
As a product manager, I'd like to know the user preference ragarding the position of the navigation toolbar so we can use this information as we re-assess our product defaults. 

## What questions will you answer with this data?
-What is the breakdown of users with a bottom or top toolbar for a specific duration (e.g. last 30 days)? (state not event)

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by sblatz** [comment]
We added this recently in the metrics ping. Should have it landing in nightly shortly 😄 

https://github.com/mozilla-mobile/fenix/issues/11118
