### ISSUE TITLE
Sentry is full of RustLogs, rather than crashes

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11482]
No issue for this but https://github.com/mozilla-mobile/fenix/commit/8769d98e712a4f34ef9d62409e7b04fab81421af added rust logs, and now the first couple pages of errors in Sentry is full of logs. Finding crashes is really annoying now.

![](https://user-images.githubusercontent.com/1082253/84425815-00ebe780-abd7-11ea-99a7-66ec6ff0efa9.png)

**Comment by liuche** [comment]
cc @grigoryk how useful is this logging for you? It's making it a huge pain to track top crashers before release. I remember @rocketsroger made some changes so that logging errors wouldn't show up in Sentry because they were so high volume, can you chat with him to see what he ended up doing?

**Comment by rocketsroger** [comment]
> @rocketsroger made some changes so that logging errors wouldn't show up in Sentry because they were so high volume, can you chat with him to see what he ended up doing?

Unfortunately my change was for Socorro, not for Sentry.  Currently:
1. Native crashes will not be submitted to Sentry.
2. Caught info crashes (which these Rust reports are) are not sent to Socorro.

@grigoryk did make a change yesterday https://github.com/mozilla-mobile/android-components/pull/7328 related to this.

**Comment by liuche** [comment]
Okay, so where do we want to be able to see Rust reports? Is there a better place than in Sentry? If not, we can filter in Sentry, but I want to check if there's a better place to view these.

**Comment by rocketsroger** [comment]
> Okay, so where do we want to be able to see Rust reports? Is there a better place than in Sentry? If not, we can filter in Sentry, but I want to check if there's a better place to view these.

My vote is once we eliminate Rust issues that we've already seen in Sentry, we shouldn't report anymore Rust caught exceptions.

**Comment by grigoryk** [comment]
@liuche hopefully with the network issues filtered out, the volume should be more manageable.

The goal here is to only have actionable issues show up in Sentry.

**Comment by grigoryk** [comment]
Regarding not displaying Rust issues at all - we can do that as a short-term solution, if the volume is still too high and we're not adjusting error reporting quickly enough to be limited to just actionable issues/actual problems we're tracking.

Generally, it should be enabled, and shouldn't overwhelm us. It's a good way to catch problems happening at that layer of our stack; it's been useful in catching problems for the application-services team on iOS, for example.

So next steps are:
- if the volume is too high still, even with network stuff filtered out (in https://github.com/mozilla-mobile/android-components/pull/7328), disable reporting
- make changes to error reporting (fix problems, remove known-issues/non-issues from the error logs)
- re-enable error reporting at a later point (say, next time we upgrade a-s version), see how things are then
- rinse and repeat if necessary.
