### ISSUE TITLE
[Bug] Fenix does not launch with Android Studio 4.0 - Activity class does not exist

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11484]
### Steps to reproduce
1. install Android Studio 4.0
1. try to create a Fenix build

### Expected behavior
No error.

### Actual behavior
```
Error while executing: am start -n "org.mozilla.fenix.debug/org.mozilla.fenix.App" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.mozilla.fenix.debug/org.mozilla.fenix.App }
Error type 3
Error: Activity class {org.mozilla.fenix.debug/org.mozilla.fenix.App} does not exist.

Error while Launching activity
```

I tried it several times with Android Studio 3.6.3 and with Android Studio 4.0. It always failed with the same error in Android Studio 4.0 and always worked in Android Studio 3.6.3.

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision cd26ba9a9c34f9ac1ffb1a10d364f05ca23228b9

**Comment by mcarare** [comment]
@cadeyrn Temporary fix: set `HomeActivity` as specified activity in launch options (run/debug config).

**Comment by jonalmeida** [comment]
I had filed https://issuetracker.google.com/issues/153413510 for this on the google tracker, but it was closed for a duplicate that is not publicly visible. :\

**Comment by ekager** [comment]
And to be clear, it does build. It just doesn't launch.

**Comment by cadeyrn** [comment]
Since the google issue is not public and therefore the status is not known but there is an easy workaround maybe it's enough to add a short notice to the build instructions in the README to close this issue? What do you think?

**Comment by jonalmeida** [comment]
> Since the google issue is not public and therefore the status is not known but there is an easy workaround maybe it's enough to add a short notice to the build instructions in the README to close this issue? What do you think?

The issue is already fixed in newer versions of Android Studio. It might be in 4.1 already.

**Comment by GreenRecycleBin** [comment]
> The issue is already fixed in newer versions of Android Studio. It might be in 4.1 already.

I'm running Android Studio v4.1 and the issue is indeed fixed. We could close this issue.

**Comment by cadeyrn** [comment]
Closing based on the previous comments.
