### ISSUE TITLE
[Bug] Intermittent handleToolbarCloseTabPress io.mockk.MockKException: no answer found for: SessionManager(child^3 of static ContextKt#1655#1661#1662).getSessions()

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#11488]
Observed 4x in CI.

@NotWoods said: `I can't replicate these failures on my local machine. I'd expect it to be caused by the new version of MockK.`
https://github.com/mozilla-mobile/fenix/pull/11020

Log: https://treeherder.mozilla.org/logviewer.html#?job_id=305887108&repo=fenix

[task 2020-06-11T02:53:35.423Z]   TEST: handleToolbarCloseTabPress
[task 2020-06-11T02:53:35.423Z]     [Robolectric] org.mozilla.fenix.components.toolbar.DefaultBrowserToolbarControllerTest.handleToolbarCloseTabPress: sdk=28; resources=LEGACY
[task 2020-06-11T02:53:35.423Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-06-11T02:53:35.423Z]     I/AssetManager: no overlays.list file found
[task 2020-06-11T02:53:35.423Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-06-11T02:53:35.423Z]     D [FenixApplication] Initializing Glean (uploadEnabled=true, isFennec=false)
[task 2020-06-11T02:53:35.423Z]     E/glean/Glean: Glean should not be initialized multiple times
[task 2020-06-11T02:53:35.623Z]   FAILURE
[task 2020-06-11T02:53:35.723Z] 
[task 2020-06-11T02:53:35.723Z] io.mockk.MockKException: no answer found for: SessionManager(child^3 of static ContextKt#1655#1661#1662).getSessions()
[task 2020-06-11T02:53:35.724Z] 	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:90)
[task 2020-06-11T02:53:35.724Z] 	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
[task 2020-06-11T02:53:35.724Z] 	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
[task 2020-06-11T02:53:35.724Z] 	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
[task 2020-06-11T02:53:35.724Z] 	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
[task 2020-06-11T02:53:35.724Z] 	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
[task 2020-06-11T02:53:35.724Z] 	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
[task 2020-06-11T02:53:35.724Z] 	at mozilla.components.browser.session.SessionManager.getSessions(SessionManager.kt:178)
[task 2020-06-11T02:53:35.724Z] 	at org.mozilla.fenix.ext.SessionManagerKt.sessionsOfType(SessionManager.kt:13)
[task 2020-06-11T02:53:35.724Z] 	at org.mozilla.fenix.components.toolbar.DefaultBrowserToolbarController.handleTabCounterItemInteraction(BrowserToolbarController.kt:147)
[task 2020-06-11T02:53:35.724Z] 	at org.mozilla.fenix.components.toolbar.DefaultBrowserToolbarControllerTest.handleToolbarCloseTabPress(DefaultBrowserToolbarControllerTest.kt:578)
[task 2020-06-11T02:53:35.724Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-06-11T02:53:35.724Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-06-11T02:53:35.724Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-06-11T02:53:35.724Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-06-11T02:53:35.724Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-06-11T02:53:35.724Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-06-11T02:53:35.724Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-06-11T02:53:35.724Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-06-11T02:53:35.724Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-06-11T02:53:35.724Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2020-06-11T02:53:35.724Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
[task 2020-06-11T02:53:35.724Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
[task 2020-06-11T02:53:35.724Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-06-11T02:53:35.724Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-06-11T02:53:35.724Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-06-11T02:53:35.724Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-06-11T02:53:35.724Z] 	at java.lang.Thread.run(Thread.java:748)

**Comment by NotWoods** [comment]
Should hopefully get fixed by https://github.com/mozilla-mobile/fenix/pull/11489

**Comment by ekager** [comment]
Closing for now since we merged a speculative fix
