### ISSUE TITLE
FNX2-13490 ⁃ [Bug] Edit bookmarks: poor placement of the "Save" icon

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#11490]
## Steps to reproduce
1. Go to 'Bookmarks'
1. Edit an existing bookmark or folder

### Expected behavior
The primary action, saving the changes, should be placed in the most prominent position at the very right of the title bar. When a new folder is created, the check icon is at the very right side, too. So the user expects the icon to be at the same position.

### Actual behavior
There are two icons: save and delete. The delete icon is placed on the more prominent right position and the save icon is to the left of the delete button.

### Screenshots
![](https://user-images.githubusercontent.com/61639215/84446433-c2414600-ac45-11ea-8973-81f9d50482e7.png)
![](https://user-images.githubusercontent.com/61639215/84446429-c1101900-ac45-11ea-8724-44471de5c17e.png)
![](https://user-images.githubusercontent.com/61639215/84446432-c1a8af80-ac45-11ea-8880-fc5abd0efa72.png)

### Device information
* Android device: Samsung Galaxy S9+ (SM-G9650/DS)
* Android version: 8.0.0
* Fenix version: 5.1.1

**Comment by AmyYLee** [comment]
@topotropic for feedback

**Comment by topotropic** [comment]
Sounds good to me, thanks for the feedback.

**Comment by ekager** [comment]
Eng action is to swap the delete and save icons.

**Comment by prabhat3108** [comment]
I would like to work on this

**Comment by prabhat3108** [comment]
I am working on this issue

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200803 (Build #22161810).
### Devices used:
- Huawei MediaPad M3 lite (Android 7)
- OnePlus 6T (Android 9)

**Comment by prabhat3108** [comment]
@data-sync-user can you help me understand why this is issue is reopened.?
