### ISSUE TITLE
FNX-12442 ⁃ [Bug] Pull-to-refresh is possible for Sync Tabs when there is no Sync account

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#11497]
## Steps to reproduce
1. Do NOT have a sync account.
1. Go to the Sync Tabs UI.
1. Pull to refresh

### Expected behaviour
* Nothing should happen.

### Actual behaviour
* The PTR loader can be used and will stay in the loading state

### Device information
* Android device: Android 10, Pixel 4
* Fenix version: Nightly, 10/06/20

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest Firefox Preview Nightly Build #21641512
### Device information
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 lite (Android 7.0)

**Comment by mcarare** [comment]
Closing as per https://github.com/mozilla-mobile/fenix/issues/11497#issuecomment-643302296.
