### ISSUE TITLE
FNX2-13492 ⁃ [Bug] Sign-in CTA for Sync Tabs is missing

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#11498]
## Steps to reproduce
1. Do NOT have a Sync account setup.
1. Open Sync Tabs menu.

### Expected behavior
* The CTA button to direct me to sign-in should be there (as per [these designs](https://app.abstract.com/share/cb14ade9-a5a1-4ca9-8012-4350363cf5b4?collectionId=4d5f57be-0965-4faa-8ed4-8635c1f16660&collectionLayerId=af01e258-4b71-45c0-9c35-b1bb4c0ec2b3&present=true&preview=false&sha=91ef9094d50e98eec299dbf1fb1f2d8783e2898a)).

![](https://user-images.githubusercontent.com/1370580/84453780-b85c1a80-ac26-11ea-9d67-d329100e927f.png)

### Actual behavior
* We show some text "Connect a Sync account".

![](https://user-images.githubusercontent.com/1370580/84453730-9c587900-ac26-11ea-8da2-94a5f872abad.png)

### Device information
* Android device: Android 10, Pixel 4
* Fenix version: Nightly, 10/06/20

**Comment by ekager** [comment]
prelanding strings in https://github.com/mozilla-mobile/fenix/pull/11503

**Comment by liuche** [comment]
Could we get this landed in this sprint so it makes it into the Sept release?

**Comment by ekager** [comment]
There are apparently some issues uncovered in the PR that need investigation: https://github.com/mozilla-mobile/fenix/pull/11634#issuecomment-650107934

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200803 (Build #22161810).
### Devices used:
- Huawei MediaPad M3 lite (Android 7)
- OnePlus 6T (Android 9)
