### ISSUE TITLE
[Bug] Bookmarks: missing context menu button

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#11492]
## Steps to reproduce
1. Go to 'Bookmarks'
1. Mark more than one item
1. Unmark all items one by one
(tap the items one by one to unmark them, don't use back)

### Expected behavior
The context menu icon is hidden when a bookmark or folder is marked. It's supposed to appear again when the item is unmarked.

### Actual behavior
This is only the case if all items.are unmarked at once. Otherwise, the context menu icon stays hidden for all items that were marked except the last item that was unmarked.

### Screenshots
<ol>
<li><b>Go to 'Bookmarks'</b>
<br>![](https://user-images.githubusercontent.com/61639215/84445346-14816780-ac44-11ea-9362-b64e37fe4b7b.png)</li>
<li><b>Mark bookmarks/folders</b>
<br>![](https://user-images.githubusercontent.com/61639215/84445349-177c5800-ac44-11ea-8ee3-d7ccb7544a8a.png)</li>
<li><b>Unmark items</b>
<br>![](https://user-images.githubusercontent.com/61639215/84445354-1ba87580-ac44-11ea-80c1-df74bc39cb57.png)
<br>![](https://user-images.githubusercontent.com/61639215/84445355-1c410c00-ac44-11ea-9e24-bdea3bc981e4.png)</li>
</ol>

### Device information
* Android device: Samsung Galaxy S9+ (SM-G9650/DS)
* Android version: 8.0.0
* Fenix version: 5.1.1

**Comment by ekager** [comment]
I believe this is fixed
