### ISSUE TITLE
FNX-4828 ⁃ [Meta] Basic Settings

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#115]
## What
Settings Page: Allow users to customize and change default settings in Fenix

## Why/User Benefit
As a Fenix user, I want to have a choice to decide how my experience of Fenix meets my needs 

## AC
* User can navigate to a settings page
* User can change default settings to for their browser experience

**Comment by st3fan** [comment]
The Reference Browser has a fairly standard settings view that exposes a few toggles. The only thing that may be reusable is the code that deals with the FxA settings. (Sign In & Showing your current FxA status & What To Sync).

The rest of the settings need to be called out here and implemented as Fenix specific issues.

**Comment by bbinto** [comment]
@mheubusch to be looped in for strings

**Comment by sblatz** [comment]
Some settings we will need:
- Make default browser
- Change default search engine

**Comment by bbinto** [comment]
See further mocks by @brampitoyo here: https://github.com/mozilla-mobile/fenix/issues/187

**Comment by sblatz** [comment]
I will work on breaking this down into some smaller issues, since this whole ticket won't be able to be completed this sprint.

**Comment by sblatz** [comment]
Breakdown:
- [ ] Initial Settings Page: 
- [ ] Account: 
- [ ] Basics: 
- [ ] Advanced: 
- [ ] About:

**Comment by Sdaswani** [comment]
@bbinto moving this to MVP Metas list

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.

https://docs.google.com/spreadsheets/d/11UL5XeFNvYC-KslMSReYZa9mCZvq_LSZ1pF1SzdjQoM/edit?usp=sharing

**Comment by vesta0** [comment]
The work for MVP is completed.
