### ISSUE TITLE
FNX-12445 ⁃ [Bug] Edit bookmarks: Select folder title bar glitch

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#11500]
## Steps to reproduce
1. Edit a bookmark or folder/create a folder
1. Select the parent folder
(tap the current folder once to go to the folder structure)

### Actual behavior
For a tiny moment the title bar says "Select folder", then the title changes to "Bookmarks"

### Expected behavior
The goal is to select a parent folder. Accordingly, only folders are displayed and the bookmarks are hidden in the folder structure. The title should be a name for the content of the current page, so "Bookmarks" is the exact opposite of the truth. Also, it's not necessary to repeat "Bookmarks" in the title bar, as it's already the name of the main folder at the top of the folder structure. Instead, a more suitable option would be simply "Folders" or the existing, overlayed title "Select folder" describing the action.

### Screen recording
![Animation (6 2)](https://user-images.githubusercontent.com/61639215/84457845-f7f52780-ac63-11ea-804b-59aebb6d423b.gif)
_The video was edited to make the crucial frames easier to see. The specific frames during the transition to the folders page were duplicated._

### Screenshots
These are the distinct frames from the transition while entering the folders page. They were extracted from the screen recording:
![](https://user-images.githubusercontent.com/61639215/84548200-65a56000-ad05-11ea-8abc-ef8624f01ed3.png) <sup>**0**</sup>
![](https://user-images.githubusercontent.com/61639215/84548203-66d68d00-ad05-11ea-80bc-e6bc9afbe186.png) <sup>**1**</sup>
![](https://user-images.githubusercontent.com/61639215/84548204-676f2380-ad05-11ea-8490-1934f294743c.png) <sup>**2**</sup>
![](https://user-images.githubusercontent.com/61639215/84548206-68a05080-ad05-11ea-8b8d-e1ebf8c22945.png) <sup>**3**</sup>

### Device information
* Android device: Samsung Galaxy S9+ (SM-G9650/DS)
* Android version: 8.0.0
* Fenix version: 5.1.1

**Comment by Vaintti** [comment]
I can take a look at this

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200622 from 6/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200622-093442](https://user-images.githubusercontent.com/51314259/85256001-06192400-b46c-11ea-8382-63286bc7ccea.gif)
