### ISSUE TITLE
[Bug] Update Collections documentation to reflect tab state restoring

### ISSUE THREAD

**Issue by maroonmoon13** [mozilla-mobile/fenix#11506]
## Steps to reproduce
Add a website to a collection (lets save www.goal.com)
Open it by clicking it from collection at time X
Open the page again after an hour or so (Y) from the collection. The time should be enough such that the website would have posted new content.

### Expected behavior
The latest page should show up.

### Actual behavior
Firefox does not load the latest version. The page displayed is still the one from time X. I have to refresh to bring up the latest page.

### Device information
Pixel 3

* Android device: ?
* Fenix version: 5.1.1

**Comment by sheikh-azharuddin** [comment]
Somewhat I too feel pages are loaded from cache
...for example in below page it shows created 13 hours ago whereas nightly is released daily at 6am and 6pm GMT.. so difference should be 12 hours...if I load after sometime say 30 mins it will show created 1hr ago...

https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest

![6792](https://user-images.githubusercontent.com/58127841/84475014-58dc2a00-ac7b-11ea-9ff5-832faf674fb1.png)

**Comment by ekager** [comment]
This is intentional behavior with collections currently. We are restoring the state of the tab with history as well.

**Comment by maroonmoon13** [comment]
The documentation is pretty lacking in this regards. No where on the page: https://support.mozilla.org/en-US/kb/collections-firefox-preview does it says that the state of the page will be maintained. Till the option of adding website short cuts was available, Collections was the only place to have quick access to websites available. And as far as I can remember, it did work properly in earlier versions. So rather than closing this bug, I would prefer that we change it to a bug for documentation.

**Comment by cadeyrn** [comment]
I agree. In the last weeks I received not only one support request due to the fact that the behaviour of collections is not obvious at all. It should really be better documented. Ideally it should be better communicated within the product but at least SUMO should mention how this feature is supposed to do - and how it is different than bookmarks. Improving the documentation on SUMO seems to be as easy change and doesn't require code changes. @ekager What is the best way forward to get a better documentation of this feature on SUMO?

**Comment by ekager** [comment]
Okay that's fine, we can request a SUMO update.

**Comment by ekager** [comment]
CC @jonichan could we get a sumo update to reflect that collections restore the state of a tab?

**Comment by PyvesB** [comment]
> This is intentional behavior with collections currently. We are restoring the state of the tab with history as well.

This does somewhat contradict #10417, where you acknowledged and reopened the issue. A lot of users dislike this behaviour and are getting confused by it. After all, what is the point of having entire collections of stale tabs? :)

**Comment by ContentPersonality2** [comment]
> > This is intentional behavior with collections currently. We are restoring the state of the tab with history as well.
> 
> This does somewhat contradict #10417, where you acknowledged and reopened the issue. A lot of users dislike this behaviour and are getting confused by it. After all, what is the point of having entire collections of stale tabs? :)

Agreed. When I started using Firefox Preview I really liked how collections worked, I could open up all my usual go to sites with as little as two clicks. Now I've had to resort to using the top sites feature so I don't load cached outdated content.

At the very least I expect to see an option to disabled collections caching.

**Comment by ekager** [comment]
#10417 is not a bug, but we can leave it open for UX feedback.
