### ISSUE TITLE
Add Multi-threaded/Parallel downloads feature to the built-in download manager

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11505]
### What is the user problem or growth opportunity you want to see solved?
Multi-threaded downloads divide the file into a number of parts lets say 3 or more and by doing so the download manager downloads each part as if it was a seperate download instance so the download speed gets improved quite a lot. Usually this type feature is found in third-party download managers like [ADM](https://play.google.com/store/apps/details?id=com.dv.adm) but Chrome has also added this feature, You can read about it in this article from [XDA Developers](https://www.xda-developers.com/google-chrome-parallel-download-accelerate-download-speeds/). 

### How do you know that this problem exists today? Why is this important?
When downloading bigger files and sometimes even smaller files servers sometimes limit/reduce the download speeds and if this feature is added this will definitely speed up the file downloads. 

### Who will benefit from it?
Users who download large files will definitely benefit from this feature. And others will also benifit from it since it offers increased download speeds.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2033)

**Comment by Gauravjani207** [comment]
You can use download manager for that.

**Comment by Amejia481** [comment]
cc @vesta0

**Comment by SS1113** [comment]
> You can use download manager for that.

@Gauravjani207 Yes, I can definitely use third-party download manager for that. What I'm asking is that this feature to be included within the browser itself because not everybody uses third-party download managers and they'll benefit from this feature

And as for me I only plan to use third-party download managers for bigger files and for smaller files I'll use built-in download manager so having this feature built into the browser itself will benefit me as well.

**Comment by ShatteredPixel** [comment]
Hi, I am the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812812

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
