### ISSUE TITLE
FNX-12450 ⁃ [Bug] Edit bookmarks: Wrong button title

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#11504]
## Steps to reproduce
1. Edit a bookmark or folder
1. Select the parent folder
(tap the current parent folder)
1. Long-press the create new folder icon on the title bar

_"Select folder" is displayed_

### Actual behavior
The button creates a new folder. "Select folder" is the wrong title for that button. It's the description for the current page, but not for the action of the button.

### Expected behavior
The button creates/adds a new folder. Accordingly, it should be called "Add folder". That's the same title the add folder button has in the bookmarks section, when not editing any bookmark or folder.

### Screenshot
![](https://user-images.githubusercontent.com/61639215/84533836-37198c00-ace9-11ea-89d4-f8e20679690a.png)

### Device information
* Android device: Samsung Galaxy S9+ (SM-G9650/DS)
* Android version: 8.0.0
* Fenix version: 5.1.1

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/15 with Samsung Galaxy Note 10 (Android 10) and Nokia 6 (Android 7.1.1).
