### ISSUE TITLE
[Bug] Edit bookmarks: glitch with the name of the main folder

### ISSUE THREAD

**Issue by theFireProjet** [mozilla-mobile/fenix#11502]
## Steps to reproduce
1. Edit a bookmark or folder/create a folder that is located in the main bookmarks folder
  * on a saved website, open the menu and tap the 'Edit bookmark' button, or
  * go to Bookmarks, open the context menu of a bookmark or folder here, tap 'Edit'

_Folder "mobile" is displayed_

1. Tap the current folder, but don't change it
1. Go back again to the edit bookmark/folder page

_Folder "Bookmarks" is displayed_

### Actual behavior
The display name of the main bookmark folder is wrong when the edit bookmark/folder page opens. It changes as soon as the folder name is reloaded, when the "select folder" page is opened and closed again.

### Expected behavior
The displayed name of the same folder shouldn't change.
The first display name "mobile" is vacuous and it's a bad style to start with a small letter.
However, "Bookmarks" is the right title for the main folder. It is also used in the folder structure of the select folder page. And obviously, it's the title of the section containing all other folders and bookmarks. So it's a suitable name.

### Screenshots
<ol>
<li> <b>First step</b>
<br>![](https://user-images.githubusercontent.com/61639215/84533401-5b289d80-ace8-11ea-8adb-8baf8c745a24.png)</li>

<li> <b>Second step</b>
<br>![](https://user-images.githubusercontent.com/61639215/84533403-5bc13400-ace8-11ea-963d-f6d60d77a04c.png)</li>

<li> <b>Third step</b>
<br>![](https://user-images.githubusercontent.com/61639215/84533405-5c59ca80-ace8-11ea-9cf9-25cd6b524246.png)</li>
</ol>

### Device information
* Android device: Samsung Galaxy S9+ (SM-G9650/DS)
* Android version: 8.0.0
* Fenix version: 5.1.1

**Comment by theFireProjet** [comment]
I just noticed that I uploaded the wrong screenshots. I've corrected it now. You can see how at the start it says "mobile" and afterwards "Bookmarks" for the same folder.

**Comment by grigoryk** [comment]
We weren't processing root titles correctly in this dialog. Should be fixed by https://github.com/mozilla-mobile/fenix/pull/15207

While looking around I also noticed that at least some of our telemetry isn't correct for bookmark actions. Filed  https://github.com/mozilla-mobile/fenix/issues/15206

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200921 06:05 (Build #2015765171) GV 82.0a1 from 9/21 with Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Nexus 5 (Android 6.0.1).
I will remove the qa:needed label and close this issue.
