### ISSUE TITLE
[Bug] Open new tab via contextual menu after close - undo action deletes the re-opened tab

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#11515]
## Steps to reproduce
1. Have an opened tab.
1. Long-tap the tabs counter and choose to close the tab.
1. Tap on "Undo" on the "Tab closed UNDO" snackbar.
1. Long-tap the tabs counter and choose to open a new tab/private tab.

### Expected behavior
A new tab/private tab is opened.

### Actual behavior
The re-opened tab from step 3 is closed.
The user is redirected to the homescreen.

### Device information
* Android device: Google Pixel 3a (Android 10), OnePlus 5T (Android 9)
* Fenix version: 6/12 Nightly build

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4771229/logcat.txt)

![20200612-164117](https://user-images.githubusercontent.com/40694158/84510864-5820b380-acce-11ea-8bf0-81500b3e9ef8.gif)

**Comment by topotropic** [comment]
@softvision-miralobontiu I tried it out but couldn't reproduce "The re-opened tab from step 3 is closed." 

When I open a new tab the tab stays open and I see home and once I enter a URL or select a top site the tab counter counts up (this is a little unfortunate but there's no way around it for now).

**Comment by softvision-miralobontiu** [comment]
I wasn't able to reproduce this issue on the latest Nightly build from 7/8 with Google Pixel (Android 10).
I will close this.
Thanks, Nicole!
