### ISSUE TITLE
FNX-12471 ⁃ [Bug] PWA inexplicably shrunken with thick white bars

### ISSUE THREAD

**Issue by igalic** [mozilla-mobile/fenix#11521]
a picture says more than i could, so see below

## Steps to reproduce
honestly, no idea
it's a bit sporadic

### Expected behavior
do not suddenly display a thick white useless bar on top
or on the bottom
and do not show me the equally useless URL bar in PWA mode

### Actual behavior
![Screenshot](https://user-images.githubusercontent.com/497249/84526422-8d80cd80-acdd-11ea-8fa1-027cb4ca141f.jpg)UNITO-UNDERSCORE!20200612-181710!

### Device information
* Android device: OnePlus 5t / Android 10 / OxygenOS 
* Fenix version: Nightly 200611 06:01 (Build #21630608)
45.0.20200610130052, e5839f921
GV: 79.0a1-20200609092134
AS: 60.0.0

**Comment by NotWoods** [comment]
Superseded by #11708. This should be fixed in the next Nightly.
