### ISSUE TITLE
FNX2-13502 ⁃ Add new Leanplum E_Search_Widget_Added Event

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#11531]
The following were identified as missing in Fenix during a recent test by the Mobile Engagement team. This event by the same name is present in Fennec. This is requested to be in market by 8/25/20 (release 80).

* [ ] E_Search_Widget_Added

This should be fired when the user adds the Search Widget to the homescreen, regardless of the app being presently opened or not.

Tasks:

* [ ]  Understand if there are implications of using the same event name (E_Search_Widget_Added) from Fennec in Fenix (noting since it seems event names changed from Fennec to Fenix)
* [ ]  Add mapping for E_Search_Widget_Added
* [ ]  Undergo data review
* [ ]  Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

**Comment by cbonacuse** [comment]
This needs to be added to the [Mobile Engagement ❤️ Fenix project ](https://github.com/mozilla-mobile/fenix/projects/48#card-39585660). I do not have access to add it myself.

**Comment by sblatz** [comment]
@cbonacuse do we care about when the widget is removed or just added?

**Comment by cbonacuse** [comment]
@sblatz just added :) the boolean attribute search_widget_installed should help us account for who does/does not have the widget installed.

**Comment by ekager** [comment]
cc @cbonacuse this has landed!

**Comment by AndiAJ** [comment]
Hi @cbonacuse & @sblatz , I've just checked this matter on both the latest **`Nightly Build 200730`** and **`Fenix Beta 80.0.0-beta-1`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

The `E_Search_Widget_Added` event **is properly generated**, on the other hand it looks like the `search_widget_installed` attribute remains set to false in most cases, filled #13114


## ✔️ Nightly
Google Pixel 3a -  device ID **`e6222324-6a2d-403a-abc5-a7b777227632`**
![image](https://user-images.githubusercontent.com/51314259/88916536-e812c080-d26e-11ea-8204-9673f3085d8a.png)
![image](https://user-images.githubusercontent.com/51314259/88916597-07a9e900-d26f-11ea-885e-babd697e70c0.png)

Huawei Mate 20 Lite -  device ID **`1334424f-5898-4337-9ed7-9679fed9fb25`**
![image](https://user-images.githubusercontent.com/51314259/88917081-da116f80-d26f-11ea-8e55-2445e9b89eb7.png)
![image](https://user-images.githubusercontent.com/51314259/88917046-c960f980-d26f-11ea-9b8d-6f793cebe0bd.png)


OnePlus A3 -  device ID **`d5e35e4f-c75a-4b5e-9aa0-6aa2cbb6c78b`**
![image](https://user-images.githubusercontent.com/51314259/88917149-f2818a00-d26f-11ea-9aa8-06afadc1531a.png)
![image](https://user-images.githubusercontent.com/51314259/88917171-fdd4b580-d26f-11ea-99af-b5de927a8c79.png)


## ✔️ Beta
Google Pixel 3a - device ID **`35d5c40d-0362-4b55-8aee-ffc6a9e7012c`**
![image](https://user-images.githubusercontent.com/51314259/88917406-5efc8900-d270-11ea-92e9-4bc61532eb41.png)
![image](https://user-images.githubusercontent.com/51314259/88917439-6ae84b00-d270-11ea-8b0d-048e58292b10.png)

Huawei Mate 20 Lite - device ID 48e981ae-5ec4-43f7-bbb2-5d4532f15627
![image](https://user-images.githubusercontent.com/51314259/88917504-894e4680-d270-11ea-851e-d81a66aab958.png)
![image](https://user-images.githubusercontent.com/51314259/88917535-95d29f00-d270-11ea-94a1-222a6f962480.png)


OnePlus A3 - device ID **`27951d4c-5729-43cf-92e2-ad7553a1a5c5`**
![image](https://user-images.githubusercontent.com/51314259/88917591-b1d64080-d270-11ea-997b-a3f78825ca73.png)
![image](https://user-images.githubusercontent.com/51314259/88917618-bf8bc600-d270-11ea-9a06-92425093182d.png)

**Comment by sblatz** [comment]
Landed the changes we discussed, @cbonacuse. Let me know if you don't see it working in tomorrow's version of Fenix Nightly :)

**Comment by cbonacuse** [comment]
Thanks @sblatz it worked for me! :) This was for E_Changed_Default_To_Fenix but this comment/commit is in the search widget ticket (not sure if that matters but just wanted to confirm!)
