### ISSUE TITLE
FNX-12484 ⁃ [Bug] Cant take screenshot in PWA or Custom tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11534]
## Steps to reproduce
Set allow screenshots in private browsing to off
Open PB mode in fenix
Leave fenix, open pwa or custom ta 

### Expected behavior
Can take screenshot. PWA cannot be in PB

### Actual behavior
Can't take screenshot

### Device information
* Android device: Asus zenfone
* Fenix version: fenix nightly

**Comment by sheikh-azharuddin** [comment]
Also while closing the private mode from notification panel the pwa screen also closing

**Comment by kbrosnan** [comment]
You should be able to change the `Allow screenshots in private browsing` toggle to true to enable this behavior in the Private Browsing section of the settings. It changed last week to disable screenshots by by default.

**Comment by cadeyrn** [comment]
Maybe this this toggle should be renamed or get a description to make it clear that it affects PWAs and Custom Tabs, too? I never would have thought that this option affects PWAs and Custom Tabs.

**Comment by s-ankur** [comment]
@kbrosnan I understand that but the problem is different.
Right now, whether you can take screenshot in PWA depends on if the *browser* is in private mode or normal mode which makes no sense .
@cadeyrn it would be one thing if the option unconditionally disabled screenshots in pwa and ct but right now it depends on what you are doing in the browser which i think should not affect pwa or ct

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200623-150322](https://user-images.githubusercontent.com/51314259/85402135-d2b9c080-b563-11ea-9820-fab707c5d24b.gif)
