### ISSUE TITLE
FNX2-13503 ⁃ [Bug] ETP sheild icon vanishes on report site issue

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11535]
## Steps to reproduce
Report site issue on any site

### Expected behavior
Webcompat.com opens

### Actual behavior
Webcompat.com opens but the sheild icon vanishes

### Device information
* Android device: asus zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200613-015611_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/84543657-47326b00-aceb-11ea-9529-50f04a38f73d.png)

**Comment by ekager** [comment]
Closing for #12848
