### ISSUE TITLE
faster page load with data saver

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11536]
### What is the user problem or growth opportunity you want to see solved?
Unlike chromium browsers such as Chrome/brave/opera/yandex which has a feature like data saver/lite mode/opera turbo to save data or load page faster on slow network, we don't have a similar feature in firefox browser. If the feature is added in firefox we can save data or load page faster like other browser. Additionally you can show in the homepage how much data saved or how many trackers blocked kind of telemetry to users like brave.

### How do you know that this problem exists today? Why is this important?
This feature is not present in firefox

### Who will benefit from it?
All users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2066)

**Comment by SS1113** [comment]
I don't think Mozilla will add this type of feature considering they don't have it on desktop as well and it'll be a serious privacy issue if all of the websites I visit are sent to a server between the client and the end remote server. 

And nowadays most of the websites are encrypted so they can't be compressed with a server. Well they can be with a Man In The Middle Attack(MitM), and this will compromise the encryption(Https connection) between the website server and the client. So it's both a security and a privacy issue as well. You can read more about it [here](https://www.techrepublic.com/blog/it-security/redirection-and-decryption-of-mobile-traffic-is-your-browser-a-mitm/). Chrome browser also doesn't touch a website which is encrypted (Https) and only the unencrypted (Non-Https) trafic is compressed to save data.
 And even in that case as well you won't save much data as most of the traffic on the web today is encrypted (Https).

**Comment by benyaminl** [comment]
In my opinion if it's allowed please bring back the image turn off and no font download on mobile network like on old fennec browser, it will help, I use it a lot and on new Fennix Browser, it's gone, poof..

**Comment by sheikh-azharuddin** [comment]
I see the turbo mode feature is already present in Firefox lite.. Probably it can be added to the main browser too

**Comment by SkewedZeppelin** [comment]
Ignoring privacy breaking proxy solutions, simply sending the `Save-Data: on` [header](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/) when the Android system-wide `Data Saver` option is [enabled](https://developer.android.com/training/basics/network-ops/data-saver#status) would be appreciated by many.

I tried to implement this for Firefox Focus long ago, but never finished:
https://github.com/mozilla-mobile/focus-android/pull/4113

And did implement in two other Android browsers:
https://github.com/anthonycr/Lightning-Browser/pull/728
https://github.com/scoute-dich/browser/pull/237

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813619

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
