### ISSUE TITLE
When a PWA is first installed, reopen the current tab in the new PWA

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#11549]
### What is the user problem or growth opportunity you want to see solved?
When a PWA is first installed, we can "promote" the current tab to be reopened in PWA form. 

The user flow would look like:

* Open Twitter website in tab no. 5 without having Twitter PWA installed
* Choose menu option to install Twitter PWA
* Twitter PWA is installed
* (_new_) Tab no. 5 is closed, as the same tab is now open as a PWA.

### How do you know that this problem exists today? Why is this important?
Inspired by this [Twitter comment](https://twitter.com/cheneytsai/status/1179416167817138184?s=09):
>I'd like to see a promote to top-level UI mechanism (like a better full-screen API...maybe on "install", auto promote UI to replace the URL bar =)

### Who will benefit from it?
This makes it easier for users to access their newly installed PWAs.

- - -
I messed up the first time I filed this and it looked like a different feature request 🤦. I'm rewording both issues to clarify the two ideas.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2083)

**Comment by TitanNano** [comment]
One issue I see with this: currently Fenix sends the user to the launcher to show the newly added PWA and I think that's good. We can't both promote the tab into a PWA and send the user to the launcher.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807427

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
