### ISSUE TITLE
[Bug] Always open website in apps

### ISSUE THREAD

**Issue by cathaysia** [mozilla-mobile/fenix#11548]
## Steps to reproduce
1. open a this website: "https://www.baidu.com/s?wd=如何评价Firefox%20site%3Azhihu.com"
1. Pick one link you like and open it.
1. This website will ask if you'd like open it in apps.
1. Fenix will open it in apps always although I choose "NO".

### Expected behavior
Fenix DON'T open website in apps automatic. 

### Actual behavior
Fenix always open website in apps.

### Device information
OPPO X7 Plus

* Android device: ?

android 7.1.1

* Fenix version: ?

5.00 build #21212137

**Comment by ekager** [comment]
@cathaysia are you still seeing this issue?

**Comment by cathaysia** [comment]
> 
> 
> @cathaysia are you still seeing this issue?

This issue had disappear in Firefox 84.1.1. I just test it in www.baidu.com and zhihu.com. It works!

**Comment by ekager** [comment]
Thanks! Closing
