### ISSUE TITLE
FNX-12498 ⁃ [Bug] Twitter PWA/custom tabs have white empty space on the top and it carries that to the whatever website that has been opened from it

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11547]
## Steps to reproduce
I don't know if it's a duplicate of this #11189 or #11356 as I'm having a hard time keeping track of dynamic toolbar bugs so I created this issue anyway. If it's a duplicate then please close it.

Edit: The issue #11545 is talking about the black bar appearing at the top in PWA+web content. So I think that issue is similar/duplicate of this.

Edit: Another similar issue #11521.

1. Go to Twitter.com
1. Install the PWA 
1. Launch it
1. See the white space at the top
1. And further, open a website within it
1. See the white empty space on top of the whatever website that has been opened from it

• See the screenshots and I'm using the **bottom toolbar**.

Edit: Any links opened in custom tabs are also behaving this way.

### Expected behavior
Shouldn't have any empty space on the top on Twitter as well as the website that has been open from it

### Actual behavior
Empty space on both Twitter and website that has been opened from it

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: `5.2.0-beta.1` and `Nightly 200612 18:01`

![Screenshot](https://user-images.githubusercontent.com/42088907/84557673-9d6bd200-ad1c-11ea-8893-bbaf8523bfbc.png)UNITO-UNDERSCORE!20200613-073342!

Empty space carried to the website as well.

![Screenshot](https://user-images.githubusercontent.com/42088907/84557676-a2308600-ad1c-11ea-86e4-da90354860dd.png)UNITO-UNDERSCORE!20200613-073401!

**Comment by sheikh-azharuddin** [comment]
In dark mode the big fat white space is purple color...

**Comment by sheikh-azharuddin** [comment]
Also I see custom tab also has that ugly white space....

![Screenshot_20200613-143500](https://user-images.githubusercontent.com/58127841/84564929-0838ff80-ad55-11ea-8f9f-9e5f7b0aabdf.jpg)

**Comment by yoasif** [comment]
Also seeing this on Pixel 2.

**Comment by NotWoods** [comment]
Superseded by #11708. This should be fixed in the next Nightly.
