### ISSUE TITLE
[Bug] Syncronised Tabs still show in menu when tab syncing is disabled

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#11546]
## Steps to reproduce
With tab sync off, open the menu

### Expected behavior
Synchronized Tabs option shows in the menu when Tab Sync is enabled, and is hidden when it's disabled

### Actual behavior
It shows regardless of the setting

**Comment by apbitner** [comment]
@violasong For consideration re: the menu. I believe we're showing Synced Tabs for users who aren't signed in, but if a user is signed in and deslects Open tabs from their account settings, should we still show it?

**Comment by topotropic** [comment]
Thanks for the feedback! Synced tabs will move to the tab tray https://github.com/mozilla-mobile/fenix/issues/14117 and once implemented will be removed from the menu. I'll close the issue.
