### ISSUE TITLE
FNX-12492 ⁃ Tab Tray A11y - First tab in list is read as "3 of 3"

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/fenix#11542]
## Steps to reproduce
1. Open 3 tabs
1. Open the newest tab (first in the list)
1. Open the tab tray again
1. Hear "3 of 3 in list of 3 items"

### Expected behavior
Hear "1 of 3 in list of 3 items"

Since it says "3 of 3", I would think I would need to swipe backward/left to get to 2 of 3, but instead you need to swipe right.

Not sure there's a great way to fix this.  To get the newest tabs on top, we reverse the order of the tab display visually:

```
val layout = LinearLayoutManager(context).apply {
                reverseLayout = true
                stackFromEnd = true
            }
```

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200624 from 6/24`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200624-121157](https://user-images.githubusercontent.com/51314259/85531033-115c8300-b617-11ea-903e-1e6a912d72ac.gif)


@darkwing - Filled a new issue #11879 regarding an OnePlus inconsistency
