### ISSUE TITLE
FNX-12496 ⁃ [Bug]  Blank bar appears above web content in custom tabs + PWAs

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#11545]
### In an installed PWA
![Screenshot](https://user-images.githubusercontent.com/63871973/84556773-c2604500-ad1c-11ea-951f-cdd5bf7edfac.jpg)UNITO-UNDERSCORE!20200613-021329!

### In custom tabs
![Screenshot](https://user-images.githubusercontent.com/63871973/84556860-9db89d00-ad1d-11ea-9b50-89b073c4f9bb.jpg)UNITO-UNDERSCORE!20200613-022707!

### Device information
* Android device: Galaxy S8+, Havoc OS (Android 10)
* Fenix version: Nightly 200612 18:01 (Build #2015745875)

**Comment by astarq** [comment]
Oh and no change when the toolbar is at the top!

**Comment by NotWoods** [comment]
Superseded by #11708. This should be fixed in the next Nightly.
