### ISSUE TITLE
FNX-4832 ⁃ Library Sign in to Sync

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1155]
As a user with a FxA, I want to sign in to sync so I will be able to access things I've saved on other devices and get access on those devices to the things I've saved in Fenix

### Acceptance Criteria (Added by PM)
I can see the option to  log in to my Firefox Account
I can successfully sign in to my Firefox Account
When I am signed in to Fenix, I can view bookmarks and history from other devices
When I am signed in to Fenix, I can sync bookmarks and history from Fenix to other devices
When I am signed in to other devices, I can view bookmarks and history from Fenix

**Comment by bbinto** [comment]
@mheubusch - is this a duplicate of #289?

**Comment by mheubusch** [comment]
@bbinto i think so.should i close it or can i delete it?

**Comment by bbinto** [comment]
Let's close it
