### ISSUE TITLE
[BUG] Folders in Bookmark aren't shown on top.

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#11554]
I've lots of bookmarks saved with or without folders. But folders aren't always shown on top. While in regular Firefox they're always shown on top. Please fix this.
Thank You.

**Comment by AndiAJ** [comment]
Not reproducible anymore on the latest Nightly Build 201103 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
