### ISSUE TITLE
FNX-12510 ⁃ [Bug] (regression) you need two clicks instead of one to open a tab in tabs tray

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11558]
### Steps to reproduce
1. open the tabs tray
1. click on a tab
1. repeat step 2

### Expected behavior
The tab opens after step 2.

### Actual behavior
Nothing happens after step 2, the tab only opens after step 3.

It's a regression from #11487, cc @darkwing 

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 7e6116512c354eb1d8524f8922f7970fe155c65c

**Comment by AndiAJ** [comment]
Hi, reproducible on **`Nightly Build 200616 from 6/16`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200616-201814](https://user-images.githubusercontent.com/51314259/84739688-c60df900-afb4-11ea-8262-85ca47ebc209.gif)

► Video
![20200616-201348](https://user-images.githubusercontent.com/51314259/84739645-ab3b8480-afb4-11ea-89f0-667ef28a770e.gif)

**Comment by hakkikaancaliskan** [comment]
Problem is here: https://github.com/mozilla-mobile/fenix/blob/e6da2bd910e4b0f49ceda628e14fda0b67bccf13/app/src/main/res/layout/tab_tray_item.xml#L12
Removing this line fixes problem.

**Comment by ekager** [comment]
Nice, thanks @hakkikaancaliskan , I'll make a quick PR :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly 200618 from 6/18`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200618-135433](https://user-images.githubusercontent.com/51314259/85012650-02378a00-b16c-11ea-93e5-ad4a116b377d.gif)
