### ISSUE TITLE
Full screen landscape videos cuts off lower part of video.

### ISSUE THREAD

**Issue by SChetwynd** [mozilla-mobile/fenix#11565]
When viewing a video in full screen, in landscape orientation the lower portion of the video is missing, and it is not possible to scroll and view the missing bit of video. I've tested this on YouTube and Vimeo, with videos in both 6:5 and 16:9 aspect ratios, and it is still the same amount of video which is cut off.

The video controls still display at the bottom of the screen as expected.

Portrait full screen and the video is fully visible
![Screenshot](https://user-images.githubusercontent.com/41822912/84589189-d55e3c80-ae24-11ea-9ee9-be5294cd8dfd.png)UNITO-UNDERSCORE!20200614-094649!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!

Landscape full screen and the bottom is cut off
![Screenshot](https://user-images.githubusercontent.com/41822912/84589194-dee7a480-ae24-11ea-8502-f31af6c17f1b.png)UNITO-UNDERSCORE!20200614-094701!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!

A similar issue exists but the wording seems to imply that the amount cut off is dependant on the aspect ratio of the video, and in that issue it was possible to scroll to view the missing video.

I'm using: 
5.1.1 (Build #21571852)
42.0.1, 5bf46033e
GV: 77.0-20200526221856
AS: 0.58.2

On a Xaiomi Redmi Note 7, running LineageOS, Android 9

**Comment by Amejia481** [comment]
I've experience the same issue on a resent version of nightly and Fennec. It looks like the issue could reside inside of geckoView I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1654800 for the team to take a look

```
Nightly 200723 06:01 (Build #22050611)
AC: 52.0.20200722023149, 5c2458cb8
GV: 80.0a1-20200721094241
AS: 61.0.10
```

**Comment by kbrosnan** [comment]
Duplicate #8252

**Comment by Webbeh** [comment]
Confirm this issue still persists.

YouTube app defaults to the same kind of cropping (to fill the screen), but you can choose to have a "fit" instead of "fill" option.
