### ISSUE TITLE
FNX-4833 ⁃ Automate Fenix telemetry documentation to probe-scraper

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#1156]
### Why/User Benefit/User Problem
Generate telemetry documentation using an existing scraper.

### What / Requirements
Add Fenix to the [probe-scraper scripts](https://github.com/mozilla-mobile/fenix/pull/1067#discussion_r268144246) (which is already generating docs for reference browser)

### Acceptance Criteria (how do I know when I’m done?)
Docs are generated from metrics.yaml

**Comment by liuche** [comment]
@fbertsch do you manage the probe-scraper and could you do this for Fenix after #1067 lands?

**Comment by bifleming** [comment]
@vesta0 do we want to make this a blocker and add it to the board?

**Comment by fbertsch** [comment]
@bifleming @liuche yes, I do manage the probe-scraper, and the data is available: https://probeinfo.telemetry.mozilla.org/glean/fenix/metrics

Are you looking to get this integrated into the [probe-dictionary](https://telemetry.mozilla.org/probe-dictionary) before launch? That is probably a Q3 goal at the earliest.

**Comment by vesta0** [comment]
@fbertsch thanks for the info on probe-scraper! 

Considering I didn't know there was a probe-dictionary (so cool!) I'd say no that's not the goal before launch but would be great for Q3. For now we are just looking to have a list of probes publicly documented similar to [Focus.](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fmozilla-mobile%2Ffocus-android%2Fblob%2Fmaster%2Fdocs%2FTelemetry.md&sa=D&ust=1560184385876000&usg=AFQjCNEJ_Y3ydZpIy3QtyOEnolCd1b3qEQ)

**Comment by liuche** [comment]
@vesta0 we have a meeting set up for later this week about documentation of probes, but I'm wondering, could you clarify with Michael if linking to the metrics.yaml file would be acceptable to fulfill the requirements? I'm concerned that documenting probes similar to Focus in a wiki would be duplicated work (that the probe scraper will do) and engineering seems pretty overloaded with requirements at the moment.

**Comment by vesta0** [comment]
@liuche the only legal requirement is that this is user readable and accessible. Let's chat about what we can do tomorrow. I hope that there is an interim solution that I can implement with minimum Eng effort.

**Comment by liuche** [comment]
@vesta0 does the [metrics.yaml file](https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml) work? for probe documentation at least.

**Comment by sblatz** [comment]
See [this document](https://docs.google.com/document/d/198L01tgQYq10Th9l3cIeJd-Gk_iISGmGnow5_Ubw02w/edit) for more information from our meeting with Glean.

**Comment by sblatz** [comment]
I'm estimating this as an E3 since #2706 will hold most of the refactor and this can piggy-back off of that :)

**Comment by liuche** [comment]
@sblatz will follow up w/ Glean team to see if they can do it this quarter, or if Fenix should.
