### ISSUE TITLE
add ability to remove an app from the recently shared apps

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11566]
### What is the user problem or growth opportunity you want to see solved?
I would like to remove apps from the recently shared apps in Fenix. I suggest a menu item when long pressing an app.

![Screenshot](https://user-images.githubusercontent.com/1100614/84589499-26732e00-ae2f-11ea-9dc5-953a004f4024.jpg)UNITO-UNDERSCORE!20200614-110454!

### How do you know that this problem exists today? Why is this important?
I already received a support request for such a feature in Fennec. Since Fennec no longer receives feature updates it would be a great addition for Fenix. I also would love to see this in Fenix.

### Who will benefit from it?
Users who don't want an user interface that is cluttered with non important things.

A few use cases:

* A user may not want to expose which apps he used recently (privacy).
* A user may accidentally chose a wrong app and since the user only share via one or two apps the wrong app will be there forever.

### Additional notes:
An AC API was already implemented:
https://github.com/mozilla-mobile/android-components/pull/6360

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2112)

**Comment by Gauravjani207** [comment]
That is needed. I confirm that I don't like that congested share menu.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809789

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
