### ISSUE TITLE
Open non pwa shortcut like app/pwa

### ISSUE THREAD

**Issue by JVariance** [mozilla-mobile/fenix#11568]
### What is the user problem or growth opportunity you want to see solved?
If I add a non pwa website as shortcut to my homescreen and open it, it opens as a new tab in the browser.

It would be great, to let it open as an app as it's done with pwa's instead of a new tab.

### Who will benefit from it?
Everyone, who enables this feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2115)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807098

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
