### ISSUE TITLE
FNX-12513 ⁃ [Bug] alignment issue in tabs tray

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11562]
### Steps to reproduce
1. open the taby tray

### Expected behavior
Better alignment of the tree dots menu icon and the close icon of the tabs.

### Actual behavior
![](https://user-images.githubusercontent.com/1100614/84588759-5ff56a80-ae2a-11ea-8830-4faa71fc45b1.png)

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 7e6116512c354eb1d8524f8922f7970fe155c65c

**Comment by AmyYLee** [comment]
I agree the 3-dot icon should be centered

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_rsz_screennnnnshot_20200625-142037](https://user-images.githubusercontent.com/51314259/85711739-3e309900-b6f0-11ea-83d7-a9c1ccde6e3e.png)
