### ISSUE TITLE
FNX-12516 ⁃ [Bug] tabs tray: show trash icon when starting a swipe gesture to close a tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11564]
### Steps to reproduce
1. open the tabs tray
1. start to swipe to the left or right to remove a tab

### Expected behavior
There should be a trash icon like in the previous implementation.

![Screenshot](https://user-images.githubusercontent.com/1100614/84589035-405f4180-ae2c-11ea-9453-9f4da7feaf36.jpg)UNITO-UNDERSCORE!20200614-104256!

### Actual behavior
Empty space, the user doesn't know what happens.

![Screenshot](https://user-images.githubusercontent.com/1100614/84589039-4bb26d00-ae2c-11ea-8252-ba2097f303ae.jpg)UNITO-UNDERSCORE!20200614-104234!

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 7e6116512c354eb1d8524f8922f7970fe155c65c

**Comment by darkwing** [comment]
We talked about this and we'll enhance this down the road.

**Comment by ekager** [comment]
Closing for #11324
