### ISSUE TITLE
FNX2-13522 ⁃ [Bug] tabs tray: Fenix loses thumbnail of GitHub

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11573]
### Steps to reproduce / Actual behavior
Unfortunately I don't have steps to reproduce but it happens relatively often that Fenix loses the thumbnail of GitHub. Fenix only shows a white area, but the thumbnails of other tabs are still there.

![Screenshot](https://user-images.githubusercontent.com/1100614/84596156-5edd3100-ae5c-11ea-9c55-5b8a5495aedc.jpg)UNITO-UNDERSCORE!20200614-162937!

### Expected behavior
Fenix doesn't lose a thumbnail. But if it happens for whatever reason I would expect that all tabs are affected and not only GitHub.

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 7e6116512c354eb1d8524f8922f7970fe155c65c

**Comment by sheikh-azharuddin** [comment]
It's only github but other sites are affected too. This happens particularly in mobile data.

![Screenshot_20200614-205758](https://user-images.githubusercontent.com/58127841/84597464-b3c87980-ae53-11ea-8ee6-344bce550f41.jpg)

**Comment by yoasif** [comment]
It loses thumbnails randomly from any site as far as I can tell - it doesn't matter what the domain is.

**Comment by sheikh-azharuddin** [comment]
Not only thumbnail ,in the top sites too the favicon is lost sometime...sometime the icon shows sometime a letter only.

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on today's Nightly build (6/25) with HTC 10 (Android 8):

<img src="https://user-images.githubusercontent.com/40694158/85714096-c2841b80-b6f2-11ea-867a-1530e8ede307.png" width="300" height="550" />

**Comment by AndiAJ** [comment]
Similar with #11733 ?
Noticed that after you put Fenix in background and resume the screenshot is lost

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-113039](https://user-images.githubusercontent.com/51314259/91281535-e0243e80-e790-11ea-8ae7-bdf2e0f25ca7.gif)
