### ISSUE TITLE
[Telemetry] Download events

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11578]
## Description & Product Manager / Data Scientist User Story
As a product manager, I need to know how often something is downloaded using the browser, so I can appropriately prioritize enhancing the download experience in relation to other features. 

## What questions will you answer with this data?
-What percentage of total and weekly active users download a file using the browser? (e.g. 7% of total users and 5% of weekly active users download a file)

-How often do users download a file? (e.g. 3 % of users download a file every day, 2% of users download 3 files a week.)

Note: we track the interactions with download notifications but I don't believe we track the actual download events. 

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by sblatz** [comment]
@vesta0 

> "Note: we track the interactions with download notifications but I don't believe we track the actual download events."

 Are these meaningfully different? notifications will _always_ appear for users when a download begins, finishes, or fails.

**Comment by sblatz** [comment]
Ah! One case where they're different:

Long press image -> contextual menu -> save image. Triggers a download but does NOT trigger a "download notification" until it's saved.

**Comment by sblatz** [comment]
So we *should* add events firing for downloads.

**Comment by liuche** [comment]
Eng needs to file the DS Jira bug for this.

**Comment by eliserichards** [comment]
This has been approved by Marissa during our all hands Telemetry Jam, so we don't need to file a ticket for this.

**Comment by Mugurell** [comment]
Talked offline with Kate who confirmed with DS and Boek:

    The newly added metrics should log events, not counters anymore
    An an expiration date 6 months is preferred.
    Maybe if there is already related telemetry for that part of the screen / feature we can reuse the existing expiration date so that all related telemetry probes will be renewed at the same time.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly 201216`** using a Google Pixel 3a (Android 11) and it seems that the `download_added` event type ping is generated.

@Mugurell please review

**Comment by Mugurell** [comment]
Thank you @AndiAJ.
The changes should now be available to test in the current Nightly.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 12/18 with Google Pixel (Android 10):
 
```
 {
          "category": "downloads_misc",
          "name": "download_added",
          "timestamp": 3279
        }
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/5716332/11578.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-test-18122020)
