### ISSUE TITLE
[Bug] Disqus comments not working

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#11574]
## Steps to reproduce
Open a website with the disqus comments section and attempt to log in. (I commonly visit Inside EVs and face the issue there. 

### Expected behavior
Log in (usually a new tab will pop up) then go back to the page you want to comment on. 

### Actual behavior
New tab loads, appears to log in but it doesn't work. Previous page still shows the log in part. Can't add comments. 

### Device information
* Android device: Pixel 3 XL, Android 10
* Fenix version: latest nightly. 

I want to add that this worked at first when I started using fenix. I don't know why or when specifically it stopped.

**Comment by Kreuger** [comment]
It would appear that this issue is actually caused by the Privacy Badger addon and has been an issue for 6 years. Yikes! Guess we can close it here.

**Comment by ghostwords** [comment]
Hi @Kreuger this will be fixed sometime after https://github.com/EFForg/privacybadger/pull/2653 ships. (Feel free to report Privacy Badger-specific bugs in our repo, I only saw this issue here by accident.)

**Comment by Kreuger** [comment]
> Hi @Kreuger this will be fixed sometime after https://github.com/EFForg/privacybadger/pull/2653 ships. (Feel free to report Privacy Badger-specific bugs in our repo, I only saw this issue here by accident.)

I think someone else made a post about it there and I commented on it.
