### ISSUE TITLE
FNX2-13520 ⁃ "users" in add-ons manager should be renamed

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11570]
The add-ons manager shows a "users" number but this number does not represent the number of users but the numbers of reviews. It causes confusion even for Mozilla staff as seen in https://github.com/mozilla-mobile/fenix/issues/10002#issuecomment-640456773, so it won't be easier to understand for the average user. I suggest to rename it to "reviews" for two reasons:

1. It's not obvious that with "users" the "number of users who have submitted a review" is meant. The term "reviews" better reflects the reality. As user "users" mean "number of users" for me, even if it's placed to the right of the rating stars.
1. Firefox for Desktop already uses the term "reviews" for the same number in the add-ons manager and Firefox for Android should use the same term as Firefox for Desktop to be consistent.

**Comment by AmyYLee** [comment]
@betsymi for reviewing strings

**Comment by cadeyrn** [comment]
@betsymi You probably missed that - could you please confirm that this change is okay (or not)? Thanks! 🙂

**Comment by betsymi** [comment]
> @betsymi You probably missed that - could you please confirm that this change is okay (or otherwise say that it shouldn't be changed)? Thanks! 🙂

I did miss this, thanks for flagging! I agree with your recommendation to use `Reviews` instead.

**Comment by prabhat3108** [comment]
I would like to work on this, please assign it

**Comment by Ankur-Khandelwal** [comment]
I would like to contribute to this.

**Comment by Mugurell** [comment]
Should be ready to test in the next nightly.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-094154](https://user-images.githubusercontent.com/51314259/91270063-bb27cf80-e780-11ea-8f0e-63bd19a4a543.gif)
