### ISSUE TITLE
FNX-12530 ⁃ Once you fill a form, the form is constantly popping up again and again with every search.

### ISSUE THREAD

**Issue by vishalnandagopal** [mozilla-mobile/fenix#11576]
## Site with issue and any steps to reproduce
https://about.gitlab.com/why/use-continuous-integration-to-build-and-test-faster/

Scroll down. Just click on the 'number of employees' section of the form. Don't select anything and press back to go back to filling the form.
Click the toolbar at the bottom
Search anything using the toolbar at the bottom with default search engine.

### Expected behavior
The number of employees popup shouldn't be repeating constantly with every search.

### Actual behavior
It repeats constantly with every search.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No. This issue is not present in chromium browser.

### Device information
* Android device: 10
* Fenix version: Latest Nightly

**Comment by LittleAngelwings** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/11555

**Comment by NotWoods** [comment]
Closing as duplicate as the issues also look like the same request to me.
