### ISSUE TITLE
FNX-4835 ⁃ [Telemetry] Add search counts to baseline ping

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1158]
Follow up on https://github.com/mozilla-mobile/fenix/issues/959#issuecomment-475394264

bbinto update on April 1, 2019

It was identified that some basic / core pings are not included "for free" in the new Glean SDK baseline ping. This ticket is about including the additional pings product wants to track

#### Description & Product Manager 
* As a product owner, I want to know how many searches have been conducted in Fenix

#### Hypothesis
* We believe that our app is most useful when users can and increase their searches

#### What questions will you answer with this data?
* How many searchers per user/day etc. have been triggered.

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
* Report on search counts as one of our main KPIs

#### What probes (suggested, if applicable)
* search count, see row 27 in https://docs.google.com/spreadsheets/d/1P2_aGEE9OtjM3x71d0GBhnHDhzxEL02xEHuKn1no23E/edit#gid=0

### Dependencies (Added by PM and Eng)
* Core ping / baseline ping, see comment here

### Acceptance Criteria (Added by PM)
* Baseline pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by bbinto** [comment]
@boek - this should be covered by #105, can you or @georgf confirm that this is being sent as part of that: https://docs.google.com/spreadsheets/d/1P2_aGEE9OtjM3x71d0GBhnHDhzxEL02xEHuKn1no23E/edit#gid=0, row 27. 

@georgf or does the app engineer have to provide anything below 22 in separate pings and therefore GH issues?

**Comment by georgf** [comment]
@bbinto the app engineer has to record/instrument everything below row 22 in that sheet (if it's critical to the product).

Glean just provides the mechanism to record these (and will take care of sending the data etc.).

**Comment by georgf** [comment]
What might be helpful is that we have all the different metric types [documented now](https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/docs/metrics/adding-new-metrics.md#Choosing-a-metric-type).

**Comment by bbinto** [comment]
@st3fan - please update after the search meeting on April 3 - these requirements might change

**Comment by vesta0** [comment]
@sarentz please confirm if the requirements have changed.

**Comment by sarentz** [comment]
@vesta0 I was not in the April 3 meeting. I want to recommend that the search team knows these requirements best and should be owning them in this ticket.

**Comment by sarentz** [comment]
I see mconnor on the google sheet, so I think it is safe to assume that anything below row 22 is good to go.

**Comment by boek** [comment]
According to [this](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/core-ping.html#searches) possible values are:
```
{
   "yahoo.listitem":2,
   "duckduckgo.listitem":1,
   "google.suggestion":1
}
```

But in Fenix you can use a suggestion to search a listitem. Do we want to call that out in this search count in any way?

**Comment by vesta0** [comment]
@bsurd @boek just to confirm, is this issue completed?

**Comment by bsurd** [comment]
@vesta0 The search_count is being logged in the metrics ping only. Looking at the document referenced in this issue it is not clear to me if it is desired or not to be also displayed in the baseline ping as well or if it should be moved entirely to the baseline ping. Please let me know and I'll file bugs accordingly.

**Comment by boek** [comment]
@bsurd So I think metrics get added to the core ping. This should be good to go now

**Comment by Dexterp37** [comment]
> 
> 
> @bsurd So I think metrics get added to the core ping. This should be good to go now

@boek the `search_count` is only sent with the `metrics` ping, see [here](https://github.com/boek/fenix/blob/3031e0a5093475d920de094bf60bae41e3dce8ea/app/metrics.yaml).

**Comment by AndiJoltan** [comment]
Hi, I've just finished testing the above mentioned issue on the latest Fenix build (2019-06-07T06:06:42.579Z)  using a **Google Pixel 3XL**(Android 9) and a **Samsung Galaxy Note 9** (Android 8.1.0). and concluded that the baseline pings now contain the  **search_count** attribute as well.

#### Please find attached and review the following logs:
○ **Pixel 3XL**
• 6 searches performed | Baseline ping  `325abe2d-b89a-49d9-9f7c-d39d85d069a6` Successfully processed and sent **Lines 1074 - 1120** [Pixel3XLBaselineSearchCount06.txt](https://github.com/mozilla-mobile/fenix/files/3265273/Pixel3XLBaselineSearchCount06.txt)

• 10 searches performed | Baseline ping  `2712f25a-69e4-4a17-8472-ec7aaf830b66` Successfully processed and sent **Lines 1106 - 1150** [Pixel3XLBaselineSearchCount10.txt](https://github.com/mozilla-mobile/fenix/files/3265275/Pixel3XLBaselineSearchCount10.txt)


○  **Samsung Galaxy Note 9**
• 4 searches performed | Baseline ping `05667d08-806a-4c0e-8373-578eae0b589a` Successfully processed and sent  **Lines 5258 - 5304** [SamsungNote9BaselineSearchCount04.txt](https://github.com/mozilla-mobile/fenix/files/3265295/SamsungNote9BaselineSearchCount04.txt)

• 8 searches performed |  Baseline ping `25ec7ff1-824e-4d01-a99d-c59567763e96` Successfully processed and sent **Lines 7694 - 7740** [SamsungNote9BaselineSearchCount08.txt](https://github.com/mozilla-mobile/fenix/files/3265299/SamsungNote9BaselineSearchCount08.txt)

Based on this comment I'll remove the "QA needed" label
