### ISSUE TITLE
[Telemetry] Text Selection Toolbar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#11580]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to know which context menu option are used frequently when users long press on text on a page, so we can ensure that the order matches our users' needs and saves them time. 

## What questions will you answer with this data?
-What percentage of users tab on any of the long press context menu options (copy, share, search, select all)?
-Which context menu options are used most frequently. 

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by sblatz** [comment]
This lives in AC

To be clear this is for the TEXT SELECTION contextual menu.

### Notes
* Add this under category `contextual_menu`

**Comment by codrut-topliceanu** [comment]
> which context menu option are used frequently when users long press on text on a page

 Ok. So maybe a `type: counter` for each of the text selection contextual menu options. (`DefaultSelectionActionDelegate.kt`)

> What percentage of users tap on any of the long press context menu options

  Perhaps a `type: boolean` to know if users have ever activated any of these options before.


![image](https://user-images.githubusercontent.com/60002907/101370439-2d489e00-38b2-11eb-84c0-8a2d98153efd.png)

@kglazko @sblatz Does that sound/look ok to you?

**Comment by kglazko** [comment]
Yes that looks good to me!

**Comment by Mugurell** [comment]
Talked offline with Kate who confirmed with DS and Boek:
- The newly added metrics should log events, not counters anymore
- An an expiration date 6 months is preferred.
Maybe if there is already related telemetry for that part of the screen / feature we can reuse the existing expiration date so that all related telemetry probes will be renewed at the same time.

**Comment by softvision-miralobontiu** [comment]
Verified on the 1/5 Nightly build using a Google Pixel (Android 10):

1. contextual menu: copy_tapped ✔️
Ping a1c8a219-1dcf-41e0-afce-32d106f1097a
```
{
          "category": "contextual_menu",
          "name": "copy_tapped",
          "timestamp": 10379
        }
```
2. contextual menu: search_tapped ✔️
Ping a1c8a219-1dcf-41e0-afce-32d106f1097a
 ```
{
          "category": "contextual_menu",
          "name": "search_tapped",
          "timestamp": 18838
        }
```
3. contextual menu: select_all_tapped ✔️
Ping a1c8a219-1dcf-41e0-afce-32d106f1097a
```
{
          "category": "contextual_menu",
          "name": "select_all_tapped",
          "timestamp": 22404
        }
```
4. contextual menu: share_tapped ✔️
Ping a1c8a219-1dcf-41e0-afce-32d106f1097a
```
{
          "category": "contextual_menu",
          "name": "share_tapped",
          "timestamp": 29625
        }
```
 
[Logcat](https://github.com/mozilla-mobile/fenix/files/5770789/contextual.menu.logcat.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-test-05012021)

@codrut-topliceanu there is no "contextual menu: long_press_tapped" event generated.
Could you please review?

**Comment by codrut-topliceanu** [comment]
@softvision-miralobontiu I've spoken with @kglazko and she said it's okay to remove `long_press_tapped`. 
As this issue's PR is already merged I've created a new issue for the removal. (https://github.com/mozilla-mobile/fenix/issues/17481). 

Besides the removal of long_press_tapped is there anything else that needs to be done on this issue?

**Comment by softvision-miralobontiu** [comment]
@codrut-topliceanu thanks!
Nope, the only reason the ticket was left opened was for the "contextual menu: long_press_tapped" event.
I'll close it.
