### ISSUE TITLE
FNX-12543 ⁃ [Bug] Crash when using Firefox Nightly Search through pwa - libc.so@0x4b7f0 | dalvik-main space (region space)_4384_4384 (deleted)@0x3689d60b

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#11586]
## Steps to reproduce
1. Install twitter as pwa.
1. Open twitter pwa.
1. Tap on a tweet.
1. Long tap on a word from the tweet and move the handles so that you can select more than one word.
1. From the context menu choose option "Firefox Nightly Search". 
    1. Expected behavior
New tab is opened with the tweet.
    1. Actual behavior
Crash is present.
    1. Device information

* Android device: Samsung Galaxy S9 (Androdi 8)
* Fenix version: Nightly 6/15

### Crash Information
Crash ID: 269d3791-8201-4176-8ee6-039c8c725845
Socorro link1: https://crash-stats.mozilla.org/report/index/8836c4c3-7fb2-4b6c-a8b9-9be2e0200615 
Socorro link2: https://crash-stats.mozilla.org/report/index/d366a001-10bb-41bd-a28b-dd5d30200615
[Logcat-Crash-Samsung.txt](https://github.com/mozilla-mobile/fenix/files/4778869/Logcat-Crash-Samsung.txt)

Note:

* In case you do not reproduce from the first try then make a search after one word, and repeat step 4, the crash will happen at some point, reproducibility rate 4 out of 5.
* It's a regression from issue: 9056

**Comment by kbrosnan** [comment]
Looks like BZ-1644561

**Comment by kbrosnan** [comment]
@Diana-Rus please retest on Monday or later. A fix was checked in today.

**Comment by Diana-Rus** [comment]
Hi, issue is fixed, no crash encountered, rechecked on Firefox Beta 79.0.0-beta.2 AS 61.0.6 and Firefox Nightly 6/30 with 
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3 XL (Android 9)
A new tab with the search of the text through default search engine is opened.
