### ISSUE TITLE
[Bug] Force closing Fenix after disabling an Add-on uninstalls it

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11589]
## Steps to reproduce
1. Tap to install any Add-on
1. While the web extension is installed and verified wait for approx. 2 seconds
1. Force close Fenix from the Android Task manager
1. Resume Fenix and open the Add-ons manager
1. Open the previously installed Add-on
1. Quickly:
Enable "Run in private browsing"
Disable the Add-on
1. Force close Fenix as soon as the disable confirmation snackbar is displayed
1. Resume Fenix and check the Add-ons manager

### Expected behavior
Step 8: The Add-on **should remain installed** and **disabled**

### Actual behavior
Step 8: The Add-on is uninstalled

### Device information
* Android device: 
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly build 200615 from 6/15

### Notes
❗ **M3s also affected**

► Video
![20200615-115419-2](https://user-images.githubusercontent.com/51314259/84639178-b208bf80-af00-11ea-9cf0-9a3a9c42d95e.gif)

**Comment by Amejia481** [comment]
We opened a bug for the gv team to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1646530

**Comment by AndiAJ** [comment]
**Still reproducible** on **`Firefox 87.0.0 Beta 3`** using a OnePlus A3 (Android 6.0.1)

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 (Android 9) with Firefox Nightly 93.0a1 2021-09-07
