### ISSUE TITLE
[Bug] Back navigation on newly opened tab opens another tab

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#11596]
## Steps to reproduce
1. Open a new tab
1. Open top site 1 (or simply navigate to a page, just an example)
1. Oh no, I actually wanted to open top site 2, press back

### Expected behavior
Goes back to new tab page, closing top site 1. I can now open top site 2 in that tab.

### Actual behavior
A new tab is opened, top site 1 is still open in the background.

### Device information
* Android device: Samsung Galaxy A50
* Fenix version: Nightly 200615 06:01

**Comment by tortino** [comment]
Yes, pressing back should close the tab. With the current behavior I end with lots of unwanted tabs, that I have to manually close.

**Comment by 424344** [comment]
so is this definitely closed?   :-(
