### ISSUE TITLE
FNX-4836 ⁃ The library bar still visible when video goes into full screen mode

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#1159]
STR:

1. Go to http://www.bbc.com/persian/iran-47646963.
1. Play the video and make it full screen. Make sure to do it when the library bar is still visible on the screen.

Screenshot: http://i65.tinypic.com/15ytf81.png

**Comment by yoasif** [comment]
On YouTube, I don't have to make the library bar visible (well, not open at least, I see the "grab handle" lookalike widget. 

https://m.youtube.com/watch?v=vxC1lYlmw1Q

![signal-attachment-2019-03-22-223646](https://user-images.githubusercontent.com/152493/54860621-2dc28f00-4cf3-11e9-94c5-5feeae38aa7b.png)
![signal-attachment-2019-03-22-223643](https://user-images.githubusercontent.com/152493/54860622-2dc28f00-4cf3-11e9-886f-bd864941ecae.png)
