### ISSUE TITLE
[Bug] Search bar can't handle space between words of a URL

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11594]
since I use texpand and to have my search engine in all browser I use I found a very annoying bug with fenix.
let's input http://www.apkmirror.com/?s=whatsapp beta in url bar
and fenix instead of loading that very url it performs a search with defaul search engine.
old Firefox or any other browsers I aver tried has never had that odd behavoiur.

**Comment by apbitner** [comment]
Fenix does seem to be the outlier here, no objection from UX.
