### ISSUE TITLE
FNX2-13535 ⁃ Quick double tap on tab switcher to open a new tab

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#11598]
### What is the user problem or growth opportunity you want to see solved?
I want to quickly open a new tab.

### How do you know that this problem exists today? Why is this important?
If I'm in an open tab and want to open another tab, after tapping the tab switcher I have to wait a moment until the tab tray expands and the new tab button appears. It would be nicer if the new tab button appeared immediately, so I wouldn't have to pay attention to time my second tap correctly.

### Who will benefit from it?
Users who want to open a new tab from an open tab.

**Comment by Octoton** [comment]
If you hold on the tab switcher button a new tab button will be show, at least on nightly

**Comment by miDeb** [comment]
I know, but double tapping would be easier IMHO.

**Comment by Mugurell** [comment]
This would introduce a mirroring issue:
Let's say you want to change a tab.
The app has to wait a little bit (~300 ms?) to allow for a second tap on the tab switcher in the event that the user intends a double tap.

**Comment by miDeb** [comment]
Sorry for not being clear, I didn't mean that the tab switcher should wait for a double tap, but that the new tab FAB should appear sooner. Currently, it doesn't show up until the tab tray has fully expanded. Fennec for example shows the new tab button immediately, and the second tap of the double tap already hits the new tab button.

**Comment by AmyYLee** [comment]
@miDeb Hi, I'm looking into this and the new tab FAB appears as soon as you tap on the open tabs icon. It's one animation of the new tab tray appearing with the FAB icon. I'm not sure if I'm understanding the issue.

**Comment by miDeb** [comment]
Thank you @AmyYLee. Let me try to explain this again: In fennec, if I double tap on the tab icon, it opens a new tab because the new tab button appears immediately after the first tap on the position of the tab icon. In fenix the new tab button doesn't appear _immediately_ so you can't double tap on the tab icon, but you have to wait a moment and then tap again. I don't know if it is possible to show the new tab button earlier, if not, feel free to close this issue. Here is a screen recording (slowed down 5x) of [fennec](https://drive.google.com/file/d/1VR2hHBVQNaCZK2IfzzqvUobi0sBCPI17/view?usp=drivesdk) and [fenix](https://drive.google.com/file/d/1VXp7m1O-cH_ebYy6cHtvFVNcSgYWB2Dm/view?usp=drivesdk).

**Comment by AmyYLee** [comment]
@miDeb Thanks for explaining. I reviewed both versions on my phone and there is a slight delay in Fenix. I'm not sure if it's delayed enough to make any major changes to the animation. Basically the new tab icon slides up along with the panel. I would like to keep the icon consistent with the motion of the panel unless we want to speed up the panel altogether. I will let nicole make the final call @topotropic

**Comment by topotropic** [comment]
Thanks for the screen recording @miDeb; 

I agree with Amy, makes sense to keep the animation consistent. I'll close the issue.

**Comment by Mugurell** [comment]
Closing as per topotropic's comment.

**Comment by IdmFoundInHim** [comment]
Though double tap may not be the right solution, this is still an inconvenience. What about a swipe up on the tab button for a new tab? @Mugurell @AmyYLee

**Comment by DavidBE-UK** [comment]
Also no consideration is being given to the User Experience when toolbar is set to 'top', where the tap on the tab switcher is at the top of the screen, but the new tab FAB is all the way down at the bottom. The entire tab tray experience is designed solely for people with Toolbar Bottom set, and is a mess when toolbar top is set. The tab switcher UI should change when toolbar top is set in an appropriate way; or just cut the toolbar top option and commit to being a bottom control browser only. The current state where the choice is not between bottom controls and top controls but between bottom controls and a half-and-half mash up is just an unpleasant mess that looks like an afterthought kludge designed by people who love bottom controls and forget there's supposed to be a top option too during the planning stage.
