### ISSUE TITLE
FNX-12563 ⁃ [Bug] Pressing back in a tab goes to the home screen instead of the app that opened the tap

### ISSUE THREAD

**Issue by XXorro** [mozilla-mobile/fenix#11597]
## Steps to reproduce
Using Google Search, Google Now configured with Firefox as default browser.
Find item in Google, tap item, item opens in Firefox. close tab, browser resorts to tabs page but does not close. 

### Expected behavior
Page would close and activity return to invoking Google page.

### Actual behavior
Firefox falls back to Tabs page.

### Device information
Sony Xperia M5, Z5

* Android device: ?
* Fenix version: ? Firefox Preview 5.1.1
see: https://www.reddit.com/r/firefox/comments/h9ekwt/closing_behaviour_of_firefox_for_android_preview/  for longer description

**Comment by sheikh-azharuddin** [comment]
Similar to my issue

**Comment by kbrosnan** [comment]
Dupe #10394
