### ISSUE TITLE
FNX-12574 ⁃ Annecdotal delay when clicking URL bar to open search screen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11607]
On my P2, there's noticeable delay when clicking the URL bar to open the search screen. If I can notice it on the P2, it's likely not meeting our RC on this device and especially not on low-end devices. We should:

* Measure the duration
* Share results with mcomella & esmyth: if it's concerning, we should make improvements in this issue

**Comment by hwinnemoe** [comment]
Related to/duplicate of #8795?

**Comment by mcomella** [comment]
> Related to/duplicate of #8795?

@hwinnemoe Perhaps – does this delay happen every time you click the URL bar or only the first time? If it's the first time, that's #9935. If it's every time, then yes this is a dupe.

**Comment by mcomella** [comment]
I took a profile: https://share.firefox.dev/30SjayZ Interesting things initially:
- From `dispatchTouchEvent` to inflating the view, there's a 100ms delay but nothing relevant & significant appears to happen during that time. It's as if there is a scheduling delay
- After we layout & draw, `consumeFrom` runs and we do another layout + draw: I wonder if this delays anything (this seems like an anti-pattern: we should run this synchronously if possible)
- showKeyboard gets called in a loop: how does this affect the performance of this view?

**Comment by hwinnemoe** [comment]
> @hwinnemoe Perhaps – does this delay happen every time you click the URL bar or only the first time? If it's the first time, that's #9935. If it's every time, then yes this is a dupe.

Yes, the delay happens every time. Thanks for looking into this, it is one of the more major usability regressions I noticed when moving over to Fenix.

**Comment by mcomella** [comment]
Dupe https://github.com/mozilla-mobile/fenix/issues/8795
