### ISSUE TITLE
Investigate in eliminating IntentReceiverActivity

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#11608]
### What is the user problem or growth opportunity you want to see solved?
Currently `IntentReceiverActivity` is registered to handle shortcuts and view intents.  However, on slower devices such as Motorola G5 the delay is ~100ms to redirect the intent to the target activity.

Investigate into eliminating `IntentReceiverActivity` so the target activity can receive the intent directly.

### How do you know that this problem exists today? Why is this important?
This was discovered by the performance team.

### Who will benefit from it?
User with slow device will benefit from faster load time.

**Comment by rocketsroger** [comment]
Created due to https://github.com/mozilla-mobile/fenix/issues/10942

**Comment by rocketsroger** [comment]
After some more discussions related to this issue there are some reasons that we're not moving forward with this change.  The risk is very high and there are dependencies with other functionalities such as intent processors.  It could be that a better/safer way is to improve the performance of the current implementation.

**Comment by MarcLeclair** [comment]
The perf team has found (from this investigation https://github.com/mozilla-mobile/fenix/issues/19805) that the bottle neck for  loading a page from Cold VIEW (App link) comes from how early and how long GV starts and when `loadUrl` is called. Therefore, removing `IntentReceiverActivity` probably won't affect the time loading a page takes. It may affect time to first frame, but that isn't a priority for us at this time.
