### ISSUE TITLE
[Bug] pages not loading with error address not found

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11603]
## Steps to reproduce
Sometime while page is loading switch from mobile data to wifi or vice versa. You will notice negative response is cached with error address not found. I tried searching through Google also even on clicking on search result getting same error.

### Expected behavior
Page should load properly

### Actual behavior
Page not loading with error address not found

### Device information
* Android device: ? A10
* Fenix version: ? Latest

![Screenshot](https://user-images.githubusercontent.com/58127841/84691523-d3cf6a00-af33-11ea-87bc-dc2ddcf7e4c9.jpg)UNITO-UNDERSCORE!20200615-233555!

**Comment by sheikh-azharuddin** [comment]
I have captured a video to prove..how to upload video?

**Comment by ekager** [comment]
@sheikh-azharuddin are you still seeing this? You can upload a gif to the issue if possible

**Comment by sheikh-azharuddin** [comment]
Issue resolved
