### ISSUE TITLE
FNX-12566 ⁃ [Bug] The url bar appears when using Picture in Picture

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#11600]
## Steps to reproduce
1. Go to https://www.youtube.com/.
1. Watch a Video in fullscreen;
1. Press the device home button.
    1. Expected behavior
Only the video is shown in Picture in Picture mode.
    1. Actual behavior
The url bar is shown when using Picture in Picture
    1. Device information

* Android device: OnePlus 6T (Android 9), Huawei P Smart (Android 9)
* Fenix version: FIrefox Preview Nightly 200615 (Build #21670608)
![Screenshot](https://user-images.githubusercontent.com/50983519/84676171-d7fc8700-af35-11ea-8a9f-687deafd46d0.jpg)UNITO-UNDERSCORE!20200615-181858!

**Comment by ekager** [comment]
cc @NotWoods do we think this is related to changes in https://github.com/mozilla-mobile/fenix/pull/11539/ ? We need to make sure we stay in fullscreen/the toolbar stays hidden for PiP

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest Firefox Preview Nightly Build 200616 (Build #21680610)

### Device information
- OnePlus 6T (Android 9)
- Huawei P Smart (Android 9)
