### ISSUE TITLE
FNX2-13536 ⁃ [Bug] Sign in into Sync via scan broken

### ISSUE THREAD

**Issue by eamsen** [mozilla-mobile/fenix#11602]
## Steps to reproduce
1. Turn on Sync.
1. Ready to scan.
1. Scan QR code from Firefox desktop (78b6).

### Expected behavior
Sign in is successful.

### Actual behavior
Error: `Missing OAuth parameter: channel_id`.

### Device information
Pixel 3 on Android 10.
Fenix version: Nightly 200614.

**Comment by vladikoff** [comment]
> Actual behavior
>Error: Missing OAuth parameter: channel_id.

@eamsen
Did you get this error in Firefox Desktop or Fenix?
Do you have any extensions installed, especially something that changes URLs?

**Comment by eamsen** [comment]
> > Actual behavior
> > Error: Missing OAuth parameter: channel_id.
> 
> @eamsen
> Did you get this error in Firefox Desktop or Fenix?
Fenix.

> Do you have any extensions installed, especially something that changes URLs?
No add-ons installed, it's a fresh install (cleaned data on Android).

**Comment by vladikoff** [comment]
@eamsen 
Could try the scan procedure, then when you get to the error page, use the "..." menu to do "Open in Firefox Nightly", this will open the scan page with a **url bar**, check what the url bar:

mine is: 
> https://accounts.firefox.com/pair/supp/allow?client_id=a2270f727f45f648&scope=profile%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Ftokens%2Fsession&state=179ca3qnfndJHO2hCSbyQg&code_challenge_method=S256&code_challenge=...&access_type=offline&keys_jwk=....&context=oauth_webchannel_v1#channel_id=[ID_HERE]&channel_key=[KEY_HERE]

Compare what you get VS what you see in my url, any oddities? 

Example:
![scan](https://user-images.githubusercontent.com/128755/84686694-71ae3f00-af0a-11ea-864c-794f79baca6f.gif)

**Comment by eamsen** [comment]
The URL is missing the `channel_id` and `channel_key` arguments, it ends with `context=oauth_webchannel_v1`.

**Comment by vladikoff** [comment]
@eamsen could you please tell me where you scanned the code from?

Was it from  `about:preferences?action=pair#sync` page:


![image](https://user-images.githubusercontent.com/128755/85429721-27057600-b54d-11ea-868e-19707d57293a.png)


Or an accounts email or accounts page?

**Comment by eamsen** [comment]
https://accounts.firefox.com/post_verify/cad_qr/scan_code?context=fx_desktop_v3&entrypoint=fxa_app_menu&service=sync&uid=&email= 
on Firefox 79b1.

**Comment by vladikoff** [comment]
> Triggered on about:preferences#sync:
> https://accounts.firefox.com/post_verify/cad_qr/scan_code?context=fx_desktop_v3&entrypoint=fxa_app_menu&service=sync&uid=&email=
> (uid and email redacted) on Firefox 79b1.

Hi @eamsen, this is not the right QR code to scan. Follow the instructions in Fenix and use the https://firefox.com/pair url to get the pairing code.

**Comment by eamsen** [comment]
Thanks, indeed, with the pair link this issue is not reproducing. We should fix the desktop link in this case for users (like me) who initiate the linking on desktop rather than following the instructions on Fenix.
