### ISSUE TITLE
FNX-4838 ⁃ Password autofill sometimes returns to Fenix home screen instead of the initiating page

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/fenix#1160]
I've seen this multiple times, but I can't reproduce it with perfect consistency. I'm sorry. Related to #87.

In my case, I'm using Bitwarden as a password manager.

## Steps to reproduce
1. Open a private tab and navigate to a login page
(I've only seen it happen on private pages, but possibly unnecessary.)
1. Tap the password field
1. Tap "Auto-fill with Bitwarden"
1. Find and select an appropriate entry
(Note that this doesn't work entirely correctly; see https://bugzil.la/1538385)

### Expected behavior
1. I'm returned to the originating page with my username and password filled in.

### Actual behavior
1. I'm returned to Fenix's Private Mode home screen.
Upon selecting my previously open tab, no information is filled in.

### Device information
* Android device: Pixel (original)
* Fenix version: 1.0.1912 (Build #10811221 :lizard: 67.0a1-20190312095443)

**Comment by ekager** [comment]
Have you continued to see this issue?

**Comment by callahad** [comment]
No, I have not encountered this recently

**Comment by ekager** [comment]
Okay, closing for now then please reopen if you see this again!
