### ISSUE TITLE
FNX2-13540 ⁃ Leanplum attribute 'Signed into FxA' is not updating when expected

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#11610]
The following attribute was identified as not updating when expected Fenix during a recent test by the Mobile Engagement team.

* [ ] Signed into FxA

This is shown as "complete" in Mobile Engagement team documentation, but this is not shown (to my knowledge) in the original Meta that was listed for it ([#4421](https://github.com/mozilla-mobile/fenix/issues/4421)).

Tasks:

* [x] Understand if Leanplum attribute 'Signed into FxA' exists
* [ ] If it exists, understand what triggers the change in the attribute from "false" to "true". If it does not exist, create the attribute so that it changes from "false" to "true" upon successful sign in to an FxA account.
* [ ] Undergo data review
* [ ] Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

This needs to be added to the [Mobile Engagement :heart: Fenix project](https://github.com/mozilla-mobile/fenix/projects/48#card-39585660). I do not have access to add it myself.

**Comment by jhugman** [comment]
An attribute, [`fxa_signed_in`]]1] exists in fenix. As an attribute, it Fenix reports to LeanPlum _only_ at cold startup. Is this what you expected, and it's not getting updated after a cold restart?

There is an event, [`E_Sign_In_FxA`][2] which may give you the results you're looking for. If you're seeing more `fxa_signed_in` attributes than would be accounted for by `E_Sign_In_FxA`, you may want to count FxA QR code pairings, signups or using the same credentials as Fennec all as `E_Sign_In_FxA` events.

@cbonacuse we can change this issue to log more signin events, or if it is updating after a cold restart close this. If it's not, then there's the possibility of a deeper problem, but I'd like to check your intentions before diving into that theoretical problem.

[1]: https://github.com/mozilla-mobile/fenix/blob/e318cd7d1561db000adfdd3c1afb2bf97dc0f5eb/app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt#L109
[1]: https://github.com/mozilla-mobile/fenix/blob/e318cd7d1561db000adfdd3c1afb2bf97dc0f5eb/app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt#L37

**Comment by cbonacuse** [comment]
@jhugman thank you for clarifying. This issue likely needs to be changed. 

I have tested the attribute fxa_signed_in and it worked for me and changed, but yes I would like to have the attribute changed to 'true' and the event E_Sign_In_FxA fired for the same credentials (QR code pairings, signups [if we cannot create a separate signup event] and email). So ideally, logging more signin events if they are not already logged. Let me know how you'd like to proceed and I can make the updates. Thanks!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly 200806`** and **`Beta 80.0.0-beta.3`** using a Google Pixel 3a (Android 10)

## Nightly - Device ID **`fdd9324a-dc99-4461-90da-7a925b396cad`**
✔️ Signed in using the sign in card from the onboarding screen
![image](https://user-images.githubusercontent.com/51314259/89526583-a5ae2e00-d7f0-11ea-83a5-1befdf10134c.png)

✔️ Sign in with existing account
![image](https://user-images.githubusercontent.com/51314259/89527287-c1660400-d7f1-11ea-8cae-3b5beab1b122.png)

✔️ Pairing 
![image](https://user-images.githubusercontent.com/51314259/89527564-2f123000-d7f2-11ea-8538-d4927c075243.png)

✔️ Sign up new account
![image](https://user-images.githubusercontent.com/51314259/89528061-11919600-d7f3-11ea-9db0-9948b9267ddf.png)



## Beta - Device ID **`d4af3353-0731-401c-8af2-178ca955fe2c`**
✔️ Migrated while being signed in
![image](https://user-images.githubusercontent.com/51314259/89518991-5f52d200-d7e4-11ea-8104-cf63295ba103.png)

✔️ Sign in with existing account
![image](https://user-images.githubusercontent.com/51314259/89519173-9cb75f80-d7e4-11ea-8009-56110b556578.png)

✔️ Pairing 
![image](https://user-images.githubusercontent.com/51314259/89519313-d38d7580-d7e4-11ea-8f86-8dd7258b69f1.png)

✔️ Sign up new account
![image](https://user-images.githubusercontent.com/51314259/89519490-1d765b80-d7e5-11ea-9e11-ed4d0d15fac4.png)
