### ISSUE TITLE
FNX-12580 ⁃ Leanplum attribute 'Signed In Sync' is not present in Leanplum UI

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#11611]
The following attribute was identified as not appearing in Leanplum UI during a recent Fenix test by the Mobile Engagement team. We tested this by signing in an FxA account but this was not an attribute present on the list of attributes under our device ID in Leanplum. 

* [ ] Signed In Sync

This is shown as "closed" in two separate Github tickets:

1. [[Meta] Integration of Leanplum Events, Attributes & Deeplinks|https://github.com/mozilla-mobile/fenix/issues/4421]
1. [Create a Fenix Leanplum Attribute that tells us whether a user has any Sync engines enabled (Next Phase)](https://github.com/mozilla-mobile/fenix/issues/3060)

Tasks:

* [ ] Understand if Leanplum attribute 'Signed In Sync' exists
* [ ] Understand difference between 'Signed In Sync' and 'Signed into FxA'
* [ ] Based on the difference in the code between 'Signed In Sync' and 'Signed into FxA', define how we want it to change from "false" to "true"
* [ ] Undergo data review
* [ ] Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

This needs to be added to the Mobile Engagement :heart: Fenix project. I do not have access to add it myself.

**Comment by jhugman** [comment]
The attribute [`fxa_signed_in`][fenix] exists in Fenix, and [`Signed In Sync`][fennec] in Fennec.

AFAIK, from a product p.o.v. **sync** as a product is now named **Firefox Accounts**.

From an engineering p.o.v. we can change it to match Fennec, or we can close this comment?

[fenix]: https://github.com/mozilla-mobile/fenix/blob/e318cd7d1561db000adfdd3c1afb2bf97dc0f5eb/app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt#L109
[fennec]: https://searchfox.org/mozilla-central/source/mobile/android/docs/mma.rst#65

**Comment by cbonacuse** [comment]
@jhugman thank you for clarifying. I just tested on my device in Preview and I do indeed see fxa_signed_in = True after signing in + a cold start. This can be closed. Thanks!
