### ISSUE TITLE
FNX-12599 ⁃ All PWA's and some sites are cut off at the top or the bottom. Possible reason included.

### ISSUE THREAD

**Issue by vishalnandagopal** [mozilla-mobile/fenix#11629]
## Site with issue and any steps to reproduce
Install any PWA and open it. Example - PWA of duckduckgo.com 

### Expected behavior
When we open the PWA, it opens like a normal app

### Actual behavior
It is cut off at the top.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No. Fenix specific.

### Device information
* Android device: 10
* Fenix version: Latest Nighty

Why does happen? - Due to minimising the toolbar at the bottom. The exact same amount of space is cut off at the top.

Because PWA don't have toolbars, there is an empty space. This issue is happening only after the update to minimize toolbar when scrolling down was introduced.

Minimising toolbar when scrolling normal web content is causing problems in PWA too?

**Comment by SS1113** [comment]
This has already been reported here #11545 and here #11521.
