### ISSUE TITLE
`Session.notifyObservers` -> `shouldShowOpenInApp` is expensive (21ms)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11628]
STR:

* Click url bar
* Type query
* (start profiler)
* Select result from history suggestions

`Session.notifyObservers` calls `DefaultToolbarMenu.shouldShowOpenInApp` which eventually calls down to `android.app.ApplicationPackageManager.queryIntentActivities`, which takes a non-trivial amount of time to run on low-end devices.

It takes 21ms in this profile: https://share.firefox.dev/3hsdXnv

These profiles are taken on a Galaxy S5, fennecNightly build, local 3535bec with local a-c 8839a884fcdba9de71913b4b0995395aff6536b0 (June 15)

I'm concerned that **this code can get run in many places** because it's called as an observer: we should find out if that's the case and fix it if so (or just fix it). `queryIntentActivities` and possibly other package manager calls, it seems, should always be called on a background thread.

I also see a few other calls to the package manager in this profile (including two session observer notifyObservers calls): https://share.firefox.dev/2B81zs6 We should eliminate all of them or file a follow-up.

**Comment by mcomella** [comment]
Triage (by myself): this doesn't appear to slow down page load – it happens in response to the isLoading event – so low impact.

**Comment by csadilek** [comment]
`DefaultToolbarMenu.shouldShowOpenInApp` is no longer called as part of any observer. I only see one call to `queryIntentActivities` when the `ShareFragment` is launched, so I think we can close this now.
