### ISSUE TITLE
FNX-4839 ⁃ Long URLs cause Fenix to become unresponsive for tens of seconds

### ISSUE THREAD

**Issue by callahad** [mozilla-mobile/fenix#1162]
## Steps to reproduce
1. Visit `about:version` or tap Menu → Settings → About Fenix
(This is automatically replaced by a large `data:` URI.)
1. Tap on the URL bar

### Expected behavior
1. The URL bar pops up and is ready for input.

### Actual behavior
1. Fenix becomes unresponsive for 20 seconds. The URL bar and search suggestion pages _s l o w l y_ load into view, piece by piece.
This appears to get worse the more times I reproduce it.

### Device information
* Android device: Pixel (original)
* Fenix version: 1.0.1912 (Build #10811221 :lizard: 67.0a1-20190312095443)

**Comment by callahad** [comment]
...I'll also note that now whenever I try to type "data", "html", "text", or a similar substring from the long `data:` URI, Fenix becomes completely unresponsive for several seconds.

**Comment by boek** [comment]
Logged handling very long URLs in the Awesomebar here: mozilla-mobile/android-components#2534
