### ISSUE TITLE
FNX2-13546 ⁃ Investigate main thread perf implications of Lottie

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11627]
When filing https://github.com/mozilla-mobile/fenix/issues/11623, I took two profiles of the STR:

* Open app
* Click URL bar & type to show search results from history
* (start profiler)
* Click result from history

And Lottie showed up in both profiles, in different ways:

* `LottieTask.addListener` - 104ms (waiting on `android.content.res.AssetManager.openXmlAssetNative` though; as part of `BaseBrowserFragment.onViewCreated`) https://share.firefox.dev/2BbDkJz
* `LottieTask$1.run` ~~> `LottieTask.notifySuccessListeners`~~  13ms https://share.firefox.dev/30LICpC

These profiles are taken on a Galaxy S5, `fennecNightly` build, local 3535bece5a778222b39ef085ca7c49529d15c76a with local a-c 8839a884fcdba9de71913b4b0995395aff6536b0 (June 15)

I'm not really sure what Lottie's doing but it seems to have more negative main thread performance implications than using a animated drawable: https://github.com/mozilla-mobile/fenix/issues/7435 **When does it run?** How long does it usually take? We should find out.

**Comment by mcomella** [comment]
https://github.com/mozilla-mobile/fenix/issues/7435 already exists to remove Lottie for APK size reasons.

**Comment by mcomella** [comment]
In this profile on the GS5 https://share.firefox.dev/2Ce8Erz, Lottie takes 55ms when clicking a history suggestion on the search screen and launching into the browser.

**Comment by rpappalax** [comment]
> #7435 already exists to remove Lottie for APK size reasons. It sounds like it will happen when we get the UX resources to determine an alternative so perhaps we should not waste our time on this investigation if we want to get rid of it anyway. What we find could be a catalyst for its removal though.
@mcomella do you know who in UX I might reach out to?

**Comment by mcomella** [comment]
@rpappalax I don't know – I don't have any connection to the UX team. Maybe @liuche or @boek can point you in the right direction.

**Comment by mcomella** [comment]
Dupe https://github.com/mozilla-mobile/fenix/issues/7435 – I don't think we need two issues to raise concerns about Lottie. :)
