### ISSUE TITLE
FNX-12596 ⁃ [Bug] Tabs tray stays open when clicking links from other apps

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11625]
## Steps to reproduce
* Open the tabs tray
* Press the home button
* Click a link from another app that will open Fenix _that isn't a custom tab_

### Expected behavior
Page loads, tabs tray is closed

### Actual behavior
Tabs tray is open. It looks a little unpolished and gets in the way of the users intended action

### Device information
* Android device: P2
* Fenix version: Nightly 200615

**Comment by sheikh-azharuddin** [comment]
I have reported this....like other browsers it should ideally open in the custom tab and on cliking back should take back to the original app from where link was  clicked leaving no trace....but currently it opens directly in the browser and when you click back it goes back but the tab remains in recent app panels....when you click it either it stays or shows a white blank screen

**Comment by darkwing** [comment]
@boek I don't have a phone with a back button, can you check this out?

**Comment by sheikh-azharuddin** [comment]
> @boek I don't have a phone with a back button, can you check this out?

The Behaviour is same if you use back navigation gesture 😛
Infact I am using A10 gestures

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video Fenix not set as default browser
![20200619-102251](https://user-images.githubusercontent.com/51314259/85108268-189b1f80-b218-11ea-9c60-a6908ad6c651.gif)

► Video Fenix set as default browser
![20200619-102420](https://user-images.githubusercontent.com/51314259/85108386-5009cc00-b218-11ea-9b35-60c3243d7417.gif)

**Comment by sheikh-azharuddin** [comment]
Please reopen the case...issue not fixed properly
It leaves a blank screen in recent app panel...

![ScreenRecord-20200619-181025](https://user-images.githubusercontent.com/58127841/85136155-bf8ab600-b22e-11ea-945b-4ca9c8977129.gif)

**Comment by mcomella** [comment]
@sheikh-azharuddin The screenshot of Fenix being blank in the recent tab switcher seems unrelated to this issue: assuming you agree, can you file a new one?

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin The screenshot of Fenix being blank in the recent tab switcher seems unrelated to this issue: assuming you agree, can you file a new one?

But why file a new one...it is fixed now...
