### ISSUE TITLE
Suggestion: Hide advanced settings in developer options (about:config, sideloading, etc.)

### ISSUE THREAD

**Issue by esjarc** [mozilla-mobile/fenix#11639]
### What is the user problem or growth opportunity you want to see solved?
Currently there are ongoing discussions between users and developers about which Fenix channels should receive what features (e. g. [about:config](https://github.com/mozilla-mobile/fenix/issues/7865), [sideloading](https://github.com/mozilla-mobile/fenix/issues/11308)). To solve these issues and make advanced features available in every Fenix branch, I want to suggest the addition of (hidden) developer options, where the user is able to toggle these features on or off. Other browsers, e. g. Chromium, and the Android operating system itself already have hidden developer options, so this is a familiar feature for advanced Android users already and as far as I know these features have not caused damage to normal users of said programs.
These settings should at least include an option to enable about:config. Ideally there should also be preferences for enabling unsigned extension sideloading and some kind of debugging features (if needed).

### How do you know that this problem exists today? Why is this important?
There is a certain demand for advanced configuration options and features, which you can see in several issues across this issue tracker. Even though these features might not be useful for most users, they are an integral part for many Firefox fans, advanced and long-time users (which also recommend browsers to less tech-savvy people) and this functionality has existed for years already on Android (Fennec). It helps to make the migration smoother for all groups of users and prevents certain people from no longer upgrading their Firefox browser on Android or switching to other browsers that offer missing functionality (→ loosing more marketshare).
It also enables the possibility to revert about:config entries, which had been changed in Fennec, after upgrading to Fenix.

### Who will benefit from it?
Anyone with needs that exceed the needs of the average Firefox user and anyone that can't use Fenix because of missing preferences or walled gardens. Also developers (e. g. web developers, security researchers, maybe extension developers) who want to test certain features in all Fenix channels before shipping them to the end-user.

### How does a similar feature look in other browsers?
![Screenshot](https://user-images.githubusercontent.com/53082773/84776231-5877c200-afe0-11ea-8088-79af9a137443.png)UNITO-UNDERSCORE!20200616-143315!![Screenshot](https://user-images.githubusercontent.com/53082773/84776232-59105880-afe0-11ea-9b4b-f1ce61978986.png)UNITO-UNDERSCORE!20200616-143341!![Screenshot](https://user-images.githubusercontent.com/53082773/84776233-59105880-afe0-11ea-903d-8a061378857e.png)UNITO-UNDERSCORE!20200616-143343!![Screenshot](https://user-images.githubusercontent.com/53082773/84776235-59a8ef00-afe0-11ea-9f70-a0601c181296.png)UNITO-UNDERSCORE!20200616-143358!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2220)

**Comment by SS1113** [comment]
I think they should just handle the add-on side-loading behaviour like how they handle it on desktop Firefox. 

And I really don't think that it's s good Idea to hide add-on side-loading setting in a hidden menu. It should be somewhere in the settings. `about:config` is a different matter it directly introduces browser breaking changes if wrong settings/options are turned on; this happened to me on Chrome browser.

**Comment by filips123** [comment]
`about:config` should still be supported on all Fenix channels. It is very useful if you want to change advanced settings, configure some features, maybe change some privacy or experimental features...

If it has clear warning when it is opened that changing some preferences can result in breakage or security issues (like it has on desktop), most users will understand.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813621

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
