### ISSUE TITLE
[Bug] On Add-ons submenu, "Report site issue" is not necessary

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#11631]
## Steps to reproduce
1. Install at least one add-on
1. Go to any webpage
1. Open main menu → Add-ons submenu

### Expected behavior
“Report site issue” should not be seen in this submenu. If anything, it should be put inside the main menu itself.

### Actual behavior
“Report site issue” is seen in the Add-ons submenu.

**Comment by cadeyrn** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1643144

**Comment by pocmo** [comment]
(The webcompat reporter is an add-on nowadays)

**Comment by apbitner** [comment]
'Report site issue' was supposed to be in the main menu, as shown here - https://share.goabstract.com/a5961d72-3d6b-4d7c-98cb-ef94ffbb5aa9

The add-ons submenu should be reserved for add-ons the user has installed/enabled manually.

**Comment by mcarare** [comment]
@denschub I've seen you comment in code regarding this feature. Is this still the case?
```
 "Report site issue" feature should stay disabled in Fenix Release builds for now.
```

**Comment by denschub** [comment]
@mcarare yeah. We might try running a short-time/limited-audience experiment on Release at one point, see https://bugzilla.mozilla.org/show_bug.cgi?id=1661165 - but we're not sure yet if this should be permanent. There are some things left we need to do before this is "release ready", including this bug, but also adding i18n.

**Comment by mcarare** [comment]
Submitted an AC issue: https://github.com/mozilla-mobile/android-components/issues/8593.

**Comment by mcarare** [comment]
UI test failures seem unrelated.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/21 with Google Pixel 3 (Android 11).
