### ISSUE TITLE
FNX-12601 ⁃ [Bug] On New Tab Page main menu, “Add-ons” is not necessary

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#11630]
## Steps to reproduce
1. Open Fenix new tab page
1. Open main menu
1. Notice that there’s a menu item called “Add-ons”

### Expected behavior
The “Add-ons” menu item should not be seen in the main menu of new tab page, for two reasons:

* NTP is not a type of page that add-ons can interact with
* NTP is not likely to be a moment in time when users think e.g. “I want to block ads”. This moment is more likely to happen while users view a webpage.

### Actual behavior
The “Add-ons” menu item is seen.

**Comment by cadeyrn** [comment]
In was intentionally added two weeks ago: #9696

> NTP is not a type of page that add-ons can interact with

That's true but it's not the same menu with submenu as on websites, it's only a link to the add-ons manager where the user can install add-ons.

**Comment by SS1113** [comment]
@brampitoyo it's a bad UX decision if you ask me (talking as a user). How do you expect users to know something like "add-ons" exist. Mozilla is keen on pushing "collections", "pocket articles", "synced tabs" and a permanent "What's new" entry for who know why, etc but add-ons are also an important part of Fenix and if you ask me a lot users will be switching browsers only because Fenix supports add-ons. 

And I don't have to open a webpage to manage add-ona and I don't want to dig settings for it either, making the add-ons entry at the home is necessary for easy add-on management.

**Comment by brampitoyo** [comment]
@cadeyrn @SS1113 If we do include “Add-ons” in the New Tab Page main menu – and you’ve both presented good arguments for it – then do you think that it should follow the same behaviour (as in, it should open the submenu if you have ≥1 add-ons installed), or should it always go to the Add-ons Manager?

If we follow the same behaviour, then it will lead to more consistency. But I’m also aware that most add-ons don’t work on “special” pages like the NTP, so seeing a list will not be helpful.

**Comment by SS1113** [comment]
@brampitoyo you are correct there's no need to make the same behaviour (sub menu) at the homescreen as it will confuse users if the add-ons don't work there.

I'm suggesting to keep the behaviour as it is now, clicking the **Add-ons** should just take to the add-ons manager.

 

I'd like to present another change to the three-dot menu items, do you think a permanent **What's New** botton is necessary? I don't think it is necessary once the users knows what's new in the update it should just disappear. 

I'm suggesting show the **What's New** button only when after the browser is updated and users click on it to view what's new in the update and hide it after that.

**Comment by brampitoyo** [comment]
@SS1113 Good points. Suggestions accepted, and I will close out this issue.

As for when to show or not show the “What’s New” menu item, will you file a new issue and CC @apbitner?
