### ISSUE TITLE
[Bug] Synced tabs is not translated in all browser languages

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#11646]
## Prerequisites
* Have browser language set to Albanina-Shqip
    1. Steps to reproduce

1. Go back until you can open the menu.
    1. Expected behavior
Synced tabs is translated.
    1. Actual behavior
Synced tabs is not translated. That goes as well when entering the Synced tabs page title but as well the text present on the page.
    1. Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 6/16

Note:

* It reproduces with other languages as well: Arabic, Estonian, Irish (Gaeilge), Esperanto, Rumantsch, Japanese, Lao, Romanian
* When Belarusian is set the "Connect with a Firefox Account" text.
* Related to: #11201

**Comment by liuche** [comment]
This should be fixed now, and I can see those translated strings in Nightly 10/20
