### ISSUE TITLE
FNX-12621 ⁃ [Bug] Tab tray first touch isn't registered

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#11648]
## Steps to reproduce
Have at least two apps
Switch one tab to another
Notice first touch not registered

### Expected behavior
Switches on first touch

### Actual behavior
Doesn't switch on first touch
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17825767/84809922-495e3780-b013-11ea-83fd-9ca40459c3c7.gif)

### Device information
* Android device: Xperia XZ1 Android 10
* Fenix version: 
Nightly 200615 06:01 (Build #21670608)
45.0.20200613130120, b4f036c83
GV: 79.0a1-20200612094620
AS: 60.0.0

**Comment by cadeyrn** [comment]
Duplicate of #11558.

**Comment by ekager** [comment]
Closing for  #11558

**Comment by hakkikaancaliskan** [comment]
@ekager @cadeyrn waow, faaaast :)
