### ISSUE TITLE
FNX-12622 ⁃ [Bug] Tabs require two clicks to switch between

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11649]
## Steps to reproduce
Not sure if it reproduces 100% always but I can reproduce 100% right now.

* Open tabs tray with multiple tabs
* Click different tab to open

### Expected behavior
Tabs switches

### Actual behavior
Nothing. Click again and tab opens.

### Device information
* Android device: P2, GS5
* Fenix version: 200616 Nightly

- - -
I only started noticing this happen today

**Comment by kbrosnan** [comment]
dupe #11558
