### ISSUE TITLE
FNX-12613 ⁃ [Bug] Update synced tabs view

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#11641]
https://github.com/mozilla-mobile/fenix/pull/11258#pullrequestreview-425532744

> Looking good, some small things:
> 
>     synced tabs view: device icons should align with the back arrow in the header (16dp left margin).
>     please add a full-width separator below the device name (color: light_grey_30 in light mode and dark_grey_10 in dark mode)
> 
> https://share.goabstract.com/d1d0bb78-03c9-4822-aea1-a553d2fd4944?mode=build&sha=72ed314cb3b094e510d264a18e99870147787fa0

cc @topotropic

**Comment by hakkikaancaliskan** [comment]
I'm working on this.

**Comment by hakkikaancaliskan** [comment]
Note to self:
In UI design phone icon is 24x24 but in ac 16x16.
https://github.com/mozilla-mobile/android-components/blob/master/components/ui/icons/src/main/res/drawable/mozac_ic_device_mobile.xml

**Comment by ekager** [comment]
This has been updated! Closing
