### ISSUE TITLE
FNX2-13556 ⁃ Add new Leanplum ETP Setting Attribute

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#11657]
The following attribute was identified as a priority for Fenix during a recent test by the Mobile Engagement team. 

* [x] ETP Setting

This should have the value of the setting (Standard, Strict or Custom) of Enhanced Tracking Protection (Standard is default in the app). This value should be null if ETP setting is off.

![](https://user-images.githubusercontent.com/60749496/84822210-53b80b80-afea-11ea-8f7d-6194660f913b.png)

Tasks:

* [x] Create attribute: ETP Setting
* [ ] Undergo data review
* [ ] Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

This needs to be added to the [Mobile Engagement :heart: Fenix](https://github.com/mozilla-mobile/fenix/projects/48#card-39585660) project. I do not have access to add it myself.

**Comment by bifleming** [comment]
Work is complete
