### ISSUE TITLE
FNX-4842 ⁃ Create UI for Doorhanger be shown when the toolbar padlock is clicked

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1165]
![image](https://user-images.githubusercontent.com/773158/54921981-8a819d80-4edd-11e9-90a4-4dbc84a44e3f.png)

**Comment by Amejia481** [comment]
Related issues: https://github.com/mozilla-mobile/fenix/issues/1258 and https://github.com/mozilla-mobile/fenix/issues/1257

**Comment by sv-ohorvath** [comment]
Logged issues:
#1409 
#1410
#1411
