### ISSUE TITLE
FNX2-13554 ⁃ Add new Leanplum E_Add_Ons_Added Event

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#11655]
The following event was identified as a priority for Fenix during a recent test by the Mobile Engagement team. This is requested to be in market by 8/25/20 (release 80).

* [ ] E_Add_Ons_Added

This should be fired when the user successfully adds an add-on to their browser (by clicking "+" on the screen in the below image).

![Screenshot](https://user-images.githubusercontent.com/60749496/84822605-f1abd600-afea-11ea-8c0d-3e92610b1dee.png)UNITO-UNDERSCORE!20200616-184806!

Tasks:

* [x] Add mapping for E_Add_Ons_Added
* [ ] Undergo data review
* [ ] Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

This needs to be added to the [Mobile Engagement :heart: Fenix](https://github.com/mozilla-mobile/fenix/projects/48#card-39585660) project. I do not have access to add it myself.

**Comment by bifleming** [comment]
Work is complete
