### ISSUE TITLE
FNX2-13553 ⁃ Add new Leanplum E_Changed_ETP Event

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#11654]
The following event was identified as a priority for Fenix during a recent test by the Mobile Engagement team. This is requested to be in market by 8/25/20 (release 80).

* [ ] E_Changed_ETP

This should be fired when the user makes any change to their Enhanced Tracking Protection settings (on the screen in the below image).

![Screenshot](https://user-images.githubusercontent.com/60749496/84822210-53b80b80-afea-11ea-8f7d-6194660f913b.png)UNITO-UNDERSCORE!20200616-184758!

Tasks:

* [ ] Add mapping for E_Changed_ETP
* [ ] Undergo data review
* [ ] Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

This needs to be added to the [Mobile Engagement :heart: Fenix](https://github.com/mozilla-mobile/fenix/projects/48#card-39585660) project. I do not have access to add it myself.

**Comment by ekager** [comment]
cc @cbonacuse this has landed!

**Comment by AndiAJ** [comment]
Hi @cbonacuse & @ekager  , I've just checked this matter on both the latest **`Nightly Build 200730`** and **`Fenix Beta 80.0.0-beta-1`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

The E_Changed_ETP events are properly generated, on the other hand it looks like the **`tracking_protection_setting`** attribute remains set to "standard", filled #13125

## ✔️ Nightly
Google Pixel 3a -  device ID **`e6222324-6a2d-403a-abc5-a7b777227632`**
► **Set to Strict**
![image](https://user-images.githubusercontent.com/51314259/88925036-adb02000-d27c-11ea-8ef3-93ba2da6fbfb.png)
![image](https://user-images.githubusercontent.com/51314259/88924977-9ffa9a80-d27c-11ea-9db4-7f55dd4352ff.png)

► **Set to Custom**
![image](https://user-images.githubusercontent.com/51314259/88925485-45ae0980-d27d-11ea-9c0a-91c8ca6d21a2.png)
![image](https://user-images.githubusercontent.com/51314259/88925459-3d55ce80-d27d-11ea-8b77-d045df1fb437.png)

► **Set to Standard**
![image](https://user-images.githubusercontent.com/51314259/88925931-ed2b3c00-d27d-11ea-9406-4fc11c2ab22f.png)
![image](https://user-images.githubusercontent.com/51314259/88925962-f61c0d80-d27d-11ea-8944-3e5f1cf23b78.png)



Huawei Mate 20 Lite -  device ID **`1334424f-5898-4337-9ed7-9679fed9fb25`**
► **Set to Strict**
![image](https://user-images.githubusercontent.com/51314259/88925117-c7516780-d27c-11ea-890c-db66251aa3fd.png)
![image](https://user-images.githubusercontent.com/51314259/88925088-bef92c80-d27c-11ea-8ec9-0efaa8091fcc.png)

► **Set to Custom**
![image](https://user-images.githubusercontent.com/51314259/88925550-578fac80-d27d-11ea-9634-c2447273fcd8.png)
![image](https://user-images.githubusercontent.com/51314259/88925573-5e1e2400-d27d-11ea-95e7-3d915252ccb1.png)

► **Set to Standard**
![image](https://user-images.githubusercontent.com/51314259/88926020-0cc26480-d27e-11ea-8cd0-be2d960f50e4.png)
![image](https://user-images.githubusercontent.com/51314259/88926045-164bcc80-d27e-11ea-9f91-0bfed9226c27.png)


OnePlus A3 -  device ID **`d5e35e4f-c75a-4b5e-9aa0-6aa2cbb6c78b`**
► **Set to Strict**
![image](https://user-images.githubusercontent.com/51314259/88925193-ddf7be80-d27c-11ea-8ed4-633ae9d27879.png)
![image](https://user-images.githubusercontent.com/51314259/88925167-d46e5680-d27c-11ea-807b-a216cf22abcf.png)

► **Set to Custom**
![image](https://user-images.githubusercontent.com/51314259/88925611-69714f80-d27d-11ea-9286-98628c6df74a.png)
![image](https://user-images.githubusercontent.com/51314259/88925647-755d1180-d27d-11ea-8646-216103ec977b.png)

► **Set to Standard**
![image](https://user-images.githubusercontent.com/51314259/88926112-28c60600-d27e-11ea-88c6-2171434178cb.png)
![image](https://user-images.githubusercontent.com/51314259/88926137-31b6d780-d27e-11ea-911f-71406c21f07f.png)


## ✔️ Beta
Google Pixel 3a - device ID **`35d5c40d-0362-4b55-8aee-ffc6a9e7012c`**
► **Set to Strict**
![image](https://user-images.githubusercontent.com/51314259/88926555-d5a08300-d27e-11ea-82f1-f59c8d091a82.png)
![image](https://user-images.githubusercontent.com/51314259/88926580-dcc79100-d27e-11ea-8287-824ba44c2a8c.png)

► **Set to Custom**
![image](https://user-images.githubusercontent.com/51314259/88926956-64150480-d27f-11ea-8aa9-6bd4be818553.png)
![image](https://user-images.githubusercontent.com/51314259/88926978-6d05d600-d27f-11ea-9ffc-310aafc49535.png)

►**Set to Standard**
![image](https://user-images.githubusercontent.com/51314259/88927280-de458900-d27f-11ea-89a3-36a5cee1fe61.png)
![image](https://user-images.githubusercontent.com/51314259/88927309-e7cef100-d27f-11ea-8af9-62fc22e7ea26.png)


Huawei Mate 20 Lite - device ID 48e981ae-5ec4-43f7-bbb2-5d4532f15627
► **Set to Strict**
![image](https://user-images.githubusercontent.com/51314259/88926648-f23cbb00-d27e-11ea-8aca-8ee4bc453125.png)
![image](https://user-images.githubusercontent.com/51314259/88926661-f9fc5f80-d27e-11ea-937b-2df8494eb95b.png)

► **Set to Custom**
![image](https://user-images.githubusercontent.com/51314259/88927009-78590180-d27f-11ea-8b6c-43676883733d.png)
![image](https://user-images.githubusercontent.com/51314259/88927035-81e26980-d27f-11ea-97b4-237bd2f93b13.png)

► **Set to Standard**
![image](https://user-images.githubusercontent.com/51314259/88927359-f4ebe000-d27f-11ea-97b4-3b9da9dd4233.png)
![image](https://user-images.githubusercontent.com/51314259/88927387-fe754800-d27f-11ea-9b6d-a51372165316.png)


OnePlus A3 - device ID **`27951d4c-5729-43cf-92e2-ad7553a1a5c5`**
► **Set to Strict**
![image](https://user-images.githubusercontent.com/51314259/88926731-13051080-d27f-11ea-83a5-a956c3477577.png)
![image](https://user-images.githubusercontent.com/51314259/88926757-1c8e7880-d27f-11ea-9ef2-2fb9025db654.png)

► **Set to Custom**
![image](https://user-images.githubusercontent.com/51314259/88927058-8d359500-d27f-11ea-8b70-b0d171cecbcf.png)
![image](https://user-images.githubusercontent.com/51314259/88927092-9aeb1a80-d27f-11ea-968f-41c8db2ad01d.png)

► **Set to Standard**
![image](https://user-images.githubusercontent.com/51314259/88927410-08974680-d280-11ea-8401-9df52edbf0e5.png)
![image](https://user-images.githubusercontent.com/51314259/88927434-1351db80-d280-11ea-9651-9d0f5f0d233f.png)
