### ISSUE TITLE
FNX3-14800 ⁃ Add new Leanplum Add Ons Installed Attribute

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#11656]
The following attribute was identified as a priority for Fenix during a recent test by the Mobile Engagement team. 

* [ ] Add Ons Installed

This should include a list of add-ons the user has installed when the user successfully adds an add-on to their browser (by clicking "+" on the screen in the below image).

![Screenshot](https://user-images.githubusercontent.com/60749496/84822605-f1abd600-afea-11ea-8c0d-3e92610b1dee.png)UNITO-UNDERSCORE!20200616-184806!

Tasks:

* [ ] Create attribute: Add Ons Installed
* [ ] Understand if it is possible to implement in the requested way of having a list of values vs. boolean
* [ ] Undergo data review
* [ ] Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

This needs to be added to the [Mobile Engagement :heart: Fenix](https://github.com/mozilla-mobile/fenix/projects/48#card-39585660) project. I do not have access to add it myself.

**Comment by jhugman** [comment]
@liuche @chutten @boek 

Requesting a data-review on this prior to doing the engineering work on this: this is the ids of the addons installed, logged at/near startup.

@cbonacuse of the mobile engagement team is requesting this.

**Comment by jhugman** [comment]
@cbonacuse to fill in.

# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) **What questions will you answer with this data?**

2) **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**

3) **What alternative methods did you consider to answer these questions? Why were they not sufficient?**

4) **Can current instrumentation answer these questions?**

* No, while we are tracking some of these metrics in Glean, we need access to them in Leanplum for marketing usage.

5) **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**

6) **How long will this data be collected?**

7) **What populations will you measure?**

8) **Please provide a general description of how you will analyze this data.**

* Leanplum / Amplitude

9) **Where do you intend to share the results of your analysis?**

* Only on Leanplum, Amplitude and with mobile teams.

**Comment by cbonacuse** [comment]
@boek just curious, what is the difference between `enabled_addons` and `installed_addons`? Are these not the same? I see the definitions are slightly different in the code but I thought if an addon was installed, it is enabled.

I just hit the "+" button for 2 addons and I'm now seeing a value of `2` for both attributes.

cc: @liuche

**Comment by andreicristianpetcu** [comment]
@cbonacuse you can enable an addon and then disable it. same like on desktop. 
![Screenshot_20200825-003248_Firefox_Nightly](https://user-images.githubusercontent.com/922368/91098648-86c1ef80-e66a-11ea-84e1-701175763f42.png)

**Comment by bifleming** [comment]
Work is complete
