### ISSUE TITLE
FNX-12624 ⁃ [Bug] Top site icon size and dark theme border doesn't match spec

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#11651]
From @brampitoyo https://github.com/mozilla-mobile/fenix/issues/11081#issuecomment-644403738 and https://github.com/mozilla-mobile/fenix/issues/11081#issuecomment-644509917:

> In the spec, the box has a size of 40×40, and the icon inside it is always sized 24×24. Is it possible to follow this rule consistently, even for the default tile with capital letters?

> Re: background colour – referring back to the original design, it seems that the background colour value we have today is already correct, with only one addition required.

```
Light theme
    Background: White
    Border: Light Grey 30 #e0e0e6
Dark theme
    Background: Dark Grey 50 #32313c
    Border: Dark Grey 10 #52525e ← We don’t have this yet, and will need to add it
```

For reference heres what it currently looks like:
![image](https://user-images.githubusercontent.com/6396431/84815238-987e7b00-afc7-11ea-8010-611d19fb1402.png)

**Comment by brampitoyo** [comment]
@person808 Just for reference, I know that landscape orientation will be an issue in the near future.

I’m not sure what Top Sites will look like on a landscape layout – whether it will contain 4 icons in a row, or 6, or 8. I think it’s something that @topotropic have thought of.

She can respond to it after returning to PTO, and we can then file a new issue.

**Comment by person808** [comment]
@brampitoyo Thanks for letting me know. I've already created an issue for issues with the top sites padding so I'll quote you there since handling landscape properly is relevant there.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200619 from 6/19`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200619-152320](https://user-images.githubusercontent.com/51314259/85132481-8dcf1a80-b241-11ea-8758-5b080abf7e91.png)

**Comment by 532910** [comment]
Huge padding wastes space, it must looks so:

![image](https://user-images.githubusercontent.com/14617699/85529006-4c5db700-b615-11ea-9c3c-b610c4301687.png)

**Comment by 532910** [comment]
Still not fixed, please reopen.
