### ISSUE TITLE
FNX-12642 ⁃ [Bug] Visual design of "Delete browsing data" should match "Delete browsing data on quit"

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#11665]
@mcarare wrote on https://github.com/mozilla-mobile/fenix/issues/9229#issuecomment-642698518

> I noticed that there are some noticeable inconsistencies between the two screens (option name, option description font- see below) and a strange large space on the first screen.

<img src = https://user-images.githubusercontent.com/48995920/84398967-41fcef80-ac09-11ea-9507-1457e63e4bef.png width = 48%> <img src = https://user-images.githubusercontent.com/48995920/84398992-488b6700-ac09-11ea-9ddb-f0bc0f5183d5.png width = 48%>

The changes that we should make is outlined below.

- - -
### Delete browsing data on quit
* Browsing history → Browsing history and site data
* Reduce space between toggle and checkbox group. The amount of space should be identical to Settings → Enhanced Tracking Protection toggle, and the radio buttons below it.

### Delete browsing data
* Caption font should be Inter (or Roboto) instead of Metropolis

### On both pages
* Icon and text padding should be identical to the value used on the Settings main page

- - -
### Revised mockups that shows the changes above
![](https://user-images.githubusercontent.com/51007/84841454-76076300-b096-11ea-8438-4c45bc30d191.png) ![](https://user-images.githubusercontent.com/51007/84841457-77d12680-b096-11ea-8df6-f35c9b148a3b.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200622 from 6/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200622-094851](https://user-images.githubusercontent.com/51314259/85258958-efc19700-b470-11ea-83c6-897ece25256a.png)
