### ISSUE TITLE
FNX-4843 ⁃ Add behavior to use recommended settings

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1166]
### What / Requirements
We have to persist the user selection in this case "Recommended settings".
Provide the "Recommended settings" to the `SitePermissionsFeature`.

### Acceptance Criteria (how do I know when I’m done?)
Every time the user visits a site the rules of "Recommended settings" must be applied
If we close and open the app the "Recommended settings" must still active.

**Recommended settings Rules:**
Camera: Ask to allow
Notification: Ask to allow
Location: Ask to allow
Microphone: Ask to allow

**Comment by sv-ohorvath** [comment]
Verified, but found a new issue: #1414

**Comment by Amejia481** [comment]
@sv-ohorvath  I think this issue should be fixed in actual version of Fenix
