### ISSUE TITLE
FNX2-13560 ⁃ LeanPlum MissingResourceException  No 3-letter language code for locale: cak, lij

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11664]
Sentry report on Nightly: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7513010/?query=is%3Aunresolved%20level%3Afatal

Looks like Leanplum is trying to send messages to the locale `cak` but it's not working, and causing a crash.

Supported languages are [here](https://github.com/mozilla-mobile/fenix/blob/master/l10n.toml) and it does look like `cak` is supported. Maybe it's not supported by the Leanplum SDK/dashboard/localization? cc @lwa-moz

**Comment by liuche** [comment]
Don't see any more reports, and last reported was 23 days ago, so I'm going to close this one.

**Comment by liuche** [comment]
This is also happening again here: https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9267129/?query=release%3Aorg.mozilla.firefox-79.0.0

We should not crash on these failures, and figure out why we're messaging missing locales.

**Comment by st3fan** [comment]
It is important that we do not do fixes for the specific locales mentioned in these crashes, but instead make sure we simply ignore, or at least not crash, on locales that are not supported or recognized. (Unclear what the root cause is, but a crash should never happen in this code)

**Comment by st3fan** [comment]
I think this is high priority because if Leanplum for whatever reason can remotely crash a client, we should address this ASAP.

**Comment by liuche** [comment]
@cbonacuse is there some kind of mismatch for the supported locales in Leanplum? I also thought we had turned off LeanPlum notifications for Fenix (but this is showing up in our Migration Production crash reporter).

**Comment by cbonacuse** [comment]
Looping in @jhugman incase he has some insight here. We do not have any Leanplum messages live in Fenix now. The API keys should still be for Fennec so Fenix messages should not even be possible.

@liuche I can reach out and ask if Leanplum does not support 'cak' - is there something you would like them to take action on?

**Comment by st3fan** [comment]
This is most likely not actually a Leanplum issue but instead Android Component's `LocaleManager` not dealing well with some specific locales.

Is it possible that https://github.com/mozilla-mobile/android-components/blob/df55e790c6f2a5b51720157ca44251642458acc7/components/support/locale/src/main/java/mozilla/components/support/locale/LocaleManager.kt#L100 throws when the device is using an unexpected locale?

**Comment by st3fan** [comment]
As part of this patch, can we please add some _unhappy path_ tests to `LocaleManagerTest.kt`? I think we are only testing with locales that are supported but we need to be sure that a locale like `cak` or even `zz_ZZ` does not crash. Or if it crashes, that we handle that properly.

**Comment by AndiAJ** [comment]
Hi I've just checked this matter on **`Fenix 80.0-beta.2`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)


► ✔️ Cak (set in Fenix's settings)
![20200731-092744](https://user-images.githubusercontent.com/51314259/89009226-c23ff700-d314-11ea-891c-29e16723517d.gif)

► ✔️ Lij (set in Fenix's settings)
![20200731-094116](https://user-images.githubusercontent.com/51314259/89009347-08955600-d315-11ea-8dd6-6dbe4a4c6c51.gif)


I've also checked by setting the device language and input options to Filipino and Nepali installed **`Fenix 80.0-beta.2`** 
❓ I couldn't find the devices on Leanplum.
Waited and performed different actions for approx. 1h without any luck.

✔️ On the other hand, didn't encounter any issues if if I installed **`Fenix 80.0-beta.2`** with English set as the language and input option and only after I identified the devices on Leanplum changed  to Filipino and Nepali.
I've received the push notifications tapped them and properly opened Fenix without any crashes.

@liuche - Please review and advise. ☺️
