### ISSUE TITLE
FNX-12643 ⁃ Switch topSites to LinearLayout instead of constraint Layout

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#11666]
ConstraintLayouts seem to be less performant on simpler layouts.  We've noticed this with our own changes and there's quite a few blogs around that point to this being true. I did a quick experiment with topSites locally and it improved my start up time by 15-20 ms

**Comment by MarcLeclair** [comment]
Needs some QA to validate that switching the layout didn't change any topsites behavior

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200623 from 6/23`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
