### ISSUE TITLE
FNX-12648 ⁃ [Bug]Tabs tray: Tapping the New Tab FAB displays ":)" instead of the tabs number

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11672]
## Prerequisites
Have at least a tab opened

## Steps to reproduce
1. From the page view tap the tabs counter
1. Tapping the New tab FAB
1. Check the Tabs Counter icon 

### Expected behavior
The Tabs Counter should display the number of open tabs

### Actual behavior
Displays ":)" while the making the transition to Fenix's home screen
![image](https://user-images.githubusercontent.com/51314259/84870744-5b2df200-b088-11ea-8d37-c614b9fdc343.png)

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly 200617 from 6/17
• Beta 5.2.0-beta.2 from 6/16

### Notes
► Video
![20200617-104416](https://user-images.githubusercontent.com/51314259/84871882-c1ffdb00-b089-11ea-85ed-7cdcd41d4719.gif)

**Comment by hakkikaancaliskan** [comment]
I'm working on this. Instead of showing ":)" why not to leave it empty until fetching tab number?
https://github.com/mozilla-mobile/fenix/blob/1356b3e426f76fec78e94de6265b796f920c4ff4/app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounter.kt#L32

**Comment by ekager** [comment]
Reopening for QA

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200625-113006](https://user-images.githubusercontent.com/51314259/85685851-1fbea380-b6d8-11ea-8f8e-8917152f8e7b.gif)
