### ISSUE TITLE
[Bug] Black Highlight on Selecting Text and Searching

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11673]
## Steps to reproduce
Select some text
Click on Firefox Nightly Search, which opens another tab
Return to original tab

### Expected behavior
Normal Highlighting (Blue color)

### Actual behavior
Black highlighting with the selection bars missing

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200617-135225_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/84874180-c3260d80-b073-11ea-924b-475ca191ea09.png)

**Comment by AndiAJ** [comment]
**Reproducible** on the latest **`Nightly Build 201106`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1711089

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kaream671** [comment]
11693

**Comment by kaream671** [comment]
11673

**Comment by kaream671** [comment]
17373
