### ISSUE TITLE
FNX2-13564 ⁃ [Bug] Add-ons menu not reversed when toolbar is set to top

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#11679]
## Steps to reproduce
1. Open Fenix and go to Settings-> Customize - Toolbar - Set to "Top".
1. Open a page.
1. Tap on the three-dot menu - Add-ons.

### Expected behavior
The Add-ons menu is reversed.

### Actual behavior
The menu is displayed the same as for toolbar position to bottom.

### Device information
* Android device: all.
* Fenix version: Nightly 6/17, Beta 5.2.0-beta.2.

**Comment by Amejia481** [comment]
I'm not sure if it's something device specific, but I'm not able to reproduce on nightly 200617 06:00, on Pixel 3 with Android 10.
 
![image](https://user-images.githubusercontent.com/773158/84929969-9a673d80-b09e-11ea-83fc-1a5ee85ad0a6.png)

**Comment by sflorean** [comment]
Screenshot - Bottom toolbar

The items from the menu are in the same order for both options (bottom, top)

![Screenshot_2020-06-18-07-37-12](https://user-images.githubusercontent.com/58466444/84979013-07c6ad00-b137-11ea-9ed8-5b23ee2c4436.png)

**Comment by Amejia481** [comment]
cc @psymoon

**Comment by psymoon** [comment]
@brampitoyo should the add-on sub menu order be reversed when the toolbar positioning change? Refer to the 2 screenshots above.

**Comment by brampitoyo** [comment]
@psymoon Yes. I think that the sub menu ordering needs to be reversed when the positioning changes.

I realise now that the orientation I originally specced out was for the top toolbar positioning.

When the toolbar position is down the bottom, the ordering of the sub-menu should be reversed like this (the list below is ordered from top to bottom):

Add-ons Manager
—————
List of add-ons
—————
← Add-ons

I think that this issue isn’t critical by any means. I don’t think that the submenu is any less useable if the orientation is reversed.

Let’s just double-check with @AmyYLee @apbitner @betsymi to confirm that bottom-to-top menu ordering (ie. last item on top, first item on the bottom) is indeed what we _always want_, if the toolbar is positioned down the bottom.

**Comment by AmyYLee** [comment]
@brampitoyo I recall reversing the order is correct depending on bottom/top postition. I'll wait for @apbitner to confirm this.

**Comment by apbitner** [comment]
Yes the reverse order was intentional, to put more frequently used actions closer to the user's finger that just opened the menu.

**Comment by brampitoyo** [comment]
Great. Thanks for the confirmation to both @apbitner and @AmyYLee!

I’m reposting the same Add-ons submenu, where the menu items inside it have been reverse-ordered.

The submenu header is located down the bottom: first item on the list. The Add-ons manager is up top: last item. The rest of the add-ons are ordered alphabetically, bottom-to-top.

<img width="360" src="https://user-images.githubusercontent.com/51007/85496945-4675cf00-b631-11ea-9f8d-f06efe312cda.png">

**Comment by hakkikaancaliskan** [comment]
<img src="https://user-images.githubusercontent.com/17825767/85743613-dd638980-b70c-11ea-9ade-9342a73aaa90.png" width="300">
<img src="https://user-images.githubusercontent.com/17825767/85743622-df2d4d00-b70c-11ea-986b-dddec82c351c.png" width="300">
<img src="https://user-images.githubusercontent.com/17825767/85743656-e5bbc480-b70c-11ea-8bd9-c37f331afd18.png" width="300">
<img src="https://user-images.githubusercontent.com/17825767/85743661-e6ecf180-b70c-11ea-9f40-79e541d83525.png" width="300">
Is this how exactly you guys want?

**Comment by hakkikaancaliskan** [comment]
Noooo @psymoon :(
Go on bro, my bad. I should have written here.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build 7/3 with Samsung Galaxy Note 10 (Android 10) and LG G7 FIT (Android 8).
