### ISSUE TITLE
FNX-12650 ⁃ [Bug] One pixel white line on top in many websites on scrolling up

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11674]
## Steps to reproduce
activate top address bar
go to github.com 
Scroll down a bit
scroll to top

### Expected behavior
No white line

### Actual behavior
White line about a single pixel

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200617-141420_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/84876486-cb337c80-b076-11ea-9b78-f9f39434c630.png)
![Screenshot_20200617-141354_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/84876553-dc7c8900-b076-11ea-96bc-0da0e5495b9b.png)
![Screenshot_20200617-141321_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/84876528-d686a800-b076-11ea-8e2d-006da29be4c9.png)

**Comment by s-ankur** [comment]
Also happens for bottom bar

**Comment by ekager** [comment]
Closing for #10598
