### ISSUE TITLE
FNX-4844 ⁃ Add behavior to use custom settings

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1167]
### What / Requirements
When the user clicks "Use custom settings", we have to allow the user to change the settings per each permissions. When the user change a permission we have store it and let the 
know `SitePermissionsFeature`.

### Acceptance Criteria (how do I know when I’m done?)
Every time the user visits a site the rules of "Custom settings" must be applied.
If we close and open the app the "Custom settings" must still active

**Comment by bsurd** [comment]
Custom site permissions are applied successfully and work as expected. All of the acceptance criteria for this has been met and verified.
