### ISSUE TITLE
FNX-12647 ⁃ No Apk in GitHub release assets since Preview 5.0.0

### ISSUE THREAD

**Issue by stefan-niedermann** [mozilla-mobile/fenix#11671]
Hello there,

i noticed, that there haven't been any built apk files attached to the GitHub release assets since Firefox Preciew 5.0.0.

Since it's quiet unsecure to browse the web with an outdated browser, the question is, where can i get a new compiled version which is trustable? Or did you just "forget" to attach them?

It seems like #162 doesn't have a high priority for you,  but at least i was able to run my own F-Droid repository which fetched the Apk directly from GitHub with no efforts. This is no longer possible.(Alternative solution might be that your run an own F-Droid repository :wink: )

PS: Yeah, i am one more of those guys who don't run proprietary Play Services on their phone and can not access the Play Store therefore. :laughing:

**Comment by SS1113** [comment]
@stefan-niedermann This #11030 and this #11418 it has already been discussed here.

**Comment by stefan-niedermann** [comment]
Thank you

**Comment by stefan-niedermann** [comment]
Just as documentation for other people coming along here looking for the `apk`s: I found the latest release here:

https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/project.mobile.fenix.v2.production.latest/artifacts/public/build/arm64-v8a/geckoBeta/target.apk
