### ISSUE TITLE
FNX-12651 ⁃ [Bug] Clear a URL from the nav bar and then press back, goes to the homescreen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#11675]
## Steps to reproduce
1. Load a webpage.
1. Tap the URL bar to trigger edit mode.
1. Tap the "x" button to clear the URL.
1. Press the device back button to undo and return to the web page.
    1. Expected behavior
The search view closes and returns to the webpage, no changes made to the URL.
    1. Actual behavior
The search view closes and goes to the home screen. The tab is kept in the tabs tray.
    1. Device information

* Android device: Nexus 9 (Android 7.1.1) Not reproducing 100%
Not reproducing on Pixel 4 (Android 10)
* Fenix version: 5.2-beta2

**Comment by miDeb** [comment]
I wonder if this is related to https://github.com/mozilla-mobile/android-components/issues/3600, but I can't confirm because I can't reproduce.

**Comment by sv-ohorvath** [comment]
On the same device, I noticed another back-press issue on the edit toolbar:
1. Clear the app data to get the first run onboarding.
2. Press the Start Browsing button at the bottom.
3. The search mode is triggered, then press back.
Result: The app is closed instead of showing the homescreen.

**Comment by sv-ohorvath** [comment]
Closing in favor of: https://github.com/mozilla-mobile/fenix/issues/11866 (duplicates)
