### ISSUE TITLE
FNX2-13563 ⁃ [Bug] General blocked site permissions are shown on websites that don't need them

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#11676]
## Steps to reproduce
1. Go to Settings>Site permissions, set any to Blocked (camera, mic, location or notifications).
1. Load a website (e.g. wikipedia), tap the lock icon to open the site info panel.
    1. Expected behavior
Only site exceptions should be displayed in the info panel.
    1. Actual behavior
The generally blocked permissions appear in the info panel, even when the website doesn't require them. The ones only blocked by Android are not displayed.
    1. Device information

* Android device: Nexus 9 (Android 7.1.1), Pixel 4 (Android 10)
* Fenix version: 5.2-beta2, Nightly 6/17

**Comment by Amejia481** [comment]
@NotWoods I think this could be a regression from https://github.com/mozilla-mobile/fenix/pull/10810

**Comment by softvision-miralobontiu** [comment]
Verified that no blocked permissions appear in the info panel when the website doesn't require them.
Tested on Sony Xperia Z5 Premium (Android 7.1.1), Google Pixel (Android 10), and OnePlus 5T (Android 9), on the latest Nightly build from 7/27.

**Comment by AndiAJ** [comment]
Reproducible on the 79.0.2 RC build from 8/1 using a OnePlus A3 (Android 6.0.1)

**Comment by Amejia481** [comment]
@liuche should https://github.com/mozilla-mobile/fenix/commit/6530a45eb9b2bc8b60497d47600b7b233762dc6d be uplifted ?

**Comment by liuche** [comment]
Since this isn't impairing user usage, and is showing blocking that doesn't apply to the site, we can let this ride the trains.

**Comment by Amejia481** [comment]
👍
