### ISSUE TITLE
FNX-12654 ⁃ Tab counter long-press menu: re-arrange items so "New tab" is always under finger

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#11677]
### What is the user problem or growth opportunity you want to see solved?
Long press on tab counter brings up context menu - which is great. But ATM the item order is not ideal. I think New Tab is the most likely menu item to be used. I think therefore New Tab should always be under the user's finger straight after the long press. Then I can go long-press; tap in the same area of the screen to open a new tab.

### How do you know that this problem exists today? Why is this important?
ATM I have to long press the tab counter then look hard to find the New Tab context menu item, move my finger to it, and then tap. 

Plus the menu item under my finger is different with top toolbar (close tab) and with bottom toolbar (New private tab).

So I think the menu order should be

Bottom toolbar:-
Close tab
New private tab
New tab

Top toolbar:-
New tab
New private tab
Close tab

### Who will benefit from it?
All users will be able to, without looking, long-press then tap the tab counter to open a new (non-private) tab.

Thanks!

**Comment by person808** [comment]
The feature is pretty much a copy of chrome's implementation which is

```
Close tab
New tab
New private tab
```

You're right that the order of menu items relative to the user's finger changes depending on the toolbar position. Will wait for UX feedback.

**Comment by AmyYLee** [comment]
This makes sense to me. @apbitner to confirm menu order.

**Comment by apbitner** [comment]
Agreed 👍🏻

**Comment by person808** [comment]
reopening for qa

**Comment by sflorean** [comment]
Verified as fixed on Nightly 06/26 with Xiaomi Redmi Note 8T (Android 9) and LG G7 FIT (Android 8).
