### ISSUE TITLE
[Bug]Tabs Tray: Improperly page link while in reader mode after Delete + Undo

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11683]
## Steps to reproduce
1. Navigate to: https://en.wikipedia.org/wiki/Main_Page
1. Switch to Reader mode
1. Tap the Tabs counter
1. Swipe Delete the Tab
1. Undo the deletion 

### Expected behavior
Display the correct link
E.g.
**`en.m.wikipedia.org`**

### Actual behavior
Displays a web extension link
E.g.
**`moz-extension://92cbbc65-c49a-487d-ba8d-40851478d34a/readerview.html?url=https%3A%2F%2Fen.m.wikipedia.org%2Fwiki%2FMain_Page&id=137438953478`**

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly 200617 from 6/17
• Beta 5.2.0-beta.2 from 6/16

### Notes
► Video
![20200617-135425](https://user-images.githubusercontent.com/51314259/84890798-896cfb00-b0a3-11ea-9d34-7f6c43722ccc.gif)

**Comment by csadilek** [comment]
Tried in Nightly 201115 and can't reproduce anymore. @AndiAJ can you verify please? :)

NB: This needs to be verified with multiple open tabs now because deleting the last tab switches back to the browser fragment.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201117`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201117-091557](https://user-images.githubusercontent.com/51314259/99359001-0d2b4d80-28b7-11eb-9468-0571e93499e5.gif)
