### ISSUE TITLE
[Bug] App crashes when cancelling the "Downloading and verifying add-on..."

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#11688]
## Steps to reproduce
1. Go to three-dot menu - Add-ons and select to install an add-on.
1. Tap on "Add" on the first prompt.
1. When "Downloading and verifying add-on..." prompt is displayed, wait for 3-4 seconds and tap on "Cancel".

### Expected behavior
The add-on isn't downloaded.

### Actual behavior
Fenix crashes.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 9), Samsung Galaxy S9 (Android 8), Google Pixel 3 XL (Android 9), OnePlus A3 (Android 6.0.1), and Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: Beta 5.2.0-beta.2
* Not reproducible on 6/17 Nightly

dae359e9-704e-4125-af22-6966ad9f6c8b
java.lang.IllegalStateException: result is already complete

* Sentry: https://sentry.prod.mozaws.net/operations/fenix-beta/?query=7510c3ec53d84bb7a7a60347c371212a
* Socorro: https://crash-stats.mozilla.org/report/index/bp-03680143-5214-4139-a55c-79a310200617
----
<details><summary>Crashlog 1</summary>
<p>

java.lang.IllegalStateException: result is already complete
at org.mozilla.geckoview.GeckoResult.complete(GeckoResult.java:7)
at org.mozilla.geckoview.WebExtensionController$WebExtensionResult.sendSuccess(WebExtensionController.java:3)
at org.mozilla.gecko.EventDispatcher$JavaCallbackDelegate$1.run(EventDispatcher.java:2)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7258)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

</p>
</details>

![](https://user-images.githubusercontent.com/40694158/84893867-9f30ef00-b0a8-11ea-83e2-3950a81c785a.gif)

**Comment by csadilek** [comment]
> Fenix version: Beta 5.2.0-beta.2
Not reproducible on 6/17 Nightly

Thanks, yes, this is fixed in GV 79 (master), but the fix wasn't uplifted to beta: https://bugzilla.mozilla.org/show_bug.cgi?id=1637765

This happens only if the extension is already downloaded and installation cancelled after that. Our main motivation for landing cancellation support is cancelling (slow) downloads...so I think this is acceptable until the next release goes out.

**Comment by liuche** [comment]
This should get fixed in the 79.0.0 build, but will not be fixed in the 78.0.0 one.

**Comment by AndiAJ** [comment]
Reproducible on Beta **`78.0.0-beta.1 from 6/26`** using  OnePlus A3 (Android 6.0.1) after cancelling the instalaltion of **Privacy Badger**

https://crash-stats.mozilla.org/report/index/463d7f79-7eff-41a0-a464-a74b70200626

**Comment by softvision-miralobontiu** [comment]
I wasn't able to reproduce the crash anymore on the latest Nightly builds, or Beta builds.
I will close it.
