### ISSUE TITLE
[Bug] Browser Speed

### ISSUE THREAD

**Issue by anmol257** [mozilla-mobile/fenix#11681]
### Device information
* Android device:Yes android 5.1 lollipop
* Fenix version: ?

**Comment by cadeyrn** [comment]
It could be useful to provide a few details as steps to reproduce, measurements…

**Comment by anmol257** [comment]
> 
> 
> It could be useful to provide a few details as steps to reproduce, measurements…

Previous and forward tabs can be saved in cache memory till the concerned tab is closed be user.This will improve the speed.

**Comment by hakkikaancaliskan** [comment]
> > It could be useful to provide a few details as steps to reproduce, measurements…
> 
> Previous and forward tabs can be saved in cache memory till the concerned tab is closed, by user.This will improve the speed.
> @cadeyrn

Agreed, back and forward tabs should be cached, generally reloading when going back etc.

**Comment by ekager** [comment]
Closing this issue as it doesn't have enough details to be actionable. If you're still seeing problems, please open a new issue with more information/logs/videos etc.
