### ISSUE TITLE
[New Feature] Report clickbait sites ,Protect user privacy

### ISSUE THREAD

**Issue by anmol257** [mozilla-mobile/fenix#11686]
### What is the user problem or growth opportunity you want to see solved?
There are lots of websites that post clickbait content, thereby wasting users time. Some also transfer spyware to the devices.

### How do you know that this problem exists today? Why is this important?
Because I have been facing this problem for many years. Many people use mobiles for doing payments and saving private info. The spyware if installed compromises the privacy of the concerned individual.

### Who will benefit from it?
Everyone

### Possible Solution
Users can have the option to report a site to firefox. Then based on data and algorithm other firefox users can be given the warning to turn back.
Eg - Truecaller is using the method to identify spam callers and reduce fraud.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2290)

**Comment by Dunexus** [comment]
Do you mean integrate something like [WebOfTrust](https://www.mywot.com/) inside Fenix ?

**Comment by anmol257** [comment]
Well yeah
Its great some poeple share similar concerns.
However with the userbase of firefox it will be on another level.

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
