### ISSUE TITLE
FNX-448 ⁃ Cannot connect to site hosted with a self signed certificate

### ISSUE THREAD

**Issue by pasqualedante** [mozilla-mobile/fenix#1168]
## Steps to reproduce
Try to visit a site that is hosted with a self-signed certificate (for example for develop purpose)

### Expected behavior
Fenix warning me about security and he give me a way to add a certificate exception

### Actual behavior
Cannot vist the site and an "Security connection failed" page is shown

### Device information
* Android device: POCOPhone F1 (Android 9)
* Fenix version: 1.0.1912 (build #10811221 67.0a1-20190312095443)

**Comment by kbrosnan** [comment]
Example: https://self-signed.badssl.com

**Comment by sblatz** [comment]
This will be handled by #921.

**Comment by vesta0** [comment]
@cpeterso can be bypass the security warning page in GV?

**Comment by cpeterso** [comment]
@eamsen, do we have a GV bug or API for bypassing Safe Browsing warning pages? We have the same problem with cert error pages.

**Comment by vesta0** [comment]
@cpeterso do we have a GV bug to track this?

**Comment by cpeterso** [comment]
I filed new GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1553265 which might be related to "load flag to bypass the URI classifier" GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1509018

This bug probably does not need to block MVP.

**Comment by vesta0** [comment]
Thank you @cpeterso and no it's not a blocker :)

**Comment by AlbertoFabbri93** [comment]
I'm having the same problem. It should be possible to add a certificate exception.

**Comment by monreal** [comment]
I wonder if there is a workaround for this? I can access one of my two WiFi access points just fine with Fenix while they both use self signed certs. Is the override config synced from Fennec via FxA?

**Comment by mike-pt** [comment]
> This bug probably does not need to block MVP.

I'm not one to decide but consider that this would force me to install another browser to be able to access local router config or other LOCAL web services that have self-signed certificates.

I understand the security point of view but I often find myself switching to *insert other browser (even if it is "old" firefox)* for this reason. 

Both home users and enterprise users still need this more often then we think.

**Comment by vesta0** [comment]
I believe this will be fixed by #6380
