### ISSUE TITLE
[Bug] logins not syncing from laptop to mobile.

### ISSUE THREAD

**Issue by anmol257** [mozilla-mobile/fenix#11692]
### Expected behaviour
All the sites logged in on laptop should automatically be on mobile or at least logging should be auto-filled and vice-versa.

### Device information
* Android device:?
* Fenix version:?

**Comment by ekager** [comment]
@anmol257 are you still seeing this issue? Have you performed a manual sync?

**Comment by anmol257** [comment]
> 
> 
> @anmol257 are you still seeing this issue? Have you performed a manual sync?

Its resolved way back.
