### ISSUE TITLE
FNX-4845 ⁃ Opening a link from an external app crashes

### ISSUE THREAD

**Issue by armenzg** [mozilla-mobile/fenix#1169]
## Steps to reproduce
* Tap on a link on an external app
* Android asks you to choose which browser to use
* Select Fenix

### Expected behavior
* The page loads up

### Actual behavior
* The browser crashes and requests you to send feedback

NOTE: This does not happen always but mainly when I have not used the phone for a time.

### Device information
* Android device: Moto G5
* Fenix version: I don't know

**Comment by kbrosnan** [comment]
Sounds like a dupe of 1148
