### ISSUE TITLE
[Bug] Can't access shortcut sites from device's home screen when saved in reader mode

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#11699]
## Steps to reproduce
1. Open app and go to wikipedia.org/wiki/mozilla.
1. Tap on the reader mode icon.
1. Go to app's Menu/Add to home screen.
1. Tap on the "Add" button from the app's dialog box.
1. Tap on the "Add" button from the device's dialog box.
1. Open the page from homescreen
    1. Expected behavior
User can access the shortcut of the page saved in reader mode.
    1. Actual behavior
User can't access the shortcut.
    1. Device information

* Android device: Google Pixel 3XL (Android 9), Samsung Galaxy S9 (Android 8)
* Fenix version: Fenix Beta 5.2.0-beta.2, Nightly 6/17

GIF
![20200617-201302](https://user-images.githubusercontent.com/49859863/84929051-f8644700-b0d7-11ea-9450-caf6246b06a3.gif)

Note:
Seems that it's considering the shortcut as it's an app.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly 210120`** and **`85.1.0-rc.1`** using the following devices:
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)
