### ISSUE TITLE
FNX2-13572 ⁃ [Bug]Collections flicker after tapping the New Tab FAB

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11690]
## Prerequisites
Have at least one Collection created

## Steps to reproduce
1. Open the Tabs Tray
1. Tap the New Tab FAB 

### Expected behavior
No UI issues

### Actual behavior
The previously created collections flicker

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly 200617 from 6/17
• Beta 5.2.0-beta.2 from 6/16

### Notes
► Video
![20200617-150455](https://user-images.githubusercontent.com/51314259/84896661-018bee80-b0ad-11ea-9b51-f1a10b97aaa9.gif)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/4 with Samsung Galaxy Note 10 (Android 10), Google Pixel 3 (Android 11), and Huawei MediaPad M2	(Android 5.1.1).
