### ISSUE TITLE
FNX2-13574 ⁃ [Bug] Top sites are not centered properly on some screen sizes

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#11694]
On some screen sizes, the top sites have more padding on the right than on the left due to wrapping of the top sites row.

![image](https://user-images.githubusercontent.com/6396431/84919361-ae974480-b076-11ea-9965-1635995e4e99.png)

Here is the original spec: https://github.com/mozilla-mobile/fenix/issues/11081#issuecomment-644509917

Related Issue: #10281 

### Device information
* Android device: Google Pixel 2 XL
* Fenix version: Nightly 6/17

**Comment by person808** [comment]
Quoting @brampitoyo https://github.com/mozilla-mobile/fenix/issues/11651#issuecomment-645775196 on landscape mode: 

> @person808 Just for reference, I know that landscape orientation will be an issue in the near future.
> I’m not sure what Top Sites will look like on a landscape layout – whether it will contain 4 icons in a row, or 6, or 8. I think it’s something that @topotropic have thought of.
> She can respond to it after returning to PTO, and we can then file a new issue.

**Comment by Dunexus** [comment]
Another solution to the spacing problem that would behave correctly regardless of aspect ratio or top sites number could be to split the space left at the end of the row (or the space that would be left at the end if the row was full) as extra padding between the element.
It will stay left align and the extra padding can't be more than the width of one element and its padding divided but the number of elements that can fit in one row, so really small even in worst case scenario.

**Comment by AmyYLee** [comment]
@gabrielluong Have we resolved this by having the grid flexible?

**Comment by gabrielluong** [comment]
> @gabrielluong Have we resolved this by having the grid flexible?

Not necessarily. I think we are essentially trying to do `justify-content: center` as seen in the BLUE row in https://codepen.io/team/css-tricks/pen/zzJMGJ. Right now, it is behaving as the first row.

**Comment by AmyYLee** [comment]
@gabrielluong Do you still need UX feedback?

**Comment by madb1lly** [comment]
Hi all,

I also have this issue on Nokia 8 which has a 1440 pixel width display in portrait mode. I only have 5 top sites icons on the top row and the space at the right hand side is large enough to easily fit another icon.

I know it's easy for me to suggest things that might be technically difficult, but why not just justify these rows centre rather than to the left?

Cheers 🙂

**Comment by brampitoyo** [comment]
@madb1lly Thanks for your report. Because Android has such differing screen sizes and pixel density, it’s helpful for us to get more screenshots and anecdotes to be able to create a sensible policy that’s “set once, works everywhere”.

**Comment by madb1lly** [comment]
Hi @brampitoyo,

Here's a screenshot:
![Screenshot_1597913750507](https://user-images.githubusercontent.com/25123631/90749520-d2277700-e2d3-11ea-8682-22c05300edf3.jpg)

Cheers 🙂

**Comment by person808** [comment]
Updated screenshot with new top site layout. Still an issue unfortunately
![Screenshot_20200825-075727](https://user-images.githubusercontent.com/6396431/91190682-b263ca80-e6a8-11ea-97c3-550cac1bbdb9.png)

**Comment by person808** [comment]
Since they're shown in a ViewPager I wonder if Constraint layout's `Flow` would be helpful here? 🤔

**Comment by madb1lly** [comment]
Hi all,
Yes, I agree that the top sites icons are still off-centred with with new 4x2 x2 pages layout.
Cheers 🙂

**Comment by apbitner** [comment]
This should be addressed here - https://github.com/mozilla-mobile/fenix/issues/13765
