### ISSUE TITLE
[Bug] Lastpass Autofill service doesn't work

### ISSUE THREAD

**Issue by Sayrus** [mozilla-mobile/fenix#11702]
## Steps to reproduce
For my test, I used Google (Login form), a Nextcloud (to ensure this is not a strange bug with not having a password field) and basic auth from `https://jigsaw.w3.org/HTTP/Basic`

* Makes sure you enable Lastpass as an autofill service
* Open any website with a login form or basic auth
* Dropdown menu doesn't appear

Additional steps to ensure this is (only?) with Lastpass:

* Change the autofill service to Bitwarden
* Dropdown appear
* Change it back to Lastpass
* No dropdown

### Expected behavior
Dropdown menu appear and I can fill my password

### Actual behavior
No dropdown appear

### Device information
* Android device: Xiaomi Mi Mix 3 (MIUI 11.0.3, Android 10)
* Fenix version: 5.1.1 (Build #21571852), 42.0.1

Note:
I don't think this is not a duplicate of #9854 as using the provided method doesn't fix. Doing it with Bitwarden works like a charm.
I think it blocks #9854 as I understood it as "We want autofill service" to work and not just "any autofill method" like the legacy method Lastpass also have.

**Comment by sophiekuehn** [comment]
I have the same or at least a similar issue with KeePassDX or KeePass2Android. Expected auto fill not happening .

**Comment by auanasgheps** [comment]
I have a similar behaviour on KeePassDX: the prompt appears for an instant then disappears. Reported [here](https://github.com/Kunzisoft/KeePassDX/issues/681)

**Comment by kbrosnan** [comment]
Please keep password filling issues to one app per issue. Our understanding of the Laspass issue is that they need to support the modern [Android autofill API](https://developer.android.com/guide/topics/text/autofill)
