### ISSUE TITLE
FNX-12688 ⁃ Blank space under top toolbar in custom tab

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11708]
STR:

1. Have top toolbar
1. Open https://www.rollingstone.com/politics/politics-news/new-york-senate-50-a-police-misconduct-1012357/ in custom tab

Expected: top toolbar lines up with web content 

Actual: top toolbar has space (size of toolbar, color of background) under it, and then web content

![Screenshot](https://user-images.githubusercontent.com/25442310/84957985-5db13b80-b0ca-11ea-9458-4ea06b31c525.png)UNITO-UNDERSCORE!20200617-183955!

**Comment by hakkikaancaliskan** [comment]
Same happens with bottom toolbar.
Latest weekly.
Also on light theme close (x) button is white (becomes invisible)

**Comment by ekager** [comment]
cc @NotWoods wondering if this could be a regression from the hide toolbar feature changes?

**Comment by AndiAJ** [comment]
Hi @ekager , can't test this on today's Nightly build due to #11756

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** using both TOP and BOTTOM toolbar position on the latest **`Nightly Build 200622 from 6/22`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Opened the following custom tabs https://www.rollingstone.com/politics/politics-news/new-york-senate-50-a-police-misconduct-1012357/
https://www.freepik.com/
https://www.desidime.com/
