### ISSUE TITLE
FNX2-13584 ⁃ Add new Leanplum ETP Enabled Attribute

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#11704]
The following attribute was identified as a priority for Fenix during a recent test by the Mobile Engagement team. 

* [ ] ETP Enabled

This value should say 'TRUE' upon install since ETP is enabled by default. The value should be changed to 'FALSE' if the setting is turned off on page in the screenshot below. If a user turns it off, then turns it on again, we would expect the value to then change back to 'TRUE'.

![Screenshot](https://user-images.githubusercontent.com/60749496/84822210-53b80b80-afea-11ea-8f7d-6194660f913b.png)UNITO-UNDERSCORE!20200616-184758!

Tasks:

* [ ] Create attribute: ETP Enabled
* [ ] Undergo data review
* [ ] Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

This needs to be added to the [Mobile Engagement :heart: Fenix](https://github.com/mozilla-mobile/fenix/projects/48#card-39585660) project. I do not have access to add it myself.

**Comment by bifleming** [comment]
Work is complete
