### ISSUE TITLE
[Bug] Separate scroll action from top bar animation

### ISSUE THREAD

**Issue by zakutin** [mozilla-mobile/fenix#11703]
## Steps to reproduce
1. Open any scrollable website.
1. With top bar option enabled, make quick swipes (scroll top/bottom)
1. The top bar animation takes some initial acceleration from the page content.
1. It is required to make second swipe to begin to scroll with expected and smooth acceleration.

### Expected behavior
The scrolling with the top bar enabled shall be smooth with the first swipe. The scrolling with the bottom bar enabled works well from the first swipe.

### Actual behavior
The animation of the top bar appearance shall be independent from the scrolling of the main content, as the "energy" of the first quick swipe is suppressed by this animation. The scrolling looks laggy. It requires to make the second swipe.

### Device information
* Android device: Redmi 4x, Android 9
* Fenix version: 77.0.0-beta.2 (Build #2015744451)

Animation with bottom and top bars:
![ScreenRecord-2020-06-17-19-17-54](https://user-images.githubusercontent.com/53969222/84933331-03b67300-b0d6-11ea-9860-a50a43b6b334.gif)UNITO-UNDERSCORE!3!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2315)

**Comment by zakutin** [comment]
The issue is still present in 89.1.1 (Build #2015812947). Any changes?

**Comment by SoftVision-LorandJanos** [comment]
I tried to reproduce this issue on different scrollable pages with the address bar on top and I couldn't reproduce it on the latest builds.
I didn't observe any noticeable difference on scrolling with address bar on top or bottom, and between scrolling up or down.
@zakutin please confirm if it's not reproducible on your end either. Thank you!
Tested on the latest builds:
- latest Nightly 96.0a1 (2021-12-03).
- latest Beta (95.0.0-beta6).
- latest RC (95.1.0).

Device used: Xiaomi Mi11 Lite (Android11).

**Comment by zakutin** [comment]
Well, I do not have the 95 or 96 versions yet, but the issue is still present on two different phones I've tested:

Xiaomi Mi A3, Android 11, FF 94.1.2 (Build #2015844587), top position:

https://user-images.githubusercontent.com/53969222/144930413-43b4f086-f6af-457b-b093-eb0c52ea3eb2.mp4

Xiaomi Mi A3, Android 11, FF 94.1.2 (Build #2015844587), bottom position:

https://user-images.githubusercontent.com/53969222/144930506-b6bf67d6-73fa-4933-92a3-29403d07af58.mp4

Xiaomi Redmi 4X, Android 9, FF 94.1.2 (Build #2015844587), top position:

https://user-images.githubusercontent.com/53969222/144930677-c71fb108-e66d-4444-9905-5bf34d99b6af.mp4

Xiaomi Redmi 4X, Android 9, FF 94.1.2 (Build #2015844587), bottom position:

https://user-images.githubusercontent.com/53969222/144930737-8489fa45-25e8-4ad0-a9a8-4722bc191da5.mp4

Looking forward to test the RC version.

**Comment by zakutin** [comment]
The same behavior on both devices with 95.1.0 (Build #2015848803) version.
