### ISSUE TITLE
FNX-12684 ⁃ [Bug] fenix nighlty ui getting worse

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11705]
Fenix nighlty ui is getting worse and worse, now url bar will hide during scrolling (someone may like it, I personally love fixed one) also add ons now are buried in a sub menu, so for example clicking ublock origin now requires an extra tap.instead of messing an already awful ui (old Firefox was much better, a simple tap on url bar and was possible to both click top sites or perform a search) why dont the mozilla engineers add swipe left/right to move left /right tab. also the dynamic toolbar has a bug where elements underneath are not clickable.

**Comment by ekager** [comment]
Thanks for your feedback. If you want any of these UI issues looked at, please open individual issues for each one.
Some of them already have issues 
dynamic toolbar: #11189 
gestures: #10585
