### ISSUE TITLE
[Bug] Opening multiple tabs from History screen opens homescreen instead of tabs tray or page content

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11712]
## Steps to reproduce
* Go to history
* Long press and select multiple tabs
* Click 3-dot at top
* Select "Open in new tab"

### Expected behavior
One of the pages is loaded or the tabs tray is opened

### Actual behavior
The homescreen is loaded (presumably because the tabs used to be on the homescreen). Video: https://drive.google.com/file/d/147cheN6q8mAw54t_RgjBjHzNkR-ax-Go/view?usp=sharing

### Device information
* Android device: Galaxy S5
* Fenix version: Nightly 200617

**Comment by VitalyVPinchuk** [comment]
Tabs tray opens with selected tabs from history on the latest main branch.
Probably already fixed.
