### ISSUE TITLE
FNX-12695 ⁃ [Bug] When previewing sites from external app, top of screen is blank

### ISSUE THREAD

**Issue by ktaeleman** [mozilla-mobile/fenix#11715]
## Steps to reproduce
Open a link from an external application like mail client, reddit app,... 
In my case it was https://freepik.com, but I think it happens everywhere.

### Expected behavior
Page displays normally

### Actual behavior
Blank bar at top of page

![Screenshot](https://user-images.githubusercontent.com/37940779/84963842-5c2e4600-b0bf-11ea-96b7-9f306d65d5a3.png)UNITO-UNDERSCORE!20200617-171501!

### Device information
* Android device: Pixel 3 XL
* Fenix version: Nightly 200615 06:01 (Build #21670608)
45.0.20200613130120, b4f036c83
GV: 79.0a1-20200612094620
AS: 60.0.0

**Comment by ktaeleman** [comment]
The black with red bar is a webrender performance indicator.

**Comment by SS1113** [comment]
This has already been reported here #11545 and here #11521.

**Comment by sheikh-azharuddin** [comment]
> This has already been reported here #11545 and here #11521.

The bar size have increased now.really thick now😅🤣
Instead of fixing seems they have increased the size

 
![Screenshot_20200618-114115](https://user-images.githubusercontent.com/58127841/84984532-8bc66800-b12a-11ea-8e33-d94e7c0bd500.jpg)

**Comment by NotWoods** [comment]
Superseded by #11708. This should be fixed in the next Nightly.
