### ISSUE TITLE
FNX-12691 ⁃ [Bug] Tabs flicker when switching from private tabs to normal tabs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11711]
## Steps to reproduce
* Open a tab, load a page
* Open tabs tray
* Click Private tabs
* Click normal tabs

### Expected behavior
See normal tabs, no flicker

### Actual behavior
See normal tabs, flicker. Here's a video: https://drive.google.com/file/d/1Qpmv_bHSV0DgeZfXU3Gp5DBXxFeEAGGh/view?usp=sharing

### Device information
* Android device: P2, Galaxy S5
* Fenix version: Nightly 200617

**Comment by cadeyrn** [comment]
Duplicate of #11560.

**Comment by cadeyrn** [comment]
Fixed by #11826.
