### ISSUE TITLE
FNX-12694 ⁃ [Bug] Settings action bar is multi-select colored after opening multiple tabs from history

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11714]
## Steps to reproduce
* Open history
* Long press and select multiple tabs (note action bar color)
* Click 3-dot menu
* Click Open in New Tab
* CLick 3-dot on homescreen
* Click Settings

### Expected behavior
Action bar is white

### Actual behavior
Action bar is multi-select color (dark blue):
![image](https://user-images.githubusercontent.com/759372/84963389-1c1a9380-b0be-11ea-9439-5a159391ba31.png)

### Device information
* Android device: Galaxy S5
* Fenix version: Nightly 200617

**Comment by s-ankur** [comment]
Duplicate of #8114

**Comment by mcarare** [comment]
Closing as duplicate of #8114.
