### ISSUE TITLE
FNX2-13588 ⁃ How to stay up to date with new features in Fenix Nightly?

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#11719]
### What is the user problem or growth opportunity you want to see solved?
It's _very_ difficult to stay up to date with what the new changes/features are.

So, what's the most efficient way to do this? FYI I'm using Firefox Nightly on on Android, which I know means it's less stable than Firefox Beta on Android and therefore more difficult to keep up to date with new features. 

### How do you know that this problem exists today? Why is this important?
I didn't realise that collections now save their content and there have been many other changes I only found out after several weeks and probably even more that I'm not aware of yet! 

### Who will benefit from it?
Me! And all the other people who are using Nightly to stay up to date with new features and test them but are unaware of changes because there's no obvious (to me) centralised place to see what's new.

Cheers :slightly_smiling_face:

**Comment by SS1113** [comment]
You can follow this Fenix release page to know what's been new: https://github.com/mozilla-mobile/fenix/releases

**Comment by sheikh-azharuddin** [comment]
The link is for beta....how to know the major changes in nightly

**Comment by cadeyrn** [comment]
You can find merged PRs here: https://github.com/mozilla-mobile/fenix/pulls?q=is%3Apr+is%3Aclosed

**Comment by madb1lly** [comment]
Hi all,

Thanks for the tips. The releases page is useful, I hadn't thought of that, but some things stay in Nightly for months before they arrive in beta so it's not always a good indicator.

The PRs is a bit like looking for a needle in a haystack, most PRs aren't actually new features, just incremental fixes for them. Also it's not possible to subscribe to _just_ PRs is it? It's either watch releases or watch all conversations, no middle ground available AFAICT.

Cheers 🙂

**Comment by B0pol** [comment]
https://github.com/mozilla-mobile/fenix/commits/master

**Comment by sheikh-azharuddin** [comment]
@B0pol Quick question as per the page only one commit done since yesterday but you released 3 versions since then... wondering what are the changes? Or just version number update?

**Comment by klint** [comment]
You also can follow FirefoxPreview on Twitter.

**Comment by B0pol** [comment]
> @B0pol Quick question as per the page only one commit done since yesterday but you released 3 versions since then... wondering what are the changes? Or just version number update?

I'm not mozilla staff. And I guess it's automatically built every day even though there were no changes, I don't know.

**Comment by sheikh-azharuddin** [comment]
So it's just version number update only 🤣

**Comment by madb1lly** [comment]
> 
> 
> https://github.com/mozilla-mobile/fenix/commits/master

Yes @B0pol that's the page but there's no way I can find to _only_ follow that page via GitHub. The only options are _all_ conversations or releases only.



> 
> 
> You also can follow FirefoxPreview on Twitter.
> https://mobile.twitter.com/FirefoxPreview

Thanks @klint I do follow that, but haven't logged into Twitter since February! There's just too much retweeting of rubbish by the other people I follow (yes I know that's not a fault of this project).

Why not have a weekly newsletter for Fenix? Even small projects for only _parts_ of Firefox desktop have a newsletter, e.g. Fission. A newsletter would be a very helpful way to stay up to date with what's happening without being overwhelmed by all the activity on this repo (not to mention GV, AC, AS, etc).

Cheers 🙂

**Comment by B0pol** [comment]
> > https://github.com/mozilla-mobile/fenix/commits/master
> 
> Yes @B0pol that's the page but there's no way I can find to _only_ follow that page via GitHub. The only options are _all_ conversations or releases only.
> 
> > You also can follow FirefoxPreview on Twitter.
> > https://mobile.twitter.com/FirefoxPreview
> 
> Thanks @klint I do follow that, but haven't logged into Twitter since February! There's just too much retweeting of rubbish by the other people I follow (yes I know that's not a fault of this project).
> 
> Why not have a weekly newsletter for Fenix? Even small projects for only _parts_ of Firefox desktop have a newsletter, e.g. Fission. A newsletter would be a very helpful way to stay up to date with what's happening without being overwhelmed by all the activity on this repo (not to mention GV, AC, AS, etc).
> 
> Cheers slightly_smiling_face

you can use a feed agregator

For master branch commits: ahttps://github.com/mozilla-mobile/fenix/commits/master.atom

For the twitter account: https://nitter.net/FirefoxPreview/rss

**Comment by madb1lly** [comment]
Hi @B0pol,

Thanks for those links, I should have thought for looking for a feed on the commits page with Feedbro.The commits list is hardly a thrilling read though is it! 😆 And it's often difficult to see the overall feature progression from that list, especially for things which are actually enabled from GV, AC and AS. But in the absence of anything else that's really the best there is.

Thanks for the tip about the update scanner addon @klint.

I think the best solution would be a newsletter 📰.

Cheers 🙂

**Comment by kbrosnan** [comment]
https://discourse.mozilla.org/c/firefox-android/468 is the best place to follow new feature development andreip said that they are moving their @firefoxpreview Twitter posts to that forum. I don't believe that the team has bandwidth to do a newsletter or similar item focused on Nightly. We do roll up interesting features and fixes to the Beta and Release [release notes in Github](https://github.com/mozilla-mobile/fenix/releases/) and the Mozilla release note website. If we missed anything please reach out on [Discourse](https://discourse.mozilla.org) or [Element](https://wiki.mozilla.org/Matrix)

**Comment by madb1lly** [comment]
Thanks @kbrosnan 🙂
