### ISSUE TITLE
FNX-4848 ⁃ Select input elements non-functional

### ISSUE THREAD

**Issue by mystor** [mozilla-mobile/fenix#1171]
I was unable to fill out the Whistler registration form using Fenix due to the select dropdown options not being presented to me.

Expected: tapping a select input element shows a list of options

Actual: tapping a select input element adds focus highlighting, but does not show any browser UI

**Comment by Amejia481** [comment]
Hi @mystor, 
I [was trying to replicate the same issue](https://drive.google.com/file/d/1kGw_U1sEjVxYpfoU2la3cpelqq3AZDcG/view?usp=sharing) but without luck.

Could you provide me a bit of more info about your device OS version, Fenix app version and which specific select option, it is not working.

You could find the Fenix version details under the t**hree dots menu** ->  **Settings** -> **About Fenix** :)
![image](https://user-images.githubusercontent.com/773158/54932857-f3731080-4ef1-11e9-905a-6c99bfbab643.png)

**Comment by mystor** [comment]
The bug appears to have gone away, and I can no longer reproduce it.
