### ISSUE TITLE
FNX-12707 ⁃ [Bug]Tabs Tray: Tabs counter "∞" symbol padding issue

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11727]
## Steps to reproduce
1. Open more than 100 tabs
1. Check the Tabs counter

### Expected behavior
Properly displayed "**∞**" symbol

### Actual behavior
Padding issues

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly 200618 from 6/18
• Beta 5.2.0-beta.2 from 6/16

### Notes
► Screenshot
![rsz](https://user-images.githubusercontent.com/51314259/85010539-d8309880-b168-11ea-8f4a-fb4c80fe6675.png)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200618-125149!

**Comment by hakkikaancaliskan** [comment]
Is there a way to open 100 tabs easily :)

**Comment by hakkikaancaliskan** [comment]
Added some padding bottom if gonna show infinite character because infinite character's height is nearly half of numbers.
I'm unable to produce that cut-off @AndiAJ.
I'll open pr after some more investigation.
![resim](https://user-images.githubusercontent.com/17825767/85022346-d9b78c00-b17b-11ea-99ef-81fd63420daa.png)

**Comment by gabrielluong** [comment]
@hakkikaancaliskan I am assigning this to you since you aalready looking into this. Thank you for the help!

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_11rsz_screenshot_20200625-101350](https://user-images.githubusercontent.com/51314259/85676417-40cec680-b6cf-11ea-92c4-cd3b59e4df13.png)
