### ISSUE TITLE
[Bug] The keyboard covers the Fenix search bar entirely when in landscape mode

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11720]
## Steps to reproduce
The keyboard covers the entire search bar when in landscape mode. The keyboard I'm using is **Gboard** and it's in **default** size mode.

### Expected behavior
Shouldn't cover the search bar this makes it harder to see what has been typed. 

Fenix behaviour: 

![Screenshot](https://user-images.githubusercontent.com/42088907/84988322-55401b80-b131-11ea-89d8-767a0d309277.png)UNITO-UNDERSCORE!20200618-122423!

This is how Chrome does it: 

![Screenshot](https://user-images.githubusercontent.com/42088907/84988287-43f70f00-b131-11ea-9008-db58d66e19b4.png)UNITO-UNDERSCORE!20200618-122631!

### Actual behavior
Keyboard covers the entire search bar when in landscape mode.

### Device information
* Android device: **Motorola One Power, Android 10**.
* Fenix version: **`5.2.0-beta.2`** and **`Nightly 200617 18:01`**

**Comment by ShatteredPixel** [comment]
Hi, I'm the reporter of this issue. Please let me know if you need more information.

Thanks! :)

**Comment by ekager** [comment]
Closing as the reporter deleted their account
