### ISSUE TITLE
FNX-4849 ⁃ Verify a11y behavior on the settings screens

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1172]
As a user with accessibility needs, I want to be able to interact with my browser settings, understand my options, and make changes. 

Context: We got a report that while using Samsung's Talkback we were focusing on the radio buttons, not the row causing the label never to be read. Another odd behavior is that when you go to settings it starts reading from the bottom of the list versus the top.

**Comment by vesta0** [comment]
@eeejay any recommendations?

**Comment by eeejay** [comment]
I'll look into this. I see this as an issue with the radio buttons in the site permissions panel. Did the user mention anything else?
