### ISSUE TITLE
FNX-12718 ⁃ [Bug] Tab counter flickers

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#11739]
Put `Log.d()` to necessary lines to watch `count`.
https://github.com/mozilla-mobile/fenix/blob/54d7fc182449cf2bc72892729d7dd78310333f3f/app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounter.kt#L53 

Open new tab, go home, open tab tray, tap to addTab fab etc. Watch changes of `this.count`.

Looks like `this.count` reset to 0 while navigating, thus `setCount()` works on every newTab fab pressing and this causes flicker.

**Comment by hakkikaancaliskan** [comment]
Looks like we need to save tab count somewhere out of there to prevent resetting.

**Comment by hakkikaancaliskan** [comment]
Properly handling this.count doesn't solve issue. Looks like problem is something another. Investigating.

**Comment by hakkikaancaliskan** [comment]
Fixed issue.
Tab counter init was adding 3dp top and right padding, idk why.
I've changed it.

**Comment by gabrielluong** [comment]
> Fixed issue.
> Tab counter init was adding 3dp top and right padding, idk why.
> This padding causing the flicker.
> I've changed it.

@hakkikaancaliskan Would you be available to also upstream these changes to android-components? https://github.com/mozilla-mobile/android-components/blob/ca3eff8a75ec791d718e5ceddc03285c8357836e/components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt

Ideally, we would always use the components from android-components since it is meant to be re-usable beyond Fenix. We have another issue https://github.com/mozilla-mobile/android-components/issues/2743 to eventually upstream all the downstream Fenix changes to the android-components and remove the duplication in Fenix. You can build the sample-browser in the android-components repo to test any TabCounter changes.

**Comment by hakkikaancaliskan** [comment]
> 
> 
> > Fixed issue.
> > Tab counter init was adding 3dp top and right padding, idk why.
> > This padding causing the flicker.
> > I've changed it.
> 
> @hakkikaancaliskan Would you be available to also upstream these changes to android-components? https://github.com/mozilla-mobile/android-components/blob/ca3eff8a75ec791d718e5ceddc03285c8357836e/components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt
> 
> Ideally, we would always use the components from android-components since it is meant to be re-usable beyond Fenix. We have another issue [mozilla-mobile/android-components#2743](https://github.com/mozilla-mobile/android-components/issues/2743) to eventually upstream all the downstream Fenix changes to the android-components and remove the duplication in Fenix. You can build the sample-browser in the android-components repo to test any TabCounter changes.

I've done this in a gist because I'm not good at components. Is this enough or need more job?
https://gist.github.com/hakkikaancaliskan/d11a07c5a963051b28498fdba1a1c06a

**Comment by gabrielluong** [comment]
> > > Fixed issue.
> > > Tab counter init was adding 3dp top and right padding, idk why.
> > > This padding causing the flicker.
> > > I've changed it.
> > 
> > 
> > @hakkikaancaliskan Would you be available to also upstream these changes to android-components? https://github.com/mozilla-mobile/android-components/blob/ca3eff8a75ec791d718e5ceddc03285c8357836e/components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt
> > Ideally, we would always use the components from android-components since it is meant to be re-usable beyond Fenix. We have another issue [mozilla-mobile/android-components#2743](https://github.com/mozilla-mobile/android-components/issues/2743) to eventually upstream all the downstream Fenix changes to the android-components and remove the duplication in Fenix. You can build the sample-browser in the android-components repo to test any TabCounter changes.
> 
> I've done this in a gist because I'm not good at components. Is this enough or need more work?
> https://gist.github.com/hakkikaancaliskan/d11a07c5a963051b28498fdba1a1c06a

Ideally, a PR for components so that it could be reviewed and landed by a peer. Feel free to reach out on https://chat.mozilla.org/#/room/#android-components:mozilla.org if you need help.

**Comment by hakkikaancaliskan** [comment]
> 
> 
> > > > Fixed issue.
> > > > Tab counter init was adding 3dp top and right padding, idk why.
> > > > This padding causing the flicker.
> > > > I've changed it.
> > > 
> > > 
> > > @hakkikaancaliskan Would you be available to also upstream these changes to android-components? https://github.com/mozilla-mobile/android-components/blob/ca3eff8a75ec791d718e5ceddc03285c8357836e/components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt
> > > Ideally, we would always use the components from android-components since it is meant to be re-usable beyond Fenix. We have another issue [mozilla-mobile/android-components#2743](https://github.com/mozilla-mobile/android-components/issues/2743) to eventually upstream all the downstream Fenix changes to the android-components and remove the duplication in Fenix. You can build the sample-browser in the android-components repo to test any TabCounter changes.
> > 
> > 
> > I've done this in a gist because I'm not good at components. Is this enough or need more work?
> > https://gist.github.com/hakkikaancaliskan/d11a07c5a963051b28498fdba1a1c06a
> 
> Ideally, a PR for components so that it could be reviewed and landed by a peer. Feel free to reach out on https://chat.mozilla.org/#/room/#android-components:mozilla.org if you need help.

Opened pr, https://github.com/mozilla-mobile/android-components/pull/7446
