### ISSUE TITLE
FNX-12716 ⁃ [Bug] Dark Mode bug

### ISSUE THREAD

**Issue by anmol257** [mozilla-mobile/fenix#11735]
## Steps to reproduce
Normal operation of app in dark mode 
Switch to any new page or click on any link.

### Expected behavior
Dark mode is persistent. .

### Actual behavior
When moving to another page/link ;the dark mode switches off for a second and then resumes;leading to sudden flash of white light on eyes.

### Device information
Androud 5.1 lolipop

* Android device: ?samsung j2 pro
* Fenix version: ?
Latest available on playstore

**Comment by Dunexus** [comment]
If i understand well, you are talking about white flashes on page loading while in dark mode.
This is tracked by https://github.com/mozilla-mobile/fenix/issues/6313.

**Comment by kbrosnan** [comment]
Is this in the web content or is this the app UI?

**Comment by anmol257** [comment]
> If i understand well, you are talking about white flashes on page loading while in dark mode.
> This is tracked by #6313.

Yeah thanks will be clsing the issue here.
