### ISSUE TITLE
FNX-12710 ⁃ Please reopen #9483

### ISSUE THREAD

**Issue by gh7893** [mozilla-mobile/fenix#11730]
I left a crash report in #9483 (which still occurs in the latest nightly), unfortunately that bug report seems to be abandoned and I cannot reopen it as I am not the original poster. Also paging @liuche.

https://github.com/mozilla-mobile/fenix/issues/9483#issuecomment-643327690

I would be very grateful if someone could go ahead and would reopen #9483. Thank you.

**Comment by ekager** [comment]
Done!
