### ISSUE TITLE
FNX2-13594 ⁃ [Bug]Tabs Tray: Site preview are lost after resuming Fenix

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11733]
## Prerequisites
Have a couple of open tabs

## Steps to reproduce
1. Open the Tabs Tray
1. Tap one of the open tabs
1. Put Fenix in background
1. Resume Fenix check the previously opened web sites screenshot
1. Tab on another tab
1. Open the Tabs Tray
1. Put Fenix in background 
1. Resume Fenix check the previously opened web sites screenshot

### Expected behavior
The screenshots are properly displayed

### Actual behavior
The screenshots are lost

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
* Fenix version: Nightly 200618 from 6/18

### Notes
► Video
![20200618-163749](https://user-images.githubusercontent.com/51314259/85027405-901e6f80-b182-11ea-982b-9b294d2f2525.gif)

**Comment by jonalmeida** [comment]
This is the effect of https://github.com/mozilla-mobile/android-components/issues/7413.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-120918](https://user-images.githubusercontent.com/51314259/91290942-fdf7a080-e79c-11ea-9390-4aa7a901cb3d.gif)
