### ISSUE TITLE
FNX-12717 ⁃ [Bug] Dark mode not working in reader mode.

### ISSUE THREAD

**Issue by anmol257** [mozilla-mobile/fenix#11737]
### Device information
* Android device: ?
* Fenix version: ?

**Comment by csadilek** [comment]
@anmol257 reader mode has its own appearance controls. You can find them by activating reader mode, then opening the three dot menu and tap on "Appearance". You can change the font and background color there.

We have a ticket on file so reader mode automatically follows the app scheme: https://github.com/mozilla-mobile/fenix/issues/3289. Please follow along there.
