### ISSUE TITLE
FNX-4850 ⁃ Ship the WebCompat GoFaster extension

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1174]
### Why/User Benefit/User Problem
Improve website compatibility with Fenix.

### What / Requirements
Bundle Mozilla's WebCompat GoFaster extension in Fenix:

https://wiki.mozilla.org/Compatibility/Go_Faster_Addon
https://github.com/mozilla/webcompat-addon

The extension injects JS content or spoofs UAs to make individual websites compatible with Gecko. The WebCompat extension currently ships in all branches of Fennec and Firefox Desktop.

We do not need this extension for Fenix MVP, but it should block the Fennec/Fenix transition.

### Acceptance Criteria (how do I know when I’m done?)
The WebCompat GoFaster extension is bundled in Fenix and the extension correctly fixes some test website (TBD!).

**Comment by cpeterso** [comment]
This might require a little GV work, but the A-C team should start the initial investigation to see what Fenix/A-C needs from GV.

**Comment by pocmo** [comment]
Met with the webcompat folks in Whistler and they are already on it.

CC @denschub @ksy36 @wisniewskit

**Comment by denschub** [comment]
👍

This is something that will be on our plate for Q3.

**Comment by cpeterso** [comment]
@denschub - Any updates on shipping the WebCompat extension in Fenix? GeckoView might need to make some API changes, but we won't know until someone tries to test the WebCompat extension in Fenix..

**Comment by denschub** [comment]
I've shared a little status update on Slack [here](https://mozilla.slack.com/archives/CLUREFWM6/p1566312605011700), but didn't think about updating GitHub. Basically, I got the extension running as an Android-Component inside the Sample Browser, and everything works just fine there. I planned on doing the Fenix integration this week, but I've got a bit distracted in the last two days, so I'm not sure if that's happening. I expect to have it embedded in Fenix next week, and I can update you again. But as it appears to be working just fine in the Reference Browser, I'm somewhat optimistic.

**Comment by cpeterso** [comment]
> I got the extension running as an Android-Component inside the Sample Browser, and everything works just fine there. I planned on doing the Fenix integration this week ... But as it appears to be working just fine in the Reference Browser, I'm somewhat optimistic.

Cool! So it sounds like we might not need to fix any GV bugs or APIs. In that case, I am optimistically removing this issue's `needs:gv` label.

**Comment by liuche** [comment]
Does this require Fenix to have WebExtensions working? which we'll do in Q4.

**Comment by denschub** [comment]
Actually, given https://github.com/mozilla-mobile/fenix/pull/5432, this should be closed now. :)
