### ISSUE TITLE
[Bug] Top Sites borders are superfluous and look messy

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11743]
## Steps to reproduce
Open Fenix, show home and see top sites.

### Expected behavior
Clean icons without adornment.

### Actual behavior
Borders around icons that make it harder to see icon content (smaller) and add virtually nothing to the experience.

Both Edge and previous versions of Fenix do better here.

Edge:

![signal-2020-06-18-144725](https://user-images.githubusercontent.com/152493/85060130-b5a37d00-b172-11ea-885f-7d64e903ac40.png)UNITO-UNDERSCORE!002!

older Fenix:

![signal-2020-06-18-144725](https://user-images.githubusercontent.com/152493/85060150-be944e80-b172-11ea-96ec-730d5f6a4a5a.png)UNITO-UNDERSCORE!001!

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 200618 06:01 (Build #21700609)
AC: 47.0.20200617190137, 9fe469d33
GV: 79.0a1-20200617093637
AS: 61.0.2

**Comment by AmyYLee** [comment]
The intent of the border is to safeguard against contrast issues between light/dark themes since we cannot predict the colour of the site icon.

**Comment by yoasif** [comment]
@AmyYLee Edge seems to handle the dark mode without issues on my device:

![signal-2020-06-24-013526](https://user-images.githubusercontent.com/152493/85504910-083dc880-b5bb-11ea-9103-1cf6a76612af.png)

**Comment by cadeyrn** [comment]
> The intent of the border is to safeguard against contrast issues between light/dark themes since we cannot predict the colour of the site icon.

It's true that the colour of the site icon can not be predicted. But I don't see how the border is supposed to give any benefit, the border don't help with that. And all icons are clearly enough separated by the large space between them. To be honest _my_ biggest concern the look and feel. I think it would look much more modern without a border. The new Firefox is modern app with a modern design but the top sites look outmoded in my opinion, especially with the padding between the border and the icon itself.

I vote for re-adding the "needs:UX-feedback" label at least to investigate if there are better solutions.

**Comment by apbitner** [comment]
We've decided to keep borders for now as part of work done in #13765

**Comment by madb1lly** [comment]
Hi @apbitner,
But #13765 is closed?
Cheers 🙂
