### ISSUE TITLE
[Bug] links in the email are not handled properly

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11749]
## Steps to reproduce
Click the link in the email such as track order(screenshot attached) it is showing address not found on clicking it.
It should open the website but instead shows address not found
Works fine in chromium browsers

### Expected behavior
Link should open properly after redirect and resolve

### Actual behavior
Address not found error showing.fennec has same issue

### Device information
* Android device: ? A10
* Fenix version: ? Latest

![6916](https://user-images.githubusercontent.com/58127841/85066303-3e83de00-b19e-11ea-95d7-ae417cac9046.png)

![Screenshot](https://user-images.githubusercontent.com/58127841/85066258-201de280-b19e-11ea-90ce-d5fc8f0fb477.jpg)UNITO-UNDERSCORE!20200619-012538!

**Comment by sheikh-azharuddin** [comment]
Seems sms links are not handled properly
![Screenshot_20200620-151419](https://user-images.githubusercontent.com/58127841/85198777-c4a53f00-b2da-11ea-807d-408e85386276.jpg)

**Comment by s-ankur** [comment]
I think this fixed now

**Comment by sheikh-azharuddin** [comment]
Nope
![Screenshot_20200712-142917](https://user-images.githubusercontent.com/58127841/87242623-0038b200-c41e-11ea-9d35-6bf361818d84.jpg)

**Comment by ekager** [comment]
@sheikh-azharuddin are you still seeing this?

**Comment by sheikh-azharuddin** [comment]
Yes fixed
