### ISSUE TITLE
FNX-12721 ⁃ [BUG] Browser hangs while downloading a file

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#11741]
Browser stops working as soon as I add any file to download. And then crashes. Happens every time.

Device: Xiaomi Redmi Note 4 Android 7.0

Fenix version: Nightly 200618 06:01 (Build #21700609)
AC: 47.0.20200617190137, 9fe469d33
GV: 79.0a1-20200617093637
AS: 61.0.2

**Comment by Amejia481** [comment]
@RealGJ would you mind sharing the file that you are trying to download? I could help us to find the issue :)

**Comment by RealGJ** [comment]
@Amejia481 it's happening with every file. I've downloaded just a image from Google of size about 40 kB. But it crashes everytime irrespective of size and type of file.

**Comment by leela52452** [comment]
hello @RealGJ 
* tap three dot
* settings
* about firefox preview
* crashes
* socorro

try again downloading file
* firefox crashes
* restart firefox
* tapping socorro will open new tab, copy hyperlink and paste here

OR

provide hyperlink to the file

![Screenshot_20200619-130123_Firefox Preview](https://user-images.githubusercontent.com/52065244/85108394-2e501b00-b1ff-11ea-8cda-b3130c53bc06.jpg)

**Comment by RealGJ** [comment]
@leela52452 hello. I've tried the mentioned steps, but that crash isn't recorded there. Actually browser stops working, so I reported that system log to Mozilla.

Here is hyperlink to file:

https://www.google.com/url?q=https://www.westlake.com/sites/default/files/inject1.pdf&sa=U&ved=2ahUKEwjtorzn64_qAhXXXCsKHdYHDsAQFjAAegQIARAB&usg=AOvVaw1yMArq8Jot8FFA_fuCyETH

**Comment by leela52452** [comment]
@RealGJ 

> so I reported that system log to Mozilla.

as far as i know, you must attach log on this issue.

btw, thank you for sharing hyperlink. i have no issue downloading it.

**Comment by RealGJ** [comment]
@leela52452 please find the bug video here:

https://mega.nz/file/3YozjChR#MnptdjfCmq4P_cXRMQIUiTOqwUH0IXz4Du72z4IGzgc

**Comment by RealGJ** [comment]
Update: Problem persists in 

Nightly 200621 06:01 (Build #21730611)
AC: 47.0.20200618130101, 0e690abd2
GV: 79.0a1-20200617093637
AS: 61.0.2 

Too

**Comment by AndiAJ** [comment]
Hi @Amejia481 **can't repro** on the latest **Nightly Build 200622 from 6/22** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**Comment by RealGJ** [comment]
I was able to reproduce this issue on :

Nightly 200622 06:01 (Build #2015747699)
AC: 47.0.20200618130101, 0e690abd2
GV: 79.0a1-20200617093637
AS: 61.0.2

**Comment by sflorean** [comment]
Tested with Xiaomi Redmi Note 8T (Android 9) on latest Nightly and couldn't reproduce the crash, checked about:crash also, following the steps from the user. @RealGJ do you have any additional settings, addons installed?

**Comment by kbrosnan** [comment]
Looking at the video this is an ANR. If you still get this please provide a screenshot or the text of the ANR stacktraces section of the Google Feedback form.

![Screenshot_2020-06-22 File on MEGA](https://user-images.githubusercontent.com/250273/85315515-0c110400-b470-11ea-88ed-adb19a4ded82.png)

**Comment by RealGJ** [comment]
@sflorean yes. I have ublock origin, Dark reader and HTTPS Everywhere installed.

**Comment by RealGJ** [comment]
Update : Can't reproduce issue in latest nightly.

Nightly 200624 06:01 (Build #2015748083)
AC: 47.0.20200623130149, 88694edfb
GV: 79.0a1-20200622093309
AS: 61.0.2

Closing. Thank You
