### ISSUE TITLE
[Bug] Site previews in total dark mode (with DarkReader on ) merge visually with Fenix dark background

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#11758]
## Steps to reproduce
Activate Dark mode on Fenix
Install and activate DarkReader

### Expected behavior
in Tab Tray, Site Previews dark background should be told apart from Fenix dark background 

### Actual behavior
Unlike light mode, there is no border around site previews nor any shade of grey to tell both backgrounds apart (and a small difference in background shades)

See the different behaviour between light and dark mode (in light mode there is a thin darker border around the site previews)

![image](https://user-images.githubusercontent.com/218971/85112395-dcff5600-b215-11ea-9ae1-914f4fc8ddc4.png)

### Device information
* Android device: Redmi Note 7
* Fenix version: 2015746931

**Comment by apbitner** [comment]
@topotropic for review

**Comment by topotropic** [comment]
Thanks for the feedback. 
Let's add a border to the thumbnail in <color name="dark_grey_10">#52525E</color>.

**Comment by klint** [comment]
Has anything been implemented so far? 😊
