### ISSUE TITLE
FNX-12739 ⁃ [Bug] toolbar customize showing both selected

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11756]
## Steps to reproduce
Open settings> customize> toolbar
It shows both selected

### Expected behavior
Should show one radio button selected

### Actual behavior
Showing both radio button selected

### Device information
* Android device: ? A10
* Fenix version: ? Latest nightly

![6919](https://user-images.githubusercontent.com/58127841/85105694-66a12a80-b1fa-11ea-8894-40ed02f33ff8.png)

**Comment by igalic** [comment]
i had neither selected, even though the toolbar was on top

**Comment by sheikh-azharuddin** [comment]
Since this is fixed in latest version, closing the case

**Comment by sheikh-azharuddin** [comment]
Since this is fixed in latest version, closing the case
