### ISSUE TITLE
Cloud download / Save to cloud

### ISSUE THREAD

**Issue by anmol257** [mozilla-mobile/fenix#11754]
### What is the user problem or growth opportunity you want to see solved?
Users should have the option of saving the files directly to the cloud, rather than only saving it to their device. This eases accessing the files on different devices of the same account easily as well sharing it to others without dependence on uploading speed.

### How do you know that this problem exists today? Why is this important?
It is important as 5g has arrived. The future is here, the future is about cloud computing where everything is connected to it via internet.
It is the reason why many multinationals are heavily investing in the cloud.

### Who will benefit from it?
Everyone, all the users who
*use firefox on more one device
*need more storage space on their device to access the file than they have.
*want to view the file temporarily without saving it on their phone.

### Suggestion 
Users should be given the option to connect any cloud of their choice like google drive, drop box, one drive etc. (This may as well help in generating revenue for Mozilla)

### Intent of this idea
To make Fenix more user-friendly and future-ready.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2375)

**Comment by Amejia481** [comment]
cc: @vesta0

**Comment by Daplugg23** [comment]
This would be a great feature for Firefox!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812811

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
