### ISSUE TITLE
[Bug] Embedded Facebook video does not show

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#11755]
i was trying to reproduce #3285
video is not visible, if

* etp off
* etp strict
* etp standard

i am not sure how to proceed, excuse for new issue

## Steps to reproduce
https://www.popsugar.com/family/Viral-Video-Baby-Boy-Talking-His-Dad-46235433

### Expected behavior
should show video

### Actual behavior
video not shown

### Device information
* Android device: ?
* Fenix version: Build #2015747025
![Screenshot](https://user-images.githubusercontent.com/52065244/85099841-0a380e00-b1ee-11ea-8f93-3fb1b6918cc1.jpg)UNITO-UNDERSCORE!20200619-104145!UNITO-UNDERSCORE!Firefox Nightly!

**Comment by sheikh-azharuddin** [comment]
Also sometime embedded twitter feed does not show...

**Comment by leela52452** [comment]
video not working on 5.2.0 also with etp on, standard, strict

**Comment by kbrosnan** [comment]
This sounds like expected behavior. Video embeds are a way to track users across websites.
