### ISSUE TITLE
[Bug] unable to export privacy badger settings

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#11759]
## Steps to reproduce
* remove all installed addons
* delete browsing data on quit (all check)
* clear cache of app
* install privacy badger (check: run in private browsing)
* settings of privacy badger
* change some settings
* manage user data: Export user data
    1. Expected behavior
export settings
    1. Actual behavior
cannot complete request
    1. Device information
* Android device: ?
* Fenix version: 5.2.0

![Screenshot](https://user-images.githubusercontent.com/52065244/85121198-e4bdfb00-b213-11ea-850e-f5fac8cf9842.jpg)UNITO-UNDERSCORE!20200619-151955!UNITO-UNDERSCORE!Firefox Preview!

**Comment by SS1113** [comment]
This has already been reported here: https://github.com/mozilla-mobile/android-components/issues/6463.

Duplicate issue. Thanks for the report!

**Comment by ekager** [comment]
Closing for the AC issue
