### ISSUE TITLE
FNX-12734 ⁃ [Bug] caching behavior

### ISSUE THREAD

**Issue by chrisvdb** [mozilla-mobile/fenix#11753]
## Steps to reproduce
Open /. (https://slashdot.org/).
Close.
Open /. again a few hours/days later.

### Expected behavior
Content of /. has changed.

### Actual behavior
Exactly same outdated cached /. content is shown. Refreshing the page (either pulling down or refresh button) updates the content. This is not required on Firefox for Android or Firefox on my desktop, only on Firefox Preview.

### Device information
* Android device: Xiaomi RedMi 8
* Fenix version: 5.2

**Comment by kbrosnan** [comment]
Dupe #5869

**Comment by chrisvdb** [comment]
Note that this behavior is not only with back button as described in #5869. I will in any case monitor that bug and will retest once the fix hits stable.

**Comment by chrisvdb** [comment]
Ok, so the issue was related to the Corrections feature that apparently saves page state as part of the collection.
