### ISSUE TITLE
FNX-12749 ⁃ [Bug] autoplay block not working

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11766]
## Steps to reproduce
Even though autoplay is blocked in site permissions, some sites still play the video. Please fix this critical bug. Even in Google news articles the video plays in the background.

Sample site:
https://in.reuters.com/article/us-alphabet-google-chrome-exclusive/exclusive-massive-spying-on-users-of-googles-chrome-shows-new-security-weakness-idINKBN23P0JO

### Expected behavior
The video should not play automatically

### Actual behavior
Video plays in the background

### Device information
* Android device: ? A10
* Fenix version: ? Latest nightly

![Screenshot](https://user-images.githubusercontent.com/58127841/85132683-cc0c1000-b228-11ea-885f-8bfeaebddb51.jpg)UNITO-UNDERSCORE!20200619-175832!

![Screenshot](https://user-images.githubusercontent.com/58127841/85132701-d4fce180-b228-11ea-8c8a-3cb53b31fb90.jpg)UNITO-UNDERSCORE!20200619-175819!

**Comment by ekager** [comment]
Hi @sheikh-azharuddin have you ever changed this setting? If you toggle between one of the other settings and back to blocked, is this resolved?

**Comment by sheikh-azharuddin** [comment]
Earlier I even tried with toggling the settings but autoplay used to play....now I browsed several articles this works fine as expected...autoplay is blocked👍

Just curious was there any recent change 🤔

**Comment by ekager** [comment]
I did find a bug that if you toggled the settings between "allowed on wifi" and "blocked" sometimes it would change the setting back to allowed on wifi. That bug should be fixed by https://github.com/mozilla-mobile/fenix/pull/11832 . I'm going to close this for now, but please open a new bug if you're seeing this again  :)
