### ISSUE TITLE
FNX-12750 ⁃ [Bug] PWAs have large, toolbar-sized gap at the top of the screen

### ISSUE THREAD

**Issue by EmberHeartshine** [mozilla-mobile/fenix#11767]
## Steps to reproduce
1. Go to any PWA site
1. In the hamburger menu, tap "install"
1. Open PWA
    1. Expected behavior

* The PWA should display full-screen with no fenix UI elements
    1. Actual behavior
* Large gap appears at the top of the screen:

* 

* [Screenshot 1](https://user-images.githubusercontent.com/50666308/85133096-0d3ff800-b208-11ea-8977-cbf526a64026.png) (https://5e.tools)

* 

* [Screenshot 2](https://user-images.githubusercontent.com/50666308/85133150-2779d600-b208-11ea-8591-cc79d44ce91c.png) (https://rec.net/)
    1. Device information
* Android device: LG V20 (Android 8.0.0)
* Fenix version: Firefox Preview 5.2.0 (Build #21701706), AC: 46.0.0, bca4c5c91, GV: 78.0-20200612174529, AS: 60.0.0

**Comment by sheikh-azharuddin** [comment]
Fixed in latest update bro...just now installed the pwa and it is showing in full screen.
No top white/black thick border

Nightly 200619 06:01 (Build #2015747123)
AC: 47.0.20200618130101, 0e690abd2
GV: 79.0a1-20200617093637
AS: 61.0.2

**Comment by EmberHeartshine** [comment]
You may have noticed I'm not on the nightlies, "bro".

**Comment by SS1113** [comment]
@EmberHeartshine  Thanks for the report! This has already been reported and fixed in the latest **`Nightly 200619 06:01`**.
Refer this for more info: https://github.com/mozilla-mobile/fenix/issues/11708.

**Comment by B0pol** [comment]
Uh, it's also in 5.2.0 (playstore version 5.2.0.21701705) and also happen with custom tabs :/

**Comment by ekager** [comment]
Closing because fixed in Nightly.
