### ISSUE TITLE
FNX2-13604 ⁃ [Bug] collection deletion inconsistent behaviour

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11763]
## Steps to reproduce
Add a website to the collection
Remove the website using the cross button it will delete the collection.
However if you try to delete the collection instead of the website it shows a confirmation prompt as shown in the screenshot.

### Expected behavior
When there is just one website in a collection, while deleting it should show a confirmation that deleting it will delete the collection too

### Actual behavior
Removing the only website in a collection does not show any confirmation while deleting the collection it shows a confirmation prompt

### Device information
* Android device: ? A10
* Fenix version: ? Latest nightly

![Screenshot](https://user-images.githubusercontent.com/58127841/85129464-b0057000-b222-11ea-8043-971b56e1ebda.jpg)UNITO-UNDERSCORE!20200619-171039!

![Screenshot](https://user-images.githubusercontent.com/58127841/85129435-a11ebd80-b222-11ea-903e-3fa3c38f66f3.jpg)UNITO-UNDERSCORE!20200619-171021!

**Comment by AmyYLee** [comment]
@topotropic and @betsymi for review - Should there be a warning if you delete the last tab in a collection which automatically removes the collection...which brings another interesting point to consider. Should we be removing the collection if the user deletes the last tab in it?

**Comment by ValentinTimisica** [comment]
My opinion is that we should show a confirmation dialog ("Are you sure you want to delete Collection 1") when we remove the last tab from that collection.

**Comment by betsymi** [comment]
If deleting the last tab in a collection deletes the collection itself, yes we can have a dialog with the following copy. We can revisit that behavior at a future date if we want to.

Please note there is a headline and body copy, which we don't have in many of our dialogs just yet. We are slowly updating our dialogs to improve them. 

**Delete collection %1$s?**

Deleting this tab will delete the entire collection. You can create new collections at any time.

CANCEL | DELETE

Two reasons why I'm recommending this particular copy:

- "Are you sure" assumes the user intended to do this action, and they may not have. They may not have known deleting this tab would delete the collection itself. A more neutral tone is recommended. 
- Incorporating a headline ('Delete collection %1$s?') makes clear what will happen if indeed this behavior is unexpected. The body copy explains why. Users don't necessarily need to read the body copy to make a decision, but we offer the explanation there if they are curious as to why. 

Could you post a screenshot here when this has been implemented so I can have for my documentation purposes? Thank you!

**Comment by ebalazs-sv** [comment]
@betsymi Hi! In comment https://github.com/mozilla-mobile/fenix/issues/11763#issuecomment-648908113, the wording "Are you sure" is used. 
I had tested this issue on Nightly 200707 GV 80, from 7/7 with Google Pixel 2 (Android 9) and the dialog does not have this wording. 
Also, in case the collection is called "Colection x", then the word "collection" is duplicated in the question's dialog.

Can you please confirm if this is the desired text for the dialog? Screenshot: 
![Screenshot_20200707-111628](https://user-images.githubusercontent.com/48799384/86746505-c8a7bf80-c043-11ea-9fea-c7a6fa80e849.png)
Thanks!

**Comment by ValentinTimisica** [comment]
@ebalazs-sv I think @betsymi said that "Are you sure" is not ok to use and "A more neutral tone is recommended". This is why she recommended the following strings: 

"Delete collection %1$s?

Deleting this tab will delete the entire collection. You can create new collections at any time.

CANCEL | DELETE"

**Comment by ebalazs-sv** [comment]
@ValentinTimisica Thanks! Since this is the required string, I will mark this issue as verified.
For the duplicated "collection" word, when the collection is called "Collection x", I filed a new issue: https://github.com/mozilla-mobile/fenix/issues/12339

**Comment by betsymi** [comment]
> @betsymi Hi! In comment [#11763 (comment)](https://github.com/mozilla-mobile/fenix/issues/11763#issuecomment-648908113), the wording "Are you sure" is used.
> I had tested this issue on Nightly 200707 GV 80, from 7/7 with Google Pixel 2 (Android 9) and the dialog does not have this wording.
> Also, in case the collection is called "Colection x", then the word "collection" is duplicated in the question's dialog.
> 
> Can you please confirm if this is the desired text for the dialog? Screenshot:
> ![Screenshot_20200707-111628](https://user-images.githubusercontent.com/48799384/86746505-c8a7bf80-c043-11ea-9fea-c7a6fa80e849.png)
> Thanks!
> I will remove the qa:needed label for now.

Good eye @ebalazs-sv! We are slowly updating some of our dialogs to this new pattern. 

I did make a mistake with the duplicated word, so thank you for filing a new issue to update that.
