### ISSUE TITLE
[Bug] Active icon of Enhanced Tracking Protection in bottom bar has visual glitches

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#11774]
## Steps to reproduce
1. Have Enhanced Tracking Protection (ETP) enabled
1. Visit a website that triggers ETP, e.g. https://www.bbc.com 

### Expected behavior
The icon notifying the user of active ETP should appear without visual glitches.

### Actual behavior
The active ETP icon shows visual glitches.

![enhanced tracking protection non-pbm](https://user-images.githubusercontent.com/42788925/85174456-b7a23480-b275-11ea-9063-dbc55fb2fc44.png)

![enhanced tracking protection PBM](https://user-images.githubusercontent.com/42788925/85174465-ba9d2500-b275-11ea-9b79-9edd4e00024a.png)

### Device information
* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version:
Nightly 200619 06:01 (Build #2015747121)
AC: 47.0.20200618130101, 0e690abd2
GV: 79.0a1-20200617093637
AS: 61.0.2

**Comment by Amejia481** [comment]
It's very likely to be an Android OS version specific issue. QA  would you mind helping us testing on devices with Android 6.0.1

**Comment by AndiAJ** [comment]
Hi @Amejia481 , I've just checked this matter on the latest **`Nightly Build 200706 from 7/6`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

The inconsistency highlighted by @hwinnemoe is indeed reproducible on the OnePlus A3 (Android 6.0.1)

❌  Screenshot OnePlus A3
![rsz_screenshot_20200706-104815](https://user-images.githubusercontent.com/51314259/86569849-b6f8e600-bf77-11ea-84cd-a3d34fd9df7c.png)

✔️ Screenshot Google Pixel 3a
![rsz_screenshot_20200706-105155](https://user-images.githubusercontent.com/51314259/86569820-af394180-bf77-11ea-8d9d-58a60401723b.png)

**Comment by Amejia481** [comment]
Thanks @AndiAJ 
@ekager I think you have fixed similar issues before do you have an idea that what could be happening in this case? :)

**Comment by ekager** [comment]
mm usually before these have been vectors that we're setting incorrectly in xml. This is a Lottie file so I'm assuming it's a different issue.

**Comment by hwinnemoe** [comment]
Since there are plans to remove Lottie (#7435), this might not be worth looking into until a decision was made, is it?

**Comment by AndiAJ** [comment]
Hi, I'll close this issue as per the change from [#7435](https://github.com/mozilla-mobile/fenix/issues/7435#issuecomment-710697665).
