### ISSUE TITLE
FNX2-13607 ⁃ Automatically Request the Desktop Version of Some Sites Everytime, While Requesting the Mobile Version of All Sites Not Specifically Listed

### ISSUE THREAD

**Issue by CharmCityCrab** [mozilla-mobile/fenix#11777]
### What is the user problem or growth opportunity you want to see solved?
On Firefox for Android, I generally want to load the mobile versions of sites. Some sites (Like Yelp) have really, likely intentionally, awful mobile versions of their sites, though, in what appears to be an effort to force people to use apps that they prefer not to use instead of the mobile sites.

So, for those sites, what I would like to do is have my copy of Firefox for Android automatically request the desktop versions of them every session every time without further user intervention after first enabling it (Set it and forget it), while still continuing to always request the mobile versions of every other site every session every time.

I know how to click the hamburger menu and check or uncheck "Request desktop site". That's not what I'm asking about. I would like a setting that allows me to basically make a list of domains (Like a whitelist or or a blacklist) that always will load in desktop mode and have everything else always load in mobile mode, without having to keep checking and unchecking the box all the time.

### How do you know that this problem exists today? Why is this important?
I know the problem exists from personal experience.  Granted, I am still using Fennec, but I have spoken with Fenix users who say that the issue also exists on Fenix, and of course eventually I will be upgraded to Fenix along with everyone else.

It is important both for ease of use reasons (Preventing users from having to fiddle with settings every single time they visit a site), and also to prevent to preserve and enhance user freedom.  When a poor mobile site shunts a user into a proprietary controlled app, they no longer have the benefit of Firefox's built-in tracking and privacy protections, a dark theme (if enabled by the user), the ability, at their own discretion if they desire to, of using of ad-blockers and content blockers, the ability to keep a video playing even when viewing other tabs or other apps through an extension, and so on and so forth.

Potentially, implementing this feature could be as simple as adding an "Always open this site in desktop mode" next to "Open this site in desktop mode", or could even be included buried in some sort of advanced options menu where an "always open in desktop mode" list could be maintained for users who seek it out and desire it.

Firefox would benefit from implementing this feature in the browser app itself instead of people's only similar option being a user-agent change extension (If one is even made available for Fenix), because an in-browser option here would always present the most current Firefox for Android user-agent to sites that are displayed as mobile sites, and would be able to always automatically display the most current Firefox for desktop UA to the sites the user selects to always open in desktop mode.

A UA switcher extension, on the other hand, might be used to list any user-agent (Perhaps even of a competing browser) regardless of which option is selected.

Doing it with the browser itself ensures that website owners and people who calculate browser share based on the UA browsers presented to servers by browsers when visiting a list of sites they host will always see some variation of Firefox.  This will raise Firefox's user share rankings and also encourage webmasters to code with Firefox in mind more often.

A native implementation limited specifically to this function would also be more accessible and less intimidating for casual users.

### Who will benefit from it?
1. Everyone who wants to open the desktop mode of a given website (or websites) every time they visit it (or them) without further user intervention after "permanently" enabling it the first time.
1. Everyone who wants to keep the privacy and other protections and customizations Firefox offers (Along with content-blocking, etc. when applicable) when viewing content that website owners are trying to force mobile users to access via an app that may not have those protections or options.
1. Mozilla Firefox, by maintaining and enabling more accurate higher user shares as a percentage of overall visits to sites, and by keeping users engaged with their browser more and engaged with third-party apps less.
1. The mobile web, by making browsing sites easier so that users do not have to use proprietary apps instead of websites.  Perhaps if implemented on a wide enough scale, some maintainers of these websites would even decide to reluctantly implement better more fully functioned mobile sites to keep users using the mobile version or to lure them back to the mobile version, instead of continuing to push everyone into apps.

**Comment by liuche** [comment]
Dupe to #7039
