### ISSUE TITLE
FNX-12759 ⁃ [Bug] (regression) large gap on "Delete browsing data on quit" screen

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#11776]
### Steps to reproduce
1. open the "Delete browsing data on quit" screen

### Expected behavior
No large gap because it a) doesn't make sense to waste the space and b) other settings screens don't have such a gap (AFAIK only the view / edit login screens have such a gap and I reported that already as a bug).

### Actual behavior
Large gap on the left side of the first option. Probably a regression from #11693. /cc @mcarare 

![Screenshot](https://user-images.githubusercontent.com/1100614/85177071-993f3780-b27b-11ea-8187-1547500efed8.jpg)UNITO-UNDERSCORE!20200619-221121!

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision cb129231ae9160f0d54f927f6300cbe21b7cbe3e

**Comment by hakkikaancaliskan** [comment]
This is intended, #11665.

**Comment by mcarare** [comment]
@cadeyrn As the above comment says, this follows to UX specs here: https://github.com/mozilla-mobile/fenix/issues/11665#issue-640085355.

**Comment by cadeyrn** [comment]
@mcarare I think this issue should be reopened because even if it follows the mockup it doesn't mean that the mockup does not contain an error. In this case I report an error in the specification.

Please have a look at the other settings screen. Other screens don't have such a gap and introducing such a gap only for one screen is in fact a bug because it breaks the consistency of the design. /cc @brampitoyo - maybe you can comment?

But let's only focus only on the toggle options:

![screen1](https://user-images.githubusercontent.com/1100614/85195970-2fed1200-b2d7-11ea-9a09-f643a688ce90.png)

**None of these options** has such a gap.

The tracking protection settings are an exception - but **only because they have an additional icon**:

![Screenshot_20200620-090044](https://user-images.githubusercontent.com/1100614/85195996-632fa100-b2d7-11ea-944c-bc43d9b544f6.jpg)

Also the checkboxes "Open tabs", "Browsing history" and so on are kind of **sub options** and I know no UX guideline at all saying that the **parent option** should be indented, I only know the opposite. At least it should be startet on the same position on the y axis. And we also already have an example for that in Fenix:

![screen2](https://user-images.githubusercontent.com/1100614/85196124-45167080-b2d8-11ea-889b-15ed61544324.png)

Here "Show in private sessions" is a sub option of "Show search suggestions" and it starts on the same position on the y axis as the parent option, the parent option is not indented.

So this:

![Screenshot_20200619-221121](https://user-images.githubusercontent.com/1100614/85196052-c6213800-b2d7-11ea-8c63-10e3d2c8f8a7.jpg)

… makes really no sense at all. Because it's conflicting both with a) the logic of these options and b) the design of Fenix in more ways than one.

**Comment by brampitoyo** [comment]
@cadeyrn Stay tuned. I’m checking with our team and will get back to you.
