### ISSUE TITLE
FNX2-13616 ⁃ Make it easy to send feedback or report a bug from Fenix itself

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11787]
Not all users are going to create GitHub accounts to report their feedback or bugs. They may not be as clear or the developers will not be able to contact them if they need more info but if we make them sign up for GitHub accounts, find the fenix repository, and have to learn where and how to report the issue they are facing or the feedback they have  then there's chance that they'll stay silent and most users who might have great ideas that'll make Fenix better and the bugs they have to report will stay hidden and never reach us if we don't create a way to easily report the feedback or the bug they're facing. The bugs they are reporting could be incomplete but I think it's better than nothing.

In between all these they're some users who just aren't willing create GitHub accounts, so we should let them have a choice and make an alternative. Or they won't want to create accounts to just report one or two bugs they're facing or the feedback they have.

You can make it like how you already handle **Webcompat** reports and have an option built into Fenix to report website compatibility issues and the Webcompat also has an anonymous way to report websites they're facing the issue on so that there's no need to create accounts. Or you could ask for an optional E-mail address to contact them on if you need more information on the bug or feedback they've filed.

So I request you to come up with a hassle free and easy way to report bugs that what you call a general user won't be willing go through all the steps to report the bug or feedback they have.

**Comment by ShatteredPixel** [comment]
Hi, I'm the reporter of this issue. Please let me know if you need more information.

Thanks! :)

**Comment by kbrosnan** [comment]
We would need a person to triage information going to another source. We tried a similar approach in the Firefox Preview development cycle and the results did not turn up any interesting issues. We will continue to monitor automated and public feedback channels for ways to improve Fenix.
