### ISSUE TITLE
[Bug]Fenix is rendering webpages at 60 fps on a 90Hz screen

### ISSUE THREAD

**Issue by Whip944** [mozilla-mobile/fenix#11783]
## Steps to reproduce
Open any webpage.

### Expected behavior
The webpage should be displayed in 90 fps. 

### Actual behavior
The webpage is displayed in 60 fps. 

Tried in other browsers including the stable Firefox 68.9.0 and the webpages are rendered at 90 fps. Fenix seems the only application on my phone running at 60 fps, everything is at 90 so it's looks pretty laggy. 

### Device information
Oneplus 7T Pro HD1913 Android 10

* Android device: Oneplus 7T Pro Oxygen OS 10.0.9.HD01BA
* Fenix version: Firefox Nightly 200620 (latest version from Playstore)

**Comment by BreadYogurt** [comment]
I’m having this issue with a 120hz screen.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/android-components/issues/6493
