### ISSUE TITLE
[Bug] Stale media notifications in twitter.com

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#11781]
## Steps to reproduce
Browse twitter.com with Fenix, play one video, but scroll past it while it's playing.

### Expected behavior
Media notifications should be removed.

### Actual behavior
Media notification persists until you get rid of the tab. 

I've seen some of these persist even after closing the relevant tabs. Only closing fenix as a whole will remove the notification under some circumstances, but I don't have precise STR for those :slightly_frowning_face:

This is also not a recent bug, I've seen it for a while.

### Device information
* Android device: Motorola Moto G8 Plus
* Fenix version:

Nightly 200619 06:01 (Build #21710608)
AC: 47.0.20200618130101, 0e690abd2
GV: 79.0a1-20200617093637
AS: 61.0.2

![Screenshot](https://user-images.githubusercontent.com/1323194/85202328-eff15380-b305-11ea-86a3-b698f0cc428e.png)UNITO-UNDERSCORE!20200620-144851!

**Comment by emilio** [comment]
Ive also reproduced this on a Galaxy A20, fwiw.

**Comment by rocketsroger** [comment]
This is fixed in nightly.  Please verify.  Thanks

**Comment by strugee** [comment]
I can confirm this is fixed for me, at least when scrolling. I also intermittently hit this behavior:

> I've seen some of these persist even after closing the relevant tabs. Only closing fenix as a whole will remove the notification under some circumstances, but I don't have precise STR for those 🙁

but I too never found consistent STR, so I can't verify. I'll comment here if I observe that behavior again though.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201210`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
