### ISSUE TITLE
Control the theme colour of the browser

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#1178]
As a web developer, I want to control the theme colour of the browser with my content theme

![](https://user-images.githubusercontent.com/1370580/54949899-74dc9a00-4f16-11e9-9d93-75089b856174.png)

### Why/User Benefit/User Problem
To customize my web content and feel more immersive I want to be able to customize the colour of my website theme.

### Acceptance Criteria (how do I know when I’m done?)
Setting the meta tag `theme-color` should turn the browser toolbar and system toolbar to the colour I request.

```html
<meta name="theme-color" content="#db5945">
```

Linked GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1538943

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2404)

**Comment by Tajnymag** [comment]
Anything new to this?

**Comment by nikolowry** [comment]
I wish this was made a priority, the lack of support makes the status bar such an eyesore when the toolbar is docked to the bottom:

**Comment by brampitoyo** [comment]
Adding [a tweet by @Destructor1702](https://twitter.com/Destructor1702/status/1247206427187273735) to this issue:

> @brampitoyo it would be nice if the top bar and maybe navigation bar on Firefox preview used the site's theme-color meta tag or maybe the document body background color if meta tag is not available
>
> UI elements blending would look really nice

**Comment by OsadebamwenEvbuomwan** [comment]
Any update on this ?

**Comment by brampitoyo** [comment]
@OsadebamwenEvbuomwan If you’d like to work on this, we’d be happy to support you. At the moment, it’s not in our design/development calendar.

I imagine that we’ll need to set some sort of light-dark theme threshold, to ensure that the colours we use not only reflect and respect the site’s theme, but also stay readable and have enough contrast.

Today, it seems that most sites already take this into consideration. This means that, if we take colour values from their header background and navigation, the contrast should be ok.

**Comment by OsadebamwenEvbuomwan** [comment]
@brampitoyo Sorry, I am just a learner may be sometime in the future when I acquire enough skill but not anytime soon.

**Comment by OsadebamwenEvbuomwan** [comment]
@brampitoyo Sorry, I am just a learner may be sometime in the future when I acquire enough skill but not anytime soon.

**Comment by jonalmeida** [comment]
We're currently blocked on this by GV support from the bug linked in the issue, that may need some Android Components support before it gets to Fenix.

**Comment by sheikh-azharuddin** [comment]
Any update? The mentioned GV bug is 2 years old and last updated 9 months ago?😛

**Comment by sheikh-azharuddin** [comment]
Hello team,

Quick question, if the custom tab and now pwa supports theming, why it cannot be added to the main browser? Maybe add as experimental feature or secret flag

Attaching pwa screenshot.

![Screenshot_20220805-220700842](https://user-images.githubusercontent.com/58127841/183122429-a0468744-07f7-49b3-bed8-a1033d1a17aa.jpg)

**Comment by jonalmeida** [comment]
> Hello team,
> 
> Quick question, if the custom tab and now pwa supports theming, why it cannot be added to the main browser? Maybe add as experimental feature or secret flag

PWAs provide the theme colour via a manifest file amongst other attributes. The theme-color property exists somewhere on the web page that we need an API in order to retrieve.

There is [work being done](https://bugzilla.mozilla.org/show_bug.cgi?id=1770985) in order to build a good structure to support a these various kinds of metadata.

**Comment by im-n1** [comment]
Just a quick reminder that Chrome has added support for this more than 8 yars ago.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809960

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
