### ISSUE TITLE
Redefine History page

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11788]
### What is the user problem or growth opportunity you want to see solved?
Currently history does not show any time. Has no search button. Also the UI looks outdated. Please make it look like edge browser which shows as card with time. Looks beautiful. Attaching screenshot

### How do you know that this problem exists today? Why is this important?
It is important to show time and search icon in history. Also the UI needs to be updated.

### Who will benefit from it?
All users

![Screenshot](https://user-images.githubusercontent.com/58127841/85227274-fd711100-b3cb-11ea-85ec-53dae71f0499.jpg)UNITO-UNDERSCORE!20200621-200201!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2420)

**Comment by benyaminl** [comment]
Is this really not being a priority, rather than proton change on Android? Hem..

**Comment by coderkei** [comment]
As for searching history, [Issue #10046](https://github.com/mozilla-mobile/fenix/issues/10046) is the main one for that.

Although I am kind of surprised that this feature is such a low priority as I would consider it a very basic browser feature especially considering how long this browser has now been released for, I do hope its considered.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1343976

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1349952

**Comment by coderkei** [comment]
Can someone from the Firefox team please give an update on this?

It doesn't seem like this feature is being considered despite the fact competing browsers like Chrome for Android has has this feature since day 1... This browser is 3 years old now.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813097

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by sheikh-azharuddin** [comment]
Things are getting moved to bugzilla after years but anyone working on the bugzilla tickets or will take decade?
