### ISSUE TITLE
make AArch64/ARM64 version available on mozilla download website

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#11794]
When I go to https://www.mozilla.org/en-CA/firefox/all/#product-android-nightly , I'm only given the options of ARM devices or Intel. Please add the AArch64/ARM64 version to this options list!

**Comment by kbrosnan** [comment]
The mozilla.org website is not part of this project. This should be reported to [Mozilla's Bedrock project](https://github.com/mozilla/bedrock/issues)
