### ISSUE TITLE
FNX2-13619 ⁃ [NATIVE CRASH] When turned off Ublock origin

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#11790]
For testing browser I turned off Ublock origin on https://health.graphics and it resulted in sudden crash.

Details:

3ad98b65-ede2-408a-a975-fb77732d0cac
<native crash>

* Socorro: https://crash-stats.mozilla.org/report/index/bp-f71cd256-2ff5-4241-8e48-1a7440200621
* Socorro: https://crash-stats.mozilla.org/report/index/bp-e27e1849-72b0-4122-9fdb-49c220200621
* Socorro: https://crash-stats.mozilla.org/report/index/bp-58351ff4-4d87-4350-8942-248440200621
* Socorro: https://crash-stats.mozilla.org/report/index/bp-bd663ddb-18c7-442a-9615-d51b50200621
* Socorro: https://crash-stats.mozilla.org/report/index/bp-f266b81a-8f97-47df-9790-b2ff50200621
* Socorro: https://crash-stats.mozilla.org/report/index/bp-c441fbb9-c0d9-4a75-a814-c6c690200621
* Socorro: https://crash-stats.mozilla.org/report/index/bp-c2ab1a4b-d756-43e9-a3a0-fcba70200621
* Socorro: https://crash-stats.mozilla.org/report/index/bp-0ae7030c-ce67-4761-916a-238e90200621
* Socorro: https://crash-stats.mozilla.org/report/index/bp-7034fc0b-3cc1-4cd6-930a-4548c0200621
----
<native crash>

**Comment by Amejia481** [comment]
Thanks for reporting the issue, unfortunately, I wasn't able to reproduce on my Pixel 3 on Android 10. If it's not a problem for you, would you mind adding more info about the steps to reproduce and more info about the devices were you were testing?

I was testing on 
```
Nightly 200629 06:01 (Build #21810611)
AC: 48.0.20200628130058, 5cf0100e3
GV: 79.0a1-20200626094540
AS: 61.0.64:40
Monday 6/29 @ 6:11 AM
```

**Comment by RealGJ** [comment]
@Amejia481 sorry. I forgot to record build info. Now have installed latest nightly and and I don't have data for last crashes. I'll try to reproduce the issue, if unable then I'll close it. Thank You.

**Comment by RealGJ** [comment]
Unable to reproduce in

Nightly 200702 06:03 (Build #2015749619)
AC: 49.0.20200701130905, 14d09cc4a
GV: 79.0a1-20200629094229
AS: 61.0.7

Thus, Closing this issue. Thank You!!!👏

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200708-124713](https://user-images.githubusercontent.com/51314259/86904984-1ee73200-c11a-11ea-9d1a-fc85c55d066e.gif)
