### ISSUE TITLE
[Bug] Image non recognized, it asks to download as bin file

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11793]
## Steps to reproduce
1. Open https://bibliogram.art/p/CAbAOQLA6Ip
1. Long press a photo, long press to open in a new tab / <sub>Alternatively, download the file</sub>
    1. Expected behavior
You see the photo / alternatively, you download a `.jpg` file (or another image extension, but on this website every pictures seems to be jpg), **as it's doing with fennec**.
    1. Actual behavior
It will ask you to download a `.bin` file.
    1. Device information

* Android device: Android 9
* Fenix version: 5.1.1, nightly 200621 06:01

### Evidence:
![image](https://user-images.githubusercontent.com/58657617/85230922-7c2d7480-b3f3-11ea-9cd0-d5f25af8151e.gif)UNITO-UNDERSCORE!bin!UNITO-UNDERSCORE!fenix!

**Comment by B0pol** [comment]
Btw, this is also a bug with Firefox desktop 77.0.1, but not ESR 68.9.0

**Comment by Amejia481** [comment]
@B0pol  The url have been blocked, would you mind adding a new example url.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/773158/106049488-25d49280-60b4-11eb-8cd9-214729865130.png">

**Comment by B0pol** [comment]
It is not reproducible anymore even with another link, the issue has been fixed.

If you want to verify,
https://bibliogram.art/u/firefox pick any post with images and try to long press -> download it will work

 Thank you anyway
