### ISSUE TITLE
[Suggestion] A permanent "What's new" entry is not necessary in the three-dot bottom/top menu at Fenix homescreen

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11795]
A permanent **What's New** botton is necessary. I don't think it is necessary once the users know what's new in the update/fresh install it should just disappear. If you ask me it has always felt out of context to me, it just doesn't make sense for me to keep it there even after knowing what's new in an update or a fresh install after clicking that button. 

I'm suggesting show the **What's New** button only after the browser is updated or on a fresh install and after the users click on it to view what's new in the update and then hide it after that. You can just let them know that there's a new entry in the menu by showing a blue dot just like how you do when a website supports Reading mode.

If users want to check what's new in the browser or an update they can always check it at the **About Firefox Preview**  screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2430)

**Comment by SS1113** [comment]
CC @apbitner Please see the discussion about the what's new button at the issue: https://github.com/mozilla-mobile/fenix/issues/11630 

The issue I mentioned is taking about removing the "add-ons" at the three-dot bottom menu but I have suggested to keep the that entry and instead remove the permanent "What's New" entry. 

Thanks!

**Comment by apbitner** [comment]
@vesta0 do you know if there's a strong use case for always keeping "What's New" in the homescreen toolbar menu? As suggested above, could we just show it after an update when the SUMO content has been updated?

**Comment by vesta0** [comment]
@apbitner good idea, let's consider that after launch.

**Comment by ShatteredPixel** [comment]
Hi, I'm the reporter of this issue. Please let me know if you need more information.

Thanks! :)

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
