### ISSUE TITLE
FNX-12782 ⁃ [Bug] Incorrect URL when sharing page from the reader view

### ISSUE THREAD

**Issue by petval** [mozilla-mobile/fenix#11798]
## Steps to reproduce
Switch page to reader view. Share it.

### Expected behavior
The url in the shared item should be the same as in original page outside reader view so it can be shared directly from reader view.

### Actual behavior
Url in shared item is like this

>moz-extension://eb8df45a-895b-4f3a-896a-c0c71ae5f6ed/readerview.html?url=https%3A%2F%2Fwww.thedailybeast.com%2Fgoogle-co-founder-sergey-brin-has-a-secret-disaster-relief-squad&id=274877907009

which will not work on receiver's end. It must be switched back from reader view, share it and then return back to reader view, and the article is back on top.

### Device information
* Android device: OnePlus 7 Pro, Android 10.0.6.GM21BA (May 2020) 
* Fenix version: Nightly 200620 06:00 Build #2015747315, GV: 79.0a1, AS: 61.0.2

**Comment by csadilek** [comment]
Removing ac label as this would needs a fix in Fenix to use the original article URL, if reader mode is turned on, similar to: https://github.com/mozilla-mobile/fenix/blob/fee09c3092d037315d4403cc98eabf3523a8e02c/app/src/main/java/org/mozilla/fenix/ext/Session.kt#L23

**Comment by csadilek** [comment]
My comment above will only work for active sessions. If sharing from history or bookmarks etc. we wouldn't find the session in the store. So, a better solution here, is to process the URL before sharing. I will give this a try.

**Comment by csadilek** [comment]
OK, this is fixed now on master and will be in tomorrow's Nightly.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 06/26 with Xiaomi Redmi Note 8T (Android 9) and LG G7 FIT (Android 8).
