### ISSUE TITLE
Accepting multiple sent tabs is very difficult

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11805]
## Steps to reproduce
Send many tabs ~8 from desktop
Notification for each sent tab appears seperate

### Expected behavior
Simple way to accept all the sent tabs

### Actual behavior
Accepting the tabs one by one each time having to oull the notification shade down and then opening the tab

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2439)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810643

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
