### ISSUE TITLE
Ability to pin extensions to 3 dot menu

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#11809]
This was already being discussed [here](https://github.com/mozilla-mobile/fenix/issues/6092#issuecomment-547258698) but that issue was eventually closed and I saw no open issue tracking this.

Now that version 5.2 is out and extensions have been moved inside the Add-ons sub menu, the ability to pin certain extensions to the 3 dot menu would be very useful.

**Comment by SS1113** [comment]
The  ability to hide certain extensions would be great as well.

**Comment by csadilek** [comment]
Thanks for filing. Closing for https://github.com/mozilla-mobile/fenix/issues/17056.
