### ISSUE TITLE
[Bug]Saved logins error state icon misaligned

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11800]
## Prerequisites
Have at least a saved login

## Steps to reproduce
1. Open "saved logins"
1. Open any login
1. Tap the upper right ⋮ "More options button"
1. Select Edit
1. Tap the ⓧ from the "Password" section
1. Check the red warning error state icon

### Expected behavior
Properly displayed, in place of the ⓧ icon

### Actual behavior
Misplaced error state icon

### Device information
* Android device: all
* Fenix version: Nightly Build 200622 from 6/22

### Notes
► Screenshot
![rsz](https://user-images.githubusercontent.com/51314259/85263776-55655180-b478-11ea-8bbb-c6c3e836569f.jpg)UNITO-UNDERSCORE!1rsz!UNITO-UNDERSCORE!img!UNITO-UNDERSCORE!20200622!UNITO-UNDERSCORE!104507!

Noticed while checking #10172

**Comment by mcarare** [comment]
While investigating this, I've noticed that are a few more differences between implementation and mocks: [UX Mocks](https://share.goabstract.com/33afd8de-f90e-4504-90e3-ee2a3bcb1925?mode=design&sha=2b7a1bf44fa2c02a3b7e470075e94c587a491d3b
)

Are those mocks up to date, or the screen needs an implementation review and changes? cc @AmyYLee

**Comment by ekager** [comment]
<img width="808" alt="Screen Shot 2020-09-14 at 11 19 52 AM" src="https://user-images.githubusercontent.com/25442310/93122967-3bed3380-f67c-11ea-902e-2b8e38bc9ab2.png">
For reference linked mocks above

**Comment by joc-a** [comment]
Hello! I would like to work on this.

**Comment by joc-a** [comment]
#15244

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 9/25** with **Google Pixel 4 XL (11).**
