### ISSUE TITLE
FNX-4853 ⁃ Application name in strings should be parameterized

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#1181]
Wherever we mention Fenix in strings, we have to use a parameter so that we can customize the product name on a per-channel basis.

**Comment by mheubusch** [comment]
I have updated the Fenix strings.xml file (attached) - In the app_name string I replaced Fenix with GeckoView Preview and in other strings that hard-coded the name I changed Fenix to %1$s.  

I also took the opportunity to fix some capitalization issues.  

Three questions -
1. is app_name the place to put the name so it works with the parameter?
2. do we have the ability to use a long name GeckoView Preview and a short name GV Preview?  
3. in the browser_menu_powered_by string the copy is all caps - and I either need to find a way to indicate that the parameter s/b all caps but would rather this be done for the whole string as a function of a style sheet not as a content and would like to use sentence case for the string in the xml file: Powered by GeckoView Preview

Please advise.

**Comment by boek** [comment]
Hey @mheubusch, sounds good. I will wrap this up tomorrow.

To answer your questions:

1. `app_name` is probably what we will use 99% of the time
2. If we have `app_name` and `short_app_name` we can inject that on a string by string basis
3. We can capitalize it in the UI, and keep the capitalization normal in strings.xml
