### ISSUE TITLE
Redesign tab tray

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11811]
### What is the user problem or growth opportunity you want to see solved?
In the tab tray most of the sites are not showing thumbnails , also even if thumbnails are showing sometime they are not loaded properly like blank space, thumbnail half loaded etc. The thumbnail also might be affecting overall performance of the browser. Also due to thumbnail the height of the tab is too large allowing max 3-4 tabs in a single view. 

Is it possible to bring the old card layout of tabs (which was on homescreen) to the new tab tray with favicon only like old layout. This will reduce the height of each tab thus accomodating more tabs in a single view . Also performance and view will be better.

### How do you know that this problem exists today? Why is this important?
The thumbnails never load properly and tabs appears too large in tab tray.

### Who will benefit from it?
All users.

**Comment by ali-alhusseini** [comment]
If you can please bring back the old design for open tabs, having them on the home page rather than going through the tabs tray was way more efficient and easier to access. The tabs tray is just not working, and users don't like it. Please bring back the old tab cards

**Comment by kbrosnan** [comment]
We are not going to support two different tab layouts. We are currently happy with the performance and the UI of the tab sheet. We are working to refine the entry to the search view so that it is fewer taps.
