### ISSUE TITLE
[Bug] Line breaks not handled properly in Tibetan Text

### ISSUE THREAD

**Issue by rogerespel** [mozilla-mobile/fenix#11816]
Open a page with long lines of Tibetan text on Firefox Preview, ex. https://www.lotsawahouse.org/words-of-the-buddha/twenty-one-tara-praise

Long text lines should break break after the Tibetan spacing character (་), avoiding horizontal scrolling.  Android Chrome handles it properly, and so does desktop Firefox on Linux.

Here long lines do not get broken, forcing horizontal scroll and/or messing up the responsive layout.  This happens with Firefox Preview, and also in the old Firefox for Android.

* Android device: 10
* Fenix version: 5.1.1

Firefox Preview screenshot:
![Screenshot](https://user-images.githubusercontent.com/5738457/85303308-99714a00-b4aa-11ea-880f-1bf582284720.png)

<br><br>

Chrome screenshot:
![chrome Screenshot](https://user-images.githubusercontent.com/5738457/85303295-94ac9600-b4aa-11ea-8b62-16d64c28244b.png)

**Comment by kbrosnan** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1647377 as this is a Gecko bug.

**Comment by ekager** [comment]
Similar: https://github.com/mozilla-mobile/fenix/issues/2643
