### ISSUE TITLE
FNX-12799 ⁃ [Bug] Crash while page loads and user taps the device's back button - libc.so@0x49e48 | libart.so@0x432f31

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#11815]
## Steps to reproduce
1. Go to twitter.com.
1. Wait until is almost fully loaded. (check GIF)
1. Tap on the device back button.
    1. Expected behavior
No crash present, the page stops from loading.
    1. Actual behavior
Crash present.
    1. Device information

* Android device: Sony Xperia Z5 (Android 7)
* Fenix version: Nightly 6/22

Note: 

* It happens with other sites as well: getpocket.com, wikipedia.org.
* When trying to reproduce the issue with Samsung Galaxy S9 (Android 8) a native crash is triggered but no crash link provided - 
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4813805/logcat.txt)

**GIF - SonY Xperia Z5 (Android 7)**
![20200622-170514](https://user-images.githubusercontent.com/49859863/85299953-9ed09380-b4ae-11ea-9d59-952cfc2d1cd9.gif)

**GIF-Samsung Galaxy S9 (Android 8)**
![20200622-171025](https://user-images.githubusercontent.com/49859863/85300369-21595300-b4af-11ea-87bf-052f18f72954.gif)

**Comment by kbrosnan** [comment]
This is a native code crash we would need any Socorro URLs

**Comment by Diana-Rus** [comment]
Yes, sorry for that.
Crash ID : 62e5435a-23eb-49be-86c1-b09610200622
Socorro link: https://crash-stats.mozilla.org/report/index/62e5435a-23eb-49be-86c1-b09610200622

**Comment by kbrosnan** [comment]
This is the RecvScreenPixels crash that was fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1647011
