### ISSUE TITLE
Investigate app link startup

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11817]

**Comment by mcomella** [comment]
@MarcLeclair Please document the results of your investigations and close this issue if applicable.

**Comment by MarcLeclair** [comment]
Findings were as follow: There's no more "low hanging fruits" (which we defined as small-ish changes that would give us performance improvements). Most of the improvements we could do would need to come from a more holistic approach.  I.e: this would require bigger changes that might have to come from other part than just Fenix.
