### ISSUE TITLE
FNX-12807 ⁃ [Bug] Don't animate tab counter when a session removed or restored

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#11822]
## Steps to reproduce
Add `Log.d()` to [here](https://github.com/mozilla-mobile/fenix/blob/1356b3e426f76fec78e94de6265b796f920c4ff4/app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounter.kt#L68).
Delete a tab or all tabs via tab tray and look to logcat.

### Expected behavior
Not animating tab counter because tab counter **not seen**.

### Actual behavior
Animating.

**Also** if fenix has at least 2 tabs, when user press `close all tabs` fenix animates like 2->1->0 instead of 2->0. But if we don't animate the tab counter, no problem.

### Device information
* Fenix version: master

**Comment by hakkikaancaliskan** [comment]
I've found the root of the problem but needs ux feedback. Should we need to animate tab counter on a session removed or restored?

**Comment by hakkikaancaliskan** [comment]
**Also** I've found out pressing a top site doesn't animate tab counter. No problem in this [function](https://github.com/mozilla-mobile/fenix/blob/1632fc93f784bc16d8c492b47153a6a8a18547e1/app/src/main/java/org/mozilla/fenix/components/toolbar/TabCounter.kt#L45), top site starts this, and starts animation but not observed by me on video record. Maybe it doesn't run because of homefragment to browserfragment transition or because of `setCount()`.

**Comment by AmyYLee** [comment]
@hakkikaancaliskan I don't quite understand the question of animating the tab counter. Are you referring to the icon with the number of tabs opened?

**Comment by hakkikaancaliskan** [comment]
![Screenshot_20200624-095339_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/85510858-a30cc600-b600-11ea-8dd4-b651619c5cde.png)
@AmyYLee 
We're animating this box and text on tab count changes but this animation not seen by user mostly because we have tab tray that covers it.
Just user sees it when opens a top site. But this one also not working currently(bug). If we're currently using animation for just 1 situation (not working that either currently), why not to remove it? Should we remove that tab counter box and text animation completely or just show while opening top site?
