### ISSUE TITLE
FNX-4854 ⁃ Enable Gecko's offline browsing mode (automatically and/or with a user setting)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1182]
### Why/User Benefit/User Problem
Avoid network error pages when the network is offline.

### What / Requirements
Fenix would need to monitor network status themselves (possibly with a network monitor A-C component) and then automatically tell GV to enter offline browsing mode. Fenix might also want a user setting to manually toggle offline browsing mode.

GV API to toggle offline browsing mode: https://bugzilla.mozilla.org/show_bug.cgi?id=1533271

### Acceptance Criteria (how do I know when I’m done?)
Disable network connection and try reloading a web page while offline. The page load should use cached files instead of showing a network error page.

**Comment by vesta0** [comment]
Dup of #219
