### ISSUE TITLE
QR Scanner Shortcut

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#11829]
### What is the user problem or growth opportunity you want to see solved?
As a user I'm looking for a fast way to experience the content behind a qr-code. Having a shortcut on my home screen (android launcher) that takes me directly into the qr-code scanner, so I can quickly browse to the target of the qr-code, would be very convenient.

### How do you know that this problem exists today? Why is this important?
It takes a couple of steps to scan a qr-code and that increases the friction of opening the link behind a qr-code.

### Who will benefit from it?
Anyone that scans qr-codes.

<img src="https://user-images.githubusercontent.com/23485114/106334352-b28f7400-629f-11eb-93cd-914124b7f8a2.jpg" width="33%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2464)

**Comment by hakkikaancaliskan** [comment]
![Screenshot_20200623-011316_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/85340491-df500180-b4ee-11ea-90b5-8f38f271afee.png)
Maybe we can add to the left of the tab counter?
Also what about to changing search engine with just tapping search engine icon?

**Comment by TitanNano** [comment]
@hakkikaancaliskan I think those are independent feature requests.

**Comment by TitanNano** [comment]
> If you are aware of Öffi, you may know that some apps can have multiple launcher icons.
> 
> So my idea was basically today: Mozilla should add an option to add a second launcher icon "Fenix QR" to home screen if the user wants this. That way you could directly launch into QR.
> 

@vaporwave9 yes, what you describe is called a "launcher shortcut" in android. That was exactly what I imagined when writing this feature request. I think this could work similar to the "private browsing" shortcut.

**Comment by vaporwave9** [comment]
Embarrassing, my reading comprehension is sometimes impaired and I jump too fast to reply boxes.
I see now where you wrote about it :)

**Comment by TitanNano** [comment]
@vaporwave9 no big deal 😄

**Comment by evertonstz** [comment]
Came to make this same request.
I use the QR Code reading a lot to get pages from my PC, having this shortcut would make things way easier for me.

For people that aren't not aware, this is the app shortcut feature: https://developer.android.com/guide/topics/ui/shortcuts

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807389

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
