### ISSUE TITLE
[Bug] Metropolis is not used in a few places within the app

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#11835]
Metropolis is the font we use for headlines & subtitles. Inter is the font we use for body & captions.

There are still a few places within the app where Metropolis is not used, or whether Inter/Roboto should be used instead. This issue aims to document them.

### Search screen: subhead “This time, search with”
And match the side padding/margin of this subhead, so it aligns with the icons underneath (I think it’s 16dp?)

![](https://user-images.githubusercontent.com/51007/85358978-2bd82300-b569-11ea-9871-2d50c43e9016.png)

### History: subheads “Today”, “Yesterday”, etc.
Match it to how other subheads look under Settings (e.g. “Account”, “General”, “Privacy and security”, etc.)

![](https://user-images.githubusercontent.com/51007/85361154-3f868800-b56f-11ea-8028-e2db200a41f3.png)

### Add-ons submenu: header title
Also applies to all other submenu headers.

![](https://user-images.githubusercontent.com/51007/85358946-1236db80-b569-11ea-9f01-a6489cf43e59.png)

### Modal bottom sheet: buttons
For example:

* Permission modal: “Don’t allow” and “Allow”
* Add-ons modal: “Cancel” and “Add”

Make sure that the font weight matches the font weight that we use in other button texts, e.g. “Delete browsing data” 

![](https://user-images.githubusercontent.com/51007/85360679-dce0bc80-b56d-11ea-8dd8-e2646cd085dc.png) ![](https://user-images.githubusercontent.com/51007/85360682-dfdbad00-b56d-11ea-8998-f70bdb075b58.png)

### Delete browsing data: caption
Also applies to all other caption texts on this sub-page, e.g. “addresses”, “Frees up storage space”.

![](https://user-images.githubusercontent.com/51007/85359167-a43ee400-b569-11ea-97dc-51578de40528.png)

### Settings: Firefox Accounts email address
And match the font weight and colour of this caption to other caption texts.

![](https://user-images.githubusercontent.com/51007/85359243-d0f2fb80-b569-11ea-81a4-a844f547cf8b.png)

### New tab page: Collections placeholder text
> Group together similar searches, sites, and tabs for quick access later.

Credit: @cadeyrn.

![](https://user-images.githubusercontent.com/51007/85663542-5236c380-b70d-11ea-9d0a-cda90f992765.png)

### Select collection: caption and button text
* Caption: “en.m.wikipedia.org” should use Inter/Roboto. Match the font weight to other captions.
* Button text: “Add new collection” should use Metropolis.

![](https://user-images.githubusercontent.com/51007/85360227-a5254500-b56c-11ea-93b7-d02b338329a2.png)

### Select Tabs: button texts
* Button text: “Deselect all” should use Metropolis. It should also be sentence case, as should “Select all”. But perhaps this should be filed as a separate issue?.
* Button text: “x tabs selected” should use Metropolis, similar style to “Add new collection” above.
* Button text: “SAVE” should use Metropolis. Match this button text style to the button text style on the right side of snackbars.

![](https://user-images.githubusercontent.com/51007/85360143-6b543e80-b56c-11ea-86ec-84d2bf021f3b.png)

edit mcarare: adding this to the list: https://github.com/mozilla-mobile/fenix/issues/11451

**Comment by brampitoyo** [comment]
CC @kglazko, @AmyYLee and @betsymi. In case I’ve missed other screens, would you be able to document them here?

We probably need to file another issue relating to font sizes.

**Comment by BMEduard** [comment]
Hello, while working on this issue I was unable to find the "Inter/Roboto" that should be used in the places that you mentioned. @brampitoyo Can you please point to a location where I can get this font?

**Comment by cadeyrn** [comment]
> In case I’ve missed other screens

I guess the text of the collections placeholder on the start screen has also the wrong font, right?

> "Group together similar searches, sites, and tabs for quick access later." It looks like Metropolis.

**Comment by kglazko** [comment]
@BMEduard Roboto is the default font. InterFont is in a separate PR, and requires AC-side work in order to implement. I think for the scope of this PR, removing the Metropolis formatting so the default is used is the appropriate course of action.

**Comment by brampitoyo** [comment]
Hi @mcarare, @kglazko is correct. For the scope of this PR, we should either add or remove Metropolis in favour of the default font (which would automatically be Roboto, until we change it to Inter one day!)

@cadeyrn You’re totally right! The placeholder text for “Collect the things that matter to you” is Metropolis, but should’ve been Roboto/Inter. Thanks for catching this. I will file it on comment 0.

**Comment by brampitoyo** [comment]
@BMEduard On comment 0, I’ve documented one more place where our default font should be used instead of Metropolis. It’s the placeholder text under the “Collections” section on the New Tab Page.

**Comment by BMEduard** [comment]
@brampitoyo I created #12181 to address the sentence case problem for the Select Tabs top right button text.
