### ISSUE TITLE
[Bug]The Old History and Bookmarks action bars are displayed on exit

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11837]
## Steps to reproduce
1. Open the History section
1. Tap the X (close) button
1. Open the Bookmarks section
1. Tap the X (close) button

### Expected behavior
No glitches or other UI issues

### Actual behavior
The Old History and Bookmarks action bars are displayed on exit

### Device information
* Android device: all
* Fenix version: Nightly Build 200623 from 6/23

### Notes
Noticed while checking #10462 

► Video History
![20200623-100623](https://user-images.githubusercontent.com/51314259/85371757-780b6f00-b539-11ea-8676-a02cd1f296d5.gif)

► Video Bookmarks
![20200623-100649](https://user-images.githubusercontent.com/51314259/85371818-8f4a5c80-b539-11ea-9156-cc9023f2fb62.gif)

**Comment by softvision-miralobontiu** [comment]
I'll close this issue since the closing buttons are no longer the case.
