### ISSUE TITLE
[Bug]  Firefox Account Has Never Synchronised, Won't Sync

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#11846]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1646992

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0

Steps to reproduce:

I'm logged in. I went to the "Account Settings" page on 77.0.0-beta.2 and pressed "Synchronise now".

Actual results:

Nothing happens when the "Synchronise now" button is pressed. The button reads "Last synchronised: Never".

Expected results:

The account should be synchronised.

**Comment by Amejia481** [comment]
We are tracking the generic work manager issue here https://github.com/mozilla-mobile/android-components/issues/7659

**Comment by eberhardweber** [comment]
Just to chime in, I'm now on my _second_ device where Sync doesn't work. My LineageOS-based Galaxy Tab S does nothing when "Sync" is pressed. There was trouble pairing the device as well, Fenix didn't know how to use the camera app, which froze, and the account linking process got interrupted halfway but eventually continued when I tried the process again.
