### ISSUE TITLE
FNX-12827 ⁃ [Bug]Top Sites section get's displayed while in private browsing

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11841]
## Steps to reproduce
1. Long tap on a Top Site
1. Select Open in Private Browsing
1. Tap the Tabs counter
1. Tap the New tab FAB

### Expected behavior
Step 4: Properly display the PB home screen

### Actual behavior
Step 4: The Top Sites are displayed for a couple of seconds

### Device information
* Android device: all
* Fenix version: Nightly Build 200623 from 6/23

## Notes
► Video
![20200623-161405](https://user-images.githubusercontent.com/51314259/85408435-31376c80-b56d-11ea-96ea-057cf8d0b9fb.gif)

**Comment by liuche** [comment]
We probably want this for release cc @darkwing (but I don't know if someone is already working on it?)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly Build 200629 from 6/29`** and **`Fenix 78.0.1-beta.1 from 6/27`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200629-162351](https://user-images.githubusercontent.com/51314259/86011803-d64abd00-ba25-11ea-97f5-77b3f4da7ade.gif)
