### ISSUE TITLE
[Bug] Bottom part of uBlock Origin settings pages hidden behind URL bar

### ISSUE THREAD

**Issue by BlitW0** [mozilla-mobile/fenix#11858]
## Steps to reproduce
* Go to uBlock Origin settings (open the dashboard)
* Scroll down to the end of settings tab or my filters tab

### Expected behavior
URL bar should scroll to below the end of the page, so as to not hide the bottom 2-3 lines worth of space.

### Actual behavior
* Some part of the bottom of the page is hidden behind the URL bar
* On the settings tab, among the 3 buttons at the end of the page, the 'Reset to default settings' button is hidden almost completely
* If you have more than ~18 lines in My filters tab, the last 2-3 lines are not accessible

### Device information
* Android device: Moto G5 Plus; Android 8.1 Oreo
* Fenix version: Firefox Preview 5.2.0 from Play Store

**Comment by AmyYLee** [comment]
Assigned to @brampitoyo for UX

**Comment by brampitoyo** [comment]
@BlitW0 Thanks for the report.

You’ll note that this problem happens on every webpage, if the address bar is somehow maximised while the user has scrolled all the way down to the bottom of the page.

The solution is to make the address bar on “in-content” add-on pages behave like address bars in every other webpage. It should be minimised on scroll down.

**Comment by Amejia481** [comment]
We are tracking this issue here https://github.com/mozilla-mobile/android-components/issues/6933
