### ISSUE TITLE
[Bug] handlePermissionsChange should store the updated permission and reload webpage java.lang.AssertionError: Verification failed: less calls happened than demanded by order verification sequence.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#11854]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=307261938&repo=fenix

[task 2020-06-23T15:34:07.757Z]   TEST: handlePermissionsChange should store the updated permission and reload webpage
[task 2020-06-23T15:34:07.758Z]     [Robolectric] org.mozilla.fenix.settings.quicksettings.DefaultQuickSettingsControllerTest.handlePermissionsChange should store the updated permission and reload webpage: sdk=28; resources=LEGACY
[task 2020-06-23T15:34:07.758Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-06-23T15:34:07.759Z]     I/AssetManager: no overlays.list file found
[task 2020-06-23T15:34:07.847Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-06-23T15:34:07.847Z]     D [FenixApplication] Initializing Glean (uploadEnabled=true, isFennec=false)
[task 2020-06-23T15:34:07.847Z]     E/glean/Glean: Glean should not be initialized multiple times
[task 2020-06-23T15:34:07.948Z]   FAILURE
[task 2020-06-23T15:34:07.948Z] 
[task 2020-06-23T15:34:07.948Z] java.lang.AssertionError: Verification failed: less calls happened than demanded by order verification sequence. 
[task 2020-06-23T15:34:07.948Z] 
[task 2020-06-23T15:34:07.948Z] Matchers: 
[task 2020-06-23T15:34:07.948Z] PermissionStorage(#2487).updateSitePermissions(eq(SitePermissions(#2494))))
[task 2020-06-23T15:34:07.948Z] ReloadUrlUseCase(#2488).invoke(eq(Session(#2485))))
[task 2020-06-23T15:34:07.948Z] 
[task 2020-06-23T15:34:07.948Z] Calls:
[task 2020-06-23T15:34:07.948Z] 1) PermissionStorage(#2487).updateSitePermissions(SitePermissions(#2494))
[task 2020-06-23T15:34:07.948Z] 
[task 2020-06-23T15:34:07.948Z] Stack traces:
[task 2020-06-23T15:34:07.948Z] 1)                                                                    io.mockk.impl.InternalPlatform.captureStackTrace     (InternalPlatform.kt:121)

[task 2020-06-23T15:34:07.948Z]                                                                         io.mockk.impl.stub.MockKStub.handleInvocation      (MockKStub.kt:247)

[task 2020-06-23T15:34:07.948Z]                                       io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation            (JvmMockFactoryHelper.kt:25)

[task 2020-06-23T15:34:07.948Z]                                                                io.mockk.proxy.jvm.advice.Interceptor.call                  (Interceptor.kt:20)

[task 2020-06-23T15:34:07.948Z]                                                       org.mozilla.fenix.components.PermissionStorage.updateSitePermissions (PermissionStorage.kt:47)

[task 2020-06-23T15:34:07.948Z]    org.mozilla.fenix.settings.quicksettings.DefaultQuickSettingsController$handlePermissionsChange$1.invokeSuspend         (QuickSettingsController.kt:147)
[task 2020-06-23T15:34:07.948Z]                                                  kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith            (ContinuationImpl.kt:33)

[task 2020-06-23T15:34:07.948Z]                                                                    kotlinx.coroutines.DispatchedTask.run                   (DispatchedTask.kt:56)

[task 2020-06-23T15:34:07.948Z]                                                     kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely             (CoroutineScheduler.kt:571)

[task 2020-06-23T15:34:07.948Z]                                              kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask           (CoroutineScheduler.kt:738)

[task 2020-06-23T15:34:07.948Z]                                              kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker             (CoroutineScheduler.kt:678)

[task 2020-06-23T15:34:07.948Z]                                              kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run                   (CoroutineScheduler.kt:665)

[task 2020-06-23T15:34:07.948Z] 	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
[task 2020-06-23T15:34:07.948Z] 	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
[task 2020-06-23T15:34:07.948Z] 	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
[task 2020-06-23T15:34:07.948Z] 	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
[task 2020-06-23T15:34:07.948Z] 	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
[task 2020-06-23T15:34:07.949Z] 	at io.mockk.MockKDsl.internalVerify(API.kt:118)
[task 2020-06-23T15:34:07.949Z] 	at io.mockk.MockKDsl.internalVerify$default(API.kt:109)
[task 2020-06-23T15:34:07.949Z] 	at io.mockk.MockKDsl.internalVerifyOrder(API.kt:182)
[task 2020-06-23T15:34:07.949Z] 	at io.mockk.MockKKt.verifyOrder(MockK.kt:212)
[task 2020-06-23T15:34:07.949Z] 	at io.mockk.MockKKt.verifyOrder$default(MockK.kt:209)
[task 2020-06-23T15:34:07.949Z] 	at org.mozilla.fenix.settings.quicksettings.DefaultQuickSettingsControllerTest$handlePermissionsChange should store the updated permission and reload webpage$1.invokeSuspend(DefaultQuickSettingsControllerTest.kt:179)
[task 2020-06-23T15:34:07.949Z] 	at org.mozilla.fenix.settings.quicksettings.DefaultQuickSettingsControllerTest$handlePermissionsChange should store the updated permission and reload webpage$1.invoke(DefaultQuickSettingsControllerTest.kt)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
[task 2020-06-23T15:34:07.949Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:288)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:89)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:82)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
[task 2020-06-23T15:34:07.949Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:72)
[task 2020-06-23T15:34:07.949Z] 	at org.mozilla.fenix.settings.quicksettings.DefaultQuickSettingsControllerTest.handlePermissionsChange should store the updated permission and reload webpage(DefaultQuickSettingsControllerTest.kt:174)
[task 2020-06-23T15:34:07.949Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-06-23T15:34:07.949Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-06-23T15:34:07.949Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-06-23T15:34:07.949Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-06-23T15:34:07.949Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-06-23T15:34:07.949Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-06-23T15:34:07.949Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-06-23T15:34:07.949Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-06-23T15:34:07.949Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
[task 2020-06-23T15:34:07.949Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
[task 2020-06-23T15:34:07.949Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-06-23T15:34:07.949Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-06-23T15:34:07.949Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-06-23T15:34:07.949Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-06-23T15:34:07.949Z] 	at java.lang.Thread.run(Thread.java:748)
[task 2020-06-23T15:34:07.949Z]

**Comment by ekager** [comment]
Couldn't repro locally. Might be an intermittent did this happen more than once?

**Comment by Archaeopteryx** [comment]
Yes, was intermittent and first and only occurrence so far.
