### ISSUE TITLE
FNX2-13648 ⁃ Prompt to restore or not session

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11853]
### What is the user problem or growth opportunity you want to see solved?
I'd like to be prompted to restore or not my last session, e.g. restore tabs, or not like the desktop prompt

### How do you know that this problem exists today? Why is this important?
If you restart your phone, you may not want your old tabs to be restored. On firefox desktop it asks you whether you want to restore your session

### Who will benefit from it?
Until a `~always do not restore session~` is implemented, everyone who doesn't want their session to be restored. BTW, on that prompt I think a _rembember_ option is appropriate.

**Comment by AmyYLee** [comment]
@topotropic for consideration

**Comment by AmyYLee** [comment]
@topotropic Does this require further UX investigation?

**Comment by topotropic** [comment]
Thanks for bringing this up. We'll look into this as part of a bigger effort documented here https://github.com/mozilla-mobile/fenix/issues/11582.
