### ISSUE TITLE
New Tab open window UX enhancements

### ISSUE THREAD

**Issue by tiniwings** [mozilla-mobile/fenix#11855]
### What is the user problem or growth opportunity you want to see solved?
growth opportunity

### How do you know that this problem exists today? Why is this important?
Improves user interactions

### Who will benefit from it?
All users.

Version: 5.2 preview
New Tab open window:
Can we move the Normal/Private tab section to bottom of the window Or Swiping at the bottom of the window will switch between the sections.

We can also have open new tab & open private tab both options at single place. 

Thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2497)

**Comment by AmyYLee** [comment]
Thanks for the feedback. This is currently being investigated on Firefox for iOS and we may consider it as well on Fenix.

**Comment by majurgens** [comment]
> We can also have open new tab & open private tab both options at single place.

As per Firefox 68, having menu options "new tab" and "new private tab" on the primary menu improves workflow ( More for private  tabs which is currently at 4 taps for opening new tabs) 

This should be relatively simple and you may want to separate this part of the request from the first part of the request

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812923

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
