### ISSUE TITLE
FNX-4855 ⁃ Remember scroll position when saving sessions

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#1185]
Depends on https://github.com/mozilla-mobile/android-components/issues/2700

### Why/User Benefit/User Problem
It is common for users to read part of an article, close their phones, and return to finish later.  Their session is currently saved when they do so, but their scroll position is not.

[Vesta]
As a user, I want to be able to close the browser, and when I come back to my last session, start reading where I left off. This is key to aligning to our vision of building a browser that is fast by design.

### What / Requirements
Scroll position should be saved whenever a session is persisted, and restored when it is reopened.

### Acceptance Criteria (how do I know when I’m done?)
I can re-open a session to where I left off in the page.

**Comment by vesta0** [comment]
Needs an A-C issue and investigation into whether GV work is required @pocmo @boek

**Comment by pocmo** [comment]
Removed a bunch of labels (a-c, Needs GV work, blocked). This has been fixed in GeckoView and uplifted. It's working in RB.

**Comment by vesta0** [comment]
Thank you @pocmo I believe it's also working in Fenix :)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1923 (#11550608), with Huawei MediaPad M2 (Android 5.1.1), Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9).
