### ISSUE TITLE
FNX2-13645 ⁃ [Bug] 0 tab shown instead of + icon

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11850]
## Steps to reproduce
1. Open the browser
    1. Expected behavior
`+` icon instead of tab count, as in -5.1.1
    1. Actual behavior
[0] tab at the bottom
    1. Device information

* Android device: 9
* Fenix version: 5.2

**Comment by B0pol** [comment]
Also, the `+` button used to open the search and keyboard, now it open the app drawer. It's annoying when you use bottom. I'm not sure if it's a wanted behaviour

**Comment by SS1113** [comment]
> Also, the `+` button used to open the search and keyboard, now it open the app drawer. It's annoying when you use bottom. I'm not sure if it's a wanted behaviour

@B0pol if we press the address bar it'll open the search and keyboard. 

I don't think the current behavior is unusual. Can you explain how this inconvenient than the new behavior. I am really curious to find your point of view regarding this since lots of other users also seem to be asking this same feature.

And as for the tab counter displaying "0" instead of "1" by default, I have already opened the issue #11633 for that. :)

**Comment by B0pol** [comment]
> > Also, the `+` button used to open the search and keyboard, now it open the app drawer. It's annoying when you use bottom. I'm not sure if it's a wanted behaviour
> 
> @B0pol if we press the address bar it'll open the search and keyboard.
> 
> I don't think the current behavior is unusual. Can you explain how this inconvenient than the new behavior. I am really curious to find your point of view regarding this since lots of other users also seem to be asking this same feature.
> 
> And as for the tab counter displaying "0" instead of "1" by default, I have already opened the issue #11633 for that. :)

About that, I always used the + to open a new tab but yeah the url bar does that.

And I don't think we should show 1, there IS 0 tab. A + button makes sense like "Hey, open a new tab" but expanding the URL bar too (and IMO it makes more sense because the + will open the tab tray, and not the address bar)

**Comment by s-ankur** [comment]
Is this still applicable with the new tab tray?

**Comment by kbrosnan** [comment]
Agreed this seems to be referring to older designs.
