### ISSUE TITLE
Enable deep links to highlight specific views

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#11856]
Users click on deep links when they are sent a notification or see a context feature recommendation.

e.g. "Why not twiddle with your privacy settings?"

Currently a deeplink maps directly to a fragment, not the feature that is being highlighted.

e.g. "@id/settingsFragment"

Unfortunately, in this example, the "Privacy Settings" 2/3 the way down the settings screen, and is not obvious.

This issue requests that the feature/view is scrolled to and the user's attention is brought to the feature itself.

e.g. "Privacy Settings"

Other deep links that need feature highlighting —

* [ ] Address bar/search customization preferences
* [ ] Show collections (now on home page)
* [ ] Customize / Toolbar preference.

There are a lot in preferences, so perhaps this could be split into an issue for preferences, and an issue for other fragments.

**Comment by AmyYLee** [comment]
@jhugman Hi, can you provide screenshots of examples? Thanks

**Comment by jhugman** [comment]
<img src="https://user-images.githubusercontent.com/99338/85440655-2c32e700-b586-11ea-8efd-ff68e9e7ef72.png" width="300px">  <img src="https://user-images.githubusercontent.com/99338/85441523-1f62c300-b587-11ea-8193-6e34f5745e0e.png" width="300px">

Other ideas: a magnification, a flashing highlight.

**Comment by AmyYLee** [comment]
> Users click on deep links when they are sent a notification or see a context feature recommendation

@apbitner for consideration - As an FYI we have a flashing highlight on desktop to highlight a section in Settings.

**Comment by apbitner** [comment]
@jhugman is there currently any deeplinking you think this should apply to, or are you proposing this if we do add deeplinking later on?

**Comment by jhugman** [comment]
@apbitner The two examples are of deeplinks that exist but go to a more general (in these cases, "Privacy Settings" and "Collections" for to Settings and Homescreen respectively.
