### ISSUE TITLE
Tab thumbnail previews should work when opened in the background

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11852]
## Steps to reproduce
1. Open wikipedia
1. Long press on several links (let's say 5) and open in a new tab
1. Click each one of them so that the page loads
    1. Expected behavior
You see the thumbnail preview
    1. Actual behavior
Blank
    1. Device information

* Android device: Android 9, pocophone F1, snapdragon 645 and 6GB of ram. Therefore I don't think it's my phone's performance to blame.
* Fenix version: 5.2

(multiple) in parenthesis because sometimes it even do this with only two tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2492)

**Comment by jonalmeida** [comment]
I'm going to make this into a feature request since we don't have the ability to take a thumbnail from a page that isn't drawn on the screen.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812924

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
