### ISSUE TITLE
FNX2-13646 ⁃ [Bug] Close last tab doesn't close tab tray

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11851]
## Steps to reproduce
1. Open a page
1. Close it, you now have 0 tab
    1. Expected behavior
The tab drawer is closed so that I can access collections / top sites / settings / …
    1. Actual behavior
Tab tray is still shown
    1. Device information

* Android device: 9
* Fenix version: 5.2

**Comment by hakkikaancaliskan** [comment]
@gabrielluong If ux team decide how it should be, i can take this issue.

**Comment by gabrielluong** [comment]
> @gabrielluong If ux team decide how it should be, i can take this issue. Needs ux feedback.

Requested. @topotropic is still away for another week I think. Thanks!

**Comment by topotropic** [comment]
Yes, please close the drawer when people don't have any open tabs and show new tab/home with top sites, collections.... Thanks!

**Comment by hakkikaancaliskan** [comment]
@gabrielluong i don't have time to work on this currently, maybe later. Other guys could work on this.

**Comment by ekager** [comment]
@topotropic when you close the last tab - we should still show the undo option though? This piece could be tricky

**Comment by person808** [comment]
The way I handled that for the tab counter menu was to provide a the sessionId as an argument to the nav action that returns to `HomeFragment` and have `HomeFragment` handle the tab closing and snackbar.

**Comment by ekager** [comment]
Nice, so I'm assuming that's what we'd want to do here as well.

**Comment by topotropic** [comment]
> The way I handled that for the tab counter menu was to provide a the sessionId as an argument to the nav action that returns to `HomeFragment` and have `HomeFragment` handle the tab closing and snackbar.

does this mean we close the tab tray and show the undo snackbar on home when people close their last tab?

**Comment by person808** [comment]
@topotropic Yup. If we take the same approach as the tab counter menu then thats what it'll look like.

**Comment by sblatz** [comment]
What should happen in the case where a user has:

1 normal tab
2 private tabs

Closes last normal tab.... should it dismiss (same goes for the inverse)? @topotropic

**Comment by sblatz** [comment]
The behavior that happens by "default" with my change is:

### user state
1 normal tab
2 private tabs

Then...
Close my normal tab

Then...
Now Fenix shows private home screen (with tray dismissed). 

Which actually seems pretty reasonable to me?

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/24 with Samsung Galaxy Note 10(Android 10) and LG G7 FIT (Android 8).
Scenarios covered: normal browsing, private browsing, closing private tab from the notification.
