### ISSUE TITLE
[Bug] Context menu is always above the text, making the page scroll up automatically if there is no space available

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11857]
## Steps to reproduce
1. Open an article
1. Scroll down
1. Long press the text on the top of the screen
    1. Expected behavior
The context menu is below the text if there is not enough space available for the context menu to be above the text, like on fennec. **Does not make the page to scroll up automatically**.
![](https://user-images.githubusercontent.com/58657617/85440410-4e306780-b58e-11ea-935b-cba657e28298.png)
    1. Actual behavior
The context menu is above the text, and the page scroll up automatically. I was at the same place: two lines above the picture, and long press the same word: "avec"
![](https://user-images.githubusercontent.com/58657617/85440592-833cba00-b58e-11ea-816c-18acf9b71eea.png)

### Device information
* Android device: pocophone F1, android 9
* Fenix version: 5.2

**Comment by SS1113** [comment]
@B0pol can you provide the website address you're testing this on? 

I couldn't reproduce the issue. The context menus always popped-up below the selection when at the top/middle and popped-up above when selected at the end of the screen and the selection didn't make it move the displayed article unless I was at the very end and the selected text was displayed partially. I tested this on a Wikipedia article. See the screenshots.

**Comment by AmyYLee** [comment]
I was able to reproduce this on my Pixel 3 visiting the new york times website. I noticed this didn't happen on wikipedia. It appears to happen when the website itself has a top menu bar. I also tried this on torontostar.com and was able to reproduce.
![image](https://user-images.githubusercontent.com/5992746/85496596-92316580-b5aa-11ea-80a7-131464d67e8b.png)

**Comment by SS1113** [comment]
Okay, this reproduces on `nytimes.com` for me but only at the bottom of the screen. The selection jumps but not always attaching a GIF.

Device: Motorola One Power, Android 10.
Fenix: `Nightly 200623 18:02`


![20200624_091723](https://user-images.githubusercontent.com/42088907/85497661-d8e48700-b5cd-11ea-85c4-b47498c199a4.gif)

**Comment by B0pol** [comment]
> @B0pol can you provide the website address you're testing this on?

Any website which is long enough to scroll about more than half the length of the page, maybe more.

Here is a GIF with GitHub, showing the bug when I select text at top, and secondly your bug I couldn't reproduce: same thing but at the bottom.

![ScreenRecord-2020-06-24-09-10-50](https://user-images.githubusercontent.com/58657617/85513503-5ffc2400-b5fb-11ea-9063-659b59bd2cf6.gif)

On nytimes.com, I think you can't reproduce at top because of the navigation bar. You should use the reader mode so that there is only the text, like on the first screenshot I posted.

**Comment by s-ankur** [comment]
@B0pol I can't seem to reproduce this on latest nightly . Can you verify?

**Comment by B0pol** [comment]
Nope it still happens, but not everytime
