### ISSUE TITLE
FNX-12860 ⁃ [Bug] Pressing back on the search screen intermittently returns to homescreen instead of browser when opened from tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11866]
## Steps to reproduce
* Open a tab
* Click URL bar to open search screen
* Press back

### Expected behavior
Return to open tab

### Actual behavior
Usually return to open tab but occassionally return to homescreen. This happens fairly infrequently on my P2 but happens fairly frequently on a GS5.

I can reproduce this behavior 100% if I instead:

* Open a tab
* click url bar
* swipe to dismiss soft keyboard
* press back

### Device information
* Android device: P2, GS5
* Fenix version: Nightly 200623

- - -
Given actual behavior notes above, perhaps we're conditionally doing `pressBack(); pressBack();` (or something like that) and it sometimes doesn't work correctly due to race conditions.

**Comment by ekager** [comment]
Looks like because `SearchFragment` handles back navigation in `onEditingCanceled`, the `onBackPressed` call is getting passed to `BrowserFragment` and `SessionFeature` is consuming the back press (taking us home). I'll try to get a fix in ASAP.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the latest Nightly and Beta 78.0.1-beta1 with a Nexus 9 (Android 7.1.1).
