### ISSUE TITLE
[Bug] Hide save tabs to collection when there is no tab

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11860]
## Steps to reproduce
When no tabs is open the home screen still shows save tabs to collection. Ideally this should show when there is atleast one tab open

### Expected behavior
Save tabs to collection should not show when there is no tab opened

### Actual behavior
It is showing save tabs to collection

### Device information
* Android device: ? A10
* Fenix version: ? Latest nightly

**Comment by sblatz** [comment]
Agreed that this is a bit weird. Here's the current view:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/85452172-79479680-b54f-11ea-9843-80100382df98.png">

**Comment by AmyYLee** [comment]
@sblatz I agree. In the previous version there was no save tabs button. @topotropic to confirm removing the button.

**Comment by vesta0** [comment]
We just added the bottom and we should add an exception to hide it when there are no tabs open.

**Comment by sheikh-azharuddin** [comment]
Thanks Emily 😊

**Comment by ekager** [comment]
Reopening for QA

**Comment by AndiAJ** [comment]
Hi, just checked this on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

❌ The "Save tabs to collection" remains displayed having 0 open tabs after performing these steps:
1. Open a tab
2. Save it to a collection
3. Delete the tab
4. Delete the collection

► Video
![20200625-093237](https://user-images.githubusercontent.com/51314259/85668150-0d883980-b6c7-11ea-8e13-dbb099029a43.gif)

@darkwing & @ekager - Please review ☺️

**Comment by sheikh-azharuddin** [comment]
Found one glitch here...sometime when opening new tab save tab to collection is visible for a short time... attaching a video....

![ScreenRecord-20200627-092305](https://user-images.githubusercontent.com/58127841/85914215-e34f8c80-b82a-11ea-8db6-ee44b62d3c63.gif)

**Comment by darkwing** [comment]
I'm unable to duplicate this issue at all, following @AndiAJ's steps.

**Comment by AndiAJ** [comment]
Hi @darkwing , **it's still reproducible** on the latest **`Nightly Build 200708 from 7/8`** using a Google Pixel 3a (Android 10)

►Video
![20200708-095834](https://user-images.githubusercontent.com/51314259/86887977-1e42a180-c102-11ea-9069-39c37323cd19.gif)


@sheikh-azharuddin's glitchy behaviour seem to be fixed by @mcarare 's PR https://github.com/mozilla-mobile/fenix/pull/12321

**Comment by mcarare** [comment]
Cn QA please update the status of this issue? If fixed, or is some inconsistencies still exist? TY!

**Comment by AndiAJ** [comment]
Hi @mcarare , yes, it's still reproducible with the STR as mentioned [above](https://github.com/mozilla-mobile/fenix/issues/11860#issuecomment-649258725) on the latest Nightly 200722 from 7/22 using a OnePlus A3 (Android 6.0.1)

► Video
![20200722-143656](https://user-images.githubusercontent.com/51314259/88172252-56310500-cc29-11ea-9088-ac6d7b1852f5.gif)

**Comment by abodea** [comment]
I was able to reproduce this issue on the latest **Beta 8.0.0 - beta.1**.

**Comment by ekager** [comment]
Let's pull the still reproducible issue to https://github.com/mozilla-mobile/fenix/issues/13080 👍
