### ISSUE TITLE
FNX-12850 ⁃ [Bug] In app pages doesn't take the entire screen

### ISSUE THREAD

**Issue by snakedye** [mozilla-mobile/fenix#11861]
## Steps to reproduce
Open a link inside an app

### Expected behavior
The webpage takes the entire length on the screen

### Actual behavior
It takes 70 to 80% and leaves an unoccupied [space](https://imgur.com/gallery/6Bp6F3o) on top.

### Device information
Android 10

* Android device: Oneplus 7
* Fenix version: 5.2

**Comment by ekager** [comment]
Closing as dupe of #11708
