### ISSUE TITLE
FNX2-13656 ⁃ [Bug] 5.2.0 Top sites icons become small with a huge borders

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#11868]
> Huge padding wastes space
https://github.com/mozilla-mobile/fenix/issues/11651#issuecomment-648704885

![image](https://user-images.githubusercontent.com/14617699/85473990-b9912e00-b5bc-11ea-9622-c1291e502626.png)

**Comment by person808** [comment]
That is intended. See #11651 for details

**Comment by 532910** [comment]
> #11651
There are no explanation and no reason for huge paddings.

Please reopen and remove padding.

**Comment by person808** [comment]
I read this issue as a report of an unintended bug, not UX feedback, my bad. You might also be interested in #11743. I'll edit the issue with your comment on #11651 to make it more clear what your reasoning is.

**Comment by liuche** [comment]
We're changing the sizing of top sites icons in #13765
