### ISSUE TITLE
FNX-12856 ⁃ [Bug] Pressing refresh in a tab loaded from a collection does not request new content from the site

### ISSUE THREAD

**Issue by mmanjos** [mozilla-mobile/fenix#11864]
## Steps to reproduce
1. Save a page as a collection (e.g. https://www.wunderground.com/forecast/us/ca/san-francisco) 
1. Load the page into a new tab from the collection
1. The page appears to be blank - no content is displayed
1. Press the refresh button - no content loads; it appears to just reload the cached version

### Expected behavior
The page should ideally load a new version when instantiated as a new tab, especially for dynamic content like news or weather reports. I don't want to see weather from 3 weeks ago when I saved the tab into a collection. 

Regardless, pressing the refresh button should request a new page from the server. In this case, I'm "trapped" in the broken site because no amount of refreshing helps - it always loads the broken, empty page from cache.

### Actual behavior
I see a blank page with no content. Refreshing does not help - it only reloads the broken, cached version. 

I have a similar experience with the USPS Informed Delivery login page (https://informeddelivery.usps.com/box/pages/secure/DashboardAction_input.action?restart=1) only in this instance, the page loads an old login page with a per-load login ID that has expired. Every login attempted from this cached version will always fail, even if I press the refresh button first.

The only workaround in both situations is to press the address bar as if I'm editing the address, then pressing enter. Only then does Firefox Preview load new content from the server.

### Device information
* Android device: Asus Z01RD, Android 9
* Fenix version: 5.2.0 (Build #21701706)

**Comment by ekager** [comment]
Closing for #10417
