### ISSUE TITLE
FNX-12873 ⁃ Hide "Save tabs to collection" if there are no open tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11877]
## Prerequisites
Don't have any open tabs

## Steps to reproduce
Tap the "Save tabs to collection" button

### Expected behavior
"Save tabs to collection" shouldn't be displayed if tabs are opened

### Actual behavior
The Collection creation tabs selection screen is display not having any practical use

### Device information
* Android device: all
* Fenix version: Nightly Build 200624 from 6/24

## Notes
► Video
![20200624-112402](https://user-images.githubusercontent.com/51314259/85522513-6fd13380-b60e-11ea-8243-04ae856c4ac6.gif)

**Comment by ValentinTimisica** [comment]
I think it's a duplicate of https://github.com/mozilla-mobile/fenix/issues/11860

**Comment by vesta0** [comment]
Will fix this as part of #11860
