### ISSUE TITLE
Update Collection creation confirmation snackbar Strings

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11889]
## Prerequisites
Have a couple of open tabs

## Steps to reproduce
1. From the Home screen tap the "Save tabs to collection"
1. Select the desired Tabs and save them to a collection

### Expected behavior
"Collection saved!" confirmation snackbar (As per @betsymi 's suggestion from [#11112](https://github.com/mozilla-mobile/fenix/issues/11112#issuecomment-648829485))

### Actual behavior
Tabs saved! confirmation snackbar

### Device information
* Android device: all
* Fenix version: Nightly Build 200624 from 6/24

**Comment by AndiAJ** [comment]
Hi, I've just cheked thi matter on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ Creating new collections from the tabs Tray
► Video
![20200708-093949](https://user-images.githubusercontent.com/51314259/86886987-90b28200-c100-11ea-96a0-dd534b880eb5.gif)

❓  Creating collections from the ⋮ Main menu  
► Video
![20200708-094242](https://user-images.githubusercontent.com/51314259/86886828-429d7e80-c100-11ea-836f-bad5fab8e5b1.gif)

**Creating new collections from the ⋮ Main menu still displays "Tab saved!"**

✔️ Adding tabs to a previously created collection
Tabs Tray:
1. One open Tab - "Tab saved"
2. Multiple open tabs - "Tabs saved"

⋮ Main menu 
1. Can only add individual Tab - "Tab saved"
 
@ekager & @ValentinTimisica  - Please review. ☺️

**Comment by ekager** [comment]
This sounds like the correct snackbar updates to me with the current behavior. The main browser menu currently only can add the selected/focused tab to a collection.
