### ISSUE TITLE
FNX-12879 ⁃ [Bug] Error colors in input fields are not consistent throughout the app and do not follow UX specs

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#11880]
See screens in : Edit logins & Add search engine

![rsz](https://user-images.githubusercontent.com/51314259/85263776-55655180-b478-11ea-8bbb-c6c3e836569f.jpg)UNITO-UNDERSCORE!1rsz!UNITO-UNDERSCORE!img!UNITO-UNDERSCORE!20200622!UNITO-UNDERSCORE!104507!

![](https://user-images.githubusercontent.com/58657617/81734453-0d1f4080-9483-11ea-9437-4411260e7220.png)

According to these mocks the colors should be: **Light theme - Red 70 #C50042. | Dark theme - Red 40 #FF6A75** :

https://app.abstract.com/share/33afd8de-f90e-4504-90e3-ee2a3bcb1925?mode=design&sha=2b7a1bf44fa2c02a3b7e470075e94c587a491d3b

https://miro.com/app/board/o9J_kwAuqu4=/

And also issue #9596 mentions the same colors. 

cc @brampitoyo @ @AmyYLee can you please double check my assessment? Thank you!

**Comment by brampitoyo** [comment]
Hi @mcarare, your assessment was right. To ensure enough colour contrast for readability and accessibility, we’ve decided on two different error colour values for light and dark/private.

Thanks for fixing this issue!

**Comment by brampitoyo** [comment]
@mcarare Just adding some colour contrast checker measurements:

![Screenshot_2020-06-25 WebAIM Contrast Checker(1)](https://user-images.githubusercontent.com/51007/85661077-6a591380-b70a-11ea-8e10-1ba37a571338.png)

![Screenshot_2020-06-25 WebAIM Contrast Checker](https://user-images.githubusercontent.com/51007/85661085-6cbb6d80-b70a-11ea-9d96-a657b4623b7f.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200625 from 6/25`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Screenshots
![rsz_rsz_img_20200625_132822222222](https://user-images.githubusercontent.com/51314259/85703764-57cde280-b6e8-11ea-8898-60381a312787.jpg)

![rsz_rsz_screenshot_20200625_1316411_orgmozillafenixnightly](https://user-images.githubusercontent.com/51314259/85704226-c57a0e80-b6e8-11ea-9225-b1fbc77530e8.jpg)
