### ISSUE TITLE
FNX2-13660 ⁃ Add a looking glass when selecting text, similar to Chromium.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11882]
Selecting text is somewhat difficult as you can't see exactly what you're selecting because your thumb or finger is in the way. Chromium has a little looking glass that appears above where you're selecting to make it far easier to see exactly what you're selecting. It would be nice if Firefox had this too.

![Chromium looking glass example](https://i.imgur.com/mlWL9EU.jpg)

**Comment by kbrosnan** [comment]
duplicate #3510
