### ISSUE TITLE
Provide information about cached data

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#11888]
### What is the user problem or growth opportunity you want to see solved?
Under delete browsing data currently it is not showing how much data is cached till now.. is it possible to add that information?

### How do you know that this problem exists today? Why is this important?
Present in chromium browsers ensuring some transparency to users.

### Who will benefit from it?
All users

![7021](https://user-images.githubusercontent.com/58127841/85564965-399bb000-b61e-11ea-8898-7dbfd4679eb8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2539)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813627

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
