### ISSUE TITLE
FNX-12893 ⁃ Improve selection menu

### ISSUE THREAD

**Issue by jandryuk** [mozilla-mobile/fenix#11893]
The Fenix selection dialog is less usable compared to the Fennec one.

My primary use of the selection box is Google Search followed by Copy. Select All is a distant third and I've never used Share.
![Screenshot](https://user-images.githubusercontent.com/1879231/85569843-e49d7100-b600-11ea-96c9-2e7fd190c6c9.png)UNITO-UNDERSCORE!20200624-094733!

Compare that with Fenix and Translate isn't useful when reading sites in ones native language.  You have to expand three dots to get to Search, my number 1 use.
![Screenshot](https://user-images.githubusercontent.com/1879231/85569845-e5360780-b600-11ea-91c2-8032778698cf.png)UNITO-UNDERSCORE!20200624-094551!

The selection menu should be arranged in a more useful order.

### How do you know that this problem exists today? Why is this important?
There is more friction when using Fenix since search is the primary use of text selection and it is hidden away.

### Who will benefit from it?
Everyone

**Comment by Diana-Rus** [comment]
Hey, you can check here #10466 , is the feature request for the Context Menu and how it's going to be implemented. have a look.
The search after the selected text it's going to be yet again visible, one of the primary options 😊.

**Comment by jandryuk** [comment]
Yes, that issue looks like what I want, thank you. (I briefly searched, but I guess I didn't got the right terms).

**Comment by Diana-Rus** [comment]
Order of the visible options from Context Menu.
Preferred order:
Copy
Search
Select all
Share
