### ISSUE TITLE
[Bug] The text from dropdown and button seams missalignment on my TP Link router page.

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#11899]
![Screenshot](https://user-images.githubusercontent.com/48178307/85575157-023dfb00-b640-11ea-9d18-aa446d4c2a49.jpg)UNITO-UNDERSCORE!20200624-170941!

* Android device: P10 Lite - WAS-LX1 - 8.0.0
* Fenix version: 5.2.0

**Comment by mcarare** [comment]
@AndRo-Marian is this also reproducible with Fennec?

**Comment by AndRo-Marian** [comment]
@mcarare What is that?

**Comment by kbrosnan** [comment]
If you go into the Firefox settings

* Accessibility
* Disable automatic font sizing
* Set the font scaling to 50% does the text fit in the box?

**Comment by AndRo-Marian** [comment]
Yes. Only the 50% is on center and not cut.

**Comment by ekager** [comment]
@AndRo-Marian are you still seeing this issue?

**Comment by AndRo-Marian** [comment]
Yes @ekager
