### ISSUE TITLE
FNX-12899 ⁃ Bring back the old tab navigation menu

### ISSUE THREAD

**Issue by MatejKafka** [mozilla-mobile/fenix#11898]
The new tab management UI is, in my opinion, a major step back. The old UI was great and innovative, with all features quickly reachable and great screen real estate utilization. The new one has a lot of unnecessary whitespace and interactions and feels like a strictly worse version of Chrome tab list.

The Collections screen (probably about:blank, not sure) is now mostly useless, unless the user uses Collections.

Opening new tab requires 1 more tap, without any good reason, as the new tab list does not really display more content than the old one and it doesn't seem more intuitive either.

**Comment by vrubleg** [comment]
Agree. The new tab management UI is a huge disappointment.

**Comment by julKali** [comment]
Please see #11833, there is already a discussion for this

**Comment by MatejKafka** [comment]
Oops, sorry, did not see that issue. (I swear I tried looking for it :) )
