### ISSUE TITLE
FNX-12904 ⁃ [Bug] White almost invisible "close" and "share" icons in custom tabs when Fenix is always set to open tabs in a Private Browsing mode

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#11903]
## Steps to reproduce
Have the setting to open all links in Private Browsing enabled by going into 3-dot main menu > settings > Private Browsing > Open links in a private tab > enable 

I tested this with [Sync for Reddit](https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync) and [Boost for Reddit](https://play.google.com/store/apps/details?id=com.rubenmayayo.reddit), when opening any link in custom tabs from them the icons for "close" (to close the tab) and "share" completely white such that they are almost invisible.  Please see the screenshots for clarity.

The issue doesn't reproduce if "Open links in a private tab" is not enabled

### Expected behavior
Icons shouldn't be white and invisible

### Actual behavior
Icons are almost invisible

### Device information
* Android device: **Motorola One Power, Android 10**.
* Fenix version: **`Nightly 200624 06:01`**.

![Screenshot](https://user-images.githubusercontent.com/42088907/85582961-62777180-b62d-11ea-942f-1452313992ad.jpg)UNITO-UNDERSCORE!20200624!UNITO-UNDERSCORE!204239!
![Screenshot](https://user-images.githubusercontent.com/42088907/85582988-66a38f00-b62d-11ea-96c5-d00a8859ca37.jpg)UNITO-UNDERSCORE!20200624!UNITO-UNDERSCORE!204157!

**Comment by AndiAJ** [comment]
Hi, just checked this on the latest **Nightly Build 200625 from 6/25** using a Google Pixel 3a (Android 10)

✔️ The "Close" and Action (Share) button are fixed
❌ On the other hand, The TP, Site certificate, URL, and ⋮ Main menu are impropely displayed

►Screenshots
![rsz_screenshot_20200625-123347](https://user-images.githubusercontent.com/51314259/85696172-5cdb6380-b6e1-11ea-985d-e2653ae82da1.png)

@NotWoods - Pleasse review. ☺️

**Comment by sflorean** [comment]
Tested on Nightly 6/30 and 78.0.1-beta.1 and here are my findings:

1. **With Fenix opened in the background in normal browsing**: I am still able to **reproduce** the issue, meaning that "close" and "share" buttons are almost invisible. 

2. **With browser closed:** close and share buttons are visible on the private background - custom tab, but opening the link in the browser and going to settings results in a blank page:
![Screenshot_2020-06-30-11-19-16](https://user-images.githubusercontent.com/58466444/86104322-8ec83d80-bac6-11ea-9d55-48c015d4f285.png)

**Comment by SS1113** [comment]
The issue still reproducible on **`Nightly 200701 06:01`**.

**Comment by ShatteredPixel** [comment]
Hi, I'm the reporter of this issue. Please let me know if you need more information.

Thanks! :)

**Comment by sv-ohorvath** [comment]
I can reproduce the 2nd issue (the screenshot) from this https://github.com/mozilla-mobile/fenix/issues/11903#issuecomment-651652062 with these STR:
1. Open Private Browsing
2. Go to settings>Customize, select Dark theme
3. Select Light theme.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/10 with Samsung Galaxy Note 10 (Android 10) and Huawei MediaPad M2	(Android 5.1.1).

**Comment by B0pol** [comment]
It doesn't work on my device, Nightly 200811 06:01, Pocophone F1, /e/ (based on lineage os 16, android 9)

**Comment by sflorean** [comment]
@B0pol could you please add a video, with the issue? thank you!

**Comment by B0pol** [comment]
<img src="https://user-images.githubusercontent.com/58657617/91634551-7f477100-e9f1-11ea-981e-94001ef2cc0c.gif" width="300">

can you re-open the issue?
