### ISSUE TITLE
FNX-4859 ⁃ Add Telemetery for FxA login

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1190]
@bbinto updated April 4:

#### Description & Product Manager User Story
As a Fenix and sync product manager, I want to know if users sign into their accounts and what sync activities they perform so we can understand stickiness of the app as well as appetite for sync. 

#### What questions will you answer with this data?
* How often users sync in/out via Fenix (in comparison to other devices/apps)
* If there any issues in the flow, drop off in funnel where/when people try to sync

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
Sync/Accounts is part of our overall 2019 KPI goals and so we want to have instrumentation in place to understand how much Fenix is contributing to this goal.

#### What probes (suggested, if applicable)
* most metrics around the actual syn flow is covered in the web flow (see @vladikoff comment)
In addition we want to cover the following events as a start (based on [this](https://mozilla.invisionapp.com/share/YFR8N20QN7R#/screens/352851515_-Fenix-_Sync_UI) sync UI)
* user clicks on "turn on sync", "turn off sync"
* user taps on either "Sign in", "Scan pairing", "+ create a new account"
* sync settings, what types are being synced, e.g. history toggle on/off
* How often people log in/out to FxA via Fenix, I assume we call an event on 
* more to come in the future, but those are the basics I can think of that will be helpful for us to understand the usage of sync within Fenix

### Dependencies (Added by PM and Eng)
* Glean SDK

### Acceptance Criteria (Added by PM)
* Event pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by bbinto** [comment]
Thinking about this a little more - @vladikoff - do we need to provide extra telemetry beyond what you are already collecting? (since our CTA is to go to the web-based login that you own)

Things we'd be interested from a Fenix perspective
- how often people log in/out to FxA via Fenix
- Any kind of syncing activities

**Comment by vladikoff** [comment]
> Things we'd be interested from a Fenix perspective

>> how often people log in/out to FxA via Fenix
>> Any kind of syncing activities


These are great, it would be good to have those!

 I don't think we need extra telemetry for now because yes, we would get metrics and error reports in the web flow. Otherwise we are working on adding telemetry to the low-level components in Q2 and should hopefully have even more telemetry.

**Comment by bbinto** [comment]
@vladikoff - So are you saying, you will be able to know if/when people sing out/in from Fenix without any further instrumentation from our end?

**Comment by vladikoff** [comment]
@bbinto oh sorry I misunderstood! I thought you were planning to have client telemetry events for these:

- [x] how often people log in/out to FxA via Fenix
- [x] Any kind of syncing activities

I highly suggest we implement the above in the Fenix client if we don't have those yet, especially if you want to see the metrics in places other than Amplitude and Re:Dash. The FxA web and server events go into Amplitude and Re:Dash and we can keep track things there as well. I think in amplitude we should be able to understand the `how often people log in/out to FxA via Fenix`. However `Any kind of syncing activities` is much trickier. @irrationalagent any input here, what would you like to see for Fenix + Fxa/Sync metrics?

**Comment by bbinto** [comment]
@boek this should now be updated, however I'm not sure how far we've come with the sync work, based on Ryan's mocks, I don't currently see that flow in Nighlty yet.

**Comment by sv-ohorvath** [comment]
> * user clicks on "turn on sync", "turn off sync"
> * user taps on either "Sign in", "Scan pairing", "+ create a new account"
> * sync settings, what types are being synced, e.g. history toggle on/off
> * How often people log in/out to FxA via Fenix, I assume we call an event on

Verified these event pings are sent so far:
sync_auth:
opened
closed
sign_in
scan_pairing
create_account

sync_account:
opened
closed
sync_now
sign_out

@sblatz ["syncing_items"](https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml#L373) metrics ping is not sent: https://debug-ping-preview.firebaseapp.com/pings/7d99d025-c78e-40f6-865a-290588b384f9/oh-sync-syncingitems
Is this because of https://github.com/mozilla-mobile/fenix/issues/2157? Should I log a new issue to be fixed later?

**Comment by sblatz** [comment]
@sv-ohorvath if you tap the "sync now" button, it should force the syncing items to be sent:

`Syncing items: [pref_key_sync_bookmarks, pref_key_sync_history]`

I just tested this on the latest master. Are you able to try again with a forced sync?

**Comment by sv-ohorvath** [comment]
@sblatz Tested with Andrei Joltan on the latest build (6/5): 
STR:
1.fresh install 
2. open Fenix-ul
3. sign in & sync (forced sync or auto-sync)
4. cmd adb shell am start -n org.mozilla.fenix/mozilla.components.service.glean.debug.GleanDebugActivity --ez logPings true --es sendPing metrics --es tagPings aj-sync-011
- both cases of auto-sync and forced sync result in an empty "metrics.syncing_items": []
- see examples:
* https://debug-ping-preview.firebaseapp.com/pings/ba20879d-7bcd-4a03-81fb-376dd9b8bac1/aj-sync-011
* https://debug-ping-preview.firebaseapp.com/pings/f09de0bd-254a-44c4-95a5-7fe2bb9be602/aj-sync-001
Following the same steps as Andi, on my devices, the metric doesn't appear at all: 
https://debug-ping-preview.firebaseapp.com/pings/4b2f5e3f-df69-48d7-a91b-99143ee6b6e1/oh-sync-nexus

**Comment by sblatz** [comment]
Ah, I had a misunderstanding! The items were only getting set after visiting the sync page, and then would get sent in the next core ping. That being said, this is clearly not an ideal solution because we will only know the syncing items of users who visit that page.

I'm going to connect with @grigoryk to see if we have an API that will tell us `syncing_items` so we can just send it in the startup ping.

**Comment by sblatz** [comment]
The "syncing items" is actually for post MVP, so I will remove them from the documentation and we can add them when they're functioning properly!

**Comment by AndiJoltan** [comment]
Hi, it looks like the FxA login works as expected.
**The steps for this session are as it follows :** 
1.   Turn on Sync
2.   Scan pairing
3.  Create account
4.   Custom tab opens
5.   Custom tab closed after successfully creating the account
6.  Go back to home page
7.   Account settings
8.   Sign out
9.   Closed Account page
10.   Turn on Sync
11.   Sign in 
12.   Sign in custom tab opens
13.   After successfully signing in 
14.  Go back to home page
15.  Account settings
16.  Sign out
17.  Closed Account page

**I would kindly ask you to confirm if everything looks ok from your point of view as well.**
The logcat (Lines 8337 - 8465)- [SN9.txt](https://github.com/mozilla-mobile/fenix/files/3266130/SN9.txt)
Glean dashboard: https://debug-ping-preview.firebaseapp.com/pings/e1739d88-c114-4f6e-8669-c27f0f6ca3aa/aj-xa-02
