### ISSUE TITLE
FNX-12909 ⁃ [Telemetry] PWA installs

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#11909]
Related to #10261 

## What questions will you answer with this data?
* How many active installs of PWAs are there?

## Engineering work
* AC work is being done in https://github.com/mozilla-mobile/android-components/issues/7474

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by kbrosnan** [comment]
Reopned so the SV team can evaluate any manual testing that is needed.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly Build 200629 from 6/29`** and **`Fenix 78.0.1-beta.1 from 6/27`** using a Google Pixel 3a (Android 10)

#### ✔️ Nightly Build 200629 from 6/29

• **No PWA's installed**  - Ping 
```"metrics.has_recent_pwas": false```

• **2 Installed PWA's** - Ping 2f940940-fce3-4e44-b839-c569bf8bb97f
```
"metrics.has_recent_pwas": true
"metrics.recently_used_pwa_count": 2
```

• **4 Installed PWA's** - Ping 6be66d16-9573-402a-9c13-aabdeb0dd402
```
"metrics.has_recent_pwas": true
"metrics.recently_used_pwa_count": 4
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/4846145/gtl.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t2906001)

#### ✔️ Fenix 78.0.1-beta.1 from 6/27
•  **10 Installed PWA's** - Ping ba9d4a9b-674a-413a-85d8-1066d60f4485
```
"metrics.has_recent_pwas": true
"metrics.recently_used_pwa_count": 10
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/4846187/bbb.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-testMig29062)
