### ISSUE TITLE
FNX2-13667 ⁃ The Fireffox Preview title uses too much space with no reason.

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#11900]
1. The Firefox Preview title just has useless space. Make it to be on the center of the Private button.
![Screenshot](https://user-images.githubusercontent.com/48178307/85577758-31ee0280-b642-11ea-919e-d0b63163f342.jpg)UNITO-UNDERSCORE!20200624-171033!
1. Same for the new TabList. The top bar are too big and is over the AddressBar.
![Screenshot](https://user-images.githubusercontent.com/48178307/85579926-f5bba180-b643-11ea-85bc-5340cc390c5f.jpg)UNITO-UNDERSCORE!20200624-175249!

* Make is on the screen static. Every time i try to scroll to a Website to top is closing.

To a little comparison i like how the normal Firefox is aligned. Just that has no DarkTheme.

**Comment by pidus** [comment]
A compact mode would be nice.

**Comment by AmyYLee** [comment]
Firefox Preview has now migrated to Firefox Nightly. Closing issue.
