### ISSUE TITLE
FNX2-13669 ⁃ [Bug] java.lang.IndexOutOfBoundsException: at java.util.ArrayList.get(ArrayList.java)

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#11906]
This looks to be the top crash in the 20200622093309 Nightly.

## Stacktrace
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at mozilla.components.browser.search.SearchEngineManager.getProvidedDefaultSearchEngineAsync(SearchEngineManager.kt:7)
	at mozilla.components.browser.search.SearchEngineManager.getDefaultSearchEngineAsync(SearchEngineManager.kt:7)
	at mozilla.components.browser.search.SearchEngineManager$getDefaultSearchEngineAsync$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

* Android device: ?
* Fenix version: 20200622093309 0.0a1 Nightly

**Comment by kbrosnan** [comment]
Hm @pocmo filed https://github.com/mozilla-mobile/android-components/issues/5842

**Comment by kbrosnan** [comment]
* Sentry issue: [FENIX-FENNEC-NIGHTLY-AG](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7288989/)

* https://crash-stats.mozilla.org/signature/?product=Fenix&version=0.0a1&signature=java.lang.IndexOutOfBoundsException%3A%20at%20java.util.ArrayList.get%28ArrayList.java%29&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports

**Comment by hakkikaancaliskan** [comment]
This happened after update from 6/20 to 6/24.
Only fix was clear app data.

**Comment by liuche** [comment]
This could be related to #9935 changes

**Comment by liuche** [comment]
I'll file this other issue: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8870448/?query=is%3Aunresolved

**Comment by liuche** [comment]
We think this will also be fixed by #12081

**Comment by lindongbin** [comment]
https://crash-stats.mozilla.org/report/index/8cd6f146-2dc6-4f2c-a477-5b2140200703

null (Build #2015749827)
AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7
Friday 7/3 @ 8:43 AM

**Comment by pocmo** [comment]
Looks like this made the top crasher list.

The last minute search changes really had a ripple effect and caused some issues. :( I hope we can try to get rid of the band-aid eventually.

**Comment by st3fan** [comment]
I put the 79 Release Blocker label on this because this is a very high frequency startup crash.

Looping in @Mugurell as this may be related to #11875

**Comment by st3fan** [comment]
Quick note: this crash is trending down in Sentry, but I think that is a false sign. I think a LOT of people hit this either at first run or a few times at startup, and then the situation resolved itself. That however does not change the fact that this is a high frequency startup crash. I've seen a number of reports on Reddit where people say they can't start the app, and this is probably one the reasons.

**Comment by Mugurell** [comment]
Indeed, I'm thinking that fixing #11875 (which is another effect for probably the same underlying issue) would also get to resolve this and a bunch recent others related to search engines.

**Comment by liuche** [comment]
Since we think the fix for #11875 may also fix this one, let's see if we can make sure this isn't still a problem.

**Comment by sv-ohorvath** [comment]
While testing the fix for #11875 I didn't encounter any crashes on 79.0-beta6. @liuche Should I close this or do you want to continue monitoring the crash rates?

**Comment by liuche** [comment]
We released beta.8 and beta.9 today and I haven't seen any issues in Sentry, so let's close this now. Can reopen if it shows up again, but the last crashes I've seen have been from beta.3.

**Comment by Mugurell** [comment]
Closing based on https://github.com/mozilla-mobile/fenix/issues/11906#issuecomment-660271105
