### ISSUE TITLE
FNX2-13676 ⁃ [Bug] Tab tray shows a white/blank preview on reader view pages

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11918]
## Steps to reproduce
1. Navigate to a page that allows reader view, eg: https://www.nbcnews.com/news/us-news/florida-s-stand-your-ground-law-under-scrutiny-after-father-n893646
1. Open reader view
1. Open tab tray

### Expected behavior
I see a an image of the reader view page in the tab tray.

### Actual behavior
I see a white colored preview (blank).

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 200624 06:01 (Build #21760611)
AC: 47.0.20200623130149, 88694edfb
GV: 79.0a1-20200622093309
AS: 61.0.2

**Comment by csadilek** [comment]
See: https://github.com/mozilla-mobile/android-components/issues/7413

**Comment by csadilek** [comment]
This will be fixed by https://github.com/mozilla-mobile/android-components/issues/6905 which also requires https://bugzilla.mozilla.org/show_bug.cgi?id=1647797

**Comment by jonalmeida** [comment]
> This creates additional jank when opening up the tab tray while the the tab is still scrolling.

This sounds like a bug in the GV thumbnail capture that causes the stutter.

The approach you mentioned will lead to _even_ more thumbnails being taken and can lead to larger perf loss on low end devices. Let's address this in a separate issue?

**Comment by hwinnemoe** [comment]
I fail to understand how this could lead to more thumbnails, my approach would avoid taking a capture at all while the tab is still scrolling and capture again the next time the tab tray is opened. Anyway, like you said, let's keep this issue focused on the blank tab preview problem and file follow-up issues :)

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly build 8/26** with **Google Pixel 4 XL (11).**
