### ISSUE TITLE
[Bug] Black flash when navigating back to homescreen after opening search screen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11910]
## Steps to reproduce
* Open app to homescreen
* Click wikipedia
* Click url bar to open search
* Press back (to wikipedia)
* Press back (to home)

### Expected behavior
Smooth transition

### Actual behavior
Flash of black when going to the homescreen. This doesn't appear to happen if you don't go to the search screen first.

I assume the black flash is GeckoView closing the tab – perhaps we can defer that until after the navigation completes?

### Device information
* Android device: P2
* Fenix version: Nightly 200624

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2569)

**Comment by liuche** [comment]
Flagging to take a look in case this is due to changes from the New Search experience. Gif in #14659 of a worse scenario

**Comment by eliserichards** [comment]
I'm not seeing the black screen on the latest Nightly

**Comment by eliserichards** [comment]
Pixel, API 28
<img width="325" src="https://user-images.githubusercontent.com/43795363/92960346-13262d80-f433-11ea-9545-e5d99dbc970e.gif">

**Comment by mcomella** [comment]
I can still reproduce as of Nightly 200918.

**Comment by delia-pop** [comment]
Hello, a similar issue can be observed in the current Fenix browsers Nightly 106, Beta 105.0b6 and RC 104.2.0 on devices with Android version <=10.
A more visible black flash will be displayed on different instances during browsing:
- returning from browser to homepage;
- accessing Settings from browser;
- tapping the URL bar from browser;
- tapping the "+" or "+ PRIVATE" buttons on tabs tray from browser;

Tested with OPPO A15s (Android 10), Samsung Galaxy S7 (Android 8), Huawei MediaPad M3 (Android 7).

https://user-images.githubusercontent.com/89388888/189337229-72578237-f078-4899-987a-2dfd2ceab482.mp4

https://user-images.githubusercontent.com/89388888/189337249-4203dd34-4548-4f2a-bb7d-82ab043bba79.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807734

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
