### ISSUE TITLE
FNX2-13672 ⁃ [Bug] Tab order changes on undo close tab

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11912]
IDK if this is intended behavior but it was not like this before

## Steps to reproduce
Open tabs
Close one
Undo close

### Expected behavior
Same order(?)

### Actual behavior
Revived tab inserted at top

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/12449#issuecomment-656772138
