### ISSUE TITLE
[Bug] Search engine logo in homescreen toolbar takes a long time to show up on start

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#11911]
## Steps to reproduce
* Cold start app

### Expected behavior
Search engine logo in toolbar appears quickly

### Actual behavior
Search engine logo takes a long time to appear sometimes. Video: https://drive.google.com/file/d/1sFp6hRLVIoT3Xri-C6En_SgeQqPUHoUj/view?usp=sharing

### Device information
* Android device: GS5, P2
* Fenix version: Nightly 200624

- - -
Not sure this is worth fixing but it does look a little unpolished.

I assume this has a similar root cause to https://github.com/mozilla-mobile/fenix/issues/9935 where we're fetching something from the network before displaying the result.

**Comment by mcomella** [comment]
For context, this is the search engine icon I'm referring to:
![device-2020-06-24-145438](https://user-images.githubusercontent.com/759372/85631638-c3517a80-b62a-11ea-81fa-e74b916945c8.png)

**Comment by mcomella** [comment]
sraturi wasn't able to reproduce this in recent builds.

**Comment by kbrosnan** [comment]
Closing as works for me based on Mike's comment.
