### ISSUE TITLE
[Bug] SVGs are not scalable properly

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11915]
## Steps to reproduce
Go to
https://www.w3schools.com/graphics/tryit.asp?filename=trysvg_myfirst
Zoom in on the yellow circle

### Expected behavior
Smooth curves, as expected from an svg image

### Actual behavior
Jagged curves

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200625-011552_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/85620738-bac16a00-b653-11ea-822b-c67795a5572c.png)
Fenix
![Screenshot_20200625-011902_Chrome](https://user-images.githubusercontent.com/33252312/85620920-fc521500-b653-11ea-9254-4035f237c909.png)

Chrome

**Comment by s-ankur** [comment]
Since fenix allows much more zooming than chrome, this issue is even more pronounced

**Comment by Diana-Rus** [comment]
Hi, I encountered this issue with Google Pixel 3 XL (Android 9) - GPU - Andreno (TM) 630 check screenshots: 
- the setting "gfx.webrender.force-disabled" is set to false 
- in about:support the webrender shows that it's on/enabled

<details closed>
<summary>With "gfx.webrender.force-disabled" set to true</summary>

![Screenshot_20200709-144537](https://user-images.githubusercontent.com/49859863/87036571-ae144880-c1f3-11ea-8582-451a5998ca11.png)
</details>
<details closed>
<summary>With "gfx.webrender.force-disabled" set to false (default)</summary>

![Screenshot_20200709-144537](https://user-images.githubusercontent.com/49859863/87036548-a81e6780-c1f3-11ea-95da-10f4c367f7a2.png)
<details>

Note: I haven't encounter the issue with Sony Xperia Z5 (Android 7) GPU - Andreno (TM) 430

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/8 Nightly build on Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1):

![Untitled](https://user-images.githubusercontent.com/40694158/107212836-34a23a00-6a10-11eb-8002-2d4b5a9a1d94.png)
