### ISSUE TITLE
[FR] New type of zoom: desktop-like

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#11914]
### What is the user problem or growth opportunity you want to see solved?
On some non-mobile friendly websites, it's really hard to read the text and everything is small. 

The current zooming way improves readability, but it's still bad.
My idea is to use desktop like zoom: until some point, the layout of the website doesn't change, only the text is bigger, and when it's not possible it switches to mobile-like zoom: layout is different, and everything is zoomed.

I don't know how can it be implemented to switch between current and the zoom I'd like way, maybe a preference in the three dot menu for quick accessibility, and / or in settings; maybe put it in the three.
Another idea of implementation: only show it in the three dot menu when the [viewport meta tag](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) is not available, otherwise you have to change in settings.

### How do you know that this problem exists today? Why is this important?
There are still tons of non-mobile friendly websites, and improving the user experience for the users of these websites is important.

### Who will benefit from it?
Any users of non-mobile friendly websites. For example, bugzilla.mozilla.org, phabricator, any GitWeb instance, …; all of these websites are used by mozilla.

**Comment by pidus** [comment]
This would be really cool. I believe Opera, Yandex have this feature.

**Comment by yoasif** [comment]
Increase/decrease text size would be handy and I ran into this myself on mobile sites that use too small text.

**Comment by kbrosnan** [comment]
Reflow zoom is #808, closing as a duplicate.
