### ISSUE TITLE
[Bug] Pause button still visible in tab tray for tabs that are in reader mode

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#11920]
## Steps to reproduce
Open https://en.m.wikipedia.org/wiki/Wikipedia:Videos
Go to reader mode
Open tabs tray

### Expected behavior
No pause icon since no media is played

### Actual behavior
Pause icon that does nothing when presses and does not go away even after changing the website

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 200908 (Build #2015762675)

### Devices used:
- OnePlus 6T (Android 9)
- Huawei P Smart (Android 9)
