### ISSUE TITLE
remove MainScope.launch from IntentReceiverActivity

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#11922]
This is a follow up issues from https://github.com/mozilla-mobile/android-components/issues/7217 in Android-Component. 

the removal of `suspend` and coroutine dispatch gives us a good ~50ms gain on VIEW start up on low end devices (Tested on G5 on FNPRMS)

**Comment by ekager** [comment]
Looks like this might be done?
