### ISSUE TITLE
FNX-12940 ⁃ Cannot open 2 tabs of Instagram

### ISSUE THREAD

**Issue by Rodze** [mozilla-mobile/fenix#11936]
## Steps to reproduce
Open one tab for Instagram, wait for it to load.
Open a second tab for Instagram

### Expected behavior
Load instagram page

### Actual behavior
Blank page

### Device information
* Android device: Galaxy S9 Android 9
* Nightly version: 200624 2015748083

[https://i.imgur.com/67cYF60.mp4|url](https://i.imgur.com/67cYF60.mp4|url)

**Comment by mcarare** [comment]
Cannot reproduce on a Huawei P10, Android 9.

**Comment by Augures01** [comment]
I can reproduce this in 1 tab. Happens only when you manually type (or paste) second instagram link.

**Comment by Augures01** [comment]
@Rodze 
Can you check this issue on latest nightly?
I can't see this bug anymore
Maybe it's fixed or initially not a Fenix bug

**Comment by Rodze** [comment]
@Augures01 
You're right. It seems it was fixed by something. It's now opening all tabs normally.

Thanks for the heads up. Gonna close this.
