### ISSUE TITLE
FNX-12942 ⁃ [Bug] Security issue: mozilla credentials access from other apps

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#11938]
Pressing `Yes, sign me in` it will successfully sign in without any confirmation from other side.
So it seems that any other app can request credentials from fenix, and it's completely unclear what should prevent it.

![image](https://user-images.githubusercontent.com/14617699/85658707-4b339500-b6bc-11ea-9fd6-62dcdad0c7dc.png)

### Steps to reproduce
1. Install fenix and fenix nightly
1. Log in on fenix to mozilla sync
1. Start nightly

### Expected behavior
Fenix must ask for confirmation to share mozilla credentials.

### Actual behavior
Fenix shares mozilla credentials without confirmation.

### Device information
* Android device: ?
* Fenix version: 5.2.0

**Comment by liuche** [comment]
This is working as expected - we share credentials through a ContentProvider only with trusted apps (that Mozilla builds and publishes). See https://github.com/mozilla-mobile/android-components/issues/2775 for more information.
