### ISSUE TITLE
FNX-12941 ⁃ [Bug] Black bar being added in "installed" webpage

### ISSUE THREAD

**Issue by nizdi** [mozilla-mobile/fenix#11937]
## Steps to reproduce
Install mangadex.com page. Open.

### Expected behavior
Should work like an app and do not create a strange black bar

### Actual behavior
Creates a black bar that does not existe if you use normal browser or other browser (chrome).

### Device information
* Android device: mi pad 4 plus
* Fenix version: latest update from play store

![IMG](https://user-images.githubusercontent.com/29477616/85652415-076f6a00-b681-11ea-8d7d-6ec70515b7b6.jpg)UNITO-UNDERSCORE!20200625!UNITO-UNDERSCORE!011226!

I hope it might not be a bug just an misunderstanding of how to use it.

I tried disabling all add-ons from the website but nothing changed.

The problem with this blackbar is that it's makes harder to read manga, for example. It's not a big issue.

**Comment by ekager** [comment]
Thanks for reporting! This will be fixed in the next update by #11747
