### ISSUE TITLE
FNX2-13679 ⁃ Move BrowserThumbnails to BrowserFragment

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#11935]
We only need this component when you're in the main browser app. Having it in `BaseBrowserFragment` would mean we're taking screenshots of custom tabs and PWAs unnecessarily. This should be a small perf win for Custom Tabs/PWAs.

**Comment by person808** [comment]
Don't think this is something that can be checked by QA so closing.
