### ISSUE TITLE
[Bug] QR scanner can glitch into green output on Xiaomi Redmi Note 8 Pro

### ISSUE THREAD

**Issue by vaporwave9** [mozilla-mobile/fenix#11941]
## Steps to reproduce
Cycle the QR scanner a few times. It doesn't matter if fast or slow.

See video: [Screenrecorder-2020-06-25-09-48-55-206.zip](https://github.com/mozilla-mobile/fenix/files/4829871/Screenrecorder-2020-06-25-09-48-55-206.zip)

### Expected behavior
You should see output of the camera feed of the Xiaomi Redmi Note 8 Pro.

### Actual behavior
The camera feed is replaced with a green only overlay.
Sometimes it fixes itself, but even in green screen **SCANNING STILL WORKS!**

![grafik](https://user-images.githubusercontent.com/64961250/85680105-483fa100-b6ca-11ea-85e9-622d053c047f.png)

### Device information
* Android device: Xiaomi Redmi Note 8 Pro using Android 10
* Fenix version: too much to write, see pic

![grafik](https://user-images.githubusercontent.com/64961250/85679922-234b2e00-b6ca-11ea-9081-cc1585192bc4.png)

**Comment by mcarare** [comment]
@vaporwave9 Does this happens in other scanning apps?

**Comment by vaporwave9** [comment]
No, it never happens in Barcode Scanned from F-Droid.
Only Fenix glitches like this.

**Comment by vaporwave9** [comment]
Since the triage label was removed and set to investigation, I assume there is no interest anymore in resolving the issue.

**Comment by mcarare** [comment]
@vaporwave9 The label removal means the opposite, it means the issue has been properly labeled.
I managed to test this on a Xiaomi Redmi Note 8 Pro and I can also see the green screen. 
This only happens when I try to scan a QR code from the search bar, but it does not happen when I try to scan for pairing (open the menu from Settings -> Turn on sync).

Can you confirm this behavior in your case?

**Comment by mcarare** [comment]
For QA: can you test this on other Xiaomi devices? Thank you!

**Comment by vaporwave9** [comment]
![grafik](https://user-images.githubusercontent.com/64961250/107924715-b693e500-6f73-11eb-80ec-e445724086ed.png)
![grafik](https://user-images.githubusercontent.com/64961250/107924730-bc89c600-6f73-11eb-9a3f-ead804a667c2.png)
![grafik](https://user-images.githubusercontent.com/64961250/107924743-c0b5e380-6f73-11eb-9e00-3eb5780e5103.png)

>QR code from the search bar
>
Confirm: still broken

>try to scan for pairing 
>
Confirm: working

I am using latest FF beta.

**Comment by sflorean** [comment]
@mcarare tested on the following devices (builds: RC, Beta and Nightly) and couldn't reproduce the issue:
- Xiaomi Mi 8 Lite (Android 9)
- Xiaomi Redmi Note 8T (Android 9)

**Comment by vaporwave9** [comment]
Thanks, good bot!
