### ISSUE TITLE
[webcontent]No video with supported format and MIME type found

### ISSUE THREAD

**Issue by lhirlimann** [mozilla-mobile/fenix#11942]
## Site with issue and any steps to reproduce
load https://developer.apple.com/videos/play/wwdc2020/10686/

### Expected behavior
I can play the video.

### Actual behavior
![image](https://user-images.githubusercontent.com/415751/85684298-4677dc80-b6ce-11ea-8f55-a618ac01135a.png)

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
Yes

### Device information
* Android device: Redmi Note 7 up to date.
* Fenix version: Nightly

**Comment by hakkikaancaliskan** [comment]
Please use "Report site issue" addon for webcontent issues.
<img src="https://user-images.githubusercontent.com/17825767/85716910-9b7b1900-b6f5-11ea-811e-abd49197fe81.png" width="300">

**Comment by hakkikaancaliskan** [comment]
Hmm no problem on fennec android and desktop. This is fenix problem.

**Comment by Diana-Rus** [comment]
Hi, i also reproduce this issue with Pixel 3 XL (Android 9), but what's interesting is that i can't reproduce it with Sony Xperia Z5 (Android 7).
There was no add-on installed.

Pixel - GIF
![20200625-160457](https://user-images.githubusercontent.com/49859863/85728785-e9494e80-b700-11ea-9f30-891393cdd79d.gif)
Sony - GIF
![20200625-160420](https://user-images.githubusercontent.com/49859863/85728833-f1a18980-b700-11ea-9eaa-4e6ba8c0a263.gif)
