### ISSUE TITLE
FNX2-13683 ⁃ Intermittent UI test failure - testDownloadNotification - API28

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#11944]
### Firebase Test Run:
Copied from https://github.com/mozilla-mobile/fenix/issues/5462#issuecomment-561760268
intermittent fail on API 28
https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8780279402119153460/executions/bs.e7261e4c00726c9e/testcases/1/test-cases

"In the video, the notification shade has a ton of other things and the notification we want to check against must be off-screen. Test fix would see if we can scroll the notification into-view."

This test was disabled a while ago, I opened this issue to track it and re-enable when possible.

**Comment by rpappalax** [comment]
Try 5-10 different devices simultaneously in flank.yml. See if notification prompts are different

**Comment by sv-ohorvath** [comment]
downloads fail on Nightly: #14052 - waiting for this to be fixed before reopening the PR
