### ISSUE TITLE
As a user I would like to be able to quickly access my top sites and collections in the tab tray

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11958]
### What is the user problem or growth opportunity you want to see solved?
Quick access to my top sites and collections via the tabs tray while browsing

### How do you know that this problem exists today? Why is this important?
broken out of #11833

### Who will benefit from it?
Users who like having access to their collections and top sites

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/10372

**Comment by SS1113** [comment]
I can imagine the Collections in the Tabs Tray but how do the Top Sites can be integrated into the Tabs Tray?

I think the Top Sites are okay where they are.

**Comment by yoasif** [comment]
> I can imagine the Collections in the Tabs Tray but how do the Top Sites can be integrated into the Tabs Tray?
> 
> I think the Top Sites are okay where they are.

Agreed, I think top sites should be put into the address bar like desktop and Fennec, and also tracked in #11296 or #10198.

**Comment by AmyYLee** [comment]
Assigning to @topotropic for consideration
