### ISSUE TITLE
Focus address bar when opening new tab

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#11955]
Spawned from https://github.com/mozilla-mobile/fenix/issues/11833

Prior to the tab tray introduction, it took two taps to create a new tab and focus the address bar in the "new tab". This felt fast and this has regressed the feeling of speed since tab tray now requires three taps. 

I think the best maintain the feeling of speed from prior Fenix is to focus the address bar on new tab creation, and to include the home page content (like top sites) on that screen.

Ideally the flow would look like:

1. Tap tab switcher icon (or open tab switcher menu)
1. Tap new tab FAB or new tab context menu
1. Fenix opens Fenix Home with address bar focused
1. Address bar page dispenses with "this time search with" content and instead includes items from home (like top sites from https://github.com/mozilla-mobile/fenix/issues/11296 or https://github.com/mozilla-mobile/fenix/issues/10198)
1. User can touch the content area to access Home directly (move focus from address bar) OR they can tap back to close the keyboard

Samsung Internet, Edge and Opera all show some piece of the home page content when their address bars are focused - the only difference here would be that Fenix would focus the address bar automatically.

![signal-2020-06-24-160705](https://user-images.githubusercontent.com/152493/85622473-dec18300-b634-11ea-9968-f4371de8aead.png)UNITO-UNDERSCORE!003!
![signal-2020-06-24-160705](https://user-images.githubusercontent.com/152493/85622475-df5a1980-b634-11ea-9e37-50971912fe3d.png)UNITO-UNDERSCORE!002!
![signal-2020-06-24-160705](https://user-images.githubusercontent.com/152493/85622477-df5a1980-b634-11ea-869d-1911b339c834.png)UNITO-UNDERSCORE!001!

This will allow users to go back to the two tap method of opening a new tab and focusing the address bar on open (like desktop and pre-tab tray Fenix).

The larger issue with the old design was that opening a new tab never actually opened a new tab unless you navigated to a new page in the address bar "interstitial", which the new design helps along.

_Originally posted by @yoasif in https://github.com/mozilla~~mobile/fenix/issues/11833#issuecomment~~649048428_

**Comment by kbrosnan** [comment]
We have tried this in early nightly builds with the tabs tray. It was rejected because it prevents the user from getting to the home screen.

**Comment by yoasif** [comment]
@kbrosnan Not sure what you mean by that - I think we definitely need changes to the address bar UI as well (it likely makes sense to open a new issue for that) because you are correct that the address bar doesn't contain content from home, which this issue demands (see #4 above): 

>Address bar page dispenses with "this time search with" content and instead includes items from home

**Comment by keeferrourke** [comment]
I think this suggestion would be a much needed improvement.

> We have tried this in early nightly builds with the tabs tray. It was rejected because it prevents the user from getting to the home screen.

To address this, could it be also be worth adding a home button to the bottom URL bar so that users can still quickly/directly access tab collections when they want them?

This could have nice parallels to desktop Firefox where there's a home button (which takes you to the home page) and a new tab button (which opens a new tab and focuses the URL bar).

(Disclaimer: I'm not a UX guy in the slightest!)

**Comment by s-ankur** [comment]
Agreed. There is so much unnecessary cognitive load for doing it right now. Moreover it does not even make sense in the case of a private tab since the "Home Screen" at that point is just a blank purple wall.

**Comment by brampitoyo** [comment]
On principle, I agree with the suggestions presented on this issue. But I want to be aware that opening the keyboard up will prevent some of the homescreen from being seen, and that “make the most useful and frequently accessed types of content easily accessible on the homescreen” is one of our goals this quarter.

I still think that there is a way out, and that we can put the keyboard up by default if we think long and hard about only showing what’s necessary on the homescreen.

**Comment by toupeira** [comment]
@brampitoyo maybe the address bar could only be focused when a tab is opened through the longpress menu?

**Comment by curtisprevo** [comment]
Won't someone think of the ~~children~~ tablets with keyboards?!

I would love for the option to turn this feature on for tablets.  When I open a new tab, I want it to function the same way it does on a laptop and focus the address bar; my tablet is essentially a laptop.  I do understand it not working this way on phones, and I wouldn't want it that way on a phone.  But literally every time I use Firefox on my tablet, this confuses the heck outta me and I type half an address into the void.

**Comment by kbrosnan** [comment]
This is in nightly #13052
