### ISSUE TITLE
FNX-4863 ⁃ Telemetry for the Quick Action Bar

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1195]
### Hypothesis
Our hypothesis is that the quick action bar is easy and intuitive to use: 

### What questions will you answer with this data?
* How often quick bar is being opened/closed
* Time between opened and closed (Amplitude)
* What are the most clicked actions?

### Events/Pings
* swipe up/down
* touch on each action

### Acceptance Criteria (Added by PM)
* Pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* [Request Review](https://github.com/mozilla/data-review/blob/master/request.md)

**Comment by sblatz** [comment]
So we actually cannot add Telemetry for the quick action sheet _buttons_ just yet as they don't actually do anything (Read, bookmark, etc.). What we have implemented is simply visual.

We **can** do telemetry for when the sheet is opened/closed. Is that sufficient for now? @bbinto

**Comment by colintheshots** [comment]
Bookmark and Share actions both work already.

**Comment by sblatz** [comment]
Ah, wasn't aware of that. Thanks @colintheshots 😄
