### ISSUE TITLE
FNX2-13687 ⁃ [Bug] Back should always return to last open tab after exhausting current tab's back history

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#11953]
## Steps to reproduce
1. Open a webpage.
1. Highlight a word, long press, and select "Firefox Nightly Search".
1. Wait for the new tab with search results to load.
1. Go back using Android 10's swipe gesture.
1. See that top sites/collections view is now open rather than being bought back to the previously open tab.

### Expected behavior
See above

### Actual behavior
See above

### Device information
* Android device: ? Huawei Mate 20 X with Android 10
* Fenix version: ? Nightly

**Comment by SS1113** [comment]
Yeah, this feels very disconnected! When the back button is pressed after searching through Fenix it should just bring to where the user was before doing the action. Don't know why this is acting like this.

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/7512

**Comment by robsmith11** [comment]
I forgot to mention: Fennec already handled this perfectly IMO, so matching the old behavior would be great.

**Comment by SS1113** [comment]
@robsmith11 seems like they already fixed it! The fix is still in review. And once it's merged you can download/update the latest Nightly to test the fix.

**Comment by sflorean** [comment]
Verified as fixed on Firefox Nightly 7/3 with Xiaomi Redmi Note 8T (Android 9).
