### ISSUE TITLE
filesize doesn't match, causing dropmefiles.com to fail

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#11969]
Related [Reddit post](https://www.reddit.com/r/firefox/comments/hfhodp/cant_download_anything_on_firefox_mobile/fvyszwr/?context=3)

## Steps to reproduce
1. Go to https://dropmefiles.com/oOhYR
1. Click the download button.

### Expected behavior
The file is downloaded.

### Actual behavior
The download fail every time

### Device information
Android 10
Firefox 77.0.0-beta 2 (Build #2015744451) 42.0.1
AS: 0.58.2

**Comment by Amejia481** [comment]
For some reason the downloaded file size is smaller than the `contentLength` provided by the sever and we are failing the download [here](https://github.com/mozilla-mobile/android-components/blob/8ab4d0740ea142acf58e563f58ed4afe1eb3eeca/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L585), more investigation is needed

**Comment by eliserichards** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1680835

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Amejia481** [comment]
We changed the gv download api, I tried on nightly and I was not able to reproduce. Let's double check with the help of the QA team.

**Comment by abodea** [comment]
Hello, @Amejia481 the link expired so I created a new one, with a picture, is that enough?
I tried on the latest **Nightly 9/12** with **Google Pixel 4 XL (11)** but I couldn't reproduce it.
I will close this issue accordingly, please let me know if the picture uploaded on that website is not enough or if there was another file.

**Comment by Amejia481** [comment]
> Hello, @Amejia481 the link expired so I created a new one, with a picture, is that enough?

Yes, thank you!
