### ISSUE TITLE
As a user, I want it to be more clear that I am in the private tabs list in the tabs tray

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11960]
### What is the user problem or growth opportunity you want to see solved?
The UI in the tabs tray doesn't change much when you click into the private tabs. I don't think we should change the entire theme (from an eng perspective it would be bad performance wise) but maybe we can add more indicators that they are in private mode (some purple border etc) 

### How do you know that this problem exists today? Why is this important?
Broken out of #11833

### Who will benefit from it?
Users who use private mode in the tabs tray

**Comment by sheikh-azharuddin** [comment]
Maybe you can change the color the background of the top section of the tab tray to purple with white private mode logo

![7045](https://user-images.githubusercontent.com/58127841/85769014-2285bc80-b709-11ea-80c6-7814c2f98521.png)

**Comment by AmyYLee** [comment]
I'll review with @topotropic on this.

**Comment by sheikh-azharuddin** [comment]
Or else why not use grid layout... I see majority of the users are not happy with the new tab tray... The grid layout can accommodate more tabs in a single view. Here is the screenshot from edge.

![Screenshot_20200705-093247](https://user-images.githubusercontent.com/58127841/86525251-65b3fe00-be74-11ea-8e55-e51fabe837e9.jpg)

**Comment by cadeyrn** [comment]
@sheikh-azharuddin Your comment has nothing to do at all with this issue… 🤔

**Comment by pwd-github** [comment]
Before this topic is derailed, can I ask why it would be bad engineering wise to make the private tab interface purple now, but wasn't before?
