### ISSUE TITLE
FNX2-13693 ⁃ [webcontent] bottom of https://news.google.com truncated and URL bar stays visible

### ISSUE THREAD

**Issue by bjherbison** [mozilla-mobile/fenix#11963]
## Site with issue and any steps to reproduce
1) Visit https://news.google.com and scroll to the bottom.

This issue exists in 5.2 but didn't exist in 5.0

### Expected behavior
The bottom of the page is shown.

### Actual behavior
The link text "Read more stories from Health" is only partially visible.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No.

### Device information
* Android device: Android 10.
* Fenix version: 5.2
![Screenshot](https://user-images.githubusercontent.com/4101902/85759170-f9e8cd00-b6de-11ea-9541-eafae631111d.jpg)UNITO-UNDERSCORE!20200625-114434!

**Comment by bjherbison** [comment]
I just noticed something that should have been obvious: The URL bar is shown on the bottom of that image.

I have icons for Wikipedia and for Google News on my Fenix home screen ("top sites"). When I touch the Wikipedia icon and start scrolling down the URL bar goes away as scrolling starts. But when I touch the Google News icon and scroll the URL bar stays in place, which probably the cause of the truncation.

**Comment by Amejia481** [comment]
Related https://github.com/mozilla-mobile/android-components/issues/6933

**Comment by Amejia481** [comment]
cc @Mugurell

**Comment by Mugurell** [comment]
Than you for the detailed report!
This does indeed seem like an issue specific to Fenix, related to the dynamic behavior of the bottom toolbar.

I'm seeing though that on the latest Beta this is not reproducing for `news.google.com` anymore.
If QA can confirm I'd say we can close this.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly from **7/8** with **Google Pixel 4 XL (10).**
Note that the `Read more stories from Health` is correctly displayed.

**Comment by bjherbison** [comment]
To state the obvious, this problem hasn't reappeared.
