### ISSUE TITLE
FNX2-13692 ⁃ As a user I would like to be able to open a new tab from the tab tray overflow menu

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11961]
### What is the user problem or growth opportunity you want to see solved?
Users want a quick way to be able to open a new tab from the tab tray without going to the homescreen ~~> click toolbar~~ > search

### How do you know that this problem exists today? Why is this important?
Broken out of #11833

### Who will benefit from it?
Users who use the tabs tray and open new tabs frequently

**Comment by yoasif** [comment]
@ekager I'm not sure how this is different from using the FAB? Or is it literally the same result but using a different UI?

**Comment by ekager** [comment]
Right. I suppose having to click into the menu and then select the new tab option is still 2 clicks versus clicking the fab then clicking the toolbar. Not my suggestion just breaking it out of the list of suggestions in #11833.

**Comment by christophgrander** [comment]
The tab tray makes things so much more complicated. It feels like it duplicates the site that is shown when I open a new tab. Having to click on the (numer of tabs) button (dont know how to call it), then again on the plus button and a third time on the url bar just to open a new tab is way to complicated. (Also, I use private browsing mode a lot and it became more complicated to switch between private and non-private mode.)

**Comment by ekager** [comment]
You can long press the tab icon to open a new tab now also - #11569

**Comment by HollMax** [comment]
> You can long press the tab icon to open a new tab now also - #11569

Congratz to the UX team, we went from 2 clicks, to 3 clicks, and now we're at a long-press + 2 clicks! That's what I call real progress.

**Comment by yoasif** [comment]
> > You can long press the tab icon to open a new tab now also - #11569
> 
> Congratz to the UX team, we went from 2 clicks, to 3 clicks, and now we're at a long-press + 2 clicks! That's what I call real progress.

Do you think it helps to be rude to people? Please try to be less hostile - I would hate these issues to get closed as being too heated.

**Comment by ItsiAdam** [comment]
The new tab tray makes no sense. 
The old one fit fenix's design perfectly and was a delight to use. This is the main thing I don't understand, the new tray does not fit into the browser at all. It feels like it wasn't even meant to be included.
Also discussions regarding the change were extremely limited before it was added, with most discussions boiling down to "well other browsers do it, so we should too."

- Promoted the use of collections.
- Less clicks to get to the home screen, less clicks to open new tabs.
- Easier to manage tabs.
- Less finicky, the new tray is a pain in the ass to move to the top of without closing accidentally. Swiping to remove tabs also either doesn't work or has a massive delay.
- Able to pick which tab to resume browsing to, instead of being dropped into your last open page.
- Users didn't complain before the change.

The benefits of the old drawer are endless. Not to say that the new one doesn't have it's advantages too, just that the old one is fundamentally better in ways the new one could never be.

**Comment by ItsiAdam** [comment]
Oh and I think I should also point out how dumb it is that you have to click new tab to get to the HONE PAGE.

**Comment by Dunexus** [comment]
The main issue raised with the old one was that over time there was too many things on a single screen making each section hard to access (top sites, tabs and collections). This is why the idea of moving tabs to their own screen came out.

**Comment by ItsiAdam** [comment]
I'd hardly say that screen was cluttered, especially when you consider the fact that collections collapse out of the way and top sites has a limited size.

**Comment by AmyYLee** [comment]
@topotropic @brampitoyo for review

**Comment by ItsiAdam** [comment]
https://www.reddit.com/r/firefox/comments/hlfjmc/return_to_old_tab_layout_fenix

**Comment by brampitoyo** [comment]
On Firefox for iOS, we are A/B testing popping the keyboard up by default every time a new tab is opened.

This saves one tap (no need to tap the address bar – just open a new tab and you can start typing straight away), but also introduces another problem: the keyboard would cover up part of the New Tab Page.

In this scenario, what if you need to access everything else on the New Tab Page? You need to minimise the keyboard, of course. It’s not hard, but takes an extra button press – versus if the keyboard was never opened on the New Tab Page

So:

- Do we prioritise for quick search, at the expense of partially covering up part of the New Tab Page?
- Or, do we prioritise frequently used actions on the New Tab Page, at the expense of quick search?

I hope this helps us realise that this is an issue that we need to balance and tread carefully on, and that there’s not necessarily one right way to proceed. Instead, there are priorities, compromises and saying ‘no’ to stuff. The principle to remember is: we can’t prioritise everything, all the time, on every screen. When everything is equally important, then nothing is.

So, please keep your ideas coming. If you managed found a way through the Gordian knot, we would love to know!

Paging @topotropic for further comments.

**Comment by Oymate** [comment]
@brampitoyo where can I vote in this A/B test? Also I do prefer keyboard popping up as if I am opening new tab I am probably searching something.  :)

**Comment by ItsiAdam** [comment]
public confusion: https://www.reddit.com/r/firefox/comments/homkot/is_there_a_way_to_display_open_tabs_by_default/

**Comment by topotropic** [comment]
Thanks for the feedback everyone! And thanks Bram for the helpful background information. 

We're actively working on this. And, it looks like it's covered here as well: https://github.com/mozilla-mobile/fenix/issues/11513  I'll go ahead and close it. Thanks!
