### ISSUE TITLE
FNX-12981 ⁃ [Dev] Allow TC for external collaborators on PR

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#11975]
This was restricted in #4996 for bors but bors removed from fenix.
Please re-review this decision.
Already allowed in AC.

**Comment by ekager** [comment]
I know :( It's really annoying. 
See #9295 for more history on this.

**Comment by hakkikaancaliskan** [comment]
@ekager I just wanna ask you a question. Gradle not using latest mavenLocal on ac auto publication. I confirm there is new builds in .m2 folder but Android Studio not using them, so I fixed this problem via adding mavenLocal() to build.gradle -> repositories.
Could you confirm this is known or just for me?
