### ISSUE TITLE
[Bug] Swipe Up on Instagram Stories doesn't work

### ISSUE THREAD

**Issue by yaomtc** [mozilla-mobile/fenix#11976]
## Steps to reproduce
View an Instagram Story with an associated link, such as:

https://www.instagram.com/stories/cassandracalin/2339424311838745456/

### Expected behavior
Swiping up on the story would activate "see more" and open the associated link in a new tab.

### Actual behavior
A blank tab is opened (about:blank)

### Device information
* Android device: Moto X4, Android 10 (LineageOS 17.1)
* Fenix version: 5.2.0

**Comment by ekager** [comment]
@yaomtc are you still experiencing this issue?

**Comment by yaomtc** [comment]
I actually just noticed this working just the other day, but forgot I had filed this bug. Thanks for reminding me.
