### ISSUE TITLE
FNX-33 ⁃ When search bar scrolled to top it should match the size of the search bar in search mode

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1197]
## Steps to reproduce
1. From the home screen, scroll through your sessions so that the search bar moves to the top of the screen.
1. Tap into the search bar to activate search mode.

### Expected behavior
The size of the search bar on the home screen should match the size of the search bar in search mode.

### Actual behavior
The search bar is not as tall in search mode.

### Device information
* Android device: Nokia 3.1 
* Fenix version: 1.0.1913 

### Priority
I don't think this is a blocker but we should still include it in the MVP.

**Comment by AmyYLee** [comment]
Scrollbar in search mode should be the same style/size as the search bar when it’s stickied to the top (see top of screenshot)
![Screenshot_20190417-175505](https://user-images.githubusercontent.com/5992746/56324416-c7d3f680-613c-11e9-94dc-f867be7f22df.png)

**Comment by mcarare** [comment]
@AmyYLee Should we increase the size of the toolbar in search mode? It was limited to 40dp according to https://github.com/mozilla-mobile/fenix/issues/2210. TY!

**Comment by mcarare** [comment]
@Verdi With the new home screen this issue does not exist anymore. Can we close this?

**Comment by Verdi** [comment]
Works for me!
