### ISSUE TITLE
Tabs Tray: Move FAB from Tabs Tray to the Home Screen

### ISSUE THREAD

**Issue by WKSuperPower** [mozilla-mobile/fenix#11984]
### What is the user problem or growth opportunity you want to see solved?
Add FAB onto Fenix's Home screen like Firefox Focus so users can easily open a new tab.

### How do you know that this problem exists today? Why is this important?
The FAB is currently inside the Tabs Tray screen.

### Who will benefit from it?
Everyone!

The tabs tray will be more clean/clear without the FAB.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2662)

**Comment by Dunexus** [comment]
When you are on tabs tray, you want an easy way to open a new tab and currently FAB provides this.

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
