### ISSUE TITLE
NoSuchElementExceptionkotlin.collections.ArraysKt in first fatal List is empty

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#11985]
Crash seen on Sentry for Fenix Nightly, has grown in the past two days with hundreds of events.

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8870448/?query=is%3Aunresolved

May be related to changes from #9935? or similar to #11906

**Comment by mcarare** [comment]
I think this is caused by the use of `engines.list.first()` as a fallback value in `getDefaultEngine`. cc @boek 

```
/**
 * Returns first element.
 * @throws [NoSuchElementException] if the list is empty.
 */
public fun <T> List<T>.first(): T {
    if (isEmpty())
        throw NoSuchElementException("List is empty.")
    return this[0]
}
```

**Comment by Augures01** [comment]
> 
> 
> I think this is caused by the use of `engines.list.first()` as a fallback value in `getDefaultEngine`. cc @boek
> 
> ```
> /**
>  * Returns first element.
>  * @throws [NoSuchElementException] if the list is empty.
>  */
> public fun <T> List<T>.first(): T {
>     if (isEmpty())
>         throw NoSuchElementException("List is empty.")
>     return this[0]
> }
> ```

Steps to reproduce
1. Add custom search, like DuckDuckGo (https://duckduckgo.com/?q=%s) (I'm on russian locale, so there's no DDG in default engines)
2. Delete all other default search engines
3. Restart browser and see crash

**Comment by kglazko** [comment]
I made this PR to attempt to address the crash but it certainly doesn't address the cause of the null condition https://github.com/mozilla-mobile/android-components/pull/7531

**Comment by hakkikaancaliskan** [comment]
> 
> 
> > I think this is caused by the use of `engines.list.first()` as a fallback value in `getDefaultEngine`. cc @boek
> > ```
> > /**
> >  * Returns first element.
> >  * @throws [NoSuchElementException] if the list is empty.
> >  */
> > public fun <T> List<T>.first(): T {
> >     if (isEmpty())
> >         throw NoSuchElementException("List is empty.")
> >     return this[0]
> > }
> > ```
> 
> Steps to reproduce
> 
>     1. Add custom search, like DuckDuckGo (https://duckduckgo.com/?q=%s) (I'm on russian locale, so there's no DDG in default engines)
> 
>     2. Delete all other default search engines
> 
>     3. Restart browser and see crash
> 
> 
> To avoid crash, leave at least one default search engine in list

I leave google as default but I have that crash too. Also no way to open app again, always crashing. Last thing i did with nightly is open a custom tab via gmail.

**Comment by Augures01** [comment]
Can't reproduce on Nightly 200714 06:01. Maybe fixed.

**Comment by liuche** [comment]
We believe it's been handled by #12544 , please reopen if you see it again after 7/17 Nightly.
