### ISSUE TITLE
[Bug] Error when switching between browser and in-app browser

### ISSUE THREAD

**Issue by J41319** [mozilla-mobile/fenix#11980]
## Steps to reproduce
When opening a link through the application like Telegram, the link is opened In-App Browser, after that I place it to open the link through the browser, and if I switch between Telegram and the browser, Firefox crashes. Telegram is just a demonstration, I don't know if the problem has already been reported.

### Expected behavior
Switching between the browser and the in-app browser should go smoothly.

### Actual behavior
Error when switching between browser and in-app browser

### Device information
* Android device: Xiaomi Mi A3 - Android 10
* Fenix version: 5.2.0

LOG: [2020-06-25-20-28-34.txt](https://github.com/mozilla-mobile/fenix/files/4834369/2020-06-25-20-28-34.txt)

Video: [1.zip](https://github.com/mozilla-mobile/fenix/files/4834372/1.zip)

**Comment by ekager** [comment]
@J41319 are you still experiencing this issue?

**Comment by J41319** [comment]
> 
> 
> @J41319 are you still experiencing this issue?

I don't have that problem anymore.

**Comment by ekager** [comment]
Great, thanks! Closing
