### ISSUE TITLE
additional functions on long pressing tab switcher button.

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#11983]
it wold be very useful if long pressing the tab switcher button besides new tab and close tab already present will integrate close other tabs and switch between two last used tabs (similar to this add on https://addons.mozilla.org/it/android/addon/most-recent-tab/?src=search, which I m using on old Firefox and I cannot really switch to fenix until it gets supported or native integrated it)
please consider it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2661)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812922

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
