### ISSUE TITLE
FNX2-13704 ⁃ [Bug] Firefox reports as a seperate incorrect device to Google My Account

### ISSUE THREAD

**Issue by adithya-s-sekhar** [mozilla-mobile/fenix#11986]
## Steps to reproduce
Visit https://myaccount.google.com/device-activity to see list of signed in devices.

### Expected behavior
It should show my phone's real name like Chrome does

### Actual behavior
It shows the phone as "Android Device" where it shows signed in on Firefox Mobile.

![Screenshot](https://user-images.githubusercontent.com/60822601/85818172-81762080-b75f-11ea-80ce-cb2a25081048.jpg)UNITO-UNDERSCORE!2020-06-26-09-12-11-198!UNITO-UNDERSCORE!org mozilla fenix nightly!

Expanding Android Phone (shown as "this device" in firefox)

![Screenshot](https://user-images.githubusercontent.com/60822601/85818280-cbf79d00-b75f-11ea-9253-16fd2463c1e5.jpg)UNITO-UNDERSCORE!2020-06-26-09-16-49-588!UNITO-UNDERSCORE!org mozilla fenix nightly!

Expanding Xiaomi Redmi Note 5 (Actual device signed in with chrome)

![Screenshot](https://user-images.githubusercontent.com/60822601/85818316-e16cc700-b75f-11ea-92b7-164c15922661.jpg)UNITO-UNDERSCORE!2020-06-26-09-16-42-161!UNITO-UNDERSCORE!org mozilla fenix nightly!

### Device information
* Android device: Xiaomi Redmi Note 5
* Fenix version: Nightly 200625 06:00 (Build #21770610)
AC: 48.0.20200624130112, 87fe54958
GV: 79.0a1-20200623034439
AS: 61.0.2

**Comment by danielzgtg** [comment]
[Chrome does this with proprietary code](https://stackoverflow.com/a/35066451). Nobody other than Google can implement this.

**Comment by adithya-s-sekhar** [comment]
@danielzgtg So this is on Google's side, should I close this issue now?

**Comment by kbrosnan** [comment]
This is not a Fenix issue. Gecko based browsers do not report your device's model number to websites so I doubt Google can do anything better here.
