### ISSUE TITLE
FNX2-13042 ⁃ [Bug] Links in add-ons details page should open in  Fenix.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#11996]
Currently all links in an add-on detail text field and the link to add-on homepage do not open by default in Fenix. Clicking on them opens the Android chooser dialog.

IMO there should be no reason to navigate away from Fenix.

**Comment by brampitoyo** [comment]
@mcarare Agreed. All those links should open in a Fenix browser tab, and shouldn’t invoke the app chooser dialog.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Fenix Nightly Build 200713 from 7/13`** using a Google Pixel 3a (Android 10)

► Video
![20200713-134935](https://user-images.githubusercontent.com/51314259/87297850-c77a0500-c511-11ea-9385-73bbd8c76bd9.gif)
