### ISSUE TITLE
[Bug] Saved logins not available in private browsing

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#11992]
## Steps to reproduce
Open a login page in a private tab.

### Expected behavior
The saved username/password should be auto-filled, or available to select when clicking on the input field.

### Actual behavior
The username and password fields are empty, and nothing pops up when clicking on them.

### Device information
* Android device: Huawei Nova 6
* Fenix version: Nightly 200626 06:01 (Build #21780613)
AC: 48.0.20200625130125, d51b5b208
GV: 79.0a1-20200624093107
AS: 61.0.6

**Comment by ekager** [comment]
This should be resolved with the new login select prompt. In Private Browsing you should be able to select from your logins that match the site.

**Comment by sflorean** [comment]
Tested on Nightly 9/16 and indeed the password and username are auto-filled with the new login select prompt.
