### ISSUE TITLE
FNX-13001 ⁃ [Bug] 0 tabs counter after the migration from Fennec to Fenix

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#11991]
## Steps to reproduce
1. Open a few tabs in Fennec Beta.
1. Install the migration build.
1. Check the tabs counter after the migration, when you are still on the Fenix onboarding screen
    1. Expected behavior
The correct number of tabs is shown.
    1. Actual behavior
The counter shows 0 tabs.
The number of tabs is shown after you dismiss the onboarding screen.
    1. Device information

* Android device: ?Huawei P20 lite (Android 9)
* Fenix version: Beta 78.0.0

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration 78.0.1-beta.1 GV 78 from 6/27 with Motorola Moto G6 (Android 8).

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta Migration 79.0.0-beta.1 GV 79 from 6/30 with Motorola Moto G6 (Android 8), Huawei P20 lite (Android 9).
I will remove the qa:needed label. Thanks!
