### ISSUE TITLE
FNX2-13037 ⁃ [Design] Follow ux mock on Settings --> Search screen

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12007]
Breakdown from issue #7065
![resim](https://user-images.githubusercontent.com/17825767/85984332-b8636500-b9f1-11ea-8cd6-b76f73e51bce.png)

**Comment by hakkikaancaliskan** [comment]
I'm working on this

**Comment by hakkikaancaliskan** [comment]
Looks like add search engine radio groups using wrap content for height.
![resim](https://user-images.githubusercontent.com/17825767/86454685-490aaf80-bd28-11ea-8bc9-7f1b8ab3ff26.png)

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build **7/7** with **Google Pixel 4 XL (10).**
![Screenshot_20200707-173522](https://user-images.githubusercontent.com/42831109/86802055-4fc55980-c07d-11ea-9a05-85bd8c687b99.png)
![Screenshot_20200707-173527](https://user-images.githubusercontent.com/42831109/86802062-505df000-c07d-11ea-80cc-85e91f39b7ce.png)
