### ISSUE TITLE
Close all tabs apart from the selected one and up or down from it

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12001]
Right now I have only one option to manage tabs which is to close all of them or keep all them and close each one one by one. It'd be great if I can close all the tabs apart from the one I have selected and top/down from the selected one.

And in conjunction with the issue #2487 to rearrange tabs it'll become a lot more easier to handle/manage tabs.

Edit: To be more clear it's something like you already find on the desktop Firefox; "Close other tabs, Close tabs to the right, Close tabs to the left (I know this one is not available in desktop).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2695)

**Comment by sheikh-azharuddin** [comment]
I would suggest one more thing tab pinning concept...
If the tab is pinned and user clicks close all tabs it will close all except the one pinned.

Instead of close button in each tab mozilla can add a 3 dot menu on each tab with below options

Close tab
Save to collection
Add to top site
Pin tab

What do you say?

![7063](https://user-images.githubusercontent.com/58127841/85878125-c170ee00-b7c7-11ea-9c35-c920b5b3e1a5.png)

**Comment by SS1113** [comment]
Yeah, it's a good idea! You need to open a new issue for this. And could be really useful if implemented correctly. 

But one thing bothers me. If we remove the current close button (X icon) how can users close the tan apart from swiping on it?

**Comment by sheikh-azharuddin** [comment]
@SS1113  Swipe gesture is already there for close....like I said we can also add the close tab optoon in a 3 dot menu.... however most user like us prefers swipe option only... Close button is redundant which can be utilised for 3 dot menu which will save clicks for adding to top site/collection. Also tab pinning can be implemented

Apart from that we can add a long press on tab to close....

**Comment by SS1113** [comment]
Do you think we should open a new issue for this?

**Comment by sheikh-azharuddin** [comment]
@SS1113 I have opened a new case  #12012 as you requested...😊

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812921

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
