### ISSUE TITLE
FNX2-13039 ⁃ [Bug] Crash @kotlin.KotlinNullPointerException: at mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated(FxaAccountManager.kt:36)

### ISSUE THREAD

**Issue by bobintetley** [mozilla-mobile/fenix#12000]
When I sign in to firefox and go through the pairing procedure, everything appears to work. I'm shown the success message on both phone and desktop browser. Once approval is given on both devices, approx 2 seconds later the app crashes. There is nothing in the logs via logcat. Let me know if there's any other debug information I can get to assist.

### Device information
* Android device: OnePlus 5T
* Fenix version: 77.0.0-beta.2 Build #2015744451 42.0.1 5bf46033e GV: 77.0-20200526221856 AS: 0.58.2 Friday 6/5 @ 8:21 AM

**Comment by ekager** [comment]
Hi @bobintetley ! When you go to about:crashes is there anything to report from there?

**Comment by bobintetley** [comment]
https://crash-stats.mozilla.org/report/index/1e31730a-cefd-4afb-9fab-d35280200626

**Comment by ekager** [comment]
Thanks!

**Comment by kbrosnan** [comment]
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=kotlin.KotlinNullPointerException%3A%20at%20mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated%28FxaAccountManager.kt%3A36%29

I'm not seeing this signature at all when searching Sentry for `FxaAccountManager.postAuthenticated`. I checked all the active Fenix projects.

**Comment by grigoryk** [comment]
This is in a-c, not a-s.

The obvious thing that can NPE in that stacktrace (unfortunately line numbers are wrong) is `fxaDeviceId = account.getCurrentDeviceId()!!`.

Filed https://github.com/mozilla-mobile/android-components/issues/7536 to track this.
