### ISSUE TITLE
FNX-13013 ⁃ Fennec migration: Tab preview is not displayed on the migrated open tabs

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12002]
## Preconditions:
Have open tabs on Fennec.

## Steps to reproduce
1. Replace Fennec with Fenix;
1. Launch Fenix and tap "Start browsing";
1. Tap the tab counter to open the tabs tray;
1. Observe the tabs preview for the migrated open tabs.
    1. Expected behavior
The tab preview is displayed for the migrated open tabs.
    1. Actual behavior
The tab preview is blank for the migrated opened tabs.
    1. Notes:
After accessing the opened tabs, the tab preview is displayed for the majority of the websites. Some of them remain blank.
![20200626](https://user-images.githubusercontent.com/48799384/85854973-1a3b8900-b7be-11ea-9a82-9c8a465aa338.gif)UNITO-UNDERSCORE!145653!

### Device information
* Android device: Motorola Moto G6 (Android 8), Huawei MediaPad M3 lite (Android 7), Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: Beta Migration 78.0.0-beta.1 from 6/26

**Comment by st3fan** [comment]
This was originally filed in A-C as a migration issue, but I've moved it to Fenix for the following reason:

 - We don't migrate tab previews. We could, but that is a major piece of work and I think we are beyond adding such functionality to the migration code.

 - I think that is really missing here is an empty state for tab previews. I think even not taking the migration into account, there is a possibility that a tab won't have a preview, so we need to find out a good design for this empty state.

**Comment by jonalmeida** [comment]
@AmyYLee should we go with a default background when we have no tabs from migration or we could try using a favicon as a placeholder. We had done this earlier in the tabs tray development as a placeholder before thumbnails landed in Fenix.

**Comment by jonalmeida** [comment]
Amy and I spoke offline:
 - We're going to try using the favicon again.
 - For the dark theme, we should use the background `#32313C`.

**Comment by jonalmeida** [comment]
We settled on using a default background instead of showing a favicon since it's visually slow have the icons generated as you scroll through.

**Comment by jonalmeida** [comment]
For QA, this is what the placeholder icons now look like when we do not have thumbnails:

<img width="883" alt="3" src="https://user-images.githubusercontent.com/1370580/85907872-02c1c780-b7e1-11ea-940f-09eeb82e2547.png">

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta Migration 79.0.0-beta.1 GV 79 from 6/30 with Motorola Moto G6 (Android 8), Pixel 2 (Android 9).
I will remove the qa:needed label. Thanks!
