### ISSUE TITLE
New tab + visit website UX

### ISSUE THREAD

**Issue by ro-savage** [mozilla-mobile/fenix#12008]
## User Story
* As a user, I want to easily be able to visited a new website.

Currently I must

* tap open tabs (very top of phone)
* tap new tab (very bottom of phone)
* tap address bar (very top of phone)
* tap keyboard (very bottom of phone)
* tap suggestion (middle of phone)

This makes one handed use, or just any intuitive use more difficult.

Keeping all the UI for this very common action grouped as much as possible would help a lot.

Example 1

* tap open tabs (very top of phone)
* tap new tab, available as always the top on the tab list (top of phone)
* auto select address bar (without suggestions) keeping the collections/recommendations in the middle
* tap keyboard (very bottom of phone)
* tap suggestion (middle of phone)

This goes from 5 taps to 4 taps. And means I can do actions as top of phone, the bottom of phone. Instead of moving between the extremes with every action.

Example 2

* `+` tab icon, along side tabs icon
* auto select address bar
* tap keyboard
* tap suggestion

From 4 taps, to 3 taps.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2703)

**Comment by person808** [comment]
Thank you for the feedback! One thing that would reduce the distance you need to move your finger for your use case is to long press on the tab counter. There's a menu that lets you open a new tab.

**Comment by ro-savage** [comment]
I noticed that after playing with it. However it is both hidden, and takes a long press followed by a click. Which ends up taking a longer (but less jumping up and down the screen)

Here is a separate post by people on similar issues r/firefox: https://www.reddit.com/r/firefox/comments/hg3izf/firefox_preview_tab_changes_in_last_update/

**Comment by were491** [comment]
I would like if the address bar was shown directly above the keyboard when searching, like when viewing web pages normally.

**How it looks when viewing web pages normally:**
![Screenshot_2020-07-26-17-21-12](https://user-images.githubusercontent.com/34976611/88491023-3cfbc180-cf65-11ea-972f-ada90d97be7b.png)

**How the searching UI currently looks**
![Screenshot_2020-07-26-17-16-44](https://user-images.githubusercontent.com/34976611/88491038-5d2b8080-cf65-11ea-81a3-5b6443da6eb7.png)

**(roughly) How I think the searching UI should look.**
![u4tjC2](https://user-images.githubusercontent.com/34976611/88491045-6f0d2380-cf65-11ea-8d51-610553eea1ee.jpg)

The mockup isn't great, but I hope it gets the idea across.

**Comment by boek** [comment]
This is fixed.
