### ISSUE TITLE
[UI Sync Integration Tests] Sync is not working in UI Tests (using Stage server)

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#12018]
These tests are failing because the sync is not complete on Fenix side. 
There have been similar issues in the past:
https://github.com/mozilla-mobile/fenix/issues/4023#issuecomment-517364646
https://github.com/mozilla-mobile/fenix/issues/4610

And now we are facing same behaviour. The login successes but the sync does not seem to finish since Fenix stays on this screen: 
![](https://user-images.githubusercontent.com/1897507/85884097-58e33a80-b7e2-11ea-8fc0-7fd5c4df5dbe.png)

while it should go back to Settings, no need to dismiss the Save Login prompt. 

@csadilek are you aware of recent changes on Fenix side so that stage sync could have stopped working?
Thank you in advance!!

**Comment by rfk** [comment]
It's possible that this may be fixed by the same change that was made to fix the iOS issue, ref https://github.com/mozilla/application-services/pull/3284. Updating android-components to use application-services v61.0.7 should pull in this patch.

If you're able to share any `adb logcat` output from during the failed login, that would also be helpful.

Is this using the same test account as the iOS tests? I can try to reproduce locally later today.

**Comment by isabelrios** [comment]
Thanks @rfk! good news for iOS, that patch fixed the issue on iOS side, the account appears and it synchronizes correctly (now there is a different one I just opened for [tps/sync](https://bugzilla.mozilla.org/show_bug.cgi?id=1649500)

I was trying to change the a-s version for fenix so that I could try to test same patch, but I could not figure that out yet. 
In case you have time in the meantime, you could use this stage account: email='pytest-3f9b6d3cc2@restmail.net', password=‘qfTcMcii' to reproduce the issue
It has a bookmark saved: mozilla.org

Also while running the tests with the current issue, I got this adb logcat logs, in case that's helpful. 
[FenixLogs2.txt](https://github.com/mozilla-mobile/fenix/files/4853392/FenixLogs2.txt)

**Comment by rfk** [comment]
> Also while running the tests with the current issue, I got this adb logcat logs, in case that's helpful.

Thanks! I see a few instances of this in the log:
```
FirefoxAccountStateMachine: Got invalid event Init for state NotAuthenticated
```

Not sure what to make of it yet but maybe it's a clue.

**Comment by rfk** [comment]
What I do *not* see in the adb log, is any attempt to complete the OAuth flow. Which maybe means the webchannel messages are not coming through correctly, similar to the other issues linked above.

**Comment by csadilek** [comment]
> What I do not see in the adb log, is any attempt to complete the OAuth flow. Which maybe means the webchannel messages are not coming through correctly, similar to the other issues linked above.

@rfk Ah yes, this integration test isn't using the webchannel. It was implemented before we had a fix to support the webchannel/web extension for staging.

@isabelrios We can now change the `FxaServer` config class override we have in the test folder: https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/components/FxaServer.kt

to just

```
object FxaServer {
    private const val CLIENT_ID = "a2270f727f45f648"
    const val REDIRECT_URL = "urn:ietf:wg:oauth:2.0:oob:oauth-redirect-webchannel"

    @Suppress("UNUSED_PARAMETER")
    fun config(context: Context): ServerConfig {
        return ServerConfig(Server.STAGE, CLIENT_ID, REDIRECT_URL)
    }
}
```

This will make sure the web channel is used when running the test. Alternatively, we can remove this class override altogether and configure the server override via settings in the test: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/FxaServer.kt#L20

@isabelrios can you give this a try? It should get the tests to pass again. Let me know if you need any help.

As a side note, it would be great to run this test in automation/CI in the future, so we notice right away when we break it :).

**Comment by isabelrios** [comment]
Thank so much @csadilek! Yeah, that fixes the tests! I will create a PR to change that part and have the tests back to green \o/

> As a side note, it would be great to run this test in automation/CI in the future, so we notice right away when we break it :).

Actually, they are (and have been) running in CI per push in master for long time but I didn't add the check to github yet. 
The[ jobs are here](http://mobileqa2.corp.mtv2.mozilla.com:8080/job/fenix-git/job/master/) (you need VPN) and there is a [slack channel](#firefox-ios-alerts) that report the status. But it is not shared broadly. There are too many parts involved when running these tests and for sometime it has been difficult to keep the tests green. This issue was kind of covered by failures in the sync process that's why it took me longer to realize I could not check exactly when this was broken on fenix side :(
