### ISSUE TITLE
FNX2-13033 ⁃ [Design] Follow ux mock on Settings --> Data Collection

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12016]
Breakdown from issue #7065 
![resim](https://user-images.githubusercontent.com/17825767/85881660-a8c40080-b7e6-11ea-9e8c-4fa68db16507.png)

**Comment by hakkikaancaliskan** [comment]
I'm working on this.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build **7/7** with **Google Pixel 4 XL (10).**
![Screenshot_20200707-164228](https://user-images.githubusercontent.com/42831109/86801936-33292180-c07d-11ea-8d20-e46eca4877c0.png)
