### ISSUE TITLE
FNX2-13035 ⁃ [Design] Follow ux mock on Settings --> ETP --> Info screen

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12010]
Breakdown from issue #7065

![resim](https://user-images.githubusercontent.com/17825767/85874564-7f51a780-b7db-11ea-918d-015232da2974.png)

**Comment by hakkikaancaliskan** [comment]
I'm working on this.

**Comment by person808** [comment]
@hakkikaancaliskan After fixes land we usually add the `eng:qa:needed` so qa can verify the changes :)

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 7/13** with **Google Pixel 4 XL (11).**
