### ISSUE TITLE
Support various actions (add to top sites, bookmarks,...) on open tabs

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12012]
### What is the user problem or growth opportunity you want to see solved?
Currently if a user wants to add a site to collection, top site, bookmarks,... or wants to share it he/she has to click many times to do the task. 

### How do you know that this problem exists today? Why is this important?
At the moment Firefox supports adding an open tab to a collection and for all the other actions you need to take multiple steps.

### Who will benefit from it?
People with a lot of open tabs who quickly want to organize them by saving or sharing.

### Possible explorations
* as part of multi-select
* on long press

**Comment by amkcpu** [comment]
One problem I see is that a lot of visual clutter gets added to the tabs tray when this functionality could alternatively be achieved by long-pressing a tab. I prefer to keep things simple (at least visually) and show more of a tabs content (see for example ) rather than put a menu on every single tab.
Especially considering that a) long-pressing a tab to pop up a context menu also works and b) Fennec did not have this.

**Comment by sheikh-azharuddin** [comment]
Fennec had a different tab management style....also it doesn't has collection feature....both are completely different..not right to compare..
Regarding the 3 dot menu...if the long press will popup a menu what's wrong with 3 dot menu...instead of that cross it will show a 3 dot....anyway long press idea is also good

**Comment by AmyYLee** [comment]
@topotropic for feedback.

**Comment by topotropic** [comment]
Thanks for the feedback. This is very valid feedback but I disagree with the proposed solution of adding a three dot menu to every open tab. We're currently exploring ways to better [multi-select open tabs](https://github.com/mozilla-mobile/fenix/issues/10163) and are considering adding more actions (atm you can just add selected open tabs to a collection). That said, the long press idea also seems promising. I'll go ahead and update comment 0 to reflect what I wrote here. Thanks again!

**Comment by topotropic** [comment]
This is in progress https://github.com/mozilla-mobile/fenix/issues/16132 (PR: https://github.com/mozilla-mobile/fenix/pull/16236). I'll close this issue but please feel free to re-open or open a new issue for additional feedback. Thanks!
