### ISSUE TITLE
FNX-13041 ⁃ Set Search shortcuts off by default

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#12025]
This is only for new users, and shouldn't override settings for users who have made a choice about this setting (similar to the other default settings).

### Acceptance Criteria
* [ ] Search screen has "Shortcuts" toggled off by default (for new users)
* [ ] Address bar > Show search shortcuts is off by default

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 6/29, and on Beta 6.0.0-beta.1, that:
* search screen has "Shortcuts" toggled off by default (for new users),
* address bar -> Show search shortcuts is off by default.

Devices: 
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Samsung Galaxy Tab S6 (Android 9),
* Google Pixel (Android 10), and
* Sony Xperia Z5 Premium (Android 7.1.1).
