### ISSUE TITLE
FNX-13040 ⁃ Update default top sites (for new users)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#12026]
We currently populate default top sites on first run for users with:
Pocket, Wikipedia, Youtube

Let's change that list to:
Google, Pocket, Wikipedia

### Acceptance Criteria
* [ ] New users will have the default top sites: Google, Pocket, Wikipedia
* [ ] Existing users don't see any changes

**Comment by softvision-miralobontiu** [comment]
Verified as fixed: the default top sites on the first run for users are: Google, Pocket, Wikipedia, on both the latest Nightly build from 6/29 and on Beta 6.0.0-beta.1

Devices:
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Samsung Galaxy Tab S6 (Android 9),
* Google Pixel (Android 10),
* Google Pixel 2 (Android 9),
* Google Pixel 3 (Android 11), and
* Sony Xperia Z5 Premium (Android 7.1.1).
