### ISSUE TITLE
FNX-13055 ⁃ [Bug] address bar keeps disappearing on scroll down

### ISSUE THREAD

**Issue by thecodingdude** [mozilla-mobile/fenix#12038]
## Steps to reproduce
1: visit a site like old.reddit.com
2: scroll up and down
3: notice the address bar keeps disappearing when you scroll down 

### Expected behavior
1: address bar doesn't disappear

### Device information
* Fenix version: 5.2

Please implement an option to disable this, it ruins the ability for me to use the web; having the UI constantly show/hide when scrolling is really jarring. Imagine every time you scroll down on Firefox desktop and the UI hides itself, that'd be horrible as this is.

I can say the address bar isn't disappearing when using this website in private mode, so I have no idea what triggers the address bar to disappear

**Comment by cadeyrn** [comment]
> address bar doesn't disappear

It _is_ the expected behaviour. If you want an option to disable this behaviour then your issue is a duplicate of #10240.

**Comment by kbrosnan** [comment]
Closing as a duplicate
