### ISSUE TITLE
FNX-13051 ⁃ [Bug] Clicking an Uber Eats app link from email stalls forever on Fenix

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#12035]
Video from user

https://drive.google.com/file/d/1d77w0XjCQSATG_Ss_wVWbwzRDtISgvB8/view?usp=sharing

## Steps to reproduce
Have Fenix set as default browser
From email, click on link (uber eats link in example)

### Expected behavior
(in chrome, after unsetting Fenix as default browser) Uber Eats app opens up

### Actual behavior
Fenix opens up, and stalls forever, does not load anything or open up app

### Device information
* Android device: ?
* Fenix version: ?

**Comment by liuche** [comment]
Dupe of #10838

**Comment by rocketsroger** [comment]
Fenix nightly with A-C "48.0.20200628130058" this should be fixed
