### ISSUE TITLE
FNX-4869 ⁃ Secure Connection Indicator

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1203]
[meta] Site Controls #227

For MVP: As a user, I want to know whether the site I am on has a secure connection. 

Acceptance Criteria
If I am on a site with a secure connection,  can see a green padlock icon in the address bar, and when I tap on it I see an expanded panel with the icon and a secure connection label. 

If I am on a site with an insecure connection,  I do not see a padlock icon in the address bar, and when I tap on the site information icon I see an expanded panel with a red padlock icon and an insecure connection label. 

See ux issue #191

**Comment by bsurd** [comment]
A padlock is shown for secure connections and a globe icon for insecure ones, when tapping on the icons a panel is being displayed with more information as well as any permissions that have been allowed/blocked on the site.
