### ISSUE TITLE
[Bug] Japanese characters are fallbacked to serif font's glyphs

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla-mobile/fenix#12045]
## Steps to reproduce
1. Change the language to Japanese
1. Load a website written in Japanese

For example: "これが日本語です。"

### Expected behavior
Should be fallback to sans-serif font from default sans-serif font.

(FYI: Japanese serif glyph may not be easier to read if the glyph is too thin.)

### Actual behavior
Western characters are displayed with default sans-serif font, and Japanese characters which are not in the default font should also be displayed with another sans-serif font.

### Device information
* Android device: Galaxy Tab S5e, patch level: 1, June
* Fenix version: Nightly 200625 06:00 (Build #21770610) AC: 48.0.20200624130112, 87fe54958 GV: 79.0a1-20200623034439 AS: 61.0.2

I updated the OS yesterday, so this might be caused by some system settings changes.

![Screenshot](https://user-images.githubusercontent.com/8064604/85910409-90d99480-b859-11ea-866c-5bc9982c2709.jpg)UNITO-UNDERSCORE!20200627-093526!UNITO-UNDERSCORE!Firefox Nightly!

**Comment by masayuki-nakano** [comment]
FYI: UI's Japanese characters are displayed correctly. This is a bug in web contents.

**Comment by masayuki-nakano** [comment]
I don't reproduce this on Pixel 3a, hmm.

**Comment by masayuki-nakano** [comment]
I additionally tested this with changing various settings in `about:config`. However, I couldn't find any workaround for this.

Even if I chang CJK font fallback order to prefering "ja", Chinese font is used to render some Japanese websites. Even on websites which are rendered with Japanese fonts, without author's CSS `font-family`, serif fonts are used as I've already reported.

It seems that:
* GV does not refer font prefs in `about:config`.
* GV does not refer language settings of Android OS.
* GV does not refer language settings of Firefox for Android.
* GV considers some Japanese websites are Western or Chinese.

**Comment by makotokato** [comment]
When I discuss with @masayuki-nakano today, I found that their font configuration (fonts.xml) doesn't have `Noto Sasn CJK`. It is `SECCJK-Regular.ttc` for CJ fonts. Korean font is `Samsung Korean`.

**Comment by makotokato** [comment]
This will be fixed when `SEC CJK JP` is added in `font.name-list.sans-serif.ja` via `about:config`.

**Comment by makotokato** [comment]
Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1673155

**Comment by masayuki-nakano** [comment]
> This will be fixed when `SEC CJK JP` is added in `font.name-list.sans-serif.ja` via `about:config`.

Yeah, it works. Thank you. On the other hand, I wonder, why the font does not appear in the fallback font list even though gfxFT2Fonts lists up all fonts with the new API on Android 10 or later...

**Comment by makotokato** [comment]
> Yeah, it works. Thank you. On the other hand, I wonder, why the font does not appear in the fallback font list even though gfxFT2Fonts lists up all fonts with the new API on Android 10 or later...

That is Samsung bugs since Android font API uses system configuration (`/etc/fonts.xml` and `/product/etc/fonts_customization.xml` on Android 10+ AOSP. So some Java applications and Native applications that use Font API won't enumerate fonts well.

Also, Skia won't check `/product/etc/fonts_customization.xml`... It may be Skia bug. (Most devices doesn't use `fonts_customization.xml` and I don't see that there is `fonts_customization.xml` in device.

**Comment by masayuki-nakano** [comment]
> > Yeah, it works. Thank you. On the other hand, I wonder, why the font does not appear in the fallback font list even though gfxFT2Fonts lists up all fonts with the new API on Android 10 or later...
> 
> That is Samsung bugs since Android font API uses system configuration (`/etc/fonts.xml` and `/product/etc/fonts_customization.xml` on Android 10+ AOSP. So some Java applications and Native applications that use Font API won't enumerate fonts well.
> 
> Also, Skia won't check `/product/etc/fonts_customization.xml`... It may be Skia bug. (Most devices doesn't use `fonts_customization.xml` and I don't see that there is `fonts_customization.xml` in device.

Thank you. Then, I'll report this to Samsung.

**Comment by masayuki-nakano** [comment]
Verified the fix inthe latest build.
