### ISSUE TITLE
FNX-4870 ⁃ Horizontal line under the search header doesn't span the full screen width

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1204]
## Steps to reproduce
1. Scroll sessions so that the search bar moves to the top of the screen and the sessions go under that search section.

### Expected behavior
Needs a design. @shorlander said it's an issue.

### Actual behavior
The horizontal line that separates search and sessions sits at the bottom of the search header but it doesn't span the full screen width. This looks unresolved.

### Device information
* Android device: Nokia 3.1
* Fenix version: 1.0.1913

### Priority
I don't think this is a blocker but we should still include it in the MVP.

**Comment by topotropic** [comment]
@Verdi can you double-check, I think that one's fixed. Thanks!

**Comment by Verdi** [comment]
Looks good to me!
