### ISSUE TITLE
[BUG] Doesn't triggers Torrent app when clicked on magnet link

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#12056]
Steps to reproduce: Click on any magnet link, and it does nothing.

Expected Behaviour: When clicked on magnet link it should display supported app list for adding torrent.

Fenix : Nightly 200627 06:01 (Build #2015748659)
AC: 48.0.20200626213814, 55bca70c8
GV: 79.0a1-20200626094540
AS: 61.0.6

Device : Xiaomi Redmi Note 4 Android 7.0, MIUI 11

**Comment by pidus** [comment]
Unable to reproduce. It works on my device fine with Firefox Beta and IDM+.

**Comment by RealGJ** [comment]
@pidus what android version are you using?? I'm using IDM+ too. But it doesn't detect magnet link at all. Works fine with fennec.

**Comment by pidus** [comment]
@RealGJ Android 7.1.1, MIUI 10 EU ROM.

**Comment by RealGJ** [comment]
@pidus please try on Fenix Nightly too

**Comment by RealGJ** [comment]
Update: 

Able to reproduce in :

Nightly 200703 06:16 (Build #2015749811)
AC: 49.0.20200702131412, 1cba216b2
GV: 80.0a1-20200701093012
AS: 61.0.7

**Comment by RealGJ** [comment]
Update :

Unable to reproduce in
Nightly 200725 06:01 (Build #22070613)
AC: 52.0.20200724130127, 71b462d5b
GV: 80.0a1-20200723095657
AS: 61.0.10

Considering as solved and Closing!! Thank You!!
