### ISSUE TITLE
FNX2-13024 ⁃ [Bug] preview image in tab tray is reused even across domains

### ISSUE THREAD

**Issue by jensrutschmann** [mozilla-mobile/fenix#12051]
## Steps to reproduce
Unkown, possibly caused by adding or removing tabs between the two affected ones. I've only seen this happen to adjacent tabs in the list.

### Expected behavior
Preview images should never be reused for other tabs.

### Actual behavior
Sometimes an image is used for another tab, even if that tab is for another domain:

![20200627](https://user-images.githubusercontent.com/784213/85920935-69de8b00-b878-11ea-84c7-6760b85f61b6.jpg)UNITO-UNDERSCORE!131011!

Some tabs don't have an image at all, even after activating them but I think this is already tracked in another issue.

### Device information
* Android device: Samsung Galaxy S7 (SM-G930F)
* Fenix version: 5.2.0 (Build #21701706) AC: 46.0.0, bca4c5c91 GV: 78.0-20200612174529 AS: 60.0.0

**Comment by kbrosnan** [comment]
This should be fixed in recent [Nightly builds](https://play.google.com/store/apps/details?id=org.mozilla.fenix)
