### ISSUE TITLE
FNX-13074 ⁃ [FEATURE REQUEST] Support for External Download Manager

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#12057]
Please add support for External Download Manager for downloading Manager, instead of downloading it within fenix itself. 

Who would benefit: everyone who downloads files

**Comment by Dunexus** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/7620

**Comment by kbrosnan** [comment]
Closing as a duplicate
