### ISSUE TITLE
FNX-13077 ⁃ [Design] Tabs tray doesn't match ux mocks

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12059]
There is no save to collection button currently. It's in homescreen.

https://app.abstract.com/share/31de1afc-87d2-4a9e-9078-4d9d9831b60d?mode=build&selected=root-F38B4261-F40B-4740-8601-005E3D413D00&sha=5b4ffcc789da606d4fea47d335427af175a0285c

cc @brampitoyo i think he's working on this

**Comment by cadeyrn** [comment]
This is an outdated mockup. It still shows the old tabs tray fragment implementation before it was a bottom drawer.

**Comment by hakkikaancaliskan** [comment]
@cadeyrn oh okey, closing the issue.
