### ISSUE TITLE
FNX2-13022 ⁃ [Bug] White navigation bar / bad contrast on XT1031

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#12058]
## Steps to reproduce
Open Fenix

### Expected behavior
Navigation bar is white buttons on black.

### Actual behavior
White  on white navigation with bad contrast.

![Screenshot](https://user-images.githubusercontent.com/152493/85930485-c77bd300-b88a-11ea-921a-25103a1305b0.png)UNITO-UNDERSCORE!2020-06-27-15-23-05!

This used to work correctly as of a day or two ago, you can see https://github.com/mozilla-mobile/fenix/issues/11044 for a screencast with it looking correct. 

### Device information
* Android device: Moto G XT1031
* Fenix version: Nightly 21790609

**Comment by person808** [comment]
Able to reproduce on a Nexus 5 emulator (API 21)

**Comment by Diana-Rus** [comment]
Hi, verified as fixed on latest Nightly 7/16 build, i did encounter this issue on an older build on a Sony Xperia Z5 (Android 7), for the navigation bar.
I'll leave a GIF below with how it is now in light mode and private mode and a screen when app has dark mode enabled.
<details closed><summary>Gif with navigation bar button in light and private mode</summary>

![20200716-115843](https://user-images.githubusercontent.com/49859863/87652304-b5d86d80-c75c-11ea-98bd-67eef2014911.gif)
</details>
<details closed><summary>Navigation bar screen with dark mode</summary>

![Screenshot_20200716-120202](https://user-images.githubusercontent.com/49859863/87652313-b96bf480-c75c-11ea-889e-ceb17225d28c.png)
</details>

Note:
Didn't encounter this issue on Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8).

**Comment by yoasif** [comment]
It is fixed for me in beta and nightly, but I see it in the release copy @Diana-Rus
