### ISSUE TITLE
FNX-13081 ⁃ [Bug] Clicking on the "Firefox Nightly Search" on the long press pop-up menu in a custom tab doens't do anything

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12063]
## Steps to reproduce
1. Open a website in a custom tab 
1. Long press on a word
1. In the resulting pop-up menu click the 'Firefox Nightly Search' item to search with Firefox Nightly
1. Observe that it doesn't do anything instead just opens the Firefox Nightly

### Expected behavior
It should perform a search with the selected word from the default search engine

### Actual behavior
Doesn't perform a search

### Device information
* Android device: **Motorola One Power, Android 10**.
* Fenix version: **`Nightly 200627 06:01`**.

![20200628](https://user-images.githubusercontent.com/42088907/85939447-339b1d00-b905-11ea-8bda-75835528c94c.gif)UNITO-UNDERSCORE!112348!

**Comment by ekager** [comment]
Closing for #9056
