### ISSUE TITLE
FNX-4872 ⁃ Cannot scroll after watching a fullscreen youtube video

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1206]
Filing this so that we have a Fenix issue as this is bad behavior on a top tier site. GV bug is [1471340](https://bugzilla.mozilla.org/show_bug.cgi?id=1471340)

## Steps to reproduce
* visit https://www.youtube.com
* start a video playing
* enter full screen
* press back

### Expected behavior
* able to scroll the page after exiting full scree

### Actual behavior
* cannot scroll after exiting full screen

### Device information
* Android device: Pixel 3/Pixel XL
* Fenix version: March 26th

**Comment by cpeterso** [comment]
Removing `blocked` and `Needs GV work` labels because snorp says this bug should be fixed in Fenix app code, not GV. Fenix needs to handle Back button navigation and exit full screen mode.

**Comment by cpeterso** [comment]
@vesta0 - Fenix should fix this bug for MVP.

**Comment by kbrosnan** [comment]
Verified fixed using Pixel 3
