### ISSUE TITLE
FNX-13085 ⁃ [Bug] Unable to Search Easily

### ISSUE THREAD

**Issue by pidus** [mozilla-mobile/fenix#12067]
## Steps to reproduce
* Set Fenix as default browser (optional).
* Load any webpage with text. 
* Select a word or sentence. 
    1. Expected behavior
Easily get an option to search the selection with default search engine.
    1. Actual behavior
The option is hidden under 3-dot menu and after alternative apps like Edge, Wikipedia. 
    1. Device information
Xiaomi Mi Max 2. MIUI 10
* Android device: 7.1.1
* Fenix version: 77.0.0-beta.2

### Fennec:
![IMG](https://user-images.githubusercontent.com/11857051/85940902-dad08200-b90e-11ea-8c50-9b80ade0ea7f.jpg)UNITO-UNDERSCORE!20200628!UNITO-UNDERSCORE!123814!

### Fenix:
![IMG](https://user-images.githubusercontent.com/11857051/85940940-2125e100-b90f-11ea-81b2-b2bc9bf13bb3.jpg)UNITO-UNDERSCORE!20200628!UNITO-UNDERSCORE!123836!
![IMG](https://user-images.githubusercontent.com/11857051/85940942-26832b80-b90f-11ea-92f8-61c36828e05f.jpg)UNITO-UNDERSCORE!20200628!UNITO-UNDERSCORE!123856!

* Related Reddit post: https://redd.it/hg8d36

**Comment by brampitoyo** [comment]
@pidus Acknowledged. This issue will be solved when we fix #10466.

On https://github.com/mozilla-mobile/fenix/issues/10466#issuecomment-626445627, you’ll see that the ordering of the context menu will prioritise “Search”.
