### ISSUE TITLE
FNX2-13010 ⁃ [Design] Follow ux mock on Settings --> Language screen

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12078]
Breakdown from issue #7065
![language-issue](https://user-images.githubusercontent.com/17825767/85996206-40556900-ba0a-11ea-83c2-51074930aea2.png)

**Comment by hakkikaancaliskan** [comment]
I'm working on this.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build **7/7** with **Google Pixel 4 XL (10).**
![Screenshot_20200707-164159](https://user-images.githubusercontent.com/42831109/86801806-17258000-c07d-11ea-8dba-b73fc2700e34.png)
