### ISSUE TITLE
[Bug] Amazon.co.uk track package link opens play store?

### ISSUE THREAD

**Issue by euinor** [mozilla-mobile/fenix#12072]
### Steps to reproduce
Click link in an email from Amazon, subject 'order despatched', button is 'track your package'. I can share the link if that is helpful.
Note:'open in app' setting is switched on in browser.

### Expected behavior
Opens amazon.co.uk webpage in browser.

### Actual behavior
Opens Google play store app at Amazon app store page. Pressing back takes you to the browser and the correct webpage.

### Device information
* Android device: Pixel 3a
* Fenix version: 5.2.0

**Comment by sheikh-azharuddin** [comment]
Try in chrome...i guess behaviour will be same... As app is not installed it is directing to play store to install the app

**Comment by euinor** [comment]
It works fine in chrome (web page opens without opening the play store)

**Comment by sheikh-azharuddin** [comment]
Maybe links are not getting handled properly...few days ago i reported one issue wherein the links in the sms/mails opens properly in chromium browsers but failed to open in Firefox (could not find address)

Let's see what Firefox says....

**Comment by euinor** [comment]
Just to say this is still an issue in Firefox mobile browser version 86.0.0-beta.5
