### ISSUE TITLE
Transparent Navigation Bar

### ISSUE THREAD

**Issue by gregoryt814** [mozilla-mobile/fenix#12074]
### What is the user problem or growth opportunity you want to see solved?
Currently, the navigation bar has a solid background and is not transparent.  I suggest that the navigation bar should be transparent in order to display more content on the screen and provide a cleaner aesthetic.

### How do you know that this problem exists today? Why is this important?
This problem exists, and its impact on content visibility can be seen below.  This is important as content that can be displayed effectively should not be hidden under a bar.

### Who will benefit from it?
This is especially important for the increasing amount of users who are using Android 10 gesture navigation as the current solid background is unappealing.

Thank you so much for your time!

![Screenshot](https://user-images.githubusercontent.com/39231651/85955465-9e634d00-b933-11ea-927d-f2274342913b.jpg)UNITO-UNDERSCORE!20200628-111109!
![Screenshot](https://user-images.githubusercontent.com/39231651/85955467-9efbe380-b933-11ea-96a6-3a802425b4c1.jpg)UNITO-UNDERSCORE!20200628-112117!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2766)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807087

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
