### ISSUE TITLE
Add a paste clipboard link when the contents are text but not a url

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1207]
### Why/User Benefit/User Problem
If I copy a url, open Fenix and tap the search bar, I see a "Fill link from clipboard" command. If I copy some other kind of text (e.g. a word or phrase) and then perform the same steps I don't see any command to fill in my clipboard contents. Of course I can still long press the search field to get the paste command but I may be led to believe that Fenix doesn't support this because I don't see fill command. In addition, tapping a fill link is more discoverable and easier to perform than a long press in the search field.

### What / Requirements
When there is text in the clipboard that is not a URL, we should present a similar command. Maybe, "Fill text from clipboard" to match the link command. But we should not show the contents of the clipboard in this case (unlike the link case) because it could be very long or contain sensitive information.

### Acceptance Criteria (how do I know when I’m done?)
When I have arbitrary text in my clipboard I should see a "Fill text from clipboard" link when in search mode.

### Priority
I don't think this is a blocker. This would be nice to have in the MVP.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2757)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807756

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
