### ISSUE TITLE
[Bug] sliding popup are inconsistent

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#12070]
The sliding popup have not the same design:

* Some are bottom square
![Screenshot](https://user-images.githubusercontent.com/56130419/85945782-45e67c80-b940-11ea-8bff-004d04b6f568.png)UNITO-UNDERSCORE!20200628-125931!UNITO-UNDERSCORE!Syst�me!UNITO-UNDERSCORE!Android~2!
* Some are top square (only when awsome bar is top), also notice the transparent status bar on top of a white popup
![Screenshot](https://user-images.githubusercontent.com/56130419/85945792-572f8900-b940-11ea-823b-5a9f13f2a358.png)UNITO-UNDERSCORE!20200628-125937!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!
* Some have big rounded corner, and the left one is not align (there is a 2-3pixel flat part left of this corner)
![Screenshot](https://user-images.githubusercontent.com/56130419/85945809-6f9fa380-b940-11ea-923c-df84ae21b801.png)UNITO-UNDERSCORE!20200628-125955!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

* Some have small rounded corner but have white status bar
![Screenshot](https://user-images.githubusercontent.com/56130419/85945816-80501980-b940-11ea-861d-f8a948d2f716.png)UNITO-UNDERSCORE!20200628-125914!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly~2!

**Comment by Octoton** [comment]
And the save password is also different:
![Screenshot_20200704-151014_Firefox_Nightly~2](https://user-images.githubusercontent.com/56130419/86513347-c78b4e00-be09-11ea-84f0-deb1861f1107.png)

**Comment by Diana-Rus** [comment]
Hi, yes i can reproduce this with Google Pixel 3 XL (Android 9) and Sony Xperia Z5 (Android 7) when
- Sharing a link
- Saving credential pop up 
- Pop up for the sites security level indicator
- ETP pop up
- When find in page options is enabled
- Download completed pop-up

**Comment by Octoton** [comment]
Link to #10105

**Comment by Octoton** [comment]
Same problem with the history tab:
![Screenshot_20200814-205434_Firefox_Nightly~2](https://user-images.githubusercontent.com/56130419/90283538-b43fb980-de70-11ea-855f-5198fa8e4cfa.png)
