### ISSUE TITLE
Fast access to Top Sites

### ISSUE THREAD

**Issue by KL643** [mozilla-mobile/fenix#12075]
### What is the user problem or growth opportunity you want to see solved?
Fast access to Top Sites

### How do you know that this problem exists today? Why is this important?
Before last update, pressing Tab showed Top Sites, now I have to press Tab/ + In old FireFox tapping the toolbar showed our favorite sites (Top Sites) which was perfect to me

### Who will benefit from it?
Everyone who uses Top Sites a lot

**Comment by Yves-Be** [comment]
Also check https://github.com/mozilla-mobile/fenix/issues/9118 and https://github.com/mozilla-mobile/fenix/issues/11296. Maybe it's best to close this as it seems like a duplicate.

**Comment by KL643** [comment]
> 
> 
> Also check #9118 and #11296. Maybe it's best to close this as it seems like a duplicate.

Thanks for pointing out :)
