### ISSUE TITLE
FNX2-13005 ⁃ [Design] Follow ux mock on Settings --> Customize screen

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12086]
Breakdown from issue #7065
![resim](https://user-images.githubusercontent.com/17825767/86009599-152b4380-ba23-11ea-8a7a-f32422d3463e.png)

**Comment by hakkikaancaliskan** [comment]
I'm working on this.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build **7/7** with **Google Pixel 4 XL (10).**
![Screenshot_20200707-163907](https://user-images.githubusercontent.com/42831109/86801694-fceba200-c07c-11ea-91c2-ea12d8b7e950.png)
