### ISSUE TITLE
FNX-4873 ⁃ Block autoplay when on mobile data

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#1208]
### Why/User Benefit/User Problem
Mobile data is expensive, and even if the video is muted with today's current implementation, this still costs :moneybag: :moneybag: .

### What / Requirements
Blocking auto-play video (not just muting it) when on a cellular connection.

### Acceptance Criteria (how do I know when I’m done?)
A preference in Settings that some combination of autoplay options: Allow, Only over Wi-Fi, Block, Never.

Notes:

* This is **NOT** the same as disabling autoplay video in a battery saving mode.
* Implementation detail: this should be possible with the site permission settings from GV/AC.

**Comment by NiLSPACE** [comment]
This is similar to #810

**Comment by vesta0** [comment]
@jonalmeida does this require any GV work to identify whether user is on mobile data or wifi?

**Comment by jonalmeida** [comment]
> @jonalmeida does this require any GV work to identify whether user is on mobile data or wifi?

@vesta0 Yes, this is a gecko feature.

**Comment by vesta0** [comment]
@cpeterso do we have a GV issue already to track this?

**Comment by cpeterso** [comment]
> do we have a GV issue already to track this?

GV already has an API for this: setAutoplayDefault.

https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntimeSettings.html#setAutoplayDefault-int-

**Comment by jonalmeida** [comment]
> @cpeterso do we have a GV issue already to track this?

@vesta0 Oh heyyy, we already have this implemented! https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt#L183

**Comment by jonalmeida** [comment]
@cpeterso I was just a second too late to reply. :)

**Comment by vesta0** [comment]
Thank you @jonalmeida and @cpeterso ! So just to clarify, we already have an API to track when user is on mobile data?

**Comment by cpeterso** [comment]
> we already have an API to track when user is on mobile data?

We have a GV API to toggle autoplay blocking. GV doesn't expose an API to track when the user is on mobile data, but Android does.

**Comment by vesta0** [comment]
@cpeterso thanks for the clarification.

**Comment by sblatz** [comment]
We need UX for this setting before we can work on it as the actual engineering change is pretty trivial.

**Comment by vesta0** [comment]
Will be covered by #255
