### ISSUE TITLE
FNX-13107 ⁃ [Bug] Save collection button not shown after the first collection

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12088]
## Steps to reproduce
1. Open a few tabs.
1. On the homescreen, check the Save to collection button is displayed. 
1. Tap the button, create a collection.
1. On the homescreen, check the Save to collection button is displayed. 
1. Delete Collection 1. 
1. On the homescreen, check the Save to collection button is displayed. 

### Expected behavior
The Save collection button is always displayed as long as there are open tabs.

### Actual behavior
Once the first collection is created, the button doesn't appear anymore.
When you delete the existing collection, the button doesn't re-appear, until you go to a tab and then back to homescreen.
This way you can only add individual tabs to a collection.

### Device information
* Android device: Pixel 4 (Android 10), Huawei P20 (Android 9)
* Fenix version: Beta 78.0.1-beta1, Nightly 6/29

**Comment by liuche** [comment]
This is a little weird, but I don't see this broken on the 6/28 Nightly, but let's take a look.

**Comment by darkwing** [comment]
Wait, this button is *always* supposed to be there?  I thought it was only if there are no collections....

**Comment by liuche** [comment]
Oh interesting, I read this as, after you delete the last collection, the "Save Collections" button doesn't come back immediately.

But I think that button should only be there if there are no collections (which is the case if you delete your last collection).

Is that correct @sv-ohorvath ?

**Comment by sv-ohorvath** [comment]
> Oh interesting, I read this as, after you delete the last collection, the "Save Collections" button doesn't come back immediately.
> 
> But I think that button should only be there if there are no collections (which is the case if you delete your last collection).
> 
> Is that correct @sv-ohorvath ?
> 
> (we decided this wouldn't be a release blocker)

From https://github.com/mozilla-mobile/fenix/issues/11860 this is what I understand:
- Only when there are no open tabs - don't show the button.
- When there are open tabs, no matter if there are other collections - show the button
Otherwise, you can't save multiple tabs at once, this button is the only place you can start that flow. If you go to a tab and add it to a collection, you can do that only with one tab at a time. 
In my opinion, it doesn't really make sense to have access to that option only once.

**Comment by liuche** [comment]
Okay, thanks for the extra information! I think based on this discussion, this is working as expected - we only show the button if there are no collections because it's meant to be a "feature discoverability" thing.
