### ISSUE TITLE
FNX2-13008 ⁃ [Bug] Google is not in the "Default search engine" list

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12081]
## Steps to reproduce
1. Launch Fenix;
1. Go to Settings -> Search;
1. Observe the "Default search engine" list;
    1. Expected behavior
An alphabetically ordered radio button list of search engines installed by default is displayed:

* Google (by default)
* Amazon.com
* Bing
* DuckDuckGo
* Twitter
* Wikipedia
    1. Actual behavior
Google is not in the "Default search engine" list. Google is displayed now in the "Add search engine" list.
    1. Notes
![20200629](https://user-images.githubusercontent.com/48799384/85999920-849a3680-ba15-11ea-8053-a4ece9c6387d.gif)UNITO-UNDERSCORE!143100!

### Device information
* Android device: Motorola Moto G6 (Android 8).
* Fenix version: Fenix Beta 78.0.1-beta.1 GV 78 from 6/27

**Comment by st3fan** [comment]
In which locale settings was this tested?

Was this tested on a clean install?

**Comment by ebalazs-sv** [comment]
The above details from the description, are for English - US locale setting, without locale-switching, on a clean-install. 

I had tested this issue further and the results are:

**Clean install:**
- reproducible on English - US, Espanol;
- not reproducible on English - UK, Francais, Deutsch, Russian, Turkce, Italian;

**Switching locale:** 
- reproducible on English - US, Espanol, Italian;
- not reproducible on English - UK, Francais, Deutsch, Russian, Turkce;

**After Migration:**
- reproducible on English - US, Espanol;
- not reproducible on English - UK, Francais, Deutsch, Russian, Turkce, Italian.

For the reproducible locale settings, on clean install or after clearing data, the default search engine icon, displayed on the onboarding screen is Google and after dismissing the onboarding screen, is Amazon, see https://github.com/mozilla-mobile/fenix/issues/11875.

Fenix version: 
- Nightly Build 200629 from 6/29;
- Fenix 78.0.1-beta.1 from 6/27.

Android device:
- Google Pixel 3a (Android 10);
- OnePlus A3 (Android 6.0.1);
- Motorola Moto G6 (Android 8);

**Comment by st3fan** [comment]
@boek @rocketsroger can you two talk about this one? I think Roger mentioned that this may be a regression from a performance improvement ... keep it in the bug in case @Mugurell is already doing work on this please.

**Comment by boek** [comment]
@st3fan already on it :)

**Comment by boek** [comment]
@st3fan @Mugurell we got a PR open, here is the fix :) 

https://github.com/mozilla-mobile/fenix/pull/12138

**Comment by liuche** [comment]
should be landed on both the 79 branch and nightly.

**Comment by sflorean** [comment]
Verified as fixed on Beta build 79.0.0-beta.3 with the following devices:
- Motorola Moto G6 (Android 8);
- Huawei MediaPad M3 lite (Android 7);
- Huawei P20 lite (Android 9);
- Samsung Galaxy Tab S6 (Android 9);
- Xiaomi Mi Pad 2 (Android 5.1);
- OnePlus A3 (Android 6.0.1).

Google is now displayed in the search engines list, however, we were able to reproduce #11875 ->Amazon icon displayed on startup.

**Comment by Mugurell** [comment]
Closing this as per https://github.com/mozilla-mobile/fenix/issues/12081#event-3502606888
