### ISSUE TITLE
[Bug]Missing History and Bookmarks action bar after opening multiple items in new tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12083]
## Prerequisites
Have a couple of Bookmarks and history items

## Steps to reproduce
1. Open History
1. Multi-select a couple of items
1. Tap the ⋮ button from the action bar
1. Select Open in new tab
1. Dismiss the Tabs Tray

### Expected behavior
The History action bar should be available

### Actual behavior
**While in Normal Browsing**

| Section | Action | Status| Remarks |
|----|----|----|----|
| History  | Open in new tab   | :x: | Missing action bar  |
| Bookmarks | Open in new tab | :x: | Missing action bar |
| History   | Open in **Private** tab | ❗ |  The action bar is available, on the other hand, the number of selected items is lost after minimizing the Tabs Tray |
| Bookmarks | Open in **Private** tab | ❗ | The action bar is available, the problem is that it's not in selection mode (number of selected items, color change )  |

it should display the number of previously selected bookmarks
**While in Private Browsing**

| Section | Action | Status| Remarks |
|----|----|----|----|
| History  | Open in new tab   | ❗  |  The action bar is available, on the other hand, the number of selected items is lost after minimizing the Tabs Tray |
| Bookmarks | Open in new tab | ❗ | The action bar is available, the problem is that it's not in selection mode (number of selected items, color change ) |
| History   | Open in **Private** tab | :x: | Missing action bar |
| Bookmarks | Open in **Private** tab | :x:  | Missing action bar |

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)
* Fenix version: 
**`Fenix 78.0.1-beta.1 from 6/27`**
**`Nightly Build 200629 from 6/29`**

### Notes
Could be caused by #11468 

► Video Normal Browsing
![20200629-152635](https://user-images.githubusercontent.com/51314259/86007357-f37c8d00-ba1f-11ea-923e-dc773deba722.gif)

► Video Private Browsing
![20200629-152919](https://user-images.githubusercontent.com/51314259/86008244-2a06d780-ba21-11ea-9744-2e4246886177.gif)

**Comment by mcarare** [comment]
Before submitting a fix can UX give some feedback on what the behavior should be? Specifically, do user expect their selection to be kept when returning to the library screen? Should we preserve that, or on return we should show the initial toolbar? TY!

**Comment by nc-x** [comment]
As a user who has lots of bookmarks in a lot of different folders, I would prefer that after I select bookmarks and open them, I stay inside bookmarks in the same folder with everything deselected, so that I can move around opening bookmarks from the next folder.

**Comment by AmyYLee** [comment]
Assigning to @topotropic  for feedback

**Comment by topotropic** [comment]
@nc-x thanks for the feedback – I'm just wondering if we should open the last select site right away instead of sending people to the tab tray. I'm curious to learn more about your use case here, why would you want to go back to the bookmark/history section? Thanks!

**Comment by nc-x** [comment]
@topotropic 
Well, it's the same reason as having Ctrl+B open a persistent bookmarks side bar in desktop firefox.
You have bookmarks organized into many folders, and you want to open bookmarks from multiple folders. So, opening bookmarks again and again, as well as remembering whether you already went through a particular bookmark folder or not is a chore.
So instead, you have the bookmarks tab open, and you open all the urls you want, then you close the bookmarks tab and browse in peace.

In any case, currently after opening multiple tabs the tab tray is shown. So, if people do not want to open any more bookmarks, they can always just click any tab then. It's just one more click (comparatively, my usecase above requires multiple clicks because I have to reopen bookmarks tab again and again, then go through the folder hierarchy to find where I was previously, open more tabs, repeat...)

**Comment by topotropic** [comment]
Thanks for the explanation @nc-x 

> Specifically, do user expect their selection to be kept when returning to the library screen? Should we preserve that, or on return we should show the initial toolbar?

@mcarare We don't need to keep the selection after someone opened the selected tabs, please return to the initial toolbar.

Currently, we keep a back arrow icon in selection mode, would it be possible to update this to a close icon when people are in selection mode as part of this issue? thanks!
