### ISSUE TITLE
Evaluate need for and remove if not needed scrollAndAnimateCollection

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#12084]
With the tabs being moved into the tabs tray the need to scroll on the homescreen to a newly created collection is probably not necessary anymore since the newest collection should appear on the top of the list anyway now and there shouldn't be tabs in the way.

Also looking at the old code for it, it's currently attempting to scroll to a position based on the number of tabs and incorrect number of list items, so we either need to fix it up or remove it entirely. 

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L793

**Comment by ekager** [comment]
Because the tabs tray stays up while the collection is being added even while on the homescreen AFAICT these animations are never even called right now

**Comment by mcomella** [comment]
@ekager Is there performance work needed here? We're trying to figure out how this is a performance issue.

**Comment by ekager** [comment]
Ah no, sorry
