### ISSUE TITLE
FNX-13119 ⁃ Reader mode toggle should appear in Custom Tabs

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#12098]
### What is the user problem or growth opportunity you want to see solved?
Title ...sorry

### How do you know that this problem exists today? Why is this important?
The toggle doesn't currently appear for me. I have to open firefox to use it, which apart from defeating the point (SPEED!), is just frustrating - what's that? You can tell? :/

### Who will benefit from it?
Everyone :grinning:

**Comment by ekager** [comment]
Closing for #5691

**Comment by astarq** [comment]
Sorry I didn't find that :/
