### ISSUE TITLE
[Bug] error page button outline

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#12093]
![image](https://user-images.githubusercontent.com/14617699/86021725-13b54780-ba32-11ea-9176-0fa46614002f.png)

5.2.0

**Comment by hakkikaancaliskan** [comment]
No problem on nightly.

![resim](https://user-images.githubusercontent.com/17825767/86044090-48d19200-ba52-11ea-9f5b-dbd6f3e3bc51.png)

**Comment by 532910** [comment]
LineageOS 16 / Android 9

The same issue on nightly!

**Comment by hakkikaancaliskan** [comment]
This outline shown on all error screens and just when you tap the reload button.

**Comment by 532910** [comment]
Yep, and when reload takes long time you'll see it all this time.

**Comment by hakkikaancaliskan** [comment]
> 
> 
> Yep, and when reload takes long time you'll see it all this time.

That long time normal because retrying to connect to server and waits for timeout.

**Comment by 532910** [comment]
Any time is normal, but the outline is not. It must not be shown at all.

**Comment by mcarare** [comment]
In this type of pages it is custom to keep a button outline (focus rectangle) as a way  to help the user know that the button click was registered and the action the button triggers is ongoing, and prevent him from repeatedly clicking the button. IMO from this should be left alone, but I'm leaving the decision to UX.

**Comment by 532910** [comment]
There are a lot of other ways to show the user the response, besides of ugly outline.

**Comment by AmyYLee** [comment]
I agree there shouldn't be a white outline here. Since we already have the loading bar providing feedback to the user that something is happening, I don't think it's necessary to highlight the button. @brampitoyo Do you have an opinion?

**Comment by brampitoyo** [comment]
@mcarare Having a 1px outline to acknowledge focus is ok (Chrome also does this. For maximum compatibility, we can even make this colour controlled by the system.

But we should definitely make this outline match our button height (36dp) and border radius value (4dp). Can we do that?

So it would look like this:

<img width="360" src="https://user-images.githubusercontent.com/51007/86877960-10117700-c13c-11ea-9b24-ff81884c447a.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/86877963-1142a400-c13c-11ea-90a3-34ac61f5d6b5.png">

Just one thing to note: when the theme is set to dark, the white outline has good contrast. But when the theme is light, the black outline doesn’t. There’s nothing I can do there.

**Comment by 532910** [comment]
Chrome is not a role model, but I completely agree with Bram, the main problem with current outline that it's ugly. Making it shaped solves this issue.
