### ISSUE TITLE
FNX-4874 ⁃ Remove duplicate urls from search suggestions and history suggestions

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1209]
## Steps to reproduce
1. Copy a URL to the clipboard. In this case, https://en.m.wikipedia.org/wiki/Solange_Knowles
1. Paste in url in Fenix and navigate to the page.
1. Tap the search bar to enter search mode.

### Expected behavior
The URL is selected and the keyboard comes up. Nothing else is displayed.

### Actual behavior
In addition to the URL being selected and the keyboard coming up, there is:

* a search suggestion that is equal to the selected URL (maybe related to Issue #1205)
* two history entries for this url
* a "Fill link from clipboard" command for this url.

### Device information
* Android device: Nokia 3.1
* Fenix version: 1.0.1913

### Priority
I think this is a blocker.

### Dependencies
This is ticket https://github.com/mozilla-mobile/android-components/issues/1368

**Comment by Verdi** [comment]
I think I conflated 2 issues when filing this:

1. There are duplicate URLs present
2. There are search and history suggestions present

The duplicate URLs issue seems to be tracked with #482 & https://github.com/mozilla-mobile/android-components/issues/1368 as noted above.

I filed a new issue for the presence of search and history suggestions - #1620

**Comment by vesta0** [comment]
Closing this issue and addressing reported issues in #1620 and #482
