### ISSUE TITLE
FNX-35 ⁃ "New tab"/"Private tab" is hard to find

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#1210]
## Steps to reproduce
* Open browser
* Load page
* Click menu (to open new tab)

### Expected behavior
New tab is easy to find: it's at the top of the list. Or maybe it's at the bottom of the list (because it's close to your thumb and the button that opened the menu).

### Actual behavior
New tab is lost somewhere in the middle of the list and it requires scanning to find it. At the top of the list, we have minorly used items "Help" and "Settings".

Note: this is especially a problem for accessibility where users will have to hear each item in the list spoken to them in order to find new tab.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1913

**Comment by lime124** [comment]
removing ux label - collecting issues for a bigger UX effort on the toolbar menu.

**Comment by apbitner** [comment]
'New Private Tab' and 'New Tab' have been prioritized to be closest to the menu button
