### ISSUE TITLE
FNX2-12993 ⁃ [Design] Follow ux mock on Settings --> Accessibility screen

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12105]
Breakdown from issue #7065

![resim](https://user-images.githubusercontent.com/17825767/87294799-ecb84480-c50c-11ea-9122-27f0f2ebdf21.png)

**Comment by hakkikaancaliskan** [comment]
I'm working on this.

**Comment by SS1113** [comment]
@hakkikaancaliskan In the third image 'Zoom on all websites' should be aligned with 'Automatic Font sizing' 'Font size' position.

To mockup image seems to not match with the issue you have linked. Hope you're aware of this.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo what do you think about this?

**Comment by brampitoyo** [comment]
@hakkikaancaliskan I’d love to see a screenshot of this screen? I’ll see it first thing tomorrow, and will provide a feedback.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo 
![resim](https://user-images.githubusercontent.com/17825767/86142761-3a3fb500-bafc-11ea-9757-4b15d67ab991.png)![resim](https://user-images.githubusercontent.com/17825767/86142766-3c097880-bafc-11ea-8ebc-0141e3b15844.png)

**Comment by hakkikaancaliskan** [comment]
> To mockup image seems to not match with the issue you have linked. Hope you're aware of this.

Look to the comment of @brampitoyo on that issue. That's the latest.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan The only two tweaks I would make to this page:

- Change all the font family value from Metropolis to our default font (Inter/Roboto).
- Make sure that the margin between “Font size” and “Make text on websites larger or smaller”, matches the margin between other label heading and label text. At the moment, the margin is larger than it’s supposed to.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo 
>     * Change all the font family value from Metropolis to our default font (Inter/Roboto).

They're not metropolis, my device's font looks similar to metropolis. Could you please verify on your device?

**Comment by brampitoyo** [comment]
@hakkikaancaliskan The screenshot you provided on https://github.com/mozilla-mobile/fenix/pull/12478#issue-447800156 was already correct in terms of font family and margin between list items, but I totally forgot about the 72dp keyline gap. This was totally my mistake – sorry!

The correct spec is as follows (you can replace comment 0 with this spec if you like):

<img width="1680" alt="Screen Shot 2020-07-13 at 3 13 51 PM" src="https://user-images.githubusercontent.com/51007/87267332-7f5fe000-c51b-11ea-8748-a8786b0cda59.png">

You’ll observe that all the list items and elements (sliders, preview text box) on this page now follows the same 72dp keyline gap, as the rest of Settings.

Full credit to @cadeyrn for pointing out this inconsistency!

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly from 7/20 with Google Pixel 4 XL (Android 11).
