### ISSUE TITLE
FNX2-12991 ⁃ [Design] Follow ux mock on Settings --> Account screen

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12107]
Breakdown from issue #7065 

![account](https://user-images.githubusercontent.com/17825767/86057617-2cd8eb00-ba68-11ea-81ed-def91f056cbe.png)

**Comment by hakkikaancaliskan** [comment]
I'm working on this.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo I'm unable to find this icon in fenix and it's [16x16 in ac](https://github.com/mozilla-mobile/android-components/blob/master/components/ui/icons/src/main/res/drawable/mozac_ic_sync.xml). Could you please share the icon so i can update the ac icon? 
![resim](https://user-images.githubusercontent.com/17825767/86143273-e5506e80-bafc-11ea-9c72-6a1d1bf6559c.png)

**Comment by brampitoyo** [comment]
@hakkikaancaliskan Thanks heaps for checking on this small detail! The sync icon is meant to be 24x24, just like all other icons we use on Fenix.

Asset: https://share.getcloudapp.com/ApuAXXjz

**Comment by hakkikaancaliskan** [comment]
> 
> 
> @hakkikaancaliskan Thanks heaps for checking on this small detail! The sync icon is meant to be 24x24, just like all other icons we use on Fenix.
> 
> Asset: https://share.getcloudapp.com/ApuAXXjz

Ohh, @NotWoods said photon icon is okey so i've already opened pr with photon icon. Do I need to update it?

**Comment by NotWoods** [comment]
@hakkikaancaliskan We can use the photon icon that was merged for now.

@brampitoyo The asset you provided has a 5px margin while photon icons just has 2px margin, which better aligns with our other icons. Is the photon icons version OK to keep?

**Comment by hakkikaancaliskan** [comment]
@NotWoods I was writing to you :)

**Comment by brampitoyo** [comment]
@NotWoods I didn’t know that our Photon icons have a different margin.

As strange as this may sound, the icon we have in our library has a 5px margin! But it sounds like the Photon version is more correct. Let’s use that instead.

**Comment by hakkikaancaliskan** [comment]
@Mugurell this one landed, so it requires qa needed tag

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200716 from 7/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200716-121136](https://user-images.githubusercontent.com/51314259/87654329-66e00780-c75f-11ea-907b-121de712a2a2.png)
