### ISSUE TITLE
FNX2-12992 ⁃ [Design] Follow ux mock on Settings --> Logins screen

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12106]
Breakdown from issue #7065 

![logins-1](https://user-images.githubusercontent.com/17825767/86057528-01560080-ba68-11ea-97e4-b4a14b112cfb.png)
![logins-2](https://user-images.githubusercontent.com/17825767/86057532-031fc400-ba68-11ea-8c30-af6d9f97cf54.png)
![logins-3](https://user-images.githubusercontent.com/17825767/86057531-02872d80-ba68-11ea-82ea-3022850f27f8.png)

**Comment by hakkikaancaliskan** [comment]
I'm working on this.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200716 from 7/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200716-124355](https://user-images.githubusercontent.com/51314259/87659270-fee0ef80-c765-11ea-8d16-4dce34ce5114.png)
![rsz_screenshot_20200716-124420](https://user-images.githubusercontent.com/51314259/87659271-00121c80-c766-11ea-8acf-23786ea578e0.png)
