### ISSUE TITLE
FNX2-12990 ⁃ [UX] [Meta] Enhancements to tab organization/navigation

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12108]
## User Story
* As a user, I want to easily and quickly find and navigate to the information I am looking for in the browser, without having to take too many steps to find what I need. 

### Acceptance Criteria
~~Re~~evaluate user’s starting point on return visits #12062
~~Re~~evaluate what happens when user opens a new tab (go to homescreen vs open search) #11513
-I can restore a recently closed tab or session #11582 
-I can easily find and open their last visited tab #10344 
-I can access synced tabs from within the tabs tray

**Comment by maverick74** [comment]
Using address bar at the bottom and having new tabs popping up on the top of the screen is, from my point of view, a contradiction as I have to go all the way up just to get that new opened tab.

I believe it would make more sense to have the more recent tabs on the bottom

**Comment by brampitoyo** [comment]
@maverick74 For tab ordering (top-to-bottom vs. bottom-to-top) within the tab tray, let’s ask @topotropic.

**Comment by Dunexus** [comment]
See https://github.com/mozilla-mobile/fenix/issues/12861 and https://github.com/mozilla-mobile/fenix/issues/13172.

From https://github.com/mozilla-mobile/fenix/issues/12861, the choice was between : 

> the newest tab in tab tray would be at botton
> the most left tab in "swiping gesture" would be the oldest
> The oldest tab in tab tray would be at top
> the most right tab in "swiping gesture" would be the newest.
>
> or
>
> the newest tab in tab tray would be at top
> the most left tab in "swiping gesture" would be the newest
> The oldest tab in tab tray would be at botton
> the most right tab in "swiping gesture" would be the oldest.

The latter has been chosen but it is really counter-intuitive to me.

Inside tab tray (vertical navigation) : 
- on fennec, the newest tab was at the bottom
- inside the old vertical Android app switcher, the newest app was at the bottom

For "swiping gesture" (horizontal navigation) : 
- on desktop, the newest tab is on the right
- inside Android 10 horizontal app switcher, the newest app on the right too

**Comment by maverick74** [comment]
I agree with @Dunexus they're both counter-intuitive.

Also, one of the reasons to move address bar to bottom was to have "at hand"... So, why are new tabs totally "out of hand" (aka "all the way up in tab tray")?

What a pita this is to me.........
