### ISSUE TITLE
FNX2-12996 ⁃ Map Deeplink to Search Widget Setting for Leanplum in Fenix

### ISSUE THREAD

**Issue by cbonacuse** [mozilla-mobile/fenix#12102]
The following deeplink was identified as a priority for Fenix during a recent test by the Mobile Engagement team.

* [ ] Search Widget deeplink (in Fennec: firefox://search_widget)

This deeplink should open the app (even if killed) and show this screen where the user can click "add automatically" and the widget is added in the background while the app is still open.

![Screenshot](https://user-images.githubusercontent.com/60749496/86047846-8f58c980-ba1d-11ea-8030-7d491fdc4e06.png)UNITO-UNDERSCORE!20200629-152942!

Tasks:

* [ ] Map deeplink
* [ ] Add test to show it's being fired (e.g. specified by #11210 )
* [ ] Test end-to-end and validate attribute in Leanplum

**Comment by data-sync-user** [comment]
➤ James Hugman commented:

This is fixed in the deeplink PR #11197.
