### ISSUE TITLE
[Bug] In the long press menu "Firefox Nightly search" is always searching with 'Amazon.com' instead of the selected default search engine

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12117]
In the long press menu after selecting a word on a webpage "Firefox Nightly Search" is searching with amazon.com instead of the default search engine which is Google.

I have tried changing the search engine to another search engine and it fixes the problem for some time but after a while it starts to search with Amazon.com always.

![20200630](https://user-images.githubusercontent.com/42088907/86075883-93fe9b80-ba78-11ea-9a8a-57af6ab1bbd6.gif)UNITO-UNDERSCORE!074648!

Firefox Nightly default search engine: 

![Screenshot](https://user-images.githubusercontent.com/42088907/86075963-bee8ef80-ba78-11ea-8fac-842c54f3619a.png)UNITO-UNDERSCORE!20200630-075320!

Edit: Forgot to add the versions this was reproducible on, I'm sorry but I've lost the track of the build it was reproducing on but it is still reproducing on: Fennec migration build **`null (Build #2015749827) AC: 48.0.3, ce6247fb8 GV: 79.0-20200629163142 AS: 61.0.7`** . 

**Device: Motorola One Power, Android 10**.

See the https://github.com/mozilla-mobile/fenix/issues/12117#issuecomment-653871658.

**Comment by SS1113** [comment]
Currently this is still reproducible in: Fennec migration build **`null (Build #2015749827)
AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7`** and I'm yet to reproduce this again in: **`Nightly 200704 18:05`**.

GIF: 
![20200705_160328](https://user-images.githubusercontent.com/42088907/86530788-52705500-beab-11ea-9c9e-8048cd25a671.gif)

**Comment by upsuper** [comment]
I have the same problem with beta version, but it's using Baidu most of the time probably because my locale is zh-CN. My default search engine is ddg, and I've actually removed Baidu from the list. Sometimes it uses Google instead, which is in the list but not default either.

Similarly, it's fixed after I change the default search engine in settings then back, but the issue comes back again later.

**Comment by SS1113** [comment]
@upsuper can you provide the exact version number which it is reproducing on?

**Comment by upsuper** [comment]
79.0.0-beta.5 (Build #2015749827)
AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7

**Comment by SS1113** [comment]
> 79.0.0-beta.5 (Build #2015749827)
> AC: 48.0.3, ce6247fb8
> GV: 79.0-20200629163142
> AS: 61.0.7

Yeah, it is reproducing for me there as well; it always searches with `Amazon.com` instead of Google which is the default search engine.

**Comment by ShatteredPixel** [comment]
I am the reporter of this issue. Please let me know if I can provide you any more information. Thanks. :)

**Comment by kbrosnan** [comment]
This was a bug when we maid some search engine changes. We have resolved those issues.
