### ISSUE TITLE
FNX-449 ⁃ Hide the keyboard when scrolling through suggestions

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1211]
## Steps to reproduce
1. Enter a search term
1. Scroll the list of suggestions

### Expected behavior
The keyboard should hide since I no longer need and it and it will let see more of the list.

### Actual behavior
The keyboard stays up and I can only see 4 suggestions at a time.

### Device information
* Android device: Nokia 3.1
* Fenix version: 1.0.1913

**Comment by buttercookie42** [comment]
This is even worse in landscape - I can only see half a suggestion at most. And pressing back dismisses the whole search screen instead of merely the keyboard, even though the back arrow changes to the down pointing arrow that normally seems to indicate that pressing back will only dismiss the keyboard.

**Comment by ekager** [comment]
I had previously completed this, but there's a bug in ConstraintLayout causing weirdness. See #3668 . So I will need to revert this change and revisit this feature later.

**Comment by ekager** [comment]
I'm reopening this now. This was removed when implementing #3985. I think this was also causing weird behavior like #3587 because of how we are overriding the back button in Search. We should look into those issues before readding this feature

**Comment by sblatz** [comment]
Let's make sure this on @vesta0's roadmap if it's really a P2.

**Comment by liuche** [comment]
There's a dependency on this where if we do this functionality, either:
- we would require 2 back-presses to hide, and then go back
- OR we'd have make some changes to the keyboard hiding behavior in AC (which requires making changes to existing feature)

**Comment by sv-ohorvath** [comment]
> I think this was also causing weird behavior like #3587 because of how we are overriding the back button in Search. We should look into those issues before readding this feature

Emily was right here.
Current behavior: The keyboard hides while scrolling the suggestions. You need to press back to exit the search mode. If you were on the homescreen when you started the search, this will close the app. If you were on a webpage, it will navigate back one page/close the tab. Logged: https://github.com/mozilla-mobile/fenix/issues/6625

This is verified as fixed on Nightly 11/15.
