### ISSUE TITLE
Clear browser history after a specified amount of time

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12119]
As it is right now the browsing history stays forever on the browser and it could become a privacy issue, as not everybody remembers to use a Private Browsing Mode everytime, not to mention the browser history tab becomes an unmanaged clutter if let it be. 

I'd great if the browser history cleared itself after a set period of time such as in a few hours/days/weeks or let them set a custom period.

Edit: I'm talking about the locally saved browsing history.

**Comment by Dunexus** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/8342

**Comment by manan025** [comment]
I want to work on this.

**Comment by SS1113** [comment]
I'm not sure if this is a duplicate of the issue #8342, so I'm re-opening this issue.
