### ISSUE TITLE
FNX2-12987 ⁃ When the tabs tray is closed, don't reset the scroll position of the opened tab to the top of the Tabs Tray

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12116]
After opening a lot of tabs, when the tabs tray is closed, the opened tabs position is reset the top of the tabs tray. This behaviour should be changed as I have to scroll and try to reach the open tab which was at around my thumb finger a while ago is now at the top after closing the tabs tray. If the tabs position is reset to the top after a browser restart I can understand that but tabs tray opening and closing is done a lot times during a browsing session, I don't have to scroll and reach the tab I opened a few seconds ago everytime I close the tabs tray. 

![20200630](https://user-images.githubusercontent.com/42088907/86075587-dd022000-ba77-11ea-8900-b892d44071bc.gif)UNITO-UNDERSCORE!074059!

**Comment by kbrosnan** [comment]
We scroll to the currently focused tab at the when coming back to the tabs view now.
