### ISSUE TITLE
[Bug] Too many sites are left without favicons in the Top Site page

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#12110]
## Steps to reproduce
Wander in the web and pin sites as "Top sites"
Display the "Top sites"

### Expected behavior
All the sites shown on the "Top sites" page should have a real favicon and not an initial letter

### Actual behavior
Almost half of the sites do not have any real favicon but only an initial letter. This does not help in "reading" that page.

![image](https://user-images.githubusercontent.com/218971/86061095-601a7a80-ba66-11ea-9d89-adc43491724c.png)

I know that the reason for the missing favicons is that they are too small to be used as shortcuts on the phone launcher, or formerly in the tab list (now replaced by site previews).
But on the Top Sites page, the favicons are shown in a reduced size, therefore even a small-defined favicon could be displayed correctly for a better readibility in this situation (while still giving a blurry result if used as shortcut).

And it IS a fact, whether we like it or not, that many sites do not have favicons that are defined properly and large enough. Fenix cannot fix that and should be able to cope with it :).

### Device information
* Android device: ?
* Fenix version: ?

**Comment by SS1113** [comment]
Top sites not having a favicon of the actual website has become a real problem for me!

**Comment by sheikh-azharuddin** [comment]
In Outlook website sometime favicon is showing sometime a letter 😅

**Comment by SS1113** [comment]
Yeah, it's really random, sometimes the top sites fetch the favicon and sometimes it just doesn't, no matter how may time you try to add to the Top site.

**Comment by OsadebamwenEvbuomwan** [comment]
87 tabs opened at once, my phone would literally crash

**Comment by ekager** [comment]
@klint has this gotten any better?

**Comment by klint** [comment]
@ekager Not quite sure. While some sites have gained a favicon since the bug was open, other are still missing one.

Examples of those sites on my Top Sites pages are:
- support.mozilla.org (itself!)
- mubi.com
- www.huffingtonpost.fr
- www.monde-diplomatique.fr
- voiture.opodo.fr
- quaidesbrumes.fr
-

**Comment by lobontiumira** [comment]
This issue still reproduces on the 6/24 Nightly build with several devices: Google Pixel (Android 10), Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by yoasif** [comment]
Saw a report of an example here: https://www.reddit.com/r/firefox/comments/oo45t7/these_two_shortcuts_were_made_using_add_to_home/

The page is: https://minsktrans.by/lookout_yard/Home/Index/minsk#/routes/bus

**Comment by Sydnxt** [comment]
Can confirm, having the issue on Desktop and generating app icons on Mobile.
