### ISSUE TITLE
FNX-4876 ⁃ Dropped gestures when scrolling on container that can horizontally scroll

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#1212]
## Steps to reproduce
* Go to https://en.m.wikipedia.org/wiki/List_of_pastries
* Scroll the page down, including moving your finger on the table of pastries to continue scrolling

### Expected behavior
Each downward scroll gesture is registered.

### Actual behavior
Downward scroll gestures are sometimes dropped.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1913

**Comment by vesta0** [comment]
@mcomella does the page stops moving as a result of not registering downward scroll gesture? What is the user experience?

**Comment by mcomella** [comment]
> @mcomella does the page stops moving as a result of not registering downward scroll gesture? What is the user experience?

There are a few cases:
- If the page is not scrolling, after the gesture the page will not scroll
- If the page is scrolling, after the gesture the page will stop scrolling
- In both cases, sometimes the page flings unnaturally: it flings much faster than I had released

**Comment by vesta0** [comment]
@cpeterso is there a GV bug related to this?

**Comment by cpeterso** [comment]
I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1541644

**Comment by cpeterso** [comment]
The GV bug fix has landed and should be in tomorrow's GV 68 Nightly build. 🚀

**Comment by kbrosnan** [comment]
This is fixed in a current Fenix build. Noting that #1506 can be triggered.
