### ISSUE TITLE
FNX2-12981 ⁃ [Bug] Branding is not reverted back to Beta on v. 78.0.1-beta.1 and v. 79.0.0-beta.1

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12123]
## Steps to reproduce
1. Replace Fennec Beta with Fenix Beta with one of the builds:
https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.fennec-beta.2020.06.30.revision.05b6934e9958f595bf98685e9569e6d15a13fd13/arm64-v8a
https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.fennec-beta.2020.06.27.revision.e0fa1c0db4ff806c991b13906ef6a30ba4d6054d
1. Launch Fenix Beta and observe the branding;
    1. Expected behavior
The branding is reverted back to Beta, as it was for version 78.0.0-beta.1 with https://github.com/mozilla-mobile/fenix/issues/9946.
    1. Actual behavior
The branding is not reverted back to Beta, is displayed as Release.
    1. Device information

* Android device: all
* Fenix version: Beta v. 78.0.1-beta.1 and v. 79.0.0-beta.1

**Comment by pocmo** [comment]
CC @liuche 

It looks like this [commit, reverting to the beta branding,](https://github.com/mozilla-mobile/fenix/commit/d84f48a3912c6dee8760e7ba205623755117fc0c) only landed in the release branch for 78.0.0. It doesn't seem to have made it to master, 78.0.1 or 79.0.0.

* I am not sure if that was deliberately or a mistake. I assume we want to go back to the beta branding. But I am not sure if it is supposed this build?

* If it was supposed to go into 78.0.1 and 79.0.0 (and master) then maybe we need to double check if other things accidentally didn't make it into those branches?

**Comment by pocmo** [comment]
Patch uplifted to 79.0.0 Beta 2.

**Comment by st3fan** [comment]
I made this a 79ReleaseBlocker, which may sound weird for a Beta build, but we depend heavily on this being resolved and that build going out for testing to get to the final release. So I think it is good to keep this one on that list and to keep an eye on it.

**Comment by st3fan** [comment]
Sounds like this is resolved. Did we get QA confirmation?

**Comment by liuche** [comment]
QA, please verify on the 79.0.0-beta.2 build!

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta Migration 79.0.0-beta.3 GV 79 from 7/1 with the following devices:
- Motorola Moto G6 (Android 8);
- Huawei MediaPad M3 lite (Android 7);
- Huawei P20 lite (Android 9);
- Samsung Galaxy Tab S6 (Android 9);
- Xiaomi Mi Pad 2 (Android 5.1);
- OnePlus A3 (Android 6.0.1);

and the in-app branding in reverted back to Firefox Beta.
I will remove the qa:needed label. Thanks!
