### ISSUE TITLE
FNX2-12979 ⁃ [Bug]Missing or intermittently displayed "Save tabs to collection" while having open tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12125]
## Steps to reproduce
1. Open Wikipedia from the Top Sites section
1. Quickly open the Tabs Tray and press the New tab FAB

### Expected behavior
"Save tabs to collection" button should be displayed

### Actual behavior
"Save tabs to collection" is not displayed

## Alternative Steps to reproduce
1. Quickly open one by one the featured Top Sites
1. Observe the availability of "Save tabs to collection" button in the process

### Expected behavior
Clean transition to the Home screen
"Save tabs to collection" button should be displayed as long as the user has open tabs

### Actual behavior
Improper transition to the Home screen 
"Save tabs to collection" is displayed intermittently 

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
•Nightly Build 200629 from 6/30
•Fenix 79.0.1-beta.1 from 6/30

### Notes
► Video
![20200630-135721](https://user-images.githubusercontent.com/51314259/86119722-a3630080-badb-11ea-8816-1c8bc6419bca.gif)

► Video
![20200630-135641](https://user-images.githubusercontent.com/51314259/86119599-77477f80-badb-11ea-9a8d-fff73bcdd310.gif)

**Comment by liuche** [comment]
This isn't a release blocker, but since it's on our homescreen, we'll want to fix this because it looks unpolished. Fast-follow sprint.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build **7/8** with **Google Pixel 4 XL (10).**
![20200708-110642](https://user-images.githubusercontent.com/42831109/86895614-661af600-c10d-11ea-82d1-4208621aafbf.gif)
