### ISSUE TITLE
FNX2-12976 ⁃ [Bug]Closing the private tabs from the notification breaks the value of the normal browsing tabs counter

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12129]
## Prerequisites
Have a couple of open tabs in normal browsing

## Steps to reproduce
1. Open a new private tab
1. Open the Tabs Tray
1. Close the private tabs using the the system notification 
1. Check the Normal browsing tabs counter value

### Expected behavior
The tabs counter should display the number of previously opened normal browsing tabs

### Actual behavior
Displays 0 normal browsing open tabs

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly Build 200629 from 6/30
• Fenix 79.0.1-beta.1 from 6/30

### Notes
►Video
![20200630-164808](https://user-images.githubusercontent.com/51314259/86134070-d4e6c680-baf1-11ea-824f-2828940abe1c.gif)

**Comment by BMEduard** [comment]
After investigating, this issue was also fixed by PR #12307  . and it had the same underlying problem as #12126 .

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200716 from 7/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200716-095353](https://user-images.githubusercontent.com/51314259/87637514-06df6600-c74b-11ea-8c25-f8d81ea20cd9.gif)
