### ISSUE TITLE
[Bug] inconsistent string color

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12124]
## Steps to reproduce
In collection menu the delete collection item is red in color whereas in other sub menu the color is black...please make it consistent...i.e. make it red for items string such as "Remove" , "close all tabs" etc....or better why not also add a red trash icon...not big but small one...

### Expected behavior
Strings in submenu for delete, close all tabs, remove etc should show in red color

### Actual behavior
Shows in black color...the deletion should be easy to distinguish ...

### Device information
* Android device: ? Rog phone 2 A10
* Fenix version: ? Latest nightly

![Screenshot](https://user-images.githubusercontent.com/58127841/86117091-f8901980-babd-11ea-818e-cafeb04a767e.jpg)UNITO-UNDERSCORE!20200630-160410!

![Screenshot](https://user-images.githubusercontent.com/58127841/86117117-0180eb00-babe-11ea-9a38-9cf5f14e7191.jpg)UNITO-UNDERSCORE!20200630-160437!

![Screenshot](https://user-images.githubusercontent.com/58127841/86117145-0c3b8000-babe-11ea-9da4-7e429979680e.jpg)UNITO-UNDERSCORE!20200630-160500!

**Comment by mcarare** [comment]
This looks to me like a legitimate design consistency issue.

**Comment by AmyYLee** [comment]
@betsymi @topotropic for feedback - I think any sort of destructive behaviour should be highlighted in red. I'm not sure if closing actions are considered destructive enough to warrant red text. I think we reserve red for "delete" actions and leave the rest as regular text colour.

**Comment by betsymi** [comment]
> @betsymi @topotropic for feedback - I think any sort of destructive behaviour should be highlighted in red. I'm not sure if closing actions are considered destructive enough to warrant red text. I think we reserve red for "delete" actions and leave the rest as regular text colour.

Makes sense to me. Do we have that documented somewhere in case it comes up again?

**Comment by ekager** [comment]
It would help eng to have a list of where we should or should not change this in the app.

**Comment by sheikh-azharuddin** [comment]
Where to have
Top site item - Remove
3 dot menu- Quit( quit browser)

Where not to have
Tab tray - close all tabs

Just a suggestion 😊

**Comment by AmyYLee** [comment]
> It would help eng to have a list of where we should or should not change this in the app.

Assigned to @betsymi

**Comment by AmyYLee** [comment]
> It would help eng to have a list of where we should or should not change this in the app.

@ekager - Basically any string with "delete" as a destruction action is marked in red. It appears we are already following this rule. Marking this as won't fix.
