### ISSUE TITLE
FNX2-12978 ⁃ [Bug]Tabs counter isn't updated after deleting the Open Tabs browsing data

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12126]
## Prerequisites
Have a couple of open tabs
"Open Tabs" should be the only checked option in Delete browsing data

## Steps to reproduce
1. Navigate to Settings → Delete browsing data
1. Proceed with the deletion
1. Check the Tabs counter
1. Check the Open Tabs in the Delete browsing data section

### Expected behavior
Tabs counter should display 0 open tabs
The open tabs count in in the Delete browsing data section should be 0 as well

### Actual behavior
Tabs counter isn't updated, displays the previous number of open tabs
The Open Tabs count in the Delete browsing data section is 0 

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
•Nightly Build 200629 from 6/30
•Fenix 79.0.1-beta.1 from 6/30

### Notes
❗ Not reproducible using the "Delete browsing data on quit"

► Video
![20200630-142023](https://user-images.githubusercontent.com/51314259/86121250-63e9e380-bade-11ea-8c6e-5a0f4a18b975.gif)

**Comment by sflorean** [comment]
I was able to reproduce this also, following the steps:
1. Open 3 tabs.
2. Go to about:crashcontent in one tab.
3. Choose "close tab".

Expected result: the tab counter is 3. 
Actuals result: the tab counter isn't updated.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200708-105536](https://user-images.githubusercontent.com/51314259/86893340-27d00780-c10a-11ea-87ed-8e0eee0624e8.gif)

**Comment by AndiAJ** [comment]
Reproducible on **`79.0.0-beta.6 from 7/14`** using a OnePlus A3 (Android 6.0.1)

► Video
![20200714-113130](https://user-images.githubusercontent.com/51314259/87403736-ef2aa500-c5c5-11ea-80e3-b6d7a485f45c.gif)
