### ISSUE TITLE
FNX-13162 ⁃ [Bug] New tab list hides itself when scrolling bottoms out

### ISSUE THREAD

**Issue by Manishearth** [mozilla-mobile/fenix#12133]
## Steps to reproduce
Open the tab list, scroll downwards

### Expected behavior
You can scroll to the top of the tab list easily.

### Actual behavior
You have to be very careful about scrolling, scroll too hard and the tab list hides itself. I find it's not a great UX pattern for a scroll control to perform a different action when it "bottoms out", since it's very common to "bottom out" a scroll to get to the end of it, so much that iOS typically has a special stretchy animation that happens when you bottom out.

### Bad interaction with "open in new tab"
This is especially annoying for the "open in new tab case":

Let's say I have some tabs open

[<img src="https://user-images.githubusercontent.com/1617736/86147475-49981180-baae-11ea-948f-efb8b7f5313b.png" width=150>](https://user-images.githubusercontent.com/1617736/86147475-49981180-baae-11ea-948f-efb8b7f5313b.png)

I open a link in a new tab, saving it for later

[<img src="https://user-images.githubusercontent.com/1617736/86147775-a5fb3100-baae-11ea-9117-dfeeb6599601.png" width=150>](https://user-images.githubusercontent.com/1617736/86147775-a5fb3100-baae-11ea-9117-dfeeb6599601.png)

When I want to switch to it, I open the tab list, and my current page is still on top:

[<img src="https://user-images.githubusercontent.com/1617736/86147475-49981180-baae-11ea-948f-efb8b7f5313b.png" width=150>](https://user-images.githubusercontent.com/1617736/86147475-49981180-baae-11ea-948f-efb8b7f5313b.png)

I can scroll up to get to it:

[<img src="https://user-images.githubusercontent.com/1617736/86147918-d2af4880-baae-11ea-8e8d-0778e4f3f7c4.png" width=150>](https://user-images.githubusercontent.com/1617736/86147918-d2af4880-baae-11ea-8e8d-0778e4f3f7c4.png)

but if I scroll really hard (which is common, I know it's near the top of the list, so the easiest way to get there is to "bottom out" the scroll) the tab list drops out the bottom and I have to do it all over again.

[<img src="https://user-images.githubusercontent.com/1617736/86148056-fd999c80-baae-11ea-9d7c-9b6889e9e4dc.png" width=150>](https://user-images.githubusercontent.com/1617736/86148056-fd999c80-baae-11ea-9d7c-9b6889e9e4dc.png)

This might also be indicative of a different bug: when you open stuff in a new tab, it should probably already be visible in the tab list: the current focused tab should not be at the top.

### Device information
* Android device: Pixel 3
* Fenix version: 5.2.0 Build 21701706

**Comment by sheikh-azharuddin** [comment]
Fixed in nightly... Firefox might push it soon to beta build

**Comment by Manishearth** [comment]
Oh, yep, there's a stop when it bottoms out, and you need a second swipe to hide it. That's good enough!

Wondering if we should still try to fix the open in new tab issue, but I'll wait a while and try to use this for a bit before opening a more specific issue.
