### ISSUE TITLE
Tab tray empty space utilize for frequently visited sites

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12134]
### What is the user problem or growth opportunity you want to see solved?
Currently there is too much space after tab button and private tab button...this space can be utilised to add 1/2 menu --- frequently used sites/top sites and collection...

### How do you know that this problem exists today? Why is this important?
This will benefit all users to go to the frequently visited site directly from tab tray.

### Who will benefit from it?
All users

![Screenshot](https://user-images.githubusercontent.com/58127841/86150820-6dc71300-baed-11ea-87dd-04942bdcf780.jpg)UNITO-UNDERSCORE!20200630-214510~2!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2859)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812920

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
