### ISSUE TITLE
FNX-13165 ⁃ Too many touches to open a new tab

### ISSUE THREAD

**Issue by paul1764** [mozilla-mobile/fenix#12135]
### What is the user problem or growth opportunity you want to see solved?
It takes 3 touches to open a new tab, and I think it should take only 2. If you have a tab open, you touch the icon with the number of open tabs, which opens the tab list (photo 1), then the plus icon (you see photo 2), then touch in the address bar to type in a new search or address (photo 3). I think the last touch should be eliminated and touching the plus icon should immediately bring up the address bar for typing.
![preview1](https://user-images.githubusercontent.com/15822011/86151101-e5804800-bac3-11ea-9d6b-3844a68ee35f.jpeg)
![preview2](https://user-images.githubusercontent.com/15822011/86151105-e6b17500-bac3-11ea-96b5-f219985c33e2.jpeg)
![preview3](https://user-images.githubusercontent.com/15822011/86151111-e87b3880-bac3-11ea-9738-942262d7fc38.png)

### How do you know that this problem exists today? Why is this important?
I think this was changed from a previous version when the new tab list interface was first implemented. The version with fewer touches was more streamlined and easier to use.

### Who will benefit from it?
Any user who is trying to open a new tab by searching or typing an address, rather than opening a link from a collection. In my experience at least, I am rarely opening a tab from a collection.

**Comment by kbrosnan** [comment]
Duplicate #11955
