### ISSUE TITLE
Very-Completely Unresponsive and Crashing (F-Droid) [Bug]

### ISSUE THREAD

**Issue by grravity** [mozilla-mobile/fenix#12132]
## Steps to reproduce
Open "Firefox Preview", Cannot click anything (url bar, extended menu, tab icons, etc.) , completely unresponsive.
Wait a little, get a popup saying "Firefox Preview is unresponsive" with choices to "Close" or "Wait" and notice in the background, Firefox actually changed to the thing I clicked. So I click wait, now I can interact.
Few minutes later after clicking on stuff, it goes unresponsive again, wait a little and it's fine.

### Expected behavior
Be responsive.

### Actual behavior
Unresponsive/crashes.
Completely unusable.

### Things Tried
Complete reinstall, clear data & cache, clear device cache

### Device information
* Android device: Android 10, LGv40
* Fenix version: 5.2.0 (F-Droid), fresh install, have not used before this so cannot confirm if this issue was present on previous versions.

_On a sidenote, I'd like to suggest to the F-Droid maintainer, to have telemetry/data collection options/flags disabled by default on install._

**Comment by kbrosnan** [comment]
The F-droid maintainer does not [repackage or build the Firefox binary](https://gitlab.com/rfc2822/fdroid-firefox#how-does-it-work). This is why it is in a separate repo from the main Fdroid app.

To make any progress on this crash we will need a crash ID or log as described in https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by grravity** [comment]
I have not had the time to do this, if I can I will.
It'd be helpful if someone could try to reproduce this.

**Comment by kbrosnan** [comment]
Going to close this as incomplete. If more info is found a new issue is best.
