### ISSUE TITLE
[Bug] Search widget not working when minimized in tab switcher

### ISSUE THREAD

**Issue by mariomie** [mozilla-mobile/fenix#12149]
## Steps to reproduce
1. open tab switcher
1. minimize app
1. select search widget
    1. Expected behavior

* search bar selected
    1. Actual behavior
* tab switcher is selected
    1. Device information
* Android device: Huawei P30 (ELE-L29) Android 10
* Fenix version: 5.2.0 (Build #21701706)

**Comment by mcarare** [comment]
Not reproducible in the latest nightly. QA please check! TY!

**Comment by sflorean** [comment]
No reproducible on Firefox Nightly 7/3 with Samsung Galaxy Note10 (Android 10), Xiaomi Redmi Note 8T (Android 9), Huawei P10 (Android 9.1) following the steps from the description. 

@mariomie do you have some extra steps? Thank you!

**Comment by mariomie** [comment]
Based on your feedback I installed the nightly and can confirm that the issue does not exist anymore. I just have that issue with the regular preview version. So it was probably fixed already.
