### ISSUE TITLE
[Bug] [Discoverability Experiment] The popup is only dismissed after pressing "Not Now" or outside its borders twice

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#12154]
**[Affected Versions]:**

* Firefox Preview Nightly 200701 (Build #21830609) GV: 79.0a1-20200629094229

**[Affected Platforms]:**

* Android 9 (Samsung Galaxy S8)
* Android 10 (Motorola One Vision)

**[Prerequisites]:**

* The browser is open.
* You are enrolled in the “treatment_cfr” branch.
* The helper popup asking whether you want to install the widget is displayed.

**[Steps to reproduce]:**

1. Press the “Not now” button.
1. Observe the behavior of the helper popup.

**[Expected results]:**

* The popup is dismissed after one tap.

**[Actual results]:**

* The popup is only dismissed after two taps.

**[Notes]:**

* This is also reproducible when dismissing the pop-up by tapping outside it borders.

![popup not dismissed](https://user-images.githubusercontent.com/53752296/86240254-8694fe80-bba9-11ea-80b5-c40b72083345.gif)

**Comment by mcarare** [comment]
This is probably related to: https://github.com/mozilla-mobile/fenix/issues/12153, the popup might be shown twice.

**Comment by heres-maria** [comment]
After further investigation I believe mcarare is right. The behavior displayed by the pop-up across the board is consistent with the idea that the pop-up is shown twice.

**Comment by sblatz** [comment]
This is intentional :)

**Comment by heres-maria** [comment]
After a discussion on Slack with @sblatz, it seems this issue was valid. It was fixed together with #12157 and is no longer reproducible. As such, it can remain closed.
Tested on Firefox Preview Nightly 200703 (Build #21850624) (1cba216b2) GV: 80.0a1-20200701093012 using Android 9 (Samsung Galaxy S8) and Android 10 (Motorola One Vision).
