### ISSUE TITLE
FNX2-15051 ⁃ [Bug] [Discoverability Experiment] The popup is not dismissed after the user has added the widget

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#12157]
**[Affected Versions]:**

* Firefox Preview Nightly 200701 (Build #21830609) GV: 79.0a1-20200629094229

**[Affected Platforms]:**

* Android 9 (Samsung Galaxy S8)
* Android 8 (Samsung Galaxy S9)
* Android 10 (OnePlus 5)

**[Prerequisites]:**

* The browser is open.
* You are enrolled in the “treatment_cfr” branch.
* The helper popup asking whether you want to install the widget is displayed.

**[Steps to reproduce]:**

1. Press the “Add widget” button.
1. Press the “Add” option.
1. Refocus the browser (if needed).
1. Observe the behavior of the helper popup.

**[Expected results]:**

* The helper popup is no longer displayed after the user has added the widget.

**[Actual results]:**

* The helper popup is still displayed.

**[Notes]:**

* This is also reproducible if the user adds the widget by pressing on the widget icon of the Add widget prompt, dragging it in place and then refocuses the browser - as seen in [this recording](https://drive.google.com/file/d/1kepPOSOaelGEz_eATu2SWvLSlV-rzKcw/view?usp=sharing).
* This issue was not reproducible on Android 10 - Motorola One Vision.
* Probably related to #12154.

![add widget popup not dismissed](https://user-images.githubusercontent.com/53752296/86253714-94547f00-bbbd-11ea-99f7-be793313525a.gif)

**Comment by sblatz** [comment]
This one definitely needs a fix, thanks for filing!

**Comment by sblatz** [comment]
This should be fixed.

**Comment by heres-maria** [comment]
I have verified that this issue is no longer reproducible. The popup is dismissed after the user has added the widget.
Tested on Firefox Preview Nightly 200703 (Build #21850624) (1cba216b2) GV: 80.0a1-20200701093012 using Android 9 (Samsung Galaxy S8) and Android 10 (Motorola One Vision).
As a result, I am closing this issue.
