### ISSUE TITLE
FNX2-15050 ⁃ [Bug]Native code crash: [@ mozilla::ipc::BackgroundChildImpl::ProcessingError ]

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12156]
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1325918

## Steps to reproduce
1. Navigate to www.dailymotion.com/us
1. Close the tab and force close Fenix
1. Resume Fenix open again www.dailymotion.com/us in a new tab
1. Repeat a couple of time Steps 1-3

### Expected behavior
The web site should be properly loaded each time

### Actual behavior
Native code crash (crashed after trying to load the 3rd time dailymotion.com/us)

## Alternative steps to reproduce
1. Open www.dailymotion.com/us a couple of times (each time in a new tab)

### Expected behavior
The web site should be properly loaded each time

### Actual behavior
Native code crash (crashed after trying to load the 3rd time dailymotion.com/us)

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
Beta 79.0.0-beta.3 from 7/1
Nightly 200701 from 7/1

### Notes
❗ Not reproducible on the following devices:
• Samsung Galaxy Tab S6 (Android 9)
• Huawei P20 lite (Android 9)
• Huawei MediaPad M3 lite (Android 7) 

## 1st STR
Crash report: https://crash-stats.mozilla.org/report/index/85405dea-fda8-4107-aa24-770fd0200701

► Video
![20200701-144609](https://user-images.githubusercontent.com/51314259/86242866-02914580-bbae-11ea-9a40-a3d11a842dd4.gif)

## 2nd STR
Crash report: https://crash-stats.mozilla.org/report/index/7e0a2fa8-448a-4a0b-b03c-148d90200701

► Video
![20200701-145239](https://user-images.githubusercontent.com/51314259/86243514-34ef7280-bbaf-11ea-85a6-6576c2dfe308.gif)

❗ Reported today another dailymotion related issue #12155

**Comment by kbrosnan** [comment]
Fixed in Firefox 80.
