### ISSUE TITLE
[Bug] After the first scroll fling, the second one accelerates the scrolling unusually faster

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12150]
After first scroll on a any given webpage, the second fling accelerates the scrolling speed really unusually faster. I have noticed this behaviour recently and it's really frustrating (I shouldn't have discovered this bug and now I just want to forget it but can't now -- I honestly really tried, really... :sweat_smile:)!

I have recorded 2 videos one of them is on Chrome which doesn't accelerate the scroll speed unusually and another one on Fenix. On Fenix, observe it closely as I scroll for the first time on the page, the first fling scrolls the screen almost okay but the second one almost takes it to the bottom even if not much force is applied to the scroll fling; just touching the page while the page is scrolling accelerates the page scrolling speed too much faster and sometimes it almost takes it to the bottom of the page.

Both are archived ZIP files -- not GIFs -- so you can see it clearly with all frame rate, extract to see the videos.

Chrome: 
[Chrome Scroll Speed.zip](https://github.com/mozilla-mobile/fenix/files/4856831/Chrome.Scroll.Speed.zip)

Fenix:
[Fenix Scroll Speed.zip](https://github.com/mozilla-mobile/fenix/files/4856856/Fenix.Scroll.Speed.zip)

**Comment by hardycz** [comment]
I experience the same issue. This inconsistent scroll speed/acceleration is really annoying and basically the only thing that keeps me away from using FF as a daily driver.

Device: Galaxy S10e, Android 10
FF: 79.0.0-beta.4 (Build #2015749491)

**Comment by BlitW0** [comment]
Try setting the `apz.fling_accel_interval_ms` in `about:config` to a lower value than 750, I have set mine to 300 and it works well. It is the minimum interval between 2 consecutive flings required to trigger acceleration, I think. You can also set it to 0 to disable the acceleration completely.

I do feel that this should work out of the box though, it is kind of ridiculous that we have to go to `about:config` for such basic functionality.

**Comment by SS1113** [comment]
Found a relevant Bugzilla issue about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1458653

**Comment by ShatteredPixel** [comment]
I am the reporter of this issue. Please let me know if I can provide you any more information. Thanks. :)
