### ISSUE TITLE
[Bug]System media notification and Tab view media state displayed on www.dailymotion.com/us without any media being actually played

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12155]
## Steps to reproduce
1. Navigate to www.dailymotion.com/us
1. Wait a couple of seconds

### Expected behavior
No system media notification and Tab view media state should be displayed displayed

### Actual behavior
Both the System media notification and Tab view media state are displayed without any media being actually played

### Device information
* Android device: OnePlus A3 (Android 6.0.1) 
* Fenix version: 
Beta 79.0.0-beta.3 from 7/1
Nightly 200701 from 7/1

### Notes
❗ Similar with [#5634](https://github.com/mozilla-mobile/fenix/issues/5634)
► Video
![20200701-143437](https://user-images.githubusercontent.com/51314259/86242069-bdb8df00-bbac-11ea-80c3-c10340e2441e.gif)

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the 83.0.0-beta.3 with Samsung Galaxy Tab S6 (Android 10) on twitter.com.

**Comment by AndiAJ** [comment]
Still reproducible on 85.1.0-rc.1 using a OnePlus A3 (Android 6.0.1)
