### ISSUE TITLE
[Crash]  Fenix crashes when opening links from Twitter

### ISSUE THREAD

**Issue by WKSuperPower** [mozilla-mobile/fenix#12166]
## Steps to reproduce
go to Twitter app and click on a (XDA-Developers) link, then press the device's back button

### Expected behavior
Fenix should fallback to the Twitter app without any issue. More specifically, Fenix should handle the device's back button!

### Actual behavior
java.lang.IllegalStateException: at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java)

07-01 15:58:32.654 W/GeckoLinker(5659): /data/app/org.mozilla.fenix-2/lib/arm/libnss3.so: unhandled flags #8 not handled

07-01 15:58:32.664 W/GeckoLinker(5659): /data/app/org.mozilla.fenix-2/lib/arm/libnss3.so: Relocation to NULL @0x00121ffc for symbol "__cxa_type_match"

07-01 15:58:32.674 W/GeckoLinker(5659): /data/app/org.mozilla.fenix-2/lib/arm/libxul.so: unhandled flags #8 not handled

07-01 15:58:32.674 W/GeckoLinker(5659): /data/app/org.mozilla.fenix-2/lib/arm/liblgpllibs.so: unhandled flags #8 not handled

Socorro link: https://crash-stats.mozilla.org/report/index/b16227f2-53be-470f-b4b5-7ce5e0200701

### Device information
* Android device: 5.1.1
* Fenix version: 5.2.0

**Comment by ekager** [comment]
Thanks for the report! This is fixed by #11924 which will out in the next release
