### ISSUE TITLE
Intermittent UI test failure - StrictEnhancedTrackingProtectionTest.testStrictVisitContentShield

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#12161]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5775755259756697270/executions/bs.3a35aa14d22c065c/test-cases

### Stacktrace:
```java
within 45000 milliseconds. Perhaps the main thread has not gone idle within a reasonable amount of time? 
There could be an animation or something constantly repainting the screen. 
Or the activity is doing network calls on creation? See the threaddump logs. 
For your reference the last time the event queue was idle before your activity launch request was 1593564970581 
and now the last time the queue went idle was: 1593564970606. If these numbers are the same your activity might be hogging the event queue. 
```

**Comment by rpappalax** [comment]
@kbrosnan  Checking to see if this may be caused by some test-lab device issue.  I reran the test 50 x and it passed every time.  
See conversation in test-lab slack: https://firebase-community.slack.com/archives/C1MTSQ5QT/p1593632658083000

**Comment by kbrosnan** [comment]
This landed, closing issue.
