### ISSUE TITLE
FNX-13192 ⁃ [webcontent]How I can use the checked out mozilla-central as a local dependency?

### ISSUE THREAD

**Issue by fpichlou** [mozilla-mobile/fenix#12160]
How I can use a built version of mozilla-central as a local dependency in fenix?
I did the last section of README in the local properties file, but it didn't work!

**Comment by kbrosnan** [comment]
This is not a place for support. You can ask at the following places. 

* https://chat.mozilla.org/#/room/#geckoview:mozilla.org 
* https://stackoverflow.com/questions/tagged/geckoview
* https://mail.mozilla.org/listinfo/mobile-firefox-dev
