### ISSUE TITLE
FNX-4878 ⁃ address bar colors illegible when opening link from Fastmail app

### ISSUE THREAD

**Issue by heycam** [mozilla-mobile/fenix#1217]
See this screen shot. The address bar text is illegible.

![Screenshot](https://user-images.githubusercontent.com/1484434/55058532-f7e92600-50b7-11e9-8e3a-cfc5bf0b0e77.png)UNITO-UNDERSCORE!20190327-183804!

**Comment by vesta0** [comment]
Thanks for filing! This will be addressed in #1277
