### ISSUE TITLE
FNX2-15060 ⁃ Update Firefox Nightly branding to include one-line logo

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#12171]
We're cleaning up the Firefox Nightly channels, and we need to make our branding consistent there.
![Screenshot](https://user-images.githubusercontent.com/1082253/86842063-84bfb500-c059-11ea-8e9e-6a55c3937e39.png)UNITO-UNDERSCORE!20200707-135351~2!

We have the 2-line branding from before for Nightly, but need to have the 1-line version, similar to https://github.com/mozilla-mobile/fenix/issues/8278#issuecomment-637618003

cc @shorlander could you get us this updated branding? I think this should be last one, because we've already bothered you for the Production and the Beta at this point :joy:

**Comment by pocmo** [comment]
I got them from shorlander a while ago as part of the migration resources. I'll update a PR with them.

**Comment by pocmo** [comment]
Looks like this already happened here?
https://github.com/mozilla-mobile/fenix/commit/d51faea6c56b76137936d45d5df9cec7dbe9c668

**Comment by pocmo** [comment]
Hm, but I still see the old logo. Ah, looks like the vector image is not updated yet. I'll put up a PR for that :)

**Comment by sblatz** [comment]
I'm still seeing this in nightly :O Is that expected? @pocmo

**Comment by liuche** [comment]
I think this was just the launcher icon! the in-app logo (added a screenshot) still needs to be an updated asset.

**Comment by shorlander** [comment]
[Branding-Firefox-Nightly.zip](https://github.com/mozilla-mobile/fenix/files/4887772/Branding-Firefox-Nightly.zip)

This is all of the branded assets for Nightly. Including the one-line wordmark.

**Comment by NotWoods** [comment]
@shorlander Is there a corresponding vector asset for the wordmark?

**Comment by shorlander** [comment]
> @shorlander Is there a corresponding vector asset for the wordmark?

There is. Do you want just the wordmark or the logo + wordmark lockup?

**Comment by NotWoods** [comment]
Just the one line wordmark that displays the Firefox logo next to "Firefox Browser Nightly"

**Comment by shorlander** [comment]
[lockup-horizontal-svg.zip](https://github.com/mozilla-mobile/fenix/files/4903809/lockup-horizontal-svg.zip)

@NotWoods let me know if those work.

**Comment by NotWoods** [comment]
Yes, these should work

**Comment by ekager** [comment]
@NotWoods do you have a WIP for this?

**Comment by NotWoods** [comment]
Yes, I'll put it up
