### ISSUE TITLE
FNX-4879 ⁃ App freezes with an about: page opened

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1218]
## Steps to reproduce
1. Open a tab and go to about:about, about:crashes or other about pages.
1. Tap the tabs view button.
1. Close & restart the app.
    1. Expected behavior
About: pages shouldn't freeze the app.
    1. Actual behavior
At step 2, the homescreen is empty, no saved sessions displayed, no tabs.
App freezes.
After restart, there is only one tab displayed, the about: page.
Close the about: page tab and the other saved sessions will be displayed.

*If there are other tabs already opened before these STR, they will be displayed along with saved sessions after a restart.

### Device information
* Android device: Pixel, Nexus 5(Android 6)
* Fenix version: 3/26 build.

**Comment by vesta0** [comment]
@sv-ohorvath please verify that this has been fixed.

**Comment by bsurd** [comment]
This is no longer reproducible, tested on a Pixel, HTC 10, OnePlux 5T and Oana also confirmed on the Nexus 5.
