### ISSUE TITLE
FNX2-15068 ⁃ [Bug] Android toolbar uses white background even when the icons are white too

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#12189]
## Steps to reproduce
Start Fenix

### Expected behavior
Android toolbar at the bottom should have dark background and white icons, or white background and dark icons

### Actual behavior
background and icons are using the same (white) color

### Device information
* Android device: honor 7
* Fenix version: Nightly 200702, GV, 79.0a1-20200629094229

**Comment by manan025** [comment]
I would like to work on this issue.

**Comment by kbrosnan** [comment]
@sblatz you have been working on themes is this something you know about?

**Comment by Diana-Rus** [comment]
Hello, this issue should be fixed as mentioned in last comment from bug #12058 , now the android navigation system should be visible for the users when the app has light mode, dark mode applied or when used in private mode.

@smaug----  - Could you please check on you device as well with the latest Nightly?

Note; I'll leave this issue opened until further info.

**Comment by Diana-Rus** [comment]
I've come with an update based on my verification on multiple devices there are some inconsistencies around navigation bar color:
 - in Light mode for Sony Xperia Z5 (Android 7) the navigation bar color is black and the buttons are white - with and without tabs tray opened 

<details closed><summary>Sony</summary>

![20200716-125220](https://user-images.githubusercontent.com/49859863/87666990-49686900-c772-11ea-89f7-34a6422521b8.gif)
</details>

 - in Light mode with Samsung Galaxy S9 (Android 8) the navigation bar color is white and the buttons are gray - with and without tabs tray opened

<details closed><summary>Samsung</summary>

![20200716-125526](https://user-images.githubusercontent.com/49859863/87666996-4c635980-c772-11ea-9ad5-622190b0a391.gif)
</details>

Note:
- The same case as for Samsung Galaxy S9 (Android 8) is applied for Google Pixel 3 XL (Android 9)

**Comment by smaug----** [comment]
Looks ok now on my phone. Black background and light gray buttons.
I hope there are some tests for this so that we don't regress the behavior again. This wasn't the first time this occurred.

**Comment by Diana-Rus** [comment]
Issue is reproducible on Firefox 79.0.2 with Samsung Galaxy S9 (Android 8).
