### ISSUE TITLE
FNX-4880 ⁃ [Bug] App freezes when a tab is crashed and crash reporter is turned off

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1219]
## Steps to reproduce
1. Go to Settings>Data choices and turn off Crash reporter.
1. Ope a new tab and go to about:crashcontent.
    1. Expected behavior
The tab crashed image is displayed.
    1. Actual behavior
A blank page is displayed and the app stops responding.
    1. Device information

* Android device: Pixel, Nexus 5.
* Fenix version: 3/27 build

**Comment by boek** [comment]
@sblatz we can talk about this one :)

**Comment by bsurd** [comment]
The issue is no longer reproducible. Tested with a Pixel, Htc 10 and OnePlus 5T.
