### ISSUE TITLE
[Bug] [Synced tabs] The list of opened tabs are not displayed after restarting the app and accessing Synced tabs

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12195]
### Preconditions:
Sign in with valid credentials on one or two mobile devices and on desktop.
Open several tabs on each device.
Trigger sync.

## Steps to reproduce
1. Launch Fenix;
1. Remove Fenix from Recent apps;
1. Launch Fenix and from the three-dot menu go to Synced tabs;
1. Observe the Synced tabs information.
    1. Expected behavior
The Synced tabs page opens displaying the connected devices and a list with the opened tabs on each device.
    1. Actual behavior
"Connect with a Firefox Account." text is displayed.  Then a second text is displayed: "You don't have any tabs open in Firefox on your other devices."
Going to Settings, the logged in email address is not displayed, only "Firefox Account".
    1. Notes:
This is not reproducible after restarting Fenix and going to Settings first.
![20200702](https://user-images.githubusercontent.com/48799384/86353657-48164700-bc70-11ea-8b57-58df173d7216.gif)UNITO-UNDERSCORE!142426!

### Device information
* Android device: Motorola Moto G6 (Android 8), Huawei P20 lite (Android 9), Samsung Galaxy Tab S6 (Android 9);
* Fenix version: Fenix Beta 79.0.0-beta.4 GV 79 from 7/1.

**Comment by BranescuMihai** [comment]
Progress: So the problem is that the user clicks the sync tabs page while the auth flow is in progress. Currently this is not handled in the code and always displays an error first.

I decided to wait until https://github.com/mozilla-mobile/android-components/pull/7856 is landed, since that PR refactors the whole sync flow and gives access to an internal state (auth in progress) that we need

**Comment by Mugurell** [comment]
Seems like this is blocked until at least mid September - https://github.com/mozilla-mobile/android-components/pull/7856#issuecomment-680226831

**Comment by bifleming** [comment]
Fix for related bug was merged 2 days ago.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200925 06:01 GV 83.0a1 from 9/25 with Motorola Moto G6 (Android 8).
![20200925_112539](https://user-images.githubusercontent.com/48799384/94245021-5c41ab80-ff22-11ea-8f74-26db604f3252.gif)
