### ISSUE TITLE
[Bug] [Discoverability Experiment] The last screen displayed before focusing/launching Firefox is wrongly displayed after adding the search widget

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#12192]
**[Affected Versions]:**

* Firefox Preview Nightly 200702 (Build #21840611) (14d09cc4a) GV: 79.0a1-20200629094229

**[Affected Platforms]:**

* Android 9 (Samsung Galaxy S8)
* Android 8 (Samsung Galaxy S9)

**[Prerequisites]:**

* The browser is open.
* You were on the app drawer screen before launching Firefox.
* You are enrolled in the “treatment_cfr” branch.
* The helper popup asking whether you want to install the widget is displayed.

**[Steps to reproduce]:**

1. Press the “Add widget” button.
1. Press the “Add” option.
1. Observe the screen you are directed to.

**[Expected results]:**

* The homescreen where the search widget has been added is displayed.

**[Actual results]:**

* The last screen displayed before accessing Firefox is displayed - in this case the app drawer.

**[Note]:**

* If the user launches or refocuses the app from another screen (e.g. homescreen - screen 2 of 3), after adding the widget that screen will be displayed.
* This issue is not reproducible on Android 10 (Motorola One Vision, OnePlus 5). 

![app drawer](https://user-images.githubusercontent.com/53752296/86351038-45195780-bc6c-11ea-830b-92da2ae0947c.gif)

**Comment by sblatz** [comment]
Does this happen on all devices? I'm guessing this is only on certain older versions of android?

**Comment by sblatz** [comment]
@vesta0 @liuche are we okay launching the experiment with this bug? I'm not sure how much extra work it is to fix this or if we'd be able to get it in before Tuesday.

**Comment by sblatz** [comment]
Oh, this is not with older devices, my mistake. This is only happening if a user launches Fenix from the app drawer. I don't know if we could have a solution for this by Tuesday, so the question stands: 

Should we launch with this bug or delay experiment?

**Comment by heres-maria** [comment]
I have retested this issue on  Firefox Preview Nightly 200703 (Build #21850624) (1cba216b2) GV: 80.0a1-20200701093012 using Android 9 (Samsung Galaxy S8) and Android 10 (Motorola One Vision).

The two devices displayed different behaviors:
- Android 9 (Samsung Galaxy S8): After tapping "Add", the browser remained focused and a message informing the user that the widget was added was displayed. 
- Android 10 (Motorola One Vision): After tapping "Add", the browser remained focused, but there was no message displayed. When the user exits the app to the homepage, they are redirected to the homepage screen where the widget was added.

@sblatz Can you please confirm this is the expected behavior?

**Comment by sblatz** [comment]
Fixed by https://github.com/mozilla-mobile/fenix/pull/12204
