### ISSUE TITLE
FNX2-15074 ⁃ [Bug] Dark purple bar in the top of Webview

### ISSUE THREAD

**Issue by paritosh9199** [mozilla-mobile/fenix#12196]
I am facing an issue where when ever a link opens from other apps into the Webview I see a dark purple ish bar at the top. It dosen't go away, it just stays there.

**Comment by paritosh9199** [comment]
Here is a link to the snapshot https://photos.app.goo.gl/kSaUECSpRi7qvQdJ7

**Comment by paritosh9199** [comment]
Here is a link to the snapshots 
https://photos.app.goo.gl/kSaUECSpRi7qvQdJ7

**Comment by kbrosnan** [comment]
What version of Fenix are you using @paritosh9199?

**Comment by sheikh-azharuddin** [comment]
This is fixed in nightly few days ago...maybe not yet pushed to beta

**Comment by paritosh9199** [comment]
@kbrosnan Firefox 78.0.0-beta.1 (Build #2015748427)

**Comment by paritosh9199** [comment]
Facing the same issue in Firefox Preview 5.2.0 (Build #21701706)

**Comment by sheikh-azharuddin** [comment]
Try nightly build

**Comment by kbrosnan** [comment]
Duplicate of #11708 which is fixed in Nightly builds.

**Comment by paritosh9199** [comment]
@sheikh-azharuddin There are two versions, Firefox nightly and Firefox Preview nightly. Which one should I download?

**Comment by sheikh-azharuddin** [comment]
Both are same bro....not sure why they have 2 versions... confusing for users...

Better to download the latest apk from below link. It takes time to publish in playstore but from this link you will get the updated one....updates are released twice a day 6am GMT and 6pm GMT... 

https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest

**Comment by paritosh9199** [comment]
@sheikh-azharuddin Thanks a lot!

**Comment by paritosh9199** [comment]
Why is this open again? I am closing it.
