### ISSUE TITLE
[BUG] Toolbar stays in light colour

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#12205]
When opened links from another apps like telegram, the link opens in fenix but the toolbar doesn't follow dark theme even if it's turned on in fenix settings.

Steps to reproduce: open any link from another app, say telegram, select Firefox Nightly in Browser selection popup and see the bug.

Fenix version: 

Nightly 200702 06:03 (Build #2015749619)
AC: 49.0.20200701130905, 14d09cc4a
GV: 79.0a1-20200629094229
AS: 61.0.7
Device: Xiaomi Redmi Note 4, Android 7.0, MIUI11

SCREENSHOT: https://photos.app.goo.gl/6zohJHEJppwXs1Jf8

**Comment by ekager** [comment]
The photo is gone now. 
Are you still seeing this @RealGJ ? And are you referring to a custom tab?

**Comment by RealGJ** [comment]
@ekager I think, I deleted photo by mistake! But good news is the issue isn't there!


Thank You and Closing the Issue!🙏
