### ISSUE TITLE
[Bug] Language screen should display its "Follow Device Language" label **in the device language**

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#12206]
## Steps to reproduce
1. Open settings
1. Change the language to Basque (or any foreign language that you don't understand).  This is really easy to do by accident, if you mis-tap the "Language" menu item a few times (and the last tap hits some arbitrary language option).
1. Now try to get Fenix back to your preferred language. (in particular, try to get it back to matching the device language)

### Expected behavior
The first menu option for "Use the device language" (which is a high-probability use case) should be **shown in the device language**, to maximize the likelihood that the user will be able to read & understand that option.

### Actual behavior
The first menu option is simply shown as "Erabili gailuaren hizkuntza".  Unless the user speaks Basque, they're unlikely to tap that menu item because who knows what it does.  If they're English-speaking, the only safe-feeling option is to anxiously scroll through the list until you find English (several screen-heights down) and tap that; this is unnecessary extra work and anxiety when the first menu item is what they really want if only they could understand what it says.

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 200701

**Comment by dholbert** [comment]
Note: "Use the device language" can also be shown in the currently-selected language [Basque in my case], as it currently is.  My suggestion here is that it should **also be shown in the device language** (e.g. on a second line, as seems to happen for every other entry in this list).

**Comment by dholbert** [comment]
Here's a screenshot showing how this looks (after selecting Basque):
![Screenshot_20200702-100951](https://user-images.githubusercontent.com/426803/86390119-5c484d00-bc4c-11ea-9fc4-986f91c6cc46.png)

Unless the user has carefully studied this menu, they have no way of knowing what do do here (other than scroll frantically looking for "English" or their preferred language); there's no way for them to know that the first menu item is likely really what they want.

**Comment by mcarare** [comment]
@dholbert You can easily find the language you want to select by using the search menu in the action bar (top bar). Also, follow device language is always the first option in the list, no matter what language is currently selected.

**Comment by cadeyrn** [comment]
> Also, follow device language is always the first option in the list, no matter what language is currently selected.

That's true but if you don't know it then it won't help you. Yes, there is also a search field but I agree that this specific menu item should follow the device language to reduce user frustration.

**Comment by dholbert** [comment]
> You can easily find the language you want to select by using the search menu in the action bar (top bar).

I'm not sure about "easily". :)   Personally I hadn't noticed that magnifying glass -- and even if I had noticed it, I wouldn't have felt comfortable tapping it, because it's labeled something like "Լեզու" as shown in the screenshot below. And I'm not especially confident about what's going to happen if I tap "Լեզու" (particularly if I've just caused all of my browser-text to become unreadable and I'm trying my best not to make things worse):
![image](https://user-images.githubusercontent.com/426803/86485873-b7db0f00-bd0e-11ea-832b-5e8e01722182.png)

>  follow device language is always the first option in the list, no matter what language is currently selected.

Echoing @cadeyrn, this is handy once you know it.  But for users who change their language by accident (which again, is really easy to do - just tapping once on "Language" and then basically tap anywhere on the screen), they will not know this & will simply be staring at a screen of unreadable text, if they can even find their way back to this Language picker in the first place.

**Comment by s-ankur** [comment]
Also, searching is impossible after you change to certain languages #12487

**Comment by dholbert** [comment]
This is still an issue.

**Comment by dholbert** [comment]
This is essentially fixed, I think.

The "Follow Device Language" label itself is still translated & displayed using the currently-selected language (e.g. Basque in my STR); **but we now display an additional label below that, to tell you what the device language is, and we seem to render that line using the device language**.  So in my case, I now see:
> [illegibile string of characters, which mean "Follow Device Language" in some foreign language]
> English (United States)

This addresses the use case of oops-I-changed-my-Firefox-language-and-now-I-can't-easily-get-back (which is what prompted me to file this issue), so I think we can close this.

**Comment by dholbert** [comment]
Here's a screenshot showing how this looks now, in Nightly 93.0a1 (Build #2015829867):

![Screenshot_20210824-160619](https://user-images.githubusercontent.com/426803/130701338-6727fed2-66c0-4a38-b3b8-784962022118.png)
