### ISSUE TITLE
[Telemetry] Report add-on versions in add-on ping

### ISSUE THREAD

**Issue by jvillalobos** [mozilla-mobile/fenix#12202]
## Description & Product Manager / Data Scientist User Story
Follow up to https://github.com/mozilla-mobile/fenix/issues/8920 and [bug 1643683](https://bugzilla.mozilla.org/show_bug.cgi?id=1643683). AMO has a per-add-on stats dashboard that is used to monitor various usage metrics and give developers useful data to make product decisions. We recently [changed the data source](https://blog.mozilla.org/addons/2020/06/10/improvements-to-statistics-processing-on-amo/) to use telemetry data and want to include Fenix data.

The ping introduced in https://github.com/mozilla-mobile/fenix/issues/8920 gives us everything we need except the add-on version, which is an important way to slice the data.

## What questions will you answer with this data?
Which add-on **versions** are installed by Fenix users?

## Acceptance Criteria
* [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
* [ ] DS sign off on instrumentation methodology addressing product questions.
* [ ] Event pings can be queried via re:dash
* [ ] Event pings can be queried via amplitude
* [ ] We are sending telemetry events for the actions listed in the requirements
* [ ] We have documented the telemetry
* [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by eliserichards** [comment]
Needs eng ticket filed for Marissa to review

**Comment by sblatz** [comment]
I will touch base with Marissa about this on Friday 😄

**Comment by eliserichards** [comment]
Closing in favor of #13322

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

🚩 Flag added

https://github.com/mozilla-mobile/fenix/issues/13322
