### ISSUE TITLE
[Bug] Some website can't back

### ISSUE THREAD

**Issue by cathaysia** [mozilla-mobile/fenix#12219]
## Steps to reproduce
1. Step into https://vip.sdmxgt.com:168/index.html?u=80760#

Emm, this website is a sex website.

1. Then, you press back press.

### Expected behavior
Back pre page, or close this page.

### Actual behavior
It is no work.

### Device information
* Android device: android 7.1
* Fenix version: 5.2.0

**Comment by kbrosnan** [comment]
Duplicate #8180
