### ISSUE TITLE
FNX-4882 ⁃ [Bug] Crash reports do not display in about:crashes

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1221]
## Steps to reproduce
Crash reporter is turned ON:

1. Go to about:crashcontent, to crash a tab.
1. Check the report on about:crashes.
1. Go to about: crashparent to crash the app.
1. Check the report on about:crashes.

Crash reporter is OFF:

1. Go to about:crashcontent, to crash a tab.
1. Check the report on about:crashes.
1. Go to about: crashparent to crash the app.
1. Check the report on about:crashes.
    1. Expected behavior
Both app & tab crash reports appear under the submitted reports, when the crash reporter is On.
None appear in about:crashes when the crash reporter is Off.
    1. Actual behavior
The crash report from the tab crash is displayed in about:crashes but it's not submitted, in both cases.
The crash report from the app crash is not displayed in the list in both cases.
    1. Device information

* Android device: Pixel, Nexus 5
* Fenix version: 3/27 build

**Comment by boek** [comment]
@cpeterso How does data get into `about:crashes`?

**Comment by cpeterso** [comment]
> @cpeterso How does data get into `about:crashes`?

I don't know.

@snorp, where does GV's `about:crashes` look for crash reports? Should `about:crashes` show crash reports just for the current app or for all GV-powered apps on the phone? On desktop, `about:crashes` shows crash reports for all Firefox installs and user profiles, not just the current install and user profile.

**Comment by sblatz** [comment]
The reports _are_ sent to Sentry (I confirmed this when working on the feature. I believe this is an issue of `about:crashes` not reflecting what Sentry sees. Updating the title for clarification.

**Comment by snorp** [comment]
GeckoView apps doesn't use `about:crashes` because the report submission is handled by the app.

**Comment by boek** [comment]
@snorp Should we prevent access to `about:crashes` then?

**Comment by cpeterso** [comment]
> @snorp Should we prevent access to `about:crashes` then?

That's probably a good idea. Fenix *does* display an `about:crashes` page that misleadingly says "No crash reports have been submitted." That looks like Gecko's [no-reports-label](https://searchfox.org/mozilla-central/rev/3d469329a42644b41e66944d8da22d78d8c0f5ec/toolkit/locales/en-US/crashreporter/aboutcrashes.ftl#24) string. Maybe it it GV, not Fenix, that needs to stop pretending it supports `about:crashes`?

**Comment by sv-ohorvath** [comment]
I had the impression that reports sent to Socorro we're the ones visible on about:crashes. Should I, or could I check the reports sent to Sentry/Socorro in other ways?

**Comment by pocmo** [comment]
Since GeckoView doesn't know about all crashes it can't display them in `about:crashes`. However the "crash reporter" component does and we have the following issue about providing an "about:crashes"-like UI in the component (but that's probably not going to happen in the MVP timeframe):

https://github.com/mozilla-mobile/android-components/issues/1705

**Comment by cpeterso** [comment]
I filed a GV bug requesting GV disable its `about:crashes` page to avoid user confusion. If Fenix wants to support `about:crashes`, it can write its own `about:crashes` handler and show the Socorro and Sentry crash reports it has caught and submitted.

https://bugzilla.mozilla.org/show_bug.cgi?id=1541152
