### ISSUE TITLE
FNX2-15088 ⁃ [Bug] Crash on startup

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12214]
## Steps to reproduce
My device language is Turkish but auto fill not working on Turkish, so i need to change Fenix lang to English. #7742
1- change Fenix lang to English united States
2- restart Fenix to allow change default search engines
3- change search engines
Mine: 1- google 2- YouTube, just this
4- close app and use as normal

On first startup after this str there is no crash (cache?) but after some time app starts to crash. Crashes nearly every startup.

![Screenshot](https://user-images.githubusercontent.com/17825767/86413414-d965d780-bcc9-11ea-8107-864534ef79af.jpg)UNITO-UNDERSCORE!20200703-010445!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly.jpg!

https://crash-stats.mozilla.org/report/index/6364a7cd-fa5f-493a-bf67-6d78f0200702

### Expected behavior
Works fine.

### Actual behavior
Crashes

### Device information
* Android device: XZ1 Android 10
* Fenix version: 7/2 org.mozilla.fenix

**Comment by Augures01** [comment]
Duplicate? #11985

**Comment by hakkikaancaliskan** [comment]
Yes, looks like it is, I've also added str for this issue.

**Comment by hakkikaancaliskan** [comment]
**Adding amazon to the list fixes issue and also amazon shown on search bar on startup**
