### ISSUE TITLE
[Bug] Send tab to Fenix not receiving it automatically anymore

### ISSUE THREAD

**Issue by scheinercc** [mozilla-mobile/fenix#12218]
## Steps to reproduce
Send a tab from Firefox desktop (tested with Dev Edition and Nightly) to Fenix.

### Expected behavior
Tab arrives kind of right away on device.

### Actual behavior
Tab doesn't arrive on device.
I wait a while, then I open `Settings > Account` where it right away changes to "Synchronising ..."  grey out, but the tab still doesn't appear. Only if I wait until that sync is done and tab on "Synchronise now" manually, then it comes through right away.

### Device information
* Android device: Fairphone 2; Android 7.1.2
* Fenix version: 5.2.0 (Build #21701705)

### Note
The other way around works fine and so does "send tab" from desktop to desktop for me.

**Comment by sv-ohorvath** [comment]
Thanks for your report, you can follow https://github.com/mozilla-mobile/fenix/issues/8582 as it contains the same issue.

**Comment by scheinercc** [comment]
Fair enough @sv-ohorvath :) I only skimmed over the other ticket and a saw a lot of examples sending to multiple dives at ones and sending collections, so I thought it might be slightly different. Thanks for checking!
