### ISSUE TITLE
FNX2-15087 ⁃ [Bug]Too small Firefox logo on org.mozilla.fenix

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12212]
![Screenshot](https://user-images.githubusercontent.com/17825767/86409123-f053fc00-bcc0-11ea-9d29-be4434da3eb4.jpg)UNITO-UNDERSCORE!20200702-224928!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly.jpg!

### Device information
* Android device: Android 10 XZ1
* Fenix version: 2/7

**Comment by liuche** [comment]
dupe of #12171
