### ISSUE TITLE
change download notification progress color

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12226]
### What is the user problem or growth opportunity you want to see solved?
Please change the download progress and buttons color to purple to match with Firefox theme... Currently it shows green.

### How do you know that this problem exists today? Why is this important?
It should match Firefox theme

### Who will benefit from it?
All users.. aesthetically pleasing.

![Screenshot](https://user-images.githubusercontent.com/58127841/86447916-9295d300-bd05-11ea-8cd1-769308ad30b0.jpg)UNITO-UNDERSCORE!20200703-121802!

**Comment by AmyYLee** [comment]
I agree we should be using Fenix colours. @brampitoyo for confirmation.

Light Theme Color: Violet 70 (#592ACB)
Dark Theme Color: Violet 40 (#AB71FF)

**Comment by sheikh-azharuddin** [comment]
One more suggestion apart from changing text and progress color to purple is it possible to change the background of the download notification panel to light purple something like tab tray selected tab background color as per as below screenshot ... It looks really good in other apps and also notification will stand out from others..
![Screenshot_20200707-124144~2](https://user-images.githubusercontent.com/58127841/86734056-35f62900-c021-11ea-9bc1-d10b79d7acb1.jpg)


![Screenshot_20200707-124117](https://user-images.githubusercontent.com/58127841/86733859-0fd08900-c021-11ea-9216-2c042eca07b3.jpg)

**Comment by brampitoyo** [comment]
@AmyYLee I agree that we should use Fenix’s colour scheme, on light and dark theme.

As far as I know, we only have limited control over the colour of our notification shade. It’s controlled by Android System. If the System theme is set to dark, then I think that we have to follow that.

So in these mockups below, I have posted both the light and dark variant.

Light theme:

- Surface: White `#ffffff`
- Text and icon: Ink 80 `#20123a` (if possible – it seems like it might not be possible; can we confirm?)
- Accent (for text buttons and progress bar): Violet 70 `#592acb`

Dark theme:

- Surface: Dark Grey 50 `#32313c`
- Text and icon: Light Grey 5 `#fbfbfe`
- Accent: Violet 40 `#ab71ff`

<img width="360" src="https://user-images.githubusercontent.com/51007/86875673-2a952180-c137-11ea-8db3-03fa49f20d09.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/86875675-2bc64e80-c137-11ea-8824-8e7aa8390db3.png">

I tried @sheikh-azharuddin’s suggestions of changing the background colour of our notification (thanks for this idea – it’s sensible!), but couldn’t find a lighter coloured background that still maintains good accessibility contrast (WCAG 2.0) with our violet, and that fits our user interface visual style (which is quite neutral).

So in the end, I don’t recommend changing the colour to any value other than the above.

**Comment by sheikh-azharuddin** [comment]
This is good and looks better👍

**Comment by AmyYLee** [comment]
> @AmyYLee I agree that we should use Fenix’s colour scheme, on light and dark theme.
> 
> As far as I know, we only have limited control over the colour of our notification shade. It’s controlled by Android System. If the System theme is set to dark, then I think that we have to follow that.
> 
> So in these mockups below, I have posted both the light and dark variant.
> 
> Light theme:
> 
>     * Surface: White `#ffffff`
> 
>     * Text and icon: Ink 80 `#20123a` (if possible – it seems like it might not be possible; can we confirm?)
> 
>     * Accent (for text buttons and progress bar): Violet 70 `#592acb`
> 
> 
> Dark theme:
> 
>     * Surface: Dark Grey 50 `#32313c`
> 
>     * Text and icon: Light Grey 5 `#fbfbfe`
> 
>     * Accent: Violet 40 `#ab71ff`
> 
> 
> <img alt="" width="360" src="https://user-images.githubusercontent.com/51007/86875673-2a952180-c137-11ea-8db3-03fa49f20d09.png"> <img alt="" width="360" src="https://user-images.githubusercontent.com/51007/86875675-2bc64e80-c137-11ea-8824-8e7aa8390db3.png">
> 
> I tried @sheikh-azharuddin’s suggestions of changing the background colour of our notification (thanks for this idea – it’s sensible!), but couldn’t find a lighter coloured background that still maintains good accessibility contrast (WCAG 2.0) with our violet, and that fits our user interface visual style (which is quite neutral).
> 
> So in the end, I don’t recommend changing the colour to any value other than the above.

Looks good! Thanks

**Comment by sheikh-azharuddin** [comment]
This looks really beautiful and match perfectly with Firefox theme... Please implement  as soon as you can😊
Thanks for bringing my imagination to life 😅

**Comment by sheikh-azharuddin** [comment]
Hi all
Any news about the implementation?

**Comment by Amejia481** [comment]
Sorry @sheikh-azharuddin we haven't had time to pick this bug as we are still working on issues with higher priority. If you want to give it a try I can help up throughout the needed changes  :)

**Comment by sheikh-azharuddin** [comment]
> Sorry @sheikh-azharuddin we haven't had time to pick this bug as we are still working on issues with higher priority. If you want to give it a try I can help up throughout the needed changes :)

Hi Arturo thanks for the update
Actually i am a normal end user which some background of coding and scripting (powershell)😅

If you still feel I can do it please guide me...

**Comment by Amejia481** [comment]
> > Sorry @sheikh-azharuddin we haven't had time to pick this bug as we are still working on issues with higher priority. If you want to give it a try I can help up throughout the needed changes :)
> 
> Hi Arturo thanks for the update
> Actually i am a normal end user which some background of coding and scripting (powershell)😅
> 
> If you still feel I can do it please guide me...

Sorry for the late reply. If you are new to Android it will be a bit challenging but not impossible to achieve :) 

1. If new first download [Android studio](https://developer.android.com/studio).
2. Take a look to the contributing section on the [android components website ](https://mozac.org/contributing/).
3. For changing the style colour on the notification, we need to expose an styling object from AC that Fenix can pass to the [AbstractFetchDownloadService](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L84) similar to what we are doing on [AddonsManagerAdapter#Style](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L328).
4. Pass the style to [DownloadNotification](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L317) each notification type.
5. On [DownloadNotification](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt#L36) we are using the default Android notifications, I'm not completely sure if the super that level of customization [described above](https://github.com/mozilla-mobile/fenix/issues/12226#issuecomment-656771900), I see [we can customize the colour](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt#L63), I not sure about the other properties, if the default android notification doesn't allow all that customization then it will be more complicated as we will have to [create our own download notification](https://developer.android.com/training/notify-user/custom-notification).

Do not feel forced to take on the challenge, but if you do I'm happy to help you along the way :)

**Comment by hakkikaancaliskan** [comment]
> 
> 
> > > Sorry @sheikh-azharuddin we haven't had time to pick this bug as we are still working on issues with higher priority. If you want to give it a try I can help up throughout the needed changes :)
> > 
> > 
> > Hi Arturo thanks for the update
> > Actually i am a normal end user which some background of coding and scripting (powershell)😅
> > If you still feel I can do it please guide me...
> 
> Sorry for the late reply. If you are new to Android it will be a bit challenging but not impossible to achieve :)
> 
>     1. If new first download [Android studio](https://developer.android.com/studio).
> 
>     2. Take a look to the contributing section on the [android components website ](https://mozac.org/contributing/).
> 
>     3. For changing the style colour on the notification, we need to expose an styling object from AC that Fenix can pass to the [AbstractFetchDownloadService](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L84) similar to what we are doing on [AddonsManagerAdapter#Style](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L328).
> 
>     4. Pass the style to [DownloadNotification](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L317) each notification type.
> 
>     5. On [DownloadNotification](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt#L36) we are using the default Android notifications, I'm not completely sure if the super that level of customization [described above](https://github.com/mozilla-mobile/fenix/issues/12226#issuecomment-656771900), I see [we can customize the colour](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadNotification.kt#L63), I not sure about the other properties, if the default android notification doesn't allow all that customization then it will be more complicated as we will have to [create our own download notification](https://developer.android.com/training/notify-user/custom-notification).
> 
> 
> Do not feel forced to take on the challenge, but if you do I'm happy to help you along the way :)

I really want this and want to work on this :)
I'm absolutely unsure I can handle this lol

**Comment by hakkikaancaliskan** [comment]
@Amejia481 https://developer.android.com/training/notify-user/custom-notification#custom-content with this we're able to just manage colored area. Looks like we need [full custom widget layout](https://developer.android.com/training/notify-user/custom-notification#create_a_fully_custom_notification_layout) :(
![Screenshot_20200718-004750_Firefox_Preview](https://user-images.githubusercontent.com/17825767/87833426-7d39b080-c890-11ea-8ec7-06f1d63e1dd8.png)

**Comment by hakkikaancaliskan** [comment]
Ok, we're getting closer, looks like it's possible to design however we want but there will be layout inconsistencies? I really don't know.
<img src="https://user-images.githubusercontent.com/17825767/87835059-c429a500-c894-11ea-8c8b-48b80256469b.png" width="300">

**Comment by hakkikaancaliskan** [comment]
I've worked on this but after a second thought, maybe we "should" use Android's default.
Because look to the caution at the end of the page https://developer.android.com/training/notify-user/custom-notification.

Chrome also using default without "any" modification.

@Amejia481 we shouldn't take this risk, this can cause instability, layout inconsistencies, unexpected crashes, performance impacts. What do you guys think?

**Comment by shahsurajk** [comment]
Wouldn't this be a part of the  android-components repo?

**Comment by hakkikaancaliskan** [comment]
> Wouldn't this be a part of the  android-components repo?

Yes this is part of ac. Already there is pr for this in ac. https://github.com/mozilla-mobile/android-components/pull/7763

**Comment by brampitoyo** [comment]
@hakkikaancaliskan I am worried about layout inconsistencies, and the fact that we’re not following Android System standard. It means that we will need to keep maintaining our custom component in case of system-wide changes, instead of focusing on other important problems.


The risk of designing our own notification useful to restate:

> …your notification will not match the rest of the notifications and it can cause significant layout compatibility issues on different devices that apply different styling to the notification area.

It seems like Android wants different devices to handle the styling, and as an app, our policy should be to “follow device”. I’d like to follow the official platform recommendation.

Then, is there no element that can be customised? For example, accent colour must always follow device and not manually selected by the app.

If there’s no further customisation possible, then I recommend closing this issue.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo We could follow accent color based on fenix's theme but android theme could be different and could cause contrast issues.

**Comment by sheikh-azharuddin** [comment]
@brampitoyo Wait I don't understand what's wrong with the earlier implementation of purple color?? The one which you gave earlier? No offense but that hakki guy is a noobie.Inspired by amejia android guide tried with few implementation and when cannot gave a proper design highlighted the risk....

Even youtube is changing the notification color and background in Firefox here no one has any problem...the download notification is part of Firefox and I seriously believe you should design to match with Firefox theme... Purple and white/gray.

**Comment by sheikh-azharuddin** [comment]
![Screenshot_2020-07-20-10-38-02-34](https://user-images.githubusercontent.com/58127841/87901783-8768d400-ca75-11ea-9624-9ae528931f63.png)

**Comment by hakkikaancaliskan** [comment]
> @brampitoyo Wait I don't understand what's wrong with the earlier implementation of purple color?? The one which you gave earlier? No offense but that hakki guy is a noobie.Inspired by amejia android guide tried with few implementation and when cannot gave a proper design highlighted the risk....
> 
> Even youtube is changing the notification color and background in Firefox here no one has any problem...the download notification is part of Firefox and I seriously believe you should design to match with Firefox theme... Purple and white/gray.
> 
> 
> 
> 
> 

Vaov, noobie? Look at the pr i made. I did but i and Google don't recommend using custom notifications. For example on my device, grey notification looks awful because all notifications black, and Fenix grey.
We're talking about engineering side. If you don't know, please don't talk.

**Comment by hakkikaancaliskan** [comment]
> ![Screenshot_2020-07-20-10-38-02-34](https://user-images.githubusercontent.com/58127841/87901783-8768d400-ca75-11ea-9624-9ae528931f63.png)
> 

That's "media" notification and android controlling manually.

**Comment by hakkikaancaliskan** [comment]
@Amejia481 what do you think from engineering side, there is layout inconsistencies even on my device, (grey notification while others black). If wanna work on this further I'll go on but i really don't recommend this. Let Android handle this as other ALL apps do.

**Comment by sheikh-azharuddin** [comment]
> 
> That's "media" notification and android controlling manually.
> That's not custom, same on all apps, that's provided by android.

Nope then tell me when I am playing same video in chrome and Firefox why the color is different...if it's android it should show the same color but I strongly believe this is how the website treating and changing the notification color and background....
![Screenshot_2020-07-20-10-48-09-90](https://user-images.githubusercontent.com/58127841/87902297-dcf1b080-ca76-11ea-8c79-91a6844443ea.png)
![Screenshot_2020-07-20-10-48-27-90](https://user-images.githubusercontent.com/58127841/87902305-e1b66480-ca76-11ea-81d0-f807a685a267.png)

**Comment by hakkikaancaliskan** [comment]
We should think how will look this on Xiaomi, Poco, Samsung, Huawei... Nearly all of them using different look on notifications. We can't adopt all of them. Think about what will happen on reddit lol.
Yes I'm noobie. Do better and eng guys wil be happy to merge. Don't even know media notification is provided by android, you think all devs doing same layout and colors etc? Poor.

**Comment by hakkikaancaliskan** [comment]
> 
> > 
> > That's "media" notification and android controlling manually.
> > That's not custom, same on all apps, that's provided by android.
> 
> Nope then tell me when I am playing same video in chrome and Firefox why the color is different...if it's android it should show the same color but I strongly believe this is how the website treating and changing the notification color and background....
> ![Screenshot_2020-07-20-10-48-09-90](https://user-images.githubusercontent.com/58127841/87902297-dcf1b080-ca76-11ea-8c79-91a6844443ea.png)
> ![Screenshot_2020-07-20-10-48-27-90](https://user-images.githubusercontent.com/58127841/87902305-e1b66480-ca76-11ea-81d0-f807a685a267.png)
> 

Because looks like Fenix can't provide correct thumbnail.
Fenix provided just tab thumbnail and chrome provided video thumbnail.
But notice that notification color is based on thumbnail.

**Comment by hakkikaancaliskan** [comment]
Look to this, https://developer.android.com/training/notify-user/expanded#media-style, does this look like custom or devs using Android provided one. Even if you know nothing, just look to the code, just a bunch of line.

**Comment by ShatteredPixel** [comment]
@hakkikaancaliskan Just question out of curiosity...

Will it still be considered as a custom notification even if we just the colour of the "Progress bar" and "Pause" and "Cancel" button to something like suggested in the https://github.com/mozilla-mobile/fenix/issues/12226#issuecomment-655276128 (arguments aside, but I have to say that it _does_ look really nice!)?
___


Also, as you can see, on my device, the progress bar of most apps on my device is green coloured (so I think, the default colour accent or whatever... for this is green on my device):

### On Chrome browser the progress bar is green on my device:

![Screenshot_20200720-140400](https://user-images.githubusercontent.com/68282543/87917264-521eaf00-ca92-11ea-89be-e13e49dc28db.png)



### On [ADM ](https://play.google.com/store/apps/details?id=com.dv.adm) download manager the progress bar is again green on my device:
![Screenshot_20200720-110548](https://user-images.githubusercontent.com/68282543/87913778-3d8be800-ca8d-11ea-89e1-c52d3e638874.png)

___ 

### But on Fenix the progress bar is of some other colour, and the button for Pause and Cancel seem to be of other colour as well:

![Screenshot_20200720-110842](https://user-images.githubusercontent.com/68282543/87914070-be4ae400-ca8d-11ea-8b82-ba6d8c9d23ca.png)
___



I don't understand the engineering aspect of this ( as I am not a developer) but as a general Android user who loves stock AOSP Android's UI and UX, I can say that the custom notification style of the apps does do interfere with the OEM implemented notification style, as I have seen it on some devices like Xiaomi, Realme, Samsung, Oppo, Vivo, etc. they do have notification style something that feels very different from AOSP Android. And if they clash the result is something that I don't want to talk about! and designing for each OEM will take considerable amount of engineering efforts/resources and it's also seems to be not practical as the nature of AOSP Android stands, any OEM could modify any aspect of the OS and it will be impossible to track down every device implementation out there (yes, I know there's [CDD ](https://source.android.com/compatibility/cdd )but I don't think _every_ Android OEM out there is strictly following it).   
 
And the custom notification style of Fenix is causing several issues, as you are already saying, and I also think it shouldn't be implemented if the benefits are not outweighing the negatives we are getting in return.
 
but as you can see in the screenshots I attached, at least the current behavior is something that could/should be matched with how the other apps are behaving as otherwise Fenix's behavior would feel inconsistent with how the rest of the apps are behaving.



Thanks for listening to me. :)
What do you think?

**Comment by hakkikaancaliskan** [comment]
> @hakkikaancaliskan Just question out of curiosity...
> 
> Will it still be considered as a custom notification even if we just the colour of the "Progress bar" and "Pause" and "Cancel" button to something like suggested in the https://github.com/mozilla-mobile/fenix/issues/12226#issuecomment-655276128 (arguments aside, but I have to say that it _does_ look really nice!)?
> ___
> 
> 
> Also, as you can see, on my device, the progress bar of most apps on my device is green coloured (so I think, the default colour accent or whatever... for this is green on my device):
> 
> ### On Chrome browser the progress bar is green on my device:
> 
> ![Screenshot_20200720-140400](https://user-images.githubusercontent.com/68282543/87917264-521eaf00-ca92-11ea-89be-e13e49dc28db.png)
> 
> 
> 
> ### On [ADM ](https://play.google.com/store/apps/details?id=com.dv.adm) download manager the progress bar is again green on my device:
> ![Screenshot_20200720-110548](https://user-images.githubusercontent.com/68282543/87913778-3d8be800-ca8d-11ea-89e1-c52d3e638874.png)
> 
> ___ 
> 
> ### But on Fenix the progress bar is of some other colour, and the button for Pause and Cancel seem to be of other colour as well:
> 
> ![Screenshot_20200720-110842](https://user-images.githubusercontent.com/68282543/87914070-be4ae400-ca8d-11ea-8b82-ba6d8c9d23ca.png)
> ___
> 
> 
> 
> I don't understand the engineering aspect of this ( as I am not a developer) but as a general Android user who loves stock AOSP Android's UI and UX, I can say that the custom notification style of the apps does do interfere with the OEM implemented notification style, as I have seen it on some devices like Xiaomi, Realme, Samsung, Oppo, Vivo, etc. they do have notification style something that feels very different from AOSP Android. And if they clash the result is something that I don't want to talk about! and designing for each OEM will take considerable amount of engineering efforts/resources and it's also seems to be not practical as the nature of AOSP Android stands, any OEM could modify any aspect of the OS and it will be impossible to track down every device implementation out there (yes, I know there's [CDD ](https://source.android.com/compatibility/cdd )but I don't think _every_ Android OEM out there is strictly following it).   
>  
> And the custom notification style of Fenix is causing several issues, as you are already saying, and I also think it shouldn't be implemented if the benefits are not outweighing the negatives we are getting in return.
>  
> but as you can see in the screenshots I attached, at least the current behavior is something that could/should be matched with how the other apps are behaving as otherwise Fenix's behavior would feel inconsistent with how the rest of the apps are behaving.
> 
> 
> 
> Thanks for listening to me. :)
> What do you think?

Yes as you said we're using different accent color, we can use default one for consistency.
@brampitoyo what do you think about this?

**Comment by ShatteredPixel** [comment]
@hakkikaancaliskan it'd be great for me if you deleted your comment history and keep the only the recent edit for the https://github.com/mozilla-mobile/fenix/issues/12226#issuecomment-660899262 above. I have blurred some information from the screenshots of my comment (I'm not comfortable with revealing where I'm from). So could you please do it? Pretty please...

**Comment by Amejia481** [comment]
> I've worked on this ([mozilla-mobile/android-components#7763](https://github.com/mozilla-mobile/android-components/pull/7763)) but after a second thought, maybe we "should" use Android's default.
> Because look to the caution at the end of the page https://developer.android.com/training/notify-user/custom-notification.
> 
> Chrome also using default without "any" modification.
> 
> @Amejia481 we shouldn't take this risk, this could cause layout inconsistencies. What do you guys think?

First of all, thanks @hakkikaancaliskan for doing all this great work 🥇 .  


> …your notification will not match the rest of the notifications and it can cause significant layout compatibility issues on different devices that apply different styling to the notification area.

That's an important consideration, as we prefer to keep notifications compatibility to avoid fragmentation issues, as we are relying on default behaviours for [Notification grouping](https://developer.android.com/training/notify-user/group). Let's not not go the custom route for now, maybe we can re-explore that alternative in the future.  One thing that we could try to make Fenix notification more closer to its theme is changing the accent colour to the Fenix one or just using the default  as you mentioned @hakkikaancaliskan.
