### ISSUE TITLE
FNX-4883 ⁃ [Bug] The Tab/app crashed message doesn't appear in Private browsing

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1222]
## Steps to reproduce
1. Open a tab in private browsing.
1. Go to about:crashcontent.
1. Go to about:crashparent
    1. Expected behavior
1. The tab crashed message is displayed.
1. "Fenix isn't responding" dialog is displayed.
    1. Actual behavior
The homepage is displayed, with the tab minimized.
"Fenix isn't responding" dialog is not displayed either.
    1. Device information

* Android device: Pixel, Nexus 5
* Fenix version: 3/27

**Comment by sblatz** [comment]
This is blocked on a soon-to-come change with a-c.

**Comment by sblatz** [comment]
I believe [this change](https://github.com/mozilla-mobile/android-components/issues/2571) is the fix we were waiting on. Is that correct, @pocmo?

**Comment by bsurd** [comment]
This has now been verified the tab/app crash now work in private mode as well without any issues.
