### ISSUE TITLE
Add option to open new tab from three dot menu menu

### ISSUE THREAD

**Issue by nc-x** [mozilla-mobile/fenix#12229]
All other browsers have the new tab option in the three dot menu, having the same option here would help with muscle memory.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2989)

**Comment by ekager** [comment]
FYI: you can long press on the tab counter to quickly open a new tab.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809231

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
