### ISSUE TITLE
[Bug] Wikipedia search language doesn't change when browser's language changes.

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#12236]
## Steps to reproduce
1. Change your browser language
1. Search with wikipedia
    1. Expected behavior
Wikipedia uses the new browser's language
    1. Actual behavior
Wikipedia stays with old browser's language
    1. Device information

* Android device: Pocophone F1, android 9
* Fenix version: nightly 200703 06:16

workaround: go to app info, kill firefox, reopen firefox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3002)

**Comment by B0pol** [comment]
It's still an issue

**Comment by B0pol** [comment]
Bump

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 99.0a1 (2022-02-25).
Device used: Oppo Reno 6 (Android 11).

**Comment by lapaz17** [comment]
Still reproducible on latest release 99.2.0
Device used : Xiaomi Note 9 pro.

**Comment by AdinaPetridean** [comment]
This issue is still reproducible on the latest Nightly 108.0a1 (2022-10-27).
Device used:  Google Pixel 3 (Android 11)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 109.0a1 (2022-12-07) build.
Deviced used: Google Pixel 4 (Android 13) and Oppo Find X5 (Android 12).
Languages tested: Arabic and hungarian.
Closing the ticket as fixed.
