### ISSUE TITLE
FNX2-15100 ⁃ [Bug] Multiple Browsers in App Switcher

### ISSUE THREAD

**Issue by tjsmith1991** [mozilla-mobile/fenix#12237]
## Steps to reproduce - 
* Open up Firefox version 79.0.0 beta 5 and go to app switcher and you will see two Firefox browsers open. One is blank and the other is wherever you left off in the browser.

### Expected behavior - 
* Only one open browser.

### Actual behavior - 
* Shows two open browsers.

### Device information - 
* Pixel 3 XL running Android 11 Beta build number  RPB1.200504.020
* Fenix version: 79.0.0-beta.5 (Build #2015749827)
AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7
![Screenshot](https://user-images.githubusercontent.com/67785545/86460747-f1a01b80-bcf6-11ea-8416-dda2c12e0455.png)UNITO-UNDERSCORE!20200703-063117!

**Comment by rawkode** [comment]
I have this also and I'm also on Android 11 beta

**Comment by tjsmith1991** [comment]
It continues on 79.1.0 Beta 1 as well on Android 11 Beta 2.5.

**Comment by rawkode** [comment]
This isn't an issue with the nightly builds, if that helps track this down. It is still an issue with the beta builds.

**Comment by tjsmith1991** [comment]
On the current android beta and Firefox beta builds, still present.

**Comment by kbrosnan** [comment]
Duplicate #13270

**Comment by Kol3sar** [comment]
Official realese of Android 11 is out and this is still an issue.

**Comment by cadeyrn** [comment]
@Kol3sar Please read the linked duplicate issue. The issue is already fixed in Firefox Beta.

**Comment by wakeup667** [comment]
Today was Firefox update but unfortunately it did not fix the problem.
Beta is worse because sync does not work and I don't know how to enable 120hz display refresh rate, it's lagging on 60hz.
Can you please push this fix to stable? 
Each day number of android 11 is growing and each of us has to live with this funny bug of his/her favourite browser.

**Comment by wakeup667** [comment]
Fixed in stable 👍. Great. Thanks
