### ISSUE TITLE
[Bug] On Firefox Nightly the button "Get Firefox for Android Beta" is displayed even if the app is already installed

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#12234]
## Prerequisites
The new Firefox Nightly is installed (old Firefox Preview).
Firefox for Android Beta is installed.

## Steps to reproduce
1. Open Firefox Nightly.
1. Check the message regarding Firefox for Android Beta.

### Expected behavior
Only information about Nightly should be displayed and maybe a link to Open Firefox for Android Beta.

### Actual behavior
"Get Firefox for Android Beta" is displayed even if the browser is already installed. 

### Device information
* Android device: Samsung Galaxy Note10 (Android 10)
* Fenix version: 7/2.

![20200703](https://user-images.githubusercontent.com/58466444/86456682-1dd58f80-bd2b-11ea-8bb8-df436554502a.gif)UNITO-UNDERSCORE!124112!

**Comment by sheikh-azharuddin** [comment]
It is just a warning and suggestions to move to beta since nightly is experimental and can have bugs

**Comment by cadeyrn** [comment]
I am sure sflorean knows that. The important detail in the report is: "Firefox for Android Beta is installed". If it's possible to detect that Firefox Beta is already installed then there is no need to suggest downloading Firefox Beta. It could either be a button to open Firefox Beta or the whole message could be hidden.
