### ISSUE TITLE
Enable btime youtube-playback Fenix tests

### ISSUE THREAD

**Issue by alexandru-io** [mozilla-mobile/fenix#12240]
### What is the user problem or growth opportunity you want to see solved?
Browsertime youtube-playback tests were added to mozilla-central: https://bugzilla.mozilla.org/show_bug.cgi?id=1621344
We need to add them to fenix and allow them to run with cron.

**Comment by ekager** [comment]
Looks like the PR was merged and we can close this issue. Please reopen if that is incorrect
