### ISSUE TITLE
[Bug] can't download file that need to login

### ISSUE THREAD

**Issue by tonln** [mozilla-mobile/fenix#12247]
## Steps to reproduce
download the file that need to login

### Expected behavior
when downloaded completely, the file is a html file and it say need to login

### Device information
* Android device: Android 10
* Fenix version: 

Nightly 200703 08:40 (Build #21850844)
AC: 49.0.20200702131412, 1cba216b2
GV: 80.0a1-20200701093012
AS: 61.0.7
Friday 7/3 @ 8:43 AM

**Comment by SS1113** [comment]
Thanks for filling the issue! This is already reported here: https://github.com/mozilla-mobile/fenix/issues/7531

**Comment by Amejia481** [comment]
thanks @SS1113 we can close this one
