### ISSUE TITLE
FNX-4885 ⁃ [Bug] Loading about:config doesn't work

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#1224]
## Steps to reproduce
Loading about:config was working, I think, still recently

### Expected behavior
about:config should load

### Actual behavior
nothing is loaded?

### Device information
* Android device: Honor 7, Android 6
* Fenix version: 1.0.1913

**Comment by cpeterso** [comment]
I wonder if this bug is related to about:config crash issue #1034. I know about:config works in GeckoView 68 in Firefox for Fire TV.

**Comment by bsurd** [comment]
Doing a regression it would seem that about:config still worked in the build from [22.03](https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly.2019.3.22/latest) task ID HYLxVmV7R1yXFCSAes2P2w and failed from the [25th](https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly.2019.3.25/latest) task ID KcPTUsBmQXmr7E1qsDKAlw. There are no other builds available between these 2 dates to help narrow it down any further.

**Comment by sblatz** [comment]
I think this is likely related to: https://github.com/mozilla-mobile/android-components/issues/2794

**Comment by kbrosnan** [comment]
This is fixed in a current build.

**Comment by alexa-v2** [comment]
This is still present on 1.0.1925

**Comment by cpeterso** [comment]
`about:config` only works in GeckoView Nightly builds. Fenix is currently using GeckoView 68 Beta, so `about:config` is not expected to work at the moment.
