### ISSUE TITLE
Order of links opened consecutively in new tabs

### ISSUE THREAD

**Issue by crisalis2** [mozilla-mobile/fenix#12243]
Right now Fenix (Google Play Firefox Beta) follows this logic, which is fine (actually I'd prefer the reverse order, but that's another thing):
1\) Older tabs at the bottom.
2\) Newer tabs at the top.
3\) If, from a given tab, you select to open a link in a new tab, that tab is placed at the top of that given tab, not at the absolute top.

But there's a case that doesn't make sense for me. It's when you're in a given tab and select a first link to be opened in a new tab, and then right away a second link to be opened in another new tab, so that two new tabs are appended to the top of the given tab.

In this case, the relative order of the two new tabs is what I think doesn't make sense. The first link (older) tab is at the top, and the second link (newer) tab is at the bottom. This contradicts the logic in 1) and 2). And it makes me "get lost" when navigating my tabs if I open several links in new tabs consecutively.

**Comment by liuche** [comment]
We're handling tab ordering in #10344
