### ISSUE TITLE
[Bug] x cross to close custom tabs almost invisible

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#12245]
## Steps to reproduce
1. Change browser's theme to light
1. Open a custom tab
    1. Expected behavior
The cross is black on white, so that it's visible
    1. Actual behavior
The cross is white on white, it's almost invisible
    1. Device information

* Android device: android 9, Pocophone F1
* Fenix version: 200703 06:13

Screenshot:
![](https://i.imgur.com/oo4ryCi.png)

**Comment by sheikh-azharuddin** [comment]
It's fine here

![Screenshot_20200703-193042](https://user-images.githubusercontent.com/58127841/86476235-ab1de180-bd35-11ea-94db-b7e3972911ae.jpg)

**Comment by SS1113** [comment]
It's a duplicate issue. I have already filed it and the developers are working on it: https://github.com/mozilla-mobile/fenix/issues/11903

Hi, @sheikh-azharuddin I have raised an issue #12228 . Can you say what opinions do you have about what I have said there?
