### ISSUE TITLE
[Bug] Desktop site toggle in Custom Tab is really close to the "Desktop site" text

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#12253]
## Steps to reproduce
1. Open an external link
1. Tap the three-dot menu under Firefox Custom Tabs
1. Observe the Desktop site label.

### Device information
* Android device: Android10
* Fenix version: Firefox Beta 79.0.0-beta.4

**Comment by ekager** [comment]
Similar issue to #14684
