### ISSUE TITLE
I can't find Firefox Preview on Google Playstore

### ISSUE THREAD

**Issue by marker10** [mozilla-mobile/fenix#12257]
I can't find Firefox Preview on Google Playstore anymore. There is only the nightly version,

**Comment by RealGJ** [comment]
Firefox Preview is now Firefox Nightly!!!
If you want to use fenix, use Firefox for Android Beta.:
https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta

**Comment by marker10** [comment]
ah ok thanks.

**Comment by sheikh-azharuddin** [comment]
Everything here is kind of dark series🤣🤣
Firefox preview is now Firefox nightly...it is same build as Firefox fennec nightly and Firefox preview nightly.... Firefox preview orginal code pushed to Firefox beta....
Firefox fenix nightly redirect to Firefox nightly...which again redirects to same app...

**Comment by Dunexus** [comment]
It is actually really simple.
Before, there was Firefox, Firefox Beta, Firefox Nightly and for fenix, Firefox Preview Beta, Firefox Preview Nightly.

Now, fenix is replacing fennec in Nightly and Beta channel before replacing it in the main update channel.
This is a transition phase.

**Comment by sheikh-azharuddin** [comment]
But why Firefox is not removing below 2 products from play store-

![Screenshot_20200703-221454~2](https://user-images.githubusercontent.com/58127841/86487079-a7e22000-bd4c-11ea-8665-42690f3621d9.jpg)

**Comment by sheikh-azharuddin** [comment]
Also one more question earlier we used to get the latest build of fenix nightly from below link.... similarly what is the link to download latest build of new Firefox nightly?

https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest

**Comment by RealGJ** [comment]
@sheikh-azharuddin they told that they're going to remove those two versions.
1. Firefox Nightly for developers - early access
2. Firefox Preview Nightly - early access.

But I don't know when!!!

**Comment by Augures01** [comment]
> Also one more question earlier we used to get the latest build of fenix nightly from below link.... similarly what is the link to download latest build of new Firefox nightly?
> 
> https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest

https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.production/latest

**Comment by sheikh-azharuddin** [comment]
Fenix nightly is still getting updated...
![Screenshot_20200704-002823](https://user-images.githubusercontent.com/58127841/86492948-2f388f00-bd5f-11ea-9608-b8c553e694b7.jpg)

**Comment by kbrosnan** [comment]
The Play store cleanup is complete. There is no more Firefox Preview. 

* [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)
* [Firefox Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta)
*  [Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)
