### ISSUE TITLE
[Bug] "Learn more" link from both Firefox Nightly opens a missing page (Page Not Found)

### ISSUE THREAD

**Issue by saschanaz** [mozilla-mobile/fenix#12256]
## Steps to reproduce
* Run either Firefox Nightly (previously Firefox Preview Nightly) or Firefox Nightly (previously Firefox Preview).

### Expected behavior
Tapping "Learn more" should show a valid page

### Actual behavior
It connects to https://support.mozilla.org/en-US/kb/sync-delist which does not exist

### Device information
* Android device: Samsung Galaxy Note 8
* Fenix version: 80.0a1-20200701093012

**Comment by sivaraam** [comment]
I can confirm this.

**Comment by saschanaz** [comment]
This is now fixed, seems the problem was in support.mozilla.org.
