### ISSUE TITLE
[Bug] After about a minute of use, it no longer loads any sites

### ISSUE THREAD

**Issue by marker10** [mozilla-mobile/fenix#12259]
After about a minute of use, it no longer loads any sites. 
Restarting the browser then it starts working again.
Screenshoot:
https://i.postimg.cc/9fgR7nJv/fbeta.jpg

79.0.0-beta.4 (Build #2015749491)
AC: 48.0.2, 0fe2d3031
GV: 79.0-20200629161151
AS: 61.0.7

Android 6.0.1 Asus Zenfone 2

**Comment by ekager** [comment]
@marker10 are you still seeing this issue?
