### ISSUE TITLE
FNX2-15124 ⁃ [SUGGESION] Only 2 builds should be there on Play Store

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#12268]
As we have, a Old Firefox (fennec), Mozilla Firefox for Android (Fenix beta), and Firefox Nightly (Fenix Nightly) on android play store. Again there are Firefox Nightly for Developers (Early access), Firefox Preview Nightly (Early access). it's so confusing.

Out of mentioned above, only Old Firefox (fennec) and Firefox Nightly (fenix nightly) should be there. As Firefox for Android Beta (fenix beta) is the beta program, it should be available to only those users who join Beta program for Main Firefox Browser (Fennec). It'll be alot easier for Users.

HOW YOU KNOW IT'S A PROBLEM:
This is how beta program works.

Who will benefit:   Every one.

**Comment by sheikh-azharuddin** [comment]
Correct the beta should be available for users who join beta channel...so even if they switch to beta or back to stable it won't cause any data loss.... microsoft edge is following same strategy...

**Comment by filips123** [comment]
Having two builds in same app using beta program makes it impossible to install both stable and beta app at the same time. This means that if you want to use Fenix as main browser but keep Fennec for addons or occasionally browsing (or opposite), you will have to install Nightly which can be very unstable.

Also, how do you think migration from beta to stable would work? If there are some breaking changes in beta that make profile incompatible with stable, having the same app won't magically make profile available in stable, but probably cause even more problems.

**Comment by sheikh-azharuddin** [comment]
Why would someone install both beta and stable at the same time? The implementation should be smooth like microsoft edge....once you join beta channel or leave it it should revert immediately without any interruption or data loss

**Comment by filips123** [comment]
> f you want to use Fenix as main browser but keep Fennec for addons or occasionally browsing

**Comment by sheikh-azharuddin** [comment]
Those breaking changes should be first observed in nightly...if any issue observed  you don't release it as beta. So everything is first tested in nightly then released to beta after all issue fixed....should not be much issue. This is how microsoft edge has deployed...for new features testing user can always use nightly one that is almost stable only....

**Comment by filips123** [comment]
And what if breaking changes are meant to be eventually released?

**Comment by sheikh-azharuddin** [comment]
> And what if breaking/backwards-incompatible changes are meant to be eventually released?

In short you want to keep 3 versions.... You want to keep what I can say more....

**Comment by klint** [comment]
And now it's even worse we have 5 builds! 😞

**Comment by cadeyrn** [comment]
> And now it's even worse we have 5 builds! 😞

Why "worse"? There were already 5 build when the issue was created.

**Comment by klint** [comment]
Yes of course, I mean worse than last week or so. Don't worry I get it, 
it's temporary, but it's temporary highly confusing 😊. When can we expect 
one nightly build only again?
I'll need to migrate all my shortcuts on the launcher as well as all my 
collections to the  elected nightly build (I had bet on the migration 
build, but I was wrong as it seems).

Le 6 juillet 2020 14:43:39 Sören Hentzschel <notifications@github.com> a 
écrit :

**Comment by Dunexus** [comment]
The developers are updating the whole producing and publishing process to have the right build deployed on the right update channel and stopping deprecated ones.
This PR filter should give you a good vision of the process : https://github.com/mozilla-mobile/fenix/pulls?q=is%3Apr+1649400

**Comment by klint** [comment]
Thanks. One question: once a deprecated nightly is stopped, will it be uninstalled from the phone automatically or will it stay there, never updated again?

**Comment by Dunexus** [comment]
I don't think developer can uninstall their app from users phone. My guess is that the app page will be removed from the play store search results and you will not get any further update.
For the Firefox Preview Nighlty at least, they did an update to show an in-app message saying that this version was outdated and will not receive updates and a link bringing us to the Firefox Nightly play store page as the new nightly version to be used.

**Comment by RealGJ** [comment]
Okay, Just checked on play store, the and the unwanted builds are removed. And now Firefox follows Stable, Beta and Nightly track for Android. I think I should close this now as Mozilla won't follow the 2 build way!!!
