### ISSUE TITLE
[Bug] Make sure that the user uninstalled the correct "Firefox Nightly" app

### ISSUE THREAD

**Issue by reinhart1010** [mozilla-mobile/fenix#12266]
Having 2 "Firefox Nightly" apps seems to be confusing. Reproducible when a user has installed Firefox Preview Nightly alongside Firefox Preview before the transition. Related to #12232

![image](https://user-images.githubusercontent.com/17312341/86504718-71f17a00-bde6-11ea-8499-690fa9a98883.png)

**Comment by filips123** [comment]
Maybe some idea how to quickly do this: Publish a build for old nightlies which renamed them to something like "Old Firefox"

**Comment by kbrosnan** [comment]
We are not pushing any new builds to those channels.
