### ISSUE TITLE
Bring back Trash icon / one tap close all tabs in private mode tab tray

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#12260]
### What is the user problem or growth opportunity you want to see solved?
Make it easier to close tabs in private mode.

### How do you know that this problem exists today? Why is this important?
User feedback: https://www.reddit.com/r/firefox/comments/hkm87y/fenix_tab_switcher_i_hate_how_closing_all_tabs/

We already had this in previous Fenix.

It continues to exist in Edge, Focus/Klar, DuckDuckGo browser

### Who will benefit from it?
Anyone who wants a fast removal of all open private tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3029)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812918

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
