### ISSUE TITLE
[Bug] visual issue with main menu

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#12265]
### Steps to reproduce
1. open the main menu

### Expected behavior
No visual bugs.

### Actual behavior
There is something black on the bottom of the menu. It could be the bottom of the tab counter. Maybe you could move the menu a bit down?

![](https://user-images.githubusercontent.com/1100614/86498529-7a19cd00-bd86-11ea-8845-0edb53f48835.png)

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 388c144a6274cfab0318dcc8e0691e43137a5292

**Comment by lomomcat** [comment]
I think that's fine.😊No need to change.

**Comment by cadeyrn** [comment]
I'm happy for you, if you don't mind. For me details are important and in fact it's a regressing since Firefox Preview 5.2, it was not an issue in Firefox Preview 5.1 and older versions.

**Comment by sheikh-azharuddin** [comment]
It's jus a thin line( thinner than hair) from tab button....not that much visible...😅

**Comment by cadeyrn** [comment]
But still very noticeable for some people. Especially because it's a thin line it feels like a visual bug and its easily avoidable.

**Comment by sheikh-azharuddin** [comment]
@cadeyrn somewhat I disagree to that...I have a large screen device 6.56" but still that is hardly noticeable...and also it is completely understandable because that thin line is from tab button...maybe they can expand the menu by 1-2dp to cover that 😅

**Comment by cadeyrn** [comment]
Again: It's very noticeable **for some people** - of course not for everyone. I have the same answer for you as for lomomcat: I'm happy for you if you don't mind. But please accept that some people have an eye for details while others don't or at least not in the same way. I am a web developer and my customers have the highest demands so my eyes are trained for such details and thus it's eye-catching for me.

**Comment by AndRo-Marian** [comment]
Why is that up anyway. Should be on bottom with no space.

**Comment by AndRo-Marian** [comment]
Seams this still happens on start page where no website is open.

**Comment by cadeyrn** [comment]
This is fixed.
