### ISSUE TITLE
As a user, I would like to migrate from Firefox Nightly (formerly Firefox Preview) to Beta

### ISSUE THREAD

**Issue by reinhart1010** [mozilla-mobile/fenix#12267]
## User Story
* As a user, I would like to migrate from Firefox Nightly (formerly Firefox Preview) to Beta.
* Currently the app does not offer instructions to move my bookmarks, logins, and history to Firefox Beta, or even the final release of the new Firefox app.
* (Consider that the user was not aware of Firefox Accounts and Sync, and/or ignored the Sync advertisement at the first place)

## Dependencies
* This can be done by putting the following text into the Firefox Preview notice (originally shown on Preview Nightly), unless if the Beta app allows data migration from Preview/Nightly.

> To transfer bookmarks, logins, and history to another app, create a Firefox account.

### Acceptance Criteria
* I can finally move my browsing data to Firefox Beta

**Comment by kbrosnan** [comment]
Sync is the best tool we have for this. There are other issues about exporting/importing various profile bits that are open.
