### ISSUE TITLE
[Bug] synced tabs: large gap if there is no page title

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#12264]
### Steps to reproduce
1. enable the sync feature
1. open the synced tabs screen

### Expected behavior
No large gap if a page has no title. There could be a placeholder text like "(no page title)" or something else.

### Actual behavior
There is a large gap.

![screen2](https://user-images.githubusercontent.com/1100614/86498353-cd3f5000-bd85-11ea-9b9a-e3d3bcd60515.png)

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 388c144a6274cfab0318dcc8e0691e43137a5292

**Comment by yoasif** [comment]
I have seen this as well, but is it actually the case that there is no title?

**Comment by cadeyrn** [comment]
I don't know if Firefox really lost the page title or why there is no page title. Since it's a GitHub issue the page should probably have a page title. But regardless of whether this is a Firefox bug or whether a page actually has no title, I think it the case that nothing is shown should be prevented because this looks wrong in any case and I know that pages without title exist in the web. 🙂

**Comment by ekager** [comment]
UX - should we do something like use the host of the website as the "title" if we don't have a title here?

**Comment by yoasif** [comment]
@ekager Is the underlying issue a sync issue aside from the weirdness with UX? Clearly that GitHub page has a title, but my guess is that Fenix doesn't know it because it hasn't been loaded inside of Fenix.

If the issue being tracked is pages with no title, is the issue shared for open tabs?

**Comment by AmyYLee** [comment]
> UX - should we do something like use the host of the website as the "title" if we don't have a title here?

Is this a bug with Fenix that a title does exist but it's not showing up? - Either way if we have a situation where there actually is no title, I think we should have placeholder copy. @betsymi Thoughts?

**Comment by betsymi** [comment]
> @betsymi gentle ping 🙂
> 
> > Either way if we have a situation where there actually is no title, I think we should have placeholder copy. @betsymi Thoughts?

I don't understand the string request. Is the request that if there is no page title, we automate one? Or that it reads something like `No Page Title`.

**Comment by cadeyrn** [comment]
@betsymi 

> I don't understand the string request. Is the request that if there is no page title, we automate one? Or that it reads something like No Page Title.

As you can see in the screenshot above in the current version of Firefox there is nothing at all when there is no page title. I think there are different options that are all better than showing nothing. Either show the same for the title as for the URL or only the domain (for example just "github.com" in the example above) or a placeholder text, as @AmyYLee suggested, like "No Page Title".

If the decision is to use a placeholder text then it's the placeholder text that is requested.

Does it help?
