### ISSUE TITLE
FNX-13307 ⁃ [Bug] device name on synced tabs screen is truncated

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#12263]
### Steps to reproduce
1. make sure you have a longer device name for one of your devices
1. enable the sync feature
1. open the synced tabs screen

### Expected behavior
No truncated device name.

### Actual behavior
Device name is truncated.

![screen1](https://user-images.githubusercontent.com/1100614/86498257-5b670680-bd85-11ea-9e6f-3581391f937d.png)

### Device information
* Android device: OnePlus 7T Pro McLaren Edition with Oxygen OS 10.0.9 (Android 10)
* Fenix version: master branch revision 388c144a6274cfab0318dcc8e0691e43137a5292

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200708-102548](https://user-images.githubusercontent.com/51314259/86890904-ab87f500-c106-11ea-9d04-44adde2ffa45.png)
