### ISSUE TITLE
[Bug] sites not loading for some time if connection interrupted

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12272]
## Steps to reproduce
Click any article including google search and while page is starts to load(blank screen) disconnect the internet it will stop loading no matter how many times you try even in a new tab while if you try to open the same page in private mode it opens properly....so some how negative result is cached somewhere not allowing page to load....kind of dns negative result

Please fix the bug too much frustrating... happens sometime even in google search too 

### Expected behavior
Page should load again if net connection is back to normal.

### Actual behavior
Page does not load even if net connection is stable...it is kind of caching the negative result. In earlier version it used to show address not found now showing a blank screen

### Device information
* Android device: ? A10
* Fenix version: ? Latest nightly

![Screenshot](https://user-images.githubusercontent.com/58127841/86509676-2a182600-bdd9-11ea-8b13-a344cf5296eb.jpg)UNITO-UNDERSCORE!20200704-150109!
![Screenshot](https://user-images.githubusercontent.com/58127841/86509677-30a69d80-bdd9-11ea-8e5e-2494107ff2f3.jpg)UNITO-UNDERSCORE!20200704-150128!

**Comment by sheikh-azharuddin** [comment]
The issue is getting worse....it seems it is cached for longer time...the link open fines from private mode
![Screenshot_20200704-175424](https://user-images.githubusercontent.com/58127841/86512385-6ce5f800-bdf1-11ea-90ae-0531ea1c2e3a.jpg)

**Comment by SS1113** [comment]
@sheikh-azharuddin can you investigate if by any chance you're experiencing this bug: https://github.com/mozilla-mobile/fenix/issues/11501

**Comment by sheikh-azharuddin** [comment]
Yep same issue...
