### ISSUE TITLE
[Bug] 'Fill link from clipboard' not working when directly opening new tab.

### ISSUE THREAD

**Issue by vishalnandagopal** [mozilla-mobile/fenix#12274]
## Steps to reproduce
1. Add a shortcut/widget to directly open new tab to your Android home screen. (By long pressing on FF icon and dragging out the 'new tab' option)
1. Copy a link from somewhere else.
1. Click the newly created 'new tab' shortcut. The URL bar and keyboard are directly opened.

### Expected behavior
It should show 'fill link from clipboard' and the URL you copied should be suggested.

### Actual behavior
Not shown. Have to go back and press URL bar again to open.

### Device information
* Android device: 10
* Fenix version:  Nightly 200704 06:01 (Build #21860821)

**Comment by klint** [comment]
Also happens when clicking on the Fenix search widget on the launcher (nightly).

**Comment by ekager** [comment]
@klint @vishalnandagopal thanks for reporting! Is this still a problem?

**Comment by klint** [comment]
Hi @ekager . It seems to be fixed on my end. Thanks 😊

**Comment by ekager** [comment]
Great! Closing :)
