### ISSUE TITLE
FNX2-15126 ⁃ [Bug] Search suggestions doesn't work for custom search engines.

### ISSUE THREAD

**Issue by h0cheung** [mozilla-mobile/fenix#12270]
## Steps to reproduce
Add startpage or searx to fenix, and set it as default, then try to search some words.

### Expected behavior
It should show some suggestions.

### Actual behavior
It doesn't show

### Device information
* Android device: 10
* Fenix version: both 79.0.0-beta5 and latest nightly have this.

**Comment by cadeyrn** [comment]
Duplicate of #7866.

**Comment by ekager** [comment]
closing for #7866
