### ISSUE TITLE
[Bug] Device name changes in Fenix aren't reflected in Firefox Desktop "Synced Tabs" view

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#12276]
## Steps to reproduce
1. Change the device name, and perform a manual sync.
1. Open the synced tabs view in Firefox Desktop (from the side bar or the Firefox account icon).

### Expected behavior
The changed device name is reflected in the Firefox Desktop "Synced Tabs" view.

### Actual behavior
The device name in the Firefox Desktop "Synced Tabs" view is still shown as the default "Firefox {Channel} on {Device Manufacturer & Model}".

**Changed device name:**
![](https://user-images.githubusercontent.com/45960387/86511701-3084bd00-be2e-11ea-93da-6989dfe28151.jpg)

**Changes in device name is not reflected in Firefox Desktop "Synced Tabs" view:**
![](https://user-images.githubusercontent.com/45960387/86511656-c10ecd80-be2d-11ea-8d89-e2185d16d4b8.png)

**However, one thing I noticed is that the changed device name shows up as expected when viewing synced tabs in another Fenix channel (from Firefox Nightly):**
![](https://user-images.githubusercontent.com/45960387/86511710-3a0e2500-be2e-11ea-9f3b-bd47a1db50c7.jpg)

### Device information
* Android device: Oppo Reno 2
* Fenix version: 79.0.0-beta.4 (Build #2015749491), Nightly 200704 06:01 (Build #21860821)

**Comment by sflorean** [comment]
@SL-Lee this is still reproducible for you? Tested on latest Firefox Nightly 7/20 and couldn't reproduce the issue, the device name was changed on Win10.

**Comment by SL-Lee** [comment]
Yes, unfortunately this issue is still somewhat reproducible on my end, and I think I have found out why this happens: after starting Fenix, going into Settings and tapping on the "Turn on Sync" banner before it finished loading will reset the device name in Fenix for Synced Tabs (observe the brief flash of the default device name in the video below). However, other areas where the device name is shown (e.g. Send Tab to Device) is not affected by this.

![](https://user-images.githubusercontent.com/45960387/88016246-93c45e00-cb55-11ea-8758-00d94272342f.gif)

**Comment by SL-Lee** [comment]
Yes, unfortunately this issue is still reproducible on my end. If go to *Settings > Firefox Account*, tap on the device name field in Fenix, press "OK" and force a sync, the changed device name will show up in the Firefox Desktop Synced Tabs view. However, once I restart Fenix, then go to *Settings > Firefox Account* and force a sync again, the device name is reset to the default in the Firefox Desktop Synced Tabs view. This may be due to how the device name is updated dynamically, as shown in the video below (observe the brief flash of the default device name, before it is updated to the changed device name):

![](https://user-images.githubusercontent.com/45960387/88016246-93c45e00-cb55-11ea-8758-00d94272342f.gif)

**Comment by ekager** [comment]
Seems related to https://github.com/mozilla-mobile/fenix/issues/10792

**Comment by SL-Lee** [comment]
This issue is still reproducible for me (I'm using **Nightly 210317 17:01 Build #2015799243**). The steps I mentioned in [my previous comment](https://github.com/mozilla-mobile/fenix/issues/12276#issuecomment-661648625) still reproduces the issue.

Here's an excerpt of those steps:

> The changed device name stays *until I restart Fenix, and a sync occurs*. To observe this, here are the steps to reproduce this issue:
>
> 1. Go to **Settings > Firefox Account**.
> 2. Tap on the device name field, press "OK" and force a sync on **BOTH** mobile and desktop.
> 3. Observe that the changed device name will show up in the Firefox Desktop Synced Tabs view.
> 4. Proceed to close and reopen Fenix. Then, repeat steps 1-2 to force a sync again.
> 5. Observe that the changed device name is reset to the default in the Firefox Desktop Synced Tabs view (in the format `Firefox <channel> on <device-model>`).

**Comment by SL-Lee** [comment]
This issue is still reproducible for me on Firefox **93.0.0-beta.2 (Build #2015833763)** and **94.0a1 (Build #2015833899)**.

**Comment by SL-Lee** [comment]
I'm going to close this issue preemptively since it appears to be fixed (refer to attached screenshot).

![](https://user-images.githubusercontent.com/45960387/154906700-672c12fb-5d0c-48f6-8021-5a324188f88b.png)
