### ISSUE TITLE
Janky layout on nytimes article while scrolling when toolbar is on top

### ISSUE THREAD

**Issue by dpalmeiro** [mozilla-mobile/fenix#12279]
On this site https://www.nytimes.com/2020/05/22/technology/google-antitrust.html there is a bottom banner asking you to login.  If you scroll the article the banner is very janky and constantly stuttering around.   In chrome, the banner never moves when scrolling the article.

**Comment by sheikh-azharuddin** [comment]
Works fine in latest nightly....

**Comment by dpalmeiro** [comment]
Attached a video describing what I mean.  This was with firefox preview nightly build 21860821 on a Pixel 2.

![janky](https://user-images.githubusercontent.com/37376204/86515102-bed45100-bde4-11ea-8a7a-e6fe79f37f1f.gif)

**Comment by sheikh-azharuddin** [comment]
Where is the video?

**Comment by sheikh-azharuddin** [comment]
Works fine here

![2020-07-04-20-59-34](https://user-images.githubusercontent.com/58127841/86515981-9f511e80-be0c-11ea-8b0a-31e71826e565.gif)

**Comment by vishalnandagopal** [comment]
Can confirm scrolling behavior is not up on this page.

**Comment by dpalmeiro** [comment]
> 
> 
> Works fine here
> 


If I move the toolbar to the bottom like you have it, the banner is no longer janky and I see smooth scrolling like in your gif.    Is your behaviour also smooth with the toolbar on top?

**Comment by sheikh-azharuddin** [comment]
@dpalmeiro yes correct with top toolbar there is some stuttering... Works fine with bottom bar

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
