### ISSUE TITLE
FNX2-15142 ⁃ [Bug] Pressing Back on Home Screen Closes the browser

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12286]
## Steps to reproduce
Open home screen 
Press back

### Expected behavior
The previous tab is opened (i think this was pre tab tray behaviour)

### Actual behavior
The browser just closes

### Device information
* Android device:Asus Zenfone
* Fenix version: Nightly

**Comment by Mugurell** [comment]
This is the expected behavior.
One could have no open tabs to which to go back to.

**Comment by Mugurell** [comment]
Closing this as per https://github.com/mozilla-mobile/fenix/issues/12286#issuecomment-654102854
