### ISSUE TITLE
FNX2-15143 ⁃ Show Synced Tabs after Normal And Private Tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12287]
### What is the user problem or growth opportunity you want to see solved?
Syced tabs are such a useful feature but right now it is difficult to use. Adding synced tabs to the tab tray as a third option will make it more comfortable to use and also switch between synced and non synced tabs 

### How do you know that this problem exists today? Why is this important?
Synced tabs are nice but difficult to use feature.

### Who will benefit from it?
Everyone who uses synced tabs

**Comment by SS1113** [comment]
Yes, such feature is already in consideration according one of the developers https://github.com/mozilla-mobile/fenix/issues/11995#issuecomment-650444399

**Comment by s-ankur** [comment]
Nice! Would love to see it implemented

**Comment by cadeyrn** [comment]
@jonalmeida The screenshots in #13893 shows that the synced tabs are below the regular tabs. Could these be moved to a third tab (regular tabs, private tabs, synced tabs) instead? I have hundreds of open tabs on other devices and most times I don't want to access these from my smartphone. But sometimes I want to access these so it's not an option to disable the synchronisation of tabs. Moving the synced tabs to a own tab would be great because my tabs view would keep clean and the only sometimes needed synced tabs would still be easy accessible.

**Comment by jonalmeida** [comment]
@cadeyrn that's great feedback! I wonder what @topotropic thinks about it.

**Comment by madb1lly** [comment]
Hi all,

Nice to to see synced tabs in the tab tray, it makes up for the lack of the Fennec awesomescreen/page whatever it was called. _However_ please can you make it so that individual devices can be expanded and collapsed like in #13449?

I second @cadeyrn's suggestion too, this will be much more pleasing. Was it Opera that someone showed this from a few months ago? Much nicer.

Cheers 🙂

**Comment by yoasif** [comment]
Mentioned previously in https://github.com/mozilla-mobile/fenix/issues/7913 - would definitely like to see this - the current UI leaves much to be desired. I actually missed it after turning it on initially in secret settings.

**Comment by yoasif** [comment]
> _However_ please can you make it so that individual devices can be expanded and collapsed like in #13449?

I think that is https://github.com/mozilla-mobile/fenix/issues/11402

**Comment by amkcpu** [comment]
I did a quick mock-up to try to visualize what this could look like (using the screenshot generously provided in #13893):
- A sync can be forced by tapping the "sync" floating action button 
- Devices can be collapsed/expanded (#11402) by tapping somewhere on the row where the respective device's name is. The arrow next the the device name also serves as status indicator.

<img src="https://user-images.githubusercontent.com/46764284/91031300-ac1a1380-e600-11ea-8958-3ea2163ba78e.png" width=350 />

**Comment by jonalmeida** [comment]
Hey folks, thanks for the feedback and ideas! I'm going to file a separate issue for showing Synced Tabs in a separate tab since we've used this one for showing synced tabs on the tabs tray.

You can follow along there! https://github.com/mozilla-mobile/fenix/issues/14117

**Comment by s-ankur** [comment]
Hi, is are the synced tabs supposed to disappear when you have no normal mode tabs? On Nightly 200825 06:07 (Build #2015759987)

**Comment by topotropic** [comment]
Thanks for the suggestion, @amkcpu – looking good to me. 

Now that we have a follow-up issue, can we close this one?

**Comment by Diana-Rus** [comment]
Hi, did the following verification for this one until the follow up is done.

@jonalmeida  - Could you please check the questions below

1. As @s-ankur said when there is no normal tab opened, the sync option is not available. Is this intended?
2. With sync option enabled, we do have in private browsing tabs tray all the sync options (at the moment in case you are connected with an account the devices are going to be displayed, user can open the domains in new private tab). Should it be present? Please check the below screen for when in private mode in private tab the same is applied when it is in normal mode with private tab.
<details closed><summary>Private mode-Private tabs tray-Connected with account</summary>

![Screenshot_20200827-162430_Firefox Nightly](https://user-images.githubusercontent.com/49859863/91448295-5ce31580-e882-11ea-9108-eb7f064791a0.jpg)
</details>

3. After logging in with an account from tabs tray: 
- user is redirected to browser's homescreen, in case the tabs tray is opened over the browser's homescreen
- user is redirected to Settings page, in case , in case the tabs tray is opened over an active tab
Shouldn't the user be redirected in either cases to the opened tabs tray?
4. At the moment "Reconnect to Sync" option is at Menu level, at Settings/Account. Wouldn't it be more easier to have the option available in tabs tray?
"Reconnect to sync" at menu level:
![image](https://user-images.githubusercontent.com/49859863/91474906-86f8ff80-e8a3-11ea-8ac9-08dd81070e42.png)

**Scenarios:**
**Normal Browsing mode**
1. Tabs tray - user not signed in - the "Sign in to sync" button is present ✔️
2. Sync option is not displayed when collection mode is enabled ✔️
3. Synced tabs present when sign in through QR code ✔️
4. Syncing snack-bar is displayed ❌ (is displayed over the navigation bar)
<details closed><summary></summary>

![Screenshot_20200827-195426](https://user-images.githubusercontent.com/49859863/91474650-2c5fa380-e8a3-11ea-9ce9-f731e8808d7f.png)
</details>

5. Synced tabs present when sign in through email address ✔️
6. Updates of synced tabs closing tabs, updating tabs with different site ✔️
**Private mode**
1. Tabs tray - user not signed in - the "Sign in to sync" button is present ✔️
2. Sync option is not displayed when collection mode is enabled ✔️
3. Synced tabs present when sign in through QR code ❌ - impacted by issue 14307
4. Syncing snack-bar is displayed ❌ (is displayed over the navigation bar)
5. Synced tabs present when sign in through email address ❌ - impacted by issue 14307
6. Updates of synced tabs closing tabs, updating tabs with different site ❌ - impacted by issue 14307

Note: Also while testing this encountered #14281 

I'll remove the qa-needed until further notice

**Comment by s-ankur** [comment]
For point 1, it seems unintended (see #14007)

**Comment by jonalmeida** [comment]
Thanks for the detailed break down @Diana-Rus ! I think we'll be fine with closing this issue and working on the follow-ups.

I've marked these bugs as blockers for releasing that you can find here: https://github.com/mozilla-mobile/fenix/issues/13892

**Comment by Diana-Rus** [comment]
Hi, @jonalmeida  thanks for looking, but could you also check the questions?
Depending on the answer for them there might be a need to create new tickets, or to be taken in consideration in the follow up feature request #14117 .

**Comment by jonalmeida** [comment]
@Diana-Rus so sorry I forgot to address those. Thanks for the ping!

> As @s-ankur said when there is no normal tab opened, the sync option is not available. Is this intended?

This is already filed as  #14007 as mentioned above.

> user is redirected to Settings page, in case , in case the tabs tray is opened over an active tab
> Shouldn't the user be redirected in either cases to the opened tabs tray?

This is undefined behaviour. Good catch! Definitely file it and cc myself and @topotropic to follow-up.

> At the moment "Reconnect to Sync" option is at Menu level and Settings/Account. Wouldn't it be more easier to have the option available in tabs tray?

I think we didn't want to consider this behaviour before, but we probably should now. Please file!
