### ISSUE TITLE
Bug] Fenix homescreen completely reloads everytime I get back to it or freshly launched

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12284]
## Steps to reproduce
Try to go to any website or Fenix settings and comeback and see the Fenix homescreen completely reload. And the "Save tabs to collection" also completely disappears for 1 or 2 seconds. Top Sites favicons reload, saved collections UI reloads, and just about everything...

### Expected behavior
Fenix homescreen shouldn't reload

### Actual behavior
Fenix homescreen reloads everytime I get back to it

Edit: This also happens when Fenix is launched. 

### Device information
* Android device: **Motorola One Power, Android 10**
* Fenix version: **`Nightly 200704 18:05`** and the migration build for Fennec **`null (Build #2015749827) AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7`**

![20200705](https://user-images.githubusercontent.com/42088907/86528168-13cfa000-be95-11ea-8acd-af7e9899a37f.gif)UNITO-UNDERSCORE!131317!

**Comment by ShatteredPixel** [comment]
I'm the reporter of this issue. Please let me know if you need more information. 

Thanks! :)

**Comment by eliserichards** [comment]
I created a "meta" bug for this and referenced both issues :) https://github.com/mozilla-mobile/fenix/issues/12642
