### ISSUE TITLE
FNX2-15137 ⁃ [Bug] (Regression): Fenix crashes when trying to open it through the device's launcher

### ISSUE THREAD

**Issue by WKSuperPower** [mozilla-mobile/fenix#12281]
## Steps to reproduce
Click the app's icon from the device's launcher

### Expected behavior
I want to know:

1) What is the Flag #8?
2) Why that Flag does not get handled by Fenix's .so libs?

### Actual behavior
I'm unable to open/access Fenix.

ed6ae751-8aaf-4d60-959a-d0c2411b207d
java.util.NoSuchElementException: List is empty.

* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=a5f05334f70e4d24a76200c94c0306d4
* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=2e8b916017644e6a940190b5ddec39a2
----
java.util.NoSuchElementException: List is empty.
at kotlin.collections.ArraysKt.first(Unknown Source)
at org.mozilla.fenix.components.searchengine.FenixSearchEngineProvider.getDefaultEngine(FenixSearchEngineProvider.kt:3)
at org.mozilla.fenix.home.HomeFragment$onViewCreated$2.invokeSuspend(HomeFragment.kt:9)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

##07-04 09:56:16.004 W/GeckoLinker(9662): /data/app/org.mozilla.fenix-2/lib/arm/libsoftokn3.so: unhandled flags #8 not handled

07-04 09:56:16.004 W/GeckoLinker(9662): /data/app/org.mozilla.fenix-2/lib/arm/libsoftokn3.so: Relocation to NULL @0x0002cffc for symbol "__cxa_type_match"

07-04 09:56:16.004 W/GeckoLinker(9662): /data/app/org.mozilla.fenix-2/lib/arm/libfreebl3.so: unhandled flags #8 not handled

07-04 09:56:16.004 W/GeckoLinker(9662): /data/app/org.mozilla.fenix-2/lib/arm/libfreebl3.so: Relocation to NULL @0x00051ffc for symbol "__cxa_type_match"

07-04 09:56:16.024 W/GeckoLinker(9662): /data/app/org.mozilla.fenix-2/lib/arm/libnssckbi.so: Relocation to NULL @0x00054ffc for symbol "__cxa_type_match"

# Device information
* Android device: 5.1.1 (API 22)
* Fenix version: Current

**Comment by Mugurell** [comment]
Thank you for the report and sorry for the problems you have.

The native stack trace I think is misleading.
There is a known issue regarding the default search engine which I think is responsible for the problem you're encountering.
You can follow the progress here https://github.com/mozilla-mobile/fenix/issues/11875
I think this will be soon fixed.

Keeping this ticket open just to verify the eventuality that the fix for https://github.com/mozilla-mobile/fenix/issues/11875 will not also fix this.

**Comment by WKSuperPower** [comment]
@Mugurell ,  I'm running into the #11875 since the upgrade from Fenix 5.2 to Fenix Nightly.

**Comment by WKSuperPower** [comment]
@Mugurell Maybe the native crashes happen due to the empty list.

**Comment by kbrosnan** [comment]
Not seeing any new reports of this crash using up to date builds.

**Comment by Mugurell** [comment]
Closing as per https://github.com/mozilla-mobile/fenix/issues/12281#issuecomment-659724768
