### ISSUE TITLE
An option to sync customized Fenix settings through Firefox account

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12283]
Currently Firefox account sync only supports syncing Bookmarks, History Logins, Open tabs. If the browser customization settings are also synced I'll be perfect for who install browser on multiple devices or keep re-installing the Browsers some reasons -- like when someone factory resets their devices; they don't have to set-up the browser from scratch or sign into a new device. 

Sync settings could include all the settings customised by the users in the main browser settings found in 3-dot menu > Settings as well as sub-settings found in different sections like `General`, `Privacy and security`, `Advanced`.

This could also include the custom search engines added by the users and the default ones set by them. 

And also sync different add-ons which are installed by the users so they don't have to remember to install dozens of add-ons they'd installed a few months ago when setting up their devices again. This feature is already available on desktop Firefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3075)

**Comment by lomomcat** [comment]
I Hope that add-ons can also be synchronized.😃

**Comment by SS1113** [comment]
@lomomcat I was gonna add that as well, don't know how I forgot it! 😅

Thanks for reminding! :)

**Comment by sheikh-azharuddin** [comment]
We need top sites and preferences synced too...

**Comment by SS1113** [comment]
Top sites syncing is already requested here: #7936 & https://github.com/mozilla-mobile/fenix/issues/10583

**Comment by sheikh-azharuddin** [comment]
Preferences?

**Comment by SS1113** [comment]
> Preferences?

Can you elaborate a bit more?

**Comment by sheikh-azharuddin** [comment]
I mean about:config settings

**Comment by SS1113** [comment]
> I mean about:config settings

Yeah, at first, I was thinking of requesting `about:config` settings as well. But I thought, they're experimental settings, don't know if Mozilla would consider adding that, thats why I didn't include that.

I don't even know if Mozilla is considering enabling`about:config` in the  Release channel or not.

**Comment by lomomcat** [comment]
@SS1113 Do you know **BasicAuth**?The account and password of a **BasicAuth** Page won't be synchronized to Firefox Sync in _**Fenix**_.

I have already reported this,but everyone ignored me.
[Issue#9257](https://github.com/mozilla-mobile/fenix/issues/9257)
[BasicAuth_demo](https://www.github.com/lomomcat/Leflex/tree/master/IMG_20200320_031627.jpg)

And maybe the text of **BasicAuth** login GUI can be translated to many languages.

Yours truly.

**Comment by ShatteredPixel** [comment]
I'm the reporter of this issue. Please let me know if I can provide you any more information.

Thanks. :)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810649

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
