### ISSUE TITLE
FNX2-15141 ⁃ Crash on "Open in Firefox"ing a custom tab

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12285]
1. On  clean install
1. Sign in with email
1. In the sign in custom tab, click open with firefox
1. Crash

Device: Asus Zenfone
Version: Firefox Nightly

**Comment by B0pol** [comment]
I can confirm, it happens with all custom tabs.

**Comment by Raamakrishnan** [comment]
I am seeing this as well. I feel like this is the crash log that will be needed https://crash-stats.mozilla.org/report/index/6decf0fb-cb86-4d88-89df-c49de0200706

**Comment by rafalopilowski1** [comment]
Duplicate of #12277

**Comment by ekager** [comment]
closing for #12277
