### ISSUE TITLE
Automatically open sent tabs

### ISSUE THREAD

**Issue by CharoSW** [mozilla-mobile/fenix#12294]
### What is the user problem or growth opportunity you want to see solved?
Tabs sent to the device should be automatically opened in the tab list rather than popping up a notification which you then have to interact with.  The current behaviour runs counter to how the desktop version works where tabs are added automatically.

### How do you know that this problem exists today? Why is this important?
It's important for ease of use.  As #11805 notes it can be annoying when you've sent a lot of tabs and have to click through them all to open them.  However, where that bug could be solved by making a single notification for all sent tabs, what I am proposing does away with the unnecessary user interaction.  After all you already knowingly sent Fenix the tabs.

### Who will benefit from it?
People that regularly send tabs between devices.  It also would have an additional effect of working between the various release channels as currently the notification opens in the default browser which may not be the browser you intended the tab to be sent to.

### Related use cases
 - https://github.com/mozilla-mobile/fenix/issues/11152

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3094)

**Comment by 532910** [comment]
One more problem with the current behaviour:
notifications can be accidentally cleared.

**Comment by tomyummmm** [comment]
Is there any progress for this? It's difficult and annoying when i am trying to send a large number of tabs >20 from desktop to phone.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810642

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
