### ISSUE TITLE
FNX-4887 ⁃ [Bug] preference_recommended_settings_summary in strings.xml uses non-supported markup

### ISSUE THREAD

**Issue by Pike** [mozilla-mobile/fenix#1229]
In 

https://github.com/mozilla-mobile/fenix/blob/c2d0a6e265e2d51017a4480069d6ed3ba594d179/app/src/main/res/values/strings.xml#L148-L160

the string uses top-level markup. Sadly, we don't support that in our l10n toolchain.

The usual way to work around that is to put the markup fragment into a CDATA section.

CC @pocmo as that's part of the agreed feature set for Android. @boek wrote the implementation for the string in #1181.

Johan found this while working on #1220.

The quick work-around would be to move the string outside of `strings.xml`, like https://gist.github.com/Pike/8b6ef223ee58a2c691802c9155d0f175

**Comment by mheubusch** [comment]
@Amejia481 The copy in the strings isn't ready - I know you met with Bram today but I have not reviewed and signed off on these strings. Can you back out just the strings for Permissions settings out so L10n is not blocked?

**Comment by Amejia481** [comment]
@mheubusch sure, sorry for the trouble.
