### ISSUE TITLE
While a site loads, its tab tray preview can be the favicon instead of a blank white rectangle

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12290]
### What is the user problem or growth opportunity you want to see solved?
When you open tab tray, and the tabs are not loaded, you will see a white rectangle. I think we would benefit a lot from changing this white rectangle to the favicon of the site, since it will be recognized far more easily instead of reading title and the url.

### How do you know that this problem exists today? Why is this important?
A comment on reddit suggested it here https://www.reddit.com/r/firefox/comments/hevbxc/comment/fvujulj. It had 10 upvotes so atleast that many people care about it

### Who will benefit from it?
It can also help in accessibility, if people find it hard to read etc, they can use the favicon for reference until site loads.

**Comment by cadeyrn** [comment]
> When you open tab tray, and the tabs are not loaded, you will see a white rectangle.

If you don't talk about an outdated version of Fenix then it's not only a white rectangle, there is a globe icon in the middle of the thumbnail area…

And to be honest it doesn't make much sense to me: Either there is a thumbnail or there is a reason why the thumbnail can't be loaded. But if the thumbnail can't be loaded why should it be possible to load the favicon? Either it's possible to load an image from the memory/storage or it's not possible. I don't the difference why it should be possible to load the one but nt the other.

**Comment by s-ankur** [comment]
@cadeyrn about the rectangles, apparently it was another bug. What Im suggesting is instead of a globe icon you can show the favicon until the site loads. Im assuming that the favicon is available like for top sites etc

**Comment by cadeyrn** [comment]
Just like a thumbnail a favicon has also to be fetched either of network or storage/memory. And to show something until the site loads makes also no sense to me because then first the favicon will be shown and then a few hundred milliseconds later the thumbnail. This causes flicker and would be a bad user experience…

**Comment by s-ankur** [comment]
Ahh ok then. Ill close the issue

**Comment by SS1113** [comment]
@s-ankur You should not close the issues until you hear from the Firefox developers team, I think. :)

**Comment by SS1113** [comment]
Thanks @s-ankur for bringing this feature request from Reddit to GitHub. This is really important as the developers work here and you'll be letting them know that this type of feature request exists. Thanks for this again! :) Keep up the good work! :)


If I have to add my comments to this feature request then I think those white rectangles should be replaced with letters or existing Top Sites' already fetched favicons icons. Fenix did this before, IIRC, having empty white boxes is no use, if at least websites' first letter is displayed then it'd be useful and I think Fenix could do it without any major performance penalties as it only needs to know what letter the website is starting with.

**Comment by s-ankur** [comment]
Another comment, with 10 upvotes https://www.reddit.com/r/firefox/comments/hlfjmc/comment/fwzegwe

**Comment by cadeyrn** [comment]
I can't see how this reddit link relates to your issue, there is no mention of a favicon during page load at all… 🤔

**Comment by s-ankur** [comment]
Closing as no longer relevant
