### ISSUE TITLE
[Bug] wrong error message

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12296]
## Steps to reproduce
Browse the below website it shows an error that certificate is invalid whereas if I browse the same URL in chrome/edge it shows certificate is valid but the site is using TLS 1.0 protocol which is by default not allowed in Firefox and hence the error but the message is not correct. It should show the site is using old ciphers etc. 

Other than that accept the risk and continue also not working 

https://www.sevecek.com/EnglishPages/Lists/Posts/Post.aspx?ID=57

### Expected behavior
Site should show proper error message

### Actual behavior
Site is showing non relevant error message.. Kind of generic message. 

### Device information
* Android device: ? A10
* Fenix version: ? Firefox nightly latest

![Screenshot](https://user-images.githubusercontent.com/58127841/86535498-4a76dc00-bed0-11ea-9a1d-c49ed3cc602d.jpg)UNITO-UNDERSCORE!20200705-202214!

![Screenshot](https://user-images.githubusercontent.com/58127841/86535510-59f62500-bed0-11ea-8eba-5f1fd44e6d06.jpg)UNITO-UNDERSCORE!20200705-203058!

**Comment by lordgurke** [comment]
If you open a website with an expired certificate, the same message is shown. And this message is simply wrong.
To be honest, when I tap the "advanced" button, I expect to get a proper error message and an option to view the certificate BEFORE I "Accept the risk". The proper error message can be shown in a smaller font with less contrast, and could come from directly from the internal SSL library.
