### ISSUE TITLE
[Bug] Debug app opens incorrect playstore link

### ISSUE THREAD

**Issue by nikit19** [mozilla-mobile/fenix#12292]
## Steps to reproduce
Open setting -> rate app on Google Play

### Expected behavior
Should open the playstore link of the app

### Actual behavior
Opens the playstore link for an app that is not there on the playstore (Debug app id)

### Device information
* Android device: Pixel XL
* Fenix version: 1.0.2028 (Build #1)

I would like to work on this issue.

**Comment by boek** [comment]
Mirroring my comment from the PR:

Hey @nikit19, after some consideration I don't think this is the right approach. I agree the current experience could be confusing but debug builds are probably not something we should optimize or add code complexity for.
