### ISSUE TITLE
New user "Synced Tab" experience

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12300]
## User Story
* As a user who isn't signed into a Firefox Account, when I tap on the "Synced Tab" toolbar option, I am taken to a blank page telling me to connect with a Firefox account without giving me an easy way to connect. I should either see a "sign-in to sync" button on that page OR "Synced Tab" should be hidden from the toolbar for me.

### Acceptance Criteria
* I know what to do when I tap on the synced tab page. 
OR
* I don't see toolbar menu options that aren't relevant to me.

**Comment by BranescuMihai** [comment]
The same requirement is in https://github.com/mozilla-mobile/fenix/issues/11498, which I'm working on.

**Comment by sheikh-azharuddin** [comment]
Why just for new users why not all... I had requested for this earlier.... The synced tabs should not be visible for users who have not enabled the option to sync open tabs..
 #11995

**Comment by cadeyrn** [comment]
@sheikh-azharuddin What you said is one of the possible solutions mentioned in the user story and acceptance criteria. _New user_ means _not signed in_ in this context. I am pretty sure they won't implement a different behaviour based on the age of the profile…

**Comment by vesta0** [comment]
I see how that was confusing. I have removed the "new" from the user story in comment 0. Thanks for the feedback!

**Comment by betsymi** [comment]
I'm chatting with @topotropic about this before recommending an approach.

**Comment by betsymi** [comment]
It appears that we [already have a design](https://app.abstract.com/projects/8afc4b50-7667-11e9-94ba-3558f8596822/branches/master/commits/72ed314cb3b094e510d264a18e99870147787fa0/files/235D0569-D4AF-43C9-9256-6C6956C7CF2C/layers/96A5BA27-8D07-4A00-9793-62D84906076F?mode=design&sha=72ed314cb3b094e510d264a18e99870147787fa0) to cover this use case. 

![image](https://user-images.githubusercontent.com/43555492/86815407-3d7cf880-c048-11ea-8b07-1fcfa02c06a2.png)

**Comment by vesta0** [comment]
@betsymi don't you love it when that happens?! 

If this is `eng:ready` please feel free to remove the 'needs:string` and 'needs: UX-feedback`

**Comment by vesta0** [comment]
addressed in #11498
