### ISSUE TITLE
[Bug] general.useragent.override is not working in Android Beta

### ISSUE THREAD

**Issue by Crandel** [mozilla-mobile/fenix#12303]
## Steps to reproduce
Open about:config
Create general.useragent.override key with custom string as value

### Expected behavior
user-agent header could be changed

### Actual behavior
user-agent header doesn`t change

### Device information
* Android device: 9
* Fenix version: Firefox Beta 79.0.0-beta.5

![2](https://user-images.githubusercontent.com/4005032/86569773-78a2fd00-bf5e-11ea-91a7-b820d965d2ad.jpg)
![1](https://user-images.githubusercontent.com/4005032/86569792-7e98de00-bf5e-11ea-81f7-5932376c683c.jpg)

**Comment by sheikh-azharuddin** [comment]
This is working fine in nightly version....
It is detecting as Chrome after copying the user agent from Chrome canary browser... Previously i had set the value from desktop chrome version... After setting it I was getting desktop style search result by default 😂
So you need to open another browser like Chrome /edge, copy the user agent.. Create a new string in Firefox preference and set the user agent. It should work

![Screenshot_20200706-233643](https://user-images.githubusercontent.com/58127841/86624793-774fef80-bfb3-11ea-92d8-8d64c2315ee4.jpg)
![Screenshot_20200706-233625](https://user-images.githubusercontent.com/58127841/86624803-7c14a380-bfb3-11ea-8e87-59e417b704cf.jpg)

**Comment by sheikh-azharuddin** [comment]
And I love this hack... Search results are now better and looks like Chrome android version... Also spoofing user agent protects from fingerprinting... Attaching screen with no user agent (firefox default) and chrome user agent..
Looks better now!
 
No user agent 
![Screenshot_20200706-234303](https://user-images.githubusercontent.com/58127841/86625462-9e5af100-bfb4-11ea-8003-fe44fe24a3bd.jpg)

Chrome user agent 
![Screenshot_20200706-234308](https://user-images.githubusercontent.com/58127841/86625477-a3b83b80-bfb4-11ea-9f9a-73803f129c16.jpg)

**Comment by Crandel** [comment]
@sheikh-azharuddin which nightly version do you have. I have also nightly converted from preview and its not working for me
![Screenshot_20200706-204309](https://user-images.githubusercontent.com/4005032/86628053-d5cb9c80-bfb8-11ea-9e88-ea10da0a54e2.jpg)

**Comment by sheikh-azharuddin** [comment]
![Screenshot_20200707-002118](https://user-images.githubusercontent.com/58127841/86628625-af5a3100-bfb9-11ea-97f1-251f09c77ddb.jpg)

**Comment by Crandel** [comment]
I forgot I enabled `privacy.resistFingerprinting`. Will wait for User-agent switcher add-on

**Comment by e-t-l** [comment]
@Crandel I'm also having trouble with UA on mobile, so just to confirm I understand: Does RFP prevent UA override from working at all? In that case, does it just send the default FF UA?
