### ISSUE TITLE
FNX2-15160 ⁃ [Bug]YouTube High definition doesn't work properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12305]
## Prerequisites
YouTube High definition should be installed
Set the video quality to 720p
Set the Volume to mute

## Steps to reproduce
Open a video from Youtube
Check the picture quality and if the video is muted

### Expected behavior
The playback picture quality should match the ones selected by the user
The video should be muted

### Actual behavior
The playback picture quality doesn't match the ones selected by the user
The video isn't muted 

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly Build 200706 from 7/6

► Video
![20200706-121122](https://user-images.githubusercontent.com/51314259/86577862-8f0f7f80-bf83-11ea-9aff-37f66297eb0e.gif)

**Comment by klint** [comment]
Autoplay doesn't work for me either.

**Comment by csadilek** [comment]
Filed in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1650897

**Comment by csadilek** [comment]
This is fixed now in latest Nightly (200716). Need to reload to apply a settings change but that appears to be expected, same in Fennec.

**Comment by Diana-Rus** [comment]
Hi, verified the issue on latest Nightly 200720:
- Samsung Galaxy S9 (Android 8)
   - The playback picture quality should match the ones selected by the user ✔️
   - The video should be muted ❌
- Google Pixel 3 XL (Android 9)
   - The playback picture quality should match the ones selected by the user ✔️
   - The video should be muted ✔️

**Comment by csadilek** [comment]
@Diana-Rus Thank you! I can't seem to reproduce, but also don't have an S9. Would you mind trying this in Fennec as well so we know if this is specific to Fenix when you get a chance?

I'd suggest filing a follow up for the mute problem as the more general problem here seems fixed (all controls not working).

**Comment by csadilek** [comment]
OK, filed a follow-up for the "mute" issue: https://github.com/mozilla-mobile/fenix/issues/12897 so we can close this ticket.

**Comment by AndiAJ** [comment]
I can still repro the video playback quality problem on Fenix Beta 80.0.0-beta-1 using a OnePlus A3 (Android 6.0.1)
