### ISSUE TITLE
[Bug] [Discoverability Experiment] Users from non-English locales are wrongly enrolled in the experiment

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#12308]
**[Affected Versions]:**

* Firefox Preview Nightly 200706 (Build #21880609) (bafa9299b) GV: 80.0a1-20200702094606

**[Affected Platforms]:**

* Android 9 (Samsung Galaxy S8)

**[Prerequisites]:**

* The mobile device is connected to the computer used and both are set for ADB commands.
* Have a way to observe Logcat logs.
* The browser is open.

**[Steps to reproduce]:**

1. Open the terminal.
1. Enter the following commands:

`adb shell am start -n org.mozilla.fenix.nightly/mozilla.components.service.experiments.debug.ExperimentsDebugActivity --es setKintoInstance staging`

`adb shell am start -n org.mozilla.fenix.nightly/mozilla.components.service.experiments.debug.ExperimentsDebugActivity --ez updateExperiments true`

1. Observe the enrollment logs in Logcat.

**[Expected results]:**

* The logs read that there are no active experiments.

**[Actual results]:**

* The logs read that the user is randomly enrolled in one of the two branches.
(e.g. “Activating experiment - id="fenix-search-widget-debug", branch="treatment_cfr")

**[Note]:**

* In the Treatment branch, the helper popup is displayed after three searches.
* Telemetry sent afterwards has the fenix-search-widget experiment listed as active.

**Comment by travis79** [comment]
This was most likely due to a malformed regex that was entered into the locale match field in the recipe.  I also didn't see that the addition of this matching field was reviewed/deployed so it may also have been overlooked and changed but not deployed.

**Comment by heres-maria** [comment]
I have tried testing enrollment using both Firefox Nightly (org.mozilla.fenix) and the old Firefox Preview Nightly (org.mozilla.fenix.nightly). Both versions were tested using both the stage and production Kinto configurations. 

It seems simulating natural enrollment is not possible at the moment - using the steps in the bug report above, app id modified in the case of Firefox Nightly - neither the English locale versions, nor other language locales were enrolled in the experiment using either production or stage servers.

Using the override command (`adb shell am start -n org.mozilla.fenix/mozilla.components.service.experiments.debug.ExperimentsDebugActivity --es overrideExperiment fenix-search-widget --es branch treatment_cfr`) will seemingly bypass all filters, so it's not a reliable way of testing this particular bug.

I'm including a logcat of an attempt to naturally enroll using the stage server using Firefox Nightly. The production enrollment attempt can be observed at the beginning, since it automatically happens at app launch.
[Firefox Nightly stage.txt](https://github.com/mozilla-mobile/fenix/files/4890326/Firefox.Nightly.stage.txt)

**Comment by heres-maria** [comment]
I am including a more complete log since the one attached in the last comment had been filtered for the "exp" string for testing purposes.
[log_2020-07-08_16-27-34.34.txt](https://github.com/mozilla-mobile/fenix/files/4890919/log_2020-07-08_16-27-34.34.txt)

**Comment by heres-maria** [comment]
This issue is no longer reproducible.
Users on the English locales (e.g US, CA, GB, NZ ) are now enrolled, while those on others are not (e.g. RO). Having more than one language in the system language list does not influence the result, with the default language being enrolled or not enrolled as it should.
Tested using Samsung Galaxy S8 (Android 9) on Firefox Nightly 200709 using the production configuration.
As a result, I am closing this issue.
