### ISSUE TITLE
Remember the state of the Home Screen: Scroll Position and Expanded Collections

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12310]
### What is the user problem or growth opportunity you want to see solved?
Right now the usability of the home screen is hampered by the fact that you need to expand the collection each and every time you want to access a tab. An easy fix for this would be to remeber which collection is expanded. In addition it would also be helpful to remember the scroll position on the screen.

### How do you know that this problem exists today? Why is this important?
I find it cumbersome to access my collections

### Who will benefit from it?
Anyone who used collections

**Comment by AmyYLee** [comment]
@topotropic for feedback.
