### ISSUE TITLE
FNX-13360 ⁃ [Bug] Sentence in French truncated on nightly welcome screen

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#12316]
## Steps to reproduce
Install latest Fenix nightly 

### Expected behavior
No visual glitches on welcome screen

### Actual behavior
last part of sentence in French is truncated
![image](https://user-images.githubusercontent.com/218971/86614068-ba5d9300-bfb2-11ea-8c94-37202662935f.png)

### Device information
* Android device: Redmi Note 7 with Android 9
* Fenix version: ?

**Comment by Diana-Rus** [comment]
Hi, verified as fixed on latest Nightly 7/8 with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8).

<details closed>
<summary>Samsung Galaxy S9 (Android 8) - Light theme - set dpi to 370</summary>

![Screenshot_20200708-105154_Firefox Nightly](https://user-images.githubusercontent.com/49859863/86894059-2fdc7700-c10b-11ea-8a6a-b08aac8e2a72.jpg)
</details> 
<details closed>
<summary>Samsung Galaxy S9 (Android 8)- Dark Theme - set dpi to 370</summary>

![Screenshot_20200708-105318_Firefox Nightly](https://user-images.githubusercontent.com/49859863/86894069-34089480-c10b-11ea-96ac-7afc93d914dd.jpg)
</details> 
<details closed>
<summary>Google Pixel 3 XL (Android 9) set dpi to 390</summary>

![Screenshot_20200708-105954](https://user-images.githubusercontent.com/49859863/86894085-3a970c00-c10b-11ea-88e4-3208a489dc2e.png)
</details>
