### ISSUE TITLE
FNX2-15168 ⁃ [Bug] long press menu shows search in edge

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12319]
## Steps to reproduce
My default browser is set to Firefox only however when I am long pressing any word in Firefox website articles it is showing search in edge and search in Firefox is under under 3dot menu. Any reason why search in edge showing in main item list instead of Firefox? 

### Expected behavior
Search in Firefox should be shown in default long press primary menu and not in secondary menu

### Actual behavior
Search in Firefox shows in secondary menu list instead of primary in long press menu

### Device information
* Android device: ? A10
* Fenix version: ?latest nightly 

![Screenshot](https://user-images.githubusercontent.com/58127841/86620272-92b6fc80-bfab-11ea-8185-fcec7051d7d1.jpg)UNITO-UNDERSCORE!20200706-223711!

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/10466
