### ISSUE TITLE
[Bug] The dialog for delete the last tab in a collection, contains the "collection" word twice when this is called "Collection x"

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12339]
## Steps to reproduce
1. Launch Firefox;
1. Save one page in a collection with the custom name: "Collection x";
1. Delete the page from the previous step, by tapping the "x" button;
1. Observe the dialog's question;
    1. Expected behavior
Delete Collection x?
    1. Actual behavior
Delete collection Collection x?
    1. Screenshot
![Screenshot](https://user-images.githubusercontent.com/48799384/86771129-5f7f7680-c05a-11ea-9e50-6bc8bd007173.png)UNITO-UNDERSCORE!20200707-111628!

### Notes
When deleting the collection from the three-dot menu, the dialog's question is: "Are you sure you want to delete Collection 1?", so there is no duplicated "collection" word.

### Device information
* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 200707 GV 80, from 7/7

**Comment by sheikh-azharuddin** [comment]
What if the collection name is not collection X? In that case removing the word collection won't create confusion? ? ? 

What Firefox team can do is to set the collection name in bold letter to distinguish from the word collection

**Comment by ebalazs-sv** [comment]
> What if the collection name is not collection X? In that case removing the word collection won't create confusion? ? ?

As mentioned in the description's notes, this is already the case for when deleting the collection from the three-dot menu.

**Comment by betsymi** [comment]
Correct copy should be: 

**Delete %1$s?**

Deleting this tab will delete the entire collection. You can create new collections at any time.

CANCEL | DELETE

**Comment by ebalazs-sv** [comment]
Hi! This issue is verified as fixed on Nightly 200805 GV 81.0a1 from 8/5 with Motorola Moto G6 (Android 8).
I filed a new related issue: https://github.com/mozilla-mobile/fenix/issues/13305.
