### ISSUE TITLE
FNX2-15173 ⁃ [Bug] When there is only one search engine, "Search engine settings" is missing in search mode

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12335]
## Steps to reproduce
1. Launch Fenix and go to Settings - Search;
1. Delete all search engines except one;
1. Open search;
    1. Expected behavior
The "Search engine settings" is displayed in search mode, when there is only one search engine.
    1. Actual behavior
The "Search engine settings" is missing in search mode, when there is only one search engine.
    1. Screenshot
![Screenshot](https://user-images.githubusercontent.com/48799384/86735898-cc374880-c03b-11ea-9f6d-6df03567c366.png)UNITO-UNDERSCORE!20200707-102124!

### Device information
* Android device: Google Pixel 2 (Android 9), Huawei P9 Lite (Android 7);
* Fenix version: Nightly 200707 GV 80, from 7/7

**Comment by mcarare** [comment]
This seems to be missing also when you have all search engines, also reproducible in Beta.

**Comment by BranescuMihai** [comment]
Since 'Search engine settings' is part of the Search Engine list, that was decided to be dismissed when there is only one engine available (https://github.com/mozilla-mobile/fenix/issues/10401#issuecomment-641044895), what is the expected behaviour? Always show the Search engine settings button?

**Comment by AmyYLee** [comment]
@brampitoyo for feedback

**Comment by brampitoyo** [comment]
@ebalazs-sv @BranescuMihai I can confirm that this behaviour works as intended.

When there’s only one search engine available, the search shortcuts button isn’t useful in any way (ie. you’d only be able to select the same search engine that you have already selected, which does nothing). In this specific scenario, this search shortcuts button shouldn’t show up.
