### ISSUE TITLE
[UX feedback] Issues related to zooming behaviour on Fenix

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12332]
## Steps to reproduce
1. Open Wikipedia articles or any website
1. Try to pinch-out to zoom-in 
1. Try to move the zoomed-in content to the right & left and now try to zoom in and out 
1. Observe that Fenix can't zoom in or out. 

This isn't the case with Chrome browser or any other browser based on Chromium/Blink. Chrome browser's behaviour is what I expect other browsers to behave like because not only I and other users will be or might be moving to Fenix will expect this behaviour but also there's a practical use case in it. Let's say you need to zoom in & out on the parts of the website continuosly and see the contents without lifting the fingers this would be really helpful. Lifting and zooming in and out everytime is impractical/tiring and cumbersome to users. This was the case in Fennec as well and now it is in Fenix too; I really want this to behave like Chrome/Chromium Browser**s**. And not to mention even image/photo gallery viewers act this way for example Google Photos, [Simple Gallery](https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery) when zoomed in & out on the images.

I think I should have reported this when the force "Zoom in on all websites" on website which don't support it was being designed. But nevertheless I'm reporting now, the zoom feature on Fenix feels very broken to me. And not to mention it feels very frustrating to me.

Attaching two GIFs one on Fenix and one on Chrome browser; let me know if you need higher quality videos. :grinning:

Chrome browser's zoom in & out behaviour:
![20200707](https://user-images.githubusercontent.com/42088907/86708535-8dd46600-c008-11ea-8faa-dd1d393399d0.gif)UNITO-UNDERSCORE!094339!

Fenix's zoom in & out behaviour: 

![20200707](https://user-images.githubusercontent.com/42088907/86708860-dee45a00-c008-11ea-9313-ceb479cdb406.gif)UNITO-UNDERSCORE!094625!

**Comment by ShatteredPixel** [comment]
I am the reporter of this issue. Please let me know if I can provide you any more information. Thanks. :)
