### ISSUE TITLE
Https everywhere

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12347]
### What is the user problem or growth opportunity you want to see solved?
The https everywhere add on by default tries to redirect to https version of a website and if it does not exist it falls back to http. Firefox has 2 preference items in about:config with same behaviour or i would say even better because the add on works for certain domains only whereas the preferences works for any domain.. So when Firefox has such awesome feature built in why should any user or we install a 3rd party add-on. What I suggest you can promote this feature just like brave and bring it to the main settings with a toogle like brave. When the toggle is on both preference value will set to True. 

dom.security.https_only_mode
dom.security.https_only_mode_ever_enabled

### How do you know that this problem exists today? Why is this important?
Currently user need to install a 3rd party add on which has permission to read site data.. When Firefox has the feature built in why should we rely on 3rd party extensions. Adding this feature i.e. Bringing to front end setting through a toggle will make a headline in several security websites... Firefox added this:sweat_smile:.. This will increase confidence with new users who go through same articles where several security issues were highlighted  both for chrome and brave... This will also increase user base. 

### Who will benefit from it?
All users.

**Comment by Amejia481** [comment]
Closed in favour of https://github.com/mozilla-mobile/fenix/issues/16952
