### ISSUE TITLE
Show the download progress size in kB, MB, GB, etc. instead of percentage

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12346]
Currently Fenix doesn't show the download size but instead shows the percentage and a progress bar with respect to how much the file has been downloaded but if Fenix showed the download size in kB, MB, GB, etc. and it's progress like how Chrome browser does it. It'll be really helpful. 

For example the file has downloaded;

**`3 kB / 500 kB`**, **`20 MB / 500 MB`**, **`1GB / 10 GB`** and so on...

See the screenshots for clarification.

![Screenshot](https://user-images.githubusercontent.com/42088907/86806161-1fbf8b80-c068-11ea-8985-a238f47d7f7e.jpg)UNITO-UNDERSCORE!20200707!UNITO-UNDERSCORE!210144!
![Screenshot](https://user-images.githubusercontent.com/42088907/86806178-23531280-c068-11ea-98a5-88f61cd2696f.jpg)UNITO-UNDERSCORE!20200707!UNITO-UNDERSCORE!210248!

- - -
P.S.  To be really honest until now I always thought that Fenix did this but after trying to get the screenshots for filing this issue I realized that it isn't the case. I thought that only in this issue  https://github.com/mozilla-mobile/fenix/issues/11107 the file size is not being shown but after seeing it now I realized Fenix doesn't do this; it doesn't show file size at all; it only shows a progress bar and a percentage in the notification. It really caused a lot of confusion between me and the developers, wait, actually it was just me who was confused. Sorry... :grinning:
This confusion caused because I mostly use external third-party download managers, so I download files very rarely with Fenix. I always thought that how could Fenix be missing such an useful feature. Or so...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3169)

**Comment by SS1113** [comment]
CC @Amejia481 I have filed the new issue for download size progress in the notification bar instead of percentage. Is it correct? Does conveys the idea clearly that we were taking about?

**Comment by Amejia481** [comment]
@SS1113  Thanks for filing this, yes the idea it's clear expressed :)

**Comment by ShatteredPixel** [comment]
Hi, I'm the reporter of this issue. Please let me know if you need more information. Sorry for deleting the GitHub account out of nowhere. It was very irresponsible of me!

Thank you! :)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812809

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
