### ISSUE TITLE
[Bug] when started for first time the written "Firefox Browser" is not visible using dark theme

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#12349]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1651015

Screen shot on Bugzilla

Steps to reproduce:

When I start Firefox on dark theme, the written "Firefox Browser" (beside the logo) is violet thus is not quite visible. After I open a new tab, the written is now white and is readable. The problem does not recur until firefox is completely closed and restarted

Actual results:

the written "Firefox Browser" is violet on a dark background

Expected results:

the written "Firefox Browser" should be white

https://bugzilla.mozilla.org/attachment.cgi?id=9161815

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
