### ISSUE TITLE
[Bug] anotate or remove getGenericSumoURLForTopic

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#12354]
I tracked down the source of the SUMO link failure and there are two similar functions `getSumoURLForTopic` and `getGenericSumoURLForTopic`. The generic function drops some parameters that SUMO expects to see. Assuming that SUMO can handle the  `getSumoURLForTopic` format for [URLs that have previously used the `getGeneric`](https://github.com/mozilla-mobile/fenix/search?q=getGenericSumoURLForTopic&unscoped_q=getGenericSumoURLForTopic)  it would make sense to remove this function as it is a footgun. 

The other option is to place a here be dragons comment that the `getGenericSumoURLForTopic` should only be used with explicit permission from the SUMO team.

@sblatz thoughts on the trade-offs here?

**Comment by sblatz** [comment]
If I'm understanding this correctly, you're saying that `getGenericSumoURLForTopic` should never be necessary? All topics should properly resolve if we exclusively use ` getSumoURLForTopic`?

**Comment by kbrosnan** [comment]
I believe so. It would need some testing to verify that assumption.
