### ISSUE TITLE
FNX2-15185 ⁃ [Bug] URL copied from reader mode is useless: hard-coded as `moz-extension://...`

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#12353]
## Steps to reproduce
* Load a page
* Enter reader mode
* After page load, long press on URL
* Select "copy"
* (go see what's in your clipboard by clicking URL bar and seeing clipboard suggestion or pasting it somewhere)

### Expected behavior
URL is original page URL

### Actual behavior
URL is reader mode URL: `moz-extension://4cb11be8-83cb-41af-81c3-58e30a4717ab/readerview.html?url=https%3A%2F%2Fwww.nytimes.com%2F2020%2F07%2F07%2Fworld%2Fcoronavirus-updates.html&id=137438953892`

This behavior does not appear to apply to sharing the URL.

### Device information
* Android device: P2
* Fenix version: Nightly 200706

**Comment by csadilek** [comment]
See https://github.com/mozilla-mobile/android-components/issues/2879#issuecomment-649101920 for a way to fix this with protocol headers.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 7/9** with **Google Pixel 4 XL (10).**
