### ISSUE TITLE
[Bug] Find in Page search box is not properly sized in landscape

### ISSUE THREAD

**Issue by TejaswiKarasani** [mozilla-mobile/fenix#12357]
## Steps to reproduce
1)Open app in landscape
2)Load a website
3)Click on three dot
4)Click on Find In Page

### Expected behavior
![image](https://user-images.githubusercontent.com/46127128/86825488-10166600-c0ad-11ea-8304-eeb20cc3622c.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/46127128/86825722-52d83e00-c0ad-11ea-9d45-227bd440fd81.png)

### Device information
* Android device: Redmi MI A2 Android 9
* Fenix version: Gecko Nightly Debug

**Comment by Diana-Rus** [comment]
Reproducible with Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9), it has been at some point fixed through issue: #4587 
The same outcome is present when using custom tabs.
