### ISSUE TITLE
FNX-13397 ⁃ [Bug] Constant crash when using "open in firefox nightly"

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#12350]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1651069

Happened when I was using twitter.

Steps to reproduce:

1- find a tweet with a link

2- click on the link, then click on "open in firefox nightly"

3 - crashes every time.

I got a notification to download the new firefox nightly as the old one I was using was going to be discontinued, so this issue is in the new one, firefox nightly 79.

**Comment by st3fan** [comment]
May not be a blocker if this does not happen in 79 beta4/5

**Comment by ekager** [comment]
Dupe of #12311 and a likely regression from AC browser store refactoring
