### ISSUE TITLE
Can't send multiple tabs from desktop to Fenix

### ISSUE THREAD

**Issue by padenot** [mozilla-mobile/fenix#12351]
## Steps to reproduce
* Have a Firefox Desktop connected to an Fx Account, and Fenix also connected to the same Fx Account.
* Select two tabs on the Firefox Desktop, right click, "Send 2 tabs to Device", choose the Fenix

### Expected behavior
Two tabs are sent / received.

### Actual behavior
Only the second tab is received.

### Device information
* Android device: Sony XZ1 Compact, android 9
* Fenix version: Latest as of today:

```
Nightly 200707 06:01 (Build #21890608)
AC: 49.0.20200706130124, e4c11aa23
GV: 80.0a1-20200705095345
AS: 61.0.7
```

**Comment by padenot** [comment]
I tried again, and in fact it's just quite unreliable. Even sending tabs one by one doesn't really work it seems.

**Comment by julienw** [comment]
My experience is that if you send enough tabs, the notifications are grouped. Then clicking on the "grouped notification" (as opposed to clicking on a specific one) opens Firefox, but then nothing more happens. I believe Firefox itself should somehow propose to open all received tabs.
This would also make the migration process less painful, by making it easier to move all tabs from one instance to another.

**Comment by ekager** [comment]
Also see #12294

**Comment by jonalmeida** [comment]
> I tried again, and in fact it's just quite unreliable. Even sending tabs one by one doesn't really work it seems.

@padenot based on your comment, it sounds like you were experiencing some intermittent failures from the service at the time. Will close this for now unless you feel strongly about it.

**Comment by padenot** [comment]
Nope, not fixed, it's as broken as it was. When doing this, I have to go to the settings, go into my Fx Account, and force the synchronization, and then tap the notification (this seems to be #12294), and then I have the tab (or tabs, if I sent more than one).
