### ISSUE TITLE
[GH Member Contributor only] [1 min low effort to close, low priority] Update GH Description to Firefox Nightly instead of Preview.

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#12369]
There's a gear here:
![image](https://user-images.githubusercontent.com/38327267/86852741-d2154400-c0a4-11ea-8e0a-8f0e04ab8450.png)

To jump to the right page, click: [mozilla-mobile/fenix](https://github.com/mozilla-mobile/fenix/)

**Comment by kbrosnan** [comment]
This has been updated to `Firefox for Android`
