### ISSUE TITLE
[Bug] Don't prompt to "Add to Homescreen" the first time you visit a PWA

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#12364]
# Steps to reproduce
Visit for the very first time (or clear storage to repro that) a PWA website (such as proxx.app)

### Expected behavior
I can view the site that I have never been to before.

### Actual behavior
A Fenix whole-screen popup appears, asking if I want to add this website (that I'm visiting for the first time) to my homescreen. (This should happen on a subsequent visit, not the first one)

### Acceptance criteria
* [ ] PWA prompt shows the 3rd time the user visits any PWA (not the first time)

### Device information
* Android device: ?
* Fenix version: Nightly 7/7

![Screenshot](https://user-images.githubusercontent.com/1082253/86858477-9616ba80-c075-11ea-8332-75117a213839.png)UNITO-UNDERSCORE!20200707-140902!

**Comment by ekager** [comment]
Eng needs to know which visit this should be shown on in order to make the changes.

**Comment by AmyYLee** [comment]
@apbitner for feedback

**Comment by apbitner** [comment]
This was expected behavior, but now that a new prompt is being added for 'Open in App' we're going to defer this prompt to display on the **third** visit to a PWA site. cc: @betsymi @vesta0

**Comment by ebalazs-sv** [comment]
@ekager Hi! I had tested this on Nightly 200720 (Build #22020611) GV 80.0a1 from 7/20 with Motorola Moto G6 (Android 8), Pixel 2 (Android 9) and 
- it is reproduce when accessing for the first time 9gag.com and digi24.ro, pinterest.com, audiomack.com, olx.ro, sportsmole.co.uk;
- it is reproduce when accessing for the second time app.starbucks.com;
- it is not reproducible on twitter.com and proxx.app, trivago.com, music.youtube.com, instagram.com, daleharvey.ghithub.io/testapp;

I will remove the qa:needed label for now.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 79.1.0-beta.1 (Build #22040602) GV 79 from 7/22 with Samsung Galaxy Tab S3 (Android 8).

**Comment by sblatz** [comment]
This may prove tricky to get perfect for each site. `onWebManifestChanged` can be called many times, and even our own `onLoadingStateChanged` gets called on completion an indeterminate number of times (1 or 2), a known issue: https://github.com/mozilla-mobile/android-components/issues/4795

**Comment by sblatz** [comment]
@ekager I tried a few solutions for this, but none seems to entirely fix the issue. I'm able to get it to sometimes work every SECOND time on Pinterest, but can't get it to work every three times because `onLoadingStateChanged` and `onWebManifestChanged` are called inconsistently.

**Comment by ekager** [comment]
Could we retest the suite of sites above @ebalazs-sv ?

**Comment by TejaswiKarasani** [comment]
@ekager I was about to file the same issue. I had seen the same behaviour of geckoNightlyDebug on Redmi MI A2 over Android 9 version!

**Comment by ebalazs-sv** [comment]
@ekager Hi! I had tested this on Nightly 200727 Build #22090608 GV 80.0a1 from 7/27 with Motorola Moto G6 (Android 8), Pixel 2 (Android 9) and here are the results:

with Motorola Moto G6 (Android 8):
- the prompt is displayed the **3rd or 4th** time: digi24.ro;
- the prompt is displayed the **4th** time: 9gag.com, pinterest.com, audiomack.com, twitter.com, proxx.app, trivago.com, instagram.com, daleharvey.github.io/testapp;
- the prompt is displayed the **4th or 5th** time: sportsmole.co.uk, app.starbucks.com;
- the prompt is displayed the **3rd** time: olx.ro, music.youtube.com;

with Pixel 2 (Android 9):
- the prompt is displayed the **2nd** time: digi24.ro;
- the prompt is displayed the **4th** time: 9gag.com, pinterest.com, twitter.com, proxx.app, daleharvey.github.io/testapp;
- the prompt is displayed the **3rd** time: audiomack.com, olx.ro, sportsmole.co.uk, app.starbucks.com, trivago.com, music.youtube.com, instagram.com;

As a conclusion, I noticed that the prompt is displayed after more than 3 times in the majority of cases. Also, on all the tested pages, except olx.ro, 9gag.com, proxx.app, music.youtube.com, the prompt is not displayed when accessing a page in a different tab. 

I will remove the qa:needed label for now.

**Comment by ekager** [comment]
Thanks for checking all those!! The main purpose of this change was that we don't bombard users with this dialog on the first time, so sounds like this might be okay for now. I'm going to unassign myself for now until we decide if it's important to show on exactly the third visit.

**Comment by ebalazs-sv** [comment]
@liuche Hi! I had tested this issue and the prompt is displayed the 2nd time, 3rd time, 4th or 5th time, as described in comment https://github.com/mozilla-mobile/fenix/issues/12364#issuecomment-664902654. 
Could you please answer at the previous comment question, if this prompt is important to be shown at the exactly 3rd visit? Thanks!
