### ISSUE TITLE
Make hiding the adress bar while scrolling optional

### ISSUE THREAD

**Issue by Eskander** [mozilla-mobile/fenix#12365]
### What is the user problem or growth opportunity you want to see solved?
The user should have the choice to autohide the adress bar or not while scrolling.
I suggest adding a checkbox in the Customize submenu.

### How do you know that this problem exists today? Why is this important?
Scrolling up and down several times on a web page might become distracting since the adress bar keeps hiding/showing without the user choosing to.

### Who will benefit from it?
Any user with a big enough screen that doesn't gain much vertical space when the adress bar autohides but prefers a consistant experience.

**Comment by kbrosnan** [comment]
Duplicate #10240
