### ISSUE TITLE
FNX-4891 ⁃ Create Bookmark Folders

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1236]
As a user with bookmarked websites, I want to create folders so that my bookmarks stay organized and are easier to retrieve. 

### Acceptance Criteria (Added by PM)
I can create a new folder for bookmarks
I can create a label for that folder
I can create that folder inside of other folders

**Comment by sv-ohorvath** [comment]
No issues found yet while verifying this feature. Closing.
