### ISSUE TITLE
Intermittent UI test failure - ContextMenusTest.verifyContextOpenImageNewTab

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#12367]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6949576656803130555/executions/bs.3650cedb891eeaed/testcases/2/test-cases

Failing on tom.prince's PR
https://github.com/mozilla-mobile/fenix/pull/12356#partial-pull-merging

**Comment by sv-ohorvath** [comment]
Old issue, haven't seen this happen again, closing for now.

**Comment by AndiAJ** [comment]
Closing in favor for #18421
