### ISSUE TITLE
FNX-4892 ⁃ Delete Bookmark Folders

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1237]
As a user with bookmarks in folders, I can delete a folder so that I can get rid of old bookmarks and keep my bookmarks organized. 

### Acceptance Criteria (Added by PM)
I can delete a bookmark folder
When I delete a bookmark folder,  this will delete all the bookmarks inside of the folder
When I delete a bookmark folder that contains other folders,  this will delete all contained folders and the bookmarks inside of the folders

**Comment by sv-ohorvath** [comment]
The blocking issue was fixed, can close this now.
