### ISSUE TITLE
[Design Bug] Undo Collection deletion

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#12375]
## Steps to reproduce
Delete a collection

### Expected behavior
No confirmation, get an undo prompt.

### Actual behavior
No confirmation.

### Device information
* Android device: Oneplus 5T
* Fenix version: 200707

**Comment by Djfe** [comment]
yes, please. It could look similar to the purple undo dialogue when you delete a tab.

**Comment by AndiAJ** [comment]
Dupe of #2783
