### ISSUE TITLE
[Feature Request] When long pressing the plus button in tab overview mode it should give option to open a tab in either private mode or normal mode.

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#12378]
### What is the user problem or growth opportunity you want to see solved?
It will be easier to open a new private tab without having to reach for the top.

### How do you know that this problem exists today? Why is this important?
It is another UX problem solving which will enhance user experience.

### Who will benefit from it?
User of private tabs.

**Comment by cadeyrn** [comment]
You can already switch between regular and private mode within the tabs tray and you can already do a long press on the tabs counter before the tabs tray is opened to open. I don't think that yet another way is really needed. You don't save any steps.

**Comment by Oymate** [comment]
@cadeyrn  Maybe then bring the switching to private mode button at the bottom-right in the tabs overview?

**Comment by ekager** [comment]
Closing because there's a workaround.
