### ISSUE TITLE
[Design improvement] Send to device: No Devices Connected: Connect an another device.

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#12371]
Triage: Low priority, easy first issue
Note: I might try to close this myself. :tada: Though if I don't within 2 months, it's all fine for anyone to take this without asking.

### What is the user problem or growth opportunity you want to see solved?
The 'Connect Another Device..' button is useless.
![Screenshot](https://user-images.githubusercontent.com/38327267/86856971-01c84a00-c0ad-11ea-8a04-b0077f0881e2.jpg)UNITO-UNDERSCORE!20200708-015151!

### Potential solutions:
![image](https://user-images.githubusercontent.com/38327267/86856919-e8270280-c0ac-11ea-9339-3e51b9f7d6a5.png)

**Comment by Oymate** [comment]
Or a prompt can be given to login inorder to share tabs.

**Comment by jtagcat** [comment]
> Or a prompt can be given to login in order to share tabs.

@Oymate wdym? How would you log on, say on a laptop with a magic prompt on the mobile?

Also, I might take this backlog for hacktoberfest.

**Comment by Oymate** [comment]
@jtagcat nvm, login is implemented.

**Comment by ekager** [comment]
Closing because this is a solution based issue. Please open a new issue that is user problem based.
