### ISSUE TITLE
FNX2-15201 ⁃ [UX] Choice to hide collections placeholder from homescreen

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12377]
## User Story

As a user who values choice, I want to have the option to hide the collections placeholder from my homescreen, so I can customize my homescreen the way that fits my needs. 

### Acceptance Criteria

- [ ] I can choose to hide the collections placeholder from the homescreen.
- [ ] Default setting is to show collections placeholder on the homescreen.
- [ ] If I create a collection, then I WILL see my collection the homescreen.
- [ ] "Save collection" will still show up on tabs tray.

https://share.goabstract.com/217e1b31-b1e1-41e9-93aa-73ee3a5fa361?mode=design&sha=a33c6759620ababdb8080b31568c55597940316e

**Comment by anmol257** [comment]
@vesta0 I agree with you.Even I would love this feature.

**Comment by RealGJ** [comment]
@vesta0 I agree for this feature suggestions too.

**Comment by Scripterr** [comment]
@anmol257 @RealGJ I think giving a thumbs up in original comment would be suffice, as your comments doesn't add any constructive feedback so they are unnecessary and will only clutter the issue.
Thanks.

**Comment by AmyYLee** [comment]
@topotropic for consideration

**Comment by SlowNicoFish** [comment]
I'd love to hide the "save to collections" button in the tab tray too!

**Comment by lukestateson** [comment]
Is it possible to add this at least in about:config?

**Comment by kbrosnan** [comment]
`about:config` is not an option. Gecko/Geckoview has no idea about collections.  `about:config` will never be used to control Fenix UI.

**Comment by vesta0** [comment]
Clarification: I think users should have the choice to hide the collections CTA/placeholder ONLY from the homescreen. Once a user creates a collection, then they should be able to see their saved collections on the homescreen.

**Comment by liuche** [comment]
@betsymi just want to check that you and Nicole have the strings for this toggle, since it's specific for removing the CTA/placeholder, but not the Collections feature.

**Comment by vesta0** [comment]
@topotropic does the user have the option of adding this back if they change their mind? Just curious.

**Comment by topotropic** [comment]
> @topotropic does the user have the option of adding this back if they change their mind? Just curious.

No but they might see it again (depending on implementation) when they create a collection and then delete it.

**Comment by ekager** [comment]
In the current implementation, a user will never see the placeholder again if they dismiss it. They will see it again if they add a collection and then delete the collection (without dismissing the placeholder). Do we want it to dismiss once they add a collection as well?

**Comment by vesta0** [comment]
I think the current implementation (seeing the placeholder again if they add a collection then delete it) is great. Thanks @ekager

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200827 07:01 (Build #2015760377) GV 81.0a1 from 8/27 with the devices:
- Google Pixel 2 (Android 9);
- Samsung Galaxy Tab S3 (Android 8);
- Nexus 5 (Android 6.0.1).

When the Collection placeholder **is dismissed** from the homescreen by tapping the "X" button:
- the added collections will be displayed in the Collection homescreen section;
- the Collection placeholder will **not** be displayed again after deleting all the collections;

When the Collection placeholder **is not dismissed** from the homescreen:
- the added collections will be displayed in the Collection homescreen section;
- the Collection placeholder will be displayed again after deleting all the collections.

**Comment by jawz101** [comment]
> Clarification: I think users should have the choice to hide the collections CTA/placeholder ONLY from the homescreen. Once a user creates a collection, then they should be able to see their saved collections on the homescreen.
> 
> We believe that collections can bring value to a user's online experience and we should always have the save collection flow on the tabs tray, but customization is also very important to our users and we should allow them to customize their homescreen.

If its hidden then how would it be accessible?  So the user just ends up filling a collection. unknowingly?

**Comment by yoasif** [comment]
@jawz101 This just controls the collections tip / placeholder UI. The container features are still available in the UI from other places.

**Comment by jawz101** [comment]
But you cannot restore the collections placeholder once it is removed.  That's stupid
