### ISSUE TITLE
[Bug] My scroll is not smooth

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#12373]
## Steps to reproduce
I open the m.youtube to search for something and when scrolling the scroll is not smooth.
Animations are  bad and the page is like flassing.

Same on https://www.tiktok.com/foryou?lang=en when sliding the video. Not smooth at all.

### Expected behavior
To be smooth.

* Android device: P10 Lite WAS-LX1 8.0.0
* Fenix version: 79.0.0-beta.5 (Build #2015749827)

**Comment by atulsnjena** [comment]
I think the ability to turn on or off smooth scrolling should be presented to the users. Right now I don't find it anywhere.
