### ISSUE TITLE
[Bug]Improperly displayed "Firefox has moved" banner while using German

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12384]
## Prerequisites
Have a fresh install or a clean profile

## Steps to reproduce
1. Open Fenix
1. Tap the ⋮ Main menu and change the language to Deutsch (German)
1. Exit to the Home screen

### Expected behavior
Properly displayed and aligned text in the banner.

### Actual behavior
Improperly displayed and alignment issues

### Device information
* Android device: all
* Fenix version: Nightly Build 200708 from 7/8

### Notes
❗ Applicable if the Android Language and Input method is set to German

► Screenshot
![rsz](https://user-images.githubusercontent.com/51314259/86911458-054ae800-c124-11ea-8660-95a735544783.png)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200708-104131!UNITO-UNDERSCORE!1!

**Comment by cadeyrn** [comment]
Not exactly the same because it's a different message but related: #12211.
