### ISSUE TITLE
[Telemetry] Telemetry server

### ISSUE THREAD

**Issue by AminAshtiani** [mozilla-mobile/fenix#12381]
### What is the user problem or growth opportunity you want to see solved?
I cloned and build a version of Fenix but I need to change the telemetry server address in order to watch the performance and collect data to improve it. 
I changed `toolkit.telemetry.server` but I didn't work.

**Comment by kbrosnan** [comment]
This is not a Fenix bug. You should contact the Glean project https://github.com/mozilla/glean/
