### ISSUE TITLE
[Bug] Often, when closing a tab the next tab does not appear, shows old tab's page

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#12382]
- [ ] GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1660546

## Steps to reproduce
1. Have at least two tabs open (I currently have 40).
1. Close the active tab
1. View the new active tab.

### Expected behavior
When a tab is closed the next active tab's page is displayed correctly on the screen; the old tab's content is no longer visible.

### Actual behavior
The new active tab's content may or may not appear. In some cases the previously active tab's content (now closed) is still visible. To view the current tab's correct content the page must be reloaded.

Note that this behaviour has been present for the past week I think.

Update : after changing to org.Mozilla.fenix today this happens with every tab. 

### Device information
* Android device: Nokia 8 on Android 9
* Fenix version: 
Nightly 200706 06:01 (Build #2015750387)
AC: 49.0.20200702190156, bafa9299b
GV: 80.0a1-20200702094606
AS: 61.0.7

**Comment by madb1lly** [comment]
Selecting address bar then back clears the ghost of the tab.

**Comment by liuche** [comment]
@csadilek talked to vesta and she thinks this is a critical issue, is that something we can pull into the next AC sprint? I'm not really clear if sebastian is working on it already or something else.

**Comment by boek** [comment]
This may also be related to #5478. We should be able to test this once we update to the latest GV

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build 9/10 with Google Pixel 4 XL (Android 11).
Now when closing the active tab, the tab that was under is correctly displayed.
Note that there is a regression and I added https://github.com/mozilla-mobile/fenix/issues/14936.
