### ISSUE TITLE
FNX-4893 ⁃ Edit Bookmark Folders

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1238]
As a user with bookmarks in folders, I can edit the folder label so that I can keep my bookmarks organized.

### Acceptance Criteria (Added by PM)
I can change the label on a bookmark folder

**Comment by sv-ohorvath** [comment]
This has been tested and verified by QA. Removing the QA needed label but leaving the issue open until all blocking/related issues are fixed.

**Comment by kbrosnan** [comment]
All blocking issues are closed. Closing this issue.
