### ISSUE TITLE
[Bug]Deletion confirmation snackbar missing when closing all PB Open Tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12383]
## Prerequisites
Have a couple of Normal and Private tabs open.

## Steps to reproduce
1. Open one of the Private Tabs
1. Tap the tab counter
1. Tap the ⋮ "More options button"
1. Select "Close all tabs"

### Expected behavior
The Deletion confirmation snackbar is properly displayed, I can undo the deletion

### Actual behavior
The Deletion confirmation snackbar is missing, can't undo the deletion

### Device information
* Android device: all
* Fenix version: Nightly Build 200708 from 7/8

### Notes
►Video
![20200708-130753](https://user-images.githubusercontent.com/51314259/86907138-42f84280-c11d-11ea-80f1-97762be4050e.gif)

**Comment by ekager** [comment]
Similar to #11851

**Comment by Diana-Rus** [comment]
Reproducible on Firefox Preview Beta 81.1.0 with Google Pixel 3XL (Android 9)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200928`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

Filled #15490 for an inconsistency I've encountered.
