### ISSUE TITLE
Option to disable suggestions

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#12385]
### What is the user problem or growth opportunity you want to see solved?
As someone who often delete firefox data / change version to be sure the bug I wanna report is not my config but firefox, I'm tired of being forced to see: firefox protects your privacy with the purple shield icon, tired to be forced to install the PWA or add to the top sites if I don't want the blue icon to stay there forever… 

Of course it's important for newcomers, so that they can discover the browser functionalities, that's why I'd like it to be disabled by default.

### How do you know that this problem exists today? Why is this important?
It will allow people testing firefox, often resetting data not to waste time with suggestions.

### Who will benefit from it?
testers, power users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3228)

**Comment by terr72** [comment]
I'd like to second was B0pol said.
Those notifications are also a distraction for regular users: I don't want to be notified by a blue dot everytime I visit a site that offers a PWA.
It also confuses elder people, as I just had to learn after getting the second phone call from elder relatives asking me what this dot and the install thingie actually means.
So please, offer an option to disable this in the settings.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807119

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
