### ISSUE TITLE
FNX-4894 ⁃ Move Bookmark Folders

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1239]
As a user with bookmark folders, I can move my folders so that I can organize them in a way that makes sense to me. 

### Acceptance Criteria (Added by PM)
I can select a bookmark folder and move it into another folder
I can select a bookmark folder that is in another folder and move it into a different folder
I can select a bookmark folder that is in another folder and make it a top-level folder

**Comment by sv-ohorvath** [comment]
This has been tested and verified by QA. Removing the QA needed label but leaving the issue open until all blocking/related issues are fixed.

**Comment by sv-ohorvath** [comment]
All bocking issues fixed, closing.
