### ISSUE TITLE
FNX2-15215 ⁃ Make "Forget Me Not" available as an add-on within Fenix

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#12393]
### Why/User Benefit/User Problem
Users want to control their privacy online from first parties in addition to third parties (like ETP provides). Forget Me Not allows people to make these choices on a case by case basis. Forget Me Not is already a recommended extension for Firefox. 

### What/Requirements
Make https://addons.mozilla.org/en-US/firefox/addon/forget_me_not/ available as an add-on in nightly. 

### Acceptance Criteria (how do I know when I’m done?)
If I go to add-ons, I can install this add-on.

**Comment by LittleAngelwings** [comment]
I'm in favor with @yoasif

**Comment by NotWoods** [comment]
We would like to expand our support to other add-ons but we are not keeping open requests for specific ones. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.
