### ISSUE TITLE
FNX-36 ⁃ Add a Startup Option to Specify the Client ID

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#124]
### Why/User Benefit/User Problem
Automated and performance testing may skew our telemetry numbers, confusing us. We don't like to be confused!

### What / Requirements
Add a Startup Option to Specify the Client ID . The Client ID would be used as the id for our telemetry calls.

### Acceptance Criteria (how do I know when I’m done?)
I can start up Focus with a specified client id and that is what is reported in redash.

cc @mmccorks

**Comment by mcomella** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1514336 against glean.

**Comment by liuche** [comment]
We have so few QA release tests (manual) compared to our userbase, and this requires Glean work, so we're going to close this for now because it's not important. Can re-open if we start doing more automated, release tests.
