### ISSUE TITLE
[UX Feedback] Increase spacing inbetween the Collection header and the first saved website and also in the individual websites saved in the Collection

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12409]
This adds further suggestions to the issue #12408.

Right now it's really very easy to accidentally click on the "X" button to delete a website stored in a collection. 

The spacing between the header (which contains  the "share" and the "3-dot" menu) the first website that is stored in the collection is very less, it is easy to click on the "X" button accidentally and the saved website gets deleted in moments. This has happened to me while I was trying to click the 3-dot menu of the Collection to rename it; it's really very easy to click the "X" button while clicking the 3-dot menu as they are both vertically very near. And to add to it also increase the spacing between the individual websites that are stored in the Collection so the user doesn't accidently click on "X" button to delete the website that they did not intend to delete. 

I know it'll increase the Collection size but I think it's worth as the saved Collection and the websites in them are very important and I cannot afford to lose them accidentally.

**Comment by ShatteredPixel** [comment]
I'm the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by ekager** [comment]
Closing as original reporter closed their account
