### ISSUE TITLE
Determine how long GeckoView main thread continuations take during startup

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#12402]
Break-out of https://github.com/mozilla-mobile/fenix/issues/8060 for pre-work

GeckoView posts some operations on the main thread which occur before visual completeness and not as part of the Application/Activity lifecycle methods. We should determine how long these operations take (either with a non-debuggable startup profile or instrumenting the methods on a low end device) to inform how we should prioritize this work.

**Comment by mcomella** [comment]
@MarcLeclair Should this be Done? I don't see an analysis and the issue is not closed.

**Comment by MarcLeclair** [comment]
Not much was found, except that on some profiles, I saw the ContentProvider taking a good chunk of time (~40ms). but I'm not sure if that info is valuable
