### ISSUE TITLE
[UX Feedback] Add an undo button after deleting a website in a Collection

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12408]
This issue adds extra suggestions to the issue #12375 is asking. 

Collections are precious, they are saved because they are important. Right now there are too many ways that could easily delete a website save in the Collections; swipe to delete, click "x" icon at the right side to delete it, or even accidently clicking on the "x" icon to delete it while clicking on the 3-dot menu of the Collection so when there're these many ways to accidentally delete a website saved in the collections it's needed that an undo button is needed to un-delete an accidentally deleted website in the Collection since they are important it will make sure that the user actually intends to delete the website not accidentally clicked the "x" icon or swiped on it.

I know adding an "undo website deletion" prompt may annoy some users but to make the website not get accidentally get deleted it's needed as the saved websites are important.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3262)

**Comment by ShatteredPixel** [comment]
I'm the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by AmyYLee** [comment]
@topotropic for feedback

**Comment by ShatteredPixel** [comment]
Please have a look at the #12409 as well.

**Comment by AmyYLee** [comment]
@topotropic - Is there an update on this? If this requires more investigation, please update the flag to UX- investigation and remove UX-feedback flag. Thanks!

**Comment by topotropic** [comment]
thanks for the feedback, we can show a "UNDO" snackbar when someone removes a collection entry.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812750

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
