### ISSUE TITLE
FNX2-13709 ⁃ GV frustratingly pauses for a moment between pages on page load under low bandwidth

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#1241]
## Steps to reproduce
* Be in low bandwidth network conditions
* Load a page and continue trying to interact with the current page (e.g. scrolling)

### Expected behavior
The user can keep interacting with content on the current page until the new page draws on screen.

### Actual behavior
At some point during the page load, you are unable to scroll the current page beyond the currently visible screen length, blocking the user from doing anything useful (if they've already consumed the page's current content). A bit later (maybe 5-10s in my experience), the next page begins to load as expected.

This pause when switching from the current page to the next page, while reasonable as a product team (e.g. the user chose to go somewhere else, they don't care about the current page so why do we need to support it?), feels really bad as a user: it feels like the app is wasting my time and it's tedious.

Note: I was only able to reproduce this briefly (in the elevator) so I wasn't able to reproduce to guarantee all page loads were like this.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1913 (I think)

I also wonder what other tedious behaviors we might experience during low bandwidth conditions: do we test this?

- - -
### Acceptance criteria
* Is this still an issue?

**Comment by bifleming** [comment]
@cpeterso

**Comment by cpeterso** [comment]
The QF performance team should profile this scenario to see where Fenix or GV is spending all its time.

**Comment by jeanygong** [comment]
Chris, as part of the QF triage process the reporter who filed the bug should provide the profile as well.  This would better help the QF team triage the issue better.  Can we use the same process here in github for performance issues?

**Comment by cpeterso** [comment]
> Chris, as part of the QF triage process the reporter who filed the bug should provide the profile as well. This would better help the QF team triage the issue better. Can we use the same process here in github for performance issues?

Sure.

@mcomella - Can you please record a profile of the page load pause using the Gecko Profiler or an Android profiler?

**Comment by mcomella** [comment]
> @mcomella - Can you please record a profile of the page load pause using the Gecko Profiler or an Android profiler?

Two thoughts:
- This is a user experience issue, not strictly a performance issue: is a profile still useful?
- I can't reproduce this reliably (I was in an elevator)

@cpeterso Given these two items, do you think it's best for me to produce a profile? I feel like the optimal use of everyone's time would be for someone on the GV team to reproduce, identify the user experience issues, and fix them, no profile really required.

**Comment by cpeterso** [comment]
> Given these two items, do you think it's best for me to produce a profile? I feel like the optimal use of everyone's time would be for someone on the GV team to reproduce, identify the user experience issues, and fix them, no profile really required.

I think a Gecko profile would be helpful if the problem was reproducible. The Gecko profile includes details about Gecko's rendering and networking, so we can what code is busy or if we're waiting for some data.

Without reliable STR, we would just be profiling regular page loads (which we do already, though I don't know if we test low-bandwidth network connections).

@ecsmyth - How fast is the network we use for our Android page load tests? Do we do any simulation of slow 2G or 3G networks? Do we have any telemetry or market data about typical mobile network speeds? We might find different performance bottlenecks.

**Comment by mcomella** [comment]
@cpeterso Do you have steps to create a Gecko profile?

**Comment by cpeterso** [comment]
> Do you have steps to create a Gecko profile?

Here are instructions for Android: https://profiler.firefox.com/docs/#/./guide-remote-profiling

**Comment by tarekziade** [comment]
@mcomella  In case you are able to install and run an android emulator, you have options there to simulate poor network conditions. It's -netdelay and -netspeed with the command line or in the UI in celullar->signal strength and cellular->network type.

**Comment by mcomella** [comment]
Triage:
1. is this still an issue?
1. Is there a change in behavior needed for how we render pages? What if we changed only mobile and not desktop? We currently display a white flash between pages so it's possible my connection stopped between screens. Based on user research

**Comment by mcomella** [comment]
>     2. Is there a change in behavior needed for how we render pages?

I filed https://github.com/mozilla-mobile/fenix/issues/7215 to address this part of the issue.

>     1. is this still an issue?

Let's address this in this bug.

Note: we haven't received any other reports of this so perhaps it's no longer a problem.

**Comment by mcomella** [comment]
We can reopen if we see this again. Otherwise tracking the high level issue on JIRA: https://jira.mozilla.com/browse/FXP-1253
