### ISSUE TITLE
[Bug] Zooming in on bugzilla pages changes minimum zoom

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#12418]
## Steps to reproduce
Go to any bugzilla bug page, e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1647177
Pinch zoom in slightly
Now try to zoom back out to fit the entire content the way it was when the page loaded

### Expected behavior
Able to zoom out to restore original zoom

### Actual behavior
Unable to do so. Minimum zoom is at a level that now requires horizontal scrolling to view.

### Device information
* Android device: Sony Xperia XZ1C
* Fenix version: 
Nightly 200709 06:10 (Build #21910619)
AC: 50.0.20200708130551, 8ce4bdb18
GV: 80.0a1-20200707094747
AS: 61.0.7

**Comment by Diana-Rus** [comment]
Hi, an issue is already created for this problem, please follow here #9813.

**Comment by staktrace** [comment]
Thanks. For future reference, that one was duped to https://github.com/mozilla-mobile/fenix/issues/10479 so that's the one to track.

**Comment by hiikezoe** [comment]
Thank you kats for ccing me!  I wasn't aware of the open issue at all.
