### ISSUE TITLE
FNX2-15230 ⁃ [Feature Request] Add a developer mode

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#12413]
### What is the user problem or growth opportunity you want to see solved?
This will solve the problem of having developer features and user features from colliding to make the UI more simple and less confusing.

### How do you know that this problem exists today? Why is this important?
There are currently developer options in user settings which they should be opt-in instead.

### Who will benefit from it?
Developers and users.

Sidenote: As an example view page source could be added as a developer option.

**Comment by kbrosnan** [comment]
We are not going to hide the USB debugging items. They are critical to getting web developers to support Firefox for Android.

**Comment by Oymate** [comment]
@kbrosnan So, the page source thing?
