### ISSUE TITLE
FNX2-15236 ⁃ [Bug] Bottom of bugzilla page is hidden by dynamic toolbar

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#12419]
## Steps to reproduce
Go to a page like https://bugzilla.mozilla.org/show_bug.cgi?id=1647177. Scroll down to the end

### Expected behavior
Bottommost text "Add the named tag" stuff is visible. (note: the bottommost text may be different if you're not logged in)

### Actual behavior
It's hidden behind the dynamic toolbar. If you zoom in you can see part of it because it gets bigger but there's still a part that's hidden and cannot be made visible

### Device information
* Android device: Sony Xperia XZ1C
* Fenix version: Nightly 200709 06:10 (Build #21910619)
AC: 50.0.20200708130551, 8ce4bdb18
GV: 80.0a1-20200707094747
AS: 61.0.7

**Comment by Amejia481** [comment]
cc @Mugurell

**Comment by Mugurell** [comment]
Something strange is happening on both Fenix and Chrome

| Fenix  | Chrome |
| ------------- | ------------- |
| ![SomethingIsHiddenOnFenix](https://user-images.githubusercontent.com/11428869/87121765-380ff000-c28c-11ea-8f61-1e11d1cd3e4f.gif) |![ChromeBandingBugzilla](https://user-images.githubusercontent.com/11428869/87121896-7d342200-c28c-11ea-82cc-38f75104335a.gif)l  |

 so I'd see it as a webcompat issue.

But there are no issues on GeckoView Example.

Hoping hiro knows what's he best course of action for this.

**Comment by staktrace** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1649865 seems to be the same problem as what I reported here.

**Comment by theres-waldo** [comment]
> Something strange is happening on both Fenix and Chrome after zooming the pages a little.

Yeah, this has been reported before as https://bugzilla.mozilla.org/show_bug.cgi?id=1521330. It was observed there too that Chrome shares the same behaviour, but I kept the bug open as I feel like we don't have a good understanding of why this behaviour occurs.

**Comment by staktrace** [comment]
The issue as filed is the same as #10479, per https://bugzilla.mozilla.org/show_bug.cgi?id=1649865#c7 so I'm closing this.

**Comment by Mugurell** [comment]
Closing as per staktrace's comment.

**Comment by Mugurell** [comment]
Closing this as per https://github.com/mozilla-mobile/fenix/issues/12419#issuecomment-671753653
