### ISSUE TITLE
FNX2-15232 ⁃ Can we create a way for Fenix to get served better Google results?

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#12415]
### What is the user problem or growth opportunity you want to see solved?
As we all know, in order to monopolize the browser market and suppress competitors, **Google** treats browsers differently. 
In _**Google Search**_, if a browser uses **Webkit** engine, The web page will show the best results.
![Chrome](https://user-images.githubusercontent.com/62339707/87009184-68f21580-c1f7-11ea-8f96-ad00b5686397.jpg)
However, due to the use of the **Gecko** (*GeckoView*) engine in the **Firefox Mobile** (both **Fennec** and **Fenix**), _**Google Search**_ will show a poor simplified version of web page.
It looks terrible.
![Fenix](https://user-images.githubusercontent.com/62339707/87009243-79a28b80-c1f7-11ea-9af8-21c10394216b.jpg)

### How do you know that this problem exists today? Why is this important?
I usually use **Firefox Browser** for _**Google Search**_, I will never use the **Google APP** neither now nor in the future.
I believe most people are the same as me that only using a web browser to do most of the daily Internet activities.

### Who will benefit from it?
All **Firefox Mobile** users who use _**Google search**_.

Actually we can manually modify the _**User-Agent**_ of the **Fenix** to deceive **Google** to make it believe that I am using a **Webkit** browser. But there is no way to modify it now in settings.

Perhaps, we can also use a **Firefox Add-on** to achieve it. This is the second way.

Hope my words come true.

Thanks to all developers.

**Comment by sheikh-azharuddin** [comment]
You need to change the user agent to chrome to fool Google. 2 days ago someone requested for an add-on
For now you have to manage with about:config preferences.

*Outcome*

![Screenshot_20200709-141007](https://user-images.githubusercontent.com/58127841/87017674-cec2ab00-c1bf-11ea-8498-5cb736f2ebc6.jpg)

**Comment by lomomcat** [comment]
@sheikh-azharuddin 
So can you teach me which option to modify in **about:config**?
Thanks.

**Comment by sheikh-azharuddin** [comment]
Mobile browser user agents are mostly device specific
So first open chrome and find your user agent.
Copy the value
Open Firefox > about:config
Create a new **string**
**general.useragent.override**
In the value section paste the user agent.
Quit the browser, force stop and then open and check.

Example user agent :
Mozilla/5.0 (Linux; Android 10; ASUS_I001DE) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4194.0 Mobile Safari/537.36

![Screenshot_20200709-141806](https://user-images.githubusercontent.com/58127841/87018737-30374980-c1c1-11ea-96b1-fe8c5ca17261.jpg)

**Comment by sheikh-azharuddin** [comment]
Pro tip
If you use the mobile agent from desktop version of chrome you will get all results by default in desktop mode

**Comment by cadeyrn** [comment]
It's a bad idea to override the user agent because you have to do it again and again for every new major release otherwise the version numer won't match and this will cause other compatibility problems. It also causes issues on other websites since the about:config option applies for every website in the world. Also it won't be possible at all in stable release because about:config is only enabled in pre release builds of Fenix. While this can be a workaround in the meantime it's not a solution of the problem.

**Comment by sheikh-azharuddin** [comment]
No sir... Thats why i suggested use canary build user agent... For stable to reach that will take months... So no issue of outdated.
The user agent add on present in Firefox store are providing much older user agent still sites are working...so you are good atleast for 6 months if using canary user agent

**Comment by lomomcat** [comment]
@sheikh-azharuddin 

I think Add-ons are better. The add-on can make use of specific UA for Google search. It is more automated. As you said, the UA modification was successful. But it is troublesome to restore the Firefox UA, isn't it? You need to view **about:config** page, find the option and delete it. And next time you want to use Google again…

**Comment by sheikh-azharuddin** [comment]
Not that much difficult you can click reset button on the preference item it will delete it... But why switch ... Chrome UA results are better.. Make it permanent

**Comment by lomomcat** [comment]
@sheikh-azharuddin 

So the best way to solve it is to make Google LLC change the page format of Google for Fenix.

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin
> 
> So the best way to solve it is to make Google LLC change the page format of Google for Fenix.

Bro that wil take years or probably never... The issue is there even in desktop version and they have not solved it yet...

**Comment by hwinnemoe** [comment]
> And and and unless Firefox has a built in solution we are happy to change the user agent... Kind of best of both browsers privacy+ better search

If you change your browser agent and do not update it like everyone else, e.g. every time a new canary version is released, you make yourself _more unique_ to websites, thus creating less privacy. Especially if you do this globally via about:config and not in specific circumstances.

**Comment by sheikh-azharuddin** [comment]
Lol in that case isn't the Firefox ETP supposed to protect?😅🤣
. Anyway we have installed for better search result.. For privacy we have ublock, privacy possum and default ETP.

**Comment by cadeyrn** [comment]
> Lol in that case isn't the Firefox ETP supposed to protect?

Nope. Enhanced Tracking Protection blocks tracking scripts, it's not about reducung the fingerprint.

**Comment by ekager** [comment]
Also see https://github.com/mozilla-mobile/fenix/issues/5350 and https://github.com/mozilla-mobile/fenix/issues/12341

**Comment by liuche** [comment]
Going to dupe this to #5350

**Comment by Poopooracoocoo** [comment]
@liuche that issue is locked. I can't even mention Google Search Fixer.

**Comment by nesbocaj** [comment]
if #5350 was not locked I would add this comment there:

Another solution is to use the Firefox for iOS User-Agent (like this [add-on](https://addons.mozilla.org/en-US/firefox/addon/firefox-ios-ua-on-google/) does) as that too gets served the Webkit version of Google Search.

I would argue this is the better option compared to using the Chrome useragent as this way the Chrome usage numbers are not artificially inflated.
