### ISSUE TITLE
Allow the websites to be moved to a different Collection than the one it is stored in

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12411]
This adds to the suggestions the issue #12410 is asking about.

right now it is not possible to move a website that is stored in a collection to a different collection the one it is stored in (well, actually it could be done but the website needs to be opened and has to be placed in a collection manually). This will make it easier to move some websites that are not intended to be in a specified collection and be allowed to move to a collection it belongs to.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3266)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812748

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
