### ISSUE TITLE
FNX2-15233 ⁃ [Bug] Long press not selecting text

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#12416]
## Steps to reproduce
Open any webpage with text. 
Press on the text for a few seconds. 

### Expected behavior
The text is selected. 

### Actual behavior
Nothing happens. 

### Device information
* Android device: ? Huawei Mate 20 X, Android 10
* Fenix version: ? Nightly

**Comment by lomomcat** [comment]
Nope.
![Screenshot_2020-07-09-16-36-44-361_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/62339707/87017339-6ea12880-c202-11ea-93c7-80e2dd9dff9c.jpg)
Version: Nightly 200709 06:10

**Comment by robsmith11** [comment]
Hmm.. apparently it's intermittent.  At the moment, I can't reproduce either.  But it was happening earlier today with multiple tabs.

**Comment by sheikh-azharuddin** [comment]
> Hmm.. apparently it's intermittent. At the moment, I can't reproduce either. But it was happening earlier today with multiple tabs.

Its not intermittent I think... It does not work when you long press on blank space between the words.. Not your or device fault seems some issue with the logic in fenix... It works fine in other browsers.

**Comment by robsmith11** [comment]
I haven't seen this issue recently so closing for now.

@sheikh-azharuddin your issue is different I think.
