### ISSUE TITLE
Allow the websites that are stored in Collection to be opened in Private Browsing Mode

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12412]
This adds to the issue #12410 is asking about. 

Right now the websites that are stored in a collection cannot be opened in Private Browsing Mode but instead have to be opened a normal browsing mode and then websites link has to be copied and placed in a private browsing mode to be able to browse the specified site in a Private Browsing Mode. This defeats the purpose of a browser featuring a Private Browsing Mode as some websites need to be opened in a Private Browsing Mode no matter where they are saved in a browser; bookmarks otherwise.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3267)

**Comment by ShatteredPixel** [comment]
I'm the reporter of this issue. Please let me know if I can provide you any more information.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812747

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
