### ISSUE TITLE
Add a 3-dot menu to the websites stored in a Collection

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12410]
Add a 3-dot menu to the websites stored in a Collection which can contain options to **copy the website's address, open in the Private Browsing Mode (right now there is no option to open the website saved in a collection in a private browsing mode), share the website, move the website stored in one Collection to another Collection and delete a website stored in the Collection, etc.** And remove the "X" icon that deletes the website in the Collection . This adds some customizability to the websites stored in the Collection.

The spacing between the collection header and the spacing between the individual websites should still be increased as the issue #12409 Is asking even if the the "X" icon is removed and replaced with 3-dot menu. It is still necessary as to make it easier to select a saved website and perform actions on it and not accidentally select other websites instead while doing so.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3265)

**Comment by ShatteredPixel** [comment]
I'm the reporter of this issue. Please let me know if I can provide you any more information.

Thank you! :)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812749

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
