### ISSUE TITLE
FNX2-15240 ⁃ [BUG] App doesn't resume the way I minimised

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#12425]
How to reproduce: 

1. Open a tab on any website
1. Push app to background by any means, say just press home button
1. Go to your recent app menu and resume Firefox Nightly
1. You see that app resumes on new tab page like a fresh session. 

Expected Behaviour: It should remember the tab when minimised app.

Fenix: Nightly 200709 06:10 (Build #21910619)
AC: 50.0.20200708130551, 8ce4bdb18
GV: 80.0a1-20200707094747
AS: 61.0.7

Device: Xiaomi Redmi Note 4, Android 7.0

**Comment by RealGJ** [comment]
Unable to reproduce in :

Nightly 200728 06:22 (Build #22100630)
AC: 52.0.20200727130115, 14848f934
GV: 80.0a1-20200724093206
AS: 61.0.10

Considering as Solved!! Closing!! Thank You!❤️

**Comment by RealGJ** [comment]
@pocmo

**Comment by RealGJ** [comment]
@pocmo this issue isn't there on nightly but is there on latest stable fenix.

79.0.4 (Build #2015757667)
AC: 48.0.14, c6965e12d
GV: 79.0-20200720193547
AS: 61.0.10

**Comment by yoasif** [comment]
@RealGJ Do you see this in 79.0.5?
