### ISSUE TITLE
FNX-4896 ⁃ [Telemetry] Error Pages

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1242]
#### Description & Product Manager User Story
* As a product owner, I want to know when people encounter errors on websites so we know when they 

#### What questions will you answer with this data?
* When and what errors users experience within the app
* What will users do after they've encountered an error (Amplitude funnel) and how will they get out of it

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
* Understand the health of the web and how often users encounter website errors

#### What probes (suggested, if applicable)
* send an event ping on each specific error, see [here](https://github.com/mozilla-mobile/fenix/issues/921#issue-418789690) for kind of errors

### Dependencies (Added by PM and Eng)
* Glean SDK

### Acceptance Criteria (Added by PM)
* Event pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by sblatz** [comment]
@vesta0 is there any other data we want to track in this? I'm understanding this ticket to mean that we're just going to send a ping with the error type (e.g. ERROR_NET_TIMEOUT) and no other information.

**Comment by vesta0** [comment]
@sblatz I think that's about it (when and what error type). We also want to track what users do right after they've encountered the error but I think that depends on other probes we have put in place, would you agree?

**Comment by AndiJoltan** [comment]
Hi all,

This issue is still replicating, I've tested this using the latest Fenix version (05.06.2019) on a Google Pixel 3 XL.

Please find attached and review the logcat [Error.txt](https://github.com/mozilla-mobile/fenix/files/3257547/Error.txt) 

## Please note that I've used the following web sites:
Ping ID **19c9a358-6687-4c2c-b640-e86f794756e5**  Lines 477-527 
Visited page: http://browserscope.org/security/test 
Error 522 "Connection timed out" 

Ping ID **ccaab7ff-50b3-4e02-b7ec-174c1314ad96** Lines 963-1006 
Visited page: https://sjeng.org/mozilla.geo.html 
Error 404 "Not Found"  

Ping ID **3a753b0b-506e-426d-a4d9-b64608d34df1** Lines 1437-1481 
Visite page: http://archive.mozilla.org/pub/mobile/nightly/latest-mozilla-central-android-api-16/
Error 404 "Not Found" 

Ping ID **35001890-086a-490b-94a4-3c25dc390961** Lines 1930 - 1974 
Visited page: http://testsafebrowsing.appspot.com/s/phishing.html
Deceptive site 

Based on this comment, I will remove the QA Needed label.

**Comment by sblatz** [comment]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/4400286/58975604-349d6180-877a-11e9-82c7-87123e9feb9b.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/4400286/58975633-47b03180-877a-11e9-9254-e8d68bc5b459.png">

The first three errors are not pages we display error pages for, so it makes sense the telemetry is not sending for them. Notice that the difference in the above screenshots and the one below which is actually one of our error pages

<img width="250" alt="image" src="https://user-images.githubusercontent.com/4400286/58975705-7a5a2a00-877a-11e9-8e8d-b3ec43856d73.png">

@AndiJoltan are you able to test with something like:
1. `https://www.fakeurlwebsite.org` to trigger an "address not found"
2. `http://testsafebrowsing.appspot.com/s/malware.html` to trigger "Harmful site issue"

And others that trigger our error pages (you'll see a button to "go back" or "try again" at the bottom).

**Comment by AndiJoltan** [comment]
Hi, still **no luck** while testing the **Latest Fenix** version (2019-06-06T06:12:22.271Z) on a **Google Pixel 3** (**Android 9**).

Please find attached and review the logcat for this testing session [ErrorPixel.txt](https://github.com/mozilla-mobile/fenix/files/3260744/ErrorPixel.txt)

## I've used the following websites to trigger the errors:

**Server IP address could not be found DNS_PROBE_FINISHED_NXDOMAIN:**

`https://www.fakeurlwebsite.org/` 
`http://mediarepoes.net/  `
`http://www.odiadon.com/ `

**Refused to connect ERR_CONNECTION_REFUSED"**
`http://tessline.com/  `

**Harmfull web sites:**
`https://testsafebrowsing.appspot.com/s/phishing.html `
`https://testsafebrowsing.appspot.com/s/malware.html `
`https://testsafebrowsing.appspot.com/s/malware_in_iframe.html `
`https://expired.badssl.com `

**Comment by sblatz** [comment]
Should be fixed by #3224.

**Comment by AndiJoltan** [comment]
Hi, the error_page still **doesn't work**.

Please find attached and review the **logcat** [Errortxt.txt](https://github.com/mozilla-mobile/fenix/files/3276365/Errortxt.txt) and the log from the **dashboard** (https://debug-ping-preview.firebaseapp.com/pings/2311bde3-47fc-4272-9a8b-b1cce4e7eaf5/aj-TezzErr-00)

#### I've used the following websites to trigger the errors:
https://www.fakeurlwebsite.org/
http://mediarepoes.net/
http://www.odiadon.com/
http://tessline.com/
https://testsafebrowsing.appspot.com/s/phishing.html
https://testsafebrowsing.appspot.com/s/unwanted.html
https://expired.badssl.com

One question though, @sblatz shouldn't it be correlated with "searched_page" event ping? After accessing a page only afterwards the error should pop up ?

Based on this comment I'll remove the QA needed label.

**Comment by sblatz** [comment]
Could @boek weigh in here? I'm really not sure what else would be the issue here. I'm able to get the [telemetry line triggered](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt#L53) in my debugging. I wonder if the `AppRequestInterceptor` is for some reason not compatible with Telemetry?

**Comment by AndiJoltan** [comment]
Hi, **verified as fixed** on the latest Fenix version (2019-06-14) using a Google Pixel 3XL(Android 9)

## I've used the following websites to trigger the errors:

`https://www.fakeurlwebsite.org/` 
`http://mediarepoes.net/  `
`http://www.odiadon.com/ `
`http://tessline.com/  `
`https://testsafebrowsing.appspot.com/s/phishing.html `
`https://testsafebrowsing.appspot.com/s/malware.html `
`https://testsafebrowsing.appspot.com/s/unwanted.html `
`https://expired.badssl.com `

Please find attached the **logcat** [Error.txt](https://github.com/mozilla-mobile/fenix/files/3290325/Error.txt)
and the link from the dashboard:https://debug-ping-preview.firebaseapp.com/pings/c9dd95fc-79ff-455b-ac97-eac9d4ccc7df/aj-testerr-140600

@boek @sblatz  - Please review the attached logs and if any problems encountered, reopen this ticket.
 
Based on this comment I'll remove the QA needed label and close the ticket
