### ISSUE TITLE
[Bug] Fenix does not show any synced tabs in the synced tabs UI

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#12431]
## Steps to reproduce
1. Open Fenix
1. Open synced tabs from kebab menu

### Expected behavior
I see the 1271 tabs I have on the sync server.

### Actual behavior
I see placeholder text with "connect with a firefox account".

### Device information
* Android device: Pixel 2
* Fenix version: 79.0.0-beta.4 and Nightly 200709 06:10 (Build #21910619)

Log attached showing me doing a sync and navigating to the synced tabs UI, first in beta, then in nightly. 

[logcat-sync.txt](https://github.com/mozilla-mobile/fenix/files/4898969/logcat-sync.txt)

**Comment by grigoryk** [comment]
In the logs, it appears like tabs are being synced correctly:

```
07-09 14:51:43.274 I/sync15::sync(28325): Syncing collection tabs
07-09 14:51:43.274 I/sync15::coll_state(28325): Resetting tabs store
07-09 14:51:44.192 I/sync15::client(28325): Successful request to "/1.5/105166049/storage/tabs", incoming x-last-modified=ServerTimestamp(1594320476670)
07-09 14:51:44.231 I/sync15::sync(28325): Downloaded 8 remote changes (request 0 of 1)
07-09 14:51:44.238 I/sync15::sync(28325): Uploading 1 outgoing changes
07-09 14:51:44.238 I/sync15::request(28325): Posting 1 records of 575 bytes
07-09 14:51:44.379 I/sync15::client(28325): Successful request to "/1.5/105166049/storage/tabs", incoming x-last-modified=ServerTimestamp(1594320705410)
07-09 14:51:44.379 D/sync15::request(28325): Committed batch NoBatch
07-09 14:51:44.379 I/sync15::sync(28325): Upload success (1 records success, 0 records failed)
07-09 14:51:44.380 I/tabs::sync::store(28325): sync completed after uploading 1 records
07-09 14:51:44.380 I/sync15::sync(28325): Sync finished!
07-09 14:51:44.380 I/sync15::sync_multiple(28325): Sync of tabs was successful!
07-09 14:51:44.381 I/sync15::sync_multiple(28325): Finished syncing stores.
07-09 14:51:44.381 D/sync15::sync_multiple(28325): sync was successful, final status=Ok
07-09 14:51:44.381 I/sync_manager::manager(28325): Sync finished with status Ok
07-09 14:51:44.381 I/sync_manager::manager(28325): engine "passwords" status: Ok(())
07-09 14:51:44.382 I/sync_manager::manager(28325): engine "bookmarks" status: Ok(())
07-09 14:51:44.382 I/sync_manager::manager(28325): engine "tabs" status: Ok(())
07-09 14:51:44.382 I/sync_manager::manager(28325): engine "history" status: Ok(())
```

> I see placeholder text with "connect with a firefox account".

This seems like problem here, somehow we're not detecting the FxA state correctly in this UI?

**Comment by grigoryk** [comment]
So Synced Tabs logic for determining if account is present or not is just wrong.

Specifically, it's looking at a presence of a an `fxa profile`, and assumes that there's no account available if that profile is missing. This is wrong - profile may be present or absent, it doesn't affect our ability to sync tabs.
Furthermore, the account observers appear wrong to me, as well. We're probably not re-triggering the UI state correctly in response to account manager events.

This is a bug in a-c in `feature-syncedtabs`.

**Comment by grigoryk** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/7667

**Comment by jonalmeida** [comment]
A related PR is here too for reference: https://github.com/mozilla-mobile/fenix/pull/11634

**Comment by kbrosnan** [comment]
Both the linked issues/PRs have been fixed/merged. Closing
