### ISSUE TITLE
FNX2-15243 ⁃ [Bug] synced tab "pull to refresh" never gets re-enabled after encountering an account error

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#12433]
We set `synced_tabs_pull_to_refresh.isEnabled = false` in an `onError` handler in `SyncedTabsLayout`, but there's no corresponding point at which we re-enable once the error has been resolved.

**Comment by grigoryk** [comment]
cc @jonalmeida

**Comment by sv-ohorvath** [comment]
@grigoryk looking at the commits list, this appears to have landed on Beta 79.1.0. Could you please let us know if it's ready for QA? Thanks!

**Comment by jonalmeida** [comment]
@sv-ohorvath this should be ready for testing. Thanks for checking. :)

**Comment by sv-ohorvath** [comment]
@jonalmeida Thanks! I was able to verify the steps on the latest Nightly and Beta 79.1.0 and it works as expected.
Devices: Pixel 4 (Android 10), Htc Desire 820 (Android 6.0.1)
