### ISSUE TITLE
[Bug] Serious performance issues after becoming nightly

### ISSUE THREAD

**Issue by marthinwurer** [mozilla-mobile/fenix#12439]
## Steps to reproduce
Navigate around the old reddit site for a while

### Expected behavior
Navigation remains smooth and responsive.

### Actual behavior
UI becomes laggy and jumps around when you scroll.

If I ignore that issue, it eventually crashes to the launcher and all my app icons have to reload. 

### Device information
* Android device: S8 fully updated
* Fenix version: Nightly 200708 06:05 (Build #21900620)

**Comment by sheikh-azharuddin** [comment]
Try the new version once.. Lagginess somewhat seems fixed

https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.production/latest

**Comment by ekager** [comment]
Closing because this is very old. If you're still having issues, please file a new bug (possibly with logs/video)
