### ISSUE TITLE
FNX2-15241 ⁃ Consider hiding the mic/voice button when using a search engine other than google

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12430]
## User Story
* As a user who has chosen a default search engine other than google, I don't want to accidentally tap on the mic/voice icon which is only available for google search.

### Acceptance Criteria
* I don't see the mic/voice option when using a different search engine than google.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200724 (Build #22060613).
### Devices used:
- OnePlus6T (Android 9)
- Huawei P Smart (Android 9)
