### ISSUE TITLE
[Bug]Misaligned ETP CFR on Android 11 (Emulator)

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12446]
### Prerequisites
Have a fresh install or a clean profile

## Steps to reproduce
1. Navigate to cnn.com

### Expected behavior
Properly displayed ETP CFR (right above the shield)

### Actual behavior
Misaligned ETP CFR (empty space left)

### Device information
* Android device: Emulator Google Pixel 3 (Android 11)
* Fenix version: Nightly 200709 from 7/9

### Notes
:heavy_check_mark: Properly displayed on Google Pixel 4XL (Android 11)

► Screenshot from the Emulator
![rsz](https://user-images.githubusercontent.com/51314259/87160407-9a3c1580-c2cb-11ea-866d-a5e5f6fd5187.png)UNITO-UNDERSCORE!1screenshot!UNITO-UNDERSCORE!1594387743!

► Screenshot from Google Pixel 4XL (Android 11)
![rsz](https://user-images.githubusercontent.com/51314259/87162207-4a128280-c2ce-11ea-9578-4fb6d4ae6e70.jpg)UNITO-UNDERSCORE!1594389209396!

**Comment by Amejia481** [comment]
cc @ekager

**Comment by ekager** [comment]
Hm if it's just on the emulator on Android 11 I'm slightly less concerned, but we can investigate to see if this happens on more real devices.

**Comment by mcarare** [comment]
Tested this on Pixel 4 and the CFR shows up where is expected. Also tested on different configurations on emulators and did not manage to reproduce the issue. I think we should close this and reopen it only if this shows up on a real device.
