### ISSUE TITLE
[Bug] Unable to add a custom search engine (specifically searx.ninja)

### ISSUE THREAD

**Issue by TuxKruger** [mozilla-mobile/fenix#12447]
## Steps to reproduce
Click on 3 dots in the right side of URL/Search bar -> Settings ~~> Search~~ > Add Search Engine ~~> Other ~~> Name (anything, I tried searx, searx.ninja, https://searx.ninja/) ~~> Search string to use~~ -- https://searx.ninja/?q=%s (also tried~~ - https://searx.ninja/search?q=%s and https://searx.ninja/?q=%s&categories=general&language=en~~US which is the actual search string)

### Expected behavior
The search string being an existing one, it is expected from the browser app to actually connect to the site and add the search engine

### Actual behavior
Receiving this response - Error connecting to "<names_I_mentioned_above>"

### Device information
* Android version: 10
* Fenix version: Nightly 200709 06:10
* ROM - MIUI, OxygenOS
* Proxy or VPN - No (though tried with a VPN connection too after constant failures)

**Comment by TuxKruger** [comment]
The issue is fixed in today's update on Google Playstore. Although there's no difference in the version number but anyways, the issue is fixed and I am closing the issue!

**Comment by TuxKruger** [comment]
It worked well for one day, now the issue still persists!!??

**Comment by kbrosnan** [comment]
Duplicate #11332

**Comment by TuxKruger** [comment]
It is probably a bug with Searx.ninja instance since it uses old version of searx. In Searx 17.1 (IG), it was solved. So searx.be like instances work fine.
