### ISSUE TITLE
FNX2-15248 ⁃ [Bug] Tab count does not change on doing Delete Browsing data->Open Tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12440]
## Steps to reproduce
Open some tabs
Go to delete browsing data and select the open tabs check box
Click delete browsing data
Go to home screen

### Expected behavior
Tab Count :0

### Actual behavior
Tab count: not zero

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200710-044719_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/87099862-61079500-c23a-11ea-8033-0a68bf8db6f0.png)

An example, here there are no open tabs and yet the tab counter is set to 1

**Comment by AndiAJ** [comment]
Hi @s-ankur , this got fixed a couple of days ago see [#12126](https://github.com/mozilla-mobile/fenix/issues/12126#issuecomment-655357031).

I **can't repro** this on the latest **`Firefox Nightly build 200710 from 7/10`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video
![20200710-134610](https://user-images.githubusercontent.com/51314259/87146863-4540d500-c2b4-11ea-9e90-34ddda3bb4b5.gif)

**Comment by s-ankur** [comment]
@AndiAJ  oh sorry i was on an earlier build. I can see its fixed. You can close this issue
