### ISSUE TITLE
FNX2-15255 ⁃ Reinsert Restored Tab at Previous Position in Tabs Tray

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#12449]
In https://github.com/mozilla-mobile/fenix/issues/11431 we added scrolling to a restored tab (which is currently restored to the top of the list). 

UX wants to also restore the tab to its previous position in the list, which will require more AC work to add a tab to a particular position.

**Comment by s-ankur** [comment]
Related #11912

**Comment by ekager** [comment]
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/10986
