### ISSUE TITLE
FNX-4898 ⁃ [Bug] Keep the settings menu opened when the app is in background

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1244]
## Steps to reproduce
1. Open the Settings menu.
1. Minimize the app.
1. Restore the app from the task manager.
    1. Expected behavior
The Settings menu is still displayed.
    1. Actual behavior
The menu is closed. You can see it disappearing when you restore the app.
    1. Device information

* Android device: Pixel, HTC Desire 820 (Android 6.0.1)
* Fenix version: 3/28 build.

**Comment by kbrosnan** [comment]
This works for me with a current Fenix build. @sv-ohorvath reopen if you can still reproduce.
