### ISSUE TITLE
[Bug] Text selector looks ugly on zooming

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12455]
## Steps to reproduce
Select some text
Zoom on it 

### Expected behavior
It looks ok

### Actual behavior
It looks as though it has been stretched extremely
![Screenshot](https://user-images.githubusercontent.com/33252312/87184157-05d7b000-c2d7-11ea-89e7-3eede40eba35.png)UNITO-UNDERSCORE!20200710-232654!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Reproducible on the latest Nightly Build 201106 using a Google Pixel 3a (Android 11)

**Comment by s-ankur** [comment]
Hi @AndiAJ seems to be solved now can you confirm?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201210`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20201210-105855](https://user-images.githubusercontent.com/51314259/101749926-fbfce780-3ad6-11eb-827b-4ef0b8c467ae.png)
