### ISSUE TITLE
[Bug] Downloaded PDFs do not open

### ISSUE THREAD

**Issue by CmosError** [mozilla-mobile/fenix#12451]
## Steps to reproduce
1:  Download any PDF file
2: Select "Open" once complete or tapping the notification in tray
3: Installed other PDF viewers, issue persists
4: Downloaded the same PDFs with another browser, and been able to open without fail

## Expected behavior
Downloaded PDF opens

### Actual behavior
Errors states "failed to open doc from stream" (see screenshot attached), large red X appears.

##Screenshots
![1](https://user-images.githubusercontent.com/39971127/87179132-3bb36f00-c2ac-11ea-994a-4b01c7018693.png)
![2](https://user-images.githubusercontent.com/39971127/87179137-3c4c0580-c2ac-11ea-9cd6-6798f4884b19.png)
![3](https://user-images.githubusercontent.com/39971127/87179131-3bb36f00-c2ac-11ea-9036-092170ca3191.png)

### Device information
* Moto Z3 (Android 9) 
* Xperia XA2 (Android 10)
* Android device: Currently Sony Xperia XA2
* Fenix version: 79.0.0-beta4 (build 2015749491)

**Comment by Amejia481** [comment]
@CmosError thanks for reporting the issue. Could you please confirm if you are able to download/open this test [PDF file?](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

**Comment by CmosError** [comment]
> 
> 
> @CmosError thanks for reporting the issue. Could you please confirm if you are able to download/open this test [PDF file?](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

[dummy.pdf](https://github.com/mozilla-mobile/fenix/files/4905007/dummy.pdf)

This downloaded and error stated "Could not open file" when I clicked Open. I was able to open this one with the file browser though. Attached the resulting copy.

**Comment by Amejia481** [comment]
> > @CmosError thanks for reporting the issue. Could you please confirm if you are able to download/open this test [PDF file?](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)
> 
> [dummy.pdf](https://github.com/mozilla-mobile/fenix/files/4905007/dummy.pdf)
> 
> This downloaded and error stated "Could not open file" when I clicked Open. I was able to open this one with the file browser though. Attached the resulting copy.

Which default app do you use for opening PDF? Or which app other browsers open the PDF.

I think the first time you tried you were on a website that requires to be logged we have an open issue for that one https://github.com/mozilla-mobile/fenix/issues/7531 for this reason the PDF was not downloaded correctly.

The error "Could not open file" normally shows when we are not able to find an app that can open that type of file.

**Comment by Amejia481** [comment]
@CmosError is this still reproducible in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)? QA team could take a look, thanks in advance!

**Comment by CmosError** [comment]
It appears to be resolved in nightly

**Comment by ebalazs-sv** [comment]
I had tested this on the latest Nightly 201117 05:03 (Build #2015776107) GV 84 from 11/17 with Motorola Moto G6 (Android 8) and I did not encounter the described issue.

I will close this issue for now, please feel free to reopen it this is reproducible again. Removing the qa:needed label.

**Comment by Amejia481** [comment]
Thanks @ebalazs-sv :)
