### ISSUE TITLE
FNX2-15260 ⁃ [Bug] wrong nightly link in mozilla documentation

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12454]
## Steps to reproduce
https://www.mozilla.org/en-US/firefox/channel/android/?utm_source=support.mozilla.org&utm_campaign=footer&utm_medium=referral#nightly
It shows the old nightly

**Comment by cadeyrn** [comment]
Since it affects mozilla.org it's probably an issue for https://github.com/mozilla/bedrock/issues, I guess.

**Comment by s-ankur** [comment]
Closing for https://github.com/mozilla/bedrock/issues/9225
