### ISSUE TITLE
[Bug] Inconsistency in delete browsing data

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12450]
## Steps to reproduce
This is a corner case but i noticed it so im creating an issue anyway

Open setting/delete Browsing Data
Select only the Site permissions checkbox
Delete browsing data

### Expected behavior
Doing so should take you back to settings screen
This is how it works for any other selection

### Actual behavior
You remain in the delete browsing data screen

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by apbitner** [comment]
@s-ankur 

> This is how it works for any other selection

Can you provide an example(s)?

**Comment by s-ankur** [comment]
Seems this is fixed. Can be closed
