### ISSUE TITLE
[Bug] Rename Settings to Preferences

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#12469]
From about:preferences to it being Preferences everywhere else, setting should be renamed preferences.

### Device information
* Fenix version: 200710

**Comment by cadeyrn** [comment]
There is no "about:preferences" in Fenix so the URI isn't relevant at all. And if you're referring to Firefox for Desktop the preferences are called "Preferences" on macOS but on Windows with ~ 90 percent market share the preferences are called "Options", not "Preferences". So "Preferences everywhere else" is simply wrong.

But it's "Settings" in Chrome and on Android itself. To be consistent with the common OS language is more important. That's also the reason why the preferences also have different names on different Desktop operating systems.

**Comment by jtagcat** [comment]
..but but I really love the name more than any other name for Preferences!
