### ISSUE TITLE
[Bug] ⠇-> Help should be same as in the desktop.

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#12468]
## Steps to reproduce
⠇-> Help

### Expected behavior
Work as in the desktop Firefox. Every time I am filing a bug for Fenix, the Fenix version wants me to go to ⠇-> ![Help Icon](https://design.firefox.com/icons/icons/desktop/help-16.svg) Help -> About FF, since I'm used to doing ≡ ~~> ![Help Icon](https://design.firefox.com/icons/icons/desktop/help-16.svg) Help~~ > About Firefox

### Actual behavior
A help page is opened, the Firefox version can be found in ![Prefs icon](https://design.firefox.com/icons/icons/android/preferences-36.svg) Settings -> About Firefox Nightly.

### Device information
* Fenix version: 200710

Related: #12230

**Comment by kbrosnan** [comment]
This is not expected. We have different UI constraints that make matching desktop behavior a non-goal.
