### ISSUE TITLE
Add tab number to icon in tab tray

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#12461]
### What is the user problem or growth opportunity you want to see solved?
* I'd like to see how many open tabs I have when the tab tray is open

From spike investigation: https://github.com/mozilla-mobile/fenix/issues/10849

**Comment by sblatz** [comment]
This is an e2 for just shipping the current solution I proposed in #10849 (just putting the number beneath the tab). To implement this **inside** the icon may be a larger amount of work. I'd guess an e5.

**Comment by sblatz** [comment]
cc @topotropic so she can follow if needed.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/24 with Samsung Galaxy Note 10(Android 10), and LG G7 FIT (Android 8). The number of tabs opened is displayed only for normal browsing as noted in #10849.

**Comment by Diana-Rus** [comment]
Reproducible on Firefox 79.0.2 with Samsung Galaxy S9 (Android 8), the number of tabs opened in normal browsing are not displayed in tabs tray.
