### ISSUE TITLE
Request: New Tabs Tray Disabler

### ISSUE THREAD

**Issue by JoGarWeb** [mozilla-mobile/fenix#12467]
Please, add an option to "Customize" tab for disable "New Tabs Tray". Before you implemeted that horrifing tab switcher the option was hidden in "Secret Settings". What if you move that option from "Secret Settings" to "Customize"?

Something like this: 
![8Vs58dSqA1L4aRNkIyMDhLK-w7fUKmf8bhAz6V5ATrhU9fNydu49](https://user-images.githubusercontent.com/7904563/87215539-1dc22a80-c2fd-11ea-91df-58b8b32a5f34.png)UNITO-UNDERSCORE!wliSrXPcXxY7ffb-_wQwa33hMsVkA4h5cQSYOAiA6uTwiUAOgdrQELMjOcWEwincGIyGJfhZTCfXj-bbqEM2-7DkgO6rlK5XHabN8aEh4hlaZXVwCA3vK-oMtpdJ7dx5Xp7r3aqRRU9MkiGQhaAntpIXqbqE!

**Comment by gabrielluong** [comment]
Sorry, the new tabs tray feature is effectively shipped at this point which also means wee have removed the the old tabs tray and secret menu preference. Ongoing work is happening to improve the experience, but at this point, please bare with us.
