### ISSUE TITLE
[Bug] Scrolling by holding space bar doesn't deselect.

### ISSUE THREAD

**Issue by jtagcat** [mozilla-mobile/fenix#12470]
(Desktop equivalents)

## Steps to reproduce
1. Be on a page
1. Click the URL (Ctrl+L)
1. All the URL is selected
1. Briefly hold down the spacebar, then move your finger right/left. (right/left arrow)

### Expected behavior
The URL is deselected, since your text cursor has been moved, as in most other apps. The cursor appears at the beginning or at end of the URL.

### Actual behavior
No text cursor is shown at all, text remains selected.

### Device information
* Fenix version: 200710

**Comment by ekager** [comment]
@jtagcat are you still seeing this issue? Could you possibly include a video/gif to describe this further?

**Comment by jtagcat** [comment]
> @jtagcat are you still seeing this issue? Could you possibly include a video/gif to describe this further?

The text cursor deselects, as if on a desktop you'd be holding shift. Going all the way to the beginning releases the shift-like behaviour.

**Comment by jtagcat** [comment]
The expected behaviour, as the space scrolling is equivalent to arrow keys on the desktop, to deselect the text right away. Try Ctrl+L, → on the desktop as an example.

https://sh.c7.ee/9OEkB/ffs-gh-doesnt-support-videos.webm

**Comment by jtagcat** [comment]
unstale

**Comment by jtagcat** [comment]
unstale, just checked, still occurs
