### ISSUE TITLE
[Bug] Tabs are often painted white

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#12477]
## Steps to reproduce
Load some pages using context menu's "open link in a new tab"
Switch to the new tab

### Expected behavior
The new tab should be painted properly showing the web page

### Actual behavior
The new tab is all white. Switching between other tabs eventually forces proper painting.

### Device information
* Android device: Honor 7
* Fenix version: Nightly 200706, GV 20200702

(Hmm, why I haven't gotten more recent update)

**Comment by LittleAngelwings** [comment]
>     * Fenix version: Nightly 200706, GV 20200702
> (Hmm, why I haven't gotten more recent update)

The channels had changed.. For Nightly you must use this version: https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=de

**Comment by smaug----** [comment]
I tried with latest Nightly and the issue happens there too.

**Comment by pocmo** [comment]
Taking this since it is similar to #12593 and could have the same cause.

**Comment by pocmo** [comment]
Yeah, so this looks like it is the same as #12593. Closing this here in favor of #12593.
