### ISSUE TITLE
Add top sites header with icon

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12474]
### What is the user problem or growth opportunity you want to see solved?
Please add top sites header with icon and a collapsible arrow icon similar to desktop browser. In future you can add 3 ellipse menu to it like desktop browser to export the top sites or import in case of factory reset or backup. 

### How do you know that this problem exists today? Why is this important?
While the collection has a header it is missing for top sites. Adding this will ensure consistency. 
Do note the top sites header should only be visible if user has top sites added

### Who will benefit from it?
All users

**Comment by gabrielluong** [comment]
We recently remove the Top Sites header as part of the Tabs Tray work. I am not sure where our position is on bringing back the header, but I will keep this in the backlog until there's more UX direction.
