### ISSUE TITLE
FNX2-15277 ⁃ Undo Close Tab for tabs closed using the back button

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12481]
### What is the user problem or growth opportunity you want to see solved?
Undo is a remarkably important feature. But in fenix it is only available for tabs closed using the x button. Since you can close a tab by pressing the back button as well it makes sense to offer undo functionality for this case as well.

### How do you know that this problem exists today? Why is this important?
Right now if you accidentally close a tab it using the back button, the only way to get them back is finding them through history. This is very time consuming

### Who will benefit from it?
Anyone who accidentally closes a tab

**Comment by cadeyrn** [comment]
> Since you can close a tab by pressing the back button as well

I've never heard of that and I can't confirm that it works. To be honest it sounds like a buf if a tab is closed by pressing the back button.

**Comment by s-ankur** [comment]
@cadeyrn open any link from this page in a new tab. Now press the back button

**Comment by cadeyrn** [comment]
This sound really like a bug: I can confirm that pressing back closes the tab for tabs opened in background, but the same does not happen for other tabs. In my opinion it doesn't make sense at all to have a different behaviour. So first it should be clarified which behaviour is the correct one.

**Comment by s-ankur** [comment]
Frankly this behavior makes more sense to me. If there is no history to go back to then the back button should close the tab, regardless of how it was opened. It should also offer the option to undo close tab but that is not how it is now

**Comment by cadeyrn** [comment]
There are argument for both options but more important is that it either close the tab or not, regardless of how it was opened. At the moment there are two different behaviours and that's why I said that first Mozilla has to clarify what the correct behaviour is.

**Comment by s-ankur** [comment]
Closing as a duplicate of  #11204
