### ISSUE TITLE
[Question] What is the pupose of the private mode home screen?

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12483]
I understand the utility of the normal mode home screen: a place where you can quickly access all your collections and frequently used top sites. But none of these things are available in the private mode homescreen. I fact, as far as I understand, it is not having any feature. So i am curious as to what purpose it serves as personally i think it would be better if new private tab went straight to the search.

**Comment by ekager** [comment]
I'm closing this issue because "new tab" action now does go straight to the search dialog. Hopefully, this is enough :)

**Comment by s-ankur** [comment]
yes, thank you!
