### ISSUE TITLE
[Bug] Numbers not localized anywhere in the UI

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12486]
## Steps to reproduce
Change language to Hindi
Observe tab count or any other place with numbers

### Expected behavior
It follows the english digits 1,2,3..

### Actual behavior
It should follow the indic digits १, २, ३ and so on

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment]
Infact numerals are not localized anywhere in the ui

**Comment by s-ankur** [comment]
Interesting this works corrctly for marathi but not for hindi, not sure why

**Comment by sflorean** [comment]
I was able to reproduce on beta 87.0.0-beta.2.
