### ISSUE TITLE
Swipe to switch modes in tab tray

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12484]
### What is the user problem or growth opportunity you want to see solved?
Right now if you want to switch the mode of the tab tray, for example if you are looking at the normal mode tabs and want to see the private mode tabs then you need to click on the button to change that.

My suggestion is that you should be able to swipe on the blank spqce under the tabs to switch modes. It is faster and requires less effort than clicking a button and  it would feel intuitive as well

### How do you know that this problem exists today? Why is this important?
If you are using the bottom bar, then switching from an open normal mode tab to an open private mode tab will require a lot of finger movement. I believe that this suggestion will minimize that time

### Who will benefit from it?
Everyone using fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3367)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807053

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
