### ISSUE TITLE
[Bug] Status bar icons not visible in Twitter PWA

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#12488]
## Steps to reproduce
1. Go to twitter.com
1. Install it as a progressive web app
1. Open the Twitter PWA

### Expected behavior
Status bar icons are visible above the Twitter header.

### Actual behavior
The status bar icons are invisible as the status bar background and icons are both white.

### Device information
* Android device: Huawei Mate 20 Lite, EMUI 10 (Android 10)
* Fenix version: Nightly 200711 06:00 (Build #21930609)
AC: 50.0.20200710130140
GV: 80.0a1-20200709093347

**Comment by sheikh-azharuddin** [comment]
Works fine here though.. Tested with latest nightly Nightly 200711 18:01. Please update from your side and check once. 

![Screenshot_20200712-183708](https://user-images.githubusercontent.com/58127841/87247055-d8a71100-c440-11ea-8a22-fcb3429e25cc.jpg)

**Comment by anotherus3r** [comment]
@sheikh-azharuddin seems to be a problem when the system theme is set to dark.

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin seems to be a problem when the system theme is set to dark. Switching the system theme to light seems to solve this. Is there a way for Fenix to change the status bar to a dark color when dark mode is on?

Nope.. But i found the problem... When system dark mode is on and fenix theme set to dark or follow system theme, then only the status bar is white with white icons... However if you change the fenix theme to light it is fixed... Seems developer need to fix the issue.. In dark mode the status bar should be dark with white icons

**Comment by AndiAJ** [comment]
Hi @anotherus3r , I've managed to reproduce this issue on the latest **`Fenix Nightly Build 200713 from 7/13`** using a Google Pixel 3a (Android 10) 

► Video
![20200713-153049](https://user-images.githubusercontent.com/51314259/87305314-f054c700-c51e-11ea-8f92-9754a694ff92.gif)

**Comment by anotherus3r** [comment]
Seems to be fixed in latest Nightly. Could you please confirm @AndiAJ ?

**Comment by Scripterr** [comment]
Doesn't fixed for me, also able to reproduce on instagram PWA.
Android 8.0.0 and latest nightly.

**Comment by marcel263** [comment]
Not fixed
