### ISSUE TITLE
[Bug] Language Selection Bar is weirdly small

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12485]
## Steps to reproduce
open setting/language
Search for a language

### Expected behavior
It looks ok

### Actual behavior
It looks like this
![Screenshot](https://user-images.githubusercontent.com/33252312/87243611-dc2d9e80-c426-11ea-99a0-de9cd52641da.png)UNITO-UNDERSCORE!20200712-153005!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by AndiAJ** [comment]
Hi @s-ankur  , I **wasn't able to reproduce** this issue on the latest **`Fenix Nightly Build 200713 from 7/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200713-154319](https://user-images.githubusercontent.com/51314259/87305868-d5368700-c51f-11ea-96c0-8184ffc243a5.png)

**Comment by s-ankur** [comment]
@AndiAJ try to decrease your display size from system settings

**Comment by AndiAJ** [comment]
Thx for the info, I've managed to repro it using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video
![20200713-155759](https://user-images.githubusercontent.com/51314259/87307800-e3d26d80-c522-11ea-83a8-37a892fdc4c9.gif)
