### ISSUE TITLE
FNX2-15278 ⁃ [Bug] Links opened through Google Search results dont show up in History

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12482]
## Steps to reproduce
Google Something
Open any result
Check history

### Expected behavior
It should show the correct website

### Actual behavior
It shows the google redirect url not the actual website.

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by Dunexus** [comment]
Probably related to https://github.com/mozilla-mobile/fenix/issues/7544

**Comment by s-ankur** [comment]
Ohh i compltely forgot about that one😅.

**Comment by s-ankur** [comment]
Closing in favor of #7544

**Comment by s-ankur** [comment]
@data-sync-user is there a reason for reopening 🤔
