### ISSUE TITLE
[Bug] Language Search does not work after you change the language

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12487]
## Steps to reproduce
Go to setting/language
Change language to hindi (or any language not using latin script)
Search for hind or any other language

### Expected behavior
You can search

### Actual behavior
No results

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by mcarare** [comment]
I cannot reproduce this.

**Comment by s-ankur** [comment]
![GifMaker_lowquality](https://user-images.githubusercontent.com/33252312/87292010-b4eed400-c4ef-11ea-9ad4-146e459bfdb3.gif)

**Comment by s-ankur** [comment]
This is on 
Nightly 200711 06:00 (Build #21930609)
AC: 50.0.20200710130140, b54541be1
GV: 80.0a1-20200709093347
AS: 61.0.7

**Comment by ekager** [comment]
@s-ankur can you still reproduce this?

**Comment by s-ankur** [comment]
Still able to reproduce in latest nightly
