### ISSUE TITLE
FNX2-15287 ⁃ [Bug] Fenix sometimes forgets to update the screen/display

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#12492]
## Steps to reproduce
Weird bug. Happens only sometimes.

* Tap back to navigate to the previous page fast enough, ideally going through several pages, or
* Close a tab fast enough, maybe closing several tabs?
    1. Expected behavior
You're shown the previously opened page/tab.
    1. Actual behavior
Fenix seems to get stuck displaying the current tab/page. The fix is just to tap Home and open Fenix from Recents again. The correct tab/page will be shown.
    1. Device information
* Android device: Xiaomi Mi 5 (LineageOS 16)
* Fenix version: Nightly 200711 18:01 (Build #21931810). I'm pretty sure it also happened when it was still called Firefox Preview.

**Comment by pocmo** [comment]
Taking this since it is similar to #12593 and could have the same cause.

**Comment by pocmo** [comment]
Closing this in favor of #12593 as this seems to be the same cause.

**Comment by opusforlife2** [comment]
Closing as duplicate of #12382.
