### ISSUE TITLE
[Bug] Canceling of hanging downloads.

### ISSUE THREAD

**Issue by marthinwurer** [mozilla-mobile/fenix#12496]
## Steps to reproduce
Not actually sure, it just happens a lot. 

### Expected behavior
A download that goes on for too long should get cancelled. 

### Actual behavior
Two things are happening: sometimes a download takes forever and should get cancelled so that I can clear the notification, or something goes screwy and the download becomes null and goes on forever.

Since they're still in the system, I can't remove the notification. The only way to remove the notification is to force stop the app from the settings menu.

### Device information
* Android device: S8
* Fenix version: Nightly 200711 06:00 (Build #21930609)

**Comment by AndiAJ** [comment]
Closing in favor of #15378
