### ISSUE TITLE
FNX-4900 ⁃ Empty state for history

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1249]
Right now it's just a blank fragment with a `Delete history` button

**Comment by topotropic** [comment]
Let's put "No history here" (Inter UI, 16sp, RGBA 21, 20, 26, 48) there.
Similar to: https://mozilla.invisionapp.com/share/4FRF40AVG56
Also discussed in bookmark issue https://github.com/mozilla-mobile/fenix/issues/242#issuecomment-480763002

**Comment by isabelrios** [comment]
This seems to be fixed in build from Wed 5/22 1.0.1921:
![Screenshot_20190523-095742](https://user-images.githubusercontent.com/1897507/58235608-71606600-7d41-11e9-8678-dc0e46bdfcef.png)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/23 build.
