### ISSUE TITLE
[Bug] App resume failed, stuck in limbo?

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#12490]
## Steps to reproduce
Not exactly sure, since this was only the second time it happened. Just try to switch away from Fenix, open/interact with a few other apps, and come back.

### Expected behavior
The app resumes as you left it, or at the very least, the tab loads again upon resuming. This is usually the case.

### Actual behavior
* The entire screen is white except for the status bar, which is blue themed. The address bar is gone. So you can't access the menu or any settings.
* The pull to refresh gesture is somehow accessible in this state, even though it isn't available yet in Nightly. The animation works properly, but then it goes on endlessly, since there is no actual page to reload.
* The system showed an error when I tried to take a screenshot, saying the app doesn't allow this, even though the permission to take screenshots in private browsing was toggled on. Weird.
* The only way left is to swipe away the app from Recents and open it again, losing all your tabs in private browsing.
### Device information
* Android device: Xiaomi Mi 5 ( LineageOS 16)
* Fenix version: Nightly 200711 18:01 (Build #21931810) -- It also happened 2-3 days ago, so it wasn't introduced in this version.

**Comment by s-ankur** [comment]
This has happened to me a few times but i am not able to reproduce it reliably

**Comment by madb1lly** [comment]
Hi all,

Me too. It's happened with PWAs as well, seems to be when I'm switching apps a lot or when opening closing tabs a lot.

Cheers 🙂

**Comment by madb1lly** [comment]
Hi all,

Me too. It's happened with PWAs as well, seems to be when I'm switching apps a lot or when opening closing tabs a lot.

Cheers 🙂

**Comment by kbrosnan** [comment]
Possibly a duplicate of https://github.com/mozilla-mobile/android-components/issues/7753

**Comment by opusforlife2** [comment]
THIS TIME, when it happened, a single back press successfully took me back to the Fenix home screen. Woohoo! I'm... no closer to reproducing this, though. Having low free RAM just makes it more likely to occur.

**Comment by nyanpasu64** [comment]
I think this is the same issue as #4529. When I first reported it, I took some Android Studio layout captures of Fenix. I just hit this issue again on Nightly 200830, but was unable to take a layout capture of Nightly since debugging was disabled.

**Comment by ekager** [comment]
@opusforlife2 or anyone else who commented - have you seen this recently?

**Comment by opusforlife2** [comment]
Nope. Fenix successfully restores each time. Whatever this was seems to be gone now.
