### ISSUE TITLE
FNX2-15293 ⁃ [QUESTION]save login prompt cannot be found in code

### ISSUE THREAD

**Issue by renyson** [mozilla-mobile/fenix#12497]
about save login prompt, I search in code, the string should be "do you want save..."
but in my build, it show "save this login", and related res cannot be found in code
![图片](https://user-images.githubusercontent.com/17057077/87269813-defcc200-c500-11ea-89b4-b1e9c3fe1a24.png)
Is there a problem with my compilation method?
build command:./gradlew clean app:assembleGeckoBetaDebug

**Comment by kbrosnan** [comment]
Fenix builds upon our [Android Components](https://github.com/mozilla-mobile/android-components) core reusable features are often built in the components code.

If you run into trouble building Firefox we have real time chat available at https://chat.mozilla.org/#/room/#introduction:mozilla.org
