### ISSUE TITLE
FNX2-15296 ⁃ [Bug]Add-ons Permission links should open in Fenix

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12503]
## Prerequisites
Add-ons should be installed

## Steps to reproduce
1. Open the Add-on from the manager
1. Open the "Permissions" section
1. Tap the "Learn more about permissions"

### Expected behavior
The link should automatically be opened in Fenix

### Actual behavior
The Android chooser dialog is displayed

### Device information
* Android device: all
* Fenix version: Fenix Nightly Build 200713 from 7/13

### Notes
Should have the similar behavior as #11996 
CC @mcarare & @brampitoyo 

► Video
![20200713-141258](https://user-images.githubusercontent.com/51314259/87298682-402d9100-c513-11ea-8f54-86a0e70929ce.gif)

**Comment by brampitoyo** [comment]
Agreed. Thanks for catching this, @AndiAJ!

As a general rule, _all_ links opened from within the Fenix app, should open in a Fenix browser tab.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200716 from 7/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200716-132708](https://user-images.githubusercontent.com/51314259/87661170-dad2dd80-c768-11ea-8175-b3f64f894d57.gif)
