### ISSUE TITLE
FNX2-15298 ⁃ [Design] Align add ons view section titles

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12509]
Currently add ons view "recommended", "enabled", "disabled" titles not aligned to top bar.
Looks like we need ac changes for this.

@brampitoyo Is this something we want?
If yes, how should we proceed? Just change padding start to 72dp in [this view](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/addons/src/main/res/layout/mozac_feature_addons_section_item.xml)?

![Screenshot](https://user-images.githubusercontent.com/17825767/87314947-8cd19600-c52c-11ea-988a-970639ed57f1.png)UNITO-UNDERSCORE!1594649434!

**Comment by hakkikaancaliskan** [comment]
Here is the result if I change padding start to 72 dp in [this view](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/addons/src/main/res/layout/mozac_feature_addons_section_item.xml).

![Screenshot_1594650656](https://user-images.githubusercontent.com/17825767/87316639-b7245300-c52e-11ea-8bd2-3fc9da8e75f8.png)

**Comment by brampitoyo** [comment]
@hakkikaancaliskan Yes. I haven’t had time to go through every single Settings screen – it’s on my radar – but we do want to align the text under “Add-ons”, too.

The value that you use, 72dp, is correct.

I have checked the individual add-on’s main and sub-pages (Details & Permissions), and these pages are all aligned correctly.

Thanks for proactively proposing these changes!

**Comment by brampitoyo** [comment]
@hakkikaancaliskan If I could propose one additional change for consistency (feel free to file this in another issue if you think that it’s more appropriate):

Under the individual add-on’s main page, there’s a button labelled “Remove”.

<img width="360" src="https://user-images.githubusercontent.com/51007/87391471-f28e5280-c5fe-11ea-98e3-4049613763db.png">

Everything about this button is correct, except the height of the button (48dp). It should be the same height as every other button used on Fenix (36dp).

Visually, it should look identical to the “Delete history” and “Delete browsing history” buttons below:

<img width="360" src="https://user-images.githubusercontent.com/51007/87391700-53b62600-c5ff-11ea-8191-59f31e77db8e.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/87391899-b0b1dc00-c5ff-11ea-9eaa-b5430b40ca70.png">

**Comment by hakkikaancaliskan** [comment]
@NotWoods needs qa verify

**Comment by hakkikaancaliskan** [comment]
For qa verifier: There is 2 thing to check in this issue.
1. Section title item aligment
2. Add-on "remove" button height should match "delete history" and "delete browsing data" height.
