### ISSUE TITLE
FNX2-15297 ⁃ [Bug] [a11y] "Desktop site" icon is not highlighted

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#12505]
## Steps to reproduce
1. Turn on Accessibility - Talkback/Voice Assistant.
1. Open a tab and select the three-dot menu.
1. Using TB gestures, navigate to the "Desktop site" option from the menu.

### Expected behavior
The icon, the "Desktop site" text, and toggle are highlighted together.

### Actual behavior
Only the "Desktop site" text and toggle are highlighted together, the icon is not.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: Beta 79.0.0-beta. 5, 7/11 Nightly build

![settings](https://user-images.githubusercontent.com/40694158/87307190-d4065980-c521-11ea-99e3-23f86e5d9be3.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200826-101315](https://user-images.githubusercontent.com/51314259/91273183-8a966480-e785-11ea-8f5b-c40a8b2f5370.png)
