### ISSUE TITLE
FNX-4902 ⁃ [Bug] Delete history button is missing in history view

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1250]
### Steps to reproduce
1. Open Your Library > History

### Expected behavior
There should be a "Delete history" button.

### Actual behavior
There is no "Delete history" button.

I know there was a "Delete history" button in the past but I thought it was an intentional / temporary / UX change to remove the button because things are still in flux. But in #1249 @boek said the empty history view shows just a blank fragment with a "delete history" button right now. So it seems I should still see a "delete history" buttton. But I don't see the button.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 3ab1b3b3d91e964b486e851401cccb4f473effd8

**Comment by boek** [comment]
@cadeyrn It got removed when we sectioned the history by dates. I'm re-adding it with #1259 which actually wires up the button to actually delete things! I'm going to close this since we're also tracking it there and #356
