### ISSUE TITLE
native code crash on Nightly 200711

### ISSUE THREAD

**Issue by zyx012** [mozilla-mobile/fenix#12514]
## Steps to reproduce
Run Firefox Nightly, it will crash on this android phone

### Expected behavior
Firefox Nightly runs normally

### Actual behavior
Firefox Nightly crashes as soon as it's launched

### Device information
* Android device: Vivax Fun s501, Android Marshmallow 6.0, Mediatek 6580 SOC
* Fenix version: Nightly 200711 06:00

[firefoxnightly.txt](https://github.com/mozilla-mobile/fenix/files/4913700/firefoxnightly.txt)

File attached is adb logcat log

Nightly doesn't crash on a device with the same chipset, but android 7.1.2

**Comment by kbrosnan** [comment]
`07-13 18:12:00.869 E/mozac/CrashReporter( 4531): CrashHandlerService received native code crash`

**Comment by kbrosnan** [comment]
Opened BZ-1652509 as this is some sort of GV crash. The Gecko team will need more info on the Bugzilla bug to address the issue. Please follow along there.
