### ISSUE TITLE
Validate RC: Startup with user-installed WebExtension - Cold startup from applink with installed WebExtension

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#12515]
https://jira.mozilla.com/browse/FXP-946

**Comment by sraturi** [comment]
### Result on S7
Extension installed: uBlock Origin https://addons.mozilla.org/en-CA/firefox/addon/ublock-origin/

|without extension  |with extension  |
|--|--|
| 3.2583388333 | 3.39267166 |

Overall Takes ~104% time to start with an extension

**Comment by MarcLeclair** [comment]
### Result on Pixel 4
Extension installed: uBlock Origin https://addons.mozilla.org/en-CA/firefox/addon/ublock-origin/

|without extension  |with extension  |
|--|--|
|  0.17092000000000002 | 0.23404000000000016 |

Having 1 web extension seems to worsen start up by ~136%

**Comment by MarcLeclair** [comment]
We need to know which extension we want to test with. Desktop tests with 5 extensions, which we decided we should do. Question remains, which extensions do we want to test with? @ecsmyth

**Comment by MarcLeclair** [comment]
Closing for now  since this was mainly a use case for perftest. We can reopen this if we want to introduce this use case later on.
