### ISSUE TITLE
Add a update button to the add-on item

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#12513]
When an add-on requires new permissions we need to add a update button for manual update s

![image](https://user-images.githubusercontent.com/773158/71379951-67cf0300-259b-11ea-8fb4-12ccc18ceffd.png)

![image](https://user-images.githubusercontent.com/773158/71380411-0ad44c80-259d-11ea-857f-7c050d05cbfc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3400)

**Comment by AmyYLee** [comment]
Assigned to @brampitoyo

**Comment by AmyYLee** [comment]
@brampitoyo any update on this?

**Comment by brampitoyo** [comment]
Thanks for contacting me again on this issue, @AmyYLee.

Checking with @Amejia481 – I saw that you labelled this issue `needs:UX-feedback`. Is there any question that I can help answer?

**Comment by Amejia481** [comment]
@brampitoyo we want to verify if the UI above on https://github.com/mozilla-mobile/fenix/issues/12513#issue-655969715 should be the  should be the right one for the update button.

**Comment by brampitoyo** [comment]
@Amejia481 Yes. I can confirm that this is the right UI for the update button.

Let me complete this issue early next week, by posting links to the Abstract artboard.

**Comment by Amejia481** [comment]
Thanks!

**Comment by anotherus3r** [comment]
Would this also include a button to manually trigger a check for new updates for all installed add-ons? Like the equivalent option on the `about:addons` page in desktop Firefox.

**Comment by brampitoyo** [comment]
@anotherus3r It seems to me that “manually check for updates” is a feature that should be made accessible using a gesture like pull to refresh, rather than a totally separate control. What do you think?

**Comment by anotherus3r** [comment]
@brampitoyo Yes, that sounds good. Only question is would it be easy to discover by other users.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813921

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
