### ISSUE TITLE
FNX-4903 ⁃ Download completed notification

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1252]
## Steps to reproduce
-Open Fenix and browse to a site where you can download a file (e.g. Restaurant menu)
-Tap on a link to download 
-Allow Fenix to access storage
-On the download prompt, tap on DOWNLOAD

### Expected behavior
-Download is completed and there is a new Download completed notification in the phone notification tray.

### Actual behavior
-Download is completed but there is no notification

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1914

**Comment by pocmo** [comment]
Related functionality in AC:
https://github.com/mozilla-mobile/android-components/tree/master/components/feature/downloads#downloadsfeature

**Comment by vesta0** [comment]
@ekager could you please test this with your Pixel 3 and let me know if you get the download confirmation notification?

**Comment by ekager** [comment]
I just tried to reproduce by searching "download sample pdf" and downloaded this pdf: http://www.pdf995.com/samples/pdf.pdf

I was able to see the download notification when completed. 

Maybe it is site specific? Do you remember which menu you were dowloading? Or are you unable to ever see the download notification?

**Comment by andreicristianpetcu** [comment]
I have the same issue on OnePlus2 lineageos 14.1 based on android 7.1.2

**Comment by vesta0** [comment]
Dup of #3465
