### ISSUE TITLE
FNX2-15313 ⁃ [Bug] Main Settings screen categories should have 16dp keyline

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#12533]
cc: @brampitoyo 

Currently it's 72dp:

![Screenshot](https://user-images.githubusercontent.com/48995920/87394221-209c7400-c5b8-11ea-845e-6bee7703a7db.jpg)UNITO-UNDERSCORE!20200713!UNITO-UNDERSCORE!163013!UNITO-UNDERSCORE!org mozilla fenix debug!

**Comment by brampitoyo** [comment]
Corrent. Just to note: sub-headings on this root Settings page is a special exception at 16dp. On every other Settings sub-pages, we will align to 72dp keyline.

**Comment by cadeyrn** [comment]
> sub-headings on this root Settings page is a special exception at 16dp. On every other Settings sub-pages, we will align to 72dp keyline.

why are we introducing such an noticeable inconistency? 🤔

**Comment by cadeyrn** [comment]
@brampitoyo Please see the question above. Now the change landed and to be honest it feels like a bug to me that on the main settings screen there is no gap now but still on all other screens. Could you please clarify what the rationale is? Is this a Google Material Design guideline? Why does it apply to one but not to other screens?

**Comment by brampitoyo** [comment]
@cadeyrn I’m in two minds about this.

On one hand, I share the same concern about having one consistent policy that we can apply on every single in-app pages (not just Settings. See also: History, Bookmarks, Synced Tabs.)

On the other hand:

- If we make all headings follow a 16dp keyline, it would introduce awkward left-side gaps under one section: Search → Address bar.
- Android’s own System Settings have headings with 72dp keyline, although you’re right: practically all Google apps use 16dp keyline – so why can’t we follow them?

Ultimately, I’m looking for a policy for all headings, that can serve as a guide for making future choices, and that will result in good layouts 100% of the time. It seems like this is a really ambitious ideal! But if we have a policy of “let’s do what looks good in each situation”, I’m also afraid that it will lead to inconsistent layout.

I suppose that was why I made an exception one time, just for the root Settings page, but not for any other sub-pages.

Let me know if you’ve thought of a good idea to solve this problem. I’d be really interested to hear it!

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/30 and Beta 80.0.0-beta.1 with Samsung Galaxy Note10 (Android 10), and Huawei MediaPad M2 (Android 5.1.1).
