### ISSUE TITLE
[Bug] Firefox crashes on Motorola device, with different scenarios

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12535]
## Steps to reproduce 1:
1. Launch Nightly and open 3-4 tabs;
1. Download a file and keep the notification;
1. Leave the app in stand by for 20 minutes;
1. Observe the download notification;
1. Tap on the open tabs from Tabs tray;

### Expected behavior 1
The download notification is displayed the same and the tabs are loading.

### Actual behavior 1
The download notification is displayed as "null", one of the tabs is displayed as blank and Nightly crashes.
Crash report: https://crash-stats.mozilla.org/report/index/33a7f6d6-81e2-474c-9c53-8abf30200714#tab-details

### Notes
![20200714](https://user-images.githubusercontent.com/48799384/87392641-905d2f80-c5b5-11ea-9f08-00cdc7e0575a.gif)UNITO-UNDERSCORE!092555!
This is not reproducible all the time. I reproduce this behavior only once from 4 tries.

## Steps to reproduce 2:
1. Launch Beta and opens 3-4 tabs;
1. Go to Settings - Customize and choose "Dark";
1. Go to Tabs tray and tap the open tabs, one by one;
1. Observe the behavior.
    1. Expected behavior 2
The open tabs are loaded.
    1. Actual behavior 2
Firefox crashes.
Crash report: https://crash-stats.mozilla.org/report/index/e0694b4c-220c-42e1-a83d-b032a0200714
    1. Device information

* Android device: Motorola Moto G6 (Android 8)
* Fenix version: Nightly 200713 GV 80 from 7/13, Beta 79.0.0-beta.6, 7/14, Beta migration 79.0.0-beta.6

**Comment by sheikh-azharuddin** [comment]
It is crashing even in my rog 2...too much crashing today😕
![Screenshot_20200714-183926](https://user-images.githubusercontent.com/58127841/87429471-75181180-c601-11ea-84ea-76dc45aee64b.jpg)

**Comment by ebalazs-sv** [comment]
This is reproducible on Release Migration 79.0.0 (Build #2015753313) GV 79 from 7/21 with Motorola Moto G6 (Android 8).

**Comment by ebalazs-sv** [comment]
This is also reproducible on Fenix 81.1.1-beta.5 with Motorola Moto G6 (Android 8).
crash report: https://crash-stats.mozilla.org/report/index/b36ab2dc-b46b-4bda-82d0-905250200915#tab-details

**Comment by adrian3d** [comment]
I have the same too, on a Motorola Z2 Play, Android 8, since the Firefox Preview.
