### ISSUE TITLE
FNX2-15311 ⁃ Align Settings -> Private browsing to 72dp keyline

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#12531]
@hakkikaancaliskan 

![](https://user-images.githubusercontent.com/51007/87392035-ec4ca600-c5ff-11ea-8614-e7ae927f3d28.png)

**Comment by ebalazs-sv** [comment]
@brampitoyo Hi! I had tested this on Nightly 200720 (Build #22020611) GV 80.0a1 from 7/20 with Motorola Moto G6 (Android 8). Is this the expected result? Thanks!
![Screenshot_20200720-160432](https://user-images.githubusercontent.com/48799384/87940969-104a3480-caa3-11ea-8f71-4af0ff526d88.png)

**Comment by hakkikaancaliskan** [comment]
> @brampitoyo Hi! I had tested this on Nightly 200720 (Build #22020611) GV 80.0a1 from 7/20 with Motorola Moto G6 (Android 8). Is this the expected result? Thanks!
> ![Screenshot_20200720-160432](https://user-images.githubusercontent.com/48799384/87940969-104a3480-caa3-11ea-8f71-4af0ff526d88.png)
> 

Yep, we added gap. That's what we expected.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200720 (Build #22020611) GV 80.0a1 from 7/20 with Motorola Moto G6 (Android 8).
Thanks for the quick reply!
I will remove the qa:needed label.
