### ISSUE TITLE
Align Settings -> Site permissions -> Sub-pages to 72dp keyline

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#12532]
@hakkikaancaliskan 

The main page of Site permissions has correct keyline value and icon alignment.

![](https://user-images.githubusercontent.com/51007/87392285-58c7a500-c600-11ea-8651-2f27d2c69b73.png)

The sub-pages (Autoplay, Camera, Location, Microphone, Notification, Exceptions) all need to follow.

### Sub-page: Location (also applies to other adjacent sub-pages)
The text block that says “Blocked by Android” should also align to a 72dp keyline.

![](https://user-images.githubusercontent.com/51007/87392694-1488d480-c601-11ea-9ac6-210ff6e5f8ac.png)

### Sub-page: Exceptions
![](https://user-images.githubusercontent.com/51007/87392499-bf4cc300-c600-11ea-977f-72b2d4979c1e.png)

### Sub-page: Exceptions -> Individual site ~~> Location (also applies to other adjacent sub~~pages)
The text block that says “Blocked by Android” should also align to a 72dp keyline.

![](https://user-images.githubusercontent.com/51007/87392635-fde27d80-c600-11ea-8025-23b7ec9746cd.png)

**Comment by sv-ohorvath** [comment]
@liuche @eliserichards Looking at the commits list, this appears to have landed on Beta 79.1.0. Could you please let us know if it's ready for QA? Thanks!

**Comment by hakkikaancaliskan** [comment]
@ekager this issue was fixed a while ,ready for QA review

**Comment by softvision-miralobontiu** [comment]
Hi all!

The settings in Site permissions are not aligned yet in the latest Nightly from 7/24, or Beta 79.1.0-beta.1. Tested on Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

![permissions](https://user-images.githubusercontent.com/40694158/88390791-a17e1b80-cdc1-11ea-85f8-601d7f3df36b.png)

**Comment by hakkikaancaliskan** [comment]
> Hi all!
> 
> The settings in Site permissions are not aligned yet in the latest Nightly from 7/24, or Beta 79.1.0-beta.1. Tested on Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
> 
> ![permissions](https://user-images.githubusercontent.com/40694158/88390791-a17e1b80-cdc1-11ea-85f8-601d7f3df36b.png)
> 

Is it aligned in nightly?
Because we've merged a PR for that alignment, maybe 79.1 doesn't include it.

**Comment by hakkikaancaliskan** [comment]
Hmm, that's aligned on my device. I'll take a look at it when I get home.

**Comment by hakkikaancaliskan** [comment]
@softvision-miralobontiu That radio button texts are aligned on my devices with master and 7/24:
XZ1 Android 10
<img src="https://user-images.githubusercontent.com/17825767/88440988-665b0700-ce18-11ea-82ce-5dd85ae6c5c3.png" width="300">

Android 5.0 API 21 Emulator
<img src="https://user-images.githubusercontent.com/17825767/88441005-71ae3280-ce18-11ea-8459-d48144eacc6b.png" width="300">

@NotWoods how or what should i do for this?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/15 Nightly, on Beta 86.0.0-beta.5, and RC 85.1.3, with Google Pixel (Android 10).
