### ISSUE TITLE
FNX2-15316 ⁃ [Bug] Deleting browsing data does not delete crashes

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12541]
## Steps to reproduce
Delete browsing data either through settings or through delete browsing data on quit

### Expected behavior
Crash data is deleted, as it may contain sensitive info

### Actual behavior
It is not. In fact i dont think there is a way to delete it.
Also i am not sure whether fenix should keep crash data from private browsing sessions

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by eliserichards** [comment]
We are matching the behavior of desktop Firefox.
