### ISSUE TITLE
FNX2-15319 ⁃ [Bug] Search widget open private mode tabs if browser is in PBM

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12545]
## Steps to reproduce
Set browser to private browsing mode by opening a private tab
Go to search widget and search

### Expected behavior
Normal tab

### Actual behavior
Private tab

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by eliserichards** [comment]
This is intentional behavior. Can @vesta0 confirm?

**Comment by eliserichards** [comment]
Confirmed!

**Comment by s-ankur** [comment]
@eliserichards is it possible to discuss this futher? Because i feel that the state of the browser should not affect how the widget works. It is not really intuitive behavior and feels a lot like spooky action at a distance.
