### ISSUE TITLE
[Bug][Regression]Missing or intermittently displayed "Save tabs to collection" while having open tabs on 79.0.0-beta.6

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12547]
## Steps to reproduce
1. Open one by one the default Top Sites
1. Observe the availability of "Save tabs to collection" button in the process

### Expected behavior
"Save tabs to collection" button should be displayed

### Actual behavior
"Save tabs to collection" is displayed intermittently or sometimes is missing

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)
* Fenix version: 79.0.0-beta.6 from 7/14

### Notes
Seems to be a regression of #12125 
❗ Not reproducible on the latest **Nightly Build 200714 from 7/14**

► Video
![20200714-153909](https://user-images.githubusercontent.com/51314259/87430108-645da080-c5ed-11ea-8a67-8c84843da6b0.gif)

**Comment by Diana-Rus** [comment]
Reproducible with Samsung Galaxy S9 (Android 8) on Firefox 79.0.2

**Comment by sflorean** [comment]
I wasn't able to reproduce this issue on Nightly or Beta, following the steps with Pixel 3 (Android 11).

**Comment by amedyne** [comment]
Closing issue per comment above.
