### ISSUE TITLE
FNX-4905 ⁃ [Bug] developer.android.com page appears broken

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1255]
## Steps to reproduce
1. Visit http://developer.android.com in the latest Fenix

### Expected behavior
CSS stylesheets are applied and look similar to Fennec or Chrome on mobile.

### Actual behavior
CSS stylesheets are not applied. The page appears broken.

### Device information
* Android device: Android Pie
* Fenix version: Build #10851633

**Comment by vesta0** [comment]
@cpeterso is there a GV bug for this?

**Comment by cpeterso** [comment]
I can reproduce this bug in Fenix, but not Fennec 66/67/68 or Focus+GV 65. I can't test RB because it crashes.

I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1541632

**Comment by kbrosnan** [comment]
This is fixed in a current Fenix build.
