### ISSUE TITLE
[Bug] 'Failed to query Addon' again

### ISSUE THREAD

**Issue by vishalnandagopal** [mozilla-mobile/fenix#12556]
#12399 - Had been fixed with the last update. Returned again after this update.

## Steps to reproduce
Open app. Click the three dot menu. Select addons.

### Expected behavior
Should open addon menu

### Actual behavior
Doesn't open.

### Device information
Android 10 , Nightly 200714 06:01 (Build #21960614)

Addons work. Just can't access their settings.

**Comment by csadilek** [comment]
https://github.com/mozilla-mobile/fenix/issues/12399 is not fixed yet, it's an open ticket and we're actively working on it. It's an intermittent problem. It will appear in Nightly until https://bugzilla.mozilla.org/show_bug.cgi?id=1651697 is resolved. See comment at https://github.com/mozilla-mobile/fenix/issues/12399#issuecomment-656371846

Sorry for the problems this causes, but we will have a fix soon. Please keep tracking https://github.com/mozilla-mobile/fenix/issues/12399 for this issue.
