### ISSUE TITLE
Radio buttons and checkboxes not aligned

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12550]
Radio buttons and check boxes not aligned across fenix because in ux mocks they're 24x24 but Android's default ones are 36x36.

Looks like there's 2 way:

1. We need to find a way to set them 24x24.
1. We can hide that paddings via hacky dimens.

Here is where we used radio buttons and checkboxes (maybe I missed some of them) (all of them misaligned)

* Settings -> Search "show in private sessions checkbox (I've fixed search engine radio buttons via hacky dimens)
* Settings -> Customize radio buttons
* Settings -> ETP radio buttons
* Settings -> Site Permissions, general and per site radio buttons
* Settings -> Delete browsing data on quit checkboxes
* Settings -> Delete browsing data checkboxes
* Settings -> Account checkboxes

**Comment by eliserichards** [comment]
@hakkikaancaliskan it would be nice to document which specific icons need to be resized so that this issue can be scoped 👍

**Comment by hakkikaancaliskan** [comment]
@eliserichards updated comment 0
