### ISSUE TITLE
[Bug] can't swipe download inform

### ISSUE THREAD

**Issue by cvbni** [mozilla-mobile/fenix#12553]
![Screenshot](https://user-images.githubusercontent.com/13873462/87451577-a2c97e80-c632-11ea-9fcc-ccb9e33da1a8.png)UNITO-UNDERSCORE!2020-07-15-00-31-47-0521036086!

## Steps to reproduce
I downloaded a file, then swiped the download information, then turned the "null "  in info bar.
I can't swipe the "null" download item away.

I have to restart my phone to get rid of it.

* Android device: lenovo z6, Android 9.0(zui 11)
* Fenix version: 79.0.0-beta.7

**Comment by Amejia481** [comment]
Would you mind sharing which url you were trying to download? Does the notification have a "Retry" and a "Cancel" buttons?

**Comment by cvbni** [comment]
no, the notification do not  have a "Retry" and a "Cancel" buttons.
---------------------
https://m.mydrivers.com/newsview/700569.html
every link I test, the result is the same.
step 1,
I download this html link.

![1](https://user-images.githubusercontent.com/13873462/87458187-2dfb4200-c63c-11ea-91a5-f4bfa8a26d1f.png)

step 2.
I have downloaded the html file,and the notification show:

![2](https://user-images.githubusercontent.com/13873462/87458508-ad891100-c63c-11ea-8743-951590961290.png)

step3.
I swiped the notification(step 2.),then turn out the "null"  download item

![3](https://user-images.githubusercontent.com/13873462/87458916-3d2ebf80-c63d-11ea-9c84-a4e6326e9c0f.png)

**Comment by hakkikaancaliskan** [comment]
@Amejia481
Currently we're recording downloads to Android's download library. Maybe that's the problem because fenix's notification is swipeable (@cvbni says) and second one that appears not swipeable.

> I swiped the notification(step 2.),then turn out the "null" download item

**Comment by Amejia481** [comment]
I think we addressed this on https://github.com/mozilla-mobile/android-components/pull/8858 looks pretty similar to https://github.com/mozilla-mobile/fenix/issues/15527, please feel free to reopen if it's still happening
