### ISSUE TITLE
FNX2-15327 ⁃ [Bug] Can't click on link at bottom of page

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#12557]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1652288

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

Steps to reproduce:

I'm working on building a web app at https://quartermaster.fyi/. On https://quartermaster.fyi/sightings, there is a button-styled link at the bottom of the page which is labeled "Add sighting". I tried to click this button in Firefox Nightly for Android.

It seems I have to fill out the Version field but I'm not really sure what version it is. Going to About Firefox Nightly reports:

Nightly 200711 06:00 (Build #21930608)
AC: 50.0.20200710130140, b54541be1
GV: 80.0a1-20200709093347
AS: 61.0.7

Saturday 7/11 @ 6:08 AM

Actual results:

Clicking this button on Firefox Nightly for Android does nothing, although it works fine for Firefox Desktop, even when in Responsive Design Mode.

Expected results:

It should take you to https://quartermaster.fyi/sightings/new.

I've been trying to debug this, thinking it was an issue in my application, and it seems that if I add another element to the bottom of the page with height of about 50px, I can interact with the element, but only if I touch the top part of it. For this reason, I wonder if it is being "covered" somehow by the address bar, even when the address bar is not visible.

**Comment by kbrosnan** [comment]
Might be bz-1652190

**Comment by hiikezoe** [comment]
@st3fan are you able to reproduce the issue?  I can't repro at all.

**Comment by st3fan** [comment]
Yes. I tried on Firefox Beta on a Pixel 2XL and although the button was fully visible, tapping it did not do anything.

**Comment by hiikezoe** [comment]
Thank, that's weird.  Why I can't repro at all. Anyways, if the button is visible it's not related to https://bugzilla.mozilla.org/show_bug.cgi?id=1652190, I think.

**Comment by kbrosnan** [comment]
You can't go directly to https://quartermaster.fyi/sightings this seems to break the site, I never get any data to load. You need to visit the site and tap the `Sightings` heading to load the data. In that case I see the broken behavior.

**Comment by kbrosnan** [comment]
For some reason tapping into the site's search bar and dismissing the keyboard allows the navigation to work.

**Comment by hiikezoe** [comment]
I could reproduce the issue locally, so I did reopen the bug in bmo.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200803 (Build #22161810).
### Devices used:
- Huawei MediaPad M3 lite (Android 7)
- OnePlus 6T (Android 9)
