### ISSUE TITLE
[Bug] Selection menu search not using default search provider

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#12559]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1651638

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

Steps to reproduce:

Coming from Firefox Android Preview, on Firefox Beta I set my default search provider to Startpage.com manually.

Actual results:

When I select some text and let Firefox Beta run a search via the selection menu, it used DuckDuckGo. I removed all search engines but Startpage.com, which led to Firefox defaulting to Google.

Expected results:

Firefox Beta should use Startpage.com (or whichever chosen engine) for all searches. This problem does not occur when I use the navbar to search. I am unable to replicate this issue on Firefox Nightly. It only happens in Firefox Beta.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly 201218`** and  **`85.0.0-beta.2`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
