### ISSUE TITLE
[Bug] Tabs tray opening background fade animation seems reversed in PBM

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#12563]
## Steps to reproduce
1. Switch to PBM
1. Open the tabs tray

### Expected behavior
The background fading animation is similar to the one observable without active PBM.

### Actual behavior
The background fading animation fades from a lower brightness to a higher brightness, reversing the behaviour compared to the animation without active PBM.

![video](https://user-images.githubusercontent.com/42788925/87464344-4145e780-c613-11ea-8c92-37bfd9f8b825.gif)

### Device information
* Android device: 6.0.1, Sony Xperia Z2
* Fenix version:
Nightly 200714 06:01 (Build #21960613)
AC: 50.0.20200712190143, 22f032ca7
GV: 80.0a1-20200711092223
AS: 61.0.7

**Comment by AmyYLee** [comment]
It looks like the PBM overlay is a different colour than the non-PBM overlay.

**Overlay for Dark/Light/PBM: Ink 90 (#1D1133) 48% Opacity**

The fade transition also looks like it's missing from the PBM version. This should match the fade animation in non-PBM.

Thanks

**Comment by ekager** [comment]
We got rid of the scrim on home. Closing

**Comment by hwinnemoe** [comment]
@ekager I have looked at this again and this issue still persists in the current Nightly, e.g. Nightly 210125 17:01 (Build #2015789449). The scrim was only removed when entering URLs in the toolbar, not when opening the tabs tray.

**Comment by hwinnemoe** [comment]
This has been fixed by f5b068a which intended to fix #17785 but also resolved this issue.
