### ISSUE TITLE
Clean up use of Context and Activity within Controllers

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#12565]
Clean up uses of `Context` and `Activity` in our code, specifically within `Controllers`, based on conversation with @Mugurell in https://github.com/mozilla-mobile/fenix/pull/11208:

> I'm normally against passing it around and then expect all receivers to know how to build/extract their end dependencies from it. (Demeter's law).
To keep the code clean, have a better separation of responsibilities, loose coupling and ease testing I would propose to have end dependencies sent as parameters to the controller.
Here I see that anyway the context, cast to a specific activity!? is only used for obtaining a reference to components.core.passwordsStorage. That can easily be injected in the constructor without even worrying about it become bloated.

**Comment by gabrielluong** [comment]
@mcarare curious if we should be closing this as in we are completely done with all the clean up of these usages?
