### ISSUE TITLE
FNX-4907 ⁃ Investigate how Doorhanger should look like in tablets

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1257]
@brampitoyo Do we have some mock-ups for the Doorhanger interaction in tablets?

![image](https://user-images.githubusercontent.com/773158/55241235-0eef5b80-5211-11e9-83cf-1688396cf3dc.png)

**Comment by Amejia481** [comment]
cc: @pocmo

**Comment by brampitoyo** [comment]
@Amejia481 wrote:
> Do we have some mock-ups for the Doorhanger interaction in tablets?

Good question!

If the tablet layout looks like this:

<img src="https://user-images.githubusercontent.com/51007/55393121-d62fe900-5566-11e9-8b32-0423f0994742.png">

Then the site information panel doorhanger would look like this:

<img src="https://user-images.githubusercontent.com/51007/55393159-e9db4f80-5566-11e9-99fa-af9138829cae.png">

Note the rounded corner (mobile doorhangers have square edges) and its positioning relative to the URL bar.

CC @shorlander @AmyYLee to check my work.

**Comment by Amejia481** [comment]
Thanks @brampitoyo !
