### ISSUE TITLE
Add telemetry probe: was startup cold, warm, or hot?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#12573]
We want to know how often the app opens in a cold, warm, or hot state. via https://jira.mozilla.com/browse/FXP-1071

**Comment by sraturi** [comment]
QA: can you ensure the probe app_startup_all accurately represents what it says it should represent and edge cases are handled correctly.

Some test cases:

    Launch app, FenixApplication is created = COLD startup
    Launch app on external activity = COLD
    Launch app through icon ->press home button -> open external activity (creating a new activity) = WARM
    Launch app through icon -> press home button -> open a link = HOT

**Comment by AndiAJ** [comment]
Hi I've just checked this matter on the latest Nightly Build 200908 using a Google Pixel 3a (Android 10)


• Open first time Fenix using: **`adb shell am start -n org.mozilla.fenix/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es tagPings aj-t08090`**

Ping **b1731157-230b-42b2-9735-7677b0cf6b84**
```
{
          "category": "events",
          "extra": {
            "has_saved_instance_state": "false",
            "source": "UNKNOWN",
            "type": "COLD"
          },
          "name": "app_opened_all_startup"

```

• While Fenix is in background - > Open a custom tab 
Ping **c5875daa-9c5d-42cb-94fa-dc28f5e97b84**
```
{
          "category": "events",
          "extra": {
            "has_saved_instance_state": "false",
            "source": "CUSTOM_TAB",
            "type": "WARM"
          },
          "name": "app_opened_all_startup"
```


• While Fenix is in background -> Open a custom tab -> Open the custom tab in Fenix (using the "Open in Firefox Nightly" from the custom tabs overlay )
Ping **67e65f06-0bb1-4e02-bc72-2af786f225aa**
```
"events": [
        {
          "category": "events",
          "extra": {
            "source": "UNKNOWN",
            "type": "HOT"
          },
          "name": "app_opened_all_startup"
```



• Open a custom tab -> Force close Fenix -> Open Fenix from the App icon
Ping **71db0d4b-506e-4fa0-ab7d-f57934efbb64**
```
{
          "category": "events",
          "extra": {
            "has_saved_instance_state": "false",
            "source": "APP_ICON",
            "type": "WARM"
          },
          "name": "app_opened_all_startup"

```

• Force close the custom tab -> While Fenix is in background tap the App icon
Ping **815f77c7-8aa7-4d7f-8b3b-51b05808b582**
```
{
          "category": "events",
          "extra": {
            "source": "APP_ICON",
            "type": "HOT"
          },
          "name": "app_opened_all_startup"
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/5187379/cwh.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t8090)

@mcomella & @sraturi - Please review and share your thoughts. ☺️ 
**I'll remove the QA needed label until further notice.**

**Comment by mcomella** [comment]
@AndiAJ These are really good test cases – thanks for testing so thoroughly.

These all seem like reasonable values given the implementation. The results for some of these are misleading, e.g.:
- While Fenix is in background - > Open a custom tab
- Open a custom tab -> Force close Fenix -> Open Fenix from the App icon

So I'll try to document them. Closing as QA'd.
