### ISSUE TITLE
FNX-13656 ⁃ Renaming "Shortcuts" to "Search engines"

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12571]
Let's rename search "Shortcuts" to "Search engines" based on UX recommendation. 

![image](https://user-images.githubusercontent.com/42752644/87480201-d092d100-c5fa-11ea-8479-46e40df0bab7.png)

### What is the user problem or growth opportunity you want to see solved?
People may not understand that tapping the “:mag: Shortcuts” button will give them a selection of search engines to choose from.

By renaming “:mag: Shortcuts” to “:mag: Search engines”, we are labelling the feature using a name that people may be more used to hearing.

![](https://user-images.githubusercontent.com/51007/87491611-b4e00700-c69c-11ea-8c85-5e7e3b7ea4a8.png)

**Comment by NotWoods** [comment]
Since this should just involve string changes I'm making it as good first issue

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200727 from 7/27`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200728-092513](https://user-images.githubusercontent.com/51314259/88627490-0d5bcf00-d0b5-11ea-867b-c4b582d9f27e.png)
