### ISSUE TITLE
Opening a new tab and navigating to it breaks the camera/microphone notification

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#12574]
I have independently confirmed Jan-Ivar's steps in Nightly

### STR:
1. Open https://jan-ivar.github.io/dummy/gum_events.html and allow camera + mic
1. In a new tab, open a random site e.g. https://stackoverflow.com/
1. Go to a different app or the Android home screen.
1. Drag down notification bar and click on _":video_camera: Firefox Nightly: Camera and microphone are on"_

### Expected result:
* Firefox opens to tab with https://jan-ivar.github.io/dummy/gum_events.html 

### Actual result:
* Firefox opens to tab with https://stackoverflow.com/

Might be related to https://github.com/mozilla-mobile/android-components/issues/7477

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3471)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809279

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
