### ISSUE TITLE
[Bug] Loading a page with an embed causes associated app to open

### ISSUE THREAD

**Issue by nathansgithub** [mozilla-mobile/fenix#12575]
## Steps to reproduce
Open a page with an embedded Youtube link on a device with the Youtube app installed. The "Open links in apps" option in Firefox should be enabled. Example URL (the Youtube embed is in the comments of the article): https://paleofuture.gizmodo.com/whats-on-the-ground-in-the-jetsons-1796495295 I think this is a recently introduced bug.

### Expected behavior
Firefox should not open the external app unless the user goes to the URL associated with the app. If you do click the embed, I would expect the video to load inside the page, but it definitely shouldn't redirect to the app just because you load a page with a video embedded in it.

### Actual behavior
Once the page loads the embedded content, it will automatically load the Youtube app without prompting. I have also seen Firefox open the installed Facebook app when loading a news article with an embedded Facebook comment feature.

### Device information
* Android device: Motorola Z3 Play, Android Pie
* Fenix version: Nightly 200711 6:00 (Build #21930609)

**Comment by somepaulo** [comment]
Had this in Android Beta and now also have this in the latest regular Firefox for Android that I got updated to this morning.

**Comment by ekager** [comment]
@nathansgithub @somepaulo are you still experiencing this bug?

**Comment by nathansgithub** [comment]
@ekager It looks like it is working now. Thanks!
