### ISSUE TITLE
FNX2-15331 ⁃ [Bug] Remove search suggestions after erasing

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#12570]
## Steps to reproduce
1. Click on address bar to start a new search 

![](https://user-images.githubusercontent.com/43795363/87478340-3e390000-c5ef-11ea-8688-cefdd9109f85.png)

1. After you type something and erase it, the search suggestions don’t disappear. 

### Expected behavior
Suggestions should disappear along with the characters you’ve entered.

### Actual behavior
Suggestions do not disappear, and are still there above the other suggestions/history/etc

![](https://user-images.githubusercontent.com/43795363/87478401-56a91a80-c5ef-11ea-9967-38ea38548d8b.png) ![](https://user-images.githubusercontent.com/43795363/87478447-67f22700-c5ef-11ea-8bb6-05215aab95b4.png)

### Device information
* Android device: Pixel 3, android 10
* Fenix version: Nightly

### What is the user problem or growth opportunity you want to see solved?
People expects the address bar to be fluid and responsive. This means that suggestions (search keywords, history, bookmarks, etc.) should be fetched as quickly as possible. And whenever any changes happen (e.g. add new letters, remove all letters.), suggestions should respond as quickly as possible.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Beta 80.0

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

Unassigning this since I will be on PTO for the rest of the week
