### ISSUE TITLE
FNX2-15340 ⁃ [Bug]Floating tabs tray overlay after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12585]
## Prerequisites
Have one open tab

## Steps to reproduce
1. Rotate the device to landscape view
1. Shrink the Tabs Tray
1. Tap the ⋮ "More options" button
1. Rotate the device to portrait view

### Expected behavior
Properly displayed overlay

### Actual behavior
Floating overlay

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly 200714 from 7/14 
• 79.0.0-beta.6 from 7/14

### Notes
► Video
![20200715-110541](https://user-images.githubusercontent.com/51314259/87523318-7728b180-c68f-11ea-8c07-c3919b5f57d8.gif)

**Comment by hakkikaancaliskan** [comment]
I'm unable to reproduce on my XZ1 Android 10 but we can save orientation `onViewCreate` and watch changes of orientation in `onConfigurationChanged`. Currently we're dismissing menu on portrait to landscape orientations.

**Comment by Mugurell** [comment]
Thank you @hakkikaancaliskan 
The proposed solution looks ok to me but I think we also need a greenlight from UX for the change.

**Comment by AmyYLee** [comment]
@topotropic for review

**Comment by topotropic** [comment]
ok, just to confirm, when you open the tab tray menu and then switch from portrait to landscape or vice versa we dismiss the menu, correct?

**Comment by hakkikaancaliskan** [comment]
> ok, just to confirm, when you open the tab tray menu and then switch from portrait to landscape or vice versa we dismiss the menu, correct?

Yep.

**Comment by topotropic** [comment]
thanks, sounds good to me!
