### ISSUE TITLE
FNX2-15342 ⁃ Allow removing apps from recent apps list on share sheet

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#12587]
Initially posted here: https://github.com/mozilla-mobile/fenix/issues/9332#issuecomment-603136441.
See: https://github.com/mozilla-mobile/fenix/issues/9332#issuecomment-658627920.

**Comment by cadeyrn** [comment]
Duplicate of #11566.

**Comment by kbrosnan** [comment]
Closing as a duplicate.
