### ISSUE TITLE
Synced tabs should hide or group pinned tabs

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/fenix#12584]
### What is the user problem or growth opportunity you want to see solved?
I would like the synced tabs menu to hide or group the pinned tabs on other devices.  This could group into a single "pinned tabs" menu selection which, when tapped, opens another pane for that device.

### How do you know that this problem exists today? Why is this important?
When searching through my synced tabs, more than half are pinned.  Usually I am looking for an unpinned tab and the pinned ones make it difficult to find since these are not alphabetized.

### Who will benefit from it?
Users with many pinned tabs on other devices, especially multiple devices, e.g., laptop, desktop, with duplicate mail, calendar, RSS, etc. tabs

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3480)

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
