### ISSUE TITLE
Support for desktop mode

### ISSUE THREAD

**Issue by jdelga2** [mozilla-mobile/fenix#12590]
### What is the user problem or growth opportunity you want to see solved?
I'm working in a project with a big customer, trying to use a Samsung mobile device as the only device for users. The idea is to use the mobile device as a PC connected to a screen, mouse and keyboard. Samsung provides a solution to this with DeX. The problem is that the user experience is bad when using Firefox for two reasons:

1. When in desktop mode, the browser still uses the mobile view, and we have to set manually the desktop view, and conversely, automatically activate mobile view when changing to mobile use (not connected to screen, keyboard and mouse)
1. The user agent identifies the device as mobile, and therefore web pages serve a mobile view even when working in desktop mode and activated the desktop view in firefox. Examples are G-Suite (GMail, Docs, Spreadsheets, ...), Salesforce, and many others

What we need is: 

* Automatically activate Desktop View when the device is in DeX mode, and deactivate it when disconnected
* Ensure the same desktop experience as windows, mac or linux, specially for G-Suite services (Gmail, Docs, Slides, Spreadsheets, Meet, …) GMail and other web services always use a mobile view, even when desktop mode activated, because Google sees the device as a mobile device, not a desktop device (identifying the device as a desktop with the user agent)
* Ensure this experience in new firefox versions

### How do you know that this problem exists today? Why is this important?
As I said, we are stuck in a project that could scalate to several thousand users, and that could be replicated to other big companies. 

### Who will benefit from it?
This could position firefox as the browser for this use case, as Google has refused to collaborate in this project, as their strategy is based on native apps instead of browser use of these services. Samsung is collaborating in this project, but they haven't been able to make google change this behaviour in Chrome.

And it could also enable this desktop use of mobile devices as the only device, removing pcs for these users.

**Comment by mkaply** [comment]
Information on how to modify your app for DeX:

https://developer.samsung.com/samsung-dex/modify-optimizing.html

**Comment by kbrosnan** [comment]
Duplicate #3107
