### ISSUE TITLE
Measure performance impact of initializing built-in extensions

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#12598]
We have quite a few built-in web extensions (ads, cookies, icons, fxa, reader view etc.). Let's measure the cost of initializing them on startup.

**Comment by bdekoz** [comment]
there seems to be a need for a top-level 'measure the performance impact of initializing X....' tracker

Also, for extensions (unlike experiments) there is no top-level config switch to do top-level on/off checks

**Comment by mcomella** [comment]
Triage: csadilek has previously done multiple web extension perf investigations and hasn't seen any problems though we might not have measured this explicitly. That being said, if this is a problem, we'll see it in the profiles as we work on improving start up (the current priority) so it doesn't seem that useful to measure it independently. Let's close this.
