### ISSUE TITLE
FNX-4910 ⁃ Remove out-of-scope issues from designs

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1260]
Remove the out of scope assets from the designs/mocks

* Downloads

From 

* Quick action bar
* Library UI

(needs to be confirmed)

**Comment by boek** [comment]
@bbinto should we be spending time actively removing them? Can't we just remove the stubs from the app?

**Comment by vesta0** [comment]
@boek this is a UX issue. Once UX has provided feedback we will size it and move it to a sprint.

**Comment by mheubusch** [comment]
Removed  Reader mode from note above since we should be able to get this for MVP (but not Reading List)

**Comment by kbrosnan** [comment]
All the items in the epic are done. Close it?
