### ISSUE TITLE
FNX2-15354 ⁃ [webcontent] [tab crash] Firefox Nightly crashes on http://www.tagesschau.de

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#12609]
## Site with issue and any steps to reproduce
www.tagesschau.de
Sometimes the tab crashes immediately, sometimes after an other link on that page. 

### Expected behavior
No tab crash

### Actual behavior
Tab crashes
Socorro: https://crash-stats.mozilla.org/report/index/57c97d3a-c929-4e9d-b533-0edd80200715

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
Nope

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Nope

### Can you reproduce in Chrome (or other non-Mozilla browser)?
Nope

### Device information
* Android device: Samsung Galaxy Tab A6 SM-T580 with Android 8.1.0 and Huawei P Smart with Android 9.1.0 
* Fenix version: latest nigthly

**Comment by Diana-Rus** [comment]
Hello we'll be closing this issue, but please follow #12605 .
Thank you for reporting!
