### ISSUE TITLE
Crash in [@ nsTextEquivUtils::ShouldIncludeInSubtreeCalculation]

### ISSUE THREAD

**Issue by Gaspacchio** [mozilla-mobile/fenix#12605]
## Steps to reproduce
* Open firefox nightly
* Go to https://www.presse-citron.net/une-souris-gaming-equipee-de-ventilateurs-pour-ne-pas-avoir-les-mains-moites/

### Expected behavior
The page should load successfully. 

### Actual behavior
Firefox crashes.

### Device information
* Android device: Samsung Galaxy S8 (Android 9)
* Fenix version: Nightly 200714 06:01 (Build #21960614)
* Crash ID: [76c8160a-ae87-47dd-8124-3f9300200715](https://crash-stats.mozilla.org/report/index/76c8160a-ae87-47dd-8124-3f9300200715)

**Comment by kbrosnan** [comment]
Please get a crash ID as described at https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by Gaspacchio** [comment]
There you go: https://crash-stats.mozilla.org/report/index/76c8160a-ae87-47dd-8124-3f9300200715

I'm editing the bug report as well.

**Comment by cadeyrn** [comment]
#12609 has the same crash signature (nsTextEquivUtils::ShouldIncludeInSubtreeCalculation).

**Comment by Diana-Rus** [comment]
Reproduced the issue with Samsung Galaxy S9 (Android 8) on latest Nightly 7/16.
Crash link: https://crash-stats.mozilla.org/report/index/e21cba0c-0328-4ca0-a97a-143f70200716
With Sony Xperia Z5 (Android 7) and Google Pixel 3 XL(Android 9) the crash is not reproducible with neither of the sites:
- https://www.presse-citron.net/une-souris-gaming-equipee-de-ventilateurs-pour-ne-pas-avoir-les-mains-moites/
- http://www.tagesschau.de/  (12609)

**Comment by kbrosnan** [comment]
Fixed by bz-1652215
