### ISSUE TITLE
[Bug] Leanplum event for installing addon gets tracked twice

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#12600]
It looks like we're sending/tracking the event when showing the permission dialog and also once the add-on is installed and the installation dialog is shown.

**Comment by sv-ohorvath** [comment]
@csadilek looking at the commits list, this appears to have landed on Beta 79.1.0. Could you please let us know if it needs QA? Thanks!

**Comment by csadilek** [comment]
@sv-ohorvath thanks, I think we can close this then.
