### ISSUE TITLE
FNX2-15356 ⁃ [l10n] Locale(s?) missing in language list

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#12613]
## Steps to reproduce
Latest Firefox Nightly > navigate to Preferences > Languages

### Expected behavior
Breton (br) should show up in the Laguage list (but doesn't). Not sure there are other locales missing either, since there are a lot.
Breton should appear there because it's both in our [Fenix](https://github.com/mozilla-l10n/android-l10n/blob/master/mozilla-mobile/fenix/l10n.toml) and [a-c](https://github.com/mozilla-l10n/android-l10n/blob/master/mozilla-mobile/android-components/l10n.toml) l10n.toml files.

I hope no other locales are affected, because the deadline for l10n is this Saturday July 18th, and people are still actively localizing and testing.

### Actual behavior
Breton doesn't show up.
Maybe other locales are affected as well, would be good to double check. All the locales present in the l10n.toml files for a-c and Fenix should appear on the Firefox Nightly language list.

### Device information
* Android device: Pixel 2, android version 10
* Fenix version: latest Nightly

**Comment by mcarare** [comment]
Tested with Pixels, Android 9 and 10, Brezhoneg / Breton is there.

**Comment by eliserichards** [comment]
I am unable to see it on my Pixel 3 with the latest master:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/87690143-ace09f80-c74e-11ea-812b-7f3330a8f9e0.png">

**Comment by Delphine** [comment]
I just updated to the latest Nightly, and now I'm seeing Breton (vs in yesterday's build).
Do we know why this is showing up for some but not others?
![Screenshot_20200716-095624](https://user-images.githubusercontent.com/399020/87700899-f085da00-c74b-11ea-8448-949efb122570.png)

**Comment by tornoz** [comment]
I am now also seeing the language but the translation is incomplete. I completed it last night at 10:30 pm cest. Is this just an expected delay for the translated strings showing up in the nightly build?

**Comment by eliserichards** [comment]
@tornoz There will be a delay (waiting for the bot that pulls the translations from Pontoon)

**Comment by eliserichards** [comment]
Let's followup with this tomorrow (or after the update lands) and verify that the new translations are there.

**Comment by eliserichards** [comment]
List of locales: https://docs.google.com/spreadsheets/d/1Z1N0a6KogjyUZQhTXFDca-0-YXBOl5Jr9xyE1fQHayE/edit#gid=0

**Comment by Delphine** [comment]
Just in case: it might be easier to look at the list of locales on pontoon here: https://pontoon.mozilla.org/projects/android-l10n/tags/fenix/
Every locale there should be on nightly - except the zero percent ones

**Comment by Delphine** [comment]
Both Uzbec (uz) and Kannada (kn) are also missing from Nightly builds.

**Comment by person808** [comment]
Went through and checked the locales. Uzbek, Kannada, and Breton are available now. I already checked the other locales here: https://github.com/mozilla-mobile/fenix/issues/7104#issuecomment-659646945
