### ISSUE TITLE
[Bug] Regression - Tab crash when pressing "Reply" box on 17thshard.com

### ISSUE THREAD

**Issue by BeeeWall** [mozilla-mobile/fenix#12614]
## Steps to reproduce
1. Go to any post on the 17th Shard forums, such as [this one](https://www.17thshard.com/forum/topic/89569-17s-forum-and-discord-policies/). 
1. Press the "reply" button at the bottom of the page. (Not sure if login is necessary to trigger the crash or not.)

### Expected behavior
It should open up the reply editor. 

### Actual behavior
The tab crashes. 

### Device information
* Android device: Samsung Galaxy S10e on Android 10
* Fenix version: Nightly 200714 06:01 (Build #21960614)

Issue started happening for me maybe a couple days ago, up until then it worked fine. I have not had this issue with Chrome or Fennec. 

Edit: I also tested it on the old Firefox Nightly app, which I still have installed with an older version of Fenix (Nightly 200706 06:01 (Build #2015750387)), and this does _not_ occur.

**Comment by kbrosnan** [comment]
Please add a crash ID from this crash. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by BeeeWall** [comment]
This actually appears to be fixed in the latest version, should I close this?

**Comment by kbrosnan** [comment]
Sounds good to close this. Thank you for filing an issue and updating the status.
