### ISSUE TITLE
Choppy animation on reveal/hide of menu

### ISSUE THREAD

**Issue by bull500** [mozilla-mobile/fenix#12611]
Visit html5test.com
Reveal the menu by clicking on the hamburger menu icon.

The reveal/hide animation should be smooth but it's quite choppy on my device redmi note 7s.
Android 9. Nightly 200714 06:01 (Build #21960614)

**Comment by eliserichards** [comment]
![html5test-animation](https://user-images.githubusercontent.com/43795363/87600075-6725c780-c6b9-11ea-884d-f0029d9bb8c8.gif)
