### ISSUE TITLE
Add a second access point to search shortcuts: search engine icon/logo

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#12619]
### What is the user problem or growth opportunity you want to see solved?
Some people may associate the act of “changing search engine” with the icon/logo of the search engine itself. If tapping the icon/logo does nothing, people may then assume that one-off search engines aren’t available.

This could still happen even if the “:mag: Shortcuts” button are clearly labelled. One hypothesis may be because the :mag: icon is less clearly understood as “the place to go to change my search engine”, when compared to the icon/logo of the search engine itself.

#### Search screen
Tapping on either the search engine icon/logo, or the arrowhead next to it, will show the search shortcuts interface.

![](https://user-images.githubusercontent.com/51007/87613548-b7586480-c761-11ea-9b4f-1f57434caa1c.png) ![](https://user-images.githubusercontent.com/51007/87613762-5f6e2d80-c762-11ea-82dd-51093ab21c79.png)

#### New Tab Page
The search engine icon/logo and the arrowhead are also tappable. When tapped, it will select the address bar, pop the keyboard up, and show the search shortcuts interface.

(Note: the arrowhead faces UP when the toolbar sits on the bottom; the arrowhead faces DOWN when the toolbar sits on top)

![](https://user-images.githubusercontent.com/51007/87613953-e3281a00-c762-11ea-8a93-f46a24c192fb.png) ![](https://user-images.githubusercontent.com/51007/87613762-5f6e2d80-c762-11ea-82dd-51093ab21c79.png)

**Comment by liuche** [comment]
Discussed this in backlog grooming. This would require some changes in AC to the homescreen toolbar and the edit toolbar:
- making icon clickable
- adding an arrow image (based on top/bottom)

(If we pick this up, we should start an RFC with AC to get input regarding effects on other consumers of AC Toolbar)

**Comment by brampitoyo** [comment]
Paging @violasong. When it’s time to implement your search engine selection access point, this was the issue that I originally filed. Perhaps we can just reuse and rename this issue?

**Comment by violasong** [comment]
Oh nice :). Betty and I actually decided to reuse [this issue](https://github.com/mozilla-mobile/fenix/issues/15357) for my work, so we can bring this over into that thread. It seems likely we'll be able to get this into the next sprint.

I'll close this as duped. Thanks for your work on this!
