### ISSUE TITLE
 When Fenix's "Open links in apps" preference is enabled and if user opens the specific links in a new tab then don't redirect it to the respective app and instead open it in the browser itself

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12626]
Currently if the "Open links in apps" is enabled there's no way to open the website links the browser if the users wants unless the user disable the "Open links in apps" completely in preferences. This will provide more flexibility to the "Open links in apps" preference. This is how Chrome browser handles it. 

Chrome browser behaviour; user clicks a website and Chrome browser opens it in the respective app (for example, Play Store). And if the user long presses the link and opens it in a new tab then the link gets opened in the Chrome browser and then the user can browse the website in the browser itself. 

The all or nothing approach that Fenix currently uses for "Open links in apps" is too strict and causes frustrations sometimes and this will definitely provide more flexibility and user choice to it. And maybe in the process reduce some user frustrations like https://github.com/mozilla-mobile/fenix/issues/12388, https://github.com/mozilla-mobile/fenix/issues/12480, #12631. :grinning:

Thank you! :grinning:

### Chrome browser's default behaviour when clicked on Play Store's links for example: 
![Chrome's  behaviour 1](https://user-images.githubusercontent.com/68282543/88074276-b7dc6b00-cb66-11ea-9722-01e2dd3fffc7.gif)

### Chrome's behaviour when the same Play Store's links are opened in a new tab. Observe that the link is not getting opened in the Play Store but instead getting opened in the browser itself and this is what this issue is asking about (to bring this feature/behaviour to Fenix):
![Chrome's behaviour 2](https://user-images.githubusercontent.com/68282543/88074542-13a6f400-cb67-11ea-8f97-6f9ae8ae3a09.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3528)

**Comment by ShatteredPixel** [comment]
CC @rocketsroger

**Comment by ShatteredPixel** [comment]
@eliserichards May know the reason for changing the title? 

...And "*it's not a bug it's a feature request** and the title changes the _entire_ purpose and meaning of the feature I'm asking. This is the reason I always say developers to communicate with their users. I don't want to revert the title unless knowing your reasons behind it; Was I not clear? sorry if it confused you. Please ask me and I'll clear it for you. 

Thanks. :) And sorry if it caused confusions.

**Comment by rocketsroger** [comment]
After investigation.  This was caused by the recent change of allowing redirect URL to trigger to 3rd party application.  Since when user enters "youtube.com", we get 2 redirects before arriving to the destined URL. 
"youtube.com" -> "www.youtube.com" -> "m.youtube.com".

I'll have to update how domains are checked to see if we're in the same domain.  I'll update the title to reflect the investigation results.

**Comment by ShatteredPixel** [comment]
@rocketsroger I think there's a bit of confusion here, the issue you're taking about here is here: https://github.com/mozilla-mobile/fenix/issues/12670 . 

And this issue (#12626) is a feature request. 


The QA also changed this issue's title. I think I'll need to add videos and GIFs explaining the behaviour I'm asking in this issue

**Comment by rocketsroger** [comment]
> @rocketsroger I think there's a bit of confusion here, the issue you're taking about here is here: #12670 .

Oh you're right.  What I found is more applicable to https://github.com/mozilla-mobile/fenix/issues/12670.  I'll restore the title of this.  Thanks for letting me know

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809260

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
