### ISSUE TITLE
FNX-13725 ⁃ [Bug] (regression) Can't download from blob url anymore

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12628]
* [ ] AC issue tracking this https://github.com/mozilla-mobile/android-components/issues/7757

This was once fixed in https://github.com/mozilla-mobile/fenix/issues/2579 but now I can reproduce this again.

## Steps to reproduce
1. Download file from https://github.com/mozilla-mobile/fenix/issues/2579#issuecomment-535981773
1. Download an image from https://squoosh.app/
1. Open https://kinoseed.com/ and install as PWA. Start the PWA, load a target image, press "save".
    1. Expected behavior
Files are downloaded.
    1. Actual behavior
Nothing happens, not even an error message.
    1. Device information

* Android device: Pixel 4 (Android 10), Huawei P20 (Android 9)
* Fenix version: Nightly 7/14

**Comment by Amejia481** [comment]
This is addressed on https://github.com/mozilla-mobile/android-components/pull/7758#event-3559067333, it will be fixed when Fenix update to the respective ac version.

**Comment by Amejia481** [comment]
I tested on the latest nightly and it's working for me. QA please help us to verify :) 

```
Nightly 200721 13:47 (Build #22031352)
AC: 51.0.20200720130437, 82bcabef4
GV: 80.0a1-20200719090414
AS: 61.0.10
Tuesday 7/21 @ 1:51 PM
```

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 7/24 on a Pixel 4(Android 10).
