### ISSUE TITLE
FNX2-15365 ⁃ Visually indicate different types of suggestions in the search screen

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#12622]
### What is the user problem or growth opportunity you want to see solved?
People forget that the things they want to access are already stored somewhere (e.g. in open tabs, history, bookmarks), so they would search for the same information and reopen it many times.

By visually indicating different types of suggestions as they appear on the search screen based on their sources, people can more quickly identify, find, and re-access items in their library.

### Strawman mockup
Note: the visual design of these indicators isn’t final.

![](https://user-images.githubusercontent.com/51007/87630521-62c8df80-c789-11ea-91ef-58ccb8dcf2a9.png)

#### Dark theme
* [search results bookmarks](https://share.getcloudapp.com/E0uz0gJ6)
* [search results tab](https://share.getcloudapp.com/7KumKQnR)
* [search results device desktop](https://share.getcloudapp.com/z8u8eLBP)
* [search results device mobile](https://share.getcloudapp.com/Z4uY072r)
* [search results device tablet](https://share.getcloudapp.com/v1uewgBP)

#### Light theme
* Replace bookmark icon colour `#0090ed` with `#0060df`
* Replace tab and device icon colours `#2ac3a2` with `#008787`
* Replace outline foundation colour `#1c1b22` with `#f9f9fb`

#### Private theme
* All icon colours stay the same
* Replace outline foundation colour `#1c1b22` with `#1d1133`

### Specs
The search results icons should be offset from the site favicon by 10dp.

![](https://user-images.githubusercontent.com/51007/88018053-0ac01d80-cb7b-11ea-8b1b-da6917825b2f.png)

**Comment by hakkikaancaliskan** [comment]
Also search results and icons not aligned

<img src="https://user-images.githubusercontent.com/17825767/87662331-b4ae3d00-c76a-11ea-9c56-64a6c6736718.png" width="800">

**Comment by hakkikaancaliskan** [comment]
@brampitoyo Looks like I've managed to do a little bit. Could you send that icons?

**Comment by brampitoyo** [comment]
@hakkikaancaliskan I wrote that I don’t yet have the final assets. For now, I am just using the same asset that Firefox for Desktop uses. I even kept the size identical to desktop: 16x16.

Do you think you’d be able to grab those assets from desktop, to use for now?

**Comment by hakkikaancaliskan** [comment]
> @hakkikaancaliskan I wrote that I don’t yet have the final assets. For now, I am just using the same asset that Firefox for Desktop uses. I even kept the size identical to desktop: 16x16.
> 
> Do you think you’d be able to grab those assets from desktop, to use for now?

Idk where is the source of Firefox for desktop and not sure i can find them. Could someone know that send this icons?
@brampitoyo of course we could wait pr until you prepare the icons. That's not something urgent.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan I’ve posted some assets to use, along with measurements. They might change later, but they should allow you to work and test the issue – and they work across themes if you colourise the SVG files.

**Comment by hakkikaancaliskan** [comment]
@NotWoods qa needed

**Comment by softvision-miralobontiu** [comment]
Hi all,

I've tested on the latest Nightly build from 8/4. I've connected 4 devices, and the desktop with the same account. Had opened tabs on all, containing the term I was looking for (i.e. "nutella"), and a bookmarked page with that term.

* I only had one suggestion indicator (bookmark) displayed on OnePlus 5T (Android 9), Samsung Galaxy Tab S6 (Android 9), and Google Pixel (Android 10):
<img src="https://user-images.githubusercontent.com/40694158/89395519-1c2a2d80-d716-11ea-832c-c74910ebea9e.png" width="300" height="550" />  

* Only on Sony Xperia Z5 Premium (Android 7.1.1), there were 2 indicators (bookmark, and opened tab):
<img src="https://user-images.githubusercontent.com/40694158/89395092-8ababb80-d715-11ea-978d-ac0e957c49dc.png" width="300" height="550" />  

I will remove the qa:needed label until further notice,

**Comment by hakkikaancaliskan** [comment]
> Hi all,
> 
> I've tested on the latest Nightly build from 8/4. I've connected 4 devices, and the desktop with the same account. Had opened tabs on all, containing the term I was looking for (i.e. "nutella"), and a bookmarked page with that term.
> 
> * I only had one suggestion indicator (bookmark) displayed on OnePlus 5T (Android 9), Samsung Galaxy Tab S6 (Android 9), and Google Pixel (Android 10):
> <img src="https://user-images.githubusercontent.com/40694158/89395519-1c2a2d80-d716-11ea-832c-c74910ebea9e.png" width="300" height="550" />  
> 
> * Only on Sony Xperia Z5 Premium (Android 7.1.1), there were 2 indicators (bookmark, and opened tab):
> <img src="https://user-images.githubusercontent.com/40694158/89395092-8ababb80-d715-11ea-978d-ac0e957c49dc.png" width="300" height="550" />  
> 
> I will remove the qa:needed label until further notice,
> 
> 

This issue and pr just adds icon to search suggestions and doesn't remove or add any suggestion. There is no problem with this pr. We need to investigate why that search suggestion not shown.
@NotWoods what should we do?

**Comment by hwinnemoe** [comment]
> We need to investigate why that search suggestion not shown.

@hakkikaancaliskan That sounds like #12852.

**Comment by NotWoods** [comment]
I'll close this issue as the visual indicators are done, and other issues can track related suggestions work.

**Comment by softvision-miralobontiu** [comment]
I'll re-close this issue, and remove the qa:needed label, since this was re-opened by data-sync.
