### ISSUE TITLE
[Bug] Last Synced time changes but bookmarks not synced

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12625]
## Steps to reproduce
* If internet is off, and `Sync Now` option is pressed, the app crashes. - Moved to https://github.com/mozilla-mobile/fenix/issues/12644
* If internet is on, and `Sync Now` option is pressed, the `Last Synced` time changes to current time, but no bookmarks are synced. 

```
07-17 12:42:17.258 28856 28971 D sync15::sync_multiple: sync was successful, final status=Ok
07-17 12:42:17.258 28856 28971 I sync_manager::manager: Sync finished with status Ok
07-17 12:42:17.258 28856 28971 I sync_manager::manager: engine "bookmarks" status: Err(Error(Store error: Error executing SQL: FOREIGN KEY constraint failed))
07-17 12:42:17.258 28856 28971 I sync_manager::manager: engine "passwords" status: Ok(())
```

* Syncing used to work fine in the previous build.

### Device information
* Android device: Android 8
* Fenix version: Build 21960614

**Comment by eliserichards** [comment]
We will need to improve error reporting when there is no internet connection. 

If the `Last synced` time is updating and the bookmarks aren't synced (assuming your sync settings in Fenix are set to sync them), there should be some sort of exception being caught and not propagated to the user. Do you see anything in the logs?
<img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/87711590-17083d00-c76d-11ea-96b1-3aca32a219d5.png">

**Comment by grigoryk** [comment]
Well it certainly shouldn't crash, so let's deal with that first. Tracking in https://github.com/mozilla-mobile/android-components/issues/7748

Regarding error reporting - a lot of sync errors aren't actionable by the user, and mostly just require to "try again". Some (like network connection dropping) are actionable, yes. Currently we have no UX for displaying these errors. In Fennec we had _some_ error reporting UX, and it was always kind of a hit and miss. It's hard to strike a balance between useful and non-anxiety-inducing when it comes to these errors.

Regarding the timestamp - most sensible behaviour would be to update it only if _all_ configured engines succeeded. I'm not sure if that's what we're doing though, will double check.

**Comment by sheepycoder** [comment]
@eliserichards @grigoryk 
I think this is the relevant portion of error from the logs -
```
07-17 12:42:17.258 28856 28971 D sync15::sync_multiple: sync was successful, final status=Ok
07-17 12:42:17.258 28856 28971 I sync_manager::manager: Sync finished with status Ok
07-17 12:42:17.258 28856 28971 I sync_manager::manager: engine "bookmarks" status: Err(Error(Store error: Error executing SQL: FOREIGN KEY constraint failed))
07-17 12:42:17.258 28856 28971 I sync_manager::manager: engine "passwords" status: Ok(())
```

**Comment by sheepycoder** [comment]
I cleared all data of the application, and now syncing bookmarks works fine. So most likely some other bug caused the local database to get corrupted which caused this issue.
