### ISSUE TITLE
[Bug] Fenix's "Open links in app" preference is not respecting the Android's "Open by default" preference.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12624]
## Steps to reproduce
Have the Fenix's "Open links in apps" enabled.

1. Install [LiveChart.me](https://play.google.com/store/apps/details?id=me.livechart.android).
1. Set the behaviour of the 'open in app' by going to its' App info' page "Open by default" > Open supported links > Ask every time
1. Now search in Google search, type "Fruits Basket livechart.me" then click one of the Livechart.me's search results listings.
1. Notice that it take to the app instead of asking whether to open in app or not.

Chrome browser asks if the links should be opened in app or the Chrome browser when the Chrome browser is set as the default browser

See the screenshots.

This can also be reproduced in [GitHub app](https://play.google.com/store/apps/details?id=com.github.android); search for a repository like for example typing "Fenix GitHub repo" and click one of the links leading to it. I observe that Fenix opens then in the GitHub app.

This should be reproducible with any app that has Android's "Open by default" setting.

**Note:** On the current `Nightly 200714 18:01` the links are opening in the websites even if the Fenix's "Open links in app" setting is enabled.

### Expected behavior
Fenix should respect Android system's behaviour of opening links in app

### Actual behavior
Fenix doesn't respect Android system's behaviour of opening links in app

### Device information
* Android device: Motorola One Power, Android 10
* Fenix version: Fennec migration build `null (Build #2015749827)
AC: 48.0.3, ce6247fb8
GV: 79.0-20200629163142
AS: 61.0.7` 

![Screenshot](https://user-images.githubusercontent.com/68282543/87641084-41ee9300-c765-11ea-897b-b1899ef5d34a.png)UNITO-UNDERSCORE!20200716-130609.png!
![Screenshot](https://user-images.githubusercontent.com/68282543/87640042-c213f900-c763-11ea-96ee-a4e2f7898c66.png)UNITO-UNDERSCORE!20200716-125543.png!

**Comment by ShatteredPixel** [comment]
CC @rocketsroger
