### ISSUE TITLE
[Bug] Fenix opens on flashing home screen (with no collection) before displaying collections

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#12629]
## Steps to reproduce
Set up some collections
Close Fenix completely
Open Fenix

### Expected behavior
The home screen is displayed immediately

### Actual behavior
An empty home screen with no collection is displayed in a flash before the expected home screen

See video here: https://photos.app.goo.gl/jD73nHKNQrui5xjW7

### Device information
* Android device: Redmi Note 7 Android 9
* Fenix version: #21960614

**Comment by ShatteredPixel** [comment]
Might be related to the bug I reported:  https://github.com/mozilla-mobile/fenix/issues/12284 

Can you check?

**Comment by klint** [comment]
> 
> 
> Might be related to the bug I reported: #12284
> 
> Can you check?

Hi. Yes, that would make sense. Yet, I just have checked and I just suffer from this bug here, as far as I can see. But both look consistent all the same.

**Comment by eliserichards** [comment]
I created a "meta" bug for this and referenced both issues :) #12642

**Comment by klint** [comment]
@kbrosnan is the issue solved? I'm asking because the issue is closed and it is still there in the latest nightly. :) Thanks

**Comment by cadeyrn** [comment]
See https://github.com/mozilla-mobile/fenix/issues/12629#issuecomment-659605494 - it's covered by #12642 and it's still open. This issue was accidentally reopened by the data-sync-user bot and that's why it was closed again.
