### ISSUE TITLE
When URLs autocomplete to a supported search engine, allow users to switch to it

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#12620]
### What is the user problem or growth opportunity you want to see solved?
Some people are used to visiting search engine sites by manually entering URLs into the address bar. Fenix provides a way to select these search engine shortcuts quickly and efficiently. Recent issues I’ve filed have explored multiple ways to make these shortcuts more discoverable and easier to access.

However, many people will type and wait for autocomplete to show something.

> I want to search Amazon.
> 
> Let's type ‘a’ — ‘m’ —

There are two paths to move forward from this point:

1. Tap “Enter” and follow the autocomplete suggestion. It will proceed straight to Amazon.
1. Wait for keyword suggestions to show up and then choose one.

If path 2 is a common scenario for many people, then they may not realise that Amazon is a search option.

In this “waiting for suggestions” moment, we should offer users the option to switch their search engine to Amazon.

#### Before tapping
* Label: Search with [engine_name]
* Placement: Below the first search suggestion
* Trigger condition: only appears IF URL autocompletes to a known search engine.

![](https://user-images.githubusercontent.com/51007/87617410-8aa94a80-c76b-11ea-9475-e363e3403e83.png)

#### After tapping
* Search engine changes
* Search screen starts back up from zero (ie. as if nothing has been entered into the address bar)

![](https://user-images.githubusercontent.com/51007/87617515-c217f700-c76b-11ea-80df-5de62a09e548.png)

**Comment by liuche** [comment]
UX question: do users actually search through this new interface, or does it just clutter the UI?

(If users type google, also follow this pattern even if it's the default search engine)

Bram says it would be useful to run this as a 50/50 test, and we'll want to compare clicks between the two versions.

This would have to be in AC though, and either allowing a flag to determine which to show, or doing the experiment in AC?

**Comment by liuche** [comment]
These changes would primarily be in AC:
- will need to support both autocomplete and typed text
- will need to add it into the search suggestions list at the top
