### ISSUE TITLE
Add "Always Ask" option to "Open link in apps"

### ISSUE THREAD

**Issue by xmine64** [mozilla-mobile/fenix#12631]
### What is the user problem or growth opportunity you want to see solved?
Sometimes I like to open some links in apps, sometime I don't, it depends on the app and the situation. For exaple I would open play store links in the app, but I don't want to open github repos in the app. I'm lazy to enable/disable the option each time, also I don't want to load web version of some apps, then press open in app option from menu.

### How do you know that this problem exists today? Why is this important?
It's something I need. Also you can't login to github app, if you set firefox as default browser and enable open in app option, because github opens firefox to login, then firefox opens github app automatically. If it asks it will be good. Also it's a privacy problem to open an app automatically.

### Who will benefit from it?
Everyone.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3537)

**Comment by ShatteredPixel** [comment]
@mmdmine 

I have filed this issue https://github.com/mozilla-mobile/fenix/issues/12480. Do you think that will solve the problems you are mentioning. Or do you have a better idea?

**Comment by mmdmine** [comment]
> @mmdmine 
> 
> I have filed this issue https://github.com/mozilla-mobile/fenix/issues/12480. Do you think that will solve the problems you are mentioning. Or do you have a better idea?

Hey. This is different issue. 302 moved means that the page is opened in the app. I would firefox ask me before opening the app.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809262

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
