### ISSUE TITLE
FNX2-15373 ⁃ [Bug] Edit toolbar string and search suggestion text not aligned

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12632]
![Screenshot](https://user-images.githubusercontent.com/17825767/87668158-4a01ff00-c774-11ea-9509-7d19c4d13968.png)UNITO-UNDERSCORE!20200716-134537!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

**Comment by eliserichards** [comment]
Closing in favor of #12622

**Comment by hakkikaancaliskan** [comment]
@eliserichards that issue is about to adding indicator to search suggestions, not alignment. Why is this closed?
