### ISSUE TITLE
RFP timezone spoof broken

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [mozilla-mobile/fenix#12638]
## Steps to reproduce
* don't **actually** be in timezone `UTC 0`
* enable RFP (`privacy.resistFingerprinting` = `true`)
* load TZP ( https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#language )
* expand `show details`

### Expected behavior
* timezone results should be sets of `0 | 0` and `UTC`
* relevant date/times displayed should use `Coordinated Universal Time` or `GMT` (or your locale equivalent)

### Actual behavior
* results are not spoofed, instead they reveal your real timezone

### Device information
* Android device: Samsung Galaxy A30
* Fenix version: at least since `2020 07 11 092223`

### Other
I didn't do any regression testing but pretty sure this is the ticket : [1534160](https://bugzilla.mozilla.org/show_bug.cgi?id=1534160)

@tomrittervg

**Comment by kbrosnan** [comment]
Opened bz-1653333

**Comment by kbrosnan** [comment]
This is fixed on nightly and will make its way through the trains on the Gecko 80 release.
