### ISSUE TITLE
[Bug] Unable to install Profiler add-on

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#12635]
## Steps to reproduce
1. Navigate to https://profiler.firefox.com/
1. Tap "Install add-on" button.
1. Observe behavior.

### Expected behavior
Add-on is installed.

### Actual behavior
Nothing happens, add-on is not installed.

### Device information
* Android device: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density), Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density)
* Fenix version: Firefox Nightly 200714 (:lizard: 80.0a1-20200711092223)

### Notes:
1. Screenshot attached.
1. The issue is not reproducible on Firefox Release 68.10.1

<details>
      <summary>View the screenshot</summary>
      ![](https://webcompat.com/uploads/2020/7/a37f1ebd-b9e2-47d6-8e9b-85829deb220b.jpg)
</details>

**Comment by eliserichards** [comment]
@mcomella I wasn't sure if perf-impact is the correct label here 🤔

**Comment by julienw** [comment]
We don't support using the profiler directly in Fenix, instead we support remote profiling. But we should detect this case and display some better documentation. This is a Firefox Profiler bug, I filed a bug in https://github.com/firefox-devtools/profiler/issues/2654. I believe you can close this one :-)

**Comment by softvision-oana-arbuzov** [comment]
Closing as duplicate of https://github.com/firefox-devtools/profiler/issues/2654
