### ISSUE TITLE
[Bug] Decentraleyes addon shows extra number in brackets

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#12648]
## Steps to reproduce
Have Decentraleyes installed and visit a website where it comes in use.

### Expected behavior
Decentraleyes would show just a coloured number like uBlock Origin and Privacy Badger do.

### Actual behavior
I can see both the coloured number and the number in brackets. This is now unneeded.

On websites with zero intercepted requests, it still shows (0), and no coloured number.

Fenix version: Nightly 200716 18:06 (Build #21981810)

**Comment by eliserichards** [comment]
Is this an addon? @opusforlife2

**Comment by opusforlife2** [comment]
Yes.

**Comment by hakkikaancaliskan** [comment]
https://github.com/mozilla-mobile/fenix/issues/12845#issuecomment-663272360

While I've been debugging i saw that they're not using badge, instead they're writing to next to they're extension name.

**Comment by opusforlife2** [comment]
@hakkikaancaliskan This was the regular behaviour in Fennec. uBO, Privacy Badger, Decentraleyes, all used to have the number as text next to their names. uBO and PB have updated to use badges, Decentraleyes hasn't, yet.

**Comment by hakkikaancaliskan** [comment]
> @hakkikaancaliskan This was the regular behaviour in Fennec. uBO, Privacy Badger, Decentraleyes, all used to have the number as text next to their names. uBO and PB have updated to use badges, Decentraleyes hasn't, yet.

Yep, i saw that in their codebase.
https://git.synz.io/Synzvato/decentraleyes/-/blob/master/core/state-manager.js#L40

**Comment by hakkikaancaliskan** [comment]
@opusforlife2 see https://github.com/mozilla-mobile/fenix/issues/12845#issuecomment-663272360

**Comment by opusforlife2** [comment]
This was fixed by a Decentraleyes update quite a while ago.
