### ISSUE TITLE
FNX-4913 ⁃ Remove "crash reporting" under data choices

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1264]
We should remove "crash reporting" settings under data choices as we will just ask the users with a checkbox.

**Comment by sblatz** [comment]
See [here](https://github.com/mozilla-mobile/fenix/issues/1003#issuecomment-478106992) for more explanation.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on Fenix version 1.0.1916 (Build#11081206), with Samsung Galaxy Tab S3 (Android 8.0), and Motorola Nexus 6 (Android 7.1.1).
