### ISSUE TITLE
[Bug] search_shortcuts.selected metric is missing data review

### ISSUE THREAD

**Issue by mdboom** [mozilla-mobile/fenix#12650]
The `search_shortcuts.selected` metric links to https://github.com/mozilla-mobile/fenix/pull/1202#issuecomment-476870449 as its data review, but that issue contains a data review _request_, but there doesn't seem to be a data review approval there.  I think it's quite possible it exists somewhere, it just fell through the cracks.

(I didn't find this to be a busy-body :wink: ...  I'm actually writing a data review scraper [over here](https://github.com/mozilla/glean_parser/pull/199) that caught this...)

**Comment by eliserichards** [comment]
Let's disable this, and re-add with an approved review
