### ISSUE TITLE
FNX-13760 ⁃ [Feature Request] Sync Collection too

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#12658]
I want to use my collection in other device with fenix. But I can't sync collection. Please add that to sync too.

**Comment by ShatteredPixel** [comment]
Thanks for filing the issue, this has already been asked here: https://github.com/mozilla-mobile/fenix/issues/6512 

Thanks.

**Comment by RealGJ** [comment]
@ShatteredPixel ok. Thanks bro. Closing now!!
