### ISSUE TITLE
FNX2-15395 ⁃ Support installation of extensions that haven't yet been officially recommended on nightly

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#12655]
### What is the user problem or growth opportunity you want to see solved?
There are many webextensions that only depend on the webextension APIs that Mozilla has already implemented in Fenix, but they're currently unable able to be used because Mozilla hasn't chosen to bless them with the "Recommended" status yet.

Developers of extensions may also want to test their extensions to see what functionality is currently working.

### How do you know that this problem exists today? Why is this important?
I am unable to install extensions with the Fenix app other than the handful that have been blessed by Mozilla.

I even tried following the needlessly complicated workaround of using USB debugging [1], but that just results in the addon being installed but disabled with the message "Not yet available".

### Who will benefit from it?
Extension developers and app power users.

[1] https://github.com/mozilla-mobile/fenix/issues/5315#issuecomment-592082109

**Comment by ShatteredPixel** [comment]
There's a bit of discussion going on at the isssue: https://github.com/mozilla-mobile/fenix/issues/11308, unfortunately Mozilla is not letting us install add-ons even if the supported APIs are available on the stable channel. like for example I want to install [Nano Adblocker ](https://addons.mozilla.org/en-US/firefox/addon/nano-adblocker-firefox/) but cannot even if it is still based on [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) which is already supported!

So we only have a choice to install whatever they want or nothing. That's direction how it seems it is going. 


And here I'm wondering what about the [Mozilla Manifesto Principles](https://www.mozilla.org/en-US/about/manifesto/). :)

**Comment by kamran-12** [comment]
This is probably the main problem with Firefox Nightly right now. The classic Firefox for Android supports such extensions.

**Comment by creesch** [comment]
Some more unfortunate context can be found in #5315. This has been requested multiple times and technically it is perfectly feasible to install other extensions as the development tools do allow to do so temporarily. So to me it seems to be a deliberate choice to not allow it at all. Combined with their responses in my linked issue I don't have high hopes as the best I could get was a "we are looking into it in some capacity".

**Comment by robsmith11** [comment]
It really doesn't make any sense why an open source non-profit organization would prevent their users from doing something they want with no real downsides.

The only explanation of which I can think is some nefarious reason tied to Google's continued funding, but that seems like a stretch.

**Comment by liuche** [comment]
Duping to #11308

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/12655
https://github.com/mozilla-mobile/fenix/issues/13059
https://github.com/mozilla-mobile/fenix/issues/14339
https://github.com/mozilla-mobile/fenix/issues/14452
https://github.com/mozilla-mobile/fenix/issues/14489
https://github.com/mozilla-mobile/fenix/issues/15154
