### ISSUE TITLE
FNX2-15396 ⁃ [Request] Swap the position of "Mic/voice" icon and the "x" icon in address bar

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12656]
**Please read everything that I have to say including the comments I'm adding below otherwise you might miss the whole context as I'm making 2 seperate issues for this "Voice" and "x" button and making 2 seperate argument on why this behaviour should other way around. Thanks. :grinning:**

Swap the buttons for "Mic/voice" and the "x" mark for clearing the typed text in the Fenix's address bar

Right now the place of the mic icon for voice typing is weirdly placed behind the "x" button for typed text (please see the screenshot if you not sure what I am talking about) in the Fenix's address bar. And I think the placement of it is not "standard" if you see other Android apps and this makes it not intuitive to the users of Fenix.

**_Fenix UI for voice/mic button_**:

![](https://user-images.githubusercontent.com/68282543/87748281-11653280-c813-11ea-86cd-8e5ccb62172b.jpg)

**_And placement of voice/mic button for various other apps;_**

Google Search app:
![](https://user-images.githubusercontent.com/68282543/87748354-48d3df00-c813-11ea-8f2a-cb58205a7b41.jpg)

Play Store:
![](https://user-images.githubusercontent.com/68282543/87748372-5721fb00-c813-11ea-85db-6cb996c68d91.jpg)

Gmail: 
![](https://user-images.githubusercontent.com/68282543/87748391-63a65380-c813-11ea-9d75-e923c6961a35.jpg)

Google Maps: 
![](https://user-images.githubusercontent.com/68282543/87748445-82a4e580-c813-11ea-9bcc-7d4477da96d7.jpg)

WhatsApp:
![](https://user-images.githubusercontent.com/68282543/87748470-918b9800-c813-11ea-993f-3f24464d1b58.jpg)

Spotify's action button for camera (not the voice button but you are getting the idea, right?):
![](https://user-images.githubusercontent.com/68282543/87748487-9bad9680-c813-11ea-80f8-68b9af48aa12.jpg)

And even the Gboard itself:
![](https://user-images.githubusercontent.com/68282543/87748514-b122c080-c813-11ea-88e5-450c1d9cb033.jpg)

**Or** you could make the both button for mic/voice and "x" icon for clearing the typed text dynamically appear and disappear based on the context of if the user is typing or doing something else like how other Google apps like Play Store, Chrome Browser, Google Maps. I am going to file an issue for that in a moment and link to it here. **Update:** Here's the issue for it #12657. 

**I actually am not in support of this (swapping icons of voice and "x" icon in the address bar) behavior and I strongly suggest to make the behavior like how Chrome browser does.** And here's the issue for it: #12657.
Below is the comment explaining why there should be only one button while typing sometimes in the address bar: https://github.com/mozilla-mobile/fenix/issues/12656#issuecomment-660396395

Thanks! :grinning:

**Comment by eliserichards** [comment]
@ShatteredPixel do you have any examples that include both the text clearing X and the mic? I don't see that functionality on any of these screenshots. 

Tagging UX for thoughts.

**Comment by hakkikaancaliskan** [comment]
> @ShatteredPixel do you have any examples that include both the text clearing X and the mic? I don't see that functionality on any of these screenshots. 
> 
> Tagging UX for thoughts.

For example chrome, showing mic icon when nothing typed in url bar and if user starts to writing, hiding mic icon and shows clear icon at there.
I think that's the best way.

**Comment by ShatteredPixel** [comment]
> @ShatteredPixel do you have any examples that include both the text clearing X and the mic? I don't see that functionality on any of these screenshots.
> 
> Tagging UX for thoughts.

@eliserichards No, I do not have them (the only app I have seen place the voice button in the middle is on Google Maps but that too disappears as soon as I touch the search bar) and if any of the apps do this then it'll become harder to press the "X" icon to clear the typed text and users may end up clicking the voice button instead or they may even end up clicking the "X" icon accidently when trying to click the voice button.

There should be only one button in the address bar as I have already suggested in the issue #12657. I strongly suggest to go with dynamically making the button appear and disappear based on the context.

Thank you! :)

**Comment by AmyYLee** [comment]
@brampitoyo for feedback

**Comment by brampitoyo** [comment]
@ShatteredPixel I’ve made a suggestion on #12657 that agreed with your recommendation. The Mic button should appear and disappear based on whether a character has been typed into the address bar.

By solving that problem, we no longer need to swap the position of Mic and Clear/x icons – we can therefore close this issue in favour of implementing #127657 

Thanks for your proposal!
