### ISSUE TITLE
[Bug] Close private tabs from lock-screen while media is playing leaves an empty notification

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12668]
## Steps to reproduce
1. Play some media in a private tab. (not youtube because the video will stop)
1. Lock the device screen.
1. On the lock-screen, you'll have a media notification and the "close private tabs" notification.
1. Double tap on the close private tabs notification.
1. Observe the notification tray.
    1. Expected behavior
The media notification should be dismissed.
    1. Actual behavior
An empty Firefox notification is still shown.
    1. Device information

* Android device: Nexus 9 (Android 7.1.1), Pixel 4 (Android 10)
* Fenix version: 79.0-beta 8, Nightly 7/17

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 84.0.0-beta.4 from 12/8 with Motorola Moto G6 (Android 8).
