### ISSUE TITLE
Add-ons sub-menu overlay should not disappear after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12661]
## Steps to reproduce
1. Open a website and tap the  ⋮ Main menu button
1. Tap on Add-ons
1. Rotate the device to landscape view

### Expected behavior
The overlay should remain displayed

### Actual behavior
The overlay disappears after rotating the device to landscape view 

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Nightly 200717 from 7/17
•79 beta.8 from 7/17

### Notes
► Video
![20200717-122352](https://user-images.githubusercontent.com/51314259/87771585-3f557180-c829-11ea-9264-2824518f02c3.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3578)

**Comment by eliserichards** [comment]
Changing this to a feature request since this functionality is intentional in the current version.

**Comment by AndiAJ** [comment]
Hi @eliserichards , As I recall, the main menu was never dismissed on rotation. 

Made it float with a different STR:
1. Open a website and tap the ⋮ Main menu button
2. Rotate the device to landscape view
3. Tap the Add-ons button
4. Rotate the device to portrait mode

![20200720-111050](https://user-images.githubusercontent.com/51314259/87915815-4b387200-ca7b-11ea-9e2a-da9bb2a5e98c.gif)

Please review and share your thoughts ☺️

**Comment by AmyYLee** [comment]
@brampitoyo for feedback

**Comment by brampitoyo** [comment]
@AndiAJ @eliserichards Hi. I don’t think Android is explicit about whether main menu should be dismissed or preserved during device rotation.

Google’s own apps aren’t consistent. Sometimes menus are dismissed, and sometimes they’re kept open.

I would recommend keeping all our menus open during rotation. This includes the Add-ons submenu.

When we rotate the device, let’s remember to keep the menu positioning, so they’re always consistent against the side of the screen where the menu icon is located. This means that the menu is default-positioned on the bottom-right hand corner on toolbar-bottom, top-right corner on toolbar-top, and will shift to the left corners if the user changes to an RTL language.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809232

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
