### ISSUE TITLE
[Bug] Keyboard leaves behind black area

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12679]
## Steps to reproduce
* Minimize keyboard

### Expected behavior 
Keyboard does not leave behind black area.

### Actual behavior
Black area appears and persists even when switching tabs (see comment below)

![IMG](https://user-images.githubusercontent.com/67375302/87827157-e83ab580-c897-11ea-9239-72e3e6342bb7.jpg)UNITO-UNDERSCORE!20200718!UNITO-UNDERSCORE!014043!

### Device information
* Android : 8
* Fenix version: Latest nightly
* Keyboard app: Fleksy 

Since, I have no idea how to reproduce the issue, so if the devs don't have any idea regarding this either, feel free to close the issue.

**Comment by eliserichards** [comment]
@sheepycoder did you minimize the keyboard right before this happened? or did you navigate to this page and see it there?

**Comment by sheepycoder** [comment]
@eliserichards I minimized the keyboard after I finished typing. However this black screen persisted even on tab change. Minimizing and reopening the browser from recent activities screen fixed it.
