### ISSUE TITLE
[Bug] Different behaviour when opening bookmarks

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12671]
Inconsistent behavior when opening bookmarks.

### Unselected - opens tab
1. Open a bookmark folder (do not select a bookmark)
1. Select three-dot menu on the right side of the bookmark
1. Open in tab
1. Opens in a tab, tab tray not shown

**Video:**
[1.zip](https://github.com/mozilla-mobile/fenix/files/4938351/1.zip)

### Multiselect - opens tab tray
1. Multi-select bookmark
1. Select three-dot menu in toolbar
1. Open in tab
1. Opens in tab tray and shows tab tray

**Video:**
[2.zip](https://github.com/mozilla-mobile/fenix/files/4938349/2.zip)

Considering https://github.com/mozilla-mobile/fenix/issues/12083#issuecomment-660136888, preferably their behaviour should be the same, and should be that of the 2nd screen recording.

(Anybody who wants to directly open the link would press the bookmark directly instead of pressing the 3 dot menu and then opening it anyways.)

**Comment by topotropic** [comment]
Thanks for the feedback. 

It's inconsistent by design in this case: If you open one bookmarked page, Fenix opens the page right away to save a step and when you open multiple pages it send you to the tab tray so that you can choose what to view first.
