### ISSUE TITLE
FNX-4915 ⁃ [Bug] Android Edge Effect missing on home screen

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#1267]
## Steps to reproduce
1. Open Fenix
1. Scroll the home page
1. Observe

Places I've noted are the homescreen and browsing web pages. We should also take a look at settings. 

### Expected behavior
1. Edge effect is there

### Actual behavior
1. Edge effect not there

### Device information
* Android device: Pixel something  - i have no idea
* Fenix version: The 3/26 build

**Comment by kbrosnan** [comment]
#1055 is the bug for web content.

**Comment by sblatz** [comment]
We have this edge effect now. 

@lime124 please re-open this ticket if you feel the effect should be different 😄 

![edge effect 2019-07-01 14_39_12](https://user-images.githubusercontent.com/4400286/60468314-12c6bb80-9c0e-11e9-830f-8fe161dabc20.gif)

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/3673
