### ISSUE TITLE
[Homescreen] Adjust top and left alignment of logo on homescreen

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#12673]
Hi, 

Please update the homescreen logo position to the mock posted below. The logo should be left aligned with 16px margin along with the collections elements and should be vertically aligned to the Private browsing icon. Thanks

![](https://user-images.githubusercontent.com/5992746/87809746-df12ff80-c829-11ea-8bd4-714d11965b09.png)

**Comment by Dunexus** [comment]
@AmyYLee What about the alignment of beta and nightly text as it has two lines of text ("Firefox Browser" and "Beta"/"Nightly") ?

Currently, "Firefox Browser" is aligned with the logo and "Beta"/"Nightly" below seems missaligned.

![Screenshot_20200717-224743.jpg](https://user-images.githubusercontent.com/13906248/87829742-e95fe880-c87f-11ea-8963-b29e079795dc.jpg)

**Comment by hakkikaancaliskan** [comment]
> 
> 
> @AmyYLee What about the alignment of beta and nightly text as it has two lines of text ("Firefox Browser" and "Beta"/"Nightly") ?
> 
> Currently, "Firefox Browser" is aligned with the logo and "Beta"/"Nightly" below seems missaligned.
> 
> ![Screenshot_20200717-224743.jpg](https://user-images.githubusercontent.com/13906248/87829742-e95fe880-c87f-11ea-8963-b29e079795dc.jpg)

Yep, agreed. We will need new wordmark icons for that, there will be no problem on eng side.

**Comment by AmyYLee** [comment]
![Screen Shot 2020-08-25 at 3 47 31 PM](https://user-images.githubusercontent.com/5992746/91220617-6e91b500-e6ea-11ea-958e-1a0bea65d4c8.png)

@hakkikaancaliskan  The alignment should follow like this for the Nightly logo. Thanks


> > @AmyYLee What about the alignment of beta and nightly text as it has two lines of text ("Firefox Browser" and "Beta"/"Nightly") ?
> > Currently, "Firefox Browser" is aligned with the logo and "Beta"/"Nightly" below seems missaligned.
> > ![Screenshot_20200717-224743.jpg](https://user-images.githubusercontent.com/13906248/87829742-e95fe880-c87f-11ea-8963-b29e079795dc.jpg)
> 
> Yep, agreed. We will need new wordmark icons for that, there will be no problem on eng side.

This should be top aligned with the

**Comment by AmyYLee** [comment]
Moving forward - please ping @apbitner for review

**Comment by hakkikaancaliskan** [comment]
> ![Screen Shot 2020-08-25 at 3 47 31 PM](https://user-images.githubusercontent.com/5992746/91220617-6e91b500-e6ea-11ea-958e-1a0bea65d4c8.png)
> 
> @hakkikaancaliskan The alignment should follow like this for the Nightly logo. Thanks
> 
> > > @AmyYLee What about the alignment of beta and nightly text as it has two lines of text ("Firefox Browser" and "Beta"/"Nightly") ?
> > > Currently, "Firefox Browser" is aligned with the logo and "Beta"/"Nightly" below seems missaligned.
> > > ![Screenshot_20200717-224743.jpg](https://user-images.githubusercontent.com/13906248/87829742-e95fe880-c87f-11ea-8963-b29e079795dc.jpg)
> > 
> > 
> > Yep, agreed. We will need new wordmark icons for that, there will be no problem on eng side.
> 
> This should be top aligned with the

It's currently as you said in #12676 afaik. I'll check and post a screenshot in pr.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build 9/10 with Google Pixel 4 XL (Android 11).
