### ISSUE TITLE
Create unit tests for shortcuts

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1268]
We did not land unit tests with the shortcuts feature, but we should add some.

Files to test: 
* https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/PrivateShortcutCreateManager.kt
* ...

**Comment by sblatz** [comment]
It will be pretty difficult to create the first test when we don't have a framework set up. I'm going to label this blocked until we have some groundwork.

**Comment by vesta0** [comment]
@st3fan what is the next step to set up a framework for unit tests?

**Comment by sblatz** [comment]
My understanding after speaking with @colintheshots and @boek is that we just need to integrate some robo electric tests as examples for others to work off of.

**Comment by sblatz** [comment]
@vesta0 I think we need to move this out of this sprint and instead have a more senior engineer work on https://github.com/mozilla-mobile/fenix/issues/1710.

**Comment by liuche** [comment]
Also somewhat related: thinking about what other unit test bugs can be done in a similar manner? We should add them to the Eng Stories column in the Fenix Kanban.

**Comment by sblatz** [comment]
Notably we now have UI tests for this, but we should likely add unit tests still

**Comment by sanyud24** [comment]
may I work over this issue ?

**Comment by RotBolt** [comment]
Hello @sblatz and @eliserichards This issue seems to be long pending and stale. I have written unit tests for my applications. I think could be good fit for this. If you think the same could you please assign it to me
