### ISSUE TITLE
Add link selection effect like Chromium browsers.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12689]
Currently It feels like Fenix isn't doing anything when the link is being selected or the user has clicked on something in the website and the user only knows that something _has_ happened is only when the link long-press menu pops-up or something pops-up from clicking link on the website itself. This should be improved otherwise it'll feel like nothing is happening when the link is long-pressed and it will feel like the link selection process is taking longer that expected. Something like how Chromium browsers do when the link is being selected would be great as it'll let the users know that something is happening until the link click long-press menu pops-up.

Otherwise issues and bugs like #10618 these will make it feel more like the link selection process taking too much time even if the Fenix team fixes the #10618 issue. 

Please see the GIFs.

Thank you. :grinning:

### Chrome browser's behaviour (just see how connected it feels): 
![Chrome link effect 2.gif](https://user-images.githubusercontent.com/68282543/87844841-0a0b5b00-c8df-11ea-927f-1ef94a54fa0b.gif)

![20200718](https://user-images.githubusercontent.com/68282543/87845309-afa9d480-c8b5-11ea-9079-c3447aeae0ee.gif)UNITO-UNDERSCORE!104324!

![20200718](https://user-images.githubusercontent.com/68282543/87845468-41661180-c8b7-11ea-98f2-580c101cd483.gif)UNITO-UNDERSCORE!105505!

### Fenix behaviour: 
![20200717](https://user-images.githubusercontent.com/68282543/87844909-76865a00-c8df-11ea-8b8b-0b5c4d5e1622.gif)UNITO-UNDERSCORE!184239.gif!

![20200718](https://user-images.githubusercontent.com/68282543/87845394-5e4e1500-c8b6-11ea-8534-ecf071e4c853.gif)UNITO-UNDERSCORE!104837!

![20200718](https://user-images.githubusercontent.com/68282543/87845529-cb15df00-c8b7-11ea-9f06-9e7ef9bf366d.gif)UNITO-UNDERSCORE!105826!

Thank you!  :grinning:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3601)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809297

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
