### ISSUE TITLE
[Bug] Unnecessary context menu options for find in page->long click

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12697]
## Steps to reproduce
Open find in page
Long click to open context menu in find in page search box

### Expected behavior
Optsions are: Paste

### Actual behavior
Options are: Paste, Paste as plain text and Autofill

Paste as plain text and autofill make no sense in this context

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by AndiAJ** [comment]
**Not reproducible** anymore, only the "Paste" option is displayed on the latest **`Nightly Build 201106`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by s-ankur** [comment]
I am not able to take the screenshot, but I still have autofill option for this. Can you try and install Bitwarden and then check @AndiAJ

**Comment by AndiAJ** [comment]
Hi @s-ankur , thanks for the heads up! ☺️ 
I've managed to reproduce it having the Bitwarden app installed.

► Video 
![20201106-173936](https://user-images.githubusercontent.com/51314259/98385444-a9538a00-2057-11eb-8cf2-62e12f827d2e.gif)
