### ISSUE TITLE
[Bug] Search Widget text does not change on changing language.

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12694]
## Steps to reproduce
Install widget on android homescreen
Change language in fenix settings
Exit fenix
View widget

### Expected behavior
Widget uses the correct language set in fenix

### Actual behavior
It gets stuck on a previous language

### Device information
* Android device: asus zenfone 
* Fenix version: nightly

**Comment by sflorean** [comment]
Tested on Nightly 7/20 and the search widget text is changing after 2-3 seconds. @s-ankur can you confirm this?

**Comment by s-ankur** [comment]
@sflorean for me the text does not change until I delete and replace the widget. I am on

Nightly 200720 06:02 (Build #22020612)
AC: 51.0.20200719130512, e38c71e17
GV: 80.0a1-20200717093907
AS: 61.0.10

**Comment by AndiAJ** [comment]
**Reproducible** on the latest **`Nightly Build 201106`** using a Google Pixel 3a (Android 11)
