### ISSUE TITLE
FNX2-15412 ⁃ [Bug] "www." not trimmed from url in tab tray

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#12692]
## Steps to reproduce
Open https://www.wikipedia.org/ or https://www.nytimes.com/.

### Expected behavior
URLs in tab tray have the "www." stripped like they do in the address bar:

![](https://user-images.githubusercontent.com/46764284/87849073-f9121800-c8e5-11ea-9970-984d2c4fc6f7.png)

![](https://user-images.githubusercontent.com/46764284/87849076-fadbdb80-c8e5-11ea-945d-ac8ca8758a60.png)

This also happened in the old version of the tab tray (I borrowed this screenshot from https://github.com/mozilla-mobile/fenix/issues/10683#issue-618970283):

![](https://user-images.githubusercontent.com/46764284/87849181-d03e5280-c8e6-11ea-91c0-82a052aa6e87.png)

### Actual behavior
The "www." is present:

![](https://user-images.githubusercontent.com/46764284/87849104-39719600-c8e6-11ea-8f90-756e8a6488ca.png)

There are actully two arguments in favor of this:

1. The hostname shown should reflect the one shown in the address bar.
1. Hiding this reduces clutter in the tab tray.

**Comment by amkcpu** [comment]
Two arguments:
1. The hostname shown should reflect the one shown in the address bar.
2. Hiding this reduces clutter in the tab tray.

**Comment by ShatteredPixel** [comment]
Can you tell me if this is going to hide only the "www" or anything that's comes after the "https://"? For example, for the address "blog.mozilla.org", is it gonna to hide the "blog" in it or keep it? 

If it is going to hide anything that comes after the "https" them I'd suggest keep everything as it is right now and if it is going to only hide "www" then I think this would provide consistency with the tabs in the tabs tray showing the same the address as the address bar. 


But I also say that we have the space in the address bar to show the website address with "www" in it and why not utilise that? but it'll also feel a bit weird as the address bar is showing something and and the tabs in the tabs tray is showing something. 


Anyway, Mozilla is already hiding the protocol "https" and "www" and I say that hide the "www" or whatever and make it consistent with what is being shown in the address bar so the users can be confident that the only way to view the full website address is to click the address bar and view it and there's no other way to view the full website address.

**Comment by amkcpu** [comment]
It's only about hiding the "www.", to be consistent with the address bar. As you mentioned, other subdomains can be very important, like the example you gave (blog.mozilla.org). I don't want to hide these!

**Comment by amkcpu** [comment]
For reference: #7077 discusses shortening the URL in the address bar.
https://github.com/mozilla-mobile/fenix/issues/7077#issuecomment-602870296 states only to hide "http://", "https://" and "www." for the time being. The first two don't apply to the tab tray (only the hostname is shown anyway) but the third one does (and that's what this issue addresses).

**Comment by ShatteredPixel** [comment]
Thanks a lot for the references and the link to the issue. I have subscribed to that issue to see how the situation develops going forward.

Thanks again! :)

**Comment by amkcpu** [comment]
> Edit: Why's that issue closed? Has everything been settled already? Do you know anything more about it?

Issue #7077 was about shortening the URL **in the address bar**, which was then implemented in PR https://github.com/mozilla-mobile/android-components/pull/6232 (hence, the issue was closed).

This issue here is about bringing a part of that shortening (dropping the "www." prefix) to the URL shown in the **tab tray**.

**Comment by ShatteredPixel** [comment]
The issue's title #7077 "Clean URL Display" confused me bit and I thought the elision of website addresses in the address bar is still ongoing and removing "http://" ,"https://" and "www." are just starting points and there would more like these, the comments there seem to indicate this. That's the reason I asked why that issue was closed.


I already understand what this issue and PR is about.  

I think I annoyed you a bit and sorry for that! :) And thanks for the explanation.

**Comment by amkcpu** [comment]
Sorry I got you wrong then! And don't worry, questions are always good :)

**Comment by ekager** [comment]
cc @topotropic is this something we want to do?

**Comment by topotropic** [comment]
Yes, we can follow the same rules we currently use for the URL display in the awesome bar (cut protocol and www but keep subdomains like **blog**.mozilla.org)

**Comment by ekager** [comment]
Reopening for QA

**Comment by sv-ohorvath** [comment]
Verified as fixed on Beta 80.0
