### ISSUE TITLE
[Bug] Tab count switching animation is not activated when it is 0

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12696]
## Steps to reproduce
Open some tabs in one mode and no tabs in the other.
On home screen, switch from private mode to normal mode and vice versa

### Expected behavior
Tab switch animation activated in both cases

### Actual behavior
Tab switch animation not activiated on switching from the mode with 0 tabs to the mode with some tabs.

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by ekager** [comment]
Closing because now when you switch modes you'll enter the search dialog. I don't think this is relevant anymore
