### ISSUE TITLE
FNX-4916 ⁃ Re-architect Reference Browser for Learnings

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#127]
This will allow us to learn more about our architecture pattern we will use in Fenix.

**Comment by bbinto** [comment]
@colintheshots will break down further and time-box to be finished for next week

**Comment by colintheshots** [comment]
This is in a usable state. I'll improve it further over time, but the basic ideas are there. https://github.com/colintheshots/reference-browser/tree/prototype

**Comment by colintheshots** [comment]
The only thing needed at this point is some arch documentation in the wiki explaining how we do things for Fenix.
