### ISSUE TITLE
Missing referenced file in adaptive-icon mipmap-anydpi-v26/ic_launcher.xml

### ISSUE THREAD

**Issue by greenorion** [mozilla-mobile/fenix#12701]
### Steps to reproduce
Looking in
[app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml)
and 
[app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml)
we have
`<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">`
{{    <background android:drawable="@color/ic_launcher_background"/>}}
{{    <foreground android:drawable="@drawable/ic_launcher_foreground"/>}}
`</adaptive-icon>`

But there is no file color/ic_launcher_background

**Comment by kleinph** [comment]
This is most likely not a bug. The `@color/ic_launcher_background` is defined in [the colors.xml](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/colors.xml#L384)
