### ISSUE TITLE
Add a scrollbar to the Fenix's "Bookmarks" screen

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12706]
This adds to the suggestions listed in the issue and continues it: #12704. 

I already made a suggestion to add a scrollbar to the tabs tray in the issue #11873. And these upcoming suggestion were suggested here: https://github.com/mozilla-mobile/fenix/issues/12050#issuecomment-660557463.

To go through my previous thoughts on why there should be scroll bar, I'll repeat what's said in the issue #11973 while replacing the word tabs tray with Bookmarks screen;

- - -
Please add a scrollbar so users can know where exactly their position in the in the Fenix's Bookmarks screen is, for example if they're in the middle, the end or the starting position of the the Bookmarks screen.

Right now it is hard to know the position if there're lots of Bookmarks items and when it'll end. let's say 100, 200, or even more, unless the user scrolls to the end or the start of the Fenix's Bookmarks screen.

Chrome and Vivaldi already feature such a feature: 

Chrome's Bookmarks screen: 

![Screenshot](https://user-images.githubusercontent.com/68282543/87864081-29dc6680-c953-11ea-8bca-414a4feea95d.png)UNITO-UNDERSCORE!20200719-053143!

**Comment by ekager** [comment]
Done
