### ISSUE TITLE
FNX2-15423 ⁃ [Bug] Long presssing mailto link does not show context menu

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#12705]
From https://www.reddit.com/r/firefox/comments/htqozv/does_fenix_not_show_a_dialog_when_longpressing/

## Steps to reproduce
1. Navigate to https://output.jsbin.com/qotekoc/quiet
1. Long press "John’s email address"

### Expected behavior
Context menu appears with options like: share email, copy, add to contacts

### Actual behavior
No menu appears.

This worked in Fennec and works in Chrome. 

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 200718

**Comment by kbrosnan** [comment]
This is broken in Reference browser as well. Likely an A-C issue.

**Comment by rocketsroger** [comment]
This is fixed in Nightly.  Please verify.  Thanks

**Comment by yoasif** [comment]
Working for me.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200818 Build #2015758643 from 8/18 with Pixel 2 (Android 9).
The menu is displayed as in the screenshot:
![rsz_screenshot_20200819-095048](https://user-images.githubusercontent.com/48799384/90602193-0599d100-e202-11ea-8646-8311982ac536.png)
I will remove the qa:needed label.
