### ISSUE TITLE
Add a scrollbar to the Fenix's address bar's "Search suggestions" screen

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12707]
This adds to the suggestions listed in the issue and continues it: #12706 . 

I already made a suggestion to add a scrollbar to the tabs tray in the issue #11973. And these upcoming suggestion were suggested here: https://github.com/mozilla-mobile/fenix/issues/12050#issuecomment-660557463.

To go through my previous thoughts on why there should be scroll bar, I'll repeat what's said in the issue #11873 while replacing the tabs tray with "Search suggestions" screen;

- - -
Please add a scrollbar so users can know where exactly their position in the in the Fenix's address bar's "Search suggestions" screen is, for example if they're in the middle, the end or the starting position of the the "Search suggestions" screen.

Right now it is hard to know the position if there're lots of Search suggestions in the address bar's screen and when it'll end. let's say 10, 15, or even more, unless the user scrolls to the end or the start of the Fenix's address bar's Search suggestions screen.

Vivaldi already feature such a feature: 

Vivaldi's Bookmarks screen:
![Screenshot](https://user-images.githubusercontent.com/68282543/87864199-e97de800-c954-11ea-9368-1ec8aef360e6.png)UNITO-UNDERSCORE!20200719-054410!

**Comment by ekager** [comment]
Done
