### ISSUE TITLE
Flip Tabs Tray UI elements if URL bar is on top

### ISSUE THREAD

**Issue by cousteaulecommandant** [mozilla-mobile/fenix#12703]
The Tabs Tray is designed targeting users who have the URL bar on bottom: the position of the New Tab button is very close to where the Tabs button is, so you can open a new tab quickly by double tapping this button.
For consistency, users who have chosen to have the URL bar at the top because they don't quite like the new placement should have the New Tab button at the top as well. 

The changes I would make for users who have configured the URL bar on top are:

* Flip the position of widgets. 
* ~~Make the tab tray slide from the top, not the bottom, and close it by swiping it up, not down.  (Can this be done with the current UI API?)~~
* Maybe also change the order of tabs to have the newest at the bottom (I'm not too sure about this one). 
* Also see issue #12148 for a similar issue regarding the placement of the tabs/private/dots buttons. 

EDIT: [As this comment suggests](https://github.com/mozilla-mobile/fenix/issues/11298#issuecomment-640114638), the widget API does not allow having a sheet that slides from top, so scratch that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3635)

**Comment by ekager** [comment]
closing for #11298

**Comment by cousteaulecommandant** [comment]
> closing for #11298

That issue only covers the second point.  This one focuses mainly on the position of buttons in the tray.

**Comment by AmyYLee** [comment]
@topotropic for consideration

**Comment by toupeira** [comment]
> EDIT: As this comment suggests, the widget API does not allow having a sheet that slides from top, so scratch that.

Looks like it's still possible to maximize the sheet with `STATE_EXPANDED`, and even disable collapsing with `app:behavior_skipCollapsed`: https://material.io/develop/android/components/bottom-sheet-behavior
This way it would at least stick to the top.

Regarding "New tab", I would love to just have it back in the hamburger menu. It's confusing having to show all tabs first when I just want to open a new tab. It would also work great next to the "Scan" and "Shortcuts" buttons above the keyboard, so I could just tap the address bar and open a new tab from there.

**Comment by cousteaulecommandant** [comment]
> Looks like it's still possible to maximize the sheet with `STATE_EXPANDED`, and even disable collapsing with `app:behavior_skipCollapsed`: https://material.io/develop/android/components/bottom-sheet-behavior
> This way it would at least stick to the top.

I think the way it is right now is good enough (tray goes ALMOST all the way to the top, and corners are straight instead of rounded, but you can still flick the tray down to close it).  This was a nice improvement; kudos to the devs.

**Comment by AVHon** [comment]
I disagree with @cousteaulecommandant; I think the tab tray is still much worse when the URL bar is at the top than at the bottom.

With the URL bar at the top, opening a new tab and navigating to a URL requires a *lot* of travel:

* Tap tab counter at top of screen
* Tab "new tab" button near bottom of screen
* Tap inside URL bar at top of screen
* Type in keyboard at bottom of screen

It would be much better if, when the URL bar was at the top of the screen, the "new tab" button was, too. The previous release of FF maximized this by having the tab counter *turn in to* the "new tab" button when you tapped it -- no travel at all between the first two taps, and the URL bar is huge and close by.

**Comment by cousteaulecommandant** [comment]
> I disagree with @cousteaulecommandant; I think the tab tray is still much worse when the URL bar is at the top than at the bottom.

Yes; the position of the New Tab button is still wrong.  I was referring only to the Regular/Private Tabs buttons, which are now very close to the top of the screen and thus easier to reach; but this change did NOT fix the main issue discussed in the topic (the New Tab button should be on the top, where the other two buttons are).  Sorry for the confusion.

**Comment by yoasif** [comment]
> Regarding "New tab", I would love to just have it back in the hamburger menu. It's confusing having to show all tabs first when I just want to open a new tab. It could also work great next to the "Scan" and "Shortcuts" buttons above the keyboard, so I could just tap the address bar and open a new tab from there.


@toupeira You may be interested in https://github.com/mozilla-mobile/fenix/issues/9871.

**Comment by yoasif** [comment]
> Looks like it's still possible to maximize the sheet with `STATE_EXPANDED`, and even disable collapsing with `app:behavior_skipCollapsed`: https://material.io/develop/android/components/bottom-sheet-behavior
> This way it would at least stick to the top.

@toupeira a comment might be good here: https://github.com/mozilla-mobile/fenix/issues/9871.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812925

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
