### ISSUE TITLE
Add a scrollbar to the Fenix's "History" screen

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12704]
I already made a suggestion to add a scrollbar to the tabs tray in the issue #11873. And these upcoming suggestion were suggested here: https://github.com/mozilla-mobile/fenix/issues/12050#issuecomment-660557463.

To go through my previous thoughts on why there should be scroll bar, I'll repeat what's said in the issue #11873 while replacing the word tabs tray with History screen;

- - -
Please add a scrollbar so users can know where exactly their position in the in the Fenix's History screen is, for example if they're in the middle, the end or the starting position of the the History screen.

Right now it is hard to know the position if there're lots of History items and when it'll end. let's say 100, 200, or even more, unless the user scrolls to the end or the start of the Fenix's History screen.

Chrome and Vivaldi already feature such a feature: 

### Chrome browser's history screen: 
![Screenshot](https://user-images.githubusercontent.com/68282543/87863941-f13b8d80-c950-11ea-96cb-de9e0a97d0bc.png)UNITO-UNDERSCORE!20200719-051541!

### Vivaldi browser's history screen: 
![Screenshot](https://user-images.githubusercontent.com/68282543/87863942-f567ab00-c950-11ea-8c91-da246496e3ac.png)UNITO-UNDERSCORE!20200719-051354!

**Comment by liuche** [comment]
@topotropic do you have any thoughts on this and related issues #12706, #12707, etc? There are PRs opened for these as well, so if you think they're good we could review them.

**Comment by topotropic** [comment]
Yes, sounds good to me. Scrollbar helps people to get an idea of how many entries they have and gives some sense of orientation. Thanks!

**Comment by ShatteredPixel** [comment]
@topotropic can you also provide some feedback here on this issue: https://github.com/mozilla-mobile/fenix/issues/12708 the mentioned issue is about adding a scrollbar to the address bar's "Shortcuts" screen. And I'm not sure if a scrollbar should be added to that screen or not.

**Comment by ekager** [comment]
Done
