### ISSUE TITLE
Add a scrollbar to the Fenix's address bar's "Shortcuts" screen

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12708]
This adds to the suggestions listed in the issue and continues it: #12707. 

I already made a suggestion to add a scrollbar to the tabs tray in the issue #11873. And this ends suggestions that were suggested here: https://github.com/mozilla-mobile/fenix/issues/12050#issuecomment-660557463.

To go through my previous thoughts on why there should be scroll bar, I'll repeat what's said in the issue #11873 while replacing the word tabs tray with search engine "Shortcuts screen" screen;

- - -
Please add a scrollbar so users can know where exactly their position in the in the Fenix's address bar's "Search suggestions" screen is, for example if they're in the middle, the end or the starting position of the the "Shortcuts" screen.

Right now it is hard to know the position if there're lots of Search suggestions in the address bar's screen and when it'll end. let's say 10, 15, or even more, unless the user scrolls to the end or the start of the Fenix's address bar's search engine "Shortcuts" screen.

**_I'm not sure if this particular feature of adding the scrollbar to the "Shortcuts" screen would be useful since I don't know how many users actually add how many number of search engines Shortcuts their Shortcuts screen. So I'll have to discuss it with the UX team to know whether this should be added or not but since if we end up adding a scrollbar bar in the search suggestions screen then it'll maintain consistency with both the "Search suggestions" and "Search with" screen if we add a scrollbar in "Shortcuts" screen as well._**

P.S I think I'm probably missing several other screens where the scrollbar is missing. Please let me know if that is the case. 

Thanks. :grinning:

**Comment by amkcpu** [comment]
> I'm not sure if this particular feature of adding the scrollbar to the "Shortcuts" screen would be useful since I don't know how many users actually add how many number of search engines Shortcuts their Shortcuts screen.

After doing #12713, #12714 and #12715, holding of on this issue waiting for UX feedback.

**Comment by ShatteredPixel** [comment]
@amkcpu 

Thanks a lot for your work on adding scrollbars bar's to Fenix in different screens.

In the issue #12050, I received a response regarding scrollbars in Fenix, can you please go through it: https://github.com/mozilla-mobile/fenix/issues/12050#issuecomment-660814208

Thanks again for your work on this! :)

**Comment by topotropic** [comment]
@brampitoyo I leave this up to you – not sure how long this list can get; for reference my reply to the history/bookmark scrollbar issue https://github.com/mozilla-mobile/fenix/issues/12704#issuecomment-660982130

**Comment by apbitner** [comment]
If there is no limit to the number of search shortcuts a user can have then we should make this list scrollable.
