### ISSUE TITLE
[Bug] Beta is noticably laggy

### ISSUE THREAD

**Issue by dead10ck** [mozilla-mobile/fenix#12709]
I've been trying out the new Firefox UI on Android ever since the first Firefox Preview release, and I can't help but be bothered by a very noticeable difference in the responsiveness. The Beta UI is significantly slower.

I'm not sure if it's going to do it justice, since my screen is 90Hz, but I captured a screen recording of a difference between the most up to date versions of Firefox and Firefox Beta on the Play Store.

https://vimeo.com/439655054

## Steps to reproduce
Open a stable build of Firefox, open a web page with lots of vertical room, and just scroll around, quickly and slowly.

### Expected behavior
There shouldn't be any perceptible lag when scrolling the window.

### Actual behavior
There is.

### Device information
* Android device: OnePlus 7T
* Fenix version:

79.0.0-beta.9 (Build #2015752523)
AC: 48.0.5, c14ffa848
GV: 79.0-20200713185329
AS: 61.0.7

**Comment by ShatteredPixel** [comment]
Can you record a profile for this performance issue and include in your issue's description? 

https://profiler.firefox.com/docs/#/./guide-remote-profiling

**Comment by dead10ck** [comment]
@ShatteredPixel sure, I can do that on Monday

**Comment by dead10ck** [comment]
Hmm, someone made a comment on reddit that suggested that the issue may be specific to the OnePlus series: https://www.xda-developers.com/oneplus-7-pro-true-90hz-display-mode/

Apparently not every app runs in 90Hz, which makes them seem slower.

**Comment by ShatteredPixel** [comment]
Yeah, I know about that. If you forcefully try to to run an app that doesn't support the higher refresh rate. It will apparently run even slower than it was at 60Hz

Just keep thi issue open and let rhe developers worry about all the technical details and what to do higher refresh rate devices. Okay?

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/android-components/issues/6493

**Comment by dead10ck** [comment]
Ah, this is probably a duplicate of that

**Comment by ShatteredPixel** [comment]
I don't have a high refresh rate device with me yet but I'm imagining that the devices with high refresh rate will become common (read very common)  in coming months/years. So if Fenix does not support high refresh rate devices then the users who run Fenix on those devices will find it to be really slow, laggy and buggy as **dead10ck** is already facing. 

AFAIK, that high refresh rate could be turned off but I think by default it's already turned on by OEMs and even if it can be turned off I think AFAIK the users of those devices are not willing to do so and I know why they are saying so and I might do same thing. 

The users will, I think, move to other browsers instead than turning off the high refresh rate of their devices which is one of the unique features about it.

**Comment by hakkikaancaliskan** [comment]
I have stutter as you described on my 60 hz XZ1. Same issue with #12710.

**Comment by ShatteredPixel** [comment]
**hakkikaancaliskan** You are facing stutters even on your a 60Hz device as well? Does it happen on all websites? Can you provide me some websites where do you think this could be reproducible so that I can test it too? Do you think a performance [profile](https://profiler.firefox.com/docs/#/./guide-remote-profiling) of Fenix would help investigate what's causing these stutters?

**Comment by hakkikaancaliskan** [comment]
> **hakkikaancaliskan** You are facing stutters even on your a 60Hz device as well? Does it happen on all websites? Can you provide me some websites where do you think this could be reproducible so that I can test it too? Do you think a performance [profile](https://profiler.firefox.com/docs/#/./guide-remote-profiling) of Fenix would help investigate what's causing these stutters?

Latest nightly
Android 10, XZ1 60hz
Nearly on all websites
For example: https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix
I will try to take profile when I get home.

**Comment by cadeyrn** [comment]
I have a 90 Hz device (OnePlus 7T Pro McLaren Edition) and yes, in a direct comparison I notice a difference between Fenix and Chrome, but it's really far from "really slow, laggy and buggy". Without this issue and a direct comparison I wouldn't have even noticed it's not ideal.

**Comment by ShatteredPixel** [comment]
For clarification, I said, "really slow, laggy and buggy" because I have seen users complain exactly like this. 

Full disclosure: I don't own a device having a high refresh rate. So anything that I say should taken with a big pinch of salt! ;)

Thank you! :)

**Comment by hakkikaancaliskan** [comment]
Here is the profile on my XZ1, Android 10, 60hz on stackoverflow.com: https://share.firefox.dev/3eMxLiA
Idk what's the frame rate but it feels like stuttering. Even more on more complex websites.

**Comment by Dunexus** [comment]
I think it may help the eng team to know if this happen with and/or without webrender enabled (gfx.webrender.all in about:config)

**Comment by hakkikaancaliskan** [comment]
> I think it may help the eng team to know if this happen with and/or without webrender enabled (gfx.webrender.all in about:config)

All default.
Webrender enabled.

**Comment by hakkikaancaliskan** [comment]
Here is some real stutter: https://share.firefox.dev/2CVTM16
XZ1, Android 10, 60hz on https://forum.xda-developers.com/xperia-xz1/development/9-carbonrom-cr-7-0-t3960309/page22
All default about:config, webrender enabled by default

**Comment by hakkikaancaliskan** [comment]
When I toggle webrender.force_disabled to true, websites scrolling smoothly. Could you guys verify this?

**Comment by dead10ck** [comment]
That made no difference for me

**Comment by hakkikaancaliskan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1655278
Could you guys try to set toolkit.lazyHiddenWindow=false in about:config?
Also try is there a lag on second and later tabs.

**Comment by mcomella** [comment]
Triage: there was a flag enabled early in the beta cycle that affected early beta flag that affected performance. ecsmyth will try to reproduce the issue on the S10 with the 120 Hz display (and if they can't, MarcLeclair can try on the P4's 90 Hz display).

**Comment by mcomella** [comment]
I have difficulty seeing the issue in the recorded video but it looks like on beta (the second device shown), towards the end of the video, it starts to drop frames while scrolling up.

**Comment by dead10ck** [comment]
I want to emphasize again that while you can see some of the lag in the video, the video really doesn't do it justice, because it's only recording 60 FPS. It's much worse when actually looking at a 90Hz screen.

**Comment by dead10ck** [comment]
I noticed the new UI was just pushed to stable. After upgrading, the lag is no longer there!

**Comment by mcomella** [comment]
@dead10ck If I understand correctly then this is no longer an issue and this can be closed? I'll go ahead and do so. Please reopen if I am mistaken. :)

**Comment by dead10ck** [comment]
@mcomella it is fixed for me with the stable version of Firefox. It must be specific to OnePlus devices only having certain apps set to 90Hz.
