### ISSUE TITLE
Add violentmonkey and tampermonkey extensions to Fenix.

### ISSUE THREAD

**Issue by fafnar** [mozilla-mobile/fenix#12719]
扩展里最强大的，莫过于violentmonkey或者tampermonkey了，通过添加脚本，能实现很多功能，希望能在新版本里添加

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3652)

**Comment by AVHon** [comment]
Seconding this. Being able to run userscripts is valuable for allowing users to customize and improve their web experience.

**Comment by Giwayume** [comment]
I'm uninstalling the latest and installing the old version of Firefox for Android where userscripts used to work. This kind of incompatibility is inexcusable. The ONLY reason to use Firefox on mobile vs any other browser was its ability to customize the web experience, and user scripts account for a ginormous part of that.

**Comment by mattsteve** [comment]
> The ONLY reason to use Firefox on mobile vs any other browser was its ability to customize the web experience

I wouldn't say it's the only reason, but definitely a big reason. The Google Play reviews corroborate that people care a lot about extensions... and having less than 10 available right now is not a good look. I don't think this walled garden approach is going to work out well for the adoptability of the browser.

**Comment by pruidong** [comment]
Hello, I would like to ask if you have plans to introduce more extensions to the Android version of Firefox? There are too few extensions for the Android version of the browser. I hope to introduce tampermonkey or violentmonkey extensions. Thank you.

**Comment by pruidong** [comment]
In addition, I hope to introduce more other extensions to the Android version of Firefox. Thank you.

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/20736

**Comment by gabrielluong** [comment]
There are workarounds with creating your own whitelist of addon collections. See https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

**Comment by rokejulianlockhart** [comment]
@gabrielluong, why?
