### ISSUE TITLE
[Bug] Tab switching popup is too tall on narrow-and-tall phones

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#12718]
## Steps to reproduce
Open two tabs and try the then switch from one to another

### Expected behavior
It should be easy to access the tabs

### Actual behavior
Lots of white space at the bottom of the tab switching popup

### Device information
* Android device: Sony Xperia 10 II, Android 10
* Fenix version: Nightly 200718, GV 80.a1-20200717093907

**Comment by mcarare** [comment]
@smaug---- Can you please provide a screenshot so we can also see the issue? Thank you!

**Comment by smaug----** [comment]
https://i.ibb.co/tJ1Bpys/image.png

**Comment by smaug----** [comment]
![image](https://user-images.githubusercontent.com/9219935/87925710-58f4f400-ca89-11ea-9833-d4f284838f51.png)

**Comment by apbitner** [comment]
@topotropic for review

**Comment by topotropic** [comment]
Thanks for your feedback. We are constantly working on improving the tab tray and will keep your feedback in mind.
