### ISSUE TITLE
[Bug] Scrolling on Nightly and Beta is somewhat laggy and choppy, not smooth. But the stable version scrolls just fine, but doesnt follow device theme (dark mode).

### ISSUE THREAD

**Issue by peidodeveio** [mozilla-mobile/fenix#12710]
### Device information
* Android device: Galaxy S9+, Android 10, OneUi 2.0
* Fenix version: 200718

**Comment by hakkikaancaliskan** [comment]
Web-content scrolling, right?

Android 10, webrender enabled by default, not pref
ublock origin, decentraleyes

**Comment by sflorean** [comment]
Duplicate of #12709.
