### ISSUE TITLE
[Missing Features] Disable Images and Fonts on Mobile network (or completely)

### ISSUE THREAD

**Issue by benyaminl** [mozilla-mobile/fenix#12711]
### What is the user problem or growth opportunity you want to see solved?
I'm still a fennec Firefox user, and the only thing why I choose Firefox because it really conserve data with Disabling Images and Fonts when I'm on mobile network, and it's really useful to be used to conserve data plan OTG (On Third World Country like Indonesia, and Africa, data plan is really expensive, in Indonesia, it cost more than 2 days lavish meal, and it's normal for that data plan packages hurt a lot of people[even gov based telco companies riping people of, and censor some web of it, it's not related to this data saving feature although, DoH is]), and it's already working on fennec based browser, and hoping in the future it will still bring to Fenix browser. 

### How do you know that this problem exists today? Why is this important?
It's not on fenix and no one mention it on this issue [although it's on #11536 with data saver concept, but this's more bullet proof], and I think by helping people choose some only needed images then it will help a lot of people, conserve more data OTG/mobile plan, and help people in rural area having a better surfing experience on web browsing

### Who will benefit from it?
Indonesian People, third world country that have expensive data plan (which telco rip them off, giving them more ability to access more information by granting them ways to conserve data plan)

This's related to #11536, Hope this will be considered, because it's already on Fennec based, and I really hope this will last across android version, or maybe event Firefox can detect the network is slow, then automatically turn off image and font intelegently(I think if it's can be more bold, also turn off CSS, haha... because if we use it only for reading, it will conserve data, a lot, really, text based information still the king of the web, for me, especially like Wikipedia, and other pages that give other people information), it will help, because data saving features of chrome, use this kind of thing/algorithm. Thank you

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3644)

**Comment by madb1lly** [comment]
Hi @kbrosnan,

If you're editing issues then please can you add the "Feature:FennecTransition" label to this one? Or is that label now defunct and [Missing Features] is the new way to identify Fennec features that are missing in Fenix?

Cheers 🙂

**Comment by cadeyrn** [comment]
> Or is that label now defunct and [Missing Features] is the new way to identify Fennec features that are missing in Fenix?

The issue opener addded "[Missing Features]" to the issue title, kbrosnan only reverted the changes of the data-sync-user bot.

**Comment by madb1lly** [comment]
Thanks @cadeyrn, I should have checked.

So, can someone with the power add the "Feature:FennecTransition" label?

Cheers 🙂

**Comment by Fidgetcetera** [comment]
Writing this *as* I waste data on images on github because my home internet dropped out, said data being rather precious and costly. This is one of those big essential "why wasn't this in when the transition happened" features for me.

**Comment by javi2man** [comment]
I was wondering if anyone has got the Google Data saver extension 's backup (.xpi file). Please! This will solve the problem, thanks!

**Comment by JP95Git** [comment]
It took me a while to find this issue. I also need this feature (again), because mobile internet is rather slow and expensive for me. uBlock Orign helps, but it has a very bad user experience:
- Either always load all images, get huge traffic and pay a lot at the end of the month.
- Or temporally unblock each website if I am using Wi-Fi.

Since I see no progress so far, I cancelled my recurring donations to Mozilla. I also started so search for a good alternative for Firefox on Android.

**Comment by W4RH4WK** [comment]
Let us know if something comes up. It's quite stupid that this feature was available at some point and hasn't been brought back.

**Comment by W4RH4WK** [comment]
> This change in about:config (you need to add the entry using the "+" button) can be used to disable image loading https://support.mozilla.org/en-US/questions/981640 It worked using Fennec on Android.

Apart from not being able to open `about:config` on Android, this is not an acceptable workaround as one has to toggle this setting manually when switching between WiFi or mobile network.

**Comment by pas-calc** [comment]
> > This change in about:config (you need to add the entry using the "+" button) can be used to disable image loading https://support.mozilla.org/en-US/questions/981640 It worked using Fennec on Android.
> 
> Apart from not being able to open `about:config` on Android, this is not an acceptable workaround as one has to toggle this setting manually when switching between WiFi or mobile network.

This is at least a workaround and it is possible to open this on Android. I can confirm this. Using Fennec on Android.

**Comment by W4RH4WK** [comment]
> This is at least a workaround and it is possible to open this on Android. I can confirm this. Using Fennec on Android.

Yeah, after some discussion I discovered that Fennec (the Firefox you get via F-Droid) allows you to access about:config. The Play Store version, however, does not; not even when you enter that _secret_ developer mode.

At this point I really wonder what the devs / Mozilla are thinking.

**Comment by B0pol** [comment]
https://github.com/mozilla-mobile/fenix/issues/810#issuecomment-683265176

It shouldn’t be only on mobile data but also on Wi-Fi if user wants, because it helps with low bandwith. So the preference should be (display images and fonts): always / Wi-Fi only / never

**Comment by benyaminl** [comment]
It's like uBo, but don't achieve the purpose when on Mobile Network. That's
the difference when on old Firefox Android...



Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807116

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
