### ISSUE TITLE
[Bug] Sometimes a recently used device disappears from the Send Tab list

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#12722]
## Steps to reproduce
Share, send a tab to synced Firefox device

### Expected behavior
List of available devices includes all recently used ones

### Actual behavior
Sometimes I find that a device has disappeared from this list for some reason, typically the other device I used most recently (portable Firefox on Win10). The other device only reappears when reload Firefox on it. This has happened a few times over the past month or so.

### Device information
* Android device: Nokia 8 on Android 9
* Fenix version: Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3657)

**Comment by ekager** [comment]
@madb1lly are you still seeing this issue?

**Comment by madb1lly** [comment]
Hi @ekager,

Yes I'm seeing it frequently but not continuously. I font know what the trigger is,  but sometimes recently used devices (plural) disappear from my list of synced devices in to the share dialogue. It is only of Fenix,  not Fennec nor desktop release or Dev on Windows nor Ubuntu. 

For example, one day last week i used 3 desktop devices,  all synced,  but then later on Fenix they have all disappeared from my sync list. Conversely, devices I've not used in months are still shown. 

This is the single most annoying bug for me at the moment as it means i need to save tabs to send later. 

Let me know if I can provide more info. 

Cheers 🙂

**Comment by madb1lly** [comment]
Hello,

This still happens and it only happens with Fenix. From Fenix the Firefox instances which disappear could be any of my other linked machines, it's not related to only a single one. It's not repeatable, i.e. I've not yet worked out how to force this to happen, but when it does happen it's always instances which I've very recently used which disappear. The way to make them appear again is to force a sync operation on both then send a tab from the disappeared on to Fenix. Fenix then receives the tab and the missing instance reappears in the sync menu. 

This workaround means I have to turn on the disappeared instance, which means I have to keep tabs open that I want to send until I can turn on that other instance and do the workaround. Sometimes this can be a few weeks if I've away for work or leave, so I end up with a huge amount of tabs open just waiting to reconnect the sync. Yes I could save them to collections but collections are not synced so there's no backup if my phone dies or is lost.

Cheers 🙂

**Comment by klakiervx** [comment]
I have the same issue. Of my two laptops and a phone, laptops often disappear from the list when I try to send some tabs from one of the other devices. Just now I can see that my private laptop disappeared from the send to list on phone and work laptop, not more than two days after I last used the private laptop.

It just happens too often that I find this feature not working as desired when I need it. Shouldn't the list on each device show all other devices logged in to the Firefox account in some reasonable amount of time (like a month or so)?

**Comment by madb1lly** [comment]
Seems to be fixed now.

**Comment by csadilek** [comment]
Thanks, closing based on https://github.com/mozilla-mobile/fenix/issues/12722#issuecomment-1326946750.
