### ISSUE TITLE
[Bug] Inconsistent recent app view when having private tabs tray opened

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#12724]
## Steps to reproduce
1. Open a tab in normal browsing.
1. Go to tabs tray and go to private mode and open a new tab in private mode.
1. Tap on tabs tray and go to normal browsing mode through tabs tray icon.
1. Go to app's homescreen, tap on tabs tray.
1. As it is in normal browsing mode put the app in recent apps.
1. Bring app in foreground and tap on on the private tabs icon.
1. Put the app in recent apps.

### Expected behavior
While the app is in recent apps it should either display a white background and remain in private browsing tabs tray when put in foreground.

### Actual behavior
After step 7 the app will display the open tabs from normal browsing mode.

### Device information
* Android device: Sony Xperia Z5 (Android 7)
* Fenix version: Nightly 200720 (Build 22020611)

<details><summary>Sony Xperia Z5 (Android 7)</summary>

![20200720-121511](https://user-images.githubusercontent.com/49859863/87923040-8a6bc080-ca85-11ea-84f0-093c25b400db.gif)
</details>

Note:

* I did not reproduce this with Google Pixel 3 XL (Android 9) neither with Samsung Galaxy S9 (Android 8)
* "Allow screenshots in private browsing" remained disabled for this testing
* Encountered issue after having tested #12453

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/8 Nightly build with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9).
