### ISSUE TITLE
[Bug] Somes Open in Browser from custom tab creates a new "instance" of Fenix in the task switcher

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#12723]
## Steps to reproduce
From a custom tab, select open in browser, then open the task switcher.

### Expected behavior
In the task switcher see a single instance of Fenix running and the custom tab closed.

### Actual behavior
Recently I was able to create 3 instances of Fenix in the task switcher! I was opening links from FairEmail app and they open in custom tabs*. I then select Open in Nightly and quickly double tap the task switcher to go back to FairEmail.

I do this a lot, to open links from emails then look through them all in Fenix, rather than wait for each custom tab to load one by one.

Over the past few days I've found odd behaviour where the task switcher shows two instances of Fenix, or in one case three instances. Even odder, the instances had different tab numbers in the tabs box even though they all had the same tabs open!

All "instances" in the task switcher seem to be the same instance of Fenix, so it is just a display issue I think.

When I select the address bar then go back to the page, the tabs number updates to the correct amount.

*I don't actually want to use custom tabs, I prefer it when links open directly in the browser. Is there a benefit to custom tabs vs the main browser? I would actually _prefer_ the tab queue from Fennec, but that appears to be MIA so far in the transition to Fenix.

### Device information
* Android device: Nokia 8 with Android 9
* Fenix version: Nightly over the past week (org.mozilla.fenix.nightly).

**Comment by madb1lly** [comment]
Hi all,
After not happening for a while this happened again last night.
Cheers 🙂

**Comment by ekager** [comment]
@madb1lly are you still seeing this recently?
