### ISSUE TITLE
FNX2-15435 ⁃ [Bug] Tab counter is not updated when opening a tab from Custom tab

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12721]
## Steps to reproduce
1. Make Firefox your default browser;
1. Open one page in Firefox;
1. Open a custom tab in Gmail. Tap the 3 dot menu.
1. Tap Open in Firefox.
    1. Expected behavior
The website is opened in Firefox and the tab counter is updated.
    1. Actual behavior
The website is opened in Firefox and the tab counter is not updated.

### Notes
![20200720](https://user-images.githubusercontent.com/48799384/87908930-f4796b00-ca6f-11ea-9352-99be7967dafa.gif)UNITO-UNDERSCORE!095929!

This is not reproducible when there are no tabs open in Firefox.

### Device information
* Android device: Motorola Moto G6 (Android 8), Google Pixel 3 XL (Android 9),
* Fenix version: Nightly 200719 Build #22010616 GV 80.0a1 from 7/19
This is also reproducible on Reference Browser https://github.com/mozilla-mobile/reference-browser/issues/1218

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 79.1.0-beta.1 (Build #22040602) GV 79 from 7/22 with Samsung Galaxy Tab S3 (Android 8).

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on on Firefox Preview Nightly 200727 (Build #22090608).
### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPap M3 (Android 7.0)
