### ISSUE TITLE
FNX2-15434 ⁃ Uplift strings from master to releases/79.0.0 branch

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#12720]
String freeze was July 18, so all the final strings should have been translated.

We'll need to uplift them in Fenix to the releases/79.0.0 branch, and if there are any strings that need to be translated in AC, those will also have to be done in an AC dot release.

We plan to cut the RC candidate July 20.

**Comment by liuche** [comment]
@pocmo cc-ing you here, and if you need someone to pick this up from you afterwards, please let me know!

**Comment by pocmo** [comment]
On it.

**Comment by pocmo** [comment]
> We plan to cut the RC candidate July 20.

Note that we do not have a final GeckoView 79 release until a bit later this week. So technically if we cut a build today then this will not really be an "RC".

**Comment by pocmo** [comment]
String uplifts in AC:
https://github.com/mozilla-mobile/android-components/pull/7773

**Comment by pocmo** [comment]
String uplifts Fenix:
https://github.com/mozilla-mobile/fenix/pull/12725

**Comment by pocmo** [comment]
This was also uplifted to AC 48:
https://github.com/mozilla-mobile/android-components/pull/7734

**Comment by pocmo** [comment]
I am not fully sure if I should make an AC dot release yet: We do not have the final release version of GeckoView yet. If we use the existing versions (for a beta?!)... would we need two releases again?

**Comment by liuche** [comment]
Chatted with Eric Smythe and RyanVM today, and while we only need one GV version, we are waiting on some results from the perf experiment in order to decide which build-flag version we want to use for release.

One thing I'm thinking...I just checked the previous L10N automated update and it looks like it was on Friday (rather than Saturday, the L10N cutoff) so we may have missed importing some strings: https://github.com/mozilla-mobile/fenix/pull/12687#issue-451566550

Is the script something that's easy to run again, or is it harder now that some strings have already been uplifted?

**Comment by pocmo** [comment]
The script is in the AC repository: https://github.com/mozilla-mobile/android-components/blob/master/l10n-uplift.py
It worked fine with AC, but I got a bunch of conflicts with Fenix. So I ended up copying the strings over manually for Fenix (and that's how the erroneous styles.xml ended up in the PR). I can do that again today.

**Comment by pocmo** [comment]
Okay, uplifted the L10N update form #12687.
