### ISSUE TITLE
FNX-13838 ⁃ [Bug] The ripple for the "Font Size" option in the Accessibility menu is not fully displayed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#12730]
## Steps to reproduce
1. Access Accessibility in the settings.
1. Tap on the `Automatic font sizing`.
1. Tap and hold on the `Font Size` option.
    1. Expected behavior
The ripple for the `Font Size` option is fully displayed.
    1. Actual behavior
The ripple for the `Font Size` option in the Accessibility menu is not fully displayed
    1. Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 7/20.**

![20200720-144149](https://user-images.githubusercontent.com/42831109/87947619-43dd8c80-caac-11ea-8898-d91ccafebc96.gif)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/24 with Google Pixel 4 XL (Android 11).
