### ISSUE TITLE
FNX2-15445 ⁃ [Bug] Closed tab comes back when navigating back to home screen

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#12735]
## Steps to reproduce
1. Close a tab
1. Press the "undo" button on the snackbar
1. Press "back" (android nav)

### Expected behavior
1. I am on the home screen and my tab sticks around

### Actual behavior
1. I am on the home screen and the tab gets removed again.

This is happening because our navigation flags are not getting reset when we press back.

**Comment by sblatz** [comment]
## New behavior

![new behavior 2020-07-20 10_28_22](https://user-images.githubusercontent.com/4400286/87967515-c7c75280-ca73-11ea-8893-d86edfb8341e.gif)

**Comment by Diana-Rus** [comment]
Hello, verified as fixed, with Google Pixel 3XL (Android 9) and with Samsung Galaxy S9 (Android 8) it happens as per [comment](https://github.com/mozilla-mobile/fenix/issues/12735#issuecomment-661238336)
<details closed><summary>Google Pixel 3XL (Android 9)</summary>

![20200727-124046](https://user-images.githubusercontent.com/49859863/88527800-6c163f80-d006-11ea-8125-2b8b113f733b.gif)
</details>
