### ISSUE TITLE
[Design] Download notification accent color

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12732]
As @Amejia481 decided in https://github.com/mozilla-mobile/fenix/issues/12226#issuecomment-661069684 we're gonna stick with default notification.
Next thing @brampitoyo needs to decide is should we use fenix's accent color or let android use its own accent color https://github.com/mozilla-mobile/fenix/issues/12226#issuecomment-660899262.

**Comment by Amejia481** [comment]
One drawback of changing the accent colour is that icon also change not only the buttons.

### With default colour


**Normal theme**
![image](https://user-images.githubusercontent.com/773158/87952552-f21b0f00-ca77-11ea-99ec-bdb206b9bc53.png)

**Dark theme**
![image](https://user-images.githubusercontent.com/773158/87952945-681f7600-ca78-11ea-96e0-8c656e3c2c91.png)


___________________________





### With accent colour

**Normal theme**

![image](https://user-images.githubusercontent.com/773158/87952277-a10b1b00-ca77-11ea-8976-4526d5232eed.png)


**Dark theme**
![image](https://user-images.githubusercontent.com/773158/87950937-f3e3d300-ca75-11ea-88c4-0380c8f465a5.png)

**Comment by hakkikaancaliskan** [comment]
Also i saw from your screenshots, why not to add a "x time left" indicator?

**Comment by Amejia481** [comment]
> @Amejia481 what if we set color of that icons to our accent color?

In my opinion, I would prefer in the normal default icon colour for the normal theme, but I guess it's a matter of preference, but in dark theme the accent colour looks pretty cool, in the icon and buttons!

**Normal theme**

![image](https://user-images.githubusercontent.com/773158/87952277-a10b1b00-ca77-11ea-8976-4526d5232eed.png)

___________________________

**Dark theme**
![image](https://user-images.githubusercontent.com/773158/87950937-f3e3d300-ca75-11ea-88c4-0380c8f465a5.png)



The twitter app is changing the default accent colour and it looks pretty nice

![image](https://user-images.githubusercontent.com/773158/87955467-cbf76e00-ca7b-11ea-83b3-40979a913b25.png)

**Comment by Amejia481** [comment]
> Also i saw from your screenshots, why not to add a "x mins left" indicator?

I think this one will be a separate feature request ticket :)

**Comment by hakkikaancaliskan** [comment]
Agree with you they're soooo cool. I'm also on your side :)

**Comment by ShatteredPixel** [comment]
Hey guys, please don't leave me alone... 🥺

Please tell me what's going too (I can already see what's going on though, so actually no need tell 😅)

:)

**Comment by hakkikaancaliskan** [comment]
@Amejia481 #12734 opened issue
I've take a look at chromium source but unable to find how they added :(
Also unable to find online.

**Comment by brampitoyo** [comment]
@Amejia481 @hakkikaancaliskan As long as we get the same icon animation (which is important to indicate visually that “something is going on”), I think the accent colour looks great!

Just making sure that our values are correct:

Light theme:
- Accent: Violet 70 `#592acb`

Dark theme:
- Accent: Violet 40 `#ab71ff`

**Comment by hakkikaancaliskan** [comment]
@brampitoyo Currently light theme is correct but dark is set to `#815BDD`
And best part is i can't find where we set accent color in fenix lol

**Comment by Amejia481** [comment]
I think for themes Fenix is using attributes, the accent colour is represented using `R.attr.accent` this property will update accordingly to the theme that fenix has light or dark, you can find [an example of using it here](https://github.com/mozilla-mobile/fenix/blob/808584b75ffc6265bb31d60db36fc63e64f6cc78/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt#L149)

**Comment by hakkikaancaliskan** [comment]
> I think for themes Fenix is using attributes, the accent colour is represented using `R.attr.accent` this property will update accordingly to the theme that fenix has light or dark, you can find [an example of using it here](https://github.com/mozilla-mobile/fenix/blob/808584b75ffc6265bb31d60db36fc63e64f6cc78/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt#L149)

I know that but i mean where do we send accent color to ac for download notification?

**Comment by Amejia481** [comment]
Oh, sorry 😅 . We are not actually doing that now as it was not needed it before. Now we will have to implement it.
For changing the style colour on the notification, we need to expose an styling object from AC that Fenix can pass to the [AbstractFetchDownloadService](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L84) similar to what we are doing on [AddonsManagerAdapter#Style](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L328).
An example can be how we pass[ the store and the httpClient](https://github.com/mozilla-mobile/fenix/blob/9c4fba45659a29d679eaea7fbc68a6e1b5e4fb1d/app/src/main/java/org/mozilla/fenix/downloads/DownloadService.kt#L12). Hope it helps

**Comment by hakkikaancaliskan** [comment]
> Oh, sorry 😅 . We are not actually doing that now as it was not needed it before. Now we will have to implement it.
> For changing the style colour on the notification, we need to expose an styling object from AC that Fenix can pass to the [AbstractFetchDownloadService](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L84) similar to what we are doing on [AddonsManagerAdapter#Style](https://github.com/mozilla-mobile/android-components/blob/84d7a0f74ffda33b169d8f258f926b3314219576/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L328).
> An example can be how we pass[ the store and the httpClient](https://github.com/mozilla-mobile/fenix/blob/9c4fba45659a29d679eaea7fbc68a6e1b5e4fb1d/app/src/main/java/org/mozilla/fenix/downloads/DownloadService.kt#L12). Hope it helps

I don't have time currently but someone maybe work on this.

**Comment by hakkikaancaliskan** [comment]
@Amejia481 I did this without using data class. I'll open pr for both on AC and fenix. Could you please review them?

**Comment by hakkikaancaliskan** [comment]
@Amejia481 I've did with data class. Could you please review them?
AC side: https://github.com/mozilla-mobile/android-components/pull/9300
Fenix side: https://github.com/mozilla-mobile/fenix/pull/17231

**Comment by Amejia481** [comment]
> @Amejia481 I've did with data class. Could you please review them?
> AC side: https://github.com/mozilla-mobile/android-components/pull/9300
> Fenix side: https://github.com/mozilla-mobile/fenix/pull/17231

Hi @hakkikaancaliskan I'm on PTO spending some quality time with family and friends during the holidays 🙂. I know others team members that are available will review, be aware reviews could take a bit longer as many people are on PTO too.
Happy holidays!

**Comment by hakkikaancaliskan** [comment]
> > @Amejia481 I've did with data class. Could you please review them?
> > AC side: https://github.com/mozilla-mobile/android-components/pull/9300
> > Fenix side: https://github.com/mozilla-mobile/fenix/pull/17231
> 
> Hi @hakkikaancaliskan I'm on PTO spending some quality time with family and friends during the holidays 🙂. I know others team members that are available will review, be aware reviews could take a bit longer as many people are on PTO too.
> Happy holidays!

Ohh of course, I was expecting to be reviewed after holiday already, happy new year to all team members :)

See you after holiday ☺️ have a good time

**Comment by hakkikaancaliskan** [comment]
We fixed this but qa needed?

**Comment by Amejia481** [comment]
Sorry about that, I tagged the QA for verification, thanks for remind me it :)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 1/29 Nightly build, and Beta 86.0.0-beta.1 build. On RC 85.1.1 is not implemented yet.
Tested with several devices: 
* Google Pixel (Android 10),
* Samsung Galaxy Note 8 (Android 9), and
* Sony Xperia Z5 Premium (Android 7.1.1).

![Untitled](https://user-images.githubusercontent.com/40694158/106267460-56dad180-6232-11eb-8b82-3dc69d3251e5.png)

Thanks!
