### ISSUE TITLE
Add narration feature to Reader Mode

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#1273]
### Why/User Benefit/User Problem
This is a huge accessibility boon, enabling visually impaired users to access articles via Firefox.

### What / Requirements
We need UX direction, basically we need a TTS icon. With that and placement in the UI of #190  we can accept a pull request. In terms of how the feature acts and interacts, I suggest following what we do on desktop.

### Acceptance Criteria (how do I know when I’m done?)
Icon
Placement
Okay to follow desktop UX.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3665)

**Comment by NotWoods** [comment]
We could possibly incorporate [Firefox Listen](https://labs.mozilla.org/projects/firefox-listen/) here.

**Comment by pwd-github** [comment]
No thank you. Not unless they add some sort of caption service. Being able to see what's being read (the current desktop system) is far more useful than what's available in Firefox Listen.

**Comment by b3n63r** [comment]
I am not elderly but I have issues with reading long texts. On desktop I use this feature on daily basis. I would love to have the narration feature in Reader Mode on android too. Thank you!

**Comment by HubKing** [comment]
Please add this feature. The feature already exists on FireFox desktop, and Microsoft's Edge browser already has this feature even on Android. I think Edge uses Microsoft's cloud service (Azure)'s AI voice. Their voices are very natural and nice. The only problem is that Edge's reader is stupid (it narrows the view to the ridiculous level with huge margins if I increase the font size) and it covers the entire page with some gray layer to highlight the currently-spoken word, which I think is stupid.

Android FireFox could use Android's in-built TTS, whose quality is acceptable, or it could use some cloud service for better and more natural voice. I am willing to pay for that.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807378

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kuanyui** [comment]
Curious why close this issue on GitHub when this issue has not been
resolved yet? I never seen any other issue in mozilla-mobile/fenix do like
this... The other issues are always opened, even if bugzilla has a ticket,
until the issue is really resolved. For example:

https://github.com/mozilla-mobile/fenix/issues/16585
https://bugzilla.mozilla.org/show_bug.cgi?id=1538348

2022年12月24日(土) 5:05 Chris Peterson ***@***.***>:

**Comment by cpeterso** [comment]
@kuanyui This GitHub issue was closed because we're moving Firefox issue tracking from GitHub to Bugzilla. See https://github.com/mozilla-mobile/fenix/issues/26855 for more information.

We'll track this narration feature in Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1807378
