### ISSUE TITLE
FNX2-15449 ⁃ [Bug] Failed to Query Addons

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12745]
## Steps to reproduce
Open addons

### Expected behavior
Shows the add ons 

### Actual behavior
Failed to Query Addons error 

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200720 06:02 (Build #22020612)
AC: 51.0.20200719130512, e38c71e17
GV: 80.0a1-20200717093907
AS: 61.0.10

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/12399
