### ISSUE TITLE
Decide what the correct UX behavior is for system level login management

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#12743]
If your system level password manager saves logins correctly via Firefox, you can get into a situation like this when entering a new login:

![image (8)](https://user-images.githubusercontent.com/25442310/87975366-877acb00-ca99-11ea-9cb7-38311a7b18d0.png)

I am wary of suppressing the system level solution here (because users likely have a third party password manager because they use it and prefer to save logins there). Additionally, users can currently turn off saving logins in Firefox via Settings. 

Maybe the correct answer is do nothing (or maybe show a CTA to turn off logins saving if a user doesn't save logins more than X times) 🤷

**Comment by cadeyrn** [comment]
See also #7739.
