### ISSUE TITLE
FNX-13876 ⁃ Separate release locale list from master locale list.

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#12759]
We use `l10n.toml` to define what locales to include in our builds. For release we want to use a separate list of locales than on the master branch. To allow us to have the same `l10n.toml` file on `master` and release branches we should create a separate list that is used to filter out locales on release builds. We can't modify [this](https://github.com/mozilla-mobile/fenix/blob/09d0688e6483d0e2ca33009c7a77855f29b9556d/l10n.toml#L4) list on `master` because Pontoon uses it to expose locales to translators.

**Comment by person808** [comment]
Note for QA: we want to check that the apk from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.fennec-production) should have only the locales in [`l10n-release.toml`](https://github.com/mozilla-mobile/fenix/blob/master/l10n-release.toml) in future builds. If we can verify the locale filter is running on one build in TC then it should be working for all build variants its needed for.

**Comment by softvision-miralobontiu** [comment]
Verified all the languages from the locales in [l10n-release.toml](https://github.com/mozilla-mobile/fenix/blob/master/l10n-release.toml), on the build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.fennec-production.latest/arm64-v8a) with OnePlus 5T (Android 9).
Three languages are missing on the build from above, but **they are available on the 7/27 Nightly build**:
1. Hebrew "he".
2. Bahasa Indonesia "id".
3. Triqui "trs".

I'll remove the qa:needed label for now.
@person808 please let us know if there is anything else we can do.
Thanks!

**Comment by person808** [comment]
Likely just a delay in pulling in the translations thanks!
