### ISSUE TITLE
FNX2-15453 ⁃ Clean up incorrect XML uses of `@+id`

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#12755]
In our XML files there are two similar ways to refer to IDs: `@+id/example_id` and `@id/example_id`. The "plus" variant should only be used to create a new ID, and should only be used inside `android:id`. 

In other attributes, the ID is used to reference another value (such as `app:destination`, `app:layout_constraintStart_toStartOf`). In these locations, the `@id` variant with no plus should be used. Incorrect usage doesn't have runtime issues, but makes the IDE confused sometimes.

We may want to create a lint rule for this later on.

**Comment by leonardoamurca** [comment]
Hi @NotWoods! Can I help you with these changings as my `good first issue` ?

**Comment by NotWoods** [comment]
Sure @leonardoamurca! Please look through our docs so you can check out a copy of the codebase locally and edit it with Android Studio. Let me know if you need tips for how to proceed with the changes.

**Comment by NotWoods** [comment]
Closing since this has been fixed by @leonardoamurca 😄
