### ISSUE TITLE
FNX-13879 ⁃ Code such as withText("Get the most out of Firefox Preview.") won't work on non English localized versions

### ISSUE THREAD

**Issue by greenorion** [mozilla-mobile/fenix#12763]
## Steps to reproduce
app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Line 553
    onView(allOf(withText("Get the most out of Firefox Preview.")))

I don't see how this could possibly work when the view object's text is localized to non English regions. And there are several examples of this sort of thing in this file.

**Comment by liuche** [comment]
These are for testing only, and we only run CI on en-US because it's not feasible to run tests on every single locale.
