### ISSUE TITLE
FNX2-15462 ⁃ Intermittent UI test failure - TabbedBrowsingTest.closeTabTest & closePrivateTabTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12778]
Don't have a test run/report, but I found that these 2 tests have been disabled without any issue for reference: https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt#L144
This ticket is about investigating, fixing, and re-enabling the closeTabTest & closePrivateTabTest in TabbedBrowsingTest.kt.

**Comment by rpappalax** [comment]
add logs to issue (if still failing), add longTabDelay - see: 3dotMenuItemsTest)

**Comment by rpappalax** [comment]
Re-ran both tests 30x each and all failed.  Looks like they're both failing for a missing/changed ID.

**closeTabTest**

Firebase:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6405713151126449495/executions/bs.a652c9dca6f9bce4/testcases/1/test-cases

logcat:

```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/tabsTray
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATI
```

**closePrivateTabTest**
Firebase:

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8264247305427389450/executions/bs.6f22a8b101816fc3/testcases/1/test-cases

logcat:

``` 
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/tabsTray
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f140329
fl=LAYOUT_IN_SCREEN SECURE LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
```

**Comment by sv-ohorvath** [comment]
The tabs drawer is hidden after closing the last tab so you need to re-open the tab drawer to see the tab restored with Undo.
Modified the steps and should be fixed now. PR is ready for review.
