### ISSUE TITLE
FNX2-15461 ⁃ [Collections] Rename and move entries in a collection

### ISSUE THREAD

**Issue by Furax-31** [mozilla-mobile/fenix#12775]
I propose to add the possibility of renaming and classifying our bookmarks in the collections. I have created a lot of collections, and I would like to be able to sort them as I wish. 

Excuse me if this topic has already been created, but I couldn't find anything in the search.

Have a good day.

**Comment by Dunexus** [comment]
Hello,
Thank you for your feedback. I think this is already covered by https://github.com/mozilla-mobile/fenix/issues/3751

**Comment by eliserichards** [comment]
@Furax-31 sorry for the confusion, is this referring to editing bookmarked sites, or editing saved sites in a Collection?

**Comment by Furax-31** [comment]
@eliserichards editing saved sites in  collection.

Sorry for my english ^^

**Comment by liuche** [comment]
Thanks! Going to dupe this to #3751 and please follow along there.
