### ISSUE TITLE
FNX2-15459 ⁃ [Bug] Cannot open file after download is complete

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#12772]
## Steps to reproduce
Only reproduceable on Android 10 (possibly on Android 11 also)

* start a download (for any type of file), wait for the download to complete
* try to open the just downloaded file from the dialog / notification

### Expected behavior
Assuming an app that can open that file is installed the file should be opened.

### Actual behavior
The file is tried to be opened by 3rd party apps, opening fails.

### Device information
* Android device: Pixel 3, Android 10
* Fenix version: latest Nightly

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 7/29, with Google Pixel (Android 10).
I've downloaded a .pdf file, a .avi file, a .mov file, a .jpg file, for which I had the proper apps installed.
I was able to open all the downloaded files from the notification.

**Comment by Mugurell** [comment]
Closing as per https://github.com/mozilla-mobile/fenix/issues/12772#issuecomment-665713574
