### ISSUE TITLE
FNX-4920 ⁃ White on white address bar for LinkedIn custom tab

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1277]
Fenix is set as default browser. 
Open LinkedIn app
Open web link within LinkedIn
website is opened in custom tab
Blue LinkedIn color scheme applied but address bar text color is difficult to read (white on white)

**Comment by bbinto** [comment]
https://www.dropbox.com/s/v55s8g1rjdjrffh/Screenshot_20190330-125417.png?dl=0

**Comment by yoasif** [comment]
My similar #1037 was closed because: 

>Will be addressed in #668

**Comment by vesta0** [comment]
Should be fixed by #668

**Comment by bsurd** [comment]
Verified on Honor 8 and Note 8 devices. A blue color scheme is applied all over now and the white text is easy to read.
