### ISSUE TITLE
FNX-4921 ⁃ Add 'Are you sure' prompt before deleting history

### ISSUE THREAD

**Issue by DoggoOfSpeed** [mozilla-mobile/fenix#1278]
### Why/User Benefit/User Problem
This will prevent accidental history deletion

### What / Requirements
A pop-up saying 'Are you sure? 

### Acceptance Criteria (how do I know when I’m done?)
When there is a prompt

**Comment by vesta0** [comment]
Thanks for the feature request. Will take into consideration when user testing the history component.
