### ISSUE TITLE
[Bug] zooming in on certain media like gifs cannot be reversed

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12798]
## Steps to reproduce
Click on the below link and open it in new tab
https://user-images.githubusercontent.com/1370580/88098459-cecf8d00-cb67-11ea-8453-cf7ffa83af4d.gif 
Zoom in
Try to zoom out

### Expected behavior
Can return to original position

### Actual behavior
Can't return to original position. Bottom bar now hides part of image forever

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by ekager** [comment]
@s-ankur can you still repro in Nightly?

**Comment by s-ankur** [comment]
@ekager original bug seems to be fixed on latest nightly. However, scrolling out on a scrolled in image results in a white bar (you can scroll to get dynamic bar back). Perhaps this is a seperate issue
![Screenshot_20200801-194420_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/89103520-1db2d780-d430-11ea-8c14-020efcea3e6d.png)

**Comment by s-ankur** [comment]
The white bar issue seems to be #11389

**Comment by ekager** [comment]
Yeah unfortunately the fix for this issue revealed another problem https://bugzilla.mozilla.org/show_bug.cgi?id=1652190#c8 

Filed here: https://github.com/mozilla-mobile/android-components/issues/7718

**Comment by ebalazs-sv** [comment]
This is still reproducible on Nightly 200804 Build #22170943 GV 81.0a1 from 8/4 with Pixel 2 (Android 9). I will remove the qa:needed label for now.
![20200804_143532](https://user-images.githubusercontent.com/48799384/89290064-f1ca6880-d660-11ea-9116-9c4eac5abbc9.gif)
