### ISSUE TITLE
FNX-13916 ⁃ [Regression] Search Engine shortcut is hidden

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12792]
## Steps to reproduce
Tap to search bar

### Expected behavior
There is search engine shortcut  at the right of scan shortcut

### Actual behavior
Its hidden.

![Screenshot](https://user-images.githubusercontent.com/17825767/88091143-52ed3900-cb97-11ea-8ced-c31c6cdda848.jpg)UNITO-UNDERSCORE!20200721-211231!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly.jpg!

### Device information
* Android device: XZ1, Android 10
* Fenix version: 21/7 nightly

**Comment by Augures01** [comment]
Not a bug
https://github.com/mozilla-mobile/fenix/pull/12188

**Comment by hakkikaancaliskan** [comment]
@Augures01 thanks
