### ISSUE TITLE
FNX2-15466 ⁃ [Bug] Restore closed tab snackbar not visible

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12791]
## Steps to reproduce
Open a tab
Open tab tray
Close tab

### Expected behavior
Tab and tab tray gets closed and snack bar shown

### Actual behavior
Tab and tab tray closed but snack bar not shown

It's visible if you close tabs with "close all tabs".

### Device information
* Android device: XZ1, Android 10
* Fenix version: 21/7 nightly

**Comment by hakkikaancaliskan** [comment]
@sblatz possibly related to #12615

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200727 from 7/27`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200728-092023](https://user-images.githubusercontent.com/51314259/88626907-1a2bf300-d0b4-11ea-9bd0-06beb8251668.gif)
