### ISSUE TITLE
FNX-4923 ⁃ [Bug] History does not load, Fenix freezes

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1280]
## Steps to reproduce
1. Launch Fenix
1. Navigate to Library > History

### Expected behavior
History loads.

### Actual behavior
Fenix freezes.

logcat: 

03-30 15:52:26.255 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.271 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.330 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 90 lines
03-30 15:52:26.330 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.431 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.453 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.498 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 80 lines
03-30 15:52:26.498 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.593 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.602 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.649 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 68 lines
03-30 15:52:26.649 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.726 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.726 I/g.mozilla.feni(4165): Clamp target GC heap from 215MB to 192MB
03-30 15:52:26.726 I/g.mozilla.feni(4165): Alloc concurrent copying GC freed 1(40B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 284us total 2.125s
03-30 15:52:26.726 I/g.mozilla.feni(4165): WaitForGcToComplete blocked Alloc on HeapTrim for 4.181s
03-30 15:52:26.726 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:26.726 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:26.727 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.728 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.728 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.728 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.728 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.728 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.728 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.730 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.737 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:26.748 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.763 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 24 lines
03-30 15:52:26.763 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.768 I/x8bit.bitwarde(2860): Explicit concurrent copying GC freed 30146(1479KB) AllocSpace objects, 0(0B) LOS objects, 59% free, 1064KB/2MB, paused 119us total 18.050ms
03-30 15:52:26.800 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:26.835 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 12 lines
03-30 15:52:26.835 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:29.106 I/g.mozilla.feni(4165): Clamp target GC heap from 215MB to 192MB
03-30 15:52:29.106 I/g.mozilla.feni(4165): Alloc concurrent copying GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 122us total 2.379s
03-30 15:52:29.106 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:29.106 I/g.mozilla.feni(4165): WaitForGcToComplete blocked Alloc on HeapTrim for 8.496s
03-30 15:52:29.106 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:29.106 I/g.mozilla.feni(4165): WaitForGcToComplete blocked Alloc on HeapTrim for 6.559s
03-30 15:52:29.106 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.107 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:29.826 W/ActivityManager(1153): Activity stop timeout for ActivityRecord{c4f2b11 u0 org.mozilla.fenix/.HomeActivity t1596}
03-30 15:52:31.236 I/g.mozilla.feni(4165): Clamp target GC heap from 215MB to 192MB
03-30 15:52:31.236 I/g.mozilla.feni(4165): Alloc concurrent copying GC freed 5(104B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 257us total 2.129s
03-30 15:52:31.237 I/g.mozilla.feni(4165): WaitForGcToComplete blocked Background on HeapTrim for 8.691s
03-30 15:52:31.237 I/g.mozilla.feni(4165): WaitForGcToComplete blocked Alloc on HeapTrim for 6.630s
03-30 15:52:31.237 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:31.237 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:31.237 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:31.238 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:31.238 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:31.238 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:31.238 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:31.238 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:31.238 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:31.242 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.462 I/g.mozilla.feni(4165): Clamp target GC heap from 215MB to 192MB
03-30 15:52:33.462 I/g.mozilla.feni(4165): Alloc concurrent copying GC freed 3(88B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 278us total 2.224s
03-30 15:52:33.462 I/g.mozilla.feni(4165): WaitForGcToComplete blocked Alloc on HeapTrim for 7.207s
03-30 15:52:33.462 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:33.462 V/chatty  (4165): uid=10279(org.mozilla.fenix) Thread-4 identical 1 line
03-30 15:52:33.463 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.467 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:33.869 D/MDTintHelper(4100): Device issue with cursor tinting: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
03-30 15:52:33.869 W/System.err(4100): java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
03-30 15:52:33.869 W/System.err(4100): 	at java.lang.Class.getDeclaredField(Native Method)
03-30 15:52:33.869 W/System.err(4100): 	at com.afollestad.materialdialogs.internal.MDTintHelper.setCursorTint(MDTintHelper.java:183)
03-30 15:52:33.869 W/System.err(4100): 	at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:171)
03-30 15:52:33.869 W/System.err(4100): 	at com.afollestad.materialdialogs.DialogInit.setupInputDialog(DialogInit.java:527)
03-30 15:52:33.869 W/System.err(4100): 	at com.afollestad.materialdialogs.DialogInit.init(DialogInit.java:346)
03-30 15:52:33.869 W/System.err(4100): 	at com.afollestad.materialdialogs.MaterialDialog.<init>(MaterialDialog.java:92)
03-30 15:52:33.869 W/System.err(4100): 	at com.afollestad.materialdialogs.MaterialDialog$Builder.build(MaterialDialog.java:2183)
03-30 15:52:33.869 W/System.err(4100): 	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2188)
03-30 15:52:33.869 W/System.err(4100): 	at com.pluscubed.logcat.helper.DialogHelper.showFilenameSuggestingDialog(DialogHelper.java:141)
03-30 15:52:33.869 W/System.err(4100): 	at com.pluscubed.logcat.ui.LogcatActivity.showSaveLogDialog(LogcatActivity.java:1339)
03-30 15:52:33.869 W/System.err(4100): 	at com.pluscubed.logcat.ui.LogcatActivity.onOptionsItemSelected(LogcatActivity.java:627)
03-30 15:52:33.869 W/System.err(4100): 	at android.app.Activity.onMenuItemSelected(Activity.java:3544)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:90)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
03-30 15:52:33.869 W/System.err(4100): 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
03-30 15:52:33.869 W/System.err(4100): 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
03-30 15:52:33.869 W/System.err(4100): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
03-30 15:52:33.869 W/System.err(4100): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
03-30 15:52:33.869 W/System.err(4100): 	at android.widget.AbsListView$3.run(AbsListView.java:4052)
03-30 15:52:33.869 W/System.err(4100): 	at android.os.Handler.handleCallback(Handler.java:873)
03-30 15:52:33.869 W/System.err(4100): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-30 15:52:33.869 W/System.err(4100): 	at android.os.Looper.loop(Looper.java:193)
03-30 15:52:33.869 W/System.err(4100): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
03-30 15:52:33.869 W/System.err(4100): 	at java.lang.reflect.Method.invoke(Native Method)
03-30 15:52:33.869 W/System.err(4100): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-30 15:52:33.869 W/System.err(4100): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-30 15:52:33.885 D/SurfaceFlinger(607): duplicate layer name: changing com.pluscubed.matlog/com.pluscubed.logcat.ui.LogcatActivity to com.pluscubed.matlog/com.pluscubed.logcat.ui.LogcatActivity#1
03-30 15:52:33.899 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:33.969 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 126 lines
03-30 15:52:33.969 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:33.979 I/AssistStructure(4100): Flattened final assist data: 8852 bytes, containing 3 windows, 36 views
03-30 15:52:33.981 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:34.006 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 112 lines
03-30 15:52:34.006 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:34.006 I/AssistStructure(1153): Flattened final assist data: 8484 bytes, containing 3 windows, 36 views
03-30 15:52:34.006 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:34.007 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 4 lines
03-30 15:52:34.007 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:34.019 I/KeyboardViewUtil(1590): systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
03-30 15:52:34.019 I/AndroidIME(1590): LatinIme.onActivate() : EditorInfo = Package = com.pluscubed.matlog : Type = Text : Learning = Disable : Suggestion = Hide : AutoCorrection = Disable : Microphone = Show : NoPersonalizedLearning = Disable
03-30 15:52:34.022 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:34.043 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 60 lines
03-30 15:52:34.043 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:34.044 D/SurfaceFlinger(607): duplicate layer name: changing Surface(name=996c51c com.pluscubed.matlog/com.pluscubed.logcat.ui.LogcatActivity)/@0x60a14ab - animation-leash to Surface(name=996c51c com.pluscubed.matlog/com.pluscubed.logcat.ui.LogcatActivity)/@0x60a14ab - animation-leash#1
03-30 15:52:34.044 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:34.047 V/chatty  (4100): uid=10293(com.pluscubed.matlog) identical 22 lines
03-30 15:52:34.047 V/StaticLayout(4100): maxLineHeight should not be -1.  maxLines:1 lineCount:1
03-30 15:52:34.189 D/OpenGLRenderer(4100): endAllActiveAnimators on 0x74cbfdf400 (MenuPopupWindow$MenuDropDownListView) with handle 0x74d01d9d20
03-30 15:52:35.570 I/g.mozilla.feni(4165): Clamp target GC heap from 215MB to 192MB
03-30 15:52:35.571 I/g.mozilla.feni(4165): Alloc concurrent copying GC freed 1(32B) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 118us total 2.107s
03-30 15:52:35.571 I/g.mozilla.feni(4165): WaitForGcToComplete blocked Alloc on HeapTrim for 8.844s
03-30 15:52:35.571 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:35.571 I/g.mozilla.feni(4165): Starting a blocking GC Alloc
03-30 15:52:35.571 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:35.573 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:35.574 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:35.574 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:35.574 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:35.574 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:35.574 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:35.574 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc
03-30 15:52:35.574 I/g.mozilla.feni(4165): Waiting for a blocking GC Alloc

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1913 #10891214

**Comment by vesta0** [comment]
[adding more details]

After it stays frozen for a minute (and is not force closed) Fenix will crash.
