### ISSUE TITLE
FNX2-15475 ⁃ [Bug] When there is one search engine, height is lower than 48dp

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#12804]
![Screenshot](https://user-images.githubusercontent.com/17825767/88106028-81760e80-cbad-11ea-95cd-9ba623f05547.png)UNITO-UNDERSCORE!20200721-235034!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

**Comment by hakkikaancaliskan** [comment]
@ekager qa needed

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/27 with Xiaomi Redmi Note 8T (Android 9).
