### ISSUE TITLE
FNX2-15470 ⁃ Turn off secret debug click listener if the debug menu is already enabled

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#12801]
Minor polish work. I'd like to additionally move some logic out of the fragment so that it can be tested.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200724 (Build #22060613).
*** Devices used:
- OnePlus6T (Android 9)
- Huawei P Smart (Android 9)
