### ISSUE TITLE
FNX2-15481 ⁃ [Feature Request] Let us sort/arrange collections (and bookmarks!) via drag 'n drop.

### ISSUE THREAD

**Issue by x2k13** [mozilla-mobile/fenix#12817]
### What is the user problem or growth opportunity you want to see solved?
Collections can't be sorted/rearranged manually, this should be possible, preferrably via drag 'n drop.

### How do you know that this problem exists today? Why is this important?
Collections can't be sorted/rearranged to the users liking.

### Who will benefit from it?
Practically everyone using Firefox Preview.

**Comment by cadeyrn** [comment]
Duplicate of #4348 (bookmarks) and #3751 (collections).

**Comment by x2k13** [comment]
> Duplicate of #4348 (bookmarks) and #3751 (collections).

No, it's no duplicate. I was talking about rearranging the collections as such, not just entries within. The linked issue refers to items inside collections.

**Comment by cadeyrn** [comment]
Then it's a duplicate of #8141.

**Comment by x2k13** [comment]
> Then it's a duplicate of #8141.

True. Nevertheless, it apparently is a high-demand feature missing. Sorry for duplicate.

**Comment by mcarare** [comment]
Closing as duplicate.
