### ISSUE TITLE
FNX2-15480 ⁃ [Feature Request] Sync collections via Firefox account

### ISSUE THREAD

**Issue by x2k13** [mozilla-mobile/fenix#12816]
### What is the user problem or growth opportunity you want to see solved?
At the moment, collections are not synced via a Firefox account. If the App has to be reset/reinstalled, all collections are gone.

### How do you know that this problem exists today? Why is this important?
Collections are not synced. Had to find out the hard way after clearing the app data.

### Who will benefit from it?
Practically everyone using Firefox Preview.

**Comment by cadeyrn** [comment]
Duplicate of #6512.

**Comment by mcarare** [comment]
Thank you for your suggestion @x2k13! Closing this, as it is already tracked in #6512 .
