### ISSUE TITLE
Youtube video cut off in fullscreen

### ISSUE THREAD

**Issue by howdyhamster** [mozilla-mobile/fenix#12818]
## Steps to reproduce
I go to a youtube video, rotate the phone to landscape, and hit fullscreen.

### Expected behavior
On a 1080 x 2300 screen, the video should display in 1080p with bars on the sides.

### Actual behavior
There is a small bar on the left side where the notification bar would be, but other than that the video fills the rest of the width, cutting off the bottom.
Screenshots are available at https://imgur.com/a/ryzRs8S
Issue was first reported on reddit at https://www.reddit.com/r/firefox/comments/hv1nz1/

### Device information
Motorola Moto G Power running Android 10

* Android device: Motorola Moto G Power running Android 10
* Fenix version: The issue occurs in both Firefox 68.10.1 and Firefox Beta 79.0.0-beta.9

**Comment by kbrosnan** [comment]
Duplicate #8252
