### ISSUE TITLE
FNX-4924 ⁃ Find in Page in a Custom Tab

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1281]
Dependent on https://github.com/mozilla-mobile/android-components/issues/2699

### Acceptance Criteria
I can use the find in page feature to find a word on a site that is opened in a custom tab.

**Comment by jonalmeida** [comment]
This should be fixed in tomorrow's A-C 0.54.0 snapshot. (Fenix is currently on 0.53.0)

**Comment by softvision-miralobontiu** [comment]
Verified that the "Find in page" option works in Custom tab, on the latest build 1.0.1921 (#11440149), with Google Pixel (Android 9), Nexus 5 (Android 6.0.1, and Sony Xperia Z5 Premium (Android 7.1.1)
