### ISSUE TITLE
[Spike] Android 11: Scoped storage

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#12822]
Based on the current cycle targeting Android 11 is expected to be a requirement in Q3 2021 - https://support.google.com/googleplay/android-developer/answer/113469#targetsdk.
Once we'll target Android 11 we need to support [scoped storage](https://developer.android.com/training/data-storage#scoped-storage)

## Description
Eng needs to investigate 

* our current interactions with Android filesystem 
* what recommended approaches should we use for Android 11 - https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage
* if there are any legacy storage locations to be migrated.

## Deliverables
* Reach out to Product to go over results of investigation.
* Open new tickets for addressing each part of the needed work

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly with Google Pixel 4 XL (11).
Note that I was able to upload/download files without issues.
