### ISSUE TITLE
[Bug] Weird Glean Sentry crashes suggesting code is being optimized away

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-mobile/fenix#12820]
We've been seeing a few bunch of weird Sentry issues recently:

* [Null reference used for synchronization](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/9086498/?query=is%3Aunresolved%20glean)
* [Class 'java.lang.VirtualMachineError' does not implement interface ...](https://sentry.prod.mozaws.net/operations/fenix/issues/9163643/?query=is%3Aunresolved%20glean)

Both stacktraces look really weird and seem to suggest that code is being optimized away by R8, breaking some builds in a very nasty way.

@NotWoods was looking into something similar in the past few weeks-

**Comment by liuche** [comment]
Looking at the sentry, this seems like a very very isolated case (3 cases), and if this was getting optimized out by R8 I'd expect to see more. For now, I'll close and if we start seeing more we can prioritize this.
