### ISSUE TITLE
[Bug] raw.githubusercontent is untheme-able

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#12824]
## Steps to reproduce
1. Enable Dark Reader.
1. Open any file as Raw on Github. You'll be taken to raw.githubusercontent.com.
    1. Expected behavior
The page should be themed just like any other.
    1. Actual behavior
The page isn't themed.

Fenix version: Nightly 200718 06:04 (Build #22000612)

**Comment by mcarare** [comment]
This seems to be a Dark Reader Add-on /  GV issue, since it does not work on desktop Firefox either, but works on Chrome Desktop.

**Comment by opusforlife2** [comment]
Indeed: https://bugzilla.mozilla.org/show_bug.cgi?id=1654505

**Comment by opusforlife2** [comment]
Not a Dark Reader specific issue, though: https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/269

**Comment by evilpie** [comment]
This is basically a bug in Gecko for all WebExtensions, not limited to Android. Not sure if you need to duplicate tracking this issue for Fenix.

**Comment by kbrosnan** [comment]
Going to close this. We can pickup whatever Gecko changes are chosen here.

**Comment by opusforlife2** [comment]
Oh no. The bug was marked duplicate of a 3 year old bug.
