### ISSUE TITLE
FNX-4925 ⁃ Back button doesn't work on first tap on a Twitter custom tab

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1282]
## Steps to reproduce
-Open Twitter App
-Click on a link (default browser Fenix) to open in custom tab
-Tap on the back button to go back to Twitter

### Expected behavior
-Going back to Twitter on the first try

### Actual behavior
-Tapping on the back button doesn't work on the first try (works on second)

### Device information
* Device: Pixel 3
* Android device: 9
* Fenix version: 1.0.1914

**Comment by vesta0** [comment]
This is fixed.

**Comment by sv-ohorvath** [comment]
Cannot reproduce it either. closing.
