### ISSUE TITLE
FNX-4926 ⁃ [Meta] Gestures

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1283]
### Why/User Benefit/User Problem
As a user, I want to use gestures to interact with the browser so I can perform my tasks quicker.

### Acceptance Criteria
-UX completed
-QA completed

### What / Requirements 
https://github.com/mozilla-mobile/fenix/issues/176

Known dependencies:
~~[GV bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1509249) for iOS~~like back/forward navigation gestures:

**Comment by mheubusch** [comment]
@lime124 what is the status of this?

**Comment by lime124** [comment]
I'm guessing this is blocked on UX? It totally fell off my radar with all the other stuff going on. Let me dig in to it today.

**Comment by vesta0** [comment]
Depending on the gesture, this is also blocked on GeckoView.

**Comment by andreicristianpetcu** [comment]
the gv dependency was fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1509249
