### ISSUE TITLE
FNX2-15489 ⁃ [Bug] Glitches with the swipe to delete gesture action for bookmarks

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12831]
This was first reported here: https://github.com/mozilla-mobile/fenix/issues/12551#issuecomment-662230064 

There's a bug with this behaviour (Swipe to delete bookmarks). See the GIFs. I cannot delete bookmarks easily due the glitches in this gesture behaviour. You may need to swipe a bit diagonally to reproduce it. Even if I try to swipe exactly horizontally in a straight line it reproduces most of the time and of course I can do the swipe to delete gestures action if I try harder but it's not intuitive and the swipe action seems to be triggering the 3-dot menu button of bookmarks, which I think it should not.

**Edit:** Observe that this gestures action seems to be also triggering the "pull to refresh" action in bookmarks screen.

Device: Motorola One Power, Android 10.
Fenix: Nightly 200721 06:05

See the GIFs:
![20200722](https://user-images.githubusercontent.com/68282543/88133327-4e457680-cbd1-11ea-9872-48230f99f54e.gif)UNITO-UNDERSCORE!093112!

![20200722](https://user-images.githubusercontent.com/68282543/88133431-982e5c80-cbd1-11ea-8c81-9ce20f9c8460.gif)UNITO-UNDERSCORE!093241!

Thank you. :grinning:

**Comment by ShatteredPixel** [comment]
CC @person808
