### ISSUE TITLE
Import Logins from csv files

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#12832]
### What is the user problem or growth opportunity you want to see solved?
People migrating from other browsers want to use their new browser to autofill passwords.

### How do you know that this problem exists today? Why is this important?
See:

* https://www.reddit.com/r/firefox/comments/hvvwb9/data_transfer/
* https://www.reddit.com/r/firefox/comments/fckz78/is_there_a_way_to_import_saved_logins_from_chrome/

### Who will benefit from it?
People switching from other browsers or password managers. Also filed on Lockwise: https://github.com/mozilla-lockwise/lockwise-android/issues/866

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3782)

**Comment by kbrosnan** [comment]
This is technically impossible. Firefox cannot access Chrome user data on Android. The only way for a user to get the data out of Chrome is to use a desktop build [Windows, MacOS, or Linux] of Chrome and Firefox sync and import data.

* Use [Chrome Sync](https://support.google.com/chrome/answer/185277) to get your Android data to a desktop
* Use [Firefox to import Chrome data](https://support.mozilla.org/en-US/kb/import-bookmarks-google-chrome) on desktop
* Use [Firefox Sync](https://support.mozilla.org/en-US/kb/how-do-i-set-sync-my-computer) to get the data to [Firefox on Android](https://support.mozilla.org/en-US/kb/sync-bookmarks-tabs-history-and-passwords-android)

**Comment by yoasif** [comment]
@kbrosnan I didn't mention Chrome for a reason, and for what it is worth, it is not impossible - it just requires more steps.

Users can [export passwords](https://www.howtogeek.com/436340/how-to-view-saved-passwords-in-chrome-for-android/) from Chrome, and ideally, Fenix could just be a share target for the filetype Chrome exports (it looks like a CSV). Otherwise, we could enable an import passwords menu item in the login UI in Fenix that allows users to grab a csv from Chrome or other managers to import directly into Fenix. 

We just did this in Firefox Desktop, FWIW: https://bugzilla.mozilla.org/show_bug.cgi?id=1198973

**Comment by kbrosnan** [comment]
The first reddit thread was about all data and both of them specifically mention Chrome.

**Comment by Poopooracoocoo** [comment]
i guess moz wants to put this in #2080?

**Comment by guillaumeportails** [comment]
Some (I) don't want to use sync, as it implies a logins file put on internet. Whatever encrypted it is, some find this ugly.
It is so simple to import/export locally such a file in my home privacy.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812448

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
