### ISSUE TITLE
[Bug] Missing page content until scroll on OfferUp list page after navigation back from listing

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#12844]
## Steps to reproduce
1. Navigate to https://offerup.com/explore/k/computer-equipment/?delivery_param=s
1. Scroll down a few pages (wait for loading to occur a few times)
1. Tap into any listing
1. Go back to list

### Expected behavior
I am returned to where I was on the listing page and posts are visible. 

### Actual behavior
I am taken to the listing page but no listings are shown until I scroll.

This does not happen in Chrome or Reference Browser.

Screencast: https://drive.google.com/file/d/14SRa7FGcS12CBpTRmEiqJ3jiqeih-mdG/view?usp=sharing

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 200722 06:08 (Build #22040614)
AC: 51.0.20200721130108, 8f5aadc8b
GV: 80.0a1-20200720094507
AS: 61.0.10

**Comment by liuche** [comment]
Hmm, I'm concerned that this is on Fenix, and not happening with Reference Browser - are we doing something strange with caching or paint?
