### ISSUE TITLE
got pop-up saying Fenix was draining battery, feels it actually is

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#12840]
from yoasif

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3788)

**Comment by mcomella** [comment]
@MarcLeclair please follow-up with yoasif about an STR.

**Comment by Dunexus** [comment]
See https://github.com/mozilla-mobile/fenix/issues/10411 for previous discussions about battery usage

**Comment by MarcLeclair** [comment]
Notes from Yoasif:

1) There was 40 tabs opened on the phone ( mostly twitter and similar things)
2) Phone is a pixel 2
3) OS version is android 10
4) Only add on is Ublock ( wasn't enabled when this was reported)
5) Logged into FxA
6) Scree brightness was at medium / auto
7) The reporter doesn't have their phone on most of the time. It was just with the screen turned off but Fenix still in the foreground.

The app was considered in used for 17 hours by the OS

**Comment by mcomella** [comment]
Triage: I'll follow-up with ecsmyth on the priority. Some triage thoughts:
- MarcLeclair mentioned they remember being able to the Gecko profiler even after the app is killed, implying the app restarts itself. Maybe Gecko is misbehaving in the background
- Relatedly, I filed a bug for an issue where Gecko restarted itself: https://github.com/mozilla-mobile/fenix/issues/11439
- It may be that certain web pages or web APIs run even when the screen is off
  - maybe relevant b/c "The app was considered in used for 17 hours by the OS"

**Comment by mcomella** [comment]
Triage: @ecsmyth will check the app feedback for battery concerns and report back

**Comment by keeferrourke** [comment]
Figured commenting here is better than opening a new issue, but sorry if this is the wrong place. (Also sorry for any weird formatting, since I'm posting from mobile)

I semi-regularly get a warning notification on my OnePlus 7 Pro running Android 10 that "Firefox Beta is draining the battery". I always choose to ignore the warning, but that doesn't stop it from coming back, and I bet it could scare away other users.

In terms of runtime info for the most recent time I got the warning:

- 5 tabs open
- I don't suspect that any of the open websites would have any background tasks
- Logged into FxA
- Add-ons: Dark Reader, Privacy possum, HTTPS Everywhere, Decentraleyes (no uBlock, since I have hosts file level ad blocking)
- System Settings > Battery > Battery Optimization reports that since my last full charge, Firefox Beta has been active in the foreground for 3 minutes, and 0 minutes in the background. The app is set to "intelligent control".
- Screen brightness set to medium/auto

Happy to provide more info or follow up to help debug!

**Comment by mcomella** [comment]
Thanks @keeferrourke ! It would be great if you could try different configurations so we might understand where this is coming from. Would be you able to:
- Try installing a Fenix build from a separate release channel (e.g. if you're on Nightly, install Beta) and see if you can reproduce the behavior? If possible, try to avoid changing settings, especially the ones suggested below
- Try enabling FxA and trying to reproduce again
- Try adding the add-ons you have installed and try to reproduce again

By the way, what release channel are you on currently?

Thanks in advance!

**Comment by mcomella** [comment]
@keeferrourke Are you still having this issue?

**Comment by mcomella** [comment]
Triage: ecsmyth briefly looked at battery concerns and saw battery concerns are one of the top besides issues besides the more general performance keywords faster/slower/stuff. However, this data is not normalized to pop and reports jumped up in august, which iiuc might just be indicative that the population was migrated, not that it's a bigger issue.

Action item: if we don't get info to help us reproduce from our reporters here we can dig into the Google Play data to see if there is information there that would help us reproduce https://datastudio.google.com/u/0/reporting/1Nfln73MZW5M3ZrhcdvDI-hlJYlP4xdc_/page/F2SVB

**Comment by keeferrourke** [comment]
@mcomella I personally haven't seen a pop up for any of the firefox releases I'm running for a while, but I'm getting them for lots of other apps sporadically!

**Comment by mcomella** [comment]
I watched a talk where the chrome team said power usage correlates 100% with CPU usage (though I'm not sure on which platform, desktop or android) so I wonder if Fenix uses more power than fennec because it does a lot more redundant computation. For example, it reinflate layouts every time they are shown.

**Comment by mcomella** [comment]
> where the chrome team said power usage correlates 100% with CPU usage (t

ecsmyth said sparky and corey have experience with power use testing on mobile – screen and network also impact power use. To get more information, we should talk with them. There have also been initiatives by the profiler team to track power usage so if we bring it up with them, they may put it on their roadmap.

**Comment by mcomella** [comment]
> I wonder if Fenix uses more power than fennec because it does a lot more redundant computation. For example, it reinflate layouts every time they are shown.

Here are the known issues with redundant computation:
- https://github.com/mozilla-mobile/fenix/issues/15920
- https://github.com/mozilla-mobile/fenix/issues/15921

I don't think we batch when telemetry pings are sent so I wonder if that's a problem for power usage related to network? Then again, we're making random network calls all the time when the user is using a browser so perhaps batching network calls isn't worth it, given how long it takes for the radio to turn off.

**Comment by mcomella** [comment]
Triage: MarcLeclair mentions that a few folks who have had this issue can no longer reproduce; we should get data on how often it occurs before we dig in. We still can still look over the GPlay feedback as one option. However, we're focused on start up for now so we'll revisit this later.

**Comment by cpeterso** [comment]
Old issue
