### ISSUE TITLE
FNX2-15496 ⁃ [Bug]Please reopen #12530

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#12847]
[#12530](https://github.com/mozilla-mobile/fenix/issues/12530)
This issue was not resolved, but was linked to a wrong issue. Both two issues are currently closed.
But the problem still exists.
See the bottom of [#12530](https://github.com/mozilla-mobile/fenix/issues/12530) for details.

**Comment by ShatteredPixel** [comment]
Wow! That issue was closed even when the user is reporting that the user is still facing the problems? 


___

If you don't know I'm the one who helped you on the issue: https://github.com/mozilla-mobile/fenix/issues/9257. Did you remember now?

**Comment by lomomcat** [comment]
> @lomomcat
> 
> Wow! That issue was closed even when the user is reporting that the user is still facing the problems? 
> 
> 
> ___
> 
> If you don't know I'm the one who helped you on the issue: https://github.com/mozilla-mobile/fenix/issues/9257. Did you remember now? 

@ShatteredPixel 
All of us hope **Fenix** can be better. You are not helping me. We just help this software be better and stronger.
Thanks for your help!
[#12530](https://github.com/mozilla-mobile/fenix/issues/12530) was indeed not resolved but it was closed. Can you help us?
It may be that part of the code was modified by mistake during the upgrade, or forgot to change it back after the modification.

**Comment by ShatteredPixel** [comment]
Your issue should be open in due time as you have already filed a new issue for it. Just wait, it's been just 5 hours since you filed the issue. Fenix team must be busy as they plan to release Fenix soon to the general audience. Just wait. Your issue will be reopened. Thanks. :)

**Comment by Amejia481** [comment]
I reopened https://github.com/mozilla-mobile/fenix/issues/12530 to do some further investigation.
