### ISSUE TITLE
FNX2-15494 ⁃ Refine add-ons badge design

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#12845]
### What is the user problem or growth opportunity you want to see solved?
When people see add-on badges, they may not realise that they convey important and useful information, as they currently looks like a plain number with a bit of colour highlight behind it.

![](https://user-images.githubusercontent.com/51007/88252732-5f8ea000-cd03-11ea-8ced-d27250cfa5f8.png)

We’d like to refine its design so it looks like a badge, while respecting developer-side customisation such as [`setBadgeTextColor`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeTextColor) and [`setBadgeBackgroundColor`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeBackgroundColor).

![](https://user-images.githubusercontent.com/51007/88252768-8351e600-cd03-11ea-9831-a0e8862622f0.png)

### Specs
Notes:

* The width shown is a `min-width` value. Add-ons may choose to show heaps of texts (let’s say that 99+ elements are blocked on the page). In that case, we simply widen the badge to fit.
* The badge should follow the same margin used by the menu item text. I think the value is 16dp.

![](https://user-images.githubusercontent.com/51007/88752588-68bdb800-d1ae-11ea-8648-962c289f2e69.png)

**Comment by hakkikaancaliskan** [comment]
@brampitoyo I've debugged a little bit and looks like they don't really providing us correct colors. We're applying what we get properly. No problem on our end. We just need to add some radius.

Here is what extensions providing us:
| Extension name | badgeTextColor | badgeBackgroundColor
| ------------- | ------------- | ------------- | 
| uBlock Origin  | #FFFFFF | #666666 |
| YouTube High Definition | null  | #D90000 |
| Report Site Issue… | null  | null |
| Search by Image | null  | #D90000 |
| Privacy Possum | null  | #D90000 |
| Privacy Badger | #FFFFFF  | #EC9329 |
| NoScript | null  | #800000 |
| HTTPS Everywhere | null  | #D90000 |
| Decentraleyes (0) | #FFFFFF  | #4A826C |
| Dark Reader | null  | #D90000 |

Also as you can see Decentraleyes not using badge, instead they're writing badge to next to their extension name. They "must" use badge to show it.

**Comment by brampitoyo** [comment]
Hi @hakkikaancaliskan, thanks heaps for your work on this issue!

It seems as if the colours that extensions gave us is correct. Those are the colour values that we should use. One question here: what happens if they give us a `null` value? In that case, should we turn our text colour white, or black? Instinctively, I’d pick white – but I’m not sure.

I will post the badge dimension, border radius and font size/style in comment 0. Stay tuned!

**Comment by brampitoyo** [comment]
@hakkikaancaliskan Badge specs are posted above on https://github.com/mozilla-mobile/fenix/issues/12845#issue-664198860

**Comment by hakkikaancaliskan** [comment]
> Hi @hakkikaancaliskan, thanks heaps for your work on this issue!
> 
> It seems as if the colours that extensions gave us is correct. Those are the colour values that we should use. One question here: what happens if they give us a `null` value? In that case, should we turn our text colour white, or black? Instinctively, I’d pick white – but I’m not sure.
> 
> I will post the badge dimension, border radius and font size/style in comment 0. Stay tuned!

`#D90000` is default badgeBackgroundColor as writes here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeBackgroundColor and there is no default badgeTextColor.
Choice is yours.

**Comment by hakkikaancaliskan** [comment]
@Amejia481 10px font size means 10sp?

**Comment by Amejia481** [comment]
> @Amejia481 @brampitoyo 10px font size means 10sp (current 12sp)?
> ![image](https://user-images.githubusercontent.com/17825767/88816961-a4b04780-d1c5-11ea-8265-306601ce399f.png)
> 
> Demo(10sp font size, min width 20):
> <img alt="" width="300" src="https://user-images.githubusercontent.com/17825767/88818522-7cc1e380-d1c7-11ea-90c9-064ddd063d86.png">
> I think this is so small.

I think there is no a one to one relation between pixels and sp [see](https://stackoverflow.com/questions/6263250/convert-pixels-to-sp).  I think 12sp would be sufficient.

**Comment by hakkikaancaliskan** [comment]
> > @Amejia481 @brampitoyo 10px font size means 10sp (current 12sp)?
> > ![image](https://user-images.githubusercontent.com/17825767/88816961-a4b04780-d1c5-11ea-8265-306601ce399f.png)
> > Demo(10sp font size, min width 20):
> > <img alt="" width="300" src="https://user-images.githubusercontent.com/17825767/88818522-7cc1e380-d1c7-11ea-90c9-064ddd063d86.png">
> > I think this is so small.
> 
> I think there is no a one to one relation between pixels and sp [see](https://stackoverflow.com/questions/6263250/convert-pixels-to-sp). I think 12sp would be sufficient.

Then im going to use 22dp min width to maintain square shape.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan When you’ve tried a 12sp font size, would you be able to post a screenshot? I think it’ll good great regardless.

Checking against WCAG 2.1, white `#ffffff` has enough contrast against the default background `#d90000`. Black doesn’t pass. It seems wise to use white text if the default background value is used.

**Comment by hakkikaancaliskan** [comment]
> @hakkikaancaliskan When you’ve tried a 12sp font size, would you be able to post a screenshot? I think it’ll good great regardless.
> 
> Checking against WCAG 2.1, white `#ffffff` has enough contrast against the default background `#d90000`. Black doesn’t pass. It seems wise to use white text if the default background value is used.

This is 22dp min width with 12sp font size
https://github.com/mozilla-mobile/android-components/pull/7838 comment 0

**Comment by brampitoyo** [comment]
@hakkikaancaliskan The updated screenshot you posted on that issue looks great to me!

**Comment by hakkikaancaliskan** [comment]
@Amejia481 qa needed :)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/12 with the following devices:
- Samsung Galaxy Note 10 (Android 10)
- Google Pixel 3 (Android 11)
- Huawei MediaPad M2 (Android 5.1.1)

![Screenshot_24](https://user-images.githubusercontent.com/58466444/90013670-6418f980-dcae-11ea-98ca-0e0b44af4219.png)
