### ISSUE TITLE
FNX2-15500 ⁃ [Bug] runtime.reload() call by uBlock Origin does not reload the extension and shows zero-tab

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#12851]
## Steps to reproduce
1. Open the uBlock Origin _Settings_
1. Press _Reset to default settings_ and confirm the prompt with _OK_

### Expected behavior
The extension is reloaded, e.g. in Fennec it shows Fennec's extension configuration page for uBlock Origin.

### Actual behavior
Tab-zero is shown. Following the calls from [settings.js](https://github.com/gorhill/uBlock/blob/b34e6da6ec22e0186d5b406cdb798a537c11ec8a/src/js/settings.js#L185) to [vapi-background.js](https://github.com/gorhill/uBlock/blob/64cfc5779d87612f87bd5f9bd5581704d5795b64/platform/chromium/vapi-background.js#L92) points to the [`runtime.reload()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/reload) function.

![video-ext](https://user-images.githubusercontent.com/42788925/88279988-44ad3300-cce5-11ea-83ca-93a4a0be368d.gif)

### Device information
* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 200723 06:01 (Build #22050610)
AC: 52.0.20200722023149, 5c2458cb8
GV: 80.0a1-20200721094241
AS: 61.0.10

**Comment by csadilek** [comment]
Thanks for filing. This only seems to happen if uBlock settings is the only open tab. The expected behaviour (working with multiple tabs) is that the settings tab is closed once "reset to default settings" is complete. So, this is a UI issue we need to fix.

**Comment by csadilek** [comment]
I've verified that uBlock is properly reloaded and reset to default settings.

The UI issue is a fallout from https://github.com/mozilla-mobile/android-components/pull/7759. When the tab is closed we're not releasing the engine view and therefore see the tab contents left on the screen.

Let's track this problem (it's not specific to uBlock) in this ticket: https://github.com/mozilla-mobile/android-components/issues/7868
