### ISSUE TITLE
[Bug] Search widget hint shows up above the tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#12858]
## Steps to reproduce
1. Open the tabs tray.
1. [Unknown] Switch between Fenix and other apps or perform actions required to invoke the widget hint.

### Expected behavior
* No hint is seen until the toolbar is visible.

### Actual behavior
* The hint is visible above the tabs tray and seems odd (see screenshot below).

<img width=350, src="https://user-images.githubusercontent.com/1370580/88303917-95b52b00-ccd5-11ea-9a97-5e50c69f55eb.png" />

### Device information
* Android device: Android 10, Pixel 4
* Fenix version: Nightly Thursday 7/23 @ 6:10 AM

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that the issue is reproducible on Firefox Preview Nightly 200729 (Build #22110610).

### Device used:
- OnePlus 6T (Android 9)

**Comment by ekager** [comment]
Search Widget CFR has been removed in #16081
