### ISSUE TITLE
[Bug] Blocking tracking content only in private tabs shows ETP off on normal tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12854]
## Steps to reproduce
1. Open a tab in normal browsing.
1. Go to ETP settings, select Custom, and change Tracking content to "Only in private tabs"
1. Go back to the tab, tap the ETP shield. Check the toggle position.
    1. Expected behavior
ETP is still on all websites.
    1. Actual behavior
The toggle is off and indicates that "Protections are off on this site", but the panel still shows other trackers are being blocked.
    1. Device information

* Android device: Nexus 6P (Android 8.1)
* Fenix version: 79.1.0-beta1, Nightly 7/23.

**Comment by ekager** [comment]
Looking at the code, this looks intentional but it is definitely confusing that changing that one custom setting takes away ETP for normal mode entirely 🤔 

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt#L44-L55

@Amejia481 do you know if this was the only way we had to apply the setting for tracking content "Only in private tabs"?

**Comment by Amejia481** [comment]
> Looking at the code, this looks intentional but it is definitely confusing that changing that one custom setting takes away ETP for normal mode entirely 🤔
> 
> https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt#L44-L55
> 
> @Amejia481 do you know if this was the only way we had to apply the setting for tracking content "Only in private tabs"?

Thanks for looking into this issue, it looks like this is [a problem in AC](https://github.com/mozilla-mobile/android-components/blob/534a9f6b88e4af7faaf2dc6c94689861c48905a9/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L204). I will take a look.

**Comment by softvision-miralobontiu** [comment]
This is still reproducible on the latest Nightly build from 8/13, and on RC 79,0,4, with Samsung Galaxy Tab S6 (Android 9).

**Comment by softvision-miralobontiu** [comment]
Reproducible on Beta 86.0.0-beta.5 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 89.0.0-beta.1 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.4 with Samsung Galaxy Note 8 (Android 9).
