### ISSUE TITLE
FNX-4927 ⁃ [UX] Accessibility options under Settings

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1285]
## User Story
As a user, I want to be able to change my browser accessibility settings so I can browse comfortably.

## Dependencies
A-C Issue: Using system font for non-mobile pages (Landed in A-C) #577 

### Acceptance Criteria
I can use a toggle to scale web content according to the system font size.

**Comment by vesta0** [comment]
@lime124 This is a P1 for MVP - I couldn't find it in the accessibility section of the UX settings.

**Comment by buttercookie42** [comment]
@vesta0 Also "Always enabled zoom", too? (Though unfortunately that needs a new GeckoView API, too, I think)

**Comment by cpeterso** [comment]
GV API to support "Always enable zoom" setting: https://bugzilla.mozilla.org/show_bug.cgi?id=1540615

**Comment by vesta0** [comment]
@boek that's why I didn't include "Always enable zoom" but I'll create a separate ticket for for post MVP.

**Comment by lime124** [comment]
@vesta0 it's in our backlog now.

**Comment by mheubusch** [comment]
Hi @apbitner this is a good first issue and there  may be some existing designs done by @brampitoyo - please let Tif know if you need support.

**Comment by apbitner** [comment]
@brampitoyo I poked around and couldn't find any designs, have you done any work on this?

**Comment by apbitner** [comment]
Updated settings screen: https://mozilla.invisionapp.com/share/X3R7SA84BFR
New accessibility screen: https://mozilla.invisionapp.com/share/87RPXG0QDUZ

@shorlander & @mheubusch , ready for approval

**Comment by mheubusch** [comment]
Thanks, Adam! @shorlander pls review

**Comment by apbitner** [comment]
InVision links above have been updated. Changes are:

1. Removed voice dictation setting
2. Changed font size toggle to a slider, which GV team confirmed we can support

**Comment by mheubusch** [comment]
Left comments in InVision @apbitner

**Comment by vesta0** [comment]
@apbitner can we close this?

**Comment by apbitner** [comment]
@vesta0 Yes 👍🏻

**Comment by data-sync-user** [comment]
➤ Adam Bitner commented:

Closed in GH, closing in JIRA.
