### ISSUE TITLE
[Bug] Outdated thumbnails while switching tabs using swipe guesture

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#12859]
## Steps to reproduce
1. Open a tab (tab A) and then scroll down the page.
1. Swipe to another tab (tab B).
1. Now again swipe to previous tab (tab A).
    1. Expected behavior
The preview of the tab is updated to reflect the scroll.
    1. Actual behavior
Shows previous preview when the tab was full loaded first time not the scrolled page preview.
    1. Device information

* Android device: 8.0.0
* Fenix version: latest nightly

//Cc @person808

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3816)

**Comment by person808** [comment]
Thanks for opening a new issue! I'm fairly sure the issue is we're not capturing a new thumbnail after scrolling. Perhaps we could capture a new thumbnail when switching tabs or when the gesture starts. @jonalmeida or @gabrielluong probably have a better idea of the best way to solve this.

**Comment by jonalmeida** [comment]
> I'm fairly sure the issue is we're not capturing a new thumbnail after scrolling. Perhaps we could capture a new thumbnail when switching tabs or when the gesture starts. 

We want to do that more often yes, but we're currently blocked om this by [bug 1647797](https://bugzilla.mozilla.org/show_bug.cgi?id=1647797).

**Comment by jonalmeida** [comment]
With the GV bug fixed, we can now work on this by taking more screenshots as detailed in #14122 .

**Comment by hwinnemoe** [comment]
I think it will be even more relevant than compared to https://github.com/mozilla-mobile/fenix/issues/11918#issuecomment-678758682 to avoid taking a capture when the view is still scrolling. It might also introduce stutter on low-end devices when taking a screenshot while the tab is still scrolling.

**Comment by jonalmeida** [comment]
> I think it will be even more relevant for this issue than compared to [#11918 (comment)](https://github.com/mozilla-mobile/fenix/issues/11918#issuecomment-678758682) to avoid taking a capture when the view is still scrolling. It might also introduce stutter on low-end devices when taking a screenshot while the tab is still scrolling.

I've left a comment on that issue as well that this is sounds like a bug with the GV API. Maybe I'm wrong, but it sounds like the situation where a _high_ accelerated scroll is still happening when we swipe tabs seems like a lower probability that we can bring up with GV outside of this issue.

**Comment by hwinnemoe** [comment]
Sure, let's keep the focus for this issue on implementing and file new issues for minor additions.

**Comment by samlux04** [comment]
it's not only when scrolling. but after done scrolling. it seems it only took a screenshot after initial load. the thumbnail get updated when opening tabs tray tho. shouldn't it take screenshot also when switching tab/leaving the tab.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807079

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
