### ISSUE TITLE
FNX2-15506 ⁃ Share title of collection

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12857]
## User Story
* As a user, I want to be able to share the title of a collection as part of the sharing flow, so it's clear what type of collection I am sharing and I don't have to manually enter the name. 

### Acceptance Criteria
* When I share a collection to another app, the title of the collection appears as the header/subject.

![image](https://user-images.githubusercontent.com/42752644/88484469-91d71200-cf3c-11ea-9959-62b90577a7bc.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200813`** using the following devices:
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200813-164206](https://user-images.githubusercontent.com/51314259/90145285-736c7580-dd88-11ea-951d-83a355843361.gif)
