### ISSUE TITLE
FNX2-15504 ⁃ Save a collection button in tabs tray

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#12856]
## User Story
* As a user, I want to be able to quickly save collection directly from the tabs tray, so that it is convenient and easy to find.

## Dependencies
* AC work in progress to allow adding buttons to tabs tray. 

### Acceptance Criteria
* [ ] I can quickly save a collection directly from the tabs tray
* [ ] UX to re-evaluate whether we should remove "save collection" from homescreen" once we add it to the tabs tray 

Abstract link: https://app.abstract.com/projects/8afc4b50-7667-11e9-94ba-3558f8596822/branches/master/commits/562779285de5fd8e7000e10116956a1693981e42/files/af6f466c-1a56-494d-ae53-20dd23f8a685/layers/99FC9CA6-50D5-4A85-835E-F566185D8075

<img width=350 src="https://user-images.githubusercontent.com/1370580/88430527-97aae700-cdc6-11ea-9bba-03b59f8abd1f.png"/>

**Comment by vesta0** [comment]
I believe @topotropic has mocks for this already.

**Comment by ebalazs-sv** [comment]
Hi! I had tested this issue on Nightly 200729 (Build #22110610) GV 80.0a1 from 7/29 with Pixel 2 (Android 9) and the "Save to collection" button is available in tabs tray as described in the screenshot description. 
I do not have access to the abstract, so I requested it and I will keep the qa:needed label to verify this further after receiving the access.

**Comment by s-ankur** [comment]
Hi, coming from #13065 .  this functionality is already represented in the three dot menu and long press to open multi select. So I feel that the button is redundant. It also makes the tab tray seem slower(due to the newer animation). Please consider reverting

**Comment by cadeyrn** [comment]
> So I feel that the button is redundant. It also makes the tab tray seem slower(due to the newer animation).

I don't have a problem with the redudancy but I agree that the tab tray _feels_ noticeably slower.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200729 (Build #22110610) GV 80.0a1 from 7/29 with Pixel 2 (Android 9)  and Beta 80.0.0-beta.1 GV 79 from 7/30 with Samsung Galaxt Tab S3 (Android 8).
I will remove the qa:needed label for now.

**Comment by ebalazs-sv** [comment]
This issue is verified as fixed on Nightly 200818 Build #2015758643 from 8/18 with Pixel 2 (Android 9). 

There is one related issue: https://github.com/mozilla-mobile/fenix/issues/13348, that was filed after the fix for https://github.com/mozilla-mobile/fenix/issues/13117.

I will remove the qa:needed label and close this issue.

**Comment by abodea** [comment]
Verified as fixed on **Fenix RC 80.1.0** with **Google Pixel 4 XL (11).**
