### ISSUE TITLE
[Bug] "source": "UNKNOWN" for "name": "app_opened" and "name": "app_received_intent" event type pings

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12850]
## Prerequisites
Have a fresh install of Fenix or a clean profile

## Steps to reproduce
1. Start the app using `**adb shell am start -n org.mozilla.fenix/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es tagPings tagtagtag**`
1. Put the app in background

### Expected behavior
```
 "events": [
        {
          "category": "events",
          "extra": {
            "source": "APP_ICON"
          },
          "name": "app_opened",
          "timestamp": 0
        },
        {
          "category": "events",
          "extra": {
            "source": "APP_ICON"
          },
          "name": "app_received_intent",
```

### Actual behavior
```
"events": [
        {
          "category": "events",
          "extra": {
            "source": "UNKNOWN"
          },
          "name": "app_received_intent",

```

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: 
• Nightly 200723 from 7/23
• Beta 79.1.0 beta.1 from 

### Notes
❗ Another worth mentioning aspect is that the `**"source": "APP_ICON" "name": "app_opened"**` doesn't get generated anymore

**Comment by liuche** [comment]
This is very strange, I'll push it to the Glean team, but could you test on a current Nightly? We just upgraded the Glean version I believe.

**Comment by AndiAJ** [comment]
Hi @liuche , yes, unfortunately the `"source": "UNKNOWN"` still gets displayed on the latest **`Nightly 200812`** build using a Google Pixel 3a (Android 10)

```
      "events": [
        {
          "category": "events",
          "extra": {
            "source": "UNKNOWN"
          },
          "name": "app_received_intent",
          "timestamp": 0
        },
        {
          "category": "events",
          "extra": {
            "source": "UNKNOWN"
          },
          "name": "app_opened_all_startup"
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/5062738/loga.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t1208000)

Perhaps @Dexterp37 could advise? ☺️

**Comment by Dexterp37** [comment]
@liuche @AndiAJ I'm afraid that the value that's being communicated by the Glean SDK is indeed the value Fenix is setting. This is the [documented expected value](https://searchfox.org/mozilla-mobile/rev/5f3be92a6df90ec548747c2b380bf889adbe6fe5/fenix/app/metrics.yaml#58) (minus the case) for this metric, which [matches up with the Fenix implementation](https://searchfox.org/mozilla-mobile/rev/5f3be92a6df90ec548747c2b380bf889adbe6fe5/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt#316). Probably coming from [here](https://searchfox.org/mozilla-mobile/rev/5f3be92a6df90ec548747c2b380bf889adbe6fe5/fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AppAllSourceStartTelemetry.kt#46,49). This is probably a Fenix bug!
