### ISSUE TITLE
[Bug] Closing last private tab does not show undo snackbar when on BrowserFragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#12860]
## Steps to reproduce
1. Open a single private tab
1. Open tabs tray (while on the browser fragment)
1. Close the tab (by pressing the "X")

### Expected behavior
1. Tab closes and an undo snackbar appears

### Actual behavior
1. Tab closes but no undo snackbar appears

Note that this works as expected when pressing "close all tabs" and does NOT affect normal browsing mode. I believe it's something to do with mode changes which recreates the activity :slightly_frowning_face:

**Comment by s-ankur** [comment]
I feel like the current behavior should be the intended behaviour. I understand that it must be irritating for someone to not have an undo button in this specific scenario, but I think when the private mode is closed then it should stay closed. The risk of exposing private mode content seems to outweigh the inconvenience.

**Comment by sblatz** [comment]
Regardless, we should be consistent using the same behavior between close all tabs and closing an individual tab.

**Comment by Diana-Rus** [comment]
Hi, reproduced the issue with both Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9), i've seen this outcome in this circumstances:
- When there is another tab in normal browsing opened and one in private tab (for which the deletion is made)
- When using the "Close tab" option from the tabs tray menu

Note:
For first scenario - in case of deleting the tab from normal browsing and afterwards the one from private tab than the undo snackbar, for private tab, will be present.

**Comment by hwinnemoe** [comment]
The undo snackbar is displayed when using the x-button or swiping to close on 80.1.2 and 81.1.0-beta.2, but it is not displayed on Nightly 200909 06:00 (Build #2015762865), thus this might be seen as a regression.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200928`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
