### ISSUE TITLE
FNX-14006 ⁃ [Bug] undo close tab popup obscures the bottom bar

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12868]
## Steps to 
Open 2 tabs
Long click on tab counter and close tab

### Expected behavior
Popup appears as usual, above the bottom bar

### Actual behavior
Popup appears ON the bottom bar
![Screenshot](https://user-images.githubusercontent.com/33252312/88330778-896ab580-cd49-11ea-940a-45d7d6fd3d4c.png)UNITO-UNDERSCORE!20200724-010146!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus Zenfone
* Fenix version: nightly

**Comment by AndiAJ** [comment]
Hi @person808 , I've just re-checked this matter on the latest **`Nightly Build #200728 from 7/28`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

It seems that the confirmation snackbar **is still being displayed on top of the URL bar**, on the other hand, It **doesn't seem to have any interaction impact** as it gets **dismissed along with the Tabs Tray**

► Time lapsed video 
![20200728-121519](https://user-images.githubusercontent.com/51314259/88645334-a9dd9b80-d0cc-11ea-9f9a-cebf086989ec.gif)

► Normal video
![20200728-122231](https://user-images.githubusercontent.com/51314259/88645800-34be9600-d0cd-11ea-974a-329e1d1b1fb0.gif)

Please review and share your thoughts. ☺️  
**I'll remove the QA needed label until further notice.**

**Comment by person808** [comment]
@AndiAJ This snackbar this issue is referring to is from long pressing the tab counter to close a tab, not the tab tray. Could you recheck? Thanks!

**Comment by AndiAJ** [comment]
Hi @person808, sorry for the inconvenience. ☺️ 
**Verified as fixed** on the **`Nightly Build #200728 from 7/28`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200729-085413](https://user-images.githubusercontent.com/51314259/88762298-92102100-d179-11ea-90c1-97d2c8feff97.gif)
