### ISSUE TITLE
FNX2-15510 ⁃ Migrate library menus to concept-menu

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#12862]
Classes still using browser-menu:

* [x] BookmarkItemMenu
* [x] HistoryItemMenu

After converting to the new library, the menus should still work in the same way.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/19 with Samsung Galaxy Note 10 (Android 10) and Google Pixel 3 (Android 11).
