### ISSUE TITLE
FNX-13996 ⁃ [Bug] it is strange how it sorts tabs in "Swiping Address Bar" vs "tabs tray"

### ISSUE THREAD

**Issue by Neikon** [mozilla-mobile/fenix#12861]
## Steps to reproduce
When you slide the address bar between two or more tabs, it seems strange how it sorts in front of the tabs tray.
I have url bar at the botton.

### Expected behavior
the newest tab in tab tray would be at botton
the most left tab in "swiping gesture" would be the oldest
The oldest tab in tab tray would be at top
the most right tab in "swiping gesture" would be the newest.

or 

the newest tab in tab tray would be at top
the most left tab in "swiping gesture" would be the newest
The oldest tab in tab tray would be at botton
the most right tab in "swiping gesture" would be the oldest.

The first form is how chrome does it and i think is the most intuitive form, and easier for new users. but it should be okay like second. But i think, how we do right now have not sense. 
I tagged @person808 beacuse he did "swiping address bar" feature

### Actual behavior
the newest tab in tab tray is at top
the most left tab in "swiping gesture" is the oldest
The oldest tab in tab tray is at botton
the most right tab in "swiping gesture" is the newest.

### Device information
* Android device: Oneplus 7, Android 10
* Fenix version: Nigthly 200723 06:01 (Build 22050611)

**Comment by person808** [comment]
Thanks for filing as a separate issue. Will let UX weigh in on this.

**Comment by sheepycoder** [comment]
As mentioned [here](https://github.com/mozilla-mobile/fenix/issues/3481#issuecomment-662938578), this is the same as https://github.com/mozilla-mobile/fenix/issues/10365 and https://github.com/mozilla-mobile/fenix/issues/11376

**Comment by AmyYLee** [comment]
@topotropic for feedback

**Comment by topotropic** [comment]
Thanks for bringing this up. 

We currently follow reading patterns (top --> down, left --> right or right --> left) and display the newest tab where people start reading. Based on this, we should update the gesture for left-to-right languages to match the suggested behavior:

> the most left tab in "swiping gesture" would be the newest
> the most right tab in "swiping gesture" would be the oldest.

And keep the current behavior for right-to-left languages (oldest tab is on the left, newest on the right)

**Comment by Dunexus** [comment]
@topotropic On desktop, when you "Open in a new tab", the new tab is on the right of the original tab.
It is weird to do the opposite on Fenix.

**Comment by AndiAJ** [comment]
Hi, **`verified as fixed`** on the latest **`Nightly Build #200729 from 7/29`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video left-to-right language
![20200729-151725](https://user-images.githubusercontent.com/51314259/88806513-32396a80-d1b9-11ea-85d0-32f7ca1411f3.gif)


► Video right-to-left language
![20200729-152453](https://user-images.githubusercontent.com/51314259/88806738-7a588d00-d1b9-11ea-9db4-030ff22ab704.gif)

**Comment by Dunexus** [comment]
@topotropic 
I tested the updated behavior, it is really disturbing to have new tabs on the left while on desktop they are on the right. It is really counter-intuitive.
Also, Android 10 app switcher displays the newest app on the right and the oldest on the left.
Could this be reconsidered ?

**Comment by madb1lly** [comment]
Hello @topotropic,

I came to this issue from #13172 and your answer is inconsistent with the way Fenix shows tabs in the tab list. The tabs list shows the newest tabs at the _top_, not at the bottom, but if we should be following the top=>down reading pattern then the newest tabs should be at the _bottom_, not the top.

(However, I think that this behaviour would not be consistent with the way the list "feels" depending on where the toolbar is set. If the toolbar is at the bottom then the tab stack should have the newest tabs at the top, whereas with the toolbar at the top the tab stack should be sorted with the newest tabs at the bottom; that is a different issue though).

In addition, LTR language books have the oldest pages on the left, newest on the right, so it would make sense for the oldest tabs to be on the left, newest on the right.

The current behaviour definitely feels counter-intuitive to me, a native LTR language speaker, but maybe it feels fine to a RTL language speaker.

I also just changed the language to a RTL language, Japanese, and the behaviour is the same, therefore it makes me wonder if:
1. The check of language to configure swipe behaviour hasn't been implemented, as if it is then LTR language swiping will work as I expect.
OR
2. Only one swipe behaviour is currently implemented, regardless of the feedback you gave.

Please can you clarify?

Thanks 🙂

**Comment by gonzaarcr** [comment]
I think that even with the address bar at the bottom, new tabs show be at the bottom. I don’t know what reasoning are you guys following, but new is always at the bottom, even when the input is at the bottom. Just look at messaging apps.

**Comment by cadeyrn** [comment]
> Just look at messaging apps.

In every messaging app I know new conversations are on top, not on bottom.

**Comment by madb1lly** [comment]
Hi @gonzaarcr,
That's a very good observation. I had a quick look on my phone and all the _messaging_ apps I have show new messages at the bottom (it may be configurable, but I believe this is the default as I don't recall changing it):

- SMS/MMS messages app (Google Messages I think)
- Telegram
- Whatsapp
- Element (Riot.im) - which is used by Mozilla

I also recall that IRC shows new messages at the bottom in general.

However all my email apps seem to show new messages at the _top_ by default.

Anyway, this isn't what this issue is about is it - this issue is primarily about the address bar swiping, so maybe we should stay on topic.

In any case, the issue is already closed 😆

Cheers 🙂

**Comment by gonzaarcr** [comment]
What I said is, the newest should be at the bottom and the swipe would be solve., since the swipe right is going to the bottom.
