### ISSUE TITLE
[Bug] Synced tabs menu is blank despite being signed in to Firefox account

### ISSUE THREAD

**Issue by mat-mil** [mozilla-mobile/fenix#12870]
## Steps to reproduce
Login to Firefox account on device 1 (Windows 10 PC in this case, Firefox Browser 78.0.2 64-bit)
Open a website on device 1
Login to Firefox account on device 2 (Android phone, Firefox Beta 79.0.0-beta.8 build #2015752515)
Go to synced tabs menu on device 2

### Expected behavior
Website opened on device 1 listed in the synced tabs menu on device 2

### Actual behavior
Blank Synced tabs with throbber looping

**Comment by mat-mil** [comment]
I wiped my phone entirely. Syncing works now after a fresh install. Thank you for your attention :)

**Comment by Arnvidr** [comment]
Always empty on both previous and new phone for me. Sync info shows initially synced: never. After manually initiated sync it shows last sync as Jan 1st 1970, so it seems like the problem could be on the backend.

**Comment by kbrosnan** [comment]
Closing as the reporter has resolved the issue. We would need some sort of logs to investigate why this happens.
