### ISSUE TITLE
Swipe up on bottom bar to get a tab switcher (like Android's recent app switcher)

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#12874]
### What is the user problem or growth opportunity you want to see solved?
@person808 implemented swipe on the address bar to switch tabs. This gesture (and the accompanying look of the animation) would gel better with a tab switcher which looks like Android's app switcher, rather than a tab list:

* Swiping up on the address bar would shrink the tab into a "recent apps" like view of the tabs. (like Chrome does?)
* Naturally, you would swipe sideways to scroll through the tab list. The immediate benefit is that you can view their contents at a glance, instead of having to rely on thumbnails.
* It would be more usable than Chrome, which has vertical tab scrolling (last I remember). Chrome's implementation allows for faster scrolling, but impedes tab content visibility at a glance.

### How do you know that this problem exists today? Why is this important?
It is an alternative feature to #11862. We already have the ability to access the tab list from the tab counter button. So that can stay the way it is now. An Android-like tab switcher would look and feel better than a tab list for the swipe up gesture.

### Who will benefit from it?
Swipe-happy users, I guess? On a serious note, everyone who is used to Android's recent apps switcher (sounds like a lot of people).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3835)

**Comment by Neikon** [comment]
I think, It would have a problem. tabs switcher like  android **stock** recent app switcher is not enough good. You can not see more than one tab at the same time, or search between tabs is dificult. But maybe if it would be like Oneplus (OxygenOS) or Xiaomi (Miui).
It could be a better option.

[MIUI style](https://images.fonearena.com/blog/wp-content/uploads/2018/06/MIUI-10-11.jpg)
[OxygenOs Style](https://www.androidheadlines.com/wp-content/uploads/2020/04/OnePlus-Launcher-4.4-new-app-switcher-image-1.jpg)

Maybe a remix between[ this ](https://www.androidcentral.com/sites/androidcentral.com/files/styles/large/public/article_images/2018/05/android-p-beta-multitasking-gesture-in-hand.jpg?itok=4VuQ7AbZ) (dock icons like top sites and google search like url bar) and [MIUI](https://images.fonearena.com/blog/wp-content/uploads/2018/06/MIUI-10-11.jpg) (like tab thumbnails) would be great.

in other hand swipe up(or down if you have top bar) to open tabs tray i think would be great.

**Comment by opusforlife2** [comment]
Out of your MIUI and OOS examples, I certainly prefer OOS's look. MIUI's layout wouldn't be practical for phones with small screens.

**Comment by DavidBE-UK** [comment]
Current tab sheet ignores top control/toolbar users and is designed purely from the viewpoint of bottom control/toolbar users .... as with most discussions about tab switching. Tab sheet needs work on different behaviour when toolbar top is chosen in settings.

**Comment by opusforlife2** [comment]
Well... yeah. Swipe up if you have the bottom bar, and swipe down if you have the top bar, just like Chrome. That makes perfect sense for top bar users. The rest is basically the same.

**Comment by opusforlife2** [comment]
Maybe this overview would let the user browse and switch between Contained Spaces (#10581) as well.

**Comment by opusforlife2** [comment]
@person808 Did you have a look at this proposal?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807062

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
