### ISSUE TITLE
FNX2-15527 ⁃ [Bug] Constantly flickering icons in tab history for a loading page

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12887]
## Steps to reproduce
Open a webpage that takes a few secs to load
Long press back button

### Expected behavior
The tab history looks ok

### Actual behavior
It flickers constantly

### Device information
* Android device: Asus Zenfoen
* Fenix version: Nightly 200723 06:01 (Build #22050611)
AC: 52.0.20200722023149, 5c2458cb8
GV: 80.0a1-20200721094241
AS: 61.0.10

**Comment by ekager** [comment]
We'll need to add a change payload here (in `TabHistoryAdapter`) and more efficiently notify/bind the specific changes we need to update in the list (instead of updating the entire list on every change).

**Comment by eliserichards** [comment]
#12973 also has good STR and build info if needed

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200803 (Build #22161809) GV 81.0a1 from 8/3 with Motorola Moto G6 (Android 8) and Pixel 2 (Android 9).

**Comment by sv-ohorvath** [comment]
Verified as fixed on 80.0.0-beta6 on several devices
