### ISSUE TITLE
FNX2-15524 ⁃ [UX Feedback] Swap the button position of Share button with the Forward button.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12884]
The forward button is something that is used a lot in the browser than the other buttons (in the 3- dot main menu of bookmarks, share, forward, reload strip), I think and it should be more accessible. Right now the Forward button is placed far towards the right side in the 3-dot main menu in the toolbar (see the screenshot¹)  where it is bit harder to reach and with the issues like #1048 which make the forward button to hold for longer times I think this will strain the thumb finger as the user have to stretch the finger towards the right side of their hand I wouldn't have said so if the the users needed to tap button just once. Now with features like #1048 are implemented the button has to be held pressed for longer times and that too very frequently as they'd use history stack more frequently. 

Chrome browse places this Forward button at the start (see the screenshot²), Brave browser again places this button at the start (see the screenshot³), kiwi browser does place this at the start as well (see the screenshot⁴) which had one of the best bottom toolbar implementation, I think. But I won't recommend placing this Forward button that far apart as the button placement will become harder to reach as it'll be a bit far for the thumb finger to reach when the phone is used with one hand. 

If we place the Forward button in the place of the Share button then the Forward button will be almost at around the center of the bottom display area which I think is the ideal position of this button as it is the most used button among other buttons (Bookmarks and Share button, and when the pull to refresh #9766 is enabled the usage of the Reload button will decrease even further), and its intended behavioral usage is going to change with #1048 and it'll be used to long press on it as well. I think, the placement of this Forward button should be at the around the center of the phone's display bottom so it really depends on the width of the 3-dot main menu as it is changing the sizes dynamically now #11716 making harder for me to recommend where this Forward button should be placed. Perhaps we should go with placing the Forward button at the start like the Chrome browser? I'm not sure. But as it is right now I think the Share buttons placement should be swapped with the Forward button to make it easier to use it when the button is long pressed and as well as single tapped on it.

Thanks you. :grinning: 

    1. Screenshot¹:
![ewy1c](https://user-images.githubusercontent.com/68282543/88364858-e1350b00-cda1-11ea-9700-e146e2807e6e.jpg)UNITO-UNDERSCORE!159556989495428!

### Screenshot²:
![Screenshot](https://user-images.githubusercontent.com/68282543/88364619-0f661b00-cda1-11ea-939c-e51947ecc368.png)UNITO-UNDERSCORE!20200724-111832!

### Screenshot³:
![Screenshot](https://user-images.githubusercontent.com/68282543/88364634-1d1ba080-cda1-11ea-8639-7ae07fbc0d63.png)UNITO-UNDERSCORE!20200724-111909!

### Screenshot⁴:
![Screenshot](https://user-images.githubusercontent.com/68282543/88364645-299ff900-cda1-11ea-9f9e-1da9dc1448aa.png)UNITO-UNDERSCORE!20200724-111812!

**Comment by AmyYLee** [comment]
@brampitoyo for feedback

**Comment by brampitoyo** [comment]
Hi! Choosing between:

- Placing the Forward button at the start like the Chrome browser
- Placing the Forward button next to Bookmark

What are the pros and cons of each? What would your suggestion be?

It seems like Forward and Refresh should stay in the corner, in a predictable location. This could be the reason why the forward button appears as the leftmost item in the screenshots you’ve posted.

**Comment by apbitner** [comment]
Original user account has been deleted
