### ISSUE TITLE
[Bug] Tab history opens twice on long back button press

### ISSUE THREAD

**Issue by DmitriyFrogo** [mozilla-mobile/fenix#12885]
https://github.com/mozilla-mobile/fenix/issues/1048#issuecomment-663198580

## Steps to reproduce
Long press on back button
(Maybe it's important, my phone have physical back button)

### Expected behavior
Tab history opens once

### Actual behavior
Tab history opens twice

### Device information
* Android device: Samsung S6 Edge / Android 7.0
* Fenix version: Nightly 200723 18:05

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3848)

**Comment by eliserichards** [comment]
Thanks for the note that you have a physical back button! It might be useful! 😄

**Comment by Augures01** [comment]
> 
> 
> Thanks for the note that you have a physical back button! It might be useful! 😄

Yeah 😊
I do some "research" and can provide additional info

1. When I press physical button - history opens **twice**

2. I do build.prop tweak to enable soft keys (qemu.hw.mainkeys=0)
When I press software button - history opens **once**

3. When I long tap on forward button in Fenix menu - history opens **once**

**Comment by person808** [comment]
This is a very weird bug and probably manufacturer/device specific. Normally we use `onKeyLongPress` to trigger the tab history, but on Android 7 that method doesn't actually work. Instead we do our own handling of back button presses to achieve the same thing [1]. My first instinct was to assume `onKeyLongPress` and our custom long press implementation were both being called but we explicitly don't use `onKeyLongPress` on Android 7. The solution is probably to just check if the tab history dialog is open before navigating to it. Could QA check on some other devices (preferably Android 7) so we have a better idea of how many devices this affects?

[1] https://github.com/mozilla-mobile/fenix/blob/5ddf8beea7432826e20ca4e46e8bba29338f0ef2/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L381

**Comment by ebalazs-sv** [comment]
Hi! I had tested this on Nightly 200804 Build #22170943 GV 81.0a1 from 8/4 with Huawei P9 Lite (Android 7),  Nexus 9 (Android 7.1.1), Huawei MediaPad M3 Lite 10 (Android 7.0) and the recent history pop-up opens once when tapping the device back button. None of these devices has a physical device back button. 
I will remove the qa:needed label for now and come back with the results if I find a device with a physical back button.

**Comment by abodea** [comment]
Hi, @Augures01, @eliserichards, @person808 please note that the only physical button from s6, s7 devices is the **`home button`** the other two buttons **`back`** and **`recent apps`** are **[`capacitive buttons`](https://en.wikipedia.org/wiki/Capacitive_sensing).**

**Comment by Augures01** [comment]
> 
> 
> Hi, @Augures01, @eliserichards, @person808 please note that the only physical button from s6, s7 devices is the **`home button`** the other two buttons **`back`** and **`recent apps`** are **[`capacitive buttons`](https://en.wikipedia.org/wiki/Capacitive_sensing).**

Ok, I will remember this. But when I say "physical button", I mean "button than not on-screen displayed"

**Comment by abodea** [comment]
Yes, totally agree and I understand why you called them **`physical`** I added this information for the developers maybe it helps when trying to fix the issue.

**Comment by person808** [comment]
@Augures01 We are adding a back button to the menu as well (should be in the next nightly). You can long press it to see tab history and it shouldn't open twice.

**Comment by Augures01** [comment]
> @Augures01 We are adding a back button to the menu as well (should be in the next nightly). You can long press it to see tab history and it shouldn't open twice.

I'm not an active user of this feature
I just accidentally pressed back button, found this strange behaviour and reported it 😅
Any fixes not for me, but for other users

**Comment by ebalazs-sv** [comment]
I had tested this on Nightly 4/6 with Samsung Galaxy Tab S3 (Android 8) and the issue is not reproducible anymore.
@Augures01 Do you still reproduce this issue?

**Comment by Augures01** [comment]
> 
> 
> I had tested this on Nightly 4/6 with Samsung Galaxy Tab S3 (Android 8) and the issue is not reproducible anymore.
> @Augures01 Do you still reproduce this issue?

Yes

**Comment by abodea** [comment]
I'm also still reproducing it on the latest Nightly 4/6 with Samsung Galaxy S7 (Android 7).

**Comment by lucamp** [comment]
Same issue with Oppo CPH1931, Android 10, Fennec 92.1.1 fdroid
