### ISSUE TITLE
FNX2-15528 ⁃ [a11y] Difficult to see which tab is current in tab history

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12888]
## Steps to reproduce
Long press back button to open tab history

### Expected behavior
It's clear which tab in tab history you are on, either by inverting the colors for that item or by some other way of highlighting

### Actual behavior
It's not very clear and it's only indicated by bold text which and be hard to see for a lot of people

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200723 06:01 (Build #22050611)
AC: 52.0.20200722023149, 5c2458cb8
GV: 80.0a1-20200721094241
AS: 61.0.10

**Comment by eliserichards** [comment]
Current design (from https://github.com/mozilla-mobile/fenix/pull/12519): 

<img src="https://user-images.githubusercontent.com/6396431/87336101-35183800-c4f6-11ea-9d3b-0e92f890ef25.png" width=300>

@brampitoyo FYI for design input here :)

**Comment by s-ankur** [comment]
![Screenshot_20200727-225917_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/88572482-d8239280-d05c-11ea-98e9-8911a4d6efa3.png)
Dark mode is slightly more difficult to distinguish than light mode

**Comment by brampitoyo** [comment]
@s-ankur @eliserichards Let’s use the identical highlight colour value that we use in the Tab Tray for currently selected tab.

<img width="360" src="https://user-images.githubusercontent.com/51007/88620690-bd9bf880-d0f2-11ea-92f9-37bebc6cdc0f.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/88620692-becd2580-d0f2-11ea-8224-a9a38ec25b58.png">

Tab Tray for comparison:

<img width="360" src="https://user-images.githubusercontent.com/51007/88620863-1ff4f900-d0f3-11ea-926e-d2a7e533f78e.png"> <img width="360" src="https://user-images.githubusercontent.com/51007/88620864-22575300-d0f3-11ea-9562-fa37dd1605e1.png">


By doing this, we no longer need to bold the text.

**Comment by person808** [comment]
@brampitoyo Does this mean we use the same style in normal and private mode for the tab history sheet? Similar to how the tab tray doesn't have a separate private mode style?

**Comment by brampitoyo** [comment]
@person808 No – and sorry I didn’t clarify this.

We do want a separate style for private mode history stack. It should use the same background colour as the modal bottom sheet used for menu surfaces, ETP Panel, Site Information Panel – and the same background colour as in-app pages like Bookmarks.

The highlight colour value for the private theme will be the same as the one used on dark theme.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200803 (Build #22161809) GV 81.0a1 from 8/3 with Motorola Moto G6 (Android 8) and Pixel 2 (Android 9).

**Comment by sv-ohorvath** [comment]
Verified as fixed on 80.0.0-beta6 on several devices.
