### ISSUE TITLE
FNX-14019 ⁃ [Bug] Snackbars created by context menu items are shown on top of toolbar

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#12880]
Original report: https://github.com/mozilla-mobile/fenix/issues/9539#issuecomment-663279353

## Steps to reproduce
Long press a link and select "Open link in new tab" (or any other action that shows a snackbar)

### Expected behavior
Snackbar for new tab opened is shown above toolbar

### Actual behavior
Snackbar is shown on top of toolbar (blocking it)

**Comment by person808** [comment]
Note for qa: Theres some unrelated bugs with snackbars in custom tabs that prevent them from showing most of the time. It should be enough to verify this for the regular browser.

**Comment by sblatz** [comment]
Thanks for being on top of this! 😄

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200728 (Build #22100630).
### Devices used
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)
