### ISSUE TITLE
FNX2-15529 ⁃ Add save to pocket button on Firefox Fenix for android

### ISSUE THREAD

**Issue by OsadebamwenEvbuomwan** [mozilla-mobile/fenix#12889]
### What is the user problem or growth opportunity you want to see solved?
This would allow users to easily add articles to there pocket list, without the need to press multiple buttons to be able to save an article to pocket. It would also allow more Fenix users to use Pocket more often when browsing the web.

### How do you know that this problem exists today? Why is this important?
Whenever I browse the web on Fenix android I barely save to pocket compared to when I browse on my PC I almost always save to pocket. This would be a very good alternative to collections which as of know cannot be synced and is not a very good way to save an article, especially across devices. This is important because more users would be able to discover Pocket and also would be very handy for existing Pocket users. 
Please Investing in this and also bring recommendations by pocket to android.

### Who will benefit from it?
Everyone who is invested in the Mozilla ecosystem.

### Critireals 
* [ ] should be user friendly, should not be more than 2-3 taps to be able to save to pocket. less than 2 would be awesome.

**Comment by cadeyrn** [comment]
see also #3788 and #6416.

**Comment by kbrosnan** [comment]
Closing in favor of the other issues mentioned.
