### ISSUE TITLE
[Bug] Hard-coded "Report Site Issue…" in a website's menu

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/fenix#12886]
cc @Delphine 

In Nightly (`200724 06:05`) I see a `Report Site Issue…` menu, that is not exposed for localization (not even in the latest batch of strings from android-components).

I'm not familiar enough with Android, or Fenix's codebase, but is that coming from a built-in add-on?
https://github.com/mozilla-mobile/android-components/blob/b5d16c69d3938879bedd45c8626b2379ae206529/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json#L50

**Comment by Pike** [comment]
Found https://github.com/mozilla-mobile/fenix/blob/c143f95819aa34e65017ded6bc519d87c2c8a0e0/app/src/main/java/org/mozilla/fenix/components/Core.kt#L97-L105
