### ISSUE TITLE
Add an undo button when a Top Site is removed

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12883]
Top Sites are an extremely important feature for some users and they cannot afford to lose a single Top Site. There's a reason why users are asking the Top Sites to be synced #7936 because they are just as important.

Please add an undo button so the users don't delete the important sites they have added to the Fenix's homescreen. They are just like how bookmarks or collections in a sense; the users have collected them with a a lot effort, there's reson why they have added them to the most visible area of Fenix; it's homescreen. Just like there is an undo button when the bookmarks are deleted, I think there should be one for Top Sites too. And in case of Top sites they are even more prone to get accidentally deleted as they are at the front and centre of the Fenix's homescreen. So it'd be really great if the undo prompt is added to the Top Sites as well.

Thank you! :grinning:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3845)

**Comment by gabrielluong** [comment]
This should be fixed now.
