### ISSUE TITLE
Animation: tab switching

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1289]
Pulling up Amy's first comment:

Tab switching is the same as returning to home and opening an existing tab. When on a website, the user taps on the home icon that takes them to the homescreen where they tap on an already opened tab to switch to it. Let me know if you have any questions.

```
Opening an existing tab from the home screen - Transition duration 120ms
```

• Apply Android ripple overlay on release of pressed state on tab.https://github.com/mozilla-mobile/fenix/actions

• After ripple animation, tab moves up and simultaneously fades out to 0% opacity.
• Browser chrome and website screen moves up and simultaneously fades in to 100% opacity.

```
Closing a tab - Transition duration 120ms
```

• Animation is reversed (website screen slides down and fades out, tab slides down and fades in).

Animation reference:
https://drive.google.com/file/d/1gg-tCqAKrI08ANVpekGmnltCqvS0o6RS/view?usp=sharing

## ![Open Close Tab mp4](https://user-images.githubusercontent.com/287322/67528721-022fca80-f66f-11e9-9b88-5eab404a789d.gif)
Original post:
UX designs: #167

**Comment by AmyYLee** [comment]
Hi, 

Tab switching is the same as returning to home and opening an existing tab. When on a website, the user taps on the home icon that takes them to the homescreen where they tap on an already opened tab to switch to it. Let me know if you have any questions.

Animation reference:
https://drive.google.com/file/d/1gg-tCqAKrI08ANVpekGmnltCqvS0o6RS/view?usp=sharing

**Comment by vesta0** [comment]
@AmyYLee is this ready for eng or being re-evaluated?

**Comment by vesta0** [comment]
@lime124 do we still need to do this?

**Comment by AmyYLee** [comment]
@vesta0 @lime124 Yes this is still relevant.

**Comment by topotropic** [comment]
@AmyYLee can we close this? Thanks!

**Comment by AmyYLee** [comment]
@topotropic Yes! I'll close this.
