### ISSUE TITLE
Ability to share individual links on the website through "Send to device" feature

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12890]
Right now, it is only possible to share the whole tab through "send to device" and the individual links on the website cannot be shared. Desktop Firefox already has such a feature but the Fenix still lacks it. 

Currently when I long press on a link in a website and when Share link is pressed, the Android's Share Sheet is opened and it lacks any kind of share to device entry through Fenix.

Please see the screenshot.

Thanks. 

![Screenshot](https://user-images.githubusercontent.com/68282543/88388140-71278480-cda3-11ea-9133-035e3ca75db9.jpg)UNITO-UNDERSCORE!20200724!UNITO-UNDERSCORE!122505!

![sjaZ](https://user-images.githubusercontent.com/68282543/88388378-ec893600-cda3-11ea-8c7a-79c832249ae5.jpg)UNITO-UNDERSCORE!159557363551131!UNITO-UNDERSCORE!1!

**Comment by buttercookie42** [comment]
> Desktop Firefox already has such a feature

As does Fennec - 'Send to device' there is simply part of the general Firefox share target which can be invoked from anywhere you can share an URL, be that inside (e.g. a link's context menu) or outside of Firefox itself.

**Comment by kbrosnan** [comment]
Duplicate #1523
