### ISSUE TITLE
[Bug] YouTube High Definition add-on: Video can't be muted on some devices

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#12897]
Breaking this off https://github.com/mozilla-mobile/fenix/issues/12305

I was not able to reproduce this, but let's keep it on file and verify.

## Prerequisites
YouTube High definition should be installed
Set the Volume to mute

## Steps to reproduce
Open a video from Youtube
Check if the video is muted

### Expected behavior
The video should be muted

### Actual behavior
The video isn't muted 

### Device information
* Android device: 
• Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly Build 200720

Cannot be reproduced on Pixel 3a, XL (Android 9 and 10)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3875)

**Comment by AndiAJ** [comment]
Still reproducible on Firefox 92.0.0 Beta 1 using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Still reproducible on Firefox 99.0.0 Beta 1 using a OnePlus A3 (Android 6.0.1)
