### ISSUE TITLE
[Bug] [a11y] ETP shield pop-up content is being read twice

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#12905]
## Steps to reproduce
1. Enable TalkBack.
1. Open Fenix with a clean profile.
1. Go to cnn.com.
1. Wait for the ETP shield pop-up to be displayed.

### Expected behavior
The content of the pop-up "Every time the shield is purple, Firefox Nightly has blocked trackers on a site. Tap for more info." is being read once by the TalkBack.

### Actual behavior
The content of the pop-up "Every time the shield is purple, Firefox Nightly has blocked trackers on a site. Tap for more info." is being read twice.

### Device information
* Android device: all
* Fenix version: Nightly 7/24, Beta 79.1.0.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly Build 200831`** using the following devices:
✔️  Google Pixel 3a (Android 10)
✔️  Huawei Mate 20 Lite (Android 10)
❌  OnePlus A3 (Android 6.0.1)

It seem that the issues is **still reproducible on the OnePlus A3**, the ETP pop-up is read twice.
Everything **seems to be in order on the other 2 devices**.

► Video
![20200831-105054](https://user-images.githubusercontent.com/51314259/91696844-dd529080-eb78-11ea-8a7c-c170559ebd3e.gif)

@mcarare - Could you please review? ☺️
