### ISSUE TITLE
FNX-4931 ⁃ Animation: tapping search bar from home screen

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1290]
UX designs: #167 

Tapping search bar from home screen - Transition duration 150ms

• Search bar slides up and transitions in size and colour (search bar height is condensed, search field goes grey, text changes colour).
• Fenix logo slides up with search bar
• Fenix logo fades out along with options/PBM icons once it reaches the top of the screen
• Contents below the search bar fade out at the same time as search bar slides up
• Keyboard fades in and slides up at the same time as content fades out.

Animation reference:
https://drive.google.com/file/d/1gPL3JO3uNgl9LmpJ8P2cnEey3YsLGyGL/view?usp=sharing

**Comment by sblatz** [comment]
We removed this animation because there were crashes caused by the beta library we're using. Do we want to try adding back?

@ekager do we have any timeline on when this library may have those crashes fixed?

**Comment by sblatz** [comment]
@mozilla-mobile/ux can we make sure this animation is considered in the redesign?

**Comment by lime124** [comment]
collecting all the related issues for ux to consider. removing ux label

**Comment by sblatz** [comment]
Once the google library is updated we should just add this back. I will track this.

**Comment by softvision-miralobontiu** [comment]
Verified on a debug build 1.0.1933 (a-c 8.0.0, 78354bc12) with Huawei P9 Lite (Android 6), and Xiaomi Mi 8 Lite (Android 9) that tapping on the search bar from home screen:
• search bar slides up and transitions in size and color (search bar height is condensed, search field goes grey, text changes color),
• Fenix logo slides up with search bar until it isn't displayed anymore,
• contents below the search bar fade out at the same time as search bar slides up,
• the keyboard slides up at the same time as content fades out.

![20190814_172604_Trim](https://user-images.githubusercontent.com/40694158/63029322-02fef000-beb9-11e9-8fcb-d52b1ba1eae6.gif)
