### ISSUE TITLE
"Old" tabs

### ISSUE THREAD

**Issue by pindogu** [mozilla-mobile/fenix#12915]
The old way fenix style tabs were everything was on a single page which looked more organized and also was quicker to use.

I opened a reddit thread were many users agreed that they much preferred the old tabs. They also told me the new way makes you do more unnecessary clicks. You also saw your collections, bookmarks and tabs at a glance.

It would be great if the option to use the old style was available in the settings (or in about:config at least).

Please consider including this into the application. Thank you Firefox team

**Comment by kbrosnan** [comment]
Duplicate #11833

**Comment by pindogu** [comment]
whats going on haha. but yeah this isnt a duplicate
