### ISSUE TITLE
Crash in [@ mozilla::widget::AndroidAlerts::ShowPersistentNotification]

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12910]
## Steps to reproduce
Install search by image addon
Click on it in Addons and select google
Click on a link

### Expected behavior
An error saying it's not an image maybe?

### Actual behavior
Native Crash

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
In fact,this happens with anything that's not an image

**Comment by kbrosnan** [comment]
bz-1649494

**Comment by lrvl** [comment]
Firefox keeps native crashing. Almost anything can trigger the crash:

https://crash-stats.mozilla.org/report/index/bp-f521f62c-45c4-41aa-8f6c-b31c30200821
