### ISSUE TITLE
FNX-4932 ⁃ Animation: Private Browsing

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1291]
UX designs: #167 

Private Browsing
Switching the home view from normal to private mode (namely the background gradient) #181

• Current fade transition is fine - shorten the duration to 100ms.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1920 (#11360657), with Google Pixel (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
