### ISSUE TITLE
FNX2-15552 ⁃ Amoled and oled true black support for them and reader

### ISSUE THREAD

**Issue by johnny88** [mozilla-mobile/fenix#12927]
### What is the user problem or growth opportunity you want to see solved?
The black in the dark theme and especially the reader are not true black. Having true black as an option would help reduce battery usage for those with OLED and AMOLED displays.

### How do you know that this problem exists today? Why is this important?
I use Firefox quite a bit and it is often my main power draw. Changing this would have reduce my battery usage (and presumably others). Making it the default for dark mode would help people's battery life without them having to know the details of how AMOLED and OLED render true black.

### Who will benefit from it?
Anyone who uses firefox, has an AMOLED and OLED display and uses dark mode.

**Comment by kbrosnan** [comment]
Duplicate #1938
