### ISSUE TITLE
Remove the open in app prompt.

### ISSUE THREAD

**Issue by complexengine** [mozilla-mobile/fenix#12939]
### What is the user problem or growth opportunity you want to see solved?
I want to open YouTube in a private tab but Fenix forces to open in-app.

### How do you know that this problem exists today? Why is this important?
If I go to youtube.com in a private tab, I have no other choice than opening it in the app. The prompt is annoying for me.

### Who will benefit from it?
People who do not trust apps. Also, people who want to avoid installing useless apps.

**Comment by ShatteredPixel** [comment]
There is currently a bug with this behaviour: https://github.com/mozilla-mobile/fenix/issues/12670

I have asked feature #12626 to make the "Open links in apps" a bit better and flexible.

Thank you. :)

**Comment by liuche** [comment]
This should be fixed by #12670 which was landed 10 days ago, so closing it.
