### ISSUE TITLE
FNX2-15560 ⁃ Investigate UI Test false positive passes

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#12938]
A few times recently when PRs are closed/opened, CI will pass and a bad commit (meaning tests should have failed) will then land and reliably fail on master. Why is CI passing on these PRs :thinking: 

Examples: 

* https://github.com/mozilla-mobile/fenix/pull/12925
* https://github.com/mozilla-mobile/fenix/pull/12917

**Comment by ekager** [comment]
cc @rpappalax is this something your team can take a look at?

**Comment by ekager** [comment]
Apparently this is a Flank issue with the recent update https://github.com/Flank/flank/pull/917 
We we are waiting for a new release

**Comment by AaronMT** [comment]
Should be fixed with Flank v20.08.0

https://github.com/mozilla-mobile/fenix/commit/4b87f160682cf538f830ae86c27a277f885c6baf
