### ISSUE TITLE
FNX-4934 ⁃ New open tab notification

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1293]
As a user, when I long press on a link to open a new tab, I want to see an indication that the new tab has opened, and have the option to easily navigate to it or stay on the current page.

[In Fennec this is surfaced as a snackbar]

### Acceptance Criteria
I can see that a new tab has opened and I am able to easily navigate to it.
I can see that a new tab has opened and I can choose to stay on my current page.

**Comment by mheubusch** [comment]
@topotropic Hi - have you addressed this in your open new tab/reload existing tab designs? @mheubusch for tracking

**Comment by mheubusch** [comment]
@topotropic Hi - have you addressed this in your open new tab/reload existing tab designs? @mheubusch for tracking

**Comment by mheubusch** [comment]
@AmyYLee tagging you in on this - do the revised homescreen/Collections designs include a notification as requested above?

**Comment by topotropic** [comment]
> @topotropic Hi - have you addressed this in your open new tab/reload existing tab designs? @mheubusch for tracking

We can either use a Snackbar like in Fennec ("New tab opened SWITCH") or we can work with animation to indicate that a new tab was opened in the background (cc @AmyYLee). I'd suspect Snackbar is more realistic for MVP.

**Comment by mheubusch** [comment]
UX decision: We will use a snackbar as proposed above. Text should be New tab opened SWITCH

**Comment by vesta0** [comment]
@mheubusch are you good with the current snackbar (from A-C) or is UX working on Fenix specific designs for this?

**Comment by AmyYLee** [comment]
@vesta0 @mheubusch we currently have a Fenix snackbar that we can use for this.

**Comment by bsurd** [comment]
As mentioned in #1836 opening a new private tab and switching does not work from normal browsing, works without any kind of issues in private browsing.

**Comment by vesta0** [comment]
@bsurd can we close this issue since the new open tab notification has been build and it works in all scenarios except for the scenario addressed in #1836 ?
