### ISSUE TITLE
FNX2-15569 ⁃ [Bug] Phantom ticks in save to collection

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#12947]
## Steps to reproduce
Have many tabs open; I have 50. From Fenix homescreen Save to Collection or long press on a tab in tabs list,  start selecting tabs to save and scroll down to select more.

### Expected behavior
Tabs have no tick until selected for saving to collection.

### Actual behavior
Some tabs are already ticked but this is a "phantom", they are not really selected because selecting them leaves the tick and increases the tabs selected count.

Worse,  whilst selecting and deselecting tabs the tick marks change! This makes savingmore than a few tabs to collection very difficult.

### Device information
* Android device: Nokia 8 on Android 9
* Fenix version: Nightly 200725 06:01 (Build #22070613)
AC: 52.0.20200724130127, 71b462d5b
GV: 80.0a1-20200723095657
AS: 61.0.10

**Comment by madb1lly** [comment]
Hi @ekager,
You're on the ball today! But you know it's Saturday right? 😉
Cheers 🙂

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200727 from 7/27`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200728-095734](https://user-images.githubusercontent.com/51314259/88633848-39c81900-d0be-11ea-8418-34f308bfa3d3.gif)

**Comment by madb1lly** [comment]
Hello @AndiAJ,

Please recheck and consider reopening. I can still create a subset of this bug - if I quickly select and deselect some tabs then I can make the number of tabs selected exceed the number of tabs with a tick by 1, e.g. if 8 tabs show tick then I can make it say 9 selected.

Maybe this is caused by a different bug and therefore could be opened as a new issue, but please recheck.

Cheers 🙂

**Comment by AndiAJ** [comment]
Hi @madb1lly , thx for the feedback. ☺️ 

Unfortunately  I wasn't able to repro the count inconsistency on today's **`Nightly Build #200728 from 7/28`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

Could you please file a separate issue ? and perhaps upload video for a better overview?

**Comment by madb1lly** [comment]
Hello @AndiAJ,
It seems difficult to reproduce! I did manage it a couple of times earlier but I can't do it now, therefore it will be difficult to video.

Anyway, what tool do you recommend for recording the video? Is there something in Android developer options?

Thanks,
Will

**Comment by AndiAJ** [comment]
Hey @madb1lly , I usually use AZ Screen Recorder. (Play Store)
Understood, I'll give it a try, maybe at some point I'll get lucky ☺️

**Comment by AndiAJ** [comment]
@madb1lly I think I've found the problem #13025

**Comment by madb1lly** [comment]
Hi @AndiAJ yes that looks like! Thanks 🙂
