### ISSUE TITLE
[Feature Request] Customize position from Top Sites and Collections.

### ISSUE THREAD

**Issue by bailinhuang** [mozilla-mobile/fenix#12949]
### What is the user problem or growth opportunity you want to see solved?
I want to be able to move own the collections and top sites from the homepage to the bottom just like how we are able to with the search bar. It is a better UX for big phones (which are prevalent in this era). 

### How do you know that this problem exists today? Why is this important?
It is hard to tap on the icons up in the screen when the phone is long or big. 

### Who will benefit from it?
Users will be able to tap and access the top sites and collections with ease.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3981)

**Comment by ShatteredPixel** [comment]
for Top sites there's an open issue: https://github.com/mozilla-mobile/fenix/issues/8305

**Comment by bailinhuang** [comment]
This is different. Me as a user have a hard time tapping on the upper levels of the screen to tap on a top site or a collection. 
For example, the reason I use the search bar on the bottom is because it's easier to tap and I would like the same for Collections and Top Sites. 
![see how high it is?](https://user-images.githubusercontent.com/24628727/88485408-b29a6a00-cf32-11ea-84d1-70318989433f.jpg)

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
