### ISSUE TITLE
Add Bookmarks, History, Collection in the home page

### ISSUE THREAD

**Issue by FenixRevival** [mozilla-mobile/fenix#12941]
### What is the user problem or growth opportunity you want to see solved?
I want to have in the home:

* Top sites
* Bookmarks
* History
* Collection
Ideally I want to customise the order.

### How do you know that this problem exists today? Why is this important?
Legacy Firefox had 3 tabs: top sites, bookmarks, history.
It was a **fast** way to access websites whether it's your bookmarks/collection, the history (useful when you left Firefox and opened it again to access some previous websites not worth bookmark). Top sites and collection are already there.

### Who will benefit from it?
People who want fast and efficient browsing.

**Comment by amkcpu** [comment]
See also #12271 for putting shortcuts to these items on the home screen.

**Comment by FenixRevival** [comment]
Can we have some feedback on it? I've waited since the first release of Nightly for this. I know the team isn't big and they're doing wonderful work. Some stuff have bigger priority, which I perfectly understand.

However it's now in Production. Meaning we have no way of going back (besides ESR, fork, not updating) to the old UI/X. It may be useless for you, but it's actually a regression. The old system was fast few other browser did it, it was a strong point to open a new tab see the home page and quickly use your bookmark/history. 

You can also see the Reddit talk about that [here](https://old.reddit.com/r/firefox/comments/i04iv3/dear_fenix_team_my_honest_letter/)

**Comment by Yves-Be** [comment]
The homescreen also needs to be more easy to access. In Fennec you used to be able to tap the address bar to show it, now you either have to close all tabs, or open a new tab.
What used to be possible in 2 taps now requires many more if you didn't want to open a new tab.
Either a home button like in Chrome should be added, or the Fennec behavior should be restored.

**Comment by Dunexus** [comment]
@Yves-Be 
See the new proposal to address this https://github.com/mozilla-mobile/fenix/issues/13052 and https://github.com/mozilla-mobile/fenix/issues/13053

**Comment by weijarz** [comment]
The top sites / bookmarks list should be added to the search page (The page that appears after you click on the address bar).
This is the fastest way to open a website.

**Comment by nigelh747** [comment]
This is a regression and therefore should not be treated as a "feature request"  but instead a bug or regression

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/12271

**Comment by enderkitsune** [comment]
> 
> 
> This is a regression and therefore should not be treated as a "feature request" but instead a bug or regression

Adding customization options is not a bug or regression.

**Comment by FenixRevival** [comment]
> 
> 
> > This is a regression and therefore should not be treated as a "feature request" but instead a bug or regression
> 
> Adding customization options is not a bug or regression.

It is when you remove something that was adding a faster and better way to navigate. I remind you this was in Fennec, it's not something _new_ we want.

**Comment by bebuch** [comment]
> See also #12271 for putting shortcuts to these items on the home screen.

A shortcut means you need two clicks, this issue request not to add a shortcut but the actual contents like in the old interface. Open Firefox - click on a bookmark.

Unfortunately collections are currently not an alternative because of #10417.

The new interface feels still very beta, nevertheless, thanks a lot for going forward!

**Comment by Imold** [comment]
This is a MUST FIX! I can not update until I can make the home default to my bookmarks.

**Comment by davidmegginson** [comment]
I have installed the latest beta in parallel with 68.11 to see if I can somehow make it work for me. The new Collections feature would be a partial-workaround for the lost bookmarks page on new tabs, but it's still awkward and a step backwards in functionality.

Bookmarks are one of the building blocks of the web. Don't make them hard to use.

**Comment by Imold** [comment]
> 
> 
> The new Collections feature would be a partial-workaround for the lost bookmarks page on new tabs, but it's still awkward and a step backwards in functionality.
> 

Collections will never work as a workaround for me. If I bookmark something on my pc it won't be added to collections on my phone, and if I add something to collections on my phone it won't be added to my bookmarks on my pc. Firefox sync is central to me using firefox on android, I have to use bookmarks, I can't use collections.

**Comment by davidmegginson** [comment]
> > The new Collections feature would be a partial-workaround for the lost bookmarks page on new tabs, but it's still awkward and a step backwards in functionality.
> 
> Collections will never work as a workaround for me. If I bookmark something on my pc it won't be added to collections on my phone, and if I add something to collections on my phone it won't be added to my bookmarks on my pc. Firefox sync is central to me using firefox on android, I have to use bookmarks, I can't use collections. I can not update firefox until I can have bookmarks on the homepage.

Fully agree. It's only a partial workaround, and losing bookmarks as a new-tab option (and standalone page instead of popup) is a serious loss of functionality from the previous FF release. I've also noticed that the sort order of bookmarks is different now in the mobile browser, and folders don't appear together before links any more, so it's a mess to look at.

**Comment by liuche** [comment]
Will be addressing this in ##12065
