### ISSUE TITLE
[Bug] Speeded-up Videos have Distorted Audio.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#12951]
Not sure if this belongs here or to 'Web content issue report', but i decided on [BUG].

## Steps to reproduce
1. Go on Youtube
1. Start any video, preferably one that consists of a constant monologue so you can hear the bug properly.
1. Change the speed and listen. It's more noticeable with sped-up videos though i think so it's best to try 1.25 speed.

### Expected behavior
The same experience as the one in the old Firefox.

### Actual behavior
The Voices start sounding as if they were a robot's voice. Just try it out.

### Device information
* Android device: Samsung Galaxy S9
* Fenix version: 200725

**Comment by Glitchy-Tozier** [comment]
(By the way, this also seems to be a problem in Firefox Klar/Focus)

**Comment by ekager** [comment]
Closing for #8456
