### ISSUE TITLE
[Feature Request] Import/Export bookmark as HTML file

### ISSUE THREAD

**Issue by Domiuns** [mozilla-mobile/fenix#12953]
### What is the user problem or growth opportunity you want to see solved?
I think with this function the browser becomes better and more flexible

### How do you know that this problem exists today? Why is this important?
Much browser have this function, and desktop version have this important feature

### Who will benefit from it?
All user who don't use sync

Hi, I have been using Firefox for many years and the mobile version has always been deprived of this convenient feature.

**Comment by cadeyrn** [comment]
Duplicate of #417.

**Comment by ekager** [comment]
Closing for #417
