### ISSUE TITLE
Add copy option to QR scan dialog

### ISSUE THREAD

**Issue by Groctel** [mozilla-mobile/fenix#12959]
### What is the user problem or growth opportunity you want to see solved?
When using the browser's scan feature you can either "deny" and "allow" entering the link to the browser. A copy option that doesn't open it (or search for it in the default search engine) would let users use the browser to scan for any QR code that isn't a link (for example, a Syncthing ID) without needing to search for it in the default search engine and copying it from the search bar. It would also work great for copying the link and sending it to other people in a group chat before opening it.

### How do you know that this problem exists today? Why is this important?
It's not very important or even prioritary, really, but I believe it's a small improvement that can make the browser a bit more complete and cover more use cases.

### Who will benefit from it?
Everyone who uses the scan feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3995)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807388

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
