### ISSUE TITLE
Reduce the width/space between 2 tabs when switching tabs via gesture on the address bar

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#12952]
Currently the space between 2 tab is a bit high if it could match with how Chrome browser behaves then it'll provide more of preview of the tab the user is switching to. Keeping them that far apart would make it feel a bit disconnected too.

Thank you. :grinning:

### Chrome browser width/space between tabs when swipe gesture is used on address bar:
![Screenshot](https://user-images.githubusercontent.com/68282543/88477453-be4f5600-cf5d-11ea-96f5-7315fc853c6b.png)UNITO-UNDERSCORE!20200726-162600.png!

### This is the width/space between 2 tabs when gesture is used on Fenix:
![Screenshot](https://user-images.githubusercontent.com/68282543/88477468-d6bf7080-cf5d-11ea-9650-203bc6c954c2.png)UNITO-UNDERSCORE!20200726-162630.png!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3987)

**Comment by ShatteredPixel** [comment]
Cc @person808

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807061

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
