### ISSUE TITLE
[Feature Request] Show HTML-code

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#12955]
### What is the user problem or growth opportunity you want to see solved?
For various reasons, it can be interesting or helpful to look into the html-code. No need to do things as complicated as on desktop-firefox, just copy the old Firefox's "Show HTML"-feature.

### Who will benefit from it?
People who want to look into stuff like meta-tags, people that want to search for things that aren't displayed properly on the website, people who want to copy code snippets, etc.

**Comment by cadeyrn** [comment]
Duplicate of #3972.

**Comment by kbrosnan** [comment]
Closing as a duplicate
