### ISSUE TITLE
Add  Search Engine

### ISSUE THREAD

**Issue by minutesinch** [mozilla-mobile/fenix#12964]
### What is the user problem or growth opportunity you want to see solved?
users need som others search engine like duckduckgo, by default 

### How do you know that this problem exists today? Why is this important?
users need privacy so better add duckduck go in search engines in firefox by default.

**Comment by cadeyrn** [comment]
You already can add other search engines.

**Comment by hakkikaancaliskan** [comment]
> You already can add other search engines.

This behaviour currently blocked by https://github.com/mozilla-mobile/fenix/issues/12954

**Comment by kbrosnan** [comment]
* Open Firefox
* Tap 3 dot menu
* Tap `Settings`
* Tap `Search`
* Tap `Add search engine`
* Fill out the correct information
