### ISSUE TITLE
FNX-4936 ⁃ [Bug] Wrong default apps settings open on some devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1296]
## Steps to reproduce
On one of these 2 devices (or probably any Huawei with Android >6):
Huawei Honor 8 (Android 7.0) & Huawei P20 lite (Android 8)

1. Open Fenix, go to Settings>Make default browser.
1. Verify the Settings menu displayed.
    1. Expected behavior
System's Settings>Apps>Default apps menu is displayed.
    1. Actual behavior
System's Settings>Apps>Fenix>Open by default menu is displayed, on these 2 devices.

* not reproducing on Galaxy Note 8 (Android 9), Google Pixel (Android 9), Nokia 6 (Android 7.1.1).
    1. Device information
* Android device: Huawei Honor 8 (Android 7.0) & Huawei P20 lite (Android 8)
* Fenix version: 3/30 build.

**Comment by vesta0** [comment]
@sblatz please verify that this is working as intended.

**Comment by sblatz** [comment]
@sv-ohorvath are you able to provide a screenshot? This behavior seems fine at first blush.

**Comment by sv-ohorvath** [comment]
Here is a recording from a Huawei P20 lite: 
![20190404_155226](https://user-images.githubusercontent.com/4037709/55557179-ef18d580-56f1-11e9-98a1-d79e0a1b89f6.gif)

These are the settings if you navigate :
![20190404_155830](https://user-images.githubusercontent.com/4037709/55557484-8e3dcd00-56f2-11e9-92be-96e0e5f4bbbe.gif)

**Comment by sblatz** [comment]
Interesting, I wonder if Huawei is handling their settings instance differently.

@sv-ohorvath thank you for the demos! Do Fennec or Focus handle this **correctly**?

**Comment by sv-ohorvath** [comment]
Hm, yes, both are doing the same thing.

**Comment by Vv2233Bb** [comment]
Other apps not made by mozzila have the same issue. It is definitely Huawei's problem.

**Comment by sblatz** [comment]
I would say this is not a bug we should worry about then, @vesta0.
