### ISSUE TITLE
[Bug] embed element for pdf

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#12967]
## Steps to reproduce
1. Go to http://plantuml.com/fr/guide

### Expected behavior
Show an actionable download

### Actual behavior
blank page

### Device information
* Android device: ANdroid 10 Pixel 2
* Fenix version: Firefox 81

### Note
webcompat issue: https://github.com/webcompat/web-bugs/issues/55689

```html
<div id="root">
  <embed src="http://pdf.plantuml.net/PlantUML_Language_Reference_Guide_en.pdf" type="application/pdf" width="100%" height="100%">
</div>
```

On Chrome a download button is displayed.

**Comment by kbrosnan** [comment]
Same behavior on desktop with `pdfjs.disabled` set to `true`. Opened Gecko bug bz-1655525.

**Comment by karlcow** [comment]
a test case https://www.la-grange.net/2020/07/28/moz/embed-pdf.html
