### ISSUE TITLE
FNX2-15585 ⁃ [Bug] Parent tab not selected when closing last private tab with a non-private parent

### ISSUE THREAD

**Issue by issue-dispenser** [mozilla-mobile/fenix#12966]
## Steps to reproduce
1. **Make sure there are no open private tabs**
1. In non-private mode, open a tab containing links
1. Long-press a link and select "Open link in private tab"
1. Tap the prompt "New private tab opened" to switch to the new private tab
1. Press the back button to close the tab

### Expected behavior
The private tab is closed, and its non-private parent tab (from step 1) is selected.

### Actual behavior
The private tab is closed, and instead the home page is shown.

### Additional Info
If there _are_ other open private tabs, then the non-private parent tab is selected as expected. However, in this case there's a minor UI issue where Fenix temporarily shows the toolbar at the bottom with the tab counter decreasing from `N` to `N-1` private tabs before showing the parent tab.

### Device information
* Android device: Samsung Galaxy S7
* Fenix version: Nightly 200726 10:10

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200728 from 7/28`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200728-115539](https://user-images.githubusercontent.com/51314259/88642972-cb895380-d0c9-11ea-89a7-bef09c243d0c.gif)
