### ISSUE TITLE
[Bug] The active tab is highlighted in the recent history pop-up only after the page is loaded

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12972]
## Steps to reproduce
1. Load mail.yahoo.com, news.google.com, gmail.com and espn.com;
1. Long tap on the Device Back Button;
1. Select a different link from the list (e.g news.google.com);
1. Long tap on the Device Back Button;
    1. Expected behavior
A pop-up with the recent history is displayed with the focus on the active tab.
    1. Actual behavior
A pop-up with the recent history is displayed with the focus on the previous active tab, until the page is completely loaded.
    1. Notes
![20200727](https://user-images.githubusercontent.com/48799384/88540999-b7d3e380-d01c-11ea-8496-286fa0bee283.gif)UNITO-UNDERSCORE!151809!

### Device information
* Android device: Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Huawei P9 Lite (Android 7), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 200727 Build #22090608 GV 80.0a1 from 7/27

**Comment by person808** [comment]
Fairly sure this needs to be done in AC, all we do is observe updates to the sessions `HistoryState`
