### ISSUE TITLE
FNX-4937 ⁃ [Bug] No data shows up in Adjust

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1297]
After implementing #106, data should be showing up in Adjust.

@kbrosnan or @npark-mozilla - could you please help out verifying with the engineers what is going on and how to fix it.

![](https://user-images.githubusercontent.com/122897/55323087-15b5e280-544c-11e9-828e-ed388e77f569.png)

/cc @st3fan

**Comment by npark-mozilla** [comment]
Actually, @rpappalax should know a little more than me about telemetry - cc'ing him here

**Comment by sv-ohorvath** [comment]
Was this verified? Since it's closed I suppose I can remove the QA label now.
