### ISSUE TITLE
Firefox Home is missing from the recent history pop-up

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12974]
## Steps to reproduce
1. Launch Fenix and in a new tab visit 3-4 pages;
1. Long tap on the Device Back Button;
1. Observe the pages displayed in the recent history pop-up;
    1. Expected behavior
Firefox Home is displayed at the bottom of the list.

### Actual behavior
Firefox Home is missing from the recent history pop-up.

### Notes
![Screenshot](https://user-images.githubusercontent.com/48799384/88542456-1d28d400-d01f-11ea-9105-241d55c870bc.png)UNITO-UNDERSCORE!20200727-153512!

### Device information
* Android device: Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Huawei P9 Lite (Android 7), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 200727 Build #22090608 GV 80.0a1 from 7/27

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4020)

**Comment by eliserichards** [comment]
I'm not sure if we want the home screen to appear as a "visited" page. I think this might be a feature request -- @vesta0 for thoughts

**Comment by vesta0** [comment]
Yes I have added the `feature request` label. Unlike Fennec, the Fenix homescreen is not a new tab so it won't show up in history.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813096

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
