### ISSUE TITLE
FNX2-15595 ⁃ [Bug]Drop 3 digit numbers from the Tabs Tray's open tabs counter

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12976]
## Steps to reproduce
1. Open 100+ tabs
1. Open the Tabs Tray 
1. Check the Open tabs counter from the Tabs Tray 

### Expected behavior
Should properly display the ∞ sign in the Tabs Tray Open tabs counter

### Actual behavior
Padding problems.
Discrepancy between the Nav bar tabs counter and the Tabs Tray Tabs counter

### Device information
* Android device: all
* Fenix version: Nightly 200727 from 7/27

### Notes
► Screenshot Tabs Tray counter
![rsz](https://user-images.githubusercontent.com/51314259/88543757-1bf8a680-d021-11ea-89a3-7831d3fa2d60.png)UNITO-UNDERSCORE!2screenshot!UNITO-UNDERSCORE!20200727-153303!

► Screenshot Nav bar tabs counter
![rsz](https://user-images.githubusercontent.com/51314259/88543924-56fada00-d021-11ea-826f-b993d761f79b.png)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!20200727-153318!

**Comment by shen714** [comment]
I'd like to work on this.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200819 Build #2015758835 from 8/19 with Pixel 2 (Android 9). 

![rsz_screenshot_20200819-120217](https://user-images.githubusercontent.com/48799384/90615169-692cfa00-e214-11ea-8097-0a8b0dcb1dc0.png)

I will remove the qa:needed label and close this issue.
