### ISSUE TITLE
[Bug] In Dark mode, the active tab from recent history pop-up is barely visible

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#12978]
## Steps to reproduce
1. Launch Fenix in Dark mode and visit 3-4 pages in the same tab;
1. Long tap the device back button to open the recent history pop-up;
1. Observe the active tab.
    1. Expected behavior
The active tab from recent history pop-up is visible in Dark mode.
    1. Actual behavior
The active tab from recent history pop-up is barely visible in Dark mode.
    1. Notes
![20200727](https://user-images.githubusercontent.com/48799384/88544640-629ad080-d022-11ea-8067-5b5d1414d07f.gif)UNITO-UNDERSCORE!155936!

### Device information
* Android device: Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Huawei P9 Lite (Android 7), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 200727 Build #22090608 GV 80.0a1 from 7/27

**Comment by s-ankur** [comment]
Very similar to and less genaral than #12888

**Comment by liuche** [comment]
Makes sense! Let's dupe this to #12888
