### ISSUE TITLE
[Bug] Show collection saved snackbar above FAB

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#12971]
## Steps to reproduce
Select a few tabs and save them to a collection

### Expected behavior
Snackbar appears above new tab floating action button (FAB)

### Actual behavior
It's below and pushes FAB up

**Comment by rafalopilowski1** [comment]
I'll take that one.

**Comment by rafalopilowski1** [comment]
#16311

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201105`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201105-093957](https://user-images.githubusercontent.com/51314259/98211766-378e1a00-1f4b-11eb-8c77-8a3a0a396192.gif)
