### ISSUE TITLE
[Bug]Open tabs number padding issues

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12975]
## Steps to reproduce
1. Open 10 tabs 
1. Open the Tabs Tray check Open tabs icon

### Expected behavior
Properly displayed value

### Actual behavior
Improperly displayed, padding issues.

### Device information
* Android device: all
* Fenix version: Nightly 200727 from 7/27

### Notes
► Screenshot
![rsz](https://user-images.githubusercontent.com/51314259/88542789-a9d39200-d01f-11ea-9d22-75ccbd727aa5.png)

**Comment by eliserichards** [comment]
This might need to be re-evaluated after #8791

**Comment by eliserichards** [comment]
Tagging QA to see if this is still a valid issue 😄

**Comment by LaurentiuApahideanSV** [comment]
I retested the issue on Firefox RC 91.2.0 and Nightly 2021-08-18 and the issue no longer occurs.
![10](https://user-images.githubusercontent.com/50983519/129890173-8e70e72c-319e-4015-b96b-e56a4e281ca2.png)

### Device used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 0)

**Comment by cadeyrn** [comment]
FWIW yesterday it happened two times for me that the tab number was totally misplaced (both times with 9 and not with 10 tabs, it was much worse than in the screenshot of the original report). Unfortunately it was not possible for me to reproduce it a third time and to find steps to reproduce.
