### ISSUE TITLE
FNX2-15600 ⁃ [Bug] Deeplink scheme for Nightly no longer works

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#12983]
## Steps to reproduce
1. Install release and nightly versions of Fenix.
1. Send intent using: `adb shell am start -a android.intent.action.VIEW -d fenix://settings`
1. Send intent using: `adb shell am start -a android.intent.action.VIEW -d fenix-nightly://settings`

### Expected behavior
1. At 2, Only the **release app** launches into settings.
1. At 3, Only the **nightly app** launches into settings.

### Actual behavior
1. At 2, the app chooser is shown.
1. At 3, nothing happens.

### Device information
* Android device: Android 10
* Fenix version: 79.0.0 RC and Nightly

Discovered during testing of https://github.com/mozilla-mobile/fenix/issues/7661#issuecomment-664350860.

**Comment by jonalmeida** [comment]
This seems to be related to the change where we simplified the fenix releases: https://github.com/mozilla-mobile/fenix/commit/7e7d69cb8e4514c86c4677b3b18193c5cb66f884

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly Build #200729 from 7/29 using a Google Pixel 3a (Android 10)

✔️ Nightly - **adb shell am start -a android.intent.action.VIEW -d fenix-nightly://settings**
![20200729-113941](https://user-images.githubusercontent.com/51314259/88779248-3aca7a80-d192-11ea-844e-f15849c4ba85.gif)


✔️ RC 79.0.0 from 7/21 - adb shell am start -a android.intent.action.VIEW -d fenix://settings
![20200729-113854](https://user-images.githubusercontent.com/51314259/88778744-8b8da380-d191-11ea-9065-de03d27fabac.gif)
