### ISSUE TITLE
[Bug] Keyboard does not show after switching to a private tab and back

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#12982]
## Steps to reproduce
* Open google.com in a normal tab
* Open / Switch to any private tab
* Switch back to google.com
* Tap the search box

### Expected behavior
* The keyboard shows

### Actual behavior
* The keyboard does not show

### Device information
* Android device: Samsung Galaxy A50
* Fenix version: Nightly 200727 06:00 (Build #22090608)
AC: 52.0.20200725130253, f41b7fbbc
GV: 80.0a1-20200724093206
AS: 61.0.10

**Comment by helloworld1** [comment]
This happens on the latest beta build also. It also happens on almost every website including searching in GitHub. Closing and reopening may resolve the issue temporally.

80.0.0-beta.4 (Build #2015756491)
AC: 52.0.2, 907812bd3
GV: 80.0-20200804180257
AS: 61.0.10

**Comment by sflorean** [comment]
I was able to reproduce this with Google Pixel 4 XL (Android 11) on scribd.com.

**Comment by andreicristianpetcu** [comment]
here is a logcat result if it helps https://my.owndrive.com/index.php/s/7SQogPAns5iqzXg

I'm using hacker keyboard from fdroid

**Comment by st3fan** [comment]
Could this be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1673681 ?

**Comment by miDeb** [comment]
FWIW I can't seem to reproduce this anymore, might be fixed.

**Comment by makotokato** [comment]
> Could this be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1673681 ?

I guess that this is fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1658948 If "search box" is google.com's editbox.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly 210120`** and **`85.1.0-rc.1`** using the following devices:
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)
