### ISSUE TITLE
FNX2-15602 ⁃ [Bug] keyboard stays up on tab switching using swipe

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12990]
## Steps to reproduce
Open keyboard e.g for writing a comment here
Drag out the dynamic toolbar and swipe to switch tab

### Expected behavior
Keyboard dismissed

### Actual behavior
Not dismissed

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200724 06:05 (Build #22060613)
AC: 52.0.20200723130248, 69562438f
GV: 80.0a1-20200722094100
AS: 61.0.10

**Comment by quaintdev** [comment]
Theirs more to this. When using keyboard to write a comment one can basically swipe on screen anywhere to switch the tab not just the address bar.

**Comment by s-ankur** [comment]
@quaintdev yes that is a seperate issue #12990

**Comment by person808** [comment]
Going to disable the gesture when the keyboard is open as part of the fix for #12865 so this should become a non-issue.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200730`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200730-125055](https://user-images.githubusercontent.com/51314259/88909870-543bf700-d264-11ea-8a00-2d5a8505fad2.gif)
