### ISSUE TITLE
FNX2-15604 ⁃ [Bug] you have to be extremely precise to click the save to collection button in tab tray

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12991]
## Steps to reproduce
Open tab tray and long click to open multi select
Click on save to collection icon

### Expected behavior
It's easy to click the button

### Actual behavior
You have to click exactly at the center
Even a click here won't press the button
![Screenshot](https://user-images.githubusercontent.com/33252312/88575410-76195c00-d061-11ea-960a-1db6fdd854f0.png)UNITO-UNDERSCORE!20200727-233211!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200727 06:00 (Build #22090608)
AC: 52.0.20200725130253, f41b7fbbc
GV: 80.0a1-20200724093206
AS: 61.0.10

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #200727 from 7/27`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ Checked it with the Accessibility Scanner and it falls in the 48dp threshold 

► Video
![20200728-110945](https://user-images.githubusercontent.com/51314259/88639335-5ae03800-d0c5-11ea-92d9-ada09409113d.gif)
