### ISSUE TITLE
[Telemetry] Add distributionID to baseline ping

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1299]
#### Description & Product Manager 
* As a BD manager, I want to know from which distribution partner users installed the app from.

#### What questions will you answer with this data?
* By knowing what partner install the user came from allows us to understand their usage better

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
* Be able to understand from what partner / distro  users came from

#### What probes (suggested, if applicable)
* disributionID, see row 24 in https://docs.google.com/spreadsheets/d/1P2_aGEE9OtjM3x71d0GBhnHDhzxEL02xEHuKn1no23E/edit#gid=0

### Dependencies (Added by PM and Eng)
* Core ping / baseline ping

### Acceptance Criteria (Added by PM)
* Baseline pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4048)

**Comment by csadilek** [comment]
We did introduce this and add the distributionID to the FirstSession ping, which satisfied the initial requirements above. There will be more work needed related to this but tracked in separate issues.
