### ISSUE TITLE
FNX2-15603 ⁃ [Bug] Weird behaviour after deleting tab in tab tray multi select

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12992]
## Steps to reproduce
Open tab tray and long click to multi select
Delete the selected tab

### Expected behavior
Multi select goes away

### Actual behavior
Multi select stays and causes a lot of weird stuff

### Device information
* Android device: Asus Zenfone
* Fenix version: 
Nightly 200727 06:00 (Build #22090608)
AC: 52.0.20200725130253, f41b7fbbc
GV: 80.0a1-20200724093206
AS: 61.0.10

**Comment by s-ankur** [comment]
![Screenshot_20200727-234010_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/88576098-87169d00-d062-11ea-97f6-c787ed896bb0.png)
No tab is selected, still 1 is shown

**Comment by AndiAJ** [comment]
Hi @ekager , unfortunately it's **still reproducible** on the latest **`Nightly Build 200729 from 7/29`** using the following devices:
 • Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

The check mark isn't displayed on the highlighted tab
The user can still delete the highlighted tab
The tab selection count isn't properly adjusted

► Video
![20200729-094323](https://user-images.githubusercontent.com/51314259/88768997-89711800-d184-11ea-8fcb-86770a88aa13.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly Build 200730`** and `**Fenix Beta 80.0.0-beta-1**` using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200730-124207](https://user-images.githubusercontent.com/51314259/88908531-a8de7280-d262-11ea-916a-61c658234262.gif)
