### ISSUE TITLE
FNX-4939 ⁃ [Telemetry] Add default search to baseline ping

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1300]
#### Description & Product Manager 
* As a product manager, I want to know what default search provider our users pick

#### What questions will you answer with this data?
* By knowing what search provider was picked, we can better understand their usage

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
* Be able to understand what search providers are most used.

#### What probes (suggested, if applicable)
* default search, see row 26 in https://docs.google.com/spreadsheets/d/1P2_aGEE9OtjM3x71d0GBhnHDhzxEL02xEHuKn1no23E/edit#gid=0

### Dependencies (Added by PM and Eng)
* Core ping / baseline ping

### Acceptance Criteria (Added by PM)
* Baseline pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by bbinto** [comment]
@st3fan - please update after the search meeting on April 3 - these requirements might change

**Comment by sblatz** [comment]
Let's take into consideration whether or not we're sending custom search engines too. @liuche made a point to _not_ send these at least when using search shortcuts. We should probably adhere to that here too.

(reference: https://github.com/mozilla-mobile/fenix/pull/1269#discussion_r270609457)

**Comment by vesta0** [comment]
Dup of #800
