### ISSUE TITLE
[RTL] No padding in left boundary of URL bar

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/fenix#13005]
**Note:**
This is a duplicate of mozilla-mobile/android-components#5762, seeing that historically most RTL bugs were fixed here and not under android-components.

With an RTL locale padding seems wrong for text in address bar's left boundary.

![תמונה](https://user-images.githubusercontent.com/18016656/88596047-e679aa80-d06c-11ea-8b14-be0af12421d8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4067)

**Comment by softvision-miralobontiu** [comment]
This is reproducible on the latest Nightly build from 9/10, on RC 80.1.3, and on Beta build 81.1.1-beta.3 with Samsung Galaxy Tab S6 (Android 9).

![Untitled](https://user-images.githubusercontent.com/40694158/92890399-c2f1a000-f41f-11ea-9e52-5c0a971d98ea.png)

**Comment by ItielMaN** [comment]
Looking at the above screenshot, the url should also be aligned to the right (though still appeared as LTR).

**Comment by sflorean** [comment]
Reproducible on 86.1.0 RC build with Samsung Note 10 (Android 11).

**Comment by lobontiumira** [comment]
Reproducible with Beta 88.0.0-beta.1 with a x86 emulator Nexus 9 (Android 9).

**Comment by ItielMaN** [comment]
Still an issue.

**Comment by ItielMaN** [comment]
Still an issue.

**Comment by ItielMaN** [comment]
Still an issue.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807730

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
