### ISSUE TITLE
FNX2-15612 ⁃ [Bug] White screen when launching PWA

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#13008]
## Steps to reproduce
* On migration build RC1 (or was it 2?)...
* Install a PWA (e.g. https://mobile.twitter.com/home
* Force-swipe close Firefox & the PWA if opened
* Launch PWA from homescreen

### Expected behavior
PWA launches

### Actual behavior
White screen; it never reaches the application.

This does not occur if fenix is already running in the background.

I can't reproduce on my local nightly (July 27-ish).

### Device information
* Android device: P2
* Fenix version: migration RC1 (or 2? installed from taskcluster)

**Comment by liuche** [comment]
STR seems to indicate it's only on the migration/Production build. (Current RC2 is here: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.fennec-production.2020.07.24.revision )

I'm going to see if @NotWoods has any ideas - maybe there's something different about the migration code/build that's not happening in Nightly? (there are instructions for self-signing in the README if you want to test on a production flavor)

**Comment by NotWoods** [comment]
Sounds just like #10689, which we identified as a GeckoView issue. See BZ-1641715

**Comment by liuche** [comment]
Closing to match #10689 which has been verified
