### ISSUE TITLE
[Task] Remove feature flag for edit logins

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#13001]
Remove the feature flag after #11251 has been completed and confirmed in prod: https://github.com/mozilla-mobile/fenix/blob/52a9acf87da2b064e202a8c3a2a10ed45ffc75cd/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L20

**Comment by Bawya1098** [comment]
@data-sync-user, Have an added PR.
