### ISSUE TITLE
FNX2-15618 ⁃ { Feature Request } Dark Mode on Mozilla browser on Laptop

### ISSUE THREAD

**Issue by anmol257** [mozilla-mobile/fenix#13019]
Its high time. This feature must be included within the browser by default.
Working without it for a long stretch of time is harmful for eyes
   Everybody needs it.

PS: Kindly forward to the concerned team.

**Comment by cadeyrn** [comment]
Fenix already has a dark mode. So what exactly are you requesting? 🤔

>  Everybody needs it.

No, that's definitely not true…

**Comment by anmol257** [comment]
> 
> 
> Fenix already has a dark mode. So what exactly are you requesting? And what do you mean by "on Mozilaa Laptop"? 🤔
> 
> > Everybody needs it.
> 
> No, that's definitely not true…

I'm talking about Mozilla browser for laptop not mobile. And the Mozilla team can take a survey if they want to find out whether everybody needs it or not.
 It is true there are some extensions for dark mode at present but the thing is they don't 

- work on the homepage

- We can't be sure if they are spying or not.

Having it as a feature included by Mozilla would provide trust and sigh of relief to million of users while making web browsing more eye-friendly.

Rest is up 2 u

**Comment by anmol257** [comment]
> 
> 
> Fenix already has a dark mode. So what exactly are you requesting? And what do you mean by "on Mozilaa Laptop"? 🤔
> 
> > Everybody needs it.
> 
> No, that's definitely not true…

PS: Fixed the typo in heading.

**Comment by cadeyrn** [comment]
This is **not** the issues tracker for Firefox for Desktop. Please report suggestions for Firefox for Desktop here:
https://bugzilla.mozilla.org/

> And the Mozilla team can take a survey if they want to find out whether everybody needs it or not.

That's not needed. _Nothing_ in the world is wanted by _everbody_.
