### ISSUE TITLE
FNX2-15613 ⁃ Rename mozilla_ui_publicsuffixlist to mozilla_lib_publicsuffixlist

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#13010]
`Deps.mozilla_ui_publicsuffixlist` should be renamed to `Deps.mozilla_lib`_publicsuffixlist and updated in the build.gradle file. The corresponding dependency is named "lib-publicsuffixlist", so the current name is incorrect.

**Comment by Ankur-Khandelwal** [comment]
I would like to contribute.

**Comment by Ankur-Khandelwal** [comment]
@NotWoods I opened the build.gradle file in the master branch. But couldn't find "Deps.mozilla_ui_publicsuffixlist" in it. Can you please guide me through it?

**Comment by NotWoods** [comment]
There are two gradle files: `/build.gradle` (root folder) and `/app/build.gradle` (app folder). You'll need to edit the one inside "app".

**Comment by Ankur-Khandelwal** [comment]
@NotWoods I have submitted a Pull Request. It is asking for a review. Please review it and let me know.
