### ISSUE TITLE
FNX-4941 ⁃ [Telemetry] Add page load ms in baseline ping

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1302]
Similar to Focus: https://github.com/mozilla-mobile/focus-android/blob/master/docs/Telemetry.md#page-load-time-histogram
Similar to Focus: https://github.com/mozilla-mobile/focus-android/blob/master/docs/Telemetry.md#uri-count

#### What questions will you answer with this data?
* As a product manager, I want to know if the app renders websites in a timely fashion and if we can see regressions or improvements over time.

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
* Average page load to understand performance and any regressions/improvements on Fenix + GV

#### What probes (suggested, if applicable)
* page load ms, see row 32 in https://docs.google.com/spreadsheets/d/1P2_aGEE9OtjM3x71d0GBhnHDhzxEL02xEHuKn1no23E/edit#gid=0
* similar to Focus

### Dependencies (Added by PM and Eng)
* Core ping / baseline ping

### Acceptance Criteria (Added by PM)
* Baseline pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by bbinto** [comment]
@georgf - does GleanSDK supports histogram/aggregate numbers for this metric?

**Comment by bbinto** [comment]
Also @cpeterso maybe we should bring this up with the perf team if/how they want this metric and/or if this should be tracked somewhere else.

**Comment by cpeterso** [comment]
@vickychin says that she is talking to the telemetry team (?) about adding telemetry probes for Fenix page loads. I don't know if that is this GitHub issue or a different conversation.

**Comment by bdekoz** [comment]
I'm ok with the perf team tracking this here, and yes, this is the same issue we'd discussed in another perf meeting today.

**Comment by bbinto** [comment]
@bdekoz and @cpeterso 

Ok, I'll close this here then since that's a request/requirement for the perf team, if you need the Fenix team to access or track this metric via the Fenix client, please re-open another ticket.
