### ISSUE TITLE
[Bug] Hide "Sign in with your camera" on devices without camera

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#13037]
We're seeing quite a few crashes of users trying to scan on devices that don't have a camera:
https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9258014/
https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9260856/

On the SearchFragment, we hide the QR scanner based on `Context.hasCamera`, which we should do here as well.

**Comment by st3fan** [comment]
Looking at those crashes, it seems most of these devices are TV Boxes, Media Players or even TVs.

https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9258014/tags/device/

We should absolutely not show the "Sign in with your camera" button, but also take the above in consideration when we prioritize this for a migration fix.

**Comment by liuche** [comment]
Hi @Mugurell, since we didn't finish hershey planning, this is an issue to add to the Hershey sprint, but it's not showing up on Jira 😅 so tagging you here.

**Comment by Mugurell** [comment]
As a different approach we could have the app declaring that it requires camera, so it won't appear in Playstore for devices without camera. But on set-top boxes the app is probably sideloaded...

If there are many people interested into using Firefox on this kind of devices maybe we should look into providing a different UX to better suit their needs?

**Comment by sv-ohorvath** [comment]
There are a few other places from where you can open the Turn on sync page and you still get the Sign in with your camera option:
- sign in button from the onboarding tour
- sign in from Bookmarks>Desktop folder
- sign in from Synced Tabs 
- the share overlay (share tab/collection)
I hope I'm not missing other places.

**Comment by Mugurell** [comment]
Wow, thanks Oana!
Looked in code for other entries but didn't see these .. 🤔
I'll push a new commit for them.

**Comment by Mugurell** [comment]
As an eng note: It would've been awesome to have the camera check in `TurnOnSyncFragment` (which is normally started in all these places) and that to automatically start pairing with email. But this means the transitions from one screen to another would be visible by users who might consider them visual artifacts.
So in all places we have to decide beforehand what options we'll present the user with.

**Comment by softvision-miralobontiu** [comment]
Hi all,
I've verified on the 9/1 Nightly, on the emulator all the "sign-in" scenarios with camera option:
* sign-in button from the onboarding tour,
* sign-in from Bookmarks ->Desktop folder,
* sign-in from Synced Tabs,
* sign-in from the share overlay (share tab/collection, share history/bookmarks items),

and I can confirm that there is no "Sign-in with your camera" option available/displayed.
