### ISSUE TITLE
FNX-4942 ⁃ [Bug] Slow response when selecting history items

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1303]
## Steps to reproduce
1. Go to Library>History
1. Long tap on items to select/unselect them.
    1. Expected behavior
The tap response should be immediate.
    1. Actual behavior
On the Nexus 5, the tap response time is very long (~6s until the checkbox appears).
On Honor 8 it's a bit better but still laggy.
On a Galaxy Note, it works instantly.
![20190401](https://user-images.githubusercontent.com/4037709/55333378-e03ae480-549f-11e9-842d-3626e5140247.gif)UNITO-UNDERSCORE!170120!
    1. Device information

* Android device: Nexus 5(Android 6), Honor 8 (Android 7)
* Fenix version: 4/1

**Comment by sv-ohorvath** [comment]
Loading the history list is really slow as well (if not related, let me know if you need a different issue logged for that).

**Comment by sblatz** [comment]
@sv-ohorvath I filed a follow-up: #1360.
