### ISSUE TITLE
[Bug] Reader Mode -> Save To collection saves the moz extension link

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13036]
## Steps to reproduce
Open a page in reader mode 
Save to collection

### Expected behavior
Actual URL is saved

### Actual behavior
moz-extension url is saved

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by opusforlife2** [comment]
What if the user wants to deliberately save the page in their collection in Reader Mode? So that it directly shows up that way when they open it later?

You still have the option of tapping back and saving the page in your collection that way.

**Comment by s-ankur** [comment]
oh, I hadn't thought about that. If so then perhaps it should save with a more readable link and a favicon

**Comment by s-ankur** [comment]
According @csadilek's comment in #13398 this is indeed a bug and not a feature. If such bookmarks are synced to desktop firefox or any other device, they would not work

**Comment by csadilek** [comment]
@s-ankur @opusforlife2 yes, the way I see it, we'd want to show the original URL, but keep the page in reader mode if the user decide to add it to the collection while in reader mode. So, we should add the reader page (moz-extension link), but show the nicer / original URL.

**Comment by s-ankur** [comment]
@csadilek what about bookmarks, as the moz-extension link is saved there as well

**Comment by csadilek** [comment]
@s-ankur what's the behaviour you would expect / want in these case? The original page or the reader page?

**Comment by s-ankur** [comment]
Seeing as bookmarks can be synced, the moz extension link would make it unusable on another device (and probably an unwelcome surprise). But as @opusforlife2 said it might be useful in some cases. So I'm not sure

**Comment by opusforlife2** [comment]
Absolutely. There should definitely be a portable way to save the Reader Mode link or share it with someone, or send it to another device entirely.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on:
► **`Nightly 210218`**
► **`Beta 86.0.0-beta.5`**
► **`86.1.0 RC1`**

using the following devices:
• Google Pixel 3a (Android 11)
• Nexus 9 (Android 9) (Android 9) [EMULATOR]
• OnePlus A3 (Android 6.0.1)
