### ISSUE TITLE
[FEATURE REQUEST] Please implement 'Add to Firefox' in Fenix

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#13032]
Whenever we share a link to fenix, it opens immediately. Please add "Add to Firefox" in Fenix just like Fennec that allows users to add a link as bookmark directly even without opening the link in Fenix.

Please add "Tab queue" along with it before stable release!!

See SS : https://photos.app.goo.gl/SBpLehMiYeTonWQ9A

**Comment by JoGarWeb** [comment]
I agree, I miss send link to my laptop in other apps without open browser.

**Comment by kbrosnan** [comment]
Please keep issues to 1 item per issue. 

Tab queue is #470

Share tab is #1523
