### ISSUE TITLE
[Bug] Download size for smaller items is shown as 0.00MB

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13031]
## Steps to reproduce
Download a small item

### Expected behavior
It shows the size properly whether in MB or KB or B

### Actual behavior
It shows as 0.00 MB

### Device information
In this case it was 1.5 KB actually
![Screenshot](https://user-images.githubusercontent.com/33252312/88701667-f30f0900-d127-11ea-9875-35c100c1fda2.png)UNITO-UNDERSCORE!20200728-231020!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by mcarare** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/8500

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/7  with Nokia 6 (Android 7.1.1).
