### ISSUE TITLE
FNX-14216 ⁃ tab reorganization

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#13045]
### What is the user problem or growth opportunity you want to see solved?
There is no way to organize tab
The tab selected mode seems like the best candidate to fullfil this role
When in this mode on the left side of every tab there should be a zone/icon/both than when press enable the user to move the tab where he want

### How do you know that this problem exists today? Why is this important?
Having a way to organize tab is necessary to easily find them the next time a open firefox

### Who will benefit from it?
Everyone person with more than there screen worth of tab

**Comment by kbrosnan** [comment]
Duplicate #2487
