### ISSUE TITLE
FNX2-15634 ⁃ [Bug] tab selected state new tab reappear after moving

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#13042]
## Steps to reproduce
Hold a tab in tab tray to go in the tab selected mode
Move up or down in the tab tray

### Expected behavior
The new tab floating button is hidden

### Actual behavior
The new tab floating button reappear

* Android device: 9
* Fenix version: nightly 28/07/2020

**Comment by Diana-Rus** [comment]
Hi, issue is fixed with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8) on latest Nightly 8/5.

Google Pixel 3XL (Android 9) - GIF
![20200805-124035](https://user-images.githubusercontent.com/49859863/89399079-a2487300-d71a-11ea-88a8-39f9c69a8c75.gif)

**Comment by Diana-Rus** [comment]
Closing this issue, it is verified, as per [comment](https://github.com/mozilla-mobile/fenix/issues/13042#issuecomment-669100712).
