### ISSUE TITLE
When in the tabs tray multi select mode require an explicit user action to exit multi select

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#13043]
### What is the user problem or growth opportunity you want to see solved?
When in tab selected mode, the tab tray can be close like always, this can be frustrating when wanting to select multiple tab.
When in this mode, the tab tray should not be able to be close or resize at all and the user need to click on the close or save button to exit the mode and then close the tray liie always

### How do you know that this problem exists today? Why is this important?
Because the tray is easy to close

### Who will benefit from it?
Everyone

**Comment by yoasif** [comment]
https://github.com/mozilla-mobile/fenix/issues/14911 seems relevant to me.
