### ISSUE TITLE
FNX-4943 ⁃ [Bug] Too little space for search suggestions/search shortcuts in landscape

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1304]
## Steps to reproduce
1. Turn the device in landscape mode.
1. Type in the search bar.
    1. Expected behavior
At least one search suggestion should be visible and the user can scroll from there.
    1. Actual behavior
On phones, the search suggestions are barely (or not at all) visible.
Comparing screenshots from a Galaxy Note 8 (large screen):
Fenix:
![Screenshot](https://user-images.githubusercontent.com/4037709/55334625-46c10200-54a2-11e9-9268-a0ac17548460.jpg)UNITO-UNDERSCORE!20190401-171239!UNITO-UNDERSCORE!Fenix!

Chrome:
![Screenshot](https://user-images.githubusercontent.com/4037709/55334638-4c1e4c80-54a2-11e9-9123-547318e99c80.jpg)UNITO-UNDERSCORE!20190401-171258!UNITO-UNDERSCORE!Chrome!

### Device information
* Android device: Android phones
* Fenix version: 4/1 build.

**Comment by sv-ohorvath** [comment]
On a smaller device like Nexus 5, there are no visible search suggestions in landscape mode.

**Comment by lime124** [comment]
collecting a bunch of landscape issues to a single thing for us to take a look at and fix. thanks!
