### ISSUE TITLE
FNX-14210 ⁃ [Bug] Opening Google Forms Link in Firefox Nightly opens Google Play Services page in the Play Store

### ISSUE THREAD

**Issue by adch99** [mozilla-mobile/fenix#13040]
### Steps to Reproduce
Open any Google Form link in Firefox Nightly.

### Actual Results
It opens the Google Play Services page on the Play Store.

### Expected Results
This is how it works in Firefox (stable). When I open the link with it, it tries loading it and then gives me the option to choose my browser once again. If I select Firefox (stable), then it opens the page for logging into my Google Account.

### Device information
* Android device: Android 8.1.0 on Moto G5S+
* Fenix version: This is Nightly 200723 06:01 (Build #22050610)
* AC: 52.0.20200722023149, 5c2458cb8
* GV: 80.0a1-20200721094241
* AS: 61.0.10

Edit: google forms link : https://forms.gle/oRWh3ptzRRRc4BY48

**Comment by vishalnandagopal** [comment]
This is not only with Google Forms.

It is a 'Firebase Dynamic URL' thing. Even with docs, specific app URLs too.

For testing , 
1. Any forms.gle URL (google forms)
2. https://shrts.in/Y9KX

**Comment by yoasif** [comment]
Does not happen in Reference Browser; noted on [reddit ](https://www.reddit.com/r/firefox/comments/i5yow5/cant_open_formsgle_links_when_firefox_is_set_as/)and reproducible on nightly.

**Comment by SeburoSUMO** [comment]
I have seen this happen in both Focus GV and in RB.

**Comment by AdityaGupta150** [comment]
There was no such problem earlier, __seems it came in newer versions__. 😄 
Verified on Nightly 200811 06:01

**Comment by AdityaGupta150** [comment]
And in the meantime can anyone suggest how to access such links? 😄❔ 
I had to use firefox on laptop for the same.

**Comment by Smollejan** [comment]
> 
> 
> There was no such problem earlier, **seems it came in newer versions**.
> Verified on Nightly 200814 06:01, Android 10

I can confirm that everyting was working fine a few versions ago. Now I have the same sort of problem: https://github.com/mozilla-mobile/fenix/issues/13504

**Comment by codrut-topliceanu** [comment]
Hey, are we sure this isn't intended behaviour? In the settings screen, under "Advanced" header there is the option to "Open links in apps" (OFF by default) which, when enabled, will open the link specified by @vishalnandagopal in Google Play app. Think this covers https://github.com/mozilla-mobile/fenix/issues/13504 as well.
<img src="https://user-images.githubusercontent.com/60002907/90727931-bd93b080-e2cc-11ea-81fd-1d1587814801.png" width="300px"/>

**Comment by adch99** [comment]
@codrut-topliceanu, I am not a developer here and don't know if this was indeed the plan. But it seems to me that if we'd want an average person to be able to use this browser straight off the Play Store then you wouldn't want it to fail on opening a simple Google Forms link. Moreover, the app used here to open the form is still a browser afaik (though I don't know much about the details of it). So it seems reasonable from an end-user perspective to expect to open something as commonplace as a Google Forms link with Firefox at its default settings.

**Comment by apbitner** [comment]
@codrut-topliceanu I'm not sure what recent change may have lead to this, but I'm not understanding why a Google Forms link would open the Google Play Store? There doesn't seem to be any native Google Forms app so I would think a Google Forms link would always open in the browser. Is this an issue with the way certain URL's are being handled? I'm not sure how all of that logic works behind the scenes.

**Comment by bifleming** [comment]
Removing Flag -- please resolve with discussion between UX/Eng -- either an email or on slack.

**Comment by codrut-topliceanu** [comment]
Freshly installed Nightly (with _Open links in apps_ OFF) opens [the link I added to the top comment](https://forms.gle/oRWh3ptzRRRc4BY48) without any issue (though a bit slowly):
<img src="https://user-images.githubusercontent.com/60002907/94239374-5ea00780-ff1a-11ea-9096-759310eb907f.png" width="300" />

Turning _Open links in apps_ ON and clicking on the link again makes Fenix open the _Use different app_ prompt:
<img src="https://user-images.githubusercontent.com/60002907/94240350-dae71a80-ff1b-11ea-822b-7030fead1550.png" width="300" />
This 2nd behaviour is similar to how it behaves on Chrome.
My previous comment was based on behaviour seen when using the link provided by the @vishalnandagopal ( https://shrts.in/Y9KX )

### Device Information:
Android device: Pixel 3XL (Android 10)
<img src="https://user-images.githubusercontent.com/60002907/94241092-dc651280-ff1c-11ea-83f4-71631a5c5b74.png" width="300" />

**Comment by sflorean** [comment]
Tested on Nightly, Beta, and Release versions, and here are the testing results:
- **Open links in apps OFF**
-- for https://shrts.in/Y9KX - the link is opened in the browser
-- for https://forms.gle/oRWh3ptzRRRc4BY48 - the link is opened in the browser
- **Open links in apps ON** 
-- for https://shrts.in/Y9KX- Google Play opens
-- for https://forms.gle/oRWh3ptzRRRc4BY48 - the link is opened in the browser
