### ISSUE TITLE
[Bug] Scrolling on Amazon wish list keeps jumping back up

### ISSUE THREAD

**Issue by theRealPadster** [mozilla-mobile/fenix#13051]
## Steps to reproduce
1. Sign into amazon.ca (or dot com as well, I'd assume). 
1. Open your wish list (https://amazon.ca/gp/aw/ls/)
1. Try and scroll down the page. 

### Expected behaviour
It should scroll smoothly, like any other website

### Actual behaviour
It scrolls down a little bit, but then jumps back up to where you started. I was able to get it to scroll normally once or twice, but the behaviour seemed pretty erratic. Long pressing before scrolling, or scrolling slowly might have helped, not sure. 

### Device information
* Android device: Google Pixel 2 (Android 10)
* Fenix version: 200728 06:22 (Also does it on 79.0.0)

![20200728](https://user-images.githubusercontent.com/1565883/88750727-22bc1200-d124-11ea-9649-84a95fe9538d.gif)UNITO-UNDERSCORE!224425!

**Comment by ekager** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1656990
