### ISSUE TITLE
FNX2-15640 ⁃ [Bug] Elements contained in the area of the bottom bar can't be tapped sometimes

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#13055]
## Steps to reproduce
Go to a site like news.ycombinator.com and try to edit a comment by selecting the text input box.

Now the bottom bar covers the bottom of the screen, after selecting the input box, obscuring the "update" button. Trying to scroll down does not hide the bar, but that's because you're scrolling on the input box instead because it takes up most of the screen space. You have to scroll down on the margins in order to hide the bar again, but this is hard because they're so small on the mobile layout.

Also, sometimes when you scroll to the bottom of the page, you still can't tap the update button for some reason. The only way you can do this is by first selecting the input box, closing the keyboard, and scrolling down again to make the input box selectable. It might be because the box is contained within the area of the bar and it still thinks it is asfrive for some reason.

### Expected behavior
You should be able to tap "update" if it's visible on the page.

### Actual behavior
Sometimes the button can be tapped, sometimes it can't, and sometimes it's obscured by the bar which can't be removed because you end up scrolling on the input box instead.

### Device information
Nightly 200725 06:01 (Build #22070613)
AC: 52.0.20200724130127, 71b462d5b
GV: 80.0a1-20200723095657
AS: 61.0.10

**Comment by kbrosnan** [comment]
Duplicate #10479 and bz-1652190

**Comment by kbrosnan** [comment]
I've reopened bz-1649865 which was duped to 1652190 because this does not seem to be working.
