### ISSUE TITLE
Swipe up from address URL bar to pull up tabs.

### ISSUE THREAD

**Issue by vurtomatic** [mozilla-mobile/fenix#13054]
### What is the user problem or growth opportunity you want to see solved?
UI / gesture feature to access tabs.

### How do you know that this problem exists today? Why is this important?
Accessing tabs requires tapping the "tabs" icon to the right of the address bar.

### Who will benefit from it?
Everyone?

**Comment by kbrosnan** [comment]
Duplicate #11862
