### ISSUE TITLE
When the New Tab Page has the keyboard open, the keyboard should be easy to dismiss

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#13053]
## Current
To see “the rest of the New Tab Page” and dismiss the keyboard, people may only use the system back button/gesture.

## Proposal
People may either use the system back button/gesture, or simply swipe up/down the area that’s not covered by the keyboard.

We’ve “pre-committed” people to the Search/URL path by auto-selecting the address bar on NTP, so let’s not make them “commit to search 100%” until they’ve typed a character into the address bar. Give them an easy way to exit out and see “the rest of the NTP”.

People can dismiss the keyboard by simply swiping up or down the NTP area. When the keyboard is dismissed, the address bar returns to its initial/unselected position and the rest of the NTP shows up in full.

This should work **as long as nothing has been typed into the address bar**.

| Before swiping up/down  | After swiping up/down |
|----|----|
|![](https://user-images.githubusercontent.com/51007/88756885-e1c20d00-d1b8-11ea-80e6-f104975bf827.png) |![](https://user-images.githubusercontent.com/51007/88756899-ebe40b80-d1b8-11ea-8ac3-6d54956aae0b.png) |

- - -
When a keyword has been entered into the address bar, we assume that people have “committed to search 100%”, so swiping up or down won’t exit out of the address bar. It will just allow them to see more suggestions.

The current search results ordering is not changed: we are keeping top-to-bottom.

| After entering keyword | After swiping up/down |
|----|----|
|![](https://user-images.githubusercontent.com/51007/88757526-63ff0100-d1ba-11ea-9761-3c45183029b7.png) |![](https://user-images.githubusercontent.com/51007/88757540-6c573c00-d1ba-11ea-8714-fcce5780b4fb.png) |

And just as our behaviour today, tap/gesture back once is still the equivalent of exiting out of the search screen. The keyboard dismisses, the address bar returns to its initial/unselected position and the rest of the NTP shows up in full.

|----|
| Tap/gesture back once (after entering keyword) |

| ------------- | 

|----|
| ![](https://user-images.githubusercontent.com/51007/88757588-8abd3780-d1ba-11ea-8e88-4f24373791dd.png) |

**Comment by data-sync-user** [comment]
➤ Elise Richards commented:

🚩 Flag added

Blocked on impl in #13052

**Comment by vesta0** [comment]
@brampitoyo is this work completed? Can we close this issue?

**Comment by brampitoyo** [comment]
@vesta0 Yes. This work is now completed. Let’s close this issue.
