### ISSUE TITLE
FNX2-15642 ⁃ [Bug] Opening a file from a conversion service suggests incorrect apps to open with

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#13057]
## Steps to reproduce
Download an image from an image conversion site and try to open it from within the browser's download completion notification.

### Expected behavior
You can open the image in an app that accepts image intents.

### Actual behavior
Other irrelevant apps are provided instead, like "ZArchiver" for zip files or Book Reader, and trying to open it with these apps gives an error stating it can't be opened.

![ezgif-5-2968b5ddce12](https://user-images.githubusercontent.com/6700637/88762005-269c6400-d125-11ea-8d3f-364609404e2e.gif)

### Device information
Nightly 200725 06:01 (Build #22070613)
AC: 52.0.20200724130127, 71b462d5b
GV: 80.0a1-20200723095657
AS: 61.0.10

**Comment by liuche** [comment]
The app suggestions for opening the file come from Android's system. Firefox only handles downloading the file to your device, but you would see the same suggestions if you were to open this from the Downloads part of your device.
