### ISSUE TITLE
[Bug] You can add a website to homescreen with a whitespace name

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13069]
## Steps to reproduce
On any page click add to homescreen using three dot menu
Remove the default name and just add a single space to the feild

### Expected behavior
Add button is disabled; it does not allow to save an empty name

### Actual behavior
Allows to create the shortcut (name shows up as web site)

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by liuche** [comment]
Validate the string so it's not whitespace only.

**Comment by Bawya1098** [comment]
Hello, @data-sync-user @NotWoods  I would like to try and work on this.

**Comment by s-ankur** [comment]
Should I close this, seems to be working as intended.

**Comment by NotWoods** [comment]
Please leave the issue open as we prefer to have QA double check everything is working :)

**Comment by s-ankur** [comment]
@NotWoods perhaps you can add qa-needed label 😅

**Comment by NotWoods** [comment]
@liuche see above ^

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
