### ISSUE TITLE
[Bug] Long history list created with the same URL on Google's homepage hamburger menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13062]
## Steps to reproduce
1. Open the Google top site link from the homescreen.
1. Tap the hamburger menu on the left.
1. Go to the History menu.
1. Delete history, return to tab and then go to History again.
    1. Expected behavior
A single history entry.
    1. Actual behavior
On Chrome the hamburger menu opens a menu list. On Firefox (both Fenix and Fennec), it opens an About page. 
From there, a long list of duplicated about:google URLs is created in the history menu.
Just going back to the tab (not refreshing the page) after deleting the entire history will re-create the multiple history entries.
    1. Device information

* Android device: Pixel 4 (Android 10)
* Fenix version: Nightly 7/28

**Comment by abodea** [comment]
This issue still reproduces on the latest Nightly 2/25 and RC 80.1.3 build with Google Pixel 4 XL (Android 11).
Note that there is not really a list created but instead of one entry, there are 2 entries created on the History.

**Comment by mariansima** [comment]
Could not reproduce this issue on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29
