### ISSUE TITLE
White Flashes in dark mode while opening websites

### ISSUE THREAD

**Issue by jenabaivab** [mozilla-mobile/fenix#13060]
## Steps to reproduce
1. Turn dark mode on and enable dark reader extension.
1. Open any webpage.

### Expected behavior
The website is opening in dark mode, and the background stays dark.

### Actual behavior
There are constant white flashes when loading webpages which make it very cumbersome for late night browsing. Constant flashbangs, irrespective of which website I am opening.

### Device information
* Android device: 10
* Fenix version: 79.1.0-beta.1

**Comment by B0pol** [comment]
Duplicate of #3603

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/6313
