### ISSUE TITLE
[Bug] Tab tray opens full-screen even with few tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13068]
This seems like a regression because a few releases ago this worked perfectly

## Steps to reproduce
Open 4 tabs and open tab tray

### Expected behavior
![Screenshot](https://user-images.githubusercontent.com/33252312/88814195-6c196980-d1d7-11ea-9bd1-0ec6990fb6e8.png)UNITO-UNDERSCORE!20200729-200734!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Actual behavior
Opens full-screen like this most tabs are far away from thumb reach
![Screenshot](https://user-images.githubusercontent.com/33252312/88814110-54da7c00-d1d7-11ea-9717-bdd79844c7b2.png)UNITO-UNDERSCORE!20200729-200839!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by Matth7878** [comment]
For one I think tab tray should always be fully expanded. It was annoying that it looked different just because you had a different number of open tabs.
