### ISSUE TITLE
FNX2-15650 ⁃ [Bug] Redundant save to collection button in tab tray

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13065]
In the latest nightly, the tabs tray has a save to collection button at the bottom. However, we already have 2 different ways to save to collection on the tab tray itself. So the new button is redundant. It is also distracting for people who just want to save to tab.

#### New Button:
![Screenshot](https://user-images.githubusercontent.com/33252312/88803094-982dee00-d1c9-11ea-95ab-0a6c2372474f.png)UNITO-UNDERSCORE!20200729-182959!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

#### Pre-existing ways: three dot menu option and long click
![Screenshot](https://user-images.githubusercontent.com/33252312/88803434-125e7280-d1ca-11ea-8044-46dd2f387f07.png)UNITO-UNDERSCORE!20200729-183128!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

![Screenshot](https://user-images.githubusercontent.com/33252312/88803261-d4f9e500-d1c9-11ea-85fe-c175b945b0fa.png)UNITO-UNDERSCORE!20200729-183156!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200729 06:01 (Build #22110610)
AC: 52.0.20200728130711, 5ef3b5c7a
GV: 80.0a1-20200727095125
AS: 61.0.10

**Comment by s-ankur** [comment]
This is in addition to the save to collection buttons in home screen and in tabs->three dot menu

**Comment by cadeyrn** [comment]
It was intentionally added, see #12856.
