### ISSUE TITLE
FNX2-15655 ⁃ [Bug] Back button does not work on some tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13071]
## Steps to reproduce
Examples:
Click help in home screen 
Any link from about section in 

### Expected behavior
Tab opens and back button works normally

### Actual behavior
Tab opens but back button does not work

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by sflorean** [comment]
No issues encountered while testing on Nightly 7/30 following the steps from the description. Closing as verified.
Devices:
- Samsung Galaxy Note 10 (Android 10).
- LG G7 FIT (Android 8), 
- Huawei MediaPad M2 (Android 5.1.1.
