### ISSUE TITLE
FNX2-15657 ⁃ [Bug] Fenix connects to incoming.telemetry.mozilla.org with all data collection toggles turned off

### ISSUE THREAD

**Issue by M83tUt3** [mozilla-mobile/fenix#13077]
I'm using Firefox 79.0.0 (Build #2015753875). After turning off all data collection in the settings panel, when I browse to about:networking, Firefox still seems to connect to incoming.telemetry.mozilla.org. When I turn off all the data collection toggles I would expect Firefox to actually be quiet, and not connect to Mozilla's telemetry servers at all.

**Comment by s-ankur** [comment]
I saw this with tcpdump using adaway

**Comment by mdboom** [comment]
I can't reproduce with the current Firefox for Android release on the main channel (79.0.5).  When telemetry is disabled, there is exactly one ping sent (the "deletion request" ping, which requests deletion of the user's data -- this is as designed).  Subsequent pings aren't sent (and if you look in the adb logs you can see "Glean disabled: Not submitting any pings").

Can you provide more information about the version of Firefox that you saw this on and steps to reproduce?

**Comment by s-ankur** [comment]
>  When telemetry is disabled, there is exactly one ping sent (the "deletion request" ping, which requests deletion of the user's data 
@mdboom I think this is what I saw.

**Comment by M83tUt3** [comment]
> there is exactly one ping sent (the "deletion request" ping, which requests deletion of the user's data -- this is as designed)

This is probably what I saw as well then. I have no desire to debug this more thoroughly, and if you cannot reproduce it I suppose the issue is invalid. Thanks, I'll go ahead and close this.
