### ISSUE TITLE
FNX2-15656 ⁃ [Bug] select indicator not showing in tab tray

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#13074]
## Steps to reproduce
Open multiple tabs and start selecting them to add to collection...select mark shows in all tab thumbnail except the current opened tab.

### Expected behavior
It should show a select mark in current tab thumbnail

### Actual behavior
Not showing the select mark

### Device information
* Android device: ? Android 8
* Fenix version: ? Latest nightly

![Screenshot](https://user-images.githubusercontent.com/58127841/88818580-7e49d680-d1dc-11ea-9719-62b8f20a2e1b.png)UNITO-UNDERSCORE!2020-07-29-20-42-59-21!

**Comment by s-ankur** [comment]
For some reason the first tab is treated differently from the rest. Observe the x button on the tabs
![Screenshot_20200729-205406_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/88819546-c1f11000-d1dd-11ea-8ce1-80472099b5d4.png)

**Comment by Diana-Rus** [comment]
Hi, issue is fixed on the latest Nightly 8/4 verified with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8)
- the active tab displays the selection mark
- now when in selection mode for collection the active tab has also the check mark(as when it's selected)
<details closed><summary>Screen</summary>

![Screenshot_20200805-104753](https://user-images.githubusercontent.com/49859863/89387947-f0a24580-d70b-11ea-8384-17eb9f3b8213.png)
</details>

**Comment by Diana-Rus** [comment]
Hi closing this issue as per previous [comment](https://github.com/mozilla-mobile/fenix/issues/13074#issuecomment-669049002).
