### ISSUE TITLE
FNX-4946 ⁃ Use Firefox Sharp Sans font

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1307]
Currently we're not using the custom font `Firefox Sharp Sans`. This should be implemented before MVP, and is likely a line item in our [design audit](https://github.com/mozilla-mobile/fenix/issues/724)

> Since this is a proprietary font, we cannot include it in our product through GitHub - Instead we will have to include the fonts via the Fenix Build Process on Task Cluster. This work is documented in #1365

**Comment by sblatz** [comment]
@shorlander mentioned there _may_ be potential legal ramifications by putting this in the app, so let's make sure we address those

**Comment by pocmo** [comment]
* In the past using custom fonts was a guaranteed way to leak memory - I wonder if that is better today (@colintheshots may know?)
* Our own guidelines recommend to use the system font :) https://design.firefox.com/photon/visuals/typography.html

**Comment by shorlander** [comment]
>     * Our own guidelines recommend to use the system font :) https://design.firefox.com/photon/visuals/typography.html

Those guidelines are mostly targeted at Desktop. But also we wrote those guidelines before Material had carved out a lot of space for more flexible theming (https://material.io/design/material-studies/about-our-material-studies.html) :)

**Comment by colintheshots** [comment]
Google added full, first-party support to add custom fonts in the support library with proper caching about a year ago. Before that point, using custom fonts required various hacks and wasn't well-supported on Android. Using a proper font cache avoided the memory leaks even before Google made their first-party changes.

**Comment by fitojb** [comment]
Sharp Sans isn’t even suited for UI copy, as e.g. Inter is (Inter is the other new brand font).

**Comment by shorlander** [comment]
We aren't doing this right now.

**Comment by mon-jai** [comment]
Is the font open source?

**Comment by fitojb** [comment]
> Is the font open source?

No
