### ISSUE TITLE
FNX2-15659 ⁃ [Bug] Save to collection button in home screen even with 0 tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13080]
## Steps to reproduce
Close all tabs

### Expected behavior
No save to collection button in home screen

### Actual behavior
There is a button

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200729-214722_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/88825384-1e0b6280-d1e5-11ea-888d-a1e9f1af7ad4.png)
![Screenshot_20200729-214715_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/88825389-206dbc80-d1e5-11ea-97bf-347263629e83.png)

**Comment by ekager** [comment]
cc @mcarare re #12125 it looks like we probably need to consume changes to the `BrowserState` for num normal tabs open only and update `HomeFragmentStore`/`SessionControlView` to hide `NoCollectionsMessageViewHolder` for cases when all/last tabs are removed while on the `HomeFragment`

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-100714](https://user-images.githubusercontent.com/51314259/91272344-48205800-e784-11ea-8a44-d2ad6a9868e0.gif)
