### ISSUE TITLE
FNX2-15661 ⁃ [Bug] Intermittent SavedLoginsStorageControllerTest. WHEN fetching the login list, THEN update the state in the store | java.lang.AssertionError: Verification failed: call 1 of 1: SyncableLoginsStorage(#2).list(any())) was not called

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#13084]
Test results: https://firefoxci.taskcluster-artifacts.net/WXyROmCoT6KtgW2aAk09cQ/0/public/reports/index.html

Log: https://treeherder.mozilla.org/logviewer.html#?job_id=311407751&repo=fenix

[task 2020-07-29T16:36:21.425Z] SUITE: org.mozilla.fenix.settings.logins.SavedLoginsStorageControllerTest
[task 2020-07-29T16:36:21.525Z]   TEST: WHEN fetching the login list, THEN update the state in the store
[task 2020-07-29T16:36:21.625Z]     [Robolectric] org.mozilla.fenix.settings.logins.SavedLoginsStorageControllerTest.WHEN fetching the login list, THEN update the state in the store: sdk=28; resources=LEGACY
[task 2020-07-29T16:36:21.625Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-07-29T16:36:34.625Z]     I/AssetManager: no overlays.list file found
[task 2020-07-29T16:36:36.025Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-07-29T16:36:37.825Z]     D [FenixApplication] Initializing Glean (uploadEnabled=false, isFennec=false)
[task 2020-07-29T16:36:38.325Z]     I/glean/Glean: Registering pings for mozilla.telemetry.glean.GleanMetrics.Pings
[task 2020-07-29T16:36:44.625Z]     I/AssetManager: no overlays.list file found
[task 2020-07-29T16:36:44.725Z]   FAILURE
[task 2020-07-29T16:36:44.826Z] 
[task 2020-07-29T16:36:44.826Z] java.lang.AssertionError: Verification failed: call 1 of 1: SyncableLoginsStorage(#2).list(any())) was not called
[task 2020-07-29T16:36:44.826Z] 	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
[task 2020-07-29T16:36:44.826Z] 	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
[task 2020-07-29T16:36:44.826Z] 	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
[task 2020-07-29T16:36:44.826Z] 	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
[task 2020-07-29T16:36:44.826Z] 	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
[task 2020-07-29T16:36:44.826Z] 	at io.mockk.MockKDsl.internalCoVerify(API.kt:143)
[task 2020-07-29T16:36:44.826Z] 	at io.mockk.MockKKt.coVerify(MockK.kt:169)
[task 2020-07-29T16:36:44.826Z] 	at io.mockk.MockKKt.coVerify$default(MockK.kt:166)
[task 2020-07-29T16:36:44.826Z] 	at org.mozilla.fenix.settings.logins.SavedLoginsStorageControllerTest.WHEN fetching the login list, THEN update the state in the store(SavedLoginsStorageControllerTest.kt:91)
[task 2020-07-29T16:36:44.826Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-07-29T16:36:44.826Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-07-29T16:36:44.826Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-07-29T16:36:44.826Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-07-29T16:36:44.826Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-07-29T16:36:44.826Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-07-29T16:36:44.826Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-07-29T16:36:44.826Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-07-29T16:36:44.826Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-07-29T16:36:44.826Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2020-07-29T16:36:44.826Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
[task 2020-07-29T16:36:44.826Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
[task 2020-07-29T16:36:44.826Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-07-29T16:36:44.826Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-07-29T16:36:44.826Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-07-29T16:36:44.826Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-07-29T16:36:44.826Z] 	at java.lang.Thread.run(Thread.java:748)

**Comment by ekager** [comment]
Did the two commits seem to fix the issue or are we still seeing intermittents on this one?

**Comment by Archaeopteryx** [comment]
[Latest failure on master](https://treeherder.mozilla.org/#/jobs?repo=fenix&group_state=expanded&resultStatus=pending%2Crunning%2Ctestfailed%2Cbusted%2Cexception%2Cretry%2Cusercancel%2Crunnable&revision=d5b105097ee529a69e6b58df437f43561ee1d10d&selectedTaskRun=I3s13wESQlC1xvQnB649UA.0) is from 2 days ago.

**Comment by ekager** [comment]
Okay going to close this for now - feel free to reopen if this shows up again 😬
