### ISSUE TITLE
[Bug] Language sub-menu opens differently, and takes time to open

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#13087]
## Steps to reproduce
Settings > Language.

### Expected behavior
It opens without any lag and with the same animation, just like the other menu options.

### Actual behavior
The Language menu option gets highlighted, the title bar shows Language instead of Settings, and a search icon appears at the top right, but the menu stays frozen there for a second, giving the impression that the app is stuck. About a whole second after that, the list of languages just replaces the menu screen, as opposed to fading in from the right like all the other sub-menus.

It seems like the sub-menu _is_ fading in from the right as well, but the animation is being hidden by the long loading time.

If the loading time for this sub-menu cannot be shortened, maybe a "Loading..." indicator would help?

### Device information
* Android device: Xiaomi Mi 5 (LineageOS 16), Nokia 8 (Stock Android 9)
* Fenix version: Nightly 200728 06:22 (Build #22100630)

**Comment by mcomella** [comment]
Triage: ecsmyth to research the reach/impact of this issue

**Comment by opusforlife2** [comment]
Also tried on a Nokia 8 today. Same problem.

**Comment by opusforlife2** [comment]
Update: on Nightly 201002 17:06 (Build #2015767371), the animation is smooth and there is no delay. Was something changed meanwhile?

**Comment by mcomella** [comment]
Triage: I similarly cannot reproduce. Please reopen if the issue comes back – thanks for reporting!
