### ISSUE TITLE
Scan QR code from image file

### ISSUE THREAD

**Issue by baopaau** [mozilla-mobile/fenix#13092]
### What is the user problem or growth opportunity you want to see solved?
Adding "Scan from picture file" feature to the built-in QR code scanner.
Which allows users pick a picture from media library and then scan it using Fenix.

### How do you know that this problem exists today? Why is this important?
QR code storing in phone internal storage is very common. However, the built-in scanner can only scan code from camera view, that makes the uses very restricted.

If user's time is limited and it is not urgent to get the link, many people prefer to take a shot of code then scan it later, rather then directly scan a code by real-time camera, for some reasons:

* Camera is normally the app that easiest to open from a smartphone, even from a locked smartphone.
* The time used to scan a QR code is uncertain, which is affected by many factors such as the scale of code.
* The scanning result may not be memorized in some scanner apps.
* The media showing a QR code may includes extra information.

Additionally, QR codes appears not only printed media, but also as digital format. Sometimes people just send other a picture that includes a QR code, just like sending a link. Some web articles even let people take a screenshot then scan it!

Obviously, scanning from picture file is a common (even basic) demand to a QR code scanner nowadays. If the place of built-in scanner feature settled, it's better to make it complete.

### Who will benefit from it?
Users who need to scan QR code from phone storage

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4176)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807387

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
