### ISSUE TITLE
[Bug] Disabling "Open links in apps" doesn't work for some sites/apps

### ISSUE THREAD

**Issue by baopaau** [mozilla-mobile/fenix#13090]
If the option "Open links in apps" (from Setting - Advanced) is disable, all "open in app" requests from websites should be held up until the user clicks "Open in app" manually. It is an important protection provided by the browser that prevents tracking across webpages and apps.

Currently, this firewall works correctly for sites/apps such as:

* Play Store
* YouTube
* Discord
* Twitter
* Taobao
* Douban
* Pixiv
* ...

But there are exceptions:

* Telegram
* Reddit
* Bilibili
* Zhihu
* JD.COM
* ...

Those sites are able to "bypass the firewall" in the current Fenix (but not Fennec), as below:

## Steps to reproduce
* Precondition: The specific app is installed
* Precondition: The option"Open links in apps" is disabled
* Open a link that may open an app (Normally the official website of the app)

For example, open "https://jd.com" after the JD.COM app is installed.

### Expected behavior
* Stay at the webpage. And the button "Open in app" will be available.
* The required app actually opens only after the user clicks "Open in app".

### Actual behavior
* Just switch to the app automatically.
* If the user returns to the browser, no "Open in app" button can be found.

### Device information
* Android device: Android 10
* Fenix version: 79.1.0-beta.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4174)

**Comment by opusforlife2** [comment]
Furthermore, "mailto:" links seemingly always try to open in app, no matter which website it is.

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by mariansima** [comment]
Could not reproduce this issue on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by opusforlife2** [comment]
Further activity has occurred.

**Comment by opusforlife2** [comment]
OI.

**Comment by opusforlife2** [comment]
OI (x2).

**Comment by opusforlife2** [comment]
Oi oi!
