### ISSUE TITLE
Quick search from tabs tray

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#13091]
## User Story
As a user, when I open a new tab, I want to be able to search right away without having to take any extra steps, so I can complete my quick search faster. 

Current state:: when the new tab page is opened from the tab tray, the address bar is not selected and moves to the top, and the keyboard does not come up.
User problem: Users want to start searching right away when opening a new tab.
Proposal: when the new tab page is opened from the tab tray, select the address bar automatically and pop up the keyboard so that users can begin a new search in just two taps.

### Acceptance Criteria
* When I open a new tab from tab tray (by tapping on +) the address and keyboard pops up half way up the screen (similar to tabs tray)
* I see the same screen when opening a new tab vs. starting a new search.

![image](https://user-images.githubusercontent.com/42752644/88851447-c6f09800-d1ba-11ea-812d-24f4bf9797d9.png)

**Comment by s-ankur** [comment]
Related #13052

**Comment by brampitoyo** [comment]
Closing in favour of #13052.
