### ISSUE TITLE
FNX-4948 ⁃ Investigate how site permissions should work on private mode

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1309]

**Comment by Amejia481** [comment]
@pocmo I noticed that in [Fennec we are remembering site permissions in private mode](https://drive.google.com/file/d/1S2xiXw96Jf7uooY57Aj9py_J0JdNTH2v/view?usp=sharing), I don't know if this is the right behavior that we want on Fenix? I tested on other browsers and this is not happening.

cc: @st3fan @vesta0

**Comment by vesta0** [comment]
@bbinto @mheubusch I recommend Fennec parity. What do you think?

**Comment by vesta0** [comment]
@bbinto @mheubusch we need to make a product decision on how we want to treat site permissions in private mode. In Fennec, we are remembering site permissions in private mode but as per @ehsan that is not the correct behaviour. We should either remember site permissions for the duration of a PB session and then forget it (in case user opens the same page in a different tab in the same session) or not save the permissions at all. I vote for the latter for MVP.

**Comment by Amejia481** [comment]
Fennec issue https://bugzilla.mozilla.org/show_bug.cgi?id=1541423

**Comment by bbinto** [comment]
@vesta0 thumbs up to your suggestion and @ehsan's feedback.

**Comment by Amejia481** [comment]
👍
