### ISSUE TITLE
Dismissing the keyboard on the new tab page

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#13094]
### User Story
As a user on the New Tab Page , I can swipe up/down on the area not covered by the keyboard, to dismiss the keyboard, so I can see the rest of the items on the homescreen. 

Current: To see “the rest of the NTP” and dismiss the keyboard, users may only use the system back button/gesture.
Proposal: users may either use the system back button/gesture, or simply swipe up/down the area that’s not covered by the keyboard.

We want to make it easier for users to do a quick search after opening a new tab, but we don't want to commit them to doing a search. So this is the proposed state as long as nothing has been typed into the address bar.

Dependency:
Quick search from tabs tray #13091

### Acceptance Criteria
* When I am on the New Tab Page, I can dismiss the keyboard by swiping up/down on the area not covered by the keyboard
* This is only the case when nothing has been types into the address bar. 

![image](https://user-images.githubusercontent.com/42752644/88855230-8a279f80-d1c0-11ea-9539-8f04c58351c7.png)

**Comment by jorsn** [comment]
With the new fenix (79.0.5) I cannot dismiss the keyboard with the system back button—this also removes my typing. Instead, as soon as I scroll through the list of options the keyboard is dismissed automatically. When I tap the bar to continue typing, it reopens.

This is quite pleasant, except I would prefer that the system back button only dismissed the keyboard on the first press, and removed my typing in a second press. I think, this is the old behavior from fennec, and this prevents accidentally wiping my typing.

**Comment by vesta0** [comment]
Looks like this was addressed in #13053
