### ISSUE TITLE
FNX-4949 ⁃ Create  UI containing the browser and toolbar

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#131]
Parent: #116

**Comment by sblatz** [comment]
<img width="360" alt="screen shot 2019-01-11 at 1 12 49 pm" src="https://user-images.githubusercontent.com/4400286/51051747-ae059f00-15a2-11e9-8dd0-4522c74c219d.png">

**Comment by andreicristianpetcu** [comment]
Please use the URL. Showing the title is super friendly to phishing.
