### ISSUE TITLE
[Bug] Unable to go to zeroconf/bonjour/.local hosts

### ISSUE THREAD

**Issue by emceeaich** [mozilla-mobile/fenix#13103]
## Steps to reproduce
Start a web service on a device that has a hostname provided by zeroconf (i.e. hostname.local)

```
cat "hello world" > index.html
python3 -m http.server 8000
```

Connect device running Fenix to same wifi network as the service is running on.

Try going to the server in Fenix nightly.

### Expected behavior
Page loads

### Actual behavior
Get browser-provided 'address not found error'

Also happens with web services running on port 80

Going to non-`.local` hosts works

### Device information
* Android device: Moto Z3 Play (XT1929-4)
* Fenix version: Nightly 200729 06:01 (Build #22110610)

**Comment by kbrosnan** [comment]
Emma would you try visiting the local site in [Geckoview Example](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/GAc0P4KnQ3ev_TYfc_xW4g/runs/0/artifacts/public/build/geckoview_example.apk) this 64-bit ARM apk should be the right one. This will tell us if it is a GV or Fenix/Android components issue.

**Comment by emceeaich** [comment]
Trying with the Geckoview Example apk, I get `ERROR_CATEGORY_URI:ERROR_UNKNOWN_HOST` when trying to go to a host on my network with name of the form `hostname.local`.

**Comment by kbrosnan** [comment]
Lets have the GV team have a look, bz-1656153
