### ISSUE TITLE
Remove bottom sheet for tabs

### ISSUE THREAD

**Issue by Nico04** [mozilla-mobile/fenix#13109]
I've been using Firefox Preview for month : it was the best browser I could have.
I really don't like the new UI for tabs that use a bottom sheet.
To be sure, I've been using both Firefox Preview (v5.1.1) and Firefox beta (lastest) for few weeks now. Each time I go back to Firefox Preview's UI it feels more natural, pleasant and productive. 

Could you at least add a option to let the user choose please ?
For now I'll keep using the Preview (v5.1.1) but it's not a good idea to keep using an old version.

**Firefox Beta UI**
![Screenshot_20200730-084008](https://user-images.githubusercontent.com/34476051/88893789-2a280c00-d247-11ea-8484-ffddc5a64662.png)

**Firefox Preview UI (v5.1.1)**
![Screenshot_20200730-084027](https://user-images.githubusercontent.com/34476051/88893785-298f7580-d247-11ea-93e6-80a68ecb02b6.png)

**Comment by kbrosnan** [comment]
Duplicate #11833

**Comment by Nico04** [comment]
It doesn't seems to be the exact same issue : what I suggest is simplier : just go back on the previous UI which was perfect.

**Comment by Dunexus** [comment]
@Nico04 
Could you tell what makes the new tab tray inconvenient for you ?
It looks like there is no plan to bring back the old UI, however there is still some work in progress to make the new tab tray better, maybe your feedback could help.

**Comment by Nico04** [comment]
I'll compare both an explain the mains resons, by order of priority.
_(FP : Firefox Preview, FB : Firefox Beta)_

1. Cold start :
FP : Tabs visible
FB : Tabs not visible

2. Tap on the number of tabs :
FP : list of tabs + url bar directly (that add new tab on validation)
FB : list of tabs, need to tap + to add a tab

3. Tabs list's tiles :
FP : smaller (see more), nicer and more original look. 

4. Tabs list (> 10 tabs)
FP : header hide on scroll (showing more tabs at once). If non-top tab is selected when arriving on list, you can see a small portion of the previous tab, indicating there's more above. 
FB : Because it's a bottom sheet, there is 2 level of scrolling (tab list and bottom sheet itself), which is quite useless and confusing.

**Comment by Dunexus** [comment]
Thank you for this detailed feedback.

1. I don't think this issue has been reported here, maybe you can open one.

2. What is the difference in terms of workflow that makes you prefer one over the other ?

3. The increase in size was mainly to fit a preview of the page asked by users. For the "more original look", I agree, I liked the unique design of old tabs but it wouldn't fit well inside a bottom sheet.

4. This is how bottom sheets works in Android, I think users a used to this two levels of scrolling. A good point is about the "If non-top tab is selected when arriving on list, you can see a small portion of the previous tab, indicating there's more above.". Again, I don't think this issue has been reported here, feel free to open an ticket about this.

Please open one ticket per issue, it is easier for Fenix team to understand the request and triage.

**Comment by Nico04** [comment]
1. Well it's not a bug, it's "just" a different behavior, and it's why I've opened this issue.
2. It's way easier to add a new tab. You have a thought while on a tab, in just 1 tap you can tap on the address bar and add a new tab on validate, very pleasant.
3. I understand, but I see no interest of viewing the page behind, personnaly. At the contrary, it reduce the visibility of the tab list.
4. I will open a new issue for the top-tab issue then
