### ISSUE TITLE
[BUG] Dark Reader doesn't work on Mozilla support page

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#13107]
Install Dark Reader add on Fenix and go to https://support.mozilla.org

See dark reader doesn't work on that page while working fine on other webpages

**Comment by cadeyrn** [comment]
WebExtensions don't work on some Mozilla domains. That's intended.

**Comment by kbrosnan** [comment]
Expected behavior. As Cadern says web extensions are not allowed to run on the Mozilla Support site. See bz-1445650
