### ISSUE TITLE
[Bug] Search engine settings are reset upon update

### ISSUE THREAD

**Issue by target-san** [mozilla-mobile/fenix#13113]
## Steps to reproduce

1. Have custom search configuration. I had DDG+Wikipedia EN+Wikipedia RU, for reference
1. Get latest "update" to 79.0.0

### Expected behavior

Search engines are the same as before update

### Actual behavior

You get Google(?)+Yandex(??)+Twitter(???????????)

### Device information

* Android device: Moto G5 Plus
* Fenix version: 79.0.0

**Comment by cadeyrn** [comment]
Update from which version? 68? Then it  seems expected bedause it's documented in the upgrade FAQ:

> Custom search engines will need to be set up manually

https://support.mozilla.org/en-US/kb/firefox-android-upgrade-faqs

**Comment by target-san** [comment]
Could you please clarify then why software update with such implications was silently pushed upstream? Such update should've been a separate application. How do I downgrade to pre-Fenix on Android? Judging from Reddit and this bugtracker, you broke UX and functionality for lots of users in many areas. IMO it's the best way to lose remains of your user base.

UPD: Checked FAQ. No downgrade? Good job...
