### ISSUE TITLE
[Bug] Tab not restored when you cancel swipe to delete the last tab from a collection 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13118]
## Steps to reproduce
1. Create a collection with only one tab.
2. Swipe to remove the tab.
3. On the confirmation dialog, press Cancel.
### Expected behavior
The tab is back and nothing changed.
### Actual behavior
The tab is gone and the swipe "effect" remains displayed.
![collection](https://user-images.githubusercontent.com/4037709/88921078-8eae8f80-d276-11ea-8a2d-3b64ac1db3c0.png)

### Device information

* Android device: Pixel 4 (Android 10)
* Fenix version: Nightly 7/30, Beta 80.0

**Comment by ekager** [comment]
Should be addressed for https://github.com/mozilla-mobile/fenix/pull/12538

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/4 on the following devices:
- Huawei MediaPad M2	(Android 5.1.1)
- Google Pixel 3 (Android 11)
- Samsung Galaxy Note 10 (Android 10)
