### ISSUE TITLE
[Bug] Attempting to scroll within a textarea sometimes slides from one tab to the next

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#13112]
## Steps to reproduce

Go to bugzilla, zoom in, put focus in the textarea, and then try to scroll to make more of the textarea visible. You might need some text in the textarea already. [Video showing problem](https://mozilla.staktrace.com/bug/fenix-13112.mp4?asdfasdf)

### Expected behavior

Page scrolls to make other parts of textarea visible

### Actual behavior

Entire content area slides, showing you the next tab.

### Device information

* Android device: Sony Xperia XZ1C
* Fenix version: Nightly 200729 06:01 (Build #22110610)

**Comment by cadeyrn** [comment]
sounds like #12865.

**Comment by staktrace** [comment]
Indeed, thanks! I'll comment over there.
