### ISSUE TITLE
[Bug] ETP off and shield not visible on webcompat.com

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13115]
## Steps to reproduce
1. Go to a webpage.
2. Open the main menu>Addons>Report site issue
3. Observe the ETP icon.
### Expected behavior
ETP is on (by default) and the icon is visible.
### Actual behavior
The icon isn't visible but if you tap the spot the ETP info panel opens and ETP is off for this website.
### Device information

* Android device: Pixel 4 (android 10)
* Fenix version: Beta 80.0, Nightly 7/30

**Comment by s-ankur** [comment]
Duplicate of #12848

**Comment by liuche** [comment]
Since someone's assigned to the other bug let's close this one.
