### ISSUE TITLE
FNX-4950 ⁃ Download does not work on a custom tab (Slack)

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1311]
## Steps to reproduce
-Open a custom tap from slack
-Tap on a link on the page to download a file

### Expected behavior
-Download confirmation prompt pops up and you can tap on DOWNLOAD

### Actual behavior
-Nothing happens

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1914

**Comment by jonalmeida** [comment]
Fenix needs to pass in the session ID to the features so that they become session aware.

**Comment by vesta0** [comment]
@colintheshots  please see the comment above and confirm if this is all Fenix work.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/8 build. 
devices: Pixel(Android 9), P9 lite (Android 6)
