### ISSUE TITLE
[Bug] Creating a collection from tabs tray doesn't display the first letter with a capital letter

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#13110]
## Steps to reproduce
1. Open a few tabs.
2. Tap on the tabs counter.
3. From the tabs tray, tap on the "Save to collection".
4. Select at least one tab, tap "Save", then "+ Add new collection".
5. Name your collection observing the first letter.

### Expected behavior
The first letter of the name is with a capital letter by default.

### Actual behavior
The first letter is not with a capital letter.
Reproducible in private mode also.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 9)
* Fenix version: 7/30 Nightly, Beta 80.0.0-beta.1
* Creating a collection via three-dot menu, displays the first letter a capital one.

![collections](https://user-images.githubusercontent.com/40694158/88897175-8e50cd00-d253-11ea-96ab-aa62bb1e0b8c.gif)

**Comment by Kwasow** [comment]
I'll have a look at this if I may

**Comment by Kwasow** [comment]
Fixed in 1e7f078907cf4f0b77943890a2b6093e233da14a
Can be closed now

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build 200810 from 8/10** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200810-105230](https://user-images.githubusercontent.com/51314259/89761831-f2974a80-daf7-11ea-8e4f-a27677d61ac3.gif)
