### ISSUE TITLE
Fenix upgrade should not be silent. There should be a way to roll back Fenix upgrade.

### ISSUE THREAD

**Issue by target-san** [mozilla-mobile/fenix#13121]
### What is the user problem or growth opportunity you want to see solved?

Fenix introduces lots of issues, both functional and UX, and lacks lots of features from previous version. Thus, such upgrade should **not** be a simple silent upgrade. User must be notified about huge changes and feature cripple and make conscious decision.

### How do you know that this problem exists today? Why is this important?

Because upgrade to 79.0 just rolled onto my device

### Who will benefit from it?

All the users who don't want to be alpha-testers

**Comment by kbrosnan** [comment]
There is no way to do this on Android. Google Play controls the updates. The build ID of Fenix release builds are larger than the final Fennec build. In most cases Android will not allow the user to downgrade to a lower build ID.

**Comment by target-san** [comment]
Could you please at least tell why you did this? Why not make separate app and promote it through Fennec until it's really stable? Firefox doesn't dominate market like Windows to force any bizzare decisions onto users. I've been using Firefox for Android for quite some time. And now such a "present"...
