### ISSUE TITLE
"Enable Synchronization" banner in settings cannot be removed

### ISSUE THREAD

**Issue by target-san** [mozilla-mobile/fenix#13120]
## Steps to reproduce

1. Get Firefox 79.0
1. Go to settings
1. See huge banner half the first settings page "Enable synchronization"

### Expected behavior

1. There's some way to remove that annoying banner

### Actual behavior

1. "Enable Synchronization" banner cannot be removed

### Device information

* Android device: Moto G5 Plus
* Fenix version: 79.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4218)

**Comment by cadeyrn** [comment]
You can't disable other setting categories so why should it be possible to disable the first one? Only because it looks different?

Anyway, it's definitely a feature request, not a bug.

**Comment by target-san** [comment]
It's a settings category? Ok, sounds reasonable. Though why it looks so different? Sorry but this really reminds me of web dark patterns. Make users enable sync by accident by making button happen under their fingers as much as possible.

**Comment by cadeyrn** [comment]
> Make users enable sync by accident

That's really not possible at all. 😉

I guess Mozilla uses the different look to promote the use of Firefox Sync. I don't think that a "call to action" element is a "dark pattern".

**Comment by target-san** [comment]
CtA's are usually one-time if not part of most-used usage path, no? And IMO there are better ways to make CtA's than half-screen banner.

**Comment by cadeyrn** [comment]
> CtA's are usually one-time

Working as a web developer in a marketing agency I have to answer this with a clear "No".

> IMO there are better ways to make CtA's than half-screen banner.

It's definitively not "half-screen"…

**Comment by ekager** [comment]
You still need to sign into FxA to Sync, clicking on the banner will just bring you to a login/signup screen.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807117

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
