### ISSUE TITLE
[Bug] firstparty.isolate potentially interfering with uBlock Origin?

### ISSUE THREAD

**Issue by RonitRay** [mozilla-mobile/fenix#13129]
## Steps to reproduce
1. Install uBlock Origin
1. Go to extension dashboard/settings
1. Tick "I am an advanced user"
1. Tick "Prevent WebRTC from leaking local IP addresses"
1. Tick "Block CSP Reports"
1. Tick "Disable JavaScript"
1. Go to about:config
1. Search for privacy.firstparty.isolate
1. Toggle its value to true.
1. Go to en.wikipedia.org
1. Open uBlock Origin.

### Expected behavior
uBlock detects that you are on Wikipedia, that JS is disabled and can be re-enabled.

### Actual behavior
This rarely works. Two other behaviours I have noticed are:
1. uBlock shows that the domain is www.wikipedia.org but that the extension is disabled for this site. If I tap on the button to enable it, it goes off again in a second. Every time it it clicked.
1. uBlock shows the page as blank:about-scheme, and then same as above (extension disabled, cannot be re-enabled).

Would like to reiterate that I am very much on Wikipedia, and open uBlock from the pop-up menu when on the homepage. This issue doesn't exist on Fennec.

My best guess is that it is an issue with FPI, since with FPI set to its default "false" value, I wasn't able to replicate this issue in the few times that I tried. Further, I think this might be an FPI issue since Fenix seems to load the uBlock configuration panel as a new tab on mobile? This is definitely conjecture and not founded in any concrete analysis. Sorry if I wasn't supposed to comment this way, it's my first issue.

### Device information

* Android device: Redmi Note 4 (mido). Android 7.0.
* Fenix version: Nightly 200730 06:21 (Build #22120631). Have also noticed with previous Nightly versions going up to a couple of months back or so.

**Comment by kbrosnan** [comment]
This pref is not a supported use. Please report this upstream to https://bugzilla.mozilla.org
