### ISSUE TITLE
Remove about:logo

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#13128]
We don't need this page anymore, let's remove it. Also remove any resources that might be referenced that are unnecessary.

**Comment by jonalmeida** [comment]
This comes from Gecko.

**Comment by kbrosnan** [comment]
This probably is not a good first issue given that this would be Gecko work.

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1662835

**Comment by amedyne** [comment]
Closing 1662835, tracking thru https://bugzilla.mozilla.org/show_bug.cgi?id=1610528
