### ISSUE TITLE
[Bug] Missing Fenix Notification for Myntra TWA in android taskbar

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#13123]
## Prerequisites
- Have firefox browser set as default.
## Steps to reproduce
1. Install TWA https://play.google.com/store/apps/details?id=com.myntra.android
2. Open the TWA
### Expected behavior
In android taskbar, a Fenix notification is displayed "Powered by Fenix"
### Actual behavior
For this TWA the notification is missing
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Firefox Beta 80.0.0-beta.1

<details closed><summary>Missing notification for Myntra TWA</summary>

![Screenshot_20200730-161224_Myntra](https://user-images.githubusercontent.com/49859863/88927188-b9511600-d27f-11ea-8e26-e3db3d033f36.jpg)
<details>

Note:
There is also no history saved for it in browser.
Is this TWA unsupported by Fenix?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4223)

**Comment by AndiAJ** [comment]
Hi, still reproducible on **`Firefox 88.0.0 Beta 1`** using a OnePlus A3 (Android 6.0.1)

**Comment by lobontiumira** [comment]
Reproducible on Beta 89.0.0-beta.1 with Samsung Galaxy Note 8 (Android 9).

**Comment by delia-pop** [comment]
This issue was reproduced again on 93.0.0-beta.1 (Build 2015832715) with Huawei P9 Lite (Android 8).
The "Powered by Firefox Beta" notification is missing from the Android taskbar for Myntra and       
QuintoAndar Imóveis TWAs. However, it is correctly displayed for Dead Trails TWA.
