### ISSUE TITLE
[Bug]Leanplum tracking_protection_setting attribute remains set to standard

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#13125]
## Steps to reproduce
1. Set the Enhanced tracking protection to either "Strict" or "Custom"
2.  Check the `tracking_protection_setting` attribute in Leanplum

### Expected behavior
The `tracking_protection_setting` attribute  should be populated with either "Strict" or "Custom" in Leanplum

### Actual behavior
The  `tracking_protection_setting` attribute remains set to standard even if the `E_Changed_ETP` event is properly generated

### Device information

* Android device: all
* Fenix version: 
• Nightly Build 200730
• Fenix Beta 80.0.0-beta-1

### Notes
Noticed while checking #11654

**Comment by ekager** [comment]
Does it change correctly on next startup? I believe we only send these setting values on Leanplum start

**Comment by AndiAJ** [comment]
Yes, sorry for the inconvenience wasn't aware of that. ☺️
