### ISSUE TITLE
FNX2-18807 ⁃ String changes to the ABOUT page

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#13135]
We want to mention the Daylight Release on ABOUT page. @betsymi will provide the string. 

Please note that this change should NOT be passed as a naming variable since (1) it only applies to Release (but we can also include it in Beta if it's easier) and (2) it should only show up on the ABOUT page and not anywhere else in the app.

**Comment by betsymi** [comment]
For release versions of Fenix beginning in 80 and running through Aug. 2021. Not Nightly and Beta, if possible. 

Change `%1$s is produced by Mozilla.` to `Firefox Daylight is produced by Mozilla.`

OR

Change `%1$s is produced by Mozilla.` to `%5$S is produced by Mozilla.` where %5$s is “Firefox Daylight” and is never translated.  

(Note 1, 2, and 3 are already used in Fenix - not sure how one reserves a name/variable assignment though)

**Comment by ebalazs-sv** [comment]
Verified as fixed on RC 80.0.1 from 8/21 and RC 80.1.0 from 8/25 with the following devices:
- Nexus 5 (Android 5.1);
- OnePlus A3 (Android 6.0.1);
- Samsung Galaxy Tab S3 (Android 8);
- Samsung Galaxy Tab S6 (Android 9);
- Google Pixel 3 XL (Android 9);
- Google Pixel 4 XL (Android 11).

"Firefox Daylight is produced by Mozilla." is displayed only on the About page.
