### ISSUE TITLE
FNX2-18808 ⁃ Migrate saved logins to concept-menu

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#13140]
SavedLoginsSortingStrategyMenu will be the first menu to be moved over to the new concept-menu system. This should save some tech debt around attaching private data to browser menu and abusing the highlighting code.

**Comment by NotWoods** [comment]
QA please check that the menu still works properly in this screen. The change in menu width is a known issue (https://github.com/mozilla-mobile/android-components/issues/7932)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/12.
Devices: Samsung Galaxy Note 10 (Android 10), Google Pixel 3 (Android 11).
