### ISSUE TITLE
FNX2-18810 ⁃ [Bug] Long page titles/urls in tab history have no padding on the right

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#13149]
## Steps to reproduce
Open a page with a long title/url
Open tab history by long pressing back/forward button

### Expected behavior
The tab history item has proper padding on the right

### Actual behavior
The title/url goes all the way to the edge of the screen
<img src="https://user-images.githubusercontent.com/6396431/88988544-0b993380-d28e-11ea-8908-43daf3b5cb1c.png" width=300 />

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 7/30

cc @brampitoyo This shouldn't be hard to fix, we just need to know what the correct padding value should be.

**Comment by brampitoyo** [comment]
@person808 The correct padding value should be 16dp. Thanks!

**Comment by sv-ohorvath** [comment]
Verified as fixed on 80.0.0-beta6 on several devices:
Samsung Galaxy Tab S6 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), Motorola Moto G6 (Android 8), OnePlus A3 (Android 6.0.1), Google Pixel 3a (Android 10), Nexus 5 (Android 5.1) and Huawei Mate 20 Lite (Android 10)
