### ISSUE TITLE
[Bug] Deleting folders+websites still results in a "deleting selected folders" popup in bookmarks

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13158]
## Steps to reproduce
In bookmarks multiselect some folders and websites
Delete using three dot menu option

### Expected behavior
A message like "deleting items" or "deleting folders and items" 

### Actual behavior
A popup like "Deleting selected folders"
### Device information

* Android device: ?
* Fenix version: Nightly

**Comment by AndiAJ** [comment]
Dupe of #6977 and #6974

**Comment by s-ankur** [comment]
@AndiAJ this is about the message that pops up when you delete the items, I don't see how it is related to either of the above issues

**Comment by s-ankur** [comment]
Edited for clarity

**Comment by AndiAJ** [comment]
Sorry @s-ankur , got mistaken. ☺️
