### ISSUE TITLE
[Bug] "Save to collection" button in tabs tray too bright in dark mode

### ISSUE THREAD

**Issue by evilpie** [mozilla-mobile/fenix#13152]
## Steps to reproduce
- Use dark mode
- Open tabs tray

### Expected behavior

"Save to collection" doesn't have an almost white background

### Actual behavior

The relatively large "Save to collection" button has a dark(-ish) background

### Device information

* Android device: Samsung S8
* Fenix version: Nightly 200731

cc @ekager because you fixed #13117

**Comment by ekager** [comment]
This is a standard UI component we use around the app independent of theme so this isn't a "bug". 

Cc @topotropic for feedback.

**Comment by evilpie** [comment]
The same (as far as I can tell) "Save to collection" button is used on the homepage and is used on the homepage and has a purple background there.

**Comment by AmyYLee** [comment]
Hi, the light grey is used for secondary buttons, mostly found in settings. Can you update the collections button to the following for light/dark themes:

Text colour: 
Color: Light Grey 5 (#FBFBFE)

Dark theme Button
Color: Violet 50 (#9059FF)

Light theme Button
Color: Ink 20 (#312A65)

Thanks!

**Comment by AmyYLee** [comment]
> Hi, the light grey is used for secondary buttons, mostly found in settings. Can you update the collections button to the following for light/dark themes:
> 
> Text colour:
> Color: Light Grey 5 (#FBFBFE)
> 
> Dark theme Button
> Color: Violet 50 (#9059FF)
> 
> Light theme Button
> Color: Ink 20 (#312A65)
> 
> Thanks!

Spoke to the team and I think we are going to review the secondary button colour palette for dark theme. Please hold, will provide an update.

**Comment by ekager** [comment]
cc @topotropic are we still doing a secondary color dark theme review?

**Comment by evilpie** [comment]
*ping* @topotropic

**Comment by topotropic** [comment]
Thanks for the ping! 

for the button we can use   
<color name="dark_grey_50">#32313C</color>

and text is
<color name="light_grey_5">#FBFBFE</color>

**Comment by evilpie** [comment]
I tried to figure out how to make that change myself, but I didn't really get far. I think I might need to add a new `<style>` to `styles.xml` for this specific button, but I don't really understand how it selects which color to use. 
I am not necessarily interested in learning Android development. 
@ekager would you consider just doing this instead?

**Comment by evilpie** [comment]
This is still a problem. This just needs an implementation.

**Comment by evilpie** [comment]
Seems like that button was removed in the meantime.
