### ISSUE TITLE
[BUG] A part of screen doesn't display above URL bar any web content on some websites

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#13151]
See the attached screen recording, a little part of screen doesn't display any content and remain empty on some websites. 
On most of the sites,It works fine. I experienced this issue on webpages with more text content like news sites, blogs.

Screen Recording:
https://photos.app.goo.gl/FN2ecNqHGgXct4Nk6 

Device : Xiaomi Redmi Note 4 Android 7.0

Fenix : Nightly 200730 06:21 (Build #22120631)
AC: 53.0.20200729190533, bb7dbe3ec
GV: 80.0a1-20200727095125
AS: 61.0.10

Add ons : Ublock origin, Decentralyses, Dark Reader

**Comment by kbrosnan** [comment]
This looks to be advertisement div, I get the same behavior on Chrome.
