### ISSUE TITLE
[Bug] you can place a bookmarks folder inside itself; deleting it after this does not work

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13157]
## Steps to reproduce
Make a bookmarks folder
Edit it using 3 dot menu
Set the folder to the folder itself
Save it and try to delete the folder
### Expected behavior
It shouldn't be possible to save inside itself
### Actual behavior
Deleting does not work; no bookmarks operations work at this point
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Related #6977

**Comment by grigoryk** [comment]
Trying this out, the move isn't actually executed (bookmark structure within places.sqlite is in-tact, folder remains under the mobile root). However, editing bookmarks does stop working. Restarting the app gets everything back to normal.

**Comment by grigoryk** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/15203

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
