### ISSUE TITLE
[Bug] Account not displayed in Settings after turning on sync

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#13162]
## Steps to reproduce
1. Open browser and go to "Turn on Sync" from Mneu/Settings.
2. Tap on "Turn on Sync".
3. Use Email/Ready to scan options to log into an account.
4. Insert the email and password or scan the QR code and Sign in.
5. User is redirected to "Settings".

### Expected behavior
The connected account is displayed.
### Actual behavior
"Firefox Account" is displayed
### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Beta 80.0.0-beta.2 and Nightly 7/31

Note:
- There are times when the sync icon for the account is not displayed
- I didn't encounter this issue on 79.0.1
- When navigating out of Settings and return or by taping on "Firefox Account"  and return then the connected account will be displayed.

GIF - Samsung Galaxy S9 (Android 8)
![20200731-153910](https://user-images.githubusercontent.com/49859863/89036125-cab02600-d344-11ea-98d9-1e1d0e5e25d1.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4250)

**Comment by ekager** [comment]
cc @NotWoods maybe a regression from https://github.com/mozilla-mobile/fenix/pull/12917 ?

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 81.1.0-beta.1 (Build #2015761489) GV 81.0 from 9/2 with Samsung Galaxy Tab S3 (Android 8).

**Comment by ebalazs-sv** [comment]
This issue is also reproducible on Nightly 200908 06:01 Build #2015762673 GV 82.0a1 from 9/8 with Motorola Moto G6 (Android 8).

@NotWoods Hi! It seems that you had been unassigned by mistake and I can not add you as assignee. Could you please reassign this to yourself? Thanks!

**Comment by NotWoods** [comment]
I'm no longer at Mozilla so I've been removed from the mobile org

**Comment by mcarare** [comment]
Eng note: from what it seems, the update call made in `onResume` is made when the account is in a `AuthenticatedNoProfile` state, before it transitions to `AuthenticatedWithProfile`. No other future update call is made in the observer.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Release 86.1.0 RC1 from 2/16 with Samsung Galaxy Tab S3 (Android 8).

**Comment by lobontiumira** [comment]
Reproducible on Beta 89.0.0-beta.1 with samsung Galaxy Note 8 (Android 9).

**Comment by Alexandru2909** [comment]
Testing this issue, I found out the account is displayed properly when the `updateAccountUIState` call is made from onResume with the `Authenticated` account state. However, having a slower internet speed leads to calling the update method from onResume with a `null` profile. After this, the callbacks inside the observer have not been triggered. Another weird behavior that happened was when the `onProfileUpdated` was triggered but the coroutine was never launched.
Tagging @grigoryk for a more experienced perspective, maybe this is a known issue with `AccountObserver`?
