### ISSUE TITLE
[Bug] Remove 'x' close button from History navigation bar

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#13168]
## Steps to reproduce
Open 'History' from the toolbar menu

### Expected behavior
The navigation bar at the top should only have a back arrow on the left.

### Actual behavior
The navigation bar at the top has both a back arrow on the left _and_ an 'x' close button on the right. Please remove the 'x' close button.

### Device information

* Android device: Pixel 4, Android 10
* Fenix version: Nightly 200731 06:06

**Comment by s-ankur** [comment]
Can also be done for bookmarks

**Comment by apbitner** [comment]
@s-ankur we'd like to leave it for bookmarks so that if a user navigates down a few levels of folders they can easily exit without having to tap the back arrow multiples times.

**Comment by shen714** [comment]
I'd like to take care of this if it's OK : )

**Comment by Poopooracoocoo** [comment]
there's also both a close and a back button in the toolbar of the recently closed tabs page.

**Comment by apbitner** [comment]
@topotropic do you mind if we remove the 'x' from recently closed tabs for the same reasons as History above?

**Comment by topotropic** [comment]
> @topotropic do you mind if we remove the 'x' from recently closed tabs for the same reasons as History above?

You could get to this screen from history as well and if we keep the x for bookmark folders, we could use the same rule here as well. But I also don't have strong opinions here. Thanks!

**Comment by apbitner** [comment]
Good to know, I didn't realize you could get to it from elsewhere, so I think it does make sense to keep both.

**Comment by amkcpu** [comment]
@topotropic The rationale for keeping it for bookmarks was given in https://github.com/mozilla-mobile/fenix/issues/13168#issuecomment-667319299:
> we'd like to leave it for bookmarks so that if a user navigates down a few levels of folders they can easily exit without having to tap the back arrow multiples times.

For history and recently closed tabs, the `x` serves absolutely no additional purpose, it's redundant. On the contrary, it might mislead a user to expect a "delete" kind of functionality.
That's why I would be in favor of dropping the button for recently closed tabs and history, while keeping it for bookmarks (where it solves a valid problem).

**Comment by ekager** [comment]
Going to follow @topotropic recommendation here for now to keep both for recently closed, but remove for history.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both latest **`Nightly Build 201022`** and **`Firefox RC 83.0.0-beta.1`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20201022-115249](https://user-images.githubusercontent.com/51314259/96848722-74dbad80-145d-11eb-992a-a308d74a54ea.png)
