### ISSUE TITLE
[Bug] Synced tabs displayed, when pull to refresh, if the page wasn't closed & open tabs disabled in account settings

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#13169]
## Steps to reproduce
1. Sign in with the same Firefox account on 2 or more devices.
2. Open a couple of tabs on both of them.
3. On device1 go to Synced tabs.
4. On device 2, disable "Open tabs" in account settings.
5. On device 1, pull to refresh synced tabs.

### Expected behavior
Synced tabs aren't displayed.

### Actual behavior
Synced tabs are displayed when the page is loading.

### Device information
* Android device: Huawei MediaPad M2 (Android 5.1.1).
* Fenix version: Nightly 7/31, Beta 80.0-b2.

![20200731_152539](https://user-images.githubusercontent.com/58466444/89044121-3351cf80-d352-11ea-8d08-237ec033e3a3.gif)

**Comment by Mugurell** [comment]
@sflorean Is this still an issue?

I can't reproduce
![SyncedTabs](https://user-images.githubusercontent.com/11428869/91844241-c0dd5380-ec5f-11ea-8d07-3330af0b0188.gif)
[video](https://drive.google.com/file/d/1s575ivKNu-hkLAMSMASIPB7A_qMeCQdF/view?usp=sharing)

**Comment by softvision-miralobontiu** [comment]
Hi all,
I wasn't able to reproduce this issue. I've signed-in with the same account on 3 devices, followed the STR, and the first device displayed the "Please enable tab syncing." message on the Synced tabs page.
Tested on the latest Nightly build from 9/4 with Samsung Galaxy Tab A6 (Android 5.1.1), HTC 10 (Android 8), and Samsung Galaxy Tab S6 (Android 9).
Thanks,
