### ISSUE TITLE
Strange Tab in Collections Items Behavior When Deleting Multiple Tabs

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#13177]
1. If a collection has 2 items and you swipe them away one by one, it won't prompt you or delete the collection on the last item's removal (so then you end up with an empty collection).
2. Swiping away on the bottom tab of a collection doesn't update the remaining item to be the next bottom item visually.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4261)

**Comment by liuche** [comment]
Empty state for Collections - is this something that @ekager and @topotropic can look at during the Collections sprint?

**Comment by sv-ohorvath** [comment]
Still reproducible on Nightly 100. Reopening

**Comment by SoftVision-LorandJanos** [comment]
1. The issue with the collection is still reproducible, also, seems to be related to #20391. Collection can be created empty or delete all its items for it to be empty and still exist.
2. I don't know if I understood the second part right, for me the behavior looks expected, however there is an issue with Collection created with a webpage (which after adding a few more pages gets to the bottom of the list) and if the original item is deleted, the collection is closed/deleted with all its added content.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812746

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
