### ISSUE TITLE
[Bug] On private mode, "new tab" option opens new non priavate tab

### ISSUE THREAD

**Issue by officiallor** [mozilla-mobile/fenix#13174]
## Steps to reproduce
Open Firefox, tap on private mode and then from the 3 bullets, tap New Tab

### Expected behavior
Open a new private tab

### Actual behavior
Opens a new non private tab

### Device information

* Android device: Mi8 Android 10
* Fenix version: ?

**Comment by kbrosnan** [comment]
Fenix has not used the 3 dot menu to open new tabs for a few months now. Please update to a more recent build. 

Using the current methods, tap tab counter, tap + Private. This works for me using current Firefox Beta and Firefox Nightly.
