### ISSUE TITLE
[Bug][Android 5] Keyboard displayed on when tapping back from Edit logins

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#13171]
## Steps to reproduce
1. Save 2-3 logins.
2. Go to Settings-Saved logins- select one login - edit - tap on the username in order to bring up the keyboard.
3. Tap on the back arrow from the app.
4. Tap again on back arrow from the app. 

### Expected behavior
Keyboard is dismissed.

### Actual behavior
Keyboard is displayed. 

### Device information
* Android device: Huawei MediaPad M2 (Android 5.1.1).
* Fenix version: Beta 80.0.0-beta.2

**Comment by Bawya1098** [comment]
@jakefleming156  ,   I would like to try and work on this.

**Comment by Bawya1098** [comment]
@data-sync-user, whether this issue is still in?

**Comment by sanchi0204** [comment]
Can I work on this?
