### ISSUE TITLE
[BUG] Swipe gesture changed

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#13172]
I don't know if it's a bug or not.

But, previously, I had to swipe from left to right on the URL bar in order to switch lower tabs and right to left for switching to upper tabs.

But in new update it's reversed!! I think that previous gesture was good. 

Fenix : Nightly 200731 06:06 (Build #22130613)
AC: 53.0.20200729190533, bb7dbe3ec
GV: 80.0a1-20200727095125
AS: 61.0.10

**Comment by cadeyrn** [comment]
It was changed in #12861.

**Comment by Glitchy-Tozier** [comment]
Sounds like a great thing to let the user decide which way to swipe in the settings.
To me, the current swiping direction feels a little off, others might prefer it the current way.

**Comment by person808** [comment]
cc @topotropic Is an option something we might consider?

**Comment by opusforlife2** [comment]
I don't know about tab ordering in the tab tray, but swiping left to right for newer tabs for an LTR language just seems very odd. For an RTL language, people might have the opposite preference. Although, if desktop Firefox opens new tabs only on the right regardless of language direction, shouldn't Fenix follow the same behaviour for familiarity's sake?

**Comment by cadeyrn** [comment]
> Although, if desktop Firefox opens new tabs only on the right regardless of language direction, shouldn't Fenix follow the same behaviour for familiarity's sake?

You can read #12861 for context why it was changed. The old order caused also confusion, just for other people. I think it's more important to keep consistency within the product, more than consistency with products on other platforms. If the consensus is that the order for the gesture should be changed again then it seems to be that we should talk about the order of tabs in the tabs tray. But to have a reversed order as in the tabs tray seems like a bad idea to me.

**Comment by opusforlife2** [comment]
From #12861:
> the newest tab in tab tray would be at botton
the most left tab in "swiping gesture" would be the oldest
The oldest tab in tab tray would be at top
the most right tab in "swiping gesture" would be the newest.

I agree with this set of behaviours. This seems the most intuitive. Chrome has it right. Regardless of top or bottom bar, new tabs should open downwards in the tab tray, and towards the right in terms of swipe direction.

**Comment by tom-james-watson** [comment]
Yeah this change really threw me off.

I'm curious as to whether Mozilla actually did any user testing on this change? Just because some users claimed about the old direction didn't meant it made sense to change it. I think, as you say, you'll now just have a new set of disgruntled users.

I did some non-scientific user testing on this when I was with a group of friends. I showed them how tabs are ordered from top to bottom in the tray (I think this goes against established UX conventions too but I don't think it's as big of a deal) and opened a new tab, showing them that it is added to the top of the list. I then asked them to swipe the bottom bar to get back to the last tab. Every single person tries to swipe from left to right.

The change seems to have been made based on https://github.com/mozilla-mobile/fenix/issues/12861#issuecomment-663509790, but to me this makes no sense. Firstly, tabs in pretty much every single application ever made have new tabs on the right. Secondly, if we are equating to text, then surely new tabs should still be added on the right - text on the right is newer than text on the left.

I think this should be revisited, preferably with some real-world user testing on expected behaviour.

**Comment by RealGJ** [comment]
Just imagine a note book, where we write new lines always below  than that of the old, similarly the new tabs should always open below the old ones. 

Again, for older pages we flip the page from LEFT to RIGHT. Similarly, we should Swipe LEFT to RIGHT for old Tabs.
I'm not sure about the example of notebook is right. But it makes sense and easier to understand. Because we are used to that!!

**Comment by cadeyrn** [comment]
> I'm curious as to whether Mozilla actually did any user testing on this change? Just because some users claimed about the old direction didn't meant it made sense to change it. […] I think this should be revisited, preferably with some real-world user testing on expected behaviour.

Well, your statement does not make much sense either. What do you think happens when you do user testing? It happens exactly the same: Some users complain about the implemented solution. Let's say Mozilla makes a user test, based on the current solution. With your argumentation it doesn't make sense to change it just because some people don't like the current solution. It's what you said. Or does a change only make sense if the result of the test happens to match your opinion? There is not "one truth", people can prefer the one way or the other one and #12861 proves that not everyone shares your opinion.

**Comment by RealGJ** [comment]
@cadeyrn don't consider them. I'm trying to fix the bug on fasthub-libre android app for which allows multiple likes and heart by any single user. Atleast. That  how its appears on mobile!! 

It was my bad to test that here!! Sorry!

**Comment by cadeyrn** [comment]
> It was my bad to test that here!! Sorry!

Thanks for clarification. But it's GitHub, so anything is possible. 😂 I removed my last sentence. ;)

**Comment by tom-james-watson** [comment]
> does a change only make sense if the result of the test happens to match your opinion? There is not "one truth", people can prefer the one way or the other 

User testing gives you data with which you can make an informed decision. It would tell you what percentage of people would expect which direction, for example. If it turns out 90% expect one of the ways then it would probably make sense to have it work in that way.

**Comment by AmyYLee** [comment]
@topotropic for feedback

**Comment by madb1lly** [comment]
Hi all,

I don't use this feature much but using it today was weird! I read through #12861 and the feedback given seems to be inconsistent with how the tab list works, plus some other things didn't make sense as pointed out in discussion here. I've put more comments on that (now closed) issue so won't repeat them here, but in summary - the current way it works doesn't make sense to me or feel right.

Cheers 🙂

**Comment by yoasif** [comment]
Was going to file this as a new bug - glad I searched for it first!

Some considerations (some have already been commented about):

* Chrome does it the opposite way that we have currently - most users who know this gesture will have used it in that product and will be confused about the opposite behavior 
* I see this as akin to turning a page, and indeed I use this exact gesture on ebook apps - try Fbreader, for example. At least in LTR languages, I expect the right to left swipe action to show me the newer page 

Given that other apps do the opposite of what we are doing here, is there a good reason to break user expectation here? This will break muscle memory badly and result in Firefox seemingly having mystery meat navigation. 

I think this should be looked at again before 81 goes to release @liuche @vesta0.

**Comment by Siva981** [comment]
Day to day Firefox For Android user here. I am not a developer/coder. I too feel that the current setup of tab ordering and tab switching is totally off. As if it focuses only on left handed people (tab switching) and reversely wired (

**Comment by binocry** [comment]
Yeah this behavior so annoying please change like other browser ASAP!!!

**Comment by jenabaivab** [comment]
Please switch the tab swipe gesture so that the newest tab is on the right most direction. This is very unintuitive coming from different browsers or even using different browsers in between.

**Comment by klorinczi** [comment]
Please change the tab swipe gesture, so that the newest tab should be created on the right.

Also when swiping from right to the left, should switch to the newer tab. Swiping from right to the left, should bring the older tab.

**Comment by opusforlife2** [comment]
Opening new tabs to the left makes even less sense, now that you can activate Grid view for the tab tray. New tabs open to the right and downwards like any LTR layout in Grid view.

Now, swiping to the left switches to a newer tab, which is on the right in the tab tray. O_o

**Comment by marco-sanjuan** [comment]
For me, this is one of those features that makes the mobile browsing experience almost as rewarding as on a tablet or computer.

But in all these systems, new tabs are on the right ...

Please change this so we can start using this great feature.

**Comment by madb1lly** [comment]
Hi all,

@opusforlife2 I agree that with grid view the current swipe to change tab direction is even more confusing.

The only cases I've found where newer is on the left is my email programme (FairEmail, but that's customisable I think) and RSS reader (NewsBlur). 

Cheers 🙂

**Comment by opusforlife2** [comment]
@madb1lly Even there, it makes sense for something like an email app or an RSS reader because you're browsing a list of _already_ existing items from left to right (new to old). Here, we often open new tabs _from_ current ones, and that is an entirely different concept.

**Comment by rituraj22** [comment]
I agree with everyone here. This is the single biggest problem for me in using fenix. New tabs should open below/right similar to desktop firefox and other browsers(All chromium browsers)

**Comment by topotropic** [comment]
Thanks for the feedback everyone. Based on this discussion and the decision made in this ticket https://github.com/mozilla-mobile/fenix/issues/11376#issuecomment-709505058 we should reverse the order:

- for left to right languages: oldest tab is on the left, newest on the right
- for right to left languages it is reversed: oldest tab is on the right, newest on the left

**Comment by madb1lly** [comment]
Hi @topotropic and the team at Mozilla,
Thank you for reading and considering our feedback :raised_hands: 
Cheers :smiley:

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201105`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

✔️ Video left to right languages:  oldest tab is on the left, newest on the right
![20201105-145912](https://user-images.githubusercontent.com/51314259/98245230-4a1f4800-1f79-11eb-8c50-9aed6c007ac2.gif)


✔️ Video right to left languages: oldest tab is on the right, newest on the left
![20201105-150105](https://user-images.githubusercontent.com/51314259/98244996-f876bd80-1f78-11eb-8267-c9c911d2057a.gif)

**Comment by dausruddin** [comment]
New tabs are placed at the top. Is that how it should work? Wouldn't placing them a the bottom like how they used to be would be better?

**Comment by Siva981** [comment]
> New tabs are placed at the top. Is that how it should work? Wouldn't placing them a the bottom like how they used to be would be better?

I agree. New tabs at the bottom makes sense the most. Current setting is as if one starts writing or typing from the bottom of a page.

Please change this back too. Or at least, please provide an option for us under "Tab Settings", to change that on a per user basis.
