### ISSUE TITLE
[Bug] RuntimeException Cannot confirm/dismiss a Prompt twice.

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#13179]
Not a ton of crashes, but easily repros: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8978923/?query=is%3Aunresolved%20baseprompt

## Steps to reproduce
Go to a youtube video
Click the forward button to open the share sheet
Back out of sharesheet

### Expected behavior
Doesn't crash

### Actual behavior
Crashes

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 7/29

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Firefox Nightly build from 8/5 with:
* Samsung Galaxy Tab S6 (Android 9),
* Google Pixel (Android 10),
* Sony Xperia Z5 Premium (Android 7.1.1),
* OnePlus 5T (Android 9).
