### ISSUE TITLE
FNX2-18831 ⁃ [Bug] Can't add heise.de shortcut to homescreen

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#13176]
## Steps to reproduce
Go to heise.de
Click "Add to homescreen"
Click "Add" in the dialog

### Expected behavior
Dialog pops up to long-press/drag to be added to homescreen

### Actual behavior
Nothing happens, and site is not automatically added to homescreen

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 7/29

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200819 Build #2015758835 from 8/19 with Pixel 2 (Android 9).
I will remove the qa:needed label and close this issue.
