### ISSUE TITLE
Investigate Generated Top Sites Exclusions Management 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#13175]
Breakout of https://github.com/mozilla-mobile/fenix/issues/10342

We have identified in the RFC that we need to think more about the interactions where users can "remove" generated top sites (generated from their history), ie add a generated top site exclusion.

The user story is I, as a user, often visit a site for work (let's say Bugzilla), but don't want to see Bugzilla as a top site.

Open questions: 
- When a user removes a generated top site - should we a) remove this site from history b) Create an exclusion list and never show this site from history again? 
- Can a user manage this top site site exclusion list? How? Individually (might be private data)? Or just "clear all"?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4259)

**Comment by cadeyrn** [comment]
> When a user removes a generated top site - should we a) remove this site from history

From my POV: No. If I remove a website from the top sites then because I don't want that the website appears as a top site. It doesn't mean that I want an incomplete history. But Firefox for Desktop has options for both.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813650

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
