### ISSUE TITLE
Make long press on a tab counter open a new tab rather than a context menu

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#13178]
### What is the user problem or growth opportunity you want to see solved?
Long pressing the tab counter brings up a context menu (close tab, new tab, new private tab). I think it would be a better work flow to have long press immediately open a new "non-private" tab.

### How do you know that this problem exists today? Why is this important?
I think the majority use case is opening a new tab. At the moment long pressing the tab counter is not really a shortcut, it's actually slightly harder to open a new tab via long press than it is via tab tray

Long tap tab counter ; tap New tab 
vs
Tap tab counter; Tap + icon

### Who will benefit from it?
* users who want to open a new tab with a single (long) tap
* users who want Chrome-like behavior

**Comment by sskodje** [comment]
Is it really necessary, considering you can double tap it to create a new tab?

**Comment by AVHon** [comment]
Being able to double-tap the tab counter to open a new tab would be equivalently good, in my eyes. With the 79 release, the only ways to open a new, blank tab seem to require taps in multiple places.
