### ISSUE TITLE
Option to show images (always / Wi-Fi only / never)

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#13180]
### What is the user problem or growth opportunity you want to see solved?

When I use a bad network, images are making everything slower and aren't necessarily needed.

On Fennec, it is available under settings -> advanced -> data saver category -> show images, and you could change between always, Wi-Fi only and never.
On Fennec, you can still view an image if you set "show images" to never: you have to long press and click on "show image", therefore you can choose what image to show (e.g. you don't want to see user's profile picture on Twitter but you want to see a picture in a post, then you manually display it).
On Fennec, it was blocking images, video thumbnails but not GIFs. I think GIFs should also be blocked.
On Fennec again, after you show an image with the steps I explained above, you had a "Image unblocked     |    show all" toast and you can click on "show all" to display all images **on this page only**.

I think the implementation is perfect except GIFs.

### How do you know that this problem exists today? Why is this important?
It is important because images use a lot of data and is not really useful when you have low bandwith, or when you pay for data.

### Who will benefit from it?
People who want to save data, e.g. people with low bandwith, or people who pay for data  / people not having unlimited data (e.g. mobile data).

**Comment by cadeyrn** [comment]
It's part of #11460.

**Comment by B0pol** [comment]
… and no long press and click show image to display it, which is really useful

**Comment by s-ankur** [comment]
You can use UBO's block media elements feature as a temporary workaround btw

**Comment by yoasif** [comment]
Existed in Fennec, is being asked for in Play Store reviews:

https://play.google.com/store/apps/details?id=org.mozilla.firefox&reviewId=gp%3AAOqpTOFM7X7y5MlspDskaZWQq6FcIrcTo_cy9RJHyNh_EYt6YbjoyVEkhtn_i6fueKyMHqfqjqlyU1rpOfwDKg

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/12711 and https://github.com/mozilla-mobile/fenix/issues/810

**Comment by kbrosnan** [comment]
Closing as duplicates #12711 and #810
