### ISSUE TITLE
New version(fenix) is worse than previous(old stable)

### ISSUE THREAD

**Issue by 12sunflowers** [mozilla-mobile/fenix#13185]
Performance is bad, user interface is bad in last 79 fenix

Previous(old stable) 78 version was much better than fenix

my IMHO

**Comment by cadeyrn** [comment]
This is not how giving feedback works.

**Comment by ekager** [comment]
What @cadeyrn said. We are open to feedback, bugs, and feature requests. Please open individual tickets about specific performance issues with your configuration or which pain points you're having with the UX if you would like to help improve the app, but keep in mind we will not be responding to this tickets with attitude like this.
