### ISSUE TITLE
[Bug] Copy action bar -> "Search" only works once

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13199]
## Steps to reproduce
Do a text selection
Click search
Click back or switch back to the original tab
Jiggle the page a little so copy action bar reappears
Click search
### Expected behavior
It searches
### Actual behavior
Nothing
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix nightly

**Comment by XxJibril** [comment]
for me, it does search the 2nd time if a different text selection (1 more/less character) but if the exact same text is selected a second time nothing happens on tapping the search
