### ISSUE TITLE
[Bug] 'null' title for YouTube videos shared from Firefox Nightly

### ISSUE THREAD

**Issue by xylophonez** [mozilla-mobile/fenix#13193]
## Steps to reproduce

1. Open any YouTube video in Firefox Nightly
2. Share via the dot menu or YouTube's native Share button
3. Share to Telegram or Google Keep

### Expected behavior

Title is the title of the video, or just omitted (Chrome omits it, presumably because it is already shown in the link preview)

### Actual behavior

Title reads 'null' -  ![screenshot from Telegram](https://user-images.githubusercontent.com/69069725/89095631-879f9280-d3d8-11ea-8cbf-83490b457ee6.jpg)

### Device information

* Android device: Samsung Galaxy A10 (SM-A105FN)
* Fenix version: Nightly 200731 06:06 (Build #22130612)

**Comment by xylophonez** [comment]
This looks fixed for me now, can close?

**Comment by kbrosnan** [comment]
Sure. Closing as works for the reporter.
