### ISSUE TITLE
Option "Search Google" missing while copying text

### ISSUE THREAD

**Issue by looneyhill** [mozilla-mobile/fenix#13195]
In the normal version of Firefox, there is an option "Search Google" when you copy certain text, beside "Copy, share, select all...". But in Firefox Nightly this option is missing. This is highly inconvenient! Please bring this option back. Thank you in advance.

**Comment by cadeyrn** [comment]
I cannot confirm. There is an option "Search" that uses the default search engine, for example Google, in Firefox Nightly. Please check if you have a item "Search" (don't look for "Search Google"). If this item really not exists please provide more information about your device and Android version.

**Comment by looneyhill** [comment]
> 
> 
> I cannot confirm. There is an option "Search" that uses the default search engine, for example Google, in Firefox Nightly. Please check if you have a item "Search" (don't look for "Search Google"). If this item really not exists please provide more information about your device and Android version.

Hi Cadeyrn, thanx for your response. I have found the "Search" option. Thanx for your help! ;-)
