### ISSUE TITLE
Customize site permissions doorhanger for tablet layouts

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1319]
Relate issue https://github.com/mozilla-mobile/fenix/issues/1257

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4269)

**Comment by mheubusch** [comment]
@Amejia481 is this issue completed by your work in 1409? if so, can we close this issue @vesta0 ?

**Comment by Amejia481** [comment]
No this will be covered in this issue.  #1409 was bug report.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809961

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
