### ISSUE TITLE
Add Equivalent of Desktop Firefox's View Image Info and View Page Info

### ISSUE THREAD

**Issue by issue-dispenser** [mozilla-mobile/fenix#13206]
### What is the user problem or growth opportunity you want to see solved?
I would like to be able to view details of a webpage, including the specifics of the page's media (images, etc.). On desktop Firefox, this can be done using `Tools -> Page Info` (or `Ctrl+I`). Viewing the specifics of a single image can be done by right clicking the image and selecting `View Image Info`.

### How do you know that this problem exists today? Why is this important?
I don't believe there's a(n easy) way to do this on Fenix at the moment, and I would occasionally like to view such information without switching to desktop Firefox.

### Who will benefit from it?
Those mobile users that would like to view detailed information of webpages or images.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4282)

**Comment by buttercookie42** [comment]
There used to be an addon for that, although unfortunately it was killed by the Webextension migration (no fundamental incompatibility as far as I can tell, just that nobody found the time to port it to the new add-on system).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813276

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
