### ISSUE TITLE
[Bug] Scroll bad performance

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#13200]
## Steps to reproduce
Go to the https://www.speedtest.net/ and scroll up and down between the Speed preview and bottom.
### Expected behavior
The scroll to be smooth.
### Actual behavior
The page is laggy.
### Device information

* Android device: P10 Lite WAS-LX1, 8
* Fenix version: 200801

Normal Firefox: Much better but still is a little
Nightly: Worst
Focus: Better but not really

**Comment by s-ankur** [comment]
Related #12373
