### ISSUE TITLE
[Bug] Scrolling between text selection actions creates offset for selection cursor

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#13208]
## Steps to reproduce
1. Open a website with selectable text, e.g. https://www.mozilla.org/en-GB/mission/
2. Select some text
3. Scroll down while still keeping the selected part in your viewport
4. Drag the lower selection cursor down

### Expected behavior
The lower selection cursor follows the touch pointer.

### Actual behavior
The lower selection cursor jumps below the context menu and now has an offset to the touch pointer.

![video-text-selection](https://user-images.githubusercontent.com/42788925/89121133-7def5b00-d4bc-11ea-8388-8bd9a243cbc8.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 200802 06:16 (Build #22150626)
AC: 53.0.20200801130512, c6137485e
GV: 81.0a1-20200730093956
AS: 61.0.10

**Comment by makotokato** [comment]
This isn't related to GV and this occurs on Windows 10.

I filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1657256

**Comment by PulkitGupta707** [comment]
This bug has been there for over a month

**Comment by hwinnemoe** [comment]
BZ-1657256 has been closed and I cannot reproduce this anymore on Nightly 200910 06:07 (Build #2015763057).

**Comment by makotokato** [comment]
@kbrosnan could you close this?  BMO is resolved as fixed and this is verified. (I don't have permission to close this)

**Comment by kbrosnan** [comment]
Closing
