### ISSUE TITLE
[Bug] Website header gets detached

### ISSUE THREAD

**Issue by guilhermehrt** [mozilla-mobile/fenix#13205]
## Steps to reproduce
1. Open any website that has a pinned header
2. When you're not at the top of the page, scroll up

### Expected behavior
Nothing happens

### Actual behavior
The header gets detached [Printscreen](http://imgur.com/gallery/J1AQV5I)

### Device information

* Android device: Samsung Galaxy Tab A
* Fenix version: Nightly 200801 06:06 (Build #22140615)

**Comment by s-ankur** [comment]
Duplicate of #10598
