### ISSUE TITLE
[Bug] Very high memory usage - intermittent

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#13207]
3 boring tabs open (newspapers), typically uses ~400 Mbyte. Sometimes it spirals up to 2.4 Gbyte or more with same three tabs open.  Closing all tabs doesn't fix it, zero open tabs still uses 2.4 Gbyte. Killing & relaunching Fenix does fix it, goes back to ~400 Mbyte.   See Android Developer memory report screen grab below. Happens to me perhaps once a day (maybe once per hour's use). I usually update Fenix Nightly every day so my uptime is fairly low.  

I tried to do "Measure and save" in about:memory but nothing seemed to happen, so here is a screen grab. It seems to be the main process heap, the web content process is using little memory.

![Screenshot_20200802-103609_Firefox Nightly](https://user-images.githubusercontent.com/40568887/89120202-54c6ce80-d4ac-11ea-99ba-2a843451a0d9.jpg)
![Screenshot_20200802-103022_Settings](https://user-images.githubusercontent.com/40568887/89120208-614b2700-d4ac-11ea-8e8e-cb8f45e79234.jpg)

**Comment by hwinnemoe** [comment]
Duplicate of #9065

**Comment by Cheap-Skate** [comment]
Sounds like you guys are on top of it. Great.
