### ISSUE TITLE
[Bug] Send Tab from PC desn't work 

### ISSUE THREAD

**Issue by JoGarWeb** [mozilla-mobile/fenix#13216]
## Steps to reproduce
1. Close Firefox and don't use for some minutes (20 min aprox) or Force Stop App 
2. Send tab from PC
3. Open Firefox on Android

### Expected behavior
1. Should be appear a notification with the link tab sent. 

### Actual behavior
1. The sent tab only appear if you go to Settings/Account and Sync Manually (Even if the Last Sync was 0 minutes ago) 
*** Aditional: It could be days waiting tab until you Sync Manually. 

### Device information

* Android device: Xiaomi A2 Lite
* Fenix version: Nightly 200802 06:16 (Build #22150627)
The problem is also in Firefox 80 Beta.

**Comment by sv-ohorvath** [comment]
Thank you for your report. This is the same as https://github.com/mozilla-mobile/fenix/issues/8582 so I'll close it as a duplicate.
