### ISSUE TITLE
[Bug] Support window.print()

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#13214]
## Steps to reproduce

1. Navigate to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_print
2. Tap "Print this page"

### Expected behavior

Print dialog appears. 

### Actual behavior

Nothing happens.

See also https://github.com/mozilla-mobile/fenix/issues/10217

Also in issue in Reference Browser. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4289)

**Comment by makotokato** [comment]
Fennec didn't support this.
- https://bugzilla.mozilla.org/show_bug.cgi?id=739038
- https://bugzilla.mozilla.org/show_bug.cgi?id=1247609

**Comment by texasbruce** [comment]
Any update on this?

**Comment by karlcow** [comment]
Another duplicate for this. 
https://github.com/webcompat/web-bugs/issues/77486

**Comment by headbank** [comment]
An observation made in #10217 that is probably even more relevant here:

While we await the actual print functionality's arrival, the current state of this hurts web developers. If I understand correctly, `window.print` is totally MIA, so a method in which it is called will just quietly puke, which may clobber subsequent js code. (Whether `window.print()` should really only be called in isolation, or always wrapped in a try/catch, is arguable but besides the point.)

Even when the user-facing upshot is limited to "Clicking the Print This Page button and nothing happens", it's still likely to be assumed by many users that the site is broken and the web dev is to blame.

This is driven by the twin likelihoods (IMHO) that (a) most users and (b) a great many web developers will tend to assume that any smartphone browser does support printing. Fenix really is an outlier in this respect, as many people in the other ticket have pointed out.

I would very much like Fenix to give UI feedback to the user that printing is currently unsupported.

**Comment by karlcow** [comment]
There is also https://bugzilla.mozilla.org/show_bug.cgi?id=1659818

**Comment by headbank** [comment]
> There is also https://bugzilla.mozilla.org/show_bug.cgi?id=1659818

Which in turn appears to await https://bugzilla.mozilla.org/show_bug.cgi?id=1659819
(If I have understood what's been said there)

**Comment by headbank** [comment]
Stuff is happening: https://bugzilla.mozilla.org/showdependencygraph.cgi?id=1659818

The top two ellipses went from green to grey (resolved) this morning :)

**Comment by cpeterso** [comment]
Closing this issue because we're tracking `window.print` in https://bugzilla.mozilla.org/show_bug.cgi?id=1659818
