### ISSUE TITLE
[BUG] No dark background in Ublock origin page

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#13210]
When we use fenix in Dark Mode, the Ublock origin's details page should have dark background too, instead it has light background irrespective of Browser theme.

Steps to Reproduce:
1. Install Ublock origin in Fenix
2. Go to its details page.

 Device: Xiaomi Redmi Note 4 Android 7.0

**Comment by hwinnemoe** [comment]
This is an enhancement every add-on has to address individually, see https://github.com/uBlockOrigin/uBlock-issues/issues/401.

**Comment by kbrosnan** [comment]
Closing as upstream issue with uBlock Origin
