### ISSUE TITLE
Option to add 'Open with Private tab' or 'Open with normal tab'

### ISSUE THREAD

**Issue by 97pratyush** [mozilla-mobile/fenix#13223]
Whenever I click any link, browser could ask if you want to open in private tab or not?

If I don't want the site to have my logged in details, or site looks suspicious then I can chose private. 
Or if I want to open link where I want site to detect my logged in status and id, I can open in normal tab.

**Comment by kbrosnan** [comment]
You can do this by long pressing on a link.

**Comment by 97pratyush** [comment]
I mean opening links outside of firefox browser. 
There's no option when we open any website or link from other app.

**Comment by 97pratyush** [comment]
> You can do this by long pressing on a link.

I mean opening links outside of firefox browser. 
There's no option when we open any website or link from other app.

**Comment by s-ankur** [comment]
@97pratyush go to settings-> private browsing and you have the option to open links in a private tab

**Comment by 97pratyush** [comment]
> @97pratyush go to settings-> private browsing and you have the option to open links in a private tab

I know there's an option but it's permanent. Either it's always Private tab or always normal. 
This issue was created, just to get an option for every link individually while opening it.

**Comment by FrostedIce339** [comment]
@97pratyush do you think something like this would solve the use cases you are presenting: https://github.com/mozilla-mobile/fenix/issues/10581

**Comment by 97pratyush** [comment]
> @97pratyush do you think something like this would solve the use cases you are presenting: https://github.com/mozilla-mobile/fenix/issues/10581

Yes, this would be great and ideal implementation. I hope devs implement it.
