### ISSUE TITLE
FNX2-18859 ⁃ Intermittent UI test failure - verifyAddonsCanBeUninstalled

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13220]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8312248502354333158/executions/bs.a9d1bfdc83706379/testcases/1/test-cases

Failed 2/2 tries.
### Stacktrace:
`androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'at least 100 percent of the view's area is displayed to the user.' doesn't match the selected view.
Expected: at least 100 percent of the view's area is displayed to the user.
Got: "SwitchMaterial{id=2131362261, res-name=enable_switch, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@2f136e8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Enabled, input-type=0, ime-target=false, has-links=false, is-checked=true}"`
### Build:

**Comment by AaronMT** [comment]
Kadeem wrote a possible fix, let's re-open within 30 days if it occurs again https://github.com/mozilla-mobile/fenix/commit/60526dffd8173f3d5a8f014c42297e53594d662c

**Comment by ekager** [comment]
I'm seeing this failing intermittently, we may need to ignore again. See https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8726499571443121154 off https://github.com/mozilla-mobile/fenix/pull/14492

**Comment by sv-ohorvath** [comment]
Going to close this bug again as it was fixed and there is https://github.com/mozilla-mobile/fenix/issues/13829 for the new error.
