### ISSUE TITLE
[Bug] Native crash while toggling Reader Mode 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13225]
## Steps to reproduce
Open https://www.whatsapp.com/features/
Cllick reader mode

### Expected behavior
Reader mode opens, if it wasn't available then the icon did not appear
### Actual behavior
The page reloads, if you do it a few times it can crash(native crash)
### Device information

* Android device: Asus Zenfone (LineageOS)
* Fenix version: Nightly

**Comment by kbrosnan** [comment]
Are you able to provide a crash id? https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by s-ankur** [comment]
https://crash-stats.mozilla.org/report/index/78fe5c92-d598-41c1-abcf-142bc0200803

**Comment by ekager** [comment]
Hm that's not a very helpful dump unfortunately. I saw this native crash while toggling reader mode yesterday so it's likely the same one https://bugzilla.mozilla.org/show_bug.cgi?id=1635722

**Comment by s-ankur** [comment]
@ekager, going through my crash dump, I see that it shows "no extensions installed" but I do have UBO installed. Is this normal?

**Comment by ekager** [comment]
Not sure @s-ankur  :/ 

Managed to catch it on video it's fairly intermittent for me but if I toggle reader mode a few times I see it pretty consistently. 
![ezgif com-video-to-gif(6)](https://user-images.githubusercontent.com/25442310/89310132-4ca09780-d642-11ea-973b-10c874a0ee92.gif)

**Comment by s-ankur** [comment]
The issue with https://www.whatsapp.com/features/ is seperate from the crash it seems. Clicking on reader mode on that page just reloads it. Should it be moved to a seperate issue?

**Comment by test491** [comment]
not reproducible on

https://www.nytimes.com/2021/02/23/nyregion/daniel-prude-rochester-police.html?action=click&module=Spotlight&pgtype=Homepage
https://www.whatsapp.com/features/

on 86.1.1
normal and private browsing modes
webxtension: https everywhere: 2021.1.27
with etp settings:
standard
strict
custom: cookies: all cookies, cryptominers, fingerprinters, redirect trackers, tracking contents: all tabs (all checked)

on Nightly 210220 05:00 (Build #2015794345) AC: 73.0.20210218143118, 525591d8b GV: 87.0a1-20210218092411 AS: 70.0.0
normal and private browsing modes

with following settings:
(1) in about:config : dom.security.https_only_mode: true
etp settings:
standard
strict
custom: cookies: all cookies, cryptominers, fingerprinters, redirect trackers, tracking contents: all tabs (all checked)

(2) in about:config : dom.security.https_only_mode: false
etp settings:
standard
strict
custom: cookies: all cookies, cryptominers, fingerprinters, redirect trackers, tracking contents: all tabs (all checked)

android 9, Galaxy J7 Nxt

**Comment by kbrosnan** [comment]
Looks like bz-1635722 resolved this. There are no crashes with the signature on recent builds.
