### ISSUE TITLE
[Bug] No haptic feedback when long pressing forward button

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#13235]
## Steps to reproduce
Go to a couple websites in the same tab.
Go back one page so the forward button is enabled.
Long press the forward button to show tab history.

### Expected behavior
Small vibration to indicate long press has happened.

### Actual behavior
No vibration. Long pressing the refresh button does have the vibration.

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly 8/3

**Comment by cadeyrn** [comment]
Please only implement with an option to disable it. This (and every other) feature would be unusable to me if there is a haptic feedback that cannot be disabled.

**Comment by person808** [comment]
Could you elaborate on why? We need it here to be consistent since the default Android behavior is to have haptic feedback for long presses.

**Comment by cadeyrn** [comment]
@person808 I understand that it's a useful feedback for some people, but not for everyone. For me it's annoying especially since I use my smartphone very often in very silent environments and a vibration can be heard by others. I definitively do not want this.

**Comment by FrostedIce339** [comment]
> @person808 I understand that it's a useful feedback for some people, but not for everyone. For me it's annoying especially since I use my smartphone very often in very silent environments and a vibration can be heard by others, especially when the smartphone is on the table when I use it (I don't always hold my smartphone in my hand). I definitively do not want this.
> 
> But I noticed that there is an Android setting and it was already disabled on my device so it should be good enough.

As you realised; Android handles these vibration settings independently so if Firefox acted different then it'd create inconsistencies and users who expect it would become confused as to why Firefox is not vibrating when long pressed.


I'd remove my reactions on your comment but I'm not able to click on the reaction buttons on your comment anymore. Perhaps there's bug on GitHub Android app. I'll try to report it to them (GitHub's Android app has so many bugs and missing features, lol).

I'd have left a comment but I thought it'll clutter the issue's comment space. I'll try add a comment next time.

**Comment by Diana-Rus** [comment]
Hi, verified this on Nightly 8/5 with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8) with the following results:
- When android "Touch vibration" is enabled for android device - there is a small vibration.
- When android "Touch vibration" is disabled for android device - there is no vibration.

Google Pixel 3XL (Android 9) -  The option is "Touch vibration" - is present in android Settings/Sound/Advanced
Samsung Galaxy S9 (Android 8) - The option is named "Vibration feedback" - is present in android Settings/Sounds and vibration/System

@person808 - is the behavior mentioned above the intended one?

**I'll remove the qa:needed label until further information is provided.**

**Comment by person808** [comment]
Yup! Thank you!

**Comment by sv-ohorvath** [comment]
Verified as fixed on 80.0.0-beta6 on several devices:
Sony Xperia Z5 Premium (Android 7.1.1), Motorola Moto G6 (Android 8), OnePlus A3 (Android 6.0.1), Google Pixel 3a (Android 10) and Huawei Mate 20 Lite (Android 10)
