### ISSUE TITLE
Make error pages more thumb friendly

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#13246]
### What is the user problem or growth opportunity you want to see solved?
The button(s) in error pages are not easily accessible by thumb especially when on a large device.
Shifting the button towards the bottom would help a lot.

### How do you know that this problem exists today? Why is this important?
See screenshots from the "no internet connection" and SSL error pages:
<img src="https://user-images.githubusercontent.com/46764284/89270197-4c50ce00-d63b-11ea-923f-0772a3ca1cd4.png" width=200 />
<img src="https://user-images.githubusercontent.com/46764284/89270203-4fe45500-d63b-11ea-9643-d0f17ebb7f92.png" width=200 />

In comparison, in https://github.com/mozilla-mobile/fenix/issues/8215#issuecomment-611992360, this design was used, which is much easier to use (not sure why it isn't present in Fenix today?):
<img src="https://user-images.githubusercontent.com/40694158/78987545-fcec0c80-7b36-11ea-8d50-b99e8947c0db.png" width=200 />

### Who will benefit from it?
People receiving error pages, especially on large/long devices.

**Comment by liuche** [comment]
This was working as intended #5892
