### ISSUE TITLE
FNX-14423 ⁃ [Feature:China]Add local safebrowsing providers for China build

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#13242]
### What is the user problem or growth opportunity you want to see solved?
In China we need some different safebrowsing providers.
In fennec we modified the safebrowsing & urlclassifier related preferences to reach the goal.
This is the _about:url-classifier_ page in fennec, **_mozcn_** is the provider we add.
![Screenshot_20200803_105515_cn mozilla firefox](https://user-images.githubusercontent.com/33616048/89245696-f597c400-d63b-11ea-8da4-5701e4f2ebfb.jpg)

**Comment by lomomcat** [comment]
Sorry, you need to connect _**Mozilla Online Ltd.**_ if you need this.
如果您需要这个功能的话，建议您联系_**北京谋智火狐信息技术有限公司**_，他们会将Fenix浏览器中国特色化。

**Comment by kbrosnan** [comment]
This information is stored at the Gecko level. There is no Geckoview API to change safe browsing providers. Modifications to several source files in the Gecko code repository would be needed.

**Comment by kbrosnan** [comment]
Mozilla China uses the Google Safe Browsing bug 1498747 could be useful.
