### ISSUE TITLE
[Bug] Clear key DRM video can't be played with eme enabled

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#13249]
## Prerequisites
- Have media.eme.enabled set to true in about:config
- Have media.eme.require-app-approval - true in about:config
### Steps to reproduce
1. Go to https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3016
2. From DRM drop down choose Clear Key DRM option.
3. Tap on "OK".
### Expected behavior
Video is available for playing.
### Actual behavior
Video is not available for playing
### Device information

* Android device: Samsung Galaxy S9 (Android) and Google Pixel 3 XL (Android 9)
* GV build: 81.0a1, build ID: 20200804022706

Note:
- This video can be played in Chrome
- Issue is related to feature request #1175 
**Screen**
![Screenshot_20200804-112841_Firefox Beta](https://user-images.githubusercontent.com/49859863/89271884-02211a00-d646-11ea-8881-908ab169570b.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4333)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813907

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
