### ISSUE TITLE
[Bug] System share sheet shown when using context menu to share link

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#13248]
## Steps to reproduce
1. Open any site
2. Long-press on any link on the site.
3. Click "Share link".

### Expected behavior
The internal Firefox share sheet pops up, providing me with recently used apps and other Firefox devices to share with.

### Actual behavior
The Android system share sheet is used, see GIF below:
<img src="https://user-images.githubusercontent.com/46764284/89271153-9a1a0600-d63c-11ea-848f-553e03da130a.gif" width=350 />

**Comment by s-ankur** [comment]
Duplicate of  (sort of) #7438

**Comment by amkcpu** [comment]
You're right, thanks for the heads up
