### ISSUE TITLE
[Bug] Search widget creates a backstack when returning to homescreen multiple times

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#13245]
## Steps to reproduce
(I did the following steps in private mode, and with the keyboard OpenBoard. Might not matter, though.)
1. Click on the Widget to get to the new tab-screen. The keyboard will pop up.
2. Press your phone's home-key
3. Repeat steps 1&2 as often as you want (**x times**)
4. Click on the widget a last time.
5. press your phone's back-button. The keyboard will close, then open back up.
6. You may now repeat Step 5 **x times**

### Expected 
Don't keep creating new-tab-screens for each widget-click.

### Device information

* Android device: LG G6
* Fenix version: 200803

**Comment by jsilverstreak** [comment]
This appears fixed in Nightly 201213 17:01. I assume #16953.
