### ISSUE TITLE
FNX2-18872 ⁃ [Bug]Can't interact for a couple of seconds  after dismissing the Tabs Tray while in multi-select mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#13251]
## Steps to reproduce
1. Open a tab
2. Open the Tabs Tray
3. Long tap the previously opened tab
4. Dismiss the Tabs Tray by swiping down
5. Swipe down the website

### Expected behavior
The user can properly interact with the website after dismissing the Tabs Tray 

### Actual behavior
The user can't interact for a couple of seconds  after dismissing the Tabs Tray 

### Device information

* Android device: Google Pixel 3a (Android 10)
* Fenix version: 
Debug build from master 8/4
Nightly 200803 

### Notes
► Video
![20200804-113836](https://user-images.githubusercontent.com/51314259/89273928-e4a17f80-d648-11ea-8eff-1b8ecc9542e0.gif)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200819 Build #2015758835 from 8/19 with Pixel 2 (Android 9).
I will remove the qa:needed label and close this issue.
