### ISSUE TITLE
FNX-14431 ⁃ [Bug] "Help" button opens Firefox for Android Beta Support in Fenix Nightly

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13250]
## Steps to reproduce
go to home screen and click help

### Expected behavior
opens the help page for firefox nightly. if this is the same as the one for firefox beta then it should say so
### Actual behavior
opens Firefox for Android Beta Support

### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by liuche** [comment]
I'll bring this to the SUMO team, thanks!

**Comment by liuche** [comment]
We should update this link to be of the format:

`https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/mobile-help`

with the substitutions done by that file

**Comment by liuche** [comment]
Should be fixed on the SUMO side now!
