### ISSUE TITLE
FNX-14437 ⁃ [Bug] Opening uBlock Origin settings from outside of addons sub-menu toggles private mode

### ISSUE THREAD

**Issue by BlitW0** [mozilla-mobile/fenix#13256]
## Steps to reproduce
- From home page on normal tab, open 3-dot menu.
- Open Settings > Advanced section > Add-ons OR Open Add-ons.
- Go to uBlock Origin > Settings.

### Expected behavior
Settings open in a normal tab.

### Actual behavior
Settings open in a private tab, while browsing in normal mode.

### Device information
* Android device: Moto G5 Plus; Android 8.1
* Fenix version: Nightly 200804 09:33 (Build #22170942)

**Comment by Amejia481** [comment]
cc @psymoon

**Comment by psymoon** [comment]
This appears to be happening only when you have no tabs open. Investigating...

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200819 Build #2015758835 from 8/19 with Motorola Moto G6 (Android 8).
I will remove the qa:needed label and close this issue.
