### ISSUE TITLE
[Docs][Outdated Readme] Project build from command line fails as `assembleGeckoBetaDebug` gradle task is not found in `app` module

### ISSUE THREAD

**Issue by imGurpreetSK** [mozilla-mobile/fenix#13252]
## Steps to reproduce
Run `./gradlew clean app:assembleGeckoBetaDebug`

### Expected behavior
Project should successfully build.

### Actual behavior
Project build fails with error `Task 'assembleGeckoBetaDebug' not found in project ':app'`

### Device information
NA

### Others
Originally reported [here](https://matrix.to/#/!nJKrjaXIWSApOYfJfv:mozilla.org/$tu_JoEcOXVcu5sr5RY8W-uvjwvcFD3jFl7_nJx8HS7M?via=mozilla.org&via=matrix.org&via=synapse.leprette.fr).

* Android device: NA
* Fenix version: NA

**Comment by liuche** [comment]
Updated in README in another PR
