### ISSUE TITLE
Can't see if tab is on top of the list

### ISSUE THREAD

**Issue by Nico04** [mozilla-mobile/fenix#13264]
When comparing Firefox Preview (v5.1.1) and Firefox beta (lastest), it seems that one obvious behavious can/should be easely fixed.
On Firefox Preview (v5.1.1), if a non-top tab is selected when arriving on tabs list, you can see a small portion of the previous tab, indicating there's more above. On Firefox beta you can't see if it's to top of the list or not.

Related to #13109

**Comment by ekager** [comment]
cc @topotropic we are scrolling to the selected tab, but I guess we could show a scroll bar or tiny offset to more easily tell the user they are not at the top of the list?

**Comment by Nico04** [comment]
> 
> 
> cc @topotropic we are scrolling to the selected tab, but I guess we could show a scroll bar or tiny offset to more easily tell the user they are not at the top of the list?

I would prefer a tiny offset, it's more immediate ;)

**Comment by topotropic** [comment]
tiny offset sounds useful to indicate that it's not the top of the list, thanks for the feedback!

**Comment by madb1lly** [comment]
Hi all,
Obviously this is not a new issue but I just thought to report it and was pleased someone else has.

Personally I would prefer that, if the current tab is not the top of the list, then it should be in the centre of the list (or as close as can be permitted considering that those above and below many not be sufficient to allow the current tab to be in the middle).

Leaving only a tiny offset would give the feeling that the tabs below are more important than those above, but this may not be the case.

Cheers 🙂

**Comment by amkcpu** [comment]
The solution merged in #14372 shows the _entire_ tab one above the currently selected tab.
This is not exactly what @topotropic ![specified above](https://github.com/mozilla-mobile/fenix/issues/13264#issuecomment-670168369):
> **tiny offset** sounds useful to indicate that it's not the top of the list, thanks for the feedback!

A tiny offset has the advantage that it hints at more coming above, while not distracting from the currently selected tab, i. e. I am able to very quickly identify the currently selected tab.
Showing the whole tab above the currently selected one is 1) more distracting and 2) does not tell me if there are tabs further above.

**Comment by cadeyrn** [comment]
I wouldn't say it's "more distracting" but you're definitively right with the other part: Showing an entire tab above the currently selected tab does really not solve the problem that was explained in this issue. A tiny offset is an inituitive way to indicate that there is more.

**Comment by gabrielluong** [comment]
Yes, you are both right. We chose this current solution as shortcut given that we wanted a fix in time for the deadline of our next Firefox release. I have filed #14619 to implement the proper solution. Thanks!

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200907 06:01 (Build #2015762483) GV 82.0a1 from 9/7 with Pixel 2 (Android 9), Nexus 5 (Android 6.0.1).
The entire tab one above the currently selected tab is displayed.

The tiny offset solution will be verified in the new opened issue: https://github.com/mozilla-mobile/fenix/issues/14619.

I will close this issue and remove the qa:needed label.
