### ISSUE TITLE
[BUG] New tab button is too large

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#13277]
## Steps to reproduce
1. Open tabs tray.
2. Switch between regular and private mode.

## Expected behaviour
The new tab button should have the same height as the "new private" button and as the floating action buttons used in other Android apps (e.g. WhatsApp, Gmail, Outlook).
Also, the transistion between the buttons should only change horizontally.

## Actual behavior
Currently, the new tab button is higher than the same button for a new private tab. It is also generally larger than the floating action buttons in most other Android apps (WhatsApp or Gmail, for example).
This leads to a weird transistion when switching between the regular and private modes (see GIF below). This transistion should be horizontal only, but due to the height difference has a horizontal _and_ vertical component.

<img src="https://user-images.githubusercontent.com/46764284/89345155-455fa500-d6a7-11ea-9de4-2836e5a105bf.gif" width=350 />
(For the small grey rectangle visible on the new tab button, see #11180).

**Comment by person808** [comment]
I think this is intentional because the material design guidelines say that the extended FAB should shorter than the regular FAB.

https://material.io/components/buttons-floating-action-button#specs

**Comment by liuche** [comment]
Closing this since this matches the FAB Material Design guidelines.
