### ISSUE TITLE
Local file system browsing

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#1327]
### Why/User Benefit/User Problem
I want to be able to view HTML documents and other supported files on my phone's local storage (including removable SD cards and such-like) in the browser, like I can with Firefox today.

### What / Requirements
Unfortunately Google plans to make this rather difficult, and if we want to provide this feature on Android Q onwards we'd likely need

1. [content://-URI support in GeckoView](https://bugzilla.mozilla.org/show_bug.cgi?id=1516467)
1. Either hoping [that](https://issuetracker.google.com/issues/129629193) [these](https://issuetracker.google.com/issues/128641684) [objections](https://issuetracker.google.com/issues/128591846) succeed, so that real file system access remains possible if the user grants it at least to specific directories, or else GeckoView also needs the ability for accessing files and browsing directories through the Storage Access Framework (which e.g. isn't really written with native code in mind as far as I've heard).
1. Pestering Google about the [fundamental unsuitability of working with content://-URIs received from other apps](https://issuetracker.google.com/issues/77406791) when the content in question _isn't_ a single, atomic file, for which HTML documents are a perfect example.

### Acceptance Criteria (how do I know when I’m done?)
1. I can browse through the local file system and open supported files.
1. Other apps can launch Intents for files on the local storage that the browser supports and those files are then successfully loaded (in the case of HTML documents that means _including_ all subresources like images, style sheets, etc. and with working local relative links).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4357)

**Comment by buttercookie42** [comment]
> Unfortunately Google plans to make this rather difficult

There's a feedback form now available: https://docs.google.com/forms/d/e/1FAIpQLSdhhKVRKp1a7lj5XsQJ6rN9HyJ8d9WGPcdGwmTibWfhPUmj_g/viewform?vc=0&c=0&w=1

**Comment by AgentOak** [comment]
Sorry to add noise but for everyone coming across this issue looking for a workaround *now*: See reply in thread https://github.com/mozilla-mobile/fenix/issues/7546#issuecomment-627091018

**Comment by ohhai** [comment]
> Sorry to add noise but for everyone coming across this issue looking for a workaround _now_: See reply in thread [#7546 (comment)](https://github.com/mozilla-mobile/fenix/issues/7546#issuecomment-627091018)

"file:///" scheme seems disabled now :(

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809954

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
