### ISSUE TITLE
Intermittent UI test failure - HistoryTest.deleteAllHistoryTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#13281]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7353513557504975881/executions/bs.8128b79fb322531a/testcases/1/test-cases

### Stacktrace:

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE) `

### Waiting for:
 https://github.com/mozilla-mobile/fenix/issues/13383

**Comment by sv-ohorvath** [comment]
This failed because of the Strict mode policy violation pop-up which is being discussed here: https://github.com/mozilla-mobile/fenix/issues/11364.

**Comment by sv-ohorvath** [comment]
Failed again today 1/2 tries: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6759362972106451104/executions/bs.cc5f22bd52a60fb9/test-cases
I suspect it is a bug, the "No history here" text is not displayed every time. I'll open a bug.

**Comment by sv-ohorvath** [comment]
Still just flaky: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6814125792852425606/executions/bs.15888ff00022cba9/testcases/1/test-cases

**Comment by rpappalax** [comment]
Failed on 1 job on Tues., 9/1 
2/2 failed attempts
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5904482774751161600/executions/bs.a3909711e8a50045/test-cases

**Comment by isabelrios** [comment]
Failed 1/2 on 1 job, PR on Friday 10/2:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8457148418512075119/executions/bs.369c9a11e841c043/test-cases

**Comment by isabelrios** [comment]
Failied 1/2, commit on master on Friday 10/16:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5705673849435257539/executions/bs.4a93d1abc411f9c2/test-cases

**Comment by sv-ohorvath** [comment]
Failed 2/2: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5583391206192370605/executions/bs.d4c44e9d6c782d7/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Failed 1/2, on 11/3: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8183125839606248686/executions/bs.b4bb03f3d34b587e/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Failed 1/2 on 11/17: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7458380383054094210/executions/bs.942e6525dd200b3a/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Failed 1/2 times, on 12/2: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5589484802496802555/executions/bs.d9dc58ad34da1222/videos

**Comment by sv-ohorvath** [comment]
Failed 1/2 tries on 12/3: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5009231834692286965/executions/bs.a116232d4bc4142a/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky, failed 1/2 on 12/7: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5291967431887756400/executions/bs.eb1b4c92c98479d8/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 12/16: androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE)

**Comment by sv-ohorvath** [comment]
Failed 1/2 on 12/24: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9038153808390561985/executions/bs.a306e3394c836c0e/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 1/6/21: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7547227528362730194/executions/bs.e501a62f8a365653/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on master 1/14: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6371030455636822920/executions/bs.f077a8fba05b2f/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on master 1/22: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5777427388447764438/executions/bs.9f9f81a031274c76/testcases/1/test-cases

**Comment by AndiAJ** [comment]
Flaky on Master 2/02: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4871964125409747604/executions/bs.7877a9544d77af6c/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on Master on 2/02: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5821080885419952544/executions/bs.8632643abb7be791/testcases/1/test-cases

**Comment by AndiAJ** [comment]
Master 2/4 :
► Flaky 1x
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8823678139481686714/executions/bs.686e5a66cf1c1ab6/testcases/1/test-cases)

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE)`

**Comment by AndiAJ** [comment]
• Master  2/7 :
► Flaky 1x deleteAllHistoryTest
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6182547823119148860/executions/bs.aacccc0c32c90ca/testcases/1/test-cases)

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE)`

**Comment by sv-ohorvath** [comment]
Tried some things, can only fix this test by removing the failing verification, which would only avoid the issue. I think it can't be really fixed until https://github.com/mozilla-mobile/fenix/issues/13383 is fixed. I suggest to leave it as is as long as it's only flaky and to modify it if it becomes a blocking issue.

**Comment by sv-ohorvath** [comment]
Flaky (1/2 runs) on Master 2/10: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5030037958764977684/executions/bs.9a8f01f56725d54d/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on Master 2/15: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4706123290329451553/executions/bs.ebc759608186ea60/testcases/1/test-cases

**Comment by AndiAJ** [comment]
• Master 2/19: 
► Flaxy 1x deleteAllHistoryTest

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8669391120700452995/executions/bs.c31e21c3633ceacc/test-cases

**Comment by AndiAJ** [comment]
• Master 3/5:
► Flaxy 1x deleteAllHistoryTest

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE)`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6229392000824760503/executions/bs.15bd4f4b016efb43/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
• Master 3/8:
► Flaxy 1x deleteAllHistoryTest

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE)`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5541553156286068922/executions/bs.4c3dc3699cb38597/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
• Master 3/9:
► Flaxy 1x deleteAllHistoryTest

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE)`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7996702575831454793/executions/bs.b7bb985dae849dea/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on master 3/23: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7219997275091789666/executions/bs.a79066457301a2b2/testcases/1/test-cases

**Comment by AndiAJ** [comment]
• Debug 3/26: 
► Flaxy 1x deleteAllHistoryTest

```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/history_empty_view and view has effective visibility=VISIBLE)
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f14033f
fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND
vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
```

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7563533669572556240/executions/bs.f791cac5b44c0ccb/testcases/1/errors)

**Comment by sv-ohorvath** [comment]
Flaky on Debug 3/31: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8531912845201174554/executions/bs.7670dc593a42203e/testcases/1/test-cases

**Comment by AndiAJ** [comment]
•  Flaxy 1x  Debug 4/8: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8166307696499143222/executions/bs.7d2de71abbbfd6c4/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
• Flaky 1x Debug 4/10: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7436178715895886046/executions/bs.cd6158d2c056913b/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on 4/13: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5960173271253713072/executions/bs.a82d650a180f6f41/testcases/1/test-cases

**Comment by AndiAJ** [comment]
Flaky 1x Debug 4/16 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6871596766857266689/executions/bs.adfc822a176a143c/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x Debug 4/17 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5152810414850411646/executions/bs.514e9e80147746c4/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x Debug 4/22 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9084081166088597921/executions/bs.6f79e7be255ac26b/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x Debug 4/22 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5429210777033355835/executions/bs.9264082401b7d6a6/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on Debug 4/30: https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6629453811408406480/executions/bs.d8878f30e4798ad8/testcases/1/test-cases

**Comment by AndiAJ** [comment]
Flaky on Debug 5/14: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6053769932488287248/executions/bs.a2fe8e0eca98294c/testcases/1/test-cases)

**Comment by AaronMT** [comment]
Again in https://treeherder.mozilla.org/jobs?repo=fenix&selectedTaskRun=XErgQkI7SzeJjYDHlfoBrg.0

**Comment by sv-ohorvath** [comment]
Flaky on Master 5/24: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6529605158155291888/executions/bs.2d7842663d6487c9/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on Master 5/26: [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5748462084877474217/executions/bs.8fb6085813b906f7/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky on Master 6/7: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6981996672117960546/executions/bs.36d4d1c967aad399/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on Master 7/7: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5098951729389576372/executions/bs.c541ff1b5291906e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on Master 7/7: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6473657414635150017/executions/bs.c1ce94c0dc1355e3/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky on Master 7/22: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8584526051787019671/executions/bs.a3622248a1ed26b9/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on Master 7/27: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6375602098548877461/executions/bs.6635e94de9ae2270/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on Master 8/4: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8311718610962270279/executions/bs.94cadecba5d03238/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on Main 8/5: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7612233705456253002/executions/bs.173a5c8fe838e22a/testcases/1/test-cases) 

Flaky 1x on Main 8/6: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7333463789825505757/executions/bs.4c5efabe1a987290/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky on 8/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5454214598113655263/executions/bs.a5a40b1307f1f4e9/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8446835553952213819/executions/bs.5019b3332a379445/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6595413787761645710/executions/bs.a764cb424fe8f294/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5088302620388895070/executions/bs.d6ab81c9d089f36b/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8730521464010095834/executions/bs.463c247e79bbf57b/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4797747542705610153/executions/bs.ea6a3c41f205b84a/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on 10/1, [logs](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5926686066228573426/executions/bs.fc5f5eca6cf80d27/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/18 on Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8888926731784709871/executions/bs.f0b5bf49c92c31d6/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 1/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6081648719166993607/executions/bs.8fe872f1fed95db8/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5817278207306149773/executions/bs.35095e168aff7f63/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6719637760181211773/executions/bs.c818c8c5e01f0840/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/1 Main [Firebaselink](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5929971119007102697/executions/bs.c4dce0e62c3661e5/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a month.
