### ISSUE TITLE
FNX2-18886 ⁃ [Bug] Slight flicker when selecting a bookmark

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#13280]
## Steps to reproduce
Go to bookmarks screen and select a bookmark by tapping on the favicon.

### Expected behavior
Smooth animation of check mark being shown and overflow menu being hidden.

### Actual behavior
In addition to the behavior described above, the title and url flicker even though they don't change.

<img src="https://user-images.githubusercontent.com/6396431/89349843-bda47700-d663-11ea-906b-2ba99cf341ce.gif" width=300 />

This is caused by the recyclerview change animation. We probably need to be smarter and use payloads instead of rebinding the whole viewholder when selecting a bookmark.

### Device information

* Android device: Pixel 2 XL (more noticeable on the emulator for me)
* Fenix version: 8/3 nightly

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/19 with Samsung Galaxy Note 10 (Android 10), LG G7 FIT (Android 8).
