### ISSUE TITLE
[Bug]flash when opening app from recent screen or turning on the screen

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#13299]
## Steps to reproduce
   Str1-
1. Start fenix and open a page.
2. Go to recent app screen on phone.
3. Open the app agian and observe.
      Or
Str 2-
Open a page and switch off the phone and switch on the phone and observe.
### Expected behavior
The app doesn't flashes and app comes on screen smoothly.
### Actual behavior
Opening app from recent screen causes a white flicker.
### Device information

* Android device: 8.0.0
* Fenix version: latest nightly

**Comment by jakefleming156** [comment]
Duplicate of [#6313 ](https://github.com/mozilla-mobile/fenix/issues/6313)
