### ISSUE TITLE
[Bug] Keyboard some times does not appear

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#13295]
## Steps to reproduce
this happens some times, not always and it started a few days ago

open any page with a text field for example https://www.reddit.com/r/firefox/comments/i3uxuf/have_you_guys_noticed_an_influx_of_chromeonly/
click the comment

### Expected behavior
see the keyboard

### Actual behavior
no keyboard visible
![Screenshot_20200805-103427_Firefox_Nightly](https://user-images.githubusercontent.com/922368/89385088-c2bb0200-d707-11ea-97fb-d019bdf84630.png)

workaround: kill the browser process and restart it
### Device information

* Android device: one plus 5t
* Fenix version: nightly

**Comment by s-ankur** [comment]
This happens to me sometime on GitHub itself

**Comment by ekager** [comment]
@s-ankur do you also think this started a few days ago?

**Comment by s-ankur** [comment]
@ekager its been happening for some time now

**Comment by andreicristianpetcu** [comment]
Ohh.... I'm using Hacker's keyboard, not the default one.

**Comment by miDeb** [comment]
Not sure if this is the exact same bug, but I recently filed a bug with STR https://github.com/mozilla-mobile/fenix/issues/12982.

**Comment by s-ankur** [comment]
@miDeb yes, that is probably the bug I was facing

**Comment by sflorean** [comment]
Based on the comment above I will close this as a dupe of #12982. @s-ankur feel free to reopen if it is not the same.
