### ISSUE TITLE
FNX2-18894 ⁃ [Bug] "Save to collection" button animates down from top of tab tray before tabs are shown

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#13293]
## Steps to reproduce

1. Open enough tabs to fill tab tray
2. tap tab tray switcher button

### Expected behavior

Tabs appear without distracting animation. 

### Actual behavior

"Save to collection" button animates down as soon as the tab tray appears and before any tabs appear. This is distracting and makes the tab tray feel slow - and is completely unnecessary as it isn't even easy to see what is animating down. The physics of the button also seems very strange. 

See video: [signal-2020-08-05-012509.zip](https://github.com/mozilla-mobile/fenix/files/5026322/signal-2020-08-05-012509.zip)

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by cadeyrn** [comment]
> This is distracting and makes the tab tray feel slow

I totally agree. It's really bad for the perceived performance.

**Comment by vishalnandagopal** [comment]
Also there are 3 ways to save collections now. Right from the tab tray. Why so many? Feels forced. 4 ways in total, 3 just from the tab tray.


The one in the three button menu is sufficient. Tabs tray is lagging a lot.

**Comment by Diana-Rus** [comment]
Reproducible with Samsung Galaxy S9 (Android 8) and Google pixel 3XL (Android 9) on latest Nightly 8/5.

**Comment by ekager** [comment]
This will be taken care of by https://github.com/mozilla-mobile/fenix/issues/11185

**Comment by jonalmeida** [comment]
> This will be taken care of by #11185

I was too quick to try and fix all the things in one issue. Separating out the perf work in individual issues works in this case.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/19 with Google Pixel 3 (Android 11).
