### ISSUE TITLE
[Bug] Tabs are displayed multiple times in recent history pop-up when navigating on some pages

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#13296]
## Steps to reproduce
1. Launch Fenix and in the same tab visit twitter.com, facebook.com, google.com, emag.ro, diply.com;
2. Long tap the device back button and tap on emag.ro, tap on links remaining on the same site;
3. Long tap the device back button and observe the recent history pop-up;
### Expected behavior
The links opened at step 2 are displayed once.
### Actual behavior
The links opened at step 2 are displayed twice ore more times.
![20200805_114225](https://user-images.githubusercontent.com/48799384/89391742-45948a80-d711-11ea-8466-a556a65ef514.gif)

### Device information

* Android device: Motorola Moto G6 (Android 8)
* Fenix version: Nightly 200804 GV 81.0a1 from 8/4,

**Comment by person808** [comment]
@ebalazs-sv Are there any other sites/order of sites that this happens on? We get the history list from AC so I'm not seeing what we can do on the fenix side.

**Comment by ebalazs-sv** [comment]
@person808 I tested this on 200806 GV 81.0a1 from 8/6 with Pixel 2 (Android 9) and the steps to reproduce this issue are:
1. Launch Fenix and in the same tab visit twitter.com, facebook.com, google.com, emag.ro, diply.com;
2. Long tap the device back button;
3. Tap on emag.ro from the recent history pop up;
4. Long tap the device back button;
5. Observe the tabs in the recent history pop up;

After steps 1, diply.com must be the last tab available in the recent history pop up and after step 3, the active tab in the pop up must be emag.ro.
**The issue is that diply.com is replaced by emag.ro in the pop up list, so that is why 2 tabs from emag.ro can be seen in the list.** Also, the active tab is where diply.com used to be, and not the second tab from the list.
Please let me know if there are other details that might be helpful.

**Comment by person808** [comment]
@ebalazs-sv Thank you! It looks like we see duplicate emag.ro entries whenever that page is loaded. I was able to go to that site directly and see it. This looks like a GeckoView bug since AC and Fenix don't manipulate the history list at all (we just display whatever GeckoView gives us).

**Comment by person808** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1657967 for now.

**Comment by Diana-Rus** [comment]
Hello, reproducible on Firefox Preview Beta 81.1.0-beta.1 with Google Pixel 3XL (Android 9).
