### ISSUE TITLE
Missing these features comparing regular Firefox

### ISSUE THREAD

**Issue by Balachandarsmr** [mozilla-mobile/fenix#13291]
Please add these features in future
1. download manager
2. Save page as pdf
3. Print page
4. View page source code 
Thanks.

**Comment by cadeyrn** [comment]
Please open one isse per feature request otherwise it's not possible to set labels for individual feature requests. Also use the search feature. There are already issues for each of your feature requests.

**Comment by s-ankur** [comment]
by download manager i think they mean #4417

**Comment by kbrosnan** [comment]
Please do not report more than one item per issue. These all have duplicate requests
