### ISSUE TITLE
[Bug] Comboboxes look strange

### ISSUE THREAD

**Issue by szaimen** [mozilla-mobile/fenix#13290]
## Steps to reproduce
1. Open a combobox (aka select tag)
2. See strange looking combobox (too much space at the bottom

### Expected behavior
No additional space at the bottom

### Actual behavior
Too much space at the bottom

### Device information

* Android device: Samsung Galaxy S10e
* Fenix version: 79.1.0-beta.1

### See the screenshot:
![Screenshot_20200805-024415_Firefox Beta](https://user-images.githubusercontent.com/42591237/89359427-199fe780-d6c6-11ea-95a8-bd9d9c3a8063.png)

**Comment by Dunexus** [comment]
Related https://github.com/mozilla-mobile/android-components/issues/4902

**Comment by szaimen** [comment]
@jakefleming156  Why was this issue closed? It is only related but not the same like what is requested here: mozilla-mobile/android-components#4902
