### ISSUE TITLE
FNX2-18897 ⁃ [Bug] Tab can be added to collection in private mode through long tapping.

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#13298]
## Prerequisites:
- Make a clear data of the browser.
- Add a couple of tabs in normal browsing.
### Steps to reproduce
1. In browser tap on tabs tray.
2. Long tap on a tab.
3. Tap back on device button.
4. Tap on the private mode.
5. Add a couple of tabs in private mode.(more than one)
6. Than on tab tray long tap the second tab.
### Expected behavior
Nothing happens
### Actual behavior
The tab from private mode is selected.
### Device information

* Android device: Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 8/5, Beta 80.0.0-beta.2

**Note:**
- You can add to collection in private mode, after triggering it in normal mode.
- I can't reproduce the issue constantly.

**Gif**
![20200805-182555](https://user-images.githubusercontent.com/49859863/89431805-113cc080-d749-11ea-8c81-42d7563dc64f.gif)

**Comment by ekager** [comment]
I can reproduce after entering multiselect in normal browsing, leaving it, going to private tabs, and long pressing

**Comment by sflorean** [comment]
I wasn't able to reproduce this issue following the steps provided on Nightly 8/12.
Devices: Samsung Galaxy Note 10 (Android 10), Google Pixel 3 (Android 11).
