### ISSUE TITLE
Tabs drawer has too many animations - reduce to one

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#13297]
Tab drawer has several separate animations:- 
1. empty drawer animates up from bottom of screen
while
2. FAB animates up from bottom of screen
then
3. list of tabs drops down from top of drawer
while
4. "Save to collection" zooms down the screen

It's very very busy.

IMHO animations (3) and (4) are not necessary
- they make identifying a tab unnecessarily slow because I can't start hunting for a tab from the list until the animation cycle has completed (the list has dropped down)
- they are distracting bling:- Tab drawer going up! FAB going up! tabs going down! "Save to collection" going down! Zing, zing, pow.
- Personally I find the way "Save to collection" zooms down the screen every single time I open the tabs drawer intensely irritating :(
 
I'd prefer the tabs to already be "in the drawer" as it slides up from the bottom of the screen.  That way I can start looking for my tab as the drawer slides up and I don't have the distraction of "Save to collection" flying down the screen.

Thanks guys!

**Comment by s-ankur** [comment]
This issue was also raised [in this comment]( https://github.com/mozilla-mobile/fenix/issues/12856#issuecomment-665695310_) when the save to collection button was implemented.

**Comment by yoasif** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/13293

**Comment by liuche** [comment]
Yes, please follow along with the work happening in #13293 for improvements to the animations
