### ISSUE TITLE
FNX-4960 ⁃ Create the browser menu

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#133]
Parent: #116
UX issue: #172 

Related A-C issues:

* [x] https://github.com/mozilla-mobile/android-components/issues/1545
* [x] https://github.com/mozilla-mobile/android-components/issues/1544

**Comment by sblatz** [comment]
<img width="359" alt="screen shot 2019-01-11 at 1 14 26 pm" src="https://user-images.githubusercontent.com/4400286/51051808-ddb4a700-15a2-11e9-85ab-da127489277d.png">

**Comment by pocmo** [comment]
Related A-C issues:
* https://github.com/mozilla-mobile/android-components/issues/1545
* https://github.com/mozilla-mobile/android-components/issues/1544

**Comment by bbinto** [comment]
@ekager to finish Friday / end of sprint
