### ISSUE TITLE
FNX-14484 ⁃ [Bug] The download fails if the Download folder isn't available with a 'null download failed' dialogue in the notification tray

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#13303]
Related comment: https://github.com/mozilla-mobile/fenix/issues/12297#issuecomment-668420236

## Steps to reproduce

* Delete the 'Download' folder in your phone's internal storage.

* Go to: `https://www.apkmirror.com/`

* Try downloading an APK from the website

* The download fails with a 'null download failed' dialogue appearing in Android's notification tray that cannot be dismissed. A Force stop of the Firefox browser is necessary to make the notification go away.

### Expected behavior
 
The notification can be dismissed from the notification tray

### Actual behavior

The notification cannot be dismissed from the notification tray

### Device information

* Android device: Mi A2
* Fenix version: 79.0.2
* Android version: Android 10

**Comment by s-ankur** [comment]
is this the same as #13134

**Comment by FrostedIce339** [comment]
> is this the same as #13134 ?

It's about being able to dismiss the notification dialogue from the notification tray. I created it according to the developer's request: https://github.com/mozilla-mobile/fenix/issues/12297#issuecomment-668586992.

**Comment by FrostedIce339** [comment]
@Amejia481 @jakefleming156 The issue has been closed. Has this been fixed?

**Comment by Amejia481** [comment]
Sorry, it looks it was closed by mistake.

**Comment by jakefleming156** [comment]
My bad. I thought this was a duplicate.

**Comment by Amejia481** [comment]
No problem :)

**Comment by kbrosnan** [comment]
Duplicate #5829
