### ISSUE TITLE
FNX-14483 ⁃ [Github] Pin important and frequently requested issues to the repository

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13302]
### What is the user problem or growth opportunity you want to see solved?
Github allows us to pin issues to the top so that they are easily visible(See https://docs.github.com/en/github/managing-your-work-on-github/pinning-an-issue-to-your-repository). The fenix team should pin important and frequently requested features as this will help users know that these issues are being worked on and they can also upvote the issues which they find to be useful easily. Yes Github search exists but it isnt really all that useful and sometimes its difficult to know the exact name of that feature to search it. It is upto the team to decide what counts as important but generally features like #4417 can be included
### How do you know that this problem exists today? Why is this important?
This will both prevent needless issues like #13291 and satisfy the users requesting them. 
### Who will benefit from it?
All users of firefox who want to give their feedback via github

**Comment by Scripterr** [comment]
Yes, they should pin important issue/bugs if they there is critical bug /crash in software to reduce the duplicates.
But I'm not sure about adding features in pinned panel as there will be many common features which users want and I believe that you can add limited issues to pinned panel. The duplicate issue is that sometimes users don't search before filing issues so they need to be reminded to search before filling.
There are also feature of invisible messages in issue template where they can add the instructions to file bugs / features and they don't appear when submitted, this is used in [signal github](https://github.com/signalapp/Signal-Android/issues/new) repository, from there they can redirect users to use search first before the file issues and if they want can also add any other instructions they want. They can also take some inspiration from signal issue template.

**Comment by Scripterr** [comment]
Sorry didn't see this point😅

> Yes Github search exists but it isnt really all that useful and sometimes its difficult to know the exact name of that feature to search it.

Yes this is a valid issue that sometimes search functionality is not useful where user is searching with different keywords. This can be solved by creating a *Mega Issue* where all the important/common features are included and then pin that issue .

**Comment by liuche** [comment]
Thanks, that's a great idea. We probably won't include a ton of issues, but are there some that you stand out to you that we could consider?

**Comment by s-ankur** [comment]
Looking at google play reviews, I can say that fennec parity issues like these should be included:
#4417 Download Manager
#470 Tab Queue 
#11308 Allow sideloading addons on Nightly that use supported WebExtension APIs
And possibly one of
#219 Save Page Offline / #3709 [Spike] Save as PDF option / #10217 [Feature request] In browser printing 
Also, consider renaming #10240 to "Optionally Disable dynamic toolbar" or creating a specific issue for that request

**Comment by s-ankur** [comment]
And also, all the specific addon requests can be collected in a mega post which can be pinned (like #10044, #12393 and so forth)

**Comment by hwinnemoe** [comment]
This could also be included as it seems to quite import for some users:
https://github.com/mozilla-mobile/fenix/issues/7865 about:config support in Release/Production

**Comment by opusforlife2** [comment]
As @Scripterr says, a meta-issue, which contains multiple related issues inside it in the form of a bullet list, is probably the best way to go about it. A pinned issue called "Fennec Parity" could contain all the most requested parity features (on github, or on Play Store) like @s-ankur suggests, for example. Another could be "Browser parity", as people frequently request highly popular features from other browsers.

Focus on Fennec parity will likely stave off some of the negativity around the Fenix stable rollout, as well.

**Comment by s-ankur** [comment]
As fenix is rolled out to more users, this will be crucial to avoid spam like #14090, #14099 and so on

**Comment by Poopooracoocoo** [comment]
It's also worth adding some text to the issue template. Take a look at other repos' issue templates.

**Comment by opusforlife2** [comment]
Further activity has occurred.
