### ISSUE TITLE
FNX-14481 ⁃ [Bug][RTL] The "Share" label is overlapping the X icon when sharing a collection

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/fenix#13300]
## Steps to reproduce

1. Switch Fenix's language to Hebrew / Arabic / Persian
2. Save a collection
3. Click the share icon for the collection

### Expected behavior

The "Share" label is overlapping the X icon.

### Actual behavior

It should be on the right side of the screen,

### Device information

* Android device: Samsung Galaxy S10e
* Fenix version: Nightly, latest version

Screenshot:
![image](https://user-images.githubusercontent.com/18016656/89408762-8dbfa700-d729-11ea-9a34-0184aa5c625b.png)

**Comment by Diana-Rus** [comment]
Hi, i can reproduce the issue with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 9) on Nightly 8/5.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20200921-095810000](https://user-images.githubusercontent.com/51314259/93739770-bd4f4380-fbf1-11ea-8373-6d18dd77c11f.png)
