### ISSUE TITLE
FNX3-15488 ⁃ [Bug] history view: data URIs truncated too late

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1330]
### Steps to reproduce
1. open a data URI (example image: https://dopiaza.org/tools/datauri/examples/index.php)
1. open history

### Expected behavior
no overlap

### Actual behavior
![screenshot1](https://user-images.githubusercontent.com/1100614/55434353-b5cc5280-5597-11e9-9cd8-89fe06c7ba43.png)

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision bd81e722393381458e3c1421773ee402121e9dc7

**Comment by ekager** [comment]
This was also fixed by #1371
