### ISSUE TITLE
Tab drawer opening: use constant height when opening regardless of number of tabs

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#13310]
The current tab drawer implementation has two opening "heights". If <=3 tabs are open it's about 60% of screen height. >3 tabs it's about 90% of screen height. 

This means items move about on screen depending on how many tabs are open.  For example 
- the location of a given tab can change (eg, my BBC News tab is in the middle of the screen. Oh, wait, I opened another tab:- BBC News has moved to nearly at the top)
- the tab counter, private tab button & 3 dot menu change position (they can be near the middle of the screen or nearly at the top)
- the "Save to collection" button can be anywhere or even off the bottom of the screen

I dislike this. 

Suggestions
- always open the tabs drawer at the same height, say the taller of the two current values. Allow me to drag down to reach the tab counter, private tab button, 3 dot menu button
- turn the Save to collection button into something at a fixed location on the screen

I think #13297 is related, overall I find the tabs drawer much too busy with animations and stuff zooming about all over the screen. It sure is pretty, but opening the tabs drawer feels like a new and exciting adventure, who knows what wonders I'll see!!!! Which I think is not ideal :) :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4415)

**Comment by issue-dispenser** [comment]
Personally I would like an option to open it in fullscreen similar to Fennec to fit as much tabs on screen as reasonably possible.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812917

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
