### ISSUE TITLE
FNX-14496 ⁃ [RTL] Text for Hebrew and Persian onboarding screen is not correctly aligned

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#13315]
**Note:** these screenshots are used by **marketing** team I believe, so want to make sure that's on their radar as well
## Steps to reproduce
Choose Hebrew or Persian language on device.
Navigate to onboarding string (see screenshots below)

### Expected behavior
Text is right aligned since both Hebrew and Persian are right-to-left languages.

Note Arabic is **_not_** affected. Maybe there is an issue with the BiDi algorithm that fails because of the latin word ("Firefox") at the beginning of both Hebrew and Persian (vs Arabic doesn't).

### Actual behavior
Text is left aligned

### Device/build:
was surfaced through screenshots testing

![HomeScreenRobot_after-onboarding-pm_1596102865989](https://user-images.githubusercontent.com/399020/89444413-84711300-d706-11ea-98fc-7cf9a2f55cc1.png)
![HomeScreenRobot_after-onboarding-pm_1596104189313](https://user-images.githubusercontent.com/399020/89444430-889d3080-d706-11ea-850b-0d170c60d48c.png)

**Comment by ItielMaN** [comment]
In recent Fenix builds I've worked around this for Hebrew by appending an RLM character to that string.

**Comment by Delphine** [comment]
I think we've started shipping in RTL countries - this is an issue I'm concerned might affect other areas of the app, so would like to call that out (also, since this onboarding, so not a great experience)

**Comment by liuche** [comment]
cc @mei-loo to take a look at the marketing resources as well.

We should prioritize this for migration onboarding, @Mugurell I'm going to add this to your team's staging column as well.

**Comment by mcarare** [comment]
@Delphine It seems to me that there is also the problem of text direction, considering that the text should not only be align ed to the right, but also, it should start from the right. So, the "Firefox"  text should be at the right of the screen, not at the left.
This is the screenshot with the fix for _Farsi_:

<img src = https://user-images.githubusercontent.com/48995920/90623945-e27e1a00-e21f-11ea-8559-6dce870b9cc2.jpg  width = 50%>

**Comment by softvision-miralobontiu** [comment]
Hi all,
Verified as fixed on the latest Nightly build from 8/26 with:
- Samsung Galaxy Tab S6 (Android 9):
![Samsung](https://user-images.githubusercontent.com/40694158/91299374-2b971680-e7aa-11ea-8561-906a8f5d0a66.png)

- and Sony Xperia Z5 Premium (Android 7.1.1):
![Sony](https://user-images.githubusercontent.com/40694158/91299383-2f2a9d80-e7aa-11ea-8775-92c6d9466a73.png)
