### ISSUE TITLE
[Bug] Hide all individual 3-dot icons during multi-select for Bookmarks

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#13318]
## Steps to reproduce

1. Go to Bookmarks
2. Long-press on a bookmark to enter multi-select mode

### Expected behavior
All 3-dot icons for individual bookmarks and folders should be hidden

### Actual behavior
Only the 3-dot icon for the selected bookmark is hidden

### Device information

* Android device: 10
* Fenix version: Nightly 200804 09:33

**Comment by person808** [comment]
Oops looks like I messed up my commit message, but a fix did land for this so  it should be tested by QA.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200810 from 8/10`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200810-111441](https://user-images.githubusercontent.com/51314259/89763469-4192af00-dafb-11ea-9eb3-e7ae4f7dd82c.gif)
