### ISSUE TITLE
[Telemetry] add new data type for addon details

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#13322]
Related to https://github.com/mozilla-mobile/fenix/issues/6174, #8920, #12202

Requested data type from Glean: https://bugzilla.mozilla.org/show_bug.cgi?id=1658329
**This must be approved by the Glean team before this can be implemented**

## Description & Product Manager / Data Scientist User Story

We are currently receiving `has_enabled_addons` and `has_installed_addons` in the Metrics ping, and a string list of events for `enabled_addons` and `installed_addons`:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/43795363/89461908-412c9980-d732-11ea-8d83-b4f22865f111.png">

### New data form
1. The Metrics ping should include a `struct` for each addon with: 
  * `enabled: Boolean`, 
  * `name: String`
  * `version: String`

2. Event ping should be a `struct_list` that includes the list of enabled and installed details.

## What questions will you answer with this data?
See #8920 and #12202

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4426)

**Comment by eliserichards** [comment]
Removing "won't-fix". This issue may still be valid.

**Comment by willdurand** [comment]
🆙
