### ISSUE TITLE
FNX-4963 ⁃ [Bug] History: Redirects should be taken into account

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1332]
### Steps to reproduce
1. enter "google.de" in the address bar
1. open history

### Expected behavior
only one entry in history.

### Actual behavior
four :warning: entries in history, about:blank (that's #1318) and one for every redirect.

![Screenshot](https://user-images.githubusercontent.com/1100614/55434975-2758d080-5599-11e9-9f5c-d1c91e4ed081.png)UNITO-UNDERSCORE!20190402-224343!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision bd81e722393381458e3c1421773ee402121e9dc7

**Comment by grigoryk** [comment]
The places API we're using doesn't do any `visit_type` filtering. At the very least, we'd want to filter out redirects here, and doing that in Rust makes most sense. We'd need an API change, I filed an appservices issue to discuss this: https://github.com/mozilla/application-services/issues/920

**Comment by grigoryk** [comment]
As a stop-gap measure until the API is in place, let's do the filtering at the application level.

**Comment by grigoryk** [comment]
App-level filtering done in https://github.com/mozilla-mobile/fenix/pull/1395

**Comment by cadeyrn** [comment]
@grigoryk: It's not fixed by #1395, now it looks like this:

![Screenshot_20190405-082937](https://user-images.githubusercontent.com/1100614/55607761-49ab4380-577d-11e9-990d-6d1e99d225a1.png)

**Comment by cadeyrn** [comment]
This issue should be reopened because it was closed under the assumption that #1395 will fix this issue. But #1395 didn't fix the issue, it only introduced an additional history bug, see last comment and the new issue #1459.
