### ISSUE TITLE
Scrolling is not working on Chrome OS using trackpad.

### ISSUE THREAD

**Issue by edumorlom** [mozilla-mobile/fenix#13326]
## Steps to reproduce
If I go to any site, and use my trackpad to scroll. Firefox doesn't allow it. It only works if I use my touchscreen.
It starts highlighting the entire page instead of scrolling.

### Expected behavior
It should just scroll down as expected.
### Actual behavior
It starts highlighting the page instead of scrolling. 
### Device information
It is a Chromebook/Pixelbook.

* Android device: Chrome OS on Pixelbook
* Fenix version: Nightly 200805 06:08 (Build #22180857)
AC: 53.0.20200804130112, 789a73eb2
GV: 81.0a1-20200803094100
AS: 61.0.10

![image](https://user-images.githubusercontent.com/11444894/89465255-cb2f2f00-d73f-11ea-8baf-d310ebde86a5.png)

**Comment by kbrosnan** [comment]
Duplicate #3708
