### ISSUE TITLE
[Bug] History->Multi-Select->Three Dot menu->Open in new tab opens up the tab tray, breaks UI afterwards

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13321]
## Steps to reproduce
go to History->Multi-Select->Three Dot menu->Open in new tab
### Expected behavior
It opens the multiple tabs in the background
### Actual behavior
It opens up the tab tray, cancelling that messes up the UI 
### Device information

* Android device: Asus Zenfone
* Fenix version: Latest Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200806-014910_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/89459928-1c164600-d787-11ea-85aa-94c567c7c4ed.png)
The top bar disappears

**Comment by s-ankur** [comment]
Due to [this](https://github.com/mozilla-mobile/fenix/blob/6492773fc790004415c613a9212e13755951f46c/app/src/main/java/org/mozilla/fenix/library/LibraryPageFragment.kt#L39) probably

**Comment by nigelh747** [comment]
This is another case of the new version of Firefox for Android not being fit for purpose.

**Comment by sv-ohorvath** [comment]
Still reproducing on RC 82.1.0.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201218-125952](https://user-images.githubusercontent.com/51314259/102607610-3dbe0b80-4131-11eb-98ab-0ce7a4ee619e.gif)
