### ISSUE TITLE
Website favorite icon in tabs tray

### ISSUE THREAD

**Issue by motazalnuweiri** [mozilla-mobile/fenix#13339]
I would like to suggest adding website favorite icon in tabs tray

![Firefox Website favorite icon](https://user-images.githubusercontent.com/4532392/89526760-e8700600-d7f0-11ea-8d75-a696e0345ce3.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4449)

**Comment by cadeyrn** [comment]
That's really too much in my opinion. Why do I need a favicon when there is already a website thumbnail? In your example screenshot it's in no case useful.

**Comment by motazalnuweiri** [comment]
@cadeyrn Sometimes you can't identify what the website from it's thumbnail and if you open a lot of tabs the favorite icon will make it easy to identify it

**Comment by amkcpu** [comment]
This sounds really useful to me, especially when trying to identify one site with many tabs open.
The only possible issue I see is performance-related: Drawing a large amount of favicons at the same time could be CPU-intensive.

**Comment by clientenq** [comment]
> @cadeyrn Sometimes you can't identify what the website from it's thumbnail and if you open a lot of tabs the favorite icon will make it easy to identify it

The URL of the resource is shown for this reason.

I can see a favicon can help. Maybe as an option to only show favicon instead of page screenshot?

**Comment by willfs84** [comment]
Grid-style tabs have favicons, so should List-style. But I don't think that mockup is good, the favicon should be right beside the page title (because of familiarity. The favicon is almost always shown next to the page title)

**Comment by jackyzy823** [comment]
I made two kind of display way for your reference.

The first way: display before title , https://github.com/jackyzy823/fenix/tree/tab-listview-favicon.
Pros:  
> the favicon should be right beside the page title (because of familiarity. The favicon is almost always shown next to the page title)

Cons: 
1)  not so elegant when multi-line title. 
2) make title ellipsized more  

![Screenshot_2022-05-05-01-49-38-638](https://user-images.githubusercontent.com/2900871/166859103-289e844b-cdad-4b09-9a36-d0fb7ebfda22.jpeg)


The second way ,display before url https://github.com/jackyzy823/fenix/tree/tab-listview-favicon-v2
Pros:
more elegant
Cons:
I personally think no.

![Screenshot_2022-05-05-11-11-25-819](https://user-images.githubusercontent.com/2900871/166859176-28f8cec3-33ef-4d0f-982f-c5b70a06924c.jpeg)


I personally prefer the second way.


I think favicon is a **need** in whatever grid view or list view.  with only thumbnail , i can not easily distinguish sites from sites in a situation that i have tons of tabs..

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812916

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
