### ISSUE TITLE
FNX-14511 ⁃ Remove feature flag for swipe to switch tabs

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#13330]
Looks like bug reports for this have slowed down so lets consider removing the feature flag. There are a couple of thumbnail bugs that are waiting for GeckoView/AC work. We also never got a performance review before it got merged (cc @mcomella). The gesture implementation does wrap the whole browser fragment in a FrameLayout which could have performance impact. So barring any really bad bugs popping up, it looks like all we need is:

- [x] Get the performance team to see if there is a significant perf impact https://github.com/mozilla-mobile/fenix/issues/13411
- [x] Remove the feature flag

**Comment by person808** [comment]
forgot to mention there are a couple of thumbnail bugs (https://github.com/mozilla-mobile/fenix/issues/12873 and https://github.com/mozilla-mobile/fenix/issues/12859) but I don't think they are blockers for this.

**Comment by person808** [comment]
One more bug that occurs in multi-window mode: https://github.com/mozilla-mobile/fenix/issues/13405. Will try to figure out a fix next week. I've already tracked down the likely cause

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/13411 to track doing a performance review.

@person808 Can you link us to the PR(s) that implemented this functionality?

**Comment by person808** [comment]
@mcomella its https://github.com/mozilla-mobile/fenix/pull/12174

**Comment by sraturi** [comment]
** Performance Test on s7**

Seems like on average it takes an extra 10 ms to inflate the [swiping layout](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#172) compared to the regular one  (took an average of 10 runs). 

There were no strict mode violations. Looking into the code, I didn't see any performance issues. 

Tested the scrolling on the webpage, seems to work as intended (no difference between swiping layout vs regular `browser_fragment` layout).  

@mcomella  seems good on my end. 

Sample profile of swipe gesture
https://share.firefox.dev/2Y1NrZO

**Comment by person808** [comment]
@mcomella @sraturi Could you leave a comment and remove the do not land label from #13849 when the perf team feels this is ready?

**Comment by mcomella** [comment]
> Seems like on average it takes an extra 10 ms to inflate the swiping layout compared to the regular one (took an average of 10 runs).

@sraturi When does this inflation happen? i.e. does it impact startup?

**Comment by sraturi** [comment]
@mcomella  The inflation is inside BaseBrowserFragment when a view is [created](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#172). It would not affect the MAIN startup since we load to HomeFragment. But Id assumes it is affecting VIEW startup loading a URL.

**Comment by mcomella** [comment]
CC @MarcLeclair we may have a 10ms VIEW regression.

I'm going to give my perf r+ because we're trying to holistically improve startup so hopefully when we try to optimize the UI, we can find wins. @MarcLeclair What do you think?

I'm guessing the 10ms regression is because the addition of TabPreview's layout... I wonder if we should try lazily inflating it?

**Comment by person808** [comment]
Woo! Remove the feature flag and opened https://github.com/mozilla-mobile/fenix/issues/13907 for lazy loading TabPreview.
