### ISSUE TITLE
FNX-14521 ⁃ [Bug] when toolbar is hiding the header content jumps

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#13340]
## Steps to reproduce

1. settings -> Customize -> Toolbar (top) **important**
2. Go to https://www.interia.pl/
3. Slowly scroll

### Expected behavior
Smooth scroll.

### Actual behavior
The scroll is starting, a space is being created at the top of the banner in between the toolbar and the header.
Then suddenly jump to catch up with the toolbar which disappeared.

A profile doesn't give any specific details.
https://share.firefox.dev/3kkm2Mc
This is happening around 2.1s

I wonder if it's because the top of the viewport is not being tracked as the bottom position of the toolbar. @hiikezoe

### Device information

* Android device: Android 10, Pixel 2
* Fenix version: Firefox Nightly 200730(🦎 80.0a1-20200727095125) 
Reproduced in 81 too.

https://github.com/webcompat/web-bugs/issues/56044

**Comment by liuche** [comment]
Actually, I just went through the issues with amoya and so I'm throwing this on here - there are certainly workarounds (like scrolling around again) but there have been a couple of issues filed so checking to make sure this isn't a recent regression.

**Comment by amedyne** [comment]
Tested this on Firefox Nightly and I think this is no longer a problem.

Nightly 200907 06:01 (Build #2015762483)
AC: 58.0.20200904130229
GV: 82.01a-20200902095359

**Comment by kbrosnan** [comment]
Agreed I see an improvement with the top toolbar scrolling and the website header in Nightly 82.0a1 vs Release 80.
