### ISSUE TITLE
[Bug] Pressing back to close keyboard also closes URL bar

### ISSUE THREAD

**Issue by LinAGKar** [mozilla-mobile/fenix#13343]
## Steps to reproduce
1. Open new tab
2. Click URL bar
3. Press back

### Expected behavior
Keyboard is closed. URL bar remains.

### Actual behavior
URL bar is closed.

### Device information

* Android device: 9
* Fenix version: 79.0.2

**Comment by amkcpu** [comment]
Actually, I much prefer the current behavior. When I tap to close the keyboard, I almost always want to exit the URL bar too. If I just want more space to see more of the search results, I can swipe up/down on the results screen.
The behavior you describe was present in Fennec and it always annoyed me having to tap back twice to exit that screen.

**Comment by liuche** [comment]
Isn't this part of the intended behavior @topotropic ? Going to close.
