### ISSUE TITLE
FNX-14532 ⁃ [Bug] Webpages take a lot of time to load when uBlock Origin is enabled

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#13351]
## Steps to reproduce

* Install uBlock Origin with having default filter lists enabled (you can even enable some other filters lists if you want, it doesn't matter) .

* Go to any webpage for example wikipedia.org and try browse it by going through different articles but the problem reproduces with almost all of the websites I have browsed. For example; it reproduces on Twitter, GitHub, ect.

* Webpages take a lot of time, sometimes more than 5 to 8 seconds while with uBO disabled they load almost quickly (in less than a second or two). Sometimes they also get stuck forever.

* Going back and forward in the same webpage that I have already visited also takes just that much amount of time; It takes just as much time as loading a new webpage.

Point to be noted: Sometimes it does become faster, but it is very rarely the case.

### Expected behavior

While I do understand that there would be some overhead in loading webpages when content blockers are being used but it takes so much time to load the webpages and in already visited webpages; going back and forward also takes a lot of time.

Website should load somewhat faster and not take several seconds to load. Going back and forward is also affected.

### Actual behavior
Websites take a lot of time to load while uBO is enabled.

### Device information

* Android device: Mi A2
* Fenix version: 79.0.2
* Android version: Android 10

*uBO: uBlock Origin.

Further information: 

loading webpages and going back and forth between them;

* On [Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser) with uBO enabled (with almost all of the filters) it takes most of the time less than 2 seconds to load but never more than that.

* Brave browser with its Shields enabled loads webpages almost instantly.

* Vivaldi with its adblocker enable also loads webpages instantly

* With Firefox browser it takes almost 8 seconds to load the websites with uBO enabled. Without uBO it takes less than 2 seconds to load it and sometimes it loads the pages almost instantly.

**Comment by yoasif** [comment]
@FrostedIce339 can you grab profiles with and without uBlock Origin enabled? https://profiler.firefox.com/docs/#/./guide-remote-profiling

**Comment by Furax-31** [comment]
Same problem... A5 2017 Android 9. All versions Firefox (stable, bêta, Nightly)

**Comment by FrostedIce339** [comment]
Further investigation;


I tried reinstalling the browser and the issue were gone for a while but the long loading times were back after a day or so. I tried reducing the filter set list in uBO but that also didn't seem to work.

**Comment by Neutrino9** [comment]
@yoasif I can reproduce the issue but my device is not the same as OP, it is Motorola One Power (an Android One) device and it has Android OS Android 10. 

* https://share.firefox.dev/3aK2gWi --> uBO enabled.
* https://share.firefox.dev/3aErIwl --> uBO disabled.

I have never done Profiling so I don't know if I have done it right. I will take another Profile if you say so.

Thanks.

**Comment by mcomella** [comment]
Dupe #16473 – we've already investigated this heavily. There's a known issue for start up time that we can't do anything about – it's on ublock to fix it. Fennec was faster because fennec didn't block on add-ons being loaded before loading the first page which is undesirable behavior.
