### ISSUE TITLE
Don't open in app when URL is entered

### ISSUE THREAD

**Issue by hyperfekt** [mozilla-mobile/fenix#13353]
### What is the problem?
It is very hard to open a website in Firefox when the `Open links in apps` setting is enabled.

### Why is this important?
A user may want to open a website in Firefox as opposed to the app only sometimes, since websites often offer rarely needed functionality that's not available in the app.
Requiring the user to temporarily disable the setting induces a lot of friction.

### How could this be solved?
When the user enters a URL, the corresponding app should not be opened and the site loaded in Firefox instead.
The user can still visit the app using the `Open in app` menu item.

**Comment by FrostedIce339** [comment]
This seems to have been fixed in the Nightly with: https://github.com/mozilla-mobile/fenix/issues/12670

**Comment by FrostedIce339** [comment]
This seems to have been fixed in the Nightly with: #12670

**Comment by kbrosnan** [comment]
Closing as duplicate.

Please use [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to check if a feature is present in the development builds before opening issues.

**Comment by hyperfekt** [comment]
Thanks. Seems like auto-update for Nightly had gotten disabled somehow. I'll check the version explicitly next time.
