### ISSUE TITLE
[Bug] Update pre-push-recommended.sh

### ISSUE THREAD

**Issue by sysrqb** [mozilla-mobile/fenix#13363]
## Steps to reproduce

Run ` config/pre-push-recommended.sh`

### Expected behavior

Tests execute successfully.

### Actual behavior

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleGeckoBetaDebug' not found in root project 'fenix'.

```

Since https://github.com/mozilla-mobile/fenix/commit/c93a29f89a25bd0dc0f966deebcfa9e52a36aed5 

Is running ` config/pre-push-recommended.sh` still recommended or is there another subset of test you use?

### Device information

* Android device: ?
* Fenix version: master (9b1953ea86b19df70de173545e1ec81e1e9d6a80)

**Comment by person808** [comment]
Closing since the PR was merged :)
