### ISSUE TITLE
FNX-14554 ⁃ [Bug] duckduckgo disappeared after changing system language to Simplified Chinese.

### ISSUE THREAD

**Issue by h0cheung** [mozilla-mobile/fenix#13374]
## Steps to reproduce

Change language to Simplified Chinese in system settings. Then force close Fenix, and reopen it.

### Actual behavior

Duckduckgo disappeared from search engines.

### Device information

* Android device: Mi8 running a LineageOS based ROM.
* Fenix version: 79.1.0-beta.1

**Comment by liuche** [comment]
This sounds like a search/locales bug. will dupe to #13452
