### ISSUE TITLE
FNX-14556 ⁃ [Bug] pinch to zoom doesn't work on simultaneous touch but work with delayed touches

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#13376]
## Steps to reproduce
So this is an issue which has been reported in two cases with different sites using maps, but they don't seem to be using the same library.

Exhibit A 
https://github.com/webcompat/web-bugs/issues/56090

1. Go to https://leafletjs.com/
2. Pinch to zoom

Exhibit B
https://github.com/webcompat/web-bugs/issues/54615

1. Go to https://www.lightpollutionmap.info/
2. Pinch to zoom

In **both cases**, this is working only if you put one finger, wait, and put a second finger, then making the gesture.

### Device information

* Android device: 10, Pixel 2
* Fenix version: Firefox Preview 81

**Comment by jakefleming156** [comment]
Seems like a web compat bug but highlighting because it's a pinch to zoom bug.

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1663731

**Comment by amedyne** [comment]
From Bugzilla: 
  | Kartikaya Gupta (email:kats@mozilla.com) |  So far I'm not able to reproduce the problem.

**Comment by amedyne** [comment]
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1663731 Resolved 10/03/2020.
