### ISSUE TITLE
Allow disabling custom fonts

### ISSUE THREAD

**Issue by bkhl** [mozilla-mobile/fenix#13375]
### What is the user problem or growth opportunity you want to see solved?

Many web sites use bad fonts making reading them on a mobile device difficult and/or annoying.

### How do you know that this problem exists today? Why is this important?

I noticed today when getting the upgrade to the new Firefox for Android on my phone that the option to disable web fonts was missing.

I used this this setting before and it avoided the worst offenders, which is why I haven't reported this before.

However, what I would prefer is to be able to disable custom fonts altogether with a feature similar to disabling "Allow pages to choose their own fonts" in the desktop version of Firefox.

### Who will benefit from it?

People like me that get annoyed having to read things in the web designers font preference instead of my own.

I can see that it would also help accessibility for some people, although I'm not affected (unless I take my glasses off).

**Comment by FrostedIce339** [comment]
Seems like this has already been asked here: #12711,#10102.

**Comment by kbrosnan** [comment]
Closing as a duplicate.

**Comment by bkhl** [comment]
Those tickets are about disabing web fonts, this one is about disabling custom fonts altogether, as you can do in the desktop version of Firefox.
