### ISSUE TITLE
top-sites list like firefox for desktop

### ISSUE THREAD

**Issue by binocry** [mozilla-mobile/fenix#13382]
### What is the user problem or growth opportunity you want to see solved?
Gone are the automatically populated top-sites list, your browsing highlights (a confusing feature that randomly features pages you’ve recently visited), and recommended news articles suggested by Mozilla Pocket. In their stead, users get a list of favorites that they must manually curate and a new feature called collections.
### How do you know that this problem exists today? Why is this important?
I believe that the removal of top-sites from the new-tab page is a mistake. The new favorites list requires manual curation by the user before it becomes useful. The old top-sites feature lets you be lazy and manages to be useful without any effort on your part.
### Who will benefit from it?
All of user from firefox desktop, will feel user experience same to firefox for android

**Comment by cadeyrn** [comment]
> Gone are the automatically populated top-sites list

#10342

> your browsing highlights (a confusing feature that randomly features pages you’ve recently visited)

Since you're describing it as "confusing" I guess you're not proposing this…

> and recommended news articles suggested by Mozilla Pocket

#3788 and #6416

See also the official upgrade faq (https://support.mozilla.org/en-US/kb/firefox-android-upgrade-faqs):

> Note: Pocket stories will be available shortly after you upgrade.

**Comment by SlowNicoFish** [comment]
I actually love adding the sites myself and if the sites are going to be automatically added, can we at least make it an option and while we're at it, make those pages sync with my devices 🙂

**Comment by binocry** [comment]
> 
> 
> > Gone are the automatically populated top-sites list
> 
> #10342
> 
> > your browsing highlights (a confusing feature that randomly features pages you’ve recently visited)
> 
> Since you're describing it as "confusing" I guess you're not proposing this…
> 
> > and recommended news articles suggested by Mozilla Pocket
> 
> #3788 and #6416
> 
> See also the official upgrade faq (https://support.mozilla.org/en-US/kb/firefox-android-upgrade-faqs):
> 
> > Note: Pocket stories will be available shortly after you upgrade.
> 
> In the future please make only one feature request per issue otherwise it's not possible to prioritize specific features.

sorry i'm new to github not too familiar with it

**Comment by binocry** [comment]
> 
> 
> I actually love adding the sites myself and if the sites are going to be automatically added, can we at least make it an option and while we're at it, make those pages sync with my devices 🙂

someone has made an issue about it, maybe I will close this issue
