### ISSUE TITLE
Private browsing homescreen displayed when tapping "View" after creating a collection from tabs tray

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#13389]
## Steps to reproduce
1. Open 2-4 tabs in normal browsing.
2. Open private browsing.
3. Open tabs tray - normal browsing.
4. Create a collection.
5. Tap "View".

### Expected behavior
The collection created is displayed. 

### Actual behavior
Private browsing homescreen is displayed.

### Device information
* Android device: Xiaomi Mi Pad 2 (Android 5.1
* Fenix version: 80.0.0-beta.4, Nightly 8/7.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4505)

**Comment by AndiAJ** [comment]
**Still reproducible** on **`86.1.0 RC1`** using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Reproducible on 93.0.0-beta.1 using a OnePlus A3 (Android 6.0.1)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Beta 109.0b4 build.
Also reproducible on the latest Nightly 110.0a1 (2022-12-29).
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812745

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
