### ISSUE TITLE
Nightly CI build is not being updated

### ISSUE THREAD

**Issue by helloworld1** [mozilla-mobile/fenix#13395]
The wiki pointed to the nightly build download as https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest

However the APK is at least 19 days old and not updated since 7/22. The Google play version is much newer.

**Comment by cadeyrn** [comment]
The correct URL is https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest.

**Comment by helloworld1** [comment]
Thanks! The wiki seems to be orated outdated.

**Comment by kbrosnan** [comment]
Updated 

* https://github.com/mozilla-mobile/fenix/wiki
* https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration

If there are other places please let us know.
