### ISSUE TITLE
FNX-14572 ⁃ [Bug] URL of page at the top in Reader Mode should be a link to the original

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#13392]
## Steps to reproduce
Open a page in Reader Mode. Tap on the URL at the top.
### Expected behavior
This should be a tappable link to the original page. That's how it is in desktop Firefox.
### Actual behavior
The blue text is just that, text.

* Fenix version: Nightly 200801 06:06 (Build #22140616)

**Comment by hwinnemoe** [comment]
I can reproduce on Nightly 200807 06:01 (Build #2015756529).

@opusforlife2 Since you are still on an affected version of Nightly, can you please post your `about:memory` log in #9065. For this you need to open `about:memory`, tap _Measure_ and copy the log. That way we can narrow down your memory consumption issues you mentioned in the 13228, not linking to this to avoid more noise to that issue.

**Comment by opusforlife2** [comment]
Lol I _just_ updated to the latest Nightly as you asked in 13228 to test memory consumption. What I'll do is: perform a memory consumption test with this version (7 Aug), and then roll back to the 1 Aug build and test that for the same sites. (Aren't you glad I take full root backups? XD )

**Comment by hwinnemoe** [comment]
I think there is no need for that as it sounds like a lot of work: you can just try to reproduce these STR on your _current_ Nightly: https://github.com/mozilla-mobile/fenix/issues/11284#issuecomment-650122756 and look for the heap-unclassified memory. If you still see high memory consumption on the current Nightly, please open a new issue for this.

**Comment by opusforlife2** [comment]
Alright. Doing that now.

**Comment by opusforlife2** [comment]
@hwinnemoe Nope. Following your STR: Step 4 is ~8 MB (Main + Web) . Step 6 is ~ 19 MB. Step 9 goes back to ~8 MB.

**Comment by hwinnemoe** [comment]
That sounds fine then 😄 Can you please post this in #9065? I am going to hide/edit my comments here since there are really not related to this issue.

**Comment by liuche** [comment]
This will probably require a change in AC, but I think it might be straightforward?

**Comment by miDeb** [comment]
I'd like to fix this :)

**Comment by miDeb** [comment]
This should now work in the latest nightly, could you confirm that? (And close the issue)

**Comment by opusforlife2** [comment]
Awesome! Thanks a lot! Closing as fixed by https://github.com/mozilla-mobile/android-components/pull/8211.

**Comment by opusforlife2** [comment]
@miDeb When you tap on the link to go to the original page, there is a considerable duration for which the tab stays on "about:blank" in between. Have you not encountered this?

**Comment by miDeb** [comment]
I think see what you mean (but for me the duration is relatively short). This looks however like an issue with switching to reader mode (or from reader mode back) in general, as it looks like there's no difference in time spent on about:blank when
- switching to reader mode
- tapping on the link I added
- using the back button to leave reader mode
- or tapping on the icon in the toolbar to leave.

Do you see a difference there?

**Comment by opusforlife2** [comment]
Ah! Good point. Tapping the link, tapping the reader mode icon, and tapping back; all 3 have nearly the same about:blank duration for me.
