### ISSUE TITLE
blue page URL in the Reader Mode text doesn't show the full url

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#13397]
The full URL of the original page which is being viewed in Reader Mode is valuable; just the domain name is not.
- In Fenix, the domain name is just plain text. (#13392)
- In desktop Firefox, the domain name is still a link to the original page, but since it looks like just the domain name, users might be mistaken that it is a link to the root of the website unless they get curious or accidentally hover over it. In many cases, they might not realise that it is a link, at all.

In both Fenix and desktop Firefox, the full URL of the original page should be visible at the top, instead of just the domain name, so that it is more visible to users and they can choose to interact with it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4513)

**Comment by csadilek** [comment]
This is definitely intentional to declutter the page, same as in Desktop. I doubt we'd wanna display the potentially long original URL instead. You're right though that the link should work #13392.

**Comment by opusforlife2** [comment]
Fair point. Then what about shortening the URL to one line with ellipses?

**Comment by liuche** [comment]
We removed this in #7077 due to limited horizontal space in the urlbar. https/http is designated by the lock icon.

**Comment by opusforlife2** [comment]
Umm... @liuche, these are not the domains you're looking for. O_O

This issue is not about the address bar at all. It's about the domain name shown at the top of a page in Reader Mode in blue font.

**Comment by liuche** [comment]
oh my mistake, I'll update the issue title

**Comment by opusforlife2** [comment]
As I said above, what about ellipses to shorten it?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814172

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
