### ISSUE TITLE
FNX-14570 ⁃ [Bug] Reader view controls still displayed if we open an external link

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#13390]
## Steps to reproduce
1. Open a page and enter reader mode.
2. Open menu- appearance. 
3. Go to Gmail and open a link in Firefox.

### Expected behavior
The page is opened.

### Actual behavior
Reader view controls are displayed for the previous page opened. 
### Device information

* Android device: Samsung Galaxy Note 10(Android 10), Xiaomi Mi Pad 2 (Android 5.1), Samsung Galaxy Tab S3 (A8).
* Fenix version: 80.0.0-beta4, Nightly 8/7

**Comment by s-ankur** [comment]
Related #7591

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/8 with Google Pixel 3 (Android 11), Nokia 6 (Android 7.1.1).
