### ISSUE TITLE
FNX-14580 ⁃ Raptor WebExtension tests (speedometer, open blank page) are permafailing

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#13399]
From sparky:

> Hello! The raptor webextension tests have started currently failing and there have been no harness changes to cause this. It looks like it started perma-failing somewhere between July 31: https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&tier=1%2C2%2C3&searchStr=fenix&revision=161920b70ae464ae0157139327c2d2d7b0480275
> 
> And August 3rd: https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&tier=1%2C2%2C3&searchStr=fenix&revision=84b257d07031f657765a63f137f17b1f1c6587d7

Extra info:
> mcomella
sparky: I'm unfamiliar with the raptor webextension tests – what do they test?
sparky
One tests speedometer, another just opens a blank page. They are failing while trying to connect to the web-extension
mcomella
sparky: The web-extension is an extension designed specifically to run this type of testing?
sparky
mcomella: That's right it gathers the metrics information from the browser and send them to a control server.

**Comment by mcomella** [comment]
Initial thoughts:
- we recently removed `BrowserPerformanceTestActivity` and the `isRaptorEnabled` flag: https://github.com/mozilla-mobile/fenix/pull/13237
- there are StrictMode violations on start-up on some devices – the dialog could cause the test to fail: https://github.com/mozilla-mobile/fenix/issues/13368

**Comment by davehunt** [comment]
These are the power usage tests. You can see the outage clearly at https://health.graphics/power. We're not sheriffing these, and I'm unaware if anyone is tracking them. The plan is to migrate these to Browsertime, but it's relatively low priority. I'd be inclined to bump the priority rather than fix raptor-webext for Fenix, and live with the loss of datapoints in the meantime. @gmierz what do you think?

**Comment by davehunt** [comment]
I've created https://jira.mozilla.com/browse/FXP-1294 to track this.

**Comment by mcomella** [comment]
> I've created https://jira.mozilla.com/browse/FXP-1294 to track this.

I think we can close this as WONTFIX and defer until this browsertime migration.

@gmierz Feel free to undo. :)
