### ISSUE TITLE
Can't go back multiple pages

### ISSUE THREAD

**Issue by LinAGKar** [mozilla-mobile/fenix#13396]
On Fennec you could hold the back button (either in the browser or on the device) to get a list of the history of the tab, to go back multiple steps at once. However, this no longer works in Fenix. The back button in the browser is gone, and holding the back button on the device just goes back one step when you release it, instead of bringing up the list. This is especially a problem when you get to some redirection site, where clicking back just makes it redirect again.

**Comment by Dunexus** [comment]
See https://github.com/mozilla-mobile/fenix/issues/1048 and https://github.com/mozilla-mobile/fenix/issues/12926

**Comment by kbrosnan** [comment]
Duplicate #1048 

Please use [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to check if a feature is present in the.
