### ISSUE TITLE
[Bug] Viewing an image, zooming in, and swiping up displays white behind the hidden URL box

### ISSUE THREAD

**Issue by vaindil** [mozilla-mobile/fenix#13406]
## Steps to reproduce
1. Open an image by long-pressing and choosing "Open image in new tab".
2. Zoom into the image, then swipe upward (so the URL bar at the bottom of the app disappears).

### Expected behavior
The URL bar should be hidden and I should see the image behind it.

### Actual behavior
The URL bar is hidden but a white box is displayed behind it instead of the image. [Here's a video.](https://streamable.com/jn3ppf) This has been happening for several weeks now. I can only reproduce the behavior in nightly versions though, not stable.

### Device information

* Android device: Pixel 2 XL, Android 10
* Fenix version:

Nightly 200806 06:02 (Build #22190614)
AC: 53.0.20200804130112, 789a73eb2
GV: 81.0a1-20200803094100
AS: 61.0.10

**Comment by s-ankur** [comment]
Related to #11389

**Comment by liuche** [comment]
Yes, there are some outstanding bugs related to bottom dynamic toolbar, so I'm going to dupe this one to it - thank you for filing and including the video! #11389
