### ISSUE TITLE
[Bug] Access denied when trying to view unit test failure results

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#13404]
When clicking on "Unit Test Results" in the Github UI to see the results AND in the Taskcluster artifacts, we see access denied for  many resources aside from the `index.html`.

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>97ED96C9E4A014DE</RequestId>
<HostId>
X1BVn71kINqfRMTF7aiiw7TmhCBbfjyNIvJvJOC2VbDLNLBlGAjfyUFNjVYfuSLumo/kZtc+99M=
</HostId>
</Error>
```

Example link: https://firefox-ci-tc.services.mozilla.com/tasks/dk6jXf6ST5OjXtr0XKkGzg#artifacts

**Comment by jonalmeida** [comment]
cc @NotWoods for reference since I believe you had originally worked on this.

**Comment by NotWoods** [comment]
It seems that the URL changed, I'll send a PR soon to update it
