### ISSUE TITLE
FNX-14589 ⁃ LibrarySiteItemView unnecessarily nests ConstraintLayouts

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#13408]
LibrarySiteItemView extends ConstraintLayout and inflates `library_site_item.xml` inside of it. However, `library_site_item.xml` contains a ConstraintLayout in its top level, resulting in an unnecessary ConstraintLayout being inflated. This looks like a good candidate for using a [`<merge>`](https://developer.android.com/training/improving-layouts/reusing-layouts#Merge) tag in the xml.

**Comment by NotWoods** [comment]
Did not realize this creates two layouts, oops. We're planning to replace library_site_item.xml with a shared UI component (#8765) so the better solution may be to just delegate to that instead.
