### ISSUE TITLE
Reintroduce option to always display menu bar (disable auto-hiding of UI)

### ISSUE THREAD

**Issue by Imerion** [mozilla-mobile/fenix#13409]
### What is the user problem or growth opportunity you want to see solved?
Always having the menu bar visible to quickly allow navigation or access to browser functions without the need to keep doing random up/down movements would be desirable.

### How do you know that this problem exists today? Why is this important?
This function used to be included in the options menu but I can't seem to find it anymore in the 79+ series. Hiding important UI elements is a huge problem with modern UI design. There is no need to keep hiding things. Smartphone screens are very large today, and something that really isn't needed is more vertical space. Hiding this small menu bar makes no sense and makes efficient browsing impossible.

### Who will benefit from it?
Anyone who prefers to have the UI ready whenever needed and prefers a more efficient way to navigate and control their browser.

**Comment by cadeyrn** [comment]
Duplicate of #10240.

**Comment by Imerion** [comment]
Sorry. I tried to search around but the title of #10240 didn't indicate it was related. Closing now.
