### ISSUE TITLE
FNX-14586 ⁃ [Bug] Swipe tab switching works from the middle of the screen and not from the address bar when in split screen mode

### ISSUE THREAD

**Issue by kawaiiDango** [mozilla-mobile/fenix#13405]
## Steps to reproduce
Enter split screen mode. Try swipe to switch tabs.
Here's a video of what happens https://imgur.com/a/CmdesZF
### Expected behavior
Swipe should work on the address bar only
### Actual behavior
Swipe works at the middle of the screen
### Device information

* Android device: OnePlus 6, Android 10
* Fenix version: Nightly 200807 06:01 (Build #2015756531)

**Comment by person808** [comment]
Interesting. Looks like the area you can swipe in is about the size of the toolbar, just not where it should be. Can you confirm @kawaiiDango?

**Comment by kawaiiDango** [comment]
Yes that's true

**Comment by person808** [comment]
Ok. So we use the [`getRectWithViewLocation`](https://github.com/mozilla-mobile/fenix/blob/57c795563700be06f818a4b1b9c452a2c72b63b2/app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt#L305) method to find where the toolbar is. This method returns coordinate relative to the window, which is smaller in multi-window mode. However, the swipe detection looks at the raw coordinates relative to the whole screen so we end up with a mismatch. 

I know we use the raw coordinates for swipe detection so phones with notches work properly so my first thought is we should look into getting the toolbar location relative to the whole screen.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200819 (Build #2015758835).
### Device used:
- OnePlus 6T (Android 9)
