### ISSUE TITLE
Provide "Kill Infinite Scroll" addon

### ISSUE THREAD

**Issue by yump** [mozilla-mobile/fenix#13401]
### What is the user problem or growth opportunity you want to see solved?

It is impossible to browse most Tumblr blogs without [this extension](https://addons.mozilla.org/en-US/firefox/addon/kill-infinite-scroll/), which previously worked on Fennec. 

The specific nature of the problem is that most Tumblr blogs use a mobile theme with so-called "infinite" scrolling, because it's the default.  "Infinite" pages lose their position if you click a link and use the back button.  They also lose their position when evicted under memory pressure, which means "open in new tab" isn't even safe.  Neither is switching apps, or in the worst cases even turning off the screen.

Also, if you scroll too far, the device may hang and have to be force-rebooted because it runs out of memory.

### How do you know that this problem exists today? Why is this important?

I know it exists because I can't click links or switch tabs or apps without losing my place, and my device has hung and had to be force-rebooted because it ran out of memory.  For an example of a page that exhibits the problem, see [collapsedsquid.tumblr.com](https://collapsedsquid.tumblr.com/)  For one that does not, see [shieldfoss.tumblr.com](https://shieldfoss.tumblr.com/).

Providing this *specific* addon is important because of Fenix's ongoing failure to support addons in general.

Also, the problem will never be fixed on Tumblr's end, because they have a material interest in making the mobile website awful, to push people toward using the (probably malicious) app.

### Who will benefit from it?

All users who use Tumblr and avoid installing first party apps from social media companies, because they are a security and privacy nightmare (c.f. TikTok, Linkedin, etc.).

**Comment by kbrosnan** [comment]
We are not keeping open requests for specific addons. You can watch the open extensions issues.

**Comment by s-ankur** [comment]
Hi @kbrosnan, is this new policy? Because there are many specific addon requests still open.
