### ISSUE TITLE
Allow taking screenshot from incognito mode

### ISSUE THREAD

**Issue by officiallor** [mozilla-mobile/fenix#13419]
### What is the user problem or growth opportunity you want to see solved?
A few versions back, taking screenshots from incognito mode was allowed

### How do you know that this problem exists today? Why is this important?
Now when we want to take a screenshot from incognito mode is not allowed. Taking screenshots without needing to leave incognito mode and search again to find that specific page is a must in my opinion. 

### Who will benefit from it?
Many people that don't want to switch to normal mode, search again for something that they've already found and take a screenshot so they can send it somewhere.

**Comment by cadeyrn** [comment]
There is an option to allow screenshots in private mode.

**Comment by anotherus3r** [comment]
Three dot menu > Settings > Private browsing > Allow screenshots in private browsing

**Comment by officiallor** [comment]
I just confirmed that. It was enabled by default before and now it was disabled for some reason. Thank you.
