### ISSUE TITLE
FNX-14592 ⁃ Performance review of swipe to switch tabs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#13411]
We want to remove the feature flag from swipe to switch tabs https://github.com/mozilla-mobile/fenix/issues/13330: let's ensure it doesn't regress anything first.

**Comment by sraturi** [comment]
Performance review https://github.com/mozilla-mobile/fenix/issues/13330#issuecomment-674211214

**Comment by mcomella** [comment]
Closing: full team approval as of https://github.com/mozilla-mobile/fenix/issues/13330#issuecomment-675177794
