### ISSUE TITLE
[Bug] Can't select url

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#13413]
## Steps to reproduce
Search for something using a bang on duckduckgo and click on the url bar.

### Expected behavior
The page url is selected.

### Actual behavior
The original search query is selected.

This can be a problem because while on a search page users are probably more interested in the search query than the url, duckduckgo bangs can redirect to many sites where that wouldn't be the case. Even refreshing the page leaves the original search query in the url bar, you have to click on a link before you can access the url again.
![ezgif-6-e2d5b1d68c1e](https://user-images.githubusercontent.com/66154603/89697189-57e21480-d91b-11ea-9a95-1223d42aa975.gif)

This could be fixed by checking if the domain is still that of the search engine or not.

### Device information

* Android device: 10
* Fenix version: Nightly 200807 06:01 (Build #2015756531)

**Comment by mobd** [comment]
There could be a check for whether the domain of the page is still that of the search engine or not.

**Comment by s-ankur** [comment]
> duckduckgo bangs can redirect to many sites where that wouldn't be the case

but what if people want to use the same query and just change the bang. then this solution would be a problem for those people. It would be better to have both the URL and the query available but Im not sure how it could be implemented

**Comment by anotherus3r** [comment]
You can tap and hold the address bar and you'll get an option to copy the URL.

**Comment by mobd** [comment]
> but what if people want to use the same query and just change the bang?

Yea that might be a use case for some people, but I think the current behaviour goes against users (or at least my) expectations.

> You can tap and hold the address bar and you'll get an option to copy the URL.

You're right, that's a workaround. I think that shouldn't be necessary though

**Comment by liuche** [comment]
We added this feature so that people can change their search query, so this is working as expected and as noted, there is a workaround.
