### ISSUE TITLE
[Bug] Two finger scrolling selects instead of scrolling on Chrome OS

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla-mobile/fenix#13414]
## Steps to reproduce
Install https://play.google.com/store/apps/details?id=org.mozilla.fenix in Chrome OS
Load https://www.mozilla.org/ on Firefox Nightly
Try to scroll with two fingers

### Expected behavior
Web content scrolls normally

### Actual behavior
Web content is selected and scrolls erratically.

### Device information

* Android device: Lenovo 100e Chromebook
* Fenix version: 200807 06:01 (Build #2015756529)

**Comment by hwinnemoe** [comment]
Duplicate of #3708

**Comment by NotWoods** [comment]
Closing as duplicate. For now touchscreen usage works on Chrome OS.
