### ISSUE TITLE
The URL bar is so big

### ISSUE THREAD

**Issue by 7sevenseven** [mozilla-mobile/fenix#13415]
The URL bar is so big that sometimes when I want to click the function key to set or do other things, I will click to the window page.  This will cause many operating errors.  If I want to know what the specific URL is, I will copy it.  Can the URL bar be made smaller and the function keys enlarged?
Take some frequently used functions out of the drawer and put them in the bottom rail.  It is better to add another function to exit firefox

**Comment by kbrosnan** [comment]
Multiple issues reported in this issue. Closing
