### ISSUE TITLE
Add a Bookmark sorting (new/old) function for Firefox mobile

### ISSUE THREAD

**Issue by CrustyNpl** [mozilla-mobile/fenix#13426]
### What is the user problem or growth opportunity you want to see solved?

- Lack of bookmark sorting functions/options on Firefox mobile after recent updates and just in general.
The new update has scrambled my bookmarks and is showing my bookmarks from oldest(top) to newest(bottom) instead of the other way around. It has also changed the order of some of the bookmarks near the bottom:
(Top)
Oldest
Older
Old
New
Old
Newer
Newest
(Bottom)

Before the update it was:
Newest
Newer
New
Old
Older
Oldest

### How do you know that this problem exists today?
- I experienced it.
Why is this important?
-To fix/add a useful feature that should be easy to added.
- To make the Firefox supporters and promoters have confidence in your product/service

### Who will benefit from it?
All of the Firefox Mobile supporters who need it so they can try to fix something if and update breaks something.

###For the Import and Export on Firefox Mobile###
- Some people don't have access to a PC to download and install and sign up and sync their info.
Having and option to do just that on Firefox Mobile would be a great benefit and more people would be interested in Firefox Mobile as a good choice in mobile browsers.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4555)

**Comment by s-ankur** [comment]
It will be very helpful if you separate out the two different feature requests into different issues. Anyone working on it will find it much easier to work on one feature at a time.

**Comment by yoasif** [comment]
Import/Export bookmarks here: https://github.com/mozilla-mobile/fenix/issues/417

**Comment by liuche** [comment]
I'm going to rename this so it's clearer, and let #417 be used for tracking the bookmarks import/export part

**Comment by person808** [comment]
Adding UX feedback label so we know what a sorting UI would look like.

**Comment by cadeyrn** [comment]
see also #4348 for bookmark sorting and how it's implemented in Firefox for iOS.

**Comment by Shadowspear123** [comment]
Yes! The same thing happened to me after the update and it was sooooo frustrating. My bookmarks have no order now, they're all over the place. If I want to access a recently bookmarked site, I have to scroll allllll the way down to find it.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812711

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
