### ISSUE TITLE
Release Firefox (stable Fenix) in the Huawei AppGallery

### ISSUE THREAD

**Issue by ajhk04** [mozilla-mobile/fenix#13420]
### What is the user problem or growth opportunity you want to see solved?
Currently, Firefox for Android is not available in the Huawei AppGallery. Huawei is one of the biggest smartphone OEMs and one year ago had been revoked access to Google Mobile Services, including the Google Play Store. In response Huawei developed their own Huawei Mobile Services, and increased focus on expanding the Huawei AppGallery. 

### How do you know that this problem exists today? Why is this important?
Looking up Firefox in the AppGallery shows only Firefox Focus, but not the main Firefox for Android. Stable Fenix (ex-Fennec) has limited reach to Huawei users.

### Who will benefit from it?
Huawei users without access to GMS will get easier access to the main Firefox app. Firefox will gain access to a potentially big market. Chrome isn't available either.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4545)

**Comment by anotherus3r** [comment]
Yeah, and not just China. Huawei is big in Europe and other markets, too.

**Comment by bobreyes** [comment]
There are many Huawei devices (smartphones and tablets used for homeschooling) in the Philippines. Many are asking the local Mozilla community (MozillaPH) when will there be Firefox in the Huawei AppGallery.

**Comment by oliverkardos** [comment]
Yes please. Release FIrefox on Huawei AppGallery. These devices don't have Chrome, just an OEM browser. There is huge market and demand. I mean, have you seen the wish list with MILLIONS of unique users asking for firefox???

**Comment by fitojb** [comment]
This is tagged as “Feature: China” but Huawei devices are very popular in other markets like Mexico.

**Comment by pthfdr-42** [comment]
I do not agree. When an application is released there, Huawei modifies them.  
Even worse, it would warn against original APKs and ask you to install the so-called "safe" ones from that bullshit store.  
Also, by releasing it there, you are encouraging this bad practice.

**Comment by fitojb** [comment]
Oh no, the stupidity of some project managers to use stalebot still persists…

**Comment by fitojb** [comment]
Oh no, the stupidity of some project managers to use stalebot still persists…

https://drewdevault.com/2021/10/26/stalebot.html

**Comment by revad** [comment]
In a (yachting) forum I posted this link
https://addons.mozilla.org/en-GB/firefox/addon/ublock-origin/
A user in the UK (Huawei p smart 2019) clicked it using the default Huawei browser and got "not available in your region" - see screenshot.
So it's not only that Firefox is missing from the App Gallery but users seem to be redirected to what I assume is a fake version. And it has 74M installs!

My guess is that this is  Huawei-modified version of Fenix for China. Maybe somebody should spoof location and investigate this further.

![Screenshot_20220101_084908_com huawei appmarket](https://user-images.githubusercontent.com/3061165/147869625-a53f0d86-29b0-4eae-9750-bb0e72faed5e.jpg)

**Comment by mscardovi** [comment]
> I do not agree. When an application is released there, Huawei modifies them. Even worse, it would warn against original APKs and ask you to install the so-called "safe" ones from that bullshit store. Also, by releasing it there, you are encouraging this bad practice.

Your comment is really unuseful. There are lots of evidences about google and other "safe" companies stealing data from user and re-sell them to third parties and you still say that huawei is the evil one? Don't make me laugh. Personally I have a P40 and I feel more secure with it instead of any other phone maker. Here in italy we are a lot of people using huawei and lots of us would like to use an AppGallery version of Firefox, instead of downloading it from third-parties/aurora store.

**Comment by scardracs** [comment]
I'm still interested on it.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807948

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
