### ISSUE TITLE
FNX-14610 ⁃ [Bug] Tabs: don't reload an existing tab when switching from another tab (or less often than currently)

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#13429]
## Steps to reproduce
Navigate and add 4 tabs (ABCD) in the Tab tray
Display tab A and wait for it to be fully loaded
Then display tab B
Then display tab A again (either via Tab Tray or by horizontal swiping) (step 1)
Then display Tab B, C, D and go back to tab A (step 2)

### Expected behavior
Step 1 and 2:  Tab A should display immediately in its last state, without lag

### Actual behavior
Step 1: no issue, tab A is displayed without reloading
Step 2 There is a lag in display, It seems that tab A is being reloaded in this case

### Device information

* Android device: Redmi Note 7 Android 9
* Fenix version: #2015756915

**Comment by ekager** [comment]
Sounds like a dupe of https://github.com/mozilla-mobile/fenix/issues/12731
