### ISSUE TITLE
FNX-14604 ⁃ [Bug] private keyboard not enabled in new search experience 

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#13423]
## Steps to reproduce

1. enable new search experience
2. use gboard
3. tap address bar

### Expected behavior

gboard should be using private keyboard (can verify with icon in keyboard toolbar with glasses and hat)

### Actual behavior

gboard is not using private keyboard. 

### Device information

* Android device: pixel 2
* Fenix version: Nightly 200807 06:01 (Build #2015756531)
AC: 53.0.20200804130112, 789a73eb2
GV: 81.0a1-20200803094100
AS: 61.0.10

**Comment by klint** [comment]
Same with MS Swiftkey keyboard here.

**Comment by sflorean** [comment]
Verified as fixed on 81.1.1-beta.3 with Google Pixel 3(Android 11).
