### ISSUE TITLE
FNX-4967 ⁃ [Bug] Youtube plays fullscreen in portrait mode

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#1343]
## Steps to reproduce
* Set device in portrait mode
* Open youtube video
* Set fullscreen

### Expected behavior
* Video should play in landscape mode

### Actual behavior
* Video plays in portrait mode
Works in Fennec Nightly, Chrome latest stable

### Device information
* Android device: Samsung S10e
* Fenix version: 1.0.1914 (latest from playstore)

**Comment by jonalmeida** [comment]
Related: https://github.com/mozilla-mobile/fenix/issues/1006

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #11990109 from 18/7** using the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)
