### ISSUE TITLE
[Bug] Keyboard does not pop up on editing bookmarks

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13433]
## Steps to reproduce
set a bookmark
click on the star icon to edit the bookmark
### Expected behavior
cursor placed at end of the bookmark title and the keyboard pops up,, allowing to easily edit the bookmark
### Actual behavior
cursor placed at the start and keyboard does not pop up
### Device information

* Android device: Asus Zenfone
* Fenix version: 
Nightly 200809 06:01 (Build #2015756915)
AC: 54.0.20200807130552, 1d5e94f0d
GV: 81.0a1-20200806033456
AS: 61.0.10

**Comment by yoasif** [comment]
FYI this works in Fennec but not Chrome. I think the Fennec behavior is better.

**Comment by jakefleming156** [comment]
Thanks for filing this bug. It's looking similar to #11425 so I'll close this issue.
