### ISSUE TITLE
[feature request] Enable all Fennec extensions

### ISSUE THREAD

**Issue by mohibo** [mozilla-mobile/fenix#13430]
can somebody please explain us how much is going to take to have all the extensions back?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4562)

**Comment by freebrowser1** [comment]
That is indeed a weird limitation.
Why cannot (even as a developer option) the extensions supported previously be enabled and not limited to only nine extensions ?

**Comment by mohibo** [comment]
yet we still stuck  with six extensions since ferbuary

**Comment by cadeyrn** [comment]
> yet we still stuck with six extensions since ferbuary

This is not true, neither the months nor the number is correct.

It was one extension since March, six extensions since May and nine extensions since July.

**Comment by mohibo** [comment]
> 
> 
> > yet we still stuck with six extensions since ferbuary
> 
> This is not true, neither the month nor the number of add-ons are correct.
> 
> The new Firefox supports one extension since March, six extensions since May and nine extensions since July (in pre-release builds one month earlier for each milestone).

and they going to take one year to add another 10 extensions

**Comment by Dunexus** [comment]
@mohibo Instead of doing wacky assumptions, take a look at this comment https://github.com/mozilla-mobile/fenix/issues/11308#issuecomment-671500918 written by the Add-ons Community Manager at Mozilla. It should give you a good overview of what the next steps toward a wider add-ons support are.

**Comment by mohibo** [comment]
> 
> 
> @mohibo Instead of doing wacky assumptions, take a look at this comment [#11308 (comment)](https://github.com/mozilla-mobile/fenix/issues/11308#issuecomment-671500918) written by the Add-ons Community Manager at Mozilla. It should give you a good overview of what the next steps toward a wider add-ons support are.

which they closed it

**Comment by mohibo** [comment]
> 
> 
> @mohibo Instead of doing wacky assumptions, take a look at this comment [#11308 (comment)](https://github.com/mozilla-mobile/fenix/issues/11308#issuecomment-671500918) written by the Add-ons Community Manager at Mozilla. It should give you a good overview of what the next steps toward a wider add-ons support are.

that's for nightly only,its not for stable
