### ISSUE TITLE
[Bug] Changing the download folder from about:config doesn't work

### ISSUE THREAD

**Issue by TrianguloY** [mozilla-mobile/fenix#13435]
## Steps to reproduce
Follow the steps here https://support.mozilla.org/en-US/questions/1028808 to change the download folder to a different one (for example to "/storage/emulated/0/Download/firefox")
Go to any page with an image, long tap, save image (or download a file)

### Expected behavior
The file to be saved in the /storage/emulated/0/Download/firefox/ folder

### Actual behavior
The file is saved in the default download folder

### Device information

* Android device: Nexus 5X, Android 8.1.0
* Fenix version: 79.1.0-beta.1 (Build #2015753459) (latest play store)

[This does work in the non beta firefox for android]
[Related issue: https://github.com/mozilla-mobile/fenix/issues/5764 ]

**Comment by kbrosnan** [comment]
`about:config` will not be the way to handle this.
