### ISSUE TITLE
FNX-14618 ⁃ [Bug] Long press to select does not work in textboxes in certain cases

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13438]
## Steps to reproduce
There are multiple ways to encounter thus bug but this is the easiest to reproduce
On this page type out a few words in the comments textbox
Place cursor at the center of a word and long click on it

### Expected behavior
It should be selected, and this is the behaviour in other Android textboxes including fenixs's own urlbar

### Actual behavior
It isn't selected. 

### Device information
* Android device: Asus Zenfone
* Fenix version: Nightly 200809 06:01 (Build #2015756915)
AC: 54.0.20200807130552, 1d5e94f0d
GV: 81.0a1-20200806033456
AS: 61.0.10

**Comment by s-ankur** [comment]
Hu, @jakefleming156, could you tag this with something like feature IME since it's removed from triage?

**Comment by liuche** [comment]
is this specific to editable text boxes, or also text on a page? there's some related work in #10618 and it sounds like there's a patch coming soon

**Comment by s-ankur** [comment]
So far I've only encountered it in textboxes. I can still reproduce in latest nightly

> Place cursor at the center of a word and long click on it

Since we only have a cursor in textboxes. Moreover in this one the selection does not happen at all, but in the other issue it is about the delay before selecting

**Comment by Yajo** [comment]
I see text selection weird everywhere in Firefox. 😅

**Comment by ekager** [comment]
@s-ankur can you still reproduce this?

**Comment by s-ankur** [comment]
Yes still able to see this in nightly

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683257

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by makotokato** [comment]
@s-ankur do you have any screencast for this?

**Comment by Yajo** [comment]
See https://github.com/mozilla-mobile/fenix/issues/15391#issuecomment-698421694

**Comment by s-ankur** [comment]
Hi @makotokato , specifically this action

Notice the difference when you do it in a text box and in the awesombar, awesomebar behavior is correct

https://user-images.githubusercontent.com/33252312/104472294-cff6e980-55e1-11eb-8c58-959c8bea3ed7.mp4
