### ISSUE TITLE
[Bug] incorrect information in play store about addons

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13436]
## Steps to reproduce
Open play store and go to the firefox browser page https://play.google.com/store/apps/details?id=org.mozilla.firefox
Click about this app to see description

> GET ADD-ONS FOR EVERYTHING
> - Take control of your mobile browser by personalizing Firefox with add-ons like ad blockers, <b> password and download managers</b> and more. Want a more personalized browser? Add-ons can help you customize your browser to make your time online safer. 

This is incorrect for the latest update as password and download managers are unavailable as addons

**Comment by kbrosnan** [comment]
This should change when Firefox is at 100% rollout.
