### ISSUE TITLE
FNX2-18744 ⁃ [Bug] [Volunteering] Is there a communication kit towards Fenix new users or volunteers?

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#13431]
Hi
Sorry to open a bug for that, but I have no clue where to send my request! 

I have volunteered to help the launch of the brand new Fenix in production, starting July 28th, by answering comments left by Firefox for Android users on Google Play after they migrated (most of the time unwillingly) to Fenix.
And I feel almost as frustrated as the numerous people I read negative comments from, because I just have realized that I miss critical information about this roll out and the future steps... despite months spent in using nightlies and opening bugs/feature requests :)

The same way the migrated users are lacking communication about:
1) The reason why Firefox has evolved
2) why it has evolved with such a disruptive user experience 
3) why it has evolved by removing beloved features (PDF export, simpler bookmark management, about:config, less clicks to achieve basic things and reach critical data like bookmarks, history, most visited sites, missing addons... whatever, just read the comments on Google Play)
4) A comprehensive walkthrough showing all new features/changes compared to the now legacy version 68
5) A plan for the next steps: when will new addons and "beloved" features be made available, if they will? :)

The problem for me is that I lack the answers to these questions as much as the users! And I am the one supposed to provide them with some useful responses on Google Play (sorry, but being just kind with the user and saying "we're sorry, please come back later" is not a valid option to me, I would be quite frustrated if a company replied to me in such a manner).

So, my question basically here is: is such a level of information available somewhere and can it be provided to the support/volunteers team at least, or even better, in a proper and clear communication to the end users? 

And as a volunteer, I also miss some internal information about the rollout process and plan. Is it done by batches of users, how many if so, can the rollout be suspended at some point in order to give time to solve the must critical issues raised by the first batches of users... etc etc etc???

Or am I missing the point totally here??? :) I can't even find a blog entry about the rollout that started on July 28th.

Thanks for your patience. :)

**Comment by SeburoSUMO** [comment]
Hi Klint.

Thank you for raising this issue.  I am a contributor to the Mozilla Support team mainly looking at the Android products and it is great to hear that you are helping us through the Respond tool.

I am keen to help you to help us better and to give you a bit more background to help answer your concerns.  So that I can do this, please can you drop me a direct message through the support platform at https://support.mozilla.org/en-US/user/Seburo or message me directly on the Mozilla Matrix instance.

Thank you.

**Comment by liuche** [comment]
Please reach out to Seburo! He's an expert in our support and volunteer tools, so he will have the information that you need. If there are specific links that we can add to the README that aren't present, we can also do that.
