### ISSUE TITLE
[Bug] When YouTube video played on 1.75 sound gets distorted

### ISSUE THREAD

**Issue by Dazrok2** [mozilla-mobile/fenix#13441]
## Steps to reproduce

Play any video on YouTubeand  at1.5x or higher. 

### Expected behavior 

Sound should come as Regular Firefox

### Actual behavior

Sound is getting distorted 

### Device information

Xiomi redmi note 4x

* Fenix version: 79.1.0-beta.1

**Comment by s-ankur** [comment]
Duplicate of #8456

**Comment by jakefleming156** [comment]
Thank you for filing this bug. As it's a duplicate of #8456 I'll close this one.
