### ISSUE TITLE
Bottom search bar tab button and three dots

### ISSUE THREAD

**Issue by ksaltik** [mozilla-mobile/fenix#13440]
### What is the user problem or growth opportunity you want to see solved?

When use one hand the bottom search bar should on the right side and tab button and three dots should on the left side. Or it must be configurable for left handed people or right handed people. Also the page can be refreshed when slide down like in chrome mobile

### How do you know that this problem exists today? Why is this important?

This way it is easier to use the tab button and three dots 

### Who will benefit from it?

Everyone who use firefox and mozilla

**Comment by kbrosnan** [comment]
Duplicate #6365
