### ISSUE TITLE
FNX2-18732 ⁃ FF 79 hides bottom part of pages 

### ISSUE THREAD

**Issue by danieltakesphotos** [mozilla-mobile/fenix#13444]
I have a page that fits to the screen size of the browser window. It works in any browser, except in the latest firefox 79 for android devices (it worked until the last ff release).

The new firefox release hides the bottom of the page either with its toolbar or (if set to show toolbar on top) with a useless white bar of the same size on the bottom. I have buttons at the bottom that "shine" through that white "hiding bar", but they are not touchable. So, in principle, everything on the page is positioned correctly, except that firefox lays its "hiding bar" or it's toolbar over the bottom, depending on ff settings.

In CSS I have set html,body min-height to 100%. (It doesn't help when set to 100vh) There's a wrapper div that encloses everything else, set to min-height 100vh. There's a footer div (inside wrapper) set to position absolute, bottom 0;

Now the page fits the screen size including firefox's "hiding bar", thus part of the footer div is invisible. As the page isn't larger than the screen it cannot be moved up. There is no way to make visible the part of the footer that is overlayed by that white bar...

I tried as a test to add a margin-bottom to the wrapper, but the only effect is that firefox's hiding bar gets higher for the amount of the margin. It simply wants to hide the bottom of my page and I don't know what to do... 

So in principle right now I can only detect firefox users and display a message: "You are trying to access a page with firefox. Please use a browser instead".  

I can provide screenshots or the URL of my page on request, but didn't write it here to not appear like using bugzilla for advertisement...

**Comment by jakefleming156** [comment]
Thank you for filing this bug. It sounds similar to another issue we're working on, #11389. Within the comments, you'll find a screenshot of a white bar while on Spotify. Is this what you're seeing @danieltakesphotos?

**Comment by danieltakesphotos** [comment]
> It sounds similar to another issue we're working on, #11389. Within the comments, you'll find a screenshot of a white bar while on Spotify. Is this what you're seeing @danieltakesphotos?

Yes, that's the way it looks. Meanwhile I am investigating and (at the moment) I believe the bug appears in context with full size canvas. When I remove the canvas the white bar disappears.

As much as I can see, window sizes are calculated differently in the desktop version (I have 78.0.2esr (64-Bit) on OpenSuse) than in the mobile version 79..:

In my jquery-code I defined the height of the canvas with $(window).height(), which gave a too small number, so that the canvas (position absolute, top 0) left "free space" below: this white bar.

Now I calculate the height of the embedding wrapper that is defined in CSS with height: 100vh (var wrapH=$('#wrapper').height();) and then use this number as height for the canvas. This way the canvas fills the complete screen and the white bar disappears. But it seems a quite ugly workaround.

**Comment by jakefleming156** [comment]
That's quite clever actually. I am going to link this bug to #11389 and close this issue so we don't have too many duplicates over the same issue. Thanks for figuring out as much as you have. I'll pass this all along to our devs.
