### ISSUE TITLE
FNX-14623 ⁃ [Bug] Upgrade from python2 to python3

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13443]
I noticed that some files are still using python2 in the build and automation process. Since python2 is no longer supported since January 1st 2020 (https://www.python.org/doc/sunset-python-2/) fenix should move to using python3 as soon as possible. This will not be very difficult as most of the files are already compatible with python3

**Comment by liuche** [comment]
@JohanLorenzo is this something that we're looking to do? I'm not sure how TC is handling the python scripts in other places as well (or if that would cause any problems with our infra/images)

**Comment by JohanLorenzo** [comment]
Thanks for filing this issue @s-ankur! I agree with you, python2 is no longer supported and it's risky to keep py2 codebases around. Thanks for voicing this concern! 

As far as I know, the biggest piece to move is taskgraph. It depends on what we have in https://hg.mozilla.org/mozilla-central/ which is tracked in [Bug 1611358 - Support python 3 in taskcluster](https://bugzilla.mozilla.org/show_bug.cgi?id=1611358). Migrating the python codebase in mozilla-central has been quite a big project 😅 

That said, we may be able to update some other files! Let's see what we have:

```sh
find . -name '*.py'

./app/src/androidTest/java/org/mozilla/fenix/syncintegration/gradlewbuild.py
./app/src/androidTest/java/org/mozilla/fenix/syncintegration/conftest.py
./app/src/androidTest/java/org/mozilla/fenix/syncintegration/adbrun.py
./app/src/androidTest/java/org/mozilla/fenix/syncintegration/tps.py
./app/src/androidTest/java/org/mozilla/fenix/syncintegration/__init__.py
./app/src/androidTest/java/org/mozilla/fenix/syncintegration/test_integration.py
./taskcluster/docker/visual-metrics/similarity.py
./taskcluster/docker/visual-metrics/run-visual-metrics.py
./taskcluster/fenix_taskgraph/util.py
./taskcluster/fenix_taskgraph/job.py
./taskcluster/fenix_taskgraph/__init__.py
./taskcluster/fenix_taskgraph/gradle.py
./taskcluster/fenix_taskgraph/transforms/build.py
./taskcluster/fenix_taskgraph/transforms/signing.py
./taskcluster/fenix_taskgraph/transforms/multi_dep.py
./taskcluster/fenix_taskgraph/transforms/browsertime.py
./taskcluster/fenix_taskgraph/transforms/push_apk.py
./taskcluster/fenix_taskgraph/transforms/raptor.py
./taskcluster/fenix_taskgraph/transforms/mark_as_shipped.py
./taskcluster/fenix_taskgraph/transforms/__init__.py
./taskcluster/fenix_taskgraph/transforms/visual_metrics.py
./taskcluster/fenix_taskgraph/transforms/notify.py
./taskcluster/fenix_taskgraph/transforms/test.py
./taskcluster/fenix_taskgraph/transforms/secrets.py
./taskcluster/fenix_taskgraph/loader/multi_dep.py
./taskcluster/fenix_taskgraph/loader/__init__.py
./taskcluster/fenix_taskgraph/parameters.py
./taskcluster/fenix_taskgraph/target_tasks.py
./taskcluster/fenix_taskgraph/worker_types.py
./taskcluster/fenix_taskgraph/release_promotion.py
./taskcluster/fenix_taskgraph/routes.py
./taskcluster/scripts/get-secret.py
./taskcluster/scripts/write-dummy-secret.py
./automation/taskcluster/androidTest/parse-ui-test.py
./automation/taskcluster/l10n/filter-release-translations.py
./automation/taskcluster/l10n/locales.py
```

Good news first: we don't have that many files 😃 

* Everything under `taskcluster/fenix_taskgraph/` cannot be migrated yet (it's part of taskgraph).
* `taskcluster/scripts/` and `automation/taskcluster/l10n/` look easily doable.
* `automation/taskcluster/androidTest/parse-ui-test.py` and `taskcluster/docker/visual-metrics` are already py3.
* `app/src/androidTest/java/org/mozilla/fenix/syncintegration/` is py2.7 and I don't know how feasible the migration is. What's your view on this, @isabelrios?

**Comment by AaronMT** [comment]
Looking at /syncintegration/ today and noticed it's still py27 req  which I dont imagine it really it is. I think this should be re-opened.
