### ISSUE TITLE
Crash in [@ libxul.so@0x11bd3a4 | libc.so@0x7efff]

### ISSUE THREAD

**Issue by 894-572** [mozilla-mobile/fenix#13450]
## Steps to reproduce
Browse for a little while.
### Expected behavior
The browser remains stable.
### Actual behavior
The browsing session ends in a crash very quickly, in roughly 15 minutes of typical use. The open tabs aren't lost when not using private browsing.
### Device information
* Android device: Oneplus One (LineageOS 16/Android 9)
* Fenix version: 79.1.0-beta.1 (crashing has _always_ been an issue — I first installed Fenix when the extension support was introduced)

**crash logs** (from the last week, can share more if needed):
https://crash-stats.mozilla.org/report/index/bp-9510ec8f-f489-4f0b-acce-0f4930200810
https://crash-stats.mozilla.org/report/index/bp-da557e3b-9a5b-47be-8b96-b14520200809
https://crash-stats.mozilla.org/report/index/bp-98c68007-d77a-4e2a-8b41-28e3d0200808
https://crash-stats.mozilla.org/report/index/bp-decb1f5b-4702-4d65-acaf-acf720200807
https://crash-stats.mozilla.org/report/index/bp-cdb19c34-adbb-4458-927c-8f33b0200806
https://crash-stats.mozilla.org/report/index/bp-20f8a3de-968e-46c5-a1c0-39d380200806
https://crash-stats.mozilla.org/report/index/bp-65db2813-ace2-4e01-8e02-eb9ea0200806
https://crash-stats.mozilla.org/report/index/bp-ac94c5fc-22a2-4760-bbfa-6a5dd0200806
https://crash-stats.mozilla.org/report/index/bp-049b3023-cf6f-42c2-b2cc-cc3470200806

**Comment by kbrosnan** [comment]
Where did you get this build? Would you attach a screenshot of the about Firefox page? For some reason this build is not correctly symbolicated.  

* 3 dot menu
* Settings
* Scroll to bottom, About Firefox

**Comment by 894-572** [comment]
> Where did you get this build?

Downloaded with [Aurora store](https://f-droid.org/en/packages/com.aurora.store/) since I don't have Google Play services installed and I didn't know a better way of automating updates.

I have since updated Firefox, the version isn't the same any of the crash reports were created on.

![Screenshot_20200814-105047_Firefox_Beta_1](https://user-images.githubusercontent.com/44001490/90226804-17930280-de03-11ea-9eee-d9ea86d400be.png)
