### ISSUE TITLE
Data review on #11940 is missing data collection category

### ISSUE THREAD

**Issue by mdboom** [mozilla-mobile/fenix#13454]
We are going through using a scraper to extract the data collection (sensitivity) category for existing metrics in Fenix.

It came across a data review without a data collection category here:

https://github.com/mozilla-mobile/fenix/pull/11940/#pullrequestreview-438445008

> Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?

> Yes, when home activity gets opened

I think this is just a copy-and-paste glitch.  But we should have a data steward go in and correct this to a data collection category.  

Cc: @liuche

**Comment by liuche** [comment]
Thanks for catching this! Just fixed it :) https://github.com/mozilla-mobile/fenix/pull/11940#pullrequestreview-438445008
