### ISSUE TITLE
FNX-14638 ⁃ [Bug] Dismissed download completed/canceled notification re-appears

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13458]
## Steps to reproduce
1. Download a file.
2. Open the notifications tray.
3. Swipe to dismiss the notification.
4. Observe the notifications.
### Expected behavior
The notification is dismissed.
### Actual behavior
The download completed notification reappears for a second after it was dismissed.
Same thing for notification of a cancelled download.
### Device information

* Android device: Pixel 4 (Android 10), couldn't reproduce on other devices.
* Fenix version: Nightly 8/10, RC 79.0.3, Beta 80.0.0-beta 5

<img src="https://user-images.githubusercontent.com/4037709/89801198-825ce900-db38-11ea-8da7-1e48bf0f1361.gif" width="300" height="550" />

**Comment by liuche** [comment]
Dupe to #14790
