### ISSUE TITLE
FNX-14647 ⁃ [Bug] New Search Experience: pressing enter on an empty toolbar query puts the browser in a weird state

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13467]
## Steps to reproduce
Enable new search experience
click on toolbar and erase query, if any
press enter

### Expected behavior
Im not sure, maybe it should just close the toolbar or do nothing perhaps. In either case, it should go back to some valid state

### Actual behavior
Screen is covered by black overlay, and keyboard closes so 
1. to search you need to click on the toolbar again
2. to go back to browsing you need to click on the black overlay

So, the current state is invalid as you can neither browse nor search
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly
Related  #13052

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 81.1.0-beta.1 (Build #2015761489) GV 81.0 from 9/2 with Samsung Galaxy Tab S3 (Android 8).

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200910 (Build #2015763059).

### Devices used:
- OnePLus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)
