### ISSUE TITLE
[Bug] Tab Tray -> Save to Collection -> Swipe Down opens a translucent black overlay 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13464]
## Steps to reproduce
enable new search experience
open tab tray
click save to collection
swipe down on the purple band

### Expected behavior
tab tray closed, you can return to what you were doing
### Actual behavior
a black overlay covers the entire screen, tapping removes it
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
> enable new search experience
happens without it as well

**Comment by kbrosnan** [comment]
Closing as works for reporter
