### ISSUE TITLE
FNX-14650 ⁃ Change performance test intent so that it can run on CI

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#13470]
We need to talk with sparky to understand the requirements.

**Comment by acreskeyMoz** [comment]
The issue may be the testing of battery being usb plugged. 
https://github.com/mozilla-mobile/fenix/blob/923d8414036062b231d24f941677f29221273a3d/app/src/main/java/org/mozilla/fenix/perf/Performance.kt#L45
Some folks have seen this in local tests as well as CI.

**Comment by mcomella** [comment]
In the short term, we want to fix the issue that acreskeyMoz has raised, if possible.

In the long term, we have a different solution in mind: https://jira.mozilla.com/browse/FXP-1311

**Comment by mcomella** [comment]
I notice mach perftest MAIN/VIEW seem to use a `DEBUG_APP` setting: perhaps we can use this flag instead: https://developer.android.com/reference/android/provider/Settings.Global#DEBUG_APP

**Comment by MarcLeclair** [comment]
Triage: Wait until we test `./mach perftest` with MAIN and see if the issue is there.
