### ISSUE TITLE
FNX-4968 ⁃ [Bug] Cannot load about:telemetry

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1347]
[From @bsurd](https://github.com/mozilla-mobile/fenix/issues/513#issuecomment-479454358)

### STR:
1. Go to any about page.
1. Tap on the back button.

### Expected:
The home page is displayed without any about pages in the session.

### Actual:
Fenix crashes, after you reopen the app the about page is also displayed.

### Notes & information:
* [Logcat](https://github.com/mozilla-mobile/fenix/files/3038433/log.txt)
* [Video](https://drive.google.com/open?id=1fy4q_dX4p7EgvqPgG_51AsXi6p4CluCJ)
* Fenix 1.0.1914 (#10921239)

**Comment by sblatz** [comment]
I wonder if GV team also needs to remove this page for Fenix? Or is that just applicable to about:crashes?

cc: @cpeterso

**Comment by cpeterso** [comment]
> I wonder if GV team also needs to remove this page for Fenix? Or is that just applicable to about:crashes?

I don't know yet, but I added notes regarding `about:telemetry` and linked to this issue from GV's "disable `about:config`" bug https://bugzilla.mozilla.org/show_bug.cgi?id=1541152.

**Comment by vesta0** [comment]
We should fix the crash.

**Comment by cpeterso** [comment]
This `about:telemetry` crash is probably a duplicate of `about:config` crash #1034, which was fixed in GV 68 Nightly by https://bugzilla.mozilla.org/show_bug.cgi?id=1527778.

**Comment by bsurd** [comment]
This is now fixed and works as expected, the crash in #1034 is still reproducible on the Note 8 device tho.
