### ISSUE TITLE
FNX-14653 ⁃ Add scan shortcut and search engines to accessory bar

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#13473]
Parent #13052 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/89821904-f38aa500-db14-11ea-8632-0ccacbd3680c.png">

**Comment by brampitoyo** [comment]
We can potentially do a follow-up to move Search Shortcuts and Scan button into the address bar.

| Keyboard down | Keyboard up |
| --- | --- |
| <img width="360" src="https://user-images.githubusercontent.com/51007/89858333-81888d80-dbf2-11ea-9f9a-c7d00cec2f82.png"> | <img width="360" src="https://user-images.githubusercontent.com/51007/89858335-84837e00-dbf2-11ea-9509-8d55a1ddc3de.png"> |

| Type something into the address bar |
| --- |
| <img width="360" src="https://user-images.githubusercontent.com/51007/89858453-ddebad00-dbf2-11ea-9cd0-81b727d6c492.png"> |

**Comment by amkcpu** [comment]
@brampitoyo Maybe it makes sense to also show the arrow next to the search engine with the keyboard down, to inform the user that there are other search engines than (in this case) Google. Also, it makes for less animations/changing elements when opening the keyboard -> less distractions and more consistency.

**Comment by brampitoyo** [comment]
@amkcpu wrote:

> Maybe it makes sense to also show the arrow next to the search engine with the keyboard down

For sure. You’ve written some great points. I could’ve sworn I had the arrow in, too. I will update the table above.

**Comment by liuche** [comment]
Updating this to scope down to handle only the QR scanner.

**Comment by hwinnemoe** [comment]
Follow-up issues: https://github.com/mozilla-mobile/fenix/issues/16659 and https://github.com/mozilla-mobile/fenix/issues/16658
