### ISSUE TITLE
FNX-4969 ⁃ [Bug] Crash when playing livestreams on hdontap.com

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1348]
## Steps to reproduce
* Load https://hdontap.com
* Select Hanover Eagles under Live Animals Cam

### Expected behavior
* The site loads and I can see the stream

### Actual behavior
* I get both the Fenix crash dialog and the Google crash dialog

### Device information
* Android device: Pixel 3 running Android Pie
* Fenix version: Build ID #10921240

**Comment by ekager** [comment]
Just tried to reproduce this on Pixel 3 on Pie, and it didn't crash but the site never loaded. (Maybe a TP issue..)
Are you still seeing a crash?

**Comment by mozillamarcia** [comment]
> Just tried to reproduce this on Pixel 3 on Pie, and it didn't crash but the site never loaded. (Maybe a TP issue..)
> Are you still seeing a crash?

Using my Pixel 3 and the latest Fenix, I am no longer crashing playing various videos on that site.

**Comment by ekager** [comment]
Okay going to close this issue then for now! Please reopen if you see this happening again! Thanks!
