### ISSUE TITLE
FNX-14660 ⁃ [Bug][LeakCanary][Library Leak] LeakActivity leaked

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#13480]
/cc @mcomella

### Steps to reproduce

Unfortunately no STR.

### Expected behavior

No leak.

### Actual behavior

Leak pattern: instance field android.app.Activity$1#this$0

┬───
│ GC Root: Global variable in native code
│
├─ android.app.Activity$1 instance
│    Leaking: UNKNOWN
│    Anonymous subclass of android.app.IRequestFinishCallback$Stub
│    ↓ Activity$1.this$0
│                 ~~~~~~
╰→ leakcanary.internal.activity.LeakActivity instance
​     Leaking: YES (ObjectWatcher was watching this because leakcanary.internal.activity.LeakActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = 55b3f0d9-de3d-424b-affb-751bb3ea8d94
​     watchDurationMillis = 21246
​     retainedDurationMillis = 16199

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 8812 ms

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision 841d19e8be8b0d85e207524073c1ce2a10b3b670

**Comment by pyricau** [comment]
This is a known AOSP leak in Android Q: https://issuetracker.google.com/issues/139738913

@cadeyrn I think you probably shared only a part of the leaktrace. LeakCanary knows this leak (as hinted by the `Leak pattern: instance field android.app.Activity$1#this$0` bit you included) and adds advice on what to do with the leak.

This fix can be worked around with the following hack: https://twitter.com/Piwai/status/1169274624749658112
