### ISSUE TITLE
No 'open in app' option for Facebook

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#13496]
There is no option in the menu for facebook pages, so it opens/redirects it to Facebook app.

**Comment by liuche** [comment]
I don't think I fully understand what's happening here, are you saying that clicking Facebook links opens them in the Facebook app, instead of as links in the browser? Do you have "Open in app" checked but want to turn that off?

**Comment by aha999** [comment]
Whenever i open facebook content in a browser, be it Pages, people etc. There is no option in the menu for 'Open In App', meaning i can't directly open that facebook page in Facebook app, that would be redirected from a browser.
Facebook in browser -> missing 'Open in facebook app' button

**Comment by liuche** [comment]
I believe Firefox already has a feature that allows you to do something like this:

Do you have the "Open links in app" setting turned on in Settings? That should redirect Facebook links (and other links that can be opened by apps, such as Yelp) to the Facebook app.

3-dot menu (next to the urlbar) > Advanced > Open links in apps

**Comment by aha999** [comment]
I have that setting turned on. It does not redirrect facebook links.
What bothers me is, there's no 'Open in app' option in the menu when accessing facebook content.

**Comment by kbrosnan** [comment]
I expect that this is a Facebook bug. The open in app feature requires that the website includes code on their pages to send the user to the app. If FB does not include this code on the pages that Firefox gets then the feature will not work.
