### ISSUE TITLE
[Bug] Fix failing Deeplink UI tests

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#13491]
## Steps to reproduce
All the new deeplink UI tests are failing since [merge to master](https://github.com/mozilla-mobile/fenix/commit/77263aad704844782a461b49a92b51a8bed31c16).  Fenix has build blocking when jobs are red so not sure how they all started failing once merged unless something changed on Firebase or they were force-merged.  

Going to disable for now so they won't block other PRs from landing.  

@pocmo pls feel free to reach out if you'd like some help debugging.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by pocmo** [comment]
Sorry for causing this!

I will try to get this fixed asap. I have to get another high priority thing done and then I can look into this. I'll move it into the sprint to not forget about it.

**Comment by rpappalax** [comment]
> Sorry for causing this!
> 
> I will try to get this fixed asap. I have to get another high priority thing done and then I can look into this. I'll move it into the sprint to not forget about it.

@pocmo no worries, thank you!

**Comment by pocmo** [comment]
Please keep, Mr. Bot.
