### ISSUE TITLE
[Bug] spam mails

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#13495]
May I know why you are spamming my mailbox with mails for cases?
This seems deliberate....first you are reopening a closed case and then again closing it which is triggering mails....please fix this😡😡😡

Just now deleted 70+ mails...again mails are coming

![Screenshot_20200811-102126664](https://user-images.githubusercontent.com/58127841/89858477-70248e80-dbbc-11ea-8c8c-610f18b5d6f0.jpg)

**Comment by sheikh-azharuddin** [comment]
Now I am starting to regret contributing to this forum....tired of these mails😡😭

**Comment by sheikh-azharuddin** [comment]
@vesta0 @ekager

**Comment by sheikh-azharuddin** [comment]
![Screenshot_20200811-113749222](https://user-images.githubusercontent.com/58127841/89863126-17a6be80-dbc7-11ea-9969-eb58b9b0800c.jpg)

**Comment by AdityaGupta150** [comment]
Yes, i too got the mails, though it doesn't mean you feel bad for contributing to this.
Don't know what this data sync is doing, it's just reopening, renaming, closing, and again the same.

**In the meantime, you may change the settings [here](https://github.com/settings/notifications). Turn off the email preference for 'Participating'.** Yes you may miss some other notifications on mail from other repos, but this is just a temporary solution, if you are getting this many mails.

**Comment by s-ankur** [comment]
It's not deliberate. I've gotten a the samount of mails. They've confirmed that it's and issue with datasyncuser bot

**Comment by sheikh-azharuddin** [comment]
> Yes, i too got the mails, though it doesn't seem to be deliberate, maybe they assigned a bot something, and its going haywire.
> Don't know what this data sync is doing, it's just reopening, renaming, closing, and again the same.
> 
> **In the meantime, you may change the settings [here](https://github.com/settings/notifications). Turn off the email preference for 'Participating'. Or in email preferences turn off _Comments on Issues and Pull Requests_** Yes you may miss some other notifications on mail from other repos, but this is just a temporary solution, if you are getting this many mails.

Thanks... Turned off.. Lets see👍
Some buggy bot deployed in production 😂

**Comment by jakefleming156** [comment]
Sorry about that. Can't believe the bot's acting up again. I'll see if I can get that fixed. Blocking it should work fine and if not let me know.

**Comment by kbrosnan** [comment]
This has been turned off.
