### ISSUE TITLE
two fast taps over the tabs button open a new tab 

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#13493]
Right now, to opens a new tab, the user must tap two times instead one (with a little delay meanwhile they wait for the tab tray to open). With this new option, there's still a two taps but more faster to open directly a new tab without get through the tab tray.

**Comment by miDeb** [comment]
This was already discussed in https://github.com/mozilla-mobile/fenix/issues/11598.

**Comment by person808** [comment]
Closing as duplicate.
