### ISSUE TITLE
[Bug] No history on long press Huawei P Smart back software button 

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#13498]
## Steps to reproduce
Huawei P Smart (FIG-LX1), EMUIs software navigation is on. 
Visted some pages with any tab. 
Be sure that your history has some entries. 
Long press device software back button. 

### Expected behavior
The visited history appears. 

### Actual behavior
No history appears. 

### Device information
Huawai P Smart (FIG-LX1) has this issue

Samsung Galaxy Tab A SM-T580, the history by long press back button (hardware button) appears 

* Android device: 
9.1.0 EMUI

* Fenix version:
Nightly 200811 06:01 (Build #2015757299)
AC: 54.0.20200810074539, 7a0bc5e43
GV: 81.0a1-20200808213325
AS: 61.0.10

**Comment by pweiden** [comment]
The same problem is here for the Huawei Mate 10 Pro using Android 10, Build 10.0.0.159 (C432E5R1P3patch02) with EMUI version 10.0.0.

Both on Samsung Galaxy S8 with Android 9 and security patch level June 1, 2020, and Samsung Galaxy Tab S6 (SM-T865) with Android 10 and security patch level May 1, 2020, the "long-press history" works like a charm.

**Comment by jakefleming156** [comment]
Thank you for filing this bug. You and a few others are proving there's a need for this feature. A solution is in progress right now under issue number #11452. You can follow progress or comment there and I'll close this bug to keep dupes to a minimum.

**Comment by cadeyrn** [comment]
@jakefleming156 The feature is already implemented in Fenix Nightly and the issue here is that it doesn't work on the mentioned Huawei devices but works on other devices.

**Comment by person808** [comment]
Not a manufacturer specific bug D: I won't be able to investigate since I don't have a Huawei device. A back button should appear in the menu in the next nightly so you can long press that instead.

**Comment by person808** [comment]
On Android 7 we don't use the system long press back button detection because it doesn't work and roll our own. Maybe its appropriate to do that for Huawei devices too 🤔

**Comment by LittleAngelwings** [comment]
@cadeyrn 

Thx for your intervention 👍

@person808 

Thx 4 ur explanation, I tried the latest nightly and the new app back button with a long press shows the history.
But it's only a shaky compromise in my eyes, cause Huawei is one of the most sold devices and a big player in the business, so I think the devices back button have to work without any issues like all other devices from other brands. And @pweiden and I have Android 8+ on our devices. So it shouldn't be a problem of Android 7 and maybe lower.

**Comment by jakefleming156** [comment]
Shoot. My bad. Thanks for correcting my mistake.

**Comment by jawadalkassim** [comment]
It seems not working on all Huawei devices
My Huawei P8 / Android 8
Also not working

**Comment by yoasif** [comment]
Also an issue on Huawei P8 lite 2017

**Comment by person808** [comment]
@LittleAngelwings @jawadalkassim @pweiden Could you try one of these apks and see if it fixes the issue?

https://drive.google.com/drive/folders/19c5_7qhXqWH-NGYaZeu-JxUnY_tXT4rC?usp=sharing 

Try the arm64 variant first and if it doesn't install try the other one. It should install as a separate app so it won't overwrite your normal firefox data.

**Comment by LittleAngelwings** [comment]
@person808 

Thx, but I can't download them. Not with Fenix or chrome.

**Comment by jawadalkassim** [comment]
![Screenshot_20200828-220834](https://user-images.githubusercontent.com/48631694/91606691-30f78b00-e97b-11ea-9535-abd4e64393cf.jpg)

Fixed

**Comment by pweiden** [comment]
@person808: I can also confirm that it works now on my Huawei Mate 10 Pro! Thanks a lot!
![Screenshot_20200829_221014_org mozilla fenix debug](https://user-images.githubusercontent.com/39402893/91645421-34574900-ea45-11ea-999f-b6fc22ba3974.jpg)

**Comment by person808** [comment]
Thanks for confirming @jawadalkassim and @pweiden! I've opened #14387 with my fix.

**Comment by LittleAngelwings** [comment]
@person808 
In the meanwhile I could download the fix and it works also for me.
Good job 👍

**Comment by LittleAngelwings** [comment]
In latest GP Nigtly Update the fix work fine. Great work, Thx a lot for it. 👍😀

**Comment by person808** [comment]
Great! QA should still check though. @liuche qa:needed label?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200904`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• Huawei P10 (Android 9)
• OnePlus A3 (Android 6.0.1)
