### ISSUE TITLE
Pull-down to sync logins

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13499]
### What is the user problem or growth opportunity you want to see solved?
Similar to https://github.com/mozilla-mobile/fenix/issues/2165 and to keep consistency through the app, the Logins & passwords list would be nice to have the same pull-down to sync gesture.
### How do you know that this problem exists today? Why is this important?
Bookmarks, history, and synced tabs already have this gesture so it would come in handy to use the same gesture in all syncing lists.
### Who will benefit from it?
Everyone who uses the pull-down to sync gesture in the app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4725)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807060

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
