### ISSUE TITLE
[Bug]Chinese Pinyin Input Issue in Address Bar

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#13500]
[Bug demo video](https://youtu.be/HFy-HX1IfaI)
Chinese pinyin input issue in Address Bar.

### Device information
* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 200811 06:01
* Android Version: 10 (MIUI 12, latest patch)
* SoC: MediaTek Helio G90T (MT6785V, ARM64, ARMv8.2-A)

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1678533

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by ekager** [comment]
Mistakenly moved to Bugzilla
