### ISSUE TITLE
FNX-4971 ⁃ Use GeckoView fetch client for service-fretboard / kinto

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#1350]
We temporarily moved to `HttpUrlConnectionClient` until we have an alternative way of launching Raptor: https://bugzilla.mozilla.org/show_bug.cgi?id=1533385

See: https://github.com/mozilla-mobile/fenix/issues/1329

**Comment by rwood-moz** [comment]
For the Raptor work I filed this bug (thanks Christian for the heads-up!):

[Bug 1552519 - For geckoview browser apps startup use local configuration file instead of command line args](https://bugzilla.mozilla.org/show_bug.cgi?id=1552519)
