### ISSUE TITLE
[Bug] Transform translate lags if page has not been scrolled

### ISSUE THREAD

**Issue by jonohewitt** [mozilla-mobile/fenix#13506]
## Steps to reproduce
I have just noticed this on a site I'm building - sorry its still a bit of a mess!

Visit: http://https://la-coloc-locale.netlify.app

After the page loads, without scrolling, tap the icon to trigger the transition. This slides the page right and a settings panel slides in to fill the space.

### Expected behavior
Smooth transition of the main page and its content to the right, at the same time as the settings panel slides into view. This is observed with Firefox 80.0b6 on my desktop and the Chrome android app.

### Actual behavior
Settings panel slides out and overlaps the main content, then when it is finished transitioning, the main page begins its transition. If the page is scrolled down at all, even a few px, the issue doesn't happen - but will happen if the page is scrolled back up to the very top again.

### Device information

* Android device: Oneplus 7 Pro
* Fenix version: 81.0a1

**Comment by liuche** [comment]
Hm, I tried out the latest nightly 8/14 but don't see this.

**Comment by jonohewitt** [comment]
Ah yeah I'm not noticing it either now - sorry maybe just a bug on my phone at the time!

**Comment by liuche** [comment]
Thanks! closing this then.
