### ISSUE TITLE
Some website articles don't fully load

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#13509]
Articles on [this website](https://www.healthline.com/health/sweating-out-a-fever) refuse to load fully. Currently that link specifically.
The loading bar gets to the ~80% and it jumps back to almost start, and so it repeats indefinitely. The content is already visible, but it keeps reloading.

When i was just in the ff settings and went back, the website was fully loaded and asked me for cookies. Then i manually reloaded the website and it didn't load it fully again.

Therefore reading articles on this website that i like is basically impossible.

I have addons:
- Ublock origin
- dark reader
- privacy badger
- https everywhere

Fenix build: 79.1.0-beta.1 (Build #2015753459)

_Sent from my Lenovo P2a42 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by ghostwords** [comment]
Does disabling Privacy Badger for the site work around this problem?

**Comment by liuche** [comment]
I tried this out on the latest nightly 8/14, and don't seem to have this problem - the progress bar pauses briefly at 80%, but then continues and finishes loading (e.g. coronavirus 2020 article)

**Comment by aha999** [comment]
With all of the addons disabled, this still happens.
