### ISSUE TITLE
Open in new tab toggle from the search screen

### ISSUE THREAD

**Issue by TrianguloY** [mozilla-mobile/fenix#13508]
### What is the user problem or growth opportunity you want to see solved?

A faster, and maybe novelty, way to open a new tab, either start a new search, go to an edited url of the current tab, going to an autocompleted url, or duplicate the current url. All of that just by adding a toggle/switch. (Equivalent to the alt+enter in the search bar on firefox desktop)

### How do you know that this problem exists today? Why is this important?

There are several issues about opening new tabs (https://github.com/mozilla-mobile/fenix/issues/13178), faster search (https://github.com/mozilla-mobile/fenix/issues/13052) or ui confussion (https://github.com/mozilla-mobile/fenix/issues/12774) among others. 
The current way to continue navigating with a new tab always requires to create the new tab first (except when long tapping a link in the current tab and selecting 'open in new tab') If the new tab needs to be related to the current one (either the same url or a similar one) the user must manually copy the url, create the new page, paste, edit the url and press enter.

The suggestion is to add a toggle in the searching page, or something similar:
![newtab_suggestion](https://user-images.githubusercontent.com/10616202/89946724-a47f6580-dc23-11ea-9da4-b9daf7eca621.jpg)

When the user toggles it, pressing enter or selecting an autocompleted url/search term will open that url in a new tab directly, preserving the current tab unmodified. Note that it needs to be a toggle, not a button, otherwise you won't be able to use it with the list of suggestions. Another option is to enable a long-tap menu, but that won't work with the search bar.

### Who will benefit from it?

- Users that want to duplicate the current tab: tap the search bar, click the toggle, press enter. (currently you need to copy the url, create a new tab, and paste&go it).
- Users that want to navigate to a related url but keep the current one, for example you opened the firefox changelog (https://www.mozilla.org/en-US/firefox/79.0/releasenotes/) and you want to compare it with the previous 78.0 version (wich involves having both tabs to be able to swap between them): tap the search bar, press the toggle, change the 79 with 78 in the url and press enter. (currently you need to copy the url, create a new tab, open the search bar, paste the url, edit it and press enter).
- Users that want a faster and explicit way to open an existing bookmark/suggestion in a new tab, instead of the current one: tap the toggle before clicking the suggestion when searching it (toggle off=open in current tab, toggle on=open in new tab). Also, this will be greatly improved if this issue was implemented https://github.com/mozilla-mobile/fenix/issues/12586 (show top sites when clicking the address bar).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4742)

**Comment by person808** [comment]
cc @brampitoyo since this looks like your area

**Comment by re-hub** [comment]
An icon (or text) next to the suggestion is also an option which also reduces the number of clicks and hand movement around the screen.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807729

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
