### ISSUE TITLE
Webpage view doesn't change when switching between tabs.

### ISSUE THREAD

**Issue by gwo0d** [mozilla-mobile/fenix#13505]
- I'm using Nightly 200811 06:01 (Build #2015757299)
- OS: OxygenOS 10.3.5
- Device: OnePlus 6T

I've noticed that when I press and hold on a link and tap "open in new tab", and then tap the "Switch" button at the bottom of the screen, the new tab opens and behaves as expected, but if I then use the tab switcher to change to my original tab, the URL at the top changes, but the page content remains that of the other tab.

**Comment by bjherbison** [comment]
I see what is likely a related issue with build #2015757491. Open in new tab, switch, then long-press on the icon with the number of tabs and select Close Tab. The closed tab is still displayed but scroll-up and scroll-down don't have any effect on the area of the tab displayed. If there were only two tabs then a second Close Tab returns to the home screen.

**Comment by liuche** [comment]
This sounds the same as #14459 for "old content" showing up
