### ISSUE TITLE
[Bug] Search suggestion doesn't work on added search engines 

### ISSUE THREAD

**Issue by zahraTavakkoli** [mozilla-mobile/fenix#13518]
## Steps to reproduce
1. Add a new search engine from "setting > search" for example YouTube
2. Select this new as default search engine
3. Type a text in address bar

### Expected behavior
Autocomplete suggests some words

### Actual behavior
Autocomplete doesn't work whereas it's active on initial list of search engines like Bing, Google etc.

![Screenshot_20200812-125408_Firefox Nightly](https://user-images.githubusercontent.com/46836760/90001103-4051b580-dca6-11ea-929c-77a88cc80ffd.jpg)
![Screenshot_20200812-125353_Firefox Nightly](https://user-images.githubusercontent.com/46836760/90001123-46479680-dca6-11ea-90ca-6ee23f0aec38.jpg)

### Device information

* Android device: Samsung A10s, Android 10
* Fenix version: 
Nightly 200811 06:01 (Build #2015757297)
AC: 54.0.20200810074539, 7a0bc5e43
GV: 81.0a1-20200808213325
AS: 61.0.10

**Comment by liuche** [comment]
Duping to #7866
