### ISSUE TITLE
An option to hide "Collection" recommendation. Someone need to do something and STOP this.

### ISSUE THREAD

**Issue by PranavBhattarai** [mozilla-mobile/fenix#13517]
I don't know why Firefox is highlighting, teaching, enforcing & prioritizing **Collection** everywhere in the browser like its a really one of the biggest thing in the browser.
I get it, it's a cool feature. I know how a add a website(s) in the Collection. But **WHY** we are focusing on this feature **TOO** much?

I think we better need to rename our browser: "Firefox Collection: The place we can collect websites"

Sarcasm aside, we need to go easy on **Collection**. A browser should just a be browser. Provide as many as a feature we can use while browsing the website(s), but that doesn't mean we need to **highlight them** everwhere.

OR else, give us an option to disable Collection from recommending. 

The newly revamped address bar and the way we see tabs were amazing. But ever since the new option of Collection arrived in place of the address bar, the browser wasn't user-friendly anymore, especially in one hand use case. I accidentally press "Save to Collection" accidentally more while switching tabs. Maybe I need time to get used to it. Or, maybe I never will get used to it. But the fact is there is a lot of Collection information out there in Firefox beta.

**Comment by AdityaGupta150** [comment]
I think you should narrow down to the problem, which i think is among the last lines.
There are already 3K+ issues, with many having the needs:triage label 😄 

Though see the linked issue, that is _regarding_ the same problem though, but is a later issue

**Comment by liuche** [comment]
Thank you for filing, and raising this question.

I'll bring this up in the Highlight Collections Usability UX issue #5652, please follow along there.
