### ISSUE TITLE
[Bug] Prefill arrow is displayed for the first search suggestion

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#13520]
## Steps to reproduce
1. Tap on the URL bar and search for something.
2. Check the first suggestion (user typing).

### Expected behavior
The prefill arrow **isn't** displayed for the first search suggestion.

### Actual behavior
 The prefill arrow **is** displayed for the first search suggestion.

### Device information
* Android device: all
* Fenix version: Nightly 8/12.

<img src="https://user-images.githubusercontent.com/58466444/90006018-cc60de80-dca0-11ea-9078-0b34065ca398.png" width="300" height="550" />

**Comment by violasong** [comment]
It looks like this is fixed. I'm closing the issue. Let me know if there are any remaining concerns. CC: @vesta0
