### ISSUE TITLE
[Bug] On Google Play in French for Firefox/Fenix Beta, screenshots and legends are mixed up

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#13521]
## Steps to reproduce
Go to Google Play in French and look for Firefox Beta

### Expected behavior
The screenshots and legends should match

### Actual behavior
Screenshots and legends do not match: for instance, the 2nd legend on the left below is about Private navigation, which corresponds to the 3rd screenshot actually :)

All screenshots should be checked.

![image](https://user-images.githubusercontent.com/218971/90008540-cb2db280-dc9c-11ea-999e-b93fb8891ecb.png)

**Comment by liuche** [comment]
Mei, can you take a look at this?

**Comment by peiying2** [comment]
I have checked with Mother Tongue. They looked at the project like this - translation and image creation, they only did once before the current one that was just wrapped up. On top of that, French and German were largely done by the staff (copy translation) and images were created by marketing graphic resources (internal or external). So this eliminate the possibility that the l10n vendor created this.

**Comment by mei-loo** [comment]
I have found the original files and working with EU team to review it holistically. will confirm when assets have been updated in the play store.

**Comment by mei-loo** [comment]
updated screenshots have been uploaded and published.
![Screen Shot 2020-08-19 at 3 34 29 PM](https://user-images.githubusercontent.com/68647577/90681790-faf73000-e231-11ea-88be-cebd6411cbe1.png)
