### ISSUE TITLE
FNX-4973 ⁃ [Bug] about:support shows product name as Fennec

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1353]
## Steps to reproduce
* Open about:support using the latest Fenix build. Observe the product name

### Expected behavior
* Product name would be Fenix

### Actual behavior
* Product name is Fennec

### Device information
* Android device: Pixel
* Fenix version: Build #10931209

**Comment by vesta0** [comment]
@cpeterso I believe this requires GV work. Please confirm.

**Comment by gaby2300** [comment]
I have the sane issue using a Sony Z3C with Android 6.1.0 and Fenix version 67.0-20190318154932

**Comment by cpeterso** [comment]
I filed a GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1542579

This issue doesn't seem like a P1 or something that needs to block Fenix MVP, especially considering Fenix will eventually become the new Fennec.

**Comment by cpeterso** [comment]
mheubusch suggests that we just use "GeckoView" as the Application Name.

**Comment by gaby2300** [comment]
I see the same in today's build using a Sony Z3C device with Android 6.0.1,
and an Android 7.1.2 tablet

**Comment by vesta0** [comment]
@cpeterso when can we expect this to be done?

**Comment by cpeterso** [comment]
The GV bug 1542579 is currently prioritized as post-MVP. `about:support` is seen by very few users. mheubusch told me that "GeckoView" is preferred, but "Fennec" is OK.

**Comment by cpeterso** [comment]
The GV bug will be fixed in tomorrow's GV 71 Nightly build.

https://bugzilla.mozilla.org/show_bug.cgi?id=1583336#c12

**Comment by sv-ohorvath** [comment]
> The GV bug 1542579 is currently prioritized as post-MVP. `about:support` is seen by very few users. mheubusch told me that "GeckoView" is preferred, but "Fennec" is OK.

Verified that the page now shows graphics & other info. Based on the above comment the product name will remain as "Fennec".
build: Nightly 10/8.
