### ISSUE TITLE
FNX-4974 ⁃ Transparent icon

### ISSUE THREAD

**Issue by DoggoOfSpeed** [mozilla-mobile/fenix#1354]
### Why/User Benefit/User Problem
So the logo will look nicer in dark mode

### What / Requirements
Icon's white part to be transparent

### Acceptance Criteria (how do I know when I’m done?)
When there Is no white background behind the logo
![Screenshot](https://user-images.githubusercontent.com/28051112/55507507-7a498b00-5660-11e9-9ed3-e2924a50ba38.jpg)UNITO-UNDERSCORE!20190403-221833!

![Screenshot](https://user-images.githubusercontent.com/28051112/55507376-33f42c00-5660-11e9-95a0-59f866138cf9.png)UNITO-UNDERSCORE!20190403-221833!

**Comment by boek** [comment]
Dup of #1184
