### ISSUE TITLE
FNX3-22138 ⁃ (visually?) Differentiate between suggestions from different awesomebar suggestion providers

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/fenix#13565]
Related #1368.

We will inevitably have different adapters providing very similar suggestions, but with different actions. For example, if a HackerNews tab is currently opened, and it's also in history, the session manager and history storage providers will both suggest the same URL, (possibly with different titles or other meta). In the UI, we need to clearly distinguish between these two items.

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

I was planning to use the "flags" in the suggestion for that. But yeah, that is completely unused currently.

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

boek If you know about any related Fenix issues or UX mocks/suggestions for that then please post them here. 😀

**Comment by data-sync-user** [comment]
➤ Jeff Boek commented:

pocmo The only issue that I am aware of is this, which has gotten de-prioritized for now?

https://github.com/mozilla-mobile/fenix/issues/3105

**Comment by data-sync-user** [comment]
➤ ekager commented:

More relevant issues and discussions about similar issues in the awesomebar:
https://github.com/mozilla-mobile/fenix/issues/2037
https://github.com/mozilla-mobile/fenix/issues/482

I think UX team (specifically @Verdi) could chime in here with more information about what we want here. I would love to get this going along with https://github.com/mozilla-mobile/android-components/issues/1367 , as we've added more suggestions it's really gotten messy and a bit of AC side merging/deduping could help a lot 😀

**Comment by Verdi** [comment]
> We will inevitably have different adapters providing very similar suggestions, but with different actions. For example, if a HackerNews tab is currently opened, and it's also in history, the session manager and history storage providers will both suggest the same URL, (possibly with different titles or other meta). In the UI, we need to clearly distinguish between these two items.

I don't think we should distinguish between them. I think we should show only one url and give you the switch-to-tab action.
