### ISSUE TITLE
FNX-4975 ⁃ [Bug] Singing into Firefox Sync leads to 404 page

### ISSUE THREAD

**Issue by pietroalbini** [mozilla-mobile/fenix#1358]
## Steps to reproduce
* Click the "Sign in" button in the settings
* Insert email, password and 2FA and sign in

### Expected behavior
Firefox Sync is enabled with my account.

### Actual behavior
A 404 page on accounts.firefox.com is shown.

### Device information
* Android device: BQ Aquaris U with LineageOS 14.1
* Fenix version: 1.0.1914

**Comment by vesta0** [comment]
Dup of #1315
