### ISSUE TITLE
FNX-4977 ⁃ [Bug] Loading history in library is really slow

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1360]
## Steps to reproduce
1. Go to Library>History
    1. Expected behavior
The history page loads very quickly
    1. Actual behavior
Getting a lag several seconds in order to load my history in the library view.

**Comment by grigoryk** [comment]
History page never loads for me, with constant GC and the app eventually is killed with an OutOfMemory.

**Comment by grigoryk** [comment]
Added some logging locally, and it seems like we're running away in the Kotlin stack - native places calls are quick and return without problems. I have 40k visits, and those are returned to the caller in `HistoryFragment` in about a second. It blows up while trying to process them.

**Comment by grigoryk** [comment]
Conclusion is that at the very least we need pagination in the History UI. cc @boek
