### ISSUE TITLE
[Bug] pwa sites from the top sites do not open after starting the browser

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#13663]
> From https://bugzilla.mozilla.org/show_bug.cgi?id=1653016

Steps to reproduce:

I'm trying to open a pwa site like twitter.

Actual results:

After starting the browser, pwa sites from the top sites do not open, for example, a site m.vk.com or mobile.twitter.com. To open them, i need to click "back" after the first unsuccessful attempt and try to open the site again. Tested on several devices with Android 9

Expected results:

After starting the browser, pwa sites from the top sites do not open.

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest **`Nightly Build 201106`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
