### ISSUE TITLE
FNX-4980 ⁃ [Bug] Address bar resets when putting Fenix on the background

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#1366]
## Steps to reproduce
* Type something on the Address bar but don't navigate anywhere
* Tap on the Android Home button to make Fenix go on the background
* Open Fenix again

### Expected behavior
* The address bar contains the text that you typed
Works on Fennec Nightly, Chrome

### Actual behavior
* The address bar is empty

### Device information
* Android device: Samsung S10e
* Fenix version: 1.0.1914

**Comment by ekager** [comment]
Caused by #1323

**Comment by kbrosnan** [comment]
Even with #1323 fixed this is still an issue.

**Comment by dector** [comment]
Will check it.

**Comment by dector** [comment]
This issue has two cases:

1. Activity stays the same. (_Fixed in #1366_).
2. Activity was recreated. (_Requires saving view state implementation_).

**Comment by sblatz** [comment]
@dector is working on this. I'll own making sure it gets landed! 

Currently blocked on: https://github.com/mozilla-mobile/android-components/pull/3187

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/8 build.
