### ISSUE TITLE
[Bug] Progressive Web App (PWA) in Firefox (Android) with Single Sign On (SSO)

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#13708]
> From https://bugzilla.mozilla.org/show_bug.cgi?id=1653425

Steps to reproduce:

My Progressive Web App needs to authenticate with Single Sign On server in a different path/domain:

My app path: https://xyz.app.com/app
SSO server path: https://sso.xyz.app.com/auth

When the PWA is installed with Firefox, when the app redirects to the SSO server path, the browser opens a new window, but when SSO server redirects to the app path again this new window is not closed.

Actual results:

Firefox opens a new window when my app redirects to SSO server path but don't close it when SSO server redirects to app path again.

Expected results:

Firefox must recognize the redirect to app main path and close the opened window like Google Chrome.

**Comment by redgumnfp** [comment]
👍🏼 Also experienced this today. Anyone found a workaround?

**Comment by ExposedCat** [comment]
Same problem with telegram auth
