### ISSUE TITLE
FNX-4985 ⁃ Always private tab mode

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#1373]
### Why/User Benefit/User Problem
Outside the app weblinks will open privately instead of regular tab. Would be benefical to users. Apps like Bromite for Android has a always incognito tab mode.

### What / Requirements
N/A

### Acceptance Criteria (how do I know when I’m done?)
N/A

**Comment by vesta0** [comment]
Thanks for the suggestion! We are tracking a similar feature here: #514
