### ISSUE TITLE
FNX-4986 ⁃ Strip libfenix.so before distribution?

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/fenix#1374]
@bbinto mentioned in slack that the size of the app-services dependencies for Fenix was surprisingly large, so I've been investigating what we can do to shrink it. One thing I noticed is that the Fenix `.apk` contains an unstripped `libfenix.so` while the other `.so` files are stripped.  From the `.apk` I installed from the private nightly channel just now and then pulled off of my phone to analyze:

```
rfk@pomelo:unzipped$ file lib/arm64-v8a/libfenix.so lib/arm64-v8a/libxul.so
lib/arm64-v8a/libfenix.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, with debug_info, not stripped 
lib/arm64-v8a/libxul.so:   ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ea000abd81186d35a4a1e695036cf99715214fb6, stripped 
```

So the app-services megazord `.so` is almost as big as libxul!

```
$ du -hs lib/arm64-v8a/libfenix.so lib/arm64-v8a/libxul.so
52M     lib/arm64-v8a/libfenix.so
85M     lib/arm64-v8a/libxul.so 
```

Stripping this `.so` and re-zipping the `.apk` produes about a 10M reduction in file size:

```
$ du -hs unstripped.apk stripped.apk
63M     unstripped.apk
53M     stripped.apk
```

It appears that we are deliberately not stripping the `libfenix.so` published in the Fenix megazord build, because it wasn't really clear what behavior our consumers would expect:

https://github.com/mozilla/application-services/blob/42d387bbd178281d09caf8a8ec26250f34d9e66c/megazords/fenix/android/build.gradle#L28-L33

Is this something that Fenix should be stripping as part of its build process, or something we should strip as part of publishing it?

**Comment by rfk** [comment]
If the debug symbols are useless to you and you'd prefer that we strip them before publishing, please open an issue on https://github.com/mozilla/application-services and we'll make the necessary change.  It looks straightforward enough on our side if you'd like to go that route.

For completeness, the size of the stripped library is a bit under 8M:

```
$ du -hs ./lib/arm64-v8a/libfenix.so
7.7M    ./lib/arm64-v8a/libfenix.so
```

Which may still qualify as "surprisingly large", so I'll keep investigating other improvements we can make here.

**Comment by rfk** [comment]
@thomcc pointed out in slack, that you're also shipping an unstripped `libjnidispatch.so`, which we wouldn't be able to strip on the app-services side.  The size saving there is much smaller though:

```
rfk@pomelo:fenix$ du -hs unstripped/lib/arm64-v8a/libjnidispatch.so
100K    unzipped/lib/arm64-v8a/libjnidispatch.so
rfk@pomelo:fenix$ du -hs stripped/lib/arm64-v8a/libjnidispatch.so
92K     stripped/lib/arm64-v8a/libjnidispatch.so
```

**Comment by rfk** [comment]
We just went ahead and did this on our side, ref https://github.com/mozilla/application-services/pull/915; the next app-services release should have much smaller native binaries.  Let us know if you were actually using the debug symbols in any way, we can easily add them back and move the stripping logic into the consumer build pipeline instead.

**Comment by ncalexan** [comment]
> @thomcc pointed out in slack, that you're also shipping an unstripped `libjnidispatch.so`, which we wouldn't be able to strip on the app-services side. The size saving there is much smaller though:
> 
> ```
> rfk@pomelo:fenix$ du -hs unstripped/lib/arm64-v8a/libjnidispatch.so
> 100K    unzipped/lib/arm64-v8a/libjnidispatch.so
> rfk@pomelo:fenix$ du -hs stripped/lib/arm64-v8a/libjnidispatch.so
> 92K     stripped/lib/arm64-v8a/libjnidispatch.so
> ```

We can strip it should we need to, but it's more convenient not to.
