### ISSUE TITLE
Sort synced tabs in Firefox Preview by the order in the desktop Firefox tablist

### ISSUE THREAD

**Issue by mystiquewolf** [mozilla-mobile/fenix#13757]
### What is the user problem or growth opportunity you want to see solved?
It would be a much better experience to see inside Firefox Preview the synced tabs in the order in which they appear on Firefox Desktop's tablist.
### How do you know that this problem exists today? Why is this important?
Because the synced tabs will not look like a complete mess, especially when you have hundreds of opened tabs (between 160 and 390)
### Who will benefit from it?
All users, especially the ones that keep many opened tabs at the same time

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4918)

**Comment by liuche** [comment]
@jonalmeida since you're working on synced tabs right now, what are we using to sort them now? Curious the amount of work this would be for a v2.

**Comment by jonalmeida** [comment]
We display what is given to us from Sync and that _should_ match with what desktop is doing. 

That said we have a bug to store the `lastAccess` property from mobile that is submitted to Sync and is probably the cause of what this issue is.

@liuche we can turn this into a bug instead of a feature and link it to https://github.com/mozilla-mobile/android-components/issues/7476.

**Comment by mystiquewolf** [comment]
Is it currently sorted by order of recent switch to/interaction? Seems so but i'm not a Firefox developer.

**Comment by mystiquewolf** [comment]
Not stale. Looks like it is sorted now by last used, but there should also be the option to sort by order of tabs in the desktop tabbar.

**Comment by thebiffman** [comment]
In my mind the most obvious way to display synced tabs is to group the tabs by window and list them in the same order that they appear in that browser. If its not possible with grouping, at the least the tabs should be in the same order on both ends, to make it easier to find the correct tab. 

Right now they dont seem to be sorted at all. I see tabs in the top that I havent touched in several days.... If sorting by last accessed is the only way, then that is at least better than the current way it works.

**Comment by gta0anu** [comment]
Seconding this. Tabs needs to be in same order as they appear in browser for one desktop to another. It makes working with these tabs easier. We remember the position of certain tabs instead of every-time finding them.

**Comment by Kemeros** [comment]
I just came across this bug after deciding to activate the Sync feature and got quite confused until i read here that the tab list is sorted by last used and not the actual tab order. This is counterintuitive, i use my tabs in a specific order regardless of when i last used them.

If possible, could this maybe be a setting or changed to tab order? I believe the order is more important than the last used date.

Regards.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810786

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
