### ISSUE TITLE
FNX-4987 ⁃ Suppress history suggestions in the awesomebar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1375]
As a user, I want to change default awesomebar settings so that Fenix does not display my browsing history so that my history is not visible in this prominent spot.

### Acceptance criteria 
-I can choose to suppress history in awesomebar suggestions. 
-I do not see the addresses of sites I've previously visited, when I type an exact match on part of the URL or part of the page <title> in the awesome bar.

**Comment by topotropic** [comment]
https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/350752849_Settings_-_Search
Rename "Search engine" to "Search" in settings and add a toggle to the search section labeled "Show visited sites"

**Comment by kbrosnan** [comment]
How should this interact with Bookmarks?

**Comment by topotropic** [comment]
Yes, good point. Assuming privacy concerned people want to suppress both history and bookmarks, we could combine it to "Show visited sites and bookmarks".

**Comment by vesta0** [comment]
@topotropic do we have mocks for this?

**Comment by mheubusch** [comment]
@topotropic @lime124 we do not currently display bookmarks in search suggestions, and the request above to suppress them has triggered another issue to add bookmarks.  OK if we add bookmarks and allow users to suppress them to the search bar post MVP

**Comment by lime124** [comment]
i'm good with that

**Comment by ekager** [comment]
This setting now works for visited sites and bookmarks and the toggle should suppress both types of suggestions. Right now it's a bit difficult to tell which type of suggestion you are seeing, but I think there's an AC issue for that

**Comment by sv-ohorvath** [comment]
Verified this is fixed, there are no suggestions based on history/bookmarks. But, the autocomplete feature can still give you away. I'll file a new issue for that.
