### ISSUE TITLE
FNX3-22306 ⁃ Run Python code tools in automation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/fenix#13750]
We have a little bit of Python code for our automation tasks in our repo. There may be more in the future and it would be nice to run some tools over those too. @mastizada recommended to look at flake8 and pylint.

* http://flake8.pycqa.org/en/latest/
* https://www.pylint.org/

**Comment by mastizada** [comment]
I'll be happy to help maintaining python code in this repo just like I did for Firefox Focus (RIP? :D).

**Comment by mastizada** [comment]
@liuche do you need any help with python in this repo?
