### ISSUE TITLE
[Bug] In edit bookmarks, the x button dissapears after pressing backspace

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13759]
## Steps to reproduce
Save a bookmark and then edit it
click in the Name section or the URL, press backspace on the keyboard

### Expected behavior
The x icon does not disappear  

### Actual behavior
The x icon disappears but it still works if you click in that area

### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by darren-finch** [comment]
I see the same issue on my own phone. I have a Google Pixel 3.

I will open a pull request for the fix.

**Comment by person808** [comment]
Assigning you @darren-finch :)

**Comment by darren-finch** [comment]
> Assigning you @darren-finch :)

Thank you! This is my first contribution to open source, so it may take some time. Specifically I can't figure out how to run the app. It's giving me this error. I read through the README and made sure I was building the debug variant, but it won't launch the initial activity.

![error](https://user-images.githubusercontent.com/31454851/90167550-68521f00-dd61-11ea-86d3-2fa341990d64.png)

**Comment by person808** [comment]
Ah yes that is annoying. You'll want to add a new configuration that starts HomeActivity.

<img width="1032" alt="Screen Shot 2020-08-13 at 10 39 03 AM" src="https://user-images.githubusercontent.com/6396431/90167906-3933b180-dd51-11ea-8074-05b6f0d19b3f.png">

If you have anymore questions you can ask them here, but I'm an intern thats leaving soon so I may not be able to reply as much. Our element chat room is also a good place to ask for help (https://chat.mozilla.org/#/room/#fenix:mozilla.org)

**Comment by person808** [comment]
Also sometimes I have to open the Edit configurations dialog and close it otherwise Android Studio refuses to run my HomeActivity configuration 🤷

**Comment by darren-finch** [comment]
I'll go ahead and join the chat room, and thanks for your help, it worked!

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly build 8/19** with **Google Pixel 4 XL (11).**
