### ISSUE TITLE
[Bug] ArrayIteratorKt in throwNpe in BrowserToolbar

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#13761]
Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/9366156/?query=is%3Aunresolved%20ArrayIteratorKt

This has been around for a while, but seeing an uptick in 80.0.0-beta build.

```
kotlin.jvm.internal.ArrayIteratorKt in throwNpe at line 1
org.mozilla.fenix.browser.BaseBrowserFragment in getBrowserToolbarView at line 1
org.mozilla.fenix.browser.BaseBrowserFragment in onAccessibilityStateChanged at line 1
android.view.accessibility.AccessibilityManager in handleNotifyAccessibilityStateChanged at line 645
android.view.accessibility.AccessibilityManager in access$000 at line 68
android.view.accessibility.AccessibilityManager$MyHandler in handleMessage at line 691
```

**Comment by liuche** [comment]
Do you know if this related to the browser toolbar consolidation changes that we made recently @person808 ?

**Comment by person808** [comment]
We haven't made any toolbar changes that I'm aware of.

**Comment by liuche** [comment]
also a similar crash here on Nightly: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/9004565/?query=is%3Aunresolved%20ArrayIteratorKt

**Comment by liuche** [comment]
when you get back @mcarare could you take a look at this?

**Comment by kbrosnan** [comment]
This looks to be several crashes grouped under a common signature. See https://crash-stats.mozilla.org/search/?signature=~throwNpe&product=Fenix&_facets=signature&_facets=java_stack_trace&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-java_stack_trace

* bz-1651438 
* #12424
* https://github.com/mozilla-mobile/android-components/issues/7944

**Comment by mcarare** [comment]
@liuche I could try and add a check for that call, but IMO the main issue is with how we handle the reference to `browserToolbarView`, as we can identify multiple crashes cause by the `getBrowserToolbarView` call.

**Comment by mcarare** [comment]
@liuche this change https://github.com/mozilla-mobile/fenix/pull/13880 should avoid the crash, but I will also keep an eye on this crash signature after the fix is merged and "live".

**Comment by liuche** [comment]
Thanks - this change makes sense, that we want this once the view is created, not always on start.

**Comment by liuche** [comment]
Going to uplift this to the 80.0.1 beta channel.

**Comment by liuche** [comment]
Hey @mcarare we'd like to get this uplifted to the 80.0.0 release - could you open a PR against the `releases/v80.0.1` branch? It wasn't a clean uplift.

**Comment by mcarare** [comment]
@liuche here it is: https://github.com/mozilla-mobile/fenix/pull/13965.

**Comment by liuche** [comment]
I think this is okay to close, took a look at the Sentry logs and they seem to be decreasing a lot on beta.
