### ISSUE TITLE
Add voice search to new search experience

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#13766]
Parent #13052

**Comment by Diana-Rus** [comment]
Hi, verified as fixed on Nightly 8/31 with:
- Google Pixel 3XL (Android 9)
- Samsung Galaxy S9 (Android 8)
- Sony Xperia Z5 (Android 7)

Notes:
- The voice search/mic is correctly displayed in the navigation bar for the new search experience
- The voice search works correctly
- "Show voice search" works correctly on this implementation

<details closed><summary>Private mode- Screen</summary>

![Screenshot_20200831-165741](https://user-images.githubusercontent.com/49859863/91728765-3982d800-ebac-11ea-9129-48efa1d1a52a.png)
</details>

<details closed><summary>Normal mode - Screen</summary>

![Screenshot_20200831-165712](https://user-images.githubusercontent.com/49859863/91728778-3daef580-ebac-11ea-8126-206c9f561020.png)
</details>
