### ISSUE TITLE
[Bug] full screen controls broken, video sized incorrectly on south park cc

### ISSUE THREAD

**Issue by Balachandarsmr** [mozilla-mobile/fenix#13773]
Filed GV https://bugzilla.mozilla.org/show_bug.cgi?id=1659761 to get more information

## Steps to reproduce
Go to https://southpark.cc.com/full-episodes
Play video in full screen.
### Expected behavior
Video should be play in full screen immersive mode hiding android navigation bar.

### Actual behavior
In landscape Full screen mode there's a white bar in bottom and side of video. Video isn't in immersive landscape mode.

### Device information

* Android device: MI A2
* Fenix version: 80.0.0-beta.6
After entering Full screen on south park cc site video seek bar, subtitle button, Full screen switch button is not responding. Video isn't in full screen. There is white bar on side and bottom. 
[Watch full screen video playback bug](http://next.2yxa.mobi/import/2yxa_ru_south_park_cc_bug_imp453224.mp4) 
![Screenshot_20200813_080501](https://user-images.githubusercontent.com/29444683/90090197-f357f880-dd12-11ea-8a63-1d80b4565e9b.jpg)
Firefox 79 does not has this issue.

**Comment by liuche** [comment]
I can repro this on the latest Nightly, but doesn't happen on Youtube.com. Do we have any big Media changes recently, that could be affecting this?

**Comment by liuche** [comment]
This should be fixed in the next nightly.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200831`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200831-103921](https://user-images.githubusercontent.com/51314259/91695632-21dd2c80-eb77-11ea-88f7-2111daa5ee92.gif)

**Comment by linsui** [comment]
Full screen video broken again on nightly.

**Comment by AndiAJ** [comment]
Hi @linsui , could you please indicate the website ?

**Comment by Balachandarsmr** [comment]
Full screen playback working perfectly on latest nightly

**Comment by linsui** [comment]
Sure. https://www.bilibili.com/bangumi/play/ep71958 in desktop mode.
