### ISSUE TITLE
[Bug] Tab tray can be dragged into janky bottom-third-of-the-screen position

### ISSUE THREAD

**Issue by cartr** [mozilla-mobile/fenix#13777]
## Steps to reproduce

1. Open the tab tray.
2. Drag the drag handle to the bottom of the screen, then lift your finger off while slowly dragging up.

### Expected behavior

Either the tab tray closes or the new tab button stays visible.

### Actual behavior

The tab tray snaps to the bottom third of the screen, and the new tab button vanishes. Screen recording attached: 

<details>
<summary>GIF</summary>

![2020-08-12-22-25-47 2020-08-12 22_38_18](https://user-images.githubusercontent.com/5241813/90098205-8d587a80-dcec-11ea-9408-368f73b078b6.gif)

</details>

(The GIF also demonstrates #13776)
### Device information

* Android device: ASUS ZenFone 6
* Fenix version: Nightly 200812 06:01 (Build #2015757491)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201105`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201105-092753](https://user-images.githubusercontent.com/51314259/98211163-4c1de280-1f4a-11eb-8944-2be0523d4256.gif)
