### ISSUE TITLE
[Bug] Closing a backgrounded tab causes new tab page UI state to reset for no reason

### ISSUE THREAD

**Issue by cartr** [mozilla-mobile/fenix#13778]
## Steps to reproduce

1. Open a tab
2. Switch back to the new tab page
3. Scroll the new tab page and open a Collection accordion
4. Open the tab tray and close the backgrounded tab

### Expected behavior

The new tab page stays scrolled, and the accordion stays open.

### Actual behavior

The new tab page "resets" -- it jumps back to its default scroll position, and the accordion closes.

### Device information

* Android device: ASUS ZenFone 6
* Fenix version: Nightly 200812 06:01 (Build #2015757491)

**Comment by s-ankur** [comment]
Would be solved by #12310

**Comment by liuche** [comment]
Yeah let's dupe this to #12310
