### ISSUE TITLE
[Bug] New tab page is scrollable even when there is no additional content to be revealed by scrolling

### ISSUE THREAD

**Issue by cartr** [mozilla-mobile/fenix#13779]
## Steps to reproduce

1. Open a fresh install of Fenix, with no collections or anything
2. Observe that all of the new tab fits on the screen, with plenty of empty space at the bottom
3. Attempt to scroll the new tab page

### Expected behavior

The new tab page doesn't scroll.

### Actual behavior

The new tab page can (pointlessly) scroll just far enough to move the browser logo off the screen.

### Device information

* Android device: ASUS ZenFone 6
* Fenix version: Nightly 200812 06:01 (Build #2015757491)

**Comment by s-ankur** [comment]
Related  #8545

**Comment by liuche** [comment]
Thank you for duping!
