### ISSUE TITLE
Automatically show GV version of repo in readme (e.g. badge)

### ISSUE THREAD

**Issue by Pomax** [mozilla-mobile/fenix#13770]
The README.md current does not explain which browser/engine versions the master branch mapped to. Especially for folks who want to check whether or not they're up to date(ish) or a versioning-decade behind.

**Comment by liuche** [comment]
Does the date of the Firefox About page help with that? (Settings > About) That page in the app lists the build date so if that date is close to today, then you are as up to date as the the builds can be.

The geckoview versions are automatically pulled into from AC, which are listed here: https://github.com/mozilla-mobile/android-components/blob/master/buildSrc/src/main/java/Gecko.kt

But if there's a pipeline problem, those could also be out of date.

The Gecko versions are also of the format YYYYMMDD

**Comment by Pomax** [comment]
No I mean literally here, on the repo, for the master branch (using a ribbon similar to "CI passes", "npm version:" etc. buttong)

That way it's clear to folks what they'll end up with, without having to first run a complete build and then sideload the resulting app.

**Comment by liuche** [comment]
At the moment, we don't have the releng resourcesto make a badge that checks what the AC/GV version is to badge it (the dependencies are pulled in from AC each night), but as a tiny workaround we could add a link to the `Gecko.kt` file in the AC repo in the README, if you think that would help.

**Comment by Pomax** [comment]
Does the version change constantly? If not, it might make even more sense to just update the README.md when a new version of gecko is released, as text that `[links to the file](https://github.com/mozilla-mobile/fenix/blob/.....)`?

**Comment by liuche** [comment]
The GV version changes every night or so, hence the "Nightly". A nightly version of the app is also published to the Firefox Nightly Google Play Store app.

**Comment by Pomax** [comment]
right but that doesn't affect the folks who use the "normal" fenix, does it? Their version wouldn't be updating quite that fast?

**Comment by liuche** [comment]
The repo is not tracking Release fenix, it's the Nightly codebase. I think I understand what you're asking, and I'd prefer an automation approach bc otherwise it's very manual and a lot of work for a small team, so if you want to continue this discussion, please drop by the #fenix matrix channel in the readme.
