### ISSUE TITLE
QR scan zoom

### ISSUE THREAD

**Issue by Tithen** [mozilla-mobile/fenix#13771]
Pinch to zoom feature should be implemented to enable scanning QR codes from a distance

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4939)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807386

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
