### ISSUE TITLE
Add websites to collections in Private Tab

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#13787]
### What is the user problem or growth opportunity you want to see solved?
Private tabs are used to browse on websites and let the browser remember nothing of them. However, if you actually find a website that is interesting, users lack the option to add that tab to their collection. (I hope 'collection' is what it's called in english).

### How do you know that this problem exists today?
Add the same options that regular tabs have to add websites to the collections.
**How?**
Copy the regular-tab-functionalities to the private tabs. (such as, in a private-tab-overview, let the user long-press a tab, and then save it in a collection.)

### Who will benefit from it?
People who use private tabs for regular browsing, to make the browser forget everything once they close it. 
People who don't want to copy&paste an URL from a private tab into a regular tab, just to add something into their collection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4956)

**Comment by s-ankur** [comment]
In their current iteration, collections remember the entire tab history of the tab that you saved. By allowing collections to be saved from Private Mode, you will leak history from private browsing even after it is closed, which is unacceptable from a privacy standpoint. So for this feature to be implemented one of these things would have to happen

1. Collections work more like bookmarks, and do not have history attached to them
2. Private mode collections work differently than normal mode collections, acting as bookmarks instead of collections

**Comment by Glitchy-Tozier** [comment]
I see, that really is a problem.
1. It's a little weird anyways that the history gets saved. (just as the #13793 you mentioned)
2. If no.1 doesn't get changed, private tabs could be saved without their history. (I'm guessing, that's what you meant anyways.) You would probably also need to do something with the cookies if they, too, get saved.

(Honestly, I'm not even completely sure where the difference is between collections and bookmarks.... except collections seem to be WAY more intuitive. It's quite a shock if you open the menu and, instead of choosing the star on the bottom, you click on the "bookmarks/favorites" option somewhere near the top. I still don't know what it does or why there are things that have similar names but do completely different things. (I'm comparing the bookmark-star and the bookmark-menu-option, not bookmarks with collections))

**Comment by otede** [comment]
As I already wrote in https://github.com/mozilla-mobile/fenix/issues/14465
I strongly disagree!
If you don't actively perform several steps to actually save the private tabs to a collection the feature literally does not affect you! You might as well opt for removing "Add to bookmarks" for private tabs.

To put it differently, a person choosing to save a bunch of confidential tabs to an "in your face" (in the UI) collection shouldn't expect *anything* from collections as far as privacy goes.

**Comment by otede** [comment]
> (Honestly, I'm not even completely sure where the difference is between collections and bookmarks.... except collections seem to be WAY more intuitive. It's quite a shock if you open the menu and, instead of choosing the star on the bottom, you click on the "bookmarks/favorites" option somewhere near the top. I still don't know what it does or why there are things that have similar names but do completely different things. (I'm comparing the bookmark-star and the bookmark-menu-option, not bookmarks with collections))
With the current miserable state of bookmarks implementation Collections save the day :)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812744

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
