### ISSUE TITLE
[Feature] Move websites inbetween private & regular tabs.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#13788]
### What is the user problem or growth opportunity you want to see solved?
I noticed the potential of this feature through #13787 ... which is only somewhat related to this.
It's really handy being able to decide to turn a private tab into a regular one. 

- Maybe the user wants to not loose this tab after restarting the phone/closing Fenix. 

- Maybe there are add-ons that aren't activated in private tabs, which the user still wants to use on that one particular Webiste.

- Maybe the user wants to visit a website in this add-on-less enviroment.

- Maybe #13787 doesn't get implemented.

- .....

Point being, it's a good feature to have.

### How to implement this feature:
Option number 2 might be somewhat novel, but it's a very elegant solution to the problem.

1. In the website-menu, add the option "move to private/regular tab".
2. Currently, when on the open-tab-overview, swiping a tab into either direction will close&delete it. I propose this:
In the current app, the regular-tab-overview is on the left side and the private-tab-overview is on the right side. This sets up for the following feature: swiping a tab towards the other tab-overview could move it there.
**For example:** If we have a private tab, we could still swipe to the right to delete it. However, swiping to the left will move it to the regular-tab-side of Fenix.

**Comment by Glitchy-Tozier** [comment]
Unfortunately, I don't know enogh about browsers to suggest how to implement this coding-wise.
The tab/website will probably need to be reloaded. Cookies might need to be moved/deleted.

**Comment by liuche** [comment]
Dupe to #10132
