### ISSUE TITLE
[Bug] New search experience PBM wrong color

### ISSUE THREAD

**Issue by Dunexus** [mozilla-mobile/fenix#13784]
## Steps to reproduce
- Enable new search experience
- Open new PBM tab

### Expected behavior
The color of the search bar and suggestions panel is purple.

### Actual behavior
The color of the search bar and suggestions panel is black (or white depending on Fenix theme).

![Screenshot_20200813-101019__01](https://user-images.githubusercontent.com/13906248/90110498-9d547680-dd4d-11ea-80cb-7e1c116e681d.jpg)
![Screenshot_20200813-101028__01](https://user-images.githubusercontent.com/13906248/90110508-a2b1c100-dd4d-11ea-9a51-7680cf69c9c5.jpg)

**Comment by s-ankur** [comment]
related #13423

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200910 06:07 (Build #2015763059) GV 82.0a1 from9/10 with Motorola Moto G6 (Android 8) and Pixel 2 (Android 9).
I will remove the qa:needed label and close this issue.
