### ISSUE TITLE
[Bug][LeakCanary] several leaks when using private mode

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#13785]
/cc @mcomella 

### Steps to reproduce

1. switch to private mode
2. open a private tab
3. switch to a regular tab via tab switcher or close the tab via private mode notifcation

### Expected behavior

No leak.

### Actual behavior

There are different leaks:

┬───
│ GC Root: Global variable in native code
│
├─ org.mozilla.geckoview.GeckoEditable instance
│    Leaking: UNKNOWN
│    ↓ GeckoEditable.mListener
│                    ~~~~~~~~~
├─ org.mozilla.geckoview.GeckoInputConnection instance
│    Leaking: UNKNOWN
│    ↓ GeckoInputConnection.mSession
│                           ~~~~~~~~
├─ org.mozilla.geckoview.GeckoSession instance
│    Leaking: UNKNOWN
│    ↓ GeckoSession.mPromptDelegate
│                   ~~~~~~~~~~~~~~~
├─ mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate instance
│    Leaking: UNKNOWN
│    ↓ GeckoPromptDelegate.geckoEngineSession
│                          ~~~~~~~~~~~~~~~~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineSession instance
│    Leaking: UNKNOWN
│    ↓ GeckoEngineSession.delegate
│                         ~~~~~~~~
├─ mozilla.components.support.base.observer.ObserverRegistry instance
│    Leaking: UNKNOWN
│    ↓ ObserverRegistry.observers
│                       ~~~~~~~~~
├─ java.util.LinkedHashSet instance
│    Leaking: UNKNOWN
│    ↓ LinkedHashSet.map
│                    ~~~
├─ java.util.LinkedHashMap instance
│    Leaking: UNKNOWN
│    ↓ LinkedHashMap.table
│                    ~~~~~
├─ java.util.HashMap$Node[] array
│    Leaking: UNKNOWN
│    ↓ HashMap$Node[].[1]
│                     ~~~
├─ java.util.LinkedHashMap$LinkedHashMapEntry instance
│    Leaking: UNKNOWN
│    ↓ LinkedHashMap$LinkedHashMapEntry.key
│                                       ~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineView$observer$1 instance
│    Leaking: UNKNOWN
│    Anonymous class implementing mozilla.components.concept.engine.EngineSession$Observer
│    ↓ GeckoEngineView$observer$1.this$0
│                                 ~~~~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineView instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.engineView
│    View.mWindowAttachCount = 1
│    ↓ GeckoEngineView.mContext
╰→ org.mozilla.fenix.HomeActivity instance
​     Leaking: YES (ObjectWatcher was watching this because org.mozilla.fenix.HomeActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = ace8097b-6d02-4349-91f0-c3606daab72c
​     watchDurationMillis = 5213
​     retainedDurationMillis = 210

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 9081 ms

===

┬───
│ GC Root: Global variable in native code
│
├─ org.mozilla.geckoview.GeckoEditable instance
│    Leaking: UNKNOWN
│    ↓ GeckoEditable.mListener
│                    ~~~~~~~~~
├─ org.mozilla.geckoview.GeckoInputConnection instance
│    Leaking: UNKNOWN
│    ↓ GeckoInputConnection.mTargetView
│                           ~~~~~~~~~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineView$currentGeckoView$1 instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    Anonymous subclass of mozilla.components.browser.engine.gecko.NestedGeckoView
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    ↓ GeckoEngineView$currentGeckoView$1.$context
├─ org.mozilla.fenix.HomeActivity instance
│    Leaking: YES (GeckoEngineView$currentGeckoView$1↑ is leaking and Activity#mDestroyed is true)
│    ↓ HomeActivity.mFragments
├─ androidx.fragment.app.FragmentController instance
│    Leaking: YES (HomeActivity↑ is leaking)
│    ↓ FragmentController.mHost
├─ androidx.fragment.app.FragmentActivity$HostCallbacks instance
│    Leaking: YES (HomeActivity↑ is leaking)
│    ↓ FragmentActivity$HostCallbacks.mFragmentManager
├─ androidx.fragment.app.FragmentManagerImpl instance
│    Leaking: YES (HomeActivity↑ is leaking)
│    ↓ FragmentManagerImpl.mNonConfig
╰→ androidx.fragment.app.FragmentManagerViewModel instance
​     Leaking: YES (ObjectWatcher was watching this because androidx.fragment.app.FragmentManagerViewModel received ViewModel#onCleared() callback)
​     key = cc24ecbb-8744-4aa6-908f-7458f30adfca
​     watchDurationMillis = 4961
​     retainedDurationMillis = -52

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 10110 ms

===

┬───
│ GC Root: Global variable in native code
│
├─ org.mozilla.geckoview.GeckoEditable instance
│    Leaking: UNKNOWN
│    ↓ GeckoEditable.mListener
│                    ~~~~~~~~~
├─ org.mozilla.geckoview.GeckoInputConnection instance
│    Leaking: UNKNOWN
│    ↓ GeckoInputConnection.mTargetView
│                           ~~~~~~~~~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineView$currentGeckoView$1 instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    Anonymous subclass of mozilla.components.browser.engine.gecko.NestedGeckoView
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    ↓ GeckoEngineView$currentGeckoView$1.mParent
├─ mozilla.components.browser.engine.gecko.GeckoEngineView instance
│    Leaking: YES (GeckoEngineView$currentGeckoView$1↑ is leaking and View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.engineView
│    View.mWindowAttachCount = 1
│    ↓ GeckoEngineView.mParent
├─ androidx.swiperefreshlayout.widget.SwipeRefreshLayout instance
│    Leaking: YES (GeckoEngineView↑ is leaking and View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.swipeRefresh
│    View.mWindowAttachCount = 1
│    ↓ SwipeRefreshLayout.mParent
├─ androidx.coordinatorlayout.widget.CoordinatorLayout instance
│    Leaking: YES (SwipeRefreshLayout↑ is leaking and View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.browserLayout
│    View.mWindowAttachCount = 1
│    ↓ CoordinatorLayout.mParent
├─ org.mozilla.fenix.browser.SwipeGestureLayout instance
│    Leaking: YES (CoordinatorLayout↑ is leaking and View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is null
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.gestureLayout
│    View.mWindowAttachCount = 1
│    ↓ SwipeGestureLayout.mKeyedTags
├─ android.util.SparseArray instance
│    Leaking: YES (SwipeGestureLayout↑ is leaking)
│    ↓ SparseArray.mValues
├─ java.lang.Object[] array
│    Leaking: YES (SwipeGestureLayout↑ is leaking)
│    ↓ Object[].[0]
├─ org.mozilla.fenix.browser.BrowserFragment instance
│    Leaking: YES (SwipeGestureLayout↑ is leaking and Fragment#mFragmentManager is null)
│    ↓ BrowserFragment.sharedViewModel$delegate
├─ androidx.lifecycle.ViewModelLazy instance
│    Leaking: YES (BrowserFragment↑ is leaking)
│    ↓ ViewModelLazy.cached
╰→ org.mozilla.fenix.home.SharedViewModel instance
​     Leaking: YES (ObjectWatcher was watching this because org.mozilla.fenix.home.SharedViewModel received ViewModel#onCleared() callback)
​     key = 49084a2e-5e05-405d-a058-7e37d02be7b1
​     watchDurationMillis = 4961
​     retainedDurationMillis = -52

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 10110 ms

===

┬───
│ GC Root: Global variable in native code
│
├─ org.mozilla.geckoview.GeckoEditable instance
│    Leaking: UNKNOWN
│    ↓ GeckoEditable.mListener
│                    ~~~~~~~~~
├─ org.mozilla.geckoview.GeckoInputConnection instance
│    Leaking: UNKNOWN
│    ↓ GeckoInputConnection.mTargetView
│                           ~~~~~~~~~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineView$currentGeckoView$1 instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    Anonymous subclass of mozilla.components.browser.engine.gecko.NestedGeckoView
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    ↓ GeckoEngineView$currentGeckoView$1.mParent
├─ mozilla.components.browser.engine.gecko.GeckoEngineView instance
│    Leaking: YES (GeckoEngineView$currentGeckoView$1↑ is leaking and View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.engineView
│    View.mWindowAttachCount = 1
│    ↓ GeckoEngineView.mParent
├─ androidx.swiperefreshlayout.widget.SwipeRefreshLayout instance
│    Leaking: YES (GeckoEngineView↑ is leaking and View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.swipeRefresh
│    View.mWindowAttachCount = 1
│    ↓ SwipeRefreshLayout.mParent
├─ androidx.coordinatorlayout.widget.CoordinatorLayout instance
│    Leaking: YES (SwipeRefreshLayout↑ is leaking and View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.browserLayout
│    View.mWindowAttachCount = 1
│    ↓ CoordinatorLayout.mParent
╰→ org.mozilla.fenix.browser.SwipeGestureLayout instance
​     Leaking: YES (ObjectWatcher was watching this because org.mozilla.fenix.browser.BrowserFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks) and View.mContext references a destroyed activity)
​     key = f50ba453-5d15-4e7b-888b-0795ff613405
​     watchDurationMillis = 4130
​     retainedDurationMillis = -1
​     mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
​     View#mParent is null
​     View#mAttachInfo is null (view detached)
​     View.mID = R.id.gestureLayout
​     View.mWindowAttachCount = 1

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 9830 ms

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision c52e4fd9f5f157cb5c5da32f7a623c861f68db7b

**Comment by csadilek** [comment]
We fixed two leaks in A-C today triggered by these STR: https://github.com/mozilla-mobile/android-components/issues/9022 and https://github.com/mozilla-mobile/android-components/issues/9017 

There's one left involving the `GeckoEditable.mListener` which I filed in GV as we need help investigating what could cause this: https://bugzilla.mozilla.org/show_bug.cgi?id=1678425

**Comment by csadilek** [comment]
Thanks for filing! We fixed all known leaks in A-C and Fenix triggered by this. Closing as we have a GV ticket for the one remaining.
