### ISSUE TITLE
[Bug] Android toolbar uses white background even when the icons are white too

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#13795]
## Steps to reproduce
Start Firefox (Fenix)
Look at the bottom Android toolbar. Light background and light button.

### Expected behavior
Either dark background and light buttons, or light background and light buttons.

### Device information

* Android device: Honor 7
* Fenix version: (this is on my father's phone, and looks like he got just updated from Firefox to Fenix. Don't have access to it right now)

**Comment by person808** [comment]
Hi, what Android version is this on? This tends to be important for these kinds of bugs. Thanks!

**Comment by smaug----** [comment]
Android 6

**Comment by hwinnemoe** [comment]
Duplicate of #12058

**Comment by ekager** [comment]
According to this comment https://github.com/mozilla-mobile/fenix/issues/12058#issuecomment-671210366 it sounds like it should be fixed in the next release
