### ISSUE TITLE
Display bug in youtube desktop view

### ISSUE THREAD

**Issue by ShoEnRyu** [mozilla-mobile/fenix#13790]
When you open Youtube in desktop browser view and switch to landscape mode, it offsets the video to the top right corner and white in the remaining spaces. Controls like seek, full-screen, etc. trigger in the normal locations as if there's no offset even of the controls show offset as well. Noticed this on both firefox beta and nightly (android).
![Screenshot_2020-08-13-14-47-38-403_org mozilla firefox_beta](https://user-images.githubusercontent.com/57486806/90117449-8ecd8580-dd74-11ea-814a-b929019c70a7.jpg)

**Comment by liuche** [comment]
This is the same as #13773

**Comment by liuche** [comment]
We've also filed this GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1659761
