### ISSUE TITLE
Collections keep history??

### ISSUE THREAD

**Issue by TrianguloY** [mozilla-mobile/fenix#13793]
After reading this comment https://github.com/mozilla-mobile/fenix/issues/13787#issuecomment-673370779 I was shocked. Collections keeping history? I quickly tested it, and it's true. When saving a tab into a collection, all the past and even forward history are saved, so when you open that tab from the collection, you can go back and even forward to the same pages. 

As far as I know, this feature isn't explained anywhere. Maybe I'm mistaken and it is, but I couldn't find it nor in the app, nor here in Github, nor on firefox support (https://support.mozilla.org/en-US/kb/collections-firefox) nor on Google. Is this supposed to change in the future?

Collections are often criticised because they seem like less-powerful bookmarks, but this little feature makes them have at least a differentiated factor to consider having both. Are any other properties apart from the history preserved?

### Feature request
Unless this will be removed in future updates, you should explain this feature (collections keep history) when describing collections, make the world know why they aren't bookmarks.

Extra: Once you open a tab from a collection, the history is restored but further changes to it (navigating from the newly created tab) are not updated in the collection. This seems like the collections are locked, or read only; could it be possible to unlock them so they behave more like sessions? I think there are already some requests about this.

**Comment by s-ankur** [comment]
See also #10417, #11506

**Comment by TrianguloY** [comment]
Thanks for those links. The second one does mention the keep history feature (https://github.com/mozilla-mobile/fenix/issues/11506#issuecomment-643264112) and on the first one there is a response surprised of this discovery (https://github.com/mozilla-mobile/fenix/issues/10417#issuecomment-645804219), but the rest of the discussion and initial issues are about the cached content of the opened page, and although there are other comments that seem to explain this, they simply say 'tab state' which is not clear what 'state' it is referring to: current url (yes, obvious), current cookies (?), history (yes, not obvious), input text and user modifications (?), current scroll position (apparently yes).

Perhaps the mayority of users already know about this, and I simply didn't know, but my impression is that it is the opposite.

**Comment by yoasif** [comment]
Collections are like saved sessions (a concept seen in desktop from various add-ons over the years). They are powerful and interesting, but there are existing UX problems here that need to be solved to make them as easy to understand and accessible as it ought to be. 

Collections aren't as significant a differentiator as containers, but it could be a hugely significant one, especially as Google is exploring tab groups - a similar feature (that is not as interesting), and I am not aware of another browser that has a feature like this built-in or as an add-on.

**Comment by liuche** [comment]
Let's highlight this in in the Collections Usability UX issue #5652, please follow along there.

**Comment by otede** [comment]
Please remove the history saving as some hot heads are already advocating for removal of Collections in Private browsing mode.

**Comment by Poopooracoocoo** [comment]
you may like #7325
