### ISSUE TITLE
Notification Downloads: null (and multiple downloads)

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#13798]
## Steps to reproduce

1) Download some PDF documents with Fenix

### Expected behavior

Download notification shows PDF name.

### Actual behavior

![Screenshot_20200811_231615_org mozilla firefox](https://user-images.githubusercontent.com/1104290/90145863-add21480-dd80-11ea-820b-591ea889e151.jpg)

"null" is the displayed name.

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nighly

**Comment by Amejia481** [comment]
If it's not a problem. Could share the url that you were trying to download?

**Comment by gcp** [comment]
I'm not sure, but I think it was the PDF here: https://www.trainerroad.com/forum/t/quality-over-quantity-vs-80-20-or-chad-vs-matt/3962/140?u=garf

**Comment by Amejia481** [comment]
Thanks!

**Comment by sudhanshu-15** [comment]
Seeing similar issue with Daylight
![image](https://user-images.githubusercontent.com/883233/97222641-f13afd00-178b-11eb-9655-af2afd9cf8f4.png)

Opened a URL from Slack using Firefox, and then downloaded an apk from the opened page. Download was successful but download notification remains.

![image](https://user-images.githubusercontent.com/883233/97222977-60b0ec80-178c-11eb-922c-a58d42ad5589.png)

**Comment by Amejia481** [comment]
We did some improvements to our download stack, please take a look in the latest [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) and if the issue still persist please feel free to reopen.

**Comment by lasersPew** [comment]
![Screenshot_20211009-112156_One UI Home](https://user-images.githubusercontent.com/87552756/136642459-c62d52c9-2ae6-4481-a2aa-4303516f5bf1.jpg)

That's the ss for the latest Nightly release. It shows that download failed. https://webtoon-phinf.pstatic.net/20211006_215/1633483744264LE7XT_JPEG/7TheKissBet_S3_WTSpotlight_Ver1.jpg

**Comment by cadeyrn** [comment]
@lasersPew It's a different issue as reported in this issue and this issue has already been closed for many months. You should create a new issue with more information.
