### ISSUE TITLE
FNX-4991 ⁃ Create Search element on home view

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#138]
Parent: #99

**Comment by sblatz** [comment]
<img width="359" alt="screen shot 2019-01-11 at 1 16 06 pm" src="https://user-images.githubusercontent.com/4400286/51051894-1b193480-15a3-11e9-8fd5-137464f2c04b.png">

**Comment by sblatz** [comment]
Discussed with design--this search button is a "dummy" button that will simply transition a user to the full screen awesomebar view.
