### ISSUE TITLE
New tab page accesible with swipe

### ISSUE THREAD

**Issue by TrianguloY** [mozilla-mobile/fenix#13809]
### What is the user problem or growth opportunity you want to see solved?

Being able to access the new tab page directly by swiping from the first/last tab.

### How do you know that this problem exists today? Why is this important?

You can swipe on the navigation bar to switch between tabs, as if all the tabs were virtually placed horizontally and you can scroll this horizontal list. On the other hand, when you press the new tab button, a new tab page opens where scrolling in the search bar is disabled, as if this screen had nothing to do with that virtual horizontal list with the tabs.

The suggestion is to add this new tab as an entry in that virtual horizontal list (either at the left, at the right, or even both making the list warp). In this situation, swiping from the first/last/both tabs will show this screen, making it even faster to create a new tab, specially if you want to open multiple in succession (open, swipe, open, swipe, etc). Similarly, clicking the new tab button will simply 'scroll' to this screen (mentally speaking, it won't actually scroll, just open), so you could swipe to go to the first/last tab if wanted.

![swipe](https://user-images.githubusercontent.com/10616202/90150907-6e0e2b80-dd86-11ea-80e0-fb7945c5a3bc.png)

Note that when there are no opened tabs this new system is the same as what there is currently implemented, nothing to change (except maybe show that little 'you can't scroll' animation from when there is nothing to scroll to).

### Who will benefit from it?

Users that want a faster way to create new tabs, and more consistent behaviour when swiping on the search bar. Also users who find strange why pressing on new tab doesn't increment the new tab counter.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4995)

**Comment by person808** [comment]
Hi, thanks for providing such a detailed request! [Here](https://github.com/mozilla-mobile/fenix/issues/3481#issuecomment-652752138) is the rationale for why we didn't implement it that way initially. From an engineering perspective, the things we need to do for this (if implemented) are: 

1. Take a screenshot of the home screen at appropriate times to use as thumbnails for the preview like we do for websites. 
2. Add support to `ToolbarGestureHandler` (this name will likely change soon) to support swipe between `HomeFragment` and `BrowserFragment`. This involves adding some actions to our nav graph to perform the necessary crossfading between fragments.

**Comment by TrianguloY** [comment]
Thanks for the reply, I had checked that issue, but that particular comment was under the collapsed items, and didn't noticed. Sorry.

If I understood correctly, the main issue is the concept and what it represents. My point of view is that the new tab screen is just a screen, not a new tab (which comes as a surprise when you first click on the new tab button and the counter doesn't increase, but you get used to it without issue). 

Having this screen as another scrollable tab helps understand why: this screen is the one that lets you create tabs (from collections, from a bookmark, from the search bar...), and it is not a new tab per se, so pressing the new tab button 'scrolls' to this page to await further instructions from the user about which new tab they want to open. The gesture remains simply navigational, as it doesn't create anything (you can press the new tab button, switch left, switch right, and you will end at the new tab screen as expected).

About what needs to be done:
1) I understand the issue, as this screen can change from external actions (modify collections, add to top sites, maybe on sync). A proper solution will be to update the preview any time something on this screen changes, but a faster and simpler alternative will be to have a static screenshot of the empty page (see below). When the user scrolls, it would be as if the content is not yet loaded, and instead it is shown when the scroll ends.
![Sin título](https://user-images.githubusercontent.com/10616202/90160691-681e4780-dd92-11ea-9301-66048da4ec1b.png)

2) This is an internal change so I can't assist with it (unless I review the code, which would require a time I'm currently unable to spend).

3) You mentioned 'home screen', which I assume is what I'm calling 'new tab screen'. Again this is an internal change.

**Comment by mobd** [comment]
I agree with @TrianguloY suggestion of using an empty page as the home screen preview, or even something like a sort of splash screen. Conceptually opening a new tab is different from going to an existing tab with a state, users wouldn't need a reminder as to what the page looks like.

**Comment by Dinho33** [comment]
Very interested in this, makes me want to learn coding, gl

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807059

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
