### ISSUE TITLE
Recently shared app shortcuts like Chrome browser

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#13808]
When I share a link to an app from the Chrome browser it remembers that app shortcut and displays it in the long press menu and also displays it in the 3-dot menu.

If something like that could be added to Firefox for Android then it'd be a really handy feature so users who share links and such to frequently share something such as links to a download manager (in the screenshot it is the ADM download manager) or other apps don't have to repeat the same steps everytime to share it and would reduce the number of clicks to share something from Firefox for Android.

 ![Screenshot_20200813_200344.jpg](https://user-images.githubusercontent.com/69129878/90148830-6dcf5980-dda1-11ea-9f4d-c2471d088957.jpg)![Screenshot_20200813_201108.jpg](https://user-images.githubusercontent.com/69129878/90148835-6f008680-dda1-11ea-9622-cba4cd7ccb14.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4993)

**Comment by yoasif** [comment]
This is also available in Fennec - examples:

![signal-2020-08-20-012125_002](https://user-images.githubusercontent.com/152493/90719941-995fb180-e283-11ea-8a6b-6bff6e734e93.png)
![signal-2020-08-20-012125_001](https://user-images.githubusercontent.com/152493/90719942-99f84800-e283-11ea-9733-9e182f6e0d43.png)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809298

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
