### ISSUE TITLE
[Bug] The "Open tab" visual indicator from a different device isn't displayed in suggestions

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#13807]
## Steps to reproduce
1. Sign in with the same account on both a mobile device, and desktop.
2. On mobile, bookmark a few pages, open several tabs, making sure they have a term in common (i.e. "hotels"). On desktop, open a few tabs with the same term.
3. Trigger sync.
4. On the search bar type the term "hotels".
5. Observe the visual indicators of the suggestions displayed.

### Expected behavior
These types of suggestions should be displayed (as in #12622 ):
![visual indicators](https://user-images.githubusercontent.com/40694158/90148285-d90e3100-dd8b-11ea-8bd1-b4cc3edfb80b.png)

### Actual behavior
Only "Switch to tab" and "Bookmark" visual indicators are displayed. The "Open tab" indicator from desktop isn't.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 9)
* Fenix version: 8/13 Nightly build

![Untitled](https://user-images.githubusercontent.com/40694158/90148735-59cd2d00-dd8c-11ea-8cfa-68998a004287.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** as per #13922  on the latest Nightly Build 200921 using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200921-115410](https://user-images.githubusercontent.com/51314259/93749306-5e45fa80-fc02-11ea-88a5-455b7ccf49c4.png)
