### ISSUE TITLE
Bookmarks are extremely unintuitive. (the menu option)

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#13814]
### Problem
Honestly, I'm not even completely sure where the difference is between collections and bookmarks.... except collections seem to be WAY more intuitive. It's quite a shock if you open the menu and, instead of choosing the star on the bottom, you click on the "bookmarks/favorites" option somewhere near the top. I still don't know what it does or why there are things that have similar names but do completely different things. (I'm comparing the bookmark-star and the bookmark-menu-option, not bookmarks with collections)
Basically, the bookmark-menu-option needs to be changed to something normal users aren't scared of.

### Who will benefit from it?
Regular users that don't want to spend minutes figuring out what that "bookmark/favouritize"-option does.

### Personal experience
"Ok, there's a "Desktop-Bookmarks"-folder.... I guess I'll click on it... WHOAA now there are three.... ok, they're all empty.... no, i don't want to log in... So I need to add a new folder? I guess let's do this!... Nice, it's empty as well. How do I put this website in there????????"

**Comment by s-ankur** [comment]
#11987 Addresses  one of your concerns (Bookmarks Star Vs Bookmarks Menu)

**Comment by liuche** [comment]
Going to point you towards #5652 and #11987, thanks for filing.
