### ISSUE TITLE
[Bug] https://winpoin.com/ - Address bar on Fenix can't hide automatically

### ISSUE THREAD

**Issue by binocry** [mozilla-mobile/fenix#13819]
## Steps to reproduce

1. Navigate to: https://winpoin.com/
2. Try to scroll down page

### Expected behavior

Address bar hide automatically like other web on fenix

### Actual behavior

Address bar always show

### Device information

* Android device: 7.1.2
* Fenix version: Firefox Mobile 81.0

**Comment by s-ankur** [comment]
Seems to be solved at some point as I cannot see this on Nightly 201021 17:01 (Build #2015771019)

**Comment by s-ankur** [comment]
Otherwise it would be duplicate of https://github.com/mozilla-mobile/fenix/issues/13797
