### ISSUE TITLE
[Bug] https://www.windowslatest.com/ - Address bar on Fenix can't hide automatically

### ISSUE THREAD

**Issue by binocry** [mozilla-mobile/fenix#13820]
## Steps to reproduce

1. Navigate to: https://www.windowslatest.com/
2. Try to scroll down page

### Expected behavior

Address bar hide automatically like other web on fenix

### Actual behavior

Address bar always show

### Device information

* Android device: 7.1.2
* Fenix version: Firefox Mobile 81.0

**Comment by liuche** [comment]
Duping this, it's easier to track these issues if they are grouped.
