### ISSUE TITLE
[Bug][regression] "Set as default browser" option disappears from Settings

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#13827]
## Steps to reproduce
Go to Settings and observe the menu - more precisely the "Set as default browser" option.

### Expected behavior
The option is displayed and functional.

### Actual behavior
The option is visible very briefly, then disappears (the video is in slow motion).

### Device information
* Android device: all
* Fenix version: Beta 81.0.0-beta.1
* Not reproducible on 8/14 Nightly build, nor Beta 80.0.0-beta.6

<img src="https://user-images.githubusercontent.com/40694158/90226530-ca6f5a80-de1b-11ea-9064-886eb795e11b.gif" width="300" height="550" />

**Comment by sflorean** [comment]
Verified as fixed on Beta 80.0.1-beta.1, the option is displayed in Settings. Also, the external download manager option isn't displayed on this build.
