### ISSUE TITLE
[Bug]fenix causing soft reboot 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#13823]
Fenix causes soft reboot on my phone nubia z11max(snapdragon 652)lineage OS 7.1.2 unluckily as the phone freezes no tombstone or crash reports are generated.
I had a similar issue with kiwibrowser last year when development was active,the developer fixed it ,it turnedout it was Adreno gpu driver fault please fix it as fenix is really crap.

**Comment by s-ankur** [comment]
Can be related to #5663

**Comment by kbrosnan** [comment]
This is an OS bug. Upgrading to Lineage OS 16 or higher is recommended if there is support for your device.
