### ISSUE TITLE
[Bug] identity.sync.tokenserver.uri for own Sync Storage does no more work 

### ISSUE THREAD

**Issue by bsiege** [mozilla-mobile/fenix#13828]
## Steps to reproduce
Install Firefox Android Beta
about:config  add identity.sync.tokenserver.uri with known uri https://myhost.mydomayn.mytoplevel/token/1.0/sync/1.5
Log in to mozilla account for sync. Sync successful, but no entries in webserver log. Device syncs to default place.

### Expected behavior
Use private service as storage

### Actual behavior
Uses mozilla cloud storage 

### Device information

* Android device: Pixel 2
* Fenix version: "Mozilla/5.0 (Android 10; Mobile; rv:80.0) Gecko/80.0 Firefox/80.0"

**Comment by bsiege** [comment]
It seems there is a new process for this, working also for STABLE:

Activate "Debug Mode" if there is the "Secret Settings" menu at the bottom of settings, enter "Sync Settings" and you can enter your server directly. Check twice, then Login to firefox account.... Happy Again

**Comment by githtz** [comment]
> It seems there is a new process for this, working also for STABLE:
> 
> Activate "Debug Mode"
Plesse elaborate

**Comment by liuche** [comment]
Go to about page, click the Firefox logo multiple times. Return to settings in order to see Secret Settings > Sync Settings

**Comment by Fmstrat** [comment]
Secret Settings just shows a blank screen on my device.
