### ISSUE TITLE
Need an option to open a link in Firefox private tab

### ISSUE THREAD

**Issue by PulkitGupta707** [mozilla-mobile/fenix#13837]
### What is the user problem or growth opportunity you want to see solved?

When opening a website link from other app a user should be able to choose if he/she wants to open that link in private mode or normal mode

### How do you know that this problem exists today? Why is this important?

Currently firefox on android provide a way to open links in private tab but it will open all the links in private tab not giving user choice to open it in normal mode

### Who will benefit from it?

Anyone who wants some links to open in normal mode and some in private mode

In the picture below is it possible to add firefox Private shortcut?

![Screenshot_2020-08-14-19-31-49-26~2](https://user-images.githubusercontent.com/29430395/90258433-34145680-de66-11ea-9f99-651fa617b0bb.jpg)

**Comment by liuche** [comment]
This is a great idea! However, we already tried this in #5972 but there were problems on Android 5 which prevented users from using the Default Browser setting. I'm going to dupe this issue, please read through that issue.
