### ISSUE TITLE
[Bug] The copy button in Saved Logins is too small

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13831]
## Steps to reproduce
Go to login-> Saved Logins-> onen one login and try to click on the copy buttons

### Expected behavior
The buttons are easy to click

### Actual behavior
You have to be extremely precise to click on the button, even when your click overlaps the copy icon, the button is not pressed
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly 
(You may need to change the display size in android setting to smallest to see this, but I can also see it on the normal size to a lesser degree)

**Comment by liuche** [comment]
We should make the touch target larger in the Edit Logins screen.

I also noticed that there is no highlight when clicking the "copy" icon for the password, which we should also fix

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201012`** using a Google Pixel 3a (Android 10)
Scanned the Saved Logins section with the Accessibility Scanner app and the "Copy" buttons have the right size. ✔️
