### ISSUE TITLE
Search Logins by Username

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13839]
### What is the user problem or growth opportunity you want to see solved?
Most password managers including the lockwise password manager on desktop firefox as well as several android password managers like Bitwarden allow for searching the username of a login item. But fenix only allows you to search by the URL of the site for which it is saved. 

### How do you know that this problem exists today? Why is this important?
Sometimes it can be difficult to remember the exact url of the site you are searching for, and sometimes you can have so many accounts for a single url that you need to search through them (for example google accounts)

### Who will benefit from it?
Everyone who uses the inbuilt fenix password manager

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5038)

**Comment by liuche** [comment]
My guess is that most people use the same username for almost all of their accounts, which is usually a single email address. However, the use case you suggest, where you have many accounts on the same site (like accounts.google.com) it could be helpful to filter by a specific email/username (e.g. my subscriptions email account, etc).

Would probably fall under #5774 (which I see you've already linked).

**Comment by jerome-dl** [comment]
The Search function, on Firefox desktop, walks through URL **and** logins **and** passwords, as well!
From my perspective, it should be aligned on Android client (possibly: with an option to chose between these 3 fields). 
Furthermore, as Firefox/Android can be the password manager for other apps, they are many situations where the URL is not directly related to the name of the app. 

I would greatly appreciate that the search function aligns on the desktop client.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812447

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
