### ISSUE TITLE
The opened tabs / bookmarks suggestions are displayed at the bottom of the search screen

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#13833]
## Steps to reproduce
1. Sign in with valid credentials.
2. Bookmark a few pages.
3. Open several tabs (i.e. twitter.com).
4. Open a new page and type the first letters of twitter.com.

### Expected behavior
The search screen displays multiple suggestions, and the "Switch to tab", "Bookmarks", and "Synced tabs" suggestions are displayed first.

### Actual behavior
The "Switch to tab", "Bookmarks", and "Synced tabs" suggestions are displayed last. Sometimes the user doesn't scroll all the way down, so the visual indicators are pointless.

### Device information
* Android device: all
* Fenix version: 8/14 Nightly, and Beta 81.0.0-beta.1

<img src="https://user-images.githubusercontent.com/40694158/90250033-1b934480-de44-11ea-97f2-b29dbc32736c.jpg" width="300" height="550" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5027)

**Comment by softvision-miralobontiu** [comment]
This is still reproducing on all builds.

**Comment by lobontiumira** [comment]
The issue still reproduces on all builds.

**Comment by marcel263** [comment]
To summarize and propose an idea from the duplicate issue I submitted:

Concerning active tabs: if the search box is too crowded, context-aware sorting can prioritize the most recently used and/or matching domain names, placing these above the search engine. Ultimately the content matches and older tabs could follow.

**Comment by amocirean** [comment]
This issue is still reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using Samsung Galaxy S22 Ultra (Android 13) and Oppo Find X3 Neo.
Removing the wontfix label.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807728

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
