### ISSUE TITLE
[Bug] Swipe to switch tabs can be triggered in fullscreen mode

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#13845]
## Steps to reproduce
1. Have the device in landscape orientation
2. Start playback of a video, e.g. https://demo.bitmovin.com/public/firefox/av1/
3. Enter fullscreen mode
4. Swipe from the left edge of the device

### Expected behavior
Nothing happens.

### Actual behavior
The swipe to switch tab gesture is triggered. This does not happen when entering fullscreen mode while still being in portrait orientation.

![swipe-tab-landscape](https://user-images.githubusercontent.com/42788925/90279224-185e7f80-de69-11ea-8192-4ef1441e955b.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 200814 06:02 (Build #2015757873)
AC: 54.0.20200812130143, 721a690d6
GV: 81.0a1-20200811091731
AS: 61.0.10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5043)

**Comment by person808** [comment]
Hm probably a bug with our [hitbox detection](https://github.com/mozilla-mobile/fenix/blob/d9ffac0c890c0d58cd62f00693a45322c030f96d/app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt#L307)... weird that its happening only in those scenarios.

**Comment by hwinnemoe** [comment]
You could just block any swipe action if the device is in fullscreen mode.

I managed to also intermittently trigger the swipe gesture in portrait mode using the following STR:
1. Have the device in portrait orientation
2. Start playback of a video that does not force the device into landscape mode, e.g. the video on https://builders.mozilla.community/
3. Enter fullscreen mode
4. Start swiping from the left or right edge of the screen

![swipe-to-switch-portrait](https://user-images.githubusercontent.com/42788925/90315054-8e6def80-df18-11ea-9831-37f60bbbd07f.gif)

**Comment by hwinnemoe** [comment]
@boek Correct me if I'm wrong but how do these commits relate to this issue?

**Comment by Djfe** [comment]
This always happens to me if I want to move within a video in full screen mode (portrait). If I want to seek forwards/backwards (with the cursor), then fenix switches tabs. Very annoying. This gesture should only be applied if the bar is visible imo.

I have the address bar set so that it isn't hidden by scrolling anymore (in-case that matters), it's displayed at the bottom of my screen.

**Comment by andreicristianpetcu** [comment]
Pull to refresh had a similar issue https://github.com/mozilla-mobile/fenix/issues/16603

**Comment by Mugurell** [comment]
@hwinnemoe @Djfe Tried to reproduce this on the latest Nightly but I couldn't.
Is this still an issue?

**Comment by hwinnemoe** [comment]
@Mugurell I can still reproduce on Nightly 210203 17:01 (Build #2015791177). The moment I enter immersive mode I can swipe on the lower left part of the viewport and then produce undefined behaviour, e.g. Fenix being locked to landscape mode.

**Comment by Djfe** [comment]
still happening
Settings > customize > keep "swipe toolbar sideways to switch tabs" enabled and toolbar needs to be "bottom" 

go to
https://davidwalsh.name/demo/fullscreen.php
launch fullscreen (portrait mode)
Then swipe at the bottom of your screen where your address bar usually is. (left or right)
You will switch tabs accidentally (if there are other tabs open)

**Comment by Djfe** [comment]
This has never been fixed

**Comment by thebiffman** [comment]
This is still an issue in 93,2,0 following the instructions by Djfe using a embedded youtube video in landscape fullscreen.

**Comment by Beach77** [comment]
Still a problem. Need to find a browser with extension support that is not kiwi browser and switch from this frustrating browser named Firefox where the devs never fix anything.

**Comment by Mugurell** [comment]
With https://github.com/mozilla-mobile/fenix/pull/27370 landed this should be checked in the next Nightly.
