### ISSUE TITLE
[Bug] DuckDuckGo search box disappears on SERP pages when in dark theme (sometimes)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#13844]
Reported initially on https://www.reddit.com/r/firefox/comments/i9nduo/duckduckgo_search_box_randomly_disappears_in/

## Steps to reproduce

>basically the search box (even with the buttons for images, news etc) It disappears randomly after scrolling down the results and changing from all to images and vice versa. 

### Expected behavior

Search box does not disappear

### Actual behavior

Search box disappears. 

![VainDefenselessHuman-size_restricted](https://user-images.githubusercontent.com/152493/90276164-7bccbb00-de31-11ea-88a4-9ac847ca8e9e.gif)

### Device information

* Android device: Moto g5 plus, Pixel 2 XL
* Fenix version: beta on Moto g5 plus, release on Pixel 2 XL

**Comment by AdityaGupta150** [comment]
This seems __more of a problem on duckduckgo side__... have you tried different settings for search bar behavior (here)[https://duckduckgo.com/settings#appearance].
It should help decide if it is due to fenix or not  😄👍🏽

**Comment by karlcow** [comment]
@tagawa @pdolanjski Could you help with this issue? Thanks,

**Comment by tagawa** [comment]
Thanks for the ping. I think there's some misunderstanding. The search box does hide when scrolling down in dynamic mode (the default), as @AdityaGupta150 says, but it's supposed to reappear when scrolling back up. The reporter's issue is that it occasionally doesn't reappear in Fenix. This is only noticeable later in the attached screencast when they do an image search. I don't have Android to test but on iOS (Safari & DuckDuckGo app) I can't reproduce the issue, so it could be a browser/platform issue.

**Comment by karlcow** [comment]
fwiw it doesn't happen all the time I had to try 10-20 times before being able to reproduce on Android 10 with a pixel 2. 
here a profile with the problem showing at 14.2s 
https://share.firefox.dev/3kYvuoR

It's impossible to reproduce on rdm.

isLegacyAndroid is set to true… which is strange. given that I'm using firefox nightly 81 on Android 10. 

```js
      if (a.device.isLegacyAndroid) {
        a.addClass('html', a.$html, 'is-legacy-android')
      }
```

`mozilla/5.0 (android 10; mobile; rv:81.0) gecko/81.0 firefox/81.0`

```
    this.isLegacyAndroid = this.isAndroid && /android ([1-3])|android (4\.[0-2])/.test(q);
```

ooops this rule thinks that an Android version without 2 digits is not possible. 
but this should not be the issue at stake, that would happen for chrome too. @tagawa fyi
in https://duckduckgo.com/d2833.js


---

First load.
```html
<div class="site-wrapper  js-site-wrapper" style="min-height: 607px;">

…

<div id="header_wrapper" class="header-wrap js-header-wrap">
```

header is being hidden

```html
<div class="site-wrapper  js-site-wrapper" style="min-height: 664px;">

…

<div id="header_wrapper" class="header-wrap js-header-wrap">
```

when the header is not coming back scrolling down is when the update to 

```html
<div class="site-wrapper  js-site-wrapper" style="min-height: 607px;">

…

<div id="header_wrapper" class="header-wrap js-header-wrap" style="top: -95px;">
```

is not done. It stays at `style="top: -95px;`.

**Comment by karlcow** [comment]
Ah this is controlled by 
in https://duckduckgo.com/g2397.js

```js
    updateScrollPosition: function (i) {
      var f = (i < this._previousScroll) ? 1 : 0,
      h,
      g;
      this.scrolledToTop = this._largerMobileHeader ? i < a : i === 0;
      this.scrolledPastHeaderThreshold = (i > this._headerHeight + e);
      this.scrolledPastHeader = i > this._headerHeight;
      this.canUpdateHeaderPosition = false;
      this.newHeaderPosition = - this._headerHeight;
      if (this.scrolledToTop) {
        this._scrollBuffer = 0;
        this._showingFloatedHeader = false;
        this.newHeaderPosition = 0
      }
      h = f && !this._showingFloatedHeader;
      g = !f && this._showingFloatedHeader;
      if (this.scrolledPastHeaderThreshold && (h || g) && this._pastScrollBuffer(i, f)) {
        this.newHeaderPosition = (f) ? 0 : - this._headerHeight;
        this.canUpdateHeaderPosition = true;
        this._scrollBuffer = 0;
        this._showingFloatedHeader = !this._showingFloatedHeader
      }
      if (this._largerMobileHeader && !this.scrolledToTop) {
        this.newHeaderPosition -= a
      }
      this._previousScroll = i;
      this._previousScrollDirection = f
    },
```

**Comment by karlcow** [comment]
```js
    _onScroll: function (f) {
      this.model.updateScrollPosition(c.device.scrollTop());
      if (this.model.scrolledToTop) {
        this._reset();
        return
      }
      if (this.model.scrolledPastHeader) {
        this.views.headerLinks.hide()
      }
      if (this.model.scrolledPastHeaderThreshold && !c.hasClass(this.$el[0].id, e)) {
        this._updateHeaderPosition();
        setTimeout(function () {
          c.addClass(this.$el[0].id, c.$html, e)
        }.bind(this), a)
      }
      if (this.model.canUpdateHeaderPosition) {
        this._updateHeaderPosition()
      }
    },
    _updateHeaderPosition: function () {
      this.$el.css('top', this.model.newHeaderPosition)
    },
```

**Comment by karlcow** [comment]
I wonder if it's a race issue. :)

**Comment by tagawa** [comment]
Thanks @karlcow – impressive analysis! I've created an internal bug report for the false legacy Android reporting.

For the remainder, do you think this is a Fenix issue that could affect other sites, or something that we (DuckDuckGo) should fix?

**Comment by yoasif** [comment]
Continues to be an issue that users are finding in the new release.

**Comment by tagawa** [comment]
We've fixed the issue that falsely detected Android 10+ as legacy Android, however I don't think that fixes this search box issue (based on @karlcow's comment). I've not seen reports relating to other browsers so could this be an issue in Fenix itself?

**Comment by karlcow** [comment]
The layout seems to have changed and I still can't reproduce.

![Screenshot_20210127-135444](https://user-images.githubusercontent.com/505230/105945035-d1c3b100-60a7-11eb-88e8-fe4b01b3cc00.png)

@yoasif can you still reproduce?
