### ISSUE TITLE
Too many way to add to collection

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#13846]
There is actually 3 way to add tab to collection from the tab tray, it seems a little bit overkill:
 - long press to select
 - three dot menu
 - add to collection button at the end of the tab tray

I think that the last option should be removed, as it is distracting and can be press when not wanted (when wanting to press first tab or new tab). Moreover, the two first option are quite intuitive for an android user.

![Screenshot_20200814-200850_Firefox_Nightly~2](https://user-images.githubusercontent.com/56130419/90279749-0fba7900-de6a-11ea-83a4-a21bbd8142c0.png)

**Comment by AdityaGupta150** [comment]
Very much related to #13517 

The last line of that issue is precisely what the problem is, though this one is pointwise listing.
Both issues are quite opinion based, but shouldn't the button according to this issue be removed ? 😄❔

**Comment by liuche** [comment]
Thank you for filing, and raising this question. We're still iterating on Collections, so I'll bring this up in the Highlight Collections Usability UX issue #5652, please follow along there.
