### ISSUE TITLE
FNX-4993 ⁃ Make session share and options button labels unique

### ISSUE THREAD

**Issue by eeejay** [mozilla-mobile/fenix#1384]
From Accessibility Scanner

> org.mozilla.fenix.debug:id/session_card_overflow_button
This clickable item's speakable text: "Session options" is identical to that of 2 other item(s).

> org.mozilla.fenix.debug:id/session_card_share_button
This clickable item's speakable text: "Share session" is identical to that of 2 other item(s).

![image](https://user-images.githubusercontent.com/5764/55577680-f8417c80-56c8-11e9-87af-4fb6a6ae106b.png)

![image](https://user-images.githubusercontent.com/5764/55577736-17d8a500-56c9-11e9-86e2-8cbf11a2bcc8.png)

**Comment by eeejay** [comment]
The labels should include the name of each session.

**Comment by vesta0** [comment]
Thanks @eeejay We are changing the way sessions work so closing this.
