### ISSUE TITLE
Add Ability to Set Exceptions for Cookie Deletion Upon Browser Exit

### ISSUE THREAD

**Issue by theSdev** [mozilla-mobile/fenix#13855]
### What is the user problem or growth opportunity you want to see solved?
I set cookies to be cleared upon browser exit which is supported right now. What I think is needed is a way to set exceptions (in the form of a list of domains) just like what the desktop version allows users to do:

![Screenshot of the desktop UI for setting exceptions - 1](https://user-images.githubusercontent.com/24947508/90306224-2dc2c080-dee0-11ea-99b0-239f3ab8494f.png)
![Screenshot of the desktop UI for setting exceptions - 2](https://user-images.githubusercontent.com/24947508/90306330-54352b80-dee1-11ea-850f-2225c80b6957.png)
### How do you know that this problem exists today? Why is this important?
I regularly "exit" the browser to delete unwanted cookies. There are a few sites though which I trust or simply don't want to be signed out of. This is specially true for the PWAs I've installed such as Twitter, I don't want to be signed out of it every time I exit the browser, it conflicts the app-like property of the installed PWA IMO.
### Who will benefit from it?
All the users who turn on the cookie deletion upon browser exit option.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5050)

**Comment by fichtennadel** [comment]
There's already a addon for this and it's also a recommended addon: Cookie Autodelete. 

But unfortunately it's not yet enabled, see 
https://github.com/mozilla-mobile/fenix/issues/13925

**Comment by bege10** [comment]
I simply don't understand Mozilla's policy. There is a brand new "privacy" browser and contrary to the old one it does not support cookie managers. Delete everything or nothing is not privacy.
Urgent: Add support for cookie managers!

**Comment by theSdev** [comment]
To their credit on this matter, they recently added a mechanism to automatically delete cookies after thirty days from the last visit to the respective domain.



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: bege10 <notifications@github.com>
Datum: 14.11.20 14:04 (GMT+03:30)
An: mozilla-mobile/fenix <fenix@noreply.github.com>
Cc: Samir Saeedi <thesdev@outlook.com>, Author <author@noreply.github.com>
Betreff: Re: [mozilla-mobile/fenix] Add Ability to Set Exceptions for Cookie Deletion Upon Browser Exit (#13855)


I simply don't understand Mozilla's policy. There is a brand new "privacy" browser and contrary to the old one it does not support cookie managers. Delete everything or nothing is not privacy.
Urgent: Add support for cookie managers!

**Comment by bege10** [comment]
> 
> To their credit on this matter, they recently added a mechanism to automatically delete cookies after thirty days from the last visit to the respective domain. Von meinem/meiner Galaxy gesendet

That is correct. But that does not solve the need to always keep cookies from some sites and to remove those from others at closing the app. The new mechanism does not even come close to that, that's simply tinkering.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807118

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
