### ISSUE TITLE
Crash in [@ java.lang.IllegalArgumentException: at androidx.dynamicanimation.animation.DynamicAnimation.start(DynamicAnimation.java)] by overscrolling the tab switch gesture

### ISSUE THREAD

**Issue by TrianguloY** [mozilla-mobile/fenix#13856]
This is about the scrolling between tabs feature (when you scroll the navigation bar to switch tabs)

Under normal use, it's impossible to scroll more than the screen width for physical reasons, however there are several ways to achieve this, and when doing so and releasing the finger, the browser crashes. It is repeatable.

## Steps to reproduce
Make sure you have at least two tabs opened, and you are on one of them so you can initiate the tab-swapping scrolling. Now:

* Way 1) Multiple fingers (unusual but easy to perform)
    * Press with one finger on the navigation bar and start the scroll, don't release the finger yet.
    * Press with another finger (anywhere on the screen), and release the first one. Now you can still move the tabs with this second finger.
    * Repeat the process pressing and releasing fingers so that you can scroll more than the screen width.
![photo_2020-08-15_11-14-16](https://user-images.githubusercontent.com/10616202/90309393-84cc9380-dee8-11ea-851e-00953e30202c.jpg)

* Way 2) Windowed app (maybe it requires the 'allow any app in windowed mode' setting enabled)
    * Open the browser in windowed mode (this vary between devices and android version)
    * Simply scroll more than the window width (possible because it is smaller than the screen width)
![photo_2020-08-15_11-14-20](https://user-images.githubusercontent.com/10616202/90309395-8f872880-dee8-11ea-8139-523209ab24a0.jpg)
Note: this also makes the tab go outside of the app window, but not sure if that is the browser issue of android.

* Way 3) Horizontal split screen. Probably the easiest for a user
    * Activate split screen between the browser and another app.
    * Turn to landscape, make sure the browser is at the left if you are going to swipe to the right (or vice versa)
    * Simply swipe, now you have twice the browser width
![photo_2020-08-15_11-14-30](https://user-images.githubusercontent.com/10616202/90309412-b2b1d800-dee8-11ea-863c-b615fdf92d00.jpg)
Note: when making a screenshot it shows the tab inside the other app. While performing it it doesn't. Maybe an android issue?

Now, in any of those three ways, release the finger.

### Expected behavior

The browser doesn't crash and:
- Ideally (but probably hard to accomplish and not a big requirement) you can scroll to the second, third or even more next tab
- Better: the scrolling stops when the other tab is fully visible (that is, when the scroll reaches the browser width)

### Actual behavior
 The browser crashes. Crash report here: https://crash-stats.mozilla.org/report/index/d5dca2f7-371f-4180-aa0d-4d4b70200815

### Device information

* Android device: Nexus 5X with Oreo 8.1.0
* Fenix version: Nightly 200814 06:02 (Build #2015757875)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200929 05:08 (Build #2015766697) GV 83.0a1 from 9/29 with Motorola Moto G6 (Android 8) and Nexus 5 (Android 6.0.1).
I will close this issue and remove the qa:needed label.
