### ISSUE TITLE
Add support for Dynamic Delivery

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1385]
As described on  https://developer.android.com/studio/projects/dynamic-delivery

> Google Play’s app serving model, called Dynamic Delivery, uses Android App Bundles to generate and serve optimized APKs for each user’s device configuration, so users download only the code and resources they need to run your app. You no longer have to build, sign, and manage multiple APKs to support different devices, and users get smaller, more optimized downloads.

This may bring down the APK size.

**Comment by sarentz** [comment]
Asking @mozilla-mobile/releng for advice - no action but I want to ask you how you feel about this one.

**Comment by mitchhentges** [comment]
It looks interesting - it would save user data on-app-download by not downloading:
* Unnecessary languages
* Unnecessary assets (images) for the device's screen (resolution/dpi)
* Unnecessary feature modules (code)

I don't believe that there's any Fenix features that would be conditionally activated depending on the device, so the only savings that we'd reap would be languages + assets. It would be interesting to measure how much we'd specifically save - under a MB? Or a decent chunk of the app?

**Comment by sarentz** [comment]
I think the question I have is whether Dynamic Delivery will also allow us to send architecture specific APKs to users.

More concretely: do people now download an APK that has a for example ARMv7 and ARM64 code included for GeckoView? Will Dynamic Delivery change that to an optimized binary that only contains code for the architecture of your specific device?

**Comment by sarentz** [comment]
Note to @mozilla-mobile/releng that we are not going to do this for 1.0 and will consider it only for a later release when we understand what the actual APK size gains will be.

**Comment by JohanLorenzo** [comment]
The Firefox Lite folks use Android App Bundle and I think Dynamic Delivery too. The former was done in https://bugzilla.mozilla.org/show_bug.cgi?id=1473845. 

From a Release Engineering perspective, we currently don't support Android App Bundles in our automation pipeline. Firefox Lite signs their AAB manually (with Autograph) and let a 3rd-party (Bitrise) upload the AAB for them. 

> do people now download an APK that has a for example ARMv7 and ARM64 code included for GeckoView?
To answer this question in particular: Fenix users just download the right APK for their own processor. We've never shipped a universal APK that contains both ARMv7 and ARM64 🙂 
To my knowledge, geckoview is the biggest piece in terms of APK size (I might be wrong, check me on that). Based on that assumption, If you wanted to use Dynamic Delivery, you'd need to split geckoview into smaller pieces to let users download just the features they need. 

> Note to @mozilla-mobile/releng that we are not going to do this for 1.0
👍
