### ISSUE TITLE
[Bug]Entering a web address goes to the search engine

### ISSUE THREAD

**Issue by freebrowser1** [mozilla-mobile/fenix#13860]
## Steps to reproduce
Entering a local web IP address (e.g. 192.168.0.60 or even http://192.168.0.60) goes to the current search engine (in my case Duckduckgo).

### Expected behavior
It should go to the URL.

### Actual behavior
It issues search results for the entered URL.
### Device information

* Android device: Oneplus 6 Oxygen OS 10.3.5
* Fenix version: 80.0 beta

**Comment by LittleAngelwings** [comment]
I can't reproduce this in latest nighty and with my internal gateway  (192.168.178.1).

**Comment by liuche** [comment]
I also can't repro this - I see it go to the ip address. Please re-open if you are still seeing this.
