### ISSUE TITLE
[webcontent] youtube embed - share is not working

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#13862]
## Site with issue and any steps to reproduce
Any youtube embed, for example https://www.mouv.fr/musique/rap-fr/greg-guillotin-devoile-les-coulisses-de-sa-camera-cachee-avec-jnr-362449
1. Click on the three dot menu
2. Click on share button
### Expected behavior
The native android share menu appears (chrome) or the video is changed by a screen with a already selected short url (youtu.be) and share to twitter / facebook (fennec)
### Actual behavior
Nothing happens
### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
If you meant fennec no
### Can you reproduce in Chrome (or other non-Mozilla browser)?

No
### Device information

* Android device: Pocophone F1
* Fenix version: Nightly 200815 06:03

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that the issue is reproducible on the latest Firefox Preview Nightly 200820 (Build #2015759027).

### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by B0pol** [comment]
Bump
It is still an issue

BTW I noticed with an old version of Chrome (83) I have the old share slider
<img src="https://user-images.githubusercontent.com/58657617/108063810-136aca80-705c-11eb-96a1-f86fbb1a79ec.png" width="300">

but with the latest version I have a new one
<img src="https://user-images.githubusercontent.com/58657617/108063821-15cd2480-705c-11eb-98aa-3e60da721700.png" width="300">

The second icon at the bottom, "envoyez à vos appareils" means send to devices and it says to enable chrome sync to use it
It is the same slider as when I press on three dot -> share

**Comment by yoasif** [comment]
I can still reproduce this issue.

**Comment by B0pol** [comment]
I can not
