### ISSUE TITLE
[Bug] Sometimes unable to take screenshots in private browsing without multiple toggles

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#13869]
## Steps to reproduce
Have the "Allow screenshots in private browsing" set to true and try to take a screenshot of a private tab.

### Expected behavior
I'm able to take a screenshot.

### Actual behavior
A notification says "Unable to take a screenshot". This doesn't always happen and toggling the setting to allow screenshots off and on again fixes it.

### Device information

* Android device: Huawei Nova 6
* Fenix version: Nightly 200814 06:02 (Build #2015757875)
AC: 54.0.20200812130143, 721a690d6
GV: 81.0a1-20200811091731
AS: 61.0.10

**Comment by ekager** [comment]
Going to close this for #13978 because I think they have the same root issue
