### ISSUE TITLE
FNX-4994 ⁃ [Bug] With today build apk, Sync not works

### ISSUE THREAD

**Issue by pasqualedante** [mozilla-mobile/fenix#1386]
## Steps to reproduce
Download todaybuild from https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly/latest

### Expected behavior
Install apk and browse synced bookmarks

### Actual behavior
The apk update end with success, but Fenix crash at startup always. If I make a clean installation, I cannot log ti Sync service.

### Device information
Pocophone F1 (android 9)
FxA build 4/4 12:12 PM

**Comment by vesta0** [comment]
Fixed :)
