### ISSUE TITLE
[webcontent] audio in background is stopped after about 30s

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#13865]
## Site with issue and any steps to reproduce
1. Open-https://mouv.fr
2. Click on "Direct" _(live)_
3. Play in background
### Expected behavior
The music continues until I manually close it (pause with the notification, close the tab, close the browser…)
### Actual behavior
The music stops after about 30s
### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes
### Can you reproduce in Chrome (or other non-Mozilla browser)?

No
### Device information

* Android device: pocophone F1
* Fenix version: Nightly 200816 06:01

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that the issue is reproducible on the latest Firefox Preview Nightly 200820 (Build #2015759027).

### Devices used:
- OnePlus 6T (Android 9)

**Comment by B0pol** [comment]
In fact you don't even need to install the PWA, just play in background. 

> Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)

No

**Comment by B0pol** [comment]
Can't reproduce with Nightly 200923 06:02
