### ISSUE TITLE
[webcontent] W3C EPUB3 WG is not rendered correctly

### ISSUE THREAD

**Issue by TyDraniu** [mozilla-mobile/fenix#13876]
## Site with issue and any steps to reproduce

See https://www.w3.org/publishing/groups/epub-wg/

![Screenshot_20200817-153545](https://user-images.githubusercontent.com/10631144/90402345-9a37ee00-e09f-11ea-955a-9ee054b9212c.png)

### Device information
* Fenix version: Nightly

**Comment by kbrosnan** [comment]
This is a mobile capable website that does not set `<meta name="viewport" content="width=device-width">`. Seems like a case of garbage in garbage out.
