### ISSUE TITLE
Change search engine order

### ISSUE THREAD

**Issue by Skallwar** [mozilla-mobile/fenix#13878]
### What is the user problem or growth opportunity you want to see solved?
Having the search engines sorted by alphabetical order is not convenient. I prefer to sort my search engine by hand. 

### How do you know that this problem exists today? Why is this important?
Scrolling for the search engine I want is annoying. 

### Who will benefit from it?
Everyone with a lot of search engines

**Comment by liuche** [comment]
Duping to #8882
