### ISSUE TITLE
[Bug] Unable to Download .pdf .docx From E-mail Attachments

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#13873]
## Steps to reproduce
1. Open Firefox Browser
2. Go to yaanimail.com
3. Sing in
4. Open any received mail which include pdf or MS word document
5. Try to download pdf or MSWord document.
### Expected behavior
Firefox should be able to download documents
### Actual behavior
Pop-up appears and shows error messase "Unable to download"
### Device information
Asus Zenfone 3
* Android device: Android 8.0
* Fenix version: 80.0.0.beta.6

[20200818_150909.zip](https://github.com/mozilla-mobile/fenix/files/5084112/20200818_150909.zip)

**Comment by sheikh-azharuddin** [comment]
This is a critical issue now... It is impossible to download any pdf file.. Have to switch to chrome to download... Please fix

Sample link
https://5.imimg.com/data5/MA/RR/OO/SELLER-1103591/gpon-1g-onu.pdf

**Comment by yoasif** [comment]
> This is a critical issue now... It is impossible to download any pdf file.. Have to switch to chrome to download... Please fix
> 
> Sample link
> https://5.imimg.com/data5/MA/RR/OO/SELLER-1103591/gpon-1g-onu.pdf

FWIW, I can download this file using Nightly - can you reproduce this still?

**Comment by BigSamSampson** [comment]
I reproduced that issue on Firefox for Android, i didn't try that on Nightly.

**Comment by liuche** [comment]
I'm also able to download this file on Nightly - there could have been a fix already, and it's making its way to release.

**Comment by Amejia481** [comment]
QA could you help us to verify this issue? Thanks in advance!

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 201019 (Build #2015770539).

### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)
