### ISSUE TITLE
[webcontent] Date picker does not open.

### ISSUE THREAD

**Issue by nri82** [mozilla-mobile/fenix#13881]
## Site with issue and any steps to reproduce
I want to make an EFT with future date, and date picker can't open. But this function works with Google chrome and other Chromium based browsers and the desktop version Firefox.

Google chrome open date picker
![Screenshot_20200816-134044](https://user-images.githubusercontent.com/18355195/90425520-88b70c00-e0c8-11ea-98c1-b6098bf5001b.jpg)

Firefox can't open date picker
![Screenshot_20200816-133835~2](https://user-images.githubusercontent.com/18355195/90425533-8fde1a00-e0c8-11ea-8026-b81f8b5697db.jpg)

### Expected behavior
Open the date picker
### Actual behavior
Can't open date picker
### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes
### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information

* Android device: 10
* Fenix version: 79.0.4
* [Garanti Bankası](https://garantibbva.com.tr)

**Comment by ekager** [comment]
@nri82 are you still seeing this? If so could you link the exact page with the date picker?

**Comment by nri82** [comment]
> @nri82 are you still seeing this? If so could you link the exact page with the date picker?

Hello, yes I'm seeing. But it's bank site page you need to login if you want to see that page. How can I help?

**Comment by Amejia481** [comment]
Would you mind testing the picker working on Firefox desktop?

**Comment by nri82** [comment]
> Would you mind testing the picker working on Firefox desktop?

Okay, i have test but it's working fine no problem.

**Comment by Amejia481** [comment]
Thanks, that means that is something specific fo Fenix/geckoView.

Could you try it on [GeckoView example app](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt/artifacts/public/build/geckoview_example.apk)  this way we will know for sure if this is something related to geckoView

**Comment by nri82** [comment]
Okay, I've tested gecko view example app but result is same.

**Comment by Amejia481** [comment]
I opened [an issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1686721) for the geckoview team to take a look, as it looks.

**Comment by agi** [comment]
@nri82 unfortunately we need more information to debug this, are you able to provide an html/web page that we can look at that reproduces this problem?

**Comment by nri82** [comment]
Okay, but how can I provide that information?

**Comment by Amejia481** [comment]
You could get the HTML by using [remote](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging) debugging  [about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging).

**Comment by nri82** [comment]
> 
> 
> You could get the HTML by using [remote](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging) debugging on Firefox desktop nightly by typing [about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging).

Okay, im trying to this but it's stucked **_waiting for browser_** section. it's seen in firefox but waiting

im sure installed adb driver
enabled android developer option
enabled android usb debugging in developer options
enabled firefox nightly remote debugging via usb option

![watingforbrowser](https://user-images.githubusercontent.com/18355195/105686807-bb332380-5f08-11eb-84bb-68eda7e47bf6.png)
