### ISSUE TITLE
[Bug] PointerCapture does not work when element also has wheel event listener

### ISSUE THREAD

**Issue by mariusGundersen** [mozilla-mobile/fenix#13896]
## Steps to reproduce

[Here](https://codepen.io/mariusgundersen/full/eYZzbLy) is a reproducable example. This page has three elements, the only difference between them is that they have an `addEventListener('wheel')` attached to them. It seems like having the wheel event attached to the element affects the way captured pointers behave.

### Expected behavior

Touch the top box with two fingers at the same time, wait a bit, and then release. You should see the following output, showing when the `pointerdown`, `pointerup` and `lostpointercapture` event occured:

```
pointerDown: 0
pointerDown: 1
pointerUp: 0
lostPointerCapture: 0
pointerUp: 1
lostPointerCapture: 1
```

The last four lines are not added to the output until you release the fingers.

### Actual behavior

Touch the middle box with two fingers at the same time, wait a bit, and then release. You should see the following output, showing when the `pointerdown`, `pointerup` and `lostpointercapture` event occured:

```
pointerDown: 0
pointerDown: 1
lostPointerCapture: 0
lostPointerCapture: 1
```

There is no `pointerup` event, and the `lostpointercapture` event is triggered right away, before the fingers are released from the touch screen.

The third box has a wheel event listener, but it is set as passive, and it behaves like the first box. This however means that it's not possible to use `e.preventDefault()` in it.

### Device information

* Android device: SM-G975F (Samsung Galaxy S10+) with Android 10
* Fenix version: 79.0.4 (Build 2015757667)

**Comment by mariusGundersen** [comment]
I discovered a related bug in this same demo: If you touch the text then the `pointerup` and `lostpointercapture` events aren't triggered.

**Comment by mariusGundersen** [comment]
The bug with wheel eventlistener appears to be fixed in latest nightly, version 200825).

The bug with touching text is improved, but still to perfect in the same nightly version.

**Comment by ekager** [comment]
@mariusGundersen would you mind filing a new issue with the codepen link and describing the touching issue directly? Thank you!
