### ISSUE TITLE
[Bug] Delete a bookmark->undo does nothing if you pull to refresh 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13895]
## Steps to reproduce
Delete a bookmark
pull to refresh
click undo

### Expected behavior
undoes deletion

### Actual behavior
nothing

### Device information

* Android device: asus Zenfone
* Fenix version: nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5101)

**Comment by sv-ohorvath** [comment]
Pull to refresh is actually supposed to do a forced sync, so if you sync after deleting a bookmark it can't bring it back. 
I think this is expected but I'll leave it open for triage if someone thinks differently.

**Comment by s-ankur** [comment]
@sv-ohorvath if so then it should dismiss the undo bar immediately on pull to refresh. I tried this with bookmarks and it worked in that case so I was not sure why there was such an inconsistency

**Comment by AndiAJ** [comment]
Reproducible on the latest **`Nightly Build 201106`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by sv-ohorvath** [comment]
Still reproducing on Nightly, should keep it.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducing on the latest Nightly 96.0a1 (2021-11-05T05:12:49.870142).

Tested with Xiaomi Mi11 (Android 11).
