### ISSUE TITLE
[Bug] tab history on custom tabs shows browser history of random normal browsing tab

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13908]
## Steps to reproduce
Open custom tab
Open tab history by long press back

### Expected behavior
Tab history of this custom tab
### Actual behavior
Tab history of a random tab in normal browsing mode
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Underlying issue is same as #13934

**Comment by liuche** [comment]
Okay let's dupe to #13934
