### ISSUE TITLE
[Bug] Tab not updating

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#13906]
## Steps to reproduce

- Open a few tabs
- While on a tab (not homescreen) open the tabs tray
- Delete the tab that was open
- Open another tab

### Expected behavior

- The newly opened tab should display web content that corresponds to its URL

### Actual behavior

- Web content from the deleted tab is displayed even though the URL has been updated. The only way to fix the problem is either to switch tabs and go back, or restart the browser. 

***I have a video of this but it was too large to upload. Whoever picks this us, ping me!**

### Device information

* Android device: Pixel 4, Android 10
* Fenix version: Nightly 200818 06:01 Build #2015758643

**Comment by s-ankur** [comment]
Related #12382

**Comment by liuche** [comment]
Will dupe this to #12382
