### ISSUE TITLE
[Bug] Red radio button text for welcome screen sections "Automatic privacy" and "Choose your theme"

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#13911]
## Steps to reproduce

1. Install Fenix
2. Open Fenix
3. Scroll to _Automatic privacy_

### Expected behavior

Text is not red. 

### Actual behavior

Text is red.

![Screenshot_2020-08-18-20-26-11](https://user-images.githubusercontent.com/152493/90580696-7e177800-e197-11ea-93f5-c693d2376348.png)

### Device information

* Android device: Moto G XT1031
* Fenix version: 80.0.0-beta.6 and nightly

**Comment by mcarare** [comment]
@yoasif Is your Android version 5.1.1 ?

**Comment by yoasif** [comment]
Just 5.1 @mcarare

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 8/31 with Xiaomi Mi4i (Android 5.0.2), and Samsung Galaxy Tab A6 (Android 5.1.1).

<img src="https://user-images.githubusercontent.com/40694158/91718655-79da5a00-eb9c-11ea-8f87-ee7ca2e2361a.png" width="300" height="550" />
