### ISSUE TITLE
[Bug] Unable to Share Photo in Instagram.com

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#13917]
## Steps to reproduce
1. Open Firefox for Android
2. Go to instagram.com
3. Click + button, and select a photo from device OR take a new phone.
4. Try to share it.
### Expected behavior
Photo should be sent.
### Actual behavior
Error pop-up occurs and unable to send photo.
### Device information
Asus Zenfone 3
* Android device: 8.0
* Fenix version: 80.0.0-beta.6

Note: I can share pictures other commonly used browsers, such as Chrome.
Connection type: LTE/Mobile

[fenix_instagramissue.zip](https://github.com/mozilla-mobile/fenix/files/5094413/fenix_instagramissue.zip)

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest **`Nightly Build 201106`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
