### ISSUE TITLE
[Bug] Cannot choose camera for webrtc video

### ISSUE THREAD

**Issue by mvvvmd** [mozilla-mobile/fenix#13919]
## Steps to reproduce

Go to https://test.webrtc.org/
Run the test.
Allow camera permission.

### Expected behavior

The user should be able to select the correct camera and change to a different camera during and after a call. 

### Actual behavior

The user cannot choose the camera, in my case the wrong camera chosen by FF.

### Device information

Xiaomi Mi 9T Android v10
Fenix version: 79.0.4

**Comment by Amejia481** [comment]
@mvvvmd which video call site you were using?

**Comment by mvvvmd** [comment]
> @mvvvmd which video call site you were using?

This test works https://test.webrtc.org/ , I was using Nextcloud Talk when I noticed the issue.

**Comment by Amejia481** [comment]
Thanks!

**Comment by mvvvmd** [comment]
I fixed the change made to the title, it is not a issue just in Nextcloud Talk (not Nextcloud) but any webrtc video. I have run into a lot more issues and switched away from FF on mobile to Vivaldi. The new version simply does not work, to many issues with it making it unusable.  I hope you are able to salvage the browser on mobile some day and that this bug report helps at least.

**Comment by kbrosnan** [comment]
Duplicate #10748
