### ISSUE TITLE
Visual labling of all search suggestion types

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#13913]
## User Story
- As a user, I want to easily and effortlessly distinguish between different types of search suggestions, so I can sort through  and find what I am looking for faster. 

We already do this for bookmarks (with a star) but do we do it for history, open tabs, and sync tabs?

### Acceptance Criteria
- I can easily distinguish between different search suggestion types.

**Comment by brampitoyo** [comment]
Hi @vesta0, I believe the visual labelling work has been completed by @NotWoods and @hakkikaancaliskan on #12622 

I’m not certain whether it has landed in product, though!

So far, we’ve covered:

- Search keyword suggestions 🔍
- Bookmarks ⭐️
- Open tabs 🗂
- Synced tabs 💻 📱 🖥

History items are all the other things that aren’t the 4 items above. It’s the most numerous results we’ll display, and the least specific, because you naturally create history items as you browse. We consider them the default/generic suggestion, so we don’t ‘tag’ it with any specific icon.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo We didn't labeled synced tabs because currently we don't show them in awesomebar. There is pr waiting for product decision for "we should add them or not".

**Comment by hakkikaancaliskan** [comment]
@brampitoyo 
We're adding synced tabs suggestions to awesomebar in https://github.com/mozilla-mobile/fenix/pull/11258
We're adding indicator to synced tabs suggestions in https://github.com/mozilla-mobile/android-components/pull/8157 and https://github.com/mozilla-mobile/fenix/pull/13923

**Comment by DavidJCobb** [comment]
> I’m not certain whether it has landed in product, though!

I don't know if my pointing this out is helpful but as of this writing, I do not see these indicators in the release build of Firefox for Android v79.0.5.

**Comment by cadeyrn** [comment]
It's implemented in Firefox 80+ (except synced tabs).

**Comment by bifleming** [comment]
Removing from Sprint, according to comments.

**Comment by hakkikaancaliskan** [comment]
I think this issue is done

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly 201019`** build using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

✔️ Search keyword suggestions
![rsz_1screenshot_20201019-100931](https://user-images.githubusercontent.com/51314259/96416952-5f664980-11f9-11eb-825f-67afa00a868a.png)
 
✔️ Bookmarks 
![rsz_screenshot_20201019-100958](https://user-images.githubusercontent.com/51314259/96417065-86bd1680-11f9-11eb-8e7c-757f51a18241.png)

✔️ Open tabs 
![rsz_screenshot_20201019-100812](https://user-images.githubusercontent.com/51314259/96416802-2928ca00-11f9-11eb-9b4c-14267aa4dc72.png)


► Synced tabs:
✔️ Phone
![rsz_screenshot_20201019-100519](https://user-images.githubusercontent.com/51314259/96416571-d818d600-11f8-11eb-9385-25c842b81561.png)

✔️  Desktop
![rsz_3screenshot_20201019-100624](https://user-images.githubusercontent.com/51314259/96416724-0a2a3800-11f9-11eb-8152-b1189fb7d738.png)

❓  Tablet 
![rsz_1screenshot_20201019-102406](https://user-images.githubusercontent.com/51314259/96417231-b9ffa580-11f9-11eb-9364-4c118b1c93e3.png)
**It looks like the phone sync tabs icon is displayed when displaying the tablet sync tabs.**

Noticed in https://github.com/mozilla-mobile/fenix/issues/12622#issue-657862130 that the tablet sync tabs icon should actually be ![image](https://user-images.githubusercontent.com/51314259/96414852-54f68080-11f6-11eb-959a-1302b9f19da4.png)

@brampitoyo could you please review and advise? ☺️ 
I'll remove the QA needed label until further notice.

**Comment by brampitoyo** [comment]
@AndiAJ You’re right. The Tablet icon should be its own graphic, which is different from the Phone icon.

Other than that, everything else looks good!

**Comment by gabrielluong** [comment]
I am assuming we should close the issue when eng:qa:verified

**Comment by AndiAJ** [comment]
Hi, I've filled a new issue #16049 for the remaining Tablet synced tabs inconsistency
