### ISSUE TITLE
[Bug] Addon settings page not scrollable on small devices, can't install addons

### ISSUE THREAD

**Issue by Aractus** [mozilla-mobile/fenix#13915]
## Steps to reproduce

Settings > Add-ons > Click + on chosen Addon.

### Expected behavior

Installation button to install addon

### Actual behavior

Cannot scroll page to reveal hidden install button

### Device information

* Android device: Unihertz Jelly
* Fenix version: 80.0.0-beta.6

Note that although I'm using Beta, this issue almost certainly affects FF for Android 79 as this issue was present months ago when I first tried this version on my phone (and I haven't used it since).

### Screenshot

![Screenshot_20200819-121857](https://user-images.githubusercontent.com/16506413/90586162-0a409400-e1c6-11ea-8db5-c872b86c7c81.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5124)

**Comment by mcarare** [comment]
Note: This is an issue with phones with small screen sizes. It can also be reproduced using a higher text size or in landscape orientation.

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01 using a larger font size.
