### ISSUE TITLE
Enable recommended addon "Cookie Autodelete"

### ISSUE THREAD

**Issue by fichtennadel** [mozilla-mobile/fenix#13925]
## User Story
- As a user, I want fenix to support the recommended addon Cookie Autodelete (https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) so I can browse the web in privacy while keeping up the required functionality of web sites. This used to work fine in fennec.

## Dependencies
- none known 

### Acceptance Criteria
- I can use the addon in fenix: it's enabled in the addons menu, I can change its options, the addon behaves like in fennec.

**Comment by cadeyrn** [comment]
> We are not keeping open requests for specific addons. You can watch the open extensions issues.

#13401

**Comment by drwetter** [comment]
> You can watch the open extensions issues.

? where

**Comment by cadeyrn** [comment]
#13059 for example - where you already commented.

**Comment by s-ankur** [comment]
#13059 is only open due to @data-sync-user's shenanigans

**Comment by fichtennadel** [comment]
This is not about "any", but about a recommended extension, which were announced to be supported.

**Comment by cadeyrn** [comment]
@fichtennadel It was not announced that all recommended extensions are already supported in Firefox 79. And I don't know why you gave a thumbs down to **_my_** comment - it's not my decision at all. I only quoted an explanation from another issue.

**Comment by drwetter** [comment]
Didn't mean to step on your toes but here's the explanation.

Because I didn't know how you are involved in this and because this issue is known since February. 

As mentioned elsewhere in fenix I just have one extension left.


-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by fichtennadel** [comment]
> @fichtennadel It was not announced that all recommended extensions are already supported in Firefox 79. And I don't know why you gave a thumbs down to **_my_** comment - it's not my decision at all. I only quoted an explanation from another issue.

sorry, didn't see this was a quote. you're labelled as contributor, so your comments have a somewhat official touch.

frustration is very high in the community with this forced update, which broke so much of what made FF unique. Just have a look at the reviews in play store.

I've tried to stay positive and contribute by filing objective issues, but on the other hand I'm really frustrated by this upgrade from hell (TM) and therefore a little bit sensitive when I get the impression that my issues are closed too lighheadedly. And maybe it wasn't the brightest idea to release software with 3k open issues, but that's just my two cents.

**Comment by cadeyrn** [comment]
> sorry, didn't see this was a quote. you're labelled as contributor, so your comments have a somewhat official touch.

I see how this can be confusing. Github labels everyone as contributor once they contributed at least one pull request to a project.

**Comment by drwetter** [comment]
The frustration is also pretty high here. I couldn't phrase this better as @fichtennadel as in https://github.com/mozilla-mobile/fenix/issues/13925#issuecomment-676635509 .

On top of that: Google may gain even more market share and privacy looses more and more importance.

**Comment by NotWoods** [comment]
We would like to expand our support to other add-ons but we are not keeping open requests for specific ones, even those in the recommended add-ons program. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.

**Comment by drwetter** [comment]
This isn't a satisfying answer to me. at least. Maybe Mozilla should spent me resources on getting things done than on this blog and seeking help from the community maybe.

a) A blog is a one way street.
b) there's liitle useful information in all that text in there. Specifically how many add-ons are enabled and how many disabled. 
c) for CAD specifically the author is waiting >6 months for a recommended add-on for attention from Mozilla. So do the users. What about a timeline?

**Comment by fichtennadel** [comment]
Thanks for closing this, so it's completely clear how much appreciation for community contribution for developing add ons and openness by hiding issues in blogs is currently in place.

**Comment by joenepraat** [comment]
@NotWoods I don't know what Mozilla is doing here, but it is not the first time Mozilla changes something dramatically, resulting in alienating their user base. 

It's already eight months ago you closed the issue, with referring to an empty blog-post. The add-on-combi _Cookie Autodelete_ and _I don't care about cookies new Firefox_ where for me two essential add-ons. It made sure browsing the web on my Android phone was secure and user friendly. This is still the case on my desktop, so about time this is re-added to mobile.

**Comment by xss** [comment]
It is impressive with what amount of determination Mozilla seems to try to purposefully push their user base away.

For exactly the reason and lacking add-on combo @joenepraat described, current Firefox mobile remains unusable for me. I don't see why I should let Mozilla bully me into using an incomplete app (see still missing cookie exception settings in current version) after its previous versions where working perfectly fine until a year ago. And being forced by Mozilla to stick to that last working but way outdated version 68 is plain unacceptable.

All in all, they bully and torture us, forcing us to look for alternatives. And slap anyone in the face (just to use unoffensive wording here) who is a bit more concerned about web privacy than the average Chrome user, knowing very well that there are no easy alternatives. Well done, Mozilla, keep that up. But please stop claiming to care about your users and privacy.

**Comment by xandro0777** [comment]
Very sad reading. Zero technical reasons given. I understand that some addons may cause problems and that you can not review everything but not giving expert users any option to try them is so Microsoft.

Meanwhile all Mozilla attempts at privacy are blatantly insufficient. Get a FirefoxVPN? Isn't that totally useless if CAD doesn't work? Who is supposed to buy your VPN?

But glad I can install the "Tomato Clock" addon, that sure helps a lot.
