### ISSUE TITLE
Re-enable add-ons

### ISSUE THREAD

**Issue by lineinthesand** [mozilla-mobile/fenix#13928]
### What is the user problem or growth opportunity you want to see solved?
There are several add-ons which do not work anymore in FF mobile 79, most notably the Video background play fix (https://addons.mozilla.org/en-US/firefox/addon/video-background-play-fix/), Simple Gesture (https://addons.mozilla.org/en-US/firefox/addon/simple-gesture/) and Tablet Gestures (https://addons.mozilla.org/en-US/firefox/addon/tablet-gestures/?src=search) 

### How do you know that this problem exists today? Why is this important?
I was upgraded to FF mobile 79 without notice that many features and workflows would break. I need the background play fix because I want to be able to listen to a video's audio track being played while having the screen switched off or while browsing in other tabs. I need gestures to open, close, reload and switch between tabs easily without having to tap tiny buttons (accessibility!!).  

### Who will benefit from it?
Especially, but not limited to, visually disabled persons. But really: people who like their freedom and customizability of a browser, especially if the browser is lacking many features without these add-ons.

**Comment by cadeyrn** [comment]
There are already more than enough issues about add-ons support, no?

**Comment by s-ankur** [comment]
#5315 was closed unfortunately, so per addon issues are the only way to address the feature request

**Comment by cadeyrn** [comment]
@s-ankur There are still more than enough open issues about expanding the add-on support. And as you know (since you commented in #13401) issues for specific add-on requests should not be opened:

> We are not keeping open requests for specific addons. You can watch the open extensions issues.

**Comment by s-ankur** [comment]
Yeah I was confused even then. For example #13058, #12393, #12341 etc are still open. So is this only about newer addon requests?

**Comment by cadeyrn** [comment]
#13058 was also closed but recently re-opened by the data-sync-bot that was out of control. But yes, I guess there are quite a lot of old issues that could be closed (not only about add-ons). With almost 3.000 open issues it's difficult to know or find every issue. ;-)

**Comment by NotWoods** [comment]
I agree with everything @cadeyrn stated here. There are lots of issues and we do our best to get through them all, but it's not instantaneous. We would like to expand our support to other add-ons but we are not keeping open requests for specific ones. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.
