### ISSUE TITLE
Add suggestion indicator to synced tabs suggestions in awesomebar

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#13922]
Parent issue: #12622

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200921-115410](https://user-images.githubusercontent.com/51314259/93749158-18893200-fc02-11ea-9034-e95617c6b208.png)


Will also close @softvision-miralobontiu 's issue #13807. ☺️
