### ISSUE TITLE
[Bug] Tab history of normal browsing tab shows up in on PWA -> long press back button

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13934]
## Steps to reproduce
Open a pwa
long press back button

### Expected behavior
Not sure, nothing maybe?

### Actual behavior
Tab history of a random regular tab shows up

### Device information

* Android device: Asus Zenofone
* Fenix version: Fenix Nightly

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that the issue is reproducible on the latest Firefox Preview Nightly 200820 (Build #2015759027).
### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by ekager** [comment]
Same happens on custom tabs

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Beta 82.0.0-beta.1 (Build #2015765523).
### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)
