### ISSUE TITLE
[Bug] missing empty state for downloads view

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#13939]
/cc @kglazko

### Steps to reproduce

0. don't have any downloads
1. open the new downloads view

### Expected behavior

There should be a small text or something if there are no downloads, like in bookmarks folders.

### Actual behavior

Empty screen.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision 2e62dd5c874e3c88edaae21b1bb5f2a548d1d27a

**Comment by liuche** [comment]
Will we need this for Downloads to ship @apbitner ? If so, could you see if Betsy has time to get us some empty state strings?

**Comment by kglazko** [comment]
There is already a string, this was an accidental deletion as part of the cleanup on the last PR from an earlier version where it was functional :( Re-enabling now

**Comment by kglazko** [comment]
@cadeyrn @liuche @boek I just pushed a fix for this

**Comment by sflorean** [comment]
Verified as fixed on Nightly 8/20, "No downloads here" is displayed.
