### ISSUE TITLE
Make start page (new tab page) configurable

### ISSUE THREAD

**Issue by lineinthesand** [mozilla-mobile/fenix#13930]
### What is the user problem or growth opportunity you want to see solved?
The start page contains something called "Collections" which is visually distracting but cannot be removed, neither via menu nor about:config (as this does not work anymore).

### How do you know that this problem exists today? Why is this important?
I was upgraded to FF mobile 79 without prior notice of its many changes severly impeding its accessibility and configurability.

### Who will benefit from it?
People who want a clean start page without visual distractions and people who like to customize the look and feel of their browser

**Comment by cadeyrn** [comment]
Another duplicate: #12377.

**Comment by s-ankur** [comment]
This is understandable, the most [highly requested feature](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aopen+collections+sort%3Areactions-%2B1-desc) about collections is actually the ability to disable them.

**Comment by liuche** [comment]
Please follow along in the duped issues - we're actively working on the collections requests!
