### ISSUE TITLE
UX Polish and Custom Icons For #349 View Downloads in Browser

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/fenix#13935]
## User Story
- As a user, I want View Downloads to change icons in the list depending on the type of file the download is
- As a user, I would like to see clearer copy when viewing the empty state of downloads, bookmarks and history

## Dependencies
- List dependencies on other issues/teams etc.

### Acceptance Criteria
- I can do …  (e.g. add a bookmark)
- Empty state copy for the three sections should be as follows:
  - **Downloads:** `No downloaded files`
  - **Bookmarks:** `No pages bookmarked`
  - **History:** `No browsing history`

**Comment by brampitoyo** [comment]
> As a user, I want View Downloads to change icons in the list depending on the type of file the download is

@kglazko Hi! @apbitner and I are on track to deliver the file type icons by the end of the week.

I’ve got the assets ready for you to try in product:
https://drive.google.com/drive/folders/1Kgbotds9orO1ORB6ikfZY0kxZLYQWol7?usp=sharing

The file names are all prefixed with `file-type`
- apk
- audio (use `note`)
- default (used for generic or unknown file type)
- document
- image
- video
- zip

And we should be using the same outer frame as the one used elsewhere in the product – rounded rect with border.

<img width="360" src="https://user-images.githubusercontent.com/51007/90711033-cea3e800-e2f3-11ea-91ba-c654189f6edc.png">

**Comment by brampitoyo** [comment]
@kglazko wrote:

> …our default currently in History/Library is rounded icons. Is it ok to keep them consistent for this iteration?

Yes. In this iteration, let’s keep them rounded – consistent with History, Library, Bookmarks, etc.

In the future, will it be easy to re-change file types to be consistent with all other frames, when they all go from rounded → rounded rectangle? Our intention is to make sure that total consistency will happen at some point.

**Comment by softvision-miralobontiu** [comment]
Hi all,
Verified on the latest Nightly build from 8/26 with Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1), that:
- the icons from the Downloads page are rounded, 
- the icons represent the type of downloaded files (image, audio, video, zip, etc),
- and that when there are no downloaded files, the empty state has "No downloads here" text displayed.

![downloads](https://user-images.githubusercontent.com/40694158/91295293-86793f80-e7a3-11ea-858c-7d1e48c4047f.png)

@brampitoyo, @kglazko - the trashcans are not displayed yet, the user cannot remove any of the downloads from the Downloads page. Should I file a new issue, or leave this one open?
I'll remove the qa:needed label until further notice.

**Comment by kglazko** [comment]
@softvision-miralobontiu Yep, those features (the trashcans/deleting) aren't yet implemented and are represented by another issue in the Meta!

**Comment by Amejia481** [comment]
I think we could close this issue, please feel free to reopen otherwise.
