### ISSUE TITLE
[Bug] UBO homepage -> Reset to default settings button hidden due to bottom toolbar

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13931]
## Steps to reproduce
Set toolbar to bottom in settings
open UBlock Origin Addon homepage 
scroll down and you are unable to see the Reset to default settings button

### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200819-225150_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/90669039-a02ff980-e26e-11ea-83e3-6fa1284a38b2.png)
There is actually a third button here but you can't see it

**Comment by csadilek** [comment]
Thanks, we're already tracking this in https://github.com/mozilla-mobile/fenix/issues/11858.
