### ISSUE TITLE
Change strictMode penalty to death so it's harder to ignore

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#13943]
Blocked by https://github.com/mozilla-mobile/fenix/issues/13368

**Comment by mcarare** [comment]
@mcomella Are you referring only to `ThreadPolicy`? Or also `VmPolicy`. `VmPolicy` has multiple violations that could block changing policy to death.

**Comment by mcomella** [comment]
> @mcomella Are you referring only to `ThreadPolicy`? Or also `VmPolicy`. `VmPolicy` has multiple violations that could block changing policy to death.

@mcarare Just the main thread policy right now – specifically, we're trying to prevent main thread IO like network access and disk reads.

**Comment by mcomella** [comment]
Addressed with https://github.com/mozilla-mobile/fenix/pull/15064.
