### ISSUE TITLE
Turn off the messaging around Nightly/Beta channel consolidation

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#13949]
We're now quite far out from the channel consolidation, so we should turn off the changes that we made in #9208.

**Comment by Mugurell** [comment]
> We're now quite far out from the channel consolidation, so we should turn off the changes that we made in #9208.

Turn off meaning hide this code behind an if check but keeping it in the project so that it may be reused later,
Or basically a revert commit?

**Comment by liuche** [comment]
Let's keep the prompt for future messaging, but we don't need to be showing this specific message anymore for new nightly users.
