### ISSUE TITLE
[Bug] UninitializedPropertyAccessExceptionkotlin.jvm.internal.ArrayIteratorKt in throwUninitializedPropertyAccessException lateinit property browserToolbar has not been initialized

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#13957]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9012219/?query=release%3Aorg.mozilla.firefox_beta-80.0.1-beta.2

lateinit property browserToolbar has not been initialized

Is this related to #13761 ?

**Comment by liuche** [comment]
@mcarare could you take a look to see if this would be a dupe of the #13761 bug that you already fixed? or if it may be something else?

**Comment by mcarare** [comment]
@liuche, this looks like a scroll event in a custom tab opened from outside Fenix and we try to force expand the toolbar in order to not get stuck with no way to show the browser toolbar, not related to #13761.

**Comment by Mugurell** [comment]
Interestingly this only seems to happen on Android 8 devices.

**Comment by Mugurell** [comment]
A speculative fix for this was merged in AC for https://github.com/mozilla-mobile/android-components/issues/8305
Let's see if it will appear anymore in Sentry.

**Comment by liuche** [comment]
I'm going to close this issue to consolidate with #15116 - similar trace, but may have been caused by something else because it's not just Android 8 devices.
