### ISSUE TITLE
[UX] It's too easy to click `Close all tabs` button while clicking the `Share all tabs` in Private browsing mode and perhaps in normal browsing mode too. 

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#13963]
***The plan to making it not easier to close all tabs... to avoid... accidents?***

**_The_ Problem** 

It's too easy to click on the `Close all tabs` button while clicking the `Share all tabs` in Private browsing mode and perhaps in normal browsing mode too.  

**Possible Reasons**

* The button is too short in width and also relatively very smaller in size compared to normal browsing mode.

* Thus `Close all tabs` and `Share all tabs` are too close in PBM.

* And thus consequently they are very near the thumb finger while holding the phone with one hand. 

* The result is if the user is even slightly inattentive while clicking `Share all tabs` the user might end up clicking the `Close all tabs` button instead. And absent of an `Undo closed tab` (which is expected) makes this situation even worse.

* In the normal browsing mode as well I think there shouldn't be other buttons. At least in case of Fenix.

**Possible Solutions (rough thoughts)**

* Moving the button `Share all tabs` to somewhere else?

* Making the menu size a bit bigger so as to not accidentally be clicked by the user?

* Removing the `Save to collection` as well as `Share all tabs` buttons and keeping only the `Close all tabs` button?

Thus keeping only keeping the `Close all tabs` button in the normal browsing mode as well as Private browsing mode to maintain consistency an well as remove any chance of accidentally clicking any other buttons?

In turn, this situation presents another problem, with the `Share all tabs` gone there's no easy way to...well...share all tabs.

How about making the New tab FAB button dynamically change to a `Share` button when the user long presses an open tab in the tabs tray? And making the 3-dot menu button also dynamically have a `Select all tabs` button for a while  instead `Close all tabs` button in it until the user is done with the tab sharing?

As for where to keep the `Save to collection` 3-dot menu button then we already have such a button at the bottom of the tabs tray. So we have a solution? 

I'm not sure which one would work. I'm not even sure if they're feasible engineering-wise. Perhaps we might need an entirely different solution altogether?

For example, Chrome browser keeps these buttons on the 3-dot menu

`New tab`

`New incognito tab`

`Close incognito tab`

`Settings`

You might say Chrome browser also places other buttons in the 3-dot menu why change that in Fenix? Well, for that I'd say I have never accidentally clicked others button unintentionally in Chrome browser unlike in Fenix which happens frequently with me. Part of the problem with Fenix might be with Fenix changing menu sizes across the browser in a very random dynamic fashion unlike any other mainstream browser I haves seen. Brave, Chrome, Vivaldi, Kiwi browser, etc. don't do this, they have a consistent pattern and button clickability across the browser's interface.

![Screenshot.jpg](https://user-images.githubusercontent.com/69946395/90726136-c1193e80-e2b0-11ea-9dbc-7a915930a69c.jpg)

**Comment by Poopooracoocoo** [comment]
Another solution would be to add a confirmation dialog when the user closes more than x tabs. x could be 10.

**Comment by ekager** [comment]
Share all tab and close all tabs are now separated in normal browsing. And share all was removed from private.
