### ISSUE TITLE
Focus address bar when invoked as "assist app"

### ISSUE THREAD

**Issue by rozmansi** [mozilla-mobile/fenix#13962]
Firefox is my choice as the default assist app on Android (Settings -> Apps & notifications -> Default apps -> Assist app). This allows me to quickly search online by long pressing the Home button any time I get an idea, any time on my phone. The home button is almost always there.

Now, the legacy Firefox had this feature that when started as the Assist app, it put focus into the address/search edit box, making the keyboard pop up. This was really handy, as it eliminated an extra click to get the keyboard and start typing the search.

I was wondering, if there isn't that big deal, could you please reimplement this workflow.

The rationale behind this is to get from the spark in your head to the online search results in as few clicks as possible. I believe this task is one of the most frequent tasks we do on our phones. Imagine: a second saved times number of uses you literally save a lifetime here! 😀

**Comment by s-ankur** [comment]
Duplicate of #3722. Firefox is my default assist app as well

**Comment by rozmansi** [comment]
Thanks! I must have asked the GitHub wrong when searching for open issues.
