### ISSUE TITLE
[Bug] Firefox icon does not show when invoking Firefox as the assist app

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13966]
## Steps to reproduce
Set firefox as the assist app (#390)
invoke assist app by long pressing home button

### Expected behavior
Firefox logo shows up near the home button

### Actual behavior
a white circle shows up

### Device information
This might be OS specific so it would be good if anyone could test it on another device 
* Android device: Asus Zenfone (LineageOS16)
* Fenix version: Nightly 200818 06:01 (Build # 2015758643)

**Comment by LittleAngelwings** [comment]
I can't reproduce this issue with

Nightly 200819 06:01 (Build #2015758833)
AC: 54.0.20200818130156, 70fc79507
GV: 81.0a1-20200814094524
AS: 61.0.10

and Samsung Galaxy Tab A (SM-T580) with Stock Android 8.1.0 and on Huawei P Smart with Android 9.1.0 EMUI

**Comment by s-ankur** [comment]
Might be LineageOS specific then

**Comment by s-ankur** [comment]
Very weird: icons appears if you are in landscape view, but not portrait

**Comment by s-ankur** [comment]
Same happens with focus btw. If and when someone solves this, s port the fix to focus as well

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on the latest Firefox Preview Nightly 210406.

### Devices used:
- Huawei P Smart (Android 9)
