### ISSUE TITLE
[Bug] First item in new about libraries is hidden

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#13970]
## Steps to reproduce
Open the new about libraries page.

### Expected behavior
All libraries are shown.

### Actual behavior
The first library is not shown. The first displayed one is `android arch-common` in nightly, but is `absl` in beta. Also, the scroll bar starts hidden behind the toolbar. I think `absl` is also hidden behind it. cc @gilbsgilbs 
### Device information

* Android device: ?
* Fenix version: ?

**Comment by mcarare** [comment]
This should also be already fixed in https://github.com/mozilla-mobile/fenix/pull/13967.

**Comment by gilbsgilbs** [comment]
I confirm #13967 should fix this along with making the toolbar theme consistent and making the nav animation work.
