### ISSUE TITLE
Implement "Pocket is better on the app message/functionality" when pocket is not installed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#13976]
### What is the user problem or growth opportunity you want to see solved?
As a user, I want to be redirected to the PlayStore when accessing Pocket website to have a button with a redirection to Play Store (if not installed)
### How do you know that this problem exists today? Why is this important?
Note that there are websites like `Twitter` or `Reddit` with this option.
### Notes
When accessing the Pocket website and the app is not installed, please note that the `Open In-App` button is missing, even tho for many other websites the button is present even when the app is not installed (with a redirection to the Play Store).

![20200820-150003](https://user-images.githubusercontent.com/42831109/90767981-ba151f00-e2f6-11ea-9bb5-e2a5f3057564.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5201)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807376

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
