### ISSUE TITLE
[Bug] Screenshots are not allowed in PB when the app is in recent apps view 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#13978]
## Steps to reproduce
1. Enable the screenshots in PB.
2. Access any website in PB.
3. Tap on the recent apps button.
4. Tap on the `Screenshot` button.
### Expected behavior
The screenshot is successfully made.
### Actual behavior
The `This action isn`t allowed by the app or your organization` text error is displayed.
### Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 8/20.**

![20200820-163918](https://user-images.githubusercontent.com/42831109/90777718-79bc9d80-e304-11ea-98f1-f72c0da40331.gif)

**Comment by mobd** [comment]
Possibly related to #13869

**Comment by ekager** [comment]
Does it work after an app restart? It looks like we made some changes here in #11827 and it's possible it's not taking effect until restart

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201218-125704](https://user-images.githubusercontent.com/51314259/102607980-d8b6e580-4131-11eb-8500-432b38b9705a.gif)

**Comment by mobd** [comment]
I ran into #13869 again today with Nightly 210108 17:01 (Build #2015786187). I don't know if this is a regression or if it was never fixed since it only happens occasionally
