### ISSUE TITLE
[Bug] Notifications entry in settings doesn't do anything

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#13977]
## Steps to reproduce
Go to settings and click on notifications.

### Expected behavior
Android settings to control notifications shoulf be opened.

### Actual behavior
A popup says "The app wasn't found in the list of installed apps".

### Device information

* Android device: Huawei Nova 6
* Fenix version: Nightly 200820 03:27 (Build #2015759003)
AC: 56.0.20200819190136, fb5d4191c
GV: 81.0a1-20200818092452
AS: 61.0.10

**Comment by hwinnemoe** [comment]
Duplicate of #13938

**Comment by mobd** [comment]
Sorry, didn't see that one
