### ISSUE TITLE
[Bug] "Report site issue" is not working on Nightly

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#13973]
## Steps to reproduce
1. Launch Fenix and visit la website;
2. Go to the three dot menu and tap Add-ons -> Report Site Issue;
### Expected behavior
The webcompat.com page opens.
### Actual behavior
The webcompat.com page does not open. 
### Notes

![20200820_145415](https://user-images.githubusercontent.com/48799384/90767243-87b6f200-e2f5-11ea-8386-bcf4973cc7d9.gif)
Also reproducible in private mode.
### Device information

* Android device: Motorola Moto G6 (Android 8)
* Fenix version: Nightly 200820 Build #2015759001 GV 81.0a1, from 8/20
This is not reproducible on Firefox Beta 80.0.1-beta.1, GV 80.0, from 8/15

**Comment by csadilek** [comment]
Seeing this error quite a bit in the console and when clicking the browser action ("Report site issue"):

```
[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/Troubleshoot.jsm :: <TOP_LEVEL> :: line 25"  data: no] 6 Troubleshoot.jsm:25:34
    <anonymous> resource://gre/modules/Troubleshoot.jsm:25
    <anonymous> jar:file:///data/app/org.mozilla.fenix-klil-iVhoNAtsPc3fVO4cg==/base.apk!/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.js:12
    asyncLoaded resource://gre/modules/ExtensionCommon.jsm:1664
```

**Comment by csadilek** [comment]
Filed in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1660264

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-102757](https://user-images.githubusercontent.com/51314259/91274320-2aa0bd80-e787-11ea-88bc-5fdf9dcde873.gif)
