### ISSUE TITLE
[Bug] "This app wasn't found in the list of installed apps." toast when Fenix settings » Notifications clicked

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#13980]
The toast message comes from the Settings app (com.android.settings)

I'm not sure what else to provide, probably this feature isn't yet fully implemented (I hadn't updated Nightly for a while so I'm not sure how new it is)

# Device information

* Android device: 10
* Fenix version: Nightly 200820 03:27 (Build #2015759003)

**Comment by hwinnemoe** [comment]
Duplicate of #13938

**Comment by astarq** [comment]
Closed as duplicate of #13938
