### ISSUE TITLE
[Bug][Regression] Open in app opens the Chrome browser if Pocket onboarding is not done/skipped

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#13982]
## Steps to reproduce
1. Install Pocket from PlayStore but don't launch it (don't get past the onboarding of Pocket).
2. Launch Fenix and access Top Articles from the top sites.
3. Tap on the 3 dot menu button and then `Open in Apps`.
### Expected behavior
The Pocket app is correctly launched.
### Actual behavior
The same page is opened in Google Chrome.
### Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 8/20.**
* Pocket Version: **7.31.0.0**

### Notes
As long as the Pocket onboarding is not skipped/done when opening Pocket from Fenix will open the Chrome Browser all the time.
After the onboarding is done/skipped the Pocket app will open correctly.

![20200820-181035](https://user-images.githubusercontent.com/42831109/90790743-12591a80-e311-11ea-87d2-afa7b652b9da.gif)

**Comment by rocketsroger** [comment]
Looks like this is an issue on the Pocket app side.  I've notify the app developer.  I'll close this issue since that this is not something Android Component can fix.
