### ISSUE TITLE
Support client certificates

### ISSUE THREAD

**Issue by oakkitten** [mozilla-mobile/fenix#13988]
*This issue is not the same as #2286 or #3728, which seem to be about trusting user-provided CAs.*

Some servers ask the clients to identify themselves using certificates. These certificates, as well as private keys, commonly distributed in PKCS 12 (.pxf or .p12) or PEM containers, can be imported either directly into the app key store or installed system-wide. Upon connecting to a website that sends a `CertificateRequest` along with the list of matching issuers, the client would identify itself using one of the matching certificates.

Fenix doesn't seem to support these at all.

#### What is the user problem or growth opportunity you want to see solved?

Users can't identify themselves using client certificates and are forced to use other browsers.

#### How do you know that this problem exists today? Why is this important?

You can try it using https://badssl.com/, look for section titled “Client Certificate”. It's important as it's a required authentication method in some organizations.

#### Who will benefit from it?

Users who need to identify themselves using certificates.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5221)

**Comment by gjvnq** [comment]
I am with the same problem and I am considering writing a patch to implement this.

Hey devs, should I start working on it or is this feature mostly finished? Also, ate there any known forks or branches that stareted to implement this but gave up?

**Comment by Webbeh** [comment]
This is most certainly, and very sadly, a not-so-well-known feature that's certainly going to die in most browsers, and it's a massive shame.

Certificate based authentication was my go-to for anything that required more security than what a simple password could offer, and it's almost unusable on mobile...

If anyone is willing to implement it, I would definitely appreciate it and support it. 

Either that or FIDO/U2F/OTP based authentication using Yubi/Nitro-keys in a similar fashion...

**Comment by Dunexus** [comment]
@Webbeh See https://github.com/mozilla-mobile/fenix/issues/1340 for Webauthn implementation

**Comment by jonalmeida** [comment]
We now have the ability to do this from the Secret Settings hidden UI.

1. Go to Settings -> About Firefox.
2. Tap the logo 5 times.
3. Go back to the main settings screen.
4. Click on the newly visible "Secret Settings" menu option.
5. Enable 'Use third party CA certificates'.

This feature is available in nightly and beta so far, with release getting it in a month.

**Comment by gjvnq** [comment]
Thanks!

Gabriel Queiroz

**Comment by PiQuer** [comment]
@jonalmeida This Issue is about client certificates, not third party CA certificates. I'm using nightly 91.0.20210601143118 and have activated the mentioned setting, client certificates are still not supported. Am I missing something?

**Comment by grigorig** [comment]
Yeah, client certificates are a completely different feature. And as far as 3rd party CA certificates go, I wonder why Firefox can't use Android's certificate store for that? Android has built-in features to manage CA certificates.

**Comment by Webbeh** [comment]
@jonalmeida please reopen.

**Comment by jonalmeida** [comment]
You should be able to add client certificates to the Android OS certificate storage, and with this toggle enabled, they should be used.

**Comment by mozkeeler** [comment]
> Yeah, client certificates are a completely different feature. And as far as 3rd party CA certificates go, I wonder why Firefox can't use Android's certificate store for that? Android has built-in features to manage CA certificates.

This is off-topic, but that's exactly what the feature @jonalmeida mentioned a few comments ago does.

**Comment by fancsali** [comment]
+1

**Comment by danninov** [comment]
This feature is really useful for implement zero trust, as the website can verify the client/users using mTLS. Hope Mozilla implement this feature, either using Android certificate store or Firefox own store. All other browser based on Chromium (Opera, Edge etc) support this

**Comment by tigermick** [comment]
Hi,
I can't use android firefox in my job because it isn't possible to use my client certificate to access to my compagny website...
I'im waiting this feature too !

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1358996

**Comment by PiQuer** [comment]
> User feedback: https://support.mozilla.org/en-US/questions/1358996

The thread you posted is about using third party CA certificates. This issue is about using client certificates, which is a different concept.

**Comment by iam468** [comment]
+1 I`m using firefox mobile, but for this feature shoud use Chrome. Even default samsung browser are working with client certificates. Hope sometime Firefox will also! Thanks!

**Comment by smerschjohann** [comment]
This feature came with Firefox 90 on other platforms, so hopefully it can be adopted for the mobile platform soon :)

**Comment by grigorig** [comment]
I don't understand, client certificates have been supported on the desktop version since... forever?

**Comment by smerschjohann** [comment]
I mean this: https://blog.mozilla.org/security/2021/07/28/making-client-certificates-available-by-default-in-firefox-90/ you could use them, if manually activated yes.

**Comment by t00** [comment]
In our business we are securing potentially vulnerable software using client certificates, distributed to trusted people manually or with MDM. Either way, this is the best solution so far to prevent vulnerabilities in public facing websites to ruin our day. Think Log4J, Jenkins bugs etc. Without VPN sites are secure on TLS level, miles better than any form of authentication. I use it for my home automation too.

Firefox is my go to browser, thanks to extenstion support on mobile. Client certificate support is a serious flaw, as is less coverage of its benefits.

**Comment by fancsali** [comment]
Not only would this get the Android version on the same level as Firefox any other platform, it's certainly one of those features that seems to make Firefox more and more a niche browser as opposed to (one of) the leading forces in the browser market.

To be quite honest, my understanding is that this feature is not really on its way out, as most other browsers seem to support it. So I'd argue it's completely worth porting onto Android.

Please, pretty please... ;)

**Comment by fancsali** [comment]
Indeed, that's the unfortunate reality of this. And I really don't like the
world that lies ahead, when there's only one browser (be it Chrome or any
other one...)

**Comment by tasism** [comment]
Just bumping this to show my support. We had to switch to Edge on Android devices as the recommended browser as this feature is lacking. And it is only normal to expect that users will eventually want to switch to Edge on their laptops/desktops too. Please assign some priority to this, there are quite a few companies that use client certificates for strong user authentication.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813930

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
