### ISSUE TITLE
[Bug] Files displayed in the Downloads section after being canceled

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#13983]
## Steps to reproduce
1. Go to https://www.thinkbroadband.com/download and download a file.
2. Open the notification bar and tap on "Cancel" from the download notification.
3. Go to Menu -> Downloads.

### Expected behavior
The file is not displayed.

### Actual behavior
The file is displayed.

### Device information
* Android device: Samsung Galaxy Note 10 (Android 10)
* Fenix version: Nightly 8/20

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-104243](https://user-images.githubusercontent.com/51314259/91275929-7a808400-e789-11ea-8166-9070814cee6b.gif)
