### ISSUE TITLE
[Bug] uBlock import filed is not scrollable

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#13986]
This is a dup of https://github.com/uBlockOrigin/uBlock-issues/issues/1216 as @gorhill says:

> I consider this a Firefox issue, if you set the browser toolbar to be displayed at the top, the bottom of uBO's panes shows fine.

![ScreenRecord-2020-08-20-17-57-40](https://user-images.githubusercontent.com/14617699/90788806-d58c2400-e30e-11ea-8a1e-55853256e093.gif)
![image](https://user-images.githubusercontent.com/14617699/90788495-8b0aa780-e30e-11ea-8e51-1610674599b8.png)
![image](https://user-images.githubusercontent.com/14617699/90787799-c5c01000-e30d-11ea-933c-4bca9055f2be.png)

**Comment by hwinnemoe** [comment]
Duplicate of #11858

**Comment by 532910** [comment]
Thank you!
