### ISSUE TITLE
FNX-43 ⁃ Add new quote from Book of Mozilla to about:mozilla

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#1398]
### Why/User Benefit/User Problem
Since this will be a major launch it would be a nice to have new quote for `about:mozilla`. This was last done for 57 which was a major release as well.

### What / Requirements
A new quote from the book of mozilla.

### Acceptance Criteria (how do I know when I’m done?)
A quote is seen (for Fenix only?).

Since @SeburoSUMO worked on [the last update][0], I wonder if he'll be interested in this as well. :grinning:

[0]: https://bugzilla.mozilla.org/show_bug.cgi?id=1370613

**Comment by bifleming** [comment]
@cpeterso

**Comment by cpeterso** [comment]
Fenix can add an about:mozilla page without GV changes.

**Comment by cpeterso** [comment]
I see now that GV has its own about:mozilla page, so we can update GV's page (if we want a generic page accessible in all GV-powered app) or override it in Fenix with a custom page. If Product or UX want to rewrite GV's about:mozilla page, just let me know what content you would like to use. I can then file a GV bug in Bugzilla.

**Comment by vesta0** [comment]
Looks like this was completed.

**Comment by jonalmeida** [comment]
It isn't, but it's being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1607092

**Comment by vesta0** [comment]
Ah I didn't realize it was a different text than desktop. Ok cool :)
