### ISSUE TITLE
add more add on support

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#13984]
### What is the user problem or growth opportunity you want to see solved?
The fork version of fenix iceweasel has too many add ons added... Can those add on be added to our fenix.. The best add on translate web pages... This works like chrome

### How do you know that this problem exists today? Why is this important?
We need more add on support 

### Who will benefit from it?
All users

![Screenshot_20200820-215835413](https://user-images.githubusercontent.com/58127841/90799064-5ad40080-e330-11ea-8256-a879ea9fba0c.jpg)
![Screenshot_20200820-215851736](https://user-images.githubusercontent.com/58127841/90799085-61627800-e330-11ea-95e4-b9a05881d302.jpg)

**Comment by cadeyrn** [comment]
Please use the search, there are already enough issues about expanding the add-on support, nothing changed between the last one and now.

**Comment by NotWoods** [comment]
We would like to expand our support to other add-ons but we are not keeping open requests for specific selections. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.

**Comment by sheikh-azharuddin** [comment]
Generic blog!
