### ISSUE TITLE
[Bug] On 'search engine settings' in awesomebar, the inverted arrow appears next to it

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#13996]
### Expected behavior
The arrow should be removed.

### Actual behavior
The arrow appears there.

### Device information

* Android device: Android 10
* Fenix version: 80.0.1-beta.2

**Comment by miDeb** [comment]
This is also covered by https://github.com/mozilla-mobile/android-components/issues/8175.
