### ISSUE TITLE
[webcontent] When logging in my OMV NAS the page always return to the login page

### ISSUE THREAD

**Issue by steakhutzeee** [mozilla-mobile/fenix#13991]
### Device information: XIaomi Mi 9T

Hi, lately with Firefox Beta on Android i experienced a strange behaviour when logging in into my OMV NAS webui. Basically after entering user and password, the same login page is loaded again. This happens forever and i can't login.

FIxed the issue using Firefox not beta, but now that it has been updated to version 70.0.5 i have the same issue also with it.

No issue with Chrome.

Hope the issue is clear. Thank you in advance!

**Comment by ale82to** [comment]
I have this issue too

**Comment by ekager** [comment]
Hi @steakhutzeee @ale82to are you both still seeing this issue?

**Comment by steakhutzeee** [comment]
> Hi @steakhutzeee @ale82to are you both still seeing this issue?

Hi, the issue seems gone.

**Comment by ekager** [comment]
Thank you for testing! Closing
