### ISSUE TITLE
FNX-5003 ⁃ Homeview UI a11y

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#140]
Parent: #99

**Comment by boek** [comment]
@shorlander Should we adjust the colors for the session intro text?

**Comment by pocmo** [comment]
@sblatz Just a nit: Can you expand the bottom panel the next time? I think for the touch target it should show the current size and the size it recommends. That would be interesting to see. :)

**Comment by sblatz** [comment]
@pocmo ah, didn't know that (first time using that tool). I'll do that in the future! 😄

**Comment by shorlander** [comment]
> @shorlander Should we adjust the colors for the session intro text?

Yes, can you please try #3c2382? It should increase the contrast.

**Comment by sblatz** [comment]
@shorlander this is with the new value:

<img width=300 src=https://user-images.githubusercontent.com/4400286/52501626-9f0c0f80-2b95-11e9-84bf-00af8fae54c9.png>
