### ISSUE TITLE
[Bug] Unable to fullscreen video contained in iframe

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#14003]
## Steps to reproduce
Go to any website that embeds videos in an iframe, like Al Jazeera, and try to view a video in fullscreen.

### Expected behavior
Video is played in fullscreen.

### Actual behavior
Nothing happens

### Device information

* Android device: Huawei Nova 6
* Fenix version: Nightly 200820 06:08 (Build #2015759027)
AC: 56.0.20200819190136, fb5d4191c
GV: 81.0a1-20200818092452
AS: 61.0.10

**Comment by snorp** [comment]
I can reproduce this in the GeckoView example app. Filed a bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1661270

**Comment by mobd** [comment]
I can confirm this is fixed in the latest nightly, so this issue can probably be closed. Thank you for working on this!

However I think the fix for this introduced a bug with the title of a page, I filed another issue at #14433.
