### ISSUE TITLE
In the new 'Download UI", optionally let the users delete just the file listing.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#14001]
### What is the user problem or growth opportunity you want to see solved?

Not at all the times I want to delete the actually downloaded file, sometimes I just want to get rid of the file listing so the downloaded files list in the Download UI remains clutter-free, distraction-free and allows me to focus and I can choose which files I see in it.

### How do you know that this problem exists today? Why is this important?

As I said it will allow to manage which files listing the user sees in the Download UI so it becomes flexible and customizable and allows the user to focus by not seeing a file that they downloaded randomly from the internet once or twice, so users can have only the files they want to have a quick access to in the Download UI

### Who will benefit from it?

Users who want a clutter-free, distraction-free and customizability over downloaded files listings in Download UI.

* Download managers like ADM, IDM, etc. allow it, this could be a really useful feature for those who want a control and customizability over their downloaded files listings in the Download UI. and It definitely allows the users to have a frustration-free quick access and view of their downloaded files in Download UI.

![Screenshot](https://user-images.githubusercontent.com/69946395/90844926-a7482c00-e382-11ea-8bb6-207326c5baf2.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5245)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812807

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
