### ISSUE TITLE
[Bug] Synced tabs in tabs tray can only be viewed if there's atleast 1 tab open

### ISSUE THREAD

**Issue by karan-kamat** [mozilla-mobile/fenix#14007]
## Steps to reproduce 

Open latest nightly with "Show Synced Tabs in the tabs tray" secret setting turned on
Open tab tray if there's any tabs opened you'll see synced tabs below
Close all tabs
Open tab tray again

### Expected behavior

Can still see synced tabs

### Actual behavior

No synced tabs visible

### Device information

* Android device: Xiaomi Redmi Note 5 Pro with Android 9 and MIUI 11.0.3
* Fenix version: Nightly 200821 06:01(Build #2015759219)

![nightly-tabs](https://user-images.githubusercontent.com/59926956/90872956-0164e380-e3bb-11ea-99de-e33fe86611d2.gif)

###Why is it necessary

If someone wants to open a synced tab from another device they'll first have to open a new tab

###Alternative Suggestion

Make synced tabs seperate entity like Normal tabs and Private tabs instead of being below Normal tabs

**Comment by liuche** [comment]
Can't repro this old bug on 10/21 nightly. Synced tabs has had many improvements since it was behind a secret setting.

**Comment by karan-kamat** [comment]
It's still reproducible for me with 10/21 nightly.
![nightly-tabs-2](https://user-images.githubusercontent.com/59926956/96875572-fa2e8480-1494-11eb-87c1-14d1c3b988d1.gif)
