### ISSUE TITLE
FNX-5004 ⁃ [Bug] Able so see the QuickActionSheet in light background color site using custom tabs

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1400]
## Steps to reproduce
Open a light background color site with custom tabs (Like [UPS tacking page](https://www.ups.com/track?))

### Expected behavior
The `QuickActionSheet` shouldn't be visible behind the toolbar.

### Actual behavior
The `QuickActionSheet` is be visible behind the toolbar.

![image](https://user-images.githubusercontent.com/773158/55597503-f05ef800-571b-11e9-8c6a-21e8514ef6c3.png)

**Comment by sblatz** [comment]
@Amejia481 this doesn't exist anymore right? The custom tabs bar is now on the top and also doesn't have a quick action bar.
