### ISSUE TITLE
PWA Shortcuts

### ISSUE THREAD

**Issue by hexandcube** [mozilla-mobile/fenix#14013]
Would be nice if Firefox supported [PWA Shortcuts](https://developer.mozilla.org/en-US/docs/Web/Manifest/shortcuts) like Chrome does.

Example:
![image](https://user-images.githubusercontent.com/41151156/90886118-17ba7180-e3b2-11ea-8b83-657896bdba44.png)

```JSON
 "shortcuts": [{
        "name": "Notebook",
        "short_name": "Notebook",
        "description": "Latest post from Hexandcube's notebook",
        "url": "/notebook",
        "icons": [{
            "src": "/assets/img/icons/android-192x192.png",
            "sizes": "192x192"
        }]
    }]
```

Depends on #10038 /  mozilla-mobile/android-components#1832

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5259)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807426

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
