### ISSUE TITLE
[Bug] URL-bar can disappear at inopportune times.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#14012]
This happened to me after visiting my first website (I think it was Firefox' release notes).
A good idea would be to make sure that for this kind of notification, the bar gets forced into visibility.
![fire3](https://user-images.githubusercontent.com/59611881/90877997-7e309700-e394-11ea-8150-5d1813ec22cf.jpeg)

**Comment by mcomella** [comment]
Dupe #15402.
