### ISSUE TITLE
Add "Hold link - > add to collection" option

### ISSUE THREAD

**Issue by GiganticThirstyHerald** [mozilla-mobile/fenix#14016]
It'd be some sort of multipurpose "read later" feature using collections system

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5262)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809299

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
