### ISSUE TITLE
[UX] In the "new search" experience when the address bar is at the bottom, make the search suggestions display from "bottom to top" 

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#14017]
Suggested here: https://github.com/mozilla-mobile/fenix/issues/13052#issuecomment-677513726

I think in the new search experience, search suggestions should go from bottom to top because when I'm typing into the address bar looking down and if the search suggestions end up at the top of the display this will feel very disconnected as the user has to scan through from the top to bottom and the user will have to stop typing and look at the suggestions at the top of the screen and then come back again to continue typing in the address bar, this takes a lot of visual effort I think and it also doesn't match with user intuitions.

**When the address bar is at the top:**

The user is looking at the top and scanning through suggestions by looking downwards in a **top to bottom** fashion and if the first search suggestion matches then the user clicks on it to make a search.

**When the address bar is at the bottom:**

The user types something into the address bar and the user is looking at the bottom and scanning through the search suggestions in a direction of **bottom to top** fashion so the user types something and gets a suggestion and if the first suggestion matches up then the user click it and makes a search.

But if the search suggestion appear at the top then I think the user would get puzzled which is the search engine suggestion and which is the typed word. In my opinion the search suggestions should be just above the address bar as the user is looking at it in that moment, not at the top where the user isn't looking.

**Comment by hwinnemoe** [comment]
Now that the new search experience is the default solution I realise that I have to travel even more distance e.g. when I want to choose the first suggestion. Thus I'm very much in favour of this solution.

Can we copy this into a more visible issue? Ghost issues are not searchable by keywords by GH and can be only be found using direct links or manually searching for them when the label is known.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 81.1.0-beta.1 (Build #2015761489) GV 81.0 from 9/2 with Samsung Galaxy Tab S3 (Android 8).

**Comment by apbitner** [comment]
Pinging @violasong for consideration with the address bar work she's been investigating.

**Comment by violasong** [comment]
Forwarding the ping to @topotropic since she's been investigating overall app standards :)
