### ISSUE TITLE
[Bug] Crash on opening Downloads when  a download is ongoing

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14024]
## Steps to reproduce
Download a link
Immediately open downloads
### Expected behavior
Downloads opens
### Actual behavior
Crash
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly 
     

Nightly 200821 06:01 (Build #2015759219)
AC: 56.0.20200819190136, fb5d4191c
GV: 81.0a1-20200818092452
AS: 61.0.10

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200826`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200826-110338](https://user-images.githubusercontent.com/51314259/91278609-1e1f6380-e78d-11ea-840c-b64f9de166a6.gif)
