### ISSUE TITLE
Add "Websites visited recently" in the homepage

### ISSUE THREAD

**Issue by Sav22999** [mozilla-mobile/fenix#14028]
In the previous version of Firefox, in the Home screen there was the "Recent websites" (/Frequent), add this feature again.
On Mozilla Response many users ask for this again too.

**Comment by clientenq** [comment]
Adding top site manually is not a sufficient solution. The purpose of top sites was (and in my user opinion still should be) to provide the user with an easy mainly _automated_ overview of frequently visited sites.

The current implementation of top sites is practically not providing a list of top sites but a list of user preferred sites based in manual users choice and input instead. If the users wanted to add top sites manually they could use bookmarks as a reminder and reorder these at any given moment.

**Comment by Dunexus** [comment]
Of course but it was a first step. As I said, they are working on populating top sites with frequently open sites automatically, see #10342.

**Comment by liuche** [comment]
This is currently in-progress in #10342, closing as a dupe.

**Comment by cadeyrn** [comment]
#10342 is about frequently visited websites and the issue opener also mentioned frequently in parantheses, but the issue opener also mentioned recently visites websites and it's even the title of the issue. So I guess the issue opener is referring to the "Hightlights" section of Fennec that show recent visits and bookmarks. This is not covered by #10342.

**Comment by liuche** [comment]
Ah, thanks for catching that - I'll also link to "recently closed" in #2486, which is not exactly the same, but the idea is to cover most users' needs for recently history between "open tabs" and "recently closed".

There is possibly also UX work exploring "chronological tabs/history".
