### ISSUE TITLE
[Bug] Bing doesn't show suggestions

### ISSUE THREAD

**Issue by Sav22999** [mozilla-mobile/fenix#14029]
If the default search engine is Bing, when you write in the address bar, (and in Settings "show suggestions" is enabled) it doesn't show anything

# Device information
LG G6 (Europe)

* Android device: 9

**Comment by s-ankur** [comment]
I cannot reproduce on Asus Zenfone m1 (Latest Nightly).

**Comment by mcarare** [comment]
Cannot reproduce it either, on multiple devices.

**Comment by Sav22999** [comment]
I've deleted the data and reopened the app. Now it works

**Comment by mcarare** [comment]
Closing this as per reporter's comment https://github.com/mozilla-mobile/fenix/issues/14029#issuecomment-678986608.
