### ISSUE TITLE
[Bug] Downloads Disappear after update

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14021]
## Steps to reproduce
Download something
Update nightly

### Expected behavior
You can still see your downloads in downloads pane

### Actual behavior
Downloads are empty
### Device information

* Android device: Asus Zenfone
* Fenix version: I do not recall which version it was earlier but the current version is

Nightly 200821 06:01 (Build #2015759219)
AC: 56.0.20200819190136, fb5d4191c
GV: 81.0a1-20200818092452
AS: 61.0.10

**Comment by liuche** [comment]
Downloads currently is a nightly-only feature while it's in development, so I'll dupe this for the AC bug.
