### ISSUE TITLE
[Bug] about:support broken in recent Nightly

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#14039]
## Steps to reproduce

Go to about:support

### Expected behavior

Fields are filled in

### Actual behavior

Most fields are blank, e.g. "Name", "Version", "Build ID" and so on

### Device information

* Android device: Sony Xperia XZ1C
* Fenix version: Nightly 200820 06:08 from play store

**Comment by liuche** [comment]
Let's dupe it
