### ISSUE TITLE
Add "Exit" in the main menu, to close Firefox

### ISSUE THREAD

**Issue by Sav22999** [mozilla-mobile/fenix#14033]

**Comment by s-ankur** [comment]
Note that neither Chrome nor the stock Android browser on my phone has this feature. I agree that it would be redundant and not an effective use of screen real estate

**Comment by 3j9fkyahunqoxwqu** [comment]
@Sav22999 
First, this behavior is same as old firefox from very old versions.
It hadn't changed in years.

Also it is same in Chrome and the latest version of brave that i used several months ago.

Second, an exit button in app won't force close or stop its background processes.

Some browsers you mentioned will keep themselves in the background even when you tap on exit button.

And not any of them force stop themselves.

When you open the recent apps screen in your phone amd swipe the firefox away, it will get cleared from memory (AKA. Android will kill it)

Also if you want to force stop apps, no app would and can do that, even those that have exit button, you just need to install something like greenify or superfreezZ. 

In the last also you can set firefox to clear cookies or cache so the exit button will appear.

Best regards.

**Comment by Sav22999** [comment]
Ok, it's useless. You can close this issue.

Good work
