### ISSUE TITLE
[Bug] Twitter Retweet causes UI to glitch

### ISSUE THREAD

**Issue by Nirose** [mozilla-mobile/fenix#14051]
## Steps to reproduce

1. choose navigation bar at the bottom
2. go to twitter, scroll down a while so the navigation bar is automatically hidden
3. try to reretweet a tweet

### Expected behavior

The navigation bar should not pop up and become white. just show the actions, namely the 'retweet', 'retweet with comment' and 'cancel' button

### Actual bebehavior
1. the navigation bar section becomes white
2. unless you tap again, the cancel button is hidden and the actions are then misplaced, causing wrong action be tapped.
https://i.imgur.com/K4ikacd.jpg

### Device information

* Android device:  Oneplus 3T, Android 9.
* Fenix version: Nightly 200821

### Additional information

* Enhanced tracking:  standard
* Theme: Dark

**Comment by Nirose** [comment]
this seems to be fixed in latest nightlies

**Comment by ekager** [comment]
Thanks for the update!
