### ISSUE TITLE
[Bug] missing padding for "try again" button for failed downloads

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#14053]
### Steps to reproduce

0. change you language to German (or another language with a longer "try again" string, it's not reprodudible with English)
1. try to download something (it will always fail in the current build, so every file will work as an example)

### Expected behavior

padding on the left and the right of the button.

### Actual behavior

no padding.

![Screenshot_20200822-011637](https://user-images.githubusercontent.com/1100614/90952442-e8643d00-e463-11ea-8ac7-0b5d59ccaca3.jpg)

Similar to #7219.

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision 88a2273e4cb75e3d906bcaceedcd617a56658e18

**Comment by prabhat3108** [comment]
I am working on this.
