### ISSUE TITLE
[Bug] Retrying to download a failing download file causes "(1)" to be appeneded repeatedly to the end of the file

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14055]
## Steps to reproduce
Download something which fails to download
When the download failed dialog appears click try again
Repeat this process
### Expected behavior
Since the download never completed the file name should remain the same, OR file(1) then file(2) then file(3) and so forth
### Actual behavior
file(1) then file(1)(1) then file(1)(1)(1) etc
### Device information

* Android device:Asus Zenfone
* Fenix version: nightly

**Comment by liuche** [comment]
More concerned that we're accidentally persisting/tracking failed downloads somewhere that's causing this mis-naming, or that we're not showing the download state accurately (and the downloads are actually succeeding)? cc @Amejia481 for after the persistent downloads work, if you have any ideas what may be underlying causes.

**Comment by s-ankur** [comment]
I cant really reproduce this anymore
