### ISSUE TITLE
Remove background of "legacy" icons

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14054]
### What is the user problem or growth opportunity you want to see solved?
Just fits in better.

### How do you know that this problem exists today? Why is this important?
It's not a big problem but it doesn't really fit in.

### Who will benefit from it?
Users on Android 7 and below, and those on Android 8 and above with launchers that use legacy icons.

**Comment by buttercookie42** [comment]
The now discontinued `org.mozilla.fennec_aurora` package had the proper non-adaptive Nightly icon for example, whereas `org.mozilla.fenix` suffers from the described issue.

**Comment by ekager** [comment]
@NotWoods do you know anything about these legacy icons and if we have the right assets?

**Comment by NotWoods** [comment]
We can probably just resize the [assets from mozilla.design](https://mozilla.design/firefox/logos-usage/), but maybe @shorlander has appropriately sized and padded transparent icons for Android already?

**Comment by KrisNM** [comment]
Adding screenshots.

Proper older icon (Firefox 68.11.0): https://i.imgur.com/GyrXUCg.jpg

Current "Fenix" messed-up icon:
https://i.imgur.com/ZpWIP2S.jpg

Regards.

**Comment by Poopooracoocoo** [comment]
Looks like this also affects the release channel. I've kept my release install on fennec so I didn't know.

**Comment by KrisNM** [comment]
No one?

Please try to use Firefox on Android 5.1.1, so you can see what's we're talking about.

The icon size is currently ugly, very small and no transparency.

Icon is part of the branding, so this is not trivial matter.

**Comment by Poopooracoocoo** [comment]
Still an issue I think idk

**Comment by DragoCubed** [comment]
Still an issue on my device.
