### ISSUE TITLE
[Bug] opening a top sites link and pressing back now pops up the search instead of the home screen

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14058]
## Steps to reproduce
Open a site from top sites
Press back

### Expected behavior
You should be taken to the home screen, since that is where you started from. Also the tab you just opened should be closed but that is another bug covered elsewhere

### Actual behavior
The search bar is opened and the keyboard pops out
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by liuche** [comment]
I can't seem to repro this on the latest nightly, could it be device specific?

Open top site
hit back
see home screen (with top sites, collections, etc)

**Comment by s-ankur** [comment]
Ill will update and try to reproduce on latest nightly

**Comment by s-ankur** [comment]
cannot repro anymore
