### ISSUE TITLE
Access top sites immediately when clicking urlbar

### ISSUE THREAD

**Issue by mrBega** [mozilla-mobile/fenix#14057]
### What is the user problem or growth opportunity you want to see solved?
The top sites should be as easy as possible to get to. It used to be that you would see them as soon as you pressed the address bar. Now you have to do that and the open a new tab. Why? It's the sites you are most likely to want to visit. It's your TOP SITES. The should be easily accessible just like in the last build. Now I have to close a tab, open a new one and then press the top site of my choosing. That's two extra times I can slip up and press the wrong thing.

### How do you know that this problem exists today? Why is this important?
I experience it every time I use Firefox for Android on my phone. It's important cause it ruins the user experience the way it is now and it raises the risk of the user press g the wrong thing. 

### Who will benefit from it?
Every user that uses top sites functionality.

**Comment by yoasif** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/9118

**Comment by mrBega** [comment]
Correct. Closing.
