### ISSUE TITLE
[Bug] (regression) it's no longer possible to download anything

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#14052]
### Steps to reproduce

1. Try to download something: apk file, image file, whatever

### Expected behavior

It works.

### Actual behavior

The download fails. It's a regression from the last AC update to  56.0.20200821184.

logcat output when trying to download something:

2020-08-22 10:33:48.772 7182-7313/org.mozilla.fenix.debug E/AbstractFetchDownloadService: verifyDownload for https://www.google.com/images/branding/searchlogo/1x/googlelogo_tablet_tier1_hp_color_183x64dp.png FAILED

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision 88a2273e4cb75e3d906bcaceedcd617a56658e18

**Comment by leogama** [comment]
> Actually it looks like the download succeeds, fenix just reports it as failed. I can find the downloaded file in the file manager.

The file is in fact downloaded but, for images at least, it's not listed in my file manager under Downloads, Images, Recent files, etc. or even in the Gallery app. I had to navigate through the file system tree (Internal storage > Downloads) to find it.

**Comment by miDeb** [comment]
> The file is in fact downloaded but, for images at least, it's not listed in my file manager under Downloads, Images, Recent files, etc. or even in the Gallery app. I had to navigate through the file system tree (Internal storage > Downloads) to find it.

That's probably unrelated, see
https://github.com/mozilla-mobile/fenix/issues/8754.

**Comment by Amejia481** [comment]
Thanks for reporting the issue, indeed is a regression from https://github.com/mozilla-mobile/android-components/pull/8152, sorry about that. 

As @miDeb mentioned downloads are getting downloaded but the UI it's not showing the right status, this PR contains the fix https://github.com/mozilla-mobile/android-components/pull/8197, but as it has a larger scope will take longer to review. I'm putting a separate pr for addressing the issue.

**Comment by Amejia481** [comment]
This pr will address the issue https://github.com/mozilla-mobile/android-components/pull/8203

**Comment by liuche** [comment]
This should be in the Nightly build on 8/26, so putting a QA flag for that.

**Comment by softvision-miralobontiu** [comment]
Hi all,
I was able to download different types of files: .avi, .mp3, .zip, .jpg, on the latest Nightly build from 8/26 with Samsung Galaxy Tab S6 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
I'll remove the label and close this as verified.

<img src="https://user-images.githubusercontent.com/40694158/91297691-69467000-e7a7-11ea-88d6-65de5017fc43.jpg" width="300" height="550" />
