### ISSUE TITLE
[Bug] Videos automatically stopping while in a phone call - no way of resuming

### ISSUE THREAD

**Issue by ItsCubeTime** [mozilla-mobile/fenix#14059]
## Steps to reproduce
Get in a phone call, open up Firefox (Regular build from Google Play Store),  attempt playing any video
### Expected behavior
It is nice that videos auto pause when you get in a phone call, but it shouldn't stop you from resuming while well in the call
### Actual behavior
It will stop any videos as you attempt playing them while in a phone call and there are no settings to disable this feature making it seemingly impossible to play a video while in a call.
### Device information
Samsung A40

**Comment by ItsCubeTime** [comment]
I mean, its a pretty serious issue. The solution here is kinda to switch browser. Feel this should get some kind of attention

**Comment by ekager** [comment]
Is this still a problem? @ItsCubeTime
