### ISSUE TITLE
`preventDefault` doesn't work for "contextmenu" events on anchor elements

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla-mobile/fenix#14067]
## Steps to reproduce
1) visit page: https://codepen.io/icl7126/pen/gOrLNag
2) use long press on the link on the first line

### Expected behavior
Custom context menu should appear.
### Actual behavior
There is a browser context menu above the custom context menu.
### Device information
Not device specific.
* Fenix version: 80.0.1-beta.2 (Build #2015758613)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5323)

**Comment by Juraj-Masiar** [comment]
the bug is still present in the current Nightly

**Comment by Juraj-Masiar** [comment]
The bug is still here, please fix. Thanks!

**Comment by MelvinWM** [comment]
Another reproduction example of this same bug: https://jsfiddle.net/dho1ukrx/ .

**Comment by Juraj-Masiar** [comment]
Still broken in Nightly 101.0a1 (Build #2015874795).
Please fix :)

**Comment by Juraj-Masiar** [comment]
108 still affected.
See you in 6 months? :)
