### ISSUE TITLE
[Bug] Back button in root bookmarks folder in bookmarks page isn't disabled or hidden

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14062]
## Steps to reproduce
Open bookmarks page

### Expected behavior
Back button in root bookmarks folder would be disabled or hidden

### Actual behavior
There is a back button and tapping it does the same thing as the close button

### Device information

* Android device: ?
* Fenix version: 80.0.1-beta.2

![118177529_2695688114044558_6253511712208803843_n](https://user-images.githubusercontent.com/51363864/90954362-0444fe80-e4b7-11ea-8199-c6887993f568.png)

**Comment by Poopooracoocoo** [comment]
Waiting for feedback from Mozilla. Don't dare mark this as stale >.>

**Comment by mariansima** [comment]
This issue was reproduced on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29

**Comment by DragoCubed** [comment]
@mariansima can you still repro?
