### ISSUE TITLE
Add separators to link context menu

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14063]
### What is the user problem or growth opportunity you want to see solved?
Users get confused when they tap and hold (or right click) on a link or image

### How do you know that this problem exists today? Why is this important?
I got confused when I saw the context menu

### Who will benefit from it?
people who use the context menu
![118086795_342735443777465_7119312207036874577_n](https://user-images.githubusercontent.com/51363864/90954764-c0ec8f00-e4ba-11ea-8045-f8723a0a2116.png)

Here's the same context menu on Firefox for Windows:
![image](https://user-images.githubusercontent.com/51363864/90954784-fe511c80-e4ba-11ea-99a9-f7e11c673943.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5317)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809300

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
