### ISSUE TITLE
[webcontent] there is a gap between status bar and site's sticky content on the top (toolbar, video, etc)

### ISSUE THREAD

**Issue by bashor** [mozilla-mobile/fenix#14069]
## Site with issue and any steps to reproduce
For example you can observe it on twitter and youtube.
1. Open https://mobile.twitter.com
2. Scroll down and back
3. Take a look at the top of sticky bar.

### Expected behavior
No gap.

### Actual behavior
There is a gap.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No.

### Device information

* Android device: ?
* Fenix version: 80.0.1-beta.2

**Comment by liuche** [comment]
Please follow along in #10598!
