### ISSUE TITLE
[Bug] navigation bar on bottom isn't hidden while scrolling on mobile.twitter.com

### ISSUE THREAD

**Issue by bashor** [mozilla-mobile/fenix#14066]
## Steps to reproduce
1. Open https://mobile.twitter.com
2. Scroll feed

### Expected behavior
Navigation bar was hidden.

### Actual behavior
Navigation bar wasn't hidden.

### Device information

* Android device: ?
* Fenix version: 80.0.1-beta.2

**Comment by liuche** [comment]
I'm not able to repro this on nightly.
