### ISSUE TITLE
Rename "Delete history" button in history to "Delete all history" (unless you're adding some control over it)

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14060]
### What is the user problem or growth opportunity you want to see solved?
Users don't know what to expect when they click on that button. I expected something like Chrome's delete data prompt that gave you a fair bit of control.

### How do you know that this problem exists today? Why is this important?
see above

### Who will benefit from it?
users who use the history page and may want to clear some of their history

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5313)

**Comment by apbitner** [comment]
Pinging @betsymi for her input here

**Comment by sflorean** [comment]
This is still the case. However, after tapping on "Delete history" button, a pop-up is displayed informing the users that all the history will be deleted, with a Cancel and Delete options.

**Comment by Poopooracoocoo** [comment]
Still waiting on Mozilla to clear this up somehow.

**Comment by Poopooracoocoo** [comment]
I grew impatient so stopped using Firefox. Commenting anyway just in case.

**Comment by csadilek** [comment]
Closing as the delete button now triggers a prompt to control how much history to delete.
