### ISSUE TITLE
xvideos.com not loading video preview [adult content]

### ISSUE THREAD

**Issue by Arngue** [mozilla-mobile/fenix#14064]
## Site with issue and any steps to reproduce
`www.xvideos.com` main page, if you go in private browsing or not, and you go to the page, if you pass the finger through one video the preview won't load, it just shows black screen in video preview, but if you go in a video, related video previews will load, you should repare this script issue, before last update this works fine

### Expected behavior
Load the preview as allways worked

### Actual behavior
Preview not loading

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information
Xiaomi redmi note 8 pro

* Android device: 10
* Fenix version: ?

**Comment by ekager** [comment]
Hi @Arngue are you still seeing this issue?

**Comment by Arngue** [comment]
No, in next update, they solved it, now the problem is entering on full sceeen, the video allways dispoay bigger than the screen and hides video controls, but is nsot a big problem

**Comment by Dunexus** [comment]
@Arngue The issue of the videos being zoomed in is tracked by https://github.com/mozilla-mobile/fenix/issues/8252
