### ISSUE TITLE
FNX3-15537 ⁃ [Bug] two crash dialogs at the same time

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1407]
### Steps to reproduce
Let's Fenix crash. ;-)

### Expected behavior
Only one crash dialog.

### Actual behavior
Two crash dialogs.

![Screenshot](https://user-images.githubusercontent.com/1100614/55610396-1c619400-5783-11e9-8f72-0b039412279e.png)UNITO-UNDERSCORE!20190405-090207!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 3ad204712a7321ffc8b472cf261407fa16a5c8b3

**Comment by pocmo** [comment]
This is possible if the app is crashing multiple times in a row. I'm not sure if we can prevent it - since it is a system dialog. But then again I have never seen it happening with Fennec.

**Comment by pocmo** [comment]
Okay, I think I now know what's causing this.

**Comment by pocmo** [comment]
CC @liuche @ekager @boek @sblatz @colintheshots I need your input here to make a decision.

The second dialog on top ("App has stopped", "App keeps stopping") is shown by the Android system. I can prevent this dialog from showing up by not delegating uncaught exceptions to the system handler before we kill the crashed process (in `lib-crash`). I'm pretty sure this will cause (most) crashes to not show up in the Google Play console anymore. We can see the same behavior for "Firefox for Android" where only some random crashes make it to Google Play. So my question here is: How much do we depend on the crash statistics of Google Play? Could we live without them? We would have to rely on Sentry, Crash-Stats (we do not send exceptions here yet, but we could) and soon maybe Glean only.

**Comment by pocmo** [comment]
Looking at uploading crashes to Socorro first: https://github.com/mozilla-mobile/android-components/issues/3511

**Comment by sblatz** [comment]
@liuche can you make a call on this? :)

**Comment by liuche** [comment]
Right now, we have Sentry crashes (but these are a little hard to see as a crash percentage), and I believe crash-stats is only GeckoView crashes (and not Fenix Android).

We added [Glean crash count](https://datastudio.google.com/reporting/1wXLx7DrASI3JHlGK2A2vcfpXAJQySHPH/page/WEP5) now, but we're still working through getting it in a useful form (e.g. crash counts per hour).

So for right now, I think we still need Google Play crash count bc it gives us a crashes per usage percentage, which we don't get from Glean or Sentry.

**Comment by pocmo** [comment]
> and I believe crash-stats is only GeckoView crashes (and not Fenix Android).

We upload everything to crash-stats now.

**Comment by rocketsroger** [comment]
Nightly with A-C version `45.0.20200603130110` will not show Android crash dialog when Fenix crashes.  Please verify.  Thanks,

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200606 (Build #21610607) using a OnePlus 6T (Android 9) and Huawei MediaPad M3 (Android 7.0).
