### ISSUE TITLE
[Bug] Sometimes the background tab becomes blank and the address bar cannot be clicked

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#14074]
https://i.imgur.com/72lWtPX.mp4

80.0.1 (Build #2015759299)
AC: 54.0.3, c91a47caa
GV: 80.0-20200818235255
AS: 61.0.10

**Comment by ale82to** [comment]
I also have this issue!

**Comment by liuche** [comment]
Yes! We're fixing this but it is a tricky bug to nail down - for now, we've backed out the changeset on Firefox 80 so it doesn't hit release users. thanks for filing!

**Comment by lindongbin** [comment]
> Yes! We're fixing this but it is a tricky bug to nail down - for now, we've backed out the changeset on Firefox 80 so it doesn't hit release users. thanks for filing!

now there have another bug, sometimes open Firefox, and then open the first tab, the page is blank, switching to another app will not be restored, only to create a new tab and then return to the first tab the blank page will be restored

80.1.1 (Build #2015760555)
AC: 54.0.5, 02934e437
GV: 80.0.1-20200827204751
AS: 61.0.10

**Comment by lindongbin** [comment]
https://i.imgur.com/jJiXULe.mp4

**Comment by liuche** [comment]
hey @csadilek it looks like @lindongbin is seeing this on the 80.1.1 build, which should have had the refactor backed out - is this just the less-common-case of the same bug?

**Comment by csadilek** [comment]
@liuche yes, exactly. 

We need fixes for https://bugzilla.mozilla.org/show_bug.cgi?id=1660546 and https://bugzilla.mozilla.org/show_bug.cgi?id=1662400 which are in progress.
