### ISSUE TITLE
Unable to disable cookies from Enhanced Protection. Can log in into sites with cookies turned off.[Bug]

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14077]
## Steps to reproduce
Ther's an option to turn off cookies from custom settings under Enhanced tracking protection. Chosing to disable all cookies still leaves me with cookies turned on, and can log in into sites with cookies disabled on Firefox version 79

Expected behavior
All cookies were supposed to be rejected.

Actual behavior
All cookies are accepted instead.

Device information:
Android 5.1 running Firefox 79.0.5

**Comment by eliserichards** [comment]
@Amejia481 is this fixed in the latest nightly?

**Comment by Amejia481** [comment]
No, it looks like the UI is not showing the correct selection: 
If you go to **Settings** -> **Enhanced Tracking Protection** -> **Custom** -> **Cookies** 

The selected option for Cookies is **"All cookies (will cause websites to break)"** when it should be -> **"Cross-site and social media trackers"**.

For the setting to be applied we need to select any other item and select back **"All cookies (will cause websites to break)"** this should be fixed.

**Comment by samiuljoy** [comment]
This issue seems to be fixed. Thanks ^-^
