### ISSUE TITLE
Implementing/modifying a few extensions as a built in feature.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#14078]
### What is the user problem or growth opportunity you want to see solved?
Css exfil protection from cross site scripting attack and addding rel=noopener by default. Also, it would be nice if dark mode(for web contents) was integrated as a system built in feature along with a check box included to toggle it on/off for web contents.
### How do you know that this problem exists today? Why is this important?
Css exfil protection was a add-on I used on Firefox 68.11.0 along with "Dont touch my tabs" which adds a rel=noopener request on each new tab. Could be a good measure if implemented from a security view point. Also, if dark mode for web contents was a built in feature like Chrome, it could be a good thing, because Dark reader delays page load time. And not to mention a bit of bright flash on every page load(new tabs).
### Who will benefit from it?
All Firefox users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5342)

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
