### ISSUE TITLE
Disable remote font download and Javascript.

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14079]
### What is the user problem or growth opportunity you want to see solved?
Disabling remote font download is a good practice from a security view point and also disabling javascript. These features are available on the Firefox Focus and also were available on Firefox 68.*.* 
This features would be helpful if included in the settings menu.
### Who will benefit from it?
All Firefox Users

**Comment by Dunexus** [comment]
They haven't really been removed. Fenix is an entire rewrite of the browser around geckoview and some feature haven't been implemented *yet*.
Don't hesitate to ask for features if some are missing and not already tracked by an issue, the team is working hard to improve Fenix.

**Comment by tomchiverton** [comment]
Not downloading fonts is (was!) a good bandwidth saver.

Face it, pushing a non feature complete partial rewrite as a live stable update is,sadly,  a rod for your own back.

Get used to feedback like "put back the features you shouldn't have released withou"

**Comment by samiuljoy** [comment]
> They haven't really been removed. Fenix is an entire rewrite of the browser around geckoview and some feature haven't been implemented _yet_.
> Don't hesitate to ask for features if some are missing and not already tracked by an issue, the team is working hard to improve Fenix.

Thank you (:

**Comment by ekager** [comment]
Going to close for #11460  . Thanks!
