### ISSUE TITLE
[Feature Request]Start downloading and rendering webpages as soon as user long presses link instead of pressing open in new tab and show it when the button is pressed.

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#14088]
### What is the user problem or growth opportunity you want to see solved?
This will speed up web browsing and make browsing smoother.

### How do you know that this problem exists today? Why is this important?
This will reduce webpage load time.

### Who will benefit from it?
Everyone. (Except mobile data user for whom this may be off by default)

**Comment by TrianguloY** [comment]
This could be a security issue.

Personally when I don't trust a page, if I need to open a link I long tap it, check if the link seems safe (the popup shows the full link) and then decide whether to follow it or not (on desktop you can simply hover the mouse above it, but not on mobile).

By loading the link in the background the browser is doing something without the user permission. What if the link downloads a file? What if it shows a popup/notification? What if it is a log out link?

Also, the menu shows 6 options. Three of them will benefit from this (open, open private and download) but the other three won't (copy, share and external). The one-two seconds you can gain (when a new tab usually takes more time) doesn't seem useful enough for the cons, on my opinion.

**Comment by Oymate** [comment]
@TrianguloY Understood.
