### ISSUE TITLE
[Bug] Downloading files always faiks

### ISSUE THREAD

**Issue by adamski234** [mozilla-mobile/fenix#14082]
## Steps to reproduce
Go to any website allowing you to download files. Download a file.
### Expected behavior
File downloads
### Actual behavior
Download either fails or the download progress bar is shown in the notification list with no progress shown. The information about the file's size is also missing
### Device information

* Android device: Nokia 3.1 Plus, Android 10
* Fenix version: Nightly 200822 06:01

**Comment by mcarare** [comment]
Closing as duplicate. @adamski234 thank you for your report!
