### ISSUE TITLE
Add an option for select a preferred language for websites

### ISSUE THREAD

**Issue by JoGarWeb** [mozilla-mobile/fenix#14086]
### What is the user problem or growth opportunity you want to see solved?
The current problem is that there is no option to select a preferred language when displaying a website.

### How do you know that this problem exists today? Why is this important?
I recently had a problem with DuckDuckGo, the only way to fix my problem was to modify an option found on PC but not Android. This option on PC is "Choose your preferred language for displaying pages" which modifies the "intl.accept_languages" parameters in about:config
For some reason DuckDuckGo doesn't respect my settings from their site settings when I search directly from "search bar", that was the only solution I found.

### DuckDuckGo Search with default settings

![image](https://user-images.githubusercontent.com/7904563/90968403-7dd9ee00-e4b1-11ea-8415-5c9b5d9684be.png)

![image](https://user-images.githubusercontent.com/7904563/90968401-6ef33b80-e4b1-11ea-9462-c83617288c47.png)

### DuckDuckGo Search with modified settings
![image](https://user-images.githubusercontent.com/7904563/90968337-c47b1880-e4b0-11ea-96e3-f02e683fcbe0.png)

![image](https://user-images.githubusercontent.com/7904563/90968409-92b68180-e4b1-11ea-8d7e-a30e832cf8c1.png)

**Comment by mcarare** [comment]
Closing as duplicate. @JoGarWeb thank you for your suggestion!
