### ISSUE TITLE
Firefox 79.0.5 struggles with reddit videos.

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14080]
## Steps to reproduce
Firefox seems to struggle on reddit.com. Especially when it includes video autoplays. It also struggles to take scroll inputs properly, delays by ~2 sec on each scroll input when a video is playing. Also sometimes crashes.

### Expected behavior
Smooth video playback and scrolling.
### Actual behavior
App freeze
### Device information
Android 9 with 2GB RAM

**Comment by mcomella** [comment]
Tracking upstream in Gecko at BZ-1661594.
