### ISSUE TITLE
FNX-5007 ⁃ [Bug] Site info panel on tablets is full screen-width

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1409]
## Steps to reproduce
1. Open a website.
1. Tap the padlock in the toolbar.
    1. Expected behavior
According to #1257, the site panel should be displayed just in the left corner of the screen, with rounded corners.
    1. Actual behavior
The panel covers the whole screen width.
    1. Device information

* Android device: Galaxy Tab (Android 8)
* Fenix version: 4/5

**Comment by Amejia481** [comment]
Thanks @sv-ohorvath this will be covered in https://github.com/mozilla-mobile/fenix/issues/1319

**Comment by sv-ohorvath** [comment]
> Thanks @sv-ohorvath this will be covered in #1319

Yup, sorry, I just came across that one.
