### ISSUE TITLE
Add link directly to GitHub from app to report bugs

### ISSUE THREAD

**Issue by github-man** [mozilla-mobile/fenix#14092]
Hello Firefox Dev Team,

Please add a feedback button to the app so users can give feedback like this without having to sign up to the community forum then github.

Thank you

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5365)

**Comment by csadilek** [comment]
Duping to the more generic https://github.com/mozilla-mobile/fenix/issues/15108. We're in the process of migrating to Bugzilla.
