### ISSUE TITLE
Copy version information from the About Firefox view when the user long presses

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14098]
### What is the user problem or growth opportunity you want to see solved?
Provide a consistent format for users to copy their Firefox information for issue reporting. Long press on the version information should copy the text in the version area. It could be useful to add some basic information about the phone such as the device model number and Android version. Long pressing in the link area should not copy the information. 

### Who will benefit from it?
a minor convenience for all bug reporters.
Implementing should be fairly straightforward, maybe assign for hacktoberfest/ good first issue?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5378)

**Comment by Dunexus** [comment]
You can already long press to select and then copy-paste the text inside about firefox.

**Comment by s-ankur** [comment]
I know, I'm just saying it would be nice to have a single button to click instead of selecting and then dragging and then clicking copy. It's very minor but would be nice to have

**Comment by TrianguloY** [comment]
On other apps/systems the long tap on the version number is what triggers directly the copy to the clipboard (with a toast to notify it). You can't select what to copy, but this is even a better feature because the devs can tweak what people need to paste on their reports.

This will also avoid adding a new button to the ui.

**Comment by mrandreastoth** [comment]
> 
> 
> On other apps/systems the long tap on the version number is what triggers directly the copy to the clipboard (with a toast to notify it). You can't select what to copy, but this is even a better feature because the devs can tweak what people need to paste on their reports.
> 
> This will also avoid adding a new button to the ui.

Good user interface design is clear in functionality, and hiding functionality behind an action such as a long-tab, etc., is not clear design.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807120

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
