### ISSUE TITLE
A Clone Tab Option (On long press tab counter)

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14096]
### What is the user problem or growth opportunity you want to see solved?
Some times I need to open the current page in two different tabs. On desktop Firefox there are already many ways to duplicate an existing tab. See https://support.mozilla.org/bm/questions/762043

### My Proposal
When you long press on the tab counter, a context menu opens with three options. My proposal is that you can have four options, including the Clone/Duplicate tab option in this order:

Close tab
**Clone tab**
New private tab
New tab

Ideally this option will duplicate the entire tab history and current tab state, much like collections do right now. But I would be happy even if it just opens a new tab with the current URL. In both cases this should open a tab in the background, so that you can continue browsing on the current page (or you can replicate the desktop behavior and navigate to the newly opened tab). You can also call this "Duplicate Tab", again for parity with desktop.

### Who will benefit from it?
Users of sites like wikipedia, stackoverflow which can require a "branching" flow that the linear tab history cannot easily provide. and especially desktop users who already love and use this feature. 

Related  #9956, but this issue highlights a different solution for the underlying feature request than that one

**Comment by Poopooracoocoo** [comment]
this should've been a comment on that other issue.

**Comment by s-ankur** [comment]
Closing for #9956
