### ISSUE TITLE
FNX-5008 ⁃ Create Search UI

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#141]
Parent: #101

**Comment by sblatz** [comment]
![image](https://user-images.githubusercontent.com/4400286/51050937-62ea8c80-15a0-11e9-887c-15bb042638b5.png)

**Comment by bbinto** [comment]
testing tool / closing

**Comment by bbinto** [comment]
will re-open soon again, just to try out the estimation tool and the progress report
