### ISSUE TITLE
[webcontent] contentEditable element scroll to top when cursor position changes by click

### ISSUE THREAD

**Issue by ujjwalmishra09** [mozilla-mobile/fenix#14107]
## Steps to reproduce
1. Add `contentEditable=true` attribute on a `div` using dev tools
2. Write something long so that element height should be more than device height.
3. Change cursor position using click in bottom of the content.

You can use following gist to add html and content using dev tools.

https://gist.github.com/ujjwalmishra09/58c046ad288babfcc7b016e619b53881

### Expected behavior
Element should not scroll on top.

### Actual behavior
Element scrolls on top when cursor position changes by click

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information

* Android device: Lenevo K6 Power, Realme
* Fenix version: 68.11.0

**Comment by makotokato** [comment]
Although scrolling to top may not be bug, but when showing software keyboard, we should scroll to visible position of caret.  I file as https://bugzilla.mozilla.org/show_bug.cgi?id=1660932.

**Comment by ekager** [comment]
Should be fixed in Nightly (or very soon) as the patch landed 10 days ago
