### ISSUE TITLE
[webcontent] CSS content incorrectly loaded for Technology Review on Nightly

### ISSUE THREAD

**Issue by TheAntimist** [mozilla-mobile/fenix#14104]
## Site with issue and any steps to reproduce
https://www.technologyreview.com/2020/08/22/1007539/gpt3-openai-language-generator-artificial-intelligence-ai-opinion/

### Expected behavior
CSS should not be completely bold for the full text, as checked on Chrome Android

### Actual behavior
Full page comes up as bold on mobile, even though it works fine on Firefox desktop.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No

### Device information

* Android device: Google Pixel 3a - Android 10
* Fenix version: Nightly 200822 06:01
Also tested on Nightly 200823 06:02

**Comment by hwinnemoe** [comment]
This is reproducible on desktop Nightly as well, 81.0a1 (2020-08-24), and also not reproducible on desktop Release 79.0.

**Comment by TheAntimist** [comment]
Closing this ticket, as it seems to already be tracked. Thanks @hwinnemoe
