### ISSUE TITLE
re introduce "about:config"

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#14100]
### What is the user problem or growth opportunity you want to see solved?
Previous stable versions provided the about:config functionality
This functionality was used by advanced users and even normal users for many years to make custom configurations. This since the user interface was (and now even more is) missing many many user configurable options compared to other stable Firefox browser versions. These options are refered to in Mozilla documentation and years of documentation all over the web. The about:config configuration options were created to give users control over their needs and wishes while mozilla firefox developers provide default configurations. The wish and needs by users to be in control in their stable browser have not vanished by the decision of the developers to remove all these related options from the user. For this all this functionality should not have been removed in the first place and certainly not without providing any additional options via the gui or addons / extensions.

### How do you know that this problem exists today? Why is this important?
1) a browser is not only used by noob users. The Firefox user base exists of many experienced, advanced and power users not in need for any _user friendly_ gui with minimalistic configurable options to make life _easy_ and _clear_
2) the gui lacks many many configurable options. It even looks like developers choose to remove as much options as possible from user interaction thus not giving more but less control to users.
3) thousands and thousands of addons / extentions have delibaratly been made incompatible while these gave users more control over (missing) configurable options and features.

### Who will benefit from it?
all users who wish to be in control of their browser other then relying on a minimalistic set of config options in the gui. users did use this functionality and are still in need for such control
Mozilla firefox will benefit since the team is not able to provide many user configurable options via the gui and the team is not able to provide much needed addon / extention availability to users in a timely manner.

Invalid reasons to not provide this functionality from a users perspective:
1) a new browser is not a valid reason to withhold this functionality. Users depend on this functionality, the browser is created for the users
2) lack of time/ wanting to push a new browsers version is not a valid reason. The team could choose to only introduce a stable version at a later moment since there was and still is no solution via the gui nor via addons / extension.
3) many options do not work is no reason to remove all functionality. Then disable those options instead.
4) users can break the browser by using the options. See 3) + That is where the warnings are for: users can choose to break the browser. Apperantly the options that can break the browser should be clear and thus can be disabled by default.
5) we expect support will have more workt to do when users break the browser: then be clear support is not for users who ignore warnings and configure the browser via optional settings.

With respect to users all this functionality should not have been removed. Treating users like noobs that can do with a minimalistic (micro) interface of configurable options is not professional and is lacking respect to all users relying and supporting a highly configurable browser. Imho this new version is a shame while removing so much options and control from users of the stable verion.

**Comment by chr15m** [comment]
I am also having this problem where it's impossible to bring up `about:config`. The reason is the "Accept the Risk and Continue" page is missing from the build or can't be accessed due to a protocol security issue.

This is the page the user sees:
![image](https://user-images.githubusercontent.com/67130/91005367-4e3df980-e609-11ea-8195-2237f3682534.png)

The URL it's trying to visit is "badCertAcceptTemporary=Accept+the+Risk+and+Continue".

My sync is currently broken because of this.

**Comment by omicron-b** [comment]
My 2 cents: AFAIK it is impossible to download mp3 file to listen with your own audio player unless you change 'media.play-stand-alone' to 'false'

So, pretty valid use case for a common user.

**Comment by cadeyrn** [comment]
Duplicate of #7865.

**Comment by metal450** [comment]
Why was this closed?  It hasn't been fixed.  I just updated Firefox on Android, to find that it's no longer possible to access 99% of Firefox's configuration options (i.e. including identity.sync.tokenserver.uri, which means that sync is now completely broken - I can no longer sync my phone to any of my other clients, via my sync server).

The other topic mentioned is marked as 'off topic' and 'closed,' making it not possible to discuss.

**Comment by cadeyrn** [comment]
It was closed because it's a duplicate, see the previous comment.

You don't need about:config to change the sync server. Go to the Settings > About Firefox, tap the logo five times, then there are the sync config fields visible in the settings.

**Comment by metal450** [comment]
Even with that, syncing no longer works. Per https://github.com/mozilla-services/syncserver/issues/224, it looks like you have to set identity.sync.useOAuthForSyncToken in newer versions of Firefox. Confirmed here: https://github.com/mozilla-services/syncserver/issues/218 . However, again since there's no longer about:config, there's no way to even try setting options such as these...

> It was closed because it's a duplicate, see the previous comment.

Makes sense - but that one is locked to contributors, making it impossible to discuss.  Thus there's only a "closed duplicate," or "the open issue, which people can't respond to."

**Comment by derMart** [comment]
@liuche #7865 is locked as OT, so there is no valid duplicate of this issue where discussion is possible. Please reopen this issue! about:config is a very important part of firefox which of course should be enabled in the mobile version

**Comment by Kansai53** [comment]
I've been stuck unable to update the app since they broke it by removing this option.  While I hate using an out-of-date web browser, I see no alternative unless or until they rethink this very obvious regression.
