### ISSUE TITLE
Show Synced Tabs in a separate tab on the tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#14117]
### What is the user problem or growth opportunity you want to see solved?
Scrolling through open tabs to reach your Synced Tabs can cause scrolling fatigue. It can be bothersome to also find the tab you are looking for in a rather large list.

### How do you know that this problem exists today? Why is this important?
The Synced Tabs list is at the bottom of the normal tabs in the tabs tray.

### Who will benefit from it?
- Firefox Sync users.

### Unsolved problems
 - (UX) Do we show a tab icon when the user is not signed into Sync?
   - For now, I'm going to stick with showing it always since we have existing UX on what the screen will look like.

### Dependant issues:
 - [x] Add ability to have non-browser tabs in the tabs tray #14969 

### UX designs and discussions
 - See https://github.com/mozilla-mobile/fenix/issues/12287#issuecomment-675285951 for the user feedback and suggestions.
 - UX design spec: [Figma (link)](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=101%3A3907)

**Comment by topotropic** [comment]
>     * (UX) Do we show a tab icon when the user is not signed into Sync?

@vesta0 that's your call, we could always show it to help people discover the feature easier and monitor usage data to inform future decissions; suggested design: https://share.goabstract.com/c6bd0c2f-8384-44f3-ba59-4946d8cea469?collectionLayerId=7f7dbd7e-f8ba-4a03-aecd-aeb989476bd0&mode=design

**Comment by Anutrix** [comment]
Isn't this fixed by https://github.com/mozilla-mobile/fenix/pull/13893?

**Comment by bifleming** [comment]
@jonalmeida @ekager @amedyne is this story still blocked by the refactor? (or am I thinking of a different one...)  Is this one we could pick up now?

**Comment by brampitoyo** [comment]
@jonalmeida I’ve moved our Synced Tabs design spec from Abstract to Figma. Along the way, I’ve put them side by side with iOS and iPadOS Synced Tabs mockups.

This way, you’ll able to see how our design is aligned across the board.

See comment 0 for Figma link update, or see https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=101%3A3907

**Comment by mcarare** [comment]
We should wait for https://github.com/mozilla-mobile/fenix/issues/17821 work to be done and merged before working on this.

**Comment by jonalmeida** [comment]
> We should wait for #17821 work to be done and merged before working on this.

There are a couple of things we want to do including that ticket. I've put them on [this board](https://github.com/mozilla-mobile/fenix/projects/38#card-54239984) to make it easier to track.

**Comment by lobontiumira** [comment]
Verified on the 4/20 Nightly build with Google Pixel (Android 10), Samsung Galaxy Note 8 (Android 9), Xiaomi Mi 8 Lite (Android 9), OnePlus 5T (Android 10), and Samsung Galaxy Tab A6 (Android 5.1.1) that the synced tabs are displayed in a separate tab on the tabs tray.

![synced tabs tray](https://user-images.githubusercontent.com/40694158/115392426-385cf480-a1e9-11eb-96e2-c8c85ec25fb5.png)
