### ISSUE TITLE
FNX-5010 ⁃ [Bug] Site info: Blocked permissions should have appropriate icons

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1411]
## Steps to reproduce
1. Open a website.
1. Tap the padlock icon from the url bar.
1. Verify the permissions blocked by user/ blocked by android.
    1. Expected behavior
Blocked permissions have a crossed-over icon.
    1. Actual behavior
Same icon as for allowed permissions.
    1. Device information

* Android device: Galaxy Tab 3 (Android 8), Nexus 5 (Android 6)
* Fenix version: 4/5

**Comment by bsurd** [comment]
Verified with the latest build (5/13). Denied permissions now appear with a cross-over icon and grayed out making it easier to distinguish between allowed and blocked ones.
