### ISSUE TITLE
[Bug][RTL] "Desktop site" icon on the main menu is on the wrong side and overlapping the toggle

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-mobile/fenix#14112]
## Steps to reproduce
1. Set Fenix to any RTL language e.g. Hebrew, Arabic
2. Open any website
3. Click the main menu icon
4. Observe the "Desktop site" item from the list

### Expected behavior
Icon should be on the right.

### Actual behavior
Is on the left.

### Device information

* Android device: Samsung Galaxy S10e
* Fenix version: Latest Nightly

![תמונה](https://user-images.githubusercontent.com/18016656/91070517-806a4e00-e63f-11ea-94b8-da607d789e45.png)

**Comment by NotWoods** [comment]
Probably a regression from https://github.com/mozilla-mobile/android-components/pull/8061

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200831`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_1rsz_screenshot_20200831-131703](https://user-images.githubusercontent.com/51314259/91710963-c4080f00-eb8d-11ea-9aa5-fbc77b281563.png)
