### ISSUE TITLE
Add a setting to toggle the display of frequently visited top sites

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#14119]
This issue is to add a toggle-able setting to toggle whether frequently visited top sites are displayed. The below mock is just an example - the exact wording and placement are still tbd by UX.

<img width="631" alt="Screen Shot 2020-08-24 at 5 24 35 PM" src="https://user-images.githubusercontent.com/1190888/91098025-b7843380-e62e-11ea-824c-fad12ae4bf50.png">

**Comment by vesta0** [comment]
I think it should be under the "customize" setting. The string looks good to me. 

cc @betsymi and @topotropic

**Comment by gabrielluong** [comment]
> I think it should be under the "customize" setting. The string looks good to me.
> 
> cc @betsymi and @topotropic

Not sure, how it should look under "customize" setting since those have been radio toggles instead of a switch toggle that you see in the screenshot.

**Comment by vesta0** [comment]
Good point. Let's see what @betsymi says. I recommend keeping it as simple as possible for now and re-evaluating later. 

Thanks for working so hard to get this in @gabrielluong :)

**Comment by topotropic** [comment]
Customize might be a better place for this option; cc @betsymi for feedback

![Settings - Customize@1x](https://user-images.githubusercontent.com/353960/91181135-db0bb480-e6e8-11ea-94c3-d04997b5ae51.png)

**Comment by betsymi** [comment]
+1 to customize placement. This will also give us flexibility to make adjustments in the future if we open up the opportunity for users to customize collections in some way. 

Do I understand correctly that toggling this feature off would remove all top sites from Home, including those you may have pinned yourself? If that is true, I recommend `Show top sites`. I removed "auto-generated" to cover both cases and to shorten the string. 

Question about behavior: If I were to toggle this off, then toggle it back on, do the top sites that were previously there re-appear?

**Comment by gabrielluong** [comment]
> +1 to customize placement. This will also give us flexibility to make adjustments in the future if we open up the opportunity for users to customize collections in some way.
> 
> Do I understand correctly that toggling this feature off would remove all top sites from Home, including those you may have pinned yourself? If that is true, I recommend `Show top sites`. I removed "auto-generated" to cover both cases and to shorten the string.
> 
> Question about behavior: If I were to toggle this off, then toggle it back on, do the top sites that were previously there re-appear?

`Show top sites` and `Auto-generated top sites` aren't quite correct. We still want to show user pinned top sites. We're adding a feature that is already available in Fennec and Desktop to show frequently visited sites in Top Sites on top of user pinned top sites. The toggle itself should disabling showing the frequently visited sites. These sites are based on your user visited site history. My initial recommendation is `Show Top Frequently Visited Sites`.

**Comment by betsymi** [comment]
Thanks for that additional context and clarification. I now understand toggling this off would hide frequently visited sites only, while allowing your manually add top sites to persist. 

For continuity's sake across platforms, I'm going to recommend language that we use on desktop (In desktop preferences we describe Top sites as _the sites you visit most_ as well as in [SUMO](https://support.mozilla.org/en-US/kb/customize-new-tab-page) ) `Show most visited sites`

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Nightly 9/2 and 81.1.0-beta.1. The option is present in Nightly but not in Beta even though patch notes for the Beta build should contain this fix.
### Devices used:
- Huawei MediaPad M3 (Android 7.0)
- OnePlus 6T (Android 9)

**Comment by gabrielluong** [comment]
@LaurentiuApahideanSV This setting is currently feature flagged for nightly and debug builds only for now. We haven't officially let the feature of showing frequently visited sites ride enabled ON by default. We will still need to address some of the known bugs before we want to show frequently visited sites. I think we can say this verified for the time being.

**Comment by liuche** [comment]
We'll remove the flag so it can get to beta testers sooner, so sending another build soon to be tested.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Beta 81.1.0-beta.2 (Build #2015761657).
### Devices used:
- Huawei MediaPad M3 (Android 7.0)
- OnePlus 6T (Android 9)
