### ISSUE TITLE
Support downloading media files

### ISSUE THREAD

**Issue by omicron-b** [mozilla-mobile/fenix#14128]
### What is the user problem or growth opportunity you want to see solved?

It is impossible to download a media file, e.g. mp3

### How do you know that this problem exists today? Why is this important?

Previously it was possible to download an mp3 file to listen with external audio player if you change `media.play-stand-alone` to `false` in `about:config`.
Currently it is not possible to download any media file in stable release.

### Who will benefit from it?

Users who wish to play audio / video in stand-alone player with extra features.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5424)

**Comment by freebrowser1** [comment]
This is another reason to support more extensions. There are extensions in the 'old' Firefox to download media.

**Comment by omicron-b** [comment]
@freebrowser1 
in my opinion, downloading any type of file, when it is explicitly linked to on a webpage, should be a core feature of a browser

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812806

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
