### ISSUE TITLE
Update tab thumbnail when swiping between tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#14122]
When switching tabs, we display the last available screenshot of the size for the gesture animation.

With the current setup, we only take a screenshot when entering the browser and on page loading complete.

We should also take a screenshot in the situation where you start a swipe gesture so that we can return to a tab in the most up-to-date scroll position.

**Comment by hwinnemoe** [comment]
Related #12859

**Comment by jonalmeida** [comment]
Thank you @hwinnemoe ! Closing as duplicate.
