### ISSUE TITLE
FNX-5011 ⁃ [Bug] No system permission prompt for location access

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1412]
## Steps to reproduce
1. Go to permission.site
1. Tap location.
    1. Expected behavior
A system dialog is displayed asking for location access.
    1. Actual behavior
No system prompt displayed. Just the app doorhanger.
*The system dialog is displayed for camera & microphone
    1. Device information

* Android device: Nexus 5 (Android 6), Huawei P20 lite (Android 8)
* Fenix version: 4/5

**Comment by vesta0** [comment]
@Amejia481 is this functionality completed?

**Comment by Amejia481** [comment]
This should be fixed with the new ac snapshot version.

**Comment by vesta0** [comment]
@sv-ohorvath please verify it's been fixed.

**Comment by sv-ohorvath** [comment]
This is fixed, the prompt does appear, but the order of access request is wrong. Logged: #1686
