### ISSUE TITLE
Format string issue on nightly

### ISSUE THREAD

**Issue by JamsNJellies** [mozilla-mobile/fenix#14129]
![Screenshot_20200824-215551](https://user-images.githubusercontent.com/39382425/91095911-0644c400-e655-11ea-8dd8-4b8f21086cb2.png)
%s is shown here. it shouldnt be.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200831`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20200831-124053](https://user-images.githubusercontent.com/51314259/91707448-7ccb4f80-eb88-11ea-8ea2-be3576259fd0.png)
