### ISSUE TITLE
QR code scanner displays black screen instead of camera image

### ISSUE THREAD

**Issue by jkronegg** [mozilla-mobile/fenix#14136]
Current behavior:
On my LG G2 (Android 5.0.1), with Firefox Beta for Android (version 80.0.0.beta-6 and 80.0.1-beta.2). When I press the QR code scanner button, a black screen with a white visor appears on the screen.
![Screenshot_2020-08-24-23-27-06](https://user-images.githubusercontent.com/2843894/91099419-8e31ca80-e663-11ea-8217-a2c2d0542e85.png)

Expected behavior:
When I press the QR code scanner button, the image from the front camera is displayed on screen with the white visor.

Workaround:
Scan the QR code with an online scanner, e.g. https://webqr.com

**Comment by mrj** [comment]
I get the same behaviour on my Android 5.0.1 Samsung Galaxy S4, though it does work on my Android 6.0.1 phone.

Firefox is listed in the Application Manager as having permission to take pictures and videos.

If scanning won't be supported on Android 5 and below, please hide the "Scan" button.
