### ISSUE TITLE
FNX-5012 ⁃ [Bug] [Android Q] Crashing when selecting one of the "Today" items

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1413]
## Steps to reproduce
* Select one of the session items under "Today"
* Instantly crashes

### Expected behavior
* No crash

### Actual behavior
* Repeated crashes when selecting the item. See attached logcat. Not the same as https://github.com/mozilla-mobile/fenix/issues/1035

### Device information
* Android device: Pixel running Android Q Beta 2
[crashreport.txt](https://github.com/mozilla-mobile/fenix/files/3047964/crashreport.txt)
* Fenix version: 1.0.1914 Build #10950244

**Comment by vesta0** [comment]
@boek please verify

**Comment by kbrosnan** [comment]
Works for me using a Pixel 2 XL on Android Q. @mozillamarcia reopen if this is still happening. The logcat seems truncated. It has the crash submission but not the actual app crash log.
