### ISSUE TITLE
[Bug] Failing to download an image from KMA

### ISSUE THREAD

**Issue by saschanaz** [mozilla-mobile/fenix#14143]
## Steps to reproduce

1. Access https://m.kma.go.kr/repositary/image/typ/img/RTKO63_202008251000]08_ko.png
2. Download the image

### Expected behavior

It should succeed.

### Actual behavior

It fails. 

### Device information

* Android device: Galaxy Note 8
* Fenix version: Nightly

**Comment by sv-ohorvath** [comment]
Thank you for the report. There is already an issue filed and should be fixed in tomorrow's Nightly: https://github.com/mozilla-mobile/fenix/issues/14052
