### ISSUE TITLE
[Bug] Undo is not working when deleting five bookmarks in a row

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#14147]
## Steps to reproduce
1. Launch Fenix and add multiple bookmarks;
2. Go to Bookmarks and swipe to delete 3 or 4 bookmarks in a row;
3. Tap the Undo button from the snackbar;
### Expected behavior
Tapping undo restores the last deleted bookmark.
### Actual behavior
Undo is not working when swiping to delete three or four bookmark in a row.
### Notes
This is reproducible almost all the time.
![20200825_113620](https://user-images.githubusercontent.com/48799384/91152225-64aa8a80-e6c7-11ea-8503-bd2ea8e44bbb.gif)

### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8);
* Fenix version: RC 80.1.0 GV 80 from 8/25; Beta 80.0.1-beta.2 GV 80 from 8/18; Nightly 200824 GV 81.0a1 from 8/24

**Comment by ebalazs-sv** [comment]
This is also reproducible on RC 80.1.3 Build #2015762833 GV 80.0.2 from 9/9 with Motorola Moto G6 (Android 8).

**Comment by yump** [comment]
I attempted to reproduce on latest Nightly and F-droid Fennec Stable, and although UI churn has made it somewhat harder to hit, this bug is still present.  

If two bookmarks are deleted as separate actions (i.e. *not* by multi-select), the undo button does not work.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 88.0.0-beta.1 with Samsung Galaxy Tab S3 (Android 8).

**Comment by VitalyVPinchuk** [comment]
Hi there,
I'm trying to reproduce the issue but can't get swipe working. Was the feature removed?

**Comment by zapy85** [comment]
Nightly 94.0a1 swipe is still there to close tabs, however as OP stated a long time ago the Undo button does only restore the very last tab that is being closed.

Wouldnt it be better if the Undo snackbar just keept opening the most recent tab until theres no tabs left to open or you stop click on it?

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 100.0a1 (2022-03-28) build.
After deleting 4 bookmarks in a row, tapping Undo restored the last deleted tab.
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.
