### ISSUE TITLE
[Bug]in the new Firefox-Beta-Version, the softkeys on my tablet cannot be used ( are not  displayed)

### ISSUE THREAD

**Issue by wi2000** [mozilla-mobile/fenix#14146]
### Device information Sony Xperia Z4 Tablet

* Android device: ?yes
* Fenix version: ?
If you need further information, just send me an e-mail.
Please let me know if and when this problem will be solved. With this bug Firefox is unusable.
Regards
Christa Schmidt

**Comment by wi2000** [comment]
If possible, correspond with me using e-mail.  Going to this page means I have to restart my tablet every time when I leave. Thank you.

**Comment by s-ankur** [comment]
You can directly reply to this email and we all will be able to see it on github (you'll get an email by default from GitHub notifications) . https://github.blog/2011-03-10-reply-to-comments-from-email/

**Comment by dongminor** [comment]
I have a same/ similar issue with my Sony Z3 phone. Thè buttons are there but are virtually invisible (white on white) maybe I can configure the bottom band back to black but to say the least it is very off-putting for the inexperienced.

**Comment by Nicero** [comment]
Same problem on Huawei Honor 7, Android 6.0, Emui 4.0.3. Using the white theme, buttons are not visible (but working) because are white on a white button bar.

**Comment by liuche** [comment]
Will link this to #4498
