### ISSUE TITLE
Add pinned badge for pinned sites

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#14145]
When #10342 lands, top sites will have both pinned, default and frecent sites. We should add a pinned icon for pinned sites as described in the design.

![84441360-edbf3300-ac3b-11ea-87fc-98f7fa40b7ec](https://user-images.githubusercontent.com/1190888/91078193-4766b500-e610-11ea-9594-561c4b6dcf8c.png)

**Comment by sheikh-azharuddin** [comment]
Is it possible to change the pinned icon from grey to purple or something... It is not that prominent...

**Comment by yoasif** [comment]
Built in pins don't have the pin (Pocket, Wikipedia, YouTube). 

The built in pins on desktop *do* show the pin decoration.

**Comment by gabrielluong** [comment]
> Built in pins don't have the pin (Pocket, Wikipedia, YouTube).
> 
> The built in pins on desktop _do_ show the pin decoration.

I never quite asked if we should've added a pinned badge for sites beyond the user added top sites. We will address this issue in https://github.com/mozilla-mobile/fenix/issues/15027. Thanks!

**Comment by Poopooracoocoo** [comment]
what about putting the badge next to the title like desktop?
![image](https://user-images.githubusercontent.com/51363864/93055517-6d7ef280-f6ae-11ea-9e01-4df7a691d946.png)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/16 with Google Pixel 3 (Android 11) and Samsung Note 10 (Android 10).

**Comment by Poopooracoocoo** [comment]
@gabrielluong any thoughts on what i said above?

**Comment by gabrielluong** [comment]
> @gabrielluong any thoughts on what i said above?

I think it's best to file a new issue with the request. I personally like the idea, but unfortunately, that doesn't provide much weight in terms of decision making.

**Comment by Poopooracoocoo** [comment]
oh ok. here you go: #15143
