### ISSUE TITLE
FNX-5013 ⁃ [Bug] Recommended/custom settings selection is reset - Nexus 5

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1414]
## Steps to reproduce
1. Go to Settings>Site permissions.
1. Select one of the 2 options: custom/recommended.
1. Exit to main settings menu. 
1. Go back to site permissions settings.
    1. Expected behavior
The selection is saved.
    1. Actual behavior
No radio button is selected.
    1. Device information

* Android device: just on Nexus 5 (Android 6) so far, doesn't happen on Huawei P20 lite (Android 8), or Xiaomi Redmi 5 (Android 5)
* Fenix version: 4/5

**Comment by sv-ohorvath** [comment]
Actually, the individual permission setting is not saved as well: e.g. in Custom settings, Camera: Block/Allow radio buttons.

**Comment by Amejia481** [comment]
Could you take a look again please? I think https://github.com/mozilla-mobile/fenix/pull/1405 should have fixed that.

**Comment by sv-ohorvath** [comment]
Still happening on the 4/10 local debug build, Nexus 5:
![20190410_182539](https://user-images.githubusercontent.com/4037709/55891993-330e4d80-5bbe-11e9-825b-f31108c77eb7.gif)

**Comment by Amejia481** [comment]
Thanks @sv-ohorvath I will take a look!

**Comment by sv-ohorvath** [comment]
Also reproducing on a HTC Desire 820 (Android 6.0.1)

**Comment by Amejia481** [comment]
@sv-ohorvath  could you re-test this issue, please? After https://github.com/mozilla-mobile/fenix/commit/c81cfab84e447878cc6de008b9c7fe77904c7893 it should be fixed.

**Comment by sv-ohorvath** [comment]
Yes, this is verified as fixed on the 5/2 build. New issue found: #2230.
note: please add the QANeeded label on issues that are ready for QA, this way anyone on the QA team can check the issue if I'm not around.

**Comment by Amejia481** [comment]
Thanks!
