### ISSUE TITLE
Need a confirmation prompt when load application jump link

### ISSUE THREAD

**Issue by xuyuehang** [mozilla-mobile/fenix#14149]
When the intent:// or someapp:// request occurs, if the corresponding application is installed in the phone, the browser will automatically jump.

But in many cases this request is not actively operated by the user, that is, it is not the user clicking the "open app" button, but is included in the page loading process. At the same time, some websites maliciously use this kind of jump.

We need a toast secondary confirmation pop-up window so that the user can control the opened application while avoiding meaningless jumping out.

Fennec can handle the jump or no jump by modify the network.protocol-handler.external-default in the about:config, but this will limit the user's freedom.

Firefox for iOS has a confirmation popup.

**Comment by TrianguloY** [comment]
This confirmation exists when using private mode, so it should be simple to extend it to normal mode too (although it will require a different dialog text)

**Comment by eliserichards** [comment]
Do we want to have a confirmation popup every time, in both normal browsing mode and private mode? @mozilla-mobile/ux

**Comment by betsymi** [comment]
Tried this out in the previous Firefox for Android to understand the implementation. This message is triggered in private tabs only by tapping the Twitter-served message at the bottom of the screen.

How could this jump be used maliciously? Is that why we feel it is necessary to serve this message in both private and normal tabs? Is there a private or security concern they should be aware of? 

Also worth noting that in Fenix, our default setting for open in apps is currently OFF. We are introducing a banner that will let users know about this setting and let them know they can switch to ON, if they so choose. That's issue #9506 

![PreviousFirefoxexample](https://user-images.githubusercontent.com/43555492/91889922-43601600-ec54-11ea-90f3-86f3aee7bd7c.png)
![PrivateTabsMessage](https://user-images.githubusercontent.com/43555492/91889926-4529d980-ec54-11ea-80e9-63aff7fee6cc.png)

**Comment by apbitner** [comment]
I don't see the need for a confirmation modal since we have the 'Open links in apps' setting as @betsymi mentioned. If a user doesn't want links to automatically open in native apps then they can turn that off.

I wanted to see the confirmation on iOS so I clicked on an Amazon link from a news article and it automatically opened the Amazon app without any confirmation dialog.

**Comment by Amejia481** [comment]
cc @rocketsroger

**Comment by rocketsroger** [comment]
Technically the change will be easy.  However, my understanding is that the reason private mode have a prompt dialog is to protect user's privacy.  Having private browsing page triggering a intent with a third party app will possibly expose user's private data.

Please note that there are multiple use cases here:
**1. With `Open links in apps` off:**
    a. Normal links (http, https, about, ftp etc...)will be open in the browser.
    b. Schemes that the browser does not support(intent://, market:// etc...), the browser will open it in a third party app if available.

**2. With `Open links in apps` on:**
    a. Normal links that have third party app support will be opened in the third party app.
    b. Normal links that have no third party support will be opened in the browser.
    c. Schemes that the browser does not support, the browser sill open it in the third party app if available.

**Comment by apbitner** [comment]
@rocketsroger can you please clarify what feedback from UX is needed?
