### ISSUE TITLE
Downloads are succeeding but reported as failed.

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#14154]
![Screenshot_20200823-204703](https://user-images.githubusercontent.com/1104290/91174517-afd09780-e6df-11ea-9a48-acf6dd1c1ec5.png)
## Steps to reproduce

1) https://forums.garmin.com/sports-fitness/cycling/f/edge-530/168009/understanding-climbpro-on-the-edge---updated-for-build-5-50
2) Download Understanding ClimbPro on the Edge V1.9.pdf

### Expected behavior

File downloaded, pop-up to open it.

### Actual behavior

An error is displayed with "try again". But the file did actually download correctly.

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly

**Comment by cadeyrn** [comment]
Duplicate of #14052.
