### ISSUE TITLE
Can't dismiss download notifications

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#14155]
-[ ] https://github.com/mozilla-mobile/android-components/issues/8073

## Steps to reproduce

1) Download a file (e.g. the one from #10304)
2) Wait for download to finish
3) Open Android notifications
4) Swipe on notification

### Expected behavior

5) Notification disappears

### Actual behavior

5) Notification can't be dismissed. Browser has to be force closed from task manager.

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly
![Screenshot_20200823-204729](https://user-images.githubusercontent.com/1104290/91174739-fe7e3180-e6df-11ea-83ee-59a320fd0de0.png)

**Comment by Amejia481** [comment]
Related AC issue https://github.com/mozilla-mobile/android-components/issues/8073

**Comment by liuche** [comment]
Let's dupe to #15527
