### ISSUE TITLE
Bring back the bookmarks as default page

### ISSUE THREAD

**Issue by terr72** [mozilla-mobile/fenix#14151]
### What is the user problem or growth opportunity you want to see solved?

On Gecko-based FF it was possible to set the bookmarks as default page when FF was started or all tabs were closed.
This feature has completely disappeared in FF 79.0.5.

### How do you know that this problem exists today? Why is this important?

It's the fastest and easiest way to visit your commonly used webpages straight after the start of FF.
The 'collections' feature is no replacment, since unlike bookmarks they don't allow renaming of site names.

### Who will benefit from it?

Everyone.

**Comment by cadeyrn** [comment]
Duplicate or part of #11453, #12065 and #12941.

**Comment by mcarare** [comment]
@terr72 Thank you for your suggestion. This is already something under consideration, and requested in other opened issues, as @cadeyrn mentioned. Closing this as duplicate.
