### ISSUE TITLE
Make QR-Code scanner link above keyboard optional in settings

### ISSUE THREAD

**Issue by terr72** [mozilla-mobile/fenix#14150]
### What is the user problem or growth opportunity you want to see solved?

FF 79.0.5 introduced a QR-Code scanner icon above the keyboard, which can't be disabled anymore like it was possible in Gecko-based FFs before.

### How do you know that this problem exists today? Why is this important?

People who don't use this function on a regular basis will touch this icon by mistake.
This is not only hte case for power users, but also for elder people.

### Who will benefit from it?

Everyone who doesn't want to have the QR code scanner link.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5463)

**Comment by rc1717** [comment]
I also would like to see the qr code button made to be optional. I think it's too cluttered when the keyboard already takes up a lot of space. It would be better to take this an option that can be disabled by people who do not need it.

**Comment by JonDeereGee** [comment]
I would also like to have the option of turning off the QR scanner. Instead of making things easier it gets in my way.

**Comment by mirko77** [comment]
+1, no reason to show it for me, please add an option to hide it

**Comment by metbic** [comment]
Seconded.

**Comment by trxraptor** [comment]
Both QR Scan and Search Engine buttons should be optional.

**Comment by niederlec** [comment]
Yes, it is really annoying because on small or medium screens, when opening a new tab, it's displayed over the favorites and most visited sites. So you MUST first close the keyboard if you want to use favorites.

**Comment by mirko77** [comment]
I agree, showing the keyboard when opening a new tab is an anti pattern, I always need to hide it to tap on a favorite.

**Comment by pellaeon** [comment]
Previously, selecting a search engine only requires one click on the search engine option. Now because of the scan QR code button, it requires two clicks (1. click "Search Engine" 2. click the specific search engine you want)

**Comment by JonDeereGee** [comment]
Why is it so hard to give users a choice? Wait a sec, I DO have a choice - not use Firefox.

**Comment by cjpcjpcjp** [comment]
Any update or movement on this issue? The code scanner is taking up valuable screen real estate. Many don't use it at all and it definitely should be optional.

**Comment by over1pixel** [comment]
what's wrong with your ux designers?? you unilaterally changed the ux in so many parts without giving the user any possibility but accept it. Make the qr core reader bar optional!!!

**Comment by sinisterseed** [comment]
Just ran into this issue earlier browsing for this.

This really should have been made optional from the beginning, on smaller screens it obstructs the view quite badly and makes it difficult to see the suggestions or most visited websites - or, in my case, as someone always holding the phone horizontally, it obstructs my view completely.

I literally can't see the websites at all due to the additional bar above my keyboard.

**Comment by ivantsyganov** [comment]
It should be optional. I don't want to see this option.

**Comment by matthewcorreia** [comment]
I hate this bar... Is there maybe something in the about:config that could remove it? I was searching for a way, but don't even know how to refer to it. Please remove this noise from the UI

**Comment by mohamedmadan** [comment]
can't see why this is not an optional button

**Comment by fe60** [comment]
Alternate options to provide a qr scanner button (and to get rid of the bar above the keyboard):
#11829: QR Scanner Shortcut
#16658: Integrate QR scanner into address bar

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807385

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
