### ISSUE TITLE
Context Menus are popping up in the wrong place with toolbar position to top

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#14157]
## Steps to reproduce

1) Try to paste into the address bar

### Expected behavior

1) Paste pops up below cursor

### Actual behavior

1) Paste pops up on the bottom of the screen

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly
![Screenshot_20200824_221806_org mozilla fenix](https://user-images.githubusercontent.com/1104290/91176006-f0c9ab80-e6e1-11ea-84d5-70d5dd4d25fe.jpg)

**Comment by Diana-Rus** [comment]
Hi, issue is fixed on Nightly 8/31 with
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)

<details closed><summary>Screens</summary>

**Pixel**
![Screenshot_20200831-133257](https://user-images.githubusercontent.com/49859863/91711079-f580da80-eb8d-11ea-9366-90128b5091c4.png)

**Samsung**
![Screenshot_20200831-132409_Firefox Nightly](https://user-images.githubusercontent.com/49859863/91710968-c702ff80-eb8d-11ea-918f-d95493f7aab3.jpg)

<details>
