### ISSUE TITLE
Installed websites retain the address bar, reducing screen real estate

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#14158]
## Steps to reproduce

1) Go to chessable.com
2) Install

### Expected behavior

3) Opening the installed app makes it fullscreen

### Actual behavior

3) Opening the installed app leaves the address bar on the bottom, thus reducing usable screen size. This is a regression compared to Fennec and Chrome.

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly
![Screenshot_20200821-120201](https://user-images.githubusercontent.com/1104290/91176344-73eb0180-e6e2-11ea-8b96-de09171b40c2.png)

**Comment by s-ankur** [comment]
I can't repro this in nightly

**Comment by gcp** [comment]
Confirmed either fixed in Nightly or caused by the Fennec migration.
