### ISSUE TITLE
[Bug] Addons don't work anymore

### ISSUE THREAD

**Issue by gartenriese2** [mozilla-mobile/fenix#14156]
## Steps to reproduce
Update Firefox to version 79.0.5
### Expected behavior
Addons work just as before
### Actual behavior
Addons are not working anymore
### Device information
OnePlus 7 Pro
* Android device: ?
* Fenix version: ?

**Comment by cadeyrn** [comment]
Since you didn't write which add-ons don't work I have to make a guess that your'e talking about add-ons that are not yet supported. There will be support for more add-ons in the future. Please follow https://blog.mozilla.org/addons/ for future announcements regarding add-on support in Firefox for Android.

**Comment by gartenriese2** [comment]
> There will be support for more add-ons in the future. Please follow https://blog.mozilla.org/addons/ for future announcements regarding add-on support in Firefox for Android.

Sounds like it won't be a quick fix. I have reverted back to 68 in the meantime, where the bug is not build in yet.

**Comment by GavinBrelstaff** [comment]
... and side loading my own web-extension addons that require permission that mean they can't show up in the store?

**Comment by toupeira** [comment]
Is there a main issue we can follow for full WebExtension support?

I saw the board at https://github.com/orgs/mozilla-mobile/projects/44 but didn't find such an issue there.

I also saw this issue at https://github.com/mozilla-mobile/fenix/issues/14034 about possibly adding this in Nightly soon, which would be great!

**Comment by kbrosnan** [comment]
Closing for #14034
