### ISSUE TITLE
Automatic tabs close at app exit

### ISSUE THREAD

**Issue by marcomg** [mozilla-mobile/fenix#14159]
In the previous Firefox versions was possible to automatically close tabs at the browser's closure.
With this new version is not possible. I could delete the tabs enabling it in the menu tapping on exit. But is not anymore possible doing it tapping home button on Android and swiping for closing the app.

79.0.5 (Build #2015758619)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10

**Comment by Dunexus** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/3950

**Comment by liuche** [comment]
There's a feature in #3700 and swipe-close would be #3950
