### ISSUE TITLE
[Bug] Most add-ons not supported in version 79

### ISSUE THREAD

**Issue by griveralfie** [mozilla-mobile/fenix#14152]
Very few add-ons are supported, in older versions almost all Firefox add-ons worked well on mobile too

**Comment by cadeyrn** [comment]
This not a bug but expected. There will be support for more add-ons in the future. Please follow https://blog.mozilla.org/addons/ for future announcements regarding add-on support in Firefox for Android.

**Comment by Dakkaron** [comment]
It's not a bug, it's a feature! Who needs addons anyways? -.-

**Comment by cadeyrn** [comment]
> It's not a bug, it's a feature! Who needs addons anyways? -.-

Your comment doesn't make sense at all. GitHub is a working tool for the developers. Please do not spam.

**Comment by griveralfie** [comment]
> > It's not a bug, it's a feature! Who needs addons anyways? -.-
> 
> Your comment doesn't make sense at all. GitHub is a working tool for the developers. Please do not spam.

Bet you're popular with the ladies 😉

**Comment by Dunexus** [comment]
@griveralfie Github is a tool for developers to manage their project. Please keep it clean and professional.
