### ISSUE TITLE
Option to disable Phishing and Malware Protection 

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14163]
### What is the user problem or growth opportunity you want to see solved?

No way to disable Phishing and Malware Protection for users who are suspicious of Google/Yandex and leaking browsing history to Google/Yandex. 

### How do you know that this problem exists today? Why is this important?

This came up in SUMO chat. An option exists in desktop. `about:config` could previously have been used in Fennec. 

### Who will benefit from it?

People suspicious of Google/Yandex.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5481)

**Comment by cadeyrn** [comment]
> users who are suspicious of Google and leaking browsing history to Google

More important seems to be that theese people read how SafeBrowsing in Firefox works. It does **not** work by sending Google the browsing history.

**Comment by bartlomiejb** [comment]
> > users who are suspicious of Google and leaking browsing history to Google
> 
> More important seems to be that these people read how SafeBrowsing in Firefox works. It does **not** work by sending Google the browsing history.

Even if it doesn't send full history it may send some info to Google and it is not desirable. It also requires bandwidth and many mobile users are on a tight plans, so why do you want to take bandwidth from them without their explicit consent? Why take away option to disable it from them?

See also https://www.washingtonpost.com/news/the-switch/wp/2013/12/10/nsa-uses-google-cookies-to-pinpoint-targets-for-hacking/?arc404=true for a story how NSA is able to use unique ids (like cookies, and so-called "safebrowsing" sends them) in internet traffic for their nefarious purposes.

**Comment by yoasif** [comment]
> 
> 
> > users who are suspicious of Google and leaking browsing history to Google
> 
> More important seems to be that these people read how SafeBrowsing in Firefox works. It does **not** work by sending Google the browsing history.

I thought this article was interesting: https://blog.trailofbits.com/2019/10/30/how-safe-browsing-fails-to-protect-user-privacy/

**Comment by 3j9fkyahunqoxwqu** [comment]
Safe browsing (AKA. Malware and phishing protection won't work the way you mentioned nor it downloads the whole blocklist.

It may probably use same amount of network bandwidth a normal blocklist that you use in ublock.

https://feeding.cloud.geek.nz/posts/how-safe-browsing-works-in-firefox/

**Comment by bartlomiejb** [comment]
> Safe browsing (AKA. Malware and phishing protection) won't work the way you mentioned nor it downloads the whole blocklist.
> 
> It may probably use same amount of network bandwidth a normal blocklist that you use in ublock.
> 
> https://feeding.cloud.geek.nz/posts/how-safe-browsing-works-in-firefox/

That article is from 2016. Why do you think nothing has changed since that time?
The more relevant is probably this page: https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work#w_what-information-is-sent-to-mozilla-or-its-partners-when-phishing-and-malware-protection-are-enabled

Eg.
"In addition to the regular list updates mentioned above, when using Malware Protection to protect downloaded files, Firefox may communicate with Mozilla's partners to verify the safety of certain executable files. In these cases, Firefox will submit some information about the file, including the name, origin, size and a cryptographic hash of the contents, to the Google Safe Browsing service which helps Firefox determine whether or not the file should be blocked. "

How do you think what "origin" means in this context, if not full URL?

**Comment by jawz101** [comment]
Just because you see the word "cookie" doesn't mean it's a tracking thing.  It just gives the browser a timestamp or version string- something to know what version of the db its on.

**Comment by bartlomiejb** [comment]
> Just because you see the word "cookie" doesn't mean it's a tracking thing. It just gives the browser a timestamp or version string- something to know what version of the db its on.

No, I speak above about HTTP cookies, in particular set by google.com domain; you are wrong and you have no idea what you are talking about.

**Comment by clientenq** [comment]
Regardless of the background behaviour of these default functions the users should be in control about what content they want to view or visit.
This control is removed and thus now Firefox and Google are in control. This is not safe by default. The safe browsing also has false positives. Users may deliberately want to view a resource regardless of the opinion of the safe browsing service. It should at least be an option to visit a marked as unsafe resource like visiting possible insecure https sites can be accepted by a user.
Also, the text of the warning reads " has been blocked based on your security preferences". User preferences indicate it should be configurable.
It is appreciated Firefox and Google like to protect users but this should not be enforced without the only choice of do or do not use Firefox if you want control over what you can view online and your security preferences.

**Comment by 3j9fkyahunqoxwqu** [comment]
> Regardless of the background behaviour of these default functions the users should be in control over what content they want to view or visit. This control is removed and thus now Firefox and Google are in control.
> 
> This is not safe by default. This is not freedom of access to information by default.
> 
> The safe browsing is not a magic bullet to protect users from harm or provide freedom of access to safe content. It is a best effort service and thus also has false positives and false negatives users should be able to ignore. Safe browsing is only an indication based on Google service. Users may or may not like to trust this per warning or completely. Why they like to ignore or trust Google or results of services is up to users
> 
> Users may deliberately want to view a resource regardless of the opinion of the safe browsing service and Google or any other future provider of this sort of services. Regardless the possible negative consequence of ignoring the advise. It can also have negative consequence by not allowing the user to visit a resouce. Currently these last mentioned consequences are primary projected at the user, not Firefox or Google. This does not seem fair without users being in control over the final decision to follow or ignore safe broesing service warnings.
> 
> Users should at least have the option to visit a marked as unsafe resource, like visiting possible insecure https sites can be accepted after a fair warning.
> 
> It would be more reasonable to also provide the option to disable these Google based features like is possible in other versions of Firefox for multiple reasons. Reasons like dependency on a specific company or unwanted service behaviour or results.
> 
> Also, the text of the warning reads " has been blocked based on your security preferences". User preferences indicate it should be configurable.
> 
> It is appreciated Firefox and Google like to protect users but this should not be enforced by the only choice of do or do not use Firefox if you want control over what you can view online and who you trust.

Agree

**Comment by andreicristianpetcu** [comment]
@yoasif what is the about:config setting?

**Comment by yoasif** [comment]
> @yoasif what is the about:config setting?

@andreicristianpetcu There are some entries for `browser.safebrowsing.` if you search. I haven't tried them myself.

**Comment by YoshiTabletopGamer** [comment]
Apparently, in Firefox Focus, when a bug was filed for Safe Browsing not being able to be disabled, it got fixed (https://github.com/mozilla-mobile/focus-android/issues/4155) Why not do the same thing with Firefox for Android, not just because of privacy, but to be consistent?

**Comment by YoshiTabletopGamer** [comment]
Also, currently, there's no option to disable for a specific site once, like on the desktop, which means it becomes impossible to access a mistakenly blocked website until Google authorizes it.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807455

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
