### ISSUE TITLE
[Bug] top sites layout changed for the worst

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14167]
Jesus today top sites layout changed only 8 tops sites are shown.
the ability to have many topsites on home was the only reason I was still using this crap of fenix.
it's time to move to Samsung internet.
is this change permanent why the Mozilla devs are ruining fenix day after day?

**Comment by Dunexus** [comment]
> Jesus today top sites layout changed only 8 tops sites are shown.

You can have more than 8 tops site, they will just be on multiple slides you can browse by swiping them. See https://github.com/mozilla-mobile/fenix/issues/8312 for more context.

> the ability to have many topsites on home was the only reason I was still using **this crap of fenix**.

Is this how you ask people to improve the product ? By insulting their work ? Pretty sure respect is way more effective.

**Comment by kbrosnan** [comment]
Closing as a duplicate

**Comment by ale82to** [comment]
I do not want to swipe.
