### ISSUE TITLE
FNX-5015 ⁃ [Bug] Permission doorhanger buttons not visible on small devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1416]
## Steps to reproduce
1. Go to permission.site
1. Tap on camera/microphone/notifications.
    1. Expected behavior
A doorhanger is displayed, with two buttons.
    1. Actual behavior
The two buttons Allow/Don't allow are not displayed on 4.9, 5 inch screens.
*on a Nexus 5 emulator, they are displayed.
    1. Device information

* Android device: Nexus 5(Android 6), Xiaomi Redmi 5 (Android 5)
*Not reproducible on Huawei P20 lite (5.8"")
* Fenix version: 4/5

**Comment by sv-ohorvath** [comment]
![Screenshot_2019-04-05-16-05-20_org mozilla fenix debug](https://user-images.githubusercontent.com/4037709/55631090-e4c50d00-57bf-11e9-823b-7ef860b3afe1.png)
![Screenshot_2019-04-05-16-05-12_org mozilla fenix debug](https://user-images.githubusercontent.com/4037709/55631091-e4c50d00-57bf-11e9-8be1-b0fd7ea671f9.png)

**Comment by Amejia481** [comment]
Related: https://github.com/mozilla-mobile/android-components/issues/2489

**Comment by sv-ohorvath** [comment]
Also reproducing on HTC Desire 820 (Android 6.0.1)

**Comment by bsurd** [comment]
Verified on the latest master with a Nexus 5. Permissions can now be successfully allowed/denied on small devices as well.
