### ISSUE TITLE
Delay in displaying the proper site connection is encrypted when navigating

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#14172]
## Steps to reproduce
open a site have encryption, ssl like duckduck go and look at lock on bar.
### Expected behavior
locke on bar not locked and locked after a few second
### Actual behavior
lock must be lock after browsing on https site and not shown unlocked and locked after a few second!
### Device information

* Android device: xiaomi note 8t
* Fenix version: Firefox 79.0.5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5494)

**Comment by s-ankur** [comment]
I cant reproduce this on latest nightly, even when opening http://www.wikipedia.org and http://www.duckduckgo.com

**Comment by AgentOak** [comment]
Noticed this as well. Hopefully it's only a UI bug showing the wrong lock icon, and Firefox doesn't *actually* try to open https:// links as http:// - no way to tell witth the scheme missing from the URL bar.

**Comment by minutesinch** [comment]
> Noticed this as well. Hopefully it's only a UI bug showing the wrong lock icon, and Firefox doesn't _actually_ try to open https:// URLs as http:// first - no way to tell with the scheme missing from the URL bar.

yes that's only ui bug but its bug however!

**Comment by ekager** [comment]
@minutesinch are you still seeing this ?

**Comment by minutesinch** [comment]
Yes I see

**Comment by minutesinch** [comment]
Still exist

**Comment by AgentOak** [comment]
Bug still exists, reproducer is still 100% accurate and I just verified it on 92.1.1.

**Comment by outhex** [comment]
Still applies on the following build:

- 93.0.1 (Build #2015836707)
- AC: 93.0.11, 701ac90be7
- GV: 93.0-20210927210923
- AS: 82.1.0

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is still reproducible on Firefox Preview Nightly 2021-11-25.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by AgentOak** [comment]
Confirmed on Firefox Android 107.1.0  (Build #2015915067). Lock icon still shows the insecure padblock for a couple of moments when loading a site, even with HTTPS-only mode on.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813834

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
