### ISSUE TITLE
Snooze Tabs

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#14179]
### What is the user problem or growth opportunity you want to see solved?
Users use the web to monitor data points, but sometimes they need to wait some time for that data to change. For example, I’m monitoring when my local county will get off the governor’s COVID watch list by looking at this: https://covidactnow.org/us/ca/county/contra_costa_county/?s=938188 One way to get ‘notified’ about this is to check the page every day, but since it’s slow moving, I need to wait weeks instead of checking every day. 

Fenix should allow me to ‘snooze’ a tab, similar to how GMail allows me to snooze an email, for a set period of time, and then when that time expires, the tab should be reopened (similar to how you can send tabs between devices via a push notification).

### How do you know that this problem exists today? Why is this important?
I have this problem today. The change in data is important to me, and having to keep the browser tab open is bad for my system’s memory and makes managing my tabs harder.

### Who will benefit from it?
Fenix users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5503)

**Comment by yoasif** [comment]
Port https://medium.com/firefox-test-pilot/snooze-tabs-graduation-report-254e0d395887 ?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812914

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
