### ISSUE TITLE
google search

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#14171]
The google search page is outdated and lacks the extra features of the google search page's interface that appears in chromium browsers.

Many of my friends don't use firefox for this reason.
![Screenshot_20200825-182420_Firefox](https://user-images.githubusercontent.com/60405617/91194768-203be080-e701-11ea-8bcb-804f7e2eaf58.png)

**Comment by Mugurell** [comment]
It's a known problem unfortunately.
Please refer to https://github.com/mozilla-mobile/fenix/issues/5350
