### ISSUE TITLE
[Bug] blank page with html label in address

### ISSUE THREAD

**Issue by SmilingCoyote** [mozilla-mobile/fenix#14180]
A recurring blank page render.
 I suspect the originating site's dynamically generated page is being generated at the top,  spawning new pages as the user scrolls down since it is most noticable with hashtagged links i.e. 
https://en.m.wikipedia.org/wiki/Toyota_A_transmission#A140E
It is intermittent. 
Adendum: FFox refresh, reload the url does not work. Rotating the screen does.
So this could be a specific Galaxy/FireFox issue. Rotate screen fix? Really? FF is the only app that does this.
Galaxy Tab E  SAMSUNG-SM-T377V
Droid 7.1.1

**Comment by liuche** [comment]
We've had a blank tabs issue in nightly recently, so this could be that issue #5478

**Comment by madb1lly** [comment]
Hello @liuche,

I don't think this sounds the same as #5478, the fix by rotating the screen has not been reported as a way to correct an "about:blank" tab.

@SmilingCoyote, when this happens does the address bar show "about:blank"?

Cheers 🙂

**Comment by SmilingCoyote** [comment]
Nope. Strange thing I noticed that in YouTube I was able to barely pull
down the upper corner to see the YouTube logo at the top peeking over
behind the white sheet. Weirdest thing I've ever seen. Like it was a white
<div> overlay.

**Comment by SmilingCoyote** [comment]
Forgot to mention, I've done a complete factory reset and re-installed
Firefox nightly since. Same intermittent issue.

**Comment by SmilingCoyote** [comment]
Sheesh. I think I figured it out.
These pop ups are resizing over the entire display.
White script embedded pop ups.

**Comment by madb1lly** [comment]
Hi @SmilingCoyote,

Does this only happen on one site or others too? How do you manage to recover the page from this state?

Cheers 🙂

**Comment by SmilingCoyote** [comment]
As previously stated, I rotate it, it goes from portrait to landscape or
inverse of that and the pop ups get canceled. Like those that YouTube
advert for YouTube tv. Wikipedia has the same format popup I presume since
it too does the white screen.

**Comment by madb1lly** [comment]
Hi @SmilingCoyote,
I think you might need to raise a new issue because I'm not sure anyone from the Fenix team is looking at this because it was closed.
Cheers 🙂

**Comment by liuche** [comment]
Interesting, do these go away if you turn off ETP? ETP might be blocking those from loading, if it's a full-screen popup.

**Comment by SmilingCoyote** [comment]
Tracking? I don't know since. It's less often now than in the past. An
adversary noted to me that perhaps the droid nerds at either the original
carrier or Google might have been sticking their noses into it causing a
glitch between the Firefox tab pull up and the web sites popup. As these
things are closed systems else the Samsung gods cast it down, there's no
real way of knowing. Am still waiting for that jump chip and droid linux.
Just dreaming. Thanks for your input. Though short it applies a vector to
my thinking, giving me different directions to contemplate.
It has obscured 5 times since this post began from an hourly occurrence.
This thread is essentially dead.

**Comment by SmilingCoyote** [comment]
As a eh huh he said, perhaps a trinary bug as is his style. And I realized
ah. Here's a picture for a thousand words.

>
