### ISSUE TITLE
Set the old UI as opt in

### ISSUE THREAD

**Issue by U-B-Glade** [mozilla-mobile/fenix#14188]
### What is the user problem or growth opportunity you want to see solved?
Look to Play Stor reviews :-)
The old UI was fine and usable, the new isnt.

### How do you know that this problem exists today? Why is this important?
It is just the usability, (not real important, but nice :-))

### Who will benefit from it?
The Project
The satisfiing of the developper
The User

**Comment by liuche** [comment]
This is a complete re-write, there's not a way to support both forks.

**Comment by U-B-Glade** [comment]
Sorry, but maybe you have to do this, the new UI is unusable. :-(

**Comment by dadosch** [comment]
Firefox's users where trained **over years** on how to use "their" browser. Such a rapid and gigantic change WILL lead to frustration, anger and finally to a decline of users.
