### ISSUE TITLE
make automatic "Install App" deselectable

### ISSUE THREAD

**Issue by U-B-Glade** [mozilla-mobile/fenix#14190]
### What is the user problem or growth opportunity you want to see solved?
I feel forced by you if you show me all the Time that there is an App, I am able to install an App if i like.

### How do you know that this problem exists today? Why is this important?
look to the FF

### Who will benefit from it?
The Project
The free Internet
All mature User

**Comment by liuche** [comment]
This is working as intended - there wouldn't be another way to install a PWA if the option were not present.
