### ISSUE TITLE
FNX-5016 ⁃ Replace placeholder images on home fragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1419]
Currently we have two placeholder images on the home fragment:

1) When a tab has **not been loaded** we use a placeholder image instead of showing a snippet of the webpage
![](https://user-images.githubusercontent.com/4400286/55643467-0bffe800-5788-11e9-943b-7820f524d125.png)

2) When a session is bundled up we show this the little stacked tabs icon with a random color. This one especially should be changed since it takes up a lot of space and doesn't really provide any context/information to the user. Perhaps we could use it to display favicons of the websites or something? 

![](https://user-images.githubusercontent.com/4400286/55643475-0f936f00-5788-11e9-94d7-a9de25630d98.png)

This is likely something we want to address before MVP.

**Comment by vesta0** [comment]
@lime124 could we have UX look at this?

**Comment by lime124** [comment]
hey @vesta0 and @sblatz - @topotropic and @AmyYLee are wrapping up the news designs this week and hope to share soon. let's punt on anything related to sessions for now and revisit all these issues to see if it's still applicable to the new designs. thanks!

**Comment by mheubusch** [comment]
@AmyYLee @topotropic Please review

**Comment by AmyYLee** [comment]
With the new Collections design, this bug is no longer relevant. Please see updated spec for reference https://mozilla.invisionapp.com/share/U2RMIIZYBKE
