### ISSUE TITLE
provide geolocation info for MLS/ichnaea

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#14197]
### How do you know that this problem exists today? Why is this important?
The last android version before Fenix included the possibility to run something like the Mozilla stumbler app in the background to collect data for [Mozilla's location service](https://location.services.mozilla.com/). 

### Who will benefit from it?
All Firefox users, especially ones that don't have Google's service as an alternative (aosp without playstore).

Without this data collection, MLS data will get old and inaccurate over time. 

If you reintroduce this at some point, then it might be worth it to update the code base of server and client to support stumbling 5g cells.

**Comment by kbrosnan** [comment]
Duplicate #1253
