### ISSUE TITLE
[Bug] When calling a custom tab from another application and then trying to 'open with firefox', firefox crashes

### ISSUE THREAD

**Issue by aaronwi** [mozilla-mobile/fenix#14199]
## Steps to reproduce
open any website url from an external application such as bacon reader, discord, whatsapp
then 'open with firefox' from within the custom tab
### Expected behavior
open the website

### Actual behavior
crashes firefox, 100% of the time, restart will not open the url.

### Device information

* Android device:android 9, miui 11.0.7, redmi note 8
* Fenix version: 68.11.0
Crash ID: 74526152-a5c9-7eb2-f218-8e210593e124

**Comment by jonalmeida** [comment]
> Fenix version: 68.11.0

68 is Fennec, not Fennec.

**Comment by aaronwi** [comment]
> 
> 
> > Fenix version: 68.11.0
> 
> 68 is Fennec, not Fenix.

I just went with the default template, neither of those codenames? are listed anywhere

**Comment by jonalmeida** [comment]
If you are seeing the version as 68 then that means you are using the old version of Firefox for Android.

This project (Fenix) is the new version, so the bug may be invalid.

**Comment by Djfe** [comment]
fennec is everything up to 68.xx.x
fenix is thew version you might be able to update already through the play store.
the new version is a complete revamp so it likely doesn't have this issue.

the old version won't be fixed anymore or receive updates.

this repo is only meant for the new version (fenix)
[Bugzilla](https://bugzilla.mozilla.org/) was for the old version.

**Comment by kbrosnan** [comment]
Closing as invalid. Firefox 68 is no longer supported. https://www.mozilla.org/en-US/firefox/android/68.11.0/releasenotes/
