### ISSUE TITLE
[Bug] Magnet URIs cannot be copied via long-press

### ISSUE THREAD

**Issue by Syquel** [mozilla-mobile/fenix#14195]
## Steps to reproduce
1. Navigate to a website with a magnet URI (e.g. [Wikipedia](https://en.wikipedia.org/wiki/Magnet_URI_scheme#Design) )
2. Long-Press the magnet URI

### Expected behavior
The URI popover is displayed with the option "Copy Link" as it is for HTTP(S) links.

### Actual behavior
Nothing happens.

### Device information

* Android device: Google Pixel 3 (Android 10)
* Fenix version: Firefox for Android 79.0.5

**Comment by kbrosnan** [comment]
Duplicate #6149
