### ISSUE TITLE
Faster way to close a tab on larger screen

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#14203]
## Steps to reproduce

Open several tabs
Read a tab 
Close the tab.

### Expected behavior

You should have as you have both on the previous version of Firefox for Android and the Desktop, an X to allow you to close the tab from the original page and move to the next open tab

### Actual behavior
You need to select the tabs count, and either then select the close tab option or  when that page opens, press the X to close the tab and then select the next tab to view

A doubling or tripling of key actions

### Device information

* Android device: Lenovo Tab. Android 8.1
* Fenix version: 79.0.5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5543)

**Comment by yoasif** [comment]
Not sure exactly what you are asking for, but you can hold down on the tab switcher icon and select "close tab".

**Comment by nigelh747** [comment]
> 
> 
> Not sure exactly what you are asking for, but you can hold down on the tab switcher icon and select "close tab".

I am looking for an Icon next to the tab switcher icon that allows me to directly close a tab, rather than have to go through two steps.  It could be a user accessibility option.  However the fact that its disappeared is a regression and a bug

**Comment by Poopooracoocoo** [comment]
#4498

**Comment by gwarser** [comment]
Fennec had ability to emulate this by install add-on which will add page action button which will close the tab. Now add-ons menu is buried so deep that accessing add-on buttons is very difficult even for add-ons which does not require to be accesses often.

In current UI, closing multiple tabs is held back by toast notifications which are not transparent to touches.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812913

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
