### ISSUE TITLE
FNX-5018 ⁃ Change how we're generating the screenshots for HomeFragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1420]
Currently we're screenshotting the center of the page and using that as a tab preview. Unfortunately, this often means the content is not actually very helpful, as it's some random snippet of text. I wonder if we screenshotted something closer to the top, we'd give users a better preview of their content?

We could also consider displaying a more zoomed out view, which shows **more** of the page to combat this as well.

![](https://user-images.githubusercontent.com/4400286/55643729-bbd55580-5788-11e9-9047-f65ab885f197.png)

**Note: this is likely very small engineering effort and could make this feature a _lot_ more usable!**

**Comment by Amejia481** [comment]
The [ThumbnailsFeature](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/README.md#thumbnailsfeature) is taking a screen shot of the visible area of the screen. We are only showing the center of it with  `android:scaleType="centerCrop"`


[`tab_list_row.xml`](https://github.com/mozilla-mobile/fenix/blob/598ca17bebcef38c5f513e8d3006c892ced978af/app/src/main/res/layout/tab_list_row.xml#L65)
```xml
      <ImageView
            android:id="@+id/tab_background"
            android:layout_width="0dp"
            android:layout_height="100dp"
            android:layout_marginTop="10dp"
            android:adjustViewBounds="false"
            android:focusable="false"
            android:scaleType="centerCrop"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/favicon_image" />
```

https://github.com/mozilla-mobile/fenix/blob/1d032bbe53375e33c919230a651a868070e22cf1/app/src/main/java/org/mozilla/fenix/home/tabs/TabsAdapter.kt#L126
