### ISSUE TITLE
[Bug] You cannot scroll the list of tabs when you first open the tab tray

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14205]
## Steps to reproduce
1. Open 3 tabs
2. Before the tab tray flashes, try to scroll to the first tab

### Expected behavior
you can scroll to the first tab

### Actual behavior
tab tray closes as you're not scrolling the tabs but you are swiping the tab tray away

### Device information

* Android device: ?
* Fenix version: Nightly 200825

**Comment by PlayXman** [comment]
Duplicate of #14837 
...or vice versa

**Comment by Poopooracoocoo** [comment]
Looks like I made this before :o

**Comment by ekager** [comment]
closing for #14837 because it's had more discussion
