### ISSUE TITLE
[Bug] Tabs are unexpectedly closed 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14207]
## Steps to reproduce

Long Press tab counter+close tab 
undo
Long press tab counter + new private tab /new tab
### Expected behavior
New private tab
### Actual behavior
New private tab + older tab is closed for some reason
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Hi, I can still see this isssue

**Comment by ekager** [comment]
@s-ankur can you still repro?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201218-121854](https://user-images.githubusercontent.com/51314259/102603519-98ecff80-412b-11eb-9800-51b7253f9290.gif)
