### ISSUE TITLE
[Bug] Blank page is displayed when Firefox is resumed from running-from-background.

### ISSUE THREAD

**Issue by gvivwilson** [mozilla-mobile/fenix#14201]
Whenever Firefox is running from background, sometimes it displays a blank page when I re-open it. Reloading the webpage does not fix it. I need to quit the app and open Firefox again to fix it. It does not happen all the time, but frequent enough to see two or three occurrences daily.

## Steps to reproduce
1. Open Firefox and load a webpage.
2. Press Home button and work on any other app. Let Firefox run on background for quite a time.
3. Re-open Firefox.

### Expected behavior
Displays the webpage where I left it.

### Actual behavior
Displays blank page. Can't be fixed by reload.

### Device information
* Android device: Samsung Galaxy S9
* Fenix version: 79.0.5

**Comment by liuche** [comment]
Working on a fix in #5478
