### ISSUE TITLE
[Bug] inception of iframes and fullscreen controls not working

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#14202]
## Steps to reproduce
1. Go to https://www1.kickassanime.rs/anime/uzaki-chan-wa-asobitai-230148/episode-07-568869
2. Tap play on the video
(be aware of the tab armageddon of ads)

### Expected behavior
video controls for fullscreen is working

### Actual behavior
not working can't go to fullscreen

this is working in chrome.

### Device information

Tested with:
Browser / Version: Firefox Nightly 200823(🦎 81.0a1-20200820093209) Chrome Mobile 83.0.4103.111
Operating System: OnePlus6 (Android 10) - 1080 x 2280 pixels (~402 ppi pixel density)

so the control for fullscreen is already set as fullscreen even before the image is really is. 

also the site is inceptions of iframe…

```html
<div class="ka-player mb-3 embed-responsive embed-responsive-16by9">
  <iframe allowfullscreen="allowfullscreen" src="https://haloani.ru/dust/player.php?link=lMPAFD… cut for brevity"
  scrolling="no" class="embed-responsive-item"></iframe>
</div>
```

which includes

```html
  <iframe marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="allowfullscreen" src="https://haloani.ru/Beta-Server/player.php?link=lMPAFDFNWf9M346Niam8IeYUQPcDX501U@ZJgwgdC0N/1xjOnMzrihgORcxJ8Q8anRPKTJARVr/jt5Iav6LHjVayB0vRzsm@TLoYaQ==" frameborder="0"></iframe>
</div>
```

which includes

```html
<iframe src="pref.php?link=lMPAFDFNWf9M346Niam8IeYUQPcDX501U@ZJgwgdC0N/1xjOnMzrihgORcxJ8Q8anRPKTJARVr/jt5Iav6LHjVayB0vRzsm@TLoYaQ==&amp;" style="width:100%;height:100%" scrolling="no" allowfullscreen="true" width="720" height="90" frameborder="0"></iframe>
```

which finally includes

```html
<div class="jw-media jw-reset">
  <video class="jw-video jw-reset" tabindex="-1" disableremoteplayback="" webkit-playsinline="" playsinline="" src="https://redirector.googlevideo.com/videoplayback?expire=1598439735&amp;ei=t9BFX6unDIiJ2LYPyNWvgA4&amp;ip=51.210.101.0&amp;id=c05008eb8dc30a75&amp;itag=22&amp;source=blogger&amp;mh=gf&amp;mm=31&amp;mn=sn-25glen7y&amp;ms=au&amp;mv=u&amp;mvi=4&amp;pl=27&amp;susc=bl&amp;mime=video/mp4&amp;dur=1420.109&amp;lmt=1598020344826504&amp;mt=1598410356&amp;sparams=expire,ei,ip,id,itag,source,susc,mime,dur,lmt&amp;sig=AOq0QJ8wRQIhAN4tf5LzPAyXyEDL9DsLiJXl9F5fKKLcuEB6kXbT0e5IAiBItZBWazj4BA_Z-GLEblkxg8HKpFtNWD2CvG-SvYnTAw%3D%3D&amp;lsparams=mh,mm,mn,ms,mv,mvi,pl&amp;lsig=AG3C_xAwRgIhAIk6lijCiZQceT4SvmQUgXFgwOWwDUb9Yp5AGjDGWmtKAiEAjwC545ObyZTYAasNRpkW0-n83l_0DvVf_IrwUAKGk4A%3D"
  style="object-fit: fill;"></video>
</div>

```

if I enter directly https://haloani.ru/Beta-Server/player.php?link=lMPAFDFNWf9M346Niam8IeYUQPcDX501U@ZJgwgdC0N/1xjOnMzrihgORcxJ8Q8anRPKTJARVr/jt5Iav6LHjVayB0vRzsm@TLoYaQ==

The controls are not responsive at all too.

**Comment by ksy36** [comment]
This is probably related to https://github.com/mozilla-mobile/fenix/issues/14003 and corresponding GeckoView bug https://bugzilla.mozilla.org/show_bug.cgi?id=1661270

**Comment by kbrosnan** [comment]
Going to close this in favor of 14003
