### ISSUE TITLE
[Bug] unable to tap links near the bottom of the page

### ISSUE THREAD

**Issue by JamesM777** [mozilla-mobile/fenix#14213]
FOOTER LINKS NOT WORKING IN FIREFOX ANDROID 79

On Firefox android 79, go to www.jamesrmeyer.com . Scroll down until footer reduces in height. Click on links/icons in footer.

Links should open, or icons should initiate JavaScript action.

Nothing actually happens. Other browsers operate correctly, as did previous Firefox Android. But it works correctly when user scrolls to top and footer resizes.

Tablet: Samsung Tab S2, Phone: Huawei Honor 8x

Android device: Yes
Fenix version: No

**Comment by kbrosnan** [comment]
What settings do you have for the address bar? Top/bottom? Are you able to reproduce this behavior in [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

**Comment by JamesM777** [comment]
It makes no difference whether the address bar is at the top or the bottom.
I have checked on Firefox nightly (200826 06:01 (#2015760179) and the
behaviour is exactly the same.

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1664958
