### ISSUE TITLE
BaseBrowserFragment uses fixed selected session to initialize UI

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#14215]
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L211-L638

```Kotlin
protected open fun initializeUI(view: View): Session? {
  return getSessionById()?.also { session ->
    // ...
  }
}
```

This code is problematic. `getSessionById()` returns the fixed session (e.g. in a custom tab) or the selected tab (`sessionManager.selectedSession`). The selected tab can change during the lifetime of the fragment and so we shouldn't use it to initialize the UI once.

Luckily there's only one place where the session parameter is used. So this may not be a big project to refactor.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5558)

**Comment by pocmo** [comment]
Nowadays we still use

```
val tab = getCurrentTab()
browserInitialized = if (tab != null) {
   initializeUI(view, tab)
```

So I think the underlying problem still exists: The UI should get initialized(!) without a tab, and by observing the store the UI should react to the current/selected/custom/whatever tab changing.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810169

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
