### ISSUE TITLE
Back button disappeared from pop-up menu [Bug] 

### ISSUE THREAD

**Issue by omnitetranet** [mozilla-mobile/fenix#14214]
## Steps to reproduce
Click on menu dots

### Expected behavior
Back button near forward arrow

### Actual behavior
No arrow to go back and direct access to the visited pages history

### Device information
Before last consistent update there're both arrows in that menu.

* Android device: Honor view 10
* Fenix version: ?

**Comment by Poopooracoocoo** [comment]
Which version of Fenix are you using?

**Comment by cadeyrn** [comment]
There will be a back button in the menu in Firefox 80 and higher. In the meantime you can use the Android back button or use gesture navigation if you're on a newer Android version.

**Comment by omnitetranet** [comment]
I don't know "Fenix version"... where can I get it?

This is the Firefox data captured from the information form:
79.0.5 (Build #2015758619)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10

My phone is equipped with android 10.





In data 26 agosto 2020 12:59:09 Sören Hentzschel <notifications@github.com> 
ha scritto:

**Comment by cadeyrn** [comment]
> I don't know "Fenix version"... where can I get it?

Menu > Settings > About Firefox

It seems you already found it. In your case 79.0.5 is the version number.

**Comment by liuche** [comment]
This is #12926 and in Firefox 80+
