### ISSUE TITLE
FNX-5019 ⁃ [Bug] "Shortcuts" button color wrong when selecting alternative search engine

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#1421]
## Steps to reproduce
Tab URL to enter search mode
Tap Shortcuts button
Select Bing
-> Shortcuts button text turns black, hard to read on purple background
Tap Shortcuts button
-> Shortcuts text & background both white, can't read

Similar happens in Dark mode

### Expected behavior
Shortcuts text should be consistent (black text on white or white text on purple)

Galaxy S7
Fenix 1.0.1914 68.0a1-20190403060632

**Comment by bsurd** [comment]
Tested on a Pixel, Galaxy S8, Nokia 6 and HTC 10. This is no longer reproducible and works for both light and dark theme as intended.
