### ISSUE TITLE
Support WebExtension storage.sync syncing

### ISSUE THREAD

**Issue by kevincox** [mozilla-mobile/fenix#14218]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

### What is the user problem or growth opportunity you want to see solved?

Syncing extension data between desktop and mobile and across mobile devices (including to replacement devices) prevents repeated tedious setup and configuration of your mobile browser.

### Who will benefit from it?

Everyone who uses extensions. (As long as they end up getting a second device at some point in their life)

**Comment by kbrosnan** [comment]
WebExtensions is one area where we generally don't sync things between desktop and mobile. If we decide to do this it needs to be coordinated with the addons and webextensions teams. @caitmuenster

**Comment by kevincox** [comment]
You touch on a very good point. Users may want different things on different devices. Right now sync just ignores this problem completely. However with the mobile to desktop use case it is harder to ignore. There are a number of simpler options here:

1. Sync the extension data to all devices, but only sync the extension list between desktops and mobiles.
2. Recommend setting up a different sync account for each "device group"

My use case is I have one extension that I would like to use on mobile with the same config as on desktop. But I don't really want to sync all of my extensions to mobile. The ultimate solution would be some granular control of what syncs to each device.

- You could select which devices each add-on could be on.
- You can make "device groups" which share extension data.
  - Even more ideal would actually be pushing this to each extension so you could make this decision per-pref or other chunk of data in the extension. But we likely would see very few extensions supporting this.
- You could also do this for bookmarks (maybe by folder) or history. (For example don't sync my personal history to my work laptop).

However this would be a lot of work, and it would be very hard to make good UX for all of this granular control. I suspect that 1 is the best option for now however it would be good to see more opinions.

**Comment by caitmuenster** [comment]
Thanks @kbrosnan! I shared this with the team. @rpl commented that we may eventually want to sync storage.sync data. This isn't currently on our roadmap but we can keep it in mind for future planning!

**Comment by Gabriel85** [comment]
It's also used by uBlock-Origin, which is kind of ironic since that is one of the few extensions supposedly being fully supported!

But for sure it would be really useful having it to sync settings between 100% identical extensions across different platforms.

**Comment by bb010g** [comment]
Is this issue really wontfix, or is it still something you'd consider?

**Comment by soredake** [comment]
@kevincox can you reopen this?

**Comment by cadeyrn** [comment]
It shouldn't be needded to re-open since it's already filed as [BZ-1625257](https://bugzilla.mozilla.org/show_bug.cgi?id=1625257) on Bugzilla and issues tracking for Fenix will move to Bugzilla anyway.
