### ISSUE TITLE
[Bug] Can't rearrange my open tabs anymore

### ISSUE THREAD

**Issue by elensar** [mozilla-mobile/fenix#14217]
## Rearranging the open tabs is no longer possible
For me it was really one of the main points why I used Firefox instead of any other browser on my phone. Because I had a very good overview of all my open tabs and could rearrange them so I could more efficient. That's no longer possible and for me three steps back.

**Comment by cadeyrn** [comment]
Duplicate of #2487.

**Comment by mcarare** [comment]
@elensar Thank you for your report. The issue is already on our radar. Closing this as duplicate.
