### ISSUE TITLE
Open bookmarks in current tab

### ISSUE THREAD

**Issue by inwardmovement** [mozilla-mobile/fenix#14220]
From a UX perspective I think bookmarks should open in the current tab, not in a new one (let the user choose if they want to open a bookmark in a new tab). I think it was the case before the last update.

`Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0`

**Comment by s-ankur** [comment]
Take a look at https://github.com/mozilla-mobile/fenix/issues/13336
