### ISSUE TITLE
Open in new tab places tab before current tab

### ISSUE THREAD

**Issue by danhawkes** [mozilla-mobile/fenix#14223]
When I select "open in new tab" from a link, the tab is added to the left of the current tab in the swipe-between-tabs UI.

This is counterintuitive as I expect new tabs to open to the right of the current tab as in desktop firefox/left-to-right languages.

Please see here for demo video: https://mega.nz/file/uNhVHBTY#mEVxlIoXWFsGWU16-9pWqzCQUtwtzaDGEcg-2ffHH44

**Comment by Dunexus** [comment]
I agree, currently the order of tabs is counter-intuitive.

Quoting myself https://github.com/mozilla-mobile/fenix/issues/12108#issuecomment-669048249 :
> 
> 
> See #12861 and #13172.
> 
> From #12861, the choice was between :
> 
> > the newest tab in tab tray would be at botton
> > the most left tab in "swiping gesture" would be the oldest
> > The oldest tab in tab tray would be at top
> > the most right tab in "swiping gesture" would be the newest.
> > or
> > the newest tab in tab tray would be at top
> > the most left tab in "swiping gesture" would be the newest
> > The oldest tab in tab tray would be at botton
> > the most right tab in "swiping gesture" would be the oldest.
> 
> The latter has been chosen but it is really counter-intuitive to me.
> 
> Inside tab tray (vertical navigation) :
> 
>     * on fennec, the newest tab was at the bottom
> 
>     * inside the old vertical Android app switcher, the newest app was at the bottom
> 
> 
> For "swiping gesture" (horizontal navigation) :
> 
>     * on desktop, the newest tab is on the right
> 
>     * inside Android 10 horizontal app switcher, the newest app on the right too

Related to https://github.com/mozilla-mobile/fenix/issues/12861 and https://github.com/mozilla-mobile/fenix/issues/12108

**Comment by s-ankur** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/10986

**Comment by tomchiverton** [comment]
Also applies to the column list of tabs - the new tab is off screen high, effectively invisible, as there is no scroll bar.

**Comment by topotropic** [comment]
This will be addressed here https://github.com/mozilla-mobile/fenix/issues/13172#issuecomment-709506666 and here https://github.com/mozilla-mobile/fenix/issues/11376#issuecomment-709505058. Thanks!
