### ISSUE TITLE
Empty bar on bottom of some pages, corresponding to hidden address bar size

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#14229]
## Steps to reproduce

0) Switch address bar to top
1) Visit https://runalyze.com/activity/18228776
2) Click the wrench, "Edit activity"
3) Scroll down

### Expected behavior

Able to scroll down to the bottom of the page/pop up.

### Actual behavior

There is a white bar on the bottom of the page, obscuring the "Save" button. The bar is the size of the address bar, that was scrolled away/hidden from the top of the screen when scrolling the page down.

### Device information

* Android device: Huawei MediaPad M5 8
* Fenix version: Nightly
![Screenshot_20200826_131624_org mozilla fenix](https://user-images.githubusercontent.com/1104290/91324210-1b8b3100-e7c2-11ea-9980-818153076665.jpg)
![Screenshot_20200826_131753_org mozilla fenix](https://user-images.githubusercontent.com/1104290/91324223-1e862180-e7c2-11ea-9f28-8487c0dc7cfd.jpg)

**Comment by gcp** [comment]
Note: the second screenshot shows that by scrolling around, it's possible to get the "obscured" text partially back (i.e. to scroll a bit lower), while simultaneously still having the empty white area *and* the address bar visible.

**Comment by ekager** [comment]
Possible dupe of https://github.com/mozilla-mobile/fenix/issues/11389

**Comment by Mugurell** [comment]
Tried to reproduce this but I couldn't.
`https://runalyze.com/activity/18228776` is not available anymore.
At a quick glance I'm not seeing anything inherently wrong  but I'm not familiar with the website.
@gcp If this is still reproducing for you can you please post a small video detailing the issue?

**Comment by gcp** [comment]
Seems to have been fixed.
