### ISSUE TITLE
FNX-5020 ⁃ [Bug] Keyboard disappears when locking phone in Search screen

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#1422]
## Steps to reproduce
Tap URL bar to go to Search mode
Keyboard appears
Lock phone
Unlock phone
-> Keyboard has disappeared
Have to tap in the search box again to get keyboard back

### Expected behavior
Keyboard should remain after lock/unlock
It does remain on Fennec
Galaxy S7
Fenix 1.0.1914 68.0a1-20190403060632

**Comment by ekager** [comment]
Related bug: If you then resume the app (after pausing in SearchFragment) and press back, it exits SearchFragment, shows Home, and then exits the app. This is because we're overriding the back button when the keyboard is shown in SearchFragment.
