### ISSUE TITLE
Bookmarks organisation

### ISSUE THREAD

**Issue by George-C-Martin** [mozilla-mobile/fenix#14228]
### What is the user problem or growth opportunity you want to see solved?
The upgrade completely scrambled my bookmarks. Please can you make it possible to drag the folders into a different order and allow the contents to be sorted alphabetically? 

### How do you know that this problem exists today? Why is this important?
The upgrade has made this necessary. It will be a vast improvement and similar requests about bookmarks have seemed to be ignored in the past. 

### Who will benefit from it?
In my opinion everyone. It would bring Firefox Android more into line with other browsers in this respect.

**Comment by Dunexus** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/4348

**Comment by kbrosnan** [comment]
Closing in favor of #4348.
