### ISSUE TITLE
Private mode by default?

### ISSUE THREAD

**Issue by afonari** [mozilla-mobile/fenix#14236]
### What is the user problem or growth opportunity you want to see solved?
I want to have firefox focus experience, private browsing by default.

### How do you know that this problem exists today? Why is this important?
I haven't find a way to do it.

### Who will benefit from it?
Everyone who is currently using firefox focus/klar.

**Comment by kbrosnan** [comment]
How does the settings for private browsing `Add private browsing shortuct` and `Open links in a private tab` fail to meet those needs?

**Comment by afonari** [comment]
Yes, it works, I didn't know about Open links in a private tab, closing the case.
