### ISSUE TITLE
[Bug] Fenix does not restore last state (open tab) when restored, opens home

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14237]
I have seen a *lot* of feedback on this on Google Play and reddit, and I'm really surprised  that it isn't filed (maybe I am wrong and this is a dupe).

## Steps to reproduce

1. Go to any website
2. Switch to another tab
3. Come back to Fenix

### Expected behavior

The page opened in step 1 is shown

### Actual behavior

The home page is shown.

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/12062
