### ISSUE TITLE
[Bug] browser.urlbar.trimURLs doesn't work on Nightly

### ISSUE THREAD

**Issue by RockyTV** [mozilla-mobile/fenix#14238]
## Steps to reproduce
1. Go to `about:config`
2. Search for `trimurl`
3. Set `browser.urlbar.trimURLs` to **false**
4. Restart browser

### Expected behavior
The URLs should not be trimmed after this setting was set to false.

### Actual behavior
URLs are still being trimmed despite this setting being set to false.

### Device information

* Android device: Poco F1
* Fenix version: 200826 06:01 (Build #2015760179)

One would expect it to behave like the Desktop browser where it just highlights the domain and greys out any part not considered important by Google or Mozilla: path, subdomains and protocol, if the setting is set to false.

**Comment by kbrosnan** [comment]
`about:config` will not be used to control Fenix UI.

**Comment by RockyTV** [comment]
Are you even going to consider a setting to disable this forced behavior? Lots of users use websites that have different setups according to their subdomain, i.e., have diferent rules for `www` and the root domain. And then there's websites that are not setup correctly. I can give you an example of a website that is setup correctly for HTTPS but not HTTP and whenever you open it with Firefox it just redirects you to the non-HTTP version and you can't figure out what's wrong because the `trimURLs` setting is forced upon me.
