### ISSUE TITLE
Add slight animation when swiping to close a tab

### ISSUE THREAD

**Issue by dglttr** [mozilla-mobile/fenix#14233]
### What is the user problem or growth opportunity you want to see solved?
In #11324, a trash icon when swiping to close a tab was added. This helps to indicate what a swipe gesture will do. However, it does not indicate how long you have to swipe to actually initiate the closing of the tab.
The Outlook for Android mail app solves this the following way:
- When the user initiates a swipe on an email, an icon is shown (here, the action is archiving the mail):
![swipt_to_del_first_state](https://user-images.githubusercontent.com/46764284/91330636-02867e00-e7ca-11ea-87e1-ea7fc98a5d9f.png)

- When the swipe is long enough to initiate the action, the background color changes and the icon is enlarged, sending the signal to the user: "This action will happen if you lift your finger now".
![swipt_to_del](https://user-images.githubusercontent.com/46764284/91330790-2f3a9580-e7ca-11ea-8b9d-411927dad491.png)

### How do you know that this problem exists today? Why is this important?
Currently, the icon does not change when swiping on a tab.
This proposed change is important for two reasons:
1. It clearly shows the user when an action will happen, making the situation more intuitive and engaging.
2. It mirrors the behavior in other big apps like Outlook and thus meets user expectations.

### Who will benefit from it?
People using swipe to close tabs, especially those using it for the first time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5585)

**Comment by yoasif** [comment]
This is a really smart improvement idea, imo.

**Comment by amkcpu** [comment]
This could not only be applied to closing tabs, but also to deleting history items per swipe gesture and other gestures.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807058

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
