### ISSUE TITLE
Tabs Tray CFR Banner for Auto Close Tabs

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#14243]
Breakout of https://github.com/mozilla-mobile/fenix/issues/11582

UX mocks (this issue is for the banner in the tabs tray ONLY): 
https://app.abstract.com/projects/8afc4b50-7667-11e9-94ba-3558f8596822/branches/cfeee95f-b6fa-4579-842e-5b51f7dd4af2/commits/a3633820b169e4bc6ac37fe927c31d169dcd45d0/files/af6f466c-1a56-494d-ae53-20dd23f8a685/layers/2859F71C-CFB7-4049-8AB9-52B54EECC1FE?mode=build&selected=root-2859F71C-CFB7-4049-8AB9-52B54EECC1FE&sha=a3633820b169e4bc6ac37fe927c31d169dcd45d0

**Comment by liuche** [comment]
Checking, is this something that we're looking to uplift into 81, or will this be a large-enough change that we'll want to put it in 82? (if needs uplifting, add it to the uplifts column so we can remember to check on it)

**Comment by ekager** [comment]
Condition is: after you open more than 6 tabs or after deleting in a row 6 or more tabs

**Comment by AndiAJ** [comment]
Hi @ekager , I've just checked this matter on the latest **`Nightly Build 201008`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

✔️ If you open 6 or more tabs the Auto Close Tab CFR is properly displayed
► Video
![20201008-093049](https://user-images.githubusercontent.com/51314259/95424691-b04d8680-094b-11eb-846a-45ce8306fb63.gif)

❌ On the other hand, I couldn't trigger it after deleting 6 or more tabs in a row.
As far as I know, the CFR should be displayed again after 3 days. #15291 
Based on this, I've did the following:
1. Force close Fenix while having for E.g. 10 open tabs
2. Set the date to D+3
3. Re-open Fenix and start deleting 6 or more tabs

I've used this approach quite often, and worked like a charm. (Generate the **`Metrics`** ping using this trick and verified [#4118](https://github.com/mozilla-mobile/fenix/issues/4118#issuecomment-685460704) as well.)

Could you please review and advise? ☺️

**Comment by ekager** [comment]
We removed the delete criteria. Thanks!
