### ISSUE TITLE
[Bug] incomplete download

### ISSUE THREAD

**Issue by Karuhanga** [mozilla-mobile/fenix#14247]
## Steps to reproduce
Follow a link to a document.
(Followed a link to a pdf.)

### Expected behavior
File starts download, completes download and then displays toast with button to open file.

### Actual behavior
File starts download, displays toast with button to open file(before download is complete) and then completes download.

Tapping the open button on the toast before the download is complete opens a partial file and causes the downloaded file to be unusable when the download finally completes.

### Device information
* Android device: Android 10 on Nokia 3.1
* Fenix version: 68.10.0

**Comment by hwinnemoe** [comment]
Firefox 68 is no longer supported: https://www.mozilla.org/en-US/firefox/android/68.11.0/releasenotes/

**Comment by kbrosnan** [comment]
Unsupported version. Closing.
