### ISSUE TITLE
FNX-44 ⁃ Some site permissions should only work on secure websites

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1425]
Note to self: fill in details.

**Comment by kbrosnan** [comment]
We should get this for free from GeckoView. The documentation of the feature is https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts

**Comment by Amejia481** [comment]
It's is only working as expected for notification and location permissions.
[Demo](https://drive.google.com/file/d/1n1fYMDa9pjQpGUcxQcqm1qTAD23DE5CT/view?usp=sharing)

**Comment by sv-ohorvath** [comment]
> It's is only working as expected for notification and location permissions.
> [Demo](https://drive.google.com/file/d/1n1fYMDa9pjQpGUcxQcqm1qTAD23DE5CT/view?usp=sharing)

Same for me. @sarentz

**Comment by NotWoods** [comment]
Closing since the desired behaviour was verified by QA.
