### ISSUE TITLE
redesign the homepage to a tabbed design

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#14259]
### What is the user problem or growth opportunity you want to see solved?
Instead of dedicating just 2 rows for each item like top sites, bookmark, synced tab, collection etc why not implement a tabbed menu like Microsoft edge??this way all these items can get the full screen and user can add more items in a single view 

### How do you know that this problem exists today? Why is this important?
Currently top site is limited to just 2 rows with max 8 items and adding another step to access items on 2nd slide. 
Other items added in future will face the same issue.. Limited view! 

### Who will benefit from it?
All users

PFB the screenshot from edge 
![Screenshot_20200827-072951695 (1)](https://user-images.githubusercontent.com/58127841/91375111-6c893c80-e837-11ea-8ab6-46bb3c3dc28b.jpg)

![Screenshot_20200827-073032697](https://user-images.githubusercontent.com/58127841/91375036-3cda3480-e837-11ea-8693-ee3f6ea1fcb9.jpg)
![Screenshot_20200827-073024171](https://user-images.githubusercontent.com/58127841/91375041-3ea3f800-e837-11ea-9890-c1e54e41a2b6.jpg)
![Screenshot_20200827-073015482](https://user-images.githubusercontent.com/58127841/91375042-406dbb80-e837-11ea-9618-27d8a338d1d1.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5624)

**Comment by s-ankur** [comment]
This is actually an excellent idea. Since the synced tab will be added as another tab in tab tray, it would be wonderful if collections can also be added there. Moreover, since it is in a tab which does not bother non users, it would probably remove the need for "disable collections" option

**Comment by sheikh-azharuddin** [comment]
> This is actually an excellent idea. Since the synced tab will be added as another tab in tab tray, it would be wonderful if collections can also be added there. Moreover, since it is in a tab which does not bother non users, it would probably remove the need for "disable collections" option

Actually i am not requesting to add collection to tab tray...The home screen can contain 5 icons like edge as per as 1st screenshot... On clicking anyone it will open a new tab style menu like Microsoft edge... 

This way collection can be utilized fully... And top site content can be dedicated to frequently accessed site only 

So homepage will have below items in below order---
1.Firefox logo
2.Top sites(frequently visited sites) 
3. 5 icons like Ms edge (1st screenshot)-- fav, history, bookmarks, collection, synced tabs
4. Top articles like desktop version or maybe news( Google news for you)

**Comment by yoasif** [comment]
@s-ankur see https://github.com/mozilla-mobile/fenix/issues/10372

**Comment by bigConifer** [comment]
@sheikh-azharuddin can you please change the title of this issue to clarify that it is about redesigning the homepage to a **tabbed design**.

Imprecise titles are confusing as there is a number of other requests to change the homescreen UI/UX.

**Comment by litLizard69** [comment]
Firefox on Android should definitely redesign the startpage. As well as that more interesting wallpapers would be great as well (like Brave fetches Wallpapers from photographers) but that's a different topic.
