### ISSUE TITLE
[Bug] Unable to select text on some sites

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#14250]
## Steps to reproduce
Go to a youtube video and try to select text of either the video title or one of the comments.

### Expected behavior
The text is selected.

### Actual behavior
Nothing happens.

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 200826 06:01 (Build #2015760179)
AC: 56.0.20200825130329, 6fbe53de9
GV: 81.0a1-20200820093209
AS: 61.0.12

**Comment by mobd** [comment]
I'm not sure if I should have put this under  #12416 but that issue seems to have been reopened by mistake.

I also found that it happens on reddit too, if you open a post and try to select the title. It never happens on any "plain" text though, so it might have to do with conflicting event handlers or something like that

**Comment by s-ankur** [comment]
Related  #13438

**Comment by danpeig** [comment]
Same problem.

**Comment by ekager** [comment]
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/11151 
Please open a new issue if you find a new site that isn't Youtube
