### ISSUE TITLE
Improve usability of pinned site icons

### ISSUE THREAD

**Issue by pathbreak** [mozilla-mobile/fenix#14264]
### What is the user problem or growth opportunity you want to see solved?

Pinned sites (or "Top sites") have the following usability problems:

**Problem 1**: Firefox uses website favicon image as icon image and website title as icon caption.
However, many websites don't provide descriptive titles and memorable favicon images. A user cannot tell the website an icon refers to if its title is something generic like "Latest News" (see attached screenshot for examples).

**Suggested Improvements:** Use website domain as caption or enable user to edit icon captions.

**Problem 2**: Icon size and caption font size are too small. Should be customizable.
Previous Firefox versions showed larger icons with larger font sizes. 
Now both are too small for comfortable usability and readability. 
They cannot be increased from Customization or Accessibility pages.

**Suggested Improvements:** Enable user to set icon size and icon font size.

**Problem 3**: Caption text is limited to a single row of around 8-10 characters and then cropped with ellipses.
A website title like "News : Latest Breaking" is cropped to "News : La..." which makes it difficult to identify the website or page. 
**Suggested Improvements:** Show 2-3 rows of text. Enable user to customize the text rows or edit the caption.

### How do you know that this problem exists today? Why is this important?

See attached screenshot. 
The enhancements will improve app usability.

### Who will benefit from it?

Users who use the pinned sites feature. Users with vision or other accessibility problems.

### Screenshot:

![Screenshot_2020-08-27-09-25-18](https://user-images.githubusercontent.com/5163416/91385194-fa702200-e84d-11ea-9745-3d7fdd666bc1.png)

**Comment by kbrosnan** [comment]
Please limit reports to one issue. This contains several, each problem should be an individual report. 

* #9548
* #13765
