### ISSUE TITLE
[Bug] When you lock your device while the tab tray is open, the tray reopens when you unlock it

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14269]
## Steps to reproduce
1. Open tab tray
2. Lock device
3. Unlock device

### Expected behavior
Tab tray would stay open

### Actual behavior
Tab tray reopens when you unlock your device

### Device information

* Android device: ?
* Fenix version: Nightly 200826

**Comment by s-ankur** [comment]
Cant reproduce on latest nightly (Asus Zenfone LineageOS 16)

**Comment by ekager** [comment]
Thanks for the update! Closing
