### ISSUE TITLE
[Bug] Android Navigation Bar buttons become invisible in Light theme

### ISSUE THREAD

**Issue by pathbreak** [mozilla-mobile/fenix#14262]
## Steps to reproduce

1. Settings > Customize > Theme > Select "Light"
2. Firefox makes the system navigation bar background white.
3. Its white buttons go invisible.

### Expected behavior

Navigation bar buttons should be visible. Preferably, navigation bar's colors should not be modified by any app.

### Actual behavior

Navigation bar buttons go invisible. Forced to choose Dark theme just so they are visible.

### Device information

* Android device: Huawei Honor 6x Android version 6.0 EMUI 4.1
* Fenix version: 79.0.5

### Screenshots:
Dark theme:
![Screenshot_2020-08-27-09-25-18](https://user-images.githubusercontent.com/5163416/91383186-23da7f00-e849-11ea-8c59-76eefcd846cb.png)

Light theme:
![Screenshot_2020-08-27-09-24-10](https://user-images.githubusercontent.com/5163416/91383190-25a44280-e849-11ea-9e56-a9bf7f152920.png)

**Comment by liuche** [comment]
Already fixed in Firefox 80 #12058
