### ISSUE TITLE
[Bug] Missing tooltip on private browsing button on homescreen

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14267]
## Steps to reproduce
1. tap and hold on private browsing button

### Expected behavior
Tooltip would appear that says "Private browsing"

### Actual behavior
Tooltip doesn't appear

### Device information

* Android device: ?
* Fenix version: Nightly 200826

**Comment by ekager** [comment]
By tooltip do you mean a content description for a11y or...?

**Comment by Poopooracoocoo** [comment]
I meant an actual tooltip. Like when you tap and hold on most buttons on Android, if that makes sense.

**Comment by Poopooracoocoo** [comment]
commenting just to reopen. idk if this was added or not bc i dont actually use firefox on my phone
