### ISSUE TITLE
FNX3-15555 ⁃ history: multi select with short press on favicon

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1427]
In the history view you can long press on a row to enable the multi select mode. That's really great and it would be even more great if I could enable the multi select mode with a short press on the favicon (or favicon placeholder at the moment).

You can see the requested behaviour in the Google Mail app. I use the multi selection in the Google Mail app a lot and it would be nice if I could use the same usage pattern in Fenix since it's a very similar use case (I want to delete a few mails / history items at the same time).

**Comment by sblatz** [comment]
This is pretty small engineering effort if we decide to move forward with it.

**Comment by lime124** [comment]
@topotropic this seems totally fine - do you see any potential conflicts or pitfalls?

**Comment by topotropic** [comment]
That's fine.

**Comment by ekager** [comment]
Adding the good first issue label :)
Whomever picks this up will have to add a click listener to the favicon view here that will enter edit mode like long pressing currently does. 
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt#L41

**Comment by cadeyrn** [comment]
It's not my "first issue" but since I want to see this enhancement in Fenix I created a PR. 😃

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on a locally build from 8/5 master with LG G7 Fit (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).
