### ISSUE TITLE
[Bug] Some sites don't display the ETP shield icon

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#14271]
## Steps to reproduce
1. Open several tabs.
2. Switch tabs by swiping left/right on the navigation bar.
3. Observe the ETP shield icon on each tab.

### Expected behavior
All tabs have the ETP shield icon displayed.

### Actual behavior
Not all tabs the ETP shield icon are displayed.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab S6 (Android 9)
* Fenix version: 8/27 Nightly build
* Tapping on the empty place triggers the ETP info panel.
* Refreshing the page doesn't fix the issue.

<img src="https://user-images.githubusercontent.com/40694158/91412917-12967000-e853-11ea-8bb0-9a502747135e.gif" width="300" height="550" />

**Comment by person808** [comment]
I've got another way to reproduce this using the Search By Image addon.

1. Use Search By Image addon and select an image to search with.
2. Observe the invisible etp shield on the Google search results page.

ETP was disabled on the results page and attempting to turn it on did not work.

**Comment by TrianguloY** [comment]
A reliable way to trigger this bug for me is:

Open one page (for example this issue). Pressing the shield icon shows the protecting is active.
Open the exact same page on a new tab (faster way is to copy url, new tab, fill from clipboard). Pressing the shield icon shows the protection is disabled (bug!)
Swipe right to the original tab. Pressing the shield icon shows the protecting is active.
Swipe left to the duplicated app. The shield icon is gone, and pressing the space show the protection is disabled.

**Comment by softvision-miralobontiu** [comment]
I'll close this as a duplicate of #12848.
