### ISSUE TITLE
[Bug] File downloading issues on uploaded.net

### ISSUE THREAD

**Issue by osoyoguiconbubu** [mozilla-mobile/fenix#14273]
## Steps to reproduce
Downloads from http://uploaded.net/file/ilelap1b  and use of the reCAPTCHA that is included and is essential to download.

### Expected behavior
In the previous version (68.11.0), it could almost always be downloaded, although using reCAPTCHA, many times it failed

### Actual behavior
In the new version (79.0.5), nothing can be downloaded from "uploaded.net", and using reCAPTCHA, it keeps crashing: mark the images and they disappear.

### Device information
Motorola One Vision

* Android device: Android 10 (android one)
* Fenix version: Firefox (Android)

**Comment by osoyoguiconbubu** [comment]
In the latest version: 80.1.3, the problem remains.

**Comment by Amejia481** [comment]
@osoyoguiconbubu  do you have an link that we can use to test? 


> it keeps crashing: mark the images and they disappear.

Could you go to the 3 dotted menu (:) -> Settings -> About Firefox -> Crashes and share the last entry?

**Comment by osoyoguiconbubu** [comment]
Good afternoon,I sense from your name and surname that you can use the Spanish language, is that right?If you want, we can use it since I live in Spain.Regarding the problem you mention, in the latest version, it has disappeared, this no longer happens, but it still does not download anything hosted on uploaded.net. Version 68.11.0, download from uploaded.net without problems.An example link: http://uploaded.net/file/dm9l0trfRegards El 21 sept. 2020 15:41, Arturo Mejia <notifications@github.com> escribió:
@osoyoguiconbubu  do you have an link that we can use to test?

it keeps crashing: mark the images and they disappear.

Could you go to the 3 dotted menu (:) -> Settings -> About Firefox -> Crashes and share the last entry?

**Comment by Amejia481** [comment]
Hola 👋  thanks for the information. I'm a native Spanish speaker originally from the Dominican Republic 🏖️  and now living in Toronto, Canada 🍁  :). I prefer to keep the conversation in English as this way everybody could contribute and get info about the issue.

**Comment by osoyoguiconbubu** [comment]
Good afternoon, 
I have received an email stating that the uploaded.net downloads are working.

I just tried it with another link and it still does not work, I always get: "download failed".

The link is: http://uploaded.net/file/ilelap1b

**Comment by Amejia481** [comment]
We did some improvement to downloads in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). I was able to download the file there, would you mind trying on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to see if it's fixed for you? Hopefully it will work for you too :)

I will also ask the QA team to test a they have a wide range of devices.

![image](https://user-images.githubusercontent.com/773158/97440977-8f4ed480-18fe-11eb-963b-a7fd62fef554.png)

**Comment by AndiAJ** [comment]
Hi @Amejia481, checked both http://uploaded.net/file/ilelap1b & http://uploaded.net/file/dm9l0trf and they **work properly** on the latest **`Nightly Build 201029`** using the following devices:
• Google Pixel 3a (Android 11)
• Pixel 3 (Android 11)
• OnePlus 6T (Android 9)
• Motorola Moto G6 (Android 8)
• Xiaomi mi4i (Android 5.0.2)

**Comment by osoyoguiconbubu** [comment]
Thanks for fixing it, but ...
I don't use the Nightly version
When will it be fixed for the stable version?

**Comment by Amejia481** [comment]
> > Hi @Amejia481, checked both http://uploaded.net/file/ilelap1b & http://uploaded.net/file/dm9l0trf and they **work properly** on the latest **`Nightly Build 201029`** using the following devices:
> > • Google Pixel 3a (Android 11)
> > • Pixel 3 (Android 11)
> > • OnePlus 6T (Android 9)
> > • Motorola Moto G6 (Android 8)
> > • Xiaomi mi4i (Android 5.0.2)
> 
> Thanks for fixing it, but ...
> I don't use the Nightly version
> When will it be fixed for the stable version?

You could take a look a the release calendar [here](https://wiki.mozilla.org/Release_Management/Calendar)
