### ISSUE TITLE
Gecko resizes when opening the toolbar

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#14279]
## Steps to reproduce
- Load a webpage
- Tap on the toolbar

### Expected behavior
- No resize happens, content is just hidden

### Actual behavior
- The page resizes, as you can see in the screenshots of this profile: https://share.firefox.dev/2D8CvCE.
This had been fixed in https://github.com/mozilla-mobile/fenix/issues/8399, but the new search experience regressed it again.

### Device information

* Android device: Samsung Galaxy A50
* Fenix version: Nightly 200827 07:01 (Build #2015760379)
AC: 57.0.20200826190111, c93fc20af
GV: 81.0a1-20200820093209
AS: 61.0.13

**Comment by abodea** [comment]
Hi, @mcomella is this bug for the QA or it needs to be verified by the performance team?

**Comment by mcomella** [comment]
We filed #15142 to verify this solution from the performance team.

**Comment by miDeb** [comment]
I noticed that a resize still happens the moment the keyboard is dismissed by tapping somewhere on the webpage. It does not happen when using the back button.
See this screen recording: https://streamable.com/1q66dm
Profile: https://share.firefox.dev/3kE5z51

**Comment by mcomella** [comment]
In both the original profile and the profile above, I can confirm the resize happens via:
- the screenshots
- the `resize` `DOMEvent` in the marker chart (example: https://share.firefox.dev/31ahzUi)

On my GS5 + latest nightly, I was able to reproduce the issue with the STR, described above:
- Open a web page 
- Tap the toolbar
- Tap the web page to dismiss the keyboard (I wasn't able to reproduce with the back button)

https://share.firefox.dev/31aU6T2

This seems like a less serious case than the initial bug filing so I'll file a new issue for this.

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/15923 for the follow-up. Closing this issue as fixed.

Thanks for the good eye and thorough bug reports miDeb!

**Comment by mcomella** [comment]
@abodea I added the qa:verified label to say I verified it – am I supposed to do that or is that label for your team only?
