### ISSUE TITLE
[Bug] Videos with playbackRate > 1 have robotic audio

### ISSUE THREAD

**Issue by mrmonday** [mozilla-mobile/fenix#14270]
## Steps to reproduce

1. Go to YouTube, select any video with speech
2. Tap the settings cog, set the play back speed to anything greater than 1 (1.25x, 2x, etc)
3. Speech will sound robotic/echoy

### Expected behavior

Speech should sound fast, not robotic.

### Actual behavior

Speech sounds robotic/echoy.

### Device information

* Android device: Samsung Galaxy S9+ (SM-G965F)
* Fenix version: 79.0.5 (Build #2015758619)
  AC: 48.0.15, 8755ac0cd
  GV: 79.0.1-20200813192915
  AS: 61.0.10

This worked correctly with the previous (non-Fenix) version of Firefox for Android.

**Comment by Dunexus** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8456

**Comment by AndiAJ** [comment]
Closing in favor of #8456
