### ISSUE TITLE
[Bug] Firefox causes the whole os to crash and restart on Xperia Tablet Z LTE (sgp321) with lineageos 16

### ISSUE THREAD

**Issue by barfin** [mozilla-mobile/fenix#14276]
## Steps to reproduce
1-launch firefox
2-android os restarts

### Expected behavior
It should launch!

### Actual behavior
it causes the whole android os to restart

* Android device: Xperia Tablet Z LTE with LineageOS 16 (https://forum.xda-developers.com/xperia-tablet-z/orig-development/rom-lineageos-16-0-t3924942)
* Fenix version: stable 79.0.5

It was working perfectly well with firefox 68.11.0

**Comment by hwinnemoe** [comment]
Since there are several reports in the linked forum thread that have the same issue, maybe this patch https://github.com/mozilla-mobile/fenix/issues/5663#issuecomment-671612828 has not been included by the custom ROM creator?

**Comment by barfin** [comment]
> 
> 
> According to https://forum.xda-developers.com/showpost.php?p=83327891&postcount=155, the required LineageOS patch ([#5663 (comment)](https://github.com/mozilla-mobile/fenix/issues/5663#issuecomment-671612828)) has not been included for this custom ROM.

yes looks like that custom kernel did the trick, i'll track this at xda thread and not here since it's a rom bug
