### ISSUE TITLE
[Bug] Frequent selection test failures like deleteMultipleSelectionTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#14277]
Log: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8647691921197536714

There are frequent fenix ui-test failures in which selection of list items is involved.

@NotWoods  Regression from https://github.com/mozilla-mobile/fenix/issues/8765 ?

**Comment by NotWoods** [comment]
The failures seem to be unrelated as I haven't migrated history/bookmarks yet.

**Comment by sv-ohorvath** [comment]
settingsAddonsItemsTest was fixed in https://github.com/mozilla-mobile/fenix/issues/13218
This will cover deleteMultipleSelectionTest. The test fails because the second webpage is not yet available in the history menu when it tries to select it.
