### ISSUE TITLE
Poor video and scrolling performance on YouTube (including app freezing)

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14272]
## Steps to reproduce
A slight load delay is seen{compared to Chrome 85(latest), Firefox 68.11.0,  Firefox Focus(latest), Opera(latest), Brave(latest)} on viewing videos on YouTube. For example, I visit https://m.youtube.com from the address bar, Youtube loads properly, however scrolling delay increases by a bit. Next, when a video is clicked to be played, a verification (I'm not a robot) has to be passed, which, for a small phone (480x800), the [verify] placeholder swoops below the screen, This issue was absent on all of the above mentioned browsers. Video playback is smooth for a couple of minutes, however, videos after ~ 7 minutes(first video) starts to show signs of delay and even app freeze. The 7 minute mark was apparent for first video playback, however, trying out a second video shows signs of delay under 2 or 3 minutes, and leading to app crash. This was tested with both 144p videos and 480p videos. Also, with extensions(uBlock origin + Dark Reader), the app froze quicker than before. 

## Thoughts
Have tested it on the latest versions of Firefox Focus, Chrome, Opera, Edge, Brave and also Firefox 68.11.0 and faced no issues. I also had uBlock and Dark reader enabled on Firefox 68.11.0. Although I'm not an expert, but I think this could be a multiprocess threading issue, idk. Also, tested this on both Android 9 2GB and Android lollipop 512 MB Ram. The issue was on only 512 MB RAM phone. 

**These issues were found on Firefox Nightly(latest), Firefox Beta(latest), Firefox 79.0.5**

**None of these issues were found on Android 9 2GB Ram, although a bit of delay was apparent**

### Expected behavior
Smooth video playback

### Actual behavior
App freeze for longer videos and issues with properly solving recaptcha since the verify/next/skip placeholder goes below the screen view.

### Device information
Ram: 512MB, CPU: 1.3 Ghz quad core, resolution: 480x800

* Android device: Lollipop 5.1.1
* Fenix version: 79.0.5

**Comment by s-ankur** [comment]
#14111 may be relevant

**Comment by mcomella** [comment]
This is platform issue so we're tracking upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=1662910

**Comment by samiuljoy** [comment]
The latest Fenix release 79.0.5 (Build #2015758617) has very good YouTube performance. Quite snappy might I add.
