### ISSUE TITLE
[Bug] Crash java.util.ConcurrentModificationException: at java.util.ArrayList$Itr.next(ArrayList.java)

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14281]
## Steps to reproduce
I don't have exact STR's for this crash at the moment however i encountered while testing sync and adding a new tab on desktop, sync it on mobile to check results in tabs tray, i've also opened the new tab (the one from desktop), on mobile than closed it, triggered undo the same tab and than signing out.
Retried this a couple of times but wasn't able to reproduce it again.
### Device information

* Android device: Samsung Galaxy S9 (Android 8), Google Pixel 3XL (Android 9)
* Fenix version: Nightly 8/27

**<details closed><summary>Java stack trace</summary>**
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at mozilla.components.lib.crash.service.SentryService.report(SentryService.kt:29)
	at mozilla.components.lib.crash.CrashReporter$submitCaughtException$1.invokeSuspend(CrashReporter.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
</details>

Samsung Galaxy S9 (Android 8) crash link: https://crash-stats.mozilla.org/report/index/62db6b77-7400-49b4-9b99-03afc0200827#tab-details

Google Pixel 3XL (Android 9) crash link: https://crash-stats.mozilla.org/report/index/09ed592f-d8cb-479c-94d0-045610200827

**Note:**
- I've experienced the crash while testing #12287

**Comment by jonalmeida** [comment]
@rocketsroger this looks like a crash in the crash reporter from the trace. Would this make sense to you? I'm a little lost here otherwise.

**Comment by rocketsroger** [comment]
> @rocketsroger this looks like a crash in the crash reporter from the trace. Would this make sense to you? I'm a little lost here otherwise.

I'll investigate.

**Comment by rocketsroger** [comment]
@Diana-Rus this should be fixed in latest nightly.   Please confirm.  Thanks,

**Comment by Diana-Rus** [comment]
Hi, i was unable to reproduce the issue on Nightly 9/7 with:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)

@jonalmeida , @rocketsroger - However without specific STR maybe the crash should be monitor a bit of time until closing this issue?

I'll remove the qa-needed label until further information is provided.

**Comment by rocketsroger** [comment]
Search in Nightly crashes did not result in any recent crash related to this issue.  Closing since this is fixed in Nightly.
