### ISSUE TITLE
[Bug] Extend the new search experience to the search widget

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#14280]
## Steps to reproduce
1. Add the Fenix Nightly search widget;
2. Tap the search widget;
3. Observe the new opened tab;
### Expected behavior
The new opened tab is displayed with the new search experience.
### Actual behavior
The new opened tab is not displayed with the new search experience.
### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 200827 07:01 (Build #2015760377) GV 81.0a1 from 8/27

**Comment by hwinnemoe** [comment]
Also mentioned here https://github.com/mozilla-mobile/fenix/issues/13052#issuecomment-681041844

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 81.1.0-beta.1 (Build #2015761489) GV 81.0 from 9/2 with Samsung Galaxy Tab S3 (Android 8).

**Comment by s-ankur** [comment]
This should also trigger for the Private Browsing shortcut as mentioned in #14743

**Comment by eliserichards** [comment]
For QA: this is all behind the scenes changes, so just test out search and see if you notice any breaks :)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200925 06:01 GV 83.0a1 from 9/25 with Pixel 2 (Android 9).
One new related issue: https://github.com/mozilla-mobile/fenix/issues/15418

**Comment by s-ankur** [comment]
@eliserichards, while we are on the subject, is it also possible to extend new search to the assist function i.e. https://github.com/mozilla-mobile/fenix/issues/3722?
