### ISSUE TITLE
[Bug] The search suggestions results are overlapped by the "Allow search suggestions in private sessions?" prompt

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#14283]
## Steps to reproduce
1. Launch Fenix Nightly;
2. Go to Private browsing;
3. Start typing in the URL bar;
4. Observe the search suggestions;
### Expected behavior
The search suggestions are visible and are not overlapped by the "Allow search suggestions in private sessions?" prompt.
### Actual behavior
The search suggestions results are overlapped by the "Allow search suggestions in private sessions?" prompt.
### Notes:
![20200827_132056](https://user-images.githubusercontent.com/48799384/91434199-218a1c00-e86d-11ea-81bb-0cf7dd861247.gif)

### Device information

* Android device: Pixel 2 (Android 9);
* Fenix version: Nightly 200827 07:01 (Build #2015760377) GV 81.0a1 from 8/27

**Comment by osanshouo** [comment]
I encountered the same bug on Pixel 4 (Android 10) and Nightly 200827 07:01 (Build #2015760379) GV 81.0a1, when I updated Nightly for the first time in a week.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 81.1.0-beta.1 (Build #2015761489) GV 81.0 from 9/2 with Samsung Galaxy Tab S3 (Android 8).

**Comment by ekager** [comment]
This visual issue is fairly bad (and we're also showing private suggestions while onboarding private suggestions) and I think we should get a fix in for release.

It looks like the issue is in our logic for `shouldShowAwesomebar` but I'm not sure what the desired behavior here is. Do we want to show the onboarding with it's own background without the awesomebar? I am not really familiar with the new search experience so I'd appreciate someone who has been working on it taking a look!

**Comment by ekager** [comment]
Also it looks like https://github.com/mozilla-mobile/fenix/pull/14293 was not the right fix so we might want to revert those changes if they're not doing what we thought they were cc @boek

**Comment by liuche** [comment]
Adding this to the sourpatch sprint since we should try to fix this regression on the new search feature.

**Comment by osanshouo** [comment]
I confirmed this bug is resolved in Nightly 200912 06:01 (Build #2015763443) GV: 82.0a1 with Pixel 4 (Android 10). Thank you very much.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200914 06:05 (Build #2015763827) GV 82.0a1 from 9/14 with Samsung Galaxy Tab S3 (Android 8) and Pixel 2 (Android 9).
