### ISSUE TITLE
[Bug]Firefox remains stuck in landscape view after opening a video in full screen mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#14284]
## Steps to reproduce
1. Open a video from Youtube in full screen mode 
2. Exit to the devices home screen
3. Resume Firefox

### Expected behavior
After resume being able to use Firefox in portrait view

### Actual behavior
Remains stuck in landscape view

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly 200827

### Notes
► Video
![20200827-140936](https://user-images.githubusercontent.com/51314259/91452025-c82ee680-e886-11ea-92c5-e50e178903d5.gif)

**Comment by s-ankur** [comment]
Related  #14108

**Comment by Webbeh** [comment]
Note that relaunching a video in fullscreen and disabling fullscreen on that newly launched video brings back a functional rotation.

**Comment by BarbecueSilver** [comment]
Happens also if you:

 1.  Open a video from Youtube in full screen mode
 2. Switch off the phone
3. Switch it on again
4. Resume Firefox

**Comment by eliserichards** [comment]
This needs to be re-tested now that we have our new Media session work merged from AC.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201210`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by Webbeh** [comment]
Seems to be fixed for me as well.

**Comment by AndiAJ** [comment]
Still reproducible on Beta 85.0.0-beta.1 using a OnePlus A3 (Android 6.0.1)

**Comment by amedyne** [comment]
@eliserichards can you check this one and see what else needs to be done? Thanks!

**Comment by alexandergitter** [comment]
This is still broken for me on a OnePlus 8, Android 11 (Oxygen OS 11.0.2.2.IN21BA).
Nightly 210113 17:01 (Build #2015787147)

**Comment by AndiAJ** [comment]
Still reproducible on 85.1.0-rc.1 using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Still reproducible on 85.1.3 using a OnePlus A3 (Android 6.0.1)
