### ISSUE TITLE
[Bug] Extend the new search experience to the case of creating a new tab when long pressing the tab counter

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#14282]
## Steps to reproduce
1. Launch Fenix Nightly;
2. Open a tab from Tabs tray;
3. Long tap the tab counter;
4. Tap "New tab"/"New private tab";
### Expected behavior
The new tab opens with the new search experience.
### Actual behavior
The new tab opens without the new search experience.
### Device information

* Android device: Pixel 2 (Android 9);
* Fenix version: Nightly 200827 07:01 (Build #2015760377) GV 81.0a1 from 8/27

**Comment by hwinnemoe** [comment]
Also mentioned here https://github.com/mozilla-mobile/fenix/issues/13052#issuecomment-681041844

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 81.1.0-beta.1 (Build #2015761489) GV 81.0 from 9/2 with Samsung Galaxy Tab S3 (Android 8).
