### ISSUE TITLE
[webcontent] Broken pitch-zoom in Leaflet maps

### ISSUE THREAD

**Issue by Yarjk32** [mozilla-mobile/fenix#14285]
## Site with issue and any steps to reproduce
www.openstreetmap.org or https://leafletjs.com/examples/quick-start/example.html or other sites with Leaflet map.
1. Place two fingers on a screen at the same time.
2. Pitch or expand them.
### Expected behavior
If two fingers are placed on a screen at the same time, one can do pinch-zoom.
### Actual behavior
If two fingers are placed on a screen at the same time, no pinch-zoom is possible.
### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
Yes: 
![bug](https://imgur.com/download/B2qJvOK/)
### Can you reproduce in Chrome (or other non-Mozilla browser)?

No:
![normal](https://imgur.com/download/4twTTjb/)
### Device information

Device model | Android version | Fenix version
------------ | ------------- | -------------
Meizu M3s | Android 5.1 (Flyme 6.3.2.0G) | Firefox Daylight 81.1.1 (Build #2015764547)
Motorola Power | Android 10 | Firefox for Android 79.0.5

**Comment by theres-waldo** [comment]
Based on the discussion in [bug 1666188](https://bugzilla.mozilla.org/show_bug.cgi?id=1666188), this is a GeckoView issue that was recently fixed in [bug 1648491](https://bugzilla.mozilla.org/show_bug.cgi?id=1648491).

**Comment by Yarjk32** [comment]
I had installed Firefox Daylight 82.1.1 and made sure that this issue is fixed.
