### ISSUE TITLE
Can't select text on reddit posts

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#14295]
## Steps to reproduce

1) Visit a post on reddit.
2) Try to select text in the original post (not the comments!) by long pressing.

### Expected behavior

1) Text selection markers appear.

### Actual behavior

1) Nothing happens.

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Included in https://github.com/mozilla-mobile/fenix/issues/14250?

**Comment by gcp** [comment]
Probably!

**Comment by s-ankur** [comment]
I think you can close the issue then
