### ISSUE TITLE
[Bug] Trying to share a page leads to crash 95% of the time

### ISSUE THREAD

**Issue by liar666** [mozilla-mobile/fenix#14296]
## Steps to reproduce

- Open several tabs (I generally have between 50 & 100 opened tabs).
- Click the Share button
- Select any destination app

### Expected behavior

- The destination app should open and propose to do something with the URL that was opened in FF

### Actual behavior

- App totally Crashes and proposes to send info to Mozilla & restart.

### Device information

* Android device: Doogee N10, Android 8.1
* Fenix version: 79.0.5
* Installed Addons: uBloc Origin, Privacy Possum

**Comment by hwinnemoe** [comment]
Can you please add the links to your crash reports? You can find the crashes via _Settings_, _About Firefox_, _Crashes_. Long-press on the Sentry and/or Socorro links and post them here.
