### ISSUE TITLE
[Bug] Completely blank tab (black in color)

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14297]
## Steps to reproduce
Unsure, just opened a GitHub link in another tab

### Expected behavior
Normal tab
### Actual behavior
Completely black tab
Refreshing does nothing
Reentering url does nothing
Close tab -> undo does nothing

### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly 200827 07:01 (Build #2015760379)
AC: 57.0.20200826190111, c93fc20af
GV: 81.0a1-20200820093209
AS: 61.0.13

I'm keeping the tab open so if I you need any more information you can tell me

**Comment by s-ankur** [comment]
Still blank after force close and reopen

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/14459
