### ISSUE TITLE
Synced tabs claims Firefox Account is not active

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#14294]
- [ ] https://github.com/mozilla/application-services/issues/3373

## Steps to reproduce

1) Have a Firefox account set up.
2) Open menu->Synced Tabs

### Expected behavior

1) See open tabs on other instances.

### Actual behavior

1) Message "Connect with a Firefox Account"

See screenshots.
![Screenshot_20200826-175806](https://user-images.githubusercontent.com/1104290/91461425-45f3f180-e889-11ea-9360-3f9e78e97e8d.png)
![Screenshot_20200826-175819](https://user-images.githubusercontent.com/1104290/91461440-48eee200-e889-11ea-950f-639da1b02f2a.png)

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly

**Comment by jonalmeida** [comment]
Posting in this issue too: this requires work from mozilla/application-services#3373 but we may be able to hide this when we move to a separate tab.

**Comment by jonalmeida** [comment]
This should be fixed now.
