### ISSUE TITLE
FNX-5023 ⁃ Update Site permissions page for MVP

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#1429]
![image](https://user-images.githubusercontent.com/773158/55648920-914ac300-57af-11e9-810a-6375d62a242b.png)

**Comment by mheubusch** [comment]
@Amejia481 we are working on updates to the design files, but wanted to note that we should not build the follwing items into the interface: autoplay, popups, DRM

**Comment by Amejia481** [comment]
Thanks @mheubusch  👍
