### ISSUE TITLE
[Bug] Decremented open tabs value after deleting a tab while using the switch gesture 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#14290]
## Prerequisites
Have 3 open tabs

## Steps to reproduce
1. Open the Tabs Tray and swipe delete one of the tabs
2. Dismiss the Tabs Tray
3. Using the swipe gesture switch through the remaining open tabs
4. Check value displayed in the Tabs counter after switching

### Expected behavior
Display the correct value of open tabs in the tabs counter

### Actual behavior
Displays the value before deletion for a couple of seconds after switching .
In this case displays 3 for a couple of seconds even if I have only 2 open tabs.

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly 200827

### Notes
► Video
![20200827-164049](https://user-images.githubusercontent.com/51314259/91451583-3de68280-e886-11ea-8690-4c882f73b4e0.gif)

**Comment by softvision-miralobontiu** [comment]
I reproduced this issue on the latest Nightly build from 10/8 with HTC 10 (Android 8) without deleting any of the opened tabs. I had 7 tabs opened, swiping left/right displayed 6, then 7 tabs on the tabs counter, very briefly:

<img src="https://user-images.githubusercontent.com/40694158/95439487-5e632b80-0960-11eb-9ef8-50b743bb0852.gif" width="300" height="550" />

**Comment by softvision-miralobontiu** [comment]
Still reproducible on RC 84.1.3, Beta 85.0.0beta.5, and 1/6 Nightly build with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by softvision-miralobontiu** [comment]
Reproducible on Beta 86.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by softvision-miralobontiu** [comment]
Reproducible on Beta 86.0.0-beta.5 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by lobontiumira** [comment]
Reproducible with Beta 88.0.0-beta.1 with a x86 emulator Nexus 9 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.4 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on 90.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on 90.1.3 RC build with Sony Xperia Z5 PRemium (Android 7.1.1).

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the Samsung Galaxy Tab A6 (Android 5.1.1) device on Beta 94.0.0-beta.1 build.
