### ISSUE TITLE
[Bug] New option sync tabs is not correctly displayed

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14307]
## Prerequisites
- Have "Secret Settings" enabled
- Be connected with an fx-account on mobile and desktop
## Steps to reproduce
1. Open browser and go to private mode.
2. Tap on tabs tray counter.
3. View the synced tabs in both normal tab and private tab.
### Expected behavior
All of the newly added elements are correctly displayed
### Actual behavior
- Synced tabs - text is not visible
- Sync button/icon is not visible
- Device name is not visble
- Synced tabs (links) - have gray font
- Synced tabs (page name) is white
It does not match the private mode font and 

Please check screen:
![Screenshot_20200827-162430_Firefox Nightly](https://user-images.githubusercontent.com/49859863/91473335-69c33180-e8a1-11ea-89eb-cee05cf93cfb.jpg)

### Device information

* Android device: Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 8/27

Note: issue related to 12287

**Comment by jonalmeida** [comment]
Closing as won't fix since we're removing this implementation.
