### ISSUE TITLE
Integration with password manager app broken

### ISSUE THREAD

**Issue by whricom** [mozilla-mobile/fenix#14304]
My password manager (LastPass) stopped popping up when tapping on a username/password field after the latest Firefox update.

## Steps to reproduce
Go to any login page and tap on a username/password field. You have no way of getting your password manager to show up

### Device information
Moto Z2 Play with Android 8.0.0
Firefox 79.0.5 (Build #2015758617)

**Comment by s-ankur** [comment]
It seems this is a known issue See #11702
