### ISSUE TITLE
[Bug] No tab history when long pressing back if keyboard is up

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14303]
## Steps to reproduce
Open the keyboard in a text box
Long press back
### Expected behavior
Tab history opens, keyboard dismissed
### Actual behavior
Nothing
Some devices have "kill app back button" option in developer options for android (LineageOS and MIUI do at least). This allows long press back button to force close the app. When firefox opens the tab history, this option won't be triggered. But right now I had the keyboard open and long press back button did not open the tab history. So this caused the kill app back button thing to activate and force close the browser. There was no crash as such

Most people will not see this issue. But it will still be an inconvenience.
### Device information

* Android device: Asus Zenfone M1 (LineageOS 16)
* Fenix version: Nightly

**Comment by person808** [comment]
> Tab tray opens, keyboard dismissed

I assume you mean tab history here :)

>  If you set the setting then it will Force Close the browser!!!

I'm not sure what you mean by "set the setting" here. What setting? I can't reproduce a crash on Android 10 (Pixel 2 XL). Also what Android version are you on? The implementation of long pressing the system back button is different for Android 7, so this could be very relevant if there is a crash.

I'm not sure if Android gives the capability to detect a long press on the back button when the keyboard is up, at least without any weird hacks. FWIW, I tried opening chrome's tab history with the keyboard open and nothing happens.

**Comment by s-ankur** [comment]
Hi, I've updated the description. Please check it out. Apologies for the incomplete information

**Comment by s-ankur** [comment]
You can close this if it is not actionable

**Comment by Diana-Rus** [comment]
Hi @s-ankur  is this still happening for you on latest Nightly 9/7? I've also checked, on this Nightly version with
- Google Pixel 3XL (Android 9)
- Samsung Galaxy S9 (Android 8)
- Huawei P10 (Android 9)
but without success.

Also in case you still encounter it maybe you can add a crash link? The signature may be helpful, thank you 😊.

**Comment by s-ankur** [comment]
No, I think it can be closed
