### ISSUE TITLE
FNX-5025 ⁃ Implement Fenix Snackbar

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1430]
![image](https://user-images.githubusercontent.com/1250545/55657171-3a90b980-57ae-11e9-873a-7131c9b760be.png)

**Comment by boek** [comment]
Questions for @brampitoyo 

Do we want to use the same style for Private / Dark themes as well?

**Comment by brampitoyo** [comment]
@boek wrote:
> Do we want to use the same style [for the snackbar] for Private / Dark themes as well?

Yes. I believe that our snackbar colour would stand out against both private and dark theme foundation colours, so we can safely use the same style across all themes.

Just paging @AmyYLee and @shorlander to get a confirmation.

**Comment by brampitoyo** [comment]
@boek @AmyYLee Just to confirm:

* If theme == light, use the `Accent - Dark` colour value, which is `#312a65`.
* If theme == dark OR private, use the `Accent - Bright` colour value, which is `#592acb`.

**Comment by AmyYLee** [comment]
> @boek @AmyYLee Just to confirm:
> 
>     * If theme == light, use the `Accent - Dark` colour value, which is `#312a65`.
> 
>     * If theme == dark OR private, use the `Accent - Bright` colour value, which is `#592acb`.

@brampitoyo if this works on private

**Comment by AmyYLee** [comment]
@boek My feedback for the snackbar animation: 

1. Can the snack bar slid up from the bottom when it appears (basically a reverse of when it disappears). 
2 The shape of the snackbar and text shouldn't resize or distort when it slides up from the bottom
3. Extend the animation so it's 200ms going up and 200ms going down (not sure what the duration it is currently) and see how that feels. The animation of it appearing/disappearing is a bit fast. 

Let me know if you have any questions. Thanks!

**Comment by AmyYLee** [comment]
@boek @bram 

> @boek @AmyYLee Just to confirm:
> 
>     * If theme == light, use the `Accent - Dark` colour value, which is `#312a65`.
> 
>     * If theme == dark use the `Accent - Bright` colour value, which is `#592acb`.

 Also for the snackbar in PBM * If theme == PBM use the `Purple - 70` colour value, which is `722291`.

**Comment by brampitoyo** [comment]
@boek Here are colours for snackbars that we agreed on.

I’m reiterating the values that @AmyYLee had posted earlier. Thanks, Amy!

* Light theme: `#312a65`
* Dark theme: `#592acb`
* Private theme: `#722291`

![snackbars@2x](https://user-images.githubusercontent.com/51007/56173016-ffa94400-603f-11e9-943e-f3cc5377a71d.png)
