### ISSUE TITLE
[Bug] Automatic incognito mode for keyboards in private browsing mode does not work in latest Nightly

### ISSUE THREAD

**Issue by antinucleo** [mozilla-mobile/fenix#14300]
## Steps to reproduce
Open a new private tab and start typing with a keyboard that supports the automatic incognito mode (e.g. Gboard).
### Expected behavior
The keyboard switch to incognito mode.
### Actual behavior
The keyboard does not switch to incognito mode.
### Device information

* Android device: Google Pixel 2 XL
* Fenix version: Nightly 200827 07:01 (Build #2015760379)

**Comment by s-ankur** [comment]
https://github.com/mozilla-mobile/fenix/issues/13423 duplicate
