### ISSUE TITLE
Investigate heuristics on how frequently visited top sites should appear

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#14302]
Currently, frequently visited top sites will appear as soon as they're visited on a fresh profile. If you don't have any user pinned sites and you visit 10+ different web sites, you will see them all upon on your home screen. 

Perhaps, we should add some heuristic on when a visited site should appear as a top sites. For example, we add a min visited requirement before it qualifies as a frequently visited top site.

- Investigate what ios does (possibly desktop) (<1 day)
- work with UX on what we want to do (1 day)
- Run the ideas from UX by AS (<1 day)

**Comment by jonalmeida** [comment]
Maybe also consider how often we update the frecent sites? On a fresh profile at least, it seems like we're always changing the top sites every time a page is loaded, so when you go to the home screen (which is a lot with the current UX), it feels a bit jarring to have a items moving around so often. 

For example, a top site in the 3rd position is now in the 5th after visiting another site and returning to the home screen.

**Comment by vesta0** [comment]
As part of this investigation, it would be great to see find out how desktop does it.

**Comment by gabrielluong** [comment]
In Desktop, this is the frencey threshold used to determine if a visited site should be displayed as a top site. https://searchfox.org/mozilla-central/rev/919607a3610222099fbfb0113c98b77888ebcbfb/browser/components/newtab/lib/TopSitesFeed.jsm#79

**Comment by gabrielluong** [comment]
@topotropic @vesta0 To summarize my investigation, desktop currently shows a visited site as a top site when the user has a frecency score of 101 (100+1). Frecency score is an internal score that is used by application-services that we can use to specify our threshold for when a visited site should be listed as a top site. Currently, a link with a single visit gets a score of 100, whereas a typed in URL gets a frecency score of 2000. Using a score 101 means it will ignore first-run/one-time/one-off visits to a page.

**Comment by topotropic** [comment]
Thanks @gabrielluong – we should be very deliberate and strict about what is automatically added to top sites and make sure it mirrors sites that people frequently visit on their mobile.

**Comment by vesta0** [comment]
Thanks @gabrielluong I think this logic is better than what we have now. We should show a visited site as a top site only when it has a frecency score of 101 and ignore first-run/one-time/one-off visits.

**Comment by gabrielluong** [comment]
For testing, we want to ensure that any single page visits are no longer shown in the list of auto-populated top sites.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build 1/29 with Google Pixel 4 XL (11).
Note that I accessed more than 15 webpages only once and they never appeared on the top sites with a clean profile.
When I accessed the pages for the second time they appeared.
