### ISSUE TITLE
[Bug] Swipe Top Sites does not work properly

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14309]
## Steps to reproduce
Turn on secret settings/show top sites recent ...
Set display size to smallest or get a tablet or similar device
Try to swipe top sites in the blank space
### Expected behavior
Swipe to switch the top site pane
### Actual behavior
Nothing
### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5715)

**Comment by s-ankur** [comment]
https://drive.google.com/file/d/1BBKQ4qkrMtxBtYtnXeBO50BZwrw7n0zZ/view?usp=drivesdk

**Comment by jonalmeida** [comment]
This happens in nested RecyclerViews when your swipe gesture starts in a vertical direction before horizontal so the touch is thrown out. There is some [nice detail here](https://medium.com/@BladeCoder/fixing-recyclerview-nested-scrolling-in-opposite-direction-f587be5c1a04) to read about it.

**Comment by klint** [comment]
I do confirm the issue on redmi note 7.
It is also happening more because the top sites are located on the top of the screen, far from the hand which makes it difficult to swipe exactly horizontally by an extended finger move.

**Comment by gabrielluong** [comment]
Gonna close this issue since moving to Compose should hopefully resolve this.
