### ISSUE TITLE
[Bug] Synced tabs in tab tray disappear if there are no normal mode tabs

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14305]
## Steps to reproduce
Activate synced tabs in tabs tray
Close all normal mode tabs

### Expected behavior
Synced tabs still show

### Actual behavior
They do not

### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by cadeyrn** [comment]
Duplicate of #14007.

**Comment by s-ankur** [comment]
Aah, GitHub search is really not helpful
