### ISSUE TITLE
[Bug] Firefox on Android appears to block LastPass from filling in credentials in forms

### ISSUE THREAD

**Issue by tmc-au** [mozilla-mobile/fenix#14314]
## Steps to reproduce
Set LastPass as the autofill input provider on an Android device
Open LastPass and authenticate to get access to the credential vault
Open Firefox for Android
Navigate to a login page for a service whose credentials are stored in the LastPass vault

### Expected behavior
LastPass will fill in the credentials (username and password) into the login form 

### Actual behavior
after a short time a Notificaion popup appears: "LastPass is unable to auto-fill this app"

### Device information

* Android device: Google Pixel 4, Android 10 (5 AUG 2020 security patch), Lenovo Yoga Tab 3 LTE, Android 9 (5 AUG 2020 security patch)
* Fenix version: 79.0.5 (Build #2015758619) and 80.0.1-beta.2 (Build #2015758611)

if this persist we will be forced to find an alternative browser.

**Comment by s-ankur** [comment]
this is a known issue see #11702

**Comment by kbrosnan** [comment]
Lastpass is working on adding Firefox support. We work with many other password mangers that use the correct Android Autofill API. Closing as a duplicate.
