### ISSUE TITLE
Toggle for "Add to Home Screen" tip (PWA)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14312]
### What is the user problem or growth opportunity you want to see solved?

As a user who is not interested in seeing the "add to home screen?" tip, I'd like to be able to disable it, like I can requests for location, etc. 

### How do you know that this problem exists today? Why is this important?

Seeing feedback for it in Play Store reviews. It is important for users to be able to manage the interruptions they receive in Firefox. 

### Who will benefit from it?

Any user who wants to see fewer tips or interruptions in Firefox. Also users who know about the add to home screen feature.

**Comment by kbrosnan** [comment]
This is a one time prompt. While you may be resetting your profile often the general user will only see this once per install.

**Comment by yoasif** [comment]
Once per install? Happy to close.
