### ISSUE TITLE
[Bug] shortcut icons issues

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#14315]
## Steps to reproduce
Creare shortcuts for  https://github.com and https://online.raiffeisen.ru

### Expected behavior
a better look for all icons

### Actual behavior
raiffeisen icon is shown better on nightly:
github icon is shown better on stable:

![image](https://user-images.githubusercontent.com/14617699/91494061-ed404b00-e8c0-11ea-8af4-df5b9cdf2738.png)

### Device information

* Android device: LineageOS 17.1
* Fenix version: Stable and Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5723)

**Comment by kbrosnan** [comment]
@NotWoods looks like the manifest says the icon should be #ffffff https://online.raiffeisen.ru/import/favicons/manifest.json any idea what is going on here?

**Comment by NotWoods** [comment]
If a site doesn't provide a maskable icon, we guess the best background based on the image. We shifted from using a custom implementation to using the Android Palette API, so behaviour is slightly different. 

- GitHub is picking up the white part of the logo, not ideal
- I don't know why GitLab isn't getting a background
- raiffeisen.ru is intended behaviour.

I'm assuming "Stable" here in Fennec but I don't know for sure. What is the version in the about page for both stable and nightly?

**Comment by liuche** [comment]
The icon badging here look like Fenix-y icons (not fennec)

**Comment by 532910** [comment]
`Stable` is Fenix stable org.mozilla.firefox 79.0.5

**Comment by 532910** [comment]
After several re-attempts I was able to create nice github icon on nightly and raiffeisen on stable.

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/91508951-97c86600-e8e1-11ea-8754-1b6124207d28.png)
![image](https://user-images.githubusercontent.com/14617699/91508954-99922980-e8e1-11ea-82e3-a4de9a811372.png)

Looks like it depends on how completely page is loaded to the moment of shortcut creation.

**Comment by 532910** [comment]
And gitlab looks bad and the same every time

**Comment by 532910** [comment]
Gitlab icon still looks strange.

**Comment by 532910** [comment]
gitlab icon still looks bad

**Comment by 532910** [comment]
still actual

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807105

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
