### ISSUE TITLE
[Bug] Nighlty crashes on startup

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#14318]
## Steps to reproduce
Install Nightly and start it

### Expected behavior
not crash
### Actual behavior
crashes
### Device information

* Android device: OnePlus 5t
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Could you share the top crash report from about:crashes?

**Comment by yoasif** [comment]
logcat? https://developer.mozilla.org/en-US/docs/Mozilla/QA/Fennec_Android:_Logging_with_the_Android_Debug_and_Logcat

**Comment by ale82to** [comment]
same issue here after wasting 3 hours of my spare time it turns out that the crash occurs only if nighlty is set as default browser clearing default for browser in android setting solve the issue.

**Comment by ekager** [comment]
Could someone who is experiencing this please link a crash report from about:crashes 🙏

**Comment by yoasif** [comment]
@ekager https://crash-stats.mozilla.org/report/index/3fa2294f-64bd-41f9-9846-e1d0b0200827 from https://github.com/mozilla-mobile/fenix/issues/14333

**Comment by ekager** [comment]
Hm cc @boek @eliserichards looks related to https://github.com/mozilla-mobile/fenix/pull/14126/files possibly?

**Comment by andreicristianpetcu** [comment]
@ale82to that's correct! I removed it from default browser and it works.

**Comment by andreicristianpetcu** [comment]
I don't have google play installed, not sure if it is relevant.

**Comment by andreicristianpetcu** [comment]
secret settings looks odd
![Screenshot_20200828-082143_Firefox_Nightly](https://user-images.githubusercontent.com/922368/91524363-ae81b380-e907-11ea-892c-9e0754fc5408.png)
Clicking on prompt for review crashes.

**Comment by B0pol** [comment]
54837620-7a09-43aa-ba65-0e63abb33cb1
com.google.android.play.core.internal.aq:/ailed to bind to the service.
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=6ab57e8364cb41d1a017faf2605a4cb5
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-40b690e6-6e8d-46f9-a0d0-eca300200828
----
com.google.android.play.core.internal.aq: Failed to bind to the service.
	at com.google.android.play.core.internal.ap.a(Unknown Source:78)
	at com.google.android.play.core.internal.ai.a(Unknown Source:4)
	at com.google.android.play.core.internal.ag.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by B0pol** [comment]
I pressed on prompt to review earlier today, it crashes but I can restart the browser. Then it worked for few hours, and suddenly, without changing any settings it crashed.

- the crash message is the same as the one after prompt for review, but I did not click on it when I got these crashes on startup
- I could open a new tab from a link, but I could not use tab tray to type about:crashes, because it was making instant crash
- it stopped crashing infinitely, I don't know why. I didn't clear cache, kill browser…
- my phone: Pocophone F1, Android 9, **no google play services**, only microG

**Comment by B0pol** [comment]
So it worked for two days but now I get crash on startup with today builds, but not from the beginning (I mean right after the update).

I can't even open it if I change default browser / open via a link (I could with the original bug report) then I don't know if it is related, but I can't open about:crashes anyway

**Comment by hwinnemoe** [comment]
@B0pol That is very likely #14486 and unrelated to this issue.

**Comment by ekager** [comment]
I think we can close this crash.

**Comment by sv-ohorvath** [comment]
No startup crash in Nightly 9/1 and RC 80.1.2.
