### ISSUE TITLE
[Bug] Self-Hosted sync server not configurable anymore and existing settings ignored/not imported

### ISSUE THREAD

**Issue by lordgurke** [mozilla-mobile/fenix#14328]
## Steps to reproduce
On versions < 79 you were able to configure your own sync server URL in about:config.  
Not only is this not an option anymore, as someone decided to lock "about:config" - this setting is also silently ignored resp. not imported with the update to version 79.  
This leads to my browsing data silently stored on someone else's computer (a.k.a. "Cloud") which is not what I want and not what I expect.

### Expected behavior
To have an option to enter my own sync server URL.

### Actual behavior
Since the update my sync data has been stored without my knowledge on a server which is addressed with the DNS name "sync-1-us-west1-g.sync.services.mozilla.com". Also since the update, my sync server has not received a single request from my mobile device. All other devices (PCs) are connecting to it. Since sending tabs between these devices is working for some odd reason, I didn't notice until now.  
Since I'm living in Europe, expect me to double my concerns about storing my sensitive browsing data on a system located in the US. And double it again for storing it without any prior warning or information.

### Device information

* Android device: HTC with Android 8.x
* Fenix version: 79
* Self-Hosted sync server running at home in the cupboard under the stairs.

### Additional ranting (optional)
To be honest, this is not what I expect when talking about "protecting what's important" or "customize your browser".  
How can I possibly customize a browser which is hiding vital functions ("about:config") for customization away from me without any good reason? I genuinely don't get it...  
And to be fair: This has severely damaged my trust in Mozilla in general and Firefox in particular. You cannot repair that. Sad.  
Is there any way to request full deletion of all stored sync data?

**Comment by liuche** [comment]
There is a feature for this in #3762

Docs update has a bug open here https://github.com/mozilla-services/services-engineering/issues/50 so please comment there if the information isn't clear enough.
