### ISSUE TITLE
New search experience - Undefined state when quickly toggling the keyboard

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#14321]
## Steps to reproduce
1. Tap the toolbar's search input element
2. Quickly close the keyboard again

### Expected behavior
The toolbar should be in its default closed state.

### Actual behavior
Intermittently, the search experience is still open in an undefined state without an open keyboard, see the gif:

![new_search_undefined](https://user-images.githubusercontent.com/42788925/91496520-9173c300-e8bc-11ea-9f5d-09e02e2d5110.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 200827 06:01 (Build #2015760369)
AC: 57.0.20200826190111, c93fc20af
GV: 81.0a1-20200820093209
AS: 61.0.13

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5733)

**Comment by hwinnemoe** [comment]
I can still reproduce on 97.0a1 (Build #2015851369), 8092b0399+
AC: 97.0.20211213151530, d09a19a4ae
GV: 97.0a1-20211213093143
AS: 86.2.1
2021-12-14T05:11:20.902407.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807727

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
