### ISSUE TITLE
[Feature Request] Preload pages in background when open in new tab is clicked

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#14334]
### What is the user problem or growth opportunity you want to see solved?
This will speed up web browsing and make browsing smoother.

### How do you know that this problem exists today? Why is this important?
This will reduce webpage load time.

### Who will benefit from it?
Everyone. (Except mobile data user for whom this may be off by default)

**Comment by cadeyrn** [comment]
Same as #14088. Why do you copy your already existing issue? You can re-open #14088.

**Comment by Oymate** [comment]
@cadeyrn That one said while long pressing, this one says when clicked on new tab.

**Comment by cadeyrn** [comment]
This one says "long pressing" as well.

**Comment by Oymate** [comment]
@cadeyrn fixed

**Comment by mcomella** [comment]
@Oymate On my Pixel 2, when I long press a link and select "Open in New Tab", wait a few seconds, open the tabs tray, and click the new tab, the page is already loaded. This would fit my definition of preloading a page.

Is that not happening for you or do you have another definition of what preloading is?

**Comment by Oymate** [comment]
@mcomella Yes, this is it, but on the phone I have this doesn't seem to be the case.

**Comment by MarcLeclair** [comment]
@Oymate  to test this further, could you please tell us which device you are using (OS too if custom), Android OS version,  and extensions installed?

**Comment by Oymate** [comment]
Nevermind, it is so slow I thought it didn't preload  :/

**Comment by MarcLeclair** [comment]
It sounds like pre loading is working as expected. If you disagree, please feel free to re-open the issue!
