### ISSUE TITLE
[Feature Request] Hold the back navigation button to see a history of the current tab since opening.

### ISSUE THREAD

**Issue by anabh4569** [mozilla-mobile/fenix#14335]
### What is the user problem or growth opportunity you want to see solved?

In the previous (non-fenix) mobile firefox, holding the back navigation button displayed a history of the currently opened tab. This allowed users to quickly go back many times (rather than repeatedly pressing the back navigation button).

Was this feature intentionally removed? Can it be added back again?

### How do you know that this problem exists today? Why is this important?

When I tried holding the back navigation button in a tab, nothing happened; it didn't open a history of the currently opened tab or even mirror the behavior of a quick press of the back navigation button.

I'm not sure how important it is or if it should be prioritized; it represents some convenience that previous mobile firefox users used to have but now don't.

### Who will benefit from it?

Everyone.

**Comment by person808** [comment]
This is in beta and should be in stable with v80. See #1048

**Comment by ValeK-tpa** [comment]
This hopefully won't get in the way of me closing the app.

My phone only has the one button. Quick press is back and long press is home.

**Comment by LittleAngelwings** [comment]
The thie following ticket for more information about this issue: https://github.com/mozilla-mobile/fenix/issues/13498

**Comment by cadeyrn** [comment]
@LittleAngelwings There will only be an issue for the issue opener if they is using a Huawai device. In Firefox 79 the feature does not exist yet for anyone. ;-)

@ValeK-tpa: That's interesting. I've never heard of something like that. Maybe you could test Firefox Beta and report back what the current behaviour is on your device? And if it's not what you expect it's probably a good idea to open an issue for that!

**Comment by LittleAngelwings** [comment]
@cadeyrn 

I mentioned my issue only as an information for the ticket participants ex. the opener 😊 Not as a dupe.
