### ISSUE TITLE
[Bug] Small, niche add-ons don't work on Firefox Android. Are they ever coming back?

### ISSUE THREAD

**Issue by georgekolasa** [mozilla-mobile/fenix#14339]
So basically any add-on less than 1Mil users won't work now? What about the many niche addons with a few thousand users that are super important to their users?

**Comment by Poopooracoocoo** [comment]
I don't know when Mozilla will allow us to use other extensions. There are quite a few issues like this and we all know that Mozilla shouldn't have released Fenix in its current state but it was based on time (specifically the ESR), not maturity, unfortunately. You should check out Iceweasel for Android! https://github.com/interfect/fenix/ The developer is super cool. He's really understanding and nice :)

**Comment by kuanyui** [comment]
An issue about this opened 7 days ago, **but donno why mozilla lock it up...** :  https://github.com/mozilla-mobile/fenix/issues/14034

Since WebExtension support revoked from Firefox for Android, I feel my soul is dying...

**Comment by cadeyrn** [comment]
See #14034 for the next step and follow https://blog.mozilla.org/addons/ for announcments regarding add-on support.

@Poopooracoocoo I don't think it's appropriate to advertise an inofficial fork in the issues tracker of Fenix.

**Comment by Poopooracoocoo** [comment]
@cadeyrn I didn't _tell_ George to switch to Iceweasel. I only asked him to check it out. I wasn't _advertising_ anything either (in the sense of monetary gain). I'm not in breach of the [Mozilla Code of Conduct](https://www.mozilla.org/en-US/about/governance/policies/participation/). There's nothing inherently wrong with unofficial forks. It's up to the user to trust it.

**Comment by Dunexus** [comment]
Quoting the add-ons community manager https://github.com/mozilla-mobile/fenix/issues/11308#issuecomment-671500918 : 
>We would like to enable support for more extensions and we're still evaluating the best way to do that without running into some of the compatibility and security issues we saw on Fenix. One option we are looking into is enabling general extension support on a pre-release channel (like Nightly or Beta). We haven't made any decisions yet so there are no details, but we will announce them on the [Add-ons Blog](https://blog.mozilla.org/addons/category/mobile/) when they are available.

**Comment by hwinnemoe** [comment]
> There's nothing inherently wrong with unofficial forks. It's up to the user to trust it.

The developers themselve tell you that you should not trust this fork: "**No warranties or guarantee of security or updates**. Binaries are currently are manually built and are not meaningfully signed. Why should you trust random people on the Internet to provide your web browser, one of the most important pieces of software you use? You probably shouldn't. Go away." (source: https://github.com/interfect/fenix/commit/a8ad843d94f789d4555c9543decca9775269e613)

**Comment by Poopooracoocoo** [comment]
I think you're agreeing with my point. It is up to the user to trust it. They can run into issues and it won't be the developer's fault as the developer said.

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/12655
https://github.com/mozilla-mobile/fenix/issues/13059

https://github.com/mozilla-mobile/fenix/issues/14339
https://github.com/mozilla-mobile/fenix/issues/14452
https://github.com/mozilla-mobile/fenix/issues/14489
https://github.com/mozilla-mobile/fenix/issues/15154
