### ISSUE TITLE
Share image does not work

### ISSUE THREAD

**Issue by chronicweirdo** [mozilla-mobile/fenix#14338]
On the new version of Firefox for Android 79.0.5, you can no longer send an image to other applications, only the link to the image is sent. This seems to be a regression, since sharing an image would send the actual image file to the other applications before the update.

How to reproduce:

1. On Firefox for Android 79.0.5 open a web page with an image on it;
2. Long press on the image to bring up the context menu;
3. Click on the "Share image" option;
4. Select an app you want to send the image to (for example a messaging app like Signal or an app where you would upload the image like Dropbox);
5. Only the link to the image is sent to the chosen app, instead of the whole image.

**Comment by s-ankur** [comment]
This is a known feature request See https://github.com/mozilla-mobile/fenix/issues/12414

**Comment by chronicweirdo** [comment]
@s-ankur thank you, I did not find it, I will close this since it's a duplicate
