### ISSUE TITLE
[Bug] Smart keywords no longer work

### ISSUE THREAD

**Issue by CaviaPorcellus** [mozilla-mobile/fenix#14337]
## Steps to reproduce

1. Set up [smart keywords](https://support.mozilla.org/en-US/kb/how-search-from-address-bar) for various sites. 
(Setting a keyword is done by right-clicking a website's search and selecting "Add a Keyword for this Search..." I don't actually know a simple way of doing this in Firefox for Android besides manually editing a bookmark, but I set up all my keywords using Desktop Firefox.)
2. Sync your bookmarks, so Firefox for Android will have access to the smart keywords.

### Expected behavior

When the keyword is entered before a search term in the address bar, the term is searched not by your default search engine, but rather that particular site, as invoked by the smart keyword. This worked correctly until the most recent Firefox update.

### Actual behavior

The default search engine is opened and searches for both your smart keyword and the term you wanted to search for.

### Device information

* Android device: Pixel 3 running Android 10
* Fenix version: 79.0.5

**Comment by cadeyrn** [comment]
See #14327 for keyword support.
