### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by S4qFBxkFFg** [mozilla-mobile/fenix#14344]
Firefox on Android updates from 68.11.0 when automatic updates are disabled in Google Play.

After restoring from Titanium Backup yesterday, I confirmed again that the auto update checkbox was unchecked and the version was 68.11.0, but this morning the app was updated again.

**Comment by hwinnemoe** [comment]
This issue tracker is about the the new Firefox starting with version 79. Update behaviour is up to Google Play, see https://support.google.com/googleplay/answer/113412
