### ISSUE TITLE
Toolbar transitions are slow to tabs tray and 3-dot menu on low-end devices

### ISSUE THREAD

**Issue by nandhp** [mozilla-mobile/fenix#14340]
## Steps to reproduce

Tap any button on the toolbar, such as the menu button.

### Expected behavior

The tap should immediately take effect.

### Actual behavior

There is a delay for an animation on the button; the tap only takes effect after the animation completes.

For example, when the menu button is tapped, there is an animation of an expanding circle on the button. Once the animation on the button completes, the menu starts to appear with a separate animation.

### Device information

* Android device: Samsung Galaxy Tab A 10.1 (2019)
* Fenix version: 79.0.5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5755)

**Comment by nandhp** [comment]
This might be related to #7797

**Comment by mcomella** [comment]
Triage: we were not able to reproduce a delay on high-end devices but noticed it on low-end devices (GS5, G5): the delay is anecdotally longer than Chrome. In v80+ we didn't see the animation when clicking on the toolbar (regression?).

**Comment by mcomella** [comment]
Action item: ideally we can get this to 100ms so let's measure and see where we're at currently. Maybe we can speed up the animations to compensate.

**Comment by mcomella** [comment]
@ecsmyth This feels like a borderline P1 performance issue: the first action item is to take timings to identify how urgent it is to address. How should the priority of this action item weigh against the priorities of our planned startup and startup test improvements? e.g. Should it fit in the middle? After?

**Comment by mcomella** [comment]
Triage: we're doing planning on Monday so let's re-eval after that.

**Comment by mcomella** [comment]
Triage: Let's discuss during planning.

**Comment by mcomella** [comment]
Triage: marcleclair says A50, our new low-end reference device, doesn't appear to be slow annecdotally. However, ideally we'd measure this.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807367

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
