### ISSUE TITLE
Tab tray screenshots flicker when loaded in

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14343]
## Steps to reproduce

1. Tap tab switcher icon

### Expected behavior

Screenshots should be present on initial display.

### Actual behavior

I see placeholders briefly, then a flicker as the screenshots are loaded. Worse still, the screenshots are not present if I open the tray a few times in succession. 

See video: 

![recording-20200828-022847](https://user-images.githubusercontent.com/152493/91529274-ff2ce880-e8d6-11ea-9ae6-41c6b0563557.gif)

### Device information

* Android device: Moto G (XT1031)
* Fenix version: latest nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5757)

**Comment by liuche** [comment]
Do you know @jonalmeida if there's something that happens with the AC thumbnails loading (are we reloading them every time) or if there's something else we could do on the Fenix side re: flicker?

**Comment by jonalmeida** [comment]
@liuche If by "flicker" you mean fade in, then yes this is the default loading animation behaviour of the `RecyclerView`. If we want to change this, we can look into non-default state to show when the thumbnail is loading from disk.

Otherwise, I don't see any flicker in the gif above. @yoasif could you clarify?

**Comment by yoasif** [comment]
@jonalmeida If I switch windows in macOS or Windows, I never see a generic "window" icon - I just see the windows when switching between them. Fennec also manages to show screenshots every time i load up its tab view without ever loading in a placeholder. That is the flicker I am referring to.

If Fennec shows white at any point, I am not seeing it, so it may be caching it (which is what I would have expected on subsequent loads of the tab tray in Fenix).

**Comment by jonalmeida** [comment]
With https://github.com/mozilla-mobile/fenix/issues/19809, this bug is noticeable so let's see if there's anything we can do about it with the new implementation of the tabs tray.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812912

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
