### ISSUE TITLE
[Bug] blue 'new things' blob on 3 dot menu persists

### ISSUE THREAD

**Issue by tomchiverton** [mozilla-mobile/fenix#14345]
## Steps to reproduce
Open a site with PWA
See blue blob 
Tap menu
See "install" with blob 
Close menu 
### Expected behavior
Blue blob removed for this and future visits 
### Actual behavior
Blob stays forever becoming meaningless, more so as more sites add PWA
### Device information

* Android device: LG Q6
* Fenix version: dunno, help / about menu items have been removed

**Comment by s-ankur** [comment]
Similar to  #7660. You can go to Settings/about firefox for the version info

**Comment by liuche** [comment]
Thanks for filing, and linking! this would be the same bug, we should not show the notification if you've already installed this site as a PWA.

**Comment by tomchiverton** [comment]
No, it's different.

That is "don't show blob if installed"

This is "don't show blob (forever?) if already dismissed" 
-- 
Tom
