### ISSUE TITLE
[Bug] [Nightly Only] Secret Settings menu item does not persist

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14348]
## Steps to reproduce
Activate secret settings 
Update or force close app

### Expected behavior
The menu option in settings remains
### Actual behavior
It does not. It can be confusing since the settings themselves apply. It's just that the option disappears. This will cause confusion for both reporters and devs
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by cadeyrn** [comment]
Sounds expected to me and not like a bug. I can't image that it's intended to have the secret settings menu always visible.

**Comment by LittleAngelwings** [comment]
I think it's an expected behavior in Android if there is the developer menu activated. The menu item is still visible there if is activated once. Also after a reboot of the device. I'm wondering also I must activate the menu again and again in Fenix.

**Comment by TrianguloY** [comment]
Android's secret developer settings menu is kept enabled until a factory reset, and almost all other apps with a similar menu (always enabled by repeated clicking some version number) keep it too. If you enable it it's because you are going to use it, so having to reenable every time you need to change something is a discomfort.

For me it is also a bug (or a needed feature).

**Comment by s-ankur** [comment]
Most problematic is that the menu disapears but the options that you have in it are not disabled. Either both should persist or none should, according to me at least

**Comment by hwinnemoe** [comment]
> 
> 
> Most problematic is that the menu disapears but the options that you have in it are not disabled. Either both should persist or none should, according to me at least

100% on that one, this caused quite some confusion if users just enabled some flags and forgot about it, see #13388 and all duplicates of it.

**Comment by liuche** [comment]
Secret settings isn't really a supported "user feature", it's a debug mode so that devs can flag things on/off, so we're not going to be adding more functionality around it.
