### ISSUE TITLE
[Bug] Tab history missing vertical padding.

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#14346]
## Steps to reproduce
Open tab history

### Expected behavior
There is some vertical padding between history items. `minHeight` should be 56dp I believe?

### Actual behavior
No vertical padding
<img src="https://user-images.githubusercontent.com/6396431/91534110-b4967680-e8ac-11ea-94d7-391191654efe.png" width=300 />

### Device information

* Android device: Pixel 2 emulator, Android 7
* Fenix version: Latest master

cc @NotWoods

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200904`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![Screenshot_20200904-094633](https://user-images.githubusercontent.com/51314259/92208984-e56e4100-ee94-11ea-9048-8f3ab162dee6.png)
