### ISSUE TITLE
Support "FoxyProxy Standard" extension on new Firefox app on Android (Fenix)

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#14349]
### What is the user problem or growth opportunity you want to see solved?
Support "FoxyProxy Standard" extension on new Firefox app on Android (Fenix)
### How do you know that this problem exists today? Why is this important?
I can't install "FoxyProxy Standard" extension on new Firefox app on Android (Fenix)
It's important because I want to set a proxy.
### Who will benefit from it?
I and those who want to set up a proxy in their browser.

**Comment by xmha97** [comment]
https://github.com/foxyproxy/firefox-extension/issues/113

**Comment by cadeyrn** [comment]
> We would like to expand our support to other add-ons but we are not keeping open requests for specific ones, even those in the recommended add-ons program. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.

from https://github.com/mozilla-mobile/fenix/issues/13925#issuecomment-677828853 (and you can find similar statements in several other similar issues)

See also #14034 for the next steps for expanding the add-on support in Firefox.

**Comment by liuche** [comment]
I'm going to close this because we won't be following up on specific addon requests filed in this repo. Please visit the other bug and see the linked discussion thread there.

**Comment by kurahaupo** [comment]
@liuche which _"other bug"_ are you referring to?

There are at least 3 referenced here, but:
* the bug reports on  [FoxyProxy](/foxyproxy/firefox-extension/issues/113) and [Cookie Autodelete](https://github.com/mozilla-mobile/fenix/issues/13925) have been closed;
* #14034 is a feature request rather than a bug report per se.
