### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by rojinvgeorge** [mozilla-mobile/fenix#14352]
After the update manually addon (extension) gone.please fix this issue soon  As possible

Device name =realme 3 pro
Android version=android 10
 Contact email(rojinvgeorge2@gmail.com)

**Comment by hwinnemoe** [comment]
> We would like to expand our support to other add-ons but we are not keeping open requests for specific ones, even those in the recommended add-ons program. Please follow the Add-ons Blog for future updates. 

from https://github.com/mozilla-mobile/fenix/issues/13925#issuecomment-677828853. You can also follow https://github.com/mozilla-mobile/fenix/issues/14034 for the next steps in add-on support in Firefox.
