### ISSUE TITLE
[Bug]please allow more than 8 topsites on home 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14359]
please allow more than 8 topsites on home page without swiping left /right in latest nighlty.
in old build we can have as many topsites as we need why ruining this feature?!!!!??? ?.
first tab management,then dynamic bottom toolbar,change by change fenix is getting worse and worse and on reddit is plenty of people complaining!

**Comment by cadeyrn** [comment]
16 top sites are allowed, not 8. This issue can be closed as duplicate since the discussion already happens in #8312.
