### ISSUE TITLE
[Bug] Search Engines button checked status is not updated

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#14354]
## Steps to reproduce
- Tap the search engines button
- Select a search engine

### Expected behavior
- The search engines view is closed, and the button is unchecked

### Actual behavior
- The search engines view is closed, but the button is stil checked
- Tapping it again opens the view, but unchecks it

### Device information

* Android device: ?
* Fenix version: Nightly

**Comment by Diana-Rus** [comment]
Hi, issue is fixed verified on Nightly 9/1 with:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3XL (Android 9)

<details closed><summary>GIF-Samsung Galaxy S9 (A8)</summary>

![20200901-181225](https://user-images.githubusercontent.com/49859863/91872099-26d9d300-ec80-11ea-93e9-52a7d5e628e7.gif)
</details>
