### ISSUE TITLE
Option to set master password removed

### ISSUE THREAD

**Issue by man1001** [mozilla-mobile/fenix#14368]
It seems the option to set a password to protect login-data got removed with the last update.

**Comment by kbrosnan** [comment]
Duplicate #14363. This feature is now controlled by requesting the user's device authentication.

**Comment by yoasif** [comment]
@kbrosnan Using system authentication is not the same as Fennec's previous primary password functionality. Is that feature officially deprecated (it continues to exist on desktop, see https://support.mozilla.org/en-US/kb/use-primary-password-protect-stored-logins-and-pas)?

Just pointing out that this is not a dupe.
