### ISSUE TITLE
[Bug] Only first attempt opens link in external app in a page with multiple links

### ISSUE THREAD

**Issue by Nirose** [mozilla-mobile/fenix#14369]
## Steps to reproduce
Have an app capable of handling reddit.com links 
Go to jimmyr[.]com
tap on reddit comment links

### Expected behavior
every reddit link should open on an external reddit app

### Actual behavior
Only the first attempt launches it with the reddit app. subsequent attempt open on firefox itself. 

### Device information

* Android device: Oneplus 3T. Android 9.0
* Fenix version: Nightly 200828 06:01 (Build #2015760563)

Coincidentally, this bug is not present on stable version, last time I checked.

**Comment by liuche** [comment]
Does this happen for other apps as well?

**Comment by Nirose** [comment]
> Does this happen for other apps as well?

at the time of writing the bug report, it did happen with imgur app as well, but on the latest nightly, imgur links are opening on the app fine.

On the latest nightly, the behavior has changed slightly. 
After using the "open in external app" from the context menu, then going back (to firefox), the links open on the app for a second time. but after that, subsequent links starts loading them on the browser itself again.  

have to use "open in external app" to make it work the once again

I recorded  a video with the latest nightly. Nightly 200829 06:05 (Build #2015760755)

https://i.imgur.com/RCZ9wLQ.mp4

**Comment by Blaze-Thunder** [comment]
This issue was never solved. Only the first link opens in external app and subsequent links open only in firefox. Please fix this issue.
