### ISSUE TITLE
FNX-5026 ⁃ [Bug] Fenix Health Report is off by default

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#1436]
## Steps to reproduce
Go to Settings, Data Choices.

### Expected behavior
It should be on by default.

### Actual behavior
It's off.

### Device information
* Android device:HTC one m9 
* Fenix version: 1.0.1914

As far as I understand, the purpose of this feature is to send a daily ping reporting the status of the client.

**Comment by vesta0** [comment]
@mheubusch please share your decision regarding this feature in Fenix.

**Comment by kbrosnan** [comment]
Telemetry is the only option now and it is on by default.
