### ISSUE TITLE
Allow moving bookmarks en masse

### ISSUE THREAD

**Issue by mwoehlke-kitware** [mozilla-mobile/fenix#14365]
### What is the user problem or growth opportunity you want to see solved?
Add ability to move bookmarks *en masse*. This could easily be implemented by adding a 'move to folder' option when multiple bookmarks are selected. (See e.g. most photo gallery apps / file manager apps.)

### How do you know that this problem exists today? Why is this important?
Right now the only way to move bookmarks is to edit each bookmark individually. This takes six taps *per bookmark*. Trying to move more than 1-2 is painful.

### Who will benefit from it?
Anyone with a non-trivial number of bookmarks.

**Comment by kbrosnan** [comment]
Duplicate #1869
