### ISSUE TITLE
[Bug] Can no longer select bookmarks as default tab page

### ISSUE THREAD

**Issue by davidmegginson** [mozilla-mobile/fenix#14360]
## Steps to reproduce
* Open a new tab

### Expected behavior
* There is an option to display bookmarks as the new tab

### Actual behavior
* Hardcoded, non-configurable new-tab page

### Device information

* Android device: Nexus 6 (Android 7.1.1)
* Fenix version: 79.0.5

**Comment by cadeyrn** [comment]
Duplicate or part of #12065 and #12941.

**Comment by liuche** [comment]
Thanks for filing, we're investigating how to make the homescreen most useful and also customizable for users, so please see the two bugs filed on that topic above.
