### ISSUE TITLE
Bottom toolbar does not hide on scroll for home www.homedepot.com

### ISSUE THREAD

**Issue by danddba** [mozilla-mobile/fenix#14361]
With the toolbar displaying on the bottom
- Navigate to https://www.homedepot.com
- Scroll to the bottom, and as the attached image indicates, not all of the page is visible.  The bottom most portion of the page content is hidden behind the address bar.
- If this isn't immediately reproducible, refresh the page or select an item to navigate to another page to reproduce.

Expected behavior: I expected the content to scroll above the toolbar, or the toolbar to collapse so all page content would be visible.

![Screenshot_20200828-082248_Firefox](https://user-images.githubusercontent.com/59364877/91565372-b8a3b200-e907-11ea-8974-3b8c971b92a2.jpg)

**Comment by cadeyrn** [comment]
I can confirm the issue in Firefox 79 but it seems already to be fixed in Firefox Beta and Firefox Nightly.

**Comment by s-ankur** [comment]
Encountered similar issue on https://discourse.mozilla.org/t/add-on-support-in-new-firefox-for-android/53488/25 with nightly

**Comment by liuche** [comment]
These all seem related, so going to consolidate them to #13797
