### ISSUE TITLE
[Bug] Redirect user to tabs tray when connecting with an account when using sync tabs sing in

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14362]
## Prerequisites
- Have "Secret Settings" enabled
### Steps to reproduce
1. In browser tap on tabs tray counter.
2. Tap on "Sign in to sync" button.
3. Connect with the device on both mobile and desktop.
### Expected behavior
User is redirected to homescreen or active tab with tabs tray open?
### Actual behavior
User is redirected to homescreen or active tab without tabs tray open.
This happens in:
- Normal browsing - Normal tabs section
- Normal browsing - Private tabs section
- Private browsing - Normal tabs section
- Private browsing - Private tabs section
### Device information

* Android device: Google Pixel 3XL (Android 9), Samsung Galaxy S9 (Android 8)
* Fenix version: Nightly 8/27

Note:
Issue mentioned in feature https://github.com/mozilla-mobile/fenix/issues/12287#issuecomment-682087410

**Comment by liuche** [comment]
Secret settings isn't really a user-facing feature and meant more for development, so we shouldn't consider that a common use case. Sometimes bugs could be related to the feature that is turned on in secret settings however, which would be a bug.

Are these sync bugs still reproducible even with secret settings turned off?

**Comment by Diana-Rus** [comment]
Hi @liuche ,
When the secret settings is turned off, on the present implementation of "Synced tabs" submenu, when logging in from the submenu user will be redirected to "Synced tabs" page/module so the user is redirected to the last place he was before signing in.

I can re-check after the feature is taken from "Secret Settings" flag, otherwise, the implementations are different with changing the place where the synced tabs are going to be displayed in UI.
