### ISSUE TITLE
Feature: Password Protected Sessions

### ISSUE THREAD

**Issue by sandeepkrs** [mozilla-mobile/fenix#14378]
Is it possible to have a password protected session where I can keep all my favorite sites logged in but protected with a password by firefox.

Firefox should open in normal mode but will also have usual incognito mode and new Protected mode which is same as normal mode but is protected with a login password and remeber sessions unlike incognito.

The protected mode should be independent to normal mode just like incognito but will not clear browing data on app/tab close. There I can choose to remember passwords, auto fill forms without affecting normal mode.

If we forget password for Protected mode, it will allow to reset password by clearing all browsing data.

We can have setting for when firefox should again ask for password? like after 30 min of no-foreground-activity and each time after app is closed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5811)

**Comment by s-ankur** [comment]
Similar #5387

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807543

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
