### ISSUE TITLE
Real Tabs

### ISSUE THREAD

**Issue by U-B-Glade** [mozilla-mobile/fenix#14379]
### What is the user problem or growth opportunity you want to see solved?
There is a Button on the right Top were i can swith Pages, but there are no Tabs at all, please bring back the Tabs (I mean real Tabs ) maybe as a selectable Option. This is aspecily for Tabletts usefull

### How do you know that this problem exists today? Why is this important?
I have to click twice if i like to change between two pages, it is more faster if i have Tabs on the top of the screen

### Who will benefit from it?
All User they do not wish it "smart", but fast and useable

**Comment by Dunexus** [comment]
See https://github.com/mozilla-mobile/fenix/issues/4498

**Comment by kbrosnan** [comment]
Closing as a duplicate.

**Comment by U-B-Glade** [comment]
Sorry why closed, I like to have it also on the Smartphone
