### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by U-B-Glade** [mozilla-mobile/fenix#14373]
### What is the user problem or growth opportunity you want to see solved?
There us no navigation possible, no Back Button, no reload on the top screen please make a real Navigation Bar selectable 

### How do you know that this problem exists today? Why is this important?
on Devices with smart Buttons it is a mess to get the Back hardware Button (e.g. on Tabletts) 

### Who will benefit from it?
All User with softkeys

**Comment by kbrosnan** [comment]
Closing as a duplicate of #4498

**Comment by U-B-Glade** [comment]
This is no duplicate it is a request also for Smartphones
