### ISSUE TITLE
FNX-5027 ⁃ Add user specified alternative search engines

### ISSUE THREAD

**Issue by Kastilo** [mozilla-mobile/fenix#1437]
### Why/User Benefit/User Problem
Adding options gives us alternatives to the big engines already and also allows for further user choice

### What / Requirements
Allowing the adding of search engines similarly to current Firefox

### Acceptance Criteria
When adding new search engines is possible

Thank you very mucch <3

**Comment by buttercookie42** [comment]
> Allowing the adding of search engines similarly to current Firefox

Including installation from https://mycroftproject.com/

**Comment by maverick74** [comment]
This and add-ons support are the only thing keeping me from migrating to Fenix.

**Comment by Espio419** [comment]
Mozilla pls

**Comment by Ryonez** [comment]
What's the current position of this issue? Kinda hard to guess with the current tag.

**Comment by edwintorok** [comment]
FWIW here is how a search engine can be added on the current version of Firefox, which doesn't work on Firefox Preview: https://support.startpage.com/index.php?/Knowledgebase/Article/View/1094/0/how-do-i-make-startpage-the-default-search-on-firefox-mobile-android-ios

**Comment by sblatz** [comment]
Discussed in meeting with @vesta0--this is a could for Q3.

**Comment by Ud4ba** [comment]
i would really like to see StartPage at search engines.

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by vesta0** [comment]
Thanks for filing @Kastilo ! This will be addressed in #5489
