### ISSUE TITLE
Migrate tab counter menu to concept-menu

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/fenix#14376]
We can unify the implementation between the two places where we show this menu.

**Comment by person808** [comment]
FYI, seems like the menu order isn't properly reversed for bottom toolbar. https://github.com/mozilla-mobile/fenix/issues/14385#issuecomment-683190524

**Comment by NotWoods** [comment]
Ack, totally missed the reverse call. Will fix soon.

**Comment by softvision-miralobontiu** [comment]
Hi @NotWoods, 
If I understood correctly, the tab counter menu should have this order when the navigation bar is set to the bottom?
![a](https://user-images.githubusercontent.com/40694158/91721908-2ec34580-eba2-11ea-8933-eca19a5f60c4.png).

Currently, on the latest Nightly build from 8/31, the tab counter menus are displayed like this:

![Untitled](https://user-images.githubusercontent.com/40694158/91722421-e3f5fd80-eba2-11ea-8ef9-b724d60ef4de.png)

I'll remove the QA:needed label until further notice.

**Comment by sflorean** [comment]
Verified as fixed on Nightly9/11 and 81.1.1-beta.3 with Samsung Galaxy Note 10 (Android 10) and Google Pixel 3 (Android 11).
