### ISSUE TITLE
URL results should have badged favicons

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#14388]
Firefox for Desktop have a nice little feature I believe they called "badged favicons". URL bar results that are in your bookmarks have a little star icon badge on the favicon. This is a nice and useful little touch
![badged favicons](https://user-images.githubusercontent.com/47801466/91610130-a85ef780-e946-11ea-8f25-24abdacca9ca.png)

**Comment by cadeyrn** [comment]
Already implemented in Firefox 80, currently available as Beta and soon on the stable release channel.

**Comment by willfs84** [comment]
Sorry, Fenix does already have this but there's an issue/issues that made me think it doesn't. It seems that there's an issue where duplicates of results come up in URL results, 1 of them will be badged and 1 won't. There could be other issues

**Comment by kbrosnan** [comment]
Works for me using [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix).

**Comment by willfs84** [comment]
It only works on some, I'm not sure what the cause is. Do I file a different bug?
