### ISSUE TITLE
now is ADD-OFF not ADD-ON

### ISSUE THREAD

**Issue by zpcol** [mozilla-mobile/fenix#14384]
why..? why..? why..?

**Comment by AVHon** [comment]
Is there a mis-spelling somewhere in the app, @zpcol ?

**Comment by zpcol** [comment]
I have a large collection of addons but they can't be used at night. a setback. there will be many people who are disappointed.

**Comment by cadeyrn** [comment]
See #14034 for the next steps for expanding the add-ons support in Firefox and follow https://blog.mozilla.org/addons/ for official announcements in this area.

**Comment by zpcol** [comment]
ok thank

**Comment by zpcol** [comment]
https://blog.mozilla.org/addons/
> Mozilla and Disconnect studied the performance benefits of blocking trackers and learned that tracking protection more than doubles page loading speeds. This work led us to build Enhanced Tracking Protection directly into Firefox in 2019 using Disconnect’s tracking protection list. 

but firefox itself has 3 tracker.. is this a joke?

**Comment by zpcol** [comment]
https://blog.mozilla.org/addons/2020/07/07/new-extensions-in-firefox-for-android-nightly-previously-firefox-preview/

given built-in extensions, all of which did not interest me.

**Comment by cadeyrn** [comment]
> See #14034 for the next steps for expanding the add-ons support in Firefox and follow https://blog.mozilla.org/addons/ for official announcements in this area.

There is no point in adding more comments. No other add-ons are supported in Firefox 79, more add-ons will be supported in the future.

**Comment by zpcol** [comment]
https://github.com/FilipePS/Traduzir-paginas-web
