### ISSUE TITLE
[Bug] dynamic toolbar not hiding on discourse.mozilla.org

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14386]
I think there is a duplicate somewhere for this one but I can't find it right now
## Steps to reproduce
https://discourse.mozilla.org/t/add-on-support-in-new-firefox-for-android/53488/25
Scroll to bottom
### Expected behavior
Dynamic toolbar disappears
### Actual behavior
It remains and wecontent is obscured
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Closing as duplicate of  #14361

**Comment by cadeyrn** [comment]
@s-ankur I don't think it's a duplicate because on the website mentioned in #14361 it's fixed in Firefox 80 Beta, n discourse.mozilla.org it still doesn't work, even in Firefox Nightly.

**Comment by s-ankur** [comment]
Then maybe https://github.com/mozilla-mobile/fenix/issues/14070?

**Comment by liuche** [comment]
These all seem related, so going to consolidate them to #13797
