### ISSUE TITLE
[Bug] m3u8 video stays muted on www.rte.ie

### ISSUE THREAD

**Issue by ksy36** [mozilla-mobile/fenix#14380]
## Steps to reproduce
Open https://cdn.rasset.ie/manifest/2020/0818/20200818_webexclusi-rte-ten-angelinajo_c21820557_21820559_260_/manifest.m3u8 and play the video

### Expected behavior
Video plays with sound
### Actual behavior
Video is muted and sound indicator can't be toggled to unmuted state
### Device information

* Android device: Samsung Galaxy S5
* Fenix version: Nightly 200827 (81.0a1-20200820093209)

**Comment by softvision-raul-bucata** [comment]
The issue is still reproducible on the latest build of Firefox Nightly 91.0a1 (2015816523 -🦎91.0a1-20210614095307🦎)
