### ISSUE TITLE
[Bug] Download failed with .7z files

### ISSUE THREAD

**Issue by eatmorepies-dev** [mozilla-mobile/fenix#14390]
## Steps to reproduce
Try to download a .7z file.
### Expected behavior
It downloads correctly.
### Actual behavior
Firefox throws a "Download failed" error
### Device information

* Android device: SM-N960U
* Fenix version: ?

**Comment by liuche** [comment]
Does this happen for .7z files on different sites? This could be related to how the site itself implements the download, or could be related to the file type somehow, but having more information would help.

Does this work on other browsers?

**Comment by eatmorepies-dev** [comment]
On the website I tested it on (vimm.net) the download worked in the Google
Chrome Android browser.

**Comment by kbrosnan** [comment]
Note that this site has a lot of different file types to download. It looks like most of the Playstation archives are `7z`.

**Comment by Amejia481** [comment]
STR

1. Go to echo https://vimm.net/vault/9235
2. Press the download button.


For some reasons, we are getting a 400 HTTP error when trying to download the [file](https://download3.vimm.net/download/?mediaId=7952), I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1662211 for the GV team to take a look!

**Comment by amedyne** [comment]
Duplicate bug of: https://bugzilla.mozilla.org/show_bug.cgi?id=1530022

**Comment by Amejia481** [comment]
We did some improvements to our download stack, please take a look in the latest [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) and if the issue still persist please feel free to reopen.
