### ISSUE TITLE
Android Share To Menu Entry Missing (For Ability to Share Directly to Other Devices)

### ISSUE THREAD

**Issue by Kyrluckechuck** [mozilla-mobile/fenix#14392]
## Steps to reproduce
- Attempt to share a link from any app (such as Google News)

### Expected behavior
- Option to share to other Firefox devices (such as desktop) directly without needing to open the app and manually share to other device, then close the tab, then close the app

### Actual behavior
- No options in list to share to other Firefox devices (such as desktop), and "Add to Firefox" no longer prompts for the same
- Can only open directly into the Firefox Daylight app, manually share to device, close tab, close app (very tedious when sharing multiple links to other browsers)

### Device information

* Android device: OnePlus 6 - 10.3.5 (Android 10)
* Fenix version: 79.0.5 (Build #2015758619)

**Comment by kbrosnan** [comment]
Duplicate #1523
