### ISSUE TITLE
[Bug] Tapping outside of context menus does not dismiss menu (regression)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14399]
## Steps to reproduce

1. Save a bookmark
2. Navigate to bookmarks
3. tap three dot menu next to bookmark
4. tap outside of menu

alternatively

1. long press on tab switcher button
2. tap outside of menu

### Expected behavior

menu is dismissed

### Actual behavior

menu stays, impossible to dismiss without picking a menu item

This works correctly in beta and release.

### Device information

* Android device: Moto G XT1031
* Fenix version: 200828 #2015760681

**Comment by liuche** [comment]
Are you still seeing this? I was able to dismiss the 3-dot bookmark menu and tab switcher button on the 8/31 build.

**Comment by yoasif** [comment]
I can still see this on this device.
