### ISSUE TITLE
Access extension browser action when no tabs are open

### ISSUE THREAD

**Issue by dessant** [mozilla-mobile/fenix#14394]
### What is the user problem or growth opportunity you want to see solved?

The browser action of extensions cannot be accessed unless a website is opened in a new tab. When there are no tabs open, the `Add-ons` button from the main menu opens the extension manager directly, instead of listing registered browser actions.

### How do you know that this problem exists today? Why is this important?

Extensions often have browser actions that can be used independently from the context of a web page. Search by Image can be used to upload images from storage, or search with an URL from the clipboard, these features are not related to the current page, and do not require a tab to be open, but currently we have to load a random website to access the extension.

### Who will benefit from it?

Extension users.

**Comment by liuche** [comment]
We're revisiting the toolbar menu across browser and homescreen in #14320 so please follow along there. Thank you for filing!

**Comment by dessant** [comment]
This issue was not addressed and https://github.com/mozilla-mobile/fenix/issues/14320 is now closed. Please reopen the issue, or link to the relevant place to follow updates.
