### ISSUE TITLE
[Bug] (new search experience) switching to Android home screen leaves the keyboard open

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#14396]
### Steps to reproduce

1. open the address bar
2. press the Android home button

### Expected behavior

You see your Android home screen, but no keyboard.

### Actual behavior

The keyboard is still open. It does not happen when the new search experience is disabled via the feature flag.

![Screenshot_20200829-005157](https://user-images.githubusercontent.com/1100614/91621059-0c5add80-e992-11ea-99cb-218932a04f54.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision 96207630fce1e9ab058543a445e0e9f7b7aba0e1

**Comment by liuche** [comment]
@boek shouldn't be happening in master today?

**Comment by boek** [comment]
Hmm.. Strange. I can't reproduce locally but I can still reproduce on nightly. I'll investigate more

**Comment by s-ankur** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/13432

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 81.1.0-beta.1 (Build #2015761489) GV 81.0 from 9/2 with Samsung Galaxy Tab S3 (Android 8).

**Comment by eliserichards** [comment]
Closing as solved
