### ISSUE TITLE
FNX-5029 ⁃ Sessions on the homescreen does not close properly when tapping the close button

### ISSUE THREAD

**Issue by thanuj10** [mozilla-mobile/fenix#1439]
## Steps to reproduce
1. Use fenix and save a session.
1. Open fenix and close the session.
1. Session does not collapse or go away.
1. When you scroll to the top, the session icon changes to the one that is default

### Expected behavior
When user closes the session, the session must collapse/go away and must not simply stay until the user scrolls on the homescreen

### Actual behavior
The session box does no go away until the user scrolls on the homescreen.

### Device information
* Android device: Nokia 6.1+ (9.0 Pie)
* Fenix version: 1.0.1914 (4/5 Friday Build)

**Comment by ekager** [comment]
Thanks for reporting! Let us know if you're still seeing this issue in the latest build

**Comment by thanuj10** [comment]
The issues is fixed in the latest build (4/8 Build)
