### ISSUE TITLE
Add more granularity in browsing data deletion (specifically history vs site data)

### ISSUE THREAD

**Issue by adfhogan** [mozilla-mobile/fenix#14402]
### What is the user problem or growth opportunity you want to see solved?
Unbundle the deletion of browsing history from the deletion of site data in newer Android builds.

### How do you know that this problem exists today? Why is this important?
The browser, as part of its operations stores data for only the benefit of the user (such as form autofill, browsing history etc.). It also stores data that can be leveraged by the sites that a user visits (cookies, cache, local storage/site data).

In previous versions of the Android browser, and the current desktop browser, when deleting data, site data is a separate category unto itself, and not bundled with browsing history. This means you can elect to delete data which is used locally, and data which is shared with remote systems.

In the current versions of the Android browser (definitely 79.0.5 and higher), when either going to the delete dialog or selecting Quit, the option to delete Site Data is bundled with Browsing History. This means if someone wants to delete their local storage, they have to wipe their browsing history too. This is because a user may wish to retain a history for their own benefit of where they've been, whilst wiping data that a remote site may use to persist information about them.

That is, I might want to remember I visited a website last week, but I might not want that website to remember it (browser fingerprinting aside).

Unless what entails "site data" is different to my expectations (I understand "site data" to include "local storage" used to retain larger and more complex information than cookies), I now have to purge my browsing history when I want to purge this local storage.

If my understanding of what the different categories entail is wrong, then the documentation for the dialog needs to be updated to precisely define what is managed by each category in the new dialog. Present documentation appears to focus on the desktop versions of the browser which use a different set of checkboxes to Android.

### Who will benefit from it?
Users who wish to retain some metadata for their own personal benefit, whilst purging that in use by sites they visit.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/10175
