### ISSUE TITLE
[Un-Feature Request] It would be nice if icons in the bookmarks menu didn't behave differently from the rest of the bookmark

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#14406]
### What is the user problem or growth opportunity you want to see solved?

When browsing the bookmarks menu, bookmark icons and folder icons should not act like checkboxes for multi-select when tapped unless multi-select in general has been activated through some other means (i.e. tapping and holding a bookmark or folder). The fact that they currently always act like checkboxes makes the UI less intuitive, not more.

### How do you know that this problem exists today? Why is this important?

In the bookmarks menu, touching a bookmark icon on the current release of Firefox for Android (v79.0.5) activates multi-select and selects the bookmark, instead of navigating to the bookmarked URL.

Typically on touch devices, you tap an object to initiate a default interaction, and tap-and-hold instead to either initiate a secondary interaction or open a menu that offers multiple interactions, yes? In the bookmarks menu, the expected default interaction for a bookmark would be to open that bookmark in the current tab. Expected secondary interactions might include reordering them, editing them, or multi-selecting them to manage in bulk.

Visually speaking, a bookmark's icon is part of the bookmark. It does not resemble a special UI control and it certainly does not resemble a checkbox. It also does not need to act like a checkbox, since tap-and-hold activates multi-selection anyway. One would thus expect the icon to act the same way as the rest of the bookmark when tapped (i.e. when you have not activated multi-select, tapping it should send you to the bookmarked web page), and one would be mistaken. This means that in order to open a bookmark, you now need to aim around the bookmark icon; you have to remember that it's an obstacle even though it doesn't look like one and isn't something you'd expect to be one.

(It's fine, however, if the icon acts as a checkbox when multi-select is active, because the rest of the bookmark also acts as a checkbox in that circumstance.)

Interacting with the bookmarks menu should be intuitively obvious. Everything should do exactly what it looks like it will do, and it should ideally not do anything that it doesn't look like it would do. You shouldn't have to think about how to interact with the bookmarks menu; the only thing you should have to think about is the task that you are trying to complete using Firefox and its bookmarks menu: I want to go to X website so I can do Y thing for Z reason.

### Who will benefit from it?

People who open bookmarks from the bookmarks menu, and who would prefer to do so without having to waste time thinking about how to operate the menu itself.

**Comment by s-ankur** [comment]
I agree, clicking on icons for multi select is not at all intuitive behavior,

**Comment by cadeyrn** [comment]
I strongly disagree. For me it's a very convenient feature and it's already known from other popular apps like Gmail. Since the UI is very similar it's my expectation as a user that it works the same way.

**Comment by DavidJCobb** [comment]
In Gmail, or at least in the version I have installed, the checkboxes look like checkboxes:
![cropped screenshot of an email notification from this very thread, with a checkbox next to it](https://user-images.githubusercontent.com/831497/91637960-5e404980-ea0c-11ea-8468-934be068c6e0.jpg)

**Comment by cadeyrn** [comment]
> In Gmail, or at least in the version I have installed, the checkboxes look like checkboxes:

This is how it looks on my device:

![Screenshot_20200829-153321](https://user-images.githubusercontent.com/1100614/91638074-271e6800-ea0d-11ea-848e-18c9f5f65aa2.jpg)

**Comment by DavidJCobb** [comment]
Hm, that's strange. Haven't seen that before; thank you for the screenshot.

If these are both standard ways of presenting a checkbox list, then I guess it comes down to which is judged to be more intuitive by more people (or more likely, it'll come down to the other 2K-odd issue reports being actually urgent and this one being the opposite).

**Comment by s-ankur** [comment]
It's to do with the layout you select in gmail :compact vs comfortable. But yes, if gmail does it, it's probably intuitive just by the sheer number of users who use it

**Comment by liuche** [comment]
Yes, I believe that's the pattern that we were using for this. Since it's a common Android pattern (and in Google apps) I'm going to close this issue.
