### ISSUE TITLE
[Bug] Synced tabs in tab tray have white text in private mode

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#14407]
## Steps to reproduce
Have synced tabs in tab tray enabled.
Open at least one private tab and be in private mode

### Expected behavior
Synced tabs look the same as in normal mode

### Actual behavior
Synced tabs use white text on white background due to private theme colors
![Screenshot_20200828-230054](https://user-images.githubusercontent.com/6396431/91630025-f85baf80-e982-11ea-8e7c-9add07991d91.png)

### Device information

* Android device: Pixel 2 XL, Android 10
* Fenix version: 8/28 nightly

**Comment by Diana-Rus** [comment]
Hello, this is going to be treated under #14307, please follow it's evolution there. I'll be closing this as a dupe
Thank you for reporting it 😊.
