### ISSUE TITLE
Publish intent that allows for on-demand launching of private tab from other apps OR give option for prompt on launch

### ISSUE THREAD

**Issue by adfhogan** [mozilla-mobile/fenix#14405]
### What is the user problem or growth opportunity you want to see solved?
I frequently run my Android device without a default browser selected. When an app requests to open a browser, I'm provided with a list of the installed browsers and can select "Just Once" or "Always". I generally prefer to use Firefox, and I generally don't browse privately, but sometimes I use a different browser (because a website might have made poor assumptions about Android == Chrome), and sometimes I do want to browse privately, but the requesting app doesn't always provide a means of copying the link before it launches the browser.

In the past, certain preview builds of Firefox offered a visible intent that could be selected on demand (or made the default) to launch a private browsing session. This allowed for runtime selection by the user of whether or not they wanted to open the site in private mode or not.

This option was then removed for an option to make all requests to the only user-selectable intent normal or private based upon the setting in the browser..

I propose that the option to select intent that opens a site as private be restored as a visible/selectable option for users
... or ...
Adding a third option within the browser where default setting for new sites being launched is normal or private.. and that is "Ask me" (so that browser prompts me which I want if I'm not already in a normal or private browsing session.

### How do you know that this problem exists today? Why is this important?
The current approach is an "everything private mode" or "nothing private mode" split. If a user wants to launch a particular site as private, but otherwise browse normally, where that site is triggered from another app by way of intent they have to switch to firefox first, set the default to launch private, then switch back to launching app, trigger the intent, then reset the default in Firefox back to "normal".

### Who will benefit from it?
Users who wish to selectively engage private mode on sites launched from outside the browser by other apps, rather than an all or nothing approach.

**Comment by liuche** [comment]
Thanks for filing this issue! We originally tried this back in October using app-aliases, but ran into problems with Android 5 & 6 not being able to use "Default Browser" functionality. We may revisit this later, because it's clearly a great feature to have! but for now, please take a look at the linked issues #5742 and #5972.
