### ISSUE TITLE
[Bug] long pressing/clicking with a mouse doesn't bring up the context menu so I can't open links in a new tab

### ISSUE THREAD

**Issue by isaacschicker** [mozilla-mobile/fenix#14412]
## Steps to reproduce
Hook a mouse a mouse up to an android device (phone, tablet, laptop, SBC, whatever) and long press/click on a link in firefox.

### Expected behavior
Long pressing/clicking on a link should cause a context menu to pop-up allowing you to do things like open the link in a new tab. This is the way it worked in the previous version of firefox.

### Actual behavior
The menu does not pop-up, nothing happens.

### Device information

* Android device: ?
lenovo T440p laptop running the Bliss ROM 

* Fenix version: ?
79.0.5 (Build #2015758623)

### Additional Information

On my phone (running android 7 or so) long pressing on a link with a finger on a link brings up the expected context menu, long pressing/clicking with a mouse does not bring up the context menu.

My laptop (the one running android) does not have a touchscreen so poking things with my finger will not do anything, this mouse issue leaves me with no way to open a link in a new tab.

I should also mention that right clicking on a link with a mouse does not bring up a context menu either (this feature has not worked since quite a few versions back).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5858)

**Comment by codelalala** [comment]
I encountered the same bug on my device.

Device information

    Android device: Samsung Galaxy Tab S7+
    Android 10

    Fenix version: 
    Nightly 210111 17:02 (Build #2015786763)

**Comment by X-m7** [comment]
I think it would be better to just use right click in the first place, especially since the browser already seems to recognise the presence of a mouse (I can hover over usernames, issue numbers and whatnot to see a preview just like on desktop for example). For reference I'm currently running version 85.1.3, build 2015792287.

**Comment by gaul** [comment]
It seems that handling right click requires intercepting `KEYCODE_BACK` from `InputDevice.SOURCE_MOUSE`:

https://stackoverflow.com/questions/10041295/android-usb-mouse-right-click-correct-behaviour-ics/29311126#29311126

Assuming that this is true, we should be able to address this as part of keyboard shortcuts:

https://github.com/mozilla-mobile/android-components/issues/1978

**Comment by X-m7** [comment]
This still applies to Firefox 92.1.1 (Build #2015832087), the behaviour has not changed.

**Comment by X-m7** [comment]
Still a problem for me on version 98.3.0 (Build #2015870335).

**Comment by CSdiscoveries** [comment]
I have this issue as well. I hope it actually gets fixed...

**Comment by thedward** [comment]
I'm still experiencing this problem in Firefox Nightly¹

¹ `104.0a1 (Build #2015889675), da48ff609+ AC: 104.0.20220630143048,
0035fe83f8 GV: 104.0a1-20220630095519
AS: 93.5.0 2022-07-01T17:11:56.172619`

**Comment by rovitotv** [comment]
I have the exact same problem....when my phone is connected to a monitor, keyboard, and mouse then I need to be able to click on a link and select "open in new tab".  It works great in Chrome but I don't want to give up my privacy and I would much prefer to use Firefox. 

The version I have is here:

`102.2.1 (Build #2015891003), 10fdf130c+
AC: 102.0.14, cd19f9a6c5
GV: 102.0.1-20220705093820
AS: 93.1.0`

Running a Samsung S10+ with Android 12.

**Comment by ShapeShifter499** [comment]
Samsung Z Fold 4 user here. I have also the same issue, if using a mouse and keyboard. There is no easy way to open a link on page in a new tab. The mouse long click doesn't seem to work

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1805341

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
