### ISSUE TITLE
Option to hide Switch to tabs

### ISSUE THREAD

**Issue by wedgerage** [mozilla-mobile/fenix#14413]
### What is the user problem or growth opportunity you want to see solved?

Auto updated to 79.0.5 (Build #2015758619).
Then there is no option to hide Switch to tabs when I type in the address bar. There is no option to disable this in the settings.

### Who will benefit from it?

Everyone who do not want to see previously opened tabs as they type.

**Comment by ekager** [comment]
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/9269
