### ISSUE TITLE
[Feature Request] Bookmarking the current page and then choosing to edit its details should not stop the page's currently-playing media elements

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#14411]
### What is the user problem or growth opportunity you want to see solved?

If I have just bookmarked a page and I choose to make minor changes to the new bookmark, such as setting its parent folder, Fenix will halt any media that is currently playing on the page. It should not do this.

### How do you know that this problem exists today? Why is this important?

Let's use a real-world example. Suppose I go to a page that has media, such as [an official music upload on YouTube](https://www.youtube.com/watch?v=tv7yHglIDsc). The media begins playing (this happens automatically if you navigate from one YouTube video directly to another within the same tab) and I bookmark the page because I like the song and would like to listen to it again later. Upon doing so I am immediately presented with the option to edit the bookmark, and I tap this option (perhaps to place it under a bookmark folder). The media will not play in the background while I edit the bookmark, but will instead be suddenly stopped by the browser.

There are two sides to this.

**"I don't want the media to be interrupted:"** If I bookmark a page, then I probably either like the page or in some way find it useful. If the page has audio or video on it, then even if I don't actively *like* the media, I at least don't find it *objectionable*, else I wouldn't want to bookmark the page. If I have left the media playing while bookmarking the page and then choose to edit the bookmark, it's reasonable to assume that I would like for the media to continue to play, else I would have taken action to stop it myself.

**"I don't want to miss the media:"** If I were watching video content (and of course, audio-only uploads on YouTube aren't easily distinguishable from video as far as a browser is concerned), then opening the modal for editing a bookmark would leave me unable to see the content. If the content continued to play in the background, then I would end up missing it. I could take some action to pause the media, so that I can then resume it once I'm able to see it again, but that would require me to *do things.* That sucks? I guess? Is the thinking here?

If someone doesn't want to miss part of a page's currently playing media while bookmarking it, then it should be incumbent upon them to pause the media: let the user decide what they want and give them the means to act on that decision.

### Who will benefit from it?

People who bookmark pages that play media, especially if they browse sites that have some sort of algorithm for surfacing media content that a user is likely to enjoy.

**Comment by liuche** [comment]
We may not be able to do much about this immediately - changing from the browser view to settings is switching fragments, and the contents of the other fragments won't be active. Could spin media out into a separate thread but that would require some significant changes.
