### ISSUE TITLE
Revert back to previous version

### ISSUE THREAD

**Issue by thepooptoob** [mozilla-mobile/fenix#14418]
Let's not beat around the bush here. The new update is horrid and half-baked.

This new version is missing 90% of necessary features on top of the features the previous version was already missing. You've pulled the rug out from under your users by dumping on them a terrible version with minimal features and severely lacking usability. If you pulled this crap to get more testers to help you add more features to this version then maybe you should have wondered why you didn't get enough in the beta app.

Seriously. This is an embarrassment of an update and you should be ashamed of yourselves.

**Comment by Dunexus** [comment]
Let's not beat around the bush here. This comment is not constructive and insulting.

It doesn't highlight any issue with the new version nor improvement that can be done and is insulting of crap the hard work of a very small team.

Seriously. This is an embarrassment of a comment and you should be ashamed of yourself.

PS: Feedback is always welcome as long as it is constructive and help to improve the product.

**Comment by thepooptoob** [comment]
> Let's not beat around the bush here. This comment is not constructive and insulting.
> 
> It doesn't highlight any issue with the new version nor improvement that can be done and is insulting of crap the hard work of a very small team.
> 
> Seriously. This is an embarrassment of a comment and you should be ashamed of yourself.
> 
> PS: Feedback is always welcome as long as it is constructive and help to improve the product.

Let's not beat around the bush here. You're a moron and you were childishly insulted by someone pointing out the massive train-wreck that is this new version. Not constructive? What, did "half-baked," "minimal features," and "lacking usability" not do it for you? What, do you want me to read off the laundry list of stuff wrong with this god foresaken update? No. The update is garbage. That's the criticism. Grow up.
