### ISSUE TITLE
[Feature Request] Prevent users getting stuck on empty tab screen

### ISSUE THREAD

**Issue by mnatator** [mozilla-mobile/fenix#14410]
### What is the user problem or growth opportunity you want to see solved?
When a user presses the back button one time too many, he returns to a fire fox empty tab screen. It is impossible to move forward (back to the page the user came from) as this screens does not have navigation buttons (even in the  dot dot dot menu).
### How do you know that this problem exists today? Why is this important?
It mainly exists for users who enter Firefox through a link they clicked in another app. They expect to either exit the app when pressing the back button, or exit a tab. They do not expect to go to a place (the firefox empty tab screen) and be stuck there.
### Who will benefit from it?
Everyone who presses the back button while on the page they entered Firefox with.

**Comment by liuche** [comment]
This is going to be the same fix as #14358 so I'm going to dupe.
