### ISSUE TITLE
Bring back Most visited smart bookmark

### ISSUE THREAD

**Issue by polychloriert** [mozilla-mobile/fenix#14419]
### What is the user problem or growth opportunity you want to see solved?
The 'Most visited' smart bookmark on an empty tab was most useful. No it's gone and could, supposedly, ony be reactivated using about:config - which is also deactivated.

### How do you know that this problem exists today? Why is this important?
Current version removed it.

### Who will benefit from it?
Everyone who liked FF (mobile) so far.

**Comment by cadeyrn** [comment]
Most visited websites are already implemented as top sites in the Nightly version.

**Comment by liuche** [comment]
Yes, please see Nightly for this feature.
