### ISSUE TITLE
Restore quality of life features to daylight

### ISSUE THREAD

**Issue by mobileNetscapeUser** [mozilla-mobile/fenix#14429]
Thank you for the great work on the daylight release.  I can see the tremendous progress made in the browser.  However, there are a few features that I miss from pre-daylight release.

* Only load images over wifi - This was great to save data since I don't have an unlimited plan

* Ability to easily add search from most web pages - I was able to select a search field and add it to the firefox search list.  This was nice to be able to add specific stores or sites easily to the search configuration.  That way I didn't have to go to the store home page first then search.

* Home page in private mode - I like the information about the common myths about private browsing.  But, I used to have the home page show my bookmarks which were in a certain order so that the most frequent were at the top.  With "top sites", I wouldn't have to do that, but I don't see that in private browsing mode.

* Bookmark organization - Maybe this is already there, but I can't seem to reorder by bookmarks.  When they were imported, the order is different than I had set before.

* Long press back button - The long press of the back button to show the history of the tab was nice to go back to a specific page.

Once again, thank you for all your hard work.  Take care and stay safe.

**Comment by cadeyrn** [comment]
Please open one issue per feature request otherwise it's not possible for Mozilla to label your individual feature requests.

**Comment by s-ankur** [comment]
Hi, please 👍 the below features if you find them useful 
1. Duplicate of #810
2. Dupe #6315 
3. New issue
4. #4348
5. Already added, wait for update

**Comment by mobileNetscapeUser** [comment]
Thank you for the quick responses.  Since it appears only 1 issue is not a duplicate, should I still write a new issue or leave this issue to follow it?

Thank you.

**Comment by s-ankur** [comment]
Better create a new one. You can close this one

**Comment by mobileNetscapeUser** [comment]
I am closing this request due to most of it being a duplicate of other issues.  I have added issue #14498 to cover the 3rd item.  I've never created an issue before so thank you for guiding me in the proper procedure.
