### ISSUE TITLE
[Bug] Enable access to settings (about:config)

### ISSUE THREAD

**Issue by polychloriert** [mozilla-mobile/fenix#14420]
## Steps to reproduce
Open about:config

### Expected behavior
Access to advanced features

### Actual behavior
Some error message

I guess this topic is just annoying to you guys, but this is a major deal breaker. Removing these options puts FF mobile on the same level as the other useless mobile browsers. The only thing keeping me from uninstalling FF mobile is uBlock Origin and I assume it won't be long until you disable that as well. Sorry for the snarky tone, but this situation is annoying as hell.

**Comment by amkcpu** [comment]
about:config is available on the Nightly channel (https://play.google.com/store/apps/details?id=org.mozilla.fenix).
For enabling about:config on the release channel, see #7865.

**Comment by liuche** [comment]
closing as dupe
