### ISSUE TITLE
 open/share directly in private mode 

### ISSUE THREAD

**Issue by liar666** [mozilla-mobile/fenix#14424]
### What is the user problem or growth opportunity you want to see solved?

Being able to actually protect users' privacy by allowing them to actually use the private mode.

Currently, to use the private mode, you have to open FF in "normal"/unsafe mode, move to private browsing (top of the page), then click "add tab"/+ button (bottom of the page), then enter the URL. This very inefficient UX makes the private mode very far from accessible, thus reserved to a perseverant elite. This does not help improve privacy/security for all final users.

Currently, users cannot open a URL directly in private mode or "share" a URL from another app and open it directly in private mode.

This forces users that want to open a link (for example one with tracking info from an other app - e.g. email app like K9, or RSS reader like Aggregator) to open it in "normal"/unsafe mode and be tracked.
 
Also, as it is not possible to move a "normal"/unsafe tab to private mode, this forces the user to copy the URL, move to private mode (top of the page), open a new tab (bottom of the page), then paste the URL. Very inconvenient and inefficient!

Having GUI "open/share in private mode" shortcuts/icons/links in FF/Android, similar as the CLI options in FF/Desktop (`-private` & `      -private-toggle` would be of a great use.

### How do you know that this problem exists today? Why is this important?

Because I experience it every day.

It would help improve users' privacy on the web in everyday life setting.

### Who will benefit from it?

everybody

**Comment by s-ankur** [comment]
You can go to Settings /Private Browsing/Open link in private tab which will open links from other apps in private tabs

**Comment by liar666** [comment]
Thanks for your tip. However, this solution would make ALL links open into private mode. What I'm looking for is a way to have the choice to open a specific link in private mode, the rest being opened in normal mode by default.
Indeed, issue #12452 is closer to what I'm looking for, but having to answer a question everytime a link is opened would be a PitA for almost all users. Keeping the default to normal FF mode and having the ability to select another shortcut (that would start FF with option -private) would be a beter solution.

**Comment by liuche** [comment]
Thanks for filing this issue! We originally tried this back in October using app-aliases, but ran into problems with Android 5 & 6 not being able to use "Default Browser" functionality. We may revisit this later, because it's clearly a great feature to have! but for now, please take a look at the linked issues #5742 and #5972.
