### ISSUE TITLE
Bouton "version ordinateur" ne reste pas

### ISSUE THREAD

**Issue by Thierry49** [mozilla-mobile/fenix#14426]
Bonjour. Le bouton version ordinateur
![IMG_20200829_102209](https://user-images.githubusercontent.com/70429724/91632508-91b9ae80-e9e1-11ea-8646-b67be8b81ed9.jpg)
Ne reste pas coché après une mise en veille du téléphone.
Et il est ensuite impossible à re cocher.

**Comment by cadeyrn** [comment]
Could you please translate your request into English? Otherwise it's not possible for many people to understand your request. English is spoken all around the world that's why people communicate in English in global projects.

**Comment by B0pol** [comment]
The "desktop version" doesn't stay enabled after phone lock, and there is no way to enable it again after. I can't reproduce in nightly and we don't have info (browser version, phone) from OP

**Comment by s-ankur** [comment]
Cant reproduce in main browser either, maybe a step is missing?

**Comment by Thierry49** [comment]
Bonjour,
sur mon redminote 7 (miui 11global 11.0.1) avec la dernière version de firefox android (79.0.5 build #2015758619), j'ai 3 pages d'ouverte avec l'option "Version  ordinateur". 
Lorsque mon téléphone s'éteint et après un certains moment, mes 3 onglets ont perdu leur option cochée.
cela m'arrive systématiquement. j'utilise en ce moment Chrome en attendant que cela fonctionne normalement.
(translate by google).

**Comment by s-ankur** [comment]
Yes, I can reproduce this actually. Desktop Mode does not persist after force close even in nightly

**Comment by s-ankur** [comment]
Duplicate of  #11552

**Comment by liuche** [comment]
Merci, please follow in the linked bug #1152

**Comment by Thierry49** [comment]
merci beaucoup
