### ISSUE TITLE
[Bug] ETP causes unresponsive Chat Button

### ISSUE THREAD

**Issue by ShalokShalom** [mozilla-mobile/fenix#14423]
## Steps to reproduce
Visit 
https://www.visible.com/connect
Click on this button
![Screenshot_2020-08-29-09-47-36-45](https://user-images.githubusercontent.com/6344099/91631807-c840fa80-e9dc-11ea-991d-40e415af82c8.jpg)

### Expected behavior
Chat window pops up
### Actual behavior
Doesnt 
### Device information

* Android device: RealmeX
* Fenix version: 
![Screenshot_2020-08-29-09-49-15-02_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/6344099/91631828-f0c8f480-e9dc-11ea-9d50-df7f3f23cea9.jpg)

**Comment by s-ankur** [comment]
Issue reproduced on nightly as well. Disabling Extended Tracking Protection and UBlock Origin allows it to work

**Comment by ShalokShalom** [comment]
To me, its enough to disable the extending tracking, uBlock doesnt block it.

**Comment by ShalokShalom** [comment]
They have a different chat now, might be resolved, I switched to Vivaldi.
