### ISSUE TITLE
Organise bookmarks by date added

### ISSUE THREAD

**Issue by UserLP3** [mozilla-mobile/fenix#14430]
My bookmarks have been transferred from the old Firefox but are in no discernable order, nor is there a way to order them by date added. This is inconvenient to say the least and makes no sense. Please fix/revert.

**Comment by Dunexus** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/13426

**Comment by Shadowspear123** [comment]
Yes, at least make it the way it was on the old firefox mobile, or add the ability to sort the bookmarks.

**Comment by Shadowspear123** [comment]
This is still an issue.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/4348
