### ISSUE TITLE
[Bug] Failed download images from pixiv.net

### ISSUE THREAD

**Issue by KenFangidae** [mozilla-mobile/fenix#14435]
## Steps to reproduce
open the image you want to download

### Expected behavior
images can be saved

### Actual behavior
Download Failed

### Device information

* Android device: ?
* Fenix version: Nightly 200829 06:05 (Build #2015760753)
AC: 57.0.20200827190112, 91f7bcbca
GV: 82.0a1-20200827093043
AS: 61.0.13

**Comment by Amejia481** [comment]
We are getting a 403 HTTP error when we try to download an image. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1662235 for the GV team to take a look.

STR

1. Go to https://www.pixiv.net/en/artworks/84011474
2. Long press on the image. 
3. Click on the "Save image" option.

**Comment by DavidJCobb** [comment]
Something could've changed recently, but when I used to browse Pixiv I noticed that they check the Referer header when you load artwork files. Y'all may want to check whether Firefox is sending that for Save Image the same way it would when the image is embedded in the page normally.
