### ISSUE TITLE
[Performance issue] looping-squares.superhi.com

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#14431]
Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1662326

## Steps to reproduce
Open https://looping-squares.superhi.com/
### Expected behavior
Open in chrome Android or Desktop Firefox to see expected behaviour: it flips once, pause one second, repeat
### Actual behavior
It's really slow, the browser doesn't respond, it's hard to close the tab and go on
### Device information

* Android device: Pocophone F1
* Fenix version: Nightly 200829 06:05

**Comment by mcomella** [comment]
This is a platform issue so we'll track upstream at the bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1662326
