### ISSUE TITLE
[Bug] webm + vp9 video not supported

### ISSUE THREAD

**Issue by sbrl** [mozilla-mobile/fenix#14436]
## Steps to reproduce
1. Open Firefox for Android
2. Visit [this video](https://starbeamrainbowlabs.com/blog/images/20200831-mazes/sidebyside.webm)
3. See error

### Expected behavior
The video plays normally

### Actual behavior
Sometimes it claims the video is corrupt; others it claims the video format is unsupported.

Screenshot:

![](https://imgur.com/vJSiX0G.png)

The video plays fine on Desktop.

### Device information

Firefox for android version: 80.0.1-beta.2 (Build #2015758611)
AC: 54.0.2, ec7e84aa7
GV: 80.0-20200211133449
AS: 61.0.10
Tuesday 8/18 @ 2:02AM

Devices tested:

Nokia 7.1 TA-1085 (hardware version 3.0) with Android 10 (security patch level 1 July 2020)
Samsung SM-T580 with Android 8.1.0 (security patch level 1 April 2020)

![](https://imgur.com/A4hckgD.png)

**Comment by yoasif** [comment]
Reproducible on Fennec. "Plays" on Chrome but screen stays black (video is not totally black). Video does not play correctly with VLC on my device either. 

@sbrl does this video play anywhere correctly on your device?

**Comment by kbrosnan** [comment]
Tracked by bz-1433382

**Comment by yump** [comment]
`ffprobe` says

    Input #0, matroska,webm, from '/tmp/sidebyside.webm':
      Metadata:
        ENCODER         : Lavf58.29.100
      Duration: 00:00:10.42, start: 0.000000, bitrate: 3441 kb/s
        Stream #0:0: Video: vp9 (Profile 0), yuv420p(tv), 5760x1080, SAR 1:1 DAR 16:3, 24 fps, 24 tbr, 1k tbn, 1k tbc (default)
        Metadata:
          ENCODER         : Lavc58.54.100 libvpx-vp9
          DURATION        : 00:00:10.417000000

Something that stands out is the very large horizontal resolution.  The widest common format is 3840x2160, which could be accommodated in a hardware limit of 4096 columns.  The SoC in the Nokia, the Qualcomm 636, [claims](https://www.qualcomm.com/products/snapdragon-636-mobile-platform), "Video Playback: Up to 4K Ultra HD video playback".  The Samsung [says](https://www.samsung.com/semiconductor/minisite/exynos/products/mobileprocessor/exynos-7-octa-7870/#), "Full HD 60fps encoding and decoding with HEVC (H.265), H.264, VP8 Codec".

Can you play this video in VLC? With the various hardware acceleration settings (hamburger menu -> settings -> Hardware Acceleration)?

**Comment by sbrl** [comment]
Yeah, I can play it in VLC. on Ubuntu 20.04.

Hrm, now that you mention the horizontal resolution that could be the problem. I've re-encoded a [new version of the video](https://starbeamrainbowlabs.com/blog/images/20200831-mazes/sidebyside-small.webm) with a smaller horizontal resolution (using the exact same method as above, just with smaller input videos), and it appears to work as intended. Output from `ffprobe`:

```
Input #0, matroska,webm, from 'sidebyside-small.webm':
  Metadata:
    ENCODER         : Lavf58.29.100
  Duration: 00:00:10.42, start: 0.000000, bitrate: 715 kb/s
    Stream #0:0: Video: vp9 (Profile 0), yuv420p(tv), 1440x270, SAR 1:1 DAR 16:3, 24 fps, 24 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      ENCODER         : Lavc58.54.100 libvpx-vp9
      DURATION        : 00:00:10.417000000
```

So I think the problem isn't that it doesn't support webm + vp9, but rather that the error message is deceptive in saying that the video is "corrupt", when it isn't really (it's just that the frame size of the video is too large for the device). Perhaps in this case the error message could be updated to avoid confusion?
