### ISSUE TITLE
[Bug] Tabs containing an iframe have their title set to that of the iframe

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#14433]
bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1662327

## Steps to reproduce
Go to a page that embeds an iframe.

### Expected behavior
The title of the tab is that of the actual page you're on.

### Actual behavior
The title of the page is that of the embedded iframe. For example on Rotten Tomatoes, the title of the page becomes "Disqus Realtime Notification".

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 200829 06:05 (Build #2015760755)
AC: 57.0.20200827190112, 91f7bcbca
GV: 82.0a1-20200827093043
AS: 61.0.13

**Comment by mohibo** [comment]
and still no response

**Comment by mobd** [comment]
The bug has been [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1662327)  in geckoview already, so it should get solved once nightly pulls the new version.

**Comment by mobd** [comment]
Seems to be fixed in the latest update, so I'm closing this
