### ISSUE TITLE
FNX3-15567 ⁃ [Bug] alignment of toggles in settings

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1444]
### Steps to reproduce
1. open settings

### Expected behavior
all toggles should be on the same position on the x-asis

### Actual behavior
the remote debugging toggle is wrong positioned

![fenix](https://user-images.githubusercontent.com/1100614/55671301-22dd3200-588f-11e9-8d84-efc6fc6fd53b.png)

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision d43e902b4433348da285a2978918ccfefc389014

**Comment by ekager** [comment]
Closing because we are generic Android `SwitchPreference` here and this is the default. If they were all turned off, they would be aligned.

**Comment by cadeyrn** [comment]
oops, makes sense. Thank you for showing me the obvious. 😂
