### ISSUE TITLE
Allow opening of links from other apps without bringing Firefox to foreground

### ISSUE THREAD

**Issue by mystiquewolf** [mozilla-mobile/fenix#14445]
### What is the user problem or growth opportunity you want to see solved?
User wants to have some links for later reading from an app inside .
### How do you know that this problem exists today? Why is this important?
Exists because is not implemented. It is useful, don't know if important
### Who will benefit from it?
All users who want to save links for later, can just click some links inside a 3rd party app and collect them. Double clicking a link will open it ASAP.

**Comment by cadeyrn** [comment]
Duplicate of #470.

**Comment by kbrosnan** [comment]
Closing as a duplicate
