### ISSUE TITLE
[Bug] 0/0 items when fast clicking on up down arrows in find in page

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14448]
## Steps to reproduce
Open find in page
Type a letter or two
Click on the up or down arrow multiple times in quick succession
### Expected behavior
The correct count
### Actual behavior
0/0 as the count
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200829-222141_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/91642087-1b9b6300-ea46-11ea-8573-ce788b23decb.png)

**Comment by sflorean** [comment]
Dupe of #7953.
