### ISSUE TITLE
[Bug] Undo tab deletion sometimes leads to unrecoverable blank tab and no web content

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#14459]
## Steps to reproduce
1. Open more than 1 tab
2. Delete one tab via the tabs tray
3. Press "Undo" in snackbar

### Expected behavior
Tab restores

### Actual behavior
Tab sometimes blanks out and is unrecoverable. Refresh and app restart don't help.

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 

![ezgif com-video-to-gif(10)](https://user-images.githubusercontent.com/25442310/91644828-d2c7b800-ea0d-11ea-96d9-c291a513049a.gif)

**Comment by s-ankur** [comment]
I saw the same issue here https://github.com/mozilla-mobile/fenix/issues/14297

**Comment by pocmo** [comment]
I was debugging the same issue today. I was rewriting the way we restore crashed tabs. When restoring the last session state into a new GeckoSession then it turns into this white zombie.
When I kill the app and the same state gets restored then everything's fine.

Interestingly that happens every time in Fenix... but never in sample browser.

@snorp @agi Is this related to the white page bug you are fixing? I don't see anything in the logs, so maybe it's something different.

**Comment by pocmo** [comment]
I only tested with nightly, I wonder if that happens with beta or release too. @ekager did you test that?

**Comment by ekager** [comment]
Just tried and couldn't repro in Beta

**Comment by liuche** [comment]
Beta is currently on 80, which had the Session code (that was causing white tab) backed out.

**Comment by pocmo** [comment]
I'll take another look at this today. If needed I'll file a separate GV bug.

**Comment by pocmo** [comment]
Filed a GeckoView bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1662400

**Comment by pocmo** [comment]
@ekager I noticed that in my case (restoring tabs after a crash) only the currently selected tab turns into this zombie. For other tabs it works just fine. Is this something you are seeing too?

**Comment by pocmo** [comment]
We found the issue and will provide a fix in AC.

**Comment by liuche** [comment]
https://github.com/mozilla-mobile/android-components/pull/8310
https://github.com/mozilla-mobile/android-components/pull/8320

**Comment by sflorean** [comment]
Tested on Nightly 9/16 following the steps and we didn't encounter any issue. 
Device: Google Pixel 3 (Android 11).

@s-ankur do you still experience this issue on Nightly?
