### ISSUE TITLE
[Bug] Comment bodies are not displayed in Reddit?

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#14456]
## Steps to reproduce
Go to https://www.reddit.com/r/firefox/comments/ih9vmb/firefox_for_android_fenix_79_release_fennec_is

### Expected behavior
After a while, comments are visible below the posts (I mean, bodies of contents).

### Actual behavior
Only the tree of comments is visible, but not the texts. It works well in Fennec though.

![image](https://user-images.githubusercontent.com/218971/91643998-61512f00-ea38-11ea-8cbb-61b3aa055b52.png)

But maybe it is I who have missed something here? :)

### Device information

* Android device: Redmi Note 7
* Fenix version: nightly #2015760755

**Comment by yoasif** [comment]
Can't reproduce on my end. Any add-ons enabled?

**Comment by klint** [comment]
No, all add-ons are disabled, as well as tracking protection. But it works well in private mode.

**Comment by klint** [comment]
It was somehow related to cookies. I deleted them all and it behaves correctly now. Closing the issue 😊
