### ISSUE TITLE
Feature request: Add different layout(s) for tab tray

### ISSUE THREAD

**Issue by KryptonicDragon** [mozilla-mobile/fenix#14457]
New update is cool, but I'd like to have the tab tray show a grid layout (two columns) as it did before. Navigating through all my tabs in a single-column list (especially when the tab tray doesn't even take up the whole screen anymore!!!) is too cumbersome for me.

I may be imagining this, but I remember the previous version allowing you to change between the one- and two-column layouts for the tab tray. Having this feature back would be great.

**Comment by cadeyrn** [comment]
Duplicate of #13098.

**Comment by kbrosnan** [comment]
Closing as a duplicate
