### ISSUE TITLE
Install Addons file (.xpi) via File Manager

### ISSUE THREAD

**Issue by lo9-u** [mozilla-mobile/fenix#14452]
### What is the user problem or growth opportunity you want to see solved?

The user problem is that there is no simple and fast way for users to install downloaded addons (.xpi) via integrated file manager on Android e.g. with Files (com.android.documentsui). Firefox Nightly (29 August 2020) is generally not displayed when an .xpi file in Files is clicked.

Here are .xpi files to test.
https://github.com/gorhill/uBlock/releases/tag/1.29.2
https://addons.mozilla.org/firefox/downloads/file/3629683/ublock_origin-1.29.2-an+fx.xpi

### How do you know that this problem exists today? Why is this important?

I know Firefox Desktop version and Firefox Desktop generally has the ability to install Addons file (.xpi) via File Manager.

### Who will benefit from it?
Everyone will benefit. The solution should always be simple, fast and lightweight.

For example, if users have an addons file (.xpi), they can open the File Manager app and tap on the .xpi file.
Then users select Firefox (Android) and a small installation window appears and they can install the addon or not.

**Comment by cadeyrn** [comment]
There are already more than enough issues about this. Please see #14034 for the next steps of expanding the add-on support.

**Comment by lo9-u** [comment]
@liuche @cadeyrn 

What does that mean exactly?

I read it through, but there were no details or that work is in progress to install the .xpi file via File Manager on Android.

Why was my report closed? This is a new feature request.

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/12655
https://github.com/mozilla-mobile/fenix/issues/13059
https://github.com/mozilla-mobile/fenix/issues/14339

https://github.com/mozilla-mobile/fenix/issues/14452
https://github.com/mozilla-mobile/fenix/issues/14489
https://github.com/mozilla-mobile/fenix/issues/15154
