### ISSUE TITLE
[Bug] Keyboard is not dismissed when filling link from clipboard (regression)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14458]
## Steps to reproduce

1. copy url to clipboard
2. tap address bar
3. remove any text if present
4. tap "fill link from clipboard" suggestion

### Expected behavior

Fenix navigates to page, keyboard is dismissed. 

### Actual behavior

Keyboard stays on page as page loads and remains after page is loaded. 

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 200829 06:05 (Build #2015760755)
AC: 57.0.20200827190112, 91f7bcbca
GV: 82.0a1-20200827093043
AS: 61.0.13

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200923 06:02 GV 82.0a1 from 9/23 with Pixel 2 (Android 9).
I will remove the qa:needed label and close this issue.
