### ISSUE TITLE
[Bug] It's possible for reader mode icon to be blue without reader mode

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14453]
## Steps to reproduce
Open a website that has reader mode
While it loads, quickly click on the reader mode icon
### Expected behavior
Reader mode activates
### Actual behavior
It does not. But the icon shows blue
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly
![Screenshot_20200829-232418_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/91643238-0f67d380-ea4f-11ea-8dc6-687b11822b7d.png)

**Comment by Diana-Rus** [comment]
Reproducible on Firefox Preview Beta 81.1.0-beta.1 with Google Pixel 3XL (A9).
