### ISSUE TITLE
[Bug] Selecting text pops up "Bing search" instead of my configured search engine

### ISSUE THREAD

**Issue by aarongolliver** [mozilla-mobile/fenix#14469]
I have Google set as my default search provider. I deleted Bing entirely. Yet when I select text it wants to send me to Bing.

You should not force me to use Bing, especially when I've explicitly disabled it. There appears to be no configuration option to disable or customize this "feature".

## Steps to reproduce
Select text

### Expected behavior
It shows "search", or "google search"

### Actual behavior
It shows "Bing search"

### Device information

* Android device: pixel 4 xl
* Fenix version: 
79.0.5 (Build #2015758619)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10

**Comment by kbrosnan** [comment]
This is probably added by another app on the device. Are you able to screenshot this? What happens when you tap the bing search?

**Comment by aarongolliver** [comment]
https://www.androidauthority.com/microsoft-bing-search-in-outlook-android-1137564/
