### ISSUE TITLE
[Bug] Screenshots can be taken in private mode even if its turned off from settings.

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14463]
## Steps to reproduce
Screenshots can be taken even if its turned off from the settings option.
### Expected behavior
Disable taking screenshots
### Actual behavior
Screenshots are captured instead
### Device information
Android 9

*Fenix version: 79.0.5 and Firefox beta 80.0.1.beta-2*

80.0.1-beta.2 (Build #2015758609)

***Screenshot disabled***

![Screenshot_2020-08-29-14-05-35](https://user-images.githubusercontent.com/51329626/91645716-f6ebbf00-ea36-11ea-88ad-22fff21981e7.png)

***Screenshot taken with screenshot disabled***
![Screenshot_2020-08-29-14-06-22](https://user-images.githubusercontent.com/51329626/91645731-2ac6e480-ea37-11ea-8aa6-dc08a0ad70c9.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/8 Nightly build, on Beta 86.0.0-beta.2, and on Firefox Daylight 85.1.1 with Samsung Galaxy Note 8 (Android 9).
