### ISSUE TITLE
[Bug]If toolbar is set to bottom, it overlaps the bottom contents/rule-sets of about:config

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14466]
### Tested this on Firefox 80.0.1-beta.2 (Build #2015758609)
If the toolbar is set to bottom from the settings menu instead of top, the toolbar seemed to cover the bottom contents/rulesets of about:config. Setting the toolbar to the top seems like a solution for now on about:config.

### Expected behavior
Toolbar shouldn't cover up page contents

### Actual behavior
Toolbar covers page contents

### Device information
Android 5.1.1 resolution 480x800

***Top toolbar doesn't cover content***

![Screenshot_2020-08-29-00-03-00](https://user-images.githubusercontent.com/51329626/91646633-cd379580-ea40-11ea-9a23-b453c77a8b16.png)

***Bottom toolbar covers last rulesets***

![Screenshot_2020-08-29-09-36-45](https://user-images.githubusercontent.com/51329626/91646640-d9235780-ea40-11ea-8caa-5eedf02f505e.png)

**Comment by ale82to** [comment]
same issue for ever please give fixed bottom toolbar option asap!

**Comment by samiuljoy** [comment]
Nightly versions fixed the issue.
