### ISSUE TITLE
[Bug] Download fails

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14461]
### Tried this with Firefox beta 80.0.1.beta-2 and Firefox 79.0.5
80.0.1-beta.2 (Build #2015758609)
### Expected behavior
Downloads were suppossed to be successful.
### Actual behavior
Download fails 

**A demo link as a reference
https://packages.debian.org/buster/i386/fastboot/download**

### Device information
Android 9 2gb ram
***Note: The screenshot was taken before going into Airplane mode***

![Screenshot_2020-08-29-13-47-52](https://user-images.githubusercontent.com/51329626/91645540-5779fc80-ea35-11ea-9d6a-4cd65346eee6.png)

**Comment by hwinnemoe** [comment]
Which of the links do you use?

**Comment by samiuljoy** [comment]
> Which of the links do you use?

I tried https://ftp.debian.org/debian. Not only on Debian, other sites showed me the same failed results.

**Comment by hwinnemoe** [comment]
I get an Error code: SSL_ERROR_BAD_CERT_DOMAIN from that domain now, maybe a site issue.

**Comment by samiuljoy** [comment]
> I get an Error code: SSL_ERROR_BAD_CERT_DOMAIN from that domain now, maybe a site issue.

I was able to download on Chrome, and Firefox 68.11.0 and on my desktop too, except for Firefox 79.0.5 and Firefox 80.0.1 beta-2 I added some screenshots 

### Chrome

![Screenshot_2020-08-29-14-50-37](https://user-images.githubusercontent.com/51329626/91646347-a4fa6780-ea3d-11ea-848a-1f428120503e.png)

### Firefox 68.11.0

![Screenshot_2020-08-29-14-52-13](https://user-images.githubusercontent.com/51329626/91646355-bf344580-ea3d-11ea-8e6c-21e8d5cc4c3f.png)
![Screenshot_2020-08-29-14-52-24](https://user-images.githubusercontent.com/51329626/91646360-c52a2680-ea3d-11ea-9e1e-7cfe3b4c7fd4.png)

**Comment by samiuljoy** [comment]
> I get an Error code: SSL_ERROR_BAD_CERT_DOMAIN from that domain now, maybe a site issue.

the links lead to http://ftp.debian.org/debian/pool/main/a/android-platform-system-core/fastboot_8.1.0+r23-5_i386.deb a debian file.

**Comment by eddie-LA** [comment]
Downloads fail on 3gpp and avi files too in volatile.org for example, but mp4 downloads work. Happens in both Release and Beta, other browsers download fine.

**Comment by samiuljoy** [comment]
> I get an Error code: SSL_ERROR_BAD_CERT_DOMAIN from that domain now, maybe a site issue.

Just found this out, if ***dom.security.https_only_mode*** is set to true, then Fenix will by default use https on all sites. Make sure that is set to false. For reference, try visiting http://puppylinux.com with ***dom.security.https_only_mode*** to true, and it'll say ssl error. I think this ruleset is super helpful. (:

**Comment by Amejia481** [comment]
@samiuljoy Would you mind sharing the log when you start the download? You could follow this steps to get the logs  listed [here](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information). Thank you in advance.

**Comment by Amejia481** [comment]
>  volatile.org

@ebalazs-sv would you mind sharing a specific case? Please if it's not much trouble include the specific link that you are trying to download

**Comment by Amejia481** [comment]
I wasn't able to reproduce on Pixel 3, with Android 10. QA help us to find the STR

**Comment by hwinnemoe** [comment]
I got some bad SSDL errors while trying to download the packages on https://packages.debian.org/buster/i386/fastboot/download on that specific day (2020-08-29) but it resolved itself. I also saw download errors due to bad SSL setups on my desktop (also Nightly) on that day. So we may be chasing a site issue at least in this specific case.

**Comment by Amejia481** [comment]
Thanks @hwinnemoe! Is the issue fixed for you too @samiuljoy?

**Comment by ebalazs-sv** [comment]
This issue is not reproducible on Nightly 200831 06:01 (Build #2015761137) GV 82.0a1, Beta 80.0.1-beta.2 (Build #2015758609) GV 80.0 from 8/18, Release 79.0.5 (Build #2015758617) GV 79.0.1 from 8/18 with Pixel 2 (Android 9), Motorola Moto G6 (Android 8).

**Comment by samiuljoy** [comment]
Apologies for a very late reply, here's the log file [gist](https://gist.githubusercontent.com/samiuljoy/5bafd75533dcd7d94e7d0a2a84bf2654/raw/99f605aec028d99be521927a338c7ef2ebeac64c/log.txt). The logs are from time I start Fenix nightly, click on download, and upto the failed download part. I have replaced my IP and location with "replacedforprivacy". 
Yesterday I downloaded Fenix 80.0.1 release version, and tried downloading and everything worked fine on the release version. I had issues with Beta and nightly versions only. Also, the downlaod link is a proper download link. People using Debian all over the world uses this to download files and work with them. I had no issues on other devices only on Beta and Nightly.

**Comment by samiuljoy** [comment]
A quick question, @Amejia481, looking back at the log files, it seemed to list my directories reccursively, also noticed that on about:config browser.cache.disk.filesystem_reported was set to 1. I tried reseting it, and the whoe ruleset got deleted. However, on reopenning the app, the ruleset was there with value=1. I wonder what that ruleset stands for.

**Comment by samiuljoy** [comment]
Okay, download seems to be working fine for me on 81.1.0-beta.2 (Build #2015761657). Earlier, release version 81.0.1 showed no download issues, however, the latest release 81.0.2 had download failed issues(for me).

***Successful download on 81.1.0-beta.2 (Build #2015761657)***

![Screenshot_২০২০-০৯-০৪-১২-৫৭-৫০](https://user-images.githubusercontent.com/51329626/92277423-77e90180-eee2-11ea-8f23-6f4b4da47570.png)

**Comment by samiuljoy** [comment]
***The same file that I tried to download the other day, shows successful on 81.1.0-beta.2 (Build #2015761657)***

![Screenshot_২০২০-০৯-০৪-১৩-১৮-৩২](https://user-images.githubusercontent.com/51329626/92278056-e24e7180-eee3-11ea-8f8d-023b16a0e9f7.png)

**Comment by Amejia481** [comment]
QA team could you please verify if this issue still persist on nightly ? Thanks in advance.

**Comment by ebalazs-sv** [comment]
I had tested this on the latest Nightly build 201021 with Pixel 2 (Android 9) and this is not reproducible.

Also, on the latest Beta 82.0.0-beta.6 from 10/16 and Release 82.1.1 from 10/21, there is a known issue regarding downloads https://github.com/mozilla-mobile/fenix/issues/15378, that I reproduce when downloading the packages on https://packages.debian.org/buster/i386/fastboot/download.

I will remove the qa:needed label for now.
