### ISSUE TITLE
Tab close and new tab buttons are too close

### ISSUE THREAD

**Issue by acetylsalicyl** [mozilla-mobile/fenix#14464]
It's very easy to close a tab instead of opening a new one. (or vice versa)
Maybe the open new tab button should be placed on the other side of the screen. (from right to the left)

(But this is only a small thing compared to the mess the new browser has caused... I'm seriously disappointed with this new browser.)

**Comment by ekager** [comment]
Closing because needs more information.

Please open a new issue with screenshots or more information
