### ISSUE TITLE
Give option to disable "WiFi tickling"

### ISSUE THREAD

**Issue by lordgurke** [mozilla-mobile/fenix#14474]
### What is the user problem or growth opportunity you want to see solved?
By default, Firefox sends a "flood" of UDP packets to the default gateway when connected to a WiFi.  
In my environment, this causes more problems than it solves.
On a crowded (public hotspot) WiFi with packet rate limits or "Airtime Fairness" these unneccessary UDP packets cause the connection to get slower. To be honest, I think on most modern environments this feature is not needed anymore.
In the past, I used to disable it via "about:config" -> "network.tickle-wifi.enabled = off", which improved page load speed.

In conclusion, there should be an option to switch off "WiFi tickling".
Maybe this feature can be discarded completely, since it's advantages seem to be minimal in comparison to the many situations where it is slowing down the network (for all users).

### How do you know that this problem exists today? Why is this important?
On WiFi environments with many devices and short airtime slots, these packets significantly increase the time a web page needs to be fully loaded. This is not only a measurable phenomenon - the browser really feels slower than others without that UDP tickling.
On my old smartphone with a fraction of CPU power (but with an older firefox version with WiFi tickling disabled) most websites are loading faster than on my new phone with Firefox 79 and WiFi tickling enabled.

### Who will benefit from it?
Users on crowded and/or rate-limited WiFi networks (i.e. public WiFi).
And people who see their firewall logs spammed by this.

**Comment by jawz101** [comment]
Additional info

https://bugzilla.mozilla.org/show_bug.cgi?id=888268

**Comment by plwt** [comment]
User feedback - https://support.mozilla.org/en-US/questions/1386509
