### ISSUE TITLE
lack of link touch visual feedback before link visited: its a form of button. it needs press signalling

### ISSUE THREAD

**Issue by geeohgeegeeoh** [mozilla-mobile/fenix#14473]
You can't tell on a webpage you successfully  selected a link to touch visit until the pages redraws. There should be some visual feedback (colour change under press.) To say what you hit and what is happening. Text sites like hackernews have many active text urls in flow mark-up which are close together and the lac, of feedback makes it hard to know what is going to happen.

**Comment by Poopooracoocoo** [comment]
iirc hyperlinks get a focus rectangle

**Comment by geeohgeegeeoh** [comment]
Not on my Samsung s5e, no feedback to press in an inline <a
href="foo">foo</a> link. nothing shows its been pressed. if you hold, you
gt the popup (open in tab, open in fresh browser, open in incognito mode,
copy URL...)
