### ISSUE TITLE
[Bug] address bar won't disappear tracking protection badge is active

### ISSUE THREAD

**Issue by tsbertalan** [mozilla-mobile/fenix#14470]
## Steps to reproduce
Go to a site that triggers firefox's enhanced tracking protection, causing the badge in the address bar to turn purple. I experienced this on Chipotle.com.

### Expected behavior
When I scroll down, the address bar should disappear. Or at least, it shouldn't cover up content.

### Actual behavior
The address bar is stuck at the bottom of the screen, making it impossible to tap buttons or links underneath it on the web page.

### Device information

* Android device: Pixel 2
* Fenix version: 79.0.5 (Build #2015758619)

**Comment by s-ankur** [comment]
I can also see this on screenrants.com

**Comment by smhmore** [comment]
A most frustrating obstacle, affecting many government websites where Submit or Continue or Next buttons are always on the very bottom.
Even github.com is problematic.

**Comment by Amejia481** [comment]
This looks similar to https://github.com/mozilla-mobile/android-components/issues/6933

**Comment by Amejia481** [comment]
I think we can close this in favour of https://github.com/mozilla-mobile/fenix/issues/13797, please reopen if it is not the same issue.
