### ISSUE TITLE
Laggy swipes on swiperjs.com

### ISSUE THREAD

**Issue by JVariance** [mozilla-mobile/fenix#14479]
## Steps to reproduce

Open [swiperjs](https://swiperjs.com) and try out the swipes on top of the page.
Also try out the Demos.

### Expected behavior

Smooth swipe transition.

### Actual behavior

Laggy swipe transition.

### Device information

* Android device: Samsung Galaxy S7 (Android 8.0.0)
* Fenix version: Nightly 200830 06:01 (Build #2015760947)

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683250

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
