### ISSUE TITLE
Sorting bookmarks

### ISSUE THREAD

**Issue by gitthepie** [mozilla-mobile/fenix#14471]
The desktop version of Firefox has long had the ability to sort bookmarks within each folder in alphabetical order. The Android version of Firefox 79.0.5 finally brought folders to bookmarks, but my bookmarks are still a mess because they're not in any logical order.

The problem clearly still exists because there is no sort feature in Firefox (for Android) 79.0.5. I believe everyone who uses bookmarks on their phones and tablets would benefit from having organized bookmarks.

Other bookmark features such as the ability to import and export bookmarks from/to an html file, but the most urgent features to me have been: 1. The ability to organize bookmarks in folders 2. The ability to sort bookmarks alphabetically. I can open another issue regarding the ability to import/export bookmarks, but it's not as critical as the ability to sort bookmarks.

**Comment by Poopooracoocoo** [comment]
There are other issues for this

**Comment by kbrosnan** [comment]
Closing as a duplicate
