### ISSUE TITLE
[Bug] Switching between tabs in private and normal modes when there are different tab counts can cause unexpected tab tray closures

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14476]
## Steps to reproduce

1. Open 5 tabs
2. Open and switch to private tab
3. Tap tab switcher icon
4. Tap non-private tab scope
5. Swipe down to open newest tab

### Expected behavior

I can switch to newest non-private tab

### Actual behavior

Tab tray is dismissed.

#### Observations

The core problem seems to be that the height of the tab tray depends on the number of open tabs, and switching to a scope that has more tabs in the half height position causes down swipes to close the tray. 

It is extremely annoying when this happens, and it is not easy to understand why it happens. 

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 200829 06:05 (Build #2015760755)
AC: 57.0.20200827190112, 91f7bcbca
GV: 82.0a1-20200827093043
AS: 61.0.13

**Comment by Poopooracoocoo** [comment]
#15543
