### ISSUE TITLE
[Bug] Send to device is "Offline" with active network connection

### ISSUE THREAD

**Issue by ghtmp** [mozilla-mobile/fenix#14485]
## Steps to reproduce
When I connect to restricted wi-fi network (all connections except 1 gateway are dropped) and enable always-on VPN (to connect to said gateway) the system shows my Wifi as "not connected", but all applications, including Fenix, can access internet. It looks like "Send to device" uses the same API as the OS to check network connection and assumes that the device is "offline" based on some ping via default network route (or something).
This worked in previous major firefox release with the same networking setup.

### Expected behavior
Show connected devices.

### Actual behavior
Briefly (<1s) shows connected devices, then "Offline".

### Device information

* Android device: doesn't matter
* Fenix version: 79.0.5 (#2015758617), default (Mozilla's) sync server

**Comment by Vinnl** [comment]
I have the same issue without a VPN, but with AFWall. Disabling AFWall completely does resolve the issue, but I haven't figured out yet which entries (in addition to Firefox itself) I need to allow to make it work with AFWall enabled.
