### ISSUE TITLE
Private browsing search widget

### ISSUE THREAD

**Issue by shahsurajk** [mozilla-mobile/fenix#14483]
### What is the user problem or growth opportunity you want to see solved?
Should there be a widget exclusively to search in private mode? 

### How do you know that this problem exists today? Why is this important?
* Only have search widget which searches in private mode if in PBM which is as expected #12545

### Who will benefit from it?
* All users

Notes: Can pick this up if confirmed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5970)

**Comment by s-ankur** [comment]
Umm... There are actually two of them  #11806 😅

**Comment by shahsurajk** [comment]
Wouldn't it be good if it were visible in the system tray from where we can see all the widgets from all the apps?

**Comment by s-ankur** [comment]
Then maybe you should take a look at  #8921. If you are doing it might as well do it for private and normal modes

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807542

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
