### ISSUE TITLE
[Bug]page menu not loading when private windows open from links in other apps

### ISSUE THREAD

**Issue by UserLP3** [mozilla-mobile/fenix#14482]
### Device information - Samsung S7

* Android device: ? - latest 
* Fenix version: ?

**Comment by hwinnemoe** [comment]
Please also include the used Firefox version (_Settings_, _About Firefox_) and your phones android version. Also, a screenshot of your issue would be helpful here :)

**Comment by ekager** [comment]
@UserLP3 are you still seeing this issue?

**Comment by UserLP3** [comment]
Not any more. Thanks.

On Friday, December 18, 2020, ekager <notifications@github.com> wrote:
> @UserLP3 are you still seeing this issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/hhdc9hY1AZ0x55FMX258DB_Yqj-pVcMO2OKfVAk7BLWBJSmolvpfceoajmaLNETiqvws_XbVQyZL96kJcHHw9MaOudK_q5yaFD0GNwavI2CjUsihyZBZSrAE1RmOIi7gqRtZ-m-aD0JKG6d3RSeH_QFXx5DjTVGwri5O0x_X9ZpT-0yTLluMvBchgUzBDfzlTVp43DysGXTdmBB1lXVsC2mGHB1Q60yyYqG-b8iuWw=s0-d-e1-ft#https://github.com/notifications/beacon/AQZMCW7EUG4UYIHBUMIHWUTSVLT4PA5CNFSM4QPQPA22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFSJ4HZA.gif>

**Comment by ekager** [comment]
Thank you! Closing
