### ISSUE TITLE
most addons unavailable

### ISSUE THREAD

**Issue by natedogg423** [mozilla-mobile/fenix#14489]
Automatically updated to this new version, mostly seems fine, except I went looking for addons and every single one I found says it is unavailable for the Android version. Even add-ons listed as recommended for Android said unavailable... In fact, even add-ons that are clearly specifically designed for android, such as one I found related to customizable touch screen gestures, would not allow me to download them, claiming they were only available for the desktop version. The only add-ons I'm able to use are the handful accessible through the actual in-app menu for add-ons, and curiously enough, even these add-ons, when accessed through a website or search engine are flagged as unavailable. Adams are my favorite part of Firefox. Please fix this issue

**Comment by hwinnemoe** [comment]
> We would like to expand our support to other add-ons but we are not keeping open requests for specific ones, even those in the recommended add-ons program. Please follow the Add-ons Blog for future updates. 

from https://github.com/mozilla-mobile/fenix/issues/13925#issuecomment-677828853. You can also follow https://github.com/mozilla-mobile/fenix/issues/14034 for the next steps in add-on support in Firefox, or the [Mozilla Add-ons Blog](https://blog.mozilla.org/addons/category/mobile/).

**Comment by kbrosnan** [comment]
Closing as a duplicate

**Comment by natedogg423** [comment]
i don't necessarily want to request a specific one, i'm sure if people
requested specific add-ons the flood or requests would be absurd...but
there were over a hundred for the android version of firefox until this
update, which is honestly a drop in the ocean compared with the monstrous
archive of add-ons for the desktop version, but it was still respectable.
now there are about 8.  You've all but eliminated the concept entirely. I
gave it a shot, and I love some of the new functionality, but i won't be
using this update until you manage to implement at least a reasonable
amount of add-on compatibility.

**Comment by hwinnemoe** [comment]
You can read https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/ which has been updated with new information, tl;dr: More add-ons will be coming to the Release version of Firefox, and it will be possible in the future to load arbitrary add-ons in the Nightly version.

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/12655
https://github.com/mozilla-mobile/fenix/issues/13059
https://github.com/mozilla-mobile/fenix/issues/14339
https://github.com/mozilla-mobile/fenix/issues/14452

https://github.com/mozilla-mobile/fenix/issues/14489
https://github.com/mozilla-mobile/fenix/issues/15154

**Comment by weirdal3333** [comment]
Older versions of Firefox had this feature. Mozilla intentionally removed it for some reason. Maybe they wanted to copy apple? You can still downgrade your Firefox with 3rd party app stores or a backup to restore functionality.

**Comment by 89z** [comment]
@cadeyrn is the person who thumbs down. I wonder why @cadeyrn opposes people being able to install addons?
