### ISSUE TITLE
New layout usability problem with closing search

### ISSUE THREAD

**Issue by Giwayume** [mozilla-mobile/fenix#14484]
### What is the user problem or growth opportunity you want to see solved?

With the way the search bar now takes over the entire screen when tapped, the only way to close it is to hit the back button. If you like displaying the search on top, this is quite annoying (stretching your finger from top to bottom of the phone) if you accidentally tapped on the search when trying to open tabs or change your mind. I suggest not hiding the tab or menu button when the search is tapped.

### How do you know that this problem exists today? Why is this important?

As I understand the whole point of allowing the search bar to be at the bottom of the screen is to make it more accessible to the fingers, reducing the amount of movement your hands need to do seems to be a design priority.

### Who will benefit from it?

Everyone with a top search bar.

**Comment by Giwayume** [comment]
I noticed clicking "x" in the old search bar closed out the search UI, whereas in the new search bar it just clears the input. The old functionality was much better.

**Comment by s-ankur** [comment]
Are you using the main "Daylight" browser or the nightly version?
This has considerably improved in nightly. You can just click on the empty part of the page to close search 
![Screenshot_20200830-235022_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/91666589-9edab880-eb1b-11ea-89a4-f0b50398e08b.png)

**Comment by liuche** [comment]
We've improved the search experience in #13052 which is on Nightly, which address these issues. These changes will be making their way to Release shortly.
