### ISSUE TITLE
[GitHub] Update web content issue report template

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#14487]
The web content issue report template still has the "Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?"-question that is now redundant since Fennec is EOL.

**Comment by s-ankur** [comment]
it also says "Press the lock icon in the toolbar while on the site to see toggle" for etp. It should say sheild icon

**Comment by hwinnemoe** [comment]
Closing as fixed by https://github.com/mozilla-mobile/fenix/commit/bdc306f2baba7c08e7634524f292c0448d6515e1, thanks everyone!
