### ISSUE TITLE
Allow third-party apps to open a tab in private browsing mode

### ISSUE THREAD

**Issue by Low012** [mozilla-mobile/fenix#14499]
Previous versions of Firefox (until including version 68.11.0) allowed third party apps allowed third party apps to open tabs in private browsing mode by adding the extra "private_tab" to an Intent.

The original request for Fennec can be found in https://bugzilla.mozilla.org/show_bug.cgi?id=1347583

This feature is missing from Fenix. It only seems to be possible to open links from external when this behaviour is enabled in the settings, but in this case _all_ links are opened in private tabs. The behaviour cannot be managed by third party apps.

The check for private mode is done in https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt#L47

It may be sufficient to change the line

`val private = settings().openLinksInAPrivateTab`

to

`val private = settings().openLinksInAPrivateTab || intent.hasExtra(PRIVATE_BROWSING_MODE)`

**Comment by kbrosnan** [comment]
The open links in private tabs setting provides this feature.

**Comment by Low012** [comment]
Not really, the user story is different.

Fenix implements: "**As a user** I want to be able to determine if URLs opened from external apps will open in a private tab or not for **all** third party apps."

What was possible in previous versions of Firefox: "**As a developer** of a third party app I want to be able to determine if URLs opened from **my** app will open in a private tab or not."

**Comment by decadent** [comment]
Moreover, as a user I could use such an extra flag to send intents via Tasker or Automate, and thus open private tabs from other apps when I wish so—without fumbling with the clipboard.
