### ISSUE TITLE
[Bug] Android toolbar is all gray after starting to type and then using □ button and focusing Fenix again

### ISSUE THREAD

**Issue by smaug----** [mozilla-mobile/fenix#14490]
## Steps to reproduce
Start typing something to the location bar
Click □ on the Android toolbar (bottom right)
Select Fenix from the running apps

### Expected behavior
Since the buttons on the toolbar are still working, they should be somehow visible

### Actual behavior
The toolbar, including buttons are all gray

### Device information

* Android device: Sony Xperia 10 II, Android 10
* Fenix version: Nightly 200829, GV 82a1-20200827093043

![image](https://user-images.githubusercontent.com/9219935/91660496-ff97d000-eade-11ea-9a6c-ee96439d00a5.png)

**Comment by ekager** [comment]
@smaug---- are you still seeing this?

**Comment by smaug----** [comment]
Haven't seen this for ages.
