### ISSUE TITLE
[Bug] AMO says "Not available on Firefox for Android." for Addons that are available

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14496]
## Steps to reproduce
Go to any addon in addon manager list and in the details section click on the homepage link

### Expected behavior
AMO opens and tells you app is installed OR the addons's actual homepage opens. (Can be accessed from AMO)
I am only opening this here because option 2 is possible to do in fenix itself
### Actual behavior
Opens AMO and tells that the addon is not available on android, confusing users 
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by cadeyrn** [comment]
Since installation from AMO is not yet supported at all it's not really a bug.

**Comment by kbrosnan** [comment]
This is not a Fenix issue. Please file an issue at https://github.com/mozilla/addons-server/issues
