### ISSUE TITLE
[Bug] Unclosing Fenix tabs jumps to top of page, doesn't restore position

### ISSUE THREAD

**Issue by nyanpasu64** [mozilla-mobile/fenix#14494]
## Steps to reproduce

- Open a long page like http://patorjk.com/misc/scrollingtext/timewaster.php and scroll down.

Perform one of:
- Close the tab and undo closing it.
- Switch apps, and load enough apps to unload Fenix. Then switch back to Fenix.
  - To simplify this process, open Android "Developer options", scroll to the "Apps" heading (the bottom-most heading), and change the second option (Background process limit) to "No background processes". Then switching apps once is enough to unload Fenix.

### Expected behavior

The page loads scrolled down.

### Actual behavior

The page loads scrolled to the top.

If you switch apps and unload Fenix, the page will often be replaced by about:blank or a white screen in both Firefox and Nightly. This is a separate bug #5478 (probably not #12593).

### Device information

* Android device: Moto G5 Plus on Android 8.1.0, and Samsung SM-T510 on unofficial LineageOS 9.
* Fenix version: Bug present on Nightly 200830, and was not present in Nightly a few days/weeks ago. Bug is not present on Firefox 79.0.5 (page loads on top, and jumps to proper scroll position half a second later).

**Comment by kbrosnan** [comment]
This is because of #10986, closing.
