### ISSUE TITLE
Feature request: Home page/top sites in private mode

### ISSUE THREAD

**Issue by mobileNetscapeUser** [mozilla-mobile/fenix#14498]
This issue is being split off from issue #14429 (and it will be closed).  Thank you for all your hard work.

### What is the user problem or growth opportunity you want to see solved?

The problem is quick access to frequent sites in private browsing mode.

### How do you know that this problem exists today? Why is this important?

When I open a new private tab, I only see information about common myths about private browsing.  I like the information about the common myths about private browsing. Before the daylight release, I used to have the home page show my bookmarks which were in a certain order so that the most frequent were at the top. With the "top sites" feature, I wouldn't have to do that, but I don't see that in private browsing mode.  It is important to provide quick access to frequent sites in private browsing mode.

### Who will benefit from it?

All users that use private browsing mode and want single press to access frequent sites.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5990)

**Comment by s-ankur** [comment]
This would also solve #12483

**Comment by gabrielluong** [comment]
I think it is interesting to consider showing top sites (maybe only user pinned sites or a private only user pinned sites) in private mode. I don't know what the implications of each are, but I think it's worth thinking about in terms of UX. Don't know if we will do it right away, but I am gonna tag it as something to investigate.

**Comment by mobileNetscapeUser** [comment]
I was thinking about user pinned top sites from seeing:
menu->add to top sites

Please consider the best way to accomplish quick access to frequently visited sites in private browsing mode.  Thank you.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814174

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
