### ISSUE TITLE
[Bug] The app crashes at the startup

### ISSUE THREAD

**Issue by Sav22999** [mozilla-mobile/fenix#14505]
## Steps to reproduce
Just try to open the app and it crashes and I can't use it 🤔 I don't know, I think it's the ne update

### Expected behavior
Open the app without crash

### Actual behavior
The app crahes

### Device information
LG G6, Android 9, European version (V30b-EUR-XX). If you need more information, please tell me

* Android device: LG G6, Android 9
* Fenix version: Nightly 200830 06:01

**Comment by Sav22999** [comment]
![Capture+_2020-08-31-00-05-11.png](https://user-images.githubusercontent.com/32335378/91670430-b024c480-eb1d-11ea-91c6-1fa57457c91d.png) ![Capture+_2020-08-31-00-05-07.png](https://user-images.githubusercontent.com/32335378/91670432-b450e200-eb1d-11ea-8cd3-39a11321459d.png)

**Comment by LittleAngelwings** [comment]
Maybe the same issue https://github.com/mozilla-mobile/fenix/issues/14486

**Comment by Sav22999** [comment]
@LittleAngelwings I don't know. Unfortunatly Firefox doesn't return me any code

**Comment by kbrosnan** [comment]
Closing as a duplicate
