### ISSUE TITLE
Fenix as android's assist app

### ISSUE THREAD

**Issue by anabh4569** [mozilla-mobile/fenix#14506]
### What is the user problem or growth opportunity you want to see solved?

In the previous version of mobile firefox (fennec?), you could set firefox as android's assist app; what this meant was that when the home button was long pressed, it opened a new tab with the address bar focused, allowing convenient searching afterwards.

With fenix, you can still set firefox as android's assist app, but long pressing the home button now only switches applications to firefox, instead of additionally opening a new tab and focusing on the address bar.

### How do you know that this problem exists today? Why is this important?

I set android's assist app to mobile firefox fenix version 79.05 and tried it; long pressing the home button only navigates to firefox instead of opening a new tab and focusing on the address bar.

This is important because it gives users a very convenient way to immediately start searching/entering a URL from anywhere in android in a single action.

### Who will benefit from it?

Everyone who wants to set firefox as android's assist app.

**Comment by kbrosnan** [comment]
Duplicate #3722
