### ISSUE TITLE
[Bug] ebay.com can't click on listings/links after searching

### ISSUE THREAD

**Issue by BlueRocketMouse** [mozilla-mobile/fenix#14508]
## Steps to reproduce
Open ebay website and type anything into the search bar. Attempt to click on any of the item listings or page numbers on the search results page.
### Expected behavior
Clicking should open the link to the item listing or take the user to the next page.
### Actual behavior
Link does not open. Workaround is to press and hold the link, then open it in a new tab but that's rather cumbersome. Listings on the front page do not display this behavior and open normally.
### Device information

* Android device: Pixel 2
* Fenix version: 79.0.5

**Comment by AndiAJ** [comment]
**Not reproducible** anymore on the latest **`Nightly Build 201117`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
