### ISSUE TITLE
[Bug] Read Mode problems with new update

### ISSUE THREAD

**Issue by readmodecomplainer** [mozilla-mobile/fenix#14511]
Read mode doesn't seem to work properly anymore since the new update.

1. It no longer saves your place when you close the app. Every time you open the app it goes back to the top of whatever you were reading. I checked and I haven't changed my settings to delete any history or anything like that.

2. This is not a big deal but you used to be able to copy the url for the article you were reading while in read mode. Now when you try to do that you will actually be copying something like "moz-extension://5799391..."

Thanks!

**Comment by csadilek** [comment]
Thanks for filing!

> This is not a big deal but you used to be able to copy the url for the article you were reading while in read mode

This already fixed and will roll out with the next update. See https://github.com/mozilla-mobile/fenix/issues/12353

> every time you open the app it goes back to the top of whatever you were reading

This needs some work. I will dupe it to: https://github.com/mozilla-mobile/fenix/issues/14567
