### ISSUE TITLE
Yandex search engine isn't available in Ukraine.

### ISSUE THREAD

**Issue by karaushu** [mozilla-mobile/fenix#14514]
## Default search engine isn't available in Ukraine.

Default search engine for Ukraine is Yandex.
Due to some political and military issues it is not available in Ukraine. So users will get "Connection time out" on searching. So i suggest it should be replaced with something more relevant. (in most cases is Google).

**Comment by liuche** [comment]
@mkaply is this something that we can do anything about?

**Comment by amedyne** [comment]
Re-opening this. Default search engine for Ukraine is Google.

**Comment by mkaply** [comment]
> Re-opening this. Default search engine for Ukraine is Google.

Yes, that's what that person wants (and how it is described in list.json)

Yandex is not there for the Ukranian build and the default is Google. I'm checking if this is correct.

**Comment by Mugurell** [comment]
@mkaply Can this be closed? Does it also needs manual QA?

**Comment by kbrosnan** [comment]
Lets just double check this and then resolve if we are doing the expected behavior.

**Comment by ebalazs-sv** [comment]
I had tested this on Nightly 3/15 with Motorola Moto G6 (Android 8) and in Ukraine, the default browser is Google.
I will remove the qa:needed label and close this issue.
