### ISSUE TITLE
[Bug] Tracking protection exceptions are deleted after deleting data on quit

### ISSUE THREAD

**Issue by surprized** [mozilla-mobile/fenix#14512]
## Steps to reproduce
Add an exception to tracking protection with delete browsing data on quit enabled (all options selected), then touch quit and open the website again. The exceptions list then appears empty. Tested with DuckDuckGo.

### Expected behavior
Exceptions being saved persistently.
### Actual behavior
Exceptions not being deleted after touching quit.
### Device information

* Android device: Moto Z Play
* Fenix version: 79.0.5

I have uBlock Origin installed, in case that might provide additional information about why this is happening.

**Comment by kbrosnan** [comment]
This would leak sites you have visited and set tracking protection exception. The expected behavior for clearing private data is that no local information about sites you have visited is retained.

**Comment by surprized** [comment]
I noticed private tabs don't save exceptions permanently, which does align with what you are saying. I thought my issue was about unintended behavior, nevermind!
