### ISSUE TITLE
[Bug] Cannot access to about:config

### ISSUE THREAD

**Issue by PeopleInside** [mozilla-mobile/fenix#14518]
## Steps to reproduce
1. try to access about:config in the address bar
2. an error occur

### Expected behavior
Be able to access about:config

### Actual behavior
I try to access about:config in the address bar but an error occurs.

### Device information
Redmi Note 7 Europe, Android 10

* Fenix version: 79.0.5

I need change the punycode default setting that create security issue on Firefox. I cannot do due for this bug.

**Comment by cadeyrn** [comment]
Duplicate of #7865.

**Comment by PeopleInside** [comment]
Thanks, there is a way i can turn punycode to true (security) ?

**Comment by ekager** [comment]
Closing for #7865.

**Comment by liu7yong** [comment]
Many features (proxy feature for example) in about:config are the reason I keep firefox installed in my android phone, now  uninstalling firefox is only a question of time.
