### ISSUE TITLE
To be able to see SSL certificate details

### ISSUE THREAD

**Issue by PeopleInside** [mozilla-mobile/fenix#14519]
### What is the user problem or growth opportunity you want to see solved?

Firefox for mobile doesn't show TLS used (1.2 or 1.3) certificate expiration, and other certificate details visible by Firefox for PC or from other mobile browsers.

This is very bad for security to be unable to see certificate details.

### How do you know that this problem exists today? Why is this important?

Because if I visit a website I cannot check SSL certificate details as clicking on the certificate show only who is generating the certificate (ex Let's encrypt) and no other details: expiration TLS used, etc.

### Who will benefit from it?

Everyone also in security.

**Comment by cadeyrn** [comment]
Duplicate of #8400.

**Comment by andreicristianpetcu** [comment]
A workaround in nightly https://twitter.com/FirefoxPreview/status/1313128741208502272
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by PeopleInside** [comment]
> 
> 
> A workaround in nightly https://twitter.com/FirefoxPreview/status/1313128741208502272
> https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

This extension never work on new Firefox for Android

**Comment by andreicristianpetcu** [comment]
Please read the links I shared above. ![Screenshot_20201007-083209_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95291181-9cd0eb80-0877-11eb-956e-c034c7cf7d09.png)

**Comment by PeopleInside** [comment]
I hate the fact the new stable Firefox for Android have different security issue.
You cannot check certificate info, you cannot decide to see puny code domain as default and you cannot also set this manually because about:config is not working. Download often broken, etc. All issue are listed in the play store.

Is sad to see a company and browser you trust work with all this issue, also security issue on my opinion.
Yes maybe your post was about nighty and not the stable version.
Thanks.

**Comment by andreicristianpetcu** [comment]
Google Play is not a bug tracker. Please report [here](https://github.com/mozilla-mobile/fenix/issues) all the issues you are having and the dev team will work on them at some point.

**Comment by PeopleInside** [comment]
I'm not able to install the extension on nightly, seems the work around is complicated or need an account. I don't like as seems Firefox is blocking installation of additional component that help with improve the Firefox security who is not in the standard function. Still don't like to see how is hard to install an extension for be able to read certificate details.

**Comment by andreicristianpetcu** [comment]
You don't need an account. Use my account 12325762 with the fenix collection.

![Screenshot_20201007-225058_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95380752-dfcea580-08ef-11eb-9b3f-7eee56c61867.png)
![Screenshot_20201007-225105_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95380770-e5c48680-08ef-11eb-98d7-d2a52354856a.png)

click the logo several times

![Screenshot_20201007-225114_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95380866-0391eb80-08f0-11eb-9be0-0aae34b11e52.png)

![Screenshot_20201007-225122_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95380908-16a4bb80-08f0-11eb-9114-1022d0f99f92.png)
![Screenshot_20201007-225129_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95380918-1c020600-08f0-11eb-9a60-2e1fd1a0cd19.png)
![Screenshot_20201007-225140_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95380926-1efcf680-08f0-11eb-9657-deadc324864a.png)
![Screenshot_20201007-225217_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95380939-21f7e700-08f0-11eb-94af-f26af5dafb8b.png)
![Screenshot_20201007-225224_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95380948-23c1aa80-08f0-11eb-9059-6b98a2948e71.png)

**Comment by andreicristianpetcu** [comment]
We all want an easy way to install extensions, INCLUDING MOZILLA. Some things are broken so they enabled them only in Nightly. Use a browser that makes you feel secure, it's your choice. Firefox devs are working on what is most important at the moment.

**Comment by PeopleInside** [comment]
When will be about:config and add on available on the stable Firefox version?

**Comment by andreicristianpetcu** [comment]
@PeopleInside there are no plans for that. Please use beta. Both beta and about:config are not for the faint-hearted. They are for people who know what they are doing.
