### ISSUE TITLE
[Bug] In Tabs tray "fx-fenix_error_4" tab title is displayed instead of "Address Not Found"

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#14517]
## Steps to reproduce
1. Launch Fenix Nightly and go to thinkbrodband.com;
2. Tap the tab counter;
3. Observe the tab title for the tab opened at step 1;
### Expected behavior
"Address Not Found" is the tab title for a wrong address.
### Actual behavior
"fx-fenix_error_4" is the tab title for a wrong address.

![rsz_screenshot_20200831-142632](https://user-images.githubusercontent.com/48799384/91715384-35e45680-eb96-11ea-8d88-b21bdffa2428.png)

### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 200831 06:01 (Build #2015761139), GV 82.0a1, from 8/31.
Not reproducible on Beta 80.0.01-beta.2 GV 80 from8/18 and Release 79.0.5 (Build #2015758619) from 8/18.

**Comment by ekager** [comment]
Likely related to https://github.com/mozilla-mobile/android-components/issues/8315

**Comment by jonalmeida** [comment]
Closing as fixed and verified in https://github.com/mozilla-mobile/fenix/issues/14620.
