### ISSUE TITLE
FNX-5039 ⁃ lanacion.com.ar displays differently in Firefox than in Fenix

### ISSUE THREAD

**Issue by gaby2300** [mozilla-mobile/fenix#1451]
## Steps to reproduce
1) Type "lanacion.com.ar" in Fenix's URL bar.
   2) Notice the display.
   3) Type "lanacion.com.ar" in Firefox Release's URL bar.
   4) Notice the display.

### Expected behavior
Both displays should look the same.

### Actual behavior
Both displays look completely different.

### Device information
* Android device: Sony Z3C, Android 6.0.1
* Fenix version: Build#10971206; 68.0a1-20190403060632

**Comment by gaby2300** [comment]
Firefox Release mobile site

![Firefox mobile](https://user-images.githubusercontent.com/2151784/55691627-6363ab00-5976-11e9-8f9a-90b6b52f1834.png)

**Comment by gaby2300** [comment]
Fenix mobile site
![Fenix](https://user-images.githubusercontent.com/2151784/55691633-81311000-5976-11e9-99c3-c2a1c3043298.png)

**Comment by Baemir** [comment]
Unable to reproduce on the newest nightly. Perhaps try again, or check settings?

**Comment by gaby2300** [comment]
I tried multiple times before creating the issue. 

Could you please tell me which settings should I check?

**Comment by vesta0** [comment]
@gaby2300 please try again with the new nightly?

**Comment by gaby2300** [comment]
> 
> 
> @gaby2300 please try again with the new nightly?

Today's nightly shows the same. Maybe it's due to the Android version 6.0.1?

**Comment by gaby2300** [comment]
> 
> 
> I tried multiple times before creating the issue.
> 
> Could you please tell me which settings should I check?

**Comment by gaby2300** [comment]
> 
> 
> Unable to reproduce on the newest nightly. Perhaps try again, or check settings?

I tried a lot of times but got the same, including today's nightly but I got the same result. Could you please tell me which settings should I  check?

**Comment by gaby2300** [comment]
Sorry, I didn't mean to close this, so reopening...

**Comment by kbrosnan** [comment]
Looks like it was some sort of network error where the page's CSS and images were not delivered. 

I cannot reproduce using an April 16th build on a Pixel 3.
