### ISSUE TITLE
[Bug] Fenix offers to add PWA to home screen in private browsing mode

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14513]
## Steps to reproduce

1. Open private tab
2. Go to a site that Fenix offers a PWA install for

### Expected behavior

Nothing happens. 

### Actual behavior

Modal dialog appears asking user to add pwa to home screen. This should not happen as it is in *private* mode and it reduces significantly the level of trust I have in private browsing mode. 

I realize that this may occur only on new profiles, but that does not diminish the severity of this bug. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by kbrosnan** [comment]
Generally we have not blocked creation of certain persistent items in private browsing. Generally these items end up existing outside the browser. For example on desktop you can create desktop shortcuts from Private Browsing and saving files is allowed. This issue is best covered by https://github.com/mozilla-mobile/android-components/issues/5883 closing in favor of that one.

**Comment by yoasif** [comment]
@kbrosnan I'm not asking to block creation of persistent items, I am asking for Firefox to not *prompt* me in a tip to save persistent items during private browsing. This is not the same as either of those bugs - please reopen.

**Comment by yoasif** [comment]
Was reminded of this after seeing [Online Privacy Should Be Modeled on Real-World Privacy](https://daringfireball.net/2020/09/online_privacy_real_world_privacy) which is making the rounds.

While there is nothing "technically" wrong with this feature, it is a question of propriety and whether it is the right time to provide me with  this tip. Is the right time to prompt me to save persistent data that *in a mode that explicitly does not save persistent data* moments after browsing to a site that I don't want in my history?

Worse still, the tip is modal and must be declined to move forward - it blocks you and as such is pushy in way that we would never accept in a real world interaction. 

It is akin to saying to a friend: "I'm going to tell you a secret", and a moment after you begin, your interlocutor says "Imma let you finish, but... can I record this?"

That is really very strange coming from a brand who has used the phrase "browse like no one's watching" in marketing materials and indeed uses it in the intro for [focus](https://github.com/mozilla-mobile/focus-android). It is terribly off-brand. 

GitHub doesn't let me reopen issues, so gently pinging @NotWoods - thanks for your consideration.
