### ISSUE TITLE
Security: Punycode show_punycode set by default to true instead of false

### ISSUE THREAD

**Issue by PeopleInside** [mozilla-mobile/fenix#14520]
### What is the user problem or growth opportunity you want to see solved?

Firefox for PC and Firefox for Android is vulnerable to punycode domains.
I want see Firefox a more secure browser that has the show_punycode set to true by default so https://www.xn--80ak6aa92e.com/ will be not showed as default as same of apple.com -> security issue!

### How do you know that this problem exists today? Why is this important?

Easy, visit from Firefox with default settings https://www.xn--80ak6aa92e.com/ and you will see as you are connected with apple.com also certificate results to be generated for apple.com

### Who will benefit from it?

Security and all users.
If someone needs can change at own risk the punycode flag to false.

**Comment by cadeyrn** [comment]
Duplicate of #5640.
