### ISSUE TITLE
Intermittent UI test failure - testStrictVisitSheetDetails (Assertion failure assertEnhancedTrackingProtectionNotice)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#14524]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4874074604364252605/executions/bs.720ea0960c213075/testcases/2/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.assertEnhancedTrackingProtectionNotice(EnhancedTrackingProtectionRobot.kt:91)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.access$assertEnhancedTrackingProtectionNotice(EnhancedTrackingProtectionRobot.kt:1)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobot.verifyEnhancedTrackingProtectionNotice(EnhancedTrackingProtectionRobot.kt:29)`
### Build: 
8/31

**Comment by sv-ohorvath** [comment]
Failed on 8/30 as well, still just flaky: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5860505690576069979/executions/bs.6c4630877143e8a3/testcases/2/test-cases

If it gets worse, might need to disable it.

**Comment by Amejia481** [comment]
No should if it could be related to https://github.com/mozilla-mobile/fenix/issues/14071?

**Comment by sv-ohorvath** [comment]
> No should if it could be related to #14071?

I'm not sure: the test doesn't fail consistently, the ETP onboarding is not being displayed every time (nor the shield get highlighted to show that it's blocking). It looks like it could be: https://github.com/mozilla-mobile/fenix/issues/7907 
The test page is using this: https://trackertest.org/

**Comment by sv-ohorvath** [comment]
See also (for the same or similar error): 
https://github.com/mozilla-mobile/fenix/issues/12896
https://github.com/mozilla-mobile/fenix/issues/13830

**Comment by sv-ohorvath** [comment]
The ETP tests are now failing and blocking on this new AC 58.0.20200903130219 update, with this error.
https://github.com/mozilla-mobile/fenix/pull/14688/checks?check_run_id=1067217077 - will disable all of them.

**Comment by sv-ohorvath** [comment]
Waiting for https://github.com/mozilla-mobile/fenix/issues/12848 - the ETP toggle is off on the first load of the test pages so the ETP notice & shield are not showing as expected.

**Comment by sv-ohorvath** [comment]
https://github.com/mozilla-mobile/fenix/issues/15152 was fixed but the tests still fail on Firebase & not locally: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5458939384415128649/executions/bs.3dc07bd559205e21/test-cases
Keeping these disabled.
