### ISSUE TITLE
Show a dialog when the top sites limit has been reached

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#14529]
When people are about to add a 17th top site a dialog is displayed telling them that they reached the max amount for top sites.

Dialog spec from https://github.com/mozilla-mobile/fenix/issues/8312#issuecomment-643366197:
```
Strings for the dialog when top site limit is reached.

Top site limit reached

To add a new top site, remove one. Touch and hold the site and select remove.

OK, Got It
```

**Comment by klint** [comment]
Hi. Not sure where to post this remark :) So here it is.

It took me some days to understand how "Top Sites" are working now, together with the "Add most visited sites to home page" feature: actually the 16 displayed sites are 1) first the top sites that the user has added manually, 2) followed by the sites he has visited most often. Right? :)
But with only 16 sites and 2 slides, there is no room enough for using both options in a convenient way imho, as you have to share 16 sites only across Top Sites and Most Visited Sites.

Given that, it is not clear to me why the number of tiles was limited to 2, as the code was there to navigate across more than 2 (it worked for me as I had around 30 Top Sites when the limitation came in action :) ). The only issue was with the 2 dots that did not expend to the actual number of available slides. 

Thanks :)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200910 (Build #2015763059).

### Devices used:
- OnePLus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)
