### ISSUE TITLE
Intermittent UI test failure - verifyContextOpenLinkNewTab & verifyContextOpenLinkPrivateTab

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#14523]
### Firebase Test Run:
Flaky, failed 1/2 tries:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4874074604364252605/executions/bs.d261ad2d646315b9/testcases/2/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyLinkContextMenuItems(BrowserRobot.kt:106)`
### Build: 
8/31

**Comment by sv-ohorvath** [comment]
See also: https://github.com/mozilla-mobile/fenix/issues/14526 (might be the same problem with clicking page links?)

**Comment by sv-ohorvath** [comment]
verifyContextOpenLinkPrivateTab failure 2/2: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6068480084120569670/executions/bs.c1b132fbb2acc561/testcases/2/test-cases

**Comment by isabelrios** [comment]
Failure 1/2 Oct 9th: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5320799649453257618/executions/bs.ea89fe7280ec760c/test-cases

**Comment by isabelrios** [comment]
Failed 1/2 Oct 30th: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8930134761724998303/executions/bs.8dd4a8d126807a2/test-cases

**Comment by sv-ohorvath** [comment]
Failed 1/2, 11/2: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4738926979781110404/executions/bs.863029a449c66ecc/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 11/11: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6534721608186155265/executions/bs.cf99cbaa0c24ed67/testcases/2/test-cases

**Comment by isabelrios** [comment]
Flaky on 11/14: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8496855832271756687/executions/bs.d0f7947c1126760e/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 11/21, but with a different error:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7429037611015652157/executions/bs.9d61099114894a0a/testcases/2/test-cases
`androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: (with id: org.mozilla.fenix.debug:id/mozac_browser_tabstray_title and with text: is "Test_Page_1")' on view 'with id: org.mozilla.fenix.debug:id/tabsTray'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:25)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.ui.robots.TabDrawerRobotKt.assertExistingOpenTabs(TabDrawerRobot.kt:264)
at org.mozilla.fenix.ui.robots.TabDrawerRobotKt.access$assertExistingOpenTabs(TabDrawerRobot.kt:1)
at org.mozilla.fenix.ui.robots.TabDrawerRobot.verifyExistingOpenTabs(TabDrawerRobot.kt:53)
at org.mozilla.fenix.ui.ContextMenusTest$verifyContextOpenLinkNewTab$3.invoke(ContextMenusTest.kt:72)
at org.mozilla.fenix.ui.ContextMenusTest$verifyContextOpenLinkNewTab$3.invoke(ContextMenusTest.kt:35)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:376)
at org.mozilla.fenix.ui.ContextMenusTest.verifyContextOpenLinkNewTab(ContextMenusTest.kt:71)`

**Comment by sv-ohorvath** [comment]
verifyContextOpenLinkNewTab flaky on 12/8: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8911787755055112771/executions/bs.9a4fd083ee63eb72/testcases/2/test-cases - same error as above

**Comment by sv-ohorvath** [comment]
verifyContextOpenLinkPrivateTab flaky on 12/9: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8574127296912357875/executions/bs.4dcb42edd6379398/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
verifyContextOpenLinkNewTab flaky on 2 different commits on Master 1/22: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5620835917928530212/executions/bs.fb7c775cf975ad75/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
verifyContextOpenLinkNewTab  flaky on 1/27: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7895649690705864349/executions/bs.c1b5244e1cd3b899/testcases/3/test-cases
`androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: (with id: org.mozilla.fenix.debug:id/mozac_browser_tabstray_title and with text: is "Test_Page_1")' on view 'with id: org.mozilla.fenix.debug:id/tabsTray'.`

**Comment by sv-ohorvath** [comment]
verifyContextOpenLinkNewTab flaky on 1/28, same error as in the previous comment:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4812315134641570896/executions/bs.ee4e532eb87eddc6/testcases/3/test-cases

**Comment by sv-ohorvath** [comment]
flaky on 1/29 on master: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5905034544486530854/executions/bs.fe87359553735da0/testcases/3/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 2/2 on master: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5085046698635228408/executions/bs.46d83c7ead13f14d/testcases/3/test-cases

**Comment by sv-ohorvath** [comment]
verifyContextOpenLinkPrivateTab flaky on 2/3 on Master: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7182355998678182480/executions/bs.b34eae9bd4d14f2/testcases/3/test-cases

**Comment by AndiAJ** [comment]
**• Master  2/3 :**

**► Flaky 2x** `verifyContextOpenLinkPrivateTab`
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7182355998678182480/executions/bs.b34eae9bd4d14f2/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8629348015660504806/executions/bs.e552ad0f6f955eaa/testcases/3/test-cases)

`androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: (with id: org.mozilla.fenix.debug:id/mozac_browser_tabstray_title and with text: is "Test_Page_2")' on view 'with id: org.mozilla.fenix.debug:id/tabsTray'.`


**► Flaky 1x** `verifyContextOpenLinkNewTab`
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8629348015660504806/executions/bs.476d1975028ef5b7/testcases/3/test-cases)

`androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: (with id: org.mozilla.fenix.debug:id/mozac_browser_tabstray_title and with text: is "Test_Page_1")' on view 'with id: org.mozilla.fenix.debug:id/tabsTray'.`


**• Master  2/4 :**
**► Flaky 1x** verifyContextOpenLinkNewTab

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5235184983366049247/executions/bs.b45ab28d3b31f1da/testcases/3/test-cases)

`androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: (with id: org.mozilla.fenix.debug:id/mozac_browser_tabstray_title and with text: is "Test_Page_1")' on view 'with id: org.mozilla.fenix.debug:id/tabsTray'.`

**Comment by AndiAJ** [comment]
• Master 2/5 :
► Flaky 1x `verifyContextOpenLinkPrivateTab`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6123688277858333420/executions/bs.567f66f480b4b189/testcases/3/test-cases)

`androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: (with id: org.mozilla.fenix.debug:id/mozac_browser_tabstray_title and with text: is "Test_Page_2")' on view 'with id: org.mozilla.fenix.debug:id/tabsTray'.`
