### ISSUE TITLE
Intermittent UI test failure - testDownloadNotification

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#14526]
### Firebase Test Run:
Flaky, 1/2:
 https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7061633375658984827/executions/bs.9c0ad7ce4f780e82/testcases/1/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.clickLinkMatchingText(BrowserRobot.kt:298)`
### Build: 
8/29

New failure error:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.DownloadRobotKt.assertDownloadNotificationPopup(DownloadRobot.kt:129)
at org.mozilla.fenix.ui.robots.DownloadRobotKt.access$assertDownloadNotificationPopup(DownloadRobot.kt:1)
at org.mozilla.fenix.ui.robots.DownloadRobot.verifyDownloadNotificationPopup(DownloadRobot.kt:43)
at org.mozilla.fenix.ui.DownloadTest$testDownloadNotification$4.invoke(DownloadTest.kt:88)
at org.mozilla.fenix.ui.DownloadTest$testDownloadNotification$4.invoke(DownloadTest.kt:31)
at org.mozilla.fenix.ui.robots.DownloadRobot$Transition.clickDownload(DownloadRobot.kt:68)
at org.mozilla.fenix.ui.DownloadTest.testDownloadNotification(DownloadTest.kt:87)`

See: https://github.com/mozilla-mobile/fenix/issues/17485#issuecomment-777420045

Waiting for https://github.com/mozilla-mobile/android-components/issues/9694

**Comment by sv-ohorvath** [comment]
See also: https://github.com/mozilla-mobile/fenix/issues/14523

**Comment by sv-ohorvath** [comment]
Still flaky, on 9/26: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6228128124916055279/executions/bs.598043085f10445e/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
The test fails at waitNotNull for page link visibility which I couldn't fix with my current knowledge (same problem as with the old verifyPageContent issue - but the fix for that doesn't work here). Ran out of ideas so I'm un-assigning myself. If it fails too often and becomes problematic, we should disable the test.

**Comment by sv-ohorvath** [comment]
Failed 1/2: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5583391206192370605/executions/bs.3e4609debd24403b/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Failed 1/2, on 11/3: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6149550211770242246/executions/bs.35fa77cfed03f491/testcases/2/test-cases

**Comment by isabelrios** [comment]
Flaky 1/2, on 11/13: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8484178373882639050/executions/bs.5fef8971219a7a55/test-cases

**Comment by sv-ohorvath** [comment]
Failed 2/2 on 11/17: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7458380383054094210/executions/bs.df48489c7cea4d53/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 11/30: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7444060780967543866/executions/bs.6702160d8e2438b6/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 12/8: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8911787755055112771/executions/bs.895131b17b69818a/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 1/4/21: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7297689412371535104/executions/bs.45c927f3bba7c868/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 1/21: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6178258430809923567/executions/bs.2b033bedeafbe45d/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 1/22 on master: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6853506258424678385/executions/bs.ee20b54ab670ee15/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Lets wait for https://github.com/mozilla-mobile/android-components/issues/9694 and see if it fixes this issue as well.

**Comment by sv-ohorvath** [comment]
Flaky on 2/16: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5025857421592052053/executions/bs.f5298867fcc1aa5/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
https://github.com/mozilla-mobile/android-components/issues/9694 was merged ~2 weeks ago and this hasn't failed since, so I'm closing it as fixed.
