### ISSUE TITLE
[webcontent] doesn't open any tweets on https://www.redcafe.net/transfer-tweets/

### ISSUE THREAD

**Issue by mpaunovic** [mozilla-mobile/fenix#14521]
## Site with issue and any steps to reproduce

try to access https://www.redcafe.net/transfer-tweets/ in the address bar.
the site loads but none of the tweets do.

### Expected behavior

To load all of the tweets.

### Actual behavior

Loads none of them.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Every other Android browser I've tried (including Chrome) loads the tweets. The desktop version of Firefox works just fine, too.

### Device information

* Android device: Samsung A7, Android 10
* Fenix version: 79.0.5
* Add-ons: uBlock Origin (default filters + EasyList Cookie List), Dark Reader, HTTPS Everywhere

**Comment by Diana-Rus** [comment]
Hello, tried to reproduce the issue, but in my case it loads it takes almost a minute to load, but eventually. the tweets are loaded.
This however may be a performance issue as when trying on Chrome, the tweets load much faster.

@mpaunovic -Could you recheck and see?

**Comment by mpaunovic** [comment]
I rechecked and can confirm, it's definitely a performance issue, it took me more than a minute to load all the tweets.
