### ISSUE TITLE
[Bug] Form post bug

### ISSUE THREAD

**Issue by rickrich** [mozilla-mobile/fenix#14532]
## Steps to reproduce
Can you try this one? http://l2amazons.com/

At the bottom of the page is a donation form, enter a character name (any string) but not an amount, it should go to a second page displaying the character name you picked. If you don't see the character name, then you're experiencing the same problem as on certitude.

### Expected behavior
character name is whatever you typed

### Actual behavior
character name is blank

### Device information

* Android device: ?
LG cell phone

* Fenix version: ?
79 and 80

Desktop Firefox version 79 for linux works correctly, though.

**Comment by rickrich** [comment]
"Ok, so this is definitely a bug in firefox for android with no known workaround as far as I can tell.

The code is as simple as the examples in mozilla's own specifications for the target field: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form

and their own browser doesn't follow them..."

**Comment by rickrich** [comment]
https://www.certitudes.org/html/test2.html

Mobile 79: test1 and and test2 give "Unknown Waypoint"
Desktop 79:  test1 and and test2 give "Mission: Impossible" https://www.geocaching.com/geocache/GC1234_mission-impossible

**Comment by liuche** [comment]
Not seeing this in Firefox Nightly.

**Comment by ekager** [comment]
@rickrich are you stil experiencing this?

**Comment by rickrich** [comment]
I went back to Firefox Browser 68.11.0 for android in September.  I really don't understand what you are doing with 79, 80, ....
