### ISSUE TITLE
[Bug] Forms with target="_blank" don't submit data since version 79

### ISSUE THREAD

**Issue by chr15tophe** [mozilla-mobile/fenix#14531]
## Steps to reproduce
Define a form as such (replace /myhandler with your handler)

```
<form action="/myhandler" method="post" target="_blank">
<input type="hidden" name="field" value="test">
<input type="submit" value="Test">
</form>
```

This works on all browsers: a new tab is open and the handler receives the field value as "test". On android, the handler doesn't receive any data since version 79.

### Expected behavior
Handler receives field data.

### Actual behavior
Handler receives no data.

### Device information
* Android device: android tablet and LG phone
* Fenix version: 79 and 80

**Comment by yoasif** [comment]
@chr15tophe does this happen in GeckoView Example or Reference Browser? If it does, it may be a GeckoView issue - worth a check if you have some time.

**Comment by chr15tophe** [comment]
It's whatever you download from the google store.

**Comment by bryclee** [comment]
Created this to demonstrate the issue: https://bryclee.com/firefox-form-post.html

On Firefox Android, when using method POST with target that opens new context, the form instead sends a GET request with no query params. On desktop, it properly sends a POST and opens in a new tab.

**Comment by sflorean** [comment]
Tested on the latest Nightly and Chrome, and couldn't see any differences following the link above. 
@chr15tophe is this still an issue for you? Thank you!

**Comment by bryclee** [comment]
It looks like this is working for me as well now, tested on version 82

**Comment by sflorean** [comment]
Closing this as per the above comments.
