### ISSUE TITLE
Full Screen Videos Are Cropped and Unwatchable

### ISSUE THREAD

**Issue by cizkek** [mozilla-mobile/fenix#14533]
Just see the screenshots.
Xiaomi Mi9 Lite on latest Android.
No system setting related to fullscreen mode help with this issue.

![Screenshot_2020-08-31-16-57-33-603_org mozilla firefox](https://user-images.githubusercontent.com/70526034/91728528-e01aa900-ebab-11ea-90dd-4e1eb70f92c9.jpg)
![Screenshot_2020-08-31-16-57-44-923_org mozilla firefox](https://user-images.githubusercontent.com/70526034/91728536-e577f380-ebab-11ea-8266-86022417b57a.jpg)

**Comment by kbrosnan** [comment]
Duplicate #8252
