### ISSUE TITLE
FNX-5040 ⁃ MEDIA_ERR_UNKNOWN on New-York Post

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#1453]
Originally on https://github.com/webcompat/web-bugs/issues/28144

Fenix 1.0.1915 (Build #10971207)

1. Go to https://nypost.com/2019/03/21/alexandria-ocasio-cortez-flips-out-over-mocking-of-her-name/amp/

Video is not working.

So this is working on RDM.
This is working for me on Firefox Nightly Android with Pixel 2 device.
but indeed this is failing in Fenix.

**Comment by vesta0** [comment]
@karlcow can you please try again with the new nightly?

**Comment by sarentz** [comment]
@karlcow could this be drm related? we have not integrated widevine yet.

**Comment by kbrosnan** [comment]
This works for me using Fenix April 16th build on a Pixel 3
