### ISSUE TITLE
[Bug] Strange Bug in Page Rendering

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14537]
From a user:

Since updating to the new Firefox for Android (79.0.5) on my Redmi 7a (Android 10.QKQ1.191014.001), I keep encountering a bug in the rendering of pages.
What I do:
- I call up a news page with many links on it. Best example https://www.theguardian.com/international
- with every item that is of interest, I long tap and select "open link in new tab", but do not switch to that tab
- I repeat this for several items. Some times up to 15
- next i call up the list of open tabs
- first effect: on the list of tabs, where I should get thumbnails of all, many are blank. Not yet rendered apparently. Only some are.
- next effect: when switching to a blank tab, I get a blank page. Waiting a while changes nothing
- when I swipe down on such a blank page, at the top I get a small glimpse of the last page I was watching that was rendered properly
- switching to a properly rendered tab, then back again, does help sometimes. Often I have to repeat this several times. Sometimes, the page that was rendered properly before, is no more 

Please check, and get back to me.
I love your browser, and have been using it ever since the change from Netscape.

**Comment by vesta0** [comment]
@mcomella FYI

**Comment by liuche** [comment]
This could be related to the blank tabs bug that @csadilek has been looking at - perhaps these are some steps to reproduce? (Unless once the bugzilla bug is fixed, this won't be a problem anymore)

**Comment by vesta0** [comment]
User provided 2 screen shots - attaching here in case it's useful for investigation. 

![IMG_20200831_211335](https://user-images.githubusercontent.com/42752644/91813799-37973400-ec01-11ea-9a48-6eab0443e1b4.jpg)
![IMG_20200831_210917](https://user-images.githubusercontent.com/42752644/91813802-3960f780-ec01-11ea-9c82-1202a31b948c.jpg)

**Comment by boek** [comment]
dup of #5478
