### ISSUE TITLE
FNX-5041 ⁃ After a fling, recyclerview takes 2 clicks to activate

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#1454]
From my research, this is a bug in `MotionLayout` where the `RecyclerView` interprets the first click as the end of a fling and the second click as clicking on the list item. `MotionLayout` currently only uses `NestedScrollingParent2`, but {{NestedScrollingParent3 }}should contain the fix to this bug. [Follow the bug on Google Issue Tracker.](https://issuetracker.google.com/issues/128914828)

**Comment by vesta0** [comment]
Dup of #2726
