### ISSUE TITLE
[Bug] text selector triggered on suggested logins

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14549]
## Steps to reproduce
Open suggested logins for a website.
In the list of logins click and hold near the passwords feild
### Expected behavior
Nothing
### Actual behavior

![IMG-20200901-WA0000](https://user-images.githubusercontent.com/33252312/91767996-9b6a2e80-ebfa-11ea-945d-c121a11b2d94.jpg)

### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Nightly 2/10 with Pixel 2 (Android 9).

<img width="270" alt="rsz_screenshot_20210210-101324" src="https://user-images.githubusercontent.com/48799384/107484887-b7033900-6b8b-11eb-9c96-c459c5364966.png">

I will remove the qa:needed label for now.

**Comment by mariansima** [comment]
This issue was reproduced on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29
