### ISSUE TITLE
[Bug] Return to the Anyme X app does not work after Kanon login

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14541]
## Steps to reproduce
Install Anyme X app
Open kanonapp.com and authenticate with Google and a return to Anyme app button will appear
Click on it 

### Expected behavior
Anyme X app is opened (this is the behaviour in chrome)
### Actual behavior
Nothing, it does not launch the link
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by liuche** [comment]
Does it matter if you have the Open links in app selected or not?

**Comment by s-ankur** [comment]
No,same results
