### ISSUE TITLE
[Bug] After upgrading to Firefox 80 all Sync features turn themselves on

### ISSUE THREAD

**Issue by zsaile** [mozilla-mobile/fenix#14547]
## Steps to reproduce

Have Firefox on Android and Windows devices. 1 week ago i only had enabled Sync with open tabs and bookmarks

I have upgraded all browsers to the latest version. Then I noticed one of my PCs suddenly had a bunch of plugins which i had never installed there. Upon investigation i see sync is enabled for all features

### Expected behavior

The browsers should maintain their selected sync options

### Actual behavior

All Sync options including options, add-ons and history enabled themselves. My browsers all downloaded and synced their history even among devices i do not want this to happen

### Device information

* Android device: Samsung S9 Edge, Android 10
* Fenix version: 79.0.5

**Comment by kbrosnan** [comment]
Do you have them disabled on Desktop or any other instances of Firefox?

**Comment by zsaile** [comment]
I can't go back to check, but I'm 100% sure on my work laptop i only had open tabs and bookmarks. My 2 personal PCs should have been the same and phone the same. I updated Firefox on Friday on my work PC, and my phone over the weekend. When i logged into my work PC on monday i see new add-ons, and history of things i did on my phone on the weekend is on my work laptop. 

None of my machines would I have enabled history to cloud as that's something I never want, and Add-On/options sync was never there if i remember correctly. All the devices had all 6 sync options enabled when i checked this morning. 

I also noticed when i disabled history and add-ons but left options enabled, when i tried to re-enabled add-ons on my home PC it re-enabled it on my work PC. All the Sync settings should apply locally and not sync between devices i think otherwise i can't disabled history for one device while syncing options between my personal desktops.

**Comment by zsaile** [comment]
Also i didn't have Logins synced on my work PC, and yet the few passwords i had in there showed up on my home PC

**Comment by jawz101** [comment]
Regardless,This wouldn't be an Android issue

**Comment by liuche** [comment]
This is a worrisome bug, I wonder if we're losing this state somehow? Could be a Fenix bug, or maybe something that's happening when migrating accounts and there's some state that doesn't get updated properly/in time.

**Comment by eliserichards** [comment]
Let's get some eyes from AS on this

**Comment by liuche** [comment]
hey @jdragojevic, we're slammed with lots of bugs filed as we've hit release, and this seems like a concerning bug. Is there any investigation that your team could do, to see if there's more information that we could work with? Or ideas about things that might be coming from the AS/FxA side?

**Comment by rfk** [comment]
Thanks for the report, this is definitely a concerning bug!

To clarify, did you have to take any action to log in again on any of your devices, such as re-entering your account password?

We may be able to take a look at the state of your account on the backend and figure out what happened here. If you're willing to do so, please share the email address associated with your Firefox Account so that we can investigate further. You can do so confidentially by [filing a bug in Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Sync), which would let us restrict access to only Mozilla staff.

**Comment by mhammond** [comment]
>  All the Sync settings should apply locally and not sync between devices i think otherwise i can't disabled history for one device while syncing options between my personal desktops.

For better or worse, that's how sync currently works. [This desktop bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1215415) is where we are tracking the discussions around changing that, but it's difficult from a UX perspective as much as a technical one. However, it's certainly not expected that these options will turn on when the user didn't explicitly enable them anywhere - I'll have a think about scenarios which might cause this, but off the top of my head, the server migrations that are currently happening should not be able to cause it.

**Comment by rfk** [comment]
Cross-linking https://github.com/mozilla/application-services/issues/2161 and its friends for reference, where we've seen choose-what-to-sync weirdness in the past. I believe we shipped fixes for those already, though.

**Comment by zsaile** [comment]
@rfk No, i did not have to take any action after the upgrade. I didn't need to login back to my Firefox account. On my machine where i noticed the issue i did not have a 'primary' password set either. I simply noticed that when i started work on Monday a bunch of websites were broken. Then i noticed add-ons which should not be there. I then found sync enabled for all functions. 

I will file a bugzilla ticket with my sync account detail.

**Comment by zsaile** [comment]
Bug 1662612 Let me know if it's been restricted. I'm not sure if that the default. Ill drop my email in the comment there once you can confirm.

**Comment by rfk** [comment]
Thanks! I can't currently access the bug myself (I think you may have set "security sensitive" or similar flag, which blocks access to all but a handful of Mozilla staff) but will confirm once I have access and it's got the appropriate access controls in place.

**Comment by zsaile** [comment]
@rfk yes i did set that security and see the permissions are restricted. I added you to the cc

**Comment by rfk** [comment]
Great, yep, I have access now - let's continue the thread over in bugzilla. (Specifically the thread about investigating your account on the backend I mean, we should continue to use this bug for discussing the general issue)
