### ISSUE TITLE
[Bug] Search engine options are shown with ↖︎ Append arrow icons

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#14556]
## Steps to reproduce

- Open a new tab page with the keyboard up
- Tap “Search engine” chip

### Expected behavior

↖︎ Append arrow icons should not be displayed to the side of each search engine option, because it’s irrelevant.

### Actual behavior

↖︎ Append arrow icons are displayed.

<img width="360" src="https://user-images.githubusercontent.com/51007/91777406-d3499400-ec43-11ea-8c97-c3bc73c0030f.png">

**Comment by brampitoyo** [comment]
CC @boek

**Comment by hwinnemoe** [comment]
Duplicate of #13996

**Comment by s-ankur** [comment]
This is solved now @brampitoyo
