### ISSUE TITLE
[Bug] On New Tab Page with the keyboard up, tapping on the search provider icon dismisses the keyboard

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#14557]
## Steps to reproduce

- Open a New Tab Page with the keyboard up
- Tap on the search provider icon

### Expected behavior

It should do nothing. The text selection cursor should still be active.

### Actual behavior

The keyboard gets dismissed, with the scrim is still shown.

![search-provider-icon-dismiss-keyboard](https://user-images.githubusercontent.com/51007/91777643-8914e280-ec44-11ea-9384-881ec19d2be8.gif)

**Comment by brampitoyo** [comment]
CC @boek

**Comment by sflorean** [comment]
The issue is reproducible on the latest Nightly 9/25 with Pixel 3 (Android 11).
