### ISSUE TITLE
[Bug] When the phone wakes up after sleeping, the keyboard on the search screen is dismissed

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#14559]
## Steps to reproduce

- Open a New Tab Page with the keyboard up
- Press the power button on the phone to put it to sleep
- Press the power button again to wake it up

### Expected behavior

The address bar should remain selected with the text cursor active, and the keyboard should still be up.

![wake-up-keyboard-active](https://user-images.githubusercontent.com/51007/91778000-6df6a280-ec45-11ea-80d0-70e73490a0ec.gif)

### Actual behavior

The address bar is unselected, and the keyboard is dismissed.

This problem persists even after you’ve typed something into the address bar.

![wake-up-keyboard-inactive](https://user-images.githubusercontent.com/51007/91778124-b615c500-ec45-11ea-8a89-82e108d7b38d.gif)

**Comment by brampitoyo** [comment]
CC @boek

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/14 and 81.1.1-beta.4 with the following devices:
- Samsung Galaxy Note 10 (Android 10), 
- Google Pixel 3 (Android 11),
- LG G7 Fit (Android 8.0).
