### ISSUE TITLE
FNX-5042 ⁃ Progressbar for custom tabs should be at the bottom

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#1455]
Since I updated the default progress bar to be at the top of the toolbar, we will need to specify a bottom progress bar for a custom tab.

**Comment by vesta0** [comment]
Waiting for this[ A-C issue](https://github.com/mozilla-mobile/android-components/pull/2625) to land.

**Comment by mheubusch** [comment]
@ekager @sblatz can you confirm that this is blocked due to A-C, and not blocked awaiting UX input for bottom progress bar?

**Comment by sblatz** [comment]
@mheubusch correct: we do not need UX for this.

**Comment by pocmo** [comment]
Should no longer be blocked on AC (removing blocked label).

**Comment by bsurd** [comment]
This has now been verified by QA with the latest build.
