### ISSUE TITLE
[Bug] "Share to Desktop" functionality missing in initial share dialog on current version

### ISSUE THREAD

**Issue by Jahfry** [mozilla-mobile/fenix#14550]
## Notes: 
a) I'm unsure if this is a true bug, as in it was intended to be in the recent Firefox Android update but didn't make it, or if it is for some reason deprecated. 
b) If deprecated please adjust this report to be a Feature Request. 
c) It's entirely possible that there is a flag in Firefox or an already existing alternative that I'm not aware of to add Sync'ed devices back to the direct sharing menu in originating applications (see _Expected Behavior: Alternative Behavior_ below). If so please feel free to explain that alternative and mark this closed so long as it meets the Alternative Behavior. I don't want to cause busy work. 
d) I did some searching to see if it was already filed but didn't find it, apologies if this is a duplicate. 
e) Prior to making this report I made [a thread on Reddit that contains the use case](https://www.reddit.com/r/firefox/comments/ijm80s/recent_update_changed_core_mobile_share/). I'll paste a copy of _part_ of that Reddit post in the "Actual Behavior" section, but it may be beneficial to read the full post (didn't want to make this report TOO long). 

## Steps to reproduce
1) Have at least 2 devices to Firefox Sync (Android device + Desktop in this example)
2) Open a different application with a "Share" option. Examples: Reddit, Facebook, Google News, etc
3) Find an article you want to load on your Desktop for a future session
4) Click "Share" icon in that originating application
5) Select "Firefox"

### Expected behavior
When more than 1 Firefox sync device exists, present a "Share to [name]" for each device in the initial share dialog.

This was the default behavior for the previous versions of Firefox Android. 

_Alternative Behavior:_ Create a second app or widget called something like "Firefox Sync" that, when selected instead of the normal "Firefox" option in the share menu:

- is a very fast loading and allows selecting a device to send the share to from a list of connected Sync devices
- This could also include the local "Firefox on this device" as an option so that people selecting this second option can still reach the local browser if this was their intent. 

My guess is that something either in upcoming Android or current Fenix architecture broke the mechanism used in Fennec? In which case this alternative method of providing a second "stub" app for Firefox Sync sharing offers a way to get around the resources consumed by the current changed method. 

### Actual behavior
With the current version the behavior has changed from "Expected" to where when clicking "Share" in an originating app the link is immediately sent to the local Android browser. Then the user has to:

- let the app / page load
- click the "Share" icon in Firefox Android (second "Share" invocation for 1 link)
- manually close the tab in Firefox Android to avoid cluttering local browser
- manually switch back to the originating application

_Why this is a problem for this workflow:_

_**The worst thing is that these originating apps (Reddit, Facebook, news apps, etc) all have a chance of losing their place**_ where it might be an hour+ into a scrolling session, forcing user to find where left off or just give up and go to another app.

**Additional downsides:**

Firefox now has to fully open and display the link, which adds all of the overhead of:
- context switching apps (which is the cause of the originating app being prone to losing it's place) [significant time loss for user]
- rendering a page [time towards significant CPU invoked battery drain]
- having to invoke "share" again to get it to the desktop [time+effort for the user input]
- having to manually close the opened page on Android (previously if you shared to desktop from the direct share option the tab was not registered in the mobile app) [time+effort for the user input]

### Device information

* Android device: Essential PH-1 / Android 10
* Fenix version: 79.0.5 / Aug 17, 2020

**Comment by kbrosnan** [comment]
Duplicate #1523
