### ISSUE TITLE
[Bug] IllegalStateException  Cannot perform this action on a sealed instance.

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#14560]
https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9501355/?query=is%3Aunresolved%20sealed

This was found by the Google Play Store pre-launch randomized testing

## Steps to reproduce
seems to be varied:
a) from firefox pairing screen, in private mode, after text has been entered into email field [[video](https://storage.googleapis.com/play-mtaas-results-prod/org.mozilla.firefox/2015760553/FRT-27-en_US-portrait/video.mp4?GoogleAccessId=498997737111-pmn4sf5896c460sheh5fv3k1j1cq46t5@developer.gserviceaccount.com&Expires=1598919589&Signature=c8OoX4fdCeOyop/g4XdKaUSorzyJbmhxW3nf1Q889g9sUxDjjeGbkwSwmR8Q04ZG/tTWc5rWNIWElAg84zywwP8QFo8FRVnOBdNphvt0mk0zmfU0oDTCOi1rtm6JzdJEQaPPmaVrZKVarQNqsBQd3mHjoEZhHe7OnacQhIyHZ/7XDhpJybRM32oRD6148FRBWAuHpap09Ear4OaSXj5KN40QScZ/fwTSo/HyFp8dApsuLfWbKgiG5fQjgZ9BkQFGBN9p8Rqi/%2B%2BpTmmphwndGjFKCiaLcDwmt%2B4bs3el78TtxpzjjPy77kRjDqSaVBdwl8o2ta3lZmacpqMNMvzwEw%3D%3D)]

b) entering text into text box on accounts.google.com [[video](https://storage.googleapis.com/play-mtaas-results-prod/org.mozilla.firefox/2015760553/starqlteue-26-en_GB-portrait/video.mp4?GoogleAccessId=498997737111-pmn4sf5896c460sheh5fv3k1j1cq46t5@developer.gserviceaccount.com&Expires=1598919695&Signature=L2YQYnr/5ZHuwNx6eESsRslj4I/4FBb0k4mIxW22BpI1nG8X3/s0q7HwIIYH9cRsf9gyYdaeL3ZzQke2eqGsiEYletYLIyOnnE%2B0AbWF5AwIF9m7U6wsNz1bxmTi4eNuCw1N/9b9SI%2BWan3qFQLsI9sblYTo2kMB0/8oxBpGCdq0TZwyQl9S9jBc2PFrjrwhS7uf4xpx7tsgvWyEVerLRmliriYO76IzofLFp84DBuNiggW0uCJU9YKu%2BLHcwaVZXcIjsA/3xsMbX2yZxWNTKQMxKw6bH7K9Uo%2Bmmy7oj/0lET6BGiyNk0xWHB7jxZss9WR8KiRzPTTm28ZTQiDfVw%3D%3D)]

c) visiting textnow.com [[video](https://storage.googleapis.com/play-mtaas-results-prod/org.mozilla.firefox/2015760553/G8441-26-fr_FR-portrait/video.mp4?GoogleAccessId=498997737111-pmn4sf5896c460sheh5fv3k1j1cq46t5@developer.gserviceaccount.com&Expires=1598919799&Signature=c8FcknfxVWDVaWEfxe0TQq%2Bq34yYuyELJ8%2B2sU4wGS%2BYStdGdFU9wJKDPl2k368QM7ju4yBHB4hlGds0wNQmvFTtVzxXGT8epCxeC1QVjoBX0yL/9RTjOHqKtzrJG3vOkWgtF3juPebV7rq/ZrRS6zFEEpeefz6GNEym%2BWaYuzRXl9Kfvny1NB6MQ2qj9pGJlywKuDa%2BEeu3NehDVYJd6lMU8jwHvx40qBR%2BbWGRr0Buf15CWjOOuT/A75SiHDynC6q4YRsZGiyfUPkEK2QF6iK/WHg1sEl4HUMXnF7IIRJU6qWLHhnn8JGPUdLMAlqqVflUVLBEH%2Ba0qpybGj7uFQ%3D%3D)]

### Expected behavior
No crashing

### Actual behavior
Crashes, has some logs about accessibility

### Device information

* Android device: Android 8
* Fenix version: 80.1.1

**Comment by liuche** [comment]
cc @mcarare with a few more a11y looking crash bugs. (sorry to keep cc-ing you on these! let me know if they are different, but including you in case you have any ideas)

**Comment by liuche** [comment]
These only have 1 crash each, due to the Google randomized testing, and I don't see any sign of them in any other channels (nightly, beta), so I'm concerned that this might have been a problem introduced in a fix that we uplifted.

**Comment by mcarare** [comment]
I cannot see any of the videos attached. But, from the stack-trace it does not appear to be something wrong within our code, but rather something with the custom OS : Android 7.0 (DOOGEE-MIX-Helio_P25-20170818).

**Comment by liuche** [comment]
Thanks for the comments! Since I don't see anything else there, we can reopen if this shows up again.
