### ISSUE TITLE
FNX-5043 ⁃ [Bug] Session bug in private and normal browsing mode

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#1456]
## Steps to reproduce
1.Open fenix (in normal mode and private mode) and search or open web page.
2.Come back to the homescreen.

### Expected behavior
The save session button shows in the private browsing mode but not in the normal mode.

### Actual behavior
The save session button should show in the normal browsing mode not in the private browsing mode.

### Device information
* Android device: 8.0.0
* Fenix version: 1.0.1914 (Build#10961836
68.0a1-20190403060632)
Saturday 4/6 @ 6.36 PM

**Comment by bsurd** [comment]
I am able to reproduce this on the latest build, there is a save session button displayed in private browsing as mentioned by @Scripterr.

![button](https://user-images.githubusercontent.com/17178945/55789949-05dd7480-5ac4-11e9-9bda-d4a241a56426.jpg)

**Comment by Scripterr** [comment]
Hello @boek i can confirm that this issue is fixed in fenix recent build and the issue can be closed.👍
