### ISSUE TITLE
[Bug] Reader mode fails to preserve scroll position across back/forward

### ISSUE THREAD

**Issue by yump** [mozilla-mobile/fenix#14567]
## Steps to reproduce

1. Open a readerable page ([this one should work](https://archiveofourown.org/works/23747146/chapters/57032833)).

2. Enable reader mode.

3. Scroll partway down the page.

4. Press back.

5. Press forward.

### Expected behavior

Fenix displays reader mode view of page, scrolled to the same position as at the end of step 3.

### Actual behavior

Fenix displays reader mode view of page, scrolled to the top of the page.

### Device information

* Android device: Nokia 6.1, Android 10
* Fenix version: Beta 80.0.1 Build #2015758611

### User Story

I fumbled my phone, accidentally triggered the swipe-from-edge back gesture, and lost my place in what I was reading.  Don't like that.

**Comment by csadilek** [comment]
This needs GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1662519

**Comment by lobontiumira** [comment]
Reproducible on RC 89.1.0 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest builds:
- latest Nightly 96.0a1 (2021-11-23T05:55:53.255492).
- latest Beta (95.0.0 beta5).
- latest Release (94.1.2).

Device used: Xiaomi Mi11 Lite (Android11).
Closing the ticket.
