### ISSUE TITLE
Add telemetry to determine how frequently visited top sites are used

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#14565]
## Description & Product Manager / Data Scientist User Story
As a product manager, I need to know how users interact with frequently visited top sites so I can use this insight to prioritize bugs and enhancements related to this feature. 

## What questions will you answer with this data?
- What % of users open a frequently visited top site? And how often does a top site user open a top site in a day/week?
- What % of users use the carousel to access the second page of frequently visited top sites?
- What % of users long-press on a frequently visited top site?
- What % of users open a top site in a private tab?
- What % of users delete a frequently visited top site from history?

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using a Google Pixel 3a (Android 11)

## ► Pinned top sites

✔️ Open a pinned top site - Ping `bbed053a-798a-43da-94cd-199f36d3f1e0`
```
        {
          "category": "top_sites",
          "name": "open_in_new_tab",
          "timestamp": 13105
        },
        {
          "category": "top_sites",
          "name": "open_pinned",
          "timestamp": 13106
        }
```
✔️ Long tap + Open in a private tab - Ping `a20d9a71-0684-4824-8cff-7f73e9867f1d`

```
{
          "category": "top_sites",
          "extra": {
            "type": "PINNED"
          },
          "name": "long_press",
          "timestamp": 2773
        },
        {
          "category": "top_sites",
          "name": "open_in_private_tab",
          "timestamp": 3785
        }
```

✔️ Long tap + Delete a pinned top site - Ping `839099f7-b949-4648-bec7-73ebb88b1811`
```
{
          "category": "top_sites",
          "extra": {
            "type": "PINNED"
          },
          "name": "long_press",
          "timestamp": 2015
        },
        {
          "category": "top_sites",
          "name": "remove",
          "timestamp": 3240
        }
```

## **► Carousel movement + page number the carousel is now on** 
Ping `b80681f4-9bc3-4758-812f-1957bb9902e8`

```
 {
          "category": "top_sites",
          "extra": {
            "page": "1"
          },
          "name": "swipe_carousel",
          "timestamp": 959
        }
```

## **► Frequently visited top sites**
✔️ Open a frequently visited top site -  Ping `6c8b6567-f6c6-4364-9244-3a2327c65f96`
```
{
          "category": "top_sites",
          "name": "open_in_new_tab",
          "timestamp": 1284
        },
        {
          "category": "top_sites",
          "name": "open_frecency",
          "timestamp": 1285
        }
```

✔️ Long tap + Open in a private tab  -  Ping `fc254d36-cd62-4b66-9d3c-4402746b1d6c`
```
{
          "category": "top_sites",
          "extra": {
            "type": "FRECENT"
          },
          "name": "long_press",
          "timestamp": 2872
        },
        {
          "category": "top_sites",
          "name": "open_in_private_tab",
          "timestamp": 4306
        }
```

✔️ Long tap + delete a frequently visited top site from history -  Ping `3f0fca30-0846-4520-acda-28790`
```
{
          "category": "top_sites",
          "extra": {
            "type": "FRECENT"
          },
          "name": "long_press",
          "timestamp": 1035
        },
        {
          "category": "top_sites",
          "name": "remove",
          "timestamp": 1880
        }
```

**Comment by AndiAJ** [comment]
@sblatz I've opened #15265 because I've noticed that in the metrics ping the "metrics.has_top_sites" remains set to **false**
