### ISSUE TITLE
[Bug] Mutilple failed download messages "Null Download failed"

### ISSUE THREAD

**Issue by halbGefressen** [mozilla-mobile/fenix#14574]
## Steps to reproduce
Download a file which makes the download fail multiple times, then swipe away the "Download failed" messages.
### Expected behavior
The message disappears instantly.
### Actual behavior
The message stays for around 15 seconds saying "null Download failed"
### Device information
Oneplus 6T Stock ROM
* Android device: ?
* Fenix version: ?

**Comment by hwinnemoe** [comment]
Please also include the used Firefox version (_Settings_, _About Firefox_) and your phone's android version.

**Comment by Amejia481** [comment]
@halbGefressen could you include any particular file (link) to download?

**Comment by halbGefressen** [comment]
I can't do that because the failed download occured on a private university website, but I can provide a screenshot of it happening: 
![Screenshot_20200819-160407__01](https://user-images.githubusercontent.com/17833082/91863783-c6429a00-ec6f-11ea-9d44-aef17ec80f51.jpg)

**Comment by hwinnemoe** [comment]
Looks like #7531

**Comment by liuche** [comment]
Thanks for filing and the screenshot, we'll be working on a GV fix that you can follow along in #7531.
