### ISSUE TITLE
[Bug] Upgrade from fennec removes unnecessary settings

### ISSUE THREAD

**Issue by jorsn** [mozilla-mobile/fenix#14572]
## Steps to reproduce

get the new fenix auto-installed by accident if you just wanted to quickly look something up in your favourite search engine.

### Expected behavior

Fenix informs me: This version is new. Settings options have changed in an inconsistent way.
It asks: Do you want to configure now or proceed with the best approximation (since new option set is almost strictly smaller than before this shouldn't be a problem – tracking settings can be inferred from old with simple heuristics, e.g. cookie settings and do-not-track header).

In any case: All old configured search engines are available and the default engine stays the same.

### Actual behavior

The default search engine is google, old search engines are removed and for people using e.g. startpage there is no simple way to add it (#13484).

### Device information

* Android device: Motorola Moto 4G Play in Germany
* Fenix version: 79.0.5

**Comment by liuche** [comment]
Thanks for filing, this sounds frustrating. Fenix does provide an onboarding, and it does port over the settings that it can.

For adding a custom search engine, this is possibled: you can add startpage as a search engine by going to Settings > Search > + Add search engine
and using this as the search string:
https://www.startpage.com/do/dsearch?query=%s

**Comment by jorsn** [comment]
Well, one can debate what the best onboarding would be, but the expected behaviour

> In any case: All old configured search engines are available and the default engine stays the same.

is clearly not in effect. I cannot just open fenix and query my favourite search engine. When I want to quickly look something up, i don't want to start configuring, and I'm not the average user who gets annoyed quicker than me: E.g. I once patched firefox to run on musl libc. I quickly added my search engine (searx tunneled from localhost via ssh), but I would not consider this an easy way for average people. My relatives were complaining.

Anyway, for my friends I quickly hacked up a page where they can find the search string for their favorite engine. It's not publicly available because I don't have the necessary legal stuff (imprint, data policy), but the source is [on sourcehut](https://sr.ht/~jorsn/fenix-bang/), if anyone wants to put it on a php+json-enabled server or any web server for the slower javascript version.
