### ISSUE TITLE
[Bug] Intermittent failure debug(T) add custom engine io.mockk.MockKException: Bad recording sequence. State: SafeLoggingState

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#14573]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=314526471&repo=fenix

[task 2020-09-01T00:21:22.584Z]   TEST: add custom engine
[task 2020-09-01T00:21:22.584Z]     [Robolectric] org.mozilla.fenix.components.searchengine.FenixSearchEngineProviderTest.add custom engine: sdk=28; resources=LEGACY
[task 2020-09-01T00:21:22.584Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-09-01T00:21:22.684Z]     I/AssetManager: no overlays.list file found
[task 2020-09-01T00:21:22.684Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-09-01T00:21:22.684Z]     I [glean/GleanCrashReporterService] No crashes to record, or file not found.
[task 2020-09-01T00:21:22.684Z]     D/StrictMode: onThreadPolicyViolation; policy=65597
[task 2020-09-01T00:21:22.684Z]     D/StrictMode: StrictMode policy violation; ~duration=0 ms: android.os.strictmode.DiskWriteViolation
[task 2020-09-01T00:21:22.684Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.$$robo$$android_os_StrictMode_AndroidBlockGuardPolicy$onWriteToDisk(StrictMode.java:1460)
[task 2020-09-01T00:21:22.684Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java)
[task 2020-09-01T00:21:22.684Z]     at libcore.io.BlockGuardOs.$$robo$$libcore_io_BlockGuardOs$mkdir(BlockGuardOs.java:196)
[task 2020-09-01T00:21:22.684Z]     at libcore.io.BlockGuardOs.mkdir(BlockGuardOs.java)
[task 2020-09-01T00:21:22.684Z]     at android.system.Os.$$robo$$android_system_Os$mkdir(Os.java:323)
[task 2020-09-01T00:21:22.684Z]     at android.system.Os.mkdir(Os.java)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:608)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:596)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getPreferencesDir(ContextImpl.java:552)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.getPreferencesDir(ContextImpl.java)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferencesPath(ContextImpl.java:747)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferences(ContextImpl.java:400)
[task 2020-09-01T00:21:22.684Z]     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java)
[task 2020-09-01T00:21:22.684Z]     at android.content.ContextWrapper.$$robo$$android_content_ContextWrapper$getSharedPreferences(ContextWrapper.java:174)
[task 2020-09-01T00:21:22.684Z]     at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java)
[task 2020-09-01T00:21:22.684Z]     at mozilla.components.service.location.MozillaLocationServiceKt.regionCache(MozillaLocationService.kt:121)
[task 2020-09-01T00:21:22.684Z]     at mozilla.components.service.location.MozillaLocationServiceKt.hasCachedRegion(MozillaLocationService.kt:100)
[task 2020-09-01T00:21:22.684Z]     at mozilla.components.service.location.MozillaLocationServiceKt.access$hasCachedRegion(MozillaLocationService.kt:1)
[task 2020-09-01T00:21:22.684Z]     at mozilla.components.service.location.MozillaLocationService.hasRegionCached(MozillaLocationService.kt:82)
[task 2020-09-01T00:21:22.684Z]     at org.mozilla.fenix.components.searchengine.FenixSearchEngineProvider.<init>(FenixSearchEngineProvider.kt:40)
[task 2020-09-01T00:21:22.684Z]     at org.mozilla.fenix.components.searchengine.FakeFenixSearchEngineProvider.<init>(FenixSearchEngineProviderTest.kt:102)
[task 2020-09-01T00:21:22.684Z]     at org.mozilla.fenix.components.searchengine.FenixSearchEngineProviderTest.before(FenixSearchEngineProviderTest.kt:34)
[task 2020-09-01T00:21:22.684Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-09-01T00:21:22.684Z]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-09-01T00:21:22.684Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-09-01T00:21:22.684Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-09-01T00:21:22.684Z]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-09-01T00:21:22.684Z]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-09-01T00:21:22.684Z]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-09-01T00:21:22.684Z]     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[task 2020-09-01T00:21:22.684Z]     at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
[task 2020-09-01T00:21:22.684Z]     at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
[task 2020-09-01T00:21:22.684Z]     at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-09-01T00:21:22.684Z]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-09-01T00:21:22.685Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-09-01T00:21:22.685Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-09-01T00:21:22.685Z]     at java.lang.Thread.run(Thread.java:748)
[task 2020-09-01T00:21:22.685Z]     
[task 2020-09-01T00:21:22.685Z]     D/StrictMode: onThreadPolicyViolation; policy=65597
[task 2020-09-01T00:21:22.685Z]     D/StrictMode: StrictMode policy violation; ~duration=0 ms: android.os.strictmode.DiskWriteViolation
[task 2020-09-01T00:21:22.685Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.$$robo$$android_os_StrictMode_AndroidBlockGuardPolicy$onWriteToDisk(StrictMode.java:1460)
[task 2020-09-01T00:21:22.685Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java)
[task 2020-09-01T00:21:22.685Z]     at libcore.io.BlockGuardOs.$$robo$$libcore_io_BlockGuardOs$chmod(BlockGuardOs.java:72)
[task 2020-09-01T00:21:22.685Z]     at libcore.io.BlockGuardOs.chmod(BlockGuardOs.java)
[task 2020-09-01T00:21:22.685Z]     at android.system.Os.$$robo$$android_system_Os$chmod(Os.java:85)
[task 2020-09-01T00:21:22.685Z]     at android.system.Os.chmod(Os.java)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:609)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:596)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getPreferencesDir(ContextImpl.java:552)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.getPreferencesDir(ContextImpl.java)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferencesPath(ContextImpl.java:747)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferences(ContextImpl.java:400)
[task 2020-09-01T00:21:22.685Z]     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java)
[task 2020-09-01T00:21:22.685Z]     at android.content.ContextWrapper.$$robo$$android_content_ContextWrapper$getSharedPreferences(ContextWrapper.java:174)
[task 2020-09-01T00:21:22.685Z]     at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java)
[task 2020-09-01T00:21:22.685Z]     at mozilla.components.service.location.MozillaLocationServiceKt.regionCache(MozillaLocationService.kt:121)
[task 2020-09-01T00:21:22.685Z]     at mozilla.components.service.location.MozillaLocationServiceKt.hasCachedRegion(MozillaLocationService.kt:100)
[task 2020-09-01T00:21:22.685Z]     at mozilla.components.service.location.MozillaLocationServiceKt.access$hasCachedRegion(MozillaLocationService.kt:1)
[task 2020-09-01T00:21:22.685Z]     at mozilla.components.service.location.MozillaLocationService.hasRegionCached(MozillaLocationService.kt:82)
[task 2020-09-01T00:21:22.685Z]     at org.mozilla.fenix.components.searchengine.FenixSearchEngineProvider.<init>(FenixSearchEngineProvider.kt:40)
[task 2020-09-01T00:21:22.686Z]     at org.mozilla.fenix.components.searchengine.FakeFenixSearchEngineProvider.<init>(FenixSearchEngineProviderTest.kt:102)
[task 2020-09-01T00:21:22.686Z]     at org.mozilla.fenix.components.searchengine.FenixSearchEngineProviderTest.before(FenixSearchEngineProviderTest.kt:34)
[task 2020-09-01T00:21:22.686Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-09-01T00:21:22.686Z]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-09-01T00:21:22.686Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-09-01T00:21:22.686Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-09-01T00:21:22.686Z]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-09-01T00:21:22.686Z]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-09-01T00:21:22.686Z]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-09-01T00:21:22.686Z]     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[task 2020-09-01T00:21:22.686Z]     at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
[task 2020-09-01T00:21:22.686Z]     at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
[task 2020-09-01T00:21:22.686Z]     at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-09-01T00:21:22.686Z]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-09-01T00:21:22.686Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-09-01T00:21:22.686Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-09-01T00:21:22.686Z]     at java.lang.Thread.run(Thread.java:748)
[task 2020-09-01T00:21:22.686Z]     
[task 2020-09-01T00:21:23.784Z]   FAILURE
[task 2020-09-01T00:21:23.884Z] 
[task 2020-09-01T00:21:23.884Z] io.mockk.MockKException: Bad recording sequence. State: SafeLoggingState
[task 2020-09-01T00:21:23.885Z] 	at io.mockk.impl.recording.states.CallRecordingState.cancelAndThrowBadRecordingState(CallRecordingState.kt:32)
[task 2020-09-01T00:21:23.885Z] 	at io.mockk.impl.recording.states.CallRecordingState.estimateCallRounds(CallRecordingState.kt:20)
[task 2020-09-01T00:21:23.885Z] 	at io.mockk.impl.recording.CommonCallRecorder.estimateCallRounds(CommonCallRecorder.kt:55)
[task 2020-09-01T00:21:23.885Z] 	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:46)
[task 2020-09-01T00:21:23.885Z] 	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
[task 2020-09-01T00:21:23.885Z] 	at io.mockk.MockKDsl.internalEvery(API.kt:92)
[task 2020-09-01T00:21:23.885Z] 	at io.mockk.MockKKt.every(MockK.kt:98)
[task 2020-09-01T00:21:23.885Z] 	at org.mozilla.fenix.components.searchengine.FakeFenixSearchEngineProvider.mockSearchEngine(FenixSearchEngineProviderTest.kt:164)
[task 2020-09-01T00:21:23.885Z] 	at org.mozilla.fenix.components.searchengine.FenixSearchEngineProviderTest.before(FenixSearchEngineProviderTest.kt:38)
[task 2020-09-01T00:21:23.885Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-09-01T00:21:23.885Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-09-01T00:21:23.885Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-09-01T00:21:23.885Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-09-01T00:21:23.885Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-09-01T00:21:23.885Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-09-01T00:21:23.885Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-09-01T00:21:23.885Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[task 2020-09-01T00:21:23.885Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
[task 2020-09-01T00:21:23.885Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
[task 2020-09-01T00:21:23.885Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-09-01T00:21:23.885Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-09-01T00:21:23.885Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-09-01T00:21:23.885Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-09-01T00:21:23.885Z] 	at java.lang.Thread.run(Thread.java:748)
[task 2020-09-01T00:21:23.885Z] 
[task 2020-09-01T00:21:23.885Z]   TEST: GIVEN sharedprefs contains installed engines WHEN installedSearchEngineIdentifiers THEN defaultEngines + customEngines ids are returned
[task 2020-09-01T00:21:23.885Z]     [Robolectric] org.mozilla.fenix.components.searchengine.FenixSearchEngineProviderTest.GIVEN sharedprefs contains installed engines WHEN installedSearchEngineIdentifiers THEN defaultEngines + customEngines ids are returned: sdk=28; resources=LEGACY
[task 2020-09-01T00:21:23.885Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-09-01T00:21:23.885Z]     I/AssetManager: no overlays.list file found
[task 2020-09-01T00:21:24.684Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-09-01T00:21:26.084Z]     I/MonitoringInstr: Setting context classloader to '', Original: 'org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader@5699aa60'
[task 2020-09-01T00:21:26.184Z]   FAILURE

**Comment by amedyne** [comment]
@Archaeopteryx Are we still seeing this?

**Comment by Archaeopteryx** [comment]
Based on https://sql.telemetry.mozilla.org/queries/70708 this has been observed only once.
