### ISSUE TITLE
[Bug ) When adding a shortcut to the Android home screen, Firefox doesn't retain edits to the shortcut name

### ISSUE THREAD

**Issue by winslow-c** [mozilla-mobile/fenix#14578]
## Steps to reproduce
Open https://www.npr.org/programs/weekend-edition-saturday/
Choose "Add to home screen". A name-editing dialog box appears.
Edit the name. And choose"add."

### Expected behavior
A new icon should appear on the home screen with the edited name.

### Actual behavior
A new icon appears, but with the original page name.

### Device information
Lenovo tablet
* Android device: ?
Yes
* Fenix version: ?
79.0.5 (Build #2015758619)

**Comment by s-ankur** [comment]
Not repoducible in nightly

**Comment by liuche** [comment]
@winslow-c do you see this in Firefox Nightly, on your device?

**Comment by winslow-c** [comment]
I'm not using Nightly; I'm using this:

79.0.5 (Build #2015758619)
AC: 48.0.15, 8755ac0cd
GV: 79.0.1-20200813192915
AS: 61.0.10

Just discovered that this issue appears inconsistently. 

The following two links *will not* let me successfully edit the shortcut names:
- https://www.nytimes.com/
- https://www.npr.org/programs/weekend-edition-sunday/

The following two links (children of the links above) *will* let me edit the names:
- https://www.nytimes.com/2020/09/02/nyregion/colleges-universities-covid-parties.html?action=click&module=Top%20Stories&pgtype=Homepage
- https://www.npr.org/2020/08/30/907600127/politics-chat-donald-trumps-re-election-challenges

It makes me wonder if there is some metadata element that is overriding the edits made by the user.

**Comment by s-ankur** [comment]
Is it possible that you already have a https://www.nytimes.com/ shortcut on your home screen when you tried to add another one? The new shortcut will always take the name of the old shortcut

**Comment by winslow-c** [comment]
You nailed it -- problem solved!
