### ISSUE TITLE
[Bug] Cannot choose search engine with one click.

### ISSUE THREAD

**Issue by J-J-Chiarella** [mozilla-mobile/fenix#14589]
### Expected behavior

After typing search keywords in the text/URL bar, the user can click an icon at bottom of window to choose search engine.

Now I cannot do that. One can only search directly from text/URL bar with the default search engine.

79.0.5

Android 7.1.1

### Device information

* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment]
Duplicate #4333
