### ISSUE TITLE
[Bug] pdf or excel files are less Kb size

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#14583]
## Steps to reproduce
Login to hdfc netbanking page, download account statement in pdf or excel. The downloaded file is 1.57KB or less than actual size. 
Works fine with edge

### Expected behavior
Files should download properly 

### Actual behavior
Files are of less size around 1kb

### Device information

* Android device: ? Rog 3
* Fenix version: ? Latest

**Comment by hwinnemoe** [comment]
Duplicate of/Related to #7531

**Comment by kbrosnan** [comment]
Yes this is us downloading something like a html error page instead of the correct document. Closing as a duplicate.
