### ISSUE TITLE
[Bug]Access data are no longer saved for certain URLs since the update to 79.0.5

### ISSUE THREAD

**Issue by Rewe2000** [mozilla-mobile/fenix#14584]
## Steps to reproduce
Try to save the username and password in Firefox 79.0.5 for the following URL ( **https://192.168.50.33:8083/fhem** ), it is available in the saved access data, but it is not used for login, the login fields are not filled with it.
URLs without an appended port (**: xxxx**) all work.

### Expected behavior
Username and password should be saved just like in the desktop version for URL addresses with an attached port (**: 8083**). Just as it was possible before the Fenix version before 79.0.5.

### Actual behavior
The saved login data is available, but is no longer used for the above URL.

### Device information

* Android device: Samsung SM-A520F, Android 8.0.0, Samsung Experience-Version 9.0
* Fenix version: 79.0.5 **and** 80.0.1beta

**Comment by clientenq** [comment]
Can not reproduce on other domains with specific ports in url. @Rewe2000 any special page code used on the local network?

**Comment by kbrosnan** [comment]
Duplicate #13941

**Comment by Rewe2000** [comment]
**@kbrosnan:** Please reopen, it concerns the same problem as in report # 13961, no third-party providers (password managers) are used, the problem has only existed since 79.0.5. It is very annoying when you have to re-enter your username and password every time.

**Comment by RES-1** [comment]
Same here. Please reopen this bug!
