### ISSUE TITLE
[Bug ]Incomplete error page displayed if network cuts off mid page load.

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14586]
## Steps to reproduce
Load a page, turn off wifi/data mid page load. An error page is shown, but incomplete.

### Expected behavior
A proper error page.

### Actual behavior
An incomplete error page.

### Device information
Android 5.1.1 and Android 9 

* Fenix version: Nightly 200831 06:01 (Build #2015761137)

![Screenshot_2020-09-01-08-43-15](https://user-images.githubusercontent.com/51329626/91895744-432d3e00-ec87-11ea-99a3-dd013f231667.png)

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1662794
