### ISSUE TITLE
[Bug] Suggested Logins : arrow is upside down

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14581]
## Steps to reproduce
Open a website for which you have a number of logins
Click on the password feild and observe the suggested logins pane below
### Expected behavior
There is an up arrow on the pane, indicating that it will open upward
### Actual behavior
There is a down arrow on the pane, indicating that it will close somehow.
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
![IMG-20200901-WA0003](https://user-images.githubusercontent.com/33252312/91874076-66f88000-ec97-11ea-8386-dae3016ebcaf.jpg)
It looks to me as if this button will close the pane and I think most other apps have the opposite convention

**Comment by ekager** [comment]
This is the same convention/style we use on the homescreen when you have tabs in a collection for the "expand" action. I will tag UX for feedback.

**Comment by s-ankur** [comment]
Collections expand downwards so it does make sense there.

**Comment by clientenq** [comment]
The suggestions list arrow is an extention indicator. The arrow indicates the list will extend. It does not indicate the location of the sceen that will be used when you use it. It would not make sence to change the arrow direction considering it should be consisten regardles of the screen position and state of the list. Place the list at the top or centre and it is still indication the list will extend. Change the arrow to the direction of the screen that will be used and it can get confusing when the screen is in the centre.

**Comment by apbitner** [comment]
As @ekager noted, we are using the down arrow to indicate a panel can be expanded, and the up arrow to collapse it, so this follows suit.

**Comment by s-ankur** [comment]
@apbitner 

As I understand it, **arrows should reflect direction of motion** otherwise it has a very jarring effect 

I actually researched this for some time and I have yet to find an app that follows fenix's current behavior for expanding upwards. Most apps that I found follow the bottom sheet concept which does not use any arrows and just presents a floating sheet that can be expanded or collapsed by swiping. The rest of the apps use my suggestion of using up arrows to reflect upward movement. Examples

1. Most launchers use up arrow to indicate that the app drawer is going to open upward. This alone means that most users are already familiar with this type of action
![adw-2-640x379](https://user-images.githubusercontent.com/33252312/92306900-3f175e00-efb0-11ea-9064-40dfeb507553.png)

2. Multiple posts on Stackoverflow mentioning my suggestion as their behavior
https://stackoverflow.com/questions/28659209/rotate-imageview-in-sliding-up-panel
![](https://i.stack.imgur.com/pwUji.png)
https://stackoverflow.com/questions/28304425/imageview-disappear-in-sliding-up-panel
![](https://i.stack.imgur.com/Y7mWN.png)

3. Here is the Google IO 2018 app showing a very similar behavior, notice the direction of the arrow is the same as given in my suggestion
![](https://miro.medium.com/max/179/1*RD_k4XITEBGUBYJOnA93SA.gif)

With these examples and many more I think it can be shown that the current fenix behavior is unintuitive to a lot of android users
