### ISSUE TITLE
FNX-5044 ⁃ Add a notification for background play

### ISSUE THREAD

**Issue by akarshanbiswas** [mozilla-mobile/fenix#1458]
### Why/User Benefit/User Problem
Users will be able to control playback while firefox/fenix is minimized just like in fennec

### What / Requirements
A persistent notification when fenix plays a media

### Acceptance Criteria (how do I know when I’m done?)
When fenix behaves same as fennec when playing media.

**Comment by kbrosnan** [comment]
dupe of #1112
