### ISSUE TITLE
[Bug] Cannot click out of URL bar

### ISSUE THREAD

**Issue by J-J-Chiarella** [mozilla-mobile/fenix#14588]
When I go to touch the tab icon to switch icons and I mis-click/mis-tap on the URL bar, I cannot tap outside of the URL bar to return to the webpage I am currently viewing or access tabs. I must move my thumb to bottom of screen to hit the "Back" arrow icon of the Android operating system.

**Comment by kbrosnan** [comment]
This works for me using the new search view on Nightly. Assuming this is filed against release where the search view is full page.
