### ISSUE TITLE
[Bug] If "tab" menu is  long pressed, it leads to force choosing of 3 menus, ignoring all other actions.

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#14594]
## Steps to reproduce
If the tab open menu is long pressed, it leads to 3 options, ***open a new tab,*** ***open a new private tab,*** and ***close tab*** Now, if you try tapping elsewhere except for these 3 sub menus, it does nothing. Expected behavior should be that the sub menu closes on tapping elsewhere on the screen.

### Expected behavior
Tapping elsewhere should close the menu.
### Actual behavior
Tapping elsewhere doesn't close the menu, leading to force press one of the options.

### Device information
Android 5.1.1 and Android 9

Fenix version: Nightly latest build

***The 3 submenu on long tapping tab options***
![Screenshot_2020-09-01-14-40-10](https://user-images.githubusercontent.com/51329626/91908988-ec7e2f00-ec9b-11ea-97d2-050295c783ef.png)

**Comment by person808** [comment]
dupe of #14399

**Comment by kbrosnan** [comment]
Closing as a duplicate
