### ISSUE TITLE
[Bug] Revoked certificate from badSSL is accepted when it should be rejected

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#14597]
## Steps to reproduce
* Visit https://revoked.badssl.com/

### Expected behavior
Error page `SEC_ERROR_REVOKED_CERTIFICATE`

### Actual behavior
Page loads

### Device information

* Android device: Pixel 3 Android 10
* Fenix version: Nightly v82

**Comment by evilpie** [comment]
From my understanding no mobile browser does OCSP checking because of the connection overhead. I am however not sure why this domain is not in OneCRL, which we hopefully support on mobile. I think @april might know.

**Comment by april** [comment]
I'm pretty sure it is supposed to be in OneCRL for testing purposes. It does show up as revoked in desktop.

**Comment by april** [comment]
I do see this in OneCRL:

```
    {
      "schema": 1480349159276,
      "details": {
        "bug": "https://bugzilla.mozilla.org/show_bug.cgi?id=1300977",
        "who": ".",
        "why": ".",
        "name": "revoked.badssl.com certificate",
        "created": "2016-09-09T16:26:08Z"
      },
      "enabled": true,
      "issuerName": "ME0xCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxJzAlBgNVBAMTHkRpZ2lDZXJ0IFNIQTIgU2VjdXJlIFNlcnZlciBDQQ==",
      "serialNumber": "Aa8e+91erglSMgsk/mtVaA==",
      "id": "4b778ec2-ef45-c5b2-dc44-b00c87b11741",
      "last_modified": 1480349164410
    }
```

But given its age, it's probably not the right revocation. The current cert goes from 2019-2021.

**Comment by evilpie** [comment]
I was looking at this: https://crt.sh/?id=1988442812. I don't actually know how to query OneCRL directly.

**Comment by april** [comment]
It is kept here: https://firefox.settings.services.mozilla.com/v1/buckets/blocklists/collections/certificates/records

**Comment by april** [comment]
Since it's not in OneCRL currently, I will go ahead and open a bug to get it done today.

**Comment by april** [comment]
Sorry for the delay, things got lost in the shuffle.

https://bugzilla.mozilla.org/show_bug.cgi?id=1664854

**Comment by april** [comment]
Looks like the cert is now in OneCRL. Let me know if it doesn't show up as being blocked.

**Comment by april** [comment]
^^ @kbrosnan, ping.

**Comment by kbrosnan** [comment]
This is resolved in 83.
