### ISSUE TITLE
FNX-5045 ⁃ [Bug] History entries looks like incomplete, title not shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#1459]
## Steps to reproduce
Browse to several websites
Go to Library -> History

### Expected behavior
All history entries are shown the same way, title + url

### Actual behavior
Some titles are missing

### Device information
* Android device: Pixel 3
* Fenix version: Build 10971207 Apr 4th

See screenshot:
![Screenshot](https://user-images.githubusercontent.com/1897507/55717060-ca29a880-59f8-11e9-9732-0c84730b707b.png)UNITO-UNDERSCORE!20190408-121502!

**Comment by cadeyrn** [comment]
Regression by #1395.

**Comment by thanuj10** [comment]
Can confirm this issue on Nokia 6.1+/Android 9.
4/8 Build(Latest)

**Comment by bsurd** [comment]
There still seems to be some issues with this.

#### STR:
1. Search for any term.
2. Open one of the search results.

#### Expected:
All visited sites have a title displayed.

#### Actual:
Initial google search redirects have a title displayed, but the actual site is missing the title.

#### Info:
**[Video](https://drive.google.com/open?id=1LHZzL29yLJWcePW8S5sxmW2xHkvPLstJ)**

![screen](https://user-images.githubusercontent.com/17178945/55865843-d5f7a500-5b87-11e9-9e42-34f33c48bba5.png)

**Comment by bsurd** [comment]
This has now been verified. All URL's have a title displayed.
