### ISSUE TITLE
[Bug] Top Sites labels have too low contrast

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14602]
## Steps to reproduce

1. Open home

### Expected behavior

Top sites labels should use a darker gray or black to improve contrast. Edge does a better job here. 

### Actual behavior

Top Sites text is small and hard to read. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by cadeyrn** [comment]
Duplicate of #13850.
