### ISSUE TITLE
[Bug] Add-ons had silently become completely non-functional despite being enabled

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#14608]
## Steps to reproduce

I started wondering why I was getting all kinds of unwanted popups and cookie notices while browsing. 

I tried to go into my uBlock Origin setttings to refresh my blocklists, but was suddenly unable to access its "settings" button and page anywhere! It was neither available in the add-on menu nor on the add-ons page itself.

There's nothing to reproduce - the add-ons had just stopped working. I've included video of the problem below.

### Expected behavior

The add-on settings menu items and pages should be always available.

### Actual behavior

To fix the issue, I first tried force stopping the browser, then rebooting my phone. No dice.

What finally helped was completely disabling and re-enabling _all_ my addons - this finally returned them to a functional state with their "Settings" menu item returning to the interface. 

It seems I have been running non-functional add-ons for a few days now in the browser (none of them, including uBlock Origin, seem to have worked at all due to this issue), exposing me to cookies and other unscrupulous website features like fingerprinting and so forth.

This is a pretty big security issue. I feel pretty violated, honestly. You can say it's a beta browser but I've been forced on to it by developers due to about:config missing from the baseline build.  How is it possible for the add-ons to just get disabled while the browser believes they are enabled? 

I would have liked to attach a video I recorded that shows how the settings menu is not available until I re-enabled the add-on, but Github does not support video attachments. 

I have now begrudgingly uploaded it to Imgur, but must I remind you that Bugzilla supports proper attachments? How am I supposed to show you the issue, or repro the bug if I can't directly attach video? When is Mozilla Send coming back, I could have used that?

Here is the bug in action on video: https://imgur.com/a/GNQmR9n

### Device information

* Android device: Xiaomi Mi A1
* OS version: QQ3A.200805.001 PixelExperience_Plus_tissot-10.0-20200815-1228-OFFICIAL
* Fenix version: 
80.0.1-beta.2 (Build #2015758611)
AC: 54.0.2, ec7e84aa7
GV: 80.0-20200811133449
AS: 61.0.10

**Comment by eberhardweber** [comment]
Now that I reopened my browser, all of my add-ons had been uninstalled _completely_. The add-ons menu works, but is empty, and none of the previously installed and enabled add-ons are installed.

**Comment by DavidJCobb** [comment]
Losing add-ons shortly after disabling them sounds like #11589?

**Comment by agi** [comment]
@eberhardweber Hi! Thanks for the report. I somehow the addon database was corrupted. If you see it again could you try to collect logs? It's really hard to investigate this issue otherwise.

**Comment by amedyne** [comment]
@eberhardweber Any logs you can share to further investigate this?
