### ISSUE TITLE
If time is incorrectly set, the error page shows "Address not found" instead of "Bad ssl certificate, check your time"

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#14604]
Set my time to be 2 Aug instesd of 2 Sep and tried https://www.google.com. Error page shows "address not found, check if you typed ww instead of www or check if you have a working internet connection." Trying the same thing with Chrome, and other Chromium based browsers showed ***Your clock is behind, bad ssl certificate***

![Screenshot_2020-09-02-17-20-51](https://user-images.githubusercontent.com/51329626/91939596-a2ba3680-ece5-11ea-93fc-3b9f593226d1.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6161)

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1681814

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
This is unlikely to be a GV issue. Error pages lives in A-C

**Comment by madig** [comment]
On Firefox 84.1.1, I get a "cannot securely connect" screen (also, add-on installation and Sync activation fails). Trying to continue regardless does nothing. Would be nice to get a "check your time" message.

**Comment by lobontiumira** [comment]
I was able to reproduce this issue.
I got the "Secure Connection Failed" screen, on the 6/24 Nightly build with Google Pixel (Android 10).

**Comment by mcarare** [comment]
This will need UX for the string and options available for the buttons ( just show an error message or add an option for button click to take you to date/time settings).
Also, maybe GV will be needed because I do not know if `WebRequestError` has a special type for `ERR_CERT_DATE_INVALID` ?

**Comment by amedyne** [comment]
@agi Any thoughts on this?

**Comment by agi** [comment]
@amedyne on GeckoView example I see `ERROR_SECURITY_BAD_CERT` which seems a little bit better than `Address not Found` but still not great, I think you are right, we should expose a more fine grained error like "CERT_DATE_INVALID", I'll reopen the GV bug.

**Comment by agi** [comment]
We can use this bug to support the new error type once it lands in GV.

**Comment by amedyne** [comment]
Thank you @agi will be waiting for your go signal once the GV change is ready.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1806512

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
