### ISSUE TITLE
[Bug] Not enough padding around favicon in back stack

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14600]
Steps to reproduce:

1. Go to a few pages in a single tab
2. Press and hold back on browser

What happens:

The favicon is nearly touching the active tab highlight edge.

![Screenshot_20200829_221014_org mozilla fenix debug](https://user-images.githubusercontent.com/39402893/91645421-34574900-ea45-11ea-999f-b6fc22ba3974.jpg)

Expected result:

Better visual styling/spacing.

_Originally posted by @pweiden in https://github.com/mozilla-mobile/fenix/issues/13498#issuecomment-683337406_

**Comment by yoasif** [comment]
Can't reproduce this on my device.

**Comment by cadeyrn** [comment]
It was an issue and recently fixed.
