### ISSUE TITLE
improvements to the bug template

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#14607]
To improve the quality of the bug reports I suggest a few changes to the issue template for bugs:

- [ ] remove the "[Bug]" from the title so that people are forced to enter something. It's annoying when you're going through the issues list and you have to open issues to know what these issue are about because some people don't add anything to the title. And it is already clear from the label that an error is reported so it doesn't add any value.
- [ ] replace "Fenix version" with "Firefox version" to avoid questions like "What is Fenix?" - already happened.
- [ ] replace "Android device" with something more clear because this field is often poorly filled in. Something like "Device vendor / model and Android version".
- [ ] style nit while you're at it (doesn't improve the report quality): "Steps to reproduce" does not have the same level as the other headings.

**Comment by hwinnemoe** [comment]
Maybe we should also add a question that asks for crash report links / logcat if the report is about a crash, or create a separate template for this
