### ISSUE TITLE
[Bug] Width of main menu gets reduced when visiting a site that supports PWAs

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#14605]
## Steps to reproduce

1. Visit a site that doesn't support PWAs (e.g. https://www.example.com).
2. Open the main menu, and observe its width.
3. Visit a site that supports PWAs (e.g. https://twitter.com).
4. Open the main menu, and observe its width.

### Expected behavior

The width of the main menu remains the same.

### Actual behavior

The width of the main menu when visiting a site that supports PWAs is smaller than when visiting a site that doesn't support PWAs. Presumably, this is due to the absence of the "Add to Home Screen" entry in the main menu (which is replaced with the "Install" entry for PWAs), as it seems to have the longest string.

Main menu on a site that doesn't support PWAs:
![](https://user-images.githubusercontent.com/45960387/91939733-e8e4b980-ed28-11ea-9f2d-f8860d55633b.jpg)

Main menu on a site that supports PWAs:
![](https://user-images.githubusercontent.com/45960387/91939756-f306b800-ed28-11ea-9171-c81a93e53e96.jpg)

### Device information

* Android device: Oppo Reno 2
* Fenix version: Nightly 200901 06:03 (Build #2015761331)

**Comment by mcarare** [comment]
This is the expected behavior, as the menu width is dynamic, as requested in https://github.com/mozilla-mobile/fenix/issues/10541. When the site supports PWA, the longest menu option "Add to home screen" is replaced by a shorter one "Install".
