### ISSUE TITLE
FNX-5047 ⁃ [Bug] Confirm issue when Lockbox app crashes when using it with Fenix

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1460]
I want to make sure we figure out if this is a Fenix issue or Lockbox issue, Lockbox did not crash for Focus.

* STR: see Cross-filed, for reference https://github.com/mozilla-lockbox/lockbox-android/issues/583
* Android device: Pixel 2, version 9
* Fenix version: 
![Screenshot](https://user-images.githubusercontent.com/122897/55720749-91c1a480-59cf-11e9-9d64-1353007b277d.png)UNITO-UNDERSCORE!20190408-072110!

/cc @kbrosnan

**Comment by kbrosnan** [comment]
according to Lockbox this was https://github.com/mozilla-lockbox/lockbox-android/issues/548
