### ISSUE TITLE
[Bug][regression] Scanning a QR code doesn't open the page automatically

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#14609]
## Steps to reproduce
1. Open Fenix and tap on Scan.
2. Scan a QR code from desktop, for example.

### Expected behavior
 The scanned code opens in a new tab - the user is redirected to it instantly.

### Actual behavior
The page opens in the background, the user doesn't know that until tab counter is tapped.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 9)
* Fenix version: 9/2 Nightly, beta 81.1.0-beta.1
* **Not reproducible on RC 80.1.2**

<img src="https://user-images.githubusercontent.com/40694158/91963856-1d4f7a00-ed17-11ea-979f-4921cce73bd8.gif" width="300" height="550" />

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/10 with the following devices:
- Samsung Galaxy Note 10 (Android 10)
- Google Pixel 3 (Android 11)
- Nokia 6 (Android 7.1.1)
