### ISSUE TITLE
[webcontent] intermittent failure opening popup windows

### ISSUE THREAD

**Issue by classilla** [mozilla-mobile/fenix#14601]
## Site with issue and any steps to reproduce

https://www.floodgap.com/roadgap/6/u4/

This page (mine) has thumbnail images.

### Expected behavior

When tapped, the thumbnail should pop open a new tab/window with a full size version. If this tab is left open, additional tabs will reuse it.

### Actual behavior

It works about every other time. The initial tap leaves a blank `about:blank` window. When closed and tapped again, it appears. When closed and tapped a third time, it doesn't, etc.

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)

No (doesn't change behaviour).

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?

No (works as expected in the previous Firefox for Android).

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No (works as expected). Ditto for desktop Firefox.

Also filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1661738

### Device information

* Android device: Pixel 3, Android 10 (QQ3A.200805.001)
* Fenix version: 79

**Comment by vblanton** [comment]
+1
Facebook marketplace also has this issue. If I click on any item for sale, a blank popup is created. 
www.facebook.com/marketplace

**Comment by vblanton** [comment]
![Screenshot_20200902-101949](https://user-images.githubusercontent.com/37779807/92009601-fdfc2100-ed05-11ea-80a2-c9670837c645.png)

**Comment by classilla** [comment]
:karlcow on the Bugzilla issue says it's fixed in Nightly, and it seems to be. @vblanton does Firefox Nightly fix your issue as well?

https://bugzilla.mozilla.org/show_bug.cgi?id=1661738
