### ISSUE TITLE
Passwords not populating[Bug]

### ISSUE THREAD

**Issue by thesheepshearer** [mozilla-mobile/fenix#14611]
### Device information Amazon Fir 8 HD tablet with Google APIs for playstore use.

* Android device: ?
* Fenix version: ? 79.0.5 Build #2015758617

**Comment by liuche** [comment]
You'll be able to enter the master password on #13926

**Comment by thesheepshearer** [comment]
Thank you for your response.
Obviously I have not explained myself well, you have misunderstood what I wrote or simply regurgitated a response to another bug.
However I do not understand what you have written.

Nevertheless that does not respond to my specific problem.

My passwords are still stored and can be accessed via settings. No master password is involved.

Firefox has always (and still does on the synced PC version) auto populate saved password from a single website login or after selecting (for multiple logins) or entering the username (if not already populated) when a single username is in use for a website. This worked on all synced browsers I used.
Now (rarely) some websites do autopopulate such as Interactive Investor research login or my bank's website.
My email provider does not populate username so need to manually enter it now on mobile version (fine on PC!) but even then the password is absent. Oddly if I select the websites forgotten password link and then go back to login page the password is then auto populated!
Most other websites autopopulate neither and I have to resort to settings and the password manager and than copy back into the login page.

So does not work for majority of time and is also inconsistent!

Please address the specific issues.

Alex

September 10, 2020 2:04:35 AM CEST liuche <notifications@github.com> wrote:

You'll be able to enter the master password on #13926
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.[{"@context": "http://schema.org","@type": "EmailMessage","potentialAction": {"@type": "ViewAction","target": "https://github.com/mozilla-mobile/fenix/issues/14611#issuecomment-689888113","url": "https://github.com/mozilla-mobile/fenix/issues/14611#issuecomment-689888113","name": "View Issue"},"description": "View this Issue on GitHub","publisher": {"@type": "Organization","name": "GitHub","url": "https://github.com"}}]

-- 
Sent with https://mailfence.com
Secure and private email
