### ISSUE TITLE
Only show a tiny offset to indicate that the selected tab is not at the top of list in the tabs tray

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#14619]
In #13264, we took a shortcut to show that we are not at the top of the list in the tabs tray by scroll to the tab before the selected tab which is more than a little offset as desired by UX.

This issue is to implement the proper solution of only scrolling a small offset above the selected tab if it is not at the top of the list.

**Comment by Mugurell** [comment]
@UX what should that offset be?
Maybe 1/3 or 1/4 of the size of a tab tray item? ([item which has 88dp in height](https://github.com/mozilla-mobile/fenix/blob/5153a3f2c5011a1f77c303832f3cd22692a68207/app/src/main/res/layout/tab_tray_item.xml#L10))

Maybe we should think about doing similar to show that that there are tabs at the bottom?
I think this needs a deeper investigation.

**Comment by liuche** [comment]
I think 1/2 the size of the previous tab item would be fine, which would be better than what we have now. I don't think we necessarily need to do this for tabs on the bottom (if the user is on one of the last couple of tabs, they can see that there are a stack of tabs above, and therefore they can scrool).

cc @topotropic, if you have any additional thoughts (maybe due to the newest/oldest top ordering that you've been thinking baout).

**Comment by topotropic** [comment]
Yes, 1/2 sounds good.

**Comment by mcarare** [comment]
@gabrielluong I do not think it's in the scope of this issue, but AFAIU a different scroll should be set for grid view.

**Comment by amkcpu** [comment]
The problem with using 1/2 of the tab is visible in the PR (#15955): Hiding half of the close button `x` makes it look like there is an arrow pointing up in the upper right corner.
For this reason and to save space, I would prefer showing only 1/3 or 1/4 of the tab.
What do you think?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both latest **`Nightly Build 201022`** and **`Firefox RC 83.0.0-beta.1`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201022-121955](https://user-images.githubusercontent.com/51314259/96851974-4790fe80-1461-11eb-8104-dfcb6b0d1abf.gif)
