### ISSUE TITLE
Where to find reliable and old apk and ios with about:config

### ISSUE THREAD

**Issue by bksubhuti** [mozilla-mobile/fenix#14616]
### What is the user problem or growth opportunity you want to see solved?
About:config has been disabled and I guess it is a big issue that has been clearly already expressed.
I am a monk and developer of a firefox html app that requires security.fileuri... to be false in order to read internal Buddhist Text files.

Project is https://americanmonk.org/tipitaka-pali-projector/

### How do you know that this problem exists today? Why is this important?
It is clear the problem exists.
The users cannot use the html app with out this feature

### Who will benefit from it?

I don't want to refer the users to a third party website that serves older apk because I don' t know them and if they are trustworthy.  The mozilla website has only desktop older versions listed.

Where to find the older apk and older ios apps until this issue is resolved?

**Comment by bksubhuti** [comment]
My instructions from the website  (bottom of page) https://americanmonk.org/tipitaka-pali-projector/

To make Firefox work you need to type about:config in the address bar to get the advanced preferences. The search for security.fileuri.strict.origin.policy and set it to false. Tablets and phones might want to set the layout.css.devPixelsPerPx to 1.5 to fit better in a smaller screen area.


![image](https://user-images.githubusercontent.com/18184280/91996782-63c8c700-ed5f-11ea-9b26-071beecfe1d7.png)

**Comment by kbrosnan** [comment]
http://archive.mozilla.org/pub/mobile/releases/

Duplicate of #7865

**Comment by bksubhuti** [comment]
Thank you

**Comment by bksubhuti** [comment]
May I suggest you add this to the main website?

**Comment by cadeyrn** [comment]
> May I suggest you add this to the main website?

Using old browsers is really bad for security and for other reasons like web compatibility. They should definitively not do this…

**Comment by bksubhuti** [comment]
I believe the older versions link is listed on the moz website for desktop, but there is no listing for mobile.  I did not know it existed until now.  This is the same "security issue" as desktop.

**Comment by cadeyrn** [comment]
> I believe the older versions link is listed on the moz website for desktop

Nope.
