### ISSUE TITLE
[Bug] Unable to select/tap some items, including on addons.mozilla.org

### ISSUE THREAD

**Issue by rfugger** [mozilla-mobile/fenix#14628]
## Steps to reproduce

Navigate to search results page on addons.mozilla.org (eg, https://addons.mozilla.org/en-CA/android/search/?q=new%20tab).  Expand "Filter results" form.  Try to interact with any of the three drop-down select elements ("Sort by", "Add-on Type", "Operating System").

### Expected behavior

Selectors open and behave nicely.

### Actual behavior

Select elements do not react to taps.  If I tap madly all around them, I can sometimes get them to pop open, but this is excruciatingly difficult, and I end up tapping so fast to make it happen that it immediately selects a random item in the list, so is completely unusable.

This has happened sporadically on at least one other site, but seems to happen consistently at addons.mozilla.org.

Chrome functions fine on this page, ironically.

### Device information

* Android device: Google Pixel fully updated
* Fenix version: 79.0.5

**Comment by davidrpk** [comment]
I have this issue as well on
* Android device: Samsung A70, Android 10
* Fenix version: 80.1.2

It renders many websites unusable.

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1664074
