### ISSUE TITLE
html5 message not displayed on empty entry

### ISSUE THREAD

**Issue by daviddddddddf** [mozilla-mobile/fenix#14621]
the html5 messages are not displayed on empty entry (with required attribute). (firefox on android only)

simple example with an input required and a submit button
 
https://www.eway.fr/z.php

Do you have a solution ??

My Firefox version is 79.0.5

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1664073
