### ISSUE TITLE
[Bug] Nit: Top Sites favicon border no longer matches long-press Back button favicon border width

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#14627]
Top Sites now has bigger favicons & smaller borders
But if I long-press Back to see the history list it still has the smaller favicons with bigger borders

I think the border widths should be consistent throughout  [ideally, zero pixels???  😀😉]
### Device information

* Android device: Galaxy A40
* Fenix version: Today's

**Comment by s-ankur** [comment]
> ideally, zero pixels

This is a must from an accessibility perspective

**Comment by topotropic** [comment]
@s-ankur can you clarify what you mean with "This is a must from accessibility perspective" – do you mean having the borders? Thanks!
