### ISSUE TITLE
Crash in [@ mozilla::PresShell::EventHandler::HandleEventUsingCoordinates] when focusing text input on Nightly

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14624]
Native crash when focusing text input on today's Nightly

today nighlty on my phone lineage OS 14.1 is totally unusable it crashes. here s the soccorro
https://crash-stats.mozilla.org/report/index/bp-b596f1ce-c8a9-4dfb-9a6e-dceb20200902
can please someone explain what's Goin on  ?

**Comment by kbrosnan** [comment]
Opened bz-1662830 to track the Gecko fix for this crash

**Comment by pocmo** [comment]
Fixed in mozilla-central. Will take ~1-2 days until the fix shows up in Nightly.

**Comment by liuche** [comment]
Should be in Nightly now, will close this.

**Comment by amkcpu** [comment]
Verified as fixed in Nightly 200911 14:03 (Build #2015763315).
