### ISSUE TITLE
[Bug] Top Sites favicons slow to appear when I open a new tab

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#14622]
## Steps to reproduce
open a new tab
watch the 8 Top Sites slots

### Expected behavior
Top Sites favicons are instantly present

### Actual behavior
Top Sites favicons appear from top left to bottom right over perhaps 0.5 seconds. It looks unpolished.

### Device information
* Android device: Galaxy A40
* Fenix version: Today's

**Comment by mcomella** [comment]
Triage: we think we might be able to do this with better caching (we shouldn't block to make this happen). Moving to inter team list to investigate the possibility.

**Comment by liuche** [comment]
I'll dupe this to #14443 and copy over some of the comments
