### ISSUE TITLE
[Bug] KeePassDX password auto fill not popping up

### ISSUE THREAD

**Issue by sophiekuehn** [mozilla-mobile/fenix#14634]
## Steps to reproduce
Set up KeePassDX as the default auto fill service in android settings. Open a database and access a login form in Firefox to be filled out automatically. 

### Expected behavior
KeePass auto fill popup pops up 

### Actual behavior
Nothing happens. 

### Device information

* Android device: Samsung Galaxy S7
* Fenix version: 79.0.5

**Comment by Dunexus** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14633

**Comment by liuche** [comment]
Dupe of #14633

**Comment by sophiekuehn** [comment]
@liuche is not a duplicate, since KeePassDX is a completely other app with another code base than Keepass2Android. KeePass is a offline password storage solution. So more a format then a service.
