### ISSUE TITLE
[Bug] Keepass2android password auto fill not popping up

### ISSUE THREAD

**Issue by sophiekuehn** [mozilla-mobile/fenix#14635]
## Steps to reproduce
Set up Keepass2android as the default auto fill service in android settings. Open a database and access access a login form in Firefox to be filled out automatically. 

### Expected behavior
KeePass auto fill popup pops up 

### Actual behavior
Nothing happens. 

### Device information

* Android device: Samsung Galaxy S7
* Fenix version: 79.0.5

**Comment by Dunexus** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14633
