### ISSUE TITLE
[Bug] Toolbar is hidden behind the Gboard keyboard if it's already open

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#14638]
## Steps to reproduce
- Tap in an input field on a webpage so the keyboard opens
- Tap on the toolbar

### Expected behavior
- The toolbar is rendered above the keyboard

### Actual behavior
- The toolbar is rendered behind the keyboard

### Device information

* Android device: Samsung Galaxy A50
* Fenix version: Nightly 200902 06:01 (Build #2015761523)
AC: 57.0.0, c84cf8e77
GV: 82.0a1-20200831091558
AS: 61.0.13

**Comment by mcarare** [comment]
This is not reproducible for me, using a Huawei P10 and several emulator devices. The keyboard closes automatically when the menu shows up, for google and wikipedia websites.
@miDeb for you is this reproducible on a certain website, or on all? Thank you!

**Comment by miDeb** [comment]
I can reproduce this on all websites, here's a recording: https://streamable.com/rqznhx

**Comment by mcarare** [comment]
Oh, do you mean, the search toolbar, not the 3 dot menu. Still, the toolbar shows up above the keyboard for me. We will investigate this. Are you using OS keyboard or a custom one?

**Comment by miDeb** [comment]
Indeed, I am using gboard. With Samsung Keyboard I can't reproduce.

**Comment by amedyne** [comment]
@miDeb Can you still reproduce this issue?

**Comment by miDeb** [comment]
Yes, still able to reproduce on the latest nightly.

**Comment by Mugurell** [comment]
Hello @miDeb 
Can you please post a video recording of the issue if this is still reproducing for you?
The one from https://github.com/mozilla-mobile/fenix/issues/14638#issuecomment-686520168 is not available anymore.

**Comment by miDeb** [comment]
I just tried, and it seems like I can't reproduce this anymore, so I am going to close this.
