### ISSUE TITLE
New search experience too complicated when switching between search engines

### ISSUE THREAD

**Issue by lordgurke** [mozilla-mobile/fenix#14641]
## User Story
- The new search experience is not very intuitive to me. Maybe I'm just an idiot who does not understand the system on how to use it properly.

With the previous mobile Firefox version I used to have several search engines - like for example DuckDuckGo, dict.leo.org, a WHOIS service... You get the idea.
I typed something I wanted to search for into the URL bar, pressed enter, and the default search engine (DuckDuckGo) came up with the search results.

But sometimes, I wanted a word translated with dict.leo.org.
So I typed the word and tapped the "LEO" icon on the bottom of the screen.
The same concept worked for all other configured search engines.

With the new "search experience" (this seems to be, what it is called here) It is more complicated as it should.
Today, I type the word I want to have translated with the configured dict.leo.org search engine.
So, when the word is typed, I need to tap "search engines" on the bottom.
Then, I need to select the search engine.
Then, I need to press enter.

Why not having these icons again? Type a word, tap the search engine icon, done.
Or, to stay in the new concept: Type a word, tap "search engines", tap the icon. Just eliminate the need to press enter.
I could happily live without that QR code feature (I never use), if then my 5-6 search engine icons could fit there ;-)

Vaguely related: In my opinion it's a massive setback, I can't configure search engines automatically.
I can't even remember how many years ago autoconfiguration of search engines by website operators became a standard.
While browsing the site, I just could add this website as a search engine, as long as it provided an XML description for it. 
Is there a reason, this feature has been removed?

**Comment by kbrosnan** [comment]
Duplicate issue of #4333 / #8889
