### ISSUE TITLE
Fenix takes 2 GB on disk (via user report) - analyze app/cache size telemetry

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#14646]
via child comment (direct link is broken) of https://www.reddit.com/r/firefox/comments/iit3nb/firefox_on_android_takes_around_2_minutes_to_give/g39yct9/

### Expected behavior
Fenix should probably not grow beyond 1 GB on the largest devices; the Fenix disk storage size should be proportionate to the amount of total space available on the drive and perhaps even how filled the device is (though maybe the system addresses the latter for us?).

### Actual behavior
> Sounds like cache problem to me (my FF got to about 2GB size after a while). Can you check that?

Note: we can see how common this is: we implemented telemetry for app and cache size https://github.com/mozilla-mobile/fenix/issues/12834 but have not analyzed it yet.

### Device information

* Android device: ?
* Fenix version: ?

---

I've only seen us hovering around 800 MB locally – I wonder if extra data was lying around after the migration.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6224)

**Comment by kbrosnan** [comment]
We have a known issue with gecko with sites that generate files in the `app_tmpdir` folder. bz-1555115 / bz-1532446

**Comment by cousteaulecommandant** [comment]
> We have a known issue with gecko with sites that generate files in the `app_tmpdir` folder. [bz-1555115](https://bugzilla.mozilla.org/show_bug.cgi?id=1555115) / **[bz-1532446](https://bugzilla.mozilla.org/show_bug.cgi?id=1532446)**

Bug [bz-1532446](https://bugzilla.mozilla.org/show_bug.cgi?id=1532446) was closed stating that all Fenix bugs should be reported here from now on, so I suggest we move the conversation here, or better yet, re-open that bug as a new issue here.

**Comment by cousteaulecommandant** [comment]
I just submitted #17262 as a continuation of [bz-1532446](https://bugzilla.mozilla.org/show_bug.cgi?id=1532446).
I preferred to make it a separate issue since that one discusses the specific problem and this one suggests using telemetry to diagnose that kind of problem in the future.

**Comment by cousteaulecommandant** [comment]
PS: are we sure this is a **cache** problem?  The bug @kbrosnan mentioned isn't exactly the cache; it's a temporary directory that (unfortunately) doesn't get deleted when you select "clear cache" in Firefox or Applications.

**Comment by mcomella** [comment]
These probes are now available in GLAM, e.g.: https://glam.telemetry.mozilla.org/fenix/probe/storage_stats_cache_bytes/explore?app_id=release&ref=2021010809

That should make it considerably easier to investigate. A brief analysis shows for the 95% percentile on release for the data on 01-07 (if I'm interpreting correctly):
- 696 MB cache
- 333 MB data directory
- 226 MB app install size
- Total: 1255 MB (this is just a worst case because it's not entirely correct to add these values because a user with 696 cache may not have a 333 MB data directory. In retrospect, we should have a "total amount" probe for users in addition to the separate probes)

For the 75th percentile on release for the data on 01-07:
- 585 MB cache
- 129 MB data dir
- 216 MB app install size
- Total: 930 MB (see caveats about averages above)

Note there may be extreme cases: on beta, we see the 95% percentile for an incomplete data set of 19 clients on 17th have a data dir of 3.77 GB. These may be users affected by the issues mentioned above. I wonder what the retention of these users are in extreme circumstances

**Comment by mcomella** [comment]
Note: query length in 95% was at worse 1s, which is pretty bad, but 75% percentile was 10s of ms so maybe it's okay.

**Comment by mcomella** [comment]
Triage: the perf time is not actively looking at application size but this is moderately concerning so let's add this to fenix triage.

**Comment by janschejbal** [comment]
Regular web site storage could also be a problem. I've seen web sites store 30+ MB of site data in their directory in `/data/user/0/org.mozilla.firefox/files/mozilla/xxxxxxxx.default/storage/default` (and deleting it doesn't work reliably, see #19859).

**Comment by mcomella** [comment]
Triage: we're generally not focused on APK size right now but a report of 2 GB is pretty bad: setting as P1.

**Comment by janschejbal** [comment]
Would you mind re-checking the telemetry, especially if possible on devices that had the same profile for a longer period of time? (This isn't an issue expected on fresh installs.)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807368

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
