### ISSUE TITLE
[Bug] "Scan" in new search experience remains highlighted even if permissions are denied

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#14647]
## Steps to reproduce
- Click URL bar
- Press "Scan"
- Deny permission

### Expected behavior
Scan is not marked as selected

### Actual behavior
Scan is marked as selected. [Video of the behavior](https://drive.google.com/file/d/1KtrzxNXxULR3kZGfz4-hLF2tcKt9QbJi/view?usp=sharing)

Screenshot after permission is denied:
![image](https://user-images.githubusercontent.com/759372/92048033-8943d980-ed3b-11ea-9f46-0036e957032c.png)

### Device information

* Android device: P2
* Fenix version: Nightly 200902

**Comment by liuche** [comment]
This should be handled in #14553
