### ISSUE TITLE
[Bug]Tab History UI fixed only to go with toolbar bottom, must change with toolbar top

### ISSUE THREAD

**Issue by DavidBE-UK** [mozilla-mobile/fenix#14640]
## Steps to reproduce

Have setting Toolbar top

Long press on back button when there are just 1 or 2  items in the tab history for that tab

### Expected behavior

The tabs in the tab history should be displayed just BELOW the toolbar at the top of the screen. If you have to use the bottom sheet method, then when toolbar is set to top, the bottom sheet should open ALL THE WAY UP to keep the contents near the toolbar controls at the top.

### Actual behavior

The bottom sheet only comes up the minimum amount to show the one or two tab, meaning they are right at the bottom of the screen, as far away as they can be from the toolbar at the top. This is the same problem as with the tab tray - it is only designed for people using toolbar bottom, keeping the tabs and new tab button right down the bottom, not changing to bring them up to go with toolbar top.

I HATE bottom controls, and do not use apps that have them. I was very pleased last December when the option was introduced to set the toolbar at the top, but that has now been RUINED by the tab tray and now the tab history being designed solely for toolbar bottom users, keeping the listed tabs and actions down by a bottom toolbar, and not changing behaviour when the toolbar is set to TOP. When toolbar is set to TOP the bottom sheet displaying the tab sheet and tab history should always open FULLY to move the listed tabs and action buttons up to right below the toolbar controls at the top.

This lack of integrated proper support for people who like the controls at the TOP has driven me from using the Firefox App to using Google Chrome - which in turn, due to the need for browser syncing, is dictating I should leave desktop Firefox for Chrome too. These design choices appear to indicate that everyone in the UI design team loves bottom controls, and after the initial adding of the toolbar top or bottom setting have then forgotten about toolbar top users when adding more features. SOMEONE in the design team needs to take on the job of always looking at each new UI aspect to see if it also needs a variation added for when toolbar position is set to TOP.

### Device information

* Android device: TCL 5099Y

* Fenix version: Nightly 200902 06.01 Build #2015761521

**Comment by mcarare** [comment]
IMO it does not make sense to show the history list at the top, regardless where the toolbar is. The feature is designed to help you easily navigate through history. So, when pressing the back button, a history list is more easily accessible with the list showing near the back button,  without having to move the finger way up on the screen.

**Comment by liuche** [comment]
Thanks for filing - we can't support every configuration, and this is working as expected for handling one-handed use.
