### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14655]
## Steps to reproduce
- Play a video on the ted.com
- Background the video or turn your screen off 

### Expected behavior
- Video continues to play and you can listen while doing other things

### Actual behavior
- Video continues to play at first, but stops somewhere between 3-5 minutes (timed it 3 times: once it stopped after 4:25, then 3:20, then 3:35)

### Device information

* Android device: Pixel 4
* Fenix version: Nightly 200902 06:01 (Build #2015761523)

**Comment by hwinnemoe** [comment]
Related to/Duplicate of https://github.com/mozilla-mobile/fenix/issues/9691

**Comment by boek** [comment]
Going to track this with #9691 which is now in the a-c top 10.
