### ISSUE TITLE
[Bug] Open app instead of website

### ISSUE THREAD

**Issue by R2R29** [mozilla-mobile/fenix#14657]
## Steps to reproduce
If i search for: pré época porto 2020/21 TV and choose the first result (www.zerozero.pt > edicao
 _Pré-Época 2020/2021 :: zerozero.pt_)

### Expected behavior
Should open the website [Zerozero.pt](https://www.zerozero.pt/edicao.php?id_edicao=146060) 

### Actual behavior
Opens an app of TV channels that i have installed (not pre-defined to open any links!) 

### Device information

* Android device: OnePlus 7 Pro, Android 10, stock
* Fenix version: 80.1.2

**Comment by liuche** [comment]
Do you have Settings > Open links in App set?

**Comment by R2R29** [comment]
> Do you have Settings > Open links in App set?

Hi, 
First off all, thanks for the attention. 

No i don't; it was the first thing I've checked. 

Thanks

**Comment by sflorean** [comment]
@R2R29 this is still reproducible for you? Thank you!

**Comment by R2R29** [comment]
Hi,
Sorry for the (extremely) late reply.
No it doesn't happen anymore but since i opened the case, my phone was upgraded to Android 11, i'm using the browser with DuckDuckGo (at the time i think i was using Google), and i removed the app that used to open instead of the website since it stop working.

Thanks

Best regards
