### ISSUE TITLE
[Bug] Incorrect redirect included in Top Sites frecency, Google redirect link instead of search result

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#14654]
## Steps to reproduce
Search "cats" on Google
Click on a search result, e.g. wikipedia link for "Cats" the movie

### Expected behavior
Top sites includes Wikipedia item for Cats The Movie

### Actual behavior
Top sites includes Google search redirect link instead of Wikipedia link
Clicking on the top site will redirect you to Wikipedia, but still shows the Google icon (for the search result)

### Device information

* Android device: Pixel 3
* Fenix version: Nightly 9/2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6237)

**Comment by s-ankur** [comment]
Related, https://github.com/mozilla-mobile/fenix/issues/7544 this is exactly what shows in in history as well

**Comment by Mugurell** [comment]
@ekager #7544 will now also show `REDIRECT_PERMANENT` target urls in history.
But in this example (based on STRs) I saw the url being saved with `REDIRECT_TEMPORARY`. Should we also show these links?
Not really sure about the original reasoning for which urls to show.

**Comment by Mugurell** [comment]
This will probably be resolved by the same https://bugzilla.mozilla.org/show_bug.cgi?id=1670279.
See https://github.com/mozilla-mobile/fenix/issues/7544#issuecomment-706291787 for background.

**Comment by liuche** [comment]
I bumped the GV ticket to a fenix:p1 label because this affects some top sites.

**Comment by gabrielluong** [comment]
Closing this since it's a GV issue.
