### ISSUE TITLE
[Bug] PRISM Cloudflare

### ISSUE THREAD

**Issue by BullShark** [mozilla-mobile/fenix#14653]
## Steps to reproduce
Firefox on every platform
Ignores system dns and sends everything to Cloudflare.

### Expected behavior
Respect Users' Privacy

### Actual behavior
Spyware

### Device information
Android, Windows, Linux, Every platform

* Android device: ? All versions
* Fenix version: ? All versions

**Comment by jawz101** [comment]
Is there a way to test this?

**Comment by BullShark** [comment]
tcpdump

**Comment by BullShark** [comment]
about:networking

Type google

Fuck Firefox

**Comment by BullShark** [comment]
about:networking

Type google

**Comment by BullShark** [comment]
Firefox contantly talks to google, mozilla, cloudflare and others.

**Comment by BullShark** [comment]
![signal-2020-09-03-121228_004](https://user-images.githubusercontent.com/1526595/92146324-299f0a00-eddf-11ea-9cd2-43c6b76a6e20.png)
![signal-2020-09-03-121228_006](https://user-images.githubusercontent.com/1526595/92146330-2a37a080-eddf-11ea-8301-f46092a18ed1.png)
![signal-2020-09-03-121228_007](https://user-images.githubusercontent.com/1526595/92146331-2a37a080-eddf-11ea-805c-c9807329db05.png)
![signal-2020-09-03-121228_008](https://user-images.githubusercontent.com/1526595/92146333-2ad03700-eddf-11ea-9958-5d2f6ffc9863.png)

**Comment by BullShark** [comment]
![image](https://user-images.githubusercontent.com/1526595/92146609-961a0900-eddf-11ea-82f4-d1dfb4d72dd5.png)

**Comment by BullShark** [comment]
**### https://mozilla.cloudflare-dns.com/dns-query**

incoming.telemetry.mozilla.org
safebrowsing.googleapis.com
tracking-protection.cdn.mozilla.net
img-getpocket.cdn.mozilla.net 
firefox-settings-attachments.cdn.mozilla.net
getpocket.cdn.mozilla.net
safebrowsing.googleapis.com
shavar.services.mozilla.com

These are just a few Firefox talks to these before you even opened a webpage or told it to do anything.

**Comment by BullShark** [comment]
![image](https://user-images.githubusercontent.com/1526595/92147691-1725d000-ede1-11ea-9bbd-9742c8900533.png)

**Comment by BullShark** [comment]
How to enable about:config in Firefox for Mobile.

Use javascript in users.js to enable about:config for Mobile.

https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android

var user_pref = function(pref, val){
  try{
    if(typeof val == "string"){
         Services.prefs.setStringPref(pref, val);      
    }
    else if(typeof val == "number"){
         Services.prefs.setIntPref(pref, val);      
    }
    else if(typeof val == "boolean"){
         Services.prefs.setBoolPref(pref, val);      
    }
  } catch(e){
    console.log("pref:" + pref + " val:" + val + " e:" + e);
  }
}

user_pref("general.aboutConfig.enable", true); // unblock about:config in newer versions (FF71+?)

//paste your user.js file content on the next line

**Comment by BullShark** [comment]
Check Firefox here.

https://exodus-privacy.eu.org

Or use this:

https://f-droid.org/en/packages/org.eu.exodus_privacy.exodusprivacy

To check Firefox installed from this:

https://f-droid.org/en/packages/de.marmaro.krt.ffupdater

**Comment by BullShark** [comment]
![image](https://user-images.githubusercontent.com/1526595/92149328-7c7ac080-ede3-11ea-938d-5dce066da8cc.png)

**Comment by cadeyrn** [comment]
Please make use of the edit feature instead of posting 10 comments in a row. It causes a lot of notification spam.

**Comment by kbrosnan** [comment]
DNS over HTTPS (DOH) is not enabled by default on Firefox for Android. DNS queries are not sent to Cloudflare unless you have configured your device's DNS settings to 1.1.1.1. 

Closing this issue as invalid.
