### ISSUE TITLE
[Bug] web content stops working after visiting certain pages

### ISSUE THREAD

**Issue by lal12** [mozilla-mobile/fenix#14652]
## Steps to reproduce
Visit [https://steamcommunity.com/app/250820/discussions/5/1657817111856971474/](https://steamcommunity.com/app/250820/discussions/5/1657817111856971474/)

### Expected behavior
Page should load, everything should keep working.

### Actual behavior
Page stops loading (loading bar stops in the middle). Opening another tab it won't load either anymore and shows just a white page.

EDIT: By opening another tab I mean any page not specifically the above URL. 

UI keeps working without any issue.

### Device information

* Android device: Xiaomi Mi Mix 2S, Lineage OS 17.1
* Fenix version: 79.0.5

**Comment by lostwizard** [comment]
I have experienced the same thing with 80.1.2, exactly as described here. It seems to stay broken, too. Clearing cache, restarting Firefox, nothing fixes it.

**Comment by lal12** [comment]
I just tried again, the issue does not occur anymore. But since the FF version is the same I guess the webpage was changed.

**Comment by clientenq** [comment]
Same issue here with latest daily version. Does not seem to be www resource specific. Any tab can suddenly keep blank. Does also not respond to user relais reuests or requesting other urls via address bar.

**Comment by liuche** [comment]
We put in some fixes for this in Nightly! #5478 or #14459. If you are seeing this still after using the newest Nightly, please comment in that bug.
