### ISSUE TITLE
[Bug] [Translation] "Downloads" entries not translated into French on Beta and Nightly

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#14665]
## Steps to reproduce
Set language to "French"
Open 3 dots menu from a web page or from the home page

### Expected behavior
"Downloads" is translated by "Téléchargements"

### Actual behavior
It is not translated

### Device information

* Android device: ?
* Fenix version: 81 beta + nighlty

**Comment by cadeyrn** [comment]
Translations happen via https://pontoon.mozilla.org. If it's still in English then it's probably not yet translated by the translators. You can also suggest translations on Pontoon.

**Comment by klint** [comment]
Thanks for the hint. Will check there! 😊

**Comment by klint** [comment]
There are entries for "Downloads" in Pontoon and they are translated properly in French: https://pontoon.mozilla.org/fr/android-l10n/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=downloads&string=197484
By the way, I have checked with Italian, and it is not translated either.

**Comment by mcarare** [comment]
@klint Thank you fo the report, it turns out the menu name was hardcoded.

**Comment by klint** [comment]
I can confirm this has been corrected on my Redmi Note 7 with today's nightly. Thanks

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200907 06:01 (Build #2015762483) GV 82.0a1 from 9/7 with Pixel 2 (Android 9),  Nexus 5 (Android 6.0.1).
