### ISSUE TITLE
Multiple Reddit Tabs Tittle End Up to "chat - reddit"

### ISSUE THREAD

**Issue by MicroBeast** [mozilla-mobile/fenix#14661]
Name: Firefox Beta
Version: 81.0b5
Build ID: 20200901203141
From: Google Play Store

Effected: Reddit

How to reproduce:

Open multiple tabs of Reddit, anything, any post. At 1st, their tab title will show it subject title (as suppose to be). After a while all of them will change to "chat - reddit".

Thank you.

Edit: Also same behaviour up to;

Name: Firefox Nightly 06:04
Build ID: 2015761713
From: Google Play Store

**Comment by hwinnemoe** [comment]
Possibly related to https://github.com/mozilla-mobile/android-components/issues/8315

**Comment by MicroBeast** [comment]
I see. I'll watch both.

**Comment by jonalmeida** [comment]
I'm going to close this since there are other Fenix bugs filled against this and the AC one is where we will probably be landing a fix in.
