### ISSUE TITLE
[Bug] Background color not rendered correctly with bottom toolbar in toolbar area for wayfire.org

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14660]
## Steps to reproduce

1. Navigate to https://wayfire.org when using a bottom toolbar
2. Scroll down.

### Expected behavior

Gray background color extends to bottom of screen. 

### Actual behavior

Background color becomes white where toolbar would appear. 

![signal-2020-09-03-011652](https://user-images.githubusercontent.com/152493/92074272-aa301d00-ed83-11ea-9a86-9ce42fa11da7.png)

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 200902 06:01 (Build #2015761523)
AC: 57.0.0, c84cf8e77
GV: 82.0a1-20200831091558
AS: 61.0.13

Also reproducible on RB 1.0.2036 (Build #22460611 GV: 82.0a1-20200829091226)
 📦: 57.0.20200831130101, b70bef444
🚢: 61.0.13

**Comment by liuche** [comment]
Is this the same as #8768 and #11389? We just landed a GV improvement for this that was verified by QA a day ago.

**Comment by yoasif** [comment]
Unfortunately, I am still seeing this in:

Nightly 200909 06:00 (Build #2015762867)
AC: 58.0.20200907130126, dc4efe6c5
GV: 82.0a1-20200906094118
AS: 61.0.13

**Comment by s-ankur** [comment]
Also seeing this on SpaceBattles/SufficientVelocity Forum as described in https://www.reddit.com/r/firefox/comments/jepnlv/firefox_for_android_black_bar_on_bottom/

**Comment by karlcow** [comment]
There is an issue which is similar on webcompat.
https://github.com/webcompat/web-bugs/issues/65518


1. Go http://animesub.info/
2. Zoom in (because the page is currently using the full space)
3. scroll and make the url bar disappear. 

A white rectangle is left instead of the url bar sliding out of view.

**Comment by karlcow** [comment]
To note that this issue is not fixed and should be reopened. 
This didn't fix it. https://bugzilla.mozilla.org/show_bug.cgi?id=1633322

* https://github.com/webcompat/web-bugs/issues/92242
* https://github.com/webcompat/web-bugs/issues/65518
*

**Comment by Mugurell** [comment]
These seem like different issues. I'll move the original one to Bugzilla and open new ones for the two webcompat tickets.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1739319

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
