### ISSUE TITLE
Please add socks5 proxy support.

### ISSUE THREAD

**Issue by Alex-coffen** [mozilla-mobile/fenix#14664]
Please add socks5 proxy support. Previously it was located in the about:config but it's gone now.

**Comment by freebrowser1** [comment]
Another reason to support about:config. I know, that is another issue, but the lack thereof results in a lot of feature requests like this, which area already there, but deliberately disabled requiring re-inventing the wheel.

**Comment by yoasif** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/4105
