### ISSUE TITLE
regression: request option to disable session restore

### ISSUE THREAD

**Issue by jawz101** [mozilla-mobile/fenix#14662]
### What is the user problem or growth opportunity you want to see solved?

Tabs remain loaded/queued every time the browser is relaunched

### How do you know that this problem exists today? Why is this important?
Fennec previously had the option to disable session restore under settings>advanced>restore tabs: don't restore tabs after quitting Firefox

Now there is a new setting to remove tabs after a day, week, month, manually but I'll have 6 tabs open just after a few minutes of clicking links from other apps that launch Firefox.  Now I find myself clicking more to constantly close background tabs.

### Who will benefit from it?
Fennec users familiar with this former preference

**Comment by cadeyrn** [comment]
The new Firefox already has the option to close tabs when quitting Firefox.

**Comment by jawz101** [comment]
> The new Firefox already has the option to close tabs when quitting Firefox.

... By having you click a quit button.

If you swipe Firefox away from the Android recent list, Fennec would go ahead and clear tabs when using this advanced setting.

Since they seem to be implementing a new time-based reset, they could make one choice be to reset when removed from recents

**Comment by DavidJCobb** [comment]
This has also been discussed at #5865 and #13227; it may be useful to refer to the comments there.

**Comment by jawz101** [comment]
#5865 looks like it falls in line with my thinking.  I mean, that quit button could simply be replaced with "clearing from recents will wipe out these picked things"

**Comment by liuche** [comment]
Thanks for filing, going to consolidate with #5865
