### ISSUE TITLE
[Bug] App crashes when using S-Pen or external mouse/touchpad.

### ISSUE THREAD

**Issue by ApfelsaftMafia** [mozilla-mobile/fenix#14663]
## Steps to reproduce
use spen or mouse in app and click any link

### Expected behavior
just work normal

### Actual behavior
app crashes at some point
sometimes only in DeX, sometimes only when keyboard cover is connected, but only when spen or mouse are involved

### Device information

* Android device: Samsung Galaxy Tab S6
* Fenix version: Nightly 200902 06:01

Same issue on Samsung Galaxy Note10

**Comment by kbrosnan** [comment]
Duplicate of #14624 / https://bugzilla.mozilla.org/show_bug.cgi?id=1662830
