### ISSUE TITLE
[Bug] Overflow or confusing display on "find within page" when total matches is large

### ISSUE THREAD

**Issue by passcod** [mozilla-mobile/fenix#14666]
## Steps to reproduce

1. Open https://www.wgtn.ac.nz/students/graduation-and-beyond/roll-of-graduates?qualyear=2013 (for example, happens elsewhere)
2. Use search in page function to search for `f`

### Actual behavior

Occurrences display looks like 123/-1

![Screenshot_20200903-191530](https://user-images.githubusercontent.com/155787/92084437-81f3fd00-ee1b-11ea-887f-bcf61832e2d3.jpg)

### Expected behavior

Either exact count 123/4567890 or some other render e.g 123/∞

### Device information

* Android device: Oneplus 6t, android 10, ONEPLUS A6010_41_200717
* Fenix version: Nightly 200901 06:03 (Build #2015761331)
AC: 57.0.20200831130101, b70bef444
GV: 82.0a1-20200829091226
AS: 61.0.13

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6256)

**Comment by topotropic** [comment]
I tried it out, this seems to be broken in multiple ways, when I tap to quick on the next/down arrow, the number indicator jumps to a red 0/0. 

I guess there's enough space to show the number of results if that's feasible.

**Comment by passcod** [comment]
Well it's worse now
![Screenshot_20210915-102050](https://user-images.githubusercontent.com/155787/133341571-9b53126e-b3db-4342-884a-0184f47605a1.jpg)

**Comment by passcod** [comment]
Whatever, I give up. I guess this will unstale it, but I'm unsubbing, so next time it will get closed.
Yes, it still occurs.
