### ISSUE TITLE
[Bug] menu have different size with different languages

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#14668]
## Steps to reproduce
1. Open menu with three dots
2. Change language (to English / non-English based on your previous language)
3. Open menu again
### Expected behavior
They have the same size
### Actual behavior
English is thinner / non-English is larger

<img src="https://i.ibb.co/QJcxgTn/Screenshot-20200903-111158-Firefox-Nightly.png" width="300"> <img src="https://i.ibb.co/PQcg9nj/Screenshot-20200903-111136-Firefox-Nightly.png" width="300">
### Device information

* Android device: Pocophone F1, android 9
* Fenix version: nightly 200903

**Comment by cadeyrn** [comment]
> Expected behavior
> They have the same size

No, that's not the expected behaviour because it was an intentional decision to implement a dynamic width. As you can see in your screenshots there is no reason to have a larger menu in English while in French it's needed if you don't want that most menu items are truncated.

**Comment by B0pol** [comment]
ok
