### ISSUE TITLE
[Bug] Discrepancies between the name of the site and the content

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#14672]
## Steps to reproduce - not sure exactly how to reproduce 100%
1. Open several sites.
2. Browse through them.
3. Observe the top sites' names, the sites's names in the History page, the tabs tray.

### Expected behavior
Every site has its personalized thumbnail/icon, without discrepancies.

### Actual behavior
* Some pages display different names for their sites. Basically, the thumbnail suggests the user what page "hides" under the icon, not the name. 
* Opening, for example, rockfm.ro, displayed the Suggested logins prompt, and all the credentials saved for the facebook.com page.
* Adding that page to Home-screen, displays it with the discrepancies on the device's home-screen.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 9), Huawei P20 Lite (Android 9)
* Fenix version: Beta 81.1.0-beta.2, and 9/1 Nightly

<img src="https://user-images.githubusercontent.com/40694158/92100396-6f120600-ede4-11ea-8603-a2df36555654.gif" width="300" height="550" />
<img src="https://user-images.githubusercontent.com/40694158/92100408-733e2380-ede4-11ea-9ac0-c8f2217ac22c.gif" width="300" height="550" />

![Untitled](https://user-images.githubusercontent.com/40694158/92101255-869dbe80-ede5-11ea-9fb2-c17d152c4638.png)

**Comment by AndiAJ** [comment]
Same for me on **`Beta 81.1.0-beta.2`** using a OnePlus A3 (Android 6.0.1)  

It looks like the rockfm.ro tab is renamed to spotify
If you'll add the rockfm tab as a shortcut or as a top site it'll be named as spotify

Noticed with the following STR:
1. Open Spotify
2. Open Rockfm.ro
3. Open the tabs Tray and check the title of the tabs
4. Add the rockfm tab as a top site
5. Add the rockfm tab as a shortcut

► Video
![20201013-133631](https://user-images.githubusercontent.com/51314259/92105945-4b52be00-edec-11ea-86e6-a9a641649d3b.gif)

**Comment by mobd** [comment]
Duplicate of #14433, they already have a fix coming up

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 9/10 on Samsung Galaxy Tab S6 (Android 9), and HTC 10 (Android 8).

![Untitled](https://user-images.githubusercontent.com/40694158/92744894-8b84e400-f38a-11ea-9573-726d4be6d8f8.png)
