### ISSUE TITLE
[Bug] Fennec migration: The "x" button from the Transfer saved logins pop up is missing

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#14677]
### Preconditions
On Fennec create a Primary(Master) password.
Save some logins on Fennec with the primary password enabled.

## Steps to reproduce
1. Migrate Fennec to Fenix;
2. Go to home screen and tap the "Enter master password" button from "Looking for your logins?" messaging card;
3. Type your primary password;
4. Observe the "x" button;
### Expected behavior
The "x" button is displayed as in the [abstract](https://app.abstract.com/share/7d855129-f9cf-4edc-b913-991233f744ef?collectionId=487109bf-eea4-4870-9f78-b27fbad5c26e&sha=bb86d85374e9d28368b7aeddc6764450edaf02f0).
### Actual behavior
The "x" button is missing.

![20200903_134934](https://user-images.githubusercontent.com/48799384/92106125-97056780-edec-11ea-91e4-e92d4093210e.gif)

### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8), Nexus 5 (Android 5);
* Fenix version: Beta 81.1.0-beta.2 (Build #2015761657), GV 81.0, from 9/2.

**Comment by ekager** [comment]
Ah the clear button on the edit text.
Via material design they only support 1 end icon/action so this would have to be custom and for this temporary message it seems like overkill. 
FYI @apbitner

**Comment by apbitner** [comment]
@ekager I included the clear button only bc we have it when you edit a saved password in Settings, so wanted to be consistent with the pattern. This message is temporary, so an exception could be made, otherwise we should probably include the clear button as part of all password fields.

**Comment by ekager** [comment]
Going to close this because of the temporary nature of this dialog. We can create a custom component with the X/eye for future use cases!
