### ISSUE TITLE
[Bug] Fennec migration: The "Invalid password" error message is displayed from the first character typed in the Transfer saved logins field 

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#14678]
### Preconditions
On Fennec create a Primary(Master) password.
Save some logins on Fennec with the primary password enabled.

## Steps to reproduce
1. Migrate Fennec to Fenix;
2. Go to home screen and tap the "Enter master password" button from "Looking for your logins?" messaging card;
3. Type the first character from your primary password;
4. Observe the error message;
### Expected behavior
The "Invalid password" error message is displayed after typing the password and tapping the "Continue and transfer" button.
### Actual behavior
 The "Invalid password" error message is displayed from the first character typed in the Transfer saved logins field 

![20200903_134934](https://user-images.githubusercontent.com/48799384/92106125-97056780-edec-11ea-91e4-e92d4093210e.gif)

### Notes
This is also reproducible when tapping the view icon from the password field.
### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8), Nexus 5 (Android 5);
* Fenix version: Beta 81.1.0-beta.2 (Build #2015761657), GV 81.0, from 9/2.

**Comment by ekager** [comment]
I set a text listener to continually update the error state based on the text entered so this is expected. 
Thank you for flagging!
