### ISSUE TITLE
[Bug] Private mode should set keyboard to private e 

### ISSUE THREAD

**Issue by gabrielambuehl** [mozilla-mobile/fenix#14670]
## Steps to reproduce
Switch to private tab, keyboard remains in normal mode

### Expected behavior
Use keyboard in private mode (as Firefox focus does)

**Comment by cadeyrn** [comment]
Are you using Firefox Nightly, Beta or Stable? If the answer is Nightly then it's a duplicate of #13423.

**Comment by gabrielambuehl** [comment]
Very much sounds like it is.

Github search did not yield that 🤷‍♂️. Sorry about the duplicate.
