### ISSUE TITLE
FNX-5049 ⁃ [Bug] File upload with input type "field" results in "No file selected"

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-mobile/fenix#1467]
## Steps to reproduce
1) Go to https://adaptable-nest.glitch.me/
2) Click on the "Browse" in the upload field (doesn't matter which one)
3) Select an image or file from your gallery

### Expected behavior
Fenix should show the file name of the selected file and then also upload that file to the server (server part not implemented in the test case).

### Actual behavior
Fenix shows "No file selected" and also doesn't upload the file to the server (tested with https://fc-test.michaelkohler.info/).

![photo5287395983564581486](https://user-images.githubusercontent.com/330324/55749549-b5690700-5a30-11e9-9414-9ec98d2b1177.jpg)

### Device information
* Android device: 9
* Fenix version: 1.0.1915 (Build #10981206) - 68.0a1-20190403060632

### Other browsers tested
In Firefox Nightly it works as expected:

![photo5287395983564581487](https://user-images.githubusercontent.com/330324/55749585-d03b7b80-5a30-11e9-9272-054f4475d363.jpg)

In Reference Browser as well as Firefox Focus I'm seeing the same behavior as in Fenix.

**Comment by emilio** [comment]
Ah, so this is what prevents me from attaching screenshots to Fenix bug reports from Fenix itself :)

**Comment by emilio** [comment]
This works on Fennec fwiw, in case it helps to narrow the investigation.

**Comment by Amejia481** [comment]
GeckoView  related issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1515440

**Comment by Amejia481** [comment]
After https://github.com/mozilla-mobile/fenix/pull/2513 is merged this should be fixed

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1920 (#11360657), with HTC 10 (Android 8.0), and Sony Xperia Z5 Premium (Android 7.1.1).
