### ISSUE TITLE
[Bug] Missing private tab icon from notifications

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#14687]
## Steps to reproduce

1. Open a new private tab, go to [website]
2. Exit out from the app
3. Pull down from top to see your quick settings and notifications
4. Observe the "Firefox Beta (Private)" notification

### Expected behavior

Icon is present

### Actual behavior

Icon is missing

### Device information

* Android device: OnePlus 3T, Android 10
* Fenix version: 81.1.0-beta 2

**Comment by cadeyrn** [comment]
Duplicate of #14460.

**Comment by miladmaz12** [comment]
Thanks, I'll close the issue since its a duplicate.
