### ISSUE TITLE
[Bug] On Firefox Custom Tabs --> 3-dot menu, the desktop site label is truncated

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#14684]
## Steps to reproduce

1. Click on an external link
2. Firefox Custom Tabs opens, touch the 3-dot menu
3. Observe the desktop site label "Deskto.."

### Expected behavior

Desktop site shouldn't be truncated

### Actual behavior

Desktop site is truncated

### Device information

* Android device: OnePlus 3T, Android 10
* Fenix version: 81.1.0-beta 2

**Comment by miladmaz12** [comment]
Related #12253

**Comment by liuche** [comment]
Either a shorter string or an adjustable width menu.
