### ISSUE TITLE
[Bug] With Autofill logins Off, I still see suggested logins and have the password filled-in

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#14686]
## Steps to reproduce
1. Save a few passwords for a website.
2. Go to Settings>Logins> turn off Autofill
3. Return to the website and tap the username field.
4. Fill in the username and tap the "next" button from the keyboard to jump to the password field.
### Expected behavior
The suggested logins list shouldn't appear(?) - not sure about the desired behavior.
The password field shouldn't be auto-filled.
### Actual behavior
When you jump from the username to the password field using the keyboard, the password is auto-filled.
The suggested logins is still displayed.
### Device information

* Android device: Nexus 5 (Android 5)
* Fenix version: 81.1.0-beta.2

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1663039
