### ISSUE TITLE
Change firefox sync server settings in Fx Android 79

### ISSUE THREAD

**Issue by eddieirvine** [mozilla-mobile/fenix#14681]
### What is the user problem or growth opportunity you want to see solved?
If you run your own Firefox Sync server, normally the value "identity.sync.tokenserver.uri" needs to be modified.

### How do you know that this problem exists today? Why is this important?
Since the release of Fx for Android 79, it is no more possible to launch about:config which allows to change "identity.sync.tokenserver.uri".

### Who will benefit from it?
Everybody who is running his/her own sync server.

**Comment by cadeyrn** [comment]
Settings > About Firefox
Press 5× the Firefox logo
Return to the settings main screen
You can change the sync server at the top of this screen

**Comment by Blub** [comment]
Also, using a QR to setup the account on a new installation seems to be able to sync my bookmarks but then afterwards completely discards the custom sync server settings, so those are now where they don't belong... Thanks. It's way too easy for this to go wrong.

**Comment by murchu27** [comment]
@Blub is it now working for you? I followed @cadeyrn's steps, set the Custom Sync server option, and logged in, but I still get the "Last synchronised: never" message. 

![Screenshot_20200905-111411](https://user-images.githubusercontent.com/24554361/92303060-6bf45280-ef69-11ea-9ddd-dea0b0c69d3a.jpg)

The address is definitely right; if I go to the address in the browser, I get a JSON response like this one:

`{"status": "error", "errors": [{"location": "body", "name": "", "description": "Unauthorized"}]}`

I also get a line in my access log on the server side from doing this:

`192.168.0.1 - - [05/Sep/2020:11:10:09 +0100] "GET /token/1.0/sync/1.5 HTTP/1.1" 401 378 "-" "Mozilla/5.0 (Android 10; Mobile; rv:80.0) Gecko/80.0 Firefox/80.0"`

When trying to sync though, I get nothing in my access or error logs, so I've no idea what's wrong.

**Comment by Blub** [comment]
Yeah that part's working for me now. Re-enabling 2fa fails but w/e, different bug.

**Comment by murchu27** [comment]
Glad it's working for you. I may have to file a bug report on bugzilla...

**Comment by ashemsay** [comment]
Hello, for me this does not work as the "Personal sync server" link is greyed out.
I already tried restarting the application, and option completely disappears, I have to enable debugging options all over and again find the option greyed out.
What should I do?

**Comment by eddieirvine** [comment]
I have the same issue than @murchu27:
I set my private sync server in Fx 79 for Android, but it's not synchronizing.
Could it be that now the account is screwed up, because it was syncing with Mozilla servers?

**Comment by liuche** [comment]
This already exists in app, from #3762

Docs update has a bug open here mozilla-services/services-engineering#50 so please comment there if the information isn't clear enough.
