### ISSUE TITLE
Translation addons

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#14697]
The translation add-on on the link is very well built on both the desktop and fenix browser. Translation feature is a feature that users most search for in alternative browsers, but they do not like much (yandex translation, bing translation). This plugin has both google and yandex translation and has rich features.

Much better than the built-in translation in the Chrome browser

Please add this add-on to the list of recommended add-ons.

Screenshot :  forked froom fenix
![Screenshot_20200903-230040_Iceweasel](https://user-images.githubusercontent.com/60405617/92161807-d0b08f80-ee39-11ea-8eab-992bb423c335.png)

**Comment by reyis4402** [comment]
Links :. https://addons.mozilla.org/tr/firefox/addon/traduzir-paginas-web/

**Comment by cadeyrn** [comment]
> We would like to expand our support to other add-ons but we are not keeping open requests for specific ones, even those in the recommended add-ons program. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.

https://github.com/mozilla-mobile/fenix/issues/13925#issuecomment-677828853

See also #14034 for the next steps for expanding the add-on support in Firefox.

**Comment by mohibo** [comment]
> 
> 
> > We would like to expand our support to other add-ons but we are not keeping open requests for specific ones, even those in the recommended add-ons program. Please follow the [Add-ons Blog](https://blog.mozilla.org/addons/) for future updates.
> 
> [#13925 (comment)](https://github.com/mozilla-mobile/fenix/issues/13925#issuecomment-677828853)
> 
> See also #14034 for the next steps for expanding the add-on support in Firefox.

that's for nightly only
