### ISSUE TITLE
[Bug] Weird PBM topbar tint issues 

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#14690]
## Steps to reproduce

1. Open a link under PBM, close the tab
2. Observe the topbar
3. From tint to no tint

### Device information

* Android device: OnePlus 3T, Android 10
* Fenix version: Latest Beta

**Comment by Diana-Rus** [comment]
Hi @miladmaz12 when you say tint to no tint on the topbar, what do you exactly mean? A video would help in this case.
Is the topbar that you mention the device's status bar/android bar?
Maybe this issue #12304 , is similar to yours?

**Comment by miladmaz12** [comment]
Yes its similar to that.

**Comment by Diana-Rus** [comment]
Hi, thanks @miladmaz12  than i'll be closing this one and please follow the other issue to see when it will be fixed 😊.
