### ISSUE TITLE
[Bug] Pinch to zoom performs badly with graphical glitches

### ISSUE THREAD

**Issue by mattok** [mozilla-mobile/fenix#14691]
# Steps to reproduce

- Use default mode with address bar at bottom.
- I've tried with and without the zoom override accessibility option. It doesn't seem to make a difference to behaviour as far as I can tell.
- Visit https://thetimes.co.uk
- Wait for the privacy settings message to appear
- Use two fingers to zoom in, then attempt to zoom out.

# Expected behavior

- You can smoothly zoom in.
- You can smoothly zoom all the way out.

# Actual behavior

On Firefox for Android, 80.1.2 (Build #2015761281), AC: 54.0.5, 02934e437, GV: 80.0.1-20200827204751, AS: 61.0.10
- Zooming back out sometimes behaves erratically.
- Repainting of the screen is sometimes very very slow.
- Zooming back out leaves black rectangles over parts of the screen.
- It is sometimes not possible to zoom all the way back out, thus obscuring the buttons you need to press. (This definitely happened to me, but I am struggling to reproduce it now.)

On Firefox Nightly for Android, Nightly 200902 06:01 (Build #2015761521) AC: 57.0.0, c84cf8e77, GV: 82.0a1-20200831091558, AS: 61.0.13
- Zooming in sometimes doesn't work at all (you un-pinch and nothing happens).
- Zooming back out sometimes behaves erratically.
- Repainting of the screen is sometimes very very slow or doesn't seem to happen at all.
- Zooming back out leaves black rectangles over parts of the screen.

# Device information

OnePlus 1, Android 6.0.1

# GeckoView issue
https://bugzilla.mozilla.org/show_bug.cgi?id=1663958

**Comment by Mugurell** [comment]
Thank you @mattok !
I tried testing this and I encountered another issue - https://github.com/mozilla-mobile/fenix/issues/14821 
I saw some layout issues, but based on your report the problems manifest a lot worse for you.
Can you please make a short video with the problems described just to have a a deeper understanding and know better what to concentrate on when working on this?

**Comment by mattok** [comment]
Sorry, no video, but here is a sequence of screenshots:
1. Open up a page on the times.co.uk website and see this. 
![Screenshot_20200907-221439](https://user-images.githubusercontent.com/2501023/92613768-3aee8780-f2b3-11ea-955b-7154a095bcc8.jpg)
2. Attempt to zoom in by anti-pinching (or whatever it's called). Nothing happens!
3. Try again. Oh... what's that? ![Screenshot_20200907-221521](https://user-images.githubusercontent.com/2501023/92613925-670a0880-f2b3-11ea-8a5a-10783522e6cf.jpg)
4. I'd better zoom out a bit by pinching...  ![Screenshot_20200907-221545](https://user-images.githubusercontent.com/2501023/92614090-8e60d580-f2b3-11ea-92aa-20528e7cc7ea.jpg)
5. Oh. Maybe I should zoom right out. ![Screenshot_20200907-221555](https://user-images.githubusercontent.com/2501023/92614226-b8b29300-f2b3-11ea-89e7-52a82b6dbe64.jpg)
6. Maybe it'll sort itself out if I rotate my screen... ![Screenshot_20200907-221701](https://user-images.githubusercontent.com/2501023/92614325-d5e76180-f2b3-11ea-83c8-a0fdf0a3c4d3.jpg)

All this took place over almost 3 minutes. That was because it took loads of time for the page to re-render after each pinch or anti-pinch. It appears as if it is doing a LOT of recalculation. The visible consent window is a centred overlay over a page. Even though none of the page is ever visible, because it is hidden under the overlay, it appears to be that it is being rejiggled/calculated when you zoom, and the consent window is probably then re-centred etc. Something about all of that makes the zoom very unstable. I think that the black patches are not pure graphical glitches... They are probably part of the page to the side of or under the overlay that has been rendered on top of it for some reason. I hope that helps.

**Comment by Mugurell** [comment]
Thank you!
I've duplicated the issue over to GeckoView - https://bugzilla.mozilla.org/show_bug.cgi?id=1663958

**Comment by staktrace** [comment]
@mattok Can you also go to `about:support`, click on the "copy as text" button, and paste the result here? Thanks!

**Comment by mattok** [comment]
> Application Basics
> 
> NameFirefox NightlyVersion82.0a1Build ID20200906094118Distribution IDUser AgentMozilla/5.0 (Android 6.0.1; Mobile; rv:82.0) Gecko/82.0 Firefox/82.0OSLinux 23 #1 SMP PREEMPT Thu Aug 11 17:16:59 PDT 2016Multiprocess Windows 0/0 Enabled by default Remote Processes 1 Google Location Service KeyFoundGoogle Safebrowsing KeyFoundMozilla Location Service KeyFoundSafe Modefalse 
> 
> Crash Reports for the Last 3 Days
> 
> Report IDSubmitted 
> 
> Nightly Features
> 
> NameVersionID 
> 
> Remote Processes
> 
> TypeCountWeb Content1 / 1 
> 
> Add-ons
> 
> NameTypeVersionEnabledIDMozilla Android Components - Adsextension58.0.20200907130126.0909060941trueads@mozac.orgMozilla Android Components - Browser Iconsextension58.0.20200907130126.0907130442trueicons@mozac.orgMozilla Android Components - Cookiesextension58.0.20200907130126.0909060941truecookies@mozac.orgMozilla Android Components - Firefox Accounts WebChannelextension58.0.20200907130126.0907130440truefxa@mozac.orgMozilla Android Components - ReaderViewextension58.0.20200907130126.0907130443truereaderview@mozac.orgWeb Compatextension14.0.0truewebcompat@mozilla.orgWebCompat Reporterextension1.5.0truewebcompat-reporter@mozilla.org 
> 
> Graphics
> 
> FeaturesCompositingOpenGLAsynchronous Pan/Zoomtouch input enabled; autoscroll enabled; smooth pinch-zoom enabledWebGL 1 Driver WSI InfoEGL_VENDOR: Qualcomm, Inc EGL_VERSION: 1.4 EGL_EXTENSIONS: EGL_QUALCOMM_shared_image EGL_KHR_image EGL_KHR_image_base EGL_QCOM_create_image EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_KHR_lock_surface3 EGL_KHR_fence_sync EGL_KHR_cl_event EGL_KHR_cl_event2 EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_renderbuffer_image EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache EGL_ANDROID_framebuffer_target EGL_KHR_create_context EGL_KHR_wait_sync EGL_KHR_gl_colorspace EGL_ANDROIDX_no_config_context EGL_KHR_partial_update EGL_ANDROID_image_crop EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_image_native_buffer EGL_KHR_gl_colorspace EGL_IMG_image_plane_attribs IsWebglOutOfProcessEnabled: 0WebGL 1 Driver RendererQualcomm -- Adreno (TM) 330WebGL 1 Driver VersionOpenGL ES 3.0 V@140.0 AU@ (GIT@Ia6c73e7530)WebGL 1 Driver ExtensionsGL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query WebGL 1 ExtensionsANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_sRGB EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_contextWebGL 2 Driver WSI InfoEGL_VENDOR: Qualcomm, Inc EGL_VERSION: 1.4 EGL_EXTENSIONS: EGL_QUALCOMM_shared_image EGL_KHR_image EGL_KHR_image_base EGL_QCOM_create_image EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_KHR_lock_surface3 EGL_KHR_fence_sync EGL_KHR_cl_event EGL_KHR_cl_event2 EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_renderbuffer_image EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache EGL_ANDROID_framebuffer_target EGL_KHR_create_context EGL_KHR_wait_sync EGL_KHR_gl_colorspace EGL_ANDROIDX_no_config_context EGL_KHR_partial_update EGL_ANDROID_image_crop EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_image_native_buffer EGL_KHR_gl_colorspace EGL_IMG_image_plane_attribs IsWebglOutOfProcessEnabled: 0WebGL 2 Driver RendererQualcomm -- Adreno (TM) 330WebGL 2 Driver VersionOpenGL ES 3.0 V@140.0 AU@ (GIT@Ia6c73e7530)WebGL 2 Driver ExtensionsGL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query WebGL 2 ExtensionsEXT_color_buffer_float EXT_texture_filter_anisotropic MOZ_debug WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_contextUses TilingtrueUses Tiling (Content)trueTarget Frame Rate63GPU #1ActiveYesDescriptionModel: A0001, Product: bacon, Manufacturer: OnePlus, Hardware: bacon, OpenGL: Qualcomm -- Adreno (TM) 330 -- OpenGL ES 3.0 V@140.0 AU@ (GIT@Ia6c73e7530)Vendor IDQualcommDevice IDAdreno (TM) 330Driver VersionOpenGL ES 3.0 V@140.0 AU@ (GIT@Ia6c73e7530)RAM0GPU #2DiagnosticsAzureCanvasBackendskiaAzureContentBackendskiaAzureFallbackCanvasBackendnoneCMSOutputProfileEmpty profile dataDisplay01080x1920DisplayCount1TileHeight512TileWidth512Device ResetTrigger Device ResetDecision LogHW_COMPOSITINGavailable by defaultforce_enabled by user: Force-enabled by prefOPENGL_COMPOSITINGavailable by defaultforce_enabled by user: Force-enabled by prefWEBRENDERopt-in by default: WebRender is an opt-in featureWEBRENDER_QUALIFIEDavailable by defaultblocklisted by env: No qualified hardwareWEBRENDER_COMPOSITORdisabled by default: Disabled by defaultWEBRENDER_ANGLEopt-in by default: WebRender ANGLE is an opt-in featureWEBRENDER_DCOMP_PRESENTopt-in by default: WebRender DirectComposition is an opt-in featureOMTPdisabled by default: Disabled by defaultWEBGPUdisabled by default: Disabled by defaultCrash Guard Disabled FeaturesWorkaroundsFailure Log 
> 
> Media
> 
> Audio BackendopenslMax Channels2Preferred Sample Rate48000Roundtrip latency (standard deviation)...Output DevicesNameGroupVendorStatePreferredFormatChannelsRateLatencyEnabledAlldefault: S16LE, support: S16LE S16BE F32LE F32BE2default: 44100, support: 41000 - 44100128 - 410Input DevicesNameGroupVendorStatePreferredFormatChannelsRateLatencyEnabledAlldefault: S16LE, support: S16LE S16BE F32LE F32BE1default: 44100, support: 41000 - 44100128 - 410Media Capabilities Enumerate database 
> 
> Environment Variables
> 
> Important Modified Preferences
> 
> browser.cache.disk.filesystem_reported1dom.presentation.device.nameA0001dom.w3c_pointer_events.enabledtrueextensions.lastAppVersion82.0a1idle.lastDailyNotification1599513520media.gmp.storage.version.observed1network.trr.blocklist_cleanup_donetrueprivacy.purge_trackers.date_in_cookie_database0privacy.purge_trackers.last_purge1599513520783storage.vacuum.last.index0 
> 
> Important Locked Preferences
> 
> fission.autostartfalse 
> 
> Accessibility
> 
> ActivatedfalsePrevent Accessibility0 
> 
> Library Versions
> 
> Expected minimum versionVersion in useNSPR4.29 Beta4.29 BetaNSS3.57 Beta3.57 BetaNSSSMIME3.57 Beta3.57 BetaNSSSSL3.57 Beta3.57 BetaNSSUTIL3.57 Beta3.57 Beta 
> 
> Startup Cache
> 
> Disk Cache Path/data/user/0/org.mozilla.fenix/files/mozilla/9iojj9ef.default/startupCache/startupCache.4.littleIgnore Disk CachefalseFound Disk Cache on InittrueWrote to Disk Cachefalse 
> 
> Internationalization & Localization
> 
> Application SettingsRequested Locales["en-GB"]Available Locales["an","ar","ast","az","be","bg","bn","br","bs","ca","cak","cs","cy","da","de","dsb","el","en-CA","en-GB","en-US","eo","es-AR","es-CL","es-ES","es-MX","et","eu","fa","ff","fi","fr","fy-NL","ga-IE","gd","gl","gn","gu-IN","he","hi-IN","hr","hsb","hu","hy-AM","id","is","it","ja","ka","kab","kk","kn","ko","lij","lo","lt","lv","ml","mr","ms","my","nb-NO","ne-NP","nl","nn-NO","oc","pa-IN","pl","pt-BR","pt-PT","rm","ro","ru","sk","sl","son","sq","sr","sv-SE","ta","te","th","tr","trs","uk","ur","uz","vi","wo","xh","zam","zh-CN","zh-TW"]App Locales["en-GB","en-US","en-CA"]Regional Preferences["en-GB"]Default Locale"en-US"Operating SystemSystem Locales["en-GB"]Regional Preferences["en-GB"]

**Comment by mattok** [comment]
I tried the same on a OnePlus 2 device (not mine), which has a far more up to date OS, and although zoom in and out performance was just a little bit jerky, performance was much better and there were NO graphical glitches that I observed. I'm wondering whether this problem could be because I have an out of date Android OS software environment (as opposed to this being a hardware problem or Firefox software problem). If so, and if this is not affecting very many other people, then maybe the solution is to finally get around to flashing my device and installing a new up-to-date version of Android. Feel free to say so if you think that's the case.

**Comment by staktrace** [comment]
Thanks for the info! According to your about:support your device is getting the older, non-WebRender graphics backend in Firefox. As we are phasing that backend out in favour of the new WebRender backend, it seems unlikely that we'll invest the time to try and figure out the root cause here, particularly if a newer version of Android seems to fix the issue. Most likely it's some sort of graphics driver bug and the newer version of Android fixes the driver bug. In theory it is possible for us to add a workaround in Firefox for the driver bug but it would require a bunch of investigation - and that's going to be hard since I don't think we have a device on hand that can reproduce the problem. If you are able to install a newer version of Android then that would probably work out better.

**Comment by mattok** [comment]
OK. It sounds like I need to set aside some time for upgrading my phone then. Thanks @staktrace. I'll close this issue then.
