### ISSUE TITLE
FNX-5051 ⁃ [Bug] The space between the tabs icon and the three dots icon is too large

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1469]
It just does feel... Right.
![Screenshot](https://user-images.githubusercontent.com/32398857/55755171-c27ff900-5a24-11e9-88bc-d2ba254a6f29.jpg)UNITO-UNDERSCORE!20190408-170844!UNITO-UNDERSCORE!Fenix!

**Comment by Scripterr** [comment]
There is also some space between the lockpad icon and site address, if it can be removed the long URLs can be more visible.

**Comment by topotropic** [comment]
@AmyYLee did you address this in your review? Thanks!

**Comment by AmyYLee** [comment]
> @AmyYLee did you address this in your review? Thanks!

It's been added.

**Comment by sblatz** [comment]
From @topotropic:

![bottom-bar](https://user-images.githubusercontent.com/353960/61711019-587d2c80-ad53-11e9-8057-a2917d987af4.png)

**Comment by ekager** [comment]
This has been recently touched up and addressed. See https://github.com/mozilla-mobile/android-components/issues/4490
