### ISSUE TITLE
[Bug] Can't load any webpage because of XML parsing error

### ISSUE THREAD

**Issue by hey-i** [mozilla-mobile/fenix#14700]
## Steps to reproduce
1. Go to any website

### Expected behavior
Loads website

### Actual behavior
Shows a blank screen. If you click on the URL, there will be a brief moment where you can see the error message 

> XML Parsing Error: no root element
> Location: chrome://geckoview/content/geckoview.xhtml
> Line Number 1, Column 1:
> 
> 
> ^

### Device information

* Android device: SM-J737V
* Fenix version: 80.1.2 (Build #2015761281)

**Comment by hwinnemoe** [comment]
What is your Android version and do you have any add-ons activated? If you have any active add-ons, does it keep happening without any activated add-ons as well?

**Comment by hey-i** [comment]
It is Android version 9. I had ublock origin enabled, but disabling/removing it doesn't fix the problem.

**Comment by hwinnemoe** [comment]
Thanks! Can you reproduce on [Beta ](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) or [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

**Comment by hey-i** [comment]
Downloaded the Beta and it works

**Comment by kbrosnan** [comment]
What language is the phone set to? If you used the previous version of Firefox Android did you set a custom language? If so then which one? Those sorts of XML parsing errors generally mean some sort of langpack issue or corrupted browser state.

**Comment by hey-i** [comment]
It is set to "Follow device language" which is English

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1668842

**Comment by agi** [comment]
@hey-i @dontskipnine do you a rooted device by any chance?

**Comment by czipperz** [comment]
I have this problem after taking an update a couple days ago

**Comment by GHolk** [comment]
i faced this problem on firefox android stable version.
one can solve this problem with *clean storage space* in system setting.

**Comment by makarhuyaker** [comment]
I have rooted device with lineage os 14 and i getting this error

**Comment by rhz** [comment]
This started happening in my phone about a week ago I'd say. @GHolk, you say it can be solved by cleaning Firefox's storage space in system settings. Before doing that, I'd like to know if I'll lose my open tabs, firefox sync info, bookmarks and all that by cleaning the storage space. My system settings say there are more than 250 mb in data storage space used by Firefox.

I'm using Firefox for Android stable version 98.3.0.
Android version 7.0.

**Comment by GHolk** [comment]
@rhz you will lose all your tabs.
Do you use firefox sync? If yes, tried this to back up all your tabs:

 1. In firefox desktop, open sync tabs sidebar.
 2. right click on your mobile device, select open all in new tabs.
 3. press shift and right click on tab to select all opened tabs.
 4. right click on tabs and add them to bookmark.

If you have root permission, copy `/data/data/org.mozilla.firefox/files/mozilla_components_session_storage_gecko.json`,
and `jq .sessionStateTuples[].session.url mozilla_components_session_storage_gecko.json` or somewhat.

~~If you have no root permission, tried adb back and adb backup extractor.~~
Firefox android does not allow adb backup.

**Comment by rhz** [comment]
Thank you @GHolk. I think I'll wait for Firefox to fix the problem in a future release. In the meantime, I'm using DuckDuckGo's android browser which I imagine is based on Firefox.
