### ISSUE TITLE
[Bug] when a new private tab  is created, the keyboard appears behind the URL bar

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#14703]
## Steps to reproduce

Create a new private tab, you must be in a normal tab before create it. The problem would also pass in the other way.

### Expected behavior

New tab is created and the keyboard appears below the URL bar 

### Actual behavior

The keyboard appears behind the URL bar

### Device information
Oukitel c5

* Android device: 7.0
* Fenix version: Nightly 200903 06:04

**Comment by liuche** [comment]
I don't think I understand what is happening, can you include a screenshot?

**Comment by sv-ohorvath** [comment]
I can also reproduce this on an Android 7 device (Nexus 9 tablet). STR:
1. Open the tabs tray.
2. Tap the private mode button
3. Tap the [+ Private] button 
![Screenshot_20200923-120141](https://user-images.githubusercontent.com/4037709/93991747-4d79be00-fd95-11ea-9075-8561330daee0.png)

Couldn't reproduce on Pixel 4 (Android 10).

**Comment by joelocandol** [comment]
![Uploading Screenshot_20200924-080824.png…]()

**Comment by joelocandol** [comment]
![Screenshot_20200924-080824](https://user-images.githubusercontent.com/59028737/94143319-a7ce5980-fe3d-11ea-9f13-404763e7ca56.png)

**Comment by ebalazs-sv** [comment]
This is reproducible on Nightly 201020 05:03 (Build #2015770729) GV 83.0a1 from 10/20 with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Nightly 201214 05:03 (Build #2015781291) GV 85 from 12/14 and on the latest Beta and Release builds with Huawei P9 Lite (Android 7).
I will remove the qa:needed label.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible. I verified it on the Latest Release 87.0.0-rc.1 and on the latest Nightly 210329 00:12 (GV89). Device used: Motorola Nexus 6 (Android 7.1.1)


https://user-images.githubusercontent.com/48829350/112856329-589d0600-90b8-11eb-84c3-432859f36e99.mp4

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Verified as fixed on the latest Nightly (94.0a1 - 2021-10-04T05:10:50.531272).

Devices used:

Samsung Galaxy Tab S3 (Android 9).
Huawei P30 (Android 10).
Xiaomi Redmi 11 Lite (Android 11).
