### ISSUE TITLE
Add option to place Open in App button to address bar/toolbar

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14705]
### What is the user problem or growth opportunity you want to see solved?

As a user, I would like to generally not open links in apps, but want to optionally open them in an app. I'd like an easy way to discover/remember this without needing to open the main menu. 

### How do you know that this problem exists today? Why is this important?

This existed as the default in Fennec and while it was confusing to some, for more advanced users it was a valuable feature. This is being asked for on social media and in Google Play reviews as a missed feature from Fennec. It would be good to offer this as an option to those missing those features to help bring review scores up and to cater to user desire.

This helps to differentiate Fenix in catering to user preferences. 

### Who will benefit from it?

Migrated Fennec users, advanced users who generally prefer the web but sometimes want to opportunistically open in app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6314)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809263

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
