### ISSUE TITLE
[Bug][a11y] Onboarding screen - Text Contrast and touch target need to be changed for greeting card "Welcome to Firefox Nightly"

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14714]
## Prerequisites:
- Have Google Accessibility Scanner installed.
- Have a clean Firefox profile.
## Steps to reproduce
1. Open app and inspect the screen elements with the scanner.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
**Section: Welcome to Firefox Nightly**
**- Text contrast**
org.mozilla.fenix:id/header_text
The item's text contrast ratio is 3.70. This ratio is based on an estimated foreground color of #9B63F5 and an estimated background color of #FBFBFE. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.
**- Touch target**
org.mozilla.fenix:id/learn_more
This item's height is 20dp. Consider making the height of this touch target 48dp or larger.
### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version: Nightly 9/4

<details closed><summary>Screen</summary>

![screenshot_Firefox Nightly_2020-09-04-12_56_19](https://user-images.githubusercontent.com/49859863/92227511-122f5200-eeaf-11ea-971a-44fe0ab62cbd.png)
</details>

**Comment by amedyne** [comment]
Need new color for contrast.

**Comment by topotropic** [comment]
yes! thank you. This card will go away with the redesigned onboarding flow that's about to be implemented https://github.com/mozilla-mobile/fenix/issues/18494.
