### ISSUE TITLE
[Bug][a11y] Touch target increase for refresh button from tabs tray

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14718]
##Perquisites
- Have Google Accessibility Scanner installed.
- Have Secret Settings enabled
- Be connected with an fx-account
## Steps to reproduce
1. Open browser and tap on the tabs tray
2. Scan the home screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
The refresh button needs to have touch target resized to 48dp from 24dp.
### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version: Nightly 9/4

<details closed><summary>Screen</summary>

![Screenshot_20200904-134252](https://user-images.githubusercontent.com/49859863/92234526-e4e8a100-eeba-11ea-8d4b-b3e319c5141c.png)
</details>

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/10 with Google Pixel 3 (Android 11).
