### ISSUE TITLE
[Bug] Search hotkey does not work

### ISSUE THREAD

**Issue by paroj** [mozilla-mobile/fenix#14713]
## Steps to reproduce
On a Hardware Keyboard press: Ctrl + F
### Expected behavior
Search In Page Bar appears
### Device information

* Android device: Galaxy Tab S4
* Fenix version: 79.0.5

**Comment by mcarare** [comment]
@paroj Thank you for your report!
This is already on our radar, see https://github.com/mozilla-mobile/fenix/issues/3729.
