### ISSUE TITLE
Add an option to disable inline autofill from the address bar

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#14712]
Some users would like the address bar to only attempt to load whatever literal string was typed in. (currently, typing 'g' and submitting will end up autofilling google.com and navigating to it. With autofill turned off, it would instead trigger a search for the string 'g' via the default search engine. 

### How do you know that this problem exists today? Why is this important?

I see this request occasionally pass through r/firedox

### Who will benefit from it?

Users who dislike the browser's autofill behavior.

**Comment by cadeyrn** [comment]
Duplicat of #5745.
