### ISSUE TITLE
[Bug] Swiping on URL-bar doesn't switch between tabs.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [mozilla-mobile/fenix#14711]
For a few weeks, this option of swiping left/right to switch between tabs has been disabled.
This is really unfortunate as is was **one of the best features of the new design**, compared to the old FF-layout.
I'd love to see it corrected/brought back.

**Comment by cadeyrn** [comment]
I cannot confirm the issue, works for me. Please provide additional information (there is a reason why there is a bug template - it asks for information about your device and Firefox version).

**Comment by Glitchy-Tozier** [comment]
I've got the newest version available on the Playstore, 80.1.2. As already mentioned, it's been this way for a few versions though. Samsung Galaxy S9.
There is no information I can think of that can help you reproduce this.
- It doesn't work both in private and in regular mode
- No swiping motion ever gets initiated, no matter whether there's one or multiple tabs.
- I didn't do anything crazy with Fenix
- Some Add-ons (such as ublock) are installed, they shouldn't really influence anything though.

**Comment by cadeyrn** [comment]
> 80.1.2

This is the reason. It's not yet implemented in Firefox 80. Try Firefox Beta or Firefox Nightly, there it's already implemented.

**Comment by Glitchy-Tozier** [comment]
Okay, I'll delete this then
