### ISSUE TITLE
New tab button to reflect the toolbar position

### ISSUE THREAD

**Issue by smaxus** [mozilla-mobile/fenix#14717]
Please consider returning "add new tab" button to the top of the tab list - esp. in the toolbar on the top mode. Toolbar on the bottom mode is inconvenient since you still have to move your finger to the top of the screen frequently, e.g. to select recent tabs in the tab list, or the top sites in the new tab page.

**Comment by hwinnemoe** [comment]
Related to/Duplicate of #14403
