### ISSUE TITLE
[Bug][a11y] Touch target for the radio button search engine selection needs resizing

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14725]
## Prerequisites:
- Have Google Accessibility Scanner installed.
- Have a clean profile.
### Steps to reproduce
1. Open app and tap on "Menu"/"Settings"/"Search".
2. Scan the "Search" module.
### Expected behavior
No suggestions are made.
### Actual behavior
Suggestion is to increase the item's size from 32dp x 32dp to 48dp x 48dp or larger.
**Touch target**
org.mozilla.fenix:id/radio_button
This item's size is 32dp x 32dp. Consider making this touch target 48dp wide and 48dp high or larger. A parent container may be handling touch events for this item. If selecting the larger container performs the same action as selecting this item, consider defining this item as not clickable. If a different action is performed, consider increasing the size of this item.
### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version: Nightly 9/4

<details closed><summary>Screen</summary>

![Screenshot_20200904-154533](https://user-images.githubusercontent.com/49859863/92240406-431a8180-eec5-11ea-8da1-688cf66def9f.png)
</details>

**Comment by codrut-topliceanu** [comment]
@Diana-Rus Indeed, the radio button is set to wrap_content but, the whole row is set to 48dp (height). Clicking on the row checks the radio button. 
Should I still go ahead and make the requested changes anyway?

**Comment by Diana-Rus** [comment]
Hi, thanks for pointing it out, yes with talk back the entire row will activate a search engine, if it does not affect anything else, sure.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/16 with Samsung Galaxy Note 10 (Android 10).
