### ISSUE TITLE
[Bug][a11y] The close button, "X" for Download notification needs resizing

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14726]
## Prerequisites
- Have Google Accessibility Scanner installed.
- Have a clean Firefox profile.
### Steps to reproduce
1. Open app and navigate to thinkbroadband.com/download
2. Choose to download a file and wait until download prompt is displayed.
3. Scan the screen.
### Expected behavior
There are no suggestions to make any changes.
### Actual behavior
**Touch target**
org.mozilla.fenix:id/close_button
This item's size is 24dp x 24dp. Consider making this touch target 48dp wide and 48dp high or larger.
### Device information

* Android device: Google Pixel 3XL (A9)
* Fenix version: Nightly 9/4

<details closed><summary></summary>

![screenshot_Firefox Nightly_org mozilla fenix_id-close_button_17179869186_2020-09-04-16_13_06](https://user-images.githubusercontent.com/49859863/92243358-0dc46280-eeca-11ea-9c6b-5885feae8087.png)
</details>

Note: issue similar to #7754

**Comment by codrut-topliceanu** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/pull/8351

**Comment by sflorean** [comment]
Verified as fixed on Nightly 17/11 with Pixel 3 (Android 11) and LG G7 FIT (Android 8), no suggestions are made to increase the size dot "X" button.
