### ISSUE TITLE
Change bookmark icon fill color

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#14728]
### What is the user problem or growth opportunity you want to see solved?
If you visit any bookmarked site the fill color in the bookmark icon is black this makes it difficult to distinguish for other menu items.. In other words the icon must stand unique... The desktop version of Firefox has blue color filled in the bookmark icon for visited sites... Can you please change the color to blue similar to desktop version? 

### How do you know that this problem exists today? Why is this important?
Because of the black color it is not possible to distinguish... 

### Who will benefit from it?
All

![Screenshot_20200904-193138451 (1)](https://user-images.githubusercontent.com/58127841/92248184-e8dde880-eee5-11ea-9311-bfcdf6fa69fb.jpg)

**Comment by topotropic** [comment]
Thanks for the feedback! This design will change in the near future, see https://github.com/mozilla-mobile/fenix/issues/17797.
