### ISSUE TITLE
Show most visited sites doesn't work [Bug]

### ISSUE THREAD

**Issue by mrninko** [mozilla-mobile/fenix#14724]
## Steps to reproduce
I have checked in settings "Show most visited sites" but landing page of Firefox is still empty

### Expected behavior
Show most most visited sites 

### Actual behavior
Empty list of most visited sites

### Device information
Xiaomi Mi 9 Lite, Android 10

* Android device: Xiaomi Mi 9 Lite, Android 10
* Fenix version: Firefox Beta 81.1.0-beta.2

![sketch-1599222281145](https://user-images.githubusercontent.com/70480264/92239202-e4e8a100-eeba-11ea-8367-d0dbf44c96cb.png)

**Comment by cadeyrn** [comment]
> Empty list of most visited sites

Your screenshot tells a different story…

**Comment by mrninko** [comment]
> 
> 
> > Empty list of most visited sites
> 
> Your screenshot tells a different story…

Those pages are all pinned/top sites (see below)
![sketch-1599222803737](https://user-images.githubusercontent.com/70480264/92239673-b1f2dd00-eebb-11ea-9543-c7d3d0da0f55.png)

**Comment by cadeyrn** [comment]
The feature is limited to 16 sites. If you have 16 pinned sites, then you're right, you won't see your most visited sites and the description of the setting is misleading. It's not really a _bug_ because it works as it's implemented. But maybe it's an use case for Mozilla to consider. Maybe also related to the discussion in #8312 about the top sites limit.

**Comment by mrninko** [comment]
> 
> 
> The feature is limited to 16 sites. If you have 16 pinned sites, then you're right, you won't see your most visited sites and the description of the setting is misleading. It's not really a _bug_ because it works as it's implemented. But maybe it's an use case for Mozilla to consider. Maybe also related to the discussion in #8312 about the top sites limit.

ok, but I have pinned just 14. two are still available...

**Comment by TrianguloY** [comment]
Found the bug (I think) and made a pull request.

Basically the code gets an incorrect amount of possible frequent sites (4 in this case) and then removes duplicates, which mean that in your case the 4 most frequent sites are pinned.
