### ISSUE TITLE
"TRACKER" name of opened cards[Bug]

### ISSUE THREAD

**Issue by mrninko** [mozilla-mobile/fenix#14721]
## Steps to reproduce
Happens only on some pages - open new page from leaded page by long press and select "open link in new tab"

### Expected behavior
Name of opened page

### Actual behavior
The name of opened page is "Tracker"

### Device information
Xiaomi Mi 9 Lite, Android 10 

* Android device: Xiaomi Mi 9 Lite, Android 10 
* Fenix version: Firefox Beta 81.1.0-beta.2

![sketch-1599220859804](https://user-images.githubusercontent.com/70480264/92237798-43f8e680-eeb8-11ea-8e10-d874ad4cd0ae.png)

**Comment by hwinnemoe** [comment]
Likely related to https://github.com/mozilla-mobile/android-components/issues/8315

**Comment by liuche** [comment]
Are you still seeing this?

**Comment by mrninko** [comment]
> Are you still seeing this?
 
So far so good (after latest update)
