### ISSUE TITLE
[Bug] em tag in settings for albanese

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#14720]
## Steps to reproduce
1. Change language to albanese (first in the list)
2. Go to accessibility settings

### Expected behavior

No `<em>` tag. The text should not be bold too, because it's not in English / other locales.

### Actual behavior
`<em>Zoom</em>`
<img src="https://i.ibb.co/bKjwBHH/Screenshot-20200904-140531-Firefox-Nightly.png" width="300">
### Device information

* Android device: Pocophone F1, android 9
* Fenix version: nightly 200904

### Additional note

You should also check other languages to see if it doesn't happen

**Comment by mcarare** [comment]
This will be fixed in Pontoon. 
@Delphine  I made a suggestion, but do not have rights to approve them.
https://pontoon.mozilla.org/sq/android-l10n/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=preference_accessibility_force_enable_zoom&string=205610

**Comment by Delphine** [comment]
Fixed! thanks for flagging
