### ISSUE TITLE
[Bug][a11y] Re-sync tabs button is read as unlabeled 

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#14727]
## Prerequisites:
- Secret settings enabled with sync option in tabs tray active
- Be connected with an fx-account on mobile and desktop
- Have talk back enabled
## Steps to reproduce
1. Open browser and tap on tabs tray counter.
2. View the synced tabs in normal tab.
3. Tap on the re-sync/sync now button.
### Expected behavior
The label for the button is read correctly.
### Actual behavior
It is read "unlabeled" button.
### Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version: Nightly 9/6

**Comment by mcarare** [comment]
@betsymi Should the content description read "Refresh" or "Resync" ? Or other option, the shorter the better. Thank you!

**Comment by betsymi** [comment]
> @betsymi Should the content description read "Refresh" or "Resync" ? Or other option, the shorter the better. Thank you!

May I see a screenshot of what this looks like? I'm having trouble envisioning it and don't think I have the appropriate settings to recreate. I got stuck here, which feels like a dead end. Can we offer a path to tun on tab syncing? 
![Screenshot_20200908-092812](https://user-images.githubusercontent.com/43555492/92489792-caae0c00-f1b5-11ea-9118-0b1b24de535e.png)

**Comment by Diana-Rus** [comment]
Hi @betsymi you need to go firstly on Nightly, in Secret settings (need to activate developer mode on Nightly) and enable Show Synced tabs in the tabs tray.
Than go in tabs tray - normal browsing
It should look like this
<details closed> <summary></summary>

![Screenshot_20200904-134304](https://user-images.githubusercontent.com/49859863/92490553-d7545380-f1f9-11ea-8df1-ea6ad24dd158.png)

![Screenshot_20200904-134252](https://user-images.githubusercontent.com/49859863/92490497-c7d50a80-f1f9-11ea-829d-f4bde7f7642b.png)
</details>

**Comment by mcarare** [comment]
@betsymi https://app.abstract.com/share/0bae23a7-b55b-43f9-a57a-1fdb7b3596fc?mode=build&sha=a813facef071a6c43e3d40d20afa4aaf4f75e269.

Screenshot of implementation:

![out](https://user-images.githubusercontent.com/1370580/90475971-8ff50e80-e0f6-11ea-953f-3ef0849169ec.png)

**Comment by mcarare** [comment]
@betsymi Any feedback on this? Thank you!

**Comment by betsymi** [comment]
Let's go with Resync for the text label.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_1screenshot_20200921-120526](https://user-images.githubusercontent.com/51314259/93749778-2be8cd00-fc03-11ea-914a-7ffe50e30121.png)
