### ISSUE TITLE
All pinned pages on landing page (without horizontal scrolling)

### ISSUE THREAD

**Issue by mrninko** [mozilla-mobile/fenix#14722]
### What is the user problem or growth opportunity you want to see solved?
The number of pinned pages is reduced to 8. If there're more, you have to use horizontal scroller. It's hard to keep track of the pinned pages I open the most.

### How do you know that this problem exists today? Why is this important?
Before Firefox Beta 81.1.0-beta.2 it was possible, now not.

### Who will benefit from it?
I guess everyone who uses pinned pages - gain easier access to pages

**Comment by mrninko** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/8312

This feature is just terrible - not suitable for one-handed operation, I dont have "all I use" on one page (scrolling is just like another page)

**Comment by mrninko** [comment]
Also missing feature: drag and order to order them by my taste...

**Comment by liuche** [comment]
We've limited this number of pinned sites in #8312 as you linked.
