### ISSUE TITLE
Download manager - just list of downloaded files

### ISSUE THREAD

**Issue by mrninko** [mozilla-mobile/fenix#14723]
### What is the user problem or growth opportunity you want to see solved?
Current download manager is not download manager but just list of downloaded files. I'm not able to delete specific file from manager, not able to remove specific file name form list (or all of them) - just cleare list without deleting, not able managing ongoing downloads

### How do you know that this problem exists today? Why is this important?
Because I used old version of Firefox for Android and also use Firefox for Windows...

### Who will benefit from it?
Everyone

**Comment by cadeyrn** [comment]
> I'm not able to delete specific file from manager

This is #352.
