### ISSUE TITLE
Revive "Add to Firefox" in share menu

### ISSUE THREAD

**Issue by cole-h** [mozilla-mobile/fenix#14738]
EDIT: This is a feature request -- I don't know why GitHub didn't label it as such, even after selecting the template...

### What is the user problem or growth opportunity you want to see solved?

In pre-Fenix Firefox Mobile, there was the ability to share to "Add to Firefox", which would give a user three choices (if they had linked devices): bookmark the link, open the link in the full browser, or send the link to another device. In Fenix, this feature no longer exists, which prolongs the time spent doing anything but what I wanted to do when I want to send something to my desktop for later viewing.

### How do you know that this problem exists today? Why is this important?

This feature is important to me because it eases multitasking. When I'm browsing Reddit or YouTube on my phone, if I see something interesting, I can save it for later by sending it to my desktop through that share option. However, with the new Fenix browser, I have to open it in Firefox, wait for the browser to load, tap the overflow menu, tap the share button, and *then* I can send it to my desktop.

### Who will benefit from it?

Everyone. It'll be one more tap to open immediately in the browser (if done through the share menu), but it'll be 3-4 less steps (and a whole lot less time wasted).

(Disclaimer: I tried searching if this was a duplicate, but we all know how GitHub's search is... I didn't find anything, but that doesn't mean it doesn't exist. Feel free to point me to an existing issue I can rally behind.)

**Comment by amkcpu** [comment]
This is essentially #1523.

**Comment by cole-h** [comment]
Looks like it, thank you. I've subscribed to that issue.

**Comment by godfuture** [comment]
> This is essentially #1523.

Its kinda weird that such a native Android experience was removed, and now does not get any prio. :(
