### ISSUE TITLE
Show image thumbnails for downloads view

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14732]
### What is the user problem or growth opportunity you want to see solved?
A lot of images downloaded from the internet do not have any sort of descriptive name so it is difficult for users to recognise which image they want to open. It would be great if fenix provided a preview of the image files in the downloads view.

### How do you know that this problem exists today? Why is this important?
This is a feature seen in many other browsers. So users might have an expectation from firefox to show previews as well. 

### Who will benefit from it?
Users who frequently download images

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6358)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812805

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
