### ISSUE TITLE
[Bug] TalkBack selection misplaced after page zoom

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#1474]
## Steps to reproduce
Enable TalkBack
Load a webpage
Swipe to select an element on the page
Pinch to zoom the page in 

### Expected behavior
The TalkBack focus rectangle should stay on the originally selected element

### Actual behavior
The TalkBack focus rectangle moves to some random place on the page

### Device information
* Android device: ? Samsung Galaxy S6
* Fenix version: ? 2019-04-03

**Comment by asadotzler** [comment]
I'll file a bugzilla bug for the geckovierw issue and this can be for tracking

**Comment by mcarare** [comment]
@asadotzler Do you have a link for the bugzilla issue?
Note: same weird behaviour when you scroll through the page after selecting an element.

**Comment by vesta0** [comment]
This is an edge case, will revisit later.

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639092
