### ISSUE TITLE
Keep address bar always visible?

### ISSUE THREAD

**Issue by talz13** [mozilla-mobile/fenix#14742]
I believe there used to be an option to either disable fullscreen or to pin the address bar so it wouldn't slide off the top of the screen while scrolling.

This feature does not appear to be available in the new Firefox for Android.

I find it very bothersome when trying to scroll a little bit, only to have the page rubberband back because I didn't scroll far enough to either completely hide or completely reveal the address bar.

Please consider bringing this option back to the new Firefox.

Thanks!

**Comment by s-ankur** [comment]
Hi, this is a highly requested feature. See  #10240 (I know, the title is a bit confusing there 😅). You can click on 👍 there to show your support

**Comment by Poopooracoocoo** [comment]
lol it's grammatically incorrect. it should say "allow users _to disable_ gesture based features"

**Comment by mcarare** [comment]
Closing as duplicate. The request is included in #10240. Thank you for your report!
