### ISSUE TITLE
[Bug] No undo/restore tab when removed from collection

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14749]
Have seen this noted:
https://github.com/mozilla-mobile/fenix/issues/6538#issuecomment-607566713 
https://github.com/mozilla-mobile/fenix/issues/13177 
https://www.reddit.com/r/firefox/comments/imoh81/still_having_problems_adopting_to_the_new_start/

## Steps to reproduce

1. Create collection
2. Swipe/tap x on tab on home

### Expected behavior

* undo snackbar
* undo close/restore option in collections meatball menun

### Actual behavior

tab is irrevocably deleted

**Comment by Diana-Rus** [comment]
Hello @yoasif  this issue has been already discovered, please check #2725 and follow the progress there.
Closing this as it is a duplicate.
