### ISSUE TITLE
Can't choose file to upload after the big upgrade

### ISSUE THREAD

**Issue by 10110111** [mozilla-mobile/fenix#14748]
## Steps to reproduce

1. Go to https://yandex.ru/images.
2. After it loads, tap the camera icon on the side of the search entry field:
![Screenshot_20200905-001348_Firefox](https://user-images.githubusercontent.com/6376882/92285968-5dc51880-ef0e-11ea-8489-9faa544ad9c7.jpg)
### Expected behavior
Firefox should try accessing the camera (as the old version before "big upgrade" did), fail due to lacking permissions (I forbid FF access to camera), and open file choice UI, so that I could upload an image file.
### Actual behavior
Nothing happens. At all. Not an error message, nothing. As if I didn't tap.
### Device information

* Android device: Samsung Galaxy A320F/DS, Android 8.0.0
* Fenix version: The _About_ tab says "Firefox Daylight", version is listed as 80.1.2. By "big upgrade" mentioned above I mean the one that moved address bar from the screen top to the bottom.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6388)

**Comment by kennethtran93** [comment]
> By "big upgrade" mentioned above I mean the one that moved address bar from the screen top to the bottom.

You can change whether or not you want the bar to be on the top or bottom via 'customize'

**Comment by 10110111** [comment]
> You can change whether or not you want the bar to be on the top or bottom via 'customize'

Yeah I've already found this option. I just wanted to point to the fact that the problem appeared after this default was changed by an upgrade.

**Comment by liuche** [comment]
This is similar to #14239, we should prompt again explaining why this isn't working (because the user blocked the permission).

**Comment by amedyne** [comment]
@10110111 Is this still an issue for you?

**Comment by 10110111** [comment]
It certainly is. There's been no visible progress since I reported this issue. Neither an error message, nor a friendly switch to browsing the filesystem that used to work until the upgrade.

I'm forced to downgrade to Firefox 68 to get a working browser.

**Comment by amedyne** [comment]
Thank you for checking @10110111. This seems to be working for me on Firefox Nightly. 
Do we have the same steps and set-up? 

Settings->Site Permission-> Camera: Blocked

Go to https://yandex.ru/images.
After it loads, tap the camera icon on the side of the search entry field
Result:

I get the following:
![screenshot_20201211-165007](https://user-images.githubusercontent.com/68711330/101958375-2f23a180-3bd1-11eb-9811-de9b691b5e2b.png)

And when I click on Allow while using app, I get the option to select camera or File.

**Comment by 10110111** [comment]
My action for Image Capture permission is "Deny and never ask again". With this choice I expect Firefox to let me browse the filesystem and upload a file. The permission to access files is granted.

**Comment by abodea** [comment]
Thank you for this report @10110111!
Note that I was able to reproduce this issue:
 - Access `yandes.ru/images`
 - Tap on the `camera` icon
 - The `Allow Firefox Nightly to take pictures and record videos?` prompt is displayed with 3 options: While using the app, Only this time, and Deny.
 - On the prompt mentioned above tap on the `Deny` 
 - A new prompt is displayed `Allow Firefox Nightly to access photos, media, and files on your device?` with 2 options `Allow` and `Deny`
 - Tap on `Allow` 
 - Tap again on the camera icon and the `Allow Firefox Nightly to take pictures and record videos?` prompt is displayed with 3 options: While using the app, Only this time, and Deny is displayed again.
 - Tap `Deny` again 

Expected: After denying the first prompt and allowing the second with the access media storage, it should let the user to browse and upload files from the device. 

@10110111 is this your issue? 
@Amejia481 removing the `eng:qa::needeed` until further notice.
![ezgif-7-f3482563b2cd](https://user-images.githubusercontent.com/42831109/102083124-bcf2cd00-3e1b-11eb-9ec8-341f78e6b43a.gif)

**Comment by Amejia481** [comment]
Thanks @abodea! I changed the priority to `s3` as the issue is happening only on https://yandex.ru/images, feel free to change otherwise :)

**Comment by 10110111** [comment]
@abodea

> is this your issue?

Yes, exactly.

**Comment by 10110111** [comment]
> It will be closed if no further activity occurs

So what does it mean? That I should occasionally write a useless comment just to bump this issue to keep it alive until it's fixed? This approach doesn't make any sense, especially for S3-priority issues that _will_ need time to have the developers get to them.

**Comment by rayanHappy** [comment]
So I have looked into this, i don't think this issue is only limited to https://yandex.ru/images, if there is a website that asks for more than one permission e.g. [imgbb.com](https://imgbb.com) and the user denied one of them nothing would happen.

The code [here](https://github.com/mozilla-mobile/android-components/blob/a1ad8a208eb8545c4851f6cf57def485221ea75e/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt#L151) will check if all permissions are granted and if one of them is denied, onPermissionsDenied() will be called.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809280

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
