### ISSUE TITLE
[Bug] "Fill link from clipboard" disappears on toggling search engines on

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#14744]
## Steps to reproduce
Tap on address bar.
### Expected behavior
You can see the clipboard suggestion regardless of search engines being toggled on or off.
### Actual behavior
You can only see it if you toggle off search engines. Tapping on the search engine toggle will switch between showing the clipboard suggestion and search engines.
### Device information

* Fenix version: Nightly 200904 06:01 (Build #2015761907)

![Screenshot_20200910-115745](https://user-images.githubusercontent.com/1082253/92786334-01725680-f35d-11ea-9920-cac4b275bd55.png)

**Comment by opusforlife2** [comment]
I forgot to mention: This problem was introduced with the new search experience. Before that it worked fine.

**Comment by mcarare** [comment]
From the code, this seems to be an intended change,  "fill link from clipboard "visibility depends on `               !searchState.showSearchShortcuts`. @boek, do you have any more context why this was needed? TY!

**Comment by boek** [comment]
@mcarare hmm, no! I think I just thought that was the behavior of the old screen. We should revert it back to how the old search fragment worked

**Comment by abodea** [comment]
Verified as fixed on the **Nightly 10/20** with **Google Pixel 4 XL (11).**
