### ISSUE TITLE
[Bug] Suggestions still happening even though every option is turned off

### ISSUE THREAD

**Issue by TheEvilSkeleton** [mozilla-mobile/fenix#14740]
## Steps to reproduce

Turn off everything under "Address bar"

Write a letter, and it will still autocomplete

### Expected behavior

It shouldn't autocomplete

### Actual behavior

It autocompletes, even though there's nothing in my history

### Device information

* Android device: Lenovo P2
* Fenix version: https://github.com/mozilla-mobile/fenix/releases/tag/v79.0.5

## Screenshots

![Screenshot_20200904-133858_Iceweasel](https://user-images.githubusercontent.com/50847364/92270545-c6dc6a00-eed5-11ea-9e95-0dfd1550497c.png)
![Screenshot_20200904-133937_Iceweasel](https://user-images.githubusercontent.com/50847364/92270551-c9d75a80-eed5-11ea-89b9-04ca5f2e4a7b.png)

**Comment by s-ankur** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/5745. Yes this is really annoying. Please 👍 that issue to indicate your support

**Comment by TheEvilSkeleton** [comment]
Done. Should this issue be closed? I personally think it should be kept opened because I think that Mozilla forgot about it

**Comment by TheEvilSkeleton** [comment]
Thank you
