### ISSUE TITLE
[Bug] When opened through PB shortcut, old search experience is shown

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#14743]
## Steps to reproduce
Open the Private Browsing shortcut.
### Expected behavior
New search experience is seen.
### Actual behavior
Old search experience is seen.
### Device information

* Fenix version: Nightly 200904 06:01 (Build #2015761907)

**Comment by s-ankur** [comment]
#14280 would probably include this right?

**Comment by kbrosnan** [comment]
Seems different enough to keep this open.

**Comment by eliserichards** [comment]
For QA: this is all behind the scenes changes, so just test out search from Private browsing mode and see if you notice any breaks :)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200925 06:01 GV 83.0a1 from 9/25 with Pixel 2 (Android 9).
I will close this issue and remove the qa:needed.
