### ISSUE TITLE
[Bug] go back button on safebrowsing warning page does not work if URL is copy pasted

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14741]
## Steps to reproduce
Copy paste a safebrowsing url into the tool bar on new tab https://testsafebrowsing.appspot.com/s/phishing.html
Click go back
### Expected behavior
Unclear, maybe  close the tab
### Actual behavior
Nothing
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by amedyne** [comment]
@s-ankur Can you still reproduce this?

**Comment by s-ankur** [comment]
I can no longer see the go back button in this case, so I guess its solved
