### ISSUE TITLE
[Bug] Flicker when swiping to switch tabs

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#14755]
## Steps to reproduce
1. Use swipe to switch tabs gesture without scrolling either tab (so the thumbnail matches the real page).

### Expected behavior
No flicker, smooth fade out of the tab preview.

### Actual behavior
Flicker as the next tab is loaded. See https://www.reddit.com/r/firefox/comments/imip2z for an example video.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by person808** [comment]
I've run into this occasionally. Is GeckoView not finished painting the tab being switched to before the tab preview fade out finishes? I wonder if this happens more frequently on low end devices. Quick fix might be just increasing the fade out time, but knowing when the tab is done painting and hiding the tab preview when it is would be better (assuming my guess is right).

**Comment by amedyne** [comment]
@person808 Can you check on the latest Nightly? This seems to be no longer reproducible.

**Comment by person808** [comment]
Not seeing it anymore!
