### ISSUE TITLE
[Bug] Firefox on Android Did Not Autofill My HTTP Digest Authentication Password Anymore

### ISSUE THREAD

**Issue by imacat** [mozilla-mobile/fenix#14756]
## Steps to reproduce
Navigate to websites with HTTP Digest Authentication.

### Expected behavior
Remember and fill in my password.

### Actual behavior
Does not fill in my password anymore.

### Device information

* Android device: Samsung Galaxy S8+ (SM-G955FD) and Samsung Galaxy Tab S4 (SM-T830)
* Fenix version: Firefox Daylight 80.1.2 (Build#2015761283)

**Comment by JLJTGR** [comment]
Related to #13941.  (Not a duplicate)
Duplicate of #13961; unfortunately it was closed for what I feel was the wrong reason.

**Comment by RES-1** [comment]
The same here.

**Comment by madtibo** [comment]
This regression makes firefox on android very difficult to use for my daily job usage!

**Comment by RES-1** [comment]
Here is your ACTIVITY.

**Comment by JLJTGR** [comment]
Ugh, well it is still very much "broken" on even Nightly builds(91.0a1).  I have to manually enter login credentials for 401 auth challenges on Android.

**Comment by sebhans** [comment]
It is not fixed and still annoys me every day.

**Comment by wentasah** [comment]
For me, it started working few weeks ago. Digest auth passwords are now offered automatically. I'm now on 94.1.2.

**Comment by sebhans** [comment]
Huh, it seems my device was behind on updates. It works now. Hooray! :rocket:

I guess this ticket not being updated is one of the symptoms of the growing backlog.

**Comment by JLJTGR** [comment]
I'm happy to see that it does auto-fill auth challenge passwords.  It also appears to ask if you wish to save the password.  It seems like this issue is completely fixed.

**Comment by madtibo** [comment]
It seems to be fixed in 94.1.2.

I am closing the issue.

**Comment by imacat** [comment]
Sorry I forgot about this.  It is fixed now.
