### ISSUE TITLE
[Bug] PWA does not load content if main app window is not in memory

### ISSUE THREAD

**Issue by diabolic-preacher** [mozilla-mobile/fenix#14759]
### Steps to reproduce
1. Kill off firefox nightly by using Force Stop option in Android. Usually android itself will kill off apps in background for battery optimization etc.
2. Launch a Progressive Web App shortcut from the home screen.

### Expected behavior
The PWA should load the web content of the page it is created from

### Actual behavior
Just an empty white full screen app opens.

### Workaround
1. Close the PWA
2. Open the main browser app window
3. Open the PWA
The content loads now

### Device information

* Android device: Android Q running on Huawei Mate 20 Pro (Model: LYA-L29)
* Fenix version: Nightly 200706 06:01 (Build #2015750387)
installed and updated from Play Store

**Comment by hwinnemoe** [comment]
Likely duplicate of #14095

**Comment by diabolic-preacher** [comment]
> Likely duplicate of #14095
if that bug is tracking the issue on nightly builds as well then this issue can be closed as duplicate, reporter didn't see this issue on nightly but it looks like someone else did.

**Comment by hwinnemoe** [comment]
It was reproduced in Nightly, yes. In addition, your Nightly version looks really old, can you please follow-up on that?

**Comment by diabolic-preacher** [comment]
> It was reproduced in Nightly, yes. In addition, your Nightly version looks really old, can you please follow-up on that?

I noticed that the version I installed is an Early Access version of Firefox Nightly for Developers. I think I went with it because at the time it was the only one that seemed newer. I think I would have confused between the various versions. I see a "Firefox Nightly" updated on 4th September, 2020. I'll try with that

**Comment by diabolic-preacher** [comment]
![Screenshot_20200906_112558](https://user-images.githubusercontent.com/67977107/92319417-8a278480-f035-11ea-8aeb-6c5be8684c5e.jpg)
![Screenshot_20200906_111855_org mozilla fenix](https://user-images.githubusercontent.com/67977107/92319418-8bf14800-f035-11ea-9971-d734556b4077.jpg)

First, the bug does not occur in the newer Firefox Nightly that I downloaded now. The reason I am showing the About pages is to highlight that both say "About Firefox Nightly" even though the older one is "For Developers (Early Access)" Apart from the slightly different icons of rather their backgrounds, even the app name in Settings > Apps are the same.

The big still occurs in the version I was using before and usually previously Firefox used to show a message that this version will not get any more updates, use xyz which would be the one that is currently getting developed even if it was a newer Nightly for Developers. I think it is normal to not hunt for a "different" Nightly app on play store by getting cm epiphany that that will be newer even though it will be called the same.
Closing this and will add my comment on the other bug

**Comment by hwinnemoe** [comment]
Firefox Nightly was moved to https://play.google.com/store/apps/details?id=org.mozilla.fenix on 2020-07-02 (see https://github.com/mozilla-mobile/fenix/issues/12207#issuecomment-653329878). Your Nightly version _should_ have gotten an in-app message that looked this https://user-images.githubusercontent.com/42831109/81049344-b3d57100-8ec6-11ea-94e7-757df219e23f.png.

**Comment by diabolic-preacher** [comment]
> Firefox Nightly was moved to https://play.google.com/store/apps/details?id=org.mozilla.fenix on 2020-07-02 (see [#12207 (comment)](https://github.com/mozilla-mobile/fenix/issues/12207#issuecomment-653329878)). Your Nightly version _should_ have gotten an in-app message that looked this https://user-images.githubusercontent.com/42831109/81049344-b3d57100-8ec6-11ea-94e7-757df219e23f.png.
Exactly this one! I had got it for the "Nightly" I had before the one I reported this issue with. Having seen such a message I was sure that such a notification would tell me when the updates would stop coming. It was just a wrong idea to get the "for Developers" nightly even though it was and still is marked as "Early Access" in Play Store.
