### ISSUE TITLE
does't autofill uname & pword

### ISSUE THREAD

**Issue by xpseudonym** [mozilla-mobile/fenix#14751]
uname & pword doesnt autofil for:
https://beta.protonmail.com/login

**Comment by s-ankur** [comment]
This is working for me in the nightly version. What version are you using? @xpseudonym

**Comment by xpseudonym** [comment]
Deffo doesn't auto-fill

Version etc:
80.1.3 (Build #2015762835)
AC: 54.0.6, cfc360e05
GV: 80.0.2-20200903001900
AS: 61.0.10
Wednesday 9/9 @ 2:22 AM11

**Comment by liuche** [comment]
Do you have multiple usernames for that page? We just added the ability to select from multiple logins in 81, which should be out next week, and manifested as "not autofilling".

**Comment by xpseudonym** [comment]
Yes, I have two logins for that page - shall I wait and see...?

**Comment by ekager** [comment]
@xpseudonym in the next update next week you will be able to select from multiple logins. If you want to verify this is true, you can download Beta or Nightly and sign into FxA there
I'm going to close this because it is has been fixed. Thanks!
