### ISSUE TITLE
Reinstate Ability to View Source

### ISSUE THREAD

**Issue by userX-324-A** [mozilla-mobile/fenix#14758]
The current version of FF Android removed the ability to view page source. Please add it back. Seeing the underlying source is invaluable when troubleshooting, debugging, and automating.

**Comment by RachitKeertiDas** [comment]
Possible duplicate of #3972.

**Comment by s-ankur** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/3710

**Comment by svein83** [comment]
The removal of this functionality made the browser a toy for consumers instead of a tool for developers...
