### ISSUE TITLE
[Bug] Decimal point missing on virtual keboard can't enter non integer

### ISSUE THREAD

**Issue by Vachha** [mozilla-mobile/fenix#14757]
## Steps to reproduce
Try to enter a non integer into a number field. Also affects Firefox focus.

Sample html code to reproduce:
`<input` type="number" step=".05" name="Duration" Value="1" required >`

### Expected behavior
Virtual keyboard pop-up **with** decimal point

### Actual behavior
Virtual keyboard pop-up **without** decimal point

### Device information
* Android device: LG V40 Android V9
* Fenix version: Firefox Browser V80.12  Build #2015761283

**Comment by makotokato** [comment]
@Vachha 
What software keyboard/IME do you use? GBoard?

**Comment by Vachha** [comment]
> @Vachha
> What software keyboard/IME do you use? GBoard?

Thanks for looking at this.

I'm using the standard LG keyboard. FWIW it worked with older versions of Firefox and Focus. It still works with Chrome. I don't have GBoard installed.
![Screenshot_20200824-115829](https://user-images.githubusercontent.com/15673029/92570864-fcf26300-f2b4-11ea-9701-284f8f19683a.png)

**Comment by makotokato** [comment]
Thanks.  I see, we may have to add `TYPE_NUMBER_FLAG_DECIMAL`. I filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1663884

**Comment by kbrosnan** [comment]
Since the work is happening in Bugzilla going to close this issue in favor of that one.
