### ISSUE TITLE
Customize Toolbar

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14750]
### What is the user problem or growth opportunity you want to see solved?

Users may want to customize their toolbar to optimize [reachability](https://www.reddit.com/r/firefox/comments/imm378/left_handed_people_how_on_earth_do_you_use/), or simply [preference](https://github.com/mozilla-mobile/fenix/issues/14705). 

### How do you know that this problem exists today? Why is this important?

There is no way for users to move the menu to the left side, making browsers like Samsung Internet more attractive for left handed users (Samsung Internet includes toolbar customization). Toolbar customization can also help users make Fenix fit their needs better, like [allowing them to add a new tab button to their toolbar](https://github.com/mozilla-mobile/fenix/issues/11298). 

### Who will benefit from it?

People who are a bit more advanced or who fall a little outside of the common user (most users may be right handed, but left handed users deserve options as well!). I think [tablet](https://github.com/mozilla-mobile/fenix/issues/4498) users would also see great benefits here, as that is a more desktop-like system, where toolbar customization is even more expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6393)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813948

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
