### ISSUE TITLE
"Copy link" for non-http url image link

### ISSUE THREAD

**Issue by ffftwo** [mozilla-mobile/fenix#14761]
I'm currently using 80.1.2 from play store, please please please bring that feature back

![Screenshot_20200905_151349](https://user-images.githubusercontent.com/1555426/92300056-72df8d00-ef8a-11ea-8327-c146cada05d2.png)

**Comment by clientenq** [comment]
Any URI should fit this copy link feature.
Current status is P3 and open for almost a year.
[Bug] Unable to copy magnet links #6149

**Comment by evilpie** [comment]
Duplicate and fixed in Nightly.
