### ISSUE TITLE
[Crash] Nightly keeps crashing when scrolling on any page

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#14763]
## Steps to reproduce
1. Open any page on Nightly.
2. Scroll rapidly down.

### Expected behavior
Fenix doesn't crash.

### Actual behavior
Page first briefly freezes, then the entire browser crashes.

### Device information
* Android device: Fairphone 3
* Android version: 9

Nightly version information where this first appeared (before, I never had issues in that regard):
* Nightly 200903 06:04 (Build #2015761715)
* AC: 58.0.20200901190136, 478151899
* GV: 82.0a1-20200831091558
* AS: 61.0.13
* Thursday 9/3 @ 6:10 AM

I tried waiting a bit, but this keeps happening two days later:
* Nightly 200905 06:01 (Build #2015762099)
* AC: 58.0.20200904130229, b6c304b2a
* GV: 82.0a1-20200902095359
* AS: 61.0.13
* Saturday 9/5 @ 6:09 AM

I already tried deleting the cache, the browser data and also uninstalled and reinstalled Nightly. Nothing helped.
I don't have any add-ons installed and basically use all default settings.
To me, this seems like a GeckoView problem, because I can navigate all other Fenix menus without a problem. This only happens when scrolling on websites.

**Comment by hwinnemoe** [comment]
Can you please include your crashreports here, if you can access them?

**Comment by amkcpu** [comment]
@hwinnemoe 
>  open about:support and look for main topic Graphics, subtopic Features, what is says next to Compositing.

It says WebRender.

**Comment by amkcpu** [comment]
Soccorro report: https://crash-stats.mozilla.org/report/index/8dfa1b7c-5ca0-4496-a870-ff8810200905

**Comment by hwinnemoe** [comment]
Seems to be a duplicate of https://github.com/mozilla-mobile/fenix/issues/14624. Still, I'm puzzled that your device has active WR, did you activate this yourself?

**Comment by amkcpu** [comment]
>  I'm puzzled that your device has active WR, did you activate this yourself?

No, I didn't. No idea why this is on.

**Comment by hwinnemoe** [comment]
Just to double-check, what does it say next to _WebGL 1 Driver Renderer_? Thats a little bit further down in the same session on `about:support`

**Comment by amkcpu** [comment]
It says "Qualcomm -- Adreno (TM) 506".

**Comment by hwinnemoe** [comment]
Your crash _should_ be unrelated to having WR (WebRender) active, it is not specific to devices with active WR, so you can follow https://github.com/mozilla-mobile/fenix/issues/14624 for a fix.

Regarding WR, can you please look take a look into `about:config` and look up the current setting for
- gfx.webrender.all
- gfx.webrender.enabled
- gfx.webrender.force-disabled

Furthermore, please tell me what is says on `about:support` next to **Graphics**, **Decision Log**, _WEBRENDER_

**Comment by amkcpu** [comment]
Settings in `about:config`:
- gfx.webrender.all: false
- gfx.webrender.enabled: false
- gfx.webrender.force-disabled: false

> what is says on about:support next to Graphics, Decision Log, WEBRENDER and WEBRENDER_QUALIFIED

- `WEBRENDER`: "opt-in by default: WebRender is an opt-in feature. available by user: Qualified enabled by pref"
- `WEBRENDER_QUALIFIED`: available by default

**Comment by hwinnemoe** [comment]
Thanks! I will open a BZ issue for this, WR should not be activated on your device (yet).

**Comment by amkcpu** [comment]
Could you post the link here once you've filed it?
Thanks for following up on this!

**Comment by hwinnemoe** [comment]
If it's not too much of an inconvenience for you, could you just copy&paste the whole decision log from `about:support` here? That way we can be sure that we did not miss something

**Comment by amkcpu** [comment]
**Decision Log:**
HW_COMPOSITING 
available by default
force_enabled by user: Force-enabled by pref
OPENGL_COMPOSITING 
available by default
force_enabled by user: Force-enabled by pref
WEBRENDER 
opt-in by default: WebRender is an opt-in feature
available by user: Qualified enabled by pref
WEBRENDER_QUALIFIED 
available by default
WEBRENDER_COMPOSITOR 
disabled by default: Disabled by default
WEBRENDER_ANGLE 
opt-in by default: WebRender ANGLE is an opt-in feature
WEBRENDER_DCOMP_PRESENT 
opt-in by default: WebRender DirectComposition is an opt-in feature
OMTP 
disabled by default: Disabled by default
WEBGPU 
disabled by default: Disabled by default

**GPU #'1:**
Active: Yes
Description Model: FP3, Product: FP3, Manufacturer: Fairphone, Hardware: qcom, OpenGL: Qualcomm -- Adreno (TM) 506 -- OpenGL ES 3.2 V@331.0 (GIT@4daeac4, I85e9875322) (Date:06/01/19)
Vendor ID: Qualcomm
Device ID: Adreno (TM) 506
Driver Version: OpenGL ES 3.2 V@331.0 (GIT@4daeac4, I85e9875322) (Date:06/01/19)
RAM: 0

**Comment by hwinnemoe** [comment]
So I managed to contact a developer and it's fine for you device to have active WR, at least on Nightly, it is still blocked for WR on Beta and Release. Sorry for the trouble, but now we now for sure! 😅

**Comment by amkcpu** [comment]
Closing this as dupe of #14624.
