### ISSUE TITLE
New tab settings like desktop

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14765]
### What is the user problem or growth opportunity you want to see solved?
users who have used firefox for desktop will wonder where this functionality is. 

### How do you know that this problem exists today? Why is this important?
I don't know. Haven't heard anyone complain about this.

### Who will benefit from it?
firefox for desktop users
new tab users

Firefox for desktop's settings:
![image](https://user-images.githubusercontent.com/51363864/92303701-da153580-efba-11ea-935c-dc565de0b878.png)

![image](https://user-images.githubusercontent.com/51363864/92303625-172cf800-efba-11ea-9527-aad54460685a.png)
(kinda strange that tapping on any of those checkboxes selects them...)

**Comment by s-ankur** [comment]
I think this is https://github.com/mozilla-mobile/fenix/issues/12065 or something similar

**Comment by Poopooracoocoo** [comment]
@s-ankur similar, but not the same. This is about the settings interface
