### ISSUE TITLE
Refine the logic :Fill link from clipboard

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#14760]
### What is the user problem or growth opportunity you want to see solved?
If some text is copied to clipboard and if you click address bar it shows the option fill link from clipboard... In most cases this might not be the link rather a text which user wants to search... So the logic must be if the copied item contain URL scheme like http or https it should show fill link from clipboard else if simple text is there it should show search text in search engine from clipboard 
Please fix this. 

### How do you know that this problem exists today? Why is this important?
Even for simple texts copied to clipboard it shows fill link from clipboard and on clicking it tries to open the text as website which is not true or expected

### Who will benefit from it?
All users 

![Screenshot_20200905-124443088](https://user-images.githubusercontent.com/58127841/92300164-4faae280-ef76-11ea-9476-60b7450fe3db.jpg)

**Comment by s-ankur** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/12993

**Comment by amedyne** [comment]
@sheikh-azharuddin Can you check if this is still a problem for you? Thanks!

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin Can you check if this is still a problem for you? Thanks!

Yes fixed now... Thanks😊👍
