### ISSUE TITLE
[Bug] Scan does not work properly in new search experience

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14767]
## Steps to reproduce
Click on the + button in Tab tray (FAB)
Click on scan, then scan a qr code

### Expected behavior
Keyboard dismissed, site/search opens
### Actual behavior
Keyboard stays, site opened in Background!
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
![image](https://user-images.githubusercontent.com/33252312/92305194-99112700-efa2-11ea-847c-7faac30160f0.png)
QR Code if you need to test it

**Comment by tomyummmm** [comment]
Same issue on previous beta, latest version of 81.1.1-beta4 released on play store seems to have fixed this. Using a Xiaomi K20 Pro

**Comment by liuche** [comment]
I'm not able to repro this on Nightly 9/15 anymore

**Comment by s-ankur** [comment]
Yes, seems to be fixed!

**Comment by s-ankur** [comment]
Should I close this,?

**Comment by sflorean** [comment]
Closing this based on the above comments. Thanks @s-ankur for updates here!
