### ISSUE TITLE
Youtube advance controls in notification

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#14762]
### What is the user problem or growth opportunity you want to see solved?
When a youtube video is opened in edge or chrome the notification message shows advance controls like forward or backward and a seek bar whereas in Firefox it shows only one button even after changing the user agent... Please fix this 

### How do you know that this problem exists today? Why is this important?

A user must be able to control the video playback from notification without going to the browser

### Who will benefit from it?
All users

![Screenshot_20200905-130153170](https://user-images.githubusercontent.com/58127841/92300408-225f3400-ef78-11ea-85cd-b695e062eb77.jpg)
![Screenshot_20200905-130227690](https://user-images.githubusercontent.com/58127841/92300413-2723e800-ef78-11ea-95dd-bde348be9f39.jpg)

**Comment by amkcpu** [comment]
This is #14739 minus the seek bar which isn't mentioned there.

**Comment by Poopooracoocoo** [comment]
> This is #14739 minus the seek bar which isn't mentioned there.

which is also #5290 (which i think is the original issue about mediasession support?)

**Comment by kbrosnan** [comment]
Closing as a duplicate
