### ISSUE TITLE
When I launch a new tab or a search, bookmarks should displayed instead of search engines

### ISSUE THREAD

**Issue by snakedye** [mozilla-mobile/fenix#14766]
### What is the user problem or growth opportunity you want to see solved?
I'm not exactly sure but I suppose people navigate more often to their bookmarked websites than they switch search engine. 

### How do you know that this problem exists today? Why is this important?
Currently in Beta if you want to open a recent bookmarked page, you have to open a new tab or search, quit search and then click on bookmark. With this change, accessing theses websites will be more intuitive, ergonomic (swiping sideways at the top of screen isn't ideal) and faster.

### Who will benefit from it?
Having recent sites/bookmarks shown would speed up the browsing experience.

**Comment by s-ankur** [comment]
Take a look at https://github.com/mozilla-mobile/fenix/issues/12065
