### ISSUE TITLE
FNX-5054 ⁃ Snackbar actions are not differentiated from snackbar message (color)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1476]
## Steps to reproduce
1. Swipe up on a page
1. Hit the "download" icon

### Expected behavior
The snackbar that appears should have a different color for the message vs. the "button" that can be tapped on. 

### Actual behavior
The only differentiation between the snackbar text and the button is that the button is capitalized. I'm not a huge fan of the capitalization either. 

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1915

**Comment by vesta0** [comment]
UX will look at the colour post MVP.

**Comment by vesta0** [comment]
This is no longer an issue.
