### ISSUE TITLE
add colour to the bookmark star when a page is bookmarked

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#14775]
### What is the user problem or growth opportunity you want to see solved?
You can't tell the difference between it and the bookmarks page. 

### How do you know that this problem exists today? Why is this important?
Firefox for desktop doesn't do this and the important of colour in UI is well known. 

### Who will benefit from it?
Bookmark users

This might be a dupe.

**Comment by s-ankur** [comment]
Dupe  #14728?
