### ISSUE TITLE
[Bug] Firefox is refreshing cache on every reload

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14773]
## Steps to reproduce

Go to https://refreshyourcache.com/en/cache-test/
Refresh the page
### Expected behavior
It will show as red -- cache not cleared
This is the behaviour in chrome
### Actual behavior
It shows green -- cache cleared
This happens even with etp and UBlock off
### Device information

* Android device:Asus Zenfone
* Fenix version: nightly

**Comment by mcomella** [comment]
I can reproduce on desktop and this feels like a platform thing so I'll move to BZ.

**Comment by mcomella** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1666926
