### ISSUE TITLE
[Bug] Misleading German translation for "Download link"

### ISSUE THREAD

**Issue by hebu** [mozilla-mobile/fenix#14779]
## Steps to reproduce

- Switch Firefox to German language
- open a web page where you can download a file
- long-press on the link to the file
- see the context menu entry "Download-Link", which is a misleading translation

### Expected behavior

The menu entry should read something like "Link herunterladen" or - according to Firefox Desktop - "Ziel speichern".

### Actual behavior

The menu entry reads "Download-Link". The translation "Download-Link" actually is a compound term or noun which says "this is a link to download something". It does not describe an action like "click here to download this".

### Device information

* Android device: Android 8.0.0 / EMUI
* Fenix version: 80.1.2 (Tuesday 9/1 @ 12:16 AM)

**Comment by anotherus3r** [comment]
Translations are maintained through Pontoon at https://pontoon.mozilla.org in the "Android L10n" project. It might be better to suggest the improvement there.

**Comment by hwinnemoe** [comment]
https://pontoon.mozilla.org/de/android-l10n/mozilla-mobile/android-components/components/feature/contextmenu/src/main/res/values/strings.xml/?string=208685

**Comment by hebu** [comment]
Great, thanks for pointing out. As I do not have a registered account over there, I hope someone can take over.

**Comment by liuche** [comment]
@Delphine should we tag you for these sorts of issues, or through some other channel?

**Comment by Delphine** [comment]
Yes, please tag me for these sorts of issues. I'll look into this now. Thank you!

**Comment by crisalis2** [comment]
What a coincidence, but there's literally the same problem with the Spanish translation. "Download link" gets translated to "Enlace de descarga" ("Link of download", "\<noun\> of \<noun\>", "Download's link") which means/implies that there's a link that points to some download, instead of the correct "Descargar enlace" ("Download link", "\<verb\> \<noun (object)\>") which means/implies that you can download the link if you tap there.

**Comment by koehlermichael** [comment]
@Delphine and all the others,

Thanks for flagging this issue, you are quite right. The translation [has now been corrected](https://pontoon.mozilla.org/de/android-l10n/mozilla-mobile/android-components/components/feature/contextmenu/src/main/res/values/strings.xml/?string=208685).

**Comment by Delphine** [comment]
> What a coincidence, but there's literally the same problem with the Spanish translation. "Download link" gets translated to "Enlace de descarga" ("Link of/to download", "<noun> of/to <noun>", "Download's link"), which means/implies that there's a link that points to some download, instead of the correct "Descargar enlace" ("Download link", "<verb> <noun (object)>"), which means/implies that you can download the link if you tap there.

Thanks for flagging, I will get in touch with the Spanish localizer as well to fix this. Thank you!

**Comment by crisalis2** [comment]
> Thanks for flagging, I will get in touch with the Spanish localizer as well to fix this. Thank you!

![a](https://user-images.githubusercontent.com/65630147/92953007-3667d180-f461-11ea-882b-f2cbaac5415f.png)
You can show them this image for context.

**Comment by Delphine** [comment]
Spanish ("es" and "es-ES") has been fixed as well in Pontoon.
Closing this for now, please re-open if needed.
