### ISSUE TITLE
[Bug] unable to search on specific website, input loses focus immediately

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#14774]
## Steps to reproduce
1. Go to https://myheartbeets.com/recipe-index/#all
2. Put focus in the search input field

### Expected behavior
Keyboard stays up

### Actual behavior
Keyboard pops up then immediately disappears

### Device information

* Android device: sony xperia xz1c
* Fenix version: 
80.1.2 (Build #2015761283)
AC: 54.0.5, 02934e437
GV: 80.0.1-20200827204751
AS: 61.0.10

**Comment by staktrace** [comment]
Same problem in nightly

**Comment by TrianguloY** [comment]
Also happens on fenix and even chrome. This seems a page issue, not a browser issue.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 200907 (Build #2015762483), the issue also occurs on Chrome.

### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by staktrace** [comment]
Blah blah blah

**Comment by mariansima** [comment]
Could not reproduce this issue on Samsung A8 (Android 9) with Firefox Nightly 93.0a1 2021-09-07 or Chrome browser

**Comment by staktrace** [comment]
Can't reproduce
