### ISSUE TITLE
[Bug] Missing ETP icon when closing a child tab

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#14785]
## Steps to reproduce
1. Open a website, e.g. https://www.mozilla.org/en-GB/
2. Open another tab using a link on this website, e.g. https://www.mozilla.org/en-GB/firefox/privacy/products/
3. Switch to the new child tab
4. Close the child tab

### Expected behavior
The ETP icon in the toolbar is displayed.

### Actual behavior
The ETP icon in the toolbar vanishes. Opening the settings or switching to PBM and back resolves the issue.

![etp-icon-missing](https://user-images.githubusercontent.com/42788925/92326113-fe6f2180-f04f-11ea-89e1-df19303eaf39.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 200906 06:01 (Build #2015762289)
AC: 58.0.20200904130229, b6c304b2a
GV: 82.0a1-20200902095359
AS: 61.0.13

**Comment by anotherus3r** [comment]
Yes, noticed this, too. Can reproduce this as described in Nightly (200905 06:01) on Android 10.

**Comment by Diana-Rus** [comment]
Reproducing the issue with Samsung Galaxy S9 (Android 8) on Nightly 9/7

**Comment by B0pol** [comment]
Is it just visual or etp is also disabled? Because when you click on it it says disabled

**Comment by hwinnemoe** [comment]
> 
> 
> Is it just visual or etp is also disabled? Because when you click on it it says disabled

It seems to still be active, but the user-facing UI seems to malfunction - That is currently tracked in #14949.

**Comment by opusforlife2** [comment]
> Close the child tab

Or swipe to the parent tab. Same result.

**Comment by hwinnemoe** [comment]
This is now fixed in Nightly 200920 06:02 (Build #2015764977).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
