### ISSUE TITLE
[Bug] Tab gets visually corrupted

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#14789]
- [ ] Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1663355

## Steps to reproduce
- Have the google search fixer addon enabled
- Look something up on google images and filter for gif results
- Scroll around on the page, click on some images

### Expected behavior
The page behaves normally.

### Actual behavior
The page is displayed incorrectly, with random blocks and images all over the page. This state is persisted even on reloads, clicking on links, or going to a previous tab. I've also managed to reproduce (but not consistently) on reddit and some other sites.
![output_2](https://user-images.githubusercontent.com/66154603/92330740-916c8380-f071-11ea-83d2-c2af5a7ee9b7.gif)

### Device information
* Android device: Huawei nova 6
* Fenix version: Nightly 200906 06:01 (Build #2015762291)
AC: 58.0.20200904130229, b6c304b2a
GV: 82.0a1-20200902095359
AS: 61.0.13

**Comment by hwinnemoe** [comment]
I cannot reproduce this on the same Nightly with an OpenGL compositor. You could try **temporarily** disabling Webrender on your device and check if that resolves your issues - you can do this via `about:config` and setting _gfx.webrender.force-disabled_ to true.

**Comment by mobd** [comment]
That seems to be the problem, if I toggle that setting and restart I can no longer reproduce.

**Comment by hwinnemoe** [comment]
There are some similar bugs on Bugzille on BZ-1607335 for Mali GPUs, but I think you should file a bug on Bugzilla,
Product: Core,
Component: Graphics: WebRender.

**Comment by hwinnemoe** [comment]
Thank you for filing :) see BZ-1663355

**Comment by mobd** [comment]
No problem, I was still trying to figure out how to link this issue but I guess thats fixed now haha

**Comment by hwinnemoe** [comment]
The "See Also" setting is under the "References" section when you click "Edit Bug", but you may need more permissions to edit this. They may ask more questions on BZ, but you should get notifications if that happens

**Comment by hwinnemoe** [comment]
@mobd This should now be fixed in Nightly 200920 06:02 (Build #2015764977). Can you still reproduce with the default configuration? `gfx.webrender.picture-caching` should be `true` and WR should be active.

**Comment by mobd** [comment]
Yea, it seems to be fixed now, so I guess I'll close this. Thanks for the update :)

**Comment by hwinnemoe** [comment]
Thanks @mobd!

@liuche is it ok to close this or should QA verify this?
