### ISSUE TITLE
Settings: Section headers are inconsistent

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#14784]
### What is the user problem or growth opportunity you want to see solved?
The section headers in settings sub-pages like `Customize` and `Search` differ from the ones in the top settings screen. They are **indented** and **not separated by horizontal lines**.
This makes them visually more difficult to distinguish.  Instead, they should be not indented and have separation lines.

On horizontal lines: They are the norm for separating Android settings categories, as can be seen in the `Android settings > Accessibility`:
<img src="https://user-images.githubusercontent.com/46764284/92325370-3ecba100-f04a-11ea-8e9e-1eea68ec81f1.png" width=250 />

### How do you know that this problem exists today? Why is this important?
**Top settings screen:**

<img src="https://user-images.githubusercontent.com/46764284/92325724-23ae6080-f04d-11ea-98ef-6ea4d312b900.png" width=250 />

Note how `Advanced` and `About` are not indented and are separated by horizontal lines, making it easy to identify the different sections.

**`Customize` settings (this also happens in the `Search` settings):**

<img src="https://user-images.githubusercontent.com/46764284/92325734-2e68f580-f04d-11ea-94b3-36d6e5784259.png" width=250 />

Clearly, in `Customize`, the different categories (theme, toolbar and home) are more difficult to distinguish.
Also, it is inconsistent.

### Who will benefit from it?
Users navigating around the settings.

**Comment by cadeyrn** [comment]
This inconsistency was intentionally introduced in #12533. /cc @brampitoyo

**Comment by amkcpu** [comment]
The points made in https://github.com/mozilla-mobile/fenix/issues/12533#issuecomment-666091940 seem valid in that indentation is done inconsistently in Android and various Google apps.

However, at least category separation lines are pretty common (see the screenshot from settings above, or the Google Play Store settings).

Also, the category headers usually have a color that differs more from the other fonts (again, see screenshot from the Accessibility settings above), which already makes a huge different for visibility.

**Comment by brampitoyo** [comment]
@cadeyrn Yes. The inconsistency was intentionally introduced just as you wrote. I couldn’t find an indentation spec that would simultaneously make headers look good (at the root level), and at the same time, look like they belong with the rest of the menu items (in all other sub-pages).

It’s really cool to read @amkcpu’s proposal, that we can apply to all settings screen without exception:

> - Horizontal line separations in all settings screens
> - Category headers using a stronger accent color
> - 72dp indentation everywhere

We do have an accent colour for both themes:

- Light theme: `violet 70` `#592acb`
- Dark and Private themes: `violet 40` `#ab71ff`

We’d normally use this accent colour exclusively for text links and text-only buttons, but never for headers and items that aren’t tappable.

However, in Android System Settings, we see Google using the same accent colour for category headers and buttons:

| Category headers | Buttons |
| --- | --- |
| <img width="360" src="https://user-images.githubusercontent.com/51007/92550838-a420cb80-f2b0-11ea-930f-1d18f5ae5f69.png"> | <img width="360" src="https://user-images.githubusercontent.com/51007/92550793-7cc9fe80-f2b0-11ea-97ca-181946432e53.png"> |

So, perhaps it makes sense for us to use an accent colour in our headings, too?

See these examples below:

| Light theme | Dark theme |
| --- | --- |
| <img width="360" alt="Settings - Light@2x" src="https://user-images.githubusercontent.com/51007/92551740-dd5a3b00-f2b2-11ea-9b5c-2484046237d8.png"> | <img width="360" alt="Settings - Dark@2x" src="https://user-images.githubusercontent.com/51007/92551743-df23fe80-f2b2-11ea-9474-90647c90103c.png"> |

Thoughts?

**Comment by amkcpu** [comment]
@brampitoyo This is exacy what I had in mind!
And the same thing can then be applied to all settings screens (it's pretty self-explanatory, so I don't think additional mockups are needed). From my perspective, this is ready for engineering.

**Comment by liuche** [comment]
We're addressing this in #14636. Is this the next step for settings, or would these be explorations @apbitner ?

**Comment by apbitner** [comment]
I'll have to defer to @brampitoyo since he created the mocks above.

@brampitoyo - we're fixing the spacing to match our existing specs in #14636. The accent colors for headers look good IMO, so you could include it as part of that work or keep this ticket separate.

**Comment by brampitoyo** [comment]
@apbitner Let’s go with @liuche’s suggestion.

On #14636, in addition to fixing the spacing, let’s also set section headings to use the same colour and ruler above.

**Comment by brampitoyo** [comment]
@amkcpu @cadeyrn You can subscribe to #14636 for implementation. This issue can now be closed. Thanks!
