### ISSUE TITLE
UI improvements for users using tabs on top

### ISSUE THREAD

**Issue by Shaurya-Kalia** [mozilla-mobile/fenix#14787]
It is clear that fenix ui has been designed primarily around bottom aligned toolbar. However, many do not prefer it for various reasons, and prefer to switch toolbar to top. Their are however certain regressions when toolbar is switched to top, as the UI was not desinged specifically for it. Some of them are:

1. The tab tray comes up only half way up the screen and requires additional gesture to bring slightly above. For someone using toolbar on top, it is easier to reach top, and after clicking on tab button, the most accessible position for user's hand is near the top. It does not make sense to bring the tab tray only half way up, since it brings useless distance between the finger's position and most elements.

2. In fennec, as well as in fenix with bottom toolbar, the new tab button is directly under the tabs button, when the tab button has been clicked to invoke the tab tray. This makes adding new tabs very quick and intuitive. Although tabs button can be long pressed to show option of opening new tab and private tab, it still takes longer and is less intuitive. More over in current design, the new tab button is right at the bottom even for top toolbar design, which is a great inconvenience to click on once tab tray is up.

Solution to above problems:
1. When top toolbar is chosen, the tab tray should come all the way to top and touch the status bar. No additional gesture should be required to pull it up.

2. The new tab button of tab tray should be switched to top right position so that it is directly under the tab button when clicked

**Comment by amkcpu** [comment]
Suggestion 2) is #14403.

**Comment by yoasif** [comment]
>     1. The tab tray comes up only half way up the screen and requires additional gesture to bring slightly above. For someone using toolbar on top, it is easier to reach top, and after clicking on tab button, the most accessible position for user's hand is near the top. It does not make sense to bring the tab tray only half way up, since it brings useless distance between the finger's position and most elements.

You may like https://github.com/mozilla-mobile/fenix/issues/14909

**Comment by liuche** [comment]
If the other issues reflect what you're looking for, please close.
