### ISSUE TITLE
[Bug] Hardware menu button doesn't trigger Firefox menu

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#14795]
## Steps to reproduce
Press the menu button
### Expected behavior
In-app menu should draw
### Actual behavior
Nothing happens
### Device information
AOSP
* Android device: 9
* Fenix version: 80.1.2 (Build #2015761283)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6468)

**Comment by mcarare** [comment]
@qautomotive Can you give us more details about this?  What screen were you on, what operations you performed previously? A video of the issue might also help. Thank you!

**Comment by qautomotive** [comment]
The menu button works on screen, but doesn't respond to the 'event' of the android menu button being pressed where other apps do.
Gmail doesn't either interestingly.
The menu button is in place of what is commonly 'recents'.
I think the menu button is more important than recents and that's why I use it, google appears adamant to retire it but I refuse!
I have a video for you but github doesn't seem to support plain attachments...how do you want to see it?

**Comment by mcarare** [comment]
No need for a video, I understand the issue now. As this feature is less and less usual with Android devices, it is less probable to implement support for it.

**Comment by KrasnayaPloshchad** [comment]
Reproduced with v81.1 and [Menu Button](https://play.google.com/store/apps/details?id=jettoast.menubutton) app

**Comment by KrasnayaPloshchad** [comment]
Also reproduced with Nightly 201001

**Comment by Tomatoide** [comment]
man I miss this, also I have a search button and in fennec it opened the addressbar and keyboard so it made my workflow faster

**Comment by KrasnayaPloshchad** [comment]
It’s interesting to know how Google discourage the use of that event.

**Comment by qautomotive** [comment]
> It’s interesting to know how Google discourage the use of that event.

You can _depend_ on Google to remove features they previously expect people to rely on.
A menu button is a very logical function.

**Comment by KrasnayaPloshchad** [comment]
It’s interesting to know the reason that Google discourage the use of that event.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808761

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by rokejulianlockhart** [comment]
@Tomatoide, create a new issue for https://github.com/mozilla-mobile/fenix/issues/14795#issuecomment-725391559.
