### ISSUE TITLE
[Bug] auto hide toolbar causes unrendered bottom of screen

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#14798]
## Steps to reproduce 
Custom setting: place toolbar at top for user convenience.
When visiting several sites or even viewing firefox warning pages the toolbar can auto hide.
On multiple occasions this auto hide causes the page to partly not render or unexpected render at the bottom. Since auto hide behavior is unpredictable it is hard to say which site or errorpage to view to trigger this bug.

### Expected behavior 
Auto hide should not cause rendering issues on parts of www pages or browser warning pages.
Certainly not on pages that follow w3c html and css guidelines.
When browser auto adjust initial settings and browser elements the browser must provide corrected rerendering or provide standard triggers for pages to recalculate page behaviour and expect rerendering. When no page rerendering request is provided browser must force rerendering since browser adjusted initial settings.

### Actual behavior 
Bottom of screen has unredered screen section with similar size of toolbar.
Unrendered screen section causes extra bugs when zooming or scrolling such as not functioning page elements

### Device information
* Fenix version: 80.1.2

**Comment by Mugurell** [comment]
@clientenq Does the problem you're seeing seems similar to this https://github.com/mozilla-mobile/fenix/issues/14821 ? (see video)

**Comment by liuche** [comment]
This sounds like a dupe, please reopen if not.
