### ISSUE TITLE
[Bug] Failed download notification reappears after app restart

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#14790]
## Steps to reproduce
- Have a download that fails
- Clear the notification
- Restart the app

### Expected behavior
The notification is gone.

### Actual behavior
The notification reappears. I don't know if it's related to #14155 or #13458, but up until now notifications always went away after closing the app.
![output_3](https://user-images.githubusercontent.com/66154603/92330978-4fdcd800-f073-11ea-9f4e-ec1c5a52aeff.gif)

### Device information

* Android device: Huawei Nova 6
* Fenix version: Nightly 200906 06:01 (Build #2015762291)
AC: 58.0.20200904130229, b6c304b2a
GV: 82.0a1-20200902095359
AS: 61.0.13

**Comment by Thundebird** [comment]
I also faced the same problem..... Actually it is not good idea to hide the download files in new update....

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 200908 (Build #2015762675)

### Devices used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by Amejia481** [comment]
This issue will be addressed on https://github.com/mozilla-mobile/android-components/issues/8354

**Comment by liuche** [comment]
This should be in the the 9/16 build.

**Comment by mobd** [comment]
Thanks for the update, I can confirm this is fixed in the latest nightly.
