### ISSUE TITLE
Bottom Toolbar moves to top when entering text

### ISSUE THREAD

**Issue by thirdconspiracy** [mozilla-mobile/fenix#14797]
As a firefox android user with toolbar on bottom selected,
when I click the address bar,
the address should remain at the bottom per my selection

Steps to reproduce:
* Select Settings > Customize > Toolbar > Bottom
* Click address bar
* See address bar move to Top of browser

AC
When toolbar is configured to be on the bottom, it should remain on the bottom of browser (just above keyboard), even when entering an address

**Comment by clientenq** [comment]
Does the toolbar move to the too of the browser or only to the top of the appearing keyboard?

In the last case it is presumable not the best solution to move the keyboard on top of the toolbar (if that is even possible) since this forces users in another grip or stretch fingerpositions.

**Comment by thirdconspiracy** [comment]
It moves to the top of the browser.  I would expect it to remain at the bottom of the browser, just above the keyboard.

**Comment by thirdconspiracy** [comment]
I edited the report to be more clear.

**Comment by mcarare** [comment]
This will no longer happen in a future release. Nightly version already implements a new search experience. 
@thirdconspiracy you can test that in Nightly and let us know what you think, if it meets your expectations. Thank you for your report!

**Comment by thirdconspiracy** [comment]
Confirmed it works as expected. Thanks for the fix! Amazing work!
