### ISSUE TITLE
[GitHub] Provide google play link in readme

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14794]
Firefox focus and many similar projects hosted on GitHub provide appstore links to the browsers on their readme pages. It would be great if we had the same for Fenix. It woud help people find the correct browser without resorting to appstore search (which by the way does not return firefox as the first result on querying for "fenix"). Now that the migration is complete this should be very easy to do

**Comment by RachitKeertiDas** [comment]
Hi, 
This was fixed via #14829 .
You may want to close this ticket.

**Comment by s-ankur** [comment]
I think they forgot to mention in the PR. Closed as fixed!
