### ISSUE TITLE
Moxilla limits user experience by releasing a crippled version of Firefox for Android

### ISSUE THREAD

**Issue by freebrowser1** [mozilla-mobile/fenix#14808]
Why is Mozilla releasing a version of Firefox for Android with limited capabilities as the 'release' version while the existing one (until 68.11) worked fine and was more like the 'desktop' version ?
This version is still rather buggy, incomplete (missing add-ons and about:config) and in the Play Store

https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&showAllReviews=true

it is now raining one and two star ratings since the release of the Fenix version of 79.0, with the result average rating on Play has decreeased from 4.4 to 4.0.
And mentioning the missing of 'about:config' in Github results in "that is not included in the release version", while is was in earlier versions. 
Why are these limitaions imposed on Fenix ? Is there really such a strong reason for that ? Modern Android devices are powerful enough to use a browser just like a desktop browser. On FF 68 it worked flawlessly and users were happy but now users complain about missing add-ons, missing features (many of them can be solved with about:config). 
For me personally, I stopped using Fenix because of these limitations. I want to have a real browser and not a crippled one.

**Comment by articlecat** [comment]
about:config is available in Firefox Beta:

https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta

As for the rest, it's clear that the Firefox Daylight rollout was premature and could have been handled better.

**Comment by mohibo** [comment]
> 
> 
> Why is Mozilla releasing a version of Firefox for Android with limited capabilities as the 'release' version while the existing one (until 68.11) worked fine and was more like the 'desktop' version ?
> This version is still rather buggy, incomplete (missing add-ons and about:config) and in the Play Store
> 
> https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&showAllReviews=true
> 
> it is now raining one and two star ratings since the release of the Fenix version of 79.0, with the result average rating on Play has decreeased from 4.4 to 4.0.
> And mentioning the missing of 'about:config' in Github results in "that is not included in the release version", while is was in earlier versions.
> Why are these limitaions imposed on Fenix ? Is there really such a strong reason for that ? Modern Android devices are powerful enough to use a browser just like a desktop browser. On FF 68 it worked flawlessly and users were happy but now users complain about missing add-ons, missing features (many of them can be solved with about:config).
> For me personally, I stopped using Fenix because of these limitations. I want to have a real browser and not a crippled one.

because they wanted a new one,and they fucked it up

**Comment by mohibo** [comment]
> 
> 
> Why is Mozilla releasing a version of Firefox for Android with limited capabilities as the 'release' version while the existing one (until 68.11) worked fine and was more like the 'desktop' version ?
> This version is still rather buggy, incomplete (missing add-ons and about:config) and in the Play Store
> 
> https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&showAllReviews=true
> 
> it is now raining one and two star ratings since the release of the Fenix version of 79.0, with the result average rating on Play has decreeased from 4.4 to 4.0.
> And mentioning the missing of 'about:config' in Github results in "that is not included in the release version", while is was in earlier versions.
> Why are these limitaions imposed on Fenix ? Is there really such a strong reason for that ? Modern Android devices are powerful enough to use a browser just like a desktop browser. On FF 68 it worked flawlessly and users were happy but now users complain about missing add-ons, missing features (many of them can be solved with about:config).
> For me personally, I stopped using Fenix because of these limitations. I want to have a real browser and not a crippled one.

just use fennec from fdroid,it works perfectly

**Comment by kbrosnan** [comment]
Duplicate #14034 / #7865
Closing

**Comment by mohibo** [comment]
> 
> 
> about:config is available in Firefox Beta:
> 
> https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta
> 
> As for the rest, it's clear that the Firefox Daylight rollout was premature and could have been handled better. The release is what it is, but this something to keep in mind if Firefox is ever rewritten again.

it wasn't ready at all

**Comment by mohibo** [comment]
> 
> 
> Duplicate #14034 / #7865
> Closing
and the problems are going to being solved magically

**Comment by mohibo** [comment]
> 
> 
> Why is Mozilla releasing a version of Firefox for Android with limited capabilities as the 'release' version while the existing one (until 68.11) worked fine and was more like the 'desktop' version ?
> This version is still rather buggy, incomplete (missing add-ons and about:config) and in the Play Store
> 
> https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&showAllReviews=true
> 
> it is now raining one and two star ratings since the release of the Fenix version of 79.0, with the result average rating on Play has decreeased from 4.4 to 4.0.
> And mentioning the missing of 'about:config' in Github results in "that is not included in the release version", while is was in earlier versions.
> Why are these limitaions imposed on Fenix ? Is there really such a strong reason for that ? Modern Android devices are powerful enough to use a browser just like a desktop browser. On FF 68 it worked flawlessly and users were happy but now users complain about missing add-ons, missing features (many of them can be solved with about:config).
> For me personally, I stopped using Fenix because of these limitations. I want to have a real browser and not a crippled one.

who are the retards who are downvote you?its the truth

**Comment by mo-han** [comment]
> just use fennec from fdroid,it works perfectly

bisides [f-droid](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/), mozilla also provides (nearlly) all older versions of firefox
for example, the firefox for android 68.11:
https://download-installer.cdn.mozilla.net/pub/mobile/releases/68.11.0/android-api-16/multi/fennec-68.11.0.multi.android-arm.apk

**Comment by freebrowser1** [comment]
> > just use fennec from fdroid,it works perfectly
> 
> bisides [f-droid](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/), mozilla also provides (nearlly) all older versions of firefox
> for example, the firefox for android 68.11:
> https://download-installer.cdn.mozilla.net/pub/mobile/releases/68.11.0/android-api-16/multi/fennec-68.11.0.multi.android-arm.apk
I already use Fennec.
