### ISSUE TITLE
Address bar unresponsive and slowness opening anchor in large page

### ISSUE THREAD

**Issue by filbranden** [mozilla-mobile/fenix#14805]
## Steps to reproduce

Open an URL in this page, such as:
https://vimhelp.org/eval.txt.html#input%28%29

Then maybe edit it to navigate that website by URL.

For example, go to:
https://vimhelp.org/pattern.txt.html#%2F%5Czs

Then to:
https://vimhelp.org/eval.txt.html#execute%28%29

### Expected behavior

The old Firefox on Android was **impressively** responsive on these pages and it was one of the main reason I used it over Chrome (which would just choke and hang on the `eval.txt.html` page...)

**UPDATE:** Fennec 68.12.0esr works great here. So snappy!!!

### Actual behavior

Now the new Firefox seems to need to load the whole page and takes a long time to do it.

Also quite frustrating is that the **address bar doesn't seem to keep what I typed in it**, but it seems to keep whatever was there earlier and will only update to the new URL after it's changed.

### Device information

* Android device: Pixel 3
* Fenix version: 80

80.1.2 (Build #2015761283)
AC: 54.0.5, 02934e437
GV: 80.0.1-20200827204751
AS: 61.0.10

**Comment by MarcLeclair** [comment]
Triage: Add this bug to Bugzilla for performance and file a second issue for the address bar.

**Comment by MarcLeclair** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1667300

**Comment by snorp** [comment]
Hi @filbranden, I'm unable to reproduce either of these issues (perf or address bar problems) in Fenix Nightly. Would you mind trying there?

**Comment by amedyne** [comment]
Was able to reproduce perf (slow loading of page) issue. Took ~20 seconds for the page to load. 
![screen-20201009-093941](https://user-images.githubusercontent.com/68711330/95592410-93ca5080-0a16-11eb-8a54-9f6bdc2abdfc.gif)


on 
Android 11, Pixel 3;
 Fenix Release: 
   81.1.2 (Build #2015767043)
   AC: 57.0.7, 68343a885
   GV: 81.0.1-20200930150533
   AS: 61.0.13

Similar behavior on:
Nightly 201008 17:08 (Build #2015768523)
AC: 62.0.20201006190820, ab29a90c8
GV: 83.0a1-20201006041051
AS: 63.0.0

**Comment by amedyne** [comment]
No longer reproduced on 
Nightly 201020 17:01 (Build #2015770827)
AC: 63.0.20201019143159, b78b41f98
GV: 83.0a1-20201018211631
AS: 63.0.0
