### ISSUE TITLE
[Bug] Cant disable history in the firefox android app like pc version of firefox.

### ISSUE THREAD

**Issue by damanteg** [mozilla-mobile/fenix#14802]
Cant disable history in the firefox android app like pc version of firefox.

**Comment by liuche** [comment]
You can set History to always delete on Quit, or use the Private Browsing shortcut.

**Comment by damanteg** [comment]
there isn't an option to have it not save history similar to desktop firefox?

**Comment by damanteg** [comment]
> 
> 
> You can set History to always delete on Quit, or use the Private Browsing shortcut.

there isn't an option to have it not save history similar to desktop firefox?

**Comment by serfreeman1337** [comment]
Before fenix update I was able to turn off history completely with the `places.history.enabled` pref, but I now I have to either user private mode or quit from menu. Please consider adding back option to turn off just history.
