### ISSUE TITLE
[Bug] Can no longer share  or store "reader" view of urls

### ISSUE THREAD

**Issue by thirdconspiracy** [mozilla-mobile/fenix#14800]
## Steps to reproduce

1. Open "https://www.wuxiaworld.com/novel/the-unrivaled-tang-sect/uts-chapter-1-1"
2. Click icon to go into "reader" view
3. Copy URL (to bookmark, friend, incognito, etc)
4. Open URL
5. See that link opened "normal" view

### Expected behavior
1. Open "https://www.wuxiaworld.com/novel/the-unrivaled-tang-sect/uts-chapter-1-1"
2. Click icon to go into "reader" view
3. Copy URL (to bookmark, friend, incognito, etc)
4. Open URL
5. URL opens in "reader view"

In prior version, reader view was looked something like this: "about:reader?url=http......".  That was nice because I could bookmark my place and edit the bookmark URL's chapter and never have to view the main site.

### Actual behavior
* about:reader links no longer render
* copied reader URLs cannot be pasted into bookmarks or sent as links.  They render as normal view.

### Device information

* Android device: Pixel 4XL
* Fenix version: 80.1.2

### Suggested Bookmark Wireframe

Name: _________
URL: _____
**Use Reader: [x]**
Tags: ______
Keywork: _________

**Comment by s-ankur** [comment]
I think this is the same underlying issue as https://github.com/mozilla-mobile/fenix/issues/5190

**Comment by liuche** [comment]
I think this is the same issue! We want to be able to return to readerify-ed pages.
