### ISSUE TITLE
[Bug] irregular font sizes inflation

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#14803]
## Steps to reproduce
1. Go to http://www.mundodvd.com/multi-the-avengers-project-139319/6/

### Expected behavior
Font sizes inflation is the same for all comments.

### Actual behavior
Font sizes change

### Device information

* Android device: Pixel 2
* Fenix version: 82.0a1-20200902095359

**Comment by buttercookie42** [comment]
Basically https://bugzilla.mozilla.org/show_bug.cgi?id=786382, I think.

**Comment by karlcow** [comment]
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=786382
