### ISSUE TITLE
[Bug] App preview shows 2 search toolbars

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#14818]
## Steps to reproduce
1. Launch Fenix and tap on the URL bar.
2. Tap on the app preview button in order to minimize Fenix.

### Expected behavior
A single search toolbar is displayed in-app preview mode.
### Actual behavior
App preview shows 2 search toolbars
### Device information

* Android device: Google Pixel 4 XL (11).
* Fenix version: Nightly 9/7.

![Screenshot_20200907-155037](https://user-images.githubusercontent.com/42831109/92391317-1795d200-f125-11ea-9d0f-cfa1756a6b48.png)

**Comment by Mugurell** [comment]
@abodea Does this occur often or was it a one time thing?
FWIK in recent apps Android shows a screenshot of what each app looked like when the user left.
Here I think I'm seeing that Android captured the exact moment when you were switching to edit mode to type a url and we're seeing just a frame of the animation occurring right before you left the app - probably to go to recents screen. 
If this is the case it's certainly an interesting issue, but "it works as expected".

**Comment by abodea** [comment]
@Mugurell it occurs all the time.
> If opening the app from recent you would probably only see one toolbar because the animation ended.

This bug is not about that, it's just when following the steps from the description.

**Comment by TrianguloY** [comment]
The top toolbar is the one from the search fragment, the bottom is from the home fragment. They are different, but visible because the search fragment is transparent above home.
Normally the bottom one is hidden by the keyboard, but the android preview hides the keyboard and so it is shown (and I guess that if you can make your keyboard transparent, it will be shown too).
The simplest solution will be to force the search activity to have an opaque view below, where the keyboard is. Or if that's not possible place it in the home fragment directly.

**Comment by Mugurell** [comment]
The "edit mode" toolbar should automatically be dismissed when the user is leaving the app.
When testing with "window animation scale 10x" I see the following:
![SearchToolbarIsHiddenWhenLeaving](https://user-images.githubusercontent.com/11428869/92571145-69586c80-f28b-11ea-9946-4d35787ee15e.gif)
[video](https://drive.google.com/file/d/1lryvIBRpeuNYBzQ0T_M0VCp1M_tnttpg/view?usp=sharing)

**Comment by cadeyrn** [comment]
> The "edit mode" toolbar should automatically be dismissed when the user is leaving the app.

I cannot confirm this behaviour, but I can confirm the reported bug.

1. I start Firefox and tap on the URL bar
2. I switch to the Android home screen
3. => Now I am on the homescreen and the keyboard is still enabled (that's #14396 
4. I open the Android app previews
5. => I see the reported behaviour with two toolbars
6. I start Firefox again
7. => The edit mode toolbar is still enabled. I only see a completely white screen with the button bar for scan and search engines and the addressbar with microphone and x icons at the bottom of the screen.

**Comment by Mugurell** [comment]
Thank you all!
If this happens often I think we can synchronize the events / toolbars.
