### ISSUE TITLE
[Bug] it does not match `pointer: coarse` CSS media query 

### ISSUE THREAD

**Issue by myakura** [mozilla-mobile/fenix#14816]
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1556983

## Steps to reproduce

1. go to https://charmed-debonair-promotion.glitch.me/pointer-coarse.html
2. see if there's a green rectangle below the paragraph

### Expected behavior

There is a green square shown below the paragraph.

### Actual behavior

There isn't.

### Device information

* Android device: Xiaomi Mi A1
* Fenix version: Checked with Nightly and Beta
    ```
    Nightly 200907 06:01 (Build #2015762483)
    AC: 58.0.20200904130229, b6c304b2a
    GV: 82.0a1-20200902095359
    AS: 61.0.13
    ```
    ```
    81.1.0-beta.2 (Build #2015761659)
    AC: 57.0.1, 3bfddbb7b
    GV: 81.0-20200901203141
    AS: 61.0.13
    ```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6514)

**Comment by myakura** [comment]
The `pointer` media feature is used to apply particular style sheets depending on the accuracy of a pointing device. According to the spec, `pointer: coarse` is expected to be true on a smartphone.
However, Fenix matches `pointer: fine`, a query expected to be true on a desktop where the primary pointing device is a mouse.

**Comment by myakura** [comment]
Likewise, Fenix also does not match `hover: none` but `hover: hover`.
http://charmed-debonair-promotion.glitch.me/hover-none.html
http://charmed-debonair-promotion.glitch.me/hover-hover.html

**Comment by makotokato** [comment]
Hmm, Fennec has the fix via https://bugzilla.mozilla.org/show_bug.cgi?id=1035774 and Fenix on android emulator and Xperia XZ2 work fine. Also, hover issue will be https://bugzilla.mozilla.org/show_bug.cgi?id=1558865.

I guess that your Xiaomi devices has no InputDevice.SOURCE_TOUCHSCREEN for 1st enum data of `InputDevice`...

**Comment by makotokato** [comment]
Also, when I check Chromium code, they return coarse (https://source.chromium.org/chromium/chromium/src/+/master:ui/base/pointer/pointer_device_android.cc;l=41;drc=8586102b48a409c634250f31c3fc7bdde5ec3db0) if one device has touch at least.  This is compat issue.

**Comment by makotokato** [comment]
I think that this issue is same as https://bugzilla.mozilla.org/show_bug.cgi?id=1556983

**Comment by ofrias** [comment]
This issue can be also reproduced with Firefox 85.1.2 running on LineageOS 17.1 on a MotoG 2015 (osprey device).  Related issue:  https://gitlab.com/LineageOS/issues/android/-/issues/2979

**Comment by samuelwx** [comment]
Same problem with Essential Phone PH-1 on Firefox 85.1.3, Android 10.

Results from https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/
![pic1a](https://user-images.githubusercontent.com/39785566/108240737-16fa7080-7186-11eb-8c03-4c247e93db93.png)

**Comment by lorenzos** [comment]
The issue persists on Nightly 93.0a1. Same results as @samuelwx and @myakura on OnePlus 3T.

**Comment by ofrias** [comment]
I have just tested on Firefox Nightly, version 99.0a1 (Build #2015863465), on LineageOS 17.1 on a MotoG 2015 (osprey device), and the issue is fixed.

**Comment by lorenzos** [comment]
Can confirm, same version as @ofrias on the exact same device I originally reported for. The issue can be closed, IMO. Thanks!
