### ISSUE TITLE
[Bug] Intermittent undefined state after closing last tab in PBM

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#14817]
## Steps to reproduce
1. Have one open tab in PBM
2. Close the tab

### Expected behavior
The default PBM screen with no open tabs is displayed.

### Actual behavior
Intermittently, an undefined tab-zero is shown. Pressing back resolves the issue.

![last-pbm-tab-undefined](https://user-images.githubusercontent.com/42788925/92389962-52ded380-f11a-11ea-8110-7f9120348989.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 200907 06:01 (Build #2015762481)
AC: 58.0.20200904130229, b6c304b2a
GV: 82.0a1-20200902095359
AS: 61.0.13

**Comment by liuche** [comment]
Let's dupe these two #14878 since they are almost certainly the same cause, just closing the tab in different ways.
