### ISSUE TITLE
Clear cache option on browser quit

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#14815]
## Steps to reproduce
The clear cache and files option on delete browsing data on quit is not working as expected. It should clear all browser cache just like if you go to app info, storage and cache and clear cache option

### Expected behavior
It should purge browser cache 

### Actual behavior
Cache not getting purged entirely 

### Device information

* Android device: ? Rog 3
* Fenix version: ? Latest nightly 

![Screenshot_20200907-174640699 (1)](https://user-images.githubusercontent.com/58127841/92387022-7a419a80-f132-11ea-9c54-7127bbe74df7.jpg)

**Comment by s-ankur** [comment]
App cache and browser cache are different things. As far as I know, you won't get the effect of app info->clear cache even if you clear it manually using settings-> delete browsing data

**Comment by nigelh747** [comment]
Clearing Cache on exit still leaves some bookmark icons.

For a good App, clearing all cache on exit should mean that Firefox removes all user Cache as the "settings" for the user are kept with the application data on Android
