### ISSUE TITLE
[Bug] Font sizes are rendered wrong

### ISSUE THREAD

**Issue by Jakob-KH** [mozilla-mobile/fenix#14825]
When accessing this site: 
http://vojensbilleder.dk/hverdagen2015.htm
all other mobile browsers I've tried render the font sizes correctly, only Firefox for Android doesn't. It renders the sizes all over the place. Some very large, others much too small. It even renders the text inside some table cells much larger than the text in other cells, even though nothing in the programming specifies anything specific for the cells in question.

For instance, a text set to a size of 16 px is rendered much, much larger than a header set to 22 px. If I change the header's size to 44 px, it IS rendered larger, but only a fraction larger than the 16 px text (and it's obviously enormous on all other browsers). This happens regardless of whether the size is defined as px or pt. If you compare the attached images, it appears to be not the header ("Hverdagen 2011-2015") that is rendered wrong, but the text right below (as well as the cell text a bit further down). They are both part of a DIV with text size 16 px defined in the CSS, as is all the other text in the table seen at the bottom of the screenshot - that is rendered as it should.

It is as if Firefox doesn't keep a specific size as it's base of reference when rendering the text on the page.

Interestingly, if I choose to make Firefox display the desktop version of the page (which is the same page/document with 100% identical code - there is no special programming for the mobile site, as I haven't begun working on that bit yet), the page displays correctly.

I have attached sceenshots of the page in Firefox and Chrome.
![Screenshot_20200907-164411_Firefox](https://user-images.githubusercontent.com/70903215/92398930-b45a6e80-f129-11ea-856b-5bdbbdebc802.jpg)
![Screenshot_20200907-164440_Chrome](https://user-images.githubusercontent.com/70903215/92398933-b4f30500-f129-11ea-82ab-6e14966ef40c.jpg)

## Steps to reproduce
Visit [http://vojensbilleder.dk/hverdagen2015.htm](http://vojensbilleder.dk/hverdagen2015.htm)

### Expected behavior
The text should render with the specified sizes. 
If you visit using for instance Google Chrome or Samsung Internet, this is the case. All desktop browsers, I've tried, display the text correctly as well. As does Safari for iOS.

### Actual behavior
Different text areas render in very different sizes, seemingly for no reason.

### Device information

* Android device: Samsung Galaxy A3 (2017) model SM-A320FL
* Fenix version: 80.1.2 (Build #2015761281)

**Comment by buttercookie42** [comment]
Firefox thinks your page is a page written for desktop browsers and therefore tries to make font sizes more readable.
I concede that for your page the results are somewhat suboptimal, though.

Workarounds are either using something along the lines of `<meta name="viewport" content="width=device-width, initial-scale=1.0">` and making sure your layout works with small viewport widths, too, or else using `-moz-text-size-adjust: none;` ([see MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust) via CSS.

**Comment by Jakob-KH** [comment]
Thank you buttercookie42!

I added -moz-text-size-adjust: none; to the CSS and the problem was solved!

I still think Firefox chooses the text sizes somewhat random, and I really prefer browsers to "do as they are told", not improvise, but as long as there is a workaround, I'm happy :-)
