### ISSUE TITLE
[Bug] tab title is incorrect

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#14828]
## Steps to reproduce
Go to https://bugzilla.mozilla.org/show_bug.cgi?id=1661863 and open the tab switcher

### Expected behavior

Tab title has bug number and summary

### Actual behavior

Tab title says "Crash Data" see attached screenshot.

![Screenshot_20200907-123735](https://user-images.githubusercontent.com/485789/92406886-2d949a00-f107-11ea-9762-0e981f15f358.png)

### Device information

* Android device: Sony Xperia XZ1C
* Fenix version: Nightly 200906 06:01 (Build #2015762291)
AC: 58.0.20200904130229, b6c304b2a
GV: 82.0a1-20200902095359
AS: 61.0.13

**Comment by mobd** [comment]
Duplicate of #14433

**Comment by staktrace** [comment]
Thanks, closing as dupe.
