### ISSUE TITLE
fx-fenix_error_x tab titles

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#14826]
## Steps to reproduce

1) Launch Fenix when there is no/spotty internet connectivity
2) Attempt to open existing tabs

### Expected behavior

1) Tab titles unchanged

### Actual behavior

1) Tab titles become "fx-fenix_error_3" or "fx-fenix_error_4". 

### Device information

* Android device: Pixel 2 XL
* Fenix version: Nightly
![Screenshot_20200904-111103](https://user-images.githubusercontent.com/1104290/92403677-3babe000-f132-11ea-92ff-2fd521f07693.png)

**Comment by s-ankur** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/14620

**Comment by Diana-Rus** [comment]
Hello, thank you @s-ankur !
I'll be closing this one, but @gcp  please follow the issue's evolution #14620
