### ISSUE TITLE
FNX-46 ⁃ Ability to disable extension updates

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#1482]
### Why/User Benefit/User Problem
Allows users ability to turn off extension updates so that users can use a specific extension version or to audit/check an update before actually upgrading.

### What / Requirements
Having the same ability as available on desktop Firefox

### Acceptance Criteria (how do I know when I’m done?)
Feature parity with same ability on desktop Firefox, when #574 is implemented

**Comment by vesta0** [comment]
Thanks for filing this @sebast889 ! We will address this in #6122
