### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JSellers0** [mozilla-mobile/fenix#14834]
## Steps to reproduce
On Android Mobile, open a new tab and in search/address bar type hubblesite.org. 
Go to site.
Press three-dot menu and note a back and forward option at the bottom of the menu.
Close the three-dot menu
Press the Android back button until you arrive at Firefox new tab.
Press the three-dot menu.
Note the absence of a forward option.

### Expected behavior
If I accidentally press "Android back" too many times and arrive at Firefox new tab screen, I want an "forward" option to take me back to my first search/request

### Actual behavior
I press "Android back" too many times and end up at Firefox new tab screen. I must re-enter my site/search to get back to where I want to be.

### Device information

* Android device: Samsung Galaxy 9; android version 10
* Firefox version: 
80.1.2 (Build #2015761283)
AC: 54.0.5, 02934e437
GV: 80.0.1-20200827204751
AS: 61.0.10

**Comment by JSellers0** [comment]
I tried searching for this every way I could think of, so I apologize if it is already submitted.

**Comment by mcarare** [comment]
@JSellers0 thank you for your report!
You can get back to where you want to, by using the tab tray. From the home screen press the toolbar button with the number of tabs displayed. There you can choose the tab you want to get back to.

**Comment by journey-of-code** [comment]
@JSellers0 : Please enter a title for your bug-submission.

**Comment by liuche** [comment]
Closing this - opening a new tab and visiting a page does not enable the forward/back buttons, the site becomes the "basis" of the tab. If you want to switch tabs, the tabs tray is the tool for that.
