### ISSUE TITLE
[Bug] Firefox doesn't handle body with height 100vh properly

### ISSUE THREAD

**Issue by RadhiFadlillah** [mozilla-mobile/fenix#14839]
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1662823

## Steps to reproduce

- Create a HTML page
- Set its `body` height to `100vh`
- Put something (`p` maybe), set it to the bottom of the `body`
- Open the page in Firefox Mobile

Here is the [pen](https://codepen.io/radhifadlillah/full/bGpaOGy) to reproduce it.

### Expected behavior

The bottom area should be visible. Here is how it looks like in Brave Browser :

<img src="https://user-images.githubusercontent.com/6129042/92424668-23c67180-f1af-11ea-8d7c-ca296f483539.jpg" alt="Brave do it right" width="250">

### Actual behavior

The paragraph is hidden in Firefox, no matter where the address bar located :

| Address bar in bottom | Address bar in top |
|-----------------------------|-------------------------------|
| <img src="https://user-images.githubusercontent.com/6129042/92424780-72740b80-f1af-11ea-8c17-7a27d126eb3f.jpg" alt="The paragraph seems to be hidden by address bar" width="250"> | <img src="https://user-images.githubusercontent.com/6129042/92424961-faf2ac00-f1af-11ea-8791-bb86982bfdb1.jpg" alt="However it still not visible even after address bar moved to top" width="250">  |

### Device information

Tested in **Redmi Note 8** running MIUI Global 11.0.5 (**Android 9**). I tried in both Firefox stable and nightly :

- Firefox Daylight 80.1.2 (Build #2015761283)
- Firefox Nightly 200907 06:01 (Build #2015762483)

**Comment by Mugurell** [comment]
Thank you!
I've created https://bugzilla.mozilla.org/show_bug.cgi?id=1663634 for this.

**Comment by Mugurell** [comment]
There were many changes in the meantime but haven't verified if this is fixed.
Let's consider it's not and reopen the ticket.

**Comment by Dunexus** [comment]
Still reproducible on latest nightly with both top and bottom bar.

**Comment by sflorean** [comment]
I confirm that this is reproducible on latest Nightly build, following the steps, with Samsung Note 10 (Android 11).
