### ISSUE TITLE
Please consider removing the "Scan + Search engine" bar

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#14838]
Please consider removing the "Scan + Search engine" bar that appears when you tap the URL. There's quite a few reasons this should be considered but I think the major ones are:

- It's taking up precious space for URL/search suggestions. Smartphones already have very limited space here and there would be approx 1 more result visible if the "Scan + Search engine" bar wasn't there. 

-  Users that have the toolbar at the bottom and are using the phone with one hand have to stretch/reach their thumb slightly more to tap the "top" result

- Cleaner, more focused minimalist UI

(I hope this request doesn't come across as disrespectful. I think Fenix has the best UI of any phone browser ever, it's just this Scan+Search bar I wish was removed. I am very grateful to the Fenix team :) )

![fenixscansearchenginebar](https://user-images.githubusercontent.com/47801466/92422552-cf3dda80-f14b-11ea-9ed9-dc7a2941ba40.png)

**Comment by hwinnemoe** [comment]
Already discussed in #13473

**Comment by topnax** [comment]
I would love to see that bar removed.
