### ISSUE TITLE
Pocket integration into collections

### ISSUE THREAD

**Issue by meter1060** [mozilla-mobile/fenix#14832]
In the past I have used pocket to save my pages to read later but often I find the functionality of accessing them again hard to keep in my mind, especially since I use Firefox to save the pages and then go back to Firefox to read them. It would be neat to have pocket integrate into the collections functionality in Fenix.

-  This would mean a dynamically changing collection that auto populates based on my pocket list. That way whenever I use pocket to save a web page to pocket to be read later. It easily shows up in Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6534)

**Comment by kbrosnan** [comment]
Quite similar to #8815

**Comment by anotherus3r** [comment]
I would like that, too. Though I do have a long list of articles saved in Pocket (which I should finally start reading); maybe a collection with the 10 most recently saved articles would be a good solution. At the end of this collection could then be a button/link that takes you to your full Pocket list - either on the website or in the Pocket app.

**Comment by ekager** [comment]
We've discussed this with the Pocket team previously and I believe this would be blocked on Pocket integrating with FxA

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807375

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
