### ISSUE TITLE
FNX-5058 ⁃ [Bug] On some devices the follow device theme/battery saver option does not work

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1484]
## Steps to reproduce
1. Go into Settings > Theme
1. Select "Set by Battery Saver/Follow device theme"
1. Turn on Battery Saver.

    1. Expected behavior
Fenix theme changes when battery saver is turned on.

### Actual behavior
Theme stays exactly the same.

### Device information
* Affected devices:
  * Nokia 6 (Android 7.1.1)
  * Galaxy S8 (Android 9)
  * Galaxy Note 8 (Android 9)
* Unaffected devices:
  * HTC 10 (Android 8)
  * Google Pixel (Android 9)
  * Nexus 6P (Android 8.1)
* Fenix version: 1.0.1915 (#10981205)
* [Logcat Note 8](https://github.com/mozilla-mobile/fenix/files/3058460/log.txt)
* [Logcat Nokia](https://github.com/mozilla-mobile/fenix/files/3058462/nokia.txt)
* [Video](https://drive.google.com/open?id=1KNfPCNh-swpOlN2agUzWA6HUYcjfyBf5)
* On the Note 8 and S8 where both options were available if setting the Battery Saver option the theme changed. If setting the other option nothing happens.

**Comment by ekager** [comment]
Thanks @bsurd ! Some follow up questions: 

On Samsung devices if you scroll to the second page of settings from the pull down menu, you should see a "Night Mode" setting. From my testing, this is the setting that will force the device to go in dark mode that will then update Fenix's theme if it is using "Follow device theme". If this is working correctly, could you update the description with the devices that are affected?
![Screenshot_20190409-092859_Fenix](https://user-images.githubusercontent.com/25442310/55817684-e5082580-5aa9-11e9-8975-a44accad5c60.jpg)

Could you explain more what you mean by "both options were available"? You were able to see "Set by Battery Saver" and "Follow device theme" in Theme Settings? 

Could you send a video of the Nokia 6 if possible? 

Thank you!

**Comment by bsurd** [comment]
@ekager 

> On Samsung devices if you scroll to the second page of settings from the pull down menu, you should see a "Night Mode" setting. 

Indeed, if selecting "Night Mode" the Fenix theme changes as well. It was a bit counter intuitive since on all of the unaffected devices the theme changed when enabling the battery saver option

> Could you explain more what you mean by "both options were available"? You were able to see "Set by Battery Saver" and "Follow device theme" in Theme Settings?

I've installed an older version befor the change in #1403 landed and yes, both options were available. After the change landed only the "Follow device theme" option remained. 

> Could you send a video of the Nokia 6 if possible?

[Here](https://drive.google.com/open?id=13mRlYH7whG5GimfbODXklJ-18zTiczNv) is the video.

**Comment by ekager** [comment]
If you can still reproduce this, it seems to be a device issue where the battery saver option doesn't work the same way on the Nokia as other devices. I don't think there's anything we can do on our side, since we're just following the system's direction.

**Comment by softvision-miralobontiu** [comment]
Hi @ekager 
I encountered the same behavior on Nokia, with the latest build 1.0.1922 (#11490609).
