### ISSUE TITLE
[Bug] Discord image resized and rescaled to very low resolution

### ISSUE THREAD

**Issue by tomyummmm** [mozilla-mobile/fenix#14847]
## Steps to reproduce
1. Open image from discord in firefox android.
2. See that image is resized / rescaled down to very low resolution

### Expected behavior
Should load full image resolution. 
1. Forced it to load full image resolution in Beta/Nightly about:config, flag browser.enable_automatic_image_resizing set to false.
![Screenshot_2020-09-08-21-23-14-975_org mozilla firefox_beta](https://user-images.githubusercontent.com/65211592/92482430-32963e00-f21a-11ea-9ba2-14f8bd389038.jpg)

### Actual behavior
Loads a low resolution image
![Screenshot_2020-09-08-21-23-04-221_org mozilla firefox_beta](https://user-images.githubusercontent.com/65211592/92482453-3924b580-f21a-11ea-9300-b13d123eca45.jpg)

### Device information

* Android device: Xiaomi K20 Pro
* Fenix version: 80.1.2

**Comment by liuche** [comment]
I wonder how common this issue is on different sites, or why it's happening here - I assume you aren't able to tap to zoom and see a better resolution?

**Comment by tomyummmm** [comment]
> I wonder how common this issue is on different sites, or why it's happening here - I assume you aren't able to tap to zoom and see a better resolution?

Tap to zoom doesnt seem to work, still same low resolution scaling
