### ISSUE TITLE
[Bug] Video player bug/regression in New 80.1.2 update

### ISSUE THREAD

**Issue by OddEvans** [mozilla-mobile/fenix#14841]
## Steps to reproduce
1 - Open crunchyroll.com in Firefox Daylight 
2 - Select an episode of any anime 
3 - Click play, video plays fine
4 - Go to Full Screen 
5 - Bug/Regression, video out of boundaries of screen

### Expected behavior

Same as previous version 79, play and open video in full screen with video being in the boundaries of the screen in the phone be it vertically or horizontally 

### Actual behavior

Video is not in bondaries of the phone screen and you can only see the corner of the top left of the video if barely 

![Movie 1_1](https://user-images.githubusercontent.com/66402918/92435556-83912e00-f157-11ea-8e5c-3e124b782757.gif)    ![Movie 1_2](https://user-images.githubusercontent.com/66402918/92435568-8855e200-f157-11ea-82a0-23e4834376df.gif)

### Device information

* Android device: Samsung Galaxy S10e SM-G970U1
* Fenix version: Firefox Daylight 80.1.2 (Build #2015761283)

Edit: added GIFs and check grammar

**Comment by Mugurell** [comment]
Similar ticket - https://github.com/mozilla-mobile/fenix/issues/14820

**Comment by Mugurell** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1663591 for this.
