### ISSUE TITLE
Slow html5 performance: games stutter

### ISSUE THREAD

**Issue by grenvol** [mozilla-mobile/fenix#14842]
## Steps to reproduce
Load an html5 game like Perfect Piano: https://play.famobi.com/perfect-piano

### Expected behavior
Game should be smooth and close to 60 fps

### Actual behavior
The game stutters and is choppy

### Device information

* Android device: Honor 8x max
* Fenix version: daylight 80.1.2

**Comment by MarcLeclair** [comment]
Triage: File this on Bugzilla for performance

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1664950
