### ISSUE TITLE
[Bug]cannot enable push notification for Twitter 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14858]
I m using fenix niglht and when I try to enable push notification after the prompt for allowing notification, Twitter website tells me that my browser is not supporting push notification, REALLY!?

**Comment by kbrosnan** [comment]
This works for me on Nightly and Twitter. Have you disabled Firefox from displaying notifications or previously blocked Twitter from having notification permissions inside Firefox?

#### Check the notification settings
* Open Firefox 
* tap the 3 dot menu
* Settings
* Notifications
* Make sure that Firefox has permissions to show notifications and if you have disabled any notification channels that they are enabled

#### Check the Site permissions settings
* Open Firefox 
* tap the 3 dot menu
* Settings
* Site permissions
* Notifications should be set to Ask to allow
* The other item to check in this area is the Exceptions list make sure you are not denying Twitter access to notifications

**Comment by ale82to** [comment]
thabks for replying clearing all sites data fixed the issue (still very annoying as I had to log in all websites once again)
anyway thank you!
