### ISSUE TITLE
[l10n] Import latest strings for Sept release

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#14855]
There are no new locales ready this time around for this release (complete list can be found here: https://github.com/mozilla-mobile/fenix/issues/7104#issuecomment-661185865). 
Please therefore only import latest strings for all current locales.

Note: we should be doing the same for a-c

(CC @liuche @pocmo)

**Comment by Delphine** [comment]
Side question: given the recent changes to the l10n team's structure, could we renegotiate how we go about release sign-offs, for both Fenix and a-c strings?
For example, would it be possible for you - once string freeze ends - to import whichever new locales reach 70% completion threshold on Pontoon for each release - as well as the latest strings for all these locales?

(Note: we shouldn't drop any locales once we've added them even if they are falling behind. According to studies, partial localization is always better than nothing at all - and suddenly dropping entirely a partial localization is a very bad user experience)

**Comment by liuche** [comment]
I just ran the l10n import script for pulling in L10N strings on Fenix.

I checked AC and there don't seem to be any new strings for AC, does that sound right @pocmo @Delphine ?

```
Since 'releases/57.0' split off 'master', there were 0 commit(s) from
release+l10n-automation-bot@mozilla.com.
Of those, 0 commit(s) already uplifted.
Need to uplift 0 commit(s).
Nothing to uplift.
```

**Comment by pocmo** [comment]
Did it work without issues in Fenix? Nice :)

I did search git with `git log -- "**/values/strings.xml"` and it looks like the last string change by us was "Aug 23". And the last import  "Fri Aug 28" (`git log -- "**/strings.xml"` and `git log --author=release+l10n-automation-bot`). So definitely has been a while.

**Comment by Delphine** [comment]
Ok so this means there would only be updates to previous existing strings in the meantime done by localizers, probably.

**Comment by liuche** [comment]
I found the AC PR 😅 it's been waiting for pontoon fixes it looks like for 2 weeks: https://github.com/mozilla-mobile/android-components/pull/8285

I can't tell if it's the same PR as 2 weeks ago, or if it picked up some new changes. If the former, we might want to close it and let l10n-bot open a fresh PR.

**Comment by liuche** [comment]
Done!
