### ISSUE TITLE
Option for Chronological Order in the Tab Menu

### ISSUE THREAD

**Issue by Walt280** [mozilla-mobile/fenix#14853]
### What is the user problem or growth opportunity you want to see solved?
It would be nice to have the option of using chronological order (earlier tabs at the top of the list; later tabs at the bottom of the list; new tabs inserted at the bottom of the list) instead of the current reverse chronological order (earlier tabs at the bottom of the list; later tabs at the top of the list; new tabs inserted at the top of the list).

#### Reverse Chronological Order
<img src="https://user-images.githubusercontent.com/32001362/92504366-9267f700-f1d0-11ea-9b80-72fb775dfc24.jpg" width="360" height="640">

#### Chronological Order
<img src="https://user-images.githubusercontent.com/32001362/92504843-3356b200-f1d1-11ea-8c30-88d51eb6e1b1.jpg" width="360" height="640">

### How do you know that this problem exists today? Why is this important?
Chronological order is/was used in other Android browsers such as Chrome, Edge, and older versions of Firefox Android. Having this option would make the transition easier for newcomers and give more flexibility to the browser.

### Who will benefit from it?
All users, especially users with lots of open tabs.

**Comment by kbrosnan** [comment]
Duplicate #11376
