### ISSUE TITLE
Show more top sites on the home page at one time

### ISSUE THREAD

**Issue by bjherbison** [mozilla-mobile/fenix#14851]
### What is the user problem or growth opportunity you want to see solved?

When the number of top sites reaches nine you need to shift back and forth to see all of  them.

### How do you know that this problem exists today? Why is this important?

I added a ninth top site and them wanted to see that site and I needed to shift.

I removed Collections so 2/3 of my home page is blank so there is plenty of room to display nine top sites.

### Who will benefit from it?

Anyone who wants quick access to more than eight web pages.

**Comment by cadeyrn** [comment]
There is already a lot of discussion in #8312.
