### ISSUE TITLE
Android  vcf file showing download failed error

### ISSUE THREAD

**Issue by reyjexter** [mozilla-mobile/fenix#14862]
### What is the user problem or growth opportunity you want to see solved?

It's a problem to us and the users with the same use case.

### How do you know that this problem exists today? Why is this important?

We tested this and VCF always shows a download failed error even when it's stored on sdcard correctly. This seems to be standard on mobile browsers which VCF is already supported.

### Who will benefit from it?

Customers or users that makes use of vcards.

**Comment by reyjexter** [comment]
Android version tested is 10.x

**Comment by Amejia481** [comment]
@reyjexter thanks for reporting, would you mind sharing the link from where you were trying to download?

**Comment by Amejia481** [comment]
Please feel free to reopen if the issue still persist
