### ISSUE TITLE
FNX-5060 ⁃ [Bug] links with target=_blank don't open in new tabs

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#1486]
## Steps to reproduce
* Go to https://staktrace.github.io/moz-pages/bug/fenix-blank-target.html?x
* Click on the link on the page

### Expected behavior
* Link opens in a new tab

### Actual behavior
* Link opens in the same tab. This makes it impossible to get back to the original page, because Slashdot eats your back button attempts. In other browsers you can close the new tab and continue on the original site. With Fenix you have to re-navigate to the original site.

### Device information
* Android device: Sony Xperia XZ1C, Android 9
* Fenix version: How do I tell? It's the one from the play store beta program so probably recent (Edit: found it in the settings, 1.0.1915 (Build #109171207)

**Comment by staktrace** [comment]
Note that this is not just a UX thing, but a violation of web standards and will probably break real-world websites badly.

**Comment by AmyYLee** [comment]
Agreed this is a bug. It should open a new tab in this situation.

**Comment by kbrosnan** [comment]
Broken in reference browser as well. Android components or geckoview bug. @cpeterso @jonalmeida

**Comment by kbrosnan** [comment]
@cpeterso  opened https://bugzilla.mozilla.org/show_bug.cgi?id=1547549

**Comment by csadilek** [comment]
@cpeterso @kbrosnan here's the link to the A-C issue which requires some changes in GV: https://github.com/mozilla-mobile/android-components/issues/1503

**Comment by cpeterso** [comment]
The new GV bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1510314

**Comment by liuche** [comment]
The GV bug has been deprioritized to some time in Q3, so if we want to get it fixed we should comment in the Bugzilla.

**Comment by cpeterso** [comment]
The GV bug has been fixed in GV 70, which ride to Beta on 2019-09-02 and Release on 2019-10-22.

**Comment by kbrosnan** [comment]
@cpeterso is there any a-c or fenix work to take advantage of the changes or will it just work with Gecko 70?

**Comment by cpeterso** [comment]
@snorp, do Fenix or A-C need to write any code for your `setSession` fix (GV bug 1510314) to open new tabs for `target=_blank` links?

**Comment by jonalmeida** [comment]
> @snorp, do Fenix or A-C need to write any code for your `setSession` fix (GV [bug 1510314](https://bugzilla.mozilla.org/show_bug.cgi?id=1510314)) to open new tabs for `target=_blank` links?

Yes, Fenix needs to add a patch similar to this one: https://github.com/mozilla-mobile/reference-browser/pull/852

**Comment by cpeterso** [comment]
snorp gave his OK to uplift the GV fix to GV 69 Beta. @csadilek manually verified the GV fix using R-B and GV 70 Nightly. I've requested uplift here: https://bugzilla.mozilla.org/show_bug.cgi?id=1510314#c22

**Comment by cpeterso** [comment]
Correction: Due to some beta uplift merge conflicts, snorp recommends we not uplift the window.open fix to GV 69 Beta and just let it ride the trains with GV 70 (which rides to Beta on September 3).

https://bugzilla.mozilla.org/show_bug.cgi?id=1510314#c25

**Comment by abodea** [comment]
Verified as fixed in the latest Nightly build from 9/9 using: Samsung Galaxy S10+(Android 9).
The page was opened in a new tab every time(10 out of 10 tries).

**Comment by karlcow** [comment]
In this instance it doesn't work. 
https://github.com/webcompat/web-bugs/issues/39554
