### ISSUE TITLE
Automatic pre-scrolling is not working when opening a select box with many items

### ISSUE THREAD

**Issue by kraaden** [mozilla-mobile/fenix#14870]
## Steps to reproduce

Open the following page on Android for mobile:
https://jsfiddle.net/mdv10se9/1/

It contains a single select box with many items.

Then click on the generated select box. Firefox will show a fullscreen list where you can select another item.

### Expected behavior

The displayed list should start from the SELECTED item in the list (automatic pre-scrolling), just like it works in other web browsers. Otherwise I have to scroll a lot first till the selected item and it takes a lot of time.

### Actual behavior

The displayed fullscreen list starts from the first item in the list. Then you have to scroll through all items in the list (many hundreds).

### Device information

* Android device: Galaxy S20, Android 10
* Fenix version: 80.1.2

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1665516

**Comment by agi** [comment]
The select pop-up is painted by the App or Android Components. The native widget needs to scroll to the selected option.

**Comment by jonalmeida** [comment]
A fix for this is in this linked AC PR: https://github.com/mozilla-mobile/android-components/pull/8954

**Comment by jonalmeida** [comment]
This has landed in Fenix.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201203`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201203-123441](https://user-images.githubusercontent.com/51314259/100998918-cd29c300-3564-11eb-9618-f15f5c413cd9.gif)
