### ISSUE TITLE
[Bug] veritcally cropped video while in full screen

### ISSUE THREAD

**Issue by carriesmi** [mozilla-mobile/fenix#14877]
bottom part of video is out of view when in full screen mode
for example this 
<p align="center">
<img src="https://user-images.githubusercontent.com/36170228/92573123-f3f89600-f2a2-11ea-9681-ded24193d378.jpg" width="140" height="300">
</p>
becomes this 
<p align="center">
<img src="https://user-images.githubusercontent.com/36170228/92573119-f2c76900-f2a2-11ea-9c1b-44d89882a7f9.jpg" width="300" height="140">
</p>

as you can see bottom part of hand is not there.    
Plus for some unknown reason there is black bar on top of the video when in full screen mode.   
This does not happen in chrome on same device.   
Aspect ratio of my phone is 19.5:9.  

## Steps to reproduce
1) Open youtube.com
2) open any video and go in full screen
### Expected behavior
3) Entire video should be visible.
### Actual behavior
4) Top of the video is not at top of screen and bottom part of video is cropped out.

### Device information
* Android device: Samsung M20
* Fenix version: 80.1.2

**Comment by kbrosnan** [comment]
Duplicate #8252
