### ISSUE TITLE
[Bug] navigator.storage.persist not saving data

### ISSUE THREAD

**Issue by Nimdim** [mozilla-mobile/fenix#14875]
## Steps to reproduce

Enable persist mode via running the script:
navigator.storage.persist().then(function(val){console.log(val)});
I have tried also to bookmark page. But it didn't helped.

Testcase: https://testing123.offlinepad.com/test_persist.html

### Expected behavior

Persist mode enabled.

### Actual behavior

Persist mode not enabled.

### Device information

* Android device: Android 9
* Fenix version: 80.1.2

**Comment by kbrosnan** [comment]
Do you have a sample page that uses this or know of a public testcase? Not seeing any examples in a quick look of MDN.

**Comment by Nimdim** [comment]
> Do you have a sample page that uses this or know of a public testcase? Not seeing any examples in a quick look of MDN.

Here is a test link:
https://testing123.offlinepad.com/test_persist.html
First it detects if persist mode is already on. And after that tries to enable it

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1664002

**Comment by kbrosnan** [comment]
Android components issue. https://github.com/mozilla-mobile/android-components/issues/3153

**Comment by Nimdim** [comment]
Could someone say is this issue fixed or not? Two months were gone and I have tested this on Firefox for Android 82.1.3.
The permission prompt still doesn't popup.
