### ISSUE TITLE
Add UI to turn on DNS over HTTPS support (TRR)

### ISSUE THREAD

**Issue by valenting** [mozilla-mobile/fenix#14879]
Note: DNS over HTTPS (DoH) is also known as Trusted Recursive Resolver (TRR) in our Gecko documentation.

### What is the user problem or growth opportunity you want to see solved?

In Firefox Desktop allow the user to enable DNS over HTTPS in about:preferences and to select the provider.
We also turn the feature on by default in certain regions (currently US only) via the DoHController.jsm
While we don't see us rolling out to Fenix on-by-default at the moment it would be nice to have some UI to enable the feature so we can get some data about its performance properties on Fenix.

### How do you know that this problem exists today? Why is this important?

It's needed to enable DNS over HTTPS on Fenix. The only alternative is about:config, which we'd rather the user doesn't touch.

### Who will benefit from it?

Regular users who are on the technical side and care about DNS security.

Related Chrome feature:
https://www.zdnet.com/article/dns-over-https-doh-support-added-to-chrome-on-android/

**Comment by cadeyrn** [comment]
It's a duplicate of #4584.

**Comment by valenting** [comment]
I guess it is. Thanks for pointing that out.

**Comment by scottbeamer** [comment]
Why is this issue closed? It's still a problem.

**Comment by cadeyrn** [comment]
> Why is this issue closed? It's still a problem.

As you can read above your comment this issue is closed because it's a duplicate of an older issue.
