### ISSUE TITLE
[Bug] keyboard shows a "null" overlay when I select the address bar

### ISSUE THREAD

**Issue by maroonmoon13** [mozilla-mobile/fenix#14885]
## Steps to reproduce
Open Firefox 
Click the address bar
### Expected behavior 
The keyboard should display 
### Actual behavior
The keyboard displays and shows a null overlay for a few seconds 
### Device information
Pixel 3
* Android device: ?
![Screenshot_20200909-072041](https://user-images.githubusercontent.com/31255968/92597709-68b0dd80-f26d-11ea-89df-9102bccba1bf.png)

Android 11, gboard and SwiftKey have the issue
* Fenix version: ?

**Comment by kbrosnan** [comment]
This is a lockwise bug. Closing https://github.com/mozilla-lockwise/lockwise-android/issues/1219
