### ISSUE TITLE
[Bug] Reader View: white bg only

### ISSUE THREAD

**Issue by mackeev** [mozilla-mobile/fenix#14882]
## Steps to reproduce
Tap Reader View button when available
### Expected behavior
See controls for changing BG and font type and size
### Actual behavior
Nothing's there. BG won't change even if I manually type Dark via about:config
### Device information

* Android device: redmi note 5 pro
* Fenix version: today's nightly, dark theme, Dark Reader addon

**Comment by cadeyrn** [comment]
You can access the reader view controls via the menu when the reader view is enabled.

**Comment by mackeev** [comment]
Thank you. It's kinda counterintuitive after 68.
