### ISSUE TITLE
[Bug]Live Stream Drops Off After 4 Minutes 

### ISSUE THREAD

**Issue by doropallo** [mozilla-mobile/fenix#14881]
## Steps to reproduce open page 
http://listen.noagendastream.com/noagenda
### Device information

* Android device: Samsung Note 10 Plus 
* Fenix version:  2015761283

**Comment by journey-of-code** [comment]
@doropallo : Please add at least a title to the bug. Please try to write complete sentences - otherwise people will have to guess what you mean. In your answers you accidentally wrote into the section title instead into the section.

**Comment by liuche** [comment]
also see #13865

**Comment by liuche** [comment]
This may be because the media notification isn't persisting, so android kills the stream. We're making improvements on the Media Notifications.
