### ISSUE TITLE
[Bug] Impossible to get number of opened tabs when > 100

### ISSUE THREAD

**Issue by liar666** [mozilla-mobile/fenix#14886]
## Steps to reproduce
- Open 100+ tabs

### Expected behavior
- Be able to know the exact number of tabs opened

### Actual behavior
- The icon that displays the # tabs shows [00]

### Device information

* Android device: Doogee N10 / Android 8.1
* Fenix version: 80.1.2

**Comment by cadeyrn** [comment]
works as intended, see #12976.

**Comment by jawz101** [comment]
There needs to be a tab limit of like 20 :/

**Comment by kbrosnan** [comment]
This is expected behavior and matches what Fennec did. Making +3 digit numbers fit in the space and look good is not trivial.

**Comment by superbonaci** [comment]
> 
> 
> This is expected behavior and matches what Fennec did. Making +3 digit numbers fit in the space and look good is not trivial.

I request 3 or more numbers not on icon, but on tab list: "Your open tabs will be shown here". There's enough space there.

![](https://i.imgur.com/TvI8S2X.jpg)
