### ISSUE TITLE
[webcontent] Characters randomly dont load correctly

### ISSUE THREAD

**Issue by verycoolperson** [mozilla-mobile/fenix#14889]
This bug seems to happen randomly

### Expected behavior
In a web page characters should load normaly

### Actual behavior
Many characters are not loading normaly at all
![20200909_154510](https://user-images.githubusercontent.com/70904390/92600219-ed264f00-f2b3-11ea-9e62-52af4fee8f11.jpg)

### Device information

* Android device: Samsung A30s / Android 10
* Fenix version: Nightly 200908 06:01

**Comment by yoasif** [comment]
Have you enabled WebRender by any chance?

**Comment by verycoolperson** [comment]
Nope its disabled

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1664015

**Comment by mstange** [comment]
> Nope its disabled

Are you sure? Can you go to about:support and check what it says under Compositing in the Graphics section?

**Comment by verycoolperson** [comment]
Ahh sorry I went to about:config and it said gfx.webrender.all is false so i assumed its disabled. Anyway yes in the Compositing section it does say WebRender

**Comment by hwinnemoe** [comment]
You could try to **temporarily** disable WebRender on your device and check if that resolves your issues - open `about:config` and set _gfx.webrender.force-disabled_ to **true**

**Comment by jamienicol** [comment]
Hi @verycoolperson, thanks for the bug report.

When you say it happens randomly, how often is that? Once a day, every few minutes? Does it seem to happen on some pages more than others? Does it go away if you minimise firefox then reopen it? Does it happen during scrolling on a page that looked okay at first, or does it happen as soon as the page loads? Is it always the same letters which go missing? Once you see this bug, if you open a new tab is the new tab affected too?

**Comment by verycoolperson** [comment]
It happens maybe like once every 2 weeks? And it happens mostly on google but thats where I mostly open new tabs so idk if it is more likely to happen there or not. The only way i have found to fix it is closing firefox and opening it back again. Pretty sure thats all the info I have.

**Comment by jamienicol** [comment]
Hi @verycoolperson, are you still seeing this bug?

**Comment by verycoolperson** [comment]
Not really, haven't seen it in a while
