### ISSUE TITLE
[webcontent] Unable to expand or interact normally with certain webpages, especially when opened as a link in new tab. Have to refresh the page for them to work, otherwise they are broken

### ISSUE THREAD

**Issue by MadridSpain** [mozilla-mobile/fenix#14887]
## Steps to reproduce
1. Set Firefox Day to default settings. Clear all cache/browsing data/etc.
2. In a new session of Firefox, go to Yahoo.com. If Yahoo.com gives you a warning saying that they use cookies, click "Accept".
3. Paste the below URL into a new tab, but during the same session:
https://old.reddit.com/r/fiveg/comments/ipc2mb/test/
4. Load the webpage.
5. Close the Yahoo.com tab you opened in step 2.
6. Go back to the tab from step 4 with the Reddit page.
7. Longpress the hyperlinked Yahoo news article located in the body of the post.
8. Select "Open link in new tab"
9. Wait 10 seconds.
10. Go to your tabs list and select the Yahoo news article.

NOTE: This bug will not occur if you don't first accept the cookie warning from Yahoo. That's why we go to Yahoo.com first, accept the cookie warning, close that tab, then proceed with the process.
### Expected behavior
The webpage should be loaded normally, and I should be able to interact with the webpage like I can on any of my other mobile browsers.
### Actual behavior
The page loads, but it is broken. I can't click "story continues" at the bottom, and I can't click and cycle through the 4 pictures at the top of the article. The only way I can get it to load normally is by refreshing the page.
NOTE: I can not reliably replicate this bug. However, every single time it happens, it only happens with Firefox Day 80.
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No.
### Can you reproduce in Chrome (or other non-Mozilla browser)?
No.
### Device information

* Android device: Samsung S8 (SM-G950FD Smartphone, latest version of Android operating system as of 2020/Sep/09)
* Fenix version: Firefox Day 80.1.2 (Build number 2015761283)

**Comment by liuche** [comment]
Are you able to reproduce this in Firefox Nightly? We have just landed some fixes for pages unexpectedly stopping working.

**Comment by MadridSpain** [comment]
> 
> 
> Are you able to reproduce this in Firefox Nightly? We have just landed some fixes for pages unexpectedly stopping working.

Issue appears to be fixed on newer versions of Firefox.
