### ISSUE TITLE
[Bug] Longpressing on a blank URL bar results in the "paste" option to appear at the very bottom of the screen, and with no keyboard

### ISSUE THREAD

**Issue by MadridSpain** [mozilla-mobile/fenix#14888]
## Steps to reproduce
1. Set Firefox Day to default settings. Set your homepage to blank/nothing.
2. Clear all browsing history/cache/cookies/etc.
3. Open up a new blank tab in Firefox.
4. Longpress the empty URL bar of the new tab with one, long, continuous press.
### Expected behavior
About one second after longpressing, the "paste" option should appear near your finger. Additionally, your keyboard should pop up.
### Actual behavior
The "paste" option shows up at the very bottom of the screen, and the phone's keyboard never shows up. Screenshot:
https://imgur.com/a/hoDaqg0
### Device information

* Android device: Samsung S8 (SM-G950FD Smartphone, latest version of Android operating system as of 2020/Sep/09)
* Fenix version: Firefox Day 80.1.2 (Build number 2015761283)

**Comment by ekager** [comment]
Could you possibly download Nightly and see if you're still seeing it there on home? I can't repro
https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by kbrosnan** [comment]
This works for me in Beta and Nightly. Do see it on Release.

**Comment by clientenq** [comment]
Can reproduce on day.
Can not reproduce on nightly 

Still unable to move past bar however.

**Comment by MadridSpain** [comment]
I tried it on Nightly. Could not reproduce. The problem happens on Firefox Day.


Sep 10, 2020, 01:47 by notifications@github.com:

**Comment by MadridSpain** [comment]
Problem appears to have been fixed by version 84.1.1 (and actually, earlier versions than that).
