### ISSUE TITLE
PWA startup slower on Fenix

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#14897]
User reported this issue on Reddit:

https://gfycat.com/pleasingunsightlyavians

User phone specs: redmi note 8 and the phone was restarted before every test

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6635)

**Comment by MarcLeclair** [comment]
We think its important to keep since this hasn't been looked at yetl (PWA are pretty important)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807365

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
