### ISSUE TITLE
Can't search for a string that looks like a domain name

### ISSUE THREAD

**Issue by mavit** [mozilla-mobile/fenix#14891]
### What is the user problem or growth opportunity you want to see solved?

Type `foo.bar` into the URL bar.  Hitting enter on the virtual keyboard will navigate you to http://foo.bar.

There doesn't appear to be any way to search for `foo.bar`.  Desktop Firefox and the previous Android Firefox both allow you to do this by clicking on the search engine icon.

### How do you know that this problem exists today? Why is this important?

Users coming from other Firefox versions may expect to be able to do this without having to first navigate to the search engine.

### Who will benefit from it?

Anyone who wants to search for something that happens to look like (or actually is) a domain name.

**Comment by MicroBeast** [comment]
There's a way, but not intuitive.

- Open the New Tab tab to search. IF foo.bar never searched before then click your preffered Search Engine > Type in your Search Subject foo.bar. Notice the magnifier icon in above list complete with your foo.bapr lus name of your preffered Search Engine below it. Just press Enter to continue.
- IF you ever search foo.bar, it seem it goes to history. The search act differently. Now you; Type in the Search Subject foo.bar > Select your preffered Search Engine. Same magnifier icon show up as above.

I know, it's a weird ways. Still it does exist. I preffer Keyword, far more faster.

**Comment by kbrosnan** [comment]
Duplicate #10516
