### ISSUE TITLE
Allow sorting downloads in the built-in download manager

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#14894]
### What is the user problem or growth opportunity you want to see solved?
I would like to sort my downloads by multiple criteria:
- newest to oldest
- oldest to newest
- alphabetically
- reversed alphabetically.

### How do you know that this problem exists today? Why is this important?
When I need to find a recent download, I want to sort the downloads in the built-in download manager by date. When I need to find a download with a certain name, I want to sort my downloads alphabetically.

### Who will benefit from it?
People using the built-in download manager in Firefox (most of the user base, I would guess).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6631)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812804

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
