### ISSUE TITLE
[Bug]refresh page after close 

### ISSUE THREAD

**Issue by Mixerus** [mozilla-mobile/fenix#14907]
I have opened a few tabs www.example1, www.example2, ...
I opened a popup window by window.open in JavaScript in www.example2 , then refresh parent page when I close this popup window by
<script>
    window.onunload = refreshParent;
    function refreshParent() {
        window.opener.location.reload();
    }
</script>

### Expected behavior
refresh page www.example2

### Actual behavior
refresh page www.example2 in adress but it display www.example1. after refresh it is OK

### Device information

* Android device: LG G7 ThinQ
* Fenix version: 80.1.2 build 2015761283

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1665517
