### ISSUE TITLE
[Bug] Keyboard does not raise when new tab button is pressed, causing user to interact TOP-BOTTOM-TOP-BOTTOM of their device

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#14908]
_edit: drastically rewrote report with additional info_

Reporting for another user.

## Steps to reproduce
- Set toolbar on top
- TOP: Click URL bar to open tabs tray 
- BOTTOM: click + button for new tab
- Expected: keyboard raises and can begin typing; actual: keyboard does not raise
- TOP: click URL bar to raise keyboard
- BOTTOM: keyboard

### Expected behavior
There are two issues:
1. The new tab button is at the top (dupe #14403?)
2. The keyboard raises when + is pressed

### Actual behavior
There are two issues:
1. The new tab button is at the bottom, which is unintuitive if the toolbar is at the top (dupe #14403?)
2. For this user, the keyboard does not raise when the new tab button is pressed causing them to go TOP-BOTTOM-TOP-BOTTOM

I propose addressing 1) in #14403 and addressing 2) in this issue.

![image](https://user-images.githubusercontent.com/759372/92654077-2787f000-f2a4-11ea-8463-b98ac3aab52e.png)

### Device information

* Android device: OnePlus 7 Pro, Android 10
* keyboard: gboard
* Fenix version: release (80?)

**Comment by yoasif** [comment]
Like https://github.com/mozilla-mobile/fenix/issues/14403

See also https://github.com/mozilla-mobile/fenix/issues/14909

**Comment by mcomella** [comment]
Thanks for the info, yoasif. I updated the first comment with additional info I learned which makes it slightly different than #14403 so I'd propose leaving this open.

**Comment by mcomella** [comment]
> Fenix version: release (80?)

I've been told this is working correctly in Nightly – perhaps we should close as WORKSFORME? I'll check to see if anything is configured differently in the release build and report back though.
