### ISSUE TITLE
[Bug] "scroll to hide toolbar" option does not work (with bottom toolbar)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#14902]
### Steps to reproduce

0. Make sure you have the bottom toolbar enabled
1. Disable the new "Scroll to hide toolbar" option

### Expected behavior

Static toolbar.

### Actual behavior

Still a dynamic toolbar. Since the other new options "Swipe toolbar sideways to switch tabs" and "Pull to refresh" both works I guess the "Scroll to hide toolbar" option is also supposed to work.

With the toolbar on top the option works.

/cc @Mugurell

### Device information

* Android device: OnePlus 7T Pro McLaren / Oxygen OS 10.0.10 (Android 10)
* Fenix version: master branch revision 4de80a0493beb4bb91732e59055da2f4e0e4d319

**Comment by MicroBeast** [comment]
Issue on Youtube Mobile page (m.youtube.com) when Toolbar on Top and Scroll to hide toolbar is off. Youtube Bottom Toolbar will float above what suppose to be Firefox Bottom Toolbar.

Nightly 200910 06:07 (Build #2015763057)
SM-T555, Redmi 4A

**Comment by cadeyrn** [comment]
@MicroBeast Please open a separate issue for other problems with the toolbar.

**Comment by Mugurell** [comment]
Ticket for the page layout issues - https://github.com/mozilla-mobile/fenix/issues/14974

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/16 with Google Pixel 3 (Android 11) and Samsung Galaxy Note10 (Android 10).
