### ISSUE TITLE
[Bug] leganerd.com unbereably laggy on Fenix but not on Chromium browsers

### ISSUE THREAD

**Issue by serovar** [mozilla-mobile/fenix#14915]
## Steps to reproduce
Browse https://leganerd.com/ on Fenix and scroll.
### Expected behavior
Scrolling is smooth.
### Actual behavior
Scrolling lags like hell.
### Device information

* Android device: Pixel 2 XL, Android 11
* Fenix version: Nightly 200909 06:00 (Build #2015762867), and also stable 80.1.2

Smooth on Chrome
![chrome](https://user-images.githubusercontent.com/6732420/92666107-a0209800-f308-11ea-9b7c-98f56ad28372.gif)

Laggy on Firefox
![fenix](https://user-images.githubusercontent.com/6732420/92666251-09a0a680-f309-11ea-8ee9-f5253e022d45.gif)

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1665518
