### ISSUE TITLE
[Bug] New Search Experience Can Become Unusable With TalkBack

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#14910]
## Steps to reproduce
Follow steps from https://github.com/mozilla-mobile/fenix/issues/13467 with TalkBack on
Enable new search experience
click on toolbar and erase query, if any
press enter

### Expected behavior
Can click back into search bar to pop back up keyboard 

### Actual behavior
Can't get keyboard back up, search screen becomes unusable

(A fix for #13467 that would dismiss the search experience or something like that in this case would also solve this)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 9/10 with HTC 10 (Android 8).
I had talkback enabled, was able to delete the URL loaded, the keyboard remained visible, the focus remained on the search bar. I've entered some text, tap on "go" and the search was performed without issues.
