### ISSUE TITLE
Allow users disabling gesture based feature: Tab Tray

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#14911]
### What is the user problem or growth opportunity you want to see solved?

Many people don't like gesture based functionality, as evidenced by https://github.com/mozilla-mobile/fenix/issues/10240. Here, people don't like the tab tray having to be "managed" by using gestures to open and close, to be careful about swiping "too hard" down and dismissing it entirely. In short, they want their tabs at their fingertips without a gesture based overlay.  

I think the way this would work is to expand to the top of the screen and have some way to exit it. 

### How do you know that this problem exists today? Why is this important?

Feedback on Google Play and social media. Important because we are seeing user feedback *and* there are accessibility concerns around gesture based functionality in general. 

### Who will benefit from it?

Anyone who would like to disable the gesture based features of the tab tray.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6646)

**Comment by lime124** [comment]
hi yoasif - i really appreciate you taking the time to file a request to improve our product and i'm sorry you find  using the tab tray gesture difficult. we can definitely take your feedback on the difficulty of the gesture and use that to make improvements to the gesture. fortunately, gestures are not the only way to access the tab tray -  you can also tap on the icon to access it. 

you're right, as per #10240,  there have been explorations on what kind of customization options we may offer on gestures - thanks for your patience as we work through what sorts of customization should be provided while also balancing the overload of too many options.

**Comment by yoasif** [comment]
@lime124 I actually don't have huge issues with the tab tray, I am mostly trying to consolidate feedback I have seen with my own thinking around solutions. 

I will say that although I have generally not have had many issues with the tab tray, one issue has cropped up recently that I have been personally annoyed by - that is, when scrolling through my tabs when I am not aware of being near the top of the list, it is very easy to close the tab tray by accident. 

The clearest instance of this issue is the one I filed here: https://github.com/mozilla-mobile/fenix/issues/14476.

Unfortunately, in playing around with other Android apps that use overlays, this is pretty much how this works - the larger issue is simply that because there is a scrollable list inside of the tray, it is hard for the app to disambiguate between a scroll to top (or scroll up) option from a swipe to scroll. As this is endemic to the fact that this is a gesture based manipulation, the simplest way I could think to solve it was to make the tray essentially not an overlay (like in Fennec) as an option. 

One other thing I will note is that for fast navigation, the overlay breaks the efficiencies observed by Fitt's law -- because the amount of movement, and the precision of movement to move to the top of the tray is so fine, it will result in errors in many cases.   Users have to both quickly scroll to the top but not so quickly that the app misinterprets their movement as a "go away quickly now!" gesture. Otherwise, in order to reduce errors, they must instead scroll slowly. I am not confident that this is easily solvable without resulting in mystery meat navigation. 

Appreciate your attention to this!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807057

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
