### ISSUE TITLE
FNX-5062 ⁃ [Bug]Reload icon is missing

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#1491]
## Steps to reproduce
1. Open a site and stop the site loading mid-way.
1. Open the three dot menu.
    1. Expected behavior
The reload icon is present there and on cicking the page reload action is performed.
    1. Actual behavior
The reload icon is missing from there and cancel icon is present instead and clicking  on it doesn't have any effect.
    1. Device information

* Android device: 8.0.0
* Fenix version: 1.0.1915 (Build #10991206
68.0a1-20190408104625)
Tuesday 4/9 @12:06 PM

**Comment by ekager** [comment]
This is blocked on library work (AC) linked in #654

**Comment by sv-ohorvath** [comment]
This is also happening on error pages, which I think would have the same cause, error pages stoping the pages loading. Will verify this when this is fixed.

**Comment by g1897** [comment]
Once loading a page stopped, you can't reload it apart from tapping the address bar and press enter again. 
Just to be more precise ;)

**Comment by bifleming** [comment]
@vesta0 why is this blocked?

**Comment by Amejia481** [comment]
I think this is already fixed by https://github.com/mozilla-mobile/android-components/pull/3087, QA can verify it.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/3 build. Devices: Galaxy S8 (Android 9), Nexus 5 (Android 6)
