### ISSUE TITLE
[UX] Easy access to bookmarks

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14929]
## User Story
- As a user, I want to easily find, access, and return to bookmarks so I can accomplish what I need faster. 

## User problem

- Many users report not being able to **find** bookmarks and they think we have replaced bookmarks with collections. This is probably because they were used to accessing bookmarks on the homescreen and never actually accessed bookmarks through the toolbar.
- Many users report not being able to easily **access** bookmarks (since it's no longer on the homescreen)
- Many users report not being able to **return** to bookmarks after opening a bookmarked site (if you open a bookmarked site then go back, you will be taken to homescreen and not the bookmark page. 
- The way bookmarks are currently displayed/sorted seem to hinder their usability.

### Acceptance Criteria
- I can do easily and quickly open a bookmarked site (P1)
- I can return to my bookmarks without having to start over (P1)
- My bookmarks look visually organized (e.g. folders show up at the top and look more distinct, folders tree view - see #4203  ) (P2)

**Comment by anotherus3r** [comment]
Still relevant?
