### ISSUE TITLE
[UX] [Meta] Easily share content to another app

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14926]
## User Story
- As a user, I want to easily share content (link, tab, media) to another app, so I can share this content with other people or use it on my other apps. 

## User Problem
Many users are finding **sharing** difficult or taking a long time. Here are the user problems that we want to address:

- Users have trouble finding the share icon and tell us that it's not very noticeable. Some users complain about "partially hidden" share buttons.
- Users want quick access to their most "recently shared to" app so they can share to the same app quickly in less taps.  
- Users may not be noticing the "recently used" section of the share sheet. 
- Users find it inconsistent that tapping on share on the Selection Action Menu opens the native share sheet, whereas everywhere else in the app we surface the custom Fenix share sheet. We should show the same share sheet everywhere and look into which one makes the most sense for our users. 

### Acceptance Criteria
- I can easily share a link/media/tab to another app
- I have quick SHARE ACCESS to an app that I most recently shared to.
- I see the same share sheet no matter where I am sharing from and what I am sharing. 

**Product ask for UX: review feedback and provide recommendations. Please note that we want to make changes that actually improve usability as oppose to copying old behavior to address a temporary aversion to change.**

**Comment by mattschlosser** [comment]
Add:
* Clicking share when long pressing a link on a page and selecting "Share" does not open the same share sheet as going to the 3 dot menu and clicking share. Clicking share from a long press opens the Android share set, where share in the 3 dot menu correctly opens the custom Fenix one.

**Comment by apbitner** [comment]
UX recommendation is @violasong can take a look at the placement of the Share button as she's looking at menu organization in #14320. Otherwise, no changes to the share menu at this time.

#1523 seems like a valid feature request, and I agree with @mattschlosser that all share options within the app should be using the same custom share sheet.

**Comment by Poopooracoocoo** [comment]
#9309

**Comment by rileyinman** [comment]
I personally would advocate for #5935, especially with the recent release of Android 11 fixing most (if not all) main issues with the native share sheet. Along with the addition of Nearby Share, I think it's a good time to look at platform integration. This change would also integrate well with the new proposed menu in #14320, which has mockups with separate "share" and "send to device" buttons (the main resaon Fenix currently uses a custom share menu, as far as I can tell, is to add the ability to send to synced devices). Alternately, or in addition, the issue you mentioned (#1523) would allow for the replication of this feature without the use of a custom share sheet via Android's direct share targets.

If older versions of Android are still considered suboptimal with the native share sheet, then perhaps it could be a conditional build, but using the native UI from 11 forward at least would be an improvement in my opinion.

**Comment by klint** [comment]
I haven't checked whether a bug has already been opened, but the share sheet takes a noticeable time before it is displayed fully (3s on my Redmi Note 7 !). It is also taking longer for that reason.

**Comment by liuche** [comment]
Some of this work is related to the settings consolidation work. When discussing native vs custom share sheet with UX, if we wanted to switch to a native share sheet it would be for technical reasons, custom is fulfilling UX needs rn.

**Comment by kevincox** [comment]
Note that custom is filling some UX needs but native would fill other UX needs (direct share, familiarity, ...)
