### ISSUE TITLE
Users are unable to find "add custom search engine"

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14922]
## User Story
- As a user, I want to know that I can add a custom search engine. 

## User problem
- According to user reviews, users don't know that this feature exists. This feature may be hard to find on a very busy Search settings page and making it stand out more may address this issue. 

### Acceptance Criteria
- I can quickly find the "add custom search engine" feature.

**Comment by yoasif** [comment]
This also used to be more discoverable via this feature: https://github.com/mozilla-mobile/fenix/issues/6315

**Comment by apbitner** [comment]
@vesta0 I propose we make a couple small visual tweaks to see if that helps:

1. On the main settings screen, there is a gray divider above every section header. This is a pattern we'd like to carry over to all settings subpages, including the search settings which will help separate the `Add search engine` button from the section beneath it. We should either include all other subpages as part of this ticket or create a separate one.

2. I've also indented the `Add search engine` CTA to differentiate it more from the list of radio buttons above it. This is also how it appears in Focus (not sure about Fennec).

Figma link: https://www.figma.com/file/RyIADLmC3B0BIS9jSiAti3/Settings?node-id=0%3A1004

**Comment by vesta0** [comment]
Looks good @apbitner thanks!

Let's use this ticket for implementing your 2 recommendations for `Add search engine' listed above. 

Will you please open a separate ticket to indicate your recommended changes for any other subpages?

**Comment by andreicristianpetcu** [comment]
Is this in nightly yet? I can't find ir.

**Comment by liuche** [comment]
Mocks from UX in this comment: https://github.com/mozilla-mobile/fenix/issues/14922#issuecomment-707835602

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both latest **`Nightly Build 201022`** and **`Firefox RC 83.0.0-beta.1`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**► Screenshots**
![rsz_screenshot_202000001022-113222](https://user-images.githubusercontent.com/51314259/96847243-9f2c6b80-145b-11eb-8c0f-1d6fc1bda53d.png)
