### ISSUE TITLE
Tabs Tray CFR Banner for grid view tip

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14920]
## User Story
- As a user, I know that I can switch my default tab view to a grid view, so I could easily make this change if that is my preferred view. 

### Acceptance Criteria
- I am informed of the option to switch to tab grid view, when opening the tab tray for the first time after the grid view feature is available.
- The CFR is not intrusive to my browsing activity.
- I have the option of dismissing the CFR or tapping on the option that takes me to this particular setting. 
- I will continue to see this tip as long as I haven't dismissed or interacted with this tip. 

We can use these [UX mocks](https://app.abstract.com/projects/8afc4b50-7667-11e9-94ba-3558f8596822/branches/cfeee95f-b6fa-4579-842e-5b51f7dd4af2/commits/a3633820b169e4bc6ac37fe927c31d169dcd45d0/files/af6f466c-1a56-494d-ae53-20dd23f8a685/layers/2859F71C-CFB7-4049-8AB9-52B54EECC1FE?mode=build&selected=root-2859F71C-CFB7-4049-8AB9-52B54EECC1FE&sha=a3633820b169e4bc6ac37fe927c31d169dcd45d0) for reference but we will need strings from @betsymi

**Comment by betsymi** [comment]
Change the layout of open tabs. Go to settings and select grid under tab view. 
DISMISS | GO TO SETTINGS

**Question 1:** Since both banners appear in the same location in the tabs tray, does one take precedence?

**Question 2:** Curious if we are collecting telemetry on both banners as well as the tabs settings themselves to help us understand the effectiveness of the messaging.

**Comment by gabrielluong** [comment]
> Change the layout of open tabs. Go to settings and select grid under tab view.
> DISMISS | GO TO SETTINGS
> 
> **Question 1:** Since both banners appear in the same location in the tabs tray, does one take precedence?

The grid view CFR will take precedence and the auto-close will appear once the grid view CFR is satisfied with a position action. They both use the same ranking algo to appear.

> **Question 2:** Curious if we are collecting telemetry on both banners as well as the tabs settings themselves to help us understand the effectiveness of the messaging.

There will be a ticket https://github.com/mozilla-mobile/fenix/issues/16485 regarding telemetry, but not implemented in this issue.

**Comment by softvision-miralobontiu** [comment]
Verified as implemented on the 11/18 Nightly build with the following steps: 
1. Have a clean profile.
2. Open 6 tabs consecutively, making sure the ETP banner isn't triggered.
3. Observe the tabs tray.

The "Change the layout of open tabs. Go to settings and select grid under tab view.
DISMISS | GO TO SETTINGS" was triggered. 
Tapping on "GO TO SETTINGS", opened the Tabs page.
Tapping on "DISMISS", dismissed the banner, and didn't display it again.

Tested with: 
✔️ Samsung Galaxy Tab S6 (Android 10),
✔️ Google Pixel 3a (Android 11),
✔️ Huawei Mate 20 Lite (Android 10),
✔️ OnePlus A3 (Android 6.0.1),
✔️ Google Pixel 4 XL (Android 11),
✔️ Pixel 2 (Android 9), 
✔️ HTC 10 (Android 8), and 
✔️ Xiaomi mi4i (Android 5.0.2).

![image_2020_11_18T08_16_13_799Z](https://user-images.githubusercontent.com/40694158/99509979-2a334f80-298f-11eb-878b-4f3e6eb308be.png)
