### ISSUE TITLE
[UX] Users don't know that they can adjust their browser font size

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14923]
## User Story
- As a user, I want to adjust my browser font size based on my needs so I can use the browser. 

## User problem:
Based on user feedback, many users don't know that they are able to adjust the browser font. This may be due to the fact that the Font Size scale feature is not visible when "Automatic font sizing" is toggled on. Perhaps we can still show a grayed out version of the font size option when "Automatic font sizing" is toggled on.

### Acceptance Criteria
- I know how to adjust my font size.

**Comment by black7375** [comment]
### Simple Solution
A very easy solution exists.

1. Remove option `Automatic font size`
2. Replace `Font Size` with `Font Size Control`
3. When the option is off, disable the slider bar. (darkly)
![Font-Size](https://user-images.githubusercontent.com/25581533/94321373-e28bdb00-ff7e-11ea-8e52-79b25ec8d26a.jpg)

### New menu
Creating a page setup menu.
Similar to Safari's approach.

Pressing the current `Tracking Protection` menu position makes `Text Size`, `Tracking Protection`, `Site Setting`, ..ETC appear.
- Left Menu:  Specify site settings
- Right Menu: Browser-wide Features
![Safari-FontSize](https://user-images.githubusercontent.com/25581533/94321712-ee2bd180-ff7f-11ea-836a-5510c458d866.png)
[Refer Image](https://mcmw.abilitynet.org.uk/making-text-larger-safari-ios-13-iphone-ipad-and-ipod-touch)

You can both apply it. :smile:

**Comment by apbitner** [comment]
@ekager To @black7375's point above, I'm wondering do we really need the `Automatic font sizing` toggle? Could we just have the slider and it would be implied that 100% on the slider is the equivalent of automatic font sizing? Chromium browsers just have the scale, no toggle.

**Comment by ekager** [comment]
Yep @apbitner that would work - so do you want me to move forward with those changes?

**Comment by apbitner** [comment]
@ekager Let's confirm first.

@vesta0 it doesn't seem the `Automatic font sizing` toggle is completely necessary so we propose removing it and just having the slider, which would make this option more discoverable. Sound good?

**Comment by vesta0** [comment]
Let's do it!

**Comment by apbitner** [comment]
@ekager I think we're good to move forward. Let me know if you have any design questions but it should just be removing the toggle and moving up the content beneath.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201012`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

**Comment by ale82to** [comment]
removing automatic font sizing toggle and setting slider to 100 % gives me a very big text, so how can I get same size as before setting to 95 % or 105 % is giving me slightly smaller /bigger text
am I'm missing something?

**Comment by lindongbin** [comment]
it is a bug

**Comment by ekager** [comment]
@ale82to have you changed your system font size setting? 

As mentioned above, 100% means "automatic font sizing" now

**Comment by ale82to** [comment]
yes exactly(my android general setting for font is 130 %).as I commented in another bug report new *semplified setting* is not working as expected because is no longer possible for the user to get both 100 % real font size for web pages and automatic font sizing disabled at the same time. 
having saying that hopefully after many force close of fenix (I ve got root) i was able to get *old, real 100 % * for webpages (setting slider to 100 %)

**Comment by ale82to** [comment]
or in other words
100 % in slider (new semplified setting) MUST means real 100 % font size for webpages regardless of android setting for font size.
if the user want bigger font can just use the slider otherwise there 's no way to get real 100 % font size for web content.

**Comment by ale82to** [comment]
As mentioned above, 100% means "automatic font sizing" now SERIOUSLY? 
100 % must disable automatic font sizing
or please tell me how to *old*behavoiur :100 % real font size for webpages and automatic font sizing disabled at same time.
