### ISSUE TITLE
[Bug] Executing getUserMedia in iframe results in "Failed to allocate videosource"

### ISSUE THREAD

**Issue by bert-and-ernie** [mozilla-mobile/fenix#14932]
Trying to execute getUserMedia with `video: true` in iframe always results in a `Failed to allocate videosource` since version 79 of Firefox on Android.

## Steps to reproduce

1. Open https://jsfiddle.net/jib1/r60bzmrs/
2. Allow camera permission

### Expected behavior
See yourself in view

### Actual behavior
`NotReadableError: Failed to allocate videosource`

### Device information

* Android device: 
 LG G7 with Android 10
 Huawei P30 Lite with Android 9
 LG G6 with Android 10
* Fenix version: >= 79
Also tested with:
 Beta 81.1.0-beta.2
 Nightly 200910 06:07 (Build #2015763059)

**Comment by kbrosnan** [comment]
This reproduces in desktop Nightly. Sounds like expected behavior to me. Sending to Bugzilla for some experts to have a look.
