### ISSUE TITLE
[Bug] Booking site of my university encounters an error

### ISSUE THREAD

**Issue by leonbohn** [mozilla-mobile/fenix#14937]
## Steps to reproduce

Visit the booking [site](https://buchung.hsz.rwth-aachen.de/angebote/Uebergangsprogramm_2020/_GYM_Trainingsslots.html) and click on any green time slot to book it. 

### Expected behavior

It should lead to a form where you can enter your details like name, email address etc. 

### Actual behavior

I get an error page telling me that something went wrong. With previous versions of Firefox Android I did not have any issues and other browsers also seem to work. 

### Device information

* Android device: Oneplus 6T, Android 10
* Fenix version: 80.1.3

**Comment by hwinnemoe** [comment]
I can reproduce on

- 80.1.2 (Build #2015761281)

I can **not** reproduce on

- 81.1.0-beta.2 (Build #2015761657)
- Nightly 200910 06:07 (Build #2015763057)

**Comment by liuche** [comment]
I also cannot reproduce on Nightly. The Beta should be going out to Release next week, so please re-open or comment if this is still a problem, or if you see it on Nightly.
