### ISSUE TITLE
[Bug]Can't search anything on Google after switching to PB (Having Google Search Fixer installed)

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#14934]
## Prerequisites
Have "Google Search Fixer"  installed and enabled to run in PB

## Steps to reproduce
1. Open Google.com
2. Long tap on "Images"
3. Select "Open link in private tab" from the context menu and **Switch** to the PB tab
4. Tap Google's search box
5. Tap on "All"
6. Tap the search box

### Expected behavior
Steps 4 & 6: The keyboard should be displayed once the search box is tapped 

### Actual behavior
Steps 4 & 6: The keyboard isn't displayed making it impossible to search for anything

### Device information

* Android device:  Google Pixel 3a (Android 10) 
* Fenix version: Nightly 200910

### Notes
► Video
![20200910-113756](https://user-images.githubusercontent.com/51314259/92705610-84df7800-f35c-11ea-83c3-c6412ea6296e.gif)

**Comment by mobd** [comment]
Probably duplicate of #12982

**Comment by AndiAJ** [comment]
Indeed, managed to repro it without the Add-on installed.
Thx @mobd ! ☺️
