### ISSUE TITLE
[Bug] (regression) Weird animation is displayed when closing the active tab (the next tab flashes for ~1 sec)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#14936]
## Steps to reproduce
1. Open 3 or more tabs.
2. Close the active tab.
3. Observe the animation for the closed tab.
### Expected behavior
There should be a smooth animation when closing the active tab.
### Actual behavior
The tab under the last active tab is flashed for ~1-2 seconds after the active tab was closed.
### Device information

* Android device: **Google Pixel 4 XL (Android 11).**
* Fenix version: **Nightly 9/10**

![20200910-122717-1](https://user-images.githubusercontent.com/42831109/92711527-48fae180-f361-11ea-85a3-d338382f2fba.gif)

**Comment by yoasif** [comment]
Still reproducible and looks janky.
