### ISSUE TITLE
[UX] Favicon size consistency 

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#14931]
It appears that throughout the app, some Favicons are very large (e.g. bookmarks and history - making it difficult to sort through and look less clean/organized) and some are too small (top sites and collections - making it difficult to make out what they are). 

The favicon is 24x24dp centered in a 40x40dp box with 4dp corner radius.

Spec for top sites:
![fav-home](https://user-images.githubusercontent.com/353960/74059066-9e47cc80-49e7-11ea-8bb5-705feea25388.png)

Spec for all list items (bookmarks, history, search results):
![List element](https://user-images.githubusercontent.com/353960/75386235-9b067900-58e1-11ea-9696-5e2487217fef.png)

**Comment by apbitner** [comment]
It appears there was an old ticket to make all the favicons appear consistent - [Unify the design of all favicon icons in Fenix #7992](https://github.com/mozilla-mobile/fenix/issues/7992). However, Bookmarks and History were not covered. This ticket should follow-up that work, with the specs in the referenced ticket.

**Comment by sflorean** [comment]
Based on this [comment ](https://github.com/mozilla-mobile/fenix/issues/7992#issuecomment-668585794) the Bookmark and History icons are not fixed by the changes from #7992, checked again on Nightly 9/25. 
@liuche this appears to be in the QA column, do we have something to verify at this point?

**Comment by vesta0** [comment]
@liuche @bifleming  I can't find this issue in JIRA but please note that the work that was done in #7992 only covered top sites and logins and NOT bookmarks and history. Mocks are in #7992.
