### ISSUE TITLE
[Bug] White private browsing icon in settings

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/fenix#14933]
## Steps to reproduce
1. Open settings in light mode

### Expected behavior
Private browsing icon matches other icons.

### Actual behavior
![Screenshot_20200910-012520](https://user-images.githubusercontent.com/6396431/92701304-a9a80100-f304-11ea-99c7-81dccc186774.png)

### Device information

* Android device: Android 11
* Fenix version: Nightly 200910 06:07

**Comment by cadeyrn** [comment]
I didn't verify it but I am almost sure it's a regression from #14699.

**Comment by AndiAJ** [comment]
Reproducible on 82.0.0-beta.1

**Comment by cadeyrn** [comment]
I cannot reproduce in Firefox 82 Beta so I guess it has the same cause as #14939 and it's specific to some devices and/or Android versions. I know there were already similar issues in the past but I don't remember who fixed these issues and how.

**Comment by AndiAJ** [comment]
Reproducible on RC 81.1.2 using a OnePlus A3 (Android 6.0.1)
