### ISSUE TITLE
Option to always show menu/address bar

### ISSUE THREAD

**Issue by gtg947h** [mozilla-mobile/fenix#14943]
### What is the user problem or growth opportunity you want to see solved?

Add an option o always show the menu bar so I don't have to scroll up to see it

### How do you know that this problem exists today? Why is this important?
By using the app and seeing developer notes that not having an option is intended

### Who will benefit from it?
Everyone who doesn't like an auto hiding menu bar

**Comment by hwinnemoe** [comment]
This is already implemented in Nightly 200910 06:07 (Build #2015763057) - currently awaiting a fix for https://github.com/mozilla-mobile/fenix/issues/14902 - and will eventually land in Beta and then the release channel.

**Comment by Mugurell** [comment]
Implemented as part of https://github.com/mozilla-mobile/fenix/issues/10240
