### ISSUE TITLE
[Bug] Cannot enable notifications for Facebook

### ISSUE THREAD

**Issue by SinTan1729** [mozilla-mobile/fenix#14947]
## Steps to reproduce
Try to enable push notifications for Facebook.

### Expected behavior
The should be enabled.

### Actual behavior
The page asks for permission, and when allowed, it just keeps loading and upon forced reload, the notifications are still turned off.

### Device information

* Android device: Redmi K20 (Android 10)
* Fenix version: 200910 06:07

**Comment by kbrosnan** [comment]
Facebook serves a different site to Firefox. It does not have notifications as I recall.

**Comment by SinTan1729** [comment]
It does have notification toggle, but it doesn't work. It used to work with fennec and fenix too upto some point.

**Comment by kbrosnan** [comment]
Are you using the desktop site or changed your user agent? AFIK those were the only way to get Facebook to ask you for permissions. I frequently use m.facebook.com and have never got any sort of request to enable notifications.

**Comment by SinTan1729** [comment]
I'm using the usual m.facebook.com site. Wait, I'll attach a screenrecord.

**Comment by SinTan1729** [comment]
So, I revoked the permissions for recording, and it seems to have enabled the notifications. I'll have to wait to see if it's actually working though.

**Comment by SinTan1729** [comment]
It's working, although clicking on the notification takes me nowhere, just the notification disappears. That's a different issue though, I'll close this one now.
