### ISSUE TITLE
FNX-5063 ⁃ New Fenix strings need updates

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#1495]
I've reviewed the new strings in our [latest Quarantine PR](https://github.com/mozilla-l10n/android-l10n/pull/15) and there are a couple things that need to be fixed before we can expose them to localization:
[ ]<string name="bookmark_created_snackbar">: string ID should be updated, since the meaning of the string is changing
[ ] there are no localization comments for any of the new strings. Please provide those so translators get context for localizing correctly

CC @colintheshots for a fix since he landed those patches

(and CC @Pike so he's in the loop)

**Comment by boek** [comment]
@Delphine I didn't see any strings that were missing descriptions. They might have been added already?

**Comment by Delphine** [comment]
Oh seems like they have been fixed in the meantime :) thanks Jeff!
Closing
