### ISSUE TITLE
Firefox doesnt load website from mobile app

### ISSUE THREAD

**Issue by skick3** [mozilla-mobile/fenix#14953]
## Steps to reproduce
I got an Push-Notification and klick on it.
Firefox opens, but i see the start page und empty address bar

### Expected behavior
The Link/Website loads in Firefox

### Actual behavior
I´ve see the Firefox for Android Startpage

 ### Device information
Android Device: Nokia 8.2 (Android 10), OnePlus 2 (LineageOS 17.1/Android 10), Asus Tablet (Android 6)
App: Firefox for Android 80.1.3

**Comment by liuche** [comment]
Do you have a website that sends this push notification? That would help us repro and debug this issue.

**Comment by skick3** [comment]
> 
> 
> Do you have a website that sends this push notification? That would help us repro and debug this issue.
Hey, it´s  not a website, it´s a android app.
You can find it on
https://play.google.com/store/apps/details?id=de.fcms.webapp.hz

On First Step, you must defined which messages of news do u want. On the Day u get push notifcations for news articles.
When i click on it, firefox opens without loading the article.

**Comment by neatwheat** [comment]
@liuche 
I have the same problem. In case you need more websites for debugging, I observed this issue with notifications from:
https://derstandard.at

**Comment by tausifahmad28** [comment]
@liuche I have the same issue. Website in question : https://top.gg/
