### ISSUE TITLE
Make swipe to delete bookmarks optional

### ISSUE THREAD

**Issue by gtg947h** [mozilla-mobile/fenix#14962]
### What is the user problem or growth opportunity you want to see solved?
Please provide an option to turn off swiping to delete bookmarks

### How do you know that this problem exists today? Why is this important?
I just accidentally deleted a bookmark by swiping.  It is far too easy to do this.  I have no need to easily delete them.  Who deletes bookmarks that regularly anyway?

### Who will benefit from it?
Everyone who doesn't want to accidentally delete bookmarks

**Comment by Poopooracoocoo** [comment]
#15007

**Comment by kbrosnan** [comment]
This was removed in https://github.com/mozilla-mobile/fenix/issues/15362
