### ISSUE TITLE
Show active and failed downloads in the built-in download manager

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#14961]
### What is the user problem or growth opportunity you want to see solved?
List downloads that are in progress or have failed in the built-in download manager. For active downloads show their current progress. For failed downloads allow users to retry it from the list.

### How do you know that this problem exists today? Why is this important?
As far as I know, currently only completed downloads are listed under Downloads. When managing multiple downloads, I would like to see their progress in the built-in download manager. If a download fails, I would still like for it to be listed and have the option to retry it.

### Who will benefit from it?
Users downloading files in Firefox using the built-in download manager.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6723)

**Comment by qrqhuang** [comment]
I wish this has make any process ...

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812803

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
