### ISSUE TITLE
[Bug] Youtube Mobile page bottom toolbar float when Toolbar on Top and Scroll to hide toolbar is off.

### ISSUE THREAD

**Issue by MicroBeast** [mozilla-mobile/fenix#14974]
## Steps to reproduce

1. Set Toolbar on top.
2. Turn off Scroll to hide toolbar

### Expected behavior
Youtube bottom toolbar stay where it suppose to be.

### Actual behavior
Youtube bottom toolbar stay where it suppose to be.

### Device information

* Android device: SM-T555, Redmi 4A
* Fenix version:
Nightly 200910 06:07 (Build #2015763057)
Nightly 200911 06:01 (Build #2015763249)

![Screenshot_20200911-135829](https://user-images.githubusercontent.com/19607487/92881651-60a59900-f439-11ea-993c-c0b16976e87b.jpg)

Edited: Sorry, mixed up the actual and expected behaviour.

**Comment by MicroBeast** [comment]
Fixed. Thank you.

**Comment by SL-Lee** [comment]
The fix for this issue added a bottom margin to fullscreen videos, which is a possible regression.

**Comment by Mugurell** [comment]
> Possible regression caused by the fix for this issue: a bottom margin is added to fullscreen videos when toolbar position is set to the bottom and "Scroll to hide toolbar" is set to off.
> 
> Screenshot:
> 
> ![](https://user-images.githubusercontent.com/45960387/93013661-18bf7700-f5dd-11ea-92b5-345370bb886b.jpg)
> 
> CC @Mugurell

Thanks!
Fixed in https://github.com/mozilla-mobile/fenix/issues/15272

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/28 with Xiaomi Redmi Note 8T (Android 9) and Samsung Galaxy Note10 (Android 10).
