### ISSUE TITLE
in dark mode and enable dark reader need remove a flash white screen

### ISSUE THREAD

**Issue by spphinslove** [mozilla-mobile/fenix#14976]
### What is the user problem or growth opportunity you want to see solved?
flash screen are bad for eyes.
### How do you know that this problem exists today? Why is this important?
I just tryed
### Who will benefit from it?
everyone use dark mode.

![Gif_20200911_170105](https://user-images.githubusercontent.com/11383988/92899352-4d062c80-f451-11ea-8833-016712c35d27.gif)

**Comment by Dunexus** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/6313
