### ISSUE TITLE
Missing passwords after update

### ISSUE THREAD

**Issue by Azuus** [mozilla-mobile/fenix#14978]
## Steps to reproduce
Hello. After a recent update to your browser, I lost all my saved passwords except for my FireFox account password. How do I recover my passwords? I apologize if you do not understand something because I am Russian and do not know English I use a translator

### Device information

* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment]
Did you use Master Password (Primary Password) in the old version of Firefox for Android?

**Comment by Azuus** [comment]
> Did you use Master Password (Primary Password) in the old version of Firefox for Android?

Yes

**Comment by Azuus** [comment]
> 
> 
> Did you use Master Password (Primary Password) in the old version of Firefox for Android?

???

**Comment by Azuus** [comment]
will I get an answer? :(

**Comment by kbrosnan** [comment]
There will be a setting to recover the master password data in 81. Duplicate of https://github.com/mozilla-mobile/fenix/issues/13926
