### ISSUE TITLE
[Bug] It doesn't show the saved user and password data, in particular sites

### ISSUE THREAD

**Issue by ucanzeee** [mozilla-mobile/fenix#14971]
## Steps to reproduce
I input the https://giris.donanimhaber.com/login?returnUrl=https%3a%2f%2fmini.donanimhaber.com%2f at firefox address bar and it doesn't show saved passwords
### Expected behaviour
It must just input the user and password data when i go to login page, and if there is more than one user data, it must show the other users saved when clicked on username for example. The particular site for example is: https://giris.donanimhaber.com/login?returnUrl=https%3a%2f%2fmini.donanimhaber.com%2f

But, on another browser this site shows saved user data and inputs them automatically.

### Actual behavior
Nothing. Just blank user data. It doesn't return saved user data. 

### Device information
Genera mobile gm 9 pro android 9.0
Latest firefox for android(11.09.2020)

**Comment by liuche** [comment]
This has been fixed in #5551 and will be in the next update!
