### ISSUE TITLE
add "close other tabs" to long pressing tab switcher 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14972]
as title add "close other tabs" and switch between two last used tabs to long pressing tab switcher for example Samsung internet has this feature when long pressing tab.

**Comment by yoasif** [comment]
This seems far too destructive to put into that menu. The Samsung Internet-like option already exists in the tab tray, FYI.

**Comment by gtg947h** [comment]
I'd like this option  too, at least until the problems in #11449 , #5865 , and #13920 are fixed.  This browser breeds new tabs like rabbits and a five minute browsing session might leave me with seven-plus open tabs despite never selecting "open in new tab"

**Comment by liuche** [comment]
I think we would really have to really think about this because this would destroy all other tabs. The workaround would be to copy the url and close all tabs?

I don't think we'd be adding this, but if we want to revisit this in the future we'll reopen.

**Comment by ale82to** [comment]
well done!
