### ISSUE TITLE
[Bug] Sync Now Button doesn't work

### ISSUE THREAD

**Issue by FuLygon** [mozilla-mobile/fenix#14988]
## Steps to reproduce
Really hard to reproduce because this happen randomly and i don't know when or how it happen, it just happen randomly during normal use, tried uninstall and reinstall the app, setup everything (firefox account, change device name, extension, log in to other sites,...), sync now button still syncing after i completed setting up, but after using firefox for sometime (normal web surfing, bookmarking,...), sync now button just suddenly stop working, well it not completely stop working, it still automatically sync after 10mins, but manual syncing is no longer working, and i have reinstall + setup firefox nightly 5th or 6th times now.
### Expected behavior
Sync Now button is supposed to sync my browsing data.
### Actual behavior
Sync Now button didn't do anything, even when i'm keep spamming it, it doesn't start syncing.
### Device information
* Android device: Xiaomi Redmi Note 7 (rooted) Android 9.0 running MIUI 11
* Add-on Installed: uBlock Origin, Dark Reader, Privacy Badger, Decentraleyes, Search by Image, Video Background Play Fix, Google Search Fixer
* Setting Changed: Turn off voice search, dark mode and bottom toolbar, 95% font size, disable all options in Data Collection, turn on open links in apps and external download manager
* Fenix version: Nightly 200911 06:01 (this also happened on many previous build as well, i wait for a few update hopefully it fixed but no it does not)

**Comment by liuche** [comment]
Does this start working later? I wonder if it could be due to Sync server outages?

**Comment by FuLygon** [comment]
> 
> 
> Does this start working later? I wonder if it could be due to Sync server outages?

I don't know, i keep the app updated for a few day since i post an issue here but it still not working, so i decied to reinstall the app yesterday, i will give it a few day see if this might happen again, right now its working, but this weird bug might happen again

**Comment by FuLygon** [comment]
Here the video: [google drive](https://drive.google.com/file/d/1N3IeYP01t029a8StLS7Tpm5YDveZGk-a/view?usp=sharing) or [youtube](https://youtu.be/74-IyD0seLk)

I leave it automatically sync for 10mins, meaning it still be able to sync with the server, but then i try doing manual sync again and it not working for some reason. Im currently using Nightly 200916 06:01 when i record the video
