### ISSUE TITLE
[Bug] Disabled "Scroll to hide toolbar" option leads to bottom toolbar obscuring snackbars

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#14982]
## Steps to reproduce
1. Have the toolbar placed at the bottom
2. Deactivate "Scroll to hide toolbar"
3. Perform actions that will show a snackbar, e.g. opening tabs from existent tabs or copying text

### Expected behavior
The snackbar is displayed above the toolbar.

### Actual behavior
The snackbar is obscured by the toolbar.

![missing-snackbars-fixed-bottom-t](https://user-images.githubusercontent.com/42788925/92935080-9a31d080-f448-11ea-8192-3bec359d4896.gif)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: 
Nightly 200911 06:01 (Build #2015763249)
AC: 58.0.20200908130811, 52ac53ba1
GV: 82.0a1-20200907094115
AS: 61.0.13

**Comment by hwinnemoe** [comment]
Introduced by #10240

**Comment by Mugurell** [comment]
Eng note: I think we'll need a new Behavior - similar with [BrowserToolbarBottomBehavior](https://github.com/mozilla-mobile/android-components/blob/200fcd74905eff3f9b1672e96b1b0216634d9fe7/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt), but without the scrolling part.

**Comment by B0pol** [comment]
There is no way to directly open in a new tab without this option…

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200922`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by wis775** [comment]
Can confirm, the issued ist fixed in the current nightly.
