### ISSUE TITLE
Twitter Videos very slow to play or pause

### ISSUE THREAD

**Issue by 0xTyagi** [mozilla-mobile/fenix#14987]
## Steps to reproduce
1.  Go to any tweets that contains video.
2. Click on play button. Video plays after 2 to 5 sec.  
3. Click on pause btn. Video pause after 2 to 5 sec
### Expected behavior
Videos Plays or Pause instantly.

### Actual behavior
Video plays after some time and video pause after some time.

On chorme,Bromite it is working as expected

### Device information

* Android device: Android api 25
* Fenix version: Nightly

**Comment by 0xTyagi** [comment]
Add-ons installed: uBo and Search by image

**Comment by kbrosnan** [comment]
What device?

**Comment by 0xTyagi** [comment]
Xiaomi Redmi 4x
MIUI: 11.0.2
Android 7.1.2

**Comment by MarcLeclair** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1667302
