### ISSUE TITLE
[Bug] When "scroll to hide toolbar" is disabled the page's content at the bottom is overlapped by the toolbar.

### ISSUE THREAD

**Issue by georapbox** [mozilla-mobile/fenix#14985]
## Steps to reproduce

1. Go to Settings > Customize
2. Make sure you have the bottom toolbar enabled.

![toolbar_bottom](https://user-images.githubusercontent.com/6596039/92935815-fb11d680-f451-11ea-9402-5466fd34b04b.png)

3. Make sure that "Scroll to hide toolbar" is disabled.

![scroll_to_hide_toolbar_disabled](https://user-images.githubusercontent.com/6596039/92935945-27c5ee00-f452-11ea-8d99-9e9cc91c1204.png)

4. Open a website eg. https://developer.mozilla.org and scroll to the bottom

### Expected behavior

The bottom toolbar should not overlap the page's content at the bottom.

![mdn_scroll_to_hide_toolbar_enabled](https://user-images.githubusercontent.com/6596039/92936089-5a6fe680-f452-11ea-96c4-90443e9956f8.png)

### Actual behavior

The bottom toolbar overlaps the bottom content of the page. Check the links "Terms", "Privacy" and "Cookies", located at the bottom of the screen, that they are overlapped by the toolbar.

![mdn_scroll_to_hide_toolbar_disabled](https://user-images.githubusercontent.com/6596039/92936019-41673580-f452-11ea-9a78-c023969d2398.png)

### Device information

* Android device: Motorola One (XT1941-4)
* Fenix version: Nightly 200911 06:01 (Build #2015763251)

**Comment by Mugurell** [comment]
Should be fixed by the patch for https://github.com/mozilla-mobile/fenix/issues/14974

**Comment by georapbox** [comment]
It seems to be fixed.

Fenix version: Nightly 200914 06:05 (Build  #2015763827)

![Screenshot](https://user-images.githubusercontent.com/6596039/93174331-76b3a200-f736-11ea-9dac-7d4ec6832a28.png)
