### ISSUE TITLE
[Spike] Build the org.mozilla.firefox.cn APK on taskcluster

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#14992]
## Title
Can we build the `org.mozilla.firefox.cn` APK on taskcluster?

## Description
- [ ] Do we have resources to build/do this
- [ ] Where do the builders pull the source code from? https://github.com/MozillaOnline/fenix looks out of date
- [ ] How do we sign these builds
- [ ] Do we need a build variant 

## Deliverables
Description of deliverables, including:
Documentation of investigation results (within the spike ticket, or linked to it), including:
Findings
Recommendations
List of possible user stories to implement recommendations, including estimates
Next Steps
Reach out to Product to go over results of investigation.

Cc to @MihaiTabara

**Comment by rxumoz** [comment]
In fennec we have two different apks: base and google.
For base apk,  we didn't change the package name, we still use _org.mozilla.firefox_
For google apk, we use _cn.mozilla.firefox_

**Comment by st3fan** [comment]
Ideally we would build this variant as part of our current release/beta/nightly flow: next to a set of `org.mozilla.firefox*` builds, all those variants also result in a set of `cn.mozilla.firefox*` builds.

The `cn.*` build will have to be signed with a different key. And will be compiled as a separate variant which enabled/configures region specific features.

**Comment by bli-mozbj** [comment]
I talked with our colleagues on marketing team, since we don't have plan to upload apk to google, we do NOT need cn.firefox.mozilla anymore.
