### ISSUE TITLE
FNX-47 ⁃ Add quick action sheet to custom tabs

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1499]
Per conversation [here](https://github.com/mozilla-mobile/fenix/issues/182#issuecomment-478403491), we will now want to add the quick action sheet in custom tabs too. 

This requires a bit of constraint work since it will need to come down from the top, and we may need a bit of clarification from UX on this behavior.

**Comment by sblatz** [comment]
We'll have to take [transparent app bars](https://github.com/mozilla-mobile/fenix/issues/1621) into consideration if we want to add this functionality, too.

**Comment by mheubusch** [comment]
@brampitoyo can you address this issue or work with Nicole if you need advice/support?

**Comment by lime124** [comment]
@mheubusch - Bram is on PTO this week so @topotropic should take a look tomorrow (wed)

**Comment by topotropic** [comment]
> and we may need a bit of clarification from UX on this behavior.

@sblatz Can you be a little bit more specific about what you need? Thanks!

**Comment by sblatz** [comment]
A couple things we need to consider:

1. Transparent app bars will “show” the quick action sheet behind it. How do we want to handle that?
2. The custom tabs don’t collapse currently, when should the quick action sheet collapse? 

@topotropic

**Comment by topotropic** [comment]
1. I was wondering if we need to make the bar transparent, asked a question in https://github.com/mozilla-mobile/fenix/issues/1621
2. The QA bar collapses on scroll, like specified here https://mozilla.invisionapp.com/share/E5RPOSMT7U2#/358519150_Quick_Action_Bar_-_Review

**Comment by sblatz** [comment]
@topotropic and I discussed this and she will be following up with a solution in ticket 😄

**Comment by sblatz** [comment]
@vesta0, @bifleming 

I'm resizing this to a 5. It requires us to create our own `TopSheetBehavior` as Android only provides a `BottomSheetBehavior`. It's not as simple as flipping the gravity, unfortunately.

**Comment by vesta0** [comment]
@sblatz thanks for re-assessing. I changed the priority to P2 meaning that we still want to do it but it shouldn't take time away from P1s.

**Comment by NotWoods** [comment]
Let's close this since we're removing the quick action sheet.
