### ISSUE TITLE
[Bug] Re-evaluate camera permissions when settings are changed

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#14998]
Follow up to #14239 

## Steps to reproduce
When permission is denied and the prompt appears, go to Settings to change the Camera permission.
Switch Camera permission on.
Return to Fenix and tap the Search Scan again.

### Expected behavior
The notification is not displayed, the QR code scan is launched.

### Actual behavior
The notification still appears after allowing Camera permission.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by eliserichards** [comment]
For QA: see #15097 description for test cases 😄

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 9/18. 
Devices: Pixel 4(android 10), HTC Desire 820 (android 6.0.1), Huawei P20 lite (android 9), Nexus 5 (android 5.1)
