### ISSUE TITLE
[Bug] Back button functionality in url box

### ISSUE THREAD

**Issue by XxJibril** [mozilla-mobile/fenix#14996]
## Steps to reproduce
when researching something in the url box, the app automatically searches in the bookmarks and the history to suggest results, use the back button then

### Expected behavior
in the old version, tapping the back button used to hide the keyboard (which is taking more than half of the screen) to let the user have a full view and freely scroll through the suggestions which is in my opinion what the back button should be doing, only a 2nd back button tap should cancel the search

### Actual behavior
but on the new version, a single tap on the back button completely aborts the search closing down the search/suggestions window and bringing the user to the tab he was browsing before

### Device information
* Android device: Samsung Galaxy A7 (2018), Model: SM-A750F/DS, Android 9.0
* Fenix version: 80.1.3

**Comment by kbrosnan** [comment]
Duplicate #8556

You can dismiss the keyboard by scrolling on the search results.
