### ISSUE TITLE
[Bug] privacy.resistFingerprinting.block_mozAddonManager doesn't work

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#15003]
## Steps to reproduce
1. Create privacy.resistFingerprinting.block_mozAddonManager as a Boolean in about:config and toggle its value to true.
2. Open https://addons.mozilla.org
### Expected behavior
Extensions would work on AMO.
### Actual behavior
They don't. The pref doesn't seem to work at all.
### Device information

* Fenix version: Nightly 200911 14:03 (Build #2015763315)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1664561
