### ISSUE TITLE
FNX-48 ⁃ Design for Switch to Tab

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1500]
### Why/User Benefit/User Problem
History search suggestions from your browsing history and your open tabs look identical. You should be able to visually distinguish between their them and their operation. 

### What / Requirements
* [x] Use ~~icon and~~ text to identify that selecting the suggestion from your open tabs will switch you to that open tab. "Switch to tab"
* [x] #8200 File a follow-up issue for adding icon (which was removed due to scope).
* [x] Implement this feature in a-c ([link to a-c issue](https://github.com/mozilla-mobile/android-components/issues/5771))

### Acceptance Criteria (how do I know when I’m done?)
If I start searching for a tab that I already have open and I see an entry for it that indicates that selecting it will switch me to that open tab.

**Comment by mheubusch** [comment]
@Verdi will you provide the needed UX feedback or do i need to assign it to someone else?

**Comment by Verdi** [comment]
I’ll do it.

**Comment by Verdi** [comment]
![switch to tab](https://user-images.githubusercontent.com/107992/56322020-88ea7480-612d-11e9-916d-b5553d139928.png)

Let's use the tab switcher icon without a number along with the copy "Switch to tab". The icon should be 12dp square with 4dp between it and the Switch to tab text.

**Comment by mheubusch** [comment]
@AmyYLee @shorlander FYI - moving this to Ready for Design Review. Thanks @Verdi

**Comment by vesta0** [comment]
@mheubusch could you please confirm that we are still doing this? I know there is some work happening around re-designing tab management and I want to make sure we have the most up to design direction from UX before working on it.

**Comment by vesta0** [comment]
@shorlander are we implementing this?

**Comment by shorlander** [comment]
> @shorlander are we implementing this?

Yeah, I think this still makes sense but itwould probably be best if we roll this into the ongoing Collections / Multi-tasking work to properly spec out how it should work with Tabs in various states.

**Comment by vesta0** [comment]
Thanks @shorlander 

I am going to add the label `waiting` to indicate that this is not ready for engineering until the Collections/Multi-tasking UX work is completed.

**Comment by topotropic** [comment]
I talked to Stephen, we can roll it out as specified by Verdi. @vesta0

**Comment by sblatz** [comment]
Is this supposed to be in the awesome bar suggestions? 

It looks like the "Switch to tab" text would replace the "description" text (the greyed out portion underneath the title) where we usually put a URL. Is that right?

@topotropic 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/66588692-da564800-eb41-11e9-9734-852adb057786.png">

**Comment by topotropic** [comment]
Yes, it replaces the URL, it's consistent with what we have on desktop. Please correct me if that's wrong @Verdi

**Comment by vesta0** [comment]
We won't be adding the image in this ticket.

**Comment by Madis0** [comment]
How about adding the tab icon as a badge to the favicon/index letter itself? That would look more like the new autocomplete on the desktop.

**Comment by Poopooracoocoo** [comment]
one thing i wish mobile browsers let me do is search tabs. is there an issue for that? i'd upvote the hell outta that lol

**Comment by softvision-miralobontiu** [comment]
Verified as fixed: the "switch to tab" text is displayed under the title when is more than one tab opened.
Tested on the latest Nightly from 2/10 with Google Pixel (Android 10), and Huawei P9 Lite (Android 7).

**Comment by Poopooracoocoo** [comment]
hey guys. not sure if anyone will see this or will care but it would be great if you could star a similar Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1043372

**Comment by andreicristianpetcu** [comment]
@Poopooracoocoo this has been on desktop Firefox since forever. Maybe open a new feature request for Fenix rather than comment on a closed issue.
