### ISSUE TITLE
Allow sending to other Firefox instances

### ISSUE THREAD

**Issue by cormacltighe** [mozilla-mobile/fenix#15000]
### What is the user problem or growth opportunity you want to see solved?

It used to be that when I shard a link from another app and selected Firefox, I was offered multiple options. One of them was to send the link to Firefox on other devices. Now, sharing a link to the Firefox app only opens it in a tab, and I have to select share from there to send it to another device. Please add back the earlier functionality.

### How do you know that this problem exists today? Why is this important?

I frequently used the ability to send a link to another device as a convenient way to remind myself of things, or to send links that I know work poorly on mobile devices or greatly benefit from larger screens.

### Who will benefit from it?

I will, as well as anybody who used this now-removed functionality.

**Comment by kbrosnan** [comment]
Duplicate #1523
