### ISSUE TITLE
81b [Bug][crash] IllegalArgumentException  Selected session must exist

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#15008]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9527493/?query=is%3Aunresolved%20selected%20session

Showing up in 81 beta
```
    mozilla.components.browser.session.storage.SessionStorage in save at line 6
    mozilla.components.browser.session.storage.AutoSave$triggerSave$1 in invokeSuspend at line 10
    kotlin.coroutines.jvm.internal.BaseContinuationImpl in resumeWith at line 3
    kotlinx.coroutines.DispatchedTask in run at line 21
    kotlinx.coroutines.scheduling.CoroutineScheduler in runSafely at line 1
    kotlinx.coroutines.scheduling.CoroutineScheduler$Worker in run at line 11
```
* Android device: several
* Fenix version: 81.1.0-beta.2

**Comment by liuche** [comment]
@pocmo is this a result of the session refactor? This is the main new crasher in the late 81 betas.

**Comment by pocmo** [comment]
I'll look into this. At first I thought this could have been fallout from the state serializer rewrite (https://github.com/mozilla-mobile/android-components/issues/7886), but that should only be in Nightly.

**Comment by pocmo** [comment]
Okay, this is related to https://github.com/mozilla-mobile/android-components/commit/9e60a62119e4d0cb352642940faaec9da00fe1e1#diff-7f956dea6e47f09f743dfe9d482f199d, which is in AC 57+.

The exception is coming from here:

```
        if (state.normalTabs.isEmpty()) {
            clear()
            return true
        }

        if (state.selectedTabId != null) {
            requireNotNull(state.selectedTab) {
                "Selected session must exist"
            }
        }
```

... which is interesting. We have a non empty list of tabs and we have a selected tab id that is NOT in that list. 🤔

**Comment by pocmo** [comment]
As a workaround I think we will clear the tab id before persisting if we hit this problem. That will avoid the crash. But I'll also file an AC issue to investigate how we can end up in this state.

**Comment by pocmo** [comment]
@liuche I have a patch for this that I'll land in AC `master`. Do you want to uplift this? Maybe too late?

**Comment by liuche** [comment]
This seems like a pretty small fix, do you think it's pretty low-risk? We'll be cutting another AC release anyway to pick up GV 81 RC2, so if this seems small, I would like to get it uplifted so it goes out in the next stage of release rollout :)

**Comment by pocmo** [comment]
The patch didn't apply cleanly to the 57 branch, so I decided to not take it for 57.0.6.
