### ISSUE TITLE
Top sites second row disappears when removing a site

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#15014]
## Steps to reproduce
1. Have 5 or 13 top sites (so that you have 4 site on the top row and one on the bottom).
2. Remove one.

### Expected behaviour
 - All is good. Top site is removed.

### Actual behaviour
- The bottom row of the top sites view disappears.

<img width="517" alt="Screen Shot 2020-09-11 at 9 30 36 PM" src="https://user-images.githubusercontent.com/1370580/92984175-4b9b2b00-f476-11ea-8d61-ed87a167f905.png">

### Device information

* Android device: Android 9, Pixel 4
* Fenix version: 

> Nightly 200911 14:03 (Build #2015763315)
> AC: 58.0.20200910190642, edd37a868
> GV: 82.0a1-20200908095243
> AS: 61.0.13

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6800)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813649

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
