### ISSUE TITLE
Allow selection despite the value of the `user-select` CSS attribute

### ISSUE THREAD

**Issue by mvysny** [mozilla-mobile/fenix#15015]
### What is the user problem or growth opportunity you want to see solved?

This would be a very handy thing to have. Imagine a web page, badly written, using `user-select:none`, but containing a mail tracking number: a long trail of characters and numbers. Despite the `user-select`set to `none`, you would still wish to select the tracking number in Firefox, so that you can paste it into the mail tracking application.

I'm thinking either:

* always being able to long-touch a text and select its contents, despite having `user-select` to none, or
* activating a selection mode in the main menu via a switch. The selection mode would enable me to select anything, despite of `user-select` being set to `none`.

### Example

https://www.webfx.com/blog/images/assets/cdn.sixrevisions.com/demos/disable-text-selection/index.html

All text should be selectable on this page, regardless of the value of `user-select`.

Reproduced on: Firefox Android 80.1.3

### How do you know that this problem exists today? Why is this important?

It's annoying for the user if he can't select a text. The user doesn't know that the page prevented him from doing so (nor is he able to learn that) - he will simply blame the browser for not showing the selection dialog. He will blame the UI for being "non-responsive".

### Who will benefit from it?

All users - improves product usability.

**Comment by liuche** [comment]
We're adhering to web standards, and so we wouldn't be able to implement this.

**Comment by mvysny** [comment]
I am sad to see the web standards adherence being more important than the UX improvement, in this particular case where the web standard adherence importance is minor IMHO.
