### ISSUE TITLE
add an option to automatically open android intents in their app

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15019]
### Who will benefit from it?

which may mean opening an open with sheet. this would pair well with the current open in app option. extensions like External Video Player use android intents. you currently have to click on the open in app menu item. 

(and woah it's hard to sideload extensions. debugging...)

**Comment by liuche** [comment]
Is this through website links? What about the Open In App setting isn't working well?

**Comment by Poopooracoocoo** [comment]
@liuche iirc i made this after installing External Video Player. i honestly can't be bothered installing it again as it's only temporary.

**Comment by Poopooracoocoo** [comment]
@liuche now that you can sort of install (up to 25) extensions with AMO collections in FF Nightly, I was able to install the extension again. **The Open In App setting has no affect!** 

Steps:
1. Install External Video Player
2. Go to https://googlechrome.github.io/samples/media-session/video.html
3. Play video to let it load and then pause (pausing not required but it's convenient)
4. Go to menu and then add-ons and then tap on play video externally

this opens a new tab with the android intent with which you must then go to the menu and then tap on open in app.

**Comment by Poopooracoocoo** [comment]
@liuche just as a follow up, were you (or anyone else) able to repro?

**Comment by Poopooracoocoo** [comment]
99% sure that this wasn't fixed. I've been using Samsung Internet for playing videos now.
