### ISSUE TITLE
Issue with position on a page when selecting a word 

### ISSUE THREAD

**Issue by helperman** [mozilla-mobile/fenix#15016]
When I select a word a position on a page changes.
Chrome behaves well in this scenario, so its not a site-specific issue. 
Steps to reproduce
https://youtu.be/aDQLiJkraMg
Test page
http://braille.su/braille-font.php

Nightly 200912 06:01 (Build #2015763443)

**Comment by liuche** [comment]
Can you try this on the latest Nightly 9/16? I tried selecting text like in the video but I don't see the page jump - it stays in the same place.

**Comment by helperman** [comment]
No issue on the latest build
