### ISSUE TITLE
Load pages automatically right after a connection is re-established

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1502]
### Why/User Benefit/User Problem
This allows users to have a better browsing experience having to deal less with error messages. It saves times too.

### What / Requirements
Reload pages as soon as the device is successfully connect to the internet again.

### Acceptance Criteria (how do I know when I’m done?)
A page is automatically reloaded after a lost connection is re-established.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6815)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808746

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
