### ISSUE TITLE
For each collection there should exist a tab inside tab tray (like it is for private tabs)

### ISSUE THREAD

**Issue by Matth7878** [mozilla-mobile/fenix#15026]
### What is the user problem or growth opportunity you want to see solved?
Collections are not sufficiently exposed and are not leveraged enough into UI to be a great feature. They are mainly perceived as a kind of bookmarks which are restored without refreshing.

IMHO they need : 
- to be clearly considered as saved sessions / tab group
- and for that to have each collection having it's own tab inside tab tray along normal tabs and private tabs => and not mixed in normal tabs list
- in the future it would make possible to add specific action in tab tray context menu like a menu to trigger a refresh of all tabs from a collection

This issue is somewhat related to #10372

### How do you know that this problem exists today? Why is this important?
Today collection seems like just a way to bookmark and it might be annoying for user that when opening page is not refreshed.
Making these change will clearly display collections as something different than bookmarks. It would also be more comprehensible that going back to a tab from a collection do not trigger a refresh.

### Who will benefit from it?
Users who needs / wants saved sessions or tab group feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6830)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812742

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
