### ISSUE TITLE
Add pinned badge for default top sites (Pocket, Wikipedia, YouTube)

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15027]
Default top sites (Pocket, Wikipedia, YouTube) currently don't have the pinned badge.

**Comment by gabrielluong** [comment]
Talked to @vesta0 and @topotropic and it was decided we only want the pinned badge for manually pinned sites.

**Comment by yoasif** [comment]
Why? This is inconsistent with desktop *and* it is confusing. Should these be removed from desktop as well? @vesta0 @topotropic?
