### ISSUE TITLE
[Bug] getUserMedia camera NotFoundError: The object can not be found here

### ISSUE THREAD

**Issue by Avijobo** [mozilla-mobile/fenix#15023]
## Steps to reproduce
visit https://mozilla.github.io/webrtc-landing/gum_test.html and click camera button

### Expected behavior
Should prompt for using the camera

### Actual behavior
Returns: NotFoundError: The object can not be found here

### Device information
Samsung S20+, older devices: Samsung Note 4, Motorola Moto G

* Android device: 10
* Fenix version: 80.1.3 (Build #2015762835)

**Comment by Avijobo** [comment]
Update: also happens on recent Samsung and Xiaomi devices... to summarize: there is no camera detected in Firefox Android on these devices,  so webrtc based sites cannot have video capturing... please have a look into this!

**Comment by kbrosnan** [comment]
Does this happen on [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

**Comment by Avijobo** [comment]
Yes, just tried with Samsung Galaxy S20+ on Nightly 201006 (build #2015768139), no camera is detected. Same problem on https://test.webrtc.com. Works fine on Chrome Android.

**Comment by Go-rom** [comment]
Hello,

what's the status about this bug please ?

I'm encountering the same issue : 
Android 6.0.1 - Firefox 85.1.2
Camera Permission is enabled through android settings

Firefox doesn't even ask for camera permission. Audio is working well (Firefox does ask permission for that)

**Comment by Amejia481** [comment]
I wasn't able to replicate on Pixel 3 with Android, QA team could you please help us to verify.

**Comment by sflorean** [comment]
@Amejia481 we weren't able to reproduce this issues on latest Nightly build on the following devices:
- Samsung Galaxy S7 (7) 
- Samsung Galaxy S10+ (10)
- Google Pixel 4 XL (11)
- Samsung Note 10 (Android 10)
- Nexus 5 (Android 6.0.1) 
- Motorola Moto G6 (Android 8)
- Motorola Nexus 7 (Android 7.1.1)

@Avijobo do you have any additional steps?

**Comment by Avijobo** [comment]
Well, it depends on the Android device used. It definitely does not work on Samsung Galaxy S20+. Just tried once more with the latest Nightly. This is the error I always get when clicking the camera button: 

![Screenshot_20210211-102831_Firefox Nightly](https://user-images.githubusercontent.com/19517290/107620360-d914be00-6c54-11eb-8d95-cccc0e64f367.jpg)

**Comment by Go-rom** [comment]
Hello

new tests on my side with the last Firefox nightly

Samsung Galaxy A3 2015 (Android 6.0.1) : not working
Samsung Galaxy A5 (2016) (/E/OS 0.13-2020120789008 based on Android 9) : not working

not working = i'm getting the same error as @Avijobo 

Permissions checked under Android settings

**Comment by Amejia481** [comment]
@Go-rom @Avijobo  would you mind checking under the Android permission settings if Firefox Nightly has the camera permission granted or denied ?

![image](https://user-images.githubusercontent.com/773158/107648625-8cc48080-6c4a-11eb-8ca2-65e89c661940.png)


If it's denied, then grant it and see if it works after, thanks in advance!

**Comment by Avijobo** [comment]
Permissions are granted. As far as I understand, FF does not even recognize that a camera is present. I think permissions are only considered after a camera is detected.

![Screenshot_20210211-153022_Permission controller](https://user-images.githubusercontent.com/19517290/107650184-7f28ee00-6c7e-11eb-813f-5f1e243008ed.jpg)

**Comment by Go-rom** [comment]
Permissions are granted

**Comment by Amejia481** [comment]
Thanks to both, that info it's really helpful!

**Comment by Go-rom** [comment]
Well, i can't explain it on my side but it's working now.
I just gave another shot on both phones (A3 and A5), the camera test on https://mozilla.github.io/webrtc-landing/gum_test.html is working, without any changes on my side.

@Avijobo could you please try again ?

**Comment by Avijobo** [comment]
Still the same problem here. Since I made this bug report in September, I tried almost every day, each time after a new Nightly build or an S20+ firmware update... I never have had success so far... always the same 'camera not found' error. In contrast with what you seem to have experienced, I also never have gotten a permission request for using the camera. The microphone works as expected.

**Comment by Go-rom** [comment]
@Avijobo Could you give a try with Fennec ? (you'll find it through F-Droid app store)

**Comment by Avijobo** [comment]
Fennec is an Android app I suppose? All apps work with my S20+ camera, also Chrome, Vivaldi, etc... it is just Firefox that doesn't recognize my camera.

**Comment by Go-rom** [comment]
Fennec is Firefox without telemetry. (Android app)

12 févr. 2021 9:17:07 AM Avijobo <notifications@github.com>:

**Comment by cadeyrn** [comment]
> Fennec is Firefox without telemetry. (Android app)

Nope. Fennec ist Firefox from the F-Droid store. There are a few differences to the original Firefox. But telemetry is optional in the original Firefox as well. Please don't confuse people with false statements.

**Comment by Go-rom** [comment]
> > Fennec is Firefox without telemetry. (Android app)
> 
> Nope. Fennec ist Firefox from the F-Droid store. There are a few differences to the original Firefox. But telemetry is optional in the original Firefox as well. Please don't confuse people with false statements.

Hello @cadeyrn 
I'm sorry, i didn't intend to confuse anyone. This statement comes directly from the description provided by F-Droid.
From what you're saying, it seems to be a source of disagreement that i wasn't aware of, be sure that i don't mean to show some lack of respect towards Firefox people and project.

A friend of mine told me that he solved the same issue by using Fennec, i don't know what it's worth but it costs nothing to give a try and we're just trying to find a solution since QA team wasn't able to reproduce the bug.

**Comment by Photogad** [comment]
I am also having this issue, for many months now. Camera was working fine last year, but got broke at some point with either an Android OS update or a Fenix Update. Can't do any video calls, telemed appointments, nothing.

Chrome works fine. Fenix does not.  

![Screenshot_20210917-121403_Iceraven](https://user-images.githubusercontent.com/18505956/133821344-dcf2db10-e7f7-43b9-b511-4158d3034f32.jpg)
![Screenshot_20210917-121518_Chrome](https://user-images.githubusercontent.com/18505956/133821346-b321b9bc-7cbc-406e-9ed4-08b81c65d851.jpg)

Chrome always asks for camera permission. Fenix sometimes asks for camera permission (and doesn't work when I grant it), but most of the time it doesn't ask for permission at all.  Yes, in Android system app settings, permission is granted. Clear cache/data no help. Uninstall / reinstall app doesn't help.

I am using a Samsung Note10+ 5G, Android 11. My wife has same phone, and same problem on hers.  I also tried on a friend's Samsung S20+, same problem. Tried on another friend's Pixel (not sure model), on Android 11, and it worked on that.

Possibly a Samsung device issue? Not sure. But as it is now, cannot use or rely on Firefox as my default browser.

**Comment by mariusvirb** [comment]
Experiencing same issue with Samsung S20+, on gum test website I get exception
![image](https://user-images.githubusercontent.com/78095794/153140861-11f92cab-2ef4-4c46-86f2-d42a6e9707d8.png)
But in my sandbox (with some polyfills described here: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#using_the_new_api_in_older_browsers ) if permissions are not given from phone settings - I will get asked only once, after that I always receive `DOMException: The object can not be found here.`.
It seems `enumerateDevices`, when permissions are granted, displays only `audioinput` (microphone), while `videoinput` is never visible.

Anyone has any ideas?

Browser version - latest, as of time of writing v96.2

Code sample is not really needed, everything can easily be replicated by remote debugging and executing these commands in the console:
`window.navigator.mediaDevices.enumerateDevices().then(devices => console.log(devices))`
`window.navigator.mediaDevices.getUserMedia({ audio: true, video: true }).then(media => console.log(media)).catch(error => { console.log(error) })` - if permissions not granted through os app settings - will get asked once.

**Comment by JuniorTour** [comment]
I run into this error too in Mac Firefox.

The cause is I did NOT give system permission to Firefox from System Preference - Screen Recording.
