### ISSUE TITLE
Removing Bookmark Usage is a Terrible Design Defect[Bug]

### ISSUE THREAD

**Issue by BrendaEM** [mozilla-mobile/fenix#15029]
Previously, Firefox Mobile could use a saved bookmark with only 2 clicks.
Links must be searched for in the new version.
If you care about users, or even the health of the Internet in general, please fix this.

1.) Removing the ability to use saved links further deepens users dependency/addiction search engines.
2.) By making search and links appear the same, hides whether or not the person is on a search engine or their own links, blurring the line between being safe or clicking on untrusted links.
3.) Previously, a user could select a bookmark with only 2 clicks. A search while typing will surly take longer.

Please fix this issuess.

**Comment by liuche** [comment]
We're looking into homescreen improvements in #12065, please follow along there.
