### ISSUE TITLE
The homepage should be deprecated and it's functionalities should be integrated in the tabs menu.

### ISSUE THREAD

**Issue by snakedye** [mozilla-mobile/fenix#15024]
### What is the user problem or growth opportunity you want to see solved?
The homepage is useless and only serves to make the UI more confusing. Things that should be grouped in the same area are now fragmented since the tab menu was added.
![changes](https://user-images.githubusercontent.com/49378990/93000068-d110f080-f4f3-11ea-9842-285f610563b0.jpg)

Examples:

1. Opening a new tab launches the search menu with the new tab underneath. Why? The are recent bookmarks but I don't see them and they should be in the search suggestions to begin with. If I want to cancel my search, I have to go back to the tab menu and search for my tab.

2. Collections and bookmarks.  It would make them more accessible (2 less steps).

3. I don't think the save to collection button is necessary since there are already 2 easy ways to save tabs. It could be a button for bookmarks or collections.

The point is everything should be there.

### How do you know that this problem exists today? Why is this important?
The homepage recently changed in beta. Homepage is redundant and slow down operations.

### Who will benefit from it?
Everyone.

It would make the UI simpler and more efficient, devs would no longer have smash their heads to try to figure out what that homepage should be and it's one less thing to work on.

Maybe not everyone. People who keep the bar on top might suffer but they are a dying breed. Almost every app are moving to the bottom of screen.

**Comment by TheCianinator** [comment]
I could not agree more with all of these points. The current home screen is a confusing and frustrating experience.

**Comment by anotherus3r** [comment]
I feel like this would make the tab tray too clutered.

**Comment by snakedye** [comment]
@anotherus3r 

This would only require one other button on an already empty space of the screen.
