### ISSUE TITLE
FNX3-15609 ⁃ [Bug] Links from Twitter don't open as custom tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1503]
### Steps to reproduce
1. Make Fenix to your default browser
1. open the Twitter app and click on a link

### Expected behavior
Fenix opens a custom tab.

### Actual behavior
Fenix opens in the regular mode.

For comparison: With Fennec als default browser a custom tab opens. And with Fenix as default browsers links in the Google Mail app opens as custom tab.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 2e50d1f65f2d2ad2963c51f658e0db10b543c95d

**Comment by Amejia481** [comment]
AC issue https://github.com/mozilla-mobile/reference-browser/issues/558

**Comment by ekager** [comment]
This is something that has to be fixed from Twitter's side. I am in contact with the Twitter engineers to see if they can figure something out for us, but it may not be a high priority for their team.

**Comment by NotWoods** [comment]
[Fixed in Twitter 8.4.0-alpha.120](https://github.com/mozilla-mobile/reference-browser/issues/558#issuecomment-509900529)
