### ISSUE TITLE
Make Top Sites an Optional feature 

### ISSUE THREAD

**Issue by nigelh747** [mozilla-mobile/fenix#15035]
Make the calculation and population of top sites an Optional Feature.

It should not be a feature that automatically works, that the user can not remove.  The current option of hiding something created is simply an invasion of privacy!

**Comment by clientenq** [comment]
> It should not be a feature that automatically works, that the user can not remove. The current option of hiding something created is simply an invasion of privacy!

What do you mean by this?

**Comment by nigelh747** [comment]
I meant that if Firefox does something it must be because the user requested it.  It must not be because a developer thinks that it would be a nice feature, or because some tracking wants to know what are the top sites.  I switch off telemetry, but I still don't want or need any resources of mine, including battery power, doing anything that I don't want.

I don't want or use top sites.  Instead I use an organised list of bookmarks via the desktop application and synchronised back to an Android device.

**Comment by cadeyrn** [comment]
It is already optional.

**Comment by clientenq** [comment]
The current situation is that top sites only exist if you choose to add a resource to the top sites list.
In the nightly (experimental) build there is an additional feature to show a list of most visited sites, which is only activated when users choose to use it.
The bookmarks are an additional feature where the user can select which resource is on the bookmark list.
Where do you see the user is not in control and you have to use top sites?

**Comment by nigelh747** [comment]
> It is already optional.

Unfortunately that's not true as it's added automatically to the home page without any user ability to remove except to hide it

**Comment by nigelh747** [comment]
> The current situation is that top sites only exist if you choose to add a resource to the top sites list.
> In the nightly (experimental) build there is an additional feature to show a list of most visited sites, which is only activated when users choose to use it.

- That's not the case with the released code

> The bookmarks are an additional feature where the user can select which resource is on the bookmark list.

- unfortunately bookmarks usage involves significantly more key strokes due to a bad implementation with the released code.  The released code gets worse each release at the moment
> Where do you see the user is not in control and you have to use top sites?
-Its automatically populated without user control on the home page

**Comment by cadeyrn** [comment]
> Unfortunately that's not true as it's added automatically to the home page without any user ability to remove except to hide it

I don't get your point. You can either have:

1. only pinned pages (disable the option)
2. only auto populated pages (remove pinned pages via long press)
3. both
4. none

So how exactly it's "not true" that it's optional?

**Comment by liuche** [comment]
There is already a setting in Firefox to turn off frequently visited sites, please see Settings > Customize > Show most visited sites.

**Comment by nigelh747** [comment]
> There is already a setting in Firefox to turn off frequently visited sites, please see Settings > Customize > Show most visited sites.

This setting is not available in the released code.  Therefore please reopen this ticket.

Just hiding the feature, does not stop it working 8n the background.

Please reopen this request

**Comment by liuche** [comment]
It's not "working in the background", the frequent sites as calculated on the device from the history you have visited. If you have no history, nothing will show up.

Top Sites frecency and the setting to disable it are released together - there is no channel where the most updated build has just one but not the other.

**Comment by nigelh747** [comment]
In the released version, there is no configuration ability for top sites with Android Fenic.  You may expect people to be able to see the settings, but if the release code doesn't have it or 8ts disabled as about:config is then tickets like this need to remain open

**Comment by nigelh747** [comment]
Homescreen shows top sites
Menu option to add top sites
Customisation, no way to prevent top sites created
![Screenshot_20200917-094309](https://user-images.githubusercontent.com/70252420/93413931-8237d200-f8ca-11ea-8096-93d67ebf5683.png)
![Screenshot_20200917-094220](https://user-images.githubusercontent.com/70252420/93413932-84019580-f8ca-11ea-985b-2f32abf0387c.png)
![Screenshot_20200917-094207](https://user-images.githubusercontent.com/70252420/93413933-849a2c00-f8ca-11ea-8b5c-c15cdc882b87.png)

**Comment by cadeyrn** [comment]
>  Customisation, no way to prevent top sites created

The first three sites are default top sites. The other two were created by yourself! You can remove all of these by long pressing on the icons. The autopopulating feature does not exist at all in Firefox 80, that's why there is no setting Firefox 80. The feature will be introduced with Firefox 81 and in Firefox 81 there is an option to disable it.
