### ISSUE TITLE
Where can we download newest Firefox For Android except in Google Play?

### ISSUE THREAD

**Issue by zoumi** [mozilla-mobile/fenix#15034]
The version provide by https://www.mozilla.org/en-US/firefox/all/ is a very old version.
I have tried download from :
apkmirror.com
apkpure.com
apkleecher.com
but the SHA1 value of these apk files are different.

**Comment by JoGarWeb** [comment]
Try with Aurora Store, is the same APK from Play Store 
https://auroraoss.com/

**Comment by JoGarWeb** [comment]
If a developer read this, is time to upload APK in this site !! https://www.mozilla.org/en-US/firefox/all/#product-android-release 🙄🙄

**Comment by liuche** [comment]
We're in the process of fixing publishing in [this bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1614763), and starting in Firefox 82 will publish them to the Github pages. Please follow along there, thank you for filing.
