### ISSUE TITLE
Video/stream playback very slow/choppy on certain site(s)

### ISSUE THREAD

**Issue by deliciousnights** [mozilla-mobile/fenix#15031]
Ever since Fenix started as Firefox Android Beta I've experienced slow/choppy video/stream playback on a specific site - chaturbate. As if the stream is played back with a very low framerate (single digits).
Now that it is out of Beta the issue remains unfortunately.
Playback with Chrome is fluid.
And also with the old version of Firefox the playback was fluid.

None of the other video/streaming sites seem to have this issue, so i guess it comes down to some specific encoding used on this one?

Here is a short video to illustrate the issue, where I switch between Firefox->Chrome->Firefox->Chrome:
https://imgur.com/ck6WBsm (sfw)

Initially my guess was due to my old slow phone, but switching to Snapdragon 865+ did not improve it.

## Steps to reproduce

Open any stream on chaturbate and compare to Chrome/old Firefox playback.

### Expected behavior

The stream should be played back with the original framerate.

### Actual behavior

The stream is played back with a very low framerate (1-5 fps).

### Device information

* Android device: OnePlus 3T, ASUS ZenFone 7 Pro.
* Fenix version: 80.1.3 / 81.1.0-beta.2 / I think all earlier Fenix versions, at least since it was in Firefox Beta.

**Comment by MarcLeclair** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1667301

**Comment by deliciousnights** [comment]
This issue is no longer present for me. What is strange is that it has dissipated both from beta and from stable release at the same time. So perhaps the fix was on chaturbate side.
