### ISSUE TITLE
[Bug] Favicons not appearing for some sites

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15033]
## Steps to reproduce
Open Google play Store website
Observe favicon in history/tab history
### Expected behavior
The correct favicon
### Actual behavior

Just the letter P
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
![Screenshot_20200913-045135_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/93006681-fdbd1a80-f57c-11ea-90a4-e51e4cec2fd3.png)

**Comment by ebalazs-sv** [comment]
This issue is reproducible on the latest Nightly 201106 GV 84 from 11/6 with Motorola Moto G6 (Android 8).

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/android-components/issues/10377
