### ISSUE TITLE
HTTP/3 protocol enabled, but quic.rocks says I'm using HTTP 1.1

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#15039]
On **Firefox 81.1.0-beta.2 (Build #2015761657)** if from about:config **network.http.http3.enabled** was set to ***true***, Firefox should use HTTP/3 on all sites that supports it. I tried https://quic.rocks:443/. The results showed that I was using HTTP/1.1. However refreshing the page showed that I was using HTTP/3. Going to about:config and toggling **security.ssl3.ecdhe_rsa_aes_256_gcm_sha384** to ***true*** seemed to show HTTP/3 enabled on quick.rocks on every page refresh, and even new loads. However, toggling this to false again shows the HTTP/1.1 page and on refresh showed HTTP/3. 

### Note

From about:config, I had all **security.ssl3.\*** set to ***false*** except for any rules containing **poly**, **gcm**, **chacha**, these were set to ***true***. I tried experimenting with **security.ssl3.rsa_aes_256_gcm_sha384**(notice the absence of _ecdhe_) and toggling that to ***false*** and reloading https://quic.rocks, and it leads me with an error page, ***Address not found*** which is acceptable and just throwing it out there. I also had **network.trr.mode** set to 3 and **esni** enabled.

First time loading with ***security.ssl3.ecdhe_rsa_aes_256_gcm_sha384*** set to **true**, **network.http.https.enabled** set to ***true***

![Screenshot_20200913-121737_Firefox Beta](https://user-images.githubusercontent.com/51329626/93012422-c9068e80-f58f-11ea-806b-6b7344448fcc.jpg)

First time loading with **security.ssl3.ecdhe_rsa_aes_256_gcm_sha384** set to ***false***

![Screenshot_20200913-123509_Firefox Beta](https://user-images.githubusercontent.com/51329626/93012521-b50f5c80-f590-11ea-972e-8edf14b29cb5.jpg)

Device: Samsung
Android Version: 10

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683261

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
