### ISSUE TITLE
[Bug] ugly shortcut for sites without favicon

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#15043]
![image](https://user-images.githubusercontent.com/14617699/93017207-8bc1f100-f5cf-11ea-9528-957eead3a915.png)

It should look something like this:
![image](https://user-images.githubusercontent.com/14617699/93017341-7f8a6380-f5d0-11ea-8141-49fa47dae4bb.png)

* Android device: 10
* Fenix version: latest

**Comment by eliserichards** [comment]
@532910 what phone are you using? (Galaxy 10, Pixel, etc)

**Comment by 532910** [comment]
https://github.com/LineageOS/android_packages_apps_Trebuchet
OP3T LineageOS 17.1 on Android 10
