### ISSUE TITLE
Separate button for bookmarks on menu/address bar

### ISSUE THREAD

**Issue by gtg947h** [mozilla-mobile/fenix#15045]
### What is the user problem or growth opportunity you want to see solved?

Selecting the bookmarks menu takes a scroll (to get the menu bar to appear) and two taps (menu -> bookmarks--plus, the on screen location of the bookmarks menu item moves depending on whether I'm on the home page or not).
 
It would be nice if there were an option fo a fixed bookmarks button (say, between the tabs button and the menu dots) for direct bookmarks access.  

### How do you know that this problem exists today? Why is this important?

I use bookmarks a lot and it's a lot of wasted tapping and scrolling to access them

### Who will benefit from it?
People who use bookmarks a lot

**Comment by KrowNB** [comment]
I need quick access to my bookmarks like I do on my Windows version of FF. I've been a Firefox user since before ii was Mozilla, in the Netscape days. If this issue isn't rectified soon,  I'm going to have to look for another browser.

**Comment by eliserichards** [comment]
Closing this as it will be addressed by #14929
