### ISSUE TITLE
Add option to close tabs after 2 hours

### ISSUE THREAD

**Issue by ZorroGuevara** [mozilla-mobile/fenix#15042]
Workaround until quitting Firefox with Android launcher will work, see #5865 default Android behaviour is to use "Swipe App off" as a way to quit the Application. Fenix doesn't follow that for now, and we need to do it manually or use the option "After one day".

24h is too long for people who want the default Android behaviour.  Add an option " After 2 hours" so that it'll mimic the Android behaviour without hindering browsing (2h is quite enough time).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6865)

**Comment by jawz101** [comment]
I say remove after swiping away from recents.  I don't care about arbitrary shorter and shorter timeframes

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812910

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
