### ISSUE TITLE
Google new pop

### ISSUE THREAD

**Issue by jofra8** [mozilla-mobile/fenix#15049]
Hi,
How can I rid out this popup from Google (attach) which is always popping, without open a 
Google's account ? Cookies block on Firefox does nothing on issue ...
Thanks !

![Google pops](https://user-images.githubusercontent.com/71228414/93025336-16691700-f5f5-11ea-98ef-bbca70328d0e.jpg)

**Comment by kbrosnan** [comment]
Your report is about support for the desktop version of Firefox. Please ask your question on the support forums at https://support.mozilla.org/en-US/users/auth?next=%2Fen-US%2Fquestions%2Fnew%2Fdesktop%2Fform

Closing as invalid
