### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ahmedelabd** [mozilla-mobile/fenix#15054]
## Steps to reproduce
open any page that has saved login
### Expected behavior
login details shoud be autofilled
### Actual behavior
login details are not filled
### Device information
* Android device: yes
* Fenix version: 

80.1.3 (Build #2015762835)
AC: 54.0.6, cfc360e05
GV: 80.0.2-20200903001900
AS: 61.0.10

**Comment by eliserichards** [comment]
Duplicate of #15062
