### ISSUE TITLE
Support for shortcuts while using a physical keyboard

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#15058]
I'm using Firefox 81.1.0-beta.2 (Build #2015761657). It'd been better if support for shortcuts were implemented while using a physical keyboard. Common shortcuts like **ctrl+i** which initiates quick jump to the search bar, **alt+left** to jump to the previous page, **ctrl+h** for quick history, **alt+right** for next page, **ctrl+w** for closing down current tab, **ctrl+tab** for switching between tabs,  **alt+1/2/3/4..** to open link 1 or 2 or 3 or 4 in a page, **alt+n+1/2/3/4** to open links 1 or 2 or 3 or 4 in a new tab, **alt+n** to switch to the new tab. Something like that. These could really facilitate overall usage on larger phones/tablets. A few of the shortcuts can even be found on the newest version of Chrome for Android.

**Comment by kbrosnan** [comment]
Duplicate #3729
