### ISSUE TITLE
[Bug] FTP directories fail to load

### ISSUE THREAD

**Issue by weirdal3333** [mozilla-mobile/fenix#15057]
## Steps to reproduce
Try going to any FTP directory such as ftp://ftp.dd-wrt.com/
### Expected behavior
Webpage loads and you can navigate through the folders as normal
### Actual behavior
White screen and it doesn't even try to load anything
### Device information

* Android device: Android 10 arm 32 bit
* Fenix version: Nightly 200913 06:02 (Build #2015763633)

**Comment by kbrosnan** [comment]
`ftp:` was intentionally not supported by Android Components. We should verify that this is intentional.

**Comment by cadeyrn** [comment]
It's planned to remove FTP support in Firefox 82 for Desktop (the removal is already delayed tue to COVID-19) so this should be a WONTFIX for Android:

https://www.fxsitecompat.dev/en-CA/docs/2020/ftp-support-will-be-removed/
https://bugzilla.mozilla.org/show_bug.cgi?id=1574475#c27
