### ISSUE TITLE
switch tab

### ISSUE THREAD

**Issue by rsedaghati** [mozilla-mobile/fenix#15059]
Switching tabs is difficult. allow users to change tab by dragging address bar to left or right.
thanks

**Comment by Poopooracoocoo** [comment]
this is already possible and can even be disabled. are you encountering a bug?

**Comment by Otiel** [comment]
Can you elaborate on what is already possible?

**Comment by Poopooracoocoo** [comment]
> Can you elaborate on what is already possible?

swiping on the toolbar to switch tabs. or at least it was possible the last time I used Fenix Nightly.

**Comment by Otiel** [comment]
Looks like it didn't make its way out of Nightly yet.

**Comment by cadeyrn** [comment]
The feature is already available in Firefox 81 Beta so it should arrive the stable release channel soon. :)

**Comment by eliserichards** [comment]
Thank you so much for the feedback @rsedaghati! I'm going to close this bug since the new tab gestures are shipping in the next release. Please file any bugs you see once you get the new experience!
