### ISSUE TITLE
Your Library on the home screen (from iOS version)

### ISSUE THREAD

**Issue by MikelJohnson** [mozilla-mobile/fenix#15051]
### What is the user problem or growth opportunity you want to see solved?
Library items are hard to access
### How do you know that this problem exists today? Why is this important?
It's a highly requested feature (see #14929, #14259)
### Who will benefit from it?
>[Everyone likes a shortcut that gets you quickly to the place you need to](https://blog.mozilla.org/blog/2019/04/16/latest-firefox-for-ios-now-available/)

Note that this is a more specific request than #12271 by distinctly asking for iOS design
![GitHub Logo](https://blog.mozilla.org/wp-content/uploads/2019/04/EN_FirefoxHome_16.png)

**Comment by apbitner** [comment]
Covered in #12065
