### ISSUE TITLE
Bookmarks & History managers should have a search function

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#15055]
Apologies if this is a duplicate but I just noticed the Bookmarks manager doesn't have a search function. The History manager should probably have one too

**Comment by Poopooracoocoo** [comment]
dupe of #10046 #12717

**Comment by eliserichards** [comment]
Thanks for the suggestion @willfs84! I'm going to close this as a duplicate. Feel free to follow along in the other bugs that @Poopooracoocoo listed 😄
