### ISSUE TITLE
[Bug] webp images not supported

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#15050]
## Steps to reproduce
Firefox doesn't seem to announce webp support with it's header.
### Expected behavior
webpage shows smaller/higher quality webp images.
### Actual behavior
I get jpeg files.

HTML test says: webp support no.
But if I open webp images directly, then they are displayed just fine.
### Device information

* Android device: Android 9 oneplus 3t
* Fenix version: release and nightly

**Comment by makotokato** [comment]
@Djfe
Does this mean that HTTP's accept header has no `image/webp`?  As long as I test using Firefox Nightly, accept header has `image/webp`.
If using Nightly, what value of `image.webp.enabled` and `image.http.accept` in `about:config`?

**Comment by kbrosnan** [comment]
Is this specific case you are encountering no webp images on Facebook?

**Comment by Djfe** [comment]
Sorry I forgot to answer.
image/webp is actually part of the http header, according to https://request.urih.com/

https://html5test.com/ says webp isn't supported.

I can't test for webp images on Facebook since I can't download images on there due to Facebook blocking long press on images.
(I don't know of which format they are)

I was using heise.de, a page that serves webp to chrome but only jpg to Firefox.
This might be due to a comparison of the user agent. When I created this issue I didn't know of a way to view my clients http request header so I falsely assumed it didn't announce webp support.

**Comment by Djfe** [comment]
ok this is weird and was the reason for my confusion:
Edit: Firefox Desktop actually gets served webp images.
Firefox for Android (release and nightly) gets served jpg images.
https://heise.cloudimg.io/width/1023/q70.png-lossy-70.webp-lossy-70.foil1/_www-heise-de_/imgs/18/2/9/7/7/2/1/8/Corona-App-2035bab4ff6fe555.jpeg

the problem obviously is the fileextension: it says jpeg

Firefox for desktop nightly correctly saves it as a webp file like the content type (http response)

Firefox for Android release also gets the webp file but saves it with the extension "jpeg" (I send it to my pc and opened it in Firefox for desktop and it confirmed: file type webp)

Firefox for Android nightly gets served the jpeg for some reason and then saves it as .jpg

so three issues here: release chooses the wrong file extension on saving (could be fixed in nightly?) 
Nightly gets served a jpg instead of webp.
the html test reports no webp support (bug in the website or in Firefox?)

**Comment by Djfe** [comment]
image how the android release downloads it:
![Corona-App-2035bab4ff6fe555](https://user-images.githubusercontent.com/5685512/94657662-0f831980-0302-11eb-836f-13f86a193cdc.jpeg)

**Comment by makotokato** [comment]
@Djfe

Although I test image at https://developers.google.com/speed/webp/gallery1 using Firefox Nightly, It seems to work. How about this site?  And I would like to know test site for this. If it is about canvas support of webp, see below.

> https://html5test.com/ says webp isn't supported.

The html5test checks whether `canvas.toDataURL('image/webp')` returns `data:image/webp,...`. So this is https://bugzilla.mozilla.org/show_bug.cgi?id=1511670.

**Comment by Djfe** [comment]
Ah, that explains why the test fails.

About Heise.de: I'm just a reader I don't know how they are displaying it. I just noticed: Firefox release gets served webp images, nightly gets served jpg images. (so this might be a regression)

(also: release doesn't check the image extension on saving so it stays jpeg instead of webp)

The title of this issue might be misleading by now, but I don't know what would be a fitting title.

**Comment by Djfe** [comment]
https://heise.cloudimg.io/width/1023/q70.png-lossy-70.webp-lossy-70.foil1/_www-heise-de_/imgs/18/2/9/7/7/2/1/8/Corona-App-2035bab4ff6fe555.jpeg

this is the test site actually
release gets served a 54kb webp file
nightly a 74kb jpg

**Comment by Djfe** [comment]
> If using Nightly, what value of image.webp.enabled and image.http.accept in about:config?
Ups, I forgot to answer that earlier even though I looked it up:
image.webp.enabled is true
image.http.accept is empty

**Comment by liuche** [comment]
Investigate whether GV is sending the correct headers (based on what reporter is saying). Fenix supports loading webp images but we're not receiving them from sites.

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1669541

**Comment by st3fan** [comment]
Copying the response from Bugzilla here:

Firefox on Android supports WebP on all channels - Nightly, Beta and Production.

Don't let the `.jpeg` file extension fool you. This image is server generated and the actual content type (image format) is dynamically chosen.

 - Safari 14 on macOS gives me a JPEG
 - Firefox Nightly (today's) on Android gives me a WEBP image
 - Firefox Release 81.1.2 on Android gives me a WEBP image.

I came to these results by using Remote Debugging over USB, which lets you inspect the network requests and the image.

Closing this with WORKSFORME - if you think the above is not correct, please re-open with more details.
