### ISSUE TITLE
[Bug] Syncserver doesn't work with URL of http:

### ISSUE THREAD

**Issue by simpz** [mozilla-mobile/fenix#15065]
## Steps to reproduce

I have a private syncserver which works will all previous Firefox android versions and all desktop versions. 
Since switching to 80, this version refuses to sync to it. I go through the hit firefox icon 3 times and I can get the "Custom Sync server" setting. I set this to my internal host e.g.

http://internal.lan:5000/token/1.0/sync/1.5`

I use Mozilla for authentication.

Just silently does nothing with this and doesn't sync and either says "Last synchronised: Never" or "1 Jan 1970".

I would try https but not sure a self signed would be any better (can't buy a ".lan" funnanlly enough), and it's unnecessary as this is all on LAN or VPN connected. 

I know this is a browser issue as I have watched the network traffic to the host and it never even tries to connect to port 5000 on the server, and older version on the same device does straight away.

### Expected behavior
Should sync up!

### Actual behavior
Just silently does nothing with this and doesn't sync and either says "Last synchronised: Never" or "1 Jan 1970".

### Device information

* Android device: Android 10  (Lineage 17.1 on PocoF1)
* Fenix version: 80.1.3

**Comment by eliserichards** [comment]
This may be intentional. Definitely needs better messaging here.

**Comment by simpz** [comment]
I have just built a setup with the Sync Server and front ended with NGINX SSL, and a legit cert/name. This has now sprung into life.
So definitely http is no longer working as a syncserver URL. Whether deliberate or not.

**Comment by azban** [comment]
i'm not sure this is an issue with http. i had this same issue with https, and had to change the url to something like: "http://internal.lan:5000/token/1.0" to get it working

**Comment by simpz** [comment]
Strange, all I can tell you is when I had the URL of 

http://internal.lan:5000/token/1.0/sync/1.5

This worked fine pre Firefox 80 on Android (still worked on the Desktop versions). As soon as I switched to Firefox 80 it failed to sync.

Switching this to a URL with a valid cert over https, worked with this URL:

https://internal.validomain.com:5000/token/1.0/sync/1.5

**Comment by antanasbruzas** [comment]
Firefox 88.1.2 on Android still does not work with http...
