### ISSUE TITLE
Huawei App Galery

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#15067]
Why is there no firefox android browser in huawei app gallery store?

**Comment by kbrosnan** [comment]
Duplicate of #8754

**Comment by anotherus3r** [comment]
> Duplicate of #8754
@kbrosnan do you mean #13420? Huawei AppGallery is an app store.

**Comment by kbrosnan** [comment]
Yep. Sorry I misunderstood the issue report at first we see a lot more reports of the downloads gallery one.
