### ISSUE TITLE
[Bug] Synced tabs description not visible in PB  

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15061]
## Prerequisites
The user shouldn't be signed in to sync
Fenix's theme should be set to **Light**

## Steps to reproduce
1. Switch to PB
2. From Fenix's Home screen tap the ⋮ Main menu
3. Tap the Synced tabs option from the overlay
4. Check the description displayed above the "Sign in to sync" button

### Expected behavior
The "View a list of tabs from your other devices" description should be visible.

### Actual behavior
The description isn't visible while in private mode

### Device information

* Android device: 
• Google Pixel 4XL (Android 10)
• Samsung Galaxy Tab S3 (Android 8)
• OnePlus A3 (Android 6.0.1)
• Nexus 9 (Android 7.1.1)
• Xiaomi Mi Pad 2 (Android 5.1)

* Fenix version: 
• Nightly 200914
• Beta 81.1.1-beta.4

### Notes
✔️ **Not reproducible while having the theme set to Dark**

► Screenshot
![rsz_screenshot_20201024-111928](https://user-images.githubusercontent.com/51314259/93061613-78b92a80-f67c-11ea-808c-5e91228d9780.png)

**Comment by liuche** [comment]
@sblatz do you know if we have a color for this text in PB mode, or if we need some feedback from UX?

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 210105 GV 86 from 1/5 with Nexus 5 (Android 6.0.1).
I will remove the qa:needed label and close this issue.
