### ISSUE TITLE
Sharing doesn't include page title and URL

### ISSUE THREAD

**Issue by sojusnik** [mozilla-mobile/fenix#15075]
When sharing a text selection from Firefox, only the selected text passage is shared, but the page title and URL is missing.

## Steps to reproduce
1. Select text on any webpage in Firefox
2. Share this text to a notes app like [Google Keep](https://play.google.com/store/apps/details?id=com.google.android.keep) or [Notally](https://play.google.com/store/apps/details?id=com.omgodse.notally)
3. A popup will appear with a preview of the shared text, but the page title and URL of the text is missing

### Expected behavior
Ideally, the selected text should contain a proper page title and URL, like [Pocket](https://play.google.com/store/apps/details?id=com.ideashower.readitlater.pro) already does it:
![share with pocket](https://user-images.githubusercontent.com/1245718/93086257-246f7400-f697-11ea-937c-2a46efdcc5e7.png)

### Actual behavior
But Firefox shows currently only the selected text:
![share with firefox](https://user-images.githubusercontent.com/1245718/93086289-32bd9000-f697-11ea-8bba-e3dcb8ad7a4b.png)

### Device information

* Android device: Android 9
* Fenix version: 80.1.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6919)

**Comment by TrianguloY** [comment]
Isn't the share menu that appears after selecting text an android thing that you can't modify?

In any case, personally I don't like this idea. When I select a text and press send I expect to send only the text. This is the behaviour when doing it in all other apps I have.

Note: adding it when sharing the current page from the firefox menu is ok, but that's not what this issue is about.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809788

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
