### ISSUE TITLE
Add a setting to disable the WebRTC.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#15071]
Add a setting to disable the WebRTC.
Or open about:config.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6913)

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1351175

**Comment by original-birdman** [comment]
Why was about:config ever removed?

It's often the only way to apply certain features.

Given that it exists in nightly (and Beta?) the code must be there.

**Comment by plwt** [comment]
User feedback - https://support.mozilla.org/en-US/questions/1376229

**Comment by holequantum** [comment]
https://browserleaks.com/
can we have this option like we need webrtc block for udp because using a vpn it is very important to have this feature.
brave=>https://github.com/brave
bromite=>https://github.com/bromite/bromite
waterfox=>https://github.com/WaterfoxCo/Waterfox

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807451

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
