### ISSUE TITLE
Detangle frecent top sites from desktop

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15078]
We auto-generate top sites based on synced history. We would like to detangle visited sites based on whether or not they were visited on mobile or desktop to avoid seeing sites frequently opened on desktops. 

We would like to know if a visited site was from a mobile visit or not and filter out or deprioritize sites visited on desktop.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6924)

**Comment by Poopooracoocoo** [comment]
What about #7936?

**Comment by gabrielluong** [comment]
> What about #7936?

The 2 issues aren't necessarily the same. Looking at #7936 it looks like it was de-prioritized from product planning.  I added #7936 to the Top Sites project board so that I can continue to advocate for any work related to them. Thanks

**Comment by liuche** [comment]
Fennec had a way to distinguish Mobile-originated sites from Desktop, maybe that's something we can use?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813625

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
