### ISSUE TITLE
I want to disable WebGL.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#15070]
### What is the user problem or growth opportunity you want to see solved?
WebGL will be fingerprinted. For privacy reasons, it would be nice if it could be disabled.

### How do you know that this problem exists today? Why is this important?
I can't use about:config.
Either enable it or add a setting to disable WebGL.

### Who will benefit from it?
I'm delighted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6912)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807452

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
