### ISSUE TITLE
Blocking Mixed Content

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#15073]
Could you add a setting to block mixed content to improve privacy?
Or, please enable about:config so I can change `security.mixed_content.block_display_content`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6916)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807449

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
