### ISSUE TITLE
Added a setting to disable the sensor API.

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#15072]
Could you add a setting to disable the sensor API?
Or you could enable about:config so that I can change the `device.sensors.enabled`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6914)

**Comment by Poopooracoocoo** [comment]
I imagine that this would go in the site permissions page

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807450

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
