### ISSUE TITLE
[Bug] Firefox 80.1.3 sometimes not loading pages

### ISSUE THREAD

**Issue by HuMuK** [mozilla-mobile/fenix#15074]
## Steps to reproduce
Try to open non-specific page 
Link can be pasted, or it is on the loaded page
If the bug is reproduced, it will be seen immediately. 
### Expected behavior
Webpage should be loaded

### Actual behavior
Loading of the page stuck in the middle and it is impossible to load it - I haven't tried to reload the phone. Sometimes it takes about 5 times to reload the Firefox app.
At this time another tabs can be loaded without any problems. 
And the stucked page could be "loading" for hours without showing any error - just empty page.
### Device information
Dtek50
* Android device: yes, Android 6.
* Fenix version: ?
At the same time the fresh nightly doesn't has this issue.
![Screenshot_20200916-162154](https://user-images.githubusercontent.com/26867870/93343359-135e6880-f839-11ea-800d-c67b8c2d7829.png)

**Comment by hwinnemoe** [comment]
@HuMuK Can you still reproduce on version 82.1.3 (Release Firefox) or the current Nightly?

**Comment by HuMuK** [comment]
@hwinnemoe I just have tested the relise and last nightly version on my old phone.
The problem is solved.

**Comment by hwinnemoe** [comment]
Thank you!
