### ISSUE TITLE
[Bug] History multi select can open recently closed

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15089]
## Steps to reproduce
Open multi select in history
Click on recently closed

### Expected behavior
No action

### Actual behavior
It opens recently closed, multi select overlay not dismissed
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200922`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
