### ISSUE TITLE
Add multi select in Recently closed

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15083]
## Steps to reproduce
Go to history/recently closed
Try to long press to multi select 

### Expected behavior
Multi select overlay appears
### Actual behavior
Nothing
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by apbitner** [comment]
Since we have this functionality in History it makes sense to have it in 'Recently closed tabs' as well. I would presume no further UX is needed since this feature exists elsewhere, but let me know.

**Comment by KMaragh** [comment]
I can take a look!

**Comment by gouri-panda** [comment]
Can I work on this ticket?

**Comment by KMaragh** [comment]
Hey. sorry for the delay ill push up a change today/tomorrow

**Comment by KMaragh** [comment]
Hey. sorry for the delay, pushing up a PR later today, having some testing issues.
