### ISSUE TITLE
[Bug] Google is set as default search engine after editing the default custom search engine 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15080]
## Steps to reproduce
1. Go Settings -> Search -> Add search engine -> Other -> and add a new search engine (e.g. cnn).
2. Set the newly added search engine as default.
3. For the same search engine tap on the three-dot menu -> edit.
4. Edit the search engine.
5. Check the default.

### Expected behavior
The search engine added at step 1 is the default one. 

### Actual behavior
Google is the default search engine.

### Device information
* Android device: Google Pixel 4XL (Android 10), Xiaomi Mi Pad 2 (Android 5.1). 
* Fenix version: 81.1.1-beta.4, Nightly 9/14.

**Comment by liuche** [comment]
speaking of search @pocmo @boek - we'll want to pull this into our next sprint, but let me know if this is something that has a root cause in a search refactor we need to do.

**Comment by pocmo** [comment]
Yes, we are in the progress of refactoring already, moving everything into AC:
https://github.com/orgs/mozilla-mobile/projects/63

When we started this Jeff and I agreed that the current solution is fragile and we will try to not touch it until we can switch to the new one. That said, blocking time for this in the sprint, would be really helpful.

**Comment by liuche** [comment]
Okay, we can put this into the next sprint (which starts in 1 week) since there are some other urgent search issues that we're dealing with this sprint. I'll add it to our Eng backlog (@boek please nominate it for the sprint since i'll be out for planning)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/22 and Beta 83.0.0-beta.1 with Xiaomi Mi Pad 2 (Android 5.1)
