### ISSUE TITLE
[Bug] Private Tab closed bar appears everytime you change mode

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15093]
## Steps to reproduce
Open a private tab and close it via tab tray/3 dot menu/close all tabs
Change modes

### Expected behavior
It appears once

### Actual behavior
Private tab closed bar appears everytime
### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

**Comment by liuche** [comment]
This is a pretty old bug and we've made tabs tray improvements - I can't repro it anymore.
