### ISSUE TITLE
[Bug] Sometimes it is not possible to delete the last entry in recently closed

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15091]
## Steps to reproduce
Close some tabs and go to recently closed
Try to delete the tabs from top to bottom
### Expected behavior
You can delete all the tabs, one by one
### Actual behavior
You cannot delete the last tab, pressing delete does nothing
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
In fact it is not possible to delete duplicate entries in recently closed either

**Comment by sflorean** [comment]
Verified as fixed on Nightly 11/18 with Nokia 6 (Android 7.1.1), Pixel 3 (Android 11).
