### ISSUE TITLE
[Bug] Launcher shortcuts do not respect toolbar position setting and uses old search experience

### ISSUE THREAD

**Issue by RachitKeertiDas** [mozilla-mobile/fenix#15105]
## Steps to reproduce

1. Set your toolbar position to the bottom.
2. In the App drawer/ homescreen, long press on Firefox Nightly icon for the app shortcuts to show up.
3. Tap Open a New Tab

### Expected behavior
1. A New Tab opens with the toolbar on bottom.  

### Actual behavior

A searchbar is opened at the top, without the new tab in background. (To me, this seems like the old search experience present in Fenix version 79).

### Additional information:

Please see the screencast below.
![output](https://user-images.githubusercontent.com/51906583/93190562-243bab00-f761-11ea-836b-0287dc44ba4d.gif)

### Device information

* Android device: Redmi Note 7S, Android 9
* Fenix version: Nightly 200914 06:05 (Build #2015763827)
* GV: 82.0a1-20200908095243
* AC: 59.0.20200911130559

**Comment by eliserichards** [comment]
Shortcuts aren't using the new Search experience yet. This will be fixed in #14280
