### ISSUE TITLE
Recently closed tabs menu item should be greyed out or not present in private browsing mode tab tray

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15102]
Hide Recently Closed Tabs section while in PBM because they will always be normal tabs and won't be saved/restored in PBM anyway.

cc @topotropic for UX feedback on the issue

_Originally posted by @ekager in https://github.com/mozilla-mobile/fenix/issues/15084#issuecomment-692247283_

This matches desktop private browsing windows, FYI.

**Comment by Poopooracoocoo** [comment]
i would expect it to still be available but only include private tabs. this is fenix's version of undo close tab on firefox for desktop. 
https://github.com/mozilla-mobile/fenix/issues/2486#issuecomment-691509021

**Comment by yoasif** [comment]
Ah, good call @Poopooracoocoo.
