### ISSUE TITLE
Add links to source code repository and bug tracker

### ISSUE THREAD

**Issue by philipreimer** [mozilla-mobile/fenix#15108]
## Steps to reproduce

1. Open Firefox on Android
2. Tap "Help" or "Settings -> About"

Alternative: 
1. Open the [Firefox page on google play](https://play.google.com/store/apps/details?id=org.mozilla.firefox)

### Expected behavior

There should be prominent links to:
* a bug tracker to report bugs (or at least some kind of contact form)
* the source code repository

### Actual behavior

none of the above can be found

### Device information

* Android device: Nokia 8.1, Android 10
* Fenix version: 80.1.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6972)

**Comment by yoasif** [comment]
This is a feature request, not a bug.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810829

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
