### ISSUE TITLE
[Bug] empty page in private mode

### ISSUE THREAD

**Issue by Higgins91** [mozilla-mobile/fenix#15117]
## Steps to reproduce
Ouvrir le site enedis.fr et aller sur l'espace particulier

### Expected behavior
Ouverture d'une fenêtre pour créer un compte : https://mon-compte-particulier.enedis.fr/creation-de-compte/ avec sûrement des champs texte pour les coordonnées.

### Actual behavior
Page avec un cadre vide

### Device information

* Android device:  honor 7x(bnd-l21) Android 9.1.0
* Fenix version: 80.1.3

# Translation service:
## Steps to reproduce
Open the enedis.fr site and go to the private area

### Expected behavior
Opening of a window to create an account: https://mon-compte-particulier.enedis.fr/creation-de-compte/ with surely text fields for contact details.

### Actual behavior
Page with empty frame

**Comment by eoger** [comment]
Does not work on Firefox for Desktop also, I suggest we move this to web-compat.

**Comment by kbrosnan** [comment]
Closing as a website bug. You can report it to https://www.webcompat.com/.
