### ISSUE TITLE
Add ability to delete all logins

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15113]
### What is the user problem or growth opportunity you want to see solved?
Currently deleting all browsing history won't delete logins. Since logins do have website information, this might leak private data. It would be great if we had a logins option in delete browsing data

### How do you know that this problem exists today? Why is this important?
As a user, I want to be able to delete all user data from within the app, or on a granular scale

### Who will benefit from it?
People who frequently delete browsing data

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6980)

**Comment by yoasif** [comment]
This would be an extremely destructive operation, so I suggest putting an option into the "saved logins" UI instead. I think it makes sense to make this a little harder to find, as I think the negative consequences of losing logins (that may not be saved elsewhere!) are dire.

**Comment by s-ankur** [comment]
My issue is that logins are a privacy violation. I kinda expect all user data to be deleted if I tell it to delete all user data, especially websites I visit. Another option is include it in the delete browsing history but include an additional warning as you said about being very destructive

**Comment by s-ankur** [comment]
Oops

**Comment by yoasif** [comment]
> My issue is that logins are a privacy violation. I kinda expect all user data to be deleted if I tell it to delete all user data, especially websites I visit. Another option is include it in the delete browsing history but include an additional warning as you said about being very destructive

I could be wrong, but Fenix doesn't save logins without asking - each login must explicitly be saved by the user. I don't see that as a "privacy violation", if users are explicitly saving something.

**Comment by s-ankur** [comment]
No no, my issue is that logins include urls which I think counts as browsing data. So when I press on delete browsing data, I expect that all of it should be deleted, including logins. But you are right it is a destructive option

**Comment by cadeyrn** [comment]
Then you should also be able to remove all bookmarks and collections via the same interface. For the record: Collections were already part of this screen and it was intentionally changed in #7421. The same reason why it was changed applies to passwords as well.

**Comment by s-ankur** [comment]
Ohh I didn't know that. Then yes, it makes sense not to add it there

**Comment by mll0** [comment]
I used to use Firefox' integrated password manager. Now I switched to another tool. I need a simple solution to clear the 2000+ passwords in Lockwise.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812442

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
