### ISSUE TITLE
[Bug] Renaming Collections does not work

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15111]
## Steps to reproduce
Try to rename a collection
### Expected behavior
The change shows up
### Actual behavior
It does, but only after clicking on the collection
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by AndiAJ** [comment]
Dupe of #13836

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201020`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201020-085643](https://user-images.githubusercontent.com/51314259/96546377-d14e9980-12b2-11eb-8adb-b5d474dac43f.gif)
