### ISSUE TITLE
Undo option when you delete an item from recently closed

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15114]
### What is the user problem or growth opportunity you want to see solved?
Sometimes people misclick and at least for all destructive actions it would be nice to have an undo option. Since history already has this, it makes sense to add it to recently closed as it is a submenu of history and should probably work in a similar way

### Who will benefit from it?
Anyone who frequently misclicks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6982)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813095

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
