### ISSUE TITLE
[Bug] Recently Closed dissapears when you delete the last history item

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15112]
## Steps to reproduce
On a fresh install, open one webiste and then close it
go to history and delete the history entry

### Expected behavior
Recently closed stays because you do have recently closed tabs

### Actual behavior
Recently closed dissapears. The tabs are still saved there but you can't see them
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200922`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
