### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property browserToolbar has not been initialized

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/fenix#15116]
https://sentry.prod.mozaws.net/share/issue/30c5c45e3fd642d4920cbda02c0ca1d4/

AC issue from a little while ago: https://github.com/mozilla-mobile/android-components/issues/8305

```
UninitializedPropertyAccessException: lateinit property browserToolbar has not been initialized
    at kotlin.jvm.internal.ArrayIteratorKt.throwUninitializedPropertyAccessException(ArrayIterator.kt:2)
    at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically$browser_toolbar_release(BrowserToolbarBottomBehavior.kt:7)
    at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior$createGestureDetector$1.invoke(BrowserToolbarBottomBehavior.kt:3)
    at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$gestureDetector$1.invoke(BrowserGestureDetector.kt:5)
    at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$CustomScrollDetectorListener.onScroll(BrowserGestureDetector.kt:1)
...
(64 additional frame(s) were not displayed)

lateinit property browserToolbar has not been initialized
```

**Comment by agi** [comment]
My Fenix nightly crashes non stop with this signature.

STR

Open Twitter PWA
Scroll down (like you were trying to pull to refresh)
crash

**Comment by agi** [comment]
Samsung S10
Android 10
Latest Nightly from playstore

**Comment by SeburoSUMO** [comment]
I am seeing the same thing.

Moto E5
Android 8.0
Latest Nightly from Google Play store.

**Comment by kbrosnan** [comment]
See also 

* https://github.com/mozilla-mobile/android-components/issues/8405
* https://github.com/mozilla-mobile/android-components/issues/8305

**Comment by jonalmeida** [comment]
I had filled this one for beta too: https://github.com/mozilla-mobile/fenix/issues/15086

**Comment by kbrosnan** [comment]
Going to close this a dupe then.

**Comment by liuche** [comment]
Okay, it looks like we've been duping this issue to some older issues - I'm going to re-open this bc it has a clear STR, and is for a recent Nightly.

**Comment by liuche** [comment]
@mcarare I know Petru had been working on this in https://github.com/mozilla-mobile/android-components/issues/8305, but this looks like a recent Nightly change - do you happen to have any context on it? or if @codrut-topliceanu is looking to pick up something new. Thank you!

**Comment by ekager** [comment]
I'm seeing a different crash with similar STR.
1. Install Twitter PWA on Nightly
2. Don't be logged in, press sign in
3. Crash
`ClassCastException: com.google.material.appbar.AppBarLayout$LayoutParams cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams`
https://crash-stats.mozilla.org/report/index/5d0d5f7c-1b7f-487a-8eb5-0517a0200916

**Comment by ekager** [comment]
These seem like fallout from https://github.com/mozilla-mobile/fenix/issues/10240 (which is actually good because we excluded those commits from the RC build!)

**Comment by mcarare** [comment]
> I'm seeing a different crash with similar STR.
> 
> 1. Install Twitter PWA on Nightly
> 2. Don't be logged in, press sign in
> 3. Crash
>    `ClassCastException: com.google.material.appbar.AppBarLayout$LayoutParams cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams`
>    https://crash-stats.mozilla.org/report/index/5d0d5f7c-1b7f-487a-8eb5-0517a0200916

I think this could be avoided by not calling expand() when in PWA and being defensive in the cast and using safe cast.

**Comment by mcarare** [comment]
> https://sentry.prod.mozaws.net/share/issue/30c5c45e3fd642d4920cbda02c0ca1d4/
> 
> AC issue from a little while ago: [mozilla-mobile/android-components#8305](https://github.com/mozilla-mobile/android-components/issues/8305)
> 
> ```
> UninitializedPropertyAccessException: lateinit property browserToolbar has not been initialized
>     at kotlin.jvm.internal.ArrayIteratorKt.throwUninitializedPropertyAccessException(ArrayIterator.kt:2)
>     at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically$browser_toolbar_release(BrowserToolbarBottomBehavior.kt:7)
>     at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior$createGestureDetector$1.invoke(BrowserToolbarBottomBehavior.kt:3)
>     at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$gestureDetector$1.invoke(BrowserGestureDetector.kt:5)
>     at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$CustomScrollDetectorListener.onScroll(BrowserGestureDetector.kt:1)
> ...
> (64 additional frame(s) were not displayed)
> 
> lateinit property browserToolbar has not been initialized
> ```

This other crash is happening when scrolling in a PWA, again, when we try to expand the toolbar.

**Comment by liuche** [comment]
Thank you for picking this up!

**Comment by jensstutte** [comment]
I am seeing the same thing very frequently when just scrolling articles on www.spiegel.de

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200918`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
