### ISSUE TITLE
Grid view for tabs 

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15115]
## User Story
- As a user, I want to have the option to see my tabs in a way that provides a more visual view and larger thumbnails, so I can find the tabs that I am looking for faster.

### Acceptance Criteria
- I can choose to view tabs in a grid view

![image](https://user-images.githubusercontent.com/42752644/93235871-247d7b80-f74c-11ea-893a-48bcb313123c.png)

![image](https://user-images.githubusercontent.com/42752644/93235902-2e06e380-f74c-11ea-828d-bd23960df87d.png)

<img width="218" alt="Screen Shot 2020-09-23 at 10 16 26 AM" src="https://user-images.githubusercontent.com/1190888/94024844-dd177080-fd85-11ea-990c-62917422e24b.png">

**Comment by Poopooracoocoo** [comment]
also see #13098

**Comment by gabrielluong** [comment]
https://www.figma.com/file/luMaQYjwiMtQM5xQ30P9yP/Tabs?node-id=2%3A0

**Comment by gabrielluong** [comment]
Note: this is hidden behind a feature flag in the secret menu. There are follow up issues listed in https://github.com/mozilla-mobile/fenix/projects/42#column-11017543 to align with the design. I think for the purposes of QA we want to focus on testing the functionality of the grid view and the tabs setting.

**Comment by abhijitvalluri** [comment]
Interesting stuff! I am glad I inspired you and thanks for implementing this into official Firefox as well. I will keep track of the progress here as it will effect the fork as well (such as conflicts and also potentially reusing official implementation in place of my version in the fork).

**Comment by gabrielluong** [comment]
> Interesting stuff! I am glad I inspired you and thanks for implementing this into official Firefox as well. I will keep track of the progress here as it will effect the fork as well (such as conflicts and also potentially reusing official implementation in place of my version in the fork).

@abhijitvalluri From the team, I want to thank you for your help! I am also sorry that I messed up the co-author syntax in my commit for the grid implementation in [Part 3](https://github.com/mozilla-mobile/fenix/pull/15714/commits/1bff79027eb6b429a164994f010108e48fa27db8).

**Comment by softvision-miralobontiu** [comment]
Verified that the grid view for tabs is available after enabling the secret menu.
Environment:
* 10/12 Nightly build,
* Samsung Galaxy Note 8 (Android 9), Google Pixel (Android 10), HTC 10 (Android 8), Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Tab A6 (Android 5.1.1).

![grid](https://user-images.githubusercontent.com/40694158/95716895-cec9bf80-0c74-11eb-8410-9cfb23875a9b.png)
