### ISSUE TITLE
[Bug] Tab switching gesture is inconsistent

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#15121]
## Steps to reproduce
- Open a tab
- Open a second tab with the new tab button
- Go back to the first tab, open a link in a new tab and switch to it
- Close the newly opened tab by pressing the back button, leaving you on the first opened tab
- Swipe right on the address bar

### Expected behavior
I end up on the second opened tab
### Actual behavior
I'm unable to switch tabs by swiping right. However I can switch tabs by swiping left, but the tab I switch to is again the first tab (as if the first tab was present twice in the tab tray). After this the switching gesture works normally again.
### Device information

* Android device: Huawei Nova 6
* Fenix version: Nightly 200915 06:08 (Build #2015764019)
AC: 59.0.20200914130326, 706a49df3
GV: 82.0a1-20200908095243
AS: 61.0.13

**Comment by mobd** [comment]
I have not taken a look at the code but from the behaviour I would guess that there is a simple counter keeping track of which tab in the tab tray the user is on to implement the tab switching gesture, and that that counter is not updated correctly when closing a tab with the back button.

**Comment by amkcpu** [comment]
I believe the same thing is happening when closing a tab via long-pressing the tabs tray icon > `Close tab`.

**Comment by mobd** [comment]
Also, if you're in a state like this, where the tab switching gesture thinks you're on a different tab than the one that's displayed, every interaction with the tab bar is also registered as being for the other tab. So bookmarking doesn't add the displayed page but the other one, pressing the back/forward button affects the tab in the background. Add to home screen does add the displayed page as far as I can tell.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Beta 82.0 and Nightly 9/23.
