### ISSUE TITLE
[Bug] IllegalArgumentException: Parameter specified as non-null is null, BrowserGestureDetector

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#15127]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9527313/

Could be related to #15086 since they're both toolbar gestures with nulls.

```
IllegalArgumentException

Parameter specified as non-null is null: method kotlin.jvm.internal.ArrayIteratorKt.checkParameterIsNotNull, parameter e1

    kotlin.jvm.internal.ArrayIteratorKt in throwParameterIsNullException at line 5
    kotlin.jvm.internal.ArrayIteratorKt in checkParameterIsNotNull at line 1
    mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$CustomScrollDetectorListener in onScroll at line 2
    android.view.GestureDetector in onTouchEvent at line 651
    mozilla.components.browser.toolbar.behavior.BrowserGestureDetector in handleTouchEvent$browser_toolbar_release at line 7
    mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior in onInterceptTouchEvent at line 2
    mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior in onInterceptTouchEvent at line 1
    androidx.coordinatorlayout.widget.CoordinatorLayout in performIntercept at line 13
    androidx.coordinatorlayout.widget.CoordinatorLayout in onInterceptTouchEvent at line 3
    android.view.ViewGroup in dispatchTouchEvent at line 2582
    android.view.ViewGroup in dispatchTransformedTouchEvent at line 3041
```

* Android device: Several
* Fenix version: 81 beta

**Comment by mcarare** [comment]
I think this is a different issue, when the first param of `MotionEvent ` type in the `CustomScrollDetectorListener` is actually nullable. Or, at least in the official doc it is marked with `Platform Type` : `MotionEvent!`. A simple fix would be changing param type to `MotionEvent?`. cc @Mugurell for follow-up.

**Comment by kbrosnan** [comment]
Dupelicate of https://github.com/mozilla-mobile/android-components/issues/8356 I think

**Comment by Mugurell** [comment]
Indeed, it seems to be the same as https://github.com/mozilla-mobile/android-components/issues/8356 for which I posted a speculative fix (that I'm now more sure of) but I'm still seeing reports on Nightly.
Since there are quite many reports of this Beta as a last ditch effort I'll post another patch in 8536 to catch the exception and at least avoid the crash.
