### ISSUE TITLE
[Bug] Private browsing session not cleared after closing last private tab

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#15120]
## Steps to reproduce
Login on any site in a private tab. Then close all private tabs and open the site in a private tab again.

### Expected behavior
All cookies, logins and site data should have been cleared.

### Actual behavior
Cookies, logins and site data persist and only get cleared after closing the app.

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 200915 06:08 (Build #2015764019)
AC: 59.0.20200914130326, 706a49df3
GV: 82.0a1-20200908095243
AS: 61.0.13

**Comment by hwinnemoe** [comment]
Seems to be intermittent, I can reproduce but not on every attempt (Nightly 200915 06:08, Sony Xperia Z2, Android 6.0.1).
