### ISSUE TITLE
[Bug] Instagram PWA crashes when scrolling

### ISSUE THREAD

**Issue by serovar** [mozilla-mobile/fenix#15134]
## Steps to reproduce
Go to instagram.com and install it as a PWA. Open Instagram PWA and start scrolling through your feed.
### Expected behavior
The PWA does not crash.
### Actual behavior
The PWA crashes.
### Device information

* Android device: Google Pixel 2 XL, Android 11
* Fenix version: Nightly 200916 06:01 (Build #2015764211)

### Additional info
There are no issues using the website normally inside Fenix, without the PWA.

**Comment by mcarare** [comment]
@serovar Thank you for your report. This issue is already tracked in https://github.com/mozilla-mobile/fenix/issues/15116. 
You can follow that thread for updates.
