### ISSUE TITLE
[Bug]Beta config

### ISSUE THREAD

**Issue by e-d-e** [mozilla-mobile/fenix#15131]
Hi,
@liuche @jonalmeida @vesta0 

## Steps to reproduce

When the numbers in the first item are manually modified, the second one cannot continue to be manually modified. Can you please fix this problem?

Users must close their browser before they can continue to make changes.

thank you.

![Screenshot_20200916-124537_Firefox Nightly](https://user-images.githubusercontent.com/70746064/93293828-80fb9c00-f81b-11ea-8287-49080d4592d8.png)

### Device information

* Android device: Android 10
* Fenix version: Firefox Beta 81.1.1-beta.5

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1665422
