### ISSUE TITLE
Remove "what's new card" from onboarding

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15130]
## User Story
- As a user, I want to see the most relevant information during onboarding so I don't feel overwhelmed and miss features that can be important to me.

The "what's new card" is only part of onboarding now because it was relevant for users migrating from Fennec to Fenix. Once we are done with the migrations, we should remove this card since it will not be relevant to a brand new Firefox user. We MAY consider adding this card to the homescreen instead, or just leave it as a 3 dot menu option. 

### Acceptance Criteria
- On the first page of onboarding I see information that is relevant to me as a brand new user of Firefox.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200928`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200928-121524](https://user-images.githubusercontent.com/51314259/94414101-99a57380-0184-11eb-8756-15afec42e807.gif)
