### ISSUE TITLE
[UX] Quickly open a new search/tab after opening the browser from cold start

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15138]
## User Story
- As a user, I want to be able to quickly open a new search/tab after opening the browser from cold start

This is a follow up from #12062

We know that landing people on the last tab without giving them a quick easy way to open a new tab, might also not be ideal as it requires users' mental effort to evaluate whether they still need the tab or not. So how might we make it easier for users to quickly open a new tab after landing on their last open tab?

Suggestions from product:

- Adding a "home" button or the ability to open a new tab while on an existing open tab
- Unifying the search experience between when tapping on the URL of an existing tab and when opening a new tab (e.g. top sites accessible the background when tapping on an existing tab URL) 
- Give users the option to always close their open tabs when they exist the browser, so they have the option of opening to the homescreen, or the option to always open homescreen even if they have open tabs. 

### Acceptance Criteria
- I can quickly open a new search/tab after opening the browser from cold start

**Comment by fjorba** [comment]
I don't fully understand if this is the old behaviour before this collection mess.  But please, please restore it. I'm using other browsers meanwhile (Chrome and Samsung Browser), as Mozilla mobile does not longer serve me. The longer it takes to fix it, the more difficult I'll have to go back to my dear old browser, that I still mess. Thanks.

**Comment by yump** [comment]
>Unifying the search experience between when tapping on the URL of an existing tab and when opening a new tab (e.g. top sites accessible the background)

This sounds like it it would bring Fenix more in line with the streamlined UX from Fennec, which I strongly support.

**Comment by TrianguloY** [comment]
I already gave you a possible solution: https://github.com/mozilla-mobile/fenix/issues/13508

**Comment by apbitner** [comment]
@vesta0 My recommendation is that by giving users an option in Settings to choose their default start screen - Home or Last Tab - they can choose whether they prefer starting with a new search, or use an existing tab. Starting a new search from an existing tab is currently 2 taps, and there isn't an easy way to reduce this further right now.


> Adding a "home" button or the ability to open a new tab while on an existing open tab

We currently don't have room in the toolbar to add another icon. It is _possible_ we might combine the shield and lock icon at some point (dependent on desktop), so perhaps we could revisit then.

> Unifying the search experience between when tapping on the URL of an existing tab and when opening a new tab (e.g. top sites accessible the background)

This sounds like the Fennec model, which doesn't solve for the issue of opening a new tab, since Fennec reuses the existing tab unless the user explicitly creates a new one.

I also considered adding a 'New Tab' option to the toolbar menu, similar to Fennec and Chrome, but it would take the same number of taps as opening a new tab through the tab tray, so I don't see a benefit there.

**Comment by vesta0** [comment]
@apbitner thanks for looking into this. I noticed that none of your recommendations is actionable. Do you have a proposal to solving any of these user problems or is @violasong looking into them as part of her toolbar re-org investigation?

**Comment by apbitner** [comment]
@vesta0 For the reasons mentioned above I suggest keeping the experience as is and making sure we have a toggle in Settings for a user to set their default start screen.

**Comment by yoasif** [comment]
@apbitner I have some comments:

> > Adding a "home" button or the ability to open a new tab while on an existing open tab
> 
> We currently don't have room in the toolbar to add another icon. It is _possible_ we might combine the shield and lock icon at some point (dependent on desktop), so perhaps we could revisit then.

This could be based on user preference if we don't assume that any change here has to roll out to the entire userbase, see: https://github.com/mozilla-mobile/fenix/issues/14750 for example. 

> I also considered adding a 'New Tab' option to the toolbar menu, similar to Fennec and Chrome, but it would take the same number of taps as opening a new tab through the tab tray, so I don't see a benefit there.

This would actually be one tap if the Fenix main menu worked like the one in Chrome - which works like menus in desktop OSes. I went ahead and filed https://github.com/mozilla-mobile/fenix/issues/16058 to get this considered as well.

**Comment by apbitner** [comment]
@yoasif Thanks for filing those. The long-press interaction on the menu is interesting, and I suppose technically would make it one tap, though I'd definitely be concerned about discoverability. I'm an everyday Android user and did not know this was possible until just now, but I'm glad I do!

**Comment by tjkirch** [comment]
This isn't stale, it's still an issue.

**Comment by vesta0** [comment]
Closing this issue as we are implementing a number of features to address this user problem.
