### ISSUE TITLE
[Bug] Adding search provider shows "Error connecting to X"

### ISSUE THREAD

**Issue by TyDraniu** [mozilla-mobile/fenix#15137]
## Steps to reproduce

- Check the search engine string - it is https://www.runnaroo.com/search?term=Firefox
- Go to Settings -> Search -> Add search engine -> Other
- Enter Name: Runnaroo and Search string to use: https://www.runnaroo.com/search?term=%s
- Press the confirmation button

### Expected behavior
- Runnaroo is added as a search engine

### Actual behavior
- Red message:  **Error connecting to "Runnaroo"**

### Device information

* Android device: Samsung, Android 7
* Fenix version:  Nightly 200915

**Comment by liuche** [comment]
I was able to repro this, perhaps something is going wrong in the validation step?

**Comment by evilpie** [comment]
I suspect so. I tried querying runnaroo.com with `wget`. This failed with 403 forbidden, unless I set an explicit User-Agent header.

Does the fetch for the search engine validation use the normal Firefox user agent string?

**Comment by TyDraniu** [comment]
It can no longer be reproductible. Runnaroo answered on twitter: 

> Sorry, it was us!  There was a too strict firewall rule that was blocking on the UA.  I was just able to successfully add  Runnaroo as the default search on Firefox Nightly.
https://twitter.com/runnaroo/status/1306393825334751234

**Comment by liuche** [comment]
Great! glad to hear this :)
