### ISSUE TITLE
Ending Firefox  via menu and "X" should show the same behaviour (Android / Daylight)

### ISSUE THREAD

**Issue by martin-schoettler** [mozilla-mobile/fenix#15149]
If the user uses web apps with confidential data it is recommended to clear the cache each time the user leaves the web app. A simple solution is to edit the settings that on ending the app the cache is cleared (and all tabs are closed).

Firefox for Android (Daylight) allows this setting. But it is only active, if the menu (vertical "...") is opened and (in German) "Beenden" (I do not have the US locale) is tapped.

When I tap the "X" in the upper right corner of the Firefox app (in the list of open Apps) then the app ends without closing the tabs. Therefore I assume that also the cache isn't cleared.

The different behaviour of ending firefox via the menu and tapping the "X" contradicts to the "Principle of least astonishment". In the current case there is a security follow-up: The user may assume that the cache is cleared, but it isn't.

Martin Schöttler
matique UG (haftungsbeschränkt)
Kochel a. See, Germany

**Comment by cadeyrn** [comment]
Please see https://github.com/mozilla-mobile/fenix/issues/5865#issuecomment-603980615.

**Comment by martin-schoettler** [comment]
I see: This issue is already discussed in https://github.com/mozilla-mobile/fenix/issues/5865
Therefore closed here.
