### ISSUE TITLE
Put top sites pinned badge next to title for alignment with desktop

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15143]
### What is the user problem or growth opportunity you want to see solved?
it's not the same as desktop.

### How do you know that this problem exists today? Why is this important?
see above? i'm not sure what i'm supposed to put here as i've said "see above" in previous issues.

### Who will benefit from it?
top sites users and users who have used firefox for desktop.

![image](https://user-images.githubusercontent.com/51363864/93402077-1f910700-f8c7-11ea-8c44-4066b3513f70.png)
 i really want parity with desktop as you can tell :p

**Comment by DragoCubed** [comment]
This has actually been added @Poopooracoocoo! No idea if you still use Fenix
