### ISSUE TITLE
[Bug] Page is not displayed correctly after playing fullscreen video in landscape mode

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#15145]
## Steps to reproduce
- Go to a page with a video
- Put your phone in landscape mode
- Fullscreen the video
- Put your phone in portrait mode
- Exit fullscreen

### Expected behavior
The page is displayed normally in portrait mode.

### Actual behavior
The page is displayed as if it's still in landscape mode, with the lower half of the screen being white.

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 200916 06:01 (Build #2015764211)
AC: 59.0.20200915130327, ed607db6a
GV: 82.0a1-20200912220312
AS: 61.0.13

**Comment by s-ankur** [comment]
Dupe https://github.com/mozilla-mobile/fenix/issues/14284

**Comment by mobd** [comment]
I saw that but I think it's a different issue. In my case the phone isn't stuck in landscape mode but the content of the page is displayed wrong, like this

![Screenshot_20200917_203731_org mozilla fenix](https://user-images.githubusercontent.com/66154603/93513270-e76ce100-f925-11ea-86e0-334f42e71475.jpg)

**Comment by LaurentiuApahideanSV** [comment]
Thank you for the report. The issue has already been summited here: https://github.com/mozilla-mobile/fenix/issues/14284. I will close this issue as it will be handled there.
