### ISSUE TITLE
Firefox Lockwise app on Android seems to be unsecure [Bug]

### ISSUE THREAD

**Issue by martin-schoettler** [mozilla-mobile/fenix#15148]
## Steps to reproduce

* I have created a Firefox account (with a strong primary password) and connected my desktop Firefox to that account.
* I have installed the Lockwise App on my Android mobile and connected that to the Firefox account (I needed to enter the credentials for the Firefox account). I was _not_ asked to set a primary password for the Firefox Lockwise app.
* I could access all the passwords of my Firefox account.
* I restarted my mobile and started Firefox Lockwise again.
* The primary password (of the Firefox account) wasn't asked. I was only asked for the mobile PIN.
* Again I could access all the passwords (plain text!)
* I entered a new password in my destop Firefox
* I could access the new password in the Firefox Lockwise app on my mobile without the need to enter my primary password of the Firefox account.

### Expected behavior

I assumed that either
* the Firefox Lockwise app uses an own primary password to encrypt the passwords on the mobile, or
* the app uses the primary password of the Firefox account to encrypt the passwords.

I assumed also that
* the app stores the credentials for the Firefox account encrypted by an own primary password, or
* the app asks me to enter the primary password of the Firefox account whenever it starts or accesses that account.

### Actual behavior

Firefox Lockwise does not ask the user for a primary password, when it is restarted. But it is able to connect to the Firefox account.

Therefore Firefox seems to store crucial data (passwords, primary password of the Firefox account) in an unsecure way. Only the UI-access to the data is protected by asking the PIN. (But the PIN is not suitable to encrypt data: It is not a strong password and it is (hopefully) not known to any app.) Also if the file system of the mobile is encrypted, backups of the files transferred to the desktop computer are not encrypted without further user actions.
 
### Device information

* Android device: Samsung Galaxy 6
* Fenix version: Daylight

Martin Schöttler
matique UG (haftungsbeschränkt)
Kochel a. See, Germany

**Comment by cadeyrn** [comment]
You're in the wrong issues tracker. This is for Lockwise: https://github.com/mozilla-lockwise/lockwise-android/issues

**Comment by martin-schoettler** [comment]
You are right cadeyrn. I have searched for lockwise in bugzilla and did not find a more suitable tracker there.
