### ISSUE TITLE
FNX-5073 ⁃ Bookmarking URL with url fragment (#) causes saved bookmark title to be blank

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1515]
## Steps to reproduce
1. Navigate to https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#See_also
1. Swipe up
1. tap Bookmark icon
1. tap edit in the snackbar that appears

### Expected behavior
Title of bookmark should be "prefers-color-scheme - CSS: Cascading Style Sheets | MDN"

### Actual behavior
Bookmark title is blank

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1915 build id 10991207

**Comment by kbrosnan** [comment]
Confirmed April 16th build. Sounds similar to #1558

**Comment by colintheshots** [comment]
For some reason, the SessionManager finds no title for URLs with fragment identifiers. I think this may require a bug in Android Components.

**Comment by kbrosnan** [comment]
@colintheshots did you file an a-c bug for your last comment?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1920 (#11361806), with Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8), and HTC Desire 820 (Android 6.0.1).
