### ISSUE TITLE
Do not show open in app onboarding banner if open in app is ON.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#15150]
Breakout from https://github.com/mozilla-mobile/fenix/issues/9506#issuecomment-693565770.

> Confirming that the banner should NOT appear if you already have open in app turned on in your settings.

**Comment by mcarare** [comment]
@betsymi : Should the banner not show if: 

1. The user has "open in app" on at the time of the website visit, but show it in the future if user turns it off, when user visits a website.
2. Do not show banner at all if user has turned "open in app" ON, at some point, regardless of the setting on the moment of the website visit.

I would incline to chose the first, but wanted to confirm. Thank you!

**Comment by betsymi** [comment]
Yes, number one is good! Thanks.

**Comment by AndiAJ** [comment]
Hi @mcarare , unfortunately **the banner is still being displayed** even if the **"Open link in apps" is enabled**

Checked it on on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

Please review and advise ☺️

**Comment by mcarare** [comment]
> Hi @mcarare , unfortunately **the banner is still being displayed** even if the **"Open link in apps" is enabled**
> 
> Checked it on on the latest **`Nightly Build 200921`** using the following devices:
> • Google Pixel 3a (Android 11)
> • Huawei Mate 20 Lite (Android 10)
> • OnePlus A3 (Android 6.0.1)
> 
> Please review and advise ☺️

Opened #15263

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly 200923`** & **`82.0.0-beta.1`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
