### ISSUE TITLE
[Bug]ETP toggle is disabled in the info sheet even if it's actually enabled in settings 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15152]
## Prerequisites
Have a clean profile or a fresh install

## Steps to reproduce
1. Navigate to Cnn.com (accept the cookies if needed)
2. After the page is reloaded check the ETP shield icon
3. Tap the ETP toolbar shield icon and check the state of the ETP toggle
4. From the ETP info panel tap "Protection Settings" and check the state of the ETP toggle

### Expected behavior
Step 2 : The ETP shield icon should be purple displaying a pop-up message
Step 3 : The  ETP toggle should be enabled in the info sheet
Step 4 : The  ETP toggle should be enabled 

### Actual behavior
Step 2 : The ETP shield icon isn't colored purple and no pop-up message is displayed
Step 3 : The  ETP toggle is disabled in the info sheet
Step 4 : The  ETP toggle is actually enabled in settings

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

* Fenix version: 200917

### Notes
► Video
![20200917-132027](https://user-images.githubusercontent.com/51314259/93458430-f71a0480-f8e8-11ea-82b4-bf48aac5315b.gif)

**Comment by Amejia481** [comment]
After chatting with @pocmo, we discovered what is the issue see https://github.com/mozilla-mobile/android-components/issues/8431 for more details.

**Comment by hwinnemoe** [comment]
Related to #14949

**Comment by Amejia481** [comment]
This will be addressed on https://github.com/mozilla-mobile/android-components/pull/8432/

**Comment by hwinnemoe** [comment]
This is now fixed in Nightly 200920 06:02 (Build #2015764977).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200921`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
