### ISSUE TITLE
FNX-5074 ⁃ [Bug] Can't scroll library in landscape mode

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#1516]
## Steps to reproduce
Open Fenix, go into landsscape mode, open Library from kebab menu

### Expected behavior
I can scroll the Library

### Actual behavior
I can't scroll the Library

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1915

**Comment by jatinkumarg** [comment]
Hey, I have added a PR (https://github.com/mozilla-mobile/fenix/pull/1544). 

Let me know if any changes are required.

**Comment by bsurd** [comment]
This has now been verified, the library can be scrolled and all items are accessible.
