### ISSUE TITLE
Hard Refresh a webpage 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15163]
### What is the user problem or growth opportunity you want to see solved?
From https://www.howtogeek.com/672607/how-to-hard-refresh-your-web-browser-to-bypass-your-cache/:

> Sometimes, a website does not behave as expected or seems stuck showing outdated information. To fix this, it’s easy to force your browser to completely reload its local copy of the page (cache) using a simple keyboard shortcut. 

Since desktop firefox has this functionality it would be great if android did as well. I suggest that long press refresh button be used to invoke this option, similar to how long press back button is used for tab history 

### How do you know that this problem exists today? Why is this important?
It was important enough to be implemented on all desktop browsers

### Who will benefit from it?
Users who get stuck on outdated versions of websites.

**Comment by s-ankur** [comment]
Probably depends on https://github.com/mozilla-mobile/fenix/issues/14773

**Comment by TrianguloY** [comment]
This is already implemented since 80.1.0 https://github.com/mozilla-mobile/fenix/releases/tag/v80.1.0
Unless you mean a different force refresh when long tap the refresh button

**Comment by s-ankur** [comment]
Ahh ok, it seems because of #1
