### ISSUE TITLE
[Bug] The first 5 tabs are saved in "Recently closed tabs" when using "Close all tabs" from Tabs tray

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15162]
## Steps to reproduce
1. Open Gmail, CNN, google pages by going to URL bar.
2. Open Pocket and long tap on different links (5-6).
3. Tap on "Open in new tab" from the context menu. 
4. Go to the Tabs tray menu and tap on "Close all tabs".
5. Open 1 page and open the "Recently closed tabs" menu. 

### Expected behavior
The tabs are listed based on the last/first pages opened at steps 1 and 2. Gmail, CNN pages are not saved.

### Actual behavior
Only the first 5 tabs are listed.

### Device information
* Android device: all
* Fenix version: Nightly

@ekager I'm not sure if the expected is correct but given the fact that "When a 6th tab is removed, the oldest tab will be deleted." in this scenario the oldest tabs are kept.

**Comment by ekager** [comment]
Mmm that more meant "oldest tab in recently closed tabs".
Thanks for filing! I think this is more of a UX question. What should happen when the user deletes all tabs?

**Comment by apbitner** [comment]
Pinging @topotropic for tab management

**Comment by topotropic** [comment]
@ekager do we currently just store 5 closed tabs in "Recently closed"? What could be a good rule set here? Per session or just up the number to 10 or so?

**Comment by AndiAJ** [comment]
Fixed as per [#15503](https://github.com/mozilla-mobile/fenix/issues/15503#issuecomment-704348417)
