### ISSUE TITLE
[Bug] Intermittent failure debug(T) sets up interactor listeners

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#15168]
Log: https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=315979488&repo=fenix&lineNumber=5319

[task 2020-09-17T17:45:44.912Z]   TEST: sets up interactor listeners
[task 2020-09-17T17:45:44.913Z]     [Robolectric] org.mozilla.fenix.search.toolbar.ToolbarViewTest.sets up interactor listeners: sdk=28; resources=LEGACY
[task 2020-09-17T17:45:44.913Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-09-17T17:45:44.913Z]     I/AssetManager: no overlays.list file found
[task 2020-09-17T17:45:44.913Z]     D/StrictMode: onThreadPolicyViolation; policy=65599
[task 2020-09-17T17:45:44.913Z]     D/StrictMode: StrictMode policy violation; ~duration=0 ms: android.os.strictmode.DiskWriteViolation
[task 2020-09-17T17:45:44.913Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.$$robo$$android_os_StrictMode_AndroidBlockGuardPolicy$onWriteToDisk(StrictMode.java:1460)
[task 2020-09-17T17:45:44.913Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java)
[task 2020-09-17T17:45:44.914Z]     at libcore.io.BlockGuardOs.$$robo$$libcore_io_BlockGuardOs$mkdir(BlockGuardOs.java:196)
[task 2020-09-17T17:45:44.914Z]     at libcore.io.BlockGuardOs.mkdir(BlockGuardOs.java)
[task 2020-09-17T17:45:44.914Z]     at android.system.Os.$$robo$$android_system_Os$mkdir(Os.java:323)
[task 2020-09-17T17:45:44.914Z]     at android.system.Os.mkdir(Os.java)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:608)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:596)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getPreferencesDir(ContextImpl.java:552)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.getPreferencesDir(ContextImpl.java)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferencesPath(ContextImpl.java:747)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferences(ContextImpl.java:400)
[task 2020-09-17T17:45:44.914Z]     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java)
[task 2020-09-17T17:45:44.914Z]     at mozilla.components.support.locale.LocaleManager$Storage.getSharedPreferences(LocaleManager.kt:123)
[task 2020-09-17T17:45:44.914Z]     at mozilla.components.support.locale.LocaleManager$Storage.getLocale(LocaleManager.kt:99)
[task 2020-09-17T17:45:44.914Z]     at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:42)
[task 2020-09-17T17:45:44.914Z]     at mozilla.components.support.locale.LocaleManager.updateResources$support_locale_release(LocaleManager.kt:72)
[task 2020-09-17T17:45:44.915Z]     at mozilla.components.support.locale.LocaleAwareApplication.attachBaseContext(LocaleAwareApplication.kt:17)
[task 2020-09-17T17:45:44.915Z]     at android.app.Application.$$robo$$android_app_Application$attach(Application.java:212)
[task 2020-09-17T17:45:44.915Z]     at android.app.Application.attach(Application.java)
[task 2020-09-17T17:45:44.915Z]     at sun.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
[task 2020-09-17T17:45:44.915Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-09-17T17:45:44.915Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-09-17T17:45:44.915Z]     at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:283)
[task 2020-09-17T17:45:44.915Z]     at org.robolectric.shadows.ShadowApplication.callAttach(ShadowApplication.java:79)
[task 2020-09-17T17:45:44.915Z]     at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:250)
[task 2020-09-17T17:45:44.915Z]     at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
[task 2020-09-17T17:45:44.915Z]     at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
[task 2020-09-17T17:45:44.915Z]     at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
[task 2020-09-17T17:45:44.915Z]     at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-09-17T17:45:44.915Z]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-09-17T17:45:44.915Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-09-17T17:45:44.915Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-09-17T17:45:44.915Z]     at java.lang.Thread.run(Thread.java:748)
[task 2020-09-17T17:45:44.915Z]     
[task 2020-09-17T17:45:44.915Z]     D/StrictMode: onThreadPolicyViolation; policy=65599
[task 2020-09-17T17:45:44.915Z]     D/StrictMode: StrictMode policy violation; ~duration=0 ms: android.os.strictmode.DiskWriteViolation
[task 2020-09-17T17:45:44.915Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.$$robo$$android_os_StrictMode_AndroidBlockGuardPolicy$onWriteToDisk(StrictMode.java:1460)
[task 2020-09-17T17:45:44.915Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java)
[task 2020-09-17T17:45:44.915Z]     at libcore.io.BlockGuardOs.$$robo$$libcore_io_BlockGuardOs$chmod(BlockGuardOs.java:72)
[task 2020-09-17T17:45:44.915Z]     at libcore.io.BlockGuardOs.chmod(BlockGuardOs.java)
[task 2020-09-17T17:45:44.915Z]     at android.system.Os.$$robo$$android_system_Os$chmod(Os.java:85)
[task 2020-09-17T17:45:44.915Z]     at android.system.Os.chmod(Os.java)
[task 2020-09-17T17:45:44.915Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:609)
[task 2020-09-17T17:45:44.915Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2020-09-17T17:45:44.915Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:596)
[task 2020-09-17T17:45:44.915Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2020-09-17T17:45:44.915Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getPreferencesDir(ContextImpl.java:552)
[task 2020-09-17T17:45:44.915Z]     at android.app.ContextImpl.getPreferencesDir(ContextImpl.java)
[task 2020-09-17T17:45:44.915Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferencesPath(ContextImpl.java:747)
[task 2020-09-17T17:45:44.916Z]     at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java)
[task 2020-09-17T17:45:44.916Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferences(ContextImpl.java:400)
[task 2020-09-17T17:45:44.916Z]     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java)
[task 2020-09-17T17:45:44.916Z]     at mozilla.components.support.locale.LocaleManager$Storage.getSharedPreferences(LocaleManager.kt:123)
[task 2020-09-17T17:45:44.916Z]     at mozilla.components.support.locale.LocaleManager$Storage.getLocale(LocaleManager.kt:99)
[task 2020-09-17T17:45:44.916Z]     at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:42)
[task 2020-09-17T17:45:44.916Z]     at mozilla.components.support.locale.LocaleManager.updateResources$support_locale_release(LocaleManager.kt:72)
[task 2020-09-17T17:45:44.916Z]     at mozilla.components.support.locale.LocaleAwareApplication.attachBaseContext(LocaleAwareApplication.kt:17)
[task 2020-09-17T17:45:44.916Z]     at android.app.Application.$$robo$$android_app_Application$attach(Application.java:212)
[task 2020-09-17T17:45:44.916Z]     at android.app.Application.attach(Application.java)
[task 2020-09-17T17:45:44.916Z]     at sun.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
[task 2020-09-17T17:45:44.916Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-09-17T17:45:44.916Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-09-17T17:45:44.916Z]     at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:283)
[task 2020-09-17T17:45:44.916Z]     at org.robolectric.shadows.ShadowApplication.callAttach(ShadowApplication.java:79)
[task 2020-09-17T17:45:44.916Z]     at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:250)
[task 2020-09-17T17:45:44.916Z]     at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
[task 2020-09-17T17:45:44.916Z]     at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
[task 2020-09-17T17:45:44.916Z]     at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
[task 2020-09-17T17:45:44.916Z]     at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-09-17T17:45:44.916Z]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-09-17T17:45:44.916Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-09-17T17:45:44.916Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-09-17T17:45:44.916Z]     at java.lang.Thread.run(Thread.java:748)
[task 2020-09-17T17:45:44.916Z]     
[task 2020-09-17T17:45:44.916Z]     D/StrictMode: onThreadPolicyViolation; policy=65599
[task 2020-09-17T17:45:44.916Z]     D/StrictMode: StrictMode policy violation; ~duration=0 ms: android.os.strictmode.DiskReadViolation
[task 2020-09-17T17:45:44.916Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.$$robo$$android_os_StrictMode_AndroidBlockGuardPolicy$onReadFromDisk(StrictMode.java:1504)
[task 2020-09-17T17:45:44.916Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java)
[task 2020-09-17T17:45:44.916Z]     at android.app.SharedPreferencesImpl.$$robo$$android_app_SharedPreferencesImpl$awaitLoadedLocked(SharedPreferencesImpl.java:256)
[task 2020-09-17T17:45:44.916Z]     at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java)
[task 2020-09-17T17:45:44.916Z]     at android.app.SharedPreferencesImpl.$$robo$$android_app_SharedPreferencesImpl$getString(SharedPreferencesImpl.java:282)
[task 2020-09-17T17:45:44.916Z]     at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java)
[task 2020-09-17T17:45:44.917Z]     at mozilla.components.support.locale.LocaleManager$Storage.getLocale(LocaleManager.kt:101)
[task 2020-09-17T17:45:44.917Z]     at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:42)
[task 2020-09-17T17:45:44.917Z]     at mozilla.components.support.locale.LocaleManager.updateResources$support_locale_release(LocaleManager.kt:72)
[task 2020-09-17T17:45:44.917Z]     at mozilla.components.support.locale.LocaleAwareApplication.attachBaseContext(LocaleAwareApplication.kt:17)
[task 2020-09-17T17:45:44.917Z]     at android.app.Application.$$robo$$android_app_Application$attach(Application.java:212)
[task 2020-09-17T17:45:44.917Z]     at android.app.Application.attach(Application.java)
[task 2020-09-17T17:45:44.917Z]     at sun.reflect.GeneratedMethodAccessor237.invoke(Unknown Source)
[task 2020-09-17T17:45:44.917Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-09-17T17:45:44.917Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-09-17T17:45:44.917Z]     at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:283)
[task 2020-09-17T17:45:44.917Z]     at org.robolectric.shadows.ShadowApplication.callAttach(ShadowApplication.java:79)
[task 2020-09-17T17:45:44.917Z]     at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:250)
[task 2020-09-17T17:45:44.917Z]     at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
[task 2020-09-17T17:45:44.917Z]     at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
[task 2020-09-17T17:45:44.917Z]     at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
[task 2020-09-17T17:45:44.917Z]     at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-09-17T17:45:44.917Z]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-09-17T17:45:44.917Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-09-17T17:45:44.917Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-09-17T17:45:44.917Z]     at java.lang.Thread.run(Thread.java:748)
[task 2020-09-17T17:45:44.917Z]     
[task 2020-09-17T17:45:44.917Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-09-17T17:45:45.213Z]   FAILURE
[task 2020-09-17T17:45:45.213Z] 
[task 2020-09-17T17:45:45.213Z] java.lang.InstantiationError: kotlin.jvm.functions.Function1
[task 2020-09-17T17:45:45.213Z] 	at sun.reflect.GeneratedSerializationConstructorAccessor161.newInstance(Unknown Source)
[task 2020-09-17T17:45:45.213Z] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[task 2020-09-17T17:45:45.213Z] 	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.proxy.jvm.ObjenesisInstantiator.instanceViaObjenesis(ObjenesisInstantiator.kt:75)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.proxy.jvm.ObjenesisInstantiator.instance(ObjenesisInstantiator.kt:42)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.instantiation.JvmInstantiator$instantiate$2.invoke(JvmInstantiator.kt:16)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.instantiation.AbstractInstantiator.instantiateViaInstanceFactoryRegistry(AbstractInstantiator.kt:17)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.instantiation.JvmInstantiator.instantiate(JvmInstantiator.kt:15)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.recording.states.RecordingState$matcher$signatureValue$1$1.invoke(RecordingState.kt:49)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.instantiation.JvmAnyValueGenerator$anyValue$1.invoke(JvmAnyValueGenerator.kt:27)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.instantiation.AnyValueGenerator.anyValue(AnyValueGenerator.kt:27)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.instantiation.JvmAnyValueGenerator.anyValue(JvmAnyValueGenerator.kt:23)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.recording.states.RecordingState$matcher$signatureValue$1.invoke(RecordingState.kt:48)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:20)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.recording.states.RecordingState.matcher(RecordingState.kt:47)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.recording.CommonCallRecorder.matcher(CommonCallRecorder.kt:52)
[task 2020-09-17T17:45:45.213Z] 	at org.mozilla.fenix.search.toolbar.ToolbarViewTest$sets up interactor listeners$1.invoke(ToolbarViewTest.kt:186)
[task 2020-09-17T17:45:45.213Z] 	at org.mozilla.fenix.search.toolbar.ToolbarViewTest$sets up interactor listeners$1.invoke(ToolbarViewTest.kt:37)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.MockKDsl.internalEvery(API.kt:92)
[task 2020-09-17T17:45:45.213Z] 	at io.mockk.MockKKt.every(MockK.kt:98)
[task 2020-09-17T17:45:45.213Z] 	at org.mozilla.fenix.search.toolbar.ToolbarViewTest.sets up interactor listeners(ToolbarViewTest.kt:74)
[task 2020-09-17T17:45:45.213Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-09-17T17:45:45.213Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-09-17T17:45:45.214Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-09-17T17:45:45.214Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-09-17T17:45:45.214Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-09-17T17:45:45.214Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-09-17T17:45:45.214Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-09-17T17:45:45.214Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-09-17T17:45:45.214Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-09-17T17:45:45.214Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
[task 2020-09-17T17:45:45.214Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
[task 2020-09-17T17:45:45.214Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-09-17T17:45:45.214Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-09-17T17:45:45.214Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-09-17T17:45:45.214Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-09-17T17:45:45.214Z] 	at java.lang.Thread.run(Thread.java:748)

**Comment by csadilek** [comment]
This just happened again: https://github.com/mozilla-mobile/fenix/issues/15168 - still needs a fix.

**Comment by jonalmeida** [comment]
Happened again during the [91.0.0 release](https://github.com/mozilla-mobile/fenix/runs/3059320079).

**Comment by jonalmeida** [comment]
We're currently using 1.10.0 of mockk, so could try updating to the latest patch version [1.10.6](https://github.com/mockk/mockk/releases/tag/1.10.6), or even [1.11.0](https://github.com/mockk/mockk/releases/tag/1.11.0). This _may_ fix the internal errors from instantiating.

**Comment by jonalmeida** [comment]
> We're currently using 1.10.0 of mockk, so could try updating to the latest patch version [1.10.6](https://github.com/mockk/mockk/releases/tag/1.10.6), or even [1.11.0](https://github.com/mockk/mockk/releases/tag/1.11.0). This _may_ fix the internal errors from instantiating.

Narrator: It did not.

Happened again on the AC [bump PR](https://github.com/mozilla-mobile/fenix/pull/20777#issuecomment-896803446).

**Comment by Archaeopteryx** [comment]
Jon, shall this issue be reopened? It has been observed again, on [fenix main](https://github.com/mozilla-mobile/fenix/issues/15168).
