### ISSUE TITLE
[Bug] Add to home screen with about pages does not work

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15167]
## Steps to reproduce
Go to about:about
Click add to homescreen
Try to open it
### Expected behavior
About about opens
### Actual behavior
"App isn't installed" is toasted
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by kbrosnan** [comment]
This is intentional. I believe this happens because about: is not registered as a protocol in the manifest. We don't want third party apps to be able to launch `about:` pages in Firefox.

**Comment by s-ankur** [comment]
Maybe we could disable add to homescreen on about pages?
