### ISSUE TITLE
[webcontent] render differ between fenix and firefox desktop and other browsers

### ISSUE THREAD

**Issue by nanake** [mozilla-mobile/fenix#15177]
Copy from issue #7879. I still can reproduce.

## Site with issue and any steps to reproduce
1. open https://indy-plus-theme.tumblr.com and swipe to the bottom
2. observe at loading animation at the bottom of page
3. compare to firefox desktop.

![gifgif](https://user-images.githubusercontent.com/467392/79624318-1e5a8300-814b-11ea-9413-08dd117eb4ca.gif)

### Expected behavior
animate in full circle

### Actual behavior
not animate in full circle

### Does toggling Tracking Protection fix the issue? (Press the lock icon in the toolbar while on the site to see toggle)
nope

### Can you reproduce in [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox)?
nope! legacy firefox works fine ✔️✔️✔️

### Can you reproduce in Chrome (or other non-Mozilla browser)?

I can't. all work fine
✔️ firefox desktop
✔️ chrome desktop
✔️ edge desktop
✔️ chrome mobile
✔️ edge mobile
❌ Firefox mobile

### Device information
Nokia 6.1 Plus
Nokia 3.2

* Android device: 10
* Fenix version: 
Nightly 200917 06:07 (Build #2015764403)
AC: 59.0.20200916130055, 612650517
GV: 82.0a1-20200912220312
AS: 61.0.13

**Comment by ekager** [comment]
Can you still reproduce? I just tried this and it looks centered to me

**Comment by nanake** [comment]
> Can you still reproduce?

I still can reproduce.

> I just tried this and it looks centered to me

wrt reported device?

anyway, i don't care no more. this problem's specific to Nokia device which was EOL
