### ISSUE TITLE
A change in the order of video payload types in the first offer is not retained in subsequent sdps.

### ISSUE THREAD

**Issue by manjeshbhargav** [mozilla-mobile/fenix#15179]
## Steps to reproduce

1. Run https://codepen.io/manjeshbhargav/pen/rNeZQEJ in a Firefox Android tab (This snippet prefers VP8 codec).
2. Observe the m= lines of the first offer and the next answer.

### Expected behavior

The payload types in both m= lines should have the same order (VP8 payload type should be first).

### Actual behavior

The payload types in both m= lines do not match. That is, in the second m= line, H264 payload type is back to being the first.

### Device information

* Android device: Pixel 2
* Fenix version: 80

### Note

If you run this in Chrome and Safari, the payload types order is preserved in subsequent sdps.

**Comment by manjeshbhargav** [comment]
Bump.

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683258

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
