### ISSUE TITLE
Device Names Are Incomplete When Using Send Tab to Device From Android Firefox Nightly

### ISSUE THREAD

**Issue by Webweweave** [mozilla-mobile/fenix#15170]
## Steps to reproduce 
From tab, tap tab number icon and tap on share button. A row of buttons for various connected devices appears but names of devices are not fully shown

### Expected behavior 
I expect to be able to see the full name of the device to which I am sending the tab. I have Firefox on 2 Desktop PCs, 1 Kindle, and 1 smartphone.

### Actual behavior 
The device I am sending the tab to only shows part of the name. I have 2 buttons (of 4) that say "ADMIN's Firefox on De...", "Admin's Firefox on DESKTOP-...", and I have a 3rd button that says "SMR's Firefox on DESKTOP...". I have a button that shows a connection to "Firefox Preview on samsung..." with an smartphone icon and a final button that shows "Send to all devices".

### Device information 
* Samsung Galaxy S8
* Android device:  Yes, version 9
* Fenix version: NIGHTLY
![Screenshot_20200917-151041_Firefox](https://user-images.githubusercontent.com/36248313/93523322-7fec6c80-f8f8-11ea-9ed7-aaf5ba6b12bb.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7061)

**Comment by Webweweave** [comment]
This is still an issue. It was automatically labeled by a bot as "stale" but is that just a faint euphemism for an aged bug that nobody is working on? Too bad, its a great feature. Back about a year and a half it was not working. Someone identified the problem as not enough space alloted to the field for the entire device name to appear and the problem was fixed. Within only a few months it was not working again. WTH. Can this issue be put back into the to-do list?

**Comment by kbrosnan** [comment]
The bot checks older issues. Having the reporter check in and confirm that the report is still present is useful for bugs sometimes they are resolved. As you can see commenting that this is still present is all that it takes to have it pulled from the list. I am going to move it to a feature request so it will not re-ping on this issue.

Part of the problem is that the default desktop  `Device name {username + Firefox (channel) + computer name}`. Puts the username first. For some users this is useful for others it pushes other identifying info off screen. I am in the latter category and have chosen to edit my desktop sync device names to be more meaningful.  The only other bit of identifying info in the Sync Device Name is the computer name is the computer name, unfortunately these tend to be poor identifiers for most users.

**Comment by Webweweave** [comment]
This is quite helpful but how do I rename my "desktop sync device" names? Would this complicate network shared stuff? Thanks

**Comment by Webweweave** [comment]
OK, I figured out how to change device for sync. Not sure if it did anything to network share just yet. I'll blunder along and investigate. :)

**Comment by topotropic** [comment]
@ewachowiak could you have a look for when you find time – I made a proposal as part of the Share sheet work on how to handle device names but I want to make sure this still makes sense also considering the username part, which wasn't incooperated in the proposal I believe:

> For Nightly and Beta instances of Firefox omit “Firefox” to shorten the device name.
https://www.figma.com/file/4TFvx6UlVO127bubv1WZKZ/Print-to-PDF-%2F-Share-Sheet?node-id=438%3A19971

**Comment by ewachowiak** [comment]
@topotropic I'm checking with localization team to see if this would be an issue, but in the meantime, I'm not sure how much shortening the browser name would help because desktop devices would still have the username in front. E.g. "emilywachowiak’s Firefox on Emilys-MacBook-Pro"

**Comment by ewachowiak** [comment]
@topotropic There's no localization concerns with shortening the browser names as you suggest, so I think it should be ok!

**Comment by kbrosnan** [comment]
@topotropic that would best coordinated with desktop to make a meaningful change. The device name is controlled by the device.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809787

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
