### ISSUE TITLE
[Bug] Can't send Tab from Android to PC by FirefoxSync

### ISSUE THREAD

**Issue by JPluess** [mozilla-mobile/fenix#15172]
Hi 

Firefox on Android 10 has problem sharing websites with other computers connected to Firefox Sync.
It might have something to do with the Windows PC master password. 
Sync only works if Firefox is running active on pc. If I am away I wish to still be able to send a tabs home as before. 

![Screenshot_20200917-233309_Firefox](https://user-images.githubusercontent.com/7995240/93530618-2a3ab300-f93e-11ea-8a74-9a8ed0c0a98f.jpg)

**Comment by kbrosnan** [comment]
To send a tab in Fenix you need to open it as a tab then choose the dotted `<` "share button" to get access to your synced devices. For sending a link without opening as a tab issue #1523 exists.

**Comment by JPluess** [comment]
this is not whats causing the problem. 
it has to do with the masterpassword from firefox desktop. there needs to be a better solution. 
i reported hopefully to the correct person for ffdesktop. 
https://github.com/webcompat/web-bugs/issues/63802
