### ISSUE TITLE
Tablist should always start at the top tab or show a hint that the list starts not at the top and there are some tabs not visible

### ISSUE THREAD

**Issue by OlliKn** [mozilla-mobile/fenix#15184]
Please consider to open the Tablist always at the first entry or give the user at least a visual hint that there are some tabs hidden on top of the top _visual_ tab in the list.
I had the problem that I wanted to save all open tabs in a collection. Press "save in collection", choose the visible tabs, scroll down to choose the lower tabs and... forgot the two top tabs which were not visible in the list because the list started at the third tab. The tablist looks like it would be at the top (as expected by the user I would say). The scrollbar is thin and mostly hidden and should not be the only indicator for the position of the list.

When the Tablist starts in the middle it is maybe not a so bad idea in some or many cases but in this case you should show the user a clear hint.

**Comment by cadeyrn** [comment]
Duplicate of #14619.

**Comment by OlliKn** [comment]
sorry! Did not use the matching search string ;-) Closing.
