### ISSUE TITLE
[Bug] possible regression: apks can't be installed via notification (again)

### ISSUE THREAD

**Issue by x2k13** [mozilla-mobile/fenix#15182]
## Steps to reproduce
Download any .apk
Click "open" on the notification (in Firefox or status bar makes no difference).

### Expected behavior
Install App dialogue should show up.

### Actual behavior
Just a pop-up with unrelated apps (like share/open with) shows up. 

**It doesn't matter if the switch in app-info/settings "allow to install from unknown sources" is active or not, the behaviour stays the same, no apk install possible. You need to do this via a filemanager.**

### Device information

* Android device: Samsung Galaxy Tab A 10.5 / Motorola X Play, Android 10
* Fenix version: latest Dev, since several versions

**Edit:**
Tested on https://apkmirror.org, apk gets downloaded, Installer toast comes up (?!).
Tested on https://a2zapk.com, apk gets downloaded, above described behaviour occurs.

Question now is, why does it work on one site, and not others?

**Comment by Amejia481** [comment]
Very likely to be fixed after https://github.com/mozilla-mobile/android-components/pull/9558 lands similar to https://github.com/mozilla-mobile/fenix/issues/17502

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/8 Nightly build with Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 PRemium (Android 7.1.1).
