### ISSUE TITLE
Clear downloads log and add it to clear browsing data checklist 

### ISSUE THREAD

**Issue by Nirose** [mozilla-mobile/fenix#15181]
### What is the user problem or growth opportunity you want to see solved?

The download logs cannot be cleared from the Downloads screen. nor it is listed in 'delete browsing data' checklist
 
### How do you know that this problem exists today? Why is this important?
it kind of feels like a basic browser feature. clearing a log of  what was downloaded. 

### Who will benefit from it?
people who want to keep their download logs empty.

**Comment by nigelh747** [comment]
Surely this is a bug as downloads used to be deleted as part of the clear data options

**Comment by ekager** [comment]
This feature request is valid but would be blocked on #352 and we can look at this after that is completed

**Comment by liuche** [comment]
As a first step, we could delete the list of files that Fenix saves when downloading. The copy would have to be clear though, about what is being deleted (e.g. the download log vs the downloads themselves) and we would need to decide whether we want to do one way or the other, or one and then the other.

**Comment by Amejia481** [comment]
> As a first step, we could delete the list of files that Fenix saves when downloading. The copy would have to be clear though, about what is being deleted (e.g. the download log vs the downloads themselves) and we would need to decide whether we want to do one way or the other, or one and then the other.

This can be done using the [DownloadUseCase](https://github.com/mozilla-mobile/android-components/blob/ab29a90c889fa5a357974582e53c48d41e81d9fc/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsUseCases.kt#L72) class e.g: `usecase.removeAllDownloads()`

**Comment by mcarare** [comment]
This does not look like it's ready to be worked on. The button for clearing downloads already exists in the Downloads list. 
We still need strings if we are to add this option to the "delete browsing data" feature. 
Also, I think the distinction is not clear between deleting a Downloads list entry and deleting the downloaded item itself.

https://github.com/mozilla-mobile/fenix/issues/352 asks for the file to be deleted, but on testing this, the file is not deleted, just the entry in Fenix Download list is removed.

**Comment by eliserichards** [comment]
@betsymi might have some input on the strings here?? 🤔

**Comment by betsymi** [comment]
To clarify, it appears the files aren't actually being deleted. In that case, I wouldn't recommend we use the word `Delete` and use `Clear` or `Remove` instead. We also wouldn't have a destructive delete button either, as that signifies the user is deleting data, which isn't the case. This is something @apbitner and I are working on, new specs coming soon!

**Comment by betsymi** [comment]
Resolution for this is in #16541

**Comment by apbitner** [comment]
@topotropic That's not a bad idea, however, because we're not actually deleting the downloaded files (we're just removing them from the list), it might be confusing there.

**Comment by AndiAJ** [comment]
Hi **verified as fixed** on both **`Nightly 210127`** and **`86.0.0-beta.1`** using the following devices:
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)
