### ISSUE TITLE
[Bug] Browser stucks in landscape mode after full-screen videos

### ISSUE THREAD

**Issue by ixti** [mozilla-mobile/fenix#15189]
## Steps to reproduce

- go to YouTube.com
- play any video and enter full-screen mode
- stop video
- close tab

### Expected behavior

When I change position to portrait, browser should respect that

### Actual behavior

Browser stuck in landscape mode

### Device information

* Android device: Samsung Galaxy S20+
* Fenix version: 80.1.3

**Comment by LaurentiuApahideanSV** [comment]
Thank you for the report. The issue has already been summited here: https://github.com/mozilla-mobile/fenix/issues/14284. I will close this issue as it will be handled there.
