### ISSUE TITLE
[Bug] Android 11 'ask every time' permission prompt does not work with camera permissions for Sync pairing

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#15195]
## Steps to reproduce
1. Setup permissions for Fenix to ask for camera permissions.
2. Attempt to scan once.
3. Sign out.
4. Sign in again.

### Expected behaviour
 - At 4, you should be prompted with the native UI to provide permissions again so you can allow it to give one-time permissions.

### Actual behaviour
 - It shows the custom UI that takes you to the system settings.
 - You can't use one-time permissions, you have to give it 'allow always' to continue the pairing flow.

### Device information

* Android device: Pixel 4, Android 11
* Fenix version: Nightly 18-09-2020

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7094)

**Comment by hakkikaancaliskan** [comment]
This also happens when scanning qr

**Comment by mariansima** [comment]
This issue was reproduced on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29

**Comment by sflorean** [comment]
Reopened the issue, based on the comment above.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1366674
