### ISSUE TITLE
[Bug] Boomarks context menu can persist outside of bookmarks

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15194]
## Steps to reproduce
On a slower device open the 3 dot menu in bookmarks and quickly click on the back icon
### Expected behavior
The context menu is dismissed
### Actual behavior
It is not
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

  Edit: same issue for history

**Comment by s-ankur** [comment]
![Screenshot_2020-09-19-00-09-34-806_org mozilla fenix](https://user-images.githubusercontent.com/33252312/93633485-b0252f80-fa0c-11ea-9ae4-50d66f141e01.jpg)

**Comment by s-ankur** [comment]
Same problem with the delete history prompt btw. Also it can cause crashes if you use the options in the dislocated menus

**Comment by anotherus3r** [comment]
Yeah, noticed the same thing recently on latest Nightly.
