### ISSUE TITLE
[Bug] Unable to send tabs between devices

### ISSUE THREAD

**Issue by cormacltighe** [mozilla-mobile/fenix#15196]
## Steps to reproduce
Attempt to send a tab from one device to another

### Expected behavior
Tab is received on destination device

### Actual behavior
Sending from desktop: nothing happens, no indication of failure or error
Sending from android: "Unable to send" message appears with retry button, which doesn't work
Using "Sync now" on both devices has no effect.

### Device information

* Android device: Samsung Galaxy S10e
* Fenix version: 80.1.3 (Build #2015762835)

**Comment by jonalmeida** [comment]
I was investigating this as well and it seems to be a system-wide issue with the service; not particular to Fenix:
```
mozilla.appservices.fxaclient.FxaException$Unspecified: Remote server error: '500' '203' 'Internal Server Error' 'A backend service request failed.'
```

**Comment by cormacltighe** [comment]
Good to know it's not just me then.

**Comment by cormacltighe** [comment]
Issue appears to have alleviated itself. No clue why, but I'm not going to look a gift horse in the mouth. I'm going to close this.
