### ISSUE TITLE
Bookmarks management

### ISSUE THREAD

**Issue by XxJibril** [mozilla-mobile/fenix#15209]
### What is the user problem or growth opportunity you want to see solved?
I find it really hard to delete specific bookmarks on the new version of the app, in the old version we were able to hold a bookmark on the suggested results page and delete it but we cant anymore
![Screenshot_20200919-034915_Firefox](https://user-images.githubusercontent.com/61125414/93657578-c7bfe080-fa2b-11ea-9887-f35521d5eb91.jpg)

furthermore in the Bookmarks section it would be really nice to have a search option to browse through those hundreds bookmarks more easily
![Screenshot_20200919-034447_Firefox](https://user-images.githubusercontent.com/61125414/93657605-f8077f00-fa2b-11ea-9518-dc2a8052d8bc.jpg)

### How do you know that this problem exists today? Why is this important?
in my opinion this is really important because it will make bookmarks' management much easier for user

### Who will benefit from it?
anybody who uses bookmarks pretty often

**Comment by ekager** [comment]
Search is here: https://github.com/mozilla-mobile/fenix/issues/12717
Awesome bar context menu here: https://github.com/mozilla-mobile/fenix/issues/2596
Closing as dupe!
