### ISSUE TITLE
Older profiles seem to have slower startups

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15205]
Copied straight from matrix for now b/c end of day; might be better in JIRA or start up spreadsheet:
> acreskey
mcomella: Not urgent, but I think it's important.
I think startup is ~600-800ms slower (G5, CI) with existing profiles and we have chance at improving that.
Yesterday Tarek explained to me that the conditioned profiles are not new profiles + 30seconds of idling (which is what I thought they were).
They are existing profiles from the day prior + 30 seconds of idling.
I was focused on our scenario, but he mentioned that this perf difference could be revealing a real startup delay.
So, going through the CI results with conditioned profiles: (e.g. 3162ms G5)
https://treeherder.mozilla.org/#/jobs?repo=try&tier=1%2C2%2C3&revision=c5f2fba98fb8b3b22668d14097217f7ae114957e&selectedTaskRun=Csgr2Of7SuSV8gp8QLpZpg.0
And without (2617ms, G5)
https://treeherder.mozilla.org/#/jobs?repo=try&tier=1%2C2%2C3&revision=8fd36f665d47c2cc52b6e84dd7cfa321792fe84a&selectedTaskRun=XKgKndA9TdGMSF2pEtYLOA.0
Treeherder
Treeherder
And looking at the multicommit results -- I don't think this is the result of just the binary version changing.
So I think we made the right choice for the current view perftest -- effectively test the new user experience, which is more deterministic.
But this looks like a separate issue that has potential for a big savings:
Longer running profiles show degraded startup performance.
acreskey
I propose we log this and triage it.
In terms of investigating, we can download the CI conditioned profiles, update them to a local build, and then measure their performance, profile them, etc.

**Comment by mcomella** [comment]
Triage: we could investigate the startup time telemetry https://github.com/mozilla-mobile/fenix/pull/14375 to make progress – we expect this to land soon.

**Comment by acreskeyMoz** [comment]
I can't commit to this one yet, but I'm interested in getting to the bottom of this.

**Comment by mcomella** [comment]
Triage: let's wait until the telemetry is ready to better understand start up.
