### ISSUE TITLE
[Bug] Tab tray handle has wrong dimensions

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#15219]
## Steps to reproduce
1. Open the tab tray

### Expected behavior
The dimensions of the handle should be small to indicate a draggable object.

### Actual behavior
The dimensions are very large, looks like a visual glitch.

![tab-tray-handle-wrong](https://user-images.githubusercontent.com/42788925/93667440-1ef29f00-fa86-11ea-9a6e-71c4371bd311.png)

### Device information

* Android device: Sony Xperia Z2, Android 6.0.1
* Fenix version: Nightly 200919 06:03 (Build #2015764785)
AC: 60.0.20200917190518, a1a5c582c
GV: 82.0a1-20200912220312
AS: 61.0.13

**Comment by hwinnemoe** [comment]
As far as I can see, this commit https://github.com/mozilla-mobile/fenix/commit/b5635763357578967f3c486dca679739fcf503cb changed the `private const val NORMAL_HANDLE_HEIGHT = 3` (https://github.com/mozilla-mobile/fenix/commit/b5635763357578967f3c486dca679739fcf503cb#diff-e2de4b768816f0d0beea898195bce335L583) to `<dimen name="tab_tray_normal_handle_height">11dp</dimen>` (https://github.com/mozilla-mobile/fenix/commit/b5635763357578967f3c486dca679739fcf503cb#diff-e4590692aa6da9dc0da05cbe72efa571R175).

**Comment by sflorean** [comment]
Reproducible on Nightly 9/21 with Samsung Galaxy Note10 (Android 10) and Pixel 3 (Android 11).

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200923 06:02 GV 82.0a1 from 9/23 with Samsung Galaxy Tab S3 (Android 8).
