### ISSUE TITLE
Consider not displaying separators in the bookmarks UI

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#15214]

**Comment by grigoryk** [comment]
In https://github.com/mozilla-mobile/fenix/pull/15213 folders are moved to the top of the bookmarks UI, but this creates fun edge cases such as https://github.com/mozilla-mobile/fenix/issues/2792#issuecomment-511971100

I think we only have two options here:
- do nothing and leave it as-is
- _not_ display separators at all to avoid this. Not good for users who care bookmark about separators on mobile, if these exist. I don't think Fennec displayed bookmark separators, but it'll be nice to double check this. We don't allow editing these, anyway...

**Comment by grigoryk** [comment]
Another option is to keep separators and just make them work well (e.g. allowing deleting, moving and maybe even creating them). I'm leaning toward that... Edge case described above seems pretty harmless, and something users can probably understand/expect to happen.

**Comment by CenCerberon** [comment]
![Desktop](https://user-images.githubusercontent.com/71729377/98419741-fbab9f80-2085-11eb-80ce-ef0e742e5100.png)

![Mobile](https://user-images.githubusercontent.com/71729377/98419763-08c88e80-2086-11eb-9159-b3ba3b2c7709.png)

You should also consider syncing between desktop and mobile.
The use of separators on the desktop is very important to me.
Are these edited separators then synchronized back to the desktop?
It would be a shame if you either have fun edge cases on the mobile or on the desktop.

**Comment by topotropic** [comment]
> Another option is to keep separators and just make them work well (e.g. allowing deleting, moving and maybe even creating them). I'm leaning toward that... Edge case described above seems pretty harmless, and something users can probably understand/expect to happen.

@grigoryk Are you saying you're leaning towards removing separators on mobile?

**Comment by grigoryk** [comment]
@topotropic I think so. I'm not sure how we can keep separators and folder re-ordering and _not_ run into weird edge cases. If we add editing capabilities that just complicates things further, e.g. user moves separators around to get things to look right on mobile, but that will mess up their desktop ordering.

One way to work around this is to introduce a separate concept "mobile-only" separators, that will be only shown on mobile, and either not synced at all, or synced to desktop but then hidden. But, this just sounds like a big mess :)

So yeah, let's hide separators from the UI for now.

**Comment by grigoryk** [comment]
https://github.com/mozilla-mobile/fenix/pull/17778

**Comment by grigoryk** [comment]
#17778 landed so this should be available in the next nightly. I've done a basic round of regression testing of the bookmarks functionality - editing, deleting, adding folders, syncing, making changes on other clients (like adding bunch of separators, moving them around, deleting items near separators) and getting all these changes synced back to Fenix. All worked as expected.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 2/4 with Motorola Moto G6 (Android 8) and Nexus 5 (Android 6.0.1), there are no separators in the Bookmarks list, after changing the list and following all the scenarios from the previous comment.
I will close this issue and remove the qa:needed label.

**Comment by amirrh6** [comment]
@grigoryk 
Hi pal!
Is there any plan on bringing separators back to mobile? Shall I open a new issue for this feature request, or it'll be considered as duplicate?

**Comment by grigoryk** [comment]
> @grigoryk Hi pal! Is there any plan on bringing separators back to mobile? Shall I open a new issue for this feature request, or it'll be considered as duplicate?

Hi! Re-reading my notes above, I think the reasons for hiding separators on mobile are still good/valid. What are your use cases for wanting them? Do you use Sync and/or desktop bookmarks?

**Comment by amirrh6** [comment]
> > @grigoryk Hi pal! Is there any plan on bringing separators back to mobile? Shall I open a new issue for this feature request, or it'll be considered as duplicate?
> 
> Hi! Re-reading my notes above, I think the reasons for hiding separators on mobile are still good/valid. What are your use cases for wanting them? Do you use Sync and/or desktop bookmarks?
> 
> Feel free to open a new issue to discuss this, if you want. Please link back to this one for context.

@grigoryk Thanks for your reply. The reasons for hiding separators on mobile are indeed valid but seem to be a temp solution to the underlying issue.

That's how we got so far: (Correct me if I'm wrong.)
1. Root of all evil: "Navigating out of a folder takes you to the top of the list". (Can't find any topic in issues section **specifically** about this)
2. The issue above causes *difficulties* browsing multiple folders.
3. In order to ease the difficulty, folders are pinned to the top.
4. Pinning folders to the top causes scenarios like https://github.com/mozilla-mobile/fenix/issues/2792#issuecomment-511971100
5. In order to avoid the mentioned scenario, Separators shall be hidden :(

I'm just suggesting that the team may could have focused on finding a solution for the main issue (Item 1) rather than pinning folders to the top. 

What do you think about it?

Thank you for your time, and sorry for any possible underestimations about difficulties of developing Android applications.
