### ISSUE TITLE
[Bug]White Background on new tabs

### ISSUE THREAD

**Issue by Mk1378** [mozilla-mobile/fenix#15221]
**[Steps to reproduce]** 

Open a link in a new tab and immediately switch to it or open a link in Firefox from another app.

**[Actual Behavior]** 

Shows a page with white background while loading the website. 

![Screenshot_20200919220250](https://user-images.githubusercontent.com/46780868/93686223-1de36100-faca-11ea-99cb-8850019b61f3.jpg)

**[Expected Behavior]**

While in dark mode the white color should be black or a dark color. 

**Who will benefit from it?** 
Everyone specially people who use dark mode and are using th app at nights.

As I mostly use Firefox at nights this is really annoying.

Thanks

**Comment by hwinnemoe** [comment]
Duplicate of #6313 and BZ-1663732

**Comment by Mk1378** [comment]
Thanks
