### ISSUE TITLE
[Bug] empty space with videos when bottom scroll to hide videos is disabled

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#15222]
## Steps to reproduce
0. Set toolbar to bottom
1. Disable scroll to hide videos
2. Open https://nitter.net/firefox/status/1306263827227578369#m
3. Play the video in fullscreen
4. Rotate to landscape
### Expected behavior
The video fills the screen (except black bars on both sides, because of 18:9 screen playing 16:9 video)

![](https://pic.infini.fr/dwZRdRRz/bVTaC2lM)
(Screenshot with top toolbar)

### Actual behavior
<img src="https://pic.infini.fr/ijEdlLJT/mVCUxxg3.png">
(Screenshot with bottom toolbar)
### Device information

* Android device: Poco F1
* Fenix version: Nightly 200919

**Comment by hwinnemoe** [comment]
Duplicate of #14974, see [this comment ](https://github.com/mozilla-mobile/fenix/issues/14974#issuecomment-694385050) in the issue.

**Comment by B0pol** [comment]
But it was closed, which means fixes. Then I opened another issue because it's not fixed

**Comment by hwinnemoe** [comment]
I just followed the reasoning of this comment https://github.com/mozilla-mobile/fenix/issues/15146#issuecomment-694394184. Anyway, this should be fixed now by #15272.

**Comment by B0pol** [comment]
Yes, it's fixed
