### ISSUE TITLE
[Bug] keyboard does not dismiss when filling link from clipboard in search

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15224]
## Steps to reproduce
1. Open new tab with link in clipboard
2. Press shortcut to open link from clipboard 

### Expected behavior
Navigate to browser with link, keyboard dismisses 

### Actual behavior
Navigate to browser, but keyboard is displayed

### Device information

* Android device: ?
* Fenix version: ?

**Comment by hwinnemoe** [comment]
See #14458

**Comment by ekager** [comment]
closing for #14458
