### ISSUE TITLE
[Bug] Download pop-up notice not disappearing correctly

### ISSUE THREAD

**Issue by XxJibril** [mozilla-mobile/fenix#15239]
## Steps to reproduce
download a file (i only tried with saving pictures but i think it should work with any type of files), don't tap the "x" to close the pop-up, continue scrolling up the page to make it disappear, try scrolling back down again and it reappears

### Expected behavior
once you scroll up without closing the download confirmation pop-up through the "x" button, the whole pop-up message slides down the screen and disappears, that should close it completely

### Actual behavior
but it actually only hides it from the screen, if you scroll down the screen, the message pops back up on the screen

### Device information
* Android device: Samsung Galaxy A7 (2018), Model: SM-A750F/DS, Android 9.0
* Fenix version: 80.1.3

**Comment by codrut-topliceanu** [comment]
@Amejia481 @XxJibril 
Indeed. The download complete dialog is designed to be less intrusive as per https://github.com/mozilla-mobile/fenix/issues/9044 , the user can continue browsing and leave the dialog open for later use.

**Comment by XxJibril** [comment]
i see, i found it so weird i thought it was a bug xD
thanks for making it clear !
