### ISSUE TITLE
Disable Add to Homescreen for about:pages and moz- extensions

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15231]
### What is the user problem or growth opportunity you want to see solved?
About pages (and presumably moz extension pages) are not going to be able to be launched from another app and this includes the system launcher. Since this is the case we should prevent users from accessing this feature in the first place,  so as not to raise any valid complaints as to why it is not working

This will automatically take care of a number of issues like
https://github.com/mozilla-mobile/fenix/issues/13033
https://github.com/mozilla-mobile/fenix/issues/11699
https://github.com/mozilla-mobile/fenix/issues/15167

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7137)

**Comment by s-ankur** [comment]
I think the best option would be to just not show the add it homescreen option in 3 dot menu

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807099

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
