### ISSUE TITLE
[Bug] Cannot find the downloaded files

### ISSUE THREAD

**Issue by Yajo** [mozilla-mobile/fenix#15230]
## Steps to reproduce

Download something.
Try to find the file.

### Expected behavior

Firefox should have a "Downloads" menu somewhere.
Or, when going to the "downloads" section in the file manager, they should appear there.

### Actual behavior

None of the above. You have to open the file manager and go to the "Download" folder in device's internal mentory, and search the file by file name.

### Device information

* Android device: SM-T720 
* Fenix version: 80.1.3 (Build #2015762835)

**Comment by s-ankur** [comment]
This has already been added to Firefox (see https://github.com/mozilla-mobile/fenix/issues/4417) , you can wait for updates or try out the beta version

**Comment by liuche** [comment]
Yes, you can view downloads in 81+, or there is also more discussion in #15762. I'll close this bug since it should be covered by the other two!
