### ISSUE TITLE
[Bug] with dynamic toolbar turned off, gap in content in PWA

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15245]
## Steps to reproduce
1. Turn off swipe to hide toolbar 
2. Open PWA 

![Screenshot_20200920-131548](https://user-images.githubusercontent.com/25442310/93721253-7efb4b00-fb43-11ea-97ec-bd8cc1f45386.png)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200922`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
