### ISSUE TITLE
[Bug]can not go forward in history again once reached mainpage

### ISSUE THREAD

**Issue by OlliKn** [mozilla-mobile/fenix#15241]
## Steps to reproduce 
open a new tab. Open an URL. Follow some links. Tap the history back-button until you are again at startpage. 

### Expected behavior
I can push a history forward Button to reach the Website again (because I maybe tapped the back Button once to often accidently) 

### Actual behavior
I am at startpage and there is no arrow Button in the menue so I have lost the history for this tab. 

### Device information

* Android device: honor 6x
* Fenix version: latest build

**Comment by s-ankur** [comment]
You can still access the tab in the same number of clicks. Just click on the tab counter and click on the highlighted tab. The same amount of clicks would be needed for a hypothetical forward button in 3 dot menu

**Comment by OlliKn** [comment]
Okay , now I see. The last back tap in the history creates a NEW tab. Did not realise that! But it is different behavior from old version and not intuitive. When I want a new tab I should tap new tab somewhere...

**Comment by ekager** [comment]
Thanks for your feedback! As of now, this is expected behavior. So going to close this
