### ISSUE TITLE
[Feature Request] Expand tab multi-select actions

### ISSUE THREAD

**Issue by AerinNight** [mozilla-mobile/fenix#15243]
### What is the user problem or growth opportunity you want to see solved?
Currently, there are a number of actions that can be performed with a selection of multiple tabs on other editions of Firefox, such as bookmark-all, send-to-another-computer-via-Sync, etc. Fenix currently only has one action for a selection of multiple tabs: Save to Collection.

### How do you know that this problem exists today? Why is this important?
I selected multiple tabs on Firefox Nightly, and there were only two buttons: Save and Cancel. This fell far short of my expectation of:
- Cancel
- Bookmark
- Send
- Save
- Close

Lack of these options makes bulk tab usage on a mobile device an arduous management process, rather than a simple 2-button task.

I do cursory research on my phone while away from my main workstation, and as a result of this generally end up with between 5 and 50 open tabs that I then need to send to my main workstation for a more thorough review. The current implementation forces me to send these tabs one at a time, a process that takes ~5 seconds each (partially due to a UI/UX bug with a slow animation; I reported it separately). This _could_ take ~15 seconds _total_ for all 50 tabs, if I could simply multi-select them and send them all at once. 

**Bonus points** if there's also an option to close all these tabs after I've sent them to another device.

### Who will benefit from it?
Tech professionals, researchers, writers, power-users, tabletop gamers; anyone who utilizes many tabs at once for research purposes.

**Comment by s-ankur** [comment]
What does cancel mean for a tab?

**Comment by AerinNight** [comment]
Oh - standard Android multi-select paradigm, you should have a 'start'-aligned 'cancel' button that removes all selections and returns to a non-multi-select UI. Less of a "tab action" than a "go back" action, at that point. This already exists in the current implementation, opposite the Save button.

**Comment by Poopooracoocoo** [comment]
#16132

**Comment by ekager** [comment]
More options have been added! Closing

**Comment by AerinNight** [comment]
Y'all are the best. Thanks!
