### ISSUE TITLE
[Bug] Toast visibility blocks interaction with other buttons

### ISSUE THREAD

**Issue by AerinNight** [mozilla-mobile/fenix#15242]
## Steps to reproduce
- Select an open tab
- Tap the Vertical-Ellipsis Button for "more actions"
- Tap the Share Button
- Tap a device to send the tab to via Sync
> Share menu closes, "Tab sent!" toast appears
- Tap on [8] button for open tabs, to select a new tab or close one

### Expected behavior
**(Preferred):**
The button to open the Tabs menu responds immediately and opens to allow selection of a new tab or closing the current one. The Toast being visible does not obstruct or preclude use of any other screen control.

**(Alternate):**
Tapping the browser window anywhere outside of the "Tab sent!" toast should dismiss the toast immediately instead of waiting for the timeout.

### Actual behavior
**(Preferred):**
While the "Tab sent!" toast is visible, the button to open the tabs menu is un-interactable; it does not respond to any touches until the toast disappears. The tabs menu cannot be opened until the toast expires.

**(Alternate):**
Touching the screen outside of the toast doesn't dismiss it.

### Device information

* Android device: Pixel 3 XL running Android 10
* Fenix version: Nightly 200919 06:03 (Build #2015764787) AC: 60.0.20200917190518, a1a5c582c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7154)

**Comment by s-ankur** [comment]
Related #7709

**Comment by mystiquewolf** [comment]
Not stale.

**Comment by E0697** [comment]
Same happens with the bookmark deletion toast.

**Comment by mystiquewolf** [comment]
Not stale.

**Comment by vitaminj** [comment]
Addendum to "Actual behavior" as I commented on the ticket I just linked - the first press on the tab icon after sending a tab shows the touched animation but doesn't actually work - you have to press it a second time.

**Comment by vitaminj** [comment]
The double tap issue appears to have been fixed in 103 but the main issue still remains

**Comment by lilydjwg** [comment]
I added a new bookmark and deleted an old one. Next I wanted to close the newly bookmarked tab. But no! What I actually clicked on was the undo button on the "bookmark deleted" toast!

I notice that after copying the URL, the toast is shown above the URL bar so that I can edit the URL immediately. I hope this can happen to other toasts.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807136

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
