### ISSUE TITLE
[Bug]Cannot display the options at the bottom of about:config

### ISSUE THREAD

**Issue by Rosabis** [mozilla-mobile/fenix#15254]
## Steps to reproduce
1.Enter about:config in address bar
2.Swipe to the bottom of the page
### Expected behavior
Can see all the items
### Actual behavior
The bottom item is blocked by the URL bar at the bottom,see screenshot

![Screenshot_2020-09-21-08-30-09-439_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/32984303/93725946-d8b45180-fbe5-11ea-8903-42514cfddbe1.png)
### Device information

* Android device: Oneplus 7
* Fenix version: 80.0

**Comment by hwinnemoe** [comment]
Which version of Fenix are you using, see _Settings_, _About Firefox_? There is no up-to-date version that is currently published that has this version number.

In any case: fixed in Nightly, see #14466.
