### ISSUE TITLE
[Bug] Paste button goes down

### ISSUE THREAD

**Issue by whichbuffer** [mozilla-mobile/fenix#15250]
## Steps to reproduce
1.Try to paste something inside the search input box with long press.
2. Paste button goes bottom of main activity.
### Expected behavior
Normally in my Android device that pasting button section pops up to where I long clicked.
### Actual behavior
![image](https://i.ibb.co/grP2cvw/Whats-App-Image-2020-09-21-at-00-30-07.jpg)
### Device information

* Android device: SM-A505F
* Fenix version: 80.1.3

**Comment by kbrosnan** [comment]
Does this happen all the time or only when first switching to toolbar on top? Does this happen on [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)? I recall us addressing an issue like this.

**Comment by whichbuffer** [comment]
Thanks for the fast response , I was update this version to **81.1.1** and bug is fixed  :)
No it's not Nightly version.
