### ISSUE TITLE
[Bug] Modify the position for the "Create a new account" text on the Sign In page

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#15262]
## Steps to reproduce
1. Access the Sign In Page.
2. Observe the newly added `Create a new account` text.
### Expected behavior
The text should be [positioned a little bit lower.](https://app.abstract.com/share/634f7381-3cae-47e9-b686-5b8e8a21786b?mode=design&sha=8f8eb8c8cfb464937f96392eed3bc239750fc840)
### Actual behavior
The `Create a new account` text is too close to the `use email instead` button.
### Device information

* Android device: **Google Pixel 4XL (11).**
* Fenix version: **Nightly 9/21.**

Mock
![93753068-3ce80d00-fc08-11ea-8ac9-ddcb033aea0b](https://user-images.githubusercontent.com/42831109/93753196-715bc900-fc08-11ea-82d0-5f399bbb4f68.png)
Latest Nightly
![unknown](https://user-images.githubusercontent.com/42831109/93753159-5e48f900-fc08-11ea-8272-3d8ab9c313fb.png)

**Comment by ekager** [comment]
Looks like the margin should match whatever the margin is from the bottom of the image to the top of the first button

**Comment by ayonya100** [comment]
@ekager I have raised a PR for this.

**Comment by abodea** [comment]
I re-checked this issue on the latest **Nightly 9/23** and latest **Beta 82.0.0.b1** and please note that the text is now correctly positioned. 
Also, note that there is a regression as the space between `Ready to scan` and `Use email instead` is way too big.

Removing the `eng:qa:needed` until further notice.

![Screenshot_20200923-144929](https://user-images.githubusercontent.com/42831109/94010182-41e6c100-fdae-11ea-9077-d710861349ae.png)

**Comment by sanchi0204** [comment]
Can I work on this?
