### ISSUE TITLE
Multiple Firefox apps show in open app screen

### ISSUE THREAD

**Issue by firefoxuser1** [mozilla-mobile/fenix#15260]
With no Firefox apps running, when I press on the firefox app icon, it opens two copies of the app according to the open app screen (see screenshot). Only one is usable, meaning if I press on the unusable one I go right back to the usable one. Neither close if I choose quit in the app and if on the open app screen I swipe one up to quit the other does not automatically quit. I have no idea if the data cleaning that is supposed to take place on browser close is happening.

[Screenshot](https://photos.app.goo.gl/4gPf6REQmRK7WdfJ8) 

Pixel 3a running Android 11 w/ Sept 5, 2020 security update
w/ Firefox 80.1.3 (Build #2015762835)

**Comment by cadeyrn** [comment]
Duplicate of #13270.

**Comment by firefoxuser1** [comment]
Similar to 13270 issue mentioned, but there was no quick action on my part and I am not running a beta version. It's always does this. Can this result in a security issue where data is leaked through the second running instance? Also, I only skimmed everything on 13270, but it seems like the issue information I provided was not already present. Let me know if I can provide any more info. Thanks

**Comment by kbrosnan** [comment]
This is still a duplicate.
