### ISSUE TITLE
[Bug] Open Links in App Preference is not properly updated.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#15263]
Noticed when testing https://github.com/mozilla-mobile/fenix/issues/15150.

`settings.openLinksInExternalApp` is always false, even when switch is on in Settings screen.

**Comment by AndiAJ** [comment]
Hi, as per [this comment](https://github.com/mozilla-mobile/fenix/issues/15150#issuecomment-697302076), **verified as fixed** on both **`Nightly 200923`** & **`82.0.0-beta.1`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
