### ISSUE TITLE
[Bug]"metrics.has_top_sites": remains set to false

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15265]
## Prerequisites
Have a clean profile or a fresh install.

## Steps to reproduce
1. Generate the **`metrics`** ping having only the default top sites displayed on the home screen
2. Navigate to a coupe of pages and pin the as top sites
3. Navigate to a couple of websites displaying them as frequently visited top sites
4. Generate the **`metrics`** ping

### Expected behavior
Step 1 & 4 "metrics.has_top_sites": true

### Actual behavior
Step 1 & 4  "metrics.has_top_sites": false

### Device information

* Android device: all
* Fenix version: Nightly Build 200921

### Notes
From the attached Logcat:
Step 1 `metrics` Ping **`5e4582d1-f96c-4897-a65b-22574b4a648f`**
Step 4 `metrics` Ping **`3228e355-b7bf-4d9a-b784-03571462ec0d`**

[Logcat](https://github.com/mozilla-mobile/fenix/files/5255460/MTS.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t21091)

**Comment by ekager** [comment]
originally added these in https://github.com/mozilla-mobile/fenix/issues/8125 but looks like when we changed the way we show top sites, we never are updating `Settings.topSitesSize` anymore

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201015`** build using a Google Pixel 3a (Android 11)

✔️ Have **only the default top sites** - Ping 5ad0accb-a370-4067-8a28-7f31a9afee15
`"metrics.has_top_sites": true`
✔️ **Delete all the default top sites** - Ping 327c8838-b664-4880-9184-45ff6f0f598e
`"metrics.has_top_sites": false`
✔️ Have **only pinned top sites** - Ping e799c348-0298-4b61-abc5-e27ca1501315
`"metrics.has_top_sites": true`
✔️ **Delete all the pinned top sites** - Ping 79ad935e-0cd4-4f47-9f63-536b2b69f075
`"metrics.has_top_sites": false`
✔️ Have **only frequently visited top sites** - Ping 832a22ef-c832-4d9e-bf27-8d4f679308a1
`"metrics.has_top_sites": true`
✔️ **Delete all the frequently visited top sites** - Ping 07677185-c9ea-475d-9d56-e37b6c9e7da8
`"metrics.has_top_sites": false`

[Logcat](https://github.com/mozilla-mobile/fenix/files/5384405/TS1.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t151001)

✔️ Have **default top sites + pinned top sites** - Ping 86dec592-07a3-431c-ac09-1caabdccb0eb
`"metrics.has_top_sites": true`
✔️ **Delete all top sites** - Ping 2f518d53-7bde-4dc4-b4b1-fbba7571659e
`"metrics.has_top_sites": false`
✔️ Have **pinned top sites + frequently visited top sites** - Ping 45e04117-63a2-43eb-a352-c274094a150a
`"metrics.has_top_sites": true`
✔️ **Delete all top sites** - Ping c6525134-a9a6-4076-b0be-2f5ea11d492d
`"metrics.has_top_sites": false`

[Logcat](https://github.com/mozilla-mobile/fenix/files/5384434/TS2.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t151002)

✔️ Have **default top sites + frequently visited top sites** - Ping ff51d6ce-e990-4b4d-9e14-4a9d18a19339
`"metrics.has_top_sites": true`
✔️ **Delete all top sites** - Ping bb265d93-2eed-4c1a-91b6-1672eb2fc438
`"metrics.has_top_sites": false`

[Logcat](https://github.com/mozilla-mobile/fenix/files/5384449/TS3.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t151003)

✔️ Have **default top sites + pinned top sites + frequently visited top sites** -  211c832f-5827-4034-b43f-1589852ce4ea
`"metrics.has_top_sites": true`
✔️ **Delete all top sites** - 6dbb4415-365e-451c-987b-dd421a3d3939
`"metrics.has_top_sites": false`

[Logcat](https://github.com/mozilla-mobile/fenix/files/5384461/TS5.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t151005)

✅ Also, the `"metrics.top_sites_count"` and was updated accordingly in each case.
