### ISSUE TITLE
[Bug] The latest created bookmark folder is not at the top of the list

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#15261]
## Steps to reproduce
1. Launch Fenix;
2. Go to Settings - Bookmarks;
3. Create a new bookmark folder by tapping on the add bookmark folder icon from the top right corner;
4. Observe the new bookmark folder in the Bookmarks list.
### Expected behavior
The latest created bookmark folder is at the top.
### Actual behavior
The latest created bookmark folder is displayed as the last folder in the list.

![20200921_110019](https://user-images.githubusercontent.com/48799384/93744209-220e9c00-fbfa-11ea-84c1-9fe7fb74dabc.gif)

### Device information

* Android device: Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 200921 06:05 (Build #2015765171) GV 82.0a1 from 9/21

**Comment by grigoryk** [comment]
I don't think this is a bug per-se, and this behaviour feels correct to me (e.g. moving items into folders places them to the bottom of the list, so this is consistent with that).
