### ISSUE TITLE
[Bug] Cannot complete request on twitter and linkedin

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#15282]
## Steps to reproduce
open https://twitter.com
### Expected behavior
visit twitter
### Actual behavior
![Screenshot_20200921-225825_Firefox_Nightly](https://user-images.githubusercontent.com/922368/93814970-f8875c00-fc5d-11ea-8077-3fcb3718692d.png)

### Device information

* Android device: OnePlus 5t
* Fenix version: nightly

**Comment by evilpie** [comment]
Probably just the Fenix version of https://bugzilla.mozilla.org/show_bug.cgi?id=1665368

**Comment by ale82to** [comment]
maybe same bug I ve just reported?
https://github.com/mozilla-mobile/fenix/issues/15289

**Comment by Breenster** [comment]
Current workarounds:

* open mobile.twitter.com in a private tab

* open twitter.com as a desktop site

**Comment by andreicristianpetcu** [comment]
mobile.twitter.com works in normal tab

**Comment by andreicristianpetcu** [comment]
same with linkedin
![Screenshot_20200923-094552_Firefox_Nightly](https://user-images.githubusercontent.com/922368/93976419-a2abd480-fd81-11ea-87b5-e0755d6c3107.png)

**Comment by andreicristianpetcu** [comment]
This is fixed. Closing.
