### ISSUE TITLE
[Bug] Drops frames when scrolling gfl.zzzzz.kr using Dark Reader

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15281]
From: https://www.reddit.com/r/firefox/comments/iwjh7u/frame_drops_when_scrolling_page_with_many_images/

### **Describe the bug**

User reports that Firefox for Android drops frames when scrolling on pages with many images.

### **Steps to reproduce**

- Go to https://gfl.zzzzz.kr/story.php?q=-33-40&lang=ko
- Scroll up and down

### **Expected behavior**

No frame drops.

### **Actual behavior**

Dropped frames. 

### **Screenshots**

Profile: https://share.firefox.dev/3iOpT35

### **System Information:**
 - OS: lineageos official 16.1
 - Browser: Firefox for Android Nightly
 - Dark Reader version: 4.9.19

### **Additional context**

User is on a LeEco Le 2 snapdragon version(codename s2)

WebRender did not help the issue for them, neither did enabling the warp interpreter in Firefox (`javascript.options.warp` set to true).

Previously filed on https://github.com/darkreader/darkreader/issues/3676 but they think the issue is Fenix.

**Comment by djdisodo** [comment]
it can be reproduced here
[link](https://wallpapercave.com/8k-desktop-hd-wallpapers) 

seems happening if there are many high resolution images

**Comment by gitgitgitg** [comment]
Hi,

can this bug get resolved?
