### ISSUE TITLE
[Bug] Incorrect root folder name when creating a folder

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#15284]
Instead of "Bookmarks" we're currently showing "mobile" for the default root folder name when trying to add a folder at the top level. Same underlying issue as https://github.com/mozilla-mobile/fenix/issues/11502 (fixed by https://github.com/mozilla-mobile/fenix/pull/15207)

**Comment by grigoryk** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/15285

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200923 06:02 GV 82.0a1 from 9/23 and Beta 82.0.0-beta.1 GV 82 from 9/23 with Samsung Galaxy Tab S3 (Android 8) and Pixel 2 (Android 9).
I will close this issue and remove the qa:needed label.
