### ISSUE TITLE
[Bug] serious problem with Google sites in general 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#15289]
since two days I often get trouble using Google search or even Google sites in general (like play).
first thing I tought may be some corrupted cookie I cleared data but problem persist, luckily I ve got two phone the one I use less with nighlty from 2 days ago has no issue at all so there must be some bugs in latest nighlty. 
to trigger the bug simply perform many Google search one after the other until u got the message connection was reset and nothing load 
see screenshot:
https://drive.google.com/file/d/1P2HzcX7y8UMQTS-2j3IcDmHcpk8E1M8s/view
any clues how to solve the issue?

**Comment by ale82to** [comment]
even today nighlty build has this issue can someone confirm, 3 days ago nighlty works perfectly what the hell hasbeen changed?

**Comment by andreicristianpetcu** [comment]
Is this fixed? I closed the duplicate I reported.

**Comment by ale82to** [comment]
no the issue may be different : 
close Firefox then try to launch a web address using shell command like am start -a android.intent.action.VIEW -d www.apkmirror.com and nothing load until 4/5days ago this did not happen

**Comment by ekager** [comment]
@ale82to can you still reproduce this?
