### ISSUE TITLE
Limit CFRs to once every 3 days

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15291]
As discussed with Adam in this Jira ticket https://jira.mozilla.com/browse/FNX-14286

We want to limit the number of CFRs a user will see to a max of 1 every 3 days.

Current list of CFRs in app as of writing this:
1- ETP
2- Open in App
3- Search Widget
4- Private mode shortcut (although unlikely to overlap with any other ones)
5- PWA

**Comment by andreicristianpetcu** [comment]
what are CFRs?

**Comment by cadeyrn** [comment]
**C**ontextual **F**eature **R**ecommendations.

**Comment by sflorean** [comment]
Verified as fixed on 82.0.0-beta.1. I will close this as verified but continue to check every 3 days for the CFR limit.
