### ISSUE TITLE
"Switch to new tab" snackbar/popup should appear in the same place as the context menu

### ISSUE THREAD

**Issue by yump** [mozilla-mobile/fenix#15293]
### What is the user problem or growth opportunity you want to see solved?

When a link is opened in a background tab and the user wants to immediately switch to it, the button to do that is very far away and on an awkward part of the screen.

Instead, the popup should appear beneath the user's finger, making "open in foreground tab" implicitly available as a quick double-tap.  Like this:

![both](https://user-images.githubusercontent.com/2214413/93838318-d4704e80-fc4e-11ea-8d43-64311a5dd28c.png)

(I took the liberty of making it 20% transparent, to make it possible to read the text behind.  Might go up to 25 or 30%.)

### How do you know that this problem exists today? Why is this important?

I keep having to do uncomfortable thumb gymnastics or hit the snackbar with my nose. Someone else requested "open in foreground tab," in issue #14414.

### Who will benefit from it?

Because inconsiderate web devs commonly do things that break the back button or defeat the bfcache, many users have been trained to always open links in new tabs. This change would greatly streamline the open-in-new-tab workflow.

**Comment by Dunexus** [comment]
Quoting snackbar spec : https://material.io/components/snackbars

> Containers should be completely opaque, so that text labels remain legible.

> Snackbars should be placed at the bottom of a UI, in front of app content.

It would be weird for users to have this specific snackbar having a different behavior from all other snackbars on their phone.

**Comment by yump** [comment]
Then perhaps it should be something other than a snackbar, or perhaps #14414 needs to be re-opened.  The bottom line is that the current UI is way too inefficient.

**Comment by ekager** [comment]
Closing because it's against material guidelines
