### ISSUE TITLE
[Bug] Can't delete or rename the child folder after moving the parent bookmark folder 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15296]
## Prerequisites
Have a "Parent" Bookmarks folder created
In the "Parent" folder have a "Child" folder created

**E.g.**
```
Parent
↳ Child
```
## Steps to reproduce
1. Open the Bookmarks section
2. Move the "Parent" folder into the "Child" folder 
3. Open the "Parent" folder:
3.1 Delete the "Child" folder
3.2 Edit and rename the "Child" folder 

### Expected behavior
Step 2 : Shouldn't be able to move the "Parent" folder into the "Child folder" ❓ 
Steps 3.1 and 3.2 : Should be able to delete or rename the "Child" folder

### Actual behavior
Step 2 : You can move the "Parent" folder into the "Child" folder but **nothing actually changes** 
Steps 3.1 and 3.2 : **Can't delete or rename** the "Child" folder

### Device information

* Android device: all
* Fenix version: Nightly Build 200922

### Notes
► Video
![20200922-095509](https://user-images.githubusercontent.com/51314259/93853238-2dc29700-fcbc-11ea-960a-6574b5c720bd.gif)

@grigoryk ☺️

**Comment by grigoryk** [comment]
`Move the "Parent" folder into the "Child" folder` let's make that impossible in the UI.

**Comment by grigoryk** [comment]
Thanks for finding these, @AndiAJ ! I really should have thought of this case earlier :) Should be fixed by https://github.com/mozilla-mobile/fenix/pull/15363 once that lands.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200925 06:01 GV 83.0a1 from 9/25 with Motorola Moto G6 (Android 8).
I will close this issue and remove the qa:needed label.

**Comment by AndiAJ** [comment]
Reproducible on **`RC 81.1.2`** using a OnePlus A3 (Android 6.0.1)
