### ISSUE TITLE
[Bug] The music.youtube PWA is opened in a custom tab

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15297]
## Steps to reproduce
1. Navigate to music.youtube.com
2. Install it as a PWA
3. Open the music.youtube PWA

### Expected behavior
The PWA is properly opened

### Actual behavior
The PWA is opened in a custom tab

### Device information

* Android device: all
* Fenix version: Nightly Build 200922

### Notes
► Video
![20200922-111416](https://user-images.githubusercontent.com/51314259/93858599-10de9180-fcc5-11ea-88d0-939f9a28acd6.gif)

**Comment by mcarare** [comment]
Looked into this, I think this is expected, because manifest for YouTube Music has set `"display":"minimal-ui"`.
