### ISSUE TITLE
[Bug] Gap appears above sticky header when swiping

### ISSUE THREAD

**Issue by gollmar** [mozilla-mobile/fenix#15302]
## Steps to reproduce

1. Load a website with a fixed header (e.g., an article from https://gothamist.com)
2. Swipe down
3. Swipe back up
4. Swipe down again

### Expected behavior

I expect the header to remain fixed in place when I swipe up and down. 

### Actual behavior

The sticky header moves down a few pixels when I swipe down, creating a small gap. It moves back up a few pixels when I swipe back up.

![Screenshot_20200922-073221](https://user-images.githubusercontent.com/1475108/93878163-9a7f6680-fca7-11ea-8b4b-2c44613d894b.jpg)
Before swiping up and back down (no gap)

![Screenshot_20200922-073238](https://user-images.githubusercontent.com/1475108/93878181-a23f0b00-fca7-11ea-97e1-4ced8aae1511.jpg)
After swiping up and back down (gap above header)

### Device information

* Android device: OnePlus 6T
* Fenix version: 80.1.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7251)

**Comment by LinAGKar** [comment]
This happens on Reddit as well.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 200925 (Build #2015765939).

### Device used:
- OnePlus 6T (Android 9)

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Firefox Nightly 210324.
### Device used:
- OnePlus 6T (Android 9)

**Comment by giorgosmatzarapis** [comment]
Hello, 
I face exactly the same bug.
Any update?

**Comment by LinAGKar** [comment]
This bug is still around
