### ISSUE TITLE
search function in the history section 

### ISSUE THREAD

**Issue by joelocandol** [mozilla-mobile/fenix#15303]
### What is the user problem or growth opportunity you want to see solved?

If you want to search for a webpage in the history section, you has to make through all the other sites shown in it. Even if you knew a key word that could help you to find it more quickly

**Comment by LaurentiuApahideanSV** [comment]
Hello and thank you for the report. A feature request for searching in the History section has already been requested here: https://github.com/mozilla-mobile/fenix/issues/11788. I will close this issue as it will be handled there.
