### ISSUE TITLE
delete data browsing on quit

### ISSUE THREAD

**Issue by avie25000** [mozilla-mobile/fenix#15301]
## Steps to reproduce
1. Enable Delete data browsing on quit
2. Uncheck delete open tabs and delete cookies
3. Open youtube.com and play some video
### Expected behavior
Browser should end it session and reload tabs once reopen
### Actual behavior
Browser didn't end it session and didn't reload any tabs
### Device information

* Android device: Xiaomi Redmi Note 4, A10
* Fenix version AC: 60.0.20200921130100

**Comment by kbrosnan** [comment]
If you have not selected quit from the menu item then this is working as expected. There needs to be some user action to clear the data besides swipe closing the app which is indistinguishable from the OS killing Firefox in the background
