### ISSUE TITLE
[webcontent] FTP apk download link not update

### ISSUE THREAD

**Issue by evan0greenup** [mozilla-mobile/fenix#15300]
### Describe the bug

The FTP download link for Firefox Mobile (Android) apk file is not updated, the download apk file is still for 68.x not for latest Fenix version. 

The problem is appeared in both [https://www.mozilla.org/en-US/firefox/all/#product-android-release](https://www.mozilla.org/en-US/firefox/all/#product-android-release) and [https://wiki.mozilla.org/Mobile/Platforms/Android](https://wiki.mozilla.org/Mobile/Platforms/Android)

### Expected behavior
It should be now for version 81.x.x

**Comment by kbrosnan** [comment]
This is not a Fenix bug. https://github.com/mozilla/bedrock/issues is where the Mozilla website is maintained.
