### ISSUE TITLE
[Bug] Translation for the reading options "Appearance" not displayed correctly on small display devices 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15312]
### Steps to reproduce
1. Change the language to French or Ukrainian.
2. Open an article and enter reading mode.
3. Tap on menu - > appearance. 

### Expected behavior
The translated words are displayed on one line, or two without visual issues. 

### Actual behavior
One word displayed on two lines.

### Device information
* Android device: Google Pixel 3 (Android 11).
* Fenix version: Nightly 9/22

![Screenshot_20200922-164723](https://user-images.githubusercontent.com/58466444/93904013-068eb880-fd02-11ea-8b38-a1a8495be38a.png)

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Release 87.0.0-rc.1, Beta 87.0.0-beta.6 and Nightly 3/22 with Pixel 2 (Android 9).
