### ISSUE TITLE
Not able to select first option in the location dropdown of StackOverflow's job application page in Desktop Site mode

### ISSUE THREAD

**Issue by viraniac** [mozilla-mobile/fenix#15313]
Steps to Reproduce

1) Open any job application on StackOverflow that uses their own application form. Ex. [Application page for IOVLABS](https://stackoverflow.com/jobs/apply/416113?reset=False&ra=2fybyLHT9J7i&oqs=a%3D2fybyLHT9J7i%26so%3Dp%26sec%3DFalse%26pg%3D1%26offset%3D5%26total%3D5924%26srp%3DTrue%26so_medium%3DInternal%26so_source%3DJobSearchPreview%26_%3D1600791325104)
2) Request desktop site by toggling on the Desktop site toggle in the menu
3) Select Location text box and enter partial value for the location. Ex. Enter "Mum" for Mumbai
4) A drop-down will appear under the Location text box. Try to select the first value. Ex. "Mumbai, Maharashtra, India"
5) Click on the first option in the dropdown to select it.

Expected Behaviour: The Location text box should get populated with the selected value

Actual Behaviour: Nothing happens when you try to select the first option.

**Comment by Amejia481** [comment]
This looks like something in GV.  I opened this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1666792 for the team to take a look.

**Comment by kbrosnan** [comment]
Closing platform bug
