### ISSUE TITLE
FNX3-15625 ⁃ [Bug] regression: "Delete history" button no longer works

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1531]
### Steps to reproduce
1. open history
1. press the "delete history" button

### Expected behavior
You have an empty history.

### Actual behavior
Nothing happens.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision f36da2d8f22e769294b42fbd0f2081e835071225

**Comment by sv-ohorvath** [comment]
Can reproduce. Also valid for deleting a multiple selection.

**Comment by cadeyrn** [comment]
I compiled a new build, now revision 9de120b8ab793794190617df93cc751470497121. I can still reproduce. The "Delete history" button does not work. Also deleting a mulitple selection does not work. Only deleting a single bookmark works.
