### ISSUE TITLE
Firefox for android is suddenly only loading old (cached?) pages of many websites

### ISSUE THREAD

**Issue by handyguy2** [mozilla-mobile/fenix#15311]
Two of my android devices (running current Firefox, and Android 9 and Android 10) load the same many days old web pages when a site is selected. It is not a currently open tab, and has been happening for 2-4 days now. Clicking refresh does load the latest page. nytimes.com, washingtonpost.com, etc. I have not changed any settings in months. I have rebooted the devices and no improvement.

**Comment by s-ankur** [comment]
Can you try long pressing the refresh button? It may solve your immediate problem

**Comment by handyguy2** [comment]
Refresh button does load most current page, long press makes no difference - still initially loading old pages.

**Comment by TrianguloY** [comment]
Are you opening those pages from collections? Collections save properties of the tabs, and I think this includes the page state (I may be wrong though)

**Comment by handyguy2** [comment]
Yes! The problem started when I started using collections, I put my daily favorites in. Guess collections are not too useful if that's how they function. Thanks!

**Comment by chrisvdb** [comment]
Wow, I had the same problem... this is not obvious at all!

**Comment by kbrosnan** [comment]
Duplicate #10417
