### ISSUE TITLE
FNX3-15626 ⁃ [Bug] History: Redirects should be taken into account

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1532]
* clone of #1332 --

#1332 was closed because there was a fix but the fix does not work at all. Since it seems my comments in the closed ticket receives no attention from the developer who implemented the original fix I created a new ticket to make sure it's not overlooked.

### Steps to reproduce
1. enter "google.de" in the address bar
1. open history

### Expected behavior
only one entry in history.

### Actual behavior
four :warning: entries in history, about:blank (that's #1318) and one for every redirect.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision f36da2d8f22e769294b42fbd0f2081e835071225

**Comment by grigoryk** [comment]
Thanks for filing!

We might not be storing these visits with correct types. That is, we are filtering them on display, but if they’re stored as non-redirects, that obviously won’t help. I’ll take a deeper look and report back.

**Comment by cadeyrn** [comment]
It's fixed in current builds.

**Comment by sv-ohorvath** [comment]
Verified as fixed on 5/20.
