### ISSUE TITLE
[Bug] can't access closed tabs from tab tray if no tabs open

### ISSUE THREAD

**Issue by LinAGKar** [mozilla-mobile/fenix#15324]
## Steps to reproduce
1. Close some tabs
2. Open the tab tray

### Expected behavior
The option to reopen tabs should be there.

### Actual behavior
The menu button is completely gone. Most menu items pertain to the current tab, so it's fine for them, but "recently closed tabs" and "tab settings" should still be there even if no tabs are open.

### Device information

* Android device: ONEPLUS 5, LineageOS 16
* Fenix version: Nightly 200922 16:54 (Build #2015765451)

**Comment by ekager** [comment]
cc @topotropic for tabs tray menu feedback

**Comment by topotropic** [comment]
Yes, that makes sense. Thanks. 

Summary:
When the tab tray has 0 tabs the menu is still accessible and has the following entries: "Tab settings", "Recently closed tabs".

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200929 05:08 (Build #2015766697) GV 83.0a1 from 9/29 with Motorola Moto G6 (Android 8) and Nexus 5 (Android 6.0.1).
I will close this issue and remove the qa:needed label.
