### ISSUE TITLE
[Bug] disable ink-skipping

### ISSUE THREAD

**Issue by lvmm** [mozilla-mobile/fenix#15339]
Firefox for android skips underlining in underlined links where character descender goes below baseline. Latest desktop Firefox renders such links correctly.

## Steps to reproduce
go to mozillazine.org

### Expected behavior
underlining is uninterrupted

### Actual behavior
underlining is broken at each character descender e.g. p's or g's on the attached screenshot

### Device information

* Android device: Caterpillar S61, android 9
* Fenix version: 81.1.1
![Screenshot_20200923-113820](https://user-images.githubusercontent.com/11752339/93989930-2c17d280-fd93-11ea-871d-257efb0b90f8.png)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1666988
