### ISSUE TITLE
[Bug] Pinch-zooming has stopped working in the Android emulator in recent Fenix nightlies

### ISSUE THREAD

**Issue by theres-waldo** [mozilla-mobile/fenix#15330]
I am unable to pinch-zoom any website in recent Fenix nightlies when running them on the (x86) Android emulator.

This last worked in the 2020-08-28 nightly, and stopped working in the 2020-08-29 nightly.

Pinch-zooming in the GeckoView Example app works fine, so I assume this is not an issue in GeckoView.

**Comment by theres-waldo** [comment]
(In addition to checking that it works in GVE, I did rule out any APZ-level issues by running a local debug build of Fenix. APZ does not receive touch events for pinch gestures at all, suggesting that the issue is at an earlier layer in the system, e.g. Android widget code or Java code.)

**Comment by kbrosnan** [comment]
I'm not able to pinch zoom on a taskcluster build from https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-x86-opt on my touch screen laptop using Windows 10 and the Android Emulator.

**Comment by kbrosnan** [comment]
This seems like a platform bug given that I can reproduce in GVE.

**Comment by theres-waldo** [comment]
> I'm not able to pinch zoom on a taskcluster build from https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-x86-opt on my touch screen laptop using Windows 10 and the Android Emulator.

Sorry, I should clarify: I was talking about pinch-zooming on a non-touchscreen, using Ctrl+Drag. That works for me in GVE, but has regressed in Fenix.

(I expect the emulator passing through touchscreen pinch gestures is an unrelated issue.)

**Comment by theres-waldo** [comment]
@kbrosnan What can we do to get this diagnosed further?

This is impeding my ability to test Fenix STR related to pinch-zooming in the Android emulator for development purposes / investigating GV bugs.
