### ISSUE TITLE
Swipeable side drawers for bookmarks and tabs

### ISSUE THREAD

**Issue by estUser1** [mozilla-mobile/fenix#15333]
### What is the user problem or growth opportunity you want to see solved?

I'd like to see swipeable side drawers for tabs and bookmarks. Lightning Browser (https://play.google.com/store/apps/details?id=acr.browser.lightning) does this perfectly imo and it's such an enjoyable way to use a mobile browser.

### Who will benefit from it?

Everyone

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7295)

**Comment by gurmeetim** [comment]
Ther is already issue abou homescreen
See this https://github.com/mozilla-mobile/fenix/issues/12065

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
