### ISSUE TITLE
[Bug] Volatile tab has huge share button

### ISSUE THREAD

**Issue by Yajo** [mozilla-mobile/fenix#15334]
## Steps to reproduce

1. Make Firefox your default browser.
1. Oper any link in any app that uses Android's "volatile tabs" feature or however that's called... you know, those browser tabs that don't inclu de the whole browser UI).

### Expected behavior

Look normal.

### Actual behavior

Share button is huge.

### Device information

* Android device: Samsung SM-T720
* Fenix version: 80.1.3 (Build #2015762835)

**Comment by s-ankur** [comment]
Can you include a screenshot? For me the custom tab interface looks like this
![Screenshot_2020-09-23-11-18-45-894_org mozilla fenix](https://user-images.githubusercontent.com/33252312/93971830-af82f500-fd8e-11ea-928b-337b6b8eddd7.jpg)

**Comment by Yajo** [comment]
This is from my SM-J600FN/DS:

**Comment by Yajo** [comment]
This is from my SM-J600FN/DS:
![Screenshot_20200923-205143_Firefox](https://user-images.githubusercontent.com/973709/94101877-0fca7300-fe31-11ea-82b5-4742b5b08698.jpg)

**Comment by kbrosnan** [comment]
Duplicate #10451
