### ISSUE TITLE
[Bug] URL bar blocks the content of footer

### ISSUE THREAD

**Issue by yookoala** [mozilla-mobile/fenix#15337]
## Steps to reproduce
This seemingly normal footer CSS pattern failed. The browser would refuse to show the footer (position absolute set to bottom of the page).
* https://yookoala.github.io/footer-demo/

### Expected behavior
The footer should be shown at the bottom of the page.

### Actual behavior
The footer is not shown.

### Device information

* Android device: Sony Xperia 5
* Fenix version: 81.1.1 (Build #2015764547)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1666990
