### ISSUE TITLE
[Telemetry] Tabs settings

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15347]
## Description & Product Manager / Data Scientist User Story
As a product manager, I'd like to understand how our users choose to customize their tabs setting, so I can prioritize the most useful features accordingly. 

## What questions will you answer with this data?
- How often users enter the new TAB settings?
- What setting (state) do user have at a point in time, for sorting, tab view, and close tab?

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

![image](https://user-images.githubusercontent.com/42752644/93235902-2e06e380-f74c-11ea-828d-bd23960df87d.png)

<img width="218" alt="Screen Shot 2020-09-23 at 10 16 26 AM" src="https://user-images.githubusercontent.com/1190888/94024844-dd177080-fd85-11ea-990c-62917422e24b.png">

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201015`** build using a Google Pixel 3a (Android 11)

### Events
✔️ **Tab settings were opened** - Ping cb8d15db-c423-42a5-bc18-01876489341b
```
{
          "category": "tabs",
          "name": "setting_opened",
          "timestamp": 16175
        }
```

### Metrics
✔️ Tab view setting set to **Grid** - Ping 1002b205-f7b7-4a2a-931f-237612d765a4
` "metrics.tab_view_setting": "GRID"`

✔️ Tab view setting set to **List** - Ping 2878a311-a69c-4206-a792-48ac4dbea835
`"metrics.tab_view_setting": "LIST"`

✔️ Tab closing setting set to **Manual**- Ping  2878a311-a69c-4206-a792-48ac4dbea835
`"metrics.close_tab_setting": "MANUAL"`
          
✔️ Tab closing setting set to **One Day** - Ping 1002b205-f7b7-4a2a-931f-237612d765a4
`"metrics.close_tab_setting": "ONE_DAY"`

✔️ Tab closing setting set to **One Week** - Ping 9e6bb676-751f-4e55-8815-781d0bd856f8
`"metrics.close_tab_setting": "ONE_WEEK"`

✔️ Tab closing setting set to **One Month** - Ping 501cc2db-ded9-4e43-b7b6-52a2bc086b4b
`"metrics.close_tab_setting": "ONE_MONTH"`

[Logcat](https://github.com/mozilla-mobile/fenix/files/5383806/tbz.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t151000)
