### ISSUE TITLE
Bookmark links show up when you hit the address bar 

### ISSUE THREAD

**Issue by Jinzo2678** [mozilla-mobile/fenix#15343]
### What is the user problem or growth opportunity you want to see solved?
Before the massive update, when you hit the address bar, it'll show your bookmark links automatically which is easy if those are the only links you want to go to. I didn't like seeing that feature go, along with reusing the tab that I'm in. 
### How do you know that this problem exists today? Why is this important?
This used to be standard before the complete overhaul of Firefox mobile, and it makes navigation easier if you only use your bookmark links and you don't have to open bookmark menu. 
### Who will benefit from it?
Everyone who just wants to use their bookmarks.

**Comment by Diapolo** [comment]
That's one of the massive UI glitches, which makes me dislike the current version.

**Comment by Northshorecowboy** [comment]
Having the bookmarks in the address bar was logical for the mobile browser. ONE CLICK! You could select a bookmark or type a search instantly. The new structure requires TWO OR MORE CLICKS to accomplish the same task. AND, the Bookmarks menu item is not consistently in the same location, which is frustrating. Add in years of programmed user response actions that now are eliminated and you have millions of unhappy users. Return the address bar bookmarks access, or at least make it a controllable option in settings.

**Comment by Poopooracoocoo** [comment]
#10050

**Comment by ekager** [comment]
Closing for #10050
