### ISSUE TITLE
[Bug] add-on settings are inaccesible until a web page is opened

### ISSUE THREAD

**Issue by lvmm** [mozilla-mobile/fenix#15340]
## Steps to reproduce
prerequisites: some add-ons installed, in my case - ublock origin and dark reader

open any web page in firefox
go to menu (...)-add-ons -- menu has 'add-on manager' item and an item for each of the installed add-ons
close all tabs
go to menu (...)-add-ons

### Expected behavior
menu looks the same - has 'add-on manager' item and an item for each of the installed add-ons

### Actual behavior
Add-on manager opens immediately, individual add-on items are inaccessible, add-ons settings cannot be changed.

### Device information

* Android device: Caterpillar S61, Android 9
* Fenix version:  81.1.1

**Comment by cadeyrn** [comment]
The add-ons manager is accessible without any open tabs. Therefore the add-on **settings** are also accesssible because you reach them via the add-ons manager.

**Comment by lvmm** [comment]
True for uBlock but not true for Dark Reader: there is no settings link in add-ons manager for it. And even it were, such inconsistent UI is not a good UX.

**Comment by cadeyrn** [comment]
I would argue that it's a bug in the Dark Reader extension if the add-on does not use its settings page as a settings page. You should report it to the Dark Readere developer that they should make the settings accessible via the add-ons manager.

> And even it were, such inconsistent UI is not a good UX.

It does not make sense to open page specific interfaces if you're not on a website. I don't think that Firefox can know what will be opened. For example: Your proposal won't work for add-ons like uBlock Origin. And most if not all add-ons shows something different when pressing the menu item vs. the settings button in the add-ons manager. So it seems to be not that easy.

**Comment by lvmm** [comment]
Ok, if we consider uBlock, there are two types of settings: page-specific (opened directly via the menu) and global (opened via settings in add-on manager or by clicking dashboard icon in page-specific settings). But in desktop Firefox page-specific setting (accessible by clicking the add-on icon in the top-right corner) are available all the time - even when no page is opened, and it works just fine, so I see no reason why it shouldn't work on android.

But settings opened via the add-on manager are not site-specific too, and for uBlock Origin they open just fine which means that my proposal will work perfectly with it.

Anyway, on desktop top-right corner add-on icons are always available, even for

**Comment by lvmm** [comment]
Ok, if we consider uBlock, there are two types of settings: page-specific (opened directly via the menu) and global (opened via settings in add-on manager or by clicking dashboard icon in page-specific settings). But in desktop Firefox page-specific setting (accessible by clicking the add-on icon in the top-right corner) are available all the time - even when no page is opened, and it works just fine, so I see no reason why it shouldn't work on android.

**Comment by lvmm** [comment]
ping
