### ISSUE TITLE
[Bug] Synced tabs suggested in the search bar don't open

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#15349]
## Steps to reproduce
1. Sync tabs from a different device.
2. Type in the search bar a search term or the URL of one of the synced pages.
3. The synced tabs matching the term should appear in search suggestions. Tap the suggested synced tab.
### Expected behavior
The page opens in a tab.
### Actual behavior
Tapping it returns nothing.
### Device information

* Android device: Nexus 9 (Android 7.1.1)
* Fenix version: Beta 82.0-beta1

**Comment by jonalmeida** [comment]
@sv-ohorvath could you verify this on nightly before we landed it on beta? Thank you! 🙂

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build 200928** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
• Desktop
