### ISSUE TITLE
[Bug][Tablet] Main menu is not displayed correctly after rotating the device from landscape to portrait

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15344]
## Steps to reproduce
1. Open Fenix and rotate the tablet to landscape mode.
2. Tap on the three-dot menu.
3. Rotate the tablet to portrait mode.

### Expected behavior
The menu is correctly displayed after rotation ( bottom-right).

### Actual behavior
The menu is displayed in the right-center of the page.

### Device information
* Android device: Xiaomi Mi Pad 2 (Android 5.1).
* Fenix version: Nightly 9/23, 82.0.0-beta.1.

### Note
- on phones, this is only reproducible for the Add-ons menu.

![Screenshot_2020-09-23-12-39-12](https://user-images.githubusercontent.com/58466444/93998302-0394d600-fd9d-11ea-89f4-95be900367f2.png)

**Comment by mcarare** [comment]
@sflorean is this still reproducible? I've tried to reproduce it on an emulator tablet but the menu shows up in the correct place. Thank you!

**Comment by sflorean** [comment]
This is still reproducible, not exactly the same step but when rotating from portrait to landscape. 
Device: Huawei MediaPad M2 (Android 5.1.1). 
![Screenshot_2020-11-23-17-08-19](https://user-images.githubusercontent.com/58466444/99991491-c01b1000-2dbd-11eb-8839-c8211c676de7.png)

**Comment by Mugurell** [comment]
Should be fixed after the change in AC.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 12/14.

**Comment by softvision-miralobontiu** [comment]
@codrut-topliceanu asked if we could test again if the issue was specific to Huawei, and Xiaomi tables.
We tested on 11/23 build from @5:58 PM, with Samsung Galaxy Tab A6 (Android 5.1.1), and the original issue is reproducing also.
