### ISSUE TITLE
FNX3-15628 ⁃ [Bug] regression: The "scan" button no longer does anything

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1534]
### Steps to reproduce
1. enable the address bar
1. press the "scan" button

### Expected behavior
Either enable the QR scanner (which is not yet implemented AFAIK) or show the "not implemented" snackbar. There was already a snackbar but the snackbar no longer appears.

### Actual behavior
The color of the "Scan" button changes, but nothing else happens.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision f36da2d8f22e769294b42fbd0f2081e835071225

**Comment by kbrosnan** [comment]
The snackbar seems to be hidden under the keyboard. If you press the back button after pressing the scan button I see the expected snackbar.

**Comment by kbrosnan** [comment]
Might be fixed by https://github.com/mozilla-mobile/fenix/pull/1546

**Comment by boek** [comment]
Snackbar was being added as a child to the keyboard container :joy: That was a fun one
