### ISSUE TITLE
Single set of bookmarks on desktop and mobile

### ISSUE THREAD

**Issue by JeePeeNL** [mozilla-mobile/fenix#15355]
### What is the user problem or growth opportunity you want to see solved?
I sync my bookmarks between desktop and mobile but they are saved in separate lists.
- If I go to my bookmarks on mobile, I see the bookmarks created on mobile, and the desktop bookmarks are located in a separate folder 'Desktop bookmarks » Other bookmarks'
- On desktop, I all bookmarks are by default created in the folder 'Other bookmarks', and the mobile bookmarks are kept separately in a special folder 'Mobile bookmarks'

### How do you know that this problem exists today? Why is this important?
I just checked

### Who will benefit from it?
I think everybody. It doesn't make much sense to me that Desktop and Mobile bookmarks are kept in separate folder. They are all bookmarks and if  you sync them between devices, you expect to find all bookmarks in the same location.

**Comment by anotherus3r** [comment]
Possibly related: #9454 and maybe #9390

**Comment by JeePeeNL** [comment]
> 
> 
> Possibly related: #9454 and maybe #9390

It's not the same thing, but it would be an acceptable workaround.

**Comment by kbrosnan** [comment]
This is not a feature that the Fenix team controls. The Sync team is the primary owner of this request.

**Comment by JeePeeNL** [comment]
@kbrosnan If not here, where else should this request be posted?

**Comment by JeePeeNL** [comment]
> 
> 
> This is not a feature that the Fenix team controls. The Sync team is the primary owner of this request.

@kbrosnan, where / on which github can the sync team be reached?

Thanks
JP

**Comment by JeePeeNL** [comment]
Thanks for not answering and not listening to your users.
