### ISSUE TITLE
Only 20 collections can be displayed

### ISSUE THREAD

**Issue by TaunusJoe** [mozilla-mobile/fenix#15351]
https://github.com/mozilla-mobile/fenix/blob/943455658bf90df9c7139512790e065fc7292e0d/app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt#L78

The current maximum number of collections that can be created is 20. That on its own, to my opinion, is a too low number. 50 would be better. Worse and unacceptable is the fact that the program decides itself to delete one of the existing 20 collections when you create the 21st. The deletion occurs without warning and without indicating which collection was deleted.

Whatever the max no of collections is, if collection max+1 is to be created, it should be refused with an error message, and the user should make room by deleting a collection of his choice.

**Comment by ekager** [comment]
To be clear, the collection is not deleted. We just only are displaying 20 (which I know is not very helpful when there's no other way to see collections).

**Comment by clientenq** [comment]
Imho this issue raises two bugs.

From a user perspective there is no logic in limiting collections unless resources are limited. As a user I do not want to be limited in my choises to add collections unless necessary.

There is also no logic in not displaying all collections after a number of collection is created.

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/pull/8490 about removing the 20 limit

**Comment by ekager** [comment]
This should be fixed in Nightly

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200929 05:08 (Build #2015766697) GV 83.0a1 from 9/29 with Motorola Moto G6 (Android 8).
The 20 collections limit it is removed.
I will close this issue and remove the qa:needed label.

![rsz_screenshot_20200929-131900](https://user-images.githubusercontent.com/48799384/94546603-ca55dd80-0256-11eb-92b4-216e9b22bc6d.png)
