### ISSUE TITLE
[UX] add contrast to search dialog

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#15359]
_UX feedback needed_ Add depth/contrast to the search dialog so that you can see the difference between the dialog and the background.

Needed in:
* Normal browsing mode
* Private browsing mode
* Light mode
* Dark mode

**Comment by eliserichards** [comment]
Current designs: 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/94061489-13b3b200-fdab-11ea-8034-c53d33b61acf.png"> <img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/94061512-1b735680-fdab-11ea-9d0b-4b822eeec1d2.png"> <img width="327" alt="image" src="https://user-images.githubusercontent.com/43795363/94061559-2b8b3600-fdab-11ea-943b-8000536ede36.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/43795363/94061631-3fcf3300-fdab-11ea-95df-2467c555477d.png"> <img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/94061697-583f4d80-fdab-11ea-88cb-62fa00a371f6.png"> <img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/94061657-4b225e80-fdab-11ea-8a38-7044c12d01bf.png">

**Comment by eliserichards** [comment]
Confirmed with @violasong that we want a dividing line here.

**Comment by liuche** [comment]
Will fold into #16351
