### ISSUE TITLE
[Bug] Inconsistent padding around "Scan" and "Search engine"

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#15356]
The padding around the Scan and Search engine items in the search dialog are different when you change from top toolbar to bottom toolbar.

### Steps to reproduce
1. Set toolbar to **bottom**
2. Click on toolbar to open the search dialog

<img width="323" src="https://user-images.githubusercontent.com/43795363/94059346-e44f7600-fda7-11ea-9b71-ced5938401c5.png">

or 

1. Set toolbar to **top**
2. Click on toolbar to open the search dialog

<img width="323" src="https://user-images.githubusercontent.com/43795363/94059361-e9acc080-fda7-11ea-9875-3e81039dfca4.png">

## Questions
* what should the correct padding/margins be? @mozilla-mobile/ux

**Comment by brampitoyo** [comment]
@eliserichards According to our search pages design found here (https://share.goabstract.com/bf1a7af4-684c-48d0-b7d4-2d8f2ae0f392?mode=design&sha=f8a9a62677b28048e91f041647e71f657a35fce5), the top and bottom padding/margin values seem to be 4dp.

What’s the current value we use? I’m curious whether we already use 4dp.
