### ISSUE TITLE
[Telemetry] Picture in Picture

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15368]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to understand how often users discover and enable the picture in picture feature. 

## What questions will you answer with this data?
- How often (and what % of users) watch a video in full screen?
- How often (and what % of users) enable the picture in picture mode by minimizing a tap playing full screen video?

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201216`** using a Google Pixel 3a (Android 11)

Ping `c181bff3-1713-43ef-ba91-302a16a7608d`

**► ✔️ Full screen event** 
 ```
{
          "category": "media_state",
          "name": "fullscreen",
          "timestamp": 19186
        }

```

**► ✔️ Enable the picture in picture mode**

```
{
          "category": "media_state",
          "name": "picture_in_picture",
          "timestamp": 21987
        }
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/5702010/fullpip.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t161204)
