### ISSUE TITLE
[Telemetry] Sync Tabs

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15369]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to understand how often our users access their synced tabs in the browser, so I can prioritize related features accordingly. 

## What questions will you answer with this data?
- How often (and what % of users) tap on a synced tab to open it in browser?

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by Mugurell** [comment]
Talked offline with Kate who then confirmed with DS and Boek:
- The newly added metrics should log events, not counters anymore
- An an expiration date 6 months is preferred.
Maybe if there is already related telemetry for that part of the screen / feature we can reuse the existing expiration date so that all related telemetry probes will be renewed at the same time.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **Nightly 201216** using a Google Pixel 3a (Android 11) and it seems that **the corresponding event type ping isn't generated.**

@mcarare please review

**Comment by mcarare** [comment]
> Hi, I've just checked this matter on the latest **Nightly 201216** using a Google Pixel 3a (Android 11) and it seems that **the corresponding event type ping isn't generated.**
> 
> @mcarare please review

Should be good to go, after the latest changes.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using a Google Pixel 3a (Android 11)

✔️  Open a synced tab from the page view ⋮ Main menu - Ping **`25091ba1-9635-44b5-8166-71cb624050c7`**
✔️  Open a synced tab from the home screen ⋮ Main menu - Ping **`68e0f9f3-f0e2-47e4-a7dd-a42cdc68b6d4`**

```
{
          "category": "events",
          "name": "synced_tab_opened",
          "timestamp": 6905
        }
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/5715917/synt.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t18123)
