### ISSUE TITLE
[Telemetry] Recently closed tabs

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15366]
## Description & Product Manager / Data Scientist User Story
As a product manager, I'd like to understand how often users access their recently closed tabs, so I can better prioritize related features. 

## What questions will you answer with this data?
- How often users access their "recently closed tabs" through the tabs tray menu
- How often users restore a recently closed tab? 
- How often do users access their History when they are on the "recently closed tabs" page? 

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by Mugurell** [comment]
Talked offline with Kate who then confirmed with DS and Boek:
- The newly added metrics should log events, not counters anymore
- An an expiration date 6 months is preferred.
Maybe if there is already related telemetry for that part of the screen / feature we can reuse the existing expiration date so that all related telemetry probes will be renewed at the same time.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly 201216** using a Google Pixel 3a (Android 11)

**✔️ Access "recently closed tabs" through the tabs tray menu**
Ping **`9b51d3ed-2368-45a2-a7fc-deced5e3b6c6`**

```
{
          "category": "tabs_tray",
          "name": "menu_opened",
          "timestamp": 4640
        },
        {
          "category": "events",
          "name": "recently_closed_tabs_opened",
          "timestamp": 5926
        }
```

**✔️ Access "recently closed tabs" through the history fragment**
Ping **`43191b53-a3b3-4d57-9934-d7136d48169d`**

```
{
          "category": "events",
          "extra": {
            "item": "history"
          },
          "name": "browser_menu_action",
          "timestamp": 11207
        },
        {
          "category": "history",
          "name": "opened",
          "timestamp": 11313
        },
        {
          "category": "events",
          "name": "recently_closed_tabs_opened",
          "timestamp": 12460
        }
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/5702363/recent.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t161206)
