### ISSUE TITLE
FNX-5086 ⁃ [Bug] Videos on allrecipes.com won't play

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1536]
## Steps to reproduce
* Visit allrecipes.com and search for Baked Dijon Salmon
* Start playing the video

### Expected behavior
* The video will start playing

### Actual behavior
* "An unanticipated problem was encountered, check back soon and try again. Error code: MEDIA_ERR_UKNOWN
* The same video plays fine using Chrome

### Device information
* Android device: Pixel
* Fenix version: 1.0.1915 (Build #10981206)
![Screenshot](https://user-images.githubusercontent.com/2171777/55912076-eface280-5baf-11e9-8ff7-7e8fb619b67d.png)UNITO-UNDERSCORE!20190410-162359!

**Comment by mauryat** [comment]
Doesn't repro on Samsung Galaxy S8

**Comment by kbrosnan** [comment]
Works for me as well Pixel 3 and Fenix April 16th build.
