### ISSUE TITLE
[Telemetry] View Downloads

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15367]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to understand how often users view their downloaded files in order to prioritize future download features. 

## What questions will you answer with this data?
- How often users (and what % of users) open their downloads folder?
- How often users (and what % of users) tap on a downloaded file in the browser to open it? 
- How often users (and what % of users) delete a downloaded file?

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by Mugurell** [comment]
Talked offline with Kate who then confirmed with DS and Boek:
- The newly added metrics should log events, not counters anymore
- An an expiration date 6 months is preferred.
Maybe if there is already related telemetry for that part of the screen / feature we can reuse the existing expiration date so that all related telemetry probes will be renewed at the same time.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly 201216`** using a Google Pixel 3a (Android 11) and it seems that **the corresponding event type pings aren't generated.**

@Mugurell please review

**Comment by Mugurell** [comment]
Thank you @AndiAJ.
The changes should now be available to test in the current Nightly.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 12/18 using a Google Pixel (Android 10):
* Download screen opened - ping **7bcbd887-0f8e-4b70-af5c-2b6101ce305e**
```
{
          "category": "downloads_management",
          "name": "downloads_screen_opened",
          "timestamp": 3383
        }
```
* Downloaded item opened from - ping **27c2f6eb-ccfa-4e58-bb04-c5e2a2a472b8**
```
{
          "category": "downloads_management",
          "name": "item_opened",
          "timestamp": 4367
        }
```
* Downloaded item deletion - ping **b9d07d5a-54e5-4875-bfff-26abab1ced0e**
```
{
          "category": "downloads_management",
          "name": "item_deleted",
          "timestamp": 12492
        }
```

 
[Logcat - download item deleted](https://github.com/mozilla-mobile/fenix/files/5716474/15367.-.download.item.deleted.txt)
[Logcat - download item opened](https://github.com/mozilla-mobile/fenix/files/5716475/15367.-.download.item.opened.txt)
[Logcat - downloads screen opened](https://github.com/mozilla-mobile/fenix/files/5716477/15367.-.downloads.screen.opened.txt)
[Glean dashboard 1](https://debug-ping-preview.firebaseapp.com/pings/mira-test-181220001)
[Glean dashboard 2](https://debug-ping-preview.firebaseapp.com/pings/mira-test-181220002)
