### ISSUE TITLE
Investigate if we want to keep swipe to delete bookmarks

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#15362]
### What is the user problem or growth opportunity you want to see solved?
Swipe to delete bookmarks is nightly only at this time. We should investigate what we want to do here. Should we build some UI around having a way to restore deleted bookmarks or should we remove the feature?

### How do you know that this problem exists today? Why is this important?
Need to make a decision about a feature that is in limbo

@mozilla-mobile/ux to help inform a decision here.

**Comment by grigoryk** [comment]
We do have an `Undo` functionality right now (via the snackbar action), but it's pretty time-limited and disappears after several seconds.

![Screenshot_1600904699](https://user-images.githubusercontent.com/465422/94085170-2c789380-fdbc-11ea-9306-2ac5292344a8.png)

**Comment by kbrosnan** [comment]
Yes that was mentioned in #15007. We decided that Fenix needs a more robust undo option than the snackbar. Bookmarks are a different classification of data than tabs where undoing is less of a problem and we built a recently closed tabs UI in #2486.

**Comment by apbitner** [comment]
@kbrosnan On Desktop, is the only way to undo deletion of bookmark through the 'Recover' option in the bookmark manager?

**Comment by kbrosnan** [comment]
The accessibility of this feature is rather different than the desktop model. Where the user makes an explicit decision to delete a bookmark by right clicking and selecting delete or using the delete key. Looking and scrolling down the list of my bookmarks has resulted in accidental deletions for me. It does not take much horizontal movement to trigger this deletion. I was aware of the feature and my first thought was cannot miss that snackbar else I will have no idea what was deleted. For a user that does not know about it they could easily miss the snackbar information.

* Keep the feature and increase the spring rate and swipe length a lot. Make it into an explicit decision. 
* Keep the feature and create an undo or restore from backup method
* Remove the feature

**Comment by Matth7878** [comment]
Swiping to delete a bookmark is really not a good idea... In no way it should be easy to delete one bookmark. You risk to do it without wanting to or even noticing it... (For instance if you screen was on and you weren't looking at it and inadvertently swiped on it)

If really it should exist then It would be better if you had to enter in a delete mode (or edit mode) where you can swipe bookmarks you want to delete. But not would be better in delete mode to select bookmarks when taping on them then pushing a button to delete them, having  a confirmation dialog to actually do it.

**Comment by kleinph** [comment]
I am really in favor of removing the feature completely. Deleting bookmarks is not a task that is done to often. The currently implemented long tap selection and delete feature is enough for bulk deleting.

**Comment by apbitner** [comment]
@kbrosnan Let's remove it, I think the cons outweigh the pros here. Users can always delete via the inline 3-dot menu.

**Comment by kbrosnan** [comment]
If someone wants to pick this up as a `good first issue` they should remove the code added by https://github.com/mozilla-mobile/fenix/commit/cd2532349d8059b2ad23b399bc631e191b714f81#diff-00ed770a60ab00f41043c251896f10124b006ec0bd2a93adb584d99a2e07078a 

Other gestures such as swiping on the address bar and pull to refresh should continue to work.

**Comment by kleinph** [comment]
I would like to try that
