### ISSUE TITLE
disable home screen

### ISSUE THREAD

**Issue by Bscremers** [mozilla-mobile/fenix#15360]
My question is an option we had in the old version of firefox but not anymore.
When i start my firefox app i want it to open the last tab and website i was in last time i used the app.
But now i everytime get a start screen...
And to get to the last page i have to open de tap drawer and select the last website i was working in.
I only whant to see the start screen when i open a new tab to search for somthing ore want to write a web adress.

In the old version there was a option where you could choose to open on a start screen Ore to open in last opened screen.

**Comment by ekager** [comment]
closing as dupe of #12062
