### ISSUE TITLE
[Bug] Youtube media playback works while Firefox is backgrounded

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15374]
## Prerequisites
Make sure the "Video Background Play Fix" extension **isn't installed.**

## Steps to reproduce
1. Navigate to youtube.com
2. Play any video
3. Put  Firefox in background

### Expected behavior
Youtube's playback should stop after Firefox is backgrounded

### Actual behavior
The playback works while Firefox is backgrounded

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• Samsung Galaxy Tab S3 (Android 8)
• OnePlus A3 (Android 6.0.1)

* Fenix version: 
• Nightly 200924
• Firefox Beta 82.0.0-beta.1

### Notes
❗ PiP is also affected

► Video
![20200924-094241](https://user-images.githubusercontent.com/51314259/94110127-cedf5800-fe4a-11ea-8de2-55a3ffd99df8.gif)

**Comment by agi** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1667221
