### ISSUE TITLE
[Bug] Invalid URL shared from page in reader mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#15379]
## Steps to reproduce
1. In Fenix, open a Wikipedia article, turn on Reader mode.
2. Send the tab to your desktop and another mobile device.
3. Open the tab sent.
### Expected behavior
Shares the page URL.
### Actual behavior
The URL is sent in the form of "moz-extension://..." and the desktop browser opens it in a tab but the page can't be loaded.
Fenix doesn't even open it in a tab when you tap the notification.
### Device information

* Android device: Nexus 9 (Android 7.1.1), Pixel 4
* Fenix version: Beta 82.0-beta1, Nightly 9/24

**Comment by 532910** [comment]
can confirm

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201029`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
