### ISSUE TITLE
[Bug] custom tab is always light

### ISSUE THREAD

**Issue by Yajo** [mozilla-mobile/fenix#15371]
## Steps to reproduce
set night mode.
Open a volatile tab from another app.

### Expected behavior

Browser bar should be dark. 

### Actual behavior

It's light: 
![Screenshot_20200923-205143_Firefox](https://user-images.githubusercontent.com/973709/94102210-e827da80-fe31-11ea-8353-0b0a9ffd2f15.jpg)

### Device information

* Android device: SM-J600FN/DS
* Fenix version: 80.1.3 (Build #2015762833)

**Comment by s-ankur** [comment]
Custom tabs are supposed to be colored by the host app, it should not follow browser theme afiak https://developers.google.com/web/android/custom-tabs/implementation-guide

**Comment by s-ankur** [comment]
It is not always light either 
![Screenshot_2020-09-28-01-53-24-987_org mozilla fenix](https://user-images.githubusercontent.com/33252312/94374958-b1054200-012d-11eb-9c83-2829f2425c58.jpg)

**Comment by Yajo** [comment]
Weird. I'm using feedly, and it shows dark tabs when my browser is the Samsung one:

![Screenshot_20200928-154822_Samsung Internet](https://user-images.githubusercontent.com/973709/94447856-2f9bc700-01a2-11eb-9e78-944c3a49219a.jpg)

**Comment by s-ankur** [comment]
can you specify the host app also?

**Comment by ekager** [comment]
this might be fixed in a newer version.  Let's QA this bug in Nightly and close if we can no longer repro

**Comment by Yajo** [comment]
> can you specify the host app also?

Feedly

**Comment by ebalazs-sv** [comment]
I had tested this on the latest Nightly 200929 05:08 (Build #2015766697) GV 83.0a1 from 9/29 with Motorola Moto G6 (Android 8), Nexus 5 (Android 6.0.1), Samsung Galaxy Tab S3 (Android 8) on several pages and the custom tab is always light, even when the app theme is set to "Dark" or "Follow device theme" and the device is set to Night mode.

Please note that the custom tab main menu, the Share and Tracking Protection pop-ups are all in Dark mode, only the custom tab bar remains light.

![20200929_120639](https://user-images.githubusercontent.com/48799384/94538425-b2795c00-024c-11eb-8556-1a018d2dc3b1.gif)

I will remove the qa:needed label for now.

**Comment by s-ankur** [comment]
> Please note that the custom tab main menu, the Share and Tracking Protection pop-ups are all in Dark mode, only the custom tab bar remains light.  

Related : #10813

**Comment by Yajo** [comment]
Firefox 92.1.1 (Build #2015832083)
AC: 92.0.15, e00bef534d
GV: 92.0-20210903235534
AS: 82.1.0

I can confirm this issue still happens when the host app is feedly, but it doesn't happen when it's gmail. Maybe a feedly bug?
