### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mini536** [mozilla-mobile/fenix#15376]
### What is the user problem or growth opportunity you want to see solved?
I hope fenix have 
1.batch remove bookmarks,see picture1:
![Screenshot_2020-09-24-15-28-03-037_com kiwibrowser browser](https://user-images.githubusercontent.com/32984303/94114260-acfdc980-fe7a-11ea-932a-cb2de05921fe.png)

2.search from bookmarks or history 
function,see picture 2 and 3:
![Screenshot_2020-09-24-15-27-30-348_com kiwibrowser browser](https://user-images.githubusercontent.com/32984303/94114301-bc7d1280-fe7a-11ea-8a0b-ab5ec58b0cbd.png)
![Screenshot_2020-09-24-15-26-13-505_com kiwibrowser browser](https://user-images.githubusercontent.com/32984303/94114304-bedf6c80-fe7a-11ea-832d-4a9729044455.png)

### How do you know that this problem exists today? Why is this important?
1.It's too complex to remove many bookmarks to the same folder.
2.Can't find the bookmarks or history easily

### Who will benefit from it?
1.Always editing a large number of bookmarks
2.Search history frequently.

**Comment by kbrosnan** [comment]
This is two separate issues. In the future please open separate issues for separate ideas.

1. Duplicate #1869
2. Duplicate #10046
