### ISSUE TITLE
[Bug] Some strings missing translations in Romanian

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#15385]
## Steps to reproduce
- Settings>Turn on Sync>
  - the "No account? Create one..." string
  - the QR pairing notification for camera permission

- Settings>Search: "Autocomplete urls" & "Search synced tabs"
- In Settings>Private Browsing, the "If allowed, private tabs will also be visible...."
- The Settings>Close tabs menu
- The Tabs tray menu

### Expected behavior
Strings are translated
### Actual behavior
Partial/no translations.
### Device information

* Android device: 
* Fenix version: Beta 82.0-beta1, Nightly 9/24

**Comment by liuche** [comment]
We were waiting for l10n freeze and uplifted the strings to beta Oct 8 in #15731
