### ISSUE TITLE
[Bug] Top sites are more difficult to reach after update to Firefox 80

### ISSUE THREAD

**Issue by antimatter84** [mozilla-mobile/fenix#15387]
## Steps to reproduce
1. Have top sites shown in the start screen
2. Go to a random site
3. Tap the address bar 

OR

1. Open a new tab

### Expected behavior
Show the top sites so I can directly tap one. This was standard behaviour in pre-80 Firefox versions.

### Actual behavior
Top sites not visible when tapping address bar while having a random site open.
Top sites are visible on the new tab scenario but the focussed address bar blocks them and only an additional tap outside the address bar makes them finally tappable.

This breaks UX for me.

Also, pinning top sites no longer works. I cannot see such a function anywhere.

### Device information

* Android device: Google Pixel 3a, Android 11
* Fenix version: 81.1.1

**Comment by liuche** [comment]
If you double-tap the tab icon, you'll be able to get a top sites screen. Pinning sites can be done through the 3-dot menu: Add to top sites.
