### ISSUE TITLE
[Bug] "Collection saved!" snackbar is displayed when adding new tab to a collection

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15388]
## Steps to reproduce
1. Create a new collection (or use an existing one).
2. Open CNN.com.
3. Go to homescreen-collection-menu.
4. Tap on "Add tab" from the menu.
5. Tap on "Save" in order to add the tab to the collection.

### Expected behavior
"Tab saved" snackbar is displayed.

### Actual behavior
"Collection saved!" snackbar is displayed.

### Device information
* Android device: all
* Fenix version: 82.0.0-beta.1, Nightly 9/24.

**Comment by SoftVision-LorandJanos** [comment]
This issue is not reproducible as described. There is no snackbar displayed when Saving a tab in the collection.
Verified on Motorola Nexus 6 (Android 7.1.1)
Firefox for Android version: Latest Release 87.0.0-rc.1 and on the latest Nightly 210330 05:04 (GV89)
