### ISSUE TITLE
[Bug] Missing shortcuts in context menu for sharing with other apps

### ISSUE THREAD

**Issue by antimatter84** [mozilla-mobile/fenix#15389]
## Steps to reproduce
1. Long tap on a link to open the context menu
2. Find the recently used apps near the top to share this link with missing

### Expected behavior
Upon opening the context menu, I expect the 2 or 3 recently used apps for sharing a link or other media object. Example: I frequently share links on Youtube with an app called "Yatse" (remote control for Kodi Media Center) to make the video play on my TV or with a messenger app. Those app icons would then always appear as recently used apps for sharing links in top of the context menu.

### Actual behavior
The shortcuts for those apps are gone. I always have to tap "Share link" in the context menu and select an app from the next view. Now I always need a separate tap to achive this. 

### Device information

* Android device: Google Pixel 3a, Android 11
* Fenix version: 81.1.1

**Comment by liuche** [comment]
Going to collect these into #14926
