### ISSUE TITLE
[Bug] tap and drag to select text is crazy 

### ISSUE THREAD

**Issue by Yajo** [mozilla-mobile/fenix#15391]
## Steps to reproduce

As explained in https://github.com/mozilla-mobile/fenix/issues/10618#issuecomment-697107024:

1. Tap and hold any text.
2. Drag to another part of the paragraph to select text.

### Expected behavior

Select text range, just like any other app.

### Actual behavior

Firefox selects just one word, and then you need to use the handles to select the rest.. and it works weird because the nav bar moves.

### Device information

* Android device: SM-T720
* Fenix version: 81.1.1 (Build #2015764547)

**Comment by Yajo** [comment]
See it in action. Left side is Samsung browser 12.1.2.5. Right side is Firefox 81.1.1 (Build #2015764547).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/973709/94166855-1e924380-fe8c-11ea-9d2f-d7401259cddf.gif)

**Comment by kbrosnan** [comment]
Can you check with [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)? There are some touch scrolling fixes that might improve this situation. I did a quick check on Pixel 2XL running Nightly and did not see the address bar move with the text selection handles for me on https://paste.mozilla.org

**Comment by Yajo** [comment]
I just tested. It's much better as it doesn't seem so crazy, but it is still away from normal Android experience.


> Firefox selects just one word, and then you need to use the handles to select the rest.. 

This still happens.

> and it works weird because the nav bar moves.

This is fixed.

**Comment by liuche** [comment]
Selecting one word is standard Android behavior - it's also what chrome, gmail, and other android apps do. Will close since the navbar dragging is fixed, and the others are Android behavior.

**Comment by Yajo** [comment]
Nope. On any other Android app, this is what you do with your finger to select a text range:

1. Tap on the word
1. Hold
1. Drag
1. Release

Firefox needs:

1. Tap
1. Hold 
1. Release 
1. Tap on the handle
1. Hold
1. Drag
1. Release

It's obviously not standard. Just check the Samsung browser part of https://github.com/mozilla-mobile/fenix/issues/15391#issuecomment-698421694.

**Comment by PlayXman** [comment]
Chrome on Android 8:
![a67a41d8-49bb-4e7e-b4b9-6a60db3ede8a](https://user-images.githubusercontent.com/35222741/96079170-d355d880-0eff-11eb-9cef-8bebc42a236e.gif)

Apps usually allow you to select more than 1 word.

**Comment by liuche** [comment]
Sorry about that! Let me move this to our GeckoView team to see what we can do there.

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1671530

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
