### ISSUE TITLE
FNX-5087 ⁃ Add Multi-select Features for Bookmarks

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1539]
Add the missing bookmarks features for selecting multiple bookmarks or folders to delete or to open as per the UX design in #242.

**Comment by sv-ohorvath** [comment]
@colintheshots

**Comment by sv-ohorvath** [comment]
Removing the QA-needed label until the blocking issues are fixed.

**Comment by sv-ohorvath** [comment]
This is still blocked by 2 P1 issues. I've removed the label until they are fixed.

**Comment by AndiAJ** [comment]
Hi, there are still some issues regarding this topic on the latest Fenix Build #11830608 from 2/7 using the following devices:
• OnePlus 6T (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)

✔Selection of multiple bookmarks + performing different actions (Open in new tab, Open in private tab, Delete) went well 

❌Selection of multiple bookmarks folders is not possible, 
**The only way is to first select a normal bookmark and afterwards the selection of the folders will be possible**
![20190702_100700](https://user-images.githubusercontent.com/51314259/60494671-e798a680-9cb7-11e9-82b8-991a5b85cd4a.gif)

❌Using the above mentioned workaround the only working action is to delete multiple folders
, the bookmarks located in folders can't be opened in new tabs nor in new private tabs. 
![20190702_105938](https://user-images.githubusercontent.com/51314259/60495111-d00ded80-9cb8-11e9-813f-7702c382e9d3.gif)

Based on this, I'll remove the QA needed label.

**Comment by AndiAJ** [comment]
Hi, as per the above mentioned [comment](https://github.com/mozilla-mobile/fenix/issues/1539#issuecomment-507567918) the exclusive selection of multiple folders is still not working on the latest Nightly build #11900609 from 9/7 using the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S9 (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)

**Comment by colintheshots** [comment]
Hmm, I don't remember being given any UX for opening either one or multiple folders. Hence, the multi-selection of folders is deliberately not possible except for deletion. It looks like the solution that's there now isn't ideal though.

Either I should alter the menu items to remove options when multiple folders are selected or I should remove the option to select multiple folders altogether. Open All in one folder or multiple folders could recurse and open a lot of links, surprising the user.

I guess UX review is called for. Should I support recursion, just open one level, or not support open all in one or multiple folder(s)?

**Comment by topotropic** [comment]
Let's remove the option to "open in new tab", "open in private tab" and just have "delete" when a folder is selected (no matter in what combination, if people select two bookmarks and a folder, they just get the "delete" option)

**Comment by colintheshots** [comment]
I discovered a secondary issue at the same time due to the backdoor way to select folders. The code currently lets you delete the root folder and then crashes. So my fix includes a message and refuses to let the user select any root folder during multi-select. The fix will miss v1.1 due to the newly-added string.

**Comment by liuche** [comment]
@mheubusch and @colintheshots to figure out if we need a new string for error message.

**Comment by mheubusch** [comment]
@colintheshots I am not sure i am following the flow that you outline in the secondary issue. what are the steps a user takes and when do you propose presenting the snackbar message? What - roughly - is the message telling them and are there any allowed actions on the snackbar? Like UNDO, for example?

**Comment by colintheshots** [comment]
If the user is multi-selecting bookmarks and bookmark folders, attempting to select a root folder will produce a short snackbar message. Currently, it's "Cannot edit root folders". Of course, a user might not know what a "root folder" is.

We need to prevent users selecting the root folders because if they manage to select one along with other, valid items to delete, then there is no good user experience possible. Deleting all of the items will either: cause a crash, produce an error snackbar, leave the root folders not deleted, or visibly delete them only to have them re-appear later.

**Comment by colintheshots** [comment]
I added the UX feedback because this PR is currently blocked solely based on what the error string should be. What UX do we want if a user attempts to multi-select a root folder that they cannot modify?

**Comment by lime124** [comment]
thanks colin! @mheubusch it's on you! :)

**Comment by mheubusch** [comment]
Can’t delete default folders

**Comment by colintheshots** [comment]
@mheubusch It's not merely deletion. Any modification of these folders is prohibited so the user cannot even select them. How's "Cannot edit default folders"?

**Comment by mheubusch** [comment]
thanks @colintheshots - Can't edit default folders

(use the less formal Can't, but otherwise lgtm)

**Comment by softvision-miralobontiu** [comment]
Verified with a locally build from 8/5 master with LG G7 Fit (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1) that the default bookmark folders cannot be deleted or edited and the "Can't edit default folders" message is displayed:

![Screenshot_20190805-150503](https://user-images.githubusercontent.com/40694158/62463433-aa31a800-b792-11e9-8435-d1fdf03d6bb9.png)
