### ISSUE TITLE
[Bug] Toolbar Long Click actions not working

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15409]
## Steps to reproduce
Try to use a toolbar long click action while browsing or on home
(ie long press URL to copy it, long press tab counter to close the current tab or open a new tab)

### Expected behavior
See action menus after long click

### Actual behavior
Nothing happens. 

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Wondering if these broke when we added new swipe gestures/GestureDetector

**Comment by boek** [comment]
@ekager So interestingly this is also not working on my pixel 3. But the device isn't registering long clicks anywhere. Tried on the Android home screen and in Focus as well.. Plugged in my pixel 2 and they were all working :/

**Comment by boek** [comment]
`settings > accessibility > touch and hold delay` got unset on my pixel 3.. on my pixel 2 its set to short where everything works as expected. When I reset it to short on my pixel 3 everything started to work again. Very strange.. I wonder if we got an Android update? 🤔

**Comment by ekager** [comment]
Yep switching that back to short fixed it for me 🥴 Closing

**Comment by cadeyrn** [comment]
>  got unset on my pixel 3.. on my pixel 2 its set to short where everything works as expected. When I reset it to short on my pixel 3 everything started to work again. Very strange.. I wonder if we got an Android update?

FWIW the same happens on my OnePlus device a few weeks ago. No idea why.
