### ISSUE TITLE
What was the new message over the tab list?

### ISSUE THREAD

**Issue by saschanaz** [mozilla-mobile/fenix#15405]
I just manually updated Nightly, tapped the tab button, found there is some message over the list, but I immediately opened an existing tab and thus missed the message. What was that?

I tapped the tab button again but it doesn't reappear.

**Comment by s-ankur** [comment]
I think it was the close tabs after x duration suggestion

**Comment by ekager** [comment]
If you didn't dismiss it directly, you will see it again, but our new CFR limit is one shown every 3 days. 
It is a hint about the new tab settings #14243
