### ISSUE TITLE
[Bug] Search suggestions remain on screen after results are loaded

### ISSUE THREAD

**Issue by ngmoviedo** [mozilla-mobile/fenix#15401]
## Steps to reproduce
Write a search query after tapping the bottom search bar, and touch the search or forward key on the keyboard, ignoring the search suggestions.

### Expected behaviour
Search suggestions disappear and the search result page is loaded.

### Actual behaviour
Most of the time search suggestion stay on top covering part of the loaded page, although only visually. Interactions with that part of the screen are sent as clicks in the page or scrolling. Minimizing and maximizing Firefox solves the issue. Rarely it behaves as expected, although I haven't been able to find any pattern.

This issue wasn't present in previous versions. Also, it doesn't seem to occur when a suggestion is picked.

### Device information

* Android device: Xiamo Redmi Note 4 (mido)
* Android version: 10 (Lineage OS-based ROM)
* Fenix version: 81.1.1 (Build #2015764547)

![Screenshot_20200924-193108](https://user-images.githubusercontent.com/61010998/94179411-bdbf3700-fe9c-11ea-906b-a49b92b6b31f.jpg)

**Comment by deojames** [comment]
Faced the same issue. Its happening when using system navigation gestures but if you switch to 3-button gestures problem goes away.
[Search suggestion overlay bug video](https://streamable.com/04q42k)

**Comment by ngmoviedo** [comment]
Can confirm that. I had not tried to disable navigation gestures before, but it also solves the problem for me. I am also using Crdroid.

**Comment by Likivik** [comment]
Confirming on non-standard ROM with gestures navigation enabled. Gets fixed by switching to 3 or 2 button navigation or non-fullscreen gestures (with a slim bar at the bottom of the screen).
