### ISSUE TITLE
[Bug] While on Browser, if close all private tabs, can't undo 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15407]
## Steps to reproduce
1. Open a new tab in private mode
2. Open tabs tray and select "close all tabs" from menu
3. Click undo on snackbar

### Expected behavior
Private tabs are restored

### Actual behavior
Nothing 

It looks like when we close all the tabs, the `BrowserFragment` quickly is also changing the mode based on the new default selected session. That will recreate the activity, and then the snackbar we see actually does nothing because the tabs have already been removed.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 200925 (Build #2015765939).

### Device used:
- OnePlus 6T (Android 9)
- Huawei MediaPad M3 (Android 7.0)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200928`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

Filled #15490 for an inconsistency I've encountered.
