### ISSUE TITLE
FNX-5089 ⁃ No snackbar when bookmark is created

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1540]
## Steps to reproduce
1. Open a page
1. Swipe up to see quick action sheet
1. Tap bookmark

### Expected behavior
I see a snackbar saying that the bookmark was created, and letting me edit it. 

### Actual behavior
Bookmark is created with no snackbar. 

This worked in build 1.0.1915 build id 10991207

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1915 build id 11001743

**Comment by kbrosnan** [comment]
Might be fixed by https://github.com/mozilla-mobile/fenix/pull/1546

**Comment by sv-ohorvath** [comment]
I can confirm this is fixed on the 4/11 build.
