### ISSUE TITLE
Crash in [@ IPCError-browser | RecvNewWindowGlobal Cannot create for missing BrowsingContext]

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15400]
Crash report: https://crash-stats.mozilla.org/report/index/5b2aa2aa-fb4b-4c69-8590-293cc0200820

Top 5 frames of crashing thread:
```
0 libxul.so bool js::ValueToId< js/src/vm/JSAtom-inl.h
1 libxul.so js::jit::SetPropIRGenerator::tryAttachAddSlotStub js/src/jit/CacheIR.cpp:4558
2 libxul.so js::jit::DoSetPropFallback js/src/jit/BaselineIC.cpp:2926
3  @0x7b325ab768 
4  @0x7b325ab768 
```

Reported on: https://www.reddit.com/r/technology/comments/iy847u/firefox_usage_is_down_85_despite_mozillas_top/g6bc4uo/

>This is the most recent one showing. What generally seems to happen lately is that Firefox locks the system UI, and the whole OS crashes. I'm guessing it's unable to write a crash dump in that case

**Comment by liuche** [comment]
This looks like the exact signature for https://bugzilla.mozilla.org/show_bug.cgi?id=1650257, and should be going to release next week!
