### ISSUE TITLE
[Bug]Improperly displayed and unusable "Cast to" button on Rockfm.ro

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15414]
## Steps to reproduce
1. Navigate to rockfm.ro
2. Check the lower right "Cast to" button
3. Tap the button

### Expected behavior
Properly displayed button (Cat to device icon should be displayed)
Tapping the button should start searching for devices to cast the media to

### Actual behavior
Improperly displayed button (Cat to device icon **isn't** displayed)
Tapping the button doesn't do anything

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly 200924

### Notes
✔️ Works on Chrome

► Screenshots (Comparison Fenix VS Chrome)
![rsz_rsz_screenshot_20201005-09567676636](https://user-images.githubusercontent.com/51314259/94236876-960cb500-ff16-11ea-9ebc-6f7bacc163aa.png)

**Comment by delia-pop** [comment]
This was reproducible on the latest Nightly 101 from 04/29, latest RC 100.1.1 and Beta builds. On Samsung Galaxy Tab S3 (Android 9) the button does not work properly on Chrome either. 

https://user-images.githubusercontent.com/89388888/165949306-6e510dd1-c833-4eba-bd83-93e3a5fd3d02.mp4

Note that the website uses the https://developers.google.com/cast/docs/web_sender/integrate library which might not be supported by GVE. I will move this ticket to Bugzilla for GV's team visibility.

**Comment by delia-pop** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1767031

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
