### ISSUE TITLE
[Bug] Web Audio API is not working in background

### ISSUE THREAD

**Issue by vitalydolgov** [mozilla-mobile/fenix#15417]
## Steps to reproduce

1. open mynoise.net and select any sound generator
2. try to switch tab or switch application

### Expected behavior

Background audio still plays.

### Actual behavior

Background audio stops.

### Device information

* Android device: Xiaomi M1A1, Android 9
* Fenix version: 81.1.1

### Additional information

The site uses Web Audio API.

**Comment by liuche** [comment]
Recently made some improvements to the media session apis - I can't repro this on Nightly, are you still seeing this problem?

**Comment by vitalydolgov** [comment]
Yeah, I cannot reproduce either, but there is subtle stuttering during playback, at least on my device, especially while opening panel with tabs and during background playback as well. You can check with [this](https://mynoise.net/NoiseMachines/whiteNoiseGenerator.php) noise generator.

**Comment by rocketsroger** [comment]
Reproducible with the new `MediaSession` API on Nightly.  Confirmed that no media was activated.  Created an issue to track this with the GV team.  https://bugzilla.mozilla.org/show_bug.cgi?id=1682579
