### ISSUE TITLE
[Bug] Invalid URL stored in bookmarks for reader mode

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15413]
## Steps to reproduce
Open reader mode for a page
Add it to bookmark

### Expected behavior
The proper page link should be saved. Bookmarks can be synced so it is a very unwelcome surprise that the bookmark does not work on the synced device and instead show some gibberish url
### Actual behavior
The moz extension link is saved
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/15379 https://github.com/mozilla-mobile/fenix/issues/13036
https://github.com/mozilla-mobile/fenix/issues/11699
https://github.com/mozilla-mobile/fenix/issues/5190

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201029`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
