### ISSUE TITLE
There is no fade-out effect at the end of the address bar.

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#15419]
There is no fade-out effect at the end of the address bar.
The effect in previous versions was available, but it disappeared in the latest Nightly.
![IMG_20200925_202233.jpg](https://user-images.githubusercontent.com/62339707/94266788-2d045c00-ff6d-11ea-8238-d91e195393e1.jpg)

### Device information

* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 200925 06:01

**Comment by lomomcat** [comment]
@Amejia481 @ekager I have waited for a long time, can you help me to solve it?

**Comment by Amejia481** [comment]
> @Amejia481 @ekager I have waited for a long time, can you help me to solve it?
> It may be that the older code that contains this function is invalid or removed during the update process.

Thanks for reporting this @lomomcat :), I'm not that familiar with that part of the source code, I rather prefer that somebody more knowledgeable in that area take the issue as he/she could be more productive at it, than me. 

Something that could be really helpful to identify the source of the issue, it's if you could identify from which version the issue start to happen, that will could be very helpful :).

**Comment by lomomcat** [comment]
> > @Amejia481 @ekager I have waited for a long time, can you help me to solve it?
> > It may be that the older code that contains this function is invalid or removed during the update process.
> 
> Thanks for reporting this @lomomcat :), I'm not that familiar with that part of the source code, I'd would rather prefer that somebody more knowledgeable in that area take the issue as he/she could be more productive at it, than me. 
> 
> Something that could be really helpful to identify the source of the issue, it's if you could identify from which version the issue start to happen, that will could be very helpful :).

It was Nightly 200925 06:01 when I noticed it.
If I have free time, I will use the historical version apks of [apkmirror.com](apkmirror.com) to test which version first encountered this problem.
Thank you for reply. 😘

**Comment by Amejia481** [comment]
Thanks :)

**Comment by Amejia481** [comment]
@lomomcat is the issue fixed? :)

**Comment by lomomcat** [comment]
> @lomomcat is the issue fixed? :)

I was not sure it's a problem, so I had closed it.
I found that Dark Theme in Fenix is normal. But what I described above will appear when I turn on the dark mode of Android 10(MIUI 12).
