### ISSUE TITLE
[Bug] Home Toolbar actions have no ripple animations on click

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15410]
## Steps to reproduce
1. On home, click the tab counter or menu icon on toolbar

### Expected behavior
See ripple that matches ripple while browsing

### Actual behavior
No ripple or indication they were clicked. 

### Device information

* Android device: ?
* Fenix version: ?

**Comment by mcarare** [comment]
3-dot menu doesn't have ripple either.

**Comment by chrishernan** [comment]
Hi. Is this issue still available to work on?
