### ISSUE TITLE
[Bug] Tapping on search widget while in private open tab, opens a new private tab

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#15418]
## Steps to reproduce
1. Add the search widget;
2. Launch Fenix and open a page in private browsing; 
3. Tap the search widget;
4. Observe the opened tab;
### Expected behavior
The tab is opened in normal browsing.
### Actual behavior
The tab is opened in private browsing.

### Notes
This is not reproducible when the private home screen or the tabs tray in private mode is displayed.
![20200925_150339](https://user-images.githubusercontent.com/48799384/94265077-93bf5080-ff40-11ea-96e1-d0e4c1676db9.gif)

### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 200925 06:01 GV 83.0a1 from 9/25

**Comment by delia-pop** [comment]
While testing the widgets functionality we have noticed that the widget opens a Normal Browsing page at all times, regardless if the user had a Private Tab previously open in browser. 

@amedyne , can you please confirm which of the following behaviors is the indented one: 

- current ticket #15418 claims that the widget should open a Normal Browsing page when a Private Tab was previously open in browser;
-  ticket #12545 and feature request #14483 claim that the widget should open a Private Browsing page when a Private Tab was previously open in browser;
