### ISSUE TITLE
[Bug]problem with adb command and latest nighlty 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#15423]
since 5days (older nighlty build have no issues at all) I ve got this annoying problem :
Close Firefox then execute this shell command am start -a android.intent.action.VIEW -d https://tinder.com/app/matches
nothing load.
if I use an older nighlty build from 5or 6 days ago no problem.
how can I solve the issue?

**Comment by ale82to** [comment]
it maybe this bug?
https://bugzilla.mozilla.org/show_bug.cgi?id=1656310

**Comment by liuche** [comment]
Dupe to #15513
