### ISSUE TITLE
[Bug] tons of crashes because of mjava.lang.RuntimeException: at org.mozilla.gecko.process.ServiceAllocator$DefaultContentPolicy.allocate(ServiceAllocator.java)

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#15422]
in today nighlty I ve got tons of crashes because of [Bug] tons of crashes because of mjava.lang.RuntimeException: at org.mozilla.gecko.process.ServiceAllocator$DefaultContentPolicy.allocate(ServiceAllocator.java)
here's the soccorro:
https://crash-stats.mozilla.org/report/index/5db1f720-92ae-45cd-b5b3-261420200925

**Comment by liuche** [comment]
This is due to having invalid about:config settings set. about:config is not fully supported and not all settings apply correctly to Android and is considered an experimental feature.
