### ISSUE TITLE
Can't use self-signed certificates anymore

### ISSUE THREAD

**Issue by mattfeest** [mozilla-mobile/fenix#15429]
## Steps to reproduce
Try to download and install a self-signed certificate (i.e. https://mf327.com/ca.crt)
### Expected behavior
Either Firefox should import the certificate into it's own store or use the OS certificate store so you can use the certificate.
### Actual behavior
The certificate is downloaded and not installed in the Firefox store. I can install it in the Android store, but Firefox does not use it.
### Device information

* Android device: Samsung Galaxy Note 10
* Fenix version: 81.1.1

**Comment by mattfeest** [comment]
soooo....

**Comment by liuche** [comment]
Dupe of #2286

**Comment by vladns** [comment]
It's still not clear if there is a solution to the problem?
