### ISSUE TITLE
[Bug] Tab closed snackbar appears on opening the app from cold start sometimes

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15425]
## Steps to reproduce
Kill the app and after a while restart the browser

### Actual behavior
Sometimes there will be a tab closed snackbar that appears even though I closed no tabs and in fact the close tabs option is set to manual.
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by SoftVision-LorandJanos** [comment]
This issue is not reproducible.
Verified on Motorola Nexus 6 (Android 7.1.1)
Firefox for Android version: Latest Release 87.0.0-rc.1 and on the latest Nightly 210330 05:04 (GV89)

**Comment by s-ankur** [comment]
Have not seen this since long time. May be closed I huess

**Comment by SoftVision-LorandJanos** [comment]
This issue is not reproducible.
Tested with the latest Nightly 99.0a1 (2022-03-02).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.
