### ISSUE TITLE
[Bug] PDF downloads don't follow app defaults 

### ISSUE THREAD

**Issue by IAmRGroot** [mozilla-mobile/fenix#15439]
## Steps to reproduce

Have bunq, Firefox Nightly and Google Drive installed.

Click the pdf download link (f.e. https://manuals.coolblue.nl/06/philips-promix-staafmixer-hr265790.pdf), then open the file.

Or

Open the already downloaded pdf from the downloads menu.

### Expected behavior

Opens default PDF viewer (Google Drive PDF Viewer)

### Actual behavior

Opens bunq

(There are no defaults set on bunq. Opening the PDF through Chrome or the Files app opens it in Drive PDF Viewer)

### Device information

* Android device: 11
* Fenix version: Nightly 200925 06:01 (Build #2015765939)

**Comment by hebu** [comment]
I have Xodo Docs installed to view PDFs. When I try to download & open [this PDF](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Nov_2020/2020-11-30-de.pdf?__blob=publicationFile) it can't be opened ("no app found" pops up). When I try to download & open the PDF from the steps to reproduce I get asked which app to use, but the suggested apps are totally wrong: Archive preview, Screen reader, Keepass and a navigation app.

**Comment by hebu** [comment]
Here's a positive example: [This PDF](https://www.ladr.de/sites/all/themes/cont/files/_02_pdfs/01_medizin/11_fachlabore/ploen/Laborbuch.pdf) open perfectly fine in the default app (Xodo).

**Comment by hebu** [comment]
As a workaround, you can always long-tap a PDF link and open with external app, which seems to work fine.

**Comment by Amejia481** [comment]
> I have Xodo Docs installed to view PDFs. When I try to download & open [this PDF](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Nov_2020/2020-11-30-de.pdf?__blob=publicationFile) it can't be opened ("no app found" pops up). When I try to download & open the PDF from the steps to reproduce I get asked which app to use, but the suggested apps are totally wrong: Archive preview, Screen reader, Keepass and a navigation app.

Thanks for the info, it's likely that for some reason we are not getting the right mime type and as result not finding the right app to open the file. We have to take a look on it.

**Comment by QJKX** [comment]
If I use [Intent Intercept](https://f-droid.org/packages/de.k3b.android.intentintercept/) to look at the intent firefox sends when i try to open download from @IAmRGroot 's url https://manuals.coolblue.nl/06/philips-promix-staafmixer-hr265790.pdf it shows a mime type of 

>application/octet-stream

This matches the header from the http response that contained the file when I downloaded it -
>Content-Type: application/octet-stream


Another example is https://www.mitpressjournals.org/doi/pdfplus/10.1162/comj_e_00494
After redirects `wget -S` says the relevant header is
>Content-Type: application/pdf; charset=UTF-8

This **all** gets in to the intent mime type verbatim - 
>application/pdf; charset=UTF-8

Unfortunately, unlike the bare `application/pdf`, Android does not associate this mime type with pdf viewers.
