### ISSUE TITLE
[Bug] firefox.com/pair message show at every scan after you try to login using scan qr

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15431]
## Steps to reproduce
Open the ready to sign in button on the turn on sync message
A QR scanner opens 
Close it and open a regular qr scanner from the search toolbar

### Expected behavior
In the regular qr scanner there is no message
### Actual behavior
There is a message to sign using firefox.com/pair
### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

**Comment by mcarare** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/8537 in AC.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 201006 (Build #2015768043).
### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)
