### ISSUE TITLE
Long press on any image to save as a file

### ISSUE THREAD

**Issue by blazingkin** [mozilla-mobile/fenix#15442]
### What is the user problem or growth opportunity you want to see solved?

A user finds an image on the web that they want to share, or download for later use. Rather than having to find the file download link, they should be able to download or share that image directly from the page it is displayed on.

### How do you know that this problem exists today? Why is this important?

Because I encountered the usability issue.

I searched for "Slime Rancher" on Duck Duck Go Image search because I wanted to share an image. It took me some time to figure out how to find an actual link that I could send to my friends.

My initial instinct was to long press the image, but that failed. I needed to use Duck Duck Go's link to the image, a bit of a barrier to ease of use

It's important because this is a common workflow that is slightly cumbersome now, and may be hard to accomplish for more unfamiliar users

### Who will benefit from it?

Power users can use this as a shortcut to quickly save an image

Less experienced users can use this, since it makes a feature (saving an image to the local device) more discoverable

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7484)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812802

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
