### ISSUE TITLE
[Bug] The menu and address bar cannot be clicked before the bookmark deletion prompt disappears

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#15449]
## Steps to reproduce

1. Open a  bookmark
2. Click the main menu, and then click the star icon to enter the bookmark editing interface
3. Click the delete icon, and then confirm to delete
4. Delete floating bar appears at the bottom
5. The menu and address bar cannot be clicked before the bookmark deletion prompt disappears

* Android device: ?
* Fenix version: 
https://github.com/mozilla-mobile/fenix/releases/tag/v81.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7502)

**Comment by lindongbin** [comment]
> 
> 
> Hi @lindongbin! Thank you for the report! I could not reproduce this issue on the latest Nightly (210413 05:01 - GV89), using a HTC Nexus 9 with Android 7.1.1. Can you please check if it reproduces with the latest builds? Thank you!

can reproduce on nightly 210413 build 2015804427

1.open a page
2.menu - add
3.menu - edit
4.Click the delete icon, and then confirm to delete
5.The menu and address bar cannot be clicked before the bookmark deletion prompt disappears

https://imgur.com/HGMpnM7

**Comment by SoftVision-LorandJanos** [comment]
Hi @lindongbin! Thank you for the update! I can confirm this issue is reproducible on the latest Nightly (210429 05:01 - GV90), using a Motorola Nexus 6 with Android 7.1.1.

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01

**Comment by SoftVision-LorandJanos** [comment]
issue is still reproducible with the latest Nightly 102.0a1 (2022-05-10) build.
Device used: Google Pixel 4 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 110.0a1 (2022-12-29) build.
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813878

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
