### ISSUE TITLE
[Bug] Crashes using viewlifecyclescope in alert dialogs

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15443]
Few crashes on Sentry with the same pattern: launching in an AlertDialog off of the Fragment's view lifecycle scope. 

https://sentry.prod.mozaws.net/operations/firefox/issues/9384145/?query=is%3Aunresolved%20getViewLifecycleOwner 
 https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8650113/?query=is%3Aunresolved%20HistoryFragment

**Comment by grigoryk** [comment]
Will be great to have an understanding of _how_ this can happen, and if we should process user action or not. I guess we can start with "let's process them on an activity lifecycle scope", that gets us to at least not crash.

Aggregate volume for these on Sentry is quite significant for the release channel.

**Comment by ekager** [comment]
Instead of the activity lifecycle, we should probably use the fragment (but not fragment view) lifecycle. I also don't think we will be able to repro ourselves, but the use case AFAIK is you are pressing one of those buttons as the fragment _view_ has just been destroyed.
