### ISSUE TITLE
Add An Option To Toggle Dark Mode From 3-Dot Menu

### ISSUE THREAD

**Issue by Dev-i-l** [mozilla-mobile/fenix#15446]
IT'S A HASSLE TO GO TO SETTINGS AND TOGGLE DARK MODE. SO I SUGGEST TO ADD AN OPTION TO TOGGLE DARK MODE FROM 3-DOT MENU.

I HAVE EXPERIENCED THIS PROBLEM, IT'S KIND OF A DEAL BREAKER FOR ME

PEOPLE WILL BENEFIT FROM IT

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7499)

**Comment by Dunexus** [comment]
We can't add all the settings in 3-dot menu. Moreover, changing app theme is not something most users do very often.

ALSO, WRITING IN CAPS LOCK DOESN'T HELP READING YOUR TICKET, IT JUST MAKES IT LOOK LIKE YOU ARE SCREAMING AT THE DEVS WHO ARE WORKING HARD TO BRING YOUR THIS PRODUCT.

**Comment by Dev-i-l** [comment]
IT IS JUST A HUMBLE SUGGESTION. BTW, CAPSLOCK REALLY HELPS THE TEXT STAND OUT, YOU CAN'T BLAME ME FOR THAT LOL

**Comment by abhijitvalluri** [comment]
Feels like it will clutter the menu unnecessarily. Not all options can be or should be surfaced up to the main overflow menu.

**Comment by Dev-i-l** [comment]
ok, you have a point. but I have another solution to this problem.we can give the toggle in three dot menu of tab switcher

**Comment by abhijitvalluri** [comment]
Unfortunately it does not make any sense to put it in a completely unrelated overflow menu. This setting has nothing to do with the tab switcher.

**Comment by Dev-i-l** [comment]
I have run out of ideas, but at least people at mozilla can consider adding the toggle at 3 dot menu, why not do a survey or something as in my opinion this feature will for sure increase the quality of this great browser

**Comment by Dev-i-l** [comment]
any update on  this?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814176

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
