### ISSUE TITLE
[Bug] Swipe on the address bar to switch tabs - wrong order

### ISSUE THREAD

**Issue by bxtom** [mozilla-mobile/fenix#15457]
## Steps to reproduce

Open link in new tab. Tab opens to the left of the currently active tab. Meanwhile on desktop new tab opens to the right.

### Expected behavior

New tab should open to the right of the currently active tab to be consistent with desktop browser. 

### Actual behavior

Tab opens to the left of the currently active tab. Makes swiping confusing experience.

### Device information

* Android device: OnePlus 5T, Android 10.
* Fenix version: latest nightly.

**Comment by marco-sanjuan** [comment]
Agree.

This is important not only to be consistent with desktop browser, but consistent with most people way of thinking, as we read from left to right.

**Comment by black7375** [comment]
It's a policy I don't understand either.

**Comment by yoasif** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/13172
