### ISSUE TITLE
[Bug]History shows duplicate entries

### ISSUE THREAD

**Issue by seiko23** [mozilla-mobile/fenix#15455]
Menu > History

On the old version of Firefox mobile, if you opened the History tab, you could see a list of the sites you've visited,  but each entry would show only once a day. For example if you visited Google.com three times on Monday, then you would see one entry for it under Monday. With the upgrade, it now shows up as three separate entries. 

The upgrade also removed the ability to perform a search in the History tab.

**Comment by LaurentiuApahideanSV** [comment]
Thank you for the report, however the issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/5298. I will close this issue as it will be handled there.
