### ISSUE TITLE
add, this TRANSLATOR without new tab

### ISSUE THREAD

**Issue by zpcol** [mozilla-mobile/fenix#15458]
### What is the user problem or growth opportunity you want to see solved?
Automatic translation on Website Content

### How do you know that this problem exists today? Why is this important?
I see it has begun to add a lot of addons but there is no translator. It is very important because no one can master 200 languages in the world at once.

### Who will benefit from it?
Users who cannot master many languages.

I beg dev to add the best translator addons. 
https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/versions/

**Comment by black7375** [comment]
It looks cool.
I installed it on the desktop.

**Comment by liuche** [comment]
You can add this on Nightly! In the meantime, we're adding adons as we validate that the APIs for them have been tested. Thanks for filing!
