### ISSUE TITLE
print and save

### ISSUE THREAD

**Issue by seiko23** [mozilla-mobile/fenix#15456]
Menu > Print
Menu > Save

There used to be an option to Print or Save files. This would be helpful when a website contains information that is larger than the area that a screen capture can gather and needs to be saved on the device.

**Comment by s-ankur** [comment]
See https://github.com/mozilla-mobile/fenix/issues/3709, https://github.com/mozilla-mobile/fenix/issues/10217, https://github.com/mozilla-mobile/fenix/issues/219
