### ISSUE TITLE
[Bug] Address bar completion is stuck when pressing Enter in OSK

### ISSUE THREAD

**Issue by intrnl** [mozilla-mobile/fenix#15453]
## Steps to reproduce
- Type something in the address bar
- Tap Enter in on-screen keyboard

### Expected behavior
Completion popout should disappear after tapping Enter

### Actual behavior
Most of the time, it closes, but the artifact stays.
https://streamable.com/njn8p9

### Device information

* Android device: Redmi Note 6 Pro
* Fenix version: Nightly 200926 06:03

**Comment by liuche** [comment]
Dupe to #15464
