### ISSUE TITLE
camplete action using option no show and direct download 

### ISSUE THREAD

**Issue by praveenk466** [mozilla-mobile/fenix#15452]
### Device information

* Android device: ?
* Fenix version: ?

**Comment by praveenk466** [comment]
After downloading any file, the menu that is visible is no longer available in this new version. I do not understand that the old one was running very well and I am still running the old Firefox, I am very good  Now it seems that the menu is not visible in the new one, if someone downloads it, it is downloaded from the download manager with the menu of Fire Fox, it is not able to be downloaded from any other app.

**Comment by praveenk466** [comment]
What I used to run in the old app now, I no longer need it in this app, we will make it run the app, we should get the same as the old app, and whoever downloaded the file asked fire fox.  Now from which app do you want to download the file, he does not ask, Firefox is allowing itself to be downloaded from his manager and no other download app is allowed why

**Comment by mcomella** [comment]
Triage: this doesn't look like a performance issue: removing the label.

**Comment by liuche** [comment]
This has been fixed in #349 and is in Firefox for Android release. Please update your app to get this feature!
