### ISSUE TITLE
[Bug] Wrong link to 'What's new' page on SUMO.

### ISSUE THREAD

**Issue by TyDraniu** [mozilla-mobile/fenix#15463]
## Steps to reproduce

Click menu -> What's new.

### Expected behavior

This [SUMO page](https://support.mozilla.org/kb/whats-new-firefox-android) should be opened

### Actual behavior
This [SUMO page](https://support.mozilla.org/kb/whats-new-firefox-android-79)  opens.

### Device information

* Fenix version:  Latest Nightly

**Comment by kelimuttu** [comment]
Mine redirect me to the FAQ instead https://support.mozilla.org/en-US/kb/firefox-android-upgrade-faqs and I'm on the release version 81.1.1.

**Comment by sflorean** [comment]
I can reproduce this on Nightly 9/29, following the steps from the description.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201009`** as per [#15596](https://github.com/mozilla-mobile/fenix/issues/15596#issuecomment-705991561)
