### ISSUE TITLE
Provide confirmation dialogue when deleting multiple bookmarks

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#15467]
From the bookmarks menu it's easy to press the delete option instead of the open bookmarks.  Therefore to prevent accidental deletes of multiple bookmarks, I would suggest confirmation is needed from the user with the default option being not to delete the bookmarks.

This should only happen if more than one bookmark is selected

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7534)

**Comment by boek** [comment]
We've moved to using the undo interaction over a confirmation dialog.
