### ISSUE TITLE
[Bug] Background tabs closes after switching to another app or returning to home screen

### ISSUE THREAD

**Issue by cephirosx** [mozilla-mobile/fenix#15466]
## Steps to reproduce
1. Open Firefox for Android
2. Go to settings, turn on Close tabs
3a. Open collection tabs
4a. immediately switch to another app or return to homescreen
or
3b. Open any website
4b. Open to new tab
5b. don't switch to the new tabs
6b. switch to another app or return to the home screen
### Expected behavior
opened background tabs should still be in the tab tray after returning to firefox for Android
### Actual behavior
background tabs are gone
### Device information

* Android device: Oneplus 7 Pro
* Fenix version: 81.1.1

**Comment by cephirosx** [comment]
edited the steps to reproduce

**Comment by plfstr** [comment]
If it helps triage, I noticed this issue (detailed as steps _N_.b above) immediately after enabling ‘close tabs’ in Firefox settings:

- Settings > Close Tabs > After one month

If I switch that option back to ‘manually’, tab behaviour is as expected.

**Comment by ekager** [comment]
cc @cephirosx or @plfstr can you still reproduce this with the STR? I just tried and not sure I can
