### ISSUE TITLE
changes file extension[Bug]

### ISSUE THREAD

**Issue by ar0177417** [mozilla-mobile/fenix#15468]
* Android device: 10
* Fenix version: 81
Hello! The Firefox changes the file extension sometimes if I download a file using firedox

**Comment by SwampertX** [comment]
Hi @ar0177417 , would you mind providing an example of a link which when downloaded, the file extension changes?

**Comment by smithi7** [comment]
I see this with pascal source files, named *.pas, which whenever downloaded are renamed to *.p

Examples: any of the files from
https://www.pascal-programming.info/downloads.html

Choosing e.g. the first one, tap n hold menu shows the filename as

https://www.pascal-programming.info/lessonfiles/lesson1_program1.pas

But downloading it by tapping or by selecting download from the menu shows the file is downloaded as

lesson1_program1.p

I haven't seen this weird renaming happen on any other sort of filename, but it also happens on any website.

81.1.2 (Build #2015767041) Oreo 8.1
