### ISSUE TITLE
[Bug] all download fail, possible missing folder creation

### ISSUE THREAD

**Issue by higuita** [mozilla-mobile/fenix#15462]
## Steps to reproduce
1-reset a android tablet, locale is Portuguese
2-add sd card
3-install firefox
4-try to download any file. i even tried a mozilla.org image

### Expected behavior
File is store in device

### Actual behavior
Transfer failed popup, no matter what file or site. No other info or way to debug.
Changing the only "download" setting available, makes no difference (but i actually had a crash after changing it and trying to download again)

### Device information
* Android device: 6.0
* Fenix version: 81.0

Without any useful setting in config to change download settings, like download folder, without about:config support (by the way, way **stupid** idea to disable this, if i want a stupid browser that just support what 80% of people use, i would use chrome!), i can't really see what is failing.

To debug, i had to install chrome and trying to download, it requests permissions to use the store and download the file.
After doing this, download works in firefox by magic.
Possible firefox isn't creating the download folder or fail to correctly activate the android download. Either way it is failing on new installs

**Comment by s-ankur** [comment]
Work is ongoing for this, see https://github.com/mozilla-mobile/fenix/issues/5829

**Comment by liuche** [comment]
Thanks, closing for the dupe.
