### ISSUE TITLE
[Bug] number of tabs is wrong when opening new tab

### ISSUE THREAD

**Issue by isthisrubble** [mozilla-mobile/fenix#15472]
## Steps to reproduce

tap "tabs" button next to the url bar
tap + to open a new tab

### Expected behavior

the number in the "tabs" button goes up by one as you have opened a new tab

### Actual behavior

the number in the "tabs" button does not change

### Device information

* Android device: Samsung galaxy S10e, android 10
* Fenix version: 81.1.1 (Build #2015764547)

**Comment by RachitKeertiDas** [comment]
Hi, 
For now this seems to be intended behavior.

The New Tab actually takes you to the homescreen.
Do notice that the tab counter increments when searching or going to a URL(When a New Tab is actually opened)

This is subject to change and is currently under discussion in #12774 .

**Comment by sflorean** [comment]
@isthisrubble indeed this is the expected behavior since no website has been loaded/opened. 
Please file a feature request or follow the discussions from #12774. Thank you!
