### ISSUE TITLE
[Bug] Bottom nav bar looks skewed in Landscape mode in RTL

### ISSUE THREAD

**Issue by Xashyar** [mozilla-mobile/fenix#15476]
## Steps to reproduce

1. Put Android in a RTL language (Farsi, Hebrew, Arabic etc.)
2. Open Firefox
3. Rotate the phone to Landscape
4. Enter a URL to see 

### Expected bahavior
Nav bar should get centered as in LTR

### Actual behavior
![signal-2020-09-27-144030](https://user-images.githubusercontent.com/34171942/94363510-753b8f80-00cf-11eb-95bd-8dbdde70653f.jpeg)

### Device information

* Android device: Android 6.0.1
* Fenix version: 82.0.0-beta.1

**Comment by mcarare** [comment]
I can no longer reproduce this in latest master.

**Comment by Xashyar** [comment]
> I can no longer reproduce this in latest master.

True, tested this on the latest Nightly Build (#2015766515), hope the fix arrives on beta soon.

Closing.
