### ISSUE TITLE
Add a web, top site or PWA in android App Shortcuts

### ISSUE THREAD

**Issue by Neikon** [mozilla-mobile/fenix#15478]
it would be nice to be able to add here a PWA or web shortcut. Instead of a icon in homescreen only. It would be the fastest form to open a web without open browser>>newtab>>write web>>enter  or  open browser>>go home>>touch in a top site.

I don't like having a twitter pwa icon (for example) on my desktop, But i would like in app shortcut my pwa or top sites.
Spotify has  the last playlists in app shortcut for example

In addition If i have twitter open in a tab or I has opened it before with app shortcut and I open again twitter with app shortcut. This last acction should open the twitter tab/pwa and doesnt open another.

![InkedScreenshot_20200927-154112_LI](https://user-images.githubusercontent.com/1765319/94367045-38c26080-00dc-11eb-9ce1-6601f5bc20a1.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7560)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807100

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
