### ISSUE TITLE
[Bug] Back from reader mode and original page returns to reader mode

### ISSUE THREAD

**Issue by rolfausohnder** [mozilla-mobile/fenix#15470]
## Steps to reproduce 
search in google, open one of the results, enter reader mode, return to original page, hit back to try to return to results

### Expected behavior
return to search results

### Actual behavior
return to reader mode

### Device information

* Android device: Samsung Galaxy S9 , Android 10 with latest updates
* Fenix version: 82.0.0-beta.1

**Comment by s-ankur** [comment]
Happens on my device as well with Nightly. In fact you can get stuck in an infinite loop of normal->reader->normal->reader when pressing the back button

**Comment by LittleAngelwings** [comment]
Can Confirm that issue, but I have this behavior since one or two weeks with nightlies.

**Comment by csadilek** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1667811

**Comment by csadilek** [comment]
This is fixed now in latest Nightly (201009 17:03).

**Comment by rolfausohnder** [comment]
> 
> 
> This is fixed now in latest Nightly (201009 17:03).

Yes, that works well ! Thanks a lot !

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/12 with Samsung Galaxy Note 10(Android 10).

**Comment by rolfausohnder** [comment]
Okay, solution has arrived in beta.
