### ISSUE TITLE
[Bug] Delete button in multi select three dot menu is not red 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15471]
## Steps to reproduce
Open multi select in history or bookmarks
Open 3 dot menu
### Expected behavior
The delete button is red, which is the case for the delete button in every other 3dot menu
### Actual behavior
It is normal
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by joc-a** [comment]
I'd like to work on this.

**Comment by joc-a** [comment]
#15576

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/7 with Google Pixel 3 (Android 11) and Xiaomi Redmi Note 8T (Android 9).
