### ISSUE TITLE
Bookmarks: collapsed, re-ordered, recent list

### ISSUE THREAD

**Issue by hute37** [mozilla-mobile/fenix#15484]
### Selecting folders during bookmak save operation needs usability improvements.

Possible changes:

1. Bookmarks folder collapsed on open

2. Different ordering (synced with desktop version?), Bookmark toolbar on top.

3. "Recent" folder list, to quickly re-select last folder during navigation.

Also, 
- quick access, missing in upgrade ...
- (incremental) search
- advanced editing (keywords) ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7572)

**Comment by hute37** [comment]
Example, to save in subfolder in bookmark toolbar

![Screenshot_20200928-023447_Firefox](https://user-images.githubusercontent.com/348142/94379888-638bd380-0133-11eb-924b-b68dc2681985.jpg)
![Screenshot_20200928-023531_Firefox](https://user-images.githubusercontent.com/348142/94379900-6be40e80-0133-11eb-84bc-c33a36a1c01a.jpg)
![Screenshot_20200928-023600_Firefox](https://user-images.githubusercontent.com/348142/94379905-70102c00-0133-11eb-8e3d-70e92040e120.jpg)

**Comment by liuche** [comment]
Can you be more specific in your request? "usability problem" is not very clear. What is the behavior that you are seeing, and what is the behavior that you would expect?

**Comment by hute37** [comment]
well,
comparing with Firefox for desktop:

I miss "recent folders" and "collapsible folders" (with quick group selection (toolbar, menu, other
In this version, I have to scroll a lot to choose target folder (without a search option)

Other differences are in bookmark editing, 
but IMHO this is less important on mobile.
Maybe a "one-click" bookmark (with latest folder pre-filled) could be a nice feature


In Firefox desktop "Bookmark Save" dialog:

 - Quick Select (bookmarks toolbar, menu, others)
 - Recent Folders 
 - (Stateful) Collapsed Folders

![2020-10-16 (7)](https://user-images.githubusercontent.com/348142/96248803-6b110080-0fac-11eb-985d-1f1188c2ca99.png)

![2020-10-16 (6)](https://user-images.githubusercontent.com/348142/96248987-c6db8980-0fac-11eb-8779-b9c905d807ef.png)



- tags
- keywords

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1359612

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812709

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
