### ISSUE TITLE
[Bug] Moving the cursor should automatically scroll textareas

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15485]
## Steps to reproduce
write a long search query into github issues search box
### Expected behavior
The cursor would scroll the textarea 

### Actual behavior
I noticed that when you're editing a search query in the issues page of a GitHub repo, when you move the cursor of a long query Firefox doesn't automatically scroll the textbox. The cursor also scrolls vertically when it can only scroll horizontally. Pretty annoying.

### Device information

* Android device: ?
* Fenix version: Today's Nightly

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683259

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
