### ISSUE TITLE
[Bug] The first "Rename Collection" works, subsequent renames do not

### ISSUE THREAD

**Issue by kleintom** [mozilla-mobile/fenix#15480]
Follow up on #13836 - it seems there are cases where the rename lag still occurs.

There are exceptions, but basically it seems that each time a new Home screen is created, the first "Rename Collection" works as expected; all other "Rename Collection"s after that change the name of the collection but fail to update the UI to reflect the changed name. (There seems to be extra churn associated with the initial View creation that sidesteps the sequence described below and allows the first rename to show, but I haven't sorted out exactly how.)

The root cause of the issue seems to be the following sequence of actions:
a) The TabCollection items stored on the adapter of the RecylerView for the Collections list on the Home screen are references-to/occupy-the-same-memory-as the TabCollections on the requireComponents.core.tabCollectionStorage.cachedTabCollections list.

b) When you go to rename a collection, the Rename Collection fragment pulls its list of TabCollections off the same tabCollectionStorage.cachedTabCollections

c) When the TabCollection is renamed, it gets changed in place (i.e. not recreated as a different object with a new title), which means the copy on the RecyclerView adapter list changes in place as well, without the RecyclerView being aware of the change.

d) Now when the TabCollectionStorage observer in the HomeFragment gets notified that the TabCollection list has changed (i.e. after the user renames a Collection), the new list is pushed to the Collections RecylerView, but the RecyclerView compares the new and the old list and sees that their data is the same, and so never updates the UI.

**Comment by kleintom** [comment]
In more detail:
a) https://github.com/mozilla-mobile/fenix/blob/7d5c199e5188f1d8d553a4e732fbf9b649fd38d3/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L848 The new cachedTabCollections gets pushed to the homeFragmentStore, and when the fragment store changes, we update the UI: https://github.com/mozilla-mobile/fenix/blob/7d5c199e5188f1d8d553a4e732fbf9b649fd38d3/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L290, which updates the sessionControlAdapter using the data from the homeFragmentState

b) The CollectionCreationFragment pulls its Collections list from cachedTabCollections: https://github.com/mozilla-mobile/fenix/blob/7d5c199e5188f1d8d553a4e732fbf9b649fd38d3/app/src/main/java/org/mozilla/fenix/collections/CollectionCreationFragment.kt#L59

c) Once the collection is renamed, that collection gets pushed down to TabCollectionStorage: https://github.com/mozilla-mobile/fenix/blob/7d5c199e5188f1d8d553a4e732fbf9b649fd38d3/app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt#L95
which changes the TabCollection[Adapter] in place: https://github.com/mozilla-mobile/android-components/blob/fa040e8c05cb76147f8b3737783fcbcaa309cffe/components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/TabCollectionStorage.kt#L125
At that point the corresponding (at-the-same-memory-location) TabCollection in the Collections list's RecyclerView has changed, without the RecyclerView being informed.

d) Now again we get notified that the TabCollectionStorage has changed: https://github.com/mozilla-mobile/fenix/blob/7d5c199e5188f1d8d553a4e732fbf9b649fd38d3/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L848
so we update the cachedTabCollections list and notify the homeFragmentStore, which (as in a)) in turn causes us to push the new TabCollections list to the sessionControlAdapter of the Collection's RecyclerView, but that adapter diffs new and old TabCollections by comparing their (id and expanded state and) title: https://github.com/mozilla-mobile/fenix/blob/7d5c199e5188f1d8d553a4e732fbf9b649fd38d3/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt#L73
and concludes the two lists are the same.
At this point we again have a TabCollection item reference stored in both the cachedTabCollections and in the RecyclerView for the Collections list, which sets the next rename up to fail as well.

**Comment by kleintom** [comment]
One fix that seems to work is #15253: just manually update the Collections list UI after each rename. Another option (I think?) would be to add the ability to make a copy/clone of a TabCollection, and store clones in the Collections list adapter to break the connection between the adapter list and the cachedTabCollections list. I'm open to suggestions :-)

**Comment by liuche** [comment]
@mcarare this seems like a regression on the behavior in #13836, any idea what might have caused it?

**Comment by mcarare** [comment]
@liuche, not sure, this would need investigation. It would have seemed logical that if the first renaming works, any other future renaming would work too.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201020`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201020-090019](https://user-images.githubusercontent.com/51314259/96546526-196dbc00-12b3-11eb-819c-736e7f8c5fab.gif)
