### ISSUE TITLE
[Bug] no favicon for some sites

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#15482]
## Steps to reproduce
1. Open https://roundcube.net/
2. Add it to Top Sites

### Expected behavior
The same favicon as in FF desktop

### Actual behavior
No favicon is shown

### Device information

* Android device: OP3T Android 10
* Fenix version: latest niightly

**Comment by kbrosnan** [comment]
16x16 px favicon Duplicate of https://github.com/mozilla-mobile/android-components/issues/3814
