### ISSUE TITLE
[Bug] Custom search engines never show on the list

### ISSUE THREAD

**Issue by mackeev** [mozilla-mobile/fenix#15486]
## Steps to reproduce
In latest Nightly: add a new engine
### Expected behavior
It should appear among the engines on the list
### Actual behavior
Nothing there, BUT the browser knows about it: you can't add it again.
### Device information

* Android device: redmi note 5 pro
* Fenix version: Nightly

**Comment by mackeev** [comment]
Fixed in today's Nightly.

**Comment by mackeev** [comment]
Removed and installed today's Nightly (Oct 1). Went through adding new engines again: same problem - no show.

**Comment by liuche** [comment]
Same underlying issue as #15080
