### ISSUE TITLE
Synced Tabs: Allow opening multiple tabs in the background

### ISSUE THREAD

**Issue by StentMan** [mozilla-mobile/fenix#15481]
### What is the user problem or growth opportunity you want to see solved?
I have a bunch of tabs open on my desktop. When I'm afk and have some time to read I'd like to open a few of them and read them. Today, I need, **for every tab I'd like to open** go through the pancake menu, pick sync tabs, click a tab - rinse repeat. I'm suggesting that while I'm at the Synced tab I'll be able to pick multiple tabs and open them, similar to what's already possible to perform when I want to open multiple bookmarks.

### How do you know that this problem exists today? Why is this important?
It's not important, it'll just make using Firefox easier, make interactions more consistent (same as bookmarks).

### Who will benefit from it?
anyone who uses the Synced tabs feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7568)

**Comment by chartmix** [comment]
This would be highly appreciated.
When I move to a new phone or want to switch devices it would make the process easier.

**Comment by issue-dispenser** [comment]
I just switched devices and this feature could have made transferring the opened tabs a lot less tedious.

Please also consider an action to "open all synced tabs from [device]" to facilitate transfer of Android -> Android open tabs while ignoring desktop tabs (issue #11404 with a device filter).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810784

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
