### ISSUE TITLE
[Bug] Clicking on Reader mode just refreshes the page on whatsapp.com/features 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15498]
## Steps to reproduce
[Clicking on Reader mode  on whatsapp.com/features 
### Expected behavior
reader mode
### Actual behavior
it just refreshes the page
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 200928 (Build #2015766603).

### Device used:
- OnePlus 6T (Android 9)

**Comment by LaurentiuApahideanSV** [comment]
The issue no longer occurs on Firefox RC 87.0.0 and Nightly 210331. I will mark this issue as closed.
