### ISSUE TITLE
[Bug] Top sites flash when removing one with frecent is disabled

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#15499]
Created from https://github.com/mozilla-mobile/fenix/issues/14230#issuecomment-696029179

## Steps to reproduce
1. Disable frecent top sites.
2. Add a top site.
3. Remove the top site.

### Expected behaviour
- When removing the top site, the animation should animate only the one top site removed.

### Actual behaviour
- All top sites animate instead.

### Device information

* Android device: Motorola Moto G6 (Android 8), Google Pixel 2 (Android 9), Nexus 5 (Android 6.0.1)
* Fenix version: Nightly 200921 06:05 (Build #2015765171) GV 82.0a1 from 9/21

![](https://user-images.githubusercontent.com/48799384/93756400-bcc4a600-fc0d-11ea-80e6-c5e2451077f4.gif)

**Comment by lobontiumira** [comment]
Verified as fixed on the 92.0a1 Nightly build from 7/21 with Google Pixel (Android 10), and HTC 10 (Android 8).
I've encountered a crash after disabling the "Show most visited sites" and returning to the homescreen (filed #20449).
