### ISSUE TITLE
[Bug] status bar is greyed out when address bar is on top

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15494]
Search experience looks a little odd when the top toolbar breaks up the screen and is floating in the grey background.

![Screenshot_20201015-173124](https://user-images.githubusercontent.com/1082253/96199474-6bf25580-0f0c-11eb-9f4a-fb8fa1e6ad8c.png)

**Comment by sflorean** [comment]
@Poopooracoocoo can you please add other details, in order to reproduce the issue:
- Steps to reproduce 
- Build & device
Thank you!

**Comment by Poopooracoocoo** [comment]
@sflorean 1) set toolbar to top. 2) tap on address bar. I can repro this on today's nightly.

**Comment by liuche** [comment]
In the future, including a screenshot would make this clearer.

**Comment by Mugurell** [comment]
I think this is intended.
It makes it very clear to the user that the toolbar has focus and is actively being interacted with while the rest of what's displayed can be ignored.
Asking UX for a second confirmation.

**Comment by Poopooracoocoo** [comment]
@topotropic any updates on this?

**Comment by topotropic** [comment]
Thanks for the ping! This will be addressed with https://github.com/mozilla-mobile/fenix/issues/9118
