### ISSUE TITLE
[Bug] Three dot menu for desktop bookmarks is hidden but still functions

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15497]
## Steps to reproduce
This is with sync turned off
go to bookmarks/desktop bookmarks
click on where the 3 dot menu should be 
### Expected behavior
nothing?
or maybe you want the 3 dot menu to be visble

### Actual behavior
its not visible but it works!

### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
I can trigger crashes by renaming the folders and also this happens with sync on as well

**Comment by s-ankur** [comment]
![Screenshot_2020-09-29-00-38-19-929_org mozilla fenix](https://user-images.githubusercontent.com/33252312/94474996-17e93080-01ec-11eb-89f0-480529b9b807.jpg)

**Comment by ekager** [comment]
Let's make sure we're using `removeAndDisable()` for the menu button here https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkNodeViewHolder.kt#L67

**Comment by mrwhoknows55** [comment]
@s-ankur   I would like to work on this issue

**Comment by ekager** [comment]
Anyone can work on this!

**Comment by mrwhoknows55** [comment]
I'll submit PR after hacktoberfest kicks off!

**Comment by ekager** [comment]
We can't keep issues reserved, so it's just the first PR that we get in that will be reviewed.

**Comment by Anutrix** [comment]
It says "Can't edit default folders" for me.
![Screenshot_20201001_123839_org mozilla firefox](https://user-images.githubusercontent.com/11459028/94778953-bbe8fc80-03e3-11eb-90ee-96b211e56f7f.jpg)
Is this expected?

**Comment by Mugurell** [comment]
@sijanr also raised an important detail: the bookmarks folders' titles can occupy the entire row while the individual bookmarks are always clipped by the size of the menu button, even when that is not showing.
For this I filed #15776

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201012`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
