### ISSUE TITLE
Black loading screen

### ISSUE THREAD

**Issue by ShalokShalom** [mozilla-mobile/fenix#15491]
### What is the user problem or growth opportunity you want to see solved?

Darkreader is one of the most popular extensions and I am quite sensitive to the eyes. I can not work on computers without apps like it. Practically all of us are using dark themes in our code editors. Currently, each loading of any homepage destroys that benefit, since it is glowingly bright.

### How do you know that this problem exists today? Why is this important?

Every single time I load some homepage, my eyes get blinded and I see no good reason for this. We *beg* since *years* on the desktop edition of Firefox and nothing changes there either and fixes get often reverted one version later and so on. 

### Who will benefit from it?

First and formost light sensitive people and people who work at night.

No one will suffer, and it will take very less coding. 
Its easy to implement and has no downsides.
Thanks a lot 🙏

**Comment by liuche** [comment]
Same bug as #6313, please follow along there!
