### ISSUE TITLE
Add to homscreen menu item for bookmarks in the libaray

### ISSUE THREAD

**Issue by davidmegginson** [mozilla-mobile/fenix#15495]
## Steps to reproduce
* Open a site that has A2HS ("install") support, like Twitter
* Navigate to a specific subsection of the site
* Bookmark the page you are on
* Try to save that bookmark to your homescreen

### Expected behavior
* When you open bookmarks, there is an item in the individual bookmark context menu to save the bookmark to the homesceen

### Actual behavior
* there is no way to save the bookmark to the home screen (previously, you could do it through the bookmark context menu or the top-level Page submenu; the only option now is "install")

### Device information

* Android device: Nexus 6 (Android 7.1.1)
* Fenix version: 81.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7592)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807101

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
