### ISSUE TITLE
[Bug] PB open tabs are opened in NB after Close + undo actions

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15490]
## Steps to reproduce
1. Open a tab in Normal Browsing (E.g. Google.com)
2. Open a tab in Private Browsing (E.g. Theverge.com)
3. Open the Tabs Tray and switch to the Normal Browsing Open Tabs
4. Tap the ⋮ "More options" button and select "Close all tabs"
5. Tap "UNDO" button from the deletion confirmation snackbar 
6. Open the Tabs Tray and switch to the Normal Browsing Open Tabs
7. Close the Normal Browsing open tab by either tapping the 'x' button or by swipe closing it
8. Tap "UNDO" button from the deletion confirmation snackbar 

### Expected behavior
The correct Normal Browsing tab should be displayed (Google.com)

### Actual behavior
The Private Browsing tab is displayed in Normal Browsing (Theverge.com)

### Device information

* Android device: all
* Fenix version: Nightly Build 200928

### Notes
Noticed while checking #12860 | #15407 | #12383 

► Video 
![20200928-111510](https://user-images.githubusercontent.com/51314259/94408973-31539380-017e-11eb-9e83-e7b08a389439.gif)

❗ Not sure if this should be the expected behavior, or if this is the actual cause, but I've noticed another inconsistency if you preform the above steps vice-versa (with a slight change)

## Steps to reproduce
1. Open a tab in Normal Browsing (E.g. Google.com)
2. Open a tab in Private Browsing (E.g. Theverge.com)
3. Open the Tabs Tray and switch to the Normal Browsing Open Tabs
4. Tap the "New tab" FAB
5. Open the Tabs Tray switch to the Private Browsing Open Tabs
6. Tap the ⋮ "More options" button and select "Close all tabs"
7. Tap "UNDO" button from the deletion confirmation snackbar 
8. Open the Tabs Tray switch to the Private Browsing Open Tabs
9. Close the Private Browsing open tab by either tapping the 'x' button or by swipe closing it
10. Tap "UNDO" button from the deletion confirmation snackbar 

### Expected behavior
Display the Normal Browsing Home Screen ❓ 

### Actual behavior
The Normal Browsing Tab is automatically opened

► Video
![20200928-111431](https://user-images.githubusercontent.com/51314259/94410469-12560100-0180-11eb-801f-f0fc3ec9a1a0.gif)

@ekager Could you please review and share your thoughts ?☺️

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 201215 (Build #2015781483).

### Devices used:
- Google Pixel 3 XL (Android 9)
- OnePlus 6T (Android 9)
