### ISSUE TITLE
Add search box into add-on manager panel

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#15492]
### What is the user problem or growth opportunity you want to see solved?
It would be exciting if you add a search box into add-on manager panel, just as what you did for desktop version (see about:addons).
### How do you know that this problem exists today? Why is this important?
Current version (81.1) doesn’t provide a feature to let user search in add-on manager, and it’s support is very limited. But it’s exciting to see you announced you want give even more support for add-ons when I saw your blog, however, with the growth of extensions compatible with Fenix, the add-on manager have to display a long list of them on screen, making users feel inconvenience.
### Who will benefit from it?
Anyone who want to find for what extension he/she want would get a way to find and access it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7586)

**Comment by boek** [comment]
Dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1813984
