### ISSUE TITLE
Show all recently closed tabs within the last 5 minutes

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15505]
### What is the user problem or growth opportunity you want to see solved?
This is basically a backup for anyone who's closed all of their tabs :) 

### How do you know that this problem exists today? Why is this important?
cuz i've dunnit and missed the undo button

### Who will benefit from it?
ppl who like their tabs

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7607)

**Comment by s-ankur** [comment]
Restore last session perhaps, for parity with desktop?

**Comment by jawz101** [comment]
if I click 3 dot menu > History it shows the 5 most recently closed tabs.  And a long history of things I've browsed.  Is that not serving the same purpose?  I mean it's all there

**Comment by s-ankur** [comment]
A session might contain more than 5 or 10 tabs, if you close them all then only the first 10 are recoverable. Desktop solves this by having restore last session

**Comment by Poopooracoocoo** [comment]
And tabs can have their own history, independent of all of your history.

**Comment by jawz101** [comment]
The history button is sufficient.  There's no reason to overengineer it- esp. considering there are over 2,600 bug & feature requests open right now.

**Comment by s-ankur** [comment]
But there is already a session restore functionality (sort of) via recently closed right? What would be so different if we save all instead of just 10 specifically when we close all tabs?

Anyway, there is no expectation that the Dev's implement this request. Unless it specifically is closed as WONTF*X, it can remain open

**Comment by Poopooracoocoo** [comment]
The functionality of session restore you're referring to in desktop Firefox is different.

**Comment by Shadowspear123** [comment]
There used to be a recently closed tabs section in the history tab on old Fennec. There is also one on Firefox Nightly in the tab tray. Something akin to that would be very convenient.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812909

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
