### ISSUE TITLE
Possible locale code mapping needed for Santali

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#15502]
I've recently added Santali locale (sat-Olck) to both our l10n.toml files for Fenix and A-C.

I am unsure, but I think this locale may need some kind of mapping, as we have for Indonesian and Hebrew locales for Android:
* We have Indonesian as "id" in our toml files, however that gets mapped to "in" for Android
* We have Hebrew as "he" in our toml files, however that gets mapped to "iw" for Android
(the comment [here](https://github.com/mozilla-mobile/fenix/issues/7104#issuecomment-665432351) and the following one give some context)

Is anyone able to confirm that just adding "sat-Olck" as a locale will work, or if this locale code needs to be mapped to another specific android locale in order to work?
(CC @pocmo @liuche )

**Comment by pocmo** [comment]
I _think_ the mapping is only needed when Android knows about the locale but uses a different locale code. What we needed for Focus, and I am not sure how Fenix handles that, was a translation of the language name to display it in the UI, since Android didn't know what the locale meant.

I guess we could try creating a matching resource folder locally and see if Android will accept it.

**Comment by Delphine** [comment]
Thanks Sebastian! (and yeah, that language does look really cool!)
So in Santali Ol Chiki script, the language should be spelled like this: ᱚᱞ ᱪᱤᱠᱤ

Should I wait until you've created the folder to enable the locale under Pontoon, or can I go ahead and do that now (which will allow localizers to start working on their strings - which means you'll start getting these strings back in your repo)?

**Comment by Delphine** [comment]
Ok, so I went ahead and enabled Santali (sat-Olck) for both Fenix and a-c strings in Pontoon. I remember we usually worked this way for Focus, so crossing my fingers this will go as planned :) Thanks!

**Comment by liuche** [comment]
@Delphine did this end up working? we've had an AC update since so this should be included in a nightly if it worked (I believe?).

**Comment by Delphine** [comment]
@liuche This didn't seem to work out of the box :/ 

In this discussion above, @pocmo mentioned we could create a specific folder for this locale. However, mcarare later replied in #15763 that we need to use "sat" for Android. 

But that's not how it was set up in Pontoon given our previous discussions - and the localizers have already practically completed their work for Fenix under "sat-Olck". So I don't think there's much l10n can do on our side at this point, unfortunately :/ 

Note: we're not sure we understand why that locale code (sat-Olck) can't be used, given we use a language switcher, and support from the OS wasn't really needed (AFAIU). Please let me know!

**Comment by liuche** [comment]
This may be the locale that QA found recently showed up, but looks a little strange #16017. In app it looks like B+sat+olck - and does not seem to be translated yet.

**Comment by liuche** [comment]
@pocmo could you point me to somewhere in AC where we're doing locale renames? You mentioned that usually we need to do this for locales that Android already has but don't match, but would that be worth a try?

Also, if you have suggestions on what things to try, that would be appreciated.

**Comment by Delphine** [comment]
Going to close this since Santali has been updated to "sat" and now works on builds.
