### ISSUE TITLE
FNX-5092 ⁃ [Bug] Deleting a bookmark or a bookmark folder from edit mode crashes the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1551]
## Steps to reproduce
1. Save a bookmark.
1. Open the bookmark edit mode.
1. Tap the trashcan to delete the bookmark.

*Repeat the same steps for folders.

### Expected behavior
Bookmark / folder deleted.

### Actual behavior
App crashes.

### Device information
* Android device: Galaxy s8 (Android 9), Nexus 5 (Android 6)
* Fenix version: 4/9 build

**Comment by AaronMT** [comment]
Reproducible using 04/11 build on my Pixel 2.

**Comment by kbrosnan** [comment]
This works for me using April 16th build.

**Comment by sv-ohorvath** [comment]
Indeed this seems fixed. Closing the ticket. Thanks!
