### ISSUE TITLE
Validate JVM profiler marker calls are fast

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15515]

**Comment by mcomella** [comment]
If yes, we can move our StrictMode suppression marker to run everytime rather than just in debuggable builds.

**Comment by mcomella** [comment]
## Data
Using this PR https://github.com/mozilla-mobile/fenix/pull/15613 on local Nightly builds, I get the following values:
```
| device | profiler active? | Results (ns) |
|-|-|-|
| P2 | no | 80979.2 |
| P2 | yes | 103958.25 |
| GS5 | no | 241708.3 |
| GS5 | yes | 226367.25 |
```

Notes:
- In no profiler active, I ran 10 runs and ran tests on cold startup: i.e. I looped `force-stop && sleep 3 && start`
- In profiler active, I took 4 runs and ran tests on cold startup

## Conclusion
It's 200k nanoseconds (on the GS5), which is 0.2ms. By comparison, logging (`android.util.Log.e("lol", "test logging")`) is ~83k nanoseconds (with high variance & removing the outliers) so if we log three times, we're slower than adding a profiler marker. So it seems _okay_ to sprinkle these about, though slightly more carefully than we do log statements. If we're concerned about performance critical areas (e.g. start-up), we could record timestamps and call these methods at a later point.

The marker calls aren't significantly slower when the profiler is running either.

## Raw results
These are in the same order as the table:
- 10 runs, average: 80979.2
[74010, 82917, 79167, 77656, 90989, 76927, 83125, 85157, 74375, 85469]
- 4 runs, average: 103958.25
[90208, 90365, 141562, 93698]
- 10 runs, average: 241708.3
[291771, 221041, 217083, 234844, 210417, 306042, 238385, 226302, 231719, 239479]
- 4 runs, average: 226367.25
[224896, 244479, 226667, 209427]

**Comment by MarcLeclair** [comment]
@mcomella  I see the GS5 without profiler active being longer than with profiler active: 

```| GS5 | no | 241708.3 |```   vs  ```| GS5 | yes | 226367.25 |```

is that a formatting issue since you mentioned it was 200k slower with the profiler on?

**Comment by mcomella** [comment]
@MarcLeclair No, it was slower with the profiler on. Did you force stop the process between your tests?

**Comment by mcomella** [comment]
@MarcLeclair I think the runtime is roughly the same. There are outliers in the runs without the profiler on which could be causing the discrepancy. Unfortunately, we can't run enough times to see just how different they are.

**Comment by MarcLeclair** [comment]
I'm surprised Markers take so much time. I do know we could queue them and pass them once we capture the profile from the front end to the backend. Looking at the marker code, we don't take anything from them until we call the profiler. We could look into that if we want to add a bunch. Other option: take the time a marker takes, and we accumulate our start up time and we can infer the *real* start up time from that.

**Comment by mcomella** [comment]
I'm not sure what you mean by the last comment.

In any case, it seems like you're approving of the analysis and we can use ideas like you mentioned going forward: closing this issue.
