### ISSUE TITLE
[Bug] Sometimes it is not possible to dismiss download notifications

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15527]
## Steps to reproduce
Download a lot of images, especially from Google images
Dismiss the notifications one by one
### Expected behavior
Every notification can be dismissed
### Actual behavior
The last notification cannot be dismissed. It is not that it has failed or anything, but it just cannot be dismissed
### Device information

* Android device: Asus ZenfoneNightly 200928 06:01 (Build #2015766515)
AC: 61.0.20200925190057, 01306f87c
GV: 83.0a1-20200922094538
AS: 63.0.
* Fenix version: ?

**Comment by Amejia481** [comment]
QA could you please help us to find the STR, thanks in advance!

**Comment by sflorean** [comment]
@Amejia481 found STR:
1. search for "download pdf test files" on Google.
2. Download 2 files.
3. Open the notification bar and try to swipe **both** download notifications.

Actual results: the notifications can't be dismissed.

**Comment by Amejia481** [comment]
@s-ankur the fix should be in nightly, would you mind taking a look? Hope it is fixed for you. I will also tag the QA team to  test as they have a wide range of devices.

**Comment by AndiAJ** [comment]
Hi @Amejia481 , it **works properly with both scenarios** (images & pdf's) on the latest **`Nightly Build 201105`** using the following devices:
• Google Pixel 3a (Android 11) 
• Huawei Mate 20 Lite (Android 10) 
• OnePlus A3 (Android 6.0.1) 

► Video
![20201105-171112](https://user-images.githubusercontent.com/51314259/98259206-8018f800-1f8a-11eb-8865-2df8263cf7cd.gif)

@s-ankur - If you still encounter any problems please re-open this issue. ☺️

**Comment by Amejia481** [comment]
Thanks  @AndiAJ

**Comment by s-ankur** [comment]
No problems here! Works perfectly , thanks so much for fixing🥳🥳
