### ISSUE TITLE
FNX-5093 ⁃ Create a Raptor enabled build based on GeckoView v67

### ISSUE THREAD

**Issue by davehunt** [mozilla-mobile/fenix#1552]
### Why/User Benefit/User Problem
We'd like to run performance tests against Fenix running GeckoView v67 to compare results against Fennec v64.

### What / Requirements
Builds of Fenix with Raptor support based on GeckoView v67 that can run on a MotoG5.

### Acceptance Criteria (how do I know when I’m done?)
Successful run of Raptor page load test suite against build.

**Comment by davehunt** [comment]
I appreciate not everyone will have access to this, but this relates to the following PI request: https://moz-pi-test.atlassian.net/browse/PTE-80

**Comment by JohanLorenzo** [comment]
So far, the `greenfield` builds are made against geckoview nightly. I saw greenfield became the only variant in https://github.com/mozilla-mobile/fenix/pull/1324. I tried to `assembleArmFirefoxBeta` (after I commented out the filter), but it still builds against geckoview nightly. Any idea on how to proceed @colintheshots @pocmo ?

**Comment by davehunt** [comment]
This is no longer needed - the target is not GeckoView 68. Sorry for the noise.
