### ISSUE TITLE
no keyboard for twitter 

### ISSUE THREAD

**Issue by Eli-the-Bearded** [mozilla-mobile/fenix#15526]
Since updating four days ago, I find mobile keyboard never pops up on mobile.twitter.com. Can't type direct messages, new tweets, tweets with quotes (aka retweet with comment). I even tried "request desktop site".

In About Firefox:

81.1.1 (Build #2015764547)
AC: 57.0.6, bdbd5ccfd
GV: 81.0-20200917005511
AS: 61.0.13

Keyboard works fine on other sites, eg github here.

**Comment by purinsan** [comment]
This. It's annoying because it happens on every website. And it happens almost everytime.

**Comment by sflorean** [comment]
Tested on Nightly 9/29 and Release 81.1.1 and couldn't reproduce the issue. 
@Eli-the-Bearded what device are you using? do you have any extra steps? On Nightly is it reproducible for you? Thank you!

**Comment by Eli-the-Bearded** [comment]
I'm using a Cat S61 phone, which you've probably never encountered. In general it's very vanilla Android, but with extra hardware and ruggedization.

I don't have any extra steps that I'm aware of.  Twitter has had UI glitches like footer with action buttons being in wrong place since 80 rolled out, but they were cosmetic.

What are the steps to try Nightly? Is it in app store or do I have jump through hoops?

**Comment by ekager** [comment]
It's in the play store here: https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by Eli-the-Bearded** [comment]
Okay, keyboard works in nightly. (The ad blocking doesn't. Not sure if that's something I need to reconfigure or what, but certainly a separate matter than this ticket.)

How long between Android releases these days?

**Comment by omicron-b** [comment]
Reproduced here on Beta, on Mastodon and about:config

82.0.0-beta.1 (Build #2015765523)
AC: 60.0.1, e3661f62f
GV: 82.0-20200922183749
AS: 63.0.0

**Comment by staktrace** [comment]
I'm not getting the keyboard at all, on pretty much any text input field. This is on 81.1.5 (Build #2015769595). GV: 81.0.2-20201012085804.

**Comment by staktrace** [comment]
I don't know how widespread this is, but it seems like a "stop ship and push a dot release" kind of issue to me. @snorp @kbrosnan @ekager

**Comment by staktrace** [comment]
.. and of course after I plug in a cable to get logcat it starts working. It wasn't working all day for me on a variety of websites.

**Comment by mangoducksparkles** [comment]
This is a problem for me, too. Steps to reproduce:
1. Open a new tab
2. Navigate to https://addons.mozilla.org/en-US/android/ 
3. Tap in the search field
4. Sometimes the keyboard will show up after a delay (if so, close the keyboard)
5. Tap outside the search field
6. Tap inside the search field again
7. Keyboard never shows up again in this tab, on any site (I tried duckduckgo, ups, amazon)

I was able to reproduce this on multiple sites, but the mozilla site was the first I noticed it on. After checking multiple sites, and verifying this happened every time, I forced the app to stop. Upon re-opening FF, I can no longer reproduce this bug.

84.1.4 (Build #2015785883)
AC: 67.0.17, 2095f1a5d
GV: 84.0.3-20210106212839
AS: 67.0.0

**Comment by sv-ohorvath** [comment]
Caught a similar problem on one of the automated UI tests, tapping the homescreen nav bar didn't launch the keyboard and timed out. See:
[keyboardDelayLog.txt](https://github.com/mozilla-mobile/fenix/files/6102185/keyboardDelayLog.txt)
[Test report:](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7300464095579270765/executions/bs.b066062880ec1aa7/testcases/1/test-cases)
[Video recording](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7300464095579270765/executions/bs.b066062880ec1aa7/videos)

*Can't reproduce it manually.

**Comment by sv-ohorvath** [comment]
@Eli-the-Bearded @mangoducksparkles could you please confirm if https://github.com/mozilla-mobile/fenix/issues/18416 fixed this issue as well? Thanks!

**Comment by bgriffinte** [comment]
As noted in bug 18416, the issue does not reproduce often. I don't think I've seen it since October, and I've been using a new device since January. I'm okay with this issue being closed and marked resolved.

**Comment by Eli-the-Bearded** [comment]
As noted in bug 18416, this issue was intermittent. I don't think I've seen it since October, and I'm on a new device since January so fixes for intermittent stuff would difficult to test now. I'm okay with this being marked as resolved and closed.
