### ISSUE TITLE
[Bug] Setting img src attribute to data url might not trigger neither onload nor onerror

### ISSUE THREAD

**Issue by bmarotta** [mozilla-mobile/fenix#15528]
## Steps to reproduce

Set img src attribute via code (javascript) to an data url.

See example here: https://jsfiddle.net/uodym7g3/

Works on Firefox for Windows, but not on Firefox for Android

### Expected behavior

img is loaded or onerror event is trigerred

### Actual behavior

Nothing happens

### Device information

* Android device: A50
* Fenix version: Nightly Build 200928 17:07

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1671511

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
