### ISSUE TITLE
[Bug] Cannot auto fill on ebanking.eurobank.gr

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#15536]
## Steps to reproduce
1. Launch Fenix and access `https://ebanking.eurobank.gr/#/login`.
2. Login with valid credentials and save credentials.
3. Logout and tap on the `username` or `password` fields in order to auto-fill the recently saved credentials.
### Expected behavior
The auto-fill can be made without problems.
### Actual behavior
Cannot auto fill on ebanking.eurobank.gr
### Device information

* Android device: Any
* Fenix version: GV 80

[Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1664690).
![Screenshot_20200913-162227](https://user-images.githubusercontent.com/42831109/94569185-18c6a480-0276-11eb-9e75-d3b666beec9b.jpg)

**Comment by Soremir** [comment]
In the newer version 81.1.1 works fine! When I select the username field on the site, a pop up appears above the keyboard with "Suggested logins" and now I am able to select the login credentials I want.

![Screenshot_20200930-155704](https://user-images.githubusercontent.com/72141678/94688126-d8c6f680-0335-11eb-827b-7f423e9b166a.jpg)

**Comment by liuche** [comment]
We added login selection in 81, which fixes this issue! Please update to the newest version :)
