### ISSUE TITLE
Cannot add file:// to top sites

### ISSUE THREAD

**Issue by ThiemoWeiss** [mozilla-mobile/fenix#15532]
## Steps to reproduce
1. open local html file from internel or external storage. use file:///storage/... 
2. choose "add to home screen" from menu

### Expected behavior
Icon appears on home screen

### Actual behavior
No icon appears on home screen.

### Device information

* Android device: Galaxy S5 Neo
* Fenix version: 81.1.1 (Build #2015764545)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7638)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814179

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
