### ISSUE TITLE
[Bug] Unable to press the button of specific web pages

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#15530]
## Steps to reproduce
1. Open https://svg-edit.github.io/svgedit/dist/editor/index.html (https://github.com/SVG-Edit/svgedit)
2. Press OK button on the following dialog
> By default and where supported, SVG-Edit can store your editor preferences and SVG content locally on your machine so you do not need to add these back each time you load SVG-Edit. If, for privacy reasons, you do not wish to store this information on your machine, you can change away from the default option below.
### Expected behavior
Press OK should responce and execute it.
### Actual behavior
Fenix have no responce for that.
### Device information

* Android device: 7.0
* Fenix version: 81.1

**Comment by KrasnayaPloshchad** [comment]
This bugs is discovered in 68.0 release

**Comment by s-ankur** [comment]
In fact the entire site is unresponsive, including, the dropdown, checkbox and the cancel button. Can reproduce in nightly but works perfectly fine on desktop

**Comment by KrasnayaPloshchad** [comment]
Another steps to reproduce:
1. Open https://codebeautify.org/source-code-viewer (this is my intention to work around #3972)
2. Imput https://en.wikipedia.org/wiki/Main_Page into Enter URL field
3. Press View button

Expected behavior:
The webpage should display the source code of another webpage
Actual behavior:
Fenix have no responce for that.

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1671531

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
