### ISSUE TITLE
[Bug] 2 instances of web archive add-on showing in add-on menu because it uses page-action and browser-action 

### ISSUE THREAD

**Issue by jawz101** [mozilla-mobile/fenix#15544]
## Steps to reproduce
Installed archives extension in nightly

### Expected behavior
One instance in add-on menu

### Actual behavior
2 instances in add-on menu
### Device information

Nightly 200928 17:07 (Build #2015766603)
AC: 61.0.20200925190057, 01306f87c
GV: 83.0a1-20200922094538
AS: 63.0.0

![Screenshot_20200929-130405](https://user-images.githubusercontent.com/14151703/94598683-ebb5ca00-0254-11eb-9e4d-506b9cf7e589.png)

**Comment by jawz101** [comment]
I don't know if this is because I installed nightly today and then a bunch of the extensions and then uninstalled the web archive extension.  Later today I installed it once more and then I noticed this.  I didn't check after the first time though.

**Comment by mcarare** [comment]
There are actually 2 different entries in the menu because one is for page action and the other for browser action. Although, from the manifest i see they use the same icon so there is no way do distinguish between them.
I am not aware of other extensions with both actions.
@Amejia481 what do you think? Can we try to differentiate between actions in the menu somehow, or should extensions devs provide a way of differentiating?

**Comment by jawz101** [comment]
So is this the equivalent of an extension on the desktop having both an icon in the tray that does one thing and then a right click page option that does another?

**Comment by Amejia481** [comment]
> There are actually 2 different entries in the menu because one is for page action and the other for browser action. Although, from the manifest i see they use the same icon so there is no way do distinguish between them.
> I am not aware of other extensions with both actions.
> @Amejia481 what do you think? Can we try to differentiate between actions in the menu somehow, or should extensions devs provide a way of differentiating?

Thanks for investigating! Indeed, we are not distinguishing from [page/browser actions from each other in the UI](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenu.kt#L71)

Talking with @csadilek, he mentioned that there is something else apart from showing the two actions:

- In Fennec and Desktop, we only display one action using the same add-on code. 
- The second action doesn't work when we click it.
-  If we want to support page actions we should improve the UI.
-  The page action is disabled, but we seem to show it anyway.

**Comment by Amejia481** [comment]
From there, the first step could be to find out why Fennec/Desktop only display the one (working) action and why we display two, and from that we can determine if we want to improve the UI.

**Comment by csadilek** [comment]
Just to clarify. Desktop does display both, but shows the page action as disabled (not clickable). That's a case we don't seem to handle yet in Fenix/A-C.

**Comment by jawz101** [comment]
fixed

**Comment by dessant** [comment]
The page action is only supported by the extension on the desktop version of Firefox, and Fennec is hiding the page action declared in the manifest until `pageAction.show()` is called, as described in the [docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action).

A quick fix would be to do the same in Fenix for now, and later on rethink how page actions are visually differentiated from browser actions in the new menu design that is being flashed out by @vesta0. The way page action icons pop up in the URL bar when `pageAction.show()` is called in the desktop version of Firefox is intuitive and offers immediate access to a relevant action with a single click.

Chrome does not allow page actions and browser actions to coexist, though I think there is value in being able to show both at the same time, to offer quick contextual actions based on tab content, while also keeping a global extension UI accessible from the menu.

**Comment by dessant** [comment]
Sorry, I meant to ping @violasong in the previous comment.

**Comment by dessant** [comment]
The extension has landed in Firefox Beta. Is there a fix being planned, or should I release a workaround in the extension?

**Comment by csadilek** [comment]
@dessant Thank you for looking into this! The bug is in Android Components: https://github.com/mozilla-mobile/android-components/issues/8867.

If you have time to work around in the extension short-term or want to contribute a fix to A-C, your help is very much appreciated.

**Comment by csadilek** [comment]
This is fixed now in latest Nightly 201105 17:04. QA, please verify :).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201106`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by dessant** [comment]
I can also confirm that page actions now work as expected in Firefox Nightly. @csadilek, thanks a bunch for the fix!
