### ISSUE TITLE
[Bug] Public-available extensions are shown as "not yet available" if they are not in your custom collection

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#15545]
## Steps to reproduce
1. Install uBlock origin (or any public-available — I mean available for everyone without custom collection — extension
2. Create your collection and add extensions only available via AMO, with custom collection. See https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
3. Set your custom collection. Your browser will restart
4. Go to extension manager
### Expected behavior
You have the extension added in your custom + ublock origin (or the other public-available extensions)
### Actual behavior
uBlock origin (or the other public-available extensions) will be shown as "not yet available". This is a problem, especially because you can't enable / disable whether it will work in private mode, but also see version, last update, description and permissions.

<img src="https://user-images.githubusercontent.com/58657617/94601325-a2389f80-0293-11eb-9251-07ebac33dea9.png" width="300"> <img src="https://user-images.githubusercontent.com/58657617/94601361-ac5a9e00-0293-11eb-92be-6575c0f97780.png" width="300">

Though the extensions still work, as you can see with dark reader here
<img src="https://user-images.githubusercontent.com/58657617/94601393-b8def680-0293-11eb-9348-3d4a3304b085.png" width="300">

### Device information

* Android device: Pocophone F1
* Fenix version: Nightly 200929 **17:11** (from https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest)

**Comment by csadilek** [comment]
@B0pol This is by design. The configured collection defines what's currently supported. If you override the config and customize it to use your own collection you will need to add those add-ons to your collection.

This is not ideal yet, but the customization is really a developer feature. Stay tuned for more.
