### ISSUE TITLE
[Bug] Deleting animation replayed on exiting recently closed

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15547]
## Steps to reproduce
Delete a few items in history using multi select
Got to recently closed ,
Go back
### Expected behavior
It shows the list
### Actual behavior
It replays the deleting animation
### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 201001 (Build #2015767227).

### Device used:
- OnePlus 6T (Android 9)

**Comment by joc-a** [comment]
I'd like to work on this!
