### ISSUE TITLE
FNX-5095 ⁃ [Bug] No notification when copying the URL

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1554]
## Steps to reproduce
1. Open any link.
1. Long tap on the URL bar to copy the link.

### Expected behavior
A notification is displayed to let you know that the link has been copied.

### Actual behavior
No notification is displayed, making it hard to know if you successfully copied the URL.

### Device information
* Android device: 
  * Nexus 6P (Android 9)
  * HTC 10 (Android 8)
* Fenix version: 1.0.1915 (#11001742)

**Comment by boek** [comment]
This was fixed and should be in the latest nightly :+1:

**Comment by boek** [comment]
PR here: https://github.com/mozilla-mobile/fenix/pull/1546

**Comment by bsurd** [comment]
This has now been verified on several devices and works as expected.
