### ISSUE TITLE
Tab tray does not cover the url bar

### ISSUE THREAD

**Issue by re-hub** [mozilla-mobile/fenix#15551]
### What is the user problem or growth opportunity you want to see solved?
When clicked on tabs button tabs tray stays under the url bar so that both url bar and tabs tray are visible. The url bar says `search or enter address` so that it is easier to open a new tab. You may even add collections and top sites to tabs tray so as to get rid of the home screen.

### How do you know that this problem exists today? Why is this important?
When clicked on tabs button tabs tray covers the url bar preventing access to possible accesibilities

### Who will benefit from it?
People who value less clicks to navigate

**Comment by kbrosnan** [comment]
This is working as designed.
