### ISSUE TITLE
Faster animations

### ISSUE THREAD

**Issue by re-hub** [mozilla-mobile/fenix#15552]
### What is the user problem or growth opportunity you want to see solved?

Following changes will smoothen the UX:

- Tabs tray opens faster

- Pressing tabs button to see close tab, new private tab and, new tab options takes less time

- Pressing on links to interact takes less time

- Pressing on text to select takes less time

- Three dot menu opens faster

### How do you know that this problem exists today? Why is this important?
Interactions with the browser are slowing browsing experience.
I tried `ui.prefersReducedMotion` to no avail.

### Who will benefit from it?
Everyone

device: Moto G5s xt1754
os: Lineage OS 16.0
version: 82.0.0-beta.6

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7669)

**Comment by Poopooracoocoo** [comment]
The tab tray in particular is pretty slow +1

**Comment by jawz101** [comment]
Pixel 4a- seems fast to me

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813271

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Poopooracoocoo** [comment]
@boek I don't think this is worth keeping this issue as a lot of these animations were redone. Consider closing that issue.

@re-hub Do you still feel that the animations are slow?
