### ISSUE TITLE
Video Background Play

### ISSUE THREAD

**Issue by ZacharyGeorgeNN** [mozilla-mobile/fenix#15553]
Video background play isn't working for sites like YouTube.

**Comment by csadilek** [comment]
Thanks for filing @ZacharyGeorgeNN . I assume you're using the "Video Background Play fix" add-on? This is already tracked in https://github.com/mozilla-mobile/fenix/issues/9691 with a fix ready in Beta.

**Comment by ZacharyGeorgeNN** [comment]
I used it before the new Android update, doesn't let me use it anymore. I'm using Firefox on Android, by the way, should have been more clear.

**Comment by csadilek** [comment]
@ZacharyGeorgeNN OK, thanks for confirming. This add-on is already supported on the beta channel (Firefox for Android Beta in the Play store) and will be in the next release (next month).
