### ISSUE TITLE
Show full URL in link context menu before visiting

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15557]
### What is the user problem or growth opportunity you want to see solved?
idk

### How do you know that this problem exists today? Why is this important?
i guess it's convenient

### Who will benefit from it?
people who want to see full long urls before going to them?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7675)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809302

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
