### ISSUE TITLE
[Bug] Why always notice to open image with external app

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#15567]
## Steps to reproduce
1. Create new private tab
2. Type this URL to access: https://commons.m.wikimedia.org/wiki/File:Johnrogershousemay2020.webp
3. Press _Original File_ link 
### Expected behavior
Firefox should show a dialog to notice only if an app is requiring open image directly from browser
### Actual behavior
Firefox bumps a dialog to ask me whether to open with app, and notices me that will lost privacy.
### Device information

* Android device: 7.0
* Fenix version: 81.1

**Comment by kbrosnan** [comment]
Works for me using [Firefox for Android Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)

**Comment by KrasnayaPloshchad** [comment]
This bug happened if I allowed to open with external app in the Settings.

Another steps to reproduce:
1. Open https://en.m.wikipedia.org/wiki/File:Johnrogershousemay2020.webp 
2. Press the __description page there__ link

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on neither of the Firefox builds (3/31 Nightly, RC 87.0.0-rc.1, nor Beta 88.0.0-beta.2).
I accessed https://commons.m.wikimedia.org/wiki/File:Johnrogershousemay2020.webp in private browsing, tapped on "Original file" link, and I was redirected to the image. No dialog was displayed.

@KrasnayaPloshchad are you still reproducing this issue?

**Comment by KrasnayaPloshchad** [comment]
Yes. I have enabled Open links with apps option
