### ISSUE TITLE
Firefox is annoying users with "Failed download" notification repeatedly no matter how many times users clear them.

### ISSUE THREAD

**Issue by PranavBhattarai** [mozilla-mobile/fenix#15560]
**Firefox version**: 81.1.1
**Android**: 10
**What users don't want**: Firefox telling users about old failed downloads repeatedly every time when he/she launch the browser.
**Proof**: [Screen-record](https://imgur.com/a/hHUCm97)

**Comment by s-ankur** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15487, Thanks for reporting
