### ISSUE TITLE
FNX-5097 ⁃ [Bug] The Library menu should have a back button like the rest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1556]
## Steps to reproduce
1. Go to Your Library>History or bookmarks.
1. Tap the panel's back button.
1. Compare to the Settings menu.
    1. Expected behavior
The Library menu should have a back button to keep the flow going until you exit the menu entirely. 
    1. Actual behavior
For e.g. from a Bookmarks folder>Bookmarks>Library - here the user has to tap the "X" to close or the system back button.
    1. Device information

* Android device: any
* Fenix version: 4/11

**Comment by kbrosnan** [comment]
Confirmed this behavior using the April 16th build.

**Comment by vesta0** [comment]
It would make sense for the UX to be consistent throughout Settings and Library. Would love UX feedback on this.

**Comment by AmyYLee** [comment]
I agree this looks inconsistent. Nicole, can you confirm if this should be fixed in the library? @topotropic

**Comment by topotropic** [comment]
Yes, makes sense to add a back arrow to the Library toolbar.

**Comment by sv-ohorvath** [comment]
On the same note, the Settings menu doesn't have a "x" close button on the right, like the Library menu. Up to you to decide if that also makes sense.

**Comment by lime124** [comment]
removing 'polish' tag. this isn't polish - something is broken and confusing.
