### ISSUE TITLE
[Bug] Graphical glitch if the toolbar ain't at the default location

### ISSUE THREAD

**Issue by scanline** [mozilla-mobile/fenix#15574]
### Overview
There are some occasions - for example in a game - where you want to occupy the full available screen
space inside the browser by e.g. a `<canvas>` element.
On a mobile device this area would be scrollable using a drag gesture.
To prevent this bevaviour it's common to intercept the touchmove event and do a `preventDefault()`
on the event.
For example:
`window.addEventListener ("touchmove", function (event) { event.preventDefault(); }, { passive: false });`

This is working as expected.
Problems arise with the new default location of FireFox's toolbar at the bottom.

If you go to **Customize -> Toolbar -> Top**
thus moving it to the top of the screen, open a page that intercepts the touchmove event like I did
above (and/or possibly other touch related actions) and finally touch the screen, the screen space at
the bottom where the toolbar **would** be if it would be set to _Bottom_ gets tinted **white**.

Before touching the screen:
![FireFoxC](https://user-images.githubusercontent.com/22029272/94731425-08d9be00-0365-11eb-8e9c-472649a5474d.png)

After touching the screen:
![FireFoxD](https://user-images.githubusercontent.com/22029272/94731436-0d9e7200-0365-11eb-9989-2f921f1d10ed.png)

### Steps to reproduce
- Place the toolbar at the top (Customize -> Toolbar -> Top)
- Open the following HTML in FireFox
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>TV noise</title>
		<meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<meta name="apple-mobile-web-app-capable" content="yes">
		<script type="text/javascript">
			window.addEventListener ("touchmove", function (event) { event.preventDefault(); }, { passive: false });
		</script>
		<style>
			html,body { margin: 0; padding: 0; height: 100%; overflow: hidden; }
		</style>
	</head>
	<body>
		<canvas id="canvas"></div>
	</body>
	<script type="text/javascript">
		var canvas=document.getElementById("canvas");
		var ctx = canvas.getContext('2d');
		canvas.width = window.innerWidth;
		canvas.height = window.innerHeight;
		
		var idata = ctx.createImageData(canvas.width, canvas.height);
		var buffer32 = new Uint32Array(idata.data.buffer);
		
                for (var i=0; i < buffer32.length; i++)
		{
			buffer32[i] =  ((255 * Math.random()) | 0) << 24; 
		}
		
        ctx.putImageData(idata, 0, 0);  
	</script>
</html>
```

- Touch the screen

**Comment by s-ankur** [comment]
Related #14821

**Comment by liuche** [comment]
We're working on a fix for the browser area not painting properly with the top toolbar, so please follow along in #14821
