### ISSUE TITLE
Support setting time limits for sites through the digital wellbeing app

### ISSUE THREAD

**Issue by nsrosenqvist** [mozilla-mobile/fenix#15573]
### What is the user problem or growth opportunity you want to see solved?

Help users maintain a healthy relationship with their smart device by being able to set parameters on how much time they can spend on a site.

### How do you know that this problem exists today? Why is this important?

A lot of people spend an unhealthy amount of time on their phone and some even show addictive tendencies. Personally I'd like to be able to set a max amount of time I can spend on a site and am currently using a third-party app to accomplish this rather than using the built-in Android tools for this.

Chrome exports sites and make them configurable through the digital wellbeing app while only Firefox, the app itself, can be configured and not the individual sites.

### Who will benefit from it?

Anyone who wishes to spend less time on their phone or require extra assistance to stay focused on a task.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7697)

**Comment by NomarCub** [comment]
In what timeframe can we expect this?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808762

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
