### ISSUE TITLE
Test performance with WarpBuilder JIT changes

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15578]
Announcement email:  https://groups.google.com/g/mozilla.dev.platform/c/1PHhxBxSehQ?pli=1

**Comment by mcomella** [comment]
Triage: desktop is measuring performance and building infra/testing to do so: let's wait until that's complete before moving forward with this one.

**Comment by mcomella** [comment]
@acreskeyMoz iirc, you measured performance of some parts of the code with WarpBuilder enabled. What were your results?

**Comment by acreskeyMoz** [comment]
We saw some nice improvements with WarpBuilder in Fenix nightly pageload tests that reproduced over multiple runs:

```
SpeedIndex improved ~4.8%
ContentfulSpeedIndex improved ~2.5%
PerceptualSpeedIndex improved ~4.4%
VisualComplete85 improved ~4.8%
```
https://docs.google.com/spreadsheets/d/1jMWTCg3GDyxRZw69byTFOniOVlIfqSdUV4n4EYI-dbM/edit#gid=493292881

I'll be testing this again in the Beta stream to get more certainty. But it looks quite solid.
