### ISSUE TITLE
[Bug] Private mode is fingerprintable by nothingprivate.ml

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15575]
## Steps to Reproduce
Follow steps on https://www.nothingprivate.ml/

### Expected behavior
You should be undetectable in private mode
### Actual behavior
You are not. The site is able to tell who you are even in private mode
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by jawz101** [comment]
Preventable with privacy.resistFingerprinting set to true in about:config on nightly and beta.  Stable cannot do this

**Comment by KrasnayaPloshchad** [comment]
On the Nightly build one possible way to work around is to add [CanvasBlocker](https://addons.mozilla.org/zh-CN/android/addon/canvasblocker/) extension following instructions on this [blog post](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/).

**Comment by kbrosnan** [comment]
Private mode has always been about protecting from a local attacker being able to recover data. It is not about the site or your ISP being able to track you. If resistfingerprinting resolves this then it is something tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1260929
