### ISSUE TITLE
FNX-5099 ⁃ [Bug] No name added to a google maps bookmark

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1558]
## Steps to reproduce
1. Go to maps.google.com
1. Bookmark it.
1. Verify the bookmarks list.
    1. Expected behavior
Maps bookmark has a name.
    1. Actual behavior
No bookmark name.
    1. Device information

* Android device: Pixel (Andriod 9), Nexus 5 (Android 6)
* Fenix version: 4/11

**Comment by kbrosnan** [comment]
I end up with "Google Maps" using today's build

**Comment by sv-ohorvath** [comment]
I confirm that it shows the title if you bookmark the page without a location.
Can still reproduce this if you bookmark the page with your location coordinates. Tap the "get location" button and bookmark the page after.

**Comment by sv-ohorvath** [comment]
I actually just saw some Wikipedia & other bookmarks with a blank name. No clue yet how. But, the google maps steps are 100% reproducible.

**Comment by colintheshots** [comment]
There's a ticket #1515 showing that URLs bearing fragment identifiers don't show a title. I believe this is a duplicate and the original is something we need to fix in either Android Components or GeckoView.

**Comment by vesta0** [comment]
Will be addressed in #1515
