### ISSUE TITLE
[BUG] Failed to query Add-ons

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#15587]
When tried to open add ons manager it shows: Failed to query Add-ons errors

Fenix: Nightly 200930 17:00 (Build #2015766987)
AC: 61.0.20200925190057, 01306f87c
GV: 83.0a1-20200922094538
AS: 63.0.0

Device: Xiaomi Redmi Note 4 Android 7

**Comment by csadilek** [comment]
@RealGJ Thanks for filing. We can't reproduce here using the same build. Is it possible you configured a custom add-on collection? If so, can you share User ID and collection name?

It's also possible you hit a network issue, does the problem persist?

**Comment by RealGJ** [comment]
> @RealGJ Thanks for filing. We can't reproduce here using the same build. Is it possible you configured a custom add-on collection? If so, can you share User ID and collection name?
> 
> It's also possible you hit a network issue, does the problem persist?

Hello, @csadilek . You are right. I've configured a custom add-on collection. I couldn't try it due to that bug.

Here are user id and collection name.

gauravjani207@gmail.com

My-Add-ons
