### ISSUE TITLE
Investigating adding threshold for removing migration code to improve performance

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15581]
It's very unperformant (iirc, 100ms on high-end devices) so we should try to remove this or modify the code to be more performant.

**Comment by eliserichards** [comment]
@st3fan will discuss this with @vesta0

**Comment by st3fan** [comment]
I just updated the _PRODUCTION Fenix Migration Dashboard (High Level)_ dashboard to include the latest releases and you can see that there is still a substantial number of migrations happening.

I'll leave it up to @vesta0 to decide when we think that has bottomed-out enough, but right now we are still at 7 digits per month. Let's keep this ticket open and maybe check in at the end of next month to see where we are?

**Comment by vesta0** [comment]
Sounds good @st3fan I will add it to my backlog so we can re-evaluate in a month.

**Comment by mcomella** [comment]
Triage: waiting to see if the fenix team decides to remove this or not.

**Comment by mcomella** [comment]
Triage: we're working through it (PRs are open) but we want to wait for the beginning of a nightly cycle.

**Comment by mcomella** [comment]
Since our backfill dashboard runs nightly, we won't see an improvement in the dashboard but it should theoretically improve release: **maybe we should file a follow-up to measure it on beta/release.**

**Comment by mcomella** [comment]
Triage: PRs are still up.

**Comment by mcomella** [comment]
Triage: still waiting on a decision from product. @kbrosnan Would you be able to follow up on getting a decision about removing the migration code? If we can't remove it now, can we define when we can remove it?

**Comment by mcomella** [comment]
Triage: fenix team followed up during fenix triage. Let's hope to hear back soon.

**Comment by mcomella** [comment]
Triage: there is a decision to land this so csadilek and grigoryk expect to follow-up, perhaps after the next nightly cut (next week?).

**Comment by MarcLeclair** [comment]
Closing since we're not investigating anymore and the migration is now a [PR in Fenix](https://github.com/mozilla-mobile/fenix/issues/22489).
