### ISSUE TITLE
Fill link from clipboard opens up for same URL on every new tab

### ISSUE THREAD

**Issue by nsrosenqvist** [mozilla-mobile/fenix#15588]
## Steps to reproduce

1. Copy a link from a website
2. Open a new tab
3. Choose to not fill from the clipboard
4. Open yet another tab
5. Now it asks again, and will continue asking for the same URL into infinity

### Expected behavior

If you choose to not fill from clipboard then Firefox should stop nagging the user on subsequent new tabs for the same clipboard content.

### Actual behavior

It nags the user for the same clipboard contents every single time a new tab is opened, requiring extra taps to open a new site.

### Device information

* Android device: Pixel 3a, Android 11
* Fenix version: 81.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7717)

**Comment by ekager** [comment]
I think this needs UX feedback before a solution.

**Comment by apbitner** [comment]
While I didn't work on the initial implementation, this seems to make sense to me. @ekager can you think of any reason why we'd want to persist the clipboard link notification?

**Comment by nsrosenqvist** [comment]
*bump (to stop stale-bot)

**Comment by AdinaPetridean** [comment]
This issue is still reproducible following the steps above on the latest Nightly 109.0a1 with Motorola Moto G9 plus (Android 11). 

@vmadalin I will remove qa needed label for further investigation. Thanks!

https://user-images.githubusercontent.com/108326843/206178540-e5d6bb0d-d693-4018-8c3c-2cfc722b80d9.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807726

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
