### ISSUE TITLE
[Bug] What's new in toolbar menu opens the wrong link

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#15596]
## Steps to reproduce
- Tap on What's new in toolbar menu

### Expected behavior
- Opens the migration FAQ

### Actual behavior
- It should open What's new in 82

### Device information

* Android device: ?
* Fenix version: ?

**Comment by LaurentiuApahideanSV** [comment]
The issue also occurs on Firefox Nightly and has been reported here: https://github.com/mozilla-mobile/fenix/issues/15463.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on both the latest **`Nightly 201007`** and **`Beta 82.0.0-beta.4`** and it's still reproducible.

❌ [This link](https://support.mozilla.org/en-US/kb/whats-new-firefox-android-79) is displayed on both builds
✔️ As mentioned [here](https://github.com/mozilla-mobile/fenix/issues/15463#issue-709608110), [this link](https://support.mozilla.org/en-US/kb/whats-new-firefox-android) should be displayed. 

@boek - Please review. ☺️

**Comment by liuche** [comment]
We asked SUMO to fix the redirect on their side - we will flag for retesting when that is ready.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201009`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

The users are now re-directed to this [link](https://support.mozilla.org/en-US/kb/whats-new-firefox-android?as=u&utm_source=inproduct&redirectslug=whats-new-firefox-android-79&redirectlocale=en-US)

► Video
![20201009-091022](https://user-images.githubusercontent.com/51314259/95549412-e8b69880-0a0f-11eb-923d-6c8801301709.gif)
