### ISSUE TITLE
[Bug] With the new update search engines have been removed. They cannot be added back either.

### ISSUE THREAD

**Issue by PH320** [mozilla-mobile/fenix#15599]
### Device information

* Android device: ?
* Fenix version: ?

**Comment by PisauraXTX** [comment]
I have the same problem.

**Comment by mahlzahn** [comment]
Same here in two different Android devices (running LineageOS 16.0), starting with Firefox for Android version 81.1.4 (Build #2015768385). This happens for me for own added search engines which had been added before the update. Readding doesn't help either.

**Comment by eliserichards** [comment]
This should be fixed in #15768
