### ISSUE TITLE
Pull to refresh webpage doesnot work.[Bug]

### ISSUE THREAD

**Issue by Throb1** [mozilla-mobile/fenix#15592]
## Steps to reproduce
Open any webpage, pull from top of the site to refresh.

### Expected behavior
Must reload the opened page.

### Actual behavior
No response

### Device information

* Android device: 10
* Fenix version: 82.0.0-beta.2

**Comment by cadeyrn** [comment]
Duplicate of #9766.

**Comment by black7375** [comment]
Is there a way to activate it now?

**Comment by cadeyrn** [comment]
If you self compile Firefox for Android, yes, it's very easy. You only have to change a feature flag from false to true. Otherwise: no, there is no option within Firefox yet.

**Comment by black7375** [comment]
thank you

**Comment by kbrosnan** [comment]
Closing as a duplicate
