### ISSUE TITLE
Make GeckoView works redistributable as an alternate to Google WebView

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#15594]
### What is the user problem or growth opportunity you want to see solved?
Android’s Developer Options can switch the default WebView implementation from Google WebView, if you make GeckoView as second choice in there, Gecko could be an alternate to Google WebView when user choose to use that as WebView implementation, you will make GeckoView freer, and allow to make extensive use of it on Android.
### How do you know that this problem exists today? Why is this important?
Seen from the system settings.
![Screenshot_20201001-233222](https://user-images.githubusercontent.com/10364351/94831559-722dff80-043f-11eb-95aa-cfe2ccdb68e9.png)
Android 7.0, Galaxy S7 
### Who will benefit from it?
Anyone who have the same idea for this and want to try.

**Comment by kbrosnan** [comment]
This is not a Fenix bug. [Geckoview](https://geckoview.dev/) does not want to be a direct replacement for WebView. The APIs are not going to be the same and would unduly restrict the GV API. People should look at the [android-components](https://github.com/mozilla-mobile/android-components/) which allows the developer to switch between a WebView and Geckoview.
