### ISSUE TITLE
Slow loading of open tabs in tab tray/tab tray animation on low end tablet

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15606]
## Steps to reproduce

1. Open Fenix
2. tap tab switcher button

### Expected behavior

Tab tray opens quickly, tabs appear nearly instantly. 

### Actual behavior

Animation is slow-ish and tabs appear with a fade in effect that begins after the initial animation. The animation waits for something to happen before it starts, slowing it down further.

Profile: https://share.firefox.dev/3ikIxyo

### Device information

* Android device: HP Touchpad
* Fenix version: Fenix Nightly 201001 build 2015767225 
AC 62.0.20201001194334, 375005940 
GV: 83.0a1-20201001094020 
AS: 63.0.0

**Comment by ekager** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/11185

**Comment by mcomella** [comment]
Triage: we can't reproduce this on our low-end reference device so we suspect the device this was reproduced on is lower-end than we have the resources to support. That being said, we're refactoring the tabs tray in #21318 so please let us know if the performance gets worse. That being said, this is a good use case for us to benchmark so we added it in our list of use cases to benchmark in https://github.com/mozilla-mobile/fenix/issues/22302.
