### ISSUE TITLE
[Bug] Opening TikTok Video crashes bluetooth audio

### ISSUE THREAD

**Issue by Domenic-Y** [mozilla-mobile/fenix#15616]
## Steps to reproduce
Open a link to any TikTok video e.g https://vm.tiktok.com/ZSuqt7X8/ with Bluetooth audio
### Expected behavior
Plays Video and Audio
### Actual behavior
Video will play without audio for a few seconds then Bluetooth either disconnects or becomes glitchy repeating the same ~1 second over and over. Upon closing the page Bluetooth reconnects.
### Device information

* Android device: Samsung Galaxy A8 (2018)
* Fenix version: 81.1.1
* Bluetooth Headphones: Sony WF-1000XM3

**Comment by kbrosnan** [comment]
I can't reproduce this using a Galaxy Note 9 or a Galaxy S6 w/ Sony WH-1000XM3 (over the ear vs the in ear) headphones using nightly or release.

**Comment by Domenic-Y** [comment]
Happen to also have WH-1000XM3 and just tested and they also behave normally for me. So maybe not a bug with firefox? However I haven't had an issue with any other app. I also checked on the nightly and I still have the issue with the WF-1000XM3.
