### ISSUE TITLE
[Bug] Crash report

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#15612]
## Steps to reproduce

open https://console.ap-tokyo-1.oraclecloud.com/db/adw/create
login
crash

81.1.1 (Build #2015764547)
AC: 57.0.6, bdbd5ccfd
GV: 81.0-20200917005511
AS: 61.0.13
https://crash-stats.mozilla.org/report/index/8e1a47aa-6ce5-43c4-8ce8-9497c0201001

Nightly 201001 17:02 (Build #2015767179)
AC: 61.0.20200925190057, 01306f87c
GV: 83.0a1-20200922094538
AS: 63.0.0
https://crash-stats.mozilla.org/report/index/ba9dddce-072f-40ec-928c-8cede0201001

**Comment by liuche** [comment]
Thanks for filing this! #15011 and https://bugzilla.mozilla.org/show_bug.cgi?id=1671137
