### ISSUE TITLE
[Bug]Can't export my "Stats" from the Tomato Clock Add-on

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15625]
## Prerequisites
The Tomato Clock Add-on should be installed

## Steps to reproduce
1. Initiate a couple of breaks
2. Open the Extension from the  ⋮ Main menu
3. Tap on "Stats"
4. Tap the "Export Stats as Json" in the newly opened tab

### Expected behavior
A .json file should be exported

### Actual behavior
The stats are opened in a new tab, aren't actually downloaded

### Device information

* Android device: Google Pixel 3a (Android 11)
* Fenix version: Nightly 201002

**Comment by jawz101** [comment]
Have you contacted the add-on developer?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201124`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
