### ISSUE TITLE
[Bug] Tomato Clock "Stats" are opened in the background

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15627]
## Prerequisites
Tomato Clock Add-on should be installed

## Steps to reproduce
1. Initiate a couple of breaks
2. Open the Extension from the  ⋮ Main menu
3. Tap on "Stats"

### Expected behavior
The user should be automatically re-directed to the newly opened tab

### Actual behavior
The "Stats" tab is opened in background

### Device information
* Android device: Google Pixel 3a (Android 11)
* Fenix version: Nightly 201002

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7770)

**Comment by s-ankur** [comment]
Similar to https://github.com/mozilla-mobile/fenix/issues/13901

**Comment by AndiAJ** [comment]
Still reproducible on **`Beta 89.0.0 - beta.1`**

**Comment by lobontiumira** [comment]
This is still reproducible on the Beta 93.0.0-beta.1 build with Lenovo Tab M10 (Android 10).

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Firefox 100.0.0-Beta.1.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- OnePlus 6T (Android 9)
