### ISSUE TITLE
[Bug] All bookmarks with keywords are broken since the big update

### ISSUE THREAD

**Issue by sommerluk** [mozilla-mobile/fenix#15622]
I have defined a lot of bookmarks with keywords, among others for online dictionaries. The keywords seem to be completely broken since the big update for Firefox Android. That makes custom searches much more painful.

## Steps to reproduce
I type "ende test"

### Expected behavior
Get a translation of "test" from english to german by pons.com online dictionary

(Bookmark URL was http://de.pons.com/%C3%BCbersetzung?q=%s&l=deen&in=en )

### Actual behavior
Google search for "ende test"

### Device information

* Android device: Samsung A30
* Fenix version: 82.0.0.-beta.2

**Comment by mcarare** [comment]
@sommerluk Thank you for your report. This is already on our radar. If you have anything to add, please see https://github.com/mozilla-mobile/fenix/issues/12099. Closing as duplicate.
