### ISSUE TITLE
[Bug]Tomato Clock notification not displayed

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15626]
## Prerequisites
Tomato Clock Add-on should be installed

## Steps to reproduce
1. Initiate a break
2. Wait the countdown to end

### Expected behavior
A notification saying "Your break is done " should be displayed

### Actual behavior
Nothing happens

### Device information
* Android device: Google Pixel 3a (Android 11)
* Fenix version: Nightly 201002

**Comment by csadilek** [comment]
This should work now. Fix was https://github.com/mozilla-mobile/fenix/issues/14993.

QA, please verify :).
