### ISSUE TITLE
[Bug] Cannot change user-agent by extension

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#15621]
## Steps to reproduce
1. Install [User-Agent Switcher and Manager](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) or [User-Agent Switcher](https://addons.mozilla.org/en-US/android/addon/uaswitcher/) following your instructions on your [blog post](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)
2. Try to switch the user-agent as Firefox for Windows
3. Open https://www.bilibili.com/video/BV1mf4y1D7VA
### Expected behavior
The video page should retains desktop view
### Actual behavior
The video page switch to mobile view: https://m.bilibili.com/video/BV1mf4y1D7VA
### Device information

* Android device: 7.0
* Fenix version: Nightly 201001

**Comment by KrasnayaPloshchad** [comment]
After I updated to Nightly 201001 23:43 release, User-Agent Switcher started working, but User-Agent Switcher and Manager still doesn’t work.

**Comment by KrasnayaPloshchad** [comment]
Since Nightly 201003 release the User-Agent Switcher started working with me.

**Comment by kbrosnan** [comment]
Closing as works for the reporter

**Comment by KrasnayaPloshchad** [comment]
No. User-Agent Switcher and Manager still unable to do that.

**Comment by kbrosnan** [comment]
User agents don't define desktop view for many modern websites. Responsive web design uses display metrics to control if you get a mobile website or not. The extension would need to spoof the device aspect ratio and other display port values to get a desktop site among other things.

**Comment by KrasnayaPloshchad** [comment]
No, I just want to replace the user-agent string by extension,

**Comment by KrasnayaPloshchad** [comment]
#15837
