### ISSUE TITLE
[Bug] Synology DSM home page is incomplete (mobile version)

### ISSUE THREAD

**Issue by grmblgrmbl** [mozilla-mobile/fenix#15623]
## Steps to reproduce

Load DSM home page of Synology NAS (mobile version)

### Expected behavior

Full home page displayed

### Actual behavior

Menu on left side of page is empty. No functions of the NAS are accessible.

Switching to desktop version of page shows no problem. Chrome has no problems with mobile version.

### Device information

* Android device: Galaxy Tab S4, Android 10
* Fenix version: 81.1.2

**Comment by kbrosnan** [comment]
This is going to be impossible to debug as it is a private page. More than likely the web interface is making some assumptions that Webkit/Blink are the only mobile browser engines.

**Comment by grmblgrmbl** [comment]
These units are not that exotic, I'm sure you can borrow one for some tests. It's not a private page, it's the default management web interface of all Synology NAS.

**Comment by NeoMoucha** [comment]
I guess you can use live demo to debug this?
https://demo.synology.com/en-global/dsm

**Comment by grmblgrmbl** [comment]
Good idea, I didn't think of this.
