### ISSUE TITLE
[Bug] LeechBlock add-on's moz-extension page is displayed entirely only in Desktop site mode

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#15635]
## Steps to reproduce
1. Install LeechBlock add-on.
2. Open a page, go to three-dot menu - Add-ons - LeechBlock, and tap on the Options or Statistics button.
3. The moz-extension page of the add-on is opened (moz-extension://6182b835-c645-4801-9049-52e9d609baa5/options.html).

### Expected behavior
The page is displayed fully, without issues.

### Actual behavior
The page is stuck, the user cannot see it fully. Selecting to view the page in Desktop site mode, fixes the problem.

### Device information
* Android device: HTC 10 (Android 8), Samsung Galaxy Note 8 (Android 9)
* Fenix version: 10/2 Nightly
* Cannot test in RC or beta build, because the add-on isn't available yet.

<img src="https://user-images.githubusercontent.com/40694158/94931165-1a8ba480-04d0-11eb-8970-468b225165b9.gif" width="300" height="550" />

**Comment by KrasnayaPloshchad** [comment]
This bug is also reproducible with [Android PDF.js](https://addons.mozilla.org/zh-CN/android/addon/android-pdf-js/) and [Native MathML](https://addons.mozilla.org/zh-CN/android/addon/native-mathml/).

**Comment by lobontiumira** [comment]
The issue is not reproducible on the 3/31 Nightly build with Samsung Galaxy Note 8 (Android 9).
The page opens zoomed out, but can be zoomed in and is displayed fully.
