### ISSUE TITLE
HomeScreen/tabs concept

### ISSUE THREAD

**Issue by Neikon** [mozilla-mobile/fenix#15630]
I have seen in Reddit a UX designer looking for feedback about homescreen, so here is my concept.

It is homescreen, tabs, search and some behaviors
https://www.figma.com/file/Z5zFMS4ClKq1bx4WyXeR8n/Firefox-for-Android-homescreen-personas-public-Copy?node-id=0%3A1
Some examples pictures, more in link
![imagen](https://user-images.githubusercontent.com/1765319/94919684-274ecf00-04b5-11eb-9d54-e3074c133a7b.png)
![imagen](https://user-images.githubusercontent.com/1765319/94919694-2c138300-04b5-11eb-8b1b-d0b9f74f9c0d.png)

**Comment by cadeyrn** [comment]
This belongs to #12065.
