### ISSUE TITLE
[Bug] "Save to collection" is displayed in tabs tray menu when there are no open tabs in normal browsing

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#15632]
### Preconditions
Do not have any opened tabs in normal browsing.
## Steps to reproduce
1. Launch Fenix and open 2-3 tabs in private browsing;
2. Tap the tab counter to open the tabs tray;
3. Tap the normal browsing icon;
4. Tap the ⋮ button;
### Expected behavior
The tabs tray menu when there are no opened tabs has the options: "Tab setting" and "Recently closed tab".
### Actual behavior
The tabs tray menu has the options:  "Save to collection", "Tab settings", "Recently closed tabs".

### Notes
This is not reproducible when there are no opened tabs in private browsing and no opened tabs in normal browsing.

### Device information

* Android device: Motorola Moto G6 (Android 8);
* Fenix version: Nightly 201002 05:00 (Build #2015767273) GV 83.0a1 from 10/02

**Comment by softvision-miralobontiu** [comment]
Verified that the "Save to collection" option isn't displayed when there are no opened tabs.
Tested on 10/6 Nightly build, and on RC 81.1.3 with Samsung Galaxy Tab S6 (Android 10), and Google Pixel (Android 10).
There is a regression - the three-dot menu isn't displayed at all on RC 81.1.3 when there are no opened tabs - I've filed #15726 

![Untitled](https://user-images.githubusercontent.com/40694158/95217149-89803a80-07fb-11eb-9801-7cd947d0c370.png)
