### ISSUE TITLE
[Bug][a11y] The new collection is not selected by TalkBack when tapping on "View" , Grid View selected

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15636]
## Steps to reproduce
1. Enable TalkBack.
2. Create a collection from Tabs tray/ or add a page to a collection.
3. Tap on "View" from the -> collection created snackbar. 

### Expected behavior
The new collection is displayed. 

### Actual behavior
Top sites grid is focused. 

### Note
* When adding a new tab to a collection from tabs tray, after selection "View" from the snackbar, the three-dot menu is selected.

### Device information
* Android device: LG G7 FIT (Android 8)
* Fenix version: Nightly 10/2

**Comment by liuche** [comment]
Do we need to update the a11y layout navigation now that we added gridview?

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on 10/20 Nightly with Samsung Galaxy Tab S6 (Android 10).
After tapping on the "Collection created View" snackbar on "view", the focus jumped on the top site's area.

**Comment by codrut-topliceanu** [comment]
blocked until PR for https://github.com/mozilla-mobile/fenix/issues/16592 is landed

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201214 05:03 (Build #2015781291) GV 85 from 12/14 with Pixel 2 (Android 9).
I will close the issue and remove the qa:needed label.

**Comment by softvision-miralobontiu** [comment]
Reproduced this issue on Beta 86.0.0-beta.5 with Xiaomi Mi 8 Lite (Android 9).
After tapping on the "Collection created View" snackbar on "view", the focus jumped on the top site's area.
