### ISSUE TITLE
[a11y] Page name/URL isn't announced when swipe of the navbar is performed (switching tabs)

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#15631]
## Steps to reproduce
1. Enable TalkBack.
2. Open 2-3 pages.
3. Using 2 fingers, swipe the nav bar left and right to switch tabs.

### Expected behavior
Page name + "loading" is announced.

### Actual behavior
"Loading" is announced, without the name (URL) of the page.

### Device information
* Android device: LG G7 FIT (Android 8)
* Fenix version: Nightly 10/2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7776)

**Comment by bifleming** [comment]
Waiting to hear from Asa...

**Comment by softvision-miralobontiu** [comment]
Reproducing on Beta 86.0.0-beta.5 with Xiaomi Mi 8 Lite (Android 9).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 88.0.0-beta.4 with Pixel 2 (Android 9).

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the Beta 90.0.0-beta.3 build, with OnePlus 5T (Android 10).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible but intermittently. Sometimes the page is correctly read.
Tested with the latest Beta 94.0.0-beta.4
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible.
Tested on the latest Nightly 101.0a1 (2022-04-20T17...) build.
Device used: Google Pixel 4 (Android 12).

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the latest Fenix Nightly 106.0a1 from 9/1 with Google Pixel (Android 10).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still intermittently reproducible. Some pages are correctly read.
Tested with the latest Beta 109.0b3.
Device used: Oppo Find X5 (Android 12).

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813877

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
