### ISSUE TITLE
Missing features and issues since Fenix adoption

### ISSUE THREAD

**Issue by nunesgh** [mozilla-mobile/fenix#15642]
## User Story

As a long-time user of Firefox for Android, I must state that I am extremely disappointed by the premature release of Fenix as the new Firefox for Android. Several features that I used to rely on for everyday use were suddenly gone. I understand the need of refactoring the app so it can be more easily supported. But such a disruptive update should not have been done like this.

Users would have a far better experience if Mozilla had waited for a greater feature parity between Fenix and the previous Firefox for Android. But since we are already here, I would like to share some features I am really missing in the new Firefox and some issues I have been experiencing since the last major update.

## Dependencies

I would first suggest anyone to take a look at the latest evaluations of [Firefox for Android on the Play Store](https://play.google.com/store/apps/details?id=org.mozilla.firefox&showAllReviews=true). There is no doubt users are extremely disappointed by this update.

I could also list here several issues that were opened on GitHub since the release of Fenix as the new Firefox for Android or that are related to the missing features or current issues, but here are just a few:
- #1523
- #7865
- #12731

### Acceptance Criteria

- [ ] Reinstate access to all add-ons from [AMO](http://addons.mozilla.org/). From thousands of add-ons, Android users can now only access a handful. Not even the [Recommended](https://support.mozilla.org/en-US/kb/add-on-badges) add-ons are available anymore.
- [ ] Re-implement the **tab queue** feature. We were previously able to send several links to Firefox from other apps and those links would only load when the user decided to open Firefox. Now whenever a link is sent to Firefox, the whole app is automatically opened. _There is no tab queue anymore. Why?_ :cry:
- [ ] Re-implement the **send to other device** feature. We were previously able to send links directly to Firefox on other synced devices from any app on Android. Now it is only possible to send links to other devices by first loading the whole webpage on Firefox for Android. It is not even possible anymore to send a link to other devices from within Firefox for Android without first loading the respective webpage.
- [ ] Re-implement the **bookmark keyword** feature. We were previously able to use the bookmark keyword feature for setting-up personalized search links, a feature that is still available for the desktop version of Firefox, but that is no longer supported on Android since this last major update.
- [ ] Improve Firefox for Android **integration with the OS built-in share experience**. It has been extremely annoying to share links to **Pocket** since the last major update. Instead of performing the task on the background, Pocket is being loaded during the process, a behavior that I do not experience when sharing links from other apps to Pocket, neither did experience with the previous version of Firefox for Android. This may also relate to the _tab queue_ and the _send to other device_ missing features, since those features were beautifully integrated with the OS share experience.
- [ ] Improve Firefox for Android **performance upon first load**. Whenever I first open Firefox, it takes a while to connect to my Firefox Account and to load any webpage. The performance of the browser improves after awhile.

**Comment by andreicristianpetcu** [comment]
You can install any AMO extension in Nightly. Hope it will be in stable on 22nd of October https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by cadeyrn** [comment]
> Hope it will be in stable on 22nd of October

No, it won't be in the stable Otctober release, it's Nightly only for the moment.

**Comment by ericrbg** [comment]
I'm really sad about the lack of comment on the Tab Queue issue. The issue itself is completely locked and there seems to not even have been a hint of progress on that yet.

**Comment by kbrosnan** [comment]
Closing as this is tracked in several other bugs.

**Comment by nunesgh** [comment]
@kbrosnan, I couldn't find the open issues regarding the lack of support for **tab queue** and for **bookmark keywords**. Could you please reference those here, so I could follow their development?

**Comment by cadeyrn** [comment]
tab queue: #470
bookmark keywords: #12099 - but please note https://github.com/mozilla-mobile/fenix/issues/12099#issuecomment-704143064.

**Comment by ericrbg** [comment]
@cadeyrn Tab Queue is not open for discussion :(
