### ISSUE TITLE
[Bug] Settings (and library and add-ons) toolbar shadow is too strong

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15650]
## Steps to reproduce
1. Open Firefox
2. Tap on menu
3. Tap on settings

### Expected behavior
I don't know the values of the shadows of the toolbars in other apps but it's definitely weaker, or lower in depth

### Actual behavior
the shadow is too "strong"

### Device information

* Android device: ?
* Fenix version: Today's nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7799)

**Comment by Mugurell** [comment]
@Poopooracoocoo are you referring at the same situation as in https://github.com/mozilla-mobile/fenix/issues/15653 ?

**Comment by Poopooracoocoo** [comment]
Nope, these aren't the same issues. 

Could someone please upload some screenshots of Firefox's toolbars and some of another app? I would if I could. 

I _think_ it's been fixed. It has been several months after all:
Old (my screenshot):
![](https://user-images.githubusercontent.com/51363864/95150568-2929d280-07d4-11eb-83c8-520a6016ba65.jpg)
New (your screenshot):
![](https://user-images.githubusercontent.com/11428869/106785535-280b9380-6656-11eb-826f-11df19880619.png)

**Comment by Poopooracoocoo** [comment]
@Mugurell i'm guessing this wasn't fixed either yet?

**Comment by DragoCubed** [comment]
@Mugurell Was this fixed?

**Comment by Poopooracoocoo** [comment]
No response by @Mugurell so I'll assume this was fixed.
