### ISSUE TITLE
Add a recently updated add-ons page 

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15657]
### What is the user problem or growth opportunity you want to see solved?
Users don't know if an add-on has been updated

### How do you know that this problem exists today? Why is this important?
It's available for desktop

### Who will benefit from it?
add-on users who want to know if their add-ons have been updated

inline changelogs would be neat

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7815)

**Comment by liuche** [comment]
Related: #11326

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812454

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
