### ISSUE TITLE
[Bug] Private browsing icon also has a ripple when you tap on an add-on in the add-ons page

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15651]
## Steps to reproduce
1. Open Firefox
2. Open menu
3. Tap on add-ons
4. Install uBO
5. Click on ok
6. Tap on uBO
7. Enable run in private
8. Press back
9. Tap on uBO

### Expected behavior
private browsing icon wouldn't have a ripple

### Actual behavior
private browsing icon has a ripple

### Device information

* Android device: ?
* Fenix version: Latest nightly

![Screenshot_20201015-182611](https://user-images.githubusercontent.com/1082253/96202432-073af900-0f14-11eb-9e97-b7b06f8b3880.png)

**Comment by liuche** [comment]
including a screenshot next time would be more helpful.

honestly it looks kind of cute like an easter egg but okay, could also be a bug.
