### ISSUE TITLE
[Bug] "Homepage" link in add-ons page is not the homepage of the add-on but is actually a link to AMO

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15654]
## Steps to reproduce
click on homepage link in add-ons page

### Expected behavior
homepage of add-on

### Actual behavior
AMO

### Device information

* Android device: ?
* Fenix version: Today's Nightly

**Comment by s-ankur** [comment]
I would say that it should include both, since you need a way to rate Addons via AMO

**Comment by Poopooracoocoo** [comment]
@s-ankur agreed. that would've involved making a feature request though and i can't be bothered. i swear, we've gotta make feature requests for *everything*.

**Comment by DragoCubed** [comment]
@s-ankur Why was this marked as wont-fix? This seems like a good issue to fix.

**Comment by s-ankur** [comment]
this is done by the stalebot, nothing i can do to undo it

**Comment by DragoCubed** [comment]
@s-ankur My bad. I thought you were a Mozilla employee.

**Comment by Poopooracoocoo** [comment]
I haven't used Firefox for Android in a long time. Has thing been fixed? Can someone open a new issue if it hasn't?
