### ISSUE TITLE
Lags and freezes in fenix 81 

### ISSUE THREAD

**Issue by Aryvd** [mozilla-mobile/fenix#15652]
### Steps to reproduce 
Use fenix 81.0.1 with the specified device. 

### Expected behavior 

This isn't the case with Fenix 80, or 79 or even the new nightly version, which run perfectly fine on my device. The ui and scrolling should be smooth and not freeze every time. 

### Actual behavior 
The scrolling on any webpage lags. The tab switcher freezes everytime I try to switch to a different tab. The overall ui freezes a couple of times I try to use anything in the browser. 

### Device information

* Android device: Redmi note 7s 3gb
* Fenix version: 81.1.1
* Add-ons : Ublock Origin and HTTPS Everywhere (although the problem persists even without these add-ons)

**Comment by kbrosnan** [comment]
Would you check if [Geckoview example](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt/artifacts/public/build/geckoview_example.apk) is slow for you? It is a simple Gekcoview based browser that can help us narrow down where the problem is.

If that is fast is our [Nightly build](https://play.google.com/store/apps/details?id=org.mozilla.fenix) responsive?

**Comment by Aryvd** [comment]
Geckoview example is really fast and responsive. Doesn't lag one bit. Although it closes after I open 5-6 tabs  and visit the websites in the search results and use the browser for 5 minutes.

Nightly build is responsive too. Although did lag for 2 minutes after I opened 15 tabs, but then it was alright.

P. S. : I hope you guys implement the tab handling like in geckoview example. Because whenever I press the back button on a tab, it doesn't close, rather opens new tab page.

**Comment by MarcLeclair** [comment]
@Aryvd  would you be able to see if you can reproduce your issue on the Beta version (Fenix v82) from the play store?

**Comment by Aryvd** [comment]
Sorry for late reply (didn't get notified).

It works good-ish on beta.. Not exactly as good as nightly or geckoview, but definitely far from what 81 has.

**Comment by Aryvd** [comment]
The issue has been fixed in the firefox 81.1.4 update( 7 October one) . Just received it. Although it's not as fast as nightly, I haven't experienced any problems
