### ISSUE TITLE
Add an option to turn off automatic updates for individual add-ons and add an interface to update add-ons

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15658]
### What is the user problem or growth opportunity you want to see solved?
Users may want control over updates for add-ons for various reasons. It's particularly useful for proprietary add-ons that could be "revamped" at any moment.

### How do you know that this problem exists today? Why is this important?
it's available on desktop

### Who will benefit from it?
add-on users who want to control their updates

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7817)

**Comment by Poopooracoocoo** [comment]
@jawz101 Why did you downvote this issue?

**Comment by jawz101** [comment]
An option not to update extensions leads to outdated, vulnerable extensions.

**Comment by Poopooracoocoo** [comment]
Thanks for explaining your perspective. You can still choose to not update Firefox for desktop. That kind of thinking is what got us Windows 10 which makes me scared, having lost work multiple times because of their bugs and forced restarts. Mozilla still sort of believes that Firefox is for the people. And again, you can do this on desktop. I personally let my extensions automatically update but I can understand wanting control as I do that with Play Store and App Store updates.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814181

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
