### ISSUE TITLE
Add release notes to details page of an add-on

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15656]
### What is the user problem or growth opportunity you want to see solved?
you can't easily access release notes the way you can on desktop

### How do you know that this problem exists today? Why is this important?
because you can do this on desktop

### Who will benefit from it?
add-on users who want to know the changes in their add-ons

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7813)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812473

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
