### ISSUE TITLE
Add ability to rate, review addon in app

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15661]
### What is the user problem or growth opportunity you want to see solved?
Since we have an Addons UI within the app, it makes sense to allow users to rate the Addons that they have installed. The current route to doing this is overly complicated and involves opening AMO, which is not the proper place to install the addon for fenix in the first place. It would also be great if they could add feedback via reviews
### How do you know that this problem exists today? Why is this important?
Users cannot easily rate or review the addons
### Who will benefit from it?
Addon users, addon Devs who would like more feedback

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7822)

**Comment by Poopooracoocoo** [comment]
I don't agree. I think that Fenix should have interfaces similar to those on desktop and so a link to review it on AMO would be closer. I also imagine that they'll eventually start using AMO more in Fenix. 

but if mozilla decides that they don't want to start using AMO more, than I'd have to agree. The current state of add-ons is pretty sad.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813950

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
