### ISSUE TITLE
[Bug] native crash when quick scrolling down m.youtube.com

### ISSUE THREAD

**Issue by avie25000** [mozilla-mobile/fenix#15669]
## Steps to reproduce
open m.youtube.com
quick scrolling down
### Expected behavior
should works fine
### Actual behavior
[crashed, see gif here](https://i.ibb.co/0s82FyQ/ezgif-7-e469e5b0b169.gif) 
### Device information
No addons enabled
log info `<native crash>`
[Socorro](https://crash-stats.mozilla.org/report/index/bp-1fc3b4d3-49bb-4328-b6d0-beda40201004)  
* Android device: Redmi Note 4, Android 7
* Fenix version: Nightly 201003

**Comment by Poopooracoocoo** [comment]
that gif expired

**Comment by avie25000** [comment]
> 
> 
> that gif expired

link updated

**Comment by ale82to** [comment]
I also get native crash when fast forwarding video.

**Comment by kbrosnan** [comment]
Please provide [crash IDs or a logcat](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information) for this crash

**Comment by kbrosnan** [comment]
Sorry  missed the Socorro link in comment 0. This looks to be https://bugzilla.mozilla.org/show_bug.cgi?id=1651882 closing as upstream.
