### ISSUE TITLE
[Bug] Images not saving to gallery

### ISSUE THREAD

**Issue by ZacharyGeorgeNN** [mozilla-mobile/fenix#15666]
Using the latest version of Firefox Android. Every time I try to save an image it doesn't save to my phone's gallery like it used to before the major update. I can see them in my downloads list, but nowhere else.

**Comment by anotherus3r** [comment]
Duplicate of #8754. Fixed in latest Nightly.

**Comment by ZacharyGeorgeNN** [comment]
Will it be fixed in daylight too?

**Comment by anotherus3r** [comment]
@ZacharyGeorgeNN might be best to ask in #8754. Someone already asked if it will be uplifted into beta.

**Comment by Amejia481** [comment]
Closing in favour of #8754.

**Comment by Amejia481** [comment]
> Will it be fixed in daylight too?

We are going to added it to the uplift patches list.
