### ISSUE TITLE
[Bug] .APK files are opened in the wrong app

### ISSUE THREAD

**Issue by kotx** [mozilla-mobile/fenix#15664]
Original issue opened in [ankidroid/Anki-Android #7339](https://github.com/ankidroid/Anki-Android/issues/7339)

## Steps to reproduce
1. Download a .apk file
2. Try to open the .apk from the browser

### Expected behavior
The package installer gets opened and the user can install an APK.

### Actual behavior
AnkiDroid gets opened with the message "This isn't a valid Anki package file. Filename xxxx doesn't have .apkg or .colpkg extension"

### Notes
It seems like Firefox uses AnkiDroid as the handler for .apk files. This problem does not exist with Edge so it is likely a Firefox issue.

### Device information
* Android device: moto g power XT2041-4
* Fenix version: 81.1.2 and Nightly 83.0a1-20200922094538

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7826)

**Comment by Kyrluckechuck** [comment]
Other files that according to Firefox are registered to handle APK's include RCT3 (though if you open the APK from any other file manager it goes to the installer like expected) 😆

**Comment by qrqhuang** [comment]
I've faced the same problem in version  85.1.3. 
My phone is huawei mate20  Android 10. 

After I download an apk and type it, it promote apps to let user choose, not  apk installer. I have to open local file manager and install it. 

![Screenshot_20210221_115157.jpg](https://user-images.githubusercontent.com/17166063/108615112-8fd62280-743b-11eb-824c-f8c71208b211.jpg)


Additionally, some apk can install correctly by firefox.

**Comment by kotx** [comment]
Bump. Just checking, anybody still have the same issue? I am unable to test right now.

**Comment by Kyrluckechuck** [comment]
This shouldn't be stale, definitely still an issue

**Comment by Kyrluckechuck** [comment]
And just going to bump again since this shouldn't be skipped/closed and should be an easy fix...

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809265

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
