### ISSUE TITLE
Consider disabling firebase-core in build.gradle to lessen confusion about tracking (Google Firebase Analytics)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15662]
### What is the user problem or growth opportunity you want to see solved?

As seen on https://github.com/mozilla-mobile/fenix/issues/12809#issuecomment-662199501 and https://www.reddit.com/r/firefox/comments/j3x3mp/why_does_the_firefox_mobile_have_trackers_its/ - people who are averse to tracking and trackers (on brand for Mozilla) are distrustful of Google Firebase Analytics being included in Firefox.

There appears to be a simple way to prevent this confusion, which will help increase trust in Firefox on Android.

### How do you know that this problem exists today? Why is this important?

Fenix developers have been questioned about this here on GitHub as well as on social media. Signal also had similar questions asked of it, and were able to resolve it.

### Who will benefit from it?

People who want to trust their browser, privacy enthusiasts, the general public. 

-- 

https://community.signalusers.org/t/gcm-will-be-removed-from-google/3888/40 seems instructive here:

>here’s how Nextcloud 7 and Conversations 7 “solved” this (both use the same solution):
exclude firebase-core in build.gradle:

```
    exclude group: ‘com.google.firebase’, module: ‘firebase-core’
    exclude group: ‘com.google.firebase’, module: ‘firebase-analytics’
    exclude group: ‘com.google.firebase’, module: ‘firebase-measurement-connector’
```

> https://firebase.google.com/docs/android/setup#available_libraries says that the firebase-core library corresponds to the Analytics.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7824)

**Comment by yoasif** [comment]
@st3fan flagging you for help as per your recommendation.

**Comment by iiitomo** [comment]
Sad to see this ticket closed with no comment from devs, despite easy fix was provided in initial post.

**Comment by yoasif** [comment]
Reopen please. @kbrosnan @st3fan

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807448

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
Jonathan fixed this bug.
