### ISSUE TITLE
[Bug] Switch to tab search suggestion not appearing for topmost tab 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15677]
## Steps to reproduce
Open a website, say A.com
Click on new tab from tab tray
Type in A.com
### Expected behavior
Switch to tab: A.com appears as an option
### Actual behavior
It does not

To verify that this is the wrong behavior you can open another tab with B.com so that A.com is not the topmost tab
Then just open a new tab from tabs tray and search for A.com
In this case you can find the search suggestion for the tab

Thus the search suggestion does not work only if the tab is topmost in tab tray
### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce the issue on all of the versions of Firefox: RC 82.1.1, beta 83.0.0-beta.2, and 10/29 Nightly with Samsung Galaxy Note 8 (Android 9).

**Comment by mawen7** [comment]
Same as #16390 will be fixed by #17127

**Comment by sflorean** [comment]
The issue has been fixed and verified (this scenario was covered). Closing this as well.
