### ISSUE TITLE
[Bug] download notifications can't be swiped away

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#15673]
## Steps to reproduce
Download a file
Pull down the Android notification tray and swipe to dismiss the download complete notification

### Expected behavior
Can swipe it away

### Actual behavior
Cannot swipe it away, need to close Firefox instead

### Device information

* Android device: Sony Xperia XZ1C
* Fenix version: Nightly 201003 17:09 (Build #2015767563)
AC: 62.0.20201002143132, d96b23188
GV: 83.0a1-20201001094020
AS: 63.0.0

**Comment by s-ankur** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15527

**Comment by staktrace** [comment]
Indeed, thanks!
