### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PKailasnath** [mozilla-mobile/fenix#15672]
I  cannot  able  to  install  Firefox  mobile  browser . I  think  it  is  some  bug .
![Screenshot_20201004-181206](https://user-images.githubusercontent.com/72344123/95016162-d08cf500-066e-11eb-977a-7dd66dfdf9b4.jpg)

**Comment by s-ankur** [comment]
Can you tell us the phone model and android version?

**Comment by kbrosnan** [comment]
We can try and help you fix this but it is not a Fenix bug. The install process is handled by the Play Store. We have no control over the errors it encounters. Is there an error code that the Play Store shows?
