### ISSUE TITLE
Rename collection to saved tabs (+ some ideas to make them really nice)

### ISSUE THREAD

**Issue by Matth7878** [mozilla-mobile/fenix#15670]
### What is the user problem or growth opportunity you want to see solved?
Collections are a good idea but a lot of user don't understand them and mistake them for bookmarks.

### How do you know that this problem exists today? Why is this important?
Look at GitHub, reddit, play store : a lot of user are reporting bug because when opening them it does not refresh, or how to import old bookmarks into them because they think it's what is replacing them.

User perception could greatly improve with renaming collection to (group of) saved tabs : it would make it easier to understand it needs to be refreshed if you want to see changes.

I am going off topic but to be fully leveraged : 
- they should be operating into their own groups (like private tabs)
- adding or removing a tab should directly impact group -> what is show on homepage should just be a view of what is in the group
- homepage would be used to manage them so you can open / close group or whatever you need (apart from open all these management should be also accessible from three dot menu in tab tray for current group)

### Who will benefit from it?
Everyone

**Comment by liuche** [comment]
Thanks for filing this! We know this can be a confusing feature, so we're making some improvements in #5652 - may be similar to what you're describing ;)
