### ISSUE TITLE
[Bug] Save button initially enabled when editing a saved login when no changes have been made

### ISSUE THREAD

**Issue by joc-a** [mozilla-mobile/fenix#15675]
## Steps to reproduce

1. Have one saved login
2. Click on the saved login
3. Click on 3 dot menu, then click on Edit

### Expected behavior

The Save button on the top right is disabled and gets enabled only after making changes.

### Actual behavior

The Save button is enabled initially, remains enabled after making changes, and gets disabled only after undoing the changes and going back to the original state.

### Device information

* Android device: ?
* Fenix version: 81.1.1

**Comment by joc-a** [comment]
#15676

**Comment by Mugurell** [comment]
This seems like a nice improvement, thanks!

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 10/8 with Google Pixel 4 XL (android 11).
Note that the `save button` is grayed out when no changes are made in edit mode.
