### ISSUE TITLE
[Bug] Phone reboots when closing a tab

### ISSUE THREAD

**Issue by Shoresh613** [mozilla-mobile/fenix#15684]
## Steps to reproduce
Close tab

### Expected behavior
Tab closed 

### Actual behavior
Phone thrown into quick dirty reboot, sometimes even a second time 

### Device information

* Android device: Samsung Galaxy Note 3, Android 5.0
* Fenix version: ?
Firefox 81.1.2 (Build #2015767041)
AC: 57.0.7, 68343a885
GV: 81.0.1-20200930150533
AS: 61.0.13

**Comment by kbrosnan** [comment]
Please provide a [logcat of the problem](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information).

**Comment by s-ankur** [comment]
By any chance are you using LineageOS @Shoresh613

**Comment by Shoresh613** [comment]
No, I'm on stock ROM.

Almost seems like installing logcat again healed Firefox. I can't reproduce
the bug any more, even when not running logcat.

Den 6 okt 2020 15:02 skrev "Ankur Sonawane" <notifications@github.com>:

**Comment by kbrosnan** [comment]
Closing as not reproducible.
