### ISSUE TITLE
[Bug] addons in nighlty (close other tabs) 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#15680]
now that we are allowed to install whatever extension we like to in fenix nighlty all "close other tabs" addons i tried, even vim - like style are not working.
I also suggested to add close other tabs to long press tab switcher butto n hopefully.

**Comment by kbrosnan** [comment]
This is tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1583281
