### ISSUE TITLE
[Bug]  youtube.com - Cannot share video.

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#15685]
## Steps to reproduce
1.Enter the firefox preview
2. Enter youtube.com
3. Choose any video.
4. Click on share.
5. Nothing happens.
### Expected behavior
That the video can be shared, get the link.
### Actual behavior
Nothing happens, you don't get the link to share.
### Device information
Huawei Y9 Prime (2019) - Android 10
Huawei P20 lite (2019) - Android 10
Vestel Venüs V3 - Android 6.0.1
* Android device: Yes
* Fenix version: Fenix 5.2

**Comment by kbrosnan** [comment]
Fenix 5.2 is an ancient version. Please update to a modern version.
