### ISSUE TITLE
[Bug] Widget does not update automatically

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#15682]
Firefox widget does not update automatically

# Firefox Widget:
![Firefox](https://user-images.githubusercontent.com/23485114/95037681-acfe9480-06d8-11eb-8ab5-e2bad37feb36.gif)
I have to resize the widget after changing the theme.

# Google Widget:
![Google](https://user-images.githubusercontent.com/23485114/95037690-b7209300-06d8-11eb-8b90-4b1e7cd0a901.gif)
Other widgets do not have this problem.

**Comment by kbrosnan** [comment]
What version of Android and device? Are you using a custom homescreen?

**Comment by xmha97** [comment]
> 
> 
> What version of Android and device? Are you using a custom home screen?

I'm using [Android Pie (9.0)](https://www.android.com/versions/pie-9-0/) on my [Xiaomi Mi 6](https://www.mi.com/global/mi6/).
No, I'm using [system launcher](https://www.apkmirror.com/apk/xiaomi-inc/miui-launcher/).

**Comment by xmha97** [comment]
My phone launcher has been updated and apparently, this problem has been fixed.
