### ISSUE TITLE
FNX-5104 ⁃ [UX] Collections

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1568]
This is the feature to replace Sessions

Amy (Updated Screens April 25)
Flow: https://mozilla.invisionapp.com/share/U2RMIIZYBKE

- - -
cc @AmyYLee @shorlander @mheubusch I added flow and screens above, please feel free to update and resolve any open questions – I'd appreciate it if we can go with a minimal implementation for MVP :-)

**Comment by mheubusch** [comment]
add invision here and send along in the github board.

**Comment by AmyYLee** [comment]
@boek @pocmo I updated the spec at the top of this bug with animation specifications (on the far right). Let me know if you have any questions. I will clean up the sketch file and share that with you as well.

**Comment by AmyYLee** [comment]
Updated spec with swipe gestures/long-press for deleting tabs from collections.

**Comment by AmyYLee** [comment]
There are some small updates to the spec above. Please let me know if you have any questions.

**Comment by AmyYLee** [comment]
@boek 
Spec update: 
Save to collections - Select tabs screen 
• Removed archive icon and replaced it with "SAVE" text.
<img width="363" alt="Screen Shot 2019-04-29 at 12 17 40" src="https://user-images.githubusercontent.com/5992746/56910645-1062ac80-6a79-11e9-8015-5fb3dbff1c5d.png">

**Comment by AmyYLee** [comment]
UX Edits List (WIP):

1. Align "Add new collection" to previous toast height.
![Screen Shot 2019-05-10 at 2 14 52 PM](https://user-images.githubusercontent.com/5992746/57548064-0ae54c00-732e-11e9-9642-2deb2c32248a.png)

2. The feather gradient is missing from behind the toast in "select tabs" so when you scroll there is a hard line 
![Screen Shot 2019-05-10 at 2 29 43 PM](https://user-images.githubusercontent.com/5992746/57548898-1c2f5800-7330-11e9-810c-d16dff94ce54.png)

**Comment by AmyYLee** [comment]
@sblatz @ekager I've posted UX edits above. I'll be on PTO so please reach out to @topotropic if you need a UX person to review or have questions. Please check-off the ones that are completed. Thanks!
