### ISSUE TITLE
[Bug] Long press tab counter -> New Tab does not always bring up keyboard with Search

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#15688]
## Steps to reproduce
Put Android into "Light mode" (as opposed to Dark or Night mode)
Fenix has white URL bar with dark text
Close all tabs
Quit Fenix & restart
Fenix has zero open tabs
open first tab on mozilla.org by typing in the URL bar
Short tap tab counter to move to tab tray
open second tab using the blue + FAB
navigate second tab to google.com by typing in the URL bar
on google.com tab, long press tab counter & tap New Tab.
-> New Tab page does not appear in Search mode - **incorrect behavior**
Short tap tab counter to bring up list of tabs
Select google.com tab
Switch Android into Dark mode. Fenix has a dark URL bar & light text
on google.com tab, long press tab counter & hit New Tab.
-> New Tab page appears in Search mode - **correct behavior**

I see this with Swiftkey and with Samsung Keyboard

### Expected behavior
New Tab page always appears in Search mode

### Actual behavior
New Tab page rarely appears in search mode

### Device information

* Android device: Galaxy A40
* Fenix version: Today's

**Comment by eliserichards** [comment]
The keyboard is not being expanded when we open search from new tab. Let's revisit the entrypoints and make sure they are all handled correctly

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201020`** using the following devices:
• Google Pixel 3a (Android 11) - Swiftkey
• Samsung Tab S6 (Android 10) - Samsung Keyboard
• Samsung Galaxy S10+ - (Android 10) - Samsung Keyboard
• Huawei Mate 20 Lite (Android 10) - Swiftkey
• Samsung Galaxy Note 8 (Android 9) - Samsung Keyboard
• Samsung Galaxy S7 (Android 7) - Samsung Keyboard
• OnePlus A3 (Android 6.0.1) - Swiftkey

► Video
![20201020-102259](https://user-images.githubusercontent.com/51314259/96554160-d4e81d80-12be-11eb-99ff-1b5e8b1c6808.gif)
