### ISSUE TITLE
[Bug]fenix always asking for download confirmation 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#15681]
even when disabling external download manager why is fenix always asking for download confirmation?
is there any settiñ in about:config to disable this behavoiur?
thanks

**Comment by kbrosnan** [comment]
`about:config` Is not used to interact with the Fenix UI. Are you in private mode?

**Comment by liuche** [comment]
We don't want users to accidentally download something without realizing it - sometimes links might not look like a download, and we want to make sure the user is aware. If you use the context menu instead (to save image, or download link) it does not ask for confirmation.
