### ISSUE TITLE
[Bug] gezginler.net - page Scrolling not working correctly

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#15683]
## Steps to reproduce
1. Open firefox
2. Go to the site "http://gezginler.net" 
3. Will scroll the page up and down
### Expected behavior
As a result scrolling should work correctly and the page will scroll down
### Actual behavior
In fact scrolling does not work correctly and the page does not scroll down. 
### Device information
Huawei Y6 Pro - Android 5.1
Vestel Venüs V3 Android 6.0.1
* Android device: Yes
* Fenix version: 5.2

**Comment by kbrosnan** [comment]
Fenix 5.2 is an ancient version. Please update to a modern version.

**Comment by BigSamSampson** [comment]
the page does not scroll down when the modern version is installed (firefox for android beta 82.0.0)

**Comment by kbrosnan** [comment]
Page does not scroll on Chrome either. This looks like a desktop website.
