### ISSUE TITLE
[Bug] Service worker doesn’t works with specific webpage

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#15697]
## Steps to reproduce
1. Open https://webbrowsertools.com/qrcode-reader/ until the process bar is gone
### Expected behavior
The webpage should display an area to take a QR code from webcam
### Actual behavior
The webpage giving following notice:
> Your browser does not support service workers. This application need to register a service worker to operate.
### Device information

* Android device: Galaxy S6 Android 7.0
* Fenix version: 81.1.2

**Comment by eliserichards** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1670989

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by snorp** [comment]
This works fine for me. It doesn't work in a private tab because Service Workers are not enabled there (on purpose).

**Comment by eliserichards** [comment]
Is there more helpful messaging that could happen?

**Comment by snorp** [comment]
The error message is generated by the web content, so there isn't anything Gecko (or GeckoView) can do here.

**Comment by KrasnayaPloshchad** [comment]
@snorp Yes, you’re right.

**Comment by liuche** [comment]
closing since we do not enable service workers in private tabs.
