### ISSUE TITLE
[Bug] Navigation bar freezes after choosing 'IMAGES'

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#15692]
## Steps to reproduce
1. Open firefox preview 5.2
2. Insert google.com page addres im search bar
3. Insert random word in Google search bar (in this case "covid-19") and click search
4. Chose 'VIDEO' from navigation bar under search bar, slide the bar left/right
5. Chose 'IMAGES' from navigation bar
### Expected behavior
On page with images I can slide the navigation bar left/right and see other options and contents
### Actual behavior
On page with images, navigation bar freezes, can't slide right/left
### Device information
Samsung Galaxy A5 (2017) - Android 8.0 
Vestel Venüs V3 -Android 10.0
General Mobile Gm8 Android 9
* Android device: Yes
* Fenix version: 5.2
![1](https://user-images.githubusercontent.com/66958331/95090068-86b71400-072d-11eb-92d3-6c82efb1dc39.PNG)

**Comment by kbrosnan** [comment]
Please update to a modern version of Fenix and retest.

**Comment by BigSamSampson** [comment]
modern version also has this problem (firefox for android beta 82.0.0)

**Comment by kbrosnan** [comment]
This looks to be a Google web search bug. Looks like the images page is not scrollable.
