### ISSUE TITLE
[Bug] SVG image incorrectly renders text as a solid black shape

### ISSUE THREAD

**Issue by Lonami** [mozilla-mobile/fenix#15691]
## Steps to reproduce

1. Navigate to https://raphlinus.github.io/ui/druid/2019/11/22/reactive-ui.html.
2. Scroll down to the image under the section "Tree transformations".
3. Notice the image renders wrong.

### Expected behavior

The image should render fine, as it does when opened on its own tab https://raphlinus.github.io/assets/reactive-ui-trees.svg.

### Actual behavior

It shows a a solid black shape where the text should be:

![Screenshot_20201005-144111_Firefox_Nightly](https://user-images.githubusercontent.com/6297805/95081023-40f05080-0719-11eb-899c-b978f55edbb7.png)

### Device information

* Android device: Redmi Note 6 Pro (custom ROM)
* Fenix version: Nightly 201004 17:02 (Build #2015767755)
AC: 62.0.20201002143132, d96b23188
GV: 83.0a1-20201001094020
AS: 63.0.0

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1669289
