### ISSUE TITLE
Implement a Mozilla/Fenix custom account type

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#15694]
### What is the user problem or growth opportunity you want to see solved?
Fennec was previously registering custom "Firefox" account types.
This allowed to easily sync with the same account on more Mozilla products.
Fenix should offer the same functionality.
A Firefox account existing on the device would be recognized by other and then users would be automatically signed in / after entering only the password.

### How do you know that this problem exists today? Why is this important?
With Fenix superseeding Fennec users won't have a "Firefox" account in Settings -> Accounts and it won't be possible to easily share the same logins between multiple Mozilla apps (or different Fenix release channels apps).
This would probably increase fxa usage since users would have a more easy way of signing in.

### Who will benefit from it?
All users whom would use more Mozilla applications.

----------
I think this was initially added to Fennec with the following patch - https://github.com/mozilla-services/android-sync/pull/348/files
Android documentation:
- https://developer.android.com/reference/android/accounts/AccountManager
- https://developer.android.com/training/id-auth/custom_auth

**Comment by liuche** [comment]
@grigoryk do you know if this is something that we would want to do, in the context of the Accounts/Android ecosystem? (Maybe Pocket...?)

**Comment by Mugurell** [comment]
I think this would still be a nice addition to the app.
Asking @grigoryk about it.
