### ISSUE TITLE
[Bug] Google.com.tr - Maps - fenix crashes when using share button

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#15693]
## Steps to reproduce
1. Open the firefox preview 5.2
2. Go to Google.com.tr
3. Search "Turkey"
4. Tap Maps
5. At the footer panel tap "Turkey"
6. Tap Save button
7. Tap back button
8. Tap Share button
9. Tap back button
### Expected behavior
Window with share functionality will close but the app won't close
### Actual behavior
The app crashes
### Device information
 Xiaomi Redmi Note 4X - Android 7.0
Vestel Venüs v3 - Android 6.0.1
* Android device: yes
* Fenix version: 5.2
![2](https://user-images.githubusercontent.com/66958331/95092758-af8cd880-0730-11eb-85d5-ee1877b67a7e.PNG)

**Comment by kbrosnan** [comment]
Fenix 5.2 is an ancient version. Please update to a modern version.
