### ISSUE TITLE
[Bug] Download Finished X covered by text in German

### ISSUE THREAD

**Issue by PisauraXTX** [mozilla-mobile/fenix#15698]
## Steps to reproduce
Download any file with Fenix, an image for example. Do not click "open" on the message that comes up in Fenix on the bottom of the screen. Feel free to click the notification that comes up in system notifications. 
### Expected behavior
The message will go away at some point or I can simply swipe if I don't want to see it anymore. 
### Actual behavior
The message is now here forever. It will not go away unless you click it to open the downloaded file or close the tab. 
### Device information

* Android device: Fairphone 3 with /e/ OS (Android 9) 
* Fenix version: Daylight, 81.1.1

Just to make that clear, I am not talking about system notifications. That issue has been adressed elsewhere. I am talking about the message that pops up on the bottom of the screen within Firefox. 
My suggestion is to simply have the message disappear after five to ten seconds, or to include a function to close it manually - either by swiping or with a button.

**Comment by VMadalin** [comment]
First of all, thank you @PisauraXTX for the issue reported. The current behaviour that I discover is the following that allow you to dismiss/hide apart of open it. 

![Screenshot 2020-10-05 at 19 25 12](https://user-images.githubusercontent.com/18151158/95117877-2fbb3a00-0741-11eb-8e55-b560f26c3bc3.png)

1) If you scroll the page up you can hide the notification and continue to navigate.
2) Tap the **X** close button on the notification to dismiss it. 

Will be great to validate this behaviour with someone from UX team, but in any case, this report is more a feature request more than an issue

**Comment by Amejia481** [comment]
I think this is similar to this comment https://github.com/mozilla-mobile/fenix/issues/15239#issuecomment-696158882

**Comment by PisauraXTX** [comment]
>     1. If you scroll the page up you can hide the notification and continue to navigate.
> 
>     2. Tap the **X** close button on the notification to dismiss it.

Thank you for your answer. 

The first option is not working for me. I scroll all the way to the top of the page and the notification is still there. 

The second option does work! I realized why I didn't see the close button until now: The X symbol is covered by text. 
I use the German language version of the browser. The message "Download abgeschlossen (x,xx MB)" is so long that the X overlaps with "MB" and is thus not visible at first glance. So there we have our bug. 

I would be very happy if the message could be adapted in localized versions so that the text and the X symbol do not overlap.

**Comment by VMadalin** [comment]
Thank you @PisauraXTX for your reply. You are right regarding the first option but this is because you have enabled on the settings the option called `External download manager` this opens the popup like non-cancelable alert without the possibility to tap outside to hide/dismiss it. 

Regarding the text overlapping, you mention I gonna check it more in detail but definitely may happen if the layout isn't prepared for it.
