### ISSUE TITLE
Remove feature flag for ETP cookie purging

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#15703]
Followup to #15701 

https://github.com/mozilla-mobile/fenix/pull/15701 enables ETP cookie purging for all channels (this is going to be uplifted into beta). 

This issue is to remove the `etpCookiePurging` feature flag altogether once the feature is working in production.

**Comment by ekager** [comment]
Can we do this now? I'm a bit confused by the history here clicking through the tickets

**Comment by eliserichards** [comment]
This was missed in our sprints after we uplifted it, so we never followed up :(
