### ISSUE TITLE
Ghostery

### ISSUE THREAD

**Issue by BrokenShoeLace** [mozilla-mobile/fenix#15708]
Allow this extension to work or be installed again.

**Comment by RachitKeertiDas** [comment]
Hi,

Support for this addon has already been added in Firefox Nightly.
Please wait for the update to land on the Stable/Beta Channels.

**Comment by BrokenShoeLace** [comment]
https://addons.mozilla.org/en-GB/firefox/addon/ghostery

Not available on Firefox for Android. You can use this add-on with Firefox for Desktop. Learn more about add-ons for Android.

**Comment by cadeyrn** [comment]
> Not available on Firefox for Android.

As @RachitKeertiDas already said: Ghostery is already supported on Firefox Nightly and will probably also be supported be on the stable release channel soon.

**Comment by kbrosnan** [comment]
Closing as tracking individual extensions is not a goal of the webextensions project. They are focusing on the [APIs that are defined](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions).

**Comment by mohibo** [comment]
> 
> 
> https://addons.mozilla.org/en-GB/firefox/addon/ghostery
> 
> Not available on Firefox for Android. You can use this add-on with Firefox for Desktop. Learn more about add-ons for Android.

we didn't asked for desktop

**Comment by mohibo** [comment]
> 
> 
> https://addons.mozilla.org/en-GB/firefox/addon/ghostery
> 
> Not available on Firefox for Android. You can use this add-on with Firefox for Desktop. Learn more about add-ons for Android.

this is not the github for desktop
