### ISSUE TITLE
FNX-5107 ⁃ Bookmark deletion should offer undo snackbar

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1571]
When the user deletes bookmarks, the app should present an undo snackbar as per the final UX in #242.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on Fenix version 1.0.1916 (Build#11061212).
Tested with Sony Xperia Z5 (Android 7.1.1), Nokia 6 (Android 7.0), and Samsung Galaxy S8 (Android 9.0).
