### ISSUE TITLE
[Bug] PDF downloads without file extension, cannot open, possible JavaScript issue?

### ISSUE THREAD

**Issue by isthisrubble** [mozilla-mobile/fenix#15715]
## Steps to reproduce
go to my.gov.au, log in, and access the inbox

open a message

tap the message attachment to download

### Expected behavior

pdf is downloaded

### Actual behavior

file without file extension is downloaded, file cannot be opened (have tried to open with Firefox, drive PDF viewer and Adobe acrobat). firefox "download failed" message appears.

when file is opened in a text editor, it contains html code for a page within said government website. android html viewer can open file if .html is added to file name. this page is an "unsupported action" page, which includes a warning that the website will not work without JavaScript running.

if I long-press and hit "download link" instead, it downloads a html file that contains what I think is the same webpage.

when .pdf is added to file name, file still cannot be opened, with error message that the file "is of invalid format"

I have tried requesting desktop site, turning off tracking protection, and turning off ublock origin. no change.

I can download this file fine with the desktop version of firefox, but I don't always have access to a PC. if I can't download from this website, I can't access letters from the government about actions I need to take to continue receiving my pension.

### Device information

* Android device: Samsung S10E, android 10
* Fenix version: 81.1.2

**Comment by isthisrubble** [comment]
AND a day later the failed download notifications won't stop coming back. it's like it tries to download again every time I restart the app. unfortunately clearing the cache did not help

**Comment by Amejia481** [comment]
We did some improvement to downloads in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). Would you mind trying on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to see if it's fixed for you? Hopefully it will fixed :)

**Comment by isthisrubble** [comment]
@Amejia481 in nightly the downloaded works, but when you tap the "download complete" pop up or notification, nightly says there are no apps that can open the file. I can open the file in adobe acrobat or google drive if I access it from my file manager app. I guess nightly cannot detect that I have those apps installed?

**Comment by Amejia481** [comment]
> @Amejia481 in nightly the download works, but when you tap the "download complete" pop up or notification, nightly says there are no apps that can open the file. I can open the file in adobe acrobat or google drive if I access it from my file manager app. I guess nightly cannot detect that I have those apps installed?

It could be that we are not getting the right metadata to open the correct app. Is this only happening on my.gov.au or is there any other site that doesn't require to be logged in ? If that is the case we could close this issue as  the filed is downloaded correctly, what do you think? :)

**Comment by isthisrubble** [comment]
@Amejia481 I guess you can close the issue, assuming whatever the fix in nightly is will make its way to regular firefox eventually. I don't really download pdfs from places that don't require being logged in so I can't answer that question unfortunately

**Comment by Amejia481** [comment]
I agree we can close it for now, please feel free to reopen if neeeded
