### ISSUE TITLE
Zoom to text input on focus

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15729]
### What is the user problem or growth opportunity you want to see solved?

Especially in desktop view on non-mobile sites, it can be hard to type text into input fields when the browser viewport is not zoomed to the input. This will help usability in these instances. 

### How do you know that this problem exists today? Why is this important?

User report: https://www.reddit.com/r/firefox/comments/ixgunh/has_there_been_a_recent_change_in_behaviour_of/

Other browsers do this. Fennec did this. It is important because not zooming is less usable, and because other browsers do this, making this a critical missing feature for a11y. 

### Who will benefit from it?

People who type into input fields, especially those who browse desktop sites without mobile versions.

**Comment by kbrosnan** [comment]
Tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1669588
