### ISSUE TITLE
[Bug]"Pull to refresh" toggle option is displayed for a couple of seconds when changing Fenix's theme

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15725]
## Steps to reproduce
1. Open the "Customize" section from Settings
2. Change the Theme
3. Check the "Home" and "Gestures" subsection

### Expected behavior
Properly displayed "Home" and "Gestures" subsection

### Actual behavior
After changing the Theme the "Home" subsection isn't displayed for a couple of seconds
Instead, the "Pull to refresh" option toggle is displayed for a couple of seconds in the "Gestures" subsection

### Device information

* Android device: 
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

* Fenix version: 
• Nightly 201006
•Beta 82.0.0-beta.4

### Notes

► Video
![20201006-165212](https://user-images.githubusercontent.com/51314259/95212435-5dae8600-07f6-11eb-80b1-995f5aaea04d.gif)

**Comment by joc-a** [comment]
#16324

**Comment by ebalazs-sv** [comment]
Verified as fixed on the latest Nightly 201117 05:03 (Build #2015776107) GV 84 from 11/17 with the following devices:
- Motorola Moto G6 (Android 8);
- Google Pixel 2 (Android 9).

I will remove the qa:needed label and close this issue.

**Comment by Amejia481** [comment]
Thanks @ebalazs-sv!
