### ISSUE TITLE
FNX-5108 ⁃ Move the "try again" button for error pages once we no longer obscure bottom web content

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1572]
Waiting on https://github.com/mozilla-mobile/fenix/issues/552. 

For now I had to put the back button slightly above where it should be on the web page so the URL bar does not obscure it. Once #552 is merged, we should change this.

**Comment by softvision-miralobontiu** [comment]
On phone, the "Try again" button is displayed to the bottom, without been obscured.
Tested with the latest build 1.0.1922 (#11530616), with Motorola Moto G6 (Android 8), Huawei P9 Lite (Android 6), and Google Pixel (Android 9).
