### ISSUE TITLE
[Bug] Gittigidiyor.com-Cannot login with facebook

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#15722]
## Steps to reproduce
1.Open the firefox (v81.1.1) or firefox beta (v82.0.0)
2.Search the gittigidiyor.com
3.Tab on "Login"
4.Tab on "Google"
5.Click to back button of your device
6.Tab on "Facebook"
### Expected behavior
The Users expents to login with facebook account
### Actual behavior
Unable to login, tab is not working
### Device information
Vestel venüs v3
* Android device: yes
* Fenix version: firefox for android beta (82.0.0)

**Comment by Amejia481** [comment]
Thanks @BigSamSampson for the report, if you disable tracking protection does it work?

**Comment by BigSamSampson** [comment]
Hi @Amejia481 , even if I disable tracking protection, it still does not work.I added a video, you can see it from there

![2020 10 06-17_50_21](https://user-images.githubusercontent.com/66958331/95218807-59d23200-07fd-11eb-8c72-4ef92c5630e1.gif)

**Comment by Amejia481** [comment]
Thanks @BigSamSampson!

**Comment by mini536** [comment]
I have tried, if you clear all firefox data, disable enhanced tracking protection, and then try to log in with facebook again, you will successfully log in to the site
