### ISSUE TITLE
[Bug] Three-dot menu isn't displayed in tabs tray on RC 81.1.3 when there are no opened tabs

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#15726]
## Steps to reproduce
1. Make sure there are no opened tabs.
2. Tap on the tabs counter and observe the three-dot menu.

### Expected behavior
The three-dot menu is displayed in the right corner of tabs tray.

### Actual behavior
The three-dot menu isn't displayed.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 10), Google Pixel (Android 10)
* Fenix version: RC 81.1.3
* Not reproducible on 10/6 Nightly build
* Regression - please see #15632 

![Untitled](https://user-images.githubusercontent.com/40694158/95216837-31e1cf00-07fb-11eb-9cf9-33a2f02bb47b.png)

**Comment by Poopooracoocoo** [comment]
#15020

**Comment by Poopooracoocoo** [comment]
This was fixed in nightly and yet there were no commits or PRs referencing #15020?

**Comment by mcarare** [comment]
This was fixed in https://github.com/mozilla-mobile/fenix/pull/15507.

**Comment by softvision-miralobontiu** [comment]
I'll close this, as it is not implemented in RC yet.

**Comment by Poopooracoocoo** [comment]
> 
> 
> This was fixed in #15507.
> #15632 has nothing to do with this.



> 
> 
> This was fixed in #15507.
> #15632 has nothing to do with this.

ah okay. this issue confused me a _lot_, it didn't help that there were two issues of the same issue
