### ISSUE TITLE
[Bug] Android Share Dialog instead of Firefox Share Dialog

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#15739]
Hello Firefox Developers
When I hold on a link and select the "Share link" option, the Android share dialog is displayed instead of Firefox share dialog.
Because of this, I can not open a link on another device.

Click on the below screenshot to see it:
![Firefox](https://user-images.githubusercontent.com/23485114/95274052-a5aec680-0851-11eb-83a3-ac394a53daaa.gif)

**Comment by kbrosnan** [comment]
Duplicate of #2819
