### ISSUE TITLE
Locale sign-off for v82

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#15731]
Today is the announced deadline for l10n getting into v82 (please let me know if this has changed).

- [ ] New locale: Tajik ("tg") - needs to be added for release in both Fenix and A-C.
List of locales otherwise should remain unchanged.
- [x] Please import latest translations before cutting off for the release.

Note: we've added Tagalog ("tl") and Santali ("sat-Olck") to Pontoon, but I don't see them appear in Nightly, so localizers can't test them yet. I do see both locales have been added to the l10n.toml locales lists - both in the mozilla-l10n repo and back into the Fenix + A-C ones. Any idea what's going on? thanks!
Edit: I've filed #15763 for this
(CC @liuche @pocmo)

**Comment by liuche** [comment]
@st3fan we'll need to do this as part of the Beta uplift process too - there's a [script](https://github.com/mozilla-mobile/fenix/blob/master/l10n-uplift.py) that we run to pull in all the newly landed strings. 

This is a task that I've been doing for my team, but we should have a rotating releng role to do it.

**Comment by Mugurell** [comment]
@liuche This ticket is assigned to us but it's not quite clear what we should do.

**Comment by liuche** [comment]
Ah, I realize this is not actually documented anywhere. 

Run this [script](https://github.com/mozilla-mobile/fenix/blob/master/l10n-uplift.py) based on the instructions, targeting the beta branch.

At some point, I'll also document this 😬 either in the wiki, or the better place would be, to update the [release checklist](https://github.com/mozilla-mobile/fenix/blob/master/.github/ISSUE_TEMPLATE/release_checklist.md).

**Comment by Mugurell** [comment]
For AC 60.0 I got
> Since 'releases/60.0' split off 'master', there were 0 commit(s) from release+l10n-automation-bot@mozilla.com.

so looks like just the above Fenix PR is needed.

**Comment by st3fan** [comment]
I will pick this up for Firefox Beta 82-beta.5 as part of the uplifts next Tuesday. For me this is also the first time doing this. My goal is to get it out in a Beta build next week.

**Comment by st3fan** [comment]
Oh I see now that @Mugurell 's patch is for the 82 branch already. Fantastic - it looks like that will cleanly merge. I'll re-read the changes to see if it looks structurally sound and then uplift it?

**Comment by liuche** [comment]
Sounds good - once you've signed off, you can close this bug.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter, and it seems that **Tajik ("tg") **isn't available yet on** **`82.0.0-beta.5`** 
✔️ Works properly on the latest **`Nightly 201014`** build

@Mugurell - Could you please review and advise? ☺️

**Comment by Mugurell** [comment]
Based on https://github.com/mozilla-mobile/fenix/compare/v82.0.0-beta.4...v82.0.0-beta.5 the strings should be there (there are new string files referenced in `l10n.toml`).

I think they were somehow lost, or just not included in the build, maybe because of [this script which should build the `SUPPORTED_LOCALE_ARRAY`](https://github.com/mozilla-mobile/fenix/blob/ee673348bf986340bd27b52492c9560c93469828/app/build.gradle#L565) but has a few issues. (already saw that it doesn't work on Windows because of the file separators)

**Comment by Mugurell** [comment]
Unfortunately the build process is too opaque too know for sure.
Since we'll probably need a new beta build, it could contain a new `System.out.println(foundLocalesString)` added [immediately before `SUPPORTED_LOCALE_ARRAY` is set](https://github.com/mozilla-mobile/fenix/blob/ee673348bf986340bd27b52492c9560c93469828/app/build.gradle#L581) to be sure if this is an issue with the build or somewhere in code.

**Comment by Mugurell** [comment]
A local beta build of the same `v82.0.0-beta.5` tag has the `Tajik ("tg")` available.

**Comment by liuche** [comment]
We're making a beta.6, could you verify the `tg` locale on that build? Thank you!

**Comment by AndiAJ** [comment]
Hi @liuche & @Mugurell , **Tajik ("tg")** is still missing from 82.0.0-beta.6

**Comment by Mugurell** [comment]
A local build of `d3e93fed1a4c4a25c85dadc97ef49435bce6c0f0` from `releases/v82.0.0` shows the `Tajik` available while it can't be seen on the recent build. 
Decompiling the official build I see it doesn't even contain the `values-tg` resources although they exist in the source code.

**Comment by liuche** [comment]
Reading through these comments, it looks like we might have tried to cover too many steps in this issue, and I wasn't clear enough on what we needed to do.
- Uplift locales - this was done by running the script, thank you @Mugurell !
- `tg` Tajik is ready to be enabled on Release (I missed this part) and I've opened #15984 for it.

And the other item that was split out is #15502

**Comment by liuche** [comment]
Can QA test on the newly tagged 82.1.0-rc.2 build? thank you!

**Comment by sflorean** [comment]
'tg' locale is listed on 82.1.0-rc.2 - closing as verified. 
Devices: Pixel 3 (Android 11), LG G7 FIT (Android 8).
