### ISSUE TITLE
[Bug] Restaurant menu crashes firefox or causes no tabs to render 

### ISSUE THREAD

**Issue by iodream** [mozilla-mobile/fenix#15732]
## Steps to reproduce
1. Go to http://93.175.203.100:8088/  
(it's a webpage for a simple restaurant menu which doesn't seem to have a domain name)
2. scroll down, notice the choppy behavior. at least that's what i'm getting
3. scroll up.
4. If the page doesn't crash refresh the page a couple of times.  

### Expected behavior
Firefox doesn't slow down, renders the webpage and doesn't crash.
### Actual behavior
Firefox slows down considerably, after some time it [stops rendering](https://i.imgur.com/quPBB22.png) the webpage entirely and only shows a blank white page. 
If i open an extra tab now with any other web page,  it loads the page but doesn't render anything. If i close all tabs and open google.com it doesn't render anything. The problem only goes away if you swipe Firefox away from the recents menu. 
There is also a high chance the browser will just crash completely and generate a crash report.    
### Device information

* Android device: Moto g5. Android 8.1.0
* Fenix version: Nightly 201005

[Crash report](https://crash-stats.mozilla.org/report/index/cbe608d8-de3e-4755-b873-77d0e0201006)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1669611
