### ISSUE TITLE
[Bug] apple.com - it Is not possible to make a purchase

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#15745]
## Steps to reproduce
1. Open firefox
2. Open the site apple.com
3. Click the menu on the left
4. Select iPhone
5. Click Buy
6. Wait for load page
7. scroll Down and up the page
### Expected behavior
As a result there should be characteristics at the top of the page that you need to select in order to continue the purchase
### Actual behavior
In fact the page at the top is empty and it is not possible to finish the purchase
### Device information
Huawei Y6 Pro - Android 5.1
vestel venüs v3 -android 6.0.1
* Android device: yes
* Fenix version: firefox 81.1.1  and  firefox for android beta 82.0.0
![3](https://user-images.githubusercontent.com/66958331/95309965-7b322d00-0894-11eb-89d7-35b2cae2bead.PNG)
![4](https://user-images.githubusercontent.com/66958331/95309970-7c635a00-0894-11eb-856c-d0941af1b207.PNG)

**Comment by kbrosnan** [comment]
This seems like some sort of A/B on Apple's side test as I can't get the same problem on the same version of Firefox on different phones. I had a problem on Nightly running on a Pixel 2 XL, using the same build on a Moto G5 did not reproduce. Clearing app data on Pixel 2 XL gave me a working page.

**Comment by BigSamSampson** [comment]
![chrome](https://user-images.githubusercontent.com/66958331/97306504-a09cd000-186f-11eb-8e75-deed1d0ec8cb.gif)
![firefox](https://user-images.githubusercontent.com/66958331/97308105-8a900f00-1871-11eb-97e9-cb0b476c6200.gif)

Clearing app data on Vestel Venüs V3 gave me the same problem again. Webpage loads slower in Firefox browser than Chrome browser , therefore it is not possible to finish the purchase on the page. I added videos of Chrome and Firefox browsers.
