### ISSUE TITLE
[Bug] Reader view stuck in back button loop

### ISSUE THREAD

**Issue by Paulire** [mozilla-mobile/fenix#15746]
## Steps to reproduce
Open a webpage which would work with reader mode. Open reader mode. Pressing the back button repeatedly.

### Expected behavior
After pressing back it should return you to the webpage view. Then pressing back again should take you to the previous page.

### Actual behavior
Pressing back on webview takes you back to reader mode. Pressing it again takes you back to the webview and the cycle continues. This also happens on nightly.

### Device information

* Android device: Android 10 on Motorolla G8 Power
* Fenix version: Fenix 81.1.1

**Comment by s-ankur** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/15470, thanks for reporting!

**Comment by mcarare** [comment]
Closing as duplicate of #15470 .
