### ISSUE TITLE
FNX-5110 ⁃ Create a tab group

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1574]
As a user, I want to save the sites in my current browsing session as a group so that I can organize information in a way that is meaningful to me.

### Acceptance criteria
* I can select some or all of the open tabs in my current session
* I know how many tabs I have selected
* I can save the selected tabs as a discrete group 
* I can access the group and see which sites were saved to the group without opening all of the sites into a new browsing session

**Comment by sblatz** [comment]
### Updated UX

The creation screen for a tab collection on the "select collection" step:
- The collection list should not "float above" the selected tabs as seen in the image below.

BEFORE:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/4400286/58052403-97032a80-7b09-11e9-9a22-38fa70ee5bb0.png">
AFTER:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/4400286/58052417-9f5b6580-7b09-11e9-95fa-7e589af7a889.png">

Instead, the tabs should be pushed above the collection list

Per conversation with @topotropic.

**Comment by sv-ohorvath** [comment]
@sblatz In the mockups (https://mozilla.invisionapp.com/share/8ZQVRNUJW3H#/screens/359019534) I see that a new collection created should show a purple border animation. 
And there is one issue that I also noticed, #2412 (the save collection button is missing).
Were this changed in the meantime?

**Comment by sblatz** [comment]
@sv-ohorvath the "save collection button" should be available in tomorrow's build 😄 

The purple animation should be covered by https://github.com/mozilla-mobile/fenix/issues/2359

**Comment by sv-ohorvath** [comment]
Thank you @sblatz! I can close this now :)

**Comment by sv-ohorvath** [comment]
Reopened to add new blocking issues.

**Comment by sblatz** [comment]
The blocking bugs should be fixed by #2748.

**Comment by sv-ohorvath** [comment]
All blocking issues were fixed.
