### ISSUE TITLE
[Bug] Can't add custom search engine on latest nightly

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#15741]
Add any custom search engine, it prompts that the addition is successful, but the list is not displayed

Nightly 201006 17:38 (Build #2015768139)
AC: 62.0.20201002143132, d96b23188
GV: 83.0a1-20201001094020
AS: 63.0.0

**Comment by mcarare** [comment]
@lindongbin Thank you for your report! This issue has already been reported. Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/15711.
