### ISSUE TITLE
[Grid View] Fix the margins for the tabs in the grid view

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15757]
margin-start and margin-end should be 16dp instead of the current 8dp for the tabs in the grid view. https://www.figma.com/file/luMaQYjwiMtQM5xQ30P9yP/Tabs?node-id=2%3A0

I think we need to add a margin-start/end for the RecyclerView instead of the tab items because otherwise we would have a 32dp gap between the tabs. It gets a bit more complicated because the parent RecyclerView is shared between the list and grid view.

**Comment by gabrielluong** [comment]
Spoke to @Mugurell about https://github.com/mozilla-mobile/fenix/issues/13427 and https://github.com/mozilla-mobile/fenix/issues/15756, where we are both looking into a new solution for displaying the selected border. Since we might both might be touching the layout, we should probably wait a bit from the investigation of both issues.

**Comment by gabrielluong** [comment]
I think @Mugurell has a likely fix for this already.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201103 05:01 (Build #2015773417) GV 84 from 11/3 with

- Motorola Moto G6 (Android 8);
- Pixel 2 (Android 9);
- Samsung Galaxy Tab S3 (Android 8),

and when the tabs tray is in grid view, the space between the opened tabs is the same.
Tested this in normal and private browsing, light and dark theme, portrait and landscape mode.

I will remove the qa:needed label and close this issue.
