### ISSUE TITLE
[Bug] Background playback of Youtube playlists doesn't work

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#15753]
## Steps to reproduce
1. Use a Firefox version with #9691 fixed.
2. Install the Video Background Play Fix add-on.
3. Open any Youtube playlist you'd like, e.g. https://www.youtube.com/watch?v=kMvznKdlVUg&list=PL4B22D54E54AC7CB9
4. Put the Youtube tab in background (or Firefox as a whole, doesn't matter which).

### Expected behavior
All tracks in the playlist play until you reach the end of the playlist.

### Actual behavior
Playback stops as soon as you reach the end of the current track. Only once you bring the Youtube tab into the foreground does the player load the next video and start playback again.

With the Fennec codebase (Firefox 68) things are working fine.

I experimentally tried raising `dom.media.silence_duration_for_audibility` to 10 seconds, which seems to have helped somewhat, but not enough:
Firefox now successfully switches tracks, but playback then hangs a few seconds (around 15 seconds I think) into the start of the new track. When I switch to the Youtube tab, it is displaying as all-white. By fiddling around with it or (more reliably) pushing the playback control in the notification drawer I can usually get it going again.

Plus at least once the track switch process didn't work even with this increased value for `dom.media.silence_duration_for_audibility`, i.e. playback simply stopped at the end of one track as it used to with the original value of 2 seconds.

### Device information
Moto G4 Play
* Android device: 6.0.1
* Fenix version: 201006 17:38 (Build 2015768137)

**Comment by buttercookie42** [comment]
Regarding `dom.media.silence_duration_for_audibility`, it seems that the tracks in that particular playlist I linked to above mostly have slightly _more_ than two seconds worth of silence at the end, which explains why setting a longer value helps somewhat.

**Comment by buttercookie42** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1670066 for the default value of `dom.media.silence_duration_for_audibility` and https://bugzilla.mozilla.org/show_bug.cgi?id=1670069 for the other problem.

**Comment by Mathnerd314** [comment]
Tested in Nightly and it seems to be fixed, the playlist worked fine.
