### ISSUE TITLE
FNX-5111 ⁃ Add tabs to an existing group

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1575]
As a user, I want to add tabs to an existing group so that I can collect and organize information around a topic I’m currently interested in.

### Acceptance Criteria (Added by PM)
* if people have a saved tab group, they can choose to add selected tabs to an existing group or create a new one
* if they choose an existing one, the selected tabs are saved and they see a confirmation snackbar
* if they create a new one, they can select a name, save the group and see a confirmation snackbar

**Comment by sblatz** [comment]
The visuals for this are done, but we are now [blocked on a-c](https://github.com/mozilla-mobile/android-components/issues/2883) in order to access a collection object.

**Comment by sblatz** [comment]
Blocking bug is fixed by https://github.com/mozilla-mobile/fenix/pull/2830

**Comment by sv-ohorvath** [comment]
All blocking issues are fixed. Closing.
