### ISSUE TITLE
[Grid View] Add a divider between the tab item's title and thumbnail in grid view

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15758]
There is a small divider between title bar and thumbnail, it’s 1dp and has light_grey_30 (#E0E0E6) – same in dark mode

https://www.figma.com/file/luMaQYjwiMtQM5xQ30P9yP/Tabs?node-id=0%3A1

**Comment by axeltrinidade** [comment]
I think the tab title should also change to a dark/light background when on respective theme.
