### ISSUE TITLE
Intermittent UI test failure - MediaNotificationTest.videoPlaybackSystemNotificationTest

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#15754]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4983241498387819676
### Stacktrace:
 - See the results at the link for the tests:
   - `audioPlaybackSystemNotificationTest`
   - `mediaSystemNotificationInPrivateModeTest`
   - `tabMediaControlButtonTest`
### Build: 
 - AC upgrade and prior: https://github.com/mozilla-mobile/fenix/pull/15734

**All media tests are now re-enabled, except the `videoPlaybackSystemNotificationTest ` which is still waiting for https://github.com/mozilla-mobile/android-components/issues/9748

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7947)

**Comment by jonalmeida** [comment]
Copied over from: https://github.com/mozilla-mobile/fenix/pull/15734#issuecomment-705164263

---

There are a few tests that are failing, so I ended up testing with `tabMediaControlButtonTest` from the following list:
- `audioPlaybackSystemNotificationTest` - apparent intermittent; consistent failing now
- `mediaSystemNotificationInPrivateModeTest` - hard to reproduce; need older API level device that I do not have.
- `tabMediaControlButtonTest` - should be consistent.

I tried a bunch of GV builds to see what the media failure is but I've come across some confusing results. Using the latest AC (`3e68528074`) with these GV Nightly versions tested:
- `83.0.20201005093214` - ❌ (monday's GV after media regression was fixed)
- `83.0.20201001094020` - ❌ (GV media breakage)
- `83.0.20200930092918` - ❌ (before GV media breakage; expected to fail)
- `83.0.20200929094055` - ❌ (second before media breakage; expected to fail)

GV media regression was fixed (feature was disabled) in 20201001094020 so the `83.0.20201005093214` _should_ have worked.
  - https://hg.mozilla.org/mozilla-central/rev/e4e35e1aae77

**Comment by jonalmeida** [comment]
Adding `videoPlaybackSystemNotificationTest` to the list of ignored tests which seem to fail (intermittently though).

**Comment by jonalmeida** [comment]
To expand on comment 2, I was able to see `audioPlaybackSystemNotificationTest` _consistently_ although it was called out as [an intermittent failure](https://github.com/mozilla-mobile/fenix/issues/14593).

You can read more about that test analysis here: https://github.com/mozilla-mobile/fenix/pull/15734#issuecomment-705099077

---

For `mediaSystemNotificationInPrivateModeTest` it seems like it asserts on the Android OS system media notification which was hard for me to trust with my Android 11 device that has a new UI design for the system notifications - for that reason I didn't look further into why that test was failing.

---

For `tabMediaControlButtonTest`, previously we saw this test legitimately fail and [catch a regression](https://bugzilla.mozilla.org/show_bug.cgi?id=1668112). Visually, this test was seen trying to press the play button and that would fail.

With the regression fixed, we were able to land a fixed GV version. Now however, we are seeing the same test fail, but visually watching the test run, we can see the media content play, but the assertion always fails.

**Comment by sv-ohorvath** [comment]
Tried to fix the tests but found there is an open bug blocking media notifications for some videos: https://github.com/mozilla-mobile/fenix/issues/5290. We need to wait for that to be fixed.

**Comment by sv-ohorvath** [comment]
All media tests are now re-enabled, except the `videoPlaybackSystemNotificationTest ` which is still waiting for https://github.com/mozilla-mobile/android-components/issues/9748

**Comment by AndiAJ** [comment]
Flaky 1x on Master 6/25: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8040279606226510903/executions/bs.dbe2140dd77f0356/testcases/1/errors)

**Comment by AndiAJ** [comment]
`audioPlaybackSystemNotificationTest` Flaky 1x on Master 7/7: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6650106906194796486/executions/bs.dee2fd7f8b31f34f/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Lets keep it.

**Comment by sv-ohorvath** [comment]
We could try creating a different video test page, hosted on our github testapp to avoid https://github.com/mozilla-mobile/android-components/issues/9748

**Comment by sv-ohorvath** [comment]
After a bit more investigation I've found that videos muted or without sound don't show a notification, I left a new comment on https://github.com/mozilla-mobile/android-components/issues/9748.
The video asset used in this test didn't have sound so I replaced it with a new file which now looks like it could fix the problem, but while running on Firebase I hit the same ANR reported here: https://github.com/mozilla-mobile/fenix/issues/24047 so I'll leave it disabled until we find a fix for that.

**Comment by sv-ohorvath** [comment]
The tests were re-enabled in https://github.com/mozilla-mobile/fenix/pull/27060
