### ISSUE TITLE
[Grid View] Implement the tab play/mute button design for the grid view

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15756]
We need to align the tab's play/mute button with the grid view design. https://www.figma.com/file/luMaQYjwiMtQM5xQ30P9yP/Tabs?node-id=2%3A0

<img width="476" alt="Screen Shot 2020-10-07 at 4 19 11 PM" src="https://user-images.githubusercontent.com/1190888/95383289-f1488b00-08b8-11eb-913d-ac9110168935.png">

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 201102 (Build #2015773227).

### Devices used:
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus 6T (Android 9)
