### ISSUE TITLE
[bug] Lock Bug

### ISSUE THREAD

**Issue by cyrex2** [mozilla-mobile/fenix#15755]
![Screenshot_20201007-224251600](https://user-images.githubusercontent.com/57827385/95382922-0cd08780-08f3-11eb-9bab-1e96293c0023.jpg)

Browser is locked when make search

Browser: Firefox Nightly

**Comment by sflorean** [comment]
@cyrex2 Thanks for filing this issue! Can you please share STR about how you encounter it? the page that you were browsing, device, or other settings related.

**Comment by sflorean** [comment]
Closing this issue as no other additional information have been shared.
