### ISSUE TITLE
Update clarity of closed tabs setting summary in Tabs Customization

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15764]
Now that we're adding additional Tab Settings (Grid View, Tab order), this is more confusing.

We currently provide a summary (See "After one week" under "Tabs" in the screenshot) of the Closed Tabs Setting under the Tabs setting options. We should investigate whether or not this provides a nice affordance for finding the Closed Tabs settings.

<img width="441" alt="Screen Shot 2020-10-07 at 4 47 48 PM" src="https://user-images.githubusercontent.com/1190888/95386178-e68ff500-08bc-11eb-8d12-6c6561586a0d.png">

**Comment by liuche** [comment]
Hey @topotropic looks like this is in your area, do you have thoughts on this issue? Going through backlog grooming.

**Comment by topotropic** [comment]
I'd like to get @betsymi feedback on that one. Thanks!

**Comment by betsymi** [comment]
Is the concern that Manually/After one day/After one week/After one month text underneath Tabs on the Settings screen isn't as clear as it could be? I wouldn't be opposed to adding one word here for clarity. 

Close manually
Close after one day
Close after one week
Close after one month

**Comment by topotropic** [comment]
Sorry, I should have added some context for you @betsymi ... so it used to be just auto-close in settings > tabs but it will grow in the future and we'll have other options there as well (similar to how settings > search looks) and Gabe's request was to add it to the overview page as a reminder for people. And I wasn't sure if we want to pull out one status message if there are multiple settings behind "tabs". Thanks!

**Comment by betsymi** [comment]
Ah, I see. As it grows, would the proposal then be to 1) Remove the helper text entirely or 2) Select the most important setting to surface?

**Comment by vesta0** [comment]
I vote for the most important setting to surface, for example based on how final an action is (e.g. clearing tabs)

**Comment by betsymi** [comment]
I'm good with that. Can we update the strings to improve the clarity a bit?

**Comment by gabrielluong** [comment]
@betsymi curious what the strings improvement should be?

**Comment by betsymi** [comment]
> @betsymi curious what the strings improvement should be?

Add the verb "Close" before each option. 

Close manually
Close after one day
Close after one week
Close after one month

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201110`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201110-093133](https://user-images.githubusercontent.com/51314259/98644508-3db03c00-2339-11eb-89a2-5d446ed8e1c8.gif)
