### ISSUE TITLE
FNX-5112 ⁃ Rename saved tab groups

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1576]
As a user, I want to rename my tab groups so that I can find what I’m looking for quicker.

###Acceptance criteria

* Tab group menu has entry “Rename Group”
* People can rename their group, save it and see a snackbar confirmation

**Comment by sblatz** [comment]
The visuals for this are done, but we are now [blocked on a-c](https://github.com/mozilla-mobile/android-components/issues/2883) in order to access a collection object.

**Comment by sblatz** [comment]
Am I able to get a UX mock of how this should work?

https://mozilla.invisionapp.com/d/main#/console/16853870/359019534/preview does not outline how this should function.

@topotropic

**Comment by topotropic** [comment]
https://mozilla.invisionapp.com/share/8WS29H0KUMF#/363830894_Rename_Collection

**Comment by sv-ohorvath** [comment]
Verified on the 5/22 build.
devices: Galaxy Note 8 (Android 9), P9 Lite (Android 6.0)
