### ISSUE TITLE
[Grid View] Enable the grid view and remove its feature flag

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15761]
When grid view is ready to ship beyond Nightly or Beta, we should enable the grid view by remove all its feature flag code. That way we can remove all the code handling hiding/showing the grid view option in the tabs setting.

**Comment by softvision-miralobontiu** [comment]
The grid view is not yet available in the secret settings menu, or in the Tabs page. I've tested both in 83.0.0-beta.4 build, and in 83.1.0-rc.2 build:

![secret](https://user-images.githubusercontent.com/40694158/99548580-78614680-29c1-11eb-8a3c-f5e63b6aa093.png)

In the 11/18 Nightly build, the grid view menu/options are available without enabling the secret settings.
I'll remove the qa:needed label for now.

**Comment by softvision-miralobontiu** [comment]
Verified that the grid view option is now available in the latest Beta 84.0.0-beta.1 build, without having to enable the secret settings.
