### ISSUE TITLE
Crash in [@ libc.so@0x56b34] (BlackBerry BBF100)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15765]
Seen on https://www.reddit.com/r/firefox/comments/j6pkjg/mobile_crashing/

>My Firefox (81.1) keeps crashing when I do anything inside it. It will sit open fine, but if I even select the search bar (or even get to typing) it crashes. I have no idea what's going on.

Crash report: https://crash-stats.mozilla.org/report/index/33fe563a-24b5-4b90-88ef-9f80f0201007

Reason: ```SIGSEGV /SEGV_ACCERR```

Top 1 frames of crashing thread:
```
0 libc.so libc.so@0x56b34 
```

34 crashes in the last week over 20 installs.

**Comment by kbrosnan** [comment]
Crash in C libraries are fairly opaque. Small chance a [logcat](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information) would provide more info.
