### ISSUE TITLE
[Grid View] Determine the order of the tabs in the grid view

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15760]
The order of the tabs in the grid view is reversed right now. It’s newest to oldest in list view and we should mirror that in grid view.

**Comment by liuche** [comment]
@topotropic @vesta0 I remember that you two were talking about this, did we reach a conclusion on whether we want
a) newest on top (like listviwe)
b) oldest on top (currently in the app)

**Comment by eliserichards** [comment]
Does this investigation include synced tabs? https://github.com/mozilla-mobile/fenix/issues/15805

**Comment by vesta0** [comment]
@topotropic has been investigating this along with the UX team and I believe has recommendations.

**Comment by topotropic** [comment]
I'll close this, we keep the order that's already in grid view, see comment here https://github.com/mozilla-mobile/fenix/issues/11376#issuecomment-709505058
