### ISSUE TITLE
Locales missing from Nightly

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#15763]
(Follow-up to #15731)

We've added both Tagalog ("tl") and Santali ("sat-Olck") locales to Pontoon, but I don't see them appear in Nightly - so localizers can't test them yet (and Santali could be shipping by now).

I do see both locales have been added to the l10n.toml locales lists - both in the mozilla-l10n repo and back into the Fenix + A-C ones. 

Any idea what's going on? Is there something I/we need to do to avoid this in the future?

**Comment by Delphine** [comment]
Update: I still don't see these locales as of today in Nightly. I received more requests to add new locales in the meantime, but want to make sure this is resolved in case it adds more confusion down the road

**Comment by mcarare** [comment]
@Delphine I do not see any `strings.xml `file for Tagalog. Has it been imported?
Fo the Santali language, I'm afraid the code used is not the **ISO 639** code, the correct one would have been "sat". That should be used in `l10n.toml`and for the import of `strings.xml` file.

**Comment by Delphine** [comment]
@pocmo: You mentioned in #15502 that you might be able to create a specific folder for Santali if the locale code didn't work out. Is there any workaround for this (see comment above)?
My concern is the localizer has already worked against sat-Olck (and has finished localizing Fenix entirely), and I'd have to recreate another locale code in Pontoon for him to work against practically from scratch.

**Comment by Delphine** [comment]
@mcarare: Tagalog is at 1% completion with Fenix strings on Pontoon: https://pontoon.mozilla.org/tl/android-l10n/tags/

and I see it both in the Fenix and a-c l10n.toml files ("tl" locale), so I don't understand why it wouldn't show up on Nightly builds. Maybe the mobile team needs to import the strings back - or a step was omitted at one point?

**Comment by mcarare** [comment]
@Delphine There is no translation file in Fenix for Tagalog. It cannot show up in the app without one.

**Comment by Delphine** [comment]
Ok this seems to be because the strings localized are part of a-c, and not Fenix. So that's why nothing shows up... 🙄 Closing for now, will check back once localizers have got to the Fenix strings. Sorry for the confusion
