### ISSUE TITLE
[@ java.lang.RuntimeException: at org.mozilla.gecko.process.ServiceAllocator$DefaultContentPolicy.allocate(ServiceAllocator.java)]

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#15767]
here's the soccorro
https://crash-stats.mozilla.org/report/index/0bc7512e-7688-4305-829b-41a290201007
can someone help?

**Comment by kbrosnan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1651440 says that this is invalid `about:config` settings. Have you changed any of those?

**Comment by ale82to** [comment]
thank you very much for replying, yes I changes lots of about:config settings any hints about the wrong? ones

**Comment by kbrosnan** [comment]
enabling multiprocess and site isolation are common problem prefs
