### ISSUE TITLE
[Bug] Firefox breaks functions of SwiftKey keyboard

### ISSUE THREAD

**Issue by PisauraXTX** [mozilla-mobile/fenix#15766]
## Steps to reproduce
Install Microsoft Swiftkey keyboard on your Android device. Use it to enter text into a field on any website in Firefox. Make use of the predictive text and key swiping functions. 
### Expected behavior
Swiftkey works just like in every other application: Enter words by swiping across the keyboard, picking from the predictive text suggestions or by typing manually. Spaces and dots will be set automatically. 
### Actual behavior
Swiftkey will sometimes stop setting spaces between words automatically. Both predictive text and key swiping functions will only make edits to the previous word instead of entering a new one. 
Returning to the home screen and then opening Firefox again will fix this issue temporarily, until it turns up again at random. 

### Device information

* Android device: Fairphone 3 with /e/ OS (Android 9)
* Fenix version: 81.1.2 (The bug has first been encountered after the upgrade to version 80.0) 

Please note that this bug only turns up in Firefox 80 and up. I have tested the same keyboard on several different browsers and other applications on the same device, and never encountered it in any other app.

**Comment by ale82to** [comment]
glad you reported this bug I ve noticed too!

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1669895
