### ISSUE TITLE
Let us Search for bookmarks and history

### ISSUE THREAD

**Issue by Oymate** [mozilla-mobile/fenix#15774]
### What is the user problem or growth opportunity you want to see solved?
We can quickly search for a bookmark or history or even downloads.

### How do you know that this problem exists today? Why is this important?
It is very hard to find specific item even in properly structured bookmark directories.

### Who will benefit from it?
Everyone using bookmark, history and downloads.

**Comment by s-ankur** [comment]
Duplicate of #15094, #10046. For now we can search directly from the addressbar, it will show suggestions from history, bookmarks but not downloads i guess

**Comment by kbrosnan** [comment]
Closing as a duplicate
