### ISSUE TITLE
[Bug] Native Crashes while browsing

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15778]
## Steps to reproduce
Start browsing a heavy website, like reddit or twitter
Scroll down for a while
### Expected behavior
No crash
### Actual behavior
I have noticed a few crashes like these in the past few weeks, but not before that. I will attach logs the next time I get a crash
### Device information

* Android device: Resmi Note 4
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Found it!
https://crash-stats.mozilla.org/report/index/bp-5cf9c1c0-4995-4f54-a7f9-9c3310201008

**Comment by s-ankur** [comment]
Found the STR also! 

Got to pocket.com
Scroll downwards, slowly
Then scroll sideways
Sometimes this will also be triggered on scrolling diagonally

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1670116

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by s-ankur** [comment]
Correction, the website was https://getpocket.com/explore?src=ff_android&cdn=0.
