### ISSUE TITLE
[Bug] Error page is not dark when RFP is enabled

### ISSUE THREAD

**Issue by linsui** [mozilla-mobile/fenix#15785]
## Steps to reproduce
Enable RFP and open an error page.
### Expected behavior
It should be dark in dark mode.
### Actual behavior
It's white.
### Device information

* Android device: ?
* Fenix version: Nightly 201008 05:03 (Build #2015768427)
AC: 62.0.20201006190820, ab29a90c8
GV: 83.0a1-20201006041051
AS: 63.0.0

**Comment by liuche** [comment]
What is RFP?

**Comment by linsui** [comment]
privacy.resistFingerprinting

**Comment by kbrosnan** [comment]
Resist fingerprinting sets the CSS property prefers-color-scheme to light. As such this is invalid.

**Comment by linsui** [comment]
On desktop there is no such issue. Can fenix do the same thing? about:config also respect the dark theme.
