### ISSUE TITLE
[Bug] tap-to-zoom is harder to activate

### ISSUE THREAD

**Issue by lilydjwg** [mozilla-mobile/fenix#15780]
## Steps to reproduce

Load a webpage that shows text in small font. Try to zoom in with one hand with the phone.

By "tap-to-zoom", I mean this operation:

* Touch the screen, then leave it, and then touch again at the same place. Do this quickly.
* Move up and down to see the content zooming in and out. Leave the screen to stop and keep the current view.

### Expected behavior

Tap-to-zoom should work as easily as old Firefox for Android (or other Android apps that support this operation, e.g. Maps). I shouldn't need to try several times to zoom the page in and out.

### Actual behavior

I only succeed to activate it very occasionally. This means that the feature is there, but for some reason is harder to activate.

### Device information

* Android device: Sony Xperia XZ2 Compact 
* Fenix version:
** Nightly: I don't know which is the version, perhaps `Monday 10/5`?
** Beta: 82.0.0-beta.2

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672526

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by staktrace** [comment]
@lilydjwg can you provide specific URLs on which you have seen this problem? The feature does still exist and should still work. Works fine for me, so having specific URLs on which try and reproduce would be helpful.

**Comment by lilydjwg** [comment]
It happens with any web page, e.g. this issue page (try zoom in). I can only succeed about once out of four tries. But I can succeed almost every time with old Firefox.

**Comment by lilydjwg** [comment]
Btw, I see this issue moved to bmo. Is there any instruction about where to submit fenix issues so that it doesn't need to move?

**Comment by staktrace** [comment]
On this page I'm able to zoom in fine. I'm on a Xperia XZ1C, so very similar to your device. Do you have any modified prefs under the apz.* or ui.touch.* pref branches?

In general it's probably better to file Fenix issues here and let the triagers move it to BMO if needed.

**Comment by staktrace** [comment]
@lilydjwg ^

**Comment by lilydjwg** [comment]
I didn't change those prefs and I tested with fenix in a clean work profile.

I suddenly wasn't able to always reproduce it and I thought it might be related to the posture I had, e.g. I had a different posture while testing.

I did some screen recordings and the distance or time between two taps don't seem to matter, but there may be a small movement in the first tap, i.e. I tried to tap but actually the device senses my finger touch at one place but leaves at a nearby position. I didn't have time to do another recording to verify this, however.

**Comment by lilydjwg** [comment]
I tried multiple times in different situations, but I couldn't reproduce this reliably. I assume whatever caused the issue is gone now.

**Comment by staktrace** [comment]
Ok, thanks. It seems plausible that the movement on the first tap was causing the gesture to fail. If you still feel it happens too often we can probably increase the threshold on that movement so it allows the finger to move a bit more and still recognizes the gesture.
