### ISSUE TITLE
[Bug]"Image Search Options" isn't displayed in the Add-ons subsection from the ⋮ Main menu and can't reverse search any image

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#15784]
## Steps to reproduce
1. Install the "Image Search Options" Add-on
2. Open a website 
3. Tap the ⋮ Main menu and open the "Add-ons" subsection
4. Try to reverse search any image

### Expected behavior
Step 3 - The Add-on should be displayed in the Add-ons subsection
Step 4 - Should be able to use it in order to perform reverse image searches

### Actual behavior
Step 3 - The Add-on isn't displayed in the Add-ons subsection
Step 4 - Can't perform in any way reverse image searches

### Device information

* Android device: all
* Fenix version: Nightly 201008

### Notes
❌ Checked on Fennec as well and it [doesn't seem to be supported on Android devices](https://addons.mozilla.org/en-US/android/)

**Comment by kewisch** [comment]
The add-on is indeed not marked compatible with Android on AMO, I'm getting in touch with the author.

**Comment by Poopooracoocoo** [comment]
Update: Image Search Options was removed from the collection
