### ISSUE TITLE
FNX-5114 ⁃ Delete saved tab groups

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1578]
As a user, I want to delete my tab groups because I don’t need them any longer.

### Acceptance Criteria (Added by PM)
* tab group menu has entry “Delete Group”
* group is deleted and a snackbar with undo actions is displayed

**Comment by sblatz** [comment]
The visuals for this are done, but we are now [blocked on a-c](https://github.com/mozilla-mobile/android-components/issues/2883) in order to access a collection object.

**Comment by sv-ohorvath** [comment]
> * tab group menu has entry “Delete Group”
> * group is deleted and a snackbar with undo actions is displayed

@sblatz Delete collection works, but there is no UNDO snackbar.

**Comment by sblatz** [comment]
Is the undo snackbar expected behavior? I don't remember this being in the mocks.

@topotropic can you confirm?

**Comment by topotropic** [comment]
@sblatz makes sense to stay consistent here and display an UNDO snackbar to help people reverse this action just in case

**Comment by sv-ohorvath** [comment]
Verified as fixed along with the implementation change on with #2784.
