### ISSUE TITLE
[Bug] Android 11 recent apps show two Fenix entries

### ISSUE THREAD

**Issue by jcosentino** [mozilla-mobile/fenix#15795]
When you swipe up to the recent apps list, Fenix shows two entries. This can be problematic when trying to swipe between the browser and another app.

OS: Android 11
Android device: Google Pixel 3
Fenix version: 81.1.4 build 2015768387

Screenshot:
https://i.imgur.com/3U61JdQ.png

**Comment by Poopooracoocoo** [comment]
This sounds a bit like #13270 and was apparently fixed in version 82 which is currently in beta

fenix is pretty disappointing, eh john.

**Comment by jcosentino** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/13270

**Comment by Poopooracoocoo** [comment]
and dude your quote game is on point. you're a really cool guy
