### ISSUE TITLE
[Grid View] Grid View tabs width changes when synced tabs tray is enabled

### ISSUE THREAD

**Issue by HeiWiper** [mozilla-mobile/fenix#15799]
## Steps to reproduce
1- Enable tabs Grid View
2- Enable Synced tabs in the tab tray
4- Open few tabs
5- Click on the tab trays button
6- Click and hold on a tab
7- Click the cross button to cancel selecting tabs

### Expected behavior
- Tabs don't change dimensioni

### Actual behavior
- Tabs width changes to fit tabs tray width

### Device information

* Android device: Yes version 10 Custom ROM
* Fenix version: Nightly 201008 17:08 (Build #2015768523)

**Comment by karan-kamat** [comment]
Can confirm
Also seems to break the synced tabs part for me
The first device name seems to be misplaced

![nightly-grid-break](https://user-images.githubusercontent.com/59926956/95580936-c8a9c800-0a55-11eb-8772-542b2b337d4e.gif)

**Comment by gabrielluong** [comment]
Thank you for finding the issue!

**Comment by eliserichards** [comment]
Figma mocks: https://www.figma.com/file/luMaQYjwiMtQM5xQ30P9yP/Tabs?node-id=0%3A1

**Comment by eliserichards** [comment]
This should wait until the synced tabs UI is finished
