### ISSUE TITLE
Show selected language in "Follow device language" summary

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#15796]
### What is the user problem or growth opportunity you want to see solved?
I'd expect English (United Kingdom) (which is my language, but ofc isn't everyone's) to be the summary of the Follow device language setting

**Comment by joc-a** [comment]
I'd like to pick this up.

**Comment by joc-a** [comment]
#15838

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201019`** build using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
