### ISSUE TITLE
[Bug] Synced tabs device name should come above the tab list

### ISSUE THREAD

**Issue by axeltrinidade** [mozilla-mobile/fenix#15798]
### What is the user problem or growth opportunity you want to see solved?
In previous Synced Tabs list, the device name came above the list, making it easier to identify the source of these tabs. 

### How do you know that this problem exists today? Why is this important?
In the present version of nightly wherein synced tabs appear in the tab tray, the device name appears at the bottom. 
It gives the impression that the tab list belongs to an incorrect device. 

### Who will benefit from it?
Anyone actively using synced tabs

Old view
![Screenshot_20201009-113938](https://user-images.githubusercontent.com/68217806/95556929-1d811a80-0a25-11eb-8aed-962a091f48c5.jpg)

Nightly view
![Screenshot_20201009-103431](https://user-images.githubusercontent.com/68217806/95557032-46091480-0a25-11eb-9f04-3099518eac81.jpg)

**Comment by Croman12** [comment]
The device name still appears on top of the list on my phone (version 201008 17:08). I do however have a problem with the new order of the list. It seems synced tabs appear on top of the list, and the active tabs on device itself are located at the bottom, unless I'm missing an option to switch that back.

**Comment by eliserichards** [comment]
@Croman12 there is ongoing discussion about the order in #14117

**Comment by Poopooracoocoo** [comment]
@eliserichards I'm not sure if you misunderstood this issue. I couldn't find anything about this issue in that discussion.

**Comment by jonalmeida** [comment]
I'm going to close this as a 'won't fix - invalid' because we're moving Synced Tabs to a separate tray item in #14117 and this experimental UI will be removed.
