### ISSUE TITLE
[Telemetry] Collections CFR on homescreen

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#15790]
Add telemetry for[ Collections CFR](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/layout/no_collections_message.xml) (with call-to-action button) on the homescreen. This was reported by Marissa.

<img width="325" src="https://user-images.githubusercontent.com/43795363/95507415-fe2bb400-0976-11eb-935f-abb7611ac355.png">

----
## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] ~DS sign off on instrumentation methodology addressing product questions.~
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by gabrielluong** [comment]
This seems like something we would want to do.
