### ISSUE TITLE
[Bug] Can't login pinterest by using google account

### ISSUE THREAD

**Issue by mini536** [mozilla-mobile/fenix#15808]
## Steps to reproduce
1.Login by using google account
2.redirected to google account
3.choose your account
4.back to pinterest
5.can't login
6.refresh the tab,all the pinterest web became blank
### Expected behavior
Login pinterest successfully by using google account

### Actual behavior
Can't login
### Device information

* Android device: 11
* Fenix version: 81

**Comment by liuche** [comment]
Tracking protection leads to blocking of some trackers, so I'm going to dupe this to #15722 so we can track the work in the same place.
