### ISSUE TITLE
[Bug] YouTube stops working and displays the message " Invalid response received"

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#15802]
## Steps to reproduce
Must have account in youtube.com
1. Open the app
2. Go to youtube.com and log in to your account
3. Tap your account icon
4. Scoll down and tap Desktop
5. Tap back button
### Expected behavior
The previous page will be displayed
### Actual behavior
The message "Invalid response received" is displayed on the screen, YouTube has stopped responding to actions, continuing to display this message
### Device information
Asus Zenfone 3
* Android device: 8.0
* Fenix version: 82.0
[20201009_120209.zip](https://github.com/mozilla-mobile/fenix/files/5353746/20201009_120209.zip)

**Comment by sflorean** [comment]
@BigSamSampson thank you for your report! I wasn't able to reproduce this issue on latest Nightly build (3/29) following your steps with LG G7 Fit (Android 8.1). 
Is this issue still reproducible for you?
