### ISSUE TITLE
[Bug]Synced tabs on top of Open tabs in Tab tray

### ISSUE THREAD

**Issue by karan-kamat** [mozilla-mobile/fenix#15805]
## Steps to reproduce

1. Open Latest Fenix Nightly
2. Go to setttings
3.Click on About Firefox Nightly
4. Click on Firefox logo 5 times
5.Go back and click on Secret Settings
6. Enable Show Synced Tabs in the tab tray
7. Go outside settings and open tab tray

### Expected behavior

 See Open tabs and scroll down to see Synced Tabs

### Actual behavior

See synced Tabs and scroll down to see Open Tabs

### Device information

* Android device: Xiaomi Redmi Note 5 Pro 
with Android 9 and MIUI 11.0.5.0

* Fenix version: Nightly 201008 17:08 (Build 2015768523)
![nightly-top](https://user-images.githubusercontent.com/59926956/95579477-56d07f00-0a53-11eb-867b-d0282f335adc.gif)

**Comment by cadeyrn** [comment]
Synced tabs will be moved to a different place in #14117.
