### ISSUE TITLE
Tajik Language Name in Native Language (Тоҷикӣ)

### ISSUE THREAD

**Issue by Ibragimov** [mozilla-mobile/fenix#15814]
Hi,

Could you please, update the language name from “Tg” to “Тоҷикӣ” in the list of languages for the latest version.
Please, see the attached screenshot for reference.

![Screenshot_20201008-110714](https://user-images.githubusercontent.com/1321588/95615034-fc4e1780-0a80-11eb-9040-a49797f0d556.jpg)

Maybe this issue depends on device/carrier. Maybe Tajik isn't supported natively on all Android phones.
However, could you please, re-check and make the Tajik language name be shown as "Тоҷикӣ" instead of "Tg".

Thank you for prompt reply,
Victor Ibragimov

**Comment by eliserichards** [comment]
We may need a custom display name for Tajik. See Focus's impl: https://github.com/boek/focus-android/blob/ba0f3231add6529585dea4ac9b7aed943069fc01/app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java#L45

**Comment by liuche** [comment]
This would be a dupe of #12528, i'll copy the comment over. It's in our eng backlog, but we haven't got to it.
