### ISSUE TITLE
[Bug] Listening to youtube in the background goes white

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#15826]
## Steps to reproduce
Enable 'video background play fix' extension.
View a long video for example https://m.youtube.com/watch?v=5gnlhmaM-dM
Lock the screen and continue listening.
After some time unlock the screen. 5 or 10 min should be fine.
### Expected behavior
I can see the web page
![Screenshot_20201010-163803_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95656416-015da600-0b17-11eb-9424-28ed9a628438.png)

### Actual behavior
everything is white
![Screenshot_20201010-161618_Firefox_Nightly](https://user-images.githubusercontent.com/922368/95656423-07538700-0b17-11eb-9738-8789232b3c80.png)

### Device information

* Android device: one plus 5t
* Fenix version: nightly

**Comment by andreicristianpetcu** [comment]
This is a regression. Works fine in beta.

**Comment by JoGarWeb** [comment]
I have the same problem... It's annoying!

**Comment by andreicristianpetcu** [comment]
Here is a logcat if it helps https://my.owndrive.com/index.php/s/w2NcqJJpRfkMB7G

**Comment by liuche** [comment]
cc @csadilek (or is it enough to put the WebExt label?)

**Comment by csadilek** [comment]
Talked to @agi and moving this to Bugzilla.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672782

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by andreicristianpetcu** [comment]
this stopped reproducing
