### ISSUE TITLE
[Bug] do not keep sync tabs suggestion in tab screen

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#15821]
## Steps to reproduce
Nightly:
Open tabs.
Sync tabs suggestion appears at top of tab lists.
Not using it 
Use browser 
Open tabs 
Again sync tabs suggestion at top of tab lists.
Repeat from use browser.

### Expected behavior 
No persistant promotion of features.
Only promote sync option once 
Provide option to disable promoting option or feature.

### Actual behavior 
Forced promotion in a place where it is obstructing normal use of functionality of using tabs, tab list viewing.

### Device informatio
* Fenix version: nightly fri oct 9

**Comment by liuche** [comment]
Can you add a screenshot? I don't see this.

**Comment by softvision-miralobontiu** [comment]
@clientenq I was not able to reproduce this issue on the 1/13 Nightly build with Google Pixel (Android 10).
Could you, please retest it?
Thank you!

**Comment by jonalmeida** [comment]
Closing this since there was no response. It sounds like a duplicate of https://github.com/mozilla-mobile/fenix/issues/15848.
