### ISSUE TITLE
[Bug] media playback denial of service in browser

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#15827]
## Steps to reproduce
Start media stream via tab. Fi listening podcast.
Switch to other tab 
Media stream is cut off by / denial of existing playback by new tab

### Expected behavior 
Existing stream and play should continue 
New possible media source or tab does not interrupt existing play by other tab.

### Actual behavior 
New tabs can influence behaviour of other tab (not acceptable unless)

Existing user requested playback/stream functionality is ignored by browser.

Browser does not provide options to really care about user preferences to multitask and listen to existing stream or playback or prefer overriding existing request by opening new/other tab.

### Device information

* Fenix version: latest daily and nightly

**Comment by s-ankur** [comment]
Does the video background play fix addon help?

**Comment by liuche** [comment]
I really can't repro this, while going to mynoise.net or a cheese podcast https://www.collectivecreamery.com/podcast
