### ISSUE TITLE
Improvements to one-handed UX when the address bar is at the bottom

### ISSUE THREAD

**Issue by eddlang** [mozilla-mobile/fenix#15822]
### What is the user problem or growth opportunity you want to see solved?

One-handed UX when the address bar is at the bottom

### How do you know that this problem exists today? Why is this important?

I use it and encounter it every day. It's important for one-handed users.

### Who will benefit from it?

All those who put the address bar at the bottom.

![Fenix1 - Copy](https://user-images.githubusercontent.com/13473205/95655097-cf961080-0b11-11eb-9d71-1caf777593cc.png)
![Fenix2 - Copy](https://user-images.githubusercontent.com/13473205/95655091-cd33b680-0b11-11eb-9acd-e1334c26c6a2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8052)

**Comment by cadeyrn** [comment]
This should be part of #12065.

**Comment by anotherus3r** [comment]
I like the idea of better one-handed use, but I'm not sure about the mock-ups. The way top sites start on the right side is less convenient for left-handed people so that may need to be switchable to either side, based on user preference.

**Comment by eddlang** [comment]
> 
> 
> The way top sites start on the right side is less convenient for left-handed people so that may need to be switchable to either side, based on user preference. The top of the page also seems too empty.

True about left-handed people. A switch would be nice, although top-sites should still populate from bottom-to-top when the bar is set to the bottom. The difference would be between right-to-left and left-to-right.

As for top of the page, it'd fill up as more top sites are added.

**Comment by maverick74** [comment]
I would just change one thing: when collections are revealed, I would keep the PRIVATE button and the COLLECTIONS button on the bottom.

Only the collections list would expand to the top. The buttons would be fixed where they were before collections got revealed

**Comment by Cheap-Skate** [comment]
I find it hard to reach Top Sites one-handed now I have a tall phone screen. And I have REALLY big hands. It was easier when the Firefox logo was larger.

I would like easier one hand access to Top Sites, eg
- move Top Sites lower down the screen
Or
- be able to drag down to bring Top Sites lower if I want to
Or...
- (something else)

I like the idea of Top Sites at the bottom.

**Comment by Dev-i-l** [comment]
i suggest a hand button in toolbar, upon clicking it, it will bring down half the screen, like kiwi browser, see issue #16156 for detailed explanation

**Comment by boek** [comment]
The home page has changes quite a bit since this issue was first created. There are also a few other issues open around customizing the home screen. I'm not going to migrate this issue to Bugzilla but if there is a feature that isn't covered by the other requests please create a new enhancement request in Bugzilla :)
