### ISSUE TITLE
Don’t return SERP URLs as history results

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1582]
## Steps to reproduce
* Perform a number of searches and navigate to the SERPs (search engine result pages)
* Open a new tab and type any single character

### Expected behavior
* I should see history suggestions of sites I’ve visited before filtered by freecency and matches in the Title and URL.

As a user, I don’t consider SERPs to be “sites I’ve visited before.” The generic, google.com or duckduckgo.com is a site I’ve been to before but https://google.com/search?q=black%20hole%20picture&ie=utf8&oe=utf-8&client=firefox-b-m is not. 

### Actual behavior
* I see many history results that are SERPs and are not related to my current task and make it difficult to parse the list of suggestions.

### Device information
* Android device: ?
* Fenix version: 1.0.1915 Build #11011208

**Comment by yoasif** [comment]
FWIW, this is not how Fennec or Firefox desktop acts - I see SERPs in both awesomebar results in those apps.

**Comment by Verdi** [comment]
> FWIW, this is not how Fennec or Firefox desktop acts - I see SERPs in both awesomebar results in those apps.

That's true but we'd like them to not show SERP URLs. So starting here with Fenix.

**Comment by yoasif** [comment]
Is this meant to be compatible across all search engines? I just typed in a query into my awesomebar on desktop where I got results from both Startpage and Google (I use various search engines). 

I'm not averse to the idea in principle, but if certain search engine SERPs are suppressed, but others are not, it feels less consistent and will cause users to question the browser's behavior as it feels like there is "magic" going on that is hard for users to fit into a mental model of how it works.

**Comment by vesta0** [comment]
This needs to go through triage

**Comment by liuche** [comment]
Deprioritizing this - we'll definitely need UX feedback here on:
- Since it's infeasible to apply this to all search engines (because Fenix would need to know the search engine urls to strip out the SERPS), should we only apply this to the bundled search engines? Should we include custom search engines that users include, with the chance that they could be wrong?
- If we're starting this on Fenix, is that something that Desktop UX is committed to following? We'd like to have parity, so if this ends up being Fenix-only, it's probably going to be deprioritized.
- Are there other user experience specs that need to be filled out?

**Comment by brampitoyo** [comment]
Paging @Verdi for further feedback to @liuche’s comment above.

**Comment by Verdi** [comment]
>Since it's infeasible to apply this to all search engines (because Fenix would need to know the search engine urls to strip out the SERPS), should we only apply this to the bundled search engines? 

Yes. This would be a big improvement and cover most cases.

>Should we include custom search engines that users include, with the chance that they could be wrong?
> 
I don't think this is necessary to begin with.

>If we're starting this on Fenix, is that something that Desktop UX is committed to following? We'd like to have parity, so if this ends up being Fenix-only, it's probably going to be deprioritized.
> 
We are definitely going to address this on desktop. We may not do exactly the same thing (we might though!) but we should not block on having the same solution at the same time.

>Are there other user experience specs that need to be filled out?
I don't think so.
