### ISSUE TITLE
Be able to quickly share URL with 3 most recently shared apps

### ISSUE THREAD

**Issue by baincd** [mozilla-mobile/fenix#15829]
### What is the user problem or growth opportunity you want to see solved?
I typically share from the browser with multiple other apps.  This means the app I want to share with may not be the most recent, but may be the 2nd or 3rd most recently shared-with app. I'd like to be able to share with the 3 most recently shared apps quickly (an not have to go through the app-popup to find which app to share with)

### How do you know that this problem exists today? Why is this important?
The previous version of Firefox on Android showed multiple (2 or 3) recently shared apps, prominently on the menu.  This was a huge advantage to my workflow in Firefox over other browsers, as all it took was 2 taps (tap menu, tap the icon of the app I want to share with).  Going through the app list popup to find the app I want to share with for these frequently shared-with apps is annoying.

### Who will benefit from it?
Anyone who frequently shares URLs with more than 1 app

**Comment by s-ankur** [comment]
I can alread share with 6 recently used apps 
![Screenshot_2020-10-10-23-06-18-937_org mozilla fenix](https://user-images.githubusercontent.com/33252312/95661472-43094380-0b4d-11eb-876c-8bc7c3adff21.jpg)

**Comment by baincd** [comment]
Yes, but that requires 3 taps (menu → share-icon → recently-shared-app-icon)

I was looking to make that faster (menu → recently-shared-app-icon)
![20201010_170817](https://user-images.githubusercontent.com/5075659/95665249-9747ff80-0b1c-11eb-8872-f50d33aefc17.jpg)

**Comment by Poopooracoocoo** [comment]
#9309

**Comment by liuche** [comment]
Duping to #14926 where we'll address improvements to sharing.
