### ISSUE TITLE
[Bug] All sorts of display issues

### ISSUE THREAD

**Issue by quadriflax** [mozilla-mobile/fenix#15823]
## Steps to reproduce

Loading pages. Lots of pages. Reddit is a prime example. Everything gets distorted. Colors get weird, text gets janky.

### Expected behavior

Page should load and display as intended.

### Actual behavior

All sorts of visual elements are broken. Zooming or scrolling sometimes fixes, sometimes breaks it.

### Device information

* Android device: Samsung Tab A 2019; Android 10
* Fenix version: 
Nightly 201009 17:03 (Build #2015768713)
AC: 63.0.20201009143108, eece20266
GV: 83.0a1-20201008094950
AS: 63.0.0

See screenshot for example. This has been happening for a few nightly versions at least, though I'm not totally sure exactly when it started. Makes browsing almost impossible. Screenshot is from Slickdeals.net.

![Screenshot_20201010-083633_Firefox Nightly](https://user-images.githubusercontent.com/46144580/95655368-c6d31980-0ad4-11eb-9fc9-edf37f1b94db.jpg)

**Comment by quadriflax** [comment]
82.0.0-beta.4 (Build #2015768089)
AC: 60.0.3, 0a93a5ecd
GV: 82.0-20201002191150
AS: 63.0.0

I can't seem to replicate with the above beta version.

Latest nightly below has the problem, though. It might be related to desktop modes of websites (ie, mobile sites seem to be okay).

Nightly 201010 17:00 (Build #2015768905)
AC: 63.0.20201009143108, eece20266
GV: 83.0a1-20201008094950
AS: 63.0.0

Is there anything else I can provide to help?

![Screenshot_20201011-075136_Firefox Nightly](https://user-images.githubusercontent.com/46144580/95677865-a5d2fd00-0b96-11eb-8fa3-69ff19805f41.jpg)

**Comment by liuche** [comment]
Is this from the desktop mode? I'm not able to see these problems with a fresh 10/21 nightly - I can see the item tiles and everything seems normal.

**Comment by quadriflax** [comment]
> Is this from the desktop mode? I'm not able to see these problems with a fresh 10/21 nightly - I can see the item tiles and everything seems normal.

It does seem to happen when I'm on desktop versions of pages, but I'm not specifically toggling desktop mode. It never seemed to happen on my Moto G, and the past few nightlies haven't had the issue as frequently or severely, but sometimes it does glitch out. The most common glitch is when characters just disappear so it looks like random letters all over the place. If I tap out and come back to it, everything is fine. Nothing seems consistent about the behavior that I can see. Best bet is maybe it has something to do with the larger screen, since it never seemed to be an issue on my phone? Not sure what else to try to troubleshoot, but at least it has gotten better.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672628

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Thanks for the bug report @quadriflax! I believe this is caused by a driver bug on Mali-G71 GPUs, which explains why it happens on your tablet but not your Moto G (which has an Adreno GPU).

There are a couple things you could do to help me track this down! First, can you go to about:support page in firefox nightly on your tablet. Click on "copy text to clipboard", then attach that information to this bug.

Next, could you please go to about:config, search for gfx.webrender.debug.gpu-cache and set it to true. This should make a grey rectangle with red lines in it appear on your screen.

If you're then able to capture a video of the bug occurring that would be super helpful! If you're not able to record a video, then watch the grey rectangle with the red lines closely. As you browse around typically new red lines will appear and old ones will disappear. If the grey rectangle gets filled up with red lines, then the rectangle itself should increase in size to make more room. My theory is that this happens at the exact time that all the letters on your page go wonky. Can you see whether that is the case?

Thanks a lot!

PS, after you've done those steps, you can change gfx.webrender.force-disabled to true in about:config, and that should avoid this bug.

**Comment by quadriflax** [comment]
Here is about:support copy/paste

Name | Firefox Nightly
-- | --
84.0a1
20201106093443
 
Mozilla/5.0 (Android 10; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0
Linux 29 #1 SMP PREEMPT Mon Aug 31 12:02:34 KST 2020
0/0
0/0               Disabled by default
1
Found
Found
Found
false

I actually haven't seen it glitch out in some time now, so this may have been fixed. If it starts happening again, I'll follow up with the debug and a video if I can catch it.

**Comment by jamienicol** [comment]
Hi @quadriflax , thanks very much for getting back to me. Unfortunately that doesn't look like the full about:support page. Could you try using the copy raw data to clipboard button and see if that contains more information?

**Comment by quadriflax** [comment]
{
  "application": {
    "name": "Firefox Nightly",
    "osVersion": "Linux 29 #1 SMP PREEMPT Mon Aug 31 12:02:34 KST 2020",
    "version": "84.0a1",
    "buildID": "20201106093443",
    "distributionID": "",
    "userAgent": "Mozilla/5.0 (Android 10; Mobile; rv:84.0) Gecko/84.0 Firefox/84.0",
    "safeMode": false,
    "supportURL": "https://support.mozilla.org/1/mobile/84.0a1/Android/en-US/",
    "numTotalWindows": 0,
    "numFissionWindows": 0,
    "numRemoteWindows": 0,
    "fissionAutoStart": false,
    "fissionDecisionStatus": "disabledByDefault",
    "remoteAutoStart": true,
    "keyLocationServiceGoogleFound": true,
    "keySafebrowsingGoogleFound": true,
    "keyMozillaFound": true
  },
  "securitySoftware": {
    "registeredAntiVirus": "",
    "registeredAntiSpyware": "",
    "registeredFirewall": ""
  },
  "processes": {
    "remoteTypes": {
      "web": 1
    },
    "maxWebContentProcesses": 1
  },
  "environmentVariables": {},
  "modifiedPreferences": {
    "browser.cache.disk.amount_written": 495179,
    "browser.cache.disk.capacity": 524288,
    "browser.cache.disk.filesystem_reported": 1,
    "dom.presentation.device.name": "SM-T510",
    "dom.w3c_pointer_events.enabled": true,
    "extensions.lastAppVersion": "84.0a1",
    "general.useragent.updates.lastupdated": "1576227697487",
    "idle.lastDailyNotification": 1604851930,
    "media.gmp.storage.version.observed": 1,
    "network.dns.disablePrefetch": true,
    "network.http.speculative-parallel-limit": 0,
    "network.predictor.cleaned-up": true,
    "network.predictor.enabled": false,
    "network.prefetch-next": false,
    "network.trr.blocklist_cleanup_done": true,
    "privacy.purge_trackers.date_in_cookie_database": "0",
    "privacy.purge_trackers.last_purge": "1604851934574",
    "privacy.userContext.enabled": true,
    "privacy.userContext.extension": "@contain-facebook",
    "privacy.userContext.ui.enabled": true,
    "privacy.usercontext.about_newtab_segregation.enabled": true,
    "security.remote_settings.crlite_filters.checked": 1603860677,
    "security.remote_settings.intermediates.checked": 1603860677,
    "storage.vacuum.last.index": 0
  },
  "lockedPreferences": {
    "fission.autostart.session": false
  },
  "printingPreferences": {},
  "media": {
    "currentAudioBackend": "opensl",
    "currentMaxAudioChannels": 2,
    "currentPreferredSampleRate": 48000,
    "audioOutputDevices": [
      {
        "name": "",
        "groupId": "",
        "vendor": "",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 44100,
        "minRate": 44100,
        "maxLatency": 441,
        "minLatency": 128
      }
    ],
    "audioInputDevices": [
      {
        "name": "",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 1,
        "defaultRate": 44100,
        "maxRate": 44100,
        "minRate": 44100,
        "maxLatency": 441,
        "minLatency": 128
      }
    ]
  },
  "accessibility": {
    "isActive": true,
    "forceDisabled": 0,
    "handlerUsed": false,
    "instantiator": ""
  },
  "startupCache": {
    "DiskCachePath": "/data/user/0/org.mozilla.fenix/files/mozilla/gomjcjhx.default/startupCache/startupCache.4.little",
    "IgnoreDiskCache": false,
    "FoundDiskCacheOnInit": true,
    "WroteToDiskCache": false
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.29",
      "version": "4.29"
    },
    "NSS": {
      "minVersion": "3.59 Beta",
      "version": "3.59 Beta"
    },
    "NSSUTIL": {
      "minVersion": "3.59 Beta",
      "version": "3.59 Beta"
    },
    "NSSSSL": {
      "minVersion": "3.59 Beta",
      "version": "3.59 Beta"
    },
    "NSSSMIME": {
      "minVersion": "3.59 Beta",
      "version": "3.59 Beta"
    }
  },
  "userJS": {
    "exists": false
  },
  "intl": {
    "localeService": {
      "requested": [
        "en-US"
      ],
      "available": [
        "an",
        "ar",
        "ast",
        "az",
        "be",
        "bg",
        "bn",
        "br",
        "bs",
        "ca",
        "cak",
        "cs",
        "cy",
        "da",
        "de",
        "dsb",
        "el",
        "en-CA",
        "en-GB",
        "en-US",
        "eo",
        "es-AR",
        "es-CL",
        "es-ES",
        "es-MX",
        "et",
        "eu",
        "fa",
        "ff",
        "fi",
        "fr",
        "fy-NL",
        "ga-IE",
        "gd",
        "gl",
        "gn",
        "gu-IN",
        "he",
        "hi-IN",
        "hr",
        "hsb",
        "hu",
        "hy-AM",
        "id",
        "is",
        "it",
        "ja",
        "ka",
        "kab",
        "kk",
        "kn",
        "ko",
        "lij",
        "lo",
        "lt",
        "lv",
        "ml",
        "mr",
        "ms",
        "my",
        "nb-NO",
        "ne-NP",
        "nl",
        "nn-NO",
        "oc",
        "pa-IN",
        "pl",
        "pt-BR",
        "pt-PT",
        "rm",
        "ro",
        "ru",
        "sk",
        "sl",
        "son",
        "sq",
        "sr",
        "sv-SE",
        "ta",
        "te",
        "th",
        "tr",
        "trs",
        "uk",
        "ur",
        "uz",
        "vi",
        "wo",
        "xh",
        "zam",
        "zh-CN",
        "zh-TW"
      ],
      "supported": [
        "en-US",
        "en-CA",
        "en-GB"
      ],
      "regionalPrefs": [
        "en-US"
      ],
      "defaultLocale": "en-US"
    },
    "osPrefs": {
      "systemLocales": [
        "en-US"
      ],
      "regionalPrefsLocales": [
        "en-US"
      ]
    }
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "WebRender",
    "windowLayerManagerRemote": true,
    "windowUsingAdvancedLayers": false,
    "adapterDescription": "Model: SM-T510, Product: gta3xlwifixx, Manufacturer: samsung, Hardware: exynos7904, OpenGL: ARM -- Mali-G71 -- OpenGL ES 3.2 v1.r19p0-01rel0.###other-sha0123456789ABCDEF0###",
    "adapterVendorID": "ARM",
    "adapterDeviceID": "Mali-G71",
    "adapterRAM": 0,
    "adapterDrivers": "",
    "driverVendor": "",
    "driverVersion": "OpenGL ES 3.2 v1.r19p0-01rel0.###other-sha0123456789ABCDEF0###",
    "driverDate": "",
    "usesTiling": true,
    "contentUsesTiling": true,
    "offMainThreadPaintEnabled": false,
    "offMainThreadPaintWorkerCount": 0,
    "targetFrameRate": 60,
    "webgl1Renderer": "ARM -- Mali-G71",
    "webgl1Version": "OpenGL ES 3.2 v1.r19p0-01rel0.###other-sha0123456789ABCDEF0###",
    "webgl1DriverExtensions": "GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array ",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_float_blend EXT_sRGB MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context",
    "webgl1WSIInfo": "EGL_VENDOR: Android\nEGL_VERSION: 1.4 Android META-EGL\nEGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_IMG_context_priority EGL_KHR_no_config_context \nIsWebglOutOfProcessEnabled: 0",
    "webgl2Renderer": "ARM -- Mali-G71",
    "webgl2Version": "OpenGL ES 3.2 v1.r19p0-01rel0.###other-sha0123456789ABCDEF0###",
    "webgl2DriverExtensions": "GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array ",
    "webgl2Extensions": "EXT_color_buffer_float EXT_float_blend MOZ_debug OVR_multiview2 WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context",
    "webgl2WSIInfo": "EGL_VENDOR: Android\nEGL_VERSION: 1.4 Android META-EGL\nEGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_IMG_context_priority EGL_KHR_no_config_context \nIsWebglOutOfProcessEnabled: 0",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "ApzTouchInput": 1,
      "ApzAutoscrollInput": 1,
      "ApzZoomingInput": 1,
      "TileHeight": 512,
      "TileWidth": 512,
      "CMSOutputProfile": "Empty profile data",
      "DisplayCount": 1,
      "Display0": "1920x1200"
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "force_enabled",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "force_enabled",
              "message": "Force-enabled by pref"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "force_enabled",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "force_enabled",
              "message": "Force-enabled by pref"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_QUALIFIED",
          "description": "WebRender qualified",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_COMPOSITOR",
          "description": "WebRender native compositor",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        },
        {
          "name": "WEBRENDER_PARTIAL",
          "description": "WebRender partial present",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_ANGLE",
          "description": "WebRender ANGLE",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "env",
              "status": "unavailable",
              "message": "OS not supported"
            }
          ]
        },
        {
          "name": "WEBRENDER_DCOMP_PRESENT",
          "description": "WebRender DirectComposition",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "disabled",
              "message": "User disabled via pref"
            },
            {
              "type": "env",
              "status": "unavailable",
              "message": "Requires Windows 10 or later"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Requires ANGLE"
            }
          ]
        },
        {
          "name": "OMTP",
          "description": "Off Main Thread Painting",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        },
        {
          "name": "WEBGPU",
          "description": "WebGPU",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "addons": [
    {
      "name": "Amazon SMILE!",
      "type": "extension",
      "version": "1.4.5",
      "isActive": true,
      "id": "{1417a6e0-be73-4358-912c-5dce719b5791}"
    },
    {
      "name": "Facebook Container",
      "type": "extension",
      "version": "2.1.2",
      "isActive": true,
      "id": "@contain-facebook"
    },
    {
      "name": "HTTPS Everywhere",
      "type": "extension",
      "version": "2020.8.13",
      "isActive": true,
      "id": "https-everywhere@eff.org"
    },
    {
      "name": "Mozilla Android Components - Ads",
      "type": "extension",
      "version": "66.0.20201106143126.1108170629",
      "isActive": true,
      "id": "ads@mozac.org"
    },
    {
      "name": "Mozilla Android Components - Browser Icons",
      "type": "extension",
      "version": "66.0.20201106143126.1106144347",
      "isActive": true,
      "id": "icons@mozac.org"
    },
    {
      "name": "Mozilla Android Components - Cookies",
      "type": "extension",
      "version": "66.0.20201106143126.1108170629",
      "isActive": true,
      "id": "cookies@mozac.org"
    },
    {
      "name": "Mozilla Android Components - Firefox Accounts WebChannel",
      "type": "extension",
      "version": "66.0.20201106143126.1106144503",
      "isActive": true,
      "id": "fxa@mozac.org"
    },
    {
      "name": "Mozilla Android Components - ReaderView",
      "type": "extension",
      "version": "66.0.20201106143126.1106144309",
      "isActive": true,
      "id": "readerview@mozac.org"
    },
    {
      "name": "Mozilla Android Components - Web Compatibility Interventions",
      "type": "extension",
      "version": "16.0.0",
      "isActive": true,
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "Mozilla Android Components - WebCompat Reporter",
      "type": "extension",
      "version": "2.0.0",
      "isActive": true,
      "id": "webcompat-reporter@mozilla.org"
    },
    {
      "name": "NoScript",
      "type": "extension",
      "version": "11.1.5",
      "isActive": true,
      "id": "{73a6fe31-595d-460b-a920-fcc0f8843232}"
    },
    {
      "name": "Privacy Badger",
      "type": "extension",
      "version": "2020.10.7",
      "isActive": true,
      "id": "jid1-MnnxcxisBPnSXQ@jetpack"
    },
    {
      "name": "Reddit Enhancement Suite",
      "type": "extension",
      "version": "5.20.9",
      "isActive": true,
      "id": "jid1-xUfzOsOFlzSOXg@jetpack"
    },
    {
      "name": "uBlock Origin",
      "type": "extension",
      "version": "1.30.6",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    }
  ],
  "features": []
}

**Comment by jamienicol** [comment]
Thanks for the info! That's great to hear you don't actually experience this any more. Given the dates, I think it was probably the same bug as https://bugzilla.mozilla.org/show_bug.cgi?id=1669960, which is fixed. Please let me know if it does come up again though!

**Comment by quadriflax** [comment]
Agreed that it appears to be the same bug that was fixed. I'll keep an eye on it and report back if it happens again.
