### ISSUE TITLE
[Bug] suggested logins shown even when ive opted out of autofill

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15832]
## Steps to reproduce
Save multiple logins for a website
Disable autofill
Open the website

### Expected behavior
I don't get the saved logins prompt. In my case since I use password wallets, I don't find firefox autofill to be useful and the suggested logins prompt is also a source of mild annoyance
### Actual behavior
Suggested logins is shown
### Device information

* Android device: Redmi Note 4
* Fenix version: Nightly

**Comment by cadeyrn** [comment]
Duplicate of #14686 and moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1663039, fixed in GV 83.

**Comment by s-ankur** [comment]
Ohhh I didn't search the closed ones
