### ISSUE TITLE
[Bug] files failed to be downloaded

### ISSUE THREAD

**Issue by DorHadar** [mozilla-mobile/fenix#15835]
Hi

You have a long time bug in the function of download files through the browser in android..

9% of files failed to be downloaded...

Best Regards,
Dor, Israel

Details about version:

81.1.4 (Build #2015768387)
AC: 57.0.7, 68343a885
GV: 81.0.1-20200930150533
AS: 61.0.13

**Comment by anotherus3r** [comment]
Might be useful to give the devs a few example links to files that failed to download.

**Comment by LaurentiuApahideanSV** [comment]
Thank you for the report, however the issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/15378. I will close this issue as it will be handled there.
