### ISSUE TITLE
[Bug] reader mode tabs restored from collections cannot go back to normal mode

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15833]
## Steps to reproduce
Open reader mode in a tab
Save to collection
Restore the tab from the collection
Click on the reader mode icon

### Expected behavior
It takes you back to normal mode
### Actual behavior
It stays in reader mode
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by anotherus3r** [comment]
Hm, worked fine for me on [this link](https://www.bug.hr/sigurnost/appleov-sigurni-cip-t2-ima-propust-koji-omogucava-jailbreak-macova-16893) on Android 10, Nightly  201010 17:00 (Build #2015768907).

**Comment by LaurentiuApahideanSV** [comment]
I was able to reproduce the issue on an older version of Firefox Preview Nightly (201009) but not on the latest 201011 (Build #2015769099). The issue was probably fixed alongside https://github.com/mozilla-mobile/fenix/issues/15470. I will close this issue.
