### ISSUE TITLE
[Bug] Failed to switch the User-Agent string with User-Agent Switcher and Manager 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#15837]
## Steps to reproduce
1. Open https://webbrowsertools.com/useragent/
2. Install [User-Agent Switcher and Manager](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/)
3. Open the extension from the three-dot menu
4. Select a selective UA and press Apply button
5. Refresh the web page
### Expected behavior
The webpage should show what user-agent string I set
### Actual behavior
Whatever I set in the extension the webpage shows only following string:
`Mozilla/5.0 (Android 7.0; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0`
### Device information

* Android device: Galaxy S6
* Fenix version: Nightly 201010 17:00

**Comment by JoGarWeb** [comment]
It's a bug of Addon, this works fine on Android [User-Agent Switcher](https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/)
