### ISSUE TITLE
[Bug] clicking back on sentry Socorro links opened from about:crashes closes the browser

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15830]
## Steps to reproduce
Open about crashes from settings /about firefox
Click on back button
### Expected behavior
Take you back to setting or maybe to the home screen
### Actual behavior
Close the app
### Device information

* Android device: Redmi note 4
* Fenix version: nightly

**Comment by liuche** [comment]
We could consider something like opening about:crashes in a custom tab, or adding new tab to that stack. Essentially it's opening a new tab with about:crashes, so going back closes the browser since you've hit the "end" of your history stack (which is a bigger question about New Tab).
