### ISSUE TITLE
FNX-5117 ⁃ Don’t show internal urls in history results

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1583]
## Steps to reproduce
* Visit the Fenix about page
* Type “x” into the search field

### Expected behavior
* I should not see history results related to the letter “x”

### Actual behavior
* I see a history suggestion for data:text/html;base64,PCFkb2N0eXbllGh...

Additionally, I don’t think this page should show up in results even if we fixed it’s display by using it’s title. From a user’s point of view it’s part of the program, not a website.

### Device information
* Android device: ?
* Fenix version: 1.0.1915 Build #11011208

**Comment by kbrosnan** [comment]
This is an artifact of having visited the old fenix version page. The page no longer is loaded as a tab. https://github.com/mozilla-mobile/fenix/commit/379875a62a12c504ae0f48a5a6638e6e46f9d582

**Comment by mheubusch** [comment]
@kbrosnan is it ok to close this issue, then?

**Comment by kbrosnan** [comment]
I think so @boek reopen if I am wrong.

**Comment by boek** [comment]
@kbrosnan should we also filter out about:* pages from geckoview?

**Comment by Verdi** [comment]
> @kbrosnan should we also filter out about:* pages from geckoview?
Yes if that means they won't show in search results.

**Comment by kbrosnan** [comment]
Requesting that in a new issue seems good. This one has become messy.
