### ISSUE TITLE
[Bug][Synced tabs] Wrong display of the "Sign in to sync" card in tabs tray after canceling the collection creation

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#15848]
## Prerequisites
Make sure you are not signed in with your FxA account.

## Steps to reproduce
1. Enable the Secret settings (Menu -> Settings -> About Firefox -> tap 5 times the Firefox logo).
2. Enable the grid tab view (Settings -> Tabs).
3. Open a few tabs. Tap on the counter tab.
4. Long tap on one of the available tans in order to activate the collection creation page.
5. Cancel collection creation.
6. Observe the "Sign in to sync" card.

### Expected behavior
The "Sign in to sync" card is displayed under the "Save to collection" button.

### Actual behavior
The "Sign in to sync"/ "Please re-authenticate" card is displayed as one of the tabs - the first tab. Opening a tab and tapping the counter tab, resolves the issue.

### Device information
* Android device: HTC 10 (Android 8), Samsung Galaxy Note 8 (Android 9)
* Fenix version: 10/12 Nightly

<img src="https://user-images.githubusercontent.com/40694158/95744172-9d181f00-0c9b-11eb-8d95-645e480b3ddc.jpg" width="300" height="550" />

<img src="https://user-images.githubusercontent.com/40694158/95744057-722dcb00-0c9b-11eb-8773-d716b5e27b28.gif" width="300" height="550" />

**Comment by softvision-miralobontiu** [comment]
On the 11/24 Nightly build, and on Beta 84.0.0-beta.2, the "Sign in to sync" and the "Please re-authenticate" cards aren't displayed at all.

**Comment by jonalmeida** [comment]
Closing as no longer an issue with synced tabs in as a separate tray.
