### ISSUE TITLE
[Bug] Synced tabs in tabs tray doesn't display the moz-extensions tabs opened

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#15849]
## Prerequisites
Sign in with valid credentials on two mobile devices.

## Steps to reproduce
1. Enable the Secret settings (Menu -> Settings -> About Firefox -> tap 5 times the Firefox logo) on both devices.
2. Enable the grid tab view (Settings -> Tabs) - on both devices.
3. Install at least 1 add-on on each device - do not close the moz-extension page opened automatically after installing the add-on (i.e. install AdGuard and moz-extension://4d15cc63-a26e-4a36-a893-1666a4eeec04/pages/options.html will be opened in a new tab)
4. Open different tabs on both devices. Tap on the counter tab.
5. Observe, on both devices, if the opened tabs are synced and displayed correctly.

OR

1. Install at least 1 add-on on each device - do not close the moz-extension page opened automatically after installing the add-on (i.e. install AdGuard and moz-extension://4d15cc63-a26e-4a36-a893-1666a4eeec04/pages/options.html will be opened in a new tab)
2. Open different tabs on both devices. 
3. Go to settings - Synced tabs.
4. Observe, on both devices, if the opened tabs are synced and displayed correctly.

### Expected behavior
All the opened tabs are displayed according to the devices they are opened in.

### Actual behavior
The moz-extension pages are not displayed in the synced tabs section.

### Device information
* Android device: HTC 10 (Android 8), Samsung Galaxy Note 8 (Android 9)
* Fenix version: 10/12 Nightly

![synced](https://user-images.githubusercontent.com/40694158/95754336-8974b480-0cab-11eb-8b31-e42f30ba0df6.png)

**Comment by kbrosnan** [comment]
I think this is expected behavior @grigoryk?

**Comment by grigoryk** [comment]
Thanks for filing, @softvision-miralobontiu.

This is the desired behaviour. We won't be able to meaningfully display moz-extension:// urls that are opened on other devices - UUIDs will be unique for each device (and on the device, for each add-on installation as well - e.g. reinstalling the addon changes the UUID).

Perhaps if/once we get addons sync, we can think about changing this. For now, I'll close the issue.
