### ISSUE TITLE
[Bug] Text duplication in address bar with autocomplete enabled

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#15841]
## Steps to reproduce
- Have autocomplete urls enabled
- Type in the beginning of a url, make sure it gives an autocompleted suggestion
- Press backspace twice

### Expected behavior
Text is deleted normally

### Actual behavior
Some of the autocompleted url is added at the end of what you typed
![output_0](https://user-images.githubusercontent.com/66154603/95689380-a5774800-0c10-11eb-8316-acc0b85d7cd5.gif)

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 201010 17:00 (Build #2015768907)
AC: 63.0.20201009143108, eece20266
GV: 83.0a1-20201008094950
AS: 63.0.0

**Comment by s-ankur** [comment]
Related #3475

**Comment by mobd** [comment]
Thanks, closing this as a dupe
