### ISSUE TITLE
[Bug] text duplication on colab.research.google.com/

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15855]
## Steps to reproduce
Go to colab.research.google.com/
Start typing in to the code box 
Click on backspace
### Expected behavior
Deleted the letter
### Actual behavior
It starts to duplicate the letters
### Device information

* Android device: Redmi Note 4
* Fenix version: Nightly

**Comment by makotokato** [comment]
@s-ankur 
What (software) keyboard do you use?

**Comment by s-ankur** [comment]
GBoard, it is now happening on other websites as well

**Comment by makotokato** [comment]
Thanks, I can reproduce this on Firefox 81 and Nightly. Composition string isn't reset, so inputted string is duplicated. I am looking...

**Comment by makotokato** [comment]
> GBoard, it is now happening on other websites as well

If this occurs on other web site, it is https://bugzilla.mozilla.org/show_bug.cgi?id=1672095

**Comment by andreicristianpetcu** [comment]
I saw this issue on reddit and on github

**Comment by s-ankur** [comment]
GV bug is closed now, will this be qa verified seperately?

**Comment by makotokato** [comment]
> GV bug is closed now, will this be qa verified seperately?

I don't think that original issue (colab.research.google.com) is fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1672095 because this occurs even if 81. https://bugzilla.mozilla.org/show_bug.cgi?id=1672095 is regression from 83.

**Comment by makotokato** [comment]
Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1673396.  This is compatibility issue with Monaco editor.

**Comment by kbrosnan** [comment]
Closing as a Geckoview bug.
