### ISSUE TITLE
Fix blank title bar issue on Chromebook devices for improved user experience 

### ISSUE THREAD

**Issue by RadBrad87** [mozilla-mobile/fenix#15856]
### What is the user problem or growth opportunity you want to see solved?
Improved user experience on Chromebooks by improving title bar rendering options

### How do you know that this problem exists today? Why is this important?
For Linux apps running in the Crostoni container, ChromeOS renders the title bars of non-GTK apps. The title bar rendered by ChromeOS is a thick white bar that does not even contain the title. In short it is ugly (doesn't match rest of the Firefox GUI), takes screen real estate, and annoyingly bright at night.  It very clearly makes Firefox seem like a second class browser when used on a Chromebook. Other apps like VSCode are able to work around this with a "Title bar style" setting that can be either "Native" or "Custom".

### Who will benefit from it?
All Chromebook users will have Firefox as a second fully polished desktop class web browser. 
![Screenshot 2020-10-12 at 2 45 04 PM](https://user-images.githubusercontent.com/944410/95793041-8cff4000-0c99-11eb-9013-b194739756e8.png)

**Comment by cadeyrn** [comment]
Your screenshot shows Firefox for desktop operating systems. This issue tracker is for the Android version of Firefox.

**Comment by RadBrad87** [comment]
Will do, thank you.
