### ISSUE TITLE
In a PWA which doesn't specify nav and/or status bar colours, these should follow the browser theme, e.g, light or dark (as opposed to the current, static white colour)

### ISSUE THREAD

**Issue by astarq** [mozilla-mobile/fenix#15857]
When building a Progressive Web App, the developer of that app has to specify the colours which the browser will use for status bar and navigation bar colours on Android. When this is not done, the browser decides.

In recent Chromium-based browsers, the navbar is by default white when the browsers light theme is enabled, and dark when the dark theme is enabled, unless specified by the PWA, in which case it may be any colour. This looks normal and works well with the force-dark flag for web pages. 

In Firefox, as of version Nightly 201010 17:00, the navigation and status bar colours always stay white, regardless of the browser or OS theme. This gives the UI an unpolished feeling, especially while using the Dark Reader add-on. 

I'd like the suggest that the former approach be used in Firefox going forward.

This can be tested by installing and opening any of the following as PWA's; pinterest.com, instagram.com, news.google.com, duolingo.com/learn.
 
Example of the instagram.com PWA in Chromium (the dark mode for web pages flag is enabled here);
![Screenshot_20201012-225907_Bromite](https://user-images.githubusercontent.com/63871973/95793910-9363db00-0cde-11eb-9eff-e5290ff9d5e9.png)

Example of the instagram.com PWA in Firefox Nightly (with the dark reader add-on, as opposed to Chromium's native flag);
 ![Screenshot_20201012-225629_Firefox_Nightly](https://user-images.githubusercontent.com/63871973/95794417-c064bd80-0cdf-11eb-99d4-d03b622462ef.png)

Hope this wasn't too difficult to understand, and sorry for the long explanation, I'm just a noob so this was my best try at explaining it! 😳😳

**Comment by Poopooracoocoo** [comment]
see #8812
