### ISSUE TITLE
FNX-5118 ⁃ Share a tab group

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#1585]
As a user, I can send links to the sites I’ve collected as a group with other people or other devices so that I can share the information and resources I’ve collected with others or complete a task on another device.
###Acceptance criteria 

* I can send a group with another person via email, text, or other communication apps (assume this is a structured string)

**Comment by bifleming** [comment]
@mheubusch the team had the following feedback for this story:

_Not possible for MVP:

- I can share a group with another device sharing a Bluetooth connections
- If I am signed in to my Firefox Account, I can send the sites in a group to another device where I am signed in to my Firefox Account_

Need template for text message that would go along with share action. Would like to consider whether there is true value in this if we’re not doing the last two bullets.

**Comment by mheubusch** [comment]
I think this can use the share sheet functionality that we would use if we were sharing a single link - don't need to think of this as a new kind of content we are sharing, just however many single links/one for each open tab are in a collection for now. don't need to share metadata like the name of the collection or the fact that these links are somehow related.

**Comment by mheubusch** [comment]
Since this is no different than our current share sheet, I think it has value even without the other two items and makes sense to keep it as a feature, but am willing to deprioritize to post-MVP

**Comment by sblatz** [comment]
The visuals for this are done, but we are now [blocked on a-c](https://github.com/mozilla-mobile/android-components/issues/2883) in order to access a collection object.

**Comment by sblatz** [comment]
I'm implementing this with a newline between each url.

## Example:
https://www.google.com
https://www.mozilla.org

**Comment by sv-ohorvath** [comment]
Verified this on the 5/22 build. No issues found.
devices: Galaxy Note 8 (Android 9), P9 Lite (Android 6.0)
