### ISSUE TITLE
Random font sizes for some users with Automatic font size

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#15853]
Clearly fallout from #14923

If users who are seeing this please report

```
* Device name:
* Model:
* Android version:
* OS font size: 
* Firefox font size:
```
### Example

* Device name: Galaxy Note 9
* Model: SM-N960U1
* Android version: 10
* OS font size: Font size is set to the 3rd smallest setting out of 8. Samsung does not provide names or numbers to describe 
* Firefox font size: 100%

**Comment by gabrielluong** [comment]
Potential test sites to reproduce this from slack were Twitter and Reddit

**Comment by glandium** [comment]
* Device name: Pixel 3a
* Model: Pixel 3a (?)
* Android version: 11
* OS font size: "default" (2nd step on a slider with 4 steps for small, default, big and biggest)
* Firefox font size: 180%

Sites I visited while the size was large where it was visibly larger than usual: Google results, HN, maybe wikipedia.

**Comment by sflorean** [comment]
I am able to reproduce on Google, scribd.com with Google Pixel 4XL (Android 11)  - Nightly 10/13.

**Comment by ekager** [comment]
This will be ready to test in the next nightly

**Comment by sflorean** [comment]
@ekager this is still reproducible on Nightly 10/15 with Google Pixel 4xl (Android 11).

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/21. Devices Google Pixel 4 XL (Android 11).
