### ISSUE TITLE
Firefox freezes when location service popup appears.[Bug]

### ISSUE THREAD

**Issue by akasidney** [mozilla-mobile/fenix#15852]
When navigating to a page such as homedepot.com, location service popup appears, screen flashes multiple times, and browser freezes. Eventually returns to page but popup appears again and freezes again. Similarly when navigating to dictionary.com. Browser freezes when trying to enter a word in search box. Works in Chrome.

### Expected behavior
Should be able to Accept or Deny location service and return to page. Should be able to enter a word in search box.

### Actual behavior
Location service popup appears, screen flashes multiple times, and browser freezes. Eventually returns to page but popup appears again and freezes again. Similarly when navigating to dictionary.com. Browser freezes when trying to enter a word in search box. 

### Device information
* Android device: Revvlry Android Version 10
* Fenix version: 81

**Comment by ekager** [comment]
@akasidney can you still reproduce?

**Comment by akasidney** [comment]
Appears to be working now. Page loads a little slow but it's not freezing
anymore.

Thank you!
