### ISSUE TITLE
[Bug]The page always reload after switching tabs.

### ISSUE THREAD

**Issue by syxf** [mozilla-mobile/fenix#15862]
## Steps to reproduce
Switch tabs.

### Expected behavior
The page should stay after switching tabs.

### Actual behavior
The page always turns blank and reloads after switching tabs. This makes the browsing experience very unsothy.

### Device information

* Android device: Xiaomi Mi 8, Android 10.
* Fenix version: Nightly 201012 17:02(Build#2015769291)

**Comment by ale82to** [comment]
I ve reported this multiple time its a shame it's not been fixed yet, iceraven (fenix fork) as a fix for it hopefully.

**Comment by sflorean** [comment]
@syxf thank you for your report! This issue is already filed here #12731 and your scenario will be tested when will be fixed. Closing as duplicate.
