### ISSUE TITLE
Laggy Performance in bartamanpatrika.com

### ISSUE THREAD

**Issue by pidus** [mozilla-mobile/fenix#15864]
## Steps to reproduce
1. Go to: https://bartamanpatrika.com/
2. Zoom in/out. 
### Expected behavior
Smooth zooming operation. 
### Actual behavior
Lag. Unable to operate. 
### Device information

* Android device: Xiaomi Mi Max 2
* Fenix version: Nightly 201011 17:12 (Build #2015769099)

**Comment by mcomella** [comment]
Triage: @MarcLeclair can you try to reproduce this issue?

**Comment by pidus** [comment]
Scrolling is also laggy.

**Comment by mcomella** [comment]
Triage: @MarcLeclair can you file on BZ and get additional details, as we discussed in triage?

**Comment by MarcLeclair** [comment]
@pidus  I tried getting some more values on my g5, and I see the same behavior in Chrome. Would you mind trying it on a different browser just to confirm the behavior is confined to firefox only?

**Comment by MarcLeclair** [comment]
@pidus  I tried getting some more values on my g5, and I see the same behavior in Chrome. Would you mind trying it on a different browser just to confirm the behavior is confined to firefox only?

**Comment by mcomella** [comment]
Filed platform issue as https://bugzilla.mozilla.org/show_bug.cgi?id=1673988. Closing this issue and we'll track there.
