### ISSUE TITLE
[Bug] when toolbar is set to bottom, URL suggestions should also be at bottom

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#15863]
When the toolbar is set to bottom, suggestions should also be at the bottom instead of at the top. Look at attached screenshot to see something I experience several times a day. This needs to get fixed soon

![qc6rgp8ujcq51](https://user-images.githubusercontent.com/47801466/95808231-028b0080-0cda-11eb-8f36-981e0aa90969.png)

**Comment by AlbertoFabbri93** [comment]
Yeah, I agree, this is very confusing. I often end up looking at the search suggestions at the top without paying attention to the URL bar auto-completion.

**Comment by willfs84** [comment]
I'm not sure this is a feature request, it's more of an issue/bug. They forgot to update this for bottom toolbar :(

**Comment by willfs84** [comment]
This still repros in Nightly. Maybe this should be part of a larger bug/issue about results being inverted when the user has chosen bottom bar UI (most relevant results at the bottom of the screen, least relevant at the top of the screen). Not sure if anyone on UI/UX actually uses bottom bar UI as their "daily driver" browser...

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/14017
