### ISSUE TITLE
[Unable to open pdf file with content-type: application/octet-stream]

### ISSUE THREAD

**Issue by Zonnetj3** [mozilla-mobile/fenix#15869]
This bug is reported after posting on the support forum:
https://support.mozilla.org/nl/questions/1307518

I get the error "_could not open file_" after downloading a pdf file in Firefox for ANDROID. This happens for most, but not all, pdf files. For example this file: https://manuals.coolblue.nl/0f/aeg-l8fb86es-aeg-t8db86es.pdf
It seems Firefox does not use the default Android pdf viewer. In chrome the file opens perfectly. 
Before this error occurred the pdf file was opened in a navigation app, totally useless.
I tried many things:
 * Changing default pdf app in android
 * Removing the navigation app. 
 * Reinstalling Firefox
 * Installing Firefox nightly, 
 * Trying to Change the default pdf viewer in about:config (not possible in Firefox daylight). Unable to change this. 

The issue is related to the information of pdf : 
 * content-type: application/octet-stream

Why doesn't Firefox use the default pdf viewer of android in this case? 

Quote from Jscher 2000 in support forum: 
_"This is a generic executable file type that sites sometimes associate with PDFs to force them to be downloaded instead of opened in a tab. I think that is causing the problem that Firefox doesn't open them in an appropriate application. It would be preferable if Firefox were to "forget" that useless information and ask Android what to do with a .pdf file."_

I hope this issue can be resolved. Thanks!

**Comment by liuche** [comment]
Duping to #15119
