### ISSUE TITLE
[Bug] Google is available in the "Add search engine" list when its also available in the "Default search engine" list

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#15867]
### Precondition
Fresh install Fenix or clear data from Android app settings.

## Steps to reproduce
1. Launch Fenix and go to Settings -> Search;
2. Tap "Add search engine";
3. Observe the available search engines from the "Add search engine" list.
### Expected behavior
The available search engines from the "Add search engine" list are: Reddit and YouTube. Google is not available.
### Actual behavior
Google is available in the "Add search engine" list when its also available in the "Default search engine" list.

![20201013_124236](https://user-images.githubusercontent.com/48799384/95845146-7b2da380-0d52-11eb-9176-0c56ecaa9f09.gif)

### Device information

* Android device: Pixel 2 (Android 9), OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly 201013 05:01 (Build #2015769387), GV 83.0a1, from 10/13
Beta 82.0.0-beta.4 (Build #2015768091), GV 82.0, from 10/6
Release 81.1.4 (Build #2015768387), GV 81.0.1, from 10/8

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Release 82.1.1 GV 82 from 10/21, Beta 83.0.0-beta.1 GV 83 from 10/21 and Nightly 201026 GV 84 from 10/26 with Samsung Galaxy Tab S3 (Android 8) and Pixel 2 (Android 9).
@liuche I will remove the qa:needed label for now.

**Comment by liuche** [comment]
QA is still able to see this even after the changes in #15768 landed.

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Nightly 11/5 with Samsung Galaxy Tab S3 (Android 8).

**Comment by eliserichards** [comment]
This is on hold until Sebastian's search refactor in AC is finished

**Comment by ebalazs-sv** [comment]
This issue is not reproducible on Nightly 11/25 with Pixel 2 (Android 9).
