### ISSUE TITLE
open top sites in existing tab

### ISSUE THREAD

**Issue by 424344** [mozilla-mobile/fenix#15866]
### What is the user problem or growth opportunity you want to see solved?
Currently fenix opens top sites and bookmarks into new tabs. When I go back using Android back button the tab is not closed, so I end with lots of unused tabs, that I have to close one by one. Can you add ann option to not open links in new tabs?

### How do you know that this problem exists today? Why is this important?
It is importanti because this new behaviour make the users waste time managing all these tabs.
### Who will benefit from it?
Fenix users will benefit because the won't have to waster time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8122)

**Comment by Poopooracoocoo** [comment]
@liuche is there an issue for 
>When I go back using Android back button the tab is not closed, so I end with lots of unused tabs, that I have to close one by one

**Comment by liuche** [comment]
This one #13775 ?

**Comment by Poopooracoocoo** [comment]
Thanks. I've seen much older issues than that one.

**Comment by liuche** [comment]
If link them I'll dupe them :)

**Comment by JonDous** [comment]
Russian community supports you.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1362363

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812908

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
