### ISSUE TITLE
[Bug] Inconsistent crash when trying to load web pages with Flash

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#15873]
## Steps to reproduce
1. Launch Fenix.
2. Open all the following web pages:
* http://24hoursofhappy.com/
* http://cloudsovercuba.com/
* http://bear71.nfb.ca/#/bear71
* http://www.intel.com/museumofme/en_US/r/index.htm
* http://disneyworld.disney.go.com/new-fantasyland/
* http://vimeo.com/47875656
* http://wechoosethemoon.org/
* http://moodstream.gettyimages.com/
* http://www.mono-1.com/monoface/main.html
* http://waterlife.nfb.ca/
* https://www.agame.com/game/papas-cupcakeria
* https://bluewave.com/online-demo/index-flash.html
* http://www.stagexl.org/demos/performance_flash.html
* http://www.chinapost.com.cn/
* https://www.motherteresawomenuniv.ac.in/
* http://homestarrunner.com/
* http://techno.org/electronic-music-guide/
* http://www.zombo.com/
* https://www.y8.com/tags/flash

### Expected behavior
The websites are loaded, or an error that Flash is not supported is displayed.
### Actual behavior
Crash.
### Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 10/13** and the [Try-Build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=5fc6a578d0d89c65943a57f3fce170c093569194&selectedTaskRun=C-2NwGMzTzGuC5CdkxFx7g.0)  minimal-UI browser built with the GeckoView engine.

### Notes
The try build with the minimal-UI browser built with the GeckoView engine was created in order to test the Flash EOL(killing flash).
Here you can find the crashes: 
```
1e8cea41-1e29-4a8d-b99c-81efae2a7c13 <native crash>
71d0ee6e-c958-4089-92c3-4448378e9b44 <native crash>
```
* Socorro: https://crash-stats.mozilla.org/report/index/bp-71b11aa4-53ca-43c9-8164-875430201013
* Socorro: https://crash-stats.mozilla.org/report/index/bp-c2c4b7d0-e49b-4912-926c-f295d0201013
* Socorro: https://crash-stats.mozilla.org/report/index/bp-d3c27b8d-a993-41e4-b114-d48680201013
* Socorro: https://crash-stats.mozilla.org/report/index/bp-1c2cfc8a-3caf-4efe-91aa-9f96f0201013
* Socorro: https://crash-stats.mozilla.org/report/index/bp-91cb1e98-77fe-4bd4-b1d3-738d90201013
Also, note that for the Try-build all the web pages were lost after the crash.

For reference: 
Adobe stopped supporting Android with the old Flash Player 11.1.x branch being the last with last update back on September 10 2013.
Firefox for Android has dropped support of this old vulnerable Flash Plugin from Firefox 56.0 and later.
Even if you could get this ancient Flash 11.1.x version working may sites have long dropped support of the old 11.1 branch used by Android and BlackBerry Playbook. More and more sites are using HTML5 players for video and audio now to be more cross platform.
https://support.mozilla.org/en-US/kb/how-do-i-watch-flash-videos-firefox-androidhe last with last update back on September 10 2013.
https://support.mozilla.org/en-US/questions/1217767
So basically there shouldn't be any major issue after this change will get into Nightly.

![20201113-172218](https://user-images.githubusercontent.com/42831109/95873833-f1dd9780-0d78-11eb-9012-9418047be95d.gif)

**Comment by KrasnayaPloshchad** [comment]
> The websites are loaded, or an error that Flash is not supported is displayed.

I suggest putting a grey area at the position of Flash to notice user that Flash is not supported any more.

**Comment by KrasnayaPloshchad** [comment]
So Fenix should also ignore any attrinute for loading SWF files at the first time.

**Comment by KrasnayaPloshchad** [comment]
On [this page](https://zh.y8.com/games/hot_dog_bush) Fenix looks doesn’t load flash any more, using Nightly 201027 17:01 (Build #2015772171).
