### ISSUE TITLE
[Bug] Scroll currently viewed tab in view on tab tray (grid view)

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#15870]
## Steps to reproduce
When you have 8 or more open tabs and go back to the tab tray in grid view, the currently viewed tab is not always in view.

### Expected behavior
The tab I'm coming from is in view, similar to what happens in grid view

**Comment by mcarare** [comment]
@topotropic is this still an issue? The position calculations have changed slightly from the moment this issue was opened. 
I tried with 10 or more open tabs and it works as expected. Thank you!

**Comment by topotropic** [comment]
No, this got fixed. Thanks!
