### ISSUE TITLE
[Bug] Download failed after pausing and resuming file download

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#15872]
## Steps to reproduce
1. Launch Fenix and go to https://www.thinkbroadband.com/download;
2. Tap to download a file;
3. Expand the download notification;
4. Tap Pause;
5. Tap Resume;
6. Observe the download status;
### Expected behavior
The file is downloaded from where it was paused.
### Actual behavior
Download failed is displayed and the file is not downloaded.

![20201013_161821](https://user-images.githubusercontent.com/48799384/95865981-fc476380-0d6f-11eb-9bd9-1de9fe62702d.gif)

### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly 201013 05:01 (Build #2015769387), GV 83.0a1, from 10/13

Not reproducible on the latest Beta 82.0.0-beta.4 and Release 81.1.4 builds. This might be a regression from https://github.com/mozilla-mobile/fenix/issues/15378
cc @Amejia481

**Comment by Amejia481** [comment]
Thanks @AndiAJ yes, it looks like duplicate!
