### ISSUE TITLE
FNX-5120 ⁃ Text Reflow

### ISSUE THREAD

**Issue by magi44ken** [mozilla-mobile/fenix#1588]
### Why/User Benefit/User Problem
Usually the text are roo small to read in small screen. To read it one have to zoom in the text but it over flow the screen. One have to move left and right to read it.

### What / Requirements
When you zoom in the text to make it bigger, it should also flow the text within the screen width.

Similar to Opera (based on Chromium) has a core feature called Text Wrap that, after zooming in on a block of text, will automatically reflow the text at that size to fit the viewport. 

### Acceptance Criteria (how do I know when I’m done?)
You know when the text is zooming and the text will reflow around the screen width.

**Comment by Lululalu** [comment]
#808 may be the same

**Comment by kbrosnan** [comment]
Closing as a duplicate
