### ISSUE TITLE
Clear clipboard after copying password

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#15883]
### What is the user problem or growth opportunity you want to see solved?
Currently when credential is copied from saved login it stays in clipboard... Is it possible to enable or add one feature to clear clipboard automatically after some seconds or minutes? 

### How do you know that this problem exists today? Why is this important?
Password copied to clipboard can be read by other apps. 

### Who will benefit from it?
All users

**Comment by liuche** [comment]
I don't think there's a lot that we can do here since this is the android clipboard. Adding a setting to clear the clipboard after some number of minutes would be tricky, you could manually overwrite the clipboard yourself.
