### ISSUE TITLE
AbnormalFxaEvent$MissingExpectedAccountAfterStartup

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#15882]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9650031/?referrer=github_plugin

```
AbnormalFxaEvent$MissingExpectedAccountAfterStartup: None
    at org.mozilla.fenix.components.AccountAbnormalities.accountManagerStarted(AccountAbnormalities.kt:8)
    at org.mozilla.fenix.components.BackgroundServices$makeAccountManager$$inlined$also$lambda$2.invokeSuspend(BackgroundServices.kt:6)
...
(6 additional frame(s) were not displayed)

[INFO] null
```

**Comment by grigoryk** [comment]
The volume on nightly exploded around Sept 24, which is when https://github.com/mozilla-mobile/android-components/pull/7856 landed.
[Release](https://sentry.prod.mozaws.net/operations/firefox/issues/9258525/?query=is%3Aunresolved%20Abnormal) and [beta](https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7678027/?query=is%3Aunresolved%20AbnormalFxaEvent) volume is much lower than nightly. That's expected if this is indeed a regression that didn't make it to these channels.

Need to confirm that this code is/isn't running on beta. If it's not, that would expect lack of an uptick in volume.

**Comment by grigoryk** [comment]
As far as I can tell https://github.com/mozilla-mobile/android-components/pull/7856 landed in a-c61, and our beta is currently on 60. That explains the high nightly volume and low beta/release volume.

This also means that https://github.com/mozilla-mobile/android-components/pull/7856 introduced a significant regression.

**Comment by grigoryk** [comment]
I need to come back to this.

This isn't a crash, but a failing assertion. Basically, there’s some code in A-C which keeps track of the account state, and on startup reports any abnormalities - e.g. we had an account, but then it went away w/o an explicit user action. So, that’s what this assertion is… It's (still) not clear if this is a real problem, or a problem with the assertion logic itself.

**Comment by jonalmeida** [comment]
There was a larger up-tick in these exceptions on June 23rd.

**Comment by jonalmeida** [comment]
This error has disappeared now. 🎉 

Closing.

**Comment by grigoryk** [comment]
Unfortunately, still present.

**Comment by grigoryk** [comment]
Looks like this is a race condition: we're going through "check if there are account abnormalities" logic right after invoking `accountManager.start()`, but that call is asynchronous. So, when we're checking `accountManager.authenticatedAccount()` in `AccountAbnormalities#accountManagerStarted`, the state machine is quite likely still going through its motions and didn't resolve the true account state.
