### ISSUE TITLE
Select text from hypertext link

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1589]
### Why/User Benefit/User Problem
Currently it's very difficult to select phrases and words that are links. Being able to select this texts is helpful, because having the context menu open with the text selected, allows the user to search the term in the search engine, translate it, save it, etc. Also, no browser besides Samsung Internet allows text selection from links (that I know of), so, adding this feature to Fenix may give it some leverage over it's competitors.

### What / Requirements
When long pressing a link, the context menu shows an option to select text, among the options that are already available.

### Acceptance Criteria (how do I know when I’m done?)
It's possible to select text from links.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8150)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809955

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
