### ISSUE TITLE
Add visual separators above subheadings on all Settings screens

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#15898]
On the main Settings screen we have a horizontal line above each subheader, which separates a section from the one above it, shown here:

![settings](https://user-images.githubusercontent.com/22176302/96017035-1be19900-0e0f-11eb-871d-659966f09c1c.jpg)

To be consistent, we would like to add this separator to _all_ subheadings on _all_ Settings subpages as well. For example, the **Search** settings page should have a separator above the `Address bar` subheader, shown here:
<img width="372" alt="Settings - Search@2x" src="https://user-images.githubusercontent.com/22176302/96017277-6cf18d00-0e0f-11eb-9370-ce6e6b540650.png">

Other subpages missing separators include: **Tabs**, **Customize**, and **Add-ons**.

**Comment by mcarare** [comment]
@apbitner I do not see additional subheadings that would need a separator in the TABS screen.

Also, separator for add-ons will be added in AC.

**Comment by apbitner** [comment]
@mcarare I think it's only when you've enabled grid view in the secret settings:

![image](https://user-images.githubusercontent.com/22176302/96148216-aab4eb00-0ecd-11eb-826c-09b6712e32c8.png)

**Comment by mcarare** [comment]
As the add-ons screen will require changes in AC that will land at a later time, I will split this issue:
 - This issue is about adding separators in Tabs and Customize screen. (PR: https://github.com/mozilla-mobile/fenix/pull/15917)
 - Adding separators in subsections headers of add-ons list is this issue: https://github.com/mozilla-mobile/fenix/issues/15919.

**Comment by amkcpu** [comment]
I just wanted to add that in https://github.com/mozilla-mobile/fenix/issues/14636#issuecomment-695868874, @brampitoyo mentioned that next to the divider, the headers' _text colors_ and _spacing_ should be updated too.

This should be easily achieved by switching the header style over to `preference_cat_style` after #15377 has landed.
Currently, of course, this is not possible, but I think it would make sense to make some AC changes to make it possible to set a header style in `AddonsManagerAdapter`.
An alternative would be extending the `Style` data class to be able to set `allowDividerAbove` (the text color can already be set), but I think setting the XML layout is much preferable.

**Comment by AndiAJ** [comment]
Hi, **verified as fixe**d on the latest **`Nightly 201019`** build using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
