### ISSUE TITLE
[Bug] Can't add new custom or predefined search engines

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#15892]
## Steps to reproduce
1. Go to settings>Search.
2. Tap Add search engine
3. Select the predefined options: Youtube or Reddit.
4. Tap Add custom search engine. Add a new search engine, i.e: imdb.com/search/q=%s
### Expected behavior
A new engine is added to the default list in both cases.
### Actual behavior
The predefined options are not added to the default list but are only removed from the predefined list.
The new custom search engine is not saved.
Also, there's: https://github.com/mozilla-mobile/fenix/issues/15867

It might be needed to clear app data in some cases to reproduce this.

### Device information

* Android device: OnePlus A3 (Android 6.0.1), Nexus 5 (Android 5.1.1), Pixel 2 (Android 9)
* Not reproducible on: Pixel (Android 11), Samsung Galaxy Tab S6 (Android 10)
* Fenix version: Beta 82b5, RC 81.1.5 (also reproduced on 81.1.4)
* Not reproducing on Nightly 10/14

**Comment by gabrielluong** [comment]
cc @eliserichards @boek

**Comment by nudgegoonies** [comment]
Same here. This is horrible. The new engine, in my case Startpage, is not available for selection. But it must be stored internally. I cannot add the a search engine with the same name twice. Then it complains:
"Search engine with the name "Startpage" already exists.

**Comment by nudgegoonies** [comment]
And by the way, altough google is deleted from the active search engines it shows up in the empty tab as search engine and has to be removed manually there via long-press.

**Comment by liuche** [comment]
We may need to uplift this commit to beta: https://github.com/mozilla-mobile/fenix/commit/9845626eca88d5c59bc4832c3fd64f1dd84daf05

**Comment by sv-ohorvath** [comment]
Verified as fixed on Beta 82b6 and RC 82.1.0 with the following devices:
Pixel 2 (Android 9), Xiaomi Mi Pad 2 (Android 5.1), Nexus 5 (Android 5.1.)
