### ISSUE TITLE
Tab order is not reversed when Toolbar is on Top

### ISSUE THREAD

**Issue by nudgegoonies** [mozilla-mobile/fenix#15901]
## Steps to reproduce

Change "Toolbar" from "Bottom" to Top".
Click on Tab overview.

### Expected behavior

With "Toolbar" "Top" the latest opened Tab should be on the bottom and the oldest opened Tab on the Top. People expect this behavior because it was exactly so with Firefox Mobile 68 where the Toolbar was on Top by default.

### Actual behavior
The latest opened Tab is on Top like with "Toolbar" "Bottom".

### Device information

* Android device: Moto G3
* Fenix version: 81.1.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8166)

**Comment by Poopooracoocoo** [comment]
also see #11376 #10365

**Comment by teohhanhui** [comment]
I'd prefer the latest tabs to go on top. Why not make this customizable?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813269

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
