### ISSUE TITLE
Very slow scrolling in tab switcher when in grid view

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#15900]
## Steps to reproduce

1. Have three rows of tabs in grid view.
2. Scroll up and down page.

### Expected behavior

Smooth scrolling. 

### Actual behavior

Lots of jank. This seems a little quicker if I have two rows. 

Profile: https://share.firefox.dev/317HFHJ

### Device information

* Android device: HP Touchpad
* Fenix version: latest nightly.

**Comment by mcomella** [comment]
Triage: the profile indicates that `android.view.ThreadedRenderer.nSyncAndDrawFrame` is taking a long time (> 1s in some cases). A quick Google search indicated that some people see this when too much graphic memory is in use. MarcLeclair suggested commenting out the favicon load to test if that improves performance. Also, perhaps drawing over Gecko could create similar issues.

**Comment by mcomella** [comment]
Not sure if this is still a problem but seems not good if it is so reopening.

**Comment by mcomella** [comment]
Triage: we can't reproduce this on our low-end reference device so we suspect the device this was reproduced on is lower-end than we have the resources to support. That being said, we're refactoring the tabs tray in #21318 so please let us know if the performance gets worse. That being said, this is a good use case for us to benchmark so we added it in our list of use cases to benchmark in https://github.com/mozilla-mobile/fenix/issues/22302.
