### ISSUE TITLE
Remove the usage of the TabTrayGridItemDecorator

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15907]
Working with @Mugurell to find an alternative solution to drawing a item decorator to show the selected border in grid view.

**Comment by Mugurell** [comment]
The decorator is nice though the 2 drawbacks I see are:
- it provides a different way of indicating a tab is selected than what is used in the list based tabs tray. Would be nice to have the same approach, either decorators, either "manually" setting the "selected tab effect".
- the border is shown over other tabs when they intersect. Not sure if it can be solved by setting a higher z index on the tab that we move with the finger.
<img src="https://user-images.githubusercontent.com/11428869/96089044-f1571500-0ece-11eb-9908-65f75eab136b.gif" width="300">
