### ISSUE TITLE
[Bug] Sending multiple Tabs from Desktop to Fenix via Firefox Sync does not work.

### ISSUE THREAD

**Issue by nudgegoonies** [mozilla-mobile/fenix#15903]
## Steps to reproduce

Select more then 5 Tabs from Desktop and send to mobile device.

### Expected behavior

All tabs open on the manually triggered sync.

### Actual behavior

Only one tab opens and that only when a single tab was sent and not multiple and then only when clicked on the firefox message.
The system message shows all tabs when sending multiple tabs but clicking on it does not open them.

### Device information

* Android device: MotoG3
* Fenix version: 81.1.3

**Comment by liuche** [comment]
We had an outage for Sync recently, could you check again and let us know if this is still a problem?

@grigoryk @jonalmeida here's a user report about this issue.

**Comment by jonalmeida** [comment]
@liuche this looks like feature request to change the UX.

"Only one tab opens and that only when a single tab was sent and not multiple and then only when clicked on the firefox message."

We show each tab individually so the OS only animates the last one to pop-up on the screen.

**Comment by nudgegoonies** [comment]
The system message in the notification tray shows 5 or so entries as a list in a single entry.
Firefox was showing only one firefox message where i could click on and that opened only one of the tabs i have sent.
I was trying to get 35 tabs to the smartphone and i gave up via sync and exported them as bookmark htmls.

I tried to reproduce it but now it fails completely. Even for a single tab that i sent to the device. Even with manually sync in Firefox on desktop and manually sync on smartphone the single tab does not arrive.

**Comment by jonalmeida** [comment]
> The system message in the notification tray shows 5 or so entries as a list in a single entry.
> Firefox was showing only one firefox message where i could click on and that opened only one of the tabs i have sent.

This is the Android system UX - you have to expand the notification to see them as individual tab items.

> Even with manually sync in Firefox on desktop and manually sync on smartphone the single tab does not arrive.

There have been some intermittent outages and others had reported that send tab is working again - are the tabs still not delivered after syncing _now_?

**Comment by Shadowspear123** [comment]
I have the same problem! Any tab I send to Fenix from desktop is not received on my device, even if it is only one tab. The desktop is a macbook on latest firefox release and I have the latest version of fenix on my galaxy s8 on Android 8.0. The tabs are /not/ delivered after syncing. This used to work on Fennec.

**Comment by Shadowspear123** [comment]
Btw, tabs I send from mobile to desktop are received, just not the other way around.

**Comment by nudgegoonies** [comment]
Thank you for the answer. I was unable to send Tabs from my Laptop to the Smartphone and also the way around did not work. Now i analyzed a bit more. And although there was no error message when manually synchronizing Laptop or Smartphone with Firefox Sync it did not work. I was not able see the latest synchronized tabs from the Laptop on the Smartphone and also the way around did not work. Sending Tabs AND also Synchronized Tabs did not work and there were no error message. I needed to disconnect both devices from the sync and after reconnecting it now works. I works for sendingone Tab and also for sending several tabs. When i send several tabs from the Laptop to the Smartphone i see a message with one tab appearing over Fennec. This message disappears after some seconds. But every tab from the several tabs that i have sent appear as a single system message. I have to tap every message to open these tabs in Fennec.

Maybe i was a victim of the outage. But two things are strange:

The last time there was one System Message with a list of tabs and now i get individual messages for every tab.

The second thing is that i got no error message during manual sync on Laptop and Smartphone and that i needed to disconnect and reconnect them with Firefox sync.

**Comment by jonalmeida** [comment]
@Shadowspear123 @nudgegoonies since you're seeing issues even after pressing the 'Sync Now' button, could either of you provide device logs so we can debug this issue?

You can find instructions on how to do this from the link here: https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by grigoryk** [comment]
@Shadowspear123 does Sync work for you otherwise? E.g. history, bookmarks sync? What does the "last synced:" say in the accounts settings, after you press "Sync Now" button?

thanks!

**Comment by nudgegoonies** [comment]
@jonalmeida As i have written, i logged Firefox Sync off and then logged in again and then it worked. I followed your instruction link and there was no Crash logged. This is true because Fennec hasn't crashed, only receiving sent and synchronized tabs hasn't worked. I think now, where it works, running logcat does not make sense, right?

**Comment by jonalmeida** [comment]
> I think now, where it works, running logcat does not make sense, right?

@nudgegoonies Please do. Receiving sent tabs is what this bug is for debugging. Thanks

**Comment by nudgegoonies** [comment]
@jonalmeida Here is the Log of a Wikipedia Tab i have sent to the smartphone from my laptop by clicking manually sync on my smartphone, waiting the firefox message about the new tab to disappear and then tapping on the system message that opens the tab in Fennec:
https://gist.github.com/nudgegoonies/a7c006514aaf3dd89269834989616158

**Comment by jonalmeida** [comment]
@nudgegoonies Thank you! I can't see any start up logging in Fenix. Would you mind starting up Fenix, then sending a tab before collecting logs?

**Comment by Shadowspear123** [comment]
@grigoryk Hi! Yes sync does work for me otherwise, history/ bookmarks seem to be syncing okay. Under sync now it shows the last synced time, which is 0 minutes ago.

**Comment by Shadowspear123** [comment]
ok something really weird, I just tapped sync now, and then out of nowhere 4 tabs I sent from my macbook to my phone appeared in notifications. The weird part? These are tabs I sent like weeks ago and never received....

**Comment by jonalmeida** [comment]
@Shadowspear123 if you could open Fenix, press sync now and then grab the logs as mentioned above, that would be really helpful!

**Comment by Shadowspear123** [comment]
@jonalmeida I followed the instructions in the link above, but there is no crash log recorded under "Crashes" in "About".

**Comment by jonalmeida** [comment]
@Shadowspear123 if you scroll down the page, you can find a section called `Using adb logcat to get crash information` which will help you extract device logs.

https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information

Thanks!
