### ISSUE TITLE
[Bug] Default to "Search engine" enabled in new empty tab

### ISSUE THREAD

**Issue by nudgegoonies** [mozilla-mobile/fenix#15902]
## Steps to reproduce

Empty tab. Type something.

### Expected behavior

List search engines and select one.

### Actual behavior

I can only select the default search engine and first need to click "Search engine" and then can select an alternative one. 

### Device information

* Android device: MotoG3
* Fenix version: 81.1.3

Please restore the old behavior from Fennec 68 where the additional click was not needed. There i no reason to present a list with one entry and then click to show more entries.

**Comment by liuche** [comment]
This is related to #15867 and #15080 so I'm going to dupe.
