### ISSUE TITLE
Add separators in subsections headers of add-ons list

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#15919]
Pulled from https://github.com/mozilla-mobile/fenix/issues/15898.

As the add-ons screen will require changes in AC that will land at a later time, I will split this issue:
 - This issue is about adding separators in Tabs and Customize screen. (PR: https://github.com/mozilla-mobile/fenix/pull/15917)
 - Adding separators in subsections headers of add-ons list is this issue:

> On the main Settings screen we have a horizontal line above each subheader, which separates a section from the one above it, shown here:
> 
> <img src =https://user-images.githubusercontent.com/22176302/96017035-1be19900-0e0f-11eb-871d-659966f09c1c.jpg width = 20% >
> 
> Other subpages missing separators include: **Tabs**, **Customize**, and **Add-ons**.

**Comment by amkcpu** [comment]
I just wanted to add that in https://github.com/mozilla-mobile/fenix/issues/14636#issuecomment-695868874, @brampitoyo mentioned that next to the divider, the headers' _text colors_ and _spacing_ should be updated too.

This should be easily achieved by switching the header style over to `preference_cat_style` after #15377 has landed.
Currently, of course, this is not possible, but I think it would make sense to make some AC changes to make it possible to set a header style in `AddonsManagerAdapter`.
An alternative would be extending the `Style` data class to be able to set `allowDividerAbove` (the text color can already be set), but I think setting the XML layout is much preferable.

**Comment by liuche** [comment]
Has an AC PR open https://github.com/mozilla-mobile/android-components/issues/8703

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201103`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_202011033333-093257](https://user-images.githubusercontent.com/51314259/97959546-3d9fc180-1db8-11eb-9181-e238cf2f6761.png)
