### ISSUE TITLE
Pages rendered too wide, possible font inflation issue

### ISSUE THREAD

**Issue by kuro68k** [mozilla-mobile/fenix#15912]
Example URLs:

https://www.satsignal.eu/ntp/Raspberry-Pi-NTP.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1579296
https://slashdot.org (be sure to use the "desktop version" link at the bottom)

Browser / Version: Firefox Mobile 83.0, Nightly as of 2020/10/15
Operating System: Android 10
Tested Another Browser: Chrome for Android
Phone: Google Pixel XL

Many web pages are rendered too wide to be readable. If I zoom in enough to read the text then each line is about twice the width of the screen and I have to scroll. Examples:

Firefox:

![image](https://user-images.githubusercontent.com/2674466/96097048-696e0c80-0ec8-11eb-973e-229f4c23c501.png)

Same page in Chrome:

![image](https://user-images.githubusercontent.com/2674466/96097067-6ffc8400-0ec8-11eb-95f0-3a4d49fe58a3.png)

Bugzilla with Firefox default view:

![image](https://user-images.githubusercontent.com/2674466/96097355-c23da500-0ec8-11eb-80f0-0cc226203698.png)

Zoomed so I can read the text on the 5.5" phone screen:

![image](https://user-images.githubusercontent.com/2674466/96097392-cd90d080-0ec8-11eb-99a1-fad545835675.png)

Firefox default view (make sure you select the "desktop view" at the bottom, the mobile site is awful and desktop works fine in Chrome):

![image](https://user-images.githubusercontent.com/2674466/96097712-324c2b00-0ec9-11eb-8536-17d918dbc6b4.png)

Zoomed enough to read:

![image](https://user-images.githubusercontent.com/2674466/96097741-3a0bcf80-0ec9-11eb-8120-c86b23ea9fc1.png)

**Comment by kuro68k** [comment]
Some tests with a Pixel 5 (423 PPI) running Android 11.

Satsignal.eu displays well:

![image](https://user-images.githubusercontent.com/2674466/96352029-24103180-10b8-11eb-9a37-fc0603600a3a.png)

Slashdot desktop version is still too small:

![image](https://user-images.githubusercontent.com/2674466/96352032-2e323000-10b8-11eb-81a0-04ec86035d24.png)

**Comment by liuche** [comment]
Is this fixed by #16070 in the 10/22 nightly?

**Comment by kuro68k** [comment]
> Is this fixed by #16070 in the 10/22 nightly?

Unfortunately not, test sites display the same as before.

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683260

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
