### ISSUE TITLE
[Bug]automatic font sizing option missing in settings in nighlty 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#15910]
today nighlty is missing automatic font sizing in settings,
setting font to100%are way bigger than used to be any fix for this?
thanks

**Comment by MicroBeast** [comment]
Isn't it because of https://github.com/mozilla-mobile/fenix/issues/14923?

**Comment by ale82to** [comment]
yes thank you in today nighlty switch to completely turn off font sizing is still missing and setting font size to 100 % still give a way bigger text 
am I missing something?

**Comment by ale82to** [comment]
since my general android font size is set to 130‰ ,setting font size slider in Firefox to 100%
gives me a very big text and it's not the wanted behavior,because in the end is no longer possible to have both automatic font sizing disable and real webpages font size to 100 % how can such a simple thing be overlooked by the developers is really over me.

**Comment by ale82to** [comment]
in my opinoo this can be solved with just one switch for font size, when disabled it will also disable automatic font sizing and gives 100 font size (real webpages not android setting)

**Comment by ale82to** [comment]
or in other words
100 % in slider (new semplified setting) MUST means real 100 % font size for webpages regardless of android setting for font size.
if the user want bigger font can just use the slider otherwise there 's no way to get real 100 % font size for web content.

**Comment by interfect** [comment]
@ale82to Looks like you reported this upstream as https://github.com/mozilla-mobile/fenix/issues/15910

I think we could probably just revert https://github.com/mozilla-mobile/fenix/commit/881e3d6ccde19fc5c52e07ee097b703b41b3f950 to get the setting back, but I haven't dug in enough to figure out if that's actually a good idea.
