### ISSUE TITLE
[Bug] ESNI Doesn't Get Enabled (Fennec F-Droid)

### ISSUE THREAD

**Issue by jasonmerc** [mozilla-mobile/fenix#15911]
## Steps to reproduce

1. Go to about:config
2. Set network.security.esni.enabled to be true
3. Go to https://www.cloudflare.com/ssl/encrypted-sni/ to check for ESNI

### Expected behavior

ESNI should be reported as enabled, like it does on the desktop Firefox app

### Actual behavior

ESNI is not actually enabled, according to the CloudFlare tool

### Device information

* Android device: Moto X4, Android 10, Lineage 17.1
* Fenix version: Fennec F-Droid 81.1.3

**Comment by andreicristianpetcu** [comment]
This is an experimental feature. You can enable it in Nightly or Beta. https://twitter.com/FirefoxPreview/status/1312643838020812801

![image](https://user-images.githubusercontent.com/922368/96228064-ba9c0000-0f9d-11eb-8167-f100668e1fa4.png)
![image](https://user-images.githubusercontent.com/922368/96228076-be2f8700-0f9d-11eb-87ca-e02ddc5b49d8.png)

You can get the Fennec F-Droid maintainer to enable it if they want to.

The ESNI meta in bugzilla is still open https://bugzilla.mozilla.org/show_bug.cgi?id=esni

Firefox stable on my machine has this feature disabled by default. I don't think this is the right place for this bug.
![image](https://user-images.githubusercontent.com/922368/96227970-96d8ba00-0f9d-11eb-9865-48405103997c.png)

**Comment by liuche** [comment]
Duping to #15858 see details there.
