### ISSUE TITLE
Avoid multiple layouts to improve power usage caused by suspending observer updates

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15921]
We've noticed that fenix uses more power than fennec in user reports. #12840 We don't know the root cause of the issue but we figured we could address some obvious sources of redundant CPU use.

When creating fragments, our observers do not run synchronously – they suspend – and update the view after it's already been laid out, causing an additional layout pass. This is a problem when the whole view needs to be laid out again, like the homescreen.

TODO

This also impacts start up speed...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8196)

**Comment by mcomella** [comment]
Triage: csadilek is potentially addressing this in many cases in https://github.com/mozilla-mobile/perf-frontend-issues/issues/166 and the issue that gets filed in response to it. Let's wait for that before continuing.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807311

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
