### ISSUE TITLE
[Grid View] Investigate accessibility with the grid view

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15922]
We should check what the a11y service rads and how swipes are treated with the grid view.

**Comment by AndiAJ** [comment]
Hi @gabrielluong & @Mugurell , I've just finished checking this matter on the latest **`Nightly Build 201106`**.

✔️ Accessibility Scanner - No issues discovered
✔️ Swipe gestures while Talkback was enabled - No issues discovered
❌ Talkback reading - Filled these issues: #16426 #16424 #16420 #16417 #16416 #16415

**I'll remove the QA needed label for now, and will continue to check for any inconsistencies in the upcoming days.** ☺️

**Comment by AndiAJ** [comment]
New issue from **`Nightly Build 201110`** #16477

**Comment by bifleming** [comment]
Will call this complete, track the two remaining issues independently.
