### ISSUE TITLE
[SPIKE] Investigate Options for Tab Reordering

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15928]
Filing this as a time hold for the sprint for us to start to investigate the AC/Fenix options for reordering tabs in the tabs tray. 

Fenix feature ticket is https://github.com/mozilla-mobile/fenix/issues/10344
and AC ticket is https://github.com/mozilla-mobile/android-components/issues/8376

Main concern is that this work will not be trivial if we still want to support `SessionManager` (`SessionManager` has complex logic for ordering tab, which would get in the way really badly)

Open questions:
- Are there any feasible intermediate solutions?
- Or do we block this feature until we have moved everything off `SessionManager`?

**Comment by liuche** [comment]
added to eng backlog!

**Comment by liuche** [comment]
In planning, we decided that we need to prioritize the SessionManager/Store work over the tab reordering, so we can close this spike.
