### ISSUE TITLE
Gecko resizes when keyboard dismissed by tapping the page

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15923]
via https://github.com/mozilla-mobile/fenix/issues/14279#issuecomment-709453742

_edit: this also appears to happen when clicking a text box on a web page and pressing back on the web page to dismiss the keyboard. The original STR may not be relevant anymore because the homescreen appears when tapping the toolbar._

## Steps to reproduce
- Open a web page 
- Tap the toolbar
- Tap the web page to dismiss the keyboard (I wasn't able to reproduce with the back button)

### Expected behavior
Gecko does not resize

### Actual behavior
Gecko resizes, causing:
- unpleasant jank
- potential delays to the user interacting with the page
- unnecessary computation that uses power

The `resize` `DOMEvent` is visible in the marker chart in this profile: https://share.firefox.dev/31aU6T2

### Device information
* Android device: GS5
* Fenix version: Nightly 201015

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8200)

**Comment by mcomella** [comment]
Triage: inter-team issue but it's mostly a battery and annoying issue so low impact for now.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807312

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
