### ISSUE TITLE
[Crash] ConcurrentModificationException in java.util.LinkedHashMap

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#15925]
It seems like this issue is from Glean based on the stack traces.

See all three merged events: https://sentry.prod.mozaws.net/share/issue/8a32358c6eec4f10a65c04fbc1466b3d/

**Comment by liuche** [comment]
@badboy since you're looking at Glean crashes, is this something y'all have on your radar?

**Comment by badboy** [comment]
It wasn't. Looking at that crash: `ac.glean.build_version28.0.0, ac.version39.0.1`.
That's pretty old. We fixed a related issue back then: https://github.com/mozilla/glean/pull/900

so I think this is a "fixed already, they need to upgrade" kind of bug.
