### ISSUE TITLE
Show warning near address bar when one enters more than 32 words for a Google search

### ISSUE THREAD

**Issue by mystiquewolf** [mozilla-mobile/fenix#15924]
### What is the user problem or growth opportunity you want to see solved?
Google trims the search results to 32 words - this looses the original search query words. Back button also doesn't show you what you have written before visiting Google by clicking Enter button.
### How do you know that this problem exists today? Why is this important?
Because the user will enter more words, Google will trim to 32 words, and the user will not be able to easily get his full search request query after that.
### Who will benefit from it?
All users who for some reason enter long strings/ many words into address bar for searching.

**Comment by liuche** [comment]
This isn't something that Fenix can do - we don't track your text entry on websites, and it's a very specific website, so this would have to be done by the website itself.
