### ISSUE TITLE
Don't reinit fragments and reinflate layouts to reduce power usage

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15920]
We've noticed that fenix uses more power than fennec in user reports. https://github.com/mozilla-mobile/fenix/issues/12840 We don't know the root cause of the issue but we figured we could address some obvious sources of redundant CPU use.

Each time we navigate between fragments, we re-initialize the fragment and reinflate of view. This is probably unnecessary because we can cache the fragments and thus the views.

Concerns:
- We should ensure the observers are not updating UI when the fragment is stopped (csadilek said this is unlikely)
- Could this increase memory consumption too much on low end devices? Proposal: check how much memory these Fragments use (though it's hard to do it realistically – what about users with 100s of tabs open?) – if it's trivial, just make the change. If not, we should consider evaluating the change through other metrics such as retention on low-end devices.

Note: this will also make our UI transitions faster.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8194)

**Comment by mcomella** [comment]
Triage: leave open as an investigation for when we do power usage. However, I'm skeptical we can do anything here because the Navigation library controls a lot of this.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807310

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
