### ISSUE TITLE
FNX-5123 ⁃ [Bug] Some icons mix up the colors between light & dark mode (Android 6 and lower)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1593]
## Steps to reproduce
1. On light mode, open a tab and go to the homescreen. Observe the Save session button.
1. On dark mode, go to Settings & on homescreen, observe the black icons.
    1. Expected behavior
Icons respect the color scheme.
    1. Actual behavior
Mixed black & white icons in both theme modes.
*later noticed that the phone's status bar is invisible on the Mi 4i device (Android 5).

**HTC Desire:**

![htc home](https://user-images.githubusercontent.com/4037709/56022970-83e48a00-5d15-11e9-9b57-dfaa886484ea.png)
![htc settings dark](https://user-images.githubusercontent.com/4037709/56022973-847d2080-5d15-11e9-9537-ff650623c63f.png)
![htc home dark](https://user-images.githubusercontent.com/4037709/56022975-847d2080-5d15-11e9-98ad-4a10977d8c9a.png)

**Mi 4i:**
![Mi 4i](https://user-images.githubusercontent.com/4037709/56022972-83e48a00-5d15-11e9-944a-6d6aa0e95f96.png)

### Device information
* Android device: HTC Desire 820 (Android 6.0.1), Mi 4i (Android 5.0.2), Nexus 5 (Android 6.0.1)
* Fenix version: 4/11 build

**Comment by kbrosnan** [comment]
This sounds like a variant of #824

> @ekager  The problem was fillType:evenOdd does not play well with fillColor from theme attributes on =<24. Think I caught all of them that needed the change!

**Comment by ekager** [comment]
Ah no I think this is just a theming issue that slipped through the cracks. This button doesn't exist anymore, closing

**Comment by kbrosnan** [comment]
Screenshot number 2 and 3 is still present on a self built version of Fenix from a few minutes ago.

**Comment by ekager** [comment]
Ah I see, let me try something and see if that fixes it :)

**Comment by ekager** [comment]
Alright it *should* be better in master, please test and let me know :)

**Comment by kbrosnan** [comment]
Yes! Thank you for the quick fix. It even fixed some things like toast notifications which were not mentioned.
