### ISSUE TITLE
[Feature request] Make the "blank loading screen" black when in dark mode

### ISSUE THREAD

**Issue by daveout** [mozilla-mobile/fenix#15936]
Hi. Sometimes, when I open or switch tabs in dark mode (with the "dark reader" extension enabled), a white blank loading screen appears before the page is loaded. This totally ruins the idea and vibe of a dark mode.

Therefore, I want to suggest the following improvement:
When in dark mode, all blank loading screens should be black. Thank you.

**Comment by Poopooracoocoo** [comment]
Which version are you on? They've fixed many a bug regarding this issue.

**Comment by daveout** [comment]
The latest one: Nightly 201015 17:01 (Build #2015769889)
I'm gonna (try to) attach a screen capture:
![screen](https://user-images.githubusercontent.com/54579499/96226924-b524c280-0f69-11eb-9c29-ff3939e405c3.gif)

**Comment by Dunexus** [comment]
See https://github.com/mozilla-mobile/fenix/issues/6313

**Comment by daveout** [comment]
@Dunexus thanks. i'm gonna close this as it is redundant.
