### ISSUE TITLE
Sort Downloads from newest to oldest

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#15931]
People go to their download folder to find what they downloaded recently. Currently, downloads are sorted oldest to newest and people have to scroll to find what they recently downloaded. We should reverse the sorting to make it quicker to find recently downloaded items.

**Comment by Amejia481** [comment]
We exposed the property `createdTime` on [DownloadState](https://github.com/mozilla-mobile/android-components/blob/5cd371eebc9e2dfef8cc45472dd52a72b5a36558/components/browser/state/src/main/java/mozilla/components/browser/state/state/content/DownloadState.kt#L46), we should just sort the list of the downloads using this property :)

**Comment by joc-a** [comment]
I'd like to pick this up!

**Comment by Amejia481** [comment]
Go for it :)

**Comment by Poopooracoocoo** [comment]
darn github doesn't seem to link issues when they're referenced in the title of a PR. #15939

**Comment by anotherus3r** [comment]
Kinda related: #14984

**Comment by sflorean** [comment]
Verified as fixed on Nightly 11/3 with Pixel 3 (Android 11) and LG G7 FIT (Android 8).

**Comment by Amejia481** [comment]
Thanks @sflorean !
Awesome work @Poopooracoocoo!
