### ISSUE TITLE
FNX-5124 ⁃ [Bug] Session list scrolls just half-way up when restoring a session

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1594]
## Steps to reproduce
1. Save a few sessions to have a long list to scroll.
1. Tap a session from the bottom of the list.
    1. Expected behavior
The list scrolls up to see the restored tabs.
    1. Actual behavior
The list scrolls just half way up.
    1. Device information

* Android device: Pixel (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/11

**Comment by kbrosnan** [comment]
We have removed sessions for now.
