### ISSUE TITLE
Do not delete favicons with browsing data

### ISSUE THREAD

**Issue by code644** [mozilla-mobile/fenix#15950]
All favicons from pinned top sites, bookmarks and collections are cleared when deleting 'Browsing history and site data'. https://github.com/mozilla-mobile/fenix/issues/12980

Chromium based browsers never clear favicons for bookmarks. IMHO it is a bad user experience when favicons disappear, especially for pinned top sites.

There needs to be a way to keep favicons when browsing data is deleted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8229)

**Comment by anotherus3r** [comment]
For me, they also disappear after every Nightly update.

**Comment by jonalmeida** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
