### ISSUE TITLE
[Bug] IntersectionObserver: node isn't intersecting on the very bottom of the page

### ISSUE THREAD

**Issue by ranzwertig** [mozilla-mobile/fenix#15959]
## Steps to reproduce
1. Go to: https://codesandbox.io/s/blazing-waterfall-sury4
2. Open the preview in ff mobile
3. Scroll to the bottom
4. The red area says `should intersect` instead of `did intersect`.

### Expected behavior
1. Go to: https://codesandbox.io/s/blazing-waterfall-sury4
2. Open the preview in ff mobile
3. Scroll to the bottom
4. The red area says `did intersect`

To get the expected behavior you can uncomment the line
```
rootMargin: "50px" // TODO: to make it work, uncomment this line
```
It seems like it intersects after making the intersectable area higher than the browser bar.

### Actual behavior
The red area says `should intersect` instead of `did intersect`.

### Device information

* Android device: Pixel 4
* Fenix version: 81.1.5 (Build #2015769595)

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672564

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
