### ISSUE TITLE
FNX-5125 ⁃ [Bug] Video stops when rotating the device

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1595]
## Steps to reproduce
1. Go to youtube.com and play a video
1. Turn the device to landscape mode. 
1. Play the video again, rotate it back to portrait.
    1. Expected behavior
Video keeps playing while switching the layout.
    1. Actual behavior
Video stops.
Not reproducing on cnn or dailymotion videos.
    1. Device information

* Android device: Pixel (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/11

**Comment by sblatz** [comment]
I'm not able to reproduce this on my Galaxy S9.

**Comment by sv-ohorvath** [comment]
Not reproducing anymore on the 6/3 build. Devices: Pixel, Galaxy S8, Nexus 5.
