### ISSUE TITLE
Make the homescreen (especially top sites) costumizable

### ISSUE THREAD

**Issue by neatwheat** [mozilla-mobile/fenix#15956]
- Please make the homescreen better customizable. It should be at least possible to change the name of the top sites!! Some sites dont show a name, and if they also dont display a recognizable logo its complete useless. It would also be usefull to be able to change their order.

- It should also be possible to pin a shortcut to a certain bookmarks folder to the homescreen.

### How do you know that this problem exists today? Why is this important?
Because the homescreen is a pain to use  

### Who will benefit from it?
Every firefox user

**Comment by anotherus3r** [comment]
Top site renaming: #9548

**Comment by jawz101** [comment]
There are so many similar variations on this request- some of which I made- that I've given up.

It call I comes down to getting bookmarks on the main page because they sync as opposed to collections and top sites which don't sync.  It would eliminate the redundancy

**Comment by Imold** [comment]
Dupe of #12065
