### ISSUE TITLE
Enable Grid View in Nightly only

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#15960]
Spoke to @vesta to enable grid view for Nightly only.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201110 05:01 (Build #2015774761) GV 84.0a1 from 11/10 with the devices:

- Motorola Moto G6 (Android 8);
- Google Pixel 2 (Android 9);
- Huawei P9 Lite (Android 7).

The Grid view is enabled in Tabs setting on Nightly only. Is not enabled on the latest Beta 83.0.0-beta.4 GV 83 from 11/9 and on the latest Release 82.1.3 GV 82 from 11/9.

I will close this issue and remove the qa:needed label.
