### ISSUE TITLE
[Bug] Donwnload Link saves link image instead of the file

### ISSUE THREAD

**Issue by aembleton** [mozilla-mobile/fenix#15969]
## Steps to reproduce

1. Go to http://www.happyhiker.co.uk/MyWalks/Cumbria/Arnsideknott/Hiking%20Pages%20-%20Arnside%20Knott.htm
2. Long press on the .gpx image in the bottom left cell of the top table
3. Tap on Download link

### Expected behavior

Downloads the GPX file

### Actual behavior

Downloads the JPG file that is used to display .gpx on the web page

### Device information

* Android device: Xiaomi 9T running MIUI 12.0.2, Android 10
* Fenix version: 81.1.4

**Comment by aembleton** [comment]
I've just recreated the issue on Nightly 201015 17:01

**Comment by Amejia481** [comment]
I think this was covered by https://github.com/mozilla-mobile/android-components/pull/9420, the functionality should be available in the latest [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) and will be available in future Firefox version, please feel free to reopen if needed.
