### ISSUE TITLE
Show a border for last selected tab when in tabs tray - grid layout

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#15968]
After https://github.com/mozilla-mobile/fenix/issues/15907 which removed the decorator used for addind such a border we need a new way of showing what is the active tab.

After discussing with @gabrielluong we'll go doing this in the same method that sets the background for the active tab when the list based layout is used - [updateBackgroundColor](https://github.com/mozilla-mobile/fenix/blob/5153a3f2c5011a1f77c303832f3cd22692a68207/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt#L173)

Based on https://www.figma.com/file/luMaQYjwiMtQM5xQ30P9yP/Tabs?node-id=168%3A713 the border should:
- have 4dp in size
- be placed at the exterior of the item
- have a 8dp radius
- have the `#592ACB` color

**Comment by sflorean** [comment]
Verified as fixed on Nightly 11/2 with Pixel 3 (Android 11).
