### ISSUE TITLE
[Bug] in android the second time I cannot open link in play store

### ISSUE THREAD

**Issue by 424344** [mozilla-mobile/fenix#15964]
## Steps to reproduce
- set option to open links in app
- go to a site containing links to apps in play store, like:
https://www.androidpolice.com/2020/10/16/android-app-game-sales-october-16-2020/
- click on a link, wait for play store to load
- click on android back button to go back to fenix
- click again on the same link
### Expected behavior
I expect that the play store app is opened the second time (and third time, etc)
### Actual behavior
fenix loads the play store web page, instead of opening the play store app.
### Device information

* Android device: ?
* Fenix version: ?
nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8243)

**Comment by s-ankur** [comment]
For me it seems to work correctly: Asus Zenfone (LineageOS 16)
 Night

**Comment by tortino** [comment]
Additional info: my tests where done on a samsung galaxy a50 running android 10. 
I also tested chrome and it works correctly.
I tested fenix stable on another device (samsung galaxy a5 running android 8) and it's the same bug.

**Comment by mehee** [comment]
I have the same problem with other apps also.

But it has a pattern: 
1st click on link -> opens App 
(switch back to Fennec)
2nd click on link -> opens link in browser
(go back)
3rd click on link -> opens App
(back)
4th click on link -> browser again
and so on.

Also happen with different links but same App (+ some links will never work, but thats an Android/App/Link problem i guess).

**Comment by tortino** [comment]
still happening on current nightly

**Comment by 424344** [comment]
this issue is still present, please do not close it.
