### ISSUE TITLE
Performance experiment: Initiate a speculative TCP connection in the view intent receiver

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla-mobile/fenix#15974]
The idea behind the experiment:
In the applink scenario (view intent), initiate the speculative connection as soon as possible. (Otherwise we rely on the Geckoview layer to make the speculative connection).

The hope is to reduce the connection setup time (dns,tcp synchronization, tls handshake), thus improving the performance of the first page load.

**Procedure**

In the Android-Components handling of the view intent, we will insert a speculative connect:
```
sessionManager.engine.speculativeConnect(url)
```

https://github.com/mozilla-mobile/android-components/blob/110a151014e75ee0c14e008f9c3a818a2fd5d49f/components/feature/intent/src/main/java/mozilla/components/feature/intent/processing/TabIntentProcessor.kt#L48

**Results**

No measured improvement:

|Variant | Median, navStart | Median, loadEventEnd |
| -- | -- | -- |
| Baseline | 2420 | 5496 |
| Experiment | 2462 | 5560 |

Baseline:
https://docs.google.com/spreadsheets/d/1lu_c0hZGMzMpqGuEb8wtA8hwEucItiy-Uf8gpWUYVmo/edit#gid=0&range=B1:G22

Experiment:
https://docs.google.com/spreadsheets/d/1lu_c0hZGMzMpqGuEb8wtA8hwEucItiy-Uf8gpWUYVmo/edit#gid=0&range=B48:G68

**Notes**

I also tried preceding the speculative connection with a speculative session creation (as in  https://github.com/mozilla-mobile/fenix/issues/15973), however I did not measure any improvements:
https://docs.google.com/spreadsheets/d/1lu_c0hZGMzMpqGuEb8wtA8hwEucItiy-Uf8gpWUYVmo/edit#gid=0&range=B71:N92

**Comment by acreskeyMoz** [comment]
I'll leave this open for a bit in case anyone has any ideas on it.

**Comment by mcomella** [comment]
I'm assuming kotlin TabIntentProcessor calls loadUrl which calls into GV loadUrl which calls into its js scripts to create the speculative connection. I'd assume the JVM layers are pretty thin here: maybe it's not significantly earlier to result in a perf improvement? Maybe you can some timestamps/markers when the speculative connection occurs and compare between the two builds to see if the change 

Also, like the other bug, maybe there is a bug and this isn't working as expected.

**Comment by acreskeyMoz** [comment]
That's a good idea -- with `nsHttp,5` MOZ_LOGs I can see the timestamps of the speculative connections.

**Comment by acreskeyMoz** [comment]
Thank you Mike - I'm glad I went through the logs:
The speculative connection pool is disabled through a layer of the test harness!

It's here:
https://github.com/sitespeedio/browsertime/blob/325d5389b4deb6b68bff0e5b8fa42c9d457bfdc5/lib/firefox/settings/firefoxPreferences.js#L139

I'll fix this in the upstream repo and retest with it removed.

**Comment by acreskeyMoz** [comment]
https://github.com/sitespeedio/browsertime/issues/1422

**Comment by acreskeyMoz** [comment]
Fixing the bug in the test layer that disables speculative connections still did show any significant improvement.
https://docs.google.com/spreadsheets/d/1lu_c0hZGMzMpqGuEb8wtA8hwEucItiy-Uf8gpWUYVmo/edit#gid=0&range=A112:J208

I did capture logs and it appears that we're already establishing the connection to the target url, example.com before the speculative connect starts.

The large delay between receiving the intent and getting the geckoSession up and running (~2 seconds) appears to be the bottleneck here:

```
10-29 10:52:27.411  1570  1623 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://www.example.com/... flg=0x10000000 cmp=org.mozilla.fenix/.IntentReceiverActivity (has extras)} from uid 2000 on display 0

10-29 10:52:27.967  1570  3284 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://www.example.com/... cmp=org.mozilla.fenix/.HomeActivity (has extras)} from uid 11213 on display 0

10-29 10:52:29.344 23902 23923 I Gecko   : [(null) 23902: Main Thread]: V/nsHttp nsHttpConnectionMgr::SpeculativeConnect [ci=.SA.....[tlsflags0x00000000]incoming.telemetry.mozilla.org:443]

10-29 10:52:29.623 23902 23923 I GeckoSession: zerdatime 1362677702 - chrome startup finished

10-29 10:52:29.687 23902 23923 I Gecko   : [Parent 23902: Main Thread]: E/nsHttp host=www.example.com port=-1

10-29 10:52:29.957 23902 23923 I Gecko   : [Parent 23902: Main Thread]: V/nsHttp nsHttpConnectionMgr::SpeculativeConnect [ci=.S......[tlsflags0x00000000]www.example.com:443^partitionKey=%28https%2Cexample.com%29]
```

We can see that if we could initiate the speculative connection at the same time as the one for telemetry is made (parent process) we might be able to shave off ~300ms on Moto G5.

**Comment by acreskeyMoz** [comment]
A profile of this scenario:
https://share.firefox.dev/3kFitAf

I think this particular route - spec connection in the intent receiver won't bear any fruit.
But it does give ideas for other experiments.

**Comment by acreskeyMoz** [comment]
I'm going to close this as the experiment was run but did not yield a measurable improvement.
