### ISSUE TITLE
FNX-5127 ⁃ [Bug] The current default Bookmark folders don't make sense on mobile

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1597]
## Steps to reproduce
1. Go to bookmarks.
1. See the "menu", "toolbar", "unfiled" folders.
    1. Expected behavior
On Fennec, these folders appear only after a sync with a desktop app. 
    1. Actual behavior
The folders don't make sense on Mobile as default folders.
    1. Device information

* Android device: any
* Fenix version: 4/11 build

**Comment by colintheshots** [comment]
This is an issue for FxA. We have no control over these built-in folders. We could potentially hide the other folders, but then you wouldn't see the synced folders.

**Comment by kbrosnan** [comment]
Duping to #1951 which has had more discussion.
