### ISSUE TITLE
[Bug] Share icon on bottom bar deviates from design guidelines when opened in custom tab

### ISSUE THREAD

**Issue by naiyerasif** [mozilla-mobile/fenix#15972]
## Steps to reproduce

Open a web page in the custom tab with an app that offers share icon on the bottom bar. The example here is on Feedly.

![image](https://user-images.githubusercontent.com/19614213/96293397-4ba7c100-1008-11eb-8806-5768d5fc4c9a.png)

### Expected behavior

The share icon should be of the same size and color as the rest of the icons on the bottom bar.

### Actual behavior

The share icon is larger and is of different color than the rest of the icons.

### Device information

* Android device: OnePlus 8 Pro on Android 11
* Fenix version: 81.1.4

**Comment by anotherus3r** [comment]
Looks fine for me on Nightly 201016 17:01 (Build #2015770059).
![Screenshot_20201017_003135.jpg](https://user-images.githubusercontent.com/20287690/96319569-56feea80-1010-11eb-9e07-73e3b79f349f.jpg)

**Comment by naiyerasif** [comment]
Yes, this looks as expected on Nightly. Closing this since a fix is already upcoming.
