### ISSUE TITLE
Search Engine (not bookmark) keyword support

### ISSUE THREAD

**Issue by RussellAult** [mozilla-mobile/fenix#15985]
On Desktop, we have search engine shortcuts (like @google, @ddg) so this is a request to add that to Fenix.

![Screen Shot 2020-10-23 at 8 01 54 AM](https://user-images.githubusercontent.com/1082253/97020275-30f0b300-1506-11eb-846e-4b347ecc55f1.png)

### What is the user problem or growth opportunity you want to see solved?

Keyword-based awesomebar searching (e.g. configuring "wp" as the keyword for Wikipedia's search engine and typing `wp asdfg` in the awesomebar will take the user directly to the Wikipedia search results for "asdfg"), a feature dating back to at least Firefox v3 (and historically available in Firefox on the Android platform), is not currently possible in Fenix. Historically this has been achieved using Bookmark keywords, but (per https://bugzilla.mozilla.org/show_bug.cgi?id=1653261) this is being deprecated in favour of Search Engine keywords. Search Engine keyword support already exists in Firefox for Desktop, and adding it to Fenix would once again allow for keyword-based searching on Android.

### How do you know that this problem exists today? Why is this important?

Per #12099, there are lots of people who have relied on bookmark keyword support for keyword-based searching (myself included), and since that issue has been closed as wontfix (based on the above Bugzilla bug) keyword-based searching isn't currently available in Fenix at all.

### Who will benefit from it?

Anyone who relies on keyword-based searching.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8262)

**Comment by liuche** [comment]
Please follow along in bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1653261

**Comment by RussellAult** [comment]
I'm not sure why this was closed; I'm not requesting keyword _migration_ (which is what that bug is about), I'm asking for search keyword _support_, which already exists in desktop Firefox.

**Comment by liuche** [comment]
Sorry about that - I should have linked to the comment that explains why this bugzilla is relevant.

https://github.com/mozilla-mobile/fenix/issues/12099#issuecomment-704143064

**Comment by RussellAult** [comment]
Sorry, maybe I wasn't clear: #12099 was asking about _Bookmark_ keywords; I'm requesting _Search Engine_ keywords, as in, keywords for the preferences-defined awesomebar search engines.

On desktop Firefox, if you go to `about:preferences`, click on the "Search" menu item, and scroll down to the "One-Click Search Engines" list, you'll see there's an option to add a keyword for search engines; if I add the keyword "wiki" to the default included "Wikipedia (en)" search engine, typing "wiki test" into the awesomebar takes me to the English Wikipedia article for "Test", just like the bookmarks (used to) do.

This is existing functionality on Firefox desktop that I'd like to see added to Fenix.

**Comment by liuche** [comment]
Thank you for the clarification! I added a screenshot so this is more clear 😅 We just get a lot of requests for bookmark search, but you're right, that search engine shortcuts are what we're moving towards. Reopening!

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807570

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
