### ISSUE TITLE
[Bug] TransactionTooLargeException

### ISSUE THREAD

**Issue by ceisserer** [mozilla-mobile/fenix#15995]
## Steps to reproduce

1. changed password of my gmail account using firefox for android
2. when password was changed, google re-directed me to my account
tried two times -> always crashed

### Expected behavior

no crash

### Actual behavior

tab crashed

### Device information

* Android device: Sony Xperia XZ1 Compact (Android 9)
* Fenix version: Nightly 20201014095212

https://crash-stats.mozilla.org/report/index/0ddce4cf-29a1-4f35-9cdb-e2a180201017
https://crash-stats.mozilla.org/report/index/0e193273-675a-42fd-8a87-9832a0201017

**Comment by liuche** [comment]
This looks like a crash that's on the rise in Fenix in the last release.

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672566

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
