### ISSUE TITLE
[Bug] Firefox duplicate blank instance

### ISSUE THREAD

**Issue by dabat** [mozilla-mobile/fenix#15999]
Firefox has a duplicate blank app instance. When the recent app list is viewed, there are two Firefox instances: one that has a preview showing the most recently viewed page and one that is blank, a dark gray color.

Please review the attached screen cast and screenshots.

## Steps to reproduce
Open Firefox
Open recent apps list
Scroll back through the list and find two Firefox instances

### Expected behavior
Only one Firefox instance in the recently used app list, with page preview (for normal tabs)

### Actual behavior
There are two Firefox app instances in the list, one that has a page preview, and one that is blank.

[screen cast](https://drive.google.com/file/d/1GnxG8uozXr0q8bw3bjCupHlyh7__YzfT/view?usp=drivesdk) 
![Screenshot_20201016-202618](https://user-images.githubusercontent.com/37282138/96353500-59a22400-1092-11eb-8a01-97b734292a99.png)
![Screenshot_20201016-202705](https://user-images.githubusercontent.com/37282138/96353502-5e66d800-1092-11eb-8f93-c8d041e9b739.png)
I'm running a Pixel 2 on Android 11.

**Comment by jawz101** [comment]
Confirmed.  It looks like stable now has the bug that nightly and beta had when running on Android 11

**Comment by jawz101** [comment]
Probably a few more than this but 
I don't know why stable would still have the problem

https://github.com/mozilla-mobile/fenix/issues/13270
https://github.com/mozilla-mobile/fenix/issues/15744

**Comment by cadeyrn** [comment]
>  I don't know why stable would still have the problem

Because it's fixed in Firefox 82 and Firefox 82 is not yet released.

**Comment by dabat** [comment]
Awesome @cadeyrn thanks!
Sorry for the duplicate, I searched for this issue but was unable to find it having been reported.
