### ISSUE TITLE
Consider Skeleton UI when loading or switching tabs.

### ISSUE THREAD

**Issue by black7375** [mozilla-mobile/fenix#15994]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
- Skeleton UI when switching can feel smooth and fast
- Can't we just show it until [First Contentful Paint (FCP)](https://web.dev/fcp/)?
![Cake](https://user-images.githubusercontent.com/25581533/96328352-9be74900-1031-11eb-9d17-42d0b1aede66.gif)

### How do you know that this problem exists today? Why is this important?
- A blank screen feels boring.
- Currently, it looks `white` even in dark mode.
![Fenix](https://user-images.githubusercontent.com/25581533/96328354-9db10c80-1031-11eb-9392-1f8d6ea870f6.gif)

### Who will benefit from it?
- Slower network user
- Dark mode user

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8271)

**Comment by Poopooracoocoo** [comment]
see #6313

**Comment by black7375** [comment]
@Poopooracoocoo 
Thank you for the information.

This issue is displaying Skeleton UI until FCP, so I thought it was another feature addition.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812907

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
