### ISSUE TITLE
unmute mobile slides

### ISSUE THREAD

**Issue by kaipoeritz** [mozilla-mobile/fenix#16008]
I have an issue with Firefox on Android (e.g. build #2015770251).

When using autoplay videos in presentation slides, I do not want to show controls (play, mute, etc.), but I want the user to bring the controls up front to manipulate them (e.g. pause or mute). But there is no entry in the menu, no does a "right click" (like on the desktop) show the controls. 

This results in: the user not having controls at all.

I hereby kindly ask to make controls easily available to the user (for sites with autoplay and controls disabled).

**Comment by gabrielluong** [comment]
@kaipoeritz thank you for reporting the issue! Do you have an example page to reproduce the issue?
