### ISSUE TITLE
Add gesture to tap and drag to open+select main menu

### ISSUE THREAD

**Issue by Shadowspear123** [mozilla-mobile/fenix#16004]
### What is the user problem or growth opportunity you want to see solved?

Instead of making two taps (first to tap 3-dots and then a tap choose an option), simply tap on the menu once and without lifting the finger, glide through the menu. Once you're on desired option, lift the finger. This is a feature many android apps have had for a long long time.

Example: https://i.imgur.com/39N2K8J.gif

### How do you know that this problem exists today? Why is this important?

This is a QOL improvement which will make navigating firefox a bit more smooth and fast

### Who will benefit from it?

Everybody

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8289)

**Comment by Poopooracoocoo** [comment]
You don't long press but _drag_.

https://github.com/mozilla-mobile/reference-browser/issues/420
https://github.com/mozilla-mobile/android-components/issues/3587

I also mentioned it recently. https://github.com/mozilla-mobile/fenix/issues/14320#issuecomment-691903449

and people who use the menu often, to bookmark for example, will benefit. If you could create a new tab from that menu, it'd be also really easy to access but new tabs are still very awkward in Fenix (but that's another issue)

It's a feature that's available in native Android menus. It's similar to clicking and dragging on menus on desktop operating systems. I reported a [Bugzilla issue ](https://bugzilla.mozilla.org/show_bug.cgi?id=1647992) for the desktop browser too.

**Comment by Poopooracoocoo** [comment]
btw it's great to see some action on these issues after a long time. thanks em :D 
as you've seen already, i've triaged quite a few issues myself as dupes and i'm just a passionate user

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807055

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
