### ISSUE TITLE
Swipe to switch tabs does not work when navigation bar is hidden [Bug]

### ISSUE THREAD

**Issue by Shadowspear123** [mozilla-mobile/fenix#16003]
## Steps to reproduce

 Hide navigation bar either through adb or through your device settings.
 Set the toolbar to be on the bottom.
 Open 2 or more tabs.
 Try swiping to switch tabs, it won't work unless you unhide the navbar.

### Expected behavior

The swipe to switch tabs gesture should work

### Actual behavior

Nothing happens.

### Device information

* Android device: Galaxy S8, Android 8.0
* Fenix version: 81.1.3

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview 81.1.5 and Nightly 201019 (Build #2015770635).

**Comment by Shadowspear123** [comment]
Yes I forgot to mention that the issue is also persistent on Nightly, I have the latest version from play store and the gesture does not work.

**Comment by kcpr** [comment]
I noticed that it only appear if the tool bar is set to be displayed on the bottom. Also, I experienced the issue while using "Immerse mode" toggled with [Quick Settings](https://play.google.com/store/apps/details?id=it.simonesestito.ntiles) , but not if I use Hide [Navigation Bar](https://play.google.com/store/apps/details?id=com.ivianuu.hidenavbar) which works differently - by kind of removing the navigation bar, not hiding it.

**Comment by VitalyVPinchuk** [comment]
Hello!
I can't reproduce the issue neither using Pixel 4 API 29 emulator nor Xiaomi Mi 9T Pro on the latest master.
Could anyone please check if it's still reproducible?

**Comment by LaurentiuApahideanSV** [comment]
The issue still occurs on Firefox Nightly 210402 however I can only reproduce the issue on a Samsung Galaxy S9 (Android 8.0.0), on other devices it works fine.

**Comment by kcpr** [comment]
> The issue still occurs on Firefox Nightly 210402 however I can only reproduce the issue on a Samsung Galaxy S9 (Android 8.0.0), on other devices it works fine.

I also use Android 8.0 (it is possibly API level 26), so maybe the issue only concerns older Android versions.
