### ISSUE TITLE
Show an error message when try to download a file from an FTP server

### ISSUE THREAD

**Issue by 10110111** [mozilla-mobile/fenix#16007]
## Steps to reproduce
1. Go to an FTP server that contains a PNG image
1. Tap the link corresponding to this PNG file
1. In the dialog that appears tap _Download_
### Expected behavior
A toast indicating that "Downloads from FTP(s) servers are not supported" 
### Actual behavior
A toast appears with message "Firefox can't download this file type". The following animated sequence illustrates this:
![anim](https://user-images.githubusercontent.com/6376882/96374967-b1b65480-117e-11eb-827b-7b2da11d7721.gif)
### Device information

* Android device: Samsung SM-A320F/DS (Galaxy A3 (2017))
* Fenix version: 81.1.4

**Comment by Amejia481** [comment]
We dropped support for FTP as it's not a secure protocol, you could read more about [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475)

**Comment by 10110111** [comment]
Well it should be communicated clearly then, not saying senseless things about "file type".

**Comment by Amejia481** [comment]
We can repurpose the issue to improve the messaging, thanks for the feedback!

**Comment by chrishernan** [comment]
Hello.  If no one has picked this up, could I work on it please?
It should be a text change to the toast only correct?

**Comment by Amejia481** [comment]
👋🏽 hi @chrishernan please feel to take it. You have to detect if it's a FTP download request  and adapt the text correspondingly.

**Comment by KrasnayaPloshchad** [comment]
There are some Android app designed to create a FTP server to share files from device. 
https://search.f-droid.org/?q=FTP

**Comment by chrishernan** [comment]
Hi, after digging around to see where that Toast was coming from. I found that it is coming from the DownloadsFeature.kt in android-components. 
The function that displays the Toast is showDownloadNotSupportedError().
I don't think we can fix this in fenix, it would have to be fixed in android-components.
Any thoughts?

**Comment by Amejia481** [comment]
👋🏽  We have the functionality on Android components to share the same behavior across other other apps, please free to do the changes there, if you need any help just let know.

**Comment by SnexusG** [comment]
isn't there a way to figure out if the file requested for download is from a FTP server and then make an exception for it in the app itself?

**Comment by Amejia481** [comment]
I think using the protocol part from the request `URL` can help use to identify it. We need to do the change on  [Android components](https://github.com/mozilla-mobile/android-components)  as the download is entirely handled by the [download module](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/downloads/README.md) to make it reusable for other apps.

**Comment by SnexusG** [comment]
yea i think we can identify using the url scheme. i'll try to look into it though i'm pretty new to all of this.

**Comment by KrasnayaPloshchad** [comment]
FTP is announced to be killed in Firefox.
https://www.mozilla.org/en-US/firefox/88.0beta/releasenotes/

**Comment by SnexusG** [comment]
But the ftp urls dont even seem to open with the current build, is this issue resolved now @Amejia481? or am i missing something

**Comment by KrasnayaPloshchad** [comment]
Even through Mozilla decided to end up support for FTP in Firefox, they still create some APIs to make WebExtension working for this ([bug 1626365](https://bugzilla.mozilla.org/show_bug.cgi?id=1626365)). It would be nice if the same APIs works in Fenix as well.

**Comment by Amejia481** [comment]
> But the ftp urls dont even seem to open with the current build, is this issue resolved now @Amejia481? or am i missing something

Could you share an example of the `URL`s that you are using that I can try ?

**Comment by KrasnayaPloshchad** [comment]
On version 88.1.2 it was began worse. Input FTP server site returns blank page.
Iʼve discovered X-Plore add [FTP server](https://www.lonelycatgames.com/docs/xplore/ftp-server), which creates a FTP site from device, so I can reproduce now, both authentic and anonymous access doesnʼt work on Firefox for Android. It would be nice if Firefox for Android accept an extension work for this protocol, that make it possible to make use of Firefox for sharing files in FTP.
