### ISSUE TITLE
[Bug] DNS

### ISSUE THREAD

**Issue by Bhooty** [mozilla-mobile/fenix#16000]
## Steps to reproduce
Use dns from https://adhole.org/ on your router then use firefox
It will still load ads
Meaning it ignores the router dns because of hardcoded(maybe) dns
Chrome used to do this but after an update they fixed it for which it now uses router dns
Hope to get a fix :)

### Expected behavior
Use the router dns thus ads will be blocked

### Actual behavior
Ads loading even though router dns has adblocking

### Device information
Samsung note 8
* Android device: Yes
* Fenix version: 81.1.4

**Comment by liuche** [comment]
Not sure what we can do here, maybe we do this for security reasons?

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672567

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by valenting** [comment]
@Bhooty could you comment in the bugzilla issue? 
https://bugzilla.mozilla.org/show_bug.cgi?id=1672567

We need more info such as:
Did you manually turn on DNS over HTTPS/DoH using the network.trr.mode pref?
Did you change the DNS settings on your Android device?
Are you using a VPN or other DNS apps such as [OneDotOne](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone&hl=en_US&rdid=com.cloudflare.onedotonedotonedotone) ?
