### ISSUE TITLE
wierd textbox behaviour[Bug]

### ISSUE THREAD

**Issue by seriousgranpa** [mozilla-mobile/fenix#16010]
S1)start ryping in text box
2) get wierd bug where you cant control a coursor, you can move it but it will return to a specific poin, IN THIS CASE BETWEEN  "S" AND "TEPS TO REPRODUCE)

Android 7
Redmi 4x

Also, its not as comfortable as in chrome, where text box dividedsmartly, you can choose easily end of the text line, by tapping somewhere to the right of it, in mozilla to continue writing you need to tap exactly on the end of yhe line 
teps to reproduce

### Device information

* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672624

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
