### ISSUE TITLE
[Bug] The Onboarding tour is not dismissed after opening a page via the search bar

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#16018]
## Prerequisites
Make sure you have a clean profile.

## Steps to reproduce
1. From the Onboarding tour, tap on any link from the sync card, or "See what's new" card, or "Browse privately" card.
2. Tap on the tab counter.
3. Tap on the "+" to open a new tab.
4. In the search bar type some characters and then "go".
5. Repeat steps 2, and 3, then observe the background.

### Expected behavior
The Onboarding tour is dismissed and it is replaced by the home screen.

### Actual behavior
The Onboarding tour is not dismissed no matter how many tabs the user opens following the STR.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), Samsung Galaxy Tab S6 (Android 10), HTC 10 (Android 8)
* Fenix version: 10/19 Nightly, Beta 82.0.0-beta.6, RC 82.1.0-RC.2

<img src="https://user-images.githubusercontent.com/40694158/96426104-7743ca80-1205-11eb-936c-c02aefd52029.gif" width="300" height="550" />

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on:
* Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix versions: 10/26 Nightly, beta 83.0.0-beta.1, RC 82.1.1

**Comment by mcarare** [comment]
For QA, also see: https://github.com/mozilla-mobile/fenix/pull/16613#issue-522379526.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 11/27 with Samsung Note10(Android 10).
