### ISSUE TITLE
[Bug]Custom FxA server would change to default server after closing the login page

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#16015]
Build Fenix with master branch code (commit c941bd99b0fb21a60de0f884ab631f815f7a5cc3) locally.

## Steps to reproduce
1. Set up the custom servers and restart Fenix
2. Tap the button "Use email instead" to open the sign-in page, the custom setting works
![Screenshot_20201019_133724_org mozilla fenix debu](https://user-images.githubusercontent.com/33616048/96406350-d3ace700-1211-11eb-84c7-4996754c8510.jpg)

3. Tap the close icon in the bottom-left corner
4. Tap the button "Use email instead" to open the sign-in page again, the server changes to default
![Screenshot_20201019_133740_org mozilla fenix debu](https://user-images.githubusercontent.com/33616048/96406373-df98a900-1211-11eb-820a-cfb7836c7bff.jpg)

### Expected behavior
The server setting should not change.

### Actual behavior
The server setting changes.

### Device information

* Android device: Huawei Mate 10
* Fenix version: master branch commit c941bd99b0fb21a60de0f884ab631f815f7a5cc3

**Comment by rxumoz** [comment]
@st3fan Hi Stefan, I've tested in the 83 beta2 apk downloaded from github again and this bug still exists. I think it's not a bug only related to China build, but also all the custom servers.

**Comment by grigoryk** [comment]
This is mostly the same problem as https://github.com/mozilla-mobile/fenix/issues/16232 and is fixed by https://github.com/mozilla-mobile/android-components/pull/8976 (which we just uplifted to a-c 63 in https://github.com/mozilla-mobile/android-components/pull/8978)
