### ISSUE TITLE
FNX-5130 ⁃ Quick Action Toolbar Bookmark icon should have visual affordance if bookmarked

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1601]
### Why/User Benefit/User Problem
As a user, I would like to know if a page is bookmarked before I tap bookmark again, to prevent myself from creating a new bookmark #1586 or to edit the bookmark (new story?).

### What / Requirements
The quick action bar bookmark icon should not be filled in (solid black) unless I have bookmarked the page previously. 

FWIW, Fennec does the same thing. 

### Acceptance Criteria (how do I know when I’m done?)
* Pages that are not bookmarked has icon that is not filled in. 
* Pages that are bookmarked are solid colored (not just border)

**Comment by mheubusch** [comment]
@AmyYLee Can you look at this or reassign to Nicole?

**Comment by AmyYLee** [comment]
Hi, 
Here is a spec of bookmarked vs non-bookmarked states. @shorlander @ekager 

<img width="749" alt="Screen Shot 2019-04-23 at 10 48 59 AM" src="https://user-images.githubusercontent.com/5992746/56590919-df383700-65b5-11e9-924f-d66ffa9f7b7e.png">

**Comment by AmyYLee** [comment]
@ekager Just updated this bug with a colour edit.

**Comment by ekager** [comment]
Got it, thanks!

**Comment by kbrosnan** [comment]
@ekager Found #2063 while testing this.

**Comment by sv-ohorvath** [comment]
Verified on master 5/2. Remaining known issue: #2068.
