### ISSUE TITLE
[Bug] Unvisited tabs are closed when navigating away from app & back

### ISSUE THREAD

**Issue by JoshBoehm** [mozilla-mobile/fenix#16013]
### Steps to reproduce
 * Long press some links and open in a new tab.
 * Don't switch to them. 
 * Navigate to the home screen or another app. 

### Expected behavior
Opened unvisited tabs visited should persist. 

### Actual behavior
Opened unvisited tabs are closed. 

### Device information

* Android device: Samsung Galaxy S10+
* Fenix version: 81.1.4 (Build #2015768387)

**Comment by liuche** [comment]
I wasn't able to reproduce this - I opened 8 tabs in the background, swipe-closed the app, and the tabs were present when i re-opened the app.
