### ISSUE TITLE
[Bug] PR_END_OF_FILE_ERROR for https://help.nextcloud.com

### ISSUE THREAD

**Issue by michaelof** [mozilla-mobile/fenix#16012]
As issue happens BOTH on Firefox 78.3.0esr AND Firefox Daylight for Android 81.1.4, 
I add the reference to the issue for 78.3.0esr: https://bugzilla.mozilla.org/show_bug.cgi?id=1671851

* Android device: Nokia 7.2 (TA-1196)
* Fenix version: 81.1.4

**Comment by liuche** [comment]
Could you provide more details? The site seems to load fine for me. Does this work in other browsers?

**Comment by michaelof** [comment]
issue disappeared. No idea why only Firefox was affected, on all platforms I'm using (Linux, Android, iOS).
But can be closed, as there seems to be a change solving this server side.


FYI also a thread opened by me at Nextcloud's community help site: https://help.nextcloud.com/t/help-nextcloud-com-with-firefox-pr-end-of-file-error

Thanks! Michael
