### ISSUE TITLE
[Bug] Entering trailing slash after a hostname, ie 'hostname/' without protocol, should not search

### ISSUE THREAD

**Issue by jadzdotcom** [mozilla-mobile/fenix#16023]
Firefox Fenix changed the way that entering a hostname with a trailing slash (i.e. 'foo/') was handled. This is similar to a bug report in the standard Firefox reported and fixed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1083634.

## Steps to reproduce
* Enter a hostname with a trailing slash in the URL bar (i.e. 'foo/').

### Expected behavior
* Firefox opens http://foo/

### Actual behavior
* Firefox does a search for 'foo/'.

### Device information
* Android device: Android 10
* Fenix version: 81.1.4 (Build #2015768387)

**Comment by softvision-miralobontiu** [comment]
I did not reproduce this on the 1/13 Firefox Nightly build with Google Pixel (Android 10).
Entering http://foo/ in the search bar, displays the "Address Not Found" error page.
@jadzdotcom could you confirm that it works for you too?
Thanks!

**Comment by jadzdotcom** [comment]
@softvision-miralobontiu the scenario that I described is that the user enters 'foo/' into the navigation bar, not 'http://foo/'. 

My expectation and the common behaviour on (all?) other browsers is that the browser will open http://foo/ instead of doing a search.

**Comment by softvision-miralobontiu** [comment]
@jadzdotcom I was testing on the 2/15 Nightly build with Google Pixel (Android 10), and after typing the "foo/", "wiki/", or "jira/" texts in the search bar, on all three cases, the results were searches, not the pages mentioned by you.

**Comment by jadzdotcom** [comment]
> the results were searches

@softvision-miralobontiu this means that you have have confirmed the bug in the 2/15 Nightly. 

The undesirable behaviour is that it does a search. The desired behaviour is that it opens the resource. 

I re-state this only because it is still not clear to me if the desired vs undesired behaviour is understood.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/12641
