### ISSUE TITLE
FNX-466 ⁃ [Bug] Fenix gets a low dpi page on Facebook

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#1602]
Fenix (and all gv browsers) get a low dpi page on Facebook. This is because IIRC we don't provide device information in our UA. 

I know there are some talks of serving a special UA to Facebook with a fake device name so that they serve us the appropriate images, but I want to make sure we track it in Fenix too, since this is really detrimental to the user experience.

* Android device: Samsung S10
* Fenix version: Latest from Playstore

Fenix:
![Screenshot](https://user-images.githubusercontent.com/4297388/56056766-f3587a80-5d11-11e9-9198-ae742e0986ad.jpg)UNITO-UNDERSCORE!20190412-104850!UNITO-UNDERSCORE!Fenix-crop!

Chrome:
![Screenshot](https://user-images.githubusercontent.com/4297388/56056767-f3587a80-5d11-11e9-8b67-bb1c4d72ed01.jpg)UNITO-UNDERSCORE!20190412-105004!UNITO-UNDERSCORE!Chrome-crop!

**Comment by test2a** [comment]
oh yeah!!!  YOU the user are running the website on an "unsupported browser"... dont complain if the website doesnt look so pretty, now is this our fault or yours?  besides, its so cool to develop for chrome these days, everyone is doing that so why are you wasting our time by running an "unsupported browser"

**Comment by cadeyrn** [comment]
@test2a Please don't be so rude. This is an issues tracker to report issues with the Fenix browser and of course web compatibility issues with one of the most popular websites of the world are important to track. Comments of the kind that browsers other than Chrome would be unimportant are destructive.

**Comment by snorp** [comment]
Unfortunately this is a long-standing webcompat issue with Facebook. https://bugzilla.mozilla.org/show_bug.cgi?id=1232091

**Comment by sblatz** [comment]
Closing as this is reflected in Bugzilla :)
