### ISSUE TITLE
Intermittent UI test failure - No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/menuButton)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#16020]
### Firebase Test Run:
ThreeDotMenuMainTest.threeDotMenuItemsTest Flaky, failed 1/2 tries
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6768504386555427230/executions/bs.478fdb189e888817/testcases/2/test-cases
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/menuButton)
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) gr=CENTER sim={adjust=resize} ty=APPLICATION fmt=TRANSPARENT
fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED TRANSLUCENT_NAVIGATION DRAWS_SYSTEM_BAR_BACKGROUNDS
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}`
### Build: 
10/19

**Comment by sv-ohorvath** [comment]
Old bug, not failing lately. Closing

**Comment by sv-ohorvath** [comment]
The same error failed a different test:
verifyAboutFirefoxPreview: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6792307636032333853/executions/bs.226cd438365e6c3f/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Failed with the same error Master 1/4:
openHistoryInNewTabTest: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8938718047977164642/executions/bs.c9490a9ada8dc284/testcases/1/test-cases

verifyAboutFirefoxPreview: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6303712677038501074/executions/bs.551c4dc7adb7c898/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
openHistoryInNewTabTest failed again with this error on 1/28, on Master: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6495206361753611850/executions/bs.ce21636483aa82fe/testcases/1/test-cases

**Comment by AndiAJ** [comment]
`threeDotMenuItemsTest` failed on Mater 2/3: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4896994055468176177/executions/bs.471eca41658bd14e/testcases/1/test-cases

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/menuButton)`
