### ISSUE TITLE
[Bug][a11y] "Recently closed tabs" from the History page is not read

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#16027]
## Steps to reproduce
1. Browse a few pages, make sure to have some history.
2. Turn voice assistant/talkback on.
3. Go to the three-dot menu - History and navigate through the history page.

### Expected behavior
The elements are selected and read correctly, no issues encountered.

### Actual behavior
The "Recently closed tabs" option is skipped. Multiple elements are selected together and read as "today", or "last 24 hours", depending on the history available on the page. (please see the attached screenshot)

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 10)
* Fenix version: 10/19 Nightly, RC 82.1.0-build 2, Beta 82.0.0-beta.6
 
<img src="https://user-images.githubusercontent.com/40694158/96464020-04037e00-1230-11eb-89a4-0972e29f94bb.jpg" width="300" height="550" />

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly.
