### ISSUE TITLE
Missing Page Options in Fenix[Bug]

### ISSUE THREAD

**Issue by Shadowspear123** [mozilla-mobile/fenix#16025]
## Steps to reproduce

Open menu from toolbar on any site.

In fennec, there used to be an option called "Page options" which included features such as save to PDF, print, view page source, etc. These features were incredibly useful to those who used them regularly. A screenshot of the options is shown below;
![](https://forum.f-droid.org/uploads/default/original/2X/6/6d4622428235c981e00af20a042c2e52f61ac43a.jpeg)

### Expected behavior

These options are absolutely _essential_. But they are missing.

### Actual behavior

Missing features.

### Device information

* Android device: Android 8.0 Galaxy S8
* Fenix version: 81.1.3

**Comment by cadeyrn** [comment]
Save as PDF: #3709
Print: #10217
View source: #3710

By the way: Why do you give reactions to **every** of your **own** suggestions? 🤔

**Comment by Shadowspear123** [comment]
Hahahaaa 😂 self love my guy 🤗

**Comment by kbrosnan** [comment]
The major features have duplicate issues. Search is unlikely to ever live in the 3 dot menu again. For feed support there is #16024.

**Comment by metbic** [comment]
> The major features have duplicate issues. Search is unlikely to ever live in the 3 dot menu again. For feed support there is #16024.

But there is no feed support.
