### ISSUE TITLE
[Bug] Web Extension label text is not aligned with other menu items.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#16029]
First reported here: https://github.com/mozilla-mobile/fenix/pull/15884#issuecomment-712225770
![Screenshot_20201019-181601](https://user-images.githubusercontent.com/48995920/96470972-82175300-1237-11eb-8564-2f7165b08239.png)

**Comment by denschub** [comment]
@mcarare this is still an issue, do you plan on working on that, or should I ping someone else? :)
