### ISSUE TITLE
RSS support

### ISSUE THREAD

**Issue by metbic** [mozilla-mobile/fenix#16024]
Didn't see a request for this yet, so I propose it now. 

I can't view any rss feeds with fenix. 
Add-ons for this do exist, they aren't available for fenix tho. 

rss feeds, contrary to what some people at Mozilla think, are not obsolete. And a serious browser should provide its users a possibility to view them.

This is of potential importance for every single user. And I will not consider switching to fenix without rss add-on support.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8329)

**Comment by cadeyrn** [comment]
Am I right in assuming that you use RSS synonymously for feeds in general? Because Atom feeds are not less popular than RSS feeds and in fact Atom is the preferred standard…

**Comment by metbic** [comment]
@cadeyrn yes, you're right. My bad. 
Please read 'rss' as 'rss/atom' . Or simply as 'feed'.

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
