### ISSUE TITLE
copying text

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#16035]
When copying any text from the site below, fenix is constantly scrolling through or through.

lenovo k6 note android 10

https://www.hackerfactor.com/blog/index.php?/archives/896-Tor-0day-Finding-IP-Addresses.html

**Comment by reyis4402** [comment]
this is the case with many sites
Especially if you have a site of your own, editing the article is torture, fenix is constantly moving or the writing point goes to the beginning or the end

**Comment by kyrawertho** [comment]
Firefox not scrolls up or down when I try to select text over >1 line making it very difficult to copy anything.
