### ISSUE TITLE
[Bug] Attempting to select text in Thai script fails on Android and makes Fenix unable to load new pages

### ISSUE THREAD

**Issue by quazgar** [mozilla-mobile/fenix#16037]
## Steps to reproduce
1. Open any web site with Thai characters, for example https://th.wikipedia.org/ 
2. Long tap on any Thai text, as if you wanted to select some text. 

### Expected behavior

Some text is being selected.

### Actual behavior

1. No text is being selected by the long tap.
2. No text, not even with latin script, can be selected any more.
3. Loading a page in new tabs will do nothing at all.
 
### Device information

* Android device: Xiaomi Mi A2 Lite, Android 10, last system update 2020-09-01
* Fenix version: 81.1.4 (Build #2015768387), reproducible with today's nightly build (from Google Play Store)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1672269

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
