### ISSUE TITLE
Using the "Wait until first paint to show content" makes everything slow. 

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#16043]
Hey guys I'm using this setting to prevent the white flashes of pages loading when first opening the browser. However since enabling it, websites tend to take a lot longer to load. Is there any way to speed this up? I'm not sure if another fix was ever implemented for this issue.

**Comment by kbrosnan** [comment]
This is expected and why it is a hidden pref. https://bugzilla.mozilla.org/show_bug.cgi?id=1665068 and https://bugzilla.mozilla.org/show_bug.cgi?id=1670805 are work that will try to eliminate the flashes. It may require some Android-components work as well.
