### ISSUE TITLE
Need Some Add-ons

### ISSUE THREAD

**Issue by xploitednoob** [mozilla-mobile/fenix#16047]
Add This Add-ons

Cookie Manager
Bulk URL Opener
SingleFile

**Comment by kbrosnan** [comment]
Use nightly https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by xploitednoob** [comment]
@kbrosnan nightly don't have those two add-ons

**Comment by xploitednoob** [comment]
Thanks man. It help me a lot

**Comment by mohibo** [comment]
> 
> 
> Use nightly https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

thats for nightly only,not for stable

**Comment by mohibo** [comment]
> 
> 
> Use nightly https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
nightly is not a solution
