### ISSUE TITLE
[Pull To Refresh][Bug] Unexpected behavior when swiping on google maps' bottom sheet

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#16055]
## Steps to reproduce
- Access maps.google.com
- Swipe over the bottom sheet up and down

### Expected behavior
That bottom sheet should slide up and down

### Actual behavior
Our dynamic toolbar slides up and down

![PullToRefreshIsBuggy](https://user-images.githubusercontent.com/11428869/96602769-07fcd200-12fc-11eb-8507-cdd0ee0e0eb5.gif)

### Fenix version: 
- Happens in Beta (GV 82) and Nightly
- Does not happen in Release (GV 81)
 
### GV issue
https://bugzilla.mozilla.org/show_bug.cgi?id=1672204

**Comment by miDeb** [comment]
I noticed similar behavior when swiping _anywhere_ on [openstreetmap.org](openstreetmap.org), or more generally on [leaflet.js ](https://leafletjs.com/) maps.

**Comment by Mugurell** [comment]
I think this is fixed.
Our toolbar or pull to refresh are not moving when swiping over GMaps' bottom sheet.
Asking for a second confirmation from QA.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 4/23** with **Google Pixel 4 XL (11).**
