### ISSUE TITLE
Please add option to toggle whether to auto focus on the address bar when opening new tab

### ISSUE THREAD

**Issue by lwmv** [mozilla-mobile/fenix#16057]
Android Firefox v81.1.4. Every time I open new tab by clicking the big ⊕ sign, firefox will automatically focus on the address bar and open the input method for me. I remember in android firefox v80, it will just open a blank new tab and will not auto focus on the address bar. Maybe the decision of changing this behaviour is based on some telemetry data, but I guess not all users like that. So why not add an option to let me decide whether to auto focus on the address bar when opening new tab?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8369)

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla.
