### ISSUE TITLE
Main menu should work like classic Mac OS menus or other Android apps (tap and drag to open+select)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#16058]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Make the menu faster to use - instead of requiring additional taps, users can tap and drag. This also means better platform integration - see apps like Chrome, Google Messages, Signal, VLC, ScreenCam for examples of this being pervasive - it may be even a part of a standard component. 

### How do you know that this problem exists today? Why is this important?

I have seen comments about this on social media. It would make the menu more convenient. It would make Fenix feel more like a native Android app. It would help solve concrete problems like https://github.com/mozilla-mobile/fenix/issues/15138.

### Who will benefit from it?

All Fenix users who are used to standard Android behaviors.

**Comment by Poopooracoocoo** [comment]
#16004

**Comment by ekager** [comment]
closing for https://github.com/mozilla-mobile/fenix/issues/16004
