### ISSUE TITLE
[Bug] misbehaviour when pressing Android 'Menu' or 'Home' button 

### ISSUE THREAD

**Issue by ralxxx** [mozilla-mobile/fenix#16062]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1-Menu button
- Opening Firefox
- Clicking in the address bar (to make the keyboard appear)
- Clicking on Android's Menu button (square bottom key) and swap to any other app. 
Now the keyboard remains while I am able to swap to another app. 

2-Home button
- Opening Firefox
- Pressing Home button (circle bottom key)
Now the Firefox app disappears but the keyboard disappears only with quite some lag. 
  
I recorded two short videos to better visualise the current behaviour I am facing. 
  
### Expected behavior 
In short: as it was before.

1-Menu button
- When clicking the Menu button, the keyboard should hide right away. 

2-Home button
- When clicking the Home button, Firefox should hide with the keyboard at the same time.

### Actual behavior
Since Firefox For Android 81 I am facing two issues 
1-When pressing Android's Menu button swapping from Firefox to another app. the keyboard is not hiding, it stays on screen.   
2-When pressing Android's Home button (with Firefox+keyboard open) the app appears slowly in two steps: First the app, then after the keyboard
 
### Device information

* Android device: Beryllium/Poco F1 as well as Fairphone 3
* Fenix version: 81.1.5 & 81.1.4
* OS: custom ROM /  /e/OS 0.12-p-20200930 (Pie-based) & /e/OS 0.11-p-20200831

Short demo videos (links to my personal Dropbox as I cannot upload mp4)
- https://www.dropbox.com/s/wnk7msxlshy58ju/158-FF-1.mp4?dl=0
- https://www.dropbox.com/s/622c9mhnlmrshh1/159-FF-2.mp4?dl=0

Log-file
- [160_FF-3-log.txt](https://github.com/mozilla-mobile/fenix/files/5411154/160_FF-3-log.txt)

For further information on the ROM: https://e.foundation/

**Comment by Poopooracoocoo** [comment]
#14795

**Comment by liuche** [comment]
Are you seeing this on Nightly? I'm unable to repro on Nightly 10/25.

**Comment by ralxxx** [comment]
No, this is the regular Firefox.

**Comment by liuche** [comment]
Okay, that probably means it's already fixed on Nightly - you'll get the changes when that gets released! Will close this now.
