### ISSUE TITLE
[Bug] regression: long press new tab does not show top sited

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#16069]
## Steps to reproduce
long press on tab counter
new tab
### Expected behavior
see new tab with top sites and collections
![Screenshot_20201021-000636_Firefox_Nightly](https://user-images.githubusercontent.com/922368/96644226-68f2cd00-1331-11eb-9d43-ec024727e942.png)

### Actual behavior
I see the search bar focused with search engines filling the screen
![Screenshot_20201021-000628_Firefox_Nightly](https://user-images.githubusercontent.com/922368/96644146-52e50c80-1331-11eb-91f0-85c7a313ec16.png)

### Device information

* Android device: one plus 5t
* Fenix version: nightly

**Comment by andreicristianpetcu** [comment]
If I want to jump to search I can either click the search bar or press the tab counter and then the fab circle button

**Comment by Poopooracoocoo** [comment]
didn't they make this change on purpose though?

**Comment by andreicristianpetcu** [comment]
No clue if it was by design or not
