### ISSUE TITLE
[Bug] Enhanced Tracking Protection and other learn more links redirect to unmaintained beta URLs

### ISSUE THREAD

**Issue by FMJansen** [mozilla-mobile/fenix#16068]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Click the ‘Learn more’ link in the Enhanced Tracking Protection overview or the same link on an empty Exceptions view.

### Expected behavior
Open tab with this URL: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-android

### Actual behavior
Open tab with this URL: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-beta-android

### Device information

* Android device: Nokia 8 with Android 9
* Fenix version: 81.1.4 (Build #2015768387)

**Comment by ekager** [comment]
cc @jonichan could we get this to redirect like the other links that have "preview"? Or do we need to update this on our end?

**Comment by kbrosnan** [comment]
We should cleanup https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt#L35 to use `enhanced-tracking-protection-firefox-android` and see what the behavior is.

**Comment by mcarare** [comment]
@kbrosnan I have updated the link and also others that pointed to an unmaintained beta URL or a non-existent page.
I will need confirmation that does are the correct SUMO pages.
Also, I did not find any page for 
`SEND_TABS("send-tab-preview")` or `SEARCH_SUGGESTION("how-search-firefox-preview")`

**Comment by mcarare** [comment]
@kbrosnan I have also updated the link for Sync setup https://github.com/mozilla-mobile/fenix/pull/16854/files. The other ones redirect correctly.
Another problem would be with `SEARCH_SUGGESTION("how-search-firefox-preview")` and `SEND_TABS("send-tab-preview")` for which I could not identify the SUMO pages.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
