### ISSUE TITLE
[Telemetry] Include a distribution_id in telemetry

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#16075]
## Description & Product Manager / Data Scientist User Story

As a product manager/owner, I'd like to be able to distinguish in telemetry between builds from different distributors. We currently have two distributors: _Mozilla Online_ in _China_ and _Mozilla_ for the rest of the world.

In _Fennec_ we use a `distribution_id` field in telemetry that is either empty for the default distribution (Mozilla) or set to `MozillaOnline` for the installs that are distributed in China.

> Note that the _Distributor_ is not the same as the App Store where the build was downloaded. It is possible that one Distributor publishes to different App Stores. This is a concern for later and may require an additional field.

## What questions will you answer with this data?
- With this additional field we are able to add a distribution dimension to queries.

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by rxumoz** [comment]
In fact we use distribution_id in Fennec to differentiate China build from global builds. All the China build apks sent to different app stores share with the same distribution_id: _MozillaOnline_

**Comment by rxumoz** [comment]
For now distribution_id is the main demand for China build.
Another secondary request is to track the apk's installer source,  maybe preferably in core ping. See https://github.com/mozilla-mobile/fenix/issues/11458

**Comment by st3fan** [comment]
@travis79 is suggesting we move this to the Glean internal metrics very much like `channel` is a _core_ field. This would result in the this field being available on pings and easily initialized during app startup. I think that sounds appropriate.

**Comment by rxumoz** [comment]
Is there any update?

**Comment by rocketsroger** [comment]
## Request for data collection review
1.	What questions will you answer with this data?
This data helps us distinguish in telemetry between builds from different distributors.
2.	Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
Yes, this gives us an insight on methods of distribution.
3.	What alternative methods did you consider to answer these questions? Why were they not sufficient?
No alternative is available to answer this question.
4.	Can current instrumentation answer these questions?
No current instrumentation can answer this question.
5.	List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.

Measurement Description | Data Collection Category | Tracking Bug 
-- | -- | --
Crash is fatal/non-fatal | category 1 - technical data | #16075

6.	Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
https://github.com/mozilla-mobile/fenix/blob/master/docs/metrics.md
7.	How long will this data be collected? Choose one of the following:
I want to permanently monitor this data. (Roger Yang)
8.	What populations will you measure?
No filters - all locales, channels, etc.
9.	If this data collection is default on, what is the opt-out mechanism for users?
Default Glean SDK opt-out mechanism.
10.	Please provide a general description of how you will analyze this data.
Data science team will use this data to gain insight on methods of distribution.
11.	Where do you intend to share the results of your analysis?
Internally in the fenix/android-components/data science teams.
12.	Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
No third-party tool will use this data.

**Comment by chutten** [comment]
PRELIMINARY NOTES:
Why "Distribution ID" instead of "Distributor Name" or "Distributor"? "ID" to me suggests a UUID or a number or something that maps to something else, whereas the domain of this collection appears to be some small number of plain English labels. (( Doesn't matter for the review, just curious ))

DATA COLLECTION REVIEW RESPONSE:

    Is there or will there be documentation that describes the schema for the ultimate data set available publicly, complete and accurate?

Yes.

    Is there a control mechanism that allows the user to turn the data collection on and off?

Yes. This collection can be controlled through Fenix's Preferences.

    If the request is for permanent data collection, is there someone who will monitor the data over time?

Yes, Roger Yang is responsible.

    Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1, Technical.

    Is the data collection request for default-on or default-off?

Default on for all channels.

    Does the instrumentation include the addition of any new identifiers?

No.

    Is the data collection covered by the existing Firefox privacy notice?

Yes.

    Does there need to be a check-in in the future to determine whether to renew the data?

No. This collection is permanent.

---
Result: datareview+

**Comment by rocketsroger** [comment]
> Why "Distribution ID" instead of "Distributor Name" or "Distributor"? "ID" to me suggests a UUID or a number or something that maps to something else, whereas the domain of this collection appears to be some small number of plain English labels. (( Doesn't matter for the review, just curious ))

My understanding is that this is due to historical reasons.  Fennac used to send the same value through Distribution ID.  I think this is why data science team requested the same field name.

**Comment by st3fan** [comment]
Maybe @rxumoz and @bli-mozbj can weigh in here?

**Comment by bli-mozbj** [comment]
> 
> 
> > Why "Distribution ID" instead of "Distributor Name" or "Distributor"? "ID" to me suggests a UUID or a number or something that maps to something else, whereas the domain of this collection appears to be some small number of plain English labels. (( Doesn't matter for the review, just curious ))
> 
> My understanding is that this is due to historical reasons. Fennac used to send the same value through Distribution ID. I think this is why data science team requested the same field name.

I'm afraid I don't have a better answer, sorry for that.
Distribution ID had been used in Fennec before I took over Fennec China build releated work _(maybe even before I jonined Mozilla)_. So based on my understanding, it's more like a historical issue.

**Comment by chutten** [comment]
No worries, it's just one more oddity in the data. Without clear guidance on how we should name things, it makes sense to maintain consistency.

Now of course Krupa is working on that "clear guidance on how we should name things" so maybe this will change for the better in the medium term : )

**Comment by AndiAJ** [comment]
Hi, **verified as fixed for "The rest of the world"** on both the latest **`Nightly 201211`** and **`84.1.0 RC2 `** using a Google Pixel 3a (Android 11)
However, I **wasn't able to simulate the  `Mozilla Online` distributor for China.**

<details>
    <summary> ✔️ Nightly (▼dropdown)</summary>

Metrics Ping  - **be7f254c-ccef-4096-8b35-cb483ce1c5cd**
`"metrics.distribution_id": "Mozilla"`

[Logcat](https://github.com/mozilla-mobile/fenix/files/5679348/disn.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t112000)


</details>


<details>
    <summary> ✔️ 84.1.0 RC2 (▼dropdown)</summary>

Metrics Ping  - **1da6bb92-3a4b-4b5a-a3a5-e6bea2dda6c8**
`"metrics.distribution_id": "Mozilla"`

[disr.txt](https://github.com/mozilla-mobile/fenix/files/5679435/disr.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t11200)

</details>

**Comment by rxumoz** [comment]
Hi, I've tried Glean Debug ping viewer to verify this (apk built with releases/v84.0.0 branch && set _mozillaOnline_ in local.properties).
`"metrics.distribution_id": "MozillaOnline"`
https://debug-ping-preview.firebaseapp.com/pings/rxu-dev-metrics

@bli-mozbj will also check it on https://sql.telemetry.mozilla.org asap.

**Comment by bli-mozbj** [comment]
Hi, I've checked on Telemetry, and got the following results:
