### ISSUE TITLE
Support CSS cursor property

### ISSUE THREAD

**Issue by saschanaz** [mozilla-mobile/fenix#16072]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Fenix does not support CSS `cursor` property so users can be confused about whether something is clickable or not.

### How do you know that this problem exists today? Why is this important?

1. Open https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
2. Hover over the example and see whether cursor changes.
3. It does not

### Who will benefit from it?

Android users with mouse e.g. Samsung Dex users

**Comment by kbrosnan** [comment]
Moved to Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1672609
