### ISSUE TITLE
FNX-52 ⁃ [Telemetry] Handle custom search engines, do not leak user-added engines

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#1607]
Owner: Product Manager

This is a follow-up to the telemetry that was added in #1194 and #800. When users gain the ability to add Custom Search Engines, we need to update that telemetry so the new search engines are obfuscated (and sent as "custom" or some other non-user-generated string).

#### Description & Product Manager / Data Scienties User Story
* As a User, I don't want the names or search urls of custom search engines I add to be collected.

#### Hypothesis
* It will be sufficient to know that users are using "custom" engines, and details of the engine don't need to be sent.

#### What questions will you answer with this data?
Whether users are using custom search engines

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
Filing pre-emptively to track future work

#### What probes (suggested, if applicable)
* Send "custom" as search engine name, shortcut, or url if user is using that, instead of the name of the "bundled" search engines

### Acceptance Criteria (Added by PM)
* Event pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by liuche** [comment]
@vesta0 this isn't an MVP, but there are a couple of search engine telemetry probes that now exist, and I just want to make sure that when custom search engines are added this reminder is here that those probes need to be updated to not send things like "search engine name".

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **Nightly Build #20060605 from 01/06** using a Google Pixel 3a (Android 9).

### Shortcuts
❓ Search - Ping 066a5899-af3e-43a5-b10b-c067ce128082
✔️ Baseline - Ping 034d2eaa-87ff-4294-8403-5e4c46d371e6
❓ Suggestion - Ping 9a383cba-b6bf-4359-a64d-7a2edffa73ef
✔️ Baseline - Ping 7ddd5ccb-7cab-4072-b80a-8657fbb35a1c

### Set Custom Search Engine as Default
✔️ Search - Ping 62aa8920-ef77-4d3a-8092-9afd7ac1e049
✔️ Baseline - Ping cea31cfc-4418-497f-ba93-3b9d5fbaf567
✔️ Suggestion - Ping c04d5f7f-001a-42f0-86d1-88c0407d9ef3
✔️ Baseline  - Ping 02e92874-6fae-48f2-859a-26d6f3dd2597

✔️ Metrics - Ping c2da4015-e19e-4d4f-bad5-d814ff149c36

## Summary 

### ❓ Event type pings
When using the Custom Search Engine from the "Shortcuts" section the generated **event** type pings actually display the name of the "bundled" search engines, in this case "Imdb".

E.g.
{
          "category": "search_shortcuts",
          "extra": {
            **"engine": "Imdb"**
          }

### ✅ The baseline pings are properly generated.
E.g. Baseline ping after performing a **Search using the Custom Search Engine from the "Shortcuts section"** 
"metrics": {
        "counter": {
          "events.total_uri_count": 1
        },
        "labeled_counter": {
          "metrics.search_count": {
            **"custom.action": 1**
          }

E.g. Baseline ping after performing a **Suggestion search using the Custom Search Engine from the "Shortcuts section"**
"metrics": {
        "labeled_counter": {
          "metrics.search_count": {
            **"custom.suggestion": 1**
          }
 

### ✅ Metrics pings are properly generated.
E.g.
"metrics.search_count": {
"custom.action": 2,
"custom.suggestion": 2
}

[Logcat](https://github.com/mozilla-mobile/fenix/files/4026111/CustomSearch.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test060101)

@boek - Please review and let me know how should we proceed. ☺️ 
**I'll remove the QA needed until further notice.**

**Comment by AndiAJ** [comment]
Hi, verified as fixed on **Fenix Beta 3.2.0-beta. 2 #20230233 from 01/23** using a Google Pixel 3a XL (Android 10)

Set Custom Search Engine as Default
✔️ Search - Ping **260894ed-84b6-4777-b07c-5fff5f22fb35**
✔️ Baseline - Ping **1a048ab8-c173-40d2-aef5-ea85e9ed4048**
✔️ Suggestion - Ping **18bd7e99-36da-4ee3-9953-5d834a371655**
✔️ Baseline - Ping **a3361ffa-6e34-47be-924f-0a58143c3921**


Shortcuts
✔️Search - Ping **f18d3fef-0678-4468-8239-670534b547e4**
✔️ Baseline - Ping **31e4393b-f6ca-4473-95cd-2e471ee73dcd**
✔️ Suggestion - Ping **593ba385-fde2-4d55-bb0b-58fa724989f8**
✔️ Baseline - Ping **98ac9ab5-318d-4d90-b9c0-9e539ead8a62**

[Logcat](https://github.com/mozilla-mobile/fenix/files/4101982/CSL.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t230105)
