### ISSUE TITLE
Collections, visual regression on home

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#16084]
There is a visual regression when you unfold a collection on home (see image)

![Screenshot (Oct 20, 2020 12:31:59 PM)](https://user-images.githubusercontent.com/353960/96717517-e278d280-13a6-11eb-8bd1-3404dda16fbe.png)

**Comment by gabrielluong** [comment]
This is about the box shadow / elevation between Collection and the items.

**Comment by liuche** [comment]
cc @ekager

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both latest **`Nightly Build 201022`** and **`Firefox RC 83.0.0-beta.1`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshots
![rsz_screenshot_20201022-120430](https://user-images.githubusercontent.com/51314259/96850253-465ed200-145f-11eb-8b8b-c1c8252d7166.png)
