### ISSUE TITLE
[Pull To Refresh][Bug] Can't use pull to refresh properly on cisco.com

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16085]
## Steps to reproduce
1. Navigate to cisco.com
2. Try using the pull to refresh gesture on the image slider

### Expected behavior
Pull to refresh and the dynamic toolbar are not animated. They do not show when scrolling on inner carousels.

### Actual behavior
The icon got displayed 1x from the image slider, but didn't refresh the page. 
It only remained stuck on the screen

### Device information

* Android device: 
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly 201021
 
### Notes
✔️ Works on Chrome
Related to #16054 and #9766  

► Video
![YouCut-20201021-151249047](https://user-images.githubusercontent.com/51314259/96719210-c9c1ea00-13b1-11eb-96a0-4581bf6a5887.gif)

► Video **stuck pull to refresh icon**
![YouCut-20201021-151641482](https://user-images.githubusercontent.com/51314259/96719075-9bdca580-13b1-11eb-8522-426d58254cb7.gif)

**Comment by Mugurell** [comment]
Pull to refresh and the dynamic toolbar are functioning correctly here.
They will not animate for swipes on iframes or on scrollable divs and the like.

Will repurpose this ticket to focus on the throbber being stuck.

**Comment by Mugurell** [comment]
Seeing that both pull to refresh and the dynamic toolbar are working on Chrome when swiping over that carousel maybe we should get an update from @snorp if there are any plans for us to do the same..

**Comment by agi** [comment]
I just tested and I can pull to refresh in Fenix nightly on cisco.com, did they change the code or did we fix things? @Mugurell do you know?

**Comment by Mugurell** [comment]
Thank you @agi!
Seems like the webpage changed in the meantime.
Yay us!

I still have a question about if we should trigger pull to refresh if the user scrolls down over horizontal carousels.
If I understand other browsers do it...
I'll ask hiro on the https://bugzilla.mozilla.org/show_bug.cgi?id=1678505

**Comment by hiikezoe** [comment]
> Thank you @agi!
> Seems like the webpage changed in the meantime.
> Yay us!
> 
> I still have a question about if we should trigger pull to refresh if the user scrolls down over horizontal carousels.

Yes, it should be unless the site does preventDefault() in touchstart event handlers. I suppose this case GV should return INPUT_RESULT_HANDLED with SCROLLABLE_NONE and OVERSCROLL_HORIZONTAL|OVERSCROLL_VERTICAL (I hope scroll handoff works properly there).

**Comment by Mugurell** [comment]
@AndiAJ I see the website structure has changed in the meantime and the issue reported for `cisco.com` does not exist anymore.
Can you confirm and close the issue?

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 98.0a1 (2022-02-04).
Pull to refresh works as expected.

Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Oppo Reno 6 (Android 11).
- Google Pixel 4 (Android 12).

Closing the ticket as verified fixed.
