### ISSUE TITLE
FNX-5131 ⁃ Show a title bar at the bottom when the address bar is no longer visible

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1608]
### Why/User Benefit/User Problem
It allows users to know the website they are in, without having to check it again, specially when there are many tabs open. IMHO it's one of the best features of Yandex Browser.

### What / Requirements
A title bar at the bottom that appears when the user scroll down the page and the address bar is no longer visible

### Acceptance Criteria (how do I know when I’m done?)
A title bar is exhibited when scrolling down.

**Comment by yoasif** [comment]
Can you post a screenshot of how it looks in Yandex browser? I am curious to see what it looks like.

**Comment by Lululalu** [comment]
@yoasif 

![Screenshot_20190412-194155_Browser](https://user-images.githubusercontent.com/32398857/56069819-2bd07680-5d5b-11e9-8c25-1da462cd86ca.jpg)

**Comment by yoasif** [comment]
Not sure I understand the feature, though - do you want to not show the address bar when the user makes a scroll down gesture and instead show the page title? 

Showing the toolbar is what currently happens in Fenix for me.

**Comment by Lululalu** [comment]
@yoasif Sorry if I couldn't describe it better before (English is my secondary language). I recorded how the bottom bar/tittle bar behaves in Yandex, as a video may be between than words.

https://streamable.com/eoxlf

**Comment by yoasif** [comment]
Got it - that helps!

**Comment by cadeyrn** [comment]
To be honest I don't see any good reason to implement this proposal. If I scroll a website I already know on which website I am. And the space is limited on smartphones and I can scroll to see the toolbar. In my opinion there is no reason for an always visible bar with the page title.

**Comment by vesta0** [comment]
Thanks for the suggestion. We are currently exploring different use cases for the bottom toolbar and will take this into consideration!
