### ISSUE TITLE
[Bug] Rename "Report Site Issue" in "Report site issue"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16082]
## Steps to reproduce 
1. Open a page, then the three-dot menu.
2. Observe the "Report Site Issue".

### Expected behavior
The option should be "Report site issue" as all the other options.

### Actual behavior
The option has capital letters "Report Site Issue".

### Device information
* Android device: all
* Fenix version: 10/21 Nightly

**Comment by liuche** [comment]
@Delphine what should we do about string capitalization changes? should we create a new string id?

@violasong since you're looking at menu items, are you okay with us matching capitalization across the menu items?

**Comment by gabrielluong** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/11631

**Comment by kbrosnan** [comment]
This code is from https://github.com/webcompat/webcompat-reporter-extensions I don't think we directly control it.

**Comment by s-ankur** [comment]
For me it says "Report Site Issue... even though there is space. Is it a bug?

**Comment by mcarare** [comment]
Like @kbrosnan said, we do not directly control the code for the extension. But, for the title issue, it might be possible to tweak them in AC to follow a certain capitalization rule. That means, we do not change the title, so no new string should be necessary. 
Also, this change would be applied to all extensions that still reside in the extensions sub-menu.

**Comment by amkcpu** [comment]
I'm not sure that setting a capitalization rule for all extensions is a good idea. If this, for example, were set to uppercase the first word and lowercase all others, `uBlock Origin` would turn into `Ublock origin`.

I would prefer having webcompat change this string to `Report site issue` (also removing the ellipses at the end).

**Comment by mcarare** [comment]
@amkcpu We can surely handle keeping `uBlock Origin` or `uBlock origin` if it's intended. The only issue is getting UX decisions regarding capitalization in Extensions versus menu capitalization. Currently, there is no consistency in this matter.

**Comment by Delphine** [comment]
> @Delphine what should we do about string capitalization changes? should we create a new string id?
> 

No need to create new string id for capitalization changes, thanks!

**Comment by apbitner** [comment]
Tagging @betsymi for her input

**Comment by betsymi** [comment]
Great catch @softvision-miralobontiu! @mcarare The names of extensions themselves should be capitalized because they are proper nouns. Menu capitalization is sentence case, per Material design guidelines. `Add to Home screen` is a tricky outlier, because `Home screen` is an Android term.

**Comment by liuche** [comment]
It looks like the webcompat repo where this string/capitalization come from matches Desktop settings convention, so we wouldn't be able to ask them to change it, likely. If we want to fix this, we would need to do capitalization changes on our side. Not sure how important this is, given the extra code and possible side effects.

**Comment by lobontiumira** [comment]
This is still reproducible on the 4/28 Nightly build with Sony Xperia Z5 Premium (Android 7.1.1).
