### ISSUE TITLE
Disabling open links in external apps not working

### ISSUE THREAD

**Issue by daozhihun** [mozilla-mobile/fenix#16083]
The setting "open links in external apps" seems to have no effect.
I have ensure this setting is turned off, but the system still launch apps for many websites.

System: Android 10
Browser: Firefox for Android 81.1.5

**Comment by kbrosnan** [comment]
Open in app matches installed apps with URIs that the app claims. For example https://youtube.com will send you to the Youtube app. Websites can still direct users to the app using an `intent://` URI. An example of this is m.facebook.com sending people to the Messenger app when tapping on the Messenger icon in m.facebook.com.

**Comment by tortino** [comment]
please reopen and fix it
