### ISSUE TITLE
[Pull To Refresh][Bug] Pull to refresh doesn't work on lifehacker.com menu

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16086]
## Steps to reproduce
1. Navigate to lifehacker.com
2. Tap the ☰ button
3. Use the pull to refresh gesture 

### Expected behavior
Pull to refresh works properly.

### Actual behavior
Doesn't work

### Device information

* Android device: 
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly 201021
 
### Notes
✔️ Works on Chrome
Related to #16054 and #9766  

► Video
![20201021-154844](https://user-images.githubusercontent.com/51314259/96721748-3ee2ee80-13b5-11eb-892f-10af078c16fa.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8409)

**Comment by liuche** [comment]
Linking to #9766

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01. Scrolling back up from the bottom of the webpage's hamburger menu will refresh instead of scrolling to the top though.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 102.0a1 (2022-05-09) build.
Device used: Google Pixel 4 (Android 12).
(I did manage to activate the pull to refresh action, but after the initial success, I couldn't reproduce it anymore).

**Comment by SoftVision-LorandJanos** [comment]
Reproducible on the latest Nightly (109.0a1) using an Oppo Find X5 (Android 12).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807076

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
