### ISSUE TITLE
[Bug] "USERTrust RSA Certification Authority" is not trusted on Android but is on Desktop

### ISSUE THREAD

**Issue by glawrence** [mozilla-mobile/fenix#16080]
## Steps to reproduce
Open Firefox for Android 81.1.5
Navigate to https://www.sheffield.gov.uk

### Expected behavior
Webpage should display

### Actual behavior
Firefox does not trust because its certificate issuer is unknown, the certificate is self signed or the server is not sending the correct intermediate certificates.

![Screenshot_20201021-095015](https://user-images.githubusercontent.com/1067355/96700501-6b801180-1387-11eb-91e0-59ee7824b2fe.png)

It is worth noting that this works fine in Firefox 82.0 on Windows 10 and macOS

### Device information

* Android device: Nokia 8.3 5G, running Android 10 with 1-Sep-2020 security patch/update
* Fenix version: 81.1.5

**Comment by s-ankur** [comment]
Able to reproduce on nightly as well

**Comment by Amejia481** [comment]
I opened t[his bug on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1672402) for the GV team to take a look

**Comment by glawrence** [comment]
Thanks @Amejia481 much appreciated, I have seen the updates on there

**Comment by kbrosnan** [comment]
Broken cert chain. Might use the Bugzilla bug for intermediate preloading.

**Comment by jcjones** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=www.sheffield.gov.uk shows the server as misconfigured with an incomplete chain.
