### ISSUE TITLE
[Bug] Weird keyboard behavior

### ISSUE THREAD

**Issue by Afechad** [mozilla-mobile/fenix#16091]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)

For the past couple of days I've noticed a weired keyboard behavior on some sites.

First, keyboard is not minimized when I enter the page.

Second, when triying to type a message, touching a single letter will paste plenty of random words.

Does anybody else enconter this problem?

I've tried a different browser, but it happenes only on Firefox nightly.

P.s. I'm using Google keyboard.

### Device information
* Android device: ?
Xiomi redmi note 8 pro, Android 10, mui 12
* Fenix version:
Nightly 201020 17:01 (Build #2015770827)
AC: 63.0.20201019143159, b78b41f98
GV: 83.0a1-20201018211631
AS: 63.0.0

**Comment by andreicristianpetcu** [comment]
I'm having the same issue with hacker's keyboard
OnePlus 5t
LineageOS 16
Nightly

**Comment by s-ankur** [comment]
related issue https://github.com/mozilla-mobile/fenix/issues/15855

**Comment by Cheap-Skate** [comment]
I have the first issue (keyboard does not dismiss). It started a few days ago. It might be related to typing in a text entry field (like I am doing now). I will try to find STR
