### ISSUE TITLE
[Bug] tg language sign_in_create_account_text has incorrect <u> formatting

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#16097]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values-tg/strings.xml#L1202

This is improperly formatted html text:
`![CDATA[Ҳисоб надоред? <u> Барои танзими ҳамоҳангсозӣ байни дастгоҳҳо <u>ҳисоберо эҷод намоед</u>]]`

and shows more of the text underlined than other locales

* Fenix version: Nightly 10/21

**Comment by liuche** [comment]
cc @Delphine

**Comment by Delphine** [comment]
I don't see this string like that at all in Pontoon ([see how it's not formatted at all the same](see how it's not formatted at all the same)).
According to Pontoon history, I don't see that string has ever been localized this way.
Are we sure we're seeing the latest pull from Pontoon? Not sure where this comes from :/

**Comment by Delphine** [comment]
(Note: does this maybe come from the fact that this is [the string we had to update mid-way](https://github.com/mozilla-l10n/android-l10n/pull/274#discussion_r491250296), but didn't change the string ID? Not sure if this is related to yesterday's discussion or not...)
