### ISSUE TITLE
Shortcuts frequently used sites

### ISSUE THREAD

**Issue by hallgrimur13** [mozilla-mobile/fenix#16090]
When i press the adress line (where the adress for the current site in in is) it used to show me the shortcuts to my most used sites, now it just stays on the same page and i have to type in the link manually. Is this a bug or intended? And is there a way to change it so it functions as it did in the previous version?

**Comment by liuche** [comment]
if you open a new tab, your most used sites will show up on that screen - you need to dismiss the keyboard.

**Comment by hallgrimur13** [comment]
I mean when i allready have a page open and then tap the adress
