### ISSUE TITLE
[Bug] weird sticky keyboard pop up behaviour

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16106]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Click on a textbox, 
Scroll down till url hides (the keyboard does not hide)
Click on any link on the page

### Expected behavior
Nothing
### Actual behavior
Keyboard now pops up on every page load, forever. Without any reason
### Device information

* Android device: Asus Zenfone
* Fenix version: nightly

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1673511

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by amedyne** [comment]
[s-ankur](https://github.com/s-ankur) can you provide a specific site where you experienced this? I can't seem to reproduce this on Fenix nightly. 

Nightly 201027 17:01 (Build #2015772171)
AC: 64.0.20201027134712, 3bc485151
GV: 84.0a1-20201026092834
AS: 63.0.0
