### ISSUE TITLE
[Bug] History tests fail with A-C, GV update (master not affected): Duplicated entry

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#16115]
All tests, except for noHistoryItemsInCacheTest in [HistoryTest ](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt)suite have failed 2/2 in Firebase not intermittent.

## Steps to reproduce
Running the tests it happens the first time you follow these steps:
Visit one place
Go to History

Manually the history item appears twice the second time you go to the site or when you refresh the page and then open History again

### Expected behavior
There is one entry for History for each site visited at a time

### Actual behavior
The website visited appears twice in History. 

### Device information
  * Android device: Pixel 3, API28
  * Fenix version: release v83.0.0 branch and [PR](https://github.com/mozilla-mobile/fenix/pull/16094) to update A-C to 64.0.20201020190149

**Tests affected:**
copyHistoryItemURLTest
deleteAllHistoryTest
deleteHistoryItemTest
deleteMultipleSelectionTest
multiSelectionToolbarItemsTest
openHistoryInNewTabTest
openHistoryInPrivateTabTest
openHistoryItemInNewPrivateTabTest
openHistoryItemInNewTabTest
shareButtonTest
shareHistoryItemTest
visitedUrlHistoryTest

**Beginning of stacktrace:**
 androidx.test.espresso.AmbiguousViewMatcherException: 'with id: org.mozilla.fenix.debug:id/overflow_menu' matches multiple views in the hierarchy.
Problem views are marked with '****MATCHES****' below.
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f14032d
fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND
vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@6d57375, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
| 
....
Complete [Firebase log](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6475269486009643214/executions/bs.eb0af14ce62deaa3/testcases/1/test-cases) for one of the failing tests

**Comment by csadilek** [comment]
This was a regression in GV 84.0.20201021095128, which is fixed in today's GV 84.0.20201022093646. We're currently publishing a new A-C to upgrade. Verified that the tests pass with the version. No change needed in Fenix.
