### ISSUE TITLE
[Bug] Report Site issue is black indark mode  

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16110]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Use dark mode
Open 3 dot menu
### Expected behavior
The icon is white, like the rest. May also be a accessibility issue
### Device information

* Android device: ?
* Fenix version: ?

**Comment by sflorean** [comment]
Thanks for the report! The issue is already filed here #11367. I will close as a duplicate.
