### ISSUE TITLE
Firefox 安卓不是才68.11.0吗，这里怎么都83.0.0版本了？

### ISSUE THREAD

**Issue by 1265578519** [mozilla-mobile/fenix#16119]
Firefox 安卓不是才68.11.0吗，这里怎么都83.0.0版本了？
https://support.mozilla.org/zh-CN/kb/%E5%9C%A8%E6%89%8B%E6%9C%BA%E6%88%96%E5%B9%B3%E6%9D%BF%E4%B8%8A%E5%AE%89%E8%A3%85Firefox

**Comment by kbrosnan** [comment]
The Mozilla Online team is work on this. When they have a build that is ready it will be released.
