### ISSUE TITLE
[Bug] The Firefox logo is covered when toolbar is set to the top and there is a link in clipboard

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16114]
## Steps to reproduce 
1. Set the toolbar to the top.
2. Make sure the "Show clipboard suggestions" toggle is enabled in Settings - Search.
3. Copy an URL and open a new tab.
4. Observe the home page and the Firefox logo.

### Expected behavior
The Firefox logo/icon is displayed fully, in the background.

### Actual behavior
The Firefox logo/icon is partially covered by the "Fill link from clipboard [URL]" option.

### Device information
* Android device: all
* Fenix version: 10/22 Nightly, RC 82.1.0-rc.1, Beta 83.0.0-beta.1

![logo](https://user-images.githubusercontent.com/40694158/96871759-60a6a900-147b-11eb-878d-df166ddb0dca.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8442)

**Comment by Mugurell** [comment]
Not sure there's anything to do here, if the original UX intent is to somehow synchronize widgets' positions or just show this "enter url UI" over anything that's already displayed.
Asking UX for feedback.

**Comment by apbitner** [comment]
@Mugurell what do you think the level of effort would be to adjust the home screen content so that it's all visible in this scenario?

**Comment by mcarare** [comment]
@apbitner I think the change that could possibly fix this issue would not be a trivial one, as the logo and clipboard are in different windows, not in the same one. Also, do you think this could still be an issue with the home screen changes? If not, maybe the effort to fix a temporary issue is not worth it.

**Comment by lobontiumira** [comment]
Still reproducible on the 6/7 Nightly build with Samsung Galaxy Note 8 (Android 9).

**Comment by pwhitbread** [comment]
This is causing me an issue; not because it covers the logo but because it blocks access to the private browsing toggle. So whenever I've copied a url because I want to re-open it in a private session, I have to use the back button to exit entry before I can switch mode.  Admittedly it's only a single extra UI interaction but a fix would improve the experience.

**Comment by lobontiumira** [comment]
Still reproducible on 11/2 Nightly build with Sony Xperia Z5 (Android 7.1.1).
