### ISSUE TITLE
Top sites pin on home needs new colors

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#16122]
The pin that appears on home for added top sites doesn't have enough contrast. Please update it to the following colors:

light theme
`<color name="ink_20">#312A65</color>`

dark theme
`<color name="violet_50">#9059FF</color>`

**Comment by jawz101** [comment]
That would be annoying.  Why not just get rid of the pins

**Comment by Dunexus** [comment]
@jawz101 If you get rid of the pins, how are you supposed to differentiate pinned from top sites filled from history ?

**Comment by sflorean** [comment]
Verified as fixed on Nightly 10/27 with Samsung Galaxy Note10 (Android10). Checked both dark and light mode.
