### ISSUE TITLE
[Bug] On Anbox (emulator), only every 10th swipe is recognized

### ISSUE THREAD

**Issue by danielzgtg** [mozilla-mobile/fenix#16139]
### Steps to reproduce

1. Go to any website, for example https://www.wikipedia.org/
2. Try to scroll with the touchscreen

### Expected behavior

For Fenix to recognize all my touchscreen swipes.

The swipes scroll fine on the new tab page, the Fenix settings pages, as well as the Android settings app. They also work when using a touchpad or mouse instead of the touchscreen.

### Actual behavior

The first 9 touchscreen swipes are ignored. If the bottom chrome happens to be hidden, it will slide back up and become visible. Only the 10th swipe actually causes the page to be scrolled. The cycle repeats for further swipes. Additionally, taps have a similar problem.

### Device information

* Android device: Anbox built at https://github.com/anbox/anbox/tree/170f1e029e753e782c66bffb05e91dd770d47dc3 with https://build.anbox.io/android-images/2018/07/19/ (anbox_x86_64-userdebug 7.1.1 N6F26Q eng.root.20180719.172237) running on X11 on Ubuntu 20.04.1 LTS on linux-surface 5.8.15-surface on a Microsoft Surface Pro 7.
* Fenix version: 82.1.1 (Build # 2015770927) from https://github.com/mozilla-mobile/fenix/releases/download/v82.1.1/fenix-82.1.1-x86_64.apk

**Comment by liuche** [comment]
I'm having trouble reproducing on my device. Do you have any idea why this might be happening to you, is it a device-specific problem? Do you see this on a phone-installed Fenix?

**Comment by danielzgtg** [comment]
This does not occur on my OnePlus 7 Pro. This bug is specific to the interaction between Anbox and Fenix

**Comment by liuche** [comment]
When you're using other browsers on Anbox, you're not seeing this problem regardless of the site?

**Comment by danielzgtg** [comment]
This does not happen with the preinstalled "WebView Browser Tester".

I tried to, but could not get Chrome, Jelly, Opera, Brave, or Vivaldi working.

I don't see this problem in [Fennec](https://www.apkmirror.com/apk/mozilla/firefox/firefox-61-0-release/firefox-browser-fast-private-61-0-android-apk-download/), so this is a regression
