### ISSUE TITLE
[UX] Tabs sorting

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16130]
Adding sorting action to tabs tray in dropdown menu (every proposed sorting action can be broken into it's own ticket -> manually, by date, by address, by topic). What we currently do is similar to "by date" but it also opens child tabs with their parent.

## Dependencies
 #11376

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8459)

**Comment by liuche** [comment]
We have a few more UX questions to resolve around sorting.

Will file a ticket and pull into sprint.

**Comment by eliserichards** [comment]
Waiting on #16408

**Comment by koshkas1** [comment]
Gnew update yesterday even made this worse as new and newer tabs open at bottom instead of top and you cant change that. Lots more scrolling to find taba..ugh

**Comment by jhpratt** [comment]
Keeping this open.

**Comment by Dakkaron** [comment]
This is the most basic feature that blocks me from upgrading to a modern Firefox on Android.

Sorting tabs is such an essential feature. Without it it is e.g. incredibly difficult to compare different products in the browser.

**Comment by AbsurdlySuspicious** [comment]
nope

**Comment by Dakkaron** [comment]
Just because noone fixes this, doesn't mean that it's not an incredibly useful feature.

**Comment by cadeyrn** [comment]
@Dakkaron: You can already sort tabs in Firefox Nightly if you disable the tab groups feature. I don't know if sorting by "topic" or "address" is really the "most basic feature" of a browser…

**Comment by DieterR74** [comment]
I tried ordering tabs in Firefox Nightly today and it worked perfectly for me. I would very much like to see this feature back in the normal version. Also: Reloading a page by dragging it down would be great in the normal version of Fenix. When comparing to Chrome or Brave, these are features that are simply missing.

**Comment by boek** [comment]
Dup of #19231
