### ISSUE TITLE
Adding collection pill buttons that show collections as list to tabs tray

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16131]
Mocks: https://www.figma.com/proto/aPGQdivRyiIbP31uwef3de/Collections-v2-Library?node-id=323%3A1&viewport=-188%2C460%2C1&scaling=scale-down

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8460)

**Comment by s-ankur** [comment]
Why not "All" instead of "Unsorted"?

**Comment by ekager** [comment]
![Uploading image (1).png…]()

**Comment by amedyne** [comment]
Removing this from the board until there are more details on next steps regarding this task.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812894

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
