### ISSUE TITLE
Revise multiselect mode UI

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16132]
Mocks: https://www.figma.com/file/luMaQYjwiMtQM5xQ30P9yP/Tabs?node-id=329%3A489

## User Story
- As a user, I want … so I can do … (keep it problem-centric)

## Dependencies
- List dependencies on other issues/teams etc.

### Acceptance Criteria
- I can do …  (e.g. add a bookmark)

**Comment by ekager** [comment]
Shall I open a ticket for new telemetry for these new menu items?

Also one remaining question @topotropic  - should multiselect still only be for normal, non-private tabs since we've added more options here?

**Comment by topotropic** [comment]
Can you ping me on the telemetry ticket in case you open one? Thanks!

Let's keep it for non-private tabs for now (if feasible – let me know if this adds work). Thanks!

**Comment by softvision-miralobontiu** [comment]
Verified on the 11/16 Nightly build with Samsung Galaxy Tab S6 (Android 10), that the tabs tray has the "Select tabs" button under the opened tabs.
After the "Select tabs" button is tapped, the selection screen displays the new UI:
- the number of selected tabs,
- the "save to collection" icon,
- the "share" icon,
- the three-dot menu with the "Bookmark", and "Close" options,
- the opened tabs in list view, or in grid view,
- the purple checkmark on the selected tab.

![selection screen](https://user-images.githubusercontent.com/40694158/99237118-b9f6c380-2800-11eb-9218-aa704cc7b0ba.png)
