### ISSUE TITLE
Send/Share a URL to Chrome

### ISSUE THREAD

**Issue by liar666** [mozilla-mobile/fenix#16145]
### What is the user problem or growth opportunity you want to see solved?

With the new Firefox for Android, It is not possible anymore to print-to-pdf a webpage. As a consequence, I need to open the webpage in Android's native Chrome browser to be able to do that kind of printing.

Unfortunately, there is no means once a page is opened in FF for Android to send/share its URL to Chrome.

When I click "Share", Chrome does not appears in the list of App I can share to. Why? It *is* an application able to open URLs, it should be listed in the applications that I can send URLs to / Share URL with... (The only reason I see today that it is not listed is because it is a competitor to FF. It is it indeed the reason, then FF is acting against competitor in sneaky way, and it is *wrong*)

I know I can copy the URL in ff, then open Chrome and paste the URL in a new tab, but this is *PITA* and it takes ages: you need to scroll the opened page in FF until the header menu appears, then long press the url bar, then click copy, then hit Android's key to switch to other opened apps,  [then if chrome is not opened yet, switch to default screen, then launch it] , then  scroll up in the currently opened page in chrome until the top menu appears, then select new tab creation, then long press in url bar, then paste [there most of the time I fuck up because the icons are not self-explanatory and I copy the Chrome's URL instead of pasting, thus I need to start all over again], etc.. As I said, PITA...

Another work around is to share to SMS messaging app, send a message to myself, then click the URL and ask to open it in Chrome. Works only if FF is not set as default browser...

### How do you know that this problem exists today? Why is this important?

Because I try to do it almost everyday & because FF lacks necessary print-to-pdf feature & because all the workaround are PITA.

### Who will benefit from it?

All the users... Because for the simple sake of consistency, the "Share" button should list all apps able to open URLs when trying to share a URL...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8472)

**Comment by anotherus3r** [comment]
You can't share links with Chrome in any app, not just Firefox. It's a Chrome issue.

**Comment by Poopooracoocoo** [comment]
> You can't share links with Chrome in any app, not just Firefox. It's a Chrome issue.

but you can open a link with chrome. look at Firefox Focus or even the native open with sheet.

**Comment by anotherus3r** [comment]
> but you can open a link with chrome. look at Firefox Focus or even the native open with sheet.

I don't see why Firefox would have an "Open with" option for every website, unless these websites have their native apps (for which there's an "Open in app" option). I don't know of any browsers that don't focus on one specific usage case that have an option to open a website in another browser. The only ones I can think of is the browser built into the Facebook app (used for opening links shared on Facebook), Firefox Focus (mentioned by you, focuses on deleting all browsing data on exit) and, if I remember correctly, the DuckDuckGo app.

**Comment by Poopooracoocoo** [comment]
I often search for stuff in Focus and then will dump the tabs and their history into my browser which is Fenix at the moment. Focus has a lot of bugs, notably tabs losing their history and page and just generally being broken after the move to GeckoView. Focus only gets the occasional bump in AC and GV. DDG isn't the same. I thought it was like Focus but they closed feature requests saying that its not. I currently use an old version of Focus which uses the WebView but Google Search is even worse than GV's. DDG isn't as nice of a search engine IMO. Google's snippets, info cards and map cards are unrivalled. I hope FF's private browsing mode could replace Focus for me.

**Comment by TrianguloY** [comment]
On android opening an url and sharing an url are two different things. Almost all browsers I know register for the first (so you can choose them when clicking an url) but not for the latter (so you can't choose them when sharing an url). 
The rationale, I think, is that if an 'open in app' button is provided, most of the times the url will be opened in the same browser again (practically all normal users have only one browser, and unless you specifically change the android settings, which is some times not possible, all users have a default browser).

That said, it shouldn't be hard to detect if the 'open in app' button will open firefox again or not and show/hide the button accordingly (should be very easy) but I think the devs have other not important features to work on.

So, in the meantime, I recommend you to use an app specifically designed to solve this. Personally I use https://play.google.com/store/apps/details?id=com.tasomaniac.openwith

**Comment by Poopooracoocoo** [comment]
The problem with that is that it's an extra step. (I have actually used it before!)

>The rationale, I think, is that if an 'open in app' button is provided, most of the times the url will be opened in the same browser again confusing the user

That's why Focus uses a custom open in app sheet. It's not perfect but they also haven't dedicated any resources to Focus in a long time. It's a good workaround for if a user has set a default browser. This is important because Focus is barely in maintenance mode. My use case with Google searches in Focus can't be replaced by private browsing mode as I was saying earlier.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809266

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
