### ISSUE TITLE
[Bug] 100% height by using window.innerHeight breaking on some devices

### ISSUE THREAD

**Issue by PaulB-H** [mozilla-mobile/fenix#16140]
[comment]: # Sites calculating for 100% height by using window.innerHeight breaking on some devices. Issue does not occur in Chrome/Safari/Samsung Internet

## Steps to reproduce

Note 8 : 
Have URL bar set to top
Load [fullvhmobile.herokuapp.com](fullvhmobile.herokuapp.com)
Scroll / tap on page

S10+ : 
Have URL bar set to top
Load [fullvhmobile.herokuapp.com](fullvhmobile.herokuapp.com)
Swipe up and down on page (nothing will happen)
Press menu ⋮ then reload ⟳

Note 9 : (Pending)

### Expected behavior
Nothing happens, footer stays at bottom of page, page does not move

### Actual behavior
Footer gets stretched the height of the toolbar

### Device information

* Android device: 
Note 8, Note 9, S10+
* Fenix version: 
82.1.1
 
### Sites created for testing
[caninesolutions.herokuapp.com](caninesolutions.herokuapp.com)
[fullvhmobile.herokuapp.com](fullvhmobile.herokuapp.com)
[paulb-h.github.io/test100vh](paulb-h.github.io/test100vh)

**Comment by PaulB-H** [comment]
Images from Note 8:

## On Loading:
![onLoad](https://user-images.githubusercontent.com/51964537/96954460-6e7f1d00-14c1-11eb-8033-f3fa9d74846f.jpeg)

## While scrolling (Shouldn't scroll root div is height = window.innerHeight)
![whileScrolling](https://user-images.githubusercontent.com/51964537/96954423-5c9d7a00-14c1-11eb-83ce-69b531647f83.jpeg)

## After glitch
![afterGlitch](https://user-images.githubusercontent.com/51964537/96954428-60310100-14c1-11eb-97ec-8e08a0d31c0e.jpeg)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1673501

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
After talking with the GV team this works on bottom toolbar so it is a Fenix/AC problem.

**Comment by Mugurell** [comment]
@PaulB-H Sorry for not getting to this sooner.
Can you please restore one of your testcases to investigate exactly what's happening in those cases?

**Comment by PaulB-H** [comment]
Hey there!

This one is still up, and I just checked on my Note 8 and can confirm the issue still occurs. Just had to swipe up / down on the page a bit, and the footer will glitch up from the bottom about the same height as the URL bar.

![image](https://user-images.githubusercontent.com/51964537/106817555-0229c300-6645-11eb-8335-ca990cd62616.png)

Live: https://paulb-h.github.io/test100vh/
Repo: https://github.com/PaulB-H/test100vh/blob/main/index.html

**Comment by Mugurell** [comment]
Thank you!

Indeed, it can easily be reproduced with the top toolbar.
I think it will be soon fixed by https://github.com/mozilla-mobile/fenix/issues/10686
I'm leaving this note to know to recheck after that lands.
