### ISSUE TITLE
[Bug] Can't change language on AMO when desktop mode enabled

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#16146]
## Steps to reproduce
open https://addons.mozilla.org
enable desktop mode
double-click the language selection box at the bottom

### Expected behavior
language selection is expected to pop up

### Actual behavior
actual page zoom

### Device information
Nightly 201023 05:01 (Build #2015771307)
AC: 64.0.20201022151526, 4a939244e
GV: 84.0a1-20201022093646
AS: 63.0.0

**Comment by AndiAJ** [comment]
Hi, I managed to reproduce this issue on the latest **`Nightly Build 201027`** using a OnePlus A3 (Android 6.0.1)

✔️ No issues encountered on the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)

**Comment by Amejia481** [comment]
Duplicated of https://github.com/mozilla-mobile/fenix/issues/16399#issuecomment-741811669 we opened an issue for the gv team to take a look at it.
