### ISSUE TITLE
[Pull To Refresh] Throbber should have dark design in dark mode

### ISSUE THREAD

**Issue by dglttr** [mozilla-mobile/fenix#16142]
### What is the user problem or growth opportunity you want to see solved?
The throbber/spinning animation that appears when pulling to refresh a tab should have an appropriate design when the user has enabled dark mode.

### How do you know that this problem exists today? Why is this important?
Currently, the throbber is white in dark mode, which looks strange:

<img src="https://user-images.githubusercontent.com/46764284/96992083-aae66380-1529-11eb-9e42-3041959d9af9.png" width=300 />

### Who will benefit from it?
Users with dark mode enabled that use the pull-to-refresh gesture.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8469)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807080

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
