### ISSUE TITLE
open google discover pages in custom view tab

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#16141]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
If chrome is enabled and if you open a webpage from Google discover page it opens in android system webview however if chrome is disabled it opens directly in Firefox whereas it should open in Gecko view or custom view.. So that if you click back after reading the article it won't leave any trace in recent app panel. Thats how its working with android system web view. 

### How do you know that this problem exists today? Why is this important?
I remember in last 8 or 9 month old version of fenix it used to open in custom view instead of Firefox so something has changed... It should follow same behaviour as chrome 

### Who will benefit from it?
Users who are using chrome... They will get a smooth transition if implemented in fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8468)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812844

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
