### ISSUE TITLE
Strange rendering issue on Reuters site

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/fenix#16147]
When I just loaded this page: https://www.reuters.com/article/us-uber-california-drivers/california-appeals-court-rules-uber-lyft-must-reclassify-drivers-as-employees-idUSKBN27805F, it looked like this:

![Screenshot_20201023-150112.png](https://user-images.githubusercontent.com/158471/97006783-a5484800-1540-11eb-8c88-9d0573235875.png)

Pixel 2 running current Nightly.

**Comment by kbrosnan** [comment]
I cannot reproduce this on a Pixel XL 2 using Nightly.

**Comment by AndiAJ** [comment]
Hi, I **wasn't able reproduce** this issue on the latest **`Nightly Build 201027`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot 
![rsz_screenshot_20201027-095501](https://user-images.githubusercontent.com/51314259/97272547-c2c82b00-183a-11eb-8c39-8870fbe8b6d3.png)

**Comment by djc** [comment]
Yeah, it doesn't reproduce for me, either. Sorry for the noise!
