### ISSUE TITLE
Report site issue icon should be white in dark mode

### ISSUE THREAD

**Issue by amkcpu** [mozilla-mobile/fenix#16143]
### Steps to reproduce
1. Have dark mode enabled.
2. Open toolbar menu.

### Expected behavior
Report site issue icon should be white like all other icons in the toolbar menu.

### Actual behavior
Report site issue icon is black, making it inconsistent and hard to recognize:

<img src="https://user-images.githubusercontent.com/46764284/96992311-fdc01b00-1529-11eb-8f28-bf4047150d66.png" width=300 />

**Comment by cadeyrn** [comment]
Duplicate of #11367.

**Comment by amkcpu** [comment]
Closing as dupe
