### ISSUE TITLE
FNX-5134 ⁃ Don't list about:* pages in history results

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1614]
## Steps to reproduce
* Visit any about:* page
* Start a search with the term "about"

### Expected behavior
* I should not see suggestions for internal pages.

### Actual behavior
* I see suggestions for about:* pages

### Device information
* Android device: ?
* Fenix version: 1.0.1915 Build #11021216

**Comment by vesta0** [comment]
Will be addressed here: https://github.com/mozilla-mobile/android-components/issues/2606

**Comment by pocmo** [comment]
Related: https://github.com/mozilla-mobile/android-components/issues/2606

**Comment by bifleming** [comment]
@pocmo do you know if this is still blocked? I see that the related a-c bug has been closed.

**Comment by ekager** [comment]
This is fixed now and these domains are filtered out by AC HistoryDelegate
