### ISSUE TITLE
[Grid View] Tab titles should have dark background for dark theme

### ISSUE THREAD

**Issue by axeltrinidade** [mozilla-mobile/fenix#16152]
### What is the user problem or growth opportunity you want to see solved?
Present white border grid view favours light theme but looks odd in a dark theme. 
![Screenshot_20201023-212341](https://user-images.githubusercontent.com/68217806/97042470-22e07800-1582-11eb-95a1-ef7cb293f864.jpg)

### How do you know that this problem exists today? Why is this important?
The dark and light themes need to be consistent. 

### Who will benefit from it?
Dark theme users who want consistency.

**Comment by topotropic** [comment]
Thanks for the feedback.
Please use  the following colors for a tab in dark mode:
- border `<color name="dark_grey_10">#52525E</color> `
- selected/active tab border  `<color name="violet_40">#AB71FF</color> `
- background  `<color name="dark_grey_50">#32313C</color>`
- font color for title and close icon closer `<color name="light_grey_05">#FBFBFE</color>`

And for the "Select tabs" button please use 
- background  `<color name="dark_grey_50">#32313C</color>`
- font color `<color name="light_grey_05">#FBFBFE</color>`
<img width="357" alt="image" src="https://user-images.githubusercontent.com/353960/104615363-76e29080-5689-11eb-82b4-112de7e82e01.png">

**Comment by jonalmeida** [comment]
Clearing assignee for now since it isn't actively worked on and adding the 'help wanted' label for contributors that want to help. We could probably add the 'good first bug' too if we include more detailed steps for first time contributors.

**Comment by czlucius** [comment]
Hi
I'd like to work on this issue.

**Comment by czlucius** [comment]
Now that the select tabs button and add to collection button is gone, only the tabs in grid view need to be styled.

**Comment by czlucius** [comment]
![Screenshot_20220112-191251_Firefox Preview](https://user-images.githubusercontent.com/58442255/149129914-25cadb72-8a23-4ee2-bfee-f6181cfd650f.jpg)

Here's the fixed version on night/dark mode.

I used the colors defined in fenix instead of hardcoding the values:
background -> @color/photonDarkGrey50
border -> @color/photonDarkGrey10
active tab border -> @color/photonViolet40
font color -> @color/tab_tray_item_text_normal_theme (which is @color/photonLightGrey05 in dark theme)

**Comment by jonalmeida** [comment]
@czlucius this looks great! ✨ 

Please make sure to create a pull request referencing this issue with a screenshot of the light and dark mode. We can do a code and UX review from there.

**Comment by czlucius** [comment]
I've opened a PR for this issue with my changes.

**Comment by Nojuuu** [comment]
Looks good 👍 

There's also some white borders still left under tab title:
![image](https://user-images.githubusercontent.com/84513173/149531885-e659df55-b85b-4a52-a1f1-c72bf815bf11.png)

and  inactive tabs:
![image](https://user-images.githubusercontent.com/84513173/149532214-c9133e30-2bbb-4bb8-a068-b7d5c7fc18a4.png)

**Comment by jonalmeida** [comment]
> There's also some white borders still left under tab title:

This is from the screenshot.

> and inactive tabs:

An unfortunate case on how we had to implement the Inactive Tabs section in a custom way to give it a close-enough appearance to how a regular CardView.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with OnePlus 9 (Android 11). The results are the same as on the screenshots above., including the white border.
