### ISSUE TITLE
Add Hand Button In Bottom Toolbar

### ISSUE THREAD

**Issue by Dev-i-l** [mozilla-mobile/fenix#16156]
Problem : these days smartphones are getting out of hand like literally. oems are launching larger and larger smartphones and it's becoming harder to access the top portion of the screen, i have suffered this problem too much as my hands are real puny

Solution : well arnaud of kiwi browser realized this problem and added a hand button along with bottom tool bar, clicking the button pulls half the page down making the webpage more accessible.

**Comment by anotherus3r** [comment]
See also: #15822

**Comment by liuche** [comment]
We'll dupe this to #15822.

**Comment by Dev-i-l** [comment]
this is not exactly the dupe of #15822 as that issue does not include this one, i am ok with you closing this issue but make sure this is included in #15822 @liuche
