### ISSUE TITLE
[Bug] Buster:Captcha Solver Add-on doesn't install

### ISSUE THREAD

**Issue by axeltrinidade** [mozilla-mobile/fenix#16151]
## Steps to reproduce
Install Buster through custom add-on collection 

### Expected behavior
It installs

### Actual behavior
Toast message appears saying Failed to install

### Device information
* Android device: Oneplus 7, Android 10 
* Fenix version: Nightly 201022 17:03 (Build #2015771211)

**Comment by axeltrinidade** [comment]
Note: A reddit or suggested that any addon that requires the nativeMessaging permission fails to installon fenix. Not sure how true this is

**Comment by liuche** [comment]
We're still adding WebExtension APIs, so not all addons are likely to work. We added the ability to install any addon, but they're not really explictly supported.
