### ISSUE TITLE
FNX-5135 ⁃ [Bug] unable to build fenix "No value passed for parameter 'successPath'"

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1615]
## Steps to reproduce
Building fenix on Windows using an up to date Android Studio

* I've cloned into a clean folder
* invalidated caches and restart
* tried a clean build and/or rebuild from the Android Studio menu
* building via the command line 

### Expected behavior
Successful build

### Actual behavior
org/mozilla/fenix/components/Services.kt 
No value passed for parameter 'successPath'

Task :app:buildInfoGeneratorAarch64GreenfieldDebug 

### Device information
* Android device: n/a
* Fenix version: git hash 08edb1532ea7242297854c8a28594e2196025068

@vladikoff any thoughts?

**Comment by kbrosnan** [comment]
I've been able to build on Linux and @rpappalax was able to build on OS X.

**Comment by vladikoff** [comment]
You probably have cached android components snapshots. If you manage to get
the latest version it should resolve your issue.

**Comment by kbrosnan** [comment]
Yes this works now.
