### ISSUE TITLE
[Bug] Firefox displays British English when the language of the device is set to English (Philippines)

### ISSUE THREAD

**Issue by Burgercat** [mozilla-mobile/fenix#16167]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to the Settings app of the phone.
2. Set the device language to English (Philippines).

### Expected behavior
Firefox should show American English instead of British English as we use American English here.

### Actual behavior
It shows the British English as the language as the "z" on words like customize are replaced with "s".

### Device information

* Android device: Samsung Galaxy S9+ (Android 10, Build G965FXXSBETH2)
* Fenix version: 82.0.0-beta.6

**Comment by KrasnayaPloshchad** [comment]
That’s reasonable to fix, Philippines haven been ruled by Spain, later grabbed by the United States (and by Japan in WWII), finally gained independence one year after WWII, so Philippines have heavily American influences, and they should perfering American English.

**Comment by zbraniecki** [comment]
Gecko can work with fallback chains, so if the user declares `[en-PH, en-US, en-GB]` then the chain will go from English (Philippines) to English (USA), not English (GB) first.

The question then is whether that's what Android is feeding to Fenix. 

Older Androids only allow the user to set one locale, without any fallbacks, but newer Androids allow user to set a fallback locales in their preferred order.

@Burgercat can you verify which Android version are you on, and whether you were able to set fallback locales or just a single locale?

**Comment by Burgercat** [comment]
I am currently using Android 10 with the One UI skin. I am able to add other locales on the settings app. But currently, I use only a single locale which is English (Philippines).

**Comment by mcarare** [comment]
This issue is marked as `Won't fix` here: https://issuetracker.google.com/issues/64429534.
All English locales (except US and US territories) fallback to British English for Android SDK versions 24+.

IMO handling this with a hack in the code will introduce more instability to an already "fragile" Locale API.
The only other fix I can think of would be importing the locale for Philippine English (either properly localized or just as a copy of the American English file).
