### ISSUE TITLE
FNX-5136 ⁃ [Bug] Experiment loading happens on the main thread and blocks startup

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#1616]
## Steps to reproduce
Start the application.

### Expected behavior
Experiments should be loaded (more quickly than they are)

### Actual behavior
Experiments are loaded, but only after having blocked progress on the main thread.

### Device information
* Android device: Any
* Fenix version: Nightly

**Comment by colintheshots** [comment]
This is fixed in master. There's no QA step needed.
