### ISSUE TITLE
Shorten the name of the protocol (https) in the site address in the list of Logins

### ISSUE THREAD

**Issue by deevroman** [mozilla-mobile/fenix#16162]
The name of the protol https:// is not needed in the Logins list because:
1. Occupies space (especially on narrow screens)
2. Passwords are secret information that should be transmitted by https by default, so you should specify the protocol when it is different from https.

![Screenshot_2020-10-23-13-39-53](https://user-images.githubusercontent.com/25708359/97094841-75449600-1661-11eb-9dc3-dd52090d8fdc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8488)

**Comment by topotropic** [comment]
Yes, makes sense to hide the protocol on the logins list overview since it's still part of the detail view.

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 108.0a1 from 10/31 with Motorola Moto g ( 9 plus) - Android 11). The name of the protocol (https) in the site address in the list of Logins is shortened.

**Comment by AdinaPetridean** [comment]
Verified as fixed on the latest Beta 108.0b1. with Xiaomi Pad5 (Android 12).
