### ISSUE TITLE
Custom tab "tweet" button looks squished

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16160]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open twitter and open a link
![Screenshot_20201025-015002_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/97092803-76ac9900-1636-11eb-96e7-5619786d285e.png)

### Expected behavior
The tweet button looks ok
### Actual behavior
The tweet button looks squished
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8486)

**Comment by 8227846265** [comment]
I also confirm that it's still reproducible on the latest version. I guess this issue is a year old and still ongoing.

**Comment by cadeyrn** [comment]
This is still reproducible.

**Comment by cadeyrn** [comment]
It's still not fixed.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812843

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
