### ISSUE TITLE
[Bug] Title text is cropped

### ISSUE THREAD

**Issue by deevroman** [mozilla-mobile/fenix#16161]
Saved logins:
![Screenshot_2020-10-23-13-39-53](https://user-images.githubusercontent.com/25708359/97094799-e0419d00-1660-11eb-8604-9e6f5df1abd6.png)

Language: Russian
Samsung Galaxy J1
Android 5.1.1

Nightly 201024 17:01 (Build #2015771593)
AC: 64.0.20201023143136, d78abdf9f
GV: 84.0a1-20201022093646
AS: 63.0.0

**Comment by kbrosnan** [comment]
Is this using the phone's default font size setting?

**Comment by deevroman** [comment]
Yes

**Comment by ekager** [comment]
Yeah I can repro changing the locale to German as well

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 201102 (Build #2015773227) using a Sony Xperia Z5 (Android 7.0).
