### ISSUE TITLE
[Bug] Button in fixed position div disappears when updated via JavaScript

### ISSUE THREAD

**Issue by tonydangblog** [mozilla-mobile/fenix#16173]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to the following link (in Daylight, Beta, or Nightly): https://tonydang.blog/stackoverflow/1.html
2. Scroll to bottom
3. Click any of the "click" buttons

### Expected behavior
Button in fixed position div at bottom should not disappear.

### Actual behavior
Button in fixed position div at bottom disappears.

### Device information

* Android device: Pixel 3a
* Fenix version: Daylight 82.1.1, Beta 82.0.0-beta.6, Nightly 201025 17:01
 
More info at this stackoverflow post: https://stackoverflow.com/questions/64530403/button-in-fixed-position-div-disappears-when-updated-via-javascript-only-occurs

I checked and this is not a problem in Chrome, Safari, Brave, nor Opera mobile browsers so assume it's Firefox specific. Works fine on Firefox desktop.

**Comment by tonydangblog** [comment]
Also checked and this doesn't seem to be an issue on iPhone so seems specific to Android Firefox.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1673454

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
