### ISSUE TITLE
[Bug] Ensonhaber - The page headed doesn't fit to the headers place

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16179]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the testing firefox beta
2. Load URL Ensonhaber.com
3. Click on the search box and search "halla"
4. Click on the second result
### Expected behavior
I expect the page headed to be at the top of the page
### Actual behavior
The page header is zoomed out and it exceeds the headers place
### Device information
Samsung Galaxy A51 - Android 10
Vestel Venüs V3 - Android 6.0.1
* Android device: yes
* Fenix version: Android for Firefox Beta 82.0.0

**Comment by AndiAJ** [comment]
Hi, reproducible on the latest **`Nightly Build 201027`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)

The link for mentioned in Step 4 is: https://m.ensonhaber.com/biyografi/hallac-i-mansur-kimdir-2012-03-27

► Screenshot Fenix
![rsz_screenshot_20201027-092606](https://user-images.githubusercontent.com/51314259/97270029-1df81e80-1837-11eb-8b67-9ab383128acc.png)

►Screenshot Chrome
![rsz_screenshot_20201027-092631](https://user-images.githubusercontent.com/51314259/97270089-3a945680-1837-11eb-8535-1b16993cda4c.png)
