### ISSUE TITLE
[Bug] Changing the theme or the position of the toolbar, turns the screen black

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16176]
## Steps to reproduce 
1. Make sure to have a fresh profile.
2. On the onboarding tour, change the theme, from light to dark, or vice-versa. Observe the onboarding tour.
3. On the onboarding tour, change the position of the toolbar. Observe the onboarding tour.

### Expected behavior
The transition is done smoothly, with no glitches.

### Actual behavior
After selecting a different theme, or a different position of the toolbar, the screen turns black for a brief second.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: 10/26 Nightly, beta 83.0.0-beta.1, RC 82.1.1
 
<img src="https://user-images.githubusercontent.com/40694158/97150163-6996c380-1776-11eb-8a06-2e5b8093225b.gif" width="300" height="550" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8501)

**Comment by softvision-miralobontiu** [comment]
I reproduced this issue on the 12/7 Nightly build with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
This still reproduces on the 6/7 Nightly build, on the 89.1.1 RC, and on the 89.0.0-beta.10 build, with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on 6/25 Nightly build with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Still reproducible on 11/2 Nightly build with Samsung Galaxy Note 8 (Android 9).

**Comment by delia-pop** [comment]
This issue is reproducible on 95.0.0-beta.6 build with LG G7 fit (Android 8.1.0). The screen turns black when changing the theme from both the onboarding tour and Settings -> Customize screen.

https://user-images.githubusercontent.com/89388888/143428479-aaa1f0ac-8b6e-4595-a4fc-7d44d2fea4a1.mp4

**Comment by delia-pop** [comment]
This is also reproducible on the latest Nightly 106.0a1 from 09/13 on the new Onboarding with OPPO A15s (Android 10).

https://user-images.githubusercontent.com/89388888/189925132-777ae792-51fa-49ef-a899-282e41cd5b33.mp4

**Comment by AdinaPetridean** [comment]
This issue is reproducibleon Firefox Beta 106.0b4 with Sony Xperia (Android 6.0.1).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807096

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
