### ISSUE TITLE
[Bug] iVysilani ceskatelevize.cz - video not load

### ISSUE THREAD

**Issue by yucikala** [mozilla-mobile/fenix#16177]
[comment]: # got to https://ct24.ceskatelevize.cz/#live

## Steps to reproduce
video not load

* Android device: BlackView 9.0. Android 9.
* Fenix version: latest

**Comment by AndiAJ** [comment]
Hi, reproducible on the latest **`Nightly Build 201027`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)

► Video
![20201027-093539](https://user-images.githubusercontent.com/51314259/97270717-47657a00-1838-11eb-8f14-72738c0f036b.gif)


✔️ Works properly on Chrome

**Comment by yucikala** [comment]
Man from CT wrote me, that FF on android doesn't support the right version of DRM and streaming type... I have no idea what version they need.

On PC is all ok.
