### ISSUE TITLE
[Bug] Gazeteoku.com - Search bar overlaps with header

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16175]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open android for firefox beta browser and go to gazeteoku.com
2. In the upper right corner tap on loupe icon.
### Expected behavior
Search bar appears instead of GAZETEOKU header.
### Actual behavior
Search bar appears behing GAZETEOKU header, overlapping with it.
### Device information
Google Pixel 4 XL - Android 11
Vestel Venüs V3 - Android 6.0.1
* Android device: yes
* Fenix version: Firefox Beta 82.0.0

**Comment by AndiAJ** [comment]
Hi, reproducible on the latest **`Nightly Build 201027`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)

► Video
![20201027-094048](https://user-images.githubusercontent.com/51314259/97271155-e4c0ae00-1838-11eb-80b3-023217cdd0a0.gif)

**Comment by sflorean** [comment]
This issue is still reproducible on Fenix.
