### ISSUE TITLE
[Bug] millipiyango.gov.tr - website is not displayed correctly

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16174]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open Android for Firefox Beta
2. Go to www.millipiyango.gov.tr 
### Expected behavior
Webpage should be displayed correctly
### Actual behavior
Webpage is not displayed consistent with a mobile browser.
### Device information
 Samsung Galaxy A6 (2018) - Android 10,
Vestel Venüs V3 (Android 6.0.1)
Huawei P20 Lite (Android 10.0)
* Android device: yes
* Fenix version: Firefox Beta 82.0.0

**Comment by AndiAJ** [comment]
Hi, **reproducible** on the latest **`Nightly Build 201027`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20201027-103533](https://user-images.githubusercontent.com/51314259/97277018-9c0cf300-1840-11eb-8052-faedbdd20f41.png)
