### ISSUE TITLE
[Bug] Download All Images extension failed to get images

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#16171]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Install [Download All Images](https://addons.mozilla.org/en-US/firefox/addon/save-all-images-webextension/) following your instructions on your blog post
2. Open https://www.mozilla.org/en-US/firefox/
3. Press the menu button, then Add-ons -> Download All Images

### Expected behavior
Download All Images should capture all images from the webpage, and displaying a gallery

### Actual behavior
Download All Images doesn’t do anything

### Device information

* Android device: Galaxy S6, Android 7.0
* Fenix version: Nightly 201025 17:01

**Comment by s-ankur** [comment]
Addons are not allowed to work on mozilla domains and about pages, for security reasons

**Comment by s-ankur** [comment]
Wait, I was wrong, desktop version works just fine with the domain

**Comment by dessant** [comment]
The extension does not work because of the missing downloads API, the issue is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1538348
