### ISSUE TITLE
FNX-5137 ⁃ Search results list should look scrollable

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1618]
### Why/User Benefit/User Problem
When you type a search term in the search field, the list of results visible above the keyboard can be quite short (I see 4 on my Nokia 3.1). Of course, there are many results available if you scroll the list of results but on some devices (again, true on my Nokia 3.1) the visible results fit the available space well enough that there is no indication that more results are available. 

### What / Requirements
* When the results list is longer than the available space, there is an indication that it can be scrolled.

I'll provide a design for this.

**Comment by Verdi** [comment]
![fade to white](https://user-images.githubusercontent.com/107992/56322397-96ecc500-612e-11e9-8db1-2f2d134b6a30.png)

To make the list look scrollable, let's fade to white above the keyboard. We should remove the shadow and instead go from white to transparent over 40dp.

**Comment by shorlander** [comment]
@st3fan This is ready for Eng Feedback.
