### ISSUE TITLE
[Bug] Unable to move cursor in text field

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#16187]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Open duckduckgo, or any site with a text input, and type something (without actually searching)
- Do the same thing again in a new tab
- Go to the first tab, move the cursor and start typing

### Expected behavior
I can type at the location of the cursor

### Actual behavior
It seems like I can move the cursor, but any text I type appears at the last place the cursor was before switching tabs. This behaviour has been happening for at least a couple weeks

![output_0](https://user-images.githubusercontent.com/66154603/97206798-84d6f280-17b9-11eb-9660-b834a6e2daeb.gif)

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 201025 17:01 (Build #2015771787)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1673452

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by makotokato** [comment]
@mobd 
Although I cannot reproduce this using the latest Nightly, could you reproduce this using the latest version?
"Nightly 201025" has critical text bug, but it is fixed by the latest version.

**Comment by mobd** [comment]
I can no longer reproduce on the latest version. Thanks for the fast response!
