### ISSUE TITLE
[Bug] NullPointerException at BaseBrowserFragment.getBrowserToolbarView

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#16199]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

java.lang.NullPointerException: null
    at org.mozilla.fenix.browser.BaseBrowserFragment.getBrowserToolbarView(BaseBrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment.onStart(BrowserFragment.kt:15)

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9828702/?query=is%3Aunresolved%20NullPointerException

**Comment by liuche** [comment]
I'm seeing #8305 in 82.1.1 again - is this possibly the same root cause?

**Comment by sflorean** [comment]
@ekager do we have steps to reproduce the crash? or does the issue needs QA?

**Comment by ekager** [comment]
Doesn't need QA Sentry links looks very rare now, so closing this!
