### ISSUE TITLE
[Bug] Tab index doesn't update

### ISSUE THREAD

**Issue by meetthemeat** [mozilla-mobile/fenix#16192]
### Steps to reproduce
Open some tabs in fenix. For instance 5. Surf on one of those.
The tab index counter to the right of the uri/url input field in the toolbar shows always the absolute number (5) of tabs. Also when I'm not on the last create tab. When I swipe over the toolbar to change to another tab it also doesn't update.

### Expected behavior
The tab index updates corresponding to it's position in the tabs overview.

### Actual behavior
The index shows always the absolut number of tabs

### Device information

* Android device: opo2
* Fenix version:

```
81.1.5 (Build #2015769595)
AC: 57.0.8, 5653ef5fd
GV: 81.0.2-20201012085804
AS: 61.0.13
```

**Comment by AndiAJ** [comment]
Hi @meetthemeat , this is the expected behavior of the tabs counter (display how many tabs are open)
Since the beginning, it displayed the  total of open tabs #904
