### ISSUE TITLE
FNX-5138 ⁃ [Bug] Don’t show "fill link" prompt when characters are in the search field

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1619]
## Steps to reproduce
* Copy a url to the clipboard
* Begin a search by tying characters in the search field

### Expected behavior
* Once I start typing, the "fill link" prompt should be replaced by search and history suggestions.
* If I clear the characters in the search field the prompt should return.

### Actual behavior
* The "fill link" prompt is visible at the end of the list when I'm typing in the search field.

### Device information
* Android device: Nokia 3.1
* Fenix version: 1.0.1915 Build #11021216

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 4/29 build.
