### ISSUE TITLE
Analyze perf of MAIN when restoring to last open tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#16195]
We recently changed the cold start behavior for MAIN: if the user has any tabs open, we ARE restored to the last open tab. Let's ensure this is performant enough in an analysis (no need to write a new test or anything). One concern we have is perceived performance may change b/c it will be longer than MAIN to homescreen.

**Comment by MarcLeclair** [comment]
Closing since we're going to take another approach for now ( Most likely FNPRMS style)
