### ISSUE TITLE
FNX-5139 ⁃ [Bug] Don’t show search results when selecting a URL

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1620]
## Steps to reproduce
* Navigate to a website
* Tap the address bar

### Expected behavior
* The URL should be highlighted
* The keyboard should come up
* I should not see search and history suggestions

### Actual behavior
* I see search and history suggstions

### Device information
* Android device: Nokia 3.1
* Fenix version: 1.0.1915 Build #11021216

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 10/8.
