### ISSUE TITLE
[Bug] "cumhuriyet.com.tr" - The hamburger titles slide off screen when scroll down in page

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16207]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the firefox
2. Open link "cumhuriyet.com.tr"
3. Tap hamburger link
4. Tap "Koronavirüs"
5. Scroll to the bottom of the page
6. Tap hamburger link
### Expected behavior
The subtitles are seen on the left screen
### Actual behavior
The subtitles slide up to the left screen
### Device information
Samsung Galaxy J6 - Android 10
Vestel Venüs V3- Android 6.0.1
* Android device: yes
* Fenix version: Android for firefox beta 82.0.0
![1](https://user-images.githubusercontent.com/66958331/97313162-5f102300-1877-11eb-8e50-484bb525db88.PNG)

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1674042

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by liuche** [comment]
Seems like we're copying the sidebar scroll position from the page scroll position?
