### ISSUE TITLE
[Bug] English label in Italian dialog

### ISSUE THREAD

**Issue by massic80** [mozilla-mobile/fenix#16204]
### Steps to reproduce
Make a POST call, e.g. a login when there is no connection. A 404 appears.
Reload the page. A dialog asks you whether you want to resend data
### Expected behavior
Dialog buttons in Italian
### Actual behavior
Dialog buttons (maybe also the text, but I don't remember) in English 
### Device information

* Android device: Asus Zenfone 4, Android 8
* Fenix version: Italian Nightly 201026 17:01 (Build #2015771979)

**Comment by anotherus3r** [comment]
As far as I am aware, these strings were added not too long ago to Pontoon (Mozilla's localisation service), so they might not have been translated there yet.

**Comment by massic80** [comment]
Whoops, you are right. I'm sorry, but the latest time I reported a translation issue, Fenix wasn't on pontoon.
