### ISSUE TITLE
[Bug][crash] Opening multiple pages from Bookmarks and navigating through them

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#16203]
## Steps to reproduce 
1. Make sure you are signed in with your FxA account, and have multiple bookmarks saved.
2. Go to Bookmarks, select at least 6-7 pages, and choose to open them in new tabs.
3. Go to the tabs tray and open each page, one by one. Let the pages load.

### Expected behavior
The browsing should go smoothly, without issues.

### Actual behavior
Fenix crashes. First, the tabs tray remains blank, and the user cannot access anything else. Fenix freezes. Force closed doesn't solve the issue every time.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1)
* Fenix version: 10/26 Nightly build

### Notes
* Reproduced it 2/2. Did not reproduced the crash when opening multiple pages from History.
* Not reproducible on Xiaomi Mi8 Lite (Android 9)
 
### Details of the crash
0e2f9fdd-44b8-4a64-8a8c-1955d37df93b
<native crash>
* Socorro: https://crash-stats.mozilla.org/report/index/bp-da124479-34dc-4670-9c7d-880c10201027
----
<native crash>

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1682005

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by eamsen** [comment]
@softvision-miralobontiu we've landed a potential fix for this on Nightly. Since I couldn't reproduce the issue on my devices, could you please verify whether the issue is fixed? Thanks!

**Comment by softvision-miralobontiu** [comment]
I did not encounter the crash on the 1/26 Nightly build on the Samsung Galaxy Tab A6 (Android 5.1.1) device.
