### ISSUE TITLE
[Bug] Google - User not able to exit gmail.

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16209]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the firefox
2. Click on the 'Search' bar and type in 'Google.com'.
3. When in google log into your google account.
4. Navigate to gmail.com
5. Click on the 'device' back button.
6. Repeat step 5 several times so as to exit the Gmail.
### Expected behavior
Users should be able to exit Gmail on clicking the 'Back' button.
### Actual behavior
The user remains on the 'Primary' inbox screen, no matter how many times he clicks on the 'Back' button.
### Device information
Samsung Galaxy J8 - Android 10
Vestel Venüs V3-Android 6.0.1
* Android device: yes
* Fenix version: Firefox for Android Beta 82.0.0

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible Firefox Preview Nighlty 201105 (Build #2015773803).

### Devices used:
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus 6T (Android 9)
