### ISSUE TITLE
Some websites have enormous performance impacts

### ISSUE THREAD

**Issue by AndiLeni** [mozilla-mobile/fenix#16218]
## Steps to reproduce
Open https://www.lucidchart.com/pages/de

### Expected behavior
Scrolling happens smoothly. 

### Actual behavior
The screen flickers and the fps drops when scrolling. 

### Device information

* Android device: LG G8s Thinq
* Fenix version: 82.1.1

**Comment by mcomella** [comment]
I filed a platform issue specifically for lucidchart.com: https://bugzilla.mozilla.org/show_bug.cgi?id=1673986 Closing this issue so we can track it upstream. Please file a new issue if there are other sites that are causing performance issues.
