### ISSUE TITLE
Refactor library recycler adapters

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#16216]
Related to #15577, #16215 

Refactor the recycler views in history, bookmarks, downloads (and maybe logins too?) to use https://developer.android.com/reference/androidx/recyclerview/widget/ConcatAdapter (or another option). 

Current implementation does some weird stuff in order to have the Delete button in the scroll view: https://github.com/mozilla-mobile/fenix/blob/655a5cbf5439c162b6c221031dc7f2606eb0bc9f/app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt#L47 

```
fun updateMode(mode: HistoryFragmentState.Mode) {
        this.mode = mode
        // Update the delete button alpha that the first item holds
        if (itemCount > 0) notifyItemChanged(0)
    }
```

**Comment by jonalmeida** [comment]
When we used the `ConcatAdapter` in the tabs tray it came with some side-effects that are worth noting:
 - If the first adapter takes a while to load, the contents of the remaining items will be added and animated in first and then pushed down to show the contents of the first adapter. You read more about this in the [tabs tray bug for it](https://github.com/mozilla-mobile/fenix/issues/13950#issuecomment-683187827).
 - `ItemDecoration` can be annoying if you need to have different decorations for each adapter's ViewHolders and now you need to combine them into one.

**Comment by eliserichards** [comment]
Removing "won't-fix". This issue may still be valid.
