### ISSUE TITLE
FNX-5140 ⁃ [Bug] The Share/Download/Bookmark toolbar can be seen through the toolbar

### ISSUE THREAD

**Issue by ehsan** [mozilla-mobile/fenix#1621]
## Steps to reproduce
1. Make Fenix the default browser.
1. In the Gmail app, click on a link.

In the custom tab powered by Fenix that opens up, the Share/Download/Bookmark toolbar can be seen through the toolbar.  See the screenshot:

http://imgur.com/AzqkloQ

### Expected behavior
It shouldn't be seen. :-)

### Actual behavior
It is seen.

### Device information
HTC one m9.

* Android device: 7.0.0.
* Fenix version: 1.0.1915

**Comment by sblatz** [comment]
I will look into this.

**Comment by sblatz** [comment]
I confirmed that the quick action sheet does not display in custom tabs in the latest nightly. As for the transparent custom tab, that is expected behavior as it's the toolbar that Gmail is asking us to display.

**Comment by topotropic** [comment]
> As for the transparent custom tab, that is expected behavior as it's the toolbar that Gmail is asking us to display.

Hi @sblatz, can you point me to the documentation for custom tabs? Why do we need to offer transparency? Thanks!
