### ISSUE TITLE
Download of Rules or Settings from uBlock Origin fails

### ISSUE THREAD

**Issue by Dan884** [mozilla-mobile/fenix#16228]
I get the error "Download failed".      
I am running uBlock Origin v1.30.6 on Firefox Nightly 201026 17:01 (Build #2015771979). The problem also occurs on the Beta version of Firefox. The Stable released version works OK with the same version of uBlock Origin so bug in Firefox. 

## Steps to reproduce
Open the uBlock Origin addon and export either a rules file or click backup to file from the Settings. I have Open Links in Apps turned off. 

### Expected behavior
The rules or settings are downloaded. 

### Actual behavior
Download fails. 

### Device information
I have tested on a Samsung Galaxy S20 FE 5G, a Samsung Galaxy A11, a Samsung Galaxy S10e, and a Samsung Galaxy Tab S5e. All are running Android 10. The problem occurs on all of them.     

* Fenix version: ?
 201026 17:01 (Build #2015771979).

**Comment by Amejia481** [comment]
When we moved to the new [GeckoView api](https://github.com/mozilla-mobile/android-components/commit/449abd4010c159fa90dddac00d4db7cfa002aecd) we lose some of the functionality for data urls that the previous API provided, it looks like the new api support data urls but we have to do some adjustments for it, as when we use it doesn't provide the same metada as a normal HTTP request, the download is failing [here](https://github.com/mozilla-mobile/android-components/blob/487ead50bcb98047e8ee7db6cf5633314b7862b0/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L615)

**Comment by Amejia481** [comment]
We put a patch for it on https://github.com/mozilla-mobile/android-components/pull/8829, the issue should be fixed in nightly as soon Fenix updates to new ac version that includes the fix.

**Comment by Dan884** [comment]
I can confirm that the fix worked. Thanks for all your work.

**Comment by Dan884** [comment]
I can confirm that the fix worked in Nightly. Thanks for all your work.

Do you know when this Nightly will make it into the Beta release? It is currently broken there as well.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201102 05:00 (Build #2015773225) GV 84 from 11/2 with Motorola Moto G6 (Android 8).
I will remove the qa:needed label and close this issue.

**Comment by Amejia481** [comment]
> I can confirm that the fix worked in Nightly. Thanks for all your work.
> 
> Do you know when this Nightly will make it into the Beta release? It is currently broken there as well.

You can see the release schedule [here](https://wiki.mozilla.org/Release_Management/Calendar)
