### ISSUE TITLE
FNX-5141 ⁃ [Bug] Sometimes no pages load and app restart is required

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#1622]
## Steps to reproduce
Use Fenix as your primary browser and some times it will stop loading pages. A blank screen is displayed. I need to force quit from "Apps & notifications" to make it work again

### Expected behavior
It should always load pages.

### Actual behavior
Pages do not load and show a white page. All pages are affected.

### Device information
* Android device: OnePlus 5t/LineageOS 15.1-20190226-NIGHTLY-dumpling based on Android 8.1.0
* Fenix version: 1.0.1915

**Comment by andreicristianpetcu** [comment]
![Screenshot_20190410-083220_Fenix](https://user-images.githubusercontent.com/922368/56074623-9535a100-5dbe-11e9-83c3-fe444997ced3.png)

**Comment by AaronMT** [comment]
Any specific URLs or is it random?

**Comment by yoasif** [comment]
I have seen this. It is random. I'll try to capture a logcat the next time I see it.

**Comment by yoasif** [comment]
Here's a log where Fenix stopped responding, the crashed. I went ahead and restarted it after. Hopefully this helps. 

[logs-2019-04-15-14-00-06.zip](https://github.com/mozilla-mobile/fenix/files/3081491/logs-2019-04-15-14-00-06.zip)

**Comment by ekager** [comment]
I have also experienced this and think an investigation should be prioritized. Not infrequently after using Fenix for a while, no sessions are able to load although the app is not completely frozen (I am able to go home and to library etc) and an app restart is needed.

**Comment by jonalmeida** [comment]
@andreicristianpetcu do you have Fenix as your default browser?

**Comment by vesta0** [comment]
Link to GV Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1544281

**Comment by andreicristianpetcu** [comment]
It's random.
Fenix is default browser.

**Comment by ekager** [comment]
This should be fixed in the newest GV update. Please reopen if you're still seeing this in latest builds
