### ISSUE TITLE
[Bug] Text entry is difficult on Samsung OneUI

### ISSUE THREAD

**Issue by danielkillam** [mozilla-mobile/fenix#16225]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
I have a Samsung Galaxy Note, running Android 10 (OneUI 2.5). I try to enter text into many websites with Fenix Beta such as Twitter or Roam Notes using Samsung or Chrooma keyboard and the text input behaves unpredictably. 
### Expected behavior
I should be able to enter text with functioning autocorrect, ability to cut and paste, insert text wherever cursor is in text entry field.
### Actual behavior
Unable to insert text within a block of text. Cursor simply jumps to end. Have to delete text back to the point where I want to insert a word
Autocorrect often malfunctions and just starts inserting suggestions wildly into the box, ex. Ttetestest
Sometimes autocorrect fails entirely and I'm left to hunt and peck. 
None of these errors happen in any other app on my device 
### Device information
Samsung Galaxy Note 20 Ultra unlocked
* Android device: SM-N986U1
* Fenix version: 83.0.0-beta.1 (Build #2015771051)

**Comment by makotokato** [comment]
I believe that this is https://bugzilla.mozilla.org/show_bug.cgi?id=1672095.  Please wait for merged to beta

**Comment by danielkillam** [comment]
Interesting. I tried installing nightly and still have the issue with lack of auto-correct on Roam Research. But I hope this cursor change will help with the autocorrect and text insert issue

**Comment by liuche** [comment]
We were having some slow GV merges into Nightly - could you try to verify on the Nightly version on 10/29?

**Comment by Poopooracoocoo** [comment]
in addition to that BMO bug, also see #4208

**Comment by danielkillam** [comment]
Ah yes #4208 sounds very similar to my experience

--
Dan Killam
Postdoctoral Researcher
Biosphere 2
Pronouns: He/him
https://dantheclamman.blog

________________________________

**Comment by ekager** [comment]
Closing for #4208
