### ISSUE TITLE
[Bug] back button on suggested logins screen goes back in history instead of just dismissing suggested logins

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16238]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Press back button while the suggested logins prompt is expanded
### Expected behavior
Only the prompt is unexpanded
### Actual behavior
Prompt is unexpanded but then a back button is also registered on the page
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by Amejia481** [comment]
The fix has been merged on master, lets wait for the QA review.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with Samsung Note10 (Android 10).
