### ISSUE TITLE
[Bug] Fullscreen video controls don't show on screen when navbar is hidden

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#16241]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Have the android navigation bar hidden and view any video in fullscreen portrait mode.

### Expected behavior
I can see the video controls

### Actual behavior
Video controls are not visible

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 201028 17:00 (Build #2015772363)

**Comment by Mugurell** [comment]
Thank you for your report!
Could you please share an example of a website you've seen this happening on? Also a small video would help.
Being able to reproduce exactly the issue you're encountering would help us greatly.

**Comment by mobd** [comment]
Hi, this happens on pretty much any site that allows playing fullscreen videos in portrait mode. For example youtube (although youtube sometimes forces landscape mode, also a bug?), or cnn:

![output_0](https://user-images.githubusercontent.com/66154603/97549824-2ab07a00-19d1-11eb-9526-154392d68ddc.gif)
![output_1](https://user-images.githubusercontent.com/66154603/97549829-2be1a700-19d1-11eb-9eaa-0fae89b91cea.gif)

As you can see in the second gif, some interactions with the video make the controls pop back into the screen.

**Comment by mobd** [comment]
It also happens with the native video player:
![output_3](https://user-images.githubusercontent.com/66154603/97551346-2c7b3d00-19d3-11eb-88b1-adec220c43ea.gif)

**Comment by Mugurell** [comment]
I cannot reproduce this with:
- http://thumbs.gfycat.com/GivingShorttermGrackle-mobile.mp4
- https://edition.cnn.com/videos/world/2020/10/27/italy-coronavirus-covid-19-protests-restrictions-aftermath-wedeman-ctw-intl-ldn-vpx.cnn/video/playlists/coronavirus-intl/
- https://www.youtube.com/watch?v=FoMlSB6ftQg

Asking QA for a second check.

**Comment by mobd** [comment]
In a somewhat related issue #14820 the screen aspect ratio is also mentioned. My screen has a 20:9 ratio so that might influence this as well

**Comment by sflorean** [comment]
Tested on Nightly 11/2 with the following devices Pixel 3 (Android 11), Nexus 6 (Android 7.1.1), and couldn't reproduce the issue.
However, I was able to replicate it using CNN video with Huawei MediaPad M2(Android 5.1.1) - tablet.

**Comment by Mugurell** [comment]
No sure if this is still an issue or not.
But seems like an important one that we'd one to fix if it still reproduces.

**Comment by mobd** [comment]
Firefox now automatically switches to landscape mode but I can still reproduce on any portrait video, for example https://m.youtube.com/watch?v=FoMlSB6ftQg
![output_0](https://user-images.githubusercontent.com/66154603/123113861-2b55bf00-d43f-11eb-897d-a089a91a5b6c.gif)
It happens regardless of the site or video player, the bottom part of the page does not show as long as I have the android navbar hidden

**Comment by Mugurell** [comment]
Cannot reproduce in the latest Nightly when testing on a Pixel 3 with Android 12 or a Samsung S7 with Android 8.

https://user-images.githubusercontent.com/11428869/123387187-2e1bf580-d5a0-11eb-981d-7b4b4e2936e7.mp4

@mobd If it's possible can you test if this reproduces on other devices?
Also can you test whether the same issue exist [on this apk](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-debug/artifacts/public%2Fbuild%2Fgeckoview_example.apk) - a slimmed down version of the app that could help isolate the bug?

**Comment by mobd** [comment]
Unfortunately I don't have any other devices I could test this on.
I'm not able to reproduce on the geckoview apk, but (I'm not sure if this is related) the height at which the controls are shown changes depending on if the toolbar was visible when switching to fullscreen.
![output_0](https://user-images.githubusercontent.com/66154603/123480989-67398180-d603-11eb-9b47-1051ee8b51c3.gif)
With the native player this also happens. In both cases the controls are visible, but in the second case some pixels on the bottom of the control bar are outside the viewport.
![output_1](https://user-images.githubusercontent.com/66154603/123482118-0ad76180-d605-11eb-8245-a33b834e07eb.gif)
In firefox nightly the position of the toolbar does not matter:
![output_3](https://user-images.githubusercontent.com/66154603/123482560-a963c280-d605-11eb-8bc5-2be056ef8863.gif)

Video used is https://giant.gfycat.com/OrganicHonorableColt.webm

**Comment by mobd** [comment]
Also, this is from the geckoview app if i turn on the android navbar:
![output_4](https://user-images.githubusercontent.com/66154603/123483210-aae1ba80-d606-11eb-98b7-e541c1f71531.gif)
It seems like it just ignores it, it doesn't display the bottom controls at a different height like firefox nightly
