### ISSUE TITLE
[Bug] Sometimes you cannot trigger zoom with two fingers

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#16242]
On the desktop mode website, two-finger zooming 10 times, about 1 time can not trigger the zoom, which affects the experience very much. This problem occurs on 82 and above versions

https://i.imgur.com/LBVFuzV.mp4

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1674063

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment]
Thank you for the report @lindongbin 
With this seemingly being a GeckoView issue I moved the issue to the appropriate issues board.
Please follow-up the discussions there.

**Comment by lindongbin** [comment]
> Thank you for the report @lindongbin
> With this seemingly being a GeckoView issue I moved the issue to the appropriate issues board.
> Please follow-up the discussions there.


Kartikaya Gupta (email:kats@mozilla.staktrace.com)
	
Comment 2 • 21 hours ago

Please reopen the fenix bug, as this is not a Gecko-side bug. Fenix is eating the input events and preventing them from getting delivered to Gecko. I made a local build with logging in fenix/GV code and observed that the initial ACTION_DOWN event never makes it to GV in cases where zooming doesn't work.
