### ISSUE TITLE
[Bug] Paste behavior improvements

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#16249]
Following https://bugzilla.mozilla.org/show_bug.cgi?id=1664746 we should look for potential improvements.

**Comment by Mugurell** [comment]
I saw in Fenix we are using our own https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt as a wrapper over the ClipboardManager that would allow us to easily do what we need.

But there is also the `InlineAutocompleteEditText` from AC which shows it's own floating menu and already responds to [onTextContextMenuItem](https://github.com/mozilla-mobile/android-components/blob/b266ac3d16e15cabc969cfe33c9cf965f557e257/components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt#L718) selected items.
For this I was thinking to just do the pasting ourselves similar to what now happens in https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/TextView.java;drc=master;l=12891.
Seems to be the simplest and cleanest way to have full control.

Since I see you worked the most on `InlineAutocompleteEditText`, @csadilek does this seem like a reasonable approach?

**Comment by csadilek** [comment]
@Mugurell Yes, sounds reasonable! `InlineAutocompleteEditText` is a generic UI component though. It doesn't and probably shouldn't have a concept of protocols, but we can address that by providing some form of list / configuration as a parameter?
