### ISSUE TITLE
[Bug] Error pages improvements

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#16248]
Following https://bugzilla.mozilla.org/show_bug.cgi?id=1658276 we should look for potential improvements.

**Comment by Mugurell** [comment]
For validating this changes we would just need to know that everything works as before - it looks the same, the buttons work the same.
These error pages can be seen when  accessing https://badssl.com/

Please note that for some specific webpages with broken ssl the "Accept the Risk and Continue" button may not work. Pre-existing issue tracked in https://github.com/mozilla-mobile/android-components/issues/9136

**Comment by sflorean** [comment]
Verified as fixed on Nightly 12/9 with Pixel 3 (Android 11) an Nexus 6(Android 7.1.1).
