### ISSUE TITLE
[Bug] Restored session displays blank engine view and cannot be reloaded

### ISSUE THREAD

**Issue by reyis4402** [mozilla-mobile/fenix#16259]
When I close the Firefox Nightly browser (latest version) and restart, the progress bar no longer comes up on its own.

Device: Lenovo K6 Note Android 10
![Screenshot_20201029-185208926](https://user-images.githubusercontent.com/60405617/97598619-741bbc00-1a07-11eb-9b33-8674365b6d58.jpg)

**Comment by kbrosnan** [comment]
How are you closing the browser? Swipe close? Quit menu item? Task killer?

**Comment by reyis4402** [comment]
@kbrosnan 
I put it on the background like in the picture and close it
![Screenshot_20201029-191817_Trebuchet](https://user-images.githubusercontent.com/60405617/97601834-e5a93980-1a0a-11eb-8166-a3d0953d6e3f.png)

**Comment by aviegdown** [comment]
@kbrosnan i can confirm this bug

1. on any website
2. open some link in new tab
3. quick kill firefox from recent app (before link in new tab fully loaded)

after do this, link in new tab will not loaded (blank) and also cannot be refreshed

Nightly 201103 17:00 (Build #2015773515)
Android 7.0

**Comment by ekager** [comment]
@reyis4402 @aviegdown can you still reproduce this issue?

**Comment by aviegdown** [comment]
@ekager yes it is, 
![ezgif-3-a25219225ca2](https://user-images.githubusercontent.com/72583750/102639843-2f510d80-418c-11eb-9a85-bcf76bce2379.gif)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 1/25 Firefox Nightly build with Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
