### ISSUE TITLE
[Bug] Scrolling screenshot

### ISSUE THREAD

**Issue by Japeskie** [mozilla-mobile/fenix#16253]
## Steps to reproduce
1. Go to any website
2. Take a screenshot

### Expected behavior
Scroll screenshot feature is enabled.

### Actual behavior
Scroll screenshot feature is disabled. (Greyed out)
![nightbug - Copy](https://user-images.githubusercontent.com/73644544/97565319-011f3f00-1a21-11eb-87b1-be031987727f.jpg)

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No, tried with Chrome and Kiwi Browser and it works properly there.

### Device information

* Android device: Mi 9T Pro MIUI 12
* Fenix version: Nightly (Build #2015772363)
 (Didn't work on all Nightly version, even on Fenix)

**Comment by Mugurell** [comment]
This is dependent on a external application that would do that scrolling screenshot, with Fenix not offering this feature.

I tried a similar system feature on a OnePlus 7T Pro (Android 10) and the scrolling feature worked.

Not sure if there's anything that the app should do to offer this, though seeing in the original report that scrolling screenshot works on Chrome but not on Fenix there could be something.

I think it's important first to know exactly what such features work / or not on Fenix versus other apps.
Asking QA for more testing around this, with system features / 3rd party apps.
Ideally a scrolling screenshot should be produced in all / most cases with a similar behavior when doing a screenshot in other apps.

**Comment by Japeskie** [comment]
The device is also using Android 10, and the scrolling feature works with in every scenario except with Fenix.

Here is a screenshot with it working on Chrome browser.
![fenix  Copy](https://user-images.githubusercontent.com/73644544/97611776-95a19580-1a51-11eb-912b-76dd3b931372.jpg)

I'll try to ask other Xiaomi users if it is working on their device on the Fenix browser.

**Comment by anotherus3r** [comment]
Scrolling screenshots work in Fenix on Huawei's EMUI 10.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly Build 201103`** using the following devices:

✔️ Google Pixel 3a (Android 11) - 3rd party app - **LongShot** 
✔️ Huawei Mate 20 Lite (Android 10) - **Android built-in option**
✔️ Samsung Galaxy Note 10 (Android 10) - **Android built-in option**
❌ Xiaomi Redmi Note 8T (Android 9) - **Android built-in option**
❌ LG G7 FIT (Android 8) - **Android built-in option**
✔️ Samsung Galaxy S6 (Android 7) - **Android built-in option**
✔️ OnePlus A3 (Android 6.0.1) - 3rd party app - **Screen Master**

On both Xiaomi and LG the scrolling screenshot **fails to work on Fenix**, whereas, it **properly works on Chrome.**

**Comment by gungfujoe** [comment]
This is still an issue. Scrolling screenshots are a native feature in Android 12+, no longer requiring third-party apps or custom launchers. However, Firefox Mobile doesn't support this core Android feature.
