### ISSUE TITLE
[Bug]Video is zoomed in when in fullscreen mode

### ISSUE THREAD

**Issue by Japeskie** [mozilla-mobile/fenix#16252]
## Site with issue and any steps to reproduce
1. Go to www.twitch.tv
2. Use desktop site
3. Play any video in fullscreen mode

### Expected behavior
Video will play fullscreen.
![ok - Copy](https://user-images.githubusercontent.com/73644544/97565668-290ea280-1a21-11eb-8aaa-9284ca88cae2.jpg)

### Actual behavior
Video will play fullscreen but it is zoomed in so you could not see the full video.
![nightlybug - Copy](https://user-images.githubusercontent.com/73644544/97565719-2ca22980-1a21-11eb-91fd-6a1a5c85983b.jpg)

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No, already tried with Chrome and Kiwi Browser. 

### Device information

* Android device: Mi 9T Pro MIUI 12
* Fenix version: Nightly (Build #2015772363)

Last version that worked properly is:
* Fenix version: Nightly (Build #2015769099)
All versions next to it are bugged.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1674104

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment]
Seems like a GeckoView issue. Moving this to Bugzilla.
Please follow-up the discussion there.
