### ISSUE TITLE
[Bug] USB debugging improvements

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#16250]
Following https://bugzilla.mozilla.org/show_bug.cgi?id=1658865 we should look for potential improvements.

**Comment by softvision-miralobontiu** [comment]
Verified that the "Remote debugging via USB" option is not displayed in Settings on the following devices with Android 5:
- Xiaomi mi4i (Android 5.0.2),
- Samsung Galaxy Tab A6 (Android 5.1.1), and
- Xiaomi MiPad 2 (Android 5.1) - x86 architecture.
@Mugurell is it ok to close this issue?

**Comment by mcarare** [comment]
@softvision-miralobontiu According to the comment above, this can be verified as fixed and closed.
