### ISSUE TITLE
[Bug] java.lang.OutOfMemoryError : GC overhead limit exceeded when running CI, `test-debug`

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#16262]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Run CI on a pull request

### Expected behavior
Pass

### Actual behavior
`test-debug` Frequently failing due to error messages such as:
```
[task 2020-10-28T17:57:53.747Z] java.lang.OutOfMemoryError: GC overhead limit exceeded
```

This occurred in my PR https://github.com/mozilla-mobile/fenix/pull/16101#issuecomment-718196704 and on master commits https://github.com/mozilla-mobile/fenix/runs/1327191814.

I'm guessing we need to increase the memory available to our TC instances or there is a memory leak in our test frameworks. Notably, robolectric tests that spawn new threads do not automatically clean them up: I haven't heard anyone discussing methods to clean up threads so it's very likely we're not cleaning them up. It's entirely possible these rogue threads are causing the memory used by our unit tests to balloon.

### Device information

* Android device: N/A
* Fenix version: N/A

**Comment by mcomella** [comment]
We should take a heap dump while running the UI tests to look for any suspicious use of memory. Similarly, we can check my thread theory above by investigating the number of active threads when running the UI tests. I think this should easily be possible with the Java VisualVM (it's a desktop JVM profiler that can attach to an already running java process).

**Comment by mcomella** [comment]
[This page](http://robolectric.org/best-practices/) talks about the threading issue in robolectric.

**Comment by liuche** [comment]
Also see #16237, we should dupe one of them. This one sounds more useful?

Is there a way to determine if we've introduced a terrible memory leak recently?

**Comment by mcomella** [comment]
> Is there a way to determine if we've introduced a terrible memory leak recently? I think this has been a problem for about 2 weeks.

fwiw, if this is a memory leak, it may not affect our production code.

If it is a memory leak, we could try to determine if we introduced it by, assuming we can't reproduce the error exactly locally (I haven't been able to), instead figuring out how to measure how much memory is used by the unit tests (maybe with VisualVM?) and then we could see if there's a significant difference in memory used from today to, say, three weeks ago. If so, we could bisect from there. Unfortunately, this commit could be "Updated android-components to version ...", which would put us in a pickle. 😅

It could also be e.g. that each test leaves a few threads which gradually causes us to run out of memory and we finally hit the limit (e.g. each test adds 5 MB to the heap and we added just enough tests to exceed the heap).

**Comment by st3fan** [comment]
I am uplifting https://github.com/mozilla-mobile/fenix/pull/16350 to `v83` and I am landing https://github.com/mozilla-mobile/fenix/pull/16349 on master, which should also end up on `v83`.

Let's see if those two combined make a difference?

**Comment by mcomella** [comment]
This is now https://github.com/mozilla-mobile/fenix/issues/16302
