### ISSUE TITLE
[Bug] Sharing to pocket brings app to foreground

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#16268]
Currently pocket app is designed so when sharing a link it will show a toast that the URL has been added to the pocket app but it does not switch to the pocket app.  However, when using Fenix to share to the pocket app, if the app is in the background it is brought to the foreground.

## Steps to reproduce
1. Open the pocket app and browse to a article.
2. Open Fenix and browse to different URL.
3. Tap the menu and top the share icon.
4. Choose pocket app.

### Expected behavior
5. Toast shows to confirm URL is saved to pocket app.

### Actual behavior
5. Pocket app is brought to foreground.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201103`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
