### ISSUE TITLE
[Bug] Hiding URL bar interferes with fixed content

### ISSUE THREAD

**Issue by ygoe** [mozilla-mobile/fenix#16264]
**Prerequisites:** Pin your URL bar to where it belongs: the top edge. I don't know what happens when it's at the bottom edge but this is an inacceptable state for me so I never tried that.

## Steps to reproduce

1. Create a website that is just a bit taller than the viewport height and that has a fixed block element at the bottom of the window (non-scrolling).
2. Swipe your finger to scroll up or down.

### Expected behavior

Not sure, as the maximum scroll offset is less than the URL bar height. So either the URL bar could hide half-way and behave as it always does. Or the URL bar could always stay there because it knows it can never fully hide by scrolling it out with the content. So, no expectations here. But not what happens.

### Actual behavior

1. The element that's fixed to the viewport bottom edge moves up into the page, still covering content. This is an impossible situation! Fixed elements must never move anywhere, at least at the bottom where no URL bar is moving.
2. No matter in what direction I swipe my finger, up or down, the page always toggles between the three states: Scrolled to top and bottom fixed element is at the bottom; or scrolled a bit up and the bottom fixed element is also moved upwards; or not scrolled and the bottom element is still moved up.

It feels like a complete mess, like the layout enging doesn't have things under control and wildly guesses whatever things to move anywhere. It makes a very helpless impression here.

### Device information

* Android device: Samsung Galaxy S10e, Android 10
* Fenix version: 82.1.1

**Comment by MiquelOrtega** [comment]
I was going to file a bug report but I believe the underlying issue is the same as this one:

Pinning the URL bar to the top of the browser and loading a 100% height <div> gives unexpected behaviour when pressing or scrolling. One would expect it to retain its size but it becomes smaller, by apparently one URL bar unit of height. A sample page that goes awry is
```
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            html, body{
                height: 100%;
                background-color: purple;
            }
            #test{
                height: 100%;
                background-color: red;
            }
        </style>
    </head>
    <body>
        <div id = "test"> </div>
    </body>
</html>
```
I see a purple bar appearing in the bottom of the viewport after pressing/scrolling.

- Android device: Cubot R9
- Fenix version: 82.1.1

**Comment by jetibest** [comment]
I have a similar issue, this example shows clearly what is going on:

```html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=320, initial-scale=1">
    <style>
    html
    {overflow: hidden;width: 100%;height: 100%;margin: 0;padding: 0;background-color: yellow;box-sizing: border-box;border: 5px dashed #f0f;}
    body
    {width: 100%;height: 100%;margin: 0;padding: 0;background-color: red;box-sizing: border-box;border: 5px dashed blue;}
    main
    {background-color: rgba(230,230,230,0.8);z-index: 1;padding: 1em;box-sizing: border-box;font-size: 24pt;}
    </style>
</head>
<body>
    <main>
        <h1>Heading 1</h1>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim magna nisi, eget congue risus sodales sit amet. Cras pulvinar quam sit amet ipsum accumsan, id venenatis sem cursus. In risus risus, faucibus eget dolor feugiat, finibus aliquam ipsum. Nulla sed tellus velit. Suspendisse rutrum nisi id lacus tristique, efficitur venenatis turpis dapibus. Donec semper ut diam at dictum. Etiam sed dolor tristique, placerat lacus sed, luctus ante. Sed scelerisque consequat finibus.
        </p>
        <p>
        Cras vitae elementum justo. Proin eu justo vulputate, vehicula lacus vitae, viverra arcu. Ut id luctus ipsum. Sed ut fermentum libero. Duis at lectus in felis pharetra sodales. Morbi convallis feugiat turpis, vulputate dictum velit fringilla vitae. Duis eu sapien et odio porta pellentesque. Nullam suscipit est vitae maximus maximus. Nam dapibus elit id sapien ultrices ornare. Aliquam vel enim nunc. Ut iaculis augue neque, quis condimentum mi consequat quis. In porttitor tristique neque, vitae malesuada felis pellentesque eu. Donec a tincidunt nulla, id mollis est. Nulla in maximus ex. Duis at orci eget eros scelerisque suscipit mattis ac diam. Cras imperdiet congue turpis, vehicula rutrum lectus lobortis a.
        </p>
    </main>
</body>
</html>
```

Other browsers also have trouble solving the hideable toolbar issue with regard to 100% height and a dynamically changing viewport. However, the result here in Firefox on Android is very buggy. As can be shown in this GIF recording, where I am randomly zooming:

![firefox-viewport-bug](https://user-images.githubusercontent.com/2344986/99190821-0b537400-2769-11eb-961a-c1e45f3dea63.gif)

In practice, this breaks web apps with a full height fixed sidebar (while allowing zoomable/scrollable content on the right side). I haven't found a workaround for the issue yet.

**Comment by ygoe** [comment]
Yes, no need to fix this anymore, I had way too many issues with Firefox on Android so I switched to Brave.
