### ISSUE TITLE
yaani search engine for Turkish locale

### ISSUE THREAD

**Issue by re-hub** [mozilla-mobile/fenix#16266]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Yaani search engine option for Turkish locale installation.

yaani website: https://www.yaani.com.tr/
yaani web browser in Play store: https://play.google.com/store/apps/details?id=com.turkcell.yaani&hl=en_US&gl=US

### How do you know that this problem exists today? Why is this important?
Yaani Turkish search engine is not available in fenix preferences.

### Who will benefit from it?
Yaani search engine availability would provide Turkish users with a search engine option more suitable for their locale.

**Comment by mcarare** [comment]
@re-hub You can add any custom engine from Settings -> Search -> Add search engine.

**Comment by re-hub** [comment]
This feature request might be more suitable for the average user in Turkey, if this suits your project internationalisation aims and other considerations.

**Comment by kbrosnan** [comment]
In some cases locales can make suggestions about the search engines that are available. This seems like something to talk to the Turkish localization team about https://wiki.mozilla.org/L10n:Teams:tr
