### ISSUE TITLE
Support for auto-updating Fenix for non-Play Store builds

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#16273]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
 - Users that downloads or need to download Fenix from non-GPS locations (e.g. Huawei App gallery, Samsung app store) will have the ability to download the latest release APK from Github.

### How do you know that this problem exists today? Why is this important?
 - There are users that want to download Firefox on app stores or locations that do not have access the Play Store that download the APK manually from Github. These are savvy users who know where to get the APK from but do not know that the app does not update after that.

### Who will benefit from it?
 - Non-Google Play Store users

### Technical considerations
We have most of the parts today to support this:
 - A check for Play Services to know if the auto-downloader needs to be turned on.
 - [Mozilla Archives](https://archive.mozilla.org) or Github Releases (`curl https://api.github.com/repos/mozilla-mobile/fenix/releases`).
 - Download Manager
 - WorkManager API to poll once a day

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8567)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813264

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
