### ISSUE TITLE
[Bug] Custom Saved Logins Toolbar Header (with chevron filter) has cut off ripple 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#16271]
Opening from https://github.com/mozilla-mobile/fenix/pull/16219 :
"The ripple background (when clicking the filter button) gets cutoff because of the constraints(?) and lack of padding for it to expand fully" in this file: `saved_logins_sort_items_toolbar_child.xml`

We should see if it's possible to have the ripple not be cut off here

**Comment by ebalazs-sv** [comment]
@ekager Hi! Can you please provide the steps to reproduce this issue, so we can verify it? Thank you.
I will keep the qa:needed label to verify this issue when the steps to reproduce are available.

**Comment by ebalazs-sv** [comment]
I will remove the qa:needed label until the steps to reproduce are available.

**Comment by yichiehc** [comment]
Hi @eliserichards,

I tried to reproduce this issue but didn't see "the ripple background (when clicking the filter button) gets cut off" on Nightly. Has this been fixed already? Looks like there is a pull request for this? https://github.com/mozilla-mobile/fenix/pull/16741

**Comment by eliserichards** [comment]
Let's tag QA to verify if this is fixed 👍

**Comment by sflorean** [comment]
I didn't see any issues on latest Nightly build with Pixel 3 (Android 11) and LG G7 Fit (Android 8.1).
