### ISSUE TITLE
[Bug]Report site issue is missing from the main menu on 82.1.2

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16278]
## Steps to reproduce
1. Navigate to any website
2. Open the ⋮ Main menu

### Expected behavior
Report site issue should be available

### Actual behavior
Report site issue isn't available

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Firefox 82.1.1

### Notes
✔️ Properly displayed on Nightly 201030

**Comment by cadeyrn** [comment]
This is expected:

https://github.com/mozilla-mobile/fenix/blob/releases/v82.0.0/app/src/main/java/org/mozilla/fenix/components/Core.kt#L109-L117

**Comment by AndiAJ** [comment]
Great, many thanks @cadeyrn ! ☺️
