### ISSUE TITLE
Password manager not working with basic authentification

### ISSUE THREAD

**Issue by Hubfront** [mozilla-mobile/fenix#16270]
The fenix password manager does not store new login credentials nor does it offer login credentials when basic authentification is used.

Unfortunately, the last fix regarding the login management did not adress basic authentification as well. Basic authentification is a common used authentification method, especially in an university environment and a failure should be considered as a bug.

## Steps to reproduce

Make a http basic authentification login

### Expected behavior

First run: Firefox offers to store username/password
Second visit: Firefox autofills username/password. When multiple logins are possible, Firefox offers to select one of them

### Actual behavior

Nothing happens.

### Device information

* Android device: Galaxy Note 10
* Fenix version: latest nightly, beta, stable (82)

**Comment by ekager** [comment]
Closing for #13941.

**Comment by Hubfront** [comment]
@ekager In my bug report I adress the internal password manager not working with basic authentification. Bud your proposed #13941 refers to a the problem, that fenix is not working with a 3rd party password manager when basic authentification is used.

It found an open issue falsely marked as "feature request", that adress the internal password manager and seems to be a dupe of this one. It's #8642 and really needs to be categorized as bug. Please refer mine to this one and please categorize it as bug, because the internal password manager not working with basic authentification is a bug.
