### ISSUE TITLE
[Bug] removal of "wait for first paint" in secret setting 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#16277]
is it a bug or intentional the removal of "wait for first paint" for latest nighlty in secret setting
now white flashes are back really disappointing.

**Comment by MicroBeast** [comment]
https://github.com/mozilla-mobile/fenix/issues/6313#issuecomment-716672344

**Comment by ale82to** [comment]
thanks for letting me know!

**Comment by ekager** [comment]
This should be fixed in latest Nightly the right way! Closing :)
