### ISSUE TITLE
[Bug] All tabs closed except 3

### ISSUE THREAD

**Issue by SeregaKR** [mozilla-mobile/fenix#16281]
## Steps to reproduce
1. Open at least 2 appps on a phone
2. Go to Firefox and open more than 6 tabs in total. In my case there are 2 opened tabs and then I open other 4 tabs or more in new tabs (long press on link and choosing open in new tab)
3. Switch to one of the opened new tab
3. Switch to other app (i.e. Messenger Lite) and spend more than 3 minutes there
4. Come back to Firefox

### Expected behavior
See all the tabs that were opened before switching to other app, including opened in new tab
### Actual behavior
Only 3 tabs are opened: 2 that was opened before and one tab that was active before switching to other app
### Device information

* Android device: Xiaomi Mi Mix 2 (MIUI12, Android 9)
* Fenix version: 82.0.1

**Comment by ekager** [comment]
@SeregaKR are you still seeing this problem? Are you using private mode?

**Comment by SeregaKR** [comment]
> 
> 
> @SeregaKR are you still seeing this problem? Are you using private mode?

I don't use private mode.

Now I don't see the problem (Firefox 84.1.1) but I can't test it the same way anymore (no longer use heavy apps on my phone). So I'll try to test this issue more in the next few days and write back.
