### ISSUE TITLE
Browsing keeps freezing every 5 sec

### ISSUE THREAD

**Issue by xmatkla** [mozilla-mobile/fenix#16280]
Hello guys,
since yesterday my mobile Firefox browser started lagging (phone screen become completely unresponsive). Any ideas how to fix it ? thanks

video evidence
https://streamable.com/14nmry

Details:
- other apps works OK
- clear cache did not help
- reinstallation did not help
- phone restart did not help
- phone factory reset did not help

Phone:
- LG V40 (LM-V405EBW) / OS build v10 V30c-EUR-XX

Firefox:
- 82.1.1 build 2015770923

what has changed since yestarday:
- new build V30c-EUR-XX has been installed (OS build downgrade is not preferred)

**Comment by Mugurell** [comment]
Hello
@xmatkla Does this reproduces constantly for you?
If so can you please also try on [GVE](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt)(geckoview-example.apk) and report back if you see it also happening there?
Also, does having the toolbar at the top or to the bottom makes any difference?

**Comment by ekager** [comment]
@xmatkla is this still a problem for you?

**Comment by Mugurell** [comment]
This was probably resolved by https://github.com/mozilla-mobile/android-components/issues/9043
