### ISSUE TITLE
[Bug] site not working in nightly but works fine in beta

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#16284]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open the below site
It works in Firefox beta and chromium
Blank page in nightly... There might be other sites too who knows. Test was carried out with fresh installation.. No add on or settings modified

https://www.tatacliq.com/amazon-fire-tv-stick-3rd-gen-with-alexa-voice-remote-black/p-mp000000007855063

### Expected behavior
Site should open

### Actual behavior
Getting blank page

### Device information

* Android device: ? Rog3
* Fenix version: ?latest nightly 

![Screenshot_20201030-183216038](https://user-images.githubusercontent.com/58127841/97708126-4bb2c100-1ade-11eb-83e0-b0a57499595a.jpg)
![Screenshot_20201030-183223442](https://user-images.githubusercontent.com/58127841/97708136-4eadb180-1ade-11eb-8da9-faccbacd705c.jpg)

**Comment by mcarare** [comment]
This might be a GV problem. It is also reproducible in the Sample browser with Gecko Nightly but not with Gecko Beta.
Same, in Fenix, with build variant debug versus beta.

The site loads, but the divs that contain products do not render correctly.

**Comment by sheikh-azharuddin** [comment]
Also in beta the page loads instantly however in nightly it is taking some time after showing some intermediate pages

**Comment by mcarare** [comment]
> Also in beta the page loads instantly however in nightly it is taking some time after showing some intermediate pages

Yes, and you can actually see a short peak of some type of loader before the page turns blank.

**Comment by kbrosnan** [comment]
Renders fine on Geckoview Example but broken on Reference Browser so AC seems responsible.

**Comment by jonalmeida** [comment]
From AC triage: We should re-test this with and without Tracking Protection along with the latest GV.

**Comment by sflorean** [comment]
I wasn't able to reproduce the issue on latest Nightly build (12/14), with Strict, Custom, Standard ON and with the setting disabled. @sheikh-azharuddin is this still reproducible for you?

**Comment by sheikh-azharuddin** [comment]
Yes fixed 👌👍
