### ISSUE TITLE
Internal password manager is not working with basic authentification

### ISSUE THREAD

**Issue by Hubfront** [mozilla-mobile/fenix#16299]
The internal password manager does not store new login credentials nor does it autofill the login prompt, when basic authentification method is used.

Basic authentification is a common used authentification method, especially in an university environment and if the internal password manager of fenix cannot handle that, this should be considered as a bug. This getting fixed is even more important, because with fenix, getting login credentials from the login credentials page is much more complicated now: you cant copy username and password as easily to the login page, as it was possible with fennec.

## Steps to reproduce
Make a http basic authentification login page, e.g. with https://www.blitter.se/utils/basic-authentication-header-generator/

### Expected behavior

First run: Fill out the login prompt with user/pass. Firefox offers to store the login credentials in its database
Second visit: Firefox autofills login prompt with username/password. When multiple logins are possible, Firefox offers to select one of them

### Actual behavior

The internal password manager does not offer to store new login credentials, nor the internal password manager does autofill the login prompt with login credentials, that are already in its database.

### Device information

* Android device: Galaxy Note 10
* Fenix version: v82, beta (v83), nightly (v84)

**Comment by cadeyrn** [comment]
You commented yesterday already in four different issues (!) about the same thing - why do we need another issue for basic authentification? What is the difference to all the other issues?

**Comment by Hubfront** [comment]
@cadeyrn Because, unfortunately, my issue was falsely marked (and closed) as dupe of a feature request, that adresses the failure of fenix to work together with a 3rd party password manager when basic auth is used.

In contrary, my bug report addresses a bug of fenix own, internal password manager. My strong opinion is, that fenix internal password manager should handle basic authentification properly as well as it should handle the other types of authentification properly (which it does since some weeks).

**Comment by kbrosnan** [comment]
Closing as a duplicate

**Comment by Hubfront** [comment]
@kbrosnan Why dont you bother to fix this bug?
