### ISSUE TITLE
[Bug] Huge white splash while entering Reader View (dark theme)

### ISSUE THREAD

**Issue by mackeev** [mozilla-mobile/fenix#16294]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
In dark-themed browser, go to, e.g., http://nytimes.com and open any article in Reader view (preliminary set to dark)

### Expected behavior
No splashes or a dark one

### Actual behavior
A long-lasting white splash

### Device information

* Android device: Redmi note 5 pro
* Fenix version: latest Nightly

**Comment by csadilek** [comment]
Thanks for filing, this is fixed in latest Nightly (201104 17:01), @mackeev.
