### ISSUE TITLE
Use full vertical space for tabs tray

### ISSUE THREAD

**Issue by Matth7878** [mozilla-mobile/fenix#16296]
### What is the user problem or growth opportunity you want to see solved?

Tabs tray at best use 90% of vertical space.
It waste space which could be used to display more tabs.

I assume the only benefit is to make it clear than you can swipe it down. As a user I found it annoying as I know it can be swiped down and I would much prefer to use more space.

It would be nice to either always have tabs tray use all vertical space (and get rid of half open which serves nothing) or having an option to do so.

### How do you know that this problem exists today? Why is this important?

Wasted space leading to less visible info from tabs in tabs tray.

### Who will benefit from it?

Everybody

**Comment by kbrosnan** [comment]
We don't intend to change this behavior at this time.
