### ISSUE TITLE
FNX-5146 ⁃ [UX] Tapping on a bookmark opens a new tab which I find counter-intuitive

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#1629]
If I have an open tab and tap 3-dot menu > Library > Bookmarks and tap a bookmark it opens in a new tab. I find this odd, it's different from conventional browsers where actions in a tab always only affect that tab.

(I've raised this issue before, I find Fenix confusing because some actions act on the current tab but other very similar actions create a new tab, it's not always easy to tell what's going to happen)

**Comment by vesta0** [comment]
Thanks for filing. This is the intended behaviour for now but we will look at it during user testing.
