### ISSUE TITLE
Make it easier to open videos in full screen

### ISSUE THREAD

**Issue by dglttr** [mozilla-mobile/fenix#16309]
### What is the user problem or growth opportunity you want to see solved?
Currently, to open a video in full screen-mode, one has to tap a small icon in one edge of the screen. This should be easier and faster.
For example, one could think about **double-tapping the video** (though one has to take care that this doesn't conflict with #6136).
Also related: #2011.

### How do you know that this problem exists today? Why is this important?
Currently, it's not fast/easy to open full-screen mode.

### Who will benefit from it?
Users watching a lot of videos online wishing to to enter directly into a comfortable viewing experience.

**Comment by Dunexus** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/2011
