### ISSUE TITLE
Intermittent gradle-dependencies CI task failure: [taskcluster:error] Task timeout after 14400 seconds. Force killing container.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#16302]
Log: https://treeherder.mozilla.org/logviewer?job_id=320328681&repo=fenix

Got stuck and later terminated after the task hit the time limit:
```
[task 2020-10-31T02:08:21.855Z]   TEST: change the current step
[task 2020-10-31T02:08:21.855Z]     [Robolectric] org.mozilla.fenix.collections.CollectionCreationStoreTest.change the current step: sdk=28; resources=BINARY
[task 2020-10-31T02:08:40.455Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-10-31T02:10:16.055Z]   SUCCESS
[task 2020-10-31T02:10:16.055Z] 
[task 2020-10-31T02:10:16.055Z]   TEST: GIVEN tabs are present in state WHEN getTabs is called THEN tabs will be returned
[task 2020-10-31T02:10:16.455Z]     [Robolectric] org.mozilla.fenix.collections.CollectionCreationStoreTest.GIVEN tabs are present in state WHEN getTabs is called THEN tabs will be returned: sdk=28; resources=BINARY
[task 2020-10-31T02:10:57.255Z]     I/MonitoringInstr: Instrumentation started!

[taskcluster:error] Task timeout after 14400 seconds. Force killing container.
[taskcluster 2020-10-31 05:29:31.261Z] === Task Finished ===
[taskcluster 2020-10-31 05:29:31.261Z] Unsuccessful task run with exit code: -1 completed in 14423.845 seconds
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8591)

**Comment by pocmo** [comment]
This looks like it is now happening on `master` almost always. I'll try to take a look today.

**Comment by mcomella** [comment]
I looked into this a bit with VisualVM: the largest retained objects are from Robolectric.

![image](https://user-images.githubusercontent.com/759372/99123994-26ca4d80-25b6-11eb-9d22-a27df35bd55f.png)

This seems to match up with a known memory leak in robolectric: https://github.com/robolectric/robolectric/issues/5530 This supposedly only occurs on targetSdk=29 https://github.com/robolectric/robolectric/issues/5530#issuecomment-718900627 – I wonder if we should temporarily set the targetSdk lower in the mean time.

As I suspected, we also don't clean up our threads properly but I'm guessing that's less of an issue for this memory leak than the robolectric memory leak:
![image](https://user-images.githubusercontent.com/759372/99124109-68f38f00-25b6-11eb-9578-c04d83cc0e08.png)

Here's the overall memory chart for the process:
![image](https://user-images.githubusercontent.com/759372/99124151-7ad53200-25b6-11eb-8e99-6d8b1c32eb6f.png)

**Comment by mcomella** [comment]
> This supposedly only occurs on targetSdk=29 robolectric/robolectric#5530 (comment) – I wonder if we should temporarily set the targetSdk lower in the mean time.

Oh, robolectric is already set to sdk 28.

**Comment by mcomella** [comment]
I tried with targetSdk=28 and it doesn't seem any better.

**Comment by pocmo** [comment]
Uassigning myself. Landing the workaround was good enough for now.

@mcomella Do we want to file a separate issue for the leaks?

**Comment by pocmo** [comment]
We "fixed" this recently again, by bumping the available memory once more. So it seems like this issue still exists and sooner or later we will hit it again. Briefly looked at updating Robolectric, but that seems to be a very deep rabbit hole, so I moved on for now.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811587

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
