### ISSUE TITLE
Allow backups once again

### ISSUE THREAD

**Issue by ix5** [mozilla-mobile/fenix#16306]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Accompanying issue to Pull https://github.com/mozilla-mobile/fenix/pull/16305

---

### What is the user problem or growth opportunity you want to see solved?

Users expect Android's backup and restore feature to "give them back" their app data upon migrating to a new device.
Rivaling browsers such as Chrome (or Safari on iOS) automatically carry over user data. This process seems seamless to the average user who does not know how tightly coupled Chrome's profiles are to a user's Google account ("Is just works" with Chrome).

Firefox Mobile currently just loses user data upon changing devices if not signed in to the sync service. The Mozilla-proprietary "sync" feature - which is heavily promoted - requires users to once again provide login data on their new devices and currently does not sync their collections (see https://github.com/mozilla-mobile/fenix/issues/4424)

**Technical**
App developers can opt out of the Android backup system by setting `allowBackup=false` in their AndroidManifest.xml (see [Enabling Auto-Backup](https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup) ), as has been done for Fenix in 28ee6ddc21865f5d68301363620d62a3e50732c4
(Following discussion in https://github.com/mozilla-mobile/fenix/issues/4072 )

The app data backup-restore mechanism serves two purposes:

1. **Restore app data upon migration to a new device**
   For most Android devices, this will be done automatically via Google's "GMS backup transport", but others might implement their own backup transport.
   See https://developer.android.com/guide/topics/data/testingbackup#HowBackupWorks

2. **adb commands**
   Give agency to users to (partially) backup/restore application data via adb commands

Not everyone wants to use Mozilla's sync feature. When migrating devices (which is the most common usecase for Android's backup feature), the much better option is to have your settings and bookmarks "automagically" re-appear.

Also note: This does not have to clash with the Mozilla sync feature. It would be even better if the signed-in state of the Mozilla account was automatically restored with a migration as well.

### How do you know that this problem exists today? Why is this important?

https://github.com/mozilla-mobile/fenix/issues/4424
https://github.com/mozilla-mobile/fenix/issues/2080 (and duplicates)
https://github.com/mozilla-mobile/fenix/issues/417

### Who will benefit from it?

- Users who "lost" all their browsing data when switching devices and swore "never again" and simply went back to Chrome.
- Users switching between different flavours of Firefox Mobile (backup files are currently not bound to a signature)

### Issues yet to fix

- Provide a "refresh" mechanism upon new installs with restored user data as suggested in https://github.com/mozilla-mobile/fenix/issues/4072#issuecomment-554661044

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8594)

**Comment by kbrosnan** [comment]
For Android auto backup the Firefox user profile would need to be audited. When this was enabled several years ago it corrupted profiles and Sync data. This would require a significant amount of work from people who have a strong knowledge of the Gecko profile, our Sync data stores and the Fenix data stores and Android backup.

**Comment by superbonaci** [comment]
You are supposed to use Firefox account now. It works well for me. Of course it stores everything on the cloud.

**Comment by jtagcat** [comment]
Collections are not synced. If your device fails, your collections are gone.

**Comment by superbonaci** [comment]
@jtagcat what are collections? Wasn't aware of such thing.
P.S. iOS does allow full backup of Firefox Mobile. I believe that's a rule enforced by Apple, so you can move everything to another device. I don't think google takes this into account...

**Comment by ix5** [comment]
Apps targeting Android 11 will not be able to disable device-to-device transfers of backup anyway [1]. Seems about time Fenix fixed profiles.

[1] https://developer.android.com/about/versions/11/behavior-changes-11#device-to-device-file-transfer

**Comment by superbonaci** [comment]
@ix5 99% of apps don't target Android 11, that would be great in 5 years. Even so, remains to be seen if ALL the data gets transferred, or parts of it at certain locations or specified on manifest whatnot. the iOS approach is perfect.

**Comment by jtagcat** [comment]
> @jtagcat what are collections? Wasn't aware of such thing.
> P.S. iOS does allow full backup of Firefox Mobile. I believe that's a rule enforced by Apple, so you can move everything to another device. I don't think google takes this into account...

essentially bookmark/tab groups (but not that great)
it's like a local destination to share tabs to

**Comment by ix5** [comment]
Discussions going on in https://github.com/mozilla-mobile/fenix/issues/18373

**Comment by ohhai** [comment]
As far as I understand the subject feature will also allow tabs export (mean sessionstore.js or what file it is now). 
Currently seems like no way to do it if tabs number is more than sync limit. Deploying own sync server maybe, but it's not an easy thing.

**Comment by alittlebitofit** [comment]
any updates on Collection sync?

**Comment by cadeyrn** [comment]
> any updates on Collection sync?

This issue is about backups. #4424 is about syncing collections. And no, there is no recent update.

**Comment by SpitFire-666** [comment]
Just wanted to add, that Sync (on desktop at least) does not sync addons' data. For example, uBlock extension will be synced but its config won't be. 

As far as I'm aware, it's difficult to backup/restore addon data without getting your hands dirty. 

https://askubuntu.com/questions/141803/how-can-i-backup-installed-firefox-add-ons-and-restore

On Android, this would be even more fiddly.

**Comment by superbonaci** [comment]
The only option to do it right is to root the device I'm afraid.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808763

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
