### ISSUE TITLE
[Bug] Remote Debugging via USB toggle missing (regression) 

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#16301]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Open Settings.

### Expected behavior

"Remote Debugging via USB" toggle appears, works - can connect via USB. 

### Actual behavior

Remote Debugging via USB toggle is missing, USB debugging doesn't work. 

### Device information

* Android device: Moto G (Android 5.1), LG E970 (Android 5.1.1)
* Fenix version: Friday 10/30

**Comment by cadeyrn** [comment]
USB debugging was disabled for SDK < 23 (API Level 23 = Android 6.0) in https://github.com/mozilla-mobile/fenix/issues/16250.

**Comment by kbrosnan** [comment]
This was intentionality removed. You will need to use Reference Browser, Geckoview Example or a self built version with debugging re-enabled
