### ISSUE TITLE
[Bug]scrolling smoothness webrender Vs open gl 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#16307]
on my phone scrolling smoothness is light years better force disabling webrender (and defaulting to open gl).
I took a video first part is the extremely jumpy scrolling with webrender second part is with open gl BUTTERY SMOOTH. 
is this normal? 
video :
https://drive.google.com/file/d/1bVdaTsCmhb4B47r8vSEp5_m8oqWqTW6m/view
 for what matters I M on latest nighlty.

**Comment by ale82to** [comment]
my cpu is a snapdragon 652 andremo 510 gpu.

**Comment by Cheap-Skate** [comment]
Probably this, I think it's a general bug not just Mali

 https://bugzilla.mozilla.org/show_bug.cgi?id=1658205

**Comment by jamienicol** [comment]
@ale82to does this happen on all websites or just some in particular?

Would you be able to capture a performance profile of the problem? If you've never done this before, the steps are:
* In Firefox's settings menu on your phone, enable "Remote debugging via USB"
* Plug in your phone via USB to your computer.
* Open about:debugging in Firefox on your computer.
* Click "Enable USB devices", then click the "connect" button by your phone on the left hand side, and click again to select your phone.
* Click "profile performance"
* From the settings dropdown menu, select "Firefox Graphics"
* Navigate to the slow page on your phone.
* Click "start recording" on your computer.
* On your phone scroll around a bit on the page, for about 10 seconds, then click "capture recording"
* The profile should open up in a new tab. wait for it to finish loading them click the "publish" button in the top right corner, then share the link here.

Please let me know if you have any problems with that and I can help you out. Thanks!

**Comment by Cheap-Skate** [comment]
I see more WebRender scroll jank on my Galaxy A40 (Mali) than on my Xperia X Compact (Snapdragon 650, Adreno 510). The Xperia is pretty smooth, nearly as good as WebRender off.

I think scroll jank on the A40 might have reduced somewhat over the last couple of months (since I filed 1658205), but it's still not great.

But my Xperia has substantially the same CPU/GPU as @ale82to , and it scrolls pretty well. I've only checked mozilla.org and a couple of other sites. So I don't know what's going on.

**Comment by ale82to** [comment]
yes happen to every websites and from version 79 in latest nightly is even worse,  i cannot provide profile performance as I don't have a PC right now

**Comment by ale82to** [comment]
yes I make the issue more prominent because I modify in about:config apz.android.chrome_fling_physics.inflexion(0.28) and apz.android.chrome_fling_physics.friction(0.0020) ? 
to get a super smooth scroll like iOS.
that's the only reason I M using Firefox over Samsung browser wich is far more customizable and complete (I really need support for keyboard Shortcuts)
sorry for the long answer.

**Comment by mcomella** [comment]
@ale82to Would you be able to get a profile now? (I'm not sure if you have access to a PC now.) It would be extremely helpful for debugging this issue.

Triage: after we have a profile, we can move this to the platform team on Bugzilla.

**Comment by mcomella** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1687840

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
