### ISSUE TITLE
Location of 'Data Choices'

### ISSUE THREAD

**Issue by mtris** [mozilla-mobile/fenix#16304]
Re: Fennec F-Droid v82.1.1 downloaded from F-Droid

Hello Fennec F-Droid Fans: This is my first try with this browser. I like the sleek design.
The question I have is regarding the Privacy/Data Choices. I see articles mention it's Settings>Privacy & Security>Data Choices - but on my version I do not see that listed under Privacy or any of the Sub-sections. Could anyone tell me where it's located on this version, or how it's handled? Thanks very much for your time and consideration. Sincerely,

**Comment by anotherus3r** [comment]
AFAIK telemetry is stripped from Fennec F-Droid, so the Data Choices menu was probably removed with it, too.

**Comment by mtris** [comment]
Hi: Thanks for the reply. It's cool if the telemetry is stripped.
I see the F-Droid anti-feature 'This app tracks and reports your activity', and wondered what is tracked/reported, etc.  I appreciate the input, and hope everyone enjoyed their weekend. Sincerely,

**Comment by kbrosnan** [comment]
This is not a bug report. For Firefox see https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-browsers For f-droid questions please ask in the f-droid forums.
