### ISSUE TITLE
[Bug] Some UI tests disable device's long press action

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#16317]
## Steps to reproduce
* Run UI test, on a device, that changes the device's `long_press_timeout` such as `TabbedBrowsingTest.kt`
* After the test ends attempt to initiate a long press action such as long press on homescreen to add a widget.

### Expected behavior
* Long press action should execute as normal
### Actual behavior
* No long press action executes anymore
### Device information

* Android device: Pixel 3XL, Android 10
* Fenix version: 
<img src="https://user-images.githubusercontent.com/60002907/97876046-eea84c80-1d23-11eb-8981-ef9c118f9f52.png" width="250"/>

It appears that UI tests use `mDevice.executeShellCommand("settings put secure long_press_timeout 3000")` to change long press timeout without changing it back on `@After` resulting in an unknown Touch & hold delay value (Accessibility options):

<img src="https://user-images.githubusercontent.com/60002907/97876322-59f21e80-1d24-11eb-810a-bfe5e1220d2b.png" width="300" />

**Comment by Mugurell** [comment]
@sv-ohorvath I see in the recent patch that we would still leave the device with a possibly different touch delay than before running the tests.
The user could have set medium/long delays and would prefer to keep them.
Maybe we could use something like `android.view.ViewConfiguration.getLongPressTimeout()` to cache the device's set delays before running the tests and set that same exact value in `afterActivityFinished`?

I see `afterActivityFinished` being called even if the test encounters an exception so this is great - cleanup is ensured without the need for a try-catch / our own `Thread.setDefaultUncaughtExceptionHandler()`
