### ISSUE TITLE
[Bug]scrolling is not smooth 

### ISSUE THREAD

**Issue by helperman** [mozilla-mobile/fenix#16319]
Scrolling is not smooth on the Web site:
https://utmagazine.ru/finansoviy-slovar-treidera

See how to reproduce here
https://youtu.be/FkzMfUfM0I8

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1674837

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
@helperman is this still a problem for you. The Graphics team has implemented several improvements that should allow Firefox to use the GPU to accelerate its performance. https://bugzilla.mozilla.org/show_bug.cgi?id=1674837#c9
