### ISSUE TITLE
FNX-5148 ⁃ Fenix should work in landscape mode

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1631]
As a user, I want to be able to use all Fenix features in Landscape mode so I can have flexibility in using my browser. 

### Acceptance Criteria:
-I can use all Fenix functions in landscape mode without any user experience issues.
-I can perform all scrolling, tapping, input actions.
-I can access and change any settings.

**Comment by bsurd** [comment]
This has been tested and verified by QA, removing the QA needed label but leaving the issue open until all blocking/related issues are fixed.

**Comment by vesta0** [comment]
Closing this ticket and tracking any related existing or new bugs through the `landscape` tag
