### ISSUE TITLE
FNX-5149 ⁃ [Bug] (Regression) Dock keyboard when viewing recent apps

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1632]
## Steps to reproduce
1. Tap the search bar to launch de keyboard.
1. Open the recent apps tray.
    1. Expected behavior
The keyboard is hidden.
    1. Actual behavior
The keyboard remains displayed on top.
    1. Device information

* Android device: Nexus 5 (Android 6), Galaxy Tab 3 (Android 8), Galaxy S8 (android 9).
* Fenix version: 4/14 build.

**Comment by sblatz** [comment]
Lets do a `hideKeyboard` onPause and `showKeyboard` onResume. We took out the hide keyboard functionality on purpose, because it was originally calling keyboard back press (which would take the user to the home fragment)
