### ISSUE TITLE
[Bug] Space between tab tray grid item borders

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#16323]
As a followup to #15968 which added a new border,
there is a small gap between the borders of the items shown:
![image](https://user-images.githubusercontent.com/11428869/97890780-a3e40000-1d36-11eb-906e-5a8f065ddd2d.png)

The dimensions follow the specs but I think this is happening because
Currently we are using a 8dp cornerRadius for both the inner and the other borders.
I think a solution would be to use

#### 10dp cornerRadius for the outer border ⌄
![image](https://user-images.githubusercontent.com/11428869/97895460-7c903180-1d3c-11eb-8282-b170aff0ba90.png)

#### 6dp cornerRadius for the inner border ⌄
![image](https://user-images.githubusercontent.com/11428869/97896069-40a99c00-1d3d-11eb-92ce-f3946c74e9d5.png)

**Comment by Mugurell** [comment]
@topotropic Does the solutions above sounds okay with you?

**Comment by topotropic** [comment]
thanks @Mugurell, let's go with 10dp cornerRadius for the outer border

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201105`** using a Google Pixel 3a (Android 11)


► Portrait screenshot
![rsz_screenshot_20201105-095412222](https://user-images.githubusercontent.com/51314259/98213743-314d6d00-1f4e-11eb-9e30-584402be9230.png)

► Landscape screenshot
![rsz_screenshot_20201105-09542555555](https://user-images.githubusercontent.com/51314259/98213750-34e0f400-1f4e-11eb-8537-cca7c99831ac.png)
