### ISSUE TITLE
[webcontent] PDF download fails

### ISSUE THREAD

**Issue by magware-dev** [mozilla-mobile/fenix#16331]
## Site with issue and any steps to reproduce

Try to download the official daily COVID-19 report of the spanish government at:

Direct link to PDF of today: https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Actualizacion_241_COVID-19.pdf 

The most recent PDF can be accessed via https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/situacionActual.htm => link: Actualización nºXXX: enfermedad por SARS-CoV-2 (COVID-19) DD.MM.YYYY

The issue started maybe 1 or 2 weeks ago, with all new daily PDFs. Before that, the download always worked. 

This also happens sometime with other PDFs, but the one mentioned above always fails like described below.

### Expected behavior

After confirmation the PDF downloads

### Actual behavior

After confirmation the download notification spins for about an hour and then fails.

![Screenshot_20201102-225629](https://user-images.githubusercontent.com/56974309/97924648-482e6c80-1d60-11eb-81cc-dfdb9c2a2e8b.png)

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

no

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Download in Chrome works just fine

### Device information

* Android device: Nokia 7.1 / Android 10
* Fenix version: 82.1.1

**Comment by RachitKeertiDas** [comment]
Hello,

I can seem to download the pdfs just fine on Firefox Nightly.  

- Fenix Version : 84.0
 
P.S. : Not a Mozilla developer

**Comment by J41319** [comment]
Same problem?

(https://github.com/mozilla-mobile/fenix/issues/16144)

**Comment by Amejia481** [comment]
Thanks for reporting  @magware-dev, the issue looks similar to https://github.com/mozilla-mobile/fenix/issues/15378
I think it's fixed in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). Would you mind trying on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to see if it's fixed for you? 

I will also ask the QA team to test a they have a wide range of devices.

**Comment by AndiAJ** [comment]
Hi @Amejia481 , it **works properly** on the latest **`Nightly Build 201105`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20201105-102145](https://user-images.githubusercontent.com/51314259/98216377-a8383500-1f51-11eb-8c29-d9436c9fe79d.gif)

@magware-dev If you still encounter any problems please re-open this issue. ☺️

**Comment by Amejia481** [comment]
@AndiAJ  thanks!
