### ISSUE TITLE
[Bug] Pass a crashReporter to FxaAccountManager

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#16339]
At the moment we are not passing an instance of `CrashReporter` to `FxaAccountManager` and so we will loose some FXA exceptions reports.

Seen while trying to test #10662.

There is a separate AC issue - https://github.com/mozilla-mobile/android-components/issues/8877 for the crashReporter further being passed to `FirefoxAccount` and `FxaDeviceConstellation`

**Comment by Mugurell** [comment]
Waiting for https://github.com/mozilla-mobile/android-components/issues/8877 to also be merged to be able to easily test this.
Setting `qa:no-needed` until then.

**Comment by Mugurell** [comment]
Maybe more of a manual integration test we can now check that a fxa exception is successfully logged.
How I tested before and after:
- be logged in on Fenix and on another app/device/platform with the same account
- open the share menu on Fenix; the other devices should appear as share targets
- on the other device change the account password
- on Fenix tap that device to share to

Expected result: 
- a snackbar with a message about sharing failed
- a log similar to "I/mozac/CrashReporter: Caught Exception report submitted to 2 services"
- the exception can be queried on Socorro and Sentry.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 18/11** with **Google Pixel 4 XL (11).**
Note that the snackbar was correctly displayed following the steps from the above and the log in the Logcat.
