### ISSUE TITLE
[Bug] Scrolling horizontally doesnt work properly on Ff nightly 

### ISSUE THREAD

**Issue by Blaze-Thunder** [mozilla-mobile/fenix#16336]
[comment]: When we scroll horizontally on a page snippet, the elements are not scrolled and disappearing. Same is not happening when the element is scrolled on top of screen. This issue is only on ff nightly. Not happening on beta and stable. 

## Steps to reproduce

Open m.sakshi.com 
Scroll down and swipe horizontally 

### Expected behavior

Elements scrolling should happen normally

### Actual behavior

Elements are disappearing 

### Device information
OnePlus 7pro

* Android device: Android 10
* Fenix version: nightly 201102 17:00

**Comment by Blaze-Thunder** [comment]
![ezgif-6-d1b84227bb43.gif](https://user-images.githubusercontent.com/64011423/97951469-47c5be00-1dc0-11eb-9222-589be1bf5d8e.gif)

Attached video

**Comment by Blaze-Thunder** [comment]
![ezgif-6-d1b84227bb43](https://user-images.githubusercontent.com/64011423/97951604-ba369e00-1dc0-11eb-8e93-a08ff5bcd0ac.gif)

**Comment by Blaze-Thunder** [comment]
![ezgif-6-60d40489ab70.gif](https://user-images.githubusercontent.com/64011423/97953861-c83bed00-1dc7-11eb-8ef2-93afcc3eb17c.gif)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1675076

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
