### ISSUE TITLE
[Bug] ff is not offered as a browser by hw keyboard shortcut

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#16334]
pressing 🔎B (Meta-b) on hw keyboard ff is not offered as a browser

![Screenshot_20201103-035310_Settings](https://user-images.githubusercontent.com/14617699/97934945-352f9280-1d88-11eb-9f9b-c2382fcc9052.png)

![Screenshot_20201102-131450_Android_System](https://user-images.githubusercontent.com/14617699/97934969-45e00880-1d88-11eb-9d1a-0a25570ae8a8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8609)

**Comment by dominicm00** [comment]
This currently appears to work as intended: Firefox (both stable and nightly) show as options when the CMD-B shortcut is pressed.

Tested on Tab S7+ (SM-T970), Android 11, One UI 3.1

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808764

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
