### ISSUE TITLE
Tap on a link does not open the link

### ISSUE THREAD

**Issue by j13ag0** [mozilla-mobile/fenix#16337]
Firefox for Android:
Firefox:  82.1.1  (Build: #2015770923)
Hardware:  Google Pixel 3a
OS:  Android 10

Steps:
- Navigate to any page in Firefox.
- tap on a link on the page to navigate to it - nothing happens.
- long tap presents the menu with options to:  Open link in new tab, Open link in private tab etc.

Sometimes the screen jumps when a link is tapped.
Rarely, perhaps the first attempt to follow a link after starting Firefox, the link will be followed, but generally not.
Upon further testing, links are sometimes followed

**Comment by j13ag0** [comment]
Just updated to Android 11 on the device.
The problem persists.

**Comment by PhilAnderson1** [comment]
Having the exact same problem here after a recent update

Firefox: 82.1.1
Hardware: OnePlus 8
Android version: OxygenOS 10.5.10

**Comment by kbrosnan** [comment]
Does this happen on the [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) build? Is there a specific site(s) this is more common on? Do you have toolbar on top? Do you have any addons enabled?

**Comment by j13ag0** [comment]
I do have the toolbar on top.
I'm pretty sure I'm not using addons.
I have not tested on a nightly build.
All sites pretty much act the same way - tap does not navigate to tapped link.

**Comment by j13ag0** [comment]
Moving the toolbar to the bottom does not change the behaviour.

**Comment by PhilAnderson1** [comment]
> Does this happen on the [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) build? Is there a specific site(s) this is more common on? Do you have toolbar on top? Do you have any addons enabled?

Yes, I have just tested the nightly and it still has the problem

It happens on all sites, e.g. https://bbc.co.uk/news

I have the toolbar on the bottom

I have no add-ons enabled

**Comment by DarthNovi** [comment]
I have this problem on my Android 7 tablet running 82.1.1.  I haven't noticed it on my Android 9 and 10 phones.  Firefox menus and functions seems to work normally - only actual web page browsing has the bug(s).

The first action (tap, drag, etc.) on a web page frequently produces an unexpected jump or zoom.  While dragging/scrolling works, it frequently stalls or jumps.  Tapping links doesn't work.  Selecting text input fields doesn't work (no cursor or keyboard appears).  Pinch/zoom doesn't work.  Long-pressing links sometimes works but I've had it bring up a menu without navigation options (only Copy Link, etc.).

Glad to provide any additional information or testing within my limits as an end user.

**Comment by Mugurell** [comment]
Hello
Does this reproduces constantly for you?
If so can you please also try on [GVE](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt)(geckoview-example.apk) and report back if you see it also happening there?

Once we have clear steps to reproduce we can work towards a solution but at the moment this seems to be sporadically happening and I'm having trouble reproducing it.

**Comment by PhilAnderson1** [comment]
> Hello
> Does this reproduces constantly for you?
> If so can you please also try on [GVE](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt)(geckoview-example.apk) and report back if you see it also happening there?
> 
> Once we have clear steps to reproduce we can work towards a solution but at the moment this seems to be sporadically happening and I'm having trouble reproducing it.

Yes, it is consistent on my OnePlus 8. Virtually none of the links on the BBC news website ( https://bbc.co.uk/news ) work for me.

When links don't work, I find i can sometimes get them to work by pressing them for about half a second (e.g. just a bit too short for the 'open link in new tab' dialog to pop up).

I tried geckoview-example.apk, that works fine without any problems.

**Comment by j13ag0** [comment]
I find that this problem still occurs but is somewhat less prevalent on Firefox Nightly.

**Comment by PhilAnderson1** [comment]
I've just tried the nightly - it's absolutely no different for me.

**Comment by ekager** [comment]
@j13ag0 @PhilAnderson1 does this problem still exist in Nightly?

**Comment by PhilAnderson1** [comment]
> @j13ag0 @PhilAnderson1 does this problem still exist in Nightly?

no, it doesn't - I've just tried the nightly and the problem seems to have been fixed.

**Comment by bluberly** [comment]
in my case https://github.com/mozilla-mobile/fenix/issues/16506 the problem went away after I had installed the Opera browser (installing the FF browwer hadn't helped, removing, re-installing Nightly either. Rebooting the device also hadn't helped).
