### ISSUE TITLE
FNX-5150 ⁃ [Bug] "Open new tab" from PB just opens the homescreen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1633]
## Steps to reproduce
1. Open a webpage in PB.
1. From the main menu, tap "New tab".
    1. Expected behavior
A new tab is created in normal browsing: the search bar edit mode is opened.
    1. Actual behavior
The normal browsing home screen is displayed.
    1. Device information

* Android device: Galaxy Tab 3 (Android 8), Nexus 5 (Android 6).
Not reproducing on Galaxy S8 (Android 9)
* Fenix version: 4/14 build.

**Comment by ekager** [comment]
Can reproduce on my Moto E device.
