### ISSUE TITLE
FNX-5151 ⁃ [Bug] 3 dot menu overscroll glow doesn't match menu shape

### ISSUE THREAD

**Issue by Dunexus** [mozilla-mobile/fenix#1634]
## Steps to reproduce
Open any 3 dots menu and scroll.

### Expected behavior
Overscroll glow should match the shape of the menu (rounded square).

### Actual behavior
Overscroll glow start below the rounded corners.
![Screenshot](https://user-images.githubusercontent.com/13906248/56124861-e341d480-5f77-11e9-864d-5db4fdf0e86f.jpg)UNITO-UNDERSCORE!20190415-112407!UNITO-UNDERSCORE!!UNITO-UNDERSCORE!01!

### Device information
* Android device: OnePlus 5T (Android 9)
* Fenix version: 1.0.1915 (Build #11021215) - 4/12

**Comment by vesta0** [comment]
@lime124 UX feedback required on whether we want to change this (also do we want to remove overscroll for mvp?)

**Comment by AmyYLee** [comment]
I think this should be fixed (or removed). It looks unpolished in it's currently state.

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1) 
• Sony Xperia Z3 (Android 5.1.1)

**Comment by Dunexus** [comment]
I can confirmed it is fixed on my device :
OnePlus 5T (Android 9)
