### ISSUE TITLE
[Bug][a11y] Consider increasing contrast ratio in dark theme for "CANCEL"/"OK" buttons from "Add new collection" card

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16343]
## Steps to reproduce 
1. Have the Accessibility scanner installed and opened.
2. In Fenix, set the theme to dark.
3. Open several tabs.
4. Open the tabs tray. 
5. Long-tap on one of the tabs in order to create a collection.
6. Scan the "Add new collection" card.

### Expected behavior
No major suggestions are made.

### Actual behavior
Text contrast
android:id/button2
The item's text contrast ratio is 3.99. This ratio is based on an estimated foreground color of #AB71FF and an estimated background color of #32313C. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 11/3 Nightly

![Untitled](https://user-images.githubusercontent.com/40694158/97972769-b4938500-1dcd-11eb-9439-82984fe0e329.png)

**Comment by priyanka0906** [comment]
@eliserichards  I want to work on this . Please assign this to me

**Comment by eliserichards** [comment]
This needs UX approval if we are going to change the theme colors. Tagging @topotropic for thoughts :)

**Comment by topotropic** [comment]
Yes, this looks like a bigger endeavor since this is part of the theme. I'll put it in the UX backlog.

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01
