### ISSUE TITLE
[Bug][a11y] "Light theme"/"Dark theme" is identical to that of 2 other item(s)

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16341]
## Steps to reproduce 
1. Have the Accessibility scanner installed and opened.
2. Have a clean profile of Firefox Nightly.
3. Scan the onboarding theme's card.

### Expected behavior
No suggestions are made.

### Actual behavior
Multiple items have the same description.
This clickable item's speakable text: "Light theme"/"Dark theme" is identical to that of 2 other item(s).

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 11/3 Nightly

![Untitled](https://user-images.githubusercontent.com/40694158/97966066-fb7c7d00-1dc3-11eb-862c-7f47bd0f789b.png)

**Comment by jawz101** [comment]
https://support.google.com/accessibility/android/answer/6376570?hl=en#:~:text= Get started with Accessibility Scanner%20 1,change the thresholds that Scanner uses... More%20

**Comment by miralobontiu** [comment]
This issue still reproduces on the Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9) on the 5/16 Nightly build.

**Comment by lobontiumira** [comment]
Reproducible on 11/2 Nightly build with Google Pixel (Android 10).
