### ISSUE TITLE
[Bug][a11y] Consider increasing the contrast ratio on the counter text in the tabs tray

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16344]
## Steps to reproduce 
1. Have the Accessibility scanner installed and opened.
2. In Fenix, set the theme to light.
3. Open several tabs in normal browsing.
4. Open the private tabs tray.
5. Scan the private tabs tray.

### Expected behavior
No suggestions are made.

### Actual behavior
Text contrast
org.mozilla.fenix:id/counter_text
The item's text contrast ratio is 2.71. This ratio is based on an estimated foreground color of #9996B3 and an estimated background color of #F9F9FB. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 11/3 Nightly
 
![Untitled](https://user-images.githubusercontent.com/40694158/97974714-abf07e00-1dd0-11eb-9f9b-5db91459bd54.png)

**Comment by miralobontiu** [comment]
This issue no longer reproduces.
Tested with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9) on the 5/16 Nightly build.
