### ISSUE TITLE
[Bug][a11y] Consider increasing the themes radio buttons

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#16342]
## Steps to reproduce 
1. Have the Accessibility scanner installed and opened.
2. Have a clean profile of Firefox Nightly.
3. Scan the onboarding theme's card.

### Expected behavior
No suggestions are made.

### Actual behavior
org.mozilla.fenix:id/theme_light_radio_button
org.mozilla.fenix:id/theme_dark_radio_button
This item's size is 32dp x 32dp. Consider making this touch target 48dp wide and 48dp high or larger.

org.mozilla.fenix:id/theme_automatic_radio_button
This item's height is 37dp. Consider making the height of this touch target 48dp or larger.

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 11/3 Nightly

**Comment by mcarare** [comment]
This was previously discussed here: https://github.com/mozilla-mobile/fenix/issues/9583#issuecomment-609987250.
Having the entire image as a surface that can be pressed to change themes makes the radio button touch target irrelevant. 
Closing this as such.
