### ISSUE TITLE
Ability to display number of open tabs when exceeds 99

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#16363]
When open tabs exceed 99 it just displays infinite symbol. Would like to have a way to see how many there are exactly.

![](https://i.imgur.com/06pJuZi.jpg)

**Comment by superbonaci** [comment]
Just displaying them on tabs menu and synced tabs would be enough.

**Comment by kbrosnan** [comment]
Closing as a duplicate of #14886

**Comment by superbonaci** [comment]
The issue has not been fixed.
