### ISSUE TITLE
Firefox not launching on Android 6.0

### ISSUE THREAD

**Issue by wloeffelsend** [mozilla-mobile/fenix#16366]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
I have an Android mobile 6.0. I used Mozilla Firefox since years. But now it does´t work. I install but nothing happens. If I click on the FF Symbol I cannot see anything. Can you help me. The German Mozilla Forum could not help. They told me to contact you.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment]
What device? What exactly happens wwh en you launch Firefox? Screenshot or video would be helpful. If possible a logcat should provide useful information. See https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information

**Comment by wloeffelsend** [comment]
Hi,

it is an LG 4c. I cannot send a screenshot because nothing happens if I
click on the FF. I do not know what a log cat is and how it works.

Mit freundlichen Grüßen
Werner Löffelsend
Gerresheimer Landstr. 139
40627 Düsseldorf
Tel.: 0211 202891
Mobil: 017647073318
E-Mail wloeffelsend@gmail.com <wloeffelsend@web.de> *NEU*
werner.loeffelsend@epost.de


Am Mi., 4. Nov. 2020 um 12:33 Uhr schrieb Kevin Brosnan <
notifications@github.com>:

**Comment by wloeffelsend** [comment]
Please answer my post.

**Comment by kbrosnan** [comment]
This is not a support forum. We need a logcat as I described in my first reply to make progress in understanding the problem you are experiencing.

**Comment by wloeffelsend** [comment]
Thanks for the answer. I do not know what a logcat is. What is that? I
cannot find a German Translation.

Mit freundlichen Grüßen
Werner Löffelsend
Gerresheimer Landstr. 139
40627 Düsseldorf
Tel.: 0211 202891
Mobil: 017647073318
E-Mail wloeffelsend@gmail.com <wloeffelsend@web.de> *NEU*
werner.loeffelsend@epost.de


Am So., 8. Nov. 2020 um 00:42 Uhr schrieb Kevin Brosnan <
notifications@github.com>:

**Comment by cadeyrn** [comment]
Please see https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information (@kbrosnan already mentioned the link in his first answer).

**Comment by wloeffelsend** [comment]
Auch die Übersetzung hilft mir nicht weiter. Das alles überfordert mich.
Adieu Firefox.
Danke noch mal für die Hilfe.

Mit freundlichen Grüßen
Werner Löffelsend
Gerresheimer Landstr. 139
40627 Düsseldorf
Tel.: 0211 202891
Mobil: 017647073318
E-Mail wloeffelsend@gmail.com <wloeffelsend@web.de> *NEU*
werner.loeffelsend@epost.de


Am So., 8. Nov. 2020 um 09:31 Uhr schrieb Sören Hentzschel <
notifications@github.com>:
