### ISSUE TITLE
[Bug] sometimes crash when playing video

### ISSUE THREAD

**Issue by stevenleeS0ht** [mozilla-mobile/fenix#16362]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

playing video from any source (YouTube, ...) or some virtual meeting service (blackboard, MS teams, zoom), It has possibility to crash.

### Expected behavior

Playing video for any long period except user quit manually.

### Actual behavior

suddenly crash.

### Device information

* Android device: (This problem appears on several device) android version 10
* Fenix version: 82.1.1 (Build '#821120')
AC: 60.0.5
GV: 82.0-20201022145252

**Comment by kbrosnan** [comment]
Please get crash IDs https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by stevenleeS0ht** [comment]
@kbrosnan , It is not identified as a crash by Fennec F-Droid, but it indeed quit the program.

It might possible that the problem is from small window video player.

**Comment by ekager** [comment]
Closing as there's no STR and no crash log. 
If you get a crash dialog, make sure to hit "Report" and then check about:crashes again.
(If you can find a crash log, feel free to open a new issue)
