### ISSUE TITLE
Top sites "Rename" string missing on Pontoon

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#16367]
Issue #9548 brought us the renaming option for top sites, accessible by long pressing any of them. The string for this context menu item is currently missing on Pontoon, so for now it can't be localised.

**Comment by kbrosnan** [comment]
@Delphine @gabrielluong would you sort out if there is a change needed on the Fenix side.

**Comment by Delphine** [comment]
Not sure what is asked of me here?
If the string isn't in Pontoon, it means it needs to be exported by devs and then exposed to localizers as part of the usual process (and this wasn't done yet, apparently).

**Comment by anotherus3r** [comment]
Oh okay, thought it was somehow missed since the option was available for a few days now.
