### ISSUE TITLE
[Bug] The visibilitychange event is not dispatched when the screen is locked and the video is playing and has sound.

### ISSUE THREAD

**Issue by jomisica** [mozilla-mobile/fenix#16365]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
You can test this video on this page: https: //www.sleeping.pt/wp/2020/10/09/video-stream/

### Expected behavior
Let the 'visibilitychange' event be dispatched, so that it allows me to decide whether it makes sense or not to pause the video.

### Actual behavior
The visibilitychange event is not dispatched when we lock the screen, whenever the video has sound and is not muted.

### Device information

* Android device: A20e
* Fenix version: 82.1.1

**Comment by jomisica** [comment]
The same happens when we change the tab. With this problem it is not possible to create any logic that will save battery on mobile devices. It's not just about videos. The event must be dispatched whenever the page's visibility changes.

**Comment by jomisica** [comment]
In version: 84.1.2 it already works well.
In version: 85.0.0-beta.4 it already works well.

Thanks!

**Comment by amedyne** [comment]
Closing this per latest comment.
