### ISSUE TITLE
FNX-5154 ⁃ [Bug] Page title appears in browser toolbar above URL sometimes when page is loaded from prior session

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1637]
## Steps to reproduce
1. Open Fenix
1. Load https://www.nytimes.com/2019/04/14/technology/china-surveillance-artificial-intelligence-racial-profiling.html from a saved session

### Expected behavior
Page URL appears in location toolbar. 

### Actual behavior
Page title appears above page URL

![signal-attachment-2019-04-15-125252](https://user-images.githubusercontent.com/152493/56150707-7598a700-5f7d-11e9-8635-83e7f45f82da.png)

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1916 #11051220

**Comment by ekager** [comment]
Should be fixed by #1611
