### ISSUE TITLE
Test the view hierarchy depth on startup and count the number of ConstraintLayout in RecyclerView children

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#16376]
View hierarchy depth has an impact on performance and we should try to limit the number of levels we have. For startup, this would include traversing the startup views and counting its number of levels to make sure these don't vary to much. 

Time: 3 Days

**Comment by mcomella** [comment]
I opened a PR for both of these https://github.com/mozilla-mobile/fenix/pull/16514

**Comment by mcomella** [comment]
PR merged in https://github.com/mozilla-mobile/fenix/commit/72ab058551244bd0451d56c8c9bbcaa72849758c
