### ISSUE TITLE
Count useage of PackageManager and, at the same time, investigate the time it takes per call to it.

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#16375]
PackageManager seems to be pretty slow. Its use should be limited and wrapping it (similarly to StrictMode / `runBlocking`) to monitor it seems the best way to do so. At the same time, we should investigate the time it takes per calls to `PackageManager` for future reference.

Time: 3 Days

**Comment by MarcLeclair** [comment]
So we can see that the PackageManager takes a while for certain calls only

`
org.mozilla.fenix.debug E/packageManager:  initial 0
org.mozilla.fenix.debug E/packageManager: default icon 13
org.mozilla.fenix.debug E/packageManager: instantAppCookie 22
org.mozilla.fenix.debug E/packageManager: instantAppCookieMaxBytes 1
org.mozilla.fenix.debug E/packageManager: is deviceUpgrading 1
org.mozilla.fenix.debug E/packageManager: is instantApp 0
org.mozilla.fenix.debug E/packageManager: is safeMode 0
org.mozilla.fenix.debug E/packageManager: ispckgManagerSuspended 0
org.mozilla.fenix.debug E/packageManager: packageInstaller 1
org.mozilla.fenix.debug E/packageManager: suspendedPackageAppExtras 0
org.mozilla.fenix.debug E/packageManager: systemAvailableFeatures 0
org.mozilla.fenix.debug E/packageManager: systemSharedLibraryNames 0
`

from these logs, only loading `instantAppCookie` and `defaultAPpIcon` seems problematic. These logs were taken  on a Samsung Lite S6 ( tablet) whos processor is quite strong.

Here's the logs on a g5 + 

`
org.mozilla.fenix.debug E/packageManager:  initial 0
org.mozilla.fenix.debug E/packageManager: default icon 34
org.mozilla.fenix.debug E/packageManager: instantAppCookie 38
org.mozilla.fenix.debug E/packageManager: instantAppCookieMaxBytes 1
org.mozilla.fenix.debug E/packageManager: is instantApp 0
org.mozilla.fenix.debug E/packageManager: is safeMode 0
org.mozilla.fenix.debug E/packageManager: packageInstaller 1
org.mozilla.fenix.debug E/packageManager: systemAvailableFeatures 5
org.mozilla.fenix.debug E/packageManager: systemSharedLibraryNames 1
`

My suggestion is to still monitor it as we did with other things (such as lazyMonitored and RunBlocking) especially with issues in the past with PackageManager where we can 1) monitor them and 2) make sure the work of PackageManager is offloaded to a background thread.  Ideally, it would be good to use just strictMode to detect it but StrictMode doesn't crash on every calls that is made by the packageManager. StrictMode will only trigger with the following calls to packageManager: `packageManager.instantAppCookie`, the rest will usually just work fine even with StrictMode

**Comment by mcomella** [comment]
We can refile this if we want to do more of these.
