### ISSUE TITLE
Allow users to enable/disable site access to motion sensors

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#16385]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
tracking and privacy.

### How do you know that this problem exists today? Why is this important?
https://sensor-js.xyz/
and across various sites when the motion sensor permission is disabled in a chromium based browser on desktop.

### Who will benefit from it?
general users. and no, not just people who care for their privacy (as all the privacy advocates say :P)

I'd expect both a way to control this for all sites and to control it per-site, like chromium for desktop

I say enable/disable because there needs to be a decision about defaults. It really should be an opt-in permission honestly but that'd require spec work.

Funnily enough, Firefox for desktop doesn't provide websites with orientation, accelerometer and gyroscope data. Like Fenix, it doesn't provide users a setting to control this.

This is also related to another issue about per-site permission controls like Chromium for desktop.

Chromium for Android and desktop let you disable this permission in a user-facing setting.

just for searchers, i'll put this here:
sensor data from mobile devices using deviceorientation and devicemotion events

edit:
hmmm. https://bugs.chromium.org/p/chromium/issues/detail?id=947112

https://www.w3.org/TR/orientation-event

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8644)

**Comment by s-ankur** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/11460

**Comment by Poopooracoocoo** [comment]
Just to clarify, my edit is referring to the new-ish permissions. It's been a long time coming.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807447

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
