### ISSUE TITLE
Phone QR does not open phone app

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16388]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
On desktop open https://www.the-qrcode-generator.com/ and go to phone and enter your phone number
Scan the qr, keeping open in app on

### Expected behavior
It opens the phone app. I think firefox does not handle tel: link properly
### Actual behavior
It does not
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8647)

**Comment by s-ankur** [comment]
It handles tel links just fine idk why it doesn't open then via qr
<a href="tel:55555555">

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807384

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
