### ISSUE TITLE
[Bug][a11y] Reader mode "Appearance" control menu - Dark

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16387]
Related to #18708, #18709, #18710 

## Steps to reproduce 
1. Have the Accessibility scanner installed and opened.
2. Go to a site with a lot of text content (e.g.wikipedia).
3. Enable "Reader view" from the navigation bar.
4. From the three-dot menu, tap on the "Appearance" menu.
5. Scan the "Appearance" control menu.

### Expected behavior
No suggestions are made.

### Actual behavior
Some suggestions are made for the **"Dark"** button: 
* Touch target
org.mozilla.fenix:id/mozac_browser_toolbar_security_indicator
This item's size is 40dp x 40dp. Consider making this touch target 48dp wide and 48dp high or larger. A parent container may be handling touch events for this item. If selecting the larger container performs the same action as selecting this item, consider defining this item as not clickable. If a different action is performed, consider increasing the size of this item.

<img src="https://user-images.githubusercontent.com/40694158/98212390-30b3d700-1f4c-11eb-9741-36005bf855ee.png" width="300" height="550" />

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 11/3 Nightly build

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8646)

**Comment by sflorean** [comment]
Reproducible on Beta 86.0.0-beta.2 - Huawei P40 Lite (Android 11).

**Comment by PreciousU** [comment]
If there are no suggestions to be made, should the appearance button be removed?

If the appearance button should remain, should users be denied access to edit default settings?

Or does the task entail making adjustments to the containers?

Please I need assistance. I'm not certain I understand the task.

**Comment by codesuperstarr** [comment]
I am an outreachy applicant, can I be assigned this issue?

**Comment by eliserichards** [comment]
@PreciousU, I have made some edits to the description of this bug so that it is more clear. The size of the clickable area of the button (the orange rectangle in the screenshot) is smaller than the button itself. The purpose of this card is to make the clickable area bigger (to match the button) so that it is easier to click.

@codesuperstarr, I have just made a few new issues similar to this that you can pick up. Try this one: https://github.com/mozilla-mobile/fenix/issues/18709

**Comment by eliserichards** [comment]
See https://github.com/mozilla-mobile/android-components/blob/1d1753abba4d29ad3e91c16d0c751db7cdbd639d/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt#L78 in the [Android Components](https://github.com/mozilla-mobile/android-components) repo

**Comment by PreciousU** [comment]
Thank you, Elise. I needed this. I discovered the issue wasn't as easy as I
thought. I hope I get to complete this contribution quickly and move on to
do lots more.
