### ISSUE TITLE
Remove unused taskcluster flavors

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#16382]
In our [Taskcluster index](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix) we have many unused flavors.

<img width="212" alt="Screen Shot 2020-11-04 at 6 49 56 PM" src="https://user-images.githubusercontent.com/1082253/98191678-919cca00-1ece-11eb-8c06-aec4f79bd72a.png">

Would be helpful to clean up the unused ones, and trim to:
- beta
- release
- nightly
- debug

I think the following are also used?
- cache
- branch
- nightly-simulation

**Comment by liuche** [comment]
cc @pocmo @JohanLorenzo is this easy to do? I am forever clicking on the wrong "production" vs "release" link 😅

**Comment by pocmo** [comment]
@MihaiTabara What do you think?

I am not sure how to deal with that: If we remove the outdated index then we also lose access to those APKs?

**Comment by JohanLorenzo** [comment]
> I am not sure how to deal with that: If we remove the outdated index then we also lose access to those APKs?

Yeah. Any tool that depend on old indexes will instantaneously break. The best thing to do is to wait. Indexes expire after 1 year. The last `production` was made 4 months ago. This flavor will automatically disappear in 8 months.

To me, this is the best and safest thing to do.

**Comment by pocmo** [comment]
Okay, that sounds reasonable. :)
