### ISSUE TITLE
[l10n] Sign-off on v83 locales, new locales needed

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#16381]
New locales for release: `sat`, `gl`
The rest of our list remains the same
CC @liuche

**Comment by liuche** [comment]
assigning to @st3fan for 83 Beta work.

Also see release checklist: contains instructions (wip) for this https://github.com/mozilla-mobile/fenix/pull/16383

**Comment by liuche** [comment]
Due to transitions, @st3fan will take care of this some time next week. It may slightly behind schedule, but we aim to get it done soon! Sorry for the inconvenience @Delphine !

**Comment by st3fan** [comment]
@Delphine Is this still good to go? I am planning to pick this up today or tomorrow.

**Comment by Delphine** [comment]
Yes, it is!

**Comment by st3fan** [comment]
We landed the strings and enabled `sat` and `gl.

https://github.com/mozilla-mobile/fenix/pull/16504
https://github.com/mozilla-mobile/fenix/pull/16490
https://github.com/mozilla-mobile/fenix/pull/16491
