### ISSUE TITLE
[Bug] Delay to list already open sites in search results

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#16390]
## Steps to reproduce
1. open cnn.com
2. go to tab tray, open a new tab and enter cnn.com again

### Expected behavior
I get the option to switch to the already open cnn.com tab

### Actual behavior
I need to open another URL first and when I open cnn.com again, I see the "Switch to tab" option in my results.

### Device information

* Android device: ?
* Fenix version: ?

**Comment by mawen7** [comment]
I put up #17127 for this

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 2/3 with Google Pixel 4 XL (11).
Please note that I added this bug The switch to tab option is not visible in search suggestions only if scrolling #17788.
