### ISSUE TITLE
[Bug] Adjust divider visibility above the General section from Settings page

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#16393]
### Preconditions
Do not have an account connected.
## Steps to reproduce
1. Launch Fenix and go to Settings;
2. Observe the ruler above the General section;
### Expected behavior
The ruler above the General section is visible.
### Actual behavior
The ruler above the General section is not visible. See https://github.com/mozilla-mobile/fenix/issues/14636

![rsz_screenshot_20201103-114414](https://user-images.githubusercontent.com/48799384/98230022-539db580-1f63-11eb-881f-3601539fb36b.png)

### Notes
This is not reproducible when an account is connected.

### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8), Motorola Moto G6 (Android 8), Pixel 2 (Android 9);
* Fenix version: Nightly 201105 (Build #2015773801) GV 84 from 11/5;

**Comment by brampitoyo** [comment]
@ebalazs-sv Apologies for the overdue reply!

We should hide the ruler underneath the “Turn on Sync” card.

<img width="360" alt="Settings Not Synced@2x" src="https://user-images.githubusercontent.com/51007/98486347-aa67ff80-2281-11eb-89fa-f23ea69c9f07.png">

When people are signed in, this card turns into a section called “Account”. Like any other section, it should be separated with a ruler underneath.

<img width="360" alt="Settings Synced@2x" src="https://user-images.githubusercontent.com/51007/98486339-9de3a700-2281-11eb-85ca-c50765a6504f.png">

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with Samsung Note10(Android 10).
