### ISSUE TITLE
[Bug][a11y] Consider increasing the text contrast ratio on "Recently closed tabs" from History

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16396]
## Steps to reproduce 
1. Have the Accessibility scanner app installed and opened.
2. In Firefox, go to the History page, and scan it.

### Expected behavior
No suggestions are made.

### Actual behavior
Suggestions are made for the "Recently closed tabs".
* Text contrast
org.mozilla.fenix:id/recently_closed_tabs_header
The item's text contrast ratio is 2.53. This ratio is based on an estimated foreground color of #A29CAE and an estimated background color of #F9F9FB. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text. This item may be only partially visible within a scrollable container.

<img src="https://user-images.githubusercontent.com/40694158/98246675-4b517480-1f7b-11eb-9edb-71dca2069d04.png" width="300" height="550" />

* Text contrast
org.mozilla.fenix:id/recently_closed_tabs_description
The item's text contrast ratio is 1.67. This ratio is based on an estimated foreground color of #C3C3C5 and an estimated background color of #F9F9FB. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text. This item may be only partially visible within a scrollable container.

<img src="https://user-images.githubusercontent.com/40694158/98246716-55737300-1f7b-11eb-97a1-1cfe29e1b0f4.png" width="300" height="550" />

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 11/4 Nightly

**Comment by topotropic** [comment]
Should use the same color values as the history entries below.  Thanks!

**Comment by shahsurajk** [comment]
Can work on this, are we going ahead with the color palette of the history entries?

**Comment by fevziomurtekin** [comment]
Sorry to send two commits. You'll see [PR](https://github.com/mozilla-mobile/fenix/pull/17603).

**Comment by softvision-miralobontiu** [comment]
Hi all!
This is still reproducible on Beta 87.0.0-beta.2 with OnePlus 5T (Android 10). 
These suggestions are made only when at least one of the history entry is selected.
* light theme:
![light](https://user-images.githubusercontent.com/40694158/109782934-1ba53700-7c12-11eb-9005-3511cd9c840c.png)

* dark theme:
![dark](https://user-images.githubusercontent.com/40694158/109783074-455e5e00-7c12-11eb-842f-f241c8f2be7c.png)
