### ISSUE TITLE
[Bug] Select dropdowns on addons.mozilla.org are opening only with double tap

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla-mobile/fenix#16399]
### Describe the problem and steps to reproduce it:
1. Open https://addons.mozilla.org
2. Scroll down to the footer section
3. Tap on the language picker select box

### What happened?
The select options are not opened at the first tap. You'll have to double tap to see the options. 

### What did you expect to happen?
The select options are displayed after the first tap

### Anything else we should know?
This happens with every select field present on the site, like search filters for example - https://addons.mozilla.org/en-US/android/search/

### Device information
* Android device: Xiaomi Mi 9T Pro, Pixel 3a
* Fenix version: 82.1.1 (although I've been noticing the issue since 80.1.2)
* I did not reproduce with the same devices and Android version on other mobile browsers
* I did not reproduce with the same Fenix version on Android 9

![1599745298615](https://user-images.githubusercontent.com/31961530/92754082-34cfd800-f393-11ea-89d9-d655cb4c7c0a.gif)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-8659)

**Comment by kbrosnan** [comment]
Does this happen on [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

**Comment by s-ankur** [comment]
Yes, on latest nightly, you need two taps

**Comment by ioanarusiczki** [comment]
In my case, on Fenix or Nightly, I have a Pixel - first generation, with Android 10.0 - the search filters https://addons.mozilla.org/en-US/android/search/ are not responsive to a double tab, it's almost impossible to open the sort by filter. Same for Change Language.

**Comment by Amejia481** [comment]
This issue is also reproducible in GeckoView Sample app, I opened a bug for the gv team to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1681522

**Comment by sflorean** [comment]
This issue is still reproducible on Fenix versions.

**Comment by armanm** [comment]
Has there been any updates or fixes for this issue? The bug is still present on the latest version of FF (currently 94.1.2). This is a bad problem to have with one of HTML's oldest and commonly used elements 😕

**Comment by makotokato** [comment]
Does anyone still reproduce this? I cannot.
