### ISSUE TITLE
[Bug] The Disconnect button from Sign out is invisible

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#16398]
### Precondition
Log in with an account.
## Steps to reproduce
1. Launch Fenix and go to three-dot menu -> Settings;
2. Tap the email address from the Account section;
3. Tap "Sign out";
4. Observe the "Disconnect" button;
### Expected behavior
In Light theme, the "Disconnect" button is 
![rsz_screenshot_20201105-155407_firefox_beta](https://user-images.githubusercontent.com/48799384/98250336-f9f7b400-1f7f-11eb-9fb3-1351b6978733.jpg)
In Dark theme, the "Disconnect" button is 
![rsz_screenshot_20201105-155351_firefox_beta](https://user-images.githubusercontent.com/48799384/98250372-054adf80-1f80-11eb-8097-ef13b37b0dd0.jpg)

### Actual behavior
In Light theme, the "Disconnect" button is 
![rsz_screenshot_20201105-160116_firefox_nightly](https://user-images.githubusercontent.com/48799384/98250810-9ae66f00-1f80-11eb-94ab-56025f05ba4a.jpg)
In Dark theme, the "Disconnect" button is 
![rsz_screenshot_20201105-160132_firefox_nightly](https://user-images.githubusercontent.com/48799384/98250819-9cb03280-1f80-11eb-825f-d7625471782b.jpg)

### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8), Google Pixel (Android 10)
* Fenix version: Nightly 201105 05:01 (Build #2015773801) GV 84 from 11/5

**Comment by ebalazs-sv** [comment]
his is also reproducible on Beta 84.0.0-beta.1 from 11/18 with Samsung Galaxy Tab S3 (Android 8).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly 201208`** and **`84.0.0-beta.4`** using the following devices:
• Google Pixel 4 XL (Android 11)
• Samsung Galaxy Tab S6 (Android 10)
• Motorola Moto G6 (Android 8)
• OnePlus A3 (Android 6.0.1)
