### ISSUE TITLE
Build all variants (nightly/beta/release) for pull requests and master pushes

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#16406]
Currently we only build the `debug` variant for pull requests and pushes to `master`. In most cases this is okay-ish since most of the code is shared. But there are some differences and if there's a failure that only affects non-debug builds then we do not notice them.

Here is an example that just happened:
https://github.com/mozilla-mobile/fenix/commit/686f7bd7c65cbaa8fa8c7dd0b390cd6adf11e079

For this change the pull request was green. Once landed on master the push was green too. But the beta and release variant of the app did not compile anymore.

Currently we only notice such failures if an engineer builds such a variant or if we actually release it - which is of course super annoying.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8663)

**Comment by jonalmeida** [comment]
We should be able to do this with some easy now; we build all variants in Focus now (releng++).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813265

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
