### ISSUE TITLE
[UX] investigate tab sorting

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#16408]
Related to #16130 

Additional investigation is needed for tab sorting in the tabs tray.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8665)

**Comment by koshkas1** [comment]
New update just made this worse

**Comment by jhpratt** [comment]
Keeping open.

**Comment by boek** [comment]
Dup of
