### ISSUE TITLE
archive.org not loading batched content

### ISSUE THREAD

**Issue by Jvanwall** [mozilla-mobile/fenix#16401]
## Site with issue and any steps to reproduce
Archive.org
When scrolling through search results when the end of a page the site will refresh list.  This is not happening. No additional entries are presented.  Archive.org still works with Samsung internet browser.
### Expected behavior
When the end of current list of search results a momentry busy symbol appears followed by more search results.
### Actual behavior
List of search results ends, no additional activity

### Can you reproduce in Chrome (or other non-Mozilla browser)?
 Samsung internet browser works ok

### Device information

* Android device: samsung galaxy tab a android p
* Fenix version: 82.1.1

**Comment by liuche** [comment]
How does GV handle batched loading? Is this something that we're not doing correctly, or is there something in Fenix that is necessary?

**Comment by kbrosnan** [comment]
This looks to work on Geckoview Example. Same behavior on Reference Browser. So maybe something for AC to handle.

**Comment by jonalmeida** [comment]
From AC triage: We should re-test this with and without Tracking Protection along with the latest GV.

I'm also going to take a look into it to see if there is any useful info there.

**Comment by jonalmeida** [comment]
I can reproduce this in Reference Browser as well, but not in Sample Browser.

**Comment by jonalmeida** [comment]
I found the difference. R-B and Fenix both use `GeckoView.setDynamicToolbarMaxHeight` for the bottom toolbar. Adding that to Sample Browser immediately made the bug reproducible, so I'm guessing GVE doesn't have this usage there to have made it reproducible.

Moving this issue to https://bugzilla.mozilla.org/show_bug.cgi?id=1682664.
