### ISSUE TITLE
Ability to increase the number of top sites/page

### ISSUE THREAD

**Issue by mackeev** [mozilla-mobile/fenix#16414]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Current limit (8) is very low. (The total limit (16) is very, very low as well, BTW.) One's screen has plenty of room to hold more. 
### How do you know that this problem exists today? Why is this important?
I, for one, have more than 8 top sites and prefer not to sweep to get to the next 8. And it looks much better esthetically.
### Who will benefit from it?
All users who have more than 8 top sites marked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8669)

**Comment by cadeyrn** [comment]
There is already a discussion in #8312.

**Comment by ale82to** [comment]
people are asking for this for ages they simply don't care

**Comment by mirko77** [comment]
16 sites. 

We can save up to 16 sites in 2021 on phones with 128GB of memory and 6GB of ram.

Firefox is stuck in the 80s

**Comment by ANi1XO** [comment]
Please add more rows, there is plenty of space on the homepage and more shortcuts at homepage improve both aesthetics and usability.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814114

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
