### ISSUE TITLE
[Bug] Site didn't redirect to home from store after using sharing and clicking back

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16412]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open Posta.com.tr
2. On homepage,Click on heart icon 
3. Click on spotify icon
4.After redirecting to play store,Now click back button on the phone
### Expected behavior
Clicking back,the site should get redirected to the homepage of posta.com.tr
### Actual behavior
Clicking back,the site did not redirected to the homepage of posta.com.tr instead shows a blank page
### Device information
Samsung Galaxy J7 Prime - Android 8.1
 Huawei Y6 Prime (2019) - Android 9.0
* Android device: yes
* Fenix version:  Firefox Beta 82.0.0

**Comment by ekager** [comment]
@BigSamSampson can you still reproduce this? I have the Spotify app and with the setting Open in App on, it opens Spotify and clicking back will show the homepage.
