### ISSUE TITLE
[Bug] When trying to login with Facebook, unreadable message appears on the page

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16413]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the firefox beta
2. Open turna.com
3. Click on Menu button in upper right corner
4. Click on smile on upper right corner
5. Click on Facebook button
### Expected behavior
Facebook page should open without any unreadable messages.
### Actual behavior
When trying to login with Facebook, unreadable message appears on the page
### Device information
 Xiaomi Redmi Note 9S - Android 10,0
 Huawei Y6 Prime (2019) - Android 9.0 (Pie)
* Android device: yes
* Fenix version: Firefox Beta 82.0.0

**Comment by ekager** [comment]
Can you still reproduce this? I got a dialog asking if I wanted to navigate to Facebook in a new window, but then the Facebook login screen appears correctly AFAICT
