### ISSUE TITLE
[Bug] N11.com- new member registration page doesnt load correctly

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16421]
## Steps to reproduce
1. Start firefox beta browser
2. Go to page n11.com
3. Tap hamburger menu 
4. Tap ' Giriş yap'
5. New page tap ' Ucretsiz Uye ol'
### Expected behavior
When i tap the link i expect it loads page and shows me information without problem
### Actual behavior
I tap it and information doesnt load correct
### Device information
Xiaomi Mi 6 - Android 9.0 (Pie)
Vestel Venüs v3 (Android 6.0.1)
* Android device: yes
* Fenix version: Firefox beta 82.0.0

**Comment by ekager** [comment]
@BigSamSampson if you are still seeing this could you give more details about what exactly the problem with the site is?
