### ISSUE TITLE
[Bug] Report site issue flashes when opening 3 dot menu in dark mode

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16429]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
set dark mode
go ta a webpage and click on 3 dot menu
### Expected behavior
the report site issue button flashes for a sec
### Actual behavior
it does not
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by Tomatoide** [comment]
it flashes then shows wrong color
![Screenshot_2020-11-11-14-01-28_1](https://user-images.githubusercontent.com/6270814/98809632-8396fe00-2426-11eb-99ff-5d04a38277c1.jpg)

**Comment by Tomatoide** [comment]
also the long press back menu is broken in dark mode
![Screenshot_2020-11-11-14-03-39_1](https://user-images.githubusercontent.com/6270814/98809861-eee0d000-2426-11eb-95c3-9f28d3e55ba7.jpg)

**Comment by LaurentiuApahideanSV** [comment]
Hello and thank you for the report.
Both of the issues have been reported here: https://github.com/mozilla-mobile/fenix/issues/11367 and here: https://github.com/mozilla-mobile/fenix/issues/16422. I will close this issue as they will be handled there.
