### ISSUE TITLE
FNX3-15707 ⁃ [Bug] regression: low contrast for session text background on home screen

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1643]
### Steps to reproduce
1. start Fenix and make sure you don't have any saved sessions.

### Expected behavior
There is a text explaining what sessions are. There should be either sufficient contrast between the background color of the text box and the background color of the app or no color difference at all.

### Actual behavior
The text box has a different background color than the background of the app but it's almost the same color so you have to look very closely to be able to see a difference at all.

That's a regression, probably of #1609.

![Screenshot](https://user-images.githubusercontent.com/1100614/56158607-c5e62800-5fc2-11e9-915c-ed8acacdc67b.png)UNITO-UNDERSCORE!20190415-210043!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 658f6dcf23a086090da9cd24d5a28d900bfb2bfc

**Comment by sblatz** [comment]
This is expected behavior currently. The text box is colored with an "above" color, with the background being the "foundation" color. I will have @shorlander weigh in on this though.

**Comment by vesta0** [comment]
This will be addressed.
