### ISSUE TITLE
[Bug] sondakika.com - the Photo does not increase and remains in the same size

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16438]
## Steps to reproduce
1. Open firefox
2. Go to the site "sondakika.com"
3. Switch the device to landscape mode
### Expected behavior
As a result, the photo should increase
### Actual behavior
In fact, the photo does not increase and remains in the same size. I attached a screenshot as it should be in reality.
### Device information
Huawei Y6 Pro - Android 5.1
Vestel Venüs V3-Android 6.0.1
* Android device: yes
* Fenix version: firefox beta 82.0.0
 
![image](https://user-images.githubusercontent.com/66958331/98404974-88516000-207c-11eb-87a6-96d697a2bc48.png)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible Firefox Preview Nighlty 201111 (Build #2015775051)
### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)

**Comment by sflorean** [comment]
This is also reproducible on Chrome, but the difference is not so visible.
