### ISSUE TITLE
[Bug] Facebook.com - Share button and share button menu are cut off at 200% font size

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16433]
## Steps to reproduce
Must have a Facebook account
1. Open the firefox beta
2. Tap Settings - Accessibility
3. Select 200% font size
4. Back to home page
5. Go to facebook.com and login in to your account 
6. Tap share button under any post
### Expected behavior
Share button and share button menu captions will be visible, nothing will be cut
### Actual behavior
The share button is clipped, and the captions in the share button menu are clipped
### Device information
Xiaomi Redmi Note 4X - Android 7.0
Vestel Venüs V3 - Android 6.0.1
* Android device: yes
* Fenix version: firefox beta 82.0.0

**Comment by kbrosnan** [comment]
There is only so much that can be done to fit fonts or images into a given area. This would be up to FB to work on a different design.
