### ISSUE TITLE
Tagalog still missing on Nightly

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#16432]
This had initially been filed under #15763
Context: I thought Tagalog was missing because they had only completed a few A-C strings, and no Fenix ones. However, I see they have now started work on Fenix strings - but I still don't see Tagalog show up in our Nightly builds language list.

I do see the locale `tl` has been added to the l10n.toml locales lists - both in the mozilla-l10n repo and back into the Fenix + A-C ones. Not sure where this comes from.

**Comment by sflorean** [comment]
@Delphine Tagalog is not displayed in Fenix Nightly 12/16 under settings->languages, and on Pontoon the language is at 42% progress.

**Comment by Delphine** [comment]
Strange, I checked a week ago and was seeing it. 
I just updated Nightly, and I see it under the Language list. 
I'm wondering what could be happening? 🤔
![2020-12-16 08 41 38](https://user-images.githubusercontent.com/399020/102378382-97300a00-3f7a-11eb-9f51-797421edf473.jpg)

**Comment by sflorean** [comment]
Indeed, seems that is displayed on the affected devices. Closing this.
