### ISSUE TITLE
[Bug] detectportal.firefox.com downloads a file!

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16434]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open detectportal.firefox.com
### Expected behavior
It says success because I don't have a captive portal
This is what used to happen earlier
### Actual behavior
It downloads a file called download file.bin
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by evilpie** [comment]
I suspect something changed with the site. The response header `Content-Type` has the value `application/octet-stream`, which means trying to download it a file makes sense. The same happens on Firefox and Chrome on Desktop.

**Comment by s-ankur** [comment]
Could this be checked with whoever maintain the Firefox website?

**Comment by s-ankur** [comment]
Closing as expected behavior now
