### ISSUE TITLE
[Bug] Unnecessary space in site permission exceptions

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16437]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Scroll up while in site permission exceptions
### Expected behavior
There is no unnecessary space
### Actual behavior
![Screenshot_2020-11-07-00-28-16-204_org mozilla fenix](https://user-images.githubusercontent.com/33252312/98404341-63ff7e80-2090-11eb-9419-b598ed1c6f42.jpg)
There is a space and you can easily see due to the purple shade on overscroll
### Device information

* Android device: Remi Note 5 pro
* Fenix version: Nightly

**Comment by Dojo456** [comment]
Fixing this now

**Comment by s-ankur** [comment]
Thanks @Dojo456

**Comment by SnexusG** [comment]
is this still relevant?

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nigthly 2021-10-06 and 94.0.0-beta.1.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- Oppo Find X3 (Android 11)
