### ISSUE TITLE
Hijacked session, lost tabs

### ISSUE THREAD

**Issue by drtomeq** [mozilla-mobile/fenix#16448]
Hi,

I have a problem for the desktop version of Firefox that has happened on several occasions now.  A piece of software hijacked my session and replaced it with Bing.  I am not aware to have consented to this.  The problem is that I usually save my session from last time and there were many important tabs I had opened.  I was using the same session over a long period and some of the pages I had actually visited months ago so it would be next to impossible or extremely long to recover them from history.  On some occasions I go to recently closed tabs but this time it was greyed out.

I appreciate that there is a folder with the last tabs in session restore, but that had already replaced the files when I opened Firefox again.

Please do one of the following.
1) Have backups of sessions that go back for a few sessions and over several dates so if one is gone there is another recent one.
2) Include tabs in a session in recent history so they are easy to find.

The work I have opened was valuable. This has not only put me back, but some of it is irreplaceable and I may potentially lose clients or even get into trouble with the law.  Please fix this so it does not happen again. 

Thanks

**Comment by clientenq** [comment]
If this issue can also occur on firefox for android, what do you expect as solution?

Since sessions are not primary managed by clients but webservices, the session tools of firefox can not be considered as a single solution to keep sessions. Like you can probably not expect to forever be in the club house when being a member.

**Comment by drtomeq** [comment]
Hi,Thanks for getting back.As I suggested if it could save a few recent sessions that would be great. Also it would be great if those that were in tabs but not recently visited could be placed higher un the history list.I'm sorry if this is the wrong place. I did an internet search for Firefox suggestions and this came up but it seems to be specifically for mobile.  Perhaps a redirect would be helpful if it's the wrong place.Thanks,TomOn 8 Nov 2020 15:04, clientenq <notifications@github.com> wrote:
If this issue can also occur on firefox for android, what do you expect as solution?
Since sessions are not primary managed by clients but webservices, the session tools of firefox can not be considered as a single solution to keep sessions. Like you can probably not expect to forever be in the club house when being a member.

**Comment by kbrosnan** [comment]
This is a development tool for Firefox for Android. 

The following post may help you get back your data, https://www.reddit.com/r/firefox/comments/56sevb/how_to_restore_a_browsing_session_from_backup/. If you need additional help for desktop Firefox please ask at https://support.mozilla.org/en-US/questions/new/desktop
