### ISSUE TITLE
Update GV Google Noto emoji font version

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#16444]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
the google noto emoji font is out of date. 

### How do you know that this problem exists today? Why is this important?
i recently saw the zany face 🤪 and it has drastically changed. 
![image](https://user-images.githubusercontent.com/51363864/98437718-a7152c80-2138-11eb-9b19-84aaa6313de9.png)
https://emojipedia.org/zany-face/

### Who will benefit from it?
users who view and input emoji

note: idk if Fenix, GV or AC use Jetpack's EmojiCompat library. i also don't know how emojicompat works lol
https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat is pretty complicated 😅

**Comment by makotokato** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1391715

**Comment by Poopooracoocoo** [comment]
@makotokato Are you sure? I think GV already uses EmojiCompat. I just know that GV uses an older version Noto emoji.

**Comment by makotokato** [comment]
> @makotokato Are you sure? I think GV already uses EmojiCompat. I just know that GV uses an older version Noto emoji.

What do you mean?  GV uses "Noto Sans Emoji" font on device (/system/fonts on old Android) for emoji glyph.

**Comment by Poopooracoocoo** [comment]
ohhhh! I had no idea. I have a Samsung device and just assumed that GV provided its own font for emoji. I didn't know that Samsung's skin on Android still kept Google's emoji font and that apps could use it. 

so yeah, in that case, this would be about using EmojiCompat. Just went and voted for that bug.

**Comment by Poopooracoocoo** [comment]
@makotokato wait a minute


Alexandre Folle de Menezes said on that issue:
![image](https://user-images.githubusercontent.com/51363864/99369654-cec27c80-2910-11eb-9f8e-a78b68868c0f.png)

**Comment by DragoCubed** [comment]
@makotokato Is what @Poopooracoocoo correct?

**Comment by makotokato** [comment]
GeckoView doesn't bundle emoji font. It uses "`Noto Color Emoji`" in /system/fonts or Font match API that is Android 10+. If newer Android, vendor (Google or OEM) can update system font by [packages](https://source.android.com/devices/architecture/custom-font-fallback), not OS update.
