### ISSUE TITLE
[Bug] Unable to download anything from:  "https://www.robser.es"

### ISSUE THREAD

**Issue by osoyoguiconbubu** [mozilla-mobile/fenix#16445]
It is impossible to download anything from:  "https://www.robser.es"

### Expected behavior
In the "old version" (68.11.0), there is no problem downloading from this page

### Actual behavior
In the last version (82.1.1), nothing can be downloaded from "https://www.robser.es"

### Device information
Motorola One Vision

* Android device: Android 10 (android one)
* Fenix version: Firefox (Android) 82.1.1

**Comment by kbrosnan** [comment]
Please try this on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). There are a number of download related fixes in it.

**Comment by x2k13** [comment]
Can confirm, for me downloads are completely broken now. Notification appears, nothing downloads, then fails.Nightly works, Beta fails as well.

**Comment by kbrosnan** [comment]
Closing as works for me on development builds. The fix should be in the 84 release then.
