### ISSUE TITLE
[Bug] dom.w3c_pointer_events.enabled toggle in about:config

### ISSUE THREAD

**Issue by patrickhlauke** [mozilla-mobile/fenix#16455]
## Steps to reproduce

Pointer events are now enabled by default in Firefox/Android. Going to about:config, the `dom.w3c_pointer_events.enabled` option by default on a fresh install shows `true`, but with a "Reset" option ... this usually only happens when a config option has been manually changed by the user.

Hitting reset changes the option to `false`, and the "Reset" button disappears (suggesting the browser "thinks" this is the default).

On fully closing and restarting Firefox the option is changed back to `true` and shows "Reset" again. Similarly, toggling the option (rather than resetting) also changes the option, but it's also changed back forcibly on restart.

### Expected behavior

By default, the option should show that it's `true`, and have no "Reset" button next to it. i.e. it should "know" that `true` is the actual default.

When a user changes the option, the setting should "stick" even after they close and reopen the browser.

### Actual behavior

even when `true`, the option shows a "Reset".

Changing the option and restarting the browser resets it back to `true` regardless of what the user changed the setting to in about:config

### Device information

* Android device: 10
* Fenix version:  Nightly 201108 17:01 (Build #2015774475)

**Comment by patrickhlauke** [comment]
After a fresh install, when first going to about:config - shows `true` and "Reset"

> ![Screenshot_20201109-115146](https://user-images.githubusercontent.com/895831/98540394-c66da000-2285-11eb-979e-c34ee4cbc1e3.png)

After resetting, it shows as `false`

> ![Screenshot_20201109-115155](https://user-images.githubusercontent.com/895831/98540441-dab19d00-2285-11eb-8c9a-1c935aaeeb1d.png)

About/version

> ![Screenshot_20201109-115254](https://user-images.githubusercontent.com/895831/98540464-e56c3200-2285-11eb-957e-c6664d3978f7.png)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1676197

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
