### ISSUE TITLE
Bookmarks password protection/lock

### ISSUE THREAD

**Issue by Atifus01** [mozilla-mobile/fenix#16454]
I would like to have an option to password protect/lock certain bookmark folder/folders.
And if possible also to not show locked bookmarks in suggested.

I want this feature as some of my bookmarks are nsfw.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8703)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812708

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
