### ISSUE TITLE
[Bug] verifyRunBlockingAndStrictModeSuppresionCount test failure

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#16458]
Failed once on 11/9, passed on the second try: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6245980406465311321/executions/bs.6d95e8819e141f4c/testcases/1/test-cases
Commit: https://github.com/mozilla-mobile/fenix/runs/1366265579

**Comment by isabelrios** [comment]
Failed once on 11/13: 
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9054115299569816994/executions/bs.9dffe78976fdb8e2/test-cases
