### ISSUE TITLE
[Bug] Genius lyrics search lags on Fenix (genius.com)

### ISSUE THREAD

**Issue by jcosentino** [mozilla-mobile/fenix#16450]
## Steps to reproduce
1. Go to: [genius.com](https://genius.com/)
2. Click on the search bar and type a song title
3. The result lag and sometimes they freeze and reload after each keypress. This is not present in Google Chrome for Android.

### Expected behavior
The results should smoothly populate _while_ you're typing.

### Actual behavior
The search results lag and freeze after keypresses

* Android device: Google Pixel Android 11
* Fenix version: 82.1.1 (Build #2015770923)
 
See this screencast:
https://imgur.com/fxvglLX

**Comment by AndiAJ** [comment]
Reproducible on the latest on the latest **`Nightly Build 201111`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
