### ISSUE TITLE
[Bug] canliradyodinle.fm- The live video time line appears different for each selected fm

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16453]
## Steps to reproduce
1. Open link "canliradyodinle.fm"
2. Tap "Alem FM"
3. Tap to play
4. Tap hamburger menu
5. Tap "SLOW"
6. Tap "Slow Türk Fm"
7. Tap for going back
8. Tap "Joy Türk Fm"
### Expected behavior
The live video time line appears same for each selected fm
### Actual behavior
The live video time line appears different for each selected fm
### Device information
Samsung Galaxy J6 - Android 10
Vestel Venüs V3 - Android 6.0.1
* Android device: yes
* Fenix version: 82.0.0
 
![image](https://user-images.githubusercontent.com/66958331/98507969-ae8b2180-226f-11eb-8250-a84c6cf27800.png)
![image](https://user-images.githubusercontent.com/66958331/98507999-bba81080-226f-11eb-8ab2-fab8f72adfd5.png)
![image](https://user-images.githubusercontent.com/66958331/98508020-c82c6900-226f-11eb-8a06-a64f2e6ba6c4.png)

**Comment by AndiAJ** [comment]
Hi, **reproducible** on the latest **`Nightly Build 201117`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
