### ISSUE TITLE
Some source strings seem incorrect or inconsistent

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#16464]
A few localizers have flagged me recent strings as they seem incorrect/inconsistent to them:
* "[Delete downloads](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/strings.xml#L678)": comment says it's "clear", while "delete" suggests we are removing them entirely from the phone. Is this correct? "Delete" seems misleading here.
* Same thing for "[Downloads Deleted](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/strings.xml#L682)"
* Confusingly, there's also a "[Are you sure you want to clear your downloads?](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/strings.xml#L680)" string

Seems like either some comments, or strings, need to be updated here.
CC @betsymi for help :)

**Comment by betsymi** [comment]
Thanks for flagging. As is sometimes the case with strings inconsistencies, it appears that this might be surfacing some other issues we weren't aware of. Am continuing to investigate with @apbitner and will circle back once we have a better understanding of what's going on.

**Comment by betsymi** [comment]
Resolution for this is in #16541
