### ISSUE TITLE
Can't download apk files from apkmirror

### ISSUE THREAD

**Issue by Walkinstownlad** [mozilla-mobile/fenix#16463]
I'm using the latest stable Firefox version on Android(82.1.3) & I can no longer properly download apk files from apkmirror.com. It happens with any apk on the site. I'll choose the version, etc & when I tap download, it just hangs in download status. No "your download is complete" & when I pull down the notification shade it shows the download progress bar notification, but no file name or progress is actually displayed. 

I have not tested this on other websites.,just apkmirror. The only installed add-ons I have are dark reader & ublock origin. Looking forward to this getting fixed, as sometimes google play store is just too slow!

**Comment by trxraptor** [comment]
The download function in on the stable release seems to be buggy right now. (I can't download .ppt and .pdf files from multiple sites) However downloading on the Beta version works. Just use another browser or Firefox Beta until it is fixed.
Related Reddit post: https://www.reddit.com/r/firefox/comments/jqhxnd/downloads_dont_really_start_i_guess_notification/

**Comment by Walkinstownlad** [comment]
Cheers for the info!
