### ISSUE TITLE
Dark mode consistency - UI, initial loading content page color, reader view

### ISSUE THREAD

**Issue by crisalis2** [mozilla-mobile/fenix#16467]
### What is the user problem or growth opportunity you want to see solved?
When you use Firefox in dark mode you will have a dark UI which is a specific shade of gray and a loading content page color that is another different shade of gray (this was implemented very recently, see #6313). The shades don't match. If they matched, which is the change I suggest here, Firefox would look more consistent and clean. 

Additionally, there's the reader view. You can manually set it to a dark background (by the way, I think the dark background should be automatically selected if the user is using dark mode in Firefox/Android). This dark background is yet another shade of gray different from UI's gray and loading content page's gray. I suggest this color too is unified with those of the UI and the loading page.

### How do you know that this problem exists today? Why is this important?
Okay, this is not THAT important, but I see no reason why those three shades of gray should be different from each other. Most likely, they were implemented by different people in different moments, but if they were implemented at the same time in a more "unified" way I'm pretty sure they would have been the same color.
Also, I don't think this is too difficult to fix.

### Who will benefit from it?
Dark mode users.

--

Additional pictures ilustrating the issue.

UI's gray.
![Screenshot_20201109-232000_Firefox Nightly](https://user-images.githubusercontent.com/65630147/98603408-47f31b80-22e2-11eb-9b5a-81cf49668db4.png)

Initial loading content page color (dark mode).
![Screenshot_20201109-231715_Firefox Nightly](https://user-images.githubusercontent.com/65630147/98603411-488bb200-22e2-11eb-9d5c-79bb8f139611.png)

Reader view's dark background.
![Screenshot_20201109-231906_Firefox Nightly](https://user-images.githubusercontent.com/65630147/98603412-49244880-22e2-11eb-92a1-f433760ada4b.png)

Edit:
There's also this other shade of gray from the tab switcher:
![Screenshot_20201110-172419_Firefox Nightly](https://user-images.githubusercontent.com/65630147/98701824-fc8c4c00-2379-11eb-8ec5-16c5712cbc4f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8711)

**Comment by DiegoARL38** [comment]
In regards to the Reader view following the app's theme, there's #3289

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807088

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
