### ISSUE TITLE
Tabs don't close when you slide off the app

### ISSUE THREAD

**Issue by GuillermoAnkh** [mozilla-mobile/fenix#16479]
A long time ago, in a far far away galaxy there is a way to choose Firefox close all tabs when you kill it from Smartphone.
But now you must go to the menu and said "Quit" to quit propely the app and see your tabs close.

There is a way to have the tabs closed like before ?

Thanks for your help.

**Comment by s-ankur** [comment]
Related request #3950

**Comment by ekager** [comment]
closing for #5865
