### ISSUE TITLE
[Bug] Media auto play not blocked as expected

### ISSUE THREAD

**Issue by sophiekuehn** [mozilla-mobile/fenix#16476]
### Steps to reproduce
Set up firefox to block media auto play.

### Expected behavior
No more audio or video starting automatically when opening a website. 

### Actual behavior
Media starts automatically anyway. 

Example german news page: https://www.chip.de/news/Windows-10-20H2-Grosser-SSD-Bug-ist-aufgetaucht_183061995.html?layout=amp

### Device information

* Android device: Oreo 8
* Fenix version: 82.1.1

**Comment by emdete** [comment]
I can confirm this behaviour.

I considere this a severe security issue.

Web-pages have access to blocked features, services or devices of the mobile - this should never ever happen. What else slips through unnoticed?

**Comment by Amejia481** [comment]
We put a patch for it see https://github.com/mozilla-mobile/fenix/issues/8987, are you able to [reproduce in nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

**Comment by sophiekuehn** [comment]
> 
> 
> We put a patch for it see #8987, are you able to [reproduce in nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

It seams to be fixed in nightly atm.

**Comment by Amejia481** [comment]
I will proceed to close the issue, please feel free to re open if needed

**Comment by sophiekuehn** [comment]
This issue is back again.  Example: https://www.ingame.de/news/cyberpunk-2077-cd-projekt-red-setting-night-city-open-karte-world-release-drama-meinung-hamburg-90151857.amp.html

**Comment by Amejia481** [comment]
> https://www.ingame.de/news/cyberpunk-2077-cd-projekt-red-setting-night-city-open-karte-world-release-drama-meinung-hamburg-90151857.amp.html

@sophiekuehn thanks for the report. Are you able to reproduce on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)? I tested on it, and I wasn't able to reproduce, please let us know if the issue persist.

**Comment by sophiekuehn** [comment]
@Amejia481 i can't even reproduce it today in the regular build. Something needs to have happened on the example webpage itself.

**Comment by sophiekuehn** [comment]
I noticed that auto play is somehow still not blocked when e.g. a news site is opened through google news:

https://news.google.com/articles/CBMid2h0dHBzOi8vd3d3LmluZ2FtZS5kZS9uZXdzL3N0YXItd2Fycy1rbmlnaHRzLW9mLXRoZS1vbGQtcmVwdWJsaWMtbmV1YXVmbGFnZS1yZW1hc3Rlci1iaW93YXJlLWZhbnMtaGFtYnVyZy05MDE4MzMxMi5odG1s0gF7aHR0cHM6Ly93d3cuaW5nYW1lLmRlL25ld3Mvc3Rhci13YXJzLWtuaWdodHMtb2YtdGhlLW9sZC1yZXB1YmxpYy1uZXVhdWZsYWdlLXJlbWFzdGVyLWJpb3dhcmUtZmFucy1oYW1idXJnLTkwMTgzMzEyLmFtcC5odG1s?hl=de&gl=DE&ceid=DE%3Ade

If i open the site directly the block is working:
https://www.ingame.de/news/star-wars-knights-of-the-old-republic-neuauflage-remaster-bioware-fans-hamburg-90183312.amp.html
