### ISSUE TITLE
[Bug] Last Firefox app update for Android - after the last app update 'capture recorder' don't working, the video shows only a black screen. The old Firefox version or Opera shows the recorder video.

### ISSUE THREAD

**Issue by JoTONIC** [mozilla-mobile/fenix#16489]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
Were you in private mode? Can you take screenshots?

**Comment by JoTONIC** [comment]
Yes and No

**Comment by ekager** [comment]
Okay by default you can't record or screenshot private mode. Go to Settings -> Private Browsing -> Allow Screenshots if you want to change this behavior.

**Comment by JoTONIC** [comment]
thx for input, but I change the settings and the result the same, black record

**Comment by ekager** [comment]
Can you screen record in normal browsing?

**Comment by JoTONIC** [comment]
Yes-- Diese Nachricht wurde Mobil gesendet.Am 11.11.20, 23:29 schrieb ekager <notifications@github.com>:

   
  Can you screen record in normal browsing?

**Comment by ekager** [comment]
And you still can't screenshot once you change the setting? I can't reproduce once I toggle the setting. Which version of Fenix are you on?

**Comment by JoTONIC** [comment]
I can make a Screenshot, but the window is black like the capture video. For the version please take a look of the attachment. -- Diese Nachricht wurde Mobil gesendet.Am 12.11.20, 18:59 schrieb ekager <notifications@github.com>:

   
  And you still can't screenshot once you change the setting? I can't reproduce once I toggle the setting. Which version of Fenix are you on?

**Comment by ekager** [comment]
There's no attachment, you'll have to post a link to a video or upload a gif.

**Comment by JoTONIC** [comment]
thx for input, but I change the settings and the result the same, black record
![Screenshot_20201112_190110_org mozilla firefox](https://user-images.githubusercontent.com/74270700/98992014-ee326180-252c-11eb-9a76-747b3c172bf6.jpg)

**Comment by JoTONIC** [comment]
Done-- Diese Nachricht wurde Mobil gesendet.Am 12.11.20, 21:17 schrieb ekager <notifications@github.com>:

   
  There's no attachment, you'll have to post a link to a video or upload a gif.
