### ISSUE TITLE
Pinch Zoom doesn't work.   [Bug]

### ISSUE THREAD

**Issue by j13ag0** [mozilla-mobile/fenix#16488]
## Steps to reproduce
- Load any page in Firefox for Android.
- Try to zoom in to page contents via reverse-pinch - nothing happens.
- Same for attempting to zoom out using pinch - nothing happens.
This page is a good example of one that almost anyone would need to zoom in on to be able to navigate further:
    https://ttc.ca/Subway/index.jsp

### Expected behavior
Zoom is possible.

### Actual behavior
Zoom is not possible.

### Device information
* Android device: ?
Hardware: Google Pixel 3a
OS: Android 11

* Fenix version: ?
Firefox: 82.1.3 (Build: #2015774643)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8727)

**Comment by amedyne** [comment]
[:j13ag0](https://github.com/j13ag0) I  am not able to reproduce this problem on the same Firefox: 82.1.3 (Build: #2015774643) version.

**Comment by j13ag0** [comment]
Are there Firefox settings or modes that could disable page zooming?
I’ve searched for them but haven’t found anything yet. Any pointers you have would be appreciated. 
If those settings or modes don’t exist then the bug would seem pretty important to investigate.

**Comment by amedyne** [comment]
There shouldn't be any browser settings that affect page zooming. But this might be related to bug [1674063](https://bugzilla.mozilla.org/show_bug.cgi?id=1674063) that the team is investigating.

**Comment by kAlvaro** [comment]
Is there a way for we end users to provide helpful feedback on zooming issues? For me, pinch to zoom works but it's extremely unreliable. It does work, but most of the times the gesture is completely ignored, I need to do it several times until I get a reaction. I even thought it was a hardware issue until I realised it never fails in Chrome.

**Comment by SimonBrazell** [comment]
I can't pinch zoom (or zoom at all) on Duck Duck Go Apple Maps using Fenix 83.1.0, works fine using Chromium.

**Comment by karlcow** [comment]
This is a reproducible issue here on 
https://github.com/webcompat/web-bugs/issues/69003

1. Go to https://www.marinetraffic.com/en/ais/home/centerx:22.9/centery:28.6/zoom:4
2. Pinch out to zoom in

Expected: 
only the map is blown out

Actual:
the full ui is being enlarged.

**Comment by softvision-raul-bucata** [comment]
As observed with other issues, it seems that pages that contain videos or animation files (maps), can not be zoomed using pinch to zoom. 

**Notes:**
1. Reproducible regardless of the status of ETP.
2. Reproducible on the latest build of Firefox Nightly, Release.
3. Works as expected using Opera.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811586

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
