### ISSUE TITLE
Support notification triggers for PWAs

### ISSUE THREAD

**Issue by joshbuker** [mozilla-mobile/fenix#16484]
Apologies in advance if this is the wrong location, there are several options and I wasn't sure which one fit best.

### What is the user problem or growth opportunity you want to see solved?

This article describes pretty well the functionality requested: https://web.dev/notification-triggers/

In short, adding the ability for applications to specify a time or location-based trigger for notifications, e.g. a calendar app notifying when an event is about to start, or a TODO app reminding you to get milk when at the grocery store.

### How do you know that this problem exists today? Why is this important?

Currently applications must rely on native-level wrappers such as Ionic to provide this type of functionality, such that a pure PWA cannot compete with native apps when it comes to better tailored system notifications.

Adding notification trigger support would provide a better user experience by letting PWAs notify users about time critical information in a convenient way.

### Who will benefit from it?

Both application developers looking to use native level notifications and end users who use said apps would benefit from adding this functionality.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8724)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807424

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
