### ISSUE TITLE
[Bug] Prefill arrow (in search suggestions) should be facing downward in bottom toolbar mode 

### ISSUE THREAD

**Issue by violasong** [mozilla-mobile/fenix#16483]
Right now when you enter something into the address bar, the pre-fill arrows are pointing to the top-left regardless of toolbar position. We should have them point to the bottom-left instead when the user has the toolbar positioned at the bottom. E.g. ↙️

Thanks to @antlam for noticing this!

![image](https://user-images.githubusercontent.com/55994/98718924-e9f72000-2343-11eb-8ccd-485ddecffe83.png)

**Comment by abodea** [comment]
Verified as fixed **85.0.0-beta.2** with **Google Pixel 4 XL (11), Samsung Galaxy S10+ (10) OnePlus A3 (Android 6.0.1).**
