### ISSUE TITLE
[Telemetry] Grid View

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16485]
## Description & Product Manager / Data Scientist User Story

As a product manager, I am looking to understand how our users prefer to view their tabs (grid view or list view) as well as the effectiveness of our feature discoverability messaging.

Dismiss 
Go to settings

## What questions will you answer with this data?
- What % of users will be using grid view (tab view state)?
- What % of users will choose to "dismiss" the grid view CFR?
- What % of users will tap on "go to settings" on the CFR AND change their tab view setting to grid view?
- What % of users will tap on "go to settings" on the CFR but do not change their tab view setting to grid view?

## Acceptance Criteria
- [x] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [x] DS sign off on instrumentation methodology addressing product questions.
- [x] Event pings can be queried via re:dash
- [x] Event pings can be queried via amplitude
- [x] We are sending telemetry events for the actions listed in the requirements
- [x] We have documented the telemetry
- [x] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by eliserichards** [comment]
Current telemetry around grid view: 
- `metrics.tab_view_setting`: GRID or LIST

**Comment by eliserichards** [comment]
* What % of users will be using grid view (tab view state)?
This can be answered with the current `metrics.tab_view_setting.GRID` metric

* What % of users will choose to "dismiss" the grid view CFR?
Proposed:
   - Event: `tabs_tray.cfr_cancel`. Follows the standard of `private_browsing_shortcut.cfr_cancel`

* What % of users will tap on "go to settings" on the CFR AND change their tab view setting to grid view?
   - Event: `tabs_tray.cfr_go_to_settings`. Follows the standard of `private_browsing_shortcut.cfr_add_shortcut` ("A user pressed the "Add shortcut" button when the contextual feature recommender appeared.")
   - Event: `preferences.set_tab_tray_view` (name could be better). We can pass GRID or LIST here, similar to `metrics.tab_view_setting`

* What % of users will tap on "go to settings" on the CFR but do not change their tab view setting to grid view?
   - This will be handled with the above Events (a user clicks `tabs_tray.cfr_go_to_settings` but we receive no `preferences.set_tab_tray_view.GRID`

**Comment by eliserichards** [comment]
Data science ticket filed: https://jira.mozilla.com/browse/DO-393 (to be triaged on Monday 12/14)

**Comment by eliserichards** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/102120659-dd695a00-3e10-11eb-98c3-141f978d1d07.png">

**Comment by eliserichards** [comment]
Postponed discussion with DS team until next Monday (to accommodate design sprint work)

**Comment by bifleming** [comment]
@eliserichards this is one of the Telemetry items Vesta specifically called out as a priority for Q1, can we try to get some traction on it?

**Comment by eliserichards** [comment]
Notes from chat with Marissa: 

Preferred format for events (nested):
tabs_tray.cfr.dismiss
tabs_tray.cfr.go_to_settings -> interaction with cfr button 

if we can't layer like ^, do this:
tabs_tray.cfr_dismiss
with "tabs_tray" as top level

We can just use the metrics ping for changing the setting, we don't care about firing an event directly after the user clicks through, just if the setting has been changed at all.

**Comment by eliserichards** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

- What % of users will be using grid view (tab view state)?
- What % of users will choose to "dismiss" the grid view CFR?
- What % of users will tap on "go to settings" on the CFR AND change their tab view setting to grid view?
- What % of users will tap on "go to settings" on the CFR but do not change their tab view setting to grid view?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

We currently have telemetry to determine users' interactions with tabs in the tabs tray, and this ticket will add the necessary context to determine if this feature is being used and what the users' preferences are when interacting with their tabs. This directly supports our objectives to make the app user friendly and make features easy to find.
 
3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

We have no other way to track this.

4) Can current instrumentation answer these questions?

No, grid view and the tabs tray setting is a new feature.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Tabs grid view</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/fenix/issues/16485</td>
  </tr>
</table> 

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
 
This collection is documented in the `metrics.md` document document included in the project - https://github.com/mozilla-mobile/fenix/blob/master/docs/metrics.md

7) How long will this data be collected?  Choose one of the following:

This data should be collected for 6 months initially (with the potential to renew at that point).

8) What populations will you measure?

All channels, categories, and locales.

9) If this data collection is default on, what is the opt-out mechanism for users?

Users can opt of of data collection by disabling Usage and technical data from `Settings` -> `Data collection`.

10) Please provide a general description of how you will analyze this data.

The mobile DS team will use this data along with current tabs tray telemetry to answer the questions in #1 using Glean and/or Amplitude.

11) Where do you intend to share the results of your analysis?

The information will be available to only the Glean, Amplitude and with mobile teams.

12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:

N/A

**Comment by boek** [comment]
# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?
Yes, metrics.yaml and metrics.md

2) Is there a control mechanism that allows the user to turn the data collection on and off? 
Yes in the data collection settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?
Has expiry. Fenix team will monitor.

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Cat 2

5) Is the data collection request for default-on or default-off?
Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
No

7) Is the data collection covered by the existing Firefox privacy notice?
Yes

8) Does there need to be a check-in in the future to determine whether to renew the data?
Fenix team will review at expiry

9) Does the data collection use a third-party collection tool?
No

**Comment by gabrielluong** [comment]
@eliserichards We normally ask for QA for newly implement telemetry. Wondering if we should just do that here as well?

**Comment by gabrielluong** [comment]
Adding back QA since I think it should be done. We want to verify that we get an event ping whenever the grid view CFR is interacted with. A ping should be sent when the user clicks on "Go to settings" or "Dismiss".

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 1/29 using a Google Pixel (Android 10).
1. The user dismisses the CFR:
ping: 3726808d-7bf1-4d3b-9024-5457737f1e24
```
 {
          "category": "tabs_tray.cfr",
          "name": "dismiss",
          "timestamp": 44663
        }
```

2. The user goes to settings through the CFR:
ping: 9851fd20-f7a8-4a06-9e85-a0ccdcb8c3d4
```
{
          "category": "tabs_tray.cfr",
          "name": "go_to_settings",
          "timestamp": 25543
        }
```
[Glean dashboard 1](data:application/json;charset=utf-8,%7B%22metadata%22%3A%7B%22geo%22%3A%7B%22city%22%3A%22Cluj-Napoca%22%2C%22subdivision1%22%3A%22CJ%22%2C%22country%22%3A%22RO%22%2C%22db_version%22%3A%222021-01-25T18%3A17%3A59Z%22%7D%2C%22isp%22%3A%7B%22organization%22%3A%22Orange%20Romania%22%2C%22db_version%22%3A%222021-01-25T17%3A32%3A14Z%22%2C%22name%22%3A%22Orange%20Romania%22%7D%2C%22user_agent%22%3A%7B%22os%22%3A%22Android%22%7D%2C%22header%22%3A%7B%22date%22%3A%22Fri%2C%2029%20Jan%202021%2006%3A48%3A01%20GMT%22%2C%22x_debug_id%22%3A%22mira-210129001%22%7D%2C%22document_namespace%22%3A%22org-mozilla-fenix%22%2C%22document_type%22%3A%22events%22%2C%22document_version%22%3A%221%22%7D%2C%22submission_timestamp%22%3A%222021-01-29T06%3A48%3A02.334970Z%22%2C%22document_id%22%3A%223726808d-7bf1-4d3b-9024-5457737f1e24%22%2C%22normalized_channel%22%3A%22nightly%22%2C%22normalized_os%22%3A%22Android%22%2C%22normalized_os_version%22%3A%2210%22%2C%22normalized_country_code%22%3A%22RO%22%2C%22sample_id%22%3A99%2C%22client_info%22%3A%7B%22android_sdk_version%22%3A%2229%22%2C%22app_build%22%3A%222015790123%22%2C%22app_channel%22%3A%22nightly%22%2C%22app_display_version%22%3A%22Nightly%20210129%2005%3A00%22%2C%22architecture%22%3A%22arm64-v8a%22%2C%22client_id%22%3A%22fafe8aff-a526-4ce7-a0b7-4da8a4b0162d%22%2C%22device_manufacturer%22%3A%22Google%22%2C%22device_model%22%3A%22Pixel%22%2C%22first_run_date%22%3A%222021-01-29%2B02%3A00%22%2C%22locale%22%3A%22en-US%22%2C%22os%22%3A%22Android%22%2C%22os_version%22%3A%2210%22%2C%22telemetry_sdk_build%22%3A%2233.1.2%22%7D%2C%22events%22%3A%5B%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22source%22%3A%22UNKNOWN%22%7D%2C%22name%22%3A%22app_received_intent%22%2C%22timestamp%22%3A0%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22source%22%3A%22HOME%22%7D%2C%22name%22%3A%22search_bar_tapped%22%2C%22timestamp%22%3A2648%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22autocomplete%22%3A%22false%22%7D%2C%22name%22%3A%22entered_url%22%2C%22timestamp%22%3A5961%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A10112%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A10879%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22autocomplete%22%3A%22false%22%7D%2C%22name%22%3A%22entered_url%22%2C%22timestamp%22%3A13741%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A16373%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A17685%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22autocomplete%22%3A%22false%22%7D%2C%22name%22%3A%22entered_url%22%2C%22timestamp%22%3A20275%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A22389%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A23064%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22autocomplete%22%3A%22false%22%7D%2C%22name%22%3A%22entered_url%22%2C%22timestamp%22%3A25777%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A29440%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A30392%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22autocomplete%22%3A%22false%22%7D%2C%22name%22%3A%22entered_url%22%2C%22timestamp%22%3A33098%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A35227%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A36059%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22autocomplete%22%3A%22false%22%7D%2C%22name%22%3A%22entered_url%22%2C%22timestamp%22%3A38623%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A40442%7D%2C%7B%22category%22%3A%22tabs_tray.cfr%22%2C%22name%22%3A%22dismiss%22%2C%22timestamp%22%3A44663%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22first_frame_pre_draw_nanos%22%3A%221245185468%22%2C%22has_saved_instance_state%22%3A%22false%22%2C%22source%22%3A%22UNKNOWN%22%2C%22type%22%3A%22COLD%22%7D%2C%22name%22%3A%22app_opened_all_startup%22%2C%22timestamp%22%3A46127%7D%5D%2C%22ping_info%22%3A%7B%22end_time%22%3A%222021-01-29T08%3A48%2B02%3A00%22%2C%22reason%22%3A%22background%22%2C%22seq%22%3A0%2C%22start_time%22%3A%222021-01-29T08%3A47%2B02%3A00%22%7D%7D)

[Glean dashboard 2](data:application/json;charset=utf-8,%7B%22metadata%22%3A%7B%22geo%22%3A%7B%22city%22%3A%22Cluj-Napoca%22%2C%22subdivision1%22%3A%22CJ%22%2C%22country%22%3A%22RO%22%2C%22db_version%22%3A%222021-01-25T18%3A17%3A59Z%22%7D%2C%22isp%22%3A%7B%22organization%22%3A%22Orange%20Romania%22%2C%22db_version%22%3A%222021-01-25T17%3A32%3A14Z%22%2C%22name%22%3A%22Orange%20Romania%22%7D%2C%22user_agent%22%3A%7B%22os%22%3A%22Android%22%7D%2C%22header%22%3A%7B%22date%22%3A%22Fri%2C%2029%20Jan%202021%2006%3A52%3A31%20GMT%22%2C%22x_debug_id%22%3A%22mira-210129002%22%7D%2C%22document_namespace%22%3A%22org-mozilla-fenix%22%2C%22document_type%22%3A%22events%22%2C%22document_version%22%3A%221%22%7D%2C%22submission_timestamp%22%3A%222021-01-29T06%3A52%3A33.125618Z%22%2C%22document_id%22%3A%229851fd20-f7a8-4a06-9e85-a0ccdcb8c3d4%22%2C%22normalized_channel%22%3A%22nightly%22%2C%22normalized_os%22%3A%22Android%22%2C%22normalized_os_version%22%3A%2210%22%2C%22normalized_country_code%22%3A%22RO%22%2C%22sample_id%22%3A94%2C%22client_info%22%3A%7B%22android_sdk_version%22%3A%2229%22%2C%22app_build%22%3A%222015790123%22%2C%22app_channel%22%3A%22nightly%22%2C%22app_display_version%22%3A%22Nightly%20210129%2005%3A00%22%2C%22architecture%22%3A%22arm64-v8a%22%2C%22client_id%22%3A%227dccbc92-e6db-4303-9c0a-3d44e5cb8e33%22%2C%22device_manufacturer%22%3A%22Google%22%2C%22device_model%22%3A%22Pixel%22%2C%22first_run_date%22%3A%222021-01-29%2B02%3A00%22%2C%22locale%22%3A%22en-US%22%2C%22os%22%3A%22Android%22%2C%22os_version%22%3A%2210%22%2C%22telemetry_sdk_build%22%3A%2233.1.2%22%7D%2C%22events%22%3A%5B%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22source%22%3A%22UNKNOWN%22%7D%2C%22name%22%3A%22app_received_intent%22%2C%22timestamp%22%3A0%7D%2C%7B%22category%22%3A%22onboarding%22%2C%22name%22%3A%22finish%22%2C%22timestamp%22%3A2369%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_in_new_tab%22%2C%22timestamp%22%3A3931%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_default%22%2C%22timestamp%22%3A3933%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A6494%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A7516%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_in_new_tab%22%2C%22timestamp%22%3A8309%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_default%22%2C%22timestamp%22%3A8310%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A10516%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A11237%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_in_new_tab%22%2C%22timestamp%22%3A12051%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_default%22%2C%22timestamp%22%3A12051%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A13960%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A14641%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_in_new_tab%22%2C%22timestamp%22%3A15362%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_default%22%2C%22timestamp%22%3A15365%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A17063%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A17959%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_in_new_tab%22%2C%22timestamp%22%3A18673%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_default%22%2C%22timestamp%22%3A18673%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A20378%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22new_tab_tapped%22%2C%22timestamp%22%3A21621%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_in_new_tab%22%2C%22timestamp%22%3A22474%7D%2C%7B%22category%22%3A%22top_sites%22%2C%22name%22%3A%22open_default%22%2C%22timestamp%22%3A22474%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A24193%7D%2C%7B%22category%22%3A%22tabs_tray.cfr%22%2C%22name%22%3A%22go_to_settings%22%2C%22timestamp%22%3A25543%7D%2C%7B%22category%22%3A%22tabs%22%2C%22name%22%3A%22setting_opened%22%2C%22timestamp%22%3A25561%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22first_frame_pre_draw_nanos%22%3A%221235736409%22%2C%22has_saved_instance_state%22%3A%22false%22%2C%22source%22%3A%22UNKNOWN%22%2C%22type%22%3A%22COLD%22%7D%2C%22name%22%3A%22app_opened_all_startup%22%2C%22timestamp%22%3A30981%7D%5D%2C%22ping_info%22%3A%7B%22end_time%22%3A%222021-01-29T08%3A52%2B02%3A00%22%2C%22reason%22%3A%22background%22%2C%22seq%22%3A0%2C%22start_time%22%3A%222021-01-29T08%3A51%2B02%3A00%22%7D%7D)
