### ISSUE TITLE
The loading speed

### ISSUE THREAD

**Issue by 123336-mike** [mozilla-mobile/fenix#16499]
### What is the user problem or growth opportunity you want to see solved?
Hello, developer, can you optimize the loading speed of the website? The total card is about 70% when the page is loaded.
### How do you know that this problem exists today? Why is this important?
I think it's important to use it
### Who will benefit from it?

everyone

**Comment by ekager** [comment]
Thanks for filing! I'm not sure I fully understand. Please open a new issue describing what you're talking about in more detail.
