### ISSUE TITLE
[Bug] The tabs have broken lower borders in grid view

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#16500]
## Steps to reproduce 
1. Open a few tabs in normal or private browsing.
2. Go to Settings - Tabs and enable the grid view.
3. Go back to the tabs tray and observe the UI of the last opened tab - the purple lower border.

### Expected behavior
Both the inner and the other borders of the last opened tab are rounded and surround perfectly the screenshot of the opened tab.

### Actual behavior
The inner borders of the last opened tab are cut and do not surround perfectly the screenshot of the opened tab.
Possibly a regression of #16323, @Mugurell could you take a look.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), OnePlus A3 (Android 6.0.1)
* Fenix version: 11/11 Nightly build

<img src="https://user-images.githubusercontent.com/40694158/98788428-90f1bf80-2409-11eb-90b3-a77e3e4b89ba.png" width="300" height="550" />

**Comment by Mugurell** [comment]
This is not really a regression but something we need to add support for.
Thanks for catching this!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 11/16 Nightly build with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy A6 (Android 5.1.1).
