### ISSUE TITLE
[Bug] Fenix crashes when gfx.webrender.software is enabled

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#16503]
## Steps to reproduce
1. Launch Fenix;
2. In about:config set gfx.webrender.software to true;
3. Restart Fenix and access any webpage
### Expected behavior
Firefox Prerview browser should not crash.
### Actual behavior
Firefox Prerview crashes when gfx.webrender.software is set to true.

### Device information

* Android device: Samsung Galaxy S9 (Android 8.0.0)
* Fenix version: Firefox Preview Nighlty 201110 (Build #2015774859)
* The issue also occurs on Reference browser see https://github.com/mozilla-mobile/reference-browser/issues/1366 for more information

**Comment by makotokato** [comment]
I think that we don't support this yet.  You should watch https://bugzilla.mozilla.org/show_bug.cgi?id=1673342

**Comment by LaurentiuApahideanSV** [comment]
The issue no longer occurs on Firefox Preview Nightly 5/19.
