### ISSUE TITLE
[Bug] no reaction on second tap on any link

### ISSUE THREAD

**Issue by bluberly** [mozilla-mobile/fenix#16506]
[comment]: # Freshly installed FF Nightly - no reaction when selecting a link when pressing the 2nd time after browser was started

## Steps to reproduce
Fresh installation
Open any web page
select a link -> first time link as followed and new page is opened, seconds time does not work anymore.

### Expected behavior
Follow the link
### Actual behavior
Nothing.

When pressing long time on link a pop windows with various link options shows up. The "Back" option works, entering a new URL in the title bar works etc. Only link selection does not work.

Background: Using FF Nightly for a long time and regularly update. However new option to reload the current tab when swiping down was not offered in settings menu. Uninstalled the latest updated version and did a fresh install. With fresh install the issue started.

Did several un- and re-installs. Issue persists.

Chrome browser is not affected.

### Device information

* Android device: Google Pixel 3, Android 11, patch level Nov 5, 2020
* Fenix version: Nightly 201110 17:02 from 11/11/20202

**Comment by bluberly** [comment]
Installed for testing purposes the Firefox browser - it has exactly the same behavior and issues.

**Comment by bluberly** [comment]
Uninstalled Nightly 201110 and installed Nightly 201119 17:01 - issue continues to exist.
Chrome browser works, Opera browser works, too.

**Comment by ekager** [comment]
Are you still seeing this in nightly?

**Comment by bluberly** [comment]
> Hi thanks for filing! A few questions.
> Are you still seeing this in nightly?
> Is this the same issue as #16337 ?

I don't have the issue anymore but it only went away with the following (as many un- and re-installs didn't solve the issue, the original Firefox had the same issue, device reboots didn't help either):

1) installed Opera browser (worked like Chrome without any issues)
2) re-installed FF nightly -> then it worked
3) un-installed Opera

Since then all the many FF nightly updates do work.

Yes, #16337 sounds to describe the issue I had.

**Comment by ekager** [comment]
Okay let's close for #16337 . Thanks!
