### ISSUE TITLE
FNX-5161 ⁃ [Fenix]  https://www.smn.gob.ar does not display the weather info

### ISSUE THREAD

**Issue by gaby2300** [mozilla-mobile/fenix#1650]
## Steps to reproduce
1. Browse to the site.
1. Notice the lack of info: temperature, wind, etc.

### Expected behavior
Should display the actual temperature, wind, etc.

### Actual behavior
Does not display the weather info.

### Device information
Sony Xperia Z3C

* Android device: ?
Android 6.0.1
* Fenix version:  Firefox Mobile 68.0, Build #11051219

![Servicio Meteorológico](https://user-images.githubusercontent.com/2151784/56165837-60863d00-5faa-11e9-9175-29e644db44c9.png)

**Comment by kbrosnan** [comment]
Adding the url to a comment https://www.smn.gob.ar

**Comment by kbrosnan** [comment]
I can't reproduce this behavior. The website shows the temperature after the page finishes loading for me.

**Comment by bsurd** [comment]
Getting the same behavior as Kevin, but only after allowing location access. Removing the QA needed flag.

**Comment by gaby2300** [comment]
Tried again allowing location access and it worked!
Thanks for your comment@bsurd!

**Comment by gaby2300** [comment]
Tried again allowing location access and it worked!
Thanks for your comment@bsurd!
