### ISSUE TITLE
[Bug] native crash when scrolling in GitHub issue [@ mozilla::Maybe<T>::value ]

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#16516]
### Steps to reproduce

1. open https://github.com/matomo-org/matomo/issues/16689 and scroll (I was not yet able to reproduce on other issues)

### Expected behavior

No crash.

### Actual behavior

It always crashes with this signature: [@ mozilla::Maybe<T>::value ]

https://crash-stats.mozilla.org/report/index/670601c3-4956-4e91-9ca7-f74510201112

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.12 (Android 10)
* Fenix version: master branch revision 710d68977d6ea91e85d3f3e77b4c1d309e1ff041

**Comment by makotokato** [comment]
Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1676814

**Comment by kbrosnan** [comment]
Closing as this is tracked on Bugzilla.
