### ISSUE TITLE
[Bug] (regression) missing space between header bar and {remove downloads|delete history} button

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#16519]
### Steps to reproduce

1. download something
2. open the downloads view

_or_

1. open the history view

### Expected behavior

There is some space above the remove downloads / delete history button.

### Actual behavior

There no space. It's a regression that does not exist in Firefox Beta.

![Screenshot_20201112-094520](https://user-images.githubusercontent.com/1100614/98917457-b267af80-24cc-11eb-8fb7-20895d11012c.jpg)

### Device information

* Android device: OnePlus 7T Pro McLaren Edition / Oxygen OS 10.0.12 (Android 10)
* Fenix version: master branch revision 710d68977d6ea91e85d3f3e77b4c1d309e1ff041

**Comment by joc-a** [comment]
I would like to work on this!

**Comment by joc-a** [comment]
#17358

**Comment by Mugurell** [comment]
Thank you all for chiming in here but I don't think the changes from https://github.com/mozilla-mobile/fenix/pull/17358 are needed anymore.

- The "Delete downloads" button is not used anymore following #16541. I've created #17393 to know for sure if the related code can be removed.
- Regarding "Delete history" I'd say the proposed changes would make it look better but I don't see any recent change that could regress the UI and didn't find an Abstract or clear specs for how that screen should look.
Asking UX if we should add a 8dp top margin to the "Delete history" button that would result in the following:

| Before   |   After   | 
|----------|-------------|
| <img src="https://user-images.githubusercontent.com/11428869/104187518-932fc480-5420-11eb-87fb-10eae337dc37.png"  /> | <img src="https://user-images.githubusercontent.com/11428869/104187598-b78ba100-5420-11eb-822c-cab282df1347.png" /> |

**Comment by topotropic** [comment]
Yes, please – the added 8dp is looking good! Thanks, @Mugurell

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 1/19 with Samsung Galaxy Tab S3 (Android 8).
I will close this issue and remove the qa:needed label.
