### ISSUE TITLE
[Bug] Tab counter off center when closing 10th tab

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/fenix#16527]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Open ten tabs.  Close any one of them.

### Expected behavior

The tab counter is centered.

### Actual behavior

The tab counter is off-center.

### Device information

* Android device: Huawei MediaPad M5
* Fenix version: Nightly 201111 17:01 (Build #2015775051)
 
![2020-11-12 14 08 50](https://user-images.githubusercontent.com/848247/98948081-571fd680-2539-11eb-90dc-08981c42b103.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8753)

**Comment by sflorean** [comment]
I was able to reproduce the issue on Pixel 4 XL (Android 11) on latest Nightly build.

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20248#issuecomment-874075060

**Comment by ueen** [comment]
Confirmed on Pixel 4 5G, latest Android

But there seem to be other times when its also cut off, see screenshot https://github.com/mozilla-mobile/fenix/issues/20248

**Comment by Nickoriginal** [comment]
> see screenshot #20248

https://user-images.githubusercontent.com/5067479/124463340-0b08f700-dd93-11eb-911e-b142adc2f078.png

**Comment by mariansima** [comment]
I would like to add some alternative repro steps for Nightly 93.0a1 2021-09-07: 
1. Open 9 (or 99) tabs
2. Navigate between them by swiping the search bar
3. From the 3-dot menu select Report Site Issue...
4. Observe the 10th (or 100th) tab counter

![241422228_399559661536473_5457293116700642999_n](https://user-images.githubusercontent.com/89511597/132360401-c629104a-aa9b-4140-9cfa-df2462648673.jpg)
![241562383_524750858621850_3480733949250114150_n](https://user-images.githubusercontent.com/89511597/132360406-3ec5b191-baf8-4282-aec1-7809c20ada87.jpg)

**Comment by sflorean** [comment]
This issue is still reproducible on Nightly 100.0a1 with Samsung A32 (Android 11).

**Comment by gaul** [comment]
This is still reproducible; please reopen.
