### ISSUE TITLE
[Bug] Easy access to Leanplum device ID (user ID) 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16525]
## Steps to reproduce
* Search app for a way to get the leanplum ID

### Expected behavior
Should be able to find the device ID (user ID)

### Actual behavior
Device ID (user ID) isn't displayed in about:config

### Device information

* Android device: all
* Fenix version: Nightly Build 201111

### Notes
✔️ **Fennec**: mma.device_id was available in about:config
✔️ **Firefox for iOS**: Similar to our "Secret settings", tapping 5 times the version number displays it under the "LP Setup" section

**Comment by amedyne** [comment]
Closing this as we no longer integrate with Leanplum.
