### ISSUE TITLE
[Bug] No crash report when crashing on lucidchart.com

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#16529]
## Steps to reproduce

On a Moto G5, navigate to this URL in Firefox Nightly: https://www.lucidchart.com/pages/de

After a few seconds, the entire browser crashes for me. However, I do not get a notification to submit the crash report. And the crash does not show up on about:crashes.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 201111 17:01 (Build #22015775049), AC: 66.0.20201109143146, b44b70ee1, GV: 84.0a1-20201109095222, AS: 63.0.0

**Comment by kbrosnan** [comment]
I did get a couple crashes to the desktop. I also got a crash in the graphics driver. https://crash-stats.mozilla.org/report/index/2805195e-683e-47d2-af5d-14cda0201112

Seems simlar to bz-1669611

**Comment by mstange** [comment]
I see, so it successfully generates a crash report for you. I don't get the report.

**Comment by test491** [comment]
followed Steps to reproduce given above

not reproducible:
* version: 86.1.1

(interestingly) reproducible for:
* version: 87.0.0-beta.1 (Build #2015795065) AC: 73.0.0, 69a800e47 GV: 87.0-20210222154334 AS: 71.0.0
* version: Nightly 210224 (Build #2015795113) AC: 73.0.20210223143117, 05f3e3cc7 GV: 87.0a1-20210222084406 AS: 71.0.0

**Comment by mariansima** [comment]
Could not reproduce on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29
