### ISSUE TITLE
FNX-5162 ⁃ Custom tab title showed up in normal mode

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1653]
![Screenshot](https://user-images.githubusercontent.com/1250545/56167704-b993a800-5f8d-11e9-9432-695848160a01.jpg)UNITO-UNDERSCORE!20190415-144745!UNITO-UNDERSCORE!Fenix!

**Comment by jonalmeida** [comment]
If it's not a dup of https://github.com/mozilla-mobile/fenix/issues/1637, it's a dup of https://github.com/mozilla-mobile/fenix/issues/1639.
