### ISSUE TITLE
Downloads UX updates

### ISSUE THREAD

**Issue by apbitner** [mozilla-mobile/fenix#16541]
Based on some technical constraints that were encountered in the development of deletion functionality for downloads, UX recommends the following changes:

- Each file should have the trash icon shown on the right. Tapping on the icon will remove the file from the downloads list, however, the actual file won't be deleted due to technical constraints.
- In multi-select mode, the 3-dot icon should be shown on the right of the toolbar. It will have two options: `Select all` and `Remove`
- The `Delete downloads` button can be removed as it is no longer needed.
- Change the snackbar copy shown after removing a file to `Removed [filename]`
- Change the empty state copy to `No downloaded files`

All changes are reflected in Abstract: https://share.goabstract.com/a0ca3665-5556-4995-b1af-b2fb841a4b6a

**Comment by Amejia481** [comment]
> Each file should have the trash icon shown on the right. Tapping on the icon will remove the file from the downloads list, however, the actual file won't be deleted due to technical constraints.

This also follow the same pattern as what we are doing on Firefox desktop, and what other browsers are doing 👍🏽 .

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 12/14 Nightly build with Samsung Galaxy Tab S6 (Android 10), Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9):
* each downloaded file has a trash icon displayed on the right,
* tapping on the icon removes the file from the downloads list,
* in multi-select mode, the 3-dot icon is displayed on the right of the toolbar. It has two options: "Select all" and "Remove".
* the "Delete downloads" button is no longer displayed,
* the snackbar copy shown after removing a file is "Removed [filename]",
* the empty state displays "No downloaded files".
![downloads](https://user-images.githubusercontent.com/40694158/102094647-3a720980-3e2b-11eb-8d28-d93a322480ae.png)

**Comment by yump** [comment]
How about an 🗙 instead of a trash icon? Trash icon still seems to imply that the actual file will be "trashed".
