### ISSUE TITLE
[Pull To Refresh][Bug] Pull to refresh makes navigation on romatoday.it impossible

### ISSUE THREAD

**Issue by oidualc** [mozilla-mobile/fenix#16545]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Open https://www.romatoday.it/
- Scroll down to page 2
- Scroll up to page 1
### Expected behavior
You return to page 1
### Actual behavior
Pull to refresh is triggered
### Device information

* Android device: OnePlus 3T, Android 10
* Fenix version: Nightly 201112

**Comment by Mugurell** [comment]
Probably the same underlying issue as for https://github.com/mozilla-mobile/fenix/issues/16914
