### ISSUE TITLE
[Bug] Loss of information density in tab tray in list view after #11376 (reverse order of tabs in tab list)

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#16553]
## Steps to reproduce
Install the latest nightly build where newer tabs are added at the bottom of the tab list (I preferred it the other way, a lot, but that's not the point here ;) ) (after #11376 was implemented)
Make sure tab tray is in list view.
Open 9 new tabs
Click the tab counter icon to display the tab tray

### Expected behavior
The same amount of tabs should be displayed now as in the previous builds when tabs were ordered in the other way (newer tabs on top), 8 in the case of my phone.

![image](https://user-images.githubusercontent.com/218971/99074505-2632b680-25b8-11eb-8bc3-d981a49ba1d1.png)

### Actual behavior
Only 6 are displayed, as a lot of useful space is lost above and below the tabs themselves

![image](https://user-images.githubusercontent.com/218971/99074473-17e49a80-25b8-11eb-8981-20411afbe7c9.png)

### Device information

* Android device: Redmi Note 7

**Comment by Dunexus** [comment]
It is centered around current tab. On your second screen, it shows the "Select tabs" button that is at the very bottom of tab tray.

In you first situation, open tab "test 1" and then open tab tray, it will be the same.

**Comment by klint** [comment]
Yes, that's true, but that is not quite my point actually: the comparison is done in the same situation in both cases, which is going back to the list from the last opened tab.
Maybe the need is only to remove the "Select tabs" button, as long pressing on the tabs themselves does the same... like in every other list in every other app.

**Comment by Dunexus** [comment]
Then the issue should be about asking for the button to be removed not about the loss of information as coming from the tab at the very bottom you see the same amount of information.

**Comment by klint** [comment]
I don't get your point. You don't see the same amount of information anymore as my screenshots clearly show, and this happen right from the first time you click on the tab counter.

And actually I don't care how one could resolve that, as removing the useless "select tabs" is one option only. I prefer to let the UX team find the best way to get the same information density as before back! 😊
