### ISSUE TITLE
[Bug] Downloads from mega.nz stay at 99%

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#16552]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Try to download something from mega.nz
Download stays at 99%
### Expected behavior
It should go to 100% and prompt me to save the file. 
i downloaded chrome, and it worked normally, it went to 100%, prompted me to save the file and it saved the file..
### Actual behavior
The download stays at 99%, nothing happens after that...
### Device information
* Android device: Lenovo P2 (Kuntao)
* Fenix version: 82.1.1
* Android version: LineageOS 17.1 (Android 10)

**Comment by Amejia481** [comment]
Thanks @aha999 for reporting, are you able to replicate in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)? If it's not much trouble could you share the download like?

**Comment by Amejia481** [comment]
Closing this issue for now, if you are still able to reproduce please feel free to reopen
