### ISSUE TITLE
[Bug] scrolling normal tabs from private is impossible

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#16554]
### Steps to reproduce

1. Open multiple tabs so the list will be scrollable
2. Open some tab in the middle
3. Switch to the private mode and open a private tab
4. Open tabs list (tap the tabs button), switch to normal mode and try to scroll.

### Expected behavior
Tabs must be easy scrollable

### Actual behavior
Tabs list just closed trying to scroll down

### Device information

* Android device: OP3T, LineageOS 17.1 on Android 10
* Fenix version: 82.1.3 (Build #2015774643)

**Comment by kbrosnan** [comment]
This works for me on Nightly 84. I recall us resolving a problem similar to this recently. Please check Firefox Beta and Nightly for correct behavior.

**Comment by 532910** [comment]
Indeed!
