### ISSUE TITLE
[Question]: what properitary part is involved when playing video stream?

### ISSUE THREAD

**Issue by stevenleeS0ht** [mozilla-mobile/fenix#16569]
This is just a question, but may help a lot of users, especially for those open source related users.

**Comment by stevenleeS0ht** [comment]
If it is convenient, is it possible to add a list of proprietary component in Fenix project under wiki section?

**Comment by kbrosnan** [comment]
This team works on the front end of the browser. We don't have the expertise in video codecs to say. You can try asking the media team at https://chat.mozilla.org/#/room/#media:mozilla.org
