### ISSUE TITLE
[Bug] Cannot open APK files on Kindle Fire

### ISSUE THREAD

**Issue by ekr** [mozilla-mobile/fenix#16560]
## Steps to reproduce

Download the Fenix APK from Github release
Click to open

### Expected behavior

Open installer. Note that this worked fine when I updated to Fenix from Fennec right before this.

### Actual behavior

Error that says "No app found to open APK files"

### Device information

* Android device: Kindle Fire HD 8 (6th generation)
* Fenix version: 82.1.3 (downloaded from Github)

**Comment by ekr** [comment]
Also, I have allow install of unknown apps on.

**Comment by ekr** [comment]
FireOS 5.6.8.0 (626542120)

**Comment by kbrosnan** [comment]
Likely this is fixed on our [nightly release](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/build/arm64-v8a/target.apk) or Beta release. Unfortunately you will need to use something other than Firefox to download the APKs.

**Comment by ekr** [comment]
@kbrosnan I think I need an ARMv7  rather than ARM64 version. Do you have a link to that?

**Comment by Amejia481** [comment]
> Error that says "No app found to open APK files"

We normally show this message when there are not apps that can handle the file type, it could be the table doesn't have a file manager to handle the installation process, could you try with [nightly](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/build/arm64-v8a/target.apk)

**Comment by ekr** [comment]
I think I need an armv7 nightly. Happy to try if you can point me at one.

**Comment by st3fan** [comment]
Give this a try https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest/armeabi-v7a

**Comment by ekr** [comment]
That installs correctly, but produces the same error.

- When I click "Open" from the prompt at the bottom of the screen I get
"Could not open file"
- When I pull down from the notification and tap on it I get "No app found
to open apk files"

**Comment by Amejia481** [comment]
Verify likely to be fixed after https://github.com/mozilla-mobile/android-components/pull/9558 lands similar to https://github.com/mozilla-mobile/fenix/issues/17502

**Comment by ebalazs-sv** [comment]
We do not have a Kindle Fire device to verify this issue.
@ekr Hi! I this issue fixed on your device, on the latest Nightly? Thanks!

**Comment by ebalazs-sv** [comment]
This issue is not reproducible on Nightly 3/4 with the following devices:
- Motorola Moto G6 (Android 8), 
- Google Pixel 2 (Android 9), 
- Samsung Galaxy Tab S3 (Android 8), 
- Nexus 5 (Android 6.0.1).

I will remove the qa:needed label and close this issue.
