### ISSUE TITLE
Fixed, full height tab list height

### ISSUE THREAD

**Issue by tukusejssirs** [mozilla-mobile/fenix#16568]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Currently, the tab list is ‘hiding’ in the URL bar when the user swipes down. Of course it does this in three steps (to top tab, hiding half the tab list, hiding all the tab list). The issues is when I want to make sure I am at the top, I’ll swipe down and the tab list disappears (to my frustration).

The issue is much more prominent in landscape, when instead of hiding half the tab list, it hides most of it leaving visible only the top part of the list of approx URL bar height.

Personally, I never liked the hiding tab list. I wish I could disable it in the settings and used fixed, full height tab list.

### How do you know that this problem exists today? Why is this important?

It just exists on my OnePlus 6T. :wink:

It is important from the UX point of view.

### Who will benefit from it?

Everyone who don’t ‘floating height’ tab list, just like me. 🤣

**Comment by kbrosnan** [comment]
There are no plans for a full screen tabs view at this time.
