### ISSUE TITLE
[Pull To Refresh][Bug] touch-action: none must disable pull-to-refresh

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#16574]
## Steps to reproduce

 1. Load either of these testcases: [scrollable testcase](https://bugzilla.mozilla.org/attachment.cgi?id=9187855) or [non-scrollable testcase](https://bugzilla.mozilla.org/attachment.cgi?id=9187856)
 2. Do a downwards pan gesture inside the box with the black border.

### Expected behavior

Pull to refresh should **not** be triggered.

### Actual behavior

Pull to refresh is triggered.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 201112

Honoring `touch-action: none` is a requirement for web compatibility. This property is used, for example, on pages where you can paint things on a canvas, or on pages which implement their own touch gesture handling.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8784)

**Comment by emilio** [comment]
Also, `overscroll-behavior-y: none` should disable it, see #16599.

**Comment by mstange** [comment]
That's #16576.

**Comment by emilio** [comment]
Definitely still relevant?

**Comment by emilio** [comment]
Still relevant

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807074

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
