### ISSUE TITLE
[UI] Dark tabs title bar

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#16573]
I need the dark tabs title bar on Firefox (like Chrome)
![Screenshot](https://user-images.githubusercontent.com/23485114/99154007-b7418480-26c1-11eb-8bbc-d6c40a6be678.png)

**Comment by s-ankur** [comment]
Thanks for reporting and the screenshots. I can see that this issue is a duplicate of https://github.com/mozilla-mobile/fenix/issues/16152

**Comment by kbrosnan** [comment]
Closing as a duplicate
