### ISSUE TITLE
[Pull To Refresh][Bug] Pull to refresh should only trigger at the start of a pan gesture, not during a gesture which already resulted in scrolling

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/fenix#16577]
The current implementation of the pull-to-refresh gesture handling works differently than in Chrome, and causes unintended page refreshes because it triggers too easily.

## Steps to reproduce

 1. On any page, in Firefox Nightly for Android, scroll to the top.
 2. Scroll down a bit, for example by 20% of the viewport height.
 4. In one continuous panning motion, scroll up to the top and down again.

### Expected behavior

You should be able to scroll up and down again, if you didn't start out at the very top.

### Actual behavior

As soon as you hit the top edge, the scroll gesture is "swallowed" and turned into a pull to refresh gesture.

Pull to refresh should only be triggered when the user is intending to trigger it. Requiring the overscroll to be at the very start of the gesture is a good extra hurdle to weed out unintentional gestures.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 201112

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8786)

**Comment by hiikezoe** [comment]
Oh, this sounds like what I commented in https://github.com/mozilla-mobile/fenix/issues/16575#issuecomment-727677687 as "No. 5 dot".

**Comment by Mugurell** [comment]
Thank you.
This makes sense.

**Comment by agi** [comment]
Another case: https://bugzilla.mozilla.org/show_bug.cgi?id=1677413

> User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
>
> Steps to reproduce:
>
> I did this in Firefox for Android Nightly 201114 17:01 (Build #2015775625), AC: 66.0.20201109143146, bb44b70ee1, GV: 84.0a1-20201109095222, AS: 63.0.0, with the address bar configured to be at the bottom of the page.
>
> I loaded attachment 9187912 [details] from bug 1663000, then I scrolled to the bottom, and the address bar disappeared.
>
> Then tried to scroll back upwards by swiping the page down.
>
> Actual results:
>
> This makes the address bar reappear and reloads the page (with recycle icon appearing and rotating) and no scrolling occurs.
>
> It therefore becomes impossible (without knowing to clear the page from Firefox's cache) to scroll back up to view the top of the list. The top part of the page becomes effectively-permanently hidden from a normal user's perspective.
>
> Note: With the address bar at the top, the behaviour is the same, except the address bar does not reappear (9 times out of 10) when attempting to scrolling back up, thus leaving the user in a position whereby there is no obvious way to retrieve the address bar. (Note: rotating the screen can sometimes help.)
>
> Expected results:
>
> It would ordinarily be expected that swiping down would scroll you back up the list towards the top of the list, and that only once no more scrolling is possible would a swipe down potentially trigger a page reload.
>
> It should be possible to retrieve the address bar on demand.

**Comment by Mugurell** [comment]
Expect this to be simplified after https://bugzilla.mozilla.org/show_bug.cgi?id=1678505.
Blocked until then.

**Comment by Mugurell** [comment]
Let's keep track of this with the help of the meta - https://github.com/mozilla-mobile/fenix/issues/16577

**Comment by Mugurell** [comment]
Still an issue.

**Comment by mstange** [comment]
Still an issue.

**Comment by zapy85** [comment]
Status on this?
What can we do to help out and get pull-to-refresh in to stable? It's been 2 years now!

**Comment by hiikezoe** [comment]
I believe this is an issue in Fenix (or AC) since bug 1678505 landed.

**Comment by mstange** [comment]
Still an issue, as far as I know.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807073

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
