### ISSUE TITLE
[Feature request] Configurable content process limit in settings

### ISSUE THREAD

**Issue by magnetite2** [mozilla-mobile/fenix#16589]
### What is the user problem or growth opportunity you want to see solved?
Firefox Fenix, unlike Firefox desktop does not have a way to configure the amount of content processes it can use in the settings menu. 
### How do you know that this problem exists today? Why is this important?
There is no easy way to configure the number of content processes without digging through the about:config page. Could be useful if there was a setting for it in the settings menu. 
### Who will benefit from it?
Pretty much anyone who uses lots of tabs and such. Although I'm not sure if having one content process means that if something happens, the entire browser will crash.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8797)

**Comment by kbrosnan** [comment]
Mobile does not plan on exposing this.
