### ISSUE TITLE
[Bug] Tab count 0

### ISSUE THREAD

**Issue by EldoreiJK** [mozilla-mobile/fenix#16587]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open some (count x) tabs in normal mode.
Open 1 tab in privacy mode.
Go back to Android system, close private tabs using notification about opened private tab.
Reopen browser.
### Expected behavior
Reopened browser with last normal tab, tab count shown as x.
### Actual behavior
Reopened browser with last normal tab, tab count shows 0. When tab button is pressed, I can see all normal tabs, I can scroll them, I can open different tab than last one, but as long as I don't open a new tab, tab counter is still 0. When new tab is opened, it shows properly x+1.
### Device information

* Android device:
Redmi Note 4, Android 7.0 NRD90M, MIUI global 11.0.2
* Fenix version:
Nightly 201114 17:01 (Build #2015775627)
AC: 66.0.20201109143146, b44b70ee1
GV: 84.0a1-20201109095222
AS: 63.0.0

**Comment by csadilek** [comment]
We landed a fix for this today. It missed today's Nightly build, but should go out tomorrow in Nightly 201117.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 11/18 with Xiaomi Redmi Note 8T (Android 9).
