### ISSUE TITLE
[Bug] moving up in map applications refreshes instead

### ISSUE THREAD

**Issue by lilydjwg** [mozilla-mobile/fenix#16580]
## Steps to reproduce

* Open this Minecraft map: https://map.nyaacat.com/nyaa/
* zoom in
* try to move around

### Expected behavior

* I could move around in all directions

### Actual behavior

* I can only move to see the left, the right, and downwards. When I try to move to see the area upwards (drag the map down) beyond where I started to move, the refresh icon appears and will refresh the page if dragged too much.

This should have been happening only recently.

A similar issue happens with Google Maps: the map itself moves fine, but I need to be extremely careful (or lucky) to drag down the drawer at the bottom.

### Device information

* Android device: Sony Xperia XZ2 Compact
* Fenix version: Nightly 201109 17:01 (Build #2015774667)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8788)

**Comment by lilydjwg** [comment]
windy.com has the same issue.

**Comment by SoftVision-LorandJanos** [comment]
Hi @lilydjwg ! I can reproduce this issue using the build you logged it with (Nightly 201109 17:01 - Build #2015774667), the moving upwards on the map is compromised but manageable, however on the latest Nightly build (210406 05:01 - GV89) this issue is not reproducible anymore.
Device used: HTC Nexus 9 with Android 7.1.1

**Comment by lilydjwg** [comment]
Great, most maps work as expected now! But this one doesn't: https://leafletjs.com/examples/quick-start/example.html (I have a page using leaflet like this and it has the problem too).

Also this site: https://aqicn.org/ You need to zoom the map by clicking the zoom icon, then zoom again to make it largest (when it doesn't say "use two fingers to move the map").

My nightly is 210405 this time.

**Comment by SoftVision-LorandJanos** [comment]
Hi @lilydjwg ! Thanks for the added information. I've tested the behavior on the addresses you mentioned above and I could reproduce the issue for both cases. Verified on the latest Nightly (210429 05:01) GV90.0a1 on a HTC Nexus 9 and on a Motorola Nexus 6, both with Android 7.1.1.

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01

**Comment by karlcow** [comment]
There is a very similar issue which has been recently reported on webcompat.
https://github.com/webcompat/web-bugs/issues/92666

**Comment by lilydjwg** [comment]
Not reproduced with latest nightly, closing.
