### ISSUE TITLE
Implement browser.downloads.download WebExtension API

### ISSUE THREAD

**Issue by kuanyui** [mozilla-mobile/fenix#16585]
### What is the user problem or growth opportunity you want to see solved?
I noticed WebExtension API `browser.downloads.download` doesn't work anymore after Firefox for Android upgrading to Fenix.

### How do you know that this problem exists today? Why is this important?
In [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#downloads), the support of `browser.downloads.*` are described as `48 — 79`.

I wonder if `browser.downloads.download` would come back to new Firefox for Android.

### Who will benefit from it?

This is a widely used WebExtension API in many addons. Without this, even an image link cannot be downloaded due to CORS. Some usable existing addons become unavailable. Very sad to see it...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8793)

**Comment by cadeyrn** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1538348 and dependencies for the implementation of the downloads API in the new Firefox. It seems that they are actively working on it but I can't tell you _when_ you can expect the API in Firefox.

**Comment by kuanyui** [comment]
Got it, it's OK as long as the API would be deprecated. Looking forward its finishing!

**Comment by Smart123s** [comment]
Don't close this issue unless it's fixed. Please 🥺

**Comment by cpeterso** [comment]
Tracking in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1538348
