### ISSUE TITLE
Add a "Copy Link Text" button in link's long press menu

### ISSUE THREAD

**Issue by junjieyuan** [mozilla-mobile/fenix#16582]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
User can't select and copy link's text. If the user wants to copy the text of the link, he must long press the text around the link, then drag the handle to select the link, and then copy.
### How do you know that this problem exists today? Why is this important?
I recently migrated from Chrome to Firefox, and chrome provides this feature. It's very useful.
### Who will benefit from it?
All Firefox user.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8790)

**Comment by masayuki-nakano** [comment]
If all things around a link like top of the issue list of github, it almost impossible to select the link text from outside of the link because GV does not start to select content when I long-tap at blank area, e.g., right space of short line.

**Comment by rykardopedro** [comment]
is possible copy text link? in right click?

**Comment by abda11ah** [comment]
+1
This feature is also available on Vivaldi browser

**Comment by ganon69** [comment]
Has this issue been abandoned...?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809303

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
