### ISSUE TITLE
Restore fenix availability in the "Open With" menu

### ISSUE THREAD

**Issue by mrtootoo** [mozilla-mobile/fenix#16595]
Firefox was always listed in the Android "Open With" menu until recent versions.  This capability is very useful, especially when browsing files from a file manager.  Please restore the long standing capability of Firefox/Fenix availability in the "Open With" menu.

**Comment by kbrosnan** [comment]
Duplicate #7546

**Comment by mrtootoo** [comment]
> Duplicate #7546

I can see this issue being very similar to [3864](https://github.com/mozilla-mobile/fenix/issues/3864), but I don't see much of a similarity to [7546](https://github.com/mozilla-mobile/fenix/issues/) as there was no issue with v68.  Either way, hopefully the long standing capability of Fennec/Fenix availability in the "Open With" menu is restored.

**Comment by kbrosnan** [comment]
Open with is opening a local file saved on disk. This is a duplicate.
