### ISSUE TITLE
[Bug] Pull to refresh triggered on full screen videos

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#16603]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open a video in full screen on any website (for me it's YouTube) 
Swipe down to trigger pull to refresh
### Expected behavior
Pull to refresh not triggered while on full screen. 

### Actual behavior
It's triggered on full screen. 

![Screenshot_20201116-194646_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/99283933-b554fe00-2846-11eb-9f29-6bac24d16513.png)

### Device information

* Android device: Xperia XZ1 Android 10 
* Fenix version: Nightly

**Comment by Mugurell** [comment]
I think in this case the solution would be to just add another check for fullscreen media to the [canChildScrollUp](https://github.com/mozilla-mobile/android-components/blob/e7100fe9d010f703e7b986665aa4db3d472b8daf/components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt#L75) method as the `UNHANDLED` result from PZC is the correct one.

**Comment by hakkikaancaliskan** [comment]
@rocketsroger I've updated to 12/3 5:08AM Nightly but it's not working. Is this build include that patch? Can you confirm?

**Comment by hakkikaancaliskan** [comment]
@rocketsroger I've updated to 3/12 and its not working on youtube :(

**Comment by hakkikaancaliskan** [comment]
@Mugurell issue closed but not fixed

**Comment by Mugurell** [comment]
I can also reproduce it on the latest Nightly.

@rocketsroger Seems like that check for [HomeActivity.isImmersive](https://github.com/mozilla-mobile/fenix/blob/2cada405d81fe4831e866794c91e57fb088315ac/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L779) is not being done at the right time.
Maybe we could could have a check to enable/disable pull to refresh in the [fullscreenChanged](https://github.com/mozilla-mobile/fenix/blob/2cada405d81fe4831e866794c91e57fb088315ac/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L1173) method?

**Comment by hakkikaancaliskan** [comment]
?

**Comment by mawen7** [comment]
Can confirm the suggestion by @Mugurell works.
Can open a PR if you'd like @rocketsroger

**Comment by rocketsroger** [comment]
I can reproduce as well.  I think the reason that this sneaked passed my testing is that for some reason the first time pull to refresh is not disabled.  After the first pull to refresh this then works correctly.

**Comment by rocketsroger** [comment]
> Maybe we could could have a check to enable/disable pull to refresh in the [fullscreenChanged](https://github.com/mozilla-mobile/fenix/blob/2cada405d81fe4831e866794c91e57fb088315ac/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L1173) method?

I was hoping my solution is cleaner then keeping track in the `fullscreenChanged` method.  I'll do some more investigation to see if I can salvage the `isImmersive` check.  If not I think you're right that `fullscreenChanged` method is a good spot.  Thanks,

**Comment by rocketsroger** [comment]
> Can confirm the suggestion by @Mugurell works.
> Can open a PR if you'd like @rocketsroger

@mawen7 Thanks for offering your help.  But I think since this is my mistake I should clean it up 😜

**Comment by mawen7** [comment]
Sure I understand that completely :)
Allow me one small hint: Since you can now use `inFullScreen` you can drop the `isImmersive` check.

`IsImmersive` was always false for me so I actually had to drop it.

**Comment by rocketsroger** [comment]
> `IsImmersive` was always false for me so I actually had to drop it.

That's interesting.  For me `isImmersive` works except like it was mentioned the check was not called in fullscreen.  

> Allow me one small hint: Since you can now use `inFullScreen` you can drop the `isImmersive` check.
Yes, what I'm testing is to pass the `inFullscreen` into the check.  I agree that since we're using `fullscreenChanged` we don't need `isImmersive` anymore. Thanks
