### ISSUE TITLE
Keyboard overlaps bottom navigation bar

### ISSUE THREAD

**Issue by scjb** [mozilla-mobile/fenix#16610]
The android keyboard overlaps the bottom nav bar
![Screenshot_20201117-071204_Firefox](https://user-images.githubusercontent.com/11727884/99353144-3d1d2580-28a4-11eb-8a66-1420009be7b0.jpg)

**Comment by kbrosnan** [comment]
What version of Firefox, what device, what version of Android?

**Comment by scjb** [comment]
Firefox Android 83.1.0-rc.2 (via Google Play Store)
Android 8.0
Samsung Galaxy S7 edge
