### ISSUE TITLE
[Bug] Tapping on "View" after adding a new tab doesn't focus the updated collection

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#16629]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
## Prerequisites
Add 7-8 collections.

## Steps to reproduce
1. Open tabs tray and add a tab to collection 1.
2. Tap on "View" from the snackbar.

### Expected behavior
The collection 1/new tab added is focused.

### Actual behavior
The collection 1/new tab added is not focused.

### Device information
* Android device: Pixel 3 (Android 11)
* Fenix version: Nightly 11/18, RC 82.1.3.
 
![20201118_123958](https://user-images.githubusercontent.com/58466444/99520214-8308e500-299b-11eb-9723-cffb9a363b4c.gif)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201204 GV 85 from 12/4 with Pixel 2 (Android 9).
I will remove the qa:needed and close this issue.
