### ISSUE TITLE
[Bug]  Firefox shows blank screen when audio streaming, resuming from screen sleep

### ISSUE THREAD

**Issue by guillelebon** [mozilla-mobile/fenix#16636]
## Steps to reproduce

-- Streaming audio from web app
-- Put the phone screen to sleep.
-- Song track changes in the background, phones continues to play new song, as expected
-- Exit from screen sleep
-- **Firefox Android shows a blank page** (only way to exit blank screen is to pause playing from the notification panel)

Please see following video, it's difficult to explain otherwise.

[http://turbineinteractive.com/blankscreen_fenix.mp4] (http://turbineinteractive.com/blankscreen_fenix.mp4)

### Expected behavior

-- Streaming audio from web app
-- Put the screen to sleep
-- Song track changes in the background, phones continues to play new song, as expected
-- Exit from screen sleep
-- Firefox Android returns to web app and shows playlist from webapp

### Actual behavior

This is a new bug, it worked perfectly until Firefox Android 81, then it broke in the following Firefox versions

### Device information

* Android device: Nokia 7 Plus -- TA-1062, running Android 10, version 00WW_4_15D_SP05
* Fenix version: 82.1.3  (it used to fine fine until Fenix 81, it's been broken ever since.)

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1678104

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
