### ISSUE TITLE
AC work for: Fenix/Pocket integration

### ISSUE THREAD

**Issue by bifleming** [mozilla-mobile/fenix#16638]
Build the capability to fetch pocket stories in AC

**From related story:** 
Note:  This work will be done later, once we have UX resources available. 
As a user, I want to discover interesting content in the browser in a way that is not intrusive to my core browsing experience.
   
    [ ] User will see a pocket opt-in card on the homescreen and have the choice to enable pocket stories
    [ ] Users can dismiss the card and have it removed from homescreen
    [ ] If users enable the card, then they will see 3 top articles and 1 discover more card on their homescreen.
    [ ] Users will be able to turn off pocket stories after having enabled them
    [ ] Users will be able to enable pocket stories after having dismissed them

**Comment by gabrielluong** [comment]
Closing this since it's marked as done
