### ISSUE TITLE
[Bug] Incorrect values of document.hidden/document.visibilityState when page is loaded in background tab

### ISSUE THREAD

**Issue by jakub-g** [mozilla-mobile/fenix#16637]
## Steps to reproduce

1. Open https://jg-testpage.netlify.app/document.hidden/landing/
2. Long press the link on the page and open the link in the new tab.
3. Wait a few seconds. Switch to the newly opened tab

### Expected behavior

The logs until the time when the tab became active should be saying
```
document.hidden = true; document.visibilityState = hidden;
```

### Actual behavior

The logs are saying
```
document.hidden = false; document.visibilityState = visible;
```

In other words, *initial values* for visibility APIs are wrong *when page is loaded as background tab.* 

### Fix 

- The browser should detect that the page is initially invisible
- and raise `visibilitychange` once it becomes visible.

(The visibility APIs seem to work correctly when visible page gets changes to invisible (by switching tab) or by minimizing the browser.)

### Device information

* Android device: Huawei P20 lite, Android 9
* Fenix version: 82.1.3

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1678103

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
