### ISSUE TITLE
[webcontent] Issue with top address bar if address change

### ISSUE THREAD

**Issue by PeopleInside** [mozilla-mobile/fenix#16644]
## Site with issue and any steps to reproduce

https://discuss.flarum.org/d/25181-flarum-010-beta14-released

If the address bar in Firefox is customized to be showed on top and you scroll down community address posts, as every different message change the URL address in the browser bar, the bar is sometime showed while scrolling down and causing issues on scrolling... Is like the page move back of some row.

No issue in other browser or if the bar is set to default down.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No

### Device information

* Android device: ? Android 10 Poco X3 (Xiaomi)
* Fenix version: ? Nightly 201118 17:04 (Build #2015776395)
AC: 67.0.20201117165227, d5524f7a5
GV: 85.0a1-20201117094406
AS: 67.0.0

**Comment by sflorean** [comment]
@PeopleInside this is still reproducible for you? 
Tested on latest Nightly and couldn't reproduce the issue with Pixel 3 (Android 11) and Samsung Note 10 (Android 11). 
Do you have some extra steps? the page you find the issue will be helpful. Thank you!

**Comment by PeopleInside** [comment]
Hi @sflorean thank you for your message and intervention, as for your message I tested again and I can confirm this issue seems has been resolved.

I'm closing the issue, thank you!
