### ISSUE TITLE
[Bug] Can't download any PDF. (Works on Chrome)

### ISSUE THREAD

**Issue by ZagButNoZig** [mozilla-mobile/fenix#16649]
## Steps to reproduce
1. Pick any page with a pdf download: (https://arxiv.org/pdf/2004.15004)
2. Confirm the download
=> Now Firefox shows in the "Task bar" as downloading but nothing happens. 
### Expected behavior
It should download the file. Its not an internet problem as the file is almost imediatly downloaded on chrome. Even after minutes Firefox shows no progress.
### Actual behavior
Firefox gets stuck in this "downloading" task but nothing happens.
### Device information

* Android device: Samsung Galaxy S7
* Fenix version: 82.1.3 (Build #2015774643)

**Comment by Amejia481** [comment]
Duplicated of of https://github.com/mozilla-mobile/fenix/issues/15378

**Comment by kvahid** [comment]
I observed the same problem and think this is not a duplicate if #15378 . The problem here is with ".pdf download" behavior not the "simultaneous download" behavior. I think this issue should be opened.

**Comment by Amejia481** [comment]
> I observed the same problem and think this is not a duplicate if #15378 . The problem here is with ".pdf download" behavior not the "simultaneous download" behavior. I think this issue should be opened.

👋🏽 
Are you able to simulate on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)? If so could you share your devices specs, like phone manufacture and Android version.
