### ISSUE TITLE
File download failure.

### ISSUE THREAD

**Issue by SureshCBE** [mozilla-mobile/fenix#16643]
Hi,
When I am downloading documents (pdf,xl files,etc) firefox showing download notification but download not completed. After some time firefox showing download failed. I am facing this issue especialy while downloading documents like pdf,ms xl, ms word. But from other browser files are downloading.

**Comment by Amejia481** [comment]
Duplicated of #15378 see  https://github.com/mozilla-mobile/fenix/issues/15378#issuecomment-728145366

**Comment by SureshCBE** [comment]
Hi,
I am updated firefox to 83.1.0 and now files are downloading. Thanks for reply.

**Comment by Amejia481** [comment]
Thanks for keeping us up to date :)
