### ISSUE TITLE
Getting OOME while restoring sessions

### ISSUE THREAD

**Issue by zfrc** [mozilla-mobile/fenix#16645]
stacktrace:

Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 108986290 byte allocation with 8388608 free bytes and 100MB until OOM

java.lang.AbstractStringBuilder.enlargeBuffer (AbstractStringBuilder.java:95)
java.io.StringWriter.write (StringWriter.java:123)
kotlin.io.TextStreamsKt.copyTo (TextStreamsKt.java:125)
kotlin.io.TextStreamsKt.copyTo$default (TextStreamsKt.java:120)
kotlin.io.TextStreamsKt.readText (TextStreamsKt.java:107)
**mozilla.components.browser.session.ext.AtomicFileKt.readSnapshot** (AtomicFileKt.java:72)
**mozilla.components.browser.session.storage.SessionStorage.restore** (SessionStorage.java:40)
**org.mozilla.fenix.components.Core$sessionManager$2$$special$$inlined$also$lambda$1$1.invokeSuspend** (Core.java:162)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:56)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.java:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.java:738)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.java:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.java:665)

* Android device: various from 6 to 10
* Fenix version: 5.2(version 46 for AC)

**Comment by ekager** [comment]
Believe this is the same issue - may have been fixed in newer Fenix/AC versions https://github.com/mozilla-mobile/android-components/issues/3909
