### ISSUE TITLE
Audio device handling is poor with WebRTC

### ISSUE THREAD

**Issue by marc5000** [mozilla-mobile/fenix#16653]
I'm filing this as a bug, however there are some suggestions in here which may want to be considered as a feature. I'd be more than happy to file this in the features section if appropriate. 

The issues described below seem to span across many different types of Android devices, with varied results.

**Analogue audio devices:** 

Using a headset plugged into the built-in analogue audio jack (TRRS) works fine, no reported issues -- both the microphone input and headphone output work as expected. This seems to be system managed, and the device name remains the same when enumerating devices in WebRTC. 

The same goes when using the internal microphone and speaker (ie. no headset plugged in), audio works as expected and enumeration is correct.

Suggestion: 

For mobile devices, it would be better that when you raise the handset to your ear, that the loudspeaker turns off and audio is routed only through the 'ear speaker'. This will be more natural to the user who is trying to treat the WebRTC session as a traditional 'call'. It will also help stop unnecessary echo(!)

**USB and Bluetooth audio devices**

The experience with USB and Bluetooth devices is where things start to go a bit wrong. User experience is poor, and device selection does not yield the correct result.

Expected behavior:: When an external device (other than the system speaker/built in mic/audio jack) is selected, the audio should be routed accordingly. 

What went wrong:: When using an external USB or Bluetooth audio device, the input device may enumerate correctly, but upon selecting the device the audio still defaults to the internal microphone. This is confusing to a user who believes they have selected the right device -- but still their audio is being routed elsewhere.

The same goes for output device selection. You may be able to see the device enumerated in the list, but upon selecting the desired output, audio still defaults to the devices built in speaker or audio jack. 

You can test this using the WebRTC example page at: https://webrtc.github.io/samples/src/content/devices/input-output/

I recommend trying with both Bluetooth headsets (which have a microphone) and USB audio devices. 
A USB microphone with dedicated headphone output is ideal; a good microphone to test with is the ATR2100-USB. This should allow you to enumerate both an input and an output device to test with.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8831)

**Comment by MortimerGoro** [comment]
+1 for this one. Gecko for Android should implement audio input device selection. When using VR glasses the microphone from the phone is used instead of the one from the headset (external USB device). 

GeckoView should either redirect it or at least expose all the available options for input selection.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811585

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
