### ISSUE TITLE
[Bug] Grid View CFR Should Not Show If Already Using Grid View

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#16657]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Change tab settings to Grid View
2. Open 6 tabs

### Expected behavior
Shouldn't get recommendation for grid view

### Actual behavior
Get CFR for grid view

### Device information

* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Closing it in favour of #16735
