### ISSUE TITLE
Change the default layout of list-view tab tray in order to display more tabs (as before)

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#16654]
I put it as a bug as it is a regression pertaining to information density, following the reversal of tab order in the tab tray. But one may argue on that :)

Here is a set of screenshots that are mentioned below.

![image](https://user-images.githubusercontent.com/218971/99680054-ef0f4a00-2a7c-11eb-8c59-945911181768.png)

## Steps to reproduce
Install the latest nightly build
Make sure tab tray is in list view
Set address bar to bottom.
Open 9 new tabs
Click the tab counter icon to display the tab tray

### Expected behavior
(See BEFORE screenshot above)
The same amount of tabs should be displayed now as in the previous builds when tabs were ordered in the other way (newer tabs on top), 8 in the case of a Redmi Note 7.

### Actual behavior
(See NOW screenshot above)
Only 6 are displayed a Redmi Note 7, as a lot of useful space is lost above and below the tabs themselves

### Device information
* Android device: Redmi Note 7
* Fenix version: #2015776395 
 

I don't know what the final plans for the tab tray are (in bottom mode, will the tab tray "tabs" be moved to bottom, for instance?), but it is important to maximize the number of tabs displayed in the tab tray, imho.
At short term, here are 2 proposals to add one more tab in the visible list, ie a total of 7 for a Redmi Note 7, for instance; just by playing with the initial position of the list the first time the tab counter is pressed (by moving downwards or hiding the "Select tabs" by default).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8832)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812891

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
