### ISSUE TITLE
Integrate search engine picker into address bar

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#16659]
Related to #16658 

@violasong has outlined some improvements to our search dialog/address bar. See [Figma file](https://www.figma.com/file/Sxi1ztO52VJ4mRaCQilrAw/Fenix-address-bar-simplification?node-id=1%3A2) for the full designs.

## Acceptance criteria
Move the search engine selection from the "floating menu" above the search dialog into the search logo on the toolbar. 
* Clicking on the search logo (e.g. Google icon) should open the search engine selection (this should be the same functionality as exists now)
* There should be an arrow overlaid onto the logo to show users that it is clickable (see @jonalmeida for context/questions)
* The arrow overlay should follow the toolbar position when keyboard is minimized -- bottom toolbar has upward facing arrow, top toolbar has downward facing arrow
* The arrow should always face upwards when the keyboard is open

<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/99710809-a64c9680-2a66-11eb-96ea-4c93b8835ca9.png">

**Comment by abodea** [comment]
Removing the `needs:triage` as there is nothing to triage.

**Comment by violasong** [comment]
Nominating this bug and its [sibling bug](https://github.com/mozilla-mobile/fenix/issues/16658) for triage because I would love to see us regain those extra pixels :). It will really improve the look of the homescreen too.

**Comment by kbrosnan** [comment]
Going to tackle similar work in https://github.com/mozilla-mobile/fenix/issues/24297
