### ISSUE TITLE
Traducir páginas en Firefox con el traductor de Google.

### ISSUE THREAD

**Issue by jabiertxo** [mozilla-mobile/fenix#16655]
Hola:tengo instalados Firefox(con mi cuenta) y Nightly(sin cuenta), y al traducir una página en Firefox con el traductor de Google, la traducción me la devuelve a través de Nighty. ¿Es normal esto?¿Porque ocurre?. Gracias.

**Comment by amedyne** [comment]
Hi @jabiertxo ! Do you still have the same problem? Can you provide the following details?
- what Android device are you using?
- What version of Firefox and Firefox nightly do you have?
- What is your default browser?
- Please provide a link/url of the website where you encountered this problem.
