### ISSUE TITLE
Integrate QR scanner into address bar

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#16658]
Related to #16659

@violasong has outlined some improvements to our search dialog/address bar. See [Figma file](https://www.figma.com/file/Sxi1ztO52VJ4mRaCQilrAw/Fenix-address-bar-simplification?node-id=1%3A2) for the full designs.

## Acceptance criteria
Move the QR scanner from the "floating menu" above the search dialog into the toolbar itself
<img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/99709904-836db280-2a65-11eb-913b-4b105684daaf.png">

* Ensure that the QR scanner works as intended
* When the user starts typing, the icon should disappear (see figma designs)

**Comment by eliserichards** [comment]
Removing "won't-fix". This issue may still be valid.

**Comment by willfs84** [comment]
Yes especially important for people with smaller phones!

**Comment by willfs84** [comment]
Please do not close! That bar is wasting precious vertical space
