### ISSUE TITLE
"Find in this page" should be in the context menu for selected text 

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla-mobile/fenix#16666]
# What is the user problem or growth opportunity you want to see solved?

Cullently when you need to find text in the page, you need to:
1. Long tap and select text
2. Select "Copy"
3. Open Find bar from the 3 dots button
4. Long tap in the find bar to open context menu
5. Select "Paste"

Or, need to type text by your hand.

If the context menu has an item to open th find bar and setting the selected text, step 3 and later are not required.

### How do you know that this problem exists today? Why is this important?

When I do code review, reading code and reading log file on tryserver on my tablet, I do them not smoothly due to requiring the many steps.

### Who will benefit from it?

Advaced users who read code, log, etc.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8840)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807142

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
