### ISSUE TITLE
[Bug] Context menu position is wrong if Fenix is opend in split area

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla-mobile/fenix#16667]
## Steps to reproduce

1. Use split screen mode or popup mode of Galaxy
2. Open Fenix at non-top-left of the screen
3. Long-tap to select text

### Expected behavior

The context menu for selected text should be near the selected text.

### Actual behavior

The position is moved bottom-left than the expexted position in split screen mode.

In popup mode, it's more complicated. The position is seems right if Fenix is at near the top-left of the screen. However, moving to bottom left, the context menu becomes hidden. But moving to top-left, it's shown again.

### Device information

* Android device: Samsung Galaxy Tab S5e, Android 10, One UI 2.5
* Fenix version: Today's Nightly (Nightly 201119 17:01 (Build #2015776587), AC: 68.0.20201119143053, b7e6ad09e, GV: 85.0a1-20201118041908, AS: 67.0.0)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8841)

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1678531

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
This is a Fenix/AC issue

**Comment by SamuelMezger** [comment]
Still relevant.

**Comment by SamuelMezger** [comment]
Still relevant.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1678531
