### ISSUE TITLE
Javascript class fields

### ISSUE THREAD

**Issue by headbank** [mozilla-mobile/fenix#16677]
Per the developer docs I discovered that [public and static class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Browser_compatibility), supported in desktop Firefox for a few versions now, are not supported in Fenix.

I am keen to see this feature brought to Fenix for feature-parity with desktop, and I don't see anything regarding it either here or on Bugzilla (apologies if this should be posted over there, but as the feature is already implemented in Desktop, I assume here is the place to ask).

So, what's up with this? Is work underway, and if so what is its progress / where can I monitor this?

**Comment by evilpie** [comment]
The compatibility data is outdated. Firefox for Android supports the same JavaScript features as Desktop.
I opened https://github.com/mdn/browser-compat-data/issues/7430

**Comment by headbank** [comment]
That's great news, thank you.
