### ISSUE TITLE
[Bug] Dynamic manifest.json for SPA not recognized

### ISSUE THREAD

**Issue by kadet1090** [mozilla-mobile/fenix#16672]
For Single Page Applications sometimes there is need to create or exchange webmanifest on the fly, to for example accommodate for selected language or scope of application (in my case, there is single app with multiple providers and each provider should be independent PWA + PWA for selecting provider). One of the solutions is to replace `href` attribute to point towards proper manifest for context, but those changes are not detected. Unfortunately some state is determined from clientside and thus there is no possibility to generate proper links on server.

## Steps to reproduce
Demo is on https://alcoholic.kadet.net (don't judge on the subject ;). The minimal code (+service-worker) required to recreate:

```
<html>
    <head>
        <link rel="manifest" />
    </head>
   <body>
        <script>setTimeout(() => document.querySelector('link[rel="manifest"]').href = "/manifest.json", 30000);</script>
    </body>
</html>
```

### Expected behavior
Manifest should be correctly recognized and application should be treated as PWA - i.e. I should be able to install it based on provided manifest.

### Actual behavior
Manifest is not recognized, install option is not available.

### Device information

* Android device: Xiaomi Redmi note 8 pro, Android 10
* Fenix version: 83

## More info 
https://stackoverflow.com/questions/40900674/can-i-dynamically-modify-start-url-in-the-manifest-json-file
https://medium.com/@alshakero/how-to-setup-your-web-app-manifest-dynamically-using-javascript-f7fbee899a61
https://medium.com/@rajathans/dynamic-pwa-manifest-using-javascript-and-rest-api-a23d132de7d6

**Comment by kadet1090** [comment]
I've debugged it a little bit more and conclusions are:
 - manifest is correctly recognized and loaded if `href` on `<link />` is set soon enough (probably before onload event fires?) so doing: ```
document.querySelector('link[rel="manifest"]').href = "/manifest.json"
```
works fine and 
```
setTimeout(() => document.querySelector('link[rel="manifest"]').href = "/manifest.json", 30000);
```
does not work at all in Firefox (in chrome it's ok, install button appears after 30s).

**Comment by unrelentingtech** [comment]
This is still a problem unfortunately!
