### ISSUE TITLE
[Bug]Closing the last Private Tab VIA contextual menu doesn't display the confirmation snackbar

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16676]
## Prerequisites
Don't have any normal browsing open tabs
Switch to PB

## Steps to reproduce
1. Open a website in a new PB tab
2. While in page view long tap the tabs counter
3. Select "Close tab" from the context menu

### Expected behavior
The user should remain in PB (PB home screen)
The deletion confirmation snackbar along with the undo button should be displayed.

### Actual behavior
The deletion confirmation snackbar along with the undo button **isn't** be displayed.
The user is redirected to Normal browsing home screen
### Device information

* Android device: 
OnePlus A3 (Android 6.0.1)

* Fenix version: 
• Nightly 201119
• Beta 84.0.0-beta.1

### Notes
► Video
![20201120-135835](https://user-images.githubusercontent.com/51314259/99797904-c2206d00-2b38-11eb-8468-d6bd3e8acc21.gif)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 11/27 with Samsung Note10 (Android 10).
