### ISSUE TITLE
Intermittent UI test failure - org.mozilla.fenix.ui.BookmarksTest.openSelectionInPrivateTabTest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#16671]
### Firebase Test Run:
Flaky, failed 1/2 times: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5322991458179372259/executions/bs.83c36cdbce174ee/testcases/1/test-cases

### Stacktrace:
java.lang.NullPointerException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null 

### Build: 
Master Nov. 20th

**Comment by sv-ohorvath** [comment]
Failed on 12/16, 1 out of 2 tries: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6091183863740814060/executions/bs.de44ba83109e88e8/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
This, along with some other Bookmarks tests, failed after an AC upgrade and we haven't seen this failure since more than a month ago. Closing the issue and will reopen if it occurs again.
