### ISSUE TITLE
[Bug] Deleting an exception from ETP doesn't restore the cross-out shield

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#16670]
## Steps to reproduce 
1. Open any website.
2. Switch off the ETP toggle from the site security info panel.
3. In the same info panel, tap on Protection Settings -> ETP page -> Exceptions.
4. Remove the exception from the list.
5. Tap back until you reach the website from step 1, and observe the ETP shield.

### Expected behavior
The shield isn't crossed-out anymore. Tapping on it displays the security info panel with the active ETP toggle.

### Actual behavior
The shield is still crossed-out. BUT, tapping on it displays the security info panel with the active ETP toggle.
Refreshing the page resolves the issue.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 10)
* Fenix version:  11/18 Nightly, RC 83.1.0, and Beta 84.0.0-beta.1

<img src="https://user-images.githubusercontent.com/40694158/99774894-1286d300-2b17-11eb-9cff-94cd983e2e76.gif" width="300" height="550" />

**Comment by s-ankur** [comment]
Similar https://github.com/mozilla-mobile/fenix/issues/7929

**Comment by Amejia481** [comment]
@s-ankur and @softvision-miralobontiu are you able to reproduce consistently? I was trying with `Nightly 201130 17:01 (Build #2015778699)`  and I wasn't able to reproduce.

**Comment by softvision-miralobontiu** [comment]
@Amejia481 I was able to reproduce again today, on the 12/2 Nightly build, with Samsung Galaxy Tab S6 (Android 10).

**Comment by Amejia481** [comment]
Thanks, is it only reproducible consistently in this device or are there others? I was testing on a Pixel 3 with Android 11 and I had a hard time trying to reproduce, I was looking to see if there are any additional steps to reproduce or it's happening in certain devices.

**Comment by softvision-miralobontiu** [comment]
No, I am able to reproduce it also on HTC 10 (Android 8), and on Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by Amejia481** [comment]
Thanks for the info, I will try with Android 8 , 7 and 10. 
I changed to **S3** as the bug is not blocking any main functionality, only UI issue. and the shield icon will show the right status when the pages change or reloads.

**Comment by Amejia481** [comment]
Thanks for all the info, I was able to replicate. The issue will be fixed after this patch lands https://github.com/mozilla-mobile/android-components/pull/9110 and Fenix updates its ac version with the required changes on it.

**Comment by Amejia481** [comment]
I should be ready for QA review, I wasn't able to reproduce in nightly

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 12/10 Nightly build with Samsung Galaxy Tab S6 (Android 10), Google Pixel (Android 10), and OnePlus 5T (Android 9).
