### ISSUE TITLE
[Bug] Firefox forcing private mode home screen after opening link in private tab.

### ISSUE THREAD

**Issue by DatGrey** [mozilla-mobile/fenix#16688]
## Steps to reproduce
1. Set Firefox to "Open links in a private tab".
2. Close all tabs, have the normal (non-private) home screen active, switch to another app or put Firefox in background.
3. Open a link from another app, Firefox loads it in a new private tab.
4. Press the back button, closing the private tab and going back to the original app.
5. Open Firefox (from a homepage shortcut or from recent apps).

### Expected behavior
Firefox loads the normal home screen.

### Actual behavior
Firefox loads the private mode home screen.

### Device information
* Android device: Google Pixel 3a
* Fenix version: 83.0.0-beta.4

**Comment by anotherus3r** [comment]
Did you enable "Open links in a private tab" in Settings -> Private browsing?

**Comment by DatGrey** [comment]
Yes, it's the first point in my original post.

**Comment by anotherus3r** [comment]
> Yes, it's the first point in my original post.

Dumb of me, missed the first point. Firefox remembers the last mode you used (whether in the app itself or in a custom tab) and then opens the app in it the next time you open Firefox. If I remember correctly, this behaviour was at one point changed to always open in normal mode, but was changed back to the current behaviour.

**Comment by DatGrey** [comment]
Sorry for the late reply, and thanks for the insight. I still think the behaviour is inconsistent right now, because in the example I provided when the user explicitly uses Firefox (lauching and then closing the app, not just clicking on a link), the last mode used is normal mode and not private; yet the app reopens in private mode. 

The user never activated private mode voluntarily, he just openend a link; only the link should have been private (the option is called "Open links in a private tab", not "Switch to private mode when opening links"). Not sure if I'm explaining the reasoning correctly, if it isn't clear enough I can try again.
