### ISSUE TITLE
FNX-5169 ⁃ [Bug] Virtual keyboard doesn't close when backgrounding Fenix

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#1668]
## Steps to reproduce
* Click on URL bar
* Press Android Home button

### Expected behavior
* Virtual Keyboard disappears

### Actual behavior
* Virtual Keyboard is still visibile

### Device information
* Android device: Samsung S10e, S7
* Fenix version: Latest from playstore

See video: https://imgur.com/Gx5ITTM

**Comment by sblatz** [comment]
Will be fixed by #1659, this is a dup of #1632.
