### ISSUE TITLE
[Bug]"Share all tabs" missing from the PB Tabs Tray ⋮ overlay

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16680]
## Prerequisites
Have a couple of tabs opened in PB
Switch to PB

## Steps to reproduce
1. Open the Tabs Tray
2. Tap the ⋮ ("More options") button

### Expected behavior
The "Share all tabs" option should be available

### Actual behavior
The "Share all tabs" is missing from the overlay

### Device information

* Android device: 
• OnePlus A3 (Android 6.0.1)
•  Xiaomi Mi Pad 2 (Android 5.1)

* Fenix version: 
• Nightly 201120 
• Beta 84.0.0-beta.1

**Comment by ekager** [comment]
Thank you! This was an intentional change from https://github.com/mozilla-mobile/fenix/issues/16522#issue-741455078

**Comment by SL-Lee** [comment]
May I ask what is the motivation behind removing the "Share all tabs" option from the Private Browsing tab tray? In desktop, you can select all tabs in a private window and share them to other devices, so why should there *not* be an option to share all private tabs in Firefox for Android?
