### ISSUE TITLE
[Bug] Long collection names are truncated when expand the collection

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#16687]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Add a collection with a long name in order to be truncated when the collection is collapsed.
2. Tap on the extend button.

### Expected behavior
The name is fully displayed.

### Actual behavior
The name of the collection is still truncated.

### Device information
* Android device: all
* Fenix version: all

<img src="https://user-images.githubusercontent.com/58466444/99815263-bc378580-2b52-11eb-86d6-1f5cc4c04ab6.jpg" width="300" height="550" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8858)

**Comment by sflorean** [comment]
This is still reproducible on latest versions.

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible on the:
- latest Nightly 96.0a1 (2021-11-22).
- latest Beta (95.0.0 beta4).
- latest Release 94.1.2.
Device used: Xiaomi Mi11 Lite (Android 11).
