### ISSUE TITLE
PWA when opened has huge white bar on status bar

### ISSUE THREAD

**Issue by Blaze-Thunder** [mozilla-mobile/fenix#16686]
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open any website like news.google.com, 
Install it using the install option
Place the Progressive web app (PWA) on homescreen
Open the PWA
On top there is a huge white bar covering status bar. Nothing is visible

### Expected behavior
When opening a PWA there shouldn't be white bar but the status bar should mix with color

### Actual behavior
There is a huge white bar when opening pwa

### Device information
OnePlus 7 pro 

* Android device: yes
* Fenix version: Latest nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8857)

**Comment by Blaze-Thunder** [comment]
![Screenshot_20201120-085601](https://user-images.githubusercontent.com/64011423/99814035-725c9880-2b6e-11eb-9be7-cb74c0de3171.png)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible Firefox Preview Nighlty 201127 using a OnePlus6T (Android 9).

**Comment by mortyobnoxious** [comment]
Same here.
![Screenshot_2020-12-25-13-02-09-945_org mozilla firefox](https://user-images.githubusercontent.com/42044258/103131463-ef20ec00-46b1-11eb-883e-70ed6781706c.jpg)

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the 6/24 Nightly build with Google Pixel (Android 10).
@Blaze-Thunder could you retest?
Thank you!

**Comment by benyaminl** [comment]
@lobontiumira You could try on youtube.com

Try to set youtube.com to desktop on fenix, and install it as PWA app, and run the shortcut from the homescreen, and you could reproduce all the issue, it's tested on 10 devices with nightly 94, stable 92. 

Example : 
![image](https://user-images.githubusercontent.com/2817332/132990263-171b8c3d-bca0-432a-8c3c-54d6570c4e5f.png)
![image](https://user-images.githubusercontent.com/2817332/132990285-99c8ce7f-c950-4d95-a8dd-fb91b4879d62.png)

**Comment by Blaze-Thunder** [comment]
The bug is still happening on latest firefox Android beta 92 beta 8. I've installed Google news and attached screenshot. Please fix this.
![Screenshot_20210912-202205](https://user-images.githubusercontent.com/64011423/132992348-f5fff991-30f1-4340-9678-ba4c1aaa8fd2.jpg)

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1356784

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1356784

**Comment by Remu-rin** [comment]
Not resolved. Still reproducible with Google News when Android theme is set to dark. With light Android theme toolbar is ok.

**Comment by Blaze-Thunder** [comment]
Any planned fix for this? This has been open for a lot of time and no solution. PWA should work fine on par with Chrome.

**Comment by agis** [comment]
Still an issue

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807423

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
