### ISSUE TITLE
[Bug] [L10n] "Select tabs" from Tabs Tray is not translated in many languages

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#16684]
## Steps to reproduce
1. Open the Android "Language and Input" settings. Set the Language to Français.
2. Launch Fenix and visit a page;
3. Tap the tab counter button;
4. Observe the "Select tabs" translation from the Tabs Tray button and from the three dot menu from Tabs Tray;
### Expected behavior
The "Select tabs" is translated in both places.
### Actual behavior
The "Select tabs" is not translated in both places.

### Notes:
This is reproducible for: Francais, Indonesian, Italian, Russian, Hindi, Japanese, Arabic.

Not reproducible for Spanish, Portuguese.
### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8)
* Fenix version: Beta 84.0.0-beta.1 from 11/18, Nightly 11/20;
Not reproducible on Release 83.1.0 from 11/18

**Comment by ekager** [comment]
This was a new menu item added in https://github.com/mozilla-mobile/fenix/issues/16522 and we made a new string (best practice). We should get translations soon and we can either try to uplift into the release branch or uplift a change using the old button string

**Comment by abodea** [comment]
Verified as fixed on **Beta 85.0.0-beta.2** and latest **Nightly 18/12** with **Google Pixel 4 XL (11), Samsung Galaxy S10+ (10),** **Samsung Galaxy Tab S3 (Android 8).**
**Verified languages:** Francais, Indonesian, Italian, Russian, Hindi, Japanese, Arabic.
