### ISSUE TITLE
[Bug]New Tab FAB disappears after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16681]
## Steps to reproduce
1. Open 2 tabs
2. Tap the tabs counter and open the tabs tray
3. Rotate the device to landscape view
4. Rotate the device back to portrait view

### Expected behavior
The New Tab FAB should be available.

### Actual behavior
The New Tab FAB disappears.
After rotating back the device to portrait view, the Tabs Tray seems to be moving
Also, the "Select tabs" button disappears for a couple of seconds. 

### Device information

* Android device: 
OnePlus A3 (Android 6.0.1)

* Fenix version: 
• Nightly 201120
• Beta 84.0.0-beta.1

### Notes
**❗ Reproducible in both List view and Grid view**

► Video
![20201120-161102](https://user-images.githubusercontent.com/51314259/99810365-4af4d400-2b4c-11eb-92d1-6321e20af2ab.gif)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201214 05:03 (Build #2015781291) GV 85 from 12/14 with Samsung Galaxy Tab S3 (Android 8) and Pixel 2 (Android 9).
I will close the issue and remove the qa:needed label for now.
