### ISSUE TITLE
Create a Mergify workflow to aut-land A-C Update PRs

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#16690]
We have automation in the works that will generate pull requests to update A-C on the release branch when a new A-C release becomes available in Maven.

For example https://github.com/mozilla-mobile/fenix/pull/16665

Let's automate landing these with Mergify so that release branches are always up to date. This is a small piece in a much a much bigger automation effort that will get us to _hands-off releases_.

**Comment by pocmo** [comment]
I landed a config for auto-landing MickeyMoz / L10N / release automation PRs today:
https://github.com/mozilla-mobile/fenix/commit/302bd45f8f4146d9fd73658b22bf1a5e5d7c48e0

**Comment by st3fan** [comment]
Closing this issue because https://github.com/mozilla-mobile/fenix/commit/302bd45f8f4146d9fd73658b22bf1a5e5d7c48e0 landed.
