### ISSUE TITLE
Add `nimbus_url` secret to task cluster.

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/fenix#16691]
In order to land:

https://github.com/mozilla-mobile/fenix/pull/16682#issuecomment-731290165

Task cluster needs to add the Nimbus remote settings endpoint as a secret called `nimbus_url`.

Please could you add [this URL][1] as `nimbus_url` for all  builds that are sent to the Google Play Store (nightly, beta, release). For others this should be `null` or the empty string.

[1]: https://firefox.settings.services.mozilla.com/

**Comment by jhugman** [comment]
FAO: @mozilla-mobile/releng

**Comment by MihaiTabara** [comment]
@JohanLorenzo has added docs on this in [here](https://github.com/mozilla-mobile/shared-docs/pull/102). He's mentoring me later this afternoon in doing this, to unblock you. Sorry for the delays in replying to this.

**Comment by MihaiTabara** [comment]
This is now done, we've updated:
* https://firefox-ci-tc.services.mozilla.com/secrets/project%2Fmobile%2Ffenix%2Fbeta
* https://firefox-ci-tc.services.mozilla.com/secrets/project%2Fmobile%2Ffenix%2Fnightly
* https://firefox-ci-tc.services.mozilla.com/secrets/project%2Fmobile%2Ffenix%2Frelease

For this one I've added the empty string
* https://firefox-ci-tc.services.mozilla.com/secrets/project%2Fmobile%2Ffenix%2Fnightly-simulation

For the rest of the Fenix related secrets, I haven't touched them as they have a different structure and are not included in the APK.

Note to self: this is a measure of security to prevent forks to access the endpoint.
@JohanLorenzo ++ for mentoring me in taking care of this and for adding good docs on this!
