### ISSUE TITLE
[Bug] Pages don't load

### ISSUE THREAD

**Issue by SinTan1729** [mozilla-mobile/fenix#16699]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Reproducibility
Happens randomly

## Steps to reproduce
Search something

### Expected behavior
Should show search results

### Actual behavior
Nothing loads [(screen recording)](https://streamable.com/32psjx)

### Device information

* Android device: Redmi K20 (Android 10)
* Fenix version: Nightly 201120 17:01

**Comment by pocmo** [comment]
Is this something that broke recently for you?

In the video you seem to kill Firefox and on the next launch it worked. Is that right?

How often do you end up in this state? Does loading a URL work (when a search doesn't)?

**Comment by SinTan1729** [comment]
> Is this something that broke recently for you?
> 
> In the video you seem to kill Firefox and on the next launch it worked. Is that right?
> 
> How often do you end up in this state? Does loading a URL work (when a search doesn't)?

Yes it broke very recently. A week or so maybe.

Yes. Killing and relaunching works.

Almost 7-8 times a day. No, loading URL doesn't work.
