### ISSUE TITLE
Bring back Tabs on a Tablet. Ditch the Tab Tray

### ISSUE THREAD

**Issue by 2nyf** [mozilla-mobile/fenix#16693]
I want to switch between tabs with one touch on my tablet.
### What is the user problem or growth opportunity you want to see solved?
The 'Tab tray' requires a touch to open, and a second to select

### How do you know that this problem exists today? Why is this important?
This has only occurred after a recent update. I want to be able to see my open tabs all the time.

### Who will benefit from it?
All tablet users as a minimum.

**Comment by s-ankur** [comment]
Hi, I think this is a duplicate of https://github.com/mozilla-mobile/fenix/issues/2344

**Comment by anotherus3r** [comment]
Also see #14921

**Comment by ekager** [comment]
Closing for the issues linked
