### ISSUE TITLE
[Bug] security.enterprise_roots.enabled doesn't work if opening a page from command line

### ISSUE THREAD

**Issue by takahirox** [mozilla-mobile/fenix#16696]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Import a self-signed certificate to an Android device
2. Install Firefox Nightly from Google Play
3. Open `about:config` and set `security.enterprise_roots.enabled` true
4. Plug in the android device to laptop via USB
5. Run `adb -s serial_str shell am start -n org.mozilla.fenix/org.mozilla.gecko.BrowserApp -d "url" -a android.intent.action.VIEW` from the command line where "url" refers to the secure server which requires the self-signed certificate you imported at 1.
6. Confirm the page is not displayed due to untrusted site error

### Expected behavior

The page should be displayed because `security.enterprise_roots.enabled` is true and Firefox Nightly should refer to the android certification settings.

### Actual behavior

The page is not displayed because `security.enterprise_roots.enabled` doesn't seem to work.

### Device information

* Android device: Samsung S8+
* Fenix version: 201118 17:04 (Build #2015776395)
 
### Additional context

If I manually navigate to the URL (enter the URL in the URL bar and open) from the Android Firefox Nightly, the page is displayed without untrusted site error.

And I run the command after I open any https site (e.g. https://google.com), the page is displayed.

So this problem seems from race condition.

Discussion on Slack (For Mozilla internal).

https://mozilla.slack.com/archives/C4D3JFF26/p1605661007048800

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1680398

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
