### ISSUE TITLE
[Bug]enabling webrender software nighty crashes 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#16701]
enabling gfx.webrender.all to true
 gfx.webrender.software to true
nightly crashes. 
here s the soccorro 
https://crash-stats.mozilla.org/report/index/bp-1973ad52-568e-45fa-8ea6-5b3460201121

**Comment by LaurentiuApahideanSV** [comment]
Hello and thank you for the report. The issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/16503. I will set this issue as closed as it will be handled there.
