### ISSUE TITLE
Inconsistent page list expansion on new page and restore page

### ISSUE THREAD

**Issue by Kwasow** [mozilla-mobile/fenix#16705]
Hi,

Whenever you open a new page on Firefox Fenix (v83 stable) it appears on top of the list of all open tabs. However when you close a page from that view and then press "Undo" it will be added to the bottom of the list.

It's a minor inconsistency, but is an accessibility issue.

**Comment by ekager** [comment]
Closing as dupe of https://github.com/mozilla-mobile/fenix/issues/10986
