### ISSUE TITLE
Allow moving app to external sotrage (installLocation)

### ISSUE THREAD

**Issue by LukasGibeh** [mozilla-mobile/fenix#16703]
A lot of "old" smartphones just have a fairly low amount of internal storage (e.g. 16GB). Thanks to projects like LineageOS the use of these devices is still widespread. However, because of the modest amount of storage, users sometimes need to go without some good apps or migrate them to external storage.

In order to be able to do the latter, the `android:installLocation` entry in the Manifest [0] has to be set to `auto`.

Are there considerations against allowing the app to be stored externally?

[0] https://developer.android.com/guide/topics/manifest/manifest-element#install

**Comment by s-ankur** [comment]
Although this is not a resolution, LineageOs does allow to neglect manifest and install any app to storage from dev options 
![Screenshot_20201121-195330_Settings](https://user-images.githubusercontent.com/33252312/99879492-40e2dc00-2c05-11eb-94e1-567b8efd6646.png)

**Comment by hakkikaancaliskan** [comment]
Users will move fenix to SD card without knowing this process gonna slow down fenix really much. Fenix is a browser and it's frequent used. I think devs shouldn't allow this.
Lineageos users etc can already enable this in developer options.

**Comment by kbrosnan** [comment]
Moving the app can cause significant problems with Firefox for Android. This is not a supported configuration and we don't plan on making this work.

**Comment by Atreyu-94** [comment]
It is the only cause why I cannot use Firefox on Android. It consumes too much space in the internal storage and I cannot move it to the external one. It's sad that they don't plan to implement it. Cheers!
