### ISSUE TITLE
Add option in setting to specify the external download manager

### ISSUE THREAD

**Issue by stevenleeS0ht** [mozilla-mobile/fenix#16706]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Firefox can automatically use the download manager that user specified.

Currently, there is already a boolean checkbox about whether to user external download manager, what I hope that there is a option for which download manager to use.

### Who will benefit from it?

All the user who use external download manager?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8873)

**Comment by stevenleeS0ht** [comment]
@ekager , what is your opinion?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812801

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
