### ISSUE TITLE
[Bug] main menu should have scrollbar/scroll thumb when there's overflow

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#16717]
There's supposed to be a scrollbar/scroll thumb for the main menu when there is overflow, this is especially important for when the user is using their phone sideways or in split screen. Chrome's main menu already has a scroll thumb/scrollbar when there's overflow...

![Screenshot_20201122-192146](https://user-images.githubusercontent.com/47801466/99921564-268a2a80-2cf9-11eb-9d21-03f8230a106a.png)

**Comment by willfs84** [comment]
This still repros in Nightly, please do not close

**Comment by sflorean** [comment]
Confirming that the issue is still reproducible on latest versions of Fenix.
