### ISSUE TITLE
when choosing "Share image" command, it actually shares a link of the image

### ISSUE THREAD

**Issue by leontancfa** [mozilla-mobile/fenix#16710]
to reproduce:
1. on a image, long press the image
2. a menu shows up. the first button is "Share image". when you press it, and choose, for example, Whatsapp to share
3. then in WhatsApp, you will find that you share a link, not the image itself.

It's reported in other places but did not find it reported here.
https://www.reddit.com/r/firefox/comments/iw9wku/cant_share_images_firefox_android/

**Comment by cadeyrn** [comment]
Duplicate of #12414.

**Comment by kbrosnan** [comment]
Closing as a duplicate
