### ISSUE TITLE
[Bug] about:about needs some attention 

### ISSUE THREAD

**Issue by ChiefMikeK** [mozilla-mobile/fenix#16711]
## The link in screenshots seems ok 
 [mozilla-release: changeset 623459:55359edc5d1cb8addecf9d2e7151782da543f67b](https://hg.mozilla.org/releases/mozilla-release/rev/55359edc5d1cb8addecf9d2e7151782da543f67b) 
* but 
** build info needs to be fixed
** wrong logo
** about:config should not display as a internal link to an error page  

## Steps to produce 
- open about:about 
- click on displayed links 

### Expected behavior  
- current information is displayed  
- no error page is displayed  

### Actual behavior  
various information such   
1. build indicates Aurora fennic vice fenix reliese 83.1.0  
2. outdated logo  
3. some bad links  

### Device information  
* Android 10 aosp w/o Google play services 
* Android device: Huawei Matepad T8, Model=KOB2-L09 
* Fenix version: 83.1.0 release via alternative 💯non-GooglePlaystore repo  
---
# :neckbeard:  
![Screenshot_20201122_org mozilla firefox](https://user-images.githubusercontent.com/20070053/99907735-6a8d2780-2d19-11eb-8754-07f512c939be.png)

**Comment by kbrosnan** [comment]
This is multiple issues. The ones involving `about:buildconfig` or `about:logo` should be filed at https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView. `about:config` is not available on Firefox on Android release builds. You can use the Beta or Nightly builds if you need access to those prefs.
