### ISSUE TITLE
quick way to copy a suggested (previously visited) url

### ISSUE THREAD

**Issue by makoConstruct** [mozilla-mobile/fenix#16714]
### What is the user problem or growth opportunity you want to see solved?

Copying previously visited urls should be as easy as possible. The more convenient our tools make that very common task of recalling urls, the more there can be a culture of sharing articles instead of recapitulating old points, the better, the more informed the conversations we have, the quicker good information is able to spread.

Right now you'd need to load the url from your suggestions and then copy the url from the address bar, which is three clicks (load page, long press on url bar to open a menu thing, click copy url) and an unnecessary page load.

Long press to copy might be a good way to streamline this important task.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8880)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807065

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
