### ISSUE TITLE
Increase the touch target for 3 dot menu 

### ISSUE THREAD

**Issue by 0xTyagi** [mozilla-mobile/fenix#16719]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Could you increase the touch target of 3 dot menu button or either decrease the touch target of tab button. It is very difficult for accessing the 3 Dot menu on small screen device as many time tab button is clicked

### How do you know that this problem exists today? Why is this important?
Current version have this.

### Who will benefit from it?
Everyone but especially older people and people having heavy fingers.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8883)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809236

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
