### ISSUE TITLE
Add "Follow device theme" option to reading mode

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#16724]
Hi, I use Firefox 83.0.0-beta.4 on Android 9.0.
As you can see, there are three themes in reading mode: Dark, Sepia, Light
![Screenshot_2020-11-23-23-11-57-632_org mozilla firefox_beta](https://user-images.githubusercontent.com/23485114/100023655-9af8c280-2dfa-11eb-96ce-4e6ffae8ae65.jpg)
I need "Follow device" theme for reading mode. (like Opera)
Please watch below video:
https://youtu.be/T6uUyNTyMgA
Thanks.

**Comment by B0pol** [comment]
But what should be selected when system theme is white? I use sepia / dark in reader view, therefore I'd like follow device theme to use sepia / dark for reader view.

**Comment by DiegoARL38** [comment]
See also  #3289

**Comment by csadilek** [comment]
Thanks for filing! Duping to #3289.
