### ISSUE TITLE
FNX-5173 ⁃ Quick actions handle should not be accessible to TalkBack when find in page is visible

### ISSUE THREAD

**Issue by eeejay** [mozilla-mobile/fenix#1672]
It seems like for non-TalkBack users the quick actions sheet is not available when the find in page bar is visible. If this is the case, neither should the quick sheets button be available to TalkBack users.

**Comment by topotropic** [comment]
The quick action bar is available when "Find in page" is visible so it's alright to have it available for TalkBack as well. Please verify and feel free to close the issue. Thanks!

**Comment by lime124** [comment]
please re-ping if there is something further we need to do.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #190724 from 24/7** using the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

►Video from Huawei Mate 20 Lite
![20190724_152508](https://user-images.githubusercontent.com/51314259/61793587-27baf700-ae28-11e9-87bf-54d9fee59b14.gif)
