### ISSUE TITLE
[Bug] Facing UI glitch in Search Suggestions

### ISSUE THREAD

**Issue by ASparkOfFire** [mozilla-mobile/fenix#16723]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Search anything using address bar (happens randomly tho)

See : https://youtu.be/AMVVWVXlqGY

### Device information

* Android device: 10
* Fenix version: 83.1.0

**Comment by sflorean** [comment]
Tested on latest Fenix versions and couldn't reproduce the issue with Pixel 3 (Android 12).
@ASparkOfFire is still reproducible on your device?
