### ISSUE TITLE
[Bug] Keyboard is triggered when changing the theme or the position of the toolbar on onboarding

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16726]
## Steps to reproduce 
1. Open Firefox Nightly with a clean profile.
2. Scroll to the "Choose your theme card".
3. Change the theme.
4. Scroll further, and change the position of the toolbar.

### Expected behavior
The theme is changed without issues. The position of the toolbar can be changed without issues.

### Actual behavior
The keyboard is triggered when changing the theme, or when the position of the toolbar is changed.
The keyboard isn't triggered when changing the ETP.

### Device information
* Android device: HTC 10 (Android 8)
* Fenix version: 11/24 Nightly
* Not reproducible on RC 83.1.0, nor on Beta 84.0.0-beta.2
* Not reproducible on Samsung Galaxy Tab S6 (Android 10)

<img src="https://user-images.githubusercontent.com/40694158/100070130-3b260a00-2e42-11eb-8060-b30e6ec33cb3.gif" width="300" height="550" />

**Comment by Cheap-Skate** [comment]
Maybe same as #16668??

**Comment by Cheap-Skate** [comment]
Are you using gboard? It might not happen with other keyboards, see #16668.

**Comment by softvision-miralobontiu** [comment]
@Cheap-Skate it isn't reproducible on RC 83.1.0, nor on Beta 84.0.0-beta.2 with the same Gboard. Only on Nightly.

**Comment by selimsumlu** [comment]
I can reproduce this with both SwiftKey and Gboard on Nightly.

Device: realme 6 (Android 10)

**Comment by lobontiumira** [comment]
Closing this as I cannot reproduce it on the 5/26 Nightly build with HTC 10 (Android 8).
