### ISSUE TITLE
[Bug] scroll-behavior: smooth not working

### ISSUE THREAD

**Issue by artonge** [mozilla-mobile/fenix#16731]
# Steps to reproduce

- Open Firefox on an Android device
- Go to https://flap.cloud
- Click on "En savoir plus"

### Expected behavior

Firefox should scroll smoothly to the anchor, like on Firefox desktop.

### Actual behavior

Firefox scroll a first time not smoothly to a position above the anchor.
On a second click, Firefox will scroll smoothly to the anchor as expected.

### Device information

* Android device: OnePlus 5 on LineageOS 17.1
* Fenix version: Firefox Mobile 82.1.3

**Comment by mstange** [comment]
It scrolls smoothly for me even on the first click. I've tested both Release 83.1.0 and Nightly 85.0a1.
Maybe it's a performance issue - Firefox could be trying to scroll smoothly, but, due to a slow composite, there could be a jump in the actual animation.

**Comment by yoasif** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1680107

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
