### ISSUE TITLE
`onTrimMemory` can try to _start_ Gecko when it isn't running

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/fenix#1673]
## Steps to reproduce
Have a very underpowered Android device.  Start Fenix with Intent arguments using the `BrowserPerformanceTestActivity`, and witness the arguments being ignored.  Be confused.  Dig in with a patch and witness a stack trace like this:

```
I/XXX     ( 1543): Gecko says the profile directory is: /data/data/org.mozilla.fenix.debug.raptor/files/mozilla/yil83l0n.default
I/XXX     ( 1543): java.lang.RuntimeException
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core$runtime$2.invoke(Core.kt:54)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core$runtime$2.invoke(Core.kt:39)
I/XXX     ( 1543):  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core.getRuntime(Core.kt)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core.access$getRuntime$p(Core.kt:39)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core$engine$2.invoke(Core.kt:74)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core$engine$2.invoke(Core.kt:39)
I/XXX     ( 1543):  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core.getEngine(Core.kt)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core$sessionManager$2.invoke(Core.kt:96)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core$sessionManager$2.invoke(Core.kt:39)
I/XXX     ( 1543):  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
I/XXX     ( 1543):  at org.mozilla.fenix.components.Core.getSessionManager(Core.kt)
I/XXX     ( 1543):  at org.mozilla.fenix.FenixApplication.onTrimMemory(FenixApplication.kt:177)
I/XXX     ( 1543):  at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4251)
I/XXX     ( 1543):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)
I/XXX     ( 1543):  at android.os.Handler.dispatchMessage(Handler.java:102)
I/XXX     ( 1543):  at android.os.Looper.loop(Looper.java:135)
I/XXX     ( 1543):  at android.app.ActivityThread.main(ActivityThread.java:5254)
I/XXX     ( 1543):  at java.lang.reflect.Method.invoke(Native Method)
I/XXX     ( 1543):  at java.lang.reflect.Method.invoke(Method.java:372)
I/XXX     ( 1543):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
I/XXX     ( 1543):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

### Expected behavior
`onTrimMemory` does nothing if Gecko is not already running.

### Actual behavior
`onTrimMemory` is trying to _start_ Gecko in order to trim memory, which is clearly wrong.  As a side effect, it means that Gecko starts with a default profile, 'cuz the `onTrimMemory` call is invoked _before_ the Intent that handles the Intent extras gets to process them.

### Device information
* Android device: a very underpowered capture board.
* Fenix version: greenfield Nightly from a few days ago.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8889)

**Comment by sblatz** [comment]
@ncalexan are you seeing this? This sounds like an AC issue 🤔

**Comment by ncalexan** [comment]
> @ncalexan are you seeing this? This sounds like an AC issue 🤔

It is not an a-c issue, at least not directly.  Observe: [Fenix's `onTrimMemory`](https://searchfox.org/mozilla-mobile/rev/8cfed98308f3b329f31053279be1aa2bb7746b5f/fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#201-206) will _start_ Gecko (if it's not already running) in order to ask the `sessionManager` to save memory.  That's all kinds of wrong.

**Comment by liuche** [comment]
Timebox this to E3 and see where that gets us.

**Comment by mcomella** [comment]
Will wonders if this can still happen: since this issue was filed, we made a change such that Gecko will run before anything else runs as part of the Application (i.e. it's always started). Marc brought up the case that if the Application remains after a Gecko crash (can that happen?), this may be possible.

**Comment by mcomella** [comment]
I want to keep this on file just in case it's true.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807265

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
