### ISSUE TITLE
Show Firefox menu on start page

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#16733]
## Steps to reproduce
- Long press back button

### Expected behavior
If you long press the back button, bring up your tab history.
But if you long press the back button on new tab (or start page), nothing happens. 
In this case I want to see the Firefox menu.
![Screenshot_2020-11-25-00-59-11-653_org mozilla firefox_beta](https://user-images.githubusercontent.com/23485114/100160698-52f2a200-2ec5-11eb-8fe8-bd47dd546c1d.jpg)

### Device information
* Android device: 9
* Fenix version: 83.0.0-beta.4

**Comment by kbrosnan** [comment]
The homescreen is not a tab so it has no history. This is expected behavior.
