### ISSUE TITLE
[Bug]Failed to enable ESNI

### ISSUE THREAD

**Issue by waddt123** [mozilla-mobile/fenix#16749]
## Steps to reproduce
*Fenix version: 20201120
about:config
network.trr.mode 3
network.trr.uri https://1.1.1.1/dns-query
network.trr.bootstrapAddress 1.1.1.1
network.security.esni.enabled true
Open
https://www.cloudflare.com/zh-cn/ssl/encrypted-sni/
Encrypted SNI is OK
### Expected behavior
Turn on ESNI
### Actual behavior
upgrade：
*Fenix version: 20201121/20201123/20201125
Encrypted SNI is bad
### Device information
* Android device: Android 8.0

**Comment by cadeyrn** [comment]
Duplicate of #15858, closed for https://bugzilla.mozilla.org/show_bug.cgi?id=1500289.

**Comment by kbrosnan** [comment]
Closing as a duplicate

**Comment by shapor** [comment]
I don't believe this is the same bug.  ESNI used to work in FF nightly and recently stopped.  It doesn't work even with DoH (per OP and my testing).
