### ISSUE TITLE
In configration - delete browser data when finished, menu is partly overwritten

### ISSUE THREAD

**Issue by paulle** [mozilla-mobile/fenix#16745]
In configration - delete browser data when finished, menu is partly overwritten
## Steps to reproduce

see screenshot

* Android device: sony xperia 5; android 10
* Fenix version: 82.1.3
 
![Screenshot_20201125-193221](https://user-images.githubusercontent.com/4852079/100269243-87626e80-2f56-11eb-8c2e-22439e5214d5.png)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 11/27 with Pixel 3 (Android 11).
