### ISSUE TITLE
Content not loaded when page loads a document with target="_blank"

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#16748]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. open https://bbs.kafan.cn/forum.php?mobile=no

2. type something in the search box, then press the enter key on the keyboard, not a button on the web page, it will pop up a blank page
![IMG_20201126_140327](https://user-images.githubusercontent.com/3154109/100314106-e1b00d80-2ff0-11eb-9021-cef23366daf6.jpg)

3. the first page died

### Device information

* Android device: ?
* Fenix version: ?
 Nightly 201123 17:01 (Build #2015777355)
AC: 68.0.20201122190139, 52be4ca37
GV: 85.0a1-20201122093438
AS: 67.0.0

**Comment by lindongbin** [comment]
#16148

**Comment by ebalazs-sv** [comment]
I can reproduce this issue on the latest Nightly 11/26 with Pixel 2 (Android 9).

### Steps to reproduce
1. Launch Fenix;
2. Go to  https://bbs.kafan.cn/forum.php?mobile=no;
3. In the search box type something (i.e ne);
4. Tap the Go button from keyboard;
5. Observe the behavior;

### Expected result
The page is loaded with the search result.

### Actual result
The about:blank page is displayed. Tapping the back device button the page is frozen.
When trying to revisit the page, this will not load. The page can be visited again after a clear data.

### Video
![20201126_161639](https://user-images.githubusercontent.com/48799384/100361530-eda4cb00-3002-11eb-84ef-194c5e814098.gif)

**Comment by MicroBeast** [comment]
Same behaviour on https://www.excite.com/.

1. Type your query in search box.
2. Press Enter on your keyboard. If you press the search button there, then the service work.

New page with about:blank opened. All Tabs will freezed; nothing work, not even refresh, until I Force Close or Kill Forefox.

**Comment by kbrosnan** [comment]
Can reproduce with a current Geckoview Example both pages are using event handlers and adding `target="_blank"`

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1684967

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
