### ISSUE TITLE
[Bug] Ruffle Web Demo failed to load SWF animation

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#16755]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
Ruffle is an online emulator runs SWF via WebAssembly, it’s similar to your Shumway project.

## Steps to reproduce
1. Open https://ruffle.rs/demo/
2. Switch any of animations

### Expected behavior
Ruffle Web Demo should load and run SWF animation.

### Actual behavior
No one works, just see the black area on canvas.

### Device information

* Android device: Android 7.0, Galaxy S6
* Fenix version: 83.1.0

**Comment by LaurentiuApahideanSV** [comment]
I was able to reproduce the issue on Firefox 83.1.0 RC but not on the latest Nighlty 201126. @KrasnayaPloshchad Could you please download the latest Firefox Nighlty and see if the issue still occurs?

**Comment by KrasnayaPloshchad** [comment]
It’s now works for me on both stable and nightly builds, just have to waiting for very long time.
