### ISSUE TITLE
[Bug] m.proctorcam.com does not proceed past ID verification part

### ISSUE THREAD

**Issue by jcosentino** [mozilla-mobile/fenix#16750]
Go to: https://m.proctorcam.com/
When you need to check into an exam (for eg, AWS exam), you will need to take photos of your ID and upload it to verify your identity.

After uploading a photo, the screen shows a spinning circle that it is loading, but it never gets past this stage.

* Android device: Google Pixel 3, Android 11
* Fenix version: 83.1.0

**Comment by kbrosnan** [comment]
We don't have any way to interact or debug that page. Unfortunately that makes this unactionable.  You might try filling this as a webcompat issue at https://webcompat.com
