### ISSUE TITLE
[Bug] reader view doesn't show author

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#16769]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open reader view on desktop. It may detect an author. E.g. on this article it does: https://www.theguardian.com/technology/2019/nov/17/firefox-mozilla-fights-back-against-google-chrome-dominance-privacy-fears
2. Open the same article where author is detected on desktop, this time on mobile.
### Expected behavior
We see the author name below title
![image](https://user-images.githubusercontent.com/58657617/100540173-e3214600-323b-11eb-92e7-3aac768039cf.png)

### Actual behavior
No author name
![image](https://user-images.githubusercontent.com/58657617/100540202-2a0f3b80-323c-11eb-8dc1-c01f0fd98163.png)

### Device information

* Android device: Pocophone F1, Android 9
* Fenix version: Nightly 20201129

**Comment by kbrosnan** [comment]
I expect we need to update the [readabilty JS](https://github.com/mozilla/readability) files on Android Components. I filed a bug linked above to do this.

**Comment by kbrosnan** [comment]
We took the update and this still does not appear so it probably means we are not handling it. So we would need to change the reader code on the A-C side.

**Comment by csadilek** [comment]
Just ran into the cause for this. Assigning myself to put up a fix.

**Comment by csadilek** [comment]
OK, this works now in latest Nightly (210312 17:02). So we should be showing the author/byline for the same pages as desktop.

**Comment by B0pol** [comment]
I can confirm it's fixed

**Comment by lobontiumira** [comment]
Verified as fixed on the 3/15 Nightly build with Google Pixel (Android 10).
