### ISSUE TITLE
[Bug] Browser stuck in landscape / fullscreen mode after being sent to the background

### ISSUE THREAD

**Issue by ZagButNoZig** [mozilla-mobile/fenix#16762]
Filing this issue again because its broken again.

## Steps to reproduce
1. Watch a youtube video
2. Switch to landscape mode
3. Either put your phone on stand by or close firefox
### Expected behavior
When you try to rotate firefox back to vertical mode it should rotate back.
### Actual behavior
You need to manually close firefox in the "task view" to be able to rotate the view back. Even on other tabs it is stuck in landscape mode.
### Device information

* Android device: Samsung Galaxy S7
* Fenix version: 83.1.0 (Build #2015776403)

**Comment by s-ankur** [comment]
Duplicate of #14284

**Comment by ebalazs-sv** [comment]
I will close this issue, since is a duplicate of 14284, that is verified as fixed.

**Comment by ZagButNoZig** [comment]
@ebalazs-sv the issue is still present in 81.1.4
