### ISSUE TITLE
Google review link not working only in Firefox android versions 

### ISSUE THREAD

**Issue by dev-arjunan** [mozilla-mobile/fenix#16767]
[comment]: 

We are providing a link to Google reviews in our webpage. When users tap on it, it will redirect to google sign-in page. On successful authentication, webpage will show a popup where users can rate/review it.
Users are able to give comments in Firefox browser in desktop site, chrome browser, chrome android browser without any issues. Problem is with Android mobile browser. It shows 404 page :(
## Steps to reproduce
Please try to visit the link in Firefox android browser and chrome android browser to understand the issue.

Direct URL: https://search.google.com/local/writereview?placeid=ChIJj61dQgK6j4AR4GeTYWZsKWw
Note: Direct url of google review page. This is not working when you open it in Firefox android browser but the same works fine in all other browsers without any issues.

### Expected behavior
It should redirect and show a popup and let users to give reviews.

### Actual behavior
Shows 404 error. Issue occurs only in Firefox android browser but actually works in Firefox desktop app and choose "Request desktop site" in Firefox android browser.

### Device information
Browser / Version: Firefox Android Browser
Operating System: Android

Android device: Redmi Note 6 Pro
Fenix version: All andorid versions

![92399276-aca9c280-f147-11ea-97d0-0c54fe2f5e86](https://user-images.githubusercontent.com/50161510/100529036-126a8f80-3209-11eb-817a-64cdef8d8c2e.png)

**Comment by sflorean** [comment]
I was able to reproduce this on latest Nightly with Pixel 3 (Android 11).

**Comment by kbrosnan** [comment]
This seems like a Google bug. Reproduces on desktop using a mobile Firefox for Android user agent.

**Comment by alex-kowalczyk** [comment]
This issue does still exist and affects Firefox Mobile users receiving review invitations.
Is there any open issue in Google to track that? 
Alternatively Firefox could "spoof" user agent for this well-known URL.

**Comment by S7efan7** [comment]
This issue (exactly as originaly described) is still a thing and quite critical to smaller businesses loosing valuable reviews!
Any news about this (or any viable workaround)?
