### ISSUE TITLE
FNX-5176 ⁃ Remove "Mozilla location service" from Settings > Data choices

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1676]
The Mozilla location service (MLS) is Fennec's Wi-Fi location "stumbler" service. The feature should be integrated into Fenix after MVP (#1253), but until then this Mozilla location service setting makes to sense and should be removed.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest version of Fenix 1.0.1916 (Build#11080612), with Samsung Galaxy Tab S3 (Android 8.0), HTC Desire 820 (Android 6.0.1), and Samsung Galaxy S8 (Android 9.0).
