### ISSUE TITLE
[Bug] Click responsive behaviour working 1/10 times on any webpage 

### ISSUE THREAD

**Issue by AitorGallardo** [mozilla-mobile/fenix#16776]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open any webpage
2. Single click on any interactive element on the webpage

### Expected behavior

Click working every time.

### Actual behavior

When you click any element (e.g., input,button,link) it doesnt perform its intended action at first. The actual ratio (click -> intended action) is 1/10 | 2/8 aprox.

### Device information

* Android device: One Plus 6 A6000
* OS: Android 10 | OxygenOS 10.3.6
* Fenix version:  Firefox Daylight | 83.1.0 (Build #2015776403)

**Comment by sflorean** [comment]
@AitorGallardo I was not able to reproduce this issue on latest Nightly version with Pixel 3 (Android 12).
Can you check again?
Also, it will be helpful to know the URL/page you visited.
