### ISSUE TITLE
[Bug] Reddit multi-image posts render at too-large size when expanded

### ISSUE THREAD

**Issue by JPLeBreton** [mozilla-mobile/fenix#16779]
## Steps to reproduce
1. Open this link in latest Firefox Mobile: https://www.reddit.com/r/NoMansSkyTheGame/search?q=pyramid%20build&restrict_sr=1
2. Tap the thumbnail on the first post listed, "**Pyramid build, somewhat inspired by destiny**"
3. Observe: the thumbnail displays below the post title at a hugely blown up size.
4. Open the same link in latest Chrome for Android and tap the same thumbnail.
5. Observe: the thumbnail displays below the post title at a legible size.

### Expected behavior
Firefox Mobile should render the expanded image at a legible size, the way Chrome does.

### Actual behavior
Firefox Mobile renders the expanded image at an illegibly huge size that requires a lot of scrolling to reach the bottom of.

### Device information
* Android device: OnePlus A6000
* Fenix version: 83.1.0

**Comment by kbrosnan** [comment]
Reproduces on desktop in responsive design mode. Possibly a website bug.

**Comment by kbrosnan** [comment]
@emilio would you know what happens spec wise when a large image is constrained by h100% w100% in CSS grid?

**Comment by emilio** [comment]
@kbrosnan depends on various bits. Is there a test-case I could look at? @matspalmgren might know better off the top of his head :)
