### ISSUE TITLE
Open top site in background tab

### ISSUE THREAD

**Issue by gwarser** [mozilla-mobile/fenix#16771]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Long press on top site in home page in attempt to open it in new tab

### Expected behavior

There will be a menu entry on top for this

### Actual behavior

There is "Open in private tab" which I mistakenly clicked few times already.

### Device information

* Android device: custom Android 7.1.2 (LineageOS)
* Fenix version: Nightly 201128

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8916)

**Comment by s-ankur** [comment]
Hi, doesn't clicking on a top site *always*  open it in new tab? It never opens in current tab afiak

**Comment by gwarser** [comment]
I want to stay on home page to open few more links.

**Comment by s-ankur** [comment]
Oh understood. Perhaps you could phrase it as "open in background tab" instead?

**Comment by gwarser** [comment]
I copied the phrase from link context menu. Why this one entry should be different?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814116

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
