### ISSUE TITLE
[Bug] Firefox doesn't response from intent category CATEGORY_APP_BROWSER

### ISSUE THREAD

**Issue by ilPikachu** [mozilla-mobile/fenix#16780]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
In certain situations, developers need to send an intent to be opened in browsers only instead of using `ACTION_VIEW`. This is done by using `CATEGORY_APP_BROWSER` [(API Doc)](https://developer.android.com/reference/android/content/Intent#CATEGORY_APP_BROWSER) with `makeMainSelectorActivity ` [(API Doc)](https://developer.android.com/reference/android/content/Intent#makeMainSelectorActivity(java.lang.String,%20java.lang.String)) 

**Currently, Chrome, Opera, Edge, and Brave handle this category.**

This can be reproduced using the code blow:
``` kotlin
fun startBrowserIntent(uri: Uri) {
        val intent = Intent.makeMainSelectorActivity(Intent.ACTION_MAIN, Intent.CATEGORY_APP_BROWSER)
        intent.data = uri

        startActivity(intent)
}
```
### Expected behavior
After sending the intent, we should expect firefox to be in the list of Browser that handles `CATEGORY_APP_BROWSER`, but it does not. 
<img height="400" alt="test" src="https://user-images.githubusercontent.com/25991364/100636233-7c656080-32ff-11eb-9d70-8fa230a64d71.png">
<img height="400" alt="test" src="https://user-images.githubusercontent.com/25991364/100635943-24c6f500-32ff-11eb-9e2d-631f37fdc367.gif">

### Actual behavior
<img height="400" alt="Screen Shot 2020-11-30 at 1 54 40 AM" src="https://user-images.githubusercontent.com/25991364/100636637-ec73e680-32ff-11eb-8134-91a52e7de7fd.png">
### Device information

* Android device: Pixel 2 XL
* Fenix version: Firefox version 83.1.0

**Comment by ilPikachu** [comment]
https://github.com/mozilla-mobile/android-components/issues/9805

**Comment by Mugurell** [comment]
This was verified as fixed in https://github.com/mozilla-mobile/fenix/issues/17963.
Closing.
