### ISSUE TITLE
Support for Chrome Devtools Protocol (CDP)

### ISSUE THREAD

**Issue by Niek** [mozilla-mobile/fenix#16782]
### What is the user problem or growth opportunity you want to see solved?
Firefox Desktop ships with [CDP](https://firefox-source-docs.mozilla.org/remote/) in nightly builds (enabled build-time with the `--enable-cdp` flag) since some time now. This is great because it allows Firefox to be controlled with browser automation frameworks like e.g. Puppeteer. It would be great if the CDP support would land in Fenix as well, so we can use Android devices for browser automation.

### Who will benefit from it?
Everyone involved in browser automation. Users that have built their software on the CDP stack.

**Comment by agi** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1679876

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
