### ISSUE TITLE
Untie Clearing Site Data With Clearing Browsing History

### ISSUE THREAD

**Issue by vivazkote** [mozilla-mobile/fenix#16798]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Problem with ''Deleteing Browsing  Data''.
Site keeps me logged in. While I multiple times cleared browsing data, except history. Can it be some Firefox fingertip? 
This not happens with other browser(Opera)
### Expected behavior
should be new session.
### Actual behavior
again logged in.
### Device information
* Android device: Android 8.0
* Fenix version: 83.1.0 (Build #2015776403)
AC: 63.0.9, fc54c566e
GV: 83.0-20201112153044
AS: 63.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8931)

**Comment by s-ankur** [comment]
Able to reproduce in latest nightly with GitHub.com

**Comment by rocketsroger** [comment]
Can't reproduce.  Both delete browsing data (with or without checking `browsing history and site data`) on Github and Gmail sees the account signed out.

**Comment by rocketsroger** [comment]
@vivazkote and @s-ankur  can you please help confirm on Nightly?

**Comment by sflorean** [comment]
I wasn't able to reproduce this if all items under "Delete browsing data" are checked. If "Open tabs" are not deleted, I can browse on Twitter, 5-6 seconds until "something went wrong. Try again" message is displayed. If I reload the open tab, then I am logged out.

**Comment by vivazkote** [comment]
This happens with some site, not with all.
Probably, that site keeps user data in site settings? Which is not in mobile ffox menu.

**Comment by rocketsroger** [comment]
@vivazkote can you please give us an example site? This issue was originally reproducible with Github but not anymore.  It will be much easier to debug if we have a site that keeps the user signed in after deleting `browsing history and site data`.  Thanks

**Comment by vivazkote** [comment]
mymarket.ge

**Comment by rocketsroger** [comment]
> mymarket.ge
> remember, I am not clearing History, which is tied with site data. I think, they should be untied as in desktop firefox.

@vivazkote  To confirm, if you clear `Browsing history and site data` then you will be logged out of mymarket.ge?

**Comment by vivazkote** [comment]
Yes.
But it is ridiculous to clear History, is not it?!

**Comment by rocketsroger** [comment]
> Yes.
> But it is ridiculous to clear History, is not it?!
> In fact, it is kind of tracking.
> History must be untied from Site data. Please!

Understood.  So the issue here that it's not that clear site data doesn't work.  This is a feature request to untie browser history clearing and site data clearing.

**Comment by rocketsroger** [comment]
@vesta0 Looks like this is a feature request rather than a bug.  The user's ask is to uncouple clearing `Browsing history` and `Site data`.  Does this change the priority?

**Comment by vivazkote** [comment]
It is untied in main product - Desktop Firefox, so it is more relevant to call tied functions as incorrect invention, bug.

**Comment by rocketsroger** [comment]
> It is untied in main product - Desktop Firefox, so it is more relevant to call tied functions as incorrect invention, bug.

Understood.  I do agree 100% that this issue is legitimate.  But priority does have to be reassessed since Fenix have many differences comparing to desktop Firefox.

**Comment by mailinglists35** [comment]
On firefox desktop, I was recently asked to tell if I recommend Firefox to friends.

 You see, it's issues like this that prevent me from recommending Firefox to friends. 

Why in the world would I want to lose my history if I only want to clear the data? This the similar bad idea as Safari on iOS, where you must delete each site one by one or else lose all open tabs... Who in the world comes up with such ideas and how do they pass usability team verification, it's past my understanding... 🤦

**Comment by j-r9** [comment]
I would like to see the separation of the clearing of browsing history and site data is a good idea.  This would allow users to delete retained data while allowing them to keep there history if they would like (my preference), or the reverse.  This would also provide more continuity between Desktop and Mobile versions of Firefox.

**Comment by mattmccutchen** [comment]
This is a duplicate with issue #10175.  (I was subscribed to that one and just noticed this one in a search.)  Which shall we keep?

**Comment by B0ycee** [comment]
I'd imagine this needs to be closed as opened after https://github.com/mozilla-mobile/fenix/issues/10175, just like https://github.com/mozilla-mobile/fenix/issues/14402 and https://github.com/mozilla-mobile/fenix/issues/18104 

Showstopper missing feature I feel, but I guess I should not complain...

**Comment by vivazkote** [comment]
issue is not yet fixed for today.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807446

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
