### ISSUE TITLE
Label size for "Send to device" 

### ISSUE THREAD

**Issue by rivman** [mozilla-mobile/fenix#16795]
### Why/User Benefit/User Problem
Identifying the user devices when "Send to Device" is used 

### What / Requirements
Mozilla Firefox Focus Android

When using send tab to device, the most important part of this feature is the name of the device where to send the tab. 
The name is truncated with ellipsis. Even in landscape mode. Can name be ticker scrolling or another method of reading full name of the device ? There is rename device option that can be used to shorten the name, in about:preferences#sync , but that require physical access to that specific machine browser to make the change. 

![Screenshot_20201129-103737_Firefox](https://user-images.githubusercontent.com/11364533/100539477-0dbcd000-3237-11eb-979c-5052750cf898.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8929)

**Comment by sflorean** [comment]
This issue is still reproducible on latest Nightly 7/30.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/15170
