### ISSUE TITLE
[Bug] unable to remove top sites name

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#16790]
![ScreenRecord-2020-11-30-21-34-29](https://user-images.githubusercontent.com/14617699/100649815-0e975400-3354-11eb-93e7-63106068cd4c.gif)

[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Steps to reproduce
Try to rename a top site into an empty string.

### Expected behavior
An empty name.

### Actual behavior
Just nothing happens.

### Device information
Fenix version: latest nightly

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly.
