### ISSUE TITLE
HomeFragment and Tab Tray should use same tab counter as BrowserFragment

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#16792]
Followup to #16605 

The current implementation of the `HomeFragment` is directly using the `TabCounter` class instead of implementing `TabCounterToolbarButton`. This is a hacky approach, and the `HomeFragment` should follow the same implementation that the `BrowserFragment` is using. The Tab Tray is also using it's own tab counter - `tabs_tray_tab_counter.xml` - and should be using the AC version (``). Likewise, remove manual tab counter creation in `TabTrayView` (e.g. `updateTabCounter` method) that would be handled by the AC tab counter.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8927)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812890

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
