### ISSUE TITLE
WebPush subscription failure should reject and not resolve the promise with undefined

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#16802]
Stemming from this comment: https://github.com/mozilla-mobile/fenix/issues/15028#issuecomment-736834347

> In my application code the ServiceworkerRegistration.pushManager.subscribe() promise resolves with an undefined value, which seems kind of wierd. it should probably reject?

We should see if setting null [here](https://searchfox.org/mozilla-mobile/rev/4f4ff2f8fc81fe5ffd6036095fd032023fdabd5d/fenix/app/src/main/java/org/mozilla/fenix/push/WebPushEngineIntegration.kt#80) is incorrect and/or the result needed for GeckoView to reject the promise.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8936)

**Comment by jonalmeida** [comment]
We can use the gauntface example to reproduce the bug to re-confirm when we fix this bug: https://github.com/mozilla-mobile/fenix/issues/17272#issuecomment-778078448

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807382

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
