### ISSUE TITLE
Delete Browsing Data when Firefox swiped from Android Recents

### ISSUE THREAD

**Issue by jawz101** [mozilla-mobile/fenix#16804]
Fennec used to have an advanced option to clear tabs when Firefox is closed (swiped away from Android Recents).  Trying to bring that back.

It also gets rid of the Quit button when Delete Browsing Data is enabled.

Future: 
1-move tab clean schedule setting here as well.
2-Add a site exceptions mechanism to keep some cookies.

**Comment by cadeyrn** [comment]
Please see https://github.com/mozilla-mobile/fenix/issues/5865#issuecomment-603980615.

**Comment by kbrosnan** [comment]
This is not possible to do consistently.

**Comment by jawz101** [comment]
how about an option to either use a quit button or swipe from recents?  It seemed to be pretty consistent on Fennec.

**Comment by kbrosnan** [comment]
Android does not provide a way for the App to tell if the user swipe closed or the OS killed the app in the background both send `signal 9`. Swipe closing Focus leaves it in an indeterminate state. Firefox Focus may not have had time to delete the data it was using. To account for that there are some startup checks to see if it was in that state and do the cleanup. The only clean ways to finish a Focus session is to use the notification or the trashcan button. If we were to implement this in Firefox on Android user would randomly loose their session depending on what other programs are used when the user switches away from Firefox.

**Comment by jawz101** [comment]
I get what you are saying but it can be done.  Focus advertises itself based on the ability that it does that very thing.  And, still, Fennec had the feature as well.  It not being there is a regression since Fennec.  I used the setting on Fennec for  5ish years.  It worked well.
