### ISSUE TITLE
Add Firebase keys to debug variant

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#16806]
This is a mirror of https://github.com/mozilla-mobile/reference-browser/issues/1352.

We know that we can safely add the Firebase keys to the project without it causing a security concern.

We need to do three things to get this landed:
 1. Fix https://github.com/mozilla-mobile/android-components/issues/4166 which will kick up now that we crash on strict mode violations.
 2. Add wiki docs to the project how to debug push (e.g. disable rate-limiting, custom push endpoint)
 3. Upload the actual key files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8939)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807381

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
