### ISSUE TITLE
Synchronize search engines with Firefox Sync

### ISSUE THREAD

**Issue by Whisprin** [mozilla-mobile/fenix#16809]
Please implement synchronisation of search engines.

The [corresponding bug on desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=444284#c115) is open for 13 years and gains more relevance due to the [migration away from keyword bookmarks](https://bugzilla.mozilla.org/show_bug.cgi?id=1653261).

In the mean time any hints for manually exporting and importing all search engines on Android and desktop are welcome.

### What is the user problem or growth opportunity you want to see solved?
Currently the user has to add all search engines they use on every device manually. Implementing this feature creates a more consistent user experience across platforms.

### How do you know that this problem exists today? Why is this important?
After the decision not to implement [bookmark keywords](https://github.com/mozilla-mobile/fenix/issues/12099) - although they work on Desktop today - the option to synchronize search engines has vanished too, since bookmark keyword searches used to be a [well know workaround](https://bugzilla.mozilla.org/show_bug.cgi?id=444284#c115). The corresponding bug on desktop explicitly [requests Android (and iOS)](https://bugzilla.mozilla.org/show_bug.cgi?id=444284#c116) to implement this feature in order to get it off the ground.

### Who will benefit from it?
Every Firefox user who is using custom search engines.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8942)

**Comment by francesco-cadei** [comment]
In Android we don't have keyword option. I think it's a must have.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807757

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
