### ISSUE TITLE
"Open link in external app" does not always appear any more

### ISSUE THREAD

**Issue by Rhialto** [mozilla-mobile/fenix#16817]
## Steps to reproduce
On a page with links to media files (such as `.mp3`, `.m4a`, .`m3u`),
I want to open the a link with the Total Commander Media Player because it can stream the link and queue up several items to play. I long-press on one of those links. A pop up appears.

### Expected behavior
Until some time ago (before the overhaul of the user interface...) I would always get an option "Open link in external app" (all the way at the bottom). 

### Actual behavior
- On some links (typically `.mp3`), I get the option.
- On some links (typically `.m4a`), I used to get the option but no longer.
- Even weirder, on some more links (typically `.m3u`) I sometimes get the option and sometimes not.

I tried changing the mime types that my webserver sends for these files, but it seems to make no difference.

Changing the option "open links in apps" does not seem to help.

### Device information

* Android device: DooGee  Mix-Lite with Android 7.0
* Fenix version: What's Fenix? (I came here via https://bugzilla.mozilla.org/enter_bug.cgi#h=product%7C , then "Firefox for Android")
* Firefox version: 83.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8945)

**Comment by Rhialto** [comment]
Additional information: the problem might for some reason be related to the file name, its length, or the characters that occur in it. Or something like that.
I had a link to a file like `very-long-name.m4a` which doesn't elicit the "open links in apps" option. But a copy/symlink of the same file, now named `test.mp3` does get the option.

**Comment by Rhialto** [comment]
I think I have found a pattern in the names that do or don't work.
It fails for file names that have multiple dots in them.
It seems to behave like it tries to find the file name extension from the first dot, instead of from the last dot, and then only works for the few that it recognizes.
- test....mp3 FAILS
- test.foo.mp3
- test.m4a FAILS
- test.m4a.mp3 FAILS
- test.mp3 WORKS
- test.mp3.mp3 FAILS

By the way, I don't agree wit the label "feature request". This used to work. The label "regression" would be appropriate.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809304

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
