### ISSUE TITLE
[Feature request] Support data URIs

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#1681]
## Steps to reproduce
* Tap on the URL bar.
* Write `data:text/html,<input type=file>`

### Expected behavior
* See a file input (probably).

### Actual behavior
* Searches for my data URL.

### Device information
* Android device: OnePlus 6
* Fenix version: 1.0.1916

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8943)

**Comment by emilio** [comment]
Not sure how important this is to fix, fwiw. I don't expect many people to rely on this. It comes handy to test issues though, I was trying to see if the upload issue was GitHub-specific. But I suspect now it's not, per #1467

**Comment by makotokato** [comment]
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1582606.  GV API uses content principal, so `data:` url won't be allowed.

**Comment by karlcow** [comment]
on nasa Website webcompat/web-bugs#39953 
The app is crashing because of a navigation to a long data-url

**Comment by lnicola** [comment]
This is also useful to send text from a PC to a mobile device.

**Comment by lnicola** [comment]
`data:text/plain,foo` now works, but not the original test case with `data:text/html`.

**Comment by cartr** [comment]
In Nightly 200812 06:01 (Build #2015757491), attempting to type `data:text/html,Hello` into the address bar yields the following error message:

> ### Cannot complete request
> Additional information about this problem or error is currently unavailable.

**Comment by kellda** [comment]
This works now (along with `view-source`, `moz://a`, some about URLs like `about:mozilla`). This is great.

However the MIME type can't be omitted: `data:text/html,test` works, but `data:,test` doesn't (as of stable 88.1.4).

**Comment by masayuki-nakano** [comment]
It seems that still does not support data URI if it contains JS (<script> and event handler attribute).

**Comment by kellda** [comment]
I just tested on latest stable, and both `<script>` and event handler worked. However, you have to replace spaces with `%20`. That's maybe why it didn't worked for you. (Or it wasn't implemented and now is)

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1392211

**Comment by dyura** [comment]
I would like to add more details on the usage of my data urls. I use them a lot for three main purposes.
- On desktop, I use it all the time as scratchpad data: text/html, <html
contenteditable/><title>Edit</title> or even data:text/html,<textarea></textarea>.
- I use a lot of small javascript utilities to print dates in various formats, change text case, etc. These javascripsts are embedded in data: text/html,......
- I use data urls to bookmark many important notes, various numbers, names. Everything that goes beyond logins. 
Thus, these utilities and the information are available through the Firefox account on my devices, including Android.

Today on Android the data url still works via bookmarks. Previously, we could type "data:...." directly into the address bar. I found one of my old phones running Firefox 67.0. In Firefox 67.0 there is no issue with data URLs. Now when I type data:,str1 I am redirected to the Google search result: https://www.google.com/search?q=data%3A%2Cstr&ie=utf-8&oe=utf-8&client=firefox-b-m
Unfortunately, currently the data url doesn't work at all on iOS.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809255

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
