### ISSUE TITLE
[webcontent] www.indiatimes.com - site is not usable

### ISSUE THREAD

**Issue by ghajini** [mozilla-mobile/fenix#16813]
## Site with issue and any steps to reproduce
See
https://github.com/webcompat/web-bugs/issues/61664

### Expected behavior

Website should load correctly

### Actual behavior
Website doesn't load content

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?

No
### Device information

* Android device: android 7.1.2
* Fenix version: 
Latest firefox android nightly as well as stable

**Comment by kbrosnan** [comment]
This is a webcompat problem and is best tracked on their issue tracker.

**Comment by ghajini** [comment]
Webcompat people are unsure how to fix??
Bugzilla told to report here
https://bugzilla.mozilla.org/show_bug.cgi?id=1677276
