### ISSUE TITLE
[Bug] Unable to play certain videos on the page due to unsupported video format

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16820]
## Steps to reproduce
1. Install and Open firefox beta
2. In the URL tab type Filmakinesi site and enter
3. Open any of the film tiles from the list
### Expected behavior
The short videos on the page should play when play function is tapped
### Actual behavior
Unable to play videos in certain tiles due to error
### Device information
Huawei P30 lite - Android 10
Vestel Venüs V3- 6.0.1
* Android device: yes
* Fenix version: firefox beta 83.0.0 beta4
 
![image](https://user-images.githubusercontent.com/66958331/100928889-e183a680-34f7-11eb-8f0c-962c98581e8e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8948)

**Comment by sflorean** [comment]
I wasn't able to reproduce this on Nightly or Beta versions. @BigSamSampson do you still experience this on latest versions?

**Comment by ebalazs-sv** [comment]
I can reproduce this issue on the latest Release 85.1.0 from 1/21 and Beta 85.0.0-beta.9 from 1/17 with Motorola Moto G6 (Android 8).
Pages tested:
https://filmakinesi.com
https://bitmovin.com/demos/av1

**Comment by lobontiumira** [comment]
Reproducible on Beta 87.0.0-beta.6 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible on Beta 88.0.0-beta.4 with Google Pixel (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.0 with Xiaomi Mi 8 Lite (Android 9) on I can reproduce this issue on the https://bitmovin.com/demos/av1 page.

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.4, and Beta 89.0.0-beta.8 on the https://bitmovin.com/demos/av1 page with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
I was able to reproduce RC 90.1.0 on the https://bitmovin.com/demos/av1 page with OnePlus 5T (Android 10).

**Comment by lobontiumira** [comment]
I was able to reproduce RC 90.1.3 on the https://bitmovin.com/demos/av1 page with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by delia-pop** [comment]
This is reproducible on 96.0.0 Beta 4 build on the https://bitmovin.com/demos/av1 page with LG G7 fit (Android 8.1.0) and Samsung S10e (Android 10).

**Comment by delia-pop** [comment]
Reproducible on RC 99.1.0 with LG G7 fit (Android 8.1.0) with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
This is still reproducible on RC 100.1.2 with Huawei MediaPad M2 (Android 5.1.1)  on the https://bitmovin.com/demos/av1 page.

**Comment by wisniewskit** [comment]
This also appears to be affecting a video-to-gif converter as seen here: https://bugzilla.mozilla.org/show_bug.cgi?id=1608332

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible on Beta 106.0b4.
Device used: Oppo Find X5 (Android 12).
Page used for testing: https://bitmovin.com/demos/av1.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813904

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
