### ISSUE TITLE
[Telemetry] Open in app banner

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16828]
## Description & Product Manager / Data Scientist User Story

As a product manager, I want to know if the Open in App banner is an effective feature discoverability tool. 

## What questions will you answer with this data?
- How often users see the banner?
- How often users dismiss the banner?
- How often users tap on "go to settings" from the banner?

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by Mugurell** [comment]
Talked offline with Kate who confirmed with DS and Boek:
- The newly added metrics should log events, not counters anymore
- An an expiration date 6 months is preferred.
Maybe if there is already related telemetry for that part of the screen / feature we can reuse the existing expiration date so that all related telemetry probes will be renewed at the same time.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/1 Firefox Nightly build with Google Pixel (Android 10).
- "Open in app" banner dismissed:
ping: 9715779c-42ed-4443-b866-771f2c34fe45
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-210201000)
 ```
 {
          "category": "banner_open_in_app",
          "name": "displayed",
          "timestamp": 9540
        },
        {
          "category": "banner_open_in_app",
          "name": "go_to_settings",
          "timestamp": 10813
        }
```
- "Open in app" banner - "Go to settings":
ping: 87f56b22-9c9f-4c78-9011-9237eff907ed
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-210201001)

```
 {
          "category": "banner_open_in_app",
          "name": "displayed",
          "timestamp": 14968
        },
        {
          "category": "banner_open_in_app",
          "name": "dismissed",
          "timestamp": 18067
        }
```
