### ISSUE TITLE
FNX-5180 ⁃ Latest strings need some fixes in order to expose for localization work

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#1682]
I found a few more fixes needed in the latest strings that landed [on master](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/strings.xml) (caught in latest [fenix-quarantine l10n import](https://github.com/mozilla-l10n/android-l10n/pull/15#pullrequestreview-227502541)

* "bookmarks_multi_select_title": please always explain in localization comments what parameters (here "%1$d") will be replaced by
* "clear_permission": Not sure this makes sense when I read the comment and then the string. The comment talks about "permissions" in plural, then the string is in singular - so want to make sure everything is OK there, or not
* Also found some nits in localization comments for the "permissions" strings: they state "for clear" in most these strings, and should be "for clearing"
* "clear_permissions_on_all_sites": localization comment here needs to be updated ("fall all sites"?)

thank you!

(CC @boek so he's aware)

**Comment by Amejia481** [comment]
> "clear_permission": Not sure this makes sense when I read the comment and then the string. The comment talks about "permissions" in plural, then the string is in singular - so want to make sure everything is OK there, or not

Sorry my bad, thanks for confirming is was error comment, the string is correct. This string point to **Exceptions** -> **A specific site** ->   **A specific permission**. Below the screen that match this string.

![image](https://user-images.githubusercontent.com/773158/56262553-6fbad700-60df-11e9-8431-b548a8526258.png)

**Comment by Delphine** [comment]
I also noticed another thing:
in the string "bookmark_add_folder", there was now added a "deprecated". This won't do anything on our side, please just drop the string out of the file.
thank you :)

**Comment by Delphine** [comment]
Everything has been fixed now, thanks to everyone! :) 
Closing
