### ISSUE TITLE
[Telemetry] Long press on the address bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#16827]
## Description & Product Manager / Data Scientist User Story

As a product manager, I want to know how often users copy a URL so I can assess the use of COPY as a way of sharing. 

## What questions will you answer with this data?
- How often users long press on the address bar to COPY a URL?

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by mcarare** [comment]
@vesta0 Just to clarify, we need to count how many times the "copy" option is selected after long pressing on the address bar? Because long pressing the address bar does not copy the URL anymore but shows a pop-up menu.

**Comment by vesta0** [comment]
Yes that's correct! Thanks for clarifying!

**Comment by Mugurell** [comment]
Talked offline with Kate who confirmed with DS and Boek:
- The newly added metrics should log events, not counters anymore
- An an expiration date 6 months is preferred.
Maybe if there is already related telemetry for that part of the screen / feature we can reuse the existing expiration date so that all related telemetry probes will be renewed at the same time.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly 201216`** using a Google Pixel 3a (Android 11) and it seems that **no** **`copy_url_tapped`** **event type ping is generated.**

@mcarare please review ☺️

**Comment by mcarare** [comment]
> Hi, I've just checked this matter on the latest **`Nightly 201216`** using a Google Pixel 3a (Android 11) and it seems that **no** **`copy_url_tapped`** **event type ping is generated.**
> 
> @mcarare please review ☺️

Should be good to go, with the latest changes.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201218`** using a Google Pixel 3a (Android 11)

Ping **`d9c08492-6797-479f-9efb-727ad56197f1`**

```
 {
          "category": "events",
          "name": "copy_url_tapped",
          "timestamp": 8528
        }
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/5715650/cpy.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t18120)
