### ISSUE TITLE
[Bug] [a11y] Consider increasing the "Show in private sessions" option from the Search page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#16830]
## Steps to reproduce
1. Have the Accessibility scanner installed and running.
2. Go to Settings - Search and scan the page.

### Expected behavior
No suggestions are made.

### Actual behavior
The "Show in private sessions" option is suggested to be increased from 32dp to 48dp or larger.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 10)
* Fenix version: Beta 84.0.0-beta.3, and 12/2 Nightly
* Please see #9776 

<img src="https://user-images.githubusercontent.com/40694158/100988622-964db000-3558-11eb-9dae-8053371f9b22.jpg" width="300" height="550" />

**Comment by eliserichards** [comment]
Ahh, so this wasn't totally fixed in #9776.. this is still a valid issue 👍

**Comment by yichiehc** [comment]
Hi @eliserichards,
I'm an Outreachy applicant. May I work on this issue? Thanks!

**Comment by eliserichards** [comment]
Hi @yichiehc! Yes, go ahead and start working on this 😄 I have assigned the issue to you

**Comment by yichiehc** [comment]
Thank you @eliserichards 😄

**Comment by lobontiumira** [comment]
Verified as fixed on the 3/30 Nightly build with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).
