### ISSUE TITLE
Glitches Websites [Bug]

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#16831]
## Steps to reproduce
Download Firefox Nightly
Open any website ex: www.twitter.com
### Expected behavior
Website display normally

### Actual behavior
Glitches 

### Device information
Huawei P8 lite

* Android device: 8 Oreo
* Fenix version: Nightly 201202 17:05 (Build #2015779083)
 
![Screenshot_20201203-021636](https://user-images.githubusercontent.com/48631694/100996465-c0f03680-3561-11eb-8f6c-d6b7915c6e0b.jpg)

**Comment by ebalazs-sv** [comment]
This issue is not reproducible on Nightly 1/13 with Huawei P9 Lite (Android 7).
@jawadalkassim Hi! Is this issue still reproducible on the latest Nightly?

**Comment by jawadalkassim** [comment]
@ebalazs-sv No it's working fine in the latest nightly No glitches
