### ISSUE TITLE
[Bug]Metrics ping boolean probes remain set to false

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16832]
This bug is being broken down into a few other bugs: see #17667 (addons), #17530 (open tabs), #17531 (top sites)

## Prerequisites
Have the default top sites available
Have a couple of open tabs
Have the search widget added
Have a PWA installed
Have a couple of add-on installed and enabled

## Steps to reproduce
Generate the **`metrics`** ping

### Expected behavior
The following **`boolean`** probes should be properly updated:

"metrics": {
        "boolean": {
          "addons.has_enabled_addons" 
          "addons.has_installed_addons"
          "gfx.status.headless"
          "metrics.default_browser"
          "metrics.has_open_tabs"
          "metrics.has_recent_pwas"
          "metrics.has_top_sites"
          "metrics.search_widget_installed"
        }

### Actual behavior
The above mentioned probes remain set to false

### Device information

* Android device: Google Pixel 3a (Android 11)
* Fenix version: Nightly Build 201203

### Notes
[Logcat](https://github.com/mozilla-mobile/fenix/files/5635874/mp.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t03120)

**Comment by eliserichards** [comment]
- [x] addons.has_enabled_addon, addons.has_installed_addons: from AC WebExtensionFacts
- [ ] gfx.status.headless
- [ ] metrics.default_browser - should be false? STR don't mention default browser
- [ ] metrics.has_open_tabs: looks like it's [set on startup](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L750) for Glean. Does this happen every time the browser is opened? 
- [ ] metrics.has_recent_pwas: calculated [based on a threshold](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L819) using AC [WebAppShortcutManager](https://github.com/mozilla-mobile/android-components/blob/9d69dab4c17adb07bead817ccdd968e4532a63b9/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt#L222)
- [ ] metrics.has_top_sites
- [ ] metrics.search_widget_installed

**Comment by eliserichards** [comment]
- [ ] metrics.has_open_tabs
   - looks like it's [set on startup](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L750) for Glean. Does this happen every time the browser is opened? 
- [ ] metrics.has_top_sites
   - same as has_open_tabs
   - looks like it's [set on startup](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L756) for Glean. Does this happen every time the browser is opened? 
- [ ] metrics.search_widget_installed
   - we have an Event **and** a metric for this. Seems like it should just be an event: `object SearchWidgetInstalled : Event()`
   - we update [settings with a count](https://github.com/mozilla-mobile/fenix/blob/2796a7ff18c1fd2fb6df902006e65fb01b8e8988/app/src/main/java/org/mozilla/fenix/utils/Settings.kt#L819) of search widgets. Why is this a count?
   - same as has_open_tabs and has_top_sites
   - looks like it's [set on startup](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L747) for Glean. Does this happen every time the browser is opened?

**Comment by eliserichards** [comment]
The metrics should **always reflect the current state of the app**. Currently, we are only evaluating certain metrics on startup (see above) and this can lead to delayed/incorrect metrics.

**Comment by eliserichards** [comment]
Fixes for Addons: 

AC: https://github.com/mozilla-mobile/android-components/pull/9201
Fenix: https://github.com/mozilla-mobile/fenix/pull/17445
