### ISSUE TITLE
[Bug] Update the Bing search engine brand icon

### ISSUE THREAD

**Issue by Standard8** [mozilla-mobile/fenix#16839]
Bing has changed its brand icon, so this needs updating on Fenix.

This is the bug where we changed it on desktop:

https://bugzilla.mozilla.org/show_bug.cgi?id=1669297

**Comment by brampitoyo** [comment]
The Bing icon is available in these formats:

152x152:
https://www.bing.com/apple-touch-icon-precomposed.png

32x32:
https://www.bing.com/sa/simg/favicon-2x.ico

16x16:
https://www.bing.com/favicon.ico

SVG (not framed in square like other logos – I can frame it if you like):
https://share.getcloudapp.com/YEuQQ6R2

**Comment by Standard8** [comment]
> 16x16:
> https://www.bing.com/favicon.ico

This 16x16 favicon.ico is currently the old Bing icon and should not be used.

For desktop we used the 32x32 one.

**Comment by Mugurell** [comment]
This should be ready to test in a few days, after the AC bump.

**Comment by lobontiumira** [comment]
Verified as fixed on the 7/9 Nightly build with Google Pixel (Android 10):
![bing](https://user-images.githubusercontent.com/40694158/125044211-6a714a80-e0a4-11eb-9f71-2c08828a3484.png)
