### ISSUE TITLE
[Bug]Unable to scroll down when accessing  https://getpocket.com/explore/best-of-2020

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#16844]
Unable to scroll down when accessing  https://getpocket.com/explore/best-of-2020

## Steps to reproduce
Go to: https://getpocket.com/explore/best-of-2020

### Expected behavior
User should be able to scroll down and view page.

### Actual behavior
Unable to scroll

### Device information
* Android device: Pixel 3XL, Android 11
* Fenix version: 
83.1.0 (Build #2015776403)
AC: 63.0.9, fc54c566e
GV: 83.0-20201112153044
AS: 63.0.0

Same issue on Beta:

 84.0.0-beta.2 (Build #2015776763)
AC: 67.0.3, 614386935
GV: 84.0-20201119195818
AS: 67.0.0

and Nightly:
Nightly 201202 17:05 (Build #2015779083)
AC: 68.0.20201201190117, b68627d4a
GV: 85.0a1-20201130093031
AS: 67.0.0

**Comment by jonalmeida** [comment]
Assigning to self to investigate where the bug is: Fenix, AC, or GV.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1680709

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment]
I see this reproducing on the GVE app also - https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-debug
So this seems like a GeckoView issue.
Moved the ticket to Bugzilla.
