### ISSUE TITLE
Add ui under settings page for controlling exceptions for auto play

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#16846]
[Video demo](https://drive.google.com/file/d/16JKGmYWB0NIiv5Qr36p3BFBxyc60-xsk/view?usp=sharing)

Related issue https://github.com/mozilla-mobile/fenix/issues/11325

![image](https://user-images.githubusercontent.com/773158/101090202-44bb1a80-3584-11eb-91b2-566033729f5a.png)

**Comment by Amejia481** [comment]
This feature has landed in master, QA team please help us to verify that is working as expected. Thanks in advance!

**Comment by sflorean** [comment]
@Amejia481 tested on latest Nightly and when I add a site to exceptions, (using camera, or microphone), all the permissions are displayed: camera, location, microphone, notification, persistent storage, DRM, autoplay, not only the ones that were allowed as described in your screenshot. Is this expected?

**Comment by Amejia481** [comment]
@sflorean thanks for testing :) 
Yes,  it's expected as we take the default permission values to add the exception :)

**Comment by sflorean** [comment]
Thank you. Closing as verified.
