### ISSUE TITLE
Allow autoplay to controlled via the toolbar 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#16847]
Related issue https://github.com/mozilla-mobile/fenix/issues/11325

![image](https://user-images.githubusercontent.com/773158/101091215-df682900-3585-11eb-9eeb-ed7c00d8437e.png)

**Comment by sheikh-azharuddin** [comment]
@Amejia481 quick question bro why there is a blue dot showing in the security lock icon in your screenshot? Are you planning to integrate tracking protection with the lock icon similar to edge?

**Comment by Dunexus** [comment]
Hi @Amejia481 
As you said, the autoplay icon has been added in nightly. However, its addition is bringing the issue of visible url width back, see https://github.com/mozilla-mobile/fenix/issues/17047.

**Comment by Amejia481** [comment]
> Hi @Amejia481
> As you said, the autoplay icon has been added in nightly. However, its addition is bringing the issue of visible url width back, see #17047.

Thanks for reporting I left some comments in the issue https://github.com/mozilla-mobile/fenix/issues/17047#issuecomment-745403415 :)

**Comment by Amejia481** [comment]
This feature is on master now, ready for QA review :)

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 1/14 with Google Pixel 4 XL (11).
Note that the option can be changed without problems and all the buttons are working as expected.
There are 2 new issues regarding this implementation https://github.com/mozilla-mobile/fenix/issues/17464 and https://github.com/mozilla-mobile/fenix/issues/17457.
