### ISSUE TITLE
FNX-5182 ⁃ [Bug] Selecting bookmark folder in edit mode crashes the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1685]
## Steps to reproduce
1. Edit a bookmark or a bookmark folder.
1. Tap the Parent folder to change it.
    1. Expected behavior
A list of folders is displayed.
    1. Actual behavior
App crashes.
    1. Device information

* Android device: Nexus 5(Android 6), Pixel (Android 9)
* Fenix version: 4/16 build.

**Comment by colintheshots** [comment]
Duplicate of #1675.

**Comment by sv-ohorvath** [comment]
Fixed on 4/21 build.
