### ISSUE TITLE
[Bug] Opening New Tab Page Lags Significantly after Nightly 1203 Update

### ISSUE THREAD

**Issue by sharbet** [mozilla-mobile/fenix#16852]
## Steps to reproduce
1. Install Nightly 201203 (Latest update)
2. Open New Tab
3. Observe New Tab Page Lags

### Expected behavior
New Tab page should open instantly.

### Actual behavior
New Tab page lags for 1-2 seconds.
(This hasn't happened in ~1202 nightly version)

_edit mcomella: I also see this behavior on cold starting the app to the homescreen. Here's a profile of it: https://share.firefox.dev/37RMbwz It appears `NimbusClient.getExperimentBranch` calls into some native code that takes 2+ seconds_

### Device information
Galaxy S20+ (Snapdragon 865, 12GB)
Android 11 (One UI 3.0)
Nightly 85.a1 201203
 
[about_support.txt](https://github.com/mozilla-mobile/fenix/files/5640205/Notes_201204_112810.txt)

**Comment by sharbet** [comment]
Tested on a different device with Android 9, and still facing the same issue.

**Comment by hakkikaancaliskan** [comment]
Also happens when closing tabs and going back to home screen from a tab.

**Comment by andreicristianpetcu** [comment]
![ScreenRecord-2020-12-05-02-53-43](https://user-images.githubusercontent.com/922368/101228720-94453780-36a5-11eb-8615-34fa6b0ef7d3.gif)

**Comment by andreicristianpetcu** [comment]
I have OnePlus 5t with LineageOS 17.1 based on android 10

**Comment by jhugman** [comment]
This appears to be fixed by https://github.com/mozilla/nimbus-sdk/pull/67, but is not yet released.

Filing [this Jira ticket][1] to track the bug in Nimbus.

[1]: https://jira.mozilla.com/browse/SDK-140

**Comment by sharbet** [comment]
> 
> 
> This appears to be fixed by [mozilla/nimbus-sdk#67](https://github.com/mozilla/nimbus-sdk/pull/67), but is not yet released.
> 
> Filing [this Jira ticket](https://jira.mozilla.com/browse/SDK-140) to track the bug in Nimbus.

Any update on when this fix will be released into Nightly? (Still happening, update 1208)

**Comment by csadilek** [comment]
If Nimbus issues caused this, this should be fixed in Nightly 201211 17:01 and newer.

**Comment by hakkikaancaliskan** [comment]
> If Nimbus issues caused this, this should be fixed in Nightly 201211 17:01 and newer.

I can confirm issue fixed for me.

**Comment by andreicristianpetcu** [comment]
fixed here also

**Comment by csadilek** [comment]
Thanks, will close. Please re-open if you still experience delays.
