### ISSUE TITLE
Force open new links on the same tab

### ISSUE THREAD

**Issue by renatoyamane** [mozilla-mobile/fenix#16859]
I'm having too many tabs opened unnecessarily.

The tip available below is not valid anymore, because about:config is not available anymore.
https://support.mozilla.org/en-US/questions/1226151

Please, add an option "force open new link in the same tab" feature or a customizable "auto-close tab". The minimum time now is 1-day. It should be customizable by the user. Let's say: 1 hour (instead of 1 day).

Thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8970)

**Comment by tortino** [comment]
any news on this?

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1359409

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1360722

**Comment by causalfridays** [comment]
The problem is that all links followed from the firefox homepage or from bookmarks open in new tabs. This is what causes too many tabs to open after using firefox for not too long.

Links opened from other places correctly open in the same tab, which is fine.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1366090

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1368212

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1368378

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1380380

**Comment by AlanaRoo** [comment]
No one is bothering to reply. I am looking for a mobile browser that does not open a tab for every web page I click on. Why has this choice between taken away? Ridiculous! This thread is being ignored.

**Comment by dhdallas** [comment]
When are you going to stop Firefox from opening a new tab/window every time I click on a link? I am ready to switch back to Chrome if this issue is not fixed!

**Comment by renatoyamane** [comment]
> When are you going to stop Firefox from opening a new tab/window every time I click on a link? I am ready to switch back to Chrome if this issue is not fixed!

Hi, I reported this issue more than 2 years ago and there are also many other people complaining about this as you can see in the replies above with the link "user feedback"

My experience with open-source software is:

- If the bug is not fixed 6 months after the report, it will never be fixed and if you ask for a solution, you will hear "it's an open source. Fix it by yourself".

So, I'm pretty sure this annoying feature will never be fixed.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812887

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
