### ISSUE TITLE
[Bug] Cookies item is cropped

### ISSUE THREAD

**Issue by insiderser** [mozilla-mobile/fenix#16868]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Have a small screen or enable big fonts in system settings.
2. Open Firefox.
3. Navigate options menu -> Settings -> Delete browsing data on quit.
4. Look at the cookies item.

### Expected behavior

No text is cropped.

### Actual behavior

![screenshot](https://user-images.githubusercontent.com/34242332/101238968-b01ffc00-36ec-11eb-8350-5b1733bc9a67.png)

### Device information

* Android device: Pixel 4a
* Fenix version: 83.1.0

**Comment by cadeyrn** [comment]
Duplicate of #16745, should already be fixed in Firefox Nightly.

**Comment by insiderser** [comment]
Can confirm that this issue is not present in Nightly.
