### ISSUE TITLE
[Bug] High memory consumption, os paging, with a certain url

### ISSUE THREAD

**Issue by rolfausohnder** [mozilla-mobile/fenix#16867]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
open the following url https://opera-inside.com/ring-des-nibelungen-von-richard-wagner-opernfuehrer-und-handlung/?lang=de and browse around a bit
### Expected behavior
no problems expected
### Actual behavior
too much memory is consumed, firefox hangs, os kills other apps etc
### Device information

* Android device: Samsung Galaxy S9 with Android 10, all updates installed
* Fenix version: 84.0.0-beta.2
The following add-ons are installed and in use : uBlock Origin, Dark Reader, NoScript

Please note : can also be reproduced on windows with FireFox 83.0, the url itself is fine, can be browsed with Chrome without issues

**Comment by mcomella** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1681614

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by squarewave** [comment]
@rolfausohnder, could you give a bit more detail about the relative performance between Firefox and Chrome on this page on Windows? Those addons might be giving you trouble, and I'm wondering if Chrome performs any better than Firefox for you on Desktop with those same addons installed.

**Comment by rolfausohnder** [comment]
> 
> 
> @rolfausohnder, could you give a bit more detail about the relative performance between Firefox and Chrome on this page on Windows? Those addons might be giving you trouble, and I'm wondering if Chrome performs any better than Firefox for you on Desktop with those same addons installed.

I'm sorry, I'm unable to reproduce this with my current Firefox 84.0.2
