### ISSUE TITLE
[Bug] Show Frecency when clicking on the URL while on a webpage

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16863]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Currently when you click on the URL it opens the keyboard, but the search suggestions provided by the browser are blank
Please make this frecency instead
![Screenshot_20201205-015109_Firefox_Nightly](https://user-images.githubusercontent.com/33252312/101210963-60194900-369c-11eb-8e4b-e5adf0ac0762.png)

**Comment by sflorean** [comment]
This is still reproducible on latest Fenix versions.
