### ISSUE TITLE
[Bug] System permission prompt for location access is displayed after the app's doorhanger

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1686]
## Steps to reproduce
1. Turn off Fenix location permissions from the system settings.
1. Go to google maps / mapquest.com.
1. Wait for the permission access request. On google maps, you need to tap the "get my location" button.
    1. Expected behavior
The system prompt is displayed to allow app's permission. After this is allowed, the app's doorhanger is displayed for site permission.
    1. Actual behavior
App's doorhanger is displayed first, then after it's dismissed, the system prompt.
    1. Device information

* Android device: Pixel (Android 9), HTC 10 (Android 8).
* Fenix version: 4/16 build.

**Comment by Amejia481** [comment]
Related BugZilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1527056

**Comment by cpeterso** [comment]
@bifleming - This bug might be in Fenix, GV, or Gecko code. Can a Fenix engineer investigate to confirm this is not a Fenix bug before GV/Gecko engineers dig deeper?

**Comment by Amejia481** [comment]
@cpeterso This is a GV bug. I opened an bug about it on Bugzilla before Fenix MVP https://bugzilla.mozilla.org/show_bug.cgi?id=1527056

**Comment by cpeterso** [comment]
> This is a GV bug. I opened an bug about it on Bugzilla before Fenix MVP https://bugzilla.mozilla.org/show_bug.cgi?id=1527056

Thanks. I see this Fenix issue is a P2 in Fenix's "Items waiting for Fenix Q3" bug list. The GV team has already committed to its September sprint backlog, which doesn't include GV bug 1527056. But I'll prioritize that bug so we review it for our October sprint planning.

**Comment by vesta0** [comment]
@cpeterso did this make it into the October or November sprint backlog?

**Comment by cpeterso** [comment]
> @cpeterso did this make it into the October or November sprint backlog?

No. This issue is not in Fenix's [Top 10 GV bug list](https://github.com/orgs/mozilla-mobile/projects/48?card_filter_query=1686), so the GV team has not prioritized it yet. IIUC the site still works correctly. This issue is just about the order in which the permission prompts are shown.

**Comment by vesta0** [comment]
@boek this results in bad user experience, I recommend prioritizing it :)

**Comment by cpeterso** [comment]
@boek says he will confirm the current user experience.

What does Chrome?

**Comment by eliserichards** [comment]
@vesta0 is this still something we would like to prioritize?

**Comment by vesta0** [comment]
I have an STR which I am not sure if it's related to this issue or whether it is its own issue. If it's related, then yes please prioritize this. If it's not related, please create a new issue for it and close this one. 

-Open a new tab in Fenix and navigate to Google Maps for the first time.
-Tap on the "your location" icon on the map.
-You will get the Fenix "Allow www.google.com to use your location" prompt. 
-Select "Remember decision" and tap on "Allow".
-Nothing happens.
-Tap on the "your location" icon on the map, again.
-You will get the Fenix "Allow www.google.com to use your location" prompt, again.
-Select "Remember decision" and tap on "Allow".
-This time you can see your location on the map.

**Comment by sv-ohorvath** [comment]
@vesta0 That sounds more like: https://github.com/mozilla-mobile/fenix/issues/3207 Is that right?

**Comment by vesta0** [comment]
I think so. If that is the case then we can prioritize #3207 instead.

**Comment by sv-ohorvath** [comment]
Still reproducing, reopening.

**Comment by sv-ohorvath** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1527056 was marked as won't fix.
