### ISSUE TITLE
Fenix keeps alive Alarms and Jobs on return to foreground

### ISSUE THREAD

**Issue by quick-lab-iqui** [mozilla-mobile/fenix#16866]
## Steps to reproduce
I was profiling the behavior of Firefox in Android Studio 4.1.0. During power consumption tests of curren fenix version, strange behavior could be observed in the application. Every time the application was started, it started with 0 jobs and alarms, however, we could notice that every time it went from background to foreground, it created a new Job. At first it was thought that the application generated them to respond to system events, collect information or save the state of the application. However, when the app was returned to the foreground, these Jobs remained active and were never closed. The application was kept running for 22 minutos and during this time 80 jobs were started, as seen the figure below.

![imagen](https://user-images.githubusercontent.com/75517447/101235742-fc415100-3698-11eb-88bf-891d88aaffac.png)

### Expected behavior
The threads finish their execution and are not left open.
### Actual behavior
Threads are created that remain open that seem not to be handled by any class
### Device information

* Android device: Motorola G6. Android 9
* Fenix version: 83.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8973)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807314

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
