### ISSUE TITLE
FNX-5183 ⁃ [Bug] Dialogs remain on screen after the session auto-saves

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1687]
## Steps to reproduce
1. Go to permissions.site, tap one of the options: camera, mic, location, to show the permission doorhanger.
Or, go to settings>site permissions>exceptions list, tap the clear permission button to display the confirmation dialog.
1. Leave the phone to sleep for 5 minutes or more.
1. Return to the app.
    1. Expected behavior
Auto-saved session is shown on the homescreen, dialogs are closed.
    1. Actual behavior
Auto-saved session is displayed on the homescreen and the dialogs are still displayed.
![Screenshot](https://user-images.githubusercontent.com/4037709/56272866-4bbdbc80-6104-11e9-9818-bb4fffa2ee7c.png)UNITO-UNDERSCORE!20190417-042539!
![Screenshot](https://user-images.githubusercontent.com/4037709/56272870-4d878000-6104-11e9-84bf-f42eb5c7b831.png)UNITO-UNDERSCORE!20190416-101938!

### Device information
* Android device: Pixel, Nexus 5.
* Fenix version: 4/16 build.

**Comment by kbrosnan** [comment]
Closing as we don't have auto saving of sessions any more.
