### ISSUE TITLE
[Bug] "Send to Device" does not open tabs in target Firefox on Android, only opens notifications

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#16879]
## Steps to reproduce

Select tabs for "Send to Device", share them with "Send to Device" to another installation of Firefox on Android.

### Expected behavior

Tabs should populate directly into the target browser after tabs that are already open.

### Actual behavior

"Send to Device" only sends the tabs as individual notifications to the target browser that have to be tapped each for the tabs to actually open. In addition, see #16878 - only a portion of the sent tabs are actually sent.

### Device information

* Android device: Xiaomi Mi A1
* Fenix version: Beta (84.0.0-beta.2) -> Nightly (201205 17:02)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8985)

**Comment by purpleyuan** [comment]
This is still an issue, especially on my device that has both the stable and nightly versions of Firefox downloaded and I am sending it to a specific one. Please keep it open.

**Comment by xantonin** [comment]
Confirmed this issue. In my case, I was selecting multiple tabs and sending them to my new phone. Unfortunately I only got 55 notifications on my new phone, instead of the 55 tabs opening on my new phone...

**Comment by purpleyuan** [comment]
Commenting to keep this open.

**Comment by KopfKrieg** [comment]
Still relevant, don't close…

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810638

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
