### ISSUE TITLE
[Bug] Open https://randomnetcat.github.io/cpp_initialization/initialization.svg will cause firefox to go close

### ISSUE THREAD

**Issue by fritzmark** [mozilla-mobile/fenix#16875]
## Steps to reproduce

Open https://randomnetcat.github.io/cpp_initialization/initialization.svg in firefox browser.

### Expected behavior

The svg should be shown.

### Actual behavior

The client closes.

### Device information

* Android device:  OnePlus A3003 (OnePlus A3003_16_19104)
* Fenix version: 83.1.0 (Build #2015776403)

**Comment by Dunexus** [comment]
Cannot reproduce on latest nightly using Oneplus 5T (Android 10).

Could you retest using nightly where bug fixes land first ?

**Comment by fritzmark** [comment]
You are right in the nightly version the svg is shown. Thanks for the hint. Closing issue.
