### ISSUE TITLE
[Bug] Sharing a collection from one Firefox on Android to another only shares the 1st tab

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#16877]
## Steps to reproduce

Create a "Collection" on Firefox on Android (standard, beta and nightly), press "Share" button on created collection, share it to another Firefox.

### Expected behavior

All tabs, i.e., the full collection should be shared and opened in the Firefox (or any other browser, for that matter!).

### Actual behavior

Just the 1st saved tab in the collection is sent over by sharing.

### Device information

* Android device: Xiaomi Mi A1
* Fenix version: Beta (84.0.0-beta.2) -> Nightly (201205 17:02)

**Comment by eberhardweber** [comment]
Also selecting multiple tabs and then sending them via Android's own share (i.e., selecting "Firefox Beta" or "Firefox Nightly" instead of "Send to Device") to another Firefox only shares the 1st tab, not all of them. The 1st tab does open in the browser as it should, but the rest aren't sent.

**Comment by softvision-miralobontiu** [comment]
This is a known issue.
Please see #4178 
I'll close this as a duplicate.
