### ISSUE TITLE
[Bug] Missing options in video context menu

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#16871]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open https://gnu.org, or another website where the video can be played with browser controls (i.e. no javascript overlay as with many video websites, just direct video link).
2. Long press on video
### Expected behavior
In the context menu:
- copy link
- open in a new tab 
- open in a new private tab
- share link

should be there, as with links / images

### Actual behavior
There is only open in an external app and download file
### Device information

* Android device: Pocophone F1, android 9
* Fenix version: 20201204

**Comment by B0pol** [comment]
Note: not a duplicate of https://github.com/mozilla-mobile/fenix/issues/14730. This issue is about video controls (play / pause, mute / unmute, fullscreen, show controls).

**Comment by rocketsroger** [comment]
Added copy link and share link to video, audio and image.  This should be in the next Nightly build.  Closing as fixed.

**Comment by rocketsroger** [comment]
Did not add open in new tab since copy link is now available.  Please open a separate issue if open in new tab is a must.  We can discuss if that should be added.  Thanks,

**Comment by B0pol** [comment]
Open in an external app has been removed!
