### ISSUE TITLE
FNX-5184 ⁃ [Bug] Navigation buttons do not work in Custom Tab

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1688]
## Steps to reproduce
1. Set Fenix as the default browser.
1. From any app open a custom tab (eg. Gmail, Yelp, Facebook).
1. Tap on a different link in the opened custom tab in order to change the page.
1. Open the menu and tap on the back button.

### Expected behavior
The previous page is loaded.

### Actual behavior
Nothing happens.

### Device information
* If using the device back button you are able to get to the previous page, the forward button is still disabled/does not work.
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * Nexus 6P (Android 8.1)
  * HTC 10 (Android 8)
  * Samsung Galaxy S8 (Android 9)
* Fenix version: 1.0.1916 (#11061213)

Related to #1282 ? In my case the navigation buttons do not work at all, no matter how many times they have been pressed.

**Comment by vesta0** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/issues/2699

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11471807), with Nexus 6P (Android 8.1.0), Samsung Galaxy S8 (Android 9), and Sony Xperia Z2 tablet (Android 6.0.1).
The back and forward arrows are working as expected.
