### ISSUE TITLE
Allow for Beta/Nightly "Debug Menu" is to be permanently activated

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#16881]
## Steps to reproduce

Pressing five times on the Firefox Browser logo in Settings -> About Firefox enables the Debug Menu on Beta and Nightly.

### Expected behavior

The Debug Menu should remain permanently activated for the user. 

### Actual behavior

The Debug Menu disappears with each restart of the browser, and the user has to press the icon five times again whenever the debug menu is needed.

### Device information

    Android device: Xiaomi Mi A1
    Fenix version: Nightly (201205 17:02)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8988)

**Comment by eberhardweber** [comment]
To expound on the issue, the biggest downside to this problem is that Nightly add-on collections can only be refreshed and reloaded through activating the debug menu, even though I assume most people are constantly editing their add-on lists.

**Comment by cadeyrn** [comment]
I don't see why the current behaviour should be a bug. While I am sure there are some people that prefer the current way and other people who prefer your suggested way there is no right or wrong. FWIF I prefer the current behaviour.

**Comment by eberhardweber** [comment]
> 
> 
> I don't see why the current behaviour should be a bug. While I am sure there are some people that prefer the current way and other people who prefer your suggested way there is no right or wrong. FWIW I prefer the current behaviour.

I would actually disagree, and point you to the standard Android behavior - "Developer Options" are unlocked permanently in Android Settings by tapping the Build number information in the "About phone" section of the Settings menu. 

I do not see why Firefox should not replicate the Android standard on Android.

As a personal anedcote, I've just tapped on the icon about 200 times just this evening. I understand you may not personally be facing usability issues, but like with bug #16885, the UI is a _huge_ hurdle without permanent unlocking.

**Comment by s-ankur** [comment]
Probably it will have the same reasoning as closing https://github.com/mozilla-mobile/fenix/issues/14348

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809233

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
