### ISSUE TITLE
Tiled tab browsing descending from top instead of ascending from bottom

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#16884]
### What is the user problem or growth opportunity you want to see solved?

Currently, it is only possible to browse grid-tiled tabs from the bottom, ascending. I would prefer to browse them from the top, descending, newest tab first at top - not last at the very bottom.

Adding a toggle for this feature to the "Tab settings" menu would be very desirable.

### How do you know that this problem exists today? Why is this important?

It is very common taxonomy to display newest/latest item at top. In similar use cases (e-mail clients, etc.) it is often possible to toggle sorting by date, ascending/descending etc.

### Who will benefit from it?

All users of Firefox for Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8991)

**Comment by anotherus3r** [comment]
This was the default behaviour before, but was changed because many people wanted the top tab to be the oldest. See for example: #11376

Anyways, making this toggleable would be nice, too.

**Comment by waaronking** [comment]
I'd also like to voice my support to this feature request. I personally preferred the top-to-bottom newest-to-oldest sorting that we had in previous versions. I understand that some people prefer bottom-to-top sorting, but this seems to boil down to personal preference and whether you choose to customize your toolbar to be on the top or bottom of the UI. 

Most UX list sorting experiences I've noticed are top-to-bottom newest-to-oldest sorting (think social media, email, music playlists, messenger, telegram, etc.), so I'd love this to at least be a configurable option under the tab settings. 

Please consider.

**Comment by boek** [comment]
Dup of #19231
