### ISSUE TITLE
[Bug] "Send to Device" does not respect tab order on Android

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#16880]
## Steps to reproduce

Select tabs on Firefox Beta on Android and use "Send to Device" from the Share menu to send them to another Firefox on Android.

### Expected behavior

Tabs are populated in the target browser in the same order as they were sent.

### Actual behavior

Tab order is shuffled by "Send to Device".

### Device information

* Android device: Xiaomi Mi A1
* Fenix version: Beta (84.0.0-beta.2) -> Nightly (201205 17:02)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8987)

**Comment by sflorean** [comment]
Tested on Fenix 90.1.3 and got different behaviors with Pixel 3 (Android 12). The tabs were received on desktop, in the same order. When sending on another Android device, the tab notification were reversed.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810636

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
