### ISSUE TITLE
about:config setting to disable PWA "Add to Home Screen" menu item in Firefox for Android

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#16883]
### What is the user problem or growth opportunity you want to see solved?

An about:config toggle setting to disable the menu item is sorely needed to create extra space in the menu (see #16882 for instance). 

Unfortunately, issue #10253 seems to only track the popup, not the menu item. 

### How do you know that this problem exists today? Why is this important?

This has been an issue since the original Firefox for Android, see

https://old.reddit.com/r/firefox/comments/a7lh08/android_hiding_add_to_home_screen/
https://bugzilla.mozilla.org/show_bug.cgi?id=1444984

### Who will benefit from it?

Anyone who does not want to use PWAs.

**Comment by eberhardweber** [comment]
There's also a visual dimension to this issue: Every time a PWA-enabled website is browsed, the main menu blows up with a blue marker that indicates it is possible to "Install" the website. 

This is undesired noise in the menu and draws the user's attention away.

**Comment by cadeyrn** [comment]
It doesn't make sense to implement this as an about:config option because there is no about:config in stable releases.

**Comment by jawz101** [comment]
Make it a gui preference.

(Sometimes people learning Firefox call any setting about:config)

**Comment by eberhardweber** [comment]
> 
> 
> It doesn't make sense to implement this as an about:config option because there is no about:config in stable releases.

There are several reasons why introducing an about:config option makes sense: 

- With this push towards PWA and not away from it, I don't believe Firefox developers are currently considering a GUI option
- This resembles other under-the-hood options that suit the Beta and Nightly branches better than Stable
- Users who want to avoid PWA may be in the minority and as such adding a GUI element may not be worth the screen estate

> 
> 
> Make it a gui preference.
> 
> (Sometimes people learning Firefox call any setting about:config once they read long-time users talk about Firefox)
> 
> The guy also rapid fired 8 observational bug reports. I'd just read them, make a mental note, and move on.

See above why I don't think there's any confusion as to why it should specifically be an about:config setting. I would much rather settle on a GUI switch, though!

**Comment by kbrosnan** [comment]
There is no way to do this via about:config. It will not be used to control Fenix UI

**Comment by mvasi90** [comment]
I'm using Firefox on Android. When I'm trying to add a URL ahortcut to home screen Firefox adds shit.

For instance, the following link doesn't work. The language is lost, the current selected menu item is changed by another showing undesired videos.

https://weather.com/fr-FR/temps/aujour/l/1a8af5b9d8971c46dd5a52547f9221e22cd895d8d8639267a87df614d0912830

An option is needed to bypass/skip PWA. People need a simple link not useless shit.
