### ISSUE TITLE
[Bug] Sync setting isn't displayed temporarly after startup

### ISSUE THREAD

**Issue by ddarfantasy** [mozilla-mobile/fenix#16890]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
* Log in sync service
* Cold start Firefox
* Open settings immediately
### Expected behavior
In the account section, my account information is displayed.
### Actual behavior
You have to wait about 4~5 seconds until the account setting is loaded.
### Device information

* Android device: 10
* Fenix version: 83.1.0
 
(If you can't reproduce the issue, I can provide a screen recording.)
Thanks!
_Redirected from https://github.com/mozilla-mobile/fenix/issues/16805#issuecomment-739257969_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8996)

**Comment by eliserichards** [comment]
We should have a placeholder here until sync auth completes

**Comment by Koyomivamp01** [comment]
Because of this sync in Fenix extra more slower and wasted more times and battery

**Comment by 532910** [comment]
Why the the lack of a recent activity a reason not to fix the bug?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807128

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
