### ISSUE TITLE
[Bug] This URL makes Fenix close itself

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#16897]
## Steps to reproduce
Install brand new production Fenix version (but also happens with current nightly)
Navigate to https://www.lemonde.fr/international/article/2020/12/07/en-cisjordanie-la-colonisation-par-les-routes_6062419_3210.html

### Expected behavior
The page is displayed correctly

### Actual behavior
The page begins to be displayed, the progress bar goes up to 75% or so.
Then suddendly, Firefox closes and the launcher appears.
After checking, Firefox is actually still running in background, but address bar is empty and start page is displayed when bringing it to foreground.
Deactivating tracking protection does not change anything.

### Device information

* Android device: 9 (Redmi Note 7)
* Fenix version: 83.1.0

**Comment by kbrosnan** [comment]
Crashes on Geckoview example as well. Moving to Bugzillla.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1681139

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
