### ISSUE TITLE
FNX-5185 ⁃ [Bug] Custom Tabs: navigation buttons are not grayed out when no other page has been visited

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1689]
## Steps to reproduce
1. Set Fenix as your default browser.
1. Open a custom tab from any app (eg. Gmail, Yelp, Facebook).
1. Tap on the 3dot menu.

### Expected behavior
The navigation buttons are greyed out.

### Actual behavior
The navigation buttons are not grayed out.

### Device information
* Affected devices:
  * Nexus 5 (Android 6.0.1)
  * Nexus 6P (Android 8.1)
  * Samsung Galaxy S8 (Android 9)
  * Google Pixel (Android 9)
* Unaffected devices:
  * HTC 10 (Android 8) - the buttons remain grayed out even if navigating to a different page
* Fenix version: 1.0.1916 (#11061213)

![comparison](https://user-images.githubusercontent.com/17178945/56274860-3f3b6300-6108-11e9-8492-6feae1a0fa32.jpg)

**Comment by vesta0** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/issues/2699
