### ISSUE TITLE
FNX-5186 ⁃ [UX] Account (Setup & Management)

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#169]
GH issue to track design work. The main designer will be Ryan Feeley but shorlander will coordinate. 

User stories in Meta

https://mozilla.invisionapp.com/share/YFR8N20QN7R#/352851515_-Fenix-_Sync_UI

**Comment by vesta0** [comment]
@shorlander would you please size this work?

**Comment by vesta0** [comment]
@lime124 what is the status and size of this work?

**Comment by shorlander** [comment]
I talked with Ryan and we think this is a M sized effort. The flows for sign-in and management already exist; we will need to adapt them for Fenix specifically.

**Comment by vesta0** [comment]
@ryanfeeley when can we target completion?

**Comment by bbinto** [comment]
@rfk and @lime124 - in order to write some usedul users stories for https://github.com/mozilla-mobile/fenix/issues/212, please share some mocks here. Thanks

**Comment by bbinto** [comment]
We probably can however get started with this: https://github.com/mozilla-mobile/fenix/issues/289

**Comment by rfk** [comment]
> @rfk [ ... ] please share some mocks here. Thanks

I'm going to assume this was supposed to be for @ryanfeeley, although github didn't autocomplete his username so I'm not sure if it'll ping him about it...

**Comment by lime124** [comment]
yes - sorry about that!

**Comment by ryanfeeley** [comment]
but @rfk is still probably needed!

**Comment by mheubusch** [comment]
@lime124 Have designs been shared with and reviewed with Fenix eng?  If so can we remove blocked label?

**Comment by lime124** [comment]
@colintheshots has reviewed an earlier version. he's going to look again tomorrow and post any further questions.

**Comment by colintheshots** [comment]
This looks good to me. Signing off on it.
