### ISSUE TITLE
[Bug] Nightly start up crash: org.mozilla.experiments.nimbus.ErrorException$RequestError: Error sending request

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#16902]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Install today's nightly (12/7)
- Start the app

### Expected behavior
No crash.

### Actual behavior
A very long pause and then a crash.

> 12-07 13:36:07.556 E/AndroidRuntime(31944): Caused by: org.mozilla.experiments.nimbus.ErrorException$RequestError: Error sending request: [no-sentry] Network error: Java error: "fetch error: java.net.SocketTimeoutException"
12-07 13:36:07.556 E/AndroidRuntime(31944):     at org.mozilla.experiments.nimbus.Error.intoException(nimbus.kt:9)
12-07 13:36:07.556 E/AndroidRuntime(31944):     at org.mozilla.experiments.nimbus.NimbusClient.getExperimentBranch(nimbus.kt:10)
12-07 13:36:07.556 E/AndroidRuntime(31944):     at mozilla.components.service.nimbus.Nimbus.getExperimentBranch(Nimbus.kt:1)
12-07 13:36:07.556 E/AndroidRuntime(31944):     at org.mozilla.fenix.home.HomeMenu$coreMenuItems$2.invoke(HomeMenu.kt:11)
12-07 13:36:07.556 E/AndroidRuntime(31944):     at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
12-07 13:36:07.556 E/AndroidRuntime(31944):     at org.mozilla.fenix.home.HomeMenu.<init>(HomeMenu.kt:23)

We shouldn't ever crash if we're unable to reach the server because that's an event that will happen to real users. It seems like Nimbus should be catching these exceptions and propagating them safely to the application.

Note also that we shouldn't be doing main thread network IO on start up: I filed #16901 for that.

### Device information

* Android device: p2
* Fenix version: today's nightly, 12/7

**Comment by mcomella** [comment]
S1: I'd speculate that at some point at least 25% of users will start the app without network access, see the long pause, and crash.

**Comment by csadilek** [comment]
@mcomella This is the same as https://github.com/mozilla-mobile/fenix/issues/16886 and also likely cause of the perf. ticket https://github.com/mozilla-mobile/fenix/issues/16852. Problem is being addressed in Nimbus.

**Comment by kbrosnan** [comment]
Closing as a duplicate
