### ISSUE TITLE
Automatic download collections pages to read pages later and offline.

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#16904]
Hi,
I'm using Firefox on Android.
Please add the below feature:
- Automatic download collections pages to read pages later and offline.

Thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9008)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809310

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
