### ISSUE TITLE
View collections pages in reader view by default

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#16903]
Hi,
I'm using Firefox on Android.
Please add the below feature:
- View collections pages in reader view by default.

Thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9007)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812741

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
