### ISSUE TITLE
FNX-5187 ⁃ [Bug] The cookie acceptance popup is not entirely visible on www.cosmopolitan.com

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1690]
## Steps to reproduce
1. Open www.cosmopolitan.com.
1. Turn your device in landscape.

### Expected behavior
The user should be able to tap on "Accept" cookies.

### Actual behavior
The cookie acceptance popup is non-scroll-able, and "Accept" button cannot be tapped.

### Device information
* Android device: Nokia 6 (Android 7.0)
* Fenix version: 1.0.1916 (Build #11061212)

### Note
Not reproducible on Chrome.

![2019](https://user-images.githubusercontent.com/40694158/56283363-33f13300-611a-11e9-93f6-2c4405e7fc09.gif)UNITO-UNDERSCORE!04!UNITO-UNDERSCORE!17!UNITO-UNDERSCORE!12!UNITO-UNDERSCORE!43!UNITO-UNDERSCORE!54!

**Comment by kbrosnan** [comment]
This might only be shown to EU readers. I did not see this notice when browsing the site.

**Comment by ekager** [comment]
@softvision-miralobontiu are you still seeing this on latest Nightly?

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the issue with Nokia 6 (Android 7) on the latest Nightly build from 7/14.
