### ISSUE TITLE
[Bug] Logins&Passwords - Invisible text in light theme

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16919]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Preconditions: Light theme is activated.
1. Open the firefox browser
2. Tap kebab menu
3. Tap Settings
4.Tap Customise
5. Tap Logins&Passwords
6. Tap Saved logins
### Expected behavior
User sees prompt text “Tap the fingerprint reader” under the fingerprint image.
### Actual behavior
User doesn't see prompt text under the fingerprint image in the Light theme. This text visible only in Dark theme.
### Device information
Motorola Moto Z Droid - Android 8.0
* Android device: yes
* Fenix version: firefox beta 84.0.0
 
![image](https://user-images.githubusercontent.com/66958331/101494379-4ddb2b80-3978-11eb-8f56-43d41ae2a2b5.png)

**Comment by ekager** [comment]
This is a Google bug - looks like https://issuetracker.google.com/issues/173337268 . We'll pick up the fix when we upgrade our Biometric libraries

**Comment by kbrosnan** [comment]
Closing as an upstream bug.
