### ISSUE TITLE
[Bug] Cannot scroll up on groups.google.com, instead it causes a pull to refresh

### ISSUE THREAD

**Issue by saschanaz** [mozilla-mobile/fenix#16914]
## Steps to reproduce

1. Open https://groups.google.com/a/chromium.org/g/blink-dev/c/-2JIRNMWJ7s/m/yHe4tQNLCgAJ
2. Scroll down to the bottom
3. Now try scrolling up

### Expected behavior

It should scroll up

### Actual behavior

It calls the refresh ring

### Device information

* Android device: Galaxy Note 8 
* Fenix version: Nightly
 
Moved from https://github.com/webcompat/web-bugs/issues/63285

**Comment by Ruin0x11** [comment]
I have the same issue every other time I scroll up on google.com.

In this video I'm trying to scroll up at a constant interval.


https://user-images.githubusercontent.com/6700637/115615343-b2ea4a80-a2a3-11eb-9a86-c49aa3a271d3.mp4

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 101.0a1 (2022-04-28) build.
Device used: Google Pixel 4 (Android 12).

https://user-images.githubusercontent.com/48829350/165773100-d0415b4d-a85e-44ae-9bc4-81cf60ff8428.mp4

Closing the ticket as fixed.
