### ISSUE TITLE
Implement extension runtime permissions

### ISSUE THREAD

**Issue by xcffl** [mozilla-mobile/fenix#16912]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to Settings of an extension with runtime permission request (should be options.html on desktop)
2. Let the extionsion request runtime permissions. Say, click `Grant permission` in the Settings page

### Expected behavior
A popup is shown to grant/deny the runtime permission request

### Actual behavior
Nothing happens. 

### Device information

* Android device: Android 10
* Fenix version: Nightly 201207 17:01 (Build #2015780043)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9012)

**Comment by M-Reimer** [comment]
Same on Android 11. Latest nightly. Tried to get one of my Add-ons to work on Nightly: https://addons.mozilla.org/firefox/addon/togglereferrer/

Code execution immediately ends at the line

      const success = await browser.permissions.request(permissions);

No error messages in Console.

**Comment by Offerel** [comment]
Is there any timeline, to get this solved?

**Comment by M-Reimer** [comment]
As the "good old" Android Firefox, which had this feature, is no more and I want to get a usable environment on Android again, I decided to go for a temporary workaround.

A new Makefile target patches in a new Add-on ID (to make an independent clone of my Add-on) and then merges "permissions" with "optional_permissions" in this clone. Silly hack but it allows to make the feature work that requires the optional permissions. It just makes it impossible to enable it on demand. As this is primarily for my own need, I've checked the "experimental" checkbox for this.

**Comment by yan12125** [comment]
Looks like this feature first requires change in GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1601420

**Comment by M-Reimer** [comment]
As https://bugzilla.mozilla.org/show_bug.cgi?id=1601420 is still open I think this Issue also still is not resolved.

**Comment by M-Reimer** [comment]
Just tested. Still not fixed!

**Comment by calumozilla** [comment]
The geckoview work to implement permissions.request has been completed. Fenix can now implement the new delegate method onOptionalPrompt. 
Related patch: https://phabricator.services.mozilla.com/D143925 
Related geckoview bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1601420

**Comment by cpeterso** [comment]
I will try to add this work in the next Fenix sprint.

The linked Jira issue: https://mozilla-hub.atlassian.net/browse/FNXV2-9012

**Comment by revad** [comment]
Will fixing this also fix this:
https://github.com/mozilla-mobile/fenix/issues/24637

**Comment by Rob--W** [comment]
This issue should be neverstale.

**Comment by flier268** [comment]
Any news?

**Comment by 9ary** [comment]
Please don't post comments asking about progress, as it sends everyone who's subscribed to this issue an email. If nothing was said here then there is no news.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810047

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
