### ISSUE TITLE
[Bug] Unable to find a query consisting of numbers and a dot

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16924]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the firefox browser
2. Search query consisting of numbers and a dot, for example 26.11.2020
### Expected behavior
The search engine displays the results associated with the query
### Actual behavior
No search occurs, nothing was found, and an inappropriate query appears in the address bar and a message "The connection has timed out. " is displayed
### Device information
Xiaomi Redmi Note 4X - Android 7.0
* Android device: yes
* Fenix version: firefox beta 84.0.0
 
![image](https://user-images.githubusercontent.com/66958331/101528293-2f892600-39a0-11eb-95c9-9568a6dfefb0.png)

**Comment by jowsey** [comment]
I suppose the solution here is checking if a suspected entered IP has four sections before classifying it as an IP instead of a query? I wouldn't really call this entirely a bug, even if it is an unexpected result for most users

**Comment by kbrosnan** [comment]
Duplicate #10516
