### ISSUE TITLE
[Bug] turna.com-The page freezes after search & not responding on tap 

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#16920]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the firefox browser
2. Tap on Incognito mode
3. On the homepage tap on the turna.com icon
4. Perform a search (for example Rijeka (RJK) to Instanbul Hepsi (IST)
5. Tap on Ucak Bileti Bul button
6. Repeat step 5
7. Tap on Gidis -Donus
8. Tap on Otobus Bileti
9. Tap on Ucak Bileti
10. Repeat step 5
11. Now tap on Settings wheel, menu (three dots), Otobus Bileti, Gidis -Donus, Ucak Bileti Bul button
### Expected behavior
The page turna.com should not freeze and become unresponsive on tap after the user has switched between options and perform a search couple of times.
### Actual behavior
The page turna.com freeze and become unresponsive on tap after the user has switched between options and perform a search couple of times.
### Device information
Google Pixel 2 - Android 11
Samsung J7 Prime -Android 6.0.1
* Android device: yes
* Fenix version: Firefox beta 84.0.0

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nighlty 210204.

### Devices used:
- Google Pixel 3 XL (Android 9)
- OnePlus 6T (Android 9)
