### ISSUE TITLE
[Bug] too much delay in tab closing and crash in nightly

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#16922]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Change tab view to grid
Open one tab and swipe to delete
Tab is not closed immediately and the message tab closed is showing after some seconds. Apart from this sometime it is crashing. This is happening since last few updates. Please fix this

### Expected behavior
Tab should close immediately 

### Actual behavior
Last tab closing after some delay.. Sometime crashing 

### Device information

* Android device: ? Rog 3 
* Fenix version: ? Latest nightly

**Comment by kbrosnan** [comment]
Related to the Nimbus work possibly? @jhugman

**Comment by quaintdev** [comment]
Yes this bug affects me as well and this does not resolve in the latest nightly as well.

**Comment by ekager** [comment]
Could you please go to about:crashes and get the link of the crash to put here?

**Comment by sheikh-azharuddin** [comment]
No crashes found but delay in UI response... Particularly when open operation is on home screen

Open setting, press back should go home screen with no tab...there is delay
Close last tab should go to home screen again there is too much delay
Switch to private mode or to normal mode from home screen using the icon, there is a black screen showing for few seconds

**Comment by miDeb** [comment]
Possible duplicate of https://github.com/mozilla-mobile/fenix/issues/16886, https://github.com/mozilla-mobile/fenix/issues/16852?

**Comment by sheikh-azharuddin** [comment]
Issue fixed in latest nightly

**Comment by csadilek** [comment]
If Nimbus issues caused this, this should be fixed in Nightly 201211 17:01 and newer.

**Comment by sheikh-azharuddin** [comment]
> If Nimbus issues caused this, this should be fixed in Nightly 201211 17:01 and newer.

Yes this is fixed to some extent but not fully

**Comment by opusforlife2** [comment]
Closing tabs is fixed for me in the build mentioned.

**Comment by sheikh-azharuddin** [comment]
Yes fixed now.....i was using yesterday morning build... My mistake.

Closing the case

Thanks Mozilla team and mozillians😊
