### ISSUE TITLE
[Bug] Advertising video autoplays when autoplay is blocked

### ISSUE THREAD

**Issue by JollyJohn54** [mozilla-mobile/fenix#16938]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Goto www.pprune.org
This defaults to the homepage https://www.pprune.org/trending.php
Select any thread on the forum

### Expected behavior
Advertising videos should be blocked with Site Permissions - Autoplay Block audio and video set.

### Actual behavior
An advertising video is visible under the first post that requires tap to play.
When scrolling down the page past the advert the advert reappears in a pop up.
Closing the pop up advert by tapping the X (top right) causes the initial advert to play on repeat which you can see by scrolling up. The audio is off.

### Device information
* Android device: OnePlus3. Android ver9. OxygenOS ver 9.0.6
* Fenix version: 83.1.0
 
![ChooseAnyThread](https://user-images.githubusercontent.com/75739118/101647200-5abb5600-3a30-11eb-97c0-85f2f60b2d68.jpg)
![AdvertBelowFirstPost](https://user-images.githubusercontent.com/75739118/101647216-5f800a00-3a30-11eb-927e-19e8e243d2e6.jpg)
![PopUpAdvert](https://user-images.githubusercontent.com/75739118/101647242-6575eb00-3a30-11eb-9fff-dcea3c85b48b.jpg)
![AdvertPlaysOnRepeat](https://user-images.githubusercontent.com/75739118/101647251-69097200-3a30-11eb-9d04-53e2458dfad8.jpg)

**Comment by Amejia481** [comment]
This will be addressed by https://github.com/mozilla-mobile/fenix/pull/16947

**Comment by Amejia481** [comment]
Are you able to reproduce in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) ? We did some improvement to the autoplay setting and I wasn't able to reproduce in nightly.

**Comment by AndiAJ** [comment]
Hi @Amejia481 , the autoplay works properly. (blocks the playback of the video)
On the other hand, it seems that **the media playback is triggered once the user taps the 'x' button** from the video.

**Comment by Amejia481** [comment]
Thanks, I will take a look!

**Comment by sheikh-azharuddin** [comment]
Issue is still there.. BEst visible in twitter page... While scrolling the pages you will notice flickering on the play button on the videos... If you will play one video the other videos will play automatically while scrolling... Though no audio.. Just the video plays

**Comment by JollyJohn54** [comment]
Hi,  Firefox updated itself to version 84.1.0 today and the problem exists in this version too.

Assuming that videos that have been watched have a higher value (and cost to the advertiser) than videos that are merely present on a page could this be some form of click fraud?   I don't know enough about this but it seems plausable.
