### ISSUE TITLE
[Bug] History Tab UI bug

### ISSUE THREAD

**Issue by Doctor-Abhi** [mozilla-mobile/fenix#16933]
Dark mode is not respected by the history tab switch. Its made its way from nightly to beta and now finally in release version too.

Device: Redmi K20 pro
OS: MIUI 12.0.5 STABLE xiaomi.eu
Fenix version: Nightly 201207 17:01, Beta 84.0.0-beta4 and 84.1.0rc-1
![Screenshot_2020-12-09-07-59-44-528_org mozilla firefox](https://user-images.githubusercontent.com/75193430/101566170-8e788a80-39f4-11eb-8d70-f34305b875fb.jpg)
![Screenshot_2020-12-09-07-59-50-441_com miui home](https://user-images.githubusercontent.com/75193430/101566180-93d5d500-39f4-11eb-8e59-cb0b0e4a46bd.jpg)

**Comment by sheikh-azharuddin** [comment]
I don't have this view... How did you get this?
I mean to access history only option is click 3 dot menu and then history which opens a separate page.. How did you get split screen view

**Comment by Doctor-Abhi** [comment]
> I don't have this view... How did you get this?
> I mean to access history only option is click 3 dot menu and then history which opens a separate page.. How did you get split screen view

All u have to do is go to site. Press the 3 dot menu. Brings up the page with front and back button at bottom. Long press the back button to access this page.
![Screenshot_2020-12-09-10-58-29-232_org mozilla firefox](https://user-images.githubusercontent.com/75193430/101588986-91cc4000-3a0d-11eb-8b67-c05d9741d037.jpg)
![Screenshot_2020-12-09-10-58-54-597_org mozilla firefox](https://user-images.githubusercontent.com/75193430/101588990-955fc700-3a0d-11eb-8b95-fa94c8ca4a74.jpg)

**Comment by sheikh-azharuddin** [comment]
Thanks bro... Was not aware of this.. 👍😊

**Comment by cadeyrn** [comment]
Duplicate of #16422.

**Comment by Doctor-Abhi** [comment]
> Duplicate of #16422.

It has been quoted various times but its not been looked at. I think 1 line of code can fix this, this is related to android components. As this is a UI bug end users are going to be affected, which further plummets down the Firefox's small userbase. I am in no way an expert on this but i think UI related bugs should take the top priority. People won't use if it doesn't look nice😄😄.

**Comment by cadeyrn** [comment]
> I think 1 line of code can fix this

Maybe you want to create a Pull Request if it's that easy? 😉

**Comment by Doctor-Abhi** [comment]
> > I think 1 line of code can fix this
> 
> Maybe you want to create a Pull Request if it's that easy? 😉

Sure. Right now I'm testing the changes on my pc, reverting them to back before things broke. Worked fine in 83.1.0. I'll close this issue and send a pull request.
