### ISSUE TITLE
Add copy link in long press of top site

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#16934]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently top site link/address cannot be copied to share over messaging app or mail without opening the site first.. Please add another option "copy link" when long pressing any top site

### How do you know that this problem exists today? Why is this important?
Link cannot be copied without opening the site

### Who will benefit from it?
Users who love top site feature

![Screenshot_20201209-104721540](https://user-images.githubusercontent.com/58127841/101588343-30f03800-3a0c-11eb-8d40-2b0caae3217e.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9025)

**Comment by Poopooracoocoo** [comment]
Look at all of the items in the desktop menu:
![image](https://user-images.githubusercontent.com/51363864/101599133-5b161a00-3a4d-11eb-8add-34d713e3c090.png)

You can even bookmark right from there! You can also easily bookmark _selected_ pages, instead of a whole window (neither of which are possible in Fenix!). Firefox unfortunately lost tab groups. 

I don't know why I bother upvoting and creating issues around here anymore.

**Comment by sheikh-azharuddin** [comment]
Wait but the issue is not fixed.....

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814117

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
