### ISSUE TITLE
Allow installation of arbitrary addons on Stable/Beta

### ISSUE THREAD

**Issue by arybczak** [mozilla-mobile/fenix#16940]
### What is the user problem or growth opportunity you want to see solved?

Currently you can only use arbitrary add-ons on Nightly (after a couple of extra steps such as enabling developer tools).

1) I don't want to use Nightly because it's unstable, I ideally want to use Stable (or at least Beta).
2) To install arbitrary add-ons on Nightly you need to do extra steps that are so well hidden that nobody will do them by accident. I have no idea why this is only for Nightly.

### How do you know that this problem exists today? Why is this important?

I personally need [UltraWideo](https://addons.mozilla.org/pl/firefox/addon/ultrawideo/) because it fixes https://github.com/mozilla-mobile/fenix/issues/8252.

I can't use UltraWideo with Stable, Nightly is unstable, so I'm forced to use the latest version of Fennec that might or might not have security issues.

I''m pretty sure there's more people like me. Do not force power users to choose between security issues and unstable browser, let us enable the possibility to install arbitrary add-ons in Stable.

### Who will benefit from it?

Every power user of the Firefox on mobile who is not interested in running unstable browser.

**Comment by kbrosnan** [comment]
This is better tracked by individual bugs about supporting the webextension APIs.

**Comment by arybczak** [comment]
I don't understand. This doesn't scale.

What do I have to do to get UltraWideo working with the new Firefox?
