### ISSUE TITLE
screen.orientation.lock does not lock

### ISSUE THREAD

**Issue by ab-unity** [mozilla-mobile/fenix#16943]
screen,orientation.lock does not lock the screen orientation

## Steps to reproduce
1. Open simple web page attached
2. Tap the Fullscreen button to enter full screen mode
3. Tap the Lock button to lock the screen to landscape position

### Expected behavior
If the screen is not landscape, the screen should rotate to a landscape-primary orientation and the Promise should resolve.  Then the screen orientation should be locked to that orientation so that rotating the device does not alter the screen orientation.

This is the behavior on Chrome for Android (tested Chrome 86).

### Actual behavior
If the screen is in a portrait orientation, then on pressing the Lock button, nothing happens.  Upon rotating the device to the landscape orientation, the screen rotates to match and the promise is then resolved.  The screen orientation is not locked, rotating the device back to a portrait behavior allows the screen to rotate back.

If the screen is already in a landscape orientation, then on pressing the Lock button, the promise is immediately resolved,  The screen orientation is not locked, rotating the device back to a portrait behavior allows the screen to rotate back.

### Device information
* Android device: Google Pixel 4 XL  (Android 11) and Galaxy Tab E (Android 7.1.1)
* Fenix version: 82.1.3 and 83.1.0 and Nightly 121208

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1681572

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
