### ISSUE TITLE
[Telemetry] Bookmark Counts

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#16941]
## Description & Product Manager / Data Scientist User Story

In https://jira.mozilla.com/browse/SDK-114, we want to collect the bookmark count in Fenix for the A/B Bookmarks experiment

## What questions will you answer with this data?

We are collecting this to ensure the success of the experiment referenced in https://jira.mozilla.com/browse/SDK-114.

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by gabrielluong** [comment]
We collect 2 different bookmark counts based on the where the bookmarks are placed within the folder structure - Desktop and Mobile. The bookmarks under within the folder of `Desktop Bookmarks` will make up the counts within the `desktop_bookmark_counts`.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 201216`** using a Google Pixel 3a (Android 11)

**1. ✔️ No Bookmarked items**
Ping `288d8ab5-dded-4516-9536-2d56fe6dcd90`

`"metrics.has_mobile_bookmarks":` **false**
`"mobile_bookmarks_count"` - **Not generated**
`"metrics.has_desktop_bookmarks":` **false**
`"desktop_bookmarks_count"` - **Not generated**


**2. ✔️ Mobile and Desktop bookmark items saved**
Ping `837310d1-b05e-4a49-9eb5-4a3dee1245bf`

**► Mobile - 5 items**
`"metrics.has_mobile_bookmarks":` **true**
`"metrics.mobile_bookmarks_count":` **5**

**► Desktop - 6 items**
Bookmarks Menu - 2 items
Bookmarks Toolbar - 2 items
Other Bookmarks - 2 items

`"metrics.has_desktop_bookmarks":` **true**
`"metrics.desktop_bookmarks_count":` **6**


**3. ✔️ Mobile and Desktop bookmark items saved in default folders and subfolders**
Ping `8faadd81-d3dd-4afa-ab65-8290d22d8d73`

**► Mobile - 7 items**
Default folder - 5 items
↳Subfolder 2 items

`"metrics.has_mobile_bookmarks":` **true**
`"metrics.mobile_bookmarks_count":` **7**

**► Desktop - 9 items**
Bookmarks Menu - 2 items
↳Subfolder - 1 item

Bookmarks Toolbar - 2 items
↳Subfolder - 1 item

Other Bookmarks - 2 items
↳Subfolder - 1 item

`"metrics.has_desktop_bookmarks":` **true**
`"metrics.desktop_bookmarks_count":` **9**

[Logcat](https://github.com/mozilla-mobile/fenix/files/5701333/bookCount.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t161200)
