### ISSUE TITLE
[Bug]Missing media notification icon on Android 11 devices

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#16958]
## Steps to reproduce
1. Play any video or song
2. Check the Android notification toolbar

### Expected behavior
A speaker icon should be displayed ![rsz_screenshot_20201210-095019](https://user-images.githubusercontent.com/51314259/101738088-547bb700-3ace-11eb-8c3e-e5a46f3e2445.png)

### Actual behavior
Nothing is displayed

### Device information

* Android device: 
• Google Pixel 3a (Android 11)
• Google Pixel 4XL (Android 11)

* Fenix version: Nightly 201210

**Comment by hakkikaancaliskan** [comment]
It's not even shown on Spotify. Are you sure that's a system behavior?

![Screenshot_20201211-003122_Trebuchet](https://user-images.githubusercontent.com/17825767/101832304-394d8d80-3b48-11eb-84f6-9fb7e37dd7d3.png)
![Screenshot_20201211-003103_Trebuchet](https://user-images.githubusercontent.com/17825767/101832310-3b175100-3b48-11eb-94e6-8939d5613f33.png)

Xperia XZ1 Lineageos 18 Android 11

**Comment by ekager** [comment]
@AndiAJ could you try with Chrome and see if they get an icon? If not, could just be new Android 11 behavior

**Comment by sflorean** [comment]
@ekager Tested on Chrome & Fenix RC 85.1.3 and the media icon is not displayed when watching youtube videos. However, on Fenix I got the icon displayed but then tapped on "close private tabs" notification, and the icon was dismissed as well.

**Comment by isthisrubble** [comment]
this appears to be an android 11 thing, not a firefox thing unfortunately (noticed change after android update)
