### ISSUE TITLE
FNX-472 ⁃ [Bug]No fill from clipboard for a link copied from imgur.com

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1695]
## Steps to reproduce
1. Go to imgur.com.
1. Tap the title of a post. Tap on "copy link"
1. Open a new tab, tap the address bar.
    1. Expected behavior
Fill link from clipboard option is shown.
    1. Actual behavior
No link from clipboard shown.
If you paste the link directly, it will work.
Other links copied from other sources (other apps, 9gag website) work.
    1. Device information

* Android device: Pxiel, Nexus 5
* Fenix version: 4/17.

**Comment by vesta0** [comment]
@sv-ohorvath this looks fixed. Please verify.

**Comment by sv-ohorvath** [comment]
I can still reproduce it on the 4/29 build:
![20190430_121027](https://user-images.githubusercontent.com/4037709/56951653-115f1100-6b41-11e9-8d37-40d7bd7d845e.gif)

**Comment by vesta0** [comment]
Strange that it works for me. We should investigate.

**Comment by ekager** [comment]
@sv-ohorvath can you still reproduce? I can't on master with Pixel

**Comment by sv-ohorvath** [comment]
We can still reproduce this on Pixel 3A, Pixel 3XL, Galaxy S8 (Android 9), Nexus 5 (Android 6.0.1) on Nightly 7/15.
It also happens copying the build date from taskcluster: tap the Created date to copy it (https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest)

**Comment by ekager** [comment]
In `ClipboardHandler.kt` after copying this link, `text` is returning `null` because the mime type is `text/html` not the expected `text/plain` - so we aren't even attempting to get the URL. I think if we open up the mime type this should work.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13220606 from 11/18** using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191118_103223](https://user-images.githubusercontent.com/51314259/69036806-418fd380-09ef-11ea-9a27-441f1a28997e.gif)
