### ISSUE TITLE
[Bug] Audio input device labels gotten by navigator.mediaDevices.enumeratedDevices() are empty

### ISSUE THREAD

**Issue by takahirox** [mozilla-mobile/fenix#16956]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Run the following in the console
```javascript
navigator.mediaDevices.getUserMedia({audio: true}).then(() => {
  navigator.mediaDevices.enumerateDevices().then(devices => {
    for (const device of devices)
      console.log(device);
  });
});
```

2. Allow audio device permission if a dialog appears
3. Check the results

### Expected behavior

Audio input devices and video input devices labels are non-empty.

### Actual behavior

Audio input devices labels are empty while video input devices labels are non-empty.

On Desktop/Android Chrome and Desktop Firefox the both labels are non-empty. So it may be Fenix specific problem.

### Device information

* Android device: Samsung Galaxy 8+
* Fenix version: Nightly 201203 17:01 (Build #2015779275)

**Comment by Amejia481** [comment]
Odd I'm not able to reproduce on Nightly 201208 17:06 (Build #2015780235), could be an OS specific issue? Which Android OS are you using?


![image](https://user-images.githubusercontent.com/773158/101795873-5ba6c300-3ad6-11eb-8bf2-691a965e367f.png)

**Comment by Amejia481** [comment]
Could you also post the GV version that you tested with ?

**Comment by takahirox** [comment]
I think you reproduced the problem. Audio input device label is empty in your screenshot.

**Comment by Amejia481** [comment]
Thanks for the clarification 👍🏽

**Comment by Amejia481** [comment]
I opened an issue for the GeckoView team to take a look https://github.com/mozilla-mobile/fenix/issues/16956

**Comment by padenot** [comment]
We can very quickly put non-empty strings, but we're not quite ready to do enumeration properly.

**Comment by flaviogrossi** [comment]
This seems to be still a problem, even though it should be fixed according to https://bugzilla.mozilla.org/show_bug.cgi?id=1681772

Can anyone confirm?
