### ISSUE TITLE
[Bug] Firefox crash and make the phone reboot when having access to a network

### ISSUE THREAD

**Issue by florencebiree** [mozilla-mobile/fenix#16965]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

I have the same problem on two case:

* with the network on, starting Firefox
* with the network off, starting Firefox. Everything is ok then I enable the network

### Expected behavior

Firefox is working, and the phone doesn't reboot.

### Actual behavior

The screen freeze for some seconds, then the phone reboot.

Here are two adb logcat session, one with the network on at the start:
https://gist.github.com/florencebiree/2bd45d972f6bb7ccd11b4da4737c2907
the other with Firefox working offline, and then the network activated:
https://gist.github.com/florencebiree/1abe0ebf95c03bb52809f1e5cfa59bb6

Both seems to end with the same error messages, makes me believe it's the same bug.

### Device information

* Android device: a Samsung Galaxy SII (armeabi-v7a), with LineageOS 17.1 (Android 10). It's an old phone, and an unofficial build of LineageOS, so I also reported this bug to the developer of the build, if the issue is to search on the system side.

* Fenix version: The problem occur with every Fenix version of Firefox (Fennec one's works very well). Here I tried with Firefox 84.1.0-rc.1.
 
Thank you for your work!

**Comment by kbrosnan** [comment]
I don't see the actual crash in your logcat. Your second one has no mention of Firefox at all. Did you do some trimming?

**Comment by florencebiree** [comment]
I didn't trim anything at the end, that's the last lines before the phone reboot. On my computer, adb logcat quit and I go back to my shell.

For the second one, I started to copy lines when I enabled the wifi, which makes firefox to crash. Here are all lines since the start of firefox : https://gist.github.com/florencebiree/9dc95617288e6dea4babe6128aaacbe6

I'm not an android developer, so if you have an idea to get more information about the crash, tell me and I can try to get them…

**Comment by ekager** [comment]
Thank you for your report! Do you see anything when you visit about:crashes? Could you link the associated Sentry/Crash Stats links here? :)

**Comment by florencebiree** [comment]
In about:crashes, it says no crash report was sent…

Looks like the reboot of the phone prevents the crash report system to run, isn't it?

**Comment by MicroBeast** [comment]
For FF Mobile, Crash Reports in Settings > About Firefox* > Crashes

**Comment by florencebiree** [comment]
I just tried that, it seems to be the same screen than about:crashes, still saying that no report was sent.
-- 
Florence Birée

10 déc. 2020 19:49:56 Andrian Andersen <notifications@github.com>:

**Comment by florencebiree** [comment]
Duplicate of #5663: after more digging to this problem, I find this closed ticket, and it's the same problem: the phone crash when firefox call `ip route get IP`. I can reproduce it in a terminal, so it's a lineageos problem, I'll see to make this fixed on this side…

Sorry for the noise, I'll close this bug.

**Comment by kbrosnan** [comment]
That was my suspect for the issue. Thanks for confirming that. If the owner of the ROM wants they can take https://github.com/LineageOS/android_kernel_cyanogen_msm8974/commit/f44b4b19da1541fce8440ffa1e59cdb722cf10b5 to stop the crashing for apps that use the netlink service.
