### ISSUE TITLE
[Bug] Cannot import CA / Content-Type "application/x-x509-ca-cert" not handled correctly

### ISSUE THREAD

**Issue by arminfuerst** [mozilla-mobile/fenix#16975]
## Steps to reproduce
Download a CA from a server responding with Content-Type "application/x-x509-ca-cert".

### Expected behavior
Being prompted to import this as a certificate authority and define the trust.

### Actual behavior
Being offered to download and just saving the file.
Workaround: Install a previous version using https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi and import the certificate using the old version of Firefox and upgrade to the recent version through the Play Store afterwards.

### Device information

* Android device: Reproducable on multiple devices and also with LineageOS 17.1
* Fenix version: 81.1.3 and 83.1.0 (and probably additional versions)

**Comment by kbrosnan** [comment]
Duplicate #2286. A workaround is to use beta or nightly. Open `about:config` set `security.enterprise_roots.enabled` to true and force quit Firefox so that Firefox restarts. Swipe closing is not good enough.
