### ISSUE TITLE
Choppy WebGL in some cases

### ISSUE THREAD

**Issue by ddarfantasy** [mozilla-mobile/fenix#16982]
## Steps to reproduce
Goto https://ciechanow.ski/cameras-and-lenses/
Drag this animation:
![Screenshot_20201212-015845__01](https://user-images.githubusercontent.com/75518399/101938616-9d428580-3c1e-11eb-91e9-df9126998200.jpg)

### Expected behavior
It moves seamlessly as chrome does.
### Actual behavior
It is choppy.
### Device information

* Android device: One Plus 7T Android 10
* Fenix version: 83

**Comment by mcomella** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1682986

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by sefeng211** [comment]
Hey! Can you collect a profile by following https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=setup?

**Comment by mstange** [comment]
I've captured a profile.
