### ISSUE TITLE
[Bug] Play/pause youtube video from headphones stopped working

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#16988]
## Steps to reproduce
Plug any jack/usb c headphones that have play/pause button.
Open a youtube video.
Click the phisical pause button on the headphones.
### Expected behavior
Video pauses
### Actual behavior
Video does not pause
### Device information

* Android device: OnePlus 5t
* Fenix version: Nightly. It's a regression. It worked fine a few days ago. It works fine in Beta and Stable.

**Comment by rocketsroger** [comment]
This is due to the latest Nightly integration of the new `MediaSession` API.  The fix will be needed in Android Components.

**Comment by rocketsroger** [comment]
This should be fixed on Nightly for Dec 18th.  Please verify.  Thanks!

**Comment by andreicristianpetcu** [comment]
It's fixed. Thank you. Closing.

**Comment by softvision-miralobontiu** [comment]
I confirm that the issue is fixed on OnePlus 5T (Android 10) on the 2/3 Nightly build.
I'll remove the qa:needed label.
