### ISSUE TITLE
[Bug] Canceled first PDF download prevents following attempts from downloading

### ISSUE THREAD

**Issue by zw3n** [mozilla-mobile/fenix#16998]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Clear cache
2. Open a link to a PDF. Example: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
3. Press `X` in the pop-up to cancel the download
4. Open the link again

### Expected behavior
The pop-up dialog asking if I want to download shows

### Actual behavior
The progress bar stops around ~25% and the pop-up dialog does not show

#### Device 1
* Android device: Sony, Android 10
* Fenix version: 83.1.0, 84.0.0-beta.4

#### Device 2
* Android device: Sony, Android 6.0.1
* Fenix version: 82.1.3

**Comment by Amejia481** [comment]
I filed a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1687540) for the geckoview team to take a look, as after debugging I noticed we are not getting the `onExternalResponse` event after the first load, the page doesn't finish loading it gets stuck in 15 percent https://bugzilla.mozilla.org/show_bug.cgi?id=1687540.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 3/3.
