### ISSUE TITLE
How to import CA certs 

### ISSUE THREAD

**Issue by damionx7** [mozilla-mobile/fenix#16993]
I have added CA cert in android but how do I import it in fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9066)

**Comment by abodea** [comment]
Thank you for this report, can you add more information regarding this issue/feature request?

**Comment by damionx7** [comment]
I guess one could import certificates in firefox mobile as this link explains how to do it. 

https://blog.felixbrucker.com/2015/10/27/how-to-import-your-own-ca-cert-into-firefox-on-android/

I tried it in fenix, but failed to do so. How can one import certificate authority in fenix ?

**Comment by ezaquarii** [comment]
@abodea There is not much to explain here. Somebody decided to hide/block/remove ability to import user CA certificates on mobile browser. This feature is indispensable in any enterprise environment.

**Comment by ezaquarii** [comment]
@abodea The user have `ca.crt` CA certificate file for the organization's network. To access any site secured with private certifcate, the CA must be imported and trusted.

This is very frequent scenario for any enterprise environment and I truly cannot comprehend why this feature has been removed or hidden in Fenix.

Running development or beta is not a solution for this problem.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1358996

**Comment by deosrc** [comment]
Thansk to [this comment](https://github.com/mozilla-mobile/fenix/issues/19945#issuecomment-858754897), I've found something that seems to work.

1. Import your CA certificate into Android as normal
1. Go to firefox settings
2. Scroll to the bottom and open "About Firefox"
3. Tap the firefox logo until you get a toast saying developer options are enabled
4. Go back to the settings menu and open "Secret Settings"
5. Ensure "Use third party CA certificates is enabled
6. Restart firefox

All of the steps may not be required. This also may change some other settings affecting the security of your browser so use with caution.

**Comment by Scrumplex** [comment]
It looks like this does not work for custom CAs installed into the system store?

**Comment by deosrc** [comment]
> It looks like this does not work for custom CAs installed into the system store?

Long time since I've looked at this so not sure how I installed the cert (wish I'd been more specific than "as normal"). I have a CA cert installed to the user store (Settings > Security & Lock Screen > Encryption and credentials > Trusted credentials > User). I think I just used "Install a certificate" at Settings > Security & Lock Screen > Encryption and credentials.

Android 11
Oxygen OS: 11.2.9.9

**Comment by nroach44** [comment]
Can confirm, if you install it into the system store (either by modifying the installed OS, or when building the OS) Firefox will not sync with or load servers that use the cert.

The only thing I've found that works for all cases is 
- Install the certificate in the user-level settings
- THEN install it in the system

This works for Firefox (Cert must be in user store) and some other frustrating apps that don't trust the user store

**Comment by kbrosnan** [comment]
Use third party CA certificates is the way to do this in Firefox.
