### ISSUE TITLE
FNX-5193 ⁃ Remove incomplete options from Settings

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1699]
We want to remove incomplete features from Settings for Beta:

Passswords
Credit Cards and addresses
Accessibility

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest version of Fenix 1.0.1916 (Build#11080612), with Samsung Galaxy Tab S3 (Android 8.0), HTC Desire 820 (Android 6.0.1), and Samsung Galaxy S8 (Android 9.0).
