### ISSUE TITLE
[Bug] Can't select from dropdown in AMO in Mobile mode

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#16996]
## Steps to reproduce 
Go to any extension page for example https://addons.mozilla.org/en-US/firefox/addon/youtube-nonstop/
Log in.
Scroll down and tap on 'Select a colection'

### Expected behavior
Colection list is ready for selection like in Chromium
![Screenshot_20201212-133633_Ungoogled_Chromium](https://user-images.githubusercontent.com/922368/101983205-16bf8f80-3c82-11eb-851e-c5e0b0fbefa7.png)

### Actual behavior
Selection is not shown
![Screenshot_20201212-133719_Firefox_Nightly](https://user-images.githubusercontent.com/922368/101983238-5d14ee80-3c82-11eb-92e9-42efaa960c42.png)

### Device information

* Android device: OnePlus5t
* Fenix version: Nightly but it's not relevant. This never worked since the Fenix rewrite.

**Comment by andreicristianpetcu** [comment]
This actually works on desktop mode Fenix. This makes me think it's a Fenix issue, not a webcompat or amo fe issue.
![Screenshot_20201212-140136_Firefox_Nightly](https://user-images.githubusercontent.com/922368/101983275-b2e99680-3c82-11eb-9932-f96d6f6866c7.png)
![Screenshot_20201212-133701_Firefox_Nightly](https://user-images.githubusercontent.com/922368/101983283-bf6def00-3c82-11eb-9fde-1e5a99bc4525.png)

**Comment by bb010g** [comment]
I can reproduce this.

**Comment by lindongbin** [comment]
#16146

**Comment by andreicristianpetcu** [comment]
@lindongbin That is like the oposite of this. I can't change language in monile mode but I can in desktop mode.

**Comment by Amejia481** [comment]
Thanks for filing the issue, there is already an issue for it https://github.com/mozilla-mobile/fenix/issues/16399#issuecomment-741811669 we opened an issue for the gv team to take a look at it.
