### ISSUE TITLE
[Bug] Search engines reset during major version updates

### ISSUE THREAD

**Issue by chaserene** [mozilla-mobile/fenix#16997]
## Steps to reproduce
my custom search engines were often lost and the search engine list reset to the default when I updated across multiple major versions (e.g. 60->63), sometimes even across a single major version (e.g. 63->64). these version numbers are just examples because I never documented the behavior, and therefore I also don't know how consistently reproducible this is. but now with a recent update (68.12.0->83.1.0) it happened again and I am documenting it here.

### Expected behavior
search engines added by the user and search engine ordering shouldn't be removed by a software update.

### Actual behavior
they are reset.

### Device information
* Android version: Android 9
* Fenix version: 68.12.0 (Fennec) -> 83.1.0 (Fenix)

**Comment by ekager** [comment]
When we upgraded from Fennec to Fenix, these were entirely different apps with complex migration code and we did not choose to migrate custom search engines. If you see this again, feel free to open a new issue

**Comment by chaserene** [comment]
> we did not choose to migrate custom search engines.

please don't take this so lightly. deleting user data, even so without letting the user know and not offering a way to back it up, should not be standard developer practice.
