### ISSUE TITLE
Search bar floating after closing keyboard

### ISSUE THREAD

**Issue by indahud** [mozilla-mobile/fenix#16995]
## Steps to reproduce
1. Enter something in the searchbox
2. Press back button to close keyboard
### Expected behavior
Searchbox should come down when keyboard closed.
### Device information

* Android device: Nokia 6.1 Plus
* Fenix version: 83.1.0
 
![firefox](https://user-images.githubusercontent.com/47686324/101982460-f4227c00-3c6b-11eb-8286-76fb4e2e9b3e.png)

**Comment by ekager** [comment]
Can you reproduce on nightly?

**Comment by indahud** [comment]
Yes I can reproduce it on nightly.

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the 6/24 Nightly 91.0a1 build with Google Pixel (Android 10), nor with Sony Xperia Z5 Premium (Android 7.1.1).
@indahud could you retest with your device?
Thank you!
