### ISSUE TITLE
Esni flag missing 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#16991]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open about:config
Search for the feature "network.security.esni.enabled" 
It is no longer available 

### Expected behavior
The feature should be available to set it to True for users who want encrypted-sni

### Actual behavior
This feature flag no longer available but available in beta version and desktop version. Seems removed recently 

### Device information

* Android device: ? Rog3
* Fenix version: ?latest nightly

**Comment by MicroBeast** [comment]
Maybe related to https://bugzilla.mozilla.org/show_bug.cgi?id=1500289

All ESNI issues here were closed and pointed to that issue.

**Comment by amedyne** [comment]
Closing this to refer to the bugzilla ticket.

**Comment by cadeyrn** [comment]
ESNI is no longer a thing, it was replaced by ECH, see https://blog.mozilla.org/security/2021/01/07/encrypted-client-hello-the-future-of-esni-in-firefox/.
