### ISSUE TITLE
[Bug] "Fill link from clipboard" has too little whitespace/padding

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#16992]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Copy link to clipboard
2. tap address bar

### Expected behavior

The leading/left spacing for the "Fill link from clipboard" tip is aligned to the address bar and scan options.

### Actual behavior

The left spacing is right up against the left side of the screen.

![image](https://user-images.githubusercontent.com/152493/101976797-e262b980-3c16-11eb-957a-41ab5623c3f7.png)

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 201211 17:01 (Build #2015780811)
AC: 70.0.20201210195250, 2bfbebc6c
GV: 85.0a1-20201210092800
AS: 67.2.0

**Comment by sflorean** [comment]
Verified as fixed on Nightly 12/16 with Pixel 3(Android 11).
