### ISSUE TITLE
FNX-5195 ⁃ [UX] Account (Features e.g. Sync)

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#170]
GH issue to track design work. Ryan Feeley is working on this but shorlander will coordinate. 

User stories in Meta

**Comment by vesta0** [comment]
Need UX feedback from Ryan.

**Comment by ryanfeeley** [comment]
Hi @vesta0 I am back from PTO. I have duplicated @brampitoyo’s settings section and will aim to complete Fenix account/sync UX this week with guidance from @shorlander

**Comment by lime124** [comment]
closing in favor of using just one ux ticket to track Ryan's work. please see #169
