### ISSUE TITLE
[Bug] Two finger pinch-to-zoom can be triggered with one finger

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#17007]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open any page that allows zoom
2. Put one finger on the screen
3. Lift the finger
4. Put the same finger again on the screen and hold it
5. Move the finger without lifting it
6. Retry a few times to reproduce the bug

### Expected behavior
Double finger gestures should never be triggerable with one finger. I'm not sure if only pinch-to-zoom is affected by this.

### Actual behavior
See video:
https://www.dropbox.com/s/iqkmeybndyezdzr/2020_12_13_18_10_58.mp4?dl=0

Notice that only one figer is ever on the screen in the video.

### Device information

* Android device: Samsung Galaxy J7 2017
* Fenix version: 83.1.0 and todays (13.12.2020) nightly

**Comment by Dunexus** [comment]
Double tap + hold and swipe to zoom is a common one hand gesture to zoom. It is used in other browsers too.

**Comment by Mikaka27** [comment]
Hi, so it works as intended? I cannot trigger this at all in chrome browser.

**Comment by Dunexus** [comment]
Hi,
I tried in chrome and i was able to trigger this gesture but it require the taps to be quick (more like a double tap and hold).

**Comment by Mikaka27** [comment]
I'm closing it if you say that's not a bug.
