### ISSUE TITLE
Crash in [@ java.lang.RuntimeException: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java)]

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla-mobile/fenix#17004]
Crash report: https://crash-stats.mozilla.org/report/index/b1627bcc-fdef-4409-bee5-8d4f30201213

Java stack trace:
```
java.lang.RuntimeException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by ekager** [comment]
Do you have any known STR? unfortunately the stack is not very helpful

**Comment by lobontiumira** [comment]
@alex-mayorga did you encounter this crash again?
Do you have some steps to reproduce the crash?
Thank you!
