### ISSUE TITLE
Hepsiburada.com-The phone back button is unresponsive when you tap on it for the first time

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/fenix#17003]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open firefox beta
2. Search hepsiburada.com
3. Tap on a product 
4.Tap phone back button once to go back
### Expected behavior
It takes you back to homepage
### Actual behavior
After you tap on it the first time nothing happens unless you double tap the back button
### Device information
Tecno Camon 11 - Android 8.0
Huawei P20 lite -Android 10.0
* Android device: yes
* Fenix version: firefox beta 84.0

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible Firefox Preview Nighlty 201216 (Build #2015781675).

### Devices used:
- OnePlus6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by hakkikaancaliskan** [comment]
This issue can be closed: https://github.com/webcompat/web-bugs/issues/66888
