### ISSUE TITLE
FNX-5196 ⁃ Remove Downloads from Quick Action Bar

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1700]
We want to remove incomplete features from the Quick Action Bar for Beta

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Fenix version 1.0.1916 (Build#11080612), with Samsung Galaxy Tab S3 (Android 8.0), and HTC Desire 820 (Android 6.0.1).
