### ISSUE TITLE
[Bug] User avatars/images not loading if tab is started in background

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#17009]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to wykop.pl (polish equivalent of reddit.com)
2. Scroll to some link
3. Hold finger on it
4. Open it in new tab
5. Wait a few seconds on current tab
6. Switch to new tab

### Expected behavior
User avatars and images in comments are not loaded (ads are excluded from this behaviour)

### Actual behavior
See video:
https://www.dropbox.com/s/ulpwtswj7965r4c/2020_12_13_19_09_19.mp4?dl=0

I move a finger on the left of "saviola7" user where avatar should be visible. After I reload the page (and I stay on tab until it reloads), everything is fine.
I saw this problem on fenix preview, it's not happening on fennec android.
Desktop firefox is also fine, no issue there.

### Device information

* Android device: Samsung Galaxy J7 2017
* Fenix version: 83.1.0 as well as todays (13.12.2020) nightly

**Comment by Mikaka27** [comment]
Just checked and this issue also reproduces on reference browser.

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the 3/15 Nightly build using a Sony Xperia Z5 Premium (Android 7.1.1).
