### ISSUE TITLE
Gesture to close tab and move to next

### ISSUE THREAD

**Issue by CarlosRuiz-globalqss** [mozilla-mobile/fenix#17018]
At this moment closing an already read tab is a process of three clicks:
* I need to click on the tab counter
* close the tab with the close button or swiping
* and then click on the new tab that I want to read

My ideal world would be to have a one simple gesture or button to close my already read tab and move automatically to the next tab (not to the "new" tab unless the closed is the last one)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9090)

**Comment by s-ankur** [comment]
There is a way to do it in two:
Long press on the tab counter
Click close tab

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @s-ankur - didn't know about the long-press, that's a good option, a gesture would be faster but I'm OK with the long press option.
