### ISSUE TITLE
pdf.js does not work since ~Dec 4

### ISSUE THREAD

**Issue by JoGarWeb** [mozilla-mobile/fenix#17011]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I know that this addon can be installed optionally and to some extent only for testing. But this addon worked well until December 4, and I think it is important to report it, even more if someday you want to have a full support of extensions. 

## Steps to reproduce
Use Firefox Nightly some compilation after December 04 
Install this custom Add-On [Android PDF.js](https://addons.mozilla.org/en-US/android/addon/android-pdf-js/)
Restart your Browser
Find some webpage who has a PDF [like this page ](https://portalweb.uacm.edu.mx/uacm/Portals/2/Apoyos/ConvocatoriaPermanenteInternet.pdf)

### Expected behavior
The Add-on works fine 
Screenshot of  Firefox Nightly Nightly 201203 17:01 (3rd December Build) 

![Screenshot_20201213-212745](https://user-images.githubusercontent.com/7904563/102037207-3cd05700-3d8a-11eb-862f-c94b578242dc.png)

![Screenshot_20201213-213510](https://user-images.githubusercontent.com/7904563/102038196-3d69ed00-3d8c-11eb-988e-594f0d64aef2.png)

### Actual behavior
The Add-On can't complete request 
Screenshot of Firefox Nightly Nightly 201213 17:01 (13rd December Build) But happens since December 4th Build

![Screenshot_20201213-214344](https://user-images.githubusercontent.com/7904563/102038238-5e324280-3d8c-11eb-9eb3-bee027f2c61f.png)

![Screenshot_20201213-214349](https://user-images.githubusercontent.com/7904563/102038249-625e6000-3d8c-11eb-9ff3-0e510c29746f.png)

### Device information

* Android device: Android 10
* Fenix version:  Firefox Nightly Nightly 201204 17:01 (And above)

**Comment by Gabriel85** [comment]
It's working again with latest nightly! Can be closed..
