### ISSUE TITLE
Always show progress bar even when address bar is hidden

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#17010]
### What is the user problem or growth opportunity you want to see solved?
User currently cannot see progress bar when he clicks on some link and address bar is hidden.

### How do you know that this problem exists today? Why is this important?
You don't know if you successfully clicked on a link, or you missed.

### Who will benefit from it?
Everyone

Currently if you click on a link and address bar is hidden you see this:
![Screenshot_20201213-192909_Firefox Nightly](https://user-images.githubusercontent.com/9214100/102020523-038feb00-3d7a-11eb-8099-97192eaff9e1.jpg)

You don't know from this that some link is currently loading. I believe that it should look like this when address bar is hidden (progress bar is always visible):
![PageWithProgress](https://user-images.githubusercontent.com/9214100/102020662-f8898a80-3d7a-11eb-876c-0d34f8a90e72.jpg)

**Comment by kbrosnan** [comment]
Using Nightly I get the address bar on navigation on Reddit would you please check https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by Mikaka27** [comment]
Hi, I do get address bar on nightly too. But progress bar does not display during loading.

**Comment by Mikaka27** [comment]
Address bar is extending automatically with progress bar on firefox 84. Should I close this ticket or do we keep it as alternative idea (only progress bar visible)?

**Comment by ekager** [comment]
Let's close this ticket for now. Thanks @Mikaka27 !
