### ISSUE TITLE
[Bug] Scrollshot of tab tray not working

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#17028]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Open enough tabs so you have to scroll the tab tray to see them all
- Take a scrollshot of the tabtray

### Expected behavior
I can make a screenshot of all my open tabs

### Actual behavior
It appears to work at first, but the actual screenshot only shows the tabs you can see on the screen at once. It used to work great before

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 201213 17:01 (Build #2015781195)

**Comment by sflorean** [comment]
I was able to reproduce this on latest Nightly with Samsung Note 10(Android 11).
