### ISSUE TITLE
[Bug] Increased errors for startup.timeline.framework_start

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/fenix#17022]
Since 2020-12-05 we're seeing an increase for the `startup.timeline.framework_start` metric in both raw error counts and affected clients for the `InvalidState` error (see graph in the details).

<details>

![image](https://user-images.githubusercontent.com/2129/102104234-3a273d80-3e2e-11eb-859e-321d31d2ead9.png)

</details>

It seems the only code path this is set is in [`StartupFrameworkStartMeasurement.kt`](https://github.com/mozilla-mobile/fenix/blob/95860eba499bf9a456092f1f84c5073dabc6da89/app/src/main/java/org/mozilla/fenix/perf/StartupFrameworkStartMeasurement.kt#L58) using `setRawNanos`.

[Our docs](https://mozilla.github.io/glean/book/user/metrics/timespan.html#recorded-errors) are currently missing that, but this might be due to it being set multiple times, at which point new values are discarded.
Did something change recently in how often this value is trying to be recorded?

**Comment by kbrosnan** [comment]
Could be linked to Nimbus? @csadilek @jhugman

**Comment by csadilek** [comment]
Hm tagging @mcomella who knows `StartupFrameworkStartMeasurement` best and @travis79 who knows both Glean and Nimbus to see if anything comes to mind?

**Comment by mcomella** [comment]
I noticed we don't include `client_id`s in this ping: I wonder if that's at all related. https://searchfox.org/mozilla-mobile/rev/8fc8e15bfb0a8671ee0ad5780a4e2fe4f05662d4/fenix/app/pings.yaml#41

Triage: we're not actively working on this probe so moving to low impact.

**Comment by mcomella** [comment]
We're removed `startup.timeline` in #20596 so closing this.
