### ISSUE TITLE
[Telemetry] Sharing a screenshot

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#17023]
## Description & Product Manager / Data Scientist User Story
As a product manager, I want to better understand all the ways people capture and share content in Fenix, so we can make enhance their experience. 

## What questions will you answer with this data?
- How often users take a screenshot (Android function) of a page that's open in Fenix (assuming that they are taking a screenshot as a way to share that content with themselves (save for later) or with others. 

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by mcarare** [comment]
@vesta0 AFAIK There is no reliable way to "listen" to a screenshot being taken by the user. Even the notification for when taking a screenshot is not allowed is handled by Android. We do not have any callbacks that could help us get notified of an attempt to take a screenshot. 

So, outside of implementing our one feature that takes screenshots of the web page content and adding metrics for that feature usage, I do not think we have any means to implement this telemetry.

**Comment by bifleming** [comment]
@csadilek any thoughts on this?

**Comment by csadilek** [comment]
Yes, there's no built-in API to listen for screenshots. We could investigate using a `FileObserver` or `ContentObserver` to look for screenshots being written while the app is active, but that's quite a bit of complexity with various edge cases. So, I think it depends on how important we consider this telemetry and if it's worth doing this.
