### ISSUE TITLE
[Bug] Unable to scroll the page

### ISSUE THREAD

**Issue by ddarfantasy** [mozilla-mobile/fenix#17024]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open https://www.zhihu.com/question/434705534 in desktop mode.
Wait until the page is full loaded.
### Expected behavior
I can scroll the page.
### Actual behavior
I can't scroll the page.
### Device information

* Android device: OnePlus 7T
* Fenix version: 83

**Comment by kbrosnan** [comment]
This works for me using Firefox for Android 83, Nightly 85 and Geckoview example using a Galaxy S6 and a Pixel 3.

**Comment by ddarfantasy** [comment]
@kbrosnan ...Well, I can provide a video tomorrow, if time permitting.
Additional info: Https everywhere and ublock origin is enabled. ETP is enabled too.
I haven't tried nightly version yet, sorry about that.

**Comment by ddarfantasy** [comment]
No longer reproduceable...
