### ISSUE TITLE
[Bug] Firefox/System crash accessing webpage with video elements loading multiple codecs (?) 

### ISSUE THREAD

**Issue by jlax** [mozilla-mobile/fenix#17034]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Currently working on a new project that is about to launch. Realized one of our web pages is causing Firefox and the Android System UI to crash. I used Firefox USB Debugging to use the inspector, no errors in the console, but the inspector becomes unusable after the crash as the Firefox USB debugger can no longer connect with Firefox on the phone. 

About the web page: marketplace containing ~25 `<video>` elements loading videos of varying codecs. Happy to share the link privately with a developer.

## Steps to reproduce

Navigate to webpage. 

### Expected behavior

Webpage loads without issue, as it does on Firefox Desktop.

### Actual behavior

Firefox crash, System UI crash. Not clear if one is causing the other or in which order. 
[firefox_crash_2.txt](https://github.com/mozilla-mobile/fenix/files/5691528/firefox_crash_2.txt)

### Device information

* Android device: Pixel 2 XL, Android 11, Build RP1A.201005.004
* Fenix version: 83.1 Build 2015776403

**Comment by jlax** [comment]
Forgot to attach a second log. Same incident, separate attempt to load the page.

[firefox_crash.txt](https://github.com/mozilla-mobile/fenix/files/5691598/firefox_crash.txt)

**Comment by sando240** [comment]
Same issue I am facing on mobile firefox for my website.
I want to embed video in it but unable to.Because my endusers are mostly using Firefox. WHich cause crashing.

Here is my webiste. [https://teerresultinfo.com/teerresulttoday/]

**Comment by lobontiumira** [comment]
@jlax could you help us with the link on which this issue occurred?
Also, are you able to reproduce this on the latest Firefox build?

**Comment by privilegejunkie** [comment]
So I'm pretty sure I have been seeing this almost daily. Easily reproducible when browsing the reddit mobile site when there is a lot of video content.

**Comment by lobontiumira** [comment]
Hi @privilegejunkie 
I tried reproducing your crash on the latest RC build Firefox 87.0.0, using a google Pixel (Android 10), but I couldn't.
I spent several hours on reddit.com playing multiple videos, yesterday and today, but everything worked as expected.
We will try to reproduce it with an Android 11 device.

**Comment by abodea** [comment]
Hi @privilegejunkie!
Thank you for this report!

I was not able to reproduce this issue on **RC**, **Beta**, or the latest **Nightly** build from 3/31/21 with Google Pixel 4 XL (Android 11).
I use the android 11 for many months but I never had an issue like this on video elements.
Can you please send me the website via email in order to test the exact scenario? 

My email: abodea@mozilla.com
