### ISSUE TITLE
FNX-5199 ⁃ [Bug] Library menu top toolbar is blue after a multiple-selection of bookmarks

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1703]
## Steps to reproduce
1. Long press to select one ore more bookmarks.
1. Open them in new tabs.
1. Open the library menu.
    1. Expected behavior
Library menu looks normal.
    1. Actual behavior
The toolbar is blue.
    1. Device information

* Android device: Pixel, Nexus 5.
* Fenix version: 4/17
![Screenshot](https://user-images.githubusercontent.com/4037709/56300300-5a28ca00-613e-11e9-9b0e-111d7c098185.png)UNITO-UNDERSCORE!20190417-111207!

**Comment by kbrosnan** [comment]
Looks like code landed so this should be fixed.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 4/29 build.
