### ISSUE TITLE
Firefox for Android doesn't scroll on certain websites

### ISSUE THREAD

**Issue by shakeelosmani** [mozilla-mobile/fenix#17037]
## Steps to reproduce
Please visit https://electjon.com/ on firefox for Android and see if you can scroll the website. This not scrolling behavior is true for so many sites with firefox for Android. In fact that's the reason I have to occasionally use Chrome

### Expected behavior

Site content is long should I should be able to scroll up and down

### Actual behavior

Where as it doesn't scroll at all
### Device information

* Android device: ?Yes (Samsung Galaxy s10e) Android 10
* Fenix version: ?
83.1.0 (Build #2015776403)
AC: 63.0.9, fc54c566e
GV: 83.0-20201112153044
AS: 63.0.0

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1682414

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by agi** [comment]
@shakeelosmani is this still reproducing? I can't reproduce on the same phone  / version.

**Comment by ekager** [comment]
When I moved to Bugzilla I could repro, but I can't anymore. Sounds like it was the site's issue

**Comment by shakeelosmani** [comment]
Yes that is correct. Unable to reproduce the issue anymore.
