### ISSUE TITLE
[Bug] Address bar appears suddenly, which is not expected.

### ISSUE THREAD

**Issue by Armoree** [mozilla-mobile/fenix#17031]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to jd.com and choose an item. (As a example, https://item.m.jd.com/product/100007080931.html?_fd=jdm&cover=jfs/t1/123363/4/6697/348525/5f058ffcEeca31b7f/fd109966191c7a06.jpg&ptag=138561.2.1) Make the address bar hidden and select item types. Touch on the x button.
### Expected behavior
The address bar shouldn't show up when close button is hitted.
### Actual behavior
It suddenly appears and makes the whole page move downwards. A screenshot:
![GIF-201215_014417](https://user-images.githubusercontent.com/76005377/102117898-e0e4fb80-3e79-11eb-9aba-2485b9d3d91e.gif)

### Device information
Xiaomi Mi 8 SE, Android 10
* Android device: YES
* Fenix version: 83.1.0

**Comment by Mikaka27** [comment]
Hi I see this problem [here](https://forum.dobreprogramy.pl/t/czym-sie-rozni-samsung-galaxy-m31-s-od-m-31/630107) 

Scroll down and stop. Then address bar appears by itself.

**Comment by Armoree** [comment]
@Mikaka27 Yes many sites seem to have the same problem. I feel that the bug often occurs when a webpage shows, above the whole page, a new layer with buttons/checkboxs on it. The bug have existed long before Fenix.

**Comment by palerdot** [comment]
Firefox mobile behaves inconsistently in showing/hiding navbar when interacting with a canvas on the page. For example, if there is a canvas on the page and the user tries to draw on it with touch, firefox mobile keeps flickering the navbar and the user cannot draw on the canvas in the page. Same behaviour works flawlessly with chrome, where the navbar hiding logic does not interfere with user touch events like drawing on canvas.

Above mentioned behavior also interferes with modal, when the user tries to touch scroll within the modal, the body flickers with navbar appearing in and out of the view ...

PS: This comment was originally made here - https://github.com/mozilla-mobile/fenix/issues/1984#issuecomment-696742205

**Comment by Mugurell** [comment]
Thank you for the report!
We'll investigate.

**Comment by sflorean** [comment]
@Armoree this is still reproducible for you?

**Comment by Mikaka27** [comment]
For me this is still happening.

**Comment by Mugurell** [comment]
@Mikaka27 Can you please open a new ticket with a video showing the issue and details about the Firefox version and the website in which you are encountering it?
I think that may be a separate issue than the one from here.

**Comment by Mugurell** [comment]
Testing the initial issue in GVE and in Kiwi I see that indeed we are showing the toolbar while Kiwi doesn't.
Moving to Bugzilla for more investigations.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1723485

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
