### ISSUE TITLE
[Bug] Nightly doesn't retain "Desktop site" switch for links opened in new tabs

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#17035]
Firefox Nightly on Android (perhaps all Fenix releases?) doesn't retain "Desktop site" switch for links in the same domain that are opened in new tabs.

## Steps to reproduce

Set "Desktop site" on for your tab, and then open a link within the same domain into a new tab.

### Expected behavior

Tabs in the same domain (that has been designated as "Desktop site" for the session should also be opened as "Desktop site".

### Actual behavior

Nightly doesn't retain "Desktop site" switch for tabs opened in new tabs, reverting the setting back to off.

There is some question whether _all_ new tabs should open in "Desktop site" mode or whether just tabs in the _same_ domain should be. That should be the baseline minimum, however.

### Device information

* Android device: Xiaomi Mi A1 / Pixel Experience 10
* Fenix version: Nightly 201211 17:01 (Build #2015780811)

**Comment by kbrosnan** [comment]
Duplicate #2091
