### ISSUE TITLE
[Bug] Updates to enterkeyhint don't take effect until the next time the text field is focused

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#17046]
## Steps to reproduce
1. Visit https://jsfiddle.net/06dopzac/4/show on Firefox Nightly on Android.
2. Tap focus on the text field.
3. Type some text.

### Expected behavior
The symbol on the enter key should change from "enter" to "send" as soon as any text has been entered into the text field.
### Actual behavior
The symbol on the enter key doesn't change unless one unfocuses and refocuses the text field.
### Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 15/12.**

Notes:
The source code of the sample can be viewed at https://jsfiddle.net/06dopzac/4.
This issue also occurs when setting mozactionhint dynamically. The sample works as expected on Chrome.
[Bugzilla bug.](https://bugzilla.mozilla.org/show_bug.cgi?id=1670129)

![ezgif-4-50bf0cfb3789](https://user-images.githubusercontent.com/42831109/102222580-4671d000-3eec-11eb-8a5c-403b2ad757aa.gif)

**Comment by makotokato** [comment]
This is Gecko/GV issue.  We should reopen BMO bug.
