### ISSUE TITLE
Too much padding in address bar

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17042]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open any site such as twitter which has videos and shows the autoblock option in address bar

### Expected behavior
There should not be much padding between security lock icon and the URL or between lock icon and block icon

### Actual behavior
There is too much padding between security lock icon and the website URL.. This feels like https/www/http was removed but the space left! 
This is more prominent with the autoblock media icon

### Device information

* Android device: ? Rog3 
* Fenix version: ? Latest nightly 

![Screenshot_20201215-101502297 (1)](https://user-images.githubusercontent.com/58127841/102172542-fa5c6680-3ebe-11eb-8637-1990f7fdd2a3.jpg)
![Screenshot_20201215-101921806 (1)](https://user-images.githubusercontent.com/58127841/102172579-0c3e0980-3ebf-11eb-8e32-a698086b123e.jpg)

**Comment by Cheap-Skate** [comment]
I dislike the fact that the url gets displaced to the right when the autoplay icon is present. It feels unpolished. I think I would prefer the url position to be same with/without autoplay icon. But I agree with OP there is too much padding. 

(this is probably a nit)

**Comment by sheikh-azharuddin** [comment]
I would suggest it's now time to merge security lock icon with the tracking protection similar to Microsoft edge.. Then the tracking protection button location can be used to add another button for site specific settings control like autoplay, cookies, etc

@Amejia481

What do you say?

**Comment by Cheap-Skate** [comment]
My thought was to keep the padlock "secure" icon and to merge the autoplay (etc) icon with the shield tracking protection icon.

Then there will always be two easily understood icons to the left of the URL:-
1. the padlock says "Firefox thinks this site is secure and therefore safe to use"
2. the shield says "Firefox is shielding you from this site's default behavior for your privacy and/or convenience" by eg
- blocking trackers
- preventing geolocation
- stopping autoplay
- etc etc

The two icons will always be present so the URL won't move left and right; there will be more space in the toolbar for the URL; and the user won't have so many different icons to understand.

I guess the shield TP icon is a strong bit of Firefox branding so I can understand you might be reluctant.  Just my 2c worth

**Comment by Amejia481** [comment]
We are going to investigate why the extra space is showing even if the icon is hidden. You can see more info about the new icon and its propose https://github.com/mozilla-mobile/fenix/issues/17047#issuecomment-745403415 
![image](https://user-images.githubusercontent.com/773158/102360099-98176a80-3f7f-11eb-94f8-2cf49b954b7b.png)


![image](https://user-images.githubusercontent.com/773158/102360367-ec224f00-3f7f-11eb-923c-3669f47675bc.png)

**Comment by Amejia481** [comment]
> I dislike the fact that the url gets displaced to the right when the autoplay icon is present. It feels unpolished. I think I would prefer the url position to be same with/without autoplay icon. But I agree with OP there is too much padding.
> 
> (this is probably a nit)

The feature is only active on nightly to gather feedback, thanks for the input we are going to correct the extra space.

**Comment by Amejia481** [comment]
@sheikh-azharuddin and  @Cheap-Skate I'm going to chat with the UI/UX team

**Comment by Amejia481** [comment]
Meantime we opened a pr for reducing the space, I have pending chat with the UI/UX team to discuss about what will be the final solution. 

https://github.com/mozilla-mobile/android-components/pull/9262#issuecomment-747683375

**Comment by Amejia481** [comment]
The extra space issue is fixed is nightly

**Comment by Amejia481** [comment]
We are still analyzing our alternatives for the additional icon.

**Comment by sheikh-azharuddin** [comment]
> The extra space issue is fixed is nightly

Extra space needs to be fixed in custom tab too..

**Comment by Amejia481** [comment]
> > The extra space issue is fixed is nightly
> 
> Extra space needs to be fixed in custom tab too..

Could you share an example where the extra space is present, I wasn't able to reproduce in nightly 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/773158/104342448-d7769f80-54c8-11eb-8efc-cd56323e60eb.png">

**Comment by sheikh-azharuddin** [comment]
> > > The extra space issue is fixed is nightly
> > 
> > 
> > Extra space needs to be fixed in custom tab too..
> 
> Could you share an example where the extra space is present, I wasn't able to reproduce in nightly
> <img alt="image" width="545" src="https://user-images.githubusercontent.com/773158/104342448-d7769f80-54c8-11eb-8efc-cd56323e60eb.png">

The space between sheild icon and lock icon is too much.. This is justified in main browser screen as there is a divider... But looks odd in custom tab...

**Comment by Amejia481** [comment]
Ok, this is a separated issue, the initial one was related to the autoplay icon, the space distribution in custom tabs haven't changed.
