### ISSUE TITLE
Strings incomplete for 84

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#17055]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

The first 84 tag was on Nov 18. A large translation l10n import landed on Nov 20 (and a few more after this we should also consider). Some strings didn't make the 84 cut and were never uplifted. 

The two commits I could find are the [Grid View CFR Strings ](https://github.com/mozilla-mobile/fenix/commit/ebadbdb3522fc777e388ca1241e0287e89fec111#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103) [and new tabs tray menu strings](https://github.com/mozilla-mobile/fenix/pull/16236/files#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103)

[The l10n import on Nov 20 that contained](https://github.com/mozilla-mobile/fenix/pull/16694) (at least) the Italian strings (but there are probably more imports that could also be uplifted)

**Comment by LaurentiuApahideanSV** [comment]
We tested several language string found at https://github.com/mozilla-mobile/fenix/commit/af29a2ccdde007cb0bf412f68323f28bdacf2c05 on Nightly 201217 and RC 84.1.1. They are implemented in Nighlty but not seem to be implemented in RC. The list also contains strings referencing the "pull to refresh" feature that is only present in NIghlty and languages such Tagalog, tl that is not availble in RC 84.1.1.

**Comment by Delphine** [comment]
Just in case: we also need to import a-c strings for Fenix each time

**Comment by ekager** [comment]
@LaurentiuApahideanSV are any of those strings used in 84.1.1? It's okay if there are extra newer strings that aren't used AFAIU. 

The two features that landed in 84 that I could tell didn't get full translations were the 
GridView CFR and the Tabs Tray Menu strings.

**Comment by LaurentiuApahideanSV** [comment]
I rechecked the issue and the strings are indeed used in RC 84.1.1. Thank you for clarification regarding the extra strings. The issue is fixed.
