### ISSUE TITLE
[Bug] Scroll bar in Tabs view/tray is not visible with "Dark" theme

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#17051]
## Steps to reproduce
1. Open the browser.
2. Open multiple tabs, in order to have a scroll bar.
3. Enable "Dark" theme.
4. Observe the scroll bar while in "Tabs" view/tray

### Expected behavior
The scroll bar is visible.

### Actual behavior
The scroll bar is not visible.

### Device information

* Android device: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
* Fenix version: Firefox Nightly 201214 (🦎 85.0a1-20201210092800)
 
### Notes:
1. The issue is not reproducible with "Light" theme. 
2. Screenshot attached.

![image](https://user-images.githubusercontent.com/12184325/102237907-d4a28200-3efd-11eb-923d-7dc27e836fcc.png)

**Comment by hakkikaancaliskan** [comment]
Not reproducible on Xperia XZ1, Android 11, 12/25 Nightly
![photo_2020-12-26_17-45-16](https://user-images.githubusercontent.com/17825767/103153516-21aa1200-47a2-11eb-85f2-7cd53f9213b2.jpg)

**Comment by softvision-oana-arbuzov** [comment]
I can't reproduce it either now, the scroll bar is visible.
![image](https://user-images.githubusercontent.com/12184325/104035368-b832f600-51da-11eb-9657-dca4108d6c00.png)

**Tested with:**
Browser / Version: Firefox Nightly 210107 (🦎 86.0a1-20210107040715) 
Operating System: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density) 

Closing the issue as fixed.
