### ISSUE TITLE
fix the website

### ISSUE THREAD

**Issue by 1smartdevice** [mozilla-mobile/fenix#17054]
The way Firefox is running there's no etiquette in how I should say get it fixed and quickly it looks like I'm going to have to use a different program to serve the web because I can't do it on Firefox. There is no code of conduct right now.

**Comment by ekager** [comment]
This is not a valid issue. And we do have a code of conduct actually! Please read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) and the [Bugzilla Etiquette guidelines](https://bugzilla.mozilla.org/page.cgi?id=etiquette.html) before filing an issue in the future. 

You can file bugs with details about a specific problem you are having (with details and STR), but this is not an appropriate issue to open here, please don't do it again.

**Comment by Neon329** [comment]
@1smartdevice Please report the website issues you face on https://webcompat.com/.
