### ISSUE TITLE
[Bug] "Select tabs" button not displayed if Fenix private tab crashes

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#17066]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open 2-3 pages in normal browsing.
2. Open about:crashparent in private browsing.
3. Open Fenix and tap on tabs tray.
4. Go to normal tabs and check the buttons. 

### Expected behavior
"Select tabs" is displayed.

### Actual behavior
"Select tabs" is not displayed.

### Device information
* Android device: LG G6 (Android 8.1), Pixel 3 (Android 11). 
* Fenix version: Nightly 12/16, Beta and Release.

**Comment by ebalazs-sv** [comment]
I can reproduce this issue on Nightly 1/15, Beta 1/15 and Release 1/7 with Samsung Galaxy Tab S3 (Android 8), following the steps:
1. Open 1 or more tabs in normal browsing;
2. Go to private browsing and open one tab;
3. Close the tab from private browsing;
4. Go back to normal browsing;

The "Select tabs" button is not dispayed.
