### ISSUE TITLE
[Bug] during login, it didn't send me a single confirmation email and then locked my account

### ISSUE THREAD

**Issue by dusrdev** [mozilla-mobile/fenix#17065]
## Steps to reproduce
Download the firefox app and enter sync, instead of using code, sign in with email.
### Expected behavior
The app send the confirmation email and I receive it and continue to enable sync.
### Actual behavior
The app never sent an email (Checked all email folders and spam filter, nothing was received), tried to press on send email again, after a few times, my account got locked.
### Device information
* Android device: Samsung Galaxy S10 - Running OneUI 2.5 - Android 10
* Fenix version: 82.1.3

**Comment by kbrosnan** [comment]
We don't control Firefox Accounts in this project. See https://support.mozilla.org/en-US/kb/im-having-problems-with-my-firefox-account#w_im-having-trouble-verifying-my-firefox-account for documentation about opening a Bugzilla bug to possibly recover your account.
