### ISSUE TITLE
[Bug] Touch behavior not working on side of the screen

### ISSUE THREAD

**Issue by flofle92** [mozilla-mobile/fenix#17074]
Hi, I've been experiencing this issue with my Oppo Reno 2Z on Firefox), and I don't have that issue with Chrome.

Steps to reproduce :
1) Go to www.google.com
2) Click on the top-left corner icon (3 horizontal bars)

Expected behavior :
- This should open the website's menu

Actual behavior : it depends
- does nothing
- behaves like a ling-press

Device information : 
Oppo Reno 2Z, Android 10, ColorOS 7.1
Firefox 83.1.0

More informations : 
This happens on any website where I need to touch an icon/link on the side of the screen (left or right)

Thanks for your help !

**Comment by ekager** [comment]
Could you try to reproduce this on Nightly and let us know if you can still see this? https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by flofle92** [comment]
> Could you try to reproduce this on Nightly and let us know if you can still see this? https://play.google.com/store/apps/details?id=org.mozilla.fenix

I juste tried and the same thing happens.
