### ISSUE TITLE
Download (or upload) files without storage permission

### ISSUE THREAD

**Issue by junjieyuan** [mozilla-mobile/fenix#17077]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Firefox need storage permission to access files.
### How do you know that this problem exists today? Why is this important?
Chrome is using [storage access framework](https://developer.android.com/guide/topics/providers/document-provider) to accessing files, and it not require storage permission. Using SAF helps protect user privacy and information security.
### Who will benefit from it?
All Firefox users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9128)

**Comment by Blocked** [comment]
In Android 10 and 11, It seems  that the app is requesting storage permission to download videos and images and documents.  If denied, a popup displays  stating Firefox needs storage permission to save file. However, that's not true. The [documentation](https://developer.android.com/training/data-storage/shared/media#request-permissions) says

>Don't unnecessarily request storage-related permissions for devices that run Android 10 or higher. Your app can contribute to well-defined media collections, including the MediaStore.Downloads collection, **without requesting any storage-related permissions**. If you're developing a camera app, for example, you don't need to request storage-related permissions because your app owns the images that you're writing to the media store.


On the downloads side, Even without SAF, the app doesn't need any permission to contribute to the downloads directory or images or videos. On the uploads side, I think SAF is needed.  Either way, this is a unneeded permission. End users cannot read source code and  Mozilla's interest in privacy is best proved if such unnecessary permissions are removed at the earliest.

**Comment by wbillan** [comment]
Further to the above, as per Play's policy for [Use of All files access (MANAGE_EXTERNAL_STORAGE) [permission]](https://support.google.com/googleplay/android-developer/answer/10467955/use-of-all-files-access-manage-external-storage-permission?hl=en), if you look at the "permitted uses of the all files permission" downloading and saving files is not on the list.  

Based on the above, would suggest that, at the very least, the download aspect of this issue be updated with higher priority, as the download use case doesn't meet the intent of Play's policies for why an app may request the [Use of All files access (MANAGE_EXTERNAL_STORAGE) [permission]].

Opera is an example of a common android browser app that has been targeting API 30 for months and does not request storage permissions to download files,

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812800

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
