### ISSUE TITLE
[Bug] QR scan does not work on reverse (inverted) image QR

### ISSUE THREAD

**Issue by Etua** [mozilla-mobile/fenix#17085]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Try to scan valid QR code with URL that is surrounded with black space (colours for the code itself are standard).

### Expected behavior
QR code should be recognised and consecutively I should be redirected to a website.

### Actual behavior
QR code is not recognised by Fenix no matter the time and how well focused it is. An external app recognises it at a glance. I suspect that the black background is the issue as more "conventional" settings with white surroundings are not an issue to Fenix.

### Device information

* Android device: Xperia 10 II (XQ-AU52) Android 10
* Fenix version: 84.0.0-beta.4

**Comment by mcarare** [comment]
![reverse-image](https://user-images.githubusercontent.com/48995920/102464668-4f31e580-4055-11eb-8a0a-35ead99421c9.png)
Example of QR codes with reverse image: the one on the left works, the other one(reversed image) does not.

**Comment by sflorean** [comment]
I wasn't able to reproduce the issue on latest Nightly build with Xiaomi Redmi Note 8T (Android 9).
