### ISSUE TITLE
Option to open a page directly in Reader Mode

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#17088]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

The ability to open a link directly in Reader Mode. Ideally, Fenix (and desktop Firefox, hopefully) would parse the page and ignore the DOM elements which are not needed to display the page in Reader Mode.

If the page happens to be unsuited to Reader Mode, it could just fail and inform the user.

### How do you know that this problem exists today? Why is this important?

Often, I already know I'm opening an article or blog post which I would want to use Reader Mode for. Having to open the page, and wait for it to load before the Reader Mode icon appears, is a small waste of time.

### Who will benefit from it?

Users who read long form text often.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9134)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814120

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
