### ISSUE TITLE
Use in-app browser switching dialog when requesting users to change their default browser

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#17084]
### What is the user problem or growth opportunity you want to see solved?
Asking users to change their default browser is a big ask for them. Having to take them to the settings app, thereby leaving Fenix to do this removing them from the browser context.

### How do you know that this problem exists today? Why is this important?
Currently we send an intent to open the default apps screen, which is not even specific for setting the default browser.

### Who will benefit from it?
Converting new users.

This is what it looks like in Opera:

![Screenshot_20201216-152220](https://user-images.githubusercontent.com/1370580/102414298-4a712100-3fc4-11eb-8cb4-b5d54479dae1.png)

**Comment by jonalmeida** [comment]
@kbrosnan also mentioned he's seen this in Chrome as well.

**Comment by hakkikaancaliskan** [comment]
I've did some basic implementation :)
I'll open a pr as draft

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on both **`Nightly 210218`** and **`RC 86.1.0`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)

✔️ Works properly on **`Nightly`**
► Video

https://user-images.githubusercontent.com/51314259/108352937-34fcbb00-71f0-11eb-980f-d7d96c1bf56d.mp4

❓ On the other hand I've noticed a couple of inconsistencies on **`RC 86.1.0`**
1.  Tapping the "Cancel" button re-directs the user to the System settings -Default apps
2. Each time you set a **different Default Browser app**, the user is re-directed to the System settings -Default apps

► Video

https://user-images.githubusercontent.com/51314259/108356239-90c94300-71f4-11eb-9cc0-10244bcad0de.mp4

@eliserichards and @hakkikaancaliskan - Please review and share your thoughts ☺️

**Comment by hakkikaancaliskan** [comment]
@AndiAJ 

> Tapping the "Cancel" button re-directs the user to the System settings -Default apps

Fix landed in nightly, maybe needs uplift. https://github.com/mozilla-mobile/fenix/pull/17916

> Each time you set a different Default Browser app, the user is re-directed to the System settings -Default apps

Isn't this intented behavior, because user selected another browser and Android doesn't let us show again.  Maybe we need UX feedback.

Also this should just work on >A10.

**Comment by AndiAJ** [comment]
Hi @hakkikaancaliskan thanks for the heads-up. ☺️ 

✔️ All good on Nightly with: 
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• Google Pixel (Android 10)
• OnePlus 5T (Android 10)

> Actually if that's working fine on nightly, just an uplift required.

It seems that it was included in **`RC 86.1.0 RC 1`**
Or am I mistaken ❔ 
https://github.com/mozilla-mobile/fenix/commits/v86.1.0-rc.1

**Comment by jonalmeida** [comment]
> ❌ The prompt **isn't displayed at all (the user is re-directed to System settings -Default apps)** while using :
> • Pixel 3XL (Android 9)
> • OnePlus 6T (Android 9)
> • HTC 10 (Android 8)
> • Huawei MediaPad M3 (Android 7.0)

This sounds right since this API isn't on older devices, so it falls back to the old way (showing the system settings).

Closing this issue as completed then. Thank you @hakkikaancaliskan !
