### ISSUE TITLE
[Bug] The "Google" search engine dissapears after deleting and re-adding it 

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#17091]
## Steps to reproduce
1. Go to Settings - Search and delete the default "Google" search engine.
2. From the same Search page, go to "+ Add search engine" and add the "google" search engine" back to the default search engine list.
3. Observe the default search engine list.

### Expected behavior
The "Google" search engine is displayed in the default search engine list.

### Actual behavior
The "Google" search engine isn't displayed anymore nor in the default search engine list, nor in the "Add search engine" list.

### Device information
* Android device: Samsung Galaxy Tab S6 (Android 10)
* Fenix version: 84.1.1
* Not reproducible on the 1217 Nightly build, or Beta 85.0.0-beta.1
* Not reproducible with any other search engine
* Not reproducible on OnePlus 5T (Android 9), Motorola Moto G6 (Android 8), Google Pixel (Android 10), or Samsung Galaxy Note 8 (Android 9)

<img src="https://user-images.githubusercontent.com/40694158/102460784-2d822f80-4050-11eb-9da3-3bd17be11244.gif" width="300" height="550" />

**Comment by pocmo** [comment]
Beta and Nightly have the new search code (where this is not reproducible as described above). I think we should wontfix this for the old code in the release version.

**Comment by mcarare** [comment]
Closing this, as it's not reproducible anymore and we cannot change older release.
