### ISSUE TITLE
[webcontent] Can't open a PDF file after downloading it (from a Twitter link)

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#17099]
## Site with issue and any steps to reproduce
1. Open https://twitter.com/boostmarks/status/1339490490471878658
2. Click on the PDF link
3. Click on "open the file" after it's been downloaded.

### Expected behavior
=> The file is downloaded and can be opened in the PDF viewer.

### Actual behavior
=> The file _is_ downloaded.
=> I get an error that the file can't be opened.

When clicking on the notification for the download, the file can't be opened either, the error I get is "no application has been found for this file".

I can open the file when searching it from a File Manager app.
This also works fine in Chrome on Android, or Firefox on Desktop.

In Chrome I was unauthenticated on Twitter, so I also tried on Firefox/Android in private mode so that I'd be unauthenticated too, and I get the same problem.

Sorry I couldn't try with a link to a PDF file from another source than Twitter yet.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?

No.

### Device information

* Android device: Samsung S10e
* Fenix version: Nightly 201216 17:01 (Build #2015781771) (Gecko version: 85, Gecko BuildID 20201214091023)

**Comment by JulianMH** [comment]
The same error occurs with this link: `https://dev.esis.de/api/v9/ESISApp.php?f=PDF&id=TTT&token=5ff4418a050e08ja8cLMlJLJcJPNNXMGxPA&file=5ff44149ad633.pdf`

Works fine on Firefox Desktop and Chrome.

## Device Information

Android Version: 8.0.0
Android Device: HUAWEI P20 lite
Fenix Version: Nightly 210112 17:03

**Comment by drupol** [comment]
Hi,

Same issue when trying to download my CV from github: https://github.com/drupol/cv/releases/latest/download/cv.pdf

I tried with other browsers and I'm unable to reproduce the issue.

**Comment by Amejia481** [comment]
This issue will be addressed after https://github.com/mozilla-mobile/android-components/pull/9558 lands

**Comment by julienw** [comment]
I believe this works now.

**Comment by drupol** [comment]
Indeed, this is fixed, thanks!
