### ISSUE TITLE
FNX-5200 ⁃ [UX] Battery

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#171]
GH issue to track design work. Designer is Nicole (getting her added to repo now)

**Comment by lime124** [comment]
making a note that battery saver stuff should incorporating tracking protection type settings (optimize in the prototype). eng meta ticket for TP #97

**Comment by lime124** [comment]
@bbinto why did you add the block label?

**Comment by bbinto** [comment]
@lime124 - blocked by PM to provide further requirements, unless UX feels they have enough to get started.
