### ISSUE TITLE
FNX-5201 ⁃ Create scaffolding for Robolectric tests on non "component" classes

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1710]
We need to set up the ability to do unit tests for classes that don't perfectly fit into "components" or "views" (see: ShortcutEngineManager).

This blocks: https://github.com/mozilla-mobile/fenix/issues/1268

**Comment by sblatz** [comment]
@vesta0 are we able to prioritize this?

**Comment by bifleming** [comment]
@vesta0 this is blocking 1268, and should probably be pulled into the sprint in place of 1268.

**Comment by vesta0** [comment]
We can add it to the upcoming sprint
