### ISSUE TITLE
Bing image search crashes android firefox

### ISSUE THREAD

**Issue by KenoattX** [mozilla-mobile/fenix#17108]
I have been using bing search as my search engine for a while. Recently, when I search something in bing and then click the images button my keyboard pops up for a second, it then  disappears  then I can't click anything on the page.This does not happen in Google search engine .

**Comment by ekager** [comment]
Hi, @KenoattX thanks for reporting! Which version of Firefox? Do you see anything in Settings -> About -> Crashes

**Comment by ekager** [comment]
Can you link the Socorro or Sentry links with the entry here? And if they don't have those links attached, next time you reproduce a crash - make sure you click "report" on the dialog

**Comment by KenoattX** [comment]
> Can you link the Socorro or Sentry links with the entry here? And if they don't have those links attached, next time you reproduce a crash - make sure you click "report" on the dialog

https://crash-stats.mozilla.org/report/index/65cd2f9b-cfb2-43f2-8f93-ff3df0200916

https://crash-stats.mozilla.org/report/index/ca736729-4dae-4c61-89b1-ec73a0200906

**Comment by ekager** [comment]
And which version of Fenix are you on? It looks like a similar crash was possibly already fixed.

**Comment by KenoattX** [comment]
84.1.1 (Build #2015781795). I believe this is the correct one.

**Comment by ekager** [comment]
Thanks!

**Comment by trulow** [comment]
I have the same issue on 84.1.2

Although when looking at Settings>About>Crashes, there are no crashes to report.

**Comment by codrut-topliceanu** [comment]
Filed new issue on GV : https://bugzilla.mozilla.org/show_bug.cgi?id=1686002

**Comment by kbrosnan** [comment]
Closing as this will be tracked on Bugzilla.
