### ISSUE TITLE
suggest to always show “fill link from clipboard” whenever users click on the url bar

### ISSUE THREAD

**Issue by alastor0325** [mozilla-mobile/fenix#17109]
Everytime when users need to paste the link from the clipboard, users have to clear the current url, then the "fill link from clipboard" option would eventually show.

It would to be good to show "fill link from clipboard" below the url bar whenever users click on the url bar.

It can help to eliminate that unnecessary url clear before pasting new url.

**Comment by apbitner** [comment]
@brampitoyo This sounds like a good idea to me, but makes me wonder when the user taps on the URL bar can we just clear out the URL instead of highlighting it? Would make implementing this even easier.

**Comment by brampitoyo** [comment]
@apbitner This idea has a lot of merits.

Clearing out the URL on selecting the address bar will:

1. Make it easier to paste links/keywords from the clipboard without appending the string onto existing URLs ← the scope of this issue
2. Visually indicate that the address bar is ready for next steps: searching, entering new address, etc. To be clear: today, people can already type new keywords/addresses without clearing the highlighted URL. However, having the URL bar be empty will help strengthen this signal

**Comment by alastor0325** [comment]
It seems not a right way to simply close a bug just because there is not recent activity because the issue still exists.
