### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by KatoriYuu** [mozilla-mobile/fenix#17106]
## Steps to reproduce
Download any files, and compare the download speed with Chrome.

### Expected behavior
The download speed of both must be similar by using the same network connection.
### Actual behavior
The download speed of Firefox is 5-6 times slower than Chrome.
### Device information

* Android device: Nokia 8.1, Android 10
* Fenix version: 84.1.1

**Comment by KatoriYuu** [comment]
Please prioritizing this problem as it's a basic demand of a browser.

**Comment by mcomella** [comment]
Action item: let's verify this occurs on downloads from multiple pages (i.e. make sure it's not one page that causes the issue). If we can verify the issue, let's try to have the JVM teams take a look.

Thoughts from csadilek: we download in 4k chunks – maybe Chrome is doing something more intelligent such as increasing/decreasing chunk size based on the connection quality. They may also start parallel downloads but we're uncertain this would actually help. Note: the chunk size makes the download resume able. There is chunk size code in ac.

**Comment by sflorean** [comment]
Tested on latest Nightly with Nokia 6 (Android 7.1.1) and we didn't encounter any issue. 
@KatoriYuu could you please add your results also? since we don't have the exact device reported for this issue.

**Comment by KatoriYuu** [comment]
You are right, the download speed of the lastest stable release is good now. Maybe it was problem of older versions. Thanks for your help.
