### ISSUE TITLE
Intermittent UI test failure - <org.mozilla.fenix.ui.BookmarksTest>threeDotMenuShareBookmarkTest

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#17113]
### Firebase Test Run:
Provide a Firebase test run report link here showcasing the problem
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6477652798122442151/executions/bs.6e3b55010cbcb92f/testcases/1/test-cases
### Stacktrace:
 java.lang.NullPointerException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null
at org.mozilla.fenix.ui.BookmarksTest$threeDotMenuShareBookmarkTest$3.invoke(BookmarksTest.kt:205) 
### Build: 
master 451f7ae31c8350e749a3f2579d78d5fe867384dd

**Comment by sv-ohorvath** [comment]
This, along with some other Bookmarks tests, failed after an AC upgrade and we haven't seen this failure since more than a month ago. Closing the issue and will reopen if it occurs again.
