### ISSUE TITLE
Font spacing wrong when long pressing a URL

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#17118]
## Steps to reproduce
Long press some text on a page. Notice the text "Copy   Search   Select All   Share" has a closely spaced font
Long press the URL in the toolbar. Notice the text "Copy   Paste   Paste & Go" has a *more spaced out font*

### Expected behavior
fonts should be the same in both cases

### Actual behavior
Not

### Device information

* Android device:  Galaxy A40, Android 10
* Fenix version: Today's
![Screenshot_20201218-134648_Firefox Nightly](https://user-images.githubusercontent.com/40568887/102621763-f6874900-4137-11eb-8ee7-226697c5c45c.jpg)

vs

![20201218_134710](https://user-images.githubusercontent.com/40568887/102621751-f25b2b80-4137-11eb-974e-56d6626ded21.jpg)

**Comment by ekager** [comment]
Yes, this looks wrong. Not sure how the text spacing got weird, but should be easy enough to update

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly.
