### ISSUE TITLE
[Bug] Scrolling stutter on gadgets.ndtv.com website

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#17116]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open gadgets.ndtv.com website and scroll. For ex open this link https://gadgets.ndtv.com/mobiles/news/google-qualcomm-project-treble-partnership-4-android-os-versions-security-updates-2340017
### Expected behavior
Scrolling must be smooth.
### Actual behavior
Scrolling stutter. Samsung internet and chrome both works fine.
### Device information
Samsung Galaxy A71
* Android device: Android 10 One UI 2.5
* Fenix version: 84.1.1

**Comment by ekager** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1683354

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
