### ISSUE TITLE
[Bug] Pages often do not load all the way when "opening link in new tab". 

### ISSUE THREAD

**Issue by MadridSpain** [mozilla-mobile/fenix#17115]
Twitter is a prime example, but many other sites do it as well. You longpress a link, select "open link in new tab", and then **after** waiting a moment, when you go to the new tab, the page is only partially loaded

[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

For this example, I will use Twitter. However, this problem exists on many webpages, not just Twitter.

1. Open a fresh, new Firefox Daylight session. I have my homepage set to a blank page (I don't think that matters).

2. Go to any non-twitter webpage that has a twitter link you can press somewhere in the page. Here is an example:

https://old.reddit.com/r/CryptoCurrency/comments/jc9jpk/judy_shelton_on_twitter/

<img src=https://user-images.githubusercontent.com/34783450/102611273-87552900-4126-11eb-84d7-21d26aa6ffde.jpeg width = 40%>

3. Long press the Twitter link (in the above example, longpress the words "_Judy Shelton on Twitter_" circled in red).

4. Select "_Open link in new tab_" from the menu when it pops up.

5. Wait 10 seconds. (the problem does **not** occur unless you wait for the link to load as much as it can by itself without you viewing it).

6. Go to the tab.

### Expected behavior

The link you opened in a new tab should be loaded. It should look like this:

<img src=https://user-images.githubusercontent.com/34783450/102609248-13655180-4123-11eb-98a0-29c3acfbc701.jpeg  width = 40%>

### Actual behavior

The link you opened is only partially loaded and **won't finish loading. It's frozen as-is**. It looks like this:

<img src=https://user-images.githubusercontent.com/34783450/102609193-fc266400-4122-11eb-8add-1bb7b414268a.jpeg width = 40%>

The only way to get the page to finish loading is to refresh the page. This happens **every single time.**

### Device information

* Android device: Samsung S8 (SM-G950FD Smartphone, latest version of Android operating system as of 2020/Dec/18)
* Fenix version: Firefox Daylight 84.1.1 (build #2015781795) / Firefox Nightly (build #2015781579)

Note: This issue occurs on both Daylight and Nightly. My Nightly install has no add-ons installed whatsoever and is basically vanilla. Tracking protection on or off makes no difference. It makes no difference if the "_Open links on new private tab_" setting is toggled on or off. It does not matter if automatic font-sizing is turned on or off. The problem doesn't occur in Brave or other browsers I've tried.

**Comment by Mikaka27** [comment]
Possibly same issue reported here: #17009

**Comment by Mikaka27** [comment]
I cannot reproduce this on your example link, but I see it in issue I linked here. There it also reproduces on reference browser.

Do you have any other example where it can be reproduced? It would be good to check on reference browser as well.

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 (Android 9) with Firefox Nightly 93.0a1 2021-09-07
