### ISSUE TITLE
FNX-5202 ⁃ Switch Access web page scrolling doesn't seem to work

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#1712]
## Steps to reproduce
Enable Switch Access in Accessibility Settings in Android
Visit a long web page. 
Use switch to focus page. 
Use switch to select menu and scroll up or down button

### Expected behavior
Page scrolls up or down.

### Actual behavior
Page does not scroll. 

### Device information
* Android device: Galaxy S6
* Fenix version: 68.0a1-20190408

**Comment by eeejay** [comment]
Fixed this in GeckoView. Needs to be uplifted to 68, right?

https://bugzilla.mozilla.org/show_bug.cgi?id=1553304

**Comment by cpeterso** [comment]
> Fixed this in GeckoView. Needs to be uplifted to 68, right?

Yes, if you'd like this bug fixed in Fenix MVP (GV 68).

**Comment by asadotzler** [comment]
This seems to be working now.
