### ISSUE TITLE
Below average performance on Android devices under 1GB RAM

### ISSUE THREAD

**Issue by samiuljoy** [mozilla-mobile/fenix#17125]
I have a Mediatek (built year 2016) Android with kernel 3.10, running Android 5.1.1(stock rom). Both the release version of Firefox(release version 83.1.0 and all previous versions) and beta version (beta version 85.0.0-beta.1 and all previous versions) runs comparatively slow. By comparatively, I mean to say is if compared to the performances with Chrome and Brave Browser for Android. The performance of the new version of Firefox for Android is undoubtedly way better than it was couple months ago, kudos to the devs!!. However, when compared to browsers like Chrome and Brave, Firefox is still comparatively slower for devices under 1GB RAM. On my Samsung, running Android 10 with 4GB of RAM, Firefox release and Firefox Beta's performance is head to head with Chrome and Brave. Can't complain about that. Firefox runs smoothly on my Samsung. But, on low-end devices, the startup time is comparatively longer and pages such as Reddit(if contains videos), forces the app to crash completely. I didn't face such issues while using Chrome and Brave.

**Comment by mcomella** [comment]
Hi @samiuljoy – do you have any extensions enabled? If so, can you try to reproduce without them enabled? As far as I know, neither Chrome or Brave mobile support extensions so, for a fair comparison, we should check the behavior without the extensions.

**Comment by samiuljoy** [comment]
Hello @mcomella ! No I don't have any extensions enabled, nor do I have any extensions downloaded. I used to use Ublock origin before, probably 3 or 4 months prior, recently I managed to set up dns based host blocking system, which blocks most trackers and ads, hence removed ublock origin. Also, using Dark reader considerably reduces page load on older devices, again compared to Chrome and Brave.

**Comment by mcomella** [comment]
Let's ask ecsmyth for a priority.

**Comment by mcomella** [comment]
Thanks for reporting. Unfortunately, a very small proportion of our users are on devices with < 1 GB of RAM and we have limited development resources so we'll be unable to prioritize this issue directly though you may experience improvements as we make performance improvements focused on other areas of the code.

**Comment by samiuljoy** [comment]
That's unfortunate, but luckily I'm not using that phone as a daily driver, so that's fine. Also, I've settled on compiling the app from source(and also manually removing couple stuffs) which actually improves performance by a lot on the older device. And you're right about the performance improvement, I've downloaded the pre-release version 85.0.0-beta-7, which out of stock seems to be pretty snappy. Looking forward to more improvements.

**Comment by mcomella** [comment]
> Also, I've settled on compiling the app from source(and also manually removing couple stuffs) which actually improves performance by a lot on the older device.

@samiuljoy Interesting – what did you remove? Understanding this may help us find new areas for performance improvements. :)

**Comment by samiuljoy** [comment]
@mcomella I've removed stuffs in a pretty messy way, not practical at all. Things I've modified are;

1. Reduced/removed the extra languages strings(not sure if that effects performance)

2. Couple of telemetry stuffs(although adding debug flag removes most of them by default)

3. Set the transition and animation values to `@null` and durations to 0. This actually improved startup time, made navigating between pages a lot better and improved page load times. 

Nothing too fancy, but it's working much better than before, especially with the newer fenix versions(>85). I'll keep tinkering ^_^

**Comment by samiuljoy** [comment]
@mcomella Also, the icons.json or something similar(forgot the loaction and name of the file) has tons of urls probably for icon fetching, removed all the urls with `http://0.0.0.0` lol

**Comment by samiuljoy** [comment]
Also, I should mention, turning off `animations and transitions` from developer options under Android settings should turn off animations and transitions for all apps. The odd thing here is that, on the older device, turning off animations and transitions does not seem to work for Fenix, however works for Chrome and Brave. On my newer Samsung, fenix respects animation and transition settings.

**Comment by Dunexus** [comment]
There is an open bug about respecting the reduce motion from android accessibility settings https://github.com/mozilla-mobile/fenix/issues/3597

**Comment by samiuljoy** [comment]
@Dunexus I think turning off animations from two seperate places is necessary to disable animations and transitions on fenix. One is from accessibility settings, which is the default way and the other one is from developer settings > animations and transitions. This forces fenix to turn off animations. Although I couldn't figure out a way to tinker with the slide animation while navigating sub menu options. The right to left slide transition under settings option.

**Comment by mcomella** [comment]
> @mcomella I've removed stuffs in a pretty messy way, not practical at all. Things I've modified are;

Thanks for the list! I'll start looking into these as part of our efforts to improve start up performance. fwiw, I think you are on to something with the telemetry and (inflating) animations, both of which I think we've seen delays caused by. Ideally, these non-essential things to the user experience should not introduce noticeable delays to the user. It's a good reminder for me to look into them. :)

> @Dunexus I think turning off animations from two seperate places is necessary...

@samiuljoy Thanks for letting us know. It's most useful to us for each issue to focus on one topic (this one focusing on device < 1GB RAM performance) so if you wanted to share the information around disabling animations in the bug Dunexus mentioned or, if the info is unrelated, filing a new bug, that would be ideal – thanks!
