### ISSUE TITLE
Add redirect trackers to ETP panel view and settings

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17133]
#13812 added an Enhanced Tracking Protection category to the main settings for redirect trackers. We should also add this to the ETP panel from the toolbar: 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/43795363/102666976-dbbfcf00-414d-11eb-9d2e-2142f4c3f1b3.png">

and add the ability for users to customize this ETP category in `CUSTOM` view:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/102669202-8e466080-4153-11eb-8dba-f552205ffa52.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9167)

**Comment by eliserichards** [comment]
**Question**: when we de-select a category from CUSTOM, it disappears from the `Blocked` list in the (i) info page:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/43795363/102672305-03b33080-4156-11eb-9f38-f4f51a913fd4.png">  <img width="321" alt="image" src="https://user-images.githubusercontent.com/43795363/102672316-0ada3e80-4156-11eb-9084-bd52d9c7a852.png">

Should this (i) page show both `Allowed` and `Blocked`, which would mimic the ETP panel implementation?

**Comment by eliserichards** [comment]
@abodea tested #13812, so that might be helpful for QA: https://github.com/mozilla-mobile/fenix/issues/13812#issuecomment-700503934

**Comment by abodea** [comment]
Hello, @eliserichards regarding ETP redirect trackers, once every 24 hours ETP 2.0 will completely clear out any cookies and site data stored by known trackers. This prevents redirect trackers from being able to build a long-term profile of your activity.
When you first visit a redirect tracker it can store a unique identifier in its cookies. Any redirects to that tracker during the 24-hour window will be able to associate tracking data with that same identifying cookie. However, once ETP 2.0’s cookie clearing runs, the identifying cookies will be deleted from Firefox and you’ll look like a fresh user the next time you visit the tracker.
Based on my comment from https://github.com/mozilla-mobile/fenix/issues/13812#issuecomment-700503934 I can verify this exactly how I verified the cooking purging?
Also, does this applies only for the known trackers and cookies from non-tracking sites are unaffected.
When visiting a redirect tracker website it will be stored as a unique identifier in its cookies?

I will try to check this like ETP Cookies purging, removing `eng:qa:needed` until further notice.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807562

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
