### ISSUE TITLE
On start up, ensure first network request is page load

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#17138]
_Soft blocked by #17645. See https://github.com/mozilla-mobile/fenix/issues/17138#issuecomment-786303911_

acreskeyMoz points out

![image](https://user-images.githubusercontent.com/759372/102675557-ba131780-414e-11eb-9009-84c4b05ff874.png)

> We're making the telemetry request way before the www.example.com one in an app-link cold startup.
Perhaps the perf effort will change to warm applink?
We might have the same issue.
We'd probably have to pass in the target url as an initialization parameter to gecko to fix this.

I believe this is on start up.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9170)

**Comment by mcomella** [comment]
Note: this may not happen on every start-up.

**Comment by mcomella** [comment]
Triage: it sounds hard to do this in a generic, regression proof way. It might be easier to reorder the specific requests. That being said, it might be fixed by #17645 so let's wait for that before doing anything.

One source of network requests that isn't present in the first comment but may occur in the wild is restarting paused downloads (which seems to be the purpose of `FenixApplication.restoreDownloads`).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807315

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
