### ISSUE TITLE
GDPR and Leanplum marketing data sharing

### ISSUE THREAD

**Issue by nu111** [mozilla-mobile/fenix#17136]
Hi, just a fast question, are you sure that the marketing data share with leanplum enabled by default without used consent is OK for GDPR and EU cookie law?

**Comment by kbrosnan** [comment]
I have forwarded this query to the Legal team. It may be into the new year before it is possible to respond. Mozilla has most of the rest of December as PTO

**Comment by kbrosnan** [comment]
The reply I got was to contact compliance@mozilla.com directly with your questions. There is not anything that can be done in this issue. Closing.
