### ISSUE TITLE
Strings not refreshed on Nightly for past 11 days (was: Recently modified Corsican strings not refreshed on Nightly)

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#17135]
A localizer filed this issue, [but under our repo](https://github.com/mozilla-l10n/android-l10n/issues/299).
It seems that the strings are not being refreshed on Nightly?

Please see link above for the full details that the localizer has filed.

**Comment by mcarare** [comment]
@Delphine I do not see any PR for importing strings from `mozilla-l10n-automation-bot` since 11 days ago.

**Comment by Delphine** [comment]
Pinging RelMan folks because I think they can help out with this (CC @escapewindow, @MihaiTabara)
Also, FYI @st3fan.

**Comment by escapewindow** [comment]
um. i may have fixed? the update-projects hook is now all green
17:04
https://github.com/mozilla-mobile/android-components/pull/9284
17:04
https://github.com/mozilla-mobile/fenix/pull/17193
aki  17:04
that's a lot fewer changes than my manual PR
17:06
i hope those look good. for posterity, a) we had to re-invite the l10n bot, b) i had to add more permissions to the bot's user token, c) we had to close all open PRs (my manual PRs broke further automation), and d) i reran the update-projects hook manually. i'm hoping the update-l10n hooks Just Work after this, but time will tell

**Comment by csadilek** [comment]
Thank you! Strings have been auto-landing again today.

**Comment by Delphine** [comment]
Thank you all so much!

**Comment by st3fan** [comment]
@Delphine It is our goal to get strings for both A-C and Fenix in good shape this week.
