### ISSUE TITLE
Replace hard-coded strings in ETP Cookies setting

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17130]
Currently `settings.blockCookiesSelectionInCustomTrackingProtection` is defined as a string preference: 

```
val blockCookiesSelectionInCustomTrackingProtection by stringPreference(
        appContext.getPreferenceKey(R.string.pref_key_tracking_protection_custom_cookies_select),
        "social"
    )
```

It can be set to the following values: `all`, `social`, `unvisited`, `third-party`, or `none` (see [TrackingProtectionPolicyFactory](https://github.com/mozilla-mobile/fenix/blob/6962c967ee3828a570ce300ba2cd74a5816bfe5a/app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt#L66)). 

### Purpose
Remove hard coded strings when referencing this setting.

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/22748
