### ISSUE TITLE
[Bug]curson on text area jump to wrong position 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#17147]
typing with fenix and swiftkey is almost impossible sometimes, well often (that's why I m reporting bug) cursor jump to wrong position, please see screen recording
https://drive.google.com/file/d/1D9uHK--hpmQtA1K9xo9MEE69gJgFPDIi/view

**Comment by sflorean** [comment]
Closing as duplicate of #4208. This scenario will be verified when the issue is fixed.
