### ISSUE TITLE
[Bug] Firefox app icon is too small

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#17148]
The Firefox app icon is too small. I put Firefox, Chrome and Edge on my homescreen and took a screenshot to compare. Please make the Firefox icon within the circle larger, it's too small and it just looks wrong
![fenix app icon](https://user-images.githubusercontent.com/47801466/102699788-851dc800-4215-11eb-850b-fce46235493d.png)

**Comment by willfs84** [comment]
I forgot to add: I'm using a Google Pixel on Android 11, so that should rule out any 3rd manufacturer specific custom/non-standard weirdness.

**Comment by marcel263** [comment]
![icon](https://user-images.githubusercontent.com/76437842/102791375-d5746180-439e-11eb-901e-8ba2835cab6b.png)

**Comment by willfs84** [comment]
> ![icon](https://user-images.githubusercontent.com/76437842/102791375-d5746180-439e-11eb-901e-8ba2835cab6b.png)
> As my illustration shows, they are all equally tall. An illusion, but it looks unappealing nonetheless, honestly.

That's not what I meant. I'm saying the Firefox icon WITHIN the circle should be made larger

**Comment by TrianguloY** [comment]
The firefox icon is roughly the same size as the edge one, and both follow the android guidelines for icons (https://developer.android.com/google-play/resources/icon-design-specifications).

Chrome, on the other hand, isn't. That's why it seems bigger. Chrome is the wrong icon here.


Strangely, on my device, they all look fine. Perhaps your device or launcher isn't using the correct icon? 

![IMG_20201222_114349.jpg](https://user-images.githubusercontent.com/10616202/102880035-03af7b00-444b-11eb-8f6a-37fdc2e8c93c.jpg)

**Comment by willfs84** [comment]
As I said in comment 0, it's extremely unlikely there's an issue with Google Pixel software resulting in the Firefox icon being smaller

**Comment by TrianguloY** [comment]
I don't have a pixel, so unfortunately can't confirm it. 

However note that what I said is that Chrome's icon is the faulty one, not firefox, so this issue should be posted on chrome's bug tracker (or whatever they use). If you make firefox icon bigger, then it will be bigger than the other apps (except chrome).

**Comment by willfs84** [comment]
Are you a Mozilla dev?

**Comment by TrianguloY** [comment]
No, I'm not. Apologize if it seemed like it. I have edited the previous comment to clarify this.

**Comment by willfs84** [comment]
Let's let the Mozilla devs look at this. I'm sure one of them has a Pixel phone

**Comment by KrasnayaPloshchad** [comment]
To my eyes, Firefox icon could be bigger a bit in its background.
