### ISSUE TITLE
[Bug] Crashes initializing Nimbus

### ISSUE THREAD

**Issue by GO-jack** [mozilla-mobile/fenix#17143]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Click "+" button to open new tab.

### Expected behavior

No crash and open new tab.

### Actual behavior

Crash when click "+" button to open new tab.

Report: https://crash-stats.mozilla.org/report/index/0d29e773-b26e-4361-b64b-a07c90201219

### Device information

* Android device: ASUS ZenFone 3 (Android 6.0.1)
* Fenix version: 
![0](https://user-images.githubusercontent.com/68154921/102687140-f4041c80-4227-11eb-8050-fb75fac1eae3.png)

**Comment by Dojo456** [comment]
I could not reproduce this bug at all.

**Comment by hackel** [comment]
I've been getting this for the past few days as well.  Can only start Firefox by clicking as link from another app.  Trying to open it directly or open a new tab immediately crashes.  Unfortunately I have no way to provide any kind of debugging information on Android, but I've been reporting it every time from the crash notification.

**Comment by csadilek** [comment]
Thanks for filing! Could one of you check if this is still a problem in latest Nightly (201221 17:00)? 

It should show Monday 12/21 @ 5:04PM under Settings->About Firefox Nightly.

**Comment by gitt0r** [comment]
It's working again.

Thank you very much!

![Screenshot_2020-12-21-23-37-52-308_org mozilla fenix](https://user-images.githubusercontent.com/65116394/102828531-450d3f80-43e5-11eb-94d0-d84e4a8d25f6.jpg)

**Comment by csadilek** [comment]
OK, this confirms that it was also Nimbus related.

**Comment by csadilek** [comment]
Thanks for verifying!

**Comment by csadilek** [comment]
Filed ticket in Nimbus for remaining crashes that will need to be addressed before enabling again:
https://jira.mozilla.com/browse/SDK-161
