### ISSUE TITLE
Push notification improve

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17142]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Currently push notification from website are just showing a notification but on clicking it, it is not taking to exact website or webpage. All chromium browser support this 

### How do you know that this problem exists today? Why is this important?

Push notification should open the site or page which triggered the notification 

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9175)

**Comment by ale82to** [comment]
I find it really annoying glad someone else noticed it

**Comment by skick3** [comment]
It´s the same Problem with these bug report
https://github.com/mozilla-mobile/fenix/issues/14953

The last mobile Firefox version where this feature still works is 68.11.0.
As of the following one, the website is no longer called when the push message is clicked, only the Firefox start page is called.

**Comment by sheikh-azharuddin** [comment]
Not fixed yet even after several releases..
Stale bot go to sleep

**Comment by sheikh-azharuddin** [comment]
Not fixed

**Comment by sheikh-azharuddin** [comment]
Not fixed

**Comment by ale82to** [comment]
not only it's not fixed after so many release ,push notification for Instagram Facebook and reddit ARE NOT WORKING

**Comment by csadilek** [comment]
Duping to https://github.com/mozilla-mobile/fenix/issues/11138.

**Comment by csadilek** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/26998 for the Facebook/Instragram issue.
