### ISSUE TITLE
[Bug] Lockwise App for Android 11 on Samsung Note 20 Ultra when you enable autofill will generate NULL popup

### ISSUE THREAD

**Issue by donm527** [mozilla-mobile/fenix#17149]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Lockwise App for Android 11 on Samsung Note 20 Ultra when you enable autofill will generate NULL popup

## Steps to reproduce

Enable Lockwise as default Autofill for username and passwords. When you scrolll back pages on Samsung Internet Browser a NULL popup shows on bottom of screen. Can repeat in other apps like I believe it was Barclay's Bank app. The moment you go to settings and change default autofill to another app the issue goes away.

### Expected behavior

Should work on background with autofill set as default autofill app without any pop ups of NULL showing in certain apps.

### Actual behavior

NULL pop up in a bubble will show in bottom of screen at times when navigating certain apps and then fade away.

### Device information

Samsung Note 20 Ultra smartphone.
Recently updated to Android 11 pushed by carrier AT&T. 
Did not happen before the OS update with Android 10.
![Capturenull](https://user-images.githubusercontent.com/76271691/102703919-53bbf100-4243-11eb-80c5-b032e5c0ad8e.JPG)

* Android device: ?
* Fenix version: ?

**Comment by anotherus3r** [comment]
Should this maybe be reported in mozilla-lockwise/lockwise-android?

**Comment by donm527** [comment]
This is the link given to me by support on their Twitter account. I'm not experienced with github so I took it for what it was and posted on the link given. I re-submitted to the link you gave. thanks.
