### ISSUE TITLE
[Bug] AMO website is in different language than en-US

### ISSUE THREAD

**Issue by miladmaz12** [mozilla-mobile/fenix#17156]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to Settings ---> Add-ons
2. Tap on an extension, then details
3. Tap on add-on homepage

### Expected behavior
AMO is en-US, just as my device language.

### Actual behavior
AMO is ru (Russian) 

I don't speak Russian.

### Device information

* Android device: Oneplus 3T
* Fenix version: 85.0.0-beta.2

**Comment by AndiAJ** [comment]
Hi, just checked this matter on **`85.0.0-beta.2`** and wasn't able to reproduce using the following devices:
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

✔️ Opened each Web extension's details and is properly opened the en-US AMO.

**Comment by miladmaz12** [comment]
> 
> 
> Hi, just checked this matter on **`85.0.0-beta.2`** and wasn't able to reproduce using the following devices:
> • Google Pixel 3a (Android 11)
> • OnePlus A3 (Android 6.0.1)
> 
> ✔️ Opened each Web extension's details and properly opened the **en-US** AMO.

Now its in `de `instead of `en-US `for me.

**Comment by csadilek** [comment]
I was able to reproduce this. This only affects Beta and Nightly so far and seems related to our endpoint switch to `services.addons.mozilla.org.` I've filed for the addons-server: https://github.com/mozilla/addons-server/issues/16214

**Comment by csadilek** [comment]
Thanks for filing. This has been fixed now. It might take a day or two until client-side caches are refreshed if you're still experiencing this.
