### ISSUE TITLE
sponsorblock extension request for firefox 85

### ISSUE THREAD

**Issue by Dev-i-l** [mozilla-mobile/fenix#17150]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
many people use sponsorblock with youtube to skip sponsors currently it's not available in fenix
### Who will benefit from it?

everyone

**Comment by sheikh-azharuddin** [comment]
Create custom add on collection in nightly ... Simple

**Comment by anotherus3r** [comment]
> Create custom add on collection in nightly ... Simple

Note that custom add-on collections, to my knowledge, aren't available in stable releases of Fenix.

**Comment by kbrosnan** [comment]
We are not keeping open issues for specific extensions. The team is tracking specific webextensions APIs.
