### ISSUE TITLE
Please bring back the ability to share all private tabs

### ISSUE THREAD

**Issue by amjd** [mozilla-mobile/fenix#17152]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I use Firefox with "Open links in a private tab" setting enabled, like many others I'd imagine. It's mainly because I prefer to view random links in isolation and only switch to my normal browsing session if necessary, e.g., if I need to login or something. This setup works similar to using Firefox Focus as the default browser and sharing URLs where you need to login to regular Firefox.

The problem comes when tabs accumulate in private browsing. To prevent them from being lost by accidentally closing Firefox, I used to share these tabs to my desktop Firefox to read later. But the latest update has removed this feature from private browsing, even though it's present in normal browsing.

### How do you know that this problem exists today? Why is this important?
I tried sharing some tabs I had open in private browsing with my desktop Firefox today when I realized this feature has been removed. I'm not sure how many others share this workflow, but for me this feature was kinda important. 

Another way to solve this problem would be to allow transferring selected tabs (with a shortcut to select all) to normal browsing mode from private browsing, hence persisting them. One could then consume them either in Fenix or share to desktop. A few issues have already been raised requesting the same: #5170, #10132, #13788

### Who will benefit from it?
A section of people who primarily use Fenix in private browsing mode. It could also be useful for others occasionally, and doesn't really take away from their experience.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9183)

**Comment by amjd** [comment]
@amedyne Hi, is there any update on this? More issues have been raised requesting to add the feature of moving tabs to regular browsing which you can see in #10132, so I believe others also need a way to conserve private tabs.

Ideally I'd prefer for both features (a. sharing selected private tabs via sync i.e. this issue and, b. moving selected private tabs to regular browsing - #10132) to be available as they give users the most flexibility to choose their own workflow.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810783

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
