### ISSUE TITLE
FNX3-15762 ⁃ [Bug] three different toggle styles within Fenix

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1716]
There was already #1655 to fix the color of the toggle in the quick settings (open a website and press the lock icon) but this change regressed the disabled state AND the enabled state is still wrong. Also the "request desktop website" toggle is different.

![](https://user-images.githubusercontent.com/1100614/56313030-dd075000-6151-11e9-9bb0-5ffc8849c268.png)

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision aa117b1ea6dfaa9ac10e9c6817a3636120acce38

**Comment by AmyYLee** [comment]
Hi, can you please use this as a reference for disabled/enabled states for toggles across Fenix. This is for light and dark themes
<img width="550" alt="Screen Shot 2019-04-26 at 11 25 05" src="https://user-images.githubusercontent.com/5992746/56818622-02612180-6816-11e9-9f5c-07f4749afddd.png">

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 4/29 build.
devices:
Mi 4i (Android 5.0.2)
Pixel (Android 9 )
Galaxy Tab 3 (Android 8.0)
