### ISSUE TITLE
[Bug] [L10n] Close private tabs notification is not translated in many languages

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17165]
### Preconditions
In Settings - Languages set the device to Chinese.
## Steps to reproduce
1. Launch Fenix and go to private mode;
2. One one or more tabs;
3. Observe the Close private tabs notification;
### Expected behavior
The Close private tabs notification is translated in Chinese;
### Actual behavior
The Close private tabs notification is not translated in Chinese;

### Notes
This is also reproducible for Romanian, Spanish, Arabic, German.
### Device information

* Android device: Pixel 2 (Android 9), OnePlus 6T (Android 9)
* Fenix version: Nightly 201221 GV 86 from 12/21

**Comment by Delphine** [comment]
On Pontoon, I see these strings as translated for all these languages since more than a year ago. The string should definitely appear localized for all these locales

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 201223 GV 86 from 12/23 with Pixel 2 (Android 9).
I will close the issue and remove the qa:needed label.
