### ISSUE TITLE
[Bug] [L10n] "Report Site issue" is not translated in many languages 

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17166]
### Preconditions
In Settings - Languages set the device to Chinese.
## Steps to reproduce
1. Launch Fenix and go to three-dot menu;
2. Observe the "Report Site issue" from the three-dot menu;
### Expected behavior
The  "Report Site issue" is translated in Chinese;
### Actual behavior
The  "Report Site issue" is not translated in Chinese;

### Notes
This is also reproducible for Romanian, Spanish, Arabic, German.
### Device information

* Android device: Pixel 2 (Android 9), OnePlus 6T (Android 9)
* Fenix version: Nightly 201221 GV 86 from 12/21

**Comment by Delphine** [comment]
I don't see any "Report Site issue" string that has landed in our l10n quarantine repo. Maybe it's hardcoded and needs to be exposed?
If it has been exposed, please link to string ID. Thank you

**Comment by ebalazs-sv** [comment]
Hi! In the strings.xml file, this is what I had found regarding the "Report site issue" string: https://github.com/mozilla-mobile/fenix/blob/6040f18a6b7524a84f54660480188eaed7931000/app/src/main/res/values/strings.xml#L94

**Comment by Delphine** [comment]
Thank you! I confirm we never got that string on our side, so it hasn't been exposed for l10n yet. Not sure if it is needed for a future release, so this might be expected? Will let Fenix team chime in

**Comment by amedyne** [comment]
@Delphine let's have this translated.

**Comment by Delphine** [comment]
We still have not received this string on our end. 
If this string is needed for a given release, a mobile dev should expose this in the Fenix strings file, so that it will then get imported to our localization repo. Thank you!

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 88.0.0-beta.2 from 3/29 with Pixel 2 (Android 9) when set to Punjabi.

**Comment by Delphine** [comment]
This is expected as it's a string only used in Nightly, that doesn't show up on Beta or Release.
Thus closing for now
