### ISSUE TITLE
[Bug] [L10n] Download notification is not translated in many languages

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17168]
### Preconditions
In Settings - Languages set the device to Chinese.
## Steps to reproduce
1. Launch Fenix and go to https://www.thinkbroadband.com/download;
2. Tap to download a file;
3. Observe the Download notification;
### Expected behavior
The  Download notification is translated in Chinese;
### Actual behavior
The  Download notification is not translated in Chinese;

### Notes
This is also reproducible for Romanian, Spanish, Arabic, German.
### Device information

* Android device: Pixel 2 (Android 9), OnePlus 6T (Android 9)
* Fenix version: Nightly 201221 GV 86 from 12/21

**Comment by Delphine** [comment]
I'm not sure which string this is exactly, so that I can check against Pontoon. Could you please link to the string ID? thank you!

**Comment by ebalazs-sv** [comment]
Hi! I had searched in the strings.xml file for the Download notification but was not able to find any strings regarding this.

**Comment by Delphine** [comment]
I can not find this string on our side either. Is it landing later perhaps, and for a future release? Otherwise, we should expose it to localization

**Comment by ebalazs-sv** [comment]
This issue is also reproducible on RC 87.0.0-rc.1 from 3/17 with Pixel 2 (Android 9) in Chinese.

**Comment by Delphine** [comment]
Hmm I just checked against the latest Beta I have, which is 97.0.0-beta.6 from 3/16; and this string appears translated for all locales.
Could you please recheck? (They have been translated for over 2 years)

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 87.0.0-beta.6 from 3/16 with Pixel 2 (Android 9).
Screenshot with the issue:
![rsz_screenshot_20210324-091716](https://user-images.githubusercontent.com/48799384/112270761-c4c7d600-8c82-11eb-95f4-ff8d3d92c44c.png)

**Comment by mcarare** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/9964 in AC for tis issue.

**Comment by Delphine** [comment]
Hmmm I'm wondering how come on the same build, I see that string translated 🤔

**Comment by lobontiumira** [comment]
This is not fixed yet on the 3/30 Nightly build. Tested with German, and Arabic, on Google Pixel (Android 10), and on an x86-emulator Nexus 9 (Android 9).
The notification isn't translated:
![l10n](https://user-images.githubusercontent.com/40694158/112963959-8b92d880-9150-11eb-9849-0479f3e665f8.png)

I'll remove the qa:needed label for now.

**Comment by mcarare** [comment]
@lobontiumira Can you please recheck in the next Nightly? I tested on the latest master and the button text is translated. Thank you!

**Comment by lobontiumira** [comment]
@mcarare I tested again on the 3/31 Nightly build from 5:07AM, with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9), with German, and the download notifications are not transalted:
![german](https://user-images.githubusercontent.com/40694158/113103473-fe12bf80-9207-11eb-9e3e-4e9307c5f776.png)

**Comment by mcarare** [comment]
@lobontiumira I tested this on the latest Nightly in the store. Following the steps from the initial post in this issue, the notifications are translated in all languages. 
If you are following other steps than the ones described, please list them exactly so we can identify if this is the same bug or another issue. Thank you!

**Comment by lobontiumira** [comment]
@mcarare the steps I followed are:
1. Set the language of the device to German (Deutsch).
2. Make sure Fenix follows the system's language.
3. Go to https://www.thinkbroadband.com/download.
4. Tap to download a file.
5. Observe the Download notification.

If I set the German language in Fenix - Settings, the download notifications are translated.

**Comment by mcarare** [comment]
@lobontiumira Please confirm that Fenix was already opened in the background when you changed the system language. And that with Fenix closed or restarted after the system locale change the buttons are translated. 
If that is the case I will open a new issue for that and you can confirm this issue is fixed for the steps described in the first post. Thank you!

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible on the latest Release (v88.1.0) with French language. Tested on HTC Nexus 9 (Android 7.1.1).
