### ISSUE TITLE
[Bug] Report site issue is the wrong color in Dark Mode

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17175]
Pixel 3 Steps to Reproduce
1. Set device to Dark Mode
2. Open Fenix (nightly)
3. Open three-dot kebab menu
4. See that "Report Site Issue..." icon is the wrong color :(
<img width="325" src="https://user-images.githubusercontent.com/43795363/102816078-064e9980-4393-11eb-8f62-a679db41f810.png">

**Comment by ekager** [comment]
Closing as dupe of #11367
