### ISSUE TITLE
FNX-5205 ⁃ Remove search button from library

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1717]
We currently have a non-functioning search button in the library view. Do we want to remove this for beta?

@vesta0

**Comment by sblatz** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/56313077-8cb6d080-6106-11e9-8214-a9bbf9e844a3.png">

**Comment by vesta0** [comment]
YES! Thanks for catching that @sblatz !

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest version1.0.1917 (Build#11121209) with Samsung Galaxy Tab S3 (Android 8.0), and Xiaomi Mi4i (Android 5.0.2).
