### ISSUE TITLE
[Bug] White screen displayed when minimizing Suggested logins menu

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#17170]
## Steps to reproduce
1. Access `accounts.google.com`.
2. Tap on the arrow in order to expand the `Suggested logins` menu.
3. Minimize the `Suggested logins` menu.
### Expected behavior
The `accounts.google.com` webpage is correctly displayed.
### Actual behavior
White screen displayed when minimizing Suggested logins menu
### Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 21/12.**

Note that I had to refresh the page by scrolling down in order to see the webpage.
![ezgif-4-7a5164cde123](https://user-images.githubusercontent.com/42831109/102791545-d661bf00-43af-11eb-85c1-410ed6fac00e.gif)

**Comment by codrut-topliceanu** [comment]
I have managed to reproduce this bug, though intermittently, on a Pixel 3XL (Android 10) and only while the url toolbar was set to bottom. 

If you have a large number of  suggested login entries, when the `loginPicker` is expanded the `engineView`(GV) element of the layout is set to 0 height, then when loginPicker is shrunk back down and `engineView`'s height is restored but the view remains blank, sometimes for a few seconds other times until a touch event is sent.

@agi I think this might be a GV issue, what do you think?

GIF:
![missing web view content](https://user-images.githubusercontent.com/60002907/104026135-35a43980-51ce-11eb-92dd-4f85f72a327a.gif)

**Comment by Mugurell** [comment]
An interesting detail for when I tried testing this is that on twitter it does not reproduce.
An then on gamespot I see it 8/10 cases. Same device, same app.
So if this would be site specific maybe in some cases something is stuck in GV rendering, when it goes from a height like 1000 -> 0 -> 1000?

**Comment by Mugurell** [comment]
A profile I took - https://share.firefox.dev/39hTIpj

**Comment by agi** [comment]
Yeah this sounds like a Gecko bug to me too.

**Comment by codrut-topliceanu** [comment]
@agi Do we have a bugzilla link for this?

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1687823

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
