### ISSUE TITLE
[Bug] "Desktop Site" option prior to connection is not available

### ISSUE THREAD

**Issue by ShamrockLee** [mozilla-mobile/fenix#17176]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

The mabile version of a website often has fewer functionalities than the Desktop version, and sites such as Google Form require mobile client to switch to certain apps or to have certain local services ready. These problems can be bypassed with the "Desktop Site" option provided by the browser.
However, this option becomes unavailable before connection on Fenix, as a tab seems not to be "truely" created untill the Enter is hit in the address bar.

## Steps to reproduce
1. Install Fenix from F-Droid or Aurora store
2. Open the app
3. Tap the "+" or "+ Private Tab" button to create a tab
4. Tap the three-dotted menu icon to see the menu

### Expected behavior
Option that allows user to visit a website as a desktop client (which is available on Fennec)

### Actual behavior
Such option does not appear in the menu untill the connection is established.

### Workaround
Type and connected to `about:blank` and use the then-available option.

### Device information

* Android device: Android 10 (kernel: 4.9.186-perf+)
* Fenix version: 81.1.5 (Build #2015769595)

**Comment by sheikh-azharuddin** [comment]
The desktop site button needs to be added to the homepage 3 dot menu to solve the issue...

Additionally a setting could be added to always use desktop site.. 

![Screenshot_20201222-113920550 (1)](https://user-images.githubusercontent.com/58127841/102855293-648a8380-444a-11eb-8d59-f5f41a8ebcc5.jpg)

**Comment by LaurentiuApahideanSV** [comment]
The feature you requested will be implemented by https://github.com/mozilla-mobile/fenix/issues/17800. I will close this issue as it will be handled there.
