### ISSUE TITLE
[Bug] Fenix tries to DNS connect to telemetry although I opted out

### ISSUE THREAD

**Issue by addas** [mozilla-mobile/fenix#17188]
## Steps to reproduce
• Fresh Install Fenix
• Use VPN Adblocker on Android (Like AdGuard with DoH) | Optional: To get a log if you are not rooted
• Opt out Telemetry by unticking all Data Collection
• Force Close Firefox
• Launch Fresh Start Firefox

### Expected behavior

No any request to telemetry whether DNS requests or HTTP/HTTPS requests

### Actual behavior

Tries to connect to dns://incoming.telemetry.mozilla.org/ and if you block it, it will retry for 12 times

### Device information
* Android device: Samsung Note9 running Android 10
* Fenix version: 84.1.1

**Comment by kbrosnan** [comment]
This should be under the Glean team's control. This may be the opt out ping. Which is used to remove some data associated with that ID. 

@mdboom are you able to find someone from the Glean team to track this down?

**Comment by st3fan** [comment]
If you force quit, we may be retrying the 'opt-out' ping. Yes there is such a ping - it will instruct the Mozilla telemetry servers to delete your previously received telemetry data. My bet is that this ping gets queued to be sent when you flip the checkbox and then it goes out at the next scheduled telemetry push. Which will also be the last one.

But, if you force quit the app and then block `incoming.telemetry.mozilla.org`, it stays queued but will fail to send.

Simple solution: allow Firefox to send this final ping and then block all the things.

If there is a bug here, it may be that we should drop pings older than X days or after Y retries.

**Comment by addas** [comment]
I allowed the "last" ping and restarted and still requesting after force quit.

Also I am on fresh installation of Firefox APK (Fenix) from Play Store.

Is it possible that "dom.security.unexpected_system_load_telemetry_enabled" boolean is still true although I opted out? (I cannot check because I am on stable and "about:config" is blocked by Mozilla)

**Comment by addas** [comment]
Is there any way I can enable `about:config` in stable Fenix (Android Firefox)?

**Comment by badboy** [comment]
Hey, Glean team member here.
I'm looking into it and try to see what's going on.

**Comment by addas** [comment]
I can confirm after switching to Fenix Beta I was able to stop the request with `about:config` boolean `dom.security.unexpected_system_load_telemetry_enabled` and allowing the last access to the server to erase my clientID.

Thank you all.

**Comment by addas** [comment]
As kbrosnan and st3fan mentioned, this is the final erase telemetry clientID ping and that means this is not a bug.

Please close the issue as it has been solved.

Thank you all and happy new year!
