### ISSUE TITLE
Allow "on the fly filters" for search bar results using special "filter tokens" like on desktop (* for bookmarks etc.)

### ISSUE THREAD

**Issue by CombeeMike** [mozilla-mobile/fenix#17184]
### What is the user problem or growth opportunity you want to see solved?
Make bookmarks, history etc. easier accessible via a unified interface (the search bar) by allowing to limit the shown search results to specific areas using special "search tokens" like `* ...` for bookmarks only, `? ...` for search suggestions, `^ ...` for history etc.

Basically I'd like to see the same functionality as it already exists in desktop Firefox described [here](https://support.mozilla.org/en-US/kb/address-bar-autocomplete-firefox#w_changing-results-on-the-fly) in the `Changing results on the fly` section. Whilst all those tokens are handy at times, the most important one for me is the bookmark search using `*`.

I recently realized that Chrome (at least on desktop) is also supporting the `* ...` pattern so it at least seems like this feature is somehow being "standardized".

#### Why I'd like to see this?

I find it easier to e.g. type `* sta` in my search bar instead of finding the `Der Standard` bookmark in the "bookmarks" menu. This is even more true when opening bookmarks synced from my desktop Firefox as the bookmarks menu can be deeply nested here which makes "findability" sometimes really hard.

I know that typing `sta` is already possible today & the search result already contains the bookmark as well, however, it is "buried" somewhere in between results from history, search suggestions etc.

### How do you know that this problem exists today? Why is this important?

I'm just a user of the app with a feature request that I'd personally find very helpful. I have not done any requirements engineering here, so I can't really answer this & the following question in a useful manner...

### PS

I know that the title is very badly chosen but I can't really think of anything more meaningful. Feel free to either change the title right away or suggest something better in the comments. Sorry & thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9207)

**Comment by ohhai** [comment]
Should be reopened, as for me. @CombeeMike is it possible for you?

**Comment by CombeeMike** [comment]
@ohhai I cannot re-open this issue. I guess this needs to be done by some repo maintainer 🤷‍♂️

**Comment by ohhai** [comment]
@mcarare,  @amedyne,  you did some changes here - could you please reopen?

**Comment by amedyne** [comment]
Labeling as a "feature request" so this can be evaluated as we plan future changes for Fenix.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807725

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
