### ISSUE TITLE
Bookmarked sites are not autocompleted in the address bar when 'Search browsing history' is switched off

### ISSUE THREAD

**Issue by neekt** [mozilla-mobile/fenix#17182]
## Steps to reproduce

1. On a fresh Firefox install, ensure that 'Autocomplete URLs' is turned on (Settings > Search > Autocomplete URLs)
2. Switch off 'Search browsing history' (Settings > Search > Search browsing history)
3. Bookmark a site that is not listed in Alexa top sites (e.g., https://www.depop.com/)
4. Begin typing "depop.com" in the address bar

### Expected behavior

After typing the first few letters, depop.com should be autocompleted in the address bar. This should happen regardless of the 'Search browsing history' option.

### Actual behavior

depop.com is not autocompleted in the address bar if 'Search browsing history' is switched off. Other non-bookmarked sites (e.g., amazon.com) are.

### Device information

* Android device: Xiaomi Mi A2, running Android 10 (Android One)
* Fenix version: 84.1.1

**Comment by neekt** [comment]
An additional comment; the current autocomplete behaviour is not just inconsistent with both Firefox for desktop and the old Firefox for Android, it's also inconsistent with Chrome for Android - which autocompletes bookmarked URLs, and not sites that aren't bookmarked.

**Comment by sheikh-azharuddin** [comment]
But it is showing here..

![Screenshot_20201222-113237271](https://user-images.githubusercontent.com/58127841/102854871-7586c500-4449-11eb-8675-cbc874c5c3b3.jpg)

**Comment by neekt** [comment]
Interesting. Not for me:

![2020-12-22 18 27 54](https://user-images.githubusercontent.com/5132610/102861457-cca98b80-4483-11eb-9a42-1dafb7155b75.png)

**Comment by mcarare** [comment]
> Interesting. Not for me:
> 
> <img alt="" width="40%" src="https://user-images.githubusercontent.com/5132610/102861457-cca98b80-4483-11eb-9a42-1dafb7155b75.png">

@neekt It does show for you also, the suggestion marked with a ⭐  is the suggestion from bookmarks.

**Comment by neekt** [comment]
@mcarare I'm not talking about suggestions, I'm talking about autocompleting URLs in the address bar. Like this in Chrome for Android:

![Screenshot_20201223-081929](https://user-images.githubusercontent.com/5132610/102934453-3fece500-44f8-11eb-9922-819b262f4342.png)

**Comment by neekt** [comment]
@sheikh-azharuddin does this still work if you clear your browsing history? Autocomplete does seem to work if Search Browsing History is switched on and the bookmarked site is in your browsing history. Otherwise, not.

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin does this still work if you clear your browsing history? Autocomplete does seem to work if Search Browsing History is switched on and the bookmarked site is in your browsing history. Otherwise, not.

yes this still works after clearing browing history

![Screenshot_20201223-074900289](https://user-images.githubusercontent.com/58127841/102951707-7ecc6c00-44f3-11eb-8619-dfefb1c07985.jpg)
![Screenshot_20201223-074911655](https://user-images.githubusercontent.com/58127841/102951712-82f88980-44f3-11eb-9d71-434714a08d39.jpg)

**Comment by sheikh-azharuddin** [comment]
On a side note another critical bug found due to this auto complete feature... While deleting the character from address bar URL it deletes one character and then it auto completes so literally you have to press delete button twice to delete a single character.. . I will file new issue

**Comment by mcarare** [comment]
@neekt , @sheikh-azharuddin what keyboards are you using?

**Comment by neekt** [comment]
@sheikh-azharuddin Thanks for confirming that. 

After a little bit more testing, it seems that if 'search browsing history' is switched off (Settings > Search > Search browsing history), then bookmarked URLs aren't autocompleted, regardless of whether the site is in the history or not.

So with the following settings, bookmark URLs are not autocompleted:

![Screenshot_20201223-182949](https://user-images.githubusercontent.com/5132610/102972342-fed3ef80-454e-11eb-8c2f-fa67e77b8655.png)

**Comment by neekt** [comment]
Hi @mcarare, I've been using AnySoftKeyboard and Gboard. The results are the same with both.

**Comment by neekt** [comment]
And after a little more testing I've found that if I have search browsing history switched ON and search bookmarks switched OFF, I still get bookmarked URLs being autocompleted.

My conclusion from this is that 'Search bookmarks' doesn't do anything at all. Autocompleting bookmark URLs is entirely dependent on 'search browsing history' being activated.

**Comment by mcarare** [comment]
@neekt Maybe the setting description is not clear enough, but that setting is for the suggestions shown in the awesomebar, not the autocomplete feature.

**Comment by mcarare** [comment]
Tagging UX for feedback on expected auto-complete behavior and the Settings description.

**Comment by neekt** [comment]
> @neekt Maybe the setting description is not clear enough, but that setting is for the suggestions shown in the awesomebar, not the autocomplete feature.

I think there are a couple of issues here:

1. As in the original post and subsequent comment, I would still expect autocomplete to work for bookmarks - as it does in Firefox for desktop, the old Firefox for Android (Fennec), and in other browsers (e.g., Chrome) - regardless of the search history setting.
2. Even with 'search bookmarks' switched off and the history completely cleared, bookmarks still suggested (as well as autocompleted) when 'search browsing history' is switched on.

**Comment by sheikh-azharuddin** [comment]
Actually there is one setting missing...I have filed a ticket for the same

https://github.com/mozilla-mobile/fenix/issues/17196

**Comment by neekt** [comment]
I have updated the issue to make it properly reproducible, and to be clear this is about autocompleting URLs in the address bar, which is affected by the 'Search browsing history' option. The 'Search bookmarks' option is irrelevant to this particular issue (as @mcarare has kindly pointed out.
