### ISSUE TITLE
[Bug] Disable layers.acceleration.force-enabled doesn't render web content at all

### ISSUE THREAD

**Issue by allhavebrainimplantsandmore** [mozilla-mobile/fenix#17198]
## Steps to reproduce
Set to true layers.acceleration.disabled
Set to false layers.acceleration.force-enabled 

### Expected behavior
Able to open web pages
### Actual behavior
Shows black canvas where web content normally display. 
### Device information
Android 5.0.1
* Android device: Samsung Galaxy Note 4
* Fenix version: ?
Tried 83 and 84.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1684081

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
