### ISSUE TITLE
FNX3-15765 ⁃ [Bug] tracking protection label in quick settings is almost invisible

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1719]
### Steps to reproduce
1. open a website
1. press the padlock icon
1. if tracking protection is enabled disable it, close and open the quick settings again

### Expected behavior
You can read "Tracking Protection".

### Actual behavior
It's very difficult to read "Tracking Protection". If you can' read it you don't know what you can enable with the toogle.

![Screenshot](https://user-images.githubusercontent.com/1100614/56313483-ffe63400-6152-11e9-98b6-76e6fabe802c.png)UNITO-UNDERSCORE!20190417-203416!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision aa117b1ea6dfaa9ac10e9c6817a3636120acce38

**Comment by sv-ohorvath** [comment]
Verified as fixed on Pixel and HTC Desire 820 (Android 6)
