### ISSUE TITLE
PWAs with no name default to "Web page"

### ISSUE THREAD

**Issue by jurica1304** [mozilla-mobile/fenix#17192]
### Steps to reproduce
1. go to https://ocjene.skole.hr/login
2. open menu in toolbar
3. tap 'Install' 

### Expected behavior
It should ask you to add shortcut to launcher home page with the website title 'e-Dnevnik za učenike i roditelje'. 

### Actual behavior
It wants to add shortcut with the title 'Web stranica' meaning 'Web page'. 
App language is Croatian. Normal behavior in Google Chrome. 

### Device information

* Android device: EMUI 8.0 - Android 8.0
* Fenix version: 83.1.0 (Build #2015776403)
AC: 63.0.9, fc54c566e
GV: 83.0-20201112153044
AS: 63.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9211)

**Comment by mcarare** [comment]
The problem is within the website itself, the manifest does not provide a `name` or a `shortName`.

But maybe we should fallback to the session title and only after that to the hardcoded title.

**Comment by anotherus3r** [comment]
An option to change the name before adding it to the homescreen, like in Chrome, would also be great. Is there an open issue/feature request for this already?

**Comment by mcarare** [comment]
@anotherus3r I think you are referring to a shortcut, AFAIK a PWA name should not be changed.

**Comment by anotherus3r** [comment]
@mcarare Opening, for example, Twitter in Chrome and choosing the option to add it to the homescreen (I presume that's the equivalent to Fenix's "Install" option) still let's me change the name. Or did I make a mistake somewhere?

**Comment by mcarare** [comment]
@anotherus3r No, you are right. I am just saying that if Chrome lets you change a PWA's name, it does not mean that it should. IMO the name should respect PWA's name from manifest if that name is set.

**Comment by anotherus3r** [comment]
@mcarare Oh, understood.😉 Though this _would_ be useful in situation like this one.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807422

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
