### ISSUE TITLE
Provide an option to show search results after local results (history, bookmarks, tabs etc)

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17196]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently in fenix the search results are showing ahead of browsing history and bookmarks. The desktop version has the setting "Show search suggestions ahead of browsing history in address bar results" which is by default disabled in desktop version however in mobile version the behaviour is opposite and there is no preference to configure this.
Please add this option in fenix version similar to desktop version

### How do you know that this problem exists today? Why is this important?
With current settings bookmarks suggestions are pushed to the end, making them pointless...also the behaviour should be same as desktop version.

Desktop version
Bookmarks suggestions
History suggestions
Search result

Fenix
Search result
History suggestions
Bookmarks suggestion

### Who will benefit from it?
All users.. behaviour should be consistent and similar to other browsers

![Screenshot_20201223-174512527 (1)](https://user-images.githubusercontent.com/58127841/102995243-a7ca1c80-4546-11eb-93af-51723d6cfbc1.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9214)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807724

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
