### ISSUE TITLE
[Bug] Changing language while notifications are showing will not update notification

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#17190]
## Steps to reproduce
1. Enter Private Browsing Mode
2. Open a tab
3. Open device notifications and see PBM notification 
4. Go to settings and change the language 

<img width="322" alt="image" src="https://user-images.githubusercontent.com/43795363/106054898-426fcb00-60b2-11eb-9270-ae699553e216.png">

### Expected behavior
Notification re-creates and reflects new language

### Actual behavior
Notification does not recreate. Language updated only on app restart. 

### Device information

* Android device: Android 11, Pixel 3
* Fenix version: Nightly

**Comment by eliserichards** [comment]
Expected flow (Google Chrome)
1. Open Chrome
2. Open a private browsing session, see the PBM notification in the device notifs
3. Background Chrome
3. Go to device settings, change language
4. Foreground Chrome, see that the language of the notification changes once Chrome is brought back to the foreground

**Comment by Mugurell** [comment]
@eliserichards I'm seeing this ticket in "Ready for engineering"
so with the current backlog running low I am wondering if you are actively working or planning to work on this or it can be picked up by others?

**Comment by eliserichards** [comment]
## For QA

Fenix decides it's language in two ways: either following the device language, or choosing one from Fenix settings. When the user chooses a language in Fenix, we no longer care if the user changes their device language (we persist the language set in the app). 

Steps to test this fix: 
1. Open Fenix
2. Open a private tab(s), see the notification in the system notifications
3. Go to Fenix app settings, select another language
4. Look at the notifications and see the notification language has updated

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with Pixel 3 (Android 11).
