### ISSUE TITLE
FNX-5207 ⁃ [UX] Browser Menu

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#172]
GH Issue to track design work.

**Comment by bbinto** [comment]
@lime124 and @shorlander please check with @boek if this has already been tackled in milestone 1

**Comment by ekager** [comment]
We have been working on #133 but it's fairly straightforward and open to any changes

**Comment by mheubusch** [comment]
@lime124 @ekager The browser main menu in the Fenix build has 2 more functions than were specified in the design files (Share, Report Site Issue). The issue #133 is closed already - should I open a separate engineering bug to remove these items as well as the corresponding Share sheet?

**Comment by lime124** [comment]
whoops! totally missed this one! 

i'm going to move this to our UX MVP board 

@topotropic - see Michelle's comment above - can you file a follow up github issue (bug) if needed and link here. Otherwise if everything is good, please close this issue. 

@bifleming the epic is #116

**Comment by lime124** [comment]
closing - this is done!
