### ISSUE TITLE
[Bug] New tabs are added to the bottom of the tab list after updating to 84.1.1

### ISSUE THREAD

**Issue by mirko77** [mozilla-mobile/fenix#17205]
## Steps to reproduce
Open a new tab

### Expected behavior
Tab is added at the top of the tab list

### Actual behavior
Tab is added at the bottom of the tab list

### Device information

* Android device: Xiaomi MI 9 SE
* Fenix version: 84.1.1

**Comment by mcarare** [comment]
This is the expected behavior, as implemented for https://github.com/mozilla-mobile/fenix/issues/11376.

**Comment by mirko77** [comment]
I find it counter-intuitive, like other users in the discussion you just tagged, see #16884
New items on a list go at the top on pretty much 99% of UI. On Gmail, when a new email comes in, would you expect it to be at the bottom?
