### ISSUE TITLE
FNX3-15767 ⁃ "Report a problem" should close quick settings

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1720]
### Steps to reproduce
1. open a website
1. press the padlock icon
1. press on the "Report a problem" link in the "Tracking Protection" section

### Expected behavior
The "Report Site Issue" website opens and the quick settings overlay disappears.

### Actual behavior
The "Report Site Issue" website opens and the quick settings overlay keeps open.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision aa117b1ea6dfaa9ac10e9c6817a3636120acce38

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/6 build.
devices: Galaxy Note 8 (Android 9), HTC Desire 820 (Android 6.0.1)
