### ISSUE TITLE
[Bug] Top sites are not saved or synced between devices and/or the same userid.

### ISSUE THREAD

**Issue by handyguy2** [mozilla-mobile/fenix#17211]
As near as I can tell, Firefox does not save nor sync Top Sites. Every device I have needs to have it's top sites recreated, and the changes are never synced nor saved. I am currently running Windows firefox 84.0.1 and android nightly 201219 17:00 build #2015782347, but it has never worked on any version or any device. i would assume that only pinned top sites should be saved and synced.
https://bugzilla.mozilla.org/show_bug.cgi?id=1453645 says it was resolved, but I think not.
It has been mentioned that top sites are not synced between windows and android firefox  versions. However, they are not even synced between android devices on the same account. They need to be  recreated every time you cold start the browser.

**Comment by kbrosnan** [comment]
Duplicate #7936
