### ISSUE TITLE
FNX-474 ⁃ Document a branching/tagging strategy for beta and release builds

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1721]
Document how we will control (beta) releases and a tagging / branching strategy in general.

Make sure this aligns with what release engineering can do in terms of automation; for example, could we add tags in a specific format to start a beta / release process that sends builds to the GPS?

We don't have to do what our other products do. But let's learn from those other products. For example, are we happy with how we did things in Focus?

Is there a standard and already documented method that we can follow? 

## Engineering / Release Process
> Please note that this is full of assumptions that we have not talked about, but I hope it is a good starting point for a discussion. Alternatives are welcome.

### Version Numbers
We use [Semantic Versioning 2.0.0](https://semver.org/)

We ship features in major releases: v1.0, v2.0, v3.0

We ship what? in minor releases: v1.1, v1.2  - unclear if we need this if we stick to new features in major releases and bug fixes in patch releases.

We ship bug fixes in patch releases: v1.0.1, v1.0.2, v2.0.1

### Branch Management
As a starting point I want to propose that we follow the following model:

Development happens on master.

Master is the next version that we want to ship. All new work happens on master.

If you there is doubt whether the thing you are working on will ship in a next release, then you can do two things:

* either develop it on a separate branch and merge it in later
* land it on master but put it behind a feature flag so that the feature can ship disabled if needed

The latter is not always possible, but it should be preferred because it allows us to have features in beta and decide very late if they should ship or not.

When we feel master is functional enough to ship, we create a major release branch, for example `v1`.

The release branch should be feature complete and no new feature work should land on it. The only things that can land on a release branch are bug fixes or a configuration changes. For example to disable a feature behind a flag.

When we are ready to ship a v1.0 Beta, we tag the release branch with a v1.0b1 tag. This triggers CI and creates a Beta build, which is then pushed to the _Test Track_ of the _Beta App_. After QA sign off, this build can be promoted to the _Release Track_ of the _Beta App_.

When we are ready to ship a v1.0 release, we tag the release branch with a v1.0. This triggers CI and creates a release build, which is then pushed to the _Test Track_ of the _Release App_. After QA sign off, this build can be promoted to the _Release Track_ of the _Release App_.

### Channels & CI
_Nightly_ has no special needs and should just build every night from `master` and go to the Nightly channel automatically when the build is green.

_Beta_ ships on a fixed cadence but is controlled manually by us. Ideally we place a tag to trigger a CI build that builds _Fenix Beta_ and pushes it to the Play Store. Instead of going straight to users, it should probably go to a _Test Track_ on the _Beta Application_ to give QA a chance to test it. We can then promote this build to the _Release Track_.

_Release_ ships on a fixed cadence but is controlled manually by us. Ideally when we are happy with a specific Beta release, we place a tag on the same commit to trigger a CI build that builds _Fenix Release_ and pushes it to the Play Store. Instead of going straight to users, it will go to a _Test Track_ on the _Release Application_ to give QA a chance to test it. We can then promote this build to the _Release Track_.

**Comment by sblatz** [comment]
This is **mostly** done. [Current process found here](https://github.com/mozilla-mobile/fenix/wiki/Release-Process). Let's finish this up :)

**Comment by liuche** [comment]
Blocked on @liuche beta/nightly channel work, and related to #4305

**Comment by sblatz** [comment]
@liuche is it correct that this is no longer blocked?

**Comment by liuche** [comment]
This strategy is mostly correct, but there are a few minor changes that need to happen. I think the output should be that we document the final Nightly/Beta/Release process on the wiki.

That final part will be waiting on the Beta channel releng work to be finished.

**Comment by liuche** [comment]
Closing this with the[ updates to the release checklist](https://github.com/mozilla-mobile/fenix/pull/6489), that include how to cut a beta release.
