### ISSUE TITLE
move configured preferences to the top

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17214]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently about:config preferences are showing in alphabetical order regardless whether you set or not.
In chrome the settings which are configured using chrome://flags are moved to the top..this makes it easier to remove or revert any settings if it cause any unexpected behaviour..also it will be easier to know which settings are configured rather than browsing whole list

### How do you know that this problem exists today? Why is this important?
It's really hard to scroll through the list to know the configured settings

### Who will benefit from it?
All users

**Comment by kbrosnan** [comment]
about:config UI is not controlled by the Fenix team.
