### ISSUE TITLE
Add new tab should act the same as first opening android firefox.

### ISSUE THREAD

**Issue by handyguy2** [mozilla-mobile/fenix#17210]
A fresh open of Android Firefox shows the URL, top sites and hamburger settings menu. Their is no focus on the URL field, so you can select any of three options: enter URL, click on a top site or select options (so you can go to bookmarks.) However, once Firefox has been opened and you select add a new tab (+) from the select tabs, the focus on the URL and that brings up a mic icon on the top right instead of the hamburger settings so you cannot go to bookmarks or top sites directly without an additional tap. This is slightly annoying as it's equally likely you may want to go to any of the 3 options. Make the add tab screen act the same as a fresh open of Firefox.

**Comment by pudup** [comment]
Yes please. I've wanted to post more or less exactly this since it's been introduced.

At worst a toggle in settings or about:config would be fine.
