### ISSUE TITLE
[Bug] Crashing when accessing old Collections item 

### ISSUE THREAD

**Issue by benjsnellings** [mozilla-mobile/fenix#17219]
## Steps to reproduce
Open an older collections item. For some reason newer ones do not cause issue. I cannot say what date exactly the issue started, as i was not paying that much attention. Some time within the last month.

### Expected behavior
Collections tab opens a new link

### Actual behavior
Onclick causes a app crash
https://crash-stats.mozilla.org/report/index/afa7cd35-6393-4825-bb91-204400201225

### Device information

* Android device: Pixel 2 XL - unrooted, lastest patch
* Fenix version: 201224

**Comment by sflorean** [comment]
Tested on Pixel 3 (Android 11) and couldn't reproduce this issue on latest Nightly build. @benjsnellings Do you have any additional steps?

**Comment by benjsnellings** [comment]
Like I mentioned in the description I cannot seem to create a new collections item with the issue, only for items that were made before some build

**Comment by csadilek** [comment]
@benjsnellings Would mind checking if this still happens for you in latest Nightly? We landed some fixes that hopefully covered this.

**Comment by benjsnellings** [comment]
It appears to be working now
