### ISSUE TITLE
[Bug] Twitter behaving weirdly on firefox

### ISSUE THREAD

**Issue by Harsh-dbey** [mozilla-mobile/fenix#17229]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
open twitter on firefox mobile scroll to a tweet which contains video, wait for it to autoplay
### Expected behavior
video should play smoothly
### Actual behavior

https://user-images.githubusercontent.com/76604421/103144596-470f2f80-4752-11eb-829c-4dc8e68800ff.mp4

weird glitches
### Device information

* Android device: mido running on android 7 based on miui 11.0.2
* Fenix version: 84.1.2
  the logcat:
  [logcatfirefox.txt](https://github.com/mozilla-mobile/fenix/files/5742623/logcatfirefox.txt)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1685629

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Snowden-rgb** [comment]
> 
> 
> Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1685629
> 
> Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

I have been experiencing this too, btw what does it mean when a bug is moved from github to bugzilla?

**Comment by softvision-raul-bucata** [comment]
@Harsh-dbey Is the issue still reproducible on your side?
