### ISSUE TITLE
[Bug] support.mozilla.org strobes when scrolling in Firefox for Android in e-ink display

### ISSUE THREAD

**Issue by MarjaE2** [mozilla-mobile/fenix#17223]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Go to support,mozilla.org/en-US/kb/how-set-firefox-sync-firefox-android

Scroll down.

### Expected behavior

Safe scrolling.

### Actual behavior

Strobing. Area around "Search or Enter Address" repeatedly flashes back and white.

### Device information

Boyue Likebook Mars. Has monochrome e-ink display.

* Android device: 8.1.
* Fenix version: ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9235)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810833

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
