### ISSUE TITLE
simplify addon page and easy accessibility

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17230]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Currently if a user has installed many addons , the addons page list on any website keeps on growing..instead of one add on with name per line, add on icons can be shown with a badge to indicate the action(no of blocks etc) just like desktop version..

Also to see the add one has click many items.. click 3 dot menu, click add ons..probably a add-on icon can be added to address bar and on clicking it will show website add on page.

### How do you know that this problem exists today? Why is this important?
The add on list keeps on growing

### Who will benefit from it?

All users

![Screenshot_20201226-121010118](https://user-images.githubusercontent.com/58127841/103146781-00cac800-4774-11eb-90ea-fae1ab6abdad.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9242)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814121

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
