### ISSUE TITLE
Swipe up to show tabs

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#17238]
Swipe up to show tabs
![Firefox](https://user-images.githubusercontent.com/23485114/103163194-0d046300-4810-11eb-9d41-af21195a187d.gif)

**Comment by sheikh-azharuddin** [comment]
I would like swipe to show additional items
Like add-ons (active add ons with batch no like desktop version),  share button, page info, save to pdf, add to top sites, save to collection,desktop site etc

**Comment by Dunexus** [comment]
Seems like a duplicate of https://github.com/mozilla-mobile/fenix/issues/11862

**Comment by ekager** [comment]
Closing as dupe of #11862. Please copy over mocks/feedback there
