### ISSUE TITLE
Take a screenshot in incognito mode

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#17236]
Hi,
Please add an option to allow take a screenshot in incognito mode (like TorBrowser)
![TorBrowser](https://user-images.githubusercontent.com/23485114/103162907-0e339100-480c-11eb-8129-4365054bde78.jpg)
Thanks.

**Comment by ameaninglessname** [comment]
It's already there.
Check "Settings-Private Browsing-Allow screenshot in..."

**Comment by xmha97** [comment]
> 
> 
> It's already there.
> Check "Settings-Private Browsing-Allow screenshot in..."

Thanks, I didn't see this option. 🙏
