### ISSUE TITLE
implement best features, settings and UI from firefox lite in Fenix

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17239]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The firefox lite browser has too many features and modern UI and icons which can be used in firefox main browser to make it stand out, look more appealing and aesthetic...

Below are items which can be used in main browser(fenix)
**Features-**
Turbo mode
Screenshots
Themes
Clear cache button(optional)
Pin site
Night mode
Three dot menu
Home button
Bottom toolbar (optional) 
Smart shopping search
Block images

**Icons and menus**
**1.** Replace quit button with exit button.the desktop version also this. Not sure why use quit in fenix

![Screenshot_20201227-110533494 (1)](https://user-images.githubusercontent.com/58127841/103164595-8c575e00-4833-11eb-854b-51e03d380170.jpg)

**2.** Pin icon with rounded top site design with favicon looks way modern and appealing. **Also the pin icon color changes based on site**🤩

![Screenshot_20201227-123301869 (1)](https://user-images.githubusercontent.com/58127841/103165586-da725e80-483f-11eb-932b-b26431befa19.jpg)

**3.** Top site and bookmarks icon. Also the bookmarked sites have a blue icon here in fenix it is black..

![Screenshot_20201227-124854168 (1)](https://user-images.githubusercontent.com/58127841/103165786-eb23d400-4841-11eb-8948-11c9c94f4b89.jpg)

### How do you know that this problem exists today? Why is this important?

Some items can be modernized or adjusted to appeal users

### Who will benefit from it?

All users

**three dot menu style**
![Screenshot_20201227-110946227](https://user-images.githubusercontent.com/58127841/103164651-0a1b6980-4834-11eb-9b3b-b9de3f0cd769.jpg)
![Screenshot_20201227-111433794 (1)](https://user-images.githubusercontent.com/58127841/103164711-be1cf480-4834-11eb-8295-00296ef54eb0.jpg)

**smart shopping search**
![Screenshot_20201227-124627660 (1)](https://user-images.githubusercontent.com/58127841/103165771-ab5cec80-4841-11eb-9b84-4903272d7c13.jpg)

**Comment by zakius** [comment]
making things uglier is not appealing, that should be obvious

**Comment by cadeyrn** [comment]
Please open one issue per feature request. It doesn't make sense to have one issue for all these different features that are totally unrelated.

**Comment by sheikh-azharuddin** [comment]
Ok I will raise separate request...ideally when a company plans to move to a new version they simple don't ignore the best features of old existing browser....the point is when existing firefox had too many good features why they were not carried forward🤷🏻 simply does not make sense...

**Comment by zakius** [comment]
> ideally when a company plans to move to a new version they simple don't ignore the best features of old existing browser

been telling that to desktop department for years, don't get your hopes high

but also don't treat ugly UI as a best feature

**Comment by cadeyrn** [comment]
> ideally when a company plans to move to a new version they simple don't ignore the best features of old existing browser....the point is when existing firefox had too many good features why they were not carried forward

Your issue is about features from Firefox Lite. Maybe you don't know it but Firefox Lite is a Webkit (not GeckoView!) based product from a different and independent team that no longer exists. The mobile products from Mozilla's independent Asia department like Firefox ScreenshotGo and Firefox Lite were discontinued and neither related to the old Firefox (<= 68) nor to the new Firefox (79+, also known as Fenix). So it's really not about "ignoring" features of an old version of Firefox.
