### ISSUE TITLE
[Bug] Search pop up does not respect default search engine

### ISSUE THREAD

**Issue by bedfojo** [mozilla-mobile/fenix#17233]
Steps to reproduce

Choose a search engine as default (e.g. DuckDuckGo) which is not the first on the list of installed search engines (which is Google in the original install). 
Then select some text in a web page and choose "search" from the pop-up menu.

Expected behaviour

The search should be made using the chosen default search engine. 

Actual behaviour

The search is carried out using the first search engine on the list of installed ones. This was Google in the originally installed list. If Google is removed it is then Amazon, the next on the original list, which is used. If this is also removed it is then DuckDuckGo, third on the default list which is used.

Device information

* Android device: OnePlus 8T (out of the box, fully updated Android 11, 1 Oct 2020 security update, 1 Sep 2020 Google Play update, build number Oxygen OS 11.0.5.6.KB05BA)
* Fenix version: 84.1.2 (Build #2015783147)

**Comment by kbrosnan** [comment]
Works for me using Firefox Beta and Nightly using a [Pixel 2 XL](https://play.google.com/store/apps/details?id=org.mozilla.fenix) closing as works for me.

**Comment by bedfojo** [comment]
Still happening for me, but clearly my experience doesn't count.
