### ISSUE TITLE
Revamp three dot menu

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17246]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The existing firefox lite had really good UI for 3 dot menu. Looks way modern. If this UI is implemented in fenix it can accomodate more items, allow easier accessibility of the items and the items do stand out in the UI. The UI reminds me of Microsoft edge ..

### How do you know that this problem exists today? Why is this important?

Better view, modern UI and easy accessibility

### Who will benefit from it?
All users

![Screenshot_20201227-124854168](https://user-images.githubusercontent.com/58127841/103189384-65139600-48f2-11eb-8c7b-86a198a536bb.jpg)

**Comment by pidus** [comment]
These looks indeed nice. The current implementation has a long list. User has to play finger gymnastics if they try to reach some option that's at the top. 
![Screenshot_2020-12-30-14-36-55-862_org mozilla fenix](https://user-images.githubusercontent.com/11857051/103341375-ca12eb80-4aac-11eb-9809-121fdbd08572.jpg)

**Comment by Sciolism1** [comment]
In this request, please take the "Add-ons - Selection" to the bottom.
I'm using NoScript and on Websites who needs Custom-Settings, the way to these Add-on is to long for the thumb.
Thankx

**Comment by sheikh-azharuddin** [comment]
> In this request, please take the "Add-ons - Selection" to the bottom.
> I'm using NoScript and on Websites who needs Custom-Settings, the way to these Add-on is to long for the thumb.
> Thankx

Instead of screenshot button, they can show the add on button

**Comment by sheikh-azharuddin** [comment]
Seems Victoria is working on this...
https://mobile.twitter.com/violasong/status/1348769246642274305

**Comment by violasong** [comment]
Yep, we can close this issue in order to keep the focus on [this main one](https://github.com/mozilla-mobile/fenix/issues/14320#issuecomment-765614981). Thanks @sheikh-azharuddin for the ideas!

**Comment by MrNxbxdii** [comment]
eliminate the scroll completely, how much?

**Comment by MrNxbxdii** [comment]
its trash
