### ISSUE TITLE
In-progress downloads don't appear in the 'Downloads' window

### ISSUE THREAD

**Issue by manalog97** [mozilla-mobile/fenix#17244]
On Android 10 Lineage OS Sanders for Moto G5S+ the downloads in progress aren't shown in the 'Download' window but only in the notification area. Tapping the notification doesn't produce anything. Only completed download are shown in the Downloads section, thus, it is impossible to pause, cancel and in general manage a download in progress. 
Fenix version: 84.1.2 (Build #2015783147)

**Comment by Amejia481** [comment]
Thanks for the report, this feature hasn't been implemented yet, there is another bug for tracking it https://github.com/mozilla-mobile/fenix/issues/14961. I will close this one as dup
