### ISSUE TITLE
Huge issues with vsync [Bug]

### ISSUE THREAD

**Issue by michal1315** [mozilla-mobile/fenix#17242]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open vsynctester.com or testufo.com.
Watch how vsync not working at all.
### Expected behavior
![Screenshot_2020-12-27-21-00-51-198_com brave browser](https://user-images.githubusercontent.com/35575000/103178814-a3736b80-4886-11eb-9b67-82cb00aad708.jpg)

### Actual behavior
![Screenshot_2020-12-27-20-50-43-902_org mozilla fenix](https://user-images.githubusercontent.com/35575000/103178817-ad956a00-4886-11eb-9dd9-a9d0796a7b08.jpg)

### Device information

* Android device: Xiaomi MI6 Android 9 
* MIUI 11.0.6
* Fenix version: FF 84.1.2/86.0a1-20201225

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nighlty 210103.
### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S8 (Android 8.0.0)

**Comment by LaurentiuApahideanSV** [comment]
The issue is still reproducible on Firefox RC 89.1.1 and Nightly 2021-07-05.

### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S8 (Android 8.0.0)
