### ISSUE TITLE
Bookmark icon and bookmarked sites icon color

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17248]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

The bookmark icon in fenix lite looks better,justified and appealing and modern..however the bookmark icon in fenix looks too simple and outdated.please change the bookmark icon similar to fenix lite

Also the bookmarked sites have the star ⭐ filled with blue color which makes it stand out and justified..however in fenix the icon is filled with black color and easy to ignore

### How do you know that this problem exists today? Why is this important?

The bookmark icon and fill color should be justified and appealing

### Who will benefit from it?
All users

![Screenshot_20201227-124854168 (1)](https://user-images.githubusercontent.com/58127841/103189753-3a2a4180-48f4-11eb-85e9-50b8873da28d.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9257)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812707

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
