### ISSUE TITLE
Block images

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17247]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved? 

The firefox lite has a cool features to block images on the fly for a website. Please implement the same in fenix

Use case:
If you are browsing some private articles in front of your kids or parents you don't want them to see the images...
This feature can quickly block the images allwoing to read only the texts..😅

Also it might save bandwidth

### How do you know that this problem exists today? Why is this important?
An awesome features which can be used in different scenarios based on user requirements..

### Who will benefit from it?
All users

![Screenshot_20201227-124854168](https://user-images.githubusercontent.com/58127841/103189598-66918e00-48f3-11eb-8b28-eba4d89efbc7.jpg)

**Comment by kbrosnan** [comment]
Variation on #12711. This issue proposes a specific solution, we prefer to keep open only one general issue for a feature request.

**Comment by sheikh-azharuddin** [comment]
Hi Kevin,

Although a variation the other issue speaks about multiple things ( block images, fonts etc entirely) and a setting to block images completely( applicable to all sites) in mobile network more like turbo mode...here the block images settings is per site basis and on the fly...a feature already present in firefox lite and I believe the code can be reused in fenix easily..

**Comment by cadeyrn** [comment]
> feature already present in firefox lite and I believe the code can be reused in fenix easily

I doubt that the code can be easily reused since Firefox Lite was not a GeckoView based browser.

**Comment by benyaminl** [comment]
> 
> 
> > feature already present in firefox lite and I believe the code can be reused in fenix easily
> 
> I doubt that the code can be easily reused since Firefox Lite was not a GeckoView based browser.

Just hope the development catch up. Seems mozilla lay off really affect much of the development phase on daily basis.
