### ISSUE TITLE
Pin icon with rounded top site design

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17245]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The firefox lite has better pin site/top site design..the top sites have rounded design with favicon and pin icon color changes based on the site..the current square top site design looks way outdated. Please implement the top site design and pin icon style same as firefox lite

### How do you know that this problem exists today? Why is this important?

The top site looks outdated . The UI and design is not appealing

### Who will benefit from it?
All users

![Screenshot_20201227-123301869 (1)](https://user-images.githubusercontent.com/58127841/103189116-3517c300-48f1-11eb-93cb-3e847265df13.jpg)

**Comment by apbitner** [comment]
Pinging @violasong for consideration in her home screen exploration

**Comment by brampitoyo** [comment]
@sheikh-azharuddin By moving our pin next to the item title, we’ve aligned our design and made it look and feel consistent on all platforms – not just with Desktop, but also with Firefox for iOS. Closing this issue.
