### ISSUE TITLE
Sync Names don't match from desktop browsers

### ISSUE THREAD

**Issue by jGRite** [mozilla-mobile/fenix#17258]
I've renamed all my synced devices. However when I send or share from a desktop browser (Windows and Linux) the names aren't what I changed them to. This means that I can't tell what is what easily. Not an issue on Android.

**Comment by sflorean** [comment]
@jGRite did you change the name on Android device? I'm asking because you write that isn't an issue on this platform. If it is an issue found on desktop, the bug should be filed on Bugzilla.

**Comment by jGRite** [comment]
Yes, when I renamed all the devices I named them on each Android device. I didn't know of another way to rename them outside of each device separately. Looks like it is fixed already. They might have fixed this last year/
