### ISSUE TITLE
[Bug] The "Report site issue" option isn't displayed when reading mode is enabled

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#17250]
## Steps to reproduce
1. Open a page that can support reader mode.
2. Enable the reader mode.
3. Open the three-dot menu and observe the "Report site issue".

### Expected behavior
The "Report site issue: option is displayed.

### Actual behavior
The "Report site issue: option is not displayed. Disabling the reader mode, displays the "Report site issue" option.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Galaxy Tab S6 (Android 10), Samsung Galaxy Tab A6 (Android 5.1)
* Fenix version: 12/28 Nightly build, and on Beta 85.0.0-beta.4
 
![report site issue](https://user-images.githubusercontent.com/40694158/103208564-9ea3cb80-4909-11eb-99e6-154a02f5964b.png)

**Comment by kbrosnan** [comment]
Reporting site issue in reader mode is not useful for the webcompat team.
