### ISSUE TITLE
[Bug] crossOriginIsolated not working on Android

### ISSUE THREAD

**Issue by berndfuhrmann** [mozilla-mobile/fenix#17251]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open a website with the headers `Cross-Origin-Opener-Policy` set to `same-origin` and
`Cross-Origin-Embedder-Policy` set to `require-corp`. In the console, check `window.crossOriginIsolated`.

### Expected behavior
`window.crossOriginIsolated` should be `true`.

### Actual behavior
`window.crossOriginIsolated` is `false`.

### Device information
* Android device: Emulator Android 11, Nokia 8.1 
* Fenix version: 84.1.2 (Build #2015783151), 85.0.0-beta.4 (Build #2015783159), Nightly 201227 17:01 (Build #2015783887)
 
Attached are a small test case (`index.html` + `.htaccess` to configure the headers). This test works fine on Firefox Desktop, but not on Firefox for Android.
[crossOriginIsolated-fenix-testcase.zip](https://github.com/mozilla-mobile/fenix/files/5747017/crossOriginIsolated-fenix-testcase.zip)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1685602

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
