### ISSUE TITLE
FNX-5211 ⁃ Setup a Beta Build Variant

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1725]
Currently we only have Variants for Debug and Release. We will need a Beta variant that is similar to Release, but builds with a Beta configuration.

Some things that this variant will need to do different:

* app identifier
* icon
* branding
* telemetry channel? (if that does not follow app id)
* api keys or tokens for external services

(The last item may be covered by build-time settings that are injected by CI - unclear.)

**Comment by mitchhentges** [comment]
This depends on #1893

**Comment by colintheshots** [comment]
This is done and tested.
