### ISSUE TITLE
[Bug][custom tab] "Desktop site" toggle doesn't enable even if the page is displayed as desktop site

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#17252]
## Steps to reproduce
1. Make Firefox Nightly the default browser.
2. In Gmail, open a site in custom tab.
3. From the three-dot menu, enable the "Desktop site" and observe the toggle.
4. From the three-dot menu, select to "Open in Firefox Nightly" and observe if the page is opened in desktop mode.

### Expected behavior
The page is opened in desktop mode, and the toggle is enabled.

### Actual behavior
In custom tab, the toggle doesn't change to enabled, even if the page is displayed in desktop mode.
Opening the page in Firefox Nightly, displays the page in desktop mode, and the toggle is enabled.

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Xiaomi Redmi Note 8T (Android 9)
* Fenix version: 12/28 Nightly, Beta 85.0.0-beta.4
 
![custom tab](https://user-images.githubusercontent.com/40694158/103213881-b1250180-4917-11eb-849c-2a9d326ff774.png)

**Comment by softvision-miralobontiu** [comment]
This is reproducible on RC 85.1.0-rc.2 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by Oymate** [comment]
This happens often on wikimedia sites(I checked for non-mobile site), xiaomi Android 10

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the latest Nightly build from 11/2.
Tested with Sony Xperia Z5 Premium (Android 7.1.1), and Google Pixel (Android 10).

**Comment by Oymate** [comment]
I think this should be closed after it's on stable.
