### ISSUE TITLE
[webcontent] The "Like" button on Facebook is pressed when I try to view replies in comments

### ISSUE THREAD

**Issue by scrp445** [mozilla-mobile/fenix#17261]
## Site with issue and any steps to reproduce
**Site:**
facebook.com

**Steps to reproduce:**
- Open a Facebook post
- Search a comment with responses
- Click on "_'Some person'_ replied _X_ replies" (Occurs only when the person's name is pressed)

### Expected behavior
The replies should open
### Actual behavior
The "Like" button is pressed
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?

No
### Device information

* Android device: Huawei P9
* Fenix version: 84.1.2 (Build #2015783147) AC: 67.0.14, 8b9aabdda, GV: 84.0.2-20201223151259, AS: 67.0.0

**Comment by kbrosnan** [comment]
This is Gecko behavior. bz-1685121 has been opened to track investigating it.
