### ISSUE TITLE
[Bug] Temporary files in app_tmpdir not being deleted, resulting in hundreds of MB of used device storage

### ISSUE THREAD

**Issue by cousteaulecommandant** [mozilla-mobile/fenix#17262]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

This bug report is a follow-up to [Bugzilla 1532446: Hundreds of MB of stale temp files in app_tmpdir](https://bugzilla.mozilla.org/show_bug.cgi?id=1532446), which was closed as `RESOLVED INCOMPLETE` since development of the product has moved to this GitHub repository.
The bug has not been fixed yet (as of Firefox Beta 85).

## Steps to reproduce

1. Install Firefox (in my case, Firefox Beta, installed in 2016).
2. Install addons.
3. Use the browser for a long time (in my case, I've been using it for 4 years, but I guess there are ways to force this bug to manifest earlier, as detailed in [Bugzilla 1670503](https://bugzilla.mozilla.org/show_bug.cgi?id=1670503)).
4. Delete cached files, restart the browser, reboot the phone, etc.
5. Navigate to `file:///data/data/org.mozilla.*/app_tmpdir/` (where `*` is the name of the app, such as `firefox`, `firefox_beta`, `fennec_aurora`, or `fenix`), and observe the content of the directory.

### Expected behavior

Temporary files in `file:///data/data/org.mozilla.*/app_tmpdir/` are deleted when no longer needed, or on app startup, or when I manually select "Clear cached files".

### Actual behavior

Temporary files in `file:///data/data/org.mozilla.*/app_tmpdir/` are **not** deleted when no longer needed, nor on app startup, nor when I manually select "Clear cached files".
This may result in a large device storage usage (in my case, Firefox is using near 1 GB overall, as reported in _Applications_).  This can lead to the device internal storage to be eventually filled up, making it impossible to install new apps, updates, etc.

The files in this directory have the following name patterns (probably indicating different problem sources):
- `tmp-???.xpi` ([Bugzilla 1670503](https://bugzilla.mozilla.org/show_bug.cgi?id=1670503)).  These seem to be caused by addon updates.
- `mozilla-temp-*` ([Bugzilla 1555115](https://bugzilla.mozilla.org/show_bug.cgi?id=1555115)).
- `tmpaddon-*` ([~~Bugzilla 1385303~~](https://bugzilla.mozilla.org/show_bug.cgi?id=1385303)).  The bug that caused these files has already been fixed, but any files that were already generated by this bug are not deleted and stay in the device (i.e., updating the browser will not delete the files that were generated, but will prevent any new files with this name pattern from being generated).

(Even if the individual bugs causing these files to be generated are fixed, there still should be a way to delete the files that were generated by these bugs _before_ they were fixed.)

There doesn't seem to be a way to delete these files without rooting the phone or uninstalling the app.

### Device information

* Android device: ?
* Android version: 7.1.1
* Fenix version: 85.0.0-beta.4 (Build #2015783153)
  - _NB: I can't test Firefox Nightly for this bug due to space limitations in my device, which prevent me from installing new apps._

**Comment by kbrosnan** [comment]
This is tracked by the Gecko bugs. The fix won't be committed to this repository.
