### ISSUE TITLE
[Bug] Couldn't use some add-ons in private browsing mode. 

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#17273]
## Steps to reproduce
I have been install HTTPS Everywhere, Privacy Badger, uBlock in Firefox 68.12.0, recently I update Firefox to 84.x. I use private browsing mode almost all the time, but only HTTPS Everywhere could work. 
### Expected behavior
All  add-ons should work in private browsing mode. 
### Actual behavior
only HTTPS Everywhere could work in private browsing mode. 
### Device information

* Android device: 10
* Fenix version: 84.1.2

**Comment by anotherus3r** [comment]
They work fine for me. Have you allowed those add-ons to run in private browsing mode?

See: https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android#w_enable-add-ons-in-private-browsing

**Comment by kbrosnan** [comment]
Private browsing permission might not have been migrated as part of extensions. Please re-authorize extensions to run in private mode. If it is still broken after doing that we can reopen this.
