### ISSUE TITLE
[Bug]很多论坛无法使用搜索功能

### ISSUE THREAD

**Issue by heham** [mozilla-mobile/fenix#17274]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

很多论坛都无法搜索，搜索就卡住无法使用，关闭页面都不行，一定要强制退出才行，尝试关闭ubo无效，其他设备一样重现，很多个版本之前就这样一直没改过来。

### Device information

* Android device: ?nona6
* Fenix version: ?84.12

**Comment by lindongbin** [comment]
#16748

**Comment by kbrosnan** [comment]
Closing as a duplicate
