### ISSUE TITLE
Bug with dark theme and previous pages

### ISSUE THREAD

**Issue by kellda** [mozilla-mobile/fenix#17283]
# To reproduce:

* Set fenix to dark theme
* Navigate
* Long press the back arrow to open previous pages

# Actual result:

The list of previous pages shows with white text on white background.

# Expected result:

The list of previous pages shows with white text on dark background.

**Comment by cadeyrn** [comment]
It's already done in Firefox 85 Beta.

**Comment by kbrosnan** [comment]
Closing as works for me using pre-release builds
