### ISSUE TITLE
FNX-476 ⁃ Make Glean aware of Beta

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1728]
Make sure that Glean sends telemetry for our Beta channel to a separate bucket or endpoint.

We need to be able to identify the difference between Release, Beta and Nightly telemetry. Like with the inclusion of a channel name (Beta, Release, Nightly) or a unique app identifier.

(Unclear how this translates to the telemetry library)

**Comment by Dexterp37** [comment]
> 
> 
> Make sure that Glean sends telemetry for our Beta channel to a separate bucket or endpoint.

As long as the application uses a different `applicationId` (we send this as [part of the submission URL](https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/docs/pings/pings.md#ping-submission)) or [specifies a `channel`](https://github.com/mozilla-mobile/android-components/tree/master/components/service/glean#initializing-glean) using the Glean configuration, you get this behaviour out of the box.

> We need to be able to identify the difference between Release, Beta and Nightly telemetry. Like with the inclusion of a channel name (Beta, Release, Nightly) or a unique app identifier.

@fbertsch, can you confirm we're able to tell things apart by using the application id on the pipeline side of Glean?

**Comment by sblatz** [comment]
Depends on https://github.com/mozilla-mobile/fenix/issues/1724

**Comment by liuche** [comment]
Our beta is closed and QA-only, we do not need to track usage.

**Comment by Dexterp37** [comment]
> 
> 
> Our beta is closed and QA-only, we do not need to track usage.

Note that, as commented [here](https://github.com/mozilla-mobile/fenix/issues/1728#issuecomment-488586576), as long as the application id is different (and it [appears to be](https://github.com/mozilla-mobile/fenix/blob/56b21426eb3c7398603eac383ab098c9b941dc38/app/build.gradle#L62)) it should be fine.

Regardless if QA only or closed, this was necessary to tell release vs beta data apart.
