### ISSUE TITLE
requestAnimationFrame rate not constant when using WebGL (1 or 2) even with short calls

### ISSUE THREAD

**Issue by carlosrafaelgn** [mozilla-mobile/fenix#17285]
## Steps to reproduce

Just navigate to the game's page and start recording the performance.

https://carlosrafaelgn.github.io/pixel/

### Expected behavior

The calls should be made approximately every 16..17ms, given the duration of each call is in the range 2..6ms.

### Actual behavior

Every x frames there is a shift in the moment the call is made causing the game's animation to fell "skippy".

This is a recording of the title screen:

![image](https://user-images.githubusercontent.com/1372390/103479717-5b84a500-4dae-11eb-994d-32f017887c4e.png)

This is a recording of Level 2 (just click play and then select Level 2). The phone was sitting still and I was not touching the screen during the recording:

![image](https://user-images.githubusercontent.com/1372390/103479939-d69a8b00-4daf-11eb-9a29-6c5aede3967a.png)

The fact this delay appears to happen constantly every 3 frames I guess is not related to the game's code, because there are moments it happens with a different pattern:

![image](https://user-images.githubusercontent.com/1372390/103479997-4dd01f00-4db0-11eb-9c58-393ab0ce65a7.png)

The same game runs smoothly on Edge/Chrome in the same device. Also, the duration of each call is faster in those browsers, lying in the range of 1..3ms.

I call requestAnimationFrame at the beginning of the method: https://github.com/carlosrafaelgn/pixel/blob/master/scripts/view/gameView.ts#L548

I know I created a few comments regarding about:config, privacy.reduceTimerPrecision and so on, but that was just a test I made a few months ago. I reset those values to their defaults just after testing.
https://github.com/carlosrafaelgn/pixel/blob/master/scripts/view/gameView.ts#L506

Just for the sake of completeness it's worth mentioning I have also tried:
- Disabling WebAssembly and using only JS for the "engine"/library
- Disabling WebGL 2 and using WebGL 1
- Transpiling the TypeScript code into ES5-compatible JS (the default is ES2017)
- Transpiling the TypeScript code into ES6-compatible JS (the default is ES2017)

None of those attempts improved the perceived frame rate.

### Device information

* Android device: HUAWEI P30 lite (MAR-LX3A) / Android 10
* Fenix version: Firefox Nightly 210102 17:01 (Build 2015785035) AC: 71.0 GV: 86.0a1 AS: 67.2.0
* Fenix version: Firefox Daylight 84.1.2 (Build 2015783147) AC: 67.0.14 GV: 84.0.2 AS: 67.0.0

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1684974

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
