### ISSUE TITLE
[Bug] Can't login with Firefox for Android to OpenMediaVault

### ISSUE THREAD

**Issue by karnasw** [mozilla-mobile/fenix#17280]
## Description of issue/question
Mobile Firefox after successful login jumps back to login page.
Mobile Chrome on the same device with the same host works as expected.

## Steps to reproduce

- Open OMV web-interface in mobile Firefox
- Enter admin credentials
- No error reported
- "Loading, please wait" message appears
- Login page displayed again
Clearing the site cache/cookies doesn't help.
Other browsers open page without problem (Firefox for Desktop too)
Issue reported on OpenMediaVault GitHub, but there is no bug in that service:
[OpenMediaVault report](https://github.com/openmediavault/openmediavault/issues/864)

### Expected behavior
Login to service, and view control panel.

### Device information

* Android device: POCO F2 Pro (MIUI 12.2.1 Android 11)
* Fenix version: 84.1.2 (Build #2015783147)

**Comment by Amejia481** [comment]
Thanks for the report, are there any test credentials that we can use for testing purpose?  If so we can provide you a private email address for it.

**Comment by karnasw** [comment]
@Amejia481 unfortunately not, I don't have external IP. This is what I get when debug over USB.

> This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 172.31.88.10
> unreachable code after return statement ext-all.js:22:366125
> Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. 172.31.88.10
> downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:0) source: http://172.31.88.10/extjs6/classic/theme-triton/resources/fonts/OpenSans-Regular.ttf
> downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:0) source: http://172.31.88.10/extjs6/classic/theme-triton/resources/fonts/OpenSans-Regular.ttf
> Błąd pobierania oryginalnego źródła: request failed with status 404
> Adres URL źródła: <unknown>
> downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:0) source: http://172.31.88.10/extjs6/classic/theme-triton/resources/fonts/OpenSans-Regular.ttf
> downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:0) source: http://172.31.88.10/extjs6/classic/theme-triton/resources/fonts/OpenSans-Regular.ttf
> unreachable code after return statement ext-all.js:22:366125
> Błąd pobierania oryginalnego źródła: request failed with status 404
> Adres URL źródła: <unknown> 4
>

**Comment by Amejia481** [comment]
Thanks for the info!

Does turning off tracking protection fix it?

**Comment by karnasw** [comment]
No, it's not working. Also turned off all extensions.

https://youtu.be/5pOzBQpF9hc

**Comment by Amejia481** [comment]
This will require some further investigation, I think we will need to create an account to be able to reproduce the issue.

**Comment by karnasw** [comment]
Hi @Amejia481, I create VM with OMV Debian on Azure. You can access site on http://omv.westeurope.cloudapp.azure.com/. Use login: admin and password: openmediavault.

**Comment by Amejia481** [comment]
I tested on Firefox desktop and  I see the same issue, when I switch the [user agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) to Chrome I see the panel without redirects. This is an issue for the developers of `openmediavault` they are intentionally redirecting when they find Firefox's user agent, I think you could reopen the initial issue https://github.com/openmediavault/openmediavault/issues/864 and let them know that the website is not working on Firefox as they are allowing Firefox's user agent.

**Comment by karnasw** [comment]
> If the HTTP_USER_AGENT switches within a session then this might be a security issue. Because of that OMV exactly checks and prevents this.

**Comment by Amejia481** [comment]
See https://github.com/openmediavault/openmediavault/issues/864#issuecomment-760233409

**Comment by Amejia481** [comment]
I was able to reproduce the issue on the geckoview example app I opened a bug for then to also get involved https://bugzilla.mozilla.org/show_bug.cgi?id=1686747

**Comment by amedyne** [comment]
Closing issue and track this thru the bugzilla ticket.

**Comment by makotokato** [comment]
I believe that this has already fixed in Fenix.  Feel free to reopen this if this isn't fixed.
