### ISSUE TITLE
[Bug] .img file is saved with a .bin extension, dropping .img

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#17282]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

From: https://www.reddit.com/r/firefox/comments/kp17g7/fenix_img_files_are_downloaded_with_a_bin/

## Steps to reproduce

1. Navigate to https://dl.twrp.me/bacon/twrp-3.5.0_9-0-bacon.img.html
2. tap "Download twrp-3.5.0_9-0-bacon.img" (https://dl.twrp.me/bacon/twrp-3.5.0_9-0-bacon.img)
3. save when prompted

### Expected behavior

File is saved as `twrp-3.5.0_9-0-bacon.img`

### Actual behavior

File is saved as `twrp-3.5.0_9-0-bacon.bin`

Note: This also happens in Reference Browser. It does _not_ happen on the last pre-Fenix Fennec build. 

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by cadeyrn** [comment]
See also #11793 and #17263 for similar issues.

**Comment by Amejia481** [comment]
The fix should be in master, QA team please help us to verify. Thanks in advance!

**Comment by sflorean** [comment]
Verified as fixed on Nightly 2/01 with Pixel 3 (Android 11).
