### ISSUE TITLE
No option for disabling Mozilla Location Services on Fenix beta?

### ISSUE THREAD

**Issue by addas** [mozilla-mobile/fenix#17299]
Good evening and happy new year 2021!

On launch of Firefox Android Beta (Fenix Beta) it pings `location.services.mozilla.com` so I tried disabling `geo.enabled="false"` in `about:config` but it still pings.

Is there anyway to do so?

I used to disable it easily on legacy Android Firefox using advanced options.

Thank you.

**Comment by amedyne** [comment]
Hi @addas, we currently do not support disabling this on Fenix. We will look into this as we re-evaluate features on Fenix.
