### ISSUE TITLE
FNX-5214 ⁃ Make sure Sentry is aware of channels

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1729]
We need to setup Fenix Beta as a separate app in Sentry and make sure that we include the right Sentry API key at build time so that Beta reports go to the Beta app in Sentry.

**Comment by sarentz** [comment]
I setup a Fenix Beta app on Sentry. I hope we can configure the Sentry API Token through build automation in the Beta build infrastructure. Asking @mozilla-mobile/releng for advice.

**Comment by mitchhentges** [comment]
[Create a new secret](https://taskcluster-web.netlify.com/secrets/create) with the name `project/mobile/fenix/sentry/beta` and re-ping me, and I'll include it in beta automation.
Are there other secrets/build parameters that we'll want different for the beta?

**Comment by colintheshots** [comment]
@mitchhentges Is this working? We have a secret named `project/mobile/fenix/beta/sentry`.

**Comment by mitchhentges** [comment]
Affirmative, this is resolved
