### ISSUE TITLE
Implement top site search engine attribution

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#17304]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
* When a user taps on a top site Firefox should get attribution for searches performed from that visit

### How do you know that this problem exists today? Why is this important?
* There is no way currently to attribute these sorts of searches to Firefox 

Need to evaluate if we need https://github.com/mozilla-mobile/android-components/issues/8491 fixed to do this correctly.

**Comment by gabrielluong** [comment]
> ### What is the user problem or growth opportunity you want to see solved?
> * When a user taps on a top site Firefox should get attribution for searches performed from that visit
> 
> ### How do you know that this problem exists today? Why is this important?
> * There is no way currently to attribute these sorts of searches to Firefox
> 
> Need to evaluate if we need [mozilla-mobile/android-components#8491](https://github.com/mozilla-mobile/android-components/issues/8491) fixed to do this correctly.

Can you describe this a bit more? Are you looking for search engine attribution from Google in particular?

**Comment by eliserichards** [comment]
There is a telemetry ticket that will be implemented once the AC ticket is completed

**Comment by eliserichards** [comment]
#15370

**Comment by gabrielluong** [comment]
This should be handled by https://github.com/mozilla-mobile/android-components/issues/8491 already.

**Comment by softvision-miralobontiu** [comment]
@gabrielluong I've generated metrics on the 1/25 Nightly build and couldn't see the following metrics on the Glean dashboard:
- metrics.track(Event.TopSiteOpenInNewTab)
- metrics.track(Event.PocketTopSiteClicked)
- metrics.track(Event.TopSiteOpenDefault)

Could you provide me some more information regarding on what exactly should I check? 
Thank you!

I'll remove the QA:needed label until further information.

**Comment by gabrielluong** [comment]
> @gabrielluong I've generated metrics on the 1/25 Nightly build and couldn't see the following metrics on the Glean dashboard:
> 
> * metrics.track(Event.TopSiteOpenInNewTab)
> * metrics.track(Event.PocketTopSiteClicked)
> * metrics.track(Event.TopSiteOpenDefault)
> 
> Could you provide me some more information regarding on what exactly should I check?
> Thank you!
> 
> I'll remove the QA:needed label until further information.

@softvision-miralobontiu Those metrics aren't really part of this issue, but since they go through the same codepath, Event.TopSiteOpenInNewTab should happen any time a top site is opened, Event.PocketTopSiteClicked should happen any time the Pocket (Top Articles) top site is opened, and Event.TopSiteOpenDefault is any time a default top site (sites that are added by us for all new installs - Google, Wikipedia, Top Articles) is open. If these metrics continue to be failing, I think we should file a new issue.

**Comment by softvision-miralobontiu** [comment]
Verified on the 1/26 Nightly build, with VPN, that the Google default top site is dynamically redirected to the user's current location:
* Germany: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647996824
* US: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647948901
* Romania: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647516892
* India: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611648885824
* Taiwan: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611648956710

@gabrielluong is this sufficient?
Thank you?

**Comment by gabrielluong** [comment]
> Verified on the 1/26 Nightly build, with VPN, that the Google default top site is dynamically redirected to the user's current location:
> 
> * Germany: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647996824
> * US: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647948901
> * Romania: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647516892
> * India: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611648885824
> * Taiwan: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611648956710
> 
> Thank you?

Hmmm that's strange. The US one should be "https:\//www.google.com/webhp?client=firefox-**b-1-m**&channel=ts"

**Comment by gabrielluong** [comment]
> > Verified on the 1/26 Nightly build, with VPN, that the Google default top site is dynamically redirected to the user's current location:
> > 
> > * Germany: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647996824
> > * US: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647948901
> > * Romania: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611647516892
> > * India: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611648885824
> > * Taiwan: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611648956710
> > 
> > Thank you?
> 
> Hmmm that's strange. The US one should be "https://www.google.com/webhp?client=firefox-**b-1-m**&channel=ts"

@softvision-miralobontiu can you retest and if this still occurs, would you be able to run it with a debugger attached and see what `region.current` reports in https://github.com/mozilla-mobile/fenix/blob/87d6f323744a15a419202aac791ca974623cbbc5/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt#L394

**Comment by softvision-miralobontiu** [comment]
Hi Gabriel!
My colleague helped me again with the VPN, with a clean profile on the 1/26 Nightly build, and this time, the pages for Google are:
* US: https://www.google.com/webhp?client=firefox-b-1-m&channel=ts#spf=1611735398882
* Germany: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611735534776
* India: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611735610963
* Taiwan: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611735752603

Let us know if there is anything else we should check.
Thank you!

**Comment by gabrielluong** [comment]
> Hi Gabriel!
> My colleague helped me again with the VPN, with a clean profile on the 1/26 Nightly build, and this time, the pages for Google are:
> 
> * US: https://www.google.com/webhp?client=firefox-b-1-m&channel=ts#spf=1611735398882
> * Germany: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611735534776
> * India: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611735610963
> * Taiwan: https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1611735752603
> 
> Let us know if there is anything else we should check.
> Thank you!

Those look correct now. Closing as fixed now. Thank you!
