### ISSUE TITLE
[Crash] Download crash in UI Instrumented test

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17308]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Running the org.mozilla.fenix.ui.DownloadTest.testDownloadNotification UI test on Firebase.
### Expected behavior
Test passes.
### Actual behavior
Test crashed while downloading a test SVG file.
Test report: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8938718047977164642/executions/bs.e9d4366b75896fc5/testcases/1/test-cases

[Firebase crash log](https://github.com/mozilla-mobile/fenix/files/5769689/firebase.crash.log.txt)

### Device information

* Android device: Pixel 2, API 28 virtual device
* Fenix version: Debug 1/4/21

**Comment by rpappalax** [comment]
@sv-ohorvath is this crashing every time or was this an intermittent failure?

**Comment by AaronMT** [comment]
My guess is this is less to do with an instrumentation upgrade as suggested in Slack and more to do with the handling of possibly removing a download.

Like, what's this about? 

> 01-04 09:13:07.200: I/ActivityManager(2076): Killing 8894:org.mozilla.fenix.debug/u0a95 (adj 0): depends on provider com.android.providers.downloads/.DownloadProvider in dying proc android.process.media (adj 900)
01-04 09:13:07.201: W/ActivityManager(2076): Unable to launch app com.android.providers.downloads/10015 for provider downloads: launching app became null

and then

> 01-04 09:13:07.689: E/TaskPersister(2076): File error accessing recents directory (directory doesn't exist?).
01-04 09:13:07.720: I/ActivityManager(2076): Force stopping org.mozilla.fenix.debug appid=10095 user=-1: clearApplicationUserData

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath is this crashing every time or was this an intermittent failure?

I only saw it once so far.

**Comment by sv-ohorvath** [comment]
I think we can close this issue, as it hasn't reproduced in more than a month.
