### ISSUE TITLE
FNX-477 ⁃ Make sure Adjust is aware of channels

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1730]
We need to setup Fenix Beta as a separate app in Adjust and make sure that we include the right Adjust Token at build time so that attributions and usage data for the Beta channel are clearly identifyble in Adjust.

**Comment by liuche** [comment]
Our beta is closed and QA-only, we do not need to track usage.

**Comment by liuche** [comment]
@st3fan would there be any differences in the build, do you think, if we don't include the key, etc? Want to make sure the beta is as close to the release build as possible.
