### ISSUE TITLE
[Bug] Cannot login to Firefox on Android

### ISSUE THREAD

**Issue by himanshub16** [mozilla-mobile/fenix#17305]
I am not able to sign in to firefox to set-up sync.
I have tried with both methods - sign in using email, or pair from firefox.com/pair by scanning a QR code.
I have also tried disabling 2FA.

* In either case (with and without 2FA), the flow starts and gets stuck on waiting for other device (which is the laptop I am currently using). A paired notification is obtained on laptop while the android browser is still waiting for confirmation.
* when using email, it takes credentials and just waits forever.
* when 2fa is disabled, the results are the same.

I am able to login to firefox account on Firefox Fenix, but am not able to setup sync.

### Device information

* Android device: Xiaomi Redmi Note 9 Pro Max
* Fenix version: 84.1.2 (build # 2015783147)

**Comment by kbrosnan** [comment]
Might be similar to #17301

**Comment by himanshub16** [comment]
Most probably not. I don't have a connectivity issue. I'm currently on a 100 Mbps broadband connection, and the phone is connected to broadband via 5ghz wifi.
Please let me know if there is some way to get debug logs, or more information, so we can pin-point this problem. It's easily reproducible on this device.

https://status.services.mozilla.com/ reported OK all the time I was trying. Therefore, my assumption of downtimes during holiday also rules out.

**Comment by jonalmeida** [comment]
Assigning myself to see if this is related to https://github.com/mozilla-mobile/fenix/issues/17585

**Comment by jonalmeida** [comment]
@himanshub16 if you can still reproduce the issue, some logs would be really helpful!

You can follow this guide on how to get them (even though it references crashes, it can be used for non-crash bugs as well): https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information

**Comment by jonalmeida** [comment]
My mistake, I didn't read that this was on `Fenix version: 84.1.2 (build # 2015783147)` which is release, so I do not believe this is related to #17585.

**Comment by himanshub16** [comment]
Installed Firefox (85.1.1) again on my phone and the issue is resolved.
Same with lockwise. Login and Sync now work.

**Comment by jonalmeida** [comment]
Thanks! Closing.
