### ISSUE TITLE
FNX3-15779 ⁃ [Bug] custom tab: big gap between page title and URL

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1731]
### Steps to reproduce
1. make sure Fenix is your default browser
1. open a link from another app with custom tab support

### Actual / Expected behavior
In custom tabs there is a big gap between page title and URL which looks a bit weird.

![fenix-custom-tab](https://user-images.githubusercontent.com/1100614/56314820-6882e000-6156-11e9-87c2-74c00affa9ef.png)

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision f5babaf47d7f1f13b8dcb8cc151bc113618d085b

**Comment by k0ur0x** [comment]
I think this issue is related to https://github.com/mozilla-mobile/android-components

**Comment by cadeyrn** [comment]
It's fixed in latest build from master.
