### ISSUE TITLE
[Bug] HTTPS Everywhere Extension Page Inexplicably Blocked

### ISSUE THREAD

**Issue by zoracon** [mozilla-mobile/fenix#17321]
## Steps to reproduce
1. Install HTTPS Everywhere for Firefox Android
2. Go to Add-Ons Menu for HTTPS Everywhere
3. Toggle "ON" for Encrypt All Sites Eligible setting
4. Navigate to an insecure page with no HTTPS support, such as [http.badssl.com](http.badssl.com)

### Expected behavior
Display EASE mode page for insecure sites:
![image](https://user-images.githubusercontent.com/4276080/103713950-5d976100-4f72-11eb-8877-de12c0cb3c14.png)

### Actual behavior
Redirects to an error page with am unfamiliar prefix that I assume is browser based:
![image](https://user-images.githubusercontent.com/4276080/103715027-65f09b80-4f74-11eb-930f-6b8866953bf0.png)

URL: 
`jar:file:///data/user/0/org.mozilla.fenix/files/mozilla/p4a5m9oi.default/extensions/https-everywhere@eff.org.xpi!/pages/cancel/index.html?originURL=http%3A%2F%2Fhttp.badssl.com%2F`

Console Output during this time:
[console-export-2021-1-5_16-5-27.txt](https://github.com/mozilla-mobile/fenix/files/5773285/console-export-2021-1-5_16-5-27.txt)

When I turn HTTPSE EASE mode off and then back on, this strange error occurs where it tries to navigate to the extension's EASE interstitial but the extension's assets URIs get remapped to the insecure link's URI. Breaking scripts and other assets that need to be loaded for the page:
![image](https://user-images.githubusercontent.com/4276080/103715157-bbc54380-4f74-11eb-9b90-dcda144672b0.png)

Console error:
```bash
16:06:27.251 Loading failed for the <script> with source “http://http.badssl.com/translation.js”. http.badssl.com:28:1
16:06:27.326 Loading failed for the <script> with source “http://http.badssl.com/util.js”. http.badssl.com:29:1
16:06:27.379 Loading failed for the <script> with source “http://http.badssl.com/ux.js”. http.badssl.com:30:1
```
[console-export-2021-1-5_16-6-48.txt](https://github.com/mozilla-mobile/fenix/files/5773289/console-export-2021-1-5_16-6-48.txt)

### Device information
Reported across at least two devices, with different builds of Fenix (Stable and Nightly) but I will just give my specs
* Android device: 
  Pixel 3a, Android 11, Build RQ1A.201205.003
* Fenix version: 
  Nightly 210104 19:29 (Build #2015785435)
  AC: 71.0.20210104143130, 3790c3ac2
  GV: 86.0a1-20210103092941
  AS: 67.2.0

Note: I am the lead developer on the HTTPS Everywhere project and if there is something that can help guide me to take care of this error on my end, feel free to to speak to that. I am personally stuck debugging this error and can't seem to find the trigger point for this error.

**Comment by kbrosnan** [comment]
@agi I expect this is an API issue. Do we have a bug open already for this?

**Comment by agi** [comment]
I don't believe so. Let's move it to bugzilla as this is unlikely to be a Fenix/AC issue.

**Comment by agi** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1685403

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Rob--W** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/9381 and will be in Fenix Nightly tomorrow.
