### ISSUE TITLE
Intermittent UI test failure -  SettingsPrivacyTest.launchLinksInPrivateToggleOffStateDoesntChangeTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17329]
Edit: New failure, see: https://github.com/mozilla-mobile/fenix/issues/17329#issuecomment-776608975

### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7547227528362730194/executions/bs.94b89e3de8715a20/testcases/2/test-cases
### Stacktrace:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openPrivateBrowsingSubMenu(SettingsRobot.kt:187)
at org.mozilla.fenix.ui.SettingsPrivacyTest.launchLinksInPrivateToggleOffStateDoesntChangeTest(SettingsPrivacyTest.kt:342)`
### Build: 
Master 1/6/21

Recording screenshot:
- looks like the Private Browsing sub menu was clicked and opened
![privateBrowsingSubMenuTestFailure](https://user-images.githubusercontent.com/4037709/103753620-f336fd00-5013-11eb-9b28-5d64a05cac23.png)

**Comment by AndiAJ** [comment]
Closing this matter.
We haven't encounter it for approx. 1 month.

Can be re-opened if it fails again.

**Comment by sv-ohorvath** [comment]
Failed with a crash this time (1 out of 2 tries): 
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7928937487742646268/executions/bs.4f122438a4f87cea/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Hasn't failed in 3 months, I'll close this for now, can be reopened.
