### ISSUE TITLE
[Bug] Tabs not syncing between desktop and Android

### ISSUE THREAD

**Issue by ruijpbastos** [mozilla-mobile/fenix#17328]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Have multiple tabs on desktop Firefox
2. Go to 'Synchronised tabs' on mobile Firefox
### Expected behavior
- Expect to have desktop tabs accessible in mobile
### Actual behavior
- The 'Synchronised tabs' page always opens asking for login, then it logins without me doing anything, but not tabs from desktop (or anywhere else) appear.
### Device information

* Android device: Redmi Note 5 with Android 9
* Fenix version: Firefox Browser 84.1.2 (build 2015783147)

**Comment by jonalmeida** [comment]
This should be fixed now by the linked ticket above. So I'm going to close this. Thank you for reporting!
