### ISSUE TITLE
[Bug] can't open facebook on Nightly 210105 17:01

### ISSUE THREAD

**Issue by Balachandarsmr** [mozilla-mobile/fenix#17320]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Crash 1
Type m.facebook.com on address bar. Hit enter. Browser will crash.

Crash 2
Type facebook on Google search box or on address bar and do search browser will crash.

### Device information
MI A2
* Android device: 8.1 oreo
* Fenix version: Nightly 210105 17:01 (Build #2015785611)
![20210106_051207](https://user-images.githubusercontent.com/29444683/103712561-28c1f300-4fe0-11eb-81e7-faf4b2be5477.gif)
![20210106_075308](https://user-images.githubusercontent.com/29444683/103721927-df2fd300-4ff4-11eb-8c05-92f99964d32c.gif)
https://crash-stats.mozilla.org/report/index/2d5f43cc-f929-4104-bfbc-4b2020210106
https://crash-stats.mozilla.org/report/index/d344c3eb-aaa9-4c03-b7c3-e29c10210106
https://crash-stats.mozilla.org/report/index/e896b7b6-b20a-4d57-aa44-f33250210106

**Comment by kbrosnan** [comment]
This is fixed by bz-1684846. The next nightly should have that fix.
