### ISSUE TITLE
Can't sign in to sync on firefox nightly

### ISSUE THREAD

**Issue by Oregan0** [mozilla-mobile/fenix#17324]
## Steps to reproduce
go to settings tap sign in to sync choose sign in with email

### Expected behavior
email sign-in page should load and does load on daylight version for me

### Actual behavior
sign in page gets stuck loading

### Device information

* Android version: 10 (flame)
* Fenix version: Nightly 210105 17:01 (Build #2015785611)

**Comment by kbrosnan** [comment]
Works for me using the same Nightly on a Pixel 2 XL and Note 9 both running Android 10
