### ISSUE TITLE
[Bug] Firefox for android stopped working

### ISSUE THREAD

**Issue by requiel20** [mozilla-mobile/fenix#17330]
Since 2020/01/02 I am unable to Sync Firefox for Android.

I noticed it stopped Syncing as some bookmarks weren't showing on Firefox for MacOS and went into Account settings on Firefox for Android. It said "last syncrhonised: 3 days ago" (which was on 2020/01/02) and on clicking "Syncrhonise now" nothing happened.

I had recently logged in on MacOS, so maybe that's something to investigate.

I tried logging out and back in on Firefox for Android, now it says "Last syncrhonised: never" and on clicking "Syncrhonise now" nothing happens.

## Steps to reproduce
On Firefox 84.1.2 Build#20157783147
Log in
Go to Account settings
Tap on Syncrhonise now
Nothing happens

### Expected behavior
My data should be syncrhonised between accounts

### Actual behavior
N/A

### Device information

* Android device: Honor 10, Huawei Android 10, Build number 10.0.0.180 (C432E5R1P4patch01)
* Fenix version: 84.1.2 Build #20157783147

**Comment by requiel20** [comment]
This has now fixed itself 🤷

**Comment by amedyne** [comment]
Thank you for providing the update @requiel20.
Closing issue based on your update.
