### ISSUE TITLE
FNX-479 ⁃ Make sure Socorro is aware of channels

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#1734]
Make sure Socorro includes the App identifier or Channel (whatever is appropriate for Socorro) so that we can clearly identify crash reports for the Release, Nightly and Beta channels.

**Comment by sarentz** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1546745 to request this to be setup in Socorro.

**Comment by sarentz** [comment]
> If this is really the same as Fenix, but effectively a different channel, why not use ProductName=Fenix ReleaseChannel=beta? Most crash analysis looks at all the channels for a given product and if we structure it this way where they're different products, that'll be a lot harder.

This sounds like we just need to configure the release channel on our side.

**Comment by liuche** [comment]
Our beta is closed and QA-only, we do not need to track usage.
