### ISSUE TITLE
[Bug] Incorrect click position registering when browser is under load (is opening tabs in background)

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#17355]
## Steps to reproduce
1. Go to issues list here (website doesn't seem to matter really)
2. Open some issue in new tab in background
3. Scroll down
4. Repeat steps 2-3 until you see that firefox will try to open some other issue instead of the one you clicked

### Expected behavior
Firefox should always open what you clicked, not something else that is higher/lower than link you clicked

### Actual behavior
See video:
https://www.dropbox.com/s/46zond2gb7hz33d/2020_12_13_18_40_35.mp4?dl=0

See what happens here:
1. I Open reddit
2. I hold finger on "Queen Elisabeth II...", firefox says it will open "Queen Elisabeth II...", I open the tab and scroll down...
3. I hold finger on "Vanderbilt Kicker Sarah...", firefox says it will open "Vanderbilt Kicker Sarah...", I open the tab and scroll down...
4. I hold finger on "My fiance who deals...", firefox says it will open "My fiance who deals...", I open the tab and scroll down...
5. I hold finger on "Something feels off here...", firefox says it will open "My fiance who deals..."!

Looks like scroll position is not synchronized properly between the gecko engine and fenix app? I'm guessing here.
Additional information:
1. It's not always that firefox wants to open something I clicked before. Sometimes it will try to open something below the link I'm clicking, sometimes above
2. I'm pretty sure that one time I event saw in "new tab popup" that it would open link "A", but when I moved to this tab later, link "B" was open

### Device information

* Android device: Samsung Galaxy J7 2017 (also happening on Xiaomi Redmi 4A)
* Fenix version: Firefox 83.1.0 and 84.1.3

**Comment by buttercookie42** [comment]
I'm almost certain that I've occasionally encountered this already with Fennec, too, and I certainly have observed something like that with Desktop Firefox relatively recently on a page which had horrible performance problems with uBlock enabled. With an older Desktop Firefox, this never used to happen – there would of course be horrible jankiness, but no misregistered clicks.

**Comment by sflorean** [comment]
@Mikaka27 this is still reproducible for you?
Tested on latest Nightly with Samsung Note 10 (Android 11) and couldn't reproduce the issue following your steps.

**Comment by Mikaka27** [comment]
Yes I just tried it on latest nightly, and got it on first try.
From my observations, you can reduce the content process count to 1, to increase chances of it happening.

Go to about:config and set dom.ipc.processCount to 1
Then force restart firefox, by swiping it away in android's application switcher, and open it again normally.

**Comment by Mikaka27** [comment]
I also sometimes see a different variant of this. Website causes browser to be under load (I don't open any tab).

I try to interact with some element (button maybe) and then I scroll to do something else. It can happen that "click on button" I did will actually register higher or lower than button (depends on direction I scroll).
