### ISSUE TITLE
[Bug] Deleted downloads reappear in the Downloads menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17352]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Save a file (you can use file-examples.com)
2. Go to the Downloads menu, delete the file.
3. Go to device storage, to the Downloads folder and delete the file from storage too.
4. Return to the app, go back to the download page, download the file again.
5. Go to the Downloads menu and check the files.
### Expected behavior
The file is shown as downloaded just once.
### Actual behavior
The file appears twice in the Downloads menu.
### Device information

* Android device: Pixel 2 (Android 9)
* Fenix version: Debug 1/7
 
## Scenario 2:
1. Save a file (you can use file-examples.com)
2. Go to the Downloads menu, delete the file. Leave the file in device storage.
3. Return to the app, go back to the download page, download a different file.
4. Go to the Downloads menu and check the files.
### Actual behavior
The deleted (first) file reappears in the Downloads menu.

## Scenario 3:
1. Download a file
2. Go to the Downloads menu, delete the file.
3. Exit the menu before the UNDO snackbar disappears.
4. Go back to the Downloads menu, check the files.
### Actual behavior
The file reappears in the Downloads menu.

**Comment by softvision-miralobontiu** [comment]
Reproducible on Beta 85.0.0-beta.8 with Sony Xperia z5 Premium (Android 7.1.1).

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/15 Nightly build, and on Beta 86.0.0-beta.5 build with Sony Xperia Z5 Premium (Android 7.1.1).
