### ISSUE TITLE
[Bug] Position fixed element is flickering when user is scrolling

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#17357]
## Steps to reproduce
1. Go to https://allegro.pl/listing?string=Lego
2. Scroll down (do it rather quickly)
3. Observer bottom bar flickering

### Expected behavior
Position: fixed element shouldn't flicker while page is scrolling

### Actual behavior
Position: fixed element is flickering
See: [video](https://www.dropbox.com/s/a6a3hhchtb2giwe/2021_01_07_20_53_46.mp4?dl=0)

### Device information

* Android device: Samsung Galaxy J7 2017
* Fenix version: 84.1.3 and todays (07.01.2021) nightly

84.1.3 runs on opengl and nightly runs on webrender, both show same issue.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1685601

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mikaka27** [comment]
Please reconsider whether this is a fenix issue after all, since it only reproduces with dynamic (auto hiding) address bar enabled.
