### ISSUE TITLE
FNX-5219 ⁃ Incomplete German localization "Session Manager"[Bug]

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#1736]
* at the tab session area the timestamps will be shown in English instead of German, also the time format. Germany don't use am/pm. 

![Screenshot](https://user-images.githubusercontent.com/44252450/56318797-3bd3c600-6160-11e9-8fa3-bb4a73454bb7.png)UNITO-UNDERSCORE!20190417-220924!UNITO-UNDERSCORE!Fenix!

**Comment by kbrosnan** [comment]
This is three separate issues. It is better to file them individually.

**Comment by LittleAngelwings** [comment]
Okay, I've divided them into three separate tickets.
