### ISSUE TITLE
[Bug] Font is too small on many sites, needs inflation

### ISSUE THREAD

**Issue by kuro68k** [mozilla-mobile/fenix#17367]
## Several sites affected, including

www.bugzilla.org
slashdot.org
srad.jp
metro.nanika.net
www.pckeyboard.com/mm5/graphics/00000001/Update%20and%20Announcement%20v_1.4.htm
www.satsignal.eu/ntp/Raspberry-Pi-NTP.html
www.cad.t.u-tokyo.ac.jp/~shun/etc/20050720_usb_hub.html
www.swallowam.co.uk
starship.rs
www.hdsentinel.com

### Expected behavior

Site is readable without having to zoom and scroll right/left for every line.

### Actual behavior

Site is rendered with very small fonts and a wide page, forcing the user to zoom in and then scroll right to left to read every single line. This effectively renders the site unusable.

Using automatic font size does not help. Using manual font size with the size set to something larger does not help unless it is set to such a high value that it breaks other websites.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Chrome renders the sites with a larger font and less wide page. It seems to take notice of the system font size and ensure that web content is generally not smaller than that.

### Device information

* Android device: Pixel 5
* Fenix version: Nightly 210106 17:02 (Build #2015785803)

Screenshots (keep in mind the phone screen is about 65mm wide, so fonts readable on a desktop monitor are not readable on the phone):

Bugzilla (Fenix, zoomed in to be readable):

![image](https://user-images.githubusercontent.com/2674466/104003703-acbfda80-519a-11eb-81b7-44fd103e50b9.png)

Buzzilla in Chrome:

![image](https://user-images.githubusercontent.com/2674466/104003901-fb6d7480-519a-11eb-8f02-7f99d8d2e515.png)

NEC (Fenix, zoomed in to be readable):

![image](https://user-images.githubusercontent.com/2674466/104003614-8a2dc180-519a-11eb-8384-4921b4e0c135.png)

Same site in Chrome, no zooming:

![image](https://user-images.githubusercontent.com/2674466/104003808-d7119800-519a-11eb-9ee6-967475dcd139.png)

srad (zoomed in to be readable):

![image](https://user-images.githubusercontent.com/2674466/104003379-40dd7200-519a-11eb-9323-6e11ed54ff01.png)

u-tokyo:

![image](https://user-images.githubusercontent.com/2674466/104003443-55216f00-519a-11eb-96c9-b5cfffcdf066.png)

Swallow Amusements:

![image](https://user-images.githubusercontent.com/2674466/104003586-7f732c80-519a-11eb-8b20-8d0261337f32.png)

Unicomp PC keyboards (zoomed in to be readable):

![image](https://user-images.githubusercontent.com/2674466/104003673-a0d41880-519a-11eb-989a-a48632df8f43.png)

Metro app:

![image](https://user-images.githubusercontent.com/2674466/104003726-b6e1d900-519a-11eb-8cf7-bc578920c3e5.png)

**Comment by buttercookie42** [comment]
For me, font inflation is working on all of these pages. My phone only has 720 px (for ~62 mm of real screen width), though, so my initial suspicion would be that either something's outright wrong with our screen size/dpi calculation, or else we're at least hitting some sort of edge case here which makes Gecko think that your phone is wider than it really is, so font inflation is disabled or at least dialled down so much as to be effectively unnoticeable.

A few questions:
- In *about:config*, what is the value reported for *font.size.inflation.minTwips* when automatic font size is enabled?
- What values are reported when you visit https://whatismyviewport.com/?
- Could you install https://play.google.com/store/apps/details?id=com.sturnus.screeninfo and post a screenshot of the display metrics data?

**Comment by kuro68k** [comment]
Yes, I think it's an edge case. It also happens on my old Pixel XL. Both are running stock Android.

font.size.inflation.minTwips is set to 120 with automatic font size enabled.

Whatismyviewport reports 396x732px, DPR 2.72 recurring, screen size 396x858px.

Screen Size app:

![image](https://user-images.githubusercontent.com/2674466/104041216-9cc2ed80-51d0-11eb-8d0e-8e8ad1732f9f.png)

Thanks for your assistance.

**Comment by buttercookie42** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1685756.
Unfortunately my Android build environment is probably somewhat out of date, so I need to check how easily I can get it going again.

**Comment by kuro68k** [comment]
Thank you buttercookie42, very much appreciated. If I can assist in any way please let me know. I will investigate the Android build environment too, maybe I can find some time to have a look now I know vaguely where the issue might be.

**Comment by kbrosnan** [comment]
Closing Gecko issue.

**Comment by buttercookie42** [comment]
For those not following along on Bugzilla, a fix has landed in Firefox 93.

**Comment by kbrosnan** [comment]
Thank you Jan for your continued help on improving the font inflation code.
