### ISSUE TITLE
issue Watching Video

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#17360]
Hi Development Team, I encountered a problem when using firefox, the problem is when using the Firefox browser while watching videos in full screen mode because in full screen mode the notification bar still appears, is there a solution. The device used is ADVAN (5202) Android 9.0 Pie

**Comment by ekager** [comment]
Which version of Fenix? Does this still happen in Nightly? Could you post a screenshot to make it more clear what you're talking about? Thanks!

**Comment by amedyne** [comment]
@mzulkifli757 Can you provide the details asked by @ekager ? Thank you!

**Comment by abodea** [comment]
For the past months, we didn't encounter any issues regarding this.
I also did today some checks on few websites: YT, Vimeo, Twitch, Twitter but I had no issues on the latest Nightly 3/31/21 with Google Pixel 4 XL (11).
@mzulkifli757 can you please re-check and add the information asked above, please?
