### ISSUE TITLE
[Telemetry] extend perf.awesomebar.* metrics

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#17361]
These metrics have recently expired:
```
- perf.awesomebar.bookmark_suggestions on 2020-11-15
- perf.awesomebar.clipboard_suggestions on 2020-11-15
- perf.awesomebar.history_suggestions on 2020-11-15
- perf.awesomebar.search_engine_suggestions on 2020-11-15
- perf.awesomebar.session_suggestions on 2020-11-15
- perf.awesomebar.shortcuts_suggestions on 2020-11-15
- perf.awesomebar.synced_tabs_suggestions on 2020-11-15
```

They track performance of the queries that power awesomebar results. How long these queries take to execute directly correlates with user experience, so these metrics are quite useful to plot over time and check upon, to ensure we're not regressing awesomebar performance.

**Comment by eliserichards** [comment]
https://github.com/mozilla-mobile/fenix/pull/17406
