### ISSUE TITLE
FNX-5220 ⁃ [Bug] Crash when putting focus in URL bar after first launch

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1737]
## Steps to reproduce
* Launch Fenix
* Single tap in the URL bar at the bottom to start typing an address (Note - sometimes when I launch Fenix I don't get the launch screen. Just a blank white screen with the URL bar at the bottom. This is when the crash happens)

### Expected behavior
* Able to type in the URL bar

### Actual behavior
* Fenix crashes and I get the Sentry crash reporter dialog. I have been able to reproduce this issue several times today.

### Device information
* Android device: Pixel running Android Q 
* Fenix version: 1.0.1916 (Build #11071224)

**Comment by kbrosnan** [comment]
If you happen to be near your laptop shortly after the crash getting a logcat would be helpful. It will allow us to match it to a Sentry report.

**Comment by mozillamarcia** [comment]
I will try to get a logcat if it happens again. So far haven't been able to repro.

**Comment by sv-ohorvath** [comment]
I suppose this hasn't happened since the last comment. Should we close this bug?

**Comment by mozillamarcia** [comment]
> I suppose this hasn't happened since the last comment. Should we close this bug?

Yes, I haven't seen this issue in some time.

**Comment by softvision-miralobontiu** [comment]
Based on Marcia's comment, I will close this issue.
