### ISSUE TITLE
[Bug] Typing in the url bar sometimes mistakenly navigates web-view in installed web-app

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#17376]
## Steps to reproduce

It doesn't reproduce super consistently, but it has happened to me a bunch of times lately.

After a while of leaving twitter open and switching to fenix it repros...

 * Have an app "installed" like twitter.com.
 * Open Fenix Nightly.
 * Open twitter.com from the homepage icon (so it shows like a standalone app).
 * Open a link from twitter so that the in-app webview shows up.
 * Switch to Fenix.
 * Type a URL in the url bar (e.g., youtube.com)

### Expected behavior

Url opens in Fenix

### Actual behavior

Url opens in the embedded webview of twitter.com, without switching to it, so I get very confused and think Fenix broke :)

### Device information

* Android device: Motorola G8 plus
* Fenix version: Latest Nightly

**Comment by mcarare** [comment]
This seems to be the same problem as https://github.com/mozilla-mobile/fenix/issues/17199.
Closing as duplicate.
