### ISSUE TITLE
[Bug] Focusing a filled address bar shows blank search suggestions view instead of scrim (regression?)

### ISSUE THREAD

**Issue by violasong** [mozilla-mobile/fenix#17377]
### Steps to reproduce
When viewing a website page, and then tapping the address bar, we see a blank white search suggestions view. (In certain cases on google search results pages, we see search suggestions instead.)

### Expected behavior
We should actually show a gray scrim instead of the blank pane. It should be the same experience as when there's nothing in the address bar. As a general rule, if the search suggestions pane is completely blank, we shouldn't show it.

We'll eventually want to add some useful elements here like in other browsers (https://github.com/mozilla-mobile/fenix/issues/9118#issuecomment-724188456), but as an intermediate step, I think we should see a scrim here.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/55994/104076089-c9bfd200-51c9-11eb-8a0e-c3c1033c872e.png">

### Device information

* Android device: Galaxy S20
* Fenix version: Nightly

**Comment by abodea** [comment]
I was able to reproduce this issue on the latest nightly 1/12 with Google Pixel 4 XL (11).

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 1/25 with Google Pixel 4 XL (11).
Note that the scrim effect is correctly displayed when focusing a filled address bar.
