### ISSUE TITLE
Ошибка работы видео и браузера при версии для ПК

### ISSUE THREAD

**Issue by krasavchegcash** [mozilla-mobile/fenix#17374]
Столкнулся уже не первый раз с этой проблемой. После обновления проблемы ушли, но вот новые обновления и снова те же грабли. У меня андроит тв, чтобы на сайте посмотреть видео, приходится включать режим версия для пк. Так как в мобильной версии нажать плей курсором не возможно. При включении режима версия для пк не открывается полноценно полноэкранный режим плеера и проблема не сайта. Так же было замечено, что при долгой работе браузера в потоковом ауди или видео, происходит аппаратное зависание андроид тв приставки. Через время это проходит с обновлениями, но все снова вернулось.

**Comment by amedyne** [comment]
Google TV is not supported.
