### ISSUE TITLE
[Bug] Returning from custom tab to PWA page stuck to blank page

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#17380]
The following bug has been happening to me for some weeks already with the nightly builds.
Usually it happens at every attempt. Yet, I have tried to record it on screen recording, but in this case, it does not happen anymore. And I can't produce any recording as an evidence ;)

## Steps to reproduce
Open a PWA site like Twitter
Click on any link in a Twitter post: this should open a custom tab.
Click on the "close" icon of this custom tab once it is displayed 

### Expected behavior
The PWA page should be displayed again

### Actual behavior
a blank page is displayed (dark due to the Fenix dark theme)
I have to close Fenix fully to have be able to display the PWA page again.

### Device information
Redmi Note 7
Android 9
Builds for some weeks

**Comment by amedyne** [comment]
@klint Can you check if you are still encountering this on Firefox for Android? If yes, please provide the Firefox for Android version.

Thank you!

**Comment by klint** [comment]
Hi. I just tried quickly and it seems to fail less often than before. Yet, the link to youtube on this tweet still shows the issue.
https://twitter.com/BoingBoing/status/1355636225793798148
As well as other links to YouTube.
I'm using the very latest nightly build 2015790411

**Comment by lobontiumira** [comment]
@klint I was not able to reproduce this issue on the 3/18 Nightly build with Google Pixel (Android 10).
Could you please retry?

**Comment by sflorean** [comment]
I was able to reproduce this on Beta 88.0.0-beta.1 with LG G7 Fit (Android 8.1.0).

**Comment by klint** [comment]
Hi sorry for the delay, but it is still happening to me with build #2015804891

**Comment by klint** [comment]
Closing as it is the same bug as in #19157

**Comment by klint** [comment]
Sorry, I closed it too fast. Reopening as it could only be related to, but not identical to #19157.
And I can confirm that it is still happening with Fenix 94.0.
