### ISSUE TITLE
[Bug] Sending a tab makes the UI unresponsive as long as the message is shown

### ISSUE THREAD

**Issue by KopfKrieg** [mozilla-mobile/fenix#17383]
## Steps to reproduce

1. Open Fenix, make sure you're logged into sync (including a second device)
2. Open a website
3. Send that website using the share button → send to device
4. The entire bottom part of the UI is unresponsive as long as the "Tab sent" notification is shown.

Here's a picture that illustrates what I mean:

![Fenix_message_blocking](https://user-images.githubusercontent.com/5047813/104115809-9c7f3b00-5313-11eb-9585-92227c95b176.png)

### Expected behavior
The "Tab sent" notification shouldn't block anything.

### Actual behavior
I have to wait until the message is gone before I can close the tab, switch tabs, or enter a different URL.

### Device information

* Android device: Motorola G8+, Android 10
* Fenix version: 84.1.4

**Comment by LaurentiuApahideanSV** [comment]
Hello and thank you for the report.
The issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/9539. I will mark this issue as closed as it will be handled there.
