### ISSUE TITLE
See data usage by site 

### ISSUE THREAD

**Issue by leodoi3** [mozilla-mobile/fenix#17384]
Please add a way to view data usage by sites visited.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9349)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813261

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
