### ISSUE TITLE
[Bug] Opening link from Google search does not shows the website name in the title. With Bing search it works fine

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#17389]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Search on Firefox using Google search and open any search result.

### Expected behavior
Opening search result must show the actual website title as title in the history.

### Actual behavior
It shows nothing and the link has www.google.com as prefix.

### Device information
Samsung Galaxy A71

* Android device: Android 10 UI 2.5
* Fenix version:  @84.1.4
![20210111_134647](https://user-images.githubusercontent.com/76210878/104159609-a7ba8f80-5415-11eb-8c4b-a27e31f6178c.jpg)
![20210111_140207](https://user-images.githubusercontent.com/76210878/104159644-b7d26f00-5415-11eb-95bb-99c9e0e7b727.jpg)

**Comment by Mugurell** [comment]
Thank you @iamiceparticle !

In this exact case after tapping on the search result we get to save two visits:
- `https://www.google.com/url?q=https://www.wikihow.com/...`
with flags: VISIT_TOP_LEVEL, VISIT_REDIRECT_SOURCE
- `https://www.wikihow.com/Eat-Properly`
with flags VISIT_TOP_LEVEL, VISIT_REDIRECT_TEMPORARY

flags based on which [in PagedHistoryProvider](https://github.com/mozilla-mobile/fenix/blob/7b1af41b4056da1ee2cb78a66232d962d7d1e07a/app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt#L42) we exclude the last url from history.

This seems to be an issue specific to Google Search which uses the redirect for it's specific telemetry.
As such I don't think we should be quick on just allowing for `VISIT_REDIRECT_TEMPORARY` URLs to be shown in history but try to maybe find a workaround for this specific case.
(We should also ignore the VISIT_REDIRECT_SOURCE url which I doubt is something that should be generally applicable)

I see that on Firefox desktop the history entries are the expected ones (history shows not the google redirect but the target site) even though the same redirect link is set for search results but I don't yet know how and why we have a different behavior.

Asking @agi for any input on how to to approach this.

**Comment by Mugurell** [comment]
Talked with Agi which recommened Marco Bonardo as one who might know what the exact behavior should be.
Created https://bugzilla.mozilla.org/show_bug.cgi?id=1686280 for this.

**Comment by Mugurell** [comment]
Checked now the status, seems like there is nothing actionable on Fenix. We're still waiting for GV/Gecko:
- For GV there is a [fenix:p1] - https://bugzilla.mozilla.org/show_bug.cgi?id=1670279
- For Gecko there is a P3 ticket for the functionality needed by GV - https://bugzilla.mozilla.org/show_bug.cgi?id=1670279

**Comment by Mugurell** [comment]
@amoya Since the Gecko/GV issues seem to need quite a bit of work and there is currently no traction I propose removing this from our current backlog.

**Comment by amedyne** [comment]
@Mugurell Moving this back to the staging board for now.

**Comment by amedyne** [comment]
Will validate this as changes are implemented to History
