### ISSUE TITLE
[Bug] speechSynthesis error bug with Firefox Nightly

### ISSUE THREAD

**Issue by clarodanesh** [mozilla-mobile/fenix#17391]
SpeechSynthesis is currently throwing an error on any website that you want to use it on in Fenix Nightly build. It works as intended on the Production Fenix build.

## Steps to reproduce
1. Visit the [MDN SpeechSynthesis Demo](https://mdn.github.io/web-speech-api/speak-easy-synthesis/)
2. Enter some text into the text area
3. Press Play

### Expected behavior
Expected text to be spoken in the default settings that have been set by the website.

### Actual behavior
The text is not spoken and the devtools throws a SpeechSynthesis error in the console.

### Device information

* Android device: Samsung Galaxy S8
* Fenix version: Nightly 210110 17:01 (Build #2015786571)

**Comment by DiegoARL38** [comment]
I can't reproduce the issue on a Redmi Note 8 (MiUI 11.0.12.0, Android 9) using the same build.

**Comment by clarodanesh** [comment]
I think I should close this issue now as I am trying to reproduce it today and I cant reproduce it anymore. I tried reproducing with build Nightly 210110 17:01 (Build #2015786571) and updated and tried reproducing in Nightly 210111 17:02 (Build #2015786763).
