### ISSUE TITLE
[Bug] Media play/pause state is displayed on multiple opened tabs in tabs tray

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#17398]
## Steps to reproduce
1. Open several pages containing media.
2. Go through each page and play some media.
3. Open tabs tray and observe the media state.

### Expected behavior
The media state is displayed on the latest used site.

### Actual behavior
The media state is displayed on each site that played some media.

### Device information
* Android device: OnePlus 5T (Android 10)
* Fenix version: 1/11 Firefox Nightly, GV 86.a01
* Not reproducible on RC 84.1.4, nor on Beta 85.0.0-beta.6
 
<img src="https://user-images.githubusercontent.com/40694158/104199018-9c745d80-542f-11eb-8e5b-9d97e2a3d6c0.jpg" width="300" height="550" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9357)

**Comment by softvision-miralobontiu** [comment]
This issue is reproducible on Beta 86.0.0-beta.3 with OnePlus 5T (Android 10).
Not reproducible on RC 85.1.3.

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.4 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on the latest Nightly build from 11/2 with Samsung Galaxy Note 8 (Android 9).

**Comment by sflorean** [comment]
This is still reproducible on Fenix versions; based on this I will remove the wontfix label.
