### ISSUE TITLE
Remove dead code around "Delete downloads"

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17393]
Following https://github.com/mozilla-mobile/fenix/issues/16541 the "Delete downloads" button should not appear anymore.
The string resources still exist and also some code related to it.
I think these should be removed.
Asking @kglazko who last worked on this area if there there is still need for them or not.

**Comment by Mugurell** [comment]
This code is still around, unused as we're [always calling `toggleTopContent` with `false`](https://github.com/mozilla-mobile/fenix/blob/6a3adb5aeba976a7146eb96a2ef3794fae909304/app/src/main/java/org/mozilla/fenix/library/downloads/viewholders/DownloadsListItemViewHolder.kt#L56)

**Comment by sunil9211** [comment]
@Mugurell Hey, can i please work on this issue?

**Comment by Mugurell** [comment]
> @Mugurell Hey, can i please work on this issue?

Would be great to!

**Comment by Rishavgupta12345** [comment]
can i work on this issue

**Comment by Mugurell** [comment]
This should have been closed as fixed.
