### ISSUE TITLE
[Bug] Non-scrollable website jumps up and down if user tries to scroll (when address bar is on top)

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#17396]
## Steps to reproduce
1. Set address bar to be on top of browser
2. Visit guimp.com or other non-scrollable website
3. Try to scroll the website
4. Observe website jumping up and down

### Expected behavior
Website that is not scrollable should never move when user tries to scroll

### Actual behavior
Website jumps up and down, see video:
https://www.dropbox.com/s/0xaodcin313d4py/2021_01_11_15_11_14.mp4?dl=0

When I connect with debugger and check `window.innerHeight` I see that it jumps between this two values each time I scroll.
```
window.innerHeight;
1552
```

```
window.innerHeight;
1418
```

If you install dark reader extension you can also visibly see different background at the bottom of the website (as if it makes space for bottom address bar even though it's set to be on top).
This causes serious problems for sticky button on our website (this button jumps up and down).
None of this is happening if I set address bar to be on the bottom.

### Device information

* Android device: Samsung Galaxy J7 2017
* Fenix version: 84.1.4 and todays (11.01.2021) nightly

**Comment by michaeldel** [comment]
I have the same issue on Firefox 85.1.1, under the same conditions. With the address bar set at the top, `window.innerHeight` seems to return the viewport height minus the height of the address bar (and sometime a value close to half the expected one). For some reasons it does not seem to happen very consistently as well, only with the address bar set at the top though.

**Comment by Mikaka27** [comment]
@michaeldel Can you check on nightly? Itseems fixed for me there.

**Comment by michaeldel** [comment]
> @michaeldel Can you check on nightly? It seems fixed for me there.
You are right, it indeed seems to be fixed on Nightly 210215 (GV 87.0a1), thank you.

**Comment by Mikaka27** [comment]
Fixed on nightly.

**Comment by Mikaka27** [comment]
Reopening since I can still reproduce on different phone. Maybe it depends on the screen size?
