### ISSUE TITLE
FNX-5221 ⁃ [UX] Contextual Menus

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#174]
**User Story:**
As a user I want options for manipulating things I find on the web including images, links, and text.

**Current Design Status:**

* No Fenix specific work done on this
* Have prior reference from Fennec and Focus

**Design Priority:**
P1

**Comment by bbinto** [comment]
Tif, please provide ETA for this (cc @brampitoyo)

**Comment by shorlander** [comment]
Guessing an M size, but @brampitoyo might disagree.

**Comment by bbinto** [comment]
Thanks Tif - these are primary user controls, can somebody else pick this up? Seems pretty basic and needed for the MVP.

**Comment by bbinto** [comment]
@vesta0 and @shorlander , @st3fan to meet and discuss if current refbrowser implementation is acceptable for milestone 2.

**Comment by brampitoyo** [comment]
I’ve identified 4 different situations where a contextual menu can appear:

### 1. On tap + hold link

The context menu contains:

* Open in new tab
* Copy link 
* Copy link text
* Share link

<img width="360" src="https://user-images.githubusercontent.com/51007/51883091-5c547580-23e6-11e9-8b3e-141825832745.png">

### 2. On tap + hold image

The context menu contains:

* Open in new tab
* Save image
* Copy link
* Share image

<img width="360" src="https://user-images.githubusercontent.com/51007/51883098-624a5680-23e6-11e9-9fbe-3cb3e65d43ed.png">

### 3. On tap + hold text

The text selection toolbar (note that it’s not a modal dialogue) contains:

* Copy
* Share
* Select all

<img width="360" src="https://user-images.githubusercontent.com/51007/51883058-3038f480-23e6-11e9-8065-f291e04266f3.png">

### 4. On tap + hold address bar

In this situation, Fenix should behave **as if the address bar has been tapped**. This means that:

1. The URL is highlighted
2. The keyboard is up
3. A grey shade is shown over the web content

The text selection toolbar contains:

* Cut
* Copy
* Paste
* Share

<img width="360" src="https://user-images.githubusercontent.com/51007/51883066-38912f80-23e6-11e9-977d-ab204c2330fc.png">

**Comment by brampitoyo** [comment]
@colintheshots This issue is now ready for your feedback, and to estimate.

**Comment by pocmo** [comment]
Also see #264: This functionality is provided by a component.

Note that case 3 and 4 above are system level text selection toolbars.

**Comment by vesta0** [comment]
@lime124 is UX ok with the UI that has been done in A-C for the contextual menus? If so we can close this.

**Comment by shorlander** [comment]
Looks good to me, thanks!

**Comment by pwd-github** [comment]
This work forgot SEARCH, for both images and text.
