### ISSUE TITLE
[Bug] The scroll position goes to the end of the page when opening link with anchor in a new tab

### ISSUE THREAD

**Issue by JaimePG** [mozilla-mobile/fenix#17404]
## Steps to reproduce
This is something it's happening win all forums run by XenForo software I've been able to test. I don't know if this wrong behaviour it's also happining in other websites. When you try to open a link with an anchor in it in a new tab of the browser (long click and choosing "Open link in a new tab" option), then, when you go to the tab after selecting it on the tab list, the scroll/position view appears in the endpage instead of in the anchor position.

This is just happening when you open the link in a new tab. If you just open it in the same tab the navigation is ok.

This can be tested for example in this forum thread page: https://xenforo.com/community/threads/xenforo-2-2-2-and-add-ons-2-2-1-released.188434/ All the dates (shown in text format at the start of each post, next to the avatar) have a link that redirects to a URL with an anchor which points this position of the page.

This link:
![xenforo_link1](https://user-images.githubusercontent.com/17139675/104245532-bb411700-5464-11eb-98ba-ff42b34020d8.png)

Example: https://xenforo.com/community/threads/xenforo-2-2-2-and-add-ons-2-2-1-released.188434/post-1481671 redirects to the URL https://xenforo.com/community/threads/xenforo-2-2-2-and-add-ons-2-2-1-released.188434/#post-1481671, which is the one finally shown.

When opening that link in a new tab in Firefox for Android, the scroll goes to the endpage instead of to the anchor position.

### Expected behavior
The scroll shout go in the new opened tab to the start of that post, the position there the anchor is. This is how works in desktop and when you don't open the link in a new tab, when you do it in the current one.

![xenforo_link_ok](https://user-images.githubusercontent.com/17139675/104245697-065b2a00-5465-11eb-9329-653f2f84b193.png)

### Actual behavior
The scroll goes to the end of the page.

![xenforo_link_ko](https://user-images.githubusercontent.com/17139675/104245837-45897b00-5465-11eb-933e-adbdeffc8ac4.png)

### Device information

* Android device: OnePlus 8 with Android 11, but it's also happening in other devices.
* Fenix version: Firefox for Android 84.1.4 (Build #2015785883). It's also happening in Firefox Nightly 210110.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9361)

**Comment by JaimePG** [comment]
I've recorded a video of the issue.

https://user-images.githubusercontent.com/17139675/104246404-36ef9380-5466-11eb-8166-88119dd7e529.mp4

**Comment by JaimePG** [comment]
This behaviour is very annoying because losts of forum users use to browse the last written posts in some forum and lots of links have anchors to redirect you to your last unread post in a thread. With this bug, when I open this type of links I lose all the focus of the last unread post becase the new tab is opened in the end of the page instead of the position of my last unread post.

**Comment by test491** [comment]
tested on below two hyperlinks given in op [forum hyperlink](https://xenforo.com/community/threads/xenforo-2-2-2-and-add-ons-2-2-1-released.188434/post-1481671)

* [XenForo Resource Manager 2.2.1 Released​](https://xenforo.com/community/threads/xenforo-2-2-2-and-add-ons-2-2-1-released.188434/post-1481672)

* [XenForo Enhanced Search 2.2.1 Released​](https://xenforo.com/community/threads/xenforo-2-2-2-and-add-ons-2-2-1-released.188434/post-1481673)

#### etp settings
custom - cryptominers, fingerprinters, redirect trackers, tracking content - all tabs, cookies - all cookies

#### not reproducible with above etp settings in private browsing mode

* version: `86.1.1`
* version: `87.0.0-beta.1 (Build #2015795065)`
* version: `Nightly 210228 (Build #2015795881)`

#### android 9, Galaxy J7 Nxt

**Comment by aroskuski** [comment]
One important detail that's important for reproducing this bug, at least in my experience, is that it only seems to happen if you wait long enough for the tab to finish loading in the background before switching to it.  If the tab is in the foreground at any point while the page is still loading, the scroll position will tend to be correct, at least once loading finishes.  Opening the tab, then immediately tapping "switch" on the pop-up is a fairly effective, but inconvenient way to work around the bug.

**Comment by sflorean** [comment]
I was able to reproduce this on latest Nightly with Samsung Note 10 (Android 11) following the steps provided. Small difference: The scroll wasn't at the end of the page but at the middle.

**Comment by JaimePG** [comment]
This issue is still happening in Firefox for Android last version. Also in Firefox Desktop when the window is small resized.

**Comment by freakingprime** [comment]
It's the end of 2022 and this bug's still there. I switched to Opera mobile because of this.

**Comment by lbmaian** [comment]
I'm not sure if this is the exact same issue, but the scroll position has gets f-ed up on Xenforo pages with anchors in other conditions:
1) the exact issue reported here
2) when selecting text over multiple lines, it jumps back to the anchor position
3) when clicking a spoiler button, it jumps back to the anchor position

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813215

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
