### ISSUE TITLE
[Bug] Opening a tab from a collection opens it in the background

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/fenix#17400]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Have an open tab.
- Tap on a tab in a collection to open it.
### Expected behavior
- The tab loads.
- The browser switches to that tab

### Actual behavior
- The tab loads.
- The browser switches to the other tab that was previously open (not the one from the collection).
- If you open the tab tray it shows the new tab, and you can switch to it.

### Device information

* Android device: Samsung Galaxy A50
* Fenix version: Nightly 210110 17:01 (Build #2015786571)
AC: 71.0.20210110143120, 641cbe6b9
GV: 86.0a1-20210110092829
AS: 67.2.0

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with Samsung Note10(Android 10) and Pixel 3(Android 11)
