### ISSUE TITLE
Fenix Google Search tile [Telemetry]

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#17418]
## Description & Product Manager / Data Scientist User Story
Add telemetry to the existing Google search tile that allows for attribution in a similar fashion to the existing telemetry in other search access points, such as the Awesome Bar.
## What questions will you answer with this data?
Count of users conducting searches from the Google Search tile.
## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by codrut-topliceanu** [comment]
@lwa-moz Apologies, but could you please provide a bit more info about what you mean when you say "Google search tile"? Do you mean the topSites?

**Comment by codrut-topliceanu** [comment]
Sorry to bother you again @lwa-moz , but I'm not entirely sure what you mean by "attribution in a similar fashion to the existing telemetry in other search access points, such as the Awesome Bar." Below I put up a link to all the Awesomebar related metrics I found and all of them seem to be durations.

Would you mind being more specific with the metrics you'd like to see implemented?

https://github.com/mozilla-mobile/fenix/blob/7c56df41df575aa00cd740540d99d0a16722965f/app/metrics.yaml#L3903

**Comment by mcarare** [comment]
@lwa-moz I am not sure if I am missing some details here, but isn't this the same as [Implement top site search engine attribution ](https://github.com/mozilla-mobile/fenix/issues/17304) ?

**Comment by gabrielluong** [comment]
I think this is calling for telemetry for the "https://www.google.com" top site, but we should wait for further clarifications. You will see in https://github.com/mozilla-mobile/fenix/issues/17304 that we do an exact string match since the default Google top site can be removed and re-added.  

> ## Description & Product Manager / Data Scientist User Story
> Add telemetry to the existing Google search tile that allows for attribution in a similar fashion to the existing telemetry in other search access points, such as the Awesome Bar.
> 

I don't know much about the existing telemetry regarding search access points, but it might be good to take a look what is happening there.

**Comment by lwa-moz** [comment]
Closed as @mcarare is right that issue [#17304](https://github.com/mozilla-mobile/fenix/issues/17304) captures this work.

**Comment by lwa-moz** [comment]
Leaving this open to track telemetry related work specifically.

**Comment by softvision-miralobontiu** [comment]
Verified in the latest Beta 86.0.0-beta.3 with OnePlus 5T (Android 10), that the Google search tile allows for atribution:

```
{
          "category": "top_sites",
          "name": "open_google_search_attribution",
          "timestamp": 2264
 }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-210209000)

**Comment by softvision-miralobontiu** [comment]
Verified also on the latest RC build 85.1.3 with OnePlus 5T (Android 10):
```
 {
          "category": "top_sites",
          "name": "open_google_search_attribution",
          "timestamp": 3689
        }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-210209003)

**Comment by gabrielluong** [comment]
We landed another telemetry in https://github.com/mozilla-mobile/fenix/pull/17637 so I am throwing this back up for qa:needed.

**Comment by softvision-miralobontiu** [comment]
Verified with OnePlus 5T (Android 10) on:
* 2/12 Nightly build - ping: c6f8ba88-6a58-45ae-8b4a-fb57cde5e17d
```
{
          "category": "top_sites",
          "name": "open_google_search_attribution",
          "timestamp": 3392
        },
        {
          "category": "events",
          "extra": {
            "source": "shortcut.topsite"
          }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-210212000)

On RC 85.1.3, and on Beta 86.0.0-beta.4 the "shortcut.topsite" event isn't triggered.

**Comment by gabrielluong** [comment]
Closing since this is now verified.
