### ISSUE TITLE
Use proper templating in our error pages

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17414]
As a general improvement suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1659035 we should look into maybe replacing our usage of `innerHTML`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9364)

**Comment by mozfreddyb** [comment]
I don't think this issue should be discarded. @pocmo?

**Comment by pocmo** [comment]
Agree

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810665

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
