### ISSUE TITLE
FNX-480 ⁃ [Bug] Remove second line on search suggestions

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1741]
![search suggestions](https://user-images.githubusercontent.com/107992/56323285-fea40f80-6130-11e9-89b5-4764dabb2d73.png)

Let's remove this second line under the search suggestions. We've already got the logo in the search field.

**Comment by sv-sdeiac** [comment]
Verified as fixed using the latest version of Firefox Preview Beta 4.0.0-beta.1.

Devices:
- Nokia 6 (Android 7.1.1);
- Samsung Galaxy S8 (Android 9).
