### ISSUE TITLE
[L10N] context for the expected behaviour od "clear downloads" feature

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/fenix#17415]
Hello mobile team.

As a localizer I was looking for context on how the "clear downloads" should work, especially whether it also removes files from the device, or only their entries from the downloads list.

The related [SUMO article](https://support.mozilla.org/en-US/kb/whats-new-firefox-android) mentions that version 84 supports _deleting_ files, which I understood as the file will be actually removed from the storage, but when I tested the feature on my phone, it did not happen. After using the "clear" button, the items were removed from downloads list in Firefox (FF 84 on Android 9), but files stayed inside my phone where they were downloaded.

Can you please provide a description what is the expected behaviour? Thank you in advance.

/cc @soucet @Delphine

**Comment by MikkCZ** [comment]
The related strings are `download_delete_ ...` which also happen to mix _delete_, _clear_ and _remove_ terms btw.

**Comment by Amejia481** [comment]
cc @kglazko

**Comment by Delphine** [comment]
Flagging @betsymi as I believe she can advise about this too

**Comment by MikkCZ** [comment]
I would like to extend this request also for `preferences_delete_browsing_data_downloads`. Thank you.
