### ISSUE TITLE
[Bug] open select tabs summary often displays no open tabs and hangs

### ISSUE THREAD

**Issue by handyguy2** [mozilla-mobile/fenix#17426]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Click open select tabs summary button

### Expected behavior
All open tabs are displayed and you can switch to another tab or open a new tab

### Actual behavior
No tabs are displayed and the application hangs or crashes about 25% of the time.
### Device information
Samsung Tab S2 8.0
* Android device: ? Android 10
* Fenix version: ? Many Nightly versions. currently on 20210106 143101 (build 2015785801)
 
![Screenshot_20210113-092038_Firefox_Nightly](https://user-images.githubusercontent.com/42753983/104488854-2e917880-558c-11eb-8665-a5b311e0a01f.jpg)

**Comment by abodea** [comment]
Thank you for this report @handyguy2!
We didn't encounter this issue for the past months on tablet devices or phone devices.
I tried to reproduce it today with my Google Pixel 4 XL (11) on the latest Nightly 3/31/21 but I was not able to repro it.
Do you still reproduce this issue?

**Comment by handyguy2** [comment]
Hi,
Yes, it is still happening to me, on many different nightly releases. My Device is older, a Samsung Tab S2 8.0 running Android 10.
