### ISSUE TITLE
Text selection context menu customisation (order, icon/text, multi-line)

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#17427]
### What is the user problem or growth opportunity you want to see solved?
Currently, the items of text selection context menu seem fixed: copy, search, select all, share, more (three dot). I have seen an old request for "more useful order", but probably a fixed order won't fit everyone's different needs. How about some customisation features like,
 
* Custom order: For example, I want to switch the position of "share" and "Translate".
* Display option: Text, Icon, or Text with Icon. Personally, I would choose "icons" because they take less space, and easy to distinguish than texts.
* Multi-line: My screen is large enough. Why do I have to click "more" to see more items each time? If the context menu has two rows, it would not need the "more" button.

### How do you know that this problem exists today? Why is this important?
For example, I use the "Translate" menu from Google Translate often, and it is located inside of "more", so each time, I have to click more and then "translate". It takes extra steps and time for me. 

### Who will benefit from it?
If it is customisable, it will be better for anyone. People who have no complaint about the current fixed order won't be affected, and people who want a different order, it will be helpful.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9374)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813260

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
