### ISSUE TITLE
Reflecting On Mozilla's Deplatforming Blog

### ISSUE THREAD

**Issue by Dev-i-l** [mozilla-mobile/fenix#17425]
## User Story
-So.. the organisation that wanted to liberate the internet is going political? Mozilla, you had one job, and it seems like you are failing in it too (including telemetry by default and tracking users). What do you want mozilla? Censor trump? or censor any individual who is guilty in your eyes? That is subjective mozilla, it is not your concern who remains on the internet and who doesn't. Power corrupts, yes and absolute power corrupts absolutely, if you were to have the absolute power to censor anyone on the internet, it would be tyranny. Mozilla, you are crossing a line here. Please stop.

You were the chosen one!
It was said that you would destroy the censorship, not join it!
Bring balance to the internet, not leave it in censorship!
You were my browser, firefox
I loved you

I hope you will feel the pain there and mozilla will re-evaluate who they are and what they do

**Comment by Dunexus** [comment]
This repository is about Fenix. It is a tool for dev team and not a good place for this kind of discussion about the Mozilla Foundation.

**Comment by mcarare** [comment]
This is not a blog, but a repository. Closing this as it is unrelated to Fenix.
