### ISSUE TITLE
Add an automatic page translator tool

### ISSUE THREAD

**Issue by mzulkifli757** [mozilla-mobile/fenix#17422]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Yes And I Want To See It Resolved
### How do you know that this problem exists today? Why is this important?
This is very important because it is in the Google Chrome browser
### Who will benefit from it? This will be very useful for everyone. They see a language they can understand when viewing Web pages in a foreign language......,,,,!!!! 
Hey Mozilla Firefox. Whether You Can Add Web Page Translator Tool Automatically Translate Web Pages in Foreign Languages ​​Automatically .. ° Polishes

**Comment by cadeyrn** [comment]
Duplicate of #6133.

**Comment by mcarare** [comment]
@mzulkifli757 Thank you for your report. I am closing this as a duplicate of https://github.com/mozilla-mobile/fenix/issues/6133. Feel free to add comments or reactions in that thread.
