### ISSUE TITLE
[Bug] Don't show a search suggestion for your exact typed characters

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1742]
If I type part of a search term in the search field, e.g. "mu" my first "suggestion" is a search for "mu" which is already what will happen if I hit enter. So this is redundant and we can save a row/display more relevant suggestions.

![more suggestions](https://user-images.githubusercontent.com/107992/56323783-863e4e00-6132-11e9-836e-d0b90dcbf4bd.png)

**Comment by Mugurell** [comment]
Initially went with implementing a new flag in `SearchSuggestionProvider` to allow choosing if we want or not to [add the entered text as the first suggestion](https://github.com/mozilla-mobile/android-components/blob/b8990c13eb514bdb8477e687c5e479c8ab188a72/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt#L92) 
but then I saw that in the cases that the text is autocompleted not offering the option to search for the entered text would become an issue.
With this in mind I've created an AC ticket - https://github.com/mozilla-mobile/android-components/issues/3865

**Comment by bifleming** [comment]
@boek is this waiting for A/C after all then?

**Comment by vesta0** [comment]
This may be a desired behaviour. There is a use case for when user wants to search for a URL instead of going to a URL (e.g. searching for Mozilla.com instead of navigating to Mozilla.com). I have added the `Needs:UX-feedback` label as I'd like to UX to confirm their recommendation after considering this use case.

**Comment by lime124** [comment]
passing to @Verdi for comment

**Comment by mcarare** [comment]
Question for UX: Should we show search suggestions for exact typed characters? See Mugurell's comment: https://github.com/mozilla-mobile/fenix/issues/1742#issuecomment-514232895.
Also, note that Chrome shows search suggestions for exact typed characters.

**Comment by brampitoyo** [comment]
@Verdi’s initial suggestion makes a lot of sense: having the address bar show “abc” and the first suggestion show “abc” – same text in two different places – is redundant.

However, this conflicts with two things:

1. Autocomplete
    - If “abc” is autocompleted to “abc.com”, I can no longer search for “abc” quickly by tapping “Return”. I must first tap “Backspace”, then “Return”.
    - Solution: if my query is autocompleted, then it should also appear as a search suggestion entry. This facilitates search for any word I want, without using “Backspace”.
    - We should implement @Mugurell’s suggestion on #3865.
2. Search for a domain
    - Hypothesis: when I type “abc.com”, sometimes I want to search for that site, not go to the URL
    - We may roll our eyes, but this behaviour is realistic. To go to Facebook, some users would type “google.com”, then search for “facebook.com”, then tap the first search results.
    - Autocomplete solves this problem. Case closed. But let’s just say that some users really do prefer to search for a URL sometimes, rather than go to it.
    - In that case, @Mugurell’s suggestion on #3865 should be applied:
        - If I type “abc.com”, the query gets autocompleted
        - But I don’t want to go to the URL! That’s fine, because “abc.com” would also appear as a search suggestion entry.
        - If I want to go to the URL (which is hopefully most of the time), I simply tap “Return”
        - If I want to search, then I tap the search suggestion entry

Hopefully I’ve outlined a clear suggestion:

- This issue is indeed a bug, and we should fix it.
- Fixing this issue will introduce a few minor issues, but fixing #3865 will address those.

**Comment by sblatz** [comment]
I'm curious why we feel we should not duplicate the text here. On desktop it's duplicated?

<img width="348" alt="image" src="https://user-images.githubusercontent.com/4400286/75730637-52184100-5ca2-11ea-8a85-ada7f39fdfce.png">

Is the argument here that the real estate we're working with is limited so we want users seeing more "actual" suggestions? I could see many users not knowing that "GO" would search their result and would prefer tapping the first result

**Comment by sblatz** [comment]
I like @brampitoyo's suggestions here! We've decided that this is probably not critical to fix ASAP so I'm going to de-prioritize this on the workflow board.
