### ISSUE TITLE
FNX-5222 ⁃ [Bug] Align search results with logo in the search field

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1743]
![](https://user-images.githubusercontent.com/107992/56323976-2300eb80-6133-11e9-911b-1e9d9980a802.png)

We should visually align the list with the search engine logo in the search field.

**Comment by lime124** [comment]
@Verdi @shorlander can you clarify the expectation on alignment of elements in this screen?

Do only the visual elements align (magnifying glass and search logo) ? Or should both the text and the visual elements be aligned? Thanks!

**Comment by lime124** [comment]
as per shorlander: "Search Result Icon and Label should align with Search field Icon and Label"

**Comment by vesta0** [comment]
Perhaps this can be updated at the same time as #1443

**Comment by bwinton** [comment]
@Verdi (or whomever), how does this look?
<img width="563" alt="short search" src="https://user-images.githubusercontent.com/159571/57397330-70083880-719a-11e9-8d07-b6c3ac7d11c7.png">


And for really long search suggestions:
<img width="534" alt="Screen Shot 2019-05-08 at 14 07 17" src="https://user-images.githubusercontent.com/159571/57397424-a8a81200-719a-11e9-8bd7-f56cbddaba7f.png">

**Comment by Verdi** [comment]
@bwinton Almost there. Should be like this:
![results alignment](https://user-images.githubusercontent.com/107992/57403279-f58de780-719e-11e9-96c3-f157d4dcbcda.png)

**Comment by bwinton** [comment]
Okay, I think this might be the one… 🙂
<img width="516" alt="Screen Shot 2019-05-08 at 16 54 34" src="https://user-images.githubusercontent.com/159571/57407880-3511ff00-71b2-11e9-80e9-836979b77e14.png">

PR incoming…

**Comment by Verdi** [comment]
This looks great! Thanks Blake.
