### ISSUE TITLE
Add share option in PWA

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17430]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently the pwa apps shows in full screen and if a user browse some parts of the pwa and wants to share the URL there is no such option! 

### How do you know that this problem exists today? Why is this important?
Please add share button apart from refresh button in pwa. 
Chromium browsers have the option. 

### Who will benefit from it?
All users. 

![Screenshot_20210113-180450772](https://user-images.githubusercontent.com/58127841/104453441-6cad8d00-55ca-11eb-8569-c6f310f71b1c.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9377)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807421

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
