### ISSUE TITLE
[Bug] dev pixel per pixel does not update after resolution change.

### ISSUE THREAD

**Issue by tarlovsky** [mozilla-mobile/fenix#17433]
I am running latest release Forefox on Android 10 inside a Samsung Note 9.

Fifefox does not update layout.css.devpixelsperpx accordingly. The only solution appears to be reinstalling firefox with the desired resolution.

When you change device resolution down to 720p the elements in the browser become very large. When I go back to native resolution things become extremely small.

Thanks.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1686518

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
