### ISSUE TITLE
Some strings provide search suggestions 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#17431]
## Preconditions
Fresh install.
## Steps to reproduce
1. Launch Fenix and in the URL bar type any of the following: `http:` `https:` `ftp:` `about:` `file://` `a://` `b:` `c:\` `d:/` `etc`.
2. Observe the search suggestions.

### Expected behavior
No search suggestions are shown.
### Actual behavior
Some strings provide search suggestions 
### Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 1/13.**
 
![xd11](https://user-images.githubusercontent.com/42831109/104456400-44fdfb00-55b1-11eb-85ea-5deeb4d0e5f9.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9378)

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the RC 85.1.0-rc.1 build with Samsung Galaxy Tab S6 (Android 10).

**Comment by delia-pop** [comment]
Reproducible on Beta 100.0.0-beta.4 with Google Pixel 6 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
Reproducible on Beta 101.0.0-beta.1 with Google Pixel 4 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
Reproducible on the latest Beta (108.0a1) using an Oppo Find X5 (Android 12).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807569

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
