### ISSUE TITLE
[Bug] Dev pixel scaling issue after resolution change.

### ISSUE THREAD

**Issue by tarlovsky** [mozilla-mobile/fenix#17432]
I am running latest release Forefox on Android 10 inside a Samsung Note 9.

Fifefox does not update layout.css.devpixelsperpx accordingly. The only solution appears to be reinstalling firefox with the desired resolution.

When you change device resolution down to 720p the elements in the browser become very large. When I go back to native resolution things become extremely small.

Thanks.

**Comment by cadeyrn** [comment]
Same as #17433.

**Comment by kbrosnan** [comment]
Closing as a duplicate

**Comment by tarlovsky** [comment]
Github on Firefox bugged out and sent me to plain ol' 404 the first time. Wasn't sure it posted. My bad.
