### ISSUE TITLE
v68.11.0升级到84.1.2后发现每次打开浏览器都会自动恢复所有标签，能不能不要自动恢复？

### ISSUE THREAD

**Issue by 1265578519** [mozilla-mobile/fenix#17449]
v68.11.0升级到84.1.2后发现每次打开浏览器都会自动恢复所有标签，能不能不要自动恢复？
以前版本有选项的，怎么新版本反而没有这个设置了呢！

**Comment by rxumoz** [comment]
这个设置确实变了，和以前不一样了，但是你可以在设置-标签页里可以选是手动关闭标签页还是一天/一周/一个月后自动关闭

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/104582475-e44aed00-569a-11eb-96f8-8874c4cde223.jpg)
不知道能不能把这个设置重新做出来，，，这标签恢复真的是太难用了！

**Comment by sflorean** [comment]
@1265578519 Please open an issue in English, in order for us to be able to investigate. Thank you!

**Comment by 1265578519** [comment]
@sflorean 你不会用翻译？
