### ISSUE TITLE
FNX-5223 ⁃ Show "fill in from clipboard" on search engine screen

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#1744]
### Why/User Benefit/User Problem
If we open search shortcuts automatically when you:

1. Tap into the search field from the front page
1. You open a new tab
1. You clear the search field

We make it easy for people to select an alternate search engine.

### What / Requirements
* The Search Shortcuts should be displayed below the "Fill link from clipboard" function if applicable.
* The Search Shortcuts button should be selected
* Once you start typing, the Search Shortcuts should close

![Search Shortcuts](https://user-images.githubusercontent.com/107992/56324865-c2bf7900-6135-11e9-9244-cefa40491bf5.png)

**Comment by sblatz** [comment]
I'm not sure I agree with this. I think it's a great idea for the search widget, but if it feels a bit weird to launch with this button pressed.

**Comment by Verdi** [comment]
I wouldn't do something different for the search widget. We want the search experience to be consistent. As far as starting with the shortcuts expanded, I talked this over with both shorlander and mconnor and we agreed we'd like to try this.

**Comment by sblatz** [comment]
@Verdi If the user doesn't want to use search shortcuts, they would have to press their default engine before getting search suggestions. Typing alone does not dismiss this menu. That seems confusing to me. What's the point in having a default engine if I have to pick each time 🤔

**Comment by Verdi** [comment]
@sblatz My interaction requirements above say, "once you start typing, the Search Shortcuts should close."

**Comment by sblatz** [comment]
@Verdi Ah, missed that! Sorry for the confusion :)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190806 (#12180610) with LG G7 Fit (Android 8.1), and Nexus 5 (Android 6).

**Comment by Verdi** [comment]
The shortcuts appear but the "Fill in from clipboard" command doesn't show. 

> ### What / Requirements
> 
>    * The Search Shortcuts should be displayed below the "Fill link from clipboard" function if applicable.
> 
> 
> ![Search Shortcuts](https://user-images.githubusercontent.com/107992/56324865-c2bf7900-6135-11e9-9244-cefa40491bf5.png)

**Comment by sblatz** [comment]
@Verdi should that clipboard suggestion appear any time a user is in the shortcuts screen (from "shortcuts" button press AND from just opening search screen)? Should it disappear when the user starts typing?

**Comment by Verdi** [comment]
@sblatz It should only ever appear when applicable (url in the clipboard) and it should go away like normal when the user starts typing.

**Comment by sblatz** [comment]
Updated the ticket's title to reflect the work left.

**Comment by sblatz** [comment]
I think we will need an android component change for this. Basically this "fill in link from clipboard" button being in the same awesomebar with this different styling is not currently possible.

**Comment by liuche** [comment]
This would be an E5 if Fenix did the AC work as well.

**Comment by sblatz** [comment]
@Verdi To confirm: is the "Fill in from clipboard" item pinned to the top rather than scrolling with the rest of the suggestions? Given that there's a line break, this would visually make sense to me, and it also makes the engineering effort much easier. The "SEARCH WITH" text is already pinned, so it'd make sense that anything above it would be too.

**Comment by sblatz** [comment]
@jpfaller The current text we have in app is "Fill link from clipboard." Can we keep that or should we change it to the text in the screenshot above?

**Comment by jpfaller** [comment]
Let's keep the current text "Fill link from clipboard"

**Comment by softvision-miralobontiu** [comment]
Verified that the "Fill link from clipboard" is displayed when tapping on the search bar, if the user copied something in the clipboard.
Tested on the latest Nightly build 19092019 (#12621820) with Xiaomi Mi 8 Lite (Android 9), and Nexus 9 tablet (Android 7.1.1).
