### ISSUE TITLE
New auto play option Block video only

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17454]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Is it possible to implement a new autoplay block option "Block video only" . The very useful use case of this will be in sites like youtube wherein you can just listen audio without the video similar to the youtube audio add on. 

### How do you know that this problem exists today? Why is this important?
Currently there is no option to block video only and thus we cannot listen songs in some sites without playing video. This must be implemented to save bandwidth and use the sites to listen songs or music only.. There is one add called youtube audio which does the same job but it is not available and limited only to youtube only. 

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9391)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813258

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
