### ISSUE TITLE
[Telemetry] Quite a few latest version fenix sending data without distribution_id

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#17459]
In this query https://sql.telemetry.mozilla.org/queries/77101/source we found that there are quite a few latest version apps sending data without **_distribution_id_**.
Since the _**distribution_id**_ should be set to either **MozillaOnline** or **Mozilla** according to the code in [GleanMetricsService.kt](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L780), we think it is confusing:
```
distributionId.set(     
    when (Config.channel.isMozillaOnline) {     
        true -> "MozillaOnline"     
        false -> "Mozilla"     }    )
```
Having had a short discussion with @st3fan last week, and he thinks there might be a possibility that _Config.channel.isMozillaOnline_ is not set at all.

So this issue is used to discuss the reason why some _distribution_ids_ are not set.

**Comment by st3fan** [comment]
Investigation in Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1694343
