### ISSUE TITLE
FNX-5224 ⁃ Allow Trackers for sites on the Exceptions list

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#1745]
As a user who has tracking protection enabled globally, I want to be able to allow trackers for specific sites, so I can have an unbroken experience on those sites only and still be protected on all other sites. 

## Dependencies
* UX designs: #1064 

### Acceptance Criteria
I can turn off TP for a specific site and have that site added to my Exceptions list
I can return to the site in another browsing session and see that TP is still disabled
I can go to my settings and find the site listed as an exception that allows trackers
I can remove a site from my Exceptions list

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/15 build.
