### ISSUE TITLE
Increase limit of text zoom

### ISSUE THREAD

**Issue by timpster1750** [mozilla-mobile/fenix#17456]
[Current accessibility settings allow doubling the font size.  On websites with a wide page, this still requires scrolling horizontally if the user needs to zoom into the page further.

This could be remedied with one of two features:

* text-wrapping
* larger than 200% font size in the settings.  I'd like to see 300 or even 500% as the new limit]

(Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

I want larger text on certain websites (especially on tablet screens where many websites format to a wider text column in forums and some article websites.

### How do you know that this problem exists today? Why is this important?

The current limit is only 2x the normal font size.  50% of Americans wear prescription eye-wear according to UVEX(R) and anyone who uses this feature will benefit.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9393)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813257

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
