### ISSUE TITLE
keyboard should open automatically when you tap "Close all tabs"

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#17453]
One of the nice little UX efficiency features in Fenix is that, when you open a new tab, the keyboard pops up automatically so you can start typing right away. It's great! But I think they forgot to implement this when the user selects "Close all tabs" or when they only have 1 tab open and they close it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9390)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813259

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
