### ISSUE TITLE
FNX-55 ⁃ Fenix Should Pop Out Videos

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/fenix#1746]
### Why/User Benefit/User Problem
When I'm using Fenix, I want to be able to have videos playing from one tab while I'm perusing other tabs or content on the current tab.

This will keep folks using Fenix more so they get more TP, more security, more Mozilla. :grinning:

### What / Requirements
Something like this
![IMG](https://user-images.githubusercontent.com/4879954/56325725-14f99d80-6128-11e9-9380-28a7df28ab68.jpeg)UNITO-UNDERSCORE!4268D5477E32-1!

### Acceptance Criteria (how do I know when I’m done?)
Users can pop out videos and have them play while using Fenix.

**Comment by liuche** [comment]
Maybe this is a use case that #2818 would be able to solve? For now, I'm going to dupe it.
