### ISSUE TITLE
[Bug] Entering something into the search bar causes the app to lag

### ISSUE THREAD

**Issue by stuffi3000** [mozilla-mobile/fenix#17469]
Hello!

I've been using Firefox Nightly on my Samsung Galaxy A40 for a while now and never really encountered any issues. However, since a couple of days, when trying to enter anything into the search bar, the whole app begins to lag.
Typing something on the keyboard only shows up after around 5-7 seconds. Typing out a larger sentence results in Firefox trying to suggest a link based on the first letters of the first word used, merging the suggestion into the phrase where it shouldn't belong.

It's not easy to explain but it's basically input lag.

Pressing the back button to go back onto a website works fine, no lag is felt here. Typing something into a form on any website (like here) works without encountering any difficulties.
A few screenshots are attached in a comment below. They of course cannot show the lag, but as you can see, a word is already typed out in my keyboard but does not show up in the search bar.

I'd happily give out any more information you need.

## Steps to reproduce

1. Click into the Search Bar
2. Type any word

### Expected behavior

Words should show up instantly as their letters are typed out on the keyboard. 

### Actual behavior

Input lag occurs, preventing fluid typing and forcing to wait for a reaction before typing out the next letter/word. 

### Device information

Samsung Galaxy A40
ARM
Android 10
Not rooted

App information:
Nightly 210113 17:01 (Build #2015787147)
AC: 71.0.20210113143107, 6e0ffb55e
GV: 86.0a1-20210113100240
AS: 67.2.0

**Comment by stuffi3000** [comment]
Referencing #17460
I wanted to type out my own explanation and felt like the beforementioned issue was not well structured enough.

**Comment by stuffi3000** [comment]
![Screenshot_20210114-211353_Firefox Nightly](https://user-images.githubusercontent.com/11315157/104648303-3c8de900-56b3-11eb-866b-dbaebe4f0c4f.jpg)
![Screenshot_20210114-211415_Firefox Nightly](https://user-images.githubusercontent.com/11315157/104648305-3d267f80-56b3-11eb-8439-7d291f422e77.jpg)
![Screenshot_20210114-211433_Firefox Nightly](https://user-images.githubusercontent.com/11315157/104648308-3dbf1600-56b3-11eb-8e72-fd16db3f0621.jpg)
![Screenshot_20210114-211353_Firefox Nightly](https://user-images.githubusercontent.com/11315157/104648328-457eba80-56b3-11eb-9d3b-6344e7656783.jpg)

**Comment by stuffi3000** [comment]
It works fine again as of today (15/01/2021), without me changing anything. I didn't even restart my phone.
Leaving this open as it might we worth investigating.

**Comment by sflorean** [comment]
@stuffi3000 this is still reproducible for you?
Tested on latest Nightly, and we also perform different scenarios on RC but we couldn't reproduce the issue.
Devices: Samsung Note 10 (Android 11) and LG G7 Fit (Android 8.1).

**Comment by stuffi3000** [comment]
@sflorean it's not reproducible on my end anymore, and as nobody else seems to have this issue anymore, I suppose it can be closed :)
