### ISSUE TITLE
[Bug] The selected option is not highlighted anymore after a home button interrupt in autoplay menu

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#17464]
## Steps to reproduce
1. Launch Fenix.
2. Access cnn.com or any website.
3. Tap on the `autoplay` control button on the URL bar.
4. Select an option and perform a home button interrupt.
5. Return to Fenix.
### Expected behavior
The selected option is still highlighted.
### Actual behavior
The selected option is not highlighted anymore after a home button interrupt 
### Device information

* Android device: **Google Pixel 4 XL (11).**
* Fenix version: **Nightly 1/14/21.**
 
![ezgif-4-313bb2f930ea](https://user-images.githubusercontent.com/42831109/104614034-86b1a300-5690-11eb-9541-0ce0c207633a.gif)

**Comment by Amejia481** [comment]
@mcarare put a fix for the issue, it should be in master now, QA team please help us to verify :)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 1/29 with Pixel 4 XL (Android 11).
