### ISSUE TITLE
[Bug] The selected tab is not displayed in Recently closed tabs list when closing all the opened tabs from Tabs tray, one by one

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17462]
## Steps to reproduce
1. Launch Fenix;
2. Open 2 or more tabs;
3. Go to Tabs tray and close all the tabs one by one;
4. Go to History -> Recently closed tabs;
5. Observe the Recently closed tabs list;
### Expected behavior
All the closed tabs are displayed in the Recently closed tabs list.
### Actual behavior
The selected tab is not displayed in Recently closed tabs list when closing all the opened tabs from Tabs tray, one by one.
Also the Recently closed tabs tabs counter is not updated before opening the list.

![20210114_144244](https://user-images.githubusercontent.com/48799384/104594278-9d98cb00-5679-11eb-91aa-14ae316f465a.gif)

### Notes
This is not reproducible when closing all the opened tabs with "Close all tabs".

### Device information

* Android device: Samsung Galaxy Tab S3 (Android 8);
Not reproducible with Pixel 4 (Android 11);
* Fenix version: Nightly 1/14;
Not reproducible on Beta 1/12 and Release 1/7;

**Comment by pocmo** [comment]
Fixing in AC: https://github.com/mozilla-mobile/android-components/issues/9410

**Comment by pocmo** [comment]
A patch landed in AC and should be in the next Nightly.

**Comment by sflorean** [comment]
@pocmo this is still reproducible on latest Nightly build (1/18) with Samsung Note10 (Android 10), AC: 71.0.20210114143040, 96d4bc2e3.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 1/19 with Motorola Moto G6 (Android 8), Samsung Galaxy Tab S3 (Android 8), Nexus 5 (Android 6.0.1).
The Recently closed tabs tabs counter is not updated before opening the list and I filed https://github.com/mozilla-mobile/fenix/issues/17523
I will close this issue.
