### ISSUE TITLE
checkNotNull taking significant time on start up

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#17472]
Investigate `Instrinsics.*` (`checkNotNull`) for perf issues (remove it via compiler args or proguard)

**Comment by mcomella** [comment]
Relevant forum discussion: https://discuss.kotlinlang.org/t/run-time-null-checks-and-performance/2086/16

**Comment by MarcLeclair** [comment]
With a progard check of 

```-assumenosideeffects class kotlin.jvm.internal.Intrinsics {
    static void checkNotNullParameter(java.lang.Object, java.lang.String);
}
```

https://share.firefox.dev/3ixjXfr

and without 

https://share.firefox.dev/396LotH

**Comment by mcomella** [comment]
Triage: this looks like a real issue but we don't fully understand the implications of disabling it. The action items that MarcLeclair and I should do together:
- See if already filed in kotlin. If so, comment on it (with thoughts below). If not, file new issue with kotlin
- Comment on thread with similar effect to issue
- Consider raising awareness in android community with blog post?

Some thoughts we should consider and may want to ask the kotlin team:
- Is there anything we can do with this (besides stripping the statements)?
  - Maybe ship in release but not in beta+? Do other apps do this, or similar things (Chrome, Firefox Nightly Gecko)? What are their experiences?
- If we disable this, what are the worst possible effects? Can we even reason about it?
  - Can add null to DBs and similar
  - Affects lateinit vars?

**Comment by mcomella** [comment]
Triage: we have other issues to handle the action items in the comments above. We need to wait for a response in those issues so we'll put this in waiting.

**Comment by mcomella** [comment]
We had filed upstream: https://youtrack.jetbrains.com/issue/KT-45387 And it's not practical for us to fix locally so closing.
