### ISSUE TITLE
[Telemetry] Remove unused long_press_tapped from metrics.yml

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#17481]
At the moment `long_press_tapped` from `contextual_menu` isn't being used. 
We should remove it from `metrics.yaml`.

Original issue that led to this: https://github.com/mozilla-mobile/fenix/issues/11580

**Comment by codrut-topliceanu** [comment]
@kglazko Please let me know if you'd like further changes to the the names of the metrics

**Comment by softvision-miralobontiu** [comment]
Verified that the "long_press_tapped" from contextual_menu is removed.
I've tested on the 1/25 Firefox Nightly build with Google Pixel (Android 10).

[Glean dashboard](data:application/json;charset=utf-8,%7B%22metadata%22%3A%7B%22geo%22%3A%7B%22city%22%3A%22Cluj-Napoca%22%2C%22subdivision1%22%3A%22CJ%22%2C%22country%22%3A%22RO%22%2C%22db_version%22%3A%222021-01-22T16%3A21%3A47Z%22%7D%2C%22isp%22%3A%7B%22organization%22%3A%22Orange%20Romania%22%2C%22db_version%22%3A%222021-01-18T19%3A15%3A18Z%22%2C%22name%22%3A%22Orange%20Romania%22%7D%2C%22user_agent%22%3A%7B%22os%22%3A%22Android%22%7D%2C%22header%22%3A%7B%22date%22%3A%22Thu%2C%2028%20Jan%202021%2005%3A56%3A37%20GMT%22%2C%22x_debug_id%22%3A%22mira-test-2101003%22%7D%2C%22document_namespace%22%3A%22org-mozilla-fenix%22%2C%22document_type%22%3A%22events%22%2C%22document_version%22%3A%221%22%7D%2C%22submission_timestamp%22%3A%222021-01-25T11%3A59%3A01.790169Z%22%2C%22document_id%22%3A%22908cf966-15e8-45a6-8175-c2f5c287ce2d%22%2C%22normalized_channel%22%3A%22nightly%22%2C%22normalized_os%22%3A%22Android%22%2C%22normalized_os_version%22%3A%2210%22%2C%22normalized_country_code%22%3A%22RO%22%2C%22sample_id%22%3A85%2C%22client_info%22%3A%7B%22android_sdk_version%22%3A%2229%22%2C%22app_build%22%3A%222015789355%22%2C%22app_channel%22%3A%22nightly%22%2C%22app_display_version%22%3A%22Nightly%20210125%2005%3A01%22%2C%22architecture%22%3A%22arm64-v8a%22%2C%22client_id%22%3A%222c4504e0-c91c-401a-82ab-ce2f6bc01d98%22%2C%22device_manufacturer%22%3A%22Google%22%2C%22device_model%22%3A%22Pixel%22%2C%22first_run_date%22%3A%222021-01-26%2B02%3A00%22%2C%22locale%22%3A%22en-US%22%2C%22os%22%3A%22Android%22%2C%22os_version%22%3A%2210%22%2C%22telemetry_sdk_build%22%3A%2233.1.2%22%7D%2C%22events%22%3A%5B%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22source%22%3A%22UNKNOWN%22%7D%2C%22name%22%3A%22app_received_intent%22%2C%22timestamp%22%3A0%7D%2C%7B%22category%22%3A%22reader_mode%22%2C%22name%22%3A%22available%22%2C%22timestamp%22%3A7431%7D%2C%7B%22category%22%3A%22tabs_tray%22%2C%22name%22%3A%22opened%22%2C%22timestamp%22%3A11738%7D%2C%7B%22category%22%3A%22events%22%2C%22extra%22%3A%7B%22first_frame_pre_draw_nanos%22%3A%2277791258%22%2C%22source%22%3A%22UNKNOWN%22%2C%22type%22%3A%22HOT%22%7D%2C%22name%22%3A%22app_opened_all_startup%22%2C%22timestamp%22%3A13021%7D%5D%2C%22ping_info%22%3A%7B%22end_time%22%3A%222021-01-28T07%3A56%2B02%3A00%22%2C%22reason%22%3A%22background%22%2C%22seq%22%3A16%2C%22start_time%22%3A%222021-01-28T04%3A03%2B02%3A00%22%7D%7D)
