### ISSUE TITLE
[l10n] Locale sign-off for v85

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#17493]
No new strings since v84, no new locales.
Please import latest strings from *Fenix* and *A-C* for v85.

**Comment by st3fan** [comment]
This is the PR for Fenix https://github.com/mozilla-mobile/fenix/pull/17494 as of Jan 15th.

**Comment by st3fan** [comment]
@csadilek i don't know the process for A-C uplifts - would you mind either doing that or add it to the sprint so someone can pick it up?

**Comment by csadilek** [comment]
@st3fan OK, put up a PR for A-C 70 so we have all Strings as of Jan 15th as well: https://github.com/mozilla-mobile/android-components/pull/9438
