### ISSUE TITLE
FNX-5226 ⁃ [UX] Error Messages + Pages

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#175]
**User Story:**
As a user I want to be notified if an error occurs whiles browsing the web.

**Current Design Status:**

* No Designs
* Needs Requirements and Definition including:
* List of error messages to support
* Needs Visual and Content Design

**References:**

* See list of current error messages in Fennec and/or Desktop

**Design Priority:**
P2

**Comment by bbinto** [comment]
@vesta0 and @st3fan to confirm status of error pages / messages for Fenix

**Comment by lime124** [comment]
Michelle is meeting with Flod tomorrow to export strings from Fennec so she can review and make recommendations.

**Comment by pocmo** [comment]
Note that there's the `browser-errorpages` component that we have been using across products (e.g. in Focus).

**Comment by mheubusch** [comment]
Thanks, Sebastian. Delphine pointed those out to me.

**Comment by mheubusch** [comment]
Hello - Here are the error messages that currently exist in Moz-Central and Android Components.  I still need to do the legwork to understand which ones are in use and relevant. See tabs Android Component Errors and Mercurial Android Errors. https://docs.google.com/spreadsheets/d/1SIAm3XZz5uGOm39rAR1hcCje7XYOfqqfSkxnXWttBeU/edit?usp=sharing

**Comment by mheubusch** [comment]
@colintheshots Hello - would like your help sorting thru mobile error strings and understanding which are relevant for Fenix and what the implications are of making changes to address inconsistencies

**Comment by pocmo** [comment]
FYI: @ekager integrated the errorpages component and the error pages can be seen in the latest Fenix Nightly now.

The strings from the component are all in use. They are the same strings we used in Focus (which is using the component too nowadays):
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/errorpages/src/main/res/values/strings.xml

**Comment by bbinto** [comment]
@lime124 to follow-up with @mheubusch about status

**Comment by bbinto** [comment]
@shorlander will need to work with Sean to potentially update styling.

**Comment by brampitoyo** [comment]
# Mocks

https://mozilla.invisionapp.com/share/FXR7YVSHT3G

# Design note

We’ve tried really hard to keep the copy as brief and understandable as possible. However, they sometimes run longer than the length of the page.

When this happens, put a square backdrop underneath the “Try Again” button:

* This backdrop is set to the same colour as the page background
* This backdrop should have a drop shadow to distinguish it from the page background

When the content runs long, it will flow underneath this backdrop. If the content is short, this backdrop won’t show up.

# Risk levels

As in desktop, we’re adopting the same 3 levels of risk:

* Low risk
    * Most errors belong here
    * Illustrations are varied and whimsical
    * Action: Try again
* Medium risk
    * Only applies to SSL and other security errors
    * Uses only one illustration: broken lock – it’s more serious
    * Action: Go back
* High risk
    * Only applies to SafeBrowsing warning pages
    * Doesn’t use any illustration, and comes with a high-visibility red background
    * Action: Go back

**Comment by colintheshots** [comment]
This looks good. I only have two questions... Can we have dark mode versions? Do we want this to display over everything except the status bar and navigation bar, since that's exactly what the mocks show?

**Comment by lime124** [comment]
@colintheshots 

we're going to punt on dark mode for post MVP. can you file an issue so that we can follow up on that? 

the URL bar needs to be displayed so the user can go do something else or see what page they are on.

**Comment by mheubusch** [comment]
@AmyYLee can you update the design specs to show that the URL appears and then move this out of feedback for eng?

**Comment by AmyYLee** [comment]
@mheubusch The screens have been updated. It looks like the feedback tag is already removed and is ready for engineering

**Comment by vesta0** [comment]
@mheubusch please advise if this UX meta can be closed.
