### ISSUE TITLE
[webcontent] Redundant space in some websites

### ISSUE THREAD

**Issue by KatoriYuu** [mozilla-mobile/fenix#17504]
## Site with issue and any steps to reproduce
For example:
https://cp-algorithms.com/
https://www.xda-developers.com/
### Expected behavior
Sites are loaded normally.
### Actual behavior
There are redundant space in the websites.
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No.
### Can you reproduce in Chrome (or other non-Mozilla browser)?
No.

### Device information

* Android device: Nokia 8.1, Android 10
* Fenix version: 84.1.4

**Comment by KatoriYuu** [comment]
![Screenshot_20210117-103349](https://user-images.githubusercontent.com/42930110/104830411-880de600-58b1-11eb-86c0-92b33cf586c8.png)
![Screenshot_20210117-103847](https://user-images.githubusercontent.com/42930110/104830414-90feb780-58b1-11eb-805d-1a5db910bff0.png)

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1690281

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by sflorean** [comment]
This issue is still reproducible on latest Nightly build with Pixel 3 (Android 11), but not on Chrome.
