### ISSUE TITLE
[Bug] Page is always being re-rendered when switching between apps

### ISSUE THREAD

**Issue by genodeftest** [mozilla-mobile/fenix#17501]
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open firefox mobile
2. Open any website and wait until it is loaded
3. From the open website (tab), press the three-dots-menu
4. Press the _share_ button
5. Select an app to share with (e.g. KDE connect)
6. In the share app, go back to Firefox
7. Have a look at Firefox

### Expected behavior
Immediately present the full website as rendered in step 2.

### Actual behavior
Website re-renders. This takes some seconds.

### Device information
* Android device: Nokia 5 (HMD Global TA-1053)
* Fenix version: 84.1.4 (Build #2015785883, AC: 67.0.17, 2095f1a5d, GV 84.0.3-20210106212839, AS: 67.0.0)

**Comment by sflorean** [comment]
@genodeftest I wasn't able to reproduce this using Gmail (as share app) and latest Nightly build.
Device: Nokia 6 (Android 7.1.1).
This is still reproducible for you on latest release build?

**Comment by genodeftest** [comment]
Hi @sflorean, thanks for coming back to me and testing it!

I cannot reproduce this issue reliably on the official firefox 89.1.1 release (build #2015812947) any more.
I _think_ I have seen it lately (when not having screen recording at hand) but I think it only happens in low memory situations or if power saving is enabled, not as normal use case.
