### ISSUE TITLE
[Bug] Stripped first two octets of numerical URL when loaded in custom tab

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#17503]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Use an app that is able to load Firefox custom tabs, like https://play.google.com/store/apps/details?id=arun.com.chromer
2. load address like 10.0.0.1 or 192.168.1.1

### Expected behavior

location shown in address bar shows all of the octets (entire IP)

### Actual behavior

if loading 192.168.1.1, for example, the custom tab will show 1.1 - the first two octets are stripped. 

![signal-2021-01-16-120853](https://user-images.githubusercontent.com/152493/104818170-d9f03680-57f3-11eb-80e3-4e3f66f990ea.png)

### Device information

* Android device: Pixel 2
* Fenix version: latest nightly

**Comment by sflorean** [comment]
@yoasif this is still reproducible for you? Tested on latest Nightly build and couldn't reproduce the issue. Can you please attach a video of the issue?
