### ISSUE TITLE
[Bug] Redundant files and media permission requirement

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#17505]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1- Turn on external download manager pref in fenix
2- Download [adm](https://play.google.com/store/apps/details?id=com.dv.adm)
3- Download something

### Expected behavior
Fenix doesn't ask about files and media permission because adm is downloading, not fenix

### Actual behavior
Fenix doesn't let me download something without files and media permission

### Device information

* Android device: Xperia XZ1 Android 11 LineageOS 18.1
* Fenix version: 1/17 nightly

**Comment by hakkikaancaliskan** [comment]
Hmm i take a look at the code and if i bypass permission requirement we're boomed if user selects fenix in app selection dialog.
Just a question, why we are showing fenix in that menu? User already turned on external download manager pref and this means user doesn't want to download with fenix. I think we shouldn't add fenix to that list.
I think @Amejia481 is code owner for ac download component. What do you think about this?

**Comment by Amejia481** [comment]
> Hmm i take a look at the code and if i bypass permission requirement we're boomed if user selects fenix in app selection dialog.
> Just a question, why we are showing fenix in that menu? User already turned on external download manager pref and this means user doesn't want to download with fenix. I think we shouldn't add fenix to that list.
> I think @Amejia481 is code owner for ac download component. What do you think about this?
> 
> If we remove fenix from that list, we can easily fix this problem like this i think.
> ![image](https://user-images.githubusercontent.com/17825767/104964557-ae38a080-59ed-11eb-9bfc-d77c0c44250f.png)

We ported the feature from the previous Firefox for Android as it was, I'm not completely sure why we wanted to include the same browser as an option, I guess it is because we wanted to always give users the option to fallback to Firefox without changing the setting, but maybe @pocmo has a better explanation as he was back on the old days.

**Comment by Amejia481** [comment]
> > Hmm i take a look at the code and if i bypass permission requirement we're boomed if user selects fenix in app selection dialog.
> > Just a question, why we are showing fenix in that menu? User already turned on external download manager pref and this means user doesn't want to download with fenix. I think we shouldn't add fenix to that list.
> > I think @Amejia481 is code owner for ac download component. What do you think about this?
> > If we remove fenix from that list, we can easily fix this problem like this i think.
> > ![image](https://user-images.githubusercontent.com/17825767/104964557-ae38a080-59ed-11eb-9bfc-d77c0c44250f.png)
> 
> We ported the feature from the previous Firefox for Android as it was, I'm not completely sure why we wanted to include the same browser as an option, I guess it is because we wanted to always give users the option to fallback to Firefox without changing the setting, but maybe @pocmo has a better explanation as he was back on the old days.

Other wise we will need away to identify that we are choosing Fenix a downloader to show the permission dialog

**Comment by hakkikaancaliskan** [comment]
I think i found a way, I'll let you know.

**Comment by hakkikaancaliskan** [comment]
@Amejia481 Could you please review https://github.com/mozilla-mobile/android-components/pull/9442?

**Comment by hakkikaancaliskan** [comment]
@Amejia481 this issue also requires qa verify

**Comment by Amejia481** [comment]
👍🏽, lets wait until the new ac version get updated in Fenix to tag the QA team :)

**Comment by Amejia481** [comment]
The fix should be in master, please QA team help us to verify. Thanks in advance!

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build 2/3 with Pixel 3 (Android 11).
