### ISSUE TITLE
FNX-5227 ⁃ Update Private Browsing theme to match new design

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#1750]
# Mockups
https://mozilla.invisionapp.com/share/9QRLVJI8UZK

# Colour values
|Primary Text | Second Text | Foundation | Above | Above dark | Accent | Accent Bright | Neutral|
|----|----|----|----|----|----|----|----|
|`#FBFBFE` (same as dark theme) |`#A7A2B7` (same as dark theme) |`linear-gradient(45deg, #7529A7 0%, #492E85 50%, #383372 100%);` |`#291D4F` | Please generate this |`#722291` |`#F565FF` |`#B1B1B3` (same as dark theme)|

View these values alongside light and dark themes in the [Color Audit](https://docs.google.com/document/d/1EyFqVkR31iz4Cy4QTMlmN_O4rY_5ChCwJO4pMdCxpUw/edit) document.

**Private Browsing Mode settings doesn’t use its own theme**. It follows the theme that has been set in the app.

CC @sblatz @mheubusch and @AmyYLee

**Comment by AmyYLee** [comment]
Updated link to spec https://mozilla.invisionapp.com/share/YFR8WRD8WJ9

**Comment by sblatz** [comment]
We're timeboxing this to a 3 so we don't spend too much time trying to get the toolbar looking correct with the gradient.

This does not include adding the trash can button back or the "delete session" button as we've decided to not move forward.

**Comment by sblatz** [comment]
Can I get some clarification on which of these colors I should be using for card highlights?
<img width="301" alt="image" src="https://user-images.githubusercontent.com/4400286/60844344-d9ea9180-a18d-11e9-85ec-c7ef7159f667.png">
<img width="299" alt="image" src="https://user-images.githubusercontent.com/4400286/60844353-dd7e1880-a18d-11e9-9e42-77126a5b9bec.png">


Also, the card highlight color should match the button colors used throughout (as it does in light and dark theme). So keep in mind this color will be used for those too!

cc: @AmyYLee

**Comment by AmyYLee** [comment]
@sblatz Hi! Can we update the highlight colour for PBM to be the same as the new Dark theme update for "Buttons"? Color: Violet 50 (#9059FF)

https://github.com/mozilla-mobile/fenix/issues/1944
![Screen Shot 2019-07-09 at 5 01 54 PM](https://user-images.githubusercontent.com/5992746/60922696-4d160580-a26b-11e9-8b7e-f9b8177e61a5.png)

**Comment by abodea** [comment]
Verified as fixed in the latest Nightly build from **`7/24(190724(Build #12050609))`** with Samsung Galaxy s10+(Android 9).
![Screenshot_20190724-154028_Firefox Preview](https://user-images.githubusercontent.com/42831109/61795487-30153100-ae2c-11e9-954c-5b5ceea1fcbe.jpg)
![Screenshot_20190724-154021_Firefox Preview](https://user-images.githubusercontent.com/42831109/61795729-be89b280-ae2c-11e9-909f-d92a362457cf.jpg)

**Comment by brampitoyo** [comment]
@sblatz @abodea Just noting the fact that the Private Browsing toolbar should also have a gradient, in addition to the homescreen background: https://mozilla.invisionapp.com/share/DST592EZKRP

Should this issue be reopened?

**Comment by abodea** [comment]
@brampitoyo I just verified with the latest Nightly build from 7/25 and the Private Browsing toolbar doesn't have a gradient, I will re-open this issue until it will be fixed.
Thank you!

**Comment by abodea** [comment]
Verified as fixed on the latest **`Nightly 7/31 with Samsung Galaxy s10+(Android 9).`**
