### ISSUE TITLE
Set startup pages: open same specific urls in tabs every time browser starts

### ISSUE THREAD

**Issue by mcarans** [mozilla-mobile/fenix#17506]
### What is the user problem or growth opportunity you want to see solved?
I would like to be able to specify a list of urls that are opened every time Firefox for Android launches. I don't mean remembering what I last had opened. I mean a configuration setting to give a list of urls that are opened on startup (with only these urls being opened).

### How do you know that this problem exists today? Why is this important?
I have tried to find this feature [which is common on desktop browsers](https://www.groovypost.com/howto/open-same-set-of-web-pages-every-time-start-browser/) in many Android browsers but have not found any that support it which I find extraordinary - it is as if this feature is purposely being removed or left out perhaps as a requirement for being in the Play Store.

### Who will benefit from it?
Everyone who wants to get to the web pages they use most frequently quickly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9426)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813255

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
