### ISSUE TITLE
FNX-5228 ⁃ Icon to delete browsing history in Private Browsing address bar

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#1751]
Our current Private Browsing design includes a link to delete history on the tab view:

![](https://user-images.githubusercontent.com/51007/56329892-ce647b80-61d9-11e9-8dfd-cda610a62baf.png)

We’re going to introduce a way to delete history while you’re browsing privately, by including a garbage bin icon on the left side of the address bar:

https://mozilla.invisionapp.com/share/8CRLVWE2HKY

CC @sblatz @mheubusch and @AmyYLee.

**Comment by mheubusch** [comment]
@brampitoyo can you address 1788 to unblock this?

**Comment by kbrosnan** [comment]
@brampitoyo @mheubusch Invision link is dead. I need this to verify the bug.

**Comment by sblatz** [comment]
@kbrosnan try [this link](https://mozilla.invisionapp.com/d/main#/console/16853870/354838977/preview)

**Comment by kbrosnan** [comment]
@sblatz please make that a share link. I don't have an invision account.

**Comment by sblatz** [comment]
@kbrosnan sorry about that! [here you go](https://mozilla.invisionapp.com/share/85RQQLP6PKW#/354838977_-Fenix-_Private_Theme_Spec)

**Comment by brampitoyo** [comment]
@kbrosnan I just returned from PTO. For ease of use, here’s the relevant content of that InVision document as a screenshot:

<img width="360" src="https://user-images.githubusercontent.com/51007/56873394-29258f00-6a86-11e9-9cea-ce3a9f8f241f.png">
