### ISSUE TITLE
[Bug] Pages are broken on 1/19 Firefox Nightly

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#17524]
## Steps to reproduce
1. Open Firefox Nightly and open a few pages (I had wikipedia.org, and cnn.com).
2. Observe the pages.

### Expected behavior
No issues encountered. Pages are loaded correctly, the content is displayed without glitches.

### Actual behavior
Pages are broken! The user cannot read any of the content displayed. Reloading the page, doesn't fix the problem.
Cleaning the profile, doesn't fix the problem.

### Device information
* Android device: HTC 10 (Android 8, Andreno 530), and Huawei MediaPad M2	(Android 5.1.1)
* Fenix version: 1/19 Nightly
* Not reproducible on Beta 85.0.0-beta.9, nor on RC 84.1.4
 
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/5835053/logcat.txt)

<img src="https://user-images.githubusercontent.com/40694158/105018048-2f735000-5a4d-11eb-91d4-76009a817bec.png" width="300" height="550" />

![xiaomi](https://user-images.githubusercontent.com/40694158/105019312-a230fb00-5a4e-11eb-8c7d-ce234605e191.png)

**Comment by jrmuizel** [comment]
Can you get a regression window?

**Comment by softvision-miralobontiu** [comment]
I reproduced the issue on the latest build of Nightly from 1/18, but NOT on the latest version of Nightly from 1/17.

**Comment by jrmuizel** [comment]
Is it possible to get a tighter regression range using mozregression?

**Comment by softvision-miralobontiu** [comment]
Nope, I cannot run mozregression, sorry.

**Comment by jrmuizel** [comment]
What prevents you from running mozregression?

**Comment by amedyne** [comment]
Closing github issue. Will be tracking this in Bugzilla.

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1687554

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
