### ISSUE TITLE
[Bug] Don't Flip Back and Forward Buttons in RTL

### ISSUE THREAD

**Issue by Xashyar** [mozilla-mobile/fenix#17520]
[comment]: # (Please do your best to search fduplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Set an RTL in Fenix settings

### Expected behavior
The Buttons directions shouldn't flip
### Actual behavior
The Buttons directions get flipped
### Device information

![signal-۲۰۲۱-۰۱-۱۹-۰۲۴۷۱۰](https://user-images.githubusercontent.com/34171942/104970600-4f7d2200-5a01-11eb-855a-7cd303229907.jpg)

* Android device: *
* Fenix version: *

**Comment by mcarare** [comment]
The mirroring is done according to Material design rules (https://material.io/design/usability/bidirectionality.html#mirroring-layout). So, IMO, following these rules, the buttons are correctly mirrored and this behavior should not change. Tagging UX for a decision to close the ticket.

**Comment by Xashyar** [comment]
@mcarare 
You're right, this issue seems to be prevalent on older versions of Android (I tested this on Android 6.0 device) where changing localization won't mirror Buttom Nav Bar buttons, as u can see the in the screenshot above.

However I checked this on more recent versions of Android and the change is reflected in the nav bar as well.
