### ISSUE TITLE
[Bug]When selecting an autofilled address, the suggestion list gets stuck and the tab becomes half the size.

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#17521]
## Steps to reproduce
1. Type the first few letters of an address that you have visited before.
2. Press the "-->" button of the keyboard, in my case Gboard.

### Expected behavior
The suggestion list should disappear.

### Actual behavior
The suggestion list does not go away, so the actual tab content becomes half the size of the screen, as the screenshot below. The part above the tab content (like the address bar in the middle of the screen and above) does not respond to touch, and navigating to another site from there does not make the suggestion list go away. The only solution I have found is terminating FireFox and launching it again.

This randomly happens, so I am not sure what exactly is the condition for this to occur, but it keeps happening. I think that it happens once in a day or two.

![damn](https://user-images.githubusercontent.com/10900489/104997455-f3e87e00-5a6c-11eb-8996-64c164f1cc51.png)

### Device information

* Android device: Android 10.
* Fenix version: 84.1.4

**Comment by mcarare** [comment]
@HubKing What device do you use? Does disabling gesture navigation fix the issue?

**Comment by Yardanico** [comment]
I stumbled upon the same bug, Mi 9T (Android 10 based custom ROM - crDroid), Firefox Nightly and I use gesture navigation. Disabling gesture navigation makes the issue disappear.
![Screenshot_20210205-060758204](https://user-images.githubusercontent.com/21169548/106984713-2981ac80-6779-11eb-87a5-f797f4d3e33b.jpg)

**Comment by ekager** [comment]
QA - could we get this tested on a few devices?

**Comment by ebalazs-sv** [comment]
I tested this issue on Nightly 2/10 with several devices: 
- Motorola Moto G6 (Android 8);
- Google Pixel 2 (Android 9);
- Samsung Galaxy Tab S3 (Android 8);
- Nexus 5 (Android 6.0.1);
- Samsung Galaxy S10+ (Android 10).

and I did not encounter this behavior. 
I will remove the qa:needed label for now and will come back with a result if this issue is encountered.
