### ISSUE TITLE
The Recently closed tabs counter is not updated before opening the list

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#17523]
## Steps to reproduce
1. Launch Fenix;
2. Open 2 or more tabs;
3. Go to Tabs tray and close all the tabs one by one;
4. Go to History;
5. Observe the Recent closed tabs counter;
### Expected behavior
The Recent closed tabs counter is updated with the number of tabs closed at steps 3.
### Actual behavior
The Recent closed tabs counter is not updated with the number of tabs closed at steps 3. Is showing 1 tab less than the tabs closed. 
When closing all the tabs with "Close all tabs", the number of tabs closed at the same time are not added to the Recently closed tabs counter.

### Notes
The Recently closed tabs counter is updated after entering the list and leaving the list.
![20210119_114820](https://user-images.githubusercontent.com/48799384/105017599-a3612880-5a4c-11eb-8507-9c12c2bf66ec.gif)

### Device information

* Android device: Motorola Moto G6 (Android 8), Samsung Galaxy Tab S3 (Android 8), Nexus 5 (Android 6.0.1).
* Fenix version: Nightly 1/19

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9433)

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta 86.0.0-beta.3 from 2/8 with Samsung Galaxy Tab S3 (Android 8).

**Comment by AndiAJ** [comment]
**Still reproducible** on **`86.1.0 RC1`** using a OnePlus A3 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Reproducible on 93.0.0-beta.1 using a OnePlus A3 (Android 6.0.1)

**Comment by delia-pop** [comment]
Still reproducible on Beta 109.0b2 with LG G7 fit (Android 8.1.0).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812886

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
