### ISSUE TITLE
[Bug] top sites metric remain set to false

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17531]
Followup to #16832

## Prerequisites
Have the default top sites available

## Steps to reproduce
Generate the **`metrics`** ping

### Expected behavior
The following **`boolean`** probes should be properly updated:
```
"metrics": {
        "boolean": {
          ...
          "metrics.has_top_sites"
         ...
        }
```

### Actual behavior
The above mentioned probes remain set to false

## Notes
Similar to #17530, this metric is [set on startup](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L756) for Glean. This metric  should **always reflect the current state of the app**. Currently, we are only evaluating this metric (and others) on startup and this can lead to delayed/incorrect metrics.

**Comment by rocketsroger** [comment]
This is related to https://github.com/mozilla-mobile/android-components/issues/8679

**Comment by rocketsroger** [comment]
Needs to tweak this to make it more consistent.
