### ISSUE TITLE
[Bug] open tabs metric remain set to false

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17530]
Followup to #16832

## Prerequisites
Have a couple of open tabs

## Steps to reproduce
Generate the **`metrics`** ping

### Expected behavior
The following **`boolean`** probes should be properly updated:
```
"metrics": {
        "boolean": {
          ...
          "metrics.has_open_tabs"
         ...
        }
```

### Actual behavior
The above mentioned probes remain set to false

## Notes
This metric is [set on startup](https://github.com/mozilla-mobile/fenix/blob/cf61c10c39be1f7e2037a36408577e1dc57667d8/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L750) for Glean. This metric  should **always reflect the current state of the app**. Currently, we are only evaluating this metric (and others) on startup and this can lead to delayed/incorrect metrics.

**Comment by rocketsroger** [comment]
Can't reproduce but looks like there is a possible race if we try to record the metric when Fenix starts up.  The solution is either we:
1. Record the metrics before shutdown as a fallback. (Not sure if this could be out of sync as well)
2. Make sure `setStartupMetrics` is run before start up telemetry is sent.
