### ISSUE TITLE
Hook up credit cards and addresses storage layers and delegates

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#17538]
Once we have storage layers and delegates available in a-c (see https://github.com/mozilla-mobile/android-components/issues/9452) we can start adding them to `Core` and hooking them up to a `GeckoRuntime` instance.

These are slow, encrypted storage layers so it's import to follow the `Lazy<T>` init pattern here and use the `warmUp` calls. See `FenixApplication#queueInitStorageAndServices` and `lazy*Storage` wrappers in `Core.kt`.

**Comment by gabrielluong** [comment]
I think we still need to add a `warmUp` call in `FenixApplication#queueInitStorageAndServices`. This will also require AC changes to add a `warmUp` method. See the `SyncableLoginStorage`
