### ISSUE TITLE
Show a blue dot when autoplay is blocked in a site

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#17534]
We want to make users aware that a site was blocked from using autoplay, for this reason we want to show a blue dot in the toolbar. The blue dot should not show when the **Allow audio and video**  setting is is selected, otherwise **Block audio and video** or **Block audio only** should show the dot.

![image](https://user-images.githubusercontent.com/773158/105097945-5e9eb700-5a77-11eb-8dbf-ba425bc05732.png)

[Video demo](https://drive.google.com/file/d/1mweUu_xTUyCvZJxsAtlDut0N3nZSbtAx/view?usp=sharing)

Some site where you can test are www.netflix.com and www.cnn.com

**Comment by Amejia481** [comment]
This feature is already on master, it would be great if the QA team could do some testing, thanks in advance!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 1/25 Firefox Nightly build with Sony Xperia Z5 Premium (Android 7.1.1), and Google Pixel (Android 10).
When accessing cnn.com, the blue dot was displayed:

![Untitled](https://user-images.githubusercontent.com/40694158/105706665-7fa15500-5f1a-11eb-9fb8-8918236f34e0.png)
