### ISSUE TITLE
FNX-5229 ⁃ [Bug] Playing a video on Fenix doesn't pause Spotify's (or other app) playback.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1753]
## Steps to reproduce
Play something on Spotify and then play a video on YouTube using Fenix.

### Expected behavior
Spotify is paused

### Actual behavior
Spotify continues playing simultaneously with the YouTube video.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1916

**Comment by colintheshots** [comment]
Looks like we need to [request audio focus](https://developer.android.com/guide/topics/media-apps/audio-focus).

**Comment by vesta0** [comment]
This is the current behaviour in Fennec FYI.

**Comment by colintheshots** [comment]
The GeckoView team is looking at options for this. Here's the Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1545817

**Comment by Lululalu** [comment]
@vesta0 I just tried it on Fennec, and as soon as the YouTube video started playing, Spotify was paused, and vice-versa. Fenix does the opposite.

**Comment by pocmo** [comment]
AC: https://github.com/mozilla-mobile/android-components/issues/2451

**Comment by pocmo** [comment]
AC-Follow-up: https://github.com/mozilla-mobile/android-components/issues/3935

**Comment by cpeterso** [comment]
Removing the `needs:gv` label. The GV bug was closed as WONTFIX because the GV team says this is an app bug. The app should be responsible for deciding whether to acquire audio focus.

This issue has an `a-c` label. Is this issue waiting for A-C work? If not, can we also remove this issue's `waiting` label?

**Comment by pocmo** [comment]
Adding QA needed: This is enabled in Nightly builds now. Starting QA process already before enabling it for all builds.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on debug build **1.0.1934 from 22/8** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)

► Video from Google Pixel 3a (Android 9)
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/51314259/63523602-1cc8b480-c503-11e9-9540-53ba9d90fa7a.gif)
