### ISSUE TITLE
Expose credit card & addresses syncing in Account Settings UI

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#17537]
Issue capturing larger eng work: https://github.com/mozilla-mobile/android-components/issues/9452

## User Story
- As a user, I want to be able to enable and disable credit cards syncing
- As a user, I want to be able to enable and disable addresses syncing

## Dependencies
- https://github.com/mozilla-mobile/android-components/issues/9456

### Acceptance Criteria
- I can do see status of, and enable/disable credit cards syncing under Account Settings
- I can do see status of, and enable/disable addresses syncing under Account Settings

**Comment by grigoryk** [comment]
This will need to be wired up in AccountsSettingsFragment.

**Comment by gabrielluong** [comment]
The credit card sync engine should be available with the latest AC/AS update in https://github.com/mozilla-mobile/fenix/pull/19195. We should wire up the UI, but only display it with the credit card autofill pref enabled.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 5/18 with Google Pixel 4 XL (Android 11).
