### ISSUE TITLE
Bug 1687103

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#17543]
https://bugzilla.mozilla.org/show_bug.cgi?id=1687103

**Comment by pocmo** [comment]
QA team: I cannot reproduce the issue described in the bug above. Can you help trying to reproduce this?

**Comment by mcarare** [comment]
@pocmo I think this should not be reproducible anymore on Nightly. I think switching from using `SessionManager ` to `TabsUseCases ` in `TabIntentProcessor` has fixed this potential issue.

**Comment by mcarare** [comment]
Can QA also confirm this is fixed in the latest Nightly? TY!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 1/25 Firefox Nightly build. 
Tested with Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
