### ISSUE TITLE
Share button shares wrong page when web app is open

### ISSUE THREAD

**Issue by Dixet** [mozilla-mobile/fenix#17541]
When sharing a page from the Firefox bèta app while in the background a web app is open, the page of the web app will be shared instead of the visible page. 

Steps to reproduce
- Open a page that can be installed as a web app (e.g. app.starbucks.com)
- Use the menu to install this app to your home screen
- Close all tabs and the browser
- Open Firefox and browse to any page (not the web app page)
- Go to your home screen and open the web app
- Return to the browser (without closing the web app, either by using the Home button and starting your browser or by using the recent apps menu)
- The previously openened page (not the web app) should still be open
- Use the menu to share this page to any app
- The page shared will be that of the web app instead of the visible page

System used
- MIUI 12.2.2 on Android 11 (RKQ1.200826.002)
- Firefox Beta 85.0.0-beta.9 (the issue does not occur on the stable version 84.1.4)

[This video](https://www.dropbox.com/s/grvib4p5f71i95v/llo_20210119_183147.mp4?dl=0) shows the behavior with all the steps mentioned above

**Comment by mcarare** [comment]
@Dixet This should be fixed on the latest Nightly. Can you please check that?

**Comment by Dixet** [comment]
confirmed fixed on nightly 210119 17:04
