### ISSUE TITLE
FNX-56 ⁃ Add "open with external application" to the link's context menu

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1754]
### Why/User Benefit/User Problem
Sometimes users may want to open a YouTube video one the official app for a better viewing experience, and sometimes they may want open it on the browser for privacy reasons (TP, not being logged, etc). It gives control to the user. It's also privacy related. Kiwi has this feature.

### What / Requirements
And option to open links with external applications on the context menu when long pressing links.

### Acceptance Criteria (how do I know when I’m done?)
When it's possible to open, let's say, a YouTube link on a new tab, or on the app, through the context menu.

**Comment by openjck** [comment]
I think this is a pretty big omission. The old Firefox for Android app had this feature. I used it all the time, especially for sites like YouTube where the native app is vastly superior.

**Comment by NotWoods** [comment]
#5226 contains a good comparison between Fennec and Fenix.

**Comment by masi456** [comment]
I have implemented this functionality for my private version of Fenix (although the main changes are in android-components, see [here](https://github.com/masi456/android-components/commit/fb9c950859e5bd27c8b6c27a625fe6dac9d16165)).

If this has a chance of getting merged I can prepare a PR with documentation, tests, etc?

![Anmerkung 2019-12-29 182417](https://user-images.githubusercontent.com/9115235/71560302-84ba7900-2a68-11ea-8e0f-56c4a8ec0bf9.png)

**Comment by NotWoods** [comment]
A PR for this functionality is welcome :)

**Comment by lime124** [comment]
i think this is a small effort, adding needs ux for bram's triage.

**Comment by liuche** [comment]
#10124 is the PR.

**Comment by sv-sdeiac** [comment]
Hi, this issue is fixed using the latest version of Firefox Preview Nightly 4/24 #21150607.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1);
- Huawei MediaPad M2 (Android 5.1.1).
