### ISSUE TITLE
[Bug]Rename Default Top sites doesn't work properly

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#17542]
## Steps to reproduce
1. Long tap the "Google" default top site and select rename
2. Rename it E.g. "Test 1"
3. Long tap again the same default top site and select rename
4. Rename it E.g. "Test 2"
5. Long tap again the same default top site and select rename
6. Rename it E.g. "Test 3"
7. Long tap again the same default top site and select rename
8. Rename it E.g. "Test 4"

### Expected behavior
Step 8: The top site should be named "Test 4"

### Actual behavior
Step 8: The top site is named again "Google"

### Device information

* Android device: 
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

* Fenix version: 
• Nightly 210120
• 85.1.0-rc.1

### Notes
► Video
![20210120-115340](https://user-images.githubusercontent.com/51314259/105158984-40889380-5b17-11eb-84c8-6b36ba1af882.gif)

**Comment by mcarare** [comment]
Note that if you continue the renaming it shows Google - Test 1 - Test 2, etc...

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 1/25 Firefox Nightly build with Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on Beta 86.0.0-beta.5, and RC 86.1.0, with Nexus 9 - x86 emulator (Android 9).
