### ISSUE TITLE
HTML input accept argument String with just file extensions does not prompt a camera App

### ISSUE THREAD

**Issue by bumuellp** [mozilla-mobile/fenix#17547]
## Site with issue and any steps to reproduce

Two simple HTML Form examples show this error.
While an accept String with just file extensions (".pdf,.jpg", see pdf+jpg_just_extension.html) just opens the file explore App
an accept String with full MIME Types ("application/pdf,image/jpeg", see pdf+jpg_full_mime.html) prompts options for a camera or the file explorer App.
According to specifications both Strings are valid and should act the same. The full MIME Type example can be used as a workaround but allows additional file extensions for Desktop users.

[ff_filepicker_example_html.zip](https://github.com/mozilla-mobile/fenix/files/5843187/ff_filepicker_example_html.zip)

### Stepps to reproduce

1. Open the provides example pdf+jpg_just_extension.html
2. Click the Input element

### Expected behavior

HTML input form Elements with an accept value consisting just of file extensions (".pdf,.jpg") should prompt an camera App.
![andoid_ff_filepicker+camera](https://user-images.githubusercontent.com/34314864/105190379-3a55df80-5b36-11eb-9676-6a54fc9dee63.jpg)

### Actual behavior

HTML input form elements with an accept value just consisting of file extensions (".pdf,.jpg") do not prompt a camera App option and open instead the file explorer App directly.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Chrome for Android prompts a camera App option for both provided examples.

### Device information

* Android device: Samsung Galaxy A50 (SM-A505FN) on Android 10
* Fenix version: Firefox Daylight 84.1.4 (Build#2015785883)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9450)

**Comment by bumuellp** [comment]
Is there an update on this issue because it was labeled as wontfix?
I can still reproduce this issue with the given examples on my devices running Firefox Daylight 90.1.2 (Build #2015823035)

**Comment by Uaargh** [comment]
I can reproduce this bug too (also using the latest version of Firefox Daylight 90.1.2 (Build #2015823035))

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811583

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
