### ISSUE TITLE
Work on a way to limit or avoid URL spoofing via confusable glyphs from different languages

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#17550]
https://bugzilla.mozilla.org/show_bug.cgi?id=1656735

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9453)

**Comment by cpeterso** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1656735
