### ISSUE TITLE
Prompt the user before opening a website with an external application

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1755]
### Why/User Benefit/User Problem
Firefox users tend to be more privacy conscious, so redirecting them to another app without consent may not be the best behavior. I suggest the Samsung Internet's approach of asking the user before opening any website with an external application (when the corresponding app is installed).

### What / Requirements
A pop-up asking something like "do you want to open thiswebsite.com with it's external application?" (In the case thiswebsite.com has an app installed on the device)

### Acceptance Criteria (how do I know when I’m done?)
When touching a YouTube link on Google for example, the user is asked whether they want to open it on Fenix or other app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9452)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809956

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
