### ISSUE TITLE
FNX-5230 ⁃ German localization "Tracking Protection" [Bug]

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#1756]
* at the options menu, "Tracking Protection" must be translate. 

![Screenshot](https://user-images.githubusercontent.com/44252450/56318931-9836e580-6160-11e9-9e26-dfc5b38abef8.jpg)UNITO-UNDERSCORE!20190417-220709!UNITO-UNDERSCORE!Fenix!

**Comment by ekager** [comment]
As we add new features with new strings, the strings have to go through the localization process. Before they are translated, any string will default to the original English string. Our current builds are not meant to be perfect and will have some breakages, but thanks for testing them!
Feel free to follow the localization repo here: https://github.com/mozilla-l10n/android-l10n
