### ISSUE TITLE
[Bug]The page cannot be refreshed after "fission" is turned on

### ISSUE THREAD

**Issue by Lonelier** [mozilla-mobile/fenix#17562]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
In about:config, set the "fission.autostart" and "gfx.webrender.all" parameters to "true".
### Expected behavior
When fission is turned on, everything works fine
### Actual behavior
After closing the browser and reopening it, all pages do not refresh properly.
### Device information

* Android device: GM1910 Android 10
* Fenix version: Nightly 210120 #2015788491

**Comment by cadeyrn** [comment]
Fission is not yet supported on Android so it's not a bug but kind of expected that there are issues.

**Comment by Lonelier** [comment]
> 
> 
> Fission is not yet supported on Android so it's not a bug but kind of expected that there are issues.

Okay, so I'll come down to what to do? Keep waiting?

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1688013

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
