### ISSUE TITLE
Build Fenix targeting Android 11 and file issues if needed

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#17571]
After create issues to be addressed if any appear

**Comment by kbrosnan** [comment]
This is a hard requirement for shipping Gecko/Fenix v95 which is released 2021-11-02. Google Play policy states that any new releases of [existing app must update to target API 30 (Android 11) by 2021-11-01](https://developer.android.com/distribute/play-policies#APILevel30).

**Comment by Amejia481** [comment]
We can close this
