### ISSUE TITLE
FNX-5231 ⁃ Incomplete German localization "Website Permissions" [Bug]

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#1757]
* all strings for Website Permission are in English instead of German. 

![Screenshot](https://user-images.githubusercontent.com/44252450/56319070-ff549a00-6160-11e9-80f6-c6977a857e48.jpg)UNITO-UNDERSCORE!20190417-220738!UNITO-UNDERSCORE!Fenix!

**Comment by ekager** [comment]
These will be updated as we get translations
