### ISSUE TITLE
[Bug] Specific website unexpectedly re-uses tabs when passed through VIEW intent

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#17587]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Clear app data
- Start the browser by opening https://mozilla-mobile.github.io/perf-tools/mozperftest-test-page.html, i.e. `adb shell am start -t 'text/html' -d 'https://mozilla-mobile.github.io/perf-tools/mozperftest-test-page.html' -a android.intent.action.VIEW org.mozilla.fenix/org.mozilla.fenix.IntentReceiverActivity`
- Enter the intent query again

### Expected behavior
2 tabs, each with the same website are loaded.

### Actual behavior
Only 1 tab is there such that the tab is re-used.

This does not happen if you change the URL you are opening to https://example.com. For some reason, we are handling https://mozilla-mobile.github.io/perf-tools/mozperftest-test-page.html differently. It seems unlikely but it's possible the browser is smart enough to know this page has static content so that it probably doesn't need to reload the page.

### Device information

* Android device: P2
* Fenix version: local nightly build, probably 69f3bc7a0

**Comment by VitalyVPinchuk** [comment]
Hello!
I'm new here :)
I've looked into the matter and found the following.

`SelectOrAddUseCase` class decides whether select existing tab or create new one by comparing opening URL against sessions URLs with this code:
```
            val existingSession = sessionManager.sessions.find { it.url == url }
            if (existingSession != null) {
                sessionManager.select(existingSession)
            } else {
                val session = Session(url, private, source)
                sessionManager.add(session, selected = true)
                store.dispatch(EngineAction.LoadUrlAction(
                    session.id,
                    url,
                    flags
                ))
            }

```
When loading `https://www.examle.com` its URL will look something like this 
`http://www6.examle.com/?template=simple2c&tdfs=1&s_token=1612008110.0035447821&uuid=1612008110.0035447821&term=Dedicated%20Server%20Moscow&term=Dedicated%20Server%20North%20America&term=Dedicated%20Server%20Asia&term=Dedicated%20Server%20Europe&backfill=0` so new tab gets created
while `https://mozilla-mobile.github.io/perf-tools/mozperftest-test-page.html` remains constant and gets used.

**Comment by mcomella** [comment]
Interesting – good find! The next question is: what is the expected behavior? I'm not sure consistently re-using a tab, without reloading the page, is it. Perhaps we should see what Chrome does.

I've also noticed the back behavior varies between the two too:
- Open perftest website: back will go to homescreen and back again will close app
- Open example.com: back will close the app in one click

**Comment by mcomella** [comment]
> I've also noticed the back behavior varies between the two too:

Actually, I'm not sure this holds up in related activities but I don't have time to test it right now.
