### ISSUE TITLE
Show a functional scroll bar while scrolling

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1758]
### Why/User Benefit/User Problem
It's hassle to go to the top or bottom, or middle, of pages that are long, full of content. It takes too much times swiping your finger up and down until you reach the part of the page that you want. A scroll bar fixes this, allowing way faster navigation of long pages. This feature was add a long time to Samsung Internet, and more recently to Opera Mobile.

### What / Requirements
A scroll bar that allows for quick navigation of long pages, and gets invisible once it's not in use anymore.

### Acceptance Criteria (how do I know when I’m done?)
It's possible to browser long pages faster thanks to a scroll bar that shows up when the user scrolls.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9467)

**Comment by masayuki-nakano** [comment]
I think that this should be fixed in Gecko with making thumb of scroll bar draggable.

**Comment by kbrosnan** [comment]
bz-1480906

**Comment by Snowden-rgb** [comment]
+1

**Comment by idanej** [comment]
I made an account to request this feature, but I see it's already been suggested. +1! I've recently switched from Opera to Firefox but the lack of a quick scrolling option makes me want to go back.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1346279

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809957

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
