### ISSUE TITLE
Installing an .xpi file is not possible via File Manager.

### ISSUE THREAD

**Issue by ungubajue90k** [mozilla-mobile/fenix#17591]
## Steps to reproduce
1. download .xpi file e.g the latest release version of uBlock Origin
https://github.com/gorhill/uBlock/releases/tag/1.32.4
https://addons.mozilla.org/firefox/downloads/file/3701081/ublock_origin-1.32.4-an+fx.xpi

2. open Default File Manager on Android

3. open the .xpi file

4. there is no possibility to select Firefox.

### Expected behavior
Firefox can install the .xpi file on my Android device via File Manager.

### Actual behavior
Install .xpi file does not work.

### Device information

* Android device: Samsung Galaxy Note 20 (Android 11, OneUI 3)
* Fenix version: 85.1.0 (Build #2015788691)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9475)

**Comment by TheVaccin3** [comment]
is there an update for this? I really want this feature to be added.

**Comment by vehosah** [comment]
Hello is there any actual update?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814123

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
