### ISSUE TITLE
Investigate and analyze memory usage in Fenix

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#17590]
This is a bit generic for now but we want to take another close look at memory usage in Fenix:

- Which parts of the system consume the most memory?
- What we can we do to optimize?
- Are we handling low memory conditions most effectively esp. considering multi-e10s?
- I think we fixed all known leaks, but there's at least one in GV that still needs to be addressed. How does this affect us when switching tabs? (https://bugzilla.mozilla.org/show_bug.cgi?id=1678425)

All feedback and comments welcome.

**Comment by cadeyrn** [comment]
@csadilek 

> I think we fixed all known leaks

I have a new one for you. ;-) #17597

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/18336 and https://github.com/mozilla-mobile/fenix/issues/18337 to add quick telemetry in advance of working on this issue.
