### ISSUE TITLE
every addons "close other tabs" is not working 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#17592]
long ago I suggested the developers to add close other tabs to long press tab switcher icon and as expected my request was ignored.(Many browsers like yandex and Samsung have that useful close other tabs function) but maybe it's too much to ask for fenix!?!? 
so I tried several addons (wich worked perfectly in fennec) to get that damn function and none of them worded.
please fix it tabs management is an awful mess in fenix since IT'S NOT POSSIBLE TO OPEN TOP SITES IN CURRENT Tab as many requested.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9476)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811584

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
