### ISSUE TITLE
Firefox on youtube android

### ISSUE THREAD

**Issue by honwen123** [mozilla-mobile/fenix#17602]
Youtube cannot crop video back to original size and cannot see subtitiles in fullscren mode

Shiuld be able to adjust video size and see subtitiles.
Toggling tracking protection does not work.
There is no problem  in chrome and other non mozills browsers other than fitefox lite.

### Device information

* Android device: S9+
* Fenix version: 84.1.4
Please fix this soon.

**Comment by kbrosnan** [comment]
This should be fixed on v85

**Comment by honwen123** [comment]
Ok thanks

**Comment by honwen123** [comment]
it is already version 85 but it is not fixed
