### ISSUE TITLE
Missing Android TV Version

### ISSUE THREAD

**Issue by Blackdead** [mozilla-mobile/fenix#17609]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently there is no version of Firefox available for Android TV or at least for the NVIDIA Shield TV (2017 model) (Android 9.0 (Pie) powered by Android TV™). It would be nice to have one since Android TV versions like the NVIDIA Shield TV support mouse and keyboard inputs.

### How do you know that this problem exists today? Why is this important?
Currently Firefox can't be installed via the Play Store on Android TV devices or at least on the NVIDIA Shield TV (2017). Firstly, you won't find it in the Play Store of the Android TV and secondly in a browser on a PC the Play Store says, "the device is not compatible".

### Who will benefit from it?
Users which like to surf the web and especially those who like to do that with the variety of the Firefox Plugins on a TV or like to watch shows on websites which don’t have an app for Android TV. This may would help to protect the privacy of people as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9488)

**Comment by anotherus3r** [comment]
There is a version of Firefox for Fire TV (https://github.com/mozilla-mobile/firefox-tv) that can be sideloaded onto Android TV, and which works completely fine. Maybe that one can be release on the Play Store, too?

**Comment by rbrito** [comment]
I have a what seems to be "an old" TV by today standards that runs Android 5.0 and its firmware is really bad. I would really love to have a browser (any browser!) that would run on my TV, since none is present when I browse the Play Store in my TV and, of course, one that is focused on privacy would be terrific!

**Comment by komawoyo** [comment]
the version at https://github.com/mozilla-mobile/firefox-tv does not support extensions and seems to run sluggish on my chromecast with android tv

**Comment by abodea** [comment]
Thank you for this report.
Currently, Firefox for Android is compatible with Android 5.0 or above devices. ARMV6 devices and Android versions older than 5.0 are no longer supported.

Other mobile devices
Firefox is NOT available for Windows Phone, Windows RT, Bada, Symbian, Blackberry OS, webOS or other operating systems for mobile.

> There is a version of Firefox for Fire TV (https://github.com/mozilla-mobile/firefox-tv) that can be sideloaded onto Android TV, and which works completely fine. Maybe that one can be release on the Play Store, too?

@anotherus3r thanks for the input, but please note that Firefox has ended support for Amazon Fire TV. This app may continue to work, but it won't receive security or other updates effectively on April 30, 2021. And the FFTV was webview and Fenix is using Geckoview.

I will set this issue as a feature request.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813254

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
