### ISSUE TITLE
[Bug] DNS lookups fail

### ISSUE THREAD

**Issue by romeoneverdies** [mozilla-mobile/fenix#17606]
Accessing local addresses trough urls like these is no longer working properly (and as per standard)

http://10.0.0.x:port  (where port is not 80)
https://10.0.0.x:port (where  port is not 443) 
http(s)://hostname:port (hostname lookup is not performed only goes to search)

the first two should open regardless if its http or https and regardless of port.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9485)

**Comment by lobontiumira** [comment]
I confirm that trying to access either of the two addresses with Firefox, just displayed an "Invalid address" page.
Tested on the latest Nightly build from 3/30, using a Samsung Galaxy Note 8 (Android 9), and Google Pixel (Android 10).

**Comment by ntkoopman** [comment]
Any update on this? Access by IP is working fine for me, but local hostnames are not resolving.
