### ISSUE TITLE
Update signature algorithm from SHA1withRSA to SHA512withRSA

### ISSUE THREAD

**Issue by ungubajue90k** [mozilla-mobile/fenix#17604]
Hello developers,

I am using the latest release version.
https://github.com/mozilla-mobile/fenix/releases/tag/v85.1.0

But the .apk file from you has a signature integrated with the algorithm SHA1withRSA.

Please update to SHA512withRSA.

**Comment by lobontiumira** [comment]
@ungubajue90k is this still reproducible?
Thank you!
