### ISSUE TITLE
FNX-5233 ⁃ [Bug] Regression: Fenix fails to start, crashes immediately

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1761]
## Steps to reproduce
1. Launch Fenix

### Expected behavior
Fenix starts.

### Actual behavior
Fenix crashes.

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

See log files attached. 

[logs-2019-04-18-00-14-30.zip](https://github.com/mozilla-mobile/fenix/files/3092819/logs-2019-04-18-00-14-30.zip)

**Comment by k0ur0x** [comment]
Fixed #1752

**Comment by yoasif** [comment]
This works in the latest build.
