### ISSUE TITLE
[Bug] Addressbar covers content of website overlays

### ISSUE THREAD

**Issue by alexanderaeppli** [mozilla-mobile/fenix#17618]
## Steps to reproduce
Scroll inside an div (overflow: scroll or automatic) while not scrolling the body (body set to overflow: hidden) 
E.g. a full screen menu or overlay

### Expected behavior
The address bar hides itself to reveal the content under it.

### Actual behavior
The address bar stays visible, possibly covering content.

### Device information

* Android device: Huawei P9
* Fenix version: 84.1.4, Nightly 210124 17:01

**Comment by anotherus3r** [comment]
Same issue as in #13797 maybe?

**Comment by alexanderaeppli** [comment]
@anotherus3r Yes, seems like its the same issue.

**Comment by Delphine** [comment]
Closing since this is a dupe
