### ISSUE TITLE
[Bug] Latest version (1.48.0) of Bitwarden fails to install

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17629]
## Steps to reproduce
1. Install a fresh copy of Fenix (release or beta)
2. Try to install Bitwarden add-on

### Expected behavior
Add-on is installed 

### Actual behavior
Message on screen stating add-on failed to install. 

## Notes
* > the problem is that BitWarden requests nativeMessaging as permission now (it didn't use to) and we block it. geckoViewAddons is the only other permission we block for external add-ons.

**Comment by csadilek** [comment]
This was fixed in https://github.com/bitwarden/browser/pull/1570. We also have https://bugzilla.mozilla.org/show_bug.cgi?id=1630415 as a follow-up to allow `nativeMessaging` as optional permission.
