### ISSUE TITLE
[Bug][l10n] "OK" option from add to collection dialog is not translated in  Kazakh language

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#17621]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Change device language to Kazakh.
2. Open some pages.
3. Select tabs to add to a new collection or to an existing one. 
4. Pay attention to the dialog.

### Expected behavior
The options are displayed in  Kazakh language. 

### Actual behavior
"OK" option is not translated. Should be "Жарайды ма".

### Device information
* Android device: Samsung Note 10(Android 10).
* Fenix version: Nightly 1/25

**Comment by Delphine** [comment]
Looking at "kk" localizations in other products, I often see "OK" translated as "OK" in Kazakh. 
There are variations to that though, so I will reach out to localizers to see if there is a reason this term isn't used consistently. Will report back here!

**Comment by crayxt** [comment]
Hello,

We are using OK but written in Cyrillic letters as "ОК". We don't use "Жарайды" or "Жақсы" with exception of "Okay, got it" as "Жақсы, түсіндім". I have updated the single occurence of "Жарайды" I found on Pontoon to "ОК".
Current Firefox on Android shows "Жарайды" on Collection creation dialog as specified above, I hope it will change to "ОК" on next release.

Thanks,

**Comment by sflorean** [comment]
@crayxt @Delphine thank you for clarification! Closing this since it is working as expected, and we will take a look at the Collection creation dialog, on next release.
