### ISSUE TITLE
[SVG] SVG images in a site make scrolling choppy and slow

### ISSUE THREAD

**Issue by cryptomilk** [mozilla-mobile/fenix#17626]
## Site with issue and any steps to reproduce
https://test.ig-klettern.org/

Just scroll down and you will see that scrolling is laggy. As soon as no SVGs are displayed anymore it will be smooth again.

### Expected behavior
Even with SVG images the scrolling should be smooth

### Actual behavior
Scrolling is slow and laggy if SVG images are in the displayed area.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No

### Can you reproduce in Chrome (or other non-Mozilla browser)?
It works just fine with Jelly (LineageOS, Android) Browser which is chromium based. -->

### Device information

* Android device: Samsung S10e
* Fenix version: 84.1.4

**Comment by hakkikaancaliskan** [comment]
Here is the log for this: https://share.firefox.dev/3sUriur
As far as i can see `webrender::renderer::Renderer::update_texture_cache` causes this problem.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1688765

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
