### ISSUE TITLE
[Bug] Changing the theme or the tollbar position in private onboarding jumps the focus to the top

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#17633]
## Steps to reproduce
1. Make sure to have a fresh profile.
2. Go to private browsing.
3. On the onboarding tour, from the private browsing, select a different theme, or a different position of the toolbar.

### Expected behavior
The changes are made without issues, the onboarding remains in the same position.

### Actual behavior
The private onboarding jumps to the top of the page.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Fenix version: 1/26 Nightly, RC 85.1.0
* Not reproducible on the 85.0.0-beta.9 build
* Not reproducible on the normal browsing onboarding

https://user-images.githubusercontent.com/40694158/105814595-50422500-5fba-11eb-9467-21fd1bde7f4f.mp4

**Comment by softvision-miralobontiu** [comment]
I was able to reproduce this issue on the RC 85.1.2 build with Samsung Galaxy Tab A6 (Android 5.1.1).
