### ISSUE TITLE
Ability to edit Top Site URLs.

### ISSUE THREAD

**Issue by AnxiousSun** [mozilla-mobile/fenix#17636]
**Why/User Benefit/User Problem**
Many websites redirect their top-level domain to a sub-domain or sub-page when you first visit the website. For example, when you visit imgur (imgur.com), you are redirected to a secondary mobile URL (m.imgur.com/). If you pin this website it will add an incorrect top-level URL to your Top Sites. There is no way to edit the pinned URL to correctly reflect the correct top-level URL. 

**What/Requirements**
Long press on top site currently brings up a dialog with "Open in private tab", "Remove", and "Rename". Add "Edit" which brings up a dialog box with current URL to edit the stored link.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9507)

**Comment by ale82to** [comment]
how about removing that disgusting 8 top sites limit per page?

**Comment by anotherus3r** [comment]
Yes, I'd like this, too. The rename function could be also merged into this edit function, i.e. tapping edit would present you with a dialog box where you can edit both the name and URL.

**Comment by pepve** [comment]
I would like this too. A website I use frequently has a redirect that forwards the browser to a dynamic login page. If I try to go to the login page without using the redirect it throws an error. There is no other way to get to the login page. I would like to have the redirect as a pinned site. :-)

I made a mockup, how about this?

![mockup](https://user-images.githubusercontent.com/823248/106368199-33a24600-6348-11eb-9c83-81325b07f19c.png)

**Comment by ohhai** [comment]
Not sure what's happening but this issue should not be closed, I think

**Comment by pepve** [comment]
Indeed, it would be very nice actually if someone looked at my PR, I'm still here to support it.
