### ISSUE TITLE
[Bug] Cannot open a site from custom tab via three-dot menu in Firefox Nightly

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#17635]
## Steps to reproduce
1. Make Firefox Nightly you default browser.
2. Go to gmail and open a link in custom tab.
3. From the three-dot menu, select to open the custom tab in Firefox Nightly.

### Expected behavior
The page is opened in Firefox Nightly without issues. The tabs number increases by one.

### Actual behavior
The site doesn't open in Firefox Nightly. No new tab is opened in Firefox Nightly.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Fenix version: 1/26 Nightly 
* Not Reproducible on Beta 85.0.0-beta.9, RC 85.1.0

https://user-images.githubusercontent.com/40694158/105843918-07519700-5fe1-11eb-93d4-4ac66e5970e2.mp4

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 1/29 Firefox Nightly build with Samsung Galaxy Note 8 (Android 9), and Google Pixel (Android 10).

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on RC 86.1.0-rc.1 and Beta 86.0.0-beta.5.

### Devices used:
- Huawei MediaPad M3 (Android 7.0)
- OnePlus 6T (Android 9)
