### ISSUE TITLE
loadUrl isn't called for ~1s after IntentReceiverActivity in WARM VIEW

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#17645]
## Steps to reproduce
- View this WARM VIEW profile on the Moto G5 (filtered to loadUrl): https://share.firefox.dev/2Yi0Hti
- Note that `loadUrl` is called much later than `IntentReceiverActivity`. In this screenshot, IntentReceiverActivity is on the left and loadUrl is on the right:

![image](https://user-images.githubusercontent.com/759372/105911559-27805680-5fdf-11eb-8bca-7141decab7da.png)

### Expected behavior
As I understand it, when IntentReceiverActivity is called, we have the URL and can immediately call loadUrl, starting the loading process before we even start loading the UI in HomeActivity.

### Actual behavior
loadUrl is deferred until later. I think we create the gecko session in IntentReceiverActivity but because we're suspending on the main thread, the `loadUrl` call gets delayed until later.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 210125-ish

**Comment by mcomella** [comment]
I'm adding profiler markers in https://github.com/mozilla-mobile/fenix/issues/17816 that make it much easier to indicate this region, from `Activity.onCreate` (IntentReceiverActivity) to GeckoSession.load: https://share.firefox.dev/3jkp1UW

**Comment by mcomella** [comment]
I followed the call stack through the dispatcher:
- TabsUseCases.kt: SelectOrAddUseCase.invoke (adding the first tab, which is a profiler marker) dispatches LoadUrlAction
- EngineDelegateMiddlware.loadUrl dispatches CreateEngineSessionAction
- CreateEngineSessionMiddleware.createEngineSession launches
- CreateEngineSessionMiddleware.createEngineSession dispatches LinkEngineSessionAction
- LinkingMiddleware.performLoadOnMainThread launches
- LinkingMiddleware.performLoadOnMainThread calls engineSession.loadUrl

Since the dispatches do not happen synchronously, we're delayed from calling `loadUrl` until some other stuff happens on the main thread first.

**Comment by mcomella** [comment]
I tried the naive thing and wrapped the first `dispatch(...LoadUrlAction)` in `runBlocking`:
```
+                runBlocking {
+                    store.dispatch(EngineAction.LoadUrlAction(
+                        session.id,
+                        url,
+                        flags
+                    )).join()
```

But it didn't work: the `CreateEngineSessionMiddleware` ran between `IntentReceiverActivity.onCreate` and `HomeActivity.onCreate`, and `LinkingMiddleware` ran after `HomeActivity.onCreate`, as might be expected from when the coroutines are launched.

**Comment by mcomella** [comment]
> I tried the naive thing and wrapped the first `dispatch(...LoadUrlAction)` in `runBlocking`:

I expanded it to block several levels down and now it hangs, perhaps because we try to dispatch to the same thread or synchronize on the same store. Here's my diff: https://github.com/mcomella/android-components/commit/eb05afe2f1dba864221a3a4dbcba6cc3b4a5478c

Unfortunately, I think this implies we'll need to do a non-trivial refactor in order to make the change to call loadUrl as soon as we possibly can. As for what that looks like, I have two thoughts:
- it seems we're using coroutine dispatchers to take and run the actions sent to our queue serially: this could instead be implemented with a queue that yields control only when the queue is empty rather then suspending at arbitrary points.
- maybe we can have a unique code path for WARM VIEW start up that goes to call loadUrl as soon as possible

**Comment by mcomella** [comment]
@MarcLeclair Please take a stab at implementing what csadilek suggested.

**Comment by MarcLeclair** [comment]
PR: https://github.com/mozilla-mobile/android-components/pull/9825

**Comment by mcomella** [comment]
Triage: add to triage just to update csadilek on status. csadilek recommends filing against GV which we think we should do once we have profiler markers so we can show them what's happening and make it more actionable for them https://github.com/mozilla-mobile/perf-frontend-issues/issues/191. Let's not land the change until we fix this issue.

**Comment by mcomella** [comment]
Triage: once we add the profiler markers, we want to work with acreskey or other folks knowledgeable about Gecko on what could be preventing the loadUrl fix from working. While looking at profiles in the profiler office hours, we noticed there was ~950ms delay in scheduling the loadUrl runnable – we should try to find the root cause of that (which may be related to GeckoView start up timing).

**Comment by MarcLeclair** [comment]
After talking it, we've noticed that `loadUrl` being called earlier will have little impact on loading the web page faster since we would need to make the content process happen faster which is a whole other ordeal that is way beyond the scope of this ticket (Note: we've been told this was talked about a while ago, maybe we could follow up on that?). However, as of now, having the `loadUrl` earlier seems like its ROI would be too small to continue focusing on that.
