### ISSUE TITLE
The speculative gecko session does not appear to be created prior to the WARM VIEW scenario

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla-mobile/fenix#17646]
## Steps to reproduce
Using the WARM VIEW profile from https://github.com/mozilla-mobile/fenix/issues/17645, we see that geckoview is initialized on demand (it results in the import of numbers JS modules).

https://share.firefox.dev/2MsEq9r

The idea is to ensure that we have a speculatively created Geckosession ready for this scenario.

This is done in other user flows in Fenix, I believe opening the URL bar is one.

This has the potential to reduce WARM VIEW times.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9511)

**Comment by mcomella** [comment]
> The idea is to ensure that we have a speculatively created Geckosession ready for this scenario.

We might be able to:
- Create a session as soon as `IntentReceiverActivity` is started
- Have an idle, empty session around for when the user returns to the app (is this reasonable? if it was, maybe we'd have done this for the URL bar instead?)

**Comment by mcomella** [comment]
Triage: in my notes, it says it takes 11ms to create the session in profiles. It may also have other benefits beyond that one call (e.g. maybe timeToNavStart is reduced because we can connect immediately and don't need to init more data structures)

**Comment by mcomella** [comment]
Triage: we should talk to acreskeyMoz or other members of the perf team to understand what the potential impact of this would be.

**Comment by mcomella** [comment]
Triage: csadilek mentioned the code says we should be doing this so if it's not happening it's likely a bug or a measurement technique problem.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807316

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
