### ISSUE TITLE
[Telemetry] Web extensions

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17644]
Follow up to https://github.com/mozilla-mobile/fenix/issues/6174
Related to #16832

## Current implementation
We are currently evaluating metrics on startup and receiving a list of enabled addons and installed addons. These are being used to evaluate these metrics:
* `addons.has_enabled_addon`
* `addons.has_installed_addons`

These metrics do not answer all of the product questions that were originally proposed (see #6174).

## Description & Product Manager / Data Scientist User Story
* Does product still care about the originally proposed questions? Should we re-evaluate these and implement new probes?
* Do we still care about the list of addons for installed & enabled?

## What questions will you answer with this data?
TBD based on above questions.

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by Mugurell** [comment]
Looking at the requirements and then [what Andi verified](https://github.com/mozilla-mobile/fenix/issues/6174#issuecomment-609791654) it looks like we don't track when:
> User taps on an installed add-on in the toolbar menu to view/modify its setting

Waiting for @vesta0 @amedyne to re-evaluate what related telemetry should we have.

**Comment by vesta0** [comment]
We still care about the list of addons for installed & enabled.

**Comment by rocketsroger** [comment]
> We still care about the list of addons for installed & enabled.

Looking through the current implementation we do send the list of installed and the list of enabled addons.  However, it's not on the startup metrics.  Only when user install / enable an addon.  Do we want to change it so we send the list of installed / enabled addons at startup metrics?

**Comment by rocketsroger** [comment]
From more testing I can see that add-on telemetry is not consistent.  Reworking it so when metric ping is sent add-on telemetry values will always be the updated value.

**Comment by rocketsroger** [comment]
All needed changes have been merged.  Please verify.  Thanks!

**Comment by lobontiumira** [comment]
Verified on the latest Nightly build from 3/30 with Google Pixel (Android 10):
* ping: 94f8e316-1548-4bea-ab7d-5de892768fb7
* opening an add-on settings generates:
 ```
{
          "category": "addons",
          "extra": {
            "addon_id": "firefox@ghostery.com"
          },
          "name": "open_addon_setting",
          "timestamp": 5596
        }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2103300001)
[Logcat](https://github.com/mozilla-mobile/fenix/files/6227491/logcat.txt)
