### ISSUE TITLE
[Bug] collection item caching visited history

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17658]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
**Open the site** https://www-xda--developers-com.cdn.ampproject.org/v/s/www.xda-developers.com/firefox-proton-redesign-browser-ui/amp/?amp_js_v=a6&amp_gsa=1&usqp=mq331AQFKAGwASA%3D#aoh=16116288215095&csi=0&amp_tf=From%20%251%24s&ampshare=https%3A%2F%2Fwww.xda-developers.com%2Ffirefox-proton-redesign-browser-ui%2F

Click techdows link as per below screenshot which will open target site. Once the site is opened add to collection. 
Close all tabs and browser 
Open the techdows site from collection 
Click back it will go back to xdaforum site

### Expected behavior
Should take to home screen. It is somewhat caching the history of previous page

### Actual behavior
It is caching the history of previous page 

### Device information

* Android device: ? Rog3
* Fenix version: ? Latest
 
![Screenshot_20210127-172032032 (1)](https://user-images.githubusercontent.com/58127841/105987545-6c31ed80-60c4-11eb-9d0c-9f595fb70c13.jpg)

**Comment by mcarare** [comment]
@sheikh-azharuddin It will only take you to the home screen if you would have opened the link in a new tab.
Every tab that is saved to a collection is saved with their entire session, meaning its history as well. And it has been implemented this way from the start.  The only recent changes were that the tab is "refreshed" after loading,  to provide up-to-date content.

**Comment by ale82to** [comment]
I noticed this too for a long time one reason more not to use that stupid collections

**Comment by mcarare** [comment]
Closing this as it is the expected behavior.
