### ISSUE TITLE
[Bug] youtube.com - Framerate drop is quite high

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#17654]
Initially reported on 

https://bugzilla.mozilla.org/show_bug.cgi?id=1688783
https://github.com/webcompat/web-bugs/issues/64541

1. With Firefox Android Nightly 87 on Android 11
2. Go to https://m.youtube.com/watch?v=QvkE9n9eiIM
3. Set fullscreen
4. Activate the Top right gear
5. Select stats for nerds
6. Check the second line, the value for frames
    
Expected:
minimal dropped frame rate

Actual
A lot of frames are being dropped. (around 17% on my tests)

The initial reporter on webcompat created a profile.
https://share.firefox.dev/3qESWtc

Chrome doesn't show that many frames dropped.

**Comment by hakkikaancaliskan** [comment]
I've tested on TC nightly builds and problem started with 11/19 nightly build.

today	->	drop
12/1	->	drop
11/20	->	drop
11/19	->	drop
11/18	->	okey
11/15	->	okey
11/1	->	okey
10/1	->	okey

**Comment by hakkikaancaliskan** [comment]
@rocketsroger do you think is there a relation with this bug and MediaSession API or this is a GV bug?

**Comment by hakkikaancaliskan** [comment]
@karlcow you got the info 😊

**Comment by hakkikaancaliskan** [comment]
I've found the commit range in mozregression, padenot found the issue in geckoview matrix and he's working on fix.

**Comment by softvision-miralobontiu** [comment]
We've verified on the latest RC build 85.1.1 and there were **no frames dropped**. We've tested on the following devices:
* Google Pixel (Android 11),
* Samsung Galaxy Note 10 (Android 10),
* Sony Xperia Z5 Premium (Android 7.1.1), and
* Huawei MediaPad M3 (Android 7.0)

**Comment by hakkikaancaliskan** [comment]
@softvision-miralobontiu this issue reproduced by geckoview dev on his Android 11 and Android 9 devices, and he fixed issue already in bugzilla.

**Comment by softvision-miralobontiu** [comment]
Then this can be closed?

**Comment by hakkikaancaliskan** [comment]
> Then this can be closed?

Idk if fixed on nightly too but i think we should wait beta to be fixed.

**Comment by hakkikaancaliskan** [comment]
@softvision-miralobontiu i take a look to bugzilla and temporary fix landed for release, beta and nightly waiting for real fix.

Temporary fix: add "media.cubeb.backend" pref "opensl" as string type in about:config
