### ISSUE TITLE
[Bug] Most visited top sites shown even when it's turned off

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#17655]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Have most visited top sites turned off
Upgrade from 85-beta9 to 86-beta1

### Expected behavior
It respects to setting and remains off
### Actual behavior
It's shown even when setting turned off
### Device information

* Android device: Xperia XZ1 Android 11
* Fenix version: 86-beta1

**Comment by ThracianKnight1907** [comment]
I also have this issue. It looks like that button does nothing in the current beta

**Comment by hakkikaancaliskan** [comment]
There is no problem on nightly, maybe you guys missed a commit to include?

**Comment by leadweedy** [comment]
This bug is also affecting nightly since today's build: Nightly 210127 17:01 (Build #2015789835)

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the issue on the 1/29 Nightly build, but I **am reproducing the issue on the 86.0.0-beta.1** build with Sony Xperia Z5 Premium (Android 7.1.1).
Removing the qa:needed label for now.

**Comment by kbrosnan** [comment]
@amedyne Has this been uplifted to Beta? It would be a significant regression to ship this.

**Comment by amedyne** [comment]
Fix uplifted to Beta.
