### ISSUE TITLE
FNX-5235 ⁃ [Bug] Save session button is missing

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1766]
## Steps to reproduce
1. Open a tab.
1. Go to tabs list in current session.Observe the save session button.
1. Check the overflow menu of Current session.
    1. Expected behavior
save session button is there.
    1. Actual behavior
save session button missing from both places.
    1. Device information

* Android device: Pixel, Nexus 5.
* Fenix version: 4/18

**Comment by cadeyrn** [comment]
Sessions were removed: #1747.

**Comment by sv-ohorvath** [comment]
Ah, true. I thought that they were removed only from the library menu. Thanks!
