### ISSUE TITLE
Set Firefox android as default pdf viewer 

### ISSUE THREAD

**Issue by Ansarmughal99** [mozilla-mobile/fenix#17666]
[comment]: #  plz set firefox for android as default pdf viewer just like in desktop

### Everyone will be benefited

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9518)

**Comment by cadeyrn** [comment]
Firefox can't be set as default pdf viewer because Firefox can't display PDF files - that's #4337.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813251

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
