### ISSUE TITLE
[Bug] With immersive mode AND bottom toolbar enabled, whenever the user types anything in the toolbar, the search and site suggestions are scrolled up a bit

### ISSUE THREAD

**Issue by hungbhv** [mozilla-mobile/fenix#17677]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Enable immersive mode for Firefox
Enable bottom toolbar
Tap the toolbar to bring up the keyboard, type in anything
### Expected behavior
The search suggestions and site suggestions should be displayed normally.
### Actual behavior
The search suggestions and site suggestions are automatically pushed up by an amount seemingly equal to the height of the keyboard. The user has to scroll the suggestions down to access the topmost suggestions.
### Device information

* Device vendor / model and Android version: Xiaomi Mi 9T, MIUI 12 and Android 10
* Firefox for Android version: 
 84.1.4 (Build #2015785883)
AC: 67.0.17, 2095f1a5d
GV: 84.0.3-20210106212839
AS: 67.0.0

![YKPA2Cp](https://user-images.githubusercontent.com/78145800/106125586-eb8bf380-618e-11eb-80f7-c57188b7eaf5.jpg)
![H6zGaqj](https://user-images.githubusercontent.com/78145800/106125595-ed55b700-618e-11eb-95ca-bf95714c88a2.jpg)

**Comment by Mugurell** [comment]
Immersive mode is not officially supported other than when viewing fullscreen videos.
It can be forced from exterior but this leads to a bunch of issues.

I see there's also a request to consider hiding Android's status bar - https://github.com/mozilla-mobile/fenix/issues/1984
Let's close this in favor of that feature request where the opportunity of this can be discussed.
