### ISSUE TITLE
Video thumbnail not shown in notification on youtube

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#17670]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open a youtube video, example: https://m.youtube.com/watch?v=KV8NOtIffl8&list=PLgUi8_YoxkDo6M5XufsScmwuPob-bSSvW&index=6&t=182s
Observe there is no thumbnail image on notification

### Expected behavior
Video thumbnail shown in notification
### Actual behavior
Empty
### Device information

* Android device: Xperia XZ1, Android 11
* Fenix version: 
* 86.0.0-beta.1 (Build #2015789707)
AC: 72.0.1, d61ba1282
GV: 86.0-20210126185730
AS: 67.2.0
 
![Screenshot_20210127-235426_Firefox_Beta](https://user-images.githubusercontent.com/17825767/106053008-555abd80-60fb-11eb-8597-6cea5351cd71.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9522)

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Nightly 2/16 with Nexus 5 (Android 6.0.1).

**Comment by hakkikaancaliskan** [comment]
Issue still there

**Comment by bbhtt** [comment]
Issue is still present on today's nightly...

**Comment by bbhtt** [comment]
Still present

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809282

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
