### ISSUE TITLE
[Bug] Custom tab not working on some devices

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1767]
## Steps to reproduce
1. Set Fenix as your default browser. 
1. Install slack and enter your workspace URL.
1. Select "Sign in with Auto0".

### Expected behavior
A custom tab opens.

### Actual behavior
Fenix is opened.

### Device information
* Android device: 
  * Samsung Galaxy S8 (Android 9)
  * Samsung Galaxy Note8 (Android 9)
* Fenix version: 1.0.1916 (#11080612)
* This issue was not reproducible on the following devices:
  * Google Pixel (Android 9)
  * Nexus 5 (Android 6.0.1)
  * Huawei Honor 8 (Android 7.0)
* After logging in on the Samsung devices a custom tab is opened missing the extra menu items.

**Comment by sblatz** [comment]
I'm unable to reproduce this on my Galaxy S9 on Android 9. 

Is this only happening for that "Sign in with Auth0" page? Or also in other apps/once signed into Slack.

**Comment by bsurd** [comment]
It's happening for that "Sign in with Auth0". All other devices are opening a custom tab for that part as well.

**Comment by sblatz** [comment]
@bsurd to clarify: if you open a custom tab from Yelp, for example, is it opening as expected on the Samsung devices?

**Comment by bsurd** [comment]
Yes, it's opening as expected in Yelp. It seems to only affect that part on the Samsung devices.

**Comment by sblatz** [comment]
@bsurd are you still running into this issue?

I'm going to close as we haven't had other reports of custom tabs not working, but please re-open if you're still seeing it!

**Comment by softvision-miralobontiu** [comment]
I will reopen this issue as I am still able to reproduce it with the latest build 7/3 with Samsung Galaxy S8 (Android 9).

**Comment by vesta0** [comment]
@softvision-miralobontiu please test again and let us know if this is still reproducible.

**Comment by sflorean** [comment]
@vesta0 I am able to reproduce the issue following the steps:
1. Set Fenix as the default browser.
2. Close Fenix.
3. Go to Gmail and open a link.

Actual result: the link is opened in Fenix, not in the custom tab.
Not reproducible when Fenix is in the background. 

Device: Nokia 6 (Android 7.1.1).
