### ISSUE TITLE
[Bug] qrcode sync device

### ISSUE THREAD

**Issue by guiseek** [mozilla-mobile/fenix#17675]
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0

### Steps to reproduce:

when you suggested that I sync with another device for security, I installed it on my smartphone. However, the QRCode was not being read correctly.

### Actual results:

before pointing, fitting the QR Code in the indicated location, understood it as read, but presented an OAuth2 parameter error. Even trying about 10 times, the same thing happened.

### Expected results:

should wait for the correct reading and at this point send the authentication information.

### Print
![Screen](https://bug1688366.bmoattachments.org/attachment.cgi?id=9198802)

**Comment by mcarare** [comment]
@guiseek Thank you for your report. There already is https://github.com/mozilla-mobile/fenix/issues/17575 opened for this so I am closing this one as it is a duplicate.

**Comment by guiseek** [comment]
> @guiseek Thank you for your report. There already is #17575 opened for this so I am closing this one as it is a duplicate.

Ok, thanks!
