### ISSUE TITLE
[Bug] Dynamic top toolbar is shown on over the CFRs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17686]
Seen when testing https://github.com/mozilla-mobile/fenix/pull/17588 after which the problem would be more obvious but the issue currently exists in all current releases.

Seen on the current release:
<img src="https://user-images.githubusercontent.com/11428869/106252229-b3cc8c80-621e-11eb-86ac-32445e8db4ae.gif" width="33%" />

[video](https://drive.google.com/file/d/1Sq5-TExdsZHo84avpoKioUizb8sTnNMv/view?usp=sharing)

If moving fast enough one can even interact with the top toolbar menu while the CFR should hide it.
<img src="https://user-images.githubusercontent.com/11428869/106252535-0d34bb80-621f-11eb-92dd-d9b534f4a5b8.png" width="33%" />

**Comment by Mugurell** [comment]
After testing more and discussing with Mihai it seems like the intended behavior for this CFR when being placed at top was to

- be placed immediately below the top toolbar
- scroll with the dynamic top toolbar
- be fixed in place - at the top of the screen when bottom toolbar is use (fixed / dynamic)

**Comment by Mugurell** [comment]
Seems like the initial behavior (the banner being scrolled along with the top toolbar) was regressed  by https://github.com/mozilla-mobile/fenix/issues/16199 which fixed the situations in which the toolbar would be null.
I remember the toolbar being null could happen in the case of PWAs.

Initially the banner was added as a child of the `AppBarLayout` - toolbar's parent and would get the scrolling behavior for free.
After the changes from #16199 the banner would be added as a child of `AppToolbar`s parent and so would not animate anymore along with the toolbar.

To fix this we can add a new behavior to Y translate the banner in sync with the toolbar.

**Comment by Mugurell** [comment]
@mcarare confirmed that the intended behavior was for the banner to not obstruct the browser but appear above of the rendered webpage.
This seems to never have worked when the toolbar was placed at the bottom and needs to be fixed for when the toolbar is placed at the top.

**Comment by Mugurell** [comment]
@pocmo Looking more at the UX requirements:

- this banner should seem similar to one being shown by the webpages
  - banner should sit above the engineView
  - with the toolbar placed at top it should be scrolled along with the engineView

 I think the best approach would be to wrap the toolbar / engineView in some parent that would have placeholders for allowing other views appear immediately below / above the engineView.
(This is what was happening initially when the AppbarLayout of the toolbar was holding also the banner)
This way the toolbar behavior from AC would then scroll and keep in sync 2 Views like now, but with one containing more Views.
I would incline in wrapping [our current `swipeRefresh`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/layout/fragment_browser.xml#L25-L37) in yet another parent that would have placeholders below and above that and I think this would be a cool feature that could have many usages.
What do you say?

**Comment by Mugurell** [comment]
Talked "offline" with Sebastian about the big complexity needed to be added to support having
| toolbar
|-------
| banner
| geckoview

shown one on top of the others and scrolling at the same time.

@ UX Seeing that when the toolbar was placed at the bottom the banner already covered the top of geckoView
would it be ok to keep this behavior and also for when the toolbar is placed at the top
have the banner placed below the toolbar and scroll with it but cover the top of the geckoView?

**Comment by Mugurell** [comment]
Confirmed with Nicole that the proposed future behavior is an ok compromise.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/15 Nightly with OnePlus 5T (Android 10), and Sony Xperia Z5 PRemium (Android 7.1.1).
