### ISSUE TITLE
[Spike] Investigate a11y issues related to Android 11

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#17689]
Breakout from https://github.com/mozilla-mobile/fenix/issues/17571.

## Title
 Investigate a11y issues related to Android 11

## Description
- Investigate behavior changes for devices with Android 11 (start with [behavior-changes-all](https://developer.android.com/about/versions/11/behavior-changes-all)).
-  Investigate  behavior changes for apps targeting Android 11 ( start with [behavior-changes-11](https://developer.android.com/about/versions/11/behavior-changes-11)).

## Deliverables

 - Check for any deprecation in a11y APIs used in Fenix and open separate issues if needed.
 - Check for behavior changes that affect features in Fenix and open separate issues if needed.

Next Steps
Reach out to Product  / UX / a11y team if needed.

**Comment by Mugurell** [comment]
@kglazko I'm seeing this ticket in "Ready for engineering" 
so with the current backlog running low I am wondering if you are actively working or planning to work on this or it can be picked up by others?

**Comment by mcarare** [comment]
@kglazko I have investigated possible issues with switching to targeting Android 11 and also with Android 11 and I did not find any issues that should concern us. IMO we can close this if you also agree. TY!

**Comment by kglazko** [comment]
Same, investigated also and found no issues. Closing.
