### ISSUE TITLE
Web Authentication - Support Opting-in to Direct Attestations on Android

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#17688]
Taken and modified from https://bugzilla.mozilla.org/show_bug.cgi?id=1550164

### What is the user problem or growth opportunity you want to see solved?

Provide the user with control if they want to allow WebAuthn as a form of authentication.

### How do you know that this problem exists today? Why is this important?

We don't support permitting the user to anonymize the attestation and this is current UX on desktop.

<img width="459" alt="Screen Shot 2021-01-29 at 2 45 18 PM" src="https://user-images.githubusercontent.com/1370580/106265823-9931ed80-61f5-11eb-9c68-29ba723921dc.png">

### Who will benefit from it?

WebAuthn users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9532)

**Comment by jonalmeida** [comment]
Yes, we'd probably need Gecko support + GV API.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807264

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
