### ISSUE TITLE
Turn Off "paste url from clipboard"

### ISSUE THREAD

**Issue by vcg3rd** [mozilla-mobile/fenix#17681]
84.1.4 (Build #2015785883)
AC: 67.0.17, 2095f1a5d
GV: 84.0.3-20210106212839
AS: 67.0.0

I've searched the web and this forum, and I can't find any way to turn this "feature" off.  There are multiple request for improving it or modifying it (padding, placement, only offered when blank, etc) , but I can't stand it.  I tried loading about:config but nothing happened.  I am really tired of long pressing, clicking the dots, and deleting the url.

I'm willing to be lectured to RTFM, and be pointed to where I missed it in plain sight, but it's making me nuts. 

BTW, thanks for a great browser I've used since the start on all my devices and platforms! ;-)  Seriously, though!  If I didn't love it so much I'd just use something else, and not spend so much time looking for a solution.

**Comment by cadeyrn** [comment]
You can already disable this feature in the search settings. Maybe it's not obvious on the first sight but it's the place where the other address bar related options are as well.

**Comment by ekager** [comment]
@cadeyrn is correct. The feature exists in `Search` in settings.

**Comment by vcg3rd** [comment]
Bless you! For months, I have periodically gone through settings when I became overly annoyed, but I never clicked search because I didn't imagine it could be there.  Doh!  I knew I would probably end up looking foolish, but was willing to risk it.  Sorry for the bandwidth.
