### ISSUE TITLE
FNX-5236 ⁃ Tab crashed design needs a copy update

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1768]
## Steps to reproduce
1. Go to about:crashcontent
    1. Expected behavior
According to the latest mocks in https://github.com/mozilla-mobile/fenix/issues/1102#issuecomment-477444198 , the copy should be updated.
    1. Actual behavior
"Fenix can't get that tab back" copy is still used.
    1. Device information

* Android device: Pixel (Android 9).
* Fenix version: 4/18

**Comment by vesta0** [comment]
@mheubusch and @brampitoyo do we need an updated copy now that we can restore a crashed tab?

**Comment by vesta0** [comment]
This is completed and ready for testing.

**Comment by sv-ohorvath** [comment]
Verified as fixed on 4/24 build.
