### ISSUE TITLE
[Bug] tab follows desktop site even in previous pages

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17693]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open any website
Open another website in the same tab
Now enable desktop site mode 
Current page shows in desktop mode as expected
Click back button. It will open the previous page but this page also shows in desktop site mode 

### Expected behavior
On clicking back it should exit desktop mode and switch to mobile site for previous pages similar to chromium browser 

### Actual behavior
All pages are showing in desktop mode

### Device information

* Device vendor / model and Android version: ? Rog3
* Firefox for Android version: ? (go to Settings -> About Firefox) latest nightly

**Comment by ebalazs-sv** [comment]
This issue is reproducible on the latest Release 85.1.1, Beta 86.0.0-beta.2 and Nightly 210204 with Motorola Moto G6 (Android 8).
