### ISSUE TITLE
Fennec 85.1 doesn't show lical *.html-files

### ISSUE THREAD

**Issue by Buntbart** [mozilla-mobile/fenix#17699]
Fennec 85.1 from F-Droid
LineageOS 14.1 (Android 7.1.2)
LineageOS 17.1 (Android 10)

Local *.html-files are not shown anymore via URL like file:///storage/emulated/0/foo.html

No error message, just an empty page is shown instead on both devices.

**Comment by cadeyrn** [comment]
Duplicate of #7546.

**Comment by Buntbart** [comment]
No, different issue. This one occured first with 85.1.
I now went back to 84.1.4 from F-Droid, where the URL-scheme file:///storage/emulated/0/ still works.

**Comment by Mugurell** [comment]
This could be reconsidered in the future but for now Fenix will not support loading `file://` anymore.
Closing in favor of https://github.com/mozilla-mobile/fenix/issues/7546

**Comment by Buntbart** [comment]
That's quite poor.
