### ISSUE TITLE
FNX-5237 ⁃ [Bug] On tablet, the delete icon under tabs needs styling

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1769]
## Steps to reproduce
1. Swipe to close an opened tab on a tablet device.
    1. Expected behavior
A delete icon is displayed when swiping the tab. The icon has spacing & aligning 
    1. Actual behavior
The icon needs a bit of spacing & aligning between the icon and the text
![Screenshot](https://user-images.githubusercontent.com/4037709/56362250-11324d80-61f2-11e9-9dc8-7b72bd2c2247.png)UNITO-UNDERSCORE!20190418-154523!

### Device information
* Android device: Nexus 9 (android 8), Galaxy Tab 3 (Android 8)
* Fenix version: 4/18

**Comment by ekager** [comment]
Yeah there were other problems with the text so removing the text for now. :)
