### ISSUE TITLE
FNX-5238 ⁃ [UX] Library UI

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#177]
Added Meta for Library 

UPDATE 3/21: This issue captures the overall design requirements for the Library but the engineering tasks are addressed in individual category issues for Sessions, Downloads, Bookmarks and History. Global search for Library is moved to Post-MVP backlog issue #1118 

The Library is a place to store information related to people’s browsing activity. People can access all their Sessions, Downloads, Bookmarks and History in the Library. They can quickly find items they are looking for and they can edit or delete items.

**User Story**
As a user I want to quickly retrieve and view information I find while browsing the web so that I can continue a task I started or find something again. I also want to be able to edit, delete or organize items in the Library.

* the Library contains Sessions, Downloads, Bookmarks and History
* people can access the Library from home or from a site
* the Library items are sorted per date and follow the desktop convention: Today, Yesterday, Last 7 days, This month, January, December 2018, November 2018, October 2018, September 2018, Older than 6 month
* people can search for something in the Library, search is per category for now, mixed result search on Library overview can be done later 
* people have various options depending on item to manipulate it

**Problem and Scope**

* How might we enable people to find something again?
* How might we help people to continue a task?
* How might we support people to edit, delete or organize information in the Library?

**Current Design Status**

* In Good Shape
* Foundational Design Done

**Design Priority**
P1

**Mockup**
https://mozilla.invisionapp.com/share/8ZQVRNUJW3H
Please go to the grid overview and scroll down to the Library sections – let me know if you don't have access to the prototype to use the inspector. 

* Missing: confirmation flow for deleting an item
* Item selection: possible via menu and long press
* Get in touch to discuss detailed flows if needed

**Related**

* [ ] https://github.com/mozilla-mobile/fenix/issues/469
* [ ] https://github.com/mozilla-mobile/fenix/issues/563

**Comment by bbinto** [comment]
- Biggest eng work will be the search functionality
- Search functionality needs UI/UX
- Creating the Library section with functioning link to "sessions" (Downloads etc. has not been designed yet)

**Comment by bbinto** [comment]
@lime124

**Comment by bbinto** [comment]
UX/Eng to talk about what's feasibilty of scope for milestones

**Comment by colintheshots** [comment]
How should we sort Library searches? What kind of weighting should we use for each type of library item? Do we have any idea of relative importance for one type of library entry or metadata type over another?

What search options should we support? Should we allow searching by date? What about time or date ranges?

How does searching Screenshots work? Are we simply searching the filename and metadata (url, landscape/portrait, etc.)?

What about searching Downloads? Search by size, mime type, or extension?

**Comment by bbinto** [comment]
Here is the product manager answer, I need @topotropic or @lime124 though to comment what they had in mind from a UX perspective.

I have a feeling this is something we should also have @hmcgaw help us learn from users and their expectations. 

I think for the first version, this can be simple as following:

> How should we sort Library searches? 

By date? 

> What kind of weighting should we use for each type of library item? 

Start with the order the section are currently outlined: If a match, show Sessions, Screensthots, and so forth

> What about time or date ranges?
Maybe too complicated for MVP

> How does searching Screenshots work? Are we simply searching the filename and metadata (url, landscape/portrait, etc.)?

Depending on how we save them, I would assume date and even URL

> What about searching Downloads? Search by size, mime type, or extension?

What's the most simplest way? 

My overall take on this is get it out with the most basic functionality for MVP.

**Comment by mheubusch** [comment]
@topotropic In the designs we show labels for TODAY and YESTERDAY - should anything else go under OLDER as shown on the Sessions designs? Are these the three blocks of time we are using as a convention? Are there other increments we should consider like THIS WEEK or THIS MONTH? or is that something that @hmcgaw can test or has tested?

**Comment by topotropic** [comment]
Hi @colintheshots, I agree with @bbinto that a very basic implementation for MVP makes sense and to iterate from there.

> How should we sort Library searches? What kind of weighting should we use for each type of library item? Do we have any idea of relative importance for one type of library entry or metadata type over another?

No – we don' have enough insights to make an informed decision here – gut feeling: dedicated actions like bookmarks, downloads and screenshots are prioritized over automatic ones like session and history – I'd be ok with not having a search on Library overview if it's too much work.
We could also explore splitting up the results in their dedicated categories as another option. 

> What search options should we support? Should we allow searching by date? What about time or date ranges?

Default to date and we figure out refinements post MVP

> How does searching Screenshots work? Are we simply searching the filename and metadata (url, landscape/portrait, etc.)?

URL and Title if available. Again, I'd be ok with not having screenshot search for MVP.     

> What about searching Downloads? Search by size, mime type, or extension?

File name – something simple; I think we want to look into filtering or sorting as well for things like file size, extension – again: I'd be ok with not having downloads search for MVP

**Comment by topotropic** [comment]
> @topotropic In the designs we show labels for TODAY and YESTERDAY - should anything else go under OLDER as shown on the Sessions designs? Are these the three blocks of time we are using as a convention? Are there other increments we should consider like THIS WEEK or THIS MONTH? or is that something that @hmcgaw can test or has tested?

@mheubusch I was wondering if we could use what we have on Desktop: Today, Yesterday, Last 7 days, This month, January, December 2018, November 2018, October 2018, September 2018, Older than 6 month 
I think this format is ok; another option would be to spell it out, don't cluster dates and go with: Today – Monday, 25 February 2019, Yesterday – Sunday, 24 February 2019, Saturday, 23 February 2019....; it's a little bit more straightforward but also takes more space....

What do you think?

**Comment by mheubusch** [comment]
@topotropic I agree that we should use the desktop convention unless there is some research that suggests otherwise. I also agree that listing each day is too space consuming and I also am not sure that the detail adds value.  Is there somewhere I should document this for all places where we display time-based patterns (history, session archive, other places I'm not thinking of yet)

**Comment by bbinto** [comment]
@topotropic waiting for final UX feedback/review, will provide final update by Tuesday, March 5.

**Comment by topotropic** [comment]
Here's the UX spec https://mozilla.invisionapp.com/share/U9QUGQYJVK3

**Comment by mheubusch** [comment]
@topotropic Made two comments on Invision - re: casing for Delete downloads and Delete history

**Comment by vesta0** [comment]
@topotropic and @bbinto to make final decisions.

**Comment by vesta0** [comment]
@topotropic @mheubusch can we close this issue?

**Comment by topotropic** [comment]
yes, I'll close it and we can add follow-up stories
