### ISSUE TITLE
App Shortcut: Add "Scan QR" like Opera

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#17702]
Please add "Scan QR" to App Shortcut (like Opera)
# Opera
![Launcher](https://user-images.githubusercontent.com/23485114/106334352-b28f7400-629f-11eb-93cd-914124b7f8a2.jpg)
# Firefox
![Launcher](https://user-images.githubusercontent.com/23485114/106334507-0ac67600-62a0-11eb-807d-a03c970fda90.jpg)

**Comment by xmha97** [comment]
Similar: #11829

**Comment by Mugurell** [comment]
Seems to be the same request.
Let's merge the two tickets.
