### ISSUE TITLE
Zipalign Fenix before signing (+ consider verification after signing)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#17703]
>zipalign is an archive alignment tool that provides important optimization to Android application (APK) files. The purpose is to ensure that all uncompressed data starts with a particular alignment relative to the start of the file. Specifically, it causes all uncompressed data within the APK, such as images or raw files, to be aligned on 4-byte boundaries. This allows all portions to be accessed directly with mmap() even if they contain binary data with alignment restrictions. The benefit is a reduction in the amount of RAM consumed when running the application.

In https://github.com/mozilla-mobile/fenix/issues/12527#issuecomment-769981299, I determined that autograph (our signing server) is not zipaligning fenix APKs and  discussion in #releaseduty-mobile indicates we may not be zipaligning before sending the APK to autograph for signing. If APKs are zipaligned at this point, it's probably coincidence (or Google is automatically doing it but I can't find evidence that that is the case).

We should make sure we're zipaligning fenix builds for optimal performance. My recommendation would be to do these steps:
1. zipalign
1. sign (via autograph)
1. verify zipalign (i.e. `zipalign -c 4 <apk>`), failing build if not zipaligned

I think we'll need releng expertise to implement this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9544)

**Comment by mcomella** [comment]
Triage: st3fan mentioned they'd pass this onto releng so I'll check what the status is.

**Comment by mcomella** [comment]
To close this bug, I think the releng team would need to add `zipalign` as part of the build process (is this a task that @st3fan would pass on to them?). fwiw, I don't think the Android docs describe zipalign as optional.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807317

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
