### ISSUE TITLE
FNX-5239 ⁃ [Bug] Share icon from quick action bar is broken

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1770]
## Steps to reproduce
Observe the Share icon from Quick action bar.

### Expected behavior
Share icon should have both segments equal.

### Actual behavior
Share icon has uneven segments.

### Device information
* Android device: HTC Desire 820 (Android 6.0.1)
* Fenix version: 1.0.1916 (Build#11081206)

### Notes:
* Not reproducible on Samsung Galaxy Tab S3 (Android 8.0), Motorola Nexus 6 (Android 7.1.1)

![Untitled](https://user-images.githubusercontent.com/40694158/56367881-f2868380-61fe-11e9-8cc0-1c83111c36dc.png)

**Comment by colintheshots** [comment]
I'm not sure I understand what the bug is here. Are you saying that the icon and text for Share appears off-center? I can't see that reproduced anywhere.

**Comment by colintheshots** [comment]
Oh, I see. The vector icon itself has wider segments on certain devices.

**Comment by yoasif** [comment]
Can this be reopened? I am still seeing this on a Moto G.

**Comment by sv-ohorvath** [comment]
@colintheshots This is still reproducing on some devices. I'm also seeing this on HTC Desire 820 (Android 6.0.1)

**Comment by softvision-miralobontiu** [comment]
I'm not able to reproduce this issue anymore on the 10/18 Nightly build, with HTC Desire 820 (Android 6.0.1).
I will close this issue.
