### ISSUE TITLE
[Bug] Can't Save video files to my device on the mobile version of xhamster.com

### ISSUE THREAD

**Issue by Jpersh27** [mozilla-mobile/fenix#17711]
1.) When attempting to save a video file to my device on the website xhamster.com it always says “download failed" and “try again”. 

Description of issue-

- This issue occurs specifically after clicking play on any video and holding down over the video until the following shows up- blob:https:// and below the Video URL the “Save file to device" option appears.

- After clicking “save file to device" a “download failed" with a white and black error sign with a (!) Inside shows up. In the bottom right hand corner of my screen a purple box with the words “try again" inside of it appears also.

- Even after clicking try again several times nothing occurs and the video file is not able to be saved to my device.

Device information:
- Android 10 Q
- Fennec F-Droid, 85.1.0 (Build #851020)
- AC: 70.0.16, 21ce9abdd
- GV: 85.0-20210127155644
- AS: 67.2. Wednesday 1/27 @ 5:18 PM

**Comment by Jpersh27** [comment]
![Screenshot_20210131-011854.jpg](https://user-images.githubusercontent.com/77606699/106376634-2ba4cf00-6365-11eb-93b1-5b42dc593db0.jpg)

**Comment by Jpersh27** [comment]
-The following 2 images contain “NSFW" content that pertains specifically to the download issue that I have encountered regarding the website xhamster.com

- - The following 2 “NSFW" Images demonstrates the following message that shows up when trying to save the file to my device and the error message I get after attempting to save it to my device. 

![Screenshot_20210131-011716.jpg](https://user-images.githubusercontent.com/77606699/106376710-d4532e80-6365-11eb-9efe-24c7280de437.jpg)

![Screenshot_20210131-011708.jpg](https://user-images.githubusercontent.com/77606699/106376713-d917e280-6365-11eb-8b18-8729087273e1.jpg)

**Comment by Amejia481** [comment]
Very likely to be similar to https://github.com/mozilla-mobile/fenix/issues/17716#issuecomment-770937645 but we have to investigate

**Comment by Jpersh27** [comment]
@Amejia481 I apologize for posting the images in the repository and have removed them altogether. 

1.) Any progress or an ETA on when or if the download issue will be fixed for the specific website (xhamster.com) in question?

• A similar related website for example (pornhub.com) allows the videos to be saved within the browser.
• Don't understand why some websites are restricted and don't have the ability to save videos.

Thanks again and apologizes again and looking forward to your reply.

**Comment by Amejia481** [comment]
No problem, I opened an issue for the geckoview team to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1691055.
For the bug to be fixed, we need either the ticket above or this https://bugzilla.mozilla.org/show_bug.cgi?id=1690037 to be fixed.

**Comment by Jpersh27** [comment]
@Amejia481 Thank you for the reply and for opening the tickets.

1.) Expected ETA on when either ticket could be resolved?

2.) Is there any other information you need from me regarding these issues?

3.) Lastly is there any way for me to submit information to the geckoview or Mozilla team?

Thanks again.

**Comment by Amejia481** [comment]
> @Amejia481 Thank you for the reply and for opening the tickets.
> 
> 1.) Expected ETA on when either ticket could be resolved?
> 
> 2.) Is there any other information you need from me regarding these issues?
> 
> 3.) Lastly is there any way for me to submit information to the geckoview or Mozilla team?
> 
> Thanks again.


1) Sorry, I can't share an ETA as It's going to depends on work from another team.
2) I think the information here is sufficient, but could subscribe to https://bugzilla.mozilla.org/show_bug.cgi?id=1691055, in case they need any additional info, just add your email as `CC`
3) Yes :), you can submit any additional info here or on https://bugzilla.mozilla.org/show_bug.cgi?id=1691055

Thanks, for your wiliness to help!

**Comment by Jpersh27** [comment]
@Amejia481 Thanks again for the reply and I will be looking forward too further updates regarding the issues.

• Your welcome and please continue with further updates regarding these issues here on GitHub if possible with any new information you may receive. 

• I will also continue to follow the tickets on Bugzilla at the links provided.

Thanks again!

**Comment by Jpersh27** [comment]
Hey @Amejia481 

1.) I was just curious if there is any new updates regarding the download issue I am having with the website xhamster.com? 

• Upon going to the 2 links you provided me above to the issues labeled 1691055 and 1690037 there hasn't been any new updates from anyone in almost a week for each case respectfully. 

2.) Any workaround that would allow me to download videos from the specific website xhamster.com on my Android device? 

3.) Or will I have to just wait for the issue to be fixed? (Who knows when that will eventually happen or if it will even happen)...

**Comment by Amejia481** [comment]
> Hey @Amejia481
> 
> 1.) I was just curious if there is any new updates regarding the download issue I am having with the website xhamster.com?
> 
> • Upon going to the 2 links you provided me above to the issues labeled 1691055 and 1690037 there hasn't been any new updates from anyone in almost a week for each case respectfully.
> 
> 2.) Any workaround that would allow me to download videos from the specific website xhamster.com on my Android device?
> 
> 3.) Or will I have to just wait for the issue to be fixed? (Who knows when that will eventually happen or if it will even happen)...

If you like you could ask for an update on the bug.

For this specific site, unfortunately there is not a workaround as the site usages  `blob:` URIs, for other sites you could try activating the `External download manager` setting on Fenix by going to `Settings` -> `External download manager`. Hope it helps.

**Comment by Jpersh27** [comment]
@Amejia481 I asked for an update on the Bugzilla Bug #1690037 at the following link- 

•https://bugzilla.mozilla.org/show_bug.cgi?id=1690037

1.) Would you be able to possibly look into the bug for me also please?

**Comment by Amejia481** [comment]
> @Amejia481 I asked for an update on the Bugzilla Bug #1690037 at the following link-
> 
> •https://bugzilla.mozilla.org/show_bug.cgi?id=1690037
> 
> 1.) Can you look into the bug report and see if there is any new updates on your end?

👋🏽 
So far we are waiting for updates on the Bugzilla bug, I'm subscribed to the updates and checking for updates.

**Comment by Jpersh27** [comment]
@Amejia481- Hello it has been over 21 days (3 weeks) now and no news or any progress or updates regarding this issue. 

• Current Geckoview version in beta for Android I have installed is- GV: 87.0-20210307185839

![IMG_20210309_205655.jpg](https://user-images.githubusercontent.com/77606699/110563916-02bcea00-811a-11eb-849d-db9bd5845527.jpg)

• Here is what's displayed on Bugzilla regarding this issue. Issue hasn't been updated for 19 days now.

1.) Can you inquire/ Ask for a status updated on when or if this issue will be fixed? Or will it keep being pushed back from one Geckoview version to the next one after that? (It was already pushed back once from Geckoview: m89 from m88 as shown in my image I attached above)

**Comment by Jpersh27** [comment]
@Amejia481- It has been 6 days now and no response from you and almost 4 weeks from the other developers on Bugzilla.

1.) Will I ever receive a response from either you @Amejia481 or anyone on Bugzilla? 

• The lack of effort for almost 2 months now proves my point that a big conglomerate technology companie like Mozilla is just like the Big two (Google and Apple) and that consumers come lasts and headlines come first. New features come first and fixing bugs and other issues are put on the back burner and the overall one experience of the product continue to deteriorate.

• This is a sad state for Mozilla as a whole and for there various applications available on Android. 

• Just because a Developer is open source means nothing unless they actually try to help users of there product and try to make there experience better by improving it. 

• At this point Mozilla will no longer get my business and I will delete any information or accounts that I have registered with Mozilla products.

• I will also no longer recommend Mozilla as an alternative to Google and will tell anyone I know to stay away from this dumpster fire that will never get put out.

• Im sure this request will be closed immediately and you will not respond to me because you either say “I don't like we're this is going" And just refer me to Bugzilla or the Firefox user forums.

Good day to you...

**Comment by Amejia481** [comment]
Sorry, I missed your previous message.

As I mentioned before the scoped of the bug is outside of my team, every team has its own priority, I know for sure if the GeckoView team hasn't tackled the bug is because they are working on other higher priority issues. Feel free to inquire about it on the Bugzilla bug. Be mindful about the team sizes vs the number of bugs that are filed, for this reason, we encourage community contributions for helping with bugs,  everybody at Mozilla tries to do their best as it is humanly possible.

**Comment by Jpersh27** [comment]
Hello @Amejia481 

1.) Can you provide an update on this issue for me? 

• I have asked several times for an update on Bugzilla and they have been ignored. No response or openness from anyone. It has been over 3 months since I opened this issue on GitHub and over a month since I asked you for an update. 

Current version of the browser I'm using now is as follows- 
88.0.0-beta.6 (Build #2015803915)
AC: 74.0.9, f657946f8
GV: 88.0-20210410185959
AS: 74.0.1

**Comment by Jpersh27** [comment]
@Amejia481 

• Previously you told me to go to Bugzilla and  comment on the Bugzilla issue at the following web address below-
 https://bugzilla.mozilla.org/show_bug.cgi?id=1690037

• I did make a comment on the Bugzilla issue and also emailed the triage owner Emily Toop more than once and I haven't heard anything back from her and also on my Bugzilla comment I asked for- Flags: needinfo?(etoop)

• In your previous comment you stated the following-

As I mentioned before the scoped of the bug is outside of my team, every team has its own priority, I know for sure if the GeckoView team hasn't tackled the bug is because they are working on other higher priority issues. Feel free to inquire about it on the Bugzilla bug. Be mindful about the team sizes vs the number of bugs that are filed, for this reason, we encourage community contributions for helping with bugs, everybody at Mozilla tries to do their best as it is humanly possible.

1.) So can you now please explain if me waiting over a month for an answer is long enough?

2.) And if not then how long is long enough?

• Because I think over a month is way way to long of a time and a more reasonable wait time would be no longer than a week especially with how big a company Mozilla is and how big it's development community is.

**Comment by Jpersh27** [comment]
Hello @Amejia481 I emailed you and commented twice now on this issue and have asked for an update both times and you have not responded back either time. I am wondering if you can please look Into this and if you no longer have time or it is not longer a priority can you please direct me to the right person to contact about getting this issue resolved.

**Comment by Jpersh27** [comment]
Hello @kbrosnan @mdboom @jonalmeida @brampitoyo

• I am wondering if someone else can please look into this issue for me. It has been over 3 months now and this issue is still not fixed. I have asked several times for updates on Bugzilla from the triage owner and have emailed the triage owner several times and have not been given a response. I have also asked @Amejia481 for updates and emailed him and have not received a response Several > times.

**Comment by Amejia481** [comment]
> Sorry, I missed your previous message.
> 
> As I mentioned before the scoped of the bug is outside of my team, every team has its own priority, I know for sure if the GeckoView team hasn't tackled the bug is because they are working on other higher priority issues. Feel free to inquire about it on the Bugzilla bug. Be mindful about the team sizes vs the number of bugs that are filed, for this reason, we encourage community contributions for helping with bugs, everybody at Mozilla tries to do their best as it is humanly possible.


👋🏽 Sorry, I don't have anything to add that I haven't mentioned before.

**Comment by Jpersh27** [comment]
@Amejia481 Thank you for the same copy and paste answer as always, and yes I followed your directions to Bugzilla and was ignored and no status update was given by the team. 

Thanks again and I promise I won't bother you again for another update. I will just continue to wait like I have been for almost 4 months now.

**Comment by Amejia481** [comment]
Sorry that the bug has taken so long, but as I mentioned before:

> "Be mindful about the team sizes vs the number of bugs that are filed for this reason, we encourage community contributions for helping with bugs, everybody at Mozilla tries to do their best as it is humanly possible."

**Comment by Jpersh27** [comment]
@Amejia481 And I totally understand and respect that, but how is the community supposed to help with a Geckoview issue?

• The issue needs to be resolved by the Geckoview Developers not community Developers. The issue wasn't a problem when add-ons we're supported and I was able to use a Download manager extension. However that lasted until all the add-ons where stripped away from Firefox for Android and now only a handful work or are supported.

**Comment by Amejia481** [comment]
The geckoView team manage their issues on bugzilla, you can also chat with them on Matrix https://chat.mozilla.org/#/room/#geckoview:mozilla.org .

**Comment by Amejia481** [comment]
> @Amejia481 I totally understand and respect that, but how is the community supposed to help with a Geckoview issue?


They are also open to patches from the community, there is a guide how to contribute here https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/geckoview-quick-start.html

**Comment by Jpersh27** [comment]
@Amejia481 Thank you for all the information and I was able to speak with the Geckoview team on Matrix.
