### ISSUE TITLE
[Bug] Crash while playing video

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#17713]
## Steps to reproduce
open https://alephnews.ro/sanatate/exista-o-diferenta-intre-ivermectina-la-animale-raspunsul-dr-ion-alexie-si-noi-putem-sa-mancam-mancarea-de-caine/

Click the video to play 

### Expected behavior
video starts playing
### Actual behavior
browser crash
### Device information

* Device vendor / model and Android version: OnePlus5t. LineageOS 17.1
* Firefox for Android version: Nightly

**Comment by hakkikaancaliskan** [comment]
Duplicate of #17668, https://github.com/mozilla-mobile/android-components/issues/9556

**Comment by Mugurell** [comment]
Closing as dupe.
