### ISSUE TITLE
[Bug]Search box and suggestions remain stuck in front of search results after searching any query.

### ISSUE THREAD

**Issue by leonofjudah** [mozilla-mobile/fenix#17722]
Whenever I try to search something in the search bar, the **_suggestions and search box remain stuck_** in one place and the **search results displays behind the suggestions**. This bug I'm facing from months. Please do something about it. Fix it.

- See in the image below, after I searched for **Mozilla website**, the suggestions and search box are just stucked there. The **website is showing behind the box.**

<img src="https://user-images.githubusercontent.com/45731088/106407539-4e68dd80-6462-11eb-9a70-982cbbf34e4c.jpg" width="25%" />

- ### When I want to see the requested results, then I have to switch the application:

<img src="https://user-images.githubusercontent.com/45731088/106406565-ace08c80-645f-11eb-91bd-f1dc87398a92.jpg" width="25%" />

- ### and then the stucked box and suggestions goes away.

<img src="https://user-images.githubusercontent.com/45731088/106407696-ba4b4600-6462-11eb-8fd2-53d7021bee25.jpg" width="25%" />

- ### _**It is very irritative, every time I've to switch the application to see the search results and content which I've to access.**_

**Comment by Mugurell** [comment]
Thank you for the report!
This has already been reported here - https://github.com/mozilla-mobile/fenix/issues/17521 but it's very hard to reproduce.
If you have any details that may help in reproducing (like the device model, firefox version used or any others that you consider important) please leave a comment on that ticket.
Closing this as a duplicate.
