### ISSUE TITLE
enable github discussions

### ISSUE THREAD

**Issue by c3X69puyujLWudBjwQEjmTUgEXr49cGa74EqHiL** [mozilla-mobile/fenix#17727]
it would be a nice place for mozillians to discuss firefox

**Comment by Mugurell** [comment]
Github discussions being https://docs.github.com/en/discussions.

Please note that currently community discussions are welcomed on Mozilla's Matrix Server.
For more info - https://wiki.mozilla.org/Matrix

**Comment by kbrosnan** [comment]
We have Matrix/Element and discourse.mozilla.org which have the moderation tools we require for community building. Github has been historically weak in providing strong protections for communities.
