### ISSUE TITLE
Do not show favicon of default search engine when URL is focused

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#17721]
Go to any website. Tap the URL and observe that the favicon of the default search engine appears beside the URL. This is strange and even confusing UX. It would be fine to show the favicon of the default search engine when the URL bar is clear, but showing it beside the URL of the website you're on is strange and confusing (as welll as "noisy"). Please consider making this change. 
![Screenshot_20210128-231324](https://user-images.githubusercontent.com/47801466/106403483-f5b32980-63fc-11eb-9ef4-4316807994db.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9553)

**Comment by sflorean** [comment]
This is still reproducible on Fenix versions. 
Devices affected: all.

**Comment by willfs84** [comment]
Still needs to be fixed, please do not close

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807723

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
