### ISSUE TITLE
Kindly Build Option To Set Default Download Path🙏🏻🙏🏻🙏🏻

### ISSUE THREAD

**Issue by Happy-Kunal** [mozilla-mobile/fenix#17736]
Since it is always been a problem that when ever I try to clear firefox data inorder to delete unwanted files on my android device I accidentally delete my downloads and it difficult for me to collect them all again

Since it doesn't sounds a big deal as you set up the same for Linux so kindly try to make it as soon as possible

**Comment by Dunexus** [comment]
This is part of https://github.com/mozilla-mobile/fenix/issues/5764

**Comment by Happy-Kunal** [comment]
Ok Thank you , but try it build it as soon as possible 👍🏻
