### ISSUE TITLE
[Bug] Wrong tab selected when you click a tab from a collection

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17730]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Create a collection of tabs.
2. Open a few different tabs (to avoid confusion).
3. Expand the collection and tap one of the tabs saved to open it.
4. Observe the tab shown.
5. Open the tabs tray and observe the tabs order.
### Expected behavior
The page selected from the collection is opened.
The tab opened from the collection is added at the bottom of the list, respecting the order set in https://github.com/mozilla-mobile/fenix/issues/11376
### Actual behavior
The page shown at step 4 is not the page selected from the collection, but the last tab you have visited.
The tab opened from the collection is added at the top of the list, making it difficult to figure out if it's a long tab list.
### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9), Pixel 3 (Android 11)
* Firefox for Android version: Nightly 2/1

**Comment by LittleAngelwings** [comment]
I use the same Nightly version, but i can't confirm this issue. For me Firefox will open the same tab I had choosen. But i don't see any notice that a new tab was opened. In the tab-grid a can see the new tab.

**Comment by mcarare** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/9593

**Comment by mcarare** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/17940.
Please retest! Thank you!

**Comment by softvision-miralobontiu** [comment]
Verified on the 2/12 Nightly build with OnePlus 5T (Android 10):
* the page selected from the collection is opened ✔
* the opened page is at the top of the list, NOT at the bottom ❌


https://user-images.githubusercontent.com/40694158/107750449-b8b43480-6d24-11eb-9902-3d20961884de.mp4

@mcarare should we close this issue?

**Comment by mcarare** [comment]
Yes, the issue with the lace the tab is restored is already tracked by another issue: https://github.com/mozilla-mobile/fenix/issues/10986. Thank you for testing!
