### ISSUE TITLE
 [Bug] Autoplay blocking blocks player on m.kro-ncrv.nl, even if initiated by the user #16402 

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#17741]
## Steps to reproduce

1. Open https://m.kro-ncrv.nl/fragmenten/muziek-in-de-jaren-zeventig-een-cruciaal-punt-in-de-popmuziek
2. Click the play icon

### Expected behavior

Stream starts.

### Actual behavior

Stream does not start. Instead, the following appears in the web console in the remote developer tools:

>Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted.

If the padlock icon is tapped and autoplay is enabled, the video works fine. It is likely the page is handling JS in a fancy way which breaks the heuristics to detect if the video playback is being initiated by the DOM event for the user tapping on the play button, but this is not reproducing on the desktop build with the responsive design mode and emulation, and diagnosing the issue further using the remote devtools is not tenable right now due to the debugger not working properly.

### Device information

- Android device: Samsung Galaxy S7 Edge
- Fenix version: Nightly 210131 17:01 (Build #2015790603)

**Comment by Amejia481** [comment]
Would you mind opening a issue on Bugzilla for the gv team, we don't have control over the DOM video player.

I give it a try on Android 11 (Pixel 3) and I wasn't able to replicated, which version are you using?

**Comment by wisniewskit** [comment]
Sure, done: https://bugzilla.mozilla.org/show_bug.cgi?id=1690837

For the record I'm using Android 8 on a Samsung Galaxy S7 Edge.

**Comment by Amejia481** [comment]
Thank you!
