### ISSUE TITLE
History not being deleted upon exit

### ISSUE THREAD

**Issue by the1nine** [mozilla-mobile/fenix#17742]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

All of the fields may be selected when setting up the "Delete browsing data on quit" in Firefox for Android. I noticed the issue when visiting maps.google.com where past searches were still present suggestions The initial position of the map was also persistent from the previous sessions. in the search bar. Don't know if this issue is unique to Google's tracking attempts or something with Firefox

### Expected behavior

Past versions of Firefox would actually remove all data used by a site to prevent tracking. Google would not remember my old searches.

### Device information
Moto X4 (payton)
Android 10
LineageOS
85.1.0 (Build #2015788691)

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by mcarare** [comment]
@the1nine When you use "Delete browsing data on quit" you must actually use the "Quit" menu button for data to be deleted. If you just background the app or kill the app the browsing data will not be deleted. 
Tested your use case with google maps and all recent searches are gone if you use the quit button.

**Comment by the1nine** [comment]
@mcarare That is what I'm doing. @ekager Suggest re-opening issue.

I've rolled back to 68.11.0 and do not have this problem.

**Comment by the1nine** [comment]
@ekager @mcarare I think I see what happened to the settings. Versions around 68 contained a greater set of delete options and isolated history information from the site data. After 68 both history and site data got bundled under a single option. Maybe the more granular options were better? Don't know if this would be classified as a bug or questionable design by Mozilla.
