### ISSUE TITLE
Add Motion Transitions when navigating

### ISSUE THREAD

**Issue by marcellogalhardo** [mozilla-mobile/fenix#17752]
### What is the user problem or growth opportunity you want to see solved?

As a daily user of Firefox Mobile, I would like to have a better user experience when navigating (screens, not pages) - today, the home does not have any transition, and tapping any button will change the UI abruptly.

### How do you know that this problem exists today? Why is this important?

There is no transition from the home screen to any other first screen, giving a clumsy appearance when the app navigates, impacting the user experience. Many browsers offer fluid navigation, which is suitable for extended usage.

For more details, I prepared a visual comparison at the bottom of this description with and without motion.

### Who will benefit from it?

Users that consistently use the app might benefit from a more fluid experience.

### Extra Information

Android offers Motion Transition out of the box for Navigation Component and Fragments, both used by Firefox Mobile, and it is easy to integrate with (you need to set the motion transition you want per Fragment). As far as I know, it also respects accessibility configurations like disable animations or reduce motion, so there's no need to support it manually.

As I already did the necessary changes to create the visual comparison, if a Firefox designer thinks to approve those changes, I can submit a Pull Request myself. Feel free to request a different transition if you believe it would be better - you can check the official design document for Motion Transitions [here](https://material.io/design/motion/the-motion-system.html), there are few options.

#### Visual Comparison

| No Motion  | Motion    |
|------------|----------|
| ![f_no_motion](https://user-images.githubusercontent.com/4348197/106578748-2780d900-6540-11eb-8e23-12b7698013e4.gif) | ![ff_motion](https://user-images.githubusercontent.com/4348197/106578782-323b6e00-6540-11eb-8638-899fe310eb85.gif) |

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9570)

**Comment by amedyne** [comment]
@violasong What do you think?

**Comment by hakkikaancaliskan** [comment]
Actually not just for home, there should be animation for every single motion.
As far as I recall they were removed because of performance problems by @sblatz, maybe I'm wrong idk 🤷

**Comment by marcellogalhardo** [comment]
Hey @hakkikaancaliskan, thank you a lot for the context!

In #11825 it is stated, "In the worst case where we're unable to perform the animation because capturing the thumbnail is too slow (...)" and as a possible solution, "Use a different animation that doesn't require a thumbnail". The animations I'm using here are applied only on the Fragment level, so it _should_ not impact the performance. Maybe someone that worked on that issue can clarify it further.

Reading #9443, the only problem stated is how the animation looks janky as they can not animate the action bar, which does not look related to performance. I guess the main reason is how the animation operates: it slides up and down while the Action Bar is instantly visible and does not participate in the transition.

However, if we go with my initial proposal (Z-Axis transition), I believe the toolbar's lack of animation would not be so visible due to how the animation performs. 🤔

**Comment by hakkikaancaliskan** [comment]
Actually before ux feedback we need eng feedback because those animations were removed on purpose and they should decide if they are applicable.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814126

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
