### ISSUE TITLE
[Bug] Can't add custom Searx instance

### ISSUE THREAD

**Issue by 999eagle** [mozilla-mobile/fenix#17754]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

- Go to Settings > Search > Add search engine > Custom
- Select Other and use the URL `https://sx.catgirl.cloud/search?q=%s`

### Expected behavior

- The search engine should be added

### Actual behavior

I instantly receive the error 'Error connecting to "Searx"'.

I tried all of these search URLs with the following results:

- `imdb.com/search/q=%s`: Search engine added and works fine
- `https://sx.catgirl.cloud/search?q=%s`: Adding fails instantly with 'Error connecting to "Searx"'
- `https://sx.catgirl.cloud/search/q=%s`: Search engine added, but wrong URL so it doesn't work
- `https://sx.catgirl.com/search?q=%s`: Search engine added, but the URL doesn't exist and isn't mine.

Somehow it seems like the combination of the `.cloud` TLD and using a `?` in the URL fails.

### Device information

* Device vendor / model and Android version: LG-H850 running LineageOS 17.1
* Firefox for Android version: Fennec F-Droid 85.1.0 (Build #851020), built 2021-01-27

**Comment by Dunexus** [comment]
Some users reported an issue with the antibot solution used with searx, maybe it is the same issue here. See https://github.com/mozilla-mobile/fenix/issues/11332 for more details

**Comment by 999eagle** [comment]
Thanks, that fixed it. Closing the issue.
