### ISSUE TITLE
[Bug]Download Prompt isn't displayed again after dismissing it  

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#17755]
## Steps to reproduce
1. Navigate to : https://file-examples.com/index.php/sample-documents-download/sample-doc-download/
2. Tap the orange "Download Sample DOCX File" button next to the 1MB file
3. Dismiss the Download Prompt
4. Tap again the orange "Download Sample DOCX File" button next to the 1MB file

### Expected behavior
Step 4: The download prompt should be displayed again

### Actual behavior
Step 4: The prompt isn't displayed

### Device information

* Device vendor / model and Android version: Google Pixel 3a (Android 11)
* Firefox for Android version: Nightly 210202

### Notes
❗ Reproducible on other web sites / file types

► Video 
![20210202-135100](https://user-images.githubusercontent.com/51314259/106598522-848c8700-6560-11eb-928b-1e42641ede37.gif)

**Comment by Amejia481** [comment]
This is the same as https://github.com/mozilla-mobile/fenix/issues/16998#issuecomment-763127404  we have an Geckoview bug for it  https://bugzilla.mozilla.org/show_bug.cgi?id=1687540

**Comment by Amejia481** [comment]
This will be covered on https://github.com/mozilla-mobile/android-components/pull/9790

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with Samsung Note 10(Android 11), Pixel 3 (Android 11).

**Comment by codrut-topliceanu** [comment]
@sflorean If everything is in order with this issue may I move it to Done column on the board?
