### ISSUE TITLE
[Bug] most visited sites showing despite disabling in preferences

### ISSUE THREAD

**Issue by benedictbrown** [mozilla-mobile/fenix#17757]
In Firefox beta 86, my most visited does are showing on the home screen even though I have the option disabled in preferences.  Enabling and re-disabling the preference makes no difference.

Firefox version info:
86.0.0-beta.1 (Build #2015789707)
AC: 72.0.1, d61ba1282
GV: 86.0-20210126185730
AS: 67.2.0

## Steps to reproduce
Display home screen.  Most visited sites appear alongside the manually selected top sites.

### Expected behavior
Only the top sites should appear when "Show most visited sites" is disabled in settings.

### Actual behavior
Most visited sites continue to appear even when the setting is disabled.

### Device information
LG V-35 ThinQ
Android 9

**Comment by cadeyrn** [comment]
Duplicate of #17655 (already fixed in Nightly).

**Comment by kbrosnan** [comment]
Closing as a duplicate
