### ISSUE TITLE
[Telemetry] Update metrics expiring in March/April

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17768]
Followup to #17766

In `metrics.yaml` there are a number of metrics that are set to expire in the near future. Check with @vesta0 to confirm that we want to renew these, and increase the expiration date accordingly (usually 6 months).

**Comment by mcarare** [comment]
@vesta0 I have opened a PR for telemetry renewal addressing the metrics that expire in March. Please confirm we want to extend the expiration date for PWA telemetry: https://github.com/mozilla-mobile/fenix/pull/18071.
Also, I guess the migration telemetry is no longer needed and should not be renewed, and maybe even removed.

For issues expiring in April, as there are many and maybe product & data science need time to assess if they should be renewed or removed, I have opened a separate issue: https://github.com/mozilla-mobile/fenix/issues/18076

**Comment by vesta0** [comment]
Thanks for checking in @mcarare 

Let's user these existing metrics to investigate how many Fennec users are still migrating to Fenix and then decide when we should retire both the migration telemetry and the migration code. I will bring this up with @st3fan and data science.

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/18071.
