### ISSUE TITLE
[Bug]Youtube captions not showing in fullscreen mode.

### ISSUE THREAD

**Issue by Japeskie** [mozilla-mobile/fenix#17786]
## Steps to reproduce

1. Watch any youtube video with caption.
2. Go fullscreen mode.

### Expected behavior

Captions will still show in fullscreen mode.

### Actual behavior

Captions disappearing in fullscreen mode, but will show when you exit fullscreen mode.

https://user-images.githubusercontent.com/73644544/106725430-56807300-6644-11eb-9eec-e025e7b5dbb1.mp4

### Device information

* Device vendor / model and Android version: Mi 9T Pro / MIUI 12
* Firefox for Android version: Nightly (Build #2015791019)

**Comment by LaurentiuApahideanSV** [comment]
Hello and thank you for the report.
The issue has already been reported here: https://github.com/mozilla-mobile/fenix/issues/8252. I will mark this issue as closed as it will be handled there.
