### ISSUE TITLE
[Bug] Long pressing tab in multiselect mode triggers haptic feedback, but does not select the tab

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#17781]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open at least two tabs
2. Open tab switcher
3. Long press a tab
4. Long press a second tab

### Expected behavior

Tab is selected.

### Actual behavior

I feel some haptic feedback, but the tab is not selected. 

### Device information

* Device vendor / model and Android version: Pixel 2 
* Firefox for Android version: Nightly 210202 21:17 (Build #2015791019)
AC: 73.0.20210202194906, 59dddc21f
GV: 87.0a1-20210202095107
AS: 69.0.0

**Comment by VitalyVPinchuk** [comment]
Hello!

It is because of `onLongClickListener` in `FenixTabsAdapter` class, which works only with `Normal` selection mode but not with `MultiSelect` mode:
```
                    if (mode is TabTrayDialogFragmentState.Mode.Normal) {
                        context.metrics.track(Event.CollectionTabLongPressed)
                        tabTrayInteractor?.onAddSelectedTab(
                            tab
                        )
                    }

```
Probably `MultiSelect` mode was inadvertently omitted.

Should this be fixed?
