### ISSUE TITLE
We will need Adjust for campaign tracking

### ISSUE THREAD

**Issue by jeanMS741** [mozilla-mobile/fenix#17783]
we will need Adjust for campaign tracking, please work with Loren to get Adjust API keys etc.

This should actually also land in Milestone 2 as per milestone board.

_Originally posted by @bbinto in https://github.com/mozilla-mobile/fenix/issues/675#issuecomment-467830170_

**Comment by kbrosnan** [comment]
This looks like it is not useful. Loren if we need to track something here opening a new clean issue is best.
