### ISSUE TITLE
[Bug]Screenshot feature in private browsing mode

### ISSUE THREAD

**Issue by Japeskie** [mozilla-mobile/fenix#17785]
## Steps to reproduce

EDIT: Uploaded video to be more clear.

1. Take a screenshot.
2. Minimize the application.
3. Go back to Fenix.
4. Take a screenshot.

### Expected behavior

You will be able to take a screenshot.

### Actual behavior

Fenix will say "This app doesn't allow taking screenshots".

https://user-images.githubusercontent.com/73644544/106727709-b4ae5580-6646-11eb-959d-702839ab00e4.mp4

### Device information

* Device vendor / model and Android version: Mi 9T Pro / MIUI 12
* Firefox for Android version: Nightly (Build #2015791019)

**Comment by Dunexus** [comment]
You can disable this security/privacy feature in Settings > Private browsing > Allow screenshots in private browsing.

**Comment by Japeskie** [comment]
What I meant is that I should be able to take screenshots using "Private Browsing" mode since I enabled it, but there's a bug when you exit the app and go back it will say "This app doesn't allow taking screenshots" even though the option "Allow screenshots in private browsing" is enabled.

**Comment by Japeskie** [comment]
As of Nightly (Build #2015791947) I think this issue is fixed, I also tried it on different phones (Xiaomi, Samsung, Oppo).

Here's a video of trying to replicate the issue.

https://user-images.githubusercontent.com/73644544/107202116-c91e9380-6a34-11eb-94f4-7ffd6964dfa7.mp4

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the 2/8 Nightly build with Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
