### ISSUE TITLE
Remove Fenix from Recents after pressing Quit

### ISSUE THREAD

**Issue by gbdomubpkm** [mozilla-mobile/fenix#17790]
Hi.

Android 9
Fennec 85.1.0
![image20210203_125022484](https://user-images.githubusercontent.com/50362604/106745262-21aef480-6621-11eb-915a-585b6fe1d847.jpg)

Why is the app still open in the background after EXIT? Is this normal or is it a known bug ? Sorry, I can't find any bug reports in the jungle..

I have observed that this is not the case for Brave, Vivaldi, Privacy browser..
Thanks in advance for the explanations.

Best regards

**Comment by Mugurell** [comment]
https://user-images.githubusercontent.com/11428869/106760955-03ef8880-663d-11eb-808b-4f54b817d3c5.mp4

How did you close the app? Just pressing the back button until getting to the Android homescreen?
This is the normal behavior on Android and I see it also for Vivaldi or DDG Privacy Browser etc.
The applications shown there may be still running in background or may be "fully" closed. The recents screen shows just an overview of the current and past opened applications allowing for a quick resume.

**Comment by gbdomubpkm** [comment]
I understand what you are saying and you're absolutely right in the way you're doing it.

But i'm talking about closing the browsers using the 'exit' option in the drop-down bar (on the right for firefox and Vivaldi, on the left for privacy browser), which produces for me the effects mentioned for the different browsers.

**Comment by Mugurell** [comment]
I think for Fenix you're referring at the "Quit" menu option.
Which can be activated by enabling "Delete browsing data on quit" in app's settings,
Which indeed will not remove the app from the recents screen.

I see an "Exit" option in Brave which indeed will remove the app from recents.
Haven't seen a similar option in Vivaldi or DDG.

Asking UX if we should remove the app from the recents screen upon pressing the "Quit" menu button.

**Comment by gbdomubpkm** [comment]
Great. Thank you.

**Comment by BrokenShoeLace** [comment]
I asked the same question a few months back only to have someone reply that they dont intend to fix it.

Maybe its time to load this in Visual Studio 2019 and do it ourselves.

**Comment by topotropic** [comment]
I agree, it makes sense to remove the app from the recent screens when people have "Quit" enabled and use it.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 3/24 with Pixel 3 (Android 11), Lg G7 Fit (Android 8.1).

**Comment by opusforlife2** [comment]
This PR (#18599) has caused a problem: Though the app is removed from Recents upon tapping Quit, it remains in RAM. A user could swipe the app from Recents to remove it from RAM before this PR.

Why this is an issue for me: On network change, Fenix (and desktop Firefox) sometimes lose internet connection, and nothing short of completely closing the app fixes it. For Fenix, this meant Quit and then swipe from Recents. Now I have to go all the way into app settings to Force Stop to achieve the same effect.

**Comment by sflorean** [comment]
@opusforlife2 please file a new issue for the problem described above. Thank you!

**Comment by opusforlife2** [comment]
@sflorean I've opened #18805, but I'm not sure how useful this will be, since it doesn't have any STR.
