### ISSUE TITLE
[Feature] Three-dot menu Sync sign-in item

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17798]
Meta: #17796
Followup to #17771 

~Depends on synced tabs in the tabs tray in issue #14969 and #14117~

UX point of contact: @violasong (Victoria)

Figma designs (bottom right, labeled "Final design"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

## Acceptance criteria
* In the main three-dot menu **AND** the new tab three-dot menu show "Sign in to sync" when a user isn't signed in
* When a user has signed in to sync, they should see their username ("Signed in as _username_")
   * This should be ellipsed, see example in designs

### UX feedback needed:
Open question: what icon is shown next to this item? (need to get updated designs from @violasong)

**Main menu**
<img width="341" alt="image" src="https://user-images.githubusercontent.com/43795363/106791366-7307b580-661a-11eb-8ad9-aa3743d77a67.png"> <img width="349" alt="image" src="https://user-images.githubusercontent.com/43795363/106790813-adbd1e00-6619-11eb-8737-fe05df08e538.png">

**New tab menu**
<img width="354" alt="image" src="https://user-images.githubusercontent.com/43795363/106791502-9cc0dc80-661a-11eb-8236-8c485e2143c3.png">

**Comment by topotropic** [comment]
![Group 1](https://user-images.githubusercontent.com/353960/111535387-55755200-8769-11eb-829c-3d74f3b811fe.jpg)

I believe we have the icons in the code base but let me know in case we need them. Thanks!

**Comment by kglazko** [comment]
Is it ok if I assign myself to this one and work on it @eliserichards ?

**Comment by gabrielluong** [comment]
In case this is helpful, [SyncPreferenceView](https://github.com/mozilla-mobile/fenix/blob/a31ce9bf671bc6c388f3bf4b94d95e55bb803388/app/src/main/java/org/mozilla/fenix/settings/SyncPreferenceView.kt) which is responsible for "Sign in to sync" in "Logins" will get you really far and fast.

**Comment by eliserichards** [comment]
Go for it @kglazko! 🚀

**Comment by kglazko** [comment]
Github isn't automatically linking to the WIP PR for some reason, can see progress here https://github.com/mozilla-mobile/fenix/pull/18609

**Comment by jonalmeida** [comment]
@kglazko @violasong : There is one more state of the 'Sign in to sync' menu that we may have overlooked (which I do not see in the designs linked). If an account needs to be re-authenticated we show propagate the error to the 'Settings' menu item.

With the 'Sign in' button now in the main menu, should the re-authenticated warning move from 'Settings' to 'Sign in to sync'? This could also be done as a follow-up. 🙂 

<img width="402" alt="Screen Shot 2021-04-02 at 2 56 30 PM" src="https://user-images.githubusercontent.com/1370580/113445440-e08a5500-93c3-11eb-83d9-3781077aaabf.png">


To reproduce this case for testing, you can pair with your device, then go to https://accounts.firefox.com/settings to manage your devices and remove the device from the account console. Re-open Fenix and you should be in the re-auth state.

**Comment by violasong** [comment]
Yes, makes sense for the warning icon to move to the Sign in item. Assuming this is a rarely seen warning, doing this as a follow-up seems fine to me.
