### ISSUE TITLE
[Feature] Add/Edit bookmark buttons in three-dot menu

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17797]
Meta: #17796
Followup to #17771 

UX point of contact: @violasong (Victoria)

Figma designs (bottom right, labeled "Final design"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

## Acceptance criteria
* Create a button labeled "Add" that allows users to add the current page as a bookmark directly from the menu
* Clicking on the ⭐ star should add the current tab as a bookmark
   * When the page is bookmarked, the button text should change to "Edit" 
* If the user is on a bookmarked page, clicking the ⭐ star again should remove the page from bookmarks without navigating away
* The "Edit" button should navigate the user to the bookmark edit screen
* The user should be able to navigate backwards from that screen

<img width="320" alt="image" src="https://user-images.githubusercontent.com/43795363/106789849-65513080-6618-11eb-9c8a-352e0b2b4baa.png"> <img width="321" alt="image" src="https://user-images.githubusercontent.com/43795363/106789941-8285ff00-6618-11eb-938c-0fe0e61d806d.png">

**Comment by mcarare** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/9840 for the AC part.

**Comment by mcarare** [comment]
@topotropic With the icons back in the menu, how will this item look? Wouldn't be redundant to have 2 star icons on the same row?

**Comment by violasong** [comment]
The updated look is in the figma file. This does end up with 2 star icons in the row, but I think the difference in icon styles makes this okay. CC: @vesta0 in case she has thoughts on this. If there's concern, I'll ask Bram to look into it.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/55994/111670504-24326b80-87d5-11eb-987c-6386bc3cc530.png">

**Comment by amedyne** [comment]
@brampitoyo Any thoughts on the star icons for bookmarks?

**Comment by brampitoyo** [comment]
@amedyne I’m happy to go with @violasong’s recommendation up above, of using an additional star for the action of adding and editing a bookmark:

> This does end up with 2 star icons in the row, but I think the difference in icon styles makes this okay.

**Comment by amedyne** [comment]
Thanks for providing the feedback @brampitoyo

**Comment by cadeyrn** [comment]
@mcarare Could the spacing between the icon and the text increased a bit? There is also more spacing in the mockup as in the implementation. Thanks!

**Comment by mcarare** [comment]
@violasong Can you please check the implementation and have it compared with the ones from Figma? And if there are any things that need to be changed, can you open an `implementation review` issue (like these https://github.com/mozilla-mobile/fenix/labels/implementation%20review)? Thank you!

**Comment by lobontiumira** [comment]
Verified on the debug build with AC: 75.0.20210405143037, a69f74ece, and GV 89.0a1-20210405094633 on Google Pixel (Android 10), Samsung Galaxy Note 8 (Android 9), and HTC 10 (Android 8).
Tapping on the "Add" option from the page's three-dot menu, adds the page to Bookmarks.
Tapping on the "Edit" option redirects the user to the editing page of the bookmark.

However, the mockup shows more spacing than the current implementation.
@violasong could you please review?

https://user-images.githubusercontent.com/40694158/113709949-c9ad7080-96eb-11eb-9197-53f95e250f96.mp4

![bookmark](https://user-images.githubusercontent.com/40694158/113709930-c619e980-96eb-11eb-813c-f40220010514.png)

**Comment by violasong** [comment]
Thanks for the screenshots!

Yes, there should be a 7px spacing between the star and the "Add/Edit" text - it does look like this is short some pixels. (FYI for the future, if you're signed into Figma you can use the Inspect mode to look at pixel measurements between elements)

The star icon should also be smaller - 19px instead of the standard 24px.

For dark mode, the purple text should be the main purple text color used in dark mode (Violet 40 - #ad3bff)

**Comment by eliserichards** [comment]
I will open up a followup issue to tackle those. Thanks @violasong! 👍

**Comment by eliserichards** [comment]
Followup filed: #18829
