### ISSUE TITLE
[Feature] Three-dot menu extensions item

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17799]
Meta: #17796
Followup to #17771 

UX point of contact: @violasong (Victoria)

Figma designs (bottom right, labeled "Final design"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

## Acceptance criteria
* We are changing the label of Addons in the three-dot menu to "Extensions" 
* This change is in both the main three-dot menu **and** the new tab menu
* States of the menu are as follows:
   * A user **has extensions installed** (it doesn't matter if they are enabled): see the right-pointing arrow
   * A user has **no extensions installed**: the right-pointing arrow should not be there, and the full menu item should be clickable
* Clicking on the the arrow should navigate the user to the list of **installed addons**
* Clicking on the main area of the menu item should navigate the user to the main addons list

---
**Addons installed**
<img width="343" alt="image" src="https://user-images.githubusercontent.com/43795363/106792558-e6f68d80-661b-11eb-8fbf-bb22b61e5a52.png">

**No addons installed**
<img width="338" alt="image" src="https://user-images.githubusercontent.com/43795363/106792646-fece1180-661b-11eb-971e-ead5fdc77eae.png">

**Comment by eliserichards** [comment]
Open question: are we changing the Addons Manager strings in all places?

**Comment by violasong** [comment]
I believe so! (But double-checking with @topotropic re: we are changing the label of Addons to "Extensions" everywhere)

**Comment by mcarare** [comment]
@violasong is there any decision regarding the "Report site issue" item? It will be placed in this menu, or it will be in the extensions menu (the functionality is provided by an extension)? This placement might influence the way we construct the menu in AC. Thank you!

**Comment by AndRo-Marian** [comment]
Why is there the Sig-in anyway?
There should not existing things that is not Frequently used...

**Comment by violasong** [comment]
"Report site issue" will be put in this menu for prerelease versions. (See [this issue](https://github.com/mozilla-mobile/fenix/issues/18032#issuecomment-788307613))

**Comment by mcarare** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/9873 for the AC changes.

**Comment by mcarare** [comment]
Note for QA: Label should still say add-ons, following decision made here: https://github.com/mozilla-mobile/fenix/issues/18534.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on the latest debug build downloaded on the 24th of March.
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)
