### ISSUE TITLE
Fix Activity.enterToImmersiveMode() deprecation in Android 11

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#17804]
[Docs](https://youtu.be/acC7SR1EXsI?t=161)

https://github.com/mozilla-mobile/fenix/blob/f4a7b4c066b98e8fd999268d702f4d5d81815021/app/src/main/java/org/mozilla/fenix/ext/Activity.kt#L18

Similar to https://github.com/mozilla-mobile/android-components/issues/8517

**Comment by Amejia481** [comment]
To address this issue we need to target android 11

**Comment by mcarare** [comment]
IMO we should remove this piece of code and replace it with the AC version of the extension, deprecation being handled in https://github.com/mozilla-mobile/android-components/issues/8517.

**Comment by Amejia481** [comment]
Yes, that will be ideal there is some discussion https://github.com/mozilla-mobile/android-components/issues/8517#issuecomment-702131591 about why we have the two different versions

**Comment by mcarare** [comment]
Can QA please check if there are any issues when using fullscreen, especially on devices with Android 11? Ping me if you need more details. Thank you!

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 3/17 with Google Pixel 4 XL (11) and Samsung Galaxy S7 (7), Samsung Galaxy S10+ (10).
Note that I didn`t encounter any issues regarding full-screen videos
