### ISSUE TITLE
Fix systemWindowInset deprecation in TabTrayDialogFragment

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#17807]
[Documentation](https://developer.android.com/reference/android/view/WindowInsets#getSystemWindowInsetLeft())

https://github.com/mozilla-mobile/fenix/blob/f4a7b4c066b98e8fd999268d702f4d5d81815021/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt#L247

**Comment by Amejia481** [comment]
Similar https://github.com/mozilla-mobile/android-components/issues/9552

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/18031.
