### ISSUE TITLE
 Fix Handler default constructor deprecation in SettingsFragment

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#17806]
[Documentation](https://developer.android.com/reference/android/os/Handler#Handler()) 

https://github.com/mozilla-mobile/fenix/blob/f4a7b4c066b98e8fd999268d702f4d5d81815021/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt#L338

https://github.com/mozilla-mobile/fenix/blob/f4a7b4c066b98e8fd999268d702f4d5d81815021/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt#L409

**Comment by CharlesAdam** [comment]
@Amejia481 This issue seems to be solved by the following PR #17803

**Comment by Amejia481** [comment]
Thanks, we can close this https://github.com/mozilla-mobile/fenix/commit/41f9388380ae54aabfefa377c903ab52c4544a2a
