### ISSUE TITLE
[Bug] Pull to refresh / dynamic toolbars triggered on about:blank

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17818]
## Steps to reproduce
- Load `about:blank` (empty page, doesn't display anything)
- Swipe up and down

### Expected behavior
Nothing would happen as the page is empty

### Actual behavior
- pull to refresh throbber is shown and never dismisses since the triggered refresh never completes.
- the toolbars are scrolling even though no page content was scrolled.

**Comment by Mugurell** [comment]
Seen on https://github.com/mozilla-mobile/fenix/issues/13304

**Comment by VitalyVPinchuk** [comment]
Hello!
Can this be an issue of gecko engine?

```
            // Ignore initial loads of about:blank, see:
            // https://github.com/mozilla-mobile/android-components/issues/403
            // https://github.com/mozilla-mobile/android-components/issues/6832
            if (initialLoad && url == ABOUT_BLANK) {
                return
            }
```

**Comment by Mugurell** [comment]
Seems indeed like a GeckoView/Gecko issue since we it returns to us that it handled the touch on that empty page and as a result we will animate the toolbars / pull to refresh throbber.
I think in this casse GV should send `INPUT_RESULT_UNHANDLED`(0).

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1692405

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
