### ISSUE TITLE
[Bug] Unable to upload any file

### ISSUE THREAD

**Issue by FuLygon** [mozilla-mobile/fenix#17817]
Cannot upload any files or photos

## Steps to reproduce
Using any site that support uploading, here i'm accessing Imgur and Google Drive in desktop mode and start uploading photos/files

### Expected behavior
Files & photos supposed to be uploaded

### Actual behavior
After selecting files/photos that I want to upload, website just doesn't responding or processing

### Device information
* Device vendor / model and Android version: Xiaomi Redmi Note 7 MIUI 12 Android 10
* Firefox for Android version: Nightly 210203 17:01
* Permission allowed: storage and camera
* Permission not allowed: mic and location

**Comment by ksy36** [comment]
We received similar reports in https://github.com/webcompat/web-bugs/issues/66676 and https://github.com/webcompat/web-bugs/issues/66647

**Comment by ksy36** [comment]
Looks like uploading with `<input type="file">` is not working, a reduced test case: https://codepen.io/ksy36/pen/PobZgxK

My device is Samsung Galaxy S5
Nightly 210205

**Comment by Amejia481** [comment]
The issue will be fixed when https://github.com/mozilla-mobile/fenix/pull/17874 lands

**Comment by Amejia481** [comment]
The fixed is already on nightly 210207 17:02 @FuLygon @ksy36, if the issue still reproducible?

**Comment by FuLygon** [comment]
great work, upload work again now, i will close this issue

**Comment by ksy36** [comment]
Works for me as well, thanks for looking into this!

**Comment by sflorean** [comment]
No issues on latest Nightly when uploading files, I will update the labels.
