### ISSUE TITLE
Target Android 11

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#17810]
All the issues that we have to address on Android 11:

- [x] https://github.com/mozilla-mobile/fenix/issues/17807
- [x] https://github.com/mozilla-mobile/fenix/issues/17808
- [x] https://github.com/mozilla-mobile/fenix/issues/17806
- [x] https://github.com/mozilla-mobile/fenix/issues/17804
- [ ] https://github.com/mozilla-mobile/fenix/issues/17805
- [x] https://github.com/mozilla-mobile/fenix/issues/17803

Similar to https://github.com/mozilla-mobile/android-components/issues/8519

**Comment by Mugurell** [comment]
Haven't tested but I think we also have to support https://developer.android.com/about/versions/11/privacy/package-visibility

**Comment by Amejia481** [comment]
> Haven't tested but I think we also have to support https://developer.android.com/about/versions/11/privacy/package-visibility

Thanks, is there any feature on Fenix that we should take a look at?

**Comment by Amejia481** [comment]
Thanks, we have for it :)  https://github.com/mozilla-mobile/android-components/issues/7827

**Comment by Amejia481** [comment]
As we already address most of the ticket, I think it's OK to close this, we can track the remaining work on #17805
