### ISSUE TITLE
Consider making "x" button from collections - open tabs, item larger

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#17826]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Add a new collection.
2. Tap on "View".
3. Open Collection.
4. Scan the page.

### Expected behavior
No suggestions are made.

### Actual behavior
![Screenshot_20210204_154522_com google android apps accessibility auditor](https://user-images.githubusercontent.com/58466444/106904248-a2deb800-6703-11eb-99a9-9e540cfe9218.jpg) 

###
 Device information
* Device vendor / model and Android version: Huawei P40 Lite (Android 11).
* Firefox for Android version: Beta 86.0.0-beta.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9618)

**Comment by gurleennsidhuu** [comment]
Hi. Can I work on this issue?

**Comment by 318anushka** [comment]
Hi!! I am an outreachy applicant and would like to take up this issue if free.

**Comment by lobontiumira** [comment]
Reproducible on Beta 88.0.0-beta.3 with Samsung Galaxy Note 8 (Android 9).

**Comment by VaishnaviShri** [comment]
Hi! I am an Outreachy applicant and would like to work on the issue if no one else is currently working on it.

**Comment by eliserichards** [comment]
Hi all! @gurleennsidhuu, I believe you have already been assigned an issue to work on.

@318anushka I will assign this issue to you

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812740

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
