### ISSUE TITLE
[Bug] searchable history not showing recently visited Twitter page

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#17831]
## Steps to reproduce
navigate to mobile.twitter.com/danielhowdon
close the tab
open a new tab and type mobile.twitter.com into the search bar
mobile.twitter.com/danielhowdon is not shown <---- incorrect behavior
go 3-dot-menu > History
mobile.twitter.com/danielhowdon is the first item in History <---- correct behavior

### Expected behavior
mobile.twitter.com/danielhowdon should show up quite high up the Search page since it's a recent History item

### Actual behavior
mobile.twitter.com/danielhowdon not shown in the Search page

### Device information

* Galaxy A40, Android 10.0
* Firefox for Android version: today's

![Screenshot_20210204-160224_Firefox Nightly](https://user-images.githubusercontent.com/40568887/106920504-0fa58280-6703-11eb-927e-2405f913908e.jpg)
![Screenshot_20210204-160157_Firefox Nightly](https://user-images.githubusercontent.com/40568887/106920511-12a07300-6703-11eb-9989-8b9b5c9a2940.jpg)

**Comment by fgfgffggg** [comment]
unable to reproduced, nightly 210203

![Screenshot_2021-02-06-12-55-39-660_org mozilla fenix](https://user-images.githubusercontent.com/78303735/107110477-c0825d80-687a-11eb-9eda-dceef4be5384.jpg)

**Comment by Cheap-Skate** [comment]
It now works for me. Thanks for checking.
