### ISSUE TITLE
Intermittent UI test failure - editCustomSearchEngineTest

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17847]
I'm seeing all recent CI tasks failing because of `editCustomSearchEngineTest`:
> androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/overflow_menu and has parent matching: has child: with text: is "Ecosia") 
..
at org.mozilla.fenix.ui.robots.SettingsSubMenuSearchRobot.openEngineOverflowMenu(SettingsSubMenuSearchRobot.kt:85) 

Full error - https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8112666704190535244/executions/bs.1e44345a13c02e11/testcases/2/test-cases
 
@sv-ohorvath @AndiAJ

**Comment by AndiAJ** [comment]
Failed 2x with: 
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/overflow_menu and has parent matching: has child: with text: is "Ecosia")`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8112666704190535244/executions/bs.690d65dfae31e30a/testcases/2/test-cases)

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8112666704190535244/executions/bs.1e44345a13c02e11/testcases/2/test-cases)

**Comment by AndiAJ** [comment]
Failed again 2x with:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/overflow_menu and has parent matching: has child: with text: is "Ecosia")
`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6826102943786931667/executions/bs.5b0d6b6704024895/testcases/2/test-cases)

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6826102943786931667/executions/bs.28c01eb949c92d1b/testcases/2/test-cases)

**Comment by sv-ohorvath** [comment]
Failures started on PRs from 12hrs ago. Seems to be caused by the latest AC update from 15hrs ago: https://github.com/mozilla-mobile/fenix/commit/378e68f3a63b644416635f09dfd185f7816c948c
Will disable the test and the PRs can be reopened.

**Comment by sv-ohorvath** [comment]
There is a network connection error on Firebase, that occurs constantly on this test: 
![editCustomSearchEngine](https://user-images.githubusercontent.com/4037709/107024648-fa872d00-67b0-11eb-826b-aaec07008aa3.png)

**Comment by sv-ohorvath** [comment]
My theory is that Ecosia blocked repeated calls from the same source (there is a call made to Ecosia when we verify the search engine string), similar to what Google does when it detects automatic searches or logins. I deleted the test since it is based on 3rd party search providers which I can't replace.

**Comment by rpappalax** [comment]
Next steps: 
1. re-enable to see if working again
2. re-try with a different search provider

**Comment by Mugurell** [comment]
Saw in https://github.com/mozilla-mobile/fenix/pull/21392/checks?check_run_id=3741007613 to still be intermittently failing

```
java.lang.IllegalArgumentException: Can't scroll to index 5, it is out of bounds [0, 0)
at androidx.compose.foundation.lazy.LazySemanticsKt$lazyListSemantics$1$3.invoke(LazySemantics.kt:78)
at androidx.compose.foundation.lazy.LazySemanticsKt$lazyListSemantics$1$3.invoke(LazySemantics.kt:77)
at androidx.compose.ui.test.ActionsKt$performScrollToIndex$2.invoke(Actions.kt:145)
at androidx.compose.ui.test.ActionsKt$performScrollToIndex$2.invoke(Actions.kt:144)
at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2163)
at android.os.Handler.handleCallback(Handler.java:873) 
```

**Comment by Mugurell** [comment]
Also https://github.com/mozilla-mobile/fenix/pull/21564/checks?check_run_id=3743322944 - https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8857595597330965504/executions/bs.d7307b38d014d7c/test-cases

**Comment by sv-ohorvath** [comment]
@Mugurell there is a new bug logged for the new failures: https://github.com/mozilla-mobile/fenix/issues/21540
