### ISSUE TITLE
[Bug] Private Mode screenshots possible via Tab Tray Overviews (2)

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17855]
Similar to https://github.com/mozilla-mobile/fenix/issues/17854 and https://github.com/mozilla-mobile/fenix/issues/12453 one can unknowingly allow the list of opened private tabs screenshotted / recorded.

## Steps to reproduce
- Have Settings -> Private browsing -> Allow screenshots in private mode disabled
- have a few normal tabs and a few private tabs opened
- open one normal tab / got to normal tabs homescreen
- open tabs tray -> choose to create a new private tab
- try taking screenshots of all the tabs shown in tabs tray, incl private ones.

### Expected behavior
A message from Android saying that screenshots are not allowed

### Actual behavior
Screenshots are possible

### To note
When putting the app in background and resuming the FLAG_SECURE gets set (not all the times) so now one cannot take record the screen while in private mode.

Video showing these cases (use the android message / screenshot as indicators of when screenshots are blocked or not):

https://user-images.githubusercontent.com/11428869/107045427-2e248000-67ce-11eb-81dc-17cf98480b44.mov

**Comment by softvision-miralobontiu** [comment]
This is not fixed entirely, I was able to take a screenshot in private browsing when the keyboard is trigerred, as it can be seen in the video below:

https://user-images.githubusercontent.com/40694158/107219007-20166f80-6a19-11eb-83b1-8220f649387c.mp4

Environment:
* 2/8 Nightly build
* Samusng Galaxy Note 8 (Android 9)

**Comment by softvision-miralobontiu** [comment]
Reproducible on Beta 86.0.0-beta.5, and 2/15 Nightly with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by softvision-miralobontiu** [comment]
Reproducible on RC 86.1.0 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by lobontiumira** [comment]
This issue still reproduces on the 3/22 Nightly build with Samsung Galaxy Note 8 (Android 9).
I was able to take a screenshot in private browsing when the keyboard is trigerred.

**Comment by lobontiumira** [comment]
Reproducible on Beta 88.0.0-beta.6 with OnePlus 5T (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.0 with Xiaomi Mi 8 Lite (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on RC 88.1.4 with Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on Beta 90.0.0-beta.5 with Google Pixel (Android 10).

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/17854#issuecomment-871984799

**Comment by codrut-topliceanu** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/pull/10552

**Comment by lobontiumira** [comment]
Reproducible on 90.1.0 RC build with OnePlus 5T (Android 10).

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly (91.0a1 2021-07-09T05:07:18.274).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).
