### ISSUE TITLE
[Bug] Screenshot is not blocked when starting the app

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17854]
The `Settings -> Private browsing -> Allow screenshots in private mode` is not enforced when starting the app.
If putting the app to background and resuming it (in most cases) the screenshots are blocked - as it should have happened from the beginning.

## Steps to reproduce
Have `Settings -> Private browsing -> Allow screenshots in private mode` disabled
1)  Open the app and go tot the private tabs screen
    - Optional step: Open the list of open tabs in tabs tray
    - Take a screenshot
  
2) Come back to app homescreen from a private tab
    - Optional step: Open the list of open tabs in tabs tray
    - Take a screenshot
  
  

### Expected behavior
- A message from Android saying that screenshots are not allowed

### Actual behavior
- Screenshots are possible

### To note
When putting the app in background and resuming the FLAG_SECURE gets set (not all the times) so now one cannot take record the screen while in private mode.

Video showing these cases (use the android message / screenshot as indicators of when screenshots are blocked or not):

https://user-images.githubusercontent.com/11428869/107044110-88bcdc80-67cc-11eb-956c-350c1d52f66d.mov

**Comment by sflorean** [comment]
Verified as fixed on Nightly 2/10 with LG G7 (Android 8.1.0)

**Comment by Nickoriginal** [comment]
Still reproducible in Firefox 89.1.1, 90.0.0-beta.6 and Nightly 91.0a1 (Build #2015819403)

https://user-images.githubusercontent.com/85299944/124075938-42536d00-da4e-11eb-80a5-518c191b4e4b.mp4

https://user-images.githubusercontent.com/85299944/124081312-0c18ec00-da54-11eb-9b42-6ac73fa318d2.mp4

https://user-images.githubusercontent.com/85299944/124081329-13d89080-da54-11eb-9cd6-23d45c84af4a.mp4

**Comment by Nickoriginal** [comment]
@Mugurell, you can confirm this bug on your device(s), and, if possible, reopen it?

**Comment by Mugurell** [comment]
I see that screenshots are blocked in the browser (which this ticket was for)
but not in the tabs tray, for which we have an open ticket - https://github.com/mozilla-mobile/fenix/issues/17855

**Comment by Nickoriginal** [comment]
Thanks!
