### ISSUE TITLE
Add a button to access https://addons.mozilla.org (AMO) in Menu -> Addons

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#17860]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Lot's of users complain that they could "only" install 10 recommended add-ons in Menu -> Add-ons, and they said Chrome is better if Firefox couldn't install add-ons they want. So I hope Fenix could add a button to access AMO. 
### How do you know that this problem exists today? Why is this important?
Lot's of users complain in app store. Some of them says that they don't want to use Firefox if it couldn't install addons they want. 
### Who will benefit from it?
Everyone.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9631)

**Comment by Kethen** [comment]
yeah it's horrible when the UI change took away my extensions, tossing them info "not available yet" cept for ublock origin

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814127

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
