### ISSUE TITLE
[Bug] Memory Leak in SavedLoginsFragment

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#17868]
STR: 
Click in between logins list and login auth, pause app at logins list 

![Screenshot_20210205-130037](https://user-images.githubusercontent.com/25442310/107084671-95cdd180-67b4-11eb-889a-5ea4f4ba0424.png)

**Comment by CharlesAdam** [comment]
@ekager I've been able to reproduce this bug and will search into it

**Comment by CharlesAdam** [comment]
This issue was dealt with on this PR: #18058
