### ISSUE TITLE
[Feature] Add three-dot menu icons back

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17872]
Meta: #17796 
Followup to #17771 
UX point of contact: @violasong (Victoria)

Figma designs (bottom right, labeled "new tab menu"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

## Acceptance criteria

#17771 removed some icons on the three-dot menu, but the designs have changed and we are now keeping the icons. This issue is to add those icons back in. 

~Add the ability to remove toolbar menu icons in menu items. This should be reflected in the fenix home menu and the main three-dot menu.~
See files in AC:
*  `BrowserMenuImageText`
* `BrowserMenuHighlightableItem`
* `BrowserMenuImageSwitch`
* etc

**Old design** 
<img width="307" alt="image" src="https://user-images.githubusercontent.com/43795363/107089494-560ee600-67c4-11eb-9b4e-ccd0abf89c6b.png">

**Comment by sheikh-azharuddin** [comment]
Waiting for this to finally switch to some other browser!

**Comment by ekager** [comment]
@sheikh-azharuddin this is not an appropriate comment. This is your final warning. Next step is banning from participation. Please read up on [the CPG](https://www.mozilla.org/en-US/about/governance/policies/participation/) for what behavior will not be tolerated in this repo  and feel free to file specific issues with pain points you are having if you can do so respectfully.

**Comment by mcarare** [comment]
@eliserichards Is this issue still valid?

**Comment by sheikh-azharuddin** [comment]
The bookmark icon on tabs 3 dot menu is not matching with home screen 3 dot menu bookmark icon
