### ISSUE TITLE
[Bug] esni option is not available

### ISSUE THREAD

**Issue by privacymatter0** [mozilla-mobile/fenix#17877]
[comment]: # into about:config framework I can't find esni option no more in Firefox 
Nightly 210205 17:58 (Build #2015791571)
 on Huawei P smart Z, Android 10

**Comment by cadeyrn** [comment]
This is expected: https://blog.mozilla.org/security/2021/01/07/encrypted-client-hello-the-future-of-esni-in-firefox/

**Comment by Mugurell** [comment]
ESNI was replaced with ECH.
Please refer to the above link for more information (including how to turn on ECH).
