### ISSUE TITLE
Enable three-dot menu design changes in Nightly

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17870]
Meta: #17796

Enable feature flags for the toolbar and home screen three-dot menu changes in Nightly.

## For QA
Please ensure that you can see the new menu on Nightly (release and beta should still show the old menu) for both new tab menu and main menu

**Comment by eliserichards** [comment]
Confirmed with @amedyne that we can enable this now.

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/9 Nightly build with Samsung Galaxy Note 8 (Android 9).
The design changes are available and functional.
