### ISSUE TITLE
Full screen display of Samsung Galaxy note20 ultra Android 11 video is incomplete[Bug]

### ISSUE THREAD

**Issue by shenzhenMirren** [mozilla-mobile/fenix#17879]
85.1.1 (Build #2015790185)
AC: 0.0.1, 440ec37e1
GV: 85.0.1-20210127184413
AS: 67.2.0
![图片](https://user-images.githubusercontent.com/24805209/107108371-51087000-6872-11eb-9454-056a42d6e6cc.png)
![图片](https://user-images.githubusercontent.com/24805209/107108380-6087b900-6872-11eb-8887-5a5da626bdf3.png)

**Comment by sflorean** [comment]
@shenzhenMirren thank you for filing this issue! I was able to reproduce it on RC build 87.0.0-rc.1 but not on latest Nightly build 3/30 with Samsung Note 10 (Android 11). 
Could you please try to check on Nightly, to see the results for you?

Link used for testing: http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5 - html5 video.
Not reproducible on Chrome.

**Comment by shenzhenMirren** [comment]
test video
https://user-images.githubusercontent.com/24805209/113009734-ccb7d680-91aa-11eb-994e-dd8e64f3e484.mp4

**Comment by amedyne** [comment]
@shenzhenMirren There have been recent improvements for this. Can you validate if you are still seeing this problem? Thank you!

**Comment by shenzhenMirren** [comment]
> @shenzhenMirren There have been recent improvements for this. Can you validate if you are still seeing this problem? Thank you!

Hi, I tested on Firefox nightly 92.0a1，this problem still exists. this problem may have something to do with the navigation bar. because I use the button, the display is normal, but when I use the swipe gestures, the display is abnormal

**Comment by shenzhenMirren** [comment]
Maybe I should say that this problem occurs when the swipe gesture navigation bar is turned on

**Comment by amedyne** [comment]
@shenzhenMirren Thank you for providing more details.

**Comment by amedyne** [comment]
@Mugurell Do you think any of the outstanding open issues on Toolbar relates to this?

**Comment by Mugurell** [comment]
> > @shenzhenMirren There have been recent improvements for this. Can you validate if you are still seeing this problem? Thank you!
> 
> Hi, I tested on Firefox nightly 92.0a1，this problem still exists. this problem may have something to do with the navigation bar. because I use the button, the display is normal, but when I use the swipe gestures, the display is abnormal

Can you please post a link to a video you're seeing this issue with?
And also all the steps needed to reproduce this?  Not sure what "use the button" / "use the swipe gestures" means and how that applies.

Alternatively it would be great if you could test on `geckoview_example.apk` from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-debug) which can be seen as a stripped down version of the app that can allow us to ignore some potential causes.

**Comment by Mugurell** [comment]
These look great, thank you! (the segments really helped as the one-piece video didn't open).
Tried reproducing with the link from https://github.com/mozilla-mobile/fenix/issues/17879#issuecomment-810215459 but I couldn't.
I'm seeing in your video that the issue reproduces with the video as fullscreen in portrait.
Wondering if the issue also reproduces in landscape?

Thinking that the display form factor could impact this (as the Note 20 ultra has a rather unusual 3088×1440 resolution) I tried opening https://www.youtube.com/watch?v=FoMlSB6ftQg on a OnePlus with a 3120x1440 resolution but everything seems okay. 
So I'm wondering if it has anything to do with the website containing the videos.

**Comment by shenzhenMirren** [comment]
I added two new videos.
In the 1080p video, there are some that can be displayed normally after refreshing,
In the 1440p video, click the full screen quickly after refreshing, and a white edge will appear,
Maybe it has something to do with whether the video is loaded or not?


https://user-images.githubusercontent.com/24805209/129066643-d16437cf-12b7-46c0-8576-9eec3334672b.mp4


https://user-images.githubusercontent.com/24805209/129066658-bb96d302-eff6-4a37-8d2a-4d7dda5e4453.mp4

**Comment by shenzhenMirren** [comment]
The video I played yesterday

https://user-images.githubusercontent.com/24805209/129068663-6a9854b8-8f8e-423a-ba08-96517f0e7a22.mp4


https://user-images.githubusercontent.com/24805209/129068688-78b43fa0-b7de-4bc0-88c2-235dcadb06b6.mp4

**Comment by shenzhenMirren** [comment]
this is in HUAWEI ARS-AL00,
firefox 91.1.0

https://user-images.githubusercontent.com/24805209/129131386-6c7cfa8f-7911-4ba0-8c3f-f78db48c5d88.mp4


https://user-images.githubusercontent.com/24805209/129131401-01118899-395c-4ae7-a5cb-97287930b35f.mp4

**Comment by shenzhenMirren** [comment]
![mmexport1628738591930](https://user-images.githubusercontent.com/24805209/129133748-a2f04177-938b-4b67-8af0-99b8960eb9f7.jpg)

video 1.
https://user-images.githubusercontent.com/24805209/129134703-c9e8fccc-08b2-490d-9299-ba88475ecd6b.mp4

video 2.

https://user-images.githubusercontent.com/24805209/129134940-a25ed5de-38f2-4390-8cc8-bc4b06f70ea0.mp4


video 3.

https://user-images.githubusercontent.com/24805209/129134967-49ecc1ac-387c-4a89-aeb6-947082e947d9.mp4

**Comment by shenzhenMirren** [comment]
@Mugurell 
Hi, today I tested Huawei and Redmi phones on Firefox 91.1.0. This problem occurs as long as there is no navigation bar

**Comment by shenzhenMirren** [comment]
> Thank you for this but I think that the problem is tied with to the website hosting the videos.
> Can you share the link of the video for which you've seen this issue?

I don't think it has anything to do with the website. It should be that the system doesn't adapt to mobile phones with full screen gestures

**Comment by Mugurell** [comment]
For me, when testing on YouTube or Dailymotion everything seems to work as expected


https://user-images.githubusercontent.com/11428869/129215060-58e5bfb2-99c3-4210-ada3-82680a2a9a43.mp4

**Comment by shenzhenMirren** [comment]
The video you tested did not hide the navigation bar（sscreen indicator）
You hide the navigation bar and test again. If it is still normal
What model is your oneplus? I'll use the same model as you tomorrow and test it with several websites. I tested three brands of mobile phones

> For me, when testing on YouTube or Dailymotion everything seems to work as expected
> ScrobberBar.mp4

**Comment by Mugurell** [comment]
With gesture navigation activated in Android settings on a Samsung S9 with Android10, Pixel 3 with Android 12 and OnePlus 7T Pro with Android 12 I tested on Youtube and Dailymotion and everything seems okay.

Please provide a link to the videos that you're seeing issues with to be able to reproduce on our side.

**Comment by shenzhenMirren** [comment]
this is my test links

https://wx.fuyinwang.com/share/list.html?msg=eyJmdSI6IjdyMDA4NjQ1OWYzNzllZDgxcCIsImZpIjoiVjE2MDYzOTIyMDI0NjQ1NiIsImZ0IjowLCJmbCI6IjkxOSIsInNxIjowfQ==

**Comment by shenzhenMirren** [comment]
I only use one video address test now,
This is the test address: http://res.zhuneiyun.com/temporary/firefox_test_video.mp4
Here are the videos of my three mobile phone tests

https://user-images.githubusercontent.com/24805209/129301876-83912c1a-da35-4485-8f4e-61bf335d4f2b.mp4

**Comment by shenzhenMirren** [comment]
That's all I can offer
github video:

https://user-images.githubusercontent.com/24805209/129302310-463c78bf-ef55-4158-abb3-61f5a9f81287.mp4

**Comment by Mugurell** [comment]
Thank you for this.
I think this is rather a GeckoView issue so I'll move the ticket on Bugzilla for more investigation.
Please follow the discussion there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1725642

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
