### ISSUE TITLE
[Bug] Wrong tab selected and reloaded when opening a tab from collections

### ISSUE THREAD

**Issue by ubrainlessgit** [mozilla-mobile/fenix#17889]
Firefox android beta collections.

Hi, i think collections is a wonderful feature and if it were just synced across devices it would be perfect. A bug and some REALLY overlooked features below:

Bug: in latest version collections dont work. Clicking on a tab opens the previous tab in your list of open tabs. 

Missing features which cripple the use of collections: 

1. There is no ' long press to open in new tab option'
2. You cant open in new private window and CANT EVEN access collections in private windows
3. Once u have a tab open, you cant access your collections anywhere eg the hamburger menu at bottom right should have a way to access your collections but only has option to save to collection. U have to open a new blank tab and then navigate to collections

Samsung galaxy s7
86.0.0-beta.2 (Build #2015790811)
AC: 72.0.5, 4f36d0f93
GV: 86.0-20210131185630
AS: 67.2.0

**Comment by csadilek** [comment]
Thanks for filing. Changing this ticket to specifically address the bug you filed. You have https://github.com/mozilla-mobile/fenix/issues/17890 to cover feature requests. Please file individual tickets for feature requests and bugs.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 2/11 and Beta 86.0.0-beta.4 from 2/11 with Samsung Galaxy Tab S3 (Android 8), Sony Xperia Z5 Premium (Android 7.1.1), OnePlus 6T (Android 9).

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on RC 86.1.0-rc.1 and Beta 86.0.0-beta.5.
### Devices used:
- Huawei MediaPad M3 (Android 7.0)
- OnePlus 6T (Android 9)
