### ISSUE TITLE
Inability to make changes in about:config

### ISSUE THREAD

**Issue by gallegonovato** [mozilla-mobile/fenix#17888]
Good afternoon:

First of all thank you for all your work and effort.

I am trying to make changes to obout:config and have them saved after closing the browser. But it is impossible, they always return to their original state.

For example entries related to Google or mozilla among others.

I also tried the user.js

https://git.nixnet.xyz/Narsil/mobile_user.js and https://github.com/arkenfox/user.js

But it is impossible.

The truth is that there are several, some of mozilla telemetry, others related to google, etc . . . For example

browser.shell.checkDefaultBrowser

Disable Activity Stream feeds
Disable other sync settings

browser.safebrowsing.provider.google.advisoryURL", “”);
user_pref(“browser.safebrowsing.provider.google.pver”, “”);
user_pref(“browser.safebrowsing.provider.google.advisoryName”, “”);
user_pref(“browser.safebrowsing.provider.google.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.google.lastupdatetime”, “”); 
user_pref(“browser.safebrowsing.provider.google.lists”, “”);
user_pref(“browser.safebrowsing.provider.google.nextupdatetime”, “”); 
user_pref(“browser.safebrowsing.provider.google.reportMalwareMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google.reportPhishMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google.reportURL”, “”);
user_pref(“browser.safebrowsing.provider.google.updateURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.advisoryName”, “”);
user_pref(“browser.safebrowsing.provider.google4.advisoryURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.lastupdatetime”, “”); 
user_pref(“browser.safebrowsing.provider.google4.lists”, “”);
user_pref(“browser.safebrowsing.provider.google4.nextupdatetime”, “”); 
user_pref(“browser.safebrowsing.provider.google4.reportMalwareMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.reportPhishMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.reportURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.updateURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.dataSharing.enabled”, false);
user_pref(“browser.safebrowsing.provider.google4.dataSharingURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.pver”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lastupdatetime”, “”); 
user_pref(“browser.safebrowsing.provider.mozilla.lists”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lists.base”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lists.content”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.nextupdatetime”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.pver”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.updateURL”, “”);
user_pref(“browser.safebrowsing.reportPhishURL”, “”);
user_pref(“browser.safebrowsing.features.cryptomining.update”, false);
user_pref(“browser.safebrowsing.features.fingerprinting.update”, false);
user_pref(“browser.safebrowsing.features.malware.update”, false);
user_pref(“browser.safebrowsing.features.pishing.update”, false);
user_pref(“browser.safebrowsing.features.trackingAnnotation.update”, false);
user_pref(“browser.safebrowsing.features.trackingProtection.update”, false);
// -------------------------------------

Etc…

Thanks for your time and help.

**Comment by cadeyrn** [comment]
There is "activity stream" in Firefox for Android, so why do you want to change this setting? Same for browser.shell.checkDefaultBrowser, that's a Desktop only setting and has nothing to do at all with Firefox for Android.

For SafeBrowsing see #14163, you can't disable this security feature in the current version of Firefox.

**Comment by alicavus** [comment]
about:config is not accessible in production builds but it is available from beta and nightly builds. I have not tried user.js method, bc my phone is not rooted.

**Comment by alicavus** [comment]
The issue is dupplication of several others, fresh one: #17154

**Comment by gallegonovato** [comment]
Good afternoon @cadeyrn 

With :

Disable Activity Stream feeds
Disable other sync settings

I am referring to the section with those names in the user.js I am talking about. You can see those sections in:

https://git.nixnet.xyz/Narsil/mobile_user.js and https://github.com/arkenfox/user.js

And then all the ones that have to do with Google don't save the change either. You try to change it and when you close the browser it goes back to its original state.

Those entries are:


browser.safebrowsing.provider.google.advisoryURL", “”);
user_pref(“browser.safebrowsing.provider.google.pver”, “”);
user_pref(“browser.safebrowsing.provider.google.advisoryName”, “”);
user_pref(“browser.safebrowsing.provider.google.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.google.lastupdatetime”, “”);
user_pref(“browser.safebrowsing.provider.google.lists”, “”);
user_pref(“browser.safebrowsing.provider.google.nextupdatetime”, “”);
user_pref(“browser.safebrowsing.provider.google.reportMalwareMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google.reportPhishMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google.reportURL”, “”);
user_pref(“browser.safebrowsing.provider.google.updateURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.advisoryName”, “”);
user_pref(“browser.safebrowsing.provider.google4.advisoryURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.lastupdatetime”, “”);
user_pref(“browser.safebrowsing.provider.google4.lists”, “”);
user_pref(“browser.safebrowsing.provider.google4.nextupdatetime”, “”);
user_pref(“browser.safebrowsing.provider.google4.reportMalwareMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.reportPhishMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.reportURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.updateURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.dataSharing.enabled”, false);
user_pref(“browser.safebrowsing.provider.google4.dataSharingURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.pver”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lastupdatetime”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lists”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lists.base”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lists.content”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.nextupdatetime”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.pver”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.updateURL”, “”);
user_pref(“browser.safebrowsing.reportPhishURL”, “”);
user_pref(“browser.safebrowsing.features.cryptomining.update”, false);
user_pref(“browser.safebrowsing.features.fingerprinting.update”, false);
user_pref(“browser.safebrowsing.features.malware.update”, false);
user_pref(“browser.safebrowsing.features.pishing.update”, false);
user_pref(“browser.safebrowsing.features.trackingAnnotation.update”, false);
user_pref(“browser.safebrowsing.features.trackingProtection.update”, false)


@alicavus Don't take this the wrong way but if you can't put the user. Or try to modify and see if you can change those entries. You don't know what I mean. Since you get to have telemetry with google for example.

It is just a help to make fennix much, much better. And to continue with the philosophy of what open source is and what it was and was. And they are the experience of all the users that have been using Mozilla browsers for years. In the face of competition that is impossible to modify and have more privacy and so on.

Thanks for your help.And all your time.

**Comment by cadeyrn** [comment]
> With :
>
> Disable Activity Stream feeds
> Disable other sync settings
>
> I am referring to the section with those names in the user.js I am talking about. You can see those sections in:
>
> https://git.nixnet.xyz/Narsil/mobile_user.js and https://github.com/arkenfox/user.js

It's always a bad idea to blindly apply such files without knowing what you are doing. This can cause real harm. Again: There is no "activity stream feed" in Firefox for Android. And if you don't want to sync just don't use the sync feature.

I don't know why you repeated all the SafeBrowsing settings from your first comment after I already told you that it's not possible to disable this security feature in the current version of Firefox for Android.

**Comment by gallegonovato** [comment]
Good afternoon:

The entries in about:config of google also cannot be disabled? Or the ones that create telemetry either from Mozilla, google?

Previously I always removed them. And did not break anything in the browser.

I have even been using user.js for a long time. Before Quindecim or Chef-Koch and never had any problems.

I even tried with warden application ( https://forum.xda-developers.com/t/app-5-0-warden-app-manager.4122227/ ) or fdroid app manager . And fennix brings google trackers for example and loggers.

Best regards

Pd: I take the opportunity, if I may. To see if it is possible that fennix of origin includes search engines like seax, startpage or metager. Instead of twitter or wikipedia for example. Since you can search inside those webs or in them with any search engine. And the other three that I mention are so to speak more secure or in line with the privacy of our searches.

**Comment by cadeyrn** [comment]
> Or the ones that create telemetry either from Mozilla, google?

There is a visible option to disable telemetry, no need for about:config. There is no "telemetry from Google" in Firefox.

**Comment by kbrosnan** [comment]
This is not a supported workflow. There are prefs that GV/Fenix own and are not overwriteable. There are a lot of prefs that will just not work because they change UI behavior on desktop. about:config is use at your own risk and little to no support
