### ISSUE TITLE
[webcontent] amazon prime video site videos does not play in full screen

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17880]
## Site with issue and any steps to reproduce
Open prime video site https://www.primevideo.com/region/eu
Sign in with your account
Switch to desktop mode
Play any video
Click full screen button 
Video is playing but all contents messed up. Controls are zoomed out and not working. Also observing green pixellation. 

One other thing noticed device is heating up 
### Expected behavior
Video should play properly like other chromium browsers 

### Actual behavior
Video plays but not showing properly.. Green pixellation and other stuff 

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?

Works fine in chromium browsers. 

### Device information

* Android device: ? Rog3 A10
* Fenix version: ? Latest nightly 

![Screenshot_20210206-125152940](https://user-images.githubusercontent.com/58127841/107112015-80bb7600-687a-11eb-8e12-096ba2b4df7d.jpg)

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724453

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by amedyne** [comment]
Moving to bugzilla. Tested on Nightly 92.0a1 and this is still a problem.
