### ISSUE TITLE
[Bug] visual glitch with height 100% after exiting fullscreen 

### ISSUE THREAD

**Issue by TeeTeeHaa** [mozilla-mobile/fenix#17884]
## Steps to reproduce

Open the [attached HTML file](https://github.com/mozilla-mobile/fenix/files/5937634/index.html.txt) with Firefox Mobile on Android.
Tap anywhere to request fullscreen.
Tap again to exit fullscreen.

### Expected behavior

Visible area of the website is always completely blue (meaning that `height: 100%` in CSS always is exactly the visible height of the website).

### Actual behavior

Top 90% (approximate) of visible area is blue, bottom 10% of visible area is red (meaning that height is calculated wrong). This happens after exiting fullscreen and it stays like this even after reloading the website.

### Device information

* Device vendor / model and Android version: Nokia 5 (TA-1053) with Android 9 security update October 2020
* Firefox for Android version: 85.1.1 (Build #2015789955)

### Note: Expected behavior in the following browsers

* Firefox 85.0.1 (64-bit) on Windows
* Chromium 87.0.4280.67 (Developer Build) (64-bit) on Windows
* Chrome 88.0.4324.141 on Android

### Note: Maybe related bugs

* https://bugzilla.mozilla.org/show_bug.cgi?id=808136
* https://bugzilla.mozilla.org/show_bug.cgi?id=712225

**Comment by s-ankur** [comment]
Also Related: https://github.com/mozilla-mobile/fenix/issues/16140

**Comment by TeeTeeHaa** [comment]
This seems to be fixed: When I open the attached HTML file in Firefox 89.1.1 (for Android) it now shows the expected behavior.
According to @Mugurell this is because of https://github.com/mozilla-mobile/fenix/issues/10686 which was closed on Feb 9 2021.
Thanks! :+1:
