### ISSUE TITLE
FNX3-15817 ⁃ Remove garbage icon from address bar in private browsing

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1788]
### Steps to reproduce
1. open at least two websites in the private mode
1. press the garbage icon on the left side of the address bar

### Actual behavior
All Tabs are removed from private session.

### Expected behavior
In #1751 a garbage icon was added to the the left side of the address bar to delete browsing history in private mode. While I like the idea of having this icon to remove the tab from the private session it's totally unexpected that this button removes _all_ tabs from the private session. Even worse: There is neither an explanation nor a confirmation dialog nor a way to undo the action so it's a data loss issue.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision c8061bd9af840d13ccf43bc85a2fbd153ec9a4a1

**Comment by ekager** [comment]
This isn't a bug because this is inheriting from Focus behavior and was defined in #1751, but we could add a snackbar with possible action to undo? I am tagging for UX Feedback.

**Comment by cadeyrn** [comment]
> this is inheriting from Focus behavior

That's true but the truth is also that multi tab browsing in Focus is a very hidden feature and you have to long press on a link on a website to get a second tab. That's why in practise you almost always have no more than one single tab in Focus, so the situation is a little different. ;-)

**Comment by kbrosnan** [comment]
Closing individual tabs creates a bit of complexity. The expectation from the user is that the tab data is gone but in Fenix the data would be persisted until all the private browsing tabs are closed.

**Comment by topotropic** [comment]
I agree that it's misleading and I doubt that adding a undo Snackbar is going to help because it's after the fact: people tap it, might have wrong expectation about the consequences of their action, ignore the snackbar, go to home and are surprised that all their tabs are gone. A dialog along the lines of "Clear all tabs and date" (yes/cancel) might be helpful if we want to keep it so that people can anticipate what's going to happen. I'd question if we need it for MVP though – I definitely see the advantages but there are also issues with the current implementation.  I'm missing some background knowledge here so maybe @brampitoyo  or @shorlander  can make a call whether to remove it for now or go with a dialog. Thanks!

**Comment by ekager** [comment]
I think the dialog would definitely give users more clarity but also it will then require 2 taps to clear private your private browsing sessions.

**Comment by yoasif** [comment]
I think that this button isn't required at all. Focus is purpose made for private browsing, so I think it makes sense there, but Fenix feels more like Fennec or other heavyweight browsers to me, so it doesn't feel right to have this button right in the toolbar, especially an action so destructive. 

I'd much prefer a persistent notification - I could have sworn that Focus had this, but it doesn't seem to be present in my testing. 

In any case, Kiwi has it, and it allows users to quickly close all private tabs by swiping in the notification area and a single tap.

**Comment by kbrosnan** [comment]
Add a [x] never ask again?

**Comment by yoasif** [comment]
Added #2053 for a persistent notification to close all private tabs.

**Comment by topotropic** [comment]
I discussed this with @shorlander and we want to remove the garbage icon. 

Reasoning: 
- the interaction is misleading, it's not clear what's going to happen when people tap the garbage icon
- the icon slides into the place of a different button, increasing the chance for accidental triggering (we break muscle memory)
- there's a prominent button on home to clear tabs and data, it's not clear why we need an additional one on site level

**Comment by kbrosnan** [comment]
@vesta0 please set a new priority.

**Comment by vesta0** [comment]
@shorlander @topotropic agree that we should remove this. We may later re-evaluate whether we want to add an option to erase data on a site level but at this point it's not required.

**Comment by ekager** [comment]
Closed by #2125
