### ISSUE TITLE
[Bug] Website scrolled up when returning from fullscreen video with dynamic top toolbar

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17899]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Have the toolbar set at dynamic and set to be on top, fully expanded
- Access a website which allows playing videos in fullscreen
- Enter fullscreen
- Exit fullscreen

### Expected behavior
- The website shows the same as before entering fullscreen

### Actual behavior
- The website is scrolled to the top (with probably the size if the toolbar)

### Build info
Today's Nightly.
Possibly a regression from https://github.com/mozilla-mobile/fenix/issues/10686

**Comment by Mugurell** [comment]
The issue seems to happen only when pressing the back button to exit fullscreen, and even then not all the time.
Seems like upon showing again the toolbar the custom behavior that should place the browser immediately below the toolbar doesn't have it's [onDependentViewChanged](https://github.com/mozilla-mobile/android-components/blob/acb4ca9687a70542f7f39cf1db747e73dcfe5967/components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBrowserToolbarBehavior.kt#L75) method called and so it remains expanded to fill the screen like we previously set when entering fullscreen.

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce this issue on 2/23 Nightly build, on Beta 87.0.0-beta.1, nor on RC 86.1.1.
I've tested with Google Pixel (Android 10), and with sony Xperia Z5 Premium (Android 7.1.1).
After exiting the fullscreen mode via the back button, the website isn't scrolled to the top.
