### ISSUE TITLE
[Bug] Share image does not work with Telegram/Instagram

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17898]
From https://github.com/mozilla-mobile/fenix/issues/12414#issuecomment-774496917

-------

Firefox Nightly (210205), Android 11, OnePlus 8 Pro
Different behavior when sharing an image in Opera/Chrome and Firefox (wrong Intent or smthng)

[Firefox behavior](https://i.imgur.com/n8e0Zmk.png)

[Opera/Chrome behavior](https://i.imgur.com/VFedlnI.png)

[Image for test](https://meduza.io/impro/ZLl1xUZcZGGddYod_C0TkeJLNaUtBcOhv_aG6malvz0/fill/980/0/ce/1/aHR0cHM6Ly9tZWR1/emEuaW8vaW1hZ2Uv/YXR0YWNobWVudHMv/aW1hZ2VzLzAwNi80/NDMvNTg3L29yaWdp/bmFsL1h4NEk4N29D/Z2ROUkl6UXRtN1ls/WncuanBn.webp)

UPD:  Can't share this image from Firefox to Instagram Direct at all (Error: Unable to share image).

**Comment by Mugurell** [comment]
I think this is more of a problem with the receiving app - in this case Telegram / Instagram and their lack of support for `webp`.

When testing the share to Telegram with the two images from here https://www.silverdisc.co.uk/blog/2019/06/26/using-webp-images-improve-page-speed I see:

<img src="https://user-images.githubusercontent.com/11428869/107210147-687b6080-6a0c-11eb-8247-736f0cdefd65.png" width="33%" />

- When sharing the jpeg image - that file is recognized as image and for example can be zoomed
- When sharing the same image but as webp - Telegram does not handle the webp image but resolves it's link that we also send.

&nbsp;
I see Chrome is not actually sending original file's mime type when sharing images [but hardcodes "image/jpeg"](https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/src/org/chromium/chrome/browser/share/ShareHelper.java;l=283;drc=2ac64302ae161cd6b5e4b1254497bdf5fd6d3415)
This would give us the same result but I'm not sure it's the right approach.

Asking @Amejia481 for a second opinion - if we should hardcode the `jpeg` mime type or not.

**Comment by Mugurell** [comment]
I can't test on Instagram but I assume it's the same underlying issue - they not supporting the webp image type.

**Comment by BoyarkinNikita** [comment]
@Mugurell JPEG ok in Instagram and Telegram

But Tg adds useless link (if i want to share link i will tap the "Share Link" button, and behavior is different from other browsers)

mb u share link and not an image (wrong intent?)

**Comment by Mugurell** [comment]
@BoyarkinNikita Sharing the link alongside the image is intended.
Being that this is a new feature in Fenix with the intent of helping users and offering the best UX for sharing images I'm opened https://github.com/mozilla-mobile/fenix/issues/17910 to discuss what would be the best approach.

**Comment by Amejia481** [comment]
>     * webp

Harcoding the format seems a bit wrong("image/jpeg"),  but even though it looks the app is able to handle it. Is the issue present for other images types and other app? I don't like the idea, but if it will improve the users experience we could accept the compromise.  We could open an issue on the Telegram app  https://github.com/DrKLO/Telegram to gather more info.
