### ISSUE TITLE
[Bug] horizontal text scroll is not smooth

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#17893]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open below my bsnl broadband bill page
Check the horizontal scrolling text
Its movement is not smooth whereas the scroll is very smooth in chrome

https://mybillview.bsnl.co.in/DL_EZ_GA/webresources/app/htmlformat?ke=040220212106510545332938836106a9cf318a1d644774b2c2#

### Expected behavior
Texts should scroll smoothly
 
### Actual behavior
Text scroll is jittery 
### Device information

* Device vendor / model and Android version: ? Rog3 A10
* Firefox for Android version: ? (go to Settings -> About Firefox) latest nightly 

![Screenshot_20210208-095119099 (1)](https://user-images.githubusercontent.com/58127841/107175593-3dd0de00-69f3-11eb-8174-b8b6c76c93c2.jpg)

**Comment by Mugurell** [comment]
There's a small jitter in Chrome also (on desktop) but that scrolling text is visibly worse on both Firefox Desktop and on Fenix.
Moving to Bugzilla.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1691335

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment]
Seems like this is rather a webcompat bug with the website which uses the deprecated `marquee` API.
Filed https://github.com/webcompat/web-bugs/issues/66859 in this regard.
