### ISSUE TITLE
Local file:// protocol is not supported (yet)

### ISSUE THREAD

**Issue by alicavus** [mozilla-mobile/fenix#17891]
Background: Since there is a lot security issuess in legacy fennec browser I switched to fenix. I have my own home index.html page, with custom my stuff.

After migration I clearly see fenix does not have support for file:// protocol.

Steps to reproduce it:
Enable File access from android settings
Copy/create some html file and try to access it from the browser:
Type the full path i.e. file:///storage/emulated/0/custompage.html

What should be the result: Actual html page

What is happening: There is nothing showing up.

**Comment by cadeyrn** [comment]
Duplicate of #7546.

**Comment by kbrosnan** [comment]
Closing as a duplicate
