### ISSUE TITLE
Use Full Screen

### ISSUE THREAD

**Issue by Mossy93** [mozilla-mobile/fenix#17897]
### What is the user problem or growth opportunity you want to see solved?
I think it would be great if we had a fullscreen button or an option to have transparent navigation and notification bars with the webpage rendered behind it. This would allow us to utilize that much more of our screen space.

### How do you know that this problem exists today? Why is this important?
I'm currently using Fenix and the tom and bottom bars are flat white. I think it would be good to utilize maximum screen space.

### Who will benefit from it?
Everyone, I believe. This would make the browser look sleeker and show the webpage on the maximum available screen space.

**Comment by Mugurell** [comment]
Thank you for the request!
There are indeed other users also interested in this.
Please follow https://github.com/mozilla-mobile/fenix/issues/1984
