### ISSUE TITLE
Collections: critical features missing

### ISSUE THREAD

**Issue by ubrainlessgit** [mozilla-mobile/fenix#17890]
Firefox android beta collections.

Hi, i think collections is a wonderful feature and if it were just synced across devices it would be perfect. some REALLY overlooked features below. I listed them together because imho they are sort of part of the same spectrum 

Missing features which cripple the use of collections: 

1. There is no ' long press to open in new tab option'
2. You cant open in new private window and CANT EVEN access collections in private windows
3. Once u have a tab open, you cant access your collections anywhere eg the hamburger menu at bottom right should have a way to access your collections but only has option to save to collection. U have to open a new blank tab and then navigate to collections

Samsung galaxy s7
86.0.0-beta.2 (Build #2015790811)
AC: 72.0.5, 4f36d0f93
GV: 86.0-20210131185630
AS: 67.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9651)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812739

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
