### ISSUE TITLE
[Bug][a11y] PiP mode screen buttons - needs resizing 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#17901]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Prerequisites
Have Google Accessibility Scanner installed.

## Steps to reproduce
1. Navigate to youtube.com and open a video in full-screen mode.
2. Tap on the "Home" button from the overview menu buttons.
3. Using the Accessibility Scanner, scan the PiP mode screen.

### Expected behavior
The PiP is properly scanned and no suggestions are made.

### Actual behavior
![Screenshot_20210208_110623_com google android apps accessibility auditor](https://user-images.githubusercontent.com/58466444/107201741-12a1bb00-6a02-11eb-8bd5-5b3222bf5504.jpg)
![Screenshot_20210208_110631_com google android apps accessibility auditor](https://user-images.githubusercontent.com/58466444/107201756-16cdd880-6a02-11eb-986b-65784711f22f.jpg)

### Device information
* Device vendor / model and Android version: Huawei P40 Lite (Android 11).
* Firefox for Android version: Firefox 86.0.0-beta.2.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9662)

**Comment by eliserichards** [comment]
I think we'll need UX feedback if we want to make this bigger

**Comment by topotropic** [comment]
Just tested it and for me it passed the test. 

I'd be hesitate to make the icons bigger but if we can increase the touch target w/o updating the designs, that would be great! Thanks!
