### ISSUE TITLE
[Spike] Permissions updates in Android 11

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#17905]
## Title
Permissions updates in Android 11

## Description
Review our permissions flow in our app and ensure they follow the new requirements. 
Docs: https://developer.android.com/about/versions/11/privacy/permissions

## Deliverables

Document findings and open issues for changes that are required.

## Next Steps
See if we need to adjust site permissions according to new behaviors ( auto-reset, one-time permissions, etc...)
cc @Amejia481 who might have insights related to site permissions.

**Comment by Amejia481** [comment]
We could ask QA to perform a round of test

**Comment by Amejia481** [comment]
> See if we need to adjust site permissions according to new behaviors ( auto-reset, one-time permissions, etc...)
> cc @Amejia481 who might have insights related to site permissions.

In overall, I think should be safe.

**Comment by abodea** [comment]
Tested this on the debug build with SDK 30 with Google Pixel 4 XL (11):
I tested with the following websites `permissions.site` and `https://mozilla.github.io/webrtc-landing/gum_test.html.`
For the permissions.site website I tested the Location, Camera, Microphone, Camera + Microphone, Pan-Tilt-Zoom + Microphone and I used the `Only this time` option. 
Note that for the `permissions.site` website after ~3-5 minutes when I restarted the app I was able to trigger the permissions prompt again and select `Only this time` again or any other option.
I did the same thing for the `https://mozilla.github.io/webrtc-landing/gum_test.html.` and after ~3-5 minutes I was able to get the prompt permissions again.

- What is the default time when the temporary permission prompt is reset? 
- Is there any way to reset it manually for faster testing?
- Is it intended that the Fenix permissions to be displayed again after selecting the temporary permission `Only this time`? (the one at the bottom, the one with the check box: Remember decision for this site)

Removing `eng:qa:needed` until further notice.

**Comment by mcarare** [comment]
@abodea Are there any differences in site permissions behavior from testing Nightly on the same device (or another with Android 11) / Nightly with a device with Android <11?

I would be also interested in testing app permission outside websites (for accessing storage when downloading and camera when scanning QR codes)

**Comment by Amejia481** [comment]
>     * Only this time

Thanks for testing.

To clarify, we have two types of permissions **site permissions** and **Android permissions**.

* **Site permissions**: are permissions controlled by Fenix per site to allow or deny access to some features of the device and some of them required Android permissions, for example the camera site permission needs  an Android permissions to be used, but the notification site permession doesn't require an Android permission.

* **Android permissions**: Are the permissions that every Android app needs to has to utilize some features of the device like camera microphone, location , etc. These permissions are per Android app, Fenix as an Android app needs these permission to be granted to allow certain sites to use these features depending the permission that a site has.

**Only this time**, It's a new type of Android permission on Android 11, called [one time permission](https://developer.android.com/training/permissions/requesting#one-time), "If the user selects this option in the dialog, your app is granted a temporary one-time permission" for more info [see](https://developer.android.com/training/permissions/requesting#one-time).

Android permissions are independent of site permissions, users can change Fenix's Android permissions any time, when that happen some site permissions could be affected as they depend on the Android permissions, for example An user granted an **Android camera permission** to Fenix and after granted a camera **site permission** to an specific site for example [permissions.site](permissions.site), when the user tries to open [permissions.site](permissions.site) the site should have access to the camera, but if the user changes the camera **Android permission** to Fenix to denied then when the users tries to use [permissions.site](permissions.site) and the site ask for accessing the camera Fenix MUST prompt the **Android permission dialog**, any time the Android permission is denied.


> What is the default time when the temporary permission prompt is reset?

This is something that is controlled by Android and it could change [depending on multiple reasons ](https://developer.android.com/training/permissions/requesting#one-time), but I think there is not a specific time limit.


> Is there any way to reset it manually for faster testing?

I think the easiest way is to go to app settings and deny the permission on Fenix that should trigger the Android permissions dialog.



> Is it intended that the Fenix permissions to be displayed again after selecting the temporary permission Only this time? (the one at the bottom, the one with the check box: Remember decision for this site)

The Android permission dialog, should show any time the permission are required. But the Fenix site permission dialog should not show again if the checkbox was checked before.

**Comment by Amejia481** [comment]
Hope it help if you need any additional help just let me know happy to help :)

**Comment by mcarare** [comment]
@abodea can you also test Android permissions?

**Comment by abodea** [comment]
Hello, @mcarare note that I retested this, for more information please check the following:
I used 

| **Device**  | **Build** |   **Storage permissions**              |    **Camera permissions**                |     **Microphone permissions**               |  
| ------------- | ------------- | :-------------: | :-------------: | :-------------: | 
| **Google Pixel 4 XL (11)**  |     Latest Nightly     |      ✅       |          ✅       |     ✅             |  
| **Google Pixel 4 XL (11)**  |      Nightly SDK 30      |     ✅       |   ✅              |      ✅            |  
| **Samsung Galaxy S10+ (10)**  |    Latest Nightly    |        ✅     |       ✅         |       ✅           |  

Please note that for all 3 scenarios I was able to allow the storage/camera/microphone Android permissions.
When I cleared the Android permissions and accessed the website again, the permission prompt was displayed again.
Also, note that if I checked the box and not cleared the permissions the dialog was not displayed anymore.
Until further notice, I will remove `eng:qa:needed`.

**Comment by mcarare** [comment]
Given the info above, the documentation, and the previous testing, I do not think there are any concerns regarding permissions for Android 11. If @Amejia481 also agrees, I think we can close this. Thank you all for your input!

**Comment by Amejia481** [comment]
👍🏽
