### ISSUE TITLE
Consider not sharing a link with "Share image"

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#17910]
Fenix introduced in https://github.com/mozilla-mobile/fenix/issues/12414 the ability to share the actual image when users select "Share image" from the contextual menu while previously just the url was shared.

With the new behavior the image will be shared alongside with its link (if that does not exceed 200 characters, enough to be bothersome).
The main idea was that sharing also the link may offer more context about the image and if not needed it can easily be removed by the user.

There are reports that sharing the link also may not be needed.

Being that this is a new feature in Fenix with the intent of helping users and offering the best UX for sharing images I'm opening this ticket to discuss the opportunity of 
- keeping to share the image along with it's link or
- sharing just the image without the link.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9669)

**Comment by Mugurell** [comment]
One important thing to consider is that not all receiving apps may support all image formats, something seen in https://github.com/mozilla-mobile/fenix/issues/17898, in case of whch sending also the link still helps as a backup.

**Comment by caseyhoward** [comment]
All I want to do is be able to copy an image to my clipboard. I thought it was a little weird to have to "share" to my clipboard but I got over it. But I really don't want the link on my clipboard too. Is adding a "copy image" option out of the question?

**Comment by Mugurell** [comment]
> All I want to do is be able to copy an image to my clipboard.

That would be https://github.com/mozilla-mobile/fenix/issues/17780 which can certainly be accommodated.

**Comment by yoasif** [comment]
I think it is unexpected to copy a URL alongside the shared image - it is akin to the text that accompanies copies from web sites where they do the same thing - include the URL of the page being copied from. 

It isn't what was asked for, and if I need the context, I can always "Copy link".

**Comment by yoasif** [comment]
Hmm, can I reopen this by commenting?

**Comment by Catmato** [comment]
It is unexpected and bad UX to have to delete a URL when trying to share an image.  This wouldn't be an issue for some use cases if Firefox supported Copying an image to the clipboard.

**Comment by taracdia** [comment]
As a user, i don't like having the url in there and it is breaking the ability to share the photos using a messaging app

**Comment by taracdia** [comment]
I'm seriously thinking about returning to chrome over this

**Comment by KR2206** [comment]
> One important thing to consider is that not all receiving apps may support all image formats, something seen in #17898, in case of whch sending also the link still helps as a backup.

You are not really wrong, but it's rather counter intuitive because share link option is just above the share image if some apps are having issues. It would be better to try sending link the 2nd time than having to break the flow to clear link. Personally WhatsApp telegram can receive images well and good but clearing the prefilled textbox with url is something nobody expects from an option like "share image". My primary use case of share image is to share memes/informatics images with my friend groups and I expect it to be a breeze like every other browser does.

Another option would be to give user the control how they want to share images(only image or image+source link). Whatever yall like but please this ASAP so I can move over to firefox on all my devices

**Comment by taracdia** [comment]
> Another option would be to give user the control how they want to share images(only image or image+source link). Whatever yall like but please fix this ASAP so I can move over to firefox on all my devices
Seconded

**Comment by DreVla** [comment]
I investigated this issue and managed to solve it in Android Components. I have created the bug in bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1806411 and the PR is here: https://github.com/mozilla-mobile/firefox-android/pull/390.

**Comment by csadilek** [comment]
Duping to https://bugzilla.mozilla.org/show_bug.cgi?id=1806411 .

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 110.0a1 (2023-01-11) build.
Marked as verified on the Bugzilla ticket as well.
Removing the qa needed label.
