### ISSUE TITLE
[Bug] Default browser toggle behavior sends you to system defaults even if you cancel dialog

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#17915]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to settings -> click "Set as default browser" (tested on API 30)
2. Observe dialog with choices 
3. Press cancel or press back 

### Expected behavior
Dialog will close, be back on main Settings screen

### Actual behavior
Dialog will close, but get sent to System "Default Apps" screen anyway 

### Device information

* Device vendor / model and Android version: Pixel 3, API 30 emulator 
* Firefox for Android version: ? (go to Settings -> About Firefox) Up to date master branch

**Comment by sflorean** [comment]
Verified as fixed on Nightly 2/9 with Pixel 3 (Android 11).
