### ISSUE TITLE
[Bug] Reload button not working on certain pages opened time ago

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#17925]
Opened this website the 23rd January 2021:
[Linux 5.12 To Allow Voltage/Temperature Reporting On Some ASRock Motherboards](https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.12-ASRock-Some-Sensors)
 
After closing lots of tabs I get to this one again the 8th February, but site is displayed black (I'm on dark mode). Reload button does nothing, I have to go to address bar and pop-up keyboard and enter again. Then loads.

Now I'm on Firefox 85.1.2 on Android 10, which just updated but when the issue happened was just on previous version from Google Play Store, which I presume was 85.1.1.

Video (can be played without download): https://mega.nz/file/1dNFiYTa#tGeXpRbZ6eIeVvEdSN-8jz9me6Fq9V41Q8Q7OKt8HvU

It happened to me in about 10 sites total, most of them amp urls but not all of them.
With this newest update 85.1.2 didn't test enough, will reply if happens again.

**Comment by superbonaci** [comment]
I'm confirming this still happens in 85.1.2. Sample online video:
https://mega.nz/file/1UkkXTQa#KfVZHbuTMXTlCmvJlOYgxQ4TBkcoBE21Khrs_pZBDvE

**Comment by abodea** [comment]
Thank you for this report @superbonaci!
Note that I was not able to reproduce this on the latest Nightly from 3/31/21 with Google Pixel 4 XL (11) and Samsung Galaxy S10+ (10).
I followed the steps from the description but the website worked as expected, I even set the URL bar to top.
Can you still reproduce this issue?
Note that I also tried on the latest RC but I was not able to reproduce it.
I've had many tabs opened like 100+.

**Comment by superbonaci** [comment]
It has to pass a lot of time, and I think it was fixed, so closing for now.
