### ISSUE TITLE
Fenix prefer uses CHACHA20_POLY1305, not AES_GCM though my device's CPU is ARM Cortex-A55, which is supports AES acceleration

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#17927]
## Steps to reproduce
I did a test in https://clienttest.ssllabs.com:8443/ssltest/viewMyClient.html
### Expected behavior
Fenix should prefer AES-GCM if device's CPU supports AES acceleration. 
### Actual behavior
Fenix prefer uses CHACHA20_POLY1305, not AES_GCM. My device's CPU is ARM Cortex-A55, which is supports AES acceleration. 
Cipher Suites (in order of preference)
TLS_CHACHA20_POLY1305_SHA256 (0x1303)   Forward Secrecy 	256
TLS_AES_128_GCM_SHA256 (0x1301)   Forward Secrecy 	128
TLS_AES_256_GCM_SHA384 (0x1302)   Forward Secrecy 	256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)   Forward Secrecy 	128
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   Forward Secrecy 	128
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)   Forward Secrecy 	256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)   Forward Secrecy 	256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)   Forward Secrecy 	256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   Forward Secrecy
... 
### Device information

* Android device: Android 10, Huawei Honor 20S
* Fenix version: 85.1.2

**Comment by Mugurell** [comment]
We indeed prefer ChaCha on all ARMs - https://bugzilla.mozilla.org/show_bug.cgi?id=1583610.

Moving to Bugzilla since this is a platform discussion

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1691650

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
