### ISSUE TITLE
2+ touch point gestures should be able to be captured by the webpage

### ISSUE THREAD

**Issue by roelandschoukens** [mozilla-mobile/fenix#17936]
Eg. https://www.vrt.be/vrtnws/nl/2020/07/24/aantal-nieuwe-coronabesmettingen-per-gemeente/ doesn't work.

Pinch will sometimes zoom, however trying to scroll just scrolls the page.

This issue is not reproducible in Chrome.

I have version 85.1.2 (Build #2015791451)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1691806

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
