### ISSUE TITLE
Accomodate websites which store user preferences in cookies

### ISSUE THREAD

**Issue by roelandschoukens** [mozilla-mobile/fenix#17944]
### What is the user problem or growth opportunity you want to see solved?

Firefox doesn’t store cookies for longer than a few days. While most websites seem OK with this, it can break functionality in some websites.

### How do you know that this problem exists today? Why is this important?

Some websites store preferences in cookies. It can be annoying if they reset to the defaults whenever you don’t visit those websites for a few days.

An example is Blogger, where you can ask it to ignore your own visits for a blog you're writing.

### Who will benefit from it?

Users using these websites.

(Maybe websites are supposed to use something more modern than cookies for this, but you don’t have control over this as a user)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9681)

**Comment by kbrosnan** [comment]
This should work. Firefox supports cookies. Can you provide more context about when this breaks? Does force quitting Firefox cause this? Rebooting your phone?  Updating via the Play store? Something else?

**Comment by roelandschoukens** [comment]
Yes it looks like explicitly quitting Firefox by clearing it from the recent apps list in Android causes it to drop this cookie immediately. (I think the Android docs call this "Recents screen")

**Comment by abodea** [comment]
Thank you for this report!
Here you have some information regarding [cookies purging.](https://github.com/mozilla-mobile/fenix/issues/13812#issuecomment-700503934)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807445

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
