### ISSUE TITLE
[Bug] Links opened by apps are getting attached to existing tabs showing the same links

### ISSUE THREAD

**Issue by oakkitten** [mozilla-mobile/fenix#17959]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Steps to reproduce

- Open https://i.redd.it/ax8j6vvi1pg61.jpg in Fenix
- In some other app, e.g. Keep, tap the same link
- After the link opens in Fenix, observe the cat and press back

### Expected behavior

The device goes back to Keep

### Actual behavior

Fenix executes the browser back action, displaying whatever the tab had before you opened the link. You can keep pressing back until you get to the home page, and then it goes to Keep. 

After that, if you open Fenix from the launcher, instead of displaying whatever tab it was displaying before, it will displays the cat. This might be an unrelated issue; if an external app opens a link that's new to Fenix, after going back and launching Fenix again it will display the last tab instead.

### Device information

* Device vendor / model and Android version: Xiaomi Mi A2, Android 11
* Firefox for Android version: Nightly 210209 17:04 (Build 2015792331)

**Comment by lobontiumira** [comment]
Thanks for the report, @oakkitten!

I did not manage to reproduce your issue with Samsung Galaxy Note 8 (Android 9) on the 3/31 Nightly build. 
Are you able to reproduce this on the latest Firefox Nightly build?
Could you provide us a short video, for a better understanding?

**Comment by oakkitten** [comment]
i hope 3/30 is alright

https://user-images.githubusercontent.com/1710718/113204711-65ab2800-9265-11eb-9348-71ac299afa40.mp4
