### ISSUE TITLE
Keep Videos Playing in Background

### ISSUE THREAD

**Issue by xvoodoochildx** [mozilla-mobile/fenix#17968]
A MUST! I should be able to play a video like news and browse the web. It is super inconvenient to be stuck in webpage!! I have to use other browser to visit sites while having live news/video in firefox popup which is inconvenient also! 
Dont tell me how i should engage with content and how i use my device!!

**Comment by sheikh-azharuddin** [comment]
Use the add on video background play fix

**Comment by kbrosnan** [comment]
This is the website using standard web APIs to detect if the user is actively on that page. As mentioned there are extensions that allow users to ignore the restriction implemented by websites.
