### ISSUE TITLE
FNX-5247 ⁃ [Bug] Area between address bar and quick actions bar looks cramped when progress bar is present

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1796]
## Steps to reproduce
1. Open Fenix
1. Open tab
1. Open quick actions bar
1. Load page

### Expected behavior
More space between quick actions bar and address bar.

### Actual behavior
The progress bar makes the area between quick actions and the address bar look sloppy and cramped. 

![signal-attachment-2019-04-18-183736](https://user-images.githubusercontent.com/152493/56395678-88bfa700-6209-11e9-801a-95fef5c45074.png)

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1916 build 11081207

**Comment by ekager** [comment]
I just added a bit of padding here in #1831
