### ISSUE TITLE
[Feature] Reader view appearance controls in three-dot main menu

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17971]
Meta: #17796

UX point of contact: @violasong (Victoria)

Figma designs (bottom right, labeled "Final design"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

## Current reader view flow with "Appearance" menu item
* Open the app
* Navigate to a wikipedia page (anything with text)
* See the reader view icon showing in the search toolbar
* Select reader view
* Open three-dot menu
* See "Appearance" item 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/43795363/107705551-8652fa80-6c84-11eb-8b5d-779a7daf1ae7.png"> <img width="319" alt="image" src="https://user-images.githubusercontent.com/43795363/107705476-658aa500-6c84-11eb-9a8e-ae0d0a564d92.png">

## Acceptance criteria
* Change "Appearance" to "Customize reader view"
* When reader view is ON, item placement should be below "Desktop site" 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/108397945-1e4d6880-71de-11eb-8a61-3b00245787ca.png">

**Comment by violasong** [comment]
Checked in with Betsy - we can change "Appearance" to "Customize reader view." I've updated the main Figma "final" mockup to reflect this :)
