### ISSUE TITLE
Update UI tests for Main Menu design changes

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#17979]
Meta: #17796 

Need to update or add UI tests for the main three-dot menu redesign to ensure we don't have breakage when landing. 

## Context
The main menu redesign is currently behind a Feature Flag (`toolbarMenuFeature`). We need to update the existing UI tests to reflect the new designs, and add new tests for the new menu features. 

Places to start:  
* There are already a few UI tests in the codebase that have been marked `@Ignore` with this issue number. They will all be in this folder:  `fenix/app/src/androidTest/java/org/mozilla/fenix/ui/` (see https://github.com/mozilla-mobile/fenix/tree/master/app/src/androidTest/java/org/mozilla/fenix/ui)
* [NavigationToolbarTest](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt)
* [BookmarksTest](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt)
* [ReaderViewTest](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt)
* [SmokeTest](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt)
   * mainMenuShareButtonTest
   * mainMenuRefreshButtonTest
* [NoNetworkAccessStartupTests](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/)
   * testPageReloadAfterNetworkInterrupted

**Comment by RiyaJ2311** [comment]
Hello!
I'm Riya, an Outreachy applicant.
I'm interested in this issue and would love to be assigned to it.
@eliserichards @amedyne  how can I contribute?

**Comment by eliserichards** [comment]
Hi @RiyaJ2311! I will add some more info to the description for you :)

**Comment by sv-ohorvath** [comment]
A few more tests were disabled for blocking a PR (https://github.com/mozilla-mobile/fenix/pull/18619), here https://github.com/mozilla-mobile/fenix/pull/18722
<NavigationToolbarTest.goForwardTest>
<NavigationToolbarTest.refreshPageTest>
<NoNetworkAccessStartupTests.testPageReloadAfterNetworkInterrupted>
<SmokeTest.mainMenuShareButtonTest>
<SmokeTest.mainMenuRefreshButtonTest>
<ShareButtonTest.ShareButtonAppearanceTest>

**Comment by AaronMT** [comment]
Thank you for disabling the tests ahead of time. @isabelrios / @sv-ohorvath will be covering this.
