### ISSUE TITLE
Clear Recent Tabs list with Delete browsing data on quit

### ISSUE THREAD

**Issue by BrokenShoeLace** [mozilla-mobile/fenix#17986]
Set Delete Browser History on Quit to on, tick all of them. Now Quit the browser. It doesnt close but stay open in the background. Bring to foreground again, click the 3 dots to see recent open tabs still has the info when it should have been deleted on Quit.

It is pointless to delete open tabs, focus it the delete recently opened tabs.

**Comment by Amejia481** [comment]
This is the same as https://github.com/mozilla-mobile/fenix/issues/20367, the fix is on [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix), please feel free to reopen if the issue persists.
