### ISSUE TITLE
Intermittent UI test failure - inconclusive results for shards

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#17989]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7980052240559564767
### Build: ? / fenix revision bab7693b9d776afc3ea37b1e5c7954c34dc2129a

fenix ui-tests got 2 inconclusive results yesterday, both for ui-test runs for revision bab7693b9d776afc3ea37b1e5c7954c34dc2129a but in different shards

https://firefoxci.taskcluster-artifacts.net/B-aOhulvTtuFqRGqbYHWww/0/public/results/MatrixResultsReport.txt mentions `Infrastructure failure` (the failures hit different machines).

Is there more information available in the logs or artifact about the issue?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9703)

**Comment by sv-ohorvath** [comment]
On the Firebase #test-lab community slack channel there are multiple reports about Infrastructure failures and the team seems to be aware about it. Lets see if this issue repeats and we'll report it.
Also there was a GCP network incident on 2/12 that was disrupting tests https://status.cloud.google.com/incident/cloud-networking/21002

**Comment by sv-ohorvath** [comment]
Didn't occur again in the last month, closing.

**Comment by sv-ohorvath** [comment]
No new issues since April. closing.

**Comment by Archaeopteryx** [comment]
There is a [reference-browser failure](https://console.firebase.google.com/project/moz-reference-browser-230023/testlab/histories/bh.b4e77beaed81bc1c/matrices/6924049817060312408) about inconclusive tests.
