### ISSUE TITLE
Android Firefox botches fixed-position toolbar

### ISSUE THREAD

**Issue by sbdy716** [mozilla-mobile/fenix#17991]
## Description
The latest Android Firefox has a bug related to its dynamic toolbar, which can both leave empty space on pages, and make a site's bottom-of-page toolbar slide up into page content.  The GUI seems to believe a phantom browser toolbar is still present at page bottom, and in some cases renders an empty strip for it.  This can be worked around by setting the toggle off, but a browser fix would be better.

This sounds similar to other bugs related to Firefox's new dynamic toolbar, but it's tough to tell, and this hasn't yet been fixed in Firefox 85.  Apologies if it's a dup. 

## Steps to reproduce
This happens when the browser's "Scroll to hide toolbar" is toggled on, and can be triggered by scrolling to hide the browser's toolbar and then changing device orientation.  For examples, see the screenshots below.

### Expected behavior
Site toolbars at a fixed bottom-of-page position should remain there; and space should not be wasted for a phantom browser bar.

### Actual behavior
They don't; and it is.

### Device information
This has been seen on Firefox versions 81 through 85, and on both Galaxy and Pixel devices.  It did not occur in older Android Firefoxes, and happens in no other browsers.

## Screenshots
The first shot below shows the scene when a fixed toolbar slides, and the second captures what happens when the empty space crops up (assuming the uploads work here):

 
![firefox-android-bug-1](https://user-images.githubusercontent.com/79031310/107866809-70cb0580-6e29-11eb-8546-117c054b2d1f.jpg)

![firefox-android-bug-2](https://user-images.githubusercontent.com/79031310/107866811-82aca880-6e29-11eb-99e1-42c56338cc5b.jpg)

**Comment by Mikaka27** [comment]
I see similar behavior when buying stuff on allegro.pl
The button on the bottom leaves space for address bar even whet it isn't there:
![Screenshot_20210214-130937_Firefox](https://user-images.githubusercontent.com/9214100/107876399-1cc22e80-6ec6-11eb-841f-e8e02f2b9789.jpg)
![Screenshot_20210214-130926_Firefox](https://user-images.githubusercontent.com/9214100/107876401-20ee4c00-6ec6-11eb-86d1-1fee9b7bb813.jpg)
