### ISSUE TITLE
Allow saving cache to external storage

### ISSUE THREAD

**Issue by Noob729** [mozilla-mobile/fenix#17994]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Some websites (e.g. web games or video sharing) serve large static resources (typically 1-100 MB each).
These resources (image, video, audio) are cached in the profile's cache, on internal storage.
However, internal storage is often more limited than external storage.
(For example, my phone provides 16 GB internal + 128 GB SD card)

I think it would make sense for Fenix to let users move a profile's cache to external storage.
This would allow caching many more large "static" resources, and thus reduce cache thrashing.

Note: this is different than #16703 which discusses moving the entire app.

### How do you know that this problem exists today? Why is this important?

When I play a web game, I can see the game resources being re-downloaded every few days.
Since I have a limited data plan, I can't play the game when I don't have un-metered access.

### Who will benefit from it?

People with large external storage could cache more resources, and thus download them less often.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9706)

**Comment by Noob729** [comment]
As an example, the Deezer application (music streaming) provides a "cache on external storage" option:

https://support.deezer.com/hc/en-gb/articles/115003875089-Deezer-data-and-Smart-Cache

Assuming an average of 3-4 MB per track, a 1000-track playlist takes up 3-4 GB in the cache.
(at standard quality. Multiply by 2.5 for high quality. Multiply by 5 for lossless)

If I browse the Deezer website in Firefox (instead of using the app) the available cache is smaller than that.
(about:cache mentions 512 MB)

**Comment by Noob729** [comment]
Hello @kbrosnan,

You wrote: "Moving the app [to external storage] can cause significant problems with Firefox for Android. This is not a supported configuration and we don't plan on making this work."

I was wondering whether the dev team would allow storing **just** the file cache to external storage?

AFAIK, desktop FF supports a browser.cache.disk.parent_directory pref in about:config  
https://www.ghacks.net/2008/11/20/moving-the-firefox-disk-cache-to-another-drive/

IIUC, Fenix beta allows access to about:config?  
If so, I'll try to tweak the pref in FF beta, and see if I can give FF an 8 GB cache on the SD card.

Regards.

**Comment by kbrosnan** [comment]
Using the sdcard is problematic. It is a transient data store. It is world writeable which may have some security concerns. We don't have any plans to use the sdcard for cache.
