### ISSUE TITLE
FNX-5249 ⁃ User can access browsing history by accessing it via URL bar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#18]

**Comment by sblatz** [comment]
Can we get some clarification on what's meant by this?

**Comment by pocmo** [comment]
Those issues from April 2018 are from a very early requirements & milestone tracking spreadsheet (that is outdated now):
https://docs.google.com/spreadsheets/d/1wADrIaY95PB9X5So6J6DZMf48Ex7K6EUPSKwfrNd2RI/edit#gid=767839414

From that I assume that this was about autocompleting URLs you type from visited URLs in your history (But that's also #20) or for surfacing suggestions in the awesomebar based on your history.

**Comment by bbinto** [comment]
I think we can close this, as it will be covered in the history meta
