### ISSUE TITLE
FNX-5250 ⁃ [UX] Perceived Performance

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#180]
This is to cover looking at the app at seeing how we can improve the perceived performance. Issues could come from using it, user research, and other feedback channels. 

This is mainly for UX but eng tasks could come out of this which can be prioritized with other work.

**Comment by bbinto** [comment]
What list / source did you take this item from? I might be able to clarify then.

**Comment by vesta0** [comment]
@mheubusch can we close this bug?

**Comment by shorlander** [comment]
I think we can close this. It doesn't have anything actionable on it.
