### ISSUE TITLE
PNG image with bad CRC is not loaded in Firefox Chrome ignores error and displays image

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#18008]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Download attachment image
2. Install and enable [Wifi File Transfer](https://play.google.com/store/apps/details?id=com.smarterdroid.wififiletransfer)
3. Input the IP location given by Wifi File Transfer
4. Find the downloaded image
5. Open with Firefox

### Expected behavior
The image should be display without any problem

### Actual behavior
After the image is opened, the image is displayed on screen, suddenly it was replaced by a text `http://192.168.1.103:1234/storage/emulated/0/Download/250px-Coreldraw_x8.png` on grey background.

### Device information

* Device vendor / model and Android version: Galaxy S6, Android 7
* Firefox for Android version: 85.1.3
 
### Attachment
![250px-Coreldraw_x8](https://user-images.githubusercontent.com/10364351/108021044-adc90f00-7058-11eb-8567-c4822f985e79.png)

**Comment by kbrosnan** [comment]
```
..\108021044-adc90f00-7058-11eb-8567-c4822f985e79.png  CRC error in chunk tEXt (computed f237937e, expected 61775f78)
ERROR: ..\108021044-adc90f00-7058-11eb-8567-c4822f985e79.png
```

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1693190

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
