### ISSUE TITLE
FNX-5251 ⁃ "Report a problem" / "Report a site issue" should open in a new tab

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1800]
### Why/User Benefit/User Problem
As a user, I would like to be able to gather additional information from a page (eg screenshots) when reporting a site issue. 

### What / Requirements
Tapping "Report a problem" / "Report a site issue" should open in a new tab with the site URL correctly filled in. 

### Acceptance Criteria (how do I know when I’m done?)
I can open "Report a problem" / "Report a site issue" and switch back to the other tab, take a screeeshot and upload it without worrying about losing any data I filled into the issue page.

**Comment by ekager** [comment]
This makes sense to me and is a quick fix, tagging @vesta0 for product confirmation!

**Comment by yoasif** [comment]
FYI this is what Fennec and Firefox desktop does as well.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1920 (#11391807), with Google Pixel (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
