### ISSUE TITLE
[Bug] Weird interaction of "Add to Home screen" and "Open links in a private tab"

### ISSUE THREAD

**Issue by cmm** [mozilla-mobile/fenix#18001]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Enable "Open links in a private tab" in Settings/Private browsing
- Open a site in Firefox (_not_ in a private tab)
- Go to the menu, choose "Add to Home screen", go through the motions, make sure the new shortcut appears
- Without explicitly closing the site's tab, press the home button (or background Firefox in any other way) and press your newly-created home screen shortcut.   Observe that the existing (non-private) tab opens
- Explicitly close the tab, background or close Firefox, press the site's home screen shortcut again.  Observe that it opens in a private tab

### Expected behavior
Ideal: a home screen site shortcut opens the site in the exact same mode that the site was open in at the time the shortcut was created (and, if/when Fenix grows container support, in the same container).

Second-best: allow the user to specify how a newly-created home screen shortcut opens.

Third-best: have a global setting.

Fourth-best: any _consistent_ behavior.

### Actual behavior
Home screen shortcuts open sites either privately or not, according to whether tabs for those sites already exist.

### Device information

* Device vendor / model and Android version: Xiaomi Mi A1, Android 10 (latest LineageOS official)
* Firefox for Android version: "Nightly 210213 05:01 (Build #2015793003)"

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-9713)

**Comment by codrut-topliceanu** [comment]
@cmm Thank you for bringing this up!

> Without explicitly closing the site's tab, press the home button (or background Firefox in any other way) and press your newly-created home screen shortcut. Observe that the existing (non-private) tab opens

   The tab doesn't really open. When tapping on a "shortcut" from the homescreen if that specific tab is already open, you are sent to that tab instead. So in this case you already had that tab open in normal browsing mode so you were taken to it. 

>Explicitly close the tab, background or close Firefox, press the site's home screen shortcut again. Observe that it opens in a private tab

 Here the tab wasn't found in your list of open tabs so a new one was created using the preference from "Open links in a private tab" in Settings/Private browsing.


I'm not sure what change is best here, so I'm pinging UX for a decision regarding *Expected behavior*.

**Comment by cmm** [comment]
@codrut-topliceanu well, yes, the current behavior clearly does make *mechanical* sense, but that's not a good excuse for it.

**Comment by vladimiroff** [comment]
I would like to explain my use-case and why, even though current situation **does** make *"mechanical"* sense, it is sub-optimal.

There are pages, I often visit, which lack good mobile apps. For the most of these pages, having an account is important. In those cases "Add to home screen" functionality is close to useless when "Open links in a private tab" is enabled. Just a bookmark on the home screen. On each open there's logging in (potentially with a 2fa) process involved. Thus the lack of native app hurts.

If there's an option to open home screen links in a normal tab, the lack of native app barely matters (given the site is mobile friendly).

**Comment by codrut-topliceanu** [comment]
Yep, that makes a lot of sense to me. My previous comment was just an explanation on how it currently functions not anything else. That's why I added the UX-feedback tag 😄 .

**Comment by vladimiroff** [comment]
Just tried it out and this actually seems to be fixed.
