### ISSUE TITLE
[Bug] [a11y] On Homescreen, the top sites are announced improperly

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#18009]
## Steps to reproduce
1. Enable Talkback or voice assistant.
2. Open the Homescreen, making sure to have only the default top sites (Google, Top Articles, Wikipedia).
3. Navigate using talkback gestures through the top sites and listen the description.

### Expected behavior
The voice assistant announces "Google, 1 of 3, double tap to activate", "Top Articles, 2 of 3, double tap to activate", etc.

### Actual behavior
The voice assistant announces "Google, 1 of 4, double tap to activate", "Top Articles, 2 of 4, double tap to activate", etc.
Even when I've deleted some of the tiles, and let only Google as a top site, the voice assistant kept announcing it as "1of 4".

### Device information
* Device vendor / model and Android version: Xiaomi Mi 8 Lite (Android 9)
* Firefox for Android version: Beta 86.0.0-beta.5, 2/15 Nightly, and RC 85.1.3

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 3/4 with Pixel 2 (Android 9).
I will remove the qa:needed label and close this issue.
