### ISSUE TITLE
[Bug] [Vibration] [UX feedback] Vibration is being triggered when long-pressed in the empty space

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#18015]
I don't know if it's a UX feature or a bug but the haptic feedback (vibration) is being triggered when long-pressing in the empty space.

***Steps to reproduce:***
1. Go to `https://www.wikipedia.org/` (it can be triggered across the websites)
2. Click anywhere where space is available
3. Vibration is triggered which it should not as it'll make a bad UX for users. It's very annoying currently.

Device: Realme X3, Android 10
Firefox: 85.1.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9723)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox RC 89.1.1 and Nightly 06/30.

### Devices used
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible on the latest builds:
- latest Nightly 97.0a1 (2021-12-27).
- latest Beta 96.0.0-beta5.
- latest Release 95.2.0.

Device used: Google Pixel 4 (Android 11).
