### ISSUE TITLE
[Bug] Reopened Sites Reload When I Want To Add A New TAB

### ISSUE THREAD

**Issue by lucifer000123** [mozilla-mobile/fenix#18011]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information) Hello Firefox. Why Reopened Sites Reload When I Want To Add A New TAB

### Device information

* Device vendor / model and Android ADVAN 5202 Android 9 Pie version: ?
* Firefox for Android version: ? (go to Nightly 210215 17:01 (Build #2015793483)
AC: 73.0.20210213190052, 2850e0b9c
GV: 87.0a1-20210211092822
AS: 70.0.0Settings -> About Firefox)

**Comment by lobontiumira** [comment]
Thank you for the report @lucifer000123!

I've tested on Samsung Galaxy Note 8 (Android 9), on the 3/31 Firefox Nightly build, the following scenario: 
- I had some previous tabs opened from a day before, 
- I opened a new tab, 
- went back to tabs tray, 
- opened an old tab, which reloaded.

I'm not sure I understand if this is your issue, so please provide more details.
Could you, maybe, provide us a short video?
