### ISSUE TITLE
[Bug] [a11y] "Report site issue" option isn't selected along with the icon

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18016]
## Steps to reproduce
1. Enable voice assistant or talkback.
2. Using TB gestures, open a page, and go to the three-dot menu.
3. Go through all menu items and observe the selection of the "Report site issue" option.

### Expected behavior
All the options are selected along with the icon.

### Actual behavior
The "Report site issue" option is selected without the icon - see the screenshot below.

### Device information
* Device vendor / model and Android version: Xiaomi Mi 8 Lite (Android 9)
* Firefox for Android version: Beta 86.0.0-beta.5, and 2/15 Nightly
* Reproducible with light theme also.
 
![Untitled](https://user-images.githubusercontent.com/40694158/108065169-444ffd00-7066-11eb-8f3b-92a7b574f3b4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9724)

**Comment by mcarare** [comment]
As a note, this happens for all add-ons. It remains to be seen if this issue is still valid after the menu re-design.

**Comment by Jasaxxus** [comment]
Hey, I am an Outreachy aplicant and I would like to work on this issue

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the 90.0.0-beta.3 build with OnePlus 5T (Android 10).

**Comment by SoftVision-LorandJanos** [comment]
This issue is partially reproducible on the:
- latest Nightly 99.0a1 (2022-02-24).
- latest Beta (98.0.0-beta3).
The "Report site issue" option is selected without the icon, but the icon color is as expected.
![Screenshot_2022-02-24-11-34-48-01_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/48829350/155498531-ae597e84-ef3b-4923-9b26-76ff61aad079.jpg)
Device used: Oppo Reno 6 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 110.0a1 (2022-12-29).
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809239

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
