### ISSUE TITLE
[Bug] Bottom address bar is cutoff at the corners

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#18014]
Device: Realme X3, Android 10.
Fenix version: 85.1.3

![372_compress44](https://user-images.githubusercontent.com/78963751/108063757-b8e46500-7081-11eb-926b-bbde76c2bc93.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9722)

**Comment by mcarare** [comment]
This issue has been already discussed here: https://github.com/mozilla-mobile/fenix/issues/8900

**Comment by Neon329** [comment]
An app that offers a solution for this is Poweramp music player. It has a setting called "Offset Navbar" which moves the Poweramp's navbar slightly away from the corners. I'm not sure if the same can be implemented in Firefox as well but it's just cosmetic issue (as long as it doesn't cutoff web addresses themselves) but a lot of devices allow you to hide the the system navbar (in some cases by default). I have seen devices manufacturers like Xiaomi, Poco, Realme, OnePlus and maybe Oppo devices as well hide the system navbar completely by default and in these cases depending on how narrow the display corners are it is going to be a problem maybe? Whatever the case the majority of devices sold in my region are from Xiaomi's, OnePlus's, Poco's and Relame's AFAICT. So the majority of the devices are affected here.


![IMG_20210216_182316](https://user-images.githubusercontent.com/78963751/108066096-e7177400-7084-11eb-8bc9-1b126b12c9d7.jpg)

**Comment by mcarare** [comment]
This is one of the solutions for that, the other would be checking against a list of devices with round corners and adjust the padding automatically. I think is best that UX decides on this.

**Comment by topotropic** [comment]
Thanks! From a UX point I'll quote Bram here:

> Based on my discussion with the team, we’ve reached this answer: if it’s possible to know when to adapt the UI based on device, then that’s a solution that we should pursue.
> 
> If it’s not possible, then we should do nothing, because we are going to make things worse for the majority of devices that aren’t clipping.
> 
> https://github.com/mozilla-mobile/fenix/issues/8900#issuecomment-645778285

I guess it depend how many devices we are talking here and if that justifies the effort since it doesn't impact functionality as far as I understand.

**Comment by Dunexus** [comment]
Android 12 is adding [Rounded corner APIs](https://developer.android.com/about/versions/12/features#rounded_corner_apis) to tackle this kind of issues.

**Comment by Dunexus** [comment]
Keep it open, still an issue
