### ISSUE TITLE
Expend webpage header's color to statusbar?

### ISSUE THREAD

**Issue by cathaysia** [mozilla-mobile/fenix#18026]
### What is the user problem or growth opportunity you want to see solved?

Please see this picture:

![QQ截图20210217135714](https://user-images.githubusercontent.com/42114817/108162445-1df29600-7128-11eb-8c7d-68cbef01212d.png)

Can we let statusbar's color be same with webpage header's color ?

### How do you know that this problem exists today? Why is this important?

This issue is not very important, just to fix user's experience.

### Who will benefit from it?

Person who has a All Screen phone.

> this "All Screen" is "全面屏"'s translation, but I don't know whether it's a exactly translation or not. This mean a phone only has screen on it's front, no any other buttons. Like Mi mix 2s.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9729)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808765

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
