### ISSUE TITLE
[Bug] Tab Tray does not have rounded corners in landscape mode

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#18028]
Noticed while working on https://github.com/mozilla-mobile/fenix/issues/17807. Seems that the `setOnApplyWindowInsetsListener` was intended to handle this issue. Also requesting UX confirmation on the expected behavior, as I do not have the original designs and I do not think a landscape design was created.

## Steps to reproduce

Open tab tray while on landscape orientation / Rotate device to landscape after opening the tab tray.

### Expected behavior

The tab tray has rounded corners.

### Actual behavior

The tab tray does not have any corners.
### Device information

* Device vendor / model and Android version:  All
* Firefox for Android version: All

**Comment by topotropic** [comment]
When the tab tray is not fully extended, I see rounded corners in landscape. And once it's fully extended we remove them. This is as specified. I'll close the issue but please re-open if you have an issue! Thank you!
