### ISSUE TITLE
Suggested web search engines

### ISSUE THREAD

**Issue by gallegonovato** [mozilla-mobile/fenix#18033]
Good afternoon:

I take the opportunity, if I may. To see if it is possible that iceraven of origin includes search engines like seax, startpage or metager. Instead of twitter or wikipedia for example. Since you can search inside those webs or in them with any search engine. And the other three that I mention are so to speak more secure or in line with the privacy of our searches.

A hug and thank you for your time and help.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9734)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807568

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
