### ISSUE TITLE
[Bug] Swiping up/down while reddit loads shows toolbar placeholder

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#18034]
## Steps to reproduce
- New app install -> to not have set how to open Reddit -> to have Reddit show a banner asking about this
- Access reddit.com
- swipe up/down while Reddit loads

### Expected behavior
- Maybe the toolbar should be fixed in place?

### Actual behavior
- The toolbar is animated away from the screen but a placeholder for it is shown.

https://user-images.githubusercontent.com/11428869/108252589-801bbd00-7161-11eb-8f47-1bc8daee0ffc.mp4

**Comment by Mugurell** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/14821

**Comment by Mugurell** [comment]
Reopening this since in the linked https://github.com/mozilla-mobile/fenix/issues/14821 there seems to be more issues described while here there is a specific one.

**Comment by Mugurell** [comment]
Looked into possible approaches and one easy way to fix this exact case would be to just not animate the toolbars while the webpages are loading.
Chrome seems to do the same and Sorina recommended the same in https://github.com/mozilla-mobile/fenix/issues/10200.
Confirmed with Nicole that if this straightforward approach solves the issue we should go with it.

**Comment by Mugurell** [comment]
Added P1 back as a priority from Vesta.

**Comment by Mugurell** [comment]
Created https://bugzilla.mozilla.org/show_bug.cgi?id=1694730 as a GV followup to the Fenix/AC changes which would block the toolbar from animating while the lab loads. This is not enough.

**Comment by Mugurell** [comment]
Setting E5 as estimation for all the Fenix and AC changes + GV followups.

**Comment by Mugurell** [comment]
Removing this from Kanban since it's waiting for GV.
Will keep an eye for when things change so continue the work on it.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible. Verified on latest Nightly (210406 05:01 - GV89).
Device used: HTC Nexus 9 with Android 7.1.1.

**Comment by sflorean** [comment]
Issue is still reproducible for the following case:
1. Open reddit.com.
2. Wait for the page to load and scroll up, in order to hide the toolbar.
3. Check the Reddit banner.

Expected: no visual issues are displayed.
Actual: the placeholder for toolbar is displayed, when the banner is ON.

Not reproducible when the page is loading, and the toolbar is fixed.

**Comment by Mugurell** [comment]
@ QA: The last part with the toolbar expanding when the bottom banner appears should be resolved after https://github.com/mozilla-mobile/android-components/pull/10805. Please help verify.

**Comment by SoftVision-LorandJanos** [comment]
The toolbar works as expected on the latest Nightly build (93.0a1 - 2021-08-25T05:10:54.365489).
Verified using the following devices:
- Google Pixel 4 (Android11).
- Xiaomi Mi11 Lite (Android 11).
- LG Nexus 5 (Android 6.0.1).

Closing the ticket as verified. Removing the QA needed label.
