### ISSUE TITLE
Include Report Site Issue on menu in nightly/debug

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18032]
Meta: #17796

UX point of contact: @violasong (Victoria)

Figma designs (bottom right, labeled "new tab menu"): https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

## Acceptance criteria
**This work should be behind a feature flag**
* Report site issue item should be available on nightly and debug (this is how it is currently implemented)
* It should be placed right above the divider for "Add to home screen" 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/43795363/109993409-e102d380-7cd1-11eb-864f-60d574492cdc.png">

**Comment by violasong** [comment]
Sorry for the delay on this! 

I think the placement that makes the most sense is at the bottom of the "Find in page" section. I've updated the "full list with all possible conditional items" mockup in "Final design" to reflect this.
