### ISSUE TITLE
[Bug] Facebook/Messenger "open with..." links unsupported

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#18046]
## Steps to reproduce

1. Configure Android without a default browser

2. Tap an external link in Facebook or Facebook Messenger to open the link in their built-in browsers

3. Tap the burger menu

4. Tap "Open with..."

### Expected behavior

The system lists all browsers and other apps supporting the link

### Actual behavior

The system excludes Firefox browsers irrespective of edition (lists Chrome, Brave, etc., but not Firefox)

### Device information

* Device manufacturer: Samsung
* Device model: Note 9
* Android version: 10
* Firefox for Android versions: Daylight 85.1.3 (Build #2015792283), Beta 86.0.0-beta.5 (Build #2015793427), Nightly 210217 17:01 (Build #2015793867)

**Comment by mcarare** [comment]
Tested this on Android 9 and both Nightly and Release (85.1.3) versions show up in the picker. Can QA also test this on different devices? (At least one with Android 10, or maybe a Samsung device)

**Comment by amedyne** [comment]
Looks similar to https://github.com/mozilla-mobile/fenix/issues/17963

**Comment by abodea** [comment]
Tested with Samsung Galaxy S10+ (Android 10) on the latest Nightly (or with any Firefox browser) and I was not able to reproduce this issue.
Note that I was able to select Nightly from the list and open the webpage without problems.
@mrandreastoth can you please re-check this and add a video when you reproduce the issue?
Remvoing `eng:qa:needed` until further notice.

**Comment by mrandreastoth** [comment]
> @mrandreastoth can you please re-check this and add a video when you reproduce the issue?

As requested...

https://user-images.githubusercontent.com/26897855/108909276-a2f81680-7624-11eb-8989-9ee1d6d8ef05.mp4

**Comment by mrandreastoth** [comment]
This issue still remains forcing me to open links via different browsers. It's really annoying and also means Firefox doesn't see as much use as it should. In fact, I'm starting to like Brave, although I do miss some Firefox features that Brave doesn't have. But this is not good for Firefox's reputation. As such this issue must be taken more seriously.

**Comment by mrandreastoth** [comment]
Still remains an issue.

### Version

Firefox Nightly for Android 210410 17:02 (Build #2015803851)
### Device

Samsung Note 9, Android 10
