### ISSUE TITLE
[Bug] Web Push notification never comes

### ISSUE THREAD

**Issue by Simounet** [mozilla-mobile/fenix#18045]
## Steps to reproduce
- Go to https://serviceworke.rs/push-get-payload/
- Click on the "Request sending a notification!" button

### Expected behavior
You should receive a push notification 5 seconds after

### Actual behavior
The notification never comes.

### Device information
- Honor 9
- Android 9
- Firefox for Android Nightly 210211
 
Thanks!

**Comment by jonalmeida** [comment]
One issue here is that we do not prompt for notification access until you touch the screen before the request is made from web content. See more at [this blog post](https://blog.mozilla.org/firefox/block-notification-requests/).

There is an error thrown from the `nsIPushNotification.notifyPush` when the notification data is consumed:

```
2021-02-18 12:12:54.654 25378-25415/? D/GeckoViewPushController: onEvent GeckoView:PushEvent {"data":null,"scope":"https://serviceworke.rs/push-get-payload/"}
2021-02-18 12:12:54.655 25378-25415/? E/GeckoConsole: [JavaScript Error: "NS_ERROR_XPC_NOT_ENOUGH_ARGS: Not enough arguments [nsIPushNotifier.notifyPush]" {file: "resource://gre/modules/GeckoViewPushController.jsm" line: 59}]
    onEvent@resource://gre/modules/GeckoViewPushController.jsm:59:24
```

**Comment by hakkikaancaliskan** [comment]
![Screenshot_20210218-111843_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/108326315-26f06f80-71db-11eb-8a60-7a678be31951.png)

Notifications also not working while permissions granted.
I think I've never received notification from any website (including twitter etc.)

Latest nightly, android 11

**Comment by jonalmeida** [comment]
> NS_ERROR_XPC_NOT_ENOUGH_ARGS: Not enough arguments

I've filed BZ-1693477 since the cause is possibly in GeckoView handling the notification.

**Comment by jonalmeida** [comment]
@Simounet the GeckoView bug was fixed 2 months ago, so I think this issue should be resolved here. Leaving open for confirmation.

**Comment by Simounet** [comment]
@jonalmeida I tried but it failed. No notification received. Did it work for you?

**Comment by jonalmeida** [comment]
> One issue here is that we do not prompt for notification access until you touch the screen before the request is made from web content. See more at [this blog post](https://blog.mozilla.org/firefox/block-notification-requests/).

@Simounet were you able to confirm that are not running into this (intentional) behaviour? If it's possible, device logs would be handy!

**Comment by hakkikaancaliskan** [comment]
I tried and after a few touches i received the notification.

**Comment by Simounet** [comment]
Ok, I just get it working on the main channel (not Nightly). Closing this issue. Thanks for your help.
