### ISSUE TITLE
[Bug] "Download complete" pop-up is not displayed in custom tabs

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18049]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Set Fenix as default browser. 
2. Go to Gmail and open a custom tab (https://www.thinkbroadband.com/download).
3. Download a file.

### Expected behavior
"Download complete" pop-up is displayed after the file is downloaded.

### Actual behavior
"Download complete" pop-up is not displayed.

### Device information
* Device vendor / model and Android version: Pixel 3 (Android 11), Samsung Note 10 (Android 11), OnePlus A3 (Android 6.0.1), 
* Firefox for Android version: RC 84.1.3, RC 85.1.3, RC 86.1.0, Beta 86.0.0-beta.5, Nightly 2/18

![20210218_155644](https://user-images.githubusercontent.com/58466444/108367404-1d2e3280-7202-11eb-8485-bcc3414cd632.gif)

**Comment by Amejia481** [comment]
A patch for this issue is on master, QA team please help us to verify the issue is fixed.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 2/19 with the following devices: Pixel 3 (Android 11), Samsung Note 10 (Android 11), LG G7 FIT (Android 8.1.0).

**Comment by pascalchevrel** [comment]
Will this be uplifted to the 86 branch?

**Comment by Amejia481** [comment]
We are going to wait some baking time on nightly and uplift it on the next dot release.
