### ISSUE TITLE
[Bug] Intermittent build-ist task failures: curl: (16) Error in the HTTP2 framing layer

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#18067]
Observed twice today during download of https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip

* [bump android-components](https://treeherder.mozilla.org/logviewer?job_id=330240252&repo=android-components)
* [decision task](https://treeherder.mozilla.org/logviewer?job_id=330441490&repo=fenix)

```
[task 2021-02-18T15:33:42.935Z] Successfully installed enum34-1.1.10 future-0.18.2 mozilla-version-0.5.3
[task 2021-02-18T15:33:42.976Z] + taskcluster/scripts/decision-install-sdk.sh
[task 2021-02-18T15:33:42.977Z] + export 'CURL=curl --location --retry 5'
[task 2021-02-18T15:33:42.978Z] + CURL='curl --location --retry 5'
[task 2021-02-18T15:33:42.979Z] + ANDROID_SDK_VERSION=3859397
[task 2021-02-18T15:33:42.980Z] + ANDROID_SDK_SHA256=444e22ce8ca0f67353bda4b85175ed3731cae3ffa695ca18119cbacef1c1bea0
[task 2021-02-18T15:33:42.981Z] + SDK_ZIP_LOCATION=/builds/worker/sdk-tools-linux.zip
[task 2021-02-18T15:33:42.982Z] + curl --location --retry 5 --output /builds/worker/sdk-tools-linux.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
[task 2021-02-18T15:33:42.986Z]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[task 2021-02-18T15:33:42.986Z]                                  Dload  Upload   Total   Spent    Left  Speed
[task 2021-02-18T15:33:42.986Z] 
[task 2021-02-18T15:33:43.634Z]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[task 2021-02-18T15:33:43.635Z] 100  130M  100  130M    0     0   201M      0 --:--:-- --:--:-- --:--:--  201M
[task 2021-02-18T15:33:43.635Z] curl: (16) Error in the HTTP2 framing layer
```

**Comment by Archaeopteryx** [comment]
@MihaiTabara This might block releases in the future. The [android-components nightly task](https://treeherder.mozilla.org/jobs?repo=android-components&group_state=expanded&selectedTaskRun=W38VLChYTSmLyr--uU40Yg.1&resultStatus=testfailed%2Cbusted%2Cexception%2Cretry%2Cusercancel&revision=4c4e20dac915d28c83aa6a26b7cfc4207b47c1f3) need 4 runs to succeed, the fenix one failed its first two runs so far.

**Comment by MihaiTabara** [comment]
I wonder whether increasing the verbosity level could help with debugging this in the future. Unclear to me whether this is curl misbehaving or something on our end.
