### ISSUE TITLE
[Bug] PDF viewer toolbar on an internet archive page is not visible after rotating the device 

### ISSUE THREAD

**Issue by cbertoldi** [mozilla-mobile/fenix#18073]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open this address https://archive.org/details/7Habits2014PDF/page/n24/mode/1up
Rotate the phone in landscape mode.
My address bar is on the bottom. I have to say that I did not try to reproduce the issue while having it on top.
I experience the same issue also when playing an embedded (YouTube, Vimeo...) video.

### Expected behavior
I expected the control bar of the PDF viewer to be visible.
Behaviour in Google Chrome: 
![Screenshot_20210219-074931_Chrome](https://user-images.githubusercontent.com/669704/108480017-b870e780-7296-11eb-9a45-7b8bbd2279d0.jpg)

### Actual behavior
The control bar of the PDF viewer is invisible. 
![Screenshot_20210219-075436_Firefox](https://user-images.githubusercontent.com/669704/108480041-be66c880-7296-11eb-9b33-1649fea26eaf.jpg)

### Device information

* Device vendor / model and Android version: Samsung Galaxy S10, Android version 10.
* Firefox for Android version: 85.1.3

**Comment by mcarare** [comment]
@cbertoldi Can you scroll on that page to make the slider (control bar) visible? I am not sure this is actually an issue. That is just web content (a widget in this case) that does not fit in that screen. The content does not appear below the toolbar, it's just not visible on the page. 
Tested this on different screen sizes, and in some, the slider shows up entirely visible.

**Comment by cbertoldi** [comment]
@mcarare No, I can't, that's exactly my problem. If I scroll on the page only the PDF scrolls down.
I think that I forgot to mention that I switched to the full screen view of the PDF viewer (the same when playing a video).
That's why I believe that this is a bug. The control bar should always be visible in full-screen mode.

**Comment by mcarare** [comment]
@cbertoldi I see. I can reproduce this, but not at the first rotation.  After several rotations to portrait/landscape, the page does not load the toolbar anymore, even in portrait orientation. The viewer seems to be stuck in a zoomed-in or zoomed-out state.

I can reproduce this issue on Chrome also if I zoom in before rotating the device. So it might be something wrong with the website viewer itself.

**Comment by cbertoldi** [comment]
@mcarare 
One similar example with a Youtube video: https://www.ilpost.it/2021/02/12/animazione-cartoni-animati/ There there is the video "Every recycled Disney Shot". If I put it in full-screen mode with Firefox I do not see the Youtube overlay to play/pause see the video and so on.
On Chrome the overlay is displayed correctly.
I don't know how helpful this information is, but on the "old" Firefox for Android this behaviour did not occur.

To me it appears as the same behaviour the PDF viewer display.

**Comment by mariansima** [comment]
Could not reproduce this issue on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29
