### ISSUE TITLE
Listing all the products together for better reach

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18074]
**What is the growth opportunity you want to see solved?**
Listing all the products on the homepage to reach more users, and since they use one product, they are most likely to be comfortable with other products.
This is popularly termed [Cross Media marketing](https://www.marketing-schools.org/types-of-marketing/cross-media-marketing/#section-4).

**How do you know that this problem exists today? Why is this important?**
After using Mozilla firefox for about a decade, I still don't know all the products of the community and having a [Questionnaire testing](https://www.pewresearch.org/methods/u-s-survey-research/questionnaire-design/) on the same to classmates, I realized no one is aware of it.

 **How to measure design's effectiveness?**
1. [A/B testing](https://www.userzoom.com/ux-library/comprehensive-guide-to-ab-testing/) - A quick A/B with my classmates with a high-fidelity version.

**Who will benefit from it?**
1. The organization will have a high rise in marketing
2. The user comfortable with one product might like another one too
3. Connectivity

**Comment by kbrosnan** [comment]
This is not a Fenix bug. There is a balance between communicating products that Mozilla makes to users of other products. You might be able to reach out to the marketing team at https://chat.mozilla.org/#/room/#marketing:mozilla.org
