### ISSUE TITLE
Scrolling performance regression with webrender on Mali-T device

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#18078]
This happens on Mali-T GPU device. Given that webrender will be enabled on Mali-T devices on firefox 87, I wonder if some fix will land until then, or will we get a performance regression from opengl.

## Steps to reproduce
1. Open dobreprogramy.pl
2. Try to scroll up and down

### Expected behavior
Scrolling should be smooth.

### Actual behavior
Scrolling is not smooth, it looks as if website is moving by smaller/bigger distance on each iteration of scroll. So when you look at website as it moves, you see it jumping up/down a little (it doesn't mean I observe website moving in opposite direction as scroll direction, just that distance it moves every frame is not "consistent").

I tried to capture on video, but honestly it's not easily visible. The difference is "huge" when looking at device "in person".
https://www.dropbox.com/s/skgaczwpqoygfl3/2021_02_19_12_17_09.mp4?dl=0

When webrender is disabled in about:config, after browser restart, scrolling on this site is butter smooth.

Here is a performance profile captured with webrender on. In this run, website is already loaded when performance profiler is started.
https://share.firefox.dev/37reWki

### Device information

* Android device: Galaxy J7 2017 on android 8.1
* Fenix version: Nightly 210218 19:31 (Build #2015794073)

**Comment by Cheap-Skate** [comment]
Could it be https://bugzilla.mozilla.org/show_bug.cgi?id=1658205?

**Comment by Mikaka27** [comment]
Maybe, I'm not sure how to check :(
Also found that as possible cause: https://bugzilla.mozilla.org/show_bug.cgi?id=1673653

**Comment by jamienicol** [comment]
Thanks for the report @Mikaka27. Looking at the profile it seems most of the time in the renderer thread is spent in `eglSwapBuffers`, which tends to indicate that the GPU is busy. There might be something on that site that we render poorly. So I think this is a new issue.

However, even on a very powerful device I see some stuttery scrolling on that page, which I think is the same as bug 1673653. So it's probably a bit of both.

Do you see poor performance on other websites too, or is it mainly just that one?

**Comment by Mikaka27** [comment]
Hi, unfortunately I see more cases of worse performance with webrender.
Here I'm doing the tests on regular firefox and firefox nightly (since I have webrender enabled on nightly).

They are both fresh installs, no addons installed, nor any settings changed (except for disabled pull to refresh in nightly since it interferes). Firefox is always first in video and firefox nightly (with webrender) second:

1. Gdpr acceptance form on wp.pl
See video: https://www.dropbox.com/s/nvh21gmk98xjpi5/2021_02_23_21_44_08.mp4?dl=0
Same as in first post, the issue is more clearly visible "in person" looking at the device.
Performance profile: https://share.firefox.dev/2Nw1PYc

2. Top of tvn24.pl site
See video: https://www.dropbox.com/s/1vvuu3q4dskhz3l/2021_02_23_22_00_09.mp4?dl=0
Here in addition to worse fps, I can feel like scroll "lags behind" finger in webrender case.
Performance profile: https://share.firefox.dev/3qSLM5i

3. Scrolling over picture in spidersweb.pl
See video: https://www.dropbox.com/s/s1l157yivml82xp/2021_02_23_22_19_14.mp4?dl=0
It stutters when I scroll over this picture of a phone held in hand. More clearly visible "in person".
Performance profile: https://share.firefox.dev/3slCn6x

4. Scrolling over animated ad on antyweb.pl
See video: https://www.dropbox.com/s/qenpmqr3i9o2zi6/2021_02_23_22_26_45.mp4?dl=0
I guess you won't be able to see it, but it happens when "norton antivirus" ad is displayed.
This ad is animated and when I scroll over it I see stuttering.
Unfortunately firefox crashed when I was capturing performance profile, and when I restarted I didn't see this ad again :(

**Comment by jamienicol** [comment]
Thanks @Mikaka27 that's really helpful!

For 1 and 2, I see a huge amount of time spent in `glInvalidateFramebuffer()`, which is pretty odd. I have a Samsung Galaxy A5, which also has a Mali-T830, but "MP3" instead of "MP1". So it's slightly more powerful, and unfortunately that seems to make a huge difference. I see a few slow glInvalidateFramebuffer calls but nowhere near as extreme or as many.

There's probably an underlying problem and it just happens to be exposed via glInvalidateFramebuffer. However, I've made a build where we don't use that function. Would you be able to take another profile for me with this build and see if it helps? https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/BeploPx_T-O8pKU8IxKRCw/runs/0/artifacts/public/build/geckoview_example.apk

Also on 2, we have an issue where we don't cache the contents of the GDPR preferences screen when scrolling. This means we re-render the entire page every frame when we shouldn't. I filed [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1694707) for that specifically. I see you found it already :)

3 looks a lot more like dobreprogramy.pl, in that most of the time is spent in eglSwapBuffers.

**Comment by Mikaka27** [comment]
Hi yeah I found it :)
Unfortunately when I try to install this app I get "app not installed" error. Is there any special procedure to installing this?

The device is rooted (if it should help).

**Comment by jamienicol** [comment]
Do you know if your device runs 32bit or 64bit OS? That's a 64 bit build, so if your device runs 32 bit that might be the problem. I'll make a 32 bit build now.

**Comment by Mikaka27** [comment]
Honestly I'm not sure how to check that :) This is what uname says:


j7y17lte:/data/data/com.termux/files/home # uname -a
Linux localhost 3.18.14-15193845-QB22729397 #1 SMP PREEMPT Wed Mar 20 17:02:39 KST 2019 armv8l

**Comment by jamienicol** [comment]
Yeah I think the `armv8l` means it's a 32 bit OS (running on a 64 bit processor). I'll let you know when the build is ready.

In the meantime, another thing you could try is setting the pref `gfx.webrender.debug.show-overdraw` to true. **Note that after you do this you won't be able to read anything on any webpages** You'll probably need to clear the app storage in android settings or uninstall/reinstall to get back to normal. My theory is that we're giving the GPU too much work to do, and this enables a debug setting which happens to use much simpler GPU shader code. You might be able to tell if scrolling feels smoother or not, even though you won't be able to read the pages.

**Comment by Mikaka27** [comment]
I did that and:

dobreprogramy.pl is smooth
Gdpr on wp.pl is smooth
Top of tvn24 is not smooth
Scrolling over picture on spidersweb.pl is not smooth
Scrolling on antyweb.pl is smooth (but I cannot see what ad is displayed)

tvn24.pl case looks a little better. spidersweb.pl is the same as before.

**Comment by jamienicol** [comment]
That's really interesting. I think it shows it's worthwhile investing some time trying to simplify our fragment shaders.

The tvn24.pl definitely has something bad going on. Even on a Samsung S20 Plus I see 100ms frames. I'll file a separate bug about that.

Here is the 32 bit build: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/SRVDbMlZS8mQc5kv_Ab5UQ/runs/0/artifacts/public/build/geckoview_example.apk  If you could take a couple of profiles with them that would be hugely appreciated! (No need to do them all, maybe just wp.pl and tvn24.pl)

**Comment by Mikaka27** [comment]
Thanks for the build, it works so I now know that I'm running 32 bit android :)

I took all profiles again:
1. dobreprogramy.pl - maybe it's a little better, but definitely not "smooth": https://share.firefox.dev/3sq0EZq
2. wp.pl - huge difference, looks perfectly smooth now: https://share.firefox.dev/3bA4f01
3. tvn24.pl - looks like no difference at all, huge lag behind touching finger: https://share.firefox.dev/37Ksasz
4. spidersweb.pl - maybe a little better, but not "perfect" when scrolling over a picture: https://share.firefox.dev/3qS9azW
5. antyweb.pl - perfectly smooth, but again no ads were shown, don't know why: https://share.firefox.dev/2O1KUfZ

**Comment by jamienicol** [comment]
That's great, thanks very much! I filed bug 1694788 for getting the glInvalidateFramebuffers issue fixed.

And bug 1694752 for the tvnp24.pl issue.

**Comment by Mikaka27** [comment]
Thanks for looking into this. Should I comment here when I stumble upon more cases like this? Or in a new issue?

**Comment by jamienicol** [comment]
Obviously unrelated issues file a new bug. But any webrender performance ones let's keep them here so we don't clutter up the issues, and I'll file new bugs on bugzilla for the specific problems as I diagnose them.

**Comment by Mikaka27** [comment]
Hi,

I've got 2 more cases:

1. This is not strictly scrolling through page, but scrolling through carousel control on gog.com
https://user-images.githubusercontent.com/9214100/109230765-b0003b80-77c5-11eb-81a1-c3614a1f1786.mp4

Performance profile: https://share.firefox.dev/3qUIvm8

2. Scrolling over animated image on store.steampowered.com (to my eye it looks the same as 'antyweb.pl' case that I didn't manage to catch profile for)
https://user-images.githubusercontent.com/9214100/109230881-e2119d80-77c5-11eb-8c94-4665f65036ea.mp4

Performance profile: https://share.firefox.dev/3bzIBsQ

**Comment by jamienicol** [comment]
Hi @Mikaka27, I've got another APK for you to test! https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/XOl4E7ExT7OjFn97mZTEuw/runs/0/artifacts/public/build/geckoview_example.apk

Basically, I believe part of the reason the GPU is overloaded is because we're using a default high precision for all of the varyings. So I've made this build where I've reduced the precision of basically every varying to medium. I expect this to cause quite a few rendering errors, but that's okay for now - This is for testing the performance and that will tell us whether my theory is correct. If it is, I'll spend the time to choose the correct precision for each varying by hand. But there's not point doing that if it won't actually help!

**Comment by Mikaka27** [comment]
Hi,

I'm comparing your build to nightly 210302 17:01 (Build #2015796361) when describing if something feels more smooth.
Just to be clear, videos are not taken on the same run as performance profiles.

I've retested all cases:
1. dobreprogramy.pl
Feels more smooth (as if I get more fps during scrolling), but website is still shaky/janky when scrolling (like I described before that every frame is not moving by constant "distance"). I see this shaking on your build and nightly. Maybe I don't have this fix here: https://bugzilla.mozilla.org/show_bug.cgi?id=1658205
I spotted no rendering errors.
Anyway, video: https://user-images.githubusercontent.com/9214100/109861803-fe975500-7c5f-11eb-9c83-cd0892cae485.mp4
Performance profile: https://share.firefox.dev/3sFXyjU

2. Gdpr form on wp.pl
If I get the "bad" case they look mostly the same. In the good case, maybe your build is a little better, but I'm not sure (if there is a difference it's hardly visible). Small rendering errors can be seen on your build (letters are not so "smooth")
Video (good case): https://user-images.githubusercontent.com/9214100/109863723-461ee080-7c62-11eb-9734-960e49477552.mp4
Video (bad case): https://user-images.githubusercontent.com/9214100/109864511-381d8f80-7c63-11eb-8fb0-94edc87dce19.mp4
Performance profile (good case): Sorry I couldn't catch it, I get the "bad" case each time. I posted 2 performance profiles in comment: "good" and "bad" case on (older) nightly here: https://bugzilla.mozilla.org/show_bug.cgi?id=1694707
Performance profile (bad case): https://share.firefox.dev/2O07INx
I'm still not sure what causes this two cases. It appears "random" to me. Sometimes I'm having a hard time getting the "bad" case, but when I get it, then I get it constantly (even after clearing all data and restarting "geckoview example" or "nightly")

3. tvn24.pl
It definitely is better, but still not smooth unfortunately. Rendering errors can be seen on "round" corners.
Video: https://user-images.githubusercontent.com/9214100/109866353-77e57680-7c65-11eb-806e-486c6ca62b3c.mp4
Performance profile: https://share.firefox.dev/3e7u3mX

4. spidersweb.pl
Looks about the same, in both nightly and your build browser is a little "shaky" when scrolling over some image. But it looks more like "inconsistent" distance moved on each frame, rather than smaller fps, but maybe it only feels that way. I feel that fps is good on this one, both nightly and your build.
Video: https://user-images.githubusercontent.com/9214100/109867965-67360000-7c67-11eb-9485-9bed696a585f.mp4
Performance profile: https://share.firefox.dev/3e5ESGd

5. antyweb.pl
No ads were shown, so scrolling is smooth, small rendering errors seen in letters (same as in #1)
Video: https://user-images.githubusercontent.com/9214100/109866992-47520c80-7c66-11eb-8a97-f992289883b6.mp4
Performance profile: https://share.firefox.dev/3bXIlUz

6. Scrolling through carousel on gog.com
Feels about the same (not smooth) in both cases. Same rendering errors (not smooth text) can be seen.
Video: https://user-images.githubusercontent.com/9214100/109868612-22f72f80-7c68-11eb-94fd-d0ce4c5f4238.mp4
Performance profile: https://share.firefox.dev/3bVnguc

7. Scrolling over animated image on store.steampowered.com
Unfortunately I didn't get same image as before, I've tried scrolling through the page of same game that caused problems before and I got some "jank" on this game. It looks the same on your build and nightly. Same rendering errors (not smooth text) can be seen.
Video: https://user-images.githubusercontent.com/9214100/109870686-b598ce00-7c6a-11eb-91eb-f8ca3e74bde9.mp4
Performance profile: https://share.firefox.dev/3ecwc13

8. Scrolling in gitlab issue (same link as before)
Looks same as before, in both nightly and your build. It's a little shaky when I move over an area shown in video.
Video: https://user-images.githubusercontent.com/9214100/109872000-1e347a80-7c6c-11eb-8796-9465fad488e3.mp4
Performance profile: https://share.firefox.dev/2O0o2Oj

9. Scrolling on crackwatch site (same link as before)
It's hard to say whether there is any difference. It's stuttering when scrolling over pictures. Same rendering errors (not smooth text) can be seen.
Video: https://user-images.githubusercontent.com/9214100/109872808-3789f680-7c6d-11eb-8491-9ca15f4ec868.mp4
Performance profile: https://share.firefox.dev/3sQ6P91

**Comment by jamienicol** [comment]
That's great, thanks. The profiles do look slightly better, so I think it's a worthwhile improvement, but it's obviously not enough by itself.

I also think you might get a slight improvement if you set `gfx.webrender.use-optimized-shaders` to false. It seems our "optimized" shaders can actually be less efficient than the unoptimized versions!

**Comment by Mikaka27** [comment]
> That's really helpful, thanks. The profiles do look slightly better, so I think it's a worthwhile improvement, but it's obviously not enough by itself.
> 
> I also think you might get a slight improvement if you set `gfx.webrender.use-optimized-shaders` to false. It seems our "optimized" shaders can actually be less efficient than the unoptimized versions!

Do you want me to flip this setting in your build and redo the tests?

**Comment by jamienicol** [comment]
No that's okay, I don't want to cause you too much work! I'll wait until I think I have something more significant for you to test

**Comment by Mikaka27** [comment]
Ok, I'd be glad to help.

**Comment by mcomella** [comment]
@Mikaka27 I'm going to refile this on Bugzilla (so that it's tracked with the team working on it) and close this issue. Let me know if that's an issue for you (e.g. you don't have a Bugzilla account and can't chat with folks)!

**Comment by mcomella** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1697663

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mikaka27** [comment]
No, it's fine I have a bugzilla account :)
