### ISSUE TITLE
[Bug] Pull to refresh and dynamic toolbar issues on vulture.com amp site.

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#18072]
### Steps to reproduce
- Access https://www.google.com/amp/s/www.vulture.com/amp/article/best-tv-shows-on-netflix.html
- Scroll up and down

### Expected behavior
- The toolbar dynamic toolbar should animated
- Pull to refresh should not be triggered if the page isn't at the very top

### Actual behavior
- The toolbar dynamic toolbar is not animated
- Pull to refresh is triggered although the page is not scrolled to the top

https://user-images.githubusercontent.com/11428869/108473831-37662000-7297-11eb-8fb0-f3b54181ed03.mp4

### Device 
* Firefox for Android version: Latest Nighty.
* May happen on other websites also.

**Comment by lobontiumira** [comment]
I was able to reproduce the issue on yr.no weather website on Beta 88.0.0-beta.5, 4/7 Nightly build, and RC 87.0.0 with Samsung Galaxy Note 8 (Android 9). 
The website loads and the toolbar is dynamic, but when selecting a specific day from a location, the toolbar is not dynamic anymore.

https://user-images.githubusercontent.com/40694158/113986652-26c53580-9856-11eb-94a6-3fe5431d7579.mp4

**Comment by Mugurell** [comment]
@lobontiumira Can you open a new ticket for the issues on `yr.no` since the various issues still remaining may have different causes and each reported case needs specific investigations?

**Comment by Mugurell** [comment]
In this case I wasn't able and still ain't so to trigger pull to refresh when not being to the very top of the page.
(Though I see the toolbar sometimes being scrollable, sometimes not)
@lobontiumira Have you seen this?

**Comment by lobontiumira** [comment]
I've filed #18897 for the yr.no website not having a dynamic toolbar.
