### ISSUE TITLE
Decide if telemetry expiring in April should be removed or extended.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#18076]
Breakout from https://github.com/mozilla-mobile/fenix/issues/17768.

The metrics expiring in April are:

- https://github.com/mozilla-mobile/fenix/issues/968 - Telemetry App Entry Point 
- https://github.com/mozilla-mobile/fenix/issues/959 - Telemetry Address Bar + Search (search bar tapped, entered_url, performed_search)
- https://github.com/mozilla-mobile/fenix/issues/1024 - Telemetry 3dot menu (browser_menu_action  = browser menu item was tapped)
- https://github.com/mozilla-mobile/fenix/issues/5021 - What's New Telemetry
- https://github.com/mozilla-mobile/fenix/issues/5737 - Telemetry for "Launch links in private tab"
- https://github.com/mozilla-mobile/fenix/issues/11442 - Tab tray tab counter menu item was tapped
- https://github.com/mozilla-mobile/fenix/issues/1040 -  Crash Reporting Telemetry
- https://github.com/mozilla-mobile/fenix/issues/957 - Telemetry for browser context menu
- https://github.com/mozilla-mobile/fenix/issues/974 - Telemetry for Bookmarks
- https://github.com/mozilla-mobile/fenix/issues/977 - Telemetry for Custom tabs
- https://bugzilla.mozilla.org/show_bug.cgi?id=1538011 - Glean
- https://github.com/mozilla-mobile/fenix/issues/1242 - Telemetry for Error Pages
- https://github.com/mozilla-mobile/fenix/issues/969 - Telemetry for Collections
- https://github.com/mozilla-mobile/fenix/issues/9625 - Telemetry for ETP CFR 
- https://github.com/mozilla-mobile/fenix/issues/5583 - Telemetry for Download notifications
- https://github.com/mozilla-mobile/fenix/issues/11578 - Downloads counter
- https://github.com/mozilla-mobile/fenix/issues/15367 - Telemetry for Downloads Management
- https://github.com/mozilla-mobile/fenix/issues/6834 - Telemetry for About page
- https://github.com/mozilla-mobile/fenix/issues/7289 - Telemetry for Dark Theme selection
- https://github.com/mozilla-mobile/fenix/issues/6174 - WebExtensions Telemetry + https://github.com/mozilla-mobile/fenix/issues/8920

cc @vesta0 for deciding if all should be extended.

**Comment by vesta0** [comment]
Let's keep all for now and re-evaluate in June.

**Comment by clientenq** [comment]
Since telemetry data does expire for several reasons it does not sound sufficient to just extend retention to decide later.
Telemetry data is collected and maintained under conditions and should thus per data have valid substantial reasons to be able to keep the data.
How is the current reply sufficient to extend to June?

**Comment by clientenq** [comment]
I sure would expect a human answer to this pricacy question. Just dismissing it does not solve any problem.
