### ISSUE TITLE
[Bug] dom.security.https_only_mode keeps resetting on Quit

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#18089]
## Steps to reproduce
1. Go to about:config and set dom.security.https_only_mode to true.
2. Quit Fenix.
3. Open and check the pref.

### Expected behavior
The pref should be shown in state the user left it (toggled on).

This is how all other prefs behave.
### Actual behavior
The pref is reset (toggled off).
### Device information

* Device vendor / model and Android version: Xiaomi Mi 5
* Firefox for Android version: Nightly 210214 17:02 (Build #2015793291)

**Comment by cadeyrn** [comment]
HTTPS Only mode is not yet supported on Android, there are already a few duplicates. You can follow #16952 for progress.

**Comment by opusforlife2** [comment]
Thanks!
