### ISSUE TITLE
Show warning when closing all tabs

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#18080]
### What is the user problem or growth opportunity you want to see solved?
If I click close all tabs, please show a warning pop-up asking if I'm sure I want to close total xxxx number of tabs, in my case 1800. This will prevent accidental closing of hundreds or thousands of tabs.

### How do you know that this problem exists today? Why is this important?
There is no warning when closing all tabs.

### Who will benefit from it?
Anyone who uses lots of tabs and uses the collection feature.

**Note:**
1. Screenshot attached
![image](https://user-images.githubusercontent.com/12184325/108519113-03f4b700-72d2-11eb-8964-229867b2136b.png)
2. This was reported here: https://github.com/webcompat/web-bugs/issues/67301

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9758)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812884

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
