### ISSUE TITLE
Rotate display when showing a video in full-screen mode

### ISSUE THREAD

**Issue by cbertoldi** [mozilla-mobile/fenix#18083]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
When I play a video using Google Chrome and put it to full screen, the display orientation automatically switches to portrait mode, disregarding of the phone system settings. I like this behaviour, because 99% of the videos I watch are in landscape mode and having to disable rotation lock every time or waiting for the unreliable temporary rotation unlock icon to display is quite annoying.

### How do you know that this problem exists today? Why is this important?
I used Chrome on Android before switching to Firefox and I found this behaviour annoying. If a video is in landscape mode, it should be automatically rotated to use all the display real estate.

### Who will benefit from it?
I believe every body who think that the automatic display rotation functionality is not perfect ;)

**Comment by kbrosnan** [comment]
Duplicate #7602
