### ISSUE TITLE
[Bug] Media notification plays youtube video when no longer on the page

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#18087]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to youtube.com
2. Click on any video and hit play.
3. Observe the media notification showing up (title and playing status).
4. Click the back button to navigate back to the youtube homepage.
5. Observe the media notification status changes.
6. Click the play button.

### Expected behavior
- At 5, the media notification is gone since there is no longer any media elements on the youtube homepage.

### Actual behavior
- At 5, the media notification is still showing up there (without a title of any content playing.
- At 6, surprisingly, the video on the previous page starts playing.

### Device information

* Device vendor / model and Android version: Android 11, Pixel 4
* Firefox for Android version: Nightly 210217 17:01 (Build #2015793867), AC 73.0.20210217143150.

/cc @rocketsroger

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9760)

**Comment by jonalmeida** [comment]
Long shot: This could also be a side-effect of YouTube's design: they allow playing media with a "mini-player" in desktop mode. Maybe our media notification is triggering that hidden feature in the mobile display?

**Comment by sheikh-azharuddin** [comment]
On a side note why the media notification does not havs advance controls like next and previous button as in chrome

**Comment by rocketsroger** [comment]
> On a side note why the media notification does not havs advance controls like next and previous button as in chrome

Definitely a separate issue but I'll look into this to see if we can add those controls as well.

**Comment by eamsen** [comment]
This is likely caused by Youtube's media session implementation. If it doesn't clear the action handlers on navigation, then the media session remains in control of the media. I've filed a [GV bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1694687) to investigate.

**Comment by Taknok** [comment]
Adding a close/kill button would be appreciated too. Fex examples where it would be nice to kill the player when no more needed: - close (pause and remove notification) while the video is not finished yet
- kill the notification player when media is ended and user is no more in the firefox app

Here a example of what could be done:
![image](https://user-images.githubusercontent.com/12498020/122125985-651c3980-ce31-11eb-9375-6d625818d87b.png)

**Comment by rocketsroger** [comment]
> Adding a close/kill button would be appreciated too. Fex examples where it would be nice to kill the player when no more needed: - close (pause and remove notification) while the video is not finished yet
> 
>     * kill the notification player when media is ended and user is no more in the firefox app

To clarify, to add a close button so the user doesn't have to pause and swipe away the notification?

**Comment by Taknok** [comment]
I cannot pause the video while it is playing only with the notification. Also I cannot swipe the notification while the media is played, only when the media is paused. This mean a user as to go the the page pause the media, open the notification bar and remove the media notification. This whole process is not really user friendly.

https://user-images.githubusercontent.com/12498020/122130436-e7a7f780-ce37-11eb-83b4-9181bbe47cf3.mp4

**Comment by rocketsroger** [comment]
> I cannot pause the video while it is playing only with the notification. Also I cannot swipe the notification while the media is played, only when the media is paused. This mean a user as to go the the page pause the media, open the notification bar and remove the media notification. This whole process is not really user friendly.

When the video is playing it cannot be swiped away is expected.  To continue the video/audio in the background requires a foreground service and a notification.

That said I think the issue here is the notification should have a pause play control (similar to your original image)  I'll have to look into why in this case you can't pause it from the notification.  Thanks for letting us know.

**Comment by rocketsroger** [comment]
> I cannot pause the video while it is playing only with the notification.

I can't reproduce this.  Does this happens all the time for your device on twitter?  Or this particular link?  If it's this particular link, can you please add the link here? Thanks

**Comment by Taknok** [comment]
Bug is not consistent to trigger, I manage to trigger it on a New York Times video. But sometimes pausing hide the button, sometimes not. Sometimes swiping the player hide the button in the new popup.

**Comment by rocketsroger** [comment]
> Bug is not consistent to trigger, I manage to trigger it on a New York Times video. But sometimes pausing hide the button, sometimes not. Sometimes swiping the player hide the button in the new popup.
> 
> A close button ensuring the service is destroyed would simplify all of this.

Understood.  Could be a layout problem.  When the notification is expanded (by pulling the notification down) you should see the play/pause button.  This is definitely something we'll have to fix.  Not a great user experience.  Thanks again for letting us know.  Once I have a chance I'll investigate.

**Comment by jonalmeida** [comment]
I haven't run into this bug in a long time. Closing as won't fix.
