### ISSUE TITLE
Provide user search keyword directly in search bar.

### ISSUE THREAD

**Issue by qrqhuang** [mozilla-mobile/fenix#18099]
### What is the user problem or growth opportunity you want to see solved?
I always search keyword with several search engine. like `google`, `baidu`. 
I'd like to show my history search keyword immediately in search bar,  rather than type them again.

### How do you know that this problem exists today? Why is this important?

![image](https://user-images.githubusercontent.com/17166063/108614885-687e5600-7439-11eb-8e4c-97eaf89b112b.png)

This is another browser, It provider my search history `github app` directly. This is what I needed.

### Who will benefit from it?

All users .  Cause mobile is not convenient with copy&paste, It can be smart when user want search previous keyword again.

**Comment by kbrosnan** [comment]
Duplicate #15985

**Comment by qrqhuang** [comment]
@kbrosnan I don't think these are same request.

@liuche Can u take a look.

I've request about to keep the user search history in bar, not about search engine.
