### ISSUE TITLE
runUiThreadCallback blocks first frame & visual completeness for 44ms in COLD MAIN start up

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18093]
Tracking this change in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1693911

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9764)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807318

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
