### ISSUE TITLE
FNX-5253 ⁃ [Bug] Restore all tabs when one is crashing

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1809]
## Steps to reproduce
1. Open multiple tabs.
1. In one tab go to about:crashcontent.
1. Tap Restore tab on the crash reporter.
    1. Expected behavior
All tabs are restored.
    1. Actual behavior
Only the crashed tab is restored, the others are left with about:blank
    1. Device information

* Android device: any
* Fenix version: 4/18

**Comment by sblatz** [comment]
We should use this API: https://github.com/mozilla-mobile/android-components/pull/3275

**Comment by sblatz** [comment]
Future implementation will be here: https://github.com/mozilla-mobile/fenix/issues/3170

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/7 build. Devices: Pixel (Android 9), Nexus 5 (Android 6)
