### ISSUE TITLE
[Bug] GLAM release data seems to include builds we don't build

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18092]
If we look at GLAM data on the release channel ([example](https://glam.telemetry.mozilla.org/fenix/probe/geckoview_startup_runtime/explore?app_id=release&ping_type=*&ref=2021021621)), **there is a discrepancy with the date we create builds and that build ID dates that are present in the Glean data.** For example, so far in February up to the 16th, we've made three builds on 2/5, 2/8, and 2/16 (via [taskcluster](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.release.2021.02)). In GLAM, over the same date range, we see five builds for 2/5 (ours), 2/7 (unknown), 2/9 (probably our 2/8 build), 2/10 (unknown), and 2/16 (ours).

Furthermore, the "unknown" builds seem to have different characteristics than the our builds:
- our builds have many users & unknown builds have fewer users
- the violin plots of the results are consistent inside of our builds and inside of unknown builds but not between them

For a visualization, here are the violin plots of our builds:
![image](https://user-images.githubusercontent.com/759372/108568203-7eb3d700-72be-11eb-86f7-63882321b42a.png)![image](https://user-images.githubusercontent.com/759372/108568216-870c1200-72be-11eb-8358-abf4868b15bc.png)

And the violin plot of unknown builds:
![image](https://user-images.githubusercontent.com/759372/108568282-b02ca280-72be-11eb-8050-f87892b38fe8.png)![image](https://user-images.githubusercontent.com/759372/108568296-b6bb1a00-72be-11eb-89d3-486e5ff004fa.png)

Given this is a start up duration probe, this implies _the behavior for our builds are different than the devices for unknown builds_. The behavior is bimodal.

I see similar behavior on other probes too ([example](https://glam.telemetry.mozilla.org/fenix/probe/events_total_uri_count/explore?app_id=release&ping_type=*&ref=2021021621)).

**My theory is that someone (fdroid? Mozilla Online?) builds fenix independently of us** and redistributes it to a non-trivial user base but the telemetry numbers get included with our numbers on GLAM in way that's unintuitive to the average GLAM viewer.

That being said, if this is true, I think it's undesirable to include these builds in GLAM because:
1. it's hard to see trends over time
2. someone has to know that some builds are not ours to avoid misinterpretting data that might not be relevant (e.g. if the redistribution changes code, the probes could be invalid or the redistribution user base is not representative of our target user base)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9763)

**Comment by mcomella** [comment]
Assuming this theory is true, I think the ideal solution is that we filter these builds we don't own into a separate release population data set (or exclude it from collection). Perhaps we could do this at the build level. Alternatives are that we just filter these out in GLAM but anyone doing raw data analysis in sql.tmo may still run into this problem.

**Comment by mcomella** [comment]
To rule out Mozilla Online, we could try filtering on country or locale or there may be a separate `distribution_id`.

**Comment by badboy** [comment]
fdroid's version is distributed under a different app ID (`org.mozilla.fennec_fdroid`) and we helped them disable telemetry even for that.
In general data from other app IDs is not mixed in with the data from the app ID we control. Of course personal builds can re-use the same app ID.

**Comment by wlach** [comment]
IMO the "right" way to solve this kind of problem is to add an index of Fenix's "official" builds to BuildHub: https://bugzilla.mozilla.org/show_bug.cgi?id=1622948

Without a centralized database of what's official and what isn't, there's bound to be issues like this. I believe that GLAM for desktop already uses the buildhub data (which is available inside BigQuery) to do exactly this.

**Comment by l-hedgehog** [comment]
Hi @mcomella , @badboy & @wlach:

I don't have access to GLAM yet [1], but I can confirm for now Fenix as distributed by Beijing office to Chinese app stores are built separately, and corresponding to the above mentioned dates, 85.1.2 on Feb. 7th & 85.1.3 on Feb. 10th [2].

The majority of users in mainland China don't have access to Play store and are on our builds. I'm wondering whether the differences could be a result of the popularity of different phone brands/models in this region vs. the rest of world.

In case it's unclear, our builds are distributed using the same id `org.mozilla.firefox` in these Chinese app stores, and as I understand there's a plan to move our build into releng automation.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1693956
[2]: https://sql.telemetry.mozilla.org/queries/77101

**Comment by mdboom** [comment]
[This query](https://sql.telemetry.mozilla.org/queries/78158/source) also confirms that these builds are coming from pings with a `distribution_id` set to `MozillaOnline`.

**Comment by mdboom** [comment]
I created an issue for Data Science to provide some guidance on where they would *like* this to go (apologies for the internal link): https://jira.mozilla.com/browse/DS-1456?filter=-2

**Comment by l-hedgehog** [comment]
> 
> I don't have access to GLAM yet, ...

I got access and can now understand why showing data from our builds could be confusing. I'm not sure but at least for `geckoview_startup_runtime` maybe it makes sense to aggregate on geckoview build ids instead of fenix ones?

> 
> ... I'm wondering whether the differences could be a result of the popularity of different phone brands/models in this region vs. the rest of world.

As I suspected, [popular brands are indeed very different here](https://sql.telemetry.mozilla.org/queries/78283#194680); I also tried to write queries to see [whether the percentiles differ among users from different regions using the "official" builds](https://sql.telemetry.mozilla.org/queries/78376/source#194859) [(& `events_total_uri_count`)](https://sql.telemetry.mozilla.org/queries/78377/source#194861).

**Comment by mcomella** [comment]
This seems important to address if we want to use GLAM.

**Comment by mcomella** [comment]
This problem seems to have gotten worse: _tldr; historical data on monthly or larger aggregation scales isn't useful because it's displaying data from builds that have unrepresentative user populations and not displaying the representative data points._

For specifics, if I look at [Beta Month data for a specific probe](https://glam.telemetry.mozilla.org/fenix/probe/perf_startup_cold_main_app_to_first_frame/explore?aggType=avg&app_id=beta), one reference point seems to have a reasonable client count while all 8 other presented reference points have 84-100% fewer clients (as reported by the dashboard) and likely come from builds that aren't our Google Play builds. The same problem exists in quarterly data. The only representative displayed reference point is the current one and having one data point isn't useful for observing changes in data. I believe there are additional data points that might be more representative but are being hidden on the larger aggregation scales (e.g. monthly, quarterly).

**Comment by mcomella** [comment]
> Caveat: a root cause could be that this probe is too new or didn't get data renewal in time, so it's missing data points.

This issue also exists on [the `network_dns_start` probe](https://glam.telemetry.mozilla.org/fenix/probe/network_dns_start/explore?aggType=avg&app_id=beta&ping_type=*&timeHorizon=ALL) which doesn't seem to have either of these problems.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811593

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
