### ISSUE TITLE
[Bug] Top Sites cannot be renamed

### ISSUE THREAD

**Issue by CyberBismarck** [mozilla-mobile/fenix#18095]
On Firefox for Android, the application will not let the user rename Top Sites in the new tab page.

## Steps to reproduce
- Open Firefox for Android
- Add a site to Top Sites
- Open new tab to display Top Sites
- Tap and hold one chosen Top Site
- Choose "Rename" from drop down menu
- Change name of site
- Tap "OK"

### Expected behavior
The name of the Top Site will be changed. 

### Actual behavior
The name of the Top Site remains the default name chosen when the Top Site is first added.

### Device information

* Device vendor / model and Android version: Samsung S20 running Android 11
* Firefox for Android version: 85.1.3

**Comment by CyberBismark** [comment]
I just closed and reopened the app and that seemed to show the changed labels.

**Comment by mcarare** [comment]
This looks similar to https://github.com/mozilla-mobile/fenix/issues/17542, probably the same cause.
Can QA test this STR on Nightly and Beta?

@CyberBismarck Can you reproduce this on the latest Beta or Nightly? Thank you!

**Comment by CyberBismarck** [comment]
> This looks similar to #17542, probably the same cause.
> Can QA test this STR on Nightly and Beta?
> 
> @CyberBismarck Can you reproduce this on the latest Beta or Nightly? Thank you!

Just tried it on the latest Nightly (build #2015796171). I couldn't reproduce the bug on there; the rename function works as expected.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview RC 86.1.1, 87.0.0-beta.2 and Nightly 210303.
### Devices used
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)
