### ISSUE TITLE
[Bug] Autofilled url part is not erased most of time

### ISSUE THREAD

**Issue by ohhai** [mozilla-mobile/fenix#18096]
Usecase:
I'm entering several words in address bar to search them in default search engine. For example "test some word"

ER:
Search is performed exactly at the entered words.

AR:
Autofilled part is sometimes appended to the last word. For the mentioned example it appears as "test some wordingexample.com", if you visited "testingexample.com" previously.

How it happens:
Entering space between words erases autofilled part - but not instantly for some reason. My phone is not slowest but it takes seconds to remove the autofilled part ("ingexample.com" for this case). So if you don't wait after typing, the autofilled part did not manage to disappear - and is appended to search request.

Device: LG V20
Android 8
Firefox 85.1.3

Might be related: #12525 #3475
(I use "Hacker's Keyboard" (org.pocketworkstation.pckeyboard), not the stock one)

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce your issue but was unable to. It was probably fixed by https://github.com/mozilla-mobile/fenix/issues/12525. I will mark this issue as closed, if the problem persists feel free to reopen the issue.

**Comment by ohhai** [comment]
Still happens on latest stable 96.3.1, build #2015860775
I did search for "transferwise fee" and FF substituted "transformation.org.ua" since both start with "transf":

![photo_2022-02-08_02-20-39](https://user-images.githubusercontent.com/3885783/152995329-a7d90a2e-6aab-480c-829a-3b4ea8aa0c33.jpg)

**Comment by ohhai** [comment]
@LaurentiuApahideanSV  seems like I can't reopen this because it was closed not by me.
