### ISSUE TITLE
[Bug] "Delete browsing data on quit" should reload extensions to prevent their volatile browsing data to be leaked

### ISSUE THREAD

**Issue by hackademix** [mozilla-mobile/fenix#18103]
## Steps to reproduce
1. Install the NoScript extension
2. Open https://maone.net
3. From the Addons menu reach NoScript and set maone.net's policy preset to "Temp. TRUSTED"
4. Use the Quit menu enabled by the "Delete browsing data on quit" option
### Expected behavior
When rechecking maone.net's NoScript settings, it should be back to DEFAULT (no stored policy)
### Actual behavior
maone.net is still "temp. TRUSTED", because the extension has not been reloaded and therefore the volatile status is still there.

### Discussion
Even a notification to let affected extensions which seek to preserve users' privacy expectations to either cleanup or just calling browser.runtime.reload() would help, but I believe the best course is the browser forcibly reloading them, in order to make the "Quit" command behave less surprisingly if compared with desktop.

See also https://github.com/hackademix/noscript/issues/174

### Device information
Any device, Fenix >= 85

**Comment by mariansima** [comment]
Could not reproduce this issue on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29
