### ISSUE TITLE
I want to pass Cookie Info on browser

### ISSUE THREAD

**Issue by ChiY119** [mozilla-mobile/fenix#18100]
My app is using Geckoview and Webview, together.
My app is trying to login to our website via API communication.
App login successfully to website on API communication and I saved the cookie info.
When I'm calling website domain in app's webview, saved Cookie was used.
So I can enter the website without any login process via app's webview by using API login .
But, When I'm calling this domain on Geckoview, I think, cookie is not being used.
Website login screen is appearing to me on Geckoview.
I used the okhttp library to login API of website.
I'm based on working this fenix application.
///////////////
How can I solve this issue?
Really, I want to login without any login page on Geckoview by using Cookie.
If you can reply to me, thanks.

**Comment by kbrosnan** [comment]
This should be discussed with the [Geckoview devs](https://chat.mozilla.org/#/room/#geckoview:mozilla.org). This is not related to Fenix closing.
