### ISSUE TITLE
Searching text on page can not be started using keyboard

### ISSUE THREAD

**Issue by grmblgrmbl** [mozilla-mobile/fenix#18109]
Searching text on page can not be started using a keyboard, neither by pressing CTRL-F nor by pressing a dedicated search key. Function can only be invoked via the menu.

**Comment by mcarare** [comment]
@grmblgrmbl Thank you for your report. This has already been requested here: https://github.com/mozilla-mobile/fenix/issues/3729. Closing this as duplicate.
