### ISSUE TITLE
[Bug] Leanplum user & device ID empty

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18105]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

This bug doesn't break any feature but I just wanted to let you guys know 🤷

Turning on/off telemetry not fixing

![Screenshot_20210221-220547_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/108635577-2bde4900-7491-11eb-95c1-e0678f688b7c.png)![Screenshot_20210221-220550_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/108635579-2f71d000-7491-11eb-9cd4-2bba99180ab9.png)

### Device information

* Device vendor / model and Android version: Xperia XZ1 Android 11
* Firefox for Android version: Nightly 210221 17:02 (Build #2015794635)
AC: 73.0.20210218143118, 525591d8b
GV: 87.0a1-20210218092411
AS: 70.0.0

**Comment by AndiAJ** [comment]
Hi @hakkikaancaliskan , I **wasn't able to reproduce** this matter on the latest **`Nightly 210222`** using the following devices:
• Google Pixel 4 XL (Android 11)
• Google Pixel 3a (Android 11)
• Samsung Note 10(Android 11)
• Samsung Galaxy S10+ (Android 10)
• Huawei Mate 20 Lite (Android 10)
• Sony Xperia Z5 Premium (Android 7.1.1)
• OnePlus A3 (Android 6.0.1)
 
❓ **Are the Leanplum identifiers still missing after you update to the latest version ?**

**Comment by hakkikaancaliskan** [comment]
@AndiAJ it's still missing with 2/22 build
Maybe that's something with my region?

**Comment by AndiAJ** [comment]
Could you also check if **`Firefox News`** is enabled in the Notification Settings ?

**Comment by hakkikaancaliskan** [comment]
![Screenshot_20210222-130051_Ayarlar](https://user-images.githubusercontent.com/17825767/108692729-04799180-750e-11eb-9114-a522f569bd7f.png)
Yep, it's enabled.

**Comment by st3fan** [comment]
Leanplum is not enabled in your region. It is limited to this list:

https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/main/java/org/mozilla/fenix/components/metrics/LeanplumMetricsService.kt#L226-L241

The output in that hidden screen is confusing - we may have to fix that to clarify.

**Comment by hakkikaancaliskan** [comment]
@st3fan is it changed recently because it was enabled a few days ago

**Comment by hakkikaancaliskan** [comment]
Anyway, that's intented behavior
