### ISSUE TITLE
Enhanced Tracking Protection icon broken for Custom settings

### ISSUE THREAD

**Issue by ShintoPlasm** [mozilla-mobile/fenix#18101]
### Steps to reproduce:
1. Three-dot menu >> Settings >> Enhanced Tracking Protection
2. Select 'Custom'. It doesn't matter if you change any of the subsequent settings.
3. Go to a website where normally ETP blocks something (e.g. https://www.hivehome.com/).

### Expected behaviour:
1. ETP icon needs to colour purple in the address bar.
2. When tapping on the ETP icon, the Enhanced Tracking Protection toggle should be 'on', with the type(s) of blocked content listed below it.

### Actual behaviour:
1. ETP icon does not change colour.
2. The ETP toggle is 'off', even though some content is blocked in line with the 'Custome' settings selected.

### Device and app info:
- Google Pixel 3a
- Android version 11 (Android Security update: 5 February 2021)
- Firefox Daylight version 85.1.3

See attached screenshots for examples and full Firefox version info:

![Screenshot_20210221-074636](https://user-images.githubusercontent.com/35544416/108619967-89867d00-7420-11eb-86cf-1c5188f08c07.png)
![Screenshot_20210221-074656](https://user-images.githubusercontent.com/35544416/108619968-8a1f1380-7420-11eb-997c-fc7c4861bdd2.png)
![Screenshot_20210221-083905](https://user-images.githubusercontent.com/35544416/108619969-8ab7aa00-7420-11eb-8666-20874cb2e4a6.png)

**Comment by sflorean** [comment]
Verified a fixed on Nightly 3/3.
