### ISSUE TITLE
[Bug] Crash Report [@ mozilla::java::GeckoAppShell::GetNetworkLinkType ]

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#18113]
## Steps to reproduce - not able to reproduce it again
1. I had about 25 tabs opened.
2. I was signed in with an old Fxa account.
3. I switched tabs by swipping left-right between tabs.

### Expected behavior
Tabs are switched without issues.

### Actual behavior
The app crashed.

### Device information
* Device vendor / model and Android version: Sony Xperia Z5 Premium (Android 7.1.1)
* Firefox for Android version: RC 86.1.0

https://crash-stats.mozilla.org/report/index/d0659b12-d974-46aa-b759-c4a6a0210222#tab-rawdump

**Comment by rocketsroger** [comment]
Related https://bugzilla.mozilla.org/show_bug.cgi?id=1694179

**Comment by amedyne** [comment]
Fix available in Nightly. See bugzilla ticket updates.
