### ISSUE TITLE
Restore Default Search Engine option

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#18111]
Taken from https://github.com/mozilla-mobile/fenix/issues/17044#issuecomment-782982737:

@brampitoyo  wrote:

> Additionally, we don’t have a `Restore Default Search Engine` functionality, but may want to consider it in the future. This is how it should work.
> 
> - When `Restore Default Search Engine` is executed, the original search config order should be restored. The default should also be restored.
>     - Example: My default is `Wikipedia`
>     - I delete it and other search engines
>     - I tap on `Restore Default Search Engine`
>     - Result: original search config order is restored (Google, Bing, Amazon.com…). Set `Google` as default.

**Comment by mcarare** [comment]
Needs UX for mock-ups of the UI and strings for option / confirm dialog. 

Also, need clarification from UX: restore should restore de initial search engine list (set according to region, etc) and also delete custom engines added (if any)?

**Comment by brampitoyo** [comment]
@mcarare `Restore Default Search Engine` should not delete custom user-added search engines.

What happens instead:
- If a custom engine has been set as a default by the user, it will be unselected. The default goes back to the one set by the original search config
- If a custom engine has been moved up or down by the user, it will be reverted to the original position when it was first added, which is usually the last position on the list

Unfortunately, I currently have no capacity to mock up this UI. Let’s look into it again when there’s a little more time and priority.

**Comment by RiyaJ2311** [comment]
Hello!
I'm Riya, an Outreachy applicant.
I'm interested in this issue and would love to be assigned to it.
@brampitoyo @mcarare how can I contribute?

> Unfortunately, I currently have no capacity to mock up this UI. Let’s look into it again when there’s a little more time and priority.

**Comment by mcarare** [comment]
@RiyaJ2311 This is not ready to work on yet.
