### ISSUE TITLE
Bunching similar apps together 

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18123]
**How to reproduce?**
1. Open firefox App
2. search any website say amusebag.in
3. Click the share option
4. Search for the app 
![image](https://user-images.githubusercontent.com/48223671/108836250-a1aff500-75f6-11eb-91cd-b9d1c8b47eab.png)

5. Search for how to share in an app
6. DONE

**What is the user problem or growth opportunity you want to see solved?**
1. Multi-step process before actual usage
2. Using the same logo creates confusion as[ visual attracts more attention than text](https://slate.com/technology/2013/06/how-people-read-online-why-you-wont-finish-this-article.html)
3. Once, selecting a wrong option, a user gets irritated and doesn't want to repeat the cycle

**How do you know that this problem exists today? Why is this important?**
I am one of those people who tend to select the first option of the suggested app and that turns out to be wrong, so frustrates me.

** Who will benefit from it?**
1. Users
2. Org as maximum users will be retained

### 
If Mozilla could resolve this it would be great otherwise if it's Android's issue, this could be closed.

**Comment by mcarare** [comment]
@RiyaJ2311 The icons and text are provided by the third-party apps in that list, not by Firefox.

**Comment by RiyaJ2311** [comment]
Alright, thank you for clarifying @mcarare 
Since the issue doesn't hold significance now, I am closing it.
