### ISSUE TITLE
FNX-5257 ⁃ [Bug] Bookmarks' menu toolbar is blue

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1812]
## Steps to reproduce
1. Go to library>Bookmarks. 
1. Select a folder.
    1. Expected behavior
The menu's toolbar color is the app's default color.
    1. Actual behavior
The toolbar is blue in root Bookmarks menu and it's folders.
    1. Device information

* Android device: HTC Desire 820 (Android 6.0.1), HTC 10 (Android 8.0)
* Fenix version: Debug build 4/19

**Comment by colintheshots** [comment]
I noticed this yesterday while fixing other bookmark related issues. All the colors in the app were changed recently and this one was incorrect. The fix is already in PR waiting on code review.

**Comment by colintheshots** [comment]
This will be fixed in the next build.

**Comment by sv-ohorvath** [comment]
Verified as fixed on 4/21.
