### ISSUE TITLE
FNX-5258 ⁃ White page for tools.taskcluster.net

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#1813]
When I want to open the site tools.taskcluster.net only a white page will be shown.
The site docs.taskcluster.net/docs will be shown normally. 

Only on Samsung Galaxy Tab A (2016) SM-T580 with Android 8.1.0
No problem with Huawei P smart and Android/EMUI 8.0.0
Both tested with Fenix 1.0.1916 (11081206)

**Comment by LittleAngelwings** [comment]
I closed the issue, cause the issue is gone after I delete app data for fenix

**Comment by LittleAngelwings** [comment]
Reopend... Issue is back after reload the site... Only a blank page is shown

**Comment by ekager** [comment]
I can't reproduce this. Closing. Please reopen if you're still seeing it.
