### ISSUE TITLE
[UX] Confirm dialog before collection link delete

### ISSUE THREAD

**Issue by thirdconspiracy** [mozilla-mobile/fenix#18130]
### What is the user problem or growth opportunity you want to see solved?
For better UX, I'd like to request a confirmation dialog before deleting a collection item. Those X's are really tiny and easy to delete the wrong link.  As an added bonus, a growl to "undo" delete similar to the "switch" growl we see after opening a new tab would be nice.  Thanks!

### How do you know that this problem exists today? Why is this important?
I deleted the wrong bookmark in one of my collections and it deleted without confirm

### Who will benefit from it?
Not just those with fat fingers.  Fitz law suggests the difficulty to correctly hit a button depends on the distance and size.  Android screen is small so the x will always be a small target and near other small targets.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9791)

**Comment by Myuki** [comment]
According to #2725 and #2783, used to have an undo snackbar before. But it has been removed for some reason. It has been added in [Android Team Backlog Staging Board](https://github.com/orgs/mozilla-mobile/projects/70?card_filter_query=collection+snackbar) and hope it will be added again in future. I have many times delete tab accidentally and don't remember what it is.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813250

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
