### ISSUE TITLE
[UX] Use of buttons

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18141]
**What is the user problem or growth opportunity you want to see solved?**
 As a user, I cannot distinguish the buttons, so I can't utilize the feature which actually makes Firefox a bit easier, so I would suggest adding effects on the button so they get highlighted and easily recognizable.
For better UX, I'd like to request a change of color of the icon and shifting them to the "Okay region" from the hard-to-reach area. Thanks!
![image](https://user-images.githubusercontent.com/48223671/108953756-b5f50000-7691-11eb-80af-e3d33511b926.png)
The buttons marked in the red square.
![image](https://user-images.githubusercontent.com/48223671/108953295-facc6700-7690-11eb-9214-3c57f9b25dc4.png)

**How do you know that this problem exists today? Why is this important?**
I never used it till I started contributing to the organization.

**Who will benefit from it?**
“[Fitts’ law](https://lawsofux.com/fittss-law/) states that the amount of time required for a person to move a pointer to a target area is a function of the distance to the target divided by the size of the target.”
Thus, the longer the distance and the smaller the target’s size, the longer it takes.

This can be tested through A/B testing with organisation and to common people through the forums.

**Comment by cadeyrn** [comment]
Your screenshot shows Firefox Lite, but this issues tracker is about Firefox, not Firefox Lite. Firefox has no similar element.

The issues tracker for Firefox Lite is:
https://github.com/mozilla-mobile/FirefoxLite/issues

But please note that there is no longer an active feature development for Firefox Lite.

**Comment by RiyaJ2311** [comment]
Thank you for informing me of the error I made, and even though the firefox lite version is not active, I would like to transfer the issue there, I am closing it here and posting it in the Lite issues.
