### ISSUE TITLE
Address bar search freezes phone when there's sth super long in the clipboard 

### ISSUE THREAD

**Issue by mbalc** [mozilla-mobile/fenix#18142]
## Steps to reproduce
- copy a very, very long string to the clipboard
    - my specific case was that I had copied a save state from [a browser game under this address](https://jacorb90.github.io/Prestige-Tree/) (using "export to clipboard" option) and then forgot about that soon after I was done with backing it up
- (probably optional) have over 100 tabs open gathered over many months of browser usage
- click address bar to begin a search

### Expected behavior
- keyboard instantly pops up as usual and I can search

### Actual behavior
- the whole phone freezes, it takes roghly 30 seconds for the keyboard to show (and the search suggestions area to fill the whole screen) but the phone remains unresponsive until Android finds Firefox process unresponsive and gives me a prompt with an option to kill the app
- restarting the browser and overwriting the clipboard with any random short string fixes the problem - triggering search then proceeds successfully without any issues

### Device information

* Android device: lg g7 thinq, android 10
* Fenix version: see screenshot below

<details>
  <summary>Click to view my Firefox's 'about' page</summary>
  

![Screenshot_20210224-100055](https://user-images.githubusercontent.com/11033790/108996186-5fda8980-769e-11eb-9559-feb5657cc8ea.png)
  
</details>

**Comment by mcomella** [comment]
Triage: this is a really bad experience even if it might not happen that often so let's look into it, especially because it's a part of the search experience. There's some history around perf issues and really long clipboard strings but we were unable to find the bugs.

**Comment by mcomella** [comment]
The PR provided https://github.com/mozilla-mobile/fenix/pull/18759 is a possible fix but the discussion around it has stalled so we closed the PR and will unassign this as low impact as we're focusing in other areas.

**Comment by mcomella** [comment]
Dupe to https://github.com/mozilla-mobile/fenix/issues/21291, which has a merged PR.
