### ISSUE TITLE
Search/address bar won't disappear after entering text

### ISSUE THREAD

**Issue by GottfriedCP** [mozilla-mobile/fenix#18148]
Sometimes after entering search query or URL to the search bar, the bar won't disappear. This happens randomly. To fix it, I need to go to Android home screen and re-open FF.

I am using latest FF 86.1.1 and some addons (this also happens when not using any addon / in private browsing mode).

Sorry I don't know how to properly word this issue, but I took a screenshot below.

Notice the search suggestions and address bar won't go away and obstructing the view.

![Screenshot_20210224-183241_Firefox](https://user-images.githubusercontent.com/4402870/109002158-6a197980-76d8-11eb-96d8-278d4dea8dc7.png)

**Comment by mcarare** [comment]
@GottfriedCP What phone and Android version do you have?

**Comment by GottfriedCP** [comment]
My phone is Sony Xperia H3123 running Lineage OS 17.1 (Android 10)

**Comment by mcarare** [comment]
This looks the same as https://github.com/mozilla-mobile/fenix/issues/15464. Closing this and mention your device there.
