### ISSUE TITLE
[Bug] "Select tabs" button not displayed

### ISSUE THREAD

**Issue by test491** [mozilla-mobile/fenix#18150]
* STR:
open 2 or more websites in normal mode
switch to private browsing mode
open a website
close opened website
Go to normal tabs 
"Select tabs" button not displayed

* expected behaviour
show "Select tabs" button

* actual behaviour
"Select tabs" button not visible

reproducible:
* version: 86.1.1
* version: 87.0.0-beta.1 (Build #2015795065) AC: 73.0.0, 69a800e47 GV: 87.0-20210222154334 AS: 71.0.0
* version: Nightly 210224 (Build #2015795113) AC: 73.0.20210223143117, 05f3e3cc7 GV: 87.0a1-20210222084406 AS: 71.0.0

interesting note (continuation from STR):
go back to pbm
come back to normal bm
"Select tabs" button is visible

excuse cant submit logs.

> android 9, Galaxy J7 Nxt

**Comment by VitalyVPinchuk** [comment]
Hi
Could I try to fix this?

**Comment by amedyne** [comment]
@VitalyVPinchuk we appreciate your help to contribute and help improve Firefox on Android.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 5/3 with Samsung Note 10 (Android 11).
