### ISSUE TITLE
[UX] Adding visual search option along with scan option

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18156]
**What is the user problem or growth opportunity you want to see solved?**
Adding Image search next to the scan button for quick searching through the image.
![image](https://user-images.githubusercontent.com/48223671/109048575-3ef55100-76fd-11eb-9d75-edeaf37d351a.png)
As a user, I want an easier way to do image searching directly like many e-commerce websites uses
![image](https://user-images.githubusercontent.com/48223671/109049645-80d2c700-76fe-11eb-8808-aa0aa4ca0d37.png)

**How do you know that this problem exists today? Why is this important?**
Using e-commerce and browsing daily, I got very comfortable using the visual search option and that creates the need for a visual search option.
The user importance is already specified but as per the norms of the design, there exists the [Law of Similarity](https://www.interaction-design.org/literature/article/the-law-of-similarity-gestalt-principles-1), which is the gestalt grouping law that states that elements that are similar to each other tend to be perceived as a unified group. Similarity can refer to any number of features, including color, orientation, size, or indeed motion.

 **Who will benefit from it?**
1. Frequent users of visual search - According to one statistic, reported here, 62% of millennials and members of Gen Z want to use visual search over all other search types. [Data](https://www.semrush.com/blog/visual-search-guide-benefits-optimizatiion/#:~:text=According%20to%20one%20statistic%2C%20reported,What%20is%20visual%20search%3F)
2. The organization as competitors still haven't rolled this feature out and there is a [steep rise](https://w3-lab.com/rise-visual-search-seo-trend-2020/#:~:text=This%20interesting%20search%20method%20is,Search%2C%20and%20eBay%20Image%20Search.) in the curve of people switching over visual search

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9809)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807722

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
