### ISSUE TITLE
Use SyncedTabsFacts for Synced Tab Telemetry

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#18163]
Collect Synced Tabs Facts to be included in the Glean report.

**Comment by rocketsroger** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/14866

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly 210312** using a OnePlus A3 (Android 6.0.1)

Ping **830b621d-6397-417f-95da-5d29956ce84d**
```
 {
          "category": "synced_tabs",
          "name": "synced_tabs_suggestion_clicked",
          "timestamp": 6089
        }
```
[Logcat](https://github.com/mozilla-mobile/fenix/files/6129781/snct.txt)
