### ISSUE TITLE
FNX-5261 ⁃ [Bug] Quick Action Bar not available in Custom Tabs

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1816]
## Steps to reproduce
1. Set Fenix as the default browser.
1. From any app open a custom tab.
1. Try to open the Quick Action Bar.

### Expected behavior
The Quick Action Bar is available.

### Actual behavior
There is no way to open the Quick Action Bar.

### Device information
* Android device: Google Pixel (Android 9) & HTC 10 (Android 8)
* Fenix version: 1.0.1916 (#11091214)

As mentioned in [#182](https://github.com/mozilla-mobile/fenix/issues/182#issuecomment-478403491) this should be available in Custom Tabs.

Was there a change and Custom Tabs should not have the Quick Action Bar available anymore?

**Comment by vesta0** [comment]
Will be addressed in #1499
