### ISSUE TITLE
Total cookie protection 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#18175]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Recently Mozilla has added total cookie protection in v86 however it seems this is not yet added or implemented in Firefox Android. Please add the same

### How do you know that this problem exists today? Why is this important?
Total cookie protection missing 

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9819)

**Comment by Amejia481** [comment]
There are some dependencies that we need from GV to be completed https://bugzilla.mozilla.org/show_bug.cgi?id=1543720

**Comment by sheikh-azharuddin** [comment]
> There are some dependencies that we need from GV to be completed https://bugzilla.mozilla.org/show_bug.cgi?id=1543720

But that Bugzilla issue is 2 years old... Wondering if fenix even existed during that time 🤨

**Comment by Amejia481** [comment]
[Geckoview](https://mozilla.github.io/geckoview/) existed before Fenix was created, I think the issue has been re-prioritized by the Geckoview team :) .

**Comment by sheikh-azharuddin** [comment]
Since storage api access is enabled in fenix as per below Bugzilla..  Could you please confirm total cookie protection is implemented or not? 
https://bugzilla.mozilla.org/show_bug.cgi?id=1543721

**Comment by Amejia481** [comment]
The was marked as duplicated of https://bugzilla.mozilla.org/show_bug.cgi?id=1543720

**Comment by amedyne** [comment]
GV is no longer a dependency for this. For reference this is what was implemented on Focus: https://github.com/mozilla-mobile/focus-android/issues/5938

**Comment by sheikh-azharuddin** [comment]
> GV is no longer a dependency for this. For reference this is what was implemented on Focus: [mozilla-mobile/focus-android#5938](https://github.com/mozilla-mobile/focus-android/issues/5938)

What about main fenix browser?

**Comment by sheikh-azharuddin** [comment]
This feature is added recently to the firefox focus browser....we also need it 😭
https://www.engadget.com/firefox-focus-android-total-cookie-protection-privacy-140011016.html

**Comment by sheikh-azharuddin** [comment]
Any update?

**Comment by sheikh-azharuddin** [comment]
Is this feature enabled in nightly? I saw many commits🤔

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Fenix debug build 1.0.2236 (2022-08-30) by going to https://senglehardt.com/test/dfpi/storage_access_api.html and tapping on the request storage access buttons from the 3rd and 4th  iframes.
![1661860195039](https://user-images.githubusercontent.com/50983519/187429942-d06b03ff-8d38-44cc-84f8-32add90c16c4.JPEG)

### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 13)

**Comment by sheikh-azharuddin** [comment]
Wait why closed?
I don't see this popup neither I see any option to enable TCP...please clarify

**Comment by Mugurell** [comment]
> Wait why closed? I don't see this popup neither I see any option to enable TCP...please clarify

The new functionality was tested on a debug build.
Official release to follow.

**Comment by sheikh-azharuddin** [comment]
> > Wait why closed? I don't see this popup neither I see any option to enable TCP...please clarify
> 
> The new functionality was tested on a debug build. Official release to follow.

Thanks mugurell
Anylink to download the debug build just for testing 🙂
