### ISSUE TITLE
[Bug] white page with captcha etp custom cookies all cookies on 86.1.1

### ISSUE THREAD

**Issue by test491** [mozilla-mobile/fenix#18170]
#### str
visit https://mars.nasa.gov/participate/send-your-name/mars2020/certificate/599173796266

#### expected behaviour
content on webpage

#### actual behaviour
white page with captcha (bottom right)(see screenshot)

#### etp settings
custom - cryptominers, fingerprinters, redirect trackers, tracking content - all tabs, cookies - all cookies

#### reproducible
version 86.1.1

#### not reproducible with above etp settings
* version: 87.0.0-beta.1 (Build #2015795065) AC: 73.0.0, 69a800e47 GV: 87.0-20210222154334 AS: 71.0.0
* version: Nightly 210224 (Build #2015795113) AC: 73.0.20210223143117, 05f3e3cc7 GV: 87.0a1-20210222084406 AS: 71.0.0

> android 9, Galaxy J7 Nxt

> screenshot

![Screenshot_20210225-174728_Firefox](https://user-images.githubusercontent.com/78364929/109153906-726bc600-7765-11eb-92f2-a2fdbc017603.jpg)

**Comment by Amejia481** [comment]
This is a problem for the website developer to address, It looks like the website was built around accessing cookies to work, making the setting too aggressive for the website. The same behavior is reproducible on Firefox desktop, below the JS console error: 



<img width="1778" alt="image" src="https://user-images.githubusercontent.com/773158/109170642-f8c8dd80-774e-11eb-9fc6-f378d06c1a7a.png">
