### ISSUE TITLE
Rework History Telemetry

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#18178]
Currently anytime a user uses the History to open a tab we record the same telemetry.  The problem with this is that we can't distinguish between the user tapping on history, tapping 3 dot menu to open in new tab, tapping 3 dot menu to open in private tab, select multiple to open in new tab or select multiple to open in private tab.

Rework history telemetry so we can distinguish between all 5 cases.

**Comment by rocketsroger** [comment]
For https://github.com/mozilla-mobile/fenix/issues/14866

**Comment by lobontiumira** [comment]
Verified on the 3/15 Nightly build with Google Pixel (Android 10):
* ping a2e62209-bef0-4223-83fa-cd528577f448
* opened_item_in_new_tab:
```
{
          "category": "history",
          "name": "opened_item_in_new_tab",
          "timestamp": 25915
        }
```

* opened_items_in_new_tabs:
```
 {
          "category": "history",
          "name": "opened_items_in_new_tabs",
          "timestamp": 10537
        }
```

* opened_item_in_private_tab:
```
{
          "category": "history",
          "name": "opened_item_in_private_tab",
          "timestamp": 33429
        }
```

* opened_items_in_private_tabs:
```
{
          "category": "history",
          "name": "opened_items_in_private_tabs",
          "timestamp": 17996
        }
```
