### ISSUE TITLE
Add Telemetry When User Opens a Bookmark

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#18173]
Currently we're not tracking when user is opening a bookmark by tapping directly on the bookmark.  Add telemetry to track it.
This is for https://github.com/mozilla-mobile/fenix/issues/14866

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly 210312** using a Google Pixel 3a (Android 11)
Ping **ffbaa16d-5fbd-4aa7-83a5-1b2bb8bc6ebd**
```
"events": [
        {
          "category": "events",
          "extra": {
            "first_frame_pre_draw_nanos": "50786516",
            "source": "UNKNOWN",
            "type": "HOT"
          },
          "name": "app_opened_all_startup",
          "timestamp": 0
        },
        {
          "category": "bookmarks_management",
          "name": "open",
          "timestamp": 8513
        }
      ]
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/6129681/bokm.txt)
