### ISSUE TITLE
[Crash] Native crash on startup with 2/25 nightly

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18177]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

It mostly happens on startup but sometimes happens when i open search bar. Started with 2/25 nightly. Browser became completely unusable.

00cf1b69-92be-4cae-b4e4-2c21c8b6dc1c
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-f6457b54-ce49-4c95-872c-d2bda0210225
----
<native crash>

### Device information

* Device vendor / model and Android version: XZ1 Android 11
* Firefox for Android version: 2/25 nightly

**Comment by hakkikaancaliskan** [comment]
I've signed out from account and looks like it's fixed for now.

**Comment by hakkikaancaliskan** [comment]
Re-signed in and it's working

**Comment by hakkikaancaliskan** [comment]
Ohh found the main problem, this only happens when i switch to mobile data, no problem on wifi

**Comment by rvandermeulen** [comment]
This is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1694179. Appears to be fallout from the recent change targeting Android 11.

**Comment by Amejia481** [comment]
@rvandermeulen could stop the rollout of this version until we have a path for it?

**Comment by rvandermeulen** [comment]
No, we can't halt rollout when it's already at full rollout. We can and
should respin the Nightly build as soon as the fix is ready, however.

**Comment by Amejia481** [comment]
👍🏽

**Comment by hakkikaancaliskan** [comment]
@rvandermeulen i think this issue fixed in bz. I'm going to close the issue.
