### ISSUE TITLE
Intermittent UI test failure - NavigationToolbarTest - goBackTest

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#18188]
• Master 2/26

► Flaky 1x goBackTest

`androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?`

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7755699007721319983/executions/bs.6059beeab37a8c34/testcases/2/test-cases)

**Comment by sv-ohorvath** [comment]
See similar failure on https://github.com/mozilla-mobile/fenix/issues/17195

**Comment by sv-ohorvath** [comment]
Will be fixed in #18325.

**Comment by sv-ohorvath** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/18331
