### ISSUE TITLE
FNX-5263 ⁃ Add to desktop option is missing

### ISSUE THREAD

**Issue by suoko** [mozilla-mobile/fenix#1818]
### Why/User Benefit/User Problem
Great to avoid installing many web apps

**Comment by ekager** [comment]
I *think* what you're wanting is a PWA on the phone homescreen? Take a look at these tickets to track that work, https://github.com/mozilla-mobile/fenix/issues?utf8=✓&q=is%3Aissue+is%3Aopen+PWA

**Comment by suoko** [comment]
https://github.com/mozilla-mobile/fenix/issues/773#issuecomment-485065306
