### ISSUE TITLE
[UX] Changing flat button of private tab to raised button

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18186]
### What is the user problem or growth opportunity you want to see solved?
Highlight the private tab button using shadows. It is currently a flat button but must be converted to a raised button.
Incase of zooming in, a greyish circle could be found for the button but due to the choice of the shade, it's not clearly visible.
![Highlight the private tab buttom](https://user-images.githubusercontent.com/48223671/109258851-10709680-7821-11eb-8e7f-880638d32dad.png)

### How do you know that this problem exists today? Why is this important?
The flat button is used in the following locations:
1. On toolbars
2. In dialogs, to unify the button action with the dialog content
3. Inline, with padding, so the user can easily find them 

While the private button should be a raised button as they emphasize functions on busy or wide spaces.

### Who will benefit from it?
1. People with low vision
2. People who use after an interval

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9824)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807541

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
