### ISSUE TITLE
[Bug] Some actions don't respect the Touch & hold delay set in Android Accessibility Settings

### ISSUE THREAD

**Issue by Susko3** [mozilla-mobile/fenix#18182]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Locate the Touch & hold delay setting in Android Settings -> Accessibility
2. Change the deleay from short to long.
3. Notice that the time required to initiate the following long press actions doesn't change:
  * Long press on link in a website
  * Long pressing on text (on a website) to select it

4. The following actions respect the Touch & hold delay:
  * Long press on URL bar to show the popup menu (Copy, Paste, Paste & Go)
  * Long press on tab switcher button
  * Selecting text in the about string in Setting -> About
  * Selecting tabs in the tab switcher

### Expected behavior

Every action that is a long press (Touch and hold) should respect the Touch & hold delay set in Accessibility Settings.

### Actual behavior

Some actions respect the Touch & hold delay, while others don't and have a hard-coded Touch and hold delay.

### Device information

* Device vendor / model and Android version: Realme 6, Android 10
* Firefox for Android version:
  * 86.1.1 (Build #2015794883)
AC: 72.0.16, f4aa67a9c
GV: 86.0-20210222142601
AS: 67.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9823)

**Comment by mcarare** [comment]
Can QA also test this? I have tested on several devices and the delay is the same for the tab counter button and the URL bar context menu after I switch to Long Touch & hold delay.

**Comment by Susko3** [comment]
I've misjudged the duration the first time. The Tab switcher button respects the Touch & hold setting. I'll update the original post.

**Comment by mcarare** [comment]
It seems that the only actions that need investigating are the context menu in the browser window. 
@eeejay is this a known issue in GV?

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Nightly 3/2, Beta 87.0.0-beta.2 from 3/1, Release 86.1.1 from 2/23 with Samsung Galaxy Tab S3 (Android 8) following the steps from the description.
I will remove the qa:needed label for now.

**Comment by Susko3** [comment]
As of build
```
90.1.1 (Build #2015820747)
AC: 90.0.12, 0ab0465c5c
GV: 90.0-20210705185941
AS: 77.0.2
```
this problem expands to the tab switcher icon in the toolbar. In the previous version (presumably 89), it would open quickly (as I have touch and hold delay set to lower than normal), but in 90 it opens after a noticeably longer delay.

**Comment by Susko3** [comment]
Should I create a new issue as per the above, or is there enough information in the current issue?

The latest info:

Only seems to affect the context menu in the browser window. It will completely ignore the value set in settings and (presumably) use the 400? ms that is the default touch and hold delay on Android.

```
96.1.1 (Build #2015855931), 8711f4f20+
AC: 96.0.11, 64c90c98b3
GV: 96.0-20220106144528
AS: 86.2.1
```

**Comment by FusionDragon** [comment]
My touch hold delay on android is set to 200ms, I like my phone to be snappy but honestly the ONLY thing preventing me from switching from brave to Firefox Mobile is this issue. It completely throws me off when I touch and hold but let go too early because it doesn't respect the systems touch hold delay. I would really like the app to be consistent with my devices settings or at least add a setting to change the applications touch hold delay separately.

**Comment by FusionDragon** [comment]
This is still an issue
