### ISSUE TITLE
Add timestamps to downloads

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#18197]
### What is the user problem or growth opportunity you want to see solved?
A user might want to know the date and time of a particular download. Users are currently unable to get that information from the download list/built-in download manager in Firefox.

### How do you know that this problem exists today? Why is this important?
Currently, in the built-in download manager, only the file name and file size are shown. Users may also want to know the date and time of a download, for various reasons.

### Who will benefit from it?
User who do not use an external download manager.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9832)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812795

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
