### ISSUE TITLE
[Bug] Shared permissions between Release and Beta builds

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18192]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Install Firefox release build. 
2. Give access to camera, location or other permissions.
3. Install Firefox Beta.
4. Go to Settings and check the permissions.

### Expected behavior
The permissions are not shared. 

### Actual behavior
Beta build have access to the permissions shared for Release build.

### Device information
* Device vendor / model and Android version: Samsung Note 10 (Android 10).
* Firefox for Android version: Beta & Release

**Comment by Amejia481** [comment]
I'm bit confused, could you help me to clarify? Release and Beta are two different apps why they should share Android permissions?

**Comment by Mugurell** [comment]
> I'm bit confused, could you help me to clarify? Release and Beta are two different apps why they should share Android permissions?

I think because they have the same "shareUserId" and permissions are given for UIDs.
Fennec had the same ~"bug".
Fenix had to support the sharedUID for properly migrating beta/release.

Seems to be a known issue - https://sites.google.com/site/droidnotsecure/vulnerabilies/permission-residue/shareuserid-permission

**Comment by kbrosnan** [comment]
This is related to the shared signing key between `org.mozilla.firefox` and `org.mozilla.firefox_beta`. There are places in Android where it cannot distinguish between the two apps because of the shared signing key.

**Comment by Mugurell** [comment]
Then I think we can close this as WONT_FIX. Because we really can't.
Please also refer to https://github.com/mozilla-mobile/fenix/issues/18066#issuecomment-787930431.
The only "solution" is to have new apps without this `sharedUserId` that users would have to fresh install.
