### ISSUE TITLE
[UX] Improvements when address bar is at top one-handed 

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18196]
**What is the user problem or growth opportunity you want to see solved?**
One-handed UX when the address bar is on the top.

How do you know that this problem exists today? Why is this important?
I use it and encounter it every day. It's important for [one-handed users](https://www.uxmatters.com/mt/archives/2013/02/how-do-users-really-hold-mobile-devices.php#:~:text=The%20users%20who%20we%20observed,two%20handed%E2%80%9415%25).

![one handed users ux](https://user-images.githubusercontent.com/48223671/109323804-de3f5300-7879-11eb-86ea-ec5df284b0af.png)
![mobile regions](https://user-images.githubusercontent.com/48223671/109324036-29596600-787a-11eb-841c-7f1be30a91b2.png)

The users who we observed touching their phone’s screens or buttons held their phones in three basic ways:
one-handed—49%
cradled—36%

**Who will benefit from it?**
All those who put the address bar at the bottom.

**How to test?**
1. Using A/B testing (a kind of Quantitative usability testing that focuses on collecting metrics)
2. After A/B run a Usability Testing

**Comment by topotropic** [comment]
Thanks for the feedback! You can go to Settings > Customize and change the toolbar from top to bottom.
