### ISSUE TITLE
Need an option to NOT sync saved logins LOCALLY cause I've synced them on lockwise

### ISSUE THREAD

**Issue by ameaninglessname** [mozilla-mobile/fenix#18209]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
All of my logins could be found on two apps of my phone rather than one. (fenix and lockwise).

### How do you know that this problem exists today? Why is this important?
Though, I trust and love both of them, It's better for the user to care about only one place and this also avoid duplicate storage of login information which will increase the data security.

### Who will benefit from it?
All users that use both of fenix and lockwise.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9842)

**Comment by MisterAnderson91** [comment]
The only way I have found currently to deal with this is to not use any sync features in fenix.

When signing in to fenix and enabling sync, there is no way to disable password sync upfront, it must be disabled after-the-fact.

If it is disabled after passwords are synchronized, then the passwords remain with no way to delete them in bulk.

It also appears to have re-enabled password sync by itself now, after it was turned off.

I'd say this is a poor UX at the moment as the average user using lockwise is likely to separately also want to use other sync features. Fenix simply needs an option to sync without passwords on first setup.

**Comment by kbrosnan** [comment]
Lockwise is closed. Passwords can be disabled in the sync settings under the `Logins`.
