### ISSUE TITLE
Scroll to the top button

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#18207]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently to go to the top of the page one has to scroll to the top manually. Please add a floating button to scroll to the top similar to yandex browser and other browser

### How do you know that this problem exists today? Why is this important?
Scrolling to the top of the page is painful

### Who will benefit from it?
All users

**Comment by LittleAngelwings** [comment]
If you use Firefox Nightly you can install an extension for that. I'm using "Top and Buttom scroll buttons" and it works fine.

**Comment by cadeyrn** [comment]
> Who will benefit from it?
> All users

That's not true ("all users" will never be true for any proposal). A floating button for something like this would be really annoying for me.

**Comment by Mikaka27** [comment]
Many website already have their own "back to top" floating buttons.

Maybe a better way forward would be to add this extension to recommended extensions program and allow users to install it?
