### ISSUE TITLE
[Bug] Fullscreen is scrolling up and down or even left and right when enter website video UI

### ISSUE THREAD

**Issue by MEGADRAGSTER-288** [mozilla-mobile/fenix#18204]
Hi, i have a fullscreen issue since version 82.X.X
When I watch a movie on a website, instead of enter a fixed position in fullscreen, like it was in 81.1.15, which was the best browser so far, i can scroll it up and down, or even left and right, like if it was a normal web page but a bit zoomed in. I have searched about my issue, but there is no any that describe my situation. 

##Steps to reproduce
1) Go to xrysoi.pro
2) Click on any movie (or a serial if you like)
3) Scroll down, and click the red button where is written HDVID (if exist)
4) go to the new page, or the one its load currently (it is an web page starting with hdvid.fun/xyzklm)
5) once the timer go 0, click the button. It should bring you to the movie/video UI
6) Press twice the UI, and you enter the fullscreen (you can press the fullscreen button too)
7) Now slide the already in-fullscreen video. You will notice the exact issue I've described. The video just scrolling up and down or even left and right.

###Expected Behavior
It should remain stable fullscreen like it was in 81.1.15 version of Mozilla Firefox.

###Actual Behavior
User can slide up and down, right and left, but it doesn't hold the fullscreen UI at a fixed position, like it was at a version 81.1.15! The versions after it, all came with various fullscreen problems which some of them described in other threads.

###Device info 
Device: Xiaomi 
Model: Mi A2 lite
Android Version: 10 
Version of Android Mozilla Firefox: Latest (86.1.1)

**Comment by Dunexus** [comment]
Hello,

This issue is tracked by https://github.com/mozilla-mobile/fenix/issues/8252. Could you post you steps to reproduce there so it can be investigated too ?

**Comment by MEGADRAGSTER-288** [comment]
1) Open Android Mozilla Firefox 86.1.1
2) Type xrysoi.pro
3) Click on any movie you want
4) Click on the new tab and scroll down
5) Click on the red button where written HDVID
6) Click the new tab
7) Click the button once the timer ends
8) You should now see the video player.  Double click on it to enter
fullscreen
9) Now slide your finger on the screen and see what happens. You should see
the issue now.

If you don't, then my device is Xiaomi Mi A2 lite, running on Android 10.

**Comment by MEGADRAGSTER-288** [comment]
You know what.. Just press the link on Android Mozilla firefox 

https://hdvid.tv/pvub6in44l54.html

**Comment by lobontiumira** [comment]
Thank you for the report!
I was able to reproduce this issue with https://hdvid.tv/pvub6in44l54.html on the Xiaomi Mi 8 Lite (Android 9) device on RC 87.0.0-rc.1.
Not reproducible on the 3/31 Nightly build.

**Comment by MEGADRAGSTER-288** [comment]
Thank you so much... The issue has finally been fixed at v88... Thank you so much developers...
