### ISSUE TITLE
[UX] Bookmark review and reminder

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18213]
### What is the user problem or growth opportunity you want to see solved?
If the [bookmarks](https://support.mozilla.org/en-US/kb/bookmarks-firefox) are not used say 30+ days then if there could be a reminder to recheck them, it would declutter a lot of unnecessary data.

### How do you know that this problem exists today? Why is this important?
I saw going through my bookmarks, I found few items which were related to my schooling and it has been 3 years, so I was trying to find one particular bookmark but all this confused me.

### Who will benefit from it?
1. Anyone who is an OCD
2. people in a hurry

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9845)

**Comment by onemahon** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811814

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
