### ISSUE TITLE
Tabs from collection are placed at the wrong end of the tab list

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#18210]
ever since I updated to Firefox 86 (yesterday or so, due to staged release in Germany) tabs of my collection are opened at the top of the tab list.
if I open a new page through another app, by using the address bar or by opening a top site, then the new tab gets placed at the bottom of the list.
Why are my tabs separated now? this is very annoying since I have to open tabs now to switch between top and bottom since there is no go to top/bottom button in the tab list. scrolling is not feasible for hundreds of tabs.

this behavior is still happening in Nightly.

## Steps to reproduce
Open new tab
Open page from collection
### Expected behavior
Tab is placed at the bottom of the list like it is for all other cases.
### Actual behavior
Tab is placed at the top of the list (hundreds of tabs above other new tabs of mine) 
### Device information
* Device vendor / model and Android version: oneplus 3T Havoc OS Android 10 
* Firefox for Android version: 86.1.1 (and Nightly)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9844)

**Comment by Djfe** [comment]
is this related to the fix in #17889?

**Comment by sflorean** [comment]
I was able to reproduce this on Nightly 3/14 with Xiaomi Redmi Note 8T (Android 9). I've got different behaviors:
- open tab from collection: top position
- open tab from "switch to tab" : below the tab from where the page was opened
- open new tab: bottom position

**Comment by decadent** [comment]
Possibly related to #10986 where a tab restored right after closing is likewise put at the start of the list.

**Comment by Djfe** [comment]
it's still happening

**Comment by Djfe** [comment]
still happening

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812737

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
