### ISSUE TITLE
[Bug] incorrect delivery service tracking info result

### ISSUE THREAD

**Issue by test491** [mozilla-mobile/fenix#18218]
i was trying to reproduce #17183

#### STR
* use private browsing mode
* Go to https://www.dpd.com/at/de/ (website of german delivery service)
* enter a tracking number, eg 06225024216407
* click the magnifier symbol

#### expected behaviour

display delivery schedule

![correct-Beta](https://user-images.githubusercontent.com/78364929/109426841-a240f500-7a15-11eb-80ae-e28a1b15f3b0.jpg)

#### actual behaviour

it displays "Wo ist mein Paket?"

![incorrect-stable-nightly](https://user-images.githubusercontent.com/78364929/109426864-b97fe280-7a15-11eb-81ff-b24bd559b05b.jpg)

#### etp settings
custom - cryptominers, fingerprinters, redirect trackers, tracking content - all tabs, cookies - all cookies

#### not reproducible with above etp settings in private browsing mode
* version: `87.0.0-beta.1 (Build #2015795065)`

#### reproducible with above etp settings in private browsing mode
* version: `86.1.1`
* version: `Nightly 210228 (Build #2015795881)`

#### android 9, Galaxy J7 Nxt

**Comment by sflorean** [comment]
@test491 I wasn't able to reproduce this on Samsung Note 10 (Android 11) - on 86.1.1 or on the latest Nightly build with ETP custom settings enabled/&private browsing, as in description. Do you have some additional steps?

**Comment by mariansima** [comment]
Reproduced the issue in the on Samsung A8 (Android 9) with Firefox Nightly 93.0a1 2021-09-07. The first search in private browsing opened and stopped on an about:blank page. On subsequent tries, the issue could not be reproduced.
