### ISSUE TITLE
FNX3-15840 ⁃ [Bug] adress bar no longer works for every URL (redirect to the search engine instead)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1821]
### Steps to reproduce
1. enter a URL or about:page in the address bar and press the enter key of your keybard

### Expected behavior
Fenix opens the website.

### Actual behavior
It works for some domains, Fenix opens the website. For other domains Fenix redirects the request to the default search engine.

mozilla.org => Fenix opens the website.
bing.com => Fenix opens the website
soeren-hentzschel.at => Fenix opens Google
about:config => Fenix opens Google
about:telemetry => Fenix opens Google

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision af613962e550c1b9ab9931b12ee1c30f88c88ff6 (with PR 1795 manually removed)

**Comment by LittleAngelwings** [comment]
I've watched this issue also in Fenix Nightly 1.0.1916 (11081206) 04/18

**Comment by sblatz** [comment]
This is a [known issue in a-c](https://github.com/mozilla-mobile/android-components/issues/2794)

**Comment by kbrosnan** [comment]
This is fixed for all the cases listed in comment 0
