### ISSUE TITLE
[Bug] Visiting https://browserbench.org/ shows a "Secure Connection Failed" error

### ISSUE THREAD

**Issue by SL-Lee** [mozilla-mobile/fenix#18214]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Attempt to visit https://browserbench.org/.

### Expected behavior

The site loads in the browser tab.

### Actual behavior

Fenix shows a "Secure Connection Failed" error. However, if I go to **Advanced** > **Accept the Risk and Continue**, I am able to visit the site -- clicking on the padlock icon in the address bar does not show any errors/warnings about the site's certificate.

This does not seem like an issue with the site itself, since I was able to visit the site with Google Chrome (with no issues).

"Secure Connection Failed" error:
![](https://user-images.githubusercontent.com/45960387/109412890-950c1200-79e5-11eb-8d48-9bde7df6c20f.jpg)

After going to **Advanced** > **Accept the Risk and Continue** and clicking on the padlock icon in the address bar (which shows there is a Secure Connection, despite what the previous warning showed):
![](https://user-images.githubusercontent.com/45960387/109413021-4b6ff700-79e6-11eb-8948-466689a53995.jpg)

### Device information

* Device vendor / model and Android version: Oppo Reno 2 (Android 10)
* Firefox for Android version: Firefox Nightly 210227 17:01 (Build #2015795787), Firefox Beta 86.0.0-beta.5 (Build #2015793427)

**Comment by test491** [comment]
#### etp settings
custom - cryptominers, fingerprinters, redirect trackers, tracking content - all tabs, cookies - all cookies

#### reproducible with above etp settings in private browsing mode

* version: `86.1.1`
* version: `87.0.0-beta.1 (Build #2015795065)`
* version: `Nightly 210228 (Build #2015795881)`

#### not reproducible

`chrome 88.0.4324.93` with following settings

* privacy and security -> safe browsing -> enhanced protection
* site settings -> cookies -> block all cookies

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1695723

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
From Dana in the bug linked above.

> This is expected. The root that issued that certificate is no longer trusted. See bz-1670769. It looks like the operators of that site could replace the intermediate they're using with one that doesn't chain to a distrusted root (e.g. "Baltimore CyberTrust Root").
