### ISSUE TITLE
[Bug] reader mode doesn't allow expand or shrink  text

### ISSUE THREAD

**Issue by Theresnotenough** [mozilla-mobile/fenix#18224]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by LaurentiuApahideanSV** [comment]
@Theresnotenough Could you provide with more information regarding the issue? Are you trying to zoom the text in and out by pinching the screen or using the Reader view controls?

**Comment by Theresnotenough** [comment]
oh, thanks for your concern.
I'm trying by pinching, never heard about the controls in reading mode. I
can't find them anyway. I've switched on and of the forced zoom in any page
settings option but i don't see the controls you mention.


I'm using Miui Global 12.0.7 and android 10

thanks

**Comment by LaurentiuApahideanSV** [comment]
@Theresnotenough In order to activate Reader view controls once you are in reader mode tap the 3 dot menu and select Appearance. I've uploaded a video illustrating this. Let me know if this works for you.
![Reader_view_controls](https://user-images.githubusercontent.com/50983519/109949419-039de800-7ce4-11eb-9cd9-90996829739f.gif)

**Comment by Theresnotenough** [comment]
oh thanks a lot, that worked

**Comment by LaurentiuApahideanSV** [comment]
Since the issue has been resolved I will close it.
