### ISSUE TITLE
External download managers not working with Fenix nightly 88

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/fenix#18236]
Device: Samsung S10+ SM-G975U1
OS Version: Android 11, Feb 2021 Google Play and Security patches
Description: Downloading via external download manager, in my case ADM (beta version, updated) leads to Fenix offering a download button for Fenix's download manager. No longer am I presented with the choice to choose between Firefox and external DMs. This started a few days ago, not sure exactly when. Is likely related to recent Android 11 changes, as reported by another user on Element. You can still download via external dm via long press and share. Bug should be recent as I believe it's appeared in the last week.

**Comment by hakkikaancaliskan** [comment]
related to https://github.com/mozilla-mobile/fenix/issues/18223

**Comment by Amejia481** [comment]
@mcl21014 and @hakkikaancaliskan could you verify in nightly? This should be already fixed by https://github.com/mozilla-mobile/fenix/pull/18229

**Comment by hakkikaancaliskan** [comment]
@Amejia481 context menu, external download manager and share dialog, all of them fixed. Thank you!

**Comment by Amejia481** [comment]
Thanks to @mcarare that did all the hard work #18229 💪🏽

**Comment by mcl21014** [comment]
Definitely fixed @Amejia481 Good work everyone!

**Comment by sflorean** [comment]
Verified as fixed on Nightly 3/5 with the following devices:
- Pixel 3 (Android 11)
- Samsung Note 10 (Android 11)
- LG G7 Fit (Android 8.1)

**Comment by Amejia481** [comment]
Thanks @sflorean!
