### ISSUE TITLE
[Bug][l10n] Some string from "Account page" are not translated in Hindi

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18231]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Change language to Hindi.
2. Open Fenix and go to Settings - Account.
3. Check the string from the page.

### Expected behavior
The string is translated to hindi. 

### Actual behavior
The string" No account? Create one to sync Firefox between devices."  is in English.

### Device information
* Device vendor / model and Android version: Samsung Note 10 (Android 10)
* Firefox for Android version: Nightly 3/1, 87.0.0-beta.2
 
<img src="https://user-images.githubusercontent.com/58466444/109501154-e24cba00-7a9f-11eb-9857-f61a35d4cbce.jpg" width="300" height="550" />

**Comment by Delphine** [comment]
I see that Hindi still hasn't translated the string here: https://pontoon.mozilla.org/hi-IN/android-l10n/all-resources/?tag=fenix&search=No+account%3F+Create+one+to+sync+Firefox+between+devices.&string=215270

So I will close this for now. Thank you!
