### ISSUE TITLE
[UX] Changing the color of the private tab icon for clear visibility

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18237]
**What is the user problem or growth opportunity you want to see solved?**
Change the [color ](https://www.designandpromote.com/color-theory-the-importance-of-color-in-web-design/?__cf_chl_jschl_tk__=529963b8060771dcfa9fc5267f1843ad56415c57-1614619352-0-AYXpE2XVwx_Di8C45QDbYXPwT9_kA9z7QDJgu6ib8AITLhs5YyYuo9g1JnMXNNfw52ZNDl2WcoqQSbJa17EuN8H_fwRZFSg88ZEsQOzORbfntKP3otQC7DW02t_fhz9DM6zMsXjXiYGtReeRz-J2wWsL2eV9krGhMHclGMVcSGYWeqg_c-iXK8JjzKE0isOWzjb42KC5O_mMOTxbxt3Y3wPBLE2L5BSFnpLICSTO4kbnzR-khepOqQkiu19pz_LvwjlNOOM8VTj-8WTkzatii8GXSM7WaO41c7cIyDH49NykDmCJnreoAg5mTrr8FZBxL7dOtaOcz-yKlG1chZeEwcDEQbyI8pBVBViAGvBA6D8D2xTMXec9W_B_JUlQ0LYC-3ycEBO1LrqkftnnUMLDY51h-PxSvHy4LinYg7RA6xiZRyyyN_TUQKu53OYIuqboqg) of private tab icon when running the private tab. It is currently white in color but must be converted to the original logo button to highlight the button's presence.

![button in private tab](https://user-images.githubusercontent.com/48223671/109533349-22339180-7ae0-11eb-8b13-8892794dfb77.png)

### What is the user problem or growth opportunity you want to see solved?
The icon is not visible due to the same background and icon color:
1. On toolbars
2. Color plays an important role in text legibility.
3. How to [prioritize the color](https://material.io/design/color/text-legibility.html#text-backgrounds)
 High-emphasis text has an opacity of 87%
Medium-emphasis text and hint text have opacities of 60%
The disabled text has an opacity of 38%

### How do you know that this problem exists today? Why is this important?
On switching to the private tab, the button gets hidden due to the same color
Colored backgrounds or typography additionally change the rules regarding text opacity and different states of text.

### Who will benefit from it?
1. First-time users who are still unknown with the site road map

**Comment by topotropic** [comment]
Thanks for the feedback. To confirm: you just see a circle up there and the icon isn't visible? 
The intend is that it should look similar to this 
<img width="88" alt="image" src="https://user-images.githubusercontent.com/353960/111698074-b159dc80-8836-11eb-816d-157de8358be2.png">. Is this what you see? Thanks!

**Comment by RiyaJ2311** [comment]
No, All I am getting is a white circle only
![image](https://user-images.githubusercontent.com/48223671/111880345-fa459880-89d0-11eb-879e-68da9c67ad20.png)
