### ISSUE TITLE
Image Fails to Load when src set via fileReader.readAsDataURL with large image

### ISSUE THREAD

**Issue by Trapfether** [mozilla-mobile/fenix#18249]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Simple HTML file with an input type="file" and id="my-input"

javascript code

    var input = document.querySelector('#my-input');

    input.addEventListener('change',function(e){
      var file = input.files[0];
      var img = document.createElement('img');
      var reader = new FileReader();
      reader.onload = function(e) {

        img.onload = function(){
          alert(img.width);
        };

        img.src = e.target.result;
      });
      reader.readAsDataURL(file);
    });

try to load a large image width > 3000px.

### Expected behavior

Should alert the width of the image

### Actual behavior

alert's 0, and the image's internal data is missing / corrupted as attempting to draw it to a canvas results in a completely white canvas. I have determined that it is only a problem with larger images as the expected behavior prevailed with images < 2000px wide.

### Device information

Google Pixel 1
Android version 10
firefox 86.1.1 build #2015794883

**Comment by Amoodaa** [comment]
Any update on this?

**Comment by Trapfether** [comment]
This doesn't appear to have been fixed or mitigated in any way.

As of right now, I am checking for a width of zero as an error signal in my own project and asking the user to downsize the image.
That is an imperfect solution as many of our older users require someone to walk them through how to downsize an image on their phone.

**Comment by Amoodaa** [comment]
@Trapfether Thanks for the reply! Will utilize the error signal in a way similar to this!
