### ISSUE TITLE
[Add card] Add a screen for adding credit cards

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18243]
When clicking on "Add credit card" button from "Credit card" preferences, it should navigate to the "Add card" screen. This issue is to implement and land a basic layout and fragment for the "Add card" screen which can be used as a generic credit card editor.

<img width="407" alt="Screen Shot 2021-03-02 at 4 24 40 PM" src="https://user-images.githubusercontent.com/1190888/109717276-d500ff80-7b73-11eb-92a8-2634ec9feeac.png">

**Comment by Mugurell** [comment]
@gabrielluong Was looking into helping with a review but I see there's no PR yet.
It the work done and ready to review?

**Comment by gabrielluong** [comment]
> @gabrielluong Was looking into helping with a review but I see there's no PR yet.
> It the work done and ready to review?

Not yet ready for review. I am expecting it to be up for review early next week. I will flag you when it's up. Thanks!
