### ISSUE TITLE
Double tap tab button to go to the most recently used tab

### ISSUE THREAD

**Issue by currybullen** [mozilla-mobile/fenix#18255]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Quickly jumping between the two most recently used tabs. This could be achieved by creating a new behavior for the tabs button, where rapidly tapping it twice brings the user to the tab that was most recently open. I think it would feel very natural for Android users that are used to tapping the overview button (in the Android navigation bar) twice in order to navigate to the most recently used app.

### How do you know that this problem exists today? Why is this important?
It is not (to my knowledge) possible in any way to switch between the two most recently used tabs in any way that's quicker than switching to any other tab.

### Who will benefit from it?
Everyone!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9877)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807066

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
