### ISSUE TITLE
[Bug] Can't open downloaded apk file

### ISSUE THREAD

**Issue by kvahid** [mozilla-mobile/fenix#18254]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Expected behavior
The browser is expected to open downloaded file either directly or from the publisher's website like screenshot below that we see this behavior in chrome. In this case the apk is Firefox nightly and the publisher is myket.ir, a well known android publisher in Iran.

https://user-images.githubusercontent.com/25345225/109657011-4348c080-7b7a-11eb-9e89-3960b185839f.mp4

### Actual behavior
The browser just say it can't open the downloaded file.
https://user-images.githubusercontent.com/25345225/109651882-50fb4780-7b74-11eb-960a-e166a9459e73.mp4

### Device information

Samsung Galaxy A10s (SM-A107F/DS) / Android 10
Firefox for Android version 86.1.1

**Comment by adolfofp** [comment]
You cant open downloaded pdfs as well

**Comment by kvahid** [comment]
@adolfofp Thanks for concentrating on my issues personally. I can see pdf files. However I wanted to print a document to pdf and I didn't succeed to complete the task by the Firefox android browser.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 210407.

### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3XL (Android 9)
