### ISSUE TITLE
[UX] Adding feature to choose the downloading location

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18250]
### What is the user problem or growth opportunity you want to see solved?
While downloading a file, it doesn't ask for the location on where to save and downloads it in the download space automatically.

### How do you know that this problem exists today? Why is this important?
If I want to sort the files and arrange my folders properly, I can't. It would take a lot of time as this saves in a particular folder, I would have to cut it and paste.

**Comment by cadeyrn** [comment]
Duplicate of #5764.

**Comment by RiyaJ2311** [comment]
Since it is the same issue, I am closing this.
