### ISSUE TITLE
[Bug] No ripple animation when clicking on webpage elements. 

### ISSUE THREAD

**Issue by kvahid** [mozilla-mobile/fenix#18251]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Following behavior has been seen in multiple contexts. Screen shots provided is for an instance only.
### Expected behavior
User expects a shadow feedback from the browser when she/he clicks on a link or a button or an icon that will result in an action. Like this screen shot from chrome browser
https://user-images.githubusercontent.com/25345225/109610304-d1ed1b80-7b41-11eb-8fa2-9985f8d37cc9.mp4

### Actual behavior
While in Firefox browser no feedback is being displayed to user to assure him/her the click is received from browser. See this screen shot from Firefox browser:
https://user-images.githubusercontent.com/25345225/109610750-66f01480-7b42-11eb-9738-6395ec6b0347.mp4

### Device information
Samsung Galaxy A10s (SM-A107F/DS) / Android 10
Firefox for Android version 86.1.1

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 SM-A530F Android 9 Nightly 93.0a1 2021-08-30
