### ISSUE TITLE
[Feature request] Bookmark opened in new tab should open in background

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#18253]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to bookmark menu, browse any deep folder level bookmark, click 3 dot menu and select open in New tab
It opens in current bookmark tab only increasing frustration of a user who might wants to open another bookmark as the menu and folder path is gone. User has to open bookmark again, browse to the folder and select a new one... Painful process 

### Expected behavior
On clicking open in New tab it should actually open in New tab in the background without overriding current bookmark view

### Actual behavior
When clicking open in tab it is simply overriding current view and opening in current tab only 

### Device information

* Device vendor / model and Android version: ? A10
* Firefox for Android version: ? (go to Settings -> About Firefox): latest nightly

**Comment by mcarare** [comment]
This is not a bug, but the way it was intended in the first place. The history items have the same behavior. 
So this is a request that UX should decide on.

As a note, you can open multiple bookmarks at the same time, by selecting them, there is no need to go back and forth.

Also, please do not mark issues as "critical ". Thank you!

**Comment by rocketsroger** [comment]
Prototype: 

https://user-images.githubusercontent.com/6579541/110518447-19dbe780-80da-11eb-9c7b-6a5447fced2c.mp4

**Comment by amedyne** [comment]
@topotropic @vesta0 Any thoughts on these?

**Comment by amedyne** [comment]
@rocketsroger per discussion with @channingcarter today. We keep the current behavior for now.

**Comment by rocketsroger** [comment]
Sure, I'll un-assign myself

**Comment by vesta0** [comment]
While browsing, opening a link in a new tab always results in opening a new tab in the background. So I think the expected the expected behaviour remains the same when choosing to open a bookmark or history item in a new tab in the background - in contrast to tapping on the bookmark or history item in order to open it in the foreground. 

I recommend that we move forward with this change (for both bookmarks and history) as it is consistent with how we have defined this behaviour throughout the app.

**Comment by sheikh-azharuddin** [comment]
Why closed? The Commit is related to telemetry.. So how related to this issue?

**Comment by rocketsroger** [comment]
my mistake, I accidentally commit a pull request against this issue.
