### ISSUE TITLE
[Credit cards] Add the biometric prompt when navigating to "Manage saved cards"

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18264]
Most of the below is already implemented in https://github.com/gabrielluong/fenix/commit/2bca18187ddbe576b0626784ca572bb76d1f6a2d. I would like for someone smarter than me to see if we can refactor both the Credit card and Saved Logins code into a view similar to SyncPreferenceView working off the commit above. I would imagine we will need to pass in specific strings, but some of these strings are already common between the 2. In particular, I would want someone with deeper understanding of Android to see if we can remove the deprecation and fix the issues around having the Delay. Ideally, we should also add test coverage similar to SyncPreferenceView.

------
We want to add a biometric prompt when pressing the "Manage saved cards" preference to navigate to the "Saved cards" screen. This issue is about adding the biometric prompt feature and then navigating to the "Saved cards".

See
https://github.com/mozilla-mobile/fenix/blob/ccbca2cf78950182278308baabeba5ee0028eb59/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt#L73
https://github.com/mozilla-mobile/fenix/blob/ccbca2cf78950182278308baabeba5ee0028eb59/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt#L53.

There is a bug when the biometric prompt is showing, you are able to quickly navigate so we should disable the preferences in the "Credit card" screen while the biometric prompt is showing.

**Comment by Mugurell** [comment]
@gabrielluong Seeing that you almost finished the work for this and then abandoned it I want to ask if it's still needed and what are the new challenges that need to be overcome.

**Comment by gabrielluong** [comment]
> @gabrielluong Seeing that you almost finished the work for this and then abandoned it I want to ask if it's still needed and what are the new challenges that need to be overcome.

Using gabrielluong@2bca181, I would like to investigate if we can refactor both the Credit card and Saved Logins code for the biometric feature into a view similar to SyncPreferenceView working off the commit. I would imagine we will need to pass in specific strings, but some of these strings are already common between the 2. This should remove a lot of duplication of logic and I think we just need to pass a header string for both since the action buttons should be common between the 2.

In addition, I would want someone with deeper understanding of Android to see if we can remove the deprecation that is used as the fallback and fix the issues around having the Delay. Ideally, we should also add test coverage similar to SyncPreferenceView.

**Comment by eliserichards** [comment]
Biometrics for CC should secure the Management fragment (list of credit cards) and the Editor fragment (editing a credit card). It should follow the same flow as our current saved logins authentication.

**Comment by abodea** [comment]
Verified as fixed on the latest **Debug** built from master (5/27) with OnePlus Nord (10).
Note that the biometric prompt was displayed when I navigated to `Manage saved cards` but it was displayed only once (even when I pressed later) so I guess this is intended? @eliserichards.
