### ISSUE TITLE
[Credit cards] Integrate the credit card autofill enabled setting when the "Save and autofill cards" preference is toggled

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18263]
This issue is about wiring up the "Save and autofill cards" preference toggle in the "Credit cards" screen

When "Save and autofill cards" preference is toggled in the "Credit cards" screen, we should update the engine setting for whether or not the credit card autofill enable setting is enabled. 

See https://github.com/mozilla-mobile/fenix/blob/ccbca2cf78950182278308baabeba5ee0028eb59/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt#L108

<img width="356" alt="Screen Shot 2021-03-02 at 4 56 25 PM" src="https://user-images.githubusercontent.com/1190888/109720563-417dfd80-7b78-11eb-9740-968fe4bd5845.png">

**Comment by gabrielluong** [comment]
This probably needs https://bugzilla.mozilla.org/show_bug.cgi?id=1711992

**Comment by gabrielluong** [comment]
We discussed this further in https://mozilla.slack.com/archives/C01BTNG3684/p1621456247008400. We don't necessarily need GV for this unless we insist on it and that they can help us do this easier. 

Currently, we're forging ahead with adding something in AC similar to https://searchfox.org/mozilla-mobile/source/android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#526.

**Comment by gabrielluong** [comment]
@eliserichards I am gonna open this up in case someone can pick it up quickly since you already have several P1 tickets needed for Thursday.

**Comment by abodea** [comment]
Re-opening as I think it was closed in a PR, until I will confirm it.

**Comment by abodea** [comment]
Hello, @gabrielluong before verifying the issue I have a question:
This issue is related more to the "Save and autofill cards" preference toggle in the "Credit cards" screen as when it is ON, the autofill option should be displayed and not displayed when it is OFF, right?

**Comment by Mugurell** [comment]
@abodea If this option is enabled and there are saved cards when tapping on a credit card field that can be autocompleted the prompt with cards from which the user to choose from will appear.

If this option is off, even with cards saved when tapping on a credit card field that can be autocompleted the prompt with cards from which the user to choose from will not appear.

**Comment by abodea** [comment]
@Mugurell thank you very much!
Verified as fixed on the latest **Nightly 5/28** with **Google Pixel 4 XL(11).**
Please note that the behavior is the one Petru presented above, when `Save and autofill cards` was Enabled, the prompt was displayed and I was able to autofill without issues, and the prompt was not displayed when `Saved and autofill cards` was OFF.
