### ISSUE TITLE
FNX-5268 ⁃ [Bug] Going back to home screen loses scroll position

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1826]
## Steps to reproduce
1. Load Fenix with a few tabs open (enough where you have to scroll to see all tabs in session)
1. Scroll partway down the home screen (or to the end!)
1. tap a tab to open it.
1. go back using Android navigation

### Expected behavior
The browser goes back to the last place the user was (scrolled partway down the page). This is helpful if a user is trying to whittle down a session through the stack, and wants to keep the tabs towards the top open, and wants to continue down the stack once they go back to the tab listing. 

There is no downside to defaulting to this behavior, since the search bar/address bar is always present on the home screen. 

### Actual behavior
The user is sent back to the top of the home screen, with the large Fenix logo. 

This is unhelpful because the user has to hunt for the place they were at in the stack if they want to either reopen the tab that they had been browsing, or move to the next one in the stack. 

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1916 #11091215

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 5/23, with:
- Sony Xperia Z2 tablet (Android 6.0.1),
- Huawei Honor 8 (Android 7),
- OnePlus 5T (Android 9).

**Comment by pwd-github** [comment]
How is this QA verified? This is still broken and has always been broken.

**Comment by softvision-miralobontiu** [comment]
@pwd-github can you still reproduce this issue? On which build and device?
Thank you!

**Comment by pwd-github** [comment]
@softvision-miralobontiu 1.0.1924 (Build #11611808 🦎 68.0-20190604110028)

LG G8, Android 8 and NVIDIA Shield, Android 7

**Comment by softvision-miralobontiu** [comment]
I see what you mean. I am able to reproduce this on the latest build 1.0.1924 (#11620622), with OnePlus 5T (Android 9), Samsung Galaxy A 6 (Android 5.1.1), and Samsun Galaxy Note 8 (Android 9).
I will reopen this issue.
