### ISSUE TITLE
[Credit cards] Toggle the "Manage saved cards" display when there are saved credit cards

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18267]
We want to display "Add credit card" preference when there are no credit cards, and "Manage saved cards" when there are saved credit cards in the "Credit cards" screen.

This depends on https://github.com/mozilla-mobile/fenix/issues/18240.

This issue is to toggle the display between the 2 preferences in the "Credit cards"

<img width="357" alt="Screen Shot 2021-03-02 at 3 30 28 PM" src="https://user-images.githubusercontent.com/1190888/109710903-42109700-7b6c-11eb-849c-1ac5885b1147.png">

<img width="359" alt="Screen Shot 2021-03-02 at 3 30 34 PM" src="https://user-images.githubusercontent.com/1190888/109710900-41780080-7b6c-11eb-954b-70e1496d0279.png">
 screen.

**Comment by gabrielluong** [comment]
Depends on https://github.com/mozilla-mobile/fenix/issues/18265

**Comment by chrishernan** [comment]
Hey @gabrielluong, could I work on this issue? Also, is this ok for me to ask to work on these types issues?  I know I'm not part of the mozilla team, I don't want to take work away from ya'll. I have quite a bit of free time and I want to help as much as I can with this project.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 3/23 with Pixel 3 (Android 11). When a card is added, "Manage saved cards" is displayed.
