### ISSUE TITLE
Add "Pin" Icon to Google search tile

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#18260]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The Google tile added to the New Tab screen by default behaves as a pinned tile; however, it does not have a "pin" UI badge to indicate to users that it is a pinned tab.

By adding the icon, users will have a better understanding of the behavior of the tile.

**Comment by lwa-moz** [comment]
Worth noting that both iOS and Desktop Firefox applications currently feature a "pin" icon for the same Google tile element. Making this change would improve consistency across products.

**Comment by mcarare** [comment]
@lwa-moz Should this be added only to Google, or to all default topsites?

**Comment by lwa-moz** [comment]
@topotropic should weigh in here on the UX team's perspective. Right now the Fenix treatment of default topsites is different from that on iOS and desktop products. We're under no external (i.e. partner) obligations to add the "pin" icon. This request was prompted mainly out of a desire for consistency. If we believe that adding the pin icon to default top sites has undesirable effects, that's a good hypothesis to test.

**Comment by topotropic** [comment]
Thanks for the ping and apologies for my late reply here. 

From a UX perspective it makes sense to add a pin to default top sites to show people that they behave similar to manually pinned sites.

**Comment by lobontiumira** [comment]
Verified that Google, Top Articles (Pocket), and Wikipedia tiles have the "pin" icon on the 3/30 Nightly build.
Tested with Google Pixel (Android 10), Xiaomi Mi 8 Lite (Android 9), and Samsung Galaxy Note 8 (Android 9).


<img src="https://user-images.githubusercontent.com/40694158/112965664-250eba00-9152-11eb-8054-59032a28be24.png" width="300" height="550" />
