### ISSUE TITLE
[Add card] Integrate the credit card provider validation to validate the card number

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18266]
When https://github.com/mozilla-mobile/android-components/issues/9813 lands, we should ensure we are validating the card number in the "Add card" screen.

This depends on https://github.com/mozilla-mobile/fenix/issues/18243 and https://github.com/mozilla-mobile/android-components/issues/9813.

<img width="353" alt="Screen Shot 2021-03-02 at 4 14 41 PM" src="https://user-images.githubusercontent.com/1190888/109716122-6a02f900-7b72-11eb-8926-b07d8b14e253.png">

**Comment by gabrielluong** [comment]
Since we added some basic credit card validation with the Luhn algorithm in https://github.com/mozilla-mobile/fenix/issues/19065, let's go ahead with adding the form input validation. We will eventually refactor some of the credit card validation to be able to determine the credit card type from https://github.com/mozilla-mobile/android-components/issues/9813. In the meantime, we can use `validateCreditCardNumber` that was added.

**Comment by mcarare** [comment]
@gabrielluong Is there a Figma link or on another platform for the designs? Thank you!

**Comment by sflorean** [comment]
Tested on Nightly 5/7 with Samsung Note 10 (Android 10) and here are the results:
- couldn't add an invalid card
- it doesn't matter if the card's information aren't correct (name, date), the card was added
- here is a screenshot of the added card 

<img src="https://user-images.githubusercontent.com/58466444/117453734-f43e5380-af4d-11eb-9abe-f54484c8672a.jpg" width="300" height="550" />

cc @gabrielluong @mcarare

**Comment by mcarare** [comment]
@sflorean This is not related to card validation, but to the way a saved card is displayed. I would open that in a separate issue to track the changes needed. Thank you for testing!

**Comment by sflorean** [comment]
Thank you @mcarare I will open a new issue.
