### ISSUE TITLE
[Credit cards] QA for the Credit cards preference

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18277]
We want to check the following:
- Ensure "Add credit card" navigates to "Add card" screen
- "Save and autofill cards" is prevents the "Select credit card" prompt from showing up which will allow users to autofill a credit card
- Ensure we only display "Add credit card" when there is no credit cards and
- Ensure we only display "Manage saved cards" when there are credit cards in the storage
- "Ensure "Manage saved cards" hits the biometric prompt and navigates to the "Saved cards" screen. Note, this is not yet landed https://github.com/mozilla-mobile/fenix/issues/18264.

If all of this is completed, we should add a QA needed for this ticket to ensure the "Credit cards" screen is properly tested for accessibility and functionality.

<img width="356" alt="Screen Shot 2021-03-02 at 4 56 25 PM" src="https://user-images.githubusercontent.com/1190888/109721316-35467000-7b79-11eb-952b-3d4fbb1f759c.png">

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/27 with OnePlus Nord (10).**

- `Ensure "Add credit card" navigates to "Add card" screen`
          -The `Add credit card` redirects correctly to `Add card` screen

- `"Save and autofill cards" is prevents the "Select credit card" prompt from showing up which will allow users to autofill a credit card`
           -For this one I'm not really sure what exactly it means, @gabrielluong can you please help me out?  Note that the prompt is called `Select credit card` and I was able to autofill without issues.

- `Ensure we only display "Add credit card" when there is no credit cards and,`
            - Only `Add credit card` is displayed when there are no credit cards added.

- `Ensure we only display "Manage saved cards" when there are credit cards in the storage`
            - Only `Manage saved cards` is displayed when there are credit cards saved.

- `Ensure "Manage saved cards" hits the biometric prompt and navigates to the "Saved cards" screen. Note, this is not yet landed` #18264.
            - As I verified #18264, the biometric prompt is displayed correctly and I was able to setup a biometric when I accessed the `Manage saved cards`.
