### ISSUE TITLE
[Saved cards] QA for the Saved cards screen

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18279]
~~In the event that unit tests were neglected in the original tickets. This issue serves as a buffer to complete writing unit tests for the "Saved cards" screen.~~

We want to test the following:
- Create some dummy credit card items in the storage and ensure they are properly displayed in the "Saved cards". This includes that the obfuscated card number is displayed, credit card provider icon, expiry year and month.
- Ensure clicking on the a saved card navigates to the "Edit card" screen and the correct credit card data is displayed.
- Ensure clicking on the "Add credit card" button navigates to "Add card" screen.

<img width="356" alt="Screen Shot 2021-03-02 at 4 20 00 PM" src="https://user-images.githubusercontent.com/1190888/109723329-f36af900-7b7b-11eb-9f11-93c666851a51.png">

**Comment by abodea** [comment]
This is partially fixed, please note that clicking on the saved card navigates to the "Edit card" screen, and the correct credit card data is displayed, and clicking on the "Add credit card" button navigates to "Add card" screen.
But the icons for the cards are missing.

Removing `eng:qa:needed` until further notice.
![Screenshot_20210526-160036](https://user-images.githubusercontent.com/42831109/119664125-b3927580-be3b-11eb-9ca6-368c18c4e6ba.jpg)

**Comment by gabrielluong** [comment]
Icons should be. Adding back qa:needed.

**Comment by gabrielluong** [comment]
We also got a list of valid credit cards here https://searchfox.org/mozilla-mobile/source/android-components/components/support/utils/src/test/java/mozilla/components/support/utils/CreditCardUtilsTest.kt#58-73. I will note we do not have the icon cartebancaire.

**Comment by abodea** [comment]
Thank you @gabrielluong!
Verified as fixed on latest Nightly 5/27 with OnePlus Nord (10).
The icons are displayed correctly.
