### ISSUE TITLE
[Saved cards] Display the credit card provider icon

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18271]
This issue is to add the various credit provider icons into Fenix and display them in the "Saved cards" screen. This depends on https://github.com/mozilla-mobile/fenix/issues/18268

<img width="356" alt="Screen Shot 2021-03-02 at 4 20 00 PM" src="https://user-images.githubusercontent.com/1190888/109719574-d7b12400-7b76-11eb-9bee-8fb9a5065ca4.png">

**Comment by abodea** [comment]
Re-opening as I think it was closed in a PR, until I will confirm it.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/27 with OnePlus Nord (10).**
