### ISSUE TITLE
FNX-5269 ⁃ Tab switcher should show the current tab in home screen

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1827]
## Steps to reproduce
1. Open Fenix
1. Open multiple tab
1. Tap tab switcher

### Expected behavior
The tab that the user is switching away from is visible on the home screen without scrolling. The user can than switch back to that tab if they made a mistake, or easily go to the next or previous tabs as they wish. 

Fennec does this correctly. 

### Actual behavior
The home screen is loaded and the top of the home screen is shown.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1916 #11091215

**Comment by ekager** [comment]
So you basically want the currently selected tab to always be at the top of the tab list?

**Comment by yoasif** [comment]
I'm not saying that the tab _position_ should change - the list of tabs should just be scrolled so that the tab I am switching away from is at the top of the screen. 

The search / address bar is sticky already, so no change there. 

So if I had tabs:

tab 1
tab 2
tab 3
tab 4

and I am in tab 3 and tap the tab switcher button, I should then see:

<search box>
----
tab 3
tab 4

but I can still scroll up to see tabs 1 and 2. 

Hope that helps.

**Comment by topotropic** [comment]
related https://github.com/mozilla-mobile/fenix/issues/1826

**Comment by topotropic** [comment]
Let's sort tabs on start screen after recently interacted with. This way, the latest viewed is always at the top. (Background: in our foundational research we observed that mobile browsers are often used for quick, independent, informational searches  – also with the Collections feature we help people to organize tabs and structure their longer term research so that they don't need to rely on leaving tabs open)

**Comment by yoasif** [comment]
@topotropic Are you saying that the tab listing should be ordered by recently used? That would break #1826 and the secondary use case of tabs remaining in the same *relative* position to one another. 

At least on desktop, the preference to switch tabs based on recently used order is a preference, which would be nice to have - especially since in my brief testing, no other Android browser does this. 

![Screenshot from 2019-05-15 11-50-09](https://user-images.githubusercontent.com/152493/57789823-aa785500-7707-11e9-992b-bb5c407b74e9.png)

**Comment by buttercookie42** [comment]
Yes, a stable tab (as in browser tab, not the tab key) order means I can build a mental picture of my tabs - them reordering themselves all the time doesn't help with that (and would conflict with manual control as in #2487). And now that opening a link in a new tab finally seems to open the new tab next to the parent tab, this subsequent automatic reordering would also break the idea of having related tabs grouped together.

**Comment by yoasif** [comment]
I'm happy with the behavior after the fix in #1826. Closing this one.

**Comment by pwd-github** [comment]
Can this be reopened please?
