### ISSUE TITLE
[Add card] QA for the Add card screen

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18278]
~~In the event that unit tests were neglected in the original tickets. This issue serves as a buffer to complete writing unit tests for the "Add card" screen.~~

We will want to test the following:
- Ensure we display an error message when an invalid card number is entered.
- Validate the various input fields where necessary. (Descope for 90)
- Ensure "Cancel" navigates us back to the "Credit card" preferences screen
- Ensure "Save" and the checkmark button in the toolbar will hit the storage and add a new credit card.

<img width="353" alt="Screen Shot 2021-03-02 at 4 14 41 PM" src="https://user-images.githubusercontent.com/1190888/109722793-32e51580-7b7b-11eb-8f9b-b17809826b2c.png">

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/26** with **OnePlus Nord (Android 10).**
The `Please enter a valid card number` is correctly displayed.
