### ISSUE TITLE
[Edit card] Handle duplicates when updating a credit card

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18276]
When an user is editing a credit card from the "Edit card" screen, we should handle the case where the entered credit card to be saved turns out to be a duplicate.

This issue is to handle any error messaging to display when the entered credit card to be added turns out to be a duplicate.

This is blocked on UX investigation as of writing.

<img width="356" alt="Screen Shot 2021-03-02 at 3 51 48 PM" src="https://user-images.githubusercontent.com/1190888/109717915-ab94a380-7b74-11eb-9fac-b7a061c8f6d9.png">

**Comment by violasong** [comment]
Should show the same error message as in https://github.com/mozilla-mobile/fenix/issues/18275#issuecomment-799846579

**Comment by gabrielluong** [comment]
Should be resolved with https://github.com/mozilla-mobile/fenix/issues/18275
