### ISSUE TITLE
[Select credit card] Display a credit card autofill prompt

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18287]
This issue is to show the "Select credit card" prompt when a credit form is encountered that can be autofilled. This will depend on GV/AC work to wire everything up for this to be displayed. We will not worry about the functionality in the prompt in this issue and it is only focused on wiring things up to display the prompt.

This depends on https://github.com/mozilla-mobile/fenix/issues/18282.

<img width="396" alt="Screen Shot 2021-03-02 at 6 07 24 PM" src="https://user-images.githubusercontent.com/1190888/109728662-a50e2800-7b84-11eb-87f0-329c433e8b30.png">

**Comment by abodea** [comment]
@gabrielluong is there any test website for this?

**Comment by abodea** [comment]
Before verifying this, I have a question regarding how it should look, is this the correct one? 
Or there should be a prompt like in the picture from the description?
![Screenshot_20210519-120930](https://user-images.githubusercontent.com/42831109/118794188-fedbdf80-b8a1-11eb-8c5c-d22fbb6ab483.png)

Also, please note that I added this bug https://github.com/mozilla-mobile/fenix/issues/19559.

**Comment by abodea** [comment]
Removing `eng:qa:needed` until further notice.

**Comment by gabrielluong** [comment]
It should look like this 

![Screenshot_20210518-130804_Firefox Nightly](https://user-images.githubusercontent.com/1190888/118844105-b0761300-b898-11eb-8eb1-1cf3dca092cb.jpg)

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/26** with **OnePlus Nord (Android 10).**
![Screenshot_20210526-154433](https://user-images.githubusercontent.com/42831109/119663021-aaed6f80-be3a-11eb-8d2a-58f4945c8363.jpg)
