### ISSUE TITLE
[Select credit card] What if there are a lot of credit cards in the prompt

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18289]
This is a ticket to investigate edge cases related to have a large number of credit cards in the "Select credit card" prompt. 

<img width="396" alt="Screen Shot 2021-03-02 at 6 07 24 PM" src="https://user-images.githubusercontent.com/1190888/109729392-cb809300-7b85-11eb-9309-1745ede6b379.png">

**Comment by violasong** [comment]
Let's do the same as what currently happens when there are many logins. (I assume there's scrolling behavior?)

**Comment by gabrielluong** [comment]
Sounds good. Closing this since it wasn't only an issue for the UX question.
