### ISSUE TITLE
[Edit card] QA for the Edit card screen

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18281]
~~In the event that unit tests were neglected in the original tickets. This issue serves as a buffer to complete writing unit tests for the "Edit card" screen.~~

We will want to test the following:
- Ensure we display an error message when an invalid card number is entered.
- Validate the various input fields where necessary. (Descoped for 90)
- Ensure "Cancel" navigates us back to the "Saved cards" screen
- Ensure "Save" and the checkmark button in the toolbar will hit the storage and updates the credit card. 
- Address edge cases where we encounter a duplicate credit card when trying to save.
- Ensure the "Delete card" button trashcan button in the toolbar deletes the credit card entry and check that it does not exist in the storage.

<img width="356" alt="Screen Shot 2021-03-02 at 3 51 48 PM" src="https://user-images.githubusercontent.com/1190888/109724068-f7e3e180-7b7c-11eb-9316-d047f7ec44bf.png">

**Comment by abodea** [comment]
As the #19492 is still reproducible, removing `eng:qa:needed` until that issue is fixed.

**Comment by gabrielluong** [comment]
@abodea I am curious if this is still reproducible now that https://github.com/mozilla-mobile/fenix/issues/19680 has landed. Can you recheck? Thanks!

**Comment by abodea** [comment]
- `Ensure we display an error message when an invalid card number is entered.`
     There an error message displayed `Please enter a valid credit card number`.

- `Validate the various input fields where necessary. (Descoped for 90)`
   N/A
- `Ensure "Cancel" navigates us back to the "Saved cards" screen`
  The `Cancel` button navigates correctly to the `Saved cards` screen.

- `Ensure "Save" and the checkmark button in the toolbar will hit the storage and updates the credit card.`
   Credit cards are saved without issues and correctly when tapping on `Save` @gabrielluong I think this is the correct behavior, right?

- Address edge cases where we encounter a duplicate credit card when trying to save.
  I can add a duplicate of the same card, this is not fixed.

- Ensure the "Delete card" button trashcan button in the toolbar deletes the credit card entry and check that it does not exist in the storage.
 This works as expected, the credit card is deleted but shouldn't be a dialog text asking if you really wanna delete the CC?

Note that Fenix still crashes when trying to edit, but I think this is what you asked above.

**Comment by gabrielluong** [comment]
I think we should be verified now.
