### ISSUE TITLE
[Bug] Ads still appear on several sites while using extensions for blocking ads

### ISSUE THREAD

**Issue by sparta65** [mozilla-mobile/fenix#18303]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information) 
Ads still appear on several sites even though they have used ad blocking tools such as ad guard ad blocker and ublock origin and I will include a web page that still displays ads even though there is an ad blocking tool, the following is the website  https://158.69.0.201/ lakshmi-2018 / and maybe there are many other websites that still display advertisements even though they have used an ad blocker tool please what is the solution
## Steps to reproduce 
added more pop-up ad blocking software and website redirect
### Expected behavior
There are still a lot of ads popping up
### Actual behavior I wanted an internet browsing without annoying advertisements and pop-ups

* Device vendor / model and Android version: ADVAN 5505 Android 10 Q (Go Edition)
* Firefox for Android version: Nightly 210302 17:01 (Build #2015796361)
AC: 74.0.20210301143120, 8a55899f2
GV: 88.0a1-20210301093612
AS: 72.1.0

**Comment by mcarare** [comment]
@sparta65 I think you should raise this issue with the developers of the extension. 
uBlock for example https://github.com/gorhill/uBlock/issues.
Only if the extension developers assess the situation and think it's a problem on our side we will look more into it.
