### ISSUE TITLE
[Bug] [a11y] Consider increasing the custom tab's toolbar title and toolbar url view

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#18307]
## Prerequisites
1. Make sure you have Accessibility Scanner installed and turned on.
2. Make Fenix the default browser app.

## Steps to reproduce
1. Open an external browsing app (i.e. Gmail), and open a link to a website.
2. Using the Accessibility Scanner, scan the Custom tab.

### Expected behavior
No major discrepancies are reported.

### Actual behavior
The scanner suggests to increase the sizes of the browser toolbar title and the browser toolbar url view from the custom tab.

### Device information
* Device vendor / model and Android version: OnePlus 5T (Android 10)
* Firefox for Android version: 87.0.0-beta.2

![Untitled](https://user-images.githubusercontent.com/40694158/109779866-10044100-7c0f-11eb-9a8c-93ffd1ba8cde.png)

**Comment by mcarare** [comment]
Although this is something that usually needs improving, in this case, although the title and subtitle are `clickable` there are no actions associated with this so there is no need to improve the touch target. 

Given the reasons above I am closing this.
