### ISSUE TITLE
[Bug] Amazon.co.uk track package link opens play store?

### ISSUE THREAD

**Issue by euinor** [mozilla-mobile/fenix#18308]
See org. ticket https://github.com/mozilla-mobile/fenix/issues/12072

## Steps to reproduce
Click link in an email from Amazon, subject 'Your Amazon.co.uk order #ordernumber', button is 'track your package'. Awkwardly I think the link contains personal information so it is hard to share? Also it doesn't happen with 'smile.amazon' links just normal amazon.
Note:'open in app' setting is switched on in browser.
Edit: I don't know whether this is Amazon hijacking the openinapp function (Reddit used to do that too) or if it is something wrong with Firefox

## Expected behavior
Opens amazon.co.uk webpage in browser.

## Actual behavior
Opens Google play store app at Amazon Shopping app store page. Pressing back takes you to the browser and the correct webpage.

## Device information
    Android device: Pixel 3a
    Fenix version: 86.0.0-beta.5

**Comment by mcarare** [comment]
@euinor There is no reason to open a duplicate issue. You can comment on the original one (https://github.com/mozilla-mobile/fenix/issues/12072)
