### ISSUE TITLE
FNX-5272 ⁃ Update tab visual style

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1830]
![image](https://user-images.githubusercontent.com/1250545/56439311-878a8a80-629a-11e9-873e-adc18876bca7.png)

**Comment by sv-ohorvath** [comment]
@boek Are the thumbnail images going to be implemented later or should they already be done? Not appearing at the moment.

**Comment by yoasif** [comment]
FWIW, whatever the thumbnail building code exists in Fennec seems to work really well and always seems to look good in my experience. The one in Fenix never seemed to look right to me. Fennec also used squares, so it is something to look at, imo.

**Comment by kbrosnan** [comment]
The base of the styles are in product however we are missing the favicons. This is not complete until the spec is met. @boek @st3fan [Jeff is on PTO]

**Comment by sv-ohorvath** [comment]
@boek This was blocked by the missing thumbnail images. Currently, it's still in the same state. Is there any change we should test?

**Comment by sv-ohorvath** [comment]
Ok, I just saw the thumbnails being updated, but for some websites it takes a little longer. Marking this as fixed on the 5/22 build.
