### ISSUE TITLE
[Bug] Navigation toolbar is not dynamic

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#18305]
## Steps to reproduce
1. Launch Fenix with the toolbar set to the bottom;
2. Open a website and scroll up and down observing the navigation toolbar;
### Expected behavior
The navigation toolbar is dynamic:
- scrolling down auto-hides it,
- scrolling up displays it again.
### Actual behavior
Navigation toolbar is not dynamic.

### Notes
This is also reproducible when the toolbar is set to the top, also in private browsing, also in landscape mode.

![20210303_094225](https://user-images.githubusercontent.com/48799384/109771058-0d9ce980-7c05-11eb-9bd7-95936b817f31.gif)

### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9), OnePlus 5T (Android 10);
* Firefox for Android version: Nightly 3/3
* Not reproducible on Beta 87.0.0-beta.2 from 3/1 and Release 86.1.1 from 2/23.

**Comment by Furax-31** [comment]
Same problem.

**Comment by hwinnemoe** [comment]
Sounds like maybe https://github.com/mozilla-mobile/fenix/pull/18154 is required since the AC changes https://github.com/mozilla-mobile/android-components/pull/9771 have already landed in Fenix, cc @Mugurell

**Comment by Mugurell** [comment]
Thank you for tagging me.
Indeed, this should work again in tomorrow's Nightly.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 5/3 with the following devices:
- LG G7 Fit (Android 8.1)
- Samsung Note 10 (Android 11)
