### ISSUE TITLE
Add content description for history list items

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18317]
We should add a `contentDescription` to `history_list_item.xml` for screen readers.

**Comment by sanyud24** [comment]
I would like to work on thus issues. May I  ?

**Comment by eliserichards** [comment]
Hi @sanyud24! Are you a Outreachy applicant? 😄

**Comment by sanyud24** [comment]
Yeah, I'm from India,  thanks a lot! ..I'll start working on this issue

**Comment by sanyud24** [comment]
I'm a little confused , inside history_list_item.xml ,I saw only one textview for the delete history button and another is LibrarySiteItemView , where do I have to add contentDescription ? It'll be a lot of help if I can get a  little idea where to do it , thankyou.

**Comment by sanyud24** [comment]
Do i have to do it in library_site_item.xml ?

**Comment by mcarare** [comment]
Closing as invalid. Items already have a content description.
