### ISSUE TITLE
Glean code adds ~61ms on COLD start up, all types

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18322]
We ran an experiment where we "removed" Glean and measured the COLD start up duration: it improved median start up performance by 61ms on Nightly builds on the Moto G5. A 61ms potential improvement is significant: it's the largest remaining win we've found for all start up types.

To "remove" glean, we:
- disabled telemetry by flipping the commented out [`isDebug` flag in gradle](https://github.com/mozilla-mobile/fenix/blob/62bd3b4f95fe73984dc7606769b4514a0f31e96e/app/build.gradle#L283)
- commented out [initializeGlean()](https://github.com/mozilla-mobile/fenix/blob/62bd3b4f95fe73984dc7606769b4514a0f31e96e/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L93)

Note: there's still 13ms of Glean related code in the profile for the experiment https://share.firefox.dev/3kj9PYN so this wasn't a perfect removal and the wins could be greater (or less).

In theory, a performance-first implementation shouldn't have much overhead: for each recorded metric, it could queue the data in memory and, only after we've finished start up, we could do the heavy lifting to initialize Glean and transmit any pings. With this theory in mind, it seems like we can improve on the current implementation. That being said, the product team may prefer to take a performance hit, e.g. to send data earlier so we should discuss what are requirements are and work within them.

Marc mentioned a large part of this overhead may be attributable to the first SharedPrefs read (I think to determine if Glean is enabled or not).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9937)

**Comment by mcomella** [comment]
Triage: let's let the Glean team know about it https://github.com/mozilla-mobile/perf-frontend-issues/issues/187 and figure out if it'd be a priority for them. If it's not, we should decide if we want to work on it or not. If it's difficult, it might be good to put off to see if we can find better low effort, high impact wins.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813248

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
