### ISSUE TITLE
[UX] Minimising number of clicks in copying  a link

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18328]
### What is the user problem or growth opportunity you want to see solved?
While looking at some page, if I want to share the Url, if have to copy it manually, 
there is no feature to copy or share.

### How do you know that this problem exists today? Why is this important?
It takes more [clicks](https://uxdworld.com/2020/01/28/3-click-rule-and-usability/). The number of clicks or taps is a good metric, it is essential to inform the design and product teams about different problem areas, and opportunities.
The three-click rule or [three-click rule](https://en.wikipedia.org/wiki/Three-click_rule) is an unofficial web design rule concerning the design of website navigation. It suggests that a user of a website should be able to find any information with no more than three mouse clicks. It is based on the belief that users of a site will become frustrated and often leave if they cannot find the information within the three clicks.

**Comment by mcarare** [comment]
@RiyaJ2311 Currently you can copy the URL using 2 clicks: long click on URL and select copy option.
Also, there is an option to share it from the share menu. 
Is there something different you had in mind?

**Comment by RiyaJ2311** [comment]
@mcarare I was thinking if adding a copy button next to the link whenever someone taps on the link would work, because no one would click the link without any intention to either copy it or share it, so if we could both copy and share button together with the link then it would work.

**Comment by mcarare** [comment]
This is maybe a question for UX, but IMO the URL bar already has enough icons and would only save one click.

**Comment by RiyaJ2311** [comment]
> This is maybe a question for UX, but IMO the URL bar already has enough icons and would only save one click.
Thank you for your opinion, I will close the issue.
