### ISSUE TITLE
Videos are zoomed too much and I cannot see subtitles in youtube

### ISSUE THREAD

**Issue by honwen123** [mozilla-mobile/fenix#18329]
Please make a setting to play video in the original video aspect ratio and zooned to fill screen.I reported this before but it wasnt fixed on firefox 85.

**Comment by Dunexus** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/8252

**Comment by kbrosnan** [comment]
Closing as a duplicate. See near the end of the issue for a workaround using uBlock origin.
