### ISSUE TITLE
[Bug] Mobile Navbar drop-down menu doesn't open when clicked

### ISSUE THREAD

**Issue by jonzdev** [mozilla-mobile/fenix#18332]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open latest Firefox for Android, go to www.jonz.eu, click on three-line "hamburger" menu at top of page (doesn't matter if you accept cookie banner first).

### Expected behavior
Menu opens.

### Actual behavior
No response. On one of the tested devices (Note 9), if you scroll down the page and then back up, then the menu will work until page refreshes. Also tested in Firefox Private Tabs with same result. (Further tested on Chrome Browser without issues.)

### Device information
Tested on Galaxy Note 4 N910F (Android 6.0.1), Sony Xperia L1 G3311 (Android 7.0), Galaxy Note 9 N960F (Android 10).  
All devices running Firefox 85.1.1

**Comment by hakkikaancaliskan** [comment]
Looks like this is a website issue. If you report this problem with "Report site issue..." button in the menu, webcompat team will investigate deeply and take care of the issue.
![Screenshot_20210304-235039_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/110028606-822a7200-7d44-11eb-92b4-df439302ed60.png)

**Comment by jonzdev** [comment]
Done, thank you.

**Comment by sflorean** [comment]
Closing this issue due to the fact that a webcompat issue is opened. @jonzdev thank you for your report!
