### ISSUE TITLE
Add telemetry for memory consumption at key points

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18336]
For this issue, we want to a probe to help us notice memory consumption issues and begin as a starting point for investigations into memory consumption improvements. https://github.com/mozilla-mobile/fenix/issues/17590 We'd want this probe to help answer questions like:
- are we consuming a reasonable amount of memory for this device?
- are we consuming more memory than we used to?
- does our memory consumption create more problems in some areas of the app than others?

We should land this early so we have historic data with which to identify regressions.

csadilek and the perf team identified a few points where it might be valuable to capture this data, primarily because they're places where we see memory errors:
- on tab switch
- before page load
- after page load
- onPause or similar (we don't see memory problems here but it's the last point before the app is backgrounded so could be interesting)

One open question is, what is the best metric for us to analyze memory consumption? 
1. record current memory consumption? e.g. 456MB used (if so, we may need to also add a probe for total memory on the system if it doesn't already exist)
1. record the ratio of memory used / total memory? e.g. 50% memory used (for 1 GB used in a 2 GB system)

I think that 1 might be preferred – it can be combined with a total memory probe to create the ratio from 2. However, 2 might be simpler to analyze quickly in GLAM without custom SQL.

**Comment by MarcLeclair** [comment]
Closing since we don't think we'll get to it soon. We could always reopen this issue if we feel like we need to add probes for memory consumption.
