### ISSUE TITLE
[UX] Adding a home icon next to refresh and use it as additonal bar for navigation

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18339]
### What is the user problem or growth opportunity you want to see solved?
Adding a simpler way to get back to the home screen, like to refresh the app, a user can tap anywhere on the bottom half of the screen and drag downward. A small refresh icon will appear and will spin while it fetches the changes. In a similar way, we can add a home icon along with the refresh icon.

### How do you know that this problem exists today? Why is this important?
users tend to press the back button when they cannot find the home icon on the screen, which makes them lose their history

### Who will benefit from it?
New Users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9950)

**Comment by boek** [comment]
We now have a home icon in the toolbar, feel free to open another issue if you think there is more room for improvement :)
