### ISSUE TITLE
[webcontent]"game.granbluefantasy.jp"'s web content bug

### ISSUE THREAD

**Issue by naloder** [mozilla-mobile/fenix#18338]
The web content in game. Granbluefantasy.jp is not properly scaled and displayed.When I play the game content, the web content is skewed to one side. The bug appears to exist in the original Firefox, but in non-Firefox browsers (Chrome and other browsers will work), it's not clear if this bug can be fixed?

### Device information

* Android device:redmi note9 pro 5g
* Fenix version:87.0.0-beta.3

**Comment by hakkikaancaliskan** [comment]
Please report webcontent bugs with "Report site issue" option in firefox menu. Webcompat team will investigate the site issue.

**Comment by sflorean** [comment]
@naloder thanks for your report! Please file the bug here https://github.com/webcompat/webcompat.com/issues or follow the steps as mentioned in the comment above. Make sure to try on Beta or Nightly, since "Report site issue" is not available on Release.
