### ISSUE TITLE
FNX-484 ⁃ [Bug] Address bar does not strip rich formatting

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1833]
## Steps to reproduce
* long press on the word **community**
* select copy
* paste the text into the address bar

### Expected behavior
* formatting is dropped

### Actual behavior
* formatting is preserved

### Device information
* Android device: Nexus 10 and Pixel 3
* Fenix version: April 19th build

**Comment by kbrosnan** [comment]
### More test text
*this is italic*

* bullet list one
* bullet list two
* bullet list three

1. number list one
2. number list two
3. number list three

**Comment by kbrosnan** [comment]
This should be fixed with the a-c work.

**Comment by AndiAJ** [comment]
Hi, I've tested the above mentioned issue but, I'm not sure if it works properly on` Fenix #11791805 from 28/6` as the behaviors are quite different.

#### **1.** For both **`Google Pixel 3XL (Android 9)`** & **`Huawei Mate 20 Lite (Android 8.1.0)`** when trying to paste a rich text you have available 2 options:
• "Paste" - When selecting this option the format is preserved
• "Paste as plain text" -  When selecting this option the format is dropped
![2019_07_01_12_57_23](https://user-images.githubusercontent.com/51314259/60428258-20297900-9c01-11e9-95bf-e1f435708a94.gif)





#### **2.** Using a **`Samsung Galaxy S7 (Android 7.0)`** when selecting both "Paste" & "Clipboard" format is dropped
![20190702_031452](https://user-images.githubusercontent.com/51314259/60429055-e22d5480-9c02-11e9-88a1-c3c8b1d32553.gif)





#### **3.** For both **`Samsung Galaxy J7 (Android 6.0.1)`** & **`Sony Xperia Z3 (Android 5.1.1)`** there's ony one option "Paste" and after pasting the text format is preserved
![20190701_131632](https://user-images.githubusercontent.com/51314259/60429127-0e48d580-9c03-11e9-9748-14b7d6d5369a.gif)


@kbrosnan please advise on how to proceed.

**Comment by darkwing** [comment]
This issue still exists - still need fixing in AC

**Comment by marcinwiacek** [comment]
I've done fix for Android M and higher, can somebody help me with processing this please?

https://github.com/mozilla-mobile/android-components/pull/5497

**Comment by kbrosnan** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/5497
