### ISSUE TITLE
[Bug] Swipe to switch tab gesture stops working after locking / unlocking

### ISSUE THREAD

**Issue by Sayrus** [mozilla-mobile/fenix#18341]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

With swipe to switch tab:
- Lock device
- Unlock using fingerprint

**Note:**
- There are sometimes streak where it works properly but closing the app will nearly always make the bug happen on next try
- Changing to landscape back to portrait or opening the opened app list will resolve the issue
- Unlocking using passcode works like a charm 

### Expected behavior

Swipe change tab works as usual

### Actual behavior

Swipe opens keyboard to edit URL (or swipe start and end are in URL textbox) or does nothing (if one of them is outside the textbox).
The behavior is the same as the one observed in a new tab (you can't use the gesture to change to another tab)

### Device information

* Device vendor / model and Android version: ? Xiaomi Mi Mix 3 / MIUI 11.0.5 / Android 10
* Firefox for Android version: ? Nightly 210304 (Build #2015796747). This bug has been happening for several months, it is not specific to this release

Linking to  #176

**Comment by sflorean** [comment]
Tested on Huawei P40 Lite (Android 11) and couldn't reproduce the issue on Nightly 5/3 using fingerprint or close/open app. 
@Sayrus do you have other steps? a video with the issue will help in order to be able to reproduce it. Thank you!

**Comment by Sayrus** [comment]
There might be some Xiaomi shenanigan going on here.

![firefox](https://user-images.githubusercontent.com/22404472/110125833-a9705600-7dbb-11eb-963e-dc25b5f1269d.gif)

**Comment by sflorean** [comment]
Tested also on latest Nightly build with Xiaomi Redmi Note 8T (Android 9) and couldn't reproduce it.

**Comment by Sayrus** [comment]
Is there anything I can do to help reproduce?

I can easily reproduce it on my device but I have no idea what triggers this.

**Comment by mariansima** [comment]
Could not reproduce this issue on Samsung A8 (Android 9) with Firefox Nightly 93.0a1 2021-09-07. Tried switching multiple device display settings like gestures in advanced features.

**Comment by Sayrus** [comment]
Hey @mariansima,
Thanks for the update and reopening the issue.

I can still reproduce (93.0a1 #2015832267) but the behavior changed a bit from before.

When clicking the search bar then using the back button to close it, the issue fixes itself (No need to rotate the display or temporarily leave the app as before).
Since it will mostly fixed itself (when you fail to swipe, it usually opens the search bar), this is not as bad as it used to be.

If you have any idea on how I can help pinpoint the issue / provide logs / ..., I'd gladly help.

**Comment by mariansima** [comment]
Hey @Sayrus, glad to help. 

I am still unable to reproduce the issue as you describe it (on 94.0a1), with the exception of the homescreen, where the swipe functionality should not work. 

Nightly is updated daily, and if this still occurs on the latest build, some useful information would be if you use custom settings for the address bar or just the default.

**Comment by Sayrus** [comment]
Hello @mariansima, thanks !

I'm currently on 94.0a1. I can still reproduce.

To trigger it, I need to do the following:
1. Lock (I tested with Physical button and Timeout)
2. Light up the screen (Tested with physical button, sliding the screen, raise to wake and double tap)
3. Unlock using fingerprint

If I miss any of those, especially the second one, I can't trigger the bug. Usually waiting 1 or 2 seconds after the first step helps reproducing the issue (around enough time for Always-On to trigger, but it triggers even with Always-On disabled. Maybe it's only a coincidence)

The options I use for Customize are:
- All Gestures enabled
- :warning:  Bottom Toolbar (I don't seem to be able to reproduce with Top Toolbar even after dozens of tries)

For the Search:
- DDG
- All settings on On except for `Show search engines`, `Show voice search` and `Show in private sessions`

Tabs:
- Tab view set to List
- Close tabs: Manually
- Start on home: After four hours (Also tested with Never)

I can reproduce with and without addons.
I don't think I use fancy settings, I'm not logged in to Firefox Account.

I hope that helps.

**Comment by mariansima** [comment]
@Sayrus Unfortunately I still can't reproduce the issue on my end (Samsung Galaxy A8 with Firefox Nightly 94.0a1 2021-10-1). This issue could be OS/device specific. Hopefully someone else can try to reproduce using the steps in your latest comment on a more similar device.
