### ISSUE TITLE
WebAuthn implementation doesn't allow retry

### ISSUE THREAD

**Issue by huaracheguarache** [mozilla-mobile/fenix#18347]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open webauthn.hwsecurity.dev and tap "Create credential" to get the read NFC key prompt.
2. Swipe back to return to Firefox.
3. Tap on "Create credential" again.

### Expected behavior

The same behaviour as in Chrome where I get the following error message:

![Screenshot_20210226-130300](https://user-images.githubusercontent.com/33153877/110202595-13473900-7e6a-11eb-9afc-1ce81b4a85e0.png)

Tapping "Create credential" after this results in a new prompt to read an NFC key.

### Actual behavior

After swiping back the page look like this:

![Screenshot_20210226-124314](https://user-images.githubusercontent.com/33153877/110202658-7f29a180-7e6a-11eb-995a-e5b4f8f9ffbe.png)

Tapping "Create credential" produces the following message, but no new prompt:

![Screenshot_20210226-124326](https://user-images.githubusercontent.com/33153877/110202687-a5e7d800-7e6a-11eb-945c-699e0cbc5c50.png)

### Device information

* Device vendor / model and Android version: Nokia 8.1 with Android 10
* Firefox for Android version: 
Nightly 210305 17:01 (Build #2015796939)
AC: 74.0.20210305144553, 58cfb6476
GV: 88.0a1-20210302034602
AS: 72.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9955)

**Comment by huaracheguarache** [comment]
@jonalmeida Could you take a look at this? This bug is still present in the latest Nightly:

![Screenshot_20210505-115625](https://user-images.githubusercontent.com/33153877/117124940-396d5480-ad99-11eb-9f45-8cf7ab0ca611.png)

**Comment by jonalmeida** [comment]
Hmm.. I think we need to investigate if we're sending the intent back to GV correctly to cancel and request again, or if GV is doing something wrong here.

**Comment by mhalano** [comment]
This seems a very important problem, since affects user experience. User should be able to get a second chance to login with Webauthn.

**Comment by huaracheguarache** [comment]
Is this still an issue? We're moving into times where passwordless authentication is becoming more prevalent, and recently Apple, Google, and Microsoft announced [an initiative](https://techcrunch.com/2022/05/05/apple-google-microsoft-passwordless-logins/) to expand support for passwordless authentication. Could you please devote some time to fix this?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807263

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
