### ISSUE TITLE
PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()` returns false even when supported

### ISSUE THREAD

**Issue by uwolfer** [mozilla-mobile/fenix#18346]
While webauthn.io demo works with platform authenticator and required user verification in nightly, `PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()` returns false. I'd expect it to return true. Is this a known thing?

Nightly 210305 17:01 (Build #2015796939)
AC: 74.0.20210305144553, 58cfb6476
GV: 88.0a1-20210302034602
AS: 72.1.0

_Originally posted by @uwolfer in https://github.com/mozilla-mobile/fenix/issues/1340#issuecomment-791647047_

**Comment by uwolfer** [comment]
CC @jonalmeida

**Comment by uwolfer** [comment]
Is there anything I could support you in order to speed up resolving this issue?

**Comment by jonalmeida** [comment]
@uwolfer this looks like a bug that we need support from GeckoView to get it fixed. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1711541 for it as well.

**Comment by kbrosnan** [comment]
Closing upstream issue.

**Comment by jonalmeida** [comment]
@uwolfer the next Firefox Nightly release (some time tomorrow), should have the fix.

(posting here in case your github notifications reach you sooner than your bugzilla ones)

**Comment by uwolfer** [comment]
> @uwolfer the next Firefox Nightly release (some time tomorrow), should have the fix.

Thanks. I can confirm that it now works as expected.
