### ISSUE TITLE
FNX-5273 ⁃ [Bug] There is a line below the search that makes no sense

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#1834]
`##` Steps to reproduce
Open the app, switch to dark theme.

### Expected behavior
No line bellow  search.

### Actual behavior
There is a line bellow search
![Screenshot](https://user-images.githubusercontent.com/922368/56440789-42df0d80-62f3-11e9-8420-7bba963b705b.png)UNITO-UNDERSCORE!20190419-223151!UNITO-UNDERSCORE!Fenix!

### Device information
![Screenshot](https://user-images.githubusercontent.com/922368/56440811-5ab69180-62f3-11e9-8b3a-9ef3b440fcdf.png)UNITO-UNDERSCORE!20190419-113720!UNITO-UNDERSCORE!Fenix!
![Screenshot](https://user-images.githubusercontent.com/922368/56440822-6013dc00-62f3-11e9-9014-4dd54c125ab8.png)UNITO-UNDERSCORE!20190419-113741!UNITO-UNDERSCORE!Settings!

**Comment by andreicristianpetcu** [comment]
the line is there in light theme and private browsing

**Comment by yoasif** [comment]
This appears when there are no tabs open in a normal session; I think the divider is fine in private browsing mode because there is a note below it, but in normal mode it looks like a lack of polish. 

When tabs are open in normal mode, I think it also looks fine.

**Comment by cadeyrn** [comment]
There is always content below the line. This is how it looks in a recent build of Fenix:

![Screenshot_20190420-090028](https://user-images.githubusercontent.com/1100614/56454011-e14a8d80-634a-11e9-9c97-88ead0aa2a73.png)

**Comment by andreicristianpetcu** [comment]
I see.... so it is not a bug, it's intentional. I consider it ugly and useless but I can live with it :)

**Comment by mheubusch** [comment]
@andreicristianpetcu - It's definitely a bug - just not the one you described. :)  the content that appears in light theme should also appear in dark theme.  @AmyYLee Can you provide specs for the no open tabs state on the home screen in dark theme?  Thank you!

**Comment by cadeyrn** [comment]
>  It's definitely a bug - just not the one you described. :) the content that appears in light theme should also appear in dark theme.

It appears also in dark theme. The issue was opened before the content landed in #1829. ;-)

**Comment by mheubusch** [comment]
Touché

**Comment by andreicristianpetcu** [comment]
![Screenshot_20190422-005401_Fenix](https://user-images.githubusercontent.com/922368/56476011-4ad8b200-6499-11e9-90ab-85a093107a21.png)
