### ISSUE TITLE
Google Stadia working in Firefox browser (desktop)?

### ISSUE THREAD

**Issue by teobb** [mozilla-mobile/fenix#18355]
I hope is not against the rules, but I'm aware that Stadia can run without Chromium broswers using a script that eases the task of creating an electron package for the Google Stadia web app. It uses Nativefier as packager and creates an Electron application that you can use to play Google Stadia on our machine.

It would be nice to have the chance to play Stadia on Firefox

I know a developer that already has this done on a standalone package and the code is free, open sourced in github, I can paste the link here if it's not against the rules if it helps and it can be integrated in Firefox

**Comment by cadeyrn** [comment]
> Google Stadia working in Firefox browser (desktop)

This is the issues tracker for Firefox for Android. You can find the issues tracker for the desktop Firefox here:
https://bugzilla.mozilla.org/

**Comment by teobb** [comment]
> > Google Stadia working in Firefox browser (desktop)
> 
> This is the issues tracker for Firefox for Android. You can find the issues tracker for the desktop Firefox here:
> https://bugzilla.mozilla.org/

My bad sorry! 
Thanks
