### ISSUE TITLE
Add tab view swipe to navigate between open tabs and private tabs

### ISSUE THREAD

**Issue by ameaninglessname** [mozilla-mobile/fenix#18353]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
It's not convenient enough to navigate between "open tabs" view and "private tabs" view

### How do you know that this problem exists today? Why is this important?
For better UX.

### Who will benefit from it?
All users.

I came up with three "solution":
Which one do you prefer or you have a better idea?
(Let's vote with these reaction🤣)
![image](https://user-images.githubusercontent.com/20263103/110227879-b914a980-7f37-11eb-8b41-cf1899749d0f.png)

"Solution 1"                     |  "Solution 2"                   | "Solution 3"
:-------------------------:|:-------------------------:|:-------------------------:
Swipe in blank area ![Swipe in blank area](https://user-images.githubusercontent.com/20263103/110228154-cdf23c80-7f39-11eb-9d71-2b79256b83d1.png)| Swipe like address bar ![Swipe like address bar](https://user-images.githubusercontent.com/20263103/110228157-d34f8700-7f39-11eb-8064-8c4cf345856d.png)| Swipe in blank area ![Swipe in blank area](https://user-images.githubusercontent.com/20263103/110228159-d5194a80-7f39-11eb-82e5-1d43b8cb102b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9960)

**Comment by Ansem93** [comment]
I voted for the first option with the thumb up 👍

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812883

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
