### ISSUE TITLE
[UX] Aligning the text to the center

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18354]
### What is the user problem or growth opportunity you want to see solved?
When considering the text alignment for your web page content-centered text.
Whitespace is actually really important to web design because you can use it to improve readability and website performance.
![image](https://user-images.githubusercontent.com/48223671/110231302-01829600-7f3d-11eb-97ff-4641734950b6.png)

### How do you know that this problem exists today? Why is this important?
Before downloading the application, people tend to visit the website to understand why they should prefer the new application, rather than their existing ones.

### Who will benefit from it?
People who are planning to switch to firefox

**Comment by cadeyrn** [comment]
This issues tracker is only about Firefox, not about the Mozilla website.

**Comment by RiyaJ2311** [comment]
> This issues tracker is only about Firefox, not about the Mozilla website.

yes. it is for the [firefox website](https://www.mozilla.org/en-US/firefox/mobile/)

**Comment by amedyne** [comment]
@RiyaJ2311 Any issues, suggestions on the Mozilla website can be logged in bugzilla: https://bugzilla.mozilla.org/home.  I encourage you to log issues,suggestions in bugzilla. Thank you!
