### ISSUE TITLE
[Bug] choppy scrolling on https://www.deutsche-rentenversicherung.de

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#18351]
## Steps to reproduce
1. Open https://www.deutsche-rentenversicherung.de
2. Scroll down.

### Expected behavior
Smooth scrolling

### Actual behavior
Choppy scrolling close to the position when the 3 overlay buttons at the bottom start to get shown, and close to the end.

### Device information

* Device vendor / model and Android version: Sony Xperia XZ2 Compact
* Firefox for Android version: Nightly 210305, Beta 87.0.0-beta 3, Release 86.1.1 on Android 10

**Comment by LittleAngelwings** [comment]
I can confirm this issue on smartphones devices with powerless cpu/gpu and less of RAM /3GB). Both devices has Android 8 and 9 and old ARM. On my Chromebook with Chrome OS 88/ Android 9 and Intel 5 (10th gen, 8 GB RAM) i don't have this behaviour.

**Comment by Mikaka27** [comment]
Related to this perhaps: #18078 ?

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview 87.0.0-beta.4 and Nightly 210309.

### Devices used:
- Huawei MediaPad M3 (Android 7.0)

**Comment by mcomella** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1699261

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by mcomella** [comment]
This is a platform issue (scrolling in GeckoView) so moving to bugzilla where they can track it.
