### ISSUE TITLE
[Bug] Issue with page navigation 

### ISSUE THREAD

**Issue by pavi2410** [mozilla-mobile/fenix#18356]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Description

On some websites that I visit through Duckduckgo, I can't navigate back. The backward button is also disabled as well as the list presented when long pressing the back button is empty.

I found a few more issues
- The URL in the address bar shows that of the previous page.
- I can't long click a link on that same page.

## Screenshots

![IMG_20210307_204332.jpg](https://user-images.githubusercontent.com/28837746/110245186-29e3b200-7f88-11eb-91b7-0f0ab08da9c8.jpg)

![IMG_20210307_204355.jpg](https://user-images.githubusercontent.com/28837746/110245192-30722980-7f88-11eb-9424-f6a9928d1a56.jpg)

## Screen recording

![Screenrecording_20210307_205357.mp4](https://user-images.githubusercontent.com/28837746/110245114-f43ec900-7f87-11eb-8832-8c05cdb2de9e.mp4)

## Steps to reproduce
I don't actually know know to reproduce but it usually happens when I visit a site from duckduckgo.

### Expected behavior
I should be able to navigate back to the previous page.

### Actual behavior
When I press back button, the app closes as if there are no pages to navigate back to.

### Device information

* Device vendor / model and Android version: ?

vivo v20 Android 11

* Firefox for Android version: ? (go to Settings -> About Firefox)

87.0.0-beta.3 (Build #2015796803)
AC: 73.0.5, bc5fe91b4
GV: 87.0-20210304190020
AS: 71.0.0

**Comment by sflorean** [comment]
I wasn't able to reproduce this on latest Nightly with Pixel 3 (Android 11) and Huawei P40 Lite (Android 11). 
@pavi2410 from your video I see that the links aren't working (I didn't see new page to open) witch means that if you don't have previous pages opened in the same tab, it is expected that the back arrow to not be available. Could you please make another video, where the new page is opened? Thank you!

**Comment by pavi2410** [comment]
> Could you please make another video, where the new page is opened?

I am not sure I understood well about what video should I make.

Also, I would like to point out that the shield icon (left to the address bar) is invisible.

To sum it up, there were 3 issues with that tab:
1. Couldn't go back to the previous page.
2. Long pressing a link didn't show the dialog.
3. Shield icon (left to the address bar) is invisible.

**Comment by codrut-topliceanu** [comment]
@pavi2410 Thank you for you report ❤️  . Unfortunately I haven't been able to reproduce the issue on my devices, but maybe I'm doing something wrong. Could you perhaps add another video where you go through the steps to reproduce? (Like open new tab, go to duckduckgo, search -> follow link).

I understand that this is an intermittent issue and it may be difficult to reproduce it on demand but we would be really grateful as minor details in a video could clue us in as to where the problem might stem from.

**Comment by pavi2410** [comment]
Well, I haven't faced this issue for a long time. So, closing...
