### ISSUE TITLE
[Bug] Page reloads on Android theme switching

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#18358]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1- Switch android theme
2- Web page reloading

### Expected behavior
It doesn't reload web page and waits link navigation to send "theme information" to website 

### Actual behavior
It reloads web page, for example this causes to miss where we left youtube video (goes back to start of video)

### Device information

* Device vendor / model and Android version: A11 XZ1
* Firefox for Android version: 3/6 nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9964)

**Comment by sflorean** [comment]
I was able to reproduce this bug on Nightly 3/7 and RC build, when switching the theme from Fenix Settings, with LG G7 Fit (Android 8.1).
Not reproducible on Chrome.

**Comment by hkaancaliskan** [comment]
Still reproducible

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 (Android 9) with Firefox Nightly 93.0a1 2021-09-07

**Comment by yaomtc** [comment]
Still occurs as of 99.0a1

**Comment by rokejulianlockhart** [comment]
@stale, this continues to occur.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807095

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
