### ISSUE TITLE
Undo close tab - tab appears at the top of the tab list

### ISSUE THREAD

**Issue by Noexpert** [mozilla-mobile/fenix#18359]
In the old Firefox version, when a user selected "undo" to a recently closed tab, the re-opened tab appeared at the end of the list of tabs. With the new version, it appears at the top / start, making discoverability difficult.

**Comment by Dunexus** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/10986

**Comment by mcarare** [comment]
Closing as duplicate of #10986.
