### ISSUE TITLE
[UX] Improving the footer bar

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18361]
### What is the user problem or growth opportunity you want to see solved?
this is for the[ website ](https://www.mozilla.org/en-US/firefox/mobile/)
![image](https://user-images.githubusercontent.com/48223671/110281752-4e30a480-8003-11eb-97f8-b4fa30b6efcc.png)
a [footer](https://www.nngroup.com/articles/footers/#:~:text=Thus%2C%20a%20footer%20can%20include,to%20reach%20the%20main%20navigation.) can include global navigation. This component is beneficial when the pages are long (as is the case with many modern mobile designs) since it allows users to quickly move to a different section of the site without scrolling back to reach the main navigation.

### Who will benefit from it?
Many people can use the footer for navigation

**Comment by cadeyrn** [comment]
As already explained in #18354: This issues tracker is **not** about issues with the website…

**Comment by amedyne** [comment]
@RiyaJ2311 Any issues, suggestions on the Mozilla website can be logged in bugzilla: https://bugzilla.mozilla.org/home.  I encourage you to log these in bugzilla. Thank you!
