### ISSUE TITLE
Add the Auto Tab Switch like in Firefox Focus

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#18365]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
All the time I need to click on the Popup to switch the tab.
Or an option to hold on "Open on new tab" to switch automatically.

### How do you know that this problem exists today? Why is this important?
Because is time save and no more useless click and popups.

### Who will benefit from it?
All

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9970)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812882

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
