### ISSUE TITLE
Could not process image.

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#18369]
Nightly
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10486746/

Beta
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/10490589/?query=is%3Aunresolved%20IllegalArgumentException

Release
No available

```

java.lang.IllegalArgumentException: Could not process image.
    at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(GeckoLoader.java)
    at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:101)
```

**Comment by Amejia481** [comment]
As the crash looks like it coming from https://searchfox.org/mozilla-central/source/widget/android/ImageDecoderSupport.cpp#63, I opened a GV ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1696928

**Comment by Amejia481** [comment]
Sentry issue: [FIREFOX-NIGHTLY-9SQ](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10486746/?referrer=github_plugin)

**Comment by kbrosnan** [comment]
GV have already resolved this issue.

**Comment by Amejia481** [comment]
Thanks for the update, is there a ticket that I could link to Sentry?

**Comment by Amejia481** [comment]
Found it thanks https://bugzilla.mozilla.org/show_bug.cgi?id=1689364
