### ISSUE TITLE
FNX-5275 ⁃ [Bug] "Switch" to private tab does not update to private toolbar

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#1836]
## Steps to reproduce
* Visit a page
* Long press a link
* "Open in new private tab"
* Press "Switch" in snackbar

### Expected behavior
Toolbar UI turns to private browsing: grey & private tab count used

### Actual behavior
Toolbar UI stays in normal browsing: white & normal tab count used

### Device information
* Android device: pixel 2
* Fenix version: 1.0.1916

**Comment by ekager** [comment]
Related to AC work to pass in our own style/actions: https://github.com/mozilla-mobile/android-components/issues/2811

**Comment by jonalmeida** [comment]
I don't believe this should be a blocked on a-c but https://github.com/mozilla-mobile/fenix/issues/1627 since session selection was broken here. Theming based on the selected session should be straight-forward then.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 4/29 build.
