### ISSUE TITLE
[Bug] No tracking protection icon shown after clicking on "Report site issue"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18364]
## Steps to reproduce
1. Open a website.
2. From the page's three-dot menu tap on "Report site issue".
3. Observe the protection icon of the newly opened page webcompat.com/issues/new.

### Expected behavior
The newly opened page is loaded without issues. Tracking protection icon showing in toolbar.

### Actual behavior
The newly opened page has no tracking protection icon in toolbar (empty space).

### Device information
* Device vendor / model and Android version: HTC 10 (Android 8)
* Firefox for Android version: 3/8 Nightly debug build
* Please see #12848

**Comment by abodea** [comment]
This issue is reproducible on the **Beta 87.0.0-beta.4** build with **Samsung Galaxy Tab A6 (Android 5.1.1).**

**Comment by codrut-topliceanu** [comment]
@softvision-miralobontiu @abodea  Does this seem like a device or site specific issue?

I was unable to reproduce the issue using current Nightly, current beta or Master branch on:
Pixel 4 (Android 11)
Pixel 3xl (Android 10)

or using current Master branch on: 
One Plus A6 (Android 9)
Motorola E4 (Android 7)
Samsung Galaxy Note 3 (Android 5)

Only tested with google.com and wikipedia.org though.
