### ISSUE TITLE
Redesign the menu more like this and move it down with 12 pixels

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#18370]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I don't really like the menu now is it now. Too big and need to scroll for some buttons. And some button I don't see why appears like "Synchronised tabs", I don't use it that frequently or none.
![Screenshot_20210308-155032](https://user-images.githubusercontent.com/48178307/110347994-d9c52800-8039-11eb-9cb2-f6a7820f8837.png)

**Comment by cadeyrn** [comment]
A menu redesign is already in progress. You can follow #17796 and dependencies.

**Comment by AndRo-Marian** [comment]
I don't like it anyway. Already found that.

**Comment by kbrosnan** [comment]
There are designs for an updated 3 dot menu already as Cadeyrn mentions. A more compact menu was evaluated by the UX team. Closing.
