### ISSUE TITLE
media notification shows website title and URL on lock screen when hide sensitive notifications is set

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#18371]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
* Configure Android to hide sensitive notifications on the lock screen
* Visit a website that generates a media notification
* lock your phone
* inspect the lock screen information

![Screenshot_20210308-090506](https://user-images.githubusercontent.com/250273/110355758-6cd87080-7fee-11eb-9ab9-1727b60d95ac.png)

### Expected behavior
* Website title and URL is not disclosed when hide sensitive notifications is set

### Actual behavior
* Information about what websites the user is viewing is disclosed

![Screenshot_20210306-085332](https://user-images.githubusercontent.com/250273/110355703-60ecae80-7fee-11eb-931b-2c5be49da351.png)

### Device information

* Device vendor / model and Android version:  Pixel 3 Android 11
* Firefox for Android version: current nightly

**Comment by mcarare** [comment]
@kbrosnan Should we show just the icon and title on the lock screen, or not show the notification at all?

**Comment by kbrosnan** [comment]
![Screenshot_20210309-104154](https://user-images.githubusercontent.com/250273/110564495-c4b3cc00-8101-11eb-9ecd-362481e8ca75.png)
![Screenshot_20210309-104121](https://user-images.githubusercontent.com/250273/110564499-c7162600-8101-11eb-8459-dd0d6abc2f30.png)

This is how some notifications are handled. I did notice that Chrome discloses the website playing back same as Firefox. Might be related to the media style notification as the OS believes that it is not private info?

**Comment by mcarare** [comment]
@kbrosnan: No,  we explicitly set in the notification channel what level of privacy the notification has. Maybe we can do something different depending on the mode we are in? Private or normal?
