### ISSUE TITLE
Explicitly specify extractNativeLibs attribute in ApplicationManifest.xml

### ISSUE THREAD

**Issue by dblohm7** [mozilla-mobile/fenix#18381]
The [documentation](https://developer.android.com/studio/releases/gradle-plugin#3-6-0-behavior) for version 3.6.0 of the Android Gradle Plugin states the following:

```
When you build your app, the plugin now sets extractNativeLibs to "false" by default.
```

For Android Gradle Plugin versions prior to 3.6.0, the default value was `true`.

Based on what I see in the [commit](https://github.com/mozilla-mobile/fenix/commit/aeb0205ea5f1e618ad75d5d82badb7baad986fac) that upgraded the plugin from 3.5.0 to 3.6.4, and thus triggering this change, no modifications were made to `AndroidManifest.xml` to account for this revised default value of `extractNativeLibs`.

Could the Fenix team please (re-)evaluate which value you would like `extractNativeLibs` to take, and explicitly set it in the manifest?

**Comment by mcomella** [comment]
This was previously investigated by the perf team in https://github.com/mozilla-mobile/fenix/issues/15770

**Comment by dblohm7** [comment]
Well we never had our APK set up to build correctly when it is set to `false`, so I don't believe that it is appropriate to set it to that value without fixing the APK.

**Comment by mcomella** [comment]
PR in https://github.com/mozilla-mobile/fenix/pull/18442

**Comment by mcomella** [comment]
> Well we never had our APK set up to build correctly when it is set to `false`,

@dblohm7 What do we need to do to set up the APK to build correctly?

**Comment by MarcLeclair** [comment]
I'm waiting on Perftest to work on my computer to be able to finalize my timing measurement.

**Comment by dblohm7** [comment]
> 
> 
> > Well we never had our APK set up to build correctly when it is set to `false`,
> 
> @dblohm7 What do we need to do to set up the APK to build correctly?

Two things:
* Shared libraries need to be stored, not deflated;
* Shared libraries need to be page-aligned in the apk.

**Comment by mcomella** [comment]
This is blocking a top crasher – https://bugzilla.mozilla.org/show_bug.cgi?id=1637597 – so we're going to land it and evaluate the perf impact later in https://github.com/mozilla-mobile/fenix/issues/18688
