### ISSUE TITLE
[UX] removing the bookmarks from hard to reach region

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla-mobile/fenix#18384]
### What is the user problem or growth opportunity you want to see solved?
On choosing the top search bar, the items are listed in [hard to reach area](https://www.smashingmagazine.com/2016/09/the-thumb-zone-designing-for-mobile-users/).
![image](https://user-images.githubusercontent.com/48223671/110430397-53a8f000-80d2-11eb-8409-9bc9b780c5c6.png)

On analysis of 1,333 observations of smartphones in use, the researcher found about 75% of people rely on their thumb and 49% rely on a one-handed grip to get things done on their phones. On large screens (over four inches) those kinds of behaviors can stretch people’s thumbs well past their comfort zone as they try to reach controls positioned at the top of their device.
![image](https://user-images.githubusercontent.com/48223671/110430842-f7929b80-80d2-11eb-919c-ce90dfe0d72d.png)

### How do you know that this problem exists today? Why is this important?
Suggestion :
1. Arrange the logo in a bigger font so that the bookmarks shift a bit lower.
2. Add what's new rectangle bar to push them a little lower

**Comment by LaurentiuApahideanSV** [comment]
The issue was already discussed here: https://github.com/mozilla-mobile/fenix/issues/15822. I will mark this issue as closed as it will be handled there.
