### ISSUE TITLE
Allow for core components to be overriden in ui tests

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#18385]
Following https://github.com/mozilla-mobile/fenix/issues/18041 and https://github.com/mozilla-mobile/fenix/pull/18151#discussion_r586036123 it was seen that when running instrumented tests we need an easy way to replace the dependencies used in production with ones specifically tailored for our ui tests needs.

For this we'd probably need to:
- leverage a custom `AndroidJUnitRunner` that would use a new `FenixTestApplication` that would easily provide a custom `Components` implementation.
A solution based on this should offer a way to dynamically choose the Application / runner so that part of the tests would be run with the dev components and part of the tests would be run with the custom ui tests components.
- or have overriden components in `androidTest` package similar to the already existing [`AppRequestInterceptor`](https://github.com/mozilla-mobile/fenix/blob/3722033a5cc7498c0d99854840f997d9d7dfd6e1/app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt).
Again, we would need a way to ensure part of the tests would be run with the dev components and part of the tests would be run with the custom ui tests components.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9986)

**Comment by sv-ohorvath** [comment]
Let's keep it in case someone has the bandwidth to do this.
