### ISSUE TITLE
FNX-5276 ⁃ Ensure we're regularly testing on low-end devices

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#1838]
I wanted to remind the team to test on low-end devices too, if you're not doing so already!

In particular, I'm concerned about how the device performs when the app is in memory but backgrounded (i.e. open app, load a page, hit home button, do something else). Back in the day, I noticed that Fennec slowed down my entire device (GS5) when the app was backgrounded, probably because Gecko was doing something in the background.

**Comment by vesta0** [comment]
Thanks for the reminder @mcomella ! 

@sv-ohorvath feel free to close once you've seen this.

**Comment by sv-ohorvath** [comment]
Thank you! We're constantly testing on low-end devices and older Androids, we'll keep an eye on issues like that.

**Comment by gaby2300** [comment]
Hello!
I test regularly with a Sony Xperia with Android 6.0.1 Would you like me to test/try something in particular?
