### ISSUE TITLE
[Bug] After playing a podcast the device enters in Android Recovery mode (android is crashing) as the android system cannot be loaded

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#18396]
## Steps to reproduce
1. Navigate to https://podcasts.google.com/
2. Tap a podcast from the list (e.g "Stuff you should know").
3. Tap to play the podcast.
4. Observe behavior.
### Expected behavior
The podcast plays without problems.
### Actual behavior

The device screen is locked and some weird flashes are displayed.
### Device information

* Device vendor **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 3/9.**

Note that I was not able to reproduce this issue on the Google Chrome or the Google Podcast app using the same device.
Might be related to https://github.com/mozilla-mobile/fenix/issues/18394.

https://user-images.githubusercontent.com/42831109/110494195-06417880-80fc-11eb-8600-05aae7402b4f.mp4

**Comment by abodea** [comment]
Here is the logcat since I started the app until Android System crashed.
[logcat1.txt](https://github.com/mozilla-mobile/fenix/files/6109617/logcat1.txt)

**Comment by mcarare** [comment]
I see the same `IllegalArgumentException`("The given region must intersect with the Bitmap's dimensions.").
So this is the same as https://github.com/mozilla-mobile/fenix/issues/18394

**Comment by rocketsroger** [comment]
Same as https://github.com/mozilla-mobile/fenix/issues/18400

**Comment by rocketsroger** [comment]
Fix merged.  I'll update once the fix made it into nightly.

**Comment by codrut-topliceanu** [comment]
@rocketsroger 
The cause is an empty, but not null, bitmap in the `NotificationData.largeIcon` from `MediaNotification.buildNotification()`.
I have a patch almost ready for this. It's just a small fix where I check the `data.largeIcon` content in AC's `MediaNotification.kt` that fixes the issue. May I still put up a PR for that?

PS: I also need to make a follow up issue for the missing bitmap problem, as we should have received a bitmap for the notification.

**Comment by codrut-topliceanu** [comment]
Closed associated AC issue and PR as this issue should be fixed by https://github.com/mozilla-mobile/android-components/issues/9859

**Comment by rocketsroger** [comment]
Confirmed from my testing this is fixed in Nightly.  Please verify

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 3/16 with Google Pixel 4 XL (11).
Note that I've played more than 10 podcasts and I didn`t encounter any issues.
