### ISSUE TITLE
[Bug]Text selection menu is not dismissed after the page is in reading mode

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18395]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open an page with a lot of content.
2. Perform a long tap on a word in order to bring up the selection menu.
3. From the URL bar, tap on the reading icon.

### Expected behavior
The text selection menu is dismissed and the page enter in reading mode.

### Actual behavior
The text selection menu is still displayed and no word is selected. 

### Device information
* Device vendor / model and Android version: Xiaomi Redmi Note 8T (Android 9), LG G7 Fit (Android 8.1).
* Firefox for Android version: 86.1.1, 87-beta.4, Nightly 3/9.

**Comment by VitalyVPinchuk** [comment]
Hello all!
Could I try to fix the issue?

**Comment by VitalyVPinchuk** [comment]
Hi @sflorean @Mugurell 
Can [this](https://github.com/VitalyVPinchuk/fenix/commit/38af8195dab739ec702ecfb7c71a19cc00cc3db0) be a solution?

**Comment by Mugurell** [comment]
Thank you @VitalyVPinchuk for looking into this.
That indeed seems like the approach needed.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 3/26 with Samsung Galaxy Tab S3 (Android 8).
I will remove the qa:needed label and close this issue.
