### ISSUE TITLE
[Bug] App crashes when trying to play a podcast

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#18394]
## Steps to reproduce
1. Navigate to https://podcasts.google.com/
2. Tap a podcast from the list (e.g "Stuff you should know").
3. Tap to play the podcast.
4. Observe behavior.

### Expected behavior
The podcast plays.

### Actual behavior
The podcast plays for a few seconds and then the browser crashes.

### Device information

* Device vendor / model and Android version: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density), OnePlus 6 (Android 10) - 2280 ×1080 pixels, 19:9 ratio (~402 ppi density)
* Firefox for Android version: Firefox Nightly 210308 (🦎 88.0a1-20210302034602)

Crash report: https://crash-stats.mozilla.org/report/index/86741731-f409-4486-b7f8-ac3460210309

### Note:
1. This was previously reported here: https://github.com/webcompat/web-bugs/issues/67977
2. This might be related to https://github.com/mozilla-mobile/fenix/issues/17848
3. Reproducible: 10/10
 
![PlayPodcastCrash](https://user-images.githubusercontent.com/12184325/110474953-f2404b80-80e8-11eb-948e-eedf44c7e85f.gif)

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Nightly 3/8, Beta 87.0.0-beta.4 from 3/8 and Release 86.1.1 from 2/23 with Motorola Moto G6 (Android 8).

**Comment by rocketsroger** [comment]
Same issue as https://github.com/mozilla-mobile/fenix/issues/18400

**Comment by rocketsroger** [comment]
Fix merged.  I'll update once the fix made it into nightly.

**Comment by rocketsroger** [comment]
Confirmed from my testing this is fixed in Nightly. Please verify

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 3/15 with Motorola Moto G6 (Android 8).
I will remove the qa:needed label and close this issue.

**Comment by softvision-oana-arbuzov** [comment]
I can confirm this, I can no longer reproduce the crash and the podcast plays.
![image](https://user-images.githubusercontent.com/12184325/111309086-29bc7400-8664-11eb-8534-eef9ec147bcc.png)

**Tested with:**
Browser / Version: Firefox Nightly 210315 (🦎 88.0a1-20210313094300)
Operating System: Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density), Google Pixel 5 (Android 11) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density)
