### ISSUE TITLE
FNX-5277 ⁃ [UX] Search

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#184]
**User Story:**
As a user I want to quickly find things on the web.

**Current Design Status:**

* In Good Shape
* Foundational Design Done
* Needs more details around:
* Result priority by type of result
* Exact display of type of result

**Design Priority:**
P1

**Mockups:**
https://mozilla.invisionapp.com/share/VXQ27H3G5ZQ#/341827842_Search

**Comment by pocmo** [comment]
From Slack:
* I'd be interested in seeing how the awesome bar will looks like when displaying "booksmarks" or "open tabs".
* Search suggestions: One row with "chips" (like Fennec) vs. One row per suggestion (mocks) -> I'll modify the component to allow "one row per suggestion" but I wonder if that uses too much space?
* In the mock we mix search suggestions and history (as opposed to having a strict order) - We need to define how this should work. In all other our products search suggestions seem to be always at the top.

**Comment by Cheap-Skate** [comment]
>     * Search suggestions: One row with "chips" (like Fennec) vs. One row per suggestion (mocks) -> I'll modify the component to allow "one row per suggestion" but I wonder if that uses too much space?

I for one love the "chips" and would be sad to see them go, I find them highly space efficient without being intimidating. I filed #479.

**Comment by Cheap-Skate** [comment]
Just a suggestion, the Google under each search suggestion is redundant (already have a G icon to the left) so could that be ditched and the search suggestions squashed up a bit, there's an awful awful lot of wasted space at the moment. Perhaps the spacing contrast between search suggestions "above the line" and history stuff "below the line" might even be a positive thing.


eg
![image 15-02-2019 at 18 09](https://user-images.githubusercontent.com/40568887/52875744-fd645f80-314c-11e9-8755-e5292d8ef17d.jpg)

**Comment by lime124** [comment]
Several issues Verdi filed on the search experience. Pasting them here so we can keep track.

https://github.com/mozilla-mobile/fenix/issues/1196
https://github.com/mozilla-mobile/fenix/issues/1197
https://github.com/mozilla-mobile/fenix/issues/1198
https://github.com/mozilla-mobile/fenix/issues/1204
https://github.com/mozilla-mobile/fenix/issues/1205
https://github.com/mozilla-mobile/fenix/issues/1207
https://github.com/mozilla-mobile/fenix/issues/1209
https://github.com/mozilla-mobile/fenix/issues/1211
https://github.com/mozilla-mobile/fenix/issues/733
https://github.com/mozilla-mobile/fenix/issues/1187
https://github.com/mozilla-mobile/fenix/issues/1161

**Comment by vesta0** [comment]
@topotropic @mheubusch can we close this since all the MVP user stories have been completed?

**Comment by vesta0** [comment]
@mheubusch let me know if we can close this UX meta.
