### ISSUE TITLE
Disabling Javascript in about:config resets on its own [Bug]

### ISSUE THREAD

**Issue by Imerion** [mozilla-mobile/fenix#18406]
I want to disable Javascript. Most pages I use work great without it and it greatly speeds up navigation and rendering while avoiding trackers and similar. It can also be useful for debugging and testing. This can be done in about:config. Problem is that after a few hours the option seems to reset on its own. No idea why this happens, but it seems like a bug.

## Steps to reproduce
Go to about:config and set "javascript.enabled" to "false" .

### Expected behavior
Javascript will stay disabled until flag has been set to "true" manually by user.

### Actual behavior
Flag resets to "true" on its own after a short while.

### Device
* Device vendor / model and Android version: Blackberry KeyONE, Android 8.1
* Firefox for Android version: 87.0.0 Beta 4

**Comment by kbrosnan** [comment]
about:config cannot change prefs that are used by Geckoview. This is as designed.
