### ISSUE TITLE
Search widget is broken on Android 11

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#18405]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
* Using an Android 11 device
* Add the search Widget to the home screen

### Expected behavior
* Search widget is functional

### Actual behavior
* `Problem loading widget`

Looks to be from https://github.com/mozilla-mobile/fenix/commit/0e8dc6164d8d11bc5267e31c3e4f8759054f5828 / https://github.com/mozilla-mobile/fenix/pull/17809

### Device information

* Device vendor / model and Android version: Pixel 3 and 2XL
* Firefox for Android version: Current Nightly, Beta 87 is unaffected

**Comment by mcarare** [comment]
Tested this on the latest master and latest play store Nightly(210309) and the widget works. Tested on Pixel 4 with Android 11. 

@kbrosnan On what Nightly version did you test this?

**Comment by codrut-topliceanu** [comment]
I was also unable to reproduce this on latest Nightly on:
Pixel 4 (Android 11)
Pixel 3 (Android 10)
But I haven't tested on any other devices.

**Comment by kbrosnan** [comment]
I'm not sure what was going on. I had it break on two devices. Both allow me to add the widget and have it load properly now. Lets close this and I can reopen if I get better data.
