### ISSUE TITLE
[Bug] Firefox doesn't direct to ms teams app

### ISSUE THREAD

**Issue by GokdenizK** [mozilla-mobile/fenix#18417]
Firefox doesn't open ms teams app when clicked on a meeting link.

Pertinent recording: https://streamable.com/yyx52q

How it is supposed to work: https://streamable.com/5vf6jr

## Steps to reproduce
Clicking on a meeting link

### Expected behavior
I expect it to open ms teams app.

### Actual behavior
It opens the meeting link, and join meeting button also does not work. 
### Device information
Samsung galaxy j400
Android 10
Firefox 86.1.1

**Comment by s-ankur** [comment]
In settings, try to turn on the "Open links in apps" setting

**Comment by GokdenizK** [comment]
> In settings, try to turn on the "Open links in apps" setting

This helped, thanks. But I wish ff asked me to whether I want to open it in app by default. Otherwise, the situtation may be perplexing.
