### ISSUE TITLE
[Bug] Edit bookmark dialog does allows pasting of rich text

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1841]
## Steps to reproduce
* similar to #1833 but for the Edit Bookmarks dialog
* copy some rich text and paste it into the bookmarks dialog

### Expected behavior
* Plain text is pasted

### Actual behavior
* Rich text is pasted
* Formatting is removed when the bookmark is saved

### Device information
* Android device: Nexus 10 / Pixel 3
* Fenix version: April 19th

**Comment by iadeelzafar** [comment]
@kbrosnan Thanks for opening the ticket. I'm working on this.

**Comment by iadeelzafar** [comment]
Due to some other commitments, I'm unable to give this the time it requires. So, if anyone else wants to work on this, please go ahead.

**Comment by eliserichards** [comment]
This may need to be done on saved logins editing as well.
