### ISSUE TITLE
Add icon to tracking protections similar to desktop version

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#18418]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Various tracking protection items must show the icon similar to desktop version

### How do you know that this problem exists today? Why is this important?
Currently it is showing plain text--
Tracking content
Social media trackers
Etc
But no icon

### Who will benefit from it?
Users who need consistency in UI

**Android**
![Screenshot_20210310-152142566 (1)](https://user-images.githubusercontent.com/58127841/110610972-c4283d80-81b4-11eb-990a-483694db74ca.jpg)

**Desktop**
![Screenshot_20210310-152318809 (1)](https://user-images.githubusercontent.com/58127841/110610862-a78c0580-81b4-11eb-9436-70138e9ab12b.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10007)

**Comment by abodea** [comment]
Thank you for this report! 
I checked and this behavior is on RC, Beta, and the latest Nightly.

**Comment by neha-b2001** [comment]
Hello, is this issue open for assignment? If yes, could I work on adding the requisite icons?

**Comment by Amejia481** [comment]
@neha-b2001 thanks for interesting in this issue, as this is feature request the UX team has to review it first.

**Comment by neha-b2001** [comment]
> @neha-b2001 thanks for interesting in this issue, as this is feature request the UX team has to review it first.

Oh, okay.

**Comment by Amejia481** [comment]
There are other good issue that you could be interested  https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by neha-b2001** [comment]
@Amejia481 Thanks, I'll definitely look into these  :+1:

**Comment by Amejia481** [comment]
In that case, if it's been a long time without signs of active work (pull request or comments) ask the person to confirm.

**Comment by neha-b2001** [comment]
> In that case, if it's been a long time without signs of active work (pull request or comments) ask the person to confirm.

Okay, thanks 👍

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807561

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
