### ISSUE TITLE
[Bug] Keyboard does not show when focusing a html input field

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#18416]
## Steps to reproduce
- Access wikipedia.org
- tap the search box

### Expected behavior
Keyboard should appear to allow entering search terms

### Actual behavior
Keyboard does not appear. User cannot enter text

### Device information

* Device vendor / model and Android version: 
   - On Fenix: Reproduceable on Pixel 3 with Android 11, not reproduceable on a Samsung S7 with Android 8.
   - On GVE: Not reproduceable on the above device.
* Firefox for Android version: Issue started appearing after using `GV 88.0.20210303094110`

Based on the above conditions needed to reproduce this it seems to be a Fenix/AC issue somehow tied to the GV version.
As a quick fix we should probably revert the GV used to `88.0.20210302034602` (used up until today's Nightly which I confirmed "fixes" the issue).

**Comment by Mugurell** [comment]
I can reproduce this also on a Samsung s9 with Android 10 so this is not an `Android 11` specific issue.

**Comment by sv-ohorvath** [comment]
I saw this older bug recently: https://github.com/mozilla-mobile/fenix/issues/15526 which seems to be the same, probably not reproducing so often?

**Comment by mcarare** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/9855.

**Comment by lobontiumira** [comment]
Verified as fixed on the 3/15 Nightly build, with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).
