### ISSUE TITLE
[Bug] the first letter of type email inputs has auto-capitalization

### ISSUE THREAD

**Issue by benoapof** [mozilla-mobile/fenix#18419]
It's disturbing...
I try setting the attribute autocapitalize="none", but no effect.

To reproduce :
- Try filling any email type input...
- I expect the email to be in lowercase
- The first letter will uppercase

* Redmi Note 9 Pro / Android version: 10
* Firefox for Android version: 86.1.1

**Comment by abodea** [comment]
Thank you for this report @benoapof!
I tried to reproduce this issue on the latest Nightly 3/10 with Google Pixel 4 XL (11) but I couldn't.
Note that when I tried to fill the email on `facebook` `twitter` or any other website the first letter was in lowercase.
@benoapof can you please let me know from where you changed the auto-capitalize to none? 
Note that I turned it off from the android device settings and I had no issues.

**Comment by benoapof** [comment]
Hello !
When I try on Facebook I have the same issue, the first letter was uppercase, on twitter it's the same when I try to create an account by email...
It happen only on type email inputs.
I try to add the autocapitalize="none" attribute in the html code.

**Comment by kbrosnan** [comment]
@makotokato do we have a bug for this already in Bugzilla?

**Comment by makotokato** [comment]
We don't ship `autocapitalize` attribute on release channel yet (https://bugzilla.mozilla.org/show_bug.cgi?id=1692007). It is Nightly only now.

**Comment by benoapof** [comment]
The problem seem to be resolved now.
The first letter of email fields is no longer capitalized...
Last tests with Firefox 92.1.1

**Comment by makotokato** [comment]
> The problem seem to be resolved now.
> The first letter of email fields is no longer capitalized...
> Last tests with Firefox 92.1.1

It is https://bugzilla.mozilla.org/show_bug.cgi?id=1711626 (This is fixed by Firefox 91).
