### ISSUE TITLE
[Bug]cannot download from Dropbox with nighlty 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#18428]
with latest nightly I m no longer able to download from Dropbox example link :
https://www.dropbox.com/s/7j58vurja7vm4hj/Tasker.29.apk?dl=0

**Comment by Amejia481** [comment]
I wasn't able to reproduce on pixel 3 with Android, would you mind sharing some more details about your device and Firefox version you can find this information following [these steps](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#retrieving-crash-reports-from-the-application).

**Comment by clientenq** [comment]
Cant reproduce on nightly. Download available and downloading.

**Comment by sflorean** [comment]
Tested on latest Nightly with LG G7 (Android 8.1) and Samsung Note 10 (Android 11) and couldn't reproduce the issue. 
@ale82to could you please tell us the following:
- device model & Android version
- did you have some extra steps, permissions blocked?
