### ISSUE TITLE
[Bug] Colors are wrong with gfx.webrender.all on Android (PowerVR GPU)

### ISSUE THREAD

**Issue by ArmsOfSorrow** [mozilla-mobile/fenix#18424]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- go to about:config
- enable gfx.webrender.all
### Expected behavior
Everything renders the same way it did before.
### Actual behavior
Some colors are wrong, e.g. icons on mobile twitter are orange instead of blue and pictures have weird colors too.
Some sites look alright (github at least), so maybe it's only with certain texture formats? Idk.
### Device information

* Device vendor / model and Android version: Teracube 2e, Android 10
* Firefox for Android version: Nightly 210310 17:03 (Build #2015797899)
AC: 74.0.20210310112134, 7e3b6102a
GV: 88.0a1-20210309094921
AS: 72.1.0

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1697635

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
