### ISSUE TITLE
Analyze start up duration telemetry (discrepancy in onCreate duration telemetry vs. local Moto G5)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18426]
The [`perf_startup_home_activity_on_create` probe](https://glam.telemetry.mozilla.org/fenix/probe/perf_startup_home_activity_on_create/explore?app_id=beta&ref=2021030500&timeHorizon=WEEK) measures `HomeActivity.onCreate` and looks like this:
![image](https://user-images.githubusercontent.com/759372/110691166-a7324100-8199-11eb-8d19-b21a83aa8bb8.png)

The `perf_startup_application_on_create` probe measures the duration of `Application.onCreate`. [The results](https://glam.telemetry.mozilla.org/fenix/probe/perf_startup_application_on_create/explore?app_id=beta&ping_type=*&ref=2021030500&timeHorizon=WEEK) look like this:
![image](https://user-images.githubusercontent.com/759372/110690261-92a17900-8198-11eb-89e0-c0f0de7b3ab9.png)

To sanity check these values, I measured these values locally on the Moto G5 (a slighly less than low-end device for our users) and compared it with the received telemetry (Beta channel 2021-03-05 build). **`Activity.onCreate` seems to match up:** median 191 ms (202ms for first run) on the G5 which puts it comfortably within the 75th percentile (134ms) and the 95th percentile (268ms). However, **`Application.onCreate` does not match up:** median is 432.5ms (521ms for first run) which is towards the bottom within the 50th (414ms) and 75th (696ms).

This comes down to **the key discrepancy:** I'd expect the Moto G5 to be consistent between the probes but it's not. Our intuition for Moto G5 performance seems aligned with `Activity.onCreate` so this makes `Application.onCreate` seem suspicious but it's not necessarily the cause.

A **second discrepancy** is that the distribution of these two probes is different: app.onCreate has a larger gap to the 95th percentile, which has an unexpectedly high duration (1.8s). This also points to app.onCreate as being suspicious.

We should investigate the cause of this discrepancy – for example, perhaps there is a performance issue in `app.onCreate`.

---

We already know there are differences between these probes that could be related:
- App.onCreate and Activity.onCreate aren't called the same number of times and may be called under different conditions (e.g. if the device is low on memory, we're more likely to see App.onCreate called when fenix is opened)
- FenixApplication may be paired with activities besides HomeActivity, which may affect the conditions under which it's called
- `FenixApplication.onCreate` will always lazily initialize the same pieces of code. However, if `HomeActivity.onCreate` is called when the process is already alive, it may run different code based on what components are already lazily initialized (e.g. if HomeActivity was already created) – it may be faster
- `HomeActivity.onCreate` may be able to restore a layout from a bundle, which could speed up performance

Also, I don't know how the data is aggregated (i.e. how does a single user contribute to this visualization?) so that could be another cause of discrepancy.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10014)

**Comment by mcomella** [comment]
I notice `Activity.onCreate`'s violin plot has a bit of bimodality: I wonder if this is related to one of these

> - FenixApplication.onCreate will always lazily initialize the same pieces of code. However, if HomeActivity.onCreate is called when the process is already alive, it may run different code based on what components are already lazily initialized (e.g. if HomeActivity was already created) – it may be faster
> - HomeActivity.onCreate may be able to restore a layout from a bundle, which could speed up performance

**Comment by mcomella** [comment]
Some possible follow-up items to get more data:
- (done) What questions are we trying to answer with this telemetry?
  - How is start up performance overall? Are we fast enough? Is there any bad signal?
    - **This is concerning: FenixApplication.onCreate takes an unexpectedly long time for some clients**
  - Are there any performance cliffs?
- check range for individual clients on these probes: are clients that transmit very long values also transmitting shorter values?
- Add new start up probes to new parts of the lifecycle (e.g. onStart) to compare against onCreate 2x to see which one is more likely valid
- Add new start up probes to this part of the lifecycle to better understand it (e.g. COLD and not COLD probe)

**Comment by mcomella** [comment]
> check range for individual clients on these probes: are clients that transmit very long values also transmitting shorter values?

I did something similar: I filtered the data on the Moto G5 only. Here are my queries:
- [Application.onCreate](https://sql.telemetry.mozilla.org/queries/78712/source?p_org_mozilla_fenix=org_mozilla_firefox#195656): median 560ms (my local G5 was 432.5ms)
- [HomeActivity.onCreate](https://sql.telemetry.mozilla.org/queries/78713/source#195659): median 111ms (mine was 191ms)

Given my median HomeActivity is longer but my median Application is shorter, that continues to point to a discrepancy (as well as the same spread difference we see for all devices): it seems like Application is longer for some start ups than others. **It'd be helpful to identify the conditions when `Application.onCreate` takes longer than usual.**

As a next step, we should add new probes. We should consider adding telemetry for other subsections of start up and perhaps a simple happy path (e.g. COLD start to MAIN) to get more information on what those look like. We should also consider why application.onCreate might take longer or measure subsections of it.

**Comment by mcomella** [comment]
I compared this discrepancy with `geckoview_startup_runtime`:
- `geckoview_startup_runtime` has a similar distribution to both probes – perhaps sits somewhere between them for how far the 95th % is separated
- median on Beta is 1.3s
- median on Beta for Moto G5 is 1.6s
- local runs on moto G5 are [891, 905, 890] (which is between 25%-50% for all devices and 5%-25% for Moto G5)

This implies
- maybe the general distribution we see in `FenixApplication.onCreate` is expected
- `FenixApplication.onCreate` not running close to the median locally implies similar behavior to GV init
  - ^ Maybe the root cause of that issue is GV init
- geckoview init usually takes longer to start up than I'm seeing locally – perhaps there are periodic jobs that run on start up or it takes longer with an older profile.

**Comment by mcomella** [comment]
Looking at the GPlay data for app start up (which includes all start ups, not just MAIN or VIEW), we get a median of 2125-2250ms (closer to the higher end) for Beta over the past 30 days.

Locally, I get 1246 median for MAIN and 1618 for VIEW for time to first frame (which I believe is what Android measures). Naturally, user devices have more going on on them than my device so it's reasonable that I'd be below the median. However, it's unclear what the actual difference should be.

**Comment by mcomella** [comment]
I've been having trouble keeping track of all the questions this analysis is created so I created a doc to track them: https://docs.google.com/document/d/1EtEb8HGkGFEb2b5rvNiy5fkmP2u7ww8_U5eF2QYgUIw/edit#

**Comment by mcomella** [comment]
I opened a PR https://github.com/mozilla-mobile/fenix/pull/18525 to add subsection measurements to `application_on_create` so we can better understand the behavior of that method.

As I mention above, we may additionally want to:
- Add additional probes throughout start up to understand a broader part of it and compare back to these metrics
- Add a probe for a simple version of startup – e.g. COLD MAIN – as it will be more useful to analyze than the previous one we implemented because we can be more confident the implementation is correct
  - Maybe one probe using `start/stop` and one probe using `process init time` & `set`
- Add a probe for `application_on_create` that is filtered for some condition that may be challenging to do at query time (e.g. maybe profile age); **we should probably identify probable causes first though**

And we may also wish to write a query for:
- Are clients that transmit very long values also transmitting shorter values?

**Comment by mcomella** [comment]
Triage: this is important but I've been spending a lot of time not directly improving the product. Let's do that first and then we can work on this.

**Comment by mcomella** [comment]
I wonder if our change to include the start up cache in our `./backfill.py` measurements will have affected this.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807319

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
