### ISSUE TITLE
Need option to prevent Firefox from starting at booting

### ISSUE THREAD

**Issue by bege10** [mozilla-mobile/fenix#18422]
Please, add option to prevent Firefox from starting when phone has booted.

### What is the user problem or growth opportunity you want to see solved?
Firefox starts when the phone has booted. I don't want nor need this. It is not even possible to stop this on a rooted phone by deactivating the BOOT_COMPLETED receiver because Firefox reactivates that with every start. This behavior started with the new Firefox for Android.

### How do you know that this problem exists today? Why is this important?
I use an ungoogled phone and expect control over what the apps are doing.

### Who will benefit from it?
Everybody who wants full control over the installed apps and/or has a slow phone.

**Comment by Mugurell** [comment]
May I ask how do you verify Firefox is starting at boot?
As you can see here https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/AndroidManifest.xml we are not interested in any away about when the boot is completed.

**Comment by bege10** [comment]
- Firefox is in task managers on my rooted phone right after booting
- BOOT_COMPLETED receiver is activated in app permission manager (3C Toolbox and other tools).
  - If I deactivate it and reboot the phone Fx is not in the task manager.
  - If I start Fx and close it the receiver is activated again, at next reboot Fx is back in the task manager.
![Screenshot_20210311-144221_3C_All-in-One_Toolbox](https://user-images.githubusercontent.com/1184237/110797017-ebe0d980-8278-11eb-8892-b6f721eb2b4e.png)

**Comment by Mugurell** [comment]
Thank you!
Seems like the `BOOT_COMPLETED` receiver [is added by WorkManager](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:work/workmanager/src/main/AndroidManifest.xml;l=103-114), a library Fenix uses for background work and based on [it's description](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:work/workmanager/src/main/java/androidx/work/impl/background/systemalarm/RescheduleReceiver.java;l=30?q=RescheduleReceiver) it is something that may actually be useful.
It's also seen that is is by default disabled and the receiver seems like something we would actually want - it's used with a cache mechanism for the current work to ensure it will always complete, even in the case of a device restart.
It's only enabled [if needed](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:work/workmanager/src/main/java/androidx/work/impl/utils/EnqueueRunnable.java;l=82-101), and automatically disabled again [if not needed anymore](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:work/workmanager/src/main/java/androidx/work/impl/WorkerWrapper.java;l=434-442).
So to really disable it (and be ok with potential loss of app functionality) we would have to remove it from the merged manifest but this would mean removing it for all users.

Based on this, to not break app functionality (current or future) for many I think this is not actionable.
Asking @pocmo for a second opinion.

**Comment by pocmo** [comment]
I have to agree with @Mugurell. We are using `WorkManager`, as many other Android apps, and this is not behavior we have direct influence on - and in some regards is even desirable by us.

Please not that Firefox is not running continuously doing things in the background. In this situation a background task may try to complete if it hasn't been able previously. Those are very short lived (usually seconds or even less) and are not hoarding resources. Meaning: Having this broadcast receiver is a requirement of the work manager library and does not mean we are running an keeping a Firefox in the background at all times.
