### ISSUE TITLE
[Bug] Progress bar indicator doesn't reach the end while the page is loaded

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18423]
## Steps to reproduce
1. Open Fenix and go to cnn.com (or planet.mozilla).
2. Check the progress bar.

### Expected behavior
The progress bar is correctly displayed while the page is loaded.

### Actual behavior
The progress bar stops at 75-80% and then disappears. 

### Device information
* Android device: all
* Fenix version: RC , Beta,  Nightly 3/10.

![20200324_182328](https://user-images.githubusercontent.com/58466444/77451070-6804b780-6db1-11ea-9db6-7333641b7c5a.gif)

Closed issue: #9366.

**Comment by Mugurell** [comment]
This is expected.
The progress bar will be automatically get hidden when the page was 100% loaded so it will never really reach the end.
The progress bar will update with various increments but I see no isue currently.
When loading a big website I see the following progress values corresponding to the percent length of the progress bar:
- 15
- 25
- 25
- 25
- 25
- 55
- 55
- 55
- 80
- 80
- 80
- 100
- 100
- 100
- 100
- 100
