### ISSUE TITLE
[Bug]Browsing data is not synced after using an Android phone back up (without a Firefox account)

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18436]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Install Fenix on a device with Android 11.
2. Do not log into Firefox account. Add some bookmarks and navigate to generate some history.
3. With a new device with Android 11, follow the steps from [Switch from an Android phone](https://support.google.com/android/answer/6193424?hl=en#switch-from-an-android-phone&zippy=%2Cswitch-from-an-android-phone) section.

### Expected behavior
After switching you will see the Fenix app is installed in the new device and you should be able to use the browser without issues, navigate and use other basic functionality and your browser data WILL be synced from the old device, you WILL NOT be logged on your Firefox account.

### Actual behavior
The browser data is not synced.

### Device information
* Device vendor / model and Android version: Pixel 3 (Android 11), Samsung Note 10 (Android 11).
* Firefox for Android version: Fenix 8.1.1, Nightly 3/10.

**Comment by Amejia481** [comment]
https://github.com/mozilla-mobile/fenix/issues/18373#issuecomment-797014226
