### ISSUE TITLE
[Bug]Firefox Account is not saved when using an Android phone back up

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18435]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Install Fenix on a device with Android 11.
2. Log into your Firefox account and wait for bookmarks, history, logins and opened tabs to sync (This account should have previous data like logins, passwords and browser history).
3. With a new device with Android 11, follow the steps on [Switch from an Android phone](https://support.google.com/android/answer/6193424?hl=en#switch-from-an-android-phone&zippy=%2Cswitch-from-an-android-phone) section.

### Expected behavior
After switching, Fenix app is installed in the new device and the browsing, navigation or use of other basic functionalities are done without issues, and the Firefox account is still displayed (user is still logged in).

### Actual behavior
The user is not logged in.
Also, browsing history is not saved even if the user is not logged in with a Firefox account.

### Device information
* Device vendor / model and Android version: Pixel 3 (Android 11), Samsung Note 10 (Android 11).
* Firefox for Android version: Fenix 86.1.1, Nightly 3/10

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/fenix/issues/18373#issuecomment-797014226
