### ISSUE TITLE
[Bug] Tab playing video in landscape orientation, forces whole browser to be locked in landscape

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#18444]
I did this with screen orientation lock set to portrait only in android.

## Steps to reproduce
1. Open some website and play video
2. Hit fullscreen button on video
3. Browser rotates to landscape
4. Switch to another application that has some link
5. Click on link, and choose to open in firefox

### Expected behavior
Link opens in new tab, in portait orientation (as it is a system orientation)

### Actual behavior
Link opens in new tab, but this tab is also locked to landscape, just as the first tab.
See video: https://www.dropbox.com/s/f8n0j2x9dqosxs8/recording_20210311_203930.mp4?dl=0

### Device information

* Device vendor / model and Android version: Galaxy J7 2017 Android 9
* Firefox for Android version: Nightly 210310 17:03 (Build #2015797897), happens on release as well.

**Comment by sflorean** [comment]
I was able to reproduce this issue on latest Nightly 3/31 with Samsung Note 10 (Android 11), following the steps from description.
Note that the custom tab, and also after opening the link in Nightly, the orientation is in landscape, for both cases.
