### ISSUE TITLE
[Bug] Clicking "use precise location" in google search results doesn't work

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#18445]
First install "google search fixer" addon.

## Steps to reproduce
1. Open google.com and search for "weather" (in video you see "pogoda", it means weather in my language)
2. Click "Use precise location"
3. Allow location access

### Expected behavior
Google website should refresh the tab widget with updated location.

### Actual behavior
Most of the time nothing happens, google says it's "updating location". I only sometimes get updated location.
See video: https://www.dropbox.com/s/mfg0hgpyqq2r35s/recording_20210311_204458.mp4?dl=0

I remember that I saw it happen on other websites as well. But strangely online test (https://browserleaks.com/geo) works fine.

### Device information

* Device vendor / model and Android version: Galaxy J7 2017 Android 9
* Firefox for Android version: Nightly 210310 17:03 (Build #2015797897), happens on release as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10027)

**Comment by Mugurell** [comment]
I saw on the same device now situations in which 
- the page was immediately refreshed 
- the page showed an "Updating location" message instead of the "Use precise location" text.
I also see that if remembering the "allow" permisson the page always reloads as expected.

Unsure if the issue is of the app or with the webpage.

**Comment by Mikaka27** [comment]
Before I was also quite sure, that "remembering" permission setting, makes this always work. However notice in the video that I'm doing that, and yet I still get the "updating location..." case. This is shown on the end of video.

**Comment by Mugurell** [comment]
> Before I was also quite sure, that "remembering" permission setting, makes this always work. However notice in the video that I'm doing that, and yet I still get the "updating location..." case. This is shown on the end of video.

At the end of the video I see that the page is stuck at "Updating location" immediately after setting the permission to be always granted.
But if refreshing the page afterwards, do you still see that widget getting stuck at "Updating location"?

**Comment by Mikaka27** [comment]
Hi sorry for late response. I just retried, and after refreshing the page the widget also get's stuck when I hit "update location" button (it seems that button is different when location permission is already given).

For me it seems to always get stuck. Only exception was the first page reload after giving permanent location permission.

**Comment by sflorean** [comment]
I was able to reproduce this issue on latest Nightly build 3/29 and RC build 87.0.0-rc.1 following the steps provided in description, with Samsung Note 10 (Android 11).
