### ISSUE TITLE
[Bug] install_search_widget deeplink doesn't work on Android 6 & 5 devices

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#18454]
## Prerequisites
Identify your User ID

## Steps to reproduce
1. Run `adb shell am start -a android.intent.action.VIEW -d fenix-nightly://install_search_widget\?uid=Your User ID` on a Nightly Build.

### Expected behavior
The system prompt Add Search Widget to Home screen should be displayed

### Actual behavior
Besides launching Fenix nothing else happens

### Device information

* Device vendor / model and Android version: 
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy Tab A6 (Android 5.1.1)

* Firefox for Android version: 
• Nightly 210312
• Beta 87.0.0-beta.5
• RC 86.1.1

**Comment by Mugurell** [comment]
This is expected.
The functionality needed for this is [only available on Android Oreo and up](https://developer.android.com/reference/android/appwidget/AppWidgetManager#requestPinAppWidget(android.content.ComponentName,%20android.os.Bundle,%20android.app.PendingIntent)) for which [we have a check in code](https://github.com/mozilla-mobile/fenix/blob/66ccea4075f72e39f58f912b106fb0d5806fe6f9/app/src/main/java/org/mozilla/fenix/home/intent/DeepLinkIntentProcessor.kt#L113).
