### ISSUE TITLE
[Bug] Permission dialog is shown over the tabs tray

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#18455]
.. if moving fast enough or the website responds slow enough.

Seen while looking at https://github.com/mozilla-mobile/fenix/issues/18445.

## Steps to reproduce
- Click on a page element that would trigger a permission popup
- at roughly the same time tap the tabs counter button to open the tabs tray (I did it just because the "allow" button of the permission dialog is roughly at the same position in screen as the tabs counter)

### Expected behavior
Will leave it to UX to decide.
Should we synchronize these two and make it so that one appearing will dismiss the other maybe?

### Actual behavior
3 possible outcomes:
- only one tap was actioned upon: either the permission popup either the tabs tray will be shown
- the tabs tray will be shown with the permission dialog rendered on top
- the permission dialog would be shown first but then covered by the tabs tray.

https://user-images.githubusercontent.com/11428869/110940138-16956580-833f-11eb-9828-71f3f0717c17.mov

**Comment by Mugurell** [comment]
The same happens with the download dialog.
It's also possible that this dialog would be shown underneath the tabs tray. But when closing the tabs tray users will see it an be able to interact with it.
<img src="https://user-images.githubusercontent.com/11428869/110940567-c8349680-833f-11eb-8358-c76fc8664414.png" width="33%"/>

**Comment by topotropic** [comment]
Thanks! So is it possible to make sure we prevent people from accidentally allowing a permission because they tapped on the multi-task icon at the same time (your case)? And can we render the permission or download dialog behind the tab tray?

**Comment by Mugurell** [comment]
Ohh, interesting.
Didn't thought of that but because of the "Allow" / "Download" dialog buttons being shown where users usually expect other buttons to interact with, since this dialogs may show up even without user action I guess it would be possible for users to intend to click on the tabs counter button but in that fraction of a second another dialog gets shown there.
This is clearly an edgecase though.
Thinking about it now, in the case of these dialogs (for permissions, downloads) being shown without user interaction they could be shown over the tabs tray like shown here.
But currently I don't think there's a way to reoder these and also atm I don't think one component knows about the other to be able to sync whether to be shown or not. I guess it would be possible (the second option) but will require a significant effort.

**Comment by topotropic** [comment]
This sounds familiar 
> I don't think one component knows about the other to be able to sync whether to be shown or not
didn't we discuss this related to a recurring download issue a while ago? 

Sounds like a rare case that people open the tab tray when a bottom permission sheet opens and we can leave it as is. Thoughts?

**Comment by Mugurell** [comment]
Agree.
The root cause can be seen as a general issue that could affect more app features.
And right now all these are more at a theoretical level, being pretty hard to actually encounter IRL.
