### ISSUE TITLE
[Bug] make_default_browser deeplink doesn't work on Android 6 & 5 devices

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#18453]
## Prerequisites
Identify your User ID

## Steps to reproduce
1. Run `adb shell am start -a android.intent.action.VIEW -d fenix-nightly://make_default_browser\?uid=Your User ID` on a Nightly Build.

### Expected behavior
Open "Make Firefox the default browser on Android" Sumo page ❓ as implemeted in [#5898](https://github.com/mozilla-mobile/fenix/issues/5898)

### Actual behavior
Besides launching Fenix nothing else happens

### Device information

* Device vendor / model and Android version: 
• OnePlus A3 (Android 6.0.1)
• Samsung Galaxy Tab A6 (Android 5.1.1)

* Firefox for Android version: 
* • Nightly 210312
• Beta 87.0.0-beta.5
• RC 86.1.1

**Comment by Mugurell** [comment]
We should add an else clause [here](https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/main/java/org/mozilla/fenix/home/intent/DeepLinkIntentProcessor.kt#L89)
to open the app with [this link](https://github.com/mozilla-mobile/fenix/blob/66ccea4075f72e39f58f912b106fb0d5806fe6f9/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt#L462-L465)

**Comment by kershan** [comment]
Hey, I would like to pick this issue up to work if it is still available and needed.

**Comment by Mugurell** [comment]
> Hey, I would like to pick this issue up to work on if it is still available and needed.

That would be awesome! Thank you!

**Comment by lobontiumira** [comment]
Verified as fixed on the 3/30 Nightly build with Samsung Galaxy Tab A6 (Android 5.1.1).
Running adb shell am start -a android.intent.action.VIEW -d fenix-nightly://make_default_browser\?uid= opens the "Make Firefox the default browser on Android" SUMO page.
