### ISSUE TITLE
Share creates a link to the wrong tab [Bug]

### ISSUE THREAD

**Issue by was8309** [mozilla-mobile/fenix#18463]
## Steps to reproduce
open 3rd tab, go to menu, share, choose share-to app, share-to app comes up with link created to the wrong tab

### Expected behavior
share-to app comes up with link created to the correct -  3rd - tab

### Actual behavior
share-to app comes up with link created to the 2nd tab

### Device information
* Device vendor / model and Android version: ?
Moto Z Play Droid, Android 8.0.0
* Firefox for Android version: ? (go to Settings -> About Firefox)
 86.1.1 (Build #2015794881)
AC: 72.0.16, f4aa67a9c
GV: 86.0-20210222142601
AS: 67.2.0

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/17791
