### ISSUE TITLE
Create in-tree tests for search partner deployment

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#18460]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Firefox partners with search providers to provide our users with a selection of search engines, and to generate revenue for sustaining the Mozilla organization.

In order to ensure compliance with our partner contracts, we should institute in tree tests to verify that search engines are deployed to the regions/locales that we expect, and that the correct URLs and search codes are instituted as well.

Such tests are present in our desktop application, but not currently in place for mobile. Setting them up will protect us from violating our partnership agreements, and also save the team from having to perform manual checks.

### How do you know that this problem exists today? Why is this important?
Currently we ask our SoftVision team to perform these checks manually. This increases the possibility for errors in the checks, in addition to making such tests less frequent and more costly.

### Who will benefit from it?
As this relates to revenue generating partnership agreements, these tests will benefit the whole organization.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10034)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807721

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
