### ISSUE TITLE
[Bug] repeated push notifications 

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#18464]
In Fenix nightly the push notification request are repeated after page reloads. Even if request have already been denied.
There is also no other option to deny such push request.
Current client favours website pushing users instead of providing users with sufficient controls to deny pushing.

## Steps to reproduce
Visit page with push notification.
Deny request
Visit other page or site
Revisit or reload page with push notification

### Expected behavior
Push notification do not repeat when already denied.
User option to permanenty deny push notification requests.

### Actual behavior
User choice to deny push request are ignored.

### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by mcarare** [comment]
@clientenq Can you please give an example of a site where this happens? Maybe also post a video? What ETP settings are you using?
I have tried some sites that request to send you push notifications and the request is not repeated after denying it.

**Comment by abodea** [comment]
Tried on the latest Nightly 3/30 with Google Pixel 4 XL (11) but as Mihai said about the request is not repeated after denying it.
