### ISSUE TITLE
Darkreader failing to invert some sites on Nightly 

### ISSUE THREAD

**Issue by matthewarmand** [mozilla-mobile/fenix#18471]
I'm currently running the Nightly build and in the last couple days I've noticed that something seems to have broken the Darkreader extension. I installed Firefox Beta for comparison and the functionality works fine there. The Darkreader versions appear to be the same, so it seems like a Firefox issue. 

Here's a couple screenshots with a side-by-side of Nightly and Beta to illustrate what I'm seeing: in both, Nightly is on top, and Beta is on bottom. You can see that on Nightly the extension is partially inverting certain elements on the page, but not everything it should. 

![Screenshot_20210313-083550](https://user-images.githubusercontent.com/4631191/111031882-be5e7200-83d7-11eb-8851-9e3543f0ce08.png)

And another...
![Screenshot_20210313-083743](https://user-images.githubusercontent.com/4631191/111031888-c5858000-83d7-11eb-8d8a-c21c1e40cffb.png)

Device is a Pixel 3a running Android 11, Security update `5 March 2021`, Build number RQ2A.210305.006. Relevant versions:

| Software     | Nightly          | Beta  |
| ------------- |:-------------:| :-----:|
| Darkreader    | Version 5 Preview (4.9.29) | Version 5 Preview (4.9.29)|
| Firefox      |   Nightly 210312 17:02 (Build #2015798283) AC: 74.0.20210312143156, 5aad02863 GV: 88.0a1-20210312033752 AS: 73.0.1    |   87.0.0-beta.5 (Build #2015798155) AC: 73.0.9, 429280150 GV: 87.0-20210311161514 AS: 71.0.0 |

**Comment by MicroBeast** [comment]
https://github.com/darkreader/darkreader/issues/5182

Seem FF upstream issue?

Try the momentarily about:config workaround mentioned in that issue (until real fix arrive).

m.youtube.com comments section also effected btw. I see that config does work. I turn it off again though, workaround is a workaround, I don't depend on it.

**Comment by kbrosnan** [comment]
Duplicate bz-1697829
