### ISSUE TITLE
[Feature Request] Use a different search engine in Firefox Private mode

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#18479]
Please add this feature to the Fenix (like desktop version):
![Firefox](https://user-images.githubusercontent.com/23485114/111106387-48d6db00-856a-11eb-8ab3-bcab0271a6d2.png)

**Comment by cadeyrn** [comment]
> like desktop version

This feature was never shipped in the desktop Firefox (it has to be enabled by a hidden option).

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/1076
