### ISSUE TITLE
[Bug] firefox on android tablet defaults to mobile useragent. It should default to desktop

### ISSUE THREAD

**Issue by Rashidwi** [mozilla-mobile/fenix#18475]
Firefox for android has the option to display as a desktop site but the default is  mobile. This behavior is incorrect when the device is a tablet and requires setting to desktop for each and every web access. 

## Steps to reproduce
EVERY TIME!
### Expected behavior
The browser should detect the screen size (or the device capability) and use the appropriate user agent setting, or the "desktop site" setting should be a global setting, set once.

### Device information

* Device vendor / model and Android version: ?
Samsung S6 running in Dex mode on Android 10 

* Firefox for Android version: ? (go to Settings -> About Firefox)
86.1.1

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/1848
