### ISSUE TITLE
Open Link in current tab

### ISSUE THREAD

**Issue by KarlM256** [mozilla-mobile/fenix#18473]
Hi,

I understand that you want to emphasize tabs more in the new version of Firefox Android. But I request that you give a settings option to default to opening a bookmark in the current tab. I still prefer to use bookmarks to keep what I want to see from time to time. I find the tabs inconvenient and inconsistent. You could obviously default the setting to work the current way.

Thanks,

Karl

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/13336
