### ISSUE TITLE
Wrong (previous) url when I want to edit or share url from the current page

### ISSUE THREAD

**Issue by lle-git** [mozilla-mobile/fenix#18497]
Hello,

This issue is not systematic...

## Steps to reproduce

Display a page and :
1/ Tap in in the url to edit it
or
2/ Menu/Share/Select a target device

### Expected behavior
1/ The current url is displayed 
2/ The current url is shared on the target device

### Actual behavior
1/ The url is the url of a previous displayed page
2/ The url shared on the target device is the url of a previous displayed page

### Device information

* Device vendor / model and Android version: ? Samsung Galaxy A8, Android 9
* Firefox for Android version: ? Firefox Daylight 86.1.1
 
Thanks !

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/17791
