### ISSUE TITLE
Optimize the order and messages of onboarding cards

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#18494]
This is the Engineering User story for #15372 
## User Story
- As a NEW user, I want to quickly learn about the most interest or useful features, so I know if this browser is the right one for me and how to customize it to fit my needs.

## Acceptance Criteria

- Onboarding cards appear in order of most interesting/useful.
- ONLY highlights unique/useful features that are also actionable
- Highlight what's unique about Firefox
- Copy is clear, precise, and impactful
- FxA sign in/sign up is not presented to me as the most important option

This work will change the strings as well as the order of our onboarding cards. 

### New order:
* Theme picker
* Address bar location picker
* Enhanced Tracking Protection settings
* Sync Firefox between devices
* Privacy notice
* Start browsing call to action

### Removing
* See what's new 
* Private tabs

### String changes
See [Betsy's comment](https://github.com/mozilla-mobile/fenix/issues/15372#issuecomment-713169131)

### UX Spec
[Figma](https://www.figma.com/file/HvCGhaudYuBq3yPgwAWOVO/Onboarding?node-id=0%3A1)

**Comment by lobontiumira** [comment]
Verified as fixed on the 3/26 Nightly build with Samsung Galaxy Note 8 (Android 9):
![light theme](https://user-images.githubusercontent.com/40694158/112635055-0489eb80-8e44-11eb-9edb-58e468947144.png)
![dark theme](https://user-images.githubusercontent.com/40694158/112635087-0fdd1700-8e44-11eb-9a06-4a6a2260b723.png)
