### ISSUE TITLE
FNX-5280 ⁃ [Telemetry] High level summary of libraries used in-app to docs/

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#1849]
Owner: Product Manager

#### Description & Product Manager / Data Scienties User Story
As a user, I want to know what third-party or Mozilla-hosted telemetry is being collected, and why. I also want to be reassured why tools that don't sound like Mozilla tools like "Adjust" or "Leanplum" are being used, and how.

#### Hypothesis
We believe easily findable, transparent docs about what 3rd-party tools Fenix is using will reassure users, or others who are curious about Fenix's data collection policies.

#### What questions will you answer with this data?
Have a single place where users or others can read about the data collection tools we're using.

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
In the past people have been confused or misunderstood what 3rd party data collection tools we use are, so we should put that information in a single place that others can find easily that summarizes our usage of these tools.

### Dependencies (Added by PM and Eng)
None, add to docs/

### Acceptance Criteria (Added by PM)
Summary of what data collection tools are in Fenix, and examples of what some of those pings look like so there is no confusion what is being collected.

* [x] Glean SDK
* [x] Adjust (similar to https://github.com/mozilla-mobile/focus-android/wiki/Adjust-Usage ), copied here: https://github.com/mozilla-mobile/fenix/wiki/Adjust-Usage
* [x] LeanPlum (skeleton in docs/telemetry.md, but a quick explanation that this is used to show campaigns, https://github.com/mozilla-mobile/fenix/issues/981)
* [x] Sentry (similar to https://github.com/mozilla-mobile/focus-android/wiki/Crash-Reporting-with-Sentry )

These could also be added to the [mobile shared docs](https://github.com/mozilla-mobile/shared-docs) and linked to the Fenix docs page.

**Comment by vesta0** [comment]
@bbinto is this a joint product/eng task?

**Comment by bbinto** [comment]
Yes, I've added a Github issue for the Leanplum ask: https://github.com/mozilla-mobile/fenix/issues/981

@lwa-moz - do you want to take on the Adjust SDK ask? I believe we can copy what is written here: https://github.com/mozilla-mobile/focus-android/wiki/Adjust-Usage

**Comment by vesta0** [comment]
@sarentz please review the Fenix Adjust documentation: Adjust page: https://github.com/mozilla-mobile/fenix/wiki/Adjust-Usage

**Comment by vesta0** [comment]
Documented here: https://github.com/mozilla-mobile/fenix/wiki/Data-Practices
