### ISSUE TITLE
[Bug] Vertical grey line appear briefly on opened tabs in tabs tray, in grid view

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18495]
## Steps to reproduce
1. Have the tab view set to grid.
2. Open at least one tab.
3. Go to the tab tray, and switch from normal browsing to private and vice-versa.

### Expected behavior
The opened tabs from the tab tray are displayed without issues, or glitches.

### Actual behavior
All opened tabs, from normal or private browsing, have a vertical line in front of the "X" close button, that is dismissed in a second or so. Please see the attached short video.

### Device information
* Device vendor / model and Android version: Samsung Galaxy Tab A6 (Android 5.1.1)
* Firefox for Android version: Beta 87.0.0-beta.6
* Not reproducible on RC 86.1.1, nor on 3/16 Nightly build
* Not reproducible with google Pixel (Android 10), Motorola Moto G6 (Android 8), Huawei MediaPad M3 (Android 7.0)
 

https://user-images.githubusercontent.com/40694158/111287987-6ed4ac00-864c-11eb-946d-0a511a2ae621.mp4

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the RC 87.0.0-rc1 build with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by sflorean** [comment]
Reproducible also on 88.0.0-beta.3 - LG G7 Fit (Android 8.1).
