### ISSUE TITLE
FNX-5281 ⁃ [UX] Sessions (View & Function)

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#185]
Prototype: 
https://mozilla.invisionapp.com/share/GFQ4EM2CMVN

**Comment by bbinto** [comment]
session creation/deletion
    session retrieval
    session sharing

**Comment by lime124** [comment]
@topotropic to add in some more mockups please!

@colintheshots Can you please take a look at the prototype and mock ups when Nicole adds them? Is this enough for eng to get started? If not, please identify what else need.

I don't believe there are cross team dependencies - please correct me if I'm wrong.

@bbinto this is going to require more iteration and research, we should put this in milestone 1 or 2.

**Comment by bbinto** [comment]
@topotropic sent @shorlander designs to review, should be picked up next week (Monday)

**Comment by shorlander** [comment]
A lot of this is documented elsewhere and in the prototype, but this tries to pull it all together:

![fenix - view - sessions and tabs - 02](https://user-images.githubusercontent.com/684427/52872593-ea389c00-311a-11e9-86e1-ff288f30ebef.png)

**Comment by boek** [comment]
Hey @shorlander @topotropic. The one thing that I still haven't found a good solution for is what we will use for the session descriptions. I think the page titles will be too long, but the domains don't look as good.

**Comment by shorlander** [comment]
> Hey @shorlander @topotropic. The one thing that I still haven't found a good solution for is what we will use for the session descriptions. I think the page titles will be too long, but the domains don't look as good.

Yeah, agreed. I filed a separate issue to dig into that more: https://github.com/mozilla-mobile/fenix/issues/532

**Comment by boek** [comment]
Awesome. I'm going to close this for now then :)

**Comment by colintheshots** [comment]
Concerns:
 - How long do we store sessions? I'm assuming we store them locally only until there's sync for sessions.
- Will we have an infinite scrolling list or only go back so far?
- Will labels show Today, Yesterday, past day of week, x days ago or should it start showing the full ISO local-independent date if more than a week ago?
- It would make the app quite a bit simpler if we added an additional constraint. When the user's been away five minutes, we store the session and return to Home. If the OS closes our app due to memory pressure, we could also store the session and return to Home.
Upside: We won't have as many issues with broken UI due to Save and Restore.
Downside: If the user has an old phone full of broken apps, we may return to the Home screen quite quickly.

**Comment by boek** [comment]
@shorlander couple of questions that I have now that I'm implementing

1. What determines the color of the icon on the left? Do we have a list of all the available colors?
2. What is the difference between a session in the library and an "archived" session?

**Comment by shorlander** [comment]
@colintheshots 

> Concerns:
>
>     * How long do we store sessions? I'm assuming we store them locally only until there's sync for sessions.

We discussed indefinitely, but there are concerns around 1) disk space and 2) usefulness of really old sessions. I suggest we start with a six months for saving auto-generated sessions.

>     * Will we have an infinite scrolling list or only go back so far?

The flow above has one week back on the start screen,  and a button to take you to the sessions list with all of the sessions.

>     * Will labels show Today, Yesterday, past day of week, x days ago or should it start showing the full ISO locale-independent date if more than a week ago? Or do we want to try localizing the dates? Localizing dates can get messy.

Yeah, if we get more than a week back we can switch to full dates. I filed an issue to build more detail around this: https://github.com/mozilla-mobile/fenix/issues/532

>     * It would make the app quite a bit simpler if we added an additional constraint. When the user's been away five minutes, we store the session and return to Home. If the OS closes our app due to memory pressure, we could also store the session and return to Home.

Yes, agree with this

**Comment by shorlander** [comment]
@boek 

> @shorlander couple of questions that I have now that I'm implementing
> 
>     1. What determines the color of the icon on the left? Do we have a list of all the available colors?

Those were just random placeholders. We would like to get a better visually identifiable image: thumbnails, favicon, etc.

>     2. What is the difference between a session in the library and an "archived" session?

Archived sessions are things we wouldn’t delete after a certain time frame.
