### ISSUE TITLE
Show native video controls in context menu, like Fennec

### ISSUE THREAD

**Issue by wh0** [mozilla-mobile/fenix#18508]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Some videos don't show controls when we want to control them: play, pause, seek, etc.

Desktop Firefox has this, and Fennec had this option, where you could long press/right click a video and choose a "Show controls" option to show the controls.

### How do you know that this problem exists today? Why is this important?

From the previous posting of this request https://github.com/mozilla-mobile/fenix/issues/14730:

> ## Steps to reproduce
>
>  1. Navigate to https://www.reddit.com/r/reactiongifs/comments/imfj9f/me_watching_any_magic_trick/
>  2. Tap image
>  3. Long press on video
>
> ### Expected behavior
> 
> "Show Controls" option, like in Fennec:
> 
> ![signal-2020-09-04-104620](https://user-images.githubusercontent.com/152493/92252244-f8384400-ee9b-11ea-8c44-7be734aeef8c.png)
> ### Actual behavior
> 
> No "Show Controls" option.

![Screenshot_20210316-162008](https://user-images.githubusercontent.com/382796/111392366-a6a31a00-8673-11eb-9727-c3cc80d2db7b.png)

### Who will benefit from it?

:shrug: end users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10057)

**Comment by Shaurya-Kalia** [comment]
Yes, the lack of this option should be a regression

**Comment by Shaurya-Kalia** [comment]
Anything to be done of it?

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813895

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
