### ISSUE TITLE
Ensure the Credit card screens cannot be screenshot

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18507]
Note that there is an existing PR with feedback and take aways https://github.com/mozilla-mobile/fenix/pull/18890. Please consider using it.

-----

Secure secure flags so that the windows of the Credit cards screen cannot be screenshotted.

**Comment by clientenq** [comment]
Can you explain how you expect this suggestion to solve your issue? Credit card screens or forms are not standardised and are different per merchant.

**Comment by gabrielluong** [comment]
> Can you explain how you expect this suggestion to solve your issue? Credit card screens or forms are not standardised and are different per merchant.

This wouldn't be related to the 'webview'. This would be about securing the preference screens where we plan to provide autofill and management of stored credit card information.

**Comment by chrishernan** [comment]
Hello. Could I work on this issue if possible?

**Comment by gabrielluong** [comment]
> Hello. Could I work on this issue if possible?

Sure, I would suggest pulling in https://github.com/mozilla-mobile/fenix/pull/18808 in order to be fully complete. You need to enable the "Credit Card" feature by going into "About Firefox" in the Settings and tapping the logo 3 times to see the Secret Settings where we add toggles for our feature flags.

**Comment by chrishernan** [comment]
Will do. Thanks for the tip. I spent an hour trying to figure out where the credit card section was haha.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 5/25.
### Devices used:
- OnePlus 6T (Android 9)
- Pixel 3 XL (Android 9)
