### ISSUE TITLE
Option to open new tabs at the bottom

### ISSUE THREAD

**Issue by iosonoungatto** [mozilla-mobile/fenix#18510]
I just updated to Fenix from the old Firefox for Android and I was still very used to the old behaviour that new tabs are opened at the bottom, as mentioned in #14853. In Desktop version of Firefix, there are 2 flags to control the position of new tabs. However, they are not there in about:config even in the Beta version.

I am not sure we could have some flexibilities in the behaviour of adding new tabs like the Desktop version.

Moreover, I saw many issues of tab sorting like #11376 or #16130. I was wondering if this could be covered if tab sorting would be enabled in the future. Maybe a strict chronogical sorting that discards the tie between the parent and child tabs satisfies my request. Could this be an option?

Sorry to create another issue that is partially related to tab sorting as I think its also related to the behaviour of adding new tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10059)

**Comment by boek** [comment]
Dup of #19231
