### ISSUE TITLE
FNX3-15859 ⁃ [Bug] issue with QR code scanner if Fenix does not yet have camera permission

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1851]
### Steps to reproduce
1. make sure in your Android app permissions that Fenix does not yet have permission to use the camera
1. use the QR code scanner of Fenix

=> A dialog appears to give Fenix the permission to use the camera

1. Give Fenix the permission

### Expected behavior
After giving the permission the QR code scanner should be active.

### Actual behavior
The "Scan" button has a visible "active" state but the QR code scanner is not active. Instead you have to press again the "Scan" button.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 080dadcb7e1cc0aa53c020595505f6f493e4a143

**Comment by colintheshots** [comment]
I've definitely seen this in the past. On some phones, an Activity.recreate() is required to obtain the camera after the permission is granted.

**Comment by colintheshots** [comment]
It looks like the Android Component opens the scanner with the wrong containerViewId if one uses a custom view id.

**Comment by colintheshots** [comment]
My Android Components fix is in review.

**Comment by colintheshots** [comment]
It looks like this was simply the consequence of not passing the permissions result back to the feature. Adding that change now.

**Comment by kbrosnan** [comment]
This is fixed with Colin's work.
