### ISSUE TITLE
Add the possibility to check Cookies on Fenix

### ISSUE THREAD

**Issue by alimkoca** [mozilla-mobile/fenix#18516]
### I think we need to see cookies like laptops or personal computers

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10065)

**Comment by abodea** [comment]
Thank you for adding this.
You can check your cookies using about:debugging while you're device is connected to pc. Check [this ](https://github.com/mozilla-mobile/fenix/issues/13812#issuecomment-700503934)for more information.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807444

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
