### ISSUE TITLE
Re-add FAB button to tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#18515]
Like the original FAB button, we can create a FAB presenter that observes the selected view pager position and updates the icon accordingly.

**Comment by jonalmeida** [comment]
@codrut-topliceanu I saw that you picked this issue up and wanted to add some notes here for implementation:

 - I landed the synced tabs tray item so, we need to FAB to turn into a "sync" button as well when we're on it.
 - I think there will be some difficulty making the FAB listener in a root layout connect to the `SyncedTabsView.Listener.onRefresh` callback that needs to be invoked. What I've done for now, is move that bit to a `SyncedTabsInteractor` but we may need to have `SyncedTabLayout` observe the interactor, so we can daisy-chain those callbacks along with [this PR](https://github.com/mozilla-mobile/android-components/pull/9994) in AC.

**Comment by jonalmeida** [comment]
I think I've been trying too hard to avoid a `Store` with the thought that it was overkill for usage here.

Re-evaluating that now, I think a store would make it for the FAB as well as for multi-select. I've re-opened https://github.com/mozilla-mobile/fenix/issues/17821 and I'm going to land the patch that we worked on there.

For the FAB, that means we can add to the root fragment and have it observe the select pager tab to update the UI.

Sorry about the confusion!

**Comment by codrut-topliceanu** [comment]
Awesome. That makes things easier :)
