### ISSUE TITLE
Re-add menu to tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#18513]
We can use `browser-menu2` to construct the three-dot menu in the tabs tray and create a `MenuInteractor` to handle those actions.

**Comment by jonalmeida** [comment]
@rocketsroger I just remembered that we have synced tabs now, so I'm not sure what three-dot menu should show be when it's focused.

Might be a question for Nicole.

**Comment by rocketsroger** [comment]
> @rocketsroger I just remembered that we have synced tabs now, so I'm not sure what three-dot menu should show be when it's focused.
> 
> Might be a question for Nicole.

That's true.  I'll add the the menu in but start a conversation about what the menu should show in synced tab.
