### ISSUE TITLE
[Bug] Cannot draw mp4/h.264 video to canvas

### ISSUE THREAD

**Issue by bioRex21** [mozilla-mobile/fenix#18532]
## Steps to reproduce

1.- Go to [https://jibjab-dev-fmvr-serverless.s3-us-west-2.amazonaws.com/video-demos/video-to-canvas.html](https://jibjab-dev-fmvr-serverless.s3-us-west-2.amazonaws.com/video-demos/video-to-canvas.html)
2.- Play the video.
3.- Click "Draw to canvas" button.

### Expected behavior
Video frame should be copied to canvas element.

### Actual behavior
An error is thrown in console:
`InvalidStateError: CanvasRenderingContect2D.drawImage: Passed-in image is "broken"`
![Screenshot at Mar 17 09-55-58](https://user-images.githubusercontent.com/11635585/111554801-429c5680-8744-11eb-934d-158c904d2f79.png)

### Additional notes
The issue is not happening when using a different video codec.

### Device information
Samsung Galaxy S7 Edge (Android 8.0.0).
Samsung Galaxy 10 Lite (Android 11).
Oneplus 5 (Android 10).

Firefox for Android version:
86.1.1 (Build #2015794883)
AC: 72.0.16, f4aa67a9c
GV: 86.0-20210222142601
AS: 67.2.0

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1699485

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by boulderwebdev** [comment]
@kbrosnan Could this be reopened? You can use the following sample file

* https://filesamples.com/samples/video/webm/sample_960x540.webm
* archived at https://web.archive.org/web/20210425051803/https://filesamples.com/samples/video/mp4/sample_960x540.mp4

And a reproduction at https://plnkr.co/edit/FMtXjh9n6UTzC2cl

Here's the associated code:

```html
<!doctype html>

<html>
  <head>
    <link rel="stylesheet" href="lib/style.css">
    <script src="lib/script.js"></script>
  </head>

  <body>
    <div class="canvas-wrapper">
      <canvas id="canvas"></canvas>
      <button id="play-pause">Play/Pause</button>
    </div>

    <video controls src="https://web.archive.org/web/20210425051803/https://filesamples.com/samples/video/mp4/sample_960x540.mp4"></video>
  </body>
</html>
```

```css
.canvas-wrapper {
  padding-bottom: 50px;
  display: flex;
  flex-direction:column;
  max-width: 600px;
}
.canvas-wrapper canvas {
  background: green;
  display: block;
  width: 480px;
  height: 270px;
}
.canvas-wrapper button {
  display: block;
  margin: 20px 0;
  padding: 10px;
}
video {
  display: block;
}
```

```js
let video = document.createElement('video')
const src = 'https://web.archive.org/web/20210425051803/https://filesamples.com/samples/video/mp4/sample_960x540.mp4'
let canvas
let ctx

document.addEventListener("DOMContentLoaded", function() { 
  setupVideo()
});

function setupVideo () {
	setupCanvas()
  setupPlayPause()
  setupVideoElm()
}

function setupCanvas() {
	canvas = document.getElementById('canvas')
  const v = 30
  canvas.width = 16*v
  canvas.height = 9*v
  ctx = canvas.getContext('2d')
}

function setupPlayPause () {
	const btn = document.getElementById('play-pause')
  btn.onclick = function () {
    if (video.paused) {video.play()} 
    else { video.pause() }
  }
}

function setupVideoElm () {
  video.onerror = (e) => {
    console.log('error', e)
  }
  video.onloadeddata = () => {
    render()
  }
  video.onplay = () => {
    if (!video.paused) {
      render()
    }
  }
  video.src = src
}

function render () {
  // sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight
  ctx.drawImage(
  	video,
    0, 0, 960, 540,
    0, 0, 480, 270
  )
  if (!video.paused) {
    window.requestAnimationFrame(render)
  }
  
}
```
