### ISSUE TITLE
Re-investigate dependency injection options

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#18539]
It's been a while since we had considered dependency injection options, and now that our codebase is maturing, we can spend some time to see how we want this to grow.

Considerations:
 - Startup performance
 - Testability
 - Complexity
 - Lock-in to a particular framework

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10081)

**Comment by jonalmeida** [comment]
Some pain points I've run into with Synced Tabs and Tabs Tray, is when certain components or custom implementations:
 1.  Need a custom use case to be shared across inflated UIs and constructor injection isn't so easy.
 2. Scoping dependencies to certain parts of the application.

**Comment by jonathanalvares9009** [comment]
@jonalmeida can you elaborate on the issue?

**Comment by pocmo** [comment]
I don't have a very strong opinion here. But if we end up with something we would want to try then maybe Focus or even Reference Browser may be a good test vehicle - before committing to a long-term refactoring of Fenix.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813247

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
