### ISSUE TITLE
[Bug] Cannot convert mp4/h.264 video frame to WebGL texture

### ISSUE THREAD

**Issue by bioRex21** [mozilla-mobile/fenix#18531]
## Steps to reproduce

1.- Go to [https://jibjab-dev-fmvr-serverless.s3-us-west-2.amazonaws.com/video-demos/webgl-demo.html](https://jibjab-dev-fmvr-serverless.s3-us-west-2.amazonaws.com/video-demos/webgl-demo.html)
2.- Play the video.

Or
1.- Go to [http://jeromeetienne.github.io/threex.videotexture/examples/videotexture.html](http://jeromeetienne.github.io/threex.videotexture/examples/videotexture.html)
2.- Play the video.

### Expected behavior
Video should be displayed as texture in rotating cube.

### Actual behavior
Video texture is not applied to cube.

The following is displayed in console:

![Screenshot at Mar 17 16-38-04](https://user-images.githubusercontent.com/11635585/111553012-bd637280-8740-11eb-96f1-a56c1b9dd49d.png)

### Additional notes:
To make sure video data is downloaded, I also tried playing the video for a few seconds before applying as texture.
The issue is not happening when using a different video codec.

### Device information
Samsung Galaxy S7 Edge (Android 8.0.0).
Samsung Galaxy 10 Lite (Android 11).
Oneplus 5 (Android 10).

Firefox for Android version:
86.1.1 (Build #2015794883)
AC: 72.0.16, f4aa67a9c
GV: 86.0-20210222142601
AS: 67.2.0

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1699486

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
