### ISSUE TITLE
[Bug] Bottom margin is not aligned with system bars and ime

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18546]
![Screenshot_20210319-003221_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/111700585-a6a94280-884a-11eb-97ff-2ca3dcf0bd45.png)
![Screenshot_20210319-003120_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/111700586-a7da6f80-884a-11eb-9a99-78abf224e1e6.png)
![Screenshot_20210319-003118_Firefox_Nightly](https://user-images.githubusercontent.com/17825767/111700590-a90b9c80-884a-11eb-90ff-f49cf6b40996.png)

### Device information

* Device vendor / model and Android version: XZ1, Android 11
* Firefox for Android version: 
Nightly 210318 17:03 (Build #2015799435)
AC: 74.0.20210316190202, 6e5735dba
GV: 88.0a1-20210313094300
AS: 73.0.1

**Comment by sharbet** [comment]
https://user-images.githubusercontent.com/73639287/111735018-95018280-88be-11eb-9141-f870e8a209c3.mp4

Happening to me too. 

Also, address bar is sometimes overlapped by keyboard (Could not reproduce it, but can confirm it happens)

**Comment by Mugurell** [comment]
> Happening to me too.
In the above video I see the issue with the scrollbars not going to the very bottom.
Interestingly we didn't have an issue for it so I've now created https://github.com/mozilla-mobile/fenix/issues/18552.

**Comment by Mugurell** [comment]
@hakkikaancaliskan Just to confirm, this is not reproducing in the current Release?

**Comment by hakkikaancaliskan** [comment]
@Mugurell nope, no problem on release and beta, this problem started with 3/18 nightly or 3/17.

**Comment by hakkikaancaliskan** [comment]
Maybe related with #18252?

**Comment by sharbet** [comment]
> Also, address bar is sometimes overlapped by keyboard (Could not reproduce it, but can confirm it happens)

![Screenshot_20210319-171411_Firefox Nightly](https://user-images.githubusercontent.com/73639287/111750619-c8500b80-88d6-11eb-9eb6-23aaac922e4f.jpg)

Got the proof of this; when this happens, I cannot directly  access the website: I have to press "back" which then allows me to choose the sites.
It's like there is a transleucent layer(?) that blocks my control.

**Comment by sharbet** [comment]
> Got the proof of this; when this happens, I cannot directly access the website: I have to press "back" which then allows me to choose the sites.
It's like there is a transleucent layer(?) that blocks my control.


https://user-images.githubusercontent.com/73639287/111772691-7f0cb580-88f0-11eb-872d-a0d136eb4b9c.mp4

Video proof of the mentioned problem

**Comment by sharbet** [comment]
> Got the proof of this; when this happens, I cannot directly access the website: I have to press "back" which then allows me to choose the sites.
It's like there is a transleucent layer(?) that blocks my control.


https://user-images.githubusercontent.com/73639287/111773201-330e4080-88f1-11eb-813d-15ffb4659a11.mp4

Got proof of the situation in video.

**Comment by sflorean** [comment]
I was able to reproduce this issue and others linked here, on latest Nightly build.

**Comment by Amejia481** [comment]
We reverted https://github.com/Amejia481/fenix/commit/f2df63166a8d6e30f7471a574566e5eaffba43ea as we believe is the source of the issue, we would like to confirm if the issue is still present.

**Comment by keegan-lillo** [comment]
This appears to be fixed for me on version 24.5.13-21 [0] [PR] 363015067
Pixel 4 - Android 11

Not sure if it's related but search suggestions being scrolled down when using bottom navigation is also fixed. Thanks for all the hard work!

**Comment by sharbet** [comment]
yep. fixed.

**Comment by sflorean** [comment]
Confirming that the issue is not longer displayed on latest Nightly build.
