### ISSUE TITLE
When 'Share image' to Evernote/Whatsapp causes an error message

### ISSUE THREAD

**Issue by ErissonB** [mozilla-mobile/fenix#18547]
## Steps to reproduce
When trying to share the image from contextual menu "Share Image" to Whatsapp or Evernote, you receive an error message or the application does not open.

### Expected behavior
Being able to share the image for the aforementioned apps as it happens in the Brave app. (https://i.imgur.com/jnDz8Dq.png)

### Actual behavior
After selecting the apps in the sharing menu, Whatsapp returns an error message and Evernote doesn't even open. (https://i.imgur.com/yGsbtlx.png)

### About the tests
I tested it on Firefox Beta for Android and Firefox Nightly, with two file formats (.png and .jpg, links to the images used below).

https://media.discordapp.net/attachments/750870690634268756/822200600812716082/test.png
https://cdn.discordapp.com/attachments/750870690634268756/822200618633527346/test.jpg

### Device information
* Android version: 10
* Firefox Beta for Android version: 87.0.0-beta.6 (Build #2015798923)
* Firefox Nightly version: 210318 17:03 (Build #2015799435)

If more information is needed to reproduce the error, just ask.

**Comment by LaurentiuApahideanSV** [comment]
@ErissonB I tried to reproduce your issue but was unable to. Could you please specify the manufacturer and model of the device you are using?
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by ErissonB** [comment]
@LaurentiuApahideanSV 
I used a Motorola One Hyper with Android 10 (Build number QPFS30.103-43-14).

### Apps version

- Evernote version 10.6 (1111498)
- WhatsApp version 2.221.5.17

**Comment by orchidalloy** [comment]
This also happens to me when sharing jpeg images from Google.

Motorola G8 Power on Android 11.

**Comment by Mugurell** [comment]
I tried the two links posted in the first comment and for me sharing to WhatsApp and Evernote works as expected.

https://user-images.githubusercontent.com/11428869/112591748-81e63980-8e0d-11eb-96d9-56172a079aca.mp4

Saw an issue with Telegram not recognizing webp files - https://github.com/mozilla-mobile/fenix/issues/18547 and it's possible other apps don't recognize different formats.
So it's very important to have the link of the image for which the sharing fails tp be able to reproduce this issue and know which formats aren't recognized by which apps.

**Comment by orchidalloy** [comment]
> I tried the two links posted in the first comment and for me sharing to WhatsApp and Evernote works as expected. 
> Saw an issue with Telegram not recognizing webp files - #18547 and it's possible other apps don't recognize different formats.
> So it's very important to have the link of the image for which the sharing fails tp be able to reproduce this issue and know which formats aren't recognized by which apps.

I believe the sharing process by Firefox produces some sort of edge case in the picture's metadata that some apps can still recognize but not others. Again this happens with jpg and png as well, and only in the Firefox browser.

You can see this happening with this image in the following video: https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Bucephala-albeola-010.jpg/1280px-Bucephala-albeola-010.jpg


https://user-images.githubusercontent.com/33796679/112631687-f329ea80-8e15-11eb-9a68-393d887842f4.mp4

**Comment by Mugurell** [comment]
Thank you for the video!
Tried the same scenario and I can see know how sharing fails.
Seems like going through WhatsApp to pick a contact to share to works (and this is the only option allowed by Chrome)
But not sharing to a quick contact with
> {act=android.intent.action.SEND typ=image/jpeg flg=0xb080001 cmp=com.whatsapp/.ContactPicker (has extras)}

https://user-images.githubusercontent.com/11428869/112637883-4cf6d880-8e47-11eb-8a2e-a2385a970d56.mp4

&nbsp;
I'm seeing this as more of a problem in the WhatsApp application but it's something to consider for whether to change to a custom share sheet to not offer that quick share option.

**Comment by orchidalloy** [comment]
Oh interesting, I didn't consider it could be the quick share option itself.

**Comment by creatubers** [comment]
I just installed Firefox 88 on my OnePlus 7T (Android 11) and the bug still persists.

**Comment by orchidalloy** [comment]
Yeah this is clearly a problem with Firefox not formatting the file properly for quick share, as every other app works fine with quick share
