### ISSUE TITLE
FNX3-15863 ⁃ provide an option to disable haptic feedback for tabs button

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1855]
When pressing the tabs buttons in the address bar there is a haptic feedback. That's unexpected - neither Firefox nor Chrome does this - and it's very annoying. Please either remove this or provide an option to disable it.

From reading the code in TabCounterToolbarButton.kt I don't understand why there is a haptic feedback at all:

`it.performHapticFeedback(HapticFeedbackConstants.LONG_PRESS)`

… because it happens with a short press as well.

**Comment by LittleAngelwings** [comment]
Most of it all it's nonsense, if a device has no vibration module like Samsung Galaxy Tab A (2016) :)

**Comment by cadeyrn** [comment]
@ekager Since you implemented TabCounterToolbarButton I have a question for you. ;-) Is this expected behaviour that there is a haptic feedback even without a long press or is this a bug? I was not sure so I didn't labeled this issue as bug. But from reading the code it looks like a bug (for me as someone who is not an Android developer).

**Comment by kbrosnan** [comment]
Verified using a Nexus 5x. Requires the user to have the Vibrate on Tap setting in the Sounds section of the Android Settings.
