### ISSUE TITLE
[Bug] seeking of audio is broken on long files

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mozilla-mobile/fenix#18569]
Check on [this file](https://upload.wikimedia.org/wikipedia/commons/7/77/Complex-numbers--rusalochka.opus): try to go to 1 hour 20 minutes.

And related subissue: please make the seekbar to the full width of the screen, for easier positioning. Current view:

![image](https://user-images.githubusercontent.com/3514015/111880535-2f47f000-89bd-11eb-8aa7-c3bdc2015938.png)

My mockup:
![firefox-mobile-audio-seeking-longer-mockup](https://user-images.githubusercontent.com/3514015/111880881-e85afa00-89be-11eb-9f67-890ec7ecf998.png)

Even better to extract time and volume level, for even better positioning/seeking.

86.1.1 (Build #2015794883)
AC: 72.0.16, f4aa67a9c
GV: 86.0-20210222142601
AS: 67.2.0

**Comment by Mugurell** [comment]
Hello @vitaly-zdanevich , can you please offer more details about what is broken?
Have you seen this issue on different devices?
Have you tried the same on other browsers?

I would've thought the bug relates to seeking from the start of the file to 1h20min or closer to the end and the audio to stop playing but for me it works ok. (Pixel3 with Android 11)

**Comment by abodea** [comment]
I checked this on the latest Nightly 3/22 with Google Pixel 4 XL (11).
Note that when I fast-forwarded there was a big delay until the sound started to play again.
The width depends on the device you are using.
What device (android version) are you using? 
On chrome for example the sounds start a little bit faster when fast-forwarding.

**Comment by vitaly-zdanevich** [comment]
>  Note that when I fast-forwarded there was a big delay until the sound started to play again.

Yes, big delay, sometimes a few minutes, and sometimes infinity.

>  What device (android version) are you using?

Android 8

**Comment by vitaly-zdanevich** [comment]
> Have you seen this issue on different devices?

I have only one Android.

> Have you tried the same on other browsers?

Also very slow fast-seeking on stock browser, looks like it also try to fetch all previous audio :(

**Comment by Mugurell** [comment]
@abodea Can you please try the same file on other devices / browsers and on GVE also?
Also, what's the delay you are seeing. I see around 1 second which I think is reasonable.
I'm curious if there's a pattern to be seen.
It may be possible that the issue is because of the connection or just unrelated to the app if it's reproducing in other situations also.
