### ISSUE TITLE
Can't create new collection with Android 9 / Chrome OS[Bug]

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#18560]
Can't create a new collection with one of the newest nightlies or since the new Chrome OS 89 Update.
I can type a name for a new collection, but the enter-key (software nor hardware key) hasn't any effect.

### Device information

Lenovo IdeaPad Flex5 i5, 8 GB, Chrome 0S 89, newest Updates, Android 9 (container)

 Nightly 210319 17:02 (Build #2015799631)
AC: 74.0.20210318232824, 6010fe8ba
GV: 88.0a1-20210318093109
AS: 73.0.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10092)

**Comment by Mugurell** [comment]
Can you please try if this same issue is reproducing in the current Firefox Release?

**Comment by LittleAngelwings** [comment]
It is also in the current relase. Hard- and software keyboard,

**Comment by lobontiumira** [comment]
@LittleAngelwings could you help us with a short video, and also the exact builds on which you reproduce this issue?
Thank you!

**Comment by LittleAngelwings** [comment]
I have mad a screencast. I've tried today the latest nightly from google play. I can't still set a new collection.
https://drive.google.com/file/d/1-0tOaBQCiKvNLTswIcQ6bTzWxsS3sGqF/view?usp=drivesdk

**Comment by LittleAngelwings** [comment]
with this latest nightly:

Nightly 210417 17:00 (Build #2015805199)
AC: 75.0.20210416190104, 1c2bb53a4
GV: 89.0a1-20210416093642
AS: 74.0.1

I still can't make a new collection, cause the enter key was unrealized. I tried it in laptop mode, also in tablet mode.

**Comment by amedyne** [comment]
Able to reproduce this in Nightly 92.0a1 on a Chromebook. 
See images below comparing Chromebook and landscape on a Pixel 3.

![PXL_20210806_200434409 MP](https://user-images.githubusercontent.com/68711330/128568119-4061dc02-86fb-43ab-94b9-842c210816bc.jpg)

**Comment by LittleAngelwings** [comment]
This issue is still there. In the meanwhile is Nightly 99.0a1 (Build #2015862511), eea4b07cb+
AC: 99.0.20220209170927, b39556f3c9
GV: 99.0a1-20220209095640
AS: 91.0.1

And Chrome OS 98..... and nothing is happened

**Comment by Abendst** [comment]
Hello I have a Samsung  Chrombook also for me no  collections work
https://www.camp-firefox.de/forum/thema/135776-sammlung-erstellen/
