### ISSUE TITLE
[Bug] touch target not accurate when opening a new tab

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#18568]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open any website
Click tab view and select + button to open a new tab
It will open homepage with keyboard popup
Clicking the top site icon is expanding the collection items
Touch target is not accurateh

### Expected behavior
Should open touch items instead of others

### Actual behavior
Opening non touched target element
### Device information

* Device vendor / model and Android version: ? Rog3, A10
* Firefox for Android version: ? (go to Settings -> About Firefox) latest nightly

**Comment by ajshepley** [comment]
I noticed this as well, on `Nightly 210319 20:42 Build# 2015799651` and the preceding Play store version on an S10+.

If you retract the keyboard, the touch target becomes accurate again.

**Comment by Mugurell** [comment]
https://user-images.githubusercontent.com/11428869/111954169-5a7f2c00-8af0-11eb-9d20-2eaa1465511e.mp4

Thank you all for the details here!
Will close this as a duplicate but this scenario should definitely be tested to be fixed by #18546 .
