### ISSUE TITLE
[Bug] Certificate error in Firefox Nightly for Android but not in Firefox Stable for Android

### ISSUE THREAD

**Issue by jrbillpete** [mozilla-mobile/fenix#18561]
## Steps to reproduce
Open:
https://servicos.min-saude.pt/utente/
Or:
https://www.autenticacao.gov.pt
### Expected behavior
The page should load (at least thats what happens in Firefox Stable for Android (86.1.1 (Build #2015794883))
### Actual behavior
Firefox Nightly shows a certificate error
### Device information

* Device vendor / model and Android version: Umidigi A5 Pro - Android 9
* Firefox for Android version: ?
Nightly 210317 17:01 (Build #2015799243)
AC: 74.0.20210316143123, eeaa43b5a
GV: 88.0a1-20210313094300
AS: 73.0.1

**Comment by Mugurell** [comment]
Thank you for the report!
Will move this ticket to Bugzilla since it's more of a gecko issue.
Please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1700040

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
