### ISSUE TITLE
[Bug] Navigation bar no more transparent on Samsung Galaxy

### ISSUE THREAD

**Issue by Mugen-Houyou** [mozilla-mobile/fenix#18570]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Simply open the FF nightly.

### Expected behavior / Actual behavior
![_gff89matb3o61](https://user-images.githubusercontent.com/41905646/111881233-f04a7800-8985-11eb-8ec3-f82f99d9b3b3.jpg)
With the tweak of Good Lock and NavStar on the Samsung Galaxy, we can set the navigation bar transparent. 
However, after the recent update on FF Nightly, it remains the black hint on the navigation bar (it only happens on FF Nightly). 
Refer to the image above and you'll see.

### Device information

* Device vendor / model and Android version: Samsung Galaxy S20 with OneUI 3.1, Android 11 + NavStar 
* Firefox for Android version: FF Nightly 210319 20:42 (Build #2015799651) / AC 74.0.20210319190549

**Comment by Mugurell** [comment]
Thank you @Mugen-Houyou for the details here!
Will close this as a duplicate but this scenario should definitely be tested to be fixed by #18546 .
