### ISSUE TITLE
Reader mode easy way to move page up/down.

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#18572]
### What is the user problem or growth opportunity you want to see solved?
Documents are usually long. To read a document in the reader mode, users usually have to keep scrolling down. Maybe this is a problem with old or 60Hz AMOLED and may be different current 90 or 120MHz display, but most people are using 60Hz AMOLED, and on such a display, during scrolling, the font becomes a little bit fuzzy. And the user's eyes have to seek the correct position after scrolling.

It would be helpful if there is some sort of way to move page down (or up). Maybe something like double-tapping on the bottom area for page down and double-tapping on the upper area for page up. 

### How do you know that this problem exists today? Why is this important?
In my personal experience, following scrolling text on an AMOLED display is tiresome to my eyes, because the fonts becomes fuzzy. Maybe other people feel so, too. It may not be that important, but probably implementing this won't take that much effort either, so I think this feature may be worth the effort.

### Who will benefit from it?
Users who read long documents in the reader mode on an AMOLED screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10103)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814135

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
