### ISSUE TITLE
FNX-5287 ⁃ Telemetry for QR Scanner

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#1857]
As a product owner, I want to know how often people use the QR code scanner to search and open URLs.

Added by @bbinto, April 29, 2019

#### What questions will you answer with this data?
* These probes will help us understand if users use the QR code scanner and how useful it is (# of times successful prompt shown to proceed/open the URL

#### Probes
* Clicked QR scan button in search bar
* Capture event when prompt shows up that reading was successful / not successful

### Dependencies (Added by PM and Eng)
* Glean SDK (Event ping)

### Acceptance Criteria (Added by PM)
* Event pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by vesta0** [comment]
@bbinto to fill out requirements :)

**Comment by bbinto** [comment]
@vesta0 - updated

**Comment by bsurd** [comment]
No metrics are logged in the glean dashboard for the QR code scanner. According to the metrics.yaml file values should be logged for when the scanner has been opened, for the navigation prompt and whether navigation has been allowed or denied.

**Comment by sblatz** [comment]
> Telemetry for the QR scanner is displayed. Was confused by the fact that the data was in the metrics section on the file, but it is mentioned that it's of type event.

@boek is this a problem or is that expected?

**Comment by bsurd** [comment]
To be clear I've referring to the [metrics.yaml](https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml) file.

**Comment by boek** [comment]
@bsurd While it is under the metrics section, it's still a new top level declaration. We've started to move all events into their own namespace versus putting everything under `events:` and `metrics:`.

**Comment by vaporwave9** [comment]
I'm using it! And please don't roast me for my offtopic, I didn't know where to ask, but it is growing on me, because of how much faster it is than my other QR readers.

What library is it based on?
