### ISSUE TITLE
[Bug] Wrong URL copied from custom tab after following another link

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#18576]
## Steps to reproduce
You could probably use any app and link to reproduce this bug, but I'll use Reddit in this example.
1. Open [this post](https://www.reddit.com/r/europe/comments/m6u0n4/on_this_day_30_years_ago_referendum_on_the_future/) in a Reddit client app.
2. Open the link in the post. A Wikipedia article titled "1991 Soviet Union referendum" is opened in a custom tab using Firefox.
3. Tap any other link in the webpage, e.g. "Soviet Union" in the first sentence.
4. Tap and hold the title bar of the custom tab. Tap "Copy" to copy the URL.

### Expected behavior
The URL for the currently opened website is copied. In this case https://en.wikipedia.org/wiki/Soviet_Union.

### Actual behavior
The URL for the previous website is copied. In this case https://en.wikipedia.org/wiki/1991_Soviet_Union_referendum.

### Device information

* Device vendor / model and Android version: Huawei Mate 20 lite, EMUI 10/Android 10
* Firefox for Android version: Nightly 210321 17:00 (Build #2015800011)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/17791
