### ISSUE TITLE
Option/Button to delete all logins and passwords at once

### ISSUE THREAD

**Issue by 01d50u1** [mozilla-mobile/fenix#18573]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
An option/button to delete all saved logins and passwords, similar to the button to delete all your browsing history at once. At the moment, the only way to delete logins and passwords is one by one, which takes three taps per login. If you have dozens, hundreds or even over a thousand logins that'll take you a while.

### How do you know that this problem exists today? Why is this important?
I've checked with Mozilla support and there is no solution other than completely resetting the browser, but then you lose your browsing history, bookmarks and personal settings.

### Who will benefit from it?
Everyone using Firefox for Android or iOS.

**Comment by kbrosnan** [comment]
duplicate https://github.com/mozilla-mobile/fenix/issues/15113
