### ISSUE TITLE
`engine.tab_kills` made it to release

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/fenix#18583]
Looks like the `engine.tab_kills` metric made it into release.
I guess the fix just missed the release window?

It was subsequently fixed, see below.
It will therefore fix itself with the next release I guess.

Original: #17864
Fix: #18115

**Comment by amedyne** [comment]
@badboy Closing this ticket since as you mentioned, the fix is in. Comment if you have other questions related to this.
