### ISSUE TITLE
[Bug][L10n] The ETP Standard (default) option is truncated

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#18581]
## Steps to reproduce
1. Launch Fenix and set the language to Russian or Espanol;
2. Go to Settings -> ETP;
3. Observe the Standard (default) option;
### Expected behavior
The ETP Standard (default) option is visible.
### Actual behavior
The ETP Standard (default) option is truncated.
![rsz_screenshot_20210322-152049](https://user-images.githubusercontent.com/48799384/111997251-8536a800-8b23-11eb-93fb-c97c8b3dba1b.png)
![rsz_screenshot_20210322-152025](https://user-images.githubusercontent.com/48799384/111997233-7fd95d80-8b23-11eb-8273-082eb1bf04ee.png)

### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9);
* Firefox for Android version: Nightly 3/22, Beta 87.0.0-beta.6 and Release 87.0.0-rc.1 from 3/17

**Comment by bharat0to** [comment]
I would like to work on this issue.

**Comment by Amejia481** [comment]
Please free to work on it :)

**Comment by bharat0to** [comment]
I made a pull request #18586. Here is the screenshot
![Screenshot_20210322-224452](https://user-images.githubusercontent.com/44504687/112031073-ef217280-8b60-11eb-93e6-cb5f96bb968b.png)

**Comment by bharat0to** [comment]
Did I make any mistake in PR as it is showing I have requested review from mozilla-mobile/act as code owners instead of mozilla-mobile/fenix?

**Comment by ebalazs-sv** [comment]
This issue is also reproducible on Beta 88.0.0-beta.2 from 3/29 with Pixel 2 (Android 9) when set to Slovak.

**Comment by bharat0to** [comment]
Is this issue reproducible after the fix? and also how can I check for Beta 88.0.0-beta.2 3/29 there is no branch with 88.0.0-beta.2. Please help me out I am new to contributing to open source

**Comment by ebalazs-sv** [comment]
> Is this issue reproducible after the fix? and also how can I check for Beta 88.0.0-beta.2 3/29 there is no branch with 88.0.0-beta.2. Please help me out I am new to contributing to open source.

This is still reproducible on the latest Nightly from 3/30 as well.
The link to Beta 88.0.0-beta.2 build is: https://github.com/mozilla-mobile/fenix/releases/tag/v88.0.0-beta.2

**Comment by bharat0to** [comment]
I have checked the code with tag 88.0.0-beta.2 and of course my pull request is not merged.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta 89.0.0-beta.1 with Pixel 2 (Android 9).

**Comment by Delphine** [comment]
@brampitoyo @Amejia481  Could you perhaps let us know what the next steps are here? thank you!

**Comment by Delphine** [comment]
Update: this happens in many of our top locales, like Spanish, French and Russian (only to list a few).

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/18 Nightly build with Google Pixel (Android 10), and Xiaomi mi4i (Android 5.0.2):

![Untitled](https://user-images.githubusercontent.com/40694158/122524596-fd2c4580-d020-11eb-8d4e-ca250c6fa4f4.png)
