### ISSUE TITLE
[Unit Test] Fix OnboardingHeaderViewHolderTest for Nightly builds 

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#18585]
This [test](https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingHeaderViewHolderTest.kt#L18) is failing when unit tests run on Nightly builds.

It checks the [header text](https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingHeaderViewHolderTest.kt#L32) and the assertion fails with error:

`[task 2021-03-19T20:14:15.372Z] org.junit.ComparisonFailure: expected:<Welcome to Firefox [Preview]!> but was:<Welcome to Firefox [Nightly]!>`

Usually this test runs as part of the `test-debug` task (Task :app:testDebugUnitTest) and so it is green on master and PRs. But it has failed when the task is `test-nightly` task (Task :app:testNightlyUnitTest)  that seems to be running the unit tests on nightly builds.

**Comment by Mugurell** [comment]
With the fix merged I think this ticket can be closed now.
