### ISSUE TITLE
Adopt Default Browser Setting Without Leaving App like Duck Duck Go

### ISSUE THREAD

**Issue by ItsDevyani** [mozilla-mobile/fenix#18589]
### What is the user problem or growth opportunity you want to see solved?
While doing competitive research on how other privacy-centric browsers are asking their users to set them as their default browser, I came across Duck Duck Go New User Onboarding cards. These cards prompt the user to switch their default browser to Duck Duck Go within the onboarding flow itself, without leaving the app to go to settings. This is significant and a great user experience as the user stays within the app and conveniently can choose their default browser while still completing the task they came to do. We should adopt this user flow of setting a user's default browser choice for the following surfaces:
 - The Default Browser Local Notifications
 - The new in-app UX that Nicole designed. We should consider opening this dialog straight from the big button on the new tab page and/or the menu item.
 - The Fenix "Set as Default Browser" settings.
![image](https://user-images.githubusercontent.com/33848595/112057894-181d1580-8b17-11eb-8282-71b5eeba5a4a.png)

### How do you know that this problem exists today? Why is this important?

In Fenix today, the user gets sent to Android settings to change their default browser when they click the choose default browser call to action button in settings. This creates needless friction and disrupts their browsing work flow.

### Who will benefit from it?
This is a win-win. The user will benefit from this feature due to the ease and convenience of choosing the default browser, and Firefox will benefit because this flow will likely increase the default browser conversion rate (a hypothesis that we would like to test and measure) and generate more DoU.

**Comment by hakkikaancaliskan** [comment]
Firefox already using role manager api, that's available for Android 10 and later.
![Screenshot_20210323-000559_İzin_denetleyici](https://user-images.githubusercontent.com/17825767/112058366-91465800-8b6b-11eb-8da6-880dcd012ea7.png)

**Comment by ItsDevyani** [comment]
Adding a Comment from @st3fan from an email on this topic.

The Duck Duck Go browser is open source, and this is where they open this dialog:

  https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserSystemSettings.kt#L25

**Comment by Mugurell** [comment]
> Adding a Comment from @st3fan from an email on this topic.
> 
> The Duck Duck Go browser is open source, and this is where they open this dialog:
> 
> https://github.com/duckduckgo/Android/blob/develop/app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserSystemSettings.kt#L25

This is pretty nice and would be a great addition to our UX, but that will not show a system dialog to change the default browser. 
That code was added as part of https://github.com/duckduckgo/Android/pull/500 to highlight the default app the user is expected to change immediately after opening the system settings for default apps.
For security reasons this is the maximum Android offered on Android <Q.

On Android >=Q we will show the system dialog presented here as only starting with this Android version this exists.
Recording of tapping "Set as Default Browser" in Firefox Nightly on a Pixel3 with Android Q:

https://user-images.githubusercontent.com/11428869/112106049-d2fbf080-8bb5-11eb-820c-fe2c328415b1.mp4



On Android >=N && <= Q we are opening the default apps system settings and expect the user to know to change the default browser.
DDG goes one step further in this case and highlights the default browser system setting.
Recording of tapping "Set as Default Browser" in DDG 57801 on a Samsung S7 with Android O:

https://user-images.githubusercontent.com/11428869/112105715-6b45a580-8bb5-11eb-9ee2-6587e146ec7b.mp4

**Comment by Mugurell** [comment]
I've created #18594 to implement the highlighting the default browser system setting on Android >=N && Android <=Q.

**Comment by Mugurell** [comment]
Going by the first comment maybe we could also tweak our onboarding to prominently show the option of setting Fenix as a default browser if not already?

Asking UX about this.

**Comment by ItsDevyani** [comment]
I'm closing this issue since this flow is now in Beta 88 and will land in Fenix 88 Prod as the default browser flow. I'll file a separate issue for landing an experiment that tests showing this flow with Default borwser messaging like is in DDG above.
