### ISSUE TITLE
FNX-5288 ⁃ [Bug] Search text state not saved on screen rotation

### ISSUE THREAD

**Issue by iadeelzafar** [mozilla-mobile/fenix#1858]
## Steps to reproduce
1- Write something in the search bar.
2- Rotate screen

You'll notice that state is not saved

### Expected behavior
State should be saved.

### Actual behavior
State is not saved.

### Device information
Galaxy Nexus API 24

### GIF:
![](https://user-images.githubusercontent.com/36811908/56460532-a46bae80-63bd-11e9-8112-509aa70336c1.gif)

**Comment by jatinkumarg** [comment]
duplicate https://github.com/mozilla-mobile/fenix/issues/1198

**Comment by iadeelzafar** [comment]
@jatinkumarg Thanks for informing. Closing this.
