### ISSUE TITLE
[Bug] Can't add custom search engine "https://searx.info/?q=%s"

### ISSUE THREAD

**Issue by givianw** [mozilla-mobile/fenix#18598]
try to add "https://searx.info/?q=%s" in search settings

#### reproducible
* 87.0.0-rc.1 (Build #2015799097)
* Nightly 210323 05:01 (Build #2015800297)

android 9,  samsung galaxy j7 nxt

**Comment by cadeyrn** [comment]
Please see #11332.

**Comment by sflorean** [comment]
@givianw thank you for the report! I was able to reproduce this on latest Nightly build with LG G7 (Android 8.1), following your steps.
Please check the solution posted in the above comment and let us know the result. I will close this as duplicate.
