### ISSUE TITLE
Highlight the "Default browser" system setting when users try setting Firefox as default

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#18594]
Seen in https://github.com/mozilla-mobile/fenix/issues/18589

Currently on Android >=N && <=Q when users tap in app settings to set Firefox as the default browser we will open the system settings for from where they can do so.
To go one step further and highlight the actual setting they are expected to change we can use Intent extras as [shown here](https://github.com/duckduckgo/Android/blob/7cfabe189e29bfa760520685494546d979fdca56/app/src/main/java/com/duckduckgo/app/browser/defaultbrowsing/DefaultBrowserSystemSettings.kt).

These changes are to be done in two places: https://github.com/mozilla-mobile/fenix/search?q=ACTION_MANAGE_DEFAULT_APPS_SETTINGS

Current behavior of DDG expected in Fenix also:

https://user-images.githubusercontent.com/11428869/112107004-17d45700-8bb7-11eb-9514-a580360e0bae.mp4

**Comment by yichiehc** [comment]
Hi,
May I try and work on this issue? Thanks!

**Comment by Mugurell** [comment]
> Hi,
> May I try and work on this issue? Thanks!

Sure!
Thank you!

**Comment by jonathanalvares9009** [comment]
@Mugurell Can I work on this issue?

**Comment by Mugurell** [comment]
> @Mugurell Can I work on this issue?

Thank you for your interest!
The work for this was already merged and this feature should work in the current Nightly.
There are other cool tickets you could start with, please take a look @ https://github.com/mozilla-mobile/fenix/labels/good%20first%20issue

**Comment by lobontiumira** [comment]
Verified on the 3/30 Nightly build with several devices:
* Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1) highlight the "default browser" system setting:

https://user-images.githubusercontent.com/40694158/112985306-b12bdc00-9168-11eb-9c44-177ce721a67b.mp4

* HTC 10 (Android 8), and Xiaomi Mi 8 Lite (Android 9) **don't highlight**:

https://user-images.githubusercontent.com/40694158/112987380-55168700-916b-11eb-8fd1-09d29641c9e0.mp4

I'll remove the qa:needed until further notice.

**Comment by Mugurell** [comment]
@lobontiumira For the cases where we'd expect this to work (just because of the Android API level) but it doesn't it would be nice to check if other browsers that have this implemented - DuckDuckGo Browser / Opera show the same issue.
With this not being a public API it might just be that specific devices will not support this functionality.

**Comment by lobontiumira** [comment]
You're right!
Tested with DuckDuckGo and the problematic devices (HTC 10 (Android 8), and Xiaomi Mi 8 Lite (Android 9)) have the same behavior. I'll close this as verified.
Thank you!
