### ISSUE TITLE
Develop a 'Default Browser' Local Notification for New Fenix Users 

### ISSUE THREAD

**Issue by ItsDevyani** [mozilla-mobile/fenix#18592]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

After having Leanplum integrated into our product for almost 4 years to send external push notifications, we are ending our contract with Leanplum on 5/31/21. After a careful review, we have made this decision because of three reasons:
1) Incompatibility with internal tooling (Data and Experimentation)
2) Paying for more than we use/need (Leanplum has a rich use case set, we are only using a small part of it)
3) Resource requirements to manage and debug campaign issues (as it stands today, we spend more time debugging and less time building and running campaigns)
 
While Leanplum as a tool wasn't the best fit for our needs, we do need a solution to message our users externally and we want to start building that capability internally. This request takes the first step/MVP approach in that direction. The request here is to build a pragmatic, simple, and low effort solution to send a notification to a new user to set us as their Default Browser.

### How do you know that this problem exists today? Why is this important?
Once Leanplum is out of our product, we will not have a solution to build and ship notifications. So we want to begin with an MVP solution by building a local notification, built as a feature of the app, (much like the onboarding flow) that gets scheduled in a user's first session and triggers if they do not set us as default 24 hours after 1st app launch. The targeting and triggering functionality of local notifications may need to be explored further and that may change the final notification plan. Based on the opportunity identified, I would like to get a recommendation on what we could do in the first version of this local notification. One key benefit of building this as a feature is that we will have full-funnel visibility from click to DoU of this notification. 

Below you can see 2 notifications Brave sends within 2 hours of app install, The first one is a Default Browser prompt. This gives us a good indication of what this type of notification can look like to the user. 
![image](https://user-images.githubusercontent.com/33848595/112071583-4efe2600-8b2d-11eb-93d9-e009487e29ec.png)

### Who will benefit from it?
This is a win-win feature. A user gets a clear actionable prompt to choose Firefox as their default browser while the download and the reasons behind the download are still fresh in their mind. Firefox will get more DoU if the user chooses us as default. Based on past successful Push Notification campaigns we know that sending a notification like this will lead to a higher rate of the default setting in new users and thus higher retention and DoU.

More Details on Local Notifications can be found in [this doc](https://docs.google.com/document/d/18o4C8tNUINH3RS6FErgnoi5IiMLASr4IHRyVIIDBfRQ/edit#).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10115)

**Comment by Mugurell** [comment]
I see a few important advantages of Leanplum that will require significant effort to develop on our own. If we need them:
- The ability to show fully customizable (size, placement, colors, text, images) in-app banners. Don't think these were used on Fenix yet but they were important on Fennec.
- A/B testing with the ability to even have server overriden resources - text/images.
- A complex targeting system for Leanplum campaigns taking into consideration device details, various user details and all sorts of timing configuration (like showing a message after a few days from an event, after a number of events, etc).

All these with no modification in the app, and possible at any time in all release channels.

**Comment by rocketsroger** [comment]
For adding the notifications, I have some clarification questions that might affect the amount of work:
1. How accurate is the timing of the notification?  Can it be +/- an hour? (minutes?)
2. Are we OK with inaccurate notification in some corner cases?  For example the user might have set Fenix as default browser with Fenix not running.
3. Is the notification(s) one time only? Or will we notify again (for example a week) again if the user haven't set it?  If so, do we need an opt-out mechanism in Fenix's settings?
4. Will this feature be expended in the future so we can add other notifications?  Is time the only trigger?

**Comment by Mugurell** [comment]
If more such notifications would be shown there should be a back-off strategy to avoid them being seen as spam
https://github.com/mozilla-mobile/fenix/issues/18757.

**Comment by jonalmeida** [comment]
From some offline meetings, we need to also clarify which notification channel we want this in. 'Firefox news' is what we used for LeanPlum but we may be able to re-use it.

The 'Firefox news' ID is something that is controlled by LP with the ID value `marketing_messaging` so our local notification approach should use that to make it fall under that category.

**Comment by jonalmeida** [comment]
Yes, thanks. Closing.
