### ISSUE TITLE
FNX-5290 ⁃ [UX] Send & Share

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#186]
**User Story:**
As a user I want to share things I find on the web (including individual items and entire tasks) with myself and/or with others.

**Current Design Status:**

* Foundational Design Done
* Needs further details on intermediary steps
* Need to identify gaps in flows

**Design Priority:**
P1

**Mockups:**
https://mozilla.invisionapp.com/share/ZDQ1OVLSNQ7#/341665627_Send_And_Share

**Comment by bbinto** [comment]
- Sync team is working on "Linked Devices"
- "Sharing sessions"

MVP for Eng:
- share a session from one device to another device

MVP for A/C:
- develop sharing component for one tab/URL
- @pocmo will connect accounts team

Next steps:
- UX to create individual flows

**Comment by bbinto** [comment]
For MVP, PM is ok to have just the share the link via the intent sheet

**Comment by bbinto** [comment]
@shorlander to write up different scenarios

**Comment by topotropic** [comment]
Meta https://github.com/mozilla-mobile/fenix/issues/92

**Comment by bbinto** [comment]
@topotropic sent designs to @shorlander - should be ready for eng early next week.

**Comment by topotropic** [comment]
@boek latest mockup https://mozilla.invisionapp.com/share/4XQHZWB35C8

**Comment by boek** [comment]
@topotropic This all looks great. I can't think of anything we're missing :+1:

**Comment by colintheshots** [comment]
I concur with Jeff. This seems reasonable with the current UX.
