### ISSUE TITLE
Fenix Toolbar Menu Experiment: (Test branch 1: Menu includes Default Browser as a visible option, Control: Default Browser not an option)

### ISSUE THREAD

**Issue by ItsDevyani** [mozilla-mobile/fenix#18608]
## User Story
- As a user, I want to know how I can easily set up Fenix as my default browser when I click the Toolbar menu.

## Dependencies

   

-  [Toolbar Menu Test design option (done)](https://www.figma.com/file/YvvFxwXKonLkvdF0ZcL63Y/Design-feedback?node-id=0%3A1)
-  Nimbus SDK integration with Fenix - [Implementation guide](https://mozilla.github.io/experimenter-docs/fenix-engineers/)
- DS resources to write measurement plan
- Engineering Time

### Acceptance Criteria    

- Set Default Browser as a visible option on the Toolbar menu.
- We can track default browser activations coming from this source full-funnel (Clicks at each step) including conversion to default.
- Nimbus SDK integration with Toolbar menu to enable testing on it.

### Engineering notes
- [Nimbus engineering docs](https://mozilla.github.io/experimenter-docs/fenix-engineers/)
- Please sync with data science before starting this implementation to confirm the following: 

**Experiment length**: TBD (default: 35 days total, 7 day enrollment period)
**Start date**: TBD
**Experiment size**: TBD
**A/B split**: TBD (default: 50/50)
**Channels**: Release, Nightly
   * > all of the Nimbus experiments should be pushed to nightly first. [...]  Also, they don't need to go to beta afterwards but instead can go to production.

**Comment by amedyne** [comment]
Note: This ticket will be for tracking the Engineering tasks for developing Experiment **Test Branch 1: Menu includes Default Browser** as a visible option and the corresponding telemetry needed for this branch.
