### ISSUE TITLE
FNX-5291 ⁃ [Bug] Scattered Textviews in About Fenix

### ISSUE THREAD

**Issue by iadeelzafar** [mozilla-mobile/fenix#1860]
## Steps to reproduce
1- Go to settings.
2- Go to About Fenix 
You'll notice some text views are not in center.

### Expected behavior
These textviews should be centered.

### Actual behavior
Not centered.

### Device information
x86GreenFieldDebug
Galaxy Nexus API 24

### GIF:
![](https://user-images.githubusercontent.com/36811908/56460678-fa415600-63bf-11e9-8e4a-be46ed504138.gif)

**Comment by jatinkumarg** [comment]
I have added a PR https://github.com/mozilla-mobile/fenix/pull/1861

Let me know if any changes are required.

**Comment by lime124** [comment]
@AmyYLee can you review? i'm not sure if Bram had a design for this screen.

**Comment by AmyYLee** [comment]
Hi, 

Can you please reference this mock for content placement. Thanks!

https://mozilla.invisionapp.com/share/AHRPCMCYD2Q

**Comment by iadeelzafar** [comment]
@jatinkumarg Please have a look at the link above @AmyYLee has given and make the changes accordingly.

**Comment by jatinkumarg** [comment]
@iadeelzafar  Sure thing!

**Comment by jatinkumarg** [comment]
Hey, I am having issues with the build. So anyone who wants to fix it, please go ahead.

**Comment by abodea** [comment]
Hello, is the following text **`Fenix puts you in control`** completely removed from **`About Fenix`?** it's missing and I didn't saw any mention about it.
@vesta0 can you please clarify if this is intended?

**Comment by vesta0** [comment]
@abodea I wasn't aware of this change. @mheubusch was this planned?

**Comment by bifleming** [comment]
@softvision-miralobontiu can you please provide info on what is blocking this?

**Comment by softvision-miralobontiu** [comment]
I'll remove the "blocked" flag. Sorry for the misunderstanding.

**Comment by vesta0** [comment]
@mheubusch did we mean to remove "Fenix puts you in control"  from the About Firefox Preview pag?

**Comment by mheubusch** [comment]
Yes. We don’t yet have an approved tag line from marketing so asked to remove this until we do.

**Comment by vesta0** [comment]
Closing this issue since the original reported bug has been resolved. A new issue can be opened for adding a new tagline once we have one.
