### ISSUE TITLE
[Spike] Usage of custom built vs native Android/Material components

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#18612]
## Description

Fenix UI uses multiple components. Below is a non-exhaustive list:

- Bars
    - App bars: top (e.g. top of Settings)
    - Toolbars: bottom (e.g. address bar with ⋮ Application menu in it)
- Cards
    - Collection cards
    - Onboarding cards
- Controls
    - Buttons and Floating Action Buttons
    - Checkboxes, Radio Buttons and Switches
    - Lists (e.g. items within in ⋮ Application menu and Settings)
- Sheets and Panels [Doorhanger]
    - Dialogs
    - Menu panels (e.g. Application menu)
    - Site information and permissions panel (lock icon)
    - Tracking Protection panel
    - Tabs Tray

We at the Mobile UX team would like to know whether these components are:
- Native to Android/Material and used without alteration
- Native, but customised to some degree
- Fully custom to Firefox, and written from scratch

We know that native components have accessibility benefits (e.g. text sizes, talkback – not always, though) as well as compatibility with future OS versions (ie. they will always look good with Android 12, 13, etc.).

## Deliverables

Documentation of investigation results:
- Findings

Recommendations:
- Are there any ‘low hanging fruit’ component that’s quick and easy to convert to native?
- Are there any component that’s custom for a good reason, and/or doesn’t have Android/Material parallel?

Having an inventory of native vs. custom components will enable us, as we work on features that impact certain components, to recommend conversion to native when it makes sense to do so.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10126)

**Comment by gabrielluong** [comment]
I think we can do something similar to Proton for desktop where we create an inventory deck of all the components in Fenix. This is mostly about documenting our components with screenshots, their filename, noting the UI widget usage and any particular customization, etc.

**Comment by gabrielluong** [comment]
Potential good reference material https://github.com/mozilla-mobile/fenix/issues/4841

**Comment by brampitoyo** [comment]
@gabrielluong Last year, @betsymi and I audited Fenix UI components from a content design point of view.

https://docs.google.com/presentation/d/1b7mAuUwH5e-rLOKd8dJg2lD08KSl-3hiVEesm2y1t1k/edit

Although our deck doesn’t cover custom built vs. native, it does include a pretty comprehensive inventory of components. Maybe it will be a good starting point?

**Comment by gabrielluong** [comment]
https://github.com/mozilla-mobile/fenix/issues/9857#event-4542853933

**Comment by gabrielluong** [comment]
https://github.com/mozilla-mobile/fenix/issues/9888
https://github.com/mozilla-mobile/fenix/issues?q=label%3A%22style+guide%22+is%3Aclosed
https://github.com/mozilla-mobile/fenix/issues/5499#issuecomment-814490376

**Comment by gabrielluong** [comment]
https://github.com/mozilla-mobile/fenix/projects/40#card-36210597

**Comment by gabrielluong** [comment]
Just assigning myself so I can always find this.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813633

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
