### ISSUE TITLE
Resolve EngineView#InputResult deprecation from AC

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#18617]
https://github.com/mozilla-mobile/android-components/pull/9963 will deprecate EngineView#InputResult.

This is currently used in [DynamicDownloadDialogBehavior](https://github.com/mozilla-mobile/fenix/blob/07748f69b75144e8e247b742f66a756f999cb299/app/src/main/java/org/mozilla/fenix/downloads/DynamicDownloadDialogBehavior.kt) which needs to be migrated to the new `InputResultDetail` api.

**Comment by Mugurell** [comment]
For QA. This was just a small code refactorization. But it would help to know that the "download completed dialog" can be hidden / shown as before and nothing is broken in this functionality.

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/7 Nightly build from 4/7 with HTC 10 (Android 8), and Samsung Galaxy Note 8 (Android 9).
Downloading multiple files displays the "Download complete" dialogue. No issues encountered.
