### ISSUE TITLE
Update the cookie bocking string based on the new cookies preference for Private Browsing Mode

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#18627]
Gecko will be introducing a new preference that will [change the way that cookies work on Private Browsing Mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1695050) for  adapting to this feature we will need:

* A new string for when the preference change.
* [Expose the new API from GV](https://bugzilla.mozilla.org/show_bug.cgi?id=1700750) to detect when the preference change.
* Update Fenix integrate new API and update the string.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10133)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807443

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
