### ISSUE TITLE
[Bug]Menu animation when opening Settings - on Nightly

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#18620]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Tap on 3 dot menu.
2. Open Settings.
3. Pay attention to the menu items.

### Expected behavior
No visual issues are displayed.

### Actual behavior
A menu animation is displayed, Accessibility entry is moved up. 
 
### Device information
* Device vendor / model and Android version: Pixel 3 (Android 11), LG G7 Fit (Android 8.1.0)
* Firefox for Android version: Nightly 3/23, and 3/24
* Not reproducible on Beta and Release.
 
Video
https://user-images.githubusercontent.com/58466444/112332969-daf58680-8cc2-11eb-8ca0-784264bc85fb.mp4

**Comment by Mugurell** [comment]
@gabrielluong The setting that vanishes is the "Credit cards" ones introduced in #18240.

**Comment by Mugurell** [comment]
If this logic will remain - certain preferences need to be dynamically shown / hidden we can make it work without the visual artifact but wondering if maybe this settings will always be there when getting to beta so the issue will be fixed by itself.

**Comment by gabrielluong** [comment]
Perhaps we can make the "Credit cards" hidden in the XML layout to be hidden for the time being so we aren't hiding it dynamically.

**Comment by Mugurell** [comment]
The issue seems to be that the `update` method which sets the visibility of certain preferences is called in Fragment's `onResume` - "long" after they are initially displayed.
If starting with some preferences hidden and then we check and display them we'd see the same issue.
If we'll need to avoid this entirely we should build the preference tree before onResume (I'd say why not in onCreate?).
