### ISSUE TITLE
FNX-5292 ⁃ [Bug] deleting a bookmark item not hiding it immediately

### ISSUE THREAD

**Issue by k0ur0x** [mozilla-mobile/fenix#1862]
## Steps to reproduce
* delete a bookmark item

### Expected behavior
* bookmark item should not be visible anymore

### Actual behavior
* displays a deleted message with undo but the item is still visible

### Device information
* Android device: p20 lite (android 8.0.0)
* Fenix version: 1.0.1917

**Comment by colintheshots** [comment]
The screen reflects the actual state of the bookmarks. The snackbar on deletion offers a short window to undo during which it remains visible.

There isn't really a great option to fake that we deleted it when we didn't yet. I tried sending the signal to not show it, but if the user exits bookmarks and re-enters within three seconds then the stale bookmark will still show until one re-enters after the three seconds has expired. Setting a shorter duration to undo means there isn't much time to press undo. I'll ping UX for an opinion.

**Comment by colintheshots** [comment]
I pushed a fix. It's still not ideal. If the user browses away and browses back before the bookmark has deleted, then the deletion won't be reflected visibly right away. However, it should cover most cases.

**Comment by sv-ohorvath** [comment]
Verified as fixed on master 5/2 build, but found a new issue: #2226
