### ISSUE TITLE
Add support for SmartBlock exceptions

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#18629]
The desktop team is working on a [new feature](https://bugzilla.mozilla.org/show_bug.cgi?id=1699667) for [SmartBlock](https://blog.mozilla.org/security/2021/03/23/introducing-smartblock/) (Shimming), it will unblock automatically some resource that were previously blocked based on some heuristics. It will requires:

* Updating the tracking protection panel with new strings and section.
* [Updating AC with a new tracking protection category to detect the unblocked resources](https://github.com/mozilla-mobile/android-components/issues/10127).
* Some changes on GV to provide a new API.

**Comment by Amejia481** [comment]
Depends on https://github.com/mozilla-mobile/android-components/issues/10127

**Comment by Amejia481** [comment]
We want update the shield tracking protection panel to indicate that a site has been, unblock similar to what desktop is doing.
![image](https://user-images.githubusercontent.com/773158/126211941-6e9671d6-6b3b-481e-a55b-d8b4b30c9a33.png)

To test on desktop you only have:
1. Enable mobile view with the profile "Nokia 8110 4G"
2. Enabled strict tracking protection setting.
3. Open in private tab, an navigate to www.patreon.com.
4. Click "Login" under the hamburger menu. 
5. Click continue with Facebook.
4. Under the www.patreon.com you will bee on the tracking protection shield panel  "Tracking content"

**Comment by eliserichards** [comment]
Websites may load external ads, videos, and other content with tracking code. Blocking tracking content can help sites load faster, but some buttons, forms, and login fields might not work.

Some trackers marked below have been partially unblocked on this page because you interacted with them.

Learn more link: https://support.mozilla.org/en-US/kb/smartblock-enhanced-tracking-protection?as=u&utm_source=inproduct

**Comment by eliserichards** [comment]
Current Fenix nightly: 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/43795363/126231712-0e9d194e-03b6-4b77-bad3-256214ebb48b.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/43795363/126231750-67c0fa49-2b5c-43d2-90d2-767b5c31680d.png">
