### ISSUE TITLE
i18n.detectLanguage does not work

### ISSUE THREAD

**Issue by FilipePS** [mozilla-mobile/fenix#18633]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Call the function _browser.i18n.detectLanguage_
Example: `browser.i18n.detectLanguage("Hello", r => console.log(r))`

### Expected behavior
...

### Actual behavior
This error is generated
`[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://extensions/content/parent/ext-i18n.js :: detectLanguage :: line 34"  data: no]`

### Device information

* Device vendor / model and Android version: Moto g7 play Android 10
* Firefox for Android version: Nightly 210324

 This problem has been occurring for more than 1 year.

**Comment by mcarare** [comment]
@FilipePS I suppose you use this for a web extension. Does this work on Firefox for desktop?

**Comment by FilipePS** [comment]
> @FilipePS I suppose you use this for a web extension. Does this work on Firefox for desktop? 

Yes

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1712214

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Rob--W** [comment]
FYI this got fixed in Firefox 106.
