### ISSUE TITLE
FNX-5293 ⁃ Move Bookmarks

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1863]
### Why/User Benefit/User Problem
As a user with bookmarks, I can move my bookmarks so that I can organize them in a way that makes sense to me.

### Acceptance Criteria (how do I know when I’m done?)
I can select a bookmark and move it into another folder
I can select a bookmark that is in another folder and move it into a different folder
I can select multiple bookmarks and move them into another folder

**Comment by cadeyrn** [comment]
That's already possible so what is this ticket about?

**Comment by yoasif** [comment]
How?

Fenix crashes for me when editing a bookmark and tapping  the bookmark folder, so if that is how, that is helpful. 

There is no context menu option though, so if it is already possible to do this when tapping the folder in edit mode, this could be turned into a request to add a context menu item.

**Comment by cadeyrn** [comment]
The crash is already fixed in master. But yes, tapping the bookmark folder lets you change the folder.
