### ISSUE TITLE
Missing features in Firefox Android

### ISSUE THREAD

**Issue by barcadams0** [mozilla-mobile/fenix#18636]
As long as it is impossible to send feedback to Firefox via official feedback page (https://qsurvey.mozilla.com/s3/Give-feedback-landing-page)  for months, I try to use different channels.
I think it is a main issue, that the features available on desktop and mobile firefox are not standardized. E.g. we can't make full webpage screenshot and search in browsing history. 
I think both would be useful.
Regards,
Adam

**Comment by cadeyrn** [comment]
Please make only one feature request per issue. Otherwise it's not possible for the team to label your requests accordingly.

Your requests are both duplicates of already existing feature requests: #89, #10046.

**Comment by mcarare** [comment]
@barcadams0 Thank you for your report. This will be closed as duplicate as the requests are already made in other issues, like @cadeyrn mentioned.
