### ISSUE TITLE
FNX-5294 ⁃ [Bug] About Settings page is not entirely visible

### ISSUE THREAD

**Issue by k0ur0x** [mozilla-mobile/fenix#1864]
## Steps to reproduce
* go to About Settings page on a small screen device

### Expected behavior
* the user should see the page entirely

### Actual behavior
* the page is not entirely visible

**Comment by mauryat** [comment]
@k0ur0x what's the url you are referring to? Is it about:settings (this doesn't exist) ? So, I'm assuming you are referring to Menu -> Settings?

**Comment by cadeyrn** [comment]
@mauryat Menu > Settings > About Fenix

**Comment by mauryat** [comment]
@k0ur0x do you have an example small screen device that you tried it on? What's the screen size? Do you have a screenshot?

**Comment by mauryat** [comment]
@k0ur0x I don't see any difference between standard and small (2.7") screens. See screenshots:
2.7"
![device-2019-04-21-150553](https://user-images.githubusercontent.com/9949800/56468256-6b781c00-6447-11e9-8ce2-9303329b144d.png)

Standard:
![device-2019-04-21-150736](https://user-images.githubusercontent.com/9949800/56468262-7cc12880-6447-11e9-810e-95d744bf75ac.png)

**Comment by mauryat** [comment]
Also small screen sizes account for only 0.4% of devices (even if the visibility was an issue).

**Comment by k0ur0x** [comment]
I meant cases like when you run the app in Multi-Windows or small devices in the landscape.  I thought it would be better to have this page scrollable. however, it's not a critical problem.
