### ISSUE TITLE
Intermittent UI test failure - SmokeTest.customTrackingProtectionSettingsTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#18647]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8719182991764003537/executions/bs.e5d3849027200f00/test-cases
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/onboarding_message`

**Comment by AndiAJ** [comment]
Flaky 1x on 8/12 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5447584514495229913/executions/bs.c96340e4725804bb/testcases/1/test-cases)
