### ISSUE TITLE
website not responding

### ISSUE THREAD

**Issue by Apkroo** [mozilla-mobile/fenix#18651]
عندنا اقوم بفتح هذا الموقع علي المتصفح يقوم بالتوقف وعدم الاستجابة الي اي لمسات للهاتف هل هذا يرجع الي الموقع ام المتصفح مع ان غير المتصفح يعمل عليه عادي 

هذا رابط الموقع يهمني ان يعمل عليه لنيواق م بتحميل العاب موبايل من هناك 
[موقع العاب موبايل](https://loloapps.co/) 

Automatic Translation:
When I open this site on the browser it stops and does not respond to any touches of the phone Is this due to the site or the browser even though the non-browser is working on it normal

This website link is important for me to work on for Niqas, by downloading mobile games from there
[Mobile games site](https://loloapps.co/)

**Comment by scheinercc** [comment]
Just tested it on Nightly 210322 (GV 88) and on 210328 17:01 (GV 89) with ETP Strict enabled. I clicked around a bit and had not response issues.

**Comment by SoftVision-LorandJanos** [comment]
Hi @Apkroo! I tested it on the Latest Release 87.0.0-rc.1 and could not reproduce the issue described above, however I verified it on the latest Nightly 210329 00:12 (GV89) and while the items are accessible, the images for the items on the page are not displayed. Also, when accessing the items, the detailed page doesn't contain the images either. This happens with ETP both Strict and Standard enabled. I also checked on the latest Google Chrome 89.0.4389.105, still not reproducible.
Device used: Motorola Nexus 6 (Android 7.1.1)



https://user-images.githubusercontent.com/48829350/112827685-5a0a0680-9097-11eb-9a73-7a281692e5af.mp4

Could you please tell us the version you reproduced it and the device you were using?  And it could help a lot if you would send a video of how it happens to you! Thanks you!

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.

Verified it on the latest Nightly build (2021-09-27T05:10:46.748448).

Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Xiaomi Mi11 Lite (Android11).
