### ISSUE TITLE
[Bug] Toolbar becomes blank when find bar is opened

### ISSUE THREAD

**Issue by Andereoo** [mozilla-mobile/fenix#18654]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open the settings window in latest Firefox Daylight app and select the option to put the toolbar on the top of the screen
2. Visit any website and click on the three dots on the toolbar
3. Click 'Find in page'

### Expected behavior
The find bar would open at the bottom of the screen, and the toolbar at the top of the screen would either remain unchanged, as it did before the last update or would become hidden, as is the case when the toolbar is at the bottom of the screen.

### Actual behavior
The find bar opens at the bottom of the screen, and the toolbar is still visible but becomes blank. When the find bar is closed, the buttons and urlbar in the toolbar become once again visible.

### Device information
* Device vendor / model and Android version: BLU C6L, android 8.1.0
* Firefox for Android version: 87.0.0

 ### Screenshots
![Screenshot_20210326-121034](https://user-images.githubusercontent.com/50446686/112661364-d220c400-8e2c-11eb-9fe0-18e74e1447b4.png)
![Screenshot_20210326-121048](https://user-images.githubusercontent.com/50446686/112661359-d0570080-8e2c-11eb-977d-2aad8d9bc897.png)

**Comment by mcarare** [comment]
@Andereoo Thank you for your report. This seems like the same issue reported here: https://github.com/mozilla-mobile/fenix/issues/18616. Closing this as duplicate, you can follow the topic on the mentioned issue.
