### ISSUE TITLE
signalstickers.com animations freeze the app and system

### ISSUE THREAD

**Issue by orrc** [mozilla-mobile/fenix#18658]
## Steps to reproduce
Reproduced before and after a reboot, also incognito.

1. Visit https://signalstickers.com/
1. Wait 5–10 seconds for things to settle
1. Tap on "animated" (updates URL to https://signalstickers.com/?s=animated%3Atrue)
1. Wait 5–10 seconds for things to settle
1. Fling to scroll down a few pages
1. Wait 5–10 seconds for things to settle
1. Notice that animations become laggy and then freeze
   - If it doesn't happen immediately, it does after visiting a page or two and returning to the list
1. Attempt to interact with the page or any Android system UI

### Expected behavior
GIFs on the page don't stutter.
Firefox itself doesn't freeze.
Phone can be used.

### Actual behavior
Animations stutter and then freeze.
Firefox freezes.
Android system UI freezes — can't press Home, use Notification shade etc.
Phone is 100% unusable for 1–3 minutes and becomes warm, until an ANR dialog eventually appears for Firefox and many other apps, and/or System UI restarts itself.

### Device information
* Android device: Google Pixel 3a, Android 11 (build RQ2A.210305.006)
* Fenix version: Firefox Nightly 210324

**Comment by Mugurell** [comment]
Moving this to Bugzilla since it seems to be a GeckoView issue.
Please follow the discussion there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1701556

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
