### ISSUE TITLE
[Bug] typing domain in urlbar results in leak to google search

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#18665]
When typing a valid domain in the fenix url bar this sometimes results in a search instead of following the domain.
This unnecessary leakes user behaviour to search services such as Google.

### Expected behavior
When typing a domain in the urlbar this should never result in a search, unless the user explicitly requests a search.
The browser should only activate a search when the typed or corrected text is definitely not a domain.

### Actual behavior
Type a valid domain, or make a valid domain by correcting text.
The browser switches to the search service instead of following the valid domain.

### Device information
Recent versions Fenix

**Comment by Mugurell** [comment]
@clientenq Can you give some examples?

**Comment by lobontiumira** [comment]
Hi @clientenq!
I was not able to reproduce this issue. I opened several pages with valid domains, none of it opened a search.
I've tested on the 4/7 Firefox Nightly with Samsung Galaxy Note 8 (Android 9).
Could you, please, provide us more details?

**Comment by clientenq** [comment]
Noticed serveral times since report under following conditions:

Domain or url without protocolhandler was once used as search term.

When typing a similar domain or url, or editing such domain or url, fenix is not clear when it will use this as search request or browsing request.

It is in any situation not clear when fenix will switch from searching to browsing or vise versa, dispite use of icons in the bar.

I would expect it would help when fenix is very clear when it will handle typed text that is a domain or url as browsing or searching when text it typed or modified. At least at the moment prior to and during submitting by the user as request.
