### ISSUE TITLE
[Bug] Firefox doesn't open URL when clicked on push notification

### ISSUE THREAD

**Issue by devpato** [mozilla-mobile/fenix#18663]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to this demo website to send a push notifications: https://onesignal-fcm-e72c4.web.app/ on your mobile Android phone
2. Click on prompt
3. Go to this website on your computer https://onesignal-fcm-e72c4.web.app/
4. On the website listed above from your computer, click on SEND PUSH. 
5. You should receive notification on your phone
6. If you click on the notification, Firefox opens but it doesn't open the URL that the push notification contains.

### Expected behavior

On push notification clicked, Firefox will open the URL that the push notification contains

### Actual behavior

On push notification clicked, Firefox will  doesn't open the URL that the push notification contains. It works on Firefox for computer but not on mobile. Also, other browsers like Chrome and Brave do have the expected behavior. We have tried with OneSignal and Firebase Cloud Messaging and the bug happens in both Push notifications providers. Based on my research I think it's a bug on Firefox.

### Device information

* Device vendor / model and Android version: Google Pixel 5
* Firefox for Android version: ? 87.0.0-rc-1

**Comment by devpato** [comment]
potential duplicate https://github.com/mozilla-mobile/fenix/issues/11138

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1353005#answer-1448895
