### ISSUE TITLE
FNX-5295 ⁃ [Bug] No url can be reached

### ISSUE THREAD

**Issue by mauryat** [mozilla-mobile/fenix#1866]
## Steps to reproduce
1. Get the latest commit (23e2b51)
1. Build and run Fenix
1. Navigate to google.com

### Expected behavior
Google home page (www.google.com) should be rendered.

### Actual behavior
"Secure connection failed" message displayed. See screenshot:
![device-2019-04-21-142130](https://user-images.githubusercontent.com/9949800/56467770-d83be800-6440-11e9-8fd5-a4ce252bf339.png)

### Device information
* Android device: Samsung Galaxy S8
* Fenix version: 1.0.1917

**Comment by boek** [comment]
Hey @mauryat thanks for reporting! This is a known bug that we've been having a hard time reproducing. If your comfortable with it, I would love to be able to chat with you to try to figure out how you got into this state!

Otherwise you can just clear your app data and the app should function normally again :)

**Comment by mauryat** [comment]
Sure @boek , we can chat further on this. Let me try to recollect what could have led to this state. I might have tried making it the default browser. Also, can I work on this bug?

**Comment by mauryat** [comment]
Hmm just tried setting as default browser, but not able to reproduce. Tried
few other things, but without luck. Let me know if you'd like me to try
anything.

**Comment by kbrosnan** [comment]
The work around right now is to clear the app data. Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1546361 should fix this.

**Comment by bifleming** [comment]
@cpeterso

**Comment by cpeterso** [comment]
Is this bug still reproducible? GV bug 1546361 was fixed in GV 68 back in May, so Fenix should have the fix already.

**Comment by vesta0** [comment]
Moving this to QA needed.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly build Nightly **`#11900609 from 9/7/2019`** using the following devices:
• Google Pixel 3XL (Android 9)                                                                                                             • 
• Samsung Galaxy S9 (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
