### ISSUE TITLE
Backoff or stop trying to send the optout/delete ping if connection to the telemetry server fails

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18660]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Install and setup adguard https://adguard.com/en/welcome.html
Turn off all prefs in data collection settings
Force close firefox and then start
Watch filter log in adguard

Note: this only happens if adguard is running while turning off prefs

### Expected behavior
There is no ping to incoming.telemetry.mozilla.org

### Actual behavior
There is literally tons of pings to that telemetry link

<img src="https://user-images.githubusercontent.com/17825767/112699277-8ad21c00-8e9c-11eb-9345-caa840365f45.png" width="500">

### Device information

* Device vendor / model and Android version: Xperia XZ1 Android 11
* Firefox for Android version: 88 beta 1

**Comment by kbrosnan** [comment]
I expect that this is the optout/delete ping that is sent. Though trying 3ish times a second seems rather poor.

**Comment by kbrosnan** [comment]
Talked with the Glean team and they have opened bz-1701663

**Comment by amedyne** [comment]
Closing this issue, track thru  bz-1701663.
