### ISSUE TITLE
Search widget loses voice-search icon below 4.5 boxes (?) wide, but is very space-wasteful [Bug]

### ISSUE THREAD

**Issue by SimonDedman** [mozilla-mobile/fenix#18661]
This is with Nova launcher, 10x8 so 8 apps wide on an Asus Zenfone 6, so I don't know exactly what this equates to in terms of pixels or cm or whatever. Regardless though, the widget seems to need an inordinate amount of space to display the microphone icon, despite being incredibly wasteful of the space its given. Better design could allow the widget to shrink to 1x2 and while retaining both icons - especially since the widget is just (a paior of) shortcut(s), [as noted](https://github.com/mozilla-mobile/fenix/issues/7337).

![Screenshot_20210326-161240174](https://user-images.githubusercontent.com/4599748/112701768-6d478700-8e89-11eb-8bdb-7b8cbba4cf7f.jpg)

Side padding compared to typical app icons, including the knock-on effects of this sizing for having to shrink other widgets to accommodate this, i.e. sun cut off in the weather app.

Android 11, FF 87.0.0-beta-6, build 2015798923.

Cheers folks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10152)

**Comment by LaurentiuApahideanSV** [comment]
@SimonDedman Are you reporting that the the microphone icon for the widget is not displayed when the widget size is set to 2x1? In this case issue https://github.com/mozilla-mobile/fenix/issues/9323 has already been summited.

**Comment by SimonDedman** [comment]
Hi @LaurentiuApahideanSV , yes this is basically the same issue. However the microphone disappears below 4.5 not at 2, and the other issue doesn't mention the fact that the widget is completely misaligned to the grid system, thus wasting tons of space.

**Comment by SoftVision-LorandJanos** [comment]
Hi @SimonDedman! Is this issue still reproducible with the latest Nightly? 98.0a1 (2022-02-04) would be today's build.
If yes, could you make a video of the microphone icon not displayed below 4.5 boxes? Thank you!
For me on all the test devices this issue is only below 2, in which case the bug mentioned above should cover this one.
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Oppo Reno 6 (Android 11).
- Google Pixel 4 (Android 12).

**Comment by SimonDedman** [comment]
Sorry bud, fell through my inbox.

I turned 0.5 boxes off, but it's visible in 4 and invisible in 3 boxes, once padding is turned off. I only recently found out that you have to disable 'annoyingly large padding' - which is default in nova - on a per-item basis.

Currently 98.0.0-b4 build 2015865235 2022-02-24
