### ISSUE TITLE
Make it easier and quicker to get to bookmarks

### ISSUE THREAD

**Issue by Imerion** [mozilla-mobile/fenix#18664]
I almost never use the search option, instead preffering to browse through my bookmarks to navigate to pages. When I open a new tab I want to quickly go to my bookmarks to select the page I want to visit from the list. But every new tab covers up the dot-menu button with some sort of search overlay. In order to get to my bookmarks I first have to press back, then open the menu, then click bookmarks and then get the list.

I know I can use the search bar to write the name of a bookmark and find it, but I often want to browse around my bookmarks to decide what I want to do next. I also don't always remember names and sometimes I want to go through bookmarks in a certain order.

Solutions to this problem would be to either add a button on the search pop-up that goes directly to the bookmark menu or to add an option to disable the search pop-up. It would also be nice to have a button in the regular toolbar to open the bookmarks menu, as many other mobile browsers have solved this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10154)

**Comment by sflorean** [comment]
@Imerion you can now use the search option only for bookmarks, when you open a new tab, please check #24301. And, also if you go to menu - Bookmarks, search is also available.

**Comment by Imerion** [comment]
@sflorean Interesting! So if I click on Bookmarks in the seach menu, as shown in https://github.com/mozilla-mobile/fenix/issues/24301, it will open the Bookmarks-view with folders and all? If so that would be a good solution!

Only being able to search among the bookmarks isn't much help though. I want to browse through them. There are way too many for me to remember what to search for, and often I don't know exactly what I want to read and click around my bookmarks to find something interesting. I use them as a way to collect things I want to read in the future, for example. :)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812706

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
