### ISSUE TITLE
[Bug] user.js cannot be used

### ISSUE THREAD

**Issue by freebrowser1** [mozilla-mobile/fenix#18679]
## Steps to reproduce
On Android this cannot be done (unless you are rooted). On a computer, I can enter the folder Mozilla/profiles/xxxxx/user.js and edit that file.

It would be very useful, particularly when in the retail version of Firefox without about:config, to set own extended preferences this way. A way can be putting this file in /sdcard/Androd/data/org.mozilla.firefox/files/user.js which is readily accessible by the user.

**Comment by kbrosnan** [comment]
We are not going to allow browser prefs to be stored in a world writable location. It would be a significant security risk as any app could write to them. If you want to use such tools you are going to need root and understand that you are using a unsupported configuration.
