### ISSUE TITLE
FNX-5296 ⁃ [Bug] Bookmarks lost selected items if display turned into landscape and vise versa

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#1867]
## Steps to reproduce
Select some bookmarks at library bookmarks
Turn your device at landscape or from landscape into other scape. 

### Expected behavior
Selected items will be selected again

### Actual behavior
After a turn no bookmarks are selected 

### Device information
* Android device:
Samsung Galaxy Tab A (2016) SM-T580, Android 8.1.0 
Huawei P smart, Android 8.0.0 
* Fenix version: 1.0.1917 (11111212)

**Comment by vesta0** [comment]
This looks fixed.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Fenix Build **`#11850611 from 4/7`** using the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)
• Nexus 7 (Android 5.1.1)
•Nexus 9 (Android 7.1.1)
