### ISSUE TITLE
[Bug] WebRTC Control doesnʼt work

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#18678]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Install [WebRTC Control](https://mybrowseraddon.com/webrtc-control.html) following instructions at the [Mozilla Blog](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)
2. Open [Test WebRTC Leak](https://webbrowsertools.com/test-webrtc-leak/)
### Expected behavior
WebRTC Control should be work as expected 
### Actual behavior
1. Test page shown red notice “Your browser is leaking webrtc ip-address!”
2. All of the options for WebRTC Control canʼt be saved
### Device information

* Device vendor / model and Android version: 7.0
* Firefox for Android version: 
Nightly 210328 17:01 (Build #2015801355)
AC: 75.0.20210328143118, 6acc69a7d
GV: 89.0a1-20210327094311
AS: 74.0.1

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 210407.

### Device used:
- OnePlus 6T (Android 9)

**Comment by kbrosnan** [comment]
We don't keep issues open for individual extension. The API work should be tracked in Bugzilla.
