### ISSUE TITLE
FNX-5297 ⁃ [Bug] "Private Browsing Myths" link is broken

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#1868]
## Steps to reproduce
1. At Fenix home screen, tap the private browsing "mask" icon at top right.
1. Tap the "Common myths about private browsing" link at the end of the "You're in a private session" paragraph.

### Expected behavior
I should be taken to a functional support.mozilla.org page, probably this one or something like it:
https://support.mozilla.org/en-US/kb/common-myths-about-private-browsing

### Actual behavior
I end up at https://support.mozilla.org/1/mobile/1.0.1916/Android/en-US/private-browsing-myths which is 404

### Device information
* Android device: Q beta
* Fenix version: 1.0.1916 (68.0a1, built Saturday 4/20 12:19 PM)

CC @sblatz who worked on #510 which added this link

**Comment by sv-ohorvath** [comment]
Verified as fixed on 4/24 build

**Comment by dholbert** [comment]
Yup, fixed for me as well. Thanks everyone!
