### ISSUE TITLE
Evaluate perf impact of extractNativeLibs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18688]
Follow-up from https://github.com/mozilla-mobile/fenix/issues/18381

Historically, it was set to `false` by default but Android automatically changed it to `true` in recent versions. We changed it back to `false` because GV isn't set up to run with it. It's a possible perf win so we should run it through perftest to see what the impact is. If it's good, we should discuss making the change with the GV team.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10171)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807320

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
