### ISSUE TITLE
Allow users to disable search engine suggestions based on typed text

### ISSUE THREAD

**Issue by Jee-Hex** [mozilla-mobile/fenix#18685]
Regression from #16044.

As a matter of personal preference, I disable _Show search suggestions_, _Autocomplete URLs_, and _Show search engines_ because I want the user-agent to only connect to a search engine when I am explicitly searching for something. After #16044 every time I type _www._ into the address bar I get a brief flash of _Search Wikipedia - Search directly from the address bar_, which is more than annoying to say the least. Please consider putting this behind a pref so users can disable this feature should they wish to.

I would also like to point out that the spec for search engine suggestions seems to assume top toolbar. Tapping search engine suggestion for a one-time change may be too far away for users with a bottom toolbar.

### Device information

* Firefox for Android version: 
Nightly 210326 17:01 (Build #2015800971)
AC: 75.0.20210324143047, 0bc7edf4a
GV: 89.0a1-20210323094659
AS: 74.0.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10168)

**Comment by LaurentiuApahideanSV** [comment]
I will mark this as a feature request in regards to the ability to disable/enable search engine suggestions based on typed text.
The second issue brought up has been submitted here https://github.com/mozilla-mobile/fenix/issues/15863.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807720

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
