### ISSUE TITLE
[Bug] The dot from the scale overlaps the percentage number

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#18694]
### Steps to reproduce
1. From the device's settings, change the font size to the biggest option (extra large/huge).
2. Tap on 3 dot menu.
3. Open Settings.
4. Go to Accessibility and change the scale to a maximum (200%).
5. Observe the page.

### Expected behavior
No visual issues are displayed.

### Actual behavior
The dot from the scale overlaps the percentage number.

### Device information
Device vendor / model and Android version: Motorola Nexus 6 (Android 7.1.1)
Firefox for Android version: Latest Release 87.0.0-rc.1 and on the latest Nightly 210330 05:04 (GV89)

https://user-images.githubusercontent.com/48829350/112957972-a6fae500-914a-11eb-9882-7018f7cb62f3.png

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10174)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 94.0a1 (2021-09-27T05:10:46.748448).

Tested device: Motorola Moto e6 play with Android 9.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 100.0a1 (2022-03-28) build.
Device used: Motorola g6 (XT1925-5) with Android 8.0.0.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807126

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
