### ISSUE TITLE
"send tab to device" does not work to android firefox beta

### ISSUE THREAD

**Issue by DarkoVeberic** [mozilla-mobile/fenix#18705]
when sending a tab from a desktop firefox (could only test it with 87.0 version of firefox for ubuntu) to an android firefox beta 88.0.0-beta it does not appear instantly (like when sending in the other direction).

workaround: in android i have to go into firefox' settings > account > sync now for it to pop up...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10181)

**Comment by LaurentiuApahideanSV** [comment]
The issue has already been summited here: #https://github.com/mozilla-mobile/fenix/issues/16721. I will mark this issue as closed as it will be handled there.
