### ISSUE TITLE
[Bug][a11y] Reader mode "Appearance" control menu - Light mode contrast

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18709]
Related to #18708, #18710, #16387

## Steps to reproduce 
1. Have the Accessibility scanner installed and opened.
2. Go to a site with a lot of text content (e.g.wikipedia).
3. Enable "Reader view" from the navigation bar.
4. From the three-dot menu, tap on the "Appearance" menu.
5. Scan the "Appearance" control menu.

### Expected behavior
No suggestions are made.

### Actual behavior

Suggestions made for the **"Light"** button:
* Image contrast
[754,1668][859,1773]
The image's contrast ratio is 2.80. This ratio is based on an estimated foreground color of #AB71FF and an estimated background color of #EFEFF2. Consider increasing this ratio to 3.00 or greater. This item may be obscured by other on-screen content. Consider manually testing this item's contrast.

<img src="https://user-images.githubusercontent.com/40694158/98212539-6a84dd80-1f4c-11eb-804f-1327cf9ce92e.png" width="300" height="550" />

### Device information
* Android device: Google Pixel (Android 10)
* Fenix version: 11/3 Nightly build

**Comment by Apurwa96** [comment]
Hi, I am an outreachy applicant and This is my first time contributing to opensource, let me know if I can work on this.

**Comment by 318anushka** [comment]
Is it okay if i take up this issue?

**Comment by eliserichards** [comment]
Hi @Apurwa96! You can pick this up. You should start looking in https://github.com/mozilla-mobile/android-components/blob/1d1753abba4d29ad3e91c16d0c751db7cdbd639d/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt#L78 in the [Android Components](https://github.com/mozilla-mobile/android-components) repo

**Comment by Apurwa96** [comment]
I tried to reproduce and Accessibility Scanner didn't find any suggestion (Android device: OnePlus7T & OPPO A5 (Android 10)
Fenix version: 4/7 Nightly build).  

 In android-components\components\feature\readerview\src\main\res\values\colors.xml 
readerview_text_color : #220033, readerview_light_background: #EFEFF2, readerview_selected: #592ACB 

color #AB71FF is not present in the code.
