### ISSUE TITLE
FNX-5299 ⁃ [Bug] Copy bookmark folder does nothing

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1870]
## Steps to reproduce
1. Create bookmark folder inside of the root folders (inside of mobile or menu, for example). The only way to do this is to edit an existing bookmark and to create a new folder from within the edit folder UI
1. Navigate to parent folder of bookmark folder created in step 1
1. Tap 3 dot menu and select "Copy"

### Expected behavior
Unsure. "Copy" might mean the first step of a copy and paste operation, which makes the most sense in this context. 

Ideally, this would be replaced by a "Move" feature. I've logged one at:  #1869

### Actual behavior
Nothing happens. 

### Device information
* Android device: 2
* Fenix version: latest

**Comment by sv-ohorvath** [comment]
Verified as fixed on master build 5/2.
