### ISSUE TITLE
[Bug] Selected tab loses selected state

### ISSUE THREAD

**Issue by Halmex** [mozilla-mobile/fenix#18701]
## Steps to reproduce
Start loading a webpage, open tab list and select the tab before the webpage is fully loaded.

### Expected behavior
The selected tab stays selected. 

### Actual behavior
The loaded tab is again selectable, so the one tab can be added multiple times to the selected tabs list.

### Device information

* Device vendor / model and Android version: Xiaomi Redmi Note 5 Pro, Android 10
* Firefox for Android version: Beta 88.0.0-beta.2 and Nightly 210329 17:00

**Comment by sflorean** [comment]
I was able to reproduce this issue with Xiaomi Redmi Note 8T (Android 9) on all builds: Nightly, Beta, RC. Following the steps I have "2 selected", but only 1 tab open.

**Comment by TrianguloY** [comment]
Please see this issue https://github.com/mozilla-mobile/fenix/issues/14954 for more details about the bug and a possible cause.

**Comment by amedyne** [comment]
Closing  this one to track #14954
