### ISSUE TITLE
FNX-486 ⁃ [Bug] Context menus across app are too wide (like Bookmarks)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1871]
## Steps to reproduce
1. Open Library > Bookmarks
1. Open context menu next to a bookmark

### Expected behavior
Narrower menu that shows menu items without looking oddly wide. 

Fennec and Kiwi look neater:

![fennec-bookmark-menu](https://user-images.githubusercontent.com/152493/56474302-2bfd0000-6446-11e9-8836-06d7ec6e1310.png)

![kiwi-bookmark-menu](https://user-images.githubusercontent.com/152493/56474301-299aa600-6446-11e9-9cf0-182fae295c9b.png)

### Actual behavior
Menu looks too wide. 

![fenix](https://user-images.githubusercontent.com/152493/56474290-e2acb080-6445-11e9-84f0-75209de0d94a.png)

### Device information
* Android device: Pixel 2
* Fenix version: latest play store

**Comment by liuche** [comment]
This has already taken a lot of work, and isn't worth continuing bc of eng effort for ROI.

**Comment by sblatz** [comment]
My WIP PR: https://github.com/mozilla-mobile/android-components/pull/3714

**Comment by vesta0** [comment]
@liuche is this still too much ENG work (narrowing the BOOKMARK context menu)? If so, please comment and close this.

**Comment by liuche** [comment]
@sblatz @ekager I assume the difficulty here hasn't changed much, and it's still hard to handle dynamically sizing (or shrinking) the context menus in AC?

**Comment by ekager** [comment]
cc @Mugurell it looks like you landed something in AC that could help with this?

**Comment by Mugurell** [comment]
Thanks Emily!

Indeed, I recently added support for dynamic width menus in A-C (https://github.com/mozilla-mobile/android-components/issues/6499) but using only xml set values.
The next step would be to add runtime values support, should be fairly easy.

For this ticket we would just need to know a min/max width for the menu.
I guess 
- min would be let's say 10dp (as small as possible)
- max would be 250dp (I think what it is now)

?

The menu will have a dynamic width between this values, it will be as narrow as the widest menu action.

**Comment by ekager** [comment]
Sounds good to me! As long as it's adjusting to the widest menu item doesn't really matter what the min is 👍

**Comment by Mugurell** [comment]
Having the possibility of setting a min/max size for each menu is definitely nice.
Based on also what Emily said above I was thinking that maybe we should make it as a default for all menus to be as small as their widest item.
Currently all menus can have between 250dp-314dp width. Should we by default allow for even a smaller width?

**Comment by topotropic** [comment]
Would be great to align to an 8dp grid and follow material guidelines where the minimum width is 112dp and max width is 280dp.

**Comment by liuche** [comment]
This is still important to Vesta, but it's too much work before Release.

**Comment by Mugurell** [comment]
I think I might have an easy solution following the recent https://github.com/mozilla-mobile/fenix/issues/7157 and the UX directions from:
- https://github.com/mozilla-mobile/fenix/issues/10541#issuecomment-635147257 & https://github.com/mozilla-mobile/fenix/issues/7157#issue-537777448 - Maximum width: 314 dp while also ensuring a minimum 48dp tappable “exit area” available whenever the menu is open.
- https://github.com/mozilla-mobile/fenix/issues/1871#issuecomment-638842210 - minimum width is 112dp.

The menu width should be dynamic between this constraints, wrapping it's content.

**Comment by SS1113** [comment]
@Mugurell I think I'm somewhat late to report my comments now since there're some commits that have already been added, but can you please take a look at my comment on the issue #11716. I think the **three-dot menus** on the **bottom navigation tray** and the menu at the **new Tabs Tray** should be **reverted** to the previous state.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 6/19 with Sony Xperia Z5 Premium (Android 7.1.1), and OnePlus 5T (Android 9).
The context menus, three-dot menus, bookmark menus are dynamic, adjusting to it's content.

![Sony-context menu](https://user-images.githubusercontent.com/40694158/85133719-ea333980-b243-11ea-80c9-0981cfec64c4.png)
![Sony-bookmark menu](https://user-images.githubusercontent.com/40694158/85133728-edc6c080-b243-11ea-9916-881f437bb80d.png)
![Sony menu](https://user-images.githubusercontent.com/40694158/85133740-f0c1b100-b243-11ea-81a8-b34eaa97713e.png)
![OnePlus-menu](https://user-images.githubusercontent.com/40694158/85133746-f4edce80-b243-11ea-9f51-9ee23c8eb68d.png)
