### ISSUE TITLE
get firefox Android from somewhere really "free", NO GOOGLE PLAY;

### ISSUE THREAD

**Issue by SmallPackage** [mozilla-mobile/fenix#18718]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I can no longer easily download firefox android version directly from downlaod.mozilla.org

### How do you know that this problem exists today? Why is this important?
Yes, I could use play store doing that even esasier, but I just dont want;
So in that case, I'm asking for AOSP release for ORDINARY USER;
At present, AOSP users would have to dig into github, or FTP server to get their copy;

### Who will benefit from it?
Everyone, really careabout "independent" Internet, but dont dig that deep;

**Comment by LaurentiuApahideanSV** [comment]
You can download any version of Fenix from https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix, the latest release can be found here: https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.release.latest. Let me know if you have further issues.

**Comment by pocmo** [comment]
Builds are available from the links above as well as the releases page on GitHub:
https://github.com/mozilla-mobile/fenix/releases

Additionally there's a build available from fdroid (which is not maintained by Mozilla):
https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/
