### ISSUE TITLE
FNX-5300 ⁃ [Bug] new tabs open from Twitter don't appear in the foreground

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#1872]
## Steps to reproduce
* Have Fenix as your default browser.
* Open a Twitter link.

### Expected behavior 
* Maybe open a custom tab, or at least open Fenix with the new tab in the foreground.

### Actual behavior
* The tab is open, but is not in the foreground.

There is another Twitter issue about not opening as a custom tab, but this probably affects other apps that don't use CCT.

### Device information
* Android device: OnePlus 6
* Fenix version: 1.0.1916

**Comment by ekager** [comment]
I think this is no longer an issue. Please reopen if it is.
