### ISSUE TITLE
Smash the field.

### ISSUE THREAD

**Issue by A3148475824** [mozilla-mobile/fenix#18723]
The first point: search speed, search speed is too slow, I do not know, alas, do not understand. It's very slow and full, one card at a time, not smooth at all.
The second point: video broadcast you this is too simple, can not provide one? For example, suspension playback, video download, clarity adjustment, gesture provocation brightness and sound volume.All videos can be downloaded as long as they can be played and automatically transcoded to MP4.
Number three: can't you improve the download channel? I'm really convinced.Long press the file can not change the format? Can't you send the file? Can't there be a private passage? Can't you see the speed of downloading? Can not interrupt the download?
The fourth point: no reading mode? Read the novel is not uncomfortable? Can not come to a? Can not change the font? Can not can not typesetting? Can not change the background? Not allowed.
The fifth point plug-in: Don't you directly support plugins in all Google stores? The plugin in Google Store does not support even if the plugin in Firefox can't use it, even if you can't use it, you can translate it all into Chinese.Plug-in is too little, it is only forty or fifty, useful also that a few.
Sixth point: Do you not support import and export? I really worked. Can the password cannot be imported? Can you pour the password above the Google's browser on the Android phone? I…………
I Don't want to talk about It. the cell phone is running out of power.

**Comment by A3148475824** [comment]
Don't ask me why you read it so awkwardly that it doesn't even make sense. Because I translated it directly by iFLYTEK.

**Comment by LaurentiuApahideanSV** [comment]
Please submit a bug report/feature request separately for each of the problems you encountered along with a clear description of the issue, steps in order to reproduce it and any further information that might help us, such as the device model and firmware that you are using and the version of Firefox.
