### ISSUE TITLE
[Bug][PiP] The media buttons are still displayed when opening a new blank page in PiP

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#18727]
## Steps to reproduce
1. Open a YT video on full screen and tap on the recent apps button.
2. The PiP is displayed and the video is running without issues.
3. Long tap on the Fenix icon and select `New tab or New Private tab`.
4. Note that the tab is opened but the media buttons are still displayed and the video can be controlled even tho it is not displayed.
### Expected behavior
Media buttons should not be displayed on the newly opened tab in PiP.
### Actual behavior
The media buttons are still displayed when opening a new blank page in PiP
### Device information

* Device vendor/model and Android version: **Google Pixel 4 XL (Android 11)**
* Firefox for Android version: **Nightly 3/31/21.**

https://user-images.githubusercontent.com/42831109/113163998-5fa74e00-9249-11eb-8c18-f70f45c50ecf.mp4

**Comment by Mugurell** [comment]
The media buttons are not controlled by us but by the framework. They are standard for PIP which should only be used for media.

Since the user is opening a new tab I think the expected result is for the app to exit PIP and open a new tab in the fully shown application, tab that can be interacted with.
Like it would happen when while in PIP users tap on a link to open in Fenix.

Asking for UX's confirmation about the expected result.

**Comment by topotropic** [comment]
Thanks! The new tab opened for me in the tiny PIP window... not useful. I agree with @Mugurell's proposal: exit PIP and open new tab in fully shown application.

**Comment by czlucius** [comment]
May I work on this issue?

**Comment by czlucius** [comment]
I think the activity needs to be expanded/exit PiP mode when the various entry points are launched:
- Notifications
- Links
- App shortcuts

There are much more entry points, but I think every way of launching the apps use `Intent`, which is handled by `IntentRecieverActivity`.

Hence, we can just add `intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)` to `IntentReceiverActivity` in the `processIntent()` method. (https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt) 

Something like this:
```kotlin
if (isInPictureInPictureMode()) {
     intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)
}
```

**Comment by Mugurell** [comment]
I agree this probably needs a solution in `IntentReceiverActivity`.
But not sure `intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)` will give us the result needed.

The app mainly relies on [`FullScreenFeature`](https://github.com/mozilla-mobile/android-components/blob/bfaf514793dd20f9f12d3f551f9ff3e470f52727/components/feature/session/src/main/java/mozilla/components/feature/session/FullScreenFeature.kt) and [`MediaSessionFullscreenFeature`](https://github.com/mozilla-mobile/android-components/blob/bfaf514793dd20f9f12d3f551f9ff3e470f52727/components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt) to handle screen rotation, immersive mode and other UI properties for fullscreen videos on/off. We probably need a way to get the same to happen here.

**Comment by czlucius** [comment]
According to https://stackoverflow.com/a/43288507/12204281, launching an intent to the desired activity with flag `Intent.FLAG_ACTIVITY_REORDER_TO_FRONT` will cause it to exit PiP.

**Comment by Mugurell** [comment]
> According to https://stackoverflow.com/a/43288507/12204281, launching an intent to the desired activity with flag `Intent.FLAG_ACTIVITY_REORDER_TO_FRONT` will cause it to exit PiP.

And after exiting PIP we need to switch from playing a fullscreen video in a tab to loading a new website in another tab.
Before entering PIP a video had to be played in fullscreen, this triggering many changes to the app (see [here](https://github.com/mozilla-mobile/fenix/blob/0acd776f467692e39165b7d222beaa970c7c7fe6/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L1293-L1315)). All these have to be rolled back and the up-to-date device orientation must be set before navigating to another website.

**Comment by czlucius** [comment]
Is this already handled in `pipModeChanged()` ([here](https://github.com/mozilla-mobile/fenix/blob/0acd776f467692e39165b7d222beaa970c7c7fe6/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L1271-L1276)), which calls `fullScreenChanged(false)` ([here](https://github.com/mozilla-mobile/fenix/blob/0acd776f467692e39165b7d222beaa970c7c7fe6/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L1317-L1325)) which executes the necessary code to exit PiP (including calls to `initializeEngineView()`)?
Thanks.

**Comment by Mugurell** [comment]
@czlucius Trying out the proposed 
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && isInPictureInPictureMode) {
            intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)
}
```
in `IntentReceiverActivity` I see the issue still exists.

I think this is because `isInPictureInPictureMode` verifies the pip status for the current activity - `IntentReceiverActivity` while the one in pip is actually `HomeActivity`. In which case this requires more investigation of possible approaches.

You can open a PR with your proposed changes and we can look from there if the issue is fixed or needs more work.

**Comment by czlucius** [comment]
I managed to solve the issue by adding this:
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && isInPictureInPictureMode) {
            moveTaskToBack(false)
            intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)
}
```
in the `onCreate` method of `HomeActivity`.
However, I do not think this is a good solution, as other activities that are launched will not exit PiP
Are there other activities in this app apart from the `HomeActivity` that have a user interface?

**Comment by czlucius** [comment]
> @czlucius Trying out the proposed
> 
> ```
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && isInPictureInPictureMode) {
>             intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)
> }
> ```
> 
> in `IntentReceiverActivity` I see the issue still exists.
> 
> I think this is because `isInPictureInPictureMode` verifies the pip status for the current activity - `IntentReceiverActivity` while the one in pip is actually `HomeActivity`. In which case this requires more investigation of possible approaches.
> 
> You can open a PR with your proposed changes and we can look from there if the issue is fixed or needs more work.

Do I open the PR from here?

**Comment by Mugurell** [comment]
> Do I open the PR from here?
 
 - Create a commit with the proposed changes on a local branch created from the current Fenix master
 - Push that to your fork
 - You'll now have an option to create a pull request 
 - Choose to create a PR against Fenix's master.
 
 Ensure you're also following the official recommendations - https://github.com/mozilla-mobile/fenix#i-want-to-open-a-pull-request

**Comment by czlucius** [comment]
Thanks

**Comment by czlucius** [comment]
I managed to fix the issue, but I an unaware on other activities with a user facing UI.

With the suggestion I said in HomeActivity, the PiP exits after an intent is launched, but when the user returns to the original tab, the following happens. As seen, a dialog opens as if full screen mode is turned off.
![Screenshot_20210726-213721_Firefox Preview.jpg](https://user-images.githubusercontent.com/58442255/127124656-14bbc46b-99ca-4006-b951-096fff219f1f.jpg)

**Comment by czlucius** [comment]
May I ask what tests I need to write? 
Thanks.

**Comment by czlucius** [comment]
I have checked the source code, and it appears that there are only 3 user-facing activities with a UI, which are:
- The HomeActivity (main activity)
- activity_migration (Migration activity, calls ˋfinish()ˋ after migration is done) (where is this called from though?)
- activity_privacy_content_dialog (I do not know what is the purpose of this activity)

The other activities are all not user-facing, hence PiP won't be an issue with them.
Hence, the solution in ˋHomeActivityˋ seems like it will work, as there are no other activities that will be launched (still in PiP mode after an intent)

**Comment by Mugurell** [comment]
@czlucius Thank you for pushing through with this.
Left a comment on the PR. If it looks good from a performance standpoint we can merge it.

**Comment by czlucius** [comment]
Also something related, but not under this issue:
While I was testing, I noticed that PiP did not exit when the video finished.
Should I file it as a new issue?

**Comment by Mugurell** [comment]
> Also something related, but not under this issue:
> While I was testing, I noticed that PiP did not exit when the video finished. (No blank page is launched from external sources.)
> Should I file it as a new issue?

We already have a ticket filed for this - https://github.com/mozilla-mobile/fenix/issues/20280 though it's an older issue which needs better support in GeckoView and at the moment it's unclear when and how will it be fixed.

**Comment by czlucius** [comment]
Ok
