### ISSUE TITLE
[Bug] Changing device language does not change notifications locale if Fenix was already opened.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#18726]
Following up on  https://github.com/mozilla-mobile/fenix/issues/17168#issuecomment-810900261.

STR:

1. Open Fenix
2. Set language setting to follow device language.
3. Keep the app in the background
4. Set the language of the device to German (or another language)
5. Return to the app
6. Download a file or open a new private tab (or any action that displays a notification)
7. Observe the notification.

Expected result: Notification is translated into German.

Actual result: The notification is in the previous device language. 

Note: Might be related to https://github.com/mozilla-mobile/fenix/issues/17190, maybe @eliserichards has more insight.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the following builds: latest Nightly (Build 210407 05:01), Nightly (Build 210331 17:00) - the build from the day the issue was logged on, and the Firefox Daylight v87.0.0-rc.1 (Build #2015799099) using a HTC Nexus 9 with Android 7.1.1

**Comment by codrut-topliceanu** [comment]
Unable to reproduce on Pixel 4 (Android 11)

**Comment by codrut-topliceanu** [comment]
Was able to reproduce with these steps :

1. Open Fenix
2. Set language setting to follow device language.
3. Download a file or open a new private tab (or any action that displays a notification)
4. Keep the app in the background
5. Set the language of the device to German (or another language)
6. Return to the app
7. Observe the notification.

- Expected result: Notification is translated into German.

- Actual result: The notification is in the previous device language.
