### ISSUE TITLE
[Bug] PointerEvent.pointerType is set to touch despite using pen/stylus

### ISSUE THREAD

**Issue by H-M-H** [mozilla-mobile/fenix#18749]
## Steps to reproduce
Register an event handler for example for `onpointermove` and observe `PointerEvent.pointerType` of the event.

### Expected behavior
`pointerType` should be `pen`.

### Actual behavior
`pointerType` is `touch`.

### Device information
* Device vendor / model and Android version: Onyx Boox Note 2
* Firefox for Android version: 87.0.0-rc.1 (Build #2015799099)

### Other information
`pointerType` is set correctly using Chrome.

**Comment by Mugurell** [comment]
Thank you @H-M-H !
Will move this ticket to Bugzilla where discussions around GeckoView's development are taking place.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1702482

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
