### ISSUE TITLE
Resize the top site items

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#18742]
Figma: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=809%3A1

| Element | Theme | Current | Proposed |
| --- | --- | --- | --- |
| Shortcut tile background | Both | 40×40 | 60×60 |
| Shortcut tile favicon | Both | 32×32 | 36×36 |

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 210413.

### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)
