### ISSUE TITLE
Restoring session to CNN seems slower on Nightly than Release (for COLD MAIN start up)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18741]
csadilek anecdotally noticed on their Pixel 3a that restoring a session (when clicking the homescreen icon) to cnn.com was slower on Nightly than it is on Release (Beta seemed to be like Nightly).

csadilek took profiles and there appears to be a ~1.5s difference from when the first web content appears in the screenshots:
- Nightly (slower): https://share.firefox.dev/3sHeIhp
- Release: https://share.firefox.dev/3wdLOYt

We should find the root cause. I took profiles locally on my Pixel 2 and found similar results:
- Nightly: https://share.firefox.dev/3wgCROc
- Release: https://share.firefox.dev/3rCGXwn

**Comment by mcomella** [comment]
To determine if this regression is real, we could run performance tests (perftest VIEW?) on a each of these builds to see if there's a difference.

**Comment by mcomella** [comment]
acreskey filed a significant COLD page load regression as https://bugzilla.mozilla.org/show_bug.cgi?id=1697218 23 days ago – I wonder if these are the same issue.

**Comment by mozkeeler** [comment]
Can you recapture those profiles with the socket thread and ssl threads included? Thanks!

**Comment by mozkeeler** [comment]
To be able to tell, I'll need the "SSL" threads, not DNS threads - thanks!

**Comment by mcomella** [comment]
Triage: csadilek is not able to reproduce anymore. We'll reopen if we see this again.
