### ISSUE TITLE
Change text styles and colours of the top site items

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#18743]
Figma: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=809%3A1

## Text styles

| Element | Current | Proposed |
| --- | --- | --- |
| Shortcut tile label size | 10dp | 12dp |

## Colours

| Element | Theme | Current | Proposed |
| --- | --- | --- | --- |
| Shortcut tile label | Light | `Dark Grey 10` `#52525e` | Same as other texts `Dark Grey 90` `#15141a` |
|  | Dark | `Light Grey 60` `#afafba` | Same as other texts `Light Grey 05` `#fbfbfe` |

**Comment by sheikh-azharuddin** [comment]
It looks weird...top site text
Big and ugly

![Screenshot_20210409-155830816](https://user-images.githubusercontent.com/58127841/114167352-7554fb80-994c-11eb-8cc0-95bc122322db.jpg)
