### ISSUE TITLE
 New Tab Page stretch goal: recolour backgrounds

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#18744]
Figma: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=809%3A1

| Element | Theme | Current | Proposed |
| --- | --- | --- | --- |
| New Tab Page background | Light | `Light Grey 10` `#f9f9fb` | No change |
|  | Dark | `Dark Grey 80` `#1c1b22` | `Dark Grey 60` `#2b2a33` |
| Shortcut Tile background | Light | `white` | No change |
|  | Dark | `Dark Grey 50` `#32313c | `Dark Grey 30` `#42414d` |

**Comment by kglazko** [comment]
Hi @brampitoyo, in making these changes in this PR https://github.com/mozilla-mobile/fenix/pull/19009/files I realized that the background color of the New Tab Page Background is actually defined by `foundation_dark_theme` which affects more components than just the New Tab Page background. In talking to @gabrielluong he suggested this could be a difficult change from a UX perspective as it affects other pages such as settings pref and more. Not sure if this is something you've already looked into and want to make this as a blanket change. I can also remove the change to the New Tab Page Background and just land this issue with the new tile colors. Let me know!

**Comment by gabrielluong** [comment]
Spoke with @brampitoyo, we don't want to make the New Tab Page background change right now since it will affect multiple components that have not been investigated yet. Let's do it in the future. Since we aren't doing new tab page background change, we won't make the change for the tile background color as well. We are closing this and will file a new issue in the future when we want to tackle this together.

**Comment by brampitoyo** [comment]
@gabrielluong @kglazko Confirming this.

By the first look, the colour change doesn’t seem to that drastic:

- Foundation/base colour (includes New Tab Page background): `Dark Grey 80` `#1c1b22` → `Dark Grey 60` `#2b2a33`
- Above colour (includes Shortcut Tile background): `Dark Grey 50` `#32313c`→| `Dark Grey 30` `#42414d

On one hand, changing the global `foundation` and `above` colour values will impact many surfaces (not just New Tab Page) and introduce corner case issues.

On the other hand, changing the colour values only on the New Tab Page will require us to make a ‘mental note’ for this special exception going forward.

So, let’s not alter any background colour for now, and wait until MR2 to introduce a larger set of changes.
