### ISSUE TITLE
Local nightly builds are faster than released builds: why?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18753]
I did some performance tests on my Moto G5:
- perftest release: 2489.5ms
- perftest nightly local: 2030.5ms
- perftest nightly download: 2327.0ms
- first-frame VIEW release: 1750ms
- first-frame VIEW nightly local build: 907ms
- first-frame VIEW nightly download: 1771.5ms

My local nightlies are significantly faster than the released nightlies and release builds. Curiously, this occurs for both code bottlenecked on the JVM (first frame) and primarily Gecko (perftest to navStart).

We should find out why this is happening.

Here are some profiles:
- Release: https://share.firefox.dev/31AZTRK
- Local nightly: https://share.firefox.dev/31DfKiD

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10214)

**Comment by mcomella** [comment]
Is proguard disabled in release builds? `AppOpsManagerCompat` calls are missing. Check new profiles.

**Comment by mcomella** [comment]
I ran a local build & the latest nightly build (06-07) through `measure_start_up` and see similar behavior:
- `cold_main_first_frame` regresses 80ms on release
- `cold_view_nav_start` regresses 104ms on release
- (this is the only test that was run in the original comment) `cold_view_first_frame` regresses 88ms on release

The regressions we see aren't as extreme as the previous regressions we saw in the original comment https://github.com/mozilla-mobile/fenix/issues/18753#issue-848660165 of 300-800ms and might be attribute to some SDK that I don't have. The local builds have gotten much closer to the release builds (e.g. now 1580 instead of 907). This leads to two questions:
- Were we actually seeing such fast behavior before? If so, what changed? Could there be a perf win to be found?
- (the original question) Why are local builds faster than release builds?

**Comment by mcomella** [comment]
> Were we actually seeing such fast behavior before? If so, what changed? Could there be a perf win to be found?

I took a measurement on a local build from 04/01 (when we first filed this issue though tbf the build I originally used may have been older) and I can't reproduce the extremely fast behavior (900ms): I got 1610ms with the current script view_ff & 1607ms with the old script, medians, which is similar to what we measure today (1580 local build).

I imagine the extremely fast times I measured was a fluke – perhaps I accidentally took the measurement on a P2 or something.

> (the original question) Why are local builds faster than release builds?

Given the wins are much smaller now and likely due to a missing SDK, we should spend less time on this than we would have otherwise.

**Comment by mcomella** [comment]
I took some profiles:
- local nightly profiles 5ms sampling: https://share.firefox.dev/3pwfPjx
  - 1ms sampling: https://share.firefox.dev/2Rz2dY8
- 2 06/07 nightly profiles 5ms sampling: https://share.firefox.dev/3crGKHT and https://share.firefox.dev/3pwkvWD
  - 1ms sampling: https://share.firefox.dev/34WRARX

So far, I haven't found any large differences between them – just a few samples here or there with no consistent pattern.

The obvious difference would be enabled SDKs. There are 3 SDKs that are printed when building: adjust, nimbus, & MLS. I have adjust enabled and don't have the other two enabled. However, nimbus takes the same time in both builds & MLS didn't add much (it was 1 sample before but now I can't find it, suspicious). **It's possible an SDK is running before the profiler starts** – Firebase push is one thing that stands out to me. We could figure this out with a micro-benchmark (e.g. compare `FenixApplication.onCreate - navStart` instead of proc start).

It's also possible we're slightly slower in the nightly production builds because the system is taking profiles to boost subsequent start ups (see this [Profiling in the Cloud article](https://android-developers.googleblog.com/2019/04/improving-app-performance-with-art.html)). With `macrobenchmark`, I think you can control this state so that's a way we could measure that. However, the nightly builds I'm using are not distributed via GPlay so perhaps they're not using this functionality.

**Comment by mcomella** [comment]
> It's possible an SDK is running before the profiler starts – Firebase push is one thing that stands out to me. We could figure this out with a micro-benchmark (e.g. compare FenixApplication.onCreate - navStart instead of proc start).

I got a few times:
- proc_start to first `GeckoThread.*runGecko` log (I assume this is when gecko is started): 26ms slower in nightly
- first `GeckoThread.*runGecko` to nav start: 45ms slower in nightly

I believe the benefit of this separation is that we can see if the slowdown comes in the code before the profiler starts. While I don't know the exact point that that line runs (I guess ~400ms into the profile which should be sometime in `FenixApplication.onCreate`), it seems like the slowdown is both before and after the start. It seems unlikely that it's just some SDK init that's creating the additional slowdown.

**Comment by mcomella** [comment]
I have additional notes in [my working document](https://docs.google.com/document/d/1a7UwtmIHG_RC6aEKa9hL_ApO-nzKm_g9SQIcZhvDdKs/edit?usp=sharing).

**Comment by mcomella** [comment]
I was able to reproduce this behavior again in the 7/20 build of nightly compared to 2040af6a5 in fenix (2763ms median locally & 3227ms from Nightly). This was found during this investigation: https://github.com/mozilla-mobile/fenix/issues/20934#issuecomment-904213270

**Comment by mcomella** [comment]
Could this be related to the start up cache? I think I cleared data for the app though before I took the additional measurements...

**Comment by mcomella** [comment]
We looked into this during the Joy of Profiling: when we ensured the local build and the nightly build used the same version of GeckoView, the main difference is that the nightly build took longer in `parseManifest` – our web extensions init code. We've addressed a regression in this code in https://github.com/mozilla-mobile/fenix/issues/20934 so it's possible we won't see the discrepancy between local and nightly again. We should try to reproduce this again with newer builds.

**Comment by mcomella** [comment]
> It's also possible we're slightly slower in the nightly production builds because the system is taking profiles to boost subsequent start ups (see this [Profiling in the Cloud article](https://android-developers.googleblog.com/2019/04/improving-app-performance-with-art.html)). With macrobenchmark, I think you can control this state so that's a way we could measure that. However, the nightly builds I'm using are not distributed via GPlay so perhaps they're not using this functionality.

We can add baseline profiles to our local build to get similar performance to Google Play: see #25259.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807321

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
