### ISSUE TITLE
FNX-5301 ⁃ [Bug] Line appears in custom tabs

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#1875]
## Steps to reproduce
1. Open a link in a Fenix custom tab

### Expected behavior
no line at bottom of screen.

### Actual behavior
Line at bottom of screen. 

I suspect this is due to https://github.com/mozilla-mobile/fenix/commit/316569b89917f6724422a7624c073e8e6c615743

![signal-attachment-2019-04-22-002129](https://user-images.githubusercontent.com/152493/56484707-f46e7200-649e-11e9-8eb6-21150cb49992.png)

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by mauryat** [comment]
@ekager can I work on this one?

**Comment by vesta0** [comment]
FIXED.

**Comment by sv-ohorvath** [comment]
Verified as fixed. Build 4/24
