### ISSUE TITLE
[Bug] Top site design gets broken on >8 icons

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18754]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Have more than 8 top site
Swipe between pages

### Expected behavior
Layout not getting broken
### Actual behavior
Second page layout gets shrunken (not every time, you should try some)
Also there is some unresponsiveness to touch as you can see in recording

https://user-images.githubusercontent.com/17825767/113347548-fc4b1800-933d-11eb-89fb-d5c965c8cd2f.mp4

### Device information

* Device vendor / model and Android version: Xperia XZ1 Android 11
* Firefox for Android version: 3/31 nightly

**Comment by ebalazs-sv** [comment]
I can reproduce this issue on Nightly 4/1, Beta 88.0.0-beta.3, RC 87.0.0-rc.1 with Samsung Galaxy Tab S3 (Android 8).

**Comment by lobontiumira** [comment]
The steps to reproduce the issue 100% are:
1. Make sure you have the most visited sites toggle enabled.
2. Browse a few pages, so that the top sites area is full.
3. From the homescreen, tap the private mode icon.
4. Tap again the private mode icon in order to return to the normal browsing homescreen.
5. Long-tap one of the top sites tiles, and select to "Delete from history".
6. Swipe to the second page of the top sites tiles, and observe the layout.

**Comment by kbrosnan** [comment]
@ebalazs-sv or @lobontiumira do you still see this on Nightly with the top site redesign? From a quick check I don't see this with the Proton UI.

**Comment by SeburoSUMO** [comment]
If it helps, I am not seeing it on my own device (current Nightly).  Could it be linked to specific devices?

**Comment by hakkikaancaliskan** [comment]
Looks like issue fixed for me too

**Comment by lobontiumira** [comment]
Verified as fixed on the 5/24 Nightly build with Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
