### ISSUE TITLE
[Bug] Default browser notification spam

### ISSUE THREAD

**Issue by danielzgtg** [mozilla-mobile/fenix#18757]
I am annoyed by Firefox constantly asking whether it wants to be the default browser. I have no default browser set so that accidentally tapping on ads doesn't take me out of the app I'm in.

## Steps to reproduce

1. Don't set any default browser
2. Wait one week

### Expected behavior

Upon dismissing the notification three times, it should not appear again.

### Actual behavior

It feels like I get this notification every week! It always says "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online."

This is getting annoying. No, I don't want to set ANY browser as the default. I want the selector to pop up when I accidentally tap on an ad. This way, I can just press back and not lose my place in the app I'm in.

### Device information

* Device vendor / model and Android version: OnePlus / 7 Pro and OP&Pro_O2_BETA _4 Android 11
* Firefox for Android version: `Nightly 210331 17:00 (Build #2015801931)`

**Comment by Mugurell** [comment]
This is a Leanplum campaign though the one that I'm seeing at is set to be sent only once.
We should recheck the running campaigns. @amedyne

**Comment by amedyne** [comment]
@Mugurell Thanks for tagging me for this. I'll check with the team regarding this campaign.

**Comment by ItsDevyani** [comment]
Hello Migurell and Amedyne,

We have one default browser campaign in Nightly (https://www.leanplum.com/dashboard2/4828751897952256/composer/1445605038/goals) and one in Release (https://www.leanplum.com/dashboard2/5957278171136000/composer/1450725166/goals). As you pointed out,  They are set up to send the notifications one time only per unique user so I'm confused by "it feels like I'm getting the notification every week" Please take a look and let me know how to proceed. If the user has both Nightly and Release on their device, at most they may have received the message twice, one each. It's also interesting that this user (also probably others) doesn't understand that if they don't choose a default browser Chrome is their default browser by default :)

**Comment by amedyne** [comment]
@danielzgtg 

Thank you for your feedback. We hear you, sometimes notifications can feel disruptive. We'd like to clarify a few things. When you do not 'actively choose' a default browser, most Android devices pre-select Chrome as your default browser. 
The notification you received has been programmed to inform new Nightly users just once about the fact that they can have a choice in default browsers. We do not send this message again to someone who has already received it. We can investigate further what has led to you receiving this message several times, if, you are okay with sharing a little bit more information. 

Additionally, we would like you to know that Firefox seldom sends notifications. If you want, you can opt out of notifications from the Settings menu in the Firefox App.

**Comment by danielzgtg** [comment]
> most Android devices pre-select Chrome as your default browser

I purposefully unset Chrome as the default browser in settings soon after I set up the device. I see the browser selection menu when I click on a link, not Chrome

**Comment by danielzgtg** [comment]
Here are notifications logged in `org.hcilab.projects.nlog` filtered by `.text.startsWith("You can't")`:

```javascript
[
  {
    packageName: 'org.mozilla.fenix',
    postTime: 1616000350368,
    systemTime: 1616000350589,
    offset: -14400000,
    version: 16,
    sdk: 30,
    isOngoing: false,
    isClearable: true,
    when: 1616000350367,
    number: -1,
    flags: 16,
    defaults: 0,
    ledARGB: 0,
    ledOn: 0,
    ledOff: 0,
    ringerMode: 0,
    isScreenOn: true,
    batteryLevel: 89,
    batteryStatus: 'discharging',
    isConnected: true,
    connectionType: 'wifi',
    hasAppointment: false,
    isGroupSummary: false,
    actionCount: 0,
    isLocalOnly: false,
    people: 0,
    style: 'android.app.Notification$BigTextStyle',
    tickerText: '',
    title: 'Firefox Nightly',
    titleBig: '',
    text: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textBig: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textInfo: '',
    textSub: '',
    textSummary: '',
    appName: 'Firefox Nightly',
    priority: 0,
    nid: -468413663,
    key: '0|org.mozilla.fenix|-468413663|null|10641',
    visibility: 0,
    color: 0,
    interruptionFilter: 1,
    listenerHints: 0,
    matchesInterruptionFilter: true
  },
  {
    packageName: 'org.mozilla.fenix',
    postTime: 1616325839264,
    systemTime: 1616325839477,
    offset: -14400000,
    version: 16,
    sdk: 30,
    isOngoing: false,
    isClearable: true,
    when: 1616325839262,
    number: -1,
    flags: 16,
    defaults: 0,
    ledARGB: 0,
    ledOn: 0,
    ledOff: 0,
    ringerMode: 0,
    isScreenOn: true,
    batteryLevel: 21,
    batteryStatus: 'charging',
    isConnected: true,
    connectionType: 'wifi',
    hasAppointment: false,
    isGroupSummary: false,
    actionCount: 0,
    isLocalOnly: false,
    people: 0,
    style: 'android.app.Notification$BigTextStyle',
    tickerText: '',
    title: 'Firefox Nightly',
    titleBig: '',
    text: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textBig: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textInfo: '',
    textSub: '',
    textSummary: '',
    appName: 'Firefox Nightly',
    priority: 0,
    nid: -468413663,
    key: '0|org.mozilla.fenix|-468413663|null|10641',
    visibility: 0,
    color: 0,
    interruptionFilter: 1,
    listenerHints: 0,
    matchesInterruptionFilter: true
  },
  {
    packageName: 'org.mozilla.fenix',
    postTime: 1616416650758,
    systemTime: 1616416651203,
    offset: -14400000,
    version: 16,
    sdk: 30,
    isOngoing: false,
    isClearable: true,
    when: 1616416650758,
    number: -1,
    flags: 16,
    defaults: 0,
    ledARGB: 0,
    ledOn: 0,
    ledOff: 0,
    ringerMode: 0,
    isScreenOn: true,
    batteryLevel: 17,
    batteryStatus: 'discharging',
    isConnected: true,
    connectionType: 'wifi',
    hasAppointment: false,
    isGroupSummary: false,
    actionCount: 0,
    isLocalOnly: false,
    people: 0,
    style: 'android.app.Notification$BigTextStyle',
    tickerText: '',
    title: 'Firefox Nightly',
    titleBig: '',
    text: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textBig: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textInfo: '',
    textSub: '',
    textSummary: '',
    appName: 'Firefox Nightly',
    priority: 0,
    nid: -468413663,
    key: '0|org.mozilla.fenix|-468413663|null|10641',
    visibility: 0,
    color: 0,
    interruptionFilter: 1,
    listenerHints: 0,
    matchesInterruptionFilter: true
  },
  {
    packageName: 'org.mozilla.fenix',
    postTime: 1616865600333,
    systemTime: 1616865600675,
    offset: -14400000,
    version: 16,
    sdk: 30,
    isOngoing: false,
    isClearable: true,
    when: 1616865600331,
    number: -1,
    flags: 16,
    defaults: 0,
    ledARGB: 0,
    ledOn: 0,
    ledOff: 0,
    ringerMode: 0,
    isScreenOn: true,
    batteryLevel: 9,
    batteryStatus: 'discharging',
    isConnected: true,
    connectionType: 'wifi',
    hasAppointment: false,
    isGroupSummary: false,
    actionCount: 0,
    isLocalOnly: false,
    people: 0,
    style: 'android.app.Notification$BigTextStyle',
    tickerText: '',
    title: 'Firefox Nightly',
    titleBig: '',
    text: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textBig: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textInfo: '',
    textSub: '',
    textSummary: '',
    appName: 'Firefox Nightly',
    priority: 0,
    nid: -468413663,
    key: '0|org.mozilla.fenix|-468413663|null|10641',
    visibility: 0,
    color: 0,
    interruptionFilter: 1,
    listenerHints: 0,
    matchesInterruptionFilter: true
  },
  {
    packageName: 'org.mozilla.fenix',
    postTime: 1617315545940,
    systemTime: 1617315546172,
    offset: -14400000,
    version: 16,
    sdk: 30,
    isOngoing: false,
    isClearable: true,
    when: 1617315545938,
    number: -1,
    flags: 16,
    defaults: 0,
    ledARGB: 0,
    ledOn: 0,
    ledOff: 0,
    ringerMode: 0,
    isScreenOn: false,
    batteryLevel: 27,
    batteryStatus: 'discharging',
    isConnected: true,
    connectionType: 'wifi',
    hasAppointment: false,
    isGroupSummary: false,
    actionCount: 0,
    isLocalOnly: false,
    people: 0,
    style: 'android.app.Notification$BigTextStyle',
    tickerText: '',
    title: 'Firefox Nightly',
    titleBig: '',
    text: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textBig: "You can't see them, but they can see you. Make Firefox your default browser and keep creepy trackers from following you around online.",
    textInfo: '',
    textSub: '',
    textSummary: '',
    appName: 'Firefox Nightly',
    priority: 0,
    nid: -468413663,
    key: '0|org.mozilla.fenix|-468413663|null|10641',
    visibility: 0,
    color: 0,
    interruptionFilter: 1,
    listenerHints: 0,
    matchesInterruptionFilter: true
  }
]
```

**Comment by TrianguloY** [comment]
Even though this doesn't fix the issue, I'm writing this to inform you that there are apps that can act as a browser substitute, sometimes mimicking the choose browser popup or even including other features.

You can then set one of these apps as the default app for browser links, and forget (which will also remove those firefox notifications).

**Comment by amedyne** [comment]
Thank you for providing the notification logs @danielzgtg.
We’d like to work with you to investigate this further. And in order to do that, we will be asking for more detailed information. To protect your info/data and privacy, we would like to track this thru bugzilla. https://bugzilla.mozilla.org/home. If you do not have a bugzilla account yet, can you create one so I can transfer this GH ticket to bugzilla and we can continue investigation from there? Hopefully this works for you.
