### ISSUE TITLE
FNX-5302 ⁃ [Bug](regression) Android Soft buttons are almost invisible

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1876]
## Steps to reproduce
Open the app and check the system's soft buttons.

### Expected behavior
The buttons used to have a black background 

### Actual behavior
No background, white-on-white buttons.
![Screenshot](https://user-images.githubusercontent.com/4037709/56490929-87cf9380-64ef-11e9-81b4-62123b19f40d.png)UNITO-UNDERSCORE!20190422-110603!

### Device information
* Android device: Nexus 9 (Android 7.1.1), Sony Xperia Z5 Premium (Android 7.1.1), Mi 4i (Android 5.0.2), Huawei Nexus 6P (Android 8.1.0)
Not reproducing on Pixel (Android 9)
* Fenix version: 4/21

**Comment by smaug----** [comment]
On Honor 7, buttons are totally invisible. https://github.com/mozilla-mobile/fenix/issues/1130 / https://github.com/mozilla-mobile/fenix/issues/1144 was fixed but something regressed.

**Comment by yoasif** [comment]
See also #2102

**Comment by ekager** [comment]
@vesta0 this is done does it need to be moved to a project?

**Comment by vesta0** [comment]
Thanks @ekager I moved it :)

**Comment by bsurd** [comment]
Verified on the latest build (5/14) with a Nexus 6P, Huawei Media Pad and Nexus 9. The buttons are now visible.
