### ISSUE TITLE
Firefox should be resizeable on Samsung DeX

### ISSUE THREAD

**Issue by alexanderadam** [mozilla-mobile/fenix#18762]
## Steps to reproduce

Go into DeX mode and try to resize Firefox

### Expected behaviour

Firefox is resizeable

### Actual behaviour

It's not

### Device information

Various devices with Samsung DeX (i.e. Samsung S8, S9, S10, s20, Note 8, Note 9, Note 10, Note 20, A90, Galaxy Tab S4, Galaxy Tab S5e, Galaxy Tab S6, Galaxy Tab S6 Lite, Galaxy Tab S7 and Galaxy Tab S7+)
* Firefox for Android version: `87.0.0-rc 1`
 
# More information

This is _not_ about making some UI changes or getting the Desktop version of a website (therefore its _not_ a duplicate of [3107](https://github.com/mozilla-mobile/fenix/issues/3107#issuecomment-810587004), [10631](https://github.com/mozilla-mobile/fenix/issues/10631), [12590](https://github.com/mozilla-mobile/fenix/issues/12590), [2344](https://github.com/mozilla-mobile/fenix/issues/2344), [3999](https://github.com/mozilla-mobile/fenix/issues/3999), [4498](https://github.com/mozilla-mobile/fenix/issues/4498), [4134](https://github.com/mozilla-mobile/fenix/issues/4134), [10607](https://github.com/mozilla-mobile/fenix/issues/10607), [4140](https://github.com/mozilla-mobile/fenix/issues/4140), [4203](https://github.com/mozilla-mobile/fenix/issues/4203) or others)!

This issue is just about making Firefox resizeable(!) on devices that support a desktop environment like Samsung DeX.

To solve this it only needs the `android:resizeableActivity` set to true in the `AndroidManifest.xml`.
Other apps like [NewPipe](https://github.com/TeamNewPipe/NewPipe/pull/3948/files), [MaterialFiles](https://github.com/zhanghai/MaterialFiles/commit/7f2b9b177d43757a5063f11d3d22beb0584cc4f5), [AntennaPod](https://github.com/AntennaPod/AntennaPod/pull/4343/files), [SkyTube](https://github.com/SkyTubeTeam/SkyTube/pull/782/files), [Vinyl](https://github.com/AdrienPoupa/VinylMusicPlayer/commit/e90bc298d2313561bb42ec185370e26bda0256ee), [Joplin](https://github.com/laurent22/joplin/pull/4624/files), [Kiwix](https://github.com/kiwix/kiwix-android/pull/2330/files), [Zapp](https://github.com/mediathekview/zapp/commit/803968e7abae675b4c3142ea7f4b85386a962a39) or [GitNex](https://codeberg.org/gitnex/GitNex/commit/9e352df1ed7d1d285fde61632822e2db5d128f16) also needed this simple patch.

[Samsung also has some documentation on that](https://developer.samsung.com/samsung-dex/modify-optimizing.html).

Alternatively users could activate experimental features in system settings (DeX Labs — see screenshot) but this is probably not very user friendly and activating experimental features might not be great for everyone.

![Firefox on Samsung Dex](https://user-images.githubusercontent.com/372620/113057340-3507b780-91ad-11eb-8511-d90aa7934e6c.png)

**PS:** You might as well activate screen mirroring support via
```xml
<meta-data android:name="com.samsung.android.keepalive.density" android:value="true"/>
```
and dual mode via

```xml
<meta-data android:name="com.samsung.android.multidisplay.keep_process_alive" android:value="true"/>
```

at this point.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10220)

**Comment by Mugurell** [comment]
Thank you @alexanderadam for the report and the thorough documentation provided!

I agree it would be nice for Firefox to be resizable on Samsung Dex or ChromeOS but this will probably be a major effort with many app components - various dialogs / menus having to be checked and possible updated to ensure a consistent UX.

**Comment by alexanderadam** [comment]
> various dialogs / menus having to be checked and possible updated to ensure a consistent UX.

Good point: so as I mentioned before Samsung also have experimental flag (either via developer mode or DeX labs) to enforce this on apps and it seems that all components are able to resize properly on Firefox.

Various users are using Firefox this way (for instance [**@szaimen**](https://github.com/mozilla-mobile/fenix/issues/3107#issuecomment-810598949), or [these XDA users](https://forum.xda-developers.com/t/no-firefox-in-dex-station-mode.3673189/#post-82853859), or [these Reddit users since 2017](https://www.reddit.com/r/firefox/comments/7kjtkx/samsung_dex/), or [this Reddit users since 2019](https://www.reddit.com/r/firefox/comments/b1v6vn/what_does_firefox_look_like_in_samsung_dex/eipleon/?utm_source=reddit&utm_medium=web2x&context=3), or [this Reddit user who is even debugging on DeX](https://www.reddit.com/r/SamsungDex/comments/fzjl0i/web_debugging_with_firefox_for_android_from/) and you will probably also find even more just by searching the web :wink:).

What I mean is: Firefox seem to be working with resizing already if its support for it is forced. Thus the only difference would be, that users won't have to complain somewhere on the web until someone else is suggesting to activate developer mode or experimental features.
As you can see it is very easy to find users who tested it already. :wink: 
And so far I was unable to find a single post where a user had some issues after enforcing resizing.

**PS:** there also seem to be [an upstream issue on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1420550)

**Comment by J4gQBqqR** [comment]
This is not the only issue in Samsung device. Motorola Ready For, Huawei desktop mode, SmartianOS TNT Mode all share the same issue.

**Comment by yarcod** [comment]
I would also like to see a better desktop mode. My use-case is that I would like to use my phone on an external monitor (plugged in via USB-C), but I don't specifically use DeX. Perhaps an alternative approach could be to target Android 12L/13 notion of Extended screen sizes? https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes

**Comment by rokejulianlockhart** [comment]
@J4gQBqqR, native Desktop mode exists for Android 9 and above.

**Comment by kelimuttu** [comment]
We received [feedback](https://play.google.com/store/apps/details?id=org.mozilla.firefox&reviewId=MzBmZDg0NWUtMWNjNS00NDU0LWI1MjQtZGQ4NjFmNDVlMzlk) about this recently in Play Store: 
`Can't use until there is Samsung Dex support...`
