### ISSUE TITLE
[Bug][a11y] Add private shortcut texts contrast ratio

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18761]
## Prerequisites
Have Accessibility Scanner installed and turned on.

## Steps to reproduce
1. From the homescreen, tap on the upper right Private Browsing icon and switch to Private Mode (perform the switch 3 times).
2. Using the Accessibility Scanner, scan the "Add private browsing" shortcut to your homescreen contextual recommender.

### Expected behavior
No suggestions are made.

### Actual behavior
The "Add a shortcut to open private tabs from your Home screen.", and "No thanks" texts are suggested to have a different contrast ratio.
 
### Device information
* Device vendor / model and Android version: Samsung Galaxy Note 8 (Android 9)
* Firefox for Android version: Beta 88.0.0-beta.3, RC 87.0.0, 1/4 Nightly

<img src="https://user-images.githubusercontent.com/40694158/113392205-6941ca80-939d-11eb-9bee-cd0221d2c792.jpg" width="300" height="550" />

 <img src="https://user-images.githubusercontent.com/40694158/113392482-dd7c6e00-939d-11eb-84f0-7925bf630b5e.jpg" width="300" height="550" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10219)

**Comment by codesuperstarr** [comment]
I am interested in working on this. Please assign it to me.

**Comment by LaviniaL99** [comment]
I was able to reproduce the issue on Firefox 96.0.0-beta4, only for **"Add a shortcut to open private tabs from your Home screen."** text is suggested to have a different contrast ratio.

Device used:
Samsung S10e -> Android 10

![private shortcut 1](https://user-images.githubusercontent.com/96047134/147113674-872a77bb-7278-43d0-8337-bdf66da4b41d.JPEG)
