### ISSUE TITLE
Intermittent UI test failure - StrictEnhancedTrackingProtectionTest#testStrictVisitContentShield, testStrictVisitDisableExceptionToggle, testStrictVisitSheetDetails 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#18764]
### Firebase Test Run:
Flaky, failed 1 out of 2 runs
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6588865899882511274/executions/bs.a522f80d838f1ed2/testcases/3/test-cases
### Stacktrace:
```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/mozac_browser_toolbar_menu
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.helpers.ViewInteractionKt.click(ViewInteraction.kt:18)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.openThreeDotMenu(NavigationToolbarRobot.kt:181)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.openTrackingProtectionTestPage(NavigationToolbarRobot.kt:133)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitContentShield(StrictEnhancedTrackingProtectionTest.kt:99)
```
### Build: 
Master 4/1
commit: [AC 75.0.20210401143103 update](https://github.com/mozilla-mobile/fenix/commit/21c5eba31061598816aef7338898ed3e16dd918d)

**Comment by sv-ohorvath** [comment]
Hasn't failed since more than a month ago. Closing it for now, can be reopened if it fails again.

**Comment by sv-ohorvath** [comment]
Flaky again https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6341306172079833522/executions/bs.cfa97b64515c6c2b/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Same failure as https://github.com/mozilla-mobile/fenix/issues/19940

**Comment by AndiAJ** [comment]
Flaky 1x on Master 7/27 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5466104749619675597/executions/bs.3d69427d9330f57e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on Main 7/29 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7242961668989966286/executions/bs.3150b48be621433a/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
This and #19940 will be changed once this lands: gabrielluong@732e4dc
Let's see what is still needed after that.

**Comment by AndiAJ** [comment]
`testStrictVisitDisableExceptionToggle` Flaky 1x on 8/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7079604559173879421/executions/bs.ca9823acf6e5f78f/testcases/1/test-cases)

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.openThreeDotMenu(NavigationToolbarRobot.kt:180)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.openTrackingProtectionTestPage(NavigationToolbarRobot.kt:143)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitDisableExceptionToggle(StrictEnhancedTrackingProtectionTest.kt:164)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by sv-ohorvath** [comment]
testStrictVisitContentShield, testStrictVisitDisableExceptionToggle still flaky with the new changes.
New error:
`androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.mozilla.fenix.debug:id/trackingProtectionDetails'.
`
[testStrictVisitDisableExceptionToggle - Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5413052681356139579/executions/bs.b5dac309c3d2b692/testcases/1/test-cases)

[testStrictVisitSheetDetails- Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6728652480957699598/executions/bs.af00e18af32f43d5/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
`testStrictVisitSheetDetails` flaky on 8/20 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8538190970211871298/executions/bs.202393dff9f8f658/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6954223360048059360/executions/bs.1dcac26ef445cae5/testcases/1/test-cases)
`androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.mozilla.fenix.debug:id/trackingProtectionDetails'.`

`testStrictVisitDisableExceptionToggle` flaky on 8/20 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6954223360048059360/executions/bs.3e0cdcc38bfc47a1/testcases/1/test-cases)
androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.mozilla.fenix.debug:id/trackingProtectionDetails'.

**Comment by AndiAJ** [comment]
`testStrictVisitSheetDetails` flaky 1x on 8/21 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4851875288658467025/executions/bs.20f8abe3a2515dd1/testcases/1/test-cases)

`androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.mozilla.fenix.debug:id/trackingProtectionDetails'.`

`testStrictVisitSheetDetails` flaky 1x on 8/22 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7590162841058661041/executions/bs.79a86a9099607058/testcases/1/test-cases)

`androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.mozilla.fenix.debug:id/trackingProtectionDetails'.`

**Comment by AndiAJ** [comment]
`testStrictVisitDisableExceptionToggle` Failed 1x on 8/23 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6556112574874726927/executions/bs.4d47c1e0514daeb8/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6556112574874726927/executions/bs.9a4829d0b751315c/testcases/1/test-cases)
