### ISSUE TITLE
[Bug] Fenix crashes in recent 2 days

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#18763]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
4c9dd3a5-02d1-4325-aa55-8262d551d4a3
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-d08a4a06-891b-4aa9-9418-e12820210401
----
<native crash>

26f6b2c0-9557-4135-89db-1e6e4632a7ec
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-b8fc26db-4ba2-459b-98e9-b53230210402
----
<native crash>

Fenix crash when I surfing internet. 
### Device information

* Device vendor / model and Android version: Huawei Honor 20S, Android 10
* Firefox for Android version: 87.0.0

**Comment by sflorean** [comment]
@0x391F there are some bugs opened in Bugzilla, for this signature, Please follow/add comments there. I will close this as duplicate, but we will reach to you again when this will be fixed. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1644486
https://bugzilla.mozilla.org/show_bug.cgi?id=1360392
