### ISSUE TITLE
Verify PWAs still install on new menu 

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18776]
Make sure PWAs still install on new menu (I think this was missed in new designs)

Can be tested by:
1. Navigate to paperplanes.world/
2. Open three-dot menu
3. See that "Install" is shown (and works when clicked)

<img width="371" alt="image" src="https://user-images.githubusercontent.com/43795363/113459855-6adeb300-93dc-11eb-89c9-30bcde57b75b.png">

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 210413.
### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)
