### ISSUE TITLE
FNX-5303 ⁃ [Bug] Edit or delete the default bookmark folders crashes the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1877]
## Steps to reproduce
1. Go to bookmarks.
1. Long tap one of the existing folders: menu, toolbar, unfiled or mobile
1. From the multi-selection toolbar, tap Edit, or Delete.
    1. Expected behavior
Maybe edit and delete shouldn't be an option for these folders? If not, then they should be functional.
    1. Actual behavior
App crashes
    1. Device information

* Android device: Pixel, Nexus 9 (Android 7.1.1)
* Fenix version: 4/21 build

**Comment by kbrosnan** [comment]
Unable to delete default bookmark folders in the Library. Tested on Pixel 3 and Galaxy S6.
