### ISSUE TITLE
[Bug] Firefox nightly shown as Autofill service

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#18775]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to Android auto fill settings
Observe there is Firefox nightly in the list

Idk if this is something expected.

![Screenshot_20210403-012329_Ayarlar](https://user-images.githubusercontent.com/17825767/113458565-671e5100-941b-11eb-9145-cd6fddca9ea5.png)

### Device information

* Device vendor / model and Android version: Xperia XZ1 Android 11
* Firefox for Android version: 2/4 nightly

**Comment by amedyne** [comment]
@pocmo , Thoughts?

**Comment by pocmo** [comment]
Yes, this is expected. Nightly is shipping with an autofill implementation that can autofill usernames/passwords. (#18457)
