### ISSUE TITLE
How to change firefox android nightly to the old menu style?

### ISSUE THREAD

**Issue by Rosabis** [mozilla-mobile/fenix#18777]
Because I really hate the current menu changes:.
1. move the add-ons to the bottom,that's makes me difficult to find the item I want to use
![Screenshot_2021-04-03-10-54-30-375_org mozilla fenix](https://user-images.githubusercontent.com/32984303/113466057-58f82100-946b-11eb-92ab-89b114911d12.png)
2. Remove the icon from the settings menu
![Screenshot_2021-04-03-10-55-15-302_org mozilla fenix](https://user-images.githubusercontent.com/32984303/113466079-85ac3880-946b-11eb-9494-6a5cd3c9e3ed.png)
So I would like to ask how to change these styles to the old ones, thanks

**Comment by Goldmaster** [comment]
Completely agree with the add-ons part. When do we need that? That lives in the settings not in the menu bar. Please stop changing things that don't need to be changed.

**Comment by cadeyrn** [comment]
> How to change firefox android nightly to the old menu style?

Make your own build of Firefox and revert this change. I don't know what other answer you could expect to this question.

> move the add-ons to the bottom,that's makes me difficult to find the item I want to use

This is obviously a bug and already reported here: #18770

**Comment by Mugurell** [comment]
The browser menu is actively being refactored. Planned changes - https://github.com/mozilla-mobile/fenix/issues/17796
Options seen might change over time depending on how development advances.

Regarding the "Add-ons" option which appears below the navigation bar buttons this seems to be an issue already reported on https://github.com/mozilla-mobile/fenix/issues/18770. 
Closing as a duplicate.
