### ISSUE TITLE
Firefox Android crash when tapping on Searchbar

### ISSUE THREAD

**Issue by Buddey42** [mozilla-mobile/fenix#18771]

**Comment by cadeyrn** [comment]
Why did you remove all relevant fields from the bug template?

- What is your Firefox version?
- What is your Android version?
- What is the model name of your device?

I can not reproduce the issue (Firefox Nightly, OnePlus 7T Pro McLaren Edition, Android 11) so you see it's important to give the developers some basic information.

If you open the settings > About Firefox you can find a link for crash reports. Are there crash reports? Could you share the URL?

**Comment by Buddey42** [comment]
cya
