### ISSUE TITLE
[Bug][a11y] Consider increasing size of radio buttons in onboarding cards

### ISSUE THREAD

**Issue by neha-b2001** [mozilla-mobile/fenix#18787]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Install and open Google Accessibility Scanner
2. Have a clean Firefox profile
3. Upon opening the app, onboarding cards are seen - 'Choose your theme' and 'Pick your toolbar placement'. They have radio buttons to select your preferred theme/placement. 
### Expected behavior
No suggestions for changes.
### Actual behavior
Google Accessibility Scanner suggests **increasing the size of the radio buttons** from 32dp x 32dp to 48dp x 48dp or larger. 

![image](https://user-images.githubusercontent.com/67039214/113483513-73f58000-94c1-11eb-988b-13904d31455a.png) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ![image](https://user-images.githubusercontent.com/67039214/113483563-b28b3a80-94c1-11eb-91c7-c82d68f88e5a.png)

### Device information

* Device vendor / model and Android version: Redmi Note 8 Pro (Android 10)
* Firefox for Android version: Firefox Preview Version 1.0.2114   +   Nightly 210331 17:00 (Build #2015801931)

**Comment by neha-b2001** [comment]
I am an Outreachy applicant, hence tagging @eliserichards. Please take a look if possible.
Also, if this is a valid issue that needs to be fixed, could I be assigned the same?

**Comment by mcarare** [comment]
This was already reported [here](https://github.com/mozilla-mobile/fenix/issues/16342) and decided [here](https://github.com/mozilla-mobile/fenix/issues/9583#issuecomment-609987250).
