### ISSUE TITLE
Firefox 87 does not connect to Blackboard Collaborate Ultra sessions 

### ISSUE THREAD

**Issue by ihesham** [mozilla-mobile/fenix#18789]
Unfortunately, this is very serious for me as most of my job tasks I have to perform online through my browser (Firefox), more specifically on Blackboard websites.
Recently, almost since upgrade to Firefox 87.0, I cannot open meeting sessions on Blackboard. 

Here's a more details I found reflecting my same issue:
[https://blackboard.secure.force.com/publickbarticleview?id=kAE5Y000000kA5IWAU](https://blackboard.secure.force.com/publickbarticleview?id=kAE5Y000000kA5IWAU )

## Steps to reproduce
1- log in to https://www.blackboard.com/ from your institution website
2- Start Collaborate Ultra

### Expected behavior
Normal connection to Blackboard and starting new meeting session with audio and mic connection

### Actual behavior
A message appears saying "Uh-oh. You can't connect. Try to rejoin."
### Device information
* Device/OS: PC/  Intel corei7 / windows 10 version 20H2
* Firefox version: 87.0 (Firefox Browser for PC)

**Comment by wisniewskit** [comment]
@ihesham, I've just been told that there aren't any known WebRTC issues with Blackboard and Firefox 87 yet, so it would be great if we could grab the info that's in `about:webrtc` after trying to log in. Would you have some time to provide that info so we can begin diagnosing this?

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1703117

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
This report seems to be about desktop Firefox.

**Comment by jan-ivar** [comment]
Hi @ihesham, we're now tracking this in [bug 1703117](https://bugzil.la/1703117), but I don't know how to contact you there — do you have a bugzilla account? — so I'm reaching out here.

it sounds from your description that this used to work before 87. Would you mind confirming this with an older version of Firefox, or better yet, by running the [mozregression](https://mozilla.github.io/mozregression/install.html) tool to narrow down a regression range?
 
You mention _"Blackboard Collaborate Ultra sessions"_, is that significant, or are all forms of blackboard meetings nonfunctional for you?
