### ISSUE TITLE
[Bug] Top site favicons keep disappearing after every update

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#18788]
Top site favicons are replaced with the generic first-letter icons after every update, which is pretty annoying since Nightly is updated at least once per day.

## Steps to reproduce
1. Add a top site. 
2. Visit it to make sure it gets populated with a favicon on the new tab screen.
3. Update Nightly.
4. Open Nightly.

### Expected behavior
Top sites still have their favicons they had before the update.

### Actual behavior
Top sites have the generic first-letter icons.

### Device information

* Device vendor / model and Android version: Huawei Mate 20 lite, EMUI 10/Android 10

* Firefox for Android version: on any Nightly version

**Comment by amedyne** [comment]
Hi @anotherus3r! Can you provide example topsites urls that you have encountered this problem?

**Comment by anotherus3r** [comment]
Hi @amedyne, it affects any top site I add. 

Basically, I add and visit a top site and Fenix adds its favicon to the top site on the new tab page. Then I update Fenix when a new update is available and at next startup, the top sites have lost their favicons, which are replaced with the generic first-letter icons. Visiting the top sites again after the update repopulates them with their respective favicons until the next update is performed.

**Comment by SoftVision-LorandJanos** [comment]
Hi @anotherus3r ! Thank you for your report! I was not able to reproduce the issue you described. Could you please help us with more specific information like the website addresses you added to top sites, the versions of nightly from before and after the upgrade and your device information? Also, a screenshot of the issue would help. Thank you!

I've tested upgrading Nightly from 210405 17:00 - GV89 to 210406 05:01 - GV89.
Device used: HTC Nexus 9 with Android 7.1.1.

**Comment by anotherus3r** [comment]
Weird, I can't reproduce it anymore, too. I might be missing something in the steps to reproduce, or I assumed the wrong cause of this. I'm gonna close this for now and if I manage to reproduce it with the same or slightly altered steps, I'll update this issue.
