### ISSUE TITLE
FNX-5304 ⁃ [Bug] 3 dot menu help not linked

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1878]
## Steps to reproduce
1. Open Fenix.
1. Tap on the 3 dot menu.
1. Tap on "Help".

### Expected behavior
A help page is opened.

### Actual behavior
Nothing happens.

### Device information
* Android device: HTC 10 (Android 8)
* Fenix version: 1.0.1917(#11111213)

**Comment by ekager** [comment]
Will be closed by #1895

**Comment by vesta0** [comment]
FIXED.

**Comment by bsurd** [comment]
Verified as fixed on a Nexus 5 and HTC 10 with the latest build.
