### ISSUE TITLE
[Bug] Reader view toggle doesn't show up immediately for articles from Telegram.hr

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#18798]
## Steps to reproduce
1. Open Firefox and go to https://telegram.hr
2. Open any article.
3. Observe address bar.

### Expected behavior
Reader view toggle appears in address bar. 

### Actual behavior
Reader view toggle does not appear in the address bar immediately. It does appear after you open and close the tab tray.

### Device information

* Device vendor / model and Android version: Huawei Mate 20 lite, EMUI 10/Android 10
* Firefox for Android version: Nightly 210404 17:00 (Build #2015802699) and Daylight 87.0.0-rc.1 (Build #2015799099)

**Comment by SoftVision-LorandJanos** [comment]
Hi @anotherus3r ! Thank you for your report! This issue is reproducible. Tested on Nightly (210406 05:01 - GV89).
Device used: HTC Nexus 9 with Android 7.1.1.

**Comment by ryg-git** [comment]
If it's ok I would like to work on this issue

**Comment by csadilek** [comment]
We have the same behaviour on desktop. Readability is only detected after a reload for most articles on this site. We should not land an Android-specific workaround but file an upstream ticket for https://github.com/mozilla/readability/ to see if this can be improved at all. This way any solution will work on all platforms.

**Comment by anotherus3r** [comment]
@csadilek has someone already filed an issue there for this?

**Comment by csadilek** [comment]
@anotherus3r not yet. Would you mind transferring this ticket or filing a new one for https://github.com/mozilla/readability/. Thank you!

**Comment by anotherus3r** [comment]
@csadilek I filed mozilla/readability#691. Should this issue be closed now?

**Comment by csadilek** [comment]
@anotherus3r Thanks, yes, let's close this one then.
