### ISSUE TITLE
[Bug] Can't upload a file with sign/hash (#) symbol in name

### ISSUE THREAD

**Issue by xalt7x** [mozilla-mobile/fenix#18790]
I'm trying to add file with sign hash/sign symbol in name (e,g, "1#.jpg") into simple input
`<input type="file">`
Firefox accepts most filenames but not the ones with hash/sign symbol

## Steps to reproduce
1) Visit [MDN article about input type="file"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)
2) Try to upload file with name "1#.jpg"

### Expected behavior

Name of a file appear near "Browse" button

### Actual behavior

Visually nothing happens.

### Device information

* Tested Android devices: Google Pixel 4a / Android 11
1) Google Pixel 4a / Android 11
2) Huawei Y6 Pro (TIT-U02) / Android 5.1
* Firefox for Android version: Firefox Daylight v87.0.0-rc.1 (Build #2015799099)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10240)

**Comment by SoftVision-LorandJanos** [comment]
Hi @Alt37 ! Thank you for reporting this issue! Yes, I can confirm it is reproducible on latest Nightly (210406 05:01 (GV89), Beta (GV: 88.0-20210404185932) and Firefox Daylight v87.0.0-rc.1 (Build #2015799099). It is not reproducible on Google Chrome 89.0.4389.105.
Device used: HTC Nexus 9 with Android 7.1.1

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible.

Verified on the latest Nightly (94.0a1 - 2021-10-05T05:10:10.350256).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 101.0a1 (2022-04-14) build.
Device used: Google Pixel 4 (Android 12).
Reopening the ticket.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 110.0a1 (2023-01-17).
On Chrome the file is successfully uploaded.
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813752

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
