### ISSUE TITLE
No option Select All  to save tabs to collections

### ISSUE THREAD

**Issue by xpseudonym** [mozilla-mobile/fenix#18797]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Following instructions to save tabs to collections here:
https://support.mozilla.org/en-US/kb/collections-firefox#w_select-and-add-multiple-tabs-to-a-collection
There is no `Save to collection` option at step 3...

Choosing the option `Select tabs` does produce an icon to save to a Collection, but there is no `Select all tabs` option and selecting 59, 99 or 159 tabs individually is a complete pita and seems contrary to the intent of the Collections feature - that is, to clear tabs and prevent a browser becoming overcrowded with tabs while not loosing the references the tabs refer to

### Expected behaviour
I am able to save tabs to collections
### Actual behaviour
I am unable to save tabs to collections

### Device information

* Device vendor / model and Android version: LG 4G (H815); Android 7.1.2
* Firefox for Android version: 87.0.0-rc.1 (Build #2015799099)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10243)

**Comment by Mugurell** [comment]
Seems like "Save to collection" was changed to "Select tabs" in https://github.com/mozilla-mobile/fenix/issues/16132.
Asking @topotropic whether we should revert that or change the online documentation.

**Comment by topotropic** [comment]
Yes, that was an intentional change – we need to update the documentation.

We're working on improving collections and I'll make a note of the "Select all" request! Thanks!

**Comment by xpseudonym** [comment]
Thanks for the interest folks, Morgan

**Comment by amedyne** [comment]
Updating ticket to reflect "Select all"

**Comment by Robbankz** [comment]
should be able to search for specific tabs in sync, and delete multiple after selecting all, you miss the most essential options , i might want to select all to send to device, not select all to share to anothet app ,its too slow and too idiotic to hand pick 350 tabs to clean my history, you screwed up the three dot menu with the bonehead swipe up now this, you need to do ui/ux changes with more common sense @eliserichards

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812735

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
