### ISSUE TITLE
[Bug] Fenix loses internet, needs to be swiped from Recents/Force Closed to work again

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#18805]
## Steps to reproduce

No clear steps to reproduce, sorry. I was hesitating to file this issue because of this. All I know is that sometimes, Fenix (and desktop Firefox) loses internet connection, and nothing fixes it short of Quitting and swiping from Recents (simply quitting desktop Firefox works).

Since swiping from Recents is no longer an option (#17790), I have to go a step further and Force Close the app, then open it again to get working internet on it. 

### Expected behavior

If Fenix loses internet connection for any reason, it should try to reestablish the connection and keep working normally.

### Actual behavior

Once Fenix loses internet connection, it refuses to connect again. Other apps on the phone keep working normally, meanwhile. Only Fenix refuses to transfer a single byte either way.

Same with desktop Firefox. Other software keeps using the internet, but Firefox needs to be closed and opened again.

### Device information

* Device vendor / model and Android version: Mi 5 (LOS 17.1)
* Firefox for Android version: Nightly 210324 17:02 (Build #2015800587)

**Comment by Mugurell** [comment]
@opusforlife2 
Do you see this with a particular website?
Have you seen a similar issue in other apps?
How often does this happen?
What happens if "with lost internet" you open https://www.mozilla.org/ in a new tab?

**Comment by opusforlife2** [comment]
@Mugurell

> Do you see this with a particular website?

No. This is not a website issue, for sure. When I say Fenix/Firefox loses internet, this includes addons as well, and even trying DNS Lookup (about:networking) on multiple domains gives "NET_ERROR_UNKNOWN_HOST". (I think that's the error. I will confirm it when I next encounter the issue.)

> Have you seen a similar issue in other apps?

Nope. This has always been a Firefox/Fenix issue ever since I can remember. However, I do suspect that DoH might play a role. I have network.trr.mode set to 3 (and the correct bootstrap address), in case that is relevant. But even there, it's not a particular DoH provider that could be at fault, because the same provider works on desktop Firefox when Fenix is borked, and vice versa.

Why I think DoH might play a role is because all searching online for this bug throws up is multiple Mozilla Support answers which claim it has something to do with Firefox's proxy settings. I haven't changed anything there (it's set to use system proxy settings, the default), but DoH might count.

> How often does this happen?

It can range from 1-2 per day to once in several weeks.

> What happens if "with lost internet" you open https://www.mozilla.org/ in a new tab?

I could try it the next time, although given what I've stated in my first answer above, I'm certain it won't work.

**Comment by opusforlife2** [comment]
> What happens if "with lost internet" you open https://www.mozilla.org/ in a new tab?

Tried it; didn't work, as expected.

> "NET_ERROR_UNKNOWN_HOST". (I think that's the error. I will confirm it when I next encounter the issue.)

It's NS_ERROR_UNKNOWN_HOST.

**Comment by Mugurell** [comment]
Thank you @opusforlife2 for all details!
Since this happens on Firefox desktop also it might be a core issue.
Moving the ticket to Bugzilla.
Probably more details will be needed. Please follow  the discussion there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1703768

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by opusforlife2** [comment]
Alright. Thanks, @Mugurell!

**Comment by opusforlife2** [comment]
@Mugurell so I'm not familiar with the timelines operated on over at Bugzilla. How long will it take the bug to be triaged? Days, weeks, months?

Whatever the case may be, the problem is that I'm still left hanging regarding the issue I mentioned in #17790. Can that change be reverted until this bug is addressed and fixed? That or implementing #18686. It's just a cosmetic thing for most users, but it is quite an annoyance for me.

**Comment by KershawChang** [comment]
@opusforlife2 , this issue could be fixed by [bug 1698321](https://bugzilla.mozilla.org/show_bug.cgi?id=1698321), so could you try to use Fenix nightly and see if you can still reproduce this?
Thanks.

**Comment by opusforlife2** [comment]
@KershawChang Hey, I read your comment on Bugzilla yesterday and have been using the latest Fenix Nightly since then. Sorry I didn't respond, I didn't realise that you were waiting for information.

I haven't encountered the issue so far (and the Resolved Fixed bug you linked _does_ seem to describe my situation pretty accurately), but one day is too soon to tell. How about closing the Bugzilla bug? If I encounter the issue, I'll let you know, and you can reopen it in that case.

Also, I have been using Firefox 88 on PC as well (Bugzilla says it's fixed on this version), and after some basic usage it _does_ seem like the issue is resolved. This is because it seems like instead of losing connection permanently, Firefox "fails to connect to the server" once, but always reconnects on a reload. Who knows? This behaviour might be completely disconnected from the bug fix, or new behaviour caused by it.

Anyway, I'll keep using both Fenix and Firefox for a couple of weeks, and let you know if I encounter the bug.

Thanks!

(And thanks for filing the bug, @Mugurell!)

**Comment by KershawChang** [comment]
Thanks! Feel free to reopen [bug 1703768](https://bugzilla.mozilla.org/show_bug.cgi?id=1703768) if you see this happen again.
