### ISSUE TITLE
Safe Browsing breaks m.huxiu.com on Fenix, but not in Chrome.

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#18804]
## Steps to reproduce

Visit m.huxiu.com, note that the page isn't loading images/CSS.

### Expected behavior

The page loads normally.

### Actual behavior

Images are broken, no CSS loads. Two key scripts are blocked by Safe Browsing, according to the remote console:
```
The resource at “https://static.huxiucdn.com/common/sea/sea.js” was blocked by Safe Browsing. m.huxiu.com
The resource at “https://static.huxiucdn.com/common/sea/seajs_css.js” was blocked by Safe Browsing. m.huxiu.com
```

### Device information

* Device vendor / model and Android version: Google Pixel 3, Android 11
* Firefox for Android version: Nightly 210405 17:00 (Build #2015802891)

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1703174

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
