### ISSUE TITLE
[Bug] Valid base64 not loading

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla-mobile/fenix#18802]
## Steps to reproduce

1. Use Firefox for Android 87.0.0-rc.1
2. Load this fiddle https://jsfiddle.net/ArmorDarks/poxaLvjw/2/

### Expected behavior

The base64 image in this fiddle should appear

### Actual behavior

It won't appear. Inspector says `Could not load the image`, but it's perfectly valid base64 which is generated from Canvas by Firefox Mobile itself.

This image works fine in Chrome, for instance.

### Device information

* Device vendor / model and Android version: Samsung Note 9 (SM-N9600), stock, Android 10
* Firefox for Android version: 87.0.0-rc.1

**Comment by Mugurell** [comment]
Let's check this after https://bugzilla.mozilla.org/show_bug.cgi?id=1668952 lands.

**Comment by Mugurell** [comment]
@ArmorDarks Currently Fenix doesn't support data URLs bigger than 2 MB in size.

**Comment by abodea** [comment]
Thank you for this report, I was also able to reproduce this issue on 87.0.0-rc.1 and the latest Nightly 4/6/21 with Google Pixel 4 XL (11).

**Comment by kbrosnan** [comment]
This will be fixed in v89.
