### ISSUE TITLE
FNX-5307 ⁃ [Bug] "Back button" label on a refused connection page

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1880]
## Steps to reproduce
1. Go to badssl.com. 
1. Go to one of the test pages, e.g. the expired certificate page.
1. Observe the back button.
    1. Expected behavior
The button has a label "Go back".
    1. Actual behavior
The current button label is "%backButton".
    1. Device information

* Android device: Pixel, Nexus 9 tablet (Android 7.1.1)
* Fenix version: 4/21 build

**Comment by vesta0** [comment]
This is fixed.

**Comment by sv-ohorvath** [comment]
Verified as fixed on 4/23 build
