### ISSUE TITLE
FNX-5308 ⁃ [Bug]On tablets, the button on the error pages is behind the toolbar

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1881]
## Steps to reproduce
1. On a tablet, go to any error page: e.g. bad URL or network error
1. Observe the position of the back/try again button.
    1. Expected behavior
The button is visible.
    1. Actual behavior
The button is displayed too low, being hidden behind the toolbar.
    1. Device information

* Android device: Nexus9, Galaxy Tab 3.
* Fenix version: 4/21

**Comment by softvision-miralobontiu** [comment]
Here is how it is displayed on the latest build 1.0.1922 (#11530616), on Samsung Galaxy Tab S3 (Android 8), and Samsung Galaxy Tab A6 (Android 5.1.1).
The first screenshot is when the error page is loaded, the second is when the page is scrolled a bit.

![Screenshot_1](https://user-images.githubusercontent.com/40694158/58792284-88823c00-85fc-11e9-91ce-41d77363a5bc.png)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/8 build. tablets: Galaxy Tab S3 (Android 8), Galaxy Tab A 6 (Android 5.1.1)
