### ISSUE TITLE
[Bug] Toolbar shows up while scrolling. Doesn't stay hidden during scrolling.

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#18811]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open Yahoo.com
### Expected behavior
Toolbar hides during scrolling
### Actual behavior
Toolbar comes up.
### Device information
Samsung Galaxy A71
* Device vendor / model and Android version: Samsung A71, Android 11, UI 3.1
* Firefox for Android version: Nightly 210405 17:00 (Build #2015802891)

https://user-images.githubusercontent.com/76210878/113683452-d9c05280-96e1-11eb-9542-be731206c625.mp4

**Comment by Mugurell** [comment]
Thank you for the report @iamiceparticle !
Moving this to Bugzilla since it seems to be a more low level issue.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1703200

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
