### ISSUE TITLE
[Bug] Three-dot menu gets blocked after expanding it on Samsung devices

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18814]
## Steps to reproduce
1. Install debug build with AC: 75.0.20210405143037, a69f74ece, and GV 89.0a1-20210405094633 on Samsung Galaxy Note 8 (Android 9).
2. Open a page, then tap on the three-dot menu.
3. Scroll the menu so that is fully displayed.
4. Tap on any option from the menu.

### Expected behavior
The option tapped on is redirecting the user to what it was tapped.

### Actual behavior
* I was able to exit the menu by tapping anywhere outside the menu,
* I was NOT able to access any of the options from the menu while the menu was fully displayed,
* when the menu was collapsed, the options from the menu are responsive,
* when the toolbar was set to the top, the menu was responsive.

### Device information
* Device vendor / model and Android version:  Samsung Galaxy Note 8 (Android 9)
* Firefox for Android version: debug build with AC: 75.0.20210405143037, a69f74ece, and GV 89.0a1-20210405094633
* Not reproducible on OnePlus 5T (Android 10), Google Pixel (Android 10)
* Not reproducible on 4/6 Nightly build
* From #17772 

https://user-images.githubusercontent.com/40694158/113704815-5143b100-96e5-11eb-886e-7241fac72416.mp4

[logcat Samsung.txt](https://github.com/mozilla-mobile/fenix/files/6264296/logcat.Samsung.txt)

**Comment by Mugurell** [comment]
Thank you Mira!
I can reproduce this on a Samsung S10 with Android 10.

**Comment by lobontiumira** [comment]
Reproducible on the 4/9 Nightly build with Samsung Galaxy Note 8 (Android 9).

**Comment by Mugurell** [comment]
With the other tickets opened by users for this please test on multiple devices if the menu can be interacted with without issue before and after being expanded on multiple devices.

**Comment by soren121** [comment]
The expanded menu is working now with Nightly 210412 on a Samsung Galaxy S20 (Android 11), thanks!

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/13 Nightly build with Samsung Galaxy Note 8 (Android 9).
