### ISSUE TITLE
[Bug] Firefox Browser logo and PB icon not displayed on the home screen

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#18815]
## Prerequisites
Have a fresh install or a clean profile.

## Steps to reproduce
1. Launch Fenix
2. Tap the "Start Browsing" button
3. Check the home screen

### Expected behavior
The "Firefox Browser" logo and PB icon should be displayed  on the home screen.
![image](https://user-images.githubusercontent.com/51314259/113709473-2f4d2d00-96eb-11eb-85c9-7bb314adb2b6.png)

### Actual behavior
It only get's displayed after close-resume or after opening a new tab.

### Device information

* Device vendor / model and Android version: 
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• Pixel 2 (Android 9)
• HTC Nexus 9 (Android 7.1.1)
• OnePlus A3 (Android 6.0.1)

* Firefox for Android version: Nightly 210406

**Comment by mcarare** [comment]
This is a regression introduced with https://github.com/mozilla-mobile/fenix/commit/3260cbd986c4fd7deb56c68058d7e604e1e138f0. As the `homeAppBar` is collapsed when the button is clicked, the fact that the screen cannot be scrolled makes it impossible to scroll and make it visible again. The easiest fix, while keeping the changes introduced in https://github.com/mozilla-mobile/fenix/commit/3260cbd986c4fd7deb56c68058d7e604e1e138f0 would be to expand the `homeAppBar` when the "Start Browsing" button is clicked.

**Comment by mcarare** [comment]
Reopened for QA.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 4/15** with **Google Pixel 4XL (11), Samsung Galaxy S10+ (10), Samsung Galaxy S7 (7).**
Note that the Firefox Browser logo and PB icon are displayed after tapping on the Start Browsing button.
