### ISSUE TITLE
FNX-5309 ⁃ [Bug] No error page on phishing/malware sites

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1882]
## Steps to reproduce
1. Go to http://www.itisatrap.org/firefox/its-a-trap.html
1. Go to http://www.itisatrap.org/firefox/its-an-attack.html
Or go to badssl.com and use the test pages from there.
    1. Expected behavior
Error page displayed.
    1. Actual behavior
Unsafe website displayed
    1. Device information

* Android device: Pixel, Nexus 9 
* Fenix version: 4/21 build

**Comment by sv-ohorvath** [comment]
No error pages on any of the first 6 links from testsafebrowsing.appspot.com

**Comment by kbrosnan** [comment]
https://github.com/mozilla-mobile/android-components/issues/2725

**Comment by softvision-miralobontiu** [comment]
Verified that the page from step 1 (http://www.itisatrap.org/firefox/its-a-trap.html) displays this message:
![1](https://user-images.githubusercontent.com/40694158/58426682-def3f580-80a5-11e9-867f-57d938d91cc2.png)

the page from step 2 (http://www.itisatrap.org/firefox/its-an-attack.html) displays this message:
![2](https://user-images.githubusercontent.com/40694158/58426687-e2877c80-80a5-11e9-84a2-b0817f90cf39.png)

, and the pages from badssl.com display this:
![3](https://user-images.githubusercontent.com/40694158/58426695-e7e4c700-80a5-11e9-874d-11a8c9137cf0.png)

Tested with the latest build 1.0.1922 (#11470614), with Nexus 6P (Android 8.1.0).
