### ISSUE TITLE
Adjust Add/Edit bookmark item to fit design spec

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18829]
Follow-up to #17797 

Based on Victoria's review [here](https://github.com/mozilla-mobile/fenix/issues/17797#issuecomment-814308481)

> Yes, there should be a 7px spacing between the star and the "Add/Edit" text - it does look like this is short some pixels. (FYI for the future, if you're signed into Figma you can use the Inspect mode to look at pixel measurements between elements)
> 
> The star icon should also be smaller - 19px instead of the standard 24px.
> 
> For dark mode, the purple text should be the main purple text color used in dark mode (Violet 40 - #ad3bff)

**Comment by mcarare** [comment]
@violasong The color for the text and star icon at the end of the item is #592ACB in Figma, which corresponds to **accent_bright_light_theme**. That is why for the dark theme the corresponding **accent_bright_dark_theme** is the same #592ACB that is seen in the screenshots. 

The color you mentioned Violet 40 - #ad3bff is not used anywhere in the app, neither is #9933FF (Web safe color of #ad3bff). Also, If we are going to use new color attributes(new light-dark corresponding scheme) we will also need color for the private theme.

**Comment by violasong** [comment]
Ah, surprising that that color isn't in the app since it was in our figma library. In dark mode, there's a very similar light purple that colors the URL that's shown under "Fill link for clipboard" - we can use that instead. I'd use this same light purple for private mode as well.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 4/13 with Samsung Galaxy Tab S3 (Android 8).
