### ISSUE TITLE
Show Sync re-auth required badge on 'Settings' button

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#18837]
There is one more state of the 'Sign in to sync' menu that we may have overlooked (which I do not see in the designs linked). If an account needs to be re-authenticated we propagate the error to the 'Settings' menu item.

With the 'Sign in' button now in the main menu, the re-authenticated warning previously shown from 'Settings' will be shown on 'Sign in to sync'? This could also be done as a follow-up. 🙂 
   * we should continue to show this on the Settings menu item for now
   * Can followup with Victoria for future moving it to the sync sign in item

<img width="402" alt="Screen Shot 2021-04-02 at 2 56 30 PM" src="https://user-images.githubusercontent.com/1370580/113445440-e08a5500-93c3-11eb-83d9-3781077aaabf.png">

To reproduce this case for testing, you can pair with your device, then go to https://accounts.firefox.com/settings to manage your devices and remove the device from the account console. Re-open Fenix and you should be in the re-auth state.

_Originally posted by @jonalmeida in https://github.com/mozilla-mobile/fenix/issues/17798#issuecomment-812667505_

**Comment by jonalmeida** [comment]
Victoria mentioned [here](https://github.com/mozilla-mobile/fenix/issues/17798#issuecomment-812712088) that this can be done in a follow-up.

**Comment by violasong** [comment]
Yep, moving the badge to "Sign in to sync" can be done as a followup later :)

**Comment by lobontiumira** [comment]
Verified on the 4/9 Nightly build with Samsung Galaxy Note 8 (Android 9), and on Xiaomi mi4i (Android 5.0.2):

![error](https://user-images.githubusercontent.com/40694158/114186587-b39fea00-994f-11eb-998e-a6e653ac25f8.png)

@jonalmeida, @violasong shouldn't there be an error message on the "Signed in as email@email.com" options?

**Comment by eliserichards** [comment]
That is going to be a followup. There isn't UX bandwidth to do that change now.
