### ISSUE TITLE
FNX-5310 ⁃ [Bug] Search suggestions scroll to inconsistent position

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1883]
## Steps to reproduce
1. Go to search fragment
1. Type a query that has suggestions from multiple providers (history, search suggestions, current session, etc.)

### Expected behavior
1. RecylerView is pinned to the top, user is able to scroll down

### Actual behavior
1. The RecyclerView scrolls to a random position 

### Device information
* Galaxy S9 Android 9.0

![scroll ](https://user-images.githubusercontent.com/4400286/56505623-f81aec80-64d0-11e9-9b75-d82c28884636.gif)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the latest build 5/2. Devices: S8 (Android 9), Pixel (Android 9), Galaxy Tab (Android 8)
