### ISSUE TITLE
Remove Card Nickname from Credit Card Editor

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18830]
Turns out Card Nickname is not in scope. So, we should remove it from the credit card editor.

**Comment by chrishernan** [comment]
Hi, can I work on this issue? also, is this removing all views with credit card nickname references from the fragment_credit_card_editor.xml, as well as all strings that reference credit card nickname?

**Comment by gabrielluong** [comment]
> Hi, can I work on this issue? also, is this removing all views with credit card nickname references from the fragment_credit_card_editor.xml, as well as all strings that reference credit card nickname?

Yes, that's right. I think we also want to maintain 16dp top margin between the buttons and the last field. I am bit on the fence about whether or not to remove the string right now in case we decide to add credit card nickname in the future or just to decide to add it back into scope.

**Comment by chrishernan** [comment]
Gotcha. I don't think leaving the strings hurts anything so I will leave them alone and get rid of the nickname views.
