### ISSUE TITLE
[Telemetry] Send an event when users open the toolbar menu

### ISSUE THREAD

**Issue by tdsmith** [mozilla-mobile/fenix#18855]
## Description & Product Manager / Data Scientist User Story

In order to understand whether we can improve the effectiveness of each messaging surface we’re testing in the set-default experiment (mozilla-mobile/fenix#18796), we should understand how many people see our messages at all. This relates to the branch described in #18608.

As a data scientist, I want to know how often users view the toolbar menu. I would like to observe a Glean event each time users view the toolbar menu.

## What questions will you answer with this data?

How many users will see, saw, or could have seen the message we will place on the toolbar menu?

## Acceptance Criteria
- [ ] ~ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.~ Let's discuss in this ticket if you have any questions.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by lobontiumira** [comment]
Verified on the 4/20 Nightly build with Google Pixel (Android 10) that the following events are visible - ping 30304923-e389-4c4c-a99c-e41518c6afcf:
* toolbar_menu_visible:
```
{
          "category": "events",
          "name": "toolbar_menu_visible",
          "timestamp": 2429
        }
```
* default_browser_changed:
```
{
          "category": "events",
          "name": "default_browser_changed",
          "timestamp": 8631
        }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2104200001)
[Logcat.txt](https://github.com/mozilla-mobile/fenix/files/6341383/logcat.txt)


@Amejia481 **I cannot** trigger the "toolbar_menu_clicked". Am I missing something? Thank you!
```
experiments_default_browser:
  toolbar_menu_clicked:
    type: event
    description: |
      Set default browser was clicked from toolbar menu
```

**Comment by Amejia481** [comment]
Thanks @lobontiumira, sorry for no clarifying earlier `experiments_default_browser#toolbar_menu_clicked` needs the default browser experiments to be setup in the server, that it hasn't be done yet.

I will close the issue as the probes that don't require experiments are working.
