### ISSUE TITLE
[Telemetry] Send an event when users click on the "set as default browser" card in the settings page

### ISSUE THREAD

**Issue by tdsmith** [mozilla-mobile/fenix#18852]
## Description & Product Manager / Data Scientist User Story

In order to understand whether we can improve the effectiveness of each messaging surface we’re testing in the set-default experiment (mozilla-mobile/fenix#18796), we should understand how many people interact directly with our message.

As a data scientist, I want to know, using a Glean event, if a user interacted with the "set as default browser" card in the settings page, which we will test in the branch described by https://github.com/mozilla-mobile/fenix/issues/18376.

## What questions will you answer with this data?

* How many people clicked on the message that we presented?
* When they set to default and the system dialog shows up, how many users **actually** set us as default?
   * How many people simply close the dialog and do not follow through with setting to default?

## Acceptance Criteria
- [x] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [x] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by lobontiumira** [comment]
Verified as fixed on a debug Nightly build #2015805929, GV 89.0a1-20210418092832 with Google Pixel (Android 10):
* ping: a546b63f-afea-4a6e-9088-e56404bd0009
* the event is generated every time the user taps on the "Set as default browser" button from Settings - please see the attached photo
* [Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2104230001)
* [Logcat.txt](https://github.com/mozilla-mobile/fenix/files/6365267/Logcat.txt)

```
{
          "category": "set_default_setting_experiment",
          "name": "set_default_browser_clicked",
          "timestamp": 20399
        }
```

<img src="https://user-images.githubusercontent.com/40694158/115871108-c84ca980-a448-11eb-9acf-56e37c9bb6b8.jpg" width="300" height="550" />
