### ISSUE TITLE
[Telemetry] Send an event when users open the settings menu

### ISSUE THREAD

**Issue by tdsmith** [mozilla-mobile/fenix#18856]
## Description & Product Manager / Data Scientist User Story

In order to understand whether we can improve the effectiveness of each messaging surface we’re testing in the set-default experiment (mozilla-mobile/fenix#18796), we should understand how many people see our messages at all. This relates to the branch described in #18376.

As a data scientist, I want to know how often users view the settings menu. I would like to observe a Glean event each time users view the settings menu.

## What questions will you answer with this data?

How many users will see, saw, or could have seen the message we will place on the settings menu?

## Acceptance Criteria
- [ ] ~ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.~ Let's discuss in this ticket if you have any questions.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by mcarare** [comment]
@tdsmith There already is an event that tracks when the settings button is clicked from the browser menu implemented as requested here: https://github.com/mozilla-mobile/fenix/issues/1024.

My question for you is if we should just add the event trigger to the menu from the new tab screen, or should we add an event for the settings screen being displayed. The difference would be that while we currently track actions in the menu that open the settings screen, the settings screen could be also displayed when going back from a sub-settings screen. 

Which one of these counts would be more suitable for this experiment?

**Comment by tdsmith** [comment]
I think you're right that the browser_menu_action event has the coverage we need. Thanks!

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/19 Nightly build with Google Pixel (Android 10).
Ping: ccdad38d-90d0-42a8-bfaa-f3cd10e12df3
```
{
          "category": "home_menu",
          "name": "settings_item_clicked",
          "timestamp": 3918
        }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2104190001)
