### ISSUE TITLE
[Telemetry] Send a Glean event when users change their default browser

### ISSUE THREAD

**Issue by tdsmith** [mozilla-mobile/fenix#18857]
## Description & Product Manager / Data Scientist User Story

In #12103/#13003 we started sending Leanplum events marking when users changed their default browser. For the purposes of the set-default experiment (#18796) and future experimentation, it would be convenient to emit these as Glean events as well so that we can observe changes to the default browser in the same ping as interactions with the UI elements we're instrumenting.

As a data scientist, I want to be able to observe a Glean event when users switch their default browser to Fenix.

@eliserichards, I think this relates to the comment thread in https://docs.google.com/document/d/1fcG8V54gdEywQcSRJTsBNgzOM3EQWnmPF7jqElxpzcs/edit -- I'm not sure if there's a more direct signal we can use versus checking "is the default browser state what we remembered it was," which is what I think the Leanplum event does—either option seems fine to me.

## Acceptance Criteria
- [ ] ~ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.~ Let's discuss here instead as needed.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by Amejia481** [comment]
Just for context we are also sending   [default_browser](https://github.com/mozilla-mobile/fenix/blob/5560d7de016054509fc9a596468c43f1e38bbeb0/app/metrics.yaml#L748)

**Comment by tdsmith** [comment]
Thanks for the callout. Having both the state and the transitions represented in telemetry for important lifecycle events helps us avoid having to synthesize one from the other, which can be annoying or expensive.

I see the `events.set_default_browser_experiment` event in #18982; I think an event that does not depend on this particular experiment will facilitate tracking set-default rates going forward, since I think we're probably going to return to this well for future experiments.

**Comment by tdsmith** [comment]
Oh: the other thing that we need is an event that we can observe in the control branch, which we don't get from #18982.
