### ISSUE TITLE
[Telemetry] Send an event when users click on the "set as default browser" entry in the toolbar menu

### ISSUE THREAD

**Issue by tdsmith** [mozilla-mobile/fenix#18851]
## Description & Product Manager / Data Scientist User Story

In order to understand whether we can improve the effectiveness of each messaging surface we’re testing in the set-default experiment (mozilla-mobile/fenix#18796), we should understand how many people interact directly with our message.

As a data scientist, I want to know, using a Glean event, if a user interacted with the "set as default browser" entry in the toolbar menu, which we will test in the branch described by https://github.com/mozilla-mobile/fenix/issues/18608.

## What questions will you answer with this data?

* How many people clicked on the message that we presented?
* When they set to default and the system dialog shows up, how many users **actually** set us as default?
   * How many people simply close the dialog and do not follow through with setting to default?

## Acceptance Criteria
- [x] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [x] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by eliserichards** [comment]
@Amejia481 I added some more context to the description. We want to know if a user starts the set to default flow and doesn't follow through (the user clicked set default but then didn't actually set the default when they are prompted by the system dialog)
