### ISSUE TITLE
[Telemetry] Send an event when users view the new tab screen

### ISSUE THREAD

**Issue by tdsmith** [mozilla-mobile/fenix#18854]
## Description & Product Manager / Data Scientist User Story

In order to understand whether we can improve the effectiveness of each messaging surface we’re testing in the set-default experiment (mozilla-mobile/fenix#18796), we should understand how many people see our messages at all. This relates to the branch described in #18375.

As a data scientist, I want to know how often users view the new-tab UI. I would like to observe a Glean event each time users view the new-tab UI.

There is a [new tab tapped](https://dictionary.protosaur.dev/apps/fenix/metrics/tabs_tray_new_tab_tapped) event. If there's no other way that users experience new tab, this new telemetry isn't a high priority.

## What questions will you answer with this data?

How many users will see, saw, or could have seen the message we will place on new tab?

## Acceptance Criteria
- [ ] ~ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.~ Let's discuss in this ticket if you have any questions.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/19 Nightly build with Google Pixel (Android 10).
Ping: de13230d-0cbb-4393-b51d-8fa11679e435
```
{
          "category": "home_screen",
          "name": "home_screen_displayed",
          "timestamp": 3333
        }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2104190002)
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/6334830/logcat.txt)
