### ISSUE TITLE
[Telemetry] Send an event when users interact with the "set as default browser" card on the new tab

### ISSUE THREAD

**Issue by tdsmith** [mozilla-mobile/fenix#18853]
## Description & Product Manager / Data Scientist User Story

In order to understand whether we can improve the effectiveness of each messaging surface we’re testing in the set-default experiment (mozilla-mobile/fenix#18796), we should understand how many people interact directly with our message.

As a data scientist, I want to know, using a Glean event, if a user interacted with the "set as default browser" card on the new tab page, which we will test in the branch described by https://github.com/mozilla-mobile/fenix/issues/18375.

Distinct events should be sent for:

- selecting "set as default browser"
- dismissing the card using the X icon

## What questions will you answer with this data?

* How many people clicked on the message that we presented?
* When they set to default and the system dialog shows up, how many users **actually** set us as default?
   * How many people simply close the dialog and do not follow through with setting to default?

## Acceptance Criteria
- [x] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [x] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by lobontiumira** [comment]
Verified as fixed on a debug Nightly build #2015805929, GV 89.0a1-20210418092832 with Google Pixel (Android 10):
* ping: f9239b73-8659-4ed7-9402-3f047419b60c
* set_default_newtab_clicked event:
```
{
          "category": "set_default_newtab_experiment",
          "name": "set_default_browser_clicked",
          "timestamp": 3630
        }
```

* ping: 957c1071-3033-45e6-8fbe-2224695d6b95
* close_experiment_card_clicked event:
```
{
          "category": "set_default_newtab_experiment",
          "name": "close_experiment_card_clicked",
          "timestamp": 774
        }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2104230002)
[telemetry logcat.txt](https://github.com/mozilla-mobile/fenix/files/6365377/telemetry.logcat.txt)
