### ISSUE TITLE
Website exception only from cookie block, not from ETP overall

### ISSUE THREAD

**Issue by Username1-a** [mozilla-mobile/fenix#18865]
Since some often used websites could benefit from exception from cookie block (staying logged in to some websites; remembering user preferences; some outright refusing to work properly with third-party cookie block enabled), but at the same time user could benefit from enabled Enhanced Tracking Protection on them – would be great to have an option to allow cookie storing for current website without turning off ETP completely.

Here's mockup of how this option could look like:

![Firefox Android - Cookie Block Exception Mockup.png](https://user-images.githubusercontent.com/47947180/113965671-7dbb1280-9836-11eb-810d-5288f18e6e5e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10285)

**Comment by Amejia481** [comment]
You can customize your cookies preferences by Taping on the shield icon -> Protection  **Settings** -> **Custom** -> **Cookies**.  This is global setting and It will affect all websites, I think you were looking for something per site, but this will be a workaround.

**Comment by TheGreySquare** [comment]
> You can customize your cookies preferences by Taping on the shield icon -> Protection  **Settings** -> **Custom** -> **Cookies**.  This is global setting and It will affect all websites, I think you were looking for something per site, but this will be a workaround.

Thank you, yes I know about this, but as I mentioned custom per-site option would be better in some instances

**Comment by Amejia481** [comment]
👍🏽 I added the feature request label for the product team to triage it!
