### ISSUE TITLE
Bookmark Import from/Export to file support

### ISSUE THREAD

**Issue by TheGreySquare** [mozilla-mobile/fenix#18864]
Please, consider adding support for bookmark importing from/exporting to file directly from Firefox on Android, without requiring to install Firefox on PC first.
It would make migrating from other browsers to Firefox much easier.
As for file compatibility – Chromium browsers/ their PC versions should probably have the same structure of the exported bookmarks file, so I don't think there would be any problems.

### Who will benefit from it?

Users who don't have PC/ who have bookmarks file lying around.

**Comment by sflorean** [comment]
Thank you for report! Issue #417 is already filed for this request. Please follow the discussion there, I will close this as duplicate.
