### ISSUE TITLE
FNX-5312 ⁃ [Bug] Bookmark fragment title color not reset on back press

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1886]
## Steps to reproduce
1. Open bookmarks (in library fragment)
1. Enter edit mode
1. Press back

### Expected behavior
1. I navigate backwards and the title bar is reset in color

### Actual behavior
1. I navigate backwards and the title bar keeps the "edit state" color

**Comment by sv-ohorvath** [comment]
Verified as fixed. build 4/24.
