### ISSUE TITLE
[Bug] Three-dot menu refresh leaves lots of empty space

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#18867]
## For QA
See UX comments on this issue, we are removing the "Signed in as" string from the sync sign in item.

---

## Steps to reproduce
- Use a nightly build with the three-dot menu refresh (after 08/04/21).
- Sign in to Sync with a long username.
- Open the menu.

### Expected behaviour
- A more compact menu that allows for more web content to be seen.

### Actual behaviour
- There is a lot of empty space in the menu that seems unused.
- See the screenshot below that includes layout bounds for reference.

![output](https://user-images.githubusercontent.com/1370580/113970639-39634e80-9805-11eb-8be3-4688632fb497.png)

### Device information

* Device vendor / model and Android version: Android 10, Pixel 3
* Firefox for Android version: Nightly 08/04/21

**Comment by jonalmeida** [comment]
I've added this to the project board, but I'm not sure what's the preferred way to surface bug reports for this feature to be triaged.

cc: @eliserichards for now.

**Comment by amedyne** [comment]
tagging @violasong and @topotropic for this, too.

**Comment by violasong** [comment]
That looks a lot wider than the screenshot [here](https://github.com/mozilla-mobile/android-components/pull/10039) - I wonder why?

**Comment by jonalmeida** [comment]
> That looks a lot wider than the screenshot [here](https://github.com/mozilla-mobile/android-components/pull/10039) - I wonder why?

The screenshot here doesn't have a Sync account signed in. That might affect it.

**Comment by violasong** [comment]
Ah, it would be ideal to use the narrower width in both situations, but I know deadlines are looming.

In the future, we can also represent the signed in state as `[avatar icon] username@email.com` to reduce the length of that list item. Flagging for @brampitoyo in case this helps with the iOS toolbar menu.

**Comment by smowtenshi** [comment]
> In the future, we can also represent the signed in state as `[avatar icon] username@email.com` to reduce the length of that list item. 

Is this necessary when you can look that in the settings? In my opinion it's a really useless information.

**Comment by brampitoyo** [comment]
@jonalmeida I agree with @violasong in advising to remove the words “Signed in as…”

Instead, we can just show the email address on its own, plus an avatar icon symbol.

I’m also confirming the fact that “Synchronised tabs” will eventually longer be located inside the App Menu? Instead, we’re planning to put it inside the Tab Tray.

**Comment by eliserichards** [comment]
I believe that our width is being calculated based on the width of the screen. This is especially helpful for the Sync Sign In item and for non-english languages that tend to be longer (like German).

**Comment by jonalmeida** [comment]
> We can definitely update to not include "Signed in as" for the sync item if we have your approval :)

See Bram's response above: https://github.com/mozilla-mobile/fenix/issues/18867#issuecomment-817481461

**Comment by brampitoyo** [comment]
Thanks @jonalmeida! @eliserichards, by only including email address in this FxA menu item, our approach will be identical across platforms.

#### Desktop

<img width="294" alt="Screen Shot 2021-04-14 at 2 26 36 PM" src="https://user-images.githubusercontent.com/51007/114645358-6c3da300-9d2d-11eb-8660-45d50b6ad6f4.png">

#### iOS

<img width="360" alt="Shadow@2x" src="https://user-images.githubusercontent.com/51007/114645523-c50d3b80-9d2d-11eb-81a1-b5132da30242.png">

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Nightly 4/19 with Pixel 2 (Android 9).

**Comment by sflorean** [comment]
> This issue is still reproducible on Nightly 4/19 with Pixel 2 (Android 9), the empty space is still visible.
> The "Signed in as" is removed now.
> @jonalmeida Is this expected?
> ![rsz_screenshot_20210419-102504](https://user-images.githubusercontent.com/48799384/115197661-e6897100-a0f9-11eb-96ad-caffc454f796.png)

cc @eliserichards

**Comment by azerto11** [comment]
> > This issue is still reproducible on Nightly 4/19 with Pixel 2 (Android 9), the empty space is still visible.
> > The "Signed in as" is removed now.
> > @jonalmeida Is this expected?
> > ![rsz_screenshot_20210419-102504](https://user-images.githubusercontent.com/48799384/115197661-e6897100-a0f9-11eb-96ad-caffc454f796.png)
> 
> cc @eliserichards

Hi, are there any further changes planned for this?
