### ISSUE TITLE
Long DNS resolution times (on start up only?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#18861]
We sometimes see DNS resolution times that are 500+ ms. They usually take 10s of ms so it would be a huge win to address this. See the following bugs for more details:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1702025
- https://bugzilla.mozilla.org/show_bug.cgi?id=1664492
- https://bugzilla.mozilla.org/show_bug.cgi?id=1583298

The root cause appears to be that the system resolver takes a long time to execute.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10282)

**Comment by mcomella** [comment]
Triage: in Q2 we'll determine the priority of DNS resolution. In the waiting column until then.

**Comment by reyis4402** [comment]
I'm glad you start working to fix this problem. Good news :)

**Comment by mcomella** [comment]
Triage: it turns out we may be misreporting our DNS times https://bugzilla.mozilla.org/show_bug.cgi?id=1596935#c21, which could mean our DNS resolution times are not actually that long in practice. We should address that and attempt to reproduce. After that, from the bugs linked above, it seems the root issue is that the system DNS resolver we're using can be slow. We'd have to implement a whole new resolver: DoH might do this but it's unclear to me from the comments.

**Comment by andrewshadura** [comment]
This issue should not have been closed. Bump.

**Comment by mcomella** [comment]
Triage: we looked at (beta channel) telemetry. The `network.dns_end` probe, which uses the `HTTP_PAGE_LOOKUP_DNS_TIME` timing, doesn't indicate this is a significant problem: it's in the same ballpark as desktop (268ms at 95th vs. low 200s on desktop), assuming the probe is accurate. However, it's possible 1) this probe is inaccurate, 2) the probe only takes into account the Gecko experience and omits something in ac/fenix that contributes to a longer delay, or 3) this problem is only on start up, which the telemetry under represents.

The next steps are to have the perf or network team investigate further to better understand why this could occur.

**Comment by andrewshadura** [comment]
I guess either the probe is inaccurate, or the issue affects only some subset of users and fewer of them use beta.
I run release only, and I experience stalls almost each time, sometimes they’re extreme (30 seconds or more). I wasn’t able to correlate that to changes in the environment (network, memory, CPU load etc) so far.
I have installed Nightly in a hope this can reveal more.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807322

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
