### ISSUE TITLE
[Bug]New tab/Sync floating bubble stays on even after closing tab tray with the new tabs tray 

### ISSUE THREAD

**Issue by karan-kamat** [mozilla-mobile/fenix#18876]
## Steps to reproduce

1.Enable "Use new Tabs Tray" in secret settings
2. Open a web page
3. Open tab tray
4. Close tab tray

### Expected behavior
Tab tray closes with no remaining UI elements

### Actual behavior
The "+" floating button in case of normal tabs , The "+ PRIVATE" button in case of private tabs and "SYNC" button in synced tabs remains despite closing the tab tray

### Device information

Samsung Galaxy M51
Android 11 with One UI Core 3.1
Firefox Nightly 210408 14:26 
Build #2015803443

![nightly-tab-tray](https://user-images.githubusercontent.com/59926956/114059068-a03e4180-98b1-11eb-9459-71fb251e97be.gif)

**Comment by sflorean** [comment]
I wasn't able to reproduce this on latest Nightly. @karan-kamat please try again, and post here the results because some fixes were landed. Thank you!

**Comment by karan-kamat** [comment]
I check again and the issue no longer exists.
Thank you.
