### ISSUE TITLE
[Bug] Can't access private tabs after enabling New Tab tray

### ISSUE THREAD

**Issue by karan-kamat** [mozilla-mobile/fenix#18878]
## Steps to reproduce
1.Enable "Use new Tabs Tray" in secret settings
2.Open a new private tab
3. Open tab tray
4. Open the same private tab

### Expected behavior
Private tab opens
### Actual behavior
Private tab does not open
### Device information

Samsung Galaxy M51
Android 11 with One UI Core 3.1
Firefox Nightly 210408 14:26
Build #2015803443

![nightly-private](https://user-images.githubusercontent.com/59926956/114062311-01b3df80-98b5-11eb-9cc8-38e5187e0a64.gif)

**Comment by sflorean** [comment]
@karan-kamat thank you for report! I wasn't able to reproduce the issue on latest Nightly build following your steps. Some fixes were landed, and it will be helpful to check again. 
Devices used:
- LG G7 Fit (Android 8.1)
- Samsung Note 10 (Android 11)

**Comment by karan-kamat** [comment]
I checked again and the issue no longer exists
