### ISSUE TITLE
[Bug] `about:config` resets itself upon close after 4/6 nightly update

### ISSUE THREAD

**Issue by sharbet** [mozilla-mobile/fenix#18871]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
I don't know how to replicate the issue; it seems to be turned off randomly.

I use Adguard for Android, and it is crucial that I have this option turned on (true) for fenix to connect to the web.

This has occurred to me at least 5 times.

### Device information

* Device vendor / model and Android version: Android 11, Galaxy S20+
* Firefox for Android version: ? (go to Settings -> About Firefox)
Nightly 210407 17:03 (Build #2015803275)
AC: 75.0.20210407143059, 54395a6fa
GV: 89.0a1-20210407094544
AS: 74.0.1

**Comment by Alexey71** [comment]
Parameters are reset every time the application is close from running app

**Comment by sharbet** [comment]
> 
> 
> Parameters are reset every time the application is close from running app

Before 4/6 update, about:config parameters were saved even when app is closed from running app.

**Comment by What-Zit-Tooya** [comment]
Im faced this bug also.
Got it also since April 3, 2021 (dunno nightly version exactly), till now not fixed.
Parameter reset to default (false) after exiting firefox. And remove it from running app in background (full closed).

**Comment by sharbet** [comment]
I have found other people with same issue:

https://www.reddit.com/r/Adguard/comments/mm01bh/firefox_mobile_nightly_reset_a_security_setting/

**Comment by jobbautista9** [comment]
My suggestion to the devs is to close this issue as WONTFIX, and use their time for something more important instead, like improving the UI. This "https filtering" scam (seriously, why don't they just call it MITM instead? That would be a more honest and accurate description) needs to stop.

**Comment by Alexey71** [comment]
> 
> 
> My suggestion to the devs is to close this issue as WONTFIX, and use their time for something more important instead, like improving the UI. This "https filtering" scam (seriously, why don't they just call it MITM instead? That would be a more honest and accurate description) needs to stop.

I have a counter offer. Before you write any bullshit, think 10 times

**Comment by sharbet** [comment]
> My suggestion to the devs is to close this issue as WONTFIX, and use their time for something more important instead, like improving the UI. This "https filtering" scam (seriously, why don't they just call it MITM instead? That would be a more honest and accurate description) needs to stop.

Wow thank you for your non-productive answer that contributes nothing to this matter whatsoever!

I am so glad you are not someone I am acquainted with. With regards to how you respond, I don't think anyone would want to be acquainted with you :)

**Comment by ezaquarii** [comment]
@jobbautista9 there are genuine cases for using custom certificates, like accessing intranet in enterprise environment.

**Comment by sharbet** [comment]
Re-admitted
