### ISSUE TITLE
FNX-5313 ⁃ Overwrite the user agent on Google domains.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1887]
### Why/User Benefit/User Problem
Google refuses to make its websites work on the competitors' web browser the same way they work on Chrome. The experience is not the best on Fenix either. Faking the user agent to looks like Chrom(e/ium) solves the problem, specially given that Fenix doesn't support extensions yet.

### What / Requirements
Fenix sends a Chromium user agent to google websites.

### Acceptance Criteria (how do I know when I’m done?)
Fenix receives the same full google websites as Chrome.

**Comment by vesta0** [comment]
Thanks for filing. We are working on a solution for this :)
