### ISSUE TITLE
[Bug] Make id/mozac_browser_menu_recyclerView layout element scrollable for UI test automation

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#18873]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
**!!This doesn't affect the user's interaction in real life**. This bug is only a request for help to ease up writing automated tests.

## Steps to reproduce
In UI test automation, to be able to perform scrolling actions on a list, it has to have a "scrollable" property.
The browser view main menu recyclerView (id/mozac_browser_menu_recyclerView) element doesn't have this property so we can't use any of Espresso's [RecyclerViewActions ](https://developer.android.com/reference/androidx/test/espresso/contrib/RecyclerViewActions) or UiAutomator's [UiScrollable ](https://developer.android.com/reference/androidx/test/uiautomator/UiScrollable) class to find elements below the fold.

The swipeUp/swipeDown methods sometimes mistakenly click on UI elements.

See a comparison between the Settings list and the Main menu:
![recyclerViews](https://user-images.githubusercontent.com/4037709/114052795-08335e80-9897-11eb-999c-70c641cd1963.png)

### Device information

* Device vendor / model and Android version: Pixel 2 emulator
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by Mugurell** [comment]
The menu is initially collapsed and the first swipe up will expand it.
Then it should be scrollable like expected and I see this working in manual tests so a quick fix would be just do do another swipe up to scroll the menu and see the bottom most items.
But I understand that is finicky on an emulator.

I don't know what that `scrollable` property in UIAutomator checks since that is not a RecyclerView property and is not set or unset in code but will check what can be done.

**Comment by Mugurell** [comment]
If someone knows a "quick fix" for this would be great.

**Comment by Mugurell** [comment]
Tried to scroll progrmatically with the following code called when the menu opens
>     MainScope().launch {
>       delay(3000)
>       menuList!!.scrollToPosition(2)
>       delay(3_000)
>       menuList!!.scrollToPosition(16)
>     }
and I see the menu scrolling as expected so I'm still not sure what UiAutomator checks.
