### ISSUE TITLE
[Saved cards] Add button for "Add credit card"

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#18881]
We have an PR for this in https://github.com/mozilla-mobile/fenix/pull/19236 with some feedback on the remaining work https://github.com/mozilla-mobile/fenix/pull/19236#discussion_r634423665. Please consider using this.

------

This issue for adding a "Add credit card" button in the "Saved cards" screen. This should navigate to the credit card editor.

<img width="379" alt="Screen Shot 2021-04-08 at 2 11 34 PM" src="https://user-images.githubusercontent.com/1190888/114076612-d7423200-9874-11eb-9c1a-63074c39ea7c.png">

**Comment by chrishernan** [comment]
Hello, Could I work on this issue?

**Comment by gabrielluong** [comment]
> Hello, Could I work on this issue?

Thanks, go for it. We plan to ship the feature in the next May release so I think there is demand to pick this work up. Since no one has picked it up, I am happy to have anyone pick up work where it is reasonable. I think I do have to mention that the team can take over the issue where it is reasonable in order to hit our releasee deadline.

**Comment by gabrielluong** [comment]
Since the list of credit cards is a RecyclerView, the only known solution I have seen is using a ConcatAdapter. I am happy to entertain other solutions if you are aware of better solutions, but I hope this points a little point of guidance. I am still fairly new with Android development.

**Comment by chrishernan** [comment]
Gotcha. I'll look into it. I'm pretty sure you know your stuff. Because if you're new, then I'm in elementary school when it comes to this stuff. Still learning and trying to become an androi dev haha.

**Comment by gabrielluong** [comment]
We have an PR for this in https://github.com/mozilla-mobile/fenix/pull/19236 with some feedback on the remaining work https://github.com/mozilla-mobile/fenix/pull/19236#discussion_r634423665.

**Comment by gabrielluong** [comment]
@eliserichards I am gonna open this up in case someone can pick it up quickly since you already have several P1 tickets needed for Thursday. Feel free to pick it back up if no one gets to it.

**Comment by ionutbedregeanu** [comment]
I would like to work on this ticket

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/26** with **OnePlus Nord (Android 10).**
