### ISSUE TITLE
[Bug] The new page menu cannot be scrolled entirely in portrait mode on Android 5 and 6 devices

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18896]
## Steps to reproduce
1. Install the 4/9 Nightly build which has the new design changes.
2. Open a page and open the three-dot menu.

### Expected behavior
The page menu is scrollable and expandable.

### Actual behavior
The page menu cannot be entirely scrolled.

### Device information
* Device vendor / model and Android version: Samsung Galaxy Tab A6 (Android 5.1.1)
* Firefox for Android version: 4/9 Nightly
* Not reproducible in landscape mode
* Not reproducible on Xiaomi Mi4i (Android 5.0.2)

https://user-images.githubusercontent.com/40694158/114182922-e811a700-994b-11eb-9df3-0ad652ea9b18.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10300)

**Comment by Mugurell** [comment]
I see it's not properly anchored. Does the menu look ok in the current beta?

**Comment by lobontiumira** [comment]
The new changes had not benn implemented in Beta yet.

**Comment by Mugurell** [comment]
Confirmed with Mira that the Beta on this device looks okay so something broke in the meantime.

**Comment by lobontiumira** [comment]
Reproducible on RC 89.1.0 on the same device, Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
Reproducible also on Amazon Fire (KFFOWI), Android 5.1.1, on RC 89.1.1-armeabi-v7a (see #19973).

**Comment by rhendric** [comment]
Get outta here, bot! I care about this.

**Comment by rhendric** [comment]
Shoo, bot! Shoo!

**Comment by AdinaPetridean** [comment]
I was able to reproduce the issue on latest Nightly 109.0a1, Beta 108.0b5 and RC 107.2.0 with Samsung Galaxy Tab A6 (A 5.1.1) and Sony Xperia (Android 6.0.1).
Please note on Firefox RC 107.2.0 the 3 dots menu didn't open at all with Sony Xperia (Android 6.0.1).



https://user-images.githubusercontent.com/108326843/204504940-8dddbdc1-d02c-4257-9244-c658d6091af1.mp4

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809241

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
