### ISSUE TITLE
The new menu style has led to obstacles in using certain functions

### ISSUE THREAD

**Issue by Rosabis** [mozilla-mobile/fenix#18893]
1. Compared to the previous menu style, you will find it cumbersome to use the refresh, forward and back functions, you will need to scroll down to show the full menu to use these functions
2. You need to create a new tab to use the exit browser function, but with the previous menu style, you can exit the browser by opening the menu from the opened page and selecting exit.
![IMG_20210409_163501](https://user-images.githubusercontent.com/32984303/114153092-8eac7680-9951-11eb-911a-c464bb9116fd.jpg)
![IMG_20210409_163439](https://user-images.githubusercontent.com/32984303/114153119-95d38480-9951-11eb-9f4e-7f5806eb9190.jpg)

**Comment by cadeyrn** [comment]
> Compared to the previous menu style, you will find it cumbersome to use the refresh, forward and back functions, you will need to scroll down to show the full menu to use these functions

The new menu is not yet ready, see #17796 and especially #17772.

**Comment by sheikh-azharuddin** [comment]
Quit button is now missing...only available in home screen

![Screenshot_20210409-160353071](https://user-images.githubusercontent.com/58127841/114168065-615dc980-994d-11eb-82db-97ba8b15d303.jpg)

**Comment by Mugurell** [comment]
@Rosabis the navigation bar will will soon come back, even for the collapsed menu. In the meantime one can scroll to it.

Tagging @eliserichards for the "Quit" button.

**Comment by lobontiumira** [comment]
I've filed #18898 for the "Quit" option.

**Comment by USvsTHEM** [comment]
scrollabke menu is trash yall gotta slow down Mannn yall killing the underdog nobody likes Google !!! yall hiding the hottest buttons

**Comment by amedyne** [comment]
Closing this issue. The menu is scrollable and #18898 has been closed.
