### ISSUE TITLE
[Bug] The "Quit" option is no longer available in the new page menu

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#18898]
## Steps to reproduce
1. Install the 4/9 Nightly that has the new design changes.
2. Go to Settings - Delete browsing data on quit and enable the toggle.
3. Open a page and tap on the three-dot meu.
4. Expand the entire menu and observe the "Quit" option.

### Expected behavior
The "Quit" option is available in both menus: the homescreen menu, and the page menu.

### Actual behavior
The "Quit" option is available only on the homescreen three-dot menu, not in the page menu.

### Device information
* Devices: all
* Firefox for Android version: 4/9 Nightly

https://user-images.githubusercontent.com/40694158/114189292-b819d200-9952-11eb-8081-61270791b30c.mp4

**Comment by Queuecumber** [comment]
If some progress was made on #5865 this wouldn't be an issue

**Comment by JoGarWeb** [comment]
I WANT QUIT OPTION BACK !!!

**Comment by x2k13** [comment]
This is new since like the last 3 updates. And it is very annoying. Sometimes I want to close (and clear browserdata on quit) the browser when on a website. Having to close all tabs to be able to close the browser is a major nuissance.

**Comment by cadeyrn** [comment]
A patch already landed, it will be in the next Nightly build.

**Comment by x2k13** [comment]
> A patch already landed, it will be in the next Nightly build.

Good news.

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/13 Nightly build with Samsung Galaxy Note 8 (Android 9).
