### ISSUE TITLE
[ANR] Context.startForegroundService did not then call Service.startForeground()

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18903]
This is the ANR with the highest amount of impacted users. 

```
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{cbb0924 u0 org.mozilla.firefox/org.mozilla.fenix.media.MediaSessionService}
```

App Store Console: https://play.google.com/console/u/0/developers/7083182635971239206/app/4972519468758466290/vitals/crashes/ee5a31fb/details?installedFrom=PLAY_STORE&days=30

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10307)

**Comment by csadilek** [comment]
Sentry: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6026738/?query=is%3Aunresolved%20MediaSessionService

I think we should prioritize this.

**Comment by Amejia481** [comment]
This is still happening https://sentry.io/organizations/mozilla/issues/3262966409/?project=6375561&query=is%3Aunresolved
