### ISSUE TITLE
When reopening a closed page, it is still displayed in "Recently closed tabs" 

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#18900]
## Prerequisites
Have at least one tab open.

## Steps to reproduce
1. Close a tab.
2. Go to Tabs Tray -> three dots menu -> Recently closed tabs.
3. Tap on three-dot menu from the recently closed tab.
4.  Tap on "Open in new tab".
5. Observe the "Recently closed tabs" page. 

### Expected behavior
A new tab is opened and the page is not listed anymore in "Recently closed tabs" page. 

### Actual behavior
The page is still listed in the "Recently closed tabs" page. 

### Device information

* Device vendor / model and Android version: HTC Nexus 9
* Firefox for Android version: Firefox Nightly 210409 05:01.
 
##Video

https://user-images.githubusercontent.com/48829350/114196977-9290c680-995a-11eb-9afc-eb65522b8010.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10306)

**Comment by thunderblood101** [comment]
I'm able to reproduce this bug as well.

**Comment by Nickoriginal** [comment]
Reproducible in the Firefox 89.1.1 on the Samsung Galaxy A20s (Android 10) and Samsung Galaxy J2 Prime (Android 6.1.1)
https://user-images.githubusercontent.com/85299944/124124770-8318a980-da81-11eb-8103-76852c7ed840.mp4

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly (2021-12-29).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812881

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
