### ISSUE TITLE
How does Fenix generate list.json in search and the xml files in searchplugins?

### ISSUE THREAD

**Issue by imnotabr** [mozilla-mobile/fenix#18908]
How are the files in these 2 folders generated?

This file, list.json
fenix/app/build/intermediates/merged_assets/debug/out/search/list.json

All the .xml files in this folder
fenix/app/build/intermediates/merged_assets/debug/out/searchplugins/

When I try to change list.json in search, or add/delete/modify .xml files in searchplugins, the changes are reverted when I run the app and I get the response "Files under the "build" folder are generated and should not be edited".

How are these folders generated and how can these files be modified?

**Comment by imnotabr** [comment]
@mcarare do you know how to change these folders and files?

**Comment by clauub** [comment]
@imnotabr If you want to override these files you have to do following things: 
You have to add in src/main/assets these two directories:

- search (here you create a list.json for your needs)
- searchplugins (put all search plugins, that you'll be using in your app) 

Hope you understood. Let me know if you have more questions !
