### ISSUE TITLE
[Bug]new scrolling menu is terrible 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#18917]
honestly I ve lost any hope in fenix and Firefox in general the new scrolling menu is a time wasting design, what are the developer thinking?
can someone confirm it will stay scrollable so I can switch to Samsung browser once for good?

**Comment by JoGarWeb** [comment]
I Agree. Firefox Team always make firefox unusable everyday. 🤦🏻‍♂️🤦🏻‍♂️

**Comment by eliserichards** [comment]
Friendly reminder that this repository adheres to Mozilla's community participation guidelines.
