### ISSUE TITLE
Use mDNS for Firefox Sync

### ISSUE THREAD

**Issue by Amarjit3** [mozilla-mobile/fenix#18919]
Is it possible to add the use of mDNS name resolution when specifying the location of the Firefox Sync server within Android? I understand mDNS is accessible in Android within applications themselves.

Currently, I'm self-hosting a Firefox Sync server on my Linux laptop and I would like to point the Android app to Firefox Sync server's location on the laptop. This would be a lot easier if the browser on Android uses mDNS resolution. If I move between WiFi networks, then the Android browser will continue to synchronise with my laptop. At the moment, I would have to pay for a Dynamic DNS service instead.

**Comment by jonalmeida** [comment]
This requires work from multiple projects/teams to get local network discovery and syncing working between desktop/mobile. 

@kbrosnan might know better if this should go to bugzilla or appservices.
