### ISSUE TITLE
[Bug] PWA icon does not load when Cross-Origin-Resource-Policy: same-origin is set

### ISSUE THREAD

**Issue by frigus02** [mozilla-mobile/fenix#18918]
## Steps to reproduce

I made 2 almost identical sites. They should only differ in one point:

- https://corp-icons.glitch.me/ 👉 serves icons with `Cross-Origin-Request-Policy: same-origin` header)
- https://nocorp-icons.glitch.me/ 👉 serves icons without `Cross-Origin-Request-Policy` header)

Test the following with both sites:

1. Open https://corp-icons.glitch.me/ in Fenix (make sure you use https)
2. Click "Install" in the menu to open the dialog to add the site to the home screen

### Expected behavior

The dialog should open and show an icon preview with the apps icon.

<img src="https://user-images.githubusercontent.com/3579251/114277904-7f026000-9a2d-11eb-8e2d-9c2e0e0bea2a.png" width="150" alt="Screenshot of Fenix with PWA dialog open showing a preview of the sites icon">

### Actual behavior

Opening this dialog should take longer than expected (1-2 seconds on my device). The dialog then opens and the icon preview is a white circle.

<img src="https://user-images.githubusercontent.com/3579251/114277870-54b0a280-9a2d-11eb-9b05-f4aed13b8db7.png" width="150" alt="Screenshot of Fenix with PWA dialog of the same site, but this time the icon preview shows a white circle">

### Device information

* Device vendor / model and Android version: Pixel 5, Android 11
* Firefox for Android version: Nightly 210409 17:02 (Build #2015803659)
 
(The bug was originally reported here: #13183. I just tested and it's still valid in the latest Fenix.)

**Comment by eliserichards** [comment]
Thanks for checking on this! Looks like our stale bot killed the original issue :) I reopened with your latest device info.

Closing this as dupe.
