### ISSUE TITLE
The address bar occupies more than space in the toolbar

### ISSUE THREAD

**Issue by bitshelf** [mozilla-mobile/fenix#18912]
### The address bar may be remove in toolbar
People know the pages they visit,I think that the address bar can be replaced by the search icon.
### Set more function buttons
The address bar always takes up more space, but it's almost useless.Set more function buttons to make the browser easier to use

**Comment by TheGreySquare** [comment]
Maybe an additional Samsung Internet/Google Chrome Duet-like toolbar layout setting would solve this – address bar is on the top of the screen and fully customizable toolbar with buttons is on the bottom of the screen
Hope they can add this in the future
[Uploading Screenshot_20210410-091726.jpg …]()

**Comment by bitshelf** [comment]
Ffirefox is power browser.It has many feature,but need multiple clicks.hope add some buttons,as easy to use as Twitter.
![Screenshot_2021-04-12-14-26-06-502_org mozilla firefox](https://user-images.githubusercontent.com/62375119/114351024-9e6bcb00-9b9c-11eb-9c8a-2eff838c2710.jpg)
