### ISSUE TITLE
Top Sites thumbnails removing after clearing history

### ISSUE THREAD

**Issue by Username1-a** [mozilla-mobile/fenix#18911]
Please fix top sites cached thumbnails removing after clearing browser history or quitting browser with enabled "Delete browser data on exit">"Browsing history and site data"

It's pretty unnecessary to clear those thumbnails as they doesn't take much storage space anyway

* Device vendor / model and Android version: Redmi 4X, Android 10 AOSP
* Firefox for Android version: 87 Stable

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10313)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813638

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
