### ISSUE TITLE
[Bug] Not obvious that three dot menu is scrollable

### ISSUE THREAD

**Issue by evilpie** [mozilla-mobile/fenix#18914]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Click on the tree dots
Look for "Settings"

### Expected behavior
Immediately see settings

### Actual behavion

I apparently have scroll the view to see the settings. It's not obvious that the menu is scrollable. Other apps like Chrome have a faded out last menu item that makes it more obvious.

Another solution would be to reduce the size of the menu again.

### Device information

* Device vendor / model and Android version:  Samsung S8
* Firefox for Android version: nightly

**Comment by mrandreastoth** [comment]
What was wrong with displaying the full menu? Why having to scroll something that would otherwise fit on the screen? Please revert this or make it an option.

**Comment by sheikh-azharuddin** [comment]
They could have used firefox lite 3 dot menu implementation...but no👎😡

![Screenshot_20210411-090928465](https://user-images.githubusercontent.com/58127841/114291516-a432b500-9aa5-11eb-97a6-d090f1ba59e9.jpg)

**Comment by mrandreastoth** [comment]
> They could have used firefox lite 3 dot menu implementation...but no👎😡
> 
> ![Screenshot_20210411-090928465](https://user-images.githubusercontent.com/58127841/114291516-a432b500-9aa5-11eb-97a6-d090f1ba59e9.jpg)

Seems like a much cleaner and logical implementation. But why is it still scrollable? What isn't showing?

**Comment by cadeyrn** [comment]
> They could have used firefox lite 3 dot menu implementation...but no👎😡

There is no difference in regards to this issues. Both implementations are a scrollable menu and both indicates that you can scroll in the exact same way - with a half visible menu item. The main difference is the fixed icon bar at the bottom and this will be implemented in Fenix as well.

**Comment by sheikh-azharuddin** [comment]
Here comes the defender....trying to hide all flaws...

**Comment by sheikh-azharuddin** [comment]
> > They could have used firefox lite 3 dot menu implementation...but no👎😡
> > ![Screenshot_20210411-090928465](https://user-images.githubusercontent.com/58127841/114291516-a432b500-9aa5-11eb-97a6-d090f1ba59e9.jpg)
> 
> Seems like a much cleaner and logical implementation. But why is it still scrollable? What isn't showing?

Yes...they could refine it ...think of it like this
After using icons for downloads, bookmarks, add ons

**Comment by evilpie** [comment]
Just for reference, this is the screenshot. The menu item is not half visible. The padding at the bottom is maybe a few pixels shorter.

![Screenshot_20210411-162942_Firefox Nightly](https://user-images.githubusercontent.com/296445/114309786-ba159980-9ae8-11eb-86d5-50de9bc0a6e7.jpg)

**Comment by cadeyrn** [comment]
> Just for reference, this is the screenshot. The menu item is not half visible. 

You're using the top toolbar. It's always helpful to mention if you use a non-default configuration. Otherwise other people assume that you're talking about the default (bottom toolbar). I agree that it's not obvious with the top toolbar. 😉

**Comment by eliserichards** [comment]
Closing as a known issue, will be fixed with https://github.com/mozilla-mobile/android-components/issues/9932.

**Comment by MrNxbxdii** [comment]
why on a new page it doesny scroll up but on a page you visited it has too be scrollable, then you have settings the last one it doesnt make sense how much do i have to pay to get it like the tor browser no bullsh1t just intuitive dont sellout like Google please dont they been irritating since day 1 dont make firefox in any way shape or form similar to chromium nobody likes Google stay in your lane the browser was perfect till yall fucked the scrollable menu up now i gotta use the samsung browser
