### ISSUE TITLE
Add timestamp date/time in history

### ISSUE THREAD

**Issue by devmet34** [mozilla-mobile/fenix#18928]
Hi, I believe this is simple yet must have on a good browser. History section should be able to show date time timestamps for visited pages. Please add this feature, thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10328)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813094

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
