### ISSUE TITLE
[Bug] Menu items don't react to taps

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#18921]
### Steps to reproduce
1. Tap the burger button to display the menu
2. Tap a menu item

### Expected behaviour
Menu item is actioned

### Actual behaviour
Nothing happens. Nada. Zilch. Although, tapping the Settings many times in a row did once trigger the Settings screen to show so I could get to the version information.

### Version
Firefox Nightly for Android 210410 17:02 (Build #2015803851)

### Device
Samsung Note 9, Android 10

**Comment by mrandreastoth** [comment]
P.S. How can a fundamental usability issue like this get past testing?

**Comment by LittleAngelwings** [comment]
Have the same nightly build and I've no problems with the menu items on three different devices. Samsung Galaxy Tab A (SM-T580, Android 8.1.0), Huawei P Smart (2018, Android 9.1.0) and Chromebook ChrOS89, Android 9
)

**Comment by drannex42** [comment]
Same issue here, Oneplus 5T running LineageOS 18.

**Comment by JoGarWeb** [comment]
I have the same problem. Nokia 5.3 Android 10 
Its fucking frustrating. 


https://user-images.githubusercontent.com/7904563/114293364-1a5dfa00-9a5b-11eb-8a63-e83b3d50a1bf.mp4

**Comment by Wodnic** [comment]
Same thing on LG G7 ThinQ with Android 10.

**Comment by keegan-lillo** [comment]
Seeing the same issue on a Pixel 4

Nightly 210410 17:02 (Build #2015803851)
AC: 75.0.20210409143104, bfaf51479
GV: 89.0a1-20210409092020
AS: 74.0.1

**Comment by jonalmeida** [comment]
@Mugurell looking at the video in https://github.com/mozilla-mobile/fenix/issues/18921#issuecomment-817249719, I wonder if this is related to the collapsible menu that's dropping touching events (somehow?).

**Comment by Mugurell** [comment]
Thank you all for the reports and sorry for any issues.
This seems to be #18814 which should be fixed in tomorrow's Nightly.

**Comment by Mugurell** [comment]
Not closing the ticket as a dupe it to keep it easily visible in the list of new issues and prevent others opening similar tickets.

**Comment by eliserichards** [comment]
Thank you all for your reports! Just a reminder to that our Mozilla's community participation guidelines apply.

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/13 Nightly build with:
- Samsung Galaxy Note 8 (Android 9),
- Google Pixel (Android 10),
- Xiaomi Mi 8 Lite (Android 9),
- HTC 10 (Android 8), and
- OnePlus 5T (Android 10).

@mrandreastoth, @keegan-lillo, @JoGarWeb, @Wodnic, please retest this with the latest Firefox Nightly build.
Leaving this ticket opened, for the same reason Mugurell did.

**Comment by mrandreastoth** [comment]
> Verified as fixed on the 4/13 Nightly build

Verify working on "Monday 4/12 @ 5:10 PM", i.e., Nightly 210412 17:03 (Build #2015804235) on Samsung Note 9 running Android 10.

**Comment by keegan-lillo** [comment]
Verified working on Nightly 210412 17:03 (Build #2015804235)

Pixel 4 - Android 11

**Comment by eliserichards** [comment]
Closing as fixed 🎉
