### ISSUE TITLE
Allow locking tabs to prevent closing

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#18922]
As in the desktop version, the mobile version needs an option to lock a tab to prevent it from being accidentally closed and to prevent it from being closed when executing a "close all tabs" operation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10324)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812880

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
