### ISSUE TITLE
Visited links not highlighted in purple after reloading/refreshing page

### ISSUE THREAD

**Issue by devmet34** [mozilla-mobile/fenix#18927]
Using latest version of Firefox for Android. To reproduce the problem; search something on google and open a link from results then come back to google search page and refresh the page. It's supposed to highlight visited links in purple. Instead, it shows the links as if they never visited before.

**Comment by ebalazs-sv** [comment]
I can reproduce this issue on Nightly 5/13, Beta 89.0.0-beta.6 and Release 88.1.3 with Motorola Moto G6 (Android 8).
### Steps to reproduce
1. Launch Fenix and go to google.com
2. Search for a term, i.e "water"
3. Tap on one result to open the link;
4. Tap the back button;
5. Refresh the page;

### Expected result
The visited result is highlighted in purple.
### Actual result
The visited result is highlighted in blue, like all the others search results.
