### ISSUE TITLE
Reader mode breaks on session restore

### ISSUE THREAD

**Issue by legallyahc** [mozilla-mobile/fenix#18933]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Chose a (preferably paywalled news site or any site that results in a popup after loading the page, I encountered the bug on montrealgazette.com) website, and place in reader mode. Close the app. Then, swipe up and fully close the Firefox Nightly application. Relaunch the application, and return to the tab that states it is still in reader mode, but is actually the normal site. When attempting to disactivate reader mode, this causes either a return to a prior page or a refresh of the current page in this non-functional reader mode. 

### Expected behavior
Tab in reader mode load in reader mode. 

### Actual behavior
Tabs in reader mode do not load in reader mode, and can cause a refresh cycle when attempting to disactivate reader mode.  

### Device information
* Device vendor / model and Android version: Google Pixel 3, Android 11 (April 5, 2021 Security update and March 1, 2021 Google Play update)
* Firefox for Android version: Nightly 210409 17:02 (Build #2015803659)
AC: 75.0.20210407190141, 54395a6fa
GV: 89.0a1-20210407094544
AS: 74.0.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10332)

**Comment by legallyahc** [comment]
Here's a reproduction of my steps to recreate the bug.

**Comment by eliserichards** [comment]
Thank you for the detailed build and version numbers! They are super helpful.

**Comment by sflorean** [comment]
Tested on latest Nightly with Samsung Note 10 (Android 11) and this are the results, following the description:
- when re-opening Firefox, the reading state is kept
- when trying to disable reading more, it is not possible, remains active

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible.
The reader mode icon remains active (purple) on restart, while the page itself is in the normal mode, and trying to switch it off only refreshes the page.
Tested on the latest Nightly (2021-11-24).
Device used: Xiaomi Mi11 Lite (Android 11).
