### ISSUE TITLE
[Bug] Firefox shows downloading null on Notifications Bar

### ISSUE THREAD

**Issue by rikhwanto** [mozilla-mobile/fenix#18935]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Download any file from the internet and let it complete
2. Leave Firefox and wait for a while
3. On Notifications bar it suddenly appears that Firefox is downloading a file called null

### Expected behavior
Nothing appears on Notifications bar

### Actual behavior
Firefox shows it is downloading null on Notifications bar
![Screenshot_2021-04-11-12-55-40-60](https://user-images.githubusercontent.com/33298810/114294075-dd7b1d00-9ac5-11eb-80a1-da11a02bf9fd.jpg)

### Device information

* Device vendor / model and Android version: Realme X (RMX1903), Android 10
* Firefox for Android version: 
 87.0.0-rc.1 (Build #2015799099)
AC: 73.0.11, bea80bbac
GV: 87.0-20210315170302
AS: 71.0.0

**Comment by Amejia481** [comment]
If it's possible could you include the URL of the file that you were trying to download?

**Comment by ebalazs-sv** [comment]
I had tested this on the latest Nightly from 4/13, Beta 88.0.0-beta.6 from 4/11 and RC 87.0.0-rc.1 from 3/16 with Samsung Galaxy Tab S3 (Android 8) and could not reproduce it.

**Comment by rikhwanto** [comment]
I opened my download history and tried to redownload the last file I downloaded where it appeared but it didn't reproduce either. The file I last downloaded where it appeared was a video file that I "save file to device", from https://video.twimg.com/ext_tw_video/1376637728075431942/pu/vid/1280x720/fBnZ-2dqx_hH5Z_D.mp4?tag=12

**Comment by sflorean** [comment]
@rikhwanto @mgedmin this is still reproducible on your side? Tested on latest Nightly with OnePlus 9 (Android 12) and couldn't reproduce it.

**Comment by rikhwanto** [comment]
Sorry, just realized this issue is still open. Haven't encountered this issue anymore in stable Firefox Android for months. I'm closing this issue.

**Comment by mgedmin** [comment]
I haven't seen it lately either.
