### ISSUE TITLE
[Bug] Firefox Android is unable to open insecure websites

### ISSUE THREAD

**Issue by kanishkgiri** [mozilla-mobile/fenix#18947]
I am unable to open websites which are not safe according to the firefox, even when i click 'accept the risk and continue' as nothing happens and the site does not opens!
Please fix this búg as i am unable to open the website of the library of my college,i.e, library.iitp.ac.in

**Comment by kbrosnan** [comment]
Duplicate #6296. This website has an insecure certificate using TLS 1.0 or 1.1. This certificate is not accepted in any up to date desktop browser.
