### ISSUE TITLE
[Bug] "Nimbus Experiments" in settings have a gap on the left side

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#18940]
### Steps to reproduce

1. enable the [secret settings](https://github.com/mozilla-mobile/fenix/wiki/%22Secret-settings%22-debug-menu-instructions)
2. open the settings screen and scroll to the end

### Expected behavior

No gap on the left side.

### Actual behavior

![Screenshot_20210411-133823](https://user-images.githubusercontent.com/1100614/114303310-c04a4c80-9acd-11eb-89e1-aaab4fb21454.jpg)

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: master branch revision f6e466175f59fef29128e8d7350e6ed0b2c5f71a

**Comment by cadeyrn** [comment]
@eliserichards This is already fixed by my PR. This issue needs either QA verfication or can directly be closed. 😉

**Comment by Leena1666** [comment]
can I work on this?

**Comment by cadeyrn** [comment]
@Leena1666 This is already fixed (please see the previous comment) and it's only still open because of the pending QA verification.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly 210421`** and **`Beta 89.0.0 - beta.1 `** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20210421-095641](https://user-images.githubusercontent.com/51314259/115510451-6b09fa00-a288-11eb-8097-fdf7c252b58f.png)
