### ISSUE TITLE
[Bug] New tabs tray defaults to top (old tabs) not bottom (new tabs) of list

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#18951]
## Steps to reproduce
0. Have address bar at the bottom (may be same behaviour as top, not sure)
00. Tabs shown in grid (I didn't check with tabs in list)
1. Have many tabs open
2. Open the new tabs tray (new means the one with the synced tabs included on a new tab within the tray)
3. Tabs tray view defaults to showing the top tabs, which are oldest

### Expected behavior
Same as current tabs tray, which defaults to showing the newest tabs at the bottom of the list.

### Actual behavior
New tab tray shows oldest tabs at the top first.

### Device information
Nokia 8 Android 9.

Nightly 210410 17:02 (Build #2015803851)
AC: 75.0.20210409143104, bfaf51479
GV: 89.0a1-20210409092020
AS: 74.0.1

![Screenshot_1618226008277](https://user-images.githubusercontent.com/25123631/114389634-86447d80-9b95-11eb-8f8f-47dc1dc865f9.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10345)

**Comment by SoftVision-LorandJanos** [comment]
Hi @madb1lly! Thank you for your report! This issue is reproducible as described above. Verified on the latest on Nightly (210413 05:01 - GV89). Device used: HTC Nexus 9 with Android 7.1.1.

**Comment by madb1lly** [comment]
Still valid, we need the Fenix team to confirm if this is a explicit UI decision.

**Comment by madb1lly** [comment]
Seems to be fixed now

**Comment by SoftVision-LorandJanos** [comment]
When a newly opened tab is checked in the tabs tray the newest tab is focused at the bottom of the list.
Device used for verifying: Oppo Find X5 (Android 12).
Closing the ticket as fixed.
