### ISSUE TITLE
[Bug] Top sites bottom row partially covered by paste from clipboard dialogue

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#18950]
## Steps to reproduce
1. Copy some text.
2. Open new tab
3. See that the bottom row of the top sites icons is partially covered.

### Expected behavior
Top sites rows should all be visible on new tab page with keyboard open.

### Actual behavior
Top sites icons are not all fully visible with keyboard open if there is something on the clipboard.

### Device information
Nokia 8 Android 9

Nightly 210410 17:02 (Build #2015803851)
AC: 75.0.20210409143104, bfaf51479
GV: 89.0a1-20210409092020
AS: 74.0.1

![Screenshot_1618225855550](https://user-images.githubusercontent.com/25123631/114389539-68771880-9b95-11eb-8164-d6e4e0b60ea0.jpg)

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by amedyne** [comment]
@topotropic Thoughts on this?

**Comment by Dunexus** [comment]
This depends on several things such as screen height and keyboard height. I don't know how this can be handled.

**Comment by topotropic** [comment]
Thanks for the feedback! We're looking at improving the home screen and will consider this.
