### ISSUE TITLE
[Bug] Inconsistent behaviour of new three-dot menu

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#18952]
The new three-bot menu does not open consistently. Usually it is the shortened, widened, scrollable version. On the new tabs page it is the old menu (I think) and sometimes I get the new widened scrollable menu but already fully expanded.

As a side note, when fully expanded the menu still has a little scrollable range left in it, I can move it up and down a little.

## Steps to reproduce
1. Press three button menu on a variety of tabs until the unusual fully expanded version is seen.
2. Press three dot menu on the new tabs page, this is consistent behaviour,
3. Fully expand the menu and see if it is still a little bit scrollable.

### Expected behavior
New menu behaviour should be consistent.

### Actual behavior
Current menu behaviour is not consistent throughout the app.

### Device information
Nokia 8 Android 9.
Nightly 210410 17:02 (Build #2015803851)
AC: 75.0.20210409143104, bfaf51479
GV: 89.0a1-20210409092020
AS: 74.0.1

![Screenshot_1618225816964](https://user-images.githubusercontent.com/25123631/114389686-9a887a80-9b95-11eb-8ddf-62ca03784576.jpg)
![Screenshot_1618225479455](https://user-images.githubusercontent.com/25123631/114389695-9cead480-9b95-11eb-8149-2e38a6b406d9.jpg)
![Screenshot_1618225431402](https://user-images.githubusercontent.com/25123631/114389702-9f4d2e80-9b95-11eb-8b7b-45762eba8fb3.jpg)

**Comment by eliserichards** [comment]
We are finalizing the scrollability of the menu (making the nav buttons sticky), so closing this as known & fix is in progress :) 

See https://github.com/mozilla-mobile/android-components/issues/9932
