### ISSUE TITLE
[Bug] New tabs tray lacks the share, save to collection, bookmark and close options

### ISSUE THREAD

**Issue by madb1lly** [mozilla-mobile/fenix#18953]
## Steps to reproduce
1. Enable new tabs tray in Secret Settings
2. In tabs tray select a tab (long press)
3. Find that there's no way to share it, save it to collection, bookmark it or close it

### Expected behavior
New tab tray should include options to share, save to collection, bookmark and close a selected tab

### Actual behavior
New tab tray does not include options to share, save to collection, bookmark and close a selected tab

### Device information
Nokia 8 Android 9
Nightly 210410 17:02 (Build #2015803851)
AC: 75.0.20210409143104, bfaf51479
GV: 89.0a1-20210409092020
AS: 74.0.1

**Comment by SoftVision-LorandJanos** [comment]
Hi @madb1lly! Thank you for your report!
I cannot reproduce this issue on latest Nightly (210413 05:01 - GV89) and Nightly 210410 17:02.
I can share, add a new collection, bookmark it and close it.
Device used: HTC Nexus 9 with Android 7.1.1.

**Comment by madb1lly** [comment]
Hi @SoftVision-LorandJanos,
Are you using the new tabs tray enabled through secret settings?
Cheers 🙂

**Comment by SoftVision-LorandJanos** [comment]
> Hi @SoftVision-LorandJanos,
> Are you using the new tabs tray enabled through secret settings?
> Cheers 🙂

Yes, I had to look it up how I should enable it, but I managed it, I still couldn't reproduce the issue. Might be device or Android specific, since those are different from yours. I will ask someone with close or with the exact device/android as you have, might have a better chance of reproducing it. Thank you!

**Comment by madb1lly** [comment]
![Screenshot_1618315248551](https://user-images.githubusercontent.com/25123631/114602332-c8a1b380-9c96-11eb-8e31-6158c88bbbc4.jpg)

**Comment by mariansima** [comment]
Hey @madb1lly, if this is still an issue for you, could you let me know what I have to enable from the secret settings to help me reproduce it? Thanks.

**Comment by madb1lly** [comment]
Hi @mariansima,
Yes it works fine now, can be closed. Great to see that someone is following up on these old bugs, there are plenty that have not been fixed.
Cheers 🙂

**Comment by SoftVision-LorandJanos** [comment]
Based on the comment above, I will close this ticket.
