### ISSUE TITLE
Remove nav in home three-dot menu

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18960]
## Acceptance criteria
Remove the backwards and forwards nav buttons on the home screen three-dot menu. 

Since the home screen isn't a tab (it doesn't have state) we aren't able to utilize the back/forward nav buttons in the homescreen's three-dot menu.

**Comment by eliserichards** [comment]
Approved by @violasong

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/13 Nightly build with Samsung Galaxy Note 8 (Android 9), Google Pixel (Android 10), Xiaomi Mi 8 Lite (Android 9), HTC 10 (Android 8), and OnePlus 5T (Android 10).

<img src="https://user-images.githubusercontent.com/40694158/114510891-e1cb4580-9c3f-11eb-9ab6-bc0710b5dc46.jpg" width="300" height="550" />
