### ISSUE TITLE
[Bug] Incorrect function names

### ISSUE THREAD

**Issue by priyanka0906** [mozilla-mobile/fenix#18964]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
In file SessionControlController.kt wrong function names are written. These are actually misplaced.

### Expected behavior
![Screenshot (54)_LI](https://user-images.githubusercontent.com/56197993/114444183-30e78b00-9bec-11eb-8241-4352fdd4a6c0.jpg)
### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by priyanka0906** [comment]
@eliserichards  please have a look.

**Comment by mcarare** [comment]
Hello, @priyanka0906! I am not sure what this is about? What misplacement are you reporting? The KDoc is supposed to be above the method it documents so I am not sure what is the purpose of the arrows in the screenshot.

**Comment by priyanka0906** [comment]
> Hello, @priyanka0906! I am not sure what this is about? What misplacement are you reporting? The KDoc is supposed to be above the method it documents so I am not sure what is the purpose of the arrows in the screenshot.

@mcarare sorry for that , I thought it comes below the method. My bad😅

**Comment by priyanka0906** [comment]
> > Hello, @priyanka0906! I am not sure what this is about? What misplacement are you reporting? The KDoc is supposed to be above the method it documents so I am not sure what is the purpose of the arrows in the screenshot.
> 
> @mcarare sorry for that , I thought it comes below the method. My bad😅

Thanks for clearing @mcarare
