### ISSUE TITLE
[Bug] For Bugzilla ticket 1701932 on Autofill 

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#18977]
See: 
 
https://bugzilla.mozilla.org/show_bug.cgi?id=1701932

**Comment by amedyne** [comment]
Closing this issue since bugzilla ticket has been fixed.

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

This bug is for keeping track of related GV changes as part of the Credit Card autofill work.

So far, looks like no changes needed in AC or Fenix.

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

Note from bugzilla:

The change is deliberate here: https://bugzilla.mozilla.org/show_bug.cgi?id=1330111#c69 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1330111#c69 ) and this has been the behavior for a long time, so I'm not sure that leaving this bug restricted makes sense.

We should probably display a warning for HTTP logins, similar to what happens on desktop

Looks like we can disable the flag on Fenix and the effect will be that users have to click on the login field to autofill, which seems appropriate for HTTP pages. Note that just setting the pref to false does not disallow autofilling on HTTP pages, it just requires user interaction.

Latest update:

GV change is to flip the pref, that does not involve Fenix work, but if you want to display a warning like desktop do that would have to be done on the Fenix side. The issue will be resolved by the pref flip. The warning is an added extra work in Fenix.

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

GV change is on target for GV90.

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

GV fix landed last Friday 20210514.

[~ccarter@mozilla.com] or [~vzare@mozilla.com] do we want to display a warning like desktop does for this case?

**Comment by data-sync-user** [comment]
➤ Channing Carter commented:

[~amoya@mozilla.com] how much extra work is it to do this?

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

[~nweber@mozilla.com] Can you provide some design so we can size this? The original security bug is Fenix allows autofill on insecure pages.

The ask is to display a warning for HTTP logins, similar to what happens on desktop.

See comments/section for some background.

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

[~ccarter@mozilla.com] depending on the design, I think this can be at least a 3pt task.

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

Per discussion today, we'd want to have the warning message for Fenix, too.

**Comment by data-sync-user** [comment]
➤ Nicole Weber commented:

I'll look into this. I'm not able to access the bugzilla issue above, could someone add me to the bug? Thanks!

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

[~nweber@mozilla.com] Done! You should have access to the bug now.

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

[~nweber@mozilla.com] Let me know once you have the design ready. Thanks!

**Comment by data-sync-user** [comment]
➤ Nicole Weber commented:

[~amoya@mozilla.com] sorry for not getting back to you earlier! [~mverdi@mozilla.com] is looking into this as part of the "merging lock+shield" work.

**Comment by data-sync-user** [comment]
➤ Amedyne Moya commented:

Thanks Nicole! I will tag this task as Done now and we can track the remaining work thru the "merging lock+shield" work.
