### ISSUE TITLE
"Copy Link" context menu copies title instead of URL for HTML5 Video

### ISSUE THREAD

**Issue by majurgens** [mozilla-mobile/fenix#18979]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1) Find an HTML5 video on the Internet. Sample one on this page
https://www.edcint.co.nz/public/data/firefox/index.shtml
2) Long press video (context menu appears)
3) tap "Copy Link"
4) go to a place/app where you can paste, then paste the link you copied

### Expected behavior
the URL of the video is pasted (as experienced in the Windows desktop version of Firefox from the "Copy Video Location" context menu)

### Actual behavior
the title attribute of the video is pasted

### Device information
v87.0.0-rc.1 Build#2015799099

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10359)

**Comment by SoftVision-LorandJanos** [comment]
Hi @majurgens ! Thank you for your report! This issue is reproducible as described above.
Verified on the latest on Nightly (210413 05:01 - GV89).
Device used: HTC Nexus 9 with Android 7.1.1.

**Comment by majurgens** [comment]
This is still an issue in Nightly 98.0a1 (Build 2015857707). Just wondering if anyone if working on this or going to fix this or if there is something else that I should lodge the bug?

**Comment by majurgens** [comment]
Still an issue.
Not a great methodology to just drop issues because no one has done anything about it.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809306

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
