### ISSUE TITLE
[Bug] lots of crashes since last two days 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#18972]
the nighlty build from the last two days sometimes crashes here's the url of a crash I just had on reddit
https://crash-stats.mozilla.org/report/index/c1394414-ed25-4933-b7dd-ee1c90210412
can someone please tell me if it 's caused by some pref in about :config 
thanks.

**Comment by kbrosnan** [comment]
Filed bz-1704887
