### ISSUE TITLE
FNX-5318 ⁃ [Bug] New Bookmark Folders are not aligned properly

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1897]
## Steps to reproduce
* Edit a bookmark
* Select the folder button to add a new folder name

### Expected behavior
* Folders will be aligned

### Actual behavior
* New folders (in screenshot misc and politics) are offset from the others which are left aligned

### Device information
* Android device: Pixel 3
* Fenix version: 1.01917 (Build #11121210)
![Screenshot](https://user-images.githubusercontent.com/2171777/56519193-6ed6da80-650f-11e9-9219-31b07fd4aee2.png)UNITO-UNDERSCORE!20190422-145615!

**Comment by ekager** [comment]
These are subfolders so this is desired behavior :)
