### ISSUE TITLE
Add way to differentiate between logins

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#18985]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
On lots of sites users have to change their passwords every few months. This leads to lots of logins appearing in the suggested logins prompt, and it might not be clear which one is the current one. That's why it would be great if there was some way to differentiate between the logins, i.e. by adding a date (or adding a date to all logins older than the current one).

### How do you know that this problem exists today? Why is this important?
I've encountered this problem on different sites

### Who will benefit from it?
People who use services that require them to frequently change passwords

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10363)

**Comment by pbhj** [comment]
It's not just on single web addresses, for router addresses across different locations the address is the same (eg 10.0.0.1), often the username is the same (admin). The list of logins returned by search doesn't appear to have a logical ordering and - I can't quite tell - seems to change each time.

**Comment by tribut** [comment]
This problem is exacerbated when on a domain with many domains and different logins. Showing the subdomain would help a lot.

![Screenshot_20220403-122707_Firefox](https://user-images.githubusercontent.com/719105/161423279-80fa53ff-61cd-4efe-b889-a4557b2a2752.jpg)

**Comment by boek** [comment]
Closing as a dup: of https://bugzilla.mozilla.org/show_bug.cgi?id=1812437
