### ISSUE TITLE
FNX-5319 ⁃ [Bug] Difficult to see cursor when dark theme is set

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#1898]
## Steps to reproduce
* Turn on Dark theme and place cursor in the search field

### Expected behavior
* I can see cursor

### Actual behavior
* Cursor is purplish but difficult to see

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1917 (Build #11121210)

**Comment by lime124** [comment]
@AmyYLee can you help?

**Comment by AmyYLee** [comment]
Hi, 

This has already been reported and part of the edits in this bug https://github.com/mozilla-mobile/fenix/issues/826

**Comment by lime124** [comment]
closing as per amy's previous comment. please file a new issue if it continues to be a problem. thanks!
