### ISSUE TITLE
[Bug] Unable to choose a different login after picking a wrong one

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#18983]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to a site for which you have multiple logins saved. Click to autofill one of the logins (which could be the wrong one by accident), then click on one of the login fields again.

### Expected behavior
The suggested logins prompt should popup again, and all logins for the site should be displayed

### Actual behavior
Sometimes it's hard to make the suggested logins appear, and it will only show logins for the username that was first selected.

### Device information

* Device vendor / model and Android version: Huawei Nova 6 (Android 10)
* Firefox for Android version: Nightly 210412 17:03 (Build #2015804235)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10361)

**Comment by ebalazs-sv** [comment]
I had tested this issue on Nightly 4/13 with Samsung Galaxy Tab S3 (Android 8) ad could not reproduce it.
After clearing the first autofill password, I can choose another password from the Suggested logins list. Tested on twitter.com with multiple saved logins.
@mobd Hi! When trying to choose another password, do you clear first the existing password? Also on what page are you trying this scenario?

**Comment by mobd** [comment]
@ebalazs-sv I'm trying this on github, as far as I can tell other sites behave the same. I don't mean different passwords for the same username, but different usernames. For example:

![output_0](https://user-images.githubusercontent.com/66154603/114531182-f3b2e580-9c4b-11eb-8d47-b0c6a29cfa8b.gif)

After auto-filling the first login, the second one doesn't show up anymore

**Comment by ebalazs-sv** [comment]
Thanks @mobd for the details!
I can reproduce the issue on Nightly 4/13, Beta 88.0.0-beta.6 from 4/11, RC 87.0.0-rc.1 from 3/16 with Samsung Galaxy Tab S3 (Android 8).
Clearing the username and password fields and tapping again the username field, solves the issue.
## Precondition
Have multiple logins saved on the tested login page.
## Steps to reproduce:
1. Launch Fenix and go to mobile.twitter.com/login;
2. Tap the Username field;
3. Tap the Suggested logins;
4. Choose a saved login;
5. Tap again the Username field;
6. Tap the Suggested logins;

### Expected result:
All the saved logins are displayed in the Suggested logins list.

### Actual result:
Only the already used saved login, from steps 4, is displayed in the Suggested logins list.

**Comment by eliserichards** [comment]
I think this is a use case, not necessarily a bug. When text exists in the field already (whether autofill text or manually entered text) and we send an autofill request, should we clear the text field and autofill? Or, if text exists, do we append the autofill to the end of the currently existing text? 

As I understand it, the normal flow when using most autofill services involves manually clearing any text before autofilling again. Being smart about deleting any existing text when autofilling could make this much easier as a user 🤔

**Comment by mobd** [comment]
I can still reproduce this

**Comment by mcarare** [comment]
I do not think this is a bug but it might be something we can improve upon. We should weigh the gains from this improvement versus the possible negative implications.

Deleting existing text without user implicit action could end up having edge cases where we would clear the username when we did not really want to. As opposed to just clearing the already selected user and beginning the normal authentication flow.

Another approach, where we would receive all the options needs changes in Gecko. The same question remains if it is worth the work and risk when there already is a simple way to work around the issue. 

Note: It might be just speculation, but changing the way we receive the login options when a username is already selected might impact pages where you first select a username and click next to get to another page and also select the password for that username.

**Comment by mcarare** [comment]
Opened an issue for investigating in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1750193.
