### ISSUE TITLE
[Bug] Suggested logins don't always respond to clicks

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#18988]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Try to select a suggested login by clicking on the bottom half of it.

### Expected behavior
The login is auto filled

### Actual behavior
Nothing happens. Even though when you properly click it the whole area is highlighted, only the top part of the login actually responds to being clicked

![output_1](https://user-images.githubusercontent.com/66154603/114539284-a25b2400-9c54-11eb-9cf0-3d1796c8a17f.gif)

### Device information

* Device vendor / model and Android version: Huawei Nova 6 (Android 10)
* Firefox for Android version: Nightly 210412 17:03 (Build #2015804235)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10365)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 5/19.
### Devices used:
- Pixel 3 XL (Android 9)
- OnePlus 6T (Android 9)

**Comment by mobd** [comment]
I can still reproduce this
