### ISSUE TITLE
[Bug] Twitter PWA keeps dying on me

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#18997]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Install Twitter as a PWA via Firefox Nightly. 
Sign in to Twitter (unsure if this is necessary) 
Interact with Twitter for a period of time (scrolling, viewing individual tweets, reacting/replying to tweets, etc) 

### Expected behavior
Twitter continues behaving normally. 

### Actual behavior
At some point, the Twitter PWA turns solid grey and is completely unresponsive, and the only way to recover from this is to kill the app and restart it. 

### Device information

* Device vendor / model and Android version: This has happened on my Pixel 3 and also on my Galaxy S21, both running Android 11.
* Firefox for Android version: I've only noticed this over the last 24-48 hours on Nightly

**Comment by KWierso** [comment]
"a period of time" might be "at least 30 minutes or more", for the record. It's not an immediate thing, so quickly trying to reproduce this isn't going to work.

**Comment by sflorean** [comment]
Tested on latest Nightly with Pixel 3 (Android 11) and couldn't reproduce the issue, following the steps/information above. 
@KWierso do you have some additional settings? open links in private tab maybe, or did you have some additional steps, like sharing outside the pwa?
Thank you!

**Comment by KWierso** [comment]
I don't have much else, sadly. I guess the PWA inherits settings (and addons?) from main Nightly app, in which case I have uBlock Origin installed, but my profile is otherwise pretty vanilla.

**Comment by SoftVision-LorandJanos** [comment]
I couldn't reproduce this issue.
I will close the ticket as fixed.
@KWierso if you have the same issue on the latest builds, please share some additional details to help us reproduce as well (Even a video of the issue). Thank you!
