### ISSUE TITLE
FNX-5322 ⁃ [UX] Reader Mode

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#190]
User story:

~~As a user, I want to have a clean and distraction free reading experience for long~~form content.

Acceptance Criteria

-As a user I want to know when reader mode is available (Reader mode indicator)
-As a user I want to be able to view a site in reader mode, have be able to change font, text size, and background)
-As a user I want to be able to go back to the browser mode when I am done reading

**Comment by bbinto** [comment]
@colintheshots to identify dependencies on other teams?

**Comment by st3fan** [comment]
Can we consider delegating this to Pocket?

**Comment by lime124** [comment]
@bbinto it seems like this is still blocked? should we move it out of milestone 2?

**Comment by bbinto** [comment]
@vesta0 will be working on this. Might be best to move, I agree

**Comment by vesta0** [comment]
Draft [feature brief ](https://docs.google.com/document/d/1p4D_XNGmth4UNysDYHKbP_FhOvWfje72ywoMaJnNUL4/edit)(includes designs from @bram)

**Comment by bbinto** [comment]
@brampitoyo can you please size this?

**Comment by brampitoyo** [comment]
@bbinto If we choose to go with approach 1 (integration with Pocket), then the design on my end will be quite simple: an app bar icon. The actual reader view will be handled by Pocket.

For approach 2: in addition to the app bar icon, I will also need to design the reader view itself. This can still be simple. There is prior work in Fennec that I can adapt from. However, this approach may be harder to implement, engineering-wise.

Speaking as a Fenix user, Pocket offers me a lot of super-powers (on top of the reading mode itself) like reading list, related articles, and maybe even article narration.

Speaking as Mozilla, shipping a Pocket web service in every Fenix APK isn’t only going to increase Pocket MAU. It also means that Pocket’s content recommendation will get even better from having more inputs from Fenix users. It’s like having a more accurate “Forward button” for reader view.

For those reasons, I do prefer approach 1, even though it will require cross-team coordination (we’ll need to talk to Pocket).

**Comment by yoasif** [comment]
I like Pocket and have it installed on my device.

However, given the bug around CFR on Firefox desktop where Firefox connected to Mozilla upon presenting an add-on recommendation, I think it would be pretty concerning to privacy aware Fenix users to contact an external service to provide something as basic as a reader view - unless you are simply proposing using Pocket's reader view code locally without any connection to the Pocket web service. 

I don't know enough about how Pocket works to know whether all of the reader view stuff that Pocket does is local to the device, or whether it has help from the Pocket web service; I think it would be concerning if enabling reader view on a page caused Fenix to hit a pocket.com domain.

**Comment by pwd-github** [comment]
Since getting into web novels, I access reader view about 50 times a day, if not more. To be punted over to Pocket for each chapter and lose the integration with my Firefox (Global) session (History) would be a disaster.

**Comment by colintheshots** [comment]
Maybe we could integrate the Pocket Instant App component into the APK? That would solve two problems. We'd get Pocket for under 4MB and without requiring an external app. It would also include links to get the full app experience. It's a thought. I haven't done any analysis of this option yet, but it would be interesting to test.

**Comment by vesta0** [comment]
@brampitoyo I know you are already working on this. Please also add a S/M/L size to it based on your efforts.

**Comment by pwd-github** [comment]
So here's a test case for this feature: https://www.wuxiaworld.com/novel/trash-of-the-counts-family/tcf-chapter-1

While Pocket does a wonderful job of paginating the text. There's no way to keep your place as is the default behaviour on desktop. Also for some reason, narration isn't available via Pocket. As things stand, the user experience is better in Fennec and on desktop.

**Comment by brampitoyo** [comment]
@vesta0 If we’re building our own solution – and thanks @pwd-github @yoasif for providing really good reasons for it – then I think that this would be a size S.

If we’re using Pocket’s technology, it might be a size M.

**Comment by brampitoyo** [comment]
Here’s a mockup for our own Reader View that doesn’t rely on any Pocket-powered service.

# Entering and Exiting Reader View

1. Reader View is accessed by swiping up on the Quick Action Bar

![slice 2x](https://user-images.githubusercontent.com/51007/53542317-c5184480-3b82-11e9-89ab-20a8208526f9.png)

2. When the “Read” action is tapped, the icon turns blue and inverted, to indicate that it’s been selected.

![slice 2x](https://user-images.githubusercontent.com/51007/53542351-f8f36a00-3b82-11e9-86e1-c0302edc9669.png)

3. To exit Reader View, tap the blue “Read” icon again.

# Top app bar

The top app bar contains:

1. Add to Reading List. To have this feature, we need to design:
    a. A way for Reading List to integrate with our existing Library UI
    b. A custom icon. Note: the icon that appears in the mockup is TBD
2. Appearance controls. Font selection, text size and colour scheme.

![slice 2x](https://user-images.githubusercontent.com/51007/53542718-a31fc180-3b84-11e9-99cd-8e23f4344c77.png)

# Scroll down behaviour

Top and bottom app bars disappear as you scroll down the page, and reappears as you scroll up. This behaviour is pretty standard. I’m reiterating it here just to make sure that we have it covered.

![slice 2x](https://user-images.githubusercontent.com/51007/53542826-1e817300-3b85-11e9-916f-81bfd9176066.png)

**Comment by pwd-github** [comment]
That looks really good. Though, personally I'd prefer it to have a more intuitive back button in the top left corner to allow for exiting as well. Also, the narrate feature, which is the real MVP of reader view is missing.

**Comment by vesta0** [comment]
@csadilek to review before closing.

**Comment by mheubusch** [comment]
@brampitoyo please remove the hyphen in sans serif - otherwise has my sign off.

**Comment by csadilek** [comment]
Looks great! With the planned enhancements/APIs for WebExtensions in GeckoView and Android Components, covering all this functionality should be possible soon.

**Comment by brampitoyo** [comment]
@mheubusch I’ve removed the hyphen in the word `sans serif`. @vesta0 @csadilek We’re now good to go.

**Comment by pwd-github** [comment]
The narrate feature hasn't been included in the mockups. I can understand that it's outside of the scope of what Mozilla is able to deliver right now, however it would be nice to have some UX direction for a volunteer patch.

**Comment by vesta0** [comment]
Thanks @csadilek and @brampitoyo

**Comment by colintheshots** [comment]
Does #911 have any UX? Do we want to, say peek the bottom sheet and animate the Reader Mode button to indicate that the Reader Mode is available? @brampitoyo

**Comment by brampitoyo** [comment]
@colintheshots Good catch.

When a page detects reader mode, we definitely want to peek the Quick Access Bar halfway up, 1) to indicate that something is different with this page, and 2) to subtly bring up the Reader Mode icon.

Since Reader Mode availability is meant to be unobstrusive, no animation will be necessary.

So from this halfway point, it’s up to the user. Want to access Reader Mode? Pull up the Quick Access Bar and then tap “Read”.

**Comment by shorlander** [comment]
@brampitoyo Do you think all of the items left in the Quick Action bar apply to pages in Reader mode? E.g. What happens if you bookmark a page in Reader mode?

**Comment by brampitoyo** [comment]
@shorlander Reader View controls are now located inside the Quick Action Bar, replacing two actions there – Download and Favorite – that would do nothing in Reader View.

Share and Screenshot still works as they should on Reader View:

1. Share: the URL itself is shared
2. Screenshot: a screenshot of the reader view (not of the webpage) is taken

@colintheshots @csadilek @vesta0 @lime124 I’ve updated my specs above to account for the new reader view navigation pattern: appearance and reading list actions are now located inside the Quick Action Bar).

I try not to put up a fresh new spec every time it’s updated, so we have only one source of truth.

See the new specs here: https://github.com/mozilla-mobile/fenix/issues/190#issuecomment-468141227

**Comment by pwd-github** [comment]
The narrate feature still seems to be missing?

**Comment by cadeyrn** [comment]
>     2\. Screenshot: a screenshot of the reader view (not of the webpage) is taken

I thought screenshots are no longer part of the MVP?

**Comment by boek** [comment]
@pwd-github we would love help, but at this time our UX team is at capacity trying to provide everything we need for the MVP. Feel free to open a new ticket with the requested feature and we can prioritize it once we ship the first version :raised_hands:

**Comment by mheubusch** [comment]
@shorlander This should have gone thru you but I don't see your approval label - can you review and confirm?

**Comment by vesta0** [comment]
@mheubusch can we close this issue?

**Comment by mheubusch** [comment]
Closing . . .
