### ISSUE TITLE
[Bug] Three-dot menu is not really scrollable

### ISSUE THREAD

**Issue by Rodze** [mozilla-mobile/fenix#19006]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Open three-dot menu, roll it up, then try to roll it back down.

### Expected behavior

Menu should be rolled down again.

### Actual behavior

Nothing happens.

### Device information

* Device vendor / model and Android version: Galaxy S9 Android 9
* Firefox for Android version: ? Nightly 210413 17:00 (Build #2015804427)

**Comment by Rodze** [comment]
Related to #17796

**Comment by amedyne** [comment]
@eliserichards

**Comment by SoftVision-LorandJanos** [comment]
Hi @Rodze ! Thank you for your report!
Based on [this](https://github.com/mozilla-mobile/fenix/issues/18591#issuecomment-836578662) comment, this behavior is expected.
The issue is covered by [this](https://github.com/mozilla-mobile/fenix/issues/18591) ticket.
