### ISSUE TITLE
[Bug] Three-dot menu on a new tab should not have synced tabs in it

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19005]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Ensure you have the 'Tabs tray re-write' feature flag enabled in the secret settings.
- Open a new tab.
- Click on the three-dot menu.

### Expected behavior
- You do not see 'Sync Tabs' in the three-dot menu list.

### Actual behavior
- You see synced tabs and not sync sign in

### Device information

* Device vendor / model and Android version: Android 11, Pixel 3
* Firefox for Android version: master as of 5db2f7568f
 
<img width="393" alt="Screen Shot 2021-04-13 at 4 19 41 PM" src="https://user-images.githubusercontent.com/1370580/114616134-849db700-9c74-11eb-89cb-4cf741434045.png">

**Comment by metronightly** [comment]
Exactly, this should be somewhere inside. And to add to that, onstead of the words 'Synchronised Tabs', I have my entire email from Firefox account plastered over the 3 button menu which is ridiculous.

**Comment by eliserichards** [comment]
The new designs show synced tabs/sync sign in on the new tab menu: 

<img width="323" alt="image" src="https://user-images.githubusercontent.com/43795363/114777919-d65c4500-9d39-11eb-9723-ac030554ed6b.png">

https://www.figma.com/file/NHu4cTmzfYgi3QJz5DIDWD/Fenix-Toolbar-Menus?node-id=0%3A1

**Comment by eliserichards** [comment]
Synced tabs/sync sign in were checked in the default toolbar but not in new tab.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build 4/23. Following the steps, "Sign in to sync" is displayed, that goes to Account settings/Sign In. 
Devices: Pixel 3 (Android 11), Huawei MediaPad M2(Android 5.1.1).

**Comment by jonalmeida** [comment]
Uplifting the fix for this bug, will in turn also fix https://github.com/mozilla-mobile/fenix/issues/19184 in beta.
