### ISSUE TITLE
Show three-dot menu for Synced Tabs in tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19003]
@rocketsroger I just remembered that we have synced tabs now, so I'm not sure what three-dot menu should show be when it's focused.

Might be a question for @topotropic.

_Originally posted by @jonalmeida in https://github.com/mozilla-mobile/fenix/issues/18513#issuecomment-810650887_

<img width="199" alt="Screen Shot 2021-04-13 at 4 07 27 PM" src="https://user-images.githubusercontent.com/1370580/114614346-6636bc00-9c72-11eb-888b-c11218270ba3.png">

**Comment by jonalmeida** [comment]
Some suggestions might be the account settings page and/or recently closed.

**Comment by topotropic** [comment]
Yes, that makes sense. We should replace "Tab settings" with "Account settings" for the synced tab view. Thanks!

**Comment by metronightly** [comment]
Exactly, this should be somewhere inside. And to add to that, instead of the words 'Synchronised Tabs', I have my entire email from Firefox account plastered over the 3 button menu which is ridiculous.

Nightly 210412, Android 10
