### ISSUE TITLE
[Bug] (regression) new tabs tray no longer shows tabs once you switch the tab category

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#19015]
### Steps to reproduce

1. open the new tabs tray
2. switch to either private or synced tabs
3. switch back to regular tabs

### Expected behavior

You can see your tabs.

### Actual behavior

No tabs are shown.

/cc @jonalmeida because it's related to the tabs tray work.

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: ? (go to Settings -> About Firefox) master branch revision 990bfa7e6dd5894d61473a41da6129e6947974e2

**Comment by hakkikaancaliskan** [comment]
I think #19014 will solve this issue

**Comment by cadeyrn** [comment]
Thanks. I can confirm that #19014 will fix this issue.
