### ISSUE TITLE
[Bug] Firebox Mobile possibly not sending HTTPS cookies when fetching mp3s from m3u8 playlist

### ISSUE THREAD

**Issue by ffxsam** [mozilla-mobile/fenix#19013]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
https://codesandbox.io/s/no-hls-on-firefox-mobile-j4s6r?file=/src/index.js

### Expected behavior
Firefox on desktop properly returns an empty string when evaluating `document.createElement('audio').canPlayType('application/vnd.apple.mpegurl')`. Firefox mobile doesn't support native HLS either, so I would expect it to do the same.

### Actual behavior
`document.createElement('audio').canPlayType('application/vnd.apple.mpegurl')` returns `"maybe"`

### Device information

* Device vendor / model and Android version: Pixel 4 - Android 11
* Firefox for Android version: ? (go to Settings -> About Firefox) 87.0.0-rc.1 (Build #2015799099)

**Comment by kbrosnan** [comment]
Firefox for Android ships with its [own copy of exoplayer](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/thirdparty/java/org/mozilla/thirdparty/com/google/android/exoplayer2) for HLS playback.

**Comment by ffxsam** [comment]
So it's supposed to play m3u8 playlist files? Because it's not working for me. I get a "NotSupported" error.

**Comment by padenot** [comment]
Maybe just gave us a link to you m3u8 file? I've tried quite a few just now, randomly searching on the web, and it works as expected. Maybe it's a content-type issue, or a codec issue?

**Comment by ffxsam** [comment]
Very odd. I made a very simple CodeSandbox using an m3u8 file as an audio src, and it worked perfectly fine. However, in our production app, it fails with `NotSupportedError`. The only difference I can think of is that the files in production are protected via AWS's CloudFront signed cookies. But there's a signed cookie issued at the start of the session, and I'm not getting any kind of 4xx error or CORS error.

I'll have to dig into this a bit more.

**Comment by padenot** [comment]
I'm available on the web audio slack if you want to chat directly. I can also try things if something is available online, or tell you internal debugging tools to diagnose this quickly if that would be helpful. There has been some changes a few years back specifically on m3u8 files on mobile to fix a security issue, that might be related.

**Comment by ffxsam** [comment]
Updated the issue title to reflect that actual problem.

**Comment by padenot** [comment]
Thanks Sam, the gecko bug about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1705472
