### ISSUE TITLE
FNX-5323 ⁃ [Bug] Sync isn't working anymore

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#1902]
We have a fairly recent regression, it seems. This used to work fine. I'm seeing the following in the logs while trying to sync:

```
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: No virtual method sync(Lmozilla/appservices/places/SyncAuthInfo;)V in class Lmozilla/appservices/places/PlacesApi; or its super classes (declaration of 'mozilla.appservices.places.PlacesApi' appears in /data/app/org.mozilla.fenix-1/base.apk)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:4)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:48)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:1)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:762)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: Caused by: java.lang.NoSuchMethodError: No virtual method sync(Lmozilla/appservices/places/SyncAuthInfo;)V in class Lmozilla/appservices/places/PlacesApi; or its super classes (declaration of 'mozilla.appservices.places.PlacesApi' appears in /data/app/org.mozilla.fenix-1/base.apk)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at mozilla.components.browser.storage.sync.RustPlacesConnection.sync(Connection.kt:2)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at mozilla.components.browser.storage.sync.PlacesStorage$sync$2.invokeSuspend(PlacesStorage.kt:10)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:13)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:1)
04-22 18:29:31.577  2790  2819 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:42)
04-22 18:29:31.578  2790  2819 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=fd62137e-591b-4321-850c-26967db59a3d, tags={ Common, Immediate, mozilla.components.feature.sync.WorkManagerSyncWorker } ]

```

**Comment by grigoryk** [comment]
This is the regressing PR: https://github.com/mozilla-mobile/fenix/pull/1778 - fenix now declares an appservices version which is newer than what a-c supports. During a build, gradle resolves a-s dependency to the newer version, and a-c is now out-of-whack since the public APIs of its dependency changed without its knowledge.

Let's fix it by:
- finishing a-c upgrade to 0.26.0 in https://github.com/mozilla-mobile/android-components/pull/2798
- remove appservices version number from Fenix. It doesn't consume this dependency directly, so it shouldn't specify a version. Version will be inherited from a-c.

**Comment by sv-ohorvath** [comment]
@grigoryk 
History sync is working. Bookmarks don't sync.
build: 4/24
devices: HTC Desire 820 (Android 6.0.1), Pixel (Android 9)

**Comment by cadeyrn** [comment]
> History sync is working

So history sync is already supposed to work? Because for me history sync never worked and still not works at all.

/cc @grigoryk

**Comment by vesta0** [comment]
@sv-ohorvath I don't believe Bookmarks Sync has landed yet.

**Comment by grigoryk** [comment]
@cadeyrn could you file a bug for this? It's expected to work.

Ideally with device logs as you're trying to sync (output of `adb logcat` is sufficient, over email is fine if you don't want to post it publicly - gkruglov@mozilla.com), that should shed light on why it's not working for you.

**Comment by grigoryk** [comment]
@sv-ohorvath we'll land bookmark sync turned out for nightly only and give it some time to bake. It hasn't landed yet.

**Comment by cadeyrn** [comment]
@grigoryk I have to revert my last comment, the history sync works. History sync was disabled on my desktop system the last months and it seems that Fenix does not synchronize old data. After enabling the history sync and triggering a manual sync on desktop it works on Fenix, too.

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath I don't believe Bookmarks Sync has landed yet.

#919 was closed and ready for QA, so I supposed it has landed. I'll close this bug then, for history sync working fine.
