### ISSUE TITLE
[Bug] Edited url is not loaded in current tab when opening link from external apps

### ISSUE THREAD

**Issue by lazylynx** [mozilla-mobile/fenix#19026]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Confirm Firefox app killed.
    If app is alive, this issue will not be reproduced. 
2. Open link from external apps with Firefox.
3. Once Firefox app launched, edit url and press go(->) key from IME.
    I used Gboard to reproduce this issue.

### Expected behavior

Edited url is loaded in the current tab.

### Actual behavior

Edited url is loaded in the previously opened tab.
There is no change in the current tab.

### Device information

* Device vendor / model and Android version: Pixel 3 XL / Android 11 with security update Apr.5
* Firefox for Android version: Firefox Nightly 210413 17:00 (Build #2015804427)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview 88.1.2 and Nightly 4/29.
### Devices used:
- OnePlus 6T (Android 9)
- Pixel 3 XL (Android 9)
