### ISSUE TITLE
Show top sites when address bar is selected in an existing tab

### ISSUE THREAD

**Issue by platinops** [mozilla-mobile/fenix#19022]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
On `fennec` (v68), when you open a new tab or select the address bar of an already opened tab, the "top sites" are shown at the top (or alternatively bookmarks/history).

On `fenix`, when you open a **new tab**, the "top sites" are shown as well. When you select the **address bar** in an already opened tab, the "top sites" are not shown however. It could be more convenient if they would actually be shown, so a user can quickly browse to another "top site" without having to close the current tab, and open a new one.

### How do you know that this problem exists today? Why is this important?
See description above.

### Who will benefit from it?
At the moment, the page that is opened is shown in the background, but this has no added value as far as I see. I believe showing the top sites there would be more convenient.

Alternatively, this could be a user setting.

Thanks for your consideration and feedback.

**Comment by ale82to** [comment]
plenty of users asked for this included myself about a year ago when fenix was still a preview but developers simply will not listen to important feature actually missing from fenix

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/9118
