### ISSUE TITLE
FNX-5324 ⁃ [Bug] Unable to close open tab on home-screen after invoking share menu

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#1903]
* duckduckgo.com
* tap the tabs button next to the address bar
* tap the dotted menu on the open tab (duckduckgo.com)
* tap **Share Tab**
* back out of that view
* tap the '**x**' button on the tab

04/22, Pixel 2 (Android 9)

**Comment by ekager** [comment]
Can reproduce - it also IS closing the tab but the list is not updating accordingly.

**Comment by ekager** [comment]
If you put Fenix in the background and resume after pressing close, the tab is gone

**Comment by LittleAngelwings** [comment]
Not only if Fenix was in background. If you choose another open tab then Fenix increase the tab counter and close the previous choosen tab. If you go to homescreen next time, the tab is gone.

**Comment by boek** [comment]
We took this element out of the UI
