### ISSUE TITLE
[Bug] The new menu is too sparse and has too much white space

### ISSUE THREAD

**Issue by birdie-github** [mozilla-mobile/fenix#19039]
This is a run-of-the-mill device with Android 10, and FHD+ resolution.

A build of Firefox a week ago or so didn't have this bug.

![Screenshot_1](https://user-images.githubusercontent.com/4958603/114788416-ed6a5980-9d70-11eb-8cc6-d4208bf79534.png)
![Screenshot_2](https://user-images.githubusercontent.com/4958603/114788418-ee02f000-9d70-11eb-9bd5-8c199be97168.png)

**Comment by birdie-github** [comment]
The second menu takes pretty much all the vertical space, i.e. close to 2000 pixels.

**Comment by cadeyrn** [comment]
> A build of Firefox a week ago or so didn't have this bug.

If you mean the width of the menu with "has too much white space" then it's not a bug. It has this width due to the long "signed in" string. It will be shorter once #19035 lands.

**Comment by birdie-github** [comment]
1. The vertical spacing between menu items has increased dramatically.
2. The menu spans almost the entire screen.

**Comment by cadeyrn** [comment]
> The vertical spacing between menu items has increased dramatically.

This is not true. I just measured the vertical spacing between the menu items in Firefox 87 and Firefox Nightly - it is exactly the same. With "New Tab" the menu has one menu item more now (well, two more if you compare stable with Nightly because "Report Site Issue" was always Nightly only).

> The menu spans almost the entire screen.

The width increased for the reason I mentioned in my previous comment. And as I already said it will decrease a bit again. The height increased for the reason above.

**Comment by birdie-github** [comment]
> This is not true.

This is not true.

Firefox 87 vs Nightly:

![Screenshot_20210428-firefox87](https://user-images.githubusercontent.com/4958603/116411429-3ae0cf00-a825-11eb-8405-8925930998d5.png)
![Screenshot_20210428-nightly](https://user-images.githubusercontent.com/4958603/116411434-3c11fc00-a825-11eb-9c02-0ede3f8adad3.png)

**Comment by cadeyrn** [comment]
> This is not true.

I don't know why you quoted this sentence from my comment. It's still true what I said: The vertical spacing between menu items did not change at all and your screenshots proves that.

**Comment by birdie-github** [comment]
You could maybe show less items then, put them into submenus, and decrease vertical spacing.
