### ISSUE TITLE
[Bug] Homescreen is not scrollable to see collections

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19030]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open a few collections (2 seem enough).
2. Try to scroll in the home screen.

### Expected behaviour
- The home screen should scroll.

### Actual behaviour
- We can scroll down to the end of collections.

### Device information

* Device vendor / model and Android version: Android 10, Pixel 3
* Firefox for Android version: ? (go to Settings -> About Firefox) Nightly 210412
 

https://user-images.githubusercontent.com/1370580/114751517-3dbaca80-9d23-11eb-9e9e-9a6af7166e5f.mp4

**Comment by jonalmeida** [comment]
This bug came up from the fix in https://github.com/mozilla-mobile/fenix/issues/8545 which I'm going to revert for now.

**Comment by jonalmeida** [comment]
Hmm.. must have closed the bug in error.

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/20 Nightly build with Samsung Galaxy Note 8 (Android 9, and Google Pixel (Android 10).
The homescreen is scrollable, the collections are visible.
