### ISSUE TITLE
Turn off all Leanplum integrations on Fenix by May 31,2021

### ISSUE THREAD

**Issue by krupa-raj** [mozilla-mobile/fenix#19040]
Mozilla has decided to not renew our Leanplum contract for 2021-22. The current contract will expire on May 31, 2021. We need to turn off any Leanplum integrations in our products by that date.

This work should include the following:

 - Remove the Leanplum SDK dependency from our builds so that the product does not include it anymore.
 - Remove all Leanplum related code from the product
 - Remove all Leanplum related UI from the product

Currently the _Marketing data_ setting under the _Data collection_ group says

> Shares data about what features you use in Firefox with Leanplum, our mobile marketing vendor.

When we remove Leanplum from the product, this toggle will only enable/disable _Adjust_. That should probably be reflected in the string we use for the _Marketing data_ setting.

@amedyne @rvandermeulen Because of the adjusted 89 schedule, we probably need to ship this change in a 88 update on May 31st.

**Comment by rvandermeulen** [comment]
> Because of the adjusted 89 schedule, we probably need to ship this change in a 88 update on May 31st.

@krupa-raj So I'm clear, do we need to ship this **on** May 31st or **by** May 31st?

**Comment by pocmo** [comment]
I'll look into preparing a PR for making this changes in the 88 release branch.

**Comment by ItsDevyani** [comment]
Just an FYI: We have default browser campaigns live in iOS release and Fenix Nightly and Release. I can stop the Nightly campaign if need be. I was thinking of stopping campaigns on May 21st, but since we are thinking of an 88 dot release I can stop as you chose a date with Rel Eng, Just slack me once you have a decision.

**Comment by amedyne** [comment]
@topotropic FYI. Here's the corresponding GH ticket referred in the email with subject: "Removing Leanplum from Fenix / Needs string change in settings"

**Comment by pocmo** [comment]
We have removed Leanplum from Nightly (string not updated yet). Beta and Release PRs are up, but not ready for landing yet (needs coordination).

**Comment by pocmo** [comment]
Added the "qa needed" label for Nightly. Overall the patch does not seem risky. The "push" integration needed to change in order to remove Leanplum. So one thing we could explicitly test is that web push is still working correctly.

**Comment by lobontiumira** [comment]
Hi @pocmo!

We cannot identify new devices that use the latest Nightly build from 4/28.
We've also tried to send a push notification to a test device that was registered previously and bumped into this error "No push token exist for this device".
![notoken](https://user-images.githubusercontent.com/40694158/116418877-34fae600-a845-11eb-9223-e6642d4be0e6.jpg)
This is most likely due to the fact that "Firefox news" has been removed...


<img src="https://user-images.githubusercontent.com/40694158/116418014-6e7f2180-a844-11eb-8238-fc39a40192d4.png" width="300" height="550" />

I'll remove the qa:needed label, but leave this issue opened for further testing.

**Comment by pocmo** [comment]
@lobontiumira Sorry, I realized I didn't make it clear what "push" I was talking about. So, Leanplum is completely removed from Nightly. Not being able to identify new devices from Leanplum and no IDs showing up in the secret settings is expected and good to be verified 👍. The thing that should still work, and previously had code overlap with Leanplum, is web push messages/notifications from websites (e.g. see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) and [Documentation on Web Push Notifications](https://developers.google.com/web/fundamentals/push-notifications)). @jonalmeida  recommended the following two pages for testing:
* https://gauntface.github.io/simple-push-demo/
* https://mozilla-services.github.io/WebPushDataTestPage/

**Comment by krupa-raj** [comment]
> > ns on Fenix by May 31,2021
> 
> > Because of the adjusted 89 schedule, we probably need to ship this change in a 88 update on May 31st.

We need to ship the changes by May 31st. My preference is to not wait until the last minute to do it. Sorry about the late reply.

**Comment by lobontiumira** [comment]
Verified on https://gauntface.github.io/simple-push-demo/ with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9) that the web push notifications are still working on the 4/29 Nightly build.

Leaving this issue opened for the beta, and RC testing.

**Comment by sflorean** [comment]
Confirming that web push messages works as expected on 89.0.0-beta.4.

**Comment by pocmo** [comment]
Landed the removal patch on the 88 release branch too.

**Comment by lobontiumira** [comment]
Verified on https://gauntface.github.io/simple-push-demo/ with Samsung Galaxy Note 8 (Android 9) that the web push notifications are working as expected on RC 88.1.4 build.
I'll close this issue since all the builds were verified.
