### ISSUE TITLE
eBay Search Option

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#19056]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
 [comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
 [comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
 [comment]: # (Read [https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue](https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue) for more information)

### What is the user problem or growth opportunity you want to see solved?
The Firefox Android product strives to provide users with a variety of search options. To support this, Firefox engages with a number of search partners. Most recently Firefox has gotten agreement from eBay to extend our search partnership from desktop to mobile.

In allowing users to search with eBay directly from the URL bar on one-off searches ("this time search with"), or persistently with eBay set as their default search engine, we will be providing a greater variety of options, and diversifying our partnership support.

### How do you know that this problem exists today? Why is this important?
We do not yet know the rate at which users will engage with the eBay search option, as it has historically been absent from the Firefox for Android browser. Part of the outcome of this work will be such an understanding, which will inform whether we increase or decrease our support for this option, and other engagement opportunities with this partner over other options.

### Who will benefit from it?
Users interested in searching for products from eBay.

Locales - US, UK, DE

eBay does not need to be placed in any specific order on the Settings > Search page

**Comment by rocketsroger** [comment]
ID for each region/locale is here https://docs.google.com/spreadsheets/d/1HMm9UXjfJv-uHhGU1pJlbP4ILkdpSD9w_Fd-3yOd8oY/edit?skip_itp2_check=true&pli=1#gid=919746834

**Comment by rocketsroger** [comment]
The change is in Nightly.  Please verify. Thanks!

**Comment by lobontiumira** [comment]
Verified on the 6/9 Nightly build with Samsung Galaxy Note 8 (Android 9) that the following locales have eBay as a default search engine option:
* AU - www.ebay.com.au
* BE - www.befr.ebay.be
* CH - www.ebay.ch
* DE - www.ebay.de
* ES - www.ebay.es
* FR - www.ebay.fr
* IE - www.ebay.ie
* IT - www.ebay.it
* NL - www.ebay.nl
* PL - www.ebay.pl
* UK - www.ebay.co.uk
* US - www.ebay.com
* CA - www.ebay.ca
