### ISSUE TITLE
Remove deprecated strings

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#19059]
There are a few strings marked as "deprecated" that we can remove. Make sure they don't have any references to them.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 4/19 with Pixel 2 (Android 9) and Samsung Galaxy Tab S3 (Android 8).
The "Signed in as" in three-dot menu is removed..

**Comment by gabrielluong** [comment]
Not quite sure if this is right. We haven't landed the PR yet.
