### ISSUE TITLE
Improve the Settings screen

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19051]
Currently settings are updated after first being shown on screen.
They may start visible or not and after being displayed on the screen we recheck their status and may decide to add or remove them from the screen. This is a visual bug caused by calling the [update](https://github.com/mozilla-mobile/fenix/blob/a3f4cee388f8d18208ecc11b4ee84900f7e4e659/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt#L177) method in onResume - with the screen already being in the visible state.
This was reported recently also in https://github.com/mozilla-mobile/fenix/issues/18620 and https://github.com/mozilla-mobile/fenix/issues/18819.

There are also recent changes which try to mitigate this issue by loading an entire different PreferenceScreen with just one item changed just to avoid having to add/remove it later, showing again that visual glitch.
I don't think is a maintainable approach because if later another settings needs to be displayed or not we will have an explosion of xmls for all possible permutations and complex nested if checks to decide which settings screen to show.

The solution I'm proposing entails:
- having only one, stable, PreferenceScreen (maybe two at max to support preferences with icons or not)
- all preferences having the `isPreferenceVisible` set to true (default)
- inside `onCreatePreferences` iterate recursively through all `PreferenceGroup`s and `Preference`s. 
This method is called before the settings screen being visible with it's main purpose being to help in creating the right settings options structure.
- call `removePreference` on any `Preference` or even `PreferenceCategory` we don't want.
- [optional] do any other customization for the current iterated to `Preference`.

After the `onCreatePreferences` callback and showing the intended list of settings there is no reason for the shown `Preference`s to be added/removed.
With these changes we'll have a clean, maintainable solution without this sort of issues:

| Removing a setting in `onResume` | Removing the same in `onCreatePreferences` |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/11428869/114865424-e1c37500-9dfa-11eb-99c6-2a7efe6316b7.mp4" /> | <video src="https://user-images.githubusercontent.com/11428869/114865402-dbcd9400-9dfa-11eb-85c5-0f1e63d6ff8c.mp4" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10403)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809242

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by t-p-white** [comment]
Also reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1809660
