### ISSUE TITLE
Fix button arrangement in the Credit Card Editor Fragment

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19055]
https://user-images.githubusercontent.com/11428869/114883703-d594e300-9e0d-11eb-94ab-43841d1a9d15.mp4

- the bottom buttons are not available in landscape (they don't fit the screen and cannot scroll to them)
- the delete button (all buttons) is pushed up by the keyboard and remain there even after the keyboard is dismissed

_Originally posted by @Mugurell in https://github.com/mozilla-mobile/fenix/issues/19029#issuecomment-820459661_

**Comment by gabrielluong** [comment]
The CreditCardEditorFragment is currently using a LinearLayout and the buttons are arranged using a ConstraintLayout. We should consider also converting the entire fragment layout to use ConstraintLayout I think. Please investigate this carefully.

**Comment by kglazko** [comment]
Hey I was wondering if I can work on this one this sprint.
