### ISSUE TITLE
Navigate back to the Credit card screen when the last credit card is deleted

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19054]
After deleting the last card the user is brought to an empty "Saved cards" screen (this will still have the "Add credit card" button despite no saved credit cards to list). We should determine whether or not we should go back to the "Saved cards" screen or back to the "Credit cards" screen.

**Comment by gabrielluong** [comment]
@topotropic pinging you on this

**Comment by topotropic** [comment]
Thanks! Good point – let's go back to the "Credit card" screen once people delete their last card.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 5/20 with Google Pixel 4 XL (Android 11).
Please note that after deleting the credit card I was redirected without issues to the `Credit cards` section.
