### ISSUE TITLE
[Bug] [L10n] "OK" button not translated to Japanese language when a site is added to collection

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#19052]
## Preconditions
In Settings - Languages set the device to Japanese.
Have at least one site opened and one Collection created.

## Steps to reproduce
1. Launch Fenix and go to tabs tray.
2. Select at least 1 site with a long tap on the title.
3. Tap on the "add to collection" icon.
4. Observe the pop-up window.

### Expected behavior
The title and the buttons are translated to japanese.

### Actual behavior
The "OK" button is not translated.

### Device information

* Device vendor / model and Android version: HTC Nexus 9 (Android 7.1.1)
* Firefox for Android version: Firefox Release v88.1.0 (4/13 @ 11:28)

![Screenshot_20210415-170628](https://user-images.githubusercontent.com/48829350/114885163-13463b80-9e0f-11eb-8f71-24898ca0c07b.png)

**Comment by Delphine** [comment]
Thanks for filing!
Apparently, Japanese sometimes use "OK" like in English. I checked on Transvision across Firefox desktop strings, as well as Android strings (ex with Android here: https://transvision.mozfr.org/?recherche=ok&repo=android_l10n&sourcelocale=en-US&locale=ja&search_type=strings)
Therefore closing this. Thanks!
