### ISSUE TITLE
Strip spaces and separators from credit card number input

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19065]
When saving or updating a credit card, we will want to clean up the input provided by the user by stripping the input of spaces and separators that are currently accepted. The TextInputEditText currently accepts the following `android:digits="0123456789- "`. We should add a `Utils` file with a method to `stripSpacesAndSeparators` which will strip the card number input of the spaces and `-` separators. We should then call this helper method anywhere we save or update the credit cards. 

Also, add unit tests for this new `Utils` file.

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/19187
