### ISSUE TITLE
[Bug] New 3-dots menu: menu does not close by swiping down

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#19076]
## Steps to reproduce
Navbar/menu are set at bottom
Open a page
Click on the 3-dots menu
Do not expand it
Swipe down on the menu (next logical move if the user changed his mind about what he wanted to do)

### Expected behavior
The menu is closed 

### Actual behavior
Nothing happens
You have to click elsewhere on the left side of the page, possibly needing to use another finger. 
Not handy at all

### Device information
Redmi Note 7

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox) #2015804891

**Comment by Mugurell** [comment]
This is the expected behavior. Nothing changed regarding how the menu is closed.
After expanding the menu it might not fit the screen and needs to be scrolled up / down so there's no way to know if the user wanted to scroll it or close it.

**Comment by klint** [comment]
> After expanding the menu it might not fit the screen and needs to be scrolled up / down so there's no way to know if the user wanted to scroll it or close it.
Actually there is a way :) : if the top of the menu is displayed when the user swipes, then it means the user wants to close the menu. 

But the real problem is that the menu should be closed the same way it is opened.  On Edge for instance, you click on the ... dots to open it, then on the X at the same location then the dots to close it. I will open another issue for that.
