### ISSUE TITLE
Can collections be improved

### ISSUE THREAD

**Issue by One010101** [mozilla-mobile/fenix#19072]
My English is not good, it is all machine translation
I think it would be more useful to use the collection as your own navigation. This needs to be
1. The ability to adjust the order of collections
2. Can purchase and adjust the order of the internal website of the collection set
3. The ability to rename the names of various websites in the collection.
I'm a big fan of using favorites for sites I visit frequently such as YouTube, BBC Home....
I always categorize them to make it easier to find and visit them. I know Firefox can add sites to popular sites, but these sites are out of order, all at the top, and hard to find when using them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10412)

**Comment by SeburoSUMO** [comment]
User feedback:  

https://support.mozilla.org/en-US/questions/1345834
https://support.mozilla.org/en-US/questions/1345837

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812733

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
