### ISSUE TITLE
3 dots menu cannot be closed easily

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#19077]
Not sure it is a bug or a feature actually :)

On Edge, opening the menu is done by pressing the ... button, which is replaced by a X button at the same location to close the menu. Opening and closing the menu is done is a similar way (same location).

On Firefox, opening the menu is done by pressing the 3dots button, which is then hidden. Closing the menu needs either clicking the back button of the phone, or clicking elsewhere on the page outside of the menu layout. Which is commonly on the left of the screen, on the opposite side of the 3 dots menu that opened the menu (needing another finger to be used).

I as a user do often open the menu to do something then change my mind and close it.

It would be more handy and logical to have a similar method to open and close the menu (either by swiping down or by pressing on the 3dots again, but they are hidden. currently).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10417)

**Comment by LaurentiuApahideanSV** [comment]
I will mark this issue as a feature request in regards to the option to close the menu by repressing the 3 dots menu again.
Regarding opening the page menu by swiping issue https://github.com/mozilla-mobile/fenix/issues/11862 has already been summitted.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809243

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
