### ISSUE TITLE
[Bug] Cannot select text in some website

### ISSUE THREAD

**Issue by xuyuehang** [mozilla-mobile/fenix#19074]
Visiting some Chinese forums (these forums use discuz, a popular forum system) Firefox cannot select the text in the page. When long-pressing, it displays the context menu like long-pressing a link, while other browsers can select the text. In addition, fennec can be selected normally.

For example :https://bbs.kafan.cn/forum.php?mod=viewthread&tid=2206816&fromguid=hot&extra=&mobile=2
![Snipaste_2021-04-16_14-55-17](https://user-images.githubusercontent.com/17559985/114985253-2c112880-9ec5-11eb-9c6c-6b2889542c6a.png)

It seems to be related to #10653, but behaves differently.

### Device information
Samsung S7 with Android 8.0
Nightly 210416 Build #2015804891

**Comment by Mugurell** [comment]
This seems to be a GeckoView issue.
Moving the ticket to Bugzilla.
Please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1705672

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
