### ISSUE TITLE
[Bug]tons of native crashes 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#19098]
so  basically for the last 10 days nighlty keep crashing luckily only tab crashes not whole browser.
last crash was d086ee94-050c-4255-a42e-fe51bcf337f7
<native crash>
----
<native crash>
I suspect to be related to 
https://crash-stats.mozilla.org/report/index/bp-6fb6555a-13e3-4e99-8359-abd250210413

is it normal that such invalidating crash takes so long to be fixed?

**Comment by kbrosnan** [comment]
Tracked in bz-1704887
