### ISSUE TITLE
Undo after deleting selected tabs only returns last tab

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19091]
## STR
1. Enter multi-select mode and select multiple tabs.
2. Close all of them.
3. Click on the undo button.
4. Observe.

## Expected
All the selected and deleted tabs return.

## Actual
Only the last deleted tab returns.

https://user-images.githubusercontent.com/1370580/115640022-fd8bb700-a2e3-11eb-9bca-169eb11a6586.mp4

**Comment by jonalmeida** [comment]
I think we need to separate out the UI snackbar logic from the action so we can better cover this with tests and write in a re-useable way.

Consider also that we have https://github.com/mozilla-mobile/fenix/issues/19090 that needs to use snackbars as well, but doesn't care about undo, but instead "view".

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible. Tested on the latest Nightly (90.0a1 - Thursday 5/13 @ 5:08).

Devices: HTC Nexus 9 and Motorola Nexus 6.
