### ISSUE TITLE
Show snackbar on adding to collection/bookmark from tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19090]
This is a regression in the behaviour from the old tabs tray.

We need to add the two different collection snackbars:
 1. Adding to an existing collection.
 2. Adding to a new one.

UI tests to re-enable when fixed:
 - `verifyExpandedCollectionItemsTest`
 - `shareCollectionTest`
 - `deleteCollectionTest`

See the old tabs tray for reference for now:

https://user-images.githubusercontent.com/1370580/115662746-6cc9d100-a30d-11eb-886d-57896d90fa03.mp4

**Comment by jonalmeida** [comment]
Personal note: Adding an E3 because I think we'd run into snarly problems when trying to refactor and separate the snackbar from the functionality.

**Comment by jonalmeida** [comment]
Renamed the issue to include bookmarks because they both are related.

**Comment by kaream671** [comment]
19090

**Comment by jonalmeida** [comment]
https://github.com/mozilla-mobile/fenix/issues/19475 has landed, so I removed the waiting label.

**Comment by jonalmeida** [comment]
We may be able to re-enable `verifyExpandedCollectionItemsTest` and `createFirstCollectionTest` after this lands.

**Comment by gabrielluong** [comment]
I pointed out some relevant strings that are here for context https://github.com/mozilla-mobile/fenix/pull/19740#discussion_r644321003

**Comment by lobontiumira** [comment]
I was able to reproduce this on Beta 90.0.0-beta.1, beta.2, and beta.3, with OnePlus 5T (Android 10), Samsung Galaxy Note 8 (Android 9), and HTC 10 (Android 8):

https://user-images.githubusercontent.com/40694158/122049291-eef4e400-cdea-11eb-89b7-941125a4aed9.mp4

**NOTE**: the voice assisnatnt is reading the snackbar, when it is turned on, even when the snackbar is not displayed.

**Comment by jonalmeida** [comment]
@rocketsroger When we fix this issue, let's re-enable `createFirstCollectionTest`, `shareCollectionTest`, `deleteCollectionTest` in the same change.

See related linked issues above. ^

**Comment by rocketsroger** [comment]
@lobontiumira my change was not lifted to v90.  Can you please retest with Nightly?  Thanks,

**Comment by rocketsroger** [comment]
Here's what I see on Nightly (master).

https://user-images.githubusercontent.com/6579541/123307728-d70b1780-d4f0-11eb-9833-a46f246aae99.mp4

**Comment by lobontiumira** [comment]
Verified on the 6/25 Nightly build with Samsung Galaxy Note 8 (Android 9).
The "Tab saved! VIEW" snackbar is displayed when adding a new tab to an existing collection.
However, adding a page from the tabs tray to Bookmarks does NOT display any snackbar:

https://user-images.githubusercontent.com/40694158/123384005-86e98f00-d59c-11eb-959e-8f012b015532.mp4

**Comment by rocketsroger** [comment]
> Verified on the 6/25 Nightly build with Samsung Galaxy Note 8 (Android 9).
> The "Tab saved! VIEW" snackbar is displayed when adding a new tab to an existing collection.
> However, adding a page from the tabs tray to Bookmarks does NOT display any snackbar:

Thanks! I'll investigate.

**Comment by rocketsroger** [comment]
@lobontiumira The fix for bookmark snackbar should be in the next Nightly build.  Please verify.  Thanks!

**Comment by lobontiumira** [comment]
Verified as fixed on the 7/7 Nightly build with OnePlus 5T (Android 10).
Both, "Tab saved! VIEW" and "Bookmark saved! VIEW" snackbars are displayed when adding a page from tabs tray.
