### ISSUE TITLE
FNX-5327 ⁃ [UX] Site Control Center (Doorhanger)

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#191]
**User Story:**
As a user I want to have access to and be able to change settings for specific sites.

**Current Design Status:**

* No Design
* Needs Requirements (E.g. Permissions, Zoom Levels, Auto-Play)

**Design Priority:**
P3

**Comment by bbinto** [comment]
To me that's a P1, it might be a P3 for UX, i.e. it's not that controversial or new to UX to design but it's a big part towards making the milestone 1 and 2 and the MVP since those are basic requirements we need to have in there (=MVP).

@lime124 please let me know your thoughts.

**Comment by lime124** [comment]
Just to get a response back to this - from shorlander "we are using it [p3] mostly as an indicator for the order to work on things. For example while Site Settings and Send and Share might both by MVP items, we think Send and Share is more important (and likely requires more work) than Site Settings."

**Comment by shorlander** [comment]
**User Story:**
As a user I want to have access to and be able to change settings for specific sites.

**Current Design Status:**
- No Design
- Needs Requirements (E.g. Permissions, Zoom Levels, Auto-Play)

**Design Priority:**
P3

**Comment by bbinto** [comment]
A/C team to work on this (this has not been done), @vesta0 will work with @st3fan to provide estimates.

**Comment by brampitoyo** [comment]
@lime124 @bbinto I would argue that the user story here (“change settings for specific sites”) refers more to what I think of as Site Permissions.

It’s indeed a very important feature! And I’ve posted the mockups and walkthrough on #188.

The zoom use case mentioned above can either be covered under #188, or under the “Accessibility” section. But in case we want to cover that here, maybe it can be an item under the main menu.

So, do we want to prioritise the Site Permissions issue instead of this one and put it into the sprint/milestone?

**Comment by brampitoyo** [comment]
Closing this issue, since it’s the same thing as (and being done on) #188.

**Comment by brampitoyo** [comment]
Just leaving a note here that the Control Center/Site Information UI will need to show permissions given to websites, and allow users to turn those permissions on and off.

I already designed a page under Site Permissions settings that shows permission on a per-site basis. Maybe we can deep link to there from this Control Center.

**Comment by brampitoyo** [comment]
@st3fan @colintheshots This issue is now ready for Engineering breakdown and feedback.

**Comment by lime124** [comment]
@st3fan @colintheshots please let us know if you have questions or feedback. otherwise we can close this issue. thanks!

**Comment by bbinto** [comment]
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1525466, I think we should be ok with not offering "battery saving" on a per site-basis for MVP
