### ISSUE TITLE
[Bug] First page, loaded from another app or home screen, fails to load if "webRequest" API is used

### ISSUE THREAD

**Issue by M-Reimer** [mozilla-mobile/fenix#19100]
## Steps to reproduce

Install my "Android PDF.js" Add-on in version 2.1.1 (I may try to work around this issue somehow in future, so use this exact version)
https://addons.mozilla.org/en-US/android/addon/android-pdf-js/

Now keep the Add-on installed while using Nightly for some "daily browsing tasks". After some time you'll run into the problem for the first time, that opening a page from another app or from the home screen on Android triggers the page loading, but page loading gets interrupted at some point and leaving you with a blank page without any error message at all.

### Expected behavior

An error message of some kind would be the bare minimum. Attaching a desktop Firefox to inspect the App on Android did not reveal any suspicious error and as nothing is crashing, I also don't know how to find something useful with "logcat".

### Actual behavior

Empty page for no known reason.

![Screenshot_20210418-111941](https://user-images.githubusercontent.com/3519517/115140631-7e268b00-a038-11eb-90ad-48274deb6b86.png)

### Device information

* Device vendor / model and Android version: Google Pixel 3a XL, Android 11
* Firefox for Android version: Nightly 210416 17:01

**Comment by M-Reimer** [comment]
I use the "webRequest" API in the following places:
https://github.com/M-Reimer/android-pdf-js/blob/ca246ad71ad1794a0d416412168fedf98f79222d/pdfHandler.js#L164-L194
https://github.com/M-Reimer/android-pdf-js/blob/ca246ad71ad1794a0d416412168fedf98f79222d/preserve-referer.js#L79-L109

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1706128

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
