### ISSUE TITLE
[Bug] Set as default browser redirect to support website

### ISSUE THREAD

**Issue by ThePsychoBuck** [mozilla-mobile/fenix#19107]
## Steps to reproduce

1) open firefox
2) go to settings
3) tap on 'set as default browser'

### Expected behavior

It redirects to settings where default browser is set. 

### Actual behavior

It redirect to support website

### Device information

* Device vendor / model and Android version: Vivo V51L / Android Version 5
* Firefox for Android version: 87.0.0

https://user-images.githubusercontent.com/82816796/115235288-a77a1080-a137-11eb-9008-802a9089c4bd.mp4

**Comment by cadeyrn** [comment]
This is expected due to your outdated Android version.

> Lower Android versions don't offer the possibility of opening system settings
at a specific preference.

https://github.com/mozilla-mobile/fenix/commit/02d70d38373d19c977f20a942ee20ca164f02ec4

**Comment by ThePsychoBuck** [comment]
Thanks @cadeyrn
