### ISSUE TITLE
[Bug] lockwise problem with system unlock

### ISSUE THREAD

**Issue by Greg57C** [mozilla-mobile/fenix#19109]
Phone security and lock screen is preventing FF mobile from opening the built it password manager lockwise.
It DID work on previous versions of FF because I have always had my lock screen on Note 8 set to drawing a pattern to unlock phone. But in latest version it stopped functioning. 
The built in version does not require downloading the lockwise addon separately.

It's very easy to re-create the issue. Turn any of your phones security lock screen logons to anything but NONE and it will break the function of FF Lockwise!

Samsung Galaxy Note 8
Android 9
FF 87.0.0-rc.1 (Build #2015799099)

**Comment by kbrosnan** [comment]
I'm not seeing a Fenix issue here. Lockwise issues can be reported to https://github.com/mozilla-lockwise/lockwise-android/issues
