### ISSUE TITLE
[Bug] Three-dots menu now hides the navigation buttons out of the view

### ISSUE THREAD

**Issue by mathieui** [mozilla-mobile/fenix#19105]
## Steps to reproduce

On a my android device, open the three-dots menu when on a page.

### Expected behavior

I can access the "refresh", "back", and "next" button easily after opening the menu.

### Actual behavior

The buttons are scrolled out of the view and I end up tapping "report site issue" thanks to muscle memory.

![screenshot](https://pix.mathieui.net/s/YaHnd.png)

### Device information

* Device model: Samsung Galaxy S10e, on some Lineage OS rom (Android 10)
* Firefox for Android version: Nightly 210418 17:03 (Build #2015805387)
 
### Additional information

The S10e is on the "small" side of android screens (5.6"), so maybe this works fine on bigger screens.

**Comment by hakkikaancaliskan** [comment]
#19018 will fix this issue

**Comment by SoftVision-LorandJanos** [comment]
Hi @mathieui ! Thank you for your report! I can confirm that the issue you reported is reproducible, however as mentioned above, will be fixed along with #[19018](https://github.com/mozilla-mobile/fenix/pull/19018). Verified with LG Nexus 5 (Android 6.0.1).

**Comment by mathieui** [comment]
Thanks, it does look like a duplicate. I did not know what terms to search for when creating the issue.

**Comment by ebalazs-sv** [comment]
Closing as duplicate to issue https://github.com/mozilla-mobile/fenix/issues/18591.
