### ISSUE TITLE
FNX-5328 ⁃ [Bug] Display Toolbar flashes for a moment when entering search fragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1910]
## Steps to reproduce
1. Open search fragment

## Expected
1. The edit toolbar appears immediately

## Actual
1. The display toolbar appears momentarily then moves to edit mode

![](https://user-images.githubusercontent.com/4400286/56535587-e78a6680-6510-11e9-9502-ece621db52c6.png)

**Comment by ekager** [comment]
See #507 for related bug in the past

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/3120
