### ISSUE TITLE
[Bug] Printer app via share menu is not opened

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#19104]
## Steps to reproduce
Open share menu and choose printer app.
### Expected behavior
Printer dialog should be opened.
### Actual behavior
Nothing happens when printer icon is choosen.

As it works with Google's chrome browser, I think the cause is to be searched at Firefox.
### Device information

* Device vendor / model and Android version: 
Samsung Galaxy XCover 4s
SM-G398FN
Android 10
* Firefox for Android version: 
87.0.0-rc.1 (Build #2015799099)
AC: 73.0.11, bea80bbac
GV: 87.0-20210315170302
AS: 71.0.0

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/10217
