### ISSUE TITLE
Change border radius for top sites icon from 4dp to 8dp

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/fenix#19113]
### Acceptance Criteria
- Based on Figma, the border radius for the top sites icon should be 8dp https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=809%3A1
- We decided to create a separate issue for this since it is not part of the acceptance criteria for adding shadows/elevation

**Comment by brampitoyo** [comment]
@kglazko That’s correct.

Border radius of the box enclosing the icons are 8dp.

Border radius of the icon mask themselves are 4dp.

**Comment by gabrielluong** [comment]
This should be a simple change here https://github.com/mozilla-mobile/fenix/pull/19008/files#r616011373
