### ISSUE TITLE
Remove old tabs tray code and feature flag after release

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19112]
Once we release our code and we don't need this old code and the `tabsTrayRewrite` feature flag. 🎉

**Comment by codrut-topliceanu** [comment]
Waiting for release

**Comment by jonalmeida** [comment]
We removed old tabs tray code, but it would be great to verify that we didn't break any existing behaviours during this with a santiy round of testing from QA.

**Comment by lobontiumira** [comment]
Verified on the 6/9 Nightly build with HTC 10 (Android 8), and Samsung Galaxy Note 8 (Android 9).
The tabs tray's behaviour is without issues. I've tested in normal mode, private mode, portrait and landscape, list or grid view, dark or light theme, multiple tabs and so on.
I'll close this issue.

**Comment by jonalmeida** [comment]
Thank you @lobontiumira ! ❤️
