### ISSUE TITLE
[Bug] Three-dot menu shows account settings when not signed in

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19114]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Ensure you **don't** have a Sync account.
2. Click on the 'Sign in to sync' button on a browser screen.

### Expected behavior
- You are taken to the screen to sign in to a Sync account.

### Actual behavior
- You are taken to a (disabled) account settings screen that does not function.

### Device information

* Device vendor / model and Android version: Android 10, Pixel 3
* Firefox for Android version: ? (go to Settings -> About Firefox) master as of 8bb7abc3f 
 
<img width="434" alt="Screen Shot 2021-04-19 at 1 49 26 PM" src="https://user-images.githubusercontent.com/1370580/115280552-1181be00-a116-11eb-87be-82e876bb95eb.png">

**Comment by sflorean** [comment]
Verified as fixed on Nightly 4/23 with Pixel 3 (Android 11). Scenarios covered:
- Fresh install
- Disconnect account and perform the steps from the description
- Sign in from 3dot menu, tabs tray -synced tabs, and 3dotmenu from synced tabs
- Normal and private browsing (where applicable).
