### ISSUE TITLE
[Bug] The synced tabs tray isn't preserved when minimizing and reopening the app

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#19128]
## Steps to reproduce
1. Install the latest Nightly, from 4/20.
2. Sign in with a valid account.
3. Open the tabs tray, the synced tabs tray.
4. Minimise the app.
5. Reopen the app.

### Expected behavior
The synced tabs tray is displayed.

### Actual behavior
The focus jumps from synced tabs tray to the normal browsing tabs tray.
If the user has an opened tab in the private mode, and minimizes the app from the synced tabs tray, the focus jumps on the private mode tabs tray.
If the user does NOT have a private tab opened, and minimizes the app from the synced tabs tray, the focus jumps on the normal mode tabs tray.

### Device information
* Devices: Google Pixel (Android 10), Pixel 3 (Android 11), Pixel 2 (Android 9), Samsung Galaxy Note 8 (Android 9)
* Firefox for Android version: 4/20 Nightly build
* Note: in Beta 88.0.0-beta.6, and RC 88.1.1, the focus doesn't change from private tabs tray to normal tabs tray.

https://user-images.githubusercontent.com/40694158/115358678-91fff780-a1c6-11eb-9ebc-59d44e910e97.mp4

**Comment by jonalmeida** [comment]
We could use some UX feedback here: when returning to the tabs tray, we should the tray type depending on if we're in Private Browsing mode or not. We don't take into account Synced Tabs.

What would be the right thing to do, if a user is set of the Synced Tabs list, closes the tray (or focuses away), and then returns back?

**Comment by amedyne** [comment]
@topotropic Any thoughts here?

**Comment by topotropic** [comment]
@jonalmeida that's an interesting one – I guess because we have the bottom sheet paradigm, the tab tray depends on whatever is in the background. I think we can leave it for now but this requires some more thought, I'll add it to the UX backlog and will close it for now.
