### ISSUE TITLE
New Tab Page stretch goal: move pin icon from the top of shortcut tile, to next to item title

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/fenix#19125]
Figma: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=809%3A1

The pin icon is currently position on the top-left corner of the shortcut tile box. We’d like to move it next to the item title.

As for the icon asset, we can use the small redrawn pin icon provided in this artboard: https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-WIP?node-id=2326%3A221

We can also wait to replace this asset, until it’s done by @Amejia481.

**Comment by mcarare** [comment]
Reopened for QA.

**Comment by sflorean** [comment]
Tested on Nightly 4/23 with Pixel 3 (Android 11) and with Huawei MediaPad M2 (Android 5.1.1) and the pin icon is not aligned with the favicon, as displayed on Figma. 

@mcarare should we open a new issue and close this as verified?

![Screenshot_20210423-170327 (1)](https://user-images.githubusercontent.com/58466444/115883130-1f0cb000-a456-11eb-9f41-b0e6d71bb219.png)

**Comment by sflorean** [comment]
Closing as verified, we will log a new bug-enhancement for pages that have a long title.
