### ISSUE TITLE
Set accessibility focus on selected tab in TabsAdapter

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19139]
When we draw the view holder items, we do not set the selected tab with accessibility focus. We can probably fix this by passing the `isSelected` flag into the `Tab` of the view holder. Then, when the view is attached, we can request focus on it. Without knowing the selected tab, we have to do some awkward checks first:

```kotlin
override fun onViewAttachedToWindow(holder: TabViewHolder) {
    val tabs = tabs ?: return super.onViewAttachedToWindow(holder)

    val isSelected = holder.tab?.id == tabs.list[tabs.selectedIndex].id

    if (isSelected) {
        holder.itemView.requestFocus()
        holder.itemView.sendAccessibilityEvent(
            AccessibilityEvent.TYPE_VIEW_FOCUSED
        )
    }

    super.onViewAttachedToWindow(holder)
}

```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10456)

**Comment by neha-b2001** [comment]
> Hi @neha-b2001, you can! However, I think we can move this to the Fenix project and have the accessibility focus code added to the [`BaseBrowserTrayList`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/tabstray/browser/BaseBrowserTrayList.kt).
> 
> I'll move the ticket over there now. 🙂

Oh ohkay, thanks 👍

**Comment by neha-b2001** [comment]
Hello @jonalmeida, is it okay if the code for setting accessibility event as `TYPE_VIEW_FOCUSED` is added to the `onAttachedToWindow()` method of `BaseBrowserTrayList`?  https://github.com/mozilla-mobile/fenix/blob/d1951cc67256ed2fa2a2f8c36e826e63d3cbd816/app/src/main/java/org/mozilla/fenix/tabstray/browser/BaseBrowserTrayList.kt#L77

**Comment by jonalmeida** [comment]
Hmm, thinking about this a bit more, I'm not sure how straight-forward this change is. We can't just make the call in `onAttachedToWindow` or `onViewAttachedToWindow` because we want it to only happen once when opening the tab, and not you scroll through the list or switch between the different browser lists.

You would probably have to make a call [below here](https://github.com/mozilla-mobile/fenix/blob/65374717839aba8a78358072d733edaf544f359b/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/BaseBrowserTabViewHolder.kt#L45) to the `trayList` to tell it focus on the selected tab and set accessibility focus.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813616

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
