### ISSUE TITLE
[Bug] Account settings page is not dismissed when signing out from Tabs Tray

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#19132]
## Steps to reproduce
1. Launch Fenix and log in with a Firefox account;
2. Go to Tabs tray - Sync Tabs;
3. Tap the three-dot menu and tap Account settings;
4. Tap Sign out and Disconnect;
### Expected behavior
The Account Settings page is dismissed and the account is disconnected.
### Actual behavior
The Account settings page is not dismissed, the account details still displayed.
Leaving and going back to the Account settings, shows the account as disconnected and the Turn on Sync page is displayed.

### Note
In the Settings -> Sign in to sync, the Account settings page details is still displayed.
![20210420_120057](https://user-images.githubusercontent.com/48799384/115375555-96341100-a1d6-11eb-887c-18d2a87d26d4.gif)

### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9), Pixel 3 (Android 11), Motorola Nexus 6 (Android 7.1.1)
* Firefox for Android version: Nightly 4/20

**Comment by sflorean** [comment]
Verified as fixed on Nightly 5/7 with Samsung Note 10 (Android 11).

**Comment by jonalmeida** [comment]
These changes have been uplifted and should be available on the next beta.

**Comment by sflorean** [comment]
Verified as fixed on Beta version.
