### ISSUE TITLE
[Bug] Top sites - can't delete entries from the second page

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19131]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Install Fenix and log in with a Firefox account.
2. Go to Top sites.
3. Swipe to the second page.
4. Perform a long tap on one of the pages.
5. Tap on "Delete from history".

### Expected behavior
The page is deleted.

### Actual behavior
The page is not deleted.

### Device information
* Device vendor / model and Android version: Pixel 3 (Android 11), Samsung Galaxy Note 8 (Android 9),  HTC Nexus 9(Android 7.1.1), Motorola Nexus 6 (Android 7.1.1).
* Firefox for Android version: Nightly 4/20 

https://user-images.githubusercontent.com/58466444/115370339-a4336300-a1d1-11eb-960e-dbee150db187.mp4

**Comment by sflorean** [comment]
The issue is still reproducible on latest Nightly build with Pixel 3 (Android 11).

**Comment by codrut-topliceanu** [comment]
Issue reproducible only when trying to delete the same row/column position multiple times:


https://user-images.githubusercontent.com/60002907/121507070-faac6900-c9ec-11eb-9a67-0c0062522e13.mp4

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/9 with Samsung Note 10 (Android 11).
