### ISSUE TITLE
[Bug] Tabs tray content is not visible when switching from portrait to landscape mode

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#19135]
## Steps to reproduce
1. Launch Fenix and tap the tab counter;
2. Switch the device from portrait to landscape mode;
3. Observe the Tabs tray;
### Expected behavior
The Tabs tray content is visible when switching from portrait to landscape mode.
### Actual behavior
The Tabs tray content is not visible when switching from portrait to landscape mode.
![20210420_144639](https://user-images.githubusercontent.com/48799384/115391025-a30d3080-a1e7-11eb-94e3-720e80c4e32e.gif)

### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9);
* Firefox for Android version: Nightly 4/20
* Not reproducible on Beta 88.0.0-beta.6 from 4/11 and Release 88.1.1 from 4/16.

**Comment by jonalmeida** [comment]
This is partly known since we didn't land any landscape-mode support in the re-write yet. Thank you for filing!

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/17 Nightly build with Google Pixel (Android 10), OnePlus 5T (Android 10), and Samsung Galaxy Tab A6 (Android 5.1.1).
