### ISSUE TITLE
[Bug] Can't use input fields on websites

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#19156]
## Steps to reproduce
1. go to google.com or any other site with an input field
2. select the input field

### Expected behavior
Keyboard pops up and I can enter something

### Actual behavior
The form field is selected but the keyboard doesn't pop up

### Device information
* Device vendor / model and Android version: Pixel 3
* Firefox for Android version: Nightly Build #2015805771

**Comment by mcarare** [comment]
@topotropic What Android version does the Pixel 3 have?

**Comment by pocmo** [comment]
Can't reproduce on Pixel 4a / Android 11 / Nightly 2021-04-20.

**Comment by topotropic** [comment]
> @topotropic What Android version does the Pixel 3 have?

11

**Comment by topotropic** [comment]
ok, this is weird – I cleaned the cache and now it's working.
