### ISSUE TITLE
FNX-5331 ⁃ [Bug] Tab crashed error page doesn't appear

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1915]
## Steps to reproduce
1. Go to about:crashcontent.
    1. Expected behavior
The tab crashed error page is displayed.
    1. Actual behavior
No error page, the app crashes entirely.
    1. Device information

* Android device: Pixel
* Fenix version: 4/22

**Comment by sblatz** [comment]
This was fixed by an [a-c change](https://github.com/mozilla-mobile/android-components/issues/2794)

**Comment by sv-ohorvath** [comment]
Verified as fixed on 4/24 build.
