### ISSUE TITLE
PWA black screen after some time of inactivity

### ISSUE THREAD

**Issue by wurstsemmel** [mozilla-mobile/fenix#19157]
### Steps to reproduce
Install the PWA for meta.discourse.org (no login required) by opening the page in Firefox for Android and pressing "Install" in the three-dots-menu. Use the PWA for a little while. Do something else on the phone, lock the phone, wait roughly 3 hours. Open the PWA by tapping its icon.

### Expected behavior
The PWA should open.

### Actual behavior
A black screen is displayed.

### Additional Information
- The PWA works on Google Chrome with no issue after inactivity.
- I disabled battery optimization for Firefox with no luck.

### Device information
* Device vendor / model and Android version: Samsung Galaxy S9, Android 10, One-UI 2.5
* Firefox for Android version: 88.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10466)

**Comment by wurstsemmel** [comment]
Additional information:

- I suggest to wait/do something else for roughly 3 hours to reproduce the issue. I changed the section "Steps to reproduce" accordingly. When doing something else on the phone for about one hour the PWA may still work.
- I can reproduce the bug also with another PWA (https://findpwa.com/app/wheel). I have tested two PWAs in total.

**Comment by wurstsemmel** [comment]
Dear @LaurentiuApahideanSV, thank you very much for looking into this and trying to reproduce.

I still have the issue with Firefox for Android (Firefox Daylight) 88.1.3. The PWA is just minimized to the background, i.e. the PWA shows up in the App Switcher. If I close the PWA from the App Switcher and open it afterwards everything is back to normal.

The same websites accessed directly in Firefox (not the PWA) have no issue.

Please note that I can reproduce it on Samsung Galaxy S9 (Android 10) and Galaxy S21 (Android ?). However, it is not so easy to reproduce. Sometimes it works for a day or more, so the best way to reproduce is to include the PWA usage into daily smartphone use and test for an extended period of time.

**Comment by box-dev** [comment]
I think this might be a much bigger issue on lower-end devices - where the system unloads the tab process due to other applications requiring resources? I may be unlucky here but my phone is fairly low end and I can reproduce this very easily by opening the PWA, then opening some other applications in turn, then switching back to the PWA. It is quite a low spec device so apps are frequently unloaded and restore when opened. Something about the PWAs seems to get messed up somewhere along the way.

As the original reporter notes, this does not happen with tabs opened inside Firefox itself, which even when unloaded restore themselves normally.

NOTE - this also affects custom tabs opened inside other applications. For example, the Twitter Lite official app, which is basically just a wrapper for a custom tab as far as I can see, is also affected by this issue because it relies on a custom tab from Firefox (when Firefox is the installed browser)

**Comment by wurstsemmel** [comment]
Thank your for commenting. That could make sense. It is an issue on low-end devices and - maybe to a lesser extent - on a subset of high-end devices, maybe only Samsung? Just as a friendly reminder, I reproduced it on a Galaxy S21.

I tend to speculate (no proof!) that on the Galaxy S9 and S21 which I was using to test some type of manufacturer memory "optimization" kicks in and kills the PWA.

**Comment by klint** [comment]
I also suffer from this bug quite regularly on my Redmi Note 7 with 3GB of RAM, and I don't have to wait for hours. 
As @box-dev commented above,  I just need to switch to one or 2 other apps then go back to Fenix PWA and it is black and empty.
This is a really annoying and bug with a quite visible effect, and sadly, it is the main reason that prevents me from promoting Fenix to my friends and family to a greater extent, actually. 
As any investigation been done on that issue already?
Thank you

**Comment by brudolp** [comment]
@wurstsemmel the bug linked above is probably a duplicate, in my case after enabling 'don't keep activities' and 'background process limit =1' in developer options the behavior could be reproduced reliably (mi9tpro and Pixel3a)

**Comment by wurstsemmel** [comment]
@brudolp Very exciting! I changed the settings in Android Developer Options and now I can also reproduce the issue reliably.

With this, I hope that the root-cause can be identified by some knowledgeable persons and potentially a fix may become available.

**Comment by liebharc** [comment]
We are facing this issue with our own PWA. Let us know if we can support you with additional information.

**Comment by elichai** [comment]
Any chance this bug and https://github.com/mozilla-mobile/focus-android/issues/4599 are related?
This is starting to be frasturating 😕, I use Firefox beta and it happens both on PWA but also with regular tabs sometimes, mainly when I'm quickly jumping back and forth between multiple apps.

If I can help in any way (logs/debugging/running alpha versions etc) I'd be more than happy to help

**Comment by ICHx** [comment]
the problem is still there

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807420

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
