### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tat-2whatever** [mozilla-mobile/fenix#19151]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Actual behavior: maps show my 
![Screenshot 2021-04-20 2 40 21 PM](https://user-images.githubusercontent.com/78065163/115468909-621e1780-a1f9-11eb-8c5a-ea91a0134036.png)
location in Minneapolis

### Device information: Chrome Pixelbook

* Device vendor / model and Android version: ? Chrome Pixelbook
* Firefox for Android version: ? (go to Settings -> About Firefox) Linux Apps Beta

**Comment by cadeyrn** [comment]
Your screenshot shows Firefox for desktop operating systems. This issues tracker is not for the desktop Firefox but for Firefox for Android.

**Comment by sflorean** [comment]
Closing based on the above comment.
