### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tat-2whatever** [mozilla-mobile/fenix#19150]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information Chrome Pixelbook

* Device vendor / model and Android version: ? Linux App Beta
* Firefox for Android version: ? (go to Settings -> About Firefox) ESR
![Screenshot 2021-04-20 4 36 52 PM](https://user-images.githubusercontent.com/78065163/115468042-15860c80-a1f8-11eb-98ae-423806f6d49c.png)
![Screenshot 2021-04-20 4 38 02 PM](https://user-images.githubusercontent.com/78065163/115468045-174fd000-a1f8-11eb-80ef-d4c0b5cd8fc2.png)

**Comment by sflorean** [comment]
Please file bugs for Firefox Desktop here : https://bugzilla.mozilla.org/, your screenshots are not about Firefox Android. Thank you!

**Comment by tat-2whatever** [comment]
My eyes are going one way and the other way. Let me read this and let me get back to you
