### ISSUE TITLE
Web notifications are not displayed 

### ISSUE THREAD

**Issue by Senshi26** [mozilla-mobile/fenix#19152]
There's a post on SO, where it all started 
https://stackoverflow.com/questions/66918514/pushmanager-subscription-fails-on-firefox-for-android/66946482?noredirect=1#comment118754360_66946482

Issue is reproduced on FF mobile 88.1.1

_Test Case:_ 
Mobile FireFox (88.0, buildID 20210415), 
Desktop Firefox connected (87.0, buildID 20210318)

https://web-push-book.gauntface.com/

_Step 1:_ 
Allow Service Worker registration

_Step 2:_ 
Send Push Message

_Step 3:_ 
Confirm Delivery

This is how SW is requesting permission
```javascript
 async function registerSW() {
  await navigator.serviceWorker.register('/demos/notification-examples/service-worker.js');
}

function getSW() {
  return navigator.serviceWorker.getRegistration('/demos/notification-examples/service-worker.js');
}
```

Whenever I try to display push on Android - **I get nothing**

```javascript
registration.showNotification("HEllo"
 );
Promise { "fulfilled" }
​
<state>: "fulfilled"
​
<value>: undefined
```
Please validate information and doublecheck if browser notifications may be displayed on FF Mobile.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-10463)

**Comment by jonalmeida** [comment]
@Senshi26 could you perhaps grab some logs from your device when Fenix is starting up, that would be helpful.

This sounds like the long term effects of https://github.com/mozilla-services/autopush/issues/1445 popping up, but we can only confirm that with device logs.

**Comment by jonalmeida** [comment]
A list of the open StackOverflow questions (including the one above):
 - https://stackoverflow.com/questions/63738057/firefox-pushmanager-subscribe-does-not-work-on-android
 - https://stackoverflow.com/questions/66918514/pushmanager-subscription-fails-on-firefox-for-android/

**Comment by Senshi26** [comment]
@jonalmeida could you please advice where should I can get the necessary logs? 
Should I use Android Studio for that purpose ?

**Comment by jonalmeida** [comment]
@Senshi26 If you have android studio, that could work too! Alternatively, the output from `adb logcat` will work just as well.

The instructions here for reproducing a "crash" works here too: https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#reproducing-the-crash

**Comment by Senshi26** [comment]
Hello @jonalmeida ! 
I hope I did it right. 
Please find attached file with adb logs. 
[adb_ff_logcat.txt](https://github.com/mozilla-mobile/fenix/files/6449186/adb_ff_logcat.txt)

Cheers,
Michi

**Comment by jonalmeida** [comment]
Thanks @Senshi26 ! Let's analyse the logs now:

> 05-10 06:11:09.103 I/AbstractFirebasePushService(22591): onMessageReceived
> 05-10 06:11:09.103 I/AbstractFirebasePushService(22591): Processing message with chId: 966382ac624f3e48ad211753b845b489
> 05-10 06:11:09.104 I/AutoPushFeature(22591): New push message decrypted.
> 

This tells us that the push notification is indeed getting through the autopush servers from the Simple Push Demo site, and we were able to decrypt it.

> 05-10 06:11:09.351 D/NotificationService( 1641): 0|org.mozilla.firefox|1|https://gauntface.github.io#tag:simple-push-demo-notification|10460: granting content://settings/system/notification_sound

The system notification service has received the notification and is given sound notification access.

> 05-10 06:11:09.367 D/InterruptionStateProvider( 2303): No bubble up: not allowed to bubble: 0|org.mozilla.firefox|1|https://gauntface.github.io#tag:simple-push-demo-notification|10460
> 05-10 06:11:09.368 D/InterruptionStateProvider( 2303): No heads up: unimportant notification: 0|org.mozilla.firefox|1|https://gauntface.github.io#tag:simple-push-demo-notification|10460

We don't have heads up setting (a notification that can show the prompt immediately without the notification drawer open).

Therefore, as far as I can see, you are receiving the notifications correctly. Maybe your notification settings that are default or set by you conflict with how you would like to see it?

**Comment by Senshi26** [comment]
Hello @jonalmeida ! 
With all my respect, I can see no notification at all. 
As far as I understand FF mobile should initiate drawer of push message in Android and display the message using NotificationBuilder: 
```java
NotificationCompat.Builder builder = new NotificationCompat.Builder(this, CHANNEL_ID)
        .setSmallIcon(R.drawable.notification_icon)
        .setContentTitle(textTitle)
        .setContentText(textContent)
        .setPriority(NotificationCompat.PRIORITY_DEFAULT);
```

User expects to see the common push message in the tray. 

Here's an example from Chrome: 
![common_push_message](https://user-images.githubusercontent.com/3395857/119229329-28a23a00-bb20-11eb-8f71-2233d044347f.jpg)

I believe that any message sent to FF should be displayed the same way. 

Cheers,
Michi

**Comment by jonalmeida** [comment]
Can you share the notification settings are for 'Site notifications' in Firefox? See my above comment where the logs you provided confirm that you are receiving the notification. My guess (as mentioned above) is that your notification settings may be set to have the notifications disabled.

**Comment by aroskuski** [comment]
I think I've seen behavior like this twice now.  Suddenly all push notifications would stop, and attempts to subscribe to new ones just wouldn't work.  It seems like Firefox occasionally just gets stuck in a state where push notifications break completely.  Both times I've managed to work around the issue by clearing all the storage for Firefox and creating a fresh profile, but that's not really a great long-term solution.

**Comment by jonalmeida** [comment]
> I think I've seen behavior like this twice now. Suddenly all push notifications would stop, and attempts to subscribe to new ones just wouldn't work. It seems like Firefox occasionally just gets stuck in a state where push notifications break completely. Both times I've managed to work around the issue by clearing all the storage for Firefox and creating a fresh profile, but that's not really a great long-term solution.

What you're describing is a known issue that is linked to https://github.com/mozilla-services/autopush/issues/1445.

This bug has logs that confirm the push message is delivered and the notification is sent to the OS.

**Comment by aroskuski** [comment]
> > I think I've seen behavior like this twice now. Suddenly all push notifications would stop, and attempts to subscribe to new ones just wouldn't work. It seems like Firefox occasionally just gets stuck in a state where push notifications break completely. Both times I've managed to work around the issue by clearing all the storage for Firefox and creating a fresh profile, but that's not really a great long-term solution.
> 
> What you're describing is a known issue that is linked to [mozilla-services/autopush#1445](https://github.com/mozilla-services/autopush/issues/1445).
> 
> This bug has logs that confirm the push message is delivered and the notification is sent to the OS.

Ah, thank you for pointing me towards that.

**Comment by Senshi26** [comment]
> Can you share the notification settings are for 'Site notifications' in Firefox? See my above comment where the logs you provided confirm that you are receiving the notification. My guess (as mentioned above) is that your notification settings may be set to have the notifications disabled.

Hello @jonalmeida ! 
site notifications are allowed upon request. 
As was described above, the request to send pushes was allowed. 

![image](https://user-images.githubusercontent.com/3395857/120983525-72c32680-c782-11eb-90dc-8ced29f30e07.png)

**Comment by jonalmeida** [comment]
> > Can you share the notification settings are for 'Site notifications' in Firefox? See my above comment where the logs you provided confirm that you are receiving the notification. My guess (as mentioned above) is that your notification settings may be set to have the notifications disabled.
> 
> Hello @jonalmeida !
> site notifications are allowed upon request.
> As was described above, the request to send pushes was allowed.

Sorry, I was referring to the Android system notification settings for the Firefox app. The notification group, that allows the notifications is called "Site notifications" (might be translated differently in other languages).

**Comment by Senshi26** [comment]
Hello @jonalmeida ! The Notification settings are fine - the checkbox is set to Allow upon acknowledgement
Please reproduce on your device or report solution. 


Cheers,
Michi

**Comment by Toutenkit** [comment]
Hi,
I have the same problem

### My test
◾ My phone : Samsung Galaxy A51 > Android 11
◽ My old device : Samung Galaxy S7 Edge > Android 8.0.0

#### ✅ WORKS ON
🔹<ins>**Mobile Firefox**</ins>
◽ My old device : Mozilla/5.0 (**Android 8.0.0**; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0
(Note : Clicking on the push redirects to the homepage)

<ins>**Mobile Firefox on Android beta**</ins>
◾ My phone : Mozilla/5.0 (**Android 11**; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0

<ins>**Mobile Firefox Nightly**</ins>
◾ My phone : Mozilla/5.0 (**Android 11**; Mobile; rv:92.0) Gecko/94.0 Firefox/94.0

#### ❌ DOES NOT WORK ON

🔹<ins>**Mobile Firefox**</ins>
◾ My phone : Mozilla/5.0 (**Android 11**; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0
User 2 : Mozilla/5.0 (**Android 10**; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0

<ins>**Mobile Firefox Focus**</ins>
◾ My phone : Mozilla/5.0 (**Android 11**; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0


|                                   | Android 8     | Android 10    | Android 11    |
| -----------                       | -----------   | -----------   | -----------   |
| Mobile Firefox                    | ✅            | ❌           | ❌           |
| Mobile Firefox on Android beta    |               |               |  ✅          |
| Mobile Firefox Nightly            |               |               | ✅           |
| Mobile Firefox Focus              |               |               | ❌           |


---

### Try some tests

1. If you have another phone running Android 8
2. Otherwise try Firefox Nightly or Firefox on Android beta

---

The difference would be in the versions of Android
On Android 10/11 it would be missing > <ins>**empty keys.auth**</ins>
p256dh it's OK

Kind regards
Kit

**Comment by yaakovfeldman** [comment]
I have the same problem on today's Android Nightly running 96.0a1 on Android 11. My notifications on my own site stopped working recently but I can still get Push notifications from other sites. USB debugging confirms the same error `DOMException: User denied permission to use the Push API.` Commenting because I would be happy to provide logs if you let me know what would be helpful.

**Comment by yaakovfeldman** [comment]
This is the output of `grep push` in the logs:

```
11-11 12:50:20.701 22894 23012 I push::internal::communications: subscribed to channel 'ae5875e9a15c31c3a5bbbd4dbd6b0181' via "https://updates.push.services.mozilla.com/v1/fcm/boxwood-axon-825/registration/7fb759a66ab741f2a7de8dc821a05031/subscription" - 200
11-11 12:50:20.701 22894 23012 E WebPushEngineDelegate: Error on push onSubscribe.
11-11 12:50:20.701 22894 23012 W App     : mozilla.appservices.push.PushException$CommunicationException: Communication Error: "response has no `uaid`"
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.appservices.push.PushException$ErrorHandler.read(push.kt:15)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.appservices.push.PushException$ErrorHandler$lift$1.invoke(push.kt:2)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.appservices.push.PushException$ErrorHandler$lift$1.invoke(push.kt:1)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.appservices.push.PushKt.liftFromRustBuffer(push.kt:2)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.appservices.push.PushException$ErrorHandler.lift(push.kt:2)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.appservices.push.PushException$ErrorHandler.lift(push.kt:1)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.appservices.push.PushManager.subscribe(push.kt:17)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.components.feature.push.RustPushConnection.subscribe(Connection.kt:4)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.components.feature.push.AutoPushFeature$subscribe$3$2.invokeSuspend(AutoPushFeature.kt:4)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.components.feature.push.AutoPushFeature$subscribe$3$2.invoke(AutoPushFeature.kt:2)
11-11 12:50:20.701 22894 23012 W App     : 	at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:4)
```

**Comment by jdeluyck** [comment]
This is still an issue.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807379

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
