### ISSUE TITLE
Can fenix release package can be hosted at http://ftp.mozilla.org

### ISSUE THREAD

**Issue by qrqhuang** [mozilla-mobile/fenix#19168]
The previous firefox can be found at [http://ftp.mozilla.org/pub/mobile/releases/](http://ftp.mozilla.org/pub/mobile/releases/)

Can fenix release  package also hosted at this website? I always check the new version (pc & android) from there .

**Comment by cadeyrn** [comment]
What is wrong with https://github.com/mozilla-mobile/fenix/releases?

**Comment by kbrosnan** [comment]
This is mostly owned by the release engineering team. For now there are not any plans to place the build artifacts on archive.m.o (ftp.m.o).

**Comment by kbrosnan** [comment]
Looks like release engineering team is tracking putting builds on archive.m.o in bz-1614763
