### ISSUE TITLE
[Bug] Tab list impinged by dialogs with multiple tabs open

### ISSUE THREAD

**Issue by leadweedy** [mozilla-mobile/fenix#19166]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Open 7+ tabs in the latest ff nightly (or enough to scroll the tab list)
- scroll to the bottom of the tab list
- the close bottom on the last tab is partially covered by the "+" button
- close the last tab
- the next tab in the list will be completely covered up by the "undo" dialog, impeding interaction with it for a few seconds

### Expected behavior
- the user is able to interact with the tab list unimpeded

https://user-images.githubusercontent.com/72583854/115592878-a7d5f100-a288-11eb-9782-12b0771c023f.mp4

### Actual behavior
- the close bottom on the last tab is partially covered by the "+" button
- closing the last tab in the list will completely cover the next tab with the "undo" dialog, impeding interaction with it for a few seconds

https://user-images.githubusercontent.com/72583854/115593017-d358db80-a288-11eb-9fc4-43b298d023ec.mp4

### Device information
LG G7
- Android 10

Firefox Nightly
- Nightly 210420 17:00 (Build #2015805771)
- AC: 75.0.20210419143149, 1cf914036
- GV: 89.0a1-20210418092832
- AS: 74.0.1

**Comment by jonalmeida** [comment]
Thanks for filing, the videos are super helpful! 🙂

**Comment by jonalmeida** [comment]
For when we fix this: since we're removed the 'Select tabs' button for now, we need to add some more margin from the bottom to make up for it.

**Comment by violasong** [comment]
I've found myself running into this a lot when trying to closing a bunch of tabs at a time (the undo message now covers up the last tab, including its close button).

I'm curious if we could move the undo message to this space below the tabs. CC @topotropic 

<img width="377" alt="image" src="https://user-images.githubusercontent.com/55994/118550694-d7560d00-b711-11eb-8e7f-6b3b1a5d20d2.png">

**Comment by fm-sys** [comment]
> I've found myself running into this a lot when trying to closing a bunch of tabs at a time.
> 
> I'm curious if we could move the undo message to this space below the tabs. CC @topotropic
> 
> <img alt="image" width="377" src="https://user-images.githubusercontent.com/55994/118550694-d7560d00-b711-11eb-8e7f-6b3b1a5d20d2.png">

Never have seen an app using a half width Snackbar. 

However, I saw the material guidelines, that require it as it is currently implemented

![grafik](https://user-images.githubusercontent.com/64581222/121016955-0ace0980-c79d-11eb-9e19-6ee9774b624f.png)

But even Google doesn't follow they're own guidelines.


https://user-images.githubusercontent.com/64581222/121030136-7f0eaa00-c7a9-11eb-9e7f-4c70367383ef.mp4

So I think we could place the snackbar at the bottom and move the FAB up so that it is placed exactly between two tabs so both "x" buttons and the FAB remain usable while the snackbar is displayed.

**Comment by fm-sys** [comment]
So we could either hide the FAB while the snackbar is displayed or move it up above the snackbar. I would vote for the second variant.

**Comment by topotropic** [comment]
Thanks for filing!

I believe this issue is fixed, since we added some margin to the bottom of the tab list:

> the close bottom on the last tab is partially covered by the "+" button

As for the other one (Snackbar covers up tab) – we indeed follow material design guidelines here. We could try to keep the same margin that we added to fix the above issue to the last tab so that people can scroll the background and close the tab.

**Comment by drathier** [comment]
How did this bug reach production? Feels like a post mortem is due.

**Comment by mcarare** [comment]
@leadweedy Can you confirm this is not an issue anymore? Thank you!

**Comment by dcharles** [comment]
> @leadweedy Can you confirm this is not an issue anymore? Thank you!

Not sure about the latest Nightly, but the latest version in the Google Play app store (89.1.1, released May 27, 2021) still has this issue.

If there's a fix in Nightly, when will it be deployed to the app store?

**Comment by gitt0r** [comment]
91.0a1 is also still affected.

Is there a possibility to turn this off
in "about:config"?
I've never really used this feature anyway.

Why not have it as an option in the tab list 
called "Reopen last closed tab" (additionally)?


https://user-images.githubusercontent.com/65116394/124269929-d0595180-db3b-11eb-8281-a6eaffef6d20.mp4

**Comment by dcharles** [comment]
> Is there a possibility to turn this off
> in "about:config"?
> I've never really used this feature anyway.
> 
> Why not have it as an option in the tab list
> called "Reopen last closed tab" (additionally)?

My opinion, as a user (and a non-Firefox developer):

I do use the feature and find it useful.

Before a month or two ago, this bug was not an issue. The popup is in the same place it's always been. So the popup itself doesn't need to be resized or moved. When the issue began occuring, it was because the list of tabs was extended further down. Basically, the video in the original writeup was what it used to look like. So, the fix should probably be to just shift the "bottom point" of the list of tabs back up again.

**Comment by TechnoSwiss** [comment]
This was less of an issue when the tab list was top to bottom, the chabge for new tabs to be added at the bottom has made this bug super annoying. As a user I do sometimes use the Undo button so I would like to see it stick around in some way, but related when you click undo the undone tab gets added at the top of the list (I need to check and see if there's already a bug files for that)

**Comment by SeburoSUMO** [comment]
User feedback: 
https://support.mozilla.org/en-US/questions/1342420 
https://support.mozilla.org/en-US/questions/1341286
https://support.mozilla.org/en-US/questions/1339823

**Comment by waaronking** [comment]
This bug is still present in the nightly build v92.0a1

As a side note (and per @TechnoSwiss's comment) this bug is especially egregious due to changes made from https://github.com/mozilla-mobile/fenix/issues/11376
Although this doesn't "fix" the problem per se, issue https://github.com/mozilla-mobile/fenix/issues/16884 would make the changes of 11376 customizable and would be a small reprieve for those sorting from top-to-bottom

**Comment by MissTcat** [comment]
I cannot believe that a bug that affects daily quality of browsing is not fixed yet.

**Comment by Electw** [comment]
Would it be easier to bring back the "Select tabs" button that was present in v88 and earlier? It sort of acted like a margin for the dialog.

**Comment by topotropic** [comment]
@jonalmeida would it be possible to add some padding to the bottom of the tab tray list so that people can scroll the view to access close/open options while the snackbar is visible?

**Comment by ubalklen** [comment]
I've just found out it's possible to swipe away the dialog. It's a better workaround than waiting for the dialog to move.

**Comment by maxstarkenburg** [comment]
I read about the swipe-to-dismiss workaround somewhere else before, but couldn't make it work (if anything I undid tab closings). Tried again today after @ubalklen's post. Seems the trick is to swipe right. I'm not seeing it dismissed if swiping in any other direction.

**Comment by iamshilov** [comment]
It's been several months and this annoying bug still exists. Incredible. Talk about Firefox losing 47 million users…

**Comment by Taknok** [comment]
Another workaround is by swiping (on right or left) the tab directly.

https://user-images.githubusercontent.com/12498020/129219983-b8b55619-cb65-4cab-b796-61570b7dc19a.mp4

**Comment by aahlborg** [comment]
Yesterday's update of the default tab view makes this less of an issue. Some people will however want to switch to the old view.
![_20210813_081824](https://user-images.githubusercontent.com/557695/129314050-9f0dae01-bbfa-4b7c-a00e-e1cd86209b99.JPG)

**Comment by codrut-topliceanu** [comment]
Adding a bottom padding of about `190dp` would add sufficient space to the bottom of the tabsList to prevent the snackbar and fab from covering the last tab. Note that this extra padding will not do anything if the user is not scrolled down all the way, but this is the same behavior Gmail has.

_Padding added to NormalBrowserTrayList, list scrolled down all the way_
<img src="https://user-images.githubusercontent.com/60002907/131485522-44e0f162-f87b-435e-933c-482be922df7a.png" width="300" />

_List scrolled down all the way, no snackbar_
<img src="https://user-images.githubusercontent.com/60002907/131485722-7916822e-c600-4546-b921-a4f1f06545e6.png" width="300" />

_Middle of the list, not affected by bottom margin_
<img src="https://user-images.githubusercontent.com/60002907/131485848-e1c417b9-8424-48ef-9d97-925533eb0ba8.png" width="300" />

_Middle of the list + snackbar, not affected by bottom margin_
<img src="https://user-images.githubusercontent.com/60002907/131486200-dbfd7940-7c51-4a91-93b8-1ce5eb510967.png" width="300" />

_Gridview_
<img src="https://user-images.githubusercontent.com/60002907/131487042-1fc5be4e-5a8a-451e-8a32-5f7390278121.png" width="300" />

_Gmail for reference, scrolled down all the way_
<img src="https://user-images.githubusercontent.com/60002907/131486126-4f1d757f-5d8e-4ac1-a79b-67c0c24dc67a.png" width="300" />

I will implement this change in accordance with [this comment from UX.](https://github.com/mozilla-mobile/fenix/issues/19166#issuecomment-892533298)

**Comment by Taknok** [comment]
I was looking to change the snackbar width (to be aligned with FAB in list mode). And I changed the behavior of the FAB when list mode is set to disable depends on snackbar.

In list mode:
- disable depend on snackbar for FAB
- reduce max width of snackbar to parent - (minus) FAB width

Personal stuff came in, so I stopped my dev. This solution will be still appreciated or not ?

**Comment by codrut-topliceanu** [comment]
@Taknok Ultimately that decision is up to the UX team but there might not be enough room to fit the snackbar and Fab on the same "row", especially with some more verbose languages like German:

![image](https://user-images.githubusercontent.com/60002907/131621440-4584c915-a304-411e-8552-f50a63dca2ee.png)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/3 with LG G7 Fit (Android 8.1).
