### ISSUE TITLE
[Bug] Spelling mistake on Google play description 

### ISSUE THREAD

**Issue by PycraftDeveloper** [mozilla-mobile/fenix#19172]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by cadeyrn** [comment]
@PycraftDeveloper And why don't you tell them what the spelling mistake is? 🤔

**Comment by PycraftDeveloper** [comment]
Hehehe, sorry... OK so they miss-spelled "nightly" to "nightly" at the top of the Google play description. See attached image.
![Screenshot_20210422-075604_Google Play Store](https://user-images.githubusercontent.com/81379254/115669609-5c7f1980-a340-11eb-95dd-82cfbab4d260.jpg)

**Comment by kbrosnan** [comment]
I've reached out to our release team to correct this. If it goes a few days please reach out to [#release-drivers](https://chat.mozilla.org/#/room/#release-drivers:mozilla.org). This is not something that is a code problem in Fenix closing.
