### ISSUE TITLE
Closing a tab from select mode does not leave the mode when closing a tab

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19176]
### Steps to reproduce
1. Have a few tabs open.
2. Long press a tab to enter select mode.
3. Click the tabs tray's three-dot menu.
4. Press close.

### Expected
1. The tab is closed and no longer in the tray.
2. The tray is no longer in select mode.

## Actual
1. The tab is closed and no longer in the tray.
2. The tray is **STILL** in select mode.

https://user-images.githubusercontent.com/1370580/115640444-f618dd80-a2e4-11eb-9af9-fac87b6476bc.mp4

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Verified as fixed on the latest Nightly (90.0a1 - Monday 5/17 @ 5:05 AM) using a Motorola Nexus 6 with Android 7.1.1.
