### ISSUE TITLE
'Share Image' fails with Android Direct Share contacts

### ISSUE THREAD

**Issue by vityav** [mozilla-mobile/fenix#19171]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Attempt to share image via "Share Image" intent, using a direct contact rather than going through app contact list.
[Tested Image](https://upload.wikimedia.org/wikipedia/commons/a/a5/Caracal001.jpg)

### Expected behavior
Image is shared to the contact in the same manner as if going through the contact list

### Actual behavior
Tested with multiple jpg images on various apps with various failing results:
Textra: No response to direct share attempt
Signal: "Multiple attachments are supported only for images and video"
Hangouts: "Hangouts can't send this video for some reason. The video file might be corrupted", despite being jpg images.

All three work if I go through the app contact selection rather than direct share. 

This is mentioned in https://github.com/mozilla-mobile/fenix/issues/18547 which was closed, but the direct share bug persists so opening a specific report for this issue.

### Device information

* Device vendor / model and Android version: ?
Google Pixel 4a / Android 11, kernel 4.14.170

* Firefox for Android version: ? (go to Settings -> About Firefox)
Versions tested:
Stable: 88.1.1 
Beta: 88.0.0-beta.6 (not sure why the play store beta is behind stable)
Nightly: 210421 17:00

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10475)

**Comment by jonalmeida** [comment]
I can reproduce this failure with WhatsApp, Slack and Telegram direct sharing to a contact.

Android 11, Pixel 3
Firefox Nightly 210421

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811591

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
