### ISSUE TITLE
FNX-5333 ⁃ [Bug] Search suggestion don't turn off for shortcuts

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1917]
## Steps to reproduce
1. Go to Settings>Search. Turn off search suggestions.
1. Tap the search bar, select a different search engine from search shortcuts.
1. Type something in the search bar.
    1. Expected behavior
If search suggestions were turned off for the default search engine, they should be off for shortcuts too.
    1. Actual behavior
Search suggestions appear when using shortcuts.
    1. Device information

* Android device: Pixel (Android 9)
* Fenix version: 4/22

**Comment by kbrosnan** [comment]
Verified that when a user switches shortcuts search suggestions are disabled. Using a Pixel 3 and Galaxy S6

Found #2067 while verifying this.
