### ISSUE TITLE
Updates to Synced Tabs are not immediately reflected in tabs tray list

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19175]
There are multiple events to reproduce this bug, I'll try to list as many as I can find:

### Steps to reproduce
1. Open the tabs tray to Synced Tabs.
2. Follow the sign in flow.
3. Immediately open the tabs tray to Synced Tabs.

---

1. Open Settings and sign into Sync.
3. Immediately open the tabs tray to Synced Tabs.

---

1. Have multiple devices signed into Sync, including this one.
1. Open the tabs tray to Synced Tabs.
2. On another device, sign out from Sync.
3. On this device, click the 'Sync Now' button.

### Expected Results
 - The tabs tray list is updated when an update has taken place.

### Actual Results
 - You have to close and re-open the tabs tray to see an updated state.

**Comment by jonalmeida** [comment]
This is happening because our `SyncedTabsListener` is implemented outside the `SyncedTabsView` and so the internal controller isn't able to pass on the appropriate notifications the view on state updates.

**Comment by abodea** [comment]
Verified as fixed on Nightly 5/12 with OnePlus Nord (Android 11).
Note that I tried with all 3 scenarios from the description.

**Comment by jonalmeida** [comment]
These changes have been uplifted and should be available on the next beta.
