### ISSUE TITLE
Remove padding and add dividers to Synced Tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19178]
We should and match the designs by removing the padding besides each synced tab (we previously wanted in the old UI).

We should also add the divider (`ItemDecorator`) above each device title.

| Designs | Current |
|---------|---------|
| <img src="https://user-images.githubusercontent.com/1370580/115651848-06878300-a2fa-11eb-9312-ee700ba80b57.png" width=320 /> | <img src="https://user-images.githubusercontent.com/1370580/115659060-fc6c8100-a307-11eb-8965-bfe25839d7ea.png" width=320 /> |

Figma design link: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/MR1?node-id=467%3A59

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Nightly build from 6/9 with HTC 10 (Android 8), Samsung Galaxy Note 8 (Android 9):

![Untitled](https://user-images.githubusercontent.com/40694158/121348858-8b257380-c931-11eb-8937-94b503eba184.png)
