### ISSUE TITLE
[Bug] Audio keeps playing after closing PiP screen

### ISSUE THREAD

**Issue by yichiehc** [mozilla-mobile/fenix#19174]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. In Fenix, start playing a full-screen video on websites other than m.youtube.com.
2. Press Home Button to enter PiP mode.
3. Close the PiP screen.

### Expected behavior
The audio of the video should pause as well.

### Actual behavior
The audio of the video keeps playing in the background. Would need to turn it off manually.
Not sure if this behavior is set on purpose or not, but I feel like stop playing the audio when a user closes the pip screen is a more intuitive behavior.
Sorry for the bad recording... Please be patient with my old phone...
https://user-images.githubusercontent.com/48332564/115638346-d6190680-a344-11eb-807d-86f88bcee92d.mp4

### Device information
* Device vendor / model and Android version: Sony (Android 8.0.0)
* Firefox for Android version: Firefox Nightly 210421

**Comment by jonalmeida** [comment]
In `BaseBrowserFragment.onPictureInPictureModeChanged`, we probably want to notify our media controller to stop playing media for the selected tab.

**Comment by sflorean** [comment]
I was able to reproduce this on cnn.com/videos with LG G7 Fit (Android 8.1) on latest Nightly build. Closing the browser solves the issue.

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01 albeit, there is a notification for controlling the audio.
