### ISSUE TITLE
[Telemetry] Auto-closing tabs

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#19179]
## Description & Product Manager / Data Scientist User Story
As a product manager, I'd like to know if users choose to auto-close tabs, in order to determine whether auto-closing tabs after a certain amount of inactivity and helping users with managing their open tabs, will provide a better user experience. 

## What questions will you answer with this data?
- What % of users choose to have the browser auto-close their tabs after a certain amount of time, and what is the breakdown of the options?

## Acceptance Criteria
- [x] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology. https://mozilla-hub.atlassian.net/browse/DO-539
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by mcarare** [comment]
DO ticket created: https://mozilla-hub.atlassian.net/browse/DO-539.
