### ISSUE TITLE
Determine cause of April 15-17 regression (89ms)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19173]
_Batch this work with https://github.com/mozilla-mobile/perf-frontend-issues/issues/196_

Between April 15-17 (it's pinpointed to the 16th on the P2), we see a regression on perftest VIEW. P2 (28ms):
![image](https://user-images.githubusercontent.com/759372/115628937-42005e00-a2b6-11eb-81f9-4f1c00dfab54.png)

G5 (89ms):
![image](https://user-images.githubusercontent.com/759372/115628980-55132e00-a2b6-11eb-80fb-dc7b68f2024b.png)

Let's find the cause! We should see if the regression appears in geckoview-example. If so, it'd be easy to bisect. If not, perhaps we shouldn't spend too much time on it.

**Comment by mcomella** [comment]
For GV, I see a possible regression on the P2 but no regression on the G5: this probably means the regression doesn't affect GeckoView.

On FNPRMS MAIN for G5, we also see a regression around the 16th of ~40ms:
![image](https://user-images.githubusercontent.com/759372/115629414-2f3a5900-a2b7-11eb-95db-1b36c9611816.png)

MarcLeclair suggested this could be related to a Tabs tray change where we read from the SharedPrefs.

**Comment by jonalmeida** [comment]
> MarcLeclair suggested this could be related to a Tabs tray change where we read from the SharedPrefs.

Yes! Even though the tabs tray is not opened yet, this could be because we're doing various checks in other parts of the UI to see if we should show the new or the old UI. We could do a quick test with this by removing the FeatureFlag and settings  in nightly to see if that makes the bump go away.

Happy to put up a PR for this. 🙂

**Comment by mcomella** [comment]
I tried again this morning & double-checked the builds were correct: I was unable to reproduce. Using the latest nightly builds from 4/10 & 4/19:
- `cold_main_first_frame` was basically the same
- `cold_view_nav_start` saw an improvement of 157ms to the median (my previous run also saw an improvement but not so large)

I took one replicate of cold main fully drawn and also saw an improvement (though it's one run so potentially noisy).

Some theories why we can't reproduce:
- perftest triggers this from it's bimodal behavior bug BZ-1713238 but not a real regression. If it was real, I believe we should have seen it in `cold_view_nav_start`. This bimodal theory is backed up by my previous comment, "For GV, I see a possible regression on the P2 but no regression on the G5: this probably means the regression doesn't affect GeckoView."
- FNPRMS is kind of unreliable. It's possible the one device we could see the regression on was acting differently than the other devices (e.g. it had a longer uptime or something)
- It doesn't sound like it's the case from jonalmeida's comment but perhaps this was behind an experiments flag that changed at runtime (i.e. from Nimbus) but that flag is no longer present

I think we should close this rather than spending more time on it – I'll check with folks in stand up.

**Comment by mcomella** [comment]
As another data point, I took measurements from today's build (06/07) to 4/10: 
- `cold_main_first_frame` saw a regression of 41ms. That's probably https://github.com/mozilla-mobile/fenix/issues/19395#issuecomment-853448383 so that's further evidence there was no real regression here
- `cold_view_nav_start` saw an improvement of 156ms (oh, nice! not sure where that came from :o)

So I think again, it's probably not worth spending more time finding this regression.

**Comment by mcomella** [comment]
MarcLeclair agreed that this isn't worth digging into: let's close this.
