### ISSUE TITLE
[Bug] Visual issues with Synced Tabs - Private browsing

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19184]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Set the device to Light theme. 
2. Log in with a Firefox account on 2 devices.
3. Open Private Browsing - 3dotmenu.
4. Tap on "Synced tabs".

### Expected behavior
No visual issues are displayed and the content is readable.

### Actual behavior
The content is not readable.

### Device information
* Device vendor / model and Android version: Huawei MediaPad M2	(Android 5.1.1), Pixel 4 XL (11), OnePlus A3 (Android 6.0.1).
* Firefox for Android version: 89.0.0-beta.1, Nightly 4/22
 
![Screenshot_2021-04-22-10-40-45](https://user-images.githubusercontent.com/58466444/115699445-543dd300-a36e-11eb-83b1-e045db00645b.png)

**Comment by jonalmeida** [comment]
Synced tabs should not be shown in the three-dot menu. Probably a duplicate of https://github.com/mozilla-mobile/fenix/issues/19005 which doesn't seem to have made it in the beta release.

**Comment by jonalmeida** [comment]
With #19005 now fixed, could we get this re-tested?

**Comment by sflorean** [comment]
@jonalmeida this issue is no longer reproducible with #19005 fixed, but remains an issue for 89.0.0-beta.1.

**Comment by sflorean** [comment]
Yes, the issue is no longer reproducible on latest beta versions.
