### ISSUE TITLE
[Bug] appstore firefox has nit diff

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#19185]
The stable version of firefox as no diff anymore (or link showing where to look at least)
![Screenshot_20210422-125719](https://user-images.githubusercontent.com/56130419/115703651-aa107c00-a36a-11eb-904a-04affa5fa10d.png)

On android 11

**Comment by SoftVision-LorandJanos** [comment]
Hi @Octoton  ! Thank you for your report! Could you please help us with some information about the device and the firefox version you're using, and the steps needed to reproduce the issue you reported? Thank you!

**Comment by Octoton** [comment]
I use an pixel 4a, on android 11
The problem is in the google store not in firefox

**Comment by Octoton** [comment]
Tbe step: wait for a firefox update, go to the update and look at the diff, see none

**Comment by kbrosnan** [comment]
The release notes are updated on our website. https://www.mozilla.org/en-US/firefox/android/88.0/releasenotes/
