### ISSUE TITLE
[Bug] The webcompat.com page opens blank when tapping the "Report site issue"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#19181]
## Steps to reproduce
1. Open a website.
2. From the three-dot menu, tap on "Report site issue".
3. The webcompat.com/issues/new page opens in a new tab.

### Expected behavior
The page loads without issues in a new tab.

### Actual behavior
The webcompat.com page opens in a new tab but is blank.
Also, disabling the ETP toggle, enables it automatically, only while the page is blank - please see the short video below.

### Device information
* Devices: Samsung Galaxy Note 8 (Android 9), Xiaomi Mi 8 Lite (Android 9), OnePlus A3 (Android 6.0.1).
* Firefox for Android version: Beta 89.0.0-beta.1
* Opening the webcompat.com/issues/new page manually, loads the page without issues. And when ETP is disabled, it remains disabled.
 
https://user-images.githubusercontent.com/40694158/115670515-2ba7e000-a352-11eb-8f39-e43ee50208e7.mp4

**Comment by yichiehc** [comment]
Is this still a valid issue? Works fine on my device.

<img src="https://user-images.githubusercontent.com/48332564/116442665-58de1c00-a885-11eb-844d-181def0ca535.png" width="250">

Device: Sony (Android 8.0.0)
Firefox version: Firefox Nightly 210421

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue anymore with Samsung Galaxy Note 8 (Android 9), nor with Xiaomi Mi 8 Lite (Android 9).
Tested on both beta 89.0.0-beta.3, and 4/29 Nightly.
