### ISSUE TITLE
[Bug] History not shared between TWA and the browser

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#19189]
## Steps to reproduce
1. Make sure Firefox is the default browser.
2. Install "Myntra" TWA from PlayStore, or any other TWA (bookinglokal, quintoandar).
3. Open the TWA, browse a few pages inside it, add a product in the shopping bag.
4. Go to Firefox - History and observe.

### Expected behavior
The TWA history is visible in Firefox's history.

### Actual behavior
No history is created in the browser from the TWA.
If the default browser is switched to a different browser, and some data is created on the installed TWAs, when clearing the data, this dialog is NOT displayed "This app also had data in Chrome, would you like to clear this too?".

### Device information
* Devices: Samsung Galaxy Note 8 (Android 9), Huawei MediaPad M2 (Android 5.1.1)
* Firefox for Android version: Beta 89.0.0-beta.1, 4/21 Nightly
* Works on Xiaomi Mi 8 Lite (Android 9)

**Comment by jonalmeida** [comment]
I need to double-check this, but Firefox is not an approved/allowed client for TWAs installed from the Play Store.

**Comment by delia-pop** [comment]
This issue was reproduced again on 93.0.0-beta.1 (Build 2015832715) with Huawei P9 Lite (Android 8).
Visited pages in Myntra TWA do not appear in browser's history.

**Comment by jonalmeida** [comment]
> I need to double-check this, but Firefox is not an approved/allowed client for TWAs installed from the Play Store.

We are unable to support TWAs today.

Closing as "invalid".
