### ISSUE TITLE
Create button components for consistency

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#19196]
Consistency for text buttons: https://github.com/mozilla-mobile/fenix/issues/9857
Style guide meta: https://github.com/mozilla-mobile/fenix/issues/10991

Create common button components to be used throughout the app. 

Open questions/investigation needed: 
- Itemize buttons in the app
- Group buttons by category
- Create button templates (UX) and create components (AC)
- Integrate into button components into Fenix

**Comment by Meenohara** [comment]
How would Touch Delegate API help here?
