### ISSUE TITLE
Provide a way to remove individual autocomplete suggestions in the address bar

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1920]
### Why/User Benefit/User Problem
Sometimes users mistype addresses, and then they keep being suggested in place of the right address. Long pressing a history suggestion on the address bar on Chrome shows a pop-up asking if the user wants to delete it from the history. Fenix could do the same, or have such entries delete by swipe gestures

### What / Requirements
A way to delete history entries directly from the address bar suggestions

### Acceptance Criteria (how do I know when I’m done?
It's possible to delete history websites directly from the address bar suggestions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10495)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811653

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
