### ISSUE TITLE
Browser plugin request

### ISSUE THREAD

**Issue by rojinvgeorge** [mozilla-mobile/fenix#19206]
Hii sir
I have a request.to add manual extension adding feature for Mozilla Firefox android version...I am saying because I am working in kolotibablo and latest update of Firefox they removed manual add-on feature so we cannot work and it is a big problem happened for  kolotibablo android browser workers.if it is 
fixed it is very helpful for 1000 kolotibablo employees.so please take serious in this.
![Screenshot_2021-04-23-13-52-04-88](https://user-images.githubusercontent.com/70372327/115842384-66d20e00-a43b-11eb-905d-9e5dae8e8ace.jpg)

**Comment by rojinvgeorge** [comment]
Why no reply?

**Comment by kbrosnan** [comment]
if you want to use a wider set of extensions use [Firefox Nightly](https://github.com/mozilla-mobile/fenix/wiki#download). See https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/ for details about how this works.

**Comment by rojinvgeorge** [comment]
@kbrosnan I try to install extension in Mozilla Firefox nighty browser but no option to add and cannot add this website plugin(android)
