### ISSUE TITLE
Intermittent UI test failure - <HistoryTest.openHistoryInPrivateTabTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#19203]
### Stacktrace:
❗ The test timed out. The test ran longer than its maximum allowed duration, and was stopped.
Test failed to run to completion. Reason: 'Test run failed to complete. Expected 1 tests, received 0'. Check device logcat for details

**Comment by sv-ohorvath** [comment]
` StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/hardware/input/InputManager;->getInstance()Landroid/hardware/input/InputManager;
04-22 10:03:41.698: D/StrictMode(7872): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
04-22 10:03:41.698: D/StrictMode(7872): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
04-22 10:03:41.698: D/StrictMode(7872): 	at java.lang.Class.getDeclaredMethodInternal(Native Method)
04-22 10:03:41.698: D/StrictMode(7872): 	at java.lang.Class.getMethod(Class.java:2064)
04-22 10:03:41.698: D/StrictMode(7872): 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.InputManagerEventInjectionStrategy.initialize(InputManagerEventInjectionStrategy.java:8)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.BaseLayerModule.provideEventInjector(BaseLayerModule.java:16)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.provideEventInjector(BaseLayerModule_ProvideEventInjectorFactory.java:7)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.get(BaseLayerModule_ProvideEventInjectorFactory.java:5)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.get(BaseLayerModule_ProvideEventInjectorFactory.java:6)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.UiControllerImpl_Factory.get(UiControllerImpl_Factory.java:10)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.UiControllerImpl_Factory.get(UiControllerImpl_Factory.java:11)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.UiControllerModule_ProvideUiControllerFactory.get(UiControllerModule_ProvideUiControllerFactory.java:6)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.base.UiControllerModule_ProvideUiControllerFactory.get(UiControllerModule_ProvideUiControllerFactory.java:7)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.core.internal.deps.dagger.internal.DoubleCheck.get(DoubleCheck.java:13)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.DaggerBaseLayerComponent$ViewInteractionComponentImpl.viewInteraction(DaggerBaseLayerComponent.java:14)
04-22 10:03:41.698: D/StrictMode(7872): 	at androidx.test.espresso.Espresso.onView(Espresso.java:38)
04-22 10:03:41.698: D/StrictMode(7872): 	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.urlBar(NavigationToolbarRobot.kt:347)
04-22 10:03:41.698: D/StrictMode(7872): 	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:315)
04-22 10:03:41.698: D/StrictMode(7872): 	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:101)
04-22 10:03:41.698: D/StrictMode(7872): 	at org.mozilla.fenix.ui.HistoryTest.openHistoryInPrivateTabTest(HistoryTest.kt:281)`

**Comment by sv-ohorvath** [comment]
This hasn't failed in more than a month, I'll close it for now. Can be reopened if it happens again.
