### ISSUE TITLE
[Bug] The shield icon is always blue in tablet version.

### ISSUE THREAD

**Issue by kyoyacchi** [mozilla-mobile/fenix#19209]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to an website which makes enchanched tracking protection ON in a tablet device.
### Expected behavior
Must show half purple at right side in shield icon.
![FB_IMG_16191744961767257](https://user-images.githubusercontent.com/63583961/115861840-ff688e00-a43b-11eb-9e1a-25c452681f79.jpg)

### Actual behavior
No purple side just shows blue in shield icon.
![IMG_20210423_134456_350~2](https://user-images.githubusercontent.com/63583961/115861775-e2cc5600-a43b-11eb-951f-95fddbd54abb.JPG)

### Device information

* Device vendor / model and Android version: Casper VIA_S10 Android 6 
* Firefox for Android version:  88.1.1 (Build #2015804889)

**Comment by mcarare** [comment]
This is something not exactly working as expected but is a workaround for Android versions below 7 where `fillColor` does not accept a `gradient` in a vector drawable.
