### ISSUE TITLE
FNX-5335 ⁃ [Bug] Bookmarked pages open in a new tab when accessed from Library

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1921]
## Steps to reproduce
1. Bookmark a page.
1. Go to Library-Bookmarks and tap on the page from step 1.

### Expected behavior
The page from step 1 should open in the same tab.

### Actual behavior
The bookmarked page opens in a new tab, so now the user has 2 tabs opened with the same page.
Please see https://github.com/mozilla-mobile/fenix/issues/242#issuecomment-467160566

### Device information
* Android device: Google Pixel (Android 9), Samsung Galaxy Tab S3 (Android 8.0), Motorola Nexus 6 (Android 7.1.1)
* Fenix version: 1.0.1917 (Build#11121210)

**Comment by vesta0** [comment]
This is expected behaviour.

**Comment by sv-ohorvath** [comment]
@vesta0 On Fennec, when a bookmarked page is already opened in a tab, tapping the bookmark will open that tab and not a new one. That is also the behavior we expected from https://github.com/mozilla-mobile/fenix/issues/242#issuecomment-467160566

**Comment by vesta0** [comment]
For reference here is the final UX decision which aligns with this behaviour: https://github.com/mozilla-mobile/fenix/issues/1012#issuecomment-479608509

**Comment by sv-ohorvath** [comment]
> For reference here is the final UX decision which aligns with this behaviour: [#1012 (comment)](https://github.com/mozilla-mobile/fenix/issues/1012#issuecomment-479608509)

Thank you, we weren't aware of this one.
