### ISSUE TITLE
[Bug] Please restore ESNI until at least Cloudflare implements ECH

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#19218]
## Steps to reproduce

Open https://www.cloudflare.com/cdn-cgi/trace and see that the SNI is `plaintext`. This should be `encrypted`.

### Expected behavior

Websites that are hosted on servers implementing ESNI, such as Cloudflare, should work.

### Actual behavior

Some do not work, because of ISP blocking.

### Additional context

_Yes_, ECH is the way forward. Everyone knows that. But it has been half a year since ESNI was removed and ECH is clearly not ready. Instead of waiting for Cloudflare and others to deploy ECH at some point in the uncertain future (though seemingly _distant_ future, as the 10th ECH draft was published in March), why not restore ESNI functionality in Fenix so that users can access websites _now_? This would be the practical solution to the problem.

Backstory: https://bugzilla.mozilla.org/show_bug.cgi?id=1667801 This conversation was going somewhere positive, but some idiot decided to hurl abuses and the bug was locked. I hope to continue that discussion, and that you reconsider the premature removal of ESNI, given that no one is using ECH at the moment, and certain websites will stay ISP-blocked for the forseeable future.

**Comment by opusforlife2** [comment]
@Mugurell Sorry for pinging you directly, but no one has triaged this in a week while several newer issues have been triaged.

**Comment by opusforlife2** [comment]
Thanks for responding quickly!

The issue was marked as WONTFIX by @kershawchang immediately after the reporter opened it, and the entire discussion happened afterwards. Hence, I don't think that label is relevant here.

I'm aware of the shortcomings of ESNI compared to ECH and get why the change was made, but right now, practically speaking, I only have a choice between ESNI (where the ISP _might_ be able to tell which websites I'm visiting, depending on their capability) versus plaintext SNI, where the ISP can _definitely_ tell which websites I'm visiting, and can block them as well.

I'm asking for ESNI as a _stopgap_ measure only, hence the issue title - "until Cloudflare implements ECH". @kershawchang, would you please reconsider? (I forgot that you were the one who closed the bug, or I would have pinged you directly.)

**Comment by Mugurell** [comment]
@opusforlife2 You can open a new issue on Bugzilla and try to bring a good argument for ESNI there though I see other tickets asking for this are closed as duplicates of the wontfix issue.

**Comment by opusforlife2** [comment]
@Mugurell Thank you for the suggestion. But I would prefer to have at least some confirmation from Kershaw Chang or another team member about looking at this problem before I open a Bugzilla ticket,  because, as you said, there is a large possibility that my ticket will just be closed as a duplicate.

**Comment by KershawChang** [comment]
> I'm asking for ESNI as a _stopgap_ measure only, hence the issue title - "until Cloudflare implements ECH". @KershawChang, would you please reconsider? (I forgot that you were the one who closed the bug, or I would have pinged you directly.)

Sorry that I am not the one that made this decision. 
The most of the removed ESNI code is in NSS library, so I'd suggest to file a new bug in `NSS:Library` and see if they will consider to add ESNI code back. Thanks.

**Comment by opusforlife2** [comment]
Thank you. I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1709263.
