### ISSUE TITLE
[Bug] [L10n] "No internet connection" is not translated in some languages

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#19210]
### Preconditions
In Settings - Languages set the device to Polish.

## Steps to reproduce
1. Launch Fenix and go to three-dot menu.
2. Load a page without an internet connection and observe the error message.

### Expected behavior
The "No internet connection" error message is translated in the set language.

### Actual behavior
The "No internet connection" error message remains in english.

### Device information

* Device vendor / model and Android version: HTC Nexus 9 (Android 7.1.1)
* Firefox for Android version: Firefox 89.0.0-beta.1
 
### Notes
The same issue happens with Georgian language set.

**Comment by Delphine** [comment]
I see this as translated on Release. Please confirm this is still an issue, as I don't see it

**Comment by SoftVision-LorandJanos** [comment]
I recently retested on the latest Release (89.1.1 - Friday 5/28 @ 2:05 AM) and I cannot reproduce this issue anymore.
Tested using a Samsung Galaxy Tab 3 with Android 9.

**Comment by Delphine** [comment]
Ok closing then, thank you!
