### ISSUE TITLE
[Bug][L10n] Sync button from Tabs tray is not translated in some languages

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#19211]
## Steps to reproduce
1. Launch Fenix and set the language to Japanese/Hindi;
2. Tap the tab counter;
3. Tap the Sync tabs section from Tabs tray;
4. Observe the Sync button;
### Expected behavior
Sync button from Tabs tray is translated in Japanese/Hindi.
### Actual behavior
Sync button from Tabs tray is not translated in Japanese/Hindi.
![rsz_screenshot_20210423-152138](https://user-images.githubusercontent.com/48799384/115872429-77d64b80-a44a-11eb-8096-171aee0662cc.png)

### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9)
* Firefox for Android version:  Nightly 4/23 and Beta 89.0.0-beta.1

**Comment by Delphine** [comment]
I see this as translated both on Release and Nightly as of today. Are sure this is still an issue?

**Comment by LaurentiuApahideanSV** [comment]
I retested the issue on RC 89.1.1 and Beta 90.0.0-beta.2 and the issue still occurs but only when the language is set to Hindi.
Device used: OnePlus 6T (Android 9)
![19211](https://user-images.githubusercontent.com/50983519/121350545-7ea21a80-c933-11eb-9125-c61f282176d0.jpg)

**Comment by Delphine** [comment]
Thanks.
I've checked against [Pontoon](https://pontoon.mozilla.org/hi-IN/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=sync&string=223130) and [Transvision](https://transvision.mozfr.org/?recherche=sync&repo=android_l10n&sourcelocale=en-US&locale=hi-IN&search_type=strings). 
Hindi is not at 100%, and has not translated the string "sync" yet.
Closing for now. Thanks!
