### ISSUE TITLE
[Bug]Synced tabs (tabs tray) not displayed in RTL language when selected

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19213]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Log in with a Firefox account and make sure to have some synchronized tabs. 
2. Change the language to RTL.
3. Open Tabs tray - Synced tabs.

### Expected behavior
Synced tabs are displayed in RTL language.

### Actual behavior
The tabs are displayed in LTR language.

### Device information
* Device vendor / model and Android version: Pixel 3 (Android 11).
* Firefox for Android version: Nightly 4/23

**Comment by sflorean** [comment]
![Screenshot_20210423-172520](https://user-images.githubusercontent.com/58466444/115886116-4913a180-a459-11eb-9f41-28bac827690d.png)

**Comment by lobontiumira** [comment]
Verified as fixed on the 4/28 Nightly build with HTC 10 (Android 8):

<img src="https://user-images.githubusercontent.com/40694158/116399813-00316380-a832-11eb-868e-1d2b570cc474.png" width="300" height="550" />
