### ISSUE TITLE
Sticky elements at bottom of page have wrong click areas

### ISSUE THREAD

**Issue by ExileofAranei** [mozilla-mobile/fenix#19217]
## Steps to reproduce
Open this [sandbox](https://6vv7t.csb.app/). 

### Expected behavior
Click event should be triggered exactly by clicking element.

### Actual behavior
Scroll down a bit and after bottom browser bar hides click any button in sticky container at bottom of the page. Click areas are shifted to top by browser bar height. So red button click triggers by clicking at empty space a bit higher than element displays, same as blue button, that click triggers also at wrong area. With visible browser bar all works as expected.

### Device information

* Device vendor / model and Android version: OnePlus 3T, Android 9, OxygenOS 9.0.6
* Firefox for Android version: 88.1.1 (Build #2015804891)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10509)

**Comment by SoftVision-LorandJanos** [comment]
Hi @ExileofAranei ! Thank you for your report! This issue is reproducible on latest Nightly (210426 05:02 - GV90) and Release 88.1.1. Clicking the red button triggers the blue button and for the red button to be triggered, I have to click about a button height above. I've tested on the latest Chrome version as well, where it works as expected.
Device used: Motorola Nexus 6 with Android 7.1.1.

**Comment by VitalyVPinchuk** [comment]
Hi
Can I try to fix it?
@eliserichards

**Comment by VitalyVPinchuk** [comment]
Issue occurs in `EngineViewBrowserToolbarBehavior` class after `topToolbarChangedAction` or `bottomToolbarChangedAction` function type var gets executed.
`EngineView.setVerticalClipping()` somehow prevents `VerticalSwipeRefreshLayout` from translating Y coordinate.
If only `TranslationY` is used to animate the view then it works as expected but leaves empty space on the top/bottom of the screen.  Maybe, toolbar doesn't overlap underlaying view so we need to look into `GeckoView` library.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on latest Nightly (2021-11-08T05:11:41.935505).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by sudobash1** [comment]
Is there any way to work around this issue? I have a website which has a `sticky` button at the bottom of the screen which is suffering from this exact issue. It makes the site unusable in Firefox Mobile.

I tried making the button `fixed` instead, but that falls afoul of #16173.

**Comment by monochromer** [comment]
I have the same issue and found the effect of searchbar visibility on sticky elements:

https://user-images.githubusercontent.com/6412192/148597551-ba1165dd-d6f6-4bcf-9e77-03d05eaf95c6.mp4

Firefox 95, Android 9 (Xiaomi Redmi 6 Pro, MIUI 12.0.4)

[Demo Sandbox Link](https://jsfiddle.net/psgw3tyn/)

Initially, the sticky element is positioned correctly, but when scrolling, its real position is shifted upward by the size of the panel, while the visual position is correct. The video also shows the real click zone for calling the `alert` window.

**Comment by premyslposker** [comment]
Still experiencing same issue when page controls are sticky-bottom
- Firefox 103.2.0, Android 11 (Samsing A21s)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813213

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
