### ISSUE TITLE
FNX-5336 ⁃ [Bug] The page is not opened, when "Open in new tab" is selected from Bookmarks

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1922]
## Steps to reproduce
1. Bookmark a few pages.
1. Go to Library-Bookmarks, select a folder and tap the three-dot sub-menu from one of the bookmarked pages.

### Expected behavior
The page should be displayed.

### Actual behavior
The user doesn't know if the page is opened or not. If "Open in private tab" is selected, the background turns purple, but the page is not displayed.

### Note
#242 

### Device information
* Android device: Google Pixel (Android 9), Samsung Galaxy Tab S3 (Android 8.0), Motorola Nexus 6 (Android 7.1.1)
* Fenix version: 1.0.1917 (Build#11121210)

**Comment by kbrosnan** [comment]
Verified on a Pixel 3 and Galaxy S6.
