### ISSUE TITLE
Secure connection failed while using HTTPS filtering in AdGuard

### ISSUE THREAD

**Issue by mrclvitale** [mozilla-mobile/fenix#19220]
I've been using Firefox Beta on Android (current build 2015805811) for months with my current configuration, but this morning I started getting a secure connection failed message on any site I tried to visit and I duplicated the issue on my wife's phone running stable. I reinstalled my AdGuard certificate but that didn't help. So far I've only found two options to keep using these apps side by side and they both suck. One is to disable HTTPS filtering for Firefox in AdGuard, and the other is to toggle security.enterprise_roots.enabled to "true", but this resets every time I reboot the phone, plus this isn't even an option for my wife on stable.

**Comment by cadeyrn** [comment]
To quote https://github.com/mozilla-mobile/fenix/issues/18990#issuecomment-818894076

> This is a dupe of #3728 and fallout from [bz-1678191](https://bugzilla.mozilla.org/show_bug.cgi?id=1678191)
