### ISSUE TITLE
Firefox Android doesn't load images when links are opened in new tab

### ISSUE THREAD

**Issue by pykko87** [mozilla-mobile/fenix#19226]
I found a bug on Firefox for Android.

## Steps to reproduce: 
visit this webpage: https://www.imobiliare.ro/vanzare-apartamente/bucuresti-ilfov?id=82493726 and open in new tab one link for an apartment offer.

### Expected behavior:
 it should load the pictures for the apartment displayed, first on the page

### Actual behavior: 
it does not display the pictures, unless I manually reload the webpage

### Device information

* Device vendor / model and Android version: I use Samsung Galaxy S21 Ultra with Android 11
* Firefox for Android version: I use Firefox 88.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10518)

**Comment by pykko87** [comment]
In steps to reproduce, I meant: Open a link by long pressing the link and selecting "open link in new tab".

Just clicking it directly doesn't have the bug described.

**Comment by SoftVision-LorandJanos** [comment]
Hi @pykko87 ! Thank you for your report! I can reproduce this issue on latest Nightly (210426 05:02 - GV90) and Release 88.1.1.
On the latest version of Chrome it works as expected, the picture is loaded as the page loads for the first time.
Device used: Motorola Nexus 6 with Android 7.1.1.

**Comment by mcarare** [comment]
@pykko87 Do you have the same problem with any other websites that have a similar swipe slider? Thank you!

**Comment by pykko87** [comment]
@mcarare : I haven't noticed. Is this going to be fixed?
Should I report it elsewehere too?

**Comment by mcarare** [comment]
@pykko87 I am trying to see if this is a problem on our side or a webcompat problem, or even a logic issue within the page script. My initial findings while debugging this is that the swipe slider is loaded lazily and the loading should be done when the other elements in the page are loaded. But that does not happen in 4 out of 5 tests. So it could be a GeckoView problem or a webpage issue. The behavior on desktop Firefox is not relevant as the page loads differentlyy for mobile and desktop.

**Comment by Mikaka27** [comment]
Possibly related to these two: #17115 and #17009

**Comment by pykko87** [comment]
I tested both the stable and the nightly version, but the issue still persists. 😔

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly (2021-11-29).

**Comment by jackleson** [comment]
Can reproduce this issue and have had it for YEARS and can also say it is extremely annoying. The following was originally a bunk of ranting and complaining like three paragraphs worth but I decided before posting this was not useful. To be clear though, I open an image in a new tab using the long press (not sure if this is the right term) and it just doesn't fucking feel like it until I ask nicely I guess (refresh).

This is a genuinely important and kinda show stopping issue (browser literally does not display basic images wtf) so please unsick that dog/bot you call "stale" until this might actually be fixed.

I'm on a OnePlus 7t (hotdogb) HD1905 running LineageOS with microG (18.1-20220517-microG-hotdogb) with home app/launcher Lawnchair Version 10 Alpha 8 via Firefox for Android 102.1.1

**Comment by jackleson** [comment]
Actually I just noticed that if the image is very small (not sure specifically if dimensions, byte wise, or what) it will load fine. So this issue may have something to do with image size, memory, or something like that.

**Comment by jackleson** [comment]
I recorded something very interesting I have discovered on this issue. While it appears that images fails to load at all, it actually does just not properly. If you zoom in the image appears extremely small and beyond the zoom limit. This is the reliable and extremely odd behavior of this issue. This turns out to be some kind of zoom issue.

https://streamable.com/4512vf

**Comment by SoftVision-LorandJanos** [comment]
I wasn't able to reproduce the issue anymore, the image loads at first, the same way as in other browsers.
Tested with the latest Nightly 110.0a1 (2023-01-16) build.
Device used: Oppo Find X5 (Android 12).

**Comment by anon2828226** [comment]
please reopen this issue and learn to read. the issue isn't that clicking on images don't load or don't "load fast". its that using the "Open image in new tab" option (once you switch tabs to the image) loads the image (images has to be over 400x400 pixels^2 or so) zoomed way out such that a tiny dot of an image is all you can see a the very center of the screen. reloading almost always fixes this but not always (seems to be image specific whether reloading fixes).

**Comment by anon2828226** [comment]
Tried on nightly 111.0a1. still an issue.
see attached screen recording.

https://user-images.githubusercontent.com/43588692/214781090-91d89d05-ef90-432a-bcaf-299ef3181fad.mp4

**Comment by anon2828226** [comment]
?

**Comment by cpeterso** [comment]
We are now using Bugzilla for Fenix bug tracking. I will copy this bug report to Bugzilla so we don't lose it.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1815622

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
