### ISSUE TITLE
Use a date format that is clear to international users in  About Firefox

### ISSUE THREAD

**Issue by Y-Less** [mozilla-mobile/fenix#19221]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Go to "Settings" -> "About Firefox"

### Expected behavior

Show a date using my local language/region/culture.  I've checked that the correct language is set in the settings (it follows the global phone settings)

### Actual behavior

Shows a gibberish date from a month that doesn't even exist in England (I've just extrapolated the name of the month from the pattern of October, December, etc).

### Device information

* Device vendor / model and Android version: ? Samsung Galaxy S5 Neo, SM-G903F, Android 5.1.1
* Firefox for Android version: ? (go to Settings -> About Firefox) 88.1.1

**Comment by kbrosnan** [comment]
We do not want to use a localized date in this dialog. Too much chance of confusion in the single digit day/month case. If someone wanted to make it an ISO YYYY-MM-DD format we probably would take that change.
