### ISSUE TITLE
[Bug] Fingerprint blocking fails in stable build

### ISSUE THREAD

**Issue by shockergit** [mozilla-mobile/fenix#19225]
While i was checking the fingerprinting blocking of stable, beta and preview only beta and preview blocked fingerprinting after every session of firefox and stable version is not blocking fingerprinting.
https://browserleaks.com/canvas

**Comment by kbrosnan** [comment]
This is expected for release. You may want to use nightly where you can use a custom extension collection to install any extension though they might not work. See https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
