### ISSUE TITLE
NullPointerException: Parameter specified as non-null is null: method mozilla.components.feature.downloads.db.DownloadE...

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/fenix#19223]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11152131/?referrer=github_plugin

```
NullPointerException: Parameter specified as non-null is null: method mozilla.components.feature.downloads.db.DownloadEntity.<init>, parameter url
    at mozilla.components.feature.downloads.db.DownloadEntity.<init>
    at mozilla.components.feature.downloads.db.DownloadDao_Impl$10.call(DownloadDao_Impl.java:22)
    at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:2)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
...
(3 additional frame(s) were not displayed)

Parameter specified as non-null is null: method mozilla.components.feature.downloads.db.DownloadEntity.<init>, parameter url
```

**Comment by agi** [comment]
My nightly firefox crashes at startup with this signature, and it even seems to be crashing when trying to submit the crash report.

**Comment by pocmo** [comment]
I can only find one crash report and it only has one affected user 🤔 
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11152131/

**Comment by pocmo** [comment]
CC @Amejia481

**Comment by Amejia481** [comment]
It's pretty odd as indicates that we are trying to create a `DownloadEntity` with a null `url`, on start up we are bringing downloads from the db, I'm not sure how could we added a `DownloadEntity` with a null `url` in the database, it will be interesting to see the logs, @agi  did you remember the last file that you downloaded before the crash?

**Comment by agi** [comment]
The crash reporter crashes for me when trying to report the crash (I tried tens of times), here's the logcat from my phone.

[crash.txt](https://github.com/mozilla-mobile/fenix/files/6378247/crash.txt)
