### ISSUE TITLE
[Bug] Firefox 88 on Android 5 shows no website images or text, just graphics garbage

### ISSUE THREAD

**Issue by Sinsanga** [mozilla-mobile/fenix#19230]
Website display in Firefox 88 is completely broken, no text or images are displayed, just rectangles, dots and lines of various sizes and colors:
![Garbage](https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/images/2021-04-23-02-21-54-d6a5c9.png)

Several people have asked about this on support.mozilla.org:
- https://support.mozilla.org/en-US/questions/1333380
- https://support.mozilla.org/en-US/questions/1333413
- https://support.mozilla.org/en-US/questions/1333739
- https://support.mozilla.org/en-US/questions/1333752
- https://support.mozilla.org/en-US/questions/1333757
- https://support.mozilla.org/en-US/questions/1333848
- https://support.mozilla.org/en-US/questions/1333979

This is not related to any specific website or device, though most reports noted they are using Android 5. 

The issue appeared this week with the release of Firefox for Andoid 88.1.1.

Beta 88.0.0-beta.6, Klar 8.15.1 and Nightly display the same behaviour.

Downgrading to Firefox 86 solves the problem.

* Android 5 (most likely)
* Firefox for Android version 88

**Comment by Dunexus** [comment]
It looks like a webrender / graphic drivers bug.

What is your device ?
Can you check in `about:config` if `gfx.webrender.all` is enabled ?

If it is enabled, could you retry with this setting off.

**Comment by Sinsanga** [comment]
> What is your device ?

Acer T03, Huawai Y7, Huawei Y3 II and Galaxy Tab S2 have been mentioned so far, all running Android 5.0 or 5.1.

> Can you check in `about:config` if `gfx.webrender.all` is enabled ?
> If it is enabled, could you retry with this setting off.

about:config suffers from the same display problem as webpages, so it's not possible to check.

I did, however, install Firefox Beta 87.0.0-beta.6-2015798921, which has gfx.webrender.all disabled and works fine. Updating to version 88.1.1 probably enables it.
If it's possible to disable this setting in 88.1.1 without having to go through about:config, I'd give it another try.

**Comment by Dunexus** [comment]
Tagging @jamienicol from gfx team as he worked on several bugs of this kind.

**Comment by jamienicol** [comment]
Thanks for the heads up. Tracking this on the gecko side in https://bugzilla.mozilla.org/show_bug.cgi?id=1707283

Seems to be a driver issue affecting Mali devices running Android 5.

That seems to match the devices listed above, except perhaps the Huawei Y7 which appears to be Adreno...

**Comment by kbrosnan** [comment]
Closing upstream issue.

**Comment by waltdisneypixar** [comment]
same problem with android 5.1.1

**Comment by waltdisneypixar** [comment]
are they going to fix it?

**Comment by cadeyrn** [comment]
> are they going to fix it?

As you can see in the linked Bugzilla ticket it's already closed as fixed. It will be fixed in Firefox 88.1.2.

**Comment by waltdisneypixar** [comment]
nice. expected when? more or less 1 week 2?

**Comment by cadeyrn** [comment]
Firefox 88.1.2 has already been pusblished on the GitHub release page so the update via Google Play Store should arrive very soon.

**Comment by waltdisneypixar** [comment]
nice thank you team firefox
