### ISSUE TITLE
FNX-5337 ⁃ [Bug] The title of the screen of the current folder when browsing bookmarks is not displayed

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#1923]
## Steps to reproduce
1. Bookmark a few pages.
1. Save the bookmarked pages in a folder, i.e. "travel".
1. Open "travel" bookmark folder and observe the title of the screen.

### Expected behavior
The title should be renamed "travel". Please see https://github.com/mozilla-mobile/fenix/issues/242#issuecomment-480763002

### Actual behavior
The user is not aware that is in "travel" folder, because the screen has "Bookmarks" title.

### Device information
* Android device: Google Pixel (Android 9), Samsung Galaxy Tab S3 (Android 8.0), Motorola Nexus 6 (Android 7.1.1)
* Fenix version: 1.0.1917 (Build#11121210)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 4/24 build.
