### ISSUE TITLE
[Bug] MediaRecorder cannot record a stream source of html video element

### ISSUE THREAD

**Issue by huynhtanloc2612** [mozilla-mobile/fenix#19233]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Make below index.html file and put it in "htdocs" folder of localhost (apache server, port: 8080) or any way to create localhost on Android phone. In my case, I use Termux app and install apache server (pkg install apache2), put index.html file to "~/../usr/share/apache2/default-site/htdocs/", then run server (apachectl)
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <video id="video" width="1280" height="720" controls src="chrome.mp4"></video>
    <script>
      var video = document.getElementById("video");
      var isInitiated = false;
      video.onplay = function(){
        video.captureStream = video.captureStream || video.mozCaptureStream;
        var stream = video.captureStream();
        
        var recordedChunks = [];

        console.log("THIS IS STREAM: "+ stream);
        console.log(stream);

        // var options = { mimeType: "video/webm; codecs=vp9" };
        // mediaRecorder = new MediaRecorder(stream, options);
        mediaRecorder = new MediaRecorder(stream)

        mediaRecorder.ondataavailable = handleDataAvailable;
        mediaRecorder.start();
        
        function handleDataAvailable(event) {
          console.log("data-available");
          if (event.data.size > 0) {
            recordedChunks.push(event.data);
            console.log(recordedChunks);
            download();
          } else {
            console.log("Size = 0")
          }
        }
        function download() {
          var blob = new Blob(recordedChunks, {
            type: "video/webm"
          });
          var url = URL.createObjectURL(blob);
          var a = document.createElement("a");
          document.body.appendChild(a);
          a.style = "display: none";
          a.href = url;
          a.download = "test.webm";
          a.click();
          window.URL.revokeObjectURL(url);

          recordedChunks = [];
          // mediaRecorder = new MediaRecorder(stream)
          // mediaRecorder.ondataavailable = handleDataAvailable;
          mediaRecorder.start();
        }
        if (isInitiated == false){
          setInterval(event => {
            console.log("stopping");
            mediaRecorder.stop();
          }, 10000);
          isInitiated = true;
        }
      }
    </script>
  </body>
</html>
```
Replace "chrome.mp4" in video tag of index.html with any mp4 video on your Android phone and put the video file on "htdocs" folder as well
Access "http://localhost:8080" on Firefox for Android/Chrome on Android.

### Expected behavior
Media on the video player is recorded and download a video file every 10 seconds.

### Actual behavior
Media on the video player could not be recorded and one file is downloaded but could not be played
I think the issue in which MediaRecorder could not record a stream source of html video element (source: local mp4 video or url).
My test case: I tried to record and download video from the html video element by using video.mozCaptureStream() as my  index.html file. It worked correctly on Firefox/Chrome on PC and Chrome on Android devices..., but could not work in Firefox for Android. I think that issue is inside the MediaRecorder which cannot not recognized the stream from video.mozCaptureStream(). So that video was not recorded and downloaded. Please help take a look to this issue. Thanks.
### Device information

* Device vendor / model and Android version: 
Samsung S6 Edge Plus (Android 7)
Redmi Note 8 (Android 10)
* Firefox for Android version: ? (go to Settings -> About Firefox)
87.0.0-rc.1

**Comment by huynhtanloc2612** [comment]
Hi, I'd like to update my report with required content. (Last time when I reported this issue via my phone. I could not see the prompt as what I could see when using PC. So I'd like to update my report and hope to get response from anyone. Thanks.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1707958

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
