### ISSUE TITLE
[Bug] getUserMedia fails with NotAllowedError if microphone permissions are already given

### ISSUE THREAD

**Issue by seppevectera** [mozilla-mobile/fenix#19237]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

* Go to https://codepen.io/seppevectera/pen/mdRoebG
* Click "Start audio"
* In the Firefox notification: Choose "Remember this decision" and click "Allow".
* Click "Start audio + video"

### Expected behavior

Firefox asks for permission to start the microphone and camera

### Actual behavior

Firefox throws an error:

```
NotAllowedError: The request is not allowed by the user agent or the platform in the current context.
```

This only happens if permanent audio permissions have been granted, and you request both audio and video in the `getUserMedia` call.

### Device information

* Device vendor / model and Android version: OnePlus Nord N10, Android 10 (OxygenOS 10.5.11.BE89BA)
* Firefox for Android version: Tested in 88.1.1 and Nightly 210425 17:01 (Build #2015806731)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10526)

**Comment by SoftVision-LorandJanos** [comment]
Hi @seppevectera  ! Thank you for your report! I can reproduce this issue on latest Nightly (210426 05:02 - GV90), Nightly (210425 17:01) and Release (88.1.1). For reference, I checked on the latest version of Chrome, where it works as expected, both audio and video are successfully allowed.
Device used: Motorola Nexus 6 with Android 7.1.1.

**Comment by seppevectera** [comment]
This issue still occurs on 99.2.0 (Stable) and 101.0a1 (Nightly). It shouldn't be closed.

**Comment by seppe-lenders-tl** [comment]
This issue still occurs on 107.1.0 (Stable). It shouldn't be closed.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813892

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
