### ISSUE TITLE
[Bug] Crash on every startup

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#19232]
Firefox nightly suddenly started to crash at every restart (not right after last update yesterday, but for a couple of hours).

android.database.sqIite.SQLiteBIobTooBigException: Row too big to fit into CursorWindow
requiredPos=0, totalRows=75
at
android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native  Method)
at
android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
at
android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
at
android.database.sqIite.SQLiteQuery.fiIIWindow(SQLiteQuery.java:62)
at
android.database.sqIite.SQLiteCursor.fiIIWindow(SQLiteCursor.java:151)
at
android.database.sqIite.SQLiteCursor.getCount(SQLiteCursor.java:139)
at
mozilla.components.feature.downloads.db.DownloadDao_lmpl$10.call(DownloadDao_lmpl.java:10)
at
androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:2)
at
kotlin.coroutines.jvm.intemal.BaseContinuationlmpl.resumtWith(Continuationlmpl.kt:3)
at
kotlinx.coroutines.DispatchedTask. run(DispatchedTask.kt:15)
at
java. util. concurrent. ThreadPoolExecutor.runWorker
(ThreadPoolExecutor.java:1167)
at
java. util. concurrent. ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

### Device information
Redmi Note 7 with latest nightly build (210424 17:00). 
MIUI 11 Android 9

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/19223

**Comment by pocmo** [comment]
@kbrosnan The stacktrace looks different though! 🤔

**Comment by klint** [comment]
Thanks for reopening.
I must add some context, which may be important: the crash started not long after I installed an addon which is not yet validated, as far as I know. I cannot recall the name as my Firefox still crashes, but it was about taking a snapshot of a webpage. I played with it without a problem for a while, then Firefox started to crash.

**Comment by Amejia481** [comment]
@klint if it's not much trouble, could you share the logcat logs ? You can find instructions of how to get them [here](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information).

**Comment by Amejia481** [comment]
I'm no able to find any reports on sentry (on any Firefox variants). @klint did you remember the last file or `url` that you download?  If you had a Firefox account on nightly you can see your history on desktop.

**Comment by Amejia481** [comment]
We are only storing metadata about downloads when a file is downloaded into a room db, and we restore the metadata on startup:

The only that I can think that can grow that big it's the URL of a downloaded file:
https://github.com/mozilla-mobile/android-components/blob/feb080f1208d65767f492f8501a4648a9f488b86/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/db/DownloadEntity.kt#L16

**Comment by klint** [comment]
I'm sorry I don't have access to a computer where I could install the drivers to get the logacg logs..
What I remember is that the app was fine until I closed it and tried to reopen it, I think. That could fit with your scenario.
Just before that, I had generated and downloaded a screenshot from this site, using the screenshot add-on : https://wid.world/news-article/2020-regional-updates/

**Comment by klint** [comment]
The add-on is that one : https://addons.mozilla.org/en-US/firefox/addon/savescreenshot/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=collection

**Comment by Amejia481** [comment]
> We are only storing metadata about downloads when a file is downloaded into a room db, and we restore the metadata on startup:
> 
> The only that I can think that can grow that big it's the URL of a downloaded file:
> https://github.com/mozilla-mobile/android-components/blob/feb080f1208d65767f492f8501a4648a9f488b86/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/db/DownloadEntity.kt#L16

When I inspect the download table I found that the add-on provided us with a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), and this is what is causing the crash that you are experiencing, the string stored in the download table is to big for your device to handle it when we restore the metadata on startup. 

![image](https://user-images.githubusercontent.com/773158/116135767-7d789f00-a69f-11eb-956d-3b19f4567882.png)

**Comment by Amejia481** [comment]
I opened a bug that will prevent that from happening in the feature https://github.com/mozilla-mobile/android-components/issues/10157. Unfortunately you will have to clear your app data as a workaround to avoid the crash You can find some steps [here](https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android).

**Comment by klint** [comment]
Thank you for your help and analysis! At least, that will be a good reason to give up with collections for good in Fenix. I have lost all of them. Silly me, as I knew they were not synced in any manner. Why do they exist actually? But that is a another story, and another issue!
Cheers

**Comment by klint** [comment]
One last question though... instead of not storing data Urls, why not catch the error at startup rather than letting the app crash? 😊

**Comment by Amejia481** [comment]
> Thank you for your help and analysis! At least, that will be a good reason for me to give up with collections in Fenix for good. I have lost all of them. Silly me, as I knew they were not synced in any manner. Why do they exist actually? But that is a another story, and another issue!
> Cheers

The idea with collection is to give developers an opportunity to test their extensions on Fenix you can read more on this blog [post](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) :) 



> One last question though... instead of/in addition to not storing data Urls, why not catching the error at startup rather than letting the app crash? That would save my collections 😊


When we store a download metadata with data URLs into the db, we can't load it back to memory this is the [exception](https://github.com/mozilla-mobile/fenix/issues/19232#issue-867062582) that you are experiencing, even if we catch the exception we are not going to be able to show the download information in the download screen, as we can load it to memory.

**Comment by klint** [comment]
> The idea with collection is to give developers an opportunity to test their extensions on Fenix you can read more on this blog [post](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) :)

Sorry for the confusion, I was talking about the collections of sites that are displayed on the home page of Fenix. Add-on collections are quite useful indeed, but I don't see the point for the site collections as they are now (especially as they are not synced).

> When we store a download metadata with data URLs into the db, we can't load it back to memory this is the [exception](https://github.com/mozilla-mobile/fenix/issues/19232#issue-867062582) that you are experiencing, even if we catch the exception we are not going to be able to show the download information in the download screen, as we can load it to memory.

I was just hoping that by catching the error, I would be able to get my site collections back in a further nightly build (using Fenix beta in the meantime) ;).

**Comment by Amejia481** [comment]
Sorry for the confusion, I'm not that familiar with site collections but I know for sure that somebody on the team can help you to clarify on Matrix: https://chat.mozilla.org/#/room/#fenix:mozilla.org, that it's our public channel.

**Comment by Amejia481** [comment]
Some notes for QA to verify that the issue is fixed.

STR:

1. Download this [file]( https://mozilla.staktrace.com/bug/fenix-19279.html).
2. Kill nightly.
3. Open nightly and go to the download page.

The downloaded file should be visible in the download page without any crash.

**Comment by sflorean** [comment]
Followed the steps provided and didn't encounter any crash on Nightly 5/7.
