### ISSUE TITLE
Website rendering issue after updating on 88.1.1 version[Bug]

### ISSUE THREAD

**Issue by x4xvi** [mozilla-mobile/fenix#19249]
![Screenshot_2021-04-26-21-50-25](https://user-images.githubusercontent.com/23298027/116128670-3b208380-a6da-11eb-8a48-65ecf93bad33.png)
Just updated Firefox browser on Lenovo p70a (android 5.1) and got some weird website rendering issue. see attached pic. every web site looks like this. 
Things I have already tried:
1)removed every add-on
2)re-install
## Steps to reproduce
Have a Lenovo p70a and update Browser to 88.1.1 version. every site is broken.
### Expected behavior
uh? actual website rendering
### Actual behavior
every website is broken
### Device information
Lenovo p70a (android 5.1)  Firefox 88.1.1 
* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by kbrosnan** [comment]
This is tracked in bz-1707283
