### ISSUE TITLE
[Bug] Icon Vertical Center

### ISSUE THREAD

**Issue by gpodder770** [mozilla-mobile/fenix#19242]
I am learning web development
i created this page
https://dazzling-goldwasser-b57daf.netlify.app/
but for some reason icons are not vertically centered even though the line height is same as height

on desktop firefox when i check via crtl+alt+c and click the mobile sign 
on responsive icon is centered
can u plz tell me how to fix it for firefox mobile? 
I am using icons FontAwesome
Thanks for Help!!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10527)

**Comment by kbrosnan** [comment]
What icons? A screenshot would be helpful.

**Comment by gpodder770** [comment]
![Screenshot_20210426-205111_Firefox](https://user-images.githubusercontent.com/71787759/116103201-30152580-a6d1-11eb-8b11-e8d30d06bbcb.jpg)

Sry by mistake forgot to add the image

**Comment by abodea** [comment]
Thank you for this report @gpodder770! 
Note that I tried on the latest Nightly  4/29 but the icons look like are in the middle.
What device did you used? 
![Screenshot_20210429-154406](https://user-images.githubusercontent.com/42831109/116552861-2de5dd80-a902-11eb-95bb-93bbf0715f9a.jpg)

**Comment by gpodder770** [comment]
> Thank you for this report @gpodder770!
> Note that I tried on the latest Nightly 4/29 but the icons look like are in the middle.
> What device did you used?
> ![Screenshot_20210429-154406](https://user-images.githubusercontent.com/42831109/116552861-2de5dd80-a902-11eb-95bb-93bbf0715f9a.jpg)

Oww nice
I use samsung note 8 sm-950w

Wait i will check nightly too

**Comment by gpodder770** [comment]
Tried with nightly still not at center
Slightly down from center :(
![Screenshot_20210429-185328_Firefox Nightly](https://user-images.githubusercontent.com/71787759/116553691-35b27b80-a91c-11eb-8b00-c9bcdfb602b0.jpg)

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01

![251274001_932221387402825_1274131695909918111_n](https://user-images.githubusercontent.com/89511597/139671968-34c803d7-a01b-4dc5-9d80-d735feb4b93a.jpg)

**Comment by Bhooty** [comment]
Bump
