### ISSUE TITLE
[Bug] Local html files do not open

### ISSUE THREAD

**Issue by 1slivka** [mozilla-mobile/fenix#19247]
## Steps to reproduce
Open local .html or .htm files on Android device
### Expected behavior
Opening html file
### Actual behavior
HTML-page does not open, black background. Application have Storage Access!
### Device information
* Device vendor / model and Android version: Xiaomi Redmi Note 8T, Android 10 (LineageOS 17.1)
* Firefox for Android version: 85.x.x - 88.1.1

**Comment by kbrosnan** [comment]
Duplicate #4049
