### ISSUE TITLE
[Bug] The user cannot see the "Add" label aside from the "bookmark" option.

### ISSUE THREAD

**Issue by ilse-macias** [mozilla-mobile/fenix#19255]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open Firefox Beta 89
2. Open a new non-private tab.
3. Go to https://www.rnz.co.nz 
4. Tap on the three-dot (⋮) symbol on the toolbar (on the right in RTL locales)

### Expected behavior
The user must see the **Add** label with a star outline (☆) symbol and add the bookmark.

Reference from **Mobile Foxfooding test cases**:
https://lh5.googleusercontent.com/M9b58KsCT505pOp_dRXKDc2rHjSzSBur1AKzq0CCGiWE5UcCAWfyDN1x8pJ0Rp3CY2T-8gzdL0vX7tWjwRhoSRgxAkpDgBWLCmBti_HEemjCRDo2TacCO_lakAfRb0Cta0hAYn2K

### Actual behavior
 The user is not able to see the **Add** label is not visible; at the bottom of the toolbar menu, there is a star icon. It is the only way to add a bookmark.

### Device information
* Device vendor / model and Android version: ?
Device: **Google Pixel 3a** 
OS: **Android 11**

* Firefox for Android version: ? (go to Settings -> About Firefox)
 **Firefox 89.0.0-beta.1**

![image](https://user-images.githubusercontent.com/9839491/116154396-76e92800-a69d-11eb-8238-fb873a886b85.png)

**Comment by kbrosnan** [comment]
The updated menu is not on the beta you are testing. Use Firefox Nightly for now.
