### ISSUE TITLE
FNX-63 ⁃ Add Long Press Shortcuts to Fenix

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#1926]
### Why/User Benefit/User Problem
With the feature users can access other features quicker on Android 8.0+ devices. 

### What / Requirements
Shortcuts for commonly used features when long pressing the app icon on the device's home screen or app list.

### Acceptance Criteria (how do I know when I’m done?)
Long pressing the app icon show shortcuts for e.g opening a new tab, or a new private tab. 

Example:
![Screenshot](https://user-images.githubusercontent.com/32398857/56599594-41e8fd00-65cd-11e9-9b3e-0804a09aa1c3.jpg)UNITO-UNDERSCORE!20190423-133024!UNITO-UNDERSCORE!Samsung Experience Home!

**Comment by buttercookie42** [comment]
> With the feature users can access other features quicker on Android 8.0+ devices.

Since this isn't actually a strict OS-level features, older devices with certain third-party launchers would benefit, too.

**Comment by Scripterr** [comment]
This issue can be closed now that fenix support homescreen shortcuts for new and private tab from launcher's homescreen.
