### ISSUE TITLE
Search engine icon/thumbnail doesn't show up

### ISSUE THREAD

**Issue by verycoolperson** [mozilla-mobile/fenix#19265]
## Steps to reproduce
Go to Settings>Search>Add search engine>Other and add a search engine that isn't in Firefox by default (for example okeano.com or genius.com)
### Expected behavior
It's icon/thumbnail should show up the same way it does for Google, Duckduckgo ect.
### Actual behavior
Instead of it's icon it shows the first letter of the name you chose to give it ontop of a coloured backround
### Device information
* Samsung Galaxy A30s Android 10
* Firefox for Android version: 88.1.1

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-10542)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview 88.1.2 and Nightly 4/29. Might be related to https://github.com/mozilla-mobile/fenix/issues/18382.
### Devices used:
- OnePlus 6T (Android 9)
- Pixel 3 XL (Android 9)

**Comment by SamuelMezger** [comment]
Dear bot, please don't close. The issue still persists.

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01

**Comment by sheikh-azharuddin** [comment]
Same here...i added Brave Search engine but the thumbnail is not showing..please fix this

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1357535

**Comment by SamuelMezger** [comment]
Still relevant.

**Comment by SamuelMezger** [comment]
Still relevant.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807567

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
