### ISSUE TITLE
Custom private dns

### ISSUE THREAD

**Issue by gdnzz** [mozilla-mobile/fenix#19263]
### What is the user problem or growth opportunity you want to see solved?
Browser lacks custom private DNS option.

### How do you know that this problem exists today? Why is this important?
It is important since many it is a common privacy practice. Also, it is available on many mobile browsers and Firefox on PC.

### Who will benefit from it?
Users who want to use private DNS on their browsers without setting one from their phones' systems.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10540)

**Comment by ale82to** [comment]
in beta and nighlty is possible to set custom (private dns) in about:config

**Comment by GokdenizK** [comment]
OK then, let me make an addition: about:config should also be available on stable version, and custom private DNS should be located in gui, not in config settings.

**Comment by Cris--** [comment]
The problem is that Firefox for Android v95.2.0 didn't respect the Private DNS in Android network setting (here on A12 AOSP)!
Firefox loads ads on chefkoch.de where i know there are blocked by my Private DNS.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813642

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
