### ISSUE TITLE
Reading mode suggestions: text justification, pinch for text resize and spacing between lines

### ISSUE THREAD

**Issue by gdnzz** [mozilla-mobile/fenix#19264]
### What is the user problem or growth opportunity you want to see solved?
In reading mode, option to make text justified,  pinch to change text size, and spacing between lines.

### How do you know that this problem exists today? Why is this important?
Justified texts a are easier to read for many people. Also, pinch to change text size is useful feature when you want to change the text size easily while reading article.

### Who will benefit from it?
Everyday users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10541)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814136

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
