### ISSUE TITLE
String is Hardcoded

### ISSUE THREAD

**Issue by priyanka0906** [mozilla-mobile/fenix#19270]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
In xml file activity_privacy_content_display.xml 
"close" value of contentDescription is hardcoded.
### Actual behavior
string resource should be used.
### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by priyanka0906** [comment]
@eliserichards I would like to work on it.

**Comment by eliserichards** [comment]
Make sure the string you create includes a descriptive comment (follow the pattern of other strings) 👍

**Comment by priyanka0906** [comment]
> Make sure the string you create includes a descriptive comment (follow the pattern of other strings) 👍

@eliserichards okay, I will make sure that. Thank You.
