### ISSUE TITLE
Custom tabs text size isn't visible when Android display size is at max

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19271]
## Steps to reproduce
- Set Android text display size to the largest from your phone Setting
- Open Firefox as a custom tab

### Expected behaviour
- The title/url should be displayed properly. 

### Actual behaviour
- The title/url aren't fully visible displayed (see screenshot below).

---

there is such a problem here too. Same steps to reproduce

| | |
|--|--|
| ![IMG_20210421_095806](https://user-images.githubusercontent.com/53906414/115510418-60e7fb80-a288-11eb-8609-aabbfc711a72.jpg) | ![IMG_20210421_095826](https://user-images.githubusercontent.com/53906414/115510423-62192880-a288-11eb-97f3-5921c50f4644.jpg) |

_Originally posted by @testuser51 in https://github.com/mozilla-mobile/fenix/issues/18226#issuecomment-823828085_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10545)

**Comment by neha-b2001** [comment]
Hello, @jonalmeida, can I please work on this issue (along the same lines as issue #18226)?

**Comment by jonalmeida** [comment]
Yes, of course! I think you would need to look into the layout file for the toolbar code in Android Components [here](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml).

Note that we use the browser toolbar on multiple browsers (not just Fenix), so changes there will affect others.

**Comment by neha-b2001** [comment]
> Yes, of course! I think you would need to look into the layout file for the toolbar code in Android Components [here](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml).
> 
> Note that we use the browser toolbar on multiple browsers (not just Fenix), so changes there will affect others.

Okay 👍

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812841

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
