### ISSUE TITLE
[Bug] Download links with large inline blobs don't work

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#19279]
## Steps to reproduce

Go to https://mozilla.staktrace.com/bug/fenix-19279.html
Click on link

### Expected behavior

A 'picture.jpg' file is downloaded, as happens on desktop Firefox

### Actual behavior

Nothing happens

### Device information

* Device vendor / model and Android version: Sony Xperia XZ1C, Android 9
* Firefox for Android version: 88.1.1 (Build #2015804891)

**Comment by Amejia481** [comment]
On Firefox stable I was able to reproduce, but in [Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) and [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) is working as expected, are you able to reproduce there?

**Comment by kbrosnan** [comment]
I expect this is fixed by bz-1668952. I also see the same behavior as Arturo.

**Comment by staktrace** [comment]
Ok, thanks. I gave up on Nightly after getting stranded one too many times, but I'll wait until the fix rides into stable.
