### ISSUE TITLE
Missing Flag to Change security lock icon to green

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#19287]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
First of all thanks to add the icons from proton 
There is one preference setting in desktop version which when set to false changing security lock icon to green. . Please add the same in android version 

security.secure_connection_icon_color_gray

### How do you know that this problem exists today? Why is this important?
There must consistency in settings... We want green lock icon.. Moreover you people always speak/justifies we are aligning with desktop but this flag is not available.. 

### Who will benefit from it?
Users who prefers good security

**Comment by kbrosnan** [comment]
These sorts of UI `about:config` prefs are not a good fit for Fenix.
