### ISSUE TITLE
Overwriting mozac_error svg files

### ISSUE THREAD

**Issue by imnotabr** [mozilla-mobile/fenix#19280]
I want to overwrite the mozac_error svg files in the directory app>build>intermediates>merged_assets>debug>out

For example, "mozac_error_unplugged.svg".

Do you have to create directories in src/main/assets?

@clauub any ideas? Is it similar to how you overwrite the search suggestion xml files?

**Comment by hakkikaancaliskan** [comment]
Intermediate files are the cache and they're overwritten on build.
mozac icons are generally in Android Components. You should change corresponding svg with what you want and then build (you can find how-to in Fenix and AC Readme).
![Screenshot_20210428-094701_Firefox_Nightly.png](https://user-images.githubusercontent.com/17825767/116359071-05c58400-a807-11eb-8e32-2534cdce1e19.png)

**Comment by clauub** [comment]
@imnotabr I think you just have to add your **mozac_error_unplugged.svg** in the assets folder of your project and everything should work fine.

**Comment by kbrosnan** [comment]
There is not anything you to fix here you need to make your changes in https://github.com/mozilla-mobile/android-components and use a local copy of a-c for your build. 

For discussion style questions see https://github.com/mozilla-mobile/fenix/wiki#communication
