### ISSUE TITLE
[Bug] The main menu's icons & ETP icons have a different UI on Nightly

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#19282]
## Steps to reproduce
1. Install the 4/28 Nightly build from https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.latest.
2. Open a page and observe the main menu icons, the tracking protection icon, the tab counter icon.

### Expected behavior
The UI is not changed.

### Actual behavior
The UI is different - as seen in the short video below.

### Device information
* Devices: HTC 10 (Android 8), Samsung Galaxy Tab A6 (Android 5.1.1), Xiaomi Mi4i (Android 5.0.2), Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9)
* Firefox for Android version: 4/28 Nightly
 
https://user-images.githubusercontent.com/40694158/116366473-fea27400-a80e-11eb-94d4-a03ae88d9690.mp4

<img src="https://user-images.githubusercontent.com/40694158/116366497-05c98200-a80f-11eb-806a-c1fed1200926.jpg" width="300" height="550" />

**Comment by sheikh-azharuddin** [comment]
Expected behaviour... New icons sets imported from proton design.. Looks nice

**Comment by Amejia481** [comment]
> Expected behaviour... New icons sets imported from proton design.. Looks nice

Thanks for helping to clarify :)
 
Yeah, this is a result of the first bath of icons covered on https://github.com/mozilla-mobile/fenix/pull/19044 we are going to keep adding more icons.
