### ISSUE TITLE
[Bug] Keyboard covers text feild in PWA only

### ISSUE THREAD

**Issue by Hiimjay1** [mozilla-mobile/fenix#19283]
I am developing a Progressive web app and finding that The keypad in the Firefox browser is covering up the text boxes when the web app is downloaded using the firefox browser. It does not do this when using the application directly in the firefox browser or if I use another browser to download it such as Google.

**Comment by Hiimjay1** [comment]
https://user-images.githubusercontent.com/83339893/116385649-e7fd1c80-a810-11eb-81a0-2ef4551704a3.mp4

this is a video replica of what is taking place - thanks

**Comment by kbrosnan** [comment]
@makotokato is this a platform bug or something for the Fenix/Android Components team?

**Comment by Hiimjay1** [comment]
https://user-images.githubusercontent.com/83339893/116664844-e8bcbc80-a990-11eb-8f66-3f2083471ee4.mp4

Just to clarify it is also happening with internal pages in the PWA as demonstrated in this video. Thanks

**Comment by Hiimjay1** [comment]
![Screenshot 2021-04-30 at 08 53 48](https://user-images.githubusercontent.com/83339893/116668391-4b17bc00-a995-11eb-90db-3aa4708bffc7.png)

There is also 1 more query not sure if it can be addressed under this ticket but our users are also receiving this warning every time they try to access our site via firefox - now the website is 100% secure and has a valid SSL certificate.

**Comment by makotokato** [comment]
> @makotokato is this a platform bug or something for the Fenix/Android Components team?

If windows size isn't changed when showing software keyboard, it is a-c. Although I guess that this may be a-c, I don't know without reproduce step.
