### ISSUE TITLE
Display "undo close tab" when tab is closed via android back button

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#19285]
### What is the user problem or growth opportunity you want to see solved?
Currently "undo close tab" notification is only displayed when tab is closed from tab list, not when you close it with back button.
This could be useful to quickly restore closed tab when user clicks back button too many times.

### How do you know that this problem exists today? Why is this important?
This happens to me a lot if I interact with bloated website I hit back button, website doesn't react immediately I hit the back button again thinking I misclicked and the tab is closed. It would be good if I could immediately restore it.

### Who will benefit from it?
Users who use bloated websites.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10555)

**Comment by LaurentiuApahideanSV** [comment]
@Mikaka27 What exactly do you mean by tapping the back button? I tried to reproduce your issue by tapping the device back button several times but it just takes me back to the Firefox home screen and eventually minimizes Firefox, it does not close the tab I was in. Could you please specify the model and firmware of the device you are using and upload a short video showing the problem?
### Devices used:
- OnePlus 6T (Android 9)
- Pixel 3 XL (Android 9)

**Comment by Mikaka27** [comment]
Hi, try this.
1. Open some website with link
2. Hold the link and click "open in new tab"
3. Switch to this new tab
4. Click android back button

Result should be that this new tab is closed but you don't see "toast" about undoing it.

**Comment by Mikaka27** [comment]
Do you still require the video?

**Comment by LaurentiuApahideanSV** [comment]
@Mikaka27 No, I managed to reproduce the issue without it.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807132

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
