### ISSUE TITLE
[Bug]"Open in App" CFR - visual issues on tablets

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19288]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Make sure you have a clean profile.
2. Install Instagram app on your device.
3.  Open instagram.com on Fenix and observe if the CFR is displayed.

### Expected behavior
No visual issues are displayed when the CFR is available.

### Actual behavior
The CFR is only displayed on half of the screen.

### Device information
* Device vendor / model and Android version: Huawei MediaPad M2	(Android 5.1.1).
* Firefox for Android version: Beta 89.0.0-beta.3, Nightly 4/28.
 
![Screenshot_2021-04-28-14-26-02](https://user-images.githubusercontent.com/58466444/116415631-455d9180-a842-11eb-8056-a3c4058855ca.png)

**Comment by lobontiumira** [comment]
I was able to reproduce the issue on the latest RC 91.4.0, and on Beta 92.0.0-beta.8 builds, with Lenovo tablet M10 (Android 10).

![Screenshot_2021-08-31-17-44-19-102](https://user-images.githubusercontent.com/40694158/131526166-ddd68919-b164-426c-b185-5566f8b1153d.jpeg)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 99.0a1 (2022-02-28).
Tried with both Twitter and Instagram.
Devices used: 
- Oppo Reno 6 (Android 11).
- Samsung Galaxy Tab S3 (Android 9).
- Huawei MediaPad M2 (Android 5.1.1).
