### ISSUE TITLE
[Bug] Kasperky Did Not Install

### ISSUE THREAD

**Issue by tat-2whatever** [mozilla-mobile/fenix#19294]
I downloaded, Gdebi asked me to open file, and there is no app icon of the Kaspersky app.

### Device information: Chrome Pixelbook Linux Apps Beta

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)
 
![Screenshot 2021-04-28 11 25 37 AM](https://user-images.githubusercontent.com/78065163/116444248-2a772700-a81a-11eb-9a32-192a79db9b49.png)
![Screenshot 2021-04-25 8 20 00 PM](https://user-images.githubusercontent.com/78065163/116444285-34992580-a81a-11eb-837a-62fe27c82465.png)

**Comment by cadeyrn** [comment]
How is this related to Firefox for Android?

**Comment by kbrosnan** [comment]
Not a Firefox for Android issue.

**Comment by tat-2whatever** [comment]
It is a Chrome Pixelbook I am using. Google store sells new.
![Screenshot 2021-04-28 6 53 39 PM](https://user-images.githubusercontent.com/78065163/116486611-a9d51c80-a853-11eb-81ce-dacd0eb47006.png)

**Comment by tat-2whatever** [comment]
triage search in my packages; nothing there
![Screenshot 2021-04-28 7 01 10 PM](https://user-images.githubusercontent.com/78065163/116486899-4e575e80-a854-11eb-8175-414ece4b22db.png)

**Comment by cadeyrn** [comment]
And still it's not related to Firefox for Android.
