### ISSUE TITLE
not save settings in about:config

### ISSUE THREAD

**Issue by ZverPro** [mozilla-mobile/fenix#19297]
"For those who use Firefox beta, Nightly and Adguard installed. Firefox does not accept Adguard user or system certificate. Trying to force Firefox to accept the certificate. To do this, look for the security.enterprise_roots.enabled flag in about: config and switch it to true. After in Adguard - Application settings, enable https filtering for Firefox. "

About two weeks ago, this item in the about: config settings in the nightly version ceased to be saved, I thought a bug, they will fix it ... I went to beta ... Today, this bug was apparently transferred to beta. In the same way, the item flies in the settings. Not sure after restart or over time.

But using a browser with an adguard certificate and the like is now problematic, re-register each time.

I won't tell you about other settings in about, but most likely they are also not saved by analogy after restarting.

I checked it on two smartphones.

Does anyone know what can be done, is there the same problem?

**Comment by cadeyrn** [comment]
To quote https://github.com/mozilla-mobile/fenix/issues/18990#issuecomment-818894076

> This is a dupe of #3728 and fallout from [bz-1678191](https://bugzilla.mozilla.org/show_bug.cgi?id=1678191)

**Comment by kbrosnan** [comment]
Closing as a duplicate
