### ISSUE TITLE
[Bug] Failed to Obtain Authentication

### ISSUE THREAD

**Issue by tat-2whatever** [mozilla-mobile/fenix#19293]
I did packages update by clicking update. I did this 2 or 3 times. The notification says FAILED TO OBTAIN AUTHENTICATION. 

### Device information: Chrome Pixelbook Linux Apps Beta

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)
 
![Screenshot 2021-04-25 8 30 44 PM](https://user-images.githubusercontent.com/78065163/116443607-7bd2e680-a819-11eb-85f9-75431fa19aae.png)
![Screenshot 2021-04-28 11 39 02 AM](https://user-images.githubusercontent.com/78065163/116443632-82615e00-a819-11eb-94b6-4685358c2f68.png)
![Screenshot 2021-04-25 8 20 00 PM](https://user-images.githubusercontent.com/78065163/116443669-8db48980-a819-11eb-8ea9-b255f0bf7a38.png)

**Comment by kbrosnan** [comment]
Not a Firefox for Android issue
