### ISSUE TITLE
[Bug] Pull to refresh triggered on gallery swipe up

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#19299]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to the [link](https://www.zara.com/tr/tr/kontrast-%C3%A7i%CC%87zgi%CC%87li%CC%87-t-shirt-p00858098.html?v1=102552340&v2=1712675&utm_campaign=productShare&utm_medium=mobile_sharing_Android&utm_source=red_social_movil)
Swipe down to look other images
Then swipe up

### Expected behavior
Gallery should swipe up

### Actual behavior
Firefox is refreshing the website

https://user-images.githubusercontent.com/17825767/116464947-3fcd6f00-a875-11eb-95a2-4bf935466d11.mp4

### Device information

* Device vendor / model and Android version: XZ1 Android 11
* Firefox for Android version: 4/28 nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10566)

**Comment by SoftVision-LorandJanos** [comment]
Hi @hakkikaancaliskan ! Thank you for your report! I can also reproduce this issue. As a workaround it can be swiped gently to scroll back up, but this is not an expected behavior. I've tested on the latest Nightly (210429 05:01) GV90.0a1, using a HTC Nexus 9 with Android 7.1.1.

**Comment by hakkikaancaliskan** [comment]
Also when we swipe up/down on the gallery, bottom bar shouldn't move because we're not swiping webpage, just swiping gallery, this also causes visual glitches.

**Comment by mariansima** [comment]
This issue still occurs on Samsung Galaxy A8 (Android 9) with Firefox Nightly 95.0a1 2021-11-01 but only when using an account for the specified website

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 110.0a1 (2023-01-17).
The link provided in the description doesn't contain any pictures anymore, however, I've tried with a search with results, and when trying the scroll, the page behaved as expected, refresh was only activated at the top of the page.
Device used: Oppo Find X5 (Android 12).
