### ISSUE TITLE
Icon for "Report Site Issue..." has a different color in three-dot menu

### ISSUE THREAD

**Issue by yichiehc** [mozilla-mobile/fenix#19296]
## Steps to reproduce
Open the three-dot menu in any tab with the following combinations
- light mode, normal browsing mode
- light mode, private browsing mode
- dark mode, normal browsing mode
- dark mode, private browsing mode

### Expected behavior
Icons for all items should have the same color

### Actual behavior
The icon for "Report Site Issue..." has a different color from other items
- light mode, normal browsing mode - all dark (screenshot 1)
- light mode, private browsing mode - dark for "Report Site Issue..." & white for other icons (screenshot 2)
- dark mode, normal browsing mode - dark for "Report Site Issue..." & white for other icons (screenshot 3)
- dark mode, private browsing mode - dark for "Report Site Issue..." & white for other icons (screenshot 2)

Screenshot 1
<img src="https://user-images.githubusercontent.com/48332564/116449967-554e9300-a88d-11eb-9a2f-87113a81723c.png" width="250">

Screenshot 2
<img src="https://user-images.githubusercontent.com/48332564/116449504-d2c5d380-a88c-11eb-8466-651b70fba9fc.png" width="250">

Screenshot 3
<img src="https://user-images.githubusercontent.com/48332564/116450114-816a1400-a88d-11eb-9a1b-4b08b809bd47.png" width="250">

### Device information
* Device vendor / model and Android version: Pixel 3a (Android 11) & Sony (Android 8)
* Firefox for Android version: Firefox Nightly 210427

**Comment by sflorean** [comment]
Thank you for report! this issue is already tracked in #11367, please follow the discussion there. Closing as duplicate.
