### ISSUE TITLE
Turn off cookies on a per site basis

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#19302]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Be able to  disable cookies for a specific domain.

### How do you know that this problem exists today? Why is this important?
Desktop firefox has this, it would be great to have it on mobile as well

### Who will benefit from it?
Users who want more control over cookie storage

**Comment by abodea** [comment]
Thanks for this suggestion, for now, you can check the cookies and modify following this comment https://github.com/mozilla-mobile/fenix/issues/13812#issuecomment-700503934.
Also, when you access a website if you tap on ETP shield -> you have the Cookies section where you can disable per site or select other options available for cookies.
![Screenshot_20210429-121050](https://user-images.githubusercontent.com/42831109/116529042-2bc15600-a8e5-11eb-93ef-a0126c2913bf.jpg)
