### ISSUE TITLE
Error loading sqlite libraries

### ISSUE THREAD

**Issue by sppkarthick** [mozilla-mobile/fenix#19305]
I am trying to integrate firefox latest version 89 beta as a default browser for android 9 source. While launching the firefox browser, i am gettting below error. Is anybody help me out to resolve this issue?

04-29 04:55:48.579  3251  3284 E GeckoLibLoad: Load sqlite start
04-29 04:55:48.583  3251  3284 E GeckoLibLoad: Couldn't get a handle to libnss3!
04-29 04:55:48.583  3251  3284 E GeckoLibLoad: Throw
04-29 04:55:48.583  3251  3284 E GeckoLibLoad: Load sqlite done
04-29 04:55:48.587  3251  3284 E AndroidRuntime: FATAL EXCEPTION: Gecko
04-29 04:55:48.587  3251  3284 E AndroidRuntime: Process: org.mozilla.firefox_beta, PID: 3251
04-29 04:55:48.587  3251  3284 E AndroidRuntime: java.lang.Exception: Error loading sqlite libraries
04-29 04:55:48.587  3251  3284 E AndroidRuntime: 	at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibsNative(Native Method)
04-29 04:55:48.587  3251  3284 E AndroidRuntime: 	at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibs(GeckoLoader.java:5)
04-29 04:55:48.587  3251  3284 E AndroidRuntime: 	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:53)
04-29 04:55:48.587  3251  3284 E ExceptionHandler: Uncaught exception handled: 
04-29 04:55:48.587  3251  3284 E ExceptionHandler: java.lang.Exception: Error loading sqlite libraries
04-29 04:55:48.587  3251  3284 E ExceptionHandler: 	at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibsNative(Native Method)
04-29 04:55:48.587  3251  3284 E ExceptionHandler: 	at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibs(GeckoLoader.java:5)
04-29 04:55:48.587  3251  3284 E ExceptionHandler: 	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:53)
04-29 04:55:48.589  3251  3284 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(timestamp=1619686548588, throwable=java.lang.Exception: Error loading sqlite libraries, breadcrumbs=[], uuid=b08ef40c-b89a-4db0-8cd3-784e8db1d906)

**Comment by ralfaparins** [comment]
Experiencing same issue!
