### ISSUE TITLE
malware blocking not working

### ISSUE THREAD

**Issue by meongpice** [mozilla-mobile/fenix#19300]
![Screenshot_2021-04-29-06-39-43-36_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/81660474/116485642-eb96af00-a8b5-11eb-80d1-6e5e522e884b.jpg)

Masalah terhadap keamanan dalam browser masih dalam masalah 

Untuk situs web yang memasang Malware masih tidak dapat di cegah 

Walaupun sudah di setel ke tingkat keamanan 
tertinggi

Translated: 
The security issue in the browser is still a problem

For websites that install Malware it still cannot be prevented

Even though it has been set to the security level
the highest 

Visiting https://testsafebrowsing.appspot.com/
Should show a malware warning:

**Comment by kbrosnan** [comment]
Google does not provide malware URLs for their mobile safebrowsing lists. https://bugzilla.mozilla.org/show_bug.cgi?id=1688103#c3
