### ISSUE TITLE
[Bug]document.documentElement.clientHeight手机浏览器不能得到隐藏工具栏后的可视区域高度

### ISSUE THREAD

**Issue by ereere** [mozilla-mobile/fenix#19304]
[comment]:document.documentElement.clientHeight 在工具栏隐藏后没有得到真实的可视区域高度，隐藏后得到的数值没有变化。

### Device information：xiaomi mi 6

* Device vendor / model and Android version: Android 9
* Firefox for Android version: Nightly 210427 17:01(Build #2015807115) AC:90.0.20210426143115

**Comment by LaurentiuApahideanSV** [comment]
@ereere  Please open an issue in English, in order for us to be able to investigate. Thank you!
