### ISSUE TITLE
[Bug] Desktop site menu item is clipped

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19310]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/43795363/114916891-f6980c80-9dea-11eb-950b-26b26088b44b.png">  <img width="323" src="https://user-images.githubusercontent.com/43795363/114916514-7ffb0f00-9dea-11eb-84ac-38e3468091fa.png">

When we're signed in to sync, the menu is wide enough to see the whole "Desktop Site" string. But when we're signed out, "Desktop site" gets cut off. I think the minimum width should allow us to see that whole string (in En-US)

For more info and the fix - https://github.com/mozilla-mobile/android-components/issues/10133

**Comment by Mugurell** [comment]
This should be fixed in the latest Nightly - the "Desktop site" menu item shown on app's homescreen is not clipped anymore.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly 90.0a1 5/4`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Screenshot
![rsz_screenshot_20210504-102043](https://user-images.githubusercontent.com/51314259/116971995-12445380-acc3-11eb-9807-4362ce6b0799.png)
