### ISSUE TITLE
[webcontent] Cannot log in to twitter in a private tab

### ISSUE THREAD

**Issue by chutten** [mozilla-mobile/fenix#19318]
## Site with issue and any steps to reproduce

twitter.com in Private Browsing Mode

### Expected behavior

1. Log in to Twitter in a Private Tab

### Actual behavior

1. After logging in, you either
    - (if you don't use 2FA) Get a "Something went wrong [Retry]" UI
    - (if you use 2FA) After giving your authenticator code, you get booted back to the login flow

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

No. Though it's hard to say if it _would_ work because it doesn't maintain its settings in PBM and Twitter can't figure out which domain it wants to be.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
Does not reproduce in non-Private tabs on Fenix.

### Device information

* Android device: Samsung A5
* Fenix version: 90.0a1 2015807419

**Comment by chutten** [comment]
Oh, forgot to mention, it used to work reliably up until a couple weeks back. Sorry I didn't mention it sooner, but it sometimes very occasionally works and I thought at the time it was a dupe of "The ServiceWorker Issue" (which this does not appear to be. `about:serviceworkers` is blank)

**Comment by kbrosnan** [comment]
Can you reproduce in [Geckoview example](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt)? If so then [Mozregression ](https://mozilla.github.io/mozregression/)will work

**Comment by chutten** [comment]
I downloaded the gv_example artefact at the link you provided After installing it (going through all the warnings that were never there in the J2ME days), I was able to successfully reproduce the problem. That is to say, GV Example didn't let me log in to Twitter when I tried to do it in a Private tab.

**Comment by chutten** [comment]
With `mozregression --app gve`'s help I got the following pushlog with the STR being "Check 'Private Browsing'. Load twitter.com. Log in. Provide username and password. Presented with 'Something Went Wrong [Retry?]'": https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=e2241700c420dcd4f4420a7cc61a352e6abc1ed9&tochange=f9628f3c1fe087d98d4f3c2a2f1bb3bb8ed428e4

@kbrosnan Anything else I can help with?

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1709483

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
