### ISSUE TITLE
[Bug] black boxes when scrolling

### ISSUE THREAD

**Issue by justf0rfun** [mozilla-mobile/fenix#19319]
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open a website (e.g. github.com, the issue tends to appear more frequent or heaver on websites that seem to make heavy use of JS to update the site's content. On more static sites like Wikipedia the issue is not so heavy.)
2. Scroll around

### Expected behavior
The website should be rendered cleanly.
### Actual behavior
The website gets rendered but there are black or at least dark rectangles or (rectangular areas) spearing. Sometimes they are flickering a bit. Sometimes they stay when stopped scrolling. Sometimes they disappear on further scrolling. The rectangles tend to be more wide than high. 

When input text into a textarea like now as I type this text, I don't see the characters spearing and the cursor moving forward. When I fold the virtual keyboard away, the viewport gets updated and I see what I actually typed and were the cursor actually is. This may me a different issue but I think it is has the same root cause. Please tell me if this should become a sseparate issue.

To me this looks like a cissue of composition or so, b.

I can't promise but maybe I can provide pictures later.
### Device information

* Device vendor / model and Android version: ?
Meizu MX6
Android 6.0

* Firefox for Android version: ? (go to Settings -> About Firefox)
 
88.1.1 (Build #881120) (actually Fennec from F-Froid) 
AC: 74.0.11, e09d8a00b5
GV: 88.0-20210421130903
AS: 74.0.1

I think I upgraded from 86.x
The issue appeared after the upgrade.

Please tell me if I chose the correct type of issue (bug). Feel free to change the type if appropriate.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1708583

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Hi @justf0rfun , a screenshot or recording would be really helpful!

It's possible that this is a duplicate of a bug that we have just fixed a couple of days ago. Could you try going to about:config, setting `gfx.webrender.allow-partial-present-buffer-age` to `false`. Then restart the browser (by swiping it away in the app switcher). Then check whether the issue is still there? Thanks.

**Comment by justf0rfun** [comment]
Thanks for your help.

> Could you try going to about:config, setting `gfx.webrender.allow-partial-present-buffer-age` to `false`.

Yes, that helped. I don't see black boxes anymore.

![S10429-111631](https://user-images.githubusercontent.com/3073919/116685203-3f86be00-a9b2-11eb-8e72-edfb40e21d88.jpg)
![S10429-111704](https://user-images.githubusercontent.com/3073919/116685274-59280580-a9b2-11eb-8ac5-da87f8c5e3da.jpg)
![S10429-112154](https://user-images.githubusercontent.com/3073919/116685366-81afff80-a9b2-11eb-9873-defefe369b4e.jpg)


The behavior of typing in a text area without a black box is more difficult to show for me as it would need to capture the screen for a video. Fortunately it is also fine after changing the above setting.

I will let the setting be for now. What should I do on next update?

**Comment by jamienicol** [comment]
That's great. Just leave the setting for now, on the next update that will be the default value. Thanks for testing!
