### ISSUE TITLE
Add ability to sort Send Tab devices in share screen

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19317]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
- As a user, I have multiple devices as part of my Firefox Sync account. Sharing tabs from my mobile to desktop is a common task for me, and I have devices that are used more often than others.

### How do you know that this problem exists today? Why is this important?
- When I share to my devices, I have to scroll to the end of the list to select my device before I click the share button.
- In the screenshot below, my most common device is not visible in the list and I would like it always visible.

### Who will benefit from it?
- Users with multiple Firefox Sync devices.

<img width="320" alt="Screen Shot 2021-04-29 at 3 54 03 PM" src="https://user-images.githubusercontent.com/1370580/116610113-26730400-a903-11eb-80c4-5956bfe8e969.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10577)

**Comment by jonalmeida** [comment]
This could be solved by sorting the devices by recently used (more desirable), similar to the app section below, or by giving a user option to self sort.

**Comment by atjbramley** [comment]
Default behaviour seems to be that the devices in the synch list appear in the order in which they were added, with the most recent appearing first.  Therefore the only work-around at present is to un-synch the device that you want first in the list, then re-synch it, resetting its name in the process.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809786

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
