### ISSUE TITLE
[Bug] "XML Parsing Error: not root element found" on all websites

### ISSUE THREAD

**Issue by ByteHamster** [mozilla-mobile/fenix#19326]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

I updated Firefox Beta and "Android System WebView" yesterday. Since then, no website can be displayed. To reproduce, I just have to open any website.

### Expected behavior

It shows the website.

### Actual behavior

It shows the following error message:

> XML Parsing Error: no root element found
> Location: chrome://geckoview/content/geckoview.xhtml
> Line number 1, Column 1:
> 
> ^

<img width="100" src="https://user-images.githubusercontent.com/5811634/116656706-6a125000-a98d-11eb-8b92-d15c63da2c35.png" />

This means that I currently can't use Firefox as a browser because I only see the error message.

### Device information

* Device vendor / model and Android version: OnePlus 3T, LineageOS 17.1
* Firefox for Android version: 89.0.0-beta.3 (build `#2015807163`)

**Comment by ByteHamster** [comment]
I can no longer reproduce this in 89.0.0-beta.4

**Comment by rjcortese** [comment]
And now it seems the bug has been fixed once again 🎉
