### ISSUE TITLE
[Bug] Webrender broken in Firefox Browser for Android 88.1.2 (Stable)

### ISSUE THREAD

**Issue by fprietog** [mozilla-mobile/fenix#19323]
Webrender is broken in Firefox Browser for Android 88.1.2 (Stable). It also happens in current 89 Beta.

## Steps to reproduce
I suspect it may be not easy to reproduce because it should be device related. I'm using a Samsung Nexus 10 / Android Version 7.1.2 (32 bits) / GPU Mali T604. After upgrading Firefox Browser to 88.1.2 web pages are not displayed correctly because Webrender is totally broken.

It works if I force-disable Webrender, and in previous versions by default. I cannot assure if in previous Firefox versions were using OpenGL by default instead of Webrender and it works because of that (so maybe the problem is that now Webrender now is the default choice).

### Expected behavior
Visual example of rendering, web page https://www.mozilla.org/es-ES/

This is using Using OpenGL (forced) instead of Webrender:
![Screenshot_20210430-004817](https://user-images.githubusercontent.com/9756455/116628910-657b7680-a950-11eb-9515-935783e5a7b6.png)

### Actual behavior
This is the same web page using Webrender (the default):
![Screenshot_20210430-004558](https://user-images.githubusercontent.com/9756455/116628936-762bec80-a950-11eb-94ef-7eb338dd87e2.png)

### Workaround
Force using OpenGL instead of Webrender. It can be done setting gfx.webrender.force-disabled to true.

### Device information
* Device vendor / model and Android version: Samsung Nexus 10 / Android Version 7.1.2 (32 bits) / GPU Mali T604 
* Firefox for Android version: 88.1.2 (Build #2015806937)

**Comment by fprietog** [comment]
Just found this bug similar to the one I'm having:
**Bug 1689064 Optimized shaders produce completely broken rendering on Huawei MediaPad M2 (Mali-T628)**
https://bugzilla.mozilla.org/show_bug.cgi?id=1689064

And it was solved with this:
**Bug 1689064 - Disable optimized shaders on Mali-T6xx. r?aosmond**
https://phabricator.services.mozilla.com/D104752

Since my GPU is Mali-T604 I tested changing gfx.webrender.use-optimized-shaders to false. It made Webrender usable again without need to downgrade to OpenGL.

Another bug showing exactly the same problem that I'm having:
https://bugzilla.mozilla.org/show_bug.cgi?id=1707283

I'll also explain my problem in that bug. I suspect the solution of that bug causes my problem.

**Comment by kbrosnan** [comment]
Closing as an upstream Gecko issue. You should be able to test the [pre-release](https://github.com/mozilla-mobile/fenix/wiki#download) builds to see if that fix is the one you need. I believe we plan on shipping 88.1.3 some time next week with that change.

**Comment by fprietog** [comment]
Ok, but as I said I tested the current beta build and got the same problem. 

The real problem is the solution of this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1707283

The test cases used to mark as fixed that problem were:
```
Verified as fixed on RC 88.1.2, and Beta 89.0.0-beta.2, on the following devices:
    Samsung Galaxy Tab A6 (Android 5.1.1),
    HTC 10 (Android 8),
    Xiaomi Mi4i (Android 5.0.2),
    Nokia 2.4 (Android 10),
    Samsung Galaxy S9 (Android 8), and
    Huawei MediaPad M2 (Android 5.1.1).
```
According to these tests the problem has been solved only for devices with Android 5.1. or Below. 
Notice that Android 7.x wasn't tested, and it is failing.

**Comment by sagudev** [comment]
@fprietog Which ROM are you using?

**Comment by fprietog** [comment]
LineageOS.
