### ISSUE TITLE
[Bug] scrolling with a touchpad selects text

### ISSUE THREAD

**Issue by wills0ng** [mozilla-mobile/fenix#19320]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Browsing through any website (example: bbc.com, arstechnica.com) and using two finger gesture to interact with touchpad on device will cause all text to get highlighted when I am simply trying to scroll down website. Browsing pages using touchpad is rendered unusable...temporarily workaround is using a mouse.

When going to ChromeOS device's settings to verify touchpad settings: Settings > Device > Enable reverse scrolling (OFF) the gesture is not syncing on Mozilla browser however the build-in Chrome browser and all activity in apps are scrolling "correctly"

### Expected behavior
Only expecting to scroll down the page (with reverse scrolling off)

### Actual behavior
1. Two finger gesture "downwards" causes page to scroll "up" and gesture "upwards" scrolls "down" - which is the reverse of system settings. 
2. All text on websites are being highlighted at the same time, which is not expected behavior.
### Device information

* Device vendor / model and Android version: Chrome OS Platform: Manufacturer: Samsung Chromebook Screen size: 13.3" 4K Model: XE930QCA Color: Gray
* Version 89.0.4389.130 (Official Build) (64-bit)
* Firefox for Android version: 88.1.2 (Build #2015806943)

**Comment by kbrosnan** [comment]
duplicate #3708 this will be resolved in v89 around 2021-06-01. For right now you can use one of the [pre-release](https://github.com/mozilla-mobile/fenix/wiki#download) builds that has the fix. Both Nightly and Beta have the fix.
