### ISSUE TITLE
Support inverted landscape orientation for video even if orientation lock enabled

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#19328]
### What is the user problem or growth opportunity you want to see solved?
Some users (including me) keep their orientation lock enabled in android at all times.
But then when I'm watching a youtube video in fullscreen, I'm locked to landscape orientation.
But I still expect the browser to rotate orientation from landscape to landscape inverted (but not portrait).

### How do you know that this problem exists today? Why is this important?
It's important to help watching movies on the phone. Phones typically have volume buttons on one side, and you may wish to keep this side up for easier volume control. But you can't because video is in wrong orientation.

Another example would be watching video on a phone connected to charger. When holding the phone in landscape orientation, you have power cable coming either from left or right side of the phone.
You may wish to rotate the phone, so cable is on the other side, but again you can't because video orientation is locked.

### Who will benefit from it?
Users who watch videos a lot, but otherwise like to have orientation lock enabled.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1708926

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
