### ISSUE TITLE
[Bug] Stop showing CFR Banner for Auto Close Tabs if the setting is enabled

### ISSUE THREAD

**Issue by Jonta** [mozilla-mobile/fenix#19327]
## Steps to reproduce
- Firefox nightly
- Log in to profile
- Set Firefox to automatically close tabs >1 day old on that device

### Expected behavior
- Doesn't give me the tip "You can set Firefox to automatically close tabs after a day" ([closeTabsAfterOneDay](https://github.com/mozilla-mobile/fenix/search?q=closeTabsAfterOneDay)), because I already know about this setting, seeing as I've already used it

### Actual behavior
- Does

### Device information

* Device vendor / model and Android version: Motorola Moto G7 Power - Android 10
* Firefox for Android version: Nightly, on 5apr2021

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10585)

**Comment by LaurentiuApahideanSV** [comment]
Enhancement for https://github.com/mozilla-mobile/fenix/issues/15291.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812455

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
