### ISSUE TITLE
[Bug] about:config changes do not persist

### ISSUE THREAD

**Issue by drewsac** [mozilla-mobile/fenix#19340]
## Steps to reproduce
In firefox beta/nighlty, toggle the security.enterprise_roots.enabled to true. Leave the browser in the background. Within several hours the setting will revert to false.

### Expected behavior
Changes to about:config persist.

### Actual behavior
Changes to about:config on mobile do not persist.

### Device information
Samsung S8-Active, Android 9
Happens with current beta and nightly releases.

Why asking: I use an ad blocker that creates a proxy (AdGuard). Without enabling enterprise certs, one cannot browse in ff. See AdGuards docs here: https://kb.adguard.com/en/android/solving-problems/firefox-certificates.

**Comment by cadeyrn** [comment]
Duplicate of many other issues…
https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+%22security.enterprise_roots.enabled%22
