### ISSUE TITLE
[Bug] Settings value keeps resetting itself after browser update.

### ISSUE THREAD

**Issue by AjvarXX** [mozilla-mobile/fenix#19347]
Security option in about:config Security.enterprise_roots.emabled keeps resettingitself to false every few hours of browsing leading to blocking my browsing alltogether as I need that option for another apk on my phone.

I don't think this happened before update on 88.0.0 beta 5 or at least not frequent or I would remember me being pissed off like now.

I use arm-v7 version on Android 6 with snapdragon cpu based phone.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/3728
