### ISSUE TITLE
Address bar re-appears while scrolling

### ISSUE THREAD

**Issue by gcp** [mozilla-mobile/fenix#19341]
https://www.tagesschau.de/newsticker/liveblog-coronavirus-samstag-229.html

Scroll down the page. At first, the address bar slides away, but it occasionally pops back up, with the "reader mode" sign flickering. Feels glitch-y and seems unintended.

Current Nightly, Pixel 2 XL

**Comment by marcel263** [comment]
The issue also appears to be triggered when scrolling in the opposite direction while the page is still moving. In this case, address bar gets fixed onto the screen and stays there until after a complete scroll.

**Comment by SlowNicoFish** [comment]
Happening here too. Nightly, Oneplus 8T Android 11.
When I only scroll downwards it sometimes pops back up. This does not happen in stable

**Comment by kaream671** [comment]
19341

**Comment by kaream671** [comment]
19485

**Comment by kaream671** [comment]
19485

**Comment by kaream671** [comment]
19341

**Comment by kaream671** [comment]
> 19341

19431

**Comment by sflorean** [comment]
I was able to reproduce the issue on Pixel 3 (Android 11)/latest Nightly, following the steps provided. 
When the page is scrolled fast, the toolbar remains displayed and the reader icon flickers more visible.

**Comment by crisalis2** [comment]
Yes, happens to me too, toolbar keeps reappearing constantly while scrolling down. Basically "Scroll to hide toolbar" doesn't work.

**Comment by crisalis2** [comment]
Honestly, this is a big regression that already hit stable weeks ago and is still present in the latest nightly, but it isn't getting the attention it deserves.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly (2021-12-29).
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as verified.
