### ISSUE TITLE
How about keeping official info updated?

### ISSUE THREAD

**Issue by AjvarXX** [mozilla-mobile/fenix#19349]
When you go to Google PLAY page for Firefox Android App Beta you can check official contact information which people tend to use when they have something to say.

That address is firefox-beta-android-feedback@mozilla.com is nonexistent. So how about requesting a working address, I thought...

![Screenshot_2021-05-02-20-13-13](https://user-images.githubusercontent.com/9568793/116821521-de621480-ab82-11eb-8cf5-0d997acbe8b0.png)

**Comment by amedyne** [comment]
@bifleming @vesta0 FYI. Let's get this updated.

**Comment by vesta0** [comment]
@AjvarXX thanks so much for flagging this! 

We decided a while back to use firefox-android-feedback@mozilla.com for all 3 tracks (nightly, beta, release) to maximize our support team's capability. We remove the extra accounts but it looks like our Beta page wasn't properly updated. We will fix that asap.

**Comment by kbrosnan** [comment]
Closing as this is not a code fix.

**Comment by kbrosnan** [comment]
Ryan updated this and I see the correct email address now.
