### ISSUE TITLE
[Regression, BUG] Black rectangulars all over the screen in browser

### ISSUE THREAD

**Issue by AjvarXX** [mozilla-mobile/fenix#19348]
I have this black rectangulars which sometimes disappear when i touch screen or just teleport.

I did not have this before on FF beta. If I had many versions or repository where to download those I would test where regression appeared.

Android 6. Kodak Ektra with MTK 6797 Helio x20 arm-v8

![Screenshot_20210405-024657](https://user-images.githubusercontent.com/9568793/116821242-cb9b1000-ab81-11eb-8d36-b6803c0beb6b.png)
![Screenshot_20210405-024348](https://user-images.githubusercontent.com/9568793/116821243-cccc3d00-ab81-11eb-9c3b-95dcd4057f8e.png)
![Screenshot_20210405-024225](https://user-images.githubusercontent.com/9568793/116821244-cd64d380-ab81-11eb-8a5b-f22a2b4a3eb0.png)
![Screenshot_20210405-024145](https://user-images.githubusercontent.com/9568793/116821245-cdfd6a00-ab81-11eb-8b95-b9c485a01234.png)
![Screenshot_20210405-024127-2](https://user-images.githubusercontent.com/9568793/116821246-ce960080-ab81-11eb-894c-94a247da4f81.png)
![Screenshot_20210405-024127](https://user-images.githubusercontent.com/9568793/116821247-cf2e9700-ab81-11eb-83a9-896d041578c2.png)

**Comment by Dunexus** [comment]
Tagging @jamienicol from gfx team, looks like another Mali-T gpu driver bug.

**Comment by jamienicol** [comment]
Thanks for the report @AjvarXX. I think this is probably a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1707815

You could try going to about:config, and setting `gfx.webrender.allow-partial-present-buffer-age` to false. Then restart (by swiping the app away in the app switcher, and reopening) and see if it is fixed?

You could also try installing Firefox Nightly as it should be fixed there already.

If that doesn't resolve the issue, could you please attach a copy of your information from about:support?

> If I had many versions or repository where to download those I would test where regression appeared.

The best way to do this is to use the [mozregression](https://mozilla.github.io/mozregression/quickstart.html) tool. You can either install the GUI from the "Install" section on that page, or if you're on Linux or Macos you can install the command line version using the `pip` command. (eg `pip install mozregression`). Then make sure you select the geckoview_example app, on the command line that's using the `--app gve` flag, there should be a selection for it in the GUI. Then you tell it a last know good version or date. And make sure your phone is connected to your computer and usb debugging is enabled.

Then on command line you might run something like `mozregression --app gve --good 87`. This will install a series of versions, and you answer whether they are good or bad.

**Comment by AjvarXX** [comment]
> 
> 
> Thanks for the report @AjvarXX. I think this is probably a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1707815
> 
> You could try going to about:config, and setting `gfx.webrender.allow-partial-present-buffer-age` to false. Then restart (by swiping the app away in the app switcher, and reopening) and see if it is fixed?
> 

Ahhh, what a relief, it worked! It looked like it was not just rectangulars as a side effect but also some artifacts in type field while typing which also disappeared after this about:config fix.
Thank You!

I also will test moxregression tool so thank you twice. Have a great day!
