### ISSUE TITLE
FNX-64 ⁃ Move New Tab ("+") button and last-opened tab to/near bottom of home page.

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1935]
### Why/User Benefit/User Problem
On the home page, the "+" is currently in the middle, above the currently open tabs. That's fine, but it would be much easier/faster to use if it was at/near the bottom of the screen, reachable by thumb.

### What / Requirements
Move the "+" and Tab menu (three dots) buttons to bottom (actually, have address bar at the bottom, and these right above it. But that should probably be a separate request.)

Also, reverse opened tabs location to start at the bottom instead of top. This would solve two issues: fragmentation, and the last-opened tab(s) would be easier to reach than older tabs.

I would prefer this to be default behavior, but at least an option in Settings.

**Comment by buttercookie42** [comment]
Should we move the button, could we at the same time think about restoring the Fennec design element of having the "+" sit at the same position as the tabs counter on the URL bar? A double tap still feels faster than a [long press](https://github.com/mozilla-mobile/fenix/issues/1591).

**Comment by SKITTLE-LA** [comment]
> 
> 
> Should we move the button, could we at the same time think about restoring the Fennec design element of having the "+" sit at the same position as the tabs counter on the URL bar? A double tap still feels faster than a [long press](https://github.com/mozilla-mobile/fenix/issues/1591).

(Dang it, I accidentally closed this issue--but I immediately re-opened it). Anyway...

I would be cool with that. "New tab" is probably the single most-used (other than the address bar.) It looks like there's enough space too.

However, this should probably be a separate issue. Do you want to create one, @buttercookie42 ?

**Comment by buttercookie42** [comment]
Opened #2532.

**Comment by lime124** [comment]
collecting a bunch of issues for a larger collections/homescreen design effort. removing ux label.

**Comment by Scripterr** [comment]
Looks like this issue can be closed now that homescreen search bar is in bottom and tab and new tab buttons are aligned.
