### ISSUE TITLE
Bookmark Re-sort/re-order & AMP disable option

### ISSUE THREAD

**Issue by iamthelara** [mozilla-mobile/fenix#19354]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Who will benefit from it?

Hey, Please add Bookmark re-sort/re-order and option for AMP disable or Modification of AMP to normal Site

**Comment by cadeyrn** [comment]
Sorting bookmarks is #4348. This issue can be used for your AMP request. In general you should open one issue per feature request.

**Comment by amedyne** [comment]
Closing this, refer to #4348
