### ISSUE TITLE
Enable privacy.resistFingerprinting by default to future Firefox for Android and Firefox desktop versions (Win, Mac, Linux)

### ISSUE THREAD

**Issue by hushrom** [mozilla-mobile/fenix#19359]
I've been using this feature ever since the Tor Uplift Project was started by Mozilla to rebase all of the Tor Browser patches like resistFingerprinting and firstpartyisolation to the mainline Firefox browser. For many years of using it, I've seen improvements over time and that less and less websites break to the point it becomes trivial and unnoticeable. It would be nice to at least enable privacy.resistFingerprinting to all Firefox users to not just increase the privacy of Firefox users but to also help Tor Browser users become less unique and have greater anonymity by blending in with Firefox users since Firefox and Tor Browser are essentially the same now minus the ability to run the Tor network. The benefits of enabling it over the downsides has increased over time too due to the improvements of the both the Mozilla and Tor community has made to it and I rarely if ever encounter website breaking this days on my computer.

**Comment by kbrosnan** [comment]
This is something for the Gecko platform to decide.
