### ISSUE TITLE
[Bug] main menu on home screen and tabs use different icons for bookmarks

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#19357]
### Actual / Expected behavior

The main menu uses a different icon for the "Bookmarks" menu item depending on if you're on the home screen or not.

![screenshot](https://user-images.githubusercontent.com/1100614/116878783-1d927300-ac20-11eb-836e-4d5d95a76007.png)

The icon that can be seen on the right side of the above screenshot should be used for both menus.

/cc @Amejia481 because you're working on replacing the icons.

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: ? (go to Settings -> About Firefox): master branch revision bd9d5597fac442f249f1a1db27614cc1effa9929

**Comment by mcarare** [comment]
@vesta0 I see the icon for bookmarks was part of an experiment to use either the one in the screenshot on the left or the one in the right screenshot. It is my understanding from the UX designs that the new icon is to be used.

I just want to confirm with you that is the intention and if I can remove the experiment from the code-base.

Also tagging @brampitoyo for UX confirmation.

Thank you!

**Comment by brampitoyo** [comment]
@mcarare @vesta0 I can confirm that our recommendation is to use:

- `star-with-line` symbol for “Bookmarks” – the place
- `star-fill` and `star-outline` symbols for “Add to Bookmark” – the action

**Comment by vesta0** [comment]
@mcarare that's right and yes we can remove the experiment from code-base.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build (5/12)  with Samsung Note 10 (Android 11).
