### ISSUE TITLE
[Bug] Google Search and some other

### ISSUE THREAD

**Issue by Bhooty** [mozilla-mobile/fenix#19356]
Firefox v88.1.2 
Samsung note 8 sm-n950w
For some reason after the latest update i keep getting a horizontal scroll on google search and some pages. By scroll i mean i can drag screen to left and have white space on right
![Screenshot_20210503-184310_Firefox](https://user-images.githubusercontent.com/46019727/116877201-71f91b00-ac3f-11eb-82e5-4a1498126378.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10601)

**Comment by kbrosnan** [comment]
Reached out to stpeter to see if we can have Google fix this.

**Comment by Bhooty** [comment]
> Reached out to stpeter to see if we can have Google fix this.

Its seems if i use google search fixer extension then the scroll goes away :/ 
Google again doing things against firefox user agent :(

**Comment by Bhooty** [comment]
![Uploading Screenshot_20210511-034756_Firefox.jpg…]()

Microsoft website too

**Comment by Bhooty** [comment]
> Reached out to stpeter to see if we can have Google fix this.

any update sir?

**Comment by Bhooty** [comment]
Google search seems to be fixed
But on answers.microsoft.com
Its still same for example
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance-winpc/windows-10-hangs-when-restarting/e10d948d-5c0c-4394-baed-e336efd17670

**Comment by Bhooty** [comment]
> Reached out to stpeter to see if we can have Google fix this.

Filebot website also same 

https://www.filebot.net/forums/viewtopic.php?t=5379

**Comment by Bhooty** [comment]
.
