### ISSUE TITLE
[Bug] Performing a Search on selected text is failing the second time

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#19363]
## Steps to reproduce

- Select text, press Search from context menu
- Either navigate back, or close tab and reopen previous tab 
- Scroll the screen if context menu disappeared _(This menu being hidden seems like another standalone issue)_
- Tap Search again

### Expected behavior
Either search in a new tab or return to inactive search tab linked to it.
### Actual behavior
Nothing happens.
### Device information

* Device vendor / model and Android version: Android 11 Samsung One UI 3.1
* Firefox for Android version: 88.1.2

**Comment by sflorean** [comment]
I was able to reproduce this on latest Nightly 5/25 with Samsung Note 10 (Android 11).

**Comment by marcel263** [comment]
it is still not fixed

**Comment by fonic** [comment]
This is a very annoying bug that has been around for a long time. Would love to see this fixed.

**Comment by marcel263** [comment]
This is closed because it is a duplicate sorry
