### ISSUE TITLE
DeviantArt Issues

### ISSUE THREAD

**Issue by RTNightmare** [mozilla-mobile/fenix#19364]
I have had issues with using DeviantArt on Android Firefox. It is only on Android. 

1) when I type a sentence in a comment, after the first word, it goes back to the beginning. Example: "I want that" would become "Want I that" if I don't fix it manually. 

2) The second issue is one I thought I fixed, but when I used bulletpoints, it happened. If I type something and then start a new paragraph, it would erase the paragraph I wrote before. Or in the case of bulletpoints, it erased the first sentence from the first bullet. I only have a video of the paragraph issue which seemed to stop after I Uninstalled and reinstalled Firefox. 

I have reported it to DA and they said it wasn't an issue on their end. So I am reporting it to you. I hope I put this in the right place. I don't know how to add a video to this but I have a video available.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10609)

**Comment by kbrosnan** [comment]
What version of Firefox, device, and keyboard? Works for me with a Pixel 2 XL and gboard. Using Firefox Beta 89.

**Comment by RTNightmare** [comment]
I don't know how to check what version of Firefox. Galaxy s10e is the
device. I hope you can help me. 😅

**Comment by LittleAngelwings** [comment]
@RTNightmare 

open Firefox, three-dot menu, settings, scroll down till "About Firefox"
And do you use the nativ android keyboard or any other app as keyboard?
And which Android version has your device, and from which manufacture is your device?

**Comment by RTNightmare** [comment]
I don't see that option.

**Comment by RTNightmare** [comment]
It was never fixed and it was ignored by the person I asked for help who
was useless. 🤬 Thanks for nothing.

**Comment by RTNightmare** [comment]
You stopped responding and never fixed it. I have to live with it due to
the incompetence of the person who stopped trying to help me. 😡

**Comment by vehosah** [comment]
> What version of Firefox, device, and keyboard? Works for me with a Pixel 2 XL and gboard. Using Firefox Beta 89.

For me it happens on Firefox 109, on Nokia 5.4, 6.2 and Microsoft keyboard

**Comment by vehosah** [comment]
> @RTNightmare
> 
> open Firefox, three-dot menu, settings, scroll down till "About Firefox" And do you use the nativ android keyboard or any other app as keyboard? And which Android version has your device?

I have android 13,but the problem was also on Android 12

**Comment by RTNightmare** [comment]
I use Samsung Keyboard, Android isn't even an option. I don't know what
type. The Firefox build is 109.1.1 according to the About Firefox page. I
don't know if that helps.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813652

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
