### ISSUE TITLE
[Bug] Wrong display : "-1" count for search inside the webpage

### ISSUE THREAD

**Issue by Massedil** [mozilla-mobile/fenix#19369]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

EDIT : Use https://gist.github.com/Massedil/4dbab867bed82eb4238cf16931f54057

---

1. Go to https://www.ordre-chirurgiens-dentistes.fr/annuaire/#about
2. For "Code Postal",  add "59", for example
3. Click on "Rechercher" to get more than 1000 "praticiens"
4. Now search inside the webpage for "liber" (start of the word "Libéral")

### Expected behavior

The count is normal. Something like `3/1000`.

### Actual behavior

You can see a wrong count info like `0/-1` or `999/-1`

### Device information

* Device vendor / model and Android version: Samsung Galaxy S5 / Android 10 / LineageOS 17.1
* Firefox for Android version: 88.1.1
 
### Screenshot

![Screenshot_20210420-121251](https://user-images.githubusercontent.com/20357783/116936204-c7492280-ac67-11eb-94a4-13ef9013cb48.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10614)

**Comment by lobontiumira** [comment]
I was able to reproduce the issue on the 5/20 Nightly build with OnePlus 5T (Android 10).

<img src="https://user-images.githubusercontent.com/40694158/118993255-07114900-b98e-11eb-92b5-eb3a53bf4ac1.jpg" width="300" height="550" />

**Comment by Massedil** [comment]
This issue is still reproducible with Firefox 94.1.1.

**Comment by sflorean** [comment]
The issue is still reproducible.

**Comment by Massedil** [comment]
Bug is still present : 
https://gist.github.com/Massedil/4dbab867bed82eb4238cf16931f54057

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807146

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
