### ISSUE TITLE
FNX-65 ⁃ Move address bar to bottom of the home page

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1936]
### Why/User Benefit/User Problem
Address/search bar, Private Mode, and Menu are currently at the middle/top of the page, which can't be reached by thumb. It's also a different location than normal, which can confuse users' muscle memory.

### What / Requirements
Make location and behavior consistent by moving the bar, private mode, and menu to the bottom.
_Desktop site, Find, Share, _and__ Report site issue_ obviously don't need to be included on the home page since they wouldn't do anything.

**Comment by Chris01277** [comment]
I affirm the statement "Make location and behavior consistent by moving the bar, private mode, and menu to the bottom"
 But I can not accept the statement "Desktop site, Find, Share, and Report site issue obviously don't need to be included on the home page since they wouldn't do anything"

**Comment by lime124** [comment]
assigning to consider during the nav re-design effort. removing ux label

**Comment by Neikon** [comment]
My suggestion https://imgur.com/txqVCdw

**Comment by vesta0** [comment]
@apbitner please reference the issue where this work was completed and close this issue.

**Comment by apbitner** [comment]
This work was covered in https://github.com/mozilla-mobile/fenix/issues/561
