### ISSUE TITLE
Nightly performance regression using Adreno 618 causing browser hang, low fps on nos.nl npostart.nl

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#19362]
## Steps to reproduce

Serious performance regression affecting nos.nl, a major Dutch public broadcaster, and also npostart.nl, the VOD portal for Dutch public broadcasting; both are very popular websites.

See video: https://user-images.githubusercontent.com/76437842/116904379-e632bf00-ac3d-11eb-8dfe-2c45bc47bd0d.mp4

No issues with 88.1.2 on same device.

Add-ons do not affect issue

**If any further analysis is required, please do send instructions**

### Device information

Nightly 2015807691

- **GPU**
- Webrender enabled
- Manufacturer: samsung, Hardware: qcom, OpenGL: Qualcomm -- Adreno (TM) 618 -- OpenGL ES 3.2 V@0502.0 (GIT@e1ac91e, I2b3b5fbd00, 1605636002) (Date:11/17/20)
- OpenGL ES 3.2 V@0502.0 (GIT@e1ac91e, I2b3b5fbd00, 1605636002) (Date:11/17/20)
-

**Comment by mcomella** [comment]
@marcel263 Would you be able to capture a performance profile of the behavior for us? The instructions are here: https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=setup Please let me know if you have questions!

**Comment by mcomella** [comment]
@jamienicol Could this be a graphics issue?

**Comment by jamienicol** [comment]
Yep could be! A profile would indeed help determine.

@marcel263 Thanks for the bug report! What device are you using?

As well as a performance profile, since this is a recent regression it would be super helpful if you could use [mozregression](https://mozilla.github.io/mozregression/quickstart.html) to determine what has caused the issue. Please let me know if you need any help with that

**Comment by marcel263** [comment]
@jamienicol hello thank you for responding. Since then I cleared Nightly's data, and the issue has disappeared. Which probably means there was a misconfiguration on the device, as I remember tweaking webrender prefs. Still it was only this site out of many with such bad performance.
Should it return, then I will attempt to provide you with a perf. profile.
