### ISSUE TITLE
[Bug] Enabling Reader view sometimes fails

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#19374]
## Steps to reproduce
1. Go to [Wikipedia](https://en.wikipedia.org/wiki/Main_Page)
2. Access a link from the main page.
3. Activate the reader view.
4. Turn the reader mode off.

### Expected behavior
The reader view functions as expected..

### Actual behavior
The button, while appears to be on, doesn't turn on the reader view.
When turned off, the reader view button has the function of the back button.

### Device information
* Device vendor / model and Android version: HTC Nexus 9 (Android 7.1.1)
* Firefox for Android version: 89.0.0-beta.4

### Notes
When tapped, the reader view button turns to purple as if it's active.
This issue is not always reproducible.

https://user-images.githubusercontent.com/48829350/116997075-fd78b780-ace4-11eb-832a-9f3b560060e9.mp4

**Comment by csadilek** [comment]
@SoftVision-LorandJanos I can't reproduce this here, but what happens here is that the reader view extension encounters an error (e.g. when fetching from the network, or when processing the DOM) and then falls back to re-loading the original page instead. If it was a more permanent network error this would then cause an error page to be displayed, which is not the case for you.

To get to the bottom of this, we would need the logs of the extension. Can you attach those, please?

- In Fenix, go to Setting and enable "Remote Debugging via USB".
- Make sure the device is connected with USB.
- Open Firefox Desktop and browser to about:debugging.
- Select your device on the left and click connect.
- Scroll down and click "inspect" on the "Mozilla Android Components - ReaderView" extension.

This should bring up the logs. Please share any errors you see here after reproducing the problem. Thanks!

**Comment by sv-ohorvath** [comment]
This is not an issue only for wikipedia, I was able to reproduce it on other websites as well: https://geekflare.com/google-warning-messages/ , https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-smartscreen
build: 89.0.0-beta.8

**Comment by sv-ohorvath** [comment]
@csadilek Here are some logs I manage to take [logs.txt](https://github.com/mozilla-mobile/fenix/files/6502022/logs.txt)

**Comment by csadilek** [comment]
@sv-ohorvath Thanks, but this looks like adb logs. We would need the logs from the reader view extension from `about:debugging`. You can get those following: https://github.com/mozilla-mobile/fenix/issues/19374#issuecomment-832736269

**Comment by sv-ohorvath** [comment]
😬 Sorry, here it is: 
[reader-mode logs.txt](https://github.com/mozilla-mobile/fenix/files/6506869/reader-mode.logs.txt)

**Comment by sv-ohorvath** [comment]
I actually copied the text from there. This is it:
![screenshot](https://user-images.githubusercontent.com/4037709/118842802-2ea2db80-b8d2-11eb-9ed4-cec1abc53173.png)

**Comment by sv-ohorvath** [comment]
& the top part: 
![screenshot1](https://user-images.githubusercontent.com/4037709/118843318-9ce79e00-b8d2-11eb-8226-4654877d3385.png)

**Comment by csadilek** [comment]
@sflorean Thank you! I don't see any errors here for reader view, unfortunately. I will try again to reproduce this problem here and debug once I can.

**Comment by SoftVision-LorandJanos** [comment]
This issue is partially still reproducible with the latest Nightly 96.0a1 (2021-11-17T05:11:30.084509).
I could reproduce the part where the reader view icon remains active while the reader view is not activated.
However this time instead of functioning as a back button, it simply refreshes the page.
Device used: HTC Nexus 9 (Android 7.1.1).

https://user-images.githubusercontent.com/48829350/142217997-bac0b577-467a-4457-bbba-84d6a44ccd60.mp4

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 102.0a1 (2022-05-18T17:12:12.001240).
Device used: Samsung Galaxy Tab S3 (Android 9).
Closing the ticket as fixed.
