### ISSUE TITLE
[Bug]Navigation buttons not displayed on Huawei MediaPad M2 (Android 5.1.1) in portrait view

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19375]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open cnn.com.
2. Open the 3dotmenu.
3. Scroll the menu.

### Expected behavior
All items/options are available.

### Actual behavior
Back, forward, reload and share buttons are not visible. This is not reproducible on landscape mode. 

### Device information
* Device vendor / model and Android version: Huawei MediaPad M2 (Android 5.1.1)
* Firefox for Android version: 89.0.0-beta.4, Nightly 5/4.
 
![Screenshot_2021-05-04-12-13-03](https://user-images.githubusercontent.com/58466444/117000138-492d6000-ace9-11eb-849e-2ac7ac7d181d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10619)

**Comment by sflorean** [comment]
This is still reproducible on Fenix versions.

**Comment by ANDREW007CZ** [comment]
> This is still reproducible on Fenix versions.

and still in January 2022.

*Thanks sflorean
