### ISSUE TITLE
[Bug] UI overlaps after using the search bar to search for something

### ISSUE THREAD

**Issue by E0697** [mozilla-mobile/fenix#19376]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Use the search bar to search for something and the tap the keyboard enter button (doesn't happen all the time)
### Expected behavior
No UI overlapping
### Actual behavior
UI overlaps (Screenshot)
![Screenshot](https://user-images.githubusercontent.com/66939100/117004870-42095080-acef-11eb-9c49-b1c100d92cc5.jpg)

### Device information

* Device vendor / model and Android version: Realme 7 Pro, Android 10
* Firefox for Android version: 88.1.1 (go to Settings -> About Firefox)

**Comment by E0697** [comment]
>  Will try to record a video but it's hard to predict when it's going to happen. It also happens in Beta and Nightly (extremely rare) and seems to happen less often after 88.1.3 update.
>     * from where the search was initiatated - homescren, an opened tab: Both I think. Can confirm it happens when searching from the home screen.
> 
>     * does the new page loads as expected? Yes
> 
>     * can the "Scan" / "Search engine" be interacted with? No, it interacts with the webpage elements hidden behind it.
> 
>     * can the webpage - the visible part be interacted with? Yes
> 
>     * can the midlde urlBar be used to load a new url? If so what happens after accessing that page? No. But using the bottom one the problem persists. Even after opening a new tab the toolbar is still stuck (the content changes). Leaving Firefox and launching it again fixes it.

**Comment by E0697** [comment]
I tried to record a video but when I hit the start button it disappears (in a similar behavior to switching to another app and back, it also disappears). 
I'll try to figure out if there are certain circumstances that trigger it. Thank you!

**Comment by SoftVision-LorandJanos** [comment]
I still couldn't reproduce this issue.
@E0697 is it still reproducible on the latest builds?
Thank you!

**Comment by E0697** [comment]
> I still couldn't reproduce this issue.
> @E0697 is it still reproducible on the latest builds?
> Thank you!

It's no longer reproducible on my side. Sorry for taking long to respond.
I'll close the issue.
Thank you for your cooperation!

**Comment by E0697** [comment]
It's no longer reproducible on my side. Sorry for taking long to respond.
I'll close the issue.
Thank you for your cooperation @SoftVision-LorandJanos .
