### ISSUE TITLE
Option for OLED/"true black" theme

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1938]
### Why/User Benefit/User Problem
Saves power since pixels are _totally_ switched off instead of just dimmer. Also looks nicer by allowing screen to blend in with bezel more easily. And user choice!

### What / Requirements
Settings > Theme > "True Black".

Dark mode is **great**! But even better would be the option to change it to true black.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10622)

**Comment by johnny88** [comment]
Hey, for those looking for something more immediate (although this just effects pages not theme) you can install the dark reader addon and change the default color to #000000. This is not perfect but it probably helps somewhat (I'm thinking it could temporarily replace a OLED reading mode.)

**Comment by TheRealOsas** [comment]
Are there any updates for this issue ?

**Comment by TheGreySquare** [comment]
I'll leave here some Black Theme mockup images, just in case this issue will be worked on somewhere in the future (#000000 for BG; #151515 for searchbar; #202020 for elevated menus (3-dot menu, for example), looks good enough I think):

![Firefox Android - Amoled Black Theme Mockup 1.png](https://user-images.githubusercontent.com/47947180/114655872-ba36b480-9cf5-11eb-852e-86d6f1ddd5d4.png)
![Firefox Android - Amoled Black Theme Mockup 2.png](https://user-images.githubusercontent.com/47947180/114655887-c753a380-9cf5-11eb-9329-e02128bdc3d2.png)
![Firefox Android - Amoled Black Theme Mockup 3.png](https://user-images.githubusercontent.com/47947180/114656185-48ab3600-9cf6-11eb-8c9c-9fd044c319c9.png)

**Comment by notDevagya** [comment]
Are update on this ?

**Comment by drannex42** [comment]
Are there any major reasons or considerations why this hasn't been added?

**Comment by notDevagya** [comment]
> Are there any major reasons or considerations for why this hasn't been added?

yes, incompetence

**Comment by fice-t** [comment]
New PR for this just dropped. Preview:

https://user-images.githubusercontent.com/13156601/201012362-b632db80-6af3-46a6-8cd3-94b293e80346.mp4

**Comment by SosPosos** [comment]
> New PR for this just dropped. Preview:
> 
>  Device-2022-11-09-235451.mp4

How i can get it?

**Comment by notDevagya** [comment]
> How can i get it?

It's not merged in the source yet, I don't see it getting merged anytime soon. You could download the source code, merge the pull request, and build it yourself. One could also give you an apk, but it won't be trustworthy or be up to date with latest patches.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807081

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
