### ISSUE TITLE
[Bug] Dom.ipc.processCount does not work anymore?

### ISSUE THREAD

**Issue by michas0602** [mozilla-mobile/fenix#19385]
As written, the setting "Dom.ipc.processCount" resets to 1 itself all the time / every restart since update to Ff 89 beta.

## Steps to reproduce
Set Dom.IPC.processcount t to 4 in about:config or user.js and restart Ff

### Expected behavior
Should be 4 after I set it and restart

### Device information
LG v20 with LOS 18.1

**Comment by ale82to** [comment]
I ve noticed the same!

**Comment by kbrosnan** [comment]
This is controlled by Geckoveiw and not a user/app controllable pref.

**Comment by michas0602** [comment]
Since when, Ff89? Short explanation/details somewhere to read?

Unfortunately it felt faster with Ff88 / dom.ipc.processCount set to 4 or 6!

**Comment by kbrosnan** [comment]
Geckodriver has nothing to do with Geckoview. Geckoview is in the process of adding multi-e10s to Geckoview and as part of that they control those preferences.

**Comment by michas0602** [comment]
Devs are so funny sometimes...ok,I understand your answer...maybe I have to ask in a different way:

Why am I being able to set "dom.ipc.processCount" in Ff 88 successful to 6, resulting in up to 6 webcontent-processes - and not in 89 anymore?

Or: why uses Ff 89 less WebContent-processes (and feels slower...)  than Ff 88?

**Comment by ale82to** [comment]
I m too 100 % sure I was able to change IPC.process count prior to fenix 89 /90, although speed was about the same (always slower than Chrome or Samsung internet of course) so it could just be a placebo effect in my modest opinion while in reality IPC.process count is the same between version.

**Comment by michas0602** [comment]
@kbrosnan Why am I being able to set "dom.ipc.processCount" in Ff 88 successful to 6, resulting in up to 6 webcontent-processes - and not in 89 anymore?

Or: why uses Ff 89 less WebContent-processes (and feels slower...) than Ff 88?

@ale82to You are still able to change it - just use the normal FF 88, not the Beta (89)...and there you can see, that about:support definately shows 6 processes...not sure if its just saying this - but it definately feels faster. Same for 89 if you change it in about:config while running - its attached immediately (and browsing feels faster...dont know why). Until you restart it and it resets itself to 1.

Possibly worth a benchmark...but before I do that, I hope that @kbrosnan tells us more...

**Comment by ale82to** [comment]
oh yess u r right it seems you are more competent than the developer (not a surprise). by the way in my nighlty the default value for IPC.process is 2 not 1

**Comment by michas0602** [comment]
@kbrosnan ?

**Comment by michas0602** [comment]
I am still waiting for an answer...
