### ISSUE TITLE
[Bug] Files do not download

### ISSUE THREAD

**Issue by 0purple** [mozilla-mobile/fenix#19389]
Probably should be part of https://github.com/mozilla-mobile/fenix/projects/47

## Steps to reproduce

1. Download latest Firefox Nightly from Google Play Store
2. Download any file from any website

### Expected behavior

When I tap download, files should be downloaded

### Actual behavior

"Download failed" error, file is not saved

### Device information

* Device: Xiaomi Redmi 9C NFC (angelican) (2/32), MIUI 12.0.7.0 (EU), Android 10
* Firefox for Android version: Nightly 90.0a1 (Build #2015808457)

### Tested on:
f-droid.org
github.com
vancedapp.com
apkpure.com
zoom.us/download

**Comment by Amejia481** [comment]
Could you share some spesific files that you have tested with ?

**Comment by 0purple** [comment]
Nvm issue was with root. Sorry for taking your time, this won't happen again.

**Comment by sflorean** [comment]
Removing qa label, based on the above comment. Didn't encounter any issues while downloading files on Nightly.

**Comment by Amejia481** [comment]
Thanks @sflorean !
