### ISSUE TITLE
Exempting certain sites' cookies from "Delete browsing data"

### ISSUE THREAD

**Issue by imnotabr** [mozilla-mobile/fenix#19381]
With "Delete browsing data", is it possible to exempt certain sites from having their browsing data deleted? For example, is it possible to make it so that the cookies from "example.com" are not deleted when a user deletes browsing data?

<img width="100" alt="Screen Shot 2021-05-04 at 11 15 09 AM" src="https://user-images.githubusercontent.com/62814903/117050246-fee8b680-acc9-11eb-93c5-7c239118dde8.png">

**Comment by jonalmeida** [comment]
It isn't available, so I can turn this into a feature request. 🙂

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/13855
