### ISSUE TITLE
[Bug] Reader view sometimes not working and button not displayed after trying to deactivate it

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#19390]
## Steps to reproduce
1. Access [Wikipedia](https://en.wikipedia.org/wiki/Main_Page) and go to an article from the main page.
2. Turn the reader view on/off.

### Expected behavior
The reader view button functions as expected.

### Actual behavior
The button, while appears to be on, doesn't turn on the reader view.
When turned off, the reader view button is not displayed anymore.

Sometimes when it does turn on, the reader view cannot be turned off at first try.

### Device information

* Device vendor / model and Android version:  HTC Nexus 9 (Android 7.1.1)
* Firefox for Android version: Release 88.1.3

### Notes
This issue is not always reproducible.
 

https://user-images.githubusercontent.com/48829350/117136901-a856a780-adb1-11eb-8cd4-3eb2c85f7781.mp4

https://user-images.githubusercontent.com/48829350/117138898-4b102580-adb4-11eb-8c8e-e7747a21a93a.mp4

**Comment by csadilek** [comment]
I think we can combine this with https://github.com/mozilla-mobile/fenix/issues/19374. I can't reproduce either of those here, but added instructions on how to get to the bottom of this (we need the extension logs to find out what's failing for you). Thank you!
