### ISSUE TITLE
[Bug] Using an HTML video element as a texture source with WebGL no longer works

### ISSUE THREAD

**Issue by jlivak** [mozilla-mobile/fenix#19396]
## Steps to reproduce

Navigate to a website trying to render content from a `<video/>` tag as a texture source using WebGL.  For example, https://threejs.org/examples/webgl_video_panorama_equirectangular.html

### Expected behavior

Video content can be successfully rendered, which worked in older Firefox Android versions (tested on a build from Jan 2020).

### Actual behavior

Instead of the video content, the texture is empty and the following errors are outputted in the console:

```
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. 
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization.
```

### Device information

* Device vendor / model and Android version: Issue is encountered on all of my organization's QA devices, including recent Samsung and Pixel devices.
* Firefox for Android version: 88.1.2

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1709661

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
