### ISSUE TITLE
Consider changing "sync cards across devices" msg when user needs Reauthentication

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#19391]
https://github.com/mozilla-mobile/fenix/pull/19207#discussion_r621412052
> We might want to show this to @violasong or @topotropic to see if we need some kind of reauth string instead of reusing notLoggedInTitle. Let's file a new issue for this.

At the moment if there is a problem with the logged in status of the users, in `Credit Cards` and in `Logins and Passwords` they will see the same string as though they aren't logged in. Namely : _"Sync cards across devices"_ and _"Sync logins across devices"_.

 Perhaps this needs changing to something more appropriate?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10629)

**Comment by topotropic** [comment]
Is there a way to reproduce a state where there's a problem with the logged in status? Thanks!

**Comment by codrut-topliceanu** [comment]
@gabrielluong Can you provide some input please? I'm not that familiar with the FxA system.

**Comment by gabrielluong** [comment]
> @gabrielluong Can you provide some input please? I'm not that familiar with the FxA system.

So, I think this is related to our changes in https://github.com/mozilla-mobile/fenix/pull/19207. According to this https://searchfox.org/mozilla-mobile/source/android-components/components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt#320, you may need to reauthenticate if you change your password.
