### ISSUE TITLE
[Bug] Failed to upload video element with WebGL texImage2D()

### ISSUE THREAD

**Issue by takahirox** [mozilla-mobile/fenix#19399]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

The latest Android Firefox Nightly fails to upload videos to WebGL textures with `gl.texImage2D()`.

The problem has been originally found in Mozilla Hubs https://github.com/mozilla/hubs/issues/4213. Due to this bug, videos are not rendered in Hubs on Android Firefox. This is a sort of big issue for Hubs. I hope it will be fixed soon.

## Steps to reproduce

I made a minimal test which just runs `gl.texImage2D()` to upload ready to play videos.

https://takahirox.github.io/texImage2D-gl-test/index.html

1. Plug in an Android device to your laptop
2. Open Firefox remote debugging tool on the laptop
3. Open the URL in your Android Firefox (Nightly)
4. Select mp4 or webm and click run button
5. See the `gl.texImage2D()` warnings in the remote debugging tool console

### Expected behavior

WebGL `texImage2D()` can upload videos to WebGL texture without errors/warnings.

### Actual behavior

Failed to upload videos with the following warnings

```
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros.
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization.
```

An interesting thing is that ogv works fine with no error.

### Additional context

No errors/warnings on desktop Firefox, desktop Chrome, and Android Chrome.

### Device information

* Device vendor / model and Android version: Samsung Galaxy S8+ / Android version 9 / Kernel version 4.4.111-21427293
* Firefox for Android version:  Android Firefox Nightly version 90.0a1

**Comment by takahirox** [comment]
Made a bugzilla ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1709726

**Comment by kbrosnan** [comment]
Closing upstream issue
