### ISSUE TITLE
[Bug] Remove hard-coded Hex color codes from values\colors.xml and values-night\colors.xml

### ISSUE THREAD

**Issue by neha-b2001** [mozilla-mobile/fenix#19401]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
In the Fenix repository, check the files [app/src/main/res/values/colors.xml](https://github.com/mozilla-mobile/fenix/blob/008c523ed1ebdbe198cc29c462c2988a8cef06f1/app/src/main/res/values/colors.xml) and [app/src/main/res/values-night/colors.xml](https://github.com/mozilla-mobile/fenix/blob/008c523ed1ebdbe198cc29c462c2988a8cef06f1/app/src/main/res/values-night/colors.xml).
### Expected behavior
No hard-coded HEX codes are used for colors which are already defined.
### Actual behavior
There are hard-coded HEX codes for colors that have already been defined. For eg:   

The color code #20123A has been hard-coded for `primary_text_light_theme` even though we already have this color defined as `@color/photonInk80`.

![image](https://user-images.githubusercontent.com/67039214/117255049-ce8a4f00-ae66-11eb-8571-2044f313f4cb.png)
![image](https://user-images.githubusercontent.com/67039214/117255362-2de85f00-ae67-11eb-9399-78578874c7cb.png)

Aim is to **remove these hard-coded HEX codes** and **replace them with pre-defined colors**. 
### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by neha-b2001** [comment]
Since I am an Outreachy applicant, also tagging @eliserichards. Please take a look if possible. 

If this is a valid issue, could I please be assigned to work on this?

**Comment by gabrielluong** [comment]
Hey @neha-b2001, I think if the goal is to use the photon colors variables in place, then I think that should be fine and you have my blessing. To make it very easy to review, I would make an individual commit for each photon colors variable you used to replaced the hard coded value. That way it will be easier to go through each commit and see one change and verify the change in every place compare to looking at a single commit with multiple changes and kinda guessing if the right photon color variable was used in each instance. Hope that makes sense, as reviewers we want to make sure we can catch any errors easily. Thanks for the help!

**Comment by neha-b2001** [comment]
> Hey @neha-b2001, I think if the goal is to use the photon colors variables in place, then I think that should be fine and you have my blessing. To make it very easy to review, I would make an individual commit for each photon colors variable you used to replaced the hard coded value. That way it will be easier to go through each commit and see one change and verify the change in every place compare to looking at a single commit with multiple changes and kinda guessing if the right photon color variable was used in each instance. Hope that makes sense, as reviewers we want to make sure we can catch any errors easily. Thanks for the help!

Yes, I'll replace the hard-coded hex codes with photon color variables, and I'll make individual commits for each replaced value 👍 Thanks!
