### ISSUE TITLE
[Bug] Unresponsive button when secure connection fails

### ISSUE THREAD

**Issue by DamjanTM** [mozilla-mobile/fenix#19402]
When visiting a site with an old or no certificate and tapping the "Advanced..." button the "Accept the Risk and Continue" button is unresponsive. 

This happened on a Samsung A20e

![Screenshot_20210506-125213_Firefox](https://user-images.githubusercontent.com/39652602/117287091-41e19000-ae6a-11eb-9e72-fdffc5355c3d.jpg)

**Comment by mcarare** [comment]
@DamjanTM Thank you for your report. This issue has already been reported and it is tracked here: https://github.com/mozilla-mobile/fenix/issues/18441. CLosing this as duplicate.
