### ISSUE TITLE
Allow Firefox Fenix to open local filesystem files on Android

### ISSUE THREAD

**Issue by boinka** [mozilla-mobile/fenix#19409]
### What is the user problem or growth opportunity you want to see solved?
   - Allow firefox to open local filesystem files on android (file:// and/or content:// URLs).
### How do you know that this problem exists today? Why is this important?
   - Does not work in firefox fenix versions, but works in every other browser in the history of the world, desktop or mobile, including the pre-fenix firefox for android.
### Who will benefit from it?
   - Web developers and reference junkies.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/4049
