### ISSUE TITLE
Blank add-on name in menu?

### ISSUE THREAD

**Issue by cbwee** [mozilla-mobile/fenix#19413]
I am using Firefox Nightly 90.0a1 on Android 10.

I have installed Violentmonkey add-on, and after I opened a website, the add-on name of it in the menu is blank.

I am not sure if it is a bug of Firefox, or just a bug of the add-on itself, because the add-on name of the other add-on I installed can be displayed correctly.

Please let me know if this is a bug of Firefox, if it isn't, I will report it to the GitHub page of Violentmonkey.

![IMG_20210507_084526](https://user-images.githubusercontent.com/34395942/117382999-4ee49a80-aecf-11eb-987b-9a4f208d8c9c.jpg)

**Comment by jonalmeida** [comment]
What language have you set? Sometimes variations like `en-CA` or `en-GB` do not have the translations set for the addon.

**Comment by cbwee** [comment]
I have tried to set the phone's language to Traditional Chinese, English (Australia), English (United Kingdom) and English (United States).

In any of these languages, the add-on name of Violentmonkey in the menu is blank, but I noticed that it is only blank if there are userscripts running in the page.

**Comment by cbwee** [comment]
After testing again, even without userscripts running, the add-on name in menu is still blank, but if I go to about:config, the add-on name is not blank.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 5/12.
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by cbwee** [comment]
The issue still exists in Firefox Nightly Android 105.0a1
