### ISSUE TITLE
Allow Firefox Fenix to be an Android intent handler for web file types

### ISSUE THREAD

**Issue by boinka** [mozilla-mobile/fenix#19410]
### What is the user problem or growth opportunity you want to see solved?
   - Allow Firefox Fenix to handle intents on Android for web file types such as .htm/.html, .gif, .jpg, .css, etc. (use intent-filter in the manifest).
### How do you know that this problem exists today? Why is this important?
   - Attempting to open for example a .html file from a file browser on Android shows the registered file type intent handlers (chrome, opera, etc.), but Firefox is not among them.
### Who will benefit from it?
   - Web developers mostly.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/4049
