### ISSUE TITLE
Burn-in display while using firefox search widget for over 2 years

### ISSUE THREAD

**Issue by jacobkim9881** [mozilla-mobile/fenix#19412]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

![Screenshot_20210507-083912_Samsung Experience Home](https://user-images.githubusercontent.com/46774300/117382843-6006c900-af1a-11eb-8230-c0a293e43293.jpg)

![20210507_084153](https://user-images.githubusercontent.com/46774300/117382848-639a5000-af1a-11eb-9cda-be32e5a936ec.jpg)

### What is the user problem or growth opportunity you want to see solved?
Mobile users will have a burn-in smartphone screen display if they have used their smartphone with the firefox search widget for more than 2 years. 

### How do you know that this problem exists today? Why is this important?
I have set the firefox search widget on my smartphone screen for more than 2 years. While using an application which has white background color, I found my smartphone screen display burn-in. It's uncomfortable while watching movies on my smartphone or while surfing webs because of the burn-in display. It also causes damage to a smartphone display with the widget. Then users would not like to use the widget.

### Who will benefit from it?
Who can change the firefox search widget's theme.

**Comment by kbrosnan** [comment]
The burn in is a function of the screen quality. This would have happened with any widget or icon that displayed on the screen for long periods of time.
