### ISSUE TITLE
[Bug] The sync preference title is shown with an ellipsis.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#19418]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Open Credit cars screen from settings

### Expected behavior

The sync preference title is shown fully.

### Actual behavior
The sync preference title is shown with an ellipsis.

<img src =https://user-images.githubusercontent.com/48995920/117444500-39f51f00-af42-11eb-8055-0ec885e59cf3.jpg width = 40%>

### Device information

* Device vendor / model and Android version:  Huawei P10/ Android 9
* Firefox for Android version: latest master

**Comment by amedyne** [comment]
@topotropic Any recommendations for this?
