### ISSUE TITLE
[Bug] Camera is not working on some devices

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#19416]
## Preconditions
Call between Windows 10 and Android.

## Steps to reproduce
1. Join a call on [Talky.io](https://talky.io/)
2. Allow permissions for camera and microphone.
3. Observe the camera.

### Expected behavior
The camera is turned on.

### Actual behavior
The camera remains off and can't be switched on.

### Device information

* Device vendor / model and Android version: HTC Nexus 9 (Android 7.1.1) and Windows 10.
* Firefox for Android version: Nightly 210507 (GV90)
 
## Notes
Not reproducible on Beta (89.0.0-beta.5)
On Motorola Moto G6 (Android 8) the camera is working as expected.

**Comment by ebalazs-sv** [comment]
This is also reproducible on https://meet.jit.si/ on macOS 10.15.7 (19H1030).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1710121

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
