### ISSUE TITLE
[Bug] tab closed message blocks tab selection

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#19423]
When closing a tab in a tablist that fills the screen, the message/option tab closed/undo appears over the bottom tabs in the list. This prevents users from switching to such tab prior while the message/option is shown.
The user have to wait or opt undo to be able to use these tabs in the list. There are more productive options.

## Steps to reproduce
1 Open multiple tabs, so the tab list fills the screen to the bottom.
2 open the tab list and swipe any tab to remove from the list.
3 fenix shows tab closed messag at bottom of list, over the last tab list items, preventing use of these tabs under the message

### Expected behavior
Favourable expected behavior:
Message/undo option is shown at bottom of list, list scolls to bottom to show, keeping list functions to select any other tab available when message is shown. User has not to worry the list will adapt while selecting other screen to display.

Less favourable expected behavior:
1 Message is movable, so user can move and keep message at desired screen position for while able to use other tab list functions while message is shown.
 
### not expected as solutions
random display of message over screen
Option to prevent showing message
Option to dismiss message

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/19407
