### ISSUE TITLE
Up to 8 network requests occur before target url in COLD VIEW start up

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19435]
We notice up to 8 network requests occur before the target URL loads. Here's a profile: https://share.firefox.dev/3bXO2mE 

We should see if the efforts in https://github.com/mozilla-mobile/fenix/issues/17645 address this as it'd move the load url request to as soon as Gecko can handle it.

When working on this, we should also see if the same behavior occurs if we have only one content process (i.e. maybe this is a regression from multi-e10s).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10651)

**Comment by mcomella** [comment]
Triage: we assume this is still a problem and one we'd like to investigate and address.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807323

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
