### ISSUE TITLE
[Bug] font weight of Khmer language is incorrect

### ISSUE THREAD

**Issue by WordlessEcho** [mozilla-mobile/fenix#19439]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

This issue is discovered when I testing #19438 

## Steps to reproduce
Open [ភាសាខ្មែរ - វិគីភីឌា](https://km.wikipedia.org/wiki/%E1%9E%97%E1%9E%B6%E1%9E%9F%E1%9E%B6%E1%9E%81%E1%9F%92%E1%9E%98%E1%9F%82%E1%9E%9A)

### Expected behavior
This is how Chrome looks like:
![100057500622_96463](https://user-images.githubusercontent.com/12007025/117526340-15a74a00-aff7-11eb-9b7b-e462d03533ac.jpg)

### Actual behavior
![100039300781_156362](https://user-images.githubusercontent.com/12007025/117526351-222ba280-aff7-11eb-9240-14a1958f8441.jpg)

### Device information

* Device vendor / model and Android version: LGE Google Nexus 5, Android 11
* Firefox for Android version: (go to Settings -> About Firefox) Firefox 88.1.3, Firefox Nightly 90.0a.1

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1710513

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
