### ISSUE TITLE
Add Gecko view as a webview

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#19444]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently android system webview is showing in the webview selection list. Please add Gecko view to the list or geckview is not same as android web view? 

### How do you know that this problem exists today? Why is this important?
When Firefox is set as default and chrome is enabled.. Some webpages open in the android webview.. If chrome is disabled some pages open directly in Firefox. . Some rare sites/apps requires android webview only 

### Who will benefit from it?
Users who like to switch entirely to Firefox 

![Screenshot_20210509-112742111](https://user-images.githubusercontent.com/58127841/117562103-089f5f00-b0ba-11eb-9edd-c59d2ec8fd9a.jpg)

**Comment by kbrosnan** [comment]
There are no plans to make Geckoview a drop in replacement for Webview. There are projects like https://github.com/mozilla-mobile/android-components which allow developers to switch between the Webview and Geckoview.
