### ISSUE TITLE
[Bug] Only Google and Wikipedia available in the most visited sites section on home page.

### ISSUE THREAD

**Issue by jaroskrzek** [mozilla-mobile/fenix#19445]
There is something wrong with my Firefox for Android after an update. I have enabled the most visited sites options but on my home page there are only Google and Wikipedia, no matter what I browse. I am unable to delete them.

![Screenshot_2021-05-02-08-31-41_small](https://user-images.githubusercontent.com/83904506/117567535-ec50f180-b0bc-11eb-98a0-90e633ac8421.jpg)

## Steps to reproduce
Go to home page. Try to delete most visited sites.
Browse the internet. Go to home page to verify.

### Expected behavior
Most visited sites shoud appear instead of Google and Wikipedia.
Google and Wikipedia should be possible to remove.

### Actual behavior
Most visited sites don't appear on home page. There are only Google and Wikipedia. When deleted - new Google and Wikipedia appear.

### Device information

I have Huawei P8 Lite, EMUI 4.0.3, Android 6.0, Firefox 88.1.2.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10660)

**Comment by kbrosnan** [comment]
It would be helpful to know what the specific URLs (at least the top level domain + subdomains) that the topsites point to. I wonder if there are some localized variants. pl.wikipedia.org, en.wikipedia.org, google.com, google.pl, etc.

**Comment by jaroskrzek** [comment]
Sure. They are all the same: www.google.com and www.wikipedia.org.

**Comment by jaroskrzek** [comment]
I will show you some more screenshots. 
When I touch one of those Wikipedia top sites icons, it navigates me to wikipedia.org.  When I touch the url bar, it shows me the full address https://www.wikipedia.org. 
For google it is https://www.google.com/webhp?client=firefox-b-m&channel=ts#spf=1620843511247

![Screenshot_2021-05-11-23-29-06_small](https://user-images.githubusercontent.com/83904506/118025854-9308ec80-b360-11eb-9ff4-0636d60feebd.png)
![Screenshot_2021-05-11-23-29-28_small](https://user-images.githubusercontent.com/83904506/118025900-99976400-b360-11eb-8276-a6c0cda4810e.png)

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the 6/30 Nightly build using a Xiaomi mi4i (Android 5.0.2).
I enabled the "Show most visited sites", browsed through some random websites, and, on the homescreen, **only the Wikipedia, Google, and Top Pocket top sites were displayed**. But, I was able to remove each one of those main top sites.

On Google Pixel (Android 10), everything worked as expected.

@jaroskrzek could you retry on your devices, please?

**Comment by jaroskrzek** [comment]
@lobontiumira The problem is still there.

**Comment by sflorean** [comment]
@jaroskrzek this is still reproducible for you?

**Comment by jaroskrzek** [comment]
I managed to delete all of google and wikipedia icons. There were a lot of
them. Some of visited web sites appear as top sites, some don't. I don't
know how it works but it's better than before.

śr., 29.12.2021, 15:01 użytkownik Sorina Florean ***@***.***>
napisał:
