### ISSUE TITLE
3 dot menu of death

### ISSUE THREAD

**Issue by USvsTHEM** [mozilla-mobile/fenix#19449]
### Device information android nightly 90

how can i replace revert or customize the new 3 dot menu this is the dumbest move firefox ever made besides being in same vicinity as google a black hole bringing yall down with it please get back to the basics if it aint broke dont fix it add it to your code of ethics please tell.your devs cut down on the monster drinks slow it down a notch nobody likes google stay in your lane yall are changing too much at one time don't cross over to the dark side

**Comment by jonalmeida** [comment]
Please remember to follow the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) and the [Bugzilla Etiquette guidelines](https://bugzilla.mozilla.org/page.cgi?id=etiquette.html) before filing an issue in the future.
