### ISSUE TITLE
[Bug] Google-connection but LineageOS + F-Droid + Fennec + Google deleted from Fennec search engine

### ISSUE THREAD

**Issue by cb2-dd** [mozilla-mobile/fenix#19442]
## Steps to reproduce

1. You decide to not use Googles version of Android and install LineageOS on your mobile phone
2. You decide to use the free package manager F-Droid to only use free software
3. You decide for installing Fennec after looking for a FOSS browser in F-Droid
4. Before giving the newly installed Fennec browser the permission in NetGuard to access the internet you are shocked by choosing Google as standard search engine and change it to DuckDuckGo and delete Google from the possible search engines
5. You give Fennec browser the right to access the internet in NetGuard
6. You are shocked that NetGuard tells you that Fennec connects to google.com/443

### Expected behavior

I thought Fennec is a free browser without anything to do with Google...

### Actual behavior

Fennec connects to Google without any reason for the user...

### Device information

Should not be of importance. The bug is in Fennec for all devices, I guess...

**Comment by kbrosnan** [comment]
This project does not build the Fennec F-droid apks. I believe you can contact the developers at https://forum.f-droid.org/
