### ISSUE TITLE
Date picker UI impractical 

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#19446]
At least in the latest version of Firefox for Android, the date chooser UI is essentially unusable on any site that requires you to pick a date reasonably far in the past (eg birthday).

The problem is that you are forced to scroll by month, which is impractical. On the desktop you can scroll through mm dd yyyy separately at least; ideally you could do this or override it and enter something manually.

I've encountered this on a number of sites.

**Comment by jonalmeida** [comment]
The date picker UI is provided by the Android OS. Most common versions, including the stock Android UI, allows you to scroll by year as well if you click on the year at the top of the dialog.

Closing since the original user's account is no longer available.
