### ISSUE TITLE
FNX-5343 ⁃ Consider changing accent color of dark theme

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#1944]
Currently the accent color of our dark theme is quite bright. I propose that we use a darker color (like the one found below in the "save tab group" button) in order to ensure users aren't surprised by such a bright color in a dark setting.

## Before
![](https://user-images.githubusercontent.com/4400286/56613889-7c05cf00-65cc-11e9-94e4-f60c3bc2afcc.png)

## After
![](https://user-images.githubusercontent.com/4400286/56613780-3d701480-65cc-11e9-9460-febb62ee669a.png)

**Comment by AmyYLee** [comment]
@shorlander Wondering your thoughts on a colour for the "Save tap group" button in Dark theme. I think the proposed accent colour is too dark but we don't have suitable colour that passes contrast test on the background and also high enough contrast against white text.

**Comment by AmyYLee** [comment]
@sblatz Got a chance to review button colours on dark theme. We had to pick a colour that would pass contrast tests between text/button and button/background. This colour would also apply to radio buttons/toggle switches in settings - Basically it replaces Violet 40 #AB71FF which is what we currently have. The EXCEPTION would be if we had coloured text links on dark background (this would be Violet 40 #AB71FF). Please reach out if you need clarification. 

Color: Violet 50 (#9059FF)

<img width="430" alt="Screen Shot 2019-06-27 at 2 35 49 PM" src="https://user-images.githubusercontent.com/5992746/60291548-1a722180-98e9-11e9-9ce2-b533473b1323.png">

<img width="536" alt="Screen Shot 2019-06-27 at 2 38 22 PM" src="https://user-images.githubusercontent.com/5992746/60291640-4d1c1a00-98e9-11e9-9800-c2c5d17a7a24.png">

**Comment by hakkikaancaliskan** [comment]
We could think about adding dark background to search providers' icon to complete UI.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #190724 from 24/7** using the following devices:
• Googe Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus 3 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

►Pic from Googe Pixel 3a 
![Screenshot_20190724-150152](https://user-images.githubusercontent.com/51314259/61791995-4919e400-ae24-11e9-805f-2ff1eb3f9b8b.png)

@sblatz On the other hand, it seems that in Light Mode the button has some issues #4262
