### ISSUE TITLE
[Bug] Main menu not usable in split screen mode

### ISSUE THREAD

**Issue by oakkitten** [mozilla-mobile/fenix#19463]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open Fenix in split screen mode, on top
2. Press triple dots menu button

### Expected behavior

Menu is usable

### Actual behavior

Menu is rendered off screen, “under” the bottom app:

<img src="https://user-images.githubusercontent.com/1710718/117816497-7a181280-b25e-11eb-9c83-e7f9c2135861.png" width=300>

I'm suspecting it's positioned in a non-standard way, and someone forgot to account for bottom insets when calculating available space

### Device information

* Device vendor / model and Android version: Xiaomi Mi A2 / LineageOS 18.1 (Android 11)
* Firefox for Android version: ? 90.0a1, Sunday 5/9

An issue that might be related: #16667

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10666)

**Comment by SoftVision-LorandJanos** [comment]
Hi @kbrosnan ! Thank you for your report! This issue is reproducible on the above mentioned Nightly version (90.0a1, Sunday 5/9) using a Google Pixel 4 XL with Android 11. I didn't manage to reproduce on Motorola Nexus 6 and on HTC Nexus 9, both with Android 7.1.1, using the same version of Nightly (90.0a1, Sunday 5/9).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 96.0a1 (2021-11-10T09:00:47.893486).
Device used: Xiaomi Mi11 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 102.0a1 (2022-05-10) build.
Device used: Google Pixel 4 (Android 12)

**Comment by oakkitten** [comment]
Still reproducible on Nightly 102.0a1 (2022-05-11), on the same device, Xiaomi Mi A2 (LineageOS 18.1, Android 11).

Aaand, today marks the first anniversary 🎂 of this issue 🐞! Congratulations 🎉! Let's hope it doesn't live to to see the next one ☠️.

**Comment by SoftVision-LorandJanos** [comment]
@oakkitten you're right! I managed to test it on the same Xiaomi device I did before, and I can confirm it is still reproducible. Thank you for pointing this out! Reopening the bug.

**Comment by oakkitten** [comment]
Still reproducible on Nightly 109.0a1 (2022-11-22). While we wait for it to be resolved, let's do something fun. How about some cat facts?

Fact №1. An orange tabby cat called [Stubbs](https://allthatsinteresting.com/mayor-stubbs-the-cat) was the mayor of Talkeetna, a small town in Alaska for 20 years! He had several uncontested elections and although he didn’t hold any legislative power, he was loved by locals and tourists alike.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809245

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
