### ISSUE TITLE
[Bug] HTML Required attribute breaks if first option has no `value`

### ISSUE THREAD

**Issue by MPSinclair** [mozilla-mobile/fenix#19473]
## Steps to reproduce
Try to submit a form with a `select` element that has the `required` attribute where the first option has no `value=""`.

Demo: https://www.michaelsinclair.com/select_bug_demo.html

### Expected behavior
The user should be prompted to choose an item in the list, and the form should be prevented from being submitted.

### Actual behavior
The form is prevented from being submitted (as expected), but the user is not prompted to choose an item, leaving them without any context clues as to why the form won't submit.

### Device information

* Device vendor / model and Android version: Samsung Note 8, Android 9
* Firefox for Android version: 88.1.3 (Build #2015808507)

Happens on other Android devices and versions as well.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview RC 88.1.3 and Nightly 5/12.

### Devices used:
- OnePlus 6T (Android 9)
- Pixel 3 XL (Android 9)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1711091

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kaream671** [comment]
19473
