### ISSUE TITLE
Move undo/delete logic out of TabsTrayFragment

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19475]
I think we should find a way to remove the logic of undo from the fragment which is functionality that is specific to only normal/private tabs.

This will allow us to make that code more easily testable without needing to construct and mock the world (fragment) and reduces the size of growing base class.

**Comment by mcarare** [comment]
Moving this to RFE in Kanban as https://github.com/mozilla-mobile/fenix/issues/19090 depends on this.

**Comment by kaream671** [comment]
19475

**Comment by kaream671** [comment]
19475

**Comment by Mugurell** [comment]
This ticket was just for code refactoring.
Would be nice to know from QA that everything works the same as before regarding the tabs tray. Nothing should have been changed in the user experience.

**Comment by lobontiumira** [comment]
Verified on the 5/28 Nightly build with Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
Regarding tabs tray, everything works as before, no new issues found.
