### ISSUE TITLE
[Bug] Credit card number is displayed encrypted after saving a card

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19482]
## Steps to reproduce
1. Launch Fenix and add a new card.
2. Access the credit card section and observe the credit card number.
### Expected behavior
The credit card number should be censored and the last 4 digits to be displayed.
### Actual behavior
Credit card number is displayed encrypted after saving a card.
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/13.**

<img src = https://user-images.githubusercontent.com/42831109/117993653-97c1a680-b348-11eb-98c7-35ea3bc77c08.png width = 45%>

**Comment by gabrielluong** [comment]
Should be fixed with https://github.com/mozilla-mobile/fenix/issues/18270.
