### ISSUE TITLE
FNX-5344 ⁃ [Bug] Bookmarks without a title should display URL as a fallback

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#1948]
Otherwise we just see empty rows:

![Screenshot](https://user-images.githubusercontent.com/465422/56615921-11a35d80-65d1-11e9-8dab-1a59554f49bf.png)UNITO-UNDERSCORE!1556053280!

**Comment by sv-ohorvath** [comment]
Verified as fixed, I don't see any bookmarks without a title anymore.

**Comment by sv-ohorvath** [comment]
I stumbled upon some new websites that don't have a bookmark title and don't replace it with the URL either: mozilla.gihtub.io, konga.com and help.twitter.com.
