### ISSUE TITLE
[Bug] tons of tab crashes fenix nighlty 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#19489]
since two last weeks I m experiencing tons of crashes for single tab in nighlty
here s the soccorro 
https://crash-stats.mozilla.org/report/index/27f8cecf-ef4a-44b7-8b7b-877850210513
is there any remote possibility to have it fixed in a decent amount of time.
u ve already reported this bug two weeks ago!!

**Comment by kbrosnan** [comment]
Filed bz-1711081 looks like it might be related to Violentmonkey.

**Comment by ale82to** [comment]
thank you for letting me know I also messes some about config related to fission, I reverted no crash for now
