### ISSUE TITLE
[Bug] Twitter Not Loading - Potential Cookie Incident

### ISSUE THREAD

**Issue by MadManMoon** [mozilla-mobile/fenix#19480]
Twitter does not load in a Private tab on Firefox Nightly, latest version (_and versions through the past month_). 

I suspect this is due to aggressive cookie management, because of the testing/results below, and experience over the past year.

---

1. _I have searched for duplicate issues, but please do be aware that not everyone uses the same syntax for everything._
2. _Steps to reproduce provided, background given as extra information._

---

## Steps to reproduce

1. Open Private Browsing
2. Enter twitter.com
3. Dismiss app notification and cookie warning if it loads
4. Login
5. Get [this image](https://pixhost.to/show/209/207567912_twit1.jpg)

( _[Image available in a (downloadable) gallery on pixhost.](https://pixhost.to/gallery/dKkxB)_ )

### Expected behavior
It should load (for example) the notifications tab like the second screenshot in the above gallery, individual link is below.

https://pixhost.to/show/209/207567913_twit2-normal.jpg

### Actual behavior
It loads any Twitter page like the first screenshot in the above link.

https://pixhost.to/show/209/207567912_twit1.jpg

### Device information
* Samsung / Galaxy Tab S4 / Latest Android
* Firefox Nightly, latest, this has been happening for about a month now through various nightly versions

### Also tested and/or ruled out
* 2 different ISPs
* 3 different DNS providers
* All Add-Ons turned off
* DPI set to desktop resolution via flags
* No firewalls
* No proxy
* All enhanced tracking protection off or any combination within
* All service workers either current, or removed.

### Not tested
* Normal browsing load
* Other browsers

### Further Information / Details (_ignorable - but it'd be great if you read it_)
I've had issues with (chromium like) aggressive tab reloading affecting tabs that I needed for about a year, now. This wasn't an issue previously, in fact it was the reason to use firefox instead of any other browser. I can't remember if the new mobile engine worked for a while, but I _think_ it did.

Essentially, I'm saying that I don't think that the issue is necessarily with Twitter.com, per se, more a larger issue that is a combination of aggressive cookie handling and tab reloading causing a perfect storm. However with other sites it will occur when you switch to another tab or app, with Twitter, it can happen during the login refresh.

So, you could do literally anything else on the tablet (or phone - I've seen reports from others) and the tab reloads, and dumps all cookies, causing a completely fresh reload of the page logging you out of services, or losing searches. Here are *some* example behaviours that cause this:
* Trying to upload an image for a twitter post
* Briefly switching to another tab to look at (for example) a list of StartPage search results (but not interacting)
* If you perform a StartPage search and go to a result tab, the search is reloaded and lost
* Switching to another app for a split second

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/19318

You can follow the platform work at bz-1709483

**Comment by MadManMoon** [comment]
cheers!
