### ISSUE TITLE
[Bug] Crash when switching to an experiment branch

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#19485]
## Steps to reproduce

- Enable Secret Menu
- Go to Settings-> Nimbus Experiments
- Select an experiment
- Select an experiment branch
- Switch to a different experiment branch

### Expected behavior
Should be able to switch to a different experiment branch successfully

### Actual behavior
Crash
 
Crash log:
`
05-11 16:24:46.747 10138 10138 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(timestamp=1620764686744, throwable=java.lang.ClassCastException: androidx.preference.Preference cannot be cast to org.mozilla.fenix.settings.DefaultBrowserPreference, breadcrumbs=[Breadcrumb(message=onCreate(), data={recreated=false, intent=android.intent.action.MAIN, instance=248218743}, category=HomeActivity, level=INFO, type=DEFAULT, date=Tue May 11 16:23:57 EDT 2021), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue May 11 16:23:57 EDT 2021), Breadcrumb(message=onAttach(), data={instance=158460725, activityInstance=248218743, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Tue May 11 16:23:57 EDT 2021), Breadcrumb(message=onCreateView(), data={customTabSessionId=null, instance=158460725, activityInstance=248218743, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Tue May 11 16:23:57 EDT 2021), Breadcrumb(message=onStart(), data={instance=248218743}, category=HomeActivity, level=INFO, type=DEFAULT, date=Tue May 11 16:23:57 EDT 2021), Breadcrumb(message=onResume(), data={instance=248218743}, category=HomeActivity, level=INFO, type=DEFAULT, date=Tue May 11 16:23:57 EDT 2021), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue May 11 16:24:05 EDT 2021), Breadcrumb(message=onDestroyView(), data={instance=158460725, activityInstance=248218743, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Tue May 11 16:24:05 EDT 2021), Breadcrumb(message=Changing to fragment aboutFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue May 11 16:24:27 EDT 2021), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue May 11 16:24:32 EDT 2021), Breadcrumb(message=Changing to fragment nimbusExperimentsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue May 11 16:24:37 EDT 2021), Breadcrumb(message=Changing to fragment nimbusBranchesFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue May 11 16:24:38 EDT 2021), Breadcrumb(message=Changing to fragment nimbusExperimentsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue May 11 16:24:45 EDT 2021), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue May 11 16:24:46 EDT 2021)], uuid=cf5fd7a8-5b15-49a5-8141-e3482a8f7885)`

**Comment by mcarare** [comment]
On first thought, this kind of error or any other that would result from dynamically changing experiments branch can be avoided if the activity is recreated / the back stack is cleared. Instead of having a workaround for handling this particular case, IMO we should recreate the activity as we do on theme change. 
As I cannot seem to be able to test this, as I cannot get the list of experiments on that screen, maybe @gabrielluong can test adding activity recreation in `onBranchItemClicked` in `NimbusBranchesController`? Thank you!

**Comment by mcarare** [comment]
On a separate note, @amedyne is the debug menu supposed to work on release/beta versions on the store?

**Comment by kaream671** [comment]
19482
