### ISSUE TITLE
[Bug] Edit card section is not displayed in landscape mode after resuming Fenix

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19494]
## Steps to reproduce
1. Launch Fenix and open Saved Cards.
2. Access a saved card and tap on any saved credit card.
3. The Edit card section is displayed.
4. Rotate the device in landscape and add Fenix to the background by tapping on the device home button.
5. Resume Fenix.
### Expected behavior
The Edit credit card section is still displayed in landscape mode.
### Actual behavior
Edit card section is not displayed in landscape mode after resuming Fenix
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/13.**

https://user-images.githubusercontent.com/42831109/118133148-27c72500-b409-11eb-8b68-ccfc9354b72e.mp4

**Comment by codrut-topliceanu** [comment]
Hey @abodea. Is the issue still reproducible for you on latest nightly? I'm not able to reproduce it 🤷‍♂️ .

**Device information**
Device: Google Pixel 4 (Android 11).
Firefox for Android version: Nightly 5/16


https://user-images.githubusercontent.com/60002907/118493999-5d7e4d80-b72a-11eb-80eb-ec0aad846b94.mp4

**Comment by eliserichards** [comment]
This might not be relevant anymore once [biometrics are implemented](https://github.com/mozilla-mobile/fenix/pull/19505) (on pause we pop the user back to settings to authenticate again)

**Comment by codrut-topliceanu** [comment]
Seeing as biometrics are now implemented and returning to the manage->edit credit cards screen now requires a biometrics check, is this issue still relevant?

**Comment by abodea** [comment]
Based on the comments above I'm closing this issue.
Note that I was redirected to `Credit cards` after a home button interrupt and I didn't encounter any issues.
