### ISSUE TITLE
[Bug] Sync cards toggle is not saved after a home button interrupt

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19493]
## Steps to reproduce
1. Access the credits cards section.
2. Toggle on the `Sync cards` option.
3. Tap on the device home button (add Fenix to the background).
4. Resume Fenix and observe the `Sync cards` toggle.
### Expected behavior
Sync cards toggle should not be changed after a home button interrupt.
### Actual behavior
Sync cards toggle is not saved after a home button interrupt
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/13.**
 
https://user-images.githubusercontent.com/42831109/118122285-4f16f580-b3fb-11eb-849d-ebf5156ad142.mp4

**Comment by mcarare** [comment]
For QA: please also consider testing this https://github.com/mozilla-mobile/fenix/issues/19554 scenario.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 5/25 with Google Pixel 4 XL (Android 11).
