### ISSUE TITLE
FNX-5346 ⁃ [UX] Shortcuts

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#195]
**User Story**
As a user, I want to quickly use a specific search engine for a search without having to change my default search provider.

* when people enter search from home, the shortcuts are displayed
* we list specific search engines in alphabetic order at the top (for example Twitter or Wikipedia –  tbd by @vesta0 what search engines we support here, similar to Fennec?)
* below that we list generic engines
* people can start typing and then change the search engine, whatever they typed is preserved

**Mockup**
Single Screens: https://mozilla.invisionapp.com/share/U8R4ASRNZ59
Flow: https://mozilla.invisionapp.com/share/Q7R4ATB5PWY

**Comment by bbinto** [comment]
Still in feedback stage, final design needs to be approved by @shorlander then

**Comment by sblatz** [comment]
@topotropic how would we like the highlighted "shortcuts" button to look in private browsing since the background is already purple? Here's what I had before the design change:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/4400286/54721522-7b869e00-4b1f-11e9-9fa6-60a335dd63c9.png">

**Comment by brampitoyo** [comment]
@sblatz wrote:
> […] how would we like the highlighted "shortcuts" button to look in private browsing since the background is already purple?

Hi Sawyer, let’s hold off on making this decision for now.

On Private Browsing, we are thinking to design a light and dark variant to follow normal browsing and system theme (if Android Q has this Setting).

If that’s the case, then the highlight colour may be able to follow normal browsing.

However, if we decide that there should only be one PBM theme, then we will make a decision about colour value for the highlighted shortcuts button.

**Comment by colintheshots** [comment]
This looks ready from an engineering perspective. We'll need a dark mode version and an answer to Sawyer's question about private browsing and this is good.

**Comment by lime124** [comment]
thanks @colintheshots!

@brampitoyo is going to answer sawyer's question today. 

@AmyYLee to answer your question regarding how to make it dark mode.

**Comment by brampitoyo** [comment]
@sblatz The colour value for the highlighted button is our `accent` colour, which is `#312a65`.

Sorry for the overdue reply, this is one of those cases where “If you wish to make an apple pie from scratch, you must first invent the universe”. I had to figure out a button colour that will look good with the rest of the new Private Browsing theme, and that requires designing the PBM theme first, keeping in mind that it needs to look different from _both_ light and dark theme.

The good news is, the old theme is already mostly on point with the new theme in terms of colour values!

**Comment by bifleming** [comment]
@sblatz @mheubusch can we say this has been reviewed?  Isn't the work pretty much done on Shortcuts?

**Comment by topotropic** [comment]
@sblatz I think we wanted to go to shortcuts view when tapping the favicon additionally to the shortcut chip @bifleming should I add a follow up?

**Comment by AmyYLee** [comment]
> thanks @colintheshots!
> 
> @brampitoyo is going to answer sawyer's question today.
> 
> @AmyYLee to answer your question regarding how to make it dark mode.

This has been covered in Dark Mode edits in Comments:
https://mozilla.invisionapp.com/share/QRRJ99U27DY

**Comment by mheubusch** [comment]
@AmyYLee can we move this  to done and close it?

**Comment by AmyYLee** [comment]
> @AmyYLee can we move this to done and close it?

My feedback on edits to dark mode (as far as I can tell) hasn't been applied yet. Should I still close this bug?

**Comment by sblatz** [comment]
This feature is implemented and looks like this ticket is stale. Please file a follow up issue if this has additional work :)
