### ISSUE TITLE
FNX-5347 ⁃ [Bug] Bookmark contextual menu is scrollable and clipped near bottom of the screen

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#1950]
See screenshots:

![Screenshot](https://user-images.githubusercontent.com/465422/56616058-68a93280-65d1-11e9-89e6-571dcfd41098.png)UNITO-UNDERSCORE!1556053332!

![Screenshot](https://user-images.githubusercontent.com/465422/56616062-6ba42300-65d1-11e9-89df-73c385242608.png)UNITO-UNDERSCORE!1556053342!

**Comment by grigoryk** [comment]
It's also displayed too closely to the edge, there should be a margin.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1926 (#11760617) with Samsung Galaxy S8 (Android 9), Nexus 5 (Android 6.0.1), Xiaomi mi4i (Android 5.0.2).
