### ISSUE TITLE
Allow users to control whether sites are exempt from credit card autofill

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#19504]
Displays a list of sites that are exempted from saving credit cards along with controls to remove the exception. See [LoginExceptionsFragment.kt](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/exceptions/login/LoginExceptionsFragment.kt)

**Comment by gabrielluong** [comment]
This isn't part of the PRD. So, I imagine we will need to wait for product to weigh in if we want this..

**Comment by gabrielluong** [comment]
I think this is mostly a Logins feature since we don't do this on Desktop.
