### ISSUE TITLE
[Bug] Tapping "Search" context menu item again has no effect.

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#19514]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open any web page such as duckduckgo.com
2. Long-press a word, such as "simplified" below the search field.
3. Tap "Search" (a new tab opens)
4. Go back to the previous page (by swiping at the edge in gesture navigation).
5. The word is still highlighted. Long-press the word again.

### Expected behavior
Text selection menu shows, but tapping "Search" does not work.

### Actual behavior
Tapping "Search" should work as before.

### Device information
* Device vendor / model and Android version: It happens on two devices running Android 10/11 with gesture navigation.
* Firefox for Android version: 88.1.3 (Build #2015808505)

**Comment by marcel263** [comment]
This is a duplicate of #19363, yes?

**Comment by HubKing** [comment]
> 
> 
> This is a duplicate of #19363, yes?

Yeah, seems like the same bug.
