### ISSUE TITLE
[Bug] Firefox always asking to be set as default app

### ISSUE THREAD

**Issue by Rodze** [mozilla-mobile/fenix#19519]
## Steps to reproduce

Open Firefox menu

Cannot find a way to disable this menu entry (first)

![20210515_161851](https://user-images.githubusercontent.com/499237/118375651-6390f480-b599-11eb-9a53-b4b3d4d0a258.jpg)

Galaxy S9 Android 9 Build 2015810379

**Comment by kbrosnan** [comment]
This is the expected design.

**Comment by Rodze** [comment]
> This is the expected design.

Are you sure this is the expected design?

https://user-images.githubusercontent.com/499237/118568968-4c940300-b74f-11eb-85b7-cf7fcdab1f3e.mp4
