### ISSUE TITLE
[Bug] long words without proper display functions 

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#19516]
Some words can be wider then can be displayed. Fenix does not always provide proper alternatives to display such word completely, keeping the last part of a word hidden.

As a user I expect the main purpose of viewing content is to be able to see the full content, unless there is a reasonable restriction such as intended hiding or physical boundary.

If a word does not fit, I would at least expect a zoom out function or scrolling option. This does not always seem available for reasons unclear to me.

In a vertical view the user may think to use horizontal display, however this tilting does not necessarily be an option. Fi if the word is still to wide for the the horizontal screen or when the user is unable tot tilt (when the device is fixed or the screen is already in horizontal viewing use).
Or a user may remember to turn on desktop mode, wich is not a future proof solution, may be restricted, and defeats the purpose of using mobile mode on a mobile device.

Suggestion:
Be sure words can be fully displayed in any display mode, unless physical boundary is reached or more important restrictions are requested. Scrolling and zoom options should be available in favour of workarounds via physical and functional options while not even sure if they are available.

**Comment by kbrosnan** [comment]
Without specific examples this report is too general to be worked on.

**Comment by lobontiumira** [comment]
@clientenq please provide some pages, the device and the version of Fenix where you have encountered this issue
Also, a screenshot might be helpful.
Thank you!

**Comment by SoftVision-LorandJanos** [comment]
This issue is not reproducible.
Verified on the latest Nightly 96.0a1 (2021-11-19).
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.
