### ISSUE TITLE
http and www added to address

### ISSUE THREAD

**Issue by brainchild0** [mozilla-mobile/fenix#19510]
# Steps to reproduce

Enter address `http://thisisnotarealhost.local/`.

# Actual results

Firefox changed address to `https://www.thisisnotarealhost.local/`, then reported that the web site is unreachable.

Note the change includes both use of the secure protocol (`https`) and a web sub-domain (`www`).

# Expected results

Firefox should have preserved the address, and perhaps merely suggested changing it.

The real case is a simple one. A user seeks to connect to a local appliance, at some time when it is not operational. Realizing that the endpoint is unreachable, the user sets the appliance to be operational, then attempts to to reconnect. The address registered in the browser, however, is not correct.

In this case, the appliance uses a basic local domain, not a fully-registered web domain leading with `www`, or using a secure certificate. Such a case is very common for local systems, particularly small devices. Firefox must not assume that an address follows some canonical form for a full web site, even following a failure to reach a host using an address not in this form.

In recent use, I attempted to debug a small device operating on a simple local domain, and repeatedly needed to restore the address to the original form, changing `https` back to `http` and removing the leading `www`. The behavior was tremendously frustrating, and makes Firefox essentially unusable for this simple task.

# Device information

This problem reproduces in version 88.1.3 on Android. I am running Havoc-OS 2.8  (based on AOSP 9) on a Google Pixel 3.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-10696)

**Comment by brainchild0** [comment]
Also appears on desktop application (see [report in Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1711217)).

**Comment by SoftVision-LorandJanos** [comment]
Hi @brainchild0 ! Thank you for your report! I managed to reproduce the issue you described above on the latest Nightly (90.0a1 - Monday 5/17 @ 5:05 AM), the latest Beta (89.0.0 beta.7) and on the latest Release (88.1.3).

Devices used: Motorola Nexus 6 with Android 7.1.1 and Samsung Galaxy Tab 3 with Android 9.

**Comment by brainchild0** [comment]
Please keep open, bot or no bot.

**Comment by SamuelMezger** [comment]
Still relevant.

**Comment by brainchild0** [comment]
Please keep open.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811589

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
