### ISSUE TITLE
[Bug] port restrictions without proper user control

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#19517]
Fenix enforces port restrictions while not providing any proper user control to overrule to be able to use legitimate services.

Restricting use of services fi via specific ports is usually a security restriction in consideration for practical reasons. As developers considering use of ports as a risk for users to also block intended use is not practical and only user friendly when it is convenient for user. The developers of a browser are however not in the position to determine if it is convenient, nor in the position to even determine if use of a port is intended legitimate or a real threat.

The official stop of registered ports may come with disadvantages, however the freedom to use any port for a service is also a practical right to users and developers. This has been established practice for over 20 years. As such it is not be ignored, at least not by blocking.

Suggestions for a solution:
- fenix only blocks when there is per case sufficient proof use of a port has malicious intend. I suspect this is currently practically impossible since this requires per request current  browser knowlede about the intended communication, which fenix does not have.
- fenix by default does not automatically provide use of restricted ports, however provides the user with information regarding the risk and provides the option to make a well informed choice, to accept or ignore the warning not only depending on the partly informed opinion of fenix developers.

These choices keep use of ports as inteded by the internet community and common practice for legitimate use by benign developers, organisations and users.

These choices are in line with common practice to provide user choise in case of possible risk while not blocking legitimate use, such as certificate issues without proper well informed reason the risk is more important then the practical consequences for the user.

These choises provide opportunities for users and fenix developers to keep informed and aware, instead of blocking well informed practical use. 

The choise to prevent unnecessary restriction was available, untill fenix decided users can do without advanced configuration options. Even if advanced configuration in general is currently not practical to introduce due to limited time to develop and maintain, these choises provide the opportunity to proof other solutions are more practical and user friendly with respect to users and fenix developers.

**Comment by gzqx** [comment]
I don't understand how this problem is still not resolved.
Accessing a url:port is the basic function that a browser can be called as a browser, I can accept suggestion and warning, but firefox android don't even provide an option, which breaks entire user experience.
