### ISSUE TITLE
[Bug] Tabs for Top Toolbar

### ISSUE THREAD

**Issue by gitpubber** [mozilla-mobile/fenix#19523]
Firefox is not UI optimized for Top toolbar setup.

![ff](https://user-images.githubusercontent.com/76197622/118409553-92e25700-b6a8-11eb-93fc-44d16f98354f.png)

As you can see,

1) Tabs panel slide from below.  When i click on tabs button which is present at top, i expect tab grid to be near it.

2) New Tab button is at very bottom. It reduces user experience because finger must move from top to bottom. it must be near tab button(top) for ideal user experience.I expect it near top-left if possible.

So, i think that for top toolbar setup,full tab page is good(whereas current tab bottom-slide popup widget is good for bottom toolbar setup).can we have tab page widget like chrome instead of current tab widget bottom-slide popup?

**Comment by kbrosnan** [comment]
This is not possible with the current design using material design sheets.

**Comment by gitpubber** [comment]
Can you atleast provide option to move "new tab" button to top of material design tab sheet?
