### ISSUE TITLE
[Bug] You can not copy any comment in YouTube with long press.

### ISSUE THREAD

**Issue by Zesko** [mozilla-mobile/fenix#19524]
## Steps to reproduce
1. Go m.youtube.com 
2. Select any video in YouTube and read comments of this video.
3. Copy any word or text in any comment with long press more than 1 sec.
4. It doesn't respond. 

### Expected behavior
Long press starts asking for copy or search of comment in YouTube in other browser in Android.

### Actual behavior
Long press does not start asking for copy or search of comment in YouTube.

### Device information
Samsung Galaxy s10 Lite with original OS latest version
Android 11 (Samsung) and One UI-Version 3.1
Firefox for Android version:  88.1.3

**Comment by sflorean** [comment]
I was able to reproduce this issue on Nightly 5/17, Beta and RC versions with the following devices:
- Samsung Note 10 (Android 11)
- LG G7 Fit (Android 8.1)
The issue is not reproducible on Chrome.

**Comment by kbrosnan** [comment]
This is a Youtube bug. See https://bugzilla.mozilla.org/show_bug.cgi?id=1642073#c11 and https://webcompat.com/issues/65492
