### ISSUE TITLE
[Bug] Cycling of Tabs doesn't include New Tab

### ISSUE THREAD

**Issue by gitpubber** [mozilla-mobile/fenix#19529]
Suppose if i have 3 tabs Tab1 ,Tab2 and Tab3.

swiping on toolbar does this:

Tab1 <-> Tab2 <-> Tab3 <-> Tab1

I would like to have:

Tab1<-> Tab2 <-> Tab3 <-> New Tab <-> Tab1

**Comment by kbrosnan** [comment]
The home screen is not a tab. Duplicate #13809
