### ISSUE TITLE
[Bug] After deleting a saved card there is no redirection to Credit cards section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19527]
## Steps to reproduce
1. Save a credit card.
2. Open the saved cards, select the card and delete it, observe the redirection.
### Expected behavior
There should be a redirection to the Credit cards section.
### Actual behavior
After deleting a saved card there is no redirection to the 

Credit cards section
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/13.**
 
https://user-images.githubusercontent.com/42831109/118466865-ef2a9280-b70b-11eb-8b81-680cafa5db73.mp4

**Comment by mcarare** [comment]
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/19054.
