### ISSUE TITLE
[Bug] webm video fails with NS_ERROR_DOM_MEDIA_FATAL_ERR, but works in reader view

### ISSUE THREAD

**Issue by matham** [mozilla-mobile/fenix#19522]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Load https://matham.github.io/ceed/guide/function.html on android.

### Expected behavior

Display the videos on the page normally, like in reader mode or on Firefox desktop.

### Actual behavior

Firefox will show the red status line for a bit, as if it's trying to finish loading. But ultimately it shows "no video with supported format mime found" where the videos should display.

When I switch to reader view, it instantly displays all the videos without a problem.

### Device information

* Device vendor / model and Android version: Moto X4 LineageOS 18.
* Firefox for Android version: Firefox Beta (89.0.0-beta.7)

 
One of the videos from the page is attached:  [function_random.zip](https://github.com/mozilla-mobile/fenix/files/6489761/function_random.zip)

ffprope output:

```
Input #0, matroska,webm, from 'function_random.webm':
  Metadata:
    ENCODER         : Lavf58.45.100
  Duration: 00:00:44.20, start: 0.000000, bitrate: 28 kb/s
    Stream #0:0: Video: vp9 (Profile 1), yuv444p(tv), 460x574, SAR 1:1 DAR 230:287, 15 fps, 15 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      ENCODER         : Lavc58.91.100 libvpx-vp9
      DURATION        : 00:00:44.200000000
```

Using ADB with firefox desktop debugging I get:

```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted.
Media resource https://matham.github.io/ceed/_videos/function_random.webm could not be decoded.
All candidate resources failed to load. Media load paused.
Media resource https://matham.github.io/ceed/_videos/function_random.webm could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: OnError
```

**Comment by SoftVision-LorandJanos** [comment]
Hi @matham ! I managed to reproduce the issue you described above using the latest Nightly (90.0a1 - Monday 5/17 @ 5:05 AM) and the latest Beta (89.0.0 beta.7) and on the latest Release (88.1.3).
Devices used: Motorola Nexus 6 with Android 7.1.1 and Samsung Galaxy Tab 3 with Android 9.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1711540

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
