### ISSUE TITLE
[FR] Double button Tab button to open new tab

### ISSUE THREAD

**Issue by gitpubber** [mozilla-mobile/fenix#19532]
Currently, single clicking tab button will open tab slider. i would like to have double clicking tab button open new tab.  Please, consider this.

**Comment by kbrosnan** [comment]
Are you using tabs on top?

**Comment by gitpubber** [comment]
> Are you using tabs on top?

yes, i use top toolbar setup

**Comment by Matth7878** [comment]
Duplicate with issue #15025
Sadly it seems unlikely to be implemented ☹️
