### ISSUE TITLE
Check mark barely visible on Nimbus Experiments branch selection (when on Light Theme)

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#19534]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Customize and set "Theme" to "Light" (go to Settings-Customize-Theme)
- Enable debug Menu
- Go to Nimbus Experiments
- Select an experiment

### Expected behavior
When a user selects a branch, check mark is visible/clear

### Actual behavior
- User can barely see the check mark for selected experiment branch. Note that in Dark Theme the check mark is visible
![Screenshot_20210513-105256](https://user-images.githubusercontent.com/68711330/118509362-f5b20d80-b6fd-11eb-9426-c589759ce45b.png)

- 
### Device information

* Device vendor / model and Android version: Pixel 3XL
* Firefox for Android version: ? (go to Settings -> About Firefox) Firefox Nightly  
90.0a1 (Build #2015810763)
AC: 90.0.20210516143141, be02514d7
GV: 90.0a1-20210516091748
AS: 76.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10714)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 96.0a1 (2021-11-18).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 102.0a1 (2022-05-18) build.
Device used: Google Pixel 4 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 110.0a1 (2023-01-17).
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814138

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
