### ISSUE TITLE
FNX-5349 ⁃ Tap on QR scanner should close the keyboard

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1954]
## Steps to reproduce
* Open Fenix and tap in the address bar
* tap the scan button

### Expected behavior
* full screen camera

### Actual behavior
* keyboard covers part of the camera area

### Device information
* Android device: Pixel 3 and Pixel 2 XL
* Fenix version: April 23

**Comment by vesta0** [comment]
Keyboard should be hidden once camera is launched.

**Comment by kbrosnan** [comment]
Not fixed when first granting the permission. Pixel 3 and Galaxy S6 using 47c04de886d957e8c2be41d36efc10f76e8bd09f which has the fix from @sblatz

**Comment by Lululalu** [comment]
Opening the QR code Scanner doesn't show the keyboard for me, but it also doesn't perfectly fit the screen, it has black bars to the left and right. Also, leaving the app with the scanner opened and going back triggers the keyboard again.

**Comment by sv-ohorvath** [comment]
Fixed in nightly 5/2. New issue found: #2232.
