### ISSUE TITLE
[Bug]Pages can be added to collections from private browsing 3dotmenu

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#19544]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open a page in private browsing.
2. Open the 3dotmenu.
3. Search for/ Tap on "Save to collection".

### Expected behavior
The option is not available for pages opened in private browsing. 

### Actual behavior
The option is displayed and the pages can be added to collections.

### Device information
* Device vendor / model and Android version: all
* Firefox for Android version: Nightly 5/18, Beta 89.0.0-beta.8.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the:
- latest Nightly 96.0a1 (2021-11-18T05:12:10.153302).
- latest Beta (95.0.0-beta4).
- latest Release (94.1.2).
Device used: Xiaomi Mi11 (Android 11).

Closing the ticket as fixed
