### ISSUE TITLE
[Bug] The credit card expiration date is not auto-filled 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19559]
## Steps to reproduce
1. Save a credit card.
2. Access a website and attempt to purchase anything with a credit card.
3. Autofill the CC data in order to make the purchase.
### Expected behavior
The CC data is correctly imported.
### Actual behavior
The credit card expiration date is not auto-filled 
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/13.**
<img src =        https://user-images.githubusercontent.com/42831109/118787999-039d9500-b89c-11eb-9784-ab5937d495c4.png                      width = 45%>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10727)

**Comment by cpeterso** [comment]
The corresponding Jira issue: https://mozilla-hub.atlassian.net/browse/FNXV2-10727

**Comment by Alexandru2909** [comment]
This seems to be a GV issue, as debugging shows that we send back to GV the correct autocomplete information. This issue only occurs on sites like https://checkout.stripe.dev/ and https://www.instant-gaming.com/, but not on https://fill.dev/form/credit-card-simple.

Opened a bugzilla [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1795046) for this. However this may just be the cc heuristic not recognizing the expiry date field, as mentioned [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1775063#c1).

**Comment by cpeterso** [comment]
> This issue only occurs on sites like https://checkout.stripe.dev/ and https://www.instant-gaming.com/, but not on https://fill.dev/form/credit-card-simple.

Does CC autofill work correctly on these sites in desktop Firefox?

**Comment by Alexandru2909** [comment]
CC autofill seems to work fine in desktop for these sites, it also fills the expiry dates.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813589

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
