### ISSUE TITLE
[Bug][Telemetry][V88.*] BuildID of v7a build in Telemetry is different from the one shown in Fenix About Page

### ISSUE THREAD

**Issue by bli-mozbj** [mozilla-mobile/fenix#19557]
## Info
Mozillaonline build 
v7a build
88.1.1 & 88.1.2 & 88.1.3

The buildid in telemetry is different from what we see in Fenix about page.

![builid_telemetry_Fenix](https://user-images.githubusercontent.com/25242209/118778453-b1b93700-b8bc-11eb-8196-5dc9f39db1e7.png)

### Expected behavior
The buildids in telemetry and Fenix about page are the same.

**Comment by lobontiumira** [comment]
Hi @bli-mozbj 
I was not able to reproduce this issue. 
I've tested on the 88.1.3 build, and on 88.1.4 build, with OnePlus 5T (Android 10) (arm64-v8a), and Sony Xperia Z5 Premium (Android 7.1.1) (armeabi-v7a).
I've installed the builds from https://github.com/mozilla-mobile/fenix/releases, and from PlayStore.
All the builds had the same app build version on Glean (telemetry), and on About pages.

Could you retest on the latest version, RC 88.1.4?
Thank you!

**Comment by bli-mozbj** [comment]
Hi @lobontiumira，
This issue is on MozillaOnline build, not the one from github or Google Play.
Using  metrics_distribution_id = 'MozillaOnline' as a filter, and if you need MozillaOnline build, pls let me know.

**Comment by l-hedgehog** [comment]
Hi @badboy, I think this might be an unintended consequence of #18230 ?

**Comment by badboy** [comment]
Glean uses `BuildConfig.VERSION_CODE`, as we assume that is correctly set during the build.
How _does_ Fenix determine the build ID that is shown?

**Comment by l-hedgehog** [comment]
@badboy I think this is [the code](https://github.com/mozilla-mobile/fenix/blob/v89.1.1/app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt#L92-L127).

I'm mostly wondering when building [these four variants](https://github.com/mozilla-mobile/fenix/blob/v89.1.1/app/build.gradle#L180-L188), whether the auto-generated `GleanBuildInfo.kt` would be recreated everytime, or the one from the first variant might be cached.

**Comment by badboy** [comment]
If the generated code doesn't work for Fenix because of this they could pass their own object instead of a generated one.
All the Glean plugin generates is essentially this:

```
internal object GleanBuildInfo {
    val buildInfo: BuildInfo by lazy {
        BuildInfo(
            versionCode = BuildConfig.VERSION_CODE.toString(),
            versionName = BuildConfig.VERSION_NAME
        )
    }
}
```

If `buildInfo` is _not_ passed to `Glean.initialize` Glean will still fallback to using `applicationContext.packageManager.getPackageInfo` to get that information (however, it's marked deprecated and might thus need an annotation in Fenix code to not break the build).
From your linked code it looks like that's what `populateAboutHeader` also does, so you could use that too.
