### ISSUE TITLE
"Adjust" product name should be a placeholder in string

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/fenix#19550]
We noticed that "Adjust" product name should not be translatable for localizers in this string: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/values/strings.xml#L451
This should probably be replaced by a placeholder since this is a product name.
CC @amedyne

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10721)

**Comment by Delphine** [comment]
Seems like this is still an issue, [string](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/res/values/strings.xml#L553) here.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810594

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
