### ISSUE TITLE
Bookmark re-order

### ISSUE THREAD

**Issue by iamthelara** [mozilla-mobile/fenix#19561]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Who will benefit from it?

Hey, I appreciate your work towards this fork and i haven't checked if this already posted or not.
But it's needy feature. hopefully we see this next update. 

Thank you.

**Comment by sflorean** [comment]
@iamthelara thank you for filing this! as @cadeyrn mentioned, issue #4348 is covering this request. Please follow the discussions/updates there. Closing as duplicate.
