### ISSUE TITLE
FNX-5351 ⁃ [Bug] "Open tabs" label is obscured by hamburger and + icons in RTL language direction

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1956]
## Steps to reproduce
1. Enable "Force RTL layout direction" in Android Settings > System > Developer options (a little over half way down the long list of menu items).
1. Open Fenix's home screen.

### Expected behavior
The "Open tabs" label should appear on the right side of the screen.

### Actual behavior
The "Open tabs" label is still on the left side of the screen and is covered up by the hamburger menu and :heavy_plus_sign: icons, which have correctly moved from the right to the left side of the screen.

### Device information
* Android device: Moto G5
* Fenix version: 1.0.1917 (Build # 11131208) Tuesday 4/23 @ 12:08 PM

**Comment by cpeterso** [comment]
Here is a screenshot:

![Screenshot_20190423-164249](https://user-images.githubusercontent.com/629193/56622990-2559be80-65e7-11e9-89ad-c81cd32b3b09.png)

**Comment by ekager** [comment]
No longer an issue, closing :)
