### ISSUE TITLE
Use SecureFragment for logins screens and other places in the app where content is sensitive.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#19567]
https://github.com/mozilla-mobile/fenix/pull/19560 introduced a `SecureFragment` that can be used for securing specific screen apps. 
We should try to use the same approach in different places of the app where the content needs to be treated as secure.

**Comment by Akshay0701** [comment]
Hello Sir, I would like to take this issue up, can  you please tell me exactly which screens `fragment` are supposed to migrate to `SecureFragment`

**Comment by Alexandru2909** [comment]
Can I work on this?

**Comment by mcarare** [comment]
For QA: Please re-test the logins screens for any regressions regarding these screens being secured. Thank you!

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (2022-01-10).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.
