### ISSUE TITLE
Ensure the full text of the expiry month is visible

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19569]
This came from @violasong 

> I'm sure you already know about this card number bug, but wanted to also mention that ideally we would see the full text for "January (01) "

<img src=https://user-images.githubusercontent.com/1190888/118844662-211d2f80-b899-11eb-90b2-028d85a018a7.jpg width = 45%>

**Comment by abodea** [comment]
Verified as fixed on latest **Nightly 5/27** with **OnePlus Nord (10).**
