### ISSUE TITLE
White text/icons on white status bar with PWAs when dark mode is enabled.

### ISSUE THREAD

**Issue by kolgza** [mozilla-mobile/fenix#19572]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Install the Twitter PWA by from https://mobile.twitter.com
2. Turn on Battery Saver (this colors the battery icon orange, making this easier to demonstrate)
3. Open the Twitter PWA.

### Expected behavior
In dark mode, the device status bar is dark with white text/icons.

The following screenshots show PWAs appear in light mode:
- https://user-images.githubusercontent.com/46303203/118877571-9b12e000-b8bc-11eb-97f5-95beb3162b3a.png
- https://user-images.githubusercontent.com/46303203/118877692-bda4f900-b8bc-11eb-8bd4-aba9d45b82a7.png

### Actual behavior

In dark mode, both the status bar and status bar icons are white.

The following screenshots show demonstrate this behavior for the same PWAs as above.
- https://user-images.githubusercontent.com/46303203/118878335-723f1a80-b8bd-11eb-8437-052ec9772f85.png
- https://user-images.githubusercontent.com/46303203/118878477-9864ba80-b8bd-11eb-8307-607df2f0390b.png

The PWA for [https://lemmy.ml](lemmy.ml) appears  to **not** have this issue:
- https://user-images.githubusercontent.com/46303203/118878687-d2ce5780-b8bd-11eb-9b2d-44133b7b53d4.png

### Device information

This issue has occurred for me across multiple Android devices, Android versions, and Firefox versions.

* Device: Google Pixel 4a 5G
  * Android Version: S
  * Firefox for Android Version: 88.3 (Build #2015808507)
* Device: Essential PH-1
  * Android Version: 10
  * Firefox for Android Version: 90.0a1 (Build #2015810763)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10739)

**Comment by Caspy7** [comment]
I have experienced this as well on my device (OnePlus 7T)

**Comment by Caspy7** [comment]
I tested https://lemmy.ml and also do not see the issue there, but I installed news.google.com and *do* have the issue with it.

**Comment by kolgza** [comment]
I tested this on another person's phone because I wondered if the issue was related to any custom settings.

This time, I enabled dark mode from within the app settings, instead of system-wide. Otherwise, this is included a fresh installation of Firefox. I have not managed to test this on a fully wiped Android phone (and I don't intend to), but I hypothesize the issue would persist.


- Device: Pixel XL
  - Android Version: 10
  - Firefox for Android Version: 88.1.3 (Build #2015808507)

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the 5/20 Nightly build with OnePlus 5T (Android 10):
![Untitled](https://user-images.githubusercontent.com/40694158/118951791-0d8acb00-b964-11eb-8d5d-3bb17b770cdc.png)

**Comment by astarq** [comment]
Also reproducible on Nightly build #2015812105, Android 10 (One UI 2.5), with the [Cryptee](https://crypt.ee/home)  PWA
![Screenshot_20210523-230026_Firefox Nightly](https://user-images.githubusercontent.com/63871973/119278073-ef9ac000-bc1a-11eb-9fd4-438f9f6672db.jpg)

**Comment by astarq** [comment]
Also reproducible in the Pinterest PWA (pinterest.com):
![Screenshot_20210523-235350_Firefox Nightly](https://user-images.githubusercontent.com/63871973/119279232-3f30ba00-bc22-11eb-8d84-bcf876ee46f7.jpg)

**Comment by astarq** [comment]
Any update on this issue? 
The majority of PWA's, including Instagram and Telegram, are now affected by it.

**Comment by intrnl** [comment]
#20857, #16686 and #12488 seems to report on the same issue

**Comment by lagset** [comment]
I can confirm that I have these issues as well for twitter and instagram PWAs on a Pixel 3a on both Android 11 and 12 with dark theme enabled.

It does not appear on less popular PWAs, like e.g. saturn.de or mediamarkt.de (both part of a popular german tech retailer with online shop).

**Comment by barackenkumpel** [comment]
Same Issue on Firefox Daylight 95.2.0., Android 10. Very annoying ...

**Comment by Blaze-Thunder** [comment]
This bug need to be fixed as it's destroying pwa experience.

**Comment by Jrawke** [comment]
Please fix

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by sha-265** [comment]
Confirmed on 107.0b4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807419

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
