### ISSUE TITLE
[Bug] Fenix using Adjust MUST support user self-service data deletion

### ISSUE THREAD

**Issue by shell1** [mozilla-mobile/fenix#19571]
## User Story
- As a user, I must be able to request deleting all my data.  
- Glean user data is deleted when the user opts out of telemetry in the Fenix client.  
- Since Fenix is also using Adjust - the Fenix client needs to call the Adjust gdprForgetMe" function when users opts out of telemetry to also delete any Adjust data. 

"gdprForgetMe" function: "Upon receiving this information, Adjust will erase the user's data and the Adjust SDK will stop tracking the user. No requests from this device will be sent to Adjust in the future."

Information on internal [project shredder](https://mana.mozilla.org/wiki/display/DATA/Shredder)

## Dependencies
-  

### Acceptance Criteria
- When a user opts out of telemetry on Fenix - Adjust also erases the user's data and stops tracking the user.

**Comment by jonalmeida** [comment]
I had a quick look at the work involved. It seems like it's straight-forward enough to just add `Adjust.gdprForgetMe(application)` to the [`AdjustMetricsService.stop`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt#L69) call.

Most of the time needed will be to verify this call is actually working, which is more involved, you need to setup the SDK, build a release APK, etc.

**Comment by jonalmeida** [comment]
I'm not sure if there is a way for QA to verify this change. Putting the label on in case someone else knows how. 🙂

**Comment by amedyne** [comment]
@kbrosnan Can you help find out how to validate this change?

**Comment by amedyne** [comment]
@shell1 Can your team help confirm the change for this? The change has been in Fenix Nightly about a week now.

**Comment by AndiAJ** [comment]
Hi, just a wild guess as we don't have access to Adjust.

The only time I've checked Adjust related telemetry matters was when the `first_session` (formerly known as the `installation` ping) was added [#7295](https://github.com/mozilla-mobile/fenix/issues/7295#issuecomment-595153753) 
In #9136 the `client_id ` was added to the `first_session` ping type.

When the user wants to opt out of telemetry the `deletion-request` ping is generated containing the same `client_id`

Perhaps the check in Adjust could be made based on the `client_id` after the user decides to opt out of telemetry ?

**Comment by shell1** [comment]
Discussed with Shredder team - the call Adjust provided was added to the code to be sent at the right time - so this seems like verification enough.   Thank you!!!!
