### ISSUE TITLE
Identify current misuses of the Dispatchers.Default

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19574]
`Dispatchers.Default` has a known behavior where it can block work from starting because it has a limited thread pool: this becomes a problem if the user is waiting on the results of a blocked task. In general, this makes `Dispatchers.Default` a bad default choice: we should skim our code and look to see if we misuses currently.

Note that in addition to being used explicitly, it is the default argument to many coroutine functions and may be used that way.

**Comment by csadilek** [comment]
Reviewed Fenix and Android Components for both explicit and accidental usage of `Dispatchers.Default`.

In A-C:
- All `CorountineWorkers` not overriding `corountineContext`, in particular `SupportedAddonsChecker` and `WorkManagerSyncManager` are currently using the default dispatcher. Both of those run in the background, off the main thread, to issue network requests and process the results. We should switch to `Dispatchers.IO` for these workers.
- Image scanning in `QrFagment` uses the default dispatcher. This seems fine to me for a CPU-intensive task not on the critical path.

In Fenix:
- `MetricsUtils.getHashedIdentifier` is using the default dispatcher. It's actually causing an unneeded context switch, as its only call site is already from within an IO coroutine. However, this prevents accidental usage of this method on the main thread in case other call sites get introduced. The only usage of this method is for triggering the `ActivationPing`, which only happens once. Therefore, I don't think this is worth changing.
- `FenixApplication` is building up the `BrowsersCache` (list of installed browsers) using the default dispatcher during application startup. As we have a minimum of two threads using `Dispatchers.Default` and this task seems like a good fit, I think it's fine to leave that unchanged.

My recommendation for this ticket is to switch the `WorkManager` workers (see above) over to `Dispatchers.IO` (see above).

**Comment by csadilek** [comment]
Changes landed in A-C. Closing.
