### ISSUE TITLE
Use the dark mode red for "Delete card"

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19570]
This came from @violasong 

> Also, we probably have a dark mode red for "Delete card"

![Screenshot_20210518-131101_Firefox Nightly](https://user-images.githubusercontent.com/1190888/118844812-44e07580-b899-11eb-98ab-5fcdd6d1c389.jpg)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 5/25.
### Devices used:
- OnePlus 6T (Android 9)
- Pixel 3 XL (Android 9)
