### ISSUE TITLE
FNX-5352 ⁃ [Bug] Share is in both the 3 dot menu and in the quick action bar

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1957]
## Steps to reproduce
* Open Fenix
* Load a web page
* Inspect the quick action bar, Share is present
* Inspect the 3 dot menu, Share is present

### Expected behavior
* One entry point to share, similar to bookmarks

### Actual behavior
* Share has multiple entry points

### Device information
* Android device: Pixel 3
* Fenix version: April 23rd

@mheubusch please close if this is as designed.

**Comment by vesta0** [comment]
@lime124 would be great to have UX feedback on whether we want to have "share" in both menus (3 dot and QAB) and if so, should this also apply to add Bookmarks -  or otherwise, remove Share from the 3dot menu.

**Comment by lime124** [comment]
@topotropic FYI @apbitner as the QAB study may impact this decision as well.

**Comment by apbitner** [comment]
Hopefully the QAB study will help with this. We're asking the user to share a page but we're not telling them how, so it'll be interesting to see how many use the menu vs the QAB.

**Comment by topotropic** [comment]
> Hopefully the QAB study will help with this. We're asking the user to share a page but we're not telling them how, so it'll be interesting to see how many use the menu vs the QAB.

Not sure if we get clear results out of it because the QAB is a new interaction paradigm and people are used to go to the menu to access share, bookmark... so I'd guess most people go to the menu when not prompted. 
I think if the study shows that the general discoverability of the QAB is good we should remove it from the menu. Curious to see the results!

**Comment by mheubusch** [comment]
let's leave this as is for now - the redundant navigation is helpful while the discoverability of QAB gets worked out.
