### ISSUE TITLE
Add cookie managers to recommended add-ons

### ISSUE THREAD

**Issue by bege10** [mozilla-mobile/fenix#19573]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I tested cookie managers in Firefox Nightly and they work but they are missing in recommended add-ons

### Who will benefit from it?
Everyone using cookie managers

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10740)

**Comment by PandoraHayami** [comment]
Now that Firefox Desktop has improved on Cookie protection, and knowing that Fenix doesn't have a Cookie manager, this is seriously needed.

**Comment by cadeyrn** [comment]
> Now that Firefox Desktop has improved on Cookie protection, and knowing that Fenix doesn't have a Cookie manager, this is seriously needed.

How is this related? 🤔 There is #18175 for Total Cookie Protection in Fenix. It has nothing to do with a cookie manager add-on though.
