### ISSUE TITLE
Try out Macrobenchmark library for start up benchmarking (and dropped frame performance)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19576]
Google release the 1.1.0-alpha02 version of the macrobenchmark library recently: https://developer.android.com/studio/profile/macrobenchmark It allows you to measure start up performance. It seems beneficial because:
- we don't have to maintain our own test framework
- it solves issues we haven't yet (clicking the UI during the test)
- it takes into consideration things that we don't (e.g. OS caching of applications, perf-focused compilation of code (JIT?))

Let's try it out and see how it works for fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10742)

**Comment by mcomella** [comment]
I spent basically all day trying to get the 1.1.0-alpha02 to run unsuccessfully. Here's what I learned:
- we'll need to upgrade the android gradle plugin to 4.2.0 to use their build.gradle configuration verbatim: `androidComponents` isn't available until then (though the specific lines seem optional)
- with AGP 4.2.0, we'll need to migrate from kotlin-android-extensions #17917 OR upgrade to kotlin 1.5.0 here and in ac because it forces the android extensions to kotlin 1.5.0 (maybe we could explicitly specify the k-a-e version to avoid this?)
- it's recommended to use AS from the Beta channel (Arctic Fox 2020.3.1 or something); I wasn't able to run their sample without it

I couldn't get it running because:
- on debug builds, I get "no logcat from device"
- on nightly builds, I get `Failed resolution of: Lkotlin/collections/CollectionsKt;` – it seems proguard is removing some necessary classes

I was able to run their [macrobenchmark sample](https://github.com/android/performance-samples/tree/main/MacrobenchmarkSample) project but I'm unable to see what's different between that project and fenix.

---

We should figure out if we should invest more time to get it working in the short term (and possibly deal with additional bugs) or wait until it's in a more advanced state of release (beta? stable?).

**Comment by mcomella** [comment]
Here's my WIP for the day: https://github.com/mcomella/fenix/tree/host-macrobenchmark

**Comment by mcomella** [comment]
Stand-up: MarcLeclair agreed we should wait, especially until it supports lower API level devices.

**Comment by mcomella** [comment]
We plan to integrate microbenchmark in https://github.com/mozilla-mobile/fenix/issues/19901 – perhaps that'll make this easier.

**Comment by mcomella** [comment]
Sending back to triage because ^ microbenchmark is integrated.

**Comment by mcomella** [comment]
Triage: keep open b/c there is useful info in the bug if we implement this later.

**Comment by mcomella** [comment]
Triage: the perf test team is prioritizing this work to start in H2. Putting in Waiting column so we remember to follow-up.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807324

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
