### ISSUE TITLE
Adapt widget for Android 12

### ISSUE THREAD

**Issue by Dunexus** [mozilla-mobile/fenix#19583]
### What is the user problem or growth opportunity you want to see solved?
Android 12 comes with [some modifications on the Widgets API](https://developer.android.com/about/versions/12/features/widgets).
- [Enforced rounded corners](https://developer.android.com/about/versions/12/features/widgets#ensure-compatibility) : this one is the most critical as it may cut parts of the current widget and break its design
- [API for dynamic colors](https://developer.android.com/about/versions/12/features/widgets#dynamic-colors) : this need UX feedback to decide if this is something we want or not (ie. keep colors bounded to app theme or let users choose a custom color scheme to match their homescreen)
- [Responsive design](https://developer.android.com/about/versions/12/features/widgets#refine-widget-sizes) : could help with issues such as https://github.com/mozilla-mobile/fenix/issues/9323
- [Scalable widget preview](https://developer.android.com/about/versions/12/features/widgets#add-scalable-widget-previews)
- [Add widget description](https://developer.android.com/about/versions/12/features/widgets#add-widget-description) 

This issue may be used as a UX discussion thread and be broken into smaller issues based on UX team decisions on what we want to implement.

### How do you know that this problem exists today? Why is this important?
Android Widget API get some changes with Android 12 we should take into account to target A12 and be future-proof.

### Who will benefit from it?
Android 12 users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10746)

**Comment by rokejulianlockhart** [comment]
I believe that all of what has been proposed should be implemented. Branding considerations should be moot, considering that almost every widget ignores this to assist consistency, and because of the obvious negative effect of mandating arbitrary colouration that does not conform to what the OS mandates.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807578

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
