### ISSUE TITLE
[Bug] ETP not working properly on first page load

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#19584]
## Prerequisites
Have a fresh install or a clean profile.

## Steps to reproduce
1. Open https://senglehardt.com/test/trackingprotection/test_pages/fingerprinting_and_cryptomining_and_cookies.html
2. Check if the trackers are blocked

### Expected behavior
Fingerprinting should be blocked
Cryptomining should be blocked
Cookies Basic List should be blocked 

### Actual behavior
Fingerprinting are not blocked
Cryptomining are not blocked
Cookies Basic List are not blocked

### Device information

* Device vendor / model and Android version: all
* Firefox for Android version: 
► Fenix Nightly
► Reference Browser
► Focus

**Comment by Amejia481** [comment]
I remember this is a known issue, I will try to find the initial issue and link it to this. If I remember correctly it takes some time for GV to fetch the blocking list, leading to this issue.

**Comment by Amejia481** [comment]
Better late than never, 😄  it wasn't easy to find the bug  https://github.com/mozilla-mobile/fenix/issues/7907

**Comment by kbrosnan** [comment]
Closing as duplicate
