### ISSUE TITLE
Manually test the site permissions new GV API integration

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#19587]
It will be ideal if the QA team could help us to do a round of manual tests to discovered any possible issues early, site permissions before integrating it. Related ticket https://github.com/mozilla-mobile/android-components/issues/9391.

Here the custom [APKs](https://drive.google.com/file/d/1Zkks0ga32OZRFsTfYoPS6wimGL-W466V/view?usp=sharing) with the integration.

Some tools for manual testing: 
* Website to simulate site permissions request https://permission.site/ 
*  Related Fenix PR https://github.com/mozilla-mobile/fenix/pull/19553/ 
* [The Database Inspector In Android studio](https://developer.android.com/studio/inspect/database)
* Site permission status DB values `BLOCKED(-1), NO_DECISION(0), ALLOWED(1)`

I think we could cover the follow test cases:

1) With a clean install check you are able to allow/deny permissions.
When you check the checkbox allowing/denying permission must be persistented,  content permissions **(Notification,Location, Media key access, local storage, auto play Audible, and auto play in Audible)** should not be store in the db while media  permissions (**microphone and camera**) should be store in the DB.

2) After updating permissions (In the doorhanger) content permission should now be in the DB while media permission should be updated in the DB.

3) Updating permissions from the Settings -> Site permissions -> Exceptions page should update the permission on the next request, content permissions should not be updated in the DB while media permissions should be.

4) Removing individual permissions from the Settings -> Site permissions -> Exceptions page, clear any permissions.

5) Removing all permissions from the Settings -> Site permissions -> Exceptions page, clear all permissions.

6) Testing temporary site permissions that happen when permissions are allowed/granted without checking the checkbox, 
only location, camera and microphone have the checkbox.  temporary permissions are not persistent and get cleared out when reloading the page or navigating away.

7) Simulated previous stored permissions get migrated to the GV storage. This can be done by manually adding 
a site to db  `INSERT OR REPLACE INTO site_permissions (`origin`, `location`, `notification`, `microphone`, `camera`,`bluetooth`,`local_storage`,`autoplay_audible`,`autoplay_inaudible`,`media_key_system_access`,`saved_at`)  VALUES ('permission.site', 0, 0, 0, 0,0,0,0,0,0,0);`, this task can be easily done with [the Database Inspector In Android studio](https://developer.android.com/studio/inspect/database), when a new permission request is completed, then the permission should be migrated to the GV store and a default value is set for the spesific permissions.

Please feel free to add any tests case that I may missed.

**Comment by LaurentiuApahideanSV** [comment]
We tested the test cases and these are your results.
1. Content permissions always have the value 0 even when the "Remember decision" checkbox is ticked, media permissions also have the value 0 until the "Remember decision" checkbox is ticked after which they will be 1 or -1 depending if the permission was granted or not. Granting any permission will set the autoplay_audible, and autoplay_inaudible to -1 in the Android Studio Database Inspector until they are changed in the Autoplay option.

2. After updating permission in the doorhanger content permissions always have the value 0 and media permissions will update to 1 or -1 depending if they are blocked or allowed.

3. I was able to change the value of the location and notification to 1 and -1 by performing the following steps:
- Launch Firefox and grant allow to all Android System permissions.
- Go to a website that you visit for the first time that also requires media permissions, such as talky.io.
- Grant access to Camera or Microphone permission.
- Go to Settings -> Site permissions -> Exceptions page.
- Select the website that you granted media permissions to and modify the Location or Notification permissions to Allowed or Blocked.
Expected result 
Content permissions should remain as 0 and not be updated in the DB
Actual result
Content permissions change to 1 or -1 depending if they are Allowed or Blocked.

4. Removing individual permission resets them to 0.

5. Removing all permissions will remove all entries from the Android Studio Database Inspector.

6. Temporary site permissions do not create entries in the Android Studio Database Inspector and the permissions are requested again.

7. After manually entering an entry for several websites that were never visited before permissions are no longer requested Video, Audio and Location services will start without requesting permissions if they are set to 1, if the they are set to -1 permissions are blocked and no message is displayed.

**Comment by Amejia481** [comment]
Thanks @LaurentiuApahideanSV

**Comment by Amejia481** [comment]
> 
> 3    I was able to change the value of the location and notification to 1 and -1 by performing the following steps:
> 
>     Launch Firefox and grant allow to all Android System permissions.
>     Go to a website that you visit for the first time that also requires media permissions, such as talky.io.
>     Grant access to Camera or Microphone permission.
>     Go to Settings -> Site permissions -> Exceptions page.
>     Select the website that you granted media permissions to and modify the Location or Notification permissions to Allowed or Blocked.
>     Expected result
>     Content permissions should remain as 0 and not be updated in the DB
>     Actual result
>     Content permissions change to 1 or -1 depending if they are Allowed or Blocked.

In this case, this is the expected behavior sorry for not mentioning it before, when we add a permission for example **Camera** other permissions values like location .. notification they take a default value. Users are able to modify Content permissions via Settings -> Site permissions -> Exceptions page,  in the DB until the permission is requested for  a web content, then the permission will take a default value in the DB and will be updated in the Gecko Storage.

**Comment by LaurentiuApahideanSV** [comment]
I have rechecked the issue on the debug build and the issues is fixed.
### Devices used:
- Google Pixel 3XL (Android 9)
- OnePlus 6T (Android 9)

**Comment by Amejia481** [comment]
Thanks @LaurentiuApahideanSV we can close this ticket, thanks for all the help!
