### ISSUE TITLE
FNX-5354 ⁃ [Bug] Quick action bar icons not displayed on first run

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1959]
## Steps to reproduce
1. Open a fresh install of Fenix.
1. Go to any webpage.
1. Observe the Quick Action bar.

### Expected behavior
The Quick Action bar is displayed with all of its available options.

### Actual behavior
There are no icons displayed in the Quick Action bar, the animation starts before the keyboard is dismissed making it very easy to miss.

### Device information
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * HTC 10 (Android 8)
  * Google Pixel (Android 9)
* Fenix version: 1.0.1917 (#11131208)

![gif](https://user-images.githubusercontent.com/17178945/56645518-808ebe00-6686-11e9-8982-d8a17504a3a5.gif)

**Comment by ekager** [comment]
This should have been fixed in #1927 but this may not have been included in the build you were testing. Is this still happening in the most recent Nightly?

**Comment by bsurd** [comment]
@ekager No this has been fixed in the latest build. Closing the issue.
