### ISSUE TITLE
Measure Chrome start up performance as a baseline

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19592]
We should find a lightweight way to measure Chrome's start up performance. For example:
- take a video and count frames
- use Android's time to first frame
- use Android's time to fully drawn (if they implement it)
- (too much noise, uncertainty?) use browsertime's internal metrics

We should do this in a few different ways (to homescreen, to page load, etc.).

We should document that duration once (i.e. don't keep remeasuring it) and **use it as an ongoing baseline metric of, "How are we doing on start up performance?"**. We can compare it to our ongoing values (whichever one is most comparable).

**Comment by ZagButNoZig** [comment]
This could also be used to measure page load time, which would also be useful.
