### ISSUE TITLE
Allow installing add-ons also in stable version/beta from custom collection as in Nightly

### ISSUE THREAD

**Issue by bege10** [mozilla-mobile/fenix#19594]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
To install add-ons like cookie managers I must use Nightly although I'd prefer the stable version or beta. Because cookie managers are supported in Nightly they soon should be supported in beta and stable also.

### How do you know that this problem exists today? Why is this important?
Add-ons were beside privacy one of the main reasons why I came to Firefox. Fenix has very poor support for add-ons. I don't want to use Nightly to use more add-ons

### Who will benefit from it?
Most Firefox users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10755)

**Comment by Mikaka27** [comment]
It would be good to have, but in the meantime you could use fennec from f-droid store. It is essentialy firefox stable with about:config enabled and addons collections also enabled.

**Comment by bege10** [comment]
Thank you very much, that is interesting news. I have these questions:
- Who maintains Fennec, all links in F-Droid go to Fenix pages?
- I saw that Fennec is at 88.1.3, Fenix at 88.1.4. Is there a regular delay for updates?
- I'd like to transfer the data from Fenix Nightly to Fennec. Is it possible on a rooted phone to copy the data or will that crash? (I already know that I must delete logins.sqlite when I restore Fenix Nightly data.)


----------------------------------------

> It would be good to have, but in the meantime you could use fennec from f-droid store. It is essentialy firefox stable with about:config enabled and addons collections also enabled.

**Comment by Mikaka27** [comment]
- I'm not sure who that is, if you look here: https://gitlab.com/fdroid/fdroiddata/-/commits/master?utf8=%E2%9C%93&search=fennec you can see that someone nicked "relan" does this, but I don't know who that is
- Yes there is some delay in updates
- Not sure if that's possible, sorry I'm just a regular user

**Comment by leo60228** [comment]
Could this at least be supported on Beta? I find nightly too unstable for daily use.

**Comment by sheikh-azharuddin** [comment]
This feature must me added to the beta release.
I find nightly browser is getting unstable...crashing here and there or site issues...instead of fixing bugs seems Mozilla when fixing one bug introducing 10 other bugs so I want to use firefox beta but there is no custom add on support..

**Comment by yan12125** [comment]
From https://github.com/mozilla-mobile/fenix/issues/26948,

> Support for extension collections in Beta should become available in Firefox Beta 107.0 b1 (2022-10-17).

:tada: :tada: :tada:

**Comment by kelimuttu** [comment]
See also: https://github.com/mozilla-mobile/fenix/issues/20736

**Comment by cpeterso** [comment]
This limitation will be fixed by Fenix support for MV3 extensions: https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

**Comment by rokejulianlockhart** [comment]
@cpeterso, how did you so entirely misinterpret this feature request? It's incredible.

Your linked article does not in fact remediate this problem whatsoever.

**Comment by vehosah** [comment]
> This limitation will be fixed by Fenix support for MV3 extensions: https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

And what the heck your article has to do with the issue, because it only mentions new extensions are now available in nightly :/

**Comment by iTob191** [comment]
The linked article states:
> By following these [instructions](https://support.mozilla.org/en-US/kb/how-use-collections-addonsmozillaorg?utm_source=blog.mozilla.org&utm_medium=post&utm_content=expanded-extension-support-in-firefox-for-android-nightly) you can now create your own custom extension collections on Firefox for Android Beta (previously, collections were only available on Nightly). [...]

As far as I understand, that's exactly what this issue is about. Also, I'm on Beta (109.0b6) and I'm able to configure a custom addon collection.

**Comment by cadeyrn** [comment]
> And what the heck your article has to do with the issue, because it only mentions new extensions are now available in nightly :/

If you read more than only the headline you will notice that the article is **not** only about new extensions in Nightly. Especially the last paragraph is important:

> In 2023 we’ll begin work on the mobile adoption of MV3. Though we’re still early in planning, MV3 will certainly offer a number of advances for mobile extensions, such as elegant handling of process restarts and improved security by splitting extensions into their own processes, while also retaining critical MV2 features that support privacy and ad blocking capabilities. Indeed our goal is to design MV3 for mobile in such a manner we’re able to open up the discoverability of mobile extensions beyond the short list available today. As plans take shape, we’ll be sure to keep you informed. 

And it's really not a secret that they're working on a "general availability" of add-ons for Android, see https://bugzilla.mozilla.org/show_bug.cgi?id=1796184 and dependencies. It was already mentioned on several issues.

**Comment by vehosah** [comment]
> > And what the heck your article has to do with the issue, because it only mentions new extensions are now available in nightly :/
> 
> If you read more than only the headline you will notice that the article is **not** only about new extensions in Nightly. Especially the last paragraph is important:
> 
> > In 2023 we’ll begin work on the mobile adoption of MV3. Though we’re still early in planning, MV3 will certainly offer a number of advances for mobile extensions, such as elegant handling of process restarts and improved security by splitting extensions into their own processes, while also retaining critical MV2 features that support privacy and ad blocking capabilities. Indeed our goal is to design MV3 for mobile in such a manner we’re able to open up the discoverability of mobile extensions beyond the short list available today. As plans take shape, we’ll be sure to keep you informed.
> 
> And it's really not a secret that they're working on a "general availability" of add-ons for Android, see https://bugzilla.mozilla.org/show_bug.cgi?id=1796184 and dependencies. It was already mentioned on several issues.

We know how to fucking read, thank you very much, they don't mention where this mv3 will be, stable, nightly or beta, because for the time being we are on the damn dark :)

**Comment by vehosah** [comment]
> > And what the heck your article has to do with the issue, because it only mentions new extensions are now available in nightly :/
> 
> If you read more than only the headline you will notice that the article is **not** only about new extensions in Nightly. Especially the last paragraph is important:
> 
> > In 2023 we’ll begin work on the mobile adoption of MV3. Though we’re still early in planning, MV3 will certainly offer a number of advances for mobile extensions, such as elegant handling of process restarts and improved security by splitting extensions into their own processes, while also retaining critical MV2 features that support privacy and ad blocking capabilities. Indeed our goal is to design MV3 for mobile in such a manner we’re able to open up the discoverability of mobile extensions beyond the short list available today. As plans take shape, we’ll be sure to keep you informed.
> 
> And it's really not a secret that they're working on a "general availability" of add-ons for Android, see https://bugzilla.mozilla.org/show_bug.cgi?id=1796184 and dependencies. It was already mentioned on several issues.

Did someone ask your damn opinion?

**Comment by vehosah** [comment]
> > This limitation will be fixed by Fenix support for MV3 extensions
> 
> so fenix will get full extension support only for mv3 extensions, and not mv2 ?

We don't know that, we don't even know what they do behind our backs :)

**Comment by vehosah** [comment]
> This limitation will be fixed by Fenix support for MV3 extensions: https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

Can you please explain a little bit better, cause we don't understand?

**Comment by kevincox** [comment]
Let's keep things civil. I think there are a few main questions here.

1. This was closed with reference to https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/. Is that because it is coming to stable soon (it is in the release pipeline). Or was the closure a mistake.
2. https://bugzilla.mozilla.org/show_bug.cgi?id=1796184 was referenced. Is it intended that that bug supersedes this one? Should we be following there instead, or show this be re-opened to track that?
3. Will Fenix get support for MV2 or just MV3?

**Comment by vehosah** [comment]
> > This limitation will be fixed by Fenix support for MV3 extensions: https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/


> This limitation will be fixed by Fenix support for MV3 extensions: https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

In other words: we won’t tell you why you should trust us, just trust us because we say so.

**Comment by Poopooracoocoo** [comment]
> 3. Will Fenix get support for MV2 or just MV3?

As I understood it, the reply to my comment on that article implies that we won't be able to install non-whitelisted MV2 extensions. Installing non-whitelisted MV3 extensions is _not_ a given. It's not the news any of us wanted to hear, and it sounds like nothing in the way of documentation is coming to console us because that wasn't commented on either. [A Reddit comment](https://www.reddit.com/r/firefox/comments/zmsams/comment/j0d92ph) is not acceptable. The comment doesn't go into much detail either, and doesn't mention why it won't bring the workaround of using custom collections found to "release" versions. No information has been given on whether our own add-ons via XPIs can be installed either

**Comment by sheikh-azharuddin** [comment]
Final verdict if one wants to use custom add ons switch to beta or nightly but don't expect in stable , they will never add it
Coming to recent developments all I see aesthetic related changes text align, pocket stories, refactor this into that etc.. I don't understand why they are not taking up the issues which are critical - for example push notifications are broken ( clicking notification opens firefox only) , media advance notification are missing (seems like using Android 6 interface)

**Comment by cadeyrn** [comment]
> Will Fenix get support for MV2 or just MV3?

Does that really matter? In the long term every add-on has to be a MV3 extension anyway. Even if they only allow MV3 extensions it will expand the availability from few to hundreds of add-ons once they are ready. That's a really big step. And note: MV3 add-ons for Firefox don't have all the same restrictions as MV3 add-ons for Chrome. So there is no reason for add-on developers not to update their MV2 extensions (except for time, maybe, but if you don't have a really complex add-on and just do the minimum required changes it's really easy doable).

> As I understood it, the reply to my comment on that article implies that we won't be able to install non-whitelisted MV2 extensions.  Installing non-whitelisted MV3 extensions is not a given.

"General availability" means that you can not only install "whitelisted" add-ons in the future. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1796189 which is explict about non-recommended add-ons.

> and doesn't mention why it won't bring the workaround of using custom collections found to "release" versions.

Custom collections were a workaround for pre-release versions to install and test non-whitelisted add-ons. With the planned general availability there is no longer a point for users in having custom collections. For this reason it doesn't make sense to enable this in stable releases as they are already working on the general availability. If you follow the tickets on Bugzilla you will notice that there is a lot of recent activity around add-ons for Android. As you know are Fenix issues being tracked on Bugzilla now.

**Comment by leo60228** [comment]
My understanding is that the ability to install MV2 extensions on Fenix in
any capacity is considered a hack, and custom add-on collections being
extended to stable is extremely unlikely. It's already been extended to
beta (which was half of the request in this issue), and once MV3 rolls out
it should be possible to install add-ons on stable without any workarounds.

**Comment by Poopooracoocoo** [comment]
>>As I understood it, the reply to my comment on that article implies that we won't be able to install non-whitelisted MV2 extensions. Installing non-whitelisted MV3 extensions is not a given.
>
>"General availability" means that you can not only install "whitelisted" add-ons in the future. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1796189 which is explict about non-recommended add-ons.

I was only referencing the reply to my comment on the article. "However these plans are not firmly established yet and it would be premature to lay them out now. We’ll certainly share the mobile development timeline as it clarifies." suggests that GA of MV3 extensions are _not_ a given. 

>>and doesn't mention why it won't bring the workaround of using custom collections found to "release" versions.
>
>Custom collections were a workaround for pre-release versions to install and test non-whitelisted add-ons. With the planned general availability there is no longer a point for users in having custom collections. For this reason it doesn't make sense to enable this in stable releases as they are already working on the general availability. If you follow the tickets on Bugzilla you will notice that there is a lot of recent activity around add-ons for Android. As you know are Fenix issues being tracked on Bugzilla now.

That's not an official statement from Mozilla, nor is it official documentation in a SUMO article. Addressing user complaints in a FAQ to simply say why they're not doing something shows that they care. Reddit and GitHub comments are not appropriate communication either. 

I believe that the custom collections workaround for MV2 extensions is ugly but is all we have. It appears that Mozilla does not intend on GA of MV2 extensions. Most extensions are MV2 extensions and many will never be ported (installing our own XPIs is not part of this issue). The technical issues of MV2 extensions are why the release channel should not allow installing non-whitelisted MV2 extensions easily. It's not acceptable to install pre-release software to regain functionality present in older versions and in the desktop version. _But my opinion is not relevant here to my point as my focus was on Mozilla's communication to end users._

**Comment by 424344** [comment]
> Does that really matter?

yes, it matters because there are extensions not developed anymore, so will never get updated to mv3.

**Comment by cadeyrn** [comment]
> yes, it matters because there are extensions not developed anymore, so will never get updated to mv3.

It's extreme unlikeley that there is no alternative if there is really a use case for more than a handful of users and if it's technical possible to do it. But without an example that's very hypothetic.
