### ISSUE TITLE
[Bug] Credit card settings screen has a noticeable blink when it is opened

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#19600]
## Steps to reproduce

Open credit card preference screen

### Expected behavior

There are no visible screen updates.

### Actual behavior

There is a noticeable blink when the credit card list is not empty and the "manage saved cards" option should be visible.

https://user-images.githubusercontent.com/48995920/119145002-e7435900-ba51-11eb-8a37-8bba8e0fcff8.mp4

### Device information

* Device vendor/model and Android version:  All
* Firefox for Android version: latest master

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/26** with **OnePlus Nord (Android 10).**
