### ISSUE TITLE
FNX-5356 ⁃ [Bug] Quick Action bar handle is not displayed

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1960]
## Steps to reproduce
1. Open Fenix.
1. Go to any webpage.
1. Observe the Quick Action bar.

### Expected behavior
There is a handle displayed.

### Actual behavior
There is no handle displayed.

### Device information
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * HTC 10 (Android 8)
  * Google Pixel (Android 9)
* Fenix version: 1.0.1917 (#11131208)

![screen](https://user-images.githubusercontent.com/17178945/56645130-bed7ad80-6685-11e9-8e6c-60b6614dfa2b.png)

**Comment by sblatz** [comment]
This should be fixed on the 4/24 nightly.

**Comment by bsurd** [comment]
Verified as fixed with the build mentioned above.
