### ISSUE TITLE
[Bug] <input type="week"> shows a date prompt over the keyboard

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19619]
## Steps to reproduce
- go to https://www.456bereastreet.com/lab/html5-input-types/
- tap in the "Week" input field and close the first prompt which is correctly shown alone, without the keyboard
- tap in the "Week" input field again.

### Expected behavior
A prompt is shown allowing to enter a specific week.

### Actual behavior
Both a date prompt and the keyboard underneath (unable to interact with) are shown.
A similar situation happens with the "Month" input field but in that case the keyboard opens and is immediately closed.

https://user-images.githubusercontent.com/11428869/119326353-7c309700-bc8a-11eb-8c9b-0807c2ec3e98.mp4

**Comment by makotokato** [comment]
I think that this issue is GeckoView. Unfortunately, we open software keyboard in https://searchfox.org/mozilla-central/rev/67637695876e27ddbfb6ff99202bb1c951de847a/widget/android/GeckoEditableSupport.cpp#1430-1436. I will file this to BMO, then fix this soon.

**Comment by makotokato** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724850

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
