### ISSUE TITLE
FNX-5357 ⁃ [Bug] Page menu Help button not linked

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1961]
## Steps to reproduce
1. Open Fenix and go to any page.
1. Tap on the 3 dot menu.
1. Tap on Help.

### Expected behavior
A sumo help page is opened.

### Actual behavior
A notification to the meta-issue is displayed.

### Device information
* Android device: Nexus 5 (Android 6.0.1)
* Fenix version: 1.0.1917 (#11131208)

**Comment by vesta0** [comment]
The Help page will be built soon.

**Comment by sv-ohorvath** [comment]
The help page is working from Settings. Not linked yet in the main menu.

**Comment by bifleming** [comment]
Story is in progress.
