### ISSUE TITLE
Launch animation of PWA does not match the systemwide launch animation

### ISSUE THREAD

**Issue by botistreamer** [mozilla-mobile/fenix#19610]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Opening animation from bromite (chromium based browser): https://i.imgur.com/7tajqDo.mp4
Opening animation from firefox 88.1.4: https://i.imgur.com/fh3dd1G.mp4

1. Opening PWA from firefox **does not not follow the systemwide animation** (zoom in) and does this sideways animation. 
2. Animation **does not respect "animator duration scale"** set in developers settings. It was set at 2x or 5x(don't remember) for both but the animation for firefox occurs at the same speed regardless of this value.
Note: I am NOT talking about the splash screen that chromium browser adds but rather the opening animation itself.

Both of the above points should match with the system wide behavior.

PWA in question: https://www.covid19india.org/
Device details:
Poco X3, Android 11, Arrow OS ROM
Stock launcher
Firefox 88.1.4

**Comment by Dunexus** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/3597

**Comment by lobontiumira** [comment]
I was able to reproduce the issue on RC 88.1.4, and on RC 89.1.0 with Google Pixel (Android 10).
I could not reproduce it on Samsung Galaxy Note 8 (Android 9), nor on HTC 10 (Android 8).

**Comment by botistreamer** [comment]
Still reproducible on 91.1.0 on Android 11, Poco X3
