### ISSUE TITLE
The icon present in the ETP submenu is not updated

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#19621]
## Steps to reproduce
1. Launch Firefox Preview;
2. Go to Setting -> Enhanced Tracking Protection

### Expected behavior
The blue icon shield should be updated.
### Actual behavior
The blue icon shield is not updated.
### Device information

* Device vendor OnePlus 6T (Android 9), Huawei MediaPad M3 (Android 7.0)
* Firefox for Android version: Firefox Preview 89.0.0-beta.10
![Tracking_Protection_Icon](https://user-images.githubusercontent.com/50983519/119342939-6f1da300-bc9e-11eb-8fc0-4ab2da3e7101.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10768)

**Comment by Amejia481** [comment]
@brampitoyo should this icon be updated?

**Comment by brampitoyo** [comment]
@Amejia481 Yes. We should update this icon. (It was fine that it wasn’t updated as a part of MR1, as it’s hidden fairly deep in the UI).

Would you like me to give you the new resized icon by itself, or was the icon placed within the illustration so we’ll need to update the whole image?

**Comment by Amejia481** [comment]
No problem, we need to update the whole illustration.
<img width="649" alt="image" src="https://user-images.githubusercontent.com/773158/120203989-52312480-c1f6-11eb-956e-6441d21d8a42.png">

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807560

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
