### ISSUE TITLE
FNX-5358 ⁃ [Bug] Some actions in tab view require too many taps

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1962]
## Steps to reproduce
1. Go to tabs view, with some opened tabs.
1. To close all tabs, tap the overflow menu button, tap Delete.
1. To share a tab, tap the overflow menu button, tap share.
    1. Expected behavior
If these would be the only actions available in the overflow menus, it would be easier for the users if the menus are replaced with a single button to do these actions.
![Screenshot](https://user-images.githubusercontent.com/4037709/56646849-0c094e80-6689-11e9-9c06-b403b6fd4100.png)UNITO-UNDERSCORE!20190424-115931!

### Actual behavior
2 taps needed to accomplish one action.

### Device information
* Android device: any
* Fenix version: 4/23

**Comment by AmyYLee** [comment]
The open tabs overflow menu is needed for additional actions that is currently being worked on and we are removing the options menu in tabs.

**Comment by AmyYLee** [comment]
Closing this bug as it's no longer relevant based on updated specs here https://mozilla.invisionapp.com/d/main#/console/16853870/359019534/preview

**Comment by sv-ohorvath** [comment]
> Closing this bug as it's no longer relevant based on updated specs here https://mozilla.invisionapp.com/d/main#/console/16853870/359019534/preview

I can't log in with the original Fenix password. Could you share this with me in private, on slack?
