### ISSUE TITLE
[Bug] There is no confirmation prompt asking if you wanna quit the `Add card` when tapping cancel (if there is data) or when deleting a saved card

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19639]
## Steps to reproduce
1. Access credit cards section and tap on add new card.
2. Introduce data (fill every field) and then tap cancel.
### Expected behavior
There should be a confirmation prompt asking if you really wanna discard the data that you added.
### Actual behavior
If adding all the data for a new card, and there is one number incorrect and tapping by mistake on cancel or back, everything is deleted.
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/25.**

**Comment by amedyne** [comment]
@topotropic Need UX feedback on this. Thanks!

**Comment by topotropic** [comment]
Thanks for filing the issue! 

We currently don't have this confirmation pattern in the app nor on Firefox on other platforms. If people tap on cancel accidentally it might be annoying but the data loss is not irreversible or severe.  I agree that it's not ideal to tap accidentally on cancel but if that happens a lot of times we have a different problem here and need to re-think the save/cancel UI we are using. Let's keep an eye on it but not introduce a prompt.
