### ISSUE TITLE
"Settings -> Login & passwords -> Saved passwords" not showing anything when tapped

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#19635]
We got a report from a user that showed the "Show passwords" setting doing nothing when tapped.

> Firefox 88.1.4
> Android 9

In the video the user shared no screen for authenticating appears.

**Comment by SeburoSUMO** [comment]
Adding link to question in SUMO for further info and background.

https://support.mozilla.org/en-US/questions/1336785

**Comment by mterreni** [comment]
I filed the question. If there is something I can do to help understand the issue please tell me.

**Comment by RomanRiabenko** [comment]
This looks like my issue too. Just installed Fennec from F-Droid today, logged in into the sync account. Bookmarks synced well. Tabs sharing works well. Passwords store is empty. Not synced.

I can login to sites manually and save credentials. They are stored and become available in saved passwords, but they are not synced.

Fennec 89.1.1
Android 11

**Comment by RomanRiabenko** [comment]
I've just installed Firefox 88.1.3 on the same device with the same result.

**Comment by RomanRiabenko** [comment]
I checked on my another Android 11 device  where I have Firefox 81.1.5 from Google Play already installed and configured and I can confirm that it syncs new passwords just fine. Then I took yet another device, which is Android 8.1.0, and tried installing Fennec 89.1.1 from F-Droid and Firefox 89.1.1 from Google Play. Passwords don't sync here either.

**Comment by pocmo** [comment]
@RomanRiabenko Your issue seems different. In the case here the passwords screen can't be opened at all. It seems like you have sync specific problem. Please file a separate issue for that. :)

**Comment by RomanRiabenko** [comment]
@pocmo Sorry, I misunderstood the issue. Recreating the sync account fixed my issue, so I cannot reproduce it for another bug report.
