### ISSUE TITLE
Disable or remove Add-ons feature

### ISSUE THREAD

**Issue by imnotabr** [mozilla-mobile/fenix#19631]
In modifying Fenix, I want to remove the "Add-ons" feature from the menu and the app, but I'm unable to.

How do you remove this feature, or turn it off or hide it? @clauub 

<img width="150" alt="Android Add-ons" src="https://user-images.githubusercontent.com/62814903/119386438-5e5c3580-bc7c-11eb-91d3-f09c69cd9dda.png">

**Comment by kbrosnan** [comment]
There is no way to do that as a user.

**Comment by imnotabr** [comment]
@kbrosnan, my question is how to do it as a _developer_.

**Comment by kbrosnan** [comment]
Issues are for things to be fixed with pull requests. If you want to chat or discuss things then use Element or Discourse https://github.com/mozilla-mobile/fenix/wiki#communication

**Comment by imnotabr** [comment]
Ok. Here is my discussion post if anybody can help

https://discourse.mozilla.org/t/remove-add-ons-feature/80584

**Comment by imnotabr** [comment]
@pocmo Hey Pocmo I had another question about my post you replied to. How do you hide the second Add-on menu option from the longer Fenix menu, not the short default menu? Let me know where I can send you a tip for your help, I really appreciate it!

https://discourse.mozilla.org/t/remove-add-ons-feature/80584/3

**Comment by clauub** [comment]
@imnotabr as a developer, I think the best option is to hide it. That's what I did. To hide Add-ons you go in **HomeMenu** fragment and delete it from there. And there you go
