### ISSUE TITLE
FNX-5359 ⁃ [Bug] Cannot edit wrong urls because the previous search term is displayed instead

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1963]
## Steps to reproduce
1. Type a search term in the search bar.
1. After the search results page is displayed, enter an incorrect URL, i.e. twitter.comm
1. After the error page loads, tap the URL to modify it.
    1. Expected behavior
Can edit the incorrect typed URL.
    1. Actual behavior
Can't edit because the search term from Step 1 is displayed.
*Doesn't reproduce if another URL was introduced in the search bar previously.
    1. Device information

* Android device: Pixel (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/23

**Comment by kbrosnan** [comment]
@sv-ohorvath this should be fixed by #1205 please verify and close if true.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 4/29 build.
