### ISSUE TITLE
[Bug] Synced tab not selected when tabs tray opened from home

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#19647]
## Steps to reproduce
- Log in to FxA and make sure tabs are open on other devices
- Open tabs tray directly from home screen
- Switch to synced tabs
- Open any tab

### Expected behavior
- Tab is opened and selected

### Actual behavior
- Tab is opened in background, unclear to the user if anything happened at all.

**Comment by jonalmeida** [comment]
The added bug is that we do not dismiss the tabs tray as well. We can fix this by just including the `dismissTabsTray` call in `NavigationInteractor`. 

On the original bug, interestingly, it seems like we're calling `openToBrowserAndLoad` correctly, but we are not switching to the browser fragment for some reason.

**Comment by jonalmeida** [comment]
Figured out the issue: the nav graph was still referencing the old tab tray _dialog_ as the "from" address and this affected our transition from home to browser view.

Adding a separate entry for the new tray until we remove the old code in https://github.com/mozilla-mobile/fenix/issues/19112.

**Comment by jonalmeida** [comment]
This change has landed in nightly and will be in the next beta too.

**Comment by lobontiumira** [comment]
Verified as fixed on the 5/28 Nightly build with Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by jonalmeida** [comment]
This was uplifted to the beta 89.1.1 release as well.
