### ISSUE TITLE
The space between sections is too large

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19640]
## Steps to reproduce
1. Access Saved cards and then tap on the saved card in order to edit it or add a new card.
2. Observe the space between Card Number, Name on Card, Expiration Date (basically all the sections).
### Expected behavior
The spaces between sections shouldn't be too large.
### Actual behavior
The space between sections is too large
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/25.**

![20210525_150529](https://user-images.githubusercontent.com/42831109/119495663-4dd6b880-bd6b-11eb-98de-603d016b6069.jpg)
![20210525_150509](https://user-images.githubusercontent.com/42831109/119495670-4fa07c00-bd6b-11eb-8ca3-ede8034bf757.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10779)

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible on the:
- latest Nightly 96.0a1 (2021-11-22).
- latest Beta (95.0.0 beta4).
- latest Release 94.1.2.
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 110.0a1 (2023-01-17).
The spacing is the same as it was on the version the issue was logged on.
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814141

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
