### ISSUE TITLE
[Bug] Favicons are not reliably saved next to the bookmark in private mode.

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#19645]
Favicons are not reliably saved next to the bookmark if the bookmark was created in private mode.

## Steps to reproduce
1a) Open website in standard mode.
1b) Save bookmark.

2a) Open website in private mode.
2b) Save bookmark.

### Expected behavior
Favicon should be saved next to the bookmark regardless of the operating mode.

### Actual behavior
Favicon is only reliably saved in standard mode.

### Device information

* Samsung Galaxy XCover 4S, Android 10
* Firefox for Android version: 88.1.4

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce your issue on Firefox Preview 88.1.4 and Nightly 27/5 but was unable. @WebworkrNet Could you give us some examples of sites for which favicons are not properly saved?
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3XL (Android 9)

**Comment by WebworkrNet** [comment]
The problem occurs often, but not always.

After deleting cookies as well as graphics and cached data, improvement occurred for a short time. However, I cannot say whether there is a causal connection.

Closing tabs brought no improvement.

I can't find out that it affects specific pages. But here are some examples (or their subpages):
• fernsehserien.de
• heise.de
• kuketz-blog.de
• mobilsicher.de
• Wikipedia

**Comment by WebworkrNet** [comment]
Problem also detected on:

Samsung Galaxy XCover 4S, Android 10
 
Firefox Nightly  
91.0a1 (Build #2015819211)
AC: 91.0.20210629143047, 8904b55efe
GV: 91.0a1-20210629092640
AS: 79.0.0

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Tested with a few examples from the above comment.
The favicons were displayed for each site in private mode as well.
Verified on the latest Nightly (2022-01-06).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.

**Comment by WebworkrNet** [comment]
@SoftVision-LorandJanos 

Sorry, I can't confirm that unfortunately.

Tested sub-sites in private mode:
- fernsehserien.de
- heise.de
- de.wikipedia.org

On some pages the favicon was reloaded later, on other pages not at all. Only Wikipedia reliably saved the favicons next to the bookmark on the first try. 

- Samsung Galaxy XCover 4s
- Android 11
- 98.0a1 (Build #2015860875), 9b9fab40d+
AC: 98.0.20220201143153, dbd6aea769
GV: 98.0a1-20220201093942
AS: 90.0.1


I ask to reopen the ticket. Thank you
