### ISSUE TITLE
FNX-5360 ⁃ [Bug] [A11y] Bookmarks list text needs a higher contrast

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1964]
## Steps to reproduce
1. Go to PB.
1. Run the a11y scanner on the Bookmarks list.
    1. Expected behavior
Text contrast is acceptable.
    1. Actual behavior
From a11y scanner results: Consider increasing item's text foreground to background contrast ratio.
    1. Device information

* Android device: Pixel (android 9)
* Fenix version: 4/23

**Comment by kbrosnan** [comment]
I assume this is true of the History view as well?

**Comment by sv-ohorvath** [comment]
This was fixed in the meantime, the text has a brighter color on both menus.
