### ISSUE TITLE
[Bug] After pressing "Sync Now" credit card sync is disabled in Fenix and Desktop Credit Cards are not synced to Fenix

### ISSUE THREAD

**Issue by jdragojevic** [mozilla-mobile/fenix#19656]
## Steps to reproduce
1. Have credits saved in Desktop
2. Enable credit card syncing in Fenix
3. Watch logs (adb logcat)
4. See indication that sync is enabled
5. Check for Credit cards (not there)
6. Hit Sync now in Fenix
7. Credit card toggle is disabled
8. Logs show credit cards not syncing

### Expected behavior
Cards are synced.

### Actual behavior
1. Desktop credit card displayed in Fenix
2. Fenix card displayed in Desktop
3. Toggle not disabling itself.

### Device information
Samsung Tablet 5/25 nightly build Fenix
* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by jdragojevic** [comment]
I see some of this in the logs: 
```05-26 11:32:57.345 10664 22450 W SyncTelemetry: Ignoring telemetry for engine creditcards
05-26 11:33:19.855 10664 22433 W sync15::state: Remote state contains engines which are in both info/collections and meta/global's declined: {"creditcards"}
05-26 11:33:20.131 10664 22433 I sync15::sync_multiple: Resetting engine creditcards, as it was declined remotely
05-26 11:33:20.737 10664 22433 I sync15::sync_multiple: The creditcards engine is declined. Skipping
05-26 11:40:21.540 10664 22433 W sync15::state: Remote state contains engines which are in both info/collections and meta/global's declined: {"creditcards"}
05-26 11:40:22.297 10664 22433 I sync15::sync_multiple: The creditcards engine is declined. Skipping```

**Comment by jdragojevic** [comment]
More info:

1. I signed out of sync on Fenix - restarted Fenix.  
2. On Desktop - I have Credit card sync enabled.
3. Signed in to sync on Fenix - see in logs creditcards are still not syncing.
4. Switched to the UI view for Credit cards:  the **Sync cards** toggle is OFF - it should be ON because credit card sync is ON in Desktop
5. Toggled the **Sync cards** toggle is ON - no obvious change in sync status; no logs. @gabrielluong   _Is this all connected properly?_ 
6. Returned to accounts settings page and hit "Sync now".  Result, credit card checkbox and Creditcards toggle are both OFF again.

**Comment by jonalmeida** [comment]
Is the `creditcards` sync engine correct? When I tried to debug this, it looks like sync doesn't recognize `creditcards` as a valid engine. With then `about:sync` addon on Desktop I also cannot find an equivalent engine there, but I can see all the ones listed in the logs below ("meta", "addresses", "history", "tabs", "extension-storage", "forms", "passwords", "crypto", "bookmarks", "prefs", "clients", "addons"):

```
2021-05-26 20:42:23.053 4810-4933/org.mozilla.fenix.debug I/SyncWorker: Successfully synced creditcards
2021-05-26 20:42:23.064 4810-4933/org.mozilla.fenix.debug W/SyncTelemetry: Ignoring telemetry for engine creditcards
2021-05-26 20:43:46.266 4810-4933/org.mozilla.fenix.debug D/sync15::state: compute_engine_states: input EngineStateInput { local_declined: {}, remote: Some(RemoteEngineState { info_collections: {"meta", "addresses", "history", "tabs", "extension-storage", "forms", "passwords", "crypto", "bookmarks", "prefs", "clients", "addons"}, declined: {"creditcards"} }), user_changes: {} }
2021-05-26 20:43:46.266 4810-4933/org.mozilla.fenix.debug D/sync15::state: compute_engine_states: output EngineStateOutput { declined: {"creditcards"}, changes_needed: EngineChangesNeeded { local_resets: {"creditcards"}, remote_wipes: {} } }
2021-05-26 20:43:46.266 4810-4933/org.mozilla.fenix.debug D/sync15::state: SyncID for engine "creditcards" was present, but shouldn't be
2021-05-26 20:43:46.505 4810-4933/org.mozilla.fenix.debug D/sync15::sync_multiple: Declined engines list after state machine set to: Some(["creditcards"])
2021-05-26 20:43:46.505 4810-4933/org.mozilla.fenix.debug I/sync15::sync_multiple: Resetting engine creditcards, as it was declined remotely
2021-05-26 20:43:46.986 4810-4933/org.mozilla.fenix.debug I/sync15::sync_multiple: The creditcards engine is declined. Skipping
```

**Comment by jonalmeida** [comment]
After using a build that includes [markh's fix](https://hg.mozilla.org/releases/mozilla-release/rev/1ce0b546a957), I was able to see `creditcards` in the meta table but the engine was still not showing up in the list of syncing engines.

**Comment by grigoryk** [comment]
First pass at this locally, and I see things syncing successfully:
```
                         I  Syncing creditcards engine!
           sync15::sync  I  Syncing collection creditcards
     sync15::coll_state  I  Resetting creditcards engine
         sync15::client  I  Successful request to "/1.5/159068076/storage/creditcards", incoming x-last-modified=ServerTimestamp(1622164460600)
           sync15::sync  I  Downloaded 6 remote changes (request 0 of 1)
 autofill::sync::common  I  staging 6 incoming records into credit_cards_sync_staging
           sync15::sync  I  Uploading 0 outgoing changes
                         I  Upload success (0 records success, 0 records failed)
                         I  Sync finished!
  sync15::sync_multiple  I  Sync of creditcards was successful!
                         I  Finished syncing engines.
  sync_manager::manager  I  Sync finished with status Ok
                         I  engine "tabs" status: Ok(())
                         I  engine "history" status: Ok(())
                         I  engine "bookmarks" status: Ok(())
                         I  engine "passwords" status: Ok(())
                         I  engine "creditcards" status: Ok(())
             SyncWorker  I  Successfully synced tabs
                         I  Successfully synced passwords
                         I  Successfully synced creditcards
                         I  Successfully synced bookmarks
                         I  Successfully synced history
```

**Comment by grigoryk** [comment]
On toggling credit cards sync state, in Fenix I'm seeing what appears like correct behaviour.

Enabling it:
```
...
          sync15::state  I  Have info/collections and meta/global. Computing new engine states
                         I  Uploading new declined [] to meta/global with timestamp ServerTimestamp(1622167882760)
                         I  Uploading corrected meta/global with timestamp ServerTimestamp(1622167882760)
...
```

Disabling it:
```
...
          sync15::state  I  Have info/collections and meta/global. Computing new engine states
                         I  Uploading new declined ["creditcards"] to meta/global with timestamp ServerTimestamp(1622167940750)
                         I  Uploading corrected meta/global with timestamp ServerTimestamp(1622167940750)
         sync15::client  I  Successful request to "/1.5/159068076/storage/meta/global", incoming x-last-modified=ServerTimestamp(1622168037910)
                         I  Successful request to "/1.5/159068076/storage/crypto/keys", incoming x-last-modified=ServerTimestamp(1600538281070)
  sync15::sync_multiple  I  Engine "creditcards" just got disabled locally, wiping server
         sync15::client  I  Successful request to "/1.5/159068076/storage/creditcards", incoming x-last-modified=ServerTimestamp(1622167941470)
  sync15::sync_multiple  I  Resetting engine creditcards, as it was declined remotely
...
```

**Comment by grigoryk** [comment]
Okay, as far as I can tell it all works correctly for me, both in local builds and on Nightly. I did notice a problem above (rarely, changing sync state of an engine won't trigger an actual sync), but that's not new and not directly connected to credit cards sync.

**Comment by jdragojevic** [comment]
I'm sorry - this was all my mistake today.  I _thought_ I had update my nightly Desktop, however, I failed to restart.  After properly updating I do see the syncing work as expected.  Sorry for the confusion.

**Comment by amedyne** [comment]
Closing this as per latest comment and updates.

**Comment by jonalmeida** [comment]
> If I hit the sync now button from desktop, then sync on Fenix, the credit card option unchecks because of the engine mismatch. If I check the cc syncing box and sync on fenix multiple times, it says the cc sync was successful (but there's nothing there).

I've updated to the latest Desktop, but this behaviour still happens for me and my credit cards do not show up even when checked. 🤷‍♂️

**Comment by jonalmeida** [comment]
So after I updated my Nightly, there was _another_ update. This one now seems to work and everything is syncing as well. 😄

**Comment by grigoryk** [comment]
We heard you like nightly updates, so we put an update on top of an update... :)
