### ISSUE TITLE
Address #19643 PR comments

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19653]
There were some comments on https://github.com/mozilla-mobile/fenix/pull/19643#pullrequestreview-668098375 PR that weren't addressed there.
Since those proposed changes would not modify the app behaviour we went with merging that to unblock some QA work.
This ticket is opened to offer the change to address those. Probably by @ionutbedregeanu .

**Comment by ionutbedregeanu** [comment]
I will take it. Could you please assign it to me?
