### ISSUE TITLE
[Bug] Sign in to Sync displayed in Settings menu at startup when I am already signed in

### ISSUE THREAD

**Issue by jdragojevic** [mozilla-mobile/fenix#19657]
## Steps to reproduce
1.  Be signed in to Sync
2. Close app
3. Start app
4. Open setting menu

### Expected behavior
See my account listed in settings menu

### Actual behavior
Setting menu contains Sign in to sync
### Device information
Samsung tablet Fenix 5/25 nightly build 90.0a1
* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10789)

**Comment by sflorean** [comment]
Tested on Nightly 5/26 and I was able to reproduce the issue following the steps with Samsung Note 10 (Android 11), the account name is not displayed even if I don't close Fenix.
On LG G7 Fit (Android 8.1) the name is displayed after the sync is done, but after closing-reopening the browser, the bug is reproducible.

**Comment by VitalyVPinchuk** [comment]
Hi!
Could I try to fix the issue?
@jdragojevic @sflorean

**Comment by VitalyVPinchuk** [comment]
Hello @Mugurell 
Is the issue worth fixing or would there be a sort of substantial refactoring that would eliminate it?

I've looked into the matter and found that the menu is constructed prior to signing in, which could take more than a second.

**Comment by J41319** [comment]
I am also having this problem.

**Comment by jdragojevic** [comment]
I'd love to advocate for getting this fixed @amedyne.  If someone on the Fenix has a chance to dig in, please let them know to reach out to the sync team (#synced-client-integrations slack) to partner on the investigation.

**Comment by VitalyVPinchuk** [comment]
Could I try to fix it?

**Comment by amedyne** [comment]
@VitalyVPinchuk Go for it! We appreciate you helping out.

**Comment by rocketsroger** [comment]
Confirmed that this issue is fixed in Nightly.  Closing.
