### ISSUE TITLE
FNX-5361 ⁃ [Bug] Bookmark notification overlapping URL bar

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1965]
## Steps to reproduce
1. Open any webpage.
1. Tap on the tab counter.
1. Open the same webpage back again.
1. From the Quick Action bar, bookmark the page.

### Expected behavior
The bookmark notification is displayed above the URL bar.

### Actual behavior
The bookmark notification is displayed over the URL bar.

### Device information
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * HTC Desire 820 (Android 6.0.1)
  * HTC 10 (Android 8)
  * Google Pixel (Android 9)
* Fenix version: 1.0.1917 (#11131208)

![gif](https://user-images.githubusercontent.com/17178945/56657107-e0de2980-669f-11e9-85e5-19069adfc708.gif)

**Comment by kbrosnan** [comment]
I'm not seeing this using an April 26th build on a Galaxy S6 and Nexus 10 @bsurd please retest.

**Comment by vesta0** [comment]
Please re-open if you can reproduce.
