### ISSUE TITLE
Evaluate RTL support for the "Add credit card" button from "Saved cards"

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19654]
https://github.com/mozilla-mobile/fenix/pull/19643 added a new `Add credit card` button and also raised an important issue: whether we want have a different behavior for RTL.

Current LTR layout
<img src="https://user-images.githubusercontent.com/11428869/119541519-2ac1fe00-bd97-11eb-9449-f98d7be6af3e.png" width="33%" />

**Comment by gabrielluong** [comment]
@ionutbedregeanu fixed this.

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/27** with **OnePlus Nord (10).**
I was able to add multiple cards and the `+` `Add credit card` button was still displayed and fully functional.
