### ISSUE TITLE
[Bug] The same CC can be added multiple times

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19668]
## Steps to reproduce
1. Add one credit card.
2. Tap on the `Add credit card` button and add the same credit card.
### Expected behavior
The same CC should not be added twice.
### Actual behavior
The same CC can be added multiple times
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/26.**

**Comment by gabrielluong** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/18275
