### ISSUE TITLE
Jetpack Compose

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#19662]
This is the Fenix version of the following A-C issue:
https://github.com/mozilla-mobile/android-components/issues/10335

The goal of this issue is to explore what changes are required to get Jetpack Compose setup in the Fenix repository.

I recently did this for Reference Browser and the work is more or less covered by the following pull requests:
- https://github.com/mozilla-mobile/reference-browser/pull/1536
- https://github.com/mozilla-mobile/reference-browser/pull/1540

Currently most of the required tooling and dependencies are not stable yet. So I wouldn't necessarily do the switch now - especially since that would also require changes in the upstream and downstream projects (A-C and its consumers). But I want to start a branch and figure out what things are missing. Jetpack Compose should hit stable in July (and hopefully all tooling too) and ideally we will be ready by then.

We will at least need:
- [ ] Setup ready in A-C
- [ ] Java 11
- [ ] Android Gradle Plugin 7+
- [ ] Gradle 7
- [ ] Getting rid of the deprecated `kotlin-android-extensions` plugin [#17917](https://github.com/mozilla-mobile/fenix/issues/17917)
- [ ] Jetpack Compose and its transitive dependencies

**Comment by gabrielluong** [comment]
Gonna explore getting rid of the deprecated `kotlin-android-extension` plugin in Fenix in https://github.com/mozilla-mobile/fenix/issues/19794
