### ISSUE TITLE
FNX-5362 ⁃ [Bug] The back button from the multiple-selection toolbar should just cancel the selection

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1966]
## Steps to reproduce
1. Go to bookmarks and select a few items.
1. Tap the back button from the top toolbar.
    1. Expected behavior
The selection is canceled. The bookmarks list returns to the default view.
    1. Actual behavior
The current bookmarks folder is closed and goes to the parent folder.
Note: The name of the folder which was closed is displayed now. (I didn't file a separate issue because it could be fixed by solving this issue first).
    1. Device information

* Android device: Pixel (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/23

**Comment by sv-ohorvath** [comment]
Hi @colintheshots, I was actually referring to the back button located in the purple toolbar, this looks like it fixed the system back button behavior? :) 
![20190502_161620](https://user-images.githubusercontent.com/4037709/57078037-20d38b00-6cf6-11e9-83c7-456f563078b0.gif)

**Comment by sv-ohorvath** [comment]
Also, there's a new issue: #2227

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 1.0.1923 (#11560607) with Huawei P9 Lite (Android 6), and Xiaomi Mi 8 Lite (Android 8.1).
