### ISSUE TITLE
[Bug] Firefox GUI is still visible in multi-task interface after disabled screenshots in incognito mode option

### ISSUE THREAD

**Issue by NewtMa** [mozilla-mobile/fenix#19660]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Disable screenshot in incognito mode option;
- Open an website tab in the incognito mode, and wait for it to be loaded;
- hit the home button on your phone to invoke the multi-task interface;
- it's very likely that the web page is still visible in that interface and a screenshot can be taken on that GUI.

### Expected behavior
- the firefox task GUI should be hidden and covered in a veil (I don't know what it's called)

### Actual behavior
- the website shown in Firefox is still visible in the multi-task interface.

### Device information

* Device vendor / model and Android version: `Redmi Note 7 on MIUI 10 9.5.9 (Android 9)`
* Firefox for Android version: ? (go to Settings -> About Firefox) `88.1.4`

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce your issue on Firefox Preview 88.1.4 and Nightly 26/5, but was unable to. @NewtMa Could you please upload a short video showing the issue and also download the latest Firefox Preview Nightly and see if the issue still occurs on it?
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by NewtMa** [comment]
@LaurentiuApahideanSV Here's the video, Google Authenticator don't have the same issue, it work like a charm. Then again my Android system is heavily customized by the vendor.



https://user-images.githubusercontent.com/48610536/119755739-12f09400-bed5-11eb-9bf2-c8f2defc08d7.mp4

**Comment by LaurentiuApahideanSV** [comment]
From what I see in the video it seems that you are turning on the 'Allow screenshots in private browsing' option, if this option is on Firefox will be visible in the multi task interface. If you want Firefox to be hidden in the multi task interface this options needs to be turned off.

**Comment by kbrosnan** [comment]
You would need to disable the screenshots in private browsing option to get the behavior you are expecting.
