### ISSUE TITLE
Hang when loading https://www.monbureaunumerique.fr/ on Fenix

### ISSUE THREAD

**Issue by simon511000** [mozilla-mobile/fenix#19678]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- go to https://www.monbureaunumerique.fr/

### Expected behavior
be able to navigate on the site as on firefox desktop

### Actual behavior
firefox has a weird bug, the page is not displayed and cannot close the tab or change the url

### Device information

* Device vendor / model and Android version: tested on Pixel XL android 9 and 10
* Firefox for Android version: 88.1.3

**Comment by LittleAngelwings** [comment]
Did you tried the new version 89.1.0? 
I can confirm this issue only with my smartphone (Huawei P smart (2017, 3GB, Android 9.1.0) and the latest Play Store version.
But not complete as the opener has reported. The firsts moments while and after loading the tab Firefox didn't react. 
After a few seconds and a previous click on a button Firefox react and the site will be displayed.

On my Chromebook with Intel i5 (8GB) and Android 11 Firefox 89.1.0 and nightly I don't have any problems with the reported site.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1713002

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
