### ISSUE TITLE
Display the card network name besides the card number

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19684]
We should display the credit card network name (Visa, Discover, etc) besides the card number. You will find the list of supported credit card network https://searchfox.org/mozilla-mobile/source/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/CreditCardUtils.kt#40. I think these should be mapped to localized, you will want to map the cardType to their formal credit card network name. We will probably want to ask if (1) the credit card network name should be localized from @Delphine, and (2) make sure we get the correct network names, I looked at desktop and saw MasterCard which I assume is probably incorrect for instance.

<img width="375" alt="Screen Shot 2021-05-27 at 3 54 50 AM" src="https://user-images.githubusercontent.com/1190888/119787613-60eaa500-be9f-11eb-96a0-072b06ad61cb.png">

**Comment by gabrielluong** [comment]
We should probably display nothing if the cardType does not match the list of enum

**Comment by codrut-topliceanu** [comment]
>We will probably want to ask if (1) the credit card network name should be localized from @Delphine, and (2) make sure we get the correct network names, I looked at desktop and saw MasterCard which I assume is probably incorrect for instance.

@Delphine could you provide any input here? Are localized credit card network names a thing?
As far as I know the Network names are an international standard but I'm not really well informed on this.

<img src="https://user-images.githubusercontent.com/60002907/119820770-81941880-befa-11eb-8bc7-e1a762ffc159.png" width="300"/>

**Comment by Delphine** [comment]
Thanks for reaching out! I checked against desktop strings, and these should in face be localizable.
Also, example with MasterCard hebrew website: https://www.mastercard.co.il/he-il.html

**Comment by gabrielluong** [comment]
@codrut-topliceanu I decided to push this to 91 instead. I think we decided to just display the "name on card" instead.

**Comment by gabrielluong** [comment]
Closing this, let's file a new issue for adding "name on card"
