### ISSUE TITLE
FNX-5364 ⁃ Create bookmark folder from bookmarks

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1968]
### Why/User Benefit/User Problem
It's counter-intuitive to only have the option to create bookmark folders when adding a bookmark, this would make it easier for users to see the option and create folders inside the app.

### What / Requirements
Add a way for users to add folders from the bookmark menu directly.

Design example:
![screen](https://user-images.githubusercontent.com/17178945/56658921-85fb0100-66a4-11e9-931a-709a8e150168.png)

### Acceptance Criteria (how do I know when I’m done?)
* Bookmark folders can be added from the Bookmarks menu

**Comment by mheubusch** [comment]
https://drive.google.com/file/d/1I1O9AR5J6wlj3Q2AOAVycBZ2wBwoqPNI/view

Here is a link to the svg @vesta0  @boek @ekager @sblatz

**Comment by topotropic** [comment]
the "Add new folder" icon is left to the close icons:
![bookmarks-new-folder](https://user-images.githubusercontent.com/353960/57837797-ca6d4e80-77c3-11e9-8025-2929017e941c.png)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Fenix Build **#11850611 from 4/7** using the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)

►Video from Samsung Galaxy S8+
![20190704_143057](https://user-images.githubusercontent.com/51314259/60664146-d2fc1000-9e69-11e9-85af-c27d9303cef0.gif)
