### ISSUE TITLE
Bitwarden inline autofill fails with Firefox stable, works great in Nighly

### ISSUE THREAD

**Issue by bonyjose** [mozilla-mobile/fenix#19685]
Bitwarden app for android 11 support inline autofill of passwords, i'm using Firefox stable and Nightly side by side for a while, inline autofill works consistently great with Nightly builds, but it simply fails to autofill using Gboard when i'm trying with stable builds(tried, Firefox stable 86,87,88,and 89), today i tested with latest 89.1 stable and still fails to inline autofill, it works maybe 1/10 times in stable, but it's a solid 9/10 in case of Nightly builds, it's been the same for at least 3 months back. Below is a screenshot of autofill working in latest Nightly.

![WhatsApp Image 2021-05-27 at 4 56 06 PM](https://user-images.githubusercontent.com/2097150/119818355-b90bc080-bf0c-11eb-8972-86dd6c52f458.jpeg)

## Steps to reproduce
Use Android 11 ROM with GBoard and Bitwarden app, Enable Autofill services/Inline Autofill and use accessibility option inside Bitwarden app, save some website login to Bitwarden, try entering the login page,GBoard should bring up login details inline, works for Nightly builds, doesn't work 9/10 times in Stable build.

### Expected behavior
Stable Firefox should inline autofill correctly

### Actual behavior
Firefox stable fails to Inline autofill using GBoard

### Device information
         Mi 9T Pro with Android 11 AOSP ROM (not MIUI)
* Device vendor / model and Android version: ?
         Android 11, Xiaomi
* Firefox for Android version: ? (go to Settings -> About Firefox)
        89.1.0 stable

**Comment by Mugurell** [comment]
The good thing is that based on Mozilla's release process all features and bug fixes first landing on Nightly will eventually get to Beta and then Release.
If this feature works in Nightly 90/91 then it should also work in Release 90/91.
Keeping this ticket open to check again in the new releases.

**Comment by hakkikaancaliskan** [comment]
@Mugurell I'm tracking this issue for soooo long time but this didn't fixed as the train rides.

**Comment by bonyjose** [comment]
@hakkikaancaliskan, @Mugurell 
Exactly, as i mentioned in the original post, this feature is working great in nighly builds from 86+(that i can confirm), so it should have been working perfe tly from 86 stable onwards as part of the release cycle. But somehow it just dosent work as great even in 89 stable. So i guess there actually exists a bug that affect stable builds.

**Comment by Mugurell** [comment]
I'm seeing this working in release 88 and 89 also, though a bit finnicky as @hakkikaancaliskan said.

https://user-images.githubusercontent.com/11428869/121364594-992ec080-c940-11eb-95ef-6c3ae76d7f90.mp4

&nbsp;
Don't really know how it works, whether it's a bug in firefox, bitwarden or the keyboard but since this relates to website interactions I'm moving the ticket to Bugzilla for deeper investigations.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1715549

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by dabat** [comment]
@Mugurell is there a way to get updates on the bugzilla ticket?
i did not see a way to subscribe

**Comment by Mugurell** [comment]
> @Mugurell is there a way to get updates on the bugzilla ticket?
> i did not see a way to subscribe

You need a bugzilla account and then you'll be able to add that to the CC section.

**Comment by dabat** [comment]
Thank you very much @Mugurell !

**Comment by Mugurell** [comment]
This should now be resolved by Bitwarden.
