### ISSUE TITLE
FNX-5365 ⁃ [Bug] Cannot delete bookmark folder

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1969]
## Steps to reproduce
1. In Bookmarks, have a folder created.
1. From the folder's overflow menu, tap Delete.
1. Or, edit a folder, tap Delete.
    1. Expected behavior
Folder deleted.
    1. Actual behavior
Nothing happens.
    1. Device information

* Android device: Pixel (Android 9)
*Not reproducing on Nexus 5 (Android 6), HTC Desire 820 (Android 6.0.1), HTC 10 (Android 8)
* Fenix version: 4/23

**Comment by vesta0** [comment]
@sv-ohorvath I believe the folder is deleted but there is a significant delay. Would you try again?

**Comment by vesta0** [comment]
Related: #1862

**Comment by sv-ohorvath** [comment]
I noticed the delay, but before, they were not removed from the list. Looks like it is now fixed. Closing.
