### ISSUE TITLE
Display a biometric prompt when a credit card is selected to autofill

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19693]
<img width="494" alt="Screen Shot 2021-05-27 at 3 35 10 PM" src="https://user-images.githubusercontent.com/1190888/119890761-37b12f80-bf06-11eb-8a3d-99317291dbef.png">

**Comment by gabrielluong** [comment]
Strings for the prompt

Unlock your device
Unlock to use stored credit card information

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 5/31** with **Google Pixel 4XL (11).**
Note that I used the following methods:
- None
- Swipe
- Pattern
- Pin
- Password
- Face unlock
And I was able to unlock and autofill without problems.
