### ISSUE TITLE
[Bug] The `Select credit card` prompt arrow is inversed 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19700]
## Steps to reproduce
1. Save a credit card.
2. Access any website and attempt to purchase with the card.
3. Observe the `Select credit card` prompt arrow.
### Expected behavior
The `Select credit card` prompt arrow should not be inverted.
### Actual behavior
The `Select credit card` prompt arrow is inversed.
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/28.**

![Screenshot_20210528-163957](https://user-images.githubusercontent.com/42831109/119993717-8b8a4a00-bfd4-11eb-8c6a-2e13b9cd5139.png)
![Screenshot_20210528-163951](https://user-images.githubusercontent.com/42831109/119993719-8c22e080-bfd4-11eb-9b18-95bd9a3d9765.png)

**Comment by gabrielluong** [comment]
This is the correct arrow direction.
