### ISSUE TITLE
FNX-5367 ⁃ [Bug] Firefox Preview icon is not displayed

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1970]
## Steps to reproduce
1. Install Firefox Preview.
1. Check the app icon.

### Expected behavior
Firefox Preview icon is displayed.

### Actual behavior
Android placeholder icon is displayed.

### Device information
* The icon is displayed on Google Pixel.
* The issue is also available for all other places where the icon should be displayed in Android.
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * HTC Desire 820 (Android 6.0.1)
* Preview version: 1.0.1917 (#11141216)

![screen](https://user-images.githubusercontent.com/17178945/56661083-abd6d480-66a9-11e9-8225-5000ff2b6fb2.png)

**Comment by LittleAngelwings** [comment]
Here no problem with the same version at Android 8.1.0 and 8.0.0 and Nova Launcher

**Comment by mozillamarcia** [comment]
I see the same issue installing on a Nexus 6 running 7.1.1.

**Comment by gaby2300** [comment]
I can reproduce this using a Sony Xperia Z3C with Android 6.0.1. The home icon is an unnamed dark gray square. Opening the app, I see the Firefox Preview icon at the top.

**Comment by kbrosnan** [comment]
Verified fixed. Using a Nexus 5 running Android 6. Though I do see some issues around the icon appearance. We are defaulting to the rounded corners icon when we should use the unboxed icon.

![Nexus%205%20-%20English_20190426_092310](https://user-images.githubusercontent.com/250273/56776268-3d187a80-6780-11e9-8cc6-4d088f15b838.jpg)
