### ISSUE TITLE
[Spike] Investigate the need for using the KeyguardManager separately

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19709]
## Description
In the `BiometricPromptPreferenceFragment` and in some places in `BaseBrowserFragment`, we try to fallback to the KeyguardManager for PIN/password support. 

This isn't something that should be needed since we [allow PIN/password as a fallback](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/settings/biometric/BiometricPromptFeature.kt#L57) when we make a request through the Biometric support library. The biometric library also abstracts out the correct calls for backward compatibility for devices that do not have support for full support.

Something we could adjust is [the code checking](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/settings/biometric/ext/BiometricManager.kt#L25) for biometric support for [`DEVICE_CREDENTIAL`](https://developer.android.com/reference/androidx/biometric/BiometricManager.Authenticators#DEVICE_CREDENTIAL).

## Deliverables

- Can we remove the complexities of the KeyguardManager from our code base and use the AndroidX library alone? The less code, the better. :)
- If we do need it, can we hide those within the BiometricPromptFeature so that it can be used in multiple places since we have two separate impls of a similar code flow?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10818)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814143

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
