### ISSUE TITLE
[Bug] The user is redirected to Credit cards from Saved cards section after a home/recent interrupt

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19701]
## Steps to reproduce
1. Access Saved cards (with or without a card saved).
2. Tap on any of the home/recent buttons and then return to the app (resume Fenix).
### Expected behavior
The saved cards section is still displayed.
### Actual behavior
The user is redirected to Credit cards from the Saved cards section after a home/recent interrupt
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/28.**
 
### Notes
This issue is not reproducible on the Google Chrome. 
When the screen is black, means I'm on the saved cards section, but it can be seen how the section changes.

https://user-images.githubusercontent.com/42831109/119998278-3a308980-bfd9-11eb-9f3e-70ef6daff937.mp4

**Comment by VitalyVPinchuk** [comment]
Hi
Could this be done intentionally?

```
/**
 * Pops the backstack to force users to re-auth if they put the app in the background and return to
 * it while being inside a secured flow (e.g. logins or credit cards).
 *
 * Does nothing if the user is currently navigating to any of the [destinations] given as a
 * parameter.
 */
fun Fragment.redirectToReAuth(

```

**Comment by gabrielluong** [comment]
This is intentional.
