### ISSUE TITLE
Add Close Icon to Menu

### ISSUE THREAD

**Issue by gitpubber** [mozilla-mobile/fenix#19705]
![Screenshot_20210528-233112_Firefox](https://user-images.githubusercontent.com/76197622/120024615-18e99080-c00d-11eb-837d-012f288e319a.png)

Menu contains buttons to navigate back,front , share and refresh. I would like to request you to also add button to close the window

**Comment by gitpubber** [comment]
It also enables faster closing of windows

**Comment by kbrosnan** [comment]
This is not in the default menu. Android does not expect apps to have a quit option. You can enable the `Delete browsing data on quit` option to get this option.

**Comment by gitpubber** [comment]
@kbrosnan i would like to have close window option in menu. delete browsing data on quit is different
