### ISSUE TITLE
Select all on large page causes crash [@ java.lang.RuntimeException: at android.app.ApplicationPackageManager.queryIntentActivityOptions(ApplicationPackageManager.java) ]

### ISSUE THREAD

**Issue by seniorm0ment** [mozilla-mobile/fenix#19702]
When selecting all on large amounts of text ("select all"), the app crashes.
An example file which triggered it was this page. https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Fennec FDroid 88.1.3, Androidb10, LGv40

**Comment by kbrosnan** [comment]
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.RuntimeException%3A%20at%20android.app.ApplicationPackageManager.queryIntentActivityOptions%28ApplicationPackageManager.java%29

* https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=queryIntentActivityOptions
* https://sentry.prod.mozaws.net/operations/firefox-beta/?query=queryIntentActivityOptions
* https://sentry.prod.mozaws.net/operations/firefox/?query=queryIntentActivityOptions
