### ISSUE TITLE
Feature Request: Add close tab icon to the menu

### ISSUE THREAD

**Issue by gitpubber** [mozilla-mobile/fenix#19706]
![120024615-18e99080-c00d-11eb-837d-012f288e319a](https://user-images.githubusercontent.com/76197622/120030007-8816b300-c014-11eb-919b-51ce069142c5.png)

as you can see,there are only navigate back, navigate forth, share and refresh buttons in menu.

i would like to have "close tab" button which closes the tab on click. it improves user experience

**Comment by jonalmeida** [comment]
This already exists if you long press on the tab counter. A list of quick actions shows up.

<img src="https://user-images.githubusercontent.com/1370580/120034840-a4dac880-bfcb-11eb-9fca-97f6818c2ded.png" width=360 />

**Comment by jonalmeida** [comment]
I'm going to close this for the reason above. I don't suspect we'd want to add another close button in the menu as well. Thanks for filing! 🙂
