### ISSUE TITLE
FNX-5368 ⁃ [Bug] Closing a crashed tab leaves an empty tab

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1971]
## Steps to reproduce
1. Open a webapge.
1. Go to about:crashcontent
1. Tap Close tab on the crash error page.
    1. Expected behavior
The crashed tab is closed.
    1. Actual behavior
An empty tab remains in tabs view.
    1. Device information

* Android device: Pixel (android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/24

**Comment by sblatz** [comment]
I cannot reproduce this on my galaxy s9 (android 9) or on Pixel 3 (android 9).

**Comment by sv-ohorvath** [comment]
Somehow I can't reproduce it either now... Closing. Thanks!

**Comment by sv-ohorvath** [comment]
I've found reliable STR for this:
1. Open 2 tabs.
2. Close & restart the browser.
3. In one of the tabs opened, go to about:crashcontent.
4. On the crash reporter, tap Close tab.
- The crashed tab is still opened, with about:blank.

2nd scenario has a different outcome:
1. Open a clean browser with no tabs.
2. Load 2 new tabs.
3. In one of the tabs opened, go to about:crashcontent.
4. On the crash reporter, tap Close tab.
-Both tabs are still open and contain about:blank pages.

**Comment by boek** [comment]
@sv-ohorvath Can you still reproduce this?

**Comment by boek** [comment]
Ah so it only crashes tabs that have been active during the application session. There is a fix for A-C here: https://github.com/mozilla-mobile/android-components/pull/3275. We should be able to have this fixed tomorrow :)

**Comment by boek** [comment]
Dup of #1809
