### ISSUE TITLE
[Bug] Update to Nightly Crashing Constantly - Unopenable

### ISSUE THREAD

**Issue by L31FY** [mozilla-mobile/fenix#19710]
## Steps to reproduce
Attempt to open the browser at all by any means

### Expected behavior
Open the browser and be able to use it and not crash within a couple of seconds

### Actual behavior
Continuing almost instant crashes upon opening the browser or any other app trying to do so either by clicking on a link

### Device information
Multiple devices

* Device vendor / model and Android version: 
* device 1 is a Samsung Galaxy S9 on Android 10
* device 2 is a Ulefone Armor 6 on Android 8.1

* Firefox for Android version: unable to locate due to crashing because I can't get that far
 
Managed to click very fast and get this before it died this time: https://crash-stats.mozilla.org/report/index/bp-973cc213-44ac-4e7a-8402-281e40210528

https://crash-stats.mozilla.org/report/index/bp-6ef71d5f-27fa-47c1-ad13-97a510210528

This issue looks identical and for some reason was given no attention and closed.
https://github.com/mozilla-mobile/fenix/issues/19672

**Comment by L31FY** [comment]
Before update - fine. After update - can't even open this now. It's the update.

**Comment by csadilek** [comment]
Upstream issue: https://github.com/mozilla/application-services/issues/4035

**Comment by csadilek** [comment]
This should be fixed now in latest Nightly. @L31FY Can you verify / Are you still experiencing crashes? 

Settings->About should show AS: 77.0.2 in the fixed version.

**Comment by L31FY** [comment]
I was able to sign back in to sync and I haven't had any issues as of now
which I'm sure would have been noticed. The crash seems to have been fixed.

**Comment by csadilek** [comment]
OK, thanks for verifying and filing!
