### ISSUE TITLE
Box shadow isn't rendering properly on Firefox for Android

### ISSUE THREAD

**Issue by unknowndev00** [mozilla-mobile/fenix#19724]
## Steps to reproduce
Any boxshadow, when moving or even still
https://pcxx-9eeb0.web.app/
![Screenshot_2021-05-30-21-13-11-996_org mozilla firefox](https://user-images.githubusercontent.com/74982160/120117109-e74b0380-c18b-11eb-8650-5650db4931b0.jpg)

### Expected behavior
Chrome properly opera webview all except firefox
### Actual behavior
Flickering and weird behaviour newest firefox 88

### Device information

Mi 9 lite

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce your issue on Firefox Preview Nightly 31/5 but found no differences from Chrome. @unknowndev00 Could you be more specific about what issues is? A short video illustrating the issue would also help.
### Devices used:
- Google Pixel 3 XL ( Android 9)
- OnePlus 6T (Android 9)

**Comment by unknowndev00** [comment]
Now I tested on Firefox Beta & Nightly, same issue, not on this site, on other sites also where box-shadow is moving...
Chrome Mobile✓ Mi 9 Lite
Opera Mobile✓ Mi 9 Lite
Safari Mobile✓ iPhone, MacOS✓
Firefox on Windows ✓
Chrome Mobile ✓ Samsung SM-500
Firefox Beta & Nightly & Focus ✗ => Same Issue ✗ Mi 9 Lite ✗
Firefox Mobile > Samsung Sm 500 ✓ Works

I was running BrowserStack and apparently, only on my device it doesn't work...Pretty weird...

**Comment by unknowndev00** [comment]
https://streamable.com/933t7t
Video Shadow Bug

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1713931

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Hi @unknowndev00m, thanks for the bug report. Unfortunately his does appear to be a device specific bug as I cannot reproduce on any of my devices.

That's helpful to know that it broke sometime between 79 and 80. We actually have a tool called [mozregression](https://mozilla.github.io/mozregression/quickstart.html) that can narrow it down to _exactly_ which change introduced the bug. If you would be able to run that, it would be incredibly helpful!!

You can either install the GUI application, or if you're running Linux I think it's easier to install it with `pip install mozregression` on the command line. Then plug your phone in to your computer and run the application. In the GUI you need to select the application as "geckoview example" and select 79 and 80 as the good and bad versions. Or if running on the command line, that would be `mozregression --app gve --good 79 --bad 80`.

Then it will launch a version of firefox on your phone. You test whether you can reproduce the bug, and then select either good or bad. Then it will launch another version and you repeat. Eventually this will tell you what change introduced the bug.

If you need any help with that please let me know!
