### ISSUE TITLE
[Bug] security.enterprise_roots.enabled preference isn't persistent

### ISSUE THREAD

**Issue by PolicyPuma4** [mozilla-mobile/fenix#19720]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Set the `security.enterprise_roots.enabled` preference to `true` using the `about:config` page.

### Expected behavior
The `security.enterprise_roots.enabled` preference remains `true`.

### Actual behavior
The `security.enterprise_roots.enabled` preference reverts to the default of `false`. I believe this happens when the app is opened however I am not certain what triggers the reversion.

### Device information

* Device vendor / model and Android version: OnePlus 6T running Android 10
* Firefox for Android version: 89.0.0-beta.10

**Comment by lolrepeatlol** [comment]
dupe of #18733
