### ISSUE TITLE
'Synced Tabs' show hundread thousands of Synced Tabs from Desktop

### ISSUE THREAD

**Issue by hong620** [mozilla-mobile/fenix#19727]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

in Current GUI on Firefox for Android shows all the Synced Tabs from Each Devices trough Firefox Sync.
but Current Firefox Sync only designed for few Tabs usage Scenario.
as example, my firefox on android phone opened under 20 Tabs and firefox on Desktop opened over 1000~1200 tabs and firefox on android tablet opened under 30 tabs.

in typical android, iOS devices, mostly using opened tabs under 50 tabs and current bookmark kind group method fairly capability to deal with those numbers of tabs.
(limited in Device hw and typical usages)

but in Firefox on Desktop, there's no official Massive Tab Groups management methods.
Panorama(Tab Groups) from Mozzila is Obsleted, Major Extension as succed Tab Groups are abandoned, minor tab groups extnsion and they're fork projects are so fragmentized in code or too minor userpools.

Firefox Sync just work it machine like Sync all the Opened Tabs from Firefox's current session, so there's two problem happened.

1. just sync all the tabs that un-neccesity makes Sync Time too much long and enlarge mozzila side traffic costs.
2. in current mobile firefox ui, all the opened(synced) tab lists are shown without groups or proper category that makes hard to see, make to scroll tons of times, even not had search function on that.

if there's no plan to Firefox or Fire Sync considering to handle massive numbers of tabs,
then i guess it should limit from UI or Sync Server side.
or if they really considering to solve massive tabs problem from fundamental,
hope they forcing somekind of TabGrouping and management UI in all the firefox products to handle and sync certain tab groups and thumbnails for privacy.

honestly i'm really want to management desktop side tabs to limit proper ammount of 'Active tabs' to sync and view from tablet (in Official, smooth way),
but it's out of bounce on fenix project teams so guess only i can do is just suggestion on this problem.

### Who will benefit from it?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10831)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813654

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
