### ISSUE TITLE
Add support for entering the tabs tray in multi-select mode

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19739]
This is also a regression in behaviour from the [old tabs tray code](https://searchfox.org/mozilla-mobile/rev/467bb1f46f6cfc61eaa11a3708d5355f81ec80e1/fenix/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt#156).

We support the nav arg, but we don't do anything with it today. 🙂

**Comment by jonalmeida** [comment]
For QA..

## Steps to reproduce
1. Ensure there are no new collections.
2. Ensure you have open tabs in your tray.
3. Click the 'Add to collection' button on the homescreen.
4. Observe the tabs tray open and the state that it is in.

## Expected
- The tabs tray is in multi-select mode.
- Tapping any tab will add it the selection.

## Actual
- The tabs tray is in regular mode.
- Tapping any tab will navigate to that tab.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (91.0a1 - 2021-06-29T05:06:58.580).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).
