### ISSUE TITLE
FNX-5370 ⁃ [Bug] If denying camera access, QR Code scanner still remains selected

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1973]
## Steps to reproduce
1. Tap on the search bar.
1. Tap on Scan.
1. Deny camera access.

### Expected behavior
The scan button is deselected.

### Actual behavior
The scan button remains selected.

### Device information
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * HTC 10 (Android 8)
  * Google Pixel (Android 9)
* Preview version: 1.0.1917 (#11141216)

![gif](https://user-images.githubusercontent.com/17178945/56666044-dd549d80-66b3-11e9-9f3d-e6fd1e38dc8e.gif)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11510609), with Nexus 5 (Android 6.0.1), HTC 10 (Android 8), Motorola Moto G6 (Android 8.0), and Sony Xperia Z5 Premium (Android 7.1.1).
