### ISSUE TITLE
Set secure flag when on the private tabs page of the tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19738]
This is something that the old tabs tray [used to do](https://github.com/mozilla-mobile/fenix/blob/33b27892708d973b8e606c77d99d43cd9c8b12cb/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayDialogFragment.kt#L276-L282) as well.

Should be easy enough with a "SecurePrivateTabBinding" that observes the `TabsTrayState.selectedPage` when it's `Page.PrivateTab` and set the appropriate flags.

You can get some ideas from [`SecureWindowFeature`](https://searchfox.org/mozilla-mobile/source/android-components/components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/feature/SecureWindowFeature.kt#45).

**⚠️ Note:** We need to also be aware if the `BrowsingModeManager` is also private at the same time before we decide to clear the secure flag.

**Comment by jonalmeida** [comment]
cc: @codrut-topliceanu if you're interested. 🙂

**Comment by jonalmeida** [comment]
I think we need to remove the `drop(1)` from SelectBannerBinding and SelectHandleBinding as well.

**Comment by jonalmeida** [comment]
We may be able to re-enable `createFirstCollectionTest` after this lands.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 6/10. I tested the issues with Tab view set to List and Grid.
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)
