### ISSUE TITLE
Unable to input certain combining diacritical marks in text fields

### ISSUE THREAD

**Issue by bickxsler** [mozilla-mobile/fenix#19741]
## Steps to reproduce
Insert one of the following combining diacritics (shown here with a dotted circle for display purposes) in any text field on a web page:
- U+0300 ◌̀ (grave accent)
- U+0301 ◌́ (acute accent)
- U+0302 ◌̂ (circumflex accent)
- U+0303 ◌̃ (tilde)
- U+0308 ◌̈

I've tried this with multiple keyboards ([Unicode Keyboard](https://play.google.com/store/apps/details?id=org.tiwu.unicodekeyboard), [MessagEase](https://play.google.com/store/apps/details?id=com.exideas.mekb)).

### Expected behavior

The diacritic should combine with the preceding character if present, or otherwise appear by itself. This is the behavior in the address bar, and in other apps. This is also the behavior when any other [combining diacritical mark](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks) is inserted.

### Actual behavior

The diacritic does not appear at all. Pressing the delete key confirms that it was not inputted.

### Device information
- Android device: Motorola Moto G6, Android 9
- Fenix versions:
   - 82.1.4 (Build #2015811033)
   - 90.0a1 (Build #2015813641)
   - Firefox Focus 8.15.3 (Build #351242343)

**Comment by kbrosnan** [comment]
The Fenix version is quite old. Does this happen with a current release or better nightly? https://github.com/mozilla-mobile/fenix/wiki#download

**Comment by bickxsler** [comment]
Yes, the problem seems to persist on the current nightly, 90.0a1 (Build #2015813641).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1713959

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
