### ISSUE TITLE
FNX-5371 ⁃ [Bug] Search field shadow is wrong after scrolling down + up

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#1974]
## Steps to reproduce
Open Fenix, open a few tabs, scroll down so that search sticks to top, scroll up again so that search is in the middle of the screen again.

### Expected behavior
Search field has same drop shadow when in center of screen after scrolling down and up again

### Actual behavior
Search field shadow doesn't update and remains as in sticky top position

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1917

With correct shadow
![Screenshot](https://user-images.githubusercontent.com/353960/56667942-fb6bcf00-66ae-11e9-81df-7cc298c0949a.png)UNITO-UNDERSCORE!20190424-163316!

After scrolling
![Screenshot](https://user-images.githubusercontent.com/353960/56667943-fb6bcf00-66ae-11e9-9251-33ac180d1a37.png)UNITO-UNDERSCORE!20190424-163335!

**Comment by sblatz** [comment]
I'm not able to reproduce this anymore

**Comment by kbrosnan** [comment]
I still see this with the April 26th build and cannot reproduce with a build from master pulled a few minutes ago.
