### ISSUE TITLE
[Bug] Tab get's stuck when buying stuff on allegro.pl

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#19751]
## Steps to reproduce
1. Open allegro.pl
2. Login
3. Add something to cart
4. Try to buy it

### Expected behavior
I can finish buying it

### Actual behavior
Firefox content process uses 100% cpu and I cannot interact with page at all
Here is a performance profile of it: https://share.firefox.dev/3pcheLR

### Device information

* Device vendor / model and Android version: Samsung Galaxy J7 2017
* Firefox for Android version: Firefox nightly 90.0a1 (Build #2015813833), happens on release as well.

I reported a very similar (or same) issue here, but it previously stopped reproducing, but now it's back:
https://github.com/mozilla-mobile/fenix/issues/16234

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1714053

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
