### ISSUE TITLE
[Feature:China] Allow modifying the urls & icons of default top sites easily

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#19755]
We need to add default top sites or change the urls & icons sometimes due to revenue reasons. 

For example, we have two big shopping festivals in 18th June and 11th November, in these two periods we need to change the e-commerce topsites to their special festival urls & icons and then after the shooping festivals we need to change them back.

Ideally, if it can be done via remote config that would be the best.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10846)

**Comment by rxumoz** [comment]
What I have done temporarily  and locally is handling the top site urls & icons accroding to the system date. This need us to modify the start date and end date manually before the version update.

This is the commit: https://github.com/MozillaOnline/fenix/commit/8fd9ca65a9a71016320527de622f7097cb5c9630

If you think this can be acceptable as a temporary solution, I can submit the PR.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807949

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
