### ISSUE TITLE
[Bug] can't download PDF on this specific url

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#19757]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Visiting https://t.co/uUyW8RPR8w?amp=1 (a link from Twitter) gives me an infinite loading bar on Fenix.

When opening the same link on edge a PDF is downloaded.

### Expected behavior

A PDF is downloaded.

### Device information

* Device vendor / model and Android version: Android 10 on a Motorola G8 Plus
* Firefox for Android version: current nightly

**Comment by Amejia481** [comment]
Thanks for reporting.
I wasn't able to reproduce on nightly using Android 11, let me ask the QA team to test on Android 10 to verify.

**Comment by emilio** [comment]
I couldn't reproduce later today on the same phone, so perhaps an spurious server error?

**Comment by lobontiumira** [comment]
I cannot reproduce this issue either.
Tested on the 6/16 Nightly build with Google Pixel (Android 10).
