### ISSUE TITLE
Search engine selection based on typed text shows default search engine

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#19766]
## Steps to reproduce
1. Launch Firefox Preview
2. Tap the search bar.
3. Enter the first letter of the default search engine.

### Expected behavior
The default search engine suggestion based on typed text should not be shown.
### Actual behavior
A prompt allowing to search with the default search engine will be displayed above the search suggestions.
### Device information

* Device vendor / model and Android version: Huawei MediaPad M3 (Android 7.0), OnePlus 6T (Android 9)
* Firefox for Android version: Firefox Preview 90.0.0-beta.1, Nightly 2/6
![search_suggestion](https://user-images.githubusercontent.com/50983519/120476220-feb80580-c3b2-11eb-9eac-cc626c9d146f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10855)

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible on the:
- latest Nightly 96.0a1 (2021-12-03).
- latest Beta (95.0.0-beta6).
- latest RC (95.1.0).

Device used: Xiaomi Mi11 Lite (Android11).

**Comment by amocirean** [comment]
This issue is still reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using Samsung Galaxy S22 Ultra (Android 13) and Oppo Find X3 Neo.
Removing the wontfix label.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807566

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
