### ISSUE TITLE
[UX investigation] Fenix forms audit

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#19763]
> We should do an audit of our forms and align them – that might take a moment. I'll add it to my list.

_Originally posted by @topotropic in https://github.com/mozilla-mobile/fenix/issues/19419#issuecomment-842174903_

**Comment by kbrosnan** [comment]
Anyone interested in this should talk with @emilio as well. AFIK we moved to non-native form controls that are more consistent cross platform.

**Comment by emilio** [comment]
Yeah, our forms now are consistent with desktop. Unless there's a reason to change them I'd rather keep them the same.
