### ISSUE TITLE
[Bug]  “Select credit card” prompt doesn’t show up anymore

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19764]
Based on a discussion with @gabrielluong about the prompt not appearing when testing on https://checkout.stripe.dev/preview on the latest Nightly.

Tested this and while initially I was thinking that it could be an issue with GV that doesn't properly identify the CC fields or even a race condition in AC it seems that everything works as expected.

Asking @gabrielluong / QA for more details about the scenarios in which such an issue can be observed.

**Comment by abodea** [comment]
Hello, @Mugurell is this fixed or only for investigation?

**Comment by abodea** [comment]
Please note that I tested with https://checkout.stripe.dev/preview and instant-gaming.com.
I tried to autofill with a saved card more than 15 times, but I was able all the time no issue regarding this.
Note that I tried with only one card but also when I had more cards saved.

**Comment by Mugurell** [comment]
> Hello, @Mugurell is this fixed or only for investigation?

This would be just as a double check for the feature.
Gabriel saw the prompt not appearing but then was unable to reproduce anymore.

Thank you for checking it!
With no other reports I think this can be closed.

**Comment by abodea** [comment]
Thank you @Mugurell, changed the labels accordingly!
