### ISSUE TITLE
FNX-5374 ⁃ [Bug] Home page navigation in inverted in landscape mode

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#1977]
## Steps to reproduce
1. In landscape mode scroll up.

### Expected behavior
The page scrolls up and the open tabs section is displayed.

### Actual behavior
Nothing happens, you have to scroll down in order for the open tabs section to be displayed.
If having multiple tabs open navigation is not possible as scrolling up displays the logo and search bar.

### Device information
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * HTC 10 (Android 8)
* Preview version: 1.0.1917 (#11141216)

![gif](https://user-images.githubusercontent.com/17178945/56669399-c1ec9100-66b9-11e9-8c59-d4530a269b4a.gif)

**Comment by softvision-miralobontiu** [comment]
This issue is no longer reproducible on the latest build 1.0.1920 (#11350639), therefore it will be closed.
Tested with: Nexus 5 (Android 6.0.1), HTC 10 (Android 8), Google Pixel (Android 9), Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by bsurd** [comment]
STR:
1. Have a couple of pages opened in normal or private mode.
2. Scroll the page (up/down).

Expected:
The page scrolls exactly like in portrait mode.

Actual:
The page animation is different from portrait mode. Please see attached gif from [comment 0](https://github.com/mozilla-mobile/fenix/issues/1977#issue-436744554).

**Comment by boek** [comment]
@bsurd We've updated some dependencies since this was filed. I can't reproduce it on my pixel or S9. Can you still reproduce?

**Comment by softvision-miralobontiu** [comment]
Hi,
I wasn't able to reproduce this issue anymore on the latest build 1.0.1923 (#11561806), with Nexus 5 (Android 6.0.1), and HTC 10 (Android 8).
