### ISSUE TITLE
Start on Home

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#19789]
After being away from the browser for X hours, I like to open the app on HOME so I can start fresh and not be distracted by the last open tab which may no longer be relevant. Related [ticket](https://jira.mozilla.com/browse/FNX-22155).

**Acceptance Criteria:**

- I open the app on HOME after X hours of inactivity (default X tbd later). Inactivity counter starts when app goes to background and we can go with 4 hours as X for iteration 1)
- Bringing custom tab to the foreground does not count as activity
- Going to the background counts as an inactivity
- There is a user-facing setting to change the value of X (predefined values not custom) => this is a P2 but important to call out easily so it is considered in development strategy.

**Comment by cadeyrn** [comment]
@Amejia481 Thanks for working on it!

> There is a user-facing setting to change the value of X (predefined values not custom) => this is a P2 but important to call out easily so it is considered in development strategy.

Could you also consider a value that in fact means: always open on home screen? Well, maybe it still makes sense to open the last open tab if you close Firefox and open it again after a few seconds but a value smaller than one day (like one minute or at least one hour) would be awesome. I almost never want to start with the last open tab.

**Comment by Amejia481** [comment]
Thanks for the feedback @cadeyrn, that sounds `always` like an awesome idea, I will circle back with product to see what they think, maybe we could have `always`, `never` and an spesific set of time.

**Comment by Amejia481** [comment]
QA team please help us to verify this feature is working as expected.

We want to cover the following cases:

1. Users should should only start on home on cold starts when selecting the options **after 4 hours** or **always**, and they have opened tabs.
2. When selecting never on cold starts users should go directly should never see the home screen when they have opened tabs.
3. When a page is open via an external app link, users should always to the browser screen independently of their settings.
4. When users don't have opened tabs should always start on home independently of their settings. 


To test case 1, you can alter your OS data & time, to go further in time, but try to do it on an emulator not on your personal phone, as this could cause other apps to not work.

To access the start on home feature, you have to go to `Settings` -> `Tabs` -> `Start on home`.

![image](https://user-images.githubusercontent.com/773158/121083896-fb0af100-c7ad-11eb-81b8-2d2bb22f6223.png)

**Comment by Amejia481** [comment]
Thanks @lobontiumira!
