### ISSUE TITLE
[Bug] Buttons and Boxes are not displayed correctly (after updating to 89.1.1)

### ISSUE THREAD

**Issue by Siva981** [mozilla-mobile/fenix#19782]
## Steps to reproduce
Buttons and boxes on web pages are not being displayed properly after I updated my Firefox For Android from version 88.1.4 to version 89.1.1.
Open any page with buttons or editable boxes to reproduce issue. For example, open the basic HTML version of gmail using this link: 
https://mail.google.com/mail/u/0/h/

### Expected behavior
Buttons and boxes should appear normally as they were getting displayed on version 88.1.4

### Actual behavior
Buttons and boxes on pages are not displayed correctly. 
1) They have these weird little triangle or square shaped structures on their corners. 
2) They are not rounded off properly.
3) Weird structures seem to appear around boxes while I am typing inside them. They are appearing even around this github issue creation box, the one where I am typing this to create an issue.
4) Colors of the buttons does not seem to be accurate.

### Device information

* Device vendor / model and Android version: 
Swipe Elite Plus
Android 5.0.1

* Firefox for Android version:
89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

### Screenshots
 
![Screenshot_2021-06-03-02-25-57](https://user-images.githubusercontent.com/44178186/120560353-2db89080-c420-11eb-91dd-1933de8a14a8.png)
.

![Screenshot_2021-06-03-02-25-34](https://user-images.githubusercontent.com/44178186/120560360-301aea80-c420-11eb-9adb-5f94c3aaa95d.png)
.

![Screenshot_2021-06-03-02-24-12](https://user-images.githubusercontent.com/44178186/120560362-314c1780-c420-11eb-88c1-edf9ec92e612.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10865)

**Comment by AndRo-Marian** [comment]
Same weird artefacts, radio buttons disappeared, random. Still the text inside a button is not centered correctly vertically.

**Comment by SoftVision-LorandJanos** [comment]
Hi @Siva981 ! Thank you for your report! I wasn't able to reproduce the issue as is described above. I've tried it with the closest I got to your Android version (Android 6.0.1) on an LG Nexus 5, also with a Samsung Galaxy Tab 3 with Android 9 and with a Google Pixel 4 with Android 11. All with the above mentioned Firefox version. All the buttons and boxes were displayed correctly. Could you maybe try a clear data and see if the issue remains? And if it happens on the latest Nightly as well? Thank you!

**Comment by Siva981** [comment]
> Hi @Siva981 ! Thank you for your report! I wasn't able to reproduce the issue as is described above. I've tried it with the closest I got to your Android version (Android 6.0.1) on an LG Nexus 5, also with a Samsung Galaxy Tab 3 with Android 9 and with a Google Pixel 4 with Android 11. All with the above mentioned Firefox version. All the buttons and boxes were displayed correctly. Could you maybe try a clear data and see if the issue remains? And if it happens on the latest Nightly as well? Thank you!

Hi @SoftVision-LorandJanos,

Thank you for taking a look into this issue. 

I spent a considerable amount of time today, testing this out again in both the apps. I would really appreciate it, if you could kindly get hold of an Android 5.x device to test it from your end.

## Testing 
Per your request, I have tested with the following apps again, using my Android 5.0.1 mobile (Swipe Elite Plus):

1) Firefox For Android (version 89.1.1), after performing a " Clear Data " for this app in my Android Settings.

2) In the latest Firefox Nightly For Android, with the following version and build:

91.0a1 (Build #2015815755)
AC: 91.0.20210611143123, 143ffac776
GV: 91.0a1-20210608091819
AS: 78.0.0
Friday 6/11 @ 5:40 PM

## Testing Results

The results are the same as before in both the apps.
1) All editable boxes seem to have a double border, with tiny square shaped structures at the 4 corners of the box.
2) Whenever I start typing into an editable box, weirdly shaped structures start to randomly appear and disappear in and around the box's sides. Sometimes these structures are large enough to block whatever I am typing inside the box.
3) Non-editable boxes (clickable buttons) have the weird borders too, along with similar tiny squares at their corners.
4) Option Buttons (Radio Buttons) are completely out of shape. Instead of tiny clickable circles, they appear like these weirdly shaped, large commas.
5) Images (photos) displayed on pages have these weird structures forming around them too, sometimes large enough to hide the image.
6) Clickable Links on pages have these weird structures too.

## Screenshots (all from Nightly)

1) Clickable Buttons from Gmail HTML version, with tiny squares at their corners.

![IMG_20210613_001451](https://user-images.githubusercontent.com/44178186/121791549-89e19880-cc08-11eb-8c04-4e79cce291f4.jpg) 

----
2) Editable Box in Gmail HTML version. Note the double border, and also the tiny squares at the corners of the box.

![IMG_20210613_001549](https://user-images.githubusercontent.com/44178186/121791572-d4631500-cc08-11eb-96e4-21bbb1a2d074.jpg)

----
3) Compose New Email page from Gmail HTML version. Note the weird structures in and around the editable boxes. These weird structures are formed in and around clickable links and images (photos in pages) as well.

![IMG_20210613_002537](https://user-images.githubusercontent.com/44178186/121791611-6ff48580-cc09-11eb-9def-7f10ff9d2e0e.jpg)

----
4) Settings page from Gmail HTML version. Radio buttons are displayed as large, comma shaped structures.

![IMG_20210613_002731](https://user-images.githubusercontent.com/44178186/121791619-869adc80-cc09-11eb-82fb-2888203e38aa.jpg)

----
5) Setup page of my Internet router (modem). Radio buttons are large commas again.

![IMG_20210613_002828](https://user-images.githubusercontent.com/44178186/121791622-99151600-cc09-11eb-8973-3603b592763e.jpg)

----
6) Setup page of my Internet router (modem). 
Weird structures around editable box.

![IMG_20210613_002917](https://user-images.githubusercontent.com/44178186/121791626-a3cfab00-cc09-11eb-8900-60fbf4f7107f.jpg)

----
7) Clickable Buttons from Github, with tiny squares at their corners.

![IMG_20210613_003023](https://user-images.githubusercontent.com/44178186/121791636-bf3ab600-cc09-11eb-8d6f-df52d8d95a00.jpg)

----
8) Editable Boxes from Github login page, with weird structures around them and tiny squares at their corners.

![IMG_20210613_003219](https://user-images.githubusercontent.com/44178186/121791642-cbbf0e80-cc09-11eb-9f64-64e2226a40ba.jpg)

----
9) Github 'bug report' page. Editable title box.

![IMG_20210613_003350](https://user-images.githubusercontent.com/44178186/121791646-d5487680-cc09-11eb-93eb-35f5bd12b6f2.jpg)

----
10) Github 'bug report' page. Editable issue description box.

![IMG_20210613_003509](https://user-images.githubusercontent.com/44178186/121791654-ded1de80-cc09-11eb-9ac2-6c55d11a6638.jpg)

----
11)  Github 'bug report' page. Editable issue description box.

![IMG_20210613_003553](https://user-images.githubusercontent.com/44178186/121791658-eee9be00-cc09-11eb-9b11-34cb24cbf12f.jpg)

----
12)  Github 'bug report' page. Editable issue description box.

![IMG_20210613_003725](https://user-images.githubusercontent.com/44178186/121791661-fa3ce980-cc09-11eb-8ab0-3755d9917ddd.jpg)

----

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/19783

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/19783

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20323

**Comment by AndRo-Marian** [comment]
I don't belive this issue is not fixed already.
What I say, the desktop version is the same, worse and worse, firefox becomes a mess.
Sadly to see a good product goind downhill in one year.

On Nightly
![Screenshot_20211227-232519](https://user-images.githubusercontent.com/48178307/147508777-3930eb44-c323-4493-9de0-a93fc06946e0.jpg)

**Comment by delia-pop** [comment]
Hello, @Siva981 

I was not able to reproduce this issue on the latest Nightly (100.0a1 from 04/04), Release 99.1.1, nor Beta (99.0.0-beta5) builds. All the page elements are properly displayed on my side. 

Can you please re-test and let me know if this is still an issue for you? Thank you in advance.

Device used:
- Huawei MediaPad M2 (Android 5.1.1).

![Screenshot_2022-04-04-13-34-49](https://user-images.githubusercontent.com/89388888/161530552-2e0c8d6f-af52-452b-afb2-dfcf5fb35143.png)

**Comment by Siva981** [comment]
Hi @delia-pop, 

I can confirm that the weird structures issue is still well and alive in my device (Android 5.0.1). 

That said, the issue with buttons, borders of boxes, etc, are solved now.

Meaning, 

1) The weird structures issue (the one I had reported in #19783 and then later in #22563) is still there. 

2) The clickable buttons, radio buttons, issue (the one related to this issue, #19782) is solved.

My Firefox For Android: 
98.3.0 (Build #2015870331), b1a12ce69+
AC: 98.0.13, a31f2c481a
GV: 98.0.2-20220322144853
AS: 91.0.1 

2022-03-22T23:42:26.826530
