### ISSUE TITLE
[Bug] Double Click to zoom not working in Gmail HTML view (after upating to 89.1.1)

### ISSUE THREAD

**Issue by Siva981** [mozilla-mobile/fenix#19787]
## Steps to reproduce
Up until Firefox for Android version 88.1.4, while using the basic HTML view of Gmail, I was able to double click on the sender's name of any email in the inbox, which would zoom the page to readable size. 

After updating to Firefox For Android 89.1.1, double clicking on the sender's name of an email in the inbox does very little to no zooming. Even the pinch to zoom works very very slowly. 

To reproduce the issue: 
1) Open Gmail HTML using the following link
https://mail.google.com/mail/u/0/h/
2) While you are still in the Inbox, double click on the sender's name of any email. Please refer attached screenshot for a general idea on where to double click.
3) Pinch to zoom in the inbox.

### Expected behavior
In the Gmail HTML view,
1) Pinch to zoom should not happen in slow motion. 
2) Double clicking on the sender's name on any email in the inbox should zoom-in the page, large enough to readable level. 

Please refer attached screenshots for actual and expected zoom levels. Or, you could test it with Firefox For Android version 88.1.4 to see the difference.

### Actual behavior
In the Gmail HTML view,
1) Pinch to zoom is happening in slow motion.
2) Zooming is not upto expected level when double clicking on the sender's name of any email in the inbox.

### Device information

* Device vendor / model and Android version: 
Swipe Elite Plus
Android 5.0.1

* Firefox for Android version:
89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

### Screenshots

Double click anywhere on the highlighted area.

![IMG_20210603_054229](https://user-images.githubusercontent.com/44178186/120567185-c0f8c280-c42e-11eb-8c3b-9cca82c005f8.jpg)
.
Actual Zoom Level after double clicking

![Screenshot_2021-06-03-05-28-03](https://user-images.githubusercontent.com/44178186/120567311-11702000-c42f-11eb-8110-bf47f256d154.png)
.
Expected zoom level after double clicking

![Screenshot_2021-06-03-05-38-02](https://user-images.githubusercontent.com/44178186/120567327-20ef6900-c42f-11eb-92f5-3269c7834de5.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10869)

**Comment by SoftVision-LorandJanos** [comment]
Hi @Siva981 ! Thank you for your report! I managed to reproduce the issue you described.
Tested on a Samsung Galaxy Tab 3 with Android 9.

**Comment by Siva981** [comment]
Hi @SoftVision-LorandJanos,

Do we have any updates on this issue? 

The bot comment above says that this issue is about to be auto-closed due to inactivity. 

The issue still exists on my Firefox For Android. 

94.1.2 (Build #2015844587)
AC: 94.0.12, e5eb726f81
GV: 94.0-20211028161635
AS: 85.4.0 

2021-11-08T21:26:04.605951 

Thank You In Advance!
