### ISSUE TITLE
Investigate and remove feature flag for WebAuthn

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19785]
We added a feature flag and this ticket is to track the removal of the flag to let it ride the trains.

Tracking feature: https://github.com/mozilla-mobile/fenix/issues/1340

### Potential Blockers
 - [ ] [#18347][18347] - [Bug] WebAuthn implementation doesn't allow retry
 - [ ] [#17688][17688] - Support Opting-in to Direct Attestations on Android
 - [x] BZ-1711541 - PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable returns false even when supported
 - [x] BZ-1689612 - WebAuthn does not specify the authenticator type during attestation

[18347]: https://github.com/mozilla-mobile/fenix/issues/18347
[17688]: https://github.com/mozilla-mobile/fenix/issues/17688

**Comment by sbrl** [comment]
....but the new Firefox for Android beta doesn't support Webauthn, does it? At least it's never worked for me.

**Comment by mhalano** [comment]
@sbrl For now, I think it just works in Firefox Nightly. I opened another issue to enable the feature in beta since the nightly has the feature for some time.

**Comment by jonalmeida** [comment]
With the two main GV bugs fixed, we should let this ride the trains.

The remaining two bugs should be fixed, but they are not blocking core functionality.

**Comment by mhalano** [comment]
Unfortunately, the repo was already branched to 91.0 release, so I think this change will come just during 92.0 cycle. Although, better later than never, should I say.

**Comment by Chaz6** [comment]
I would really like to be able to use my FIDO U2F keys with firefox on android, so the sooner this gets landed the better! Thank you.

**Comment by mhalano** [comment]
@Chaz6 Seems it will be released in the Firefox 92.0.

**Comment by mhalano** [comment]
I just received the 92.0 version and I can confirm WebAuthn is working. Thanks everybody.

**Comment by Chaz6** [comment]
> @Chaz6 Seems it will be released in the Firefox 92.0.

Thank you!
