### ISSUE TITLE
[Bug] Vibration has been triggered 3 times when long press on web pages

### ISSUE THREAD

**Issue by junjieyuan** [mozilla-mobile/fenix#19795]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Long press on web pages.

### Expected behavior
Vibration 1 time.

### Actual behavior
Vibration 3 times.

### Device information

* Device vendor / model and Android version: OnePlus 8T, Osygen OS 11.0.8.12.KB05AA
* Firefox for Android version: 89.1.1 (Build #2015812947) AC: 75.0.22, 5204f4025 GV: 89.0-20210527174632 AS: 74.0.1 Friday 5/28 @ 2:05 AM

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10875)

**Comment by junjieyuan** [comment]
See also: #18015

**Comment by SoftVision-LorandJanos** [comment]
Hi @junjieyuan! I couldn't reproduce this issue. It only vibrates ones on the devices I tested.
Is it the same behavior with the latest (clean) builds?
Could you check this with another device as well?
Tested on the latest Nightly 97.0a1 (2021-12-28).
Devices used: 
- Google Pixel 4 (Android 11).
- Samsung Galaxy Tab 3 (Android 9).
- Motorola Nexus 6 (Android 7.1.1).

**Comment by junjieyuan** [comment]
> Hi @junjieyuan! I couldn't reproduce this issue. It only vibrates ones on the devices I tested. Is it the same behavior with the latest (clean) builds? Could you check this with another device as well? Tested on the latest Nightly 97.0a1 (2021-12-28). Devices used:
> 
> * Google Pixel 4 (Android 11).
> * Samsung Galaxy Tab 3 (Android 9).
> * Motorola Nexus 6 (Android 7.1.1).

Hi, @SoftVision-LorandJanos. I still can reproduce this issue on just installed Firefox Nightly 97.0a1. My phone is OnePlus 8T, running OxygenOS 11.

I guess this problem is related to the type of vibration motor of the mobile phone, the same vibration time has different vibration effects on a rotor motor and a linear motor. OnePlus 8T is equipped with a linear vibration motor, which is similar to modern iPhones.
