### ISSUE TITLE
[Bug] The "Sign in to sync" option from the three-dot menu is inactive after changing the password

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#19797]
## Steps to reproduce
1. Sign in with the same account on Desktop, and on mobile.
2. From Desktop, change the password.
3. On mobile trigger sync.
4. After the "Reconnect to sync" option is displayed on the three-dot main menu, open a page.
5. Tap on the three-dot menu from the page. Or tap on the three-dot menu from the homescreen.
6. Tap on "Sign in to sync".

### Expected behavior
The user is redirected to the "Reconnect to Sync" page.

### Actual behavior
Nothing happens. The menu is dismissed.

### Device information
* Devices: Google Pixel (Android 10), Samsung Galaxy Tab A6 (Android 5.1.1), OnePlus A3 (Android 6.0.1)
* Firefox for Android version: Beta 90.0.0-beta.1, RC 89.1.1, and Nightly 91.0a1 from 6/3
* Reproducible in Beta 89.0.0-beta.10 as well

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/6589450/logcat.txt)

https://user-images.githubusercontent.com/40694158/120599297-ffeb4000-c44f-11eb-876b-43f18f1b6115.mp4

* **On OnePlus A3, and Samsung Galaxy Tab A6, the account is still displayed along with the error message**:

![Untitled](https://user-images.githubusercontent.com/40694158/120599024-a6831100-c44f-11eb-82cf-7c1ea6ce0d0f.png)

**Comment by gabrielluong** [comment]
@eliserichards do you have any idea if this is a regression from the old toolbar that we can reference for more context on how to fix this or was this a new menu items?
