### ISSUE TITLE
Redesign the tabs list

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#19790]
Make a redesign of the tab list.

1. Move the top bar buttons to bottom: tabs, private synced, and the create nre tab icon. To be like the address bar with the buttons on it.
2. On top will be the gap to resize the window.
3. A way to make tabs on 2 columns.

**Comment by cadeyrn** [comment]
> A way to make tabs on 2 columns.

This is already implemented. You should have a look at the tab settings.

**Comment by LaurentiuApahideanSV** [comment]
The features have been implemented in Firefox Preview RC 89.1.1. You can activate them by going to Settings -> Tabs and select the Grid view.
