### ISSUE TITLE
Add content description to the FAB in the tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19792]
We don't set the content string `add_private_tab` and `add_tab`.

We should add this to the `FloatingActionButtonBinding` and `AccessibleNewTabButtonBinding` when we update the UI on page switching.

**Comment by gabrielluong** [comment]
Relevant code and strings that can be reused can be found at https://github.com/mozilla-mobile/fenix/pull/19740#discussion_r644331580

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 6/10.

### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)
