### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sethtara** [mozilla-mobile/fenix#19798]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### config page is not working it just gets stuck as the screenshot below 
<img src="https://user-images.githubusercontent.com/48066700/120622636-84d55a00-c44e-11eb-9336-033f3e1f0741.png" height="450" />

* Device nokia / 5 and Android version: 9 pie
* Firefox for Android version: 89.0

**Comment by mcarare** [comment]
Closing as dupicate of https://github.com/mozilla-mobile/fenix/issues/7865.

**Comment by vehosah** [comment]
> Thanks for reporting! Closing as duplicate of #7865.

Which is locked
