### ISSUE TITLE
Change default tabs tray layout to grid view

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19809]
## User Story

As a user, I want to view my tabs in the grid view thumbnail) format so it's easier for me to quickly locate the specific tab I want to get back to.

## Acceptance Criteria
 * My default tabs setting is GRID view.
 * Disable the existing "grid view" CFR
 * When I open the tabs tray for the first time after updating the app, I see a message telling me that the default setting has changed. (To ENG: you can exclude this criteria for now when sizing this ticket, it's not required for iteration 1)

Linked JIRA: [FNX-22614](https://jira.mozilla.com/browse/FNX-22614)

**Comment by jonalmeida** [comment]
I sized this as 1 because this is just a matter of changing the default pref in our settings and removing the CFR code (which exists in [TabsTrayInfoBannerBinding](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInfoBannerBinding.kt)).

**Comment by cadeyrn** [comment]
@jonalmeida 

> Locate tabs easier

In my opinion it's MUCH easier to locate the tabs with the current list view. If you want to change the default, it's fine, I can change it back. But I don't agree that it will help to reach this specific goal.

With the grid view:

- … I get larger thumbnails but the bigger size doesn't add any value because I can see exactly the same
- … I can see **less tabs** at once
- … the title of every tab is **much shorter** and uesless in many cases
- … the URL of every tab is **completely missing** 

So how exactly is the grid view supposed to help to locate my tabs easier? For me it's pretty obvious that the grid view makes it harder to find tabs. 🧐

**Comment by jonalmeida** [comment]
Thanks for discussing @cadeyrn ! 

> … I get larger thumbnails but the bigger size doesn't add any value because I can see exactly the same

Based on telemetry and [experimentation data](https://bugzilla.mozilla.org/show_bug.cgi?id=1386755), it showed that more people preferred grid view as the default across all channels (nightly/beta/release). From what I understand, the bigger thumbnail to identify a tab but that's just my personal guess.

> … I can see less tabs at once
> … the title of every tab is much shorter and useless in some cases
> … the URL of every tab is completely missing

This is a good point, we should definitely re-evaluate if we make the grid layout smaller so that we can see more. We had taken some original designs based on Fennec because folks like that UI a lot and allowed us to get the feature out quicker, but we can iterate on this faster now in Fenix ⚡ .

I personally like the list layout as well, but it seems like the majority preference is grid. 🙂 

FYI: this will not change your existing preference, this is just the default for new users.

**Comment by kythyria** [comment]
> … I can see less tabs at once

In portrait, certainly. In landscape I see *more* tabs at once with grid view instead of less: three rather than one (but have to scroll further).

**Comment by cadeyrn** [comment]
You can assume that most people use their smartphone, especially when browsing in the web, in portrait mode. And since it's about the default layout I was arguing about the default usage. 😉

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Nightly build from 6/10 with Google Pixel (Android 10), Samsung Galaxy Tab A6 (Android 5.1.1), and HTC 10 (Android 8).
