### ISSUE TITLE
Reduce time settings takes on start up

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19804]
Specific issues we saw:
- isDefault values don't need to resolve immediately
- ^ isDefaultBrowser takes a while

**Comment by mcomella** [comment]
By migrating to `DataStore` https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html?linkId=98693079, we may partially address this issue here and throughout the app. We also have a spike to investigate DataStore in https://github.com/mozilla-mobile/fenix/issues/19197.

**Comment by MarcLeclair** [comment]
Closed with #20116
