### ISSUE TITLE
Try moving Gecko init earlier: does it improve time to navStart?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19805]

**Comment by MarcLeclair** [comment]
After removing CrashReporter + Glean + StartupPerf pings at the beginning,  I saw an average of 100ms (or so ) gains for VIEW.

This is using a g5+ and navigating to https://cnn.com.

5 runs without change:

```
{'max': 1782.0,
 'mean': 1772.4,
 'median': 1774.0,
 'min': 1763.0,
 'replicate_count': 5,
 'replicates': [1782.0, 1777.0, 1774.0, 1766.0, 1763.0]}
```

5 runs with the changes: 

```
{'max': 1682.0,
 'mean': 1673.0,
 'median': 1671.0,
 'min': 1664.0,
 'replicate_count': 5,
 'replicates': [1677.0, 1671.0, 1664.0, 1682.0, 1671.0]}
```

Profile accompanying the changes: https://share.firefox.dev/3q4v9nC
