### ISSUE TITLE
[Bug] URL bar pops down while scrolling down the page every now and then

### ISSUE THREAD

**Issue by lordgurke** [mozilla-mobile/fenix#19806]
## Steps to reproduce
* Open a site taller than your device's display
* Continously scroll down
* URL bar pops down every now and then without any obvious reason

### Expected behavior
* URL bar remains hidden as long as the URL remains unchanged and no scrolling upwards is done (as it was before)

### Actual behavior
* URL bar pops down, which is very irritating
* This happens on some sites more often than on others. As said, I didn't find a pattern

### Device information
* Device vendor / model and Android version: OnePlus 8 Pro, Android 11
* Firefox for Android version: 89.1.1 (Build #2015812947)

https://user-images.githubusercontent.com/25770486/120709920-c4875a80-c4bd-11eb-845e-a66fb5082e1f.mp4

**Comment by SoftVision-LorandJanos** [comment]
Hi @lordgurke ! Thank you for your report! I can reproduce the issue you described above. However this issue was covered in #[16352](https://github.com/mozilla-mobile/fenix/issues/16352). I will close it as a duplicate.
