### ISSUE TITLE
[Bug] [TabsTray] Tab previews are cut off

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19815]
As in the previous implementation (as seen in the current release version of the app) tabs should expand to the bottom of the screen.
In the current Nightly they are cut off. Both in portrait and landscape, both when shown as list or as grid. 

https://user-images.githubusercontent.com/11428869/120752892-0db5c980-c513-11eb-9a10-f47b8e9c110f.mp4

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/17 Nightly build with Samsung Galaxy Tab A6 (Android 5.1.1), OnePlus 5T (Android 10), and Google Pixel (Android 10).
