### ISSUE TITLE
Slide up the address bar can show tabs list, please

### ISSUE THREAD

**Issue by Im-Ian-Chen** [mozilla-mobile/fenix#19814]
when i use my phone on my left hand, i don't want to swipe up on address again and again to get that page.(some people's finger is short, like me, hahaha, it's a trouble to choose button of tabs list).  

we can just slide up the address bar and choose that page.  

chrome have this feature, and I've been hope it does on Firefox.  

my English is not good, i hope you guys can understand it.  

Thank you very much！

**Comment by Dunexus** [comment]
Thank you for your contribution.
This is already covered by https://github.com/mozilla-mobile/fenix/issues/11862

**Comment by Im-Ian-Chen** [comment]
> Thank you for your contribution.
> This is already covered by #11862

Oh, I'm sorry for this repeated question.  
I think i should close this issue  

Thank you again
