### ISSUE TITLE
[Bug][TabsTray] Rotating the screen shows tabs tray expanding in stages

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19816]
This issue exists in the previous implementation (as seen in the current release version of the app) and will be seen after https://github.com/mozilla-mobile/fenix/issues/19135

## Steps to reproduce
- have at max two tabs opened so that the tabs tray needs to be shown as collapsed in portrait
- with the device in landscape mode open tabs tray
- with the tray open rotate the device to portrait

### Expected behavior
No visible hiccups when changing from the expanded mode shown in landscape to the collapsed mode shown in portrait.

### Actual behavior
The tray is shown with a smaller height, jumping to the collapsed tray height after.

Video showing the issue in the current release version:

https://user-images.githubusercontent.com/11428869/120754628-9b92b400-c515-11eb-8e34-d482e2161098.mp4

**Comment by gabrielluong** [comment]
Only adding this for backlog tracking for now. I think we want to align on what we should expect and then prioritize this issue as appropriate.

**Comment by jonalmeida** [comment]
I don't see this bug in nightly. I can reproduce it when running a build of #19812.

**Comment by Mugurell** [comment]
@jonalmeida Looked into this but it doesn't seem like an improvement can be made.
The scenario is simple: when the screen is rotated we change the state of the tray this resulting in a change of it's height.
But there is no way to sync this layout update with the screen rotation. (tried using some viewTreeObservers. Still in vain)

So I see two possible approaches for this issue:
- acknowledge it but wontfix. This issue already existed with the previous implementation and there weren't many user reports about it.
- close and reopen the tray (or just leave it closed) for every screen rotation. We are doing this for the menus already but it may be seen as a disruptive UX.

**Comment by jonalmeida** [comment]
@Mugurell thank you for looking into this!

Acknowledging it as wontfix would be the best low-effort solution for now in that case. I'd stay away from close/re-open as a solution for the same UX concerns - you could also be in the middle of selection mode or scrolling through a long tabs list when a user's phone rotates and it would be pretty frustrating to lose that state.

**Comment by Mugurell** [comment]
Based on the fact that when rotating the screen we need the tray to change state and this bug being about this change  being visible I'm closing this as WONTFIX. (CANTFIX actually).
