### ISSUE TITLE
[Bug] Closing the private tab in the private Tab View and undoing this action (restoring the page) moves you to the non-private Tab View

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#19819]
## Steps to reproduce
1. Open at least two private tabs
2. (Optional) Open at least one non-private tab (to see details of the issue)
3. Go to the private Tab View
4. Close any private tab
5. Undo this action

### Expected behavior
User canceled the action and remained in the private Tab View

https://user-images.githubusercontent.com/85299944/120802089-b3d0f600-c54a-11eb-825d-342da82b2174.mp4
### Actual behavior
User canceled the action but was switched to the non-private Tab View

### Device information

* Device vendor / model and Android version: Samsung Galaxy A20s (ARM64) with Android 10, Samsung Galaxy J2 Prime (ARMv7) with Android 6.0.1
* Firefox for Android version: 89.1.1
## Video
https://user-images.githubusercontent.com/85299944/120783282-8af13680-c533-11eb-900c-56bc71b27a9e.mp4
### Note
This issue occurs only in 89 branch

**Comment by SoftVision-LorandJanos** [comment]
Hi @Nickoriginal ! I can reproduce the issue you described above.
Verified using a Samsung Galaxy Tab 3 with Android 9.
Firefox for Android version: 89.1.1.
