### ISSUE TITLE
FNX-5378 ⁃ List bookmarks and/or history on new tab page

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1981]
## Steps to reproduce
Tap "New tab".

### Expected behavior
Show a list of bookmarks and/or tab history, similar to Fennec.
I think it should automatically be shown, but a button next to "Scan" and "Shortcuts" could work.
Would require fewer taps/less time.

### Actual behavior
Screen is blank.

### Device information
Samsung Galaxy S8

```
Android device:
Android 9 Pie
```

```
Fenix version:
1.0.1917 (Build #11141217)
```

**Comment by lime124** [comment]
this would be part of a bigger effort to take a look at all the issues that are part of the homescreen/new tab screens. removing need ux label.

**Comment by topotropic** [comment]
Closing as dup of #3677

**Comment by madb1lly** [comment]
@topotropic that issue links to #1487 which only stricyly addresses bookmarks, so can you add history (and also synced tabs?) to that issue or do we need to raise a new issue to get quick access to history back on the list of things to be reconsidered?
