### ISSUE TITLE
[Bug] [TabsTray] Number of columns in grid layouts needs to be updated when rotating screen

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19813]
Currently the grid layout is set to have two columns in portrait mode and 4 columns in landscape mode.
This same values are kept when rotating the screen leading too big / too small tab previews.

Recording from the current Nightly:

https://user-images.githubusercontent.com/11428869/120752177-ea3e4f00-c511-11eb-876f-7bc9f961c0e0.mp4

**Comment by Mugurell** [comment]
Blocked on deciding whether the tray will be closed upon screen rotation or not - https://github.com/mozilla-mobile/fenix/issues/19816

**Comment by Mugurell** [comment]
https://github.com/mozilla-mobile/fenix/issues/19816 seems like an issue that we'll have to live with.
If not closing the tray to avoid that bug this ticket is ready to be picked up.

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/18 Nightly build with Google Pixel (Android 10), and Xiaomi mi4i (Android 5.0.2).
