### ISSUE TITLE
Swiping down on the landscape tray collpases it making it unusable

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19817]
Issue existing in both the old and the new implementation.
The portrait tray supports two states (expanded and collapsed) depending on the number of tabs needed to be shown.
The landscape tray should support only one state: expanded but it allows to swipe it down to enter in the collapsed state.

## Steps to reproduce
- have the tabs tray opened in landscape
- swipe down on it

### Expected behavior
The tray should close.

### Actual behavior
Tabs tray goes to the collapsed state, becoming unusable.

Video showing the issue in the current Nightly:

https://user-images.githubusercontent.com/11428869/120755827-29bb6a00-c517-11eb-9ba1-3a35928e8069.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10894)

**Comment by gabrielluong** [comment]
Are we unable to expand from the collapsed state from landscape mode? I added this for backlog tracking, but without further information, I haven't move it to ready for engineering.

**Comment by Mugurell** [comment]
> Are we unable to expand from the collapsed state from landscape mode? I added this for backlog tracking, but without further information, I haven't move it to ready for engineering.

You can expand it afterwards but I don't think it should be possible to get to this state where the tabs tray doesn't show any tab.

**Comment by SamuelMezger** [comment]
Still relevant.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812877

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
