### ISSUE TITLE
FNX-67 ⁃ Option to remove search engines

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1982]
### Why/User Benefit/User Problem
Some users will never use _Amazon/Bing/Google/Twitter_ search. It just clutters the "Shortcuts" screen.

### What / Requirements
From the _Search engine_ screen, display "Remove" either somewhere on the screen, or when an engine is long-pressed.

**Comment by sebast889** [comment]
+1
If added there should also be an option to restore the default search engines

**Comment by lewoking** [comment]
support custom search engine

**Comment by elcste** [comment]
@lewoking That's https://github.com/mozilla-mobile/fenix/issues/1437

**Comment by lime124** [comment]
@brampitoyo

**Comment by brampitoyo** [comment]
I’ve taken this issue into consideration when designing manual search engine addition.

As written in https://github.com/mozilla-mobile/fenix/issues/5577#issuecomment-544795351:

> * Added a way to delete search engines, allowing you to add/remove any Search shortcuts item
> * If a search engine is predefined, deleting it will re-add it back to the ‘Add search engine’ page. This means that:
>    * We no longer need a ‘Restore defaults’ option, simplifying our menu
>    * Any predefined search engine can be re-added in one tap. Go to the ‘Add search engine’ page to do it.

Please follow along in that issue.
