### ISSUE TITLE
Consider using emulator to catch large regressions when opening a PR

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19827]
jonalmeida had an interesting idea: on each PR, we could run `measure_start_up.py` on an emulator to catch regressions. We'll need to consider:
- The regressions must be large (maybe 100+ms? 150+ms? more? if run on Moto G5) to return a binary pass or fail (e.g. perftest using a sliding window to identify smaller regressions vs. noise)
  - We need to iteratively tune what values to use: they'll be different than what we're used to for the Moto G5. These would have to change if we ever change the cloud instances we run on (can we prevent this from changing easily?). Perhaps we can use percent diff to overcome the device distinction?
- Is it worth catching these regressions, especially in a separate system from `perftest`? Large regressions (50+ms) only seem to happen every 3-4 months and we usually find the issues from FNPRMS
- We need to make sure emulator results are both consistent and representative of on-device experiences
- We need to make sure the test doesn't take too long or is too expensive to run

Some alternatives that are less work are:
- encourage devs to run perf tests locally if they feel a PR might cause a regression (make it easier?)
- a local script that backfills: i.e. for a given commit range, it runs perf tests for each per-PR merge so we can get the per-PR merge data if we see something in FNPRMS
- ^ run this backfill script regularly (e.g. I run it every day)

These might have the added benefit of catching smaller regressions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10899)

**Comment by jonalmeida** [comment]
To give some clarity. I was wondering if it would be low effort to make a taskcluster task with a simple script that:
1. Starts an emulator.
2. Install the built APK from the other task.
3. Run the adb command to launch a VIEW intent.
4. Record the delta of two profiler markers (or just log events?).
5. Post a github comment on the PR if the value is higher/lower than what is current on `master`.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807325

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
