### ISSUE TITLE
[Bug] unable to restore web content. Black screen drawn. Possibly when the OS kills the render process.

### ISSUE THREAD

**Issue by nopefornow** [mozilla-mobile/fenix#19826]
[comment]: I have been experiencing this problem for Firefox mobile for a while now. When I have an email, I go the google email app, click a link to any website. Browser will open up and if you leave it and come back to the table in the  app with Browse it turns black and will not fix when you refresh or when you open in Firefox mobile. This also for happens for Firefox Android beta. 

## Steps to reproduce 
On Android phone
Open up Google email app 
Click any internet link
Browser will load
Leave Browser but do not close tab
After 2 to 4 minutes come back to the open tab
Should had turned black 

### Actual behavior
Once it the website has gone black you must exit website or close the app to fix the problem. The problem continues if you leave the app open and come back to after 2 minutes.
![Screenshot_20210604-130920_Firefox Beta](https://user-images.githubusercontent.com/85359766/120838692-19ff4e00-c536-11eb-8496-d807a8227290.jpg)

### Device information
Android 
* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1715092

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by agi** [comment]
@nopefornow would you be willing to try to see if you can see the same behavior on Firefox Nightly?

**Comment by nopefornow** [comment]
Its does work in nightly
