### ISSUE TITLE
Evaluate how we use mutli-option settings (Radio groups)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19829]
We use `RadioButtonPreference` for handling a setting that has multiple options but requires one value. The implementation however, creates several individual preference values for _each_ option which seems redundant when we just need to know the selected value.

What's the historical context for this need?

In the tabs tray settings, we were exposing and using two int preferences to distinguish between what could have been one value (boolean/int).

We should possibly investigate into clearing this logic to rely on the Android Preferences library that gives us this ability with `RadioGroup` preferences already.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10901)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813655

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
