### ISSUE TITLE
[Bug] Firefox for Android marks connections with its embedded about: pages as unsecure

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#19831]
## Steps to reproduce
1. (Optional) Open about:about page to see and reach other about: pages
2. Open any available about: page
3. Look at the security icon and status
### Expected behavior
Firefox for Android marks connections with about: pages as secure, because they are its embedded pages
### Actual behavior
Firefox for Android marks connections with about: pages as unsecure, except those that address to other pages
### Device information
* Device vendor / model and Android version: Samsung Galaxy A20s (ARM64) with Android 10, Samsung Galaxy J2 Prime (ARMv7) with Android 6.0.1
* Firefox for Android version: 89.1.1, 90.0.0-beta.1
### Screenshots
![Screenshot_20210604-161828_Firefox](https://user-images.githubusercontent.com/85299944/120852418-d8e15b00-c582-11eb-8e0c-098743cc9378.jpg)
![Screenshot_20210604-161842_Firefox](https://user-images.githubusercontent.com/85299944/120852513-fadadd80-c582-11eb-8e57-bb1b8d458441.jpg)
![Screenshot_20210604-161927_Firefox](https://user-images.githubusercontent.com/85299944/120852542-03331880-c583-11eb-9596-c4b654518bc4.jpg)
![Screenshot_20210604-214356_Firefox](https://user-images.githubusercontent.com/85299944/120852579-0c23ea00-c583-11eb-9d24-b816a59220e2.jpg)
![Screenshot_20210604-214412_Firefox](https://user-images.githubusercontent.com/85299944/120852601-13e38e80-c583-11eb-8d32-0780ce3b8237.jpg)
![Screenshot_20210604-215219_Firefox](https://user-images.githubusercontent.com/85299944/120852611-1940d900-c583-11eb-8f73-386c8770e6c5.jpg)
## Video
https://user-images.githubusercontent.com/85299944/120852677-2fe73000-c583-11eb-88e7-1dc45e046498.mp4

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/android-components/issues/4156
