### ISSUE TITLE
FNX-5379 ⁃ Show individual Tracking Protection lists

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1983]
### Why/User Benefit/User Problem
Users can individually enable/disable lists to their liking. Increases transparency.

### What / Requirements
List _Trackers, Cookies, Cryptominers, Fingerprinters_ (just like Desktop).
Also display option to block only in Private Mode, or all the time.

**Comment by cadeyrn** [comment]
Duplicate of #1085.
