### ISSUE TITLE
[Bug] All web pages in Firefox do not accept text input any more!

### ISSUE THREAD

**Issue by sonora** [mozilla-mobile/fenix#19842]
## Steps to reproduce
With the latest version of Firefox for Android 89.1.1, the following phenomenon appeared overnight: (Not sure if right after the 89.1.1 update or a few days later):

On **ANY website**, when I tap into a text input field, like e.g. the search field on google.com or the username field on a login page, Firefox will not accept any text there. When I first tap into such a field, my Samsung on-screen keyboard does correctly pop up, but no tapped letters are accepted in the page. The field remains empty when typing, and if it has some default text displayed like e.g. "username" or "Search", that text will remain displayed indocating no keystrokes are received. 

Pasting text from the clipboard into such fields still works and such text is displayed. But if I try to make a correction and place the curser in to the text, the onscreen keyboard will not even pop up.

This is a critical issue, making Firefox almost useless.

I had sporadically encountered this issue before in recent months (I believed that the pages may not have completeted loading), and so far refreshing the page in question had always helped. Now the issue appears on any page, refreshing does not help. Now not even deleting all browsing data (in FF) or clearing the Apps' cache in Android/Settings/Apps. has an effect. I will for now not re-install FF in order to help find the root cause and a remedy. This means I do not know if reinstalling the app would fix it.

### Expected behavior
Accept text on web site's input fields

### Actual behavior
see above

### Device information
Samsung XCover 4s, stock Android 10.

Firefox 89.1.1. without Add-ons. Other devices of the same make/model (still) work, so it seems something which appears over time. When I cleared the app cache (which did not fix it) it was about 1GB in size.

**Comment by sonora** [comment]
PS:  I just found out that re-starting the device helps. So it seems that some process may have crashed which was not fixed by restarting firefox, but by re-booting.

The fact remains that only Firefox web pages are affected by the bug. Text input in Firefox's URL field or in other apps worked.

But users not realizing a device reboot helps can become pretty desperate. ;)

**Comment by SoftVision-LorandJanos** [comment]
Hi @sonora  ! Thank you for your report! I wasn't able to reproduce the issue described above. I've tried google search field, facebook login and other pages where text input is necessary. By your last comment I presume you didn't reproduce it either after that reboot. If yes, could you make a video about it? Thank you!
Tested on the latest Nightly (91.0a1 Thursday 6/17 @ 7:33 AM).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by sonora** [comment]
@SoftVision-LorandJanos Hi, thanks for responding to this! The issue has in deed not resurfaced eyet since I rebootet. Before the reboot it had bogged me for several days, and only Firefox was affected, the Samsung keyboard worked for other apps. So it seems that not the Samsung keyboard had crashed, but somehow a sub-functionality or interface Firefox uses.

I will gladly provide a video if this shows up again. The video would be rather boring, though, it would show a text cursor blinking in a text field on an arbitrary web site, and the onscreen keyboard being tapped with no effect.

For now I would conclude I am not certain anything can be fixed in Firefox at all, chances are some system process had crashed which FF simply happens to use. Maybe we should close this unless more people show up having experienced this?

**Comment by SoftVision-LorandJanos** [comment]
Hi @sonora. I agree, if others report this issue or you'd reproduce it again, please let us know, either by reopening this issue or logging a new one and try to gather as much information as possible that could have lead to the issue. Thank you!
