### ISSUE TITLE
Update widget design

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#19844]
The widget may benefit from a facelift. Compared to the Google app widget it seems a bit outdated, in my personal opinion. I'd suggest adding a bit of transparency, and maybe more rounded corners.

As a sidenote: the microphone icon seems a bit too big, especially compared to the Firefox icon. Maybe it could be a bit smaller.

Screenshot:
![Screenshot_20210605_140347.jpg](https://user-images.githubusercontent.com/20287690/120891207-96159680-c607-11eb-84c3-ea982ed44a31.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10913)

**Comment by anotherus3r** [comment]
Related: #19583

**Comment by cpeterso** [comment]
Tracking widget design issues in Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1807578.
