### ISSUE TITLE
[Bug] Firefox does not open downloaded files in another app

### ISSUE THREAD

**Issue by sonora** [mozilla-mobile/fenix#19841]
## Steps to reproduce
I run several identical installations of Firefox 89.1.1 on the same hardware model Samsung XCover 4s, stock Android 10.

On **only one of them**, downloading any PDF (e.g. http://www.orimi.com/pdf-test.pdf) and then tapping the 'Open' button on Firefox's 'Download completed' message produces an error message (for any PDF reader app selected). E.g. my default app is Acrobat Reader, and that one produces a toast like "_This file could not be accessed, check the location..._". The actual error text varies with the reader app selected, always somehow indicating the the file or file name passed by Firefox is not accessible.

But the file was correctly downloaded to internal memory/Downloads folder, and when I go their using a file manager (e.g. Samsung#s MyFiles) and tap it, Adobe Reader (or any other PDF app) does open it without problems.

I notice that in Firefox under Menu/Downloads each file downloaded creates **two** look-alike entries for each download (for the above example 2 lines "_test-pdf.pdf_"). Maybe Firefox saves the file to SD card or elsewhere also and passes the links for both or for the one not accessible by other apps, not sure. But tapping either one produces the same error stated above.  Manually deleting the downloaded file from the Downloads folder removes both references also in Firefox's Download menu.

It looks like the issues is related  to **all downloads, not just PDF**, as also when e.g. downloading an image then directly displaying it with the Gallery does not work. (Gallery shows no error message but an exclamation mark picture, indicating it could not find or access the downloaded picture.)

This was a fresh installation of Firefox 89.1.0 from scratch, later updated to89.1.1. Reinstalling both Firefox and Adobe does not fix the issue. Other devices of the same hardware and software work just fine.

Any idea?

### Expected behavior
Tapping "Open" on the Download finished message should open the downloaded file in its default app (or ask with which app if no default is selected on the device.)

### Actual behavior
see above

### Device information
Samsung XCover 4s, stock Android 10. Device has also an SD Card inserted. But this same configuration works also on other XCover 4s with the same configuration and same software. Those other devices were mostly updated from former versions of Firefox, e.g. 88. The issue device in question received a fresh install of Firefox 89.1.0, then updated to 89.1.1.

**Comment by sonora** [comment]
Funny enough, here's what fixed it for me: I installed in parallel Firefox beta (the old fennec 68.7b1 still present on ftp.mozlla.org) to see if that has the same issue.

Turns out it has not, with that things work. After then re-opening fenix 89.1.1, the issue has dissappeared also there (at least si far).

**Comment by arghyasinha** [comment]
I am also facing the same issue. Don't why this thing is happening in stable version and fixed in the beta amd nightly version.

Installing beta parallely is not working for me. If you found any other solution, kindly let me know.
