### ISSUE TITLE
Show 'Default Browser' Local Notification for New users

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#19846]
Built as a feature of the app, (much like the onboarding flow) that gets scheduled in a user's first session and triggers if they do not set us as default 24 hours after 1st app launch, see an example below.

![image](https://user-images.githubusercontent.com/773158/120893254-55eeed80-c5e0-11eb-91a3-968f9c8e6101.png)

**Comment by abodea** [comment]
Hello, @Amejia481 do we have a timer for the `Default browser` notification?
I'm trying to test this issue but after the onboarding flow, I saw no notification.

**Comment by Amejia481** [comment]
👋🏽 
@rocketsroger can provide more details as he implemented the feature :)

**Comment by rocketsroger** [comment]
> Hello, @Amejia481 do we have a timer for the `Default browser` notification?
> I'm trying to test this issue but after the onboarding flow, I saw no notification.

@abodea, after you first installed Fenix on the device (clean install) you'll have to wait 24 hours to make sure the notification shows up.  Unfortunately there's no other way to test this.

**Comment by rocketsroger** [comment]
Fixing a case when user does not tap on the notification but swiped it away.

**Comment by abodea** [comment]
> > Hello, @Amejia481 do we have a timer for the `Default browser` notification?
> > I'm trying to test this issue but after the onboarding flow, I saw no notification.
> 
> @abodea, after you first installed Fenix on the device (clean install) you'll have to wait 24 hours to make sure the notification shows up. Unfortunately, there's no other way to test this.

Thank you, Roger, yesterday I was in PTO but I have left a device for this bug.
Please note that I was able to trigger the `Local Notification` for new users. 
Also, when I tapped on the notification I was correctly redirected to the `select default` browser and I was able to set it without issues.

I have left a device for tomorrow to verify the swiping side too. 
Removing `eng:qa:needed` until I confirm this issue.

**Comment by abodea** [comment]
Hello @rocketsroger please note that for the swipe notification after 24h I had the following behavior:
The notification went away and it didn`t really appeared anymore, it should be displayed again or to not be able to dismiss it?
Removing `eng:qa:needed` until further notice, note that I have left another device for the new notification.

**Comment by rocketsroger** [comment]
> Hello, @rocketsroger please note that for the swipe notification after 24h I had the following behavior:
> The notification went away and it didn`t really appear anymore, it should be displayed again or not be able to dismiss it? Removing `eng:qa:needed` until further notice, note that I have left another device for the new notification.

Yes, that's the correct behaviour.  The user should be able to swipe the notification away.  Once the user swiped the notification away it will not be displayed anymore.  The notification will show only one time and regardless if the user tapped on it or swiped it away it will not be shown again.

**Comment by abodea** [comment]
> > Hello, @rocketsroger please note that for the swipe notification after 24h I had the following behavior:
> > The notification went away and it didn`t really appear anymore, it should be displayed again or not be able to dismiss it? Removing `eng:qa:needed` until further notice, note that I have left another device for the new notification.
> 
> Yes, that's the correct behaviour. The user should be able to swipe the notification away. Once the user swiped the notification away it will not be displayed anymore. The notification will show only one time and regardless if the user tapped on it or swiped it away it will not be shown again.

Thank you very much @rocketsroger I was able to verify this on Beta Beta 91.0.0-beta.2 and the latest Nightly as mentioned above.
I swiped the notification without a problem.
