### ISSUE TITLE
Do not force user to click "What's New" menu item on app upgrade

### ISSUE THREAD

**Issue by gsheridansmith** [mozilla-mobile/fenix#19843]
### What is the user problem or growth opportunity you want to see solved?
The blue dot that appears on the three dot menu after updating the app is annoying. I should be able to dismiss it without having to click the "What's New" item in the menu.

### How do you know that this problem exists today? Why is this important?
I just updated the app to v89. There is now a blue dot on the three dot menu every time I open the app.
It's very annoying and I don't want to be forced to click the "What's New" item to get rid of it.

### Who will benefit from it?
Anyone who doesn't care what's new or has already read the release notes elsewhere.

**Comment by anotherus3r** [comment]
Also, it leads to an outdated changelog in certain languages, as the support articles often aren't updated in all languages. E.g. when Firefox is set to Croatian (hr_HR), it leads to https://support.mozilla.org/1/mobile/89.1.1/Android/hr-HR/whats-new-firefox-preview and the latest changes mentioned there are for Firefox 85.

**Comment by gsheridansmith** [comment]
Looks like there's a timer until it dismisses itself, between around 12-18h. I'd still like a way to dismiss it immediately

**Comment by amedyne** [comment]
Tagging @topotropic for feedback on "What's New" blue dot behavior.
