### ISSUE TITLE
I can't test the application. (> Task :app:compileDebugKotlin FAILED)

### ISSUE THREAD

**Issue by ikaruxt** [mozilla-mobile/fenix#19845]
I get the following errors when opening Fenix-Master android Studio. I can't test the application.
`
> Task :app:compileDebugKotlin
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\addons\AddonsManagementView.kt: (40, 48): Unresolved reference: actionAddonsManagementFragmentToInstalledAddonDetails
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\addons\InstalledAddonDetailsFragment.kt: (217, 26): Unresolved reference: actionInstalledAddonFragmentToAddonInternalSettingsFragment
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\addons\InstalledAddonDetailsFragment.kt: (227, 57): Unresolved reference: actionInstalledAddonFragmentToAddonDetailsFragment
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\addons\InstalledAddonDetailsFragment.kt: (230, 48): Overload resolution ambiguity: 
public fun NavController.navigateBlockingForAsyncNavGraph(directions: NavDirections): Unit defined in org.mozilla.fenix.ext in file NavController.kt
public fun NavController.navigateBlockingForAsyncNavGraph(resId: Int): Unit defined in org.mozilla.fenix.ext in file NavController.kt
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\addons\InstalledAddonDetailsFragment.kt: (237, 57): Unresolved reference: actionInstalledAddonFragmentToAddonPermissionsDetailsFragment
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\addons\InstalledAddonDetailsFragment.kt: (240, 48): Overload resolution ambiguity: 
public fun NavController.navigateBlockingForAsyncNavGraph(directions: NavDirections): Unit defined in org.mozilla.fenix.ext in file NavController.kt
public fun NavController.navigateBlockingForAsyncNavGraph(resId: Int): Unit defined in org.mozilla.fenix.ext in file NavController.kt
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\components\toolbar\BrowserToolbarController.kt: (66, 17): Cannot find a parameter with this name: sessionId
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\components\toolbar\BrowserToolbarController.kt: (68, 13): No value passed for parameter 'session�d'
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\home\HomeFragment.kt: (768, 17): Cannot find a parameter with this name: sessionId
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\home\HomeFragment.kt: (769, 13): No value passed for parameter 'session�d'
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\home\intent\StartSearchIntentProcessor.kt: (52, 21): Cannot find a parameter with this name: sessionId
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\home\intent\StartSearchIntentProcessor.kt: (54, 17): No value passed for parameter 'session�d'
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\home\sessioncontrol\SessionControlController.kt: (562, 13): Cannot find a parameter with this name: sessionId
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\home\sessioncontrol\SessionControlController.kt: (564, 9): No value passed for parameter 'session�d'
e: C:\andoridapps\fenix-master\app\src\main\java\org\mozilla\fenix\search\SearchDialogFragment.kt: (138, 30): Unresolved reference: sessionId

> Task :app:compileDebugKotlin FAILED`

What didn't I do?

**Comment by hakkikaancaliskan** [comment]
Same issue here.

**Comment by hakkikaancaliskan** [comment]
Issue fixed. I'm currently on Arch Linux and I can build the fenix.
Idk if issue fixed with Arch or latest commits but fixed.

Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.8-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, org.intellij.plugins.markdown
Current Desktop: KDE
