### ISSUE TITLE
Full-screen mode, AKA hide status bar

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1984]
### Why/User Benefit/User Problem
Increases screen real estate (can display more text/pics, open tabs, bookmarks, etc. Users don't usually need status bar shown while browsing. Especially handy for reading articles--really anything.
While rare, decreases chance of screen burn-in.
User choice! 

https://github.com/mozilla-mobile/fenix/issues/17677 also requested support for full immersive mode - both the status bar and the navigation bar to be hidden.

### What / Requirements
List  a fullscreen/hide status bar option in Settings.
Samsung Internet has a fullscreen mode (Menu > Settings > Appearance > Show status bar) that works great.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10908)

**Comment by vesta0** [comment]
@SKITTLE-LA we plan to address this by (1) hiding the URL bar when scrolling down on a page (2) building a reader mode in the browser for articles, etc. Are there other use cases that may require this?

**Comment by SKITTLE-LA** [comment]
> 
> 
> @SKITTLE-LA we plan to address this by (1) hiding the URL bar when scrolling down on a page (2) building a reader mode in the browser for articles, etc. Are there other use cases that may require this?

Oh, for sure. The Android status bar doesn't _look_ like it takes up much space, but hiding it really adds an "immersive" experience to using the app. The status bar isn't really needed while browsing/reading articles/looking at pictures, and it also allows for a little less scrolling and finger strain. But if needed, it temporarily shows if the user swipes down from the top of the screen.

This is why I think an option to totally hide it everywhere while using the app would be great. I admit I'm a screen real estate nut; I also normally browse desktop in fullscreen mode.

Try out Samsung Internet's implementation if you haven't already; it looks great, and I haven't noticed any bugs while using it! I'm not yet aware of any other browsers that allow this...

I currently have to mess with ADB to hide the status bar while using Fennec (or any app.) If you're curious, here's an XDA guide how to do it. It's just enabling "Immersive Mode" which I assume is all that would need to be done:
https://forum.xda-developers.com/nexus-6p/general/guide-hide-navigation-bar-status-bar-app-t3509747

**Comment by vesta0** [comment]
@SKITTLE-LA thank you for the details! I have moved this into our post-mvp backlog.

**Comment by yoasif** [comment]
I have taken to using Fenix on a Moto G, and I now realize that this would be a very nice feature to have on a 4.5" screen. Something to consider.

**Comment by SKITTLE-LA** [comment]
Oh wow, I use it on a Galaxy S9 so can't imagine going back.

Seriously though, you can use the XDA guide that I linked in the comment above. I hope Mozilla implements a full-screen option, but I wouldn't get my hopes up.

**Comment by palerdot** [comment]
Firefox mobile behaves inconsistently in showing/hiding navbar when interacting with a canvas on the page. For example, if there is a canvas on the page and the user tries to draw on it with touch, firefox mobile keeps flickering the navbar and the user cannot draw on the canvas in the page. Same behaviour works flawlessly with chrome, where the navbar hiding logic does not interfere with user touch events like drawing on canvas.

**Comment by palerdot** [comment]
Above mentioned behavior also interferes with modal, when the user tries to touch scroll within the modal, the body flickers with navbar appearing in and out of the view ...

**Comment by Mikaka27** [comment]
@palerdot I think you should mention this problems here: #17031

**Comment by N00B2** [comment]
Any news on this issue?

**Comment by daboross** [comment]
> @SKITTLE-LA we plan to address this by (1) hiding the URL bar when scrolling down on a page (2) building a reader mode in the browser for articles, etc. Are there other use cases that may require this?

Yes: browsing webpages which don't look good in reader mode. For instance, webcomics which are largely image-based often have all of their content removed when switching into a reader mode which focuses text. They would also benefit greatly from an immersive mode where you could have the title bar hidden even if you aren't scrolling down, and have the navigation and status bar also hidden.

**Comment by vctls** [comment]
Just found out that Google removed the ability to manage immersive mode from third party apps with `WRITE_SECURE_SETTINGS` permission, so that workaround doesn't work anymore.

**Comment by Liam2349** [comment]
I've checked on this issue on and off for a while, it's disappointing that Mozilla seems uninterested in it.

I end up using Samsung Internet a lot more than Firefox just because it hides the status bar. Not only does this avoid the burn in potential, but it's just nicer to have distractions hidden away when I'm reading things.

Now that ADB immersive mode is no longer possible on Android 11, this feature is more important than ever, and until it gets implemented I can't see myself opening Firefox for anything other than when I require specific extensions.

**Comment by vitaly-zdanevich** [comment]
I found that I can use Via browser for full fullscreen.

**Comment by illegalprime** [comment]
I've had success with `adb shell settings put global policy_control immersive.full=org.mozilla.firefox`

**Comment by vitaly-zdanevich** [comment]
@illegalprime is it possible without cable to a computer? Can I execute similar command from a terminal in a smartphone?

**Comment by pauloxnet** [comment]
It seems that Firefox Android can enter in full screen mode, as you can see using this demo page:
https://krpano.com/firefox/bugs/android-fullscreen-via-touch/
But there's no way to activate this mode from its UI.

**Comment by Liam2349** [comment]
Interesting find @pauloxnet. It also works on other browsers.

It uses the Element.requestFullscreen() API: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

In this case it puts the entire HTML document into fullscreen mode.

This would help, and could be an easy stop gap fix to improve usability if they simply added this button to some accessible location. 

Or, perhaps an extension could even provide this. Not sure where an extension could conveniently place the button however.

**Comment by Dakkaron** [comment]
For some reason since the last update ,Firefox seems to be randomly switching between full immersive mode and no immersive mode, even though I disable the scroll to hide status bar feature.

**Comment by jkommeren** [comment]
> I've had success with `adb shell settings put global policy_control immersive.full=org.mozilla.firefox`

This only works on Android 10 and below.

**Comment by jkommeren** [comment]
> I found that I can use [Via](https://play.google.com/store/apps/details?id=mark.via.gp) browser for full fullscreen, but this is not open source.
I've used via for some time, even asked the owner on GitHub. Issue is still there. 

Specifically we're talking about portrait mode here, when browsing

Via also doesn't support this on Android 11 and 12, only for full screen videos was added recently.

**Comment by Dakkaron** [comment]
Interesting how almost every issue on this repo turns from being ignored by the devs to a discussion about alternative browsers... I fear, they really have given up on Firefox Mobile...

**Comment by tomyummmm** [comment]
How do i disable this immersive mode? I want my android notifications bar to show all the time. I cant find any settings in firefox beta?

**Comment by Dakkaron** [comment]
Theoretically, there is an option, practically, it's bugged and doesn't work correctly.

In German it is "Anpassen" -> "Gesten" -> "Zum Ausblenden der Symbolleiste scrollen".

Translated, that would be "Adjust" (4th option from the top under general settings) -> "Gestures" (section name) -> "Scroll to hide symbol bar" (top toggle option in the gestures section).

If you disable this, you should be in perma-non-immersive mode. But it doesn't work correctly, and sometimes you still end up in immersive mode.

**Comment by vitaly-zdanevich** [comment]
> Via **does** **not** have this feature (yet)

I use Via on Poco X3 Pro with Android 11 only because it totally full screen.

**Comment by vitaly-zdanevich** [comment]
> Samsungs browser does have a working implementation

Tried just now - no, there is no such option in preferences. Poco X3 Pro.

**Comment by vitaly-zdanevich** [comment]
> How do i disable this immersive mode? I want my android notifications bar to show all the time. I cant find any settings in firefox beta?

Tried Firefox Beta on Android 11 just now - I still see the system top bar :(

**Comment by jkommeren** [comment]
> > Samsungs browser does have a working implementation
> 
> Tried just now - no, there is no such option in preferences. Poco X3 Pro.

So it only works on a Samsung phone perhaps? There's a "hide status bar" there on my S20 work phone. That works as expected on A11. In portrait mode.

But in any case I agree let's keep this about the Firefox browser please.
