### ISSUE TITLE
Change download location for in storage or sd card

### ISSUE THREAD

**Issue by Thewisem** [mozilla-mobile/fenix#19855]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I want to download content to my sd card but I can't.

### How do you know that this problem exists today? Why is this important?
This will help me when my phone storage is not required for a single use case application
### Who will benefit from it?
People who have less storage and people who can swipe between phones by using sd card

**Comment by Amejia481** [comment]
Thanks for filing, there is already a ticket for tracking this feature https://github.com/mozilla-mobile/fenix/issues/5764
