### ISSUE TITLE
[Bug] Scroll-and-tap gesture unexpectedly opens the bottom adress bar

### ISSUE THREAD

**Issue by Susko3** [mozilla-mobile/fenix#19853]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. Open a website that can be scrolled, eg. https://support.mozilla.org/en-US/kb/whats-new-firefox-android
2. Perform the scroll-and-tap gesture (downwards scroll)
    - to perform the gesture: fling your finger over the screen to begin scrolling, while the screen is scrolling (and your finger is off the screen) tap once
    - this will stop scrolling immediately (and that's expected), but what is not expected is that the bottom adress bar will show

### Expected behavior

The adress bar remains hidded after performing a downward scroll-and-tap gesture

### Actual behavior

The adress bar is shown upon performing the gesture.

### Device information

* Device vendor / model and Android version: Realme 6 / Android 10
* Firefox for Android version: 89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

**Comment by Mikaka27** [comment]
I see same thing happens when you scroll and the while page is still scrolling, try to scroll again (to increase speed).

**Comment by vaindil** [comment]
This happens both in the latest stable (89.1.1) and the latest nightly.

**Comment by RyanQAE** [comment]
Wanted to add more as this is a rather annoying bug, here is a gif of what it looks like:

https://imgur.com/a/UW35U9Q

**Comment by SlowNicoFish** [comment]
Happening here too. 
Oneplus 8T
 Fenix 89.1.1

**Comment by SlowNicoFish** [comment]
Can confirm this on Fenix 90.1.0 as well

**Comment by Mugurell** [comment]
I think this is fixed in the current Nightly after https://github.com/mozilla-mobile/android-components/pull/10562
@Susko3 Can you confirm?

**Comment by Susko3** [comment]
It's fixed in the latest Nightly:
```
92.0a1 (Build #2015825547)
AC: 92.0.20210730143121, dca90e65d6
GV: 92.0a1-20210730093652
AS: 81.0.1
```

Should I close this issue now, or close it after it reaches stable?

I'll still be using stable as nightly has a nasty bug where it refreses at 60 Hz instead of 90 Hz (my display is 90 Hz). So the scrolling bug still technically affects me.

**Comment by Mugurell** [comment]
> I'll still be using stable as nightly has a nasty bug where it refreses at 60 Hz instead of 90 Hz (my display is 90 Hz). So the scrolling bug still technically affects me.

This seems pretty bad and if it's now in Nightly it will soon happen in Beta and Release.
Can you please open a new ticket for this issue detailing how you've measured the difference and where does this happen?

**Comment by Mugurell** [comment]
> Should I close this issue now, or close it after it reaches stable?

If it's fixed in Nightly there's nothing else to do so the ticket can be closed.
Will look though whether we can uplift the fix to Beta to speedup things a little.

**Comment by Susko3** [comment]
> > I'll still be using stable as nightly has a nasty bug where it refreses at 60 Hz instead of 90 Hz (my display is 90 Hz). So the scrolling bug still technically affects me.
> 
> This seems pretty bad and if it's now in Nightly it will soon happen in Beta and Release.
> Can you please open a new ticket for this issue detailing how you've measured the difference and where does this happen?

Issue opened at https://github.com/mozilla-mobile/fenix/issues/20630

**Comment by Mikaka27** [comment]
> > Should I close this issue now, or close it after it reaches stable?
> 
> If it's fixed in Nightly there's nothing else to do so the ticket can be closed.
> Will look though whether we can uplift the fix to Beta to speedup things a little.

It would be good if you could uplift this to release, it's quite annoying bug :)

**Comment by Lann094** [comment]
Any update on when this fix will be released?

**Comment by Mugurell** [comment]
> Any update on when this fix will be released?

This is fixed in the Nighly and Beta release channels. Will also get to Release starting with version 92 which will be available next week.
