### ISSUE TITLE
[Bug] All open private tabs occasionally crash

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#19852]
**Steps to reproduce**

1. Open one or more new tabs in private mode.
2. Switch to standard mode or open another app (multitasking).
3. Return to the private mode.

**Expected behavior**
Private tabs remain open.

**Actual behavior**
Sometimes private tabs are closed when you return.

**Device**

* Samsung Galaxy XCover 4s, Android 10
* Firefox for Android version: 89.1.1

**Comment by WebworkrNet** [comment]
So far I haven't seen a trigger.

**Comment by Dunexus** [comment]
Private tabs only kept in memory (not persisted on disk), if you run ram demanding apps while firefox is in the background, the OS may kill firefox from ram losing your private session.

**Comment by kbrosnan** [comment]
Have you disabled the private browsing notification? Generally the notification should keep the private tabs alive. If you do not get the notification check your Android Settings for notifications. Some aggressive task killers or battery saver modes can hard kill the Firefox process. The other case where this can happen is if Play updates Firefox. This will cause a full restart of the app. There is not anything that can be done for the cases outlined. If you can get reproducible steps that don't cover the above known behavior please open a new issue with the details and we can evaluate it.
