### ISSUE TITLE
Text characters get garbled randomly

### ISSUE THREAD

**Issue by mirkhosro** [mozilla-mobile/fenix#19851]
On Firefox for Android on my Pixel 5 phone, when I'm viewing a web page, often the text characters are rendered incorrectly. For example some characters get missing or misplaced. I cannot find a pattern for when this happens but it's quiet often and is more likely to happen on pages with dense text content.
The problem goes away as I do an action that refreshes the text, like changing the zoom, but can happen again on the same page after a few seconds.
I have had this problem for as long as I remember (at least 6 months) and it's still there on the latest version of Firefox that I'm using. 

Build info:
89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1
Phone: Pixel 5

I have attached a few screen shots to show the problem, but I can provide more if needed.
![1](https://user-images.githubusercontent.com/14208489/120905454-21028b00-c620-11eb-8343-5cf36ab2c74a.png)
![2](https://user-images.githubusercontent.com/14208489/120905456-2233b800-c620-11eb-98df-84044497a055.png)

**Comment by mirkhosro** [comment]
Github won't allow me to attach a zip file here, and it's pretty big. So I put it on my Google Drive that you can access from here
https://drive.google.com/file/d/1FrXEIpa8t2NHv5Fju4M1CUfrSbZd_WNX/view?usp=sharing

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox RC 89.1.1 and Nightly 06/30 but was unable to.

### Devices used
- OnePlus 6T (Android 9)
- Google Pixel 3 XL (Android 9)

**Comment by mirkhosro** [comment]
I didn't have this issue on my older Pixel 2 device, so it could be that this happens only on newer Pixel devices.

**Comment by mirkhosro** [comment]
Hi @LaurentiuApahideanSV @amedyne, are there any updates on this bug? My Firefox for Android is still affected with this which deteriorates my experience with Firefox.

**Comment by amedyne** [comment]
@mirkhosro are you still having this problem on the latest release v91?

**Comment by mirkhosro** [comment]
Yes I'm still having this problem in release 91.2

**Comment by amedyne** [comment]
Thank you for checking @mirkhosro . I'll be transferring this to bugzilla for further investigation.

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1726998

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
