### ISSUE TITLE
FNX-69 ⁃ Provide options for different levels of cookie blocking

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1985]
As a user, I want to have a choice in type of cookies to allow/block, so I can have control over my privacy.

**Comment by sebast889** [comment]
There should also be a way to add exceptions

**Comment by liuche** [comment]
Here are some things Desktop does:
<img width="731" alt="Screen Shot 2019-11-05 at 2 32 48 PM" src="https://user-images.githubusercontent.com/1082253/68251999-2f6a6a00-ffd9-11e9-9e2e-f48ddf07f673.png">
<img width="437" alt="Screen Shot 2019-11-05 at 2 33 40 PM" src="https://user-images.githubusercontent.com/1082253/68252060-4f019280-ffd9-11e9-902f-e1aab8fcf99c.png">

**Comment by vesta0** [comment]
Thank you for looking into desktop @liuche :) I agree that it makes sense to align with desktop. I created a new ticket for it: #6479

**Comment by vesta0** [comment]
Thanks @SKITTLE-LA for filing this and putting it on our radar!

**Comment by SKITTLE-LA** [comment]
Thank you for looking into this and building a bang-up mobile browser! I hope you look at all of my other suggestions, haha (kidding but also not.) I'll still be using Fennec until extensions are supported but try to do what I can to test and improve Fenix.
