### ISSUE TITLE
[Bug]cannot complete request for first search after each opening! 

### ISSUE THREAD

**Issue by BlackGhostUK1** [mozilla-mobile/fenix#19854]
Hi guys! I have issue with searching after my first enter to Firefox nightly each time! When I open it and try to search for first time after each opening it says cannot complete request! But when I refresh the same page it loades fine! Please fix it🙏 
![Screenshot_20210603_131454_org mozilla fenix](https://user-images.githubusercontent.com/85413150/120902750-5d9da900-c657-11eb-9d3b-95bcc28d736b.jpg)
My phone is running android 10 if it helps.
My network speed is good because it works fine in Firefox beta or stable version.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1715091

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by KershawChang** [comment]
@BlackGhostUK1 , are you still able to reproduce with the latest nightly?
Thanks.

**Comment by BlackGhostUK1** [comment]
Thank you very much the problem is solved
________________________________
