### ISSUE TITLE
Deleting web site data does not actually delete web site data

### ISSUE THREAD

**Issue by janschejbal** [mozilla-mobile/fenix#19859]
## Steps to reproduce

1. Use Firefox Android for a long time.
2. Notice that it is consuming ~500 MB of "user data"
3. Go to Settings -> Delete browsing data
4. Select "browsing history and site data", "cookies", and "cached images and files"
5. Delete the data
6. Switch back to the app info panel
7. Notice that "user data" consumption only shrunk a little bit

### Expected behavior

User data consumption goes to near zero. All website-related data in `/data/user/0/org.mozilla.firefox/files/mozilla/xxxxxxxx.default/storage/default` is deleted.

### Actual behavior

Hundreds of MB of web site data remain in the above mentioned path. **Repeating steps 3-5 deletes additional data. After several cycles, the directory is actually cleared.** I found a ~14 MB sqlite file remaining in storage/permanent/chrome/idb, not sure if that's supposed to remain there.

I wonder if this happens when the user takes some action (e.g. switching away from the deletion dialog) too quickly.

I suspect this is both a performance issue (lots of space wasted) and a privacy issue (some web site data not deleted correctly, even though the user thinks it was).

### Device information

* Android device: Pixel 4a
* Fenix version: 89.1.1

**Comment by sonora** [comment]
I can confirm that the Android app cache for fenix 89.1.1 had accumulated 1GB of data, and after deleting all browsing data in Firefox it still showed 0.98GB.
