### ISSUE TITLE
FNX-5380 ⁃ Include "Send tab" option from "Open tabs" and bottom UI

### ISSUE THREAD

**Issue by SKITTLE-LA** [mozilla-mobile/fenix#1986]
### Why/User Benefit/User Problem
Less taps, two separate ways to send tabs to other Firefox Sync devices.

### What / Requirements
At the homepage, include "Send tab" from the three-dot menu.
When a page is loaded, include "Send tab" from the three-dot menu at the bottom-right.
Or it could be nested in "Share" for either.

Also--have option to send bookmarks or history to other devices!

### Acceptance Criteria (how do I know when I’m done?)
Send is listed and works (syncs) correctly!

**Comment by vesta0** [comment]
This will be addressed by #246
