### ISSUE TITLE
Can't close tab tray by swiping down from anywhere while you have tabs open.

### ISSUE THREAD

**Issue by Nojuuu** [mozilla-mobile/fenix#19863]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Used to be able to swipe down **almost anywhere** on tab tray to close it, but that doesn't seem to work on latest Nightly after that new reworked tab tray with synced tabs.

## Steps to reproduce

Open tabtray and have some tabs open and try to swipe down to close it.

### Expected behavior

Allow to swipe down anywhere on tab tray to close it.

### Actual behavior

Now you can close it like that only when tab tray is empty.

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro, Android 10.
* Firefox for Android version:  Firefox Nightly 91.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10930)

**Comment by amedyne** [comment]
@Nojuuu: You can still close the tab tray by pulling down from the Tab tray header. See attached. 

https://user-images.githubusercontent.com/68711330/121258272-b26e3900-c87c-11eb-9b28-f0eaef7962dc.mp4

**Comment by Nojuuu** [comment]
The way it used to work was much more user-friendly, because you didn't have to stretch your finger halfway across the screen (and sometimes even higher).

**Comment by amedyne** [comment]
@jonalmeida is this a regression from after implementing the synced tabs?

**Comment by tobz1000** [comment]
Similarly, pre-v89, it was possible to reach higher-up tabs by pulling down anywhere on the tab tray. Since v89, the tray can only be resized by pulling on the bar at the top.

This might be considered a different bug, but the cause is the same.

**Comment by tobz1000** [comment]
This bug is still present in v96.

**Comment by tobz1000** [comment]
This bug is still present in v107.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812876

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
