### ISSUE TITLE
Mispositioning of caret in textarea or contenteditable=true

### ISSUE THREAD

**Issue by schnittchen** [mozilla-mobile/fenix#19864]
## Steps to reproduce

Given this textarea and contenteditable div,

```
<textarea rows=4>afhdghhhrf dcbjjrfvb dbuyfcb
b
c
</textarea>

<div contenteditable=true>
afhhtrdhjj jfrhbkuycvbb xvnurfvvb<br>
b<br>
c
</div>
```

### Expected behavior

Tapping anywhere on the second line except for a few pixels at the very left brings the caret to the position behind the "b".

### Actual behavior

Positioning the caret behind the end of the second line (after the "b") is only possible by tapping at the vertical position of the "b" line either right after the letter b, or horizontally behind the last character of the line above. Anywhere in between will position the caret on the line above.

The behaviour is the same for the textarea and the div.

### Device information

* Android version: Android 10
* Firefox for Android version: 89.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10931)

**Comment by makotokato** [comment]
Does this occurs on Firefox Nightly too? If so, could you resolve this on Firefox Nightly when `ui.touch.radius.enabled` is `false` via about:config (about:config supports on Firefox Nightly only)?

**Comment by schnittchen** [comment]
Does toggling the setting have immediate effect? I also reloaded the page with the textarea to be more sure.

If yes, nightly has the same behaviour and `ui.touch.radius.enabled=false` does not change it.

**Comment by schnittchen** [comment]
This problem still exists. Stupid bot.

**Comment by schnittchen** [comment]
This problem still exists. Stupid bot.

**Comment by schnittchen** [comment]
Yeah but because I was extremely busy in the past weeks and didn't answer here within the past two weeks, the issue is now closed and probably nobody will ever get a notification.

Stale bots are a really bad idea.
