### ISSUE TITLE
[UX Bug] snackbar is blocking the most recent tab

### ISSUE THREAD

**Issue by fm-sys** [mozilla-mobile/fenix#19871]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
I usually go through all tabs which remained open from time to time to close them one by one. For sure, there is the "close all" functionality, but most of the time there are some tabs which I want to keep open.

### Expected behavior
I can close the tabs one after the other by quickly pressing the X button. The snackbar should not block the most recent tab.

### Actual behavior
The snackbar is blocking the tab list, so the latest opened tab cannot be accessed for a few seconds...

![Screenshot_20210607_134328_org mozilla firefox (¼ Size)](https://user-images.githubusercontent.com/64581222/121015313-246e5180-c79b-11eb-8089-4aeaf83b897b.jpg)

However, I saw the material guidelines, that require it as it is currently implemented

![grafik](https://user-images.githubusercontent.com/64581222/121016955-0ace0980-c79d-11eb-9e19-6ee9774b624f.png)

Still, the current working mode is really not nice, but I haven't an idea how this could be solved...

### Device information

* Device vendor / model and Android version: Huawei / Android 10
* Firefox for Android version: 89.1.1

**Comment by Dunexus** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/19166

**Comment by fm-sys** [comment]
Yes, sorry. Haven't found this issue :-/

Will add my comments there...

**Comment by Dunexus** [comment]
Don't worry, searching issues on github is quite hard as it only based on keywords
