### ISSUE TITLE
[Bug] CJK text with `monospace` font shows serif font instead of sans-serif since version 89

### ISSUE THREAD

**Issue by konan8205** [mozilla-mobile/fenix#19877]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Open new tab and go to https://github.com/konan8205/xingapi-rs/blob/master/src/lib.rs

### Expected behavior
Shows korean with sans-serif font
![Screenshot_20210608-030615_Chrome](https://user-images.githubusercontent.com/11029378/121069789-e1e35e00-c808-11eb-9d14-e5252145ea4f.jpg)

### Actual behavior
Shows korean with serif font
![Screenshot_20210608-030537_Firefox](https://user-images.githubusercontent.com/11029378/121069839-edcf2000-c808-11eb-8e3f-0f6b2ab7f2b0.jpg)

### Device information
* Device vendor / model and Android version: Samsung Galaxy A51 5G, Android 11
* Firefox for Android version: 89.1.1 (Build #2015812947)

This bug seems to have occurred since the version 89.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1715113

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
