### ISSUE TITLE
Show a Home screen button to navigate to the home screen

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19876]

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/11 Nightly build with OnePlus 5T (Android 10), Google Pixel (Android 10), and Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by lobontiumira** [comment]
The Home screen button is not displayed on the page's toolbar, on Beta 91.0.0-beta.3 on any device.
But, the options to "Start on home" are available and working as expected.

**Comment by amedyne** [comment]
@lobontiumira The HomeScreen button should only be displayed in Nightly. Can you clarify what you are referring to on "options to Start on Home"?

**Comment by lobontiumira** [comment]
@amedyne I'm reffering to the options available in Settings - Tabs - Start on home.

**Comment by amedyne** [comment]
@lobontiumira We will have to put the "Start on Home" settings on a nightly only feature flag. @Amejia481 will be doing that.

**Comment by Amejia481** [comment]
> @lobontiumira We will have to put the "Start on Home" settings on a nightly only feature flag. @Amejia481 will be doing that.

This is the [PR](https://github.com/mozilla-mobile/fenix/pull/20555) for only showing the feature on nightly, after it gets merged I'll uplifted it to Beta.
