### ISSUE TITLE
[Crash] Tab crashed on GitHub, not fenix

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#19883]
Opened https://github.com/TeamNewPipe/NewPipe/issues/6425 on 90-beta2 and tab crashed, it's not reproducible
```
28fbb1da-8a2a-4ec6-8a31-1080dfb9c916
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-982acccd-8d95-42da-9dd0-0d4100210607
----
<native crash>
``
```

Xperia XZ1 Android 11
90-beta2

**Comment by kbrosnan** [comment]
Native crashes are tracked on Bugzilla. See bz-1715151
