### ISSUE TITLE
Add "close other tabs" function 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#19889]
please add "close other tabs" to long press tab switcher, smartcookieweb (based on fenix) already have this feature just like many other browsers (Samsung internet, yandex Browser).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10947)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812834

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
