### ISSUE TITLE
"Fill link from clipboard" disappears on toggling search engines on

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#19880]
> ## Steps to reproduce
> Tap on address bar.
> ### Expected behavior
> You can see the clipboard suggestion regardless of search engines being toggled on or off.
> ### Actual behavior
> You can only see it if you toggle off search engines. Tapping on the search engine toggle will switch between showing the clipboard suggestion and search engines.
> ### Device information

> * Fenix version: Nightly 200904 06:01 (Build #2015761907)

> ![Screenshot_20200910-115745](https://user-images.githubusercontent.com/1082253/92786334-01725680-f35d-11ea-9920-cac4b275bd55.png)

Please see #14744. This bug has returned in Nightly.

* Firefox for Android version: 90.0a1 (Build #2015812491)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10940)

**Comment by opusforlife2** [comment]
Sorry. I'll copy the title and description if such a thing happens again.

**Comment by mcarare** [comment]
@opusforlife2 This was an intentional change, as "fill link from clipboard" would overlap the first engine in the list when the toolbar is set to top. 
Tagging UX to decide if we should keep the current behavior or try to also show "fill link from clipboard" when the engine list is displayed (obviously, without overlapping the engine list).

**Comment by opusforlife2** [comment]
@mcarare Do you mean it was intentional the first time or this second time?

Also, shouldn't "Fill link from clipboard" be shown from the bottom anyway? Even when the toolbar is up top, the keyboard is still opened at the bottom.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest builds:
- latest Release (95.1.0).
- latest Beta (96.0.0-beta1).
- latest Nightly 97.0a1 (2021-12-10).

Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by opusforlife2** [comment]
Hi.

**Comment by amocirean** [comment]
This issue is still reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using the following devices: Samsung Galaxy S22 Ultra (Android 13)
Removing the wontfix label.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807719

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
