### ISSUE TITLE
Unify the lock badge with a combined Connection and Tracking Protection menu

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19886]
After adding the Home button to the browser toolbar, we want to explore unifying the lock badge with a combined Connection and Tracking Protection menu to not have the browser toolbar appear overloaded.

**Comment by Amejia481** [comment]
QA team please help us to verify that this feature is working as expected.
We unified the tracking protection dialog with the lock icon, now only the lock icon should be visible.

![image](https://user-images.githubusercontent.com/773158/129793337-9c08ee19-7180-4f08-9a07-bf294419233a.png)


We want to test:

### 1) The connection panel change correctly when visiting  HTTP and HTTPS sites

#### 1.1 With a  HTTP should show -> Insecure connection 
#### 1.2 With a  HTTPS should show -> secure connection 


![image](https://user-images.githubusercontent.com/773158/129793643-5d4dedea-ff48-4fb5-a234-af4b087ca3b5.png)


#### 1.3 The connection sub menu should show the icon, title, URL, connection status  and the certificate info of the site.
![image](https://user-images.githubusercontent.com/773158/129794678-13790156-c346-4368-be89-9b09df6f3877.png)


### 2) Alter permissions on the dialog (allowed/blocked) 

![image](https://user-images.githubusercontent.com/773158/129794977-aa50c28f-f35e-46ad-b3e2-283ef7e3ebb2.png)


### 3) Under the "Details" section you should be able to see trackers information (blocked and allowed)

![image](https://user-images.githubusercontent.com/773158/129795298-85988c8d-0e42-4c8c-9c1d-d463eceb69d8.png)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed in Firefox Preview Nightly 2021-08-18. The lock submenus work according to the above screenshots.

**Comment by Amejia481** [comment]
@LaurentiuApahideanSV thanks :)
