### ISSUE TITLE
Content process seems to wait for main thread to finish before starting

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#19882]
Theoretically, the content process should be largely independent of main thread but it doesn't seem to start until the main thread start up code – e.g. inflating layouts – completes.

**Comment by MarcLeclair** [comment]
From our findings, the `Web Content Process` has 2 blockers:

1) [`DoFlushPendingNotifications`](https://share.firefox.dev/2RRT3Gc) seems to be an asynchronous calls that paints the content onto the screen ( could be wrong, seemed to match on the time line)

2) `LoadUrl` is queued behind a few calls such as fonts and addons. 

From looking at it ( which I'm sure others have done so too) , Extensions and Fonts are the biggest "culprit" to load things earlier. 

End result being that maybe removing things to get gecko started (CrashReporter / Glean as an experiment) is the next step to see if we can get to our end point faster
