### ISSUE TITLE
[Telemetry] Start on Home

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#19881]
For the feature of [start on home ](https://jira.mozilla.com/browse/FNX-22155), we want to add some telemetry events for:

- We know how often user lands on Homescreen upon opening the app
- We know how often user opens the tabs tray (by tapping on the tabs tray icon) immediately after landing on Homescreen.

## Acceptance Criteria
- [x] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [x] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by Amejia481** [comment]
QA team please help use to verify that we are sending the following events both under the category `start_on_home`:

- `enter_home_screen`: when the users enters the home screen.
- `open_tabs_tray`: when the user taps the tabs tray on the home screen.

**Comment by lobontiumira** [comment]
Verified on the 6/18 Nightly build with Google Pixel (Android 10) that the following events are sent under the `start_on_home` category. The `open_tabs_tray` is generated as expected:
```
{
          "category": "start_on_home",
          "name": "open_tabs_tray",
          "timestamp": 2828
        }
```
however, the `enter_home_screen` is not:
```
 {
          "category": "home_screen",
          "name": "home_screen_displayed",
          "timestamp": 8568
        }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-210618001)
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/6675246/logcat.txt)

@Amejia481 is the `enter_home_screen` event supposed to be generated when the user is tapping the homescreen button from the page toolbar's? Or after force closing Fenix, and reopened?
Removing the qa:needed label until further notice.

**Comment by Amejia481** [comment]
Thanks for testing @lobontiumira, sorry about the confusion, to trigger the event you need to have tabs opened, then kill the app and start the app (a could start).

**Comment by Amejia481** [comment]
> Thanks for testing @lobontiumira, sorry about the confusion, to trigger the event you need to have tabs opened, then kill the app and start the app (a could start).

A quick way is go to `Settings` -> `Tabs` -> `Start on home`, select always, then kill the app, and open it again. Remember that you have to have at least one tab opened.

**Comment by lobontiumira** [comment]
@Amejia481, I tried to do that, but killing the app doesn't save any event (only when putting the app in the background generates events).
I've generated also metrics, but I couldn't see anything.

[Glean metrics](https://debug-ping-preview.firebaseapp.com/pings/mira-210618004)

**Comment by amedyne** [comment]
@Amejia481 Are there other changes needed for this?

**Comment by Amejia481** [comment]
Sorry, I missed this one. I will double check and report back.

**Comment by Amejia481** [comment]
Thanks for testing @lobontiumira, I was able to to see both on the glean console:


<img width="1769" alt="image" src="https://user-images.githubusercontent.com/773158/124849386-ae613400-df6c-11eb-8c50-24d6e1dae0f7.png">

You can search for  **"Jul 7, 2021, 21:44:39" or  "Jul 7, 2021, 22:17:27"**
https://debug-ping-preview.firebaseapp.com/pings/test-metrics-ping 

These are the steps that I followed:

1. Open a tab.
2. Go to  `Settings` -> `Tabs` -> `Start on home`, select `always`.
3. Kill the app, and open it again.
4. I run this ADB command to force Fenix to send all `events`:  `adb shell am start -n org.mozilla.fenix.debug/mozilla.telemetry.glean.debug.GleanDebugActivity \
 --ez logPings true \
 --es sendPing events \
 --es debugViewTag test-metrics-ping`. **Make sure the parameter `sendPing` is set to events like this `es sendPing events ` as this pings are not part of the `metrics` they are part of the `events` pings**
5. Go to https://debug-ping-preview.firebaseapp.com

**Comment by AndiAJ** [comment]
Hi @Amejia481 , I've just checked this matter on the latest Nightly Build using a Google Pixel 3a (Android 11)

• **"Start on home"** = **"Always"**
• Force close Fenix from the app manager
• Manually launch Fenix (Normal Browsing)
• Force event type Ping **`e2850663-b32c-4c34-92fc-993a2c252f9c`** ✔️ 
• From the Home screen switch to Private Browsing
• Put Fenix in background 
• Event type Ping **`df00d662-9f16-44f9-a4e8-63f96fff591d`**  ✔️ 
• Force close Fenix from the app manager
• Manually launch Fenix (Private Browsing)
• Force event type Ping **`b42b2d99-58f4-475b-8aba-9be3ea988774`** ✔️  
• Switch back to Normal Browsing 
• Put Fenix in background 
• Event type Ping **`92280fdd-1627-4302-ac2d-c1bd25450681`** ✔️ 

[Log.txt](https://github.com/mozilla-mobile/fenix/files/6791196/Log.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-09071)

Not sure why we need to force the events after force close + re-opening Fenix ❓
Shouldn't it be automatically generated and visible after you put Fenix in background (as usual) ❓

**Comment by Amejia481** [comment]
```
Not sure why we need to force the events after force close + re-opening Fenix ❓
Shouldn't it be automatically generated and visible after you put Fenix in background (as usual) ❓
```

I'm not sure at what point glean sends `events`, when I was testing I had to specify `events` on the logcat command to be able to see the pings.

`org.mozilla.fenix.debug/mozilla.telemetry.glean.debug.GleanDebugActivity \ --ez logPings true \ --es sendPing events \ --es debugViewTag test-metrics-ping`

Maybe @tdsmith could help us to clarify.

**Comment by AndiAJ** [comment]
Didn't really force send the pings when testing any telemetry issues.
Both the events and baseline pings are sent automatically once the user puts Fenix in background.

I'm asking just to be sure that the `enter_home_screen` will be sent properly after the user selects "Always", force closes and re-launches Fenix. 

Many Thanks @Amejia481 ! ☺️

**Comment by Amejia481** [comment]
Ah Ok, :) 
I just added, the **force close** step for you to able to simulated it quickly, the ping should be sent every time users start on home on could start ups (cold starts) .

**Comment by AndiAJ** [comment]
Synced up with @Amejia481 and @badboy and it works properly! ☺️ 

Alternative STR for testing:
1. Open 2 tabs
2. Force-close Fenix
3. Open Fenix by tapping the icon.
4. Run `adb shell am start -n org.mozilla.fenix/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es debugViewTag AJ-0907000`
5. Give it a second, then put Fenix into the background.

**Comment by eliserichards** [comment]
PR: https://github.com/mozilla-mobile/fenix/pull/19885
