### ISSUE TITLE
Button for go forward is required

### ISSUE THREAD

**Issue by ankitkaran99** [mozilla-mobile/fenix#19890]
There should be a button for go forward in menu in Firefox. It is also available in chrome.

There is no way to go forward when you hit the back button and want to go again on that page.

This will helpful for the user perspective.

I have also attached a screenshot of chrome for android with similar functionality.

Screenshot : https://we.tl/t-U1PZ9tlkSI

**Comment by cadeyrn** [comment]
There _is_ a forward button in the menu of Firefox. 🧐

**Comment by ankitkaran99** [comment]
Sorry, It was there. I didn't noticed earlier. I am an idiot.
