### ISSUE TITLE
[Bug] Screen is flashing black while scrolling. 

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#19904]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
I have Twitter running as a PWA via Fenix Nightly. While scrolling through my Twitter feed, the page is frequently flashing black (I'm running my system and Firefox in dark mode, if that matters). Also seems to be happening when I just tap the screen. It's not every time, but it's often enough to be annoying. 

### Expected behavior
Page doesn't blank out while scrolling. 

### Actual behavior
Page blanks out while scrolling. 

### Device information

* Device vendor / model and Android version: Samsung Galaxy S21
* Firefox for Android version: 91.0a1 (Build #2015814987)

**Comment by kbrosnan** [comment]
@KWierso would you hook up to the `about:debugging` page and use that to capture a performance profile. https://profiler.firefox.com/docs/#/./guide-remote-profiling

**Comment by KWierso** [comment]
I haven't seen this bug since I restarted my phone. Gonna guess I had somethink wonky on my end. I'll reopen if it happens again and I'll try to snag a log.
