### ISSUE TITLE
[Bug][L10n] The Sign in to sync text does not fit the button when the language is Armenian

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#19910]
## Steps to reproduce
1. Launch Fenix and set the language to Armenian;
2. Tap the tab counter;
3. Observe the Sign in to sync button;

### Expected behavior
The text should fit inside the button.
### Actual behavior
The text does not fit inside the button and is cut off at the bottom
### Device information

* Device vendor / model and Android version: OnePLus 6T (Android 9)
* Firefox for Android version: Firefox 89.1.1 RC 90.0.0-beta.2
![Armenian](https://user-images.githubusercontent.com/50983519/121357346-697cba00-c93a-11eb-8fe4-fb56025bd1f0.jpg)

**Comment by Delphine** [comment]
I will contac the localizer and see if he can shorten the text. Otherwise, we should have a UX fix, I believe.

**Comment by amedyne** [comment]
@topotropic Here's another one that we may need UX input.

**Comment by eliserichards** [comment]
The button needs a defined width and height:

English (fits on one line):
<img width="321" alt="image" src="https://user-images.githubusercontent.com/43795363/122471610-154e8700-cf85-11eb-9ffc-5594a5ef6e02.png">

Armenian (2 lines): 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/122472426-319ef380-cf86-11eb-967d-98b98d24ac78.png">

I'll open a PR for this.

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/18 Nightly build with Google Pixel (Android 10):

<img src="https://user-images.githubusercontent.com/40694158/122522576-cbb27a80-d01e-11eb-9277-c8bd17ff2dc1.png" width="300" height="550" />
