### ISSUE TITLE
Migrate away from Fragment.startActivityForResult() 

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#19919]
Fragment.startActivityForResult(). This API is deprecated in androidx.fragment:fragment 1.3+.  Migrate away from it.
https://developer.android.com/training/basics/intents/result

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10967)

**Comment by rocketsroger** [comment]
For QA, please verify that WebAuthn is still working.  Thank you.

**Comment by mcarare** [comment]
Reopening this after https://github.com/mozilla-mobile/fenix/pull/28713

**Comment by mcarare** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814096

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
