### ISSUE TITLE
Implement the `X` button on the Credit Card `number` and `name` fields

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19912]
### What is the user problem or growth opportunity you want to see solved?
As a Fenix user, I want to be able to delete the Credit Card number or Name by tapping one button.
### How do you know that this problem exists today? Why is this important?
The `X` button is added to the Credit Card `number` and `name` fields.
### Who will benefit from it?
The user will be able to delete the CC number and name faster.

Example from Saved Logins.
![image](https://user-images.githubusercontent.com/42831109/121375881-bddb6600-c949-11eb-9408-dc7eb00246ba.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10961)

**Comment by gabrielluong** [comment]
I will note that the credit card editor intentionally deviated from the logins design. I will leave this in the backlog, but I don't think this should be picked up without some UX feedback if any changes were to be made.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814146

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
