### ISSUE TITLE
[Telemetry] Add telemetry for the Home screen button

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#19915]
## Description & Product Manager / Data Scientist User Story

As a Product Manager, I want to be able to retreive data on how many users Return to Home by tapping the new homescreen button.

User taps on the new homescreen button

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by amedyne** [comment]
Corresponding UI change is here: https://github.com/mozilla-mobile/fenix/issues/19876

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/15 Nightly build with Google Pixel (Android 10).
The "home button tapped" event was generated:
```
"category": "events",
          "name": "browser_toolbar_home_tapped",
          "timestamp": 5164
```
Ping: 25a9692f-28cd-44e0-9764-f3309053a0cb
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2106160002)
