### ISSUE TITLE
Hard to search with non-default search engine

### ISSUE THREAD

**Issue by RalfJung** [mozilla-mobile/fenix#19913]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

I think it should be easy/easier to do a search with something other than the default search engine. This used to be very convenient before the complete re-design a few months ago; it got a lot more cumbersome every since.

Old workflow:
- type the search term
- hit the icon of the search engine you want to use

New workflow:
- type the search term
- hit "search engine"
- hit the icon of the search engine you want to use
- hit "enter"/"go"

### How do you know that this problem exists today? Why is this important?

I know it exists because I encounter it at least once a week. :) What used to be a single tap is now 3 taps, which greatly discourages me from even using alternative search engines, and reaching for other hacks instead.

### Who will benefit from it?

Everyone who uses more than one search engine on a regular basis.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10962)

**Comment by JonDous** [comment]
Russian community supports you. We are migrating on Vivaldi now. They heard us and invented.

**Comment by RalfJung** [comment]
This is still a problem in the latest version.

**Comment by smammy** [comment]
@RalfJung, does turning on "Show search engines" in Settings → Search → Address bar make this more tolerable? It reduces the workflow to:

1. Tap the search engine you want to use.
2. Type your query.
3. Tap a suggestion or hit enter/go.

**Comment by RalfJung** [comment]
That is better, yes -- I have to get used to *first* selecting the search engine and then typing the query though; usually it works the other way around for me.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813656

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
