### ISSUE TITLE
Update the default autoplay setting to be block audio only

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#19922]
We want to change the default autoplay permission value to be **"block audio only"** instead of **"block audio and video"**.
related [ticket](https://jira.mozilla.com/browse/FNX-22660).

**Comment by Amejia481** [comment]
👋🏽 
QA please help us to verify that this feature is working as expected.

The autoplay default value should be "Block audio only", for new user and old users.
you can verify this by going to `Settings` -> `Site permissions` -> `Autoplay`.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (91.0a1 - Tuesday 6/22 @ 5:07 AM).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by Amejia481** [comment]
Thanks for testing @SoftVision-LorandJanos!
