### ISSUE TITLE
Keep a changelog of features that have landed in nightly

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19925]
This would be meant for _users_ of nightly like QA/UX and not meant to be a highly technical changelog.

Some considerations:
 - Automation to generate a list of **high-level** things that have landed.
   - Maybe using a PR format that will add a line to the list.
 - We have milestones today that does this, but they also include eng-specifics that make it had to read through the list (test failures/clean-up PRs etc).
   - We could re-qualify what should go into this list (e.g. feature PRs and bugs) to make it more readable.

cc: @topotropic

**Comment by LittleAngelwings** [comment]
If a nightly user really interested he can see on the following page what has landed days by day: https://github.com/mozilla-mobile/fenix/commits/master

**Comment by topotropic** [comment]
Thanks, @jonalmeida!

This sounds like a first good step. 

It would be great if we could filter the changelog after release number or feature. So that QA/UX could look up things like  “everything that lands in 89” or “everything related to credit card autofill” etc. eventually.
