### ISSUE TITLE
Renew expired telemetry probes

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#19923]
There are a few probes that have already expired, and a long list of probes that are expiring in July.

- [x] Document expiring/expired probes
   - https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit# 
- [x] Review list with @vesta0 to determine which should be renewed
- [x] Replace `notification_emails` with updated mailing list

**Comment by lobontiumira** [comment]
Hi, @eliserichards 
Could you please help us with some more info regarding how can QA verify these renewals?
Thank you!

**Comment by lobontiumira** [comment]
I'll remove the qa:needed until further details.

**Comment by lobontiumira** [comment]
Hi all,
I've verified the telemetry metrics were renewed. Added the new expiration date in [Elise's doc](https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit).

@eliserichards should I leave this issue opened until the `contextual_hint.tracking_protection` category will be renewed or not?
Thank you!

**Comment by eliserichards** [comment]
This issue can be closed now :)
