### ISSUE TITLE
[Bug] [Nightly] Addons not customizable and not working

### ISSUE THREAD

**Issue by Bolthier** [mozilla-mobile/fenix#19927]
## Steps to reproduce
1. Install newest Firefox Nightly release
2. Install uBlock Origin
3. Open 3dot menu
4. Open addon menu
5. See no option to configure uBlock Origin and addon not working

### Expected behavior
Addon should be customizable and working as intended

### Actual behavior
Addons not working

### Device information

* Device vendor / model and Android version: Oneplus 3T / Android 9
* Firefox for Android version: 91.0a1 (Build #2015815371)

**Comment by sheikh-azharuddin** [comment]
It is working fine here... Click 3 dot menu, click add ons, click add ons manager > click ublock origin > click settings
![Screenshot_20210610-113140](https://user-images.githubusercontent.com/58127841/121472882-73a4c400-c9df-11eb-9625-fc1de0349d66.png)



![Screenshot_20210610-112945428](https://user-images.githubusercontent.com/58127841/121472806-5a037c80-c9df-11eb-9cec-15c3502c8921.jpg)
![Screenshot_20210610-112932708](https://user-images.githubusercontent.com/58127841/121472838-612a8a80-c9df-11eb-80d8-2338e892bb1b.jpg)

**Comment by Bolthier** [comment]
Reinstalling the Nightly app fixed the issue. Uninstalling all addons (which I tried before creating this issue) didn't solve it. Thank you.
