### ISSUE TITLE
Tapping back button after tapping the new home button should redirect to the previous page

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#19926]
I'm super happy that finally fenix (Nightly got an home button) but it is seriously flawled. 
let's say I'm on ciao.it website and then I tap home button, but the i decide to do nothing but returning to ciao.it website (by pressing android back button) - -->at this point instead of returning to ciao. it as expected fenix is abruptly minimized!! (go to home, but why??)please fix it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10973)

**Comment by lobontiumira** [comment]
Thanks for filing this ticket, @ale82to!
I confirm that, after tapping the home button from the toolbar, then the back button, Firefox is closed.
Tested with 6/10 Nightly with Google Pixel (Android 10).

**Comment by ale82to** [comment]
how can this be considered a feature I don't really understand in chrome, Samsung internet and yandex from home using the android back buttun get u back on the website u were in.
honestly Fénix is really bad

**Comment by lobontiumira** [comment]
@ale82to we do have another way of returning to the previous opened tab - by tapping on the tab from the "Jump back in" section which is displayed on homescreen. This is available on the 6/11 Firefox Nightly build.

![Screenshot_2](https://user-images.githubusercontent.com/40694158/121635776-824ab400-ca8f-11eb-87ec-75b966d0f14b.jpg)

**Comment by ale82to** [comment]
thank you very much for letting me know but still it's unnatural and over complicated in Firefox desktop or any other mobile browser home button preserves history without opening a new tab at this point home button with actual behavoiur is totally useless. Sorry for being so harsh but tap management is the worst part of fenix. (when old fennec was perfect!)

**Comment by TrianguloY** [comment]
According to [android guidelines](https://developer.android.com/guide/navigation/navigation-principles): 
> The Back button ... is used to navigate in reverse-chronological order through the history of screens the user has recently worked with.
 > Operations that change the back stack always operate on the top of the stack, either by pushing a new destination onto the top of the stack or popping the top-most destination off the stack.

Which means that pressing the home button is considered like adding a new destination (because the previous ones, the tabs, are not removed) so pressing the back button should go back to the previous tab instead of closing the app.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814147

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
