### ISSUE TITLE
[Bug] Rename Top Sites to Shortcuts

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/fenix#19932]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

This seems like an oversight, so I'm filing this as a bug.

## Steps to reproduce
- Open the kebab menu.

### Expected behavior
- "Add to top sites" is instead named "Add to shortcuts"

### Actual behavior
- Observe that "shortcuts" are called top sites.

## Why is this important?
With the Proton redesign, "top sites" has been renamed to "shortcuts" on both desktop and iOS. Continuing to call it "top sites" on Android is both confusing and inconsistent from other platforms.

### Device information

* Device vendor / model and Android version: n/a
* Firefox for Android version: ? (go to Settings -> About Firefox) 91.0a1 (#2015815371)

**Comment by kbrosnan** [comment]
This is done.
