### ISSUE TITLE
FNX-22337 - Homescreen updates

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#19933]
Tracking https://jira.mozilla.com/browse/FNX-22337

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly (92.0a1 20210726T05:09:42.829).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).
