### ISSUE TITLE
Can accidentally close a tab instead of selecting it

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#19937]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open a website.
2. Open the tabs tray, make sure the tabs layout is grid view.
3. Open the overflow menu, click Select tabs.
4. Tap the area around where the close tab button would be (not necessarily exactly on it).
### Expected behavior
The tab should be selected, no matter where you tap.
### Actual behavior
The tab closes if you accidentally tap it around where the close button would be.
### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9)
* Firefox for Android version: Nightly 6/10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10982)

**Comment by Mugurell** [comment]
I think this reproduces only for the grid view?
Seems like the close button visibility is set to "invisible" instead of "gone".

**Comment by sv-ohorvath** [comment]
> I think this reproduces only for the grid view?
> Seems like the close button visibility is set to "invisible" instead of "gone".

Yes, that's true, only on the grid view.

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue. Can you point out the file please? thanks

**Comment by jonalmeida** [comment]
Hi @himanshu007-creator !

You could take a look at the layout file for the grid view ([`tab_tray_grid_item`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/res/layout/tab_tray_grid_item.xml)) and the [viewholder](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt#L107) to make change the close button visibility from "invisible" to "gone" as @Mugurell mentioned above.

Make sure to check if this change has any side-effects to the layout when in multi-select mode.

Happy to answer questions if you have any. 🙂

**Comment by BBBmau** [comment]
I've taken a look at the viewHolder line of code and changed it to isGone.

From reading the comments, not sure how changing it from "invisible" to "isGone" would do much since that is just making it so the x button does not show up visually from what I understood.

Hope to hear some input on this! I am fairly new to Open-Source but am interested in helping as much as possible! :)

**Comment by Mugurell** [comment]
@BBBmau Both visibility modifiers will lead to the view not being visible but going by the documentation
- `INVISIBLE` [will make view invisible, but it still takes up space for layout purposes.](https://developer.android.com/reference/android/view/View#INVISIBLE)
Hence it can still receive touch events.
- `GONE` [will make the view invisible, and it doesn't take any space for layout.](https://developer.android.com/reference/android/view/View#GONE)
This meaning that it will actually be removed from the layout like it never existed and so we won't be able to click on it anymore.

**Comment by BBBmau** [comment]
Thanks for the clarification @Mugurell !

I went back to do some debugging on both the layout file and the viewHolder file. From my experience changing "closeView.isInvisible" to "closeView.isGone" wasn't enough to solve the bug.

`        closeView.isGone =  trayStore.state.mode is TabsTrayState.Mode.Select
`

I did make the change to closeView.isGone and looked deeper into the onBindViewHolder and added the condition to prevent the onClickListener to be active when isGone is true. It looks like it solved the problem! :)

![firefox_tabs_gif](https://user-images.githubusercontent.com/65101411/122285625-d268b280-cea3-11eb-9f08-32fea8abd531.gif)

**Comment by Mugurell** [comment]
Thank you for looking into this @BBBmau !
As I said in the PR, if `View.GONE` doesn't work for the grid item but works for the list item it seems there is a deeper issue with the grid item layout that needs to be investigated.

**Comment by avichal94** [comment]
Is this issue still open or did it get fixed?

**Comment by jonalmeida** [comment]
@avichal94 I would refrain from working on this bug at this point because the team is in the process of re-writing this part of the UI into Jetpack Compose.

**Comment by AkshatK1** [comment]
Hi, I tried to reproduce this issue. The bug still exists.

Android Version: 9
Firefox Version: 103.2.0 (this is the latest version on playstore)

https://user-images.githubusercontent.com/59464190/184653311-5a97496f-8b7a-4e7f-a7de-dd4177acbfad.mp4

**Comment by sssurvey** [comment]
I think this issue should be closed. Based on the latest design changes. It seems like the `Close` will be `View.VISIBLE` during the __tab selection__ screen. Which means this ticket is no longer valid. @Mugurell @jonalmeida 
[device-2023-01-08-223720.webm](https://user-images.githubusercontent.com/2370877/211237301-a8d718c3-4b1d-489d-9d12-f580f54c4cd4.webm)

**Comment by Mugurell** [comment]
> I think this issue should be closed. Based on the latest design changes. It seems like the `Close` button will be `VISIBLE` during the **tab selection** screen. Which means this ticket is no longer valid. @Mugurell @jonalmeida
> device-2023-01-08-223720.webm

The intention (as seen in code) is to not show the close button in multi-select mode.
Not sure how recent of a regression this is, it may warrant fixing the visibility in a separate issue.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812875

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
