### ISSUE TITLE
[Telemetry] Add telemetry for Homescreen Recently Added Bookmarked Items 

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#19931]
## Description & Product Manager / Data Scientist User Story
    As a Product Manager, I want to collect telemetry data on recently added bookmarked item(s) to homescreen
        User opens the last bookmarked page(s) from the homescreen

## What questions will you answer with this data?
    
- User opens the last bookmarked page(s)
- ~User opens the last accessed folder(s)~ tbd in separate issue
- User opens bookmarks section (show all)
- How often is this section displayed?

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by amedyne** [comment]
Fenix change for the feature is tracked [here](https://jira.mozilla.com/browse/FNX-22339).

**Comment by Mugurell** [comment]
Waiting for the feature work to complete.

**Comment by eliserichards** [comment]
DS ticket: https://mozilla-hub.atlassian.net/browse/DO-542

**Comment by AndiAJ** [comment]
Hi @eliserichards I've just checked this matter on the latest Nightly 93.0a1 8/25 and it looks like both the **`bookmark_clicked` and `show_all_bookmarks` counters aren't displayed in the metrics ping**.

[Logcat](https://github.com/mozilla-mobile/fenix/files/7046587/bookCounters.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-2508000)

Please review and share your thoughts ☺️

**Comment by AndiAJ** [comment]
Still not working on latest Nightly 93.0a1 from 8/30 using a Google Pixel 3a (Android 11)

**Comment by Mugurell** [comment]
I tested this locally with GleanDebugActivity and `sendPing metrics` with the metrics available here - https://debug-ping-preview.firebaseapp.com/pings/PetruBookmarksTest

My results:
action in app | metric name in the "metrics" ping | metric time | value
-- | -- | :---: | :---:
clicked a bookmark | recent_bookmarks.bookmark_clicked | 12:39:33 | 1
clicked "Show all" | recent_bookmarks.show_all_bookmarks | 12:39:33 | 1
&nbsp; | &nbsp; | &nbsp; | &nbsp;
clicked a bookmark 3 more times | recent_bookmarks.bookmark_clicked | 12:41:41 | 4
clicked "Show all" 3 more times | recent_bookmarks.show_all_bookmarks | 12:41:41 | 4

To me this is exactly as expected.

I understood from Andi that he tested without forcing Glean to collect and report events - actions in one day, checked the next day after 4:00 AM.
If this scenario doesn't work I'd say it's an issue with Glean / Glean implementation in the app.
What's interesting about this scenario is that other counters in the metrics ping are correctly reported, only the ones from this patch not.

@Dexterp37 any idea why these metrics would not be recorded while others would?

**Comment by Mugurell** [comment]
There are some events (but just a few) on Glam - https://glam.telemetry.mozilla.org/fenix/probe/recent_bookmarks_bookmark_clicked/explore

**Comment by eliserichards** [comment]
That does kind of make sense.. this PR was implemented based on @rocketsroger's new instructions from the Glean team. It is not the same way that the majority of the probes are implemented on Fenix, because we were using preferences to save the values (like a fake database, [example](https://github.com/mozilla-mobile/fenix/blob/91819626b42b55232fff4fcf4b9f232e49e7b465/app/src/main/java/org/mozilla/fenix/utils/Settings.kt#L1040)). From now on we will be implementing the metrics using this approach. 

I guess this means that we should talk about the correct way to verify that the data is being sent. Thoughts @rocketsroger @Mugurell?
