### ISSUE TITLE
Form sends old values, not respecting changes

### ISSUE THREAD

**Issue by mynthon** [mozilla-mobile/fenix#19939]
fenix 89.1.1 Android (various versions)

First this is very strange bug I am unable to reproduce it on any other site. The site itself is behind login screen and i can't give access to it but maybe someone has seen this kind of bug before. This bug does not appears on other browsers than mobile firefox (89.1.1 now). I debug it using usb connection to pc. On desktop version with responsive view everything works perfectly.

The problem is with form. Lest say we have 3 variables. One is form's action which default is 'noplace.php'. Next two are hidden fields with names 'type' and 'id'. And those 3 elements change basing on user actions. The example values are 'search.php' for form's action and eg. 'hospital' for type and 34 for id. 

Debugger shows that changing values works perfectly. They are changing in code (inspector) and proper values are printed in console via console.log() added to form's onsubmit event. Same when checking document.forms, all looks ok. But form doesn't respect those changes and sends values that were set on page load. I have tried many different things like replacing button-type=submit with <submit /> element. Adding new elements to page to force DOM refresh. Setting timeouts and it doesn't work. Well it works but 1 time for about 50 tries.

Form works perfectly in every other browser, desktop (yes, also firefox) and mobile on any platform, and it has worked perfectly for many years without any bigger changes. I can confirm 

I will gladly add more feedback but after spending 2 days with this problem really run out of ideas.

**Comment by Mugurell** [comment]
Does this issue reproduces with other browsers / on other platforms?

**Comment by mynthon** [comment]
Did little more debugging and no, only android/firefox. Firefox desktop, iOS or any other browser works ok. Also I noticed that i debugged that incorrectly. I get different values when querying fields from console (remember: debug via usb) and from form's on submit.

```
console.log(document.querySelector('[name=id]').value)
console.log(document.querySelector('[name=type]').value)
console.log(document.forms[0][13])
8 debugger eval code:1:9
city debugger eval code:2:9
<input id="type" type="hidden" name="type" value="city"> debugger eval code:3:9

// onsubmit below

id= <empty string> min.js:8721:9
type= <empty string> min.js:8722:9
forms[0][13] <input id="id" type="hidden" name="id" value=""> min.js:8723:9
```

![firefox89debug](https://user-images.githubusercontent.com/995932/121537200-0192a600-ca04-11eb-96af-2288fe5eb976.png)

**Comment by Mugurell** [comment]
I'm curious with which version this bug started
and also if you could test the same scenario on this 2 apks
- https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.geckoview-version.89.0.20210419094740.mobile/android-aarch64-opt
- https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-debug
(They are stripped down versions of the browser, helps with eliminating some causes)

**Comment by mynthon** [comment]
Ok, i have checked both apks and this bug exists on both of them. But after additional checking I am not sure if it is firefox bug. For sure my first diagnosis is incorrect. The values filled in hidden form fields come from typeahead script (suggest/autocomplete). The script listens for keypress events to prepare list of suggestions. When item on the list is selected another event is fired. But in mobile firefox it looks like firefox sends one more keypress. So selecting item from list sets correct values for hidden inputs but then one more keypress is send which fires autocomplete again. When submit button is clicked suggest-input looses focus and because no option is selected hidden fields are cleared and empty value is send.

You can observe this behavuior here: https://jqueryui.com/autocomplete/

For now I am closing ticket as
