### ISSUE TITLE
FNX-5384 ⁃ [Bug] Toolbar locked in expanded state after onResume

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#1993]
## Steps to reproduce
1. Load page
1. Click home 
1. Background app
1. Resume app
1. Reopen tab

### Expected behavior
Toolbar has scrolling behavior

### Actual behavior
Toolbar doesn't scroll away

### Device information
* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment]
By background the app you mean swipe kill the app?

**Comment by ekager** [comment]
Just pausing the app by switching apps in the app launcher and then resuming Fenix was causing this before the fix.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 4/29 build.
