### ISSUE TITLE
Manually add a login

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#19947]
## User Story
- As a user, I want manually add a login to my saved logins, so that I can: sync logins, use autofill, etc.

### Acceptance Criteria
From our settings, the user can access their list of saved logins and they can edit or delete the logins. We would like to add the ability to manually add a login as well. 

Notes:
- This would probably follow the same formatting as the Edit Logins screen.
- When a user is entering the information, we need to validate that the data is correct (e.g. is this a valid URL? is the password blank?)
- This inline validation should already exist for Edit
- Do we allow duplicate entries? - this validation might also exist for Edit

**Comment by VitalyVPinchuk** [comment]
Hi, can I try implementing this?

**Comment by eliserichards** [comment]
Uplifting this into beta 93 as well

**Comment by SoftVision-LorandJanos** [comment]
Verified as implemented on the latest Nightly (94.0a1 - 2021-09-13T05:10:02.695825).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.

**Comment by VitalyVPinchuk** [comment]
Hello!
I think there's a kind of security bug.
1) Open `addLoginFragment` as if adding new login
2) Go to launcher's home screen to put the app to the background
3) Return to the app
You're back in `addLoginFragment` and can go to saved password list skipping re-auth fragment.

There's also a memory leak (if you stay long enough at launcher's home screen after putting the app to the background leak canary will pop up).

**Comment by VitalyVPinchuk** [comment]
Oh I was wrong about the bug which I caused myself by fixing copy/paste error in AddLoginFragment and not fixing it in the other part
https://github.com/mozilla-mobile/fenix/blob/abc881f9f87171a0cf77813e24d7919030930328/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt#L327

which should be `R.id.addLoginFragment`

Sorry about that
