### ISSUE TITLE
[Bug] Trying to import certificate causes crash

### ISSUE THREAD

**Issue by fancsali** [mozilla-mobile/fenix#19945]
## Context
This issue was discovered when trying to find a workaround to #16993 as in my setup I badly need user certs in my browser. Looking at that issue, and this one, I feel there's literally no way to import certificates into Firefox on Android; and as far as I could find out (or test) the Android Trust Store will **not** be used by FF.

## Steps to reproduce
- Try to open a URL which serves a `.p12` or `.pem` file with the correct MIME-type (application/x-pkcs12, application/x-pem-file; or even application/x-x509-user-cert as described here: https://mtersch.wordpress.com/2015/03/17/certificate-import-in-firefox-on-android/) OR try to open `.p12` or `.pem` file locally (described here: https://blog.felixbrucker.com/2015/10/27/how-to-import-your-own-ca-cert-into-firefox-on-android/)

### Expected behavior
- The certificate details will be displayed and Firefox offers to import the certificate

### Actual behavior
- Firefox crashes

### Device information

* Device vendor / model and Android version: OnePlus Two (OP2) running Android 10 (LOS 17.1)
* Firefox for Android version: 89.1.1 (Build #2015812947)

**Comment by kbrosnan** [comment]
The Android cert store can be imported on Firefox 90 and higher using the "secret settings" option that can be enabled by tapping the Firefox logo in the About Firefox page.

Please provide a crash ID https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by fancsali** [comment]
Well, there have been a few actually...

Trying to open a remote URL:
- ebae2356-59ff-48e8-8001-630e39c73835
- 790e3fbe-800e-49a1-a81b-234cdad5ad98
- eed7d203-563a-4e34-980d-14e80c45a21c
- e34ec457-663f-45d7-87a1-7c241a494791

Using `file:///`:
- 95cb8499-7e02-4578-b9e6-9b58dfb06612
- 37876b7b-7bf1-45ce-981a-9b8961e9add0
- 02e1ed17-ee4b-46d4-ad1c-dbbe1f580706

Regarding the other comment: I do appreciate the tip, however on one hand I
am on FF for Android 89, and I suspect many of my customers will be too. On
the other hand, I am happy to muck about in internal settings, but I am not
entirely sure, the less-technically-inclined users will be.

**Comment by kbrosnan** [comment]
None of those crashes are the submitted IDs. Please go to the crashes page and tap on the links to get the shareable URLs.
