### ISSUE TITLE
Device names sticky in sync list

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#19942]
Make the device names sticky in the synced tabs view so that when people scroll they see the device name until another device is listed.

**Comment by jonalmeida** [comment]
Eng notes: We can do this with an `ItemDecoration` that we can extend from our existing `SyncedTabsTitleDecoration`

**Comment by gabrielluong** [comment]
Designs https://www.figma.com/file/hJfV1KGZuOK7OYr29pooL5/Lists?node-id=69%3A6540
