### ISSUE TITLE
[Telemetry] Tab view preference

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19956]
## Description & Product Manager / Data Scientist User Story
As a Product Manager I want to know if a user changes the default tab view preferences, so we have a better understanding of what our users like and can optimize the experience in a way that serves them.

## What questions will you answer with this data?
I want to be able to know which tab view users prefer to distinguish if they are using the default changing it themselves.

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

Filed on behalf of @vesta0

**Comment by AndiAJ** [comment]
Hi **verified as fixed** on both **Nightly 92.0a1 8/11** and **92.0.0 Beta 1**

**✔️ Nightly 92.0a1 08/11**
• Change Tabs setting to "List" - Ping 17c333e6-3364-44ad-b22f-31f20e4bec35
```
{
          "category": "events",
          "extra": {
            "type": "list"
          },
          "name": "tab_view_changed",
          "timestamp": 1148
        }

```
• Change Tabs setting to "Grid" - Ping 6b2a049e-9868-4fa1-b9a6-ac34893f2e74
```
{
          "category": "events",
          "extra": {
            "type": "grid"
          },
          "name": "tab_view_changed",
          "timestamp": 574
        }
``` 

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-1108001)
[Logcat](https://github.com/mozilla-mobile/fenix/files/6968156/NTabs.txt)


**✔️  Firefox 92.0.0 Beta 1**

• Change Tabs setting to "List" - Ping 7a55e4c1-82bb-4df3-9d79-b6e3b2dd2a6a
```
{
          "category": "events",
          "extra": {
            "type": "list"
          },
          "name": "tab_view_changed",
          "timestamp": 7212
        }
```

• Change Tabs setting to "Grid" - Ping 773665f8-2621-40e8-8a02-6d852df0d052
```
{
          "category": "events",
          "extra": {
            "type": "grid"
          },
          "name": "tab_view_changed",
          "timestamp": 679
        }
```

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-1108000)
[Logcat](https://github.com/mozilla-mobile/fenix/files/6968104/BTabs.txt)
