### ISSUE TITLE
change position of the home button

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#19952]
I propose to move the home button next to the tabs button. I know that the current position matches the position of the home button in Google Chrome but for me it's not reachable at all when I use my smartphone with only one hand, while the proposed position would allow me to use *every* toolbar feature (well, except the tracking protection shield because it's on the old home icon position then, but I would use the home button much more often than the shield button). So it's not only about aesthetics, it would be an usability advantage.

![home-2](https://user-images.githubusercontent.com/1100614/121572618-aae99400-ca24-11eb-9c95-136a26ae7c3e.png)

Left: current placement
Right: proposed placement

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10994)

**Comment by cadeyrn** [comment]
While I understand that the current position might be better for left-handed users please note that there is no left-handed mode in Firefox at all. Optimizations for left-handed users should be done with the whole product in mind, not only for one single button. There is #6365 for designing a left-handed mode.

**Comment by LittleAngelwings** [comment]
I know that's not the point of this issue ;) And I know the Ticket #6365 but there is no action for a long time :(

**Comment by amedyne** [comment]
@topotropic @Verdi Some more feedback on the Home Button.

**Comment by cadeyrn** [comment]
> It's still a valid request and should be, if at all, WONTFIX'ed by the UX team, not by a bot. :)
