### ISSUE TITLE
Use Proton icon for the Home button

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#19951]
For the sake of consistency I propose to use the new Proton icon that is used in Firefox 89+ for the desktop as the icon for the new home button, especially since the currently used icon has a stronger stroke width than the other icons.

![home-1](https://user-images.githubusercontent.com/1100614/121571039-d0759e00-ca22-11eb-8fac-6b0db2826cb5.png)

Left: current icon
Right: proposed icon

**Comment by gabrielluong** [comment]
Thanks for bringing this up. I think this will be interesting for our designers to consider.

**Comment by amedyne** [comment]
@topotropic What do you think?

**Comment by topotropic** [comment]
Yes! 
[home.svg.zip](https://github.com/mozilla-mobile/fenix/files/6662555/home.svg.zip)
