### ISSUE TITLE
[Bug] "Open links in apps" breaks logins to many sites...

### ISSUE THREAD

**Issue by gatopeich** [mozilla-mobile/fenix#19963]
When "Open links in apps" is enabled and you don't have the specific app installed, it is impossible to login to PayPal, eBay, or my banking sites. Instead you get a blank page or a new tab into the main page.

## Steps to reproduce
1. Don't install PayPal app
2. Enable "Open links in apps"
3. Go to PayPal.com => login
4. Try to login

### Expected behavior
Successful  login

### Actual behavior
On PayPal the "in progress" animation appears and stays forever.
On other app-enabled sites like eBay or my bank I get blank login screen, or a new tab with the main page.

### Device information

* FairPhone 3 / Android 10 latest update
* Firefox for Android version: 89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

**Comment by SoftVision-LorandJanos** [comment]
Hi @gatopeich ! Thank you for your report! I wasn't able to reproduce the issue you described above. I've logged in successfully on Paypal, on ebay, on a bank's page, there were no issues. Could you check if you have the same issue after you clear the data? Or maybe check if it reproduces on the latest nightly. Thank you!
Devices used for testing:  Samsung Galaxy Tab 3 with Android 9 and Google Pixel 4 with Android 11.
Firefox for Android version: 89.1.1 (Build #2015812947)

**Comment by gatopeich** [comment]
I get the same behaviour on current version 92.1.1 (Build #2015832083)
AC: 92.0.15, e00bef534d
GV: 92.0-20210903235534
AS: 82.1.0
After 2 attempts, the following screen stays with the circle going around forever:
![Screenshot_20210928-225211](https://user-images.githubusercontent.com/7722268/135170930-a5c8c417-07b2-4d13-940b-af0dbeed95d7.png)
Also it leaves 3 opened tabs on the same site, so I suspect each attempt is opening a new tab.

**Comment by sflorean** [comment]
@gatopeich this is still reproducible for you?

**Comment by gatopeich** [comment]
PayPal login works now.
