### ISSUE TITLE
Blank page restored after tab crash

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#19964]
## Steps to reproduce
1. Navigate to any website
2. In the same tab navigate to about:crashcontent
3. Tap the "Restore tab" button

### Expected behavior
The website loaded in step 1 should be restored.

### Actual behavior
The website loaded in step 1 isn't restored.
A blank page is displayed instead.

### Device information

* Device vendor / model and Android version: 
► Google Pixel 3a (Android 11)
* Firefox for Android version: 
► Nightly 91.0a1 from 6/10

### Notes
❗ Not reproducible on every attempt.
Root cause for #19585

► Video
![20210611-112521-online-video-cut](https://user-images.githubusercontent.com/51314259/121657735-54726900-caa9-11eb-87c6-13654f5b970f.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11000)

**Comment by delia-pop** [comment]
This issue was reproduced again on 93.0.0-beta.1 (Build 2015832715) with Huawei P9 Lite (Android 8).
The page is not restored upon selecting "Restore Tab", and a blank page is displayed. This behavior in not 100% reproducible.

**Comment by AndiAJ** [comment]
Hi still reproducible on the latest Nightly 96.0a1 from 11/26 using a Google Pixel 3a (Android 11)

►Video

https://user-images.githubusercontent.com/51314259/143550193-4c75ff5d-069a-4da6-9406-0638c460ee7a.mp4

**Comment by AndiAJ** [comment]
Still reproducible on the latest Nightly 98.0a1 from 2/3 using a Google Pixel 3a (Android 11)

**Comment by AndiAJ** [comment]
Still reproducible on the lastest Nightly 99.0a1 2/23 using a Google Pixel 3a (Android 11)

**Comment by AndiAJ** [comment]
Still reproducible on the latest Nightly 1010a1 4/11 using a Google Pixel 3a (Android 11)

**Comment by AndiAJ** [comment]
Still reproducible on the latest 102.0a1 using a Google Pixel 3a (Android 11)

**Comment by AndiAJ** [comment]
Still reproducible on the latest 103.0a1 using a Google Pixel 3a (Android 11)

**Comment by AndiAJ** [comment]
Still reproducible on the latest 104.0a1 using a Google Pixel 3a (Android 11)

**Comment by AndiAJ** [comment]
Still reproducible on the latest 107.0a1 using a Google Pixel 3a (Android 11)

**Comment by AndiAJ** [comment]
Still reproducible on the latest 109.0a1 using a Google Pixel 3a (Android 11)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812772

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
