### ISSUE TITLE
[Bug]Taps not working while magnifying with accessibility feature

### ISSUE THREAD

**Issue by Shane-Carelse** [mozilla-mobile/fenix#19969]
When using the system’s magnification accessibility feature, tapping on a element in the webview doesn’t seem to work as expected. It seems like the tap is detected, but not on the intended element.
This issue only seems to occur in the webview. When using this accessibility feature and tapping on the address bar or in the menus I do not experience any issues.

## Steps to reproduce

1. Enable the android magnification feature by going to Settings > Accessibility > Visibility Enhancements > Magnification and turn on "Magnification shortcut triple-tap screen";
2. Open a webpage in Firefox; 
3. Triple-tap on the screen to use the magnification feature;
4. While the magnification feature is engaged, use two fingers to pan across the screen and find a link or button;
5. Do a single finger tap on the link or button to activate it.

### Expected behavior
The link or button that you tapped is activated. For example tapping on a link while using the magnification feature should take you to the link target.

### Actual behavior
Either nothing happens or a different element registers the tap.

### Device information
Samsung Galaxy S20 FE running Android  11 (Samsung One UI 3.1)
Firefox v89.1.1 Build #2015812947

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the OnePlus 5T (Android 10), nor on Samsung Galaxy Note 8 (Android 9) on neither RC 89.1.1, and 6/14 Nightly build.
Maybe it's an Android 11 specific issue.
