### ISSUE TITLE
Make "Save this password" and "Autofill saved passwords" independent

### ISSUE THREAD

**Issue by MoritzBeroRoos** [mozilla-mobile/fenix#19979]
### What is the user problem or growth opportunity you want to see solved?
When using the autofill password option, you cannot disable the prompt "Save this password" for all Websites.
I am aware i can disable it for any one specific website, but not for every one.

### How do you know that this problem exists today? Why is this important?
I normally use my password manager for 99% of my passwords. However there are a few websites where i just want to store the login in firefox without it beeing protected by my password managers master password.
### Who will benefit from it?
Users with similar use of firefox password autofill

Cheers

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11012)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812441

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
