### ISSUE TITLE
[Bug]home button /jump back confusing and useless 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#19974]
the new *jump back in* recently added when using home button in useless, confusing and stupid, why the home button cannot just behave like Firefox desktop or any other mobile browser PRESERVING history without opening a new tab? 
is that so hard??!!

**Comment by amedyne** [comment]
Thank you for your feedback. This is a feature is in progress. We are working on adding more capabilities to make browsing better for our users.
