### ISSUE TITLE
[Bug] - "Find in page" results are not highlighted as expected

### ISSUE THREAD

**Issue by ksy36** [mozilla-mobile/fenix#19975]
## Steps to reproduce
1. Visit https://codeburst.io/introduction-to-binary-numbers-b0404f4401e3
2. Click on three dot menu, select "Find in page" 
3. Search for 6502

### Expected behavior
All search matches are highlighted

### Actual behavior
Just one match is highlighted at a time 

We've received a report regarding this in https://github.com/webcompat/web-bugs/issues/76565, not sure whether it's expected?

![image](https://user-images.githubusercontent.com/1303908/121740989-e2f7e200-cacb-11eb-9f8c-edb0ab53867a.png)

### Device information

* Device vendor / model and Android version: Pixel 4a
* Firefox for Android version: 91.0a1 (Build 2015815587), GV: 91.0a1 - 20210608091819

**Comment by kbrosnan** [comment]
We get the [Findbar behavior from Gecko](https://searchfox.org/mozilla-central/source/modules/libpref/init/all.js#753). For right now it is expected that only the first instance of the match is highlighted.
