### ISSUE TITLE
FNX3-15975 ⁃ [Bug] "open link in new tab" and fullscreen API does not use a "FenixSnackbar"

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1997]
### Steps to reproduce
1. open a website
1. long press on a link
1. open link in new tab

### Expected behavior
The snackbar is a "FenixSnackbar".

### Actual behavior
The snackbar has a different style.

![snackbars](https://user-images.githubusercontent.com/1100614/56689094-8c0bd480-66da-11e9-8680-74d635b8c908.png)

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision eadce68e520d1bc2c6be853d1481b5f62b620449

**Comment by cadeyrn** [comment]
Fullscreen API is also using the Non-Fenix snackbar.

**Comment by ekager** [comment]
Blocked on AC work: 
https://github.com/mozilla-mobile/android-components/issues/2825

**Comment by pocmo** [comment]
@ekager The component now allows to pass in a custom `SnackbarDelegate` where you can handle showing the Snackbar youself:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt#L45

Default implementation:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt#L274

**Comment by cadeyrn** [comment]
Fixed by #3028.
