### ISSUE TITLE
PWAs show an empty space for the toolbar, but only when the toolbar position is ‘Top’

### ISSUE THREAD

**Issue by rhendric** [mozilla-mobile/fenix#19972]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

1. From the three-dot menu, select Settings > Customize and set:
    * ‘Toolbar’ to ‘Top’
    * ‘Scroll to hide toolbar’ disabled
2. Install any PWA that uses `"display": "fullscreen"` or `"display": "standalone"` in its [manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest/display) (for these screenshots, I'm using https://davidsekar.github.io/pwa-sample/)
3. Open the PWA

### Expected behavior

The PWA should use the entire screen (except for Android UI elements, if `"standalone"`).

### Actual behavior

The PWA shows an empty space at the top in the area where the toolbar would appear in Fenix. (Below the status bar, if one is visible, and above the actual app content.)

Here is a table of screenshots (only the top-right is unexpected):

<table>
<thead>
<tr><th>Toolbar position</th><th>In Fenix</th><th>As PWA</th></tr>
</thead>
<tbody>
<tr><th>Top</th><td><a href="https://user-images.githubusercontent.com/1570964/121718485-5c81d700-cab0-11eb-8c22-6697927e9247.png"><img alt="Screenshot" height="256" src="https://user-images.githubusercontent.com/1570964/121718485-5c81d700-cab0-11eb-8c22-6697927e9247.png"/></a></td><td><a href="https://user-images.githubusercontent.com/1570964/121718510-60adf480-cab0-11eb-908a-26cd9c087108.png"><img alt="Screenshot" height="256" src="https://user-images.githubusercontent.com/1570964/121718510-60adf480-cab0-11eb-908a-26cd9c087108.png"/></a></td></tr>
<tr><th>Bottom</th><td><a href="https://user-images.githubusercontent.com/1570964/121718520-63104e80-cab0-11eb-918a-c74982e6297c.png"><img alt="Screenshot" height="256" src="https://user-images.githubusercontent.com/1570964/121718520-63104e80-cab0-11eb-918a-c74982e6297c.png"/></a></td><td><a href="https://user-images.githubusercontent.com/1570964/121718531-660b3f00-cab0-11eb-9956-c16fd8dab76f.png"><img alt="Screenshot" height="256" src="https://user-images.githubusercontent.com/1570964/121718531-660b3f00-cab0-11eb-9956-c16fd8dab76f.png"/></a></td></tr>
</tbody>
</table>

### Device information

* Device vendor / model and Android version: Amazon Fire (KFFOWI), Android 5.1.1
* Firefox for Android version: 89.1.1-armeabi-v7a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11005)

**Comment by SoftVision-LorandJanos** [comment]
Hi @rhendric  ! Thank you for your report! I was able to reproduce the issue described above.
Tested on the latest Nightly (91.0a1 Thursday 6/17 @ 7:33 AM).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by rhendric** [comment]
Get outta here, bot!

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly (2021-12-15).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by sh1ft-github** [comment]
I'm facing the same issue when disabling the hide on scroll feature in Fenix. Please issue a fix as it has stuck around for a long time by now.

**Comment by synthead** [comment]
Is there a timeline for fixing this issue?

**Comment by GithubUser96** [comment]
This is still an issue in the latest release of Firefox mobile. Apparently not a big deal since most people _“just use the toolbar on the bottom”_ which does not suffer this issue.

**Comment by synthead** [comment]
I don't have any interest in using the toolbar at the bottom.

This is a significant visual bug that has been open for almost two years. I'm surprised that this has gained so little traction 😐

**Comment by zimtsui** [comment]
Same problem on firefox 106.1.1.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807418

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
