### ISSUE TITLE
Give Back User Font Control on Web Pages in FireFox Android

### ISSUE THREAD

**Issue by esysfound** [mozilla-mobile/fenix#19985]
### What is the user problem or growth opportunity you want to see solved?
CREATE TOGGLE SWITCH IN SETTINGS TO ALLOW WEB PAGES TO USE SYSTEM FONT (FF Android)

On mobile phone, it is far easier to read sans serif fonts.  These even display for a second before a web page imposes its fonts.  FF Android used to allow (about:config) the user to choose between system or other font, or web font.  The switch is obviously still there - this could easily be incorporated into a simple Settings option.  This is a big deal-for me it affects both the legibility and loading speed of all web pages.  Rather than the limited, often wizzy add-ons now permitted, FF might focus on making pages legible and at least giving us the choice.  Either a settings change or allow an add-on (there are several) to manage this.  Not a problem in the desktop version;  only FF Android.  It has gotten so bad, I have switched to Kiwi as a browser which allows full customization.  But I would far prefer to use FF as it is more secure and would simplify synching.  Cannot understand why this is so difficult to tweak.  Thanks

### How do you know that this problem exists today? Why is this important?
DIRECTLY AFFECTS LEGIBILITY OF EVERY WEB PAGE

### Who will benefit from it?
EVERYONE

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11017)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813658

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
