### ISSUE TITLE
"Jump back in": website icon should have the same border radius as the top sites icons

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#19989]
For a better consistency I suggest to use the same border radius for the website icon in the "Jump back in" section as for the top site icons.

![Screenshot_20210613-105511](https://user-images.githubusercontent.com/1100614/121801350-2ae74800-cc37-11eb-9230-0328f72d06a3.png)

**Comment by amedyne** [comment]
@topotropic some more recommendations here.

**Comment by topotropic** [comment]
Yes! Thanks for filing.

Please use the same border radius for favicons here.
