### ISSUE TITLE
[Bug] "Jump back in": website icon is missing after launching to home screen or closing a tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#19988]
### Steps to reproduce

0. Prerequisite: Settings > Tabs > Start on home: Always
1. Remove Firefox from your Android recent apps
2. Start Firefox

alternative steps to reproduce:

1. open tabs tray
2. close a tab
3. close the tabs tray

### Expected behavior

The tab in the ""Jump back in" section has a website icon.

### Actual behavior

No website icon, only a large gap.

![Screenshot_20210613-105456](https://user-images.githubusercontent.com/1100614/121801168-36863f00-cc36-11eb-9b30-7b0405fd92ee.jpg)

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: master branch revision cc6bbcdf9c806bd9b049dea165821a5bbd59ef05

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/18 Nightly build with Google Pixel (Android 10), and Xiaomi mi4i (Android 5.0.2).
