### ISSUE TITLE
[Bug] "show all" button on home screen breaks having keyboard active

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#19992]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- in Firefox Nightly, press the home button and open keyboard, for example by pressing address bar
- press "show all"
### Expected behavior
user can still explore interface and test this newly implemented button, which normally opens tab list
### Actual behavior
not working while keyboard is active. only working while keyboard is inactive. user might become convinced that this button does nothing for them.
### Device information

* Device vendor / model and Android version: android 11 with openboard as ime 
* Firefox for Android version: nightly 06-12

**Comment by SoftVision-LorandJanos** [comment]
Hi @marcel263 ! Thank you for your report! I was able to reproduce the issue you described.
Tested on the latest Nightly (Monday 6/14 @ 5:07 AM)
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by VitalyVPinchuk** [comment]
Hi @SoftVision-LorandJanos @gabrielluong 
Can I try to fix it?

**Comment by gabrielluong** [comment]
> Hi @SoftVision-LorandJanos @gabrielluong
> Can I try to fix it?

Absolutely, go for it!

**Comment by marcel263** [comment]
appears like it has been fixed
