### ISSUE TITLE
Show in the history whether the URL is saved as a bookmark or not

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#19995]
Concerns the History

**Current situation:**
In the history I can't see if the single URL is already bookmarked.

However, this would be an advantage if I check my history for potential bookmarks afterwards, before I delete individual pages or the entire history.

It saves having to call up each desired page again to see whether a bookmark has already been created for page X.

**Suggested solution:**
Show in the history if a web address is already saved.
Combine the display with the possibility to create, change and delete bookmarks (i.e. access to the existing bookmark dialog).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11026)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812705

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
