### ISSUE TITLE
Keep "Home Button" visible on "New Tab Page", pressing it again will take the user back to the previous tab (i.e. close "New Tab Page")

### ISSUE THREAD

**Issue by R0M4N0F5K7** [mozilla-mobile/fenix#19994]
I'm sorry for this long post, but I see a lot of confusion here by people (e.g. #19926 or #19930) because the "home button" does not really work like a "home button" because it just switches to the "new tab page" which behaves differently than in any other browser as far as I know, but this seems to be overlooked by everyone discussing the home button here. Personally I always assumed this is for security or performance: **_Accessing the new tab page in fenix does not actually open a new tab but is isolated from all open tabs, only when you call a page from new tab it loads that page in a new tab._** Because of that, switching to it and especially back to open tabs from the new tab page (pressing back will close the app instead of taking you back to the previous homepage/tab) is a bit clumsy if you are used to it's usual behaviour of 'new tab page = landing page of a newly opened tab'.

Because of that special behavior I feel like making it a "home button" is indeed a bit confusing here and making a "firefox button"/"new tab page" button in a different design (see e.g. vivaldi's home button design) that takes you to the new tab page would make more sense (again, home buttons usually call the homepage in the current tab, but fenix' "home page" is isolated from all tabs). But no matter the design of the button, I think **_because of how the home page/new tab page works in fenix, the home button should stay present in the new tab bar (consistent design) and pressing it again from the address bar while being on the new tab page would close the new tab page again (i.e. take you back to the open tab you came from)_**. I see that closing the new tab page to return to the last opened tab was now addressed with adding the "jump back in" section on the new tab screen, which disrupts the new tab layout and seems like a super inelegant solution compared to just having one button in the address bar (currently the "home button") that calls (first click) the new tab page and closes is again.

(Personally I remember that the main argument for not adding a home button was that it would take up extra space, so just having one button (like the already existing tab overview button) to get to the new tab page/home page by long press (the current pop up options on long press of that button are completely redundant anyway, as they are also directly call-able with after a short press instead of a long press on the tab overview button) would have been the easiest solution for one-click-access of the home page without extra clutter, but this might be considered too unintuitive for new users.)

I wanted to point this out because I feel like this unique behaviour of the new tab page in fenix needs special considered in all areas where it the home page is called as it doesn't integrate with open tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11025)

**Comment by azerto11** [comment]
See #19886 and https://github.com/mozilla-mobile/fenix/issues/19987#issuecomment-860288478
> Personally I remember that the main argument for not adding a home button was that it would take up extra space

**Comment by azerto11** [comment]
> I remember that the main argument for not adding a home button was that it would take up extra space

See #19886 and https://github.com/mozilla-mobile/fenix/issues/19987#issuecomment-860288478

**Comment by amedyne** [comment]
@R0M4N0F5K7 Thank you for your feedback. The changes you have seen recently for Fenix are constantly being iterated on. Tagging our UX and product teams to take this input into consideration. @topotropic and @vesta0 FYI.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809834

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
