### ISSUE TITLE
Open selected text as link from text selection context menu

### ISSUE THREAD

**Issue by pavi2410** [mozilla-mobile/fenix#19990]
## User Story
- As a user, I want to open selected text as a link so I can visit the page via the link in a new tab without having to manually copy-pasting it.

## Dependencies
- List dependencies on other issues/teams etc.
-- None.

### Acceptance Criteria
- I can click on a text selection context menu option to open the selected text as a link in a new tab.

---

### Long Story
Often times I come across websites that do not use <a> tags for links (user-generated content, usually). In order to open the link, I have to select and copy the text and open a new tab. Firefox detects that the text in clipboard is a link and allows me to open the link. However, this is cumbersome. I am expecting a text selection context menu option to directly open a new tab if the selected text is a link.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11021)

**Comment by SoftVision-LorandJanos** [comment]
Hi @pavi2410 ! Thank you for your report! I can confirm that after a search for some non-linked websites in text, they don't give the user the option to open it in a new tab after selecting.
Tested on the latest Nightly (91.0a1 2021-06-30T05:09:53.235).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly (2021-12-28).
Tested with: Xiaomi Mi11 Lite (Android 11).

**Comment by jackyzy823** [comment]
FYI

The first problem which blocks (or annoys?) this feature is that after your long press , the text selection is restrict to chars between dot. (this behavior may be decided by geckoview and something more deeply).

so you have to manually expand the text selection to wrap up the full URL.

![Screenshot_20220508_180239](https://user-images.githubusercontent.com/2900871/167292026-4b7a6e69-8dbb-4248-9ea5-20b79fa45266.jpg)

Then some new code to display "open link w/o private" option  should  be implemented in https://github.com/mozilla-mobile/android-components/blob/main/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/DefaultSelectionActionDelegate.kt

**Comment by SoftVision-LorandJanos** [comment]
The behavior is still the same on the latest Nightly 110.0a1 (2022-12-13) build.
Device used: Google Pixel 4 (Android 13).
Reopening the ticket.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813747

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
