### ISSUE TITLE
When using "swipe toolbar sideways to switch tabs" navigation: Call and swipe into home page when swiping past last or before first open tab

### ISSUE THREAD

**Issue by R0M4N0F5K7** [mozilla-mobile/fenix#19996]
Extension of #19994 (considering home page being better integrated and accessible via open tabs and vice versa):

Personally I use the "swipe toolbar sideways to switch tabs" navigation (thanks for introducing me to this very convenient feature Mozilla) and it totally breaks my workflow that I can neither just swipe onto the new tab page but especially NOT OUT OF IT (swiping the address bar here doesn't do anything which doesn't feel right).

Walk-through:
Current "swipe toolbar sideways to switch tabs" lets you only swipe from the first to the last open tab and back.
First oversight/bug: When I call the homepage/new tab page swiping the address bar does nothing (this is due to how the new tab page in fenix is not a tab itself, as discussed in #19994)
Some mobile browsers circle the tabs after one reached the end; i.e. when swiping past the last open tab the user arrives at the first tab again.
Desired behaviour/flow: When swiping past the last or before the first open tab one gets to the new tab page / home page. When swiping past the new tab page one gets to the first tab again, swiping to the other side gets you to the last open tab.

The "circle all all tabs endlessly"-behaviour is already an option in some mobile browsers.
The "swipe into home page when swiping past open tabs"-behaviour is afaik present in the new safari with emphasis on fluent swipe navigation. (swiping the bar up would call the open tab overview page btw)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11027)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812874

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
