### ISSUE TITLE
FNX-5388 ⁃ We have a functioning URL bar with autocomplete based on your history

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#20]

**Comment by sblatz** [comment]
I believe this is a mockup of what this ticket is referencing

<img width="366" alt="screen shot 2019-01-28 at 11 39 22 am" src="https://user-images.githubusercontent.com/4400286/51861600-8415e180-22f1-11e9-8ea5-a53bc57b3623.png">

**Comment by bbinto** [comment]
@sblatz - let me know if you want to use this as a breakdown issue of the History Meta as it's one of the acceptance criteria. If not, please close.
