### ISSUE TITLE
FNX-5390 ⁃ [Bug] Every time I open settings, "LeakCanary" is momentarily listed at the bottom

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#2000]
## Steps to reproduce
1. Open settings
1. Carefully watch the bottom of your screen as the Settings screen appears.

### Expected behavior
The settings options should be consistent

### Actual behavior
(1) When the settings screen appears, there's a mysterious option at the very bottom (below "Data choices"

```
 (i)  LeakCanary                [o--]
```

(2) After a fraction of a second, the "LeakCanary" entry fades into nothingness
(3) After it's faded away, "Developer tools" slides in from the bottom.

### Device information
* Android device: Pixel 3, running Android Q (beta)
* Fenix version: "Firefox Preview" 1.0.1917 built Wednesday 4/24 at 12:16 PM

**Comment by dholbert** [comment]
Here's a screenshot of the settings menu as it initially appears (with the mysterious "LeakCanary" entry visible at the bottom):
![vlcsnap-2019-04-24-13h20m36s253](https://user-images.githubusercontent.com/426803/56691095-e5044a00-6693-11e9-96c1-fc3ca43e56dd.png)

**Comment by dholbert** [comment]
Here's a screencast of the full "opening settings" experience that I see (demonstrating both this bug at the bottom and #2002 at the top): https://www.dropbox.com/s/hi0la96m9dwkctw/fenix-settings-screen.mp4?dl=0

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/2 build. Not showing leakCanary on nightly builds.
