### ISSUE TITLE
[Bug] Linked page not loading followed by hosting page not responding to taps/clicks

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#20001]
Steps to reproduce

1. Open link in browser (used https://thenewstack.io/where-to-turn-for-a-centos-replacement-heres-5-solid-linux-distros-to-check-out/)

2. Click a link on loaded page (clicked link labelled TuxCare, i.e., https://tuxcare.com/linux-support-services/almalinux-support/)

Expected link to load but instead Firefox just sat there displaying a blank page with the address bar showing about:config. I tried refreshing but then tapped back when I realised the page would not load. This is where things went weird as I was taken back to the starting page and the link I had tapped showed it had been followed, all as expected, but taps no longer worked. Long-taps worked, i.e., I could highlight text and display the pop-up edit menu, but I could not tap off the menu to close it, I had to use the back button to close the pop-up.

I closed the page and reopen it before it would function as expected, that is, I could follow the link and display the page I had wanted to view in the first place. I could also navigate back and continue using the original page as expected.

Note: I have had this issue occur once before this in the recent past. Then I just put it down to some random event, but now that it had happened again, I suspect there is something more fundamental at play. And yes, trying to reproduce this issue will be tricky as I suspect it comes down to precise timings.

Firefox: Nightly 91.0a1 (Build #2015815947)
AC: 91.0.20210611143123, 143ffac776
GV: 91.0a1-20210608091819
AS: 78.0.0

Device: Note 10 on Android 10

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Preview RC 89.1.1 and Nightly 6/14, but was unable to. @mrandreastoth Could you please upload a short video illustrating the issue?

### Devices used:
- Samsung Galaxy S8 (Android 9)
- OnePlus 6T (Android 9)

**Comment by mrandreastoth** [comment]
> I tried to reproduce the issue on Firefox Preview RC 89.1.1 and Nightly 6/14, but was unable to. @mrandreastoth Could you please upload a short video illustrating the issue?
> ### Devices used:
> 
>     * Samsung Galaxy S8 (Android 9)
> 
>     * OnePlus 6T (Android 9)

Cannot reproduce.

Firefox Nightly 91.0a1 (Build #2015819595.
