### ISSUE TITLE
[TabsTray] Multiselect title should not be selectable by a11y services when not in select mode.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#20007]
## Steps to reproduce

Turn on accessibility mode.
Open the tabs tray.

### Expected behavior
Multiselect title should not be selectable.

### Actual behavior
Multiselect title is selectable, without action assigned, and read as "unlabelled".

### Device information

* Device vendor / model and Android version:  All
* Firefox for Android version: ? latest master

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 6/17 in both normal and private browsing.

### Devices used:
- Google Pixel 3XL (Android 9)
- OnePlus 6T (Android 9)
