### ISSUE TITLE
[Bug] Share menu option does not work in CustomTabs

### ISSUE THREAD

**Issue by philip-khor** [mozilla-mobile/fenix#20011]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open link in Custom Tab
2. Click on Share via ... 

### Expected behavior
Share menu appears 
### Actual behavior
Share menu does not appear. 

https://user-images.githubusercontent.com/35039795/121918707-e65bc980-cd68-11eb-9213-721f70ae013a.mp4

### Device information

* Device vendor / model and Android version: ?
POCO X3 NFC, Android 11
* Firefox for Android version: ? (go to Settings -> About Firefox)
91.0a1 (Build #2015815947)

**Comment by SoftVision-LorandJanos** [comment]
Hi @philip-khor  ! Thank you for your report! I wasn't able to reproduce the issue described above. The sharing function works as expected here. I've tested on the latest Nightly (91.0a1 Thursday 6/17 @ 7:33 AM).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).
Could you please check on the latest nightly, and if it still reproduces, could you give me some link examples you've tried with? Thank you!

**Comment by philip-khor** [comment]
Hi @SoftVision-LorandJanos, the share function seems to work after I enable the 'Display pop-up windows while running in the background option' for Twitter. Not sure if this can be exposed to the user better, but in any case feel free to close this issue.

**Comment by SoftVision-LorandJanos** [comment]
@philip-khor, if you come across this issue again, or any other, feel free to log again with as much details as you can provide with. I will close this one. Thanks again!
