### ISSUE TITLE
Option for Cascading Tabs Layout

### ISSUE THREAD

**Issue by Devil-criminal** [mozilla-mobile/fenix#20018]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved? 
We want the option to have cascading tabs Layout on mobile like they used to have on chromium based browsers

### How do you know that this problem exists today? Why is this important? 
There is a huge community outrage that google chrome forced end users to use grid view along with tab groups. This is evident even by looking at the most recent reviews of on google play and social media forums .
Unfortunately there are no suitable alternatives. Not from a trusted developer atleast. 

### Who will benefit from it? 
I believe a really large number of end users who are accustomed to browsing on the vertical cascading tab layout on mobile will benefit from it. 
We really hope to see this feature soon. It will definately bring a lot of users to firefox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11039)

**Comment by gitpubber** [comment]
Please implement this. I too want this feature

**Comment by gitpubber** [comment]
@amedyne please try to implement this as soon as possible. i know that the mozilla wants more people to use firefox. this is excellent opportunity which may not be available again. 

so,please implement this feature.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812873

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
