### ISSUE TITLE
[Bug] Security Key FIDO U2F doesn't work 

### ISSUE THREAD

**Issue by JoGarWeb** [mozilla-mobile/fenix#20023]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Sign in to any account with security key as 2FA in Firefox Stable Release and Beta Release. 
2. Try to use the key

### Expected behavior
Firefox should be able to open the settings to connect a security key to the Android phone. After that the website logs in. It only works in the Nightly version.

![Screenshot_20210615-003938](https://user-images.githubusercontent.com/7904563/122000048-d5648580-cd73-11eb-81c3-f7e0a5c2d0c8.png)

![Screenshot_20210615-004626](https://user-images.githubusercontent.com/7904563/122000071-dd242a00-cd73-11eb-8193-e1adf94487b5.png)

![Screenshot_20210615-004804](https://user-images.githubusercontent.com/7904563/122000095-e4e3ce80-cd73-11eb-8713-68c6ff3bcca3.png)

![Screenshot_20210615-004811](https://user-images.githubusercontent.com/7904563/122000150-faf18f00-cd73-11eb-980d-bac7e5718b0d.png)

### Actual behavior
Firefox Beta and Stable doesn't open the settings to connect the security key to the Android phone. On any website mark an error. 

![Screenshot_20210615-003929](https://user-images.githubusercontent.com/7904563/122000124-ef05cd00-cd73-11eb-9034-88351014ea47.png)

![Screenshot_20210615-004857](https://user-images.githubusercontent.com/7904563/122000141-f62cdb00-cd73-11eb-8d78-f9bfda5d39ac.png)

### Device information

* Device vendor / model and Android version: Nokia 5.3 Android 10 
* Firefox for Android version: 89.1.1 Build #2015812947 and 90.0.0-beta.3 Build #2015815723

**Comment by dveditz** [comment]
This is a duplicate of issue #19785

**Comment by eliserichards** [comment]
@jonalmeida 👆

**Comment by jonalmeida** [comment]
Correct, this is a duplicate.

> This is a duplicate of issue #19785

**Comment by jonalmeida** [comment]
I'm not sure how you were able to walk through the process of getting to the security prompt on Github using Beta/Release. Our feature flags have disabled the interaction between web content so it shouldn't prompt you for your key (even when setup).

I can see this behaviour working as expected on my device with the latest beta.
