### ISSUE TITLE
FNX-5391 ⁃ [Bug] Shortly after I open settings, "Basics" (and everything below it) slides a few pixels downwards

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#2002]
## Steps to reproduce
1. Open settings

### Expected behavior
Consistent layout, UI that doesn't move around unexpectedly.

### Actual behavior
After a short delay (maybe 1/4 second), the heading "Basics" (and everything after it) animate downwards by a handful of pixels (moving something like ~5% of my viewport height -- not extreme, but also noticeable and more than just a rounding error).

### Device information
* Android device: Pixel 3, running Android Q (beta)
* Fenix version:  "Firefox Preview" 1.0.1917 built Wednesday 4/24 at 12:16 PM

**Comment by dholbert** [comment]
This might be related to #2000 -- I'm not sure. (They happen at the same time, but I don't know if they have the same root cause.)

Here's a screencast of the bug: https://www.dropbox.com/s/hi0la96m9dwkctw/fenix-settings-screen.mp4?dl=0

**Comment by kbrosnan** [comment]
@dholbert is this still an issue with #2000 fixed?

**Comment by dholbert** [comment]
Yes, still an issue.

**Comment by dholbert** [comment]
I suspect it might be associated with the Firefox Account section populating itself with my username & email, and getting very slightly taller as a result.

**Comment by vesta0** [comment]
I believe this is fixed.

**Comment by softvision-miralobontiu** [comment]
This is fixed on the latest Nightly build ((#11840608).
Verified with Google Pixel (Android Q), Google Pixel 3 (Android 9), Samsung Galaxy S8 (Android 9).
