### ISSUE TITLE
[Bug] Top sites don't update correctly when editing

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#20034]
https://user-images.githubusercontent.com/107992/122078695-65312080-cdc2-11eb-8eed-72c4b57b3a61.mp4

## Steps to reproduce

1. Delete a site from top sites
2. Observe how top site names and favicons don't match
3. Tap on a top site and navigate to the wrong website
4. Return to homescreen and see that the top sites have updated and are now correct

### Expected behavior
Top sites update correctly (favicon and title match) when removing a site

### Device information
Samsung Galaxy S9
Android 10
Firefox 91.0a1 (Build #2015816355)

**Comment by codrut-topliceanu** [comment]
This should be fixed by https://github.com/mozilla-mobile/fenix/pull/20005 when it lands.

**Comment by csadilek** [comment]
@codrut-topliceanu hey, this should be fixed now, right? Is it ready for QA?

**Comment by codrut-topliceanu** [comment]
@csadilek Yes this should be testable now for QA.
Though the problem with flashing topSites will be fixed when https://github.com/mozilla-mobile/fenix/pull/20189 lands.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-07-14.
### Device used:
- Samsung Galaxy S9 (Android 8.0.0)
