### ISSUE TITLE
Clean up the different navigation functions in NavController

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#20039]
> Is there any particular reason why we are replacing `navigateSafe()` by `nav()`.
> 
_Originally posted by @Amejia481 in https://github.com/mozilla-mobile/fenix/pull/20038#discussion_r652112466_

If you examine closely at the various navigation functions in `NavController` https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/ext/NavController.kt, you will see most of them do the same thing, but we have many ways of calling them. 

One example is `navigateSafe()` is almost identical to `nav()` in terms of its calls. We should investigate this and see if we can simplify everything

**Comment by VitalyVPinchuk** [comment]
Hello @gabrielluong 
Could I try to refactor it?
