### ISSUE TITLE
[Bug] In Settings -> Accessibility -> Font Size, the values are incorrect for screen reader users

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#20033]
## Steps to reproduce

Enable TalkBack.
Navigate to the Accessibility Settings and turn off Automatic Font Sizing
Focus on the Font Size slider control and listen for the initial value.
Change the value.

### Expected behavior

TalkBack should announce 100% as the initial value and 50% as the minimum value and 200% as the maximum value.

### Actual behavior

TalkBack announces as if the scale was 0% to 100% instead of 50% to 200%

### Device information

* Device vendor / model and Android version: Android 9, Android 10. 
* Firefox for Android version: ? (go to Settings -> About Firefox) latest master
 
Note: This was previously fixed in https://github.com/mozilla-mobile/fenix/pull/11818, but it seems Talkback latest updates broke that implementation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11048)

**Comment by eliserichards** [comment]
This might be a good bug to work on @neha-b2001 🎉
