### ISSUE TITLE
FNX-5392 ⁃ [Bug] Vanishing quick action bar icons

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#2004]
## Steps to reproduce
1. Open app
1. Open web page
1. Swipe up to view quick action bar
1. Select three dot menu
1. Open Settings
1. Use Android < icon to close Setting icon and return to browsing

### Expected behavior
Quick action bar icons at stage 3 remain visible at stage 6

### Actual behavior
Quick action bar icons at stage 3 are not visible at stage 6

(Tested on both default and dark themes)

### Device information
Android device: Moto E5, Android 8.0.0
Fenix version: 1.0.1917 (Build #11141216 GV 68.0a1-20190422094240)

**Comment by kbrosnan** [comment]
Verified Galaxy S6 and Pixel 3.
