### ISSUE TITLE
I thought maybe I could just leave this here since I don't know what else to do with it.

### ISSUE THREAD

**Issue by DontTheyNeedYourhelp** [mozilla-mobile/fenix#20041]
<h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="app-basics-title">Application Basics</h2>

      
Name | Firefox
-- | --
89.0
20210527174632
&nbsp;
Mozilla/5.0 (Android 11; Mobile; rv:89.0) Gecko/89.0 Firefox/89.0
Linux 30 #1 SMP PREEMPT Wed Apr 14 16:17:01 +07 2021
0/0
0/0               Disabled by default
1
Found
Found
Found
false

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" id="crashes-title" data-l10n-id="report-crash-for-days" data-l10n-args="{&quot;days&quot;:3}">Crash Reports for the Last 3 Days</h2>

      
Report ID | Submitted
-- | --

      
      

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="features-title">Nightly Features</h2>

      
Name | Version | ID
-- | -- | --

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="processes-title" id="remote-processes">Remote Processes</h2>

      
Type | Count
-- | --
Web Content | 1 / 1

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="support-addons-title">Add-ons</h2>

      
Name | Type | Version | Enabled | ID
-- | -- | -- | -- | --
Google Search Fixer | extension | 1.6 | true | {58c32ac4-0d6c-4d6f-ae2c-96aaf8ffcb66}
Mozilla Android Components - Ads | extension | 75.0.22.0528020506 | true | ads@mozac.org
Mozilla Android Components - Browser Icons | extension | 75.0.22.0527234221 | true | icons@mozac.org
Mozilla Android Components - Cookies | extension | 75.0.22.0528020506 | true | cookies@mozac.org
Mozilla Android Components - Firefox Accounts WebChannel | extension | 75.0.22.0527234112 | true | fxa@mozac.org
Mozilla Android Components - ReaderView | extension | 75.0.22.0527234242 | true | readerview@mozac.org
Mozilla Android Components - Web Compatibility Interventions | extension | 22.0.0 | true | webcompat@mozilla.org
uBlock Origin | extension | 1.35.2 | true | uBlock0@raymondhill.net

      

      

      

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="graphics-title">Graphics</h2>

      
Features
--
WebRender
touch input enabled; autoscroll enabled; smooth pinch-zoom enabled
EGL_VENDOR: Android EGL_VERSION: 1.4 Android META-EGL EGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_IMG_context_priority EGL_KHR_no_config_context  IsWebglOutOfProcessEnabled: 0
ARM -- Mali-G52 MC2
OpenGL ES 3.2 v1.r26p0-01eac0.035aefc9426b37ec2259de8e3dc4e984
GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic GL_ARM_texture_unnormalized_coordinates
ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_float_blend EXT_sRGB EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context
EGL_VENDOR: Android EGL_VERSION: 1.4 Android META-EGL EGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_IMG_context_priority EGL_KHR_no_config_context  IsWebglOutOfProcessEnabled: 0
ARM -- Mali-G52 MC2
OpenGL ES 3.2 v1.r26p0-01eac0.035aefc9426b37ec2259de8e3dc4e984
GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic GL_ARM_texture_unnormalized_coordinates
EXT_color_buffer_float EXT_float_blend EXT_texture_filter_anisotropic MOZ_debug OVR_multiview2 WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context
true
true
60

Yes
Model: SM-A315G, Product: a31nndx, Manufacturer: samsung, Hardware: mt6768, OpenGL: ARM -- Mali-G52 MC2 -- OpenGL ES 3.2 v1.r26p0-01eac0.035aefc9426b37ec2259de8e3dc4e984
ARM
Mali-G52 MC2
OpenGL ES 3.2 v1.r26p0-01eac0.035aefc9426b37ec2259de8e3dc4e984
0

skia
skia
none
Empty profile data
1080x2400
1
512
512

available by defaultforce_enabled by user: Force-enabled by pref | available by default | force_enabled by user: Force-enabled by pref
available by default
force_enabled by user: Force-enabled by pref
available by defaultforce_enabled by user: Force-enabled by pref | available by default | force_enabled by user: Force-enabled by pref
available by default
force_enabled by user: Force-enabled by pref
available by default | available by default
available by default
available by default | available by default
available by default
disabled by default: Disabled by default | disabled by default: Disabled by default
disabled by default: Disabled by default
available by default | available by default
available by default
available by default | available by default
available by default
available by default | available by default
available by default
available by defaultunavailable by env: OS not supported | available by default | unavailable by env: OS not supported
available by default
unavailable by env: OS not supported
available by defaultdisabled by user: User disabled via prefunavailable by env: Requires Windows 10 or laterunavailable by runtime: Requires ANGLE | available by default | disabled by user: User disabled via pref | unavailable by env: Requires Windows 10 or later | unavailable by runtime: Requires ANGLE
available by default
disabled by user: User disabled via pref
unavailable by env: Requires Windows 10 or later
unavailable by runtime: Requires ANGLE
available by defaultdenied by env: Not on allowlist | available by default | denied by env: Not on allowlist
available by default
denied by env: Not on allowlist
disabled by default: Disabled by default | disabled by default: Disabled by default
disabled by default: Disabled by default
disabled by default: Disabled by defaultblocked by runtime: WebGPU can only be enabled in nightly | disabled by default: Disabled by default | blocked by runtime: WebGPU can only be enabled in nightly
disabled by default: Disabled by default
blocked by runtime: WebGPU can only be enabled in nightly

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="media-title">Media</h2>
      
Audio Backend | opensl
-- | --
2
48000
...

Default audio output device | &nbsp; | &nbsp; | Enabled | All | default: S16LE, support: S16LE S16BE F32LE F32BE | 2 | default: 44100, support: 44100 - 44100 | 128 - 441

Default audio input device | &nbsp; | &nbsp; | Enabled | All | default: S16LE, support: S16LE S16BE F32LE F32BE | 1 | default: 44100, support: 44100 - 44100 | 128 - 441

Enumerate database

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="environment-variables-title">Environment Variables</h2>

      

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="modified-key-prefs-title">Important Modified Preferences</h2>

      
extensions.lastAppVersion | 89.0
-- | --
idle.lastDailyNotification | 1623803881
media.gmp.storage.version.observed | 1
network.dns.disablePrefetch | true
network.http.speculative-parallel-limit | 0
network.predictor.enabled | false
network.prefetch-next | false
network.trr.blocklist_cleanup_done | true
privacy.purge_trackers.date_in_cookie_database | 0
privacy.purge_trackers.last_purge | 1623803883355
security.remote_settings.crlite_filters.checked | 1623768225
security.remote_settings.intermediates.checked | 1623768225
storage.vacuum.last.index | 0

      

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="locked-key-prefs-title">Important Locked Preferences</h2>

      
fission.autostart.session | false
-- | --

      
      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="a11y-title">Accessibility</h2>

      
Activated | false
-- | --
0

      
      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="library-version-title">Library Versions</h2>

      
&nbsp; | Expected minimum version | Version in use
-- | -- | --
NSPR | 4.30 | 4.30
NSS | 3.64 | 3.64
NSSSMIME | 3.64 | 3.64
NSSSSL | 3.64 | 3.64
NSSUTIL | 3.64 | 3.64

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="startup-cache-title">Startup Cache</h2>

      
Disk Cache Path | /data/user/0/org.mozilla.firefox/files/mozilla/ct1ukv5w.default/startupCache/startupCache.8.little
-- | --
false
true
false

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="intl-title">Internationalization &amp; Localization</h2>

      
Application Settings
--
["en-GB"]
["an","ar","ast","az","be","bg","bn","br","bs","ca","cak","cs","cy","da","de","dsb","el","en-CA","en-GB","en-US","eo","es-AR","es-CL","es-ES","es-MX","et","eu","fa","ff","fi","fr","fy-NL","ga-IE","gd","gl","gn","gu-IN","he","hi-IN","hr","hsb","hu","hy-AM","id","is","it","ja","ka","kab","kk","kn","ko","lij","lo","lt","lv","ml","mr","ms","my","nb-NO","ne-NP","nl","nn-NO","oc","pa-IN","pl","pt-BR","pt-PT","rm","ro","ru","sk","sl","son","sq","sr","sv-SE","ta","te","th","tr","trs","uk","ur","uz","vi","wo","xh","zam","zh-CN","zh-TW"]
["en-GB","en-US","en-CA"]
["en-GB"]
"en-US"

["en-GB"]
["en-GB"]

**Comment by eliserichards** [comment]
Closing as spam (?)
