### ISSUE TITLE
[Bug] Selected tabs number is not updated after close

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#20047]
## Steps to reproduce

1. Open multiple tabs.
2. Select some of them
3. Close selected
4. Select some more

### Expected behavior

Selected tabs number must be zero after closing selected tabs

### Actual behavior

Selected tabs number is not updated after close

### Device information

* Device vendor / model and Android version: OP3T LineageOS 18.1 / Android 11
* Firefox for Android version: ? 89.1.1 from GPlay
 

https://user-images.githubusercontent.com/14617699/122247422-ff32bf00-cecf-11eb-9d54-de8eddd52c45.mp4

**Comment by jonalmeida** [comment]
This bug is already fixed in 90+, if QA could verify that would be great. 🙂

**Comment by 532910** [comment]
Indeed, I should check it before on nightly.

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/18 Nightly build with Xiaomi mi4i (Android 5.0.2), and Google Pixel (Android 10).
