### ISSUE TITLE
[Bug] Dashlane autofill pop up is not consistent and reliable

### ISSUE THREAD

**Issue by Udayanithig** [mozilla-mobile/fenix#20052]
## Steps to reproduce

- Enable Autofill service, accessibility and display over the apps permisson for Dashlane
- Open Firefox and go to https://github.com/login or any website login page.

### Expected behavior
- The Autofill pop up should be consistent and reliable.

### Actual behavior
- Autofill pop up is not consistent and reliable sometimes it is flickering.

https://user-images.githubusercontent.com/76005728/122274923-bd6e3c80-cf00-11eb-9c41-2abfe2185036.mp4

### Device information

* Device vendor / model and Android version: Motorola One Fusion Plus & Android 10
* Firefox for Android version: 89.1.1 (Build #2015812947) & 90.0.0-beta.3 (Build #2015815723)

### Additional Information

-  The above mentioned issues are **not** presented on **Firefox Nightly**. 

https://user-images.githubusercontent.com/76005728/122276173-22766200-cf02-11eb-9bb9-301a0f55463d.mp4

**Comment by hakkikaancaliskan** [comment]
Same issue reported for bitwarden too and moved to bugzilla
https://github.com/mozilla-mobile/fenix/issues/19685

**Comment by jonalmeida** [comment]
This looks more like https://bugzilla.mozilla.org/show_bug.cgi?id=1693152 to me.

**Comment by jonalmeida** [comment]
> The above mentioned issues are **not** presented on **Firefox Nightly**.

Oops, didn't read this. Sounds like a no-op for us then. When nightly rides the trains and goes to release.

Thanks for filing!

**Comment by Udayanithig** [comment]
> > The above mentioned issues are **not** presented on **Firefox Nightly**.
> 
> Oops, didn't read this. Sounds like a no-op for us then. When nightly rides the trains and goes to release.
> 
> Thanks for filing

My concern is even in **February, March** builds for Nightly don't have this issue. By the time it should be fixed in 89.1.1 (Firefox Stable) and 90.0.0-beta.3. But in reality, it's **not fixed** to date.
