### ISSUE TITLE
[Bug] Recent tabs ("Jump back in") sometimes has an empty UI

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20054]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open a new tab.
2. Type in a website that is slow to load which gives you enough time to change screens before it loads (cnn.com).
3. Very quickly, before the page loads, go to the home screen.

### Expected behavior
- The title should appear eventually on the screen.

### Actual behavior
- You are left with a white card that never updates until you go back to the tab and come back again.

### Device information

* Device vendor / model and Android version: All devices.
* Firefox for Android version: Nightly 16/06/2021
 
https://user-images.githubusercontent.com/1370580/122277844-53c84100-ceb4-11eb-85cb-b4199b74a889.mp4

**Comment by lobontiumira** [comment]
Verified as fixed on the 6/22 Nightly 91.0a1 build with Google Pixel (Android 10), and Xiaomi mi4i (Android 5.0.2).
