### ISSUE TITLE
[webcontent] Text selection is not functioning correctly

### ISSUE THREAD

**Issue by KamiBruh72** [mozilla-mobile/fenix#20066]
## Site with issue and any steps to reproduce
Almost any site

### Expected behavior
The selection of the text should go smoothly without skipping half the page

### Actual behavior
Text selection skips half of the page and glitches out

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No, it doesn't

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No, I can't. It's the Firefox only issue

### Device information

* Android device: HMD Global Nokia 3.1 Plus
* Fenix version: 89.1.1 (Build #2015812947)

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Preview RC 89.1.1 and Nightly 6/17, but was unable to. @KamiBruh72  Could you please upload a short video illustrating the issue?

### Devices used:
- Samsung Galaxy S8 (Android 9)
- OnePlus 6T (Android 9)

**Comment by KamiBruh72** [comment]
https://user-images.githubusercontent.com/86050399/122635314-cff89980-d0eb-11eb-9d80-729825d3d59c.mp4
Here is a short video of this issue
