### ISSUE TITLE
Force Autofill Option 

### ISSUE THREAD

**Issue by Udayanithig** [mozilla-mobile/fenix#20065]
### What is the user problem or growth opportunity you want to see solved?

The current Firefox, don't give an option to force Autofill. This feature can be helpful when an autofill pop up fails to show up on the login page. 

### How do you know that this problem exists today? Why is this important?

Firefox currently doesn't adopt or support this feature. In Android, the **duckduckgo** and **firefox lite** browser has already implemented. It will also clear most of the autofill issues.

https://user-images.githubusercontent.com/76005728/122340040-66e41b00-cf5f-11eb-9195-19963cad82db.mp4

![Screenshot_20210617-114557.png](https://user-images.githubusercontent.com/76005728/122341883-998f1300-cf61-11eb-91e2-9902c8936725.png)

### Who will benefit from it?

The user who uses password manager can be benefitted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11061)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812439

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
