### ISSUE TITLE
Ads Issue

### ISSUE THREAD

**Issue by rafel2345** [mozilla-mobile/fenix#20063]
I am addicted of games, but some time we need to get rid from ads, that a website owner place on their article like see in this [traffic rider mod apk](https://multiapkclub.com/traffic-rider-mod-apk/) game.
Here is the issue is, Can Mozilla android browser provide some type of any feature, from that used we get rid from it.

**Comment by cadeyrn** [comment]
You can enable uBlock Origin in the add-ons sections of Firefox to get rid of ads.

**Comment by totalspotek** [comment]
same issue i have faced on this football website name [totalsportek.app](https://totalsportek.app/)
