### ISSUE TITLE
[Bug] Homescreen collections button cuts off text in Armenian

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#20081]
Set the language to Armenian, have 0 collections: 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/43795363/122473304-48921580-cf87-11eb-8284-4c3d39b8c42c.png">

### Device information

* Device vendor / model and Android version: Pixel 3
* Firefox for Android version: latest nightly

**Comment by eliserichards** [comment]
English (text on one line):
<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/122473620-bb02f580-cf87-11eb-81e0-4cbceb3bb4d4.png">

**Comment by lobontiumira** [comment]
The "Save tabs to collection" is missing entirely from the 6/18 Nightly build:

<img src="https://user-images.githubusercontent.com/40694158/122521975-1c75a380-d01e-11eb-84d0-979b58261e4a.png" width="300" height="550" />

@eliserichards should I file a new issue for this matter?
Removing the qa:needed label

**Comment by eliserichards** [comment]
Ahh! It looks like the button doesn't appear with 0 tabs... if I open a tab and then go back to Home it appears:

1. Open Nightly
2. Open a tab, www.wikipedia.org
3. Press the home button
4. THEN the button appears

I am checking an older build to see if this is intentional 🤔 it seems weird to me

**Comment by eliserichards** [comment]
It looks like this is the default behavior (i.e. not caused by my fix [yay!]), where the button doesn't appear with 0 tabs but appears once you open tabs. I am going to file a separate bug for that and check in with UX if that's intentional 🤔

<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/122792331-b0927580-d27f-11eb-8230-dbd6934451b3.png"> <img width="326" alt="image" src="https://user-images.githubusercontent.com/43795363/122795762-41b71b80-d283-11eb-9d74-36795843ab86.png">

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Nightly build with Xiaomi mi4i (Android 5.0.2), and Google Pixel (Android 10).

<img src="https://user-images.githubusercontent.com/40694158/122876110-c6667000-d33d-11eb-873d-5f45ee5cf37e.png" width="300" height="550" />
