### ISSUE TITLE
FNX-5393 ⁃ [Bug] Touching back while a video is playing in full screen makes the webpage goes back.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2008]
## Steps to reproduce
Go to YouTube (or Vimeo, etc)
Play a video in full screen
Touch the back button

### Expected behavior
The video leaves the full screen mode, but the page remains the same page. 

### Actual behavior
Firefox goes back to the previous previous page.

### Device information
* Android device: 8.0
* Fenix version: 10.1917

**Comment by ekager** [comment]
This should be fixed in tomorrow's nightly, fixed by https://github.com/mozilla-mobile/fenix/pull/1999

**Comment by Lululalu** [comment]
@ekager it was indeed fixed, so I will close the issue. Thanks.
