### ISSUE TITLE
enhanced privacy protection is not working

### ISSUE THREAD

**Issue by Rohit-codeboy** [mozilla-mobile/fenix#20089]
enhanced privacy protection is not working properly. it shows that it has blocked all the trackers but actually it doesn't. ghostery extension also blocks those trackers which should not be possible if firefox has already blocked it.

when i use the brave browser it blocks all the adds and trackers and those are not visible to ghostery extension because they are already blocked

**Comment by kbrosnan** [comment]
These work from different lists of trackers. It is not surprising that they block different elements. If you think something should be blocked that is not it should be reported to the Disconnect team https://github.com/disconnectme/disconnect-tracking-protection/issues
