### ISSUE TITLE
[Bug] Undo closed tab moves tab to top of list

### ISSUE THREAD

**Issue by herbert3000** [mozilla-mobile/fenix#20099]
## Steps to reproduce
have multiple tabs open
close an open tab 
UNDO the operation

### Expected behavior
tab should appear at same position where it was before it got closed

### Actual behavior
restored tab appears at top of list

### Device information
* Device vendor / model and Android version: Huawei P9 lite, Android 7.0
* Firefox for Android version: 89.1.1

**Comment by marcel263** [comment]
#10986

**Comment by eliserichards** [comment]
Thanks for linking to the original bug @marcel263! I'm going to close this in favor of #10986 👍
