### ISSUE TITLE
FNX-5394 ⁃ [Bug] The address bar is exhibited above the keyboard when typing in a text field.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2009]
## Steps to reproduce
Touch on a text field

### Expected behavior
The address bar is hidden, after all the user is not using it, they are writing something somewhere else. In this case the address bar is wasting screen space.

### Actual behavior
The address bar is exhibited above the keyboard. (Samsung Internet hiddens the bottom bar when typing, for example).

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917
![Screenshot](https://user-images.githubusercontent.com/32398857/56702797-5667eb00-66dc-11e9-9d84-f50016736521.jpg)UNITO-UNDERSCORE!20190424-214819!UNITO-UNDERSCORE!Firefox Preview!

**Comment by kbrosnan** [comment]
Fennec has the same behavior, though with a top address bar. Being able to see the address bar is a security feature.

**Comment by Lululalu** [comment]
@cpeterso There is another problem with an address bar that can be closed by scrolling. Some text fields already are scrollable, so, in these cases the address bar gets appearing and disappearing  all the time. Also, it has potential to cover important buttons on the website interface. One example is the DDG's feedback reporting tool. I made a video about it:

https://streamable.com/thfvn

**Comment by cpeterso** [comment]
> @cpeterso There is another problem with an address bar that can be closed by scrolling. Some text fields already are scrollable, so, in these cases the address bar gets appearing and disappearing all the time. Also, it has potential to cover important buttons on the website interface. One example is the DDG's feedback reporting tool. I made a video about it:

Interesting. The video demonstrating the problem is very helpful. That is definitely a bug! :) I think this is a Fenix bug because, AFAIK, Fenix controls the address bar scrolling, not GV.

**Comment by jonalmeida** [comment]
This is a Fenix bug in my testing, the top of the BrowserToolbar is changed dynamically and in some cases is not-reset back to the original. This can be consistently seen when using a Custom Tab.

**Comment by cpeterso** [comment]
For comparison, I tested mtggoldfish.com on Safari and Chrome/WebKit on iOS. Like Fenix, they both keep the keyboard open when you return to the browser if the mtggoldfish search field had input focus.

**Comment by vesta0** [comment]
Intended behaviour.
