### ISSUE TITLE
Increase height of Tab Slider when toolbar is on top

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#20091]
Current Behaviour:
![Screenshot_20210619-183832_Firefox_Nightly](https://user-images.githubusercontent.com/86104828/122643775-58e4f480-d12f-11eb-9e2f-f50a3d6d89c0.png)

Required Behaviour:
![Screenshot_20210619-183845_Firefox_Nightly](https://user-images.githubusercontent.com/86104828/122643782-65694d00-d12f-11eb-8f54-294f23991196.png)

So,when toolbar is on top, please increase Height of tab slider so that it is easily accessible.

**Comment by marcel263** [comment]
and likewise decrease when toolbar is on the bottom. buttons are hard to reach

**Comment by amedyne** [comment]
Tagging @topotropic for UX input.

**Comment by gitpubber** [comment]
@amedyne any update?
