### ISSUE TITLE
[Bug] Two finger scrolling on touchpad opens link dialog

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/fenix#20100]
## Steps to reproduce

* Open a page with many links, e.g., https://en.wikipedia.org/wiki/Firefox
* Scroll with 2 fingers on touch pad until the pointer end up resting on a link.
* Remove both fingers.
* Then use a single finger on the touch pad to move the pointer a little but leave it pointing at a link when you lift your finger.

### Expected behavior

Expectation is that the pointer simply is on the link but no clicking has occurred.

### Actual behavior

Unwanted click is generated.

### Device information

* Device vendor / model and Android version: Lenovo Chromebook Duet running Chrome OS 93.0.4543.0 (Android 9)
* Firefox for Android version: 91.0a1 (Build #2015817099)
 
Originally reported at https://github.com/mozilla-mobile/fenix/issues/3708#issuecomment-817533421 by @dchee2.  CC @makotokato.

**Comment by LittleAngelwings** [comment]
Same issue here with Lenovo Chromebook Flex 5i, CrOS 91.0.4472.114, Android 11.
Also my reported issue where I can create new collections, cause the enter key hasn't any function:
https://github.com/mozilla-mobile/fenix/issues/18560

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1717464

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
