### ISSUE TITLE
[Bug] Collections button doesn't show on Home with zero tabs

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#20106]
The collections button doesn't appear on the homescreen when you have zero tabs, but once you open a tab and go back to the homescreen it appears. Is this an intentional design choice, since there are no tabs open?

<img width="324" alt="image" src="https://user-images.githubusercontent.com/43795363/122792331-b0927580-d27f-11eb-8230-dbd6934451b3.png"> <img width="326" alt="image" src="https://user-images.githubusercontent.com/43795363/122795762-41b71b80-d283-11eb-9d74-36795843ab86.png">

_Originally posted by @eliserichards in https://github.com/mozilla-mobile/fenix/issues/20081#issuecomment-865174141_

**Comment by cadeyrn** [comment]
What should / could this button do if yo have no open tabs? The button opens the tabs multi select mode but you can't select anything if you don't have any tabs. And it's not possible to open a new tab in this mode.

**Comment by jonalmeida** [comment]
> The collections button doesn't appear on the homescreen when you have zero tabs, but once you open a tab and go back to the homescreen it appears. Is this an intentional design choice, since there are no tabs open?

Yes, this is intentional behaviour. If there are no tabs open, the 'Save tabs to collection' button would not have a list of tabs to add.

**Comment by amedyne** [comment]
Closing this since this is intentional behavior.
