### ISSUE TITLE
FNX-5396 ⁃ [Bug] The permission prompt (notification, location, etc) design is inconsistent with rest of the interface

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2010]
## Steps to reproduce
Go to a website that asks for permissions

### Expected behavior
A prompt is exhibited and its design is consistent with the rest of the Interface. Preferably at the boom, because it's easier to use with only one hand.

### Actual behavior
The prompt looks outdated. The font is too large, it doesn't look beautiful as the rest of the browser does.

## Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by AaronMT** [comment]
Permission string isn't even formatted to fit the display. 
![Screenshot (Apr 25, 2019 11_07_57 AM)](https://user-images.githubusercontent.com/102331/56746605-88179b00-674a-11e9-924e-40a5a34ab04a.png)

**Comment by Amejia481** [comment]
This will be addressed in this issue https://github.com/mozilla-mobile/android-components/issues/2489
