### ISSUE TITLE
[Bug] "Jump back in": too large letter spacing for page titles

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#20119]
### Steps to reproduce

1. make sure that you have at least one collection so that you can compare the "Jump back in" with the "Collections" section.

### Expected behavior

Regular letter spacing for the page title.

### Actual behavior

The font size is the same as for the page title in the (expanded) collections section. But the letter spacing is noticeable larger in the "Jump back in" section.

![Screenshot_20210621-215100](https://user-images.githubusercontent.com/1100614/122819936-5921f300-d2db-11eb-86a6-c023574d481f.jpg)

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: master branch revision 15df06b294018103f7ca4179925d2ffa7695ee52

**Comment by cadeyrn** [comment]
For better comparison:

![comparison](https://user-images.githubusercontent.com/1100614/122820413-dd747600-d2db-11eb-8605-12f696f09d3b.png)

**Comment by gabrielluong** [comment]
To my knowledge, this is actually intentional by design.

**Comment by SoftVision-LorandJanos** [comment]
Hi @cadeyrn ! As with #20117 I can reproduce this issue as well. This too looks like it's intended, according to the comment above. We will wait for UX feedback from UX regarding this.
Tested on the latest Nightly (91.0a1 Tuesday 6/22 @ 5:07 AM) and on Release 89.1.1 (Build #2015812947).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by amedyne** [comment]
@topotropic Need your feedback on this.

**Comment by topotropic** [comment]
Thanks for the feedback.
All page titles in "Jump back in", "Recently saved" and "Collections" should have the same size.

**Comment by cadeyrn** [comment]
The design changed, closing.
