### ISSUE TITLE
Provide gesture controls for the default media player

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2011]
### Why/User Benefit/User Problem
Users expect a good experience while watching videos and listening to audios. The current media player feels cluttered and outdated. You can't double tap to go back or go forward. You can't use gestures. The bar is too large with large icons. It's inconsistent with the rest of the interface, which is beautiful IMO. It doesn't feels good overall, it just feels like "it works, but nothing else".

### What / Requirements
Improvements to the media player.

### Acceptance Criteria (how do I know when I’m done?)
The user experience got better.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11085)

**Comment by lime124** [comment]
@vesta0 do we want to add this in while we look at the other media related tickets?

**Comment by vesta0** [comment]
@lime124 in order to contain the scope of our Q3 media work, let's leave ticket out for now and revisit later.

**Comment by NotWoods** [comment]
As far as I know, the video and audio players are in GeckoView. Adding label.

**Comment by anmol257** [comment]
**Playback speed, screen lock** & **gestures** etc can be considered for making the player more user friendly.
  Have a **_common video player_** for firefox irrespective of the native player on the website just like Samsung internet browser does. It's very convenient

**Comment by Mugurell** [comment]
Also related - https://github.com/mozilla-mobile/fenix/issues/1111
GV would need to add support for the new actions/gestures.
Waiting for @vesta0 to prioritize the UX effort first.

**Comment by vesta0** [comment]
We are going to look into this soon but the first priority is fixing top media bugs.

**Comment by Poopooracoocoo** [comment]
>GV would need to add support for the new actions/gestures.

I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1666667 but it got closed and was redirected to this issue. I've seen many issue get closed here and get directed to Bugzilla, so that feels wrong.

>Have a common video player for firefox irrespective of the native player on the website just like Samsung internet browser does. It's very convenient

This is the only reason I have Samsung Internet. There is an extension for Firefox that lets you play media in your own player, but it's an extension and it's Fenix, so it doesn't work that good.

**Comment by kelimuttu** [comment]
We received a comment about this recently on [Twitter](https://twitter.com/AzharuddinRaj/status/1483295018559619076).

**Comment by sheikh-azharuddin** [comment]
Any update?😭

**Comment by kelimuttu** [comment]
Another user reported about this issue recently, thinking that it was a bug: https://support.mozilla.org/en-US/questions/1396024

**Comment by j-sidd** [comment]
This is a popular request on Mozilla Connect. Here is the link: https://connect.mozilla.org/t5/ideas/advance-media-notification-in-firefox-android/idi-p/4876

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812847

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
