### ISSUE TITLE
Audit telemetry probes that doesn't have a glean annotation associated

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#20115]
The idea is to take a look a those probes and add the required glean annotations to them ([doc](https://docs.google.com/spreadsheets/d/1MG93qvZICmQ65IepOAikdhOYEc8fxjWZTiUY4oD9axk/edit#gid=0)).

Reference links:
 - https://mozilla.github.io/glean-annotations/contributing/metadata/
 - https://mozilla.github.io/glean-annotations/contributing/creating/
 - https://github.com/mozilla/glean-annotations/pull/44
 - https://gist.github.com/wlach/035255e31a0e8eb75f5d1c624ffcd7df

**Comment by jonalmeida** [comment]
We did this! 🙂
