### ISSUE TITLE
[Bug] "Jump back in" / "Collections": spacing issues

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#20118]
### Steps to reproduce

1. make sure that you have at least one collection

### Expected behavior

There should be more spacing above the "Collections" headline and less spacing below the "Collections" headlines so that…

a) … there is the same spacing below the "Jump in back" and below the "Collections" headline
b) … it's clear that the "Collections" headline belongs to the collections and not the section above.

### Actual behavior

Odd spacing:

![Screenshot_20210621-213522](https://user-images.githubusercontent.com/1100614/122819165-6094cc80-d2da-11eb-9cc9-61097e3eb920.jpg)

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: master branch revision 15df06b294018103f7ca4179925d2ffa7695ee52

**Comment by jonalmeida** [comment]
I'm going to combine this with https://github.com/mozilla-mobile/fenix/issues/20117 for now.
