### ISSUE TITLE
FNX-5397 ⁃ [Bug] BrowserToolbar looses scroll ability when opening private tab from context menu

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2012]
## Steps to reproduce
1. Open any site in a regular tab.
1. Click a link and open it in private browsing mode.
1. Switch to private browsing mode.
1. Attempt to scroll down the page.
1. Observe the browser toolbar.

### Expected behavior
* At 5, the toolbar should retain it's default behaviour of hiding when you scroll down a page.

### Actual behavior
* This behaviour no longer works.

### Device information
* Android device: Pixel 2 (Android 9)
* Fenix version: Nightly (24/04/19)

**Comment by ekager** [comment]
This should be fixed in tomorrow's Nightly by the fix for #1993
