### ISSUE TITLE
[Bug] Crash reporter dialog has no strings

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#20124]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Go to about:crashparent and check the crash report dialog
2. Tap the Close or Restart buttons.
### Expected behavior
The dialog has a message.
### Actual behavior
No strings for the dialog message and Restart app button.
Tapping Close or Restart does nothing,
### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9)
* Firefox for Android version: Nightly 6/21
 
![Screenshot_20210622-150836](https://user-images.githubusercontent.com/4037709/122924009-f594d580-d36d-11eb-9984-6ea538fc2e5b.png)

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 6/28 with Google Pixel 4 XL (11), Samsung Galaxy S10+ (10), Samsung Galaxy S7 (7).
