### ISSUE TITLE
[Bug] video is green and pink

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#20121]
This is an issue which was initially reported on https://github.com/webcompat/web-bugs/issues/75573
It is reproducible on Firefox Nightly 91 on Android, 
but not on Firefox Nightly 91 on macOS.

## Steps to reproduce
1. Go to https://noyb.eu/files/videos/cookie.mp4

### Expected behavior
Video plays

### Actual behavior
The video is garbled with pink and green squares.

### Device information

* Device vendor / model and Android version: Pixel 2
* Firefox for Android version: 91.0a1 Build 2015817683

**Comment by lobontiumira** [comment]
I can confim the issue on the 6/22 Nightly 90.0a1 build with Google Pixel (Android 10).

**Comment by marcel263** [comment]
![Uploading Screenshot_20210622-131110_Firefox Nightly.png…]()
The bottom half of the video is displayed as Vertical lines of pixels

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1717663

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
