### ISSUE TITLE
[Bug] fast forward with double tap doesn't on the fullscreen video

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#20133]
Initially reported on https://github.com/webcompat/web-bugs/issues/61319

## Steps to reproduce
1. Go to https://spankbang.com/3tcqu/video/pretty+girl+walking+big+sweater+puppies  (NSFW)
2. Put the video in fullscreen 
3. double tap to advance 10s

### Expected behavior

Advance 10s

### Actual behavior

Don't do anything, just showing the player UI

### Device information

* Device vendor / model and Android version:  Pixel 2 android 11
* Firefox for Android version: ? Firefox Nightly 91.0a1 reproducible on Firefox 84
 
They seem to be using a library which is interacting with touch events. 
https://github.com/webcompat/web-bugs/issues/61319#issuecomment-739655416

**Comment by Mugurell** [comment]
The app doesn't do anything special for this, seems like a GV feature/bug.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1717774

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
