### ISSUE TITLE
[Bug] HTML input validity messages are not displayed to users.

### ISSUE THREAD

**Issue by pocketninja** [mozilla-mobile/fenix#20136]
Howdy,

As far as I can tell `<input>`/etc validation messages are never displayed to users when `<form>`s are submitted.

It does appear to work in Firefox for desktop (MacOS).

`element.checkValidity()` returns `false`.
`element.validationMessage` has the correct message I would expect in the tooltip/bubble.
`element.reportValidity()` returns `false`, but no report UI is presented to the user.

## Steps to reproduce

1. Use the following HTML in a static HTML file
  ```
<form action="/" method="POST">
  <input type="text" required="required">
  <input type="submit">
</form>
```
2. Press the submit button

### Expected behavior

Expected a message like "Please fill out this field" to be displayed, and perhaps for field to be focused.

Screenshot from Firefox in MacOS:
![image](https://user-images.githubusercontent.com/88677/123051400-e92d7d00-d440-11eb-9ef3-5e98a3ec0028.png)

### Actual behavior

Form submission is blocked, no validity message is displayed, and field is not focused.

### Device information

* Google Pixel 4a 5G, Android 11
* Firefox for Android version: 89.1.1

**Comment by Mugurell** [comment]
I think we need GeckoView support for this.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1717776

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
