### ISSUE TITLE
Investigate  pushing AppOpsManagerCompat delay further down start up

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#20149]
Right now, AppOpsManagerCompat is triggered right on start when we call Firebase. If we could push AppOpsManagerCompat further  after GV starts could potentially improve Cold VIEW times.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16900)

**Comment by mcomella** [comment]
Triage: this delay is pretty long: we should identify why it's there and how to reduce it.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807326

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
