### ISSUE TITLE
Add Loop option to default video player

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#2014]
### Why/User Benefit/User Problem
Allows users to loop videos natively on Fenix default media/HTML5 player

### What / Requirements
Allows users to loop videos natively on Fenix default media/HTML5 player in the menu options when tap and holding on video player screen.

### Acceptance Criteria (how do I know when I’m done?)
When loop option is present and working from menu option similar to Firefox desktop

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11087)

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1669451

**Comment by kbrosnan** [comment]
Duplicate bz-1669451
