### ISSUE TITLE
support for user-agent switching addon

### ISSUE THREAD

**Issue by haraldj** [mozilla-mobile/fenix#20148]
Dear developers,

is there any timeline for readding addons for user-agent swichting to Firefox Daylight?

Kind regards
Harald Jenny

**Comment by kbrosnan** [comment]
We are not keeping issues open for individual extensions. You can use Firefox nightly and a custom extension list.https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by haraldj** [comment]
Dear Kevin Brosnan,

> We are not keeping issues open for individual extensions. You can use Firefox
> nightly and a custom extension list.https://blog.mozilla.org/addons/2020/09/29/
> expanded-extension-support-in-firefox-for-android-nightly/

thanks for the hint.

Kind regards
Harald Jenny
