### ISSUE TITLE
[Bug] Desktop site mode not reflected on back

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#20145]
## Steps to reproduce
1. Go to the following page: https://github.com/mrandreastoth/vmaf [optionally remain on the current page, i.e., that of this ticket]
2. Enable "Desktop site" in the three-dot menu of Firefox
3. Follow the link labelled "this link" (https://docs.google.com/forms/d/e/1FAIpQLSdJntNoBuucMSiYoK3SDWoY1QN0yiFAi5LyEXuOyXEWJbQBtQ/viewform?usp=sf_link) [if the optional step was used above, then simply follow the provided link]
4. Navigate back

### Expected behavior
The "Desktop site" mode remains enabled under Firefox's three-dot menu and the page renders accordingly without requiring a refresh.

### Actual behavior
The "Desktop site" mode remains enabled under Firefox's three-dot menu but the page renders in mobile mode. Note that refreshing the page renders it according to the current mode.

### Device information
Samsung Note 9
Android 10
Firefox Nightly 91.0a1 (Build #2015817867)

**Comment by SoftVision-LorandJanos** [comment]
Hi @mrandreastoth ! Thank you for your report! I've tried to reproduce it using your examples, then I used some other pages with the following result: On "back" action the "Desktop site" mode remains enabled. What I noticed happening is that it's zoomed in so it looks like it's mobile format. Please check if this happens to you as well. If yes, it's a different issue, if not, please make a video about it. Thank you!
Tested on the latest Nightly (91.0a1 2021-06-24T05:07:09.024).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by mrandreastoth** [comment]
Hmm, no, there's definitely an issue with Desktop mode... I was just viewing the O3DE GitHub repository, switched to Desktop mode, forked the repo, hit back, went to the main O3DE page to see what else there is, found the multiplayer example, and realised I was viewing in Mobile mode, so tried to switch to Desktop mode just to find that it already was. Then, when I tried switching out of Desktop mode, it didn't want to. See included video.

**Comment by mrandreastoth** [comment]
Note: Each time the dot-menu appears, I'm tapping the "Desktop site" switch.

https://user-images.githubusercontent.com/26897855/125445735-0a4cbce6-0444-4378-8fda-af489b9a026a.mp4

**Comment by mrandreastoth** [comment]
Things have gotten worse, not better, since I first reported this issue. Now the desktop mode remains showing but the page is definitely rendering in mobile mode. To make matters worse, no amount of toggling the desktop mode actually has it disable but remains locked showing it is in desktop mode while still rendering in mobile mode. Even refreshing the page has no effect.

**Comment by ArabAmerican** [comment]
I have a similar issue.

When I go on a site with Desktop Mode enabled and I switch to another app and then return to Firefox (so Firefox suspends and returns), it forgets that it was on desktop mode and loads the mobile site. It also has the desktop site "switch" turned on even though it's not working and it won't toggle until I close the app and reopen it.

The site I use is web.groupme.com

When logged in, if it notices that you're on mobile, it throws you to the app store.
