### ISSUE TITLE
[Bug] Firefox for Android release perma-crashing on startup as of this morning (SQLiteBlobTooBigException)

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#20140]
## Steps to reproduce

Start Firefox for Android. Or just wait until Firefox tries to start itself in the background.

### Expected behavior

It starts

### Actual behavior

It crashes immediately. The android and FF crash report dialogs both show up

### Device information

* Device vendor / model and Android version: Sony Xperia XZ1C with Android 9
* Firefox for Android version: ~~Can't see it because I can't open firefox. But the Play Store says my version was last updated Jun 1 and there's no newer version, so presumably it's whatever the latest release version is.~~ Crash report link (below) says it's 89.1.1.

I'm attaching logcat output showing stack traces and crash report id: [fxcrash.txt](https://github.com/mozilla-mobile/fenix/files/6703662/fxcrash.txt)

cc @kbrosnan 

Edited to add: here's the crash report link: https://crash-stats.mozilla.org/report/index/906e7dc5-cab9-4d51-a4af-df79f0210623

**Comment by amedyne** [comment]
@staktrace There is a fix that handles this crash and it is on Beta [90.0.10](https://github.com/mozilla-mobile/android-components/commit/199014501b62a397872d34f8166f9c876a196782).

**Comment by Amejia481** [comment]
The issue happens when trying to download a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), unfortunately the only workaround until the new fix arrives, it's to clear you application data.

**Comment by staktrace** [comment]
The crash popup was coming up too often while I was trying to do other things on my phone. I had to uninstall.

**Comment by staktrace** [comment]
I guess the fix has already landed in beta I'll close this out.
