### ISSUE TITLE
[Bug] The "home" icon from the toolbar is white on light theme

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#20154]
## Steps to reproduce
1. Make sure you have the light theme enabled.
2. Open a page and observe the "home" icon from the toolbar.

### Expected behavior
The "home" icon is visible when light theme is enabled.

### Actual behavior
The "home" icon is white on light theme, and barely visible - please see the screenshot below.

### Device information
* Devices: all
* Firefox for Android version: 6/24 Nightly build

![Screenshot_1](https://user-images.githubusercontent.com/40694158/123235046-3151ab80-d4e4-11eb-8b20-2a670bd30068.jpg)

**Comment by Mugurell** [comment]
@gabrielluong  this seems to be happening after https://github.com/mozilla-mobile/fenix/issues/19951.

**Comment by sheikh-azharuddin** [comment]
Also the report site issue bulb icon is not visible in white theme

**Comment by Mugurell** [comment]
> Also the report site issue bulb icon is not visible in white theme

Tracked in https://github.com/mozilla-mobile/fenix/issues/19558

**Comment by gabrielluong** [comment]
From https://github.com/mozilla-mobile/android-components/pull/10456#issuecomment-868549095

> > A question, related to: [mozilla-mobile/fenix#20154](https://github.com/mozilla-mobile/fenix/issues/20154).
> > In order to fix the issue, we could add a tint for the drawable in Fenix or add an option in `Button` for tint, or override `mozac_ui_icons_fill` in Fenix.
> > But my question is: do we need to have this resource in AC? It is not used in a custom component and it is kind of a design choice, not a library feature.
> 
> Ya, this is more of a design choice. Generally, if it's an icon that appears in our photon components library, I would just add them to ui-icon. I do this because since it's part of the design system, the odds that it could be used in RB or Focus are much higher.
> 
> Both solution you propose makes sense to me. I would probably just override `mozac_ui_icons_fill` for the time being to account for the fact that this tinting issue could happen again.

**Comment by Nickoriginal** [comment]
Fixed for me in Nightly 2021-07-01T17:41:24.496 (Samsung Galaxy A20s), however, in private mode "home" icon still have issues with color.
It becomes black on light theme:
![Screenshot_20210701-223328_Firefox Nightly](https://user-images.githubusercontent.com/85299944/124180537-01df0800-dabd-11eb-8935-4f86fa4327b6.jpg)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/5 with Samsung Note 10 (Android 11). I'll wait until the latest changes are landed and check the issue on private browsing, as well.

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20154#issuecomment-872502387
Fixed in **Nightly 91.0a1 2021-07-05T17:06:08.350**
<img src = https://user-images.githubusercontent.com/85299944/124509064-e8e69780-ddd9-11eb-826a-20490aa6690d.jpg width = 45%> <img src = https://user-images.githubusercontent.com/85299944/124509072-ee43e200-ddd9-11eb-920e-c3825133a017.jpg width = 45%>

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build. Devices:
- Samsung Note 10 (Android 11)
-  LG G7 Fit (Android 8.1)
- Pixel 3 (Android 12 Beta)
