### ISSUE TITLE
Add Search Provider to add option to launch Find in Page with search terms in Edit Toolbar

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#2015]
### Why/User Benefit/User Problem
The Fennec way of clicking menu, finding and clicking "Find in Page" option then searching for a word is harder than just tapping address bar and searching for a word.

### What / Requirements
Find/highlight text from page from address bar search. 

### Acceptance Criteria (how do I know when I’m done?)
Find/highlight text from page from address bar search showing how many words on page are found and highlight word when going through page. Safari has a decent UI of doing similar to this on i OS where the option is shown below all URL matches in its own "subsection".

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11088)

**Comment by cadeyrn** [comment]
To use the address bar for "Find in Page" does not make sense at all… You compare with Safari on iOS. In Safari you also have to press a button and then click on a "Find in Page" button. It's exactly the same with the exception that it's not a "menu button" but another button in Safari.

**Comment by sebast889** [comment]
I didn't say same as Safari, I said similar. This request is so once you search a word in address bar there is a way you can hard scroll down the page and see the words found highlighted without even needing to click an extra button. I don't know if this is possible without messing with normal address bar functions but if isn't let me know. 

Even with an extra button like the in Safari I would say it is still better than the current location of the menu, menu button and find search bar where users go from the the top right, to the center right to the bottom of the screen to find a word where in Safari's case everything is done from the address bar area at top and center of screen. I think it's still better even when Fenix moves around the address bar to the bottom but I'm open to hear if you think it's worse.

**Comment by yoasif** [comment]
I was curious to see how this worked in iOS Safari, as I have limited experience with it.

It is a pretty interesting feature that could be interesting for switchers from Safari.

See how it works: https://www.igeeksblog.com/how-to-search-within-a-website-in-safari-on-ios-7/

Basically, a user types a string into the address bar.

The results are separated by eg "Google Search" with results following, and then "On This Page (x matches) and the "result" of "Find "string". 

There is another feature in newer versions of iOS that use a button to call up the search box, which could be implemented in the quick actions bar. Either (or both) feature could be useful and interesting to add, imo.

**Comment by Lululalu** [comment]
I don't know how this works on Safari, because I don't own an iOS device, but on Samsung Internet you can touch the address bar, type a word, and then touch find in page. I find it better, and more intuitive than the traditional way.  It also allows the menu to be cleaner, more decluttered.

**Comment by yoasif** [comment]
This is how it looks on Samsung:

![signal-attachment-2019-04-25-134340](https://user-images.githubusercontent.com/152493/56756649-3843ce80-6760-11e9-9662-dd6b1ee2f74a.png)

I think it is a good idea.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809962

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
