### ISSUE TITLE
Retrieve branding name and version from chrome priv JS (remote debugging)

### ISSUE THREAD

**Issue by juliandescottes** [mozilla-mobile/fenix#2016]
For DevTools' remote debugging, we currently retrieve the browser name from the "chrome://branding/locale/brand.properties" string bundle, and the browser version from `Services.appInfo.version` (from Services.jsm).

When connected to Fenix/Firefox Preview, we currently get:

* "Mozilla Nightly" for the `brandFullName` string
* the gecko version (eg `68.0.a1`) for Services.appInfo.version

For the browser name we can for now hardcode "Firefox Preview" / "Firefox Preview Beta" / "Firefox Preview Nightly", but it would be nice to have the brand name available via a localized string or any other API.

For the version, I don't think you would like to show the firefox version, but rather the application version? Maybe for now we can get it from ADB when we connect to the browser? But similarly it would be nice to have it available via an API. 

Current bugzilla bug to improve Fenix/Firefox Preview support in remote debugging is https://bugzilla.mozilla.org/show_bug.cgi?id=1542286 for reference.

Thanks!

**Comment by vesta0** [comment]
@cpeterso is there a GV bug for this?

**Comment by cpeterso** [comment]
@snorp - What do you think we should do here? Is Gecko handling the remote debugging protocol itself or does GV or the app mediate the remote connections?

IIUC, GV doesn't know the name or version of the app embedding GV, but we could probably sniff the app's metadata at run-time to return meaningful messages in the remote debugging protocol.

**Comment by cpeterso** [comment]
GV bug 1542286 (to show the proper runtime name and app icon for Fenix in about:debugging) was fixed in GV 68. Does this Fenix issue require more GV work?

**Comment by juliandescottes** [comment]
Any update here, it seems the code we initially used in remote debugging is starting to break cf https://bugzilla.mozilla.org/show_bug.cgi?id=1589087

**Comment by cpeterso** [comment]
> We would still need a reliable API to get the runtime name and version

I see. I filed a new GV bug requesting this new API: https://bugzilla.mozilla.org/show_bug.cgi?id=1589805
