### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Rosabis** [mozilla-mobile/fenix#20178]
## Steps to reproduce
1.install browser
2.open the web
3.homepage icon is too hard to see it clearly at light theme
![IMG_20210626_084417](https://user-images.githubusercontent.com/32984303/123496513-fde55d00-d65a-11eb-82f4-5ba11b70583e.jpg)
### Expected behavior
Have a icon which can be seen clearly
### Actual behavior
see this
![IMG_20210626_084417](https://user-images.githubusercontent.com/32984303/123496513-fde55d00-d65a-11eb-82f4-5ba11b70583e.jpg)

### Device information

* Device vendor / model and Android version: 9
* Firefox for Android version: 91a (go to Settings -> About Firefox)

**Comment by cadeyrn** [comment]
Duplicate of #20154.

**Comment by SoftVision-LorandJanos** [comment]
Hi @cadeyrn ! Thank you for your report! As the issue was already described in #20154 , I will close this one.
