### ISSUE TITLE
FNX-5398 ⁃ [Bug] The "Follow device theme" setting does not follow the device theme

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/fenix#2017]
### Steps to reproduce
1. Go to Android Settings > Display > Customization > Theme and pick "Dark"
1. Open Firefox
1. Go to Firefox Settings > Themes and pick "Follow device theme"

### Expected behavior
Firefox theme is dark

### Actual behavior
Firefox theme is light

### Device information
* Android device: OnePlus 5
* Fenix version: 1.0.1917

**Comment by kbrosnan** [comment]
I see this using a Pixel 3 as well. Using the battery saver mode is the only way I have been able to trigger the auto theme switching.

**Comment by kbrosnan** [comment]
similar #1484

**Comment by vesta0** [comment]
Will address in #1484
