### ISSUE TITLE
Allow adding permanent exceptions to private browser tracking exception list

### ISSUE THREAD

**Issue by CartCaved** [mozilla-mobile/fenix#20188]
### Steps to reproduce
Since Fenix currently doesn't have container support (to run temporary containers) I run the browser in permanent private mode, including opening links in a new private tab. This currently prevents me from using exceptions to enhanced tracking protection. 

- Go to a website in regular browsing mode
- Turn off tracking
- Confirm that the site is on the exception list
- Go to the website in private browsing mode
- tracking protection is still enabled

### Expected behavior

The exception list should be obeyed also in private mode. Alternatively Fenix should allow me the choice to permanently store the exception even for private tabs. 

### Actual behavior

Exceptions added in private mode are not stored in the exception list (see  #5227). Exceptions added in regular browsing mode are not obeyed in private mode.

### Device information

    Android device: Pixel 2 XL
    Fenix version: 
    89.1.1 (Build #2015812947)
    AC: 75.0.22, 5204f4025
    GV: 89.0-20210527174632
    AS: 74.0.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16925)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807540

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
