### ISSUE TITLE
Dynamically adjust tabs display

### ISSUE THREAD

**Issue by HappyPony** [mozilla-mobile/fenix#20185]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Make one less click when opening tab when smartphone display with docking station on larger screen
### How do you know that this problem exists today?
S.Screenshots bottom. 

### Why is this important?
Because I am forced to make one more click per open tab compared to other browsers.

![Samsung Internet-Smartphone-View](https://user-images.githubusercontent.com/3226308/123542254-28f1ae80-d738-11eb-8dd2-3f528b33233f.jpg)

### Bottom see display tabs on a large screen in another browser "Samsung Internet"
![Samsung-Internetr-Desktop-View](https://user-images.githubusercontent.com/3226308/123542257-2a22db80-d738-11eb-8d09-41a4e2cbfdee.jpg)

### Who will benefit from it?
All users who use the smartphone with a large screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16924)

**Comment by Imerion** [comment]
I'd really like this feature even on small screens, as mobile Firefox used to do and many other mobile browsers, like Vivaldi, also does.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812872

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
