### ISSUE TITLE
FNX-5399 ⁃ [Bug] Fenix only syncs history up to this week/month

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2018]
## Steps to reproduce
1. Login with an old FF account which has history from over a month.
1. Sync on Fenix.
1. Check the history list.
    1. Expected behavior
All history is synced on Fenix.
    1. Actual behavior
In the History list, nothing old from the desktop app is displayed, just new synced items.
You can see what was synced by typing in the URL bar some URLs from the desktop history.
No older history items (from March, for e.g.) appear in the search suggestions, just the last month or so. 
    1. Device information

* Android device: Pixel (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/24

**Comment by kbrosnan** [comment]
@grigoryk what is the expected behavior here?

**Comment by vesta0** [comment]
This is expected behaviour.
