### ISSUE TITLE
[Bug] The back arrow should be reversed in RTL languages

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#20190]
## Steps to reproduce
1. Set the app's language to Arabic, or any RTL language.
2. Observe the back arrow of the menus from Settings.

### Expected behavior
The back arrow is pointing to the right.

### Actual behavior
The back arrow is pointing to the left.

### Device information
* Devices: all
* Firefox for Android version: 6/28 Nightly, and Beta 90.0.0-beta.6
* Not reproducible on RC 89.1.1

![Untitled](https://user-images.githubusercontent.com/40694158/123606159-493b6f00-d805-11eb-9e4f-fef1de8b1e11.png)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/06 with Samsung Note 10 (Android 12) and LG G7 Fit (Android 8.1).
