### ISSUE TITLE
[Bug] "Install" PWA to Home screen is not performed

### ISSUE THREAD

**Issue by hellpe** [mozilla-mobile/fenix#20191]
## Steps to reproduce
1. Navigate https://sanipasse.fr/ or https://airhorner.com/
2. Open the main menu
3. Tap the "Install" button.
       
### Expected behavior
PWA is created on Home Screen.

### Actual behavior
PWA is not created. Nothing happens.

### Device information

* Device vendor / model and Android version: Crosscall Core-X4, Android 10
* Firefox for Android version: Nightly 91.0a1

Not reproduced on Chrome 91.0.4472.120

**Comment by SoftVision-LorandJanos** [comment]
Hi @hellpe! Thank you for your report! I could not reproduce the issue described above. I've used the latest Nightly build (91.0a1 - 2021-06-28T05:09:42.643) and for 3 devices (with different Android versions) I got the prompt with "Add" and the install finished successfully for both sites. Could you check if it happens with the latest Nightly? Thank you!
Tested with: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).

**Comment by hellpe** [comment]
Hello @SoftVision-LorandJanos! I have eventually reinstalled Firefox on my device and couldn't reproduce the issue afterwards. Furthermore, I have also tested it on a similar phone model and couldn't reproduce it either. I guess I can close this ticket. Thank you for your quick answer!

**Comment by natrius** [comment]
Out of curiosity: Where should the "Install" button appear? I opened both sites above and when pressing the "three dots", there is nothing about 'Install'. Am i missing something? @hellpe

**Comment by hellpe** [comment]
> Out of curiosity: Where should the "Install" button appear? I opened both sites above and when pressing the "three dots", there is nothing about 'Install'. Am i missing something? @hellpe

Hi natrius, the button changes according to the visited website. See how it looks on my screenshots: one is from a regular website, the other from a PWA (https://hyperdraft.rosano.ca/)

![Screenshot_20211122-204543](https://user-images.githubusercontent.com/1238320/142925456-faf7efbf-12de-46a6-bcea-4485f86431d7.png)
![Screenshot_20211122-204606](https://user-images.githubusercontent.com/1238320/142925463-d45925b7-19d3-4ef0-bad1-bd6235d7db45.png)

**Comment by natrius** [comment]
Hint for anybody missing this "Install"-Button: 
**Check if the launcher you are using does support PWA** - OpenLauncher does not yet (see issue (https://github.com/OpenLauncherTeam/openlauncher/issues/522) or pull request https://github.com/OpenLauncherTeam/openlauncher/pull/637 )
