### ISSUE TITLE
[Bug] New "Revenir dans cet onglet" and "Tout afficher" strings are overlapping in French

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#20196]
## Steps to reproduce
Open Firefox
Press the Home button
See the new home page

### Expected behavior
New strings in French should not overlap

### Actual behavior

See screenshot :
![image](https://user-images.githubusercontent.com/218971/123755669-7008ac80-d8bc-11eb-910f-a255f1bc828a.png)

### Device information
Redmi Note 7, Android 9
Build #2015819019

**Comment by Mugurell** [comment]
Looks like [the layout](https://github.com/mozilla-mobile/fenix/blob/9d3cf790510ed4eaddcd924ba31e93b4c20b111c/app/src/main/res/layout/recent_tabs_header.xml) needs to be updated to stop the items from overlapping.
The title already supports being shown on two lines but then height of the header would probably need to be updated to `wrap_content` to support this.

**Comment by SoftVision-LorandJanos** [comment]
Hi @klint ! Thank you for your report! I can reproduce the issue you described on one device (Huawei P9 Lite - Android 7.0) but on other devices the issue is not reproducible: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11).
Tested on the latest Nightly (91.0a1 - 2021-06-29T05:06:58.580)

**Comment by klint** [comment]
Actually, in addition to allow wrapping, it would be better to have a shorter text that would not need to wrap in 99% of the cases! "revenir dans cet onglet" is quite a "heavy" sentence. Why not a shorter "Dernier onglet" ("Last tab"). It is quite obvious that pressing the tab button below will open it.
Also it is a substantive, like "Collection", not an imperative sentence. More consistent with the "Collection" string.

**Comment by Mugurell** [comment]
I think this ^^ would be of interest to @Delphine.

Independent of this there is a bug in the implementation that needs to be resolved until when it may reproduce for other languages / device configurations (font/text size/zoom).

**Comment by Nickoriginal** [comment]
Not reproducible on Samsung Galaxy A20s (Nightly 91.0a1 2021-06-29T17:37:50.207, Android 10)

**Comment by klint** [comment]
Same issue with the new "Récemment enregistrés" section.

**Comment by klint** [comment]
Solved in recent nightlies.
