### ISSUE TITLE
[Bug] Unable to screenshot in private browsing

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#20195]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Make sure " allow screenshots in private browsing" is enabled
- Open a private tab
- Open the tab drawer
- Try to take a screenshot

### Expected behavior
Screenshot is taken

### Actual behavior
Unable to take a screenshot. Additionally, after doing this it's also impossible to take screenshots of private tabs themselves (without opening tab tray). Toggling the setting to allow screenshots fixes this but doesn't affect taking screenshots of the tab tray.

### Device information

* Device vendor / model and Android version: Huawei Nova 6 (Android 10)
* Firefox for Android version: Nightly 91.0a1 (Build #2015818443)

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue on the 6/29 Nightly build.
Tested with Samsung Galaxy Note 8 (Android 9), Google Pixel (Android 10), and OnePlus 5T (Android 10).
@mobd could you clear your data and retest?

Thank you!

**Comment by sflorean** [comment]
Wasn't able to reproduce this issue on Beta/Release builds, and everything worked as expected on latest Nightly, following the steps. 
Devices: Samsung Note 10 (Android 12) and LG G7 Fit (Android 8.1).
@mobd could you please confirm, that is is fixed for you?

**Comment by codrut-topliceanu** [comment]
I posted videos on the PR https://github.com/mozilla-mobile/fenix/pull/20203#issue-680082425 of the behavior with and without the fix

**Comment by mobd** [comment]
I can also no longer reproduce. Thank you!
