### ISSUE TITLE
Edit buttons for URL field

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#20198]
Copying and pasting URLs must be one of the most common operations outside of navigating between pages, well, it is for me, anyway. As such I wish there was a much more accessible way to copy and paste URLs to/from the URL edit field. Personally, if it was up to me, I would place two small buttons next to the URL field that would always be showing whenever the URL field was visible. These two buttons would be for a) copy the current URL, and b) paste clipboard in place of the current URL, without automatic go, since the URL may need cleaning up first.

Seriously, these tiny but significant features would make using Firefox a relief and make it stand out over the competition.

P.S. I would even go as far as adding a multi-line URL pop-up editor available at the tap of a button next to the above suggested buttons. Anything that makes editing URLs easy is a huge bonus.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16932)

**Comment by Dunexus** [comment]
Currently, the easiest way to copy / paste url is by long pressing the url bar.

The issue with the idea of adding button on the url bar is that there will be little room to display the actual url.

**Comment by mrandreastoth** [comment]
> 
> 
> Currently, the easiest way to copy / paste url is by long pressing the url bar.
> 
> The issue with the idea of adding button on the url bar is that there will be little room to display the actual url.

It would be nice if the option to have these buttons could be included with Firefox and to then let the user decide if they want to actually include them or not. After all, Firefox for the desktop is very configurable, so why shouldn't  this configurability carry over into the mobile version?

Also, not every mobile device has a small screen, some use phablets or tablets, or they have very high resolutions allowing more of the URL to be seen anyway.

The other option is to display these new buttons above the URL alongside the two buttons Scan and Search engine that area already there but are only visible when the edit field is active.

The other thing is that the available visible area of the URL is mostly useless anyway, which is why the other option of displaying a pop-up multi-line editor would be excellent in not just editing a URL but actually being able to see it all without trying to make sense of it in the current single-line edit field.

I seriously think something must be done about this. URL management is, after all, one of the most important things of a browser, besides rendering a page, etc., yet it appears to be the portion given the least thought for improvement.

**Comment by mrandreastoth** [comment]
The current possible states of the URL bar...

![Screenshot_20210702-093531_Firefox Nightly](https://user-images.githubusercontent.com/26897855/124238570-0a652c00-db19-11eb-8220-5177161484dc.png)

![Screenshot_20210702-093544_Firefox Nightly](https://user-images.githubusercontent.com/26897855/124238573-0afdc280-db19-11eb-9680-e2f977fde400.png)

![Screenshot_20210702-093553_Firefox Nightly](https://user-images.githubusercontent.com/26897855/124238576-0b965900-db19-11eb-8d6d-8300d053f3b8.png)

**Comment by mrandreastoth** [comment]
Note how by default the displayed portion of the URL mainly only fits the domain. To the left of it is the home button, a button I *never* use but some designer has forced on me. There is *no* way within the mobile edition of Firefox to disable this button. Instead it sits there and wastes real estate. I would be happier if I could instead configure the buttons to my own preferences just like Firefox for the desktop allows me. After all, the configurability of Firefox is why most uses chose it in the first place, I know that's why I did way back when Firefox was still new on the scene. Let's retain this configurability and flexibility with the mobile editions as well. Otherwise Firefox is just like the others and there's not much reason to choose one over the other.

Oh, and note what happens if I tap on the URL, then I am shown a microphone button. Once again, this is a feature I *never* use yet the button is forced on me.

Note the third option whereby I am shown a bar above the URL bar with yet another two buttons that I have *never* used and don't intend to use. Once again a complete waste of real-estate for my needs. Yet I have no say in this but have to suffer the loss of real-estate because someone made that decision for me.

Firefox is not Apple software. Let us not fall in the trap of their philosophy of hard-coding user-interfaces because we think we know what's best for the user. Let's not be that arrogant. Let's provide user with choice. Let's empower users.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813938

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
