### ISSUE TITLE
[Bug] white flash appears on loading web page when activating gfx.webrender.software

### ISSUE THREAD

**Issue by KenFangidae** [mozilla-mobile/fenix#20193]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
set gfx.webrender.software to true and restart your browser. now try to open any website

### Expected behavior
the background color when loading the page should be dark

### Actual behavior
white flash appear

### Device information

* Device vendor / model and Android version: Samsung/Android 11
* Firefox for Android version: Nightly v.91

**Comment by SoftVision-LorandJanos** [comment]
Hi @KenFangidae ! Thank you for your report! I can sometimes reproduce the issue you described. Other times works as expected. The closest bug I found to be related to this is #13153, it looks to me that by fixing that issue, should fix this one as well.
Tested on the latest Nightly (91.0a1 - 2021-06-29T05:06:58.580).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1719367

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
@KenFangidae Do you have dark theme enabled? If you're using the light theme then I think a white flash would be expected. But if you're using dark theme, then yes I think this is a bug.

**Comment by jamienicol** [comment]
If this is indeed about when using a dark theme, the #6313 was the equivalent bug for non-software-webrender. There was a part of it which affected all graphics backends, and a webrender specific part: https://bugzilla.mozilla.org/show_bug.cgi?id=1663732

I need to read over the code again, but presumably there's just a part of software webrender not hooked up to the clear color correctly.
