### ISSUE TITLE
FNX-5400 ⁃ [UX] Search via QR Code

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#202]
As a user, I want to be able to use my browser to scan a QR code, so I can access a URL or search term for more information.

### Acceptance Criteria:
-I can easily find my browser QR code scanner
-I can tap on the QR scanner to initiate a scan 
-Once QR code is captured, my browser takes me directly to the URL or search result page

**Comment by vesta0** [comment]
@mheubusch @shorlander  please let me know if we can close this issue.
