### ISSUE TITLE
browser.tabs.remove() freezes the page content

### ISSUE THREAD

**Issue by utubo** [mozilla-mobile/fenix#20207]
## Steps to reproduce
Call `browser.tabs.remove(tabIds)` to remove the tab, when there is only one tab.

### Expected behavior
Show "about:home"

### Actual behavior
The page content freezes.

### Device information
* Device vendor / model and Android version: SH-M07 Android 10
* Firefox for Android version: Firefox 91.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16936)

**Comment by ohhai** [comment]
Could it be related - https://github.com/mozilla-mobile/fenix/issues/20737 ?

**Comment by ohhai** [comment]
Still happens periodically at the current versions.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814148

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
