### ISSUE TITLE
[Bug] cannot use navigatror.canShare()

### ISSUE THREAD

**Issue by BLumia** [mozilla-mobile/fenix#20205]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

Use `navigator.canShare(shareObj)` [as MDN suggested](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#:~:text=first%20test%20for%20and%20call%20navigator.canShare()).

### Expected behavior

`navigator.canShare(shareObj)` could do what descripted in [`Navigator.canShare()` MDN documentation descripted](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare).

### Actual behavior

`navigator.canShare(shareObj)` function doesn't exist.

### Device information

* Device vendor / model and Android version: OnePlus 3T
* Firefox for Android version: 89.1.1
 
-----------------

### Additional information

I know it's non-standard right now but Firefox for Android does actually (partially) support `Navigator.share()` which is useful. Since the documentation suggested to do feature detection by testing for `navigator.canShare()`, I didn't find ant related bug reports about adding `canShare()` and related API supports to Firefox (both PC and Android), so I created this bug.

At https://bugzilla.mozilla.org/show_bug.cgi?id=1312422 I can see there is a bug marked as fixed to implement Web Share API to Firefox, but it seems it's not supported at all on PC (not sure if it's a regression, but I haven't found any other related bug report), and partially supported on Android. At https://github.com/mozilla-mobile/fenix/issues/11946 there is a bug related to the support of `share()`, but not `canShare()`.

Hope it's the right place to report this issue, if not, please let me know where should I report to. Thanks!

**Comment by makotokato** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1666203. `canShare` isn't implemented.

**Comment by kbrosnan** [comment]
Closing upstream bug.
