### ISSUE TITLE
[Bug] Secure connection failed on a secure website (salutelazio.it)

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#20206]
## Steps to reproduce
1. Visit the official website of the Italian Lazio Regional Health System: https://www.salutelazio.it
### Expected behavior
Firefox for Android should show that the connection is secure, as it is shown on Google Chrome (both mobile and desktop), Firefox for Desktop and some Firefox for Android revisions.

https://user-images.githubusercontent.com/85299944/123942084-7887e280-d9a3-11eb-8af7-68169c430310.mp4

https://user-images.githubusercontent.com/85299944/123946230-a53df900-d9a7-11eb-88e9-cfee59e5106e.mp4

### Actual behavior
A "Secure Connection Failed" page is showed.

https://user-images.githubusercontent.com/85299944/123942312-b08f2580-d9a3-11eb-8fd5-afc24b6bf2bb.mp4

### Device information

* Device vendor / model and Android version: Samsung Galaxy A20s (ARM64, Android 10 (beta and nightly), Samsung Galaxy J2 Prime (ARMV7, Android 6.1.1 (stable)
* Firefox for Android version: 
Nightly 2021-06-29T17:37:50.207
91.0a1 (Build #2015819211)
AC: 91.0.20210629143047, 8904b55efe
GV: 91.0a1-20210629092640
AS: 79.0.0

    Beta 90.0.0-beta.6 (Build #2015818371)
AC: 90.0.11, 536cb9fe13
GV: 90.0-20210624190035
AS: 77.0.2

    Stable 89.1.1 (Build #2015812945)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1
### Note
Desktop browsers are not affected

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/focus-android/issues/4954

**Comment by mcarare** [comment]
This is reproducible on GeckoView Example app, with `ERROR_SECURITY_BAD_CERT` error.

**Comment by mcarare** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1718744

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Nickoriginal** [comment]
No issue because in salutelazio.it missing intermediate certificate in a chain due to server misconfiguration. It is a site's web compatibility bug.
https://github.com/mozilla-mobile/focus-android/issues/4954#issuecomment-871517590

**Comment by quaqo** [comment]
Thanks again to @Nickoriginal for helping me debug this and find the real issue.

**Comment by Nickoriginal** [comment]
> I installed a fresh copy of Firefox ESR 78, no "GlobalSign RSA OV SSL CA 2018" intermediate in about:certificate.
> 
> I visited _https://salutelazio.it/_ and got SEC_ERROR_UNKNOWN_ISSUER.
> 
> I visit another website with full intermediate chain for "GlobalSign RSA OV SSL CA 2018" such as:
> 
> _https://www.telenet.be/_
> 
> In about:certificate I got "GlobalSign RSA OV SSL CA 2018" and https://salutelazio.it/ was secure.

Here's demonstration how certificate error can be fixed on mobile browsers too using your advice. Apply it:

https://user-images.githubusercontent.com/85299944/123998002-abe56400-d9d9-11eb-9c59-c15cffd6d016.mp4

**Comment by Nickoriginal** [comment]
My browsers on Android (Firefox Stable) and desktop (Firefox 89 and Chrome) and @quaqo's browsers on Android (Firefox Nightly and Stable) were not affected because they're already visited sites with presented intermediate certificate, in our cases - "GlobalSign RSA OV SSL CA 2018".

**Comment by quaqo** [comment]
I can't reproduce the "fix" on Focus thou (for obvious reasons, I think it clears everything on close). But on my other device (Huawei Honor) as reported [here](https://github.com/mozilla-mobile/focus-android/issues/4954) it works... And I checked there's no certificate at system level.

I guess let's not go too deep as it is the webmaster's fault here.

**Comment by Nickoriginal** [comment]
@mcarare, it's time to close [Bugzilla 1718744](https://bugzilla.mozilla.org/show_bug.cgi?id=1718744).

**Comment by Nickoriginal** [comment]
Preloading the intermediate certificates as described in [bug 1520297](https://bugzilla.mozilla.org/show_bug.cgi?id=1520297) would also resolve this one automatically.
