### ISSUE TITLE
FNX-490 ⁃ [Bug] Tapping Android back button after selecting text doesn't dismiss selection

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2020]
## Steps to reproduce
1. Go to any webpage.
1. Long tap to select any text from the page.
1. Tap the Android back button.

### Expected behavior
Selection handlers are dismissed and text is no longer highlighted.

### Actual behavior
You are taken back to the previous page.

### Device information
* Android device:
  * Nexus 5 (Android 6.0.1)
  * Samsung Galaxy S8 (Android 8)
* Fenix version: 4/24

**Comment by ekager** [comment]
@cpeterso GV handles the text selection menu right? Do you know if there's already a bug for this?

**Comment by ekager** [comment]
I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1570167

**Comment by cpeterso** [comment]
The GV engineers say the app (Fenix) should be responsible for clearing the text selection. However, there is no GV API available to do that 😄 so an API will be added in https://bugzilla.mozilla.org/show_bug.cgi?id=1570810.

The GV bug is in our P3 backlog, but I see this Fenix issue is a P1. How urgent is this bug fix? Not being able to dismiss the text selection using the back button doesn't seem like that a big problem, though having the page instead navigate back would be annoying.

**Comment by ekager** [comment]
@vesta0 what do you think?

**Comment by vesta0** [comment]
This bug doesn't beak usability but it does hinder browser adoption. We should keep it as a P2. I will place it in the right priority order on the Fenix Waiting board. Thanks!

**Comment by cpeterso** [comment]
Correction: there are two bugs here:

1. Clearing the text selection on the web page when the Android back button is pressed.
2. Dismissing the popup menu when the Android back button is pressed.

Re # 1: Fenix will need the new GV API:  https://bugzilla.mozilla.org/show_bug.cgi?id=1570810

Re # 2: Randall says Fenix can dismiss the popup menu without GV's help (and that the app should be responsible for this, not GV). Fenix can implement this right now without the new GV API for # 1, though the text selection will remaining after the user presses the Android back button. The user can clear the text selection by tapping the input focus to someone else on the page. https://bugzilla.mozilla.org/show_bug.cgi?id=1570810#c4

**Comment by cpeterso** [comment]
Removing `needs:gv` label because Elliot says in https://bugzilla.mozilla.org/show_bug.cgi?id=1570810#c6:

> This can be done with no additional [GeckoView] API changes.
> A SelectionActionDelegate can know if the CCP menu is visible.
>  As an example clearSelection in BasicSelectionActionDelegate closes the CCP menu and clears selected text. The menu was visible if mResponse is non-null at that time.

Some SelectionActionDelegate API improvements will happen in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1581161.

**Comment by gabrielluong** [comment]
This is gonna be fixed in https://github.com/mozilla-mobile/android-components/issues/4240.
