### ISSUE TITLE
[Meta] FLAG_SECURE issues with Screenshots, Recents, Picture in Picture, in PrivateMode

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#20202]
This is an attempt to try and accumulate several other issues & decisions related to Screenshots and Private Browsing in one place, with the intent of having something to refer back to later.

_Please feel free to edit this or comment if it's incorrect or needs further clarifications._

### Concepts/Goals
- When `Allow screenshots in private browsing` is **Disabled** (settings->private browsing) (image1):
-- Fenix in Private Browsing mode should not allow screenshots.
-- Fenix private tabs from TabsTray should not be screenshotable
-- Fenix in Private Browsing mode should not show up in recent apps (image2) [(Issue discussing this)](https://github.com/mozilla-mobile/fenix/issues/11153)
-- Fenix private browsing videos in Picture in Picture mode should not be screenshot-able 
- When `Allow screenshots in private browsing` is **Enabled** (settings->private browsing) (image1):
-- Fenix in Private Browsing mode should _allow_ screenshots.
-- Fenix private tabs from TabsTray _should be_ screenshotable [(issue link)](https://github.com/mozilla-mobile/fenix/issues/20195) ->[fix here](https://github.com/mozilla-mobile/fenix/pull/20203)
-- Fenix in Private Browsing mode _should still not show up_ in recent apps (image2) [(Issue discussing this)](https://github.com/mozilla-mobile/fenix/issues/11153) **-> This feature doesn't work reliably**
-- Fenix private browsing videos in Picture in Picture mode should be screenshot-able -> [Confirmation here](https://github.com/mozilla-mobile/fenix/issues/20098#issuecomment-878556643) -  [(issue link)](https://github.com/mozilla-mobile/fenix/issues/20098)

image1 - allow screenshots in private browsing _(I'm unsure what the description of the setting is referring to)_
![image](https://user-images.githubusercontent.com/60002907/123797010-6bf58280-d8ee-11eb-8477-e14b249ee5a6.png)

image2 - recent apps
<img src="https://user-images.githubusercontent.com/60002907/123796620-fd182980-d8ed-11eb-9ca0-b29981f5357e.png" width=250/>

_Further bugs on the matter:_

https://github.com/mozilla-mobile/fenix/issues/17855 - issue with AC's SecureWindowFeature
https://github.com/mozilla-mobile/fenix/issues/20250 - to prevent video capture apps from recording private TabsTray

**Comment by Nickoriginal** [comment]
> When Allow screenshots in private browsing is Enabled > (settings->private browsing) (image1):
> -- Fenix in Private Browsing mode should allow > screenshots.

@mobd reported the issue about it [here](https://github.com/mozilla-mobile/fenix/issues/20195).

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20195
