### ISSUE TITLE
[Bug] Browser dialog pages are broken when JavaScript disabled

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#20213]
## Steps to reproduce
1. Open about:config page (in the stable Firefox this bug is also present but cannot be reproduced due to about:config page is not accessible and JavaScript cannot be disabled in settings)
2. Set javascript.enabled to false
3. Open https://expired.badssl.com (for example, to call dialog page)
### Expected behavior
Dialog page should be accessible, contain text, clickable buttons and pictures, how it does when JavaScript enabled.
![Screenshot_20210701-105953_Firefox](https://user-images.githubusercontent.com/85299944/124094069-1988a300-da61-11eb-82f7-d9b2ea2b2d80.jpg)
### Actual behavior
Dialog page is broken, doesn't contain any useful info and cannot be skipped, requiring by user to enable JavaScript.
![Screenshot_20210701-105844_Firefox Beta](https://user-images.githubusercontent.com/85299944/124094429-75532c00-da61-11eb-8a24-c9e223aa7e0e.jpg)
### Device information
* Device vendor / model and Android version: Samsung Galaxy A20s (Android 10)
* Firefox for Android version: Beta 90.0.0-beta.6, Nightly 91.0a1 2021-06-30T17:07:09.023

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20213

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/focus-android/issues/4567

**Comment by kbrosnan** [comment]
This is not a supported configuration.
