### ISSUE TITLE
FNX-5401 ⁃ [Bug] The account section should always show user email while logged in

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2021]
## Steps to reproduce
1. Sign in with a fx account. Restart the app.
1. Go straight to Settings. Check the account section.
    1. Expected behavior
The email account is displayed.
    1. Actual behavior
"@ Firefox account" is displayed for a few seconds before the user email appears again.
On Pixel, hard to reproduce: a few times the Sign in banner was displayed until I left the Settings menu and returned. Then it updates and shows the email address.
    1. Device information

* Android device: Pixel (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/24

### Misc
* [ ] Make sure #4019 is also fixed with this fix

**Comment by vesta0** [comment]
@sv-ohorvath is this the same issue as the more recent #4019

**Comment by sv-ohorvath** [comment]
@vesta0 They seem similar, yes. This case also shows "Firefox account" for longer now, not just a second. Should we close #4019 as a dupe?

**Comment by liuche** [comment]
It sounds like this is still an issue, and we can dupe #4019.

Also clearing @boek bc it's been a while.

**Comment by sblatz** [comment]
When we hit `onAuthenticated` we should update the name. This should be a pretty simple fix.

**Comment by ekager** [comment]
AH sorry @jyeontaek I didn't see you were assigned :/

**Comment by liuche** [comment]
@jyeontaek maybe you can review it :)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 190806.
