### ISSUE TITLE
[Bug] No dialog is displayed on crash

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#20215]
## Steps to reproduce
1. Open a few tabs and go to about:crashparent

### Expected behavior
App crashes and closes. A dialog is displayed with the following elements:
"Sorry, Firefox Preview had a problem and crashed."
[]Send crash report to Mozilla - checkbox.
[Close] button.
[Restart Firefox Preview] button.
### Actual behavior
The dialog is not displayed.
### Device information

* Device vendor / model and Android version: Google Pixel 4 (Android 11).
* Firefox for Android version: latest Nightly (91.0a1 2021-07-01T05:09:17.528).

### Notes
1. The behavior described above was after clearing data. Before that it didn't even crashed, see [video](https://user-images.githubusercontent.com/48829350/124110895-64aab200-da71-11eb-8bc3-babdacb27b8b.mp4)
2. I couldn't reproduce on other devices. Tested on Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9) and Huawei P9 Lite (Android 7.0) as well.

[Video](https://user-images.githubusercontent.com/48829350/124111987-86f0ff80-da72-11eb-8297-a520a2f8ab2a.mp4)

**Comment by Nickoriginal** [comment]
Confirmed in Stable (89.1.1), Beta (90.0.0-beta.6) and Nightly (2021-06-30T17:07:09.023) on Samsung Galaxy A20s (Android 10)

https://user-images.githubusercontent.com/85299944/124120674-b4db4180-da7c-11eb-8e1a-e3012138c7cd.mp4

https://user-images.githubusercontent.com/85299944/124120695-bad12280-da7c-11eb-8e86-871c9d80484a.mp4

Not confirmed on Samsung Galaxy J2 Prime (Android 6.0.1) (I think that you are right, it depends on Android version)
![Screenshot_20210701-145206](https://user-images.githubusercontent.com/85299944/124121033-169bab80-da7d-11eb-9aca-8e91843fc6fb.png)

**Comment by SoftVision-LorandJanos** [comment]
I believe [#4748](https://github.com/mozilla-mobile/focus-android/issues/4748) is related and based on [this](https://github.com/mozilla-mobile/focus-android/issues/4748#issuecomment-851501267) comment, I will close this issue.
