### ISSUE TITLE
[Bug] Fullscreen mode prevents phone from sleeping

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#20225]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- View a page in fullscreen. If it's a video, pause the video or wait till it's finished
- Wait for how long it takes for your screen to lock

### Expected behavior
Screen locks
### Actual behavior
Screen doesn't lock. Not sure if this is a bug but other browsers do lock the screen
### Device information

* Device vendor / model and Android version: Huawei Nova 6 (Android 10)
* Firefox for Android version: Nightly 91.0a1 (Build #2015819019)

**Comment by SoftVision-LorandJanos** [comment]
Hi @mobd ! I can reproduce the issue you described. Checked with other browsers as well, where it doesn't happen. However I'm not sure either if it's intended or not this way.
Tested on the latest Nightly (91.0a1 2021-07-02T05:07:53.859).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).

**Comment by Nickoriginal** [comment]
**Firefox Nightly 91.0a1 2021-07-03T17:04:26.908**
_Reproducible_ on:
**Samsung Galaxy A20s** (Android 10)

**Firefox 90.0.0-beta.6**
_Reproducible_ on:
**Samsung Galaxy A20s**

**Firefox 89.1.1**
_Reproducible_ on:
**Samsung Galaxy A20s**
**Samsung Galaxy J2 Prime** (Android 6.0.1)
> However I'm not sure either if it's intended or not this way.

@SoftVision-LorandJanos, I think it is intended this way because it is bad when phone locks screen at the beginning or in the middle of the fullscreen video.

**Comment by kbrosnan** [comment]
This is intended behavior.

**Comment by mobd** [comment]
@kbrosnan @Nickoriginal this bug is not about if a video is playing, but if it's paused or finished, or other non-video fullscreen pages. No other browser prevents sleeping in those scenarios and I don't see any benefit to it either. Sometimes I fall asleep watching something and my phone's screen stays on the whole time

**Comment by Nickoriginal** [comment]
@mobd, I'm sorry, I didn't read your "steps to reproduce" attentive enough, I wasn't right. When fullscreen video is paused, device screen is blocked in the Chrome. @kbrosnan, you should reopen it to learn more details and fix it, because it is not intended behavior compared to other browsers.

**Comment by Nickoriginal** [comment]
#20295

**Comment by Nickoriginal** [comment]
That's all I can do for its re-opening. Still reproducible in Firefox 90.1.1 and other editions.
