### ISSUE TITLE
Update search telemetry to use the AC common implementation

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#20229]
Follow-up to https://github.com/mozilla-mobile/focus-android/issues/4778 and https://github.com/mozilla-mobile/android-components/issues/7249

**Comment by Mugurell** [comment]
This should be ready to test in tomorrows Nightly.
It would be important to test the probes and scenarios from https://github.com/mozilla-mobile/fenix/issues/6557 and https://github.com/mozilla-mobile/fenix/issues/6558 on both a new install and on an updated app.

**Comment by Mugurell** [comment]
Although I see pings working as expected in today's Nightly [here](https://debug-ping-preview.firebaseapp.com/pings/petruNewSearch3) there are some warnings about extensions' permissions.
Let's hold off testing until we fix that warning also.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly build.
✔️After using the same STR, in all 3 cases the same count for search related metrics got generated

Metrics ping `13680156-b074-44e6-8b0f-32f8f06487dd` from a 6/30 Nightly build.

```
"labeled_counter": {
          "browser.search.ad_clicks": {
            "google.in-content.organic.none": 1
          },
          "browser.search.in_content": {
            "baidu.in-content.organic._1000969a": 2,
            "baidu.in-content.sap._1000969a": 1,
            "bing.in-content.organic.none": 1,
            "bing.in-content.sap.mozb": 1,
            "duckduckgo.in-content.organic.h_": 1,
            "duckduckgo.in-content.sap.fpas": 3,
            "google.in-content.organic.none": 1,
            "google.in-content.sap-follow-on.firefox-b-m": 1,
            "google.in-content.sap.firefox-b-m": 1,
            "yahoo.in-content.organic.none": 5
          },
          "browser.search.with_ads": {
            "google": 1
          }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-0722001)
[Logcat](https://github.com/mozilla-mobile/fenix/files/6862555/oldBuild.txt)

Metrics ping `534b86dc-a622-4846-a526-498e7aff94fc` after updating from 6/30 Nightly build to latest 7/22 Nightly build

```
"labeled_counter": {
          "browser.search.ad_clicks": {
            "google.in-content.organic.none": 1
          },
          "browser.search.in_content": {
            "baidu.in-content.organic._1000969a": 2,
            "baidu.in-content.sap._1000969a": 1,
            "bing.in-content.organic.none": 1,
            "bing.in-content.sap.mozb": 1,
            "duckduckgo.in-content.organic.h_": 1,
            "duckduckgo.in-content.sap.fpas": 3,
            "google.in-content.organic.none": 1,
            "google.in-content.sap-follow-on.firefox-b-m": 1,
            "google.in-content.sap.firefox-b-m": 1,
            "yahoo.in-content.organic.none": 5
          },
          "browser.search.with_ads": {
            "google": 1
          }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-07223)
[Logcat](https://github.com/mozilla-mobile/fenix/files/6862587/afterUpdate.txt)


Metrics ping `bfa888ad-0a0b-4adc-863c-1fc616d36a4a` from a freshly installed 7/22 Nightly build

```
"labeled_counter": {
          "browser.search.ad_clicks": {
            "google.in-content.organic.none": 1
          },
          "browser.search.in_content": {
            "baidu.in-content.organic._1000969a": 2,
            "baidu.in-content.sap._1000969a": 1,
            "bing.in-content.organic.none": 1,
            "bing.in-content.sap.mozb": 1,
            "duckduckgo.in-content.organic.h_": 1,
            "duckduckgo.in-content.sap.fpas": 3,
            "google.in-content.organic.none": 1,
            "google.in-content.sap-follow-on.firefox-b-m": 1,
            "google.in-content.sap.firefox-b-m": 1,
            "yahoo.in-content.organic.none": 5
          },
          "browser.search.with_ads": {
            "google": 1
          }
```
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-0722000)
[Logcat](https://github.com/mozilla-mobile/fenix/files/6862586/Fresh.install.txt)

❗ On the other hand I've noticed an add related inconsistency while performing different searches on Yahoo.com, filled #20470
