### ISSUE TITLE
Provide button to copy device information for use with bug tickets

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#20227]
When creating a bug ticket, the user is told to include the following section...

```
### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)
```
 
Visiting the About screen under Android displays a lot of various version strings which cannot all be selected at once to copy-and-paste into a ticket. In fact, only one of these many strings are required, but which one a user should include is not clear for the uninitiated. In addition, it isn't always clear as to how a user is to identify the Android version they are running. So, to make life easier for people, and to ensure the required information is collected and in a consistent way, why not provide a button on the About screen of Firefox, all editions, that copy all of the required information (including device vendor, model, and Android version) to the clipboard so that it can then simply be pasted directly into a bug report?

**Comment by mcarare** [comment]
Very similar to https://github.com/mozilla-mobile/fenix/issues/14098.

**Comment by kbrosnan** [comment]
Closing as a duplicate
