### ISSUE TITLE
FNX-5402 ⁃ [Bug] Push notifications do not work

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2022]
## Steps to reproduce
1. Go to https://gauntface.github.io/simple-push-demo/
1. Tap on the "Enable Push Notifications".

### Expected behavior
Push notifications prompt is displayed.

### Actual behavior
No push notifications prompt is displayed as the toggle cannot be activated.

### Device information
* Android device: 
  * Nexus 5 (Android 6.0.1)
  * Samsung Galaxy S8 (Android 9)
* Fenix version: 4/24

**Comment by vesta0** [comment]
Push notification will be built in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1343678
