### ISSUE TITLE
Revoked certificates not trapped

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#20226]
Firefox Nightly (and most likely all editions) does not trap revoked certificates when such a site is visited (test facility to be provided in an update). This is highly concerning since the revolution of a certificate should be brought to the user's attention as it can indicate some concerning reasons why this was done, such as a previously OK site having gone rogue for whatever reason. Note that I have yet to find a browser, Firefox or otherwise, that actually handles revoked certificates. However, just because everyone fails does not mean Firefox should copy a bad habit, a habit that, according to the following link, goes way back...

https://www.zdnet.com/article/major-linux-rpm-problem-uncovered/

My suggestion: make all editions of Firefox warn on revoked certificates by default.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16949)

**Comment by Nickoriginal** [comment]
Confirmation: https://revoked.badssl.com/
No warning, no "Secure Connection Failed"

**Comment by mrandreastoth** [comment]
> Confirmation: https://revoked.badssl.com/
> No warning, no "Secure Connection Failed"

Interesting, my Firefox does the right thing and warns me, but I have used another test case for which it didn't. I must try to locate that test case when I can. Meanwhile I wonder why this test case worked. Could it be an extension that I have installed?

**Comment by Nickoriginal** [comment]
What extension do you have installed? You are using mobile Firefox? I have only HTTPS Everywhere installed, but it doesn't said nothing. 89.1.1, Android 10

https://user-images.githubusercontent.com/85299944/124273761-19fc6900-db49-11eb-9152-9bbbd59ed0f0.mp4

**Comment by RachitKeertiDas** [comment]
I cannot reproduce this on the latest Fenix Nightly.

I get a "Secure Connection Failed" Error for https://revoked.badssl.com/ .

**Comment by Nickoriginal** [comment]
Hmm...
Tested in the latest Nightly 91.0a1 2021-07-01T17:41:24.496 on Samsung Galaxy A20s, Android 10, ETP disabled, addons disabled. There is a mistake with handling revoked certificates in my Firefox browsers?
https://user-images.githubusercontent.com/85299944/124288954-6d2ae780-db5a-11eb-9f18-47701f007c97.mp4

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20226#issuecomment-873031471
Confirmed in Nightly 91.0a1 2021-07-02T17:40:22.633
<img src = https://user-images.githubusercontent.com/85299944/124350631-576efe00-dbfe-11eb-9961-fccde5298af2.jpg width = 45%>

**Comment by sheikh-azharuddin** [comment]
One thing I dislike how errors are handled..
It should clearly show why secure connection failed..
Is it because of certificate expired/revoked/unknown issuer etc

Not to forget unlike chromium browsers firefox android does not has option to view certificate details

**Comment by mrandreastoth** [comment]
> 
> 
> What extension do you have installed? I have only HTTPS Everywhere installed, but it doesn't warn me. 89.1.1, Android 10, 6.0.1
> 2021-07-02_15-16-50_001.mp4

Hmm, I just realised all my security plug-ins (extensions) are disabled. So not sure what's going on.

**Comment by mrandreastoth** [comment]
> 
> 
> One thing I dislike how errors are handled..
> It should clearly show why secure connection failed..
> Is it because of certificate expired/revoked/unknown issuer etc
> 
> Not to forget unlike chromium browsers firefox android does not has option to view certificate details

Absolutely agree. Knowing why can quite significantly affect a use's response. After all, a revoked certificate does suggest something fishy compared to an expired certificate, for example.

**Comment by mrandreastoth** [comment]
> 
> 
> Tested in the latest Nightly 91.0a1 2021-07-01T17:41:24.496 on Samsung Galaxy A20s, Android 10, ETP disabled, no addons installed, app data was cleared before. Maybe there is a mistake with handling revoked certificates in my Firefox browsers?
> 2021-07-02_17-17-03_001.mp4
> 
> **UPD 07.02:** [#20226 (comment)](https://github.com/mozilla-mobile/fenix/issues/20226#issuecomment-872851762)
> [#20226 (comment)](https://github.com/mozilla-mobile/fenix/issues/20226#issuecomment-873031471)
> Confirmed in Nightly 91.0a1 **2021-07-02T17:40:22.633** and 90.0.0-beta.6
> <img alt="" width="45%" src="https://user-images.githubusercontent.com/85299944/124350631-576efe00-dbfe-11eb-9961-fccde5298af2.jpg">

It's rather disconcerting that your doesn't fail and must be investigated.

**Comment by Nickoriginal** [comment]
@mrandreastoth, I noticed, that https://revoked.badssl.com/ is starting to be flagged as dangerous after some time of browser use. When opening it instantly after data cleaning (App Info -> Storage -> Clear data) browser does not show security notification in all Firefox editions.

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20226#issuecomment-874000757
Tracked as #19158

**Comment by sheikh-azharuddin** [comment]
Issue not fixed...

**Comment by sheikh-azharuddin** [comment]
Site still showing as secured...

![Screenshot_20220113-163621027 (1)](https://user-images.githubusercontent.com/58127841/149319022-d16ae253-796b-474b-bb10-617cd000fd63.jpg)

**Comment by sheikh-azharuddin** [comment]
> Yes, the same for me.

My bad maybe it's expected...I accessed the same url in other chromium browsers too...shows the same...maybe certificate itself is not revoked

Another good test url is https://revoked.grc.com/
It shows insecure in firefox but in chromium browsers  it shows secure which indicates chromium browsers not doing revoking checks.. so I believe firefox is doing really good is catching revoked certificate!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813659

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
