### ISSUE TITLE
Request
For Myanmar users, we need support for CUSTOMIZED DEFAULT FONT of our Android 10 China ROM devices as those devices use NotoSans Myanmar Zawdecode as Default. We have to use Pyidaungsu font as CUSTOMIZED DEFAULT FONT.

### ISSUE THREAD

**Issue by aswedaw** [mozilla-mobile/fenix#20238]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Who will benefit from it?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16956)

**Comment by aswedaw** [comment]
Indigenous Tai Scripts use
NotoSans Myanmar font . But, China's telephone makers use
non-Unicode NotoSans Myanmar Zawdecode font in Android 10 China ROM devices.
Mon,Burmese, Arakanese,PaOh and Tai Indigenous peoples use
these phone. They can't see their Scripts correctly as all browsers render using good-for-nothing non-Unicode NotoSans Myanmar Zawdecode . So,we need a browser which supports or follow the CUSTOMIZED DEFAULT FONT of our devices.
Thank you so much,Mozilla.

**Comment by boek** [comment]
Dup of #19985
