### ISSUE TITLE
Import Passwords to Firefox as csv file

### ISSUE THREAD

**Issue by avjayarathna** [mozilla-mobile/fenix#20232]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

**Comment by Nickoriginal** [comment]
feature request 🌟

**Comment by cadeyrn** [comment]
> We can export Firefox passwords as csv file.

How do you export passwords in Firefox for Android? 🤔

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20232#issue-935887303
Should be "feature request 🌟"

**Comment by avjayarathna** [comment]
> 
> 
> > We can export Firefox passwords as csv file.
> 
> How do you export passwords in Firefox for Android? 🤔

**Comment by Nickoriginal** [comment]
In that GitHub repository mobile Firefox is developed and discussed.
