### ISSUE TITLE
Keep Firefox in the Galaxy Store updated

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#20241]
### What is the user problem or growth opportunity you want to see solved?
Firefox in the Galaxy Store isn't updating on time. Almost 1.5 years it had a deprecated version [68.11.0](https://www.mozilla.org/firefox/android/68.11.0/releasenotes/).
Last time it was updated on May, 6 to [88.1.3](https://www.mozilla.org/firefox/android/88.0/releasenotes/).
## Screenshot
![20210703_234859](https://user-images.githubusercontent.com/85299944/124366584-7babf880-dc59-11eb-860e-3aa4d5bb96e6.jpg)
![20210703_234954](https://user-images.githubusercontent.com/85299944/124366587-836b9d00-dc59-11eb-8974-00ca24eb63ed.jpg)
It is important because the latest Firefox 89.1.1, released on June, 1 contain fixes to **15 vulnerabilities**: 6 with _high_ impact, 7 with _moderate_ impact and 2 with _low_ impact to users, according to [Mozilla Foundation Security Advisory 2021-23](https://www.mozilla.org/security/advisories/mfsa2021-23/). Unfortunately, these important fixes are not available for Galaxy Store users.
### Who will benefit from it?
Users, who keep Firefox updated with Galaxy Store, will receive the latest Firefox with performance improvements, security fixes and [new features](https://www.mozilla.org/en-US/firefox/android/89.0/releasenotes/), for example, new [Proton design](https://www.mozilla.org/firefox/89.0/releasenotes/) (available only in 89 and higher) and will have the best user experience from Firefox using.

**Comment by Nickoriginal** [comment]
Feature request 🌟

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/focus-android/issues/4969

**Comment by kbrosnan** [comment]
I'll pass this along to the releases team.

**Comment by Nickoriginal** [comment]
Resolved, thanks!
<img src = https://user-images.githubusercontent.com/85299944/124710195-1aa84d00-df05-11eb-9e15-b1cdc566a7f8.jpg width = 45%>
