### ISSUE TITLE
Private mode: Open link in new tab (regular mode)

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20246]
### What is the user problem or growth opportunity you want to see solved?

Currently, in standard mode, a link can be opened in a new tab or alternatively in a new private tab via the context menu.

In private mode, on the other hand, it is only possible to open in private mode.

It would be desirable if a link could be "sent" to a new tab in standard mode from private mode. Opening a link in a new tab in standard mode would ensure recording in the history of the pages visited if necessary.

### How do you know that this problem exists today? Why is this important?

Increase in usability

### Who will benefit from it?

Every user

I understand this feature request as cross-platform, i.e. as a general Firefox function independent of the mobile Android platform.

**Comment by SoftVision-LorandJanos** [comment]
Hi @WebworkrNet ! Thank you for the report! I can confirm the behavior is as you described above.
Tested with the latest nightly (91.0a1 - 2021-07-05T05:06:51.686).
Device used: Google Pixel 4 (Android 11).

**Comment by Nickoriginal** [comment]
Link can be copied from private mode then inserted in the standard mode address bar, but it is not so comfortable, as in your proposition case, so I like it!

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/10132

**Comment by WebworkrNet** [comment]
> Link can be copied from private mode then inserted in the standard mode home page address bar, but it is not so comfortable, as in your proposition case, so I like it!
> 
> > Link can be copied from private mode then inserted in the standard mode home page address bar.
> 
> Use this solution as a temporary alternative.

I am already doing this. :-)

**Comment by WebworkrNet** [comment]
I'm sorry about the duplicate ticket. My research did not find ticket 10132.
