### ISSUE TITLE
UI test crash - java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20247]
• The `mainMenuInstallPWATest` UI test crashed 1x on Debug 7/3. 
• Seems to be crashing after opening the main menu `openThreeDotMenu`

❓ Could be a [hardware acceleration related problem](https://stackoverflow.com/questions/27232275/java-util-concurrent-timeoutexception-android-view-threadedrenderer-finalize)

### Device information

* Device vendor / model and Android version: Pixel 2, Virtual, API Level 29 - Cuttlefish x86
* Firefox for Android version: Debug 7/3

### Notes
► [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6650536562229874260/executions/bs.948bc4404e3edac5/test-cases)

► Stacktrace
07-03 10:15:33.290: W/CryptauthV2(5181): --------- beginning of crash
07-03 10:15:33.303: E/AndroidRuntime(7566): FATAL EXCEPTION: FinalizerWatchdogDaemon
07-03 10:15:33.303: E/AndroidRuntime(7566): Process: org.mozilla.fenix.debug, PID: 7566
07-03 10:15:33.303: E/AndroidRuntime(7566): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at android.view.ThreadedRenderer.nDeleteProxy(Native Method)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:967)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at java.lang.Thread.run(Thread.java:764)
07-03 10:15:33.303: E/ExceptionHandler(7566): Uncaught exception handled: 
07-03 10:15:33.303: E/ExceptionHandler(7566): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at android.view.ThreadedRenderer.nDeleteProxy(Native Method)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:967)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at java.lang.Thread.run(Thread.java:764)
07-03 10:15:33.328: I/CryptauthV2(5181): [ReEnrollmentCryptauthFramework] Performing SyncKeysRequest with 6 keys.
07-03 10:15:33.416: I/mozac/CrashReporter(7566): Received crash: UncaughtExceptionCrash(timestamp=1625332533304, throwable=java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds, breadcrumbs=[Breadcrumb(message=onCreate(), data={recreated=false, intent=android.intent.action.MAIN, instance=256362217}, category=HomeActivity, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:00 PDT 2021), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:01 PDT 2021), Breadcrumb(message=onStart(), data={instance=256362217}, category=HomeActivity, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:01 PDT 2021), Breadcrumb(message=onResume(), data={instance=256362217}, category=HomeActivity, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:01 PDT 2021), Breadcrumb(message=Changing to fragment searchDialogFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:07 PDT 2021), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:09 PDT 2021), Breadcrumb(message=onAttach(), data={instance=179028011, activityInstance=256362217, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:09 PDT 2021), Breadcrumb(message=onCreateView(), data={customTabSessionId=null, instance=179028011, activityInstance=256362217, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:09 PDT 2021)], uuid=b5911af2-ce80-4180-8aa8-7d0e196c0da0)
07-03 10:15:33.479: E/memtrack(2077): Couldn't load memtrack module
07-03 10:15:33.479: W/android.os.Debug(2077): failed to get memory consumption info: -1
07-03 10:15:33.515: W/GLSUser(2572): [DeviceKeyStore] Cannot load key: Device key file not found.
07-03 10:15:33.578: I/ActivityManager(2077): Start proc 10308:org.mozilla.fenix.debug:crashReportingProcess/u0a95 for service org.mozilla.fenix.debug/mozilla.components.lib.crash.service.SendCrashTelemetryService
07-03 10:15:33.598: I/mozac/CrashReporter(7566): Showing prompt
 
logged separate issue for investigation: https://github.com/mozilla-mobile/fenix/issues/21797

**Comment by AndiAJ** [comment]
Crashed again on Master 7/9: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8830249384888836501/executions/bs.416e38e82fa87d23/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Also crashed on StrictEnhancedTrackingProtectionTest#testStrictVisitProtectionSheet when the ETP shield icon was clicked to see the ETP details sheet:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5664004010732847933/executions/bs.f63b4352cbfc5a63/issues

**Comment by AndiAJ** [comment]
Received a crash of `testStrictVisitSheetDetails` on 8/11 Main, but the test still **passed ✔️**. 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5454214598113655263/executions/bs.722d0f1cfd45f7c2/test-cases)

`Performing 'single click' action on view with id: org.mozilla.fenix.debug:id/tracking_content`
As mentioned, The last action was to open the "Tracking content" details (`openDetails`)

**Comment by AndiAJ** [comment]
`testStrictVisitSheetDetails` 💥 crashed - flaky 1x on 8/27 Main 

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5457946283883325964/executions/bs.e66489dd07bd6de/testcases/1/logs)

**Comment by AndiAJ** [comment]
`testStrictVisitDisableExceptionToggle` flaky 1x on 9/4 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8869775540039198097/executions/bs.2b884d8383bf82fb/testcases/1/logs)

**Comment by AndiAJ** [comment]
`testStrictVisitProtectionSheet` flaky 1x on 9/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7721544630779456519/executions/bs.28ea38986b69ade3/testcases/1/logs)

**Comment by AndiAJ** [comment]
`testStrictVisitDisableExceptionToggle` flaky 1x on [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7385133966857513402/executions/bs.8dfe7e2e8986eec0/testcases/1/logs)

**Comment by sv-ohorvath** [comment]
testStrictVisitSheetDetails flaky again on 9/22: [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8278794498371878886/executions/bs.1c8611a47fec99ae/issues)

**Comment by sv-ohorvath** [comment]
mainMenuInstallPWATest  crashed on 10/1: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7020774727486573930/executions/bs.43bf4e4606a71bdd

**Comment by sv-ohorvath** [comment]
mainMenuInstallPWATest crashed on 10/6 https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8741857791016672135/executions/bs.7e7a1b1e305c28c2

**Comment by AndiAJ** [comment]
Flaky 1x `mainMenuInstallPWATest` crashed on 10/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8417991211609697682/executions/bs.d6a55711409ac1/testcases/1/logs)

**Comment by AndiAJ** [comment]
openBookmarkInPrivateTabTest crashed on 12/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8541809207061299238/executions/bs.8218081c3a82d6b8/testcases/1/logs)

**Comment by AndiAJ** [comment]
mainMenuInstallPWATest Flaky 1x on 1/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6154461042563423190/executions/bs.4d19b74067a39daa)

**Comment by AndiAJ** [comment]
testStrictVisitProtectionSheet Flaky 1x on 2/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7471522327065362314/executions/bs.85bd1a31ab776f4e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
mainMenuInstallPWATest Flaky 1x on 2/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5209704759348969642/executions/bs.3ab057662aaf3c7c/testcases/1/logs)

**Comment by AndiAJ** [comment]
verifyReaderViewAppearanceColorSchemeChange flaky 1x on 3/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7990348231970079023/executions/bs.cc4afab809a1918/testcases/1/logs)

**Comment by AndiAJ** [comment]
Closing for now, as we didn't encounter this problem for a month.
