### ISSUE TITLE
FNX-5403 ⁃ History entries menu contains only "Delete", could be a button instead

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2024]
Spawned from my comment on  #563

## Steps to reproduce
Navigate to History from Your Library

### Expected behavior
There is an x button where the three dot menu is, letting me delete history entries. 

Preferred view from Kiwi: 

![52917354-66b4b180-32b8-11e9-9d9b-4812a8116648](https://user-images.githubusercontent.com/152493/56726625-1ecd6300-671d-11e9-91d6-9c2590dd0877.png)

### Actual behavior
Three dot menu appears with a single option within it -- Delete. 

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store.

**Comment by vesta0** [comment]
Thanks for filing. This matches the UX specs but we will keep this in mind in user testing.
