### ISSUE TITLE
[Bug]Private TabsTray should not be recordable by video capture app

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#20250]
As seen in https://github.com/mozilla-mobile/fenix/issues/17855#issuecomment-775109558 Screen capture apps can still record video of the Private TabsTray

## Steps to reproduce
1. Install a screen capture app and begin recording
2. Open several private tabs
3. Return to the non-private browsing home screen
4. Open tabsTray and switch to private tabs page

### Expected behavior
- Private tabs from the Private TabsTray page should **not** be visible in the recording

### Actual behavior
- Private tabs from the Private TabsTray page are visible in the recording

### Device information

* Device vendor / model and Android version: Pixel 3XL Android (10)
* Firefox for Android version: Latest Nightly

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly (91.0a1 2021-07-09T05:07:18.274).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).
Recording app used: AZ Screen Recorder.
