### ISSUE TITLE
FNX-5404 ⁃ Build a delete confirmation dialuge for Deleting all history

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2025]
## Steps to reproduce
1. Navigate to History from Your Library
1. Tap "Delete history"

### Expected behavior
A confirmation step prior to delete or an undo snackbar after delete. This is destructive and should have some guard around it. 

### Actual behavior
History is deleted with no confirmation or undo. 

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by topotropic** [comment]
@vesta0 this sounds like something we should do rather soon, I'd suggest to go with a dialog, similar to Fennec "Are you sure you want to clear your history?" Cancel/OK as a quick solution

**Comment by vesta0** [comment]
I agree with your suggestion @topotropic . Will you provide mocks for it?

**Comment by topotropic** [comment]
@vesta not sure if we need mocks, I thought we already have a dialog window implemented we can re-use (Copy: "Are you sure you want to clear your history?" Cancel/OK).

**Comment by sv-ohorvath** [comment]
Testing currently blocked by #2682

**Comment by sv-ohorvath** [comment]
Verified on the 5/23 build.
