### ISSUE TITLE
[Bug] Input with <datalist> elements don't autocomplete

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#20262]
## Steps to reproduce
1. Visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist#Examples.
2. On the "Result" section, tap on the "Choose a browser from this list".

### Expected behavior
A dropdown is available, and there are different browsers displayed in the list.

### Actual behavior
No dropdown is available. Typing the name of the browser is not recognized (i.e. Chrome).

### Device information
* Devices: Samsung Galaxy Note 8 (Android 9), Google Pixel (Android 10)
* Firefox for Android: Nightly 91.0a1 from 7/5, Beta 90.0.0-beta.6, and RC 89.1.1
* Issue copied from Focus repo (https://github.com/mozilla-mobile/focus-android/issues/4266)
 
![Untitled](https://user-images.githubusercontent.com/40694158/124562306-8b892f80-de47-11eb-89c1-4c7d496aac19.png)

**Comment by mileskrell** [comment]
This bug is still present and can still be reproduced by following the original steps.

Device: Google Pixel 4a (Android 11)
Firefox for Android: 95.2.0

**Comment by NunoMouraBlek** [comment]
bump
