### ISSUE TITLE
FNX-5405 ⁃ [Bug] Custom tab toolbar scrolls down after opening in Preview

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2026]
## Steps to reproduce
1. Set FP as your default browser.
1. Open any custom tab.
1. Tap on the 3dot menu and select "Open in Firefox Preview".
1. Tap on the back button.
1. Scroll up and down the content.

### Expected behavior
The Custom tab toolbar stays in place or autohides.

### Actual behavior
The Custom tab scrolls down the page.

### Device information
* Could not reproduce this issue on Pixel, Galaxy S8 or HTC Desire 820.
* Android device: Nexus 5 (Android 6.0.1)
* Fenix version: 4/24

![gif](https://user-images.githubusercontent.com/17178945/56732260-68da3700-6765-11e9-8f16-34ad68dd8b2d.gif)

**Comment by sblatz** [comment]
I can no longer reproduce this, @bsurd can you confirm this happens on the latest nightly?

**Comment by sv-ohorvath** [comment]
Doesn't reproduce on the latest build 5/2. Closing.
