### ISSUE TITLE
Please add "home" icons on toolbar and new tab page

### ISSUE THREAD

**Issue by devmet34** [mozilla-mobile/fenix#20265]
Hi, Fenix daylight version: 89.1.1, there is no home button icon on toolbar and on new tab page either. Please add this feature, thank you.

**Comment by cadeyrn** [comment]
A home button was already implemented in the toolbar of Firefox Nighly. It will be in the stable release of Firefox in a few weeks.

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20265#issuecomment-874768464

> It will be in the stable release of Firefox in a few weeks.

Same for "Jump back in" feature in a new tab page, Credit Cards (coming soon, implemented in beta 90) and gesture "Pull to refresh", if I understood right (if you had a questions about it)
@devmet34, as I said you can expect in the Firefox 90 release only Credit Cards feature. You need to wait before home button adding at least until Firefox 91 or more.

**Comment by kbrosnan** [comment]
Home button is shipping in an upcoming version of Firefox.
