### ISSUE TITLE
[Bug] Firefox 90.1.0 released with about:config accessible

### ISSUE THREAD

**Issue by fprietog** [mozilla-mobile/fenix#20274]
Just installed and tested these packages:
- fenix-90.1.0-arm64-v8a.apk
- fenix-90.1.0-armeabi-v7a.apk

Both came with about:config accesible and with several non usual hidden options when debug menu is activated. AFAIK It's supposed to be only accessible in beta and nightly channels.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Firefox 90.1.1 using the following devices:

• Google Pixel 4 (Android11)
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus 5T (Android 10)
• OnePlus A3 (Android 6.0.1)
