### ISSUE TITLE
FNX-5406 ⁃ [Bug] Delete all tabs from Fenix kills the custom tab webpage

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2027]
## Steps to reproduce
1. Open a custom tab in Gmail/ slack.
1. In Fenix, in tabs view, tap the Open tabs menu and Delete.
1. Check the custom tab from step 1.
    1. Expected behavior
The webpage is still displayed in the custom tab.
    1. Actual behavior
The custom tab is still opened,  but the webpage is blank. (Sharing the link will crash the browser.)
    1. Device information

* Android device: Pixel
* Fenix version: 4/23

**Comment by ekager** [comment]
This seems like a blocker so I'm pulling this into the sprint @bifleming

**Comment by ekager** [comment]
This is fixed in AC and will be fixed in the next snapshot

**Comment by kbrosnan** [comment]
Verified using a self built 688cae33c33aa3457428fa0a1a5a8bb18ee0b068
