### ISSUE TITLE
[webcontent] Amazon Smile: Favicon not shown

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20288]
## Site with issue and any steps to reproduce
**https://smile.amazon.de**
### Expected behavior
Favicon is shown.
### Actual behavior
Favicon is _not_ shown.
### Does toggling Tracking Protection fix the issue?
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?
Unfortunately, I could not carry out the test.

**Comment by WebworkrNet** [comment]
### Device information

* Android 10
* Samsung Galaxy XCover 4s

**Comment by WebworkrNet** [comment]
### Device information

* Firefox Nightly
* 91.0a1 (Build #2015819211)
AC: 91.0.20210629143047, 8904b55efe
GV: 91.0a1-20210629092640
AS: 79.0.0

**Comment by WebworkrNet** [comment]
### Device information

* Firefox Daylight
* 89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/android-components/issues/10377
