### ISSUE TITLE
[Bug] Youtube autoplay leads to non-fullscreen picture in picture (PiP) mode

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#20280]
Not entirely sure what the desired behavior should be here.

## Steps to reproduce
1. Go to a Youtube Video, play it and enable autoplay
2. Press Home button, or change app so that Pip mode is activated
3. Wait for video to finish.

### Expected behavior
- Either stop pip mode and video OR fullscreen the next video as well.

### Actual behavior
- Youtube navigates to next video and continues playing but the pip mode isn't of a fullscreen fenix. See screenshot below.

### Device information

* Device vendor / model and Android version: Pixel 4 (Android 11)
* Firefox for Android version: Release 89.1.1
 
![errorpip](https://user-images.githubusercontent.com/60002907/124765799-03865100-df3f-11eb-83cc-87acb62cd6c8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17193)

**Comment by Nickoriginal** [comment]
Seems related to #18727, because they lead to the same effect in the PiP window.

**Comment by jonalmeida** [comment]
> Not entirely sure what the desired behavior should be here.

With a proper PiP API from BZ-1625012, we would be able to see the next video that is autoplayed (and is the current behaviour on desktop PiP as well) which is a feature we get for free based on Youtube's current site implementation.
