### ISSUE TITLE
FNX-5407 ⁃ [Bug] Html controls don't work in custom tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2028]
## Steps to reproduce
1. Open in a custom tab: rpappalax.github.io/testapp 
1. Verify the drop-down menus, date/time pickers, file download, text selection.
    1. Expected behavior
All of the above work.
    1. Actual behavior
None of the above work.
    1. Device information

* Android device: Pixel, HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/24

**Comment by jonalmeida** [comment]
Similar to https://github.com/mozilla-mobile/fenix/issues/1311, the session ID needs to be passed to the features for them to work:
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt#L231

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/21 build. 
devices: Xiaomi Mi Pad 2 (Android 5.1) - x86, Galaxy S8 (Android 9)
