### ISSUE TITLE
Sync favicons between Firefox installations

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20287]
URLs are synchronized via bookmarks and history.

The associated favicons are only displayed in the "target" installation if the addresses are also called up in the "target" browser.

**Comment by WebworkrNet** [comment]
Samsung Galaxy XCover 4s

**Comment by WebworkrNet** [comment]
Firefox Daylight
89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

**Comment by WebworkrNet** [comment]
Firefox Nightly
91.0a1 (Build #2015819211)
AC: 91.0.20210629143047, 8904b55efe
GV: 91.0a1-20210629092640
AS: 79.0.0

**Comment by WebworkrNet** [comment]
Android 10

**Comment by kbrosnan** [comment]
Favicon sync would be provided by the Application Services team closing in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=428378
