### ISSUE TITLE
FNX-5408 ⁃ Open account login in new tab

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2029]
## Steps to reproduce
Not logged in to a Firefox account, go to Settings, tap on "Sign in"

### Expected behavior
a new tab opens and I go to accounts.firefox.com 

### Actual behavior
my last viewed tab opens and I'm redirected to accounts.firefox.com

### Device information
* Android device: ?
* Fenix version: ?

**Comment by cadeyrn** [comment]
Sounds like #787.

**Comment by sv-ohorvath** [comment]
Testing currently blocked by issue #2935

**Comment by sv-ohorvath** [comment]
A new tab is created for account login/signup. Closing this as fixed.
