### ISSUE TITLE
[Bug] Favicons and text scrambled when return to start page

### ISSUE THREAD

**Issue by fprietog** [mozilla-mobile/fenix#20293]
Just tested these packages:
- fenix-90.1.1-arm64-v8a.apk
- fenix-90.1.1-armeabi-v7a.apk

Both have this problem; in start page, by default, the favicons and it's associated texts are shown correctly. But, when you choose one and then push back button to return to start page, the favicons and it's text are shown scrambled.
It also happens opening a new tab.
I doesn't happens always but most of time.

## Steps to reproduce
Open Firefox without any tab active. This is an example of my start page with favicons and text correctly paired:
![imagen](https://user-images.githubusercontent.com/9756455/124895939-4b5bb580-dfdd-11eb-861d-0a6efb1a4a3b.png)

I push one of the favicons (for instance the 9gag one). Then I push back button to return to start page... Now favicons and text are scrambled (it mixed texts also from the second page):
![imagen](https://user-images.githubusercontent.com/9756455/124896166-7e9e4480-dfdd-11eb-9286-45101ff56440.png)

Here is a video showing the problem:

https://user-images.githubusercontent.com/9756455/124919781-e4e39100-dff6-11eb-9252-52ac0792e13e.mp4

### Expected behavior
The favicons and it's associated texts will be shown correctly

### Actual behavior
The favicons and it's associated texts are shown scrambled when return to start page.

### Device information
Firefox 90.1.1 (Build #2015820739)
Tested in Poco F2 Pro (Android 11) and Samsung Nexus 10 (Android 7)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/19677

**Comment by fprietog** [comment]
Quick update: I'm using FF 91.1.0 (Build #2015826187) since it's release a few days ago and can confirm for sure that this bug is solved. Thanks.
