### ISSUE TITLE
[Bug] startpage like url/folder: favicon not shown

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20291]
## Steps to reproduce
When called, the URL forwards by definition to a subfolder.

example.org → example.org/folder

### Expected behavior
Favicon is shown.

### Actual behavior
Favicon is _not_ shown.

**Comment by WebworkrNet** [comment]
### Device information

* Samsung Galaxy XCover 4s
* Android 10

**Comment by WebworkrNet** [comment]
### Device information

* Firefox Nightly 
91.0a1 (Build #2015819211)
AC: 91.0.20210629143047, 8904b55efe
GV: 91.0a1-20210629092640
AS: 79.0.0

**Comment by WebworkrNet** [comment]
### Device information

* Firefox Daylight
89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

**Comment by WebworkrNet** [comment]
### Samples:

* http://bugzilla.mozilla.org → http://bugzilla.mozilla.org/home
* http://tk.de →http://tk.de/techniker
* http://www.wunschliste.de → http://www.wunschliste.de/main

**Comment by WebworkrNet** [comment]
I am limiting the "Bugzilla" example. The favicon is only displayed in the history or next to the bookmark after several calls.

**Comment by SoftVision-LorandJanos** [comment]
Hi @WebworkrNet ! I can reproduce the issue you described on the latest Nightly (91.0a1 2021-07-09T05:07:18.274).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0)
