### ISSUE TITLE
Bug #20255 was mistakenly closed

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#20295]
## Steps to reproduce **(reference from bug [#20255](https://github.com/mozilla-mobile/fenix/issues/20225)**)
- View a page in fullscreen. If it's a video, pause the video or wait till it's finished
- Wait for how long it takes for your screen to lock

### Expected behavior
When fullscreen video is paused, device screen _should be blocked_ after screen timeout (captured in Chrome).

https://user-images.githubusercontent.com/85299944/124923104-ce433700-e002-11eb-9222-954af525ec65.mp4

### Actual behavior
When fullscreen video is paused, device screen _is not blocked_ after screen timeout.

https://user-images.githubusercontent.com/85299944/124926923-bbcafc80-e006-11eb-862e-3de0d48840f4.mp4

**Reproducible in Firefox 90.1.1.
We should reopen it to learn more details and fix it, because it is not intended behavior compared to other browsers.**

**Comment by kbrosnan** [comment]
Will check if this is Gecko platform code or something the Android team owns. Closing as a duplicate.
