### ISSUE TITLE
FNX-5409 ⁃ [UX] Custom Tab UI

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#203]
**User Story:**
As a user...

**Current Design Status:**

* TBD 

**Design Priority:**
P?

**Comment by bbinto** [comment]
@lime124 - the reference browser has a basic implementation of Custom Tabs, could you please review and connect with @jonalmeida where needed / for adjustments

**Comment by jonalmeida** [comment]
Feel free to ping me for help on viewing all the options available in a Custom Tabs.

**Comment by jonalmeida** [comment]
We also need to consider the position of the toolbar for custom tabs. The browser is meant to look more like the native app itself to give the illusion of not leaving the context of the calling app, so we might want to think about re-positioning the toolbar to the top like most apps would have.

cc: @lime124

**Comment by brampitoyo** [comment]
Short status update:

1. @jonalmeida and I met to discuss possible approaches to Custom Tabs
2. @jonalmeida has sent me an .apk that allows for rapid Custom Tabs testing
3. I’ve designed an early user flow and mockup, and has posted it to Fenix UX for critique and feedback

**Comment by brampitoyo** [comment]
# 1. Opening a custom tab

On apps that call

**Comment by brampitoyo** [comment]
@vesta0 The custom tab specs is posted above, and @colintheshots this issue is now ready for feedback and breakdown.

**Comment by pocmo** [comment]
@brampitoyo Those look great. I'm a bit worried though that we are breaking one of the value propositions of Custom Tabs (from the app developer's point of view): "make transitions between native and web content more seamless without having to resort to a WebView.".

From the mocks I wonder, is it correct that:
* We do not use the theme color of the app for the toolbar (e.g. red in the gmail example)
* We do not show any custom menu items from the third-party app
* We do not let the app add a custom action button to the toolbar
* We do not let the app define the close button icon

If you are interested in other customization options of custom tabs then scroll a bit through the list of methods here:
https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.Builder

**Comment by bbinto** [comment]
I'd suggest feature parity with Focus, i.e. most of the issues @pocmo mentioned should be addressed then.

**Comment by vesta0** [comment]
@brampitoyo mocks looks great! What will the back button in the Custom tab overflow menu be used for, as oppose to the browser back button?

**Comment by mheubusch** [comment]
@brampitoyo Reviewing these designs with Stephen - for the Powered by Fenix label type can you use the Material Design Caption spec? Also, this share icon is different than the page action buttons icons.  Need to decide which we are using and apply consistently.  

Please use sentence case - Desktop site and Find in page

**Comment by brampitoyo** [comment]
@pocmo wrote:

> I'm a bit worried though that we are breaking one of the value propositions of Custom Tabs (from the app developer's point of view): "make transitions between native and web content more seamless without having to resort to a WebView.".

That’s a really good point!

I suppose I look at it more from the user’s point of view, which is: “Why should I manually switch my default browser to Fenix, if it’s not going to offer any special benefit?”

Therefore, I decided to put a few differentiating features in our custom tabs:

* Bottom app bar, for easy one-handed navigation
* Prominent URL, so it’s clear that the page you’re looking at is a website (instead of an app)
* Prominent button to open the link in Fenix, so it becomes a part of your session
* (And in the future, we might like to put other features such as reader view, etc.)

But you’ve made two really good points:

1. Custom Tabs need to be attractive for developers, for them to want to call it in their apps. If our specs are too restrictive, it’s not going to work.
2. Many Android apps have top app bars. Custom tabs shouldn’t break this positioning expectation that users have.

What if, for v1, we just make our custom tabs functionally similar to Focus or Chrome (as @bbinto has suggested)?

* Position app bar on top
* Allow third-party apps to set:
    * App bar colour
    * Custom action button (our “Open in Fenix” action will appear as a ⫶ menu item)
    * Custom menu items
    * Custom close button icon
* No change to how URLs are displayed (show host name only)

## Questions

1. If we follow Focus/Chrome’s implementations, do we still need to come up with our own default style, in case the app doesn’t specify anything?
2. Can third-party apps specify their own custom font to use in Custom Tab app bar and menu? Can Fenix uses its own font (which is not Roboto)?

**Comment by jonalmeida** [comment]
> 1. If we follow Focus/Chrome’s implementations, do we still need to come up with our own default style, in case the app doesn’t specify anything?

Some aspects, yes. For example, if the toolbar colour isn't provided by the app, then we would show the native browser app's theme colour.

>2. Can third-party apps specify their own custom font to use in Custom Tab app bar and menu? Can Fenix uses its own font (which is not Roboto)?

Unfortunately, no. These are the only options available as linked above: https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.Builder

Another thing to consider is which menu and action buttons do we want to consistently be there. For example, in Focus (and RB now) we always show the 'share' menu item but an app also has an option to ask to show the share button or not. With Focus + RB, this means that if they choose yes, then we have two share buttons. We've also taken away the ability for the app to choose to share a link where they would not want to expose this functionality (intranet links, internal sites, etc.)

**Comment by brampitoyo** [comment]
@jonalmeida @pocmo I’ve updated our Custom Tabs specs so that they have better continuity with third-party apps. As a result, the app bar is moved up top, and it carries some consequences.

@mheubusch I’ve updated the caption text style, Share icon and sentence case as you recommended.

See the updated specs just up above, or click https://github.com/mozilla-mobile/fenix/issues/203#issuecomment-463426620.

**Comment by colintheshots** [comment]
@brampitoyo Are users going to know the Fenix logo is a button and not simply a brand mark? I almost want to put something around it. Maybe a rounded button border?

How will back and forwards work? I'd expect they're both gray initially and only activate later. Is that correct?

**Comment by vesta0** [comment]
@brampitoyo What will the back button in the Custom tab overflow menu be used for, as oppose to the browser back button?

**Comment by jonalmeida** [comment]
> @brampitoyo What will the back button in the Custom tab overflow menu be used for, as oppose to the browser back button?

In a Custom Tab, you can still clicks on that page so the back button would be used for site navigation. It would be greyed out if there is nothing to go back to.

**Comment by mheubusch** [comment]
@brampitoyo I share Colin's concern that the Fenix button looks like a logo and competes with the space given to the URL, but am not sure if what you are suggesting is that this is the default and a developer could move this action to the overflow menu or are you suggesting that this would be a text link in the overflow menu and a developer could add whatever they want there?

**Comment by brampitoyo** [comment]
@colintheshots wrote:
> Are users going to know the Fenix logo is a button and not simply a brand mark or a favicon?

@mheubusch wrote:
> I share Colin's concern that the Fenix button looks like a logo and competes with the space given to the URL

Originally, I was going to give users one-tap access to open links from third-party apps in Fenix (which will then save that link into a session). This is our default state.

But your points are both very good:

1. The Fenix logo doesn’t look like a button
2. It reduces the space for page title

So now I’m thinking that, **by default, our custom tab shouldn’t come with any toolbar button**:

![fenix-custom-tabs-1](https://user-images.githubusercontent.com/51007/53313279-8c2b6600-391d-11e9-8422-2e7f6b394731.png)

”Open in Firefox Fenix” is now the last link inside the overflow menu.

Doing this frees up quite a bit of additional space that we can use to show page title. What do you think?

-----

@mheubusch wrote:
> […] am not sure if what you are suggesting is that this is the default and a developer could move this action to the overflow menu or are you suggesting that this would be a text link in the overflow menu and a developer could add whatever they want there?

Even without our own toolbar action, a developer can still have their own. Doing this will leave less space for page title, but it means more flexibility for developers – and many developers will choose not to use that precious space:

<img width="360" src="https://user-images.githubusercontent.com/51007/53313384-03f99080-391e-11e9-8999-93d20cba7eec.png">

We have moved our “Open in Fenix” action into the overflow menu, but a developer can also have their own item there. Hopefully, most developers will choose this option!

<img width="360" src="https://user-images.githubusercontent.com/51007/53313497-75d1da00-391e-11e9-91d4-e538e5f18e6c.png">

It should be noted that a developer can have _both_ a custom toolbar action and a custom overflow menu item.

-----

Just for completion’s sake, a developer can also recolour the toolbar to make it more seamless with their app:

<img width="360" src="https://user-images.githubusercontent.com/51007/53313919-8420f580-3920-11e9-8a68-716d1bd4e6a0.png">

**Comment by jonalmeida** [comment]
Nice overview of all the Custom Tab options! \o/

**Comment by colintheshots** [comment]
Thanks, Bram! This looks good. I'll mark this closed.

**Comment by brampitoyo** [comment]
@colintheshots @jonalmeida Thanks. I’ve updated my specs up above, so it contains the most recent mocks.

https://github.com/mozilla-mobile/fenix/issues/203#issuecomment-463426620

**Comment by vesta0** [comment]
@brampitoyo I really liked the one-tap access to open links from third-party apps in Fenix but I have to defer to UX experts on this.

**Comment by brampitoyo** [comment]
@vesta0 You’re right. “Open link in Browser” is an important action to have. However, it will come at the cost of hiding some of the page title (ie. we’ll have to truncate many titles if we have so little space for it). For the moment, page title takes priority.

**Comment by sblatz** [comment]
@brampitoyo am I able to get font size for the title as well as the host name? I also need the "elevation" value for the URL bar (relevant for the shadow)

**Comment by brampitoyo** [comment]
@sblatz 

* Title font size: 16dp
* Host name font size: 12dp

<img width="360" src="https://user-images.githubusercontent.com/51007/55535810-6c3c4e80-56e2-11e9-95ab-a500a0de8335.png">

The URL bar elevation value is 1 dp.

Exact dimensions and spacings are posted just below. It had to be relatively narrow to give as much space as possible for title and host name, which can run long.

<img width="360" src="https://user-images.githubusercontent.com/51007/55536152-419ec580-56e3-11e9-9f73-6458464aaa5d.png">

**Comment by topotropic** [comment]
As discussed here https://github.com/mozilla-mobile/fenix/issues/1727#issuecomment-488541929, we want to support hiding URL bar when 3rd party apps request it 
https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.html#EXTRA_ENABLE_URLBAR_HIDING – @vesta0 IMO that is something we can do post MVP, please prioritize. Thanks!
