### ISSUE TITLE
Security query: delete history

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20300]
### What is the user problem or growth opportunity you want to see solved?
The browser history can be deleted without a security query.
### How do you know that this problem exists today? Why is this important?
Accidental deletion cannot be undone.
### Who will benefit from it?
Everybody

**Comment by kbrosnan** [comment]
We don't want to prompt the user to do this action. If a history item is important there is the option to bookmark it.

**Comment by WebworkrNet** [comment]
> We don't want to prompt the user to do this action. 

What speaks against it?

**Comment by WebworkrNet** [comment]
> If a history item is important there is the option to bookmark it.

Of course, I basically agree.

However, there is not always time to save important things immediately, so that the process is postponed until later.
