### ISSUE TITLE
Sync Pinned Sites in Home Page across all devices

### ISSUE THREAD

**Issue by shockergit** [mozilla-mobile/fenix#20309]
Please add an option to sync top sites across all devices. It's frustrating to manually add all pin sites when changing devices or reinstalling Firefox.

**Comment by cadeyrn** [comment]
Duplicate of #10583.

**Comment by mcarare** [comment]
@shockergit Thank you for your report! The feature you are requesting is tracked in #10583. Closing this as duplicate.
