### ISSUE TITLE
[Bug] Bookmarks folder in "Edit Bookmark" sometimes appears incorrectly

### ISSUE THREAD

**Issue by rdragonrydr** [mozilla-mobile/fenix#20307]
## Steps to reproduce
Open a new tab. Enter a search term which appears in the title or URL of a bookmark you have previously saved in (nested?) folders. Select the suggested, bookmarked URL. Alternately, browse or type to the URL of a bookmarked site. Open the side menu and press "edit."

### Expected behavior
The appropriate folder of the bookmark is shown.

### Actual behavior
The "Bookmarks" (mobile bookmarks) folder is shown as the folder instead, even when tapping and editing the folder.

### Device information

*  Android 8.1.0 on a RCA Voyager 7 tablet, model RCT6873W42BMF8
*  Firefox Daylight 89.1.1 Build no.2015812945; AC 75.0.22, 5204f4025; GV 89.0-202010527174632; AS 74.0.1; Friday 5/28 @ 2:05 AM (I have no idea what most of this means, so if I included something personally identifying, please warn me).

**Comment by SoftVision-LorandJanos** [comment]
Hi @rdragonrydr ! Thank you for your report! I was able to reproduce the issue you described, on the latest Nightly (91.0a1 2021-07-09T05:07:18.274).
Devices used: Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy Tab 3 (Android 9), Google Pixel 4 (Android 11) and Huawei P9 Lite (Android 7.0).

**Comment by rocketsroger** [comment]
I can reproduce as well.  In my testing it only happens when the folder is newly created.  If I swipe away Fenix and reopen again the issue goes away.  I'll look into why.

**Comment by Nickoriginal** [comment]
Hello!
Reproducible on _Firefox 90.1.1_ in **Samsung Galaxy A20s**.
> (I have no idea what most of this means, so if I included something personally identifying, please warn me).

It is app internal data, what doesn't contain personal info. In most cases, only the main version of Firefox is needed (here 89.1.1)

**Comment by lobontiumira** [comment]
Verified as fixed on the 92.0a1 Nightly build from 7/18 with Google Pixel (Android 10), Sony Xperia Z5 Premium (Android 7.1.1), and HTC 10 (Android 8).
