### ISSUE TITLE
Add recently closed tabs to tabs tray

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#20310]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-17121

**Comment by codrut-topliceanu** [comment]
Waiting for FNXV2-17122

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/7.
Filed bug #21168 due to the fact that isn't clear when should "Recently closed" button be displayed.
