### ISSUE TITLE
PointerEvent.movementX and .movementY have fixed sign

### ISSUE THREAD

**Issue by HaraldKi** [mozilla-mobile/fenix#20313]
## Steps to reproduce
Create a page with a single canvas element like this.
```
<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <canvas style="border: 1px solid red"></canvas>
    <p></p>
    <script type="text/javascript">
      let p = document.querySelector("p");      
      let c = document.querySelector("canvas");
      c.ontouchstart = (evt) => {
        evt.preventDefault();
      }
      c.onpointermove = (evt) => {
        console.log(evt.movementX, evt.movementY);
        p.innerHTML = "dx=" + evt.movementX + ", dy=" + evt.movementY + "<br/>" + p.innerHTML;
      };
    </script>
  </body>
</html>
```
Navigate to the page, touch the canvas and "drag" (touchmove) your finger across. The delta numbers shown don't look right. At least on my device, for example, the movementY is always negative independent in which direction I drag.

### Expected behavior
The dx and dy values shown should be small negative *and* positive values. This is how it looks in the Chrome browser on the same device and with desktop Firefox on Linux.

### Actual behavior
The dx and dy values are unrealistically large (>100) and do not change sign when dragging left and right up and down

### Device information
* Fairphone 2, Android 9
* Firefox 89.1.1

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1719915

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
