### ISSUE TITLE
FNX-5411 ⁃ [Bug] Accounts.firefox.com says "...to continue to Fenix"

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2031]
## Steps to reproduce
Go to Settings, tap on "Sign in", accounts.firefox.com page opens  (also on confirmation page + Email)

### Expected behavior
It says "... to continue to Firefox Preview" and "You are now ready to use Firefox" on confirmation page

### Actual behavior
It says "... to continue to Fenix" and "You are now ready to use Fenix" on confirmation page

--> Check also confirmation page and email + other touch points I forgot

**Comment by AaronMT** [comment]
FxA bug (@ryanfeeley ?)

**Comment by ryanfeeley** [comment]
Already caught, though I'm getting more arguments on the topic than I want. https://github.com/mozilla/fxa/issues/913

**Comment by shane-tomlinson** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1547251

**Comment by grigoryk** [comment]
1547251 is marked as RESOLVED FIXED, so we should be good to close this one. Testing this, I see "Firefox Sync" and not "Fenix".
