### ISSUE TITLE
SVG Alpha renders incorrectly on Fill-opacity and Alpha channel.

### ISSUE THREAD

**Issue by SuperPauly** [mozilla-mobile/fenix#20315]
## Steps to reproduce

URL: https://firefox-svg-opacity-bug.stackblitz.io
Code: https://stackblitz.com/edit/firefox-svg-opacity-bug?file=src/bg-components/letterP.js

### Expected behavior

When animating the behaviour of the fill-opacity or the alpha channel of RGBA it should display the color/image behind itself.

### Actual behavior

It displays as hard white 255,255,255 when it should be translucent.

### Device information

OS: Android 11
FF setting: 89.1.1 build #2015812947
Model: Motorola G2

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1719914

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
