### ISSUE TITLE
Display Device Name instead of Email associated on the 3 button menu

### ISSUE THREAD

**Issue by metronightly** [mozilla-mobile/fenix#20325]
Issue: I am using Firefox Nightly(July 10, 2021 build) on my Android 10 phone and I am being bothered by this display of my email ID on the 3 button menu. I have attached a screenshot to help you understand.

Reasons:
1. Full Email ID shows up just like that when it absolutely doesn't need/have to.
2. Aesthetically jarring, doesn't sit well with the other options imo.

Suggestion: It would be great if Firefox displayed the 'Device Name' from account settings menu instead of showing the whole email associated with our Firefox Account.

I don't know how many here would agree with this 'feature request' but there you go anyway. I hope this is implemented, thanks.

[Screenshot_Firefox](https://user-images.githubusercontent.com/75716685/125193388-d18c2c00-e269-11eb-9356-bc967fc4a26d.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17219)

**Comment by SoftVision-LorandJanos** [comment]
Hi @metronightly! Thank you for the report! I can confirm that the behavior you described is correct.
Tested on the latest Nightly (91.0a1 - 2021-07-12T05:07:46.131)
Device used: Google Pixel 4 (Android 11).

**Comment by haloboy777** [comment]
Hi,
I want to work on this. How can I get this issue assigned to me?

**Comment by metronightly** [comment]
Hey, any update on this yet?

**Comment by haloboy777** [comment]
Hi @eeejay and @badboy ,

I actually am looking forward to work on this and found somewhat success..
Like in [FenixAccountManager.kt](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt) I want to add another variable called `deviceName`, just like `accountProfileEmail` and use then use `deviceName` variable in place of `accountProfileEmail` in files [DefaultToolbarMenu.kt](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt#L337) and [HomeMenu.kt](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt#L97).

```kt

    /**
     * Returns the Firefox device name if authenticated in app, `null` otherwise.
     */
    val deviceName: String?
        get() = if (accountState == AccountState.AUTHENTICATED) {
            accountManager.authenticatedAccount()?.deviceConstellation()?.state()?.currentDevice?.displayName
        } else {
            null
        }
```


This works sometimes but most of times the `state()` of `deviceConstellation()` comes out as null. 
Please let me know if I'm wrong but I think it's an issue of `accountSettingsStore` not being available in [FenixAccountManager.kt](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt) like it is in [AccountSettingsFragment.kt](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt#L54).

So please can you look at this and let know where to exactly get the device name which is updated on account state changes, which I can then use in [FenixAccountManager.kt](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/components/accounts/FenixAccountManager.kt) for the same.

Best Regards

**Comment by metronightly** [comment]
Any updates on this ?

**Comment by sheikh-azharuddin** [comment]
Instead of display name or device name, probably Mozilla could display one account icon. None of the chromium browsers shows account name or email address and hence the width of the menu is fixed and narrow..here in firefox the email address is unnecessarily increasing the width!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813661

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
