### ISSUE TITLE
FNX-5412 ⁃ [Bug] With history suggestions turned off, the autocomplete feature can still fill in visited websites

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2032]
## Steps to reproduce
1. Go to Settings>Search engines.
1. Turn off Show suggestions based on history adn bookmarks.
1. Type in the search bar the first 2-3 letters of a website from history.
    1. Expected behavior
No autocomplete either when refusing history suggestions.
    1. Actual behavior
The autocomplete feature can show the visited websites.
    1. Device information

* Android device: Pixel
* Fenix version: 4/24

**Comment by ekager** [comment]
I can't reproduce this anymore, so I'm tagging as QA needed

**Comment by sv-ohorvath** [comment]
Not reproducing anymore on the 5/24 build.
