### ISSUE TITLE
Not clear what "Recently saved" means on the homescreen

### ISSUE THREAD

**Issue by massic80** [mozilla-mobile/fenix#20335]
### Steps to reproduce

Open Firefox Nightly 91.0a1 home screen.
Recently a new section has been added, listing the latest added bookmarks.
The title of that section is _Recently saved_, but I find it quite obscure, since you don't immediately get "what has been saved".

### Expected behaviour

I'd change the source of [that string](https://pontoon.mozilla.org/en-GB/firefox-for-android/all-resources/?string=224577) to something like "Recent bookmarks" (due to the lack of space), in order to be more immediate for the user.

### Actual behaviour

...

### Device name

Asus Zenfone 4 Max

### Android version

Android 8

### Firefox release type

Firefox Nightly

### Firefox version

91.0a1

**Comment by amedyne** [comment]
Tagging @topotropic and @vesta0 for the feedback.

**Comment by SoftVision-LorandJanos** [comment]
Hi @massic80 ! Thank you for your report!

I can confirm the behavior is as you described. I will remove the bug label as it is a suggestion/improvement.

Tested on the following devices:
- Samsung Galaxy Tab 3 (Android 9).
- Google Pixel 4 (Android 11).
- LG Nexus 6 (Android 7.1.1).

**Comment by Delphine** [comment]
I would perhaps also add @betsymi for feedback on the string as well. Thank you everyone for the input

**Comment by Delphine** [comment]
I see the string has changed in the meantime and this should now no longer be an issue. Please let me know if it is! thanks

**Comment by amedyne** [comment]
Yes, this is no longer applicable as the string has changes. Closing the ticket.
