### ISSUE TITLE
[Bug]: Cannot navigate to about: pages

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/fenix#20338]
### Steps to reproduce

1. Navigate to about:config

### Expected behaviour

the page opens

### Actual behaviour

An error page displays
<img src="https://user-images.githubusercontent.com/69051186/125330615-da2d4280-e2fb-11eb-937e-955db5e56b44.jpg" width=250>

### Device name

S10e

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92

**Comment by agi** [comment]
I cannot reproduce anymore, so weird, I'll reopen if it happens agian.

**Comment by Nickoriginal** [comment]
You referrenced to this page from about:about? It sometimes causes an error for me.
