### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Reonine** [mozilla-mobile/fenix#20337]
### Steps to reproduce

1. Have several tabs open.
2. Open the tabs list (list view).
3. Close the tab on the bottom of the list.
4. An appearing message that the tab has been closed prevents you from closing the next tab from the bottom.

![IMG_20210712_174823](https://user-images.githubusercontent.com/87325099/125318788-783ffd80-e33a-11eb-99f0-9a8908ab6578.jpg)

### Expected behaviour

The message shouldn't delay me in closing the next tab. Either get rid of the appearing message or position it differently, so it doesn't obstruct the "close" icon of the next tab.

### Actual behaviour

See steps and photo. 

### Device name

Poco F2 Pro

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

89.1.1

**Comment by kbrosnan** [comment]
Duplicate #19166

**Comment by Reonine** [comment]
Thanks dir closing and sorry for duplicating! I wouldn't have found the other report though.
