### ISSUE TITLE
Add inactive tabs tray group

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20349]
This will be a section on the tabs tray of tabs that have not been used recently.

We need to set a variable number for what determines how long a tab needs to have existed without activity before it becomes "inactive" - we're starting with 4 days for now and we can alter that as we find a good number.

We should use the `lastAccess` property in the tray list to filter the tabs list into the two sections.

Linked JIRA: [FNXV2-17122](https://mozilla-hub.atlassian.net/browse/FNXV2-17122)

**Comment by Mugurell** [comment]
Created https://github.com/mozilla-mobile/fenix/issues/20507 for the telemetry.

**Comment by klint** [comment]
Could the inactive tabs feature be deactivated in the settings? 
Because there is a great loss of information in the inactive tabs (no screenshots and shorter site descriptions), information which would actually be needed more for inactive tabs (inactive tabs being older, memory may be failing and more information could help). 
This is suddenly breaking the way I'm using the tab tray (as kind of a "read later" list, with plenty of tabs). 
Thanks

**Comment by klint** [comment]
Hi again. I have a question: are inactive tabs being synced with other Firefox instances as well? I have no other device to check at the moment. Thank you.

**Comment by ericonr** [comment]
Something in the implementation here reset the setting to 30 days and is killing tabs for a bunch of folks: #20629

**Comment by ericonr** [comment]
Probably this line? https://github.com/mozilla-mobile/fenix/commit/69d630f46c35c8a062033edf071ef08c8a6834cb#diff-0e4df8f67ec9bfb7f74da9d75376085d7ecd5a5737322bf8375e387618bec5f3R349-R351

**Comment by ericonr** [comment]
Almost certainly this line... The defaults were changed to always close tabs older than one month and unset the manually close option, based on the inactive tabs feature being enabled or not.

As I explained in https://github.com/mozilla-mobile/fenix/issues/20650#issuecomment-892079948, this completely breaks Firefox's reliability for a multitude of users. I doubt almost anyone has a way to recover their old tabs.

**Comment by massic80** [comment]
It's not only a default value problem: I changed its value from the options and reverted it to "close manually" and the tabs have been wiped away anyway.

**Comment by tom-james-watson** [comment]
I don't understand the motivation for this feature at all. It doesn't seem like a very well though through change at all. 

There are several problems as it currently stands:

* "Reactivating" a tab now moves it out of its tab order.
* The tab tray shows inactive tabs at the bottom. If you have a lot of inactive tabs, you can't even see your active tabs without having to scroll up every time, which is awful UX. 
* Inactive tabs can't be swiped to close them.
* Inactive tabs don't have screenshots. 
* Most importantly, this does not seem like a useful feature. Why the arbitrary distinction between active and inactive? What exactly is the desired outcome here? This doesn't fit any mental model I have as a user and doesn't seem to help me in any way.

**Comment by WesleyAC** [comment]
I filed #20684 for adding an option to disable this feature.

**Comment by jonalmeida** [comment]
Hi folks, let me preface this by saying thanks for the feedback and bug reporting. This is still a nightly feature, so please expect bugs or unfinished features to land (but please keep reporting them!). 🙂 
> Because there is a great loss of information in the inactive tabs (no screenshots and shorter site descriptions), information which would actually be needed more for inactive tabs (inactive tabs being older, memory may be failing and more information could help).

This is great feedback, thank you!

> Hi again. I have a question: are inactive tabs being synced with other Firefox instances as well? I have no other device to check at the moment. Thank you.

@klint At this moment, that isn't in our roadmap.

> I changed its value from the options and reverted it to "close manually" and the tabs have been wiped away anyway.

@massic80 This is filed as https://github.com/mozilla-mobile/fenix/issues/20661

> "Reactivating" a tab now moves it out of its tab order.

@tom-james-watson  Selecting an inactive tab, should move it out of the inactive section and into it's prior position. If you can reproduce this behaviour, please file a bug, that would be helpful!

> The tab tray shows inactive tabs at the bottom. If you have a lot of inactive tabs, you can't even see your active tabs without having to scroll up every time, which is awful UX.

This is something I noticed as well: should we disable scroll to position if the last selected tab is now inactive? I'll bring this up with our team to see what the best interaction should be. Thanks for calling it out!

**Comment by tom-james-watson** [comment]
> This is something I noticed as well: should we disable scroll to position if the last selected tab is now inactive? I'll bring this up with our team to see what the best interaction should be. Thanks for calling it out!

I think the answer is to put the inactive tabs at the top of the tab tray, not at the bottom. If the newest tabs are at the bottom then the inactive, and therefore oldest, should be at the top.

I still don't understand the motivation for splitting tabs into active and inactive though. Is it to represent they are not in memory and will be loaded when you click on them? If so, just fading the tab in the tab list could work, though to be honest I don't think it's really important to show. Is it to somehow "archive" old tabs? If so, if I want that as a user then I can opt-in to having old tabs auto-closed, no? Personally, if I left a tab open then I want it there as a normal tab.

**Comment by klint** [comment]
Thanks for the replies.
But I agree with the previous comments, as I stated myself in another issue : logically, inactive tabs should be above active tabs.

Now, regarding syncing not being in the roadmap and other things: aren't we falling in the same trap as for collections? Collections are not synced (and I'm not using them for this reason) and it is a feature whose purpose is not understood by the active users community (daredevils like us using nightlies!).

Last point: there should be a option to not use inactive tabs (and keep as many active tabs as we want as longer as we want it). No more automatic deletion of info, please. Even not on nightlies 😉

**Comment by SoftVision-LorandJanos** [comment]
Hi @jonalmeida ! Verified as implemented on the latest Nightly (93.0a1 - 2021-08-13T05:08:25.050265).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.

**Comment by Matth7878** [comment]
Honestly I don't understand either this "feature"... At least if inactive tabs where just simply put in another tab (next to private and synced) as candidates to be quickly closed it would make more sense... Yet I don't think I would like to use it either...

I feel like this feature is to resolve a problem which only exists because Fenix want to create tons of tabs. Not creating tabs when it isn't asked for would have solved it...

It pains me that efforts are spend on that and not improving user experience based on what it's been requested for ages and multiple times. Especially when shortcomings push workarounds like this one. 😟
Some examples : top sites and collections improvement, better access to bookmarks / history, homepage, add-ons, and so on...

**Comment by albru123** [comment]
I would like to see the initial motivation for adding this feature. For me, a person that opens a lot of tabs, it's basically a daily tab shuffle with no upside whatsoever. From browser standpoint the tabs are inactive anyway (I think), so it doesn't really change anything aside from adding poor UX.
