### ISSUE TITLE
FNX-5413 ⁃ [Bug] Site permission string isn't wrapped

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2034]
Pixel 2, 04/25

![Screenshot (Apr 25, 2019 11](https://user-images.githubusercontent.com/102331/56747331-c19cd600-674b-11e9-9e52-a2c4e45b6c3a.png)UNITO-UNDERSCORE!07!UNITO-UNDERSCORE!57 AM)!

**Comment by kbrosnan** [comment]
dupe of #1416
