### ISSUE TITLE
setStartupMetrics perf fix is still a regression to COLD VIEW start up perf (~53ms)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20346]
We landed https://github.com/mozilla-mobile/fenix/issues/19147 to move `setStartupMetrics` to address a data quality issue and we saw a large regression of ~114ms on the Moto G5 https://github.com/mozilla-mobile/fenix/issues/19395#issuecomment-832873039. We landed a performance fix for this issue in https://github.com/mozilla-mobile/fenix/pull/19397#issuecomment-833965318 and I remeasured it https://github.com/mozilla-mobile/fenix/issues/19395#issuecomment-853448383 to find **it still regressed performance over the original implementation: 53ms on the Moto G5.**

This bug is to **fix the 53ms performance regression introduced by `setStartupMetrics` and its performance fix.** To reproduce the behavior, you can use my measurement notes from the prior comment:

> To measure this without interference from other code changes, I checked out the commit before the regression 2bd933054f0152fbc4bc3d3f2f276d9c41e42e08, checked out the commit after the regression 74047cdceb16990a6a843ce2824ca5b7696fb0d3, and cherry-picked the fix onto that commit, which applied cleanly (this change is available [on my branch](https://github.com/mcomella/fenix/tree/host-19395-measure-setStartupMetrics-fix)).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17233)

**Comment by rocketsroger** [comment]
I will be actively working with @badboy to optimize/rework how Fenix interact with Glean.  Once this process is completed, I will revisit this issue to see if we can move `setStartupMetrics` back to the original position or eliminate it completely.

I will update this issue when I have more information.

**Comment by mcomella** [comment]
Triage: removing P1. While the regression is large enough that it'd ordinarily be a P1, this issue is older than other similar size regressions (i.e. it's likely harder to address) and our P1 list is growing so we don't want it to become unmanageable.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807327

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
