### ISSUE TITLE
[Bug]: Toolbar on the homescreen ignores setting of the gesture "Scroll to hide toolbar"

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#20353]
### Steps to reproduce

1. Make sure gesture "Scroll to hide toolbar" is enabled. You can check it in Settings -> Customize -> Gestures
2. Go to Firefox home page.
3. Scroll it.

### Expected behaviour

Toolbar should hide during the scrolling or after it.

### Actual behaviour

Toolbar is not hidden during the scrolling or after it.

### Device name

Samsung Galaxy A20s

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90.1.1

### Additional information

Both toolbar locations - top and bottom are affected.
Private Home Page is too affected.
Firefox Beta and Nightly are too affected (tested on the Samsung Galaxy A20s).

https://user-images.githubusercontent.com/85299944/125456727-b6b482d7-4c76-44aa-ad16-ed602caaf82e.mp4

**Comment by Nickoriginal** [comment]
Note that the toolbar should hide immediately after scrolling beginning.

**Comment by kbrosnan** [comment]
The home screen is not a tab. This preference only applies to tabs where web content exists. One of the primary interactions in the home screen is to tap the address bar, hiding it in this case does not match our designs.
