### ISSUE TITLE
[Bug]: Swping on the addressbar does not work on the start (new) tab 

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#20358]
### Steps to reproduce

1. Have two tabs open.
2. Tap on [2] next to the address field.
3. Tap the (+) button.
4. Dismiss the keyboard.
5. Now, try to swipe left/right on the address field that says "Search or enter address" to switch the tab.

### Expected behaviour

I could switch to the previous tab.

### Actual behaviour

Swiping to the left/right shows the keyboard again.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

89.1.1

**Comment by SoftVision-LorandJanos** [comment]
Hi @HubKing ! Thank you for your report!

I could report the issue you described on the latest Release (90.1.1) and on the latest Nightly (91.0a1 - 2021-07-13T17:04:24.955).

I’m not sure however if this behavior is expected as you don’t open any page before you try to swipe between them.

Tested on the following devices:
- Samsung Galaxy Tab 3 (Android 9).
- Google Pixel 4 (Android 11).
- LG Nexus 6 (Android 7.1.1).

**Comment by SoftVision-LorandJanos** [comment]
As this issue is covered in #19839, I will close this one as duplicate. Also as described on the comment of the mentioned bug, the behavior is expected.
