### ISSUE TITLE
Recently closed tabs not cleared when using Delete browsing history on exit

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#20367]
### Steps to reproduce

1. Have everything apart from "Cookies and "Site permissions" selected in the "Delete browsing history on exit" menu
2. Visit some websites
3. Use the exit option to exit Firefox for Android
4. Open Firefox for Android and select the History option in the menu

### Expected behaviour

No recently closed tabs are available.

### Actual behaviour

Recently closed tabs are retained.

### Device name

Motorola Moto E4

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

89.1.1

### Additional information

Also reported by a user to SUMO in https://support.mozilla.org/en-US/questions/1343242.

**Comment by Amejia481** [comment]
👋🏽 
 @codrut-topliceanu this look the same issue as https://github.com/mozilla-mobile/fenix/issues/17986, lets coordinate efforts :)

It looks like when we delete tabs `store.dispatch(TabListAction.RemoveAllTabsAction)`, they are getting added into the `RecentlyClosedMiddleware` as `UndoAction.ClearRecoverableTabs` [see](https://github.com/mozilla-mobile/android-components/blob/642cde5c0de45e608d759deb95db0ff5aea2b1ca/components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt#L44).  

We should find a way to prevent that, maybe by adding some sort state to `RemoveAllTabsAction` to indicate these tabs are not recoverable, maybe:

```kotlin
data class RemoveAllTabsAction(val recoverable: Boolean = true) : TabListAction()
```

And preventing the `UndoMiddleware` from [adding them](https://github.com/mozilla-mobile/android-components/blob/642cde5c0de45e608d759deb95db0ff5aea2b1ca/components/feature/session/src/main/java/mozilla/components/feature/session/middleware/undo/UndoMiddleware.kt#L58) and subsequently the `RecentlyClosedMiddleware` adding [them to the db](https://github.com/mozilla-mobile/android-components/blob/642cde5c0de45e608d759deb95db0ff5aea2b1ca/components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedMiddleware.kt#L44).

**Comment by codrut-topliceanu** [comment]
For QA:
 - Please be aware that the erroneous behavior from the original comment also happens when using **Delete browsing data**. The PRs will fix both bugs.
 - Also bug reproduces even with  "Cookies and "Site permissions" selected.

**Comment by Amejia481** [comment]
👋🏽 
QA team  the fix is on `master`, would you mind helping us to verify if the issue is fixed, thanks in advance :)

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/21 following the steps provided.
