### ISSUE TITLE
[Bug]: ETP icon not displayed correctly when the toolbar is set to top on Tablets

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#20366]
### Steps to reproduce

1. Set the toolbar to be on Top.
2. Open a page (Twitter/cnn).
2. Wait for the ETP icon to be displayed.

### Expected behaviour

No visual issues are displayed, and the icon is right under the toolbar.

### Actual behaviour

The icon is displayed bellow the toolbar (check the screenshot)

### Device name

Huawei MediaPad M2 

### Android version

Android 5.1.1

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 

### Additional information

![Screenshot_2021-07-07-11-57-43](https://user-images.githubusercontent.com/58466444/125638461-58b1ee0a-9c90-4956-a404-51c0c7ad28be.png)

**Comment by Amejia481** [comment]
Just to make you aware, there is some work in progress to delete this popup on https://github.com/mozilla-mobile/fenix/issues/19886, we are targeting 92 not sure if it's worthwhile fixing it

**Comment by sflorean** [comment]
This is still reproducible on 91.0.0-beta 2.
