### ISSUE TITLE
ability to show/hide items shown in homescreen

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#20375]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
With more items being added recently jump back in, media tab and recently saved..the collections are getting pushed bottom and thus adding an extra scroll to access. Some of the new items are not required by all users so we need the option to show/hide the features (jump back in, recently saved, media tab, collection,top sites)

### How do you know that this problem exists today? Why is this important?
Difficult to access items

### Who will benefit from it?
the customisation will benefit all users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17253)

**Comment by TrianguloY** [comment]
Consider also the ability to reorder them, so instead of hiding you can move them to the bottom for occasional access.

**Comment by amedyne** [comment]
@Verdi and @vesta0 Some suggestions on the new features in Home.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1344124

**Comment by nershman** [comment]
From the home page click the three dots > customize home 

In that dialog there are options to disable jump back in and recent bookmarks.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809832

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
