### ISSUE TITLE
[Bug]: Video playback issue on youtube 360 video in Firefox android

### ISSUE THREAD

**Issue by gingerling** [mozilla-mobile/fenix#20378]
### Steps to reproduce

Go to https://heritagetrustnorthwest.org/higherford-mill/ using forefox android
Scroll to bottom of page
Try playing video

### Expected behaviour

Should show drone footage, 360 video so you can drag to move around the view. 

### Actual behaviour

Black space, occasional flashes of the video when you drag or adjust the playback time bar

### Device name

Oneplus nord and Samsung galaxy note)

### Android version

Andorid 11  (and older version on note)

### Firefox release type

Firefox

### Firefox version

90.11

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1720741

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
