### ISSUE TITLE
[Bug] [ASAP] 

### ISSUE THREAD

**Issue by pramod-lamsal** [mozilla-mobile/fenix#20390]
Nothing works in Firefox after new update it always shows same  error for all sites
![Screenshot_2021-07-16-08-10-44-611_org mozilla firefox](https://user-images.githubusercontent.com/85184632/125882703-908f41ec-ed9e-41fd-9afd-aeb975ef72f9.jpg)

**Comment by cadeyrn** [comment]
If you want that they fix your issue "ASAP" then you should provide some basic information at least, like your device model name, the Android version, Firefox version before and after the update and detailled steps to reproduce. And you should give this issue an useful title. Without some information for the developers it can only take longer to find and fix the cause.

**Comment by pramod-lamsal** [comment]
Device model : redmi note 8 
Android version ; 10
Miui 12 
That error page is always shown whenever you try to search anything .
This started to occur after latest update build 90.1.1 (Build #2015820747)

**Comment by kbrosnan** [comment]
This is an upstream problem. https://bugzilla.mozilla.org/show_bug.cgi?id=1668842 @agi is there any info that the user can provide to help diagnose this problem?

**Comment by agi** [comment]
Asked Zibi in 1675823
