### ISSUE TITLE
[Empty collection can be created

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20391]
### Steps to reproduce

1. Open a tab
2. Tap the ⋮ "More options button"
3. Tap "Select tabs" from the menu
4. Tap the "Add new collection" button ![image](https://user-images.githubusercontent.com/51314259/125927797-424f8e2b-8c9d-4a4b-a708-3a7aaa4ba87c.png)
5. Confirm the collection creation
6. Tap "View" from the confirmation snackbar

### Expected behaviour
• Shouldn't be able to create empty collection

### Actual behaviour
• Empty collection is created

### Device name
• OnePlus A3 (Android 6.0.1)

### Firefox version

• Nightly 92.0a1
• Beta 91.0.0-beta.1

### Additional information

► Video
![20210716-123517](https://user-images.githubusercontent.com/51314259/125928051-ae469d6f-89a8-46af-b485-f6c715de05d4.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17269)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 101.0a1 (2022-04-27) build.
Device used: Google Pixel 4 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible with the latest builds:
- latest RC (104.2.0).
- latest Beta (105.0b5).
- latest Nightly (106.0a1 - 2022-09-07).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812732

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
