### ISSUE TITLE
[Bug]: Flip rotation on fullscreen from landscape-primary to secondary takes no effect on screen.orientation

### ISSUE THREAD

**Issue by aurium** [mozilla-mobile/fenix#20405]
### Steps to reproduce

1. Open this page on your FF mobile:
    ```html
    <!DOCTYPE html>
    <html>
    <body style="height: 100vh; font-size: 8vw">
      <p id="debug"></p>
      <script>
        document.body.addEventListener('click', ()=> {
          debug.style.background = '#FF0'
          document.body.requestFullscreen()
        })
        setInterval(()=> {
          debug.innerText = `
          ${screen.orientation.type}
          ${screen.orientation.angle}deg
          `
        }, 200)
      </script>
    </body>
    </html>
    ```
2. Touch the screen to call `requestFullscreen()`.
3. Rotate from portrait to landscape-primary or secondary.
4. Flip you phone, like a coin, to the oposite landscape.
5. See the screen to flip, but no change on the `screen.orientation` data.

### Expected behaviour

The `screen.orientation` data should represent actual mobile position.

### Actual behaviour

It do not updates `screen.orientation` data if you do not turn to `portrait` between the rotation from one landscape to another.

https://user-images.githubusercontent.com/30254/126021134-96d673cf-0173-4171-89ad-3c44f26af9db.mp4

### Device name

Redmi MIUI 12.0.13

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90.1.1

**Comment by kbrosnan** [comment]
Uploaded code to https://jsfiddle.net/82az537g/

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1721738

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
