### ISSUE TITLE
[webcontent] dna logo missing

### ISSUE THREAD

**Issue by ShalokShalom** [mozilla-mobile/fenix#20407]
### Expected behavior

Visit https://github.com/Vivraan/godot-lang-support
🧬Symbol to be shown in mobile view.

![Screenshot_2021-07-18_08-54-08](https://user-images.githubusercontent.com/6344099/126058494-b65602b8-15f4-4aae-b6e3-eeb3846adbcf.png)

### Actual behavior

Symbol shows only in desktop view.

![1626591225300](https://user-images.githubusercontent.com/6344099/126058492-fe3888df-6625-4f53-8e16-c935616e50aa.jpg)

### Device information

* Android device: BlackBerry Key 2 LE
* Fenix version: 
![Screenshot_2021-07-18_08-51-17](https://user-images.githubusercontent.com/6344099/126058422-e1a46427-61db-4e6f-afa9-b0f58faba044.png)

**Comment by ShalokShalom** [comment]
https://github.com/Vivraan/godot-lang-support/issues/40#issuecomment-882431960

**Comment by sflorean** [comment]
I wasn't able to reproduce this on Pixel 3 (Android 12), the logo was displayed, build Nightly 7/30.
@ShalokShalom can you check also on Chrome? might be device related, and not browser related.

**Comment by ShalokShalom** [comment]
yeah, the same on Kiwi

Android 8.1 
Blackberry Key 2 LE

Thanks a lot
