### ISSUE TITLE
[Bug]: browser.tabs.query does not list tabs that are not loaded

### ISSUE THREAD

**Issue by utubo** [mozilla-mobile/fenix#20410]
### Steps to reproduce

1. Open some tabs.
2. Kill the firefox process.
3. Start firefox.
4. `browser.tabs.query({}).then(...)`

### Expected behaviour

browser.tabs.query lists tabs.

### Actual behaviour

browser.tabs.query lists no tabs.

### Device name

SH-M07 

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1721269

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
