### ISSUE TITLE
[Bug]: Firefox crash on https://webcamtoy.com/

### ISSUE THREAD

**Issue by michael9602** [mozilla-mobile/fenix#20411]
### Steps to reproduce

Open the website
Tap on ready button
Then tap on use my camera
At this moment Firefox will crash

### Expected behaviour

Firefox will crash

### Actual behaviour

Firefox crash

### Device name

Poco M2 pro arrow os

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.1

**Comment by Nickoriginal** [comment]
Hello, @michael9602!
_Not reproducible in:_
Firefox 90.1.1 (**Samsung Galaxy A20s**)
Firefox 91.0.0-beta.1 (**Samsung Galaxy A20s, Samsung Galaxy J2 Prime**)
Firefox Nightly 92.0a1 2021-07-18T17:06:55.361 (**Samsung Galaxy A20s**)
You can choose option "Camera" on https://permission.site/ and allow access to your camera to locate the issue (with site or your device)?

**Comment by Nickoriginal** [comment]
Also you can try [Firefox Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) and [Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to determine if it shows up there.

**Comment by kbrosnan** [comment]
Crash ID URLs are needed to understand what is causing the crash. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by kbrosnan** [comment]
Closing as incomplete. Need crash IDs to be useful.
