### ISSUE TITLE
FNX-5416 ⁃ [Bug] Private tabs remains open after the browser is closed

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2041]
## Steps to reproduce
Enable private browsing
Open some websites
Close Fenix
Reopen Fenix

### Expected behavior
Fenix is reopened freshly, on "normal browsing mode".

### Actual behavior
The private browsing is reopened, with all the previously tabs exposed. 

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by AaronMT** [comment]
I'm unable to reproduce this. Pixel 2 (9), same build.

![ezgif com-optimize](https://user-images.githubusercontent.com/102331/56758368-780cb500-6764-11e9-8de6-aff6e798ca7b.gif)

**Comment by Lululalu** [comment]
@AaronMT it's not reproducing for me anymore, and I don't know why (maybe I thought I closed Fenix, but I didn't), although private browsing is still enabled when Fenix is opened again.

**Comment by cadeyrn** [comment]
> although private browsing is still enabled when Fenix is opened again.

That's expected and really nice for everyone who always wants to use the browser privately.

**Comment by AaronMT** [comment]
Re-open if you can further reproduce.
