### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sullivan6666** [mozilla-mobile/fenix#20413]
provide support using all firefox extensions

**Comment by Nickoriginal** [comment]
Do you mean "all extensions from the desktop Firefox"? There is no way to do it. You can only choose between 18 recommended extensions, as stated [here](https://support.mozilla.org/kb/find-and-install-add-ons-firefox-android).
> You can install a limited number of extensions from the Recommended Extensions program to add features to Firefox for Android.

You can see all recommended add-ons [here](https://addons.mozilla.org/android/).

**Comment by kbrosnan** [comment]
If you want to try unsupported extensions you can use nightly. https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
