### ISSUE TITLE
Add link to current APK to download page

### ISSUE THREAD

**Issue by FreddyFeuerstein** [mozilla-mobile/fenix#20416]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Many people choose to not use google services for privacy and performance reasons. On the official download page, you can only find a download button that leads to the google play store. Furthermore, when you search for 'firefox apk' on duckduckgo, you will find many extremely outdated and forgotten mirrors and a ton of questionable download sites but this repo and the releases page only shows up on page 8 of the search results.

### How do you know that this problem exists today? Why is this important?
I think this is pretty self explanatory. The official downliad page (https://www.mozilla.org/en-US/firefox/new/) only has a google play link and all third-party mirrors are either sketchy or very outdated.

### Who will benefit from it?
All people who just want to download this app without the use of a bloated and not at all privacy concerned app store would benefit from this single extra line of html on the download page.

**Comment by FreddyFeuerstein** [comment]
This repository containing the source and releases of the mobile firefox took me over 3 days to find. I don't think that having a user needing to spend hours searching for a download of a program can be called user friendly. The average user probably would have never found this repository.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/11794
