### ISSUE TITLE
[Bug]: String "Deleting browsing data..." is incorrectly translated in Russian locale

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/fenix#20412]
### Steps to reproduce

1. Make sure "Delete browsing data on quit" is enabled.
2. Change your Firefox locale or system locale to Russian to reproduce this issue.
3. Tap on the "Quit" button in the three-dot menu.

### Expected behaviour

Russian string should be translated as "Удаляем данны**е** веб-сёрфинга..."

### Actual behaviour

Russian string is incorrectly translated as "Удаляем данны**х** веб-сёрфинга..."
<img src = https://user-images.githubusercontent.com/85299944/126077521-025eb97e-4e3b-43d8-a71d-46929c28afef.jpg width = 45%>

### Device name

Samsung Galaxy A20s

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90.1.1

### Additional information

Firefox Beta and Nightly are too affected.
Will be closed by merging #23368 or changing the translation in Pontoon.

**Comment by Nickoriginal** [comment]
https://pontoon.mozilla.org/ru/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=204934

**Comment by SoftVision-LorandJanos** [comment]
Hi @Nickoriginal ! Thank you for your report!
I'm getting the same string you are getting. However the string you were referring to in the above comment seems to be the same as the actual one, also I've checked [here](https://transvision.mozfr.org/?recherche=deleting+browsing+data&repo=android_l10n&sourcelocale=en-US&locale=ru&search_type=strings) as well, with the same result.
If it's incorrect on the mentioned translations as well, I too think it should be changed.
As I don't speak or understand the language, I can only base my theory on translating sites/apps, so I'll wait for a second opinion. Thank you!
Tested on the latest Nightly build (92.0a1 - 2021-07-22T05:11:19.498).
Devices used:
- Google Pixel 4 (Android 11).
- Samsung Galaxy Tab 3 (Android 9).
- LG Nexus 5 (Android 6.0.1).

**Comment by Nickoriginal** [comment]
Still reproducible in Firefox 93.1.0. Who knows Russian good enough to confirm my statement about the wrong translation?

**Comment by Nickoriginal** [comment]
Firefox 96.2.0
<img src=https://user-images.githubusercontent.com/85299944/150682025-a9be270c-6a17-456b-9634-02ab27b2c175.png width=50%>

**Comment by kirillaristov** [comment]
The phrase "Удаляем данны**е** веб-сёрфинга" is correct, and the phrase "Удаляем данны**х** веб-сёрфинга" is not. I'm Russian :)

**Comment by Nickoriginal** [comment]
Good, but, as said @cadeyrn, you must be registered at Pontoon to change the translation there. Hm...

**Comment by kirillaristov** [comment]
I have already made changes there..

**Comment by Nickoriginal** [comment]
Fixed in 97.1.0, thanks to @kirillaristov!
