### ISSUE TITLE
After entering fullscreen mode, Firefox always rotates to landscape when an <audio> node is playing

### ISSUE THREAD

**Issue by Toad06** [mozilla-mobile/fenix#20419]
### Steps to reproduce

- Download [these HTML samples](https://github.com/mozilla-mobile/fenix/files/6839454/samples.zip) and host them.
- Always hold your phone in portrait mode while testing.

---

- Run "firefox_audio_playing.html".
- Click "Set canvas to fullscreen", the canvas will be displayed in fullscreen, remaining in portrait mode. Audio also starts playing.
- Exit fullscreen without reloading the page and click "Set canvas to fullscreen" again. The canvas will be displayed in fullscreen, this time unexpectedly changing the orientation to landscape.

---

- "firefox_no_audio_playing.html" is quite the same file as "firefox_audio_playing.html", but audio never plays in this one, so the orientation always remains to "portrait".

### Expected behaviour

Firefox should have respected the current orientation of the device (portrait).

### Actual behaviour

Firefox changes the orientation to landscape. This can be really critical for stuff like games as this bug makes them quite impossible to play.

### Device name

Huawei P9 lite

### Android version

Android 7.0

### Firefox release type

Firefox

### Firefox version

90.1.1

### Additional information

The issue also happens in Firefox Nightly 92.0a1.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17292)

**Comment by Toad06** [comment]
Seems like the bug was introduced in version 86.x.

**Comment by Toad06** [comment]
Meh

**Comment by Toad06** [comment]
Still happening in Firefox Nightly 106.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811603

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
