### ISSUE TITLE
Temporary disable SearchTest#shortcutButtonTest test

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#20420]
SearchTest#shortcutButtonTest fails [here](https://github.com/mozilla-mobile/fenix/blob/41ba94b9517f9d61dcfc147c910de1ecc189f4fd/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt#L225) because of [a recent change](https://github.com/mozilla-mobile/android-components/pull/10599) that prepends the left to right mark for text in [DisplayToolbar].
So the text is now actually 
`\u200Educkduckgo.com/?q=mozilla` instead of the searched for 
`duckduckgo.com/?q=mozilla`

To not go on a slippery slope and add `\u200E` here now and who knows where also later I propose unblocking the AC bump by temporarily disabling this test until the AC functionality is improved.

CC @sv-ohorvath

**Comment by sv-ohorvath** [comment]
Thanks, Petru!

**Comment by sv-ohorvath** [comment]
The test was re-enabled, I'll close this now. Thanks again, Petru!
