### ISSUE TITLE
Firefox UI is broken in low resolution devices.

### ISSUE THREAD

**Issue by bonyjose** [mozilla-mobile/fenix#20426]
Firefox UI is broken in low resolution devices like realme c11, this device has 720p resolution and firefox UI is broken. A sample screen is attaching , as seen here, the low resolution is causing UI elements to be bigger/smaller and broken to be usable. Tried versions 90.1.1 and 92.0a1 .

![39468](https://user-images.githubusercontent.com/2097150/126197410-2c1ab9b3-03cc-4c9b-9ea8-18730533faf1.png)
![39464](https://user-images.githubusercontent.com/2097150/126197416-8517025f-9c7f-4593-be43-252bd9f4c6c4.png)
![39465](https://user-images.githubusercontent.com/2097150/126197417-824a60fb-54f5-4b40-a629-1aa1e97d09ba.png)

**Comment by amedyne** [comment]
@bonyjose What Android version do you have for this device?

**Comment by Nickoriginal** [comment]
Hello, @bonyjose!
**To compare:**
<img src = https://user-images.githubusercontent.com/85299944/126210632-abe1132a-b8a1-46db-91fa-25fe4629f001.png width = 49%> <img src = https://user-images.githubusercontent.com/85299944/126210651-afc3e62d-92c4-4dec-83d4-daca083c5cb8.png width = 49%>
My device, **Samsung Galaxy J2 Prime** has screen resolution 960x540 (lower than your device) and I don't see the issue on both devices.
UI elements become smaller on devices with a small screen and this is intended behaviour. The only thing that makes me suspicious [here](https://user-images.githubusercontent.com/2097150/126197416-8517025f-9c7f-4593-be43-252bd9f4c6c4.png) and [here](https://user-images.githubusercontent.com/2097150/126197417-824a60fb-54f5-4b40-a629-1aa1e97d09ba.png) that tab counter is not surrounded by white line as it should be in dark theme.
