### ISSUE TITLE
New Marketing push notifications - please don't

### ISSUE THREAD

**Issue by lordgurke** [mozilla-mobile/fenix#20429]
## User Story
To start: Normally, if an app sends unsolicited marketing push notifications, I will uninstall it without even blinking.
Last Firefox nightly started sending me push notifications, shortly after the update. At the moment, it only asks for it to be standard browser.
And I don't know, what would come next, because I muted this kind of notification in Android settings.
Because this is the only way to stop Firefox sending marketing notifications, I would challenge, if most users are aware of how to stop this.

So: Please, don't send unsolicited marketing messages! This annoys people and makes a very bad impression!
Invasive push notifications is the worst!

Instead, you should get prior consent from people. Just ask at first start if they want to receive "the latest news" or whatever, but please ask.
Someone who loves getting notified about those things can give consent and be happy, Someone who dislikes this kind of thing and wants the app to stay quiet, would decline and will be happy, too.
_To be honest: I would even question the benefits of marketing messages for an app, which already is installed. But I'm not the target audience for any kind of marketing, so..._

**I can't stress this too much: PLEASAE! No intrusive marketing notifications without PRIOR consent! Anything else is dubious and shady.**

**Comment by Nickoriginal** [comment]
I have to agree with you, these push notifications can irritate people, who would not know how to turn them off. They should appear less frequently.

**Comment by kbrosnan** [comment]
Asking the user to set a default browser is done on desktop and other major mobile browsers. It is generally shown that people who set Firefox as their default use Firefox more. This notification is only shown once. When it was implemented where swiping away was not considered dismissed. This has been corrected.

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20887
