### ISSUE TITLE
[Bug]: Scan button not shown for RTL locales

### ISSUE THREAD

**Issue by Xashyar** [mozilla-mobile/fenix#20439]
### Steps to reproduce

1. open a new tab
2. Observe there is no Scan option:

 <img src="https://user-images.githubusercontent.com/34171942/126348723-a18cdb55-5111-4f85-b70d-23e840b760e8.png" alt="Girl in a jacket" width="300"> 

### Expected behaviour

Scan option is shown as in LTR:

 <img src="https://user-images.githubusercontent.com/34171942/126349402-dc489e7b-59b1-41de-bc61-ae33d3cac562.png" alt="Girl in a jacket" width="300"> 

### Actual behaviour

Unable to capture QR-codes in RTL.

### Android version

Android 6.0

### Firefox release type

Firefox Beta

### Firefox version

90.0.0-beta.6

**Comment by SoftVision-LorandJanos** [comment]
Hi @Xashyar ! Thank you for your report!
I was able to reproduce the issue you described.
Tested with the latest Nightly (92.0a1 - 2021-07-22T05:11:19.498)
Device used: Google Pixel 4 (Android 11)

**Comment by Xashyar** [comment]
I'm no longer able to reproduce this as of 97.0 Beta.
