### ISSUE TITLE
[Bug] Media notifications are blank when the user starts/pauses the media from it

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#20434]
### Steps to reproduce

1. Open a page with media content, I had https://www.travelandleisure.com/trip-ideas/nature-travel/best-places-to-see-the-northern-lights?utm_campaign=travelandleisure_travelleisure&utm_content=bestofevergreen&utm_medium=social&utm_source=twitter.com&utm_term=60f5dab798e5200001402d12
2. Play the video inside the page.
3. Minimise Firefox, then from the media notification play or pause the video.
4. Observe the media notification.

### Expected behaviour

The media notification displays the title of the page, the URL, and the play/pause icon.

### Actual behaviour

The media notification displays only the Firefox title.

### Device name

OnePlus 5T

### Android version

 Android 10

### Firefox release type

Firefox Beta

### Firefox version

91.0.0-beta.2

### Additional information

* not reproducible on 7/19 Nightly
* reproducible on RC 90.1.2, 
* reproducible on RC 90.1.1 from PlayStore
* not reproducible 100%

https://user-images.githubusercontent.com/40694158/126285747-f1991ac5-883b-45ec-a4d6-5448a9f67246.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17303)

**Comment by lobontiumira** [comment]
I reproduced this issue again on Beta 91.0.0-beta.6 with Sony Xperia Z5 Premium (Android 7.1.1), on soundcloud.com.

**Comment by lobontiumira** [comment]
Reproducible also pn Nightly 94.0a1 from 9/24 with OnePlus 5T (Android 10).

**Comment by delia-pop** [comment]
This also occurs on 95.0.0-beta.6 (Build 2015847755) with LG G7 fit (Android 8.1.0). 

Pausing/Playing the audio stream from the Media Notification will cause both the lock screen and media notification to become blank. Only the "Play" button will be displayed, but with no functionality as the audio is playing but can no longer be paused from the media notifications.

https://user-images.githubusercontent.com/89388888/143455876-d7d8ba88-fdad-40a1-aa32-d6f5fe3eb45b.mp4

**Comment by karlcow** [comment]
Probably related https://github.com/webcompat/web-bugs/issues/70770
Firefox doesn't display the icon in the notification.
