### ISSUE TITLE
"tab closed" toast covering up top tab

### ISSUE THREAD

**Issue by JonahGroendal** [mozilla-mobile/fenix#20430]
After I close a tab, a "tab closed" toast message pops up at the bottom of the screen, covering up the tab at the top of the tab stack.

It's super annoying and I assumed it would be fixed by now but since it isn't I'm opening this issue.

It's a problem because after I close one tab I have to wait for the toast message to disappear before I can close (or open) the next tab.

**Comment by Nickoriginal** [comment]
Duplicate of #19166

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20394

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/19166
