### ISSUE TITLE
[Bug]: Everytime when I open the message page of Tweakers.net Firefox Nightly on Android crashes

### ISSUE THREAD

**Issue by deKoning** [mozilla-mobile/fenix#20435]
### Steps to reproduce

Make sure to be logged in to the website
Open https://gathering.tweakers.net/forum/list_discussions
The page crashes directly (version 92.0a1)

### Expected behaviour

The page should open and show an overview of messages

### Actual behaviour

The page seems to load for second or two and then crashes.

During the Firefox Crash is shows in Dutch 'Sorry, Firefox Nightly kan die pagina niet laden' or translated 'Sorry, Firefox Nightly can't load this page.

### Device name

Xiaomi Poco X3 NFC

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Device logs

https://crash-stats.mozilla.org/report/index/e5a048bf-dbca-4d74-bf2f-455590210720

**Comment by marcel263** [comment]
I cannot replicate with a created account and logged in

**Comment by kbrosnan** [comment]
This is a Gecko platform crash that is tracked in bz-1461724
