### ISSUE TITLE
An "add search engine" button

### ISSUE THREAD

**Issue by songsammy** [mozilla-mobile/fenix#20437]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
At old version, i could go to GitHub.com etc. and there is a button , somewhat like "add search engine" , but now I had to manually enter the search string. Not a problem for me, but I believe this can be improved.
### How do you know that this problem exists today? Why is this important?
I tried on  fenix 90.1.1   , feature not found.
I remember on 6x.x version, there's such feature, because i was using that version.
It is important, as many site has its own in-site search
### Who will benefit from it?
Everyone. When you browse on some site, you don't have to share it with that Gigantic search company.
What is more, it is more likely you get more relevant and reliable information from specific site, so users may want to customize the search engines.
To make the process easier, such button is needed.

### PS
You may prompt a dialogue box whenever there is a `<input name=q>`, asking the user whether to add this engine to the search bar.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/15985
