### ISSUE TITLE
[Bug] Gray overlay on top of browser view

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#20441]
### Steps to reproduce

1. Be in light mode
2. Go to a website (e.g. www.google.com)
3. See the difference between the white toolbar and the page itself

### Expected behaviour

There should be no gray overlay on the browser view

### Actual behaviour

There seems to be a grey/gray overlay on top of the site:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/126356450-551065b6-11c7-4192-be41-2a24290e7d64.png"> <img width="322" alt="image" src="https://user-images.githubusercontent.com/43795363/126356360-f56234a0-0d27-4ea6-89f3-74d9f1b9133b.png">

### Device name

Google Pixel 3

### Android version

Android 9

### Firefox release type

Firefox (also in beta, nightly, and master)

### Firefox version

90.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17313)

**Comment by kbrosnan** [comment]
Do you have any blue light blocker apps installed?

**Comment by TyroneSama** [comment]
This occurs for me on all new tabs. Hitting the "open new tab" button, then navigating back to the greyed-out tab, fixes it. Nightly 96.0a1 (also occurs on stable), Galaxy S8+, Android 9.

After opening:
![signal-2021-11-22-042816_002](https://user-images.githubusercontent.com/8174023/142845909-ddc5542a-aa3a-4f8e-a36f-9ce93370cf2c.jpeg)

After opening the "new tab" screen, then navigating back to the tab:
![signal-2021-11-22-042816_001](https://user-images.githubusercontent.com/8174023/142845916-f36f67f5-537c-403f-871b-c0c45cf8b86b.jpeg)

**Comment by plwt** [comment]
User feedback:- https://support.mozilla.org/en-US/questions/1377545

User feedback:- https://support.mozilla.org/en-US/questions/1382683

**Comment by Mugurell** [comment]
Asking for QAs help in finding the scenario for reproducing this.

**Comment by TyroneSama** [comment]
Still happening for me on a new device: Firefox 105.1.0, Galaxy S20 FE on Android 12. No addons installed.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807094

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
