### ISSUE TITLE
[Bug]: TopSites page count not updating 

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#20440]
### Steps to reproduce

1. Have 9 topsites available, thus needing two pages
2. Delete one topsite

### Expected behaviour

With 8 TopSites only one page should be available

### Actual behaviour

There are still two pages, the 2nd one is empty, the page indicator is still visible

### Device name

OneTouch 6

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

latest master

### Additional information

This bug was introduced by the fix for https://github.com/mozilla-mobile/fenix/issues/15499  -> PR: https://github.com/mozilla-mobile/fenix/pull/20189

Video of the issue : 

https://user-images.githubusercontent.com/60002907/126351860-0db08a08-0d30-4fb3-8553-3263031ad5f4.mp4

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly (92.0a1 20210728T05:08:41.498400).

Devices used: 
- Motorola Nexus 6 (Android 7.1.1)
- Samsung Galaxy Tab 3 (Android 9)
- Google Pixel 4 (Android 11)
- Huawei P9 Lite (Android 7.0).
