### ISSUE TITLE
[Bug]: Firefox background audio killed after using Custom Tabs 

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#20444]
### Steps to reproduce

Similar to #20360, also main Firefox process "normal" tabs are affected. Please see the testcase detailed in the mentioned bug

1. Play any media that will continue in the background
2. Put Firefox in background, ensure audio is still playing, which should  itself as a notification
3. Use a Custom Tabs enabled application. I used RedReader with Custom Tabs enabled in its settings.
4. Load any page through said application, and close it

### Expected behaviour

Audio from main Firefox not affected

### Actual behaviour

The audio not only gets paused, but system loses notification

### Device name

Samsung OneUI 3.1

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 (Build #2015823243)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17314)

**Comment by marcel263** [comment]
it also happens to running downloads, these get aborted

**Comment by marcel263** [comment]
not fixed.

**Comment by kbrosnan** [comment]
tracked as bz-1772837
