### ISSUE TITLE
A" search on this page" button

### ISSUE THREAD

**Issue by songsammy** [mozilla-mobile/fenix#20454]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I often read documents. Many times i want to jump to a specific chapter, on a long long page.
On Firefox desktop I clicked ctrl+f , but on Android i didn't figure out how.I didn't find the feature.
### How do you know that this problem exists today? Why is this important?
I am using fenix 90. Even now, i am using fenix to open this issue.
This is somehow important. I would appreciate it if it is implemented.

### Who will benefit from it?
Users who reads a lot, whose job was to view files

**Comment by marcel263** [comment]
Should be in the three-dot menu. Press the three-dot menu, then "find in page".
![Screenshot_20210721-185137_Firefox Nightly](https://user-images.githubusercontent.com/76437842/126528054-7d4ba485-f6da-4366-ba5b-480aa9174a12.png)
 Is it there like in the screenshot?

**Comment by kbrosnan** [comment]
This feature exists as the screenshot shows.
