### ISSUE TITLE
[Bug]: Device name defaults when re-launding firefox on android

### ISSUE THREAD

**Issue by wem77479** [mozilla-mobile/fenix#20455]
### Steps to reproduce

I customized me device name under sync settings and it will show up on other devices I'm syncing with the first time around.  When I re-launch firefox on my android it goes back to the default of "Firefox on Android" or something to that effect despite it still be configured in sync settings.  If I go into sync settings and edit name and type device name and OK and then do a sync the name shows up again on other sync'd devices correctly.  This is not an issue with my work and personal Windows 10 PC's...  I am running the latest version of Firefox as of this posting.

### Expected behaviour

Configured name should be used even when browser is re-launched.

### Actual behaviour

Default name is used until you bump it by going into edit the name (don't need to change it) and just click OK.

### Device name

Micrsoft Surface Duo

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90.1.1

**Comment by sflorean** [comment]
@wem77479 thank you for report! #17100 is covering the same issue, please follow the discussions there.
