### ISSUE TITLE
Remove `app_received_intent` probe

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20461]
I spoke with eliserichards and it doesn't appear anyone is using this. The perf team originally implemented it so we should remove it too.

**Comment by kbrosnan** [comment]
Is there any other work besides undoing https://github.com/mozilla-mobile/fenix/pull/12114/files ?

**Comment by mcomella** [comment]
@kbrosnan I think it'd actually be undoing https://github.com/mozilla-mobile/fenix/pull/11940/files. However, it may not be as simple as a `git revert` or equivalent manual process because some things may have been refactored as we built on this code.
