### ISSUE TITLE
Set ETP level to be more strict on a per-site basis

### ISSUE THREAD

**Issue by Carke** [mozilla-mobile/fenix#20460]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Currently ETP is a global setting that applies to all sites you visit, with the option of exempting certain sites where no ETP protections will be applied. I think it would be valuable to have the option to set ETP to be stricter on a per-site basis in a similar way to cookie permissions that exist in Page Info -> Permissions on desktop Firefox.

### How do you know that this problem exists today? Why is this important?

There is no method I'm aware of on fenix to customize this setting. You can observe the global nature of the ETP setting through the following procedure: Visit a website -> Tap the ETP shield on the address bar -> Select "Protection Settings" -> Change your settings (ex Standard -> Strict) -> Back out of the menu -> Open a different site -> Tap the ETP shield on the new site -> Select "Protection Settings" -> Observe that your changes from the previous site have persisted. 

This is important because there are some websites that use first party cookies to track users on their page and to modify page features or behavior on the basis of this tracking. There are also many websites where first party cookies are necessary for use of the site. Current ETP settings constrain user choice on this aspect of site behavior. Users currently face a choice where they must either:

1. Set their ETP to be as strict as needed for a minority of websites, but manually opt out (and therefore have no ETP) on sites where first party cookies are desired 

OR

2. Set their ETP to the level they would like for default sites, and have to tolerate the undesirable behavior by a minority of visited sites.

With this feature users would have more control over site behavior.

### Who will benefit from it?

Any user who visits sites that have a mix of desirable and undesirable first party cookie behavior.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17323)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807559

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
