### ISSUE TITLE
Bookmarks: Displays the full folder path

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#20474]
### What is the user problem or growth opportunity you want to see solved?
At the moment, only the current folder in which the bookmark is saved is displayed in the bookmark menu. Under certain circumstances, this can lead to confusion for example with sub-folders with the same name.
### How do you know that this problem exists today? Why is this important?
Displaying the full folder path could help.
### Who will benefit from it?
Anyone who has amassed numerous bookmarks and organized them in a folder structure.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17335)

**Comment by onemahon** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811812

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
