### ISSUE TITLE
[Bug]: "browser.search.with_ads" and "browser.search.ad_clicks" are not generated for Yahoo in the metrics ping

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20470]
### Steps to reproduce
1. Add Yahoo as a custom search engine (https://search.yahoo.com/search?p=%s)
2. Set it as the default search engine
3. Tap the URL bar and search for the word "Brasov"
4. Tap the first add 
![image](https://user-images.githubusercontent.com/51314259/126652217-d1a93276-c40a-4fd1-9406-7b6a130c2b9d.png)
5. Tap the URL bar and search for the word "Phone"
6. Tap the one of the Sponsored adds
![image](https://user-images.githubusercontent.com/51314259/126652356-646389c2-6b12-48d9-9ec1-eddb8b52565c.png)
7. Navigate to ro.yahoo.com
8. Tap the add displayed right bellow Yahoo's search bar
![image](https://user-images.githubusercontent.com/51314259/126652457-2524c481-fb87-4451-a391-ce5e8a38682e.png)
9. Generate the metrics ping

### Expected behaviour
The metrics ping should contain:
For step 3 `browser.search.with_ads"`
For step 4 `"browser.search.ad_clicks"`
For step 5 `browser.search.with_ads"`
For step 6 `"browser.search.ad_clicks"`
For step 7 `browser.search.with_ads"`
For step 8 `"browser.search.ad_clicks"`

### Actual behaviour
`"browser.search.with_ads"` and `"browser.search.ad_clicks"` are not generated for Yahoo in the metrics ping

### Device name
Google Pixel 3a (Android 11)

### Firefox version
Nightly 92.0a1 from 7/22

**Comment by Mugurell** [comment]
@AndiAJ Just to confirm, this is happening in both the old and in the updated telemetry?

**Comment by AndiAJ** [comment]
Yes, it happens on older builds as well.

Checked on the following Nightly builds:
• Nightly from 31st of July 2020
• Nightly from 1st of January 2021
• Nightly from 30th of June 2021

**Comment by Mugurell** [comment]
Thank you Andi!

If I'm reading [this Glam query](https://glam.telemetry.mozilla.org/fenix/probe/browser_search_with_ads/explore?app_id=release&timeHorizon=ALL) correctly we indeed never identified ads in yahoo search results.
But based on [this other Glam query](https://glam.telemetry.mozilla.org/firefox/probe/browser_search_with_ads/explore?aggregationLevel=version&channel=release&os=Windows&process=parent) never did desktop also.

**Comment by Mugurell** [comment]
Mike Kaply responded that we only record this data for built-in engines.
So it seems like since Yahoo isn't one, the current functionality works as intended.
