### ISSUE TITLE
[Bug]: Firefox 90.1.2 crashes the phone with some websites

### ISSUE THREAD

**Issue by theodolf** [mozilla-mobile/fenix#20485]
### Steps to reproduce

Go to (German news tv website):
https://www.daserste.de/information/politik-weltgeschehen/weltspiegel/videos/weltspiegel-video-1070.html
Scroll the website, click on any video link.

### Expected behaviour

Website should open, be usable.

### Actual behaviour

When clicking on links, Firefox crashes.
When scrolling, Firefox freezes.
When opening a link, Firefox shows a black screen.
Firefox freezes, then crashes the phone. Phone reboots.
This didn't happen with Firefox 89.1.1.
Firefox shows a black screen and freezes when I try to open the crash report / Socorro link.
I could only click on share. Hope the link is useful.

### Device name

Galaxy S4, model number GT-I9515

### Android version

Android 5.0.1

### Firefox release type

Firefox

### Firefox version

90.1.2

### Device logs

a29ef4e8-af7c-4629-9bdb-da1317151c07
<native crash>
* Socorro: https://crash-stats.mozilla.org/report/index/bp-14b04dee-99ef-4380-a0ea-241c20210720
* Socorro: https://crash-stats.mozilla.org/report/index/bp-8f89f9c4-4c7b-461d-b160-a2b3b0210720

### Additional information

I cleared all cashes, which didn't help.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1722068

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Hi @theodolf, does this happen on many pages, or just the one you linked to? Could you please check whether Firefox Beta or Nightly work any better for you?

**Comment by theodolf** [comment]
Hi jamienicol, I have just installed Firefox Beta 91.0.0-beta.3 and so far it has worked surprisingly well. 

I have experienced this described crash with many websites, but with this website it was absolutely reproducible. Although it hasn't always crashed at the same point.

**Comment by jamienicol** [comment]
@theodolf Glad to hear it! I think you are seeing the same issue as [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1720841) which I fixed a few days ago, but has not made it to the stable release yet. Apologies for the inconvenience caused. Maybe best to stick to beta in the meantime, and please file a new bug if you see any issues there!

**Comment by theodolf** [comment]
Hi, and thank you for taking care of it. I have installed Firefox Beta 91.0.0-beta.4 now. 
I have noticed that an websites where graphical elements are overlayed, a polygonal form is covering that overlay element. For example, a video player window that has a round button in the middle. That button will only become visible, when I zoom into the page. 
I can send you a screenshot, but I suppose you know what I mean.

**Comment by jamienicol** [comment]
@theodolf A screenshot would be great thanks. It sounds like something we're aware of and working on a fix, but would be good to confirm that there isn't something I'm missing.

**Comment by theodolf** [comment]
##![Screenshot_2021-07-27-22-31-25](https://user-images.githubusercontent.com/87871379/127317325-5b619268-dc7d-4d94-9fa1-f1e71d38fdf4.png)

**Comment by jamienicol** [comment]
Thanks for the screenshot and link. That indeed looks like the same issue as [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1721795) which I'm working on a fix for now.

**Comment by theodolf** [comment]
I have updated to Firefox release version 90.1.3 and Firefox Beta 91.0.0-beta.4 now.
Both are still having the issues that I have described in my previous post.
You can use the link above to reproduce. Thank your efforts.

**Comment by jamienicol** [comment]
This should be fixed in Firefox nightly, and will reach Beta 92 in around a week's time
