### ISSUE TITLE
Let user delete default folders in bookmarks

### ISSUE THREAD

**Issue by JonDous** [mozilla-mobile/fenix#20483]
Please let to delete default folders. I use Firefox only for mobile. What for should i see "desktop bookmarks" in my bookmarks?

Let us to delete or hide. Also to hide "tabs on other device". Why should I see them? My Firefox was updated on the same phone but now i see "tabs on _mydevice_". But I still using the same device, just updated Firefox. 
Not everyone wants to see these tabs and bookmarks. We need more flexibility.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17346)

**Comment by onemahon** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811813

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
