### ISSUE TITLE
[Bug]: File input does not open with MIME specifier in accept

### ISSUE THREAD

**Issue by jooadam** [mozilla-mobile/fenix#20489]
### Steps to reproduce

1. Visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
2. Click the file input in the demo with `accept="image/png, image/jpeg"`

### Expected behaviour

The file selector should open.

### Actual behaviour

The file selector does not open.

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90.1.2

**Comment by Mugurell** [comment]
@jooadam This could happen if the app doesn't have the storage permission needed to access files or there are no apps installed that could help in selecting a file for upload.
Can you please check that selector works for other browsers and the storage permission is granted for Firefox then try again?

For me everything works as expected:


https://user-images.githubusercontent.com/11428869/126946531-657dd46e-7596-45e1-a802-4481c4627e9f.mov

**Comment by jooadam** [comment]
@Mugurell The same input works as expected in Chrome. Firefox has access to the storage, and also note that this is specific to when the `accept` attribute contains a MIME specifier. In case of other values, like `*`, file extensions, or no `accept` specified, it works as expected.
