### ISSUE TITLE
Select multiple items on the Saved Logins screen

### ISSUE THREAD

**Issue by smammy** [mozilla-mobile/fenix#20499]
### What is the user problem or growth opportunity you want to see solved?

It currently takes _4n_ taps to delete _n_ accounts from the Saved Logins screen. This makes burdensome to perform "housekeeping" on the logins that Firefox is saving (and often syncing).

### How do you know that this problem exists today? Why is this important?

Long-pressing an item on the Saved Logins screen does nothing and there is no overflow menu on the Saved Logins screen that could be hiding a "multiple select" action.

This is important because people who have been saving and syncing passwords for many years often accumulate passwords that they would prefer not to continue to store and sync. Doing regular housekeeping has several benefits:

1. Users can remove sensitive passwords (e.g. bank passwords) that they inadvertently saved.
2. Users can remove incorrect logins/passwords that they accidentally saved.
3. Users can remove logins/passwords for accounts they have closed and for sites that no longer exist.

### Who will benefit from it?

* Users with disabilities such as anxiety or ADHD who benefit from an "uncluttered" digital workspace.
* Users who wish to reduce their "attack surface" by not storing more security-sensitive data than necessary.
* Users who often encounter useless auto-fill offers (e.g. for closed accounts or with incorrect account information) and wish to correct this in one fell swoop rather than little by little.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17355)

**Comment by MarvinMep** [comment]
I tried to delete them via Firefox for desktop and Firefox Sync, but it seems that Sync doesn't work when all accounts are deleted. Now there's no account saved on desktop and hundreds of them on Android.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810632

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
