### ISSUE TITLE
[Bug]: status bar icons not visible in dark theme custom tabs

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#20494]
### Steps to reproduce

Select the theme as dark
Open any link which opens in custom tab
Status bar is white...icons are no longer visible

### Expected behaviour

Status bar icons should be visible

### Actual behaviour

Status bar is white and icons not visible

### Device name

asus rog 3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Additional information

![Screenshot_20210724-200108636](https://user-images.githubusercontent.com/58127841/126871764-fd6b8b17-0e9e-4f9a-be84-7980615492ef.png)

**Comment by marcel263** [comment]
The icons are visible on the screenshot. Please explain what is supposedly not present?

May be related to #20094

**Comment by Nickoriginal** [comment]
I think it is about this area, [here](https://github.com/mozilla-mobile/fenix/issues/20494#issue-952086577) it is completely white.
<img src = https://user-images.githubusercontent.com/85299944/126895669-aca51d6f-285f-4d7f-bae5-4d6098de62d1.png width = 45%>

**Comment by Mugurell** [comment]
I think this might be an issue with the custom rom.
@sheikh-azharuddin Can you try the same scenario with oher browsers?

**Comment by sheikh-azharuddin** [comment]
> I think this might be an issue with the custom rom.
> @sheikh-azharuddin Can you try the same scenario with oher browsers?

I checked in firefox normal version(screenshot below)...in dark theme the status bar icons are visible...seems a bug introduced in nightly since last few updates..I am pretty sure it was fine before...

![Screenshot_20210726-162126](https://user-images.githubusercontent.com/58127841/126978146-7c9dc89b-01e3-4d48-93d9-ff64bfe07598.png)

**Comment by Nickoriginal** [comment]
Why you closed that? Looks like this regression was not fixed for Nightly and was backported in stable Firefox.

**Comment by sheikh-azharuddin** [comment]
> Why you closed that? Looks like this regression was not fixed for Nightly and was backported in stable Firefox.

It's no use only...seems mozilla is only focussed on aesthetic items yet they don't take user feedback....

So I closed...better than being closed by stale bot after few weeks😕
