### ISSUE TITLE
[Bug]: Startpage.com custom search engine's favicon missing

### ISSUE THREAD

**Issue by SinTan1729** [mozilla-mobile/fenix#20490]
### Steps to reproduce

1. Add Startpage.com as a custom search engine with the search string "https://www.startpage.com/do/dsearch?query=%s".
2. Try to make a search using it.

### Expected behaviour

Favicon should be shown in the URL bar.

### Actual behaviour

Favicon is not shown.

### Device name

OnePlus Nord CE 5G

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Additional information

Adding Brave Search as a custom search engine does show the favicon, so it's an issue specific to Startpage.com. I have added some screenshots below showing both Startpage.com missing a favicon and Brave Search having one.
![Startpage.com](https://user-images.githubusercontent.com/35728385/126839891-c865389c-f4df-4ddb-bb54-5f3dcb35c85e.jpg)
![Brave Search](https://user-images.githubusercontent.com/35728385/126839895-ff50786c-a472-414d-9a53-6aa2d63dd741.jpg)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/7491
