### ISSUE TITLE
[Bug]: Uncontrolled/fast scrolling on zoom-in gesture on sites with zoom locked

### ISSUE THREAD

**Issue by ololuki** [mozilla-mobile/fenix#20501]
### Steps to reproduce

1. Open page when zoom-in gesture gesture is blocked - when try to zoom in by touching screen with two fingers and increase distance between these fingers the page does not zoom-in.
Exaple page: https://support.mozilla.org/pl/kb/nowosci-w-firefoksie-dla-androida?as=u&utm_source=inproduct&redirectslug=nowosci-w-aplikacji-firefox-dla-androida-w-wersji-79&redirectlocale=pl
2. Try to zoom in with two fingers placed vertically and increase distance between them.
2a. When only one of the fingers is released from screen then page position immediately jumps to the seconds finger that stiil touches screen. https://youtu.be/kULJ0rqfi2I?t=26
2b. When two fingers are released almost simultanuously then screen starts to scroll vertically very fast. The velocity is proportional to the distance made by fingers during zoom-in gesture. https://youtu.be/kULJ0rqfi2I?t=59

### Expected behaviour

When zoom-in is locked on page then zoom-in gesture should be ignored and page should not jumping or scrolling with uncontrolled manner.

### Actual behaviour

After zoom-in gesture the page jumps or fast scrolls with uncontrolled manner on pages with zoom-in locked.

### Device name

Xiaomi POCO X3 NFC 6/64GB M2007J20CG

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90.1.2 build #2015823035

**Comment by Mugurell** [comment]
The same happens on `GeckoView Example`
Seems like a browser bug.
Moving to Bugzilla.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1722262

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
