### ISSUE TITLE
ab8b11fa-f4bd-4758-b6f1-a688ab091ced <native crash> ---- <native crash>

### ISSUE THREAD

**Issue by Nike156** [mozilla-mobile/fenix#20505]
Site: duckduckgo.com (any search in this site - crash)

**Comment by Mugurell** [comment]
@Nike156  Can you please refer to https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information and provide more details about the crash you're seeing ?
A Socorro link would be great.
Providing a logcat containing the error and details about the Firefox app (what version are you using) and the device you're using is also great.

**Comment by kbrosnan** [comment]
Closing as incomplete. If the crash IDs can be provided we can reopen.
