### ISSUE TITLE
[Telemetry] Inactive tabs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#20507]
## Description & Product Manager / Data Scientist User Story
As a Product Manager I want to collect telemetry data on how the "Inactive tabs" feature is used.
## What questions will you answer with this data?
- How useful is the "Inactive tabs" feature.

## Acceptance Criteria
- [x] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology - https://mozilla-hub.atlassian.net/browse/DS-1657
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

https://mozilla-hub.atlassian.net/browse/FNXV2-17054

**Comment by Mugurell** [comment]
I saw that the inactive tabs feature is now also expandable / collapsible (after https://github.com/mozilla-mobile/fenix/pull/20687, thanks Jonathan!) so looked into adding the new probes.

One thing that I want to sync about with @vesta0, @jonalmeida , @codrut-topliceanu is whether we need to differentiate on the source of the tabs.
A tab can now be open / closed from:
- tabs tray
- tabs tray -> inactive tabs
- tabs tray -> inactive tabs -> recently closed tabs

Should these be the same events or should we maybe include the source of the event (tabs tray / inactive tabs / recently closed tabs)?

**Comment by jonalmeida** [comment]
> Should these be the same events or should we maybe include the source of the event (tabs tray / inactive tabs / recently closed tabs)?

Adding a source of the event sounds like a good idea to me. 🙂

**Comment by Mugurell** [comment]
Looked into adding support for the "Recently closed tabs" to also inform from where the user is coming to open/close tabs, (eg: from the tabs tray or from history) but saw there's no telemetry for that feature yet.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest Nightly 93.0a1 8/25 using a Google Pixel 3a (Android 11).
@Mugurell what was the decision in regarding "Recently closed" ? 
Should the `"source"` related changes be applicable when opening a tab from the "Recently closed" section as well ❓ 

✔️ `inactive_tabs_expanded` and `inactive_tabs_collapsed`
Ping -  4766d574-fa95-490d-815f-aa7afa77adcc
```
{
          "category": "tabs_tray",
          "name": "inactive_tabs_collapsed",
          "timestamp": 14926
        },
        {
          "category": "tabs_tray",
          "name": "inactive_tabs_expanded",
          "timestamp": 15979
        }
```
✔️ Tabs tray - `opened_existing_tab`
Ping - 61d47e1c-667f-447c-9ef3-ba4d461b1dd2
```
{
          "category": "tabs_tray",
          "extra": {
            "source": "Tabs tray"
          },
          "name": "opened_existing_tab",
          "timestamp": 2465
        }
```
✔️ Inactive Tabs `opened_existing_tab`
Ping - ec9b2f9c-ce93-4d65-b878-ece91a112c4e
```
{
          "category": "tabs_tray",
          "extra": {
            "source": "Inactive tabs"
          },
          "name": "opened_existing_tab",
          "timestamp": 791
        }
```
❓  Recently closed - `opened_existing_tab`
Ping - 169039e9-5104-4f3c-a248-0cb37fa496c6
```
{
          "category": "tabs_tray",
          "name": "inactive_tabs_recently_closed",
          "timestamp": 1732
        }
```

✔️ Tabs tray - `closed_existing_tab`
Ping - 8f997530-a243-4fe4-a618-9a857c00c483
```
{
          "category": "tabs_tray",
          "extra": {
            "source": "Tabs tray"
          },
          "name": "closed_existing_tab",
          "timestamp": 3066
        }
```
✔️ Inactive Tabs - `closed_existing_tab`
Ping - 373987f6-d4fe-4c58-9ef7-479047fbdfac
```
{
          "category": "tabs_tray",
          "extra": {
            "source": "Inactive tabs"
          },
          "name": "closed_existing_tab",
          "timestamp": 4769
        }
```

⛔  Recently closed - `closed_existing_tab`
N/A as far as I'm concerned

**Comment by AndiAJ** [comment]
Just synced up with @Mugurell, for the "Recently closed" section this shouldn't be applicable for the moment.
**Based on this, I'll mark this matter as fixed**

**Comment by Mugurell** [comment]
Thank you Andi! There was a discussion started about similar telemetry for the "Recently closed" screen but there is no telemetry currently so it will need a bigger change as part of a separate ticket. Will check with Amedyne about this.

**Comment by eliserichards** [comment]
PR: https://github.com/mozilla-mobile/fenix/pull/20508
