### ISSUE TITLE
Tests failing wiht latest Robolectric/mockk

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#20506]
PR #19665 is going to update Robolectric and mockk.

The following tests seem to fail with that setup:
* TrackingProtectionExceptionsViewTest.`binds empty list to adapter` (updateData() was not called)
* TrackingProtectionExceptionsViewTest.`binds list with items to adapter` (updateData() was not called)
~~* ShareViewModelTest.`test loadDevicesAndApps` (expected:<1> but was:<0>)~~ DONE
~~* PwaOnboardingObserverTest.`GIVEN cfr should not yet be shown WHEN installable page is loaded THEN counter is incremented` (Settings().incrementVisitedInstallableCount()) was not called)~~ DONE
~~* PwaOnboardingObserverTest.`GIVEN cfr should be shown WHEN installable page is loaded THEN we navigate to onboarding fragment` (Settings().incrementVisitedInstallableCount()) was not called)~~ DONE

**Comment by csadilek** [comment]
Fixed all tests in https://github.com/mozilla-mobile/fenix/pull/19665 before landing.
