### ISSUE TITLE
Phone reboots on Firefox start on Android 5.0 HTC m8

### ISSUE THREAD

**Issue by ranpel** [mozilla-mobile/fenix#20510]
### Steps to reproduce

Latest Issue - As of last update
1.  Open browser
2. Select a link
3. Phone Reboots
4. Every time

### Expected behaviour

1.  The phone should not reboot.
2. I can use the browser

### Actual behaviour

The phone reboots.

### Device name

htc m8

### Android version

5.0.2

### Firefox release type

Firefox

### Firefox version

90.0.2 (maybe)

### Additional information

I can't get to the version of firefox because firefox keeps rebooting my phone.

**Comment by ranpel** [comment]
Restored to 89.1.1 and working fine.

Also, a few versions back the system nav menu doesn't go away and hides the browser nav bar.  perfectly annoying making me backout and go back in in order to use the nav bar.

thing's are unraveling quickly, folks.

**Comment by Nickoriginal** [comment]
Uploading 20210727_181345_001.mp4…

**Comment by Nickoriginal** [comment]
Might be related to [#5663](https://github.com/mozilla-mobile/fenix/issues/5663), but here is issue with clean Android (the reporter did not specified if it is custom Android firmware)

I remember that I had the same problem (Firefox reboots phone) in branch 84, but it was fixed later.

**Comment by Nickoriginal** [comment]
Not reproducible in Firefox 90.1.2, 91.0.0-beta.4 on Samsung Galaxy A20s (Android 11)

**Comment by RICCIARDI-Adrien** [comment]
I get a quite similar issue on my tablet (the only difference is that it reboots only once, then Firefox needs to be opened manually to trigger another reboot).
The reboot was happening almost immediately with Firefox version 90.1.1, now it takes several minutes to happen with Firefox version 90.1.2. Some CSS is also corrupted on websites that were successfully displayed before, like GitHub.
I'm using a stock Android 5.0.2 on a Samsung Galaxy Tab 4 tablet (model SM-T530) with kernel 3.4.0.

**Comment by kbrosnan** [comment]
If this is still a problem we need a log of the phone when it hits this problem. See https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information for details on how to collect the logs.

**Comment by RICCIARDI-Adrien** [comment]
I heavily used Firefox with a lot of websites and playing YouTube videos and I did not get any single crash since updating to Firefox 90.1.3, so for me this problem is solved. The corrupted graphics are still there but they do not belong to this ticket (and they are not an important problem).

**Comment by Nickoriginal** [comment]
You can leave your feedback about corrupted graphics [here](https://github.com/mozilla-mobile/fenix/issues/19783) and try Nightly because it can resolve your problem.

**Comment by Nickoriginal** [comment]
Also @RICCIARDI-Adrien and @ranpel download the latest Fenix [91.1.0](https://github.com/mozilla-mobile/fenix/releases/tag/v91.1.0) and test it for crashes.

**Comment by RICCIARDI-Adrien** [comment]
I intensively tested Fenix 91.1.0 for several days and I noted zero crash, congrats !
