### ISSUE TITLE
[Bug]: Spike in `search.default_engine.submission_url` errors (Invalid Overflow)

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/fenix#20513]
We're seeing a spike in errors for the `search.default_engine.submission_url` metric since 2021-07-11.
This applies to the stable release.
The error is a "Invalid Overflow", meaning values stored are [longer than 100 characters](https://mozilla.github.io/glean/book/reference/metrics/string.html#limits).
See [this query](https://sql.telemetry.mozilla.org/queries/74333#185794).

Data longer than 100 characters is truncated at 100 characters, so you will still see data, but truncated.
Did anything about the values in use change recently?

**Comment by kbrosnan** [comment]
@eliserichards can you have a look or find someone to delegate to?

**Comment by badboy** [comment]
[Query focused on that metric only](https://sql.telemetry.mozilla.org/queries/81579?p_appid=org_mozilla_firefox&p_metric=%5B%22search.default_engine.submission_url%22%5D#202286)

There's still an increase.
Increase is less visible over the 30 day span, but it's very visible over 90 days.
Given that data is coming in truncated I'm not too worried about the data being useless.
Is this metric part of any dashboard or queries that are looked at regurlarly?

We do have a new [URL metric type](https://mozilla.github.io/glean/book/reference/metrics/url.html) that we might switch this metric too (though it's not yet possible to use that on Android).

**Comment by eliserichards** [comment]
It would be fantastic to switch to the URL metric type once that's available!

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/22787.
Verified in https://github.com/mozilla-mobile/fenix/issues/22879.
