### ISSUE TITLE
[Telemetry] Renew perf telemetry probes 

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#20518]
Related to #20516 

Breaking out renewal for performance telemetry probes.
Doc: https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit#

**Comment by mcomella** [comment]
We decided which probes to renew and remove in https://github.com/mozilla-mobile/fenix/issues/20520#issuecomment-890171611 and subsequent comments.

**Comment by mcomella** [comment]
This should be addressed by https://github.com/mozilla-mobile/fenix/commit/700033ee76c92fec1ee7b71df9f17d09aafdcd1f.
