### ISSUE TITLE
Remove redundant coroutine dispatchers in tests

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#20524]
Remove redundant coroutine dispatchers in our tests: https://searchfox.org/mozilla-mobile/search?q=maincoroutinerule%5C%28%5B%5E%29%5D&path=&case=false&regexp=true

https://github.com/mozilla-mobile/android-components/pull/10605 is already removing these in AC.

**Comment by Rishavgupta12345** [comment]
Hi, can I work on this issue?

this is my first contribution.

**Comment by prateek-singh-3212** [comment]
Hello @eliserichards,
I would to work on this issue and I would like to know that mozilla android is taking part in [hacktober fest](https://hacktoberfest.digitalocean.com/)?

**Comment by Alexandru2909** [comment]
Can I work on this issue?

**Comment by Alexandru2909** [comment]
Closed by [23055](https://github.com/mozilla-mobile/fenix/pull/23055)
