### ISSUE TITLE
Renew performance probes (July 2021)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20520]
The following probes are up for expiration:
```
start_reason_process_error
start_reason_activity_error

Startup.timeline:
  framework_primary
  framework_secondary
  framework_start_error
  framework_start_read_error
  clock_ticks_per_second_v2

perf.startup:
 cold_main_app_to_first_frame:
 cold_view_app_to_first_frame
 cold_unknwn_app_to_first_frame
 application_on_create
 app_on_create_to_glean_init
 app_on_create_to_megazord_init
 app_on_create_to_setup_in_main
 home_activity_on_create
 home_activity_on_start
 home_fragment_on_create_view
 home_fragment_on_view_created
 base_bfragment_on_create_view
 base_bfragment_on_view_created

storage.stats:
 query_stats_duration
 app_bytes
 cache_bytes
 data_dir_bytes
```

We should renew them fast before we miss a release if we're still interested in them. Though we may want to transfer ownership of `storage.stats` to the fenix team since we don't actively track it – the main problem we have there is that we don't know how much is too much disk space.

**Comment by mcomella** [comment]
eliserichards put up a PR that should make this easier: https://github.com/mozilla-mobile/fenix/pull/20519

**Comment by MarcLeclair** [comment]
We've established that we would keep  the following probes from `perf.startup`:

````
cold_main_app_to_first_frame:
 cold_view_app_to_first_frame
 cold_unknwn_app_to_first_frame
 application_on_create
````

We also decided to keep all of `storage.stats`  and remove  `Startup.timeline`

**Comment by mcomella** [comment]
We'll also keep:
```
start_reason_process_error
start_reason_activity_error
```

As they monitor errors for the `cold_*_to_first_frame` probes.

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/20596 for the probe removal.

**Comment by mcomella** [comment]
I created a commit with our needed renewal https://github.com/mcomella/fenix/commit/d670e3096341a5505d2d6702b5f9ca4919c63086 based on eliserichards' PR: https://github.com/mozilla-mobile/fenix/pull/20519 I'm discussing with eliserichards about who should take care of merging this.

**Comment by mcomella** [comment]
Dupe https://github.com/mozilla-mobile/fenix/issues/20518 (because all of the commits in my PR point at that issue even though this one has more info).
