### ISSUE TITLE
[Bug]: Japanese input methods does not work  correctly on uBlock Origin

### ISSUE THREAD

**Issue by hokonch** [mozilla-mobile/fenix#20534]
### Steps to reproduce

1. Use Japanese keyboard of Gboard or Google Japanese input
2. Open uBlock Origin settings
3. Move My filters
4. Type

### Expected behaviour

See the screen recording below

### Actual behaviour

See the screen recording below

### Device name

Google Pixel 3a

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.2

### Additional information

- Gboard version: 10.7.05.377032818-release-arm64-v8a
- This issue is not reproduced on [Reference Browser](https://github.com/mozilla-mobile/reference-browser).
- This issue has been around since the release of Fenix, according to my memory.

https://user-images.githubusercontent.com/54430032/127180914-37cc4324-6d2d-460e-abfc-8e175cd54ff7.mp4

**Comment by makotokato** [comment]
Hmm, it uses CodeMirror. I don't know whether this is CodeMirror bug or GV bug.  So I filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1724439

**Comment by kbrosnan** [comment]
Closing as an upstream Gecko issue.
