### ISSUE TITLE
FNX-5422 ⁃ [Bug] Quick Action Sheet should collapse when Find in Page is launched

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#2054]
## Steps to reproduce
1. Expand quick action sheet
1. Launch find in page

### Expected behavior
Quick action sheet collapses

### Actual behavior
Quick Action sheet is behind find in page

### Device information
* Android device: ?
* Fenix version: ?

**Comment by sv-ohorvath** [comment]
Verified as fixed on the latest Nightly 190703 (7/3 build).
Devices: Pixel 3 (Android 9), Nexus 5 (Android 6)
