### ISSUE TITLE
[Bug]: Unable to install any XPI (signed) on FF Nightly (Android)

### ISSUE THREAD

**Issue by null-von-sushi** [mozilla-mobile/fenix#20545]
### Steps to reproduce

Method 1:
1. Port an extension of your choosing to Firefox
2. Sign it using the official methods, and chose to distribute it yourself
3. Download the signed file and copy it to your Android device
4. Try to tap the file in local storage

Method 2 (because of [this](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)):
1. Port an extension of your choosing to Firefox
2. Sign it using the official methods, and chose to distribute it yourself.
3. Go to the AMO page for the addon. The URL should have numbers instead of a name.
4. Try to add it to a collection.

### Expected behaviour

Method 1:
Firefox should be displayed, and upon choosing to open with firefox the user should be prompted to install the addon.
Alternatively, a menu under the settings for 'Install Addon from file' should exist

Method 2:
The Extension should be added to the collection, so that it may finally be installed.

### Actual behaviour

Method 1:
Firefox is not an option. The workarounds using HTML files and links to XPI files do not seem to work, presumably because storage access has changed since.
There is no way to install the addon.

Method 2:
An error is shown upon trying to add it to a collection: `Invalid pk or slug "2714235" - object does not exist.`. The user is unable to install the extension.

### Device name

OnePlus 8 Pro, Samsung Galaxy Tab S7+

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Device logs

N/A

### Additional information

Please note #14034 is NOT related. Despite the creative name, the bug was closed without ever providing a solution to the issue. It only added a very roundabout way of installing addons from the AMO repository. 

Despite signing the addon for self-hosting, not even th developer version of Firefox has the ability anymore to install arbitrary extensions. This makes it rather impossible to install a wide variety of extensions not hosted on AMO for one reason or another. 

Please note that compliance with the addon signing policy does not indicate endorsement. This issue is simply about not being able to install an extension at all, not about voicing disagreement with the centralized signing process.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/17591
