### ISSUE TITLE
Tab title changed by javascript becomes blank

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#20546]
### Steps to reproduce

Go to any website that changes the tab title through javascript. For example, a wikipedia link that redirects: https://en.m.wikipedia.org/wiki/Emergent_behavior
Also happens on github, if you go to https://github.com/mozilla-mobile/fenix/issues/new/choose and click get started

### Expected behaviour

The correct tab title is set

### Actual behaviour

The tab title is not set and the page url is displayed instead.

### Device name

Huawei Nova 6

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17379)

**Comment by mobd** [comment]
This is still reproducible

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812833

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
