### ISSUE TITLE
Opening homescreen shortcuts takes noticeably longer than opening the app icon

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20558]
## Steps to reproduce
- Add a homescreen shortcut
- Stop the app
- Launch the app via the app icon, note the time
- Hit the app switcher button and swipe closed the app
- Launch the app via the homescreen shortcut

### Expected behavior
Both app launches take an equal amount of time

### Actual behavior
Launching the homescreen icon takes longer. Here's a video: [device-2021-07-28-124653.mp4.zip](https://github.com/mozilla-mobile/fenix/files/6896392/device-2021-07-28-124653.mp4.zip)

Notes:
- the video is of a debug build: **the delay will be shorter and possibly negligible in release variants**
- iirc, VIEW intents take longer to get to the first frame than MAIN intents. This may be that issue, as opposed to an issue specifically with homescreen shortcuts

### Device information

* Android device: P2
* Fenix version: e2af42a49768fc91423e5e872ca18c222463718b with my local async nav graph changes (PR #20176)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17389)

**Comment by mcomella** [comment]
In `SettingsPrivacyTest.launchLinksInPrivateToggleOffStateDoesntChangeTest`, we recreate the `HomeActivity` twice when launching via a homescreen shortcut (I'm guessing this is HOT/WARM): maybe that's why this operation takes so long.

**Comment by mcomella** [comment]
Triage: probably still a problem.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807328

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
