### ISSUE TITLE
App share screen | Share to firefox dropdown menu for sharing to other devices

### ISSUE THREAD

**Issue by aha999** [mozilla-mobile/fenix#20553]
### What is the user problem or growth opportunity you want to see solved?
When we want to share a link from 3rd party app to a firefox on desktop, we first have to open a share menu, share to firefox app, and when the link opens in firefox app, only then can you select share to other devices and select the device you're sending the link to... after that, you have to close the tab in the firefox app, and then you have to close firefox app.

### How do you know that this problem exists today? Why is this important?
Because you have to go through multiple steps to send a link to a desktop for example and it's really annoying if you do this many times. 

It's important because it's completely possible to implement as seen in the example below and it would save many frustrations for users that do this on a daily basis.

Example of such functionality: On Android, If you want to share content to facebook, like a picture, and you don't want to go through multiple steps, you have a dropdown option in the share menu under the facebook icon, where you can select multiple options where on facebook would you like to share it to, "Story", "wall" or "set as profile picture".

### Who will benefit from it?

Anyone who wants to send links to Firefox on other devices (like desktop) from a 3rd party app, as quickly/efficiently as possible.

**Comment by ohhai** [comment]
It was even present for previous Firefox versions (before Fenix). Necessity to open a link before sending it to another device is a regression from this side.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/1523
