### ISSUE TITLE
Return or forward when holding Back button not showing selected page directly

### ISSUE THREAD

**Issue by Miteirao** [mozilla-mobile/fenix#20563]
### Steps to reproduce

Open 2 different pages on same tab, hold Back button and select the previous page. 

### Expected behaviour

The selected page should come to front immediately.

### Actual behaviour

You have to press Back button again or click on the page to it comes to front. It looks like the page selection option is being duplicated.

### Device name

Realme 7

### Android version

Android 11 (Realme UI 2.0)

### Firefox release type

Firefox

### Firefox version

91.1.0

### Additional information

Screenshot after selecting the page: 
![Screenshot-2021-07-28-17-00-59-07](https://user-images.githubusercontent.com/88121690/127423319-75b4d627-a76a-4562-a2cb-a4da7770566e.jpg)

Video: https://streamable.com/032spb

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17424)

**Comment by amedyne** [comment]
@sflorean Can you have someone from your team validate this? I am not able to reproduce this and I am on android 11.

**Comment by LaurentiuApahideanSV** [comment]
@amedyne I tried to reproduce the issue on Firefox Preview RC 90.1.3 and Nightly 2021-08-04, but was unable to. Tapping on the pages form history went smoothly.
### Devices used:
- OnePlus 6T (Android 9)
- Samsung Galaxy S9 (Android 8.0.0)
- OnePlus Nord N10 (Android 10)

**Comment by kbrosnan** [comment]
@Miteirao is it possible to provide a screen recording of what you are seeing?

**Comment by Miteirao** [comment]
@kbrosnan Screen record, after selecting the page, needs one more touch on page or Back button.
Video: https://streamable.com/032spb

Realme 7, Android 11 (Realme UI 2.0), Firefox 90.1.3

**Comment by SoftVision-LorandJanos** [comment]
Hi @Miteirao! I couldn't reproduce this issue on the:
- latest Nightly 98.0a1 (2022-02-07).
- latest Beta (97.0.0-beta6).
- latest Release (97.1.0).

Device used: Oppo Reno 6 (Android 11).

Could you check if you reproduce your issue with the latest builds? Thank you!

**Comment by SoftVision-LorandJanos** [comment]
Hi @Miteirao!
Could you please check on the latest builds if you can still reproduce this issue? Thank you!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811598

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
