### ISSUE TITLE
FNX-75 ⁃ Find in Page should appear in Quick Actions Sheet

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2056]
### Why/User Benefit/User Problem
As a user, I would like to quickly find things on the page. A swipe action to reveal the quick actions sheet is faster than possibly needing to scroll and then tapping a menu. 

This is available in iOS Safari. 

### What / Requirements
Find in page button appears in quick action sheet. 

### Acceptance Criteria (how do I know when I’m done?)
Find in page button appears in quick action sheet.

**Comment by lime124** [comment]
adding to the QAB design effort for consideration...

**Comment by ekager** [comment]
We have removed the QAB. Closing
