### ISSUE TITLE
FNX-5424 ⁃ [Bug] Tab previews don't show any information for the internal about: pages.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2057]
## Steps to reproduce
Go to about:about, about:config, or any other about: page
Touch the tabs icon 

### Expected behavior
The tab preview shows the address and title of the page

### Actual behavior
The tab preview shows nothing. It's blank.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by ekager** [comment]
I see a title and address in the tab preview now. Closing, please reopen with more information if still an issue
