### ISSUE TITLE
[Bug]: tabs icon misses one tap (need to tap twice) after sending tab to another device

### ISSUE THREAD

**Issue by ohhai** [mozilla-mobile/fenix#20576]
### Steps to reproduce

1. Configure Sync service with two devices at least.
2. Open some tab on Firefox Android and send it to another device.
3. Tap tabs icon (that one with the number of opened tabs)

### Expected behaviour

Tabs list will open as usually.

### Actual behaviour

Tap is ignored.
Second tap works as expected.

### Device name

LG V20

### Android version

8.0.0

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Additional information

Build info:
92.0a1 (Build #2015824971)
AC: 92.0.20210728190116, b7c74e3dba
GV: 92.0a1-20210728094336
AS: 81.0.1
2021-07-29T17:10:34.887638

**Comment by ohhai** [comment]
Now it is present in stable version as well (91.1.0)

**Comment by jonalmeida** [comment]
Thanks for filing this! I'm going to close it as a dup of https://github.com/mozilla-mobile/fenix/issues/21491 since we have a bit more traffic happening there.
