### ISSUE TITLE
FNX-5425 ⁃ [Bug] On error page, toolbar reload button in Stop state and doesn't work

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#2058]
## Steps to reproduce
1. Turn on airplane mode and go to any site
1. Open toolbar menu

### Expected behavior
Should be able to click reload in addition to the button on the page

### Actual behavior
Button is in "X" stop state and clicking it does nothing
![Screenshot](https://user-images.githubusercontent.com/25442310/56776081-160d7900-677f-11e9-81f7-8f65788b3795.png)UNITO-UNDERSCORE!20190425-172216!

Not sure if this is something we can fix on our end, or if we need the session to register that it's not loading anymore when an error page is requested/loaded.

### Device information
* Android device: ?
* Fenix version: ?

**Comment by kbrosnan** [comment]
Similar #1491

**Comment by vesta0** [comment]
@pocmo let's open an A-C bug for what needs to change.

**Comment by vesta0** [comment]
@pocmo do we have an A-C bug for this or should I create one?
