### ISSUE TITLE
[Crash]: Firefox crash on settings page of Simple gesture

### ISSUE THREAD

**Issue by utubo** [mozilla-mobile/fenix#20599]
Firefox crash when show this addon’s settings.

https://addons.mozilla.org/ja/android/addon/simple-gesture/

### Crash report
https://crash-stats.mozilla.org/report/index/7786d939-2e2f-4ae2-816b-3caaa0210730

### Device information
* Device vendor / model and Android version: Sharp SH-M15 Android 11
* Firefox for Android version: Firefox 92.0a1

**Comment by rafalopilowski1** [comment]
This also happens while accessing about:support 

Crash report on Bugzilla: [https://bugzilla.mozilla.org/show_bug.cgi?id=1723270](https://bugzilla.mozilla.org/show_bug.cgi?id=1723270)

- Device: OnePlus 6, Android 10 (Oxygen 10.3.12)
- Nightly build: #2015825163

**Comment by sflorean** [comment]
Tested on latest Nightly 7/31 and 7/30 and I was able to reproduce the crash (about:support) with LG G7 Fit (Android 8.1).
Not reproducible with Pixel 3 (Android 12).

@utubo what Android version are you using?

**Comment by utubo** [comment]
@sflorean 

> what Android version are you using?

Android 11.

Sorry, I'll add the device information.

Device information

    Device vendor / model and Android version: SH-M15 Android 11
    Firefox for Android version: Firefox 92.0a1

**Comment by utubo** [comment]
This seems to have been fixed on Build #2015825355 !😊

**Comment by rafalopilowski1** [comment]
Confirming Nightly build #2015825355 resolves this issue (+ `about:support` access issue)

![Screenshot](https://i.imgur.com/TbeYKXi.jpg)
