### ISSUE TITLE
Remove StartupTimeline & start up subsection duration probes

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20596]
While reviewing telemetry probes for renewal https://github.com/mozilla-mobile/fenix/issues/20520, we decided not to renew:
```
Startup.timeline:
  framework_primary
  framework_secondary
  framework_start_error
  framework_start_read_error
  clock_ticks_per_second_v2

perf.startup:
 app_on_create_to_glean_init
 app_on_create_to_megazord_init
 app_on_create_to_setup_in_main
 home_activity_on_create
 home_activity_on_start
 home_fragment_on_create_view
 home_fragment_on_view_created
 base_bfragment_on_create_view
 base_bfragment_on_view_created
```

Because we're not actively using them and have no intention to do so in the near future. We should remove this code.

**Comment by mcomella** [comment]
StartupTimeline in particular we could have used but it had large outliers in the data that we didn't have time to identify the cause of and it's unlikely we'll ever prioritize that.

For the subsections, we don't really know how to effectively use them and they were easy to add so we can always come back and add them later.

**Comment by RotBolt** [comment]
Hello @mcomella I think I could remove it. Seems like easy one to me. Just need to remove it from `metrics.yaml` right ?

**Comment by mcomella** [comment]
Hello again, @RotBolt ! It's a little more complicated than that. We also need to remove the code that uses that probe. You'll be able to find these because the app will have compilation errors after removing the probe from the metrics.yaml file. For an example, for the `app_on_create_to_glean_init` probe:
- we remove it [from the metrics.yaml](https://searchfox.org/mozilla-mobile/rev/0003570b4aa0536183b0040f3f3d265b31fe457c/fenix/app/metrics.yaml#4654)
- we remove [the call sites](https://searchfox.org/mozilla-mobile/rev/0003570b4aa0536183b0040f3f3d265b31fe457c/fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#99) (two in the linked function)

With some probes, we'd also need to remove the code that calls the function because the code has become a no-op. For example, I think we'd be able to remove [the `StartupFrameworkStartMeasurement` class](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/perf/StartupFrameworkStartMeasurement.kt#21) and its tests when we remove the `startup.timeline` probes.

@RotBolt What do you think? Is this something you'd like to try? I think it's doable. If so, I'd suggest trying to do a PR first for the probes listed under `perf.startup` (I think these are simpler) and, once that's landed, try out `startup.timeline` if you're still interested. Thanks for your interest! :)

**Comment by RotBolt** [comment]
@mcomella I think I would be able to do it. Would definitely work on this

**Comment by mcomella** [comment]
This was addressed with https://github.com/mozilla-mobile/fenix/pull/20808#issuecomment-904025924
