### ISSUE TITLE
[Bug]: 'Jump back in' does not obey feature flags

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20590]
### Steps to reproduce

1. Have Firefox Beta 91 installed (Firefox 90.1.3 or lower).
2. Open a tab.
3. Go to a new tab/home screen.

### Expected behaviour

- The 'Jump back in' section should not be seen.

### Actual behaviour

- The 'Jump back in' section can be seen.

### Device name

All devices

### Android version

All versions

### Firefox release type

Firefox Beta

### Firefox version

90.1.3 or lower

**Comment by sflorean** [comment]
I was able to reproduce the issue on 91.0.0-beta.5 but not on RC build. We will test again after the fix is landed.

**Comment by sflorean** [comment]
@jonalmeida @amedyne this issue is still reproducible on 91.0.0-beta.6. Maybe wasn't uplifted?
Devices:
- Google Pixel 3a (Android 11)
- OnePlus A3 (Android 6.0.1)
- Pixel 3 (Android 12)
- Samsung Galaxy Tab S3 (Android 9)

**Comment by rvandermeulen** [comment]
Yeah, https://github.com/mozilla-mobile/fenix/pull/20615 is still pending landing on the v91 branch. Let's try to get that merged before we build the RC.

**Comment by sflorean** [comment]
"Jump back in" is not displayed on RC 91, closing as verified.
