### ISSUE TITLE
FNX-5426 ⁃ [Bug] Rounded square icon used when Fennec has a round icon

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2059]
## Steps to reproduce
Install Fenix and view the app drawer

### Expected behavior
Round Icon displayed

### Actual behavior
Rounded square icon displayed

![Nexus%205%20-%20English](https://user-images.githubusercontent.com/250273/56777520-ea8e8c80-6786-11e9-9a5f-8bbf9d2e1787.jpg)UNITO-UNDERSCORE!20190426!UNITO-UNDERSCORE!092310!

### Device information
* Android device: Nexus 5 and Galaxy S6
* Fenix version: April 25 dev build

**Comment by kbrosnan** [comment]
Fallout from fixing #1970

**Comment by vesta0** [comment]
I believe we need an adaptive icon for the older devices.

**Comment by lime124** [comment]
@shorlander can you provide an asset to fix this?

**Comment by shorlander** [comment]
[ic_launcher.zip](https://github.com/mozilla-mobile/fenix/files/3158159/ic_launcher.zip)

Legacy icon files

**Comment by ekager** [comment]
I closed this becaues I don't think it's an issue anymore. Please reopen if this still needs an icon update
