### ISSUE TITLE
[Bug]: Support favicon SVG when Add to Home screen

### ISSUE THREAD

**Issue by regseb** [mozilla-mobile/fenix#20604]
### Steps to reproduce

1. Open <https://regseb.github.io/metalint/>;
2. *Add to Home screen*.

### Expected behaviour

Icon in home screen must be:

![favicon](https://regseb.github.io/metalint/img/favicon.svg)

get from [`<link rel="icon" type="image/svg+xml" href="img/favicon.svg" />`](https://github.com/regseb/regseb.github.io/blob/master/metalint/index.html#L10).

### Actual behaviour

Icon in home screen is a *R* in purple square.

### Device name

Google Pixel 4a

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.2

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/android-components/issues/2081
