### ISSUE TITLE
[Bug]: security lock icon menu not showing

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#20601]
### Steps to reproduce

Open any site , click security lock icon it is not expanding or showing

### Expected behaviour

A menu should open

### Actual behaviour

Menu is not showing..just a narrow white strip.

![Screenshot_20210731-112333560](https://user-images.githubusercontent.com/58127841/127730331-46d31a76-21f1-4798-913b-b6ca2d296aa1.png)

### Device name

rog3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

**Comment by sflorean** [comment]
I was able to reproduce this issue on cnn.com & other pages on latest Nightly build 7/31.

**Comment by Nickoriginal** [comment]
Reproducible in Firefox Nightly 92.0a1 2021-08-03T17:25:25.800599 on Samsung Galaxy A20s.

**Comment by kbrosnan** [comment]
This was fixed.
