### ISSUE TITLE
suggest to always show “fill link from clipboard” whenever users click on the url bar

### ISSUE THREAD

**Issue by alastor0325** [mozilla-mobile/fenix#20605]
Forked from [the issue 17109](https://github.com/mozilla-mobile/fenix/issues/17109). 

### What is the user problem or growth opportunity you want to see solved?
Everytime when users need to paste the link from the clipboard, users have to clear the current url, then the "fill link from clipboard" option would eventually show.

It would to be good to show "fill link from clipboard" below the url bar whenever users click on the url bar.

It can help to eliminate that unnecessary url clear before pasting new url.

### How do you know that this problem exists today? Why is this important?
This issue still exists on Nightly and it causes users to do extra moves to paste the URL comparing with other browsers.

### Who will benefit from it?
Everyone.

**Comment by SoftVision-LorandJanos** [comment]
Hi @alastor0325 ! Thank you for your report! I believe this request would be covered by #9584. I will close this one as a duplicate.
