### ISSUE TITLE
[Bug]: Cannot change name or save location for download files

### ISSUE THREAD

**Issue by LasagneCat** [mozilla-mobile/fenix#20609]
### Steps to reproduce

When I click save it brings up the save box but my only options are to save the file with default name in default location or to cancel the save.

I've tried with multiple websites.

### Expected behaviour

A window should open asking you where to save the file and what the file name is, giving you the option to change both

### Actual behaviour

The app gives you no options other than to save or to cancel

### Device name

Nokia 8.3

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.3

### Additional information

I stopped using Firefox mobile a few years ago because of this bug. It's still exactly the same

**Comment by kbrosnan** [comment]
Tracked in https://github.com/mozilla-mobile/fenix/issues/5764
