### ISSUE TITLE
[Bug]: Firefox for Android does not remove the active pseudo class from button once the button is pressed, held for some time and then released

### ISSUE THREAD

**Issue by hicnar** [mozilla-mobile/fenix#20606]
### Steps to reproduce

Below is some simple code to reproduce the behaviour.

The css used for the button:

.button {
  background: white;
  font-size: 40px;
  font-weight: bold;
  height: 100%;
  width: 100%;
}

.button:active {
  background-color: #f3f3f3;
  color: black;
}

div style="width: 100%;height: 100%"
    button class="button" >Button /button
/div

### Expected behaviour

After pressing, holding and finally releasing the button, the background should return to white.

### Actual behaviour

When the button is pressed, held and then released the button background colour remains #f3f3f3. That behaviour is present in Firefox on Android only, the Firefox for iOS works as expected.

### Device name

Samsung S9, Google Pixel C tablet

### Android version

10 on S9, 8.1.0 on Pixel C

### Firefox release type

Firefox

### Firefox version

90.1.3 on S9, 90.1.2 on Pixel C

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724759

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
