### ISSUE TITLE
FNX-5428 ⁃ [Bug] Old Firefox Preview Icon looked better / possible to use transparent background?

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2060]
## Steps to reproduce
1. Install Fenix
1. Look at icon on Android desktop

### Expected behavior
Icon like https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly.2019.4.24.revision/d1c1270e685df79b225e8424f834da6e3fd16c78 (dark background) 

OR

a transparent background like the blockada background in the screenshot below:

![signal-attachment-2019-04-25-213326](https://user-images.githubusercontent.com/152493/56777988-1ec37680-67a2-11e9-815f-0e224d097b8d.png)

### Actual behavior
White background that looks out of place unless using a white background on desktop. 

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by mcomella** [comment]
I also have concerns about the icon but they're different from these: please see https://github.com/mozilla-mobile/fenix/issues/2098

**Comment by vesta0** [comment]
@yoasif thanks for sharing! I will be sure to convey your feedback to our branding team.

**Comment by IdmFoundInHim** [comment]
When is the logo going to switch to the long-term logo (from <https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/>)? Also, are there plans to switch Fennec to the new logo before Fenix?
