### ISSUE TITLE
[Bug]: Typing in address bar does not always suggest bookmarks or synced tabs

### ISSUE THREAD

**Issue by dalb8** [mozilla-mobile/fenix#20602]
### Steps to reproduce

1. Type something into address bar
2. No suggestions appear, apart from search engine suggestions
3. Verified that history, bookmarks and synced-tabs are to be shown as-per search settings

### Expected behaviour

Items from my history should appear as well as bookmarks.

### Actual behaviour

No bookmarks or history items at all.

### Device name

Fairphone 3+

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90.1.1

**Comment by dalb8** [comment]
Sorry, appears to be a duplicate of #20351

**Comment by sflorean** [comment]
Closing as duplicate based on comment above. @dalb8 make sure that you don't have the search suggestions turned off in settings.
