### ISSUE TITLE
> just like Firefox desktop.

### ISSUE THREAD

**Issue by dustdevil1** [mozilla-mobile/fenix#20600]
> just like Firefox desktop.

... or Fennec (tabs playing audio were specifically protected from being unloaded).

_Originally posted by @buttercookie42 in https://github.com/mozilla-mobile/fenix/issues/9691#issuecomment-609791564_

**Comment by kbrosnan** [comment]
This is an incomplete report.

**Comment by notanewbie** [comment]
Can this be reopened? I also am experiencing this in Firefox Nightly, this started occurring early this week. I suspect that a recent update broke whatever had fixed this before, as I'm seeing some old issues for this dating back to 2020 and 2021, but no issues from this year.
![Screenshot_20221028-075335_Firefox Nightly](https://user-images.githubusercontent.com/16856594/198664297-ccd7f5fc-85c6-4374-aab6-1b1800228288.jpg)
