### ISSUE TITLE
Add magnifier to text selection

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#20618]
# Problem

It can be hard for a user to select a specific part of a word or avoid selecting punctuation when selecting text on a webpage in Firefox because they cover part of the text being selected with their finger. This problem is more pronounced on smaller text.

# Solution

Add a magnifier above the selector that is being dragged by the user with their finger.

# Examples

Chrome:
![Screenshot_20210802_155032.jpg](https://user-images.githubusercontent.com/20287690/127873171-bd7c19f4-95d8-4835-b90a-5ae528003d7b.jpg)

Gmail:
![Screenshot_20210802_155200.jpg](https://user-images.githubusercontent.com/20287690/127873209-b048e902-a68b-4e65-b36b-778e17d577af.jpg)

**Comment by anotherus3r** [comment]
This might be a useful resource: https://developer.android.com/guide/topics/text/magnifier

**Comment by makotokato** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1639087

**Comment by anotherus3r** [comment]
Oh looks like there's #3510, which I somehow missed when I searched for such an issue before posting this one.

**Comment by kbrosnan** [comment]
This is an upstream feature.

**Comment by gitblogman** [comment]
> This is an upstream feature.

what do you mean by the term upstream  feature  sorry I m newbs here

**Comment by sheikh-azharuddin** [comment]
Is this feature added? I noticed since last few days it is working but sometime buggy

**Comment by blogmangit** [comment]
why this feature is removed from nightly recently ?
