### ISSUE TITLE
Make access to home and tab tray coherent

### ISSUE THREAD

**Issue by Matth7878** [mozilla-mobile/fenix#20611]
### What is the user problem or growth opportunity you want to see solved?

Thanks to home button (at left to navigation/url bar) you can easily access home. But there is some incoherence in UI : 
- using home button show home without popping up an annoying keyboard which would hide half of the screen. Still keyboard pop up when home is accessed from tab tray with plus button. It shouldn't (I'm pretty sure there is an old issue for that) and by the way when going home, tab tray and hitting back button you get back without keyboard popping up. So there is one case which it doesn't work the same.
- back button doesn't dismiss home. You have to use jump back but still back button should work. It's what would be expected on Android. Besides it's not logical to have it dismiss tab tray but take you out of the app when doing it on home screen

### How do you know that this problem exists today? Why is this important?

Using the app and having to be careful how I access screen depending where I am...

### Who will benefit from it?

Users really using the app (tab tray, home, bookmarks, and so on) and not just opening link from other apps.

**Comment by amedyne** [comment]
@topotropic @Verdi some feedback on Home button.
