### ISSUE TITLE
[Bug]:  recently saved showing desktop download files

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#20613]
### Steps to reproduce

Download any file in desktop version
Open android firefox you will see download files in recently saved menu

### Expected behaviour

This should not the items downloaded from desktop variant  and saved locally in computer as those won't be accessible from mobile

So is this expected behaviour or bug?

### Actual behaviour

Showing desktop downloaded files in recently saved which cannot be accessed anyway .

![Screenshot_20210801-211344983](https://user-images.githubusercontent.com/58127841/127776988-f33bf55c-3449-4180-9000-8cf0cd6ce9b6.png)
![Screenshot_20210801-211352192](https://user-images.githubusercontent.com/58127841/127776995-e5c2023b-9005-4ba3-ada0-87791d82f753.png)

### Device name

rog3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

**Comment by eliserichards** [comment]
Wow good catch!! Thanks @sheikh-azharuddin! 

This is a bug (or at least something we didn't anticipate). We are retrieving a list of saved bookmarks through our sync service, but if that call is also returning saved _files_ we should be filtering those out.

**Comment by VitalyVPinchuk** [comment]
I can't reproduce it, can anyone?
