### ISSUE TITLE
FNX-5429 ⁃ The Find Bar should indicate that it has found no occurrences

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2061]
## Steps to reproduce
Try to find something that has no occurrences

### Expected behavior
It should indicate 0/0 (preferably in red), as it does 3/7 for example.

### Actual behavior
It has no clear visual indicator that no match was found besides the fact that the find bar doesn't highlight anything.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by AmyYLee** [comment]
Agreed there should be a 0/0 here in red #C50042 - Light theme, red #FF6A75 - Dark theme

**Comment by ekager** [comment]
Easiest way to fix this is updating the FindInPageBar in AC. Opened https://github.com/mozilla-mobile/android-components/issues/3063

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1921 (#11440149), with Huawei Honor 8 (Android 7), Google Pixel (Android 9), Sony Xperia Z5 Premium (Android 7.1.1).
