### ISSUE TITLE
Favicons for custom search engines

### ISSUE THREAD

**Issue by JonDous** [mozilla-mobile/fenix#20620]
Old Firefox used favicons and it was convenient. For now all the icons of search engines are just green.

**Comment by eliserichards** [comment]
@JonDous can you include a screenshot? Thanks! 😄

**Comment by JonDous** [comment]
> @JonDous can you include a screenshot? Thanks! 😄

![Screenshot_2021-08-03-05-58-44-437_org mozilla firefox](https://user-images.githubusercontent.com/68903949/127933958-b4a5107b-456f-400b-a9af-a2a2c0f3d0c7.png)
![Screenshot_2021-08-03-05-59-56-991_org mozilla firefox](https://user-images.githubusercontent.com/68903949/127933962-2ebb5a56-7d9e-4143-9267-c38a25cc3a12.png)

**Comment by kbrosnan** [comment]
duplicate https://github.com/mozilla-mobile/fenix/issues/7491
