### ISSUE TITLE
Allow user to choose if websites use dark/light theme independent of the theme settings

### ISSUE THREAD

**Issue by aasasd** [mozilla-mobile/fenix#20635]
Please make it possible to disable the feature of using websites' dark-mode CSS when the dark theme is used in the browser. I.e., I'd like to have FF with the dark theme but view sites in the default/‘light’ theme.

Rationale: I have astigmatism, as do ‘between 30 and 60% of adults’, according to Wikipedia. Apparently that's what makes reading light text on dark background difficult and uncomfortable, all the way to barely tolerable sometimes. Meanwhile, I prefer the phone's OS and browser UI to use the dark theme, because a) it looks good, b) this way the UI doesn't shine extra white into my eyes, and c) I don't normally read paragraphs of text in the system/browser UI. I find that dark UI with white website content is just the right amount of light from the screen, and thus was using this arrangement for ages.

Regarding the setting: a flag in `about:config` would work great for me.

Of course I don't know how hard this is to implement, but to my knowledge it would amount mostly to an `if` on the code that triggers the `prefers-color-scheme` media-query—the rest of the browser would work simply as if the site doesn't have a dark theme. After all, the mobile browser had a dark UI before `prefers-color-scheme` came along, and the browser chrome generally doesn't care about websites' colors.

P.S. I'm posting this request here because it chiefly concerns the mobile version, though it most probably has to be implemented in the engine. However I don't know what lower-level component this should be filed under. If I should re-post this on Bugzilla, please let me know what the proper designation for it is.

Currently I found only a vaguely-related issue on Bugzilla: [“Let add-ons control website's CSS media queries or prefers-color-scheme”](https://bugzilla.mozilla.org/show_bug.cgi?id=1547818). It seems to be without any development so far. Its implementation would sidestep my request on desktop, but then again, afaiu Android FF wouldn't benefit much from that and would have to re-implement the API.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17431)

**Comment by aasasd** [comment]
It appears that this is now implemented, via setting the option `layout.css.prefers-color-scheme.content-override` to 1. Dunno however if that's official and documented, or whether anyone wants to make it that way.

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1736218 tracks adding ui for this on Firefox, not sure if Fenix wants such thing too.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811317

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
