### ISSUE TITLE
FNX-5431 ⁃ [Bug] Bookmark saved snackbar shown for unbookmarking a site

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2063]
## Steps to reproduce
* visit a site
* swipe up to show the quick action bar
* bookmark a page
* wait for the snackbar to disappear
* swipe up to show the quick action bar
* unbookmark the page

### Expected behavior
* no snackbar when unbookmarking

### Actual behavior
* snackbar shown

### Device information
* Android device: Pixel 3 and Galaxy S6
* Fenix version: 99f979e86b4fcd9ad494357c519f20ebfe654da6

**Comment by ekager** [comment]
Right now you are just adding a duplicate bookmark the second time you press the bookmark button, and there's not a decision yet on the correct UX see #1586

**Comment by sv-ohorvath** [comment]
This doesn't reproduce after #1586. Tapping the bookmark icon a 2nd time will open the edit mode.
