### ISSUE TITLE
[Bug]: in tab tray, inactive tabs should be listed above active tabs

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#20639]
### Steps to reproduce

Not sure it changes the problem, but have tab tray set to list view and have URL bar set at the bottom
Have active tabs in the tab tray
Have inactive tabs in the tab tray

### Expected behaviour

Inactive tabs should be listed above the active ones, so that one can easily find and swipe to the last used active tab (which is currently stuck between all other active tabs and the inactive ones).
Scrolling down to the bottom should end up on the last active tab.
Also, in the old tab tray version, oldest tabs were listed first (and now, inactive tabs are the oldest ones, aren't they?)

### Actual behaviour

Inactive tabs are listed below the active ones.

### Device name

Redmi Note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by Octoton** [comment]
Or at least, inactive tabs should have a minimized button (like collection minimized button)  which state is remembered when firefox closes

**Comment by masayuki-nakano** [comment]
> Scrolling down to the bottom should end up on the last active tab.

Doing only this **might** be better beacuse when I open new tab from an old tab, the new (in other word, latest) tab is inserted immediately after the tab. So, bottom-most tab in the tab tray is not always latest tabs.

Additionally, putting inactive tabs to above may be far from bottom if there are a lot of active tabs and user works with the bottom-most tab, e.g., after adding new tab. Then, scrolling down from active tab **might** be nearer than scrolling up. Although I don't have any data about tab usage in Fenix.

Anyway, I'd love to see the last active tab to switch to adjacent tab when I open multiple new tabs from an old tab and accessing them.

**Comment by amedyne** [comment]
@topotropic some feedback and suggestions on the Inactive Tabs.

**Comment by amedyne** [comment]
> Or at least, inactive tabs should have a minimized button (like collection minimized button) which state is remembered when firefox closes

@Octoton This was recently implemented. You should see minimize on the latest Nightly.

**Comment by Octoton** [comment]
> > Or at least, inactive tabs should have a minimized button (like collection minimized button) which state is remembered when firefox closes
> 
> @Octoton This was recently implemented. You should see minimize on the latest Nightly.

Minimize is indeed working, however if you close firefox and reopen it, the minimize state will be forgotten and the inactive tab will be open again, which seriously lower the experience

**Comment by SoftVision-LorandJanos** [comment]
This issue seems fixed on the latest Nightly 97.0a1 (2021-12-23):
- Inactive tabs section is displayed above the active tabs in tabs tray.
- Inactive tabs are collapsed by default, and can be extended.
- On restart of the app, the inactive tabs section is displayed collapsed, even if it is left extended before closing the app.

Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.
