### ISSUE TITLE
Scrolling renders at 60 fps on a 90 Hz displays with Nightly (and Focus)

### ISSUE THREAD

**Issue by Susko3** [mozilla-mobile/fenix#20630]
### Steps to reproduce

1. Open any website in Nightly
2. Scroll

### Expected behaviour

Scrolling should be smooth, rendering at 90 fps.

### Actual behaviour

Scrolling is slow and laggy, rendering only at 60 fps.

### Device name

Realme 6

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 (Build #2015825547)

### Additional information

Firefox Nightly renders websites (including scrolling) at 60 fps even on a 90 Hz display. Native UI elements, such as the new tab page and settings are rendered at (as expected) 90 fps.
Firefox Focus shows the same problems as Nightly.

Firefox Release version is completely fine, rendering websites at 90 fps.

**Testing methodology:**

Scroll a website on Release and Nightly. The difference in smoothness is clearly visible.
My phone has a battery saver mode which limits the display to 60 Hz. With battery saver on, Release and Nightly scrolling feels the same. The smoothness is the same as Nightly without battery saving.

Additional confirmation from ADB, using command:

```
adb shell dumpsys display | grep -A 16 DisplayModeDirector
```

Sample output when Release is open, or when Nightly is open on a native page, such as Settings:
```
DisplayModeDirector
  mSupportedModesByDisplay:
    0 -> [{id=1, width=1080, height=2400, fps=90.0}, {id=2, width=1080, height=2400, fps=60.0}]
  mDefaultModeByDisplay:
    0 -> {id=2, width=1080, height=2400, fps=60.0}
  mVotesByDisplay:
    -1:
      PRIORITY_USER_SETTING -> Vote{width=-1, height=-1, minRefreshRate=0.0, maxRefreshRate=90.0}
    0:
      PRIORITY_APP_REQUEST_SIZE -> Vote{width=1080, height=2400, minRefreshRate=0.0, maxRefreshRate=Infinity}
      PRIORITY_APP_REQUEST_REFRESH_RATE -> Vote{width=-1, height=-1, minRefreshRate=90.0, maxRefreshRate=90.0}
  SettingsObserver
    mDefaultPeakRefreshRate: 60.0
  AppRequestObserver
    mAppRequestedModeByDisplay:
    0 -> {id=1, width=1080, height=2400, fps=90.0}
```

Sample output when Nightly (or Focus) is open (with some website open):
```DisplayModeDirector
  mSupportedModesByDisplay:
    0 -> [{id=1, width=1080, height=2400, fps=90.0}, {id=2, width=1080, height=2400, fps=60.0}]
  mDefaultModeByDisplay:
    0 -> {id=2, width=1080, height=2400, fps=60.0}
  mVotesByDisplay:
    -1:
      PRIORITY_USER_SETTING -> Vote{width=-1, height=-1, minRefreshRate=0.0, maxRefreshRate=90.0}
    0:
      PRIORITY_APP_REQUEST_SIZE -> Vote{width=1080, height=2400, minRefreshRate=0.0, maxRefreshRate=Infinity}
      PRIORITY_APP_REQUEST_REFRESH_RATE -> Vote{width=-1, height=-1, minRefreshRate=60.0, maxRefreshRate=60.0}
  SettingsObserver
    mDefaultPeakRefreshRate: 60.0
  AppRequestObserver
    mAppRequestedModeByDisplay:
    0 -> {id=2, width=1080, height=2400, fps=60.0}
```

(Notice `PRIORITY_APP_REQUEST_REFRESH_RATE` and `mAppRequestedModeByDisplay`)

**More info:**

There is a very curious file on my phone located at `/system/etc/refresh_rate_config.xml`
https://gist.github.com/Susko3/624b5d07614e8d8317e00cc6004d7221

The relevant bits of the file:
```xml
...
<!--0:90Hz, 1:60Hz -->
...
<refresh_rate_config>
...
  <package>org.mozilla.firefox,0</package>  <!--火狐浏览器-->
...
</refresh_rate_config>
```

So it could be that all versions are broken, just that Release version has an override (set by the phone itself) to force it to 90 Hz.
I'll report back if changing the package name affects this bug. I'll either compile the Release version myself, or 'clone' the Firefox app to a different package name.

**Versions tested:**

Release:
```
90.1.3 (Build #2015824995)
AC: 90.0.15, ef1436afb0
GV: 90.0.3-20210729144040
AS: 77.0.2
```

Nightly:
```
92.0a1 (Build #2015825547)
AC: 92.0.20210730143121, dca90e65d6
GV: 92.0a1-20210730093652
AS: 81.0.1
```

Focus:
```
8.17.1 (Build #351931837 🦎 90.0-20210705185941)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17428)

**Comment by Susko3** [comment]
Also happens with Beta, version:
```
91.0.0-beta.5 (Build #2015824891)
AC: 91.0.8, 6038cb8e83
GV: 91.0-20210727185725
AS: 79.0.0
```

**Comment by Susko3** [comment]
I've done some light testing with some very shady-looking "clone app" thing on the play store, and cloned Firefox Release is lagging when scrolling (due to 60 fps).

**Comment by Mugurell** [comment]
This is really interesting!
Thank you for all the details and the deep testing of this!

Also tested on a OnePlus 7T Pro which supports 90Hz refresh and saw the same thing: 
`PRIORITY_APP_REQUEST_REFRESH_RATE` for the browser (which is a SurfaceView) is 60Hz in Nightly but 90Hz in Release.
Saw the same thing with Chrome: 
`PRIORITY_APP_REQUEST_REFRESH_RATE` for the browser (which is a SurfaceView) is 60Hz in Canary but 90Hz in Stable.

On this device, both Firefox Nightly and Chrome Canary show 90Hz for `PRIORITY_APP_REQUEST_REFRESH_RATE` confirming for Oneplus there is a View type filtering used with exemptions for various packages.

**Comment by Mugurell** [comment]
Would be interesting to know on which other high refresh rate devices this happens.

**Comment by dhananjayraut** [comment]
@Mugurell I am having same issue.  Firefox UI is rendered on 120Hz and as soon as I open any website the refresh rate is dropped to 60Hz, builtin refresh rate meter (from developer options) clearly shows this change. For me both release and nightly version are showing this behavior.

my device is Realme X7 MAX.  (realme and oneplus are related)
while search for issues I found this: [https://bugzilla.mozilla.org/show_bug.cgi?id=1662380](https://bugzilla.mozilla.org/show_bug.cgi?id=1662380)

**Comment by abodea** [comment]
Hello, I verified this issue on OnePlus Nord (Android 10).
Same as Petru mentioned above:
OnePlus Nord (Android 10) which supports 90Hz refresh and saw the same thing: 
`PRIORITY_APP_REQUEST_REFRESH_RATE` for the browser (which is a SurfaceView) is 60Hz in Nightly but 90Hz in Release.

Pretty much the same behavior for this device too.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on OnePlus Nord N10 5G (Android 11) that supports 90Hz refresh rate, and can confirm the behavior is the same.
PRIORITY_APP_REQUEST_REFRESH_RATE is 60Hz in Nightly but 90Hz in Release.

**Comment by Susko3** [comment]
My phone (Realme 6) was just upgraded to Android 11 (with Realme UI 2.0) and now all apps (including all Firefox versions) display at 90 fps when that option is selected in system settings.

![Screenshot_2021-09-12-02-32-41-88_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/16479013/132966876-50bf770f-e275-4808-8224-ac823f3bc935.jpg)

If I set to 'Auto-select' it'll be 60 fps in many apps, including Firefox.

Keeping the issue open, as others are still having problems.

**Comment by seniorm0ment** [comment]
Encountering this as well, seems to be 60fps.
Im using the Fennec fork on Fdroid though, I presume it is an upstream issue

Pixel 6 Pro, Android 13, GrapheneOS

**Comment by seniorm0ment** [comment]
Encountering this as well, seems to be 60fps.
Im using the Fennec fork on Fdroid though, I presume it is an upstream issue

Pixel 6 Pro, Android 13, GrapheneOS

**Comment by BitGrub** [comment]
Looks like this bug has been merged into the Beta branch

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807329

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
