### ISSUE TITLE
[Bug]: Opening the tabs tray scrolls to the wrong position when inactive tabs are present

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#20637]
### Steps to reproduce

1. Have several active tabs
2. Have several inactive tabs
3. Set tab tray in list view
4. For various active tabs, try the following: open the tab, then open the tab tray and look for the focused tab -the one you just closed

### Expected behaviour

the tab tray should open by making focused tab (last open) visible

### Actual behaviour

See various examples in this video: https://photos.app.goo.gl/X9ACpbTxXa64yb8p8 (please be patient, some pages shown in the video are quite long to load!)

often, the tab tray does not display the focused active tab (either the active tabs are shown but not the focused one, or the inactive tabs are shown)

### Device name

Redmi Note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by jonalmeida** [comment]
From another user in https://github.com/mozilla-mobile/fenix/issues/20731, the selected tab is active, but opening the tabs tray scrolls to the inactive section instead:

<img src="https://user-images.githubusercontent.com/79359/128591056-9d190544-2dbe-4e1e-8a20-04243824d177.jpg" width=320 />

**Comment by yoasif** [comment]
Seeing this on a Pixel 2. This issue makes switching to recently used tabs more cumbersome, and I find myself using the less efficient swipe to switch feature.

**Comment by edwardgalligan** [comment]
I see this is labelled "S3"; I'm not sure of the exact definition of each label but looking at some of the "S1" and "S2" issues there may be a case of the severity of this being misunderstood.

I guess not all users have an inactive section at all, but for those who do (particularly a large one) this bug renders the tray completely unusable. The "Release blocker" label seems more appropriate.

**Comment by jonalmeida** [comment]
@MozillaNoah this issue a bit complicated because of some historical implementations here, so if you need some hints at any point, let me know if I can help clarify anything. 🙂

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 13/9/21 with Samsung Galaxy S21 Ultra (11).
Note that I tried to repro but the selected tab was always correctly displayed.
@edwardgalligan, @yoasif can you also take a look at your devices as you were able to repro them? Thx in advance!

**Comment by Aranjedeath** [comment]
Can confirm on latest Firefox Nightly for Android that this substantially mitigates the issues with the new inactive tabs feature (making it at least generally usable again for someone with too many tabs).
