### ISSUE TITLE
[Bug]: Closed tab reopens at the top of tab tray

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#20638]
### Steps to reproduce

Set Tab Tray to list view.
Set search field at bottom (not sure that has any impact though)
Have some active tabs opened
Close one of the active tabs via the tab tray
Reopen it immediately

### Expected behaviour

In the tab tray, it should reopen at the same place it was, or at least at the bottom (where new tabs are created)

### Actual behaviour

In the tab tray, it reopens at the top of the list, making it hard to find.

### Device name

Redmi Note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by mrBega** [comment]
I have a problem with this as well but I use grid view and NOT list view.

**Comment by SoftVision-LorandJanos** [comment]
Hi @klint ! Thank you for your report!
I can confirm this issue is reproducible, however it was logged before, and it is still covered in  #11367.
I will close this issue. If you have any extra information regarding this issue, please leave a comment for that ticket.
Thank you!

**Comment by klint** [comment]
Hi @SoftVision-LorandJanos
Thanks. But are you sure about the other bug's number? #11367 is a bug I have opened about site report icon which is already closed 😊.

**Comment by SoftVision-LorandJanos** [comment]
Hi @klint , you're right, sorry. Corrected it. Thanks! :)
