### ISSUE TITLE
Display alt text when long-pressing an image

### ISSUE THREAD

**Issue by edent** [mozilla-mobile/fenix#20643]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

There is no way for a user to see the alt text on images.

### How do you know that this problem exists today? Why is this important?

On Chrome for Android, long pressing an image will show the text of the `alt` attribute (if present).

On the latest Firefox for Android, only the URl is displayed.

<img src="https://user-images.githubusercontent.com/837136/128011360-8b5d215c-57b3-4480-a24f-90f57472d73d.jpg" width="400" alt="Chrome context menu showing alt text" /><img src="https://user-images.githubusercontent.com/837136/128011358-82ae055b-53d7-4757-bd3d-209a76ddbd56.jpg" width="400" alt="Firefox Android context menu with no text displayed." />

### Who will benefit from it?

Anyone who wants to read alt text. Developers who want to test their sites. Users migrating from Chrome to Firefox.

This is similar to #580

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17438)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813663

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
