### ISSUE TITLE
Install Android extension without registering

### ISSUE THREAD

**Issue by 89z** [mozilla-mobile/fenix#20647]
In my case, I want to install a popular addon, Stylus. It should be a trusted addon, it has over 3,000 stars on GitHub:

https://github.com/openstyles/stylus

I want to share with you the flow of the old process, with Firefox 68:

1. visit https://addons.mozilla.org/firefox/addon/styl-us
2. touch Download file
3. touch ADD

Now here is the process with new Firefox:

1. touch Play Store
2. search Firefox Nightly (as normal Firefox doesnt work anymore)
3. touch Firefox Nightly
4. touch install
5. touch Open
6. touch three dot menu
7. touch Settings
8. touch About Firefox Nightly
9. touch NIGHTLY logo five times
10. touch back
11. touch Custom Add-on collection
12. realize that I have to register on AMO to continue

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly

As a workaround, I have rolled myself back to Firefox Android 68:

https://archive.mozilla.org/pub/mobile/releases/68.11.0/

**Comment by Nickoriginal** [comment]
Custom add-ons support was hidden in debug menu to mark this unstable option as for testing purposes only. It is known Firefox lost opportunity, however, installing custom add-ons will cause errors, browser crashes or even leaking your personal data. So it cannot be enabled for free right now. Users must fully trust the add-ons they downloaded in Firefox, this is the reason why they are registered by Mozilla and checked for integrity at installation.
> As a workaround, I have rolled myself back to Firefox Android 68:

Firefox 68.11.0 is a version that was released more than 1 year ago. It have many known and unknown vulnerabilities, so do not offer to download it to users for their safety.

**Comment by 89z** [comment]
> Custom add-ons support was hidden in debug menu to mark this unstable option as for testing purposes only.

Thats fine, but why do I need to register on AMO to install an Add-on that **I made**?

> It is known Firefox lost opportunity, however, installing custom add-ons will cause errors, browser crashes or even leaking your personal data due to possible backdoors or errors in data.

No. If you create an Add-on with just `console.log('hello');`, then its impossible for that add-on to do any of the things you just said. The items you said are **possible** with untrusted 3rd party add-ons, but add-ons you write yourself, its an acceptable risk.

> So it cannot be enabled for free right now.

Firefox doesnt cost money, so this doesnt make sense.

> Users must fully trust the add-ons they downloaded in Firefox, this is the reason why they are registered by Mozilla and checked for integrity at installation.

If you write the add-on yourself, then by definition its already fully trusted, bypassing any need for registration with Mozilla.

> Firefox 68.11.0 is a version that was released more than 1 year ago. It have many known and unknown vulnerabilities, so do not offer to download it to users for their safety.

I am not offering to download it to anyone but myself. However I do **recommend** that anyone writing their own add-ons use that version, as the newer version are awful in regard to developer friendliness.

**Comment by 89z** [comment]
@cadeyrn I see your thumbs down, but since you didnt actually make a comment, I will assume you dont have any valid arguments against the issue here.

**Comment by Nickoriginal** [comment]
> Thats fine, but why do I need to register on AMO to install an Add-on that I made?

It is very unstable feature - almost all Fenix code was written in a year, and now there is its tireless support and fixes of vulnerabilities. Developers should understand that this advantage is enjoyed only by experienced users who will not risk their browser for installing 3-rd party addons and will help collect information about other add-ons for mobile browsers.

> Firefox doesnt cost money, so this doesnt make sense.

Sorry, I said wrong - if any user will have opportunity to **free** install custom add-ons from any sources, then if he encounters a problem or will be in danger due to installing suspicious add-on, he will blame Mozilla and do the right thing.

> If you write the add-on yourself, then by definition its already fully trusted, bypassing any need for registration with Mozilla.

Yes, it is. But where is the guarantee that add-ons written by random users (and even having a closed code) will be absolutely safe and not require the review and registration from Mozilla? (to prevent unexpected changes in code, for example, due to owner changing)

> I do recommend that anyone writing their own add-ons use that version,

It have a very outdated code and libraries, so it would not make much sense to the developer to target their add-ons (and develop it) to version 68 (!) of Firefox when in most cases all will use fresh version 90 and above.
Please note that Firefox 90 have a slightly different abilities and possibilities compared with Firefox 68.

**Comment by Nickoriginal** [comment]
> No. If you create an Add-on with just console.log('hello');, then its impossible for that add-on to do any of the things you just said. The items you said are possible with untrusted 3rd party add-ons, but add-ons you write yourself, its an acceptable risk.

No, it cannot be "acceptable risk". Nobody cannot trust your addon, if you do not have opened it code (what only advanced users can check) and it bypassed Mozilla registration (what would mean its full trust).
Please note that every add-on update should be checked by Mozilla to prevent
> unexpected changes in code, for example, due to owner changing

?

**Comment by 89z** [comment]
> It is very unstable feature - almost all Fenix code was written in a year, and now there is its tireless support and fixes of vulnerabilities. Developers should understand that this advantage is enjoyed only by experienced users who will not risk their browser for installing 3-rd party addons and will help collect information about other add-ons for mobile browsers.

I dont care about any of this. I want to be able to install add-ons that **I write**.

> Sorry, I said wrong - if any user will have opportunity to **free** install custom add-ons from any sources, then if he encounters a problem or will be in danger due to installing suspicious add-on, he will blame Mozilla and do the right thing.

Users should have the right to install add-ons that **they create**.

> Yes, it is. But where is the guarantee that add-ons written by random users (and even having a closed code) will be absolutely safe and not require the review and registration from Mozilla? (to prevent unexpected changes in code, for example, due to owner changing)

Users should have the option to accept the risk and install untrusted software if they choose, whether it is software they wrote, or popular software that has not yet been verified by Mozilla.

> It have a very outdated code and libraries, so it would not make much sense to the developer to target their add-ons (and develop it) to version 68 (!) of Firefox when in most cases all will use fresh version 90 and above.
> Please note that Firefox 90 have a slightly different abilities and possibilities compared with Firefox 68.

I would prefer to use newer Firefox, but I am not going to do so if I must register to install add-ons that **I wrote**.

> No, it cannot be "acceptable risk". Nobody cannot trust your addon, if you do not have opened it code (what only advanced users can check) and it bypassed Mozilla registration (what would mean its full trust).

Nope. Any add-on that I write myself is fully trusted to be used **by me**.

**Comment by Nickoriginal** [comment]
> I would prefer to use newer Firefox, but I am not going to do so if I must register to install add-ons that I wrote.

Please note that even if you created an extension for Firefox 68, you will not be able to safely use it when performing the main function of the browser - surfing the Internet.

The **only** way to download your custom add-ons in Nightly is to upload them in AMO and wait for check from reviewers. In my opinion, it is correct decision.

Waiting for @cadeyrn or other opinion to reach consensus.

**Comment by 89z** [comment]
> Please note that even if you created an extension for Firefox 68, you will not be able to safely use it when performing the main function of the browser - surfing the Internet.

I dont know how many times I have to say it. I am talking about using add-ons that **I wrote**, or popular open source add-ons **that I am choosing to trust**. I am explicitly accepting any risk involved in doing so. If that means using Nightly, or changing some setting, or both, I will gladly do that. What I wont do, is register on AMO just to install something that I wrote for use on my own computer.

> The **only** way to download your custom add-ons in Nightly is to upload them in AMO and wait for check from reviewers. In my opinion, it is correct decision.

Nope, you can use older Firefox, as Ive made very clear already. Although it would be better if newer Firefox had method for this as well.

**Comment by kbrosnan** [comment]
This is as designed.

**Comment by 89z** [comment]
Since @kbrosnan closed this issue without adding anything of substance, I just want this to be really clear for anyone visiting this page:

With Firefox for Android, **you cannot install add-ons** unless they have been approved by Mozilla. A workaround is available, but it required you to register on AMO. If you dont want to register on AMO, then **you cant install custom add-ons**, even if you wrote the add-on yourself and fully trust it. This is regardless of any version of Android Firefox (Nightly, etc), and regardless of any setting.

Only workaround I know of, is just dont use newer Firefox, with last good version as 68:

https://archive.mozilla.org/pub/mobile/releases/68.11.0/

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/13059

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/11292
https://github.com/mozilla-mobile/fenix/issues/18477

https://github.com/mozilla-mobile/fenix/issues/20647
https://github.com/mozilla-mobile/fenix/issues/20736

**Comment by quentincaffeino** [comment]
Ok so when are we disabling installing unsigned extensions on desktop?

**Comment by Tcll** [comment]
dang
latest version still can't install xpi files

mozilla must really hate their users if it's been this long

**Comment by 89z** [comment]
@Tcll I would do yourself a favor and block @cadeyrn - they are nothing but a loser troll.

**Comment by PolicyPuma4** [comment]
Make sure to express your opinions here https://connect.mozilla.org/t5/ideas/expand-add-on-compatibility-in-firefox-for-android/idi-p/191.

**Comment by muckmouf** [comment]
> Ok so when are we disabling installing unsigned extensions on desktop?

Exactly. Its contradictory in design and only orchestrates the unethically applied, its hypocrisy to have one not apply to the other in the same contrast since they are official Firefox browsers. Platforms have little to do with the differing "moral codes" or whatever beliefs from application, or at least they should have or be. Unless this has to do with laziness. I hate inconsistencies especially like this. 100 percent agree with you potentially hidden enthymeme.

**Comment by reyqn** [comment]
So the design, for "security" is to force users that want to sideload an addon to use an old, unmaintained version of this app?

That's the equivalent of forcing users to change their passwords regularly, resulting in passwords written on post-it.

Nice "security" bump.

**Comment by 89z** [comment]
@reyqn  just ignore @cadeyrn, they are a troll that has nothing better to do than downvote valid comments. I have blocked them so they cant comment, but sadly seems they can still downvote (not my comments but others).

**Comment by 89z** [comment]
@reyqn  just ignore @cadeyrn, they are a troll that has nothing better to do than downvote valid comments. I have blocked them so they cant comment, but sadly seems they can still downvote (not my comments but others).

**Comment by no-identd** [comment]
So I thought about some let us say anything but orthodox solutions for the User Experience constraints driving this issue, and I have some vague mental outline of something with which everybody could feel reasonably happy, I suspect, however, I suspect I've run into https://github.com/mozilla/addons-server/issues/5510 as a blocker. Any chance of that getting priorititized?

I suspect you might already see into which direction my thinking goes here, hopefully making in less necessary for me to immediately outline it here, for which I at present lack time.

**Comment by no-identd** [comment]
And in cases of "yes", "IDFMA", "maybe", & "depends", can we please see this issue reopened BUT also rewriten, both in terms of content and title? I'd volunteer to write an amalgam user story actually factoring in all sides of this equation, but I really lack the time to handle it, however, in case nobody else steps up I'd alibi accept the task & let it stall out until I either get around to it sometime this decade or cede it once someone steps up.

[Delicious special task management entropy, om nom nom nom]
