### ISSUE TITLE
[Bug]: collection open into inactive tabs

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#20640]
### Steps to reproduce

Go to home page
Open an old collections

### Expected behaviour

Tabs should open in the grid view or better yet in a separate tab space (like inactive tabs but with the title of the collection)

### Actual behaviour

The tabs open on top of the inactive tabs

### Device name

google pixel 4a

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by amedyne** [comment]
@Octoton There is a recent change in the Inactive tabs behavior. Can you validate on the latest Nightly if you still have the same problem?

**Comment by Octoton** [comment]
It is indeed working (tab groum style collection would have been so much powerfull, but peraphs it will come later)
