### ISSUE TITLE
[Bug]: Fenix drops scroll events on polygon.com with pull-to-refresh enabled

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20659]
### Steps to reproduce

1. with pull to refresh enabled…
2. Visit https://www.polygon.com/22526689/halo-infinite-release-date-gameplay-xbox-e3-2021 (it may work on other pages)
3. After ads load part way down the page…
4. Scroll up and down

### Expected behaviour

Scrolling works smoothly

### Actual behaviour

After scrolling down, the first scroll up event will frequently be dropped. Sometimes, you'll see the pull to refresh icon drop from the top partially but it never triggers to actually reload the page. This effect is exacerbated by playing the video content. I'm unable to reproduce this behavior with Pull to refresh disabled.

### Device name

Pixel 2

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 (2021-08-03)

### Additional information

Video recording of the issue (with both pull-to-refresh enabled and disabled): https://user-images.githubusercontent.com/759372/128097205-d1dd668b-dc76-4758-910a-e3a2cf038ebc.mp4

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724755

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
