### ISSUE TITLE
[Bug]: tabs older than 30 days old were auto-deleted when updating to nightly version 92.0a1 (Build #2015825739) even with tabs set to only be closed manually

### ISSUE THREAD

**Issue by Casstastrophe** [mozilla-mobile/fenix#20650]
### Steps to reproduce

1. Set the "close tabs" setting to manual 
2. Have many tabs open, including many tabs older than 30 days old
3. Update to nightly version 92.0a1 (Build #2015825739)
4. Observe that tabs over 30 days old are gone, and many of the ones that remain are marked as "inactive", with the notice at the bottom of this list saying inactive tabs will be deleted after 30 days
5. If the auto-close setting is changed to 30 days and then back to manual, the notice at the bottom of the inactive tabs list disappears. I believe this was reset to 30 days on the back end when the app updated, causing the tab closures on update

### Expected behaviour

Updating the app should not impact tab auto closure. 

### Actual behaviour

The app auto-closes all tabs over 30 days old when updated. 

### Device name

LG v50 thinq - model number LM-V450PM

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 (Build #2015825739)

### Additional information

Issue occurred when updating from the nightly version released on July 15th 2021 to nightly version 92.0a1 (Build #2015825739)

**Comment by willdurand** [comment]
I ran into this today and I am sad because I didn't bookmark these tabs..

**Comment by uid1000** [comment]
Just happened to me on Pixel 3a, Android 11. I really hope this isn't intended behavior. I probably just lost 100 tabs.

**Comment by ericonr** [comment]
>  I believe this was reset to 30 days on the back end when the app updated, causing the tab closures on update

Even defaulting to data loss in 30 days is bad... Someone who doesn't use their tablet for a full month, boots it up, updates the app and then launches it will lose all their tabs.

And the inactive tab list has completely screwed navigation and the position of the tabs.

**Comment by ericonr** [comment]
#20629 deals with this as well.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1345874
