### ISSUE TITLE
[Bug]: Reduced audio quality on SoundCloud when tab does not have focus

### ISSUE THREAD

**Issue by jscher2000** [mozilla-mobile/fenix#20653]
### Steps to reproduce

1. Open https://m.soundcloud.com/discover/sets/charts-top:piano:us (or another chart with music that has minimal distortion, so you can hear the issue more clearly)
2. Play a track and it should be very clear with very rare crackling sounds
3. Change focus away from the tab, for example, to the Android home screen or another app, and a very brief crackling sound may occur immediately and then intermittently as the track plays

### Expected behaviour

Background audio plays smoothly on other sites, such as YouTube (with the "Video Background Play Fix" add-on installed) and my local public radio station ([KQED FM, click the Listen Live button](https://www.kqed.org/)), so the expectation is that SoundCloud also would work seamlessly.

### Actual behaviour

Intermittent crackling sounds. Here's the SoundCloud user's latest thread: https://support.mozilla.org/questions/1345089

### Device name

Sony Xperia 10 II dual

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

89+

### Additional information

Confirmed in Firefox Nightly 92.0a1 on Samsung Galaxy S20 FE 5G with Android 11.

**Comment by al3xyce** [comment]
Here is the issue in the sample below: 
https://drive.google.com/file/d/1MrT9y43yrHwF5wgrUALd7m_UaumwQYKv/view?usp=sharing
Please fix!

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724994

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by al3xyce** [comment]
Latest Nightly, Beta, Stable upgrades: NOTHING SOLVED! 
Other details are not manageable by us!
Please fix!

**Comment by cadeyrn** [comment]
@al3xyce Please see the previous comment: The issue was moved to Bugzilla because it's something that has to be solved on the platform level. Nobody said that it's fixed.

**Comment by al3xyce** [comment]
Thank you!

**Comment by al3xyce** [comment]
We await for its solving!
