### ISSUE TITLE
Handle switching between private and normal mode when we show home behind search

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#20654]
Followup to #20573 

<img width="323" src="https://user-images.githubusercontent.com/43795363/128077998-1932fa94-4a89-486f-ac32-ce5b2a226561.png">

I am on wikipedia, and I tap on the URL and see home in the background. If I tap on the private mode button (mask) at the top of the home screen, what is the expected behavior?

Some options…

1. Open a new private tab -> ~will be opened with the same URL,~ keep the original tab in the normal tabs list
~2. Open a new private tab will be opened with the same URL, close the original tab in the normal tabs list (aka “move” the tab to private mode)~
~3. The button shouldn’t be clickable (I don’t think this is really a good option, just listing it for posterity)~

---

Because we want to preserve private mode security, we don't want to "keep" the URL when switching between private and normal mode. Instead, we are opening a new tab with a fresh session in the selected mode. 

In addition, once we switch to the new tab we start a fresh backstack and the user cannot navigate with the back button to the last tab.

Once the new tab is opened, there is no navigation until the user enters a URL/search and hits GO.

Scenarios: 
1. Start on home (not a tab) -> private mode toggle works normally and doesn't open tabs when switching
2. Start on home -> open search dialog (but do not search, just click on url bar) -> private mode toggle works normally and doesn't open tabs when switching
3. Start on home -> navigate to a URL -> click on URL to see home behind the search dialog -> click private mode button does the following:
   * Open a new tab in the new mode (if you were on normal mode, it opens a new private tab)
   * The original tab still exists
   * URL bar is cleared
4. Start on home -> perform a search (google, DDG, etc) -> click on URL to see search results -> delete search text to see Home -> click private mode button does the following:
   * Open a new tab in the new mode (if you were on normal mode, it opens a new private tab)
   * The original tab with search results still exists
   * URL bar is cleared
5. Start on a URL -> click on URL -> toggle private mode -> click Back button/minimize keyboard should do the following: 
   * Stay on the new tab you've opened
   * Home is visible
   * Private mode button works as normal (in scenario 1)
6. Open a tab -> perform a search (google, DDG, etc) -> click on URL -> toggle private mode -> click Back button/minimize keyboard should do the following: 
   * Stay on the new tab you've opened
   * Home is visible
   * Private mode button works as normal (in scenario 1)

**Comment by vesta0** [comment]
@eliserichards thanks for exploring these options! I think option 1 makes the most sense at this time and aligns better with user expectations. Just to be clear, a new private TAB wouldn't actually open until the user taps GO right?

**Comment by eliserichards** [comment]
We can do that :)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (94.0a1 - 2021-09-16T05:07:54.427449).

- Tapping on the URL takes the user to the home screen while keeping the same information in the URL.
- Tapping on the Private mode (mask icon) switches to a new tab in private mode with a fresh session without keeping the URL.
- Tapping on the back button does not take the user to the last tab. (The last tab is kept in the normal tabs list).
- There is no navigation until the user enters a URL/search and hits GO.

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
