### ISSUE TITLE
[Bug]: Duplicated results in search suggestions

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#20666]
The issue shown in the below screenshot is probably because of metadata history results.
(Grisha confirmed the entire redirect chain is saved and in that case there are two separate db entries, one with a slash at the end, one without)

We should check to ensure that a provider doesn't return duplicated results.
We should also check if its possible to filter out duplicated suggestions when combining the results from all providers.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/11428869/128138916-f22636c6-311b-4c40-b4ae-8f1ac8e94c4a.png">

**Comment by Mugurell** [comment]
History is historically complex - https://bugzilla.mozilla.org/show_bug.cgi?id=1670279

**Comment by buttercookie42** [comment]
I'm not seeing the entirely duplicated results as above any more, but as alluded to in [bug 1670279](https://bugzilla.mozilla.org/show_bug.cgi?id=1670279) above, I'm still getting superfluous history results for all the intermediate redirects.

I.e. after visiting `reddit.com/r/random_subreddit` and closing that tab again, typing `reddit.com/r/random_subreddit` into the URL bar gives me results for

* https://reddit.com/r/random_subreddit/ (with favicon)
* http://reddit.com/r/random_subreddit (no favicon)

On the first attempt, I've also seen a third intermediate version which I *think* was https://reddit.com/r/random_subreddit/ (no favicon), i.e. HTTPS but no trailing slash, but interestingly after restarting Firefox that entry has disappeared.
(And I guess on subsequent attempts with other subreddits I might run into some potential new feature that directly tries HTTPS first, so I'm missing out on that redirect??)
