### ISSUE TITLE
Make inactive tabs section collapsible 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20663]
Part of the [designs](https://www.figma.com/file/am9EJGg6ow29PXWkc9jcOH/MR2?node-id=708%3A7081), are to make the inactive tab UI collapsible when the clicking the header; the chevron indicates the current UI state.

In the designs, there is no mention of making the collapsible state persist on every new open, so let's assume not for now and we can add that later when we find out.

Linked JIRA: [FNXV2-17122](https://mozilla-hub.atlassian.net/browse/FNXV2-17122)

**Comment by MaggiWuerze** [comment]
Please make the state persistent. It is annoying to always have to scroll past the inactive tabs after closing the browser.

**Comment by SoftVision-LorandJanos** [comment]
Hi @jonalmeida ! Verified as implemented on the latest Nightly (93.0a1 - 2021-08-13T05:08:25.050265).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
