### ISSUE TITLE
search engine suggestion in address bar

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#20662]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
On clicking address bar it should show the search engine suggestion as in desktop i.e this time search with ...which includes search engines, bookmarks, history option same as desktop.. however currently it does not show anything
### How do you know that this problem exists today? Why is this important?
There is no option to search from bookmarks or history or immediately switch search engines...if this can be aligned with desktop version with a single row it will be beneficial

The scan option can be moved to the address bar itself close to the Google voice search button similar to vivaldi.. screenshot included

### Who will benefit from it?
All users

![Screenshot_20210804-091314136 (1)](https://user-images.githubusercontent.com/58127841/128119153-5ee5ee56-4721-4fb4-92f6-2b3ea36cdb95.png)

![Screenshot_20210804-091706225 (1)](https://user-images.githubusercontent.com/58127841/128119206-fbc12e07-a46a-4f78-8a32-252ba72b6952.png)

**Comment by amedyne** [comment]
@sheikh-azharuddin There is a setting that you can try that may be similar to what you are looking for. In **Settings -> Search - Address Bar,** turn on **Show Search Engines**. Let me know if this works. Thanks!

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin There is a setting that you can try that may be similar to what you are looking for. In **Settings -> Search - Address Bar,** turn on **Show Search Engines**. Let me know if this works. Thanks!

It works but there is no option to search through bookmark or history...however the desktop version show a single row with that option..is it possible to add?

Desktop version has "this time search with"...
