### ISSUE TITLE
[Bug]: Newly created tabs show up as inactive when added to the tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20664]
### Steps to reproduce

1. Go to any tab.
2. Long press a link and click 'Open in new tab'.
3. Open the tabs tray.
4. Observe.

### Expected behaviour

The new tab should be opened adjacent to the currently selected tab you are on.

### Actual behaviour

The tab is immediately add to the "inactiive tabs" grouping.

### Device name

All devices

### Android version

All versions

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by notJerl** [comment]
This definitely shouldn't be the default behavior. If a user opens a tab, they probably want to look at it pretty soon, so burying it in the dungeon with weeks old tabs seems like bad UX.

**Comment by SoftVision-LorandJanos** [comment]
Hi @jonalmeida ! I could reproduce your issue using the Nightly build from 5 days ago.
I can confirm that the newly opened tab is not automatically added to the inactive tabs, but as expected.
Verified on the latest Nightly (92.0a1 - 2021-08-10T05:07:48.618794), using the following devices:
- Google Pixel 4 (Android 11).
- Samsung Galaxy Tab S3 (Android 9).
- LG Nexus 5 (Android 6.0.1).
