### ISSUE TITLE
Move "Quit" button up

### ISSUE THREAD

**Issue by PavelShyshkouski** [mozilla-mobile/fenix#20667]
### What is the user problem or growth opportunity you want to see solved?
On many devices of medium size (maybe even on all device kinds) Quit button is hidden because of insufficient space to show the whole menu, so you need to scroll down to access it.

See an example screenshot:
![Example](https://user-images.githubusercontent.com/7083443/128148444-5b1fbccf-e05b-42e6-b5ba-768e417a983c.jpg)

For those who use "Delete browsing data on quit" this will be one of the most often used buttons.

I suggest to move the button higher up so that it's always easily accessible without scrolling. Maybe to the top of the menu or at least to the top of it's current section.

### How do you know that this problem exists today? Why is this important?
The issue has been existing in all versions of Firefox Nightly since at least half a year ago. The confirmed version at the time of the report is 92.0a1.
Obviously, the suggested feature is not critical but it will improve user experience in my opinion.

### Who will benefit from it?
I think everyone who uses "Delete browsing data on quit" will benefit from avoiding to scroll the menu each time the browser is exited.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17459)

**Comment by SoftVision-LorandJanos** [comment]
This is still repeoducible.
The "Quit" button is on the bottom of the menu.
Checked on the latest Nightly 98.0a1 (2022-02-07) using an Oppo Reno 6 with Android 11.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 109.0a1 (2022-11-25) build.
The Quit button is accessible without scrolling where in earlier builds scrolling was needed.
Device used: Pixel 4 (Android 13).
