### ISSUE TITLE
[Bug]: DRM protected content on apple tv+ does not play

### ISSUE THREAD

**Issue by aravindanve** [mozilla-mobile/fenix#20676]
### Steps to reproduce

1. Go to tv.apple.com and login with your apple credentials
2. Play any tv show or movie. It does not play past the Apple logo at the beginning of the movie, it just displays a grey screen

### Expected behaviour

It should play movies on apple tv+

### Actual behaviour

The player displays a grey screen

### Device name

Samsung Galaxy S20

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.3

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724027

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
