### ISSUE TITLE
[Bug]:  button text in document being replaced with password Text

### ISSUE THREAD

**Issue by Oscar-21** [mozilla-mobile/fenix#20673]
### Steps to reproduce

Brief summary of the issue:
If you allow google to **autofill a password**  or create a new one on a login form the submit button text will be **replaced with the password.**

This has happened on several sites but I'll give one that can be used for reproduction.

Preqresuites: gboard and  the ability to use a google account to generate a fake password you can use to test.

1.  Open a private tab at https://www.paperlessemployee.com/allegis/PE
2. Allow google to generate a password for you for this site.
![Screenshot_20210804-085042~2](https://user-images.githubusercontent.com/21151259/128185106-a4f83933-b4bf-4324-af82-a6ab737122f9.png)

### Expected behaviour

Password is generated and filled in (note this is chrome but the bug picture is Firefox)
![Screenshot_20210804-090247](https://user-images.githubusercontent.com/21151259/128185381-b4e1b984-b10a-4d9b-9de2-f541eaca8643.png)

### Actual behaviour

![Screenshot_20210804-085234](https://user-images.githubusercontent.com/21151259/128185456-6bcbf752-ad12-43b8-a9ee-ae7f9c7c3361.png)

### Device name

Google Pixel 4

### Android version

Android 12 SPB3.210618.016

### Firefox release type

Firefox

### Firefox version

90.1.3

**Comment by mcarare** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724006

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
