### ISSUE TITLE
Option to not remember history

### ISSUE THREAD

**Issue by julianfairfax** [mozilla-mobile/fenix#20678]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
There is no way to set history to not be remember in Firefox for Android like there is in Firefox for desktop (using custom settings for history and turning off remember browsing and download history and remember search and form history).

This is what the feature looks like in Firefox for desktop:
![image](https://user-images.githubusercontent.com/43753131/128235997-7c48d680-42b4-42be-920f-b04554eec48f.png)

### How do you know that this problem exists today? Why is this important?
Because I like privacy and it would mean people who like privacy wouldn't have to clear it every single time.

### Who will benefit from it?
People who like privacy

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17468)

**Comment by cadeyrn** [comment]
Firefox already has an option to delete browsing history on quit.

**Comment by julianfairfax** [comment]
That feature requires clicking a particular menu item to delete the browsing history and quit. It also doesn't stop the current session from remembering it until that menu item is clicked.

**Comment by julianfairfax** [comment]
Closing since the existing option is convenient enough

**Comment by julianfairfax** [comment]
Sorry for closing and opening this again, would you still be up for adding this functionality? Thanks for your wonderful app!

**Comment by julianfairfax** [comment]
A year on, this doesn't seem to be happening

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813664

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
