### ISSUE TITLE
FNX-5434 ⁃ [Bug] Switching search engine using shortcuts resets the text in the address bar

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2067]
## Steps to reproduce
* Tap into the address bar
* Type some text
* Tap the shorcuts button
* Tap Amazon or any other search engine but the selected one

### Expected behavior
* typed information retained

### Actual behavior
* typed information is lost

### Device information
* Android device: Pixel 3
* Fenix version: 99f979e86b4fcd9ad494357c519f20ebfe654da6

**Comment by sblatz** [comment]
This should be fixed in the latest nightly due to an AC change.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190704 (#11850611) with Google Pixel 3 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Tab S3 (Android 8).
