### ISSUE TITLE
[Bug]: Failed to query installed add-ons

### ISSUE THREAD

**Issue by quadriflax** [mozilla-mobile/fenix#20686]
### Steps to reproduce

Same as bug 12399: https://github.com/mozilla-mobile/fenix/issues/12399

92.0a1 (Build #2015826121)
AC: 92.0.20210804145319, 1efe95ff30
GV: 92.0a1-20210804093931
AS: 81.0.1

Android 11

Worked fine until I updated to latest nightly above a short while ago, but it's broken again. Let me know if there is anything I can do to help.

### Expected behaviour

Addons should load/work as intended.

### Actual behaviour

Addons do not load or work.

### Device name

Samsung Tab A

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Additional information

Uninstalling/reinstalling did not help. In fact, I couldn't even log into Sync on a fresh install with no addons. Rolling back to previous nightly from 3 Aug fixed everything:

92.0a1 (Build #2015825969)
AC: 92.0.20210803143316, 2347602c39
GV: 92.0a1-20210802093840
AS: 81.0.1

**Comment by Amejia481** [comment]
Closed as duplicated of https://github.com/mozilla-mobile/fenix/issues/20692, feel free to reopen if it's different.

**Comment by quadriflax** [comment]
Is it the same? One is failing to query, one is failing to install. Seems like they're related, but they do give different errors. The failed to install bug at least lists the addons. This bug just doesn't load anything at all. I don't know any better, but just want to make sure both issues are addressed.

**Comment by Amejia481** [comment]
To help me determine if it's the same issue that is causing https://github.com/mozilla-mobile/fenix/issues/20692. If it's not much trouble would you mind sharing the [logcast logs](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information).

**Comment by quadriflax** [comment]
Here you go. I installed nightly from 4 Aug and started getting the failed to query error again instead of failures to install. I installed a bunch of addons on the 3 Aug just fine, everything worked fine. 4 Aug gives this error, 5 Aug gives the inability to install error.

Let me know if you need anything else. Thanks for looking into it.

[adb.txt](https://github.com/mozilla-mobile/fenix/files/6941613/adb.txt)

![Screenshot_2021-08-05-16-44-46](https://user-images.githubusercontent.com/46144580/128419167-47e3a015-4550-45bd-b24c-a08ad07740f9.png)
