### ISSUE TITLE
FNX-5435 ⁃ [Bug] quick action bookmark star should be filled when interacting with the edit snackbar

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2068]
## Steps to reproduce
* Open a page
* Bookmark it
* Tap Edit in the snackbar
* Tap the Android Back button
* Examine the quick action bar

### Expected behavior
* Bookmark created
* Quick action bar marks the page as bookmarked

### Actual behavior
* Bookmark created
* Quick action bar marks the page as not bookmarked

### Device information
* Android device: Pixel 3
* Fenix version: 99f979e86b4fcd9ad494357c519f20ebfe654da6

**Comment by sv-ohorvath** [comment]
The same issue happens if you tap to edit the URL, do nothing, and press the back button to return back to the bookmarked page.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with Google Pixel (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1), on the latest build 1.0.1920 (Build#11350639).
