### ISSUE TITLE
[Bug]: AdBlock Plus and other add-ons (still) not supported

### ISSUE THREAD

**Issue by JakeQZ** [mozilla-mobile/fenix#20703]
### Steps to reproduce

1. Go to https://addons.mozilla.org/en-GB/android/addon/adblock-plus/
2. Try to click button to install add-on.

### Expected behaviour

Add-on can be installed.

### Actual behaviour

Button to install add-on is greyed out.

Attempting to install add-on via XPI file results in a message "Add-on is not supported".

### Device name

[N/A] Nokia 8

### Android version

[N/A] Android 9

### Firefox release type

Firefox

### Firefox version

89.1.1

### Device logs

N/A

### Additional information

I have contacted the add-on developers via email (support@adblockplus.org) and they gave the following responses:

> The latest firefox on Android does not support ABP anymore. You can read more about it here: https://www.androidheadlines.com/2020/07/firefox-version-79-update-features.html

I also asked if there were plans for it to be supported.

> This was a Firefox decision, not related to Adblock Plus unfortunately.

So it seems the ball is in your court.

I note #14034 which is now closed, but don't find any open issue for supporting the add-ons that were supported in version 68.x, in a "Daylight" release without any `about:config` tweaks required.  Is there an issue for tracking this?  What is the progress on this?  (It has been over a year now.)

I have marked this as a bug rather than a feature request as it is a regression since version 68.x.

**Comment by samlux04** [comment]
Just get ublock. It's much superior.
About other unsupported addons. You can try with Firefox nightly.

I always monitor Firefox mobile development. Almost everyday to check commit history. I can say there's not much activity for months.
There's still important tab tray issue and general ui issuws which hinder browsing experience. It make Firefox mobile so sluggish. But still no change for almost a year. So don't get your hope up.

**Comment by kbrosnan** [comment]
We don't keep issues open for specific extensions. You can use [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to use most extensions https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by vehosah** [comment]
> We don't keep issues open for specific extensions. You can use [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to use most extensions https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

Blog mozilla doesn't have updates, and nightly is not a solution
