### ISSUE TITLE
[Bug]: Inactive tab title can sometimes be missing

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20718]
### Steps to reproduce

1. Navigate to diply.com
2. Make that tab inactive.
3. Observe

### Expected behaviour

There should be a title.

### Actual behaviour

There is none.

### Device name

All devices

### Android version

All versions

### Firefox release type

Firefox Nightly

### Firefox version

n/a

### Additional information

<img width="607" alt="Screen Shot 2021-08-06 at 10 54 21 AM" src="https://user-images.githubusercontent.com/1370580/128529727-1f2efdf9-46b7-42a5-928c-35c3d373ae75.png">

**Comment by marcel263** [comment]
#20546 shares similarity

**Comment by SoftVision-LorandJanos** [comment]
Hi @jonalmeida ! I verified your issue with the Nightly build from 5 days ago and I could reproduce it.
I can confirm the URL is displayed as a title for the inactive tabs with the latest Nightly build.
Verified it with your example:
![Screenshot_20210818-135642](https://user-images.githubusercontent.com/48829350/128856576-5d7c28e5-b2ba-4d6c-87b6-fcf5d5437ac0.png)
Verified on the latest Nightly (92.0a1 - 2021-08-10T05:07:48.618794), using the following devices:
- Google Pixel 4 (Android 11).
- Samsung Galaxy Tab S3 (Android 9).
- LG Nexus 5 (Android 6.0.1).
