### ISSUE TITLE
No way to view the ssl certificate of the website i'm currently visiting.

### ISSUE THREAD

**Issue by DrekiDegga** [mozilla-mobile/fenix#20717]
### Steps to reproduce

I can find no way to view the certificate information of websites I'm currently visiting. This seems like a basic and necessary security feature for a web browser. 

### Expected behaviour

I should be able to easily view detailed SSL certificate information used to verify the security of the website I'm currently visiting.

### Actual behaviour

I can't do that.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.3

**Comment by clientenq** [comment]
This needs fixing asap. The certificate trust is designed so users are presented with certificate information to verify. The current implementation by mozilla fenix is the user is not able to view or verify and just has to trust the browser. Fenix developers have broken the purpose of certificates by this design.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/8400
