### ISSUE TITLE
Dropdown for <select> to select <option> should have a text field to filter/find specific item(s)

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla-mobile/fenix#20730]
I'd love the popup/dropdown of `<select>` to have a text field to filter/find spcific `<option>` element. Perhaps this is not required in most cases, i.e., when the number of `<option>` is not so many.

### What is the user problem or growth opportunity you want to see solved?

If a `<select>` has too many `<option>` elements, it's hard to search an specific item to find from tthe long list only by my eyes. Therefore, I'd like to see fewer items which contains typed text.

### How do you know that this problem exists today? Why is this important?

I usually see very long dropdown list for selecting:
* Country
* Prefecture/State (address)
* Birth year
* Birth day

And also if you're a Firefox contributor (of course!), you see such long `<select multiple>` in [advanced search field of BMO](https://bugzilla.mozilla.org/query.cgi?format=advanced), e.g., tap the "Product".

### Who will benefit from it?

For the former cases, all users. Users know the label of item to select like country, but the item is put on not top of the list.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17503)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813751

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
