### ISSUE TITLE
[Regression]: Restore Fennec web extension / add-on support

### ISSUE THREAD

**Issue by jesus2099** [mozilla-mobile/fenix#20736]
### Steps to reproduce

Go to an add-on page:

- https://addons.mozilla.org/firefox/addon/violentmonkey/
- https://addons.mozilla.org/firefox/addon/styl-us/

And try to install them.

### Expected behaviour

The add-on should be added to Firefox for Android Fenix, as they used to be all compatible with Firefox for Android 68.11.0 Fennec.

### Actual behaviour

The install buttons are greyed out since Firefox for Android Fenix.

---

This is a new ticket replacing the [Fennec Transition](https://github.com/mozilla-mobile/fenix/labels/Feature%3AFennecTransition) ticket #574 that was closed before fulfillment.

It is related to ticket #5315, that was [restricted to partial support and closed](https://github.com/mozilla-mobile/fenix/issues/5315#issuecomment-647672199).

There was ticket #13059, also closed before add-on support was actually restored.

### Device name

Redmi 7

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

89.0.10

### Additional information

web extension / add-on
web extensions / add-ons

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17509)

**Comment by jesus2099** [comment]
At least fixing #12719 would be the most important step.

**Comment by SpandexWizard** [comment]
Technically this isn't a bug, this is how they intend the add-ons to work. Unless I am mistaken they intend to, and have, completely replaced the addon web pages with the add-on manager for mobile, and you are supposed to select your add-ons through that.  While I too would prefer that we could just go to the page and tell it to add them, that doesn't make this a bug. That part is working as intended.

**Comment by jesus2099** [comment]
Indeed it's not really a bug, it's a regression, but I could not find this type.
Maybe I should edit this to something like: 

> Cannot find Violentmonkey, Stylus (styl-us) nor other web extensions /add-ons in the _add-on manager for mobile_.

**Comment by cadeyrn** [comment]
There are really more than enough duplicate issues. Opening another one does not help.

**Comment by 89z** [comment]
https://github.com/mozilla-mobile/fenix/issues/11292
https://github.com/mozilla-mobile/fenix/issues/18477
https://github.com/mozilla-mobile/fenix/issues/20647

https://github.com/mozilla-mobile/fenix/issues/20736

**Comment by 89z** [comment]
Just ignore troll @cadeyrn, the fact that Mozilla is shutting down the add-on ecosystem is concerning, so many issues should exist. That fact that you cant even install add-ons you wrote yourself is not acceptable. And its not acceptable that Mozilla is trying to force people to register on AMO just to install add-ons they wrote themself.

**Comment by benyaminl** [comment]
@kbrosnan any ETA for all extension to land on android? Or at least side loaded from Nightly? Thanks.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1358594

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1359295

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1359321

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1359466

**Comment by kelimuttu** [comment]
This was being discussed on [Reddit](https://www.reddit.com/r/firefox/comments/rej30c/add_on_support_for_firefox_on_android/) recently

**Comment by kelimuttu** [comment]
Another one on [Reddit](https://www.reddit.com/r/firefox/comments/rhnnim/any_updates_on_desktop_extensions_support_on/) today

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1362193

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1362702

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1365245

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1365463

**Comment by JJRcop** [comment]
Should this ticket get added to the Github Project tracker for [WebExtensions and AddOns](https://github.com/orgs/mozilla-mobile/projects/44) ?

**Comment by Mikaka27** [comment]
Apparently it's a business decision to not support all addons (and not a technical limitation), as claimed by former mozilla developer, link: [Source](https://www.reddit.com/r/firefox/comments/vmt6gp/why_firefox_on_android_has_limited_addon_selection/)

**Comment by cadeyrn** [comment]
> as claimed by former mozilla developer

Well, that's a one-sided quote. Another former Mozilla employee shares a bit different perspective in the answers to this comment. I recommend to also read the other comments.

**Comment by jesus2099** [comment]
I have migrated from **Firefox for Android 68** to **Kiwi Browser** on December 2021.
Now 6 months later, the 2 extensions I need, [Violentmonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag) and [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne), still run flawlessly, with all my user scripts and user styles!

It might not worth the effort to develop extension support back to [Firefox](https://github.com/mozilla-mobile/fenix/issues/20736) and new to [Vivaldi](https://forum.vivaldi.net/topic/31078/support-extensions/248).

I guess, people interested in extensions should just use [Kiwi](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser), where all the effort should be focused.

**Comment by OkyDooky** [comment]
I would recommend people invest in [SmartCookieWeb-Preview](https://github.com/CookieJarApps/SmartCookieWeb-Preview), instead of the Chromium-based (and closed source?) Kiwi browser. It is Gecko-based, open source, and you can side-load add-ons from the Mozilla site by tapping the "download file" button. Most I've tried seem to work with minimal issues. It's very much an early work-in-progress, especially compared to the SystemWebView-based SmartCookieWeb browser (currently available in F-Droid), but it is still pretty functional and usable. Plus, you can import and export bookmarks, as well. Can't wait for it to re-add traditional desktop-style tab row support, like its WebView counterpart.

**Comment by boek** [comment]
Consolidating these requests into https://bugzilla.mozilla.org/show_bug.cgi?id=1812119.

**Comment by kbrosnan** [comment]
bz-1796184  is a better dupe
