### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nausher** [mozilla-mobile/fenix#20731]
### Steps to reproduce

1. Have a tab open for more than 30 days (or as long as the tab is marked 'inactive')
2. Open a new tab and press the tab switcher icon
3. Instead of displaying the listing of regular tabs, the user is displayed a list of inactive tabs first.
See screenshot attached.

This is poor user experience. Inactive tabs should be shown last not first.
As a user I am interested in the content that I actively browsing now.

![Screenshot_20210806-142301](https://user-images.githubusercontent.com/79359/128582368-5fcc5751-915f-4c54-bb98-58afba00c31d.jpg)

### Expected behaviour

Display the listing of regular tabs first. Instead of displaying a list of inactive tabs first.

### Actual behaviour

Instead of displaying the listing of regular tabs, the user is displayed a list of inactive tabs first.
See screenshot attached.

### Device name

One Plus 6

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by jonalmeida** [comment]
Thanks for reporting!

> Instead of displaying the listing of regular tabs, the user is displayed a list of inactive tabs first.

You are seeing the selected tab first. It just happens that your selected tab is the last tab before the inactive tab section.

Closing as invalid.

**Comment by nausher** [comment]
@jonalmeida - that's not the case. Maybe in the screenshot. I do have a case where my selected tab is active but all I see are inactive tabs. I believe this bug has been closed in error. Please let me know how I can reopen it.

**Comment by nausher** [comment]
![Screenshot_20210806-233824](https://user-images.githubusercontent.com/79359/128591056-9d190544-2dbe-4e1e-8a20-04243824d177.jpg)
Attaching a screenshot where I'm on an active selected tab

**Comment by klint** [comment]
I confirm the same issue, as also reported here : #20637

**Comment by jonalmeida** [comment]
> @jonalmeida - that's not the case. Maybe in the screenshot. I do have a case where my selected tab is active but all I see are inactive tabs. I believe this bug has been closed in error. Please let me know how I can reopen it.

Thanks for clarifying. Let's re-open it then; definitely a bug.
