### ISSUE TITLE
[Bug]: Screen flickering

### ISSUE THREAD

**Issue by gmadjara** [mozilla-mobile/fenix#20733]
### Steps to reproduce

https://streamable.com/lv92dj

1. Open any page
Example: 
https://www.eurogamer.net/articles/2017-11-24-horizon-zero-dawn-override-cauldrons-locations-mounts-sigma-rho-xi-and-zeta-unlocks-locations-and-maps-4932

2. Screen will flicker everywhere on the page in form of a big black or white rectangle, depends on the theme colour.

It happens even if all add-ons are disabled. It starts only recently with the latest Nightly update.

### Expected behaviour

Display a page normally

### Actual behaviour

Flickering pages

### Device name

Huawei P30 Pro, VOG-L29

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Additional information

Application Basics
------------------

Name: Firefox Nightly
Version: 92.0a1
Build ID: 20210806132505
Distribution ID:
User Agent: Mozilla/5.0 (Android 10; Mobile; rv:92.0) Gecko/92.0 Firefox/92.0
OS: Linux 29 #1 SMP PREEMPT Thu Mar 25 12:59:08 CST 2021
Multiprocess Windows: 0/0
Fission Windows: 0/0 Disabled by default
Remote Processes: 1
Google Location Service Key: Found
Google Safebrowsing Key: Found
Mozilla Location Service Key: Found
Safe Mode: false

Crash Reports for the Last 3 Days
---------------------------------

Nightly Features
----------------

Remote Processes
----------------

Type: Web Content
Count: 1 / 2

Add-ons
-------

Name: Bypass Paywalls Clean
Type: extension
Version: 2.3.1.0
Enabled: true
ID: {d133e097-46d9-4ecc-9903-fa6a722a6e0e}

Name: I don't care about cookies
Type: extension
Version: 3.3.1
Enabled: true
ID: jid1-KKzOGWgsW3Ao4Q@jetpack

Name: Mozilla Android Components - Ads Telemetry
Type: extension
Version: 92.0.20210806164329.0806165118
Enabled: true
ID: ads@mozac.org

Name: Mozilla Android Components - Browser Icons
Type: extension
Version: 92.0.20210806164329.0806164930
Enabled: true
ID: icons@mozac.org

Name: Mozilla Android Components - Firefox Accounts WebChannel
Type: extension
Version: 92.0.20210806164329.0806165239
Enabled: true
ID: fxa@mozac.org

Name: Mozilla Android Components - ReaderView
Type: extension
Version: 92.0.20210806164329.0806165113
Enabled: true
ID: readerview@mozac.org

Name: Mozilla Android Components - Search Telemetry
Type: extension
Version: 92.0.20210806164329.0806165118
Enabled: true
ID: cookies@mozac.org

Name: Mozilla Android Components - Web Compatibility Interventions
Type: extension
Version: 25.3.0
Enabled: true
ID: webcompat@mozilla.org

Name: Mozilla Android Components - WebCompat Reporter
Type: extension
Version: 2.0.1
Enabled: true
ID: webcompat-reporter@mozilla.org

Name: uBlock Origin
Type: extension
Version: 1.37.2
Enabled: true
ID: uBlock0@raymondhill.net

Name: Undo Close Tab
Type: extension
Version: 7.4.0
Enabled: true
ID: {4853d046-c5a3-436b-bc36-220fd935ee1d}

Name: Dark Reader
Type: extension
Version: 4.9.34
Enabled: false
ID: addon@darkreader.org

Name: Nimbus Screen Capture: Screenshots, Annotate
Type: extension
Version: 15.6.9
Enabled: false
ID: nimbusscreencaptureff@everhelper.me

Name: Simple Tab Groups
Type: extension
Version: 4.5.1
Enabled: false
ID: simple-tab-groups@drive4ik

Name: Tab Session Manager
Type: extension
Version: 6.9.0
Enabled: false
ID: Tab-Session-Manager@sienori

Graphics
--------

Features
Compositing: WebRender
Asynchronous Pan/Zoom: touch input enabled; autoscroll enabled; smooth pinch-zoom enabled
WebGL 1 Driver WSI Info: EGL_VENDOR: Android EGL_VERSION: 1.4 Android META-EGL EGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context IsWebglOutOfProcessEnabled: 0
WebGL 1 Driver Renderer: ARM -- Mali-G76
WebGL 1 Driver Version: OpenGL ES 3.2 v1.r18p0-01rel0.c9f554cb2d312e725c77b822a0503b07
WebGL 1 Driver Extensions: GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic
WebGL 1 Extensions: ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_float_blend EXT_sRGB EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context
WebGL 2 Driver WSI Info: EGL_VENDOR: Android EGL_VERSION: 1.4 Android META-EGL EGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context IsWebglOutOfProcessEnabled: 0
WebGL 2 Driver Renderer: ARM -- Mali-G76
WebGL 2 Driver Version: OpenGL ES 3.2 v1.r18p0-01rel0.c9f554cb2d312e725c77b822a0503b07
WebGL 2 Driver Extensions: GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic
WebGL 2 Extensions: EXT_color_buffer_float EXT_float_blend EXT_texture_filter_anisotropic MOZ_debug OVR_multiview2 WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context
Uses Tiling: true
Uses Tiling (Content): true
Target Frame Rate: 60
GPU #1
Active: Yes
Description: Model: VOG-L29, Product: VOG-L29, Manufacturer: HUAWEI, Hardware: kirin980, OpenGL: ARM -- Mali-G76 -- OpenGL ES 3.2 v1.r18p0-01rel0.c9f554cb2d312e725c77b822a0503b07
Vendor ID: ARM
Device ID: Mali-G76
Driver Version: OpenGL ES 3.2 v1.r18p0-01rel0.c9f554cb2d312e725c77b822a0503b07
RAM: 0

Diagnostics
AzureCanvasBackend: skia
AzureContentBackend: skia
AzureFallbackCanvasBackend: skia
CMSOutputProfile: Empty profile data
Display0: 1080x2340
DisplayCount: 1
TileHeight: 512
TileWidth: 512
Device Reset: Trigger Device Reset
Decision Log
HW_COMPOSITING:
available by default
force_enabled by user: Force-enabled by pref
OPENGL_COMPOSITING:
available by default
force_enabled by user: Force-enabled by pref
WEBRENDER:
available by default
WEBRENDER_QUALIFIED:
available by default
WEBRENDER_COMPOSITOR:
disabled by default: Disabled by default
WEBRENDER_PARTIAL:
available by default
WEBRENDER_SHADER_CACHE:
available by default
WEBRENDER_OPTIMIZED_SHADERS:
available by default
WEBRENDER_ANGLE:
available by default
unavailable by env: OS not supported
WEBRENDER_DCOMP_PRESENT:
available by default
disabled by user: User disabled via pref
unavailable by env: Requires Windows 10 or later
unavailable by runtime: Requires ANGLE
WEBRENDER_SOFTWARE:
available by default
OMTP:
disabled by default: Disabled by default
WEBGPU:
disabled by default: Disabled by default

Media
-----

Audio Backend: opensl
Max Channels: 2
Preferred Sample Rate: 48000
Roundtrip latency (standard deviation): ...
Output Devices
Name: Group
Default audio output device:
Input Devices
Name: Group
Default audio input device:
Media Capabilities
Enumerate database

Environment Variables
---------------------

Important Modified Preferences
------------------------------

dom.presentation.device.name: VOG-L29
dom.w3c_pointer_events.enabled: true
extensions.lastAppVersion: 92.0a1
idle.lastDailyNotification: 1628231139
media.gmp.storage.version.observed: 1
network.dns.disablePrefetch: true
network.http.speculative-parallel-limit: 0
network.predictor.enabled: false
network.prefetch-next: false
network.trr.blocklist_cleanup_done: true
privacy.purge_trackers.date_in_cookie_database: 0
privacy.purge_trackers.last_purge: 1628231153627
security.remote_settings.crlite_filters.checked: 1628118322
security.remote_settings.intermediates.checked: 1628118322
storage.vacuum.last.index: 0

Important Locked Preferences
----------------------------

fission.autostart.session: false

Accessibility
-------------

Activated: true
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.32
Version in use: 4.32

NSS
Expected minimum version: 3.69 Beta
Version in use: 3.69 Beta

NSSSMIME
Expected minimum version: 3.69 Beta
Version in use: 3.69 Beta

NSSSSL
Expected minimum version: 3.69 Beta
Version in use: 3.69 Beta

NSSUTIL
Expected minimum version: 3.69 Beta
Version in use: 3.69 Beta

Startup Cache
-------------

Disk Cache Path: /data/user/0/org.mozilla.fenix/files/mozilla/tbagpsi5.default/startupCache/startupCache.8.little
Ignore Disk Cache: false
Found Disk Cache on Init: true
Wrote to Disk Cache: false

Internationalization & Localization
-----------------------------------

Application Settings
Requested Locales: ["en-US","en-HK"]
Available Locales: ["an","ar","ast","az","be","bg","bn","br","bs","ca","cak","cs","cy","da","de","dsb","el","en-CA","en-GB","en-US","eo","es-AR","es-CL","es-ES","es-MX","et","eu","fa","ff","fi","fr","fy-NL","ga-IE","gd","gl","gn","gu-IN","he","hi-IN","hr","hsb","hu","hy-AM","id","is","it","ja","ka","kab","kk","kn","ko","lij","lo","lt","lv","ml","mr","ms","my","nb-NO","ne-NP","nl","nn-NO","oc","pa-IN","pl","pt-BR","pt-PT","rm","ro","ru","sk","sl","son","sq","sr","sv-SE","ta","te","th","tr","trs","uk","ur","uz","vi","wo","xh","zam","zh-CN","zh-TW"]
App Locales: ["en-US","en-CA","en-GB"]
Regional Preferences: ["en-US","en-HK"]
Default Locale: "en-US"
Operating System
System Locales: ["en-US","en-HK"]
Regional Preferences: ["en-US","en-HK"]

Remote Debugging (Chromium Protocol)
------------------------------------

Accepting Connections: false
URL:

**Comment by anotherus3r** [comment]
Same problem. Happens on every page with dynamic content, like videos or banners that move.

Device: Huawei Mate 20 lite, EMUI 10.0 (Android 10)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724728

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Could anyone affected by this issue please try going to about:config, setting gfx.webrender.allow-partial-present-buffer-age to false, restart firefox (by swiping it away in the app switcher then reopening it), and see if that fixes it?

**Comment by jamienicol** [comment]
Additionally, if you are able to find the regression range for the bug that would be incredibly helpful. I'll copy my instructions from the other bug report:

We have a tool called [mozregression](https://mozilla.github.io/mozregression/quickstart.html) for this purpose.

You can find a download link from that page if you're running a windows computer, or if you're on Mac or Linux I find it easiest to use the command line:

```
pip install --user mozregression
```

Make sure your phone is plugged in to your computer, then if using the GUI launch the application and click the scissor icon to start a new bisection. You need to tell it to use the "geckoview example" application, and the last known good date (pick a conservative one if you don't know for sure, eg 2 weeks ago). Then start the bisection.

or on the command line:

```
mozregression --app gve --good 2021-07-27
```

This will download and install a series of versions of firefox. For each one you answer "good" or "bad", and eventually it'll tell you what commit(s) caused the regression. Please let me know if you need any help with that!

**Comment by tobias-kuendig** [comment]
> Could anyone affected by this issue please try going to about:config, setting gfx.webrender.allow-partial-present-buffer-age to false, restart firefox (by swiping it away in the app switcher then reopening it), and see if that fixes it?

That did not help, unfortunately! Huawei Mate P20, FF 92.0a1 Build #2015827083

**Comment by anotherus3r** [comment]
> Could anyone affected by this issue please try going to about:config, setting `gfx.webrender.allow-partial-present-buffer-age` to false, restart firefox (by swiping it away in the app switcher then reopening it), and see if that fixes it?

This didn't fix the issue on Huawei Mate 20 lite.

**Comment by tobias-kuendig** [comment]
> mozregression --app gve --good 2021-07-27

I am unable to reproduce the issue with any build of the "GeckoView Example" builds from the last seven days.

**Comment by jamienicol** [comment]
@tobias-kuendig Thanks for testing! That's interesting. But you can reproduce in Firefox Nightly. If you go to Firefox Nightly's settings, then "About Firefox Nightly", what does the version number next to "GV:" say? eg "GV: 92.0a1-20210808090543".

You can then try launching that specific geckoview version by using the last part of that version number in mozregression's `launch` command.

eg `mozregression --app gve --launch 20210808090543` (but replace the version with whatever your firefox nightly said)

**Comment by gmadjara** [comment]
> Could anyone affected by this issue please try going to about:config, setting `gfx.webrender.allow-partial-present-buffer-age` to false, restart firefox (by swiping it away in the app switcher then reopening it), and see if that fixes it?

It didn't fix the issue on P30 pro.

**Comment by tobias-kuendig** [comment]
> But you can reproduce in Firefox Nightly. If you go to Firefox Nightly's settings, then "About Firefox Nightly", what does the version number next to "GV:" say? eg "GV: 92.0a1-20210808090543".

I did install the exact build, and it does not have any flickering.

Note: I get the following error output from the `mozregression` command, but the APK is installed on my home screen just fine. That should not a problem (running on Ubuntu 20.04)?


```
$ mozregression --app gve --launch 20210808090543 
**********
You should use a config file. Please use the --write-config command line flag to help you create one.
**********

0:02.37 INFO: Downloading build from: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/VBJeJKyBQA6v-_0j-v0JpQ/runs/0/artifacts/public%2Fbuild%2Fgeckoview_example.apk
===== Downloaded 100% =====
 0:06.01 INFO: Running mozilla-central build built on 2021-08-08 11:13:08.846000, revision 56e4a835
 0:06.03 WARNING: Unable to find application.ini
 0:06.03 WARNING: Unable to find platform.ini
 0:06.03 INFO: Using adb 1.0.39
 0:06.19 INFO: /system/bin/ls -1A supported
 0:06.22 INFO: Native cp support: True
 0:06.26 INFO: Native chmod -R support: True
 0:06.29 INFO: Native chown -R support: True
 0:06.41 INFO: Native normal pidof support: True
 0:06.53 INFO: adbd not restarted as root
 0:06.56 INFO: su -c setenforce 0 exitcode 127, stdout: None
 0:06.71 WARNING: Unable to set SELinux Permissive due to args: adb wait-for-device shell setenforce Permissive, exitcode: 1, stdout: setenforce: Couldn't set enforcing status to 'Permissive': Permission denied.
 0:07.13 INFO: Setting test_root to /data/local/tmp/test_root
 0:12.97 INFO: Setting run_as_package to org.mozilla.geckoview_example
 0:13.70 INFO: Resetting test root from /data/local/tmp/test_root to /data/data/org.mozilla.geckoview_example/test_root
 0:13.75 ERROR: Unable to install /tmp/tmpew7ok_9j/56e4a835369f-shippable--mozilla-central--arm--geckoview_example.apk (error: Unable to set test_root to /data/data/org.mozilla.geckoview_example/test_root)
 0:13.75 ERROR: Unable to install /tmp/tmpew7ok_9j/56e4a835369f-shippable--mozilla-central--arm--geckoview_example.apk (error: Unable to set test_root to /data/data/org.mozilla.geckoview_example/test_root)

```

**Comment by jamienicol** [comment]
I don't think that error matters, since it appeared to install okay. Hmm. I can't think why it would reproduce in fenix but not the geckoview example app, but that's quite frustrating.

Do you know which day or version of fenix this started on?

**Comment by jamienicol** [comment]
@tobias-kuendig [Here](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2021) we have all past builds of Fenix nightly, organized by date. I would be so so grateful if you could try downloading and installing them to figure out which was the first version that has the bug

**Comment by anotherus3r** [comment]
@jamienicol 

The issue seems to appear between these two versions:

- version **without** issue:

92.0a1 (Build #2015825971)
AC: 92.0.20210803143316, 2347602c39
GV: 92.0a1-20210802093840
AS: 81.0.1

2021-08-03T22:55:59.390643

- version **with** issue:

92.0a1 (Build #2015826123)
AC: 92.0.20210804145319, 1efe95ff30
GV: 92.0a1-20210804093931
AS: 81.0.1

2021-08-04T17:38:53.819352

Tested on a Huawei Mate 20 lite with a Mali-G51 MP4 GPU and Android 10.

**Comment by jamienicol** [comment]
Thank you @anotherus3r that's very helpful.

That gives [this range](https://hg.mozilla.org/mozilla-central/pushloghtml?startdate=2021-08-03&enddate=2021-08-05), of which [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1720169) looks the most suspicious. It has in fact been reverted due to causing some other issues, so perhaps this will be fixed in an upcoming nightly version. If you do notice that this problem goes away after a Firefox update, please do let me know.

In the meantime I have ordered a Huawei device so that I can investigate this further.

**Comment by anotherus3r** [comment]
@jamienicol Seems like reverting the change you mentioned did solve the issue.

The flickering is not present anymore on the latest Nightly: 

93.0a1 (Build #2015827507)
AC: 93.0.20210811143137, 5078b5105b
GV: 93.0a1-20210811093702
AS: 82.1.0

2021-08-11T22:01:46.893797

**Comment by jamienicol** [comment]
Thanks for confirming @anotherus3r. And sorry for the inconvenience this bug has caused you. I have a Huawei device now, so I will ensure that this issue is avoided when I rewrite the patch in question.
