### ISSUE TITLE
Error in standard input field of Startpage.com, [Bug]

### ISSUE THREAD

**Issue by Paulchen232** [mozilla-mobile/fenix#20734]
when you have reached the end of the standard input field of Startpage.com, the input is initially no longer displayed. E.g. if you enter "host: startpage.com feedback", "ck" is not displayed. You can only see everything again from 5 letters onwards. Anything goes with Chrome.

Kind regards
Oswald Fischer

**Comment by Paulchen232** [comment]
![Screenshot_20210807-091119](https://user-images.githubusercontent.com/24520281/128594554-2a17217e-279f-4a3f-8d9d-f0094f7e16e9.png)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724743

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
