### ISSUE TITLE
[Bug]: Url swiping goes to inactive tab 

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#20742]
### Steps to reproduce

Have tabs open
Choose a tab and make its left and right neighboor inactive
Go to the selected tab and swipe left/rigth on the url
You wil be able to go to some inactive tab and reactivate them

### Expected behaviour

Swiping should open the left/right active tab

### Actual behaviour

Swiping open the left/right inactive tab

### Device name

pixel 4a

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17511)

**Comment by jonalmeida** [comment]
@Octoton I'm not sure I follow the difference between the expected and actual behaviour. 🙂

**Comment by Octoton** [comment]
When our are on a active tab, it is possible to go to a inactive tab by swiping on the url (even if the selected tab is in the middle of the active tab)
What i means is that url swiping doesn't follow what the tab tray order is showing as it take into account both active and inactive tab (as if there was only one array withboth type of tab and swiping only incermented the index without look at the tab type)

**Comment by jonalmeida** [comment]
Ah, gotcha, that makes sense now. Thanks for clarifying!
