### ISSUE TITLE
FNX-5437 ⁃ [Bug] Title shows on toolbar when opened from external source

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2074]
## Steps to reproduce
1. Open a link from twitter app (or messages, etc.)

### Expected behavior
1. Browser toolbar displays just the URL

### Actual behavior
1. Browser toolbar displays both the URL and the title

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 4/29 build.
