### ISSUE TITLE
Mozilla Android lags when too many tabs are open

### ISSUE THREAD

**Issue by Blackhat73** [mozilla-mobile/fenix#20747]
### Steps to reproduce

1.Open Mozilla Android 
2.Open Multiple Tabs
3.Try Switching the tabs
4.The Application start lagging

### Expected behaviour

The Application Should not Lag

### Actual behaviour

The Application is Lagging

### Device name

Samsung S8+

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

89.0.10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17514)

**Comment by cadeyrn** [comment]
> Firefox Beta 89.0.10

Do you see the same the issue with the **current** version of Firefox?

**Comment by LaviniaL99** [comment]
Hello @Blackhat73 

I tested the above issue on the latest Nightly build(98.0a1) and latest Beta version (97.0.0 -beta6) and i was not able to reproduce the issue.

**Device used:**

- Samsung S10 (Android 10)

Can you please verify the flow again and let me know if you are still able to reproduce it on the latest builds? If yes, please attach a video for it.
Thanks!
