### ISSUE TITLE
m.win007.com weird issue

### ISSUE THREAD

**Issue by rhythmbird** [mozilla-mobile/fenix#20741]
### Steps to reproduce

1, go to m.win007.com, at the first time, the content displayed correctly.
2, click "篮球"（ Basketball ） on  center/right to switch to the basketball page,  then switch back "足球"（ Football）

### Expected behaviour

The content should be displayed like the first time.

### Actual behaviour

No content displayed. And there is always “数据加载中……”（ Data loading.）

### Device name

Meizu 7 pro

### Android version

9

### Firefox release type

Firefox

### Firefox version

90.1.3

### Additional information

I have tried on two different cell phones,  the issue is the same.  Chrome or alike work well on this website,  even the desktop version of firefox works well on on this page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17510)

**Comment by SoftVision-LorandJanos** [comment]
Hi @rhythmbird ! Thank you for your report!
I could reproduce the issue you described with the difference that the content wasn't loaded the first time either.
Checked on an other browser as well (Chrome) where it loads as expected.
Tested on the latest Release (91.1.0) and the latest Nightly (92.0a1 - 2021-08-09T05:09:22.101391.
Devices used:
- Samsung Galaxy Tab S3 (Android 9)
- Google Pixel 4 (Android 11)
- LG Nexus 5 (Android 6.0.1).

**Comment by rhythmbird** [comment]
Thanks for your reply. Firefox does load the content correctly. Uh, at the first time for me but never again after the issue occurred. If I clean the data of firefox through the settings of Android, it works once until the issue happens again, 😂. And if  I have an  ad block extension (saying ublock)  installed it will never work even at the first time( I mean displaying the content).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly (2022-02-07).
Tested with an Oppo Reno 6 (Android 11).

**Comment by Amejia481** [comment]
cc @agi @jonalmeida

**Comment by jonalmeida** [comment]
This works for me some times. I think it might be web compat though or just a web app that has some bugs - there is nothing that signifies it's GV related.

<img width="479" alt="Screen Shot 2022-02-07 at 12 57 47 PM" src="https://user-images.githubusercontent.com/1370580/152845140-da18d04a-f116-435a-a90a-8250e23e852b.png">

**Comment by rhythmbird** [comment]
Since the web site (win007) has been down for a month or more, I guess your guys can safely close this bug now.
