### ISSUE TITLE
[Bug]: Browser always shows "Sign in to synchronise" instead of the signed-in user's email upon startup

### ISSUE THREAD

**Issue by mduchev** [mozilla-mobile/fenix#20750]
### Steps to reproduce

1. Start the app
2. Click on the three dot menu from the upper right corner

### Expected behaviour

The row below "Add-ons" to show the logged-in user's email.

![Screenshot_20210808-211930~2](https://user-images.githubusercontent.com/8217099/128641780-e70e1a45-655c-469b-9618-aa946352e72c.png)

### Actual behaviour

The row below that "Add-ons" shows the text "Sign in to synchronise".

![Screenshot_20210808-212432](https://user-images.githubusercontent.com/8217099/128641918-973b5180-26c1-40f0-ba88-10c03a3a020d.png)

### Device name

Google Pixel 4a 5G

### Android version

Android 12 Beta 3

### Firefox release type

Firefox

### Firefox version

91.1.0

### Additional information

If I click on the "Sign in to synchronise" row, I receive indication that I'm indeed signed-in.

![Screenshot_20210806-184836](https://user-images.githubusercontent.com/8217099/128642034-8453b4ad-8e0b-4a4a-b3ee-f9a864d69e70.png)

The issue fixes itself as soon as I either click on the "Sign in to synchronise" row, or click on the Settings row and immediately go back and open the 3-dot menu again. 

NB: Just to confirm that this is not an Android 12 beta issue - this also happens on Nokia 7.1 with Android 11.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17516)

**Comment by mduchev** [comment]
Still there.

**Comment by mduchev** [comment]
I think that this can be closed, since there is no "Sign in to synchronise" row in the popup menu anymore.

**Comment by csadilek** [comment]
Thanks, it will still show "Sync and save data" though, and that faces a similar bug of being delayed until initialization is complete. We will fix this as part of https://github.com/mozilla-mobile/fenix/issues/25486.
