### ISSUE TITLE
[Bug]: Can't login to Subway app

### ISSUE THREAD

**Issue by Graydenn** [mozilla-mobile/fenix#20753]
### Steps to reproduce

1. Download the Subway (sub sandwiches one) app from the Play Store.
2. Open the app and tap "Sign In" – the app will open Firefox to complete this step.
3. Enter your information and sign in.

### Expected behaviour

You should log in to the app. This is the behavior that occurs on any other browser I tested.

### Actual behaviour

Nothing happens when you tap the login button.

### Device name

OnePlus 8 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Additional information

Though the bug was reported under Firefox Nightly, I was able to replicate it in any version of Firefox and even other browsers based off of Firefox.

**Comment by SeburoSUMO** [comment]
@Graydenn Do you have open links in apps set in the Firefox for Android settings?

**Comment by Graydenn** [comment]
There's no difference with or without this setting enabled.

**Comment by Graydenn** [comment]
My bad. This seems to be a filter issue with ublock origin, disabling it on the login page solved the issue.
