### ISSUE TITLE
[Bug]: Flickering black box appears randomly on Firefox Nightly for Android while browsing

### ISSUE THREAD

**Issue by arrbegg** [mozilla-mobile/fenix#20768]
### Steps to reproduce

1. Open any site.
2. Scroll around the screen.

### Expected behaviour

No artifacts should be present while browsing.

### Actual behaviour

Flickering black boxes appear randomly while scrolling.

### Device name

Huawei P20 Pro

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1(Build #2015826779)

### Additional information

[https://user-images.githubusercontent.com/10772700/128832210-492684b5-41fd-452f-81b5-ba2502a7a142.mp4](url)
[https://streamable.com/ve8i85](url)

**Comment by kbrosnan** [comment]
This is tracked at bz-1724728
