### ISSUE TITLE
[Bug]: Text in textarea disappears while typing

### ISSUE THREAD

**Issue by Daniel15** [mozilla-mobile/fenix#20766]
### Steps to reproduce

1. Start typing text in a textarea. I've encountered this issue on m.facebook.com, GitHub.com, and LowEndTalk.com, but it likely occurs on other sites too

### Expected behaviour

Entering text works

### Actual behaviour

Text entry works for a while, but at some point Firefox clears the entire textarea while typing. This is really frustrating as in some cases I've entered over a paragraph of text before Firefox decides to delete the entire thing :(

### Device name

Samsung Galaxy S10

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Device logs

N/A

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1724811

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
