### ISSUE TITLE
[webcontent] -- Letsencrypt.org certificate not accepted on Android (but it is on PC)

### ISSUE THREAD

**Issue by Furrball75** [mozilla-mobile/fenix#20769]
## Site with issue and any steps to reproduce

https://80.style

### Expected behavior

Should be allowed HTTPS access via certificate by Letsencrypt.org authority.

### Actual behavior

PC version of Firefox has no problems with that certificate, Android version does.
What's up with the inconsistence? Is that meant to be, or is it a mistake?
Letsencrypt.org is an organization supported by the EFF, just saying...

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)

Of course not.

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Nope, they all accept that CA as legit.
Including Mozilla Firefox on a Windows 10 PC.

### Device information

* Android device: ?
* Fenix version: ?

Lenovo Tab 10.4
Version downloaded as of today.
![firefox on pc](https://user-images.githubusercontent.com/88711511/128840722-35a6982b-4c03-4123-b4f3-226be6c5867b.PNG)

**Comment by cadeyrn** [comment]
works for me (as for any other website with Let's Encrypt certificate).

**Comment by Furrball75** [comment]
*scratches his head*

Good to know...
I may take a screenshot, what can I say?
I downloaded Firefox on my Android earlier this morning, and it was not recognizing that CA as trusted.
I was surprised... but I'm not lying, I wouldn't have a reason to lie.
Lemme re-check...

**Comment by Furrball75** [comment]
There you go... tried to uninstall and reinstall Firefox freshly on the tablet. Tried again, default settings for privacy and tracking, and it says in his opinion, the CA isn't trusted or the certificate is self-signed, which is not because I update it regularly via "certbot renew" every three months. The site's my own, of course, but the certificate chain can be verified by everyone with an audit. And besides all that, it triggers no warnings in any other browsers (again, not even on Firefox in its PC version).

![Screenshot_2021-08-10-14-24-57-673](https://user-images.githubusercontent.com/88711511/128866775-0ad115ec-618c-4503-bb64-38b18de05e4a.jpeg)

**Comment by Furrball75** [comment]
Hmm... ok, I went on to audit the site and the validator says the certificate chain is incomplete. That MAY be te issue, assuming it fits the part of the error message that says "or the server is not sending the correct intermediate certificates". I'll look into it on my side, but still... I'd look into Firefox's problem with inconsistent behavior between the PC and the Android version.

![sslaudit](https://user-images.githubusercontent.com/88711511/128869226-4e7d0a8b-cc9d-4984-99d9-b73f4875ba97.PNG)

**Comment by Furrball75** [comment]
Uh... wait, maybe I've found the explanation.
Still... I wish they all behaved the same, but it seems it's a known issue, not necessarily a Firefox exclusive...

https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#21-use-complete-certificate-chains

Says "An invalid certificate chain effectively renders the server certificate invalid and results in browser warnings. In practice, this problem is sometimes difficult to diagnose because **some browsers can reconstruct incomplete chains and some can’t**."

Guess that solves the issue as per my curiosity, and I guess we can close it.
I've got work to do... sorry for bothering.

**Comment by Furrball75** [comment]
Yeap, I can confirm it worked. The problem was that I didn't get how certbot calls the file holding the certificate PLUS the CA root certificate "fullchain.pem", and just loaded "cert.pem" believing that'd be all.

Sorry again, my fault.
I'm closing the issue, hope it'll help someone else figure that out.
My confusion originated from certbot's naming scheme for files, ultimately.

**Comment by kbrosnan** [comment]
This is bz-1520297
