### ISSUE TITLE
[Bug]: bookmarklet unable to modify DOM of a page it opened.

### ISSUE THREAD

**Issue by thomasleplus** [mozilla-mobile/fenix#20763]
### Steps to reproduce

1. create a new bookmarklet with the following URL:
 ```
javascript:(function()%7B%22use%20strict%22%3B%20var%20t%20%3D%20window.open('about%3Ablank').document%3B%20t.write('%3C!DOCTYPE%20html%3E%3Chtml%20lang%3D%22en%22%3E%3Chead%3E%3Ctitle%3ESource%3C%2Ftitle%3E%3Cmeta%20charset%3D%22utf-8%22%2F%3E%3C%2Fhead%3E%3Cbody%2F%3E%3C%2Fhtml%3E')%3B%20t.close()%3B%20t.body.appendChild(t.createElement('pre')).appendChild(t.createElement('code')).appendChild(t.createTextNode(document.documentElement.outerHTML))%3B%20%7D)()
````
This corresponds to the following JavaScript code (for readability):
```
"use strict";
var t = window.open('about:blank').document;
t.write('<!DOCTYPE html><html lang="en"><head><title>Source</title><meta charset="utf-8"/></head><body/></html>');
t.close();
t.body.appendChild(t.createElement('pre')).appendChild(t.createElement('code')).appendChild(t.createTextNode(document.documentElement.outerHTML));
```

2. browse any web page.
3. open the bookmarklet.

### Expected behaviour

The new page that opens should contain the current page's source code.

This works as a bookmarklet on Safari and Chrome (both on iOS and Android) but does not work on Firefox Mobile (neither on iOS or Android). It does work in all 3 browsers on both platforms as a link, just not as a bookmarklet. You can test the link version [here](https://thomasleplus.github.io/bookmarklets/#view-source).

### Actual behaviour

The newly opened page remains empty (about:blank).

### Device name

Google Pixel 3 XL

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.3 (Build #2015824995)

**Comment by kbrosnan** [comment]
duplicate https://github.com/mozilla-mobile/fenix/issues/2871
