### ISSUE TITLE
[Bug]: Inactive tabs do not have a grey border 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20762]
### Steps to reproduce

1. Have an active tab and inactive tab in the tabs tray.
2. Observer the border around both items.

### Expected behaviour

There should be a grey border around the entire inactive section.

### Actual behaviour

Only active tabs have a grey border, the inactive tab section does not.

### Device name

All devices

### Android version

All versions

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

### Additional information

Observe no grey border around the inactive section in this screenshot:
<img width="527" alt="Screen Shot 2021-08-09 at 12 22 37 PM" src="https://user-images.githubusercontent.com/1370580/128744596-ed24024a-c0fd-4203-9c2c-0dad9eadd5d3.png">

cc: @topotropic

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (94.0a1 - 2021-10-04T05:10:50.531272).

The border is displayed in dark and light theme.

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
