### ISSUE TITLE
[Bug]:  language configuration/choice for voice input

### ISSUE THREAD

**Issue by bbinet** [mozilla-mobile/fenix#20761]
### Steps to reproduce

Currently the voice input from URL bar does not allow any choice of input language, voice input from (soft)-keyboard has this feature.

### Expected behaviour

Voice input language should be configurable.

### Actual behaviour

Voice input is always in english.

### Device name

Samsung Galaxy S5

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17522)

**Comment by bbinet** [comment]
The initial bug was reported on bugzilla, but it still applies for me:
https://bugzilla.mozilla.org/show_bug.cgi?id=1284871

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible.
The voice input language is still not configurable.
