### ISSUE TITLE
Implement Material You theming

### ISSUE THREAD

**Issue by mduchev** [mozilla-mobile/fenix#20778]
### What is the user problem or growth opportunity you want to see solved?
Since the first Android 12 beta, Google has been pushing the new [Material You design](https://material.io/blog/announcing-material-you). We've already seen many apps adapting this new theming. This is even more true with most of Google's apps and especially with latest [Canary version of Chrome](https://www.androidpolice.com/2021/08/09/chrome-gets-even-more-colorful-with-its-big-material-you-revamp/). I know that it's still early to have this change inside Firefox, but the official Android 12 release is almost here, so we have to think of implementing it at some point, or at least to start tinkering with it. We're expecting the fourth beta of Android 12 any time now, which will come with the final APIs.

https://developer.android.com/about/versions/12/overview
![](https://developer.android.com/about/versions/12/images/android-12-desktop-timeline-en-overpg.png)

### How do you know that this problem exists today? Why is this important?
Firefox, like many other apps, hasn't implemented (or even started to experiment with) the new Material You design. It would be good at some point to have this new design come to Firefox on Android as well, since it would increase the UI/UX substantially.

### Who will benefit from it?
All users running Android 12+
It would also help with switching of the users from Chrome to Firefox at some point, since the UI will look a lot nicer with this new theming.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17535)

**Comment by litLizard69** [comment]
Good idea but I doubt Mozilla will care at all. They are ignoring users since years by butchering the UI after v68..

**Comment by incapable** [comment]
I fully support this, chrome will blend in with the OS way nicer at this point. It would really help for Firefox to implement this to get a more cohecive experience. I'd expect using the userchrome mechanics as we see on Windows, and patching it in to the material you api, would achieve this with relative ease.

Though i'm not sure how much the codebases for the windows and android build differ

**Comment by rokejulianlockhart** [comment]
@incapable, the codebases for Android and Windows are almost entirely different.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1808766

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
