### ISSUE TITLE
FNX-5439 ⁃ [Bug] Cannot copy text in custom tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#2077]
## Steps to reproduce
* Open a custom tab (I used a link in an email)
* Long press text to copy

### Expected behavior
Text is highlighted, pop-up appears so text can be copied

### Actual behavior
Text is highlighted but pop-up does not appear.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1917

Workaround is to open tab in full Fenix browser.

**Comment by sv-ohorvath** [comment]
Cannot reproduce this on the 5/17 build. Devices: Note 8 (Android 9), P9 lite (Android 6).
Please reopen if it's still an issue, maybe a specific website?

**Comment by pwd-github** [comment]
I can reproduce this

1. Open a site in a custom tab
2. Highlight text

Expected Result:
Context menu to copy text

Actual Result:
N/A

Version: 1.0.1926 (Build #11790618 🦎 68.0-20190612114833)
AC: 2.0.0
