### ISSUE TITLE
Homescreen shows an empty space above the toolbar

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#20770]
https://user-images.githubusercontent.com/11428869/128865922-fc5c26b6-beff-4aaf-8886-592af267f4c6.mp4

@eliserichards This seems to be happening after increasing the [margin for the homescreen items list](https://github.com/mozilla-mobile/fenix/blob/5093e7a5d6555984aa5b99f6fa0f04785ab3cd32/app/src/main/res/layout/fragment_home.xml#L71) in https://github.com/mozilla-mobile/fenix/pull/20573.

**Comment by amedyne** [comment]
Looks like the same issue as #20833

**Comment by Mugurell** [comment]
That newer ticket seems to have more traction so I'll close this as a duplicate.
