### ISSUE TITLE
Customise top sites icon

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#20780]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Firefox has customisable top sites in the desktop version but not the Android version.

![image](https://user-images.githubusercontent.com/82655227/128947374-b029604a-d262-4c96-a0e5-70e6e27b08f8.png)

### How do you know that this problem exists today? Why is this important?

Custom web app icons, because sometimes the webpage icon is very ugly or nonexistent.

### Who will benefit from it?

Anyone who uses bookmarks in Firefox for Android or Firefox for iOS, I guess?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17537)

**Comment by cadeyrn** [comment]
I guess you mean the top sites on home screen? Because the screenshot has neither to do with bookmarks nor with bookmarklets. And Firefox for the desktop has no ability (without add-on) to change bookmark icons.

**Comment by SNDST00M** [comment]
Yeah that. I think there's actually a problem where the bookmark favicon is loaded from a new instance of the page instead of the DOM (so customising it with JS doesn't get respected by Firefox).
