### ISSUE TITLE
First page load delayed by some add-ons

### ISSUE THREAD

**Issue by Aranjedeath** [mozilla-mobile/fenix#20789]
## Steps to reproduce

Open the app, doesn't matter how, as long as it was not running already on phone
Open website. Nothing happens for 5-30s. Once page loads, continued operation is fine.

## additional details
I think the cause is that Firefox processes all open tabs at launch. It used to do this *at launch* and it seems like the tab processing is deferred until first connection as of a change within the last 3 months or so. It is likely I have over 1k tabs on my phone, so this is understandable -- except Firefox should not be processing the tabs (or should be doing it in a way that scales better than linearly). I am not accepting any feedback to have fewer tabs, the software must work for the person (User Agent) not the other way. 

### Expected behavior
App loads page at speed my internet is capable of, without initial load/processing delay.

### Device information

* Android device: OnePlus 5T, Android 10
* Fenix version: latest nightly

92.0a1 (Build #2015827275)
AC: 92.0.20210809143330, 6ec00f52db
GV: 92.0a1-20210809093320
AS: 81.0.1

**Comment by Aranjedeath** [comment]
Further investigation: the only startup-related settings I can think of that I changed was to disable DoH (network.trr.mode = 5). This is also disabled for every other supporting browser on the device, so if it matters then there's definitely some issue in FF. I just tested with network.trr.mode=3 (force on) and it did not change the behavior, so that is not the issue.

**Comment by kbrosnan** [comment]
Best info would be a profile of the startup. Though that is not trivial. https://profiler.firefox.com/docs/#/./guide-remote-profiling?id=manual-configuration

**Comment by Aranjedeath** [comment]
I will try to do this tonight, though I have never once done any Android development so everything is going to be completely fresh. Hopefully the documentation you linked is good.

**Comment by MarcLeclair** [comment]
This seems to be an addon issue and we have two issues for it already. I'll close this for now and mark it as a duplicate. If ever there's need to add a profile or we notice this issue stems from a different  source, we can always reopen it!
