### ISSUE TITLE
FNX-5440 ⁃ [Bug] Fenix can unexpectedly share links with itself

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#2078]
## Steps to reproduce
* Load a page
* Click 3-dot -> share

### Expected behavior
Fenix does not appear in Share list

### Actual behavior
Fenix appears in Share list. Selecting it will open the link in a new tab.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1917

fwiw, I don't think we're supposed to handle the share intent (which is generally for sharing to other people) – we're just supposed to handle the view intent. Fennec does handle share in order to support a different use case though (bookmark, send tab, and something else).

**Comment by softvision-miralobontiu** [comment]
I can confirm this issue on the latest build 1.0.1921 (#11410622), with Sony Xperia Z5 Premium (Android 7.1.1), Huawei Honor 8 (Android 7), and Google Pixel (Android 9).

Steps to reproduce:
1. Load a page.
2. Go to three-dot menu and tap on Share.
3. Tap on Firefox Preview and observe if the page is opened in a new tab.

**Comment by sblatz** [comment]
This seems like a pretty easy fix given we're using a custom share sheet we can just filter Fenix out.

**Comment by sblatz** [comment]
Is this something that we need to do in AC? @jonalmeida

**Comment by ekager** [comment]
Nah we handle building the list in Fenix

**Comment by AndiAJ** [comment]
@sblatz @ekager Should this be applicable to the custom tabs **action button** ?
![20191010_142707](https://user-images.githubusercontent.com/51314259/66565909-4d74b400-eb6c-11e9-9ceb-cc52159f65e2.gif)

**Comment by jonalmeida** [comment]
> @sblatz @ekager Should this be applicable to the custom tabs **action button** ?

This looks fine to me. You're in a Custom Tab, so it doesn't resemble the app itself, so sharing to it is fine.

**Comment by AndiAJ** [comment]
@jonalmeida I've found another way, namely using long tap and afterwards selecting "Share link" from the context menu. 

► Video
![20191027_092037](https://user-images.githubusercontent.com/51314259/67282336-34f48a00-f4da-11e9-9a1e-e10bfba93b53.gif)

**Comment by jonalmeida** [comment]
@AndiAJ this is https://github.com/mozilla-mobile/fenix/issues/2933

Thanks for checking though!
