### ISSUE TITLE
[webcontent]

### ISSUE THREAD

**Issue by techmast** [mozilla-mobile/fenix#20786]
I,m facing a issue, when i browse this [ site](https://meterreviews.com/) i experienced that some of featured images did,nt upload, also ux experience was bad. is it due to my app or it's from website.

**Comment by amedyne** [comment]
@techmast Can you provide the following information?
- Firefox for Android version
- Android Version
- Phone make and model

I tested and browsed the site you linked and it works for me on Firefox v90.1.3, on and Android 11, Pixel 3. I noticed though that the images take some time to load than the rest of the page.
