### ISSUE TITLE
"Inactive tabs" UI should have feature parity with main tab UI: swiping, selecting, etc.

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#20803]
![Screenshot_20210812-090905_Firefox Nightly](https://user-images.githubusercontent.com/76437842/129153481-56757b30-98e7-4a57-8e9f-80374fe5fe86.png)

[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Needing to select multiple tabs from both inactive and main section should be possible, for instance to:
* share mixed types of tabs
* **swiping/flicking** especially to close any number of mixed type of tabs, alongside multiselect
* bookmark any number of mixed type of tabs

### How do you know that this problem exists today? Why is this important?
* Not being able to select these tabs for user actions is lacking in functionality, especially because the user is aware that tabs may disappear automatically if they don't act. Users may want to mass save or mass bookmark for future reference

### Who will benefit from it?
Users expecting a consistent user experience who do not appreciatie wasting time manually pressing X everywhere, especially since the "snack bar" is still overlapping with this X button at the bottom of the viewport.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17555)

**Comment by marcel263** [comment]
still relevant

**Comment by marcel263** [comment]
still relevant

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812851

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
