### ISSUE TITLE
Option to export browser profile folder/settings to local storage

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#2080]
### Why/User Benefit/User Problem
There is no way to locally back up the Fenix profile and settings without having root access to the device and manually copying the folder/settings (which is still not an adequate backup).

It is tedious and time consuming to set up or customize the browser on a new install, new phone or in case of accidental data loss.

### What / Requirements
Add an easy way for people to export profile folder/settings to a local storage or SD card such as in a single zip file

### Acceptance Criteria (how do I know when I’m done?)
Add an easy way for people to export profile folder/settings locally so that the same backup is able to be imported back into Fenix as an EXACT copy of the backup (extensions, extension settings, preferences and settings, themes etc.) for example on a new phone.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11143)

**Comment by yoasif** [comment]
Can we please prioritize this before Play Store cleanup occurs?

I personally ran into this because I got a replacement device due to a hardware issue - and I am *still* trying to figure out how to migrate my open tabs.

Even something as basic as what Signal offers would be handy: https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#android_restore

**Comment by Poopooracoocoo** [comment]
I'd really like to be able to export my bookmarks as an html file and to be able to import them. It'd also be really useful to be able to import/export passwords. I don't mind not being able to export history or site storage. If you could bookmark all tabs or import/export sessions, that'd let you import/export tabs. 

Firefox for desktop gives you heaps of control over this. (the other issues surrounding this were just closed so I'm writing this comment as a way of keeping their content)

**Comment by harabat** [comment]
While this is being actioned, I came up with a temporary workaround. This might be relevant to authors of #6002, #13451, #24922.

You will need to have the same Firefox version installed on your desktop and your Android phone and a USB cable. 

1. O

1. On your phone, enable developer options, then enable remote debugging

    - [How to Access Developer Options and Enable USB Debugging on Android](https://www.howtogeek.com/129728/how-to-access-the-developer-options-menu-and-enable-usb-debugging-on-android-4.2/)

2. On your phone, launch Firefox Android/Fennec/Mull, then go to "*Settings*" and enable "*Remote debugging via USB*"

    <img src="https://user-images.githubusercontent.com/45575009/211395815-3b9b9157-3695-4078-adf0-3cff98af6804.png" alt="debugging_remote" width="200" />

3. On your phone, in Firefox Android/Fennec/Mull, open `about:config`

4. On the desktop, go to `about:debugging`

5. In the left sidebar, connect to the Firefox Android, then click on it

    <img src="https://user-images.githubusercontent.com/45575009/211395917-29e17500-0332-4910-ab4b-4b851137dbeb.png" alt="debugging_connect" width="600" />

6. On your phone, in the mobile browser, scroll all the way to the bottom of the `about:config` tab

    - This will take a little while, but is necessary in order to load all the settings

7. In the `Tabs` dropdown, in `about:config`, click on "*Inspect*"

    <img src="https://user-images.githubusercontent.com/45575009/211395989-bc350b51-b0e3-4605-b87d-95e5657fac2d.png" alt="debugging_inspect" width="600" />

    - This will open a new "*Toolbox (USB)*" tab in the desktop browser

8. On the desktop, in the left sidebar, right-click on the very first element and select "*Edit as HTML*"

    <img src="https://user-images.githubusercontent.com/45575009/211396103-ff13dc33-4fd6-4953-861d-4f32012a9a55.png" alt="debugging_edit" width="600" />

9. When the HTML elements turn into plain text, select all (right-click and "Select all" or just press "Ctrl-A") and copy

    <img src="https://user-images.githubusercontent.com/45575009/211396152-f69ccf28-ba75-4671-ab4d-bc53f468aada.png" alt="debugging_select_all" width="600" />

10. Paste the copied text into an editor and save as `about_config.html`

    - This file is structured in the following way:
        - Relevant information is in first `li` tag and the `input` tag
        - Each setting is a `li` item in the `<ul id="prefs-container">` element
        - When a setting has `default="false"`, the "Reset" button is enabled
        - Settings of `type="text"` have "Toggle" and up/down buttons disabled
        - Booleans (`type="button"`) can be toggled
        - Numbers can be increased and decreased

11. Run the following [Python script](https://gist.github.com/harabat/7c7f8ce1aafc3eb0ab9794984f069935) on the newly created file:

    ``` python
    import json
    import pathlib

    from bs4 import BeautifulSoup

    # read the file
    root = pathlib.Path.cwd()
    file = root / "about_config.html"
    html_doc = file.read_text().replace("\n", "")

    # parse html
    html = BeautifulSoup(html_doc, "html.parser")

    # locate prefs
    prefs_container = html.find(id="prefs-container")

    # collect settings
    settings = {}

    for i in prefs_container.children:
        settings[i.attrs["name"]] = {
            k: v for k, v in i.attrs.items() if k in ["value", "default"]
        }
        settings[i.attrs["name"]]["type"] = i.find("input").attrs["type"]

    # save non-default settings js file (same format as prefs.js and user.js)
    file_js = root / "about_config.js"

    user_prefs_js = ""

    for k, v in settings.items():
        # skip non-default
        if v["default"] == "true":
            continue
        value = v["value"] if v["type"] != "text" else f'"{v["value"]}"'
        user_pref = f'user_pref("{k}", {value});\n'
        user_prefs_js += user_pref

    file_js.write_text(user_prefs_js)

    # save all settings as json file
    file_json = root / "about_config.json"

    with file_json.open("w") as target_json:
        json.dump(settings, target_json, indent=4)
    ```

12. You should now have 2 files, one `about_config.js` file containing your modified preferences (same as what Firefox on desktop stores in `prefs.js`) and a JSON file with all your settings:

    ``` javascript
    user_pref("accessibility.force_disabled", 1);
    user_pref("security.OCSP.require", true);
    ```

    ``` json
    {
        "accessibility.force_disabled": {
            "default": "false",
            "value": "1",
            "type": "number"
        },
        "security.OCSP.require": {
            "default": "false",
            "value": "true",
            "type": "button"
        }
        // other settings...
    }
    ```

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809963

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
