### ISSUE TITLE
Blinking screen when load page froster.org on Android Firefox [Bug]: 

### ISSUE THREAD

**Issue by bugsexplorers** [mozilla-mobile/fenix#20809]
### Steps to reproduce

Open Firefox 
Open site froster.org

### Expected behaviour

When open page froster.org is normal view without blinking

### Actual behaviour

When open page froster.org is screen blinking

### Device name

Xiaomi K20 Pro

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90.1.3 Build 2015824995

### Device logs

I have no information about Crashes

**Comment by bugsexplorers** [comment]
I can't do anything with the browser. Only closing helps.

**Comment by dabat** [comment]
I get the same behavior on a Google pixel 2 running Android 11 and Firefox 91.1.0.

That site opens and renders fine in brave browser 1.28.105, chromium 92.

**Comment by SoftVision-LorandJanos** [comment]
Hi @bugsexplorers ! Thank you for your report!
I tried to reproduce your issue with devices/android versions/FF versions as close to the one in your description as I have available, but it didn't happen on my side.

Would there be any extra detail that might help me get the same result?
Could you check on the latest Nightly if it happens the same way?
Can you make a video of the issue?
Thank you!

Devices used:
- Xiaomi Mi11 Lite (Android 11).
- Google Pixel 4 (Android 11).
- Huawei P30 (Android 10).

Firefox versions:
- RC 90.1.3.
- RC 91.2.0
- Nightly 93.0a1.

**Comment by bugsexplorers** [comment]
Hi **@SoftVision-LorandJanos**
I recorded shot video and place on Google drive
https://drive.google.com/file/d/1v5OJPOLh-iybBN7iHgE85ZXoGzFDaajr/view?usp=sharing
