### ISSUE TITLE
[Bug]: If no tab is selected the "Bookmark" and "Close" options from the ⋮ "more options" menu shouldn't be available

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20810]
### Steps to reproduce
1. Open a tab
2. Open the tabs tray
3. Tap the  ⋮  "more options" button
4. Tap "Select tabs"
5. Tap the  ⋮  "more options" button
6. Tap close

### Expected behaviour
If no tab is selected the close option shouldn't be available

### Actual behaviour
Tapping the close option confirms the closure of an unselected (inexistent) tab.

### Device name
All

### Firefox version
Nightly 92.0a1 from 8/12
Beta 92.0.0 Beta 1

### Additional information
❗ Applicable for the Bookmark option
► Video
![20210812-100107](https://user-images.githubusercontent.com/51314259/129152493-fd8b01d1-aa58-45d8-9d06-70a37417ff98.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17559)

**Comment by sunil9211** [comment]
Hey @AndiAJ  , I would like to work on it, can i?

**Comment by sflorean** [comment]
This is still reproducible on 98.0.0-beta.1 with Sony Xperia (Android 6.0.1).

**Comment by sunilk9211** [comment]
Hi @AndiAJ @sflorean i am trying to find a solution for this issue. Can you help me a little with this?
I want to understand, what should be a solution for this?
Not only "Close", there's "Bookmark" option also showing a message for 0 selected tabs.
1. should it not show any toast message?, or
2. should it not show the options at all if three dots icon is clicked? or
3. should it show a toast like "no tab is selected!"
Please help with this.
