### ISSUE TITLE
[Bug]: Tabs tray synced tabs "Sign in to sync" button size inconsistency

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20811]
### Steps to reproduce
1. Open the tabs tray
2. Tap the synced tabs button
3. Check the "Sign in to sync" button size

### Expected behaviour
End to end display of the "Sign in to sync" button  

### Actual behaviour
Smaller button, oriented to the left.

### Device name
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

### Firefox version
• Nightly 92.0a1 from 8/12
• Beta 92.0.0 Beta 1

### Additional information
► Screenshots 
**Firefox 92.0.0 Beta 2** (left) VS **Firefox 91.0.3** (right)
![sign](https://user-images.githubusercontent.com/51314259/129169051-b954df26-8d76-47d8-9981-c4db760def88.JPG)

**Comment by lobontiumira** [comment]
Reproducible on Lenovo tablet M10 (Android 10) on Beta 93.0.0-beta.1.

**Comment by BFadairo** [comment]
Would I be able to work on this issue?

**Comment by Rishavgupta12345** [comment]
i am working on this

**Comment by Rishavgupta12345** [comment]
#21372 PULL REQUEST CREATED FOR REVIEW

**Comment by sflorean** [comment]
Verified as fixed on Nightly 4/18 with Sony Xperia (Android 6.0.1).
