### ISSUE TITLE
Black squares where images should be - Intel Atom x5-Z8500 HD Graphics (Cherry Trail)

### ISSUE THREAD

**Issue by Doc73** [mozilla-mobile/fenix#20826]
### Steps to reproduce

1. Go to a webpage with photos
2. See the result

### Expected behaviour

I would expect a regular web page with icon and images

### Actual behaviour

No icons; no photos

### Device name

Lenovo Yoga Tab 3 YT3-X90L

### Android version

6.0.1

### Firefox release type

Firefox

### Firefox version

91.1.0

### Additional information

I attach a screenshot in next post

**Comment by Doc73** [comment]
![Screenshot_20210812-211117](https://user-images.githubusercontent.com/1306260/129256563-07c15f82-70f8-4a71-a123-fa475216bf06.png)

**Comment by amedyne** [comment]
@Doc73 I do not see this problem on my end. Do you have any settings that you changed from the default or any addons installed? If yes, can you provide details here. Thanks!

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1725508

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Thank you for the bug report @Doc73. This bug appears to be specific to intel-based tablets. I have ordered myself a device to investigate this further. In the meantime you could try installing firefox beta or nightly, and going to about:config, and setting `gfx.webrender.software` to true, and restarting firefox.

**Comment by Doc73** [comment]
Thank you very much for your suggestions, @jamienicol !
Unfortunately, Firefox Beta doesn't work with your setting: black screen at all!
In the meantime, I uninstalled Firefox, but I can do other tests if necessary.

**Comment by jamienicol** [comment]
Oh, apologies about that! I'll let you know when the issue is resolved, thanks for your help and patience

**Comment by jamienicol** [comment]
@Doc73 could you please check whether the latest version of Firefox has fixed this? Could you also please attach your about:support information to this bug? I have identified the issue and made a fix, however I believe I did not apply it to all of the affected GPUs.

**Comment by jamienicol** [comment]
Thanks @Doc73 , you have the GPU which I missed the first time around, but I have since applied the fix to your GPU too. Firefox Nightly and Beta should already be working correctly, and Firefox release should be updated today with a fix. Please let me know if you have any further issues.
