### ISSUE TITLE
FNX-5442 ⁃ Bottom Location bar well/awesomebar should be a darker gray

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2082]
## Steps to reproduce
1. Open any page in Fenix
1. Show bottom location/address bar 

### Expected behavior
The input area/well for the URL is easily seen (good contrast) and identifiable as an input area. Kiwi Browser/Bromite makes this area more gray than the surrounding area.

Reference Browser and Fenix in Dark mode does this correctly. 

This is also inconsistent with the gray color on the standalone addressbar on home, see   #467

Fenix:

![signal-attachment-2019-04-26-143529](https://user-images.githubusercontent.com/152493/56829027-a5269980-6830-11e9-81a5-19bdf36891d0.png)

Bromite:

![signal-attachment-2019-04-26-143532](https://user-images.githubusercontent.com/152493/56829044-b40d4c00-6830-11e9-9d31-52d28e3196ae.png)

### Actual behavior
The well area is colored white, has very low contrast with surrounding area, and is hard to identify easily as editable. 

### Device information
* Android device: Pixel 2
* Fenix version: ?

**Comment by SKITTLE-LA** [comment]
I don't see a problem with that?
Besides, I think this should be available to change when third-party themes are enabled, right? (After MVP, since add-ons won't be available.)

**Comment by yoasif** [comment]
This may be a dupe of #467 and may already be fixed. Will close if it when I get the next build.

**Comment by yoasif** [comment]
Not fixed in  #467 but I believe the colors in  #467 and reported here should be the same - it would be internally consistent and reflect my expectation.

**Comment by vesta0** [comment]
@yoasif please test again and let us know if you still don't see enough contrast.

**Comment by yoasif** [comment]
It is better, but now it looks kinda disabled, like an informational label, rather than a tappable area where I can input data. 

The design almost feels accidental or like the browser doesn't want my attention put towards it, while the Bromite example feels like a strong sign *inviting* taps. 

It *is* better than before though because it was previously very washed out, whereas now it looks disabled. 

(I did discover the copy feature by long pressing the bar though, so that is an interesting plus.)
