### ISSUE TITLE
Consider stripping coroutine debugger facilities to reduce APK size (by how much?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20828]
The [kotlin coroutines documentation mentions](https://github.com/Kotlin/kotlinx.coroutines/blob/8c98180f177bbe4b26f1ed9685a9280fea648b9c/README.md#avoiding-including-the-debug-infrastructure-in-the-resulting-apk):

>The kotlinx-coroutines-core artifact contains a resource file that is not required for the coroutines to operate normally and is only used by the debugger. To exclude it at no loss of functionality, add the following snippet to the android block in your Gradle file for the application subproject:
>
> ```
>packagingOptions {
>  exclude "DebugProbesKt.bin"
> }
> ```

We could try stripping it, especially only for debug builds, to reduce the size of the APK. I imagine the impact is small but the effort seems small.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17576)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807331

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
