### ISSUE TITLE
[Bug]: Little black bar at bottom of home screen

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#20833]
### Steps to reproduce

When scrolling the home screen slowly up and down then sometimes a small black bar seems to appear at the bottom of the screen, hiding some parts of the home screen.

### Expected behaviour

(No black bar)

### Actual behaviour

![device-2021-08-13-130657](https://user-images.githubusercontent.com/89638/129348491-51664e42-83de-4626-9914-9b34f007dc55.png)

### Device name

PIxel 4a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1 (2021-08-12)

**Comment by sunil9211** [comment]
Hey @pocmo can i please work on this issue?

**Comment by jonalmeida** [comment]
Closing https://github.com/mozilla-mobile/fenix/issues/21421 and moving the SUMO reference to this issue.

User feedback: https://support.mozilla.org/en-US/questions/1356706

**Comment by SoftVision-LorandJanos** [comment]
Reproduced on an older Nightly version (2021-09-22).
Verified as fixed on the latest Nightly (2021-12-15) with both light and dark themes.
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.
