### ISSUE TITLE
Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalStateException: Unrecognized migration type: Migration$Gecko

### ISSUE THREAD

**Issue by davexnet** [mozilla-mobile/fenix#20830]
Reproducible steps can be found here: https://github.com/mozilla-mobile/fenix/issues/20830#issuecomment-898793857

---

### Steps to reproduce

Updated to this release on Marshmallow phone (Samsung J7 Sky Pro)
It crashes as soon as you attempt to open it

### Expected behaviour

it should not crash

### Actual behaviour

it closes with an offer to send a report to Mozilla, which I did.
I am loading this "adb logcat -v time" report at the request of nextbern from the Reddit forum
[android_6_firefox_crash.txt](https://github.com/mozilla-mobile/fenix/files/6979932/android_6_firefox_crash.txt)

### Device name

Samsung j7 Sky Pro

### Android version

Android 6

### Firefox release type

Firefox

### Firefox version

92 beta 2

**Comment by jonalmeida** [comment]
```
08-12 18:20:44.440 E/AndroidRuntime(16086): FATAL EXCEPTION: main
08-12 18:20:44.440 E/AndroidRuntime(16086): Process: org.mozilla.firefox_beta, PID: 16086
08-12 18:20:44.440 E/AndroidRuntime(16086): java.lang.RuntimeException: Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalStateException: Unrecognized migration type: Migration$Gecko
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6502)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at android.app.ActivityThread.access$1800(ActivityThread.java:231)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1889)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at android.os.Looper.loop(Looper.java:148)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at android.app.ActivityThread.main(ActivityThread.java:7422)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at java.lang.reflect.Method.invoke(Native Method)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
08-12 18:20:44.440 E/AndroidRuntime(16086): Caused by: java.lang.IllegalStateException: Unrecognized migration type: Migration$Gecko
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at mozilla.components.support.migration.MigrationResultsStore.fromJSON(MigrationResultsStore.kt:20)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at mozilla.components.support.base.utils.SharedPreferencesCache.getCached(SharedPreferencesCache.kt:2)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at mozilla.components.support.migration.FennecMigrator.getMigrationsToRun(FennecMigrator.kt:2)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at mozilla.components.support.migration.FennecMigrator.migrateAsync(FennecMigrator.kt:2)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at org.mozilla.fenix.MigratingFenixApplication$migrateBlocking$1.invokeSuspend(MigratingFenixApplication.kt:4)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at org.mozilla.fenix.MigratingFenixApplication$migrateBlocking$1.invoke(MigratingFenixApplication.kt:2)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at org.mozilla.fenix.perf.RunBlockingCounterKt$runBlockingIncrement$2.invokeSuspend(RunBlockingCounter.kt:1)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at org.mozilla.fenix.perf.RunBlockingCounterKt.runBlockingIncrement$default(RunBlockingCounter.kt:4)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at org.mozilla.fenix.MigratingFenixApplication.setupInMainProcessOnly(MigratingFenixApplication.kt:13)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:26)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6499)
08-12 18:20:44.440 E/AndroidRuntime(16086): 	... 8 more
08-12 18:20:44.440 D/TimaKeyStoreProvider(16115): TimaSignature is unavailable
```

**Comment by OhNoMoreGit** [comment]
I also hit this on Android 9 running on a Nokia 8.

**Comment by dakkar** [comment]
Same on OnePlus 7 pro, Android 11

[ff-crash.log](https://github.com/mozilla-mobile/fenix/files/6981187/ff-crash.log)

**Comment by CitronDoux** [comment]
Same on Honor 9 Lite (LLD-L31) Android 9
FF Nightly 93.0a1 works well

**Comment by sflorean** [comment]
Tested on 92.0.0-beta.2 (update from 91 Beta 6) and couldn't reproduce the crash on:
- OnePlus A3 (Android 6.0.1)
-  Nokia 6 (A 7.1.1)
- Xiaomi Redmi Note 8T (Android 9)
- Huawei MediaPad M2	(Android 5.1.1)
Will be helpful to know if there are other steps performed.

**Comment by dakkar** [comment]
No extra steps to my knowledge. What can I do to help diagnose?

**Comment by CitronDoux** [comment]
> 
> 
> Tested on 92.0.0-beta.2 (update from 91 Beta 6) and couldn't reproduce the crash on:
> 
>     * OnePlus A3 (Android 6.0.1)
> 
>     * Nokia 6 (A 7.1.1)
> 
>     * Xiaomi Redmi Note 8T (Android 9)
> 
>     * Huawei MediaPad M2	(Android 5.1.1)
>       Will be helpful to know if there are other steps performed.

I think I removed FF nightly before the update (I reinstall nightly after beta crash but no changes for beta)

**Comment by erus** [comment]
Same here on a Mi 9T (Android 10), i'm installing the update to Android 11 and trying again.

**Comment by kbrosnan** [comment]
This looks really bad https://sentry.prod.mozaws.net/operations/firefox-beta/?query=is%3Aunresolved+org.mozilla.fenix.MigratingFenixApplication

**Comment by rvandermeulen** [comment]
We've halted the rollout of 92.0.0-beta.2 while this is under investigation.

**Comment by riozebratubo** [comment]
Beta 3 fixed the crash here (android 9). Thank you!

**Comment by grigoryk** [comment]
@riozebratubo brilliant, thanks for the update! Relevant A-C change: https://github.com/mozilla-mobile/android-components/pull/10810

**Comment by jonalmeida** [comment]
For QA..


### Steps to reproduce
 - Install a Fennec Beta build from [here][0].
 - Add some browsing activity.
 - Install a Fenix Beta 91 build from [here][1]
 - Complete Fennec migration.
 - Install this particular Fenix Beta 92 (92.0.0-beta.2) from here[2].
 - Open the app.

### Expected results
 - After installing Fenix 92.0.0-beta.2, you should be able to continue browsing and verify you browsing activity was migrated over.
 
### Actual results
 - Fenix 92.0.0-beta.2 crashes. 🔥 

### Fixed
 - Fenix 92.0.0-beta.3 or higher should no longer crash. 

[0]: https://archive.mozilla.org/pub/mobile/releases/68.7b1/
[1]: https://github.com/mozilla-mobile/fenix/releases/tag/v91.0.0-beta.6
[2]: https://github.com/mozilla-mobile/fenix/releases/tag/v92.0.0-beta.2
[3]: https://github.com/mozilla-mobile/fenix/releases/tag/v92.0.0-beta.3

**Comment by kbrosnan** [comment]
Beta-3 fixes the startup crash for me.

**Comment by CitronDoux** [comment]
Confirm that beta.3 fixes crash for me.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**  on both **Fenix 92 Beta 3 & 4** using the following devices:

• Pixel 3 (Android 12) 
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.4 ✔️
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.3 -> Fenix 92 Beta.4 ✔️
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.2 💥Crash  -> Fenix 92 Beta 3 ✔️ -> Fenix 92 Beta 4 ✔️ 

• Huawei Mate 20 Lite (Android 10)
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.4 ✔️
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.3 -> Fenix 92 Beta.4 ✔️
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.2 💥Crash -> Fenix 92 Beta 3 ✔️ -> Fenix 92 Beta 4 ✔️ 

• OnePlus A3 (Android 6.0.1)
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.4 ✔️
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.3 -> Fenix 92 Beta.4 ✔️
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.2 💥Crash  -> Fenix 92 Beta 3 ✔️ -> Fenix 92 Beta 4 ✔️

• Huawei Media Pad M2 (Android 5.1.1)
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.4 ✔️
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.3 -> Fenix 92 Beta.4 ✔️
Fennec Beta -> Fenix 91 Beta -> Fenix 92 Beta.2 💥Crash -> Fenix 92 Beta 3 ✔️ -> Fenix 92 Beta 4 ✔️
