### ISSUE TITLE
FNX-5443 ⁃ Bookmarks in "Your Library" appear as "bookmarked" style in quick actions panel

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2083]
## Steps to reproduce
1. Open Fenix
1. Menu > Your Library

### Expected behavior
"Bookmarks" styling shouldn't look "active" or "bookmarked".

### Actual behavior
The bookmarks icon is the same as used when a user swipes up in a quick action panel and the page has been bookmarked. History is not "filled in" like Bookmarks is, so it looks out of place. 

![signal-attachment-2019-04-26-143930](https://user-images.githubusercontent.com/152493/56829369-8674d280-6831-11e9-933e-c610b280fa27.png)

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by ekager** [comment]
@AmyYLee which bookmark icon should be used for this library icon? The outline version from #1601 ?

**Comment by kbrosnan** [comment]
These are items the user has bookmarked so the filled in icon makes sense here.

**Comment by yoasif** [comment]
> These are items the user has bookmarked so the filled in icon makes sense here.

Only issue I find here is that the styling for the history vs. the bookmarks icon looks inconsistent. FWIW, that also applies to the nicer (imo) icons in the settings pages and menus vs. the Library section.

**Comment by AmyYLee** [comment]
> @AmyYLee which bookmark icon should be used for this library icon? The outline version from #1601 ?

Hi, yes can you please use the outline version here?

**Comment by sv-ohorvath** [comment]
Verified as fixed on master. build 5/2
