### ISSUE TITLE
homebutton style change

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#20837]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
In majority of the apps I see home button has similar style however in Firefox the button is entirely different.is it possible to align the icon same as other apps and color to purple (Firefox color)

### How do you know that this problem exists today? Why is this important?
The home button must be consistent with other apps

### Who will benefit from it?
Users who need unified icons.

![Screenshot_20210813-202313165 (1)](https://user-images.githubusercontent.com/58127841/129375990-dd7d0465-25c5-47d4-8952-09bec6f9c7c1.png)
![Screenshot_20210813-202146412 (1)](https://user-images.githubusercontent.com/58127841/129375998-6174658c-ba17-43bf-b07c-1d67f4787de8.png)

**Comment by kbrosnan** [comment]
The home button is the same as the desktop and iOS Firefox. We are going use the same icon across platforms for now. We don't have plans to make icons different for each platform.
