### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cybcarr** [mozilla-mobile/fenix#20843]
Hi there!
![Screenshot_2021-08-13-20-07-53-995_org mozilla firefox](https://user-images.githubusercontent.com/44232454/129401503-67431a9b-0503-400b-be32-fde87b4d5050.jpg)
I'm about to send a private massage, and in your browser it looks like the pic baove .
Are you going to make an improvement about this issue ?
It looks like this in Xiaomi mi browser:
![Screenshot_2021-08-13-20-11-28-789_com mi globalbrowser](https://user-images.githubusercontent.com/44232454/129401738-38eb4f2a-f897-4851-9aaf-7b8762b87832.jpg)
Thanks

**Comment by marcel263** [comment]
Try reaching out at webcompat.com for site specific compat issues.
