### ISSUE TITLE
The new tab page is not accessible when the keyboard is visible

### ISSUE THREAD

**Issue by BlindMoon38** [mozilla-mobile/fenix#20847]
### Steps to reproduce

1. Open Firefox with TalkBack enabled.
2. Navigate to any URL.
3. Open a new tab, either with a long tap on the tab counter context menu, or via the regular menu.
4. Try to explore the screen via touch or gestures.

### Expected behaviour

One is able to explore the new tab screen with TalkBack, both with gestures and touch exploration without having to close the keyboard.

### Actual behaviour

One is not able to explore the new tab screen with TalkBack, making it impossible to access top sites and the other contents of the screen without closing the keyboard.

### Device name

Xiaomi Redmi Note 8

### Android version

MIUI 12.0.4.0, Android 10

### Firefox release type

Firefox Nightly

### Firefox version

93.0.20210812143121

### Additional information

* TalkBack version 9.1
* This behaviour also applies to the recently introduced feature of showing the new tab screen when tapping the address bar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17588)

**Comment by jcsteh** [comment]
@DiegoARL38, thanks for the report. One thing I'm not understanding here is how the keyboard gets opened in your steps to reproduce. Can you clarify? Thanks.

**Comment by DiegoARL38** [comment]
@jcsteh It can be opened doing any of the following:
* Long tap the tab counter when visiting any URL, and select New tab in the context menu.
* When visiting any URL, tap the 3-dot menu and select New tab.
* visit any URL and tap the address bar.
All 3 methods display the home screen with the keyboard opened, but it's impossible to explore the screen outside of the address bar and its options.

PS: Revisiting this issue reminded me that the tab counter doesn't tell how many tabs are open... I'll have to file a bug later.

**Comment by jcsteh** [comment]
My apologies. I'm not super familiar with the Android UI, so I neglected to
realise that opening a new tab (as you specified in your STR) opens the
keyboard.

**Comment by DiegoARL38** [comment]
This issue is still present...

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811596

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
