### ISSUE TITLE
Downloaded items can be deleted individually in multiselect mode

### ISSUE THREAD

**Issue by sunilk9211** [mozilla-mobile/fenix#20848]
The delete button, either it can be hidden in multiselect or the number of selected items can be updated when any item is deleted individually.

![screenshot_1](https://user-images.githubusercontent.com/36289013/129432061-ae1fa9d3-6e6d-435c-a866-f53a500304bd.png)
![screenshot_2](https://user-images.githubusercontent.com/36289013/129432070-258d47e1-5f62-4683-b3bb-8affddc0e1cd.png)
![screenshot_3](https://user-images.githubusercontent.com/36289013/129432071-efcb822c-6aa4-4591-9081-efee510b56cf.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17589)

**Comment by BFadairo** [comment]
Hello! I would like to work on this issue

**Comment by sunil9211** [comment]
@BFadairo Hey. I am already working on it. Sorry should have put a comment. 🙂

**Comment by BFadairo** [comment]
@sunil9211 No problem 😊

**Comment by Rishavgupta12345** [comment]
can i work on this issue

**Comment by sunil9211** [comment]
> can i work on this issue

@Rishavgupta12345 Thanks for your interest, but for this issue i have done changes, will be pushing the code soon.

**Comment by Rishavgupta12345** [comment]
ok no problem

**Comment by bosankus** [comment]
Hi @sunil9211 , Can you kindly assign it to yourself, just to clear confusion for someone to contribute on this issue.

**Comment by sunil9211** [comment]
> Hi @sunil9211 , Can you kindly assign it to yourself, just to clear confusion for someone to contribute on this issue.
> 

Yes you're right, but I am not able to do that.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest builds.
Tested on:
- latest Beta (101.0.0-beta1).
- latest Nightly 102.0a1 (2022-05-05)

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with Samsung A32 (Android 11).
