### ISSUE TITLE
[Bug]: Zooming And Pan Issue

### ISSUE THREAD

**Issue by RajaHarshVardhanSolanki** [mozilla-mobile/fenix#20850]
### Steps to reproduce

1. Open Any Website.
2. Try to zoom and pan.
3. Screen Got Flicking.
4. Not Smooth As Like Chrome's Zooming Function.

### Expected behaviour

Zoom Done Without Any Problems And Smoothly

### Actual behaviour

Flicking Screen And Not Zooming Well.

### Device name

Vivo y91i

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

91.1.0

### Additional information

https://user-images.githubusercontent.com/77908087/129435061-4f0a26f2-afb7-45d6-8e64-d0a0584edb9a.mp4

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1726200

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by theres-waldo** [comment]
@RajaHarshVardhanSolanki are you still experiencing this? The issue looks pretty bad from the video, but I'm not able to reproduce it, and I haven't seen other user reports of it.

**Comment by RajaHarshVardhanSolanki** [comment]
Yes this bug has been persisted till now

**Comment by theres-waldo** [comment]
Thanks for confirming.

Given that the symptoms seem fairly severe, but we have not received any other reports of this issue, I think the issue is likely specific to this device model, or specific to the setup in some other way (e.g. maybe a modified browser preference).

@kbrosnan / @Mugurell, do you know if Fenix has something comparable to Firefox desktop's "troubleshooting mode", which runs the browser without any addons or modified preferences? And/or do you have any other suggestions for how to further investigate an issue like this that's likely to be device- or setup-specific?

**Comment by RajaHarshVardhanSolanki** [comment]
There is not any extension used when recording of this video

**Comment by tnikkel** [comment]
Do you have another device to test on? Do you see the same behaviour on other devices?

**Comment by RajaHarshVardhanSolanki** [comment]
yes i tried it many times in friends mobile phone, can you please share
your screen recording, how it works in your mobile?

**Comment by tnikkel** [comment]
I don't have time to make a screen recording but it looks smooth like you would expect.

**Comment by Mugurell** [comment]
> @kbrosnan / @Mugurell, do you know if Fenix has something comparable to Firefox desktop's "troubleshooting mode", which runs the browser without any addons or modified preferences? And/or do you have any other suggestions for how to further investigate an issue like this that's likely to be device- or setup-specific?

We don't have something similar on mobile though that sounds like a great idea.
In such cases we'd usually rely on QA to try to reproduce the issue - since they have more physical devices to test on and then on the reporters to try different options or even to search for the regression (when possibile).

**Comment by Mugurell** [comment]
@ QA Can you help on testing whether we can also reproduce this?

**Comment by Mugurell** [comment]
@RajaHarshVardhanSolanki Can you please try again on a clean install of latest Nightly - https://play.google.com/store/apps/details?id=org.mozilla.fenix without any customization or addons installed to zoom on `https://www.wikipedia.com` and post a video of that?
Just to ensure we all are using the same scenario.

**Comment by RajaHarshVardhanSolanki** [comment]
https://user-images.githubusercontent.com/77908087/158137068-a95c0e4f-d01d-44d1-8730-ecfe1bf08fce.mp4

**Comment by Mugurell** [comment]
Thank you @RajaHarshVardhanSolanki !
Based on the video it looks like you are seeing the desktop version of `google.com` though based on the shown menu `Desktop site` is off.
I have some questions about your setup:
- how you got the desktop versions?
- What firmware are you using? Is it a custom rom? Any customizations on that?
- Have you seen similar issues on other apps / browsers?

**Comment by RajaHarshVardhanSolanki** [comment]
Oh dude look at the video clearly, i press the desktop button for activate
it, 😂

**Comment by Mugurell** [comment]
> Oh dude look at the video clearly, i press the desktop button for activate it, 😂

So the issue happens only with "Desktop site" active?

**Comment by delia-pop** [comment]
Hello, @Mugurell 

I was able to partially reproduce this issue on the latest Nightly (100.0a1 from 04/01), Release (99.1.0 and 99.1.1), Beta (99.0.0-beta5) and also on Focus browsers.  

Notes:
- A flicker/shaking improper movement can be observed when swiping up if the toolbar is placed to bottom/swiping down if the toolbar is placed to top of the screen. 
- Although zooming in/zooming out on the webpage is not as smooth as it is on other devices, I cannot reproduce the flicker from the videos above during the zooming motion. 
- The issue occurs even when the Desktop site view is disabled.
- Could only be reproduced on a single device with Android 8.

Reproduced with:
- LG G7 fit (Android 8.1.0).

https://user-images.githubusercontent.com/89388888/161260105-94d179e6-3de6-4a2d-8b56-2a417bb6d602.mp4

**Comment by theres-waldo** [comment]
>    * A flicker/shaking improper movement can be observed when swiping up if the toolbar is placed to bottom/swiping down if the toolbar is placed to top of the screen.

I can reproduce this on my Samsung Galaxy S7.

It seems like a different issue than the one originally reported, so I filed a [separate Bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1763038) for it.

**Comment by hiikezoe** [comment]
Can someone having any device reproducing this issue try to see issues here are still observable with setting android.touch_resampling.enabled to false? At least for the scrolling jitter issue, as far as I can tell, disabling the pref solves the issue.

**Comment by RajaHarshVardhanSolanki** [comment]
Sure, I will do that. Wait 5 min

**Comment by RajaHarshVardhanSolanki** [comment]
It happens in mobile mode also
