### ISSUE TITLE
[Bug]: Inactive tabs menu reopening after app restart 

### ISSUE THREAD

**Issue by urmom48** [mozilla-mobile/fenix#20855]
### Steps to reproduce

1. Open tab view
2. Close the collapsible inactive tabs menu
3. Fully close the app
4. Launch again and go back to tab view

### Expected behaviour

The inactive tabs menu should remain closed

### Actual behaviour

The menu opens every time, obstructing the view 

### Device name

S10+

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1

**Comment by Aranjedeath** [comment]
Yup. This bug makes browser tabs feature not useful at all. Firefox automatically classified many of my 1100 tabs as inactive (not wrong), and now I have a good 15 seconds of scrolling to reach "current active tab" area. Would absolutely love it if the close/open state of the inactive tabs were retained.

**Comment by SoftVision-LorandJanos** [comment]
Hi @urmom48 ! Thank you for your report!
I can reproduce the issue you described.

Devices used:
- Xiaomi Mi11 Lite (Android 11).
- Google Pixel 4 (Android 11).
- Huawei P30 (Android 10).

Firefox version:
- Nightly 93.0a1.

**Comment by jonalmeida** [comment]
For now, this is expected behaviour.

> and now I have a good 15 seconds of scrolling to reach "current active tab" area.

This is part of https://github.com/mozilla-mobile/fenix/issues/20637.

**Comment by SoftVision-LorandJanos** [comment]
As this issue is covered in the ticket mentioned above, I will close this one as duplicate.

**Comment by decadent** [comment]
> For now, this is expected behaviour.

Please keep in mind that Android often closes Firefox's activity if you just step away from it for couple minutes. Switch from the browser to your notes, rummage in them for a bit, then go back to the browser, and the UI state changes from how you left it, for no particular reason. IMO that's not quite what one would consider normal behaviour for the UI.
