### ISSUE TITLE
[Bug]: global autoplay blocking of audio & video not respected

### ISSUE THREAD

**Issue by qhaas** [mozilla-mobile/fenix#20861]
### Steps to reproduce

1. Verify global autoplay settings are set to block audio & video
2. Verify a given website with autoplay videos is not listed in the site exceptions
3. Visit said website, observe videos autoplaying, and that the website is configured to block only audio

### Expected behaviour

Global autoplay setting of block audio & video should be the default for sites without a listed exception

### Actual behaviour

only audio is blocked on the site, silent videos autoplay

### Device name

Google Pixel 3

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

91.1.0

### Additional information

![global_autoplay_settings](https://user-images.githubusercontent.com/34581474/129489819-2c07a26a-375d-473f-a3b3-1b62cfef3fd4.png)
![site_autoplay](https://user-images.githubusercontent.com/34581474/129489820-cca6657b-8607-4329-b533-57d2f2e12cc9.png)
![site_exceptions](https://user-images.githubusercontent.com/34581474/129489821-bd0758e8-a5ac-4b74-9bcc-a264d5183311.png)

**Comment by amedyne** [comment]
@Amejia481 Can you check this?

**Comment by Amejia481** [comment]
Sure!

**Comment by Amejia481** [comment]
@qhaas are you able to reproduce on Firefox [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) ?

**Comment by Amejia481** [comment]
I wasn't able to simulated with Firefox release `91.2.0` with Android 11.

**Comment by qhaas** [comment]
Upgraded to 91.2.0, issue appears fixed with this version.
