### ISSUE TITLE
Intermittent UI test failure - SmokeTest.customTrackingProtectionSettingsTest

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#20868]
Update the tests to support the shield and lock icon UI.

**Comment by Amejia481** [comment]
The test is already adapted for the new shield and lock icons, in some cases, it was clicking the "Details" sections too soon, before it was draw and I couldn't figure out why :disappointed: , for this reason I ignored it 
![image](https://user-images.githubusercontent.com/773158/129788051-2ac57341-2f3a-4249-b863-214f65c2af67.png)

**Comment by sv-ohorvath** [comment]
same error now on https://github.com/mozilla-mobile/fenix/issues/18764
