### ISSUE TITLE
Quit needs to clear recently closed tabs

### ISSUE THREAD

**Issue by PencilAmazing** [mozilla-mobile/fenix#20869]
### Steps to reproduce

1. Enable the quit button and set it to clear history on quit
2. Close all tabs manually
3. Open three button menu, press quit

### Expected behaviour

Going to history->recently closed tabs would show nothing

### Actual behaviour

It shows '0 tabs' but the last tab closed is still in there, effectively leaking your history. A workaround would be to quit firefox twice to make sure it gets cleaned

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1

### Additional information

A nice option would be to make clearing 'recently closed tabs' with the quit button optional via a checkbox, since some users might like the current behaviour.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17604)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807442

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
