### ISSUE TITLE
FNX-5445 ⁃ [Bug] WebContent doesn't display when coming back to a tab

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2086]
## Steps to reproduce
It's not 100% but close on my phone, see also video: https://imgur.com/9X3Jlsl

* Start from no tabs
* Open new tab (e.g. search for "test" on google)
* Click on the tabs button
* Open the previous tab again

### Expected behavior
* Tab displays normally

### Actual behavior
* Content is white, no way to get it back besides closing the tab

### Device information
* Android device: Samsung S10e
* Fenix version: latest from playstore

**Comment by sv-ohorvath** [comment]
Cannot reproduce this on the 5/23 build.
devices: Pixel, Galaxy Note 8 (Android 9), Nexus 5 (Android 6).
@agi90 does it still happen on your end?

**Comment by bifleming** [comment]
@agi90 if you can provide logs that would be helpful.

**Comment by jonalmeida** [comment]
@agi90 do you have webrender turned on? I can repro this consistently when I turn it on on r-b. Fenix doesn't have about:config working for beta, so I can't verify this just yet.

**Comment by agi90** [comment]
Good catch! I think I do, I'll confirm when I'm near a laptop next (unfortunately I can't check because `about:config` is not available now).

**Comment by kbrosnan** [comment]
`about:support` may show webrenderer state.

**Comment by jonalmeida** [comment]
> `about:support` may show webrenderer state.

You're right! It's under: Graphics > Features > Compositing

@agi90 ^

**Comment by agi90** [comment]
Just checked: I do have WebRender on.

**Comment by bifleming** [comment]
@vesta0 This is GV -- Priority?

**Comment by jonalmeida** [comment]
> @vesta0 This is GV -- Priority?

@bifleming I think I can answer this safely and say no since WebRender is an experimental feature that Agi had on and will not ship enabled on GV right now.
