### ISSUE TITLE
FNX-5446 ⁃ Consider changing how default bookmark folders are displayed

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2087]
Currently we display four default folders that users **cannot remove**: menu, toolbar, unfiled, mobile. These are required for firefox sync, but we do not need to show these folders to the end user.

I propose that we abstract away the name of these folders. These four folders are confusing to me as an engineer, and I'm sure they will be confusing to users--why display them at all? We could merge the desktop related ones into a folder called "desktop" and all the mobile links could just appear in the root directory (unless the user creates a folder)

Other options include:

* Showing the children of parent directories
* Starting the user in the mobile folder

**Comment by kbrosnan** [comment]
#1951 is similar.
