### ISSUE TITLE
FNX-5447 ⁃ Do not block startup while loading the icon for the default search engine

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#2088]
### Why/User Benefit/User Problem
Fenix waits to complete loading until the icon for the default search engine is available. In order to get that, Fenix must wait for every single search engine entry to load. This is slow.

### What / Requirements
Fenix will start loading the list of search engines asynchronously and then complete startup.  When the icon is available, Fenix will place the icon appropriately.

### Acceptance Criteria (how do I know when I’m done?)
Profiling will indicate when this is working.

**Comment by hawkinsw** [comment]
Patch coming.

**Comment by hawkinsw** [comment]
According to my profiles of Fenix running on my motorola g(6), starting GleanMetrics takes ~600ms to start and is dependent on fetching the default search engine (which requires instantiating the search engine manager). If the search engine manager is not created when GleanMetrics starts (because telemetry is disabled, e.g.), then startup is still blocked on startup waiting for the SEM instantiation (just at a later time). The two scenarios are addressed in this patch. 

There are several ways to fix this problem. I have a WIP for a fix at the a-c level but it is more in-depth and does not actually solve the Fenix startup problem. I am happy to explain that patch and why it does not work in this case if anyone is interested.

This patch is much, much more concise and more simple. With this patch applied, GleanMetrics takes < 10ms to start. 

For some reason this change is not noticeable in nimbledroid. @colintheshots and @ncalexan and @boek and others are going to discuss this on Monday. In the meantime, I would love your feedback on this patch! 

Will

**Comment by hawkinsw** [comment]
Check out #5023 for a (the?) fix.

**Comment by ekager** [comment]
Hi @hawkinsw ! Thanks for the work here, should we close this ticket now?

**Comment by hawkinsw** [comment]
I don't think that I had much to do with fixing this, but you're welcome! And, sure, let's close this down!
