### ISSUE TITLE
Crash in [@ EMPTY: no crashing thread identified]

### ISSUE THREAD

**Issue by BReduardokramer** [mozilla-mobile/fenix#20888]
Crash report: https://crash-stats.mozilla.org/report/index/0fb39a2e-7d4d-429e-baf8-523cb0210817

So, I've installed the version 91.1.0 of Firefox on my Android phone, there is a bug on Firefox Daylight, so much bugs yet, so I've installed older version of Firefox than the recent version ones.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17614)

**Comment by kbrosnan** [comment]
Is there a specific action that causes this crash? Your device and Firefox did not record the information needed to diagnose the crash. Are there other crashes on the device that are not empty?

**Comment by BReduardokramer** [comment]
> Is there a specific action that causes this crash? Your device and Firefox did not record the information needed to diagnose the crash. Are there other crashes on the device that are not empty?

Only one, by the time I've installed the recent version, it had some bugs, in my opinion.

That caused the crash was one since installed, so I've reverted back to old version of Firefox on my Moto G4 Play.

**Comment by sflorean** [comment]
@BReduardokramer do you still see the crash on latest Firefox versions? If not, probably we can close this bug and re-open if new information are added.
