### ISSUE TITLE
[Bug]:  Crash to black screen on Windows 7

### ISSUE THREAD

**Issue by gravas68** [mozilla-mobile/fenix#20884]
### Steps to reproduce

The following webpage will result in a black screen reset of my Windows 7 machine.

https://www.bethanyec.co.uk/Video2021.html

### Expected behaviour

The videos should all load.

### Actual behaviour

Black screen reset.

### Device name

Asus PC

### Android version

N/a

### Firefox release type

Firefox

### Firefox version

91.0 32 bit

**Comment by cadeyrn** [comment]
@gravas68 This is the issues tracker for Firefox for **Android**. For issues with the desktop version of Firefox please file a bug on https://bugzilla.mozilla.org/
