### ISSUE TITLE
Update connection icons in address bar and new combined menu

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#20892]
Let's use only the black secure icon and the black with red slash insecure icon in both the address bar and the connection menu. Like this:
<img width="743" alt="Screen Shot 2021-08-17 at 10 57 12 AM" src="https://user-images.githubusercontent.com/107992/129760199-153f548f-9b49-4184-91ae-9c0c533d64f4.png">
<img width="716" alt="Screen Shot 2021-08-17 at 10 56 39 AM" src="https://user-images.githubusercontent.com/107992/129760217-2a88c17d-2a16-476e-b119-71f02ca20e03.png">

**Comment by Amejia481** [comment]
related https://github.com/mozilla-mobile/android-components/issues/10225

**Comment by sheikh-azharuddin** [comment]
> related [mozilla-mobile/android-components#10225](https://github.com/mozilla-mobile/android-components/issues/10225)

Hello Amejia
I believe the icon should be updated to reflect security and tracking protection...similar to Microsoft edge

![Screenshot_20210818-123857232 (1)](https://user-images.githubusercontent.com/58127841/129853868-3cae32d7-f166-4726-9335-b395804d25b3.png)

**Comment by Amejia481** [comment]
@Verdi  I put a fix for security icon under the menu section, for the one on the toolbar we need some additional work, this will be cover on https://github.com/mozilla-mobile/android-components/issues/10866.

https://user-images.githubusercontent.com/773158/130462044-294b119d-9491-4dfc-97f1-8bdd6ec45413.mp4

**Comment by jonalmeida** [comment]
I spoke with Arturo offline to figure out how we could style the secure/insecure icon with the red highlight across the icon. Today, this is a lot more work that we anticipated, so I recommend we differ it by filing a bug (so we don't forget) and not block this larger feature from landing.

When we re-write our toolbar in Jetpack Compose, it might potentially make it easier to do this as well. Either way, let's re-evaluate the effort for adding the red highlight at a later date.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both Nightly 94.0a1 from 9/8 and 93.0.0-beta.1 using the following devices:
• Google Pixel 3a (Android 11)
• OnePlus A3 (Android 6.0.1)

► Video
https://user-images.githubusercontent.com/51314259/132493383-d8a90f51-c7a5-450a-bf38-f2f01969ca4f.mp4
