### ISSUE TITLE
When Tracking protection is off globally then let’s not show the TP section of this menu.

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#20890]
related to https://github.com/mozilla-mobile/fenix/issues/19886

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/fenix/pull/20913

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview 93.0.0-beta.1.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- Oppo Find X3 Neo (Android 11)
