### ISSUE TITLE
[Bug] history may be getting deleted after 14 days

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#20903]
### Steps to reproduce

After last few updates I have observed history (I guess more than 30 days) getting removed and no longer appears in search history..

Is it bug? Or expected?

### Expected behaviour

History should be preserved or there must be some option to configure how long history is retained

### Actual behaviour

Ita deleting history

### Device name

asus rog 3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

**Comment by sheikh-azharuddin** [comment]
I guess this was introduced by below commit/feature
https://github.com/mozilla-mobile/fenix/pull/20577

It is deleting history also for more than 14 days...

**Comment by amedyne** [comment]
@csadilek FYI.

**Comment by grigoryk** [comment]
> I guess this was introduced by below commit/feature
> #20577
> 
> It is deleting history also for more than 14 days...

That commit should not affect history itself. History Metadata is separate feature from "history". The data is different and designed to be short-lived, and removal of history metadata should not remove history.

Also, history metadata is not enabled on Nightly right now, so this call isn't even in effect.

I'll check to see if anything else changed recently that may affect history retention.

**Comment by grigoryk** [comment]
@sheikh-azharuddin can you please check the History UI itself, see if it has data beyond 14 days? I suspect that it should.

My best guess here is that the expected items are perhaps not showing up in the awesomebar results, somehow. It's easy to mistake that for "history is missing" - and in some sense, it is, if the awesomebar is the primary way of interacting with the history.

**Comment by grigoryk** [comment]
@sheikh-azharuddin it would be helpful if you could check your History, pick some old item and try to search for it via the awesomebar. If that doesn't work, that helps us pinpoint the source of the problem.
