### ISSUE TITLE
[Bug]: Adding tabs from a collection move to inactive section immediately

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20900]
### Steps to reproduce

1. Add a few tabs to a collection.
2. Wait 2 weeks. 😅 
2. Click the 'Open tabs' menu option for that collection.
3. Open the tabs tray.
4. Observe

### Expected behaviour

- The tabs should be opened and active.

### Actual behaviour

- The tabs are opened but inactive.

### Device name

All devices

### Android version

All versions

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by jonalmeida** [comment]
Oddly enough, I can reproduce this with a local build from fd1890090 but not from Nightly.

93.0a1 (Build #2015828619)

**Comment by jonalmeida** [comment]
So it looks like this is an unintended consequence of how we categorize inactive tabs. For tabs from a collection, those tabs can have a `createdAt` or `lastAccessed` value greater than 4 days, so when they are opened into the tabs tray. They automatically move to the inactive section of the tabs tray.

If we want to solve this bug, it sounds like we need to set the `lastAccess` as "now".

**Comment by LaurentiuApahideanSV** [comment]
I tested the issues and was able to reproduce it on the Firefox Preview Nightly build 2021-10-01 by forwarding the time on the device by 2 weeks. On the 2021-10-08 the issue does not occur anymore.
@jonalmeida Do you still think we need a custom build to test the issue or should we close it as fixed?
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by jonalmeida** [comment]
> I tested the issues and was able to reproduce it on the Firefox Preview Nightly build 2021-10-01 by forwarding the time on the device by 2 weeks. On the 2021-10-08 the issue does not occur any more.

If the bug is resolved on the latest nightly, I think we can close as resolved then.
