### ISSUE TITLE
[Bug]: Broken "Whats New" link

### ISSUE THREAD

**Issue by j-r9** [mozilla-mobile/fenix#20907]
### Steps to reproduce

1. Have blank tab open.
2.  Click on "Whats New"

Also occurs at "Whats New" link at Settings>About Firefox

### Expected behaviour

A link to a page for the version of Firefox for Android that is running; perhaps by using the forwarding link https:/www.mozilla.org/en-US/firefox/android/notes/

### Actual behaviour

Forwards to Firefox for Android 79 "Whats New" page.

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

91.2.0

**Comment by Nickoriginal** [comment]
There is no issue or bug. Firefox for Android 79 "Whats new" page regularly updates and matches new release notes for the latest Firefox. SUMO page is more user-friendly than direct "Release Notes" page.
What about old Firefox users, SUMO page contains a notification for them to update to the latest Firefox.

**Comment by j-r9** [comment]
When I click "whats new" in daylight, since post-79, the current version link fails and sends me here:

https://support.mozilla.org/en-US/kb/whats-new-firefox-android?as=u&utm_source=inproduct&redirectslug=whats-new-firefox-android-79&redirectlocale=en-US

![Screenshot_20210818-134452_Firefox](https://user-images.githubusercontent.com/89143455/129947172-5b6c439d-97da-4523-bf83-a1246d516e98.jpg)

**Comment by j-r9** [comment]
That password fix is a new fix isn't it?  Maybe this been updating and I have been ignoring it because of the "(Redirected from from What's New in Firefox for Android 79)"  Maybe this should be removed.

**Comment by Nickoriginal** [comment]
> ### Expected behaviour

> A link to a page for the version of Firefox for Android that is running; perhaps by using the forwarding link https:/www.mozilla.org/en-US/firefox/android/notes/
> ### Actual behaviour

> Forwards to Firefox for Android 79 "Whats New" page.

Hmm... I thought that you doesn't like that link

**Comment by j-r9** [comment]
In my opinion, the page I mentioned would provide more than the highlights that are shown at the redirect link.  I imagine users would like to know about as many new features as possible, and see that Firefox is constantly addressing security issues, regardless of their experience in these other areas.

**Comment by Nickoriginal** [comment]
I see the same issue on my mobile Chrome when entering SUMO knowledge base using this link: https://support.mozilla.org/kb/whats-new-firefox-android

Do you can test it on your other mobile browser too?

**Comment by j-r9** [comment]
Same thing in Microsoft Edge and Samsung browser as well.

**Comment by Nickoriginal** [comment]
Now we have only **SUMO** site compatibility issue, what displays "Redirected from..." in the all mobile browsers, not in Firefox only. For this reason it cannot be confirmed or resolved in Firefox. I know person closely associated with this site.

**Comment by j-r9** [comment]
Unsure of how I report the error on a SUMO page.  What is the best way to do this?

Nickoriginal, I don't see a way to contact you directly.  I know you said something about knowing someone over there, can they take care of this?  I would still like to know the proper way to report the issue though.

**Comment by Nickoriginal** [comment]
Here, on this repository in GitHub, I saw Paul Wright multiple times as sufficiently active contributor. Usually he sends a user feedback from SUMO, so I think, he can help us or redirect our issue to SUMO developers. I don't know his @shortname (or something), but I learned his profile location https://github.com/SeburoSUMO and his twitter https://twitter.com/Seburo13 so you can contact him right now.

**Comment by j-r9** [comment]
I'm not on twitter.  I would think there was a way to do from support.mozilla.org, but I don't see it.
 
> Now we have only **SUMO** site compatibility issue, what displays "Redirected from..." in the all mobile browsers, not in Firefox only. For this reason it cannot be confirmed or resolved in Firefox.

 Should this issue be marked closed now?

**Comment by amedyne** [comment]
Tagging @fabiLpz for this bug.

**Comment by j-r9** [comment]
I found a place to report this on bugzilla, but have been noticing changes coming and going on the KB page; I will leave alone for now.

**Comment by j-r9** [comment]
Sorry amedyne, I kept putting this off and forgot about it.  I just reported it here.
https://bugzilla.mozilla.org/show_bug.cgi?id=1734755

**Comment by amedyne** [comment]
Checked the link today and the "Redericted from...." text is no longer visible. Closing.
