### ISSUE TITLE
Implement scrolling screenshots via ScrollCapture API

### ISSUE THREAD

**Issue by mduchev** [mozilla-mobile/fenix#20905]
### What is the user problem or growth opportunity you want to see solved?
Since the first Android 12 beta (DP 1), Google has been polishing the new scrollable screenshots. Now the screenshots are detecting automatically whether the View that we have screenshoted is a scrollable one and the system is presenting us with the option to scroll more in order to extend the screenshot. This is only happening automatically for View-based screenshots and not for web-based (like a browser's webview). The latest Canary version of Chrome has already started to experiment with this [link](https://www.xda-developers.com/google-chrome-full-page-screenshots-android-12/). I know that it's still early to have this change inside Firefox, but the official Android 12 release is almost here, so we have to think of implementing it at some point, or at least to start tinkering with it. Since the fourth beta of Android 12 is already released, we know for sure that this one will be in the final APIs.

[ScrollCapture API docs](https://developer.android.com/reference/android/view/ScrollCaptureCallback)

![image](https://user-images.githubusercontent.com/8217099/129885138-f20871cc-adbf-41cc-9698-c498ba1f0d65.png)

### How do you know that this problem exists today? Why is this important?
Firefox, like many other apps, hasn't implemented (or even started to experiment with) the new ScrollCapture API. It would be good at some point to have this new feature come to Firefox on Android as well.

### Who will benefit from it?
All users running Android 12+
It would also help with switching of the users from Chrome to Firefox at some point, since having this feature is a big plus for either browser.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17624)

**Comment by Mugurell** [comment]
There needs GV - https://bugzilla.mozilla.org/show_bug.cgi?id=1530967.

**Comment by jonalmeida** [comment]
> This needs GV - https://bugzilla.mozilla.org/show_bug.cgi?id=1530967.

Maybe not? This sounds like an alternative solution for full page screenshots. We could try to request a regular screenshot today when we get [`ScrollCaptureCallback.onScrollCaptureImageRequest`][0] invoked and prompt the user to scroll until the page end to then invoke [`ScrollCaptureCallbackonScrollCaptureEnd`][1].

I'm also just spit balling ideas here. 🙃 

[0]: https://developer.android.com/reference/android/view/ScrollCaptureCallback#onScrollCaptureImageRequest(android.view.ScrollCaptureSession,%20android.os.CancellationSignal,%20android.graphics.Rect,%20java.util.function.Consumer%3Candroid.graphics.Rect%3E)
[1]: https://developer.android.com/reference/android/view/ScrollCaptureCallback#onScrollCaptureEnd(java.lang.Runnable)

**Comment by jonalmeida** [comment]
> ..and prompt the user to scroll until the page end to then invoke [`ScrollCaptureCallbackonScrollCaptureEnd`](https://developer.android.com/reference/android/view/ScrollCaptureCallback#onScrollCaptureEnd(java.lang.Runnable)).

Another reason to consider screenshots that require user interaction are for sites that use rendering frameworks like React which don't fill up the DOM so taking a full page screenshot only gives you the visible content instead. (I ran into this problem when trying to grab a full page screenshot of a Slack thread.)

**Comment by mduchev** [comment]
Google Chrome now supports Android 12’s scrolling screenshots

https://9to5google.com/2021/12/08/chrome-android-12-scrolling-screenshots/

**Comment by Ban-China2020** [comment]
Yes please add this asap. Things like this makes it hard to love it 100% of the time. Still have to install multiple browsers to get things done. Also pull to refresh should go to main release and scrolling screenshot is a must

**Comment by seventhpaw** [comment]
I would also like to show support for this.

**Comment by aviv57** [comment]
Hi I just switched to android 12 and this feature is missing

**Comment by Dan0sz** [comment]
I would love to see this feature!

**Comment by hsein-a** [comment]
I need this feature!

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811925

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
