### ISSUE TITLE
[Bug]: File upload button does not work

### ISSUE THREAD

**Issue by wb9688** [mozilla-mobile/fenix#20906]
### Steps to reproduce

1. Go to e.g. imgbb.com
2. Press the button to upload the file

### Expected behaviour

It should show a file picker.

### Actual behaviour

It does nothing.

### Device name

Samsung Galaxy A50

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

91.2.0

**Comment by sheikh-azharuddin** [comment]
Works fine in nightly

![Screenshot_20210818-182305627](https://user-images.githubusercontent.com/58127841/129901452-3603c076-2002-4f7b-870a-d81c67a50380.png)

**Comment by Amejia481** [comment]
Thanks @sheikh-azharuddin  :)

@wb9688  are you able to reproduce in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)?

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Preview Nightly 2022-12-01 but was unable. Since the reporter hasn't provided additional information for a long time I will mark this issue as closed:
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 12)

**Comment by wb9688** [comment]
Apparently I forgot to reply. At the time you asked, I was unable to reproduce it in Nightly. However I currently still have the issue in Firefox 96.1.1. Is there any more information you want that could help you debug the issue?

**Comment by wb9688** [comment]
This issue still happens on Firefox 108.1.1 on my Samsung Galaxy A50, but not on my Moto G52.
