### ISSUE TITLE
New tabs opened from tabs with Desktop Site enabled are opened as mobile pages

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2091]
## Steps to reproduce
Go to a website
Request the desktop site
Open a link in new tab

### Expected behavior
If I am browsing a website that doesn't work very well on mobile devices and I am opening links from this website in new tabs, I expect that these new tabs are also requested as desktop pages, so I can better use them.

### Actual behavior
New tabs are requested as mobile pages, desktop being originated from a tab requested as desktop.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11152)

**Comment by kbrosnan** [comment]
Fennec does not have this behavior.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807152

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
