### ISSUE TITLE
[Bug] Request desktop site doesn't persist after the browser crashes.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2092]
## Steps to reproduce
Request a website as desktop, Bing for example.
Cause the browser to crash
Reopen the browser

### Expected behavior
The browser reopens as it was before, with the desktop site being requested.

### Actual behavior
Once the browser is reopened, the desktop site toggle is not enabled anymore.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1917

**Comment by ekager** [comment]
Hey @Lululalu can you still reproduce this?

**Comment by Lululalu** [comment]
@ekager I would gladly try again, but don't know how to cause Fenix to crash anymore.

**Comment by sv-ohorvath** [comment]
I can reproduce this on the 5/17 build:
1. Go to bing.com. Request desktop site.
2. Go to about:crashparent to crash the app.
3. Restart the app. Check the desktop site toggle. 
4. Refresh the page.

Results:
The toggle is off after the crash, but the page is restored in desktop mode. Refreshing the page returns the mobile page.

**Comment by liuche** [comment]
Will dupe to #11552
