### ISSUE TITLE
[Bug]: No webpage image loading after latest update.

### ISSUE THREAD

**Issue by burgoslu** [mozilla-mobile/fenix#20928]
### Steps to reproduce

I have an old tablet with Android 5.1.1, 4GB of RAM and Intel 64bit Cherry Trail x5 CPU, that I use daily just to read news from BBC.com. After the latest automatic Firefox update by Google Play to 91.2.0, all the images in that site as well as all other web sites, no loger are displayed by the browser. Everything else seems to be working fine.

### Expected behaviour

Images should be show alongside the web page text.

### Actual behaviour

No image are shown. Only black rectangles.

### Android version

Android 5.1.1

### Firefox release type

Firefox

### Firefox version

91.2.0

### Additional information

I work as a DevOps Eng. so I am familiar with general IT configuration issues, but I am not familiar with Android internal workings. So I can not troubleshoot to get more information on what is going on.

**Comment by amedyne** [comment]
Transferring to bugzilla for further investigation.

**Comment by amedyne** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1727223

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Thanks @burgoslu. We have now fixed this issue for your GPU as well. Firefox Nightly and Beta should already work correctly, and the next update of Firefox release (today I think) should be fixed too. Please let me know if you run in to further issues.
