### ISSUE TITLE
Find root cause of temporary 1089ms cold-view-nav-start improvement on 8/4

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20935]
![image](https://user-images.githubusercontent.com/759372/130148454-1366a77c-8a7a-4693-95ac-8ea56be91435.png)

We saw a temporary improvement of 1089ms on my Moto G5 for 4 builds starting on 8/4 before the behavior reverted back to the previous behavior: let's find the root cause so we can keep those wins. Note: the improved behavior is comparable to the duration before the regression on 7/14 https://github.com/mozilla-mobile/fenix/issues/20934 – perhaps they are related?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17637)

**Comment by mcomella** [comment]
I built one of these locally and noticed some logcat errors about web extensions: maybe this is the time with web extensions disabled.

**Comment by Rob--W** [comment]
There was briefly a period where the extension framework did not initialize due to a bug/regression in the JavaScript engine: https://bugzilla.mozilla.org/show_bug.cgi?id=1724298

The duration of the regression coincides with the duration of the reported "performance improvement".

**Comment by MarcLeclair** [comment]
Pinning in order to keep track of this issue.  It could be useful to see what changed on that day using the backlog script.

**Comment by cpeterso** [comment]
> There was briefly a period where the extension framework did not initialize due to a bug/regression in the JavaScript engine: https://bugzilla.mozilla.org/show_bug.cgi?id=1724298 (originally reported at #20692).
> 
> The duration of the regression coincides with the duration of the reported "performance improvement".
