### ISSUE TITLE
Fenix isn't using conditioned profiles in page load testing (formerly: understand why fenix is 300ms slower (Pixel 2) than GVE for cold page load)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20936]
For cold page load, we see around a 300ms diff between fenix and GVE in some cold page load events:
![image](https://user-images.githubusercontent.com/759372/130149982-7d04695e-ba10-4a17-845c-6e16c207fd7b.png)

via https://arewefastyet.com/androidPixel2/cold-page-load/overview?numDays=60

Similarly, we see a 150ms diff for warm page load. **These numbers are taken on a pretty fast device – a Pixel 2 – so this really is a big difference.**

Let's figure out the root cause. Theories:
- I suggested it could be that fenix takes longer to start up (e.g. nimbus, glean, crash reporters, etc.). Is this metric measuring from navigation start or process start time though? We could test this by commenting out all that stuff and re-running the tests.
- agi suggested it may be related to the web extensions framework. We could test this by re-running the test without the extensions framework
- jnicol suggested it may be because "Myself and Jim Mathies (jimm) looked in to this, as there was an obvious date in the graph at which they diverged for cold load. I think we figured out that it was to do with the profile conditioning only being used for geckoview and not fenix
And webrender is really slow on a completely cold start as it needs to compile shaders, so is much faster on a conditioned profile cold start". We could test this by enable/disabling conditioned profiles and retest

**Comment by jamienicol** [comment]
If you change it from 60 days to 90 you'll see a clear change in the GVE times sometime in june, linked to the alert bz-1716507. This was regressed by bz-1708760, which introduced conditioned profiles

**Comment by Rob--W** [comment]
A difference between GVE and Fenix (A-C) can indeed be related by the use of WebExtensions. Off the top of my head, there are two potential triggers that are tied to the extension framework (rather than an issue with a particular extension implementation):
- Extensions that use the webRequestBlocking API suspend network requests that matches previously registered URL patterns until the extension has started up. This can realistically take a "significant" amount of time. Once started up, network requests can still be suspended but are typically processed within a few ms. This network blocking-at-startup can only happen if the extension has started up before, because the logic is only activated if the extension has managed to register blocking webRequest listeners.
- Extensions that use content scripts with `run_at` `"document_start"` block the DOM parser until the content script has been loaded. Once loaded the parser won't be blocked again for subsequent uses of the content script in the same process. A quick search for "document_start" in the A-C repo shows that the webcompat add-on may be using `document_start` for some scripts.

**Comment by mcomella** [comment]
wrt to WebExtensions, the existing `parseManifest` code takes longer than I'd expect so I filed to investigate https://github.com/mozilla-mobile/fenix/issues/21096.

To test the two theories mentioned above, we can:
- conditioned profiles: add conditioned profiles to fenix and see if they're the same
- web extensions: disable webextensions and see if they're the same (we may have to measure GV Example & fenix locally)

**Comment by mcomella** [comment]
@acreskeyMoz Do you happen to have any ideas? I think you may have done work around this area. :)

**Comment by acreskeyMoz** [comment]
> @acreskeyMoz Do you happen to have any ideas why fenix is slower than GVE in cold page load? I think you may have done work around this area. :)

@mcomella That's an interesting one.
I agree with what @jamienicol  put forward:  https://github.com/mozilla-mobile/fenix/issues/20936#issuecomment-902298506
We can see from the graphs that this divergence started on June 11, when `settled` conditioned profiles were introduced.
https://hg.mozilla.org/mozilla-central/rev/5e7be02a8487
And, if I have this correct, we only added them for Geckoview and not Fenix
(looking at this comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1708760#c6)

I suggest a test run where we enable them on Fenix pageload tests and compare that against a baseline.
If we see a difference, I'd be happy to help look at the profiles. (Maybe a JoyOfProfiling session?)

**Comment by mcomella** [comment]
Following the conditioned profile theory, I opened https://github.com/mozilla-mobile/fenix/pull/21290 to enable conditioned profiles for page load & youtube playback tests in fenix on `main`. I wanted to test this in try but getting treeherder results for fenix + try pushes is disabled after BZ-1587542.

I tried the inverse test of removing conditioned profiles from GVE and got roughly what we expected on SpeedIndex, which is used by arewefastyet ([perfherder compare](https://treeherder.mozilla.org/perfherder/compare?originalProject=try&originalRevision=514124a0e64e8f401104e4c18373095936174fff&newProject=try&newRevision=2ef75fc16bd4a364c63de1f47229a1369f2f38a4&framework=13&page=1&filter=speedindex+cold)):
* 445ms regression (allrecipes)
* 334ms regression (amazon)
* 129ms regression (google)

One bonus info: I took profiles of GVE and fenix without the start up cache to see how they're different. The major differences I saw were: webExtensions (broken into several places), gfxPlatform::Init (79ms vs 35ms), a few network things. As an experiment, we can disable web extensions and see how the perf compares.

If useful, here is a link to my [working document](https://docs.google.com/document/d/1CAKuW-2uyzWfyf_fkBNoEYenEwMbbHaFTVjKOwEEwxM/edit).

**Comment by mcomella** [comment]
Conditioned profiles landed in `main` and we see the initial fenix results sitting at the high-end of the GVE results. Here's allrecipes:
![image](https://user-images.githubusercontent.com/759372/133655414-12c9ac48-b529-4bb0-ac00-700b5b02ca69.png)

And Google:
![image](https://user-images.githubusercontent.com/759372/133655443-2f04c56e-7617-4659-a99a-22cd470b5e23.png)

Let's get a few more days of data to see how the trends change. If the trends hold, that leaves a few follow-up investigations that can turn into perf wins:
- Do users experience the app as if it had conditioned profiles or not? => if not, can we get them onto these faster profiles? if so, when does it happen?
- What is in a conditioned profile and why is it so much faster? (Start up cache? This will be easier to test after BZ-1728461 lands) => awareness to solve ^ or debug later perf issues
- Why is fenix still slower than GVE? (WebExtensions?) => possible direct improvements

**Comment by mcomella** [comment]
The behavior held.

I filed two follow-ups for the questions in the previous comment as they may be a different priority than this issue:
- https://github.com/mozilla-mobile/fenix/issues/21419
- https://github.com/mozilla-mobile/fenix/issues/21420

And closing this investigation as complete.
