### ISSUE TITLE
Ability to Rearrange Bookmarks

### ISSUE THREAD

**Issue by j-r9** [mozilla-mobile/fenix#20942]
Firefox for Android has long lacked the ability to sort or rearrange bookmarks outside of sync.  This doesn't make sense to me.  I would like to see, at least, the ability to easily move bookmarks up or down from inside the app.  There are a variety of ways to organize bookmarks in most any Desktop browser, and the mobile versions of Chrome and Samsung Internet both allow bookmarks to be rearranged.  This will help users, especially those with a large number of bookmarks, to more quickly organize and find bookmarked sites from within the app.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/4348
