### ISSUE TITLE
Toolbar in Fireefox Android

### ISSUE THREAD

**Issue by iamkartk** [mozilla-mobile/fenix#20940]
Please there is no need of url address bar in toolbar. Toolbar needs necessary most required functions like forward, backward, search, tab and menu options instead of url address bar.
Take firefox ios browser.
Url address bar is at top.
In bottom toolbar, commonly required functions are available like backward, forward, search, tab, and menu.
The menu icon is properly spaced with three lines instead of three dots as in android where its space is very less for menu icon to touch from left thumb.
And also, home tab itself has library options like bookmark and downloads.
Just implement the same firefox ios browser features in firefox android.
Currently firefox android browser is very cumbersome to use.
![Capture](https://user-images.githubusercontent.com/56734031/130192608-bcb8942b-057a-473e-af2a-9a4dae6e4025.PNG)

**Comment by Imerion** [comment]
+1 for this! Would be really nice if there was a button in the Toolbar to instantly go to the Bookmarks view too!

**Comment by kbrosnan** [comment]
This issue is a mashup of several requests. Firefox for iOS behaves with the expectations of iOS apps and Firefox for Android behaves with the expectation of Android apps. The hamburger menu does not make sense in Android as that should result in a menu that slides in from the left or right and covers the screen from top to bottom (see gmail for an example). If you want top address bar you can set that in the settings. We find with taller phones that a bottom address bar provides easier access to the main controls.

**Comment by iamkartk** [comment]
Option can be provided whether one wants separate URL address bar or URL address bar in toolbar itself just as in Vivaldi Android browser. 
I want top URL address bar but bottom toolbar with features of backward, forward, search, tabs, menu icons just like in Firefox IOS browser and that is not possible from settings.
Currently my main android browser is Opera android browser which is exactly like firefox IOS browser; URL address bar is at top seperate from main toolbar which is at bottom. 
While clicking on search icon from bottom toolbar; URL address bar is automatically selected so no need of whole URL bar at bottom.
In Yandex android browser too, option is provided whether one wants address bar at toolbar itself or not. 
If yes then toolbar works as in firefox android.
If no then URL bar becomes separate from main toolbar and gets other menu options right on toolbar itself.

**Comment by iamkartk** [comment]
> 
> 
> +1 for this! Would be really nice if there was a button in the Toolbar to instantly go to the Bookmarks view too!

Well in firefox ios browser, History, downloads, bookmarks and reading list all are provided right on home tab and that is amazing. Dont see why the same features are not provided on firefox android.

**Comment by iamkartk** [comment]
> 
> 
> This issue is a mashup of several requests. Firefox for iOS behaves with the expectations of iOS apps and Firefox for Android behaves with the expectation of Android apps. The hamburger menu does not make sense in Android as that should result in a menu that slides in from the left or right and covers the screen from top to bottom (see gmail for an example). If you want top address bar you can set that in the settings. We find with taller phones that a bottom address bar provides easier access to the main controls.

Option can be provided whether one wants separate URL address bar or URL address bar in toolbar itself just as in Vivaldi Android browser. 
I want top URL address bar but bottom toolbar with features of backward, forward, search, tabs, menu icons just like in Firefox IOS browser and that is not possible from settings.
Currently my main android browser is Opera android browser which is exactly like firefox IOS browser; URL address bar is at top seperate from main toolbar which is at bottom. 
While clicking on search icon from bottom toolbar; URL address bar is automatically selected so no need of whole URL bar at bottom.
In Yandex android browser too, option is provided whether one wants address bar at toolbar itself or not. 
If yes then toolbar works as in firefox android.
If no then URL bar becomes separate from main toolbar and gets other menu options right on toolbar itself.
I really dont see whats wrong in providing options.
I love firefox windows browser because it has so many options.
