### ISSUE TITLE
Consider impact of pages hiding infinite animations on battery life

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20953]
I saw this go by in element:

> one caveat from the CSS animation perspective, web developers often use an infinite animation (for loading spinner or some such) then **they often just hide the animation in various ways (i.e. CSS visibility:hidden** or something like that), thus unfortunately such hidden animations need to keep observing nsRefreshDriver to fire animationiteration events, I think it interferes your efforts. 
>
>...  **Doesn't that hurt user's battery life also?**  As in, this is bad for other people, not just me.

Not sure there's anything to be done but I wanted to document it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17650)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807332

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
