### ISSUE TITLE
[Bug]: Canvas rendered text gets affected by text sizing features

### ISSUE THREAD

**Issue by Eskuero** [mozilla-mobile/fenix#20959]
### Steps to reproduce

1. Change the text scaling  level beyond or below a 100% OR have "Automatic font sizing" enabled in Accesibility options 
2. Have a page with `<meta name="viewport" content="width=device-width, initial-scale=1.0">`
3. Have a canvas element
4. Render text on the canvas

Sample codepen: https://codepen.io/Eskuero/pen/WNOeOJR

This is how it looks with the different percentage of scaling

![Untitled](https://user-images.githubusercontent.com/1757242/130336865-47f83b48-a831-4558-b777-b2bb5522df29.png)

### Expected behaviour

The text in the canvas should stay the same size regarless of viewport properties and browser filters.

### Actual behaviour

The text gets scaled unlike in Firefox Desktop and Chrome (both versions) and ends messing up the draw because you can't have an expectancy of how it's size will rendered in relation with other drawings you might do on the canvas.

### Device name

Samsung Galaxy Tab A 10.1, Xiaomi Mi A2 Lite

### Android version

10

### Firefox release type

Firefox

### Firefox version

92.0.20210715094037

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1727020

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
