### ISSUE TITLE
Scroll to the current tab instead of Inactive tabs while opening the tabs page

### ISSUE THREAD

**Issue by dolfinus** [mozilla-mobile/fenix#20960]
### What is the user problem or growth opportunity you want to see solved?

1. I've opened a page with several links and I want to read all of them. For example, this is the main page of some news site.
2. I've opened the pages I need in the new tabs.
3. They have been immediately moved just after the current tab.
4. Now I open the tabs window to close the current tab and move to next ones.
5. But I see here the Inactive tabs list which is quite large in my case (about 200 tabs), when the main page and newly opened pages are active tabs. Not so convenient.
6. To make things worse, Inactive tabs list has been scrolled down to the last item, not the first one which is just below the Active tabs list. So I need to scroll all the inactive tabs to search the exact tab I need.
7. More than that, current tab can be in any place in the Active tabs list, so usually I need to scroll most of them too.
9. When I've minimized Inactive tabs, the behaviour become even more inconsistent - now the list of tabs has been scrolled to the first active tab in the list, not the last one.

### How do you know that this problem exists today? Why is this important?

This is really annoying UI issue which was introduced by Inactive tabs feature. Now it takes a lot of time for me to scroll all these tabs.
In previous versions the tabs page has been opened just in the right place, I've always seen a current tab. So in my case this feature really made UX worse.

### Who will benefit from it?

Users with a lot of tabs opened via "Open in new tab" context menu item.

Nightly 93.0a1 (Build #2015829195)
Samsung Galaxy S10 (Android 11)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17653)

**Comment by amedyne** [comment]
Tagging @jonalmeida and @topotropic for consideration in future discussions about this feature.

**Comment by jonalmeida** [comment]
> This is really annoying UI issue which was introduced by Inactive tabs feature. Now it takes a lot of time for me to scroll all these tabs.

Part of the problem is that you're experiencing https://github.com/mozilla-mobile/fenix/issues/20637, so I think fixing that will make the situation better.

**Comment by dolfinus** [comment]
The issue was caused by Search tabs grouping feature, which was removed in #21898
