### ISSUE TITLE
Option to separate URL address bar from Toolbar

### ISSUE THREAD

**Issue by iamkartk** [mozilla-mobile/fenix#20967]
![130192608-bcb8942b-057a-473e-af2a-9a4dae6e4025](https://user-images.githubusercontent.com/56734031/130431394-7aaaecc6-c2fa-4277-8e2b-75d71c3a064f.PNG)
Please there is no need of url address bar in toolbar. Toolbar needs necessary most required functions like forward, backward, search, tab and menu options instead of url address bar.
Take firefox ios browser.
Url address bar is at top.
In bottom toolbar, commonly required functions are available like backward, forward, search, tab, and menu.
Option can be provided whether one wants separate URL address bar or URL address bar in toolbar itself just as in Vivaldi Android browser.
I want top URL address bar but bottom toolbar with features of backward, forward, search, tabs, menu icons just like in Firefox iOS browser and that is not possible from settings.
Currently my main android browser is Opera android browser which is exactly like firefox IOS browser; URL address bar is at top seperate from main toolbar which is at bottom.
While clicking on Search Icon from bottom Toolbar; URL address bar is automatically selected so no need of whole URL bar at bottom which is even good for large screen phones.
By keeping URl address bar and bottom toolbar seperate, browser becomes easy to use with much more options.
In Yandex android browser too, option is provided whether one wants address bar at toolbar itself or not.
If yes then toolbar works as in firefox android.
If no then URL bar becomes separate from main toolbar and gets other menu options right on toolbar itself.
In Yandex browser, even by keeping Address bar and toolbar separate, both are at bottom.
I really dont see whats wrong in providing options.
I love firefox windows browser because it has so many options.
Take another example of Samsung Android browser where bottom toolbar is customizable as well, so you can add or remove options from toolbar.
Just implement the same firefox ios browser features in firefox android.
Currently firefox android browser is very cumbersome to use.

**Comment by sheikh-azharuddin** [comment]
I liked the Samsung internet browser implementation..the address bar on top and bottom toolbar which is easily customisable
