### ISSUE TITLE
Your Library on Home Tab

### ISSUE THREAD

**Issue by iamkartk** [mozilla-mobile/fenix#20970]
![130192608-bcb8942b-057a-473e-af2a-9a4dae6e4025](https://user-images.githubusercontent.com/56734031/130431978-30bbf828-7a78-4c35-be50-d55f19e3956c.PNG)

Your Library as in Firefox iOS  that includes History, Download, Bookmarks, Reading List right on home tab should be featured in Firefox for android as well.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/14259
