### ISSUE TITLE
Bug: Use Proton icon for home button (again)

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla-mobile/fenix#20984]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

![Screenshot_20210823-175310.png](https://user-images.githubusercontent.com/17863082/130524648-e24e37d6-4fb0-4a56-a6a2-6faf3c0e3422.png)

This was an issue before, when the home icon was first added to Fenix. #19951

Now it seems to be an issue once again. The home icon on the URL bar is inconsistent from the icon on Firefox for desktop, and probably wrong given that it looks out of place with its inconsistent stroke width when compared to other icons.

No worries, mistakes happen, but could this be fixed? It doesn't fit in with the rest of the Firefox design language and that's not surprising given that it's the same home icon from Chromium... not Firefox.

**Comment by amedyne** [comment]
@gabrielluong or @mcarare has this been affected by #20927 ?

**Comment by mcarare** [comment]
No, this change was unintentional in https://github.com/mozilla-mobile/android-components/pull/10825. 
I put up a PR to bring it back: https://github.com/mozilla-mobile/android-components/pull/10869

**Comment by kbrosnan** [comment]
PR is merged this will be fixed in the next release.
