### ISSUE TITLE
FNX-5453 ⁃ New Firefox Preview icon does not spark joy like old Fenix or Firefox icons

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#2098]
The bright blue and orange Fenix icon, and the Firefox icon, are playful and joyful: imo, they have significantly more character than competitors whose icons feel more like, "Utility browser application". While I may just be missing the familiar Fenix icon and having an immediate instinctual reaction, I feel the new wireframe logo doesn't provide the same joyful pride that I get from using other Firefox products. The lack of filling/color makes it feel a little too empty.

Anecdotally, it may not just be me: I've heard users say they keep Firefox installed just because they really like the icon (or that they use Firefox release over nightly because the icon is better; I can't remember, have these come up in user research?).

Sorry if this feedback is too subjective or not helpful.

Maybe dupe #2060 (but that seems focused specifically on background colors).

Before screenshot: https://github.com/mozilla-mobile/fenix/issues/1714#issuecomment-484588731
After screenshot-ish: https://github.com/mozilla-mobile/fenix/issues/1714#issuecomment-484716328

**Comment by kbrosnan** [comment]
This is not the final icon. Lets have one issue about icon bike shedding. Duping to #2060
