### ISSUE TITLE
FNX-5455 ⁃ Sessions Prototype: Crash when attempting to conduct search

### ISSUE THREAD

**Issue by hmcgaw** [mozilla-mobile/fenix#210]
## Steps to reproduce
Open browser
Tap search bar
Type into keyboard and submit

### Expected behavior
Search results displayed

### Actual behavior
App crashes

### Device information
* Android device: Nexus 6P
* Fenix version: Sessions prototype, first version

**Comment by sblatz** [comment]
I cannot reproduce this on the latest master build.
