### ISSUE TITLE
[Bug] KitKat support?

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2100]
Given that Fennec is on the way to being EOLed, I figured I would report this to see whether Mozilla was interested in supporting KitKat devices. 

KitKat still has a nearly 7% share of Android today, per https://developer.android.com/about/dashboards

FWIW, Focus, Edge, Opera, Kiwi Browser (this has Chrome extensions support as well!) all seem to work on this device. Something to think about to provide a migration path for existing Fennec users. 

## Steps to reproduce
Try to install Fenix on a KitKat device. 

### Expected behavior
Can install. 

### Actual behavior
Can't install. 

### Device information
* Android device: LG Optimus G
* Fenix version: latest

**Comment by reinhart1010** [comment]
The `minSdkVersion` for Fenix is 21, which is the API level of Android Lollipop (5.0). See https://github.com/mozilla-mobile/fenix/blob/master/buildSrc/src/main/java/Config.kt

It's also consistent with GeckoView Android components as in https://github.com/mozilla-mobile/android-components/blob/master/buildSrc/src/main/java/Config.kt

**Comment by DancingBear1** [comment]
I'm sorry, but I don't quite understand your answer. Are you saying that it is not possible because of technical issues (some API not working in KitKat) or are you saying that it could be changed to sth. else and thus support KitKat?

@reinhart1010

**Comment by Jap2-0** [comment]
@reinhart1010 What api limitations are preventing this from being compiled for 4.4 (and would it be feasible for me to do so myself)?

**Comment by KOLANICH** [comment]
@Jap2-0 , https://github.com/mozilla-mobile/android-components/issues/5640#issuecomment-576781035

**Comment by kbrosnan** [comment]
Earlier versions of Android are not going to be supported in Fenix. It forces us to make too many engineering compromises. As of this comment the minSDK is 21.
