### ISSUE TITLE
FNX-5457 ⁃ [bug] Inconsistent Navigation bar colors dark / light

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2102]
I noticed after installing Fenix on an old Moto G (in trying to test on older devices #1838) that the dark bottom navigation makes the overall UI look _much_ better to my eye.

See screenshot:

![Screenshot](https://user-images.githubusercontent.com/152493/56839874-a36dcd80-6852-11e9-9edb-35975f6d4820.png)UNITO-UNDERSCORE!2019-04-26-18-26-32!

But on my primary device (Pixel 2), it appears as exactly the same color as the location bar. 

Not sure which one is correct. 

### Why/User Benefit/User Problem
Users would like to use an app that looks polished, and a nicely contrasting bottom navigation that cleanly separates the app from phone navigation is nice to use and pleasing to the eye. 

### What / Requirements
The bottom navigation is white buttons on black, instead of the current gray on off white, where there is a separator between the app and the navigation. 

### Acceptance Criteria (how do I know when I’m done?)
Dark navigation on bottom bar.

**Comment by yoasif** [comment]
I realized after I posted the initial story that this is inconsistent across devices. On the Moto G and HTC Desire 820, the bottom navigation is dark, but on my Pixel 2, it is light colored. 

Not sure that this is by design or a bug, but I definitely prefer the dark colored navigation.

**Comment by ekager** [comment]
The light navigation is by design, but older devices do not allow us to change the icon colors to dark if we set the background to light, so we have chosen to not change the navigation colors there.

**Comment by yoasif** [comment]
Ouch. I vastly prefer the darker navigation, as it provides a clear separation between the app and navigation; not only that, when the quick action toolbar is open, the whole bottom section of the app seems to get muddled together and distracting for me.

**Comment by vesta0** [comment]
Thanks @yoasif we will consider this during user testing!
