### ISSUE TITLE
[Bug]: Links open in browser even when open in app is set

### ISSUE THREAD

**Issue by SinadShan** [mozilla-mobile/fenix#21026]
### Steps to reproduce

1. Toggle open links in app from settings
2. Open YouTube or any other website whose app is installed in the device

### Expected behaviour

Opens in app

### Actual behaviour

Opens in browser itself

### Device name

Xiaomi Redmi 6 Pro

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

91.3.0

### Additional information

This behaviuor prevents websites like WebEx that do not run on the browser, from working at all, since they can't be opened in app. Tried with different search engines.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17700)

**Comment by markcellus** [comment]
This is still an issue unfortunately.

**Comment by andrasp** [comment]
This is still a problem on some links. For example, https://youtu.be links open correctly in the YouTube app, but https://youtube.com links still open in Firefox. While in the Firefox preview app, if I explicitly select "Open in app" then it opens the latter correctly in the YouTube app as well. However, this is not the default behavior as is expected.

**Comment by markcellus** [comment]
Reddit and HackerNews links don't seem to work as well.
