### ISSUE TITLE
Remove the "Delete history" button for a delete menu item

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#21037]
This removes the "Delete history" button in the History fragment in favour of a delete menu item.

https://www.figma.com/file/am9EJGg6ow29PXWkc9jcOH/MR2?node-id=1309%3A182821

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview 93.0.0-beta.1.

### Devices used:
- Huawei MediaPad M3 (Android 7)
- Oppo Find X3 Neo (Android 11)
