### ISSUE TITLE
Disabling Automatic Font Sizing unexpectedly improves scroll performance

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21033]
_Originally reported at https://www.reddit.com/r/firefox/comments/pa5aca/just_discovered_how_to_make_firefox_nightly_for/_

### STR
- Open a web page
- Scroll & observe scrolling smoothness
- 3-dot -> Settings -> Accessibility
- Disable "Automatic font sizing"
- Return to web page
- Scroll & observe scrolling smoothness

### Expected
Smoothnesses are the same

### Actual
Scrolling is smoother without setting enabled.

### Additional details
We suspect the root cause is a memory leak in accessibility and it's being investigated in https://bugzilla.mozilla.org/show_bug.cgi?id=1726887.

**Comment by lnicola** [comment]
I tried this and it does feel snappier, but I'm not sure it's related to accessibility. I have my fonts set to "small", and I think it's just a performance problem related to text rasterization/rendering.

**Comment by mstange** [comment]
It would be great to have a profile here.

**Comment by mcomella** [comment]
I'm unable to reproduce this on the latest nightly. iirc, I originally could reproduce on reddit and kotaku but the scroll performance on this sites seems relatively smooth.

@lnicola Are you still able to reproduce this issue?

**Comment by mcomella** [comment]
Triage: the difference between the two is not easily perceptible on tho Moto G5 so not setting P1.

**Comment by mcomella** [comment]
Triage: since we weren't able to see a difference on the Moto G5 in November, it seems like there's nothing to address. Closing – please reopen if this is still an issue!
