### ISSUE TITLE
[Bug]: bad tabs number postion

### ISSUE THREAD

**Issue by 532910** [mozilla-mobile/fenix#21034]
### Steps to reproduce

I dunno how to reproduce this. Just sometimes it happens.

### Expected behaviour

![image](https://user-images.githubusercontent.com/14617699/131013809-04d4f603-ef36-44a9-a84e-a24238042437.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/14617699/131013643-dffab459-7b7c-4c30-ac6a-697d8edbe2a7.png)

### Device name

OP3T

### Android version

11

### Firefox release type

Firefox

### Firefox version

91.3.0

**Comment by kbrosnan** [comment]
I have seen this, maybe a problem with `9`. @cadeyrn was it number 9 as well?

**Comment by cadeyrn** [comment]
@kbrosnan Yes, I saw this with 9 tabs as well.

(It seems that you closed this issue by accident.)

**Comment by 532910** [comment]
still not fixed, please reopen, ff 103.2.0
