### ISSUE TITLE
[Bug] Save passwords on sites

### ISSUE THREAD

**Issue by yones11** [mozilla-mobile/fenix#21041]
Why is it not suggested to save passwords on some sites ??

Like this site: https://kbc.exirbroker.com/mobile/index.html#view/login.html
Try it for yourself .. Storing passwords on this site in Google Chrome is not a problem

**Comment by kbrosnan** [comment]
The linked page does not load. There is no way to investigate your problem without a functioning link.

**Comment by yones11** [comment]
Oh, it's true, sites like this can only be opened with the Iranian IP ..
Please use these Iranian configurations in the openvpn program to check
further; at this site: https://freevpn.gg/c/188.208.156.128

در تاریخ دوشنبه ۳۰ اوت ۲۰۲۱،‏ ۱۹:۵۳ Kevin Brosnan ***@***.***>
نوشت:
