### ISSUE TITLE
[Bug]: Text cursor handle is white

### ISSUE THREAD

**Issue by kevinoid** [mozilla-mobile/fenix#21048]
### Steps to reproduce

1. Navigate to a page with a text input. (e.g. https://www.wikipedia.org/)
2. Enter text in the text input. (e.g. "Abcde")
3. Tap to move the text cursor position. (e.g. between "b" and "c")

### Expected behaviour

The handle/bubble/accent below the cursor would appear as a blue droplet, as it previously did:
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/336433/131142985-1df9ca92-e89e-4c65-814b-4cde0911c1eb.png"><img src="https://user-images.githubusercontent.com/336433/131142985-1df9ca92-e89e-4c65-814b-4cde0911c1eb.png" alt="Screenshot of Firefox 91.3.1 (Build #2015830179) showing blue cursor bubble" width="270" height="480"></a>

### Actual behaviour

The handle/bubble/accent below the cursor appears as a white droplet, making it hard to see:
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/336433/131143241-0ec0edfe-0df0-4090-8c65-e1d4655b970a.png"><img src="https://user-images.githubusercontent.com/336433/131143241-0ec0edfe-0df0-4090-8c65-e1d4655b970a.png" alt="Screenshot of Firefox Nightly 93.0a1 (Build #2015830443) showing blue cursor bubble" width="270" height="480"></a>

### Device name

Google Pixel

### Android version

Android 10 (Build QP1A.191005.007.A3)

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1 (Build #2015830443)

### Additional information

I'm unable to reproduce the issue with `mozregression --app gve`.

**Comment by mariansima** [comment]
Hey @kevinoid I could not reproduce this issue on the latest Nightly build (93.0a1 2021-09-01) on Samsung A8 with Android 9. I switched keyboards, system font and size without luck. Does this issue still occur if you update nightly?

**Comment by kevinoid** [comment]
Thanks for investigating @mariansima!  I am still able to reproduce the issue with Nightly 93.0a1 (Build \#2015831403) 2021-09-01.

I just realized the issue may be related to the [Dark theme](https://support.google.com/android/answer/9730472) setting, which is enabled on my device and causes a white cursor handle in other apps as well (which looks nice against a dark background).  However, I tried disabling it just now and the text handle still appears white (even after restarting the device).

Let me know if there's anything else I can to do investigate.

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on the latest Firefox Preview Nightly 2021-09-01. I didn't manage to get a white dropled however I did manage to get a green one. The issue does not occur on Firefox RC 91.4.0.
### Device used:
- Oppo Find X3 Neo (Android 11)
![1630500762324](https://user-images.githubusercontent.com/50983519/131674688-c2e6ee8e-0d24-4399-8efa-0c6f1a971401.JPEG)

**Comment by kevinoid** [comment]
After uninstalling the Nightly app and reinstalling (from Play Store) I'm no longer able to reproduce the issue.  If there's anything else I can do to investigate, let me know.  If not, feel free to close.  I can reopen if the issue reoccurs.
