### ISSUE TITLE
FNX-5458 ⁃ [Bug] Main three dot menu does not have proper shadows behind menu

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2105]
## Steps to reproduce
1. Open 3 dot menu in home or when a tab is opened

### Expected behavior
Shadow behind menu.

### Actual behavior
Shadows on corners, but not along most of the menu. 

![Screenshot](https://user-images.githubusercontent.com/152493/56840349-18da9d80-6855-11e9-97ef-190ffff4e1d1.png)UNITO-UNDERSCORE!2019-04-26-18-53-38!

### Device information
* Android device: Moto G
* Fenix version: latest from play store

**Comment by sv-ohorvath** [comment]
It looks good on my devices, with shadow all-around:
P9 lite (Android 6)
Nexus 5 (Android 6)
@yoasif Are you still seeing this issue?

**Comment by yoasif** [comment]
@sv-ohorvath I still see the issue on my Moto G (Android 5.1).

**Comment by sv-ohorvath** [comment]
Saw it too on a Xiaomi Mi Pad 2 (Android 5.1).

**Comment by AmyYLee** [comment]
I'm not seeing this issue on my Pixel 3 (Android ver 9). Can we confirm the extent of devices that this affects?

**Comment by sv-ohorvath** [comment]
So far we saw this issue on:
Moto G (Android 5.1)
Xiaomi Mi Pad 2 (Android 5.1)
Mi 4i (Android 5.0.2)
So it seems that only android 5 devices may be affected.
