### ISSUE TITLE
[Bug]: uBlock Origin crashes Firefox

### ISSUE THREAD

**Issue by SamuelePilleri** [mozilla-mobile/fenix#21058]
### Steps to reproduce

1. Install uBlock Origin Firefox extension
2. Visit https://pagellapolitica.it/blog/show/1186/da-israele-al-regno-unito-arrivano-i-primi-dati-sul-calo-dellefficacia-dei-vaccini (same happens with many other web pages)

### Expected behaviour

The page opens correctly.

### Actual behaviour

The browser crashes.

### Android version

Android 8.1

### Firefox release type

Firefox

### Firefox version

91.3.1

### Additional information

Already reported the issue to uBO, where I was instructed to report it here https://github.com/uBlockOrigin/uBlock-issues/issues/1699

**Comment by Amejia481** [comment]
Thanks for reporting, 
Would you mind sharing the crash stack trace? you can do it by going to Settings -> About Firefox -> Crashes -> Use the share link.

**Comment by Amejia481** [comment]
I wasn't able to reproduce on `91.3.1` with Android 11. Would you mind sharing which brand/model is your devices?

**Comment by SamuelePilleri** [comment]
Thank you for looking at this. I'm not sure what changed (same versions of everything as yesterday), but I can't reproduce it anymore.
As for the device, it's a BlackBerry Motion and this is a crash from the day before yesterday: https://crash-stats.mozilla.org/report/index/bp-aa897dec-44b7-4005-8fb1-bf7060210829

**Comment by Amejia481** [comment]
Don't worry I filed this ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1728589 for GeckoView team to take a look as it's a native crash.

**Comment by abodea** [comment]
@Amejia481 I will remove the `eng:qa:needed` until further notice as you reported the Bugzilla bug and it is still open.

**Comment by SamuelePilleri** [comment]
Here we go again, this time with this page (it's Venice Internet Exchange): https://www.vsix.it/it/supporto/tabella-di-peering.htm

https://crash-stats.mozilla.org/report/index/bp-18c3447a-c356-4680-8387-66dc10210919
https://crash-stats.mozilla.org/report/index/bp-a4d0545c-1426-4d23-ab01-a56ac0210919

**Comment by kbrosnan** [comment]
Closing crash that is tracked in bugzilla.
