### ISSUE TITLE
[Bug]: Bad tabs window behavior

### ISSUE THREAD

**Issue by wladmis** [mozilla-mobile/fenix#21055]
### Steps to reproduce

1. Surf the Internet, open the tabs, read its contents.
2. Open the tabs window (by clicking on tabs number button).
3. Close some tab you want to close.

### Expected behaviour

The tab you want to close closes.

### Actual behaviour

In some cases the tabs in the tab window shift up after you decided to close some tab and started doing it, but before you did it, and you close the wrong tab.

### Device name

Irrelevant

### Android version

Irrelevant

### Firefox release type

Firefox

### Firefox version

91.3.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17726)

**Comment by nagelfargithub** [comment]
I'm having the same issue in 92.1.1 on a Huawei 7 inch tablet. The tabs in the tab view just decide to shift randomly and I either close the wrong tab or I switch to the wrong one.

**Comment by LaviniaL99** [comment]
Hello @wladmis 
 I tested the above issue on the latest Nightly build and latest RC version (97.1.0) and i was not able to reproduce the issue. 

**Devices used:**
- Samsung S10 (Android 10)

Can you please verify the flow again and let me know if you are still able to reproduce it on the latest builds? If yes, please attach a video for it and type of the device you are using it/ android version.

Thanks!

**Comment by nagelfargithub** [comment]
Tested on King Kong Mini FF 96.3.1, also still happens on Hawei 7 inch tablet, same version. Video can be found at https://www.youtube.com/watch?v=yPG4YjjEtSQ
Make sure to watch the whole thing, there is a subtle difference on the third try.

**Comment by LaviniaL99** [comment]
Hello @nagelfargithub 


Thanks for your video, i followed the same flow as per you video but i'm still not able to reproduce the issue.
