### ISSUE TITLE
[Bug]: Hyphen-wrapping words doesn't disable ligatures

### ISSUE THREAD

**Issue by viraptor** [mozilla-mobile/fenix#21050]
### Steps to reproduce

1. Go to https://www.baldurbjarnason.com/2021/software-crisis-2/
2. Find the word "effect" which is wrapped at the end of the line.

### Expected behaviour

"effect" has a ligature on "ff", but a split word "ef- fect" does not.

### Actual behaviour

"ef" ends with half-ligature and "fect" starts with half-ligature.
![image](https://user-images.githubusercontent.com/188063/131201454-e37a704b-9114-483f-90e9-dbe7e9dcc3d0.png)

### Device name

OnePlus 6

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

91.3.1

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1728634

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
