### ISSUE TITLE
Quicker way to toggle between tabs

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#21056]
The current way to toggle between tabs is less than acceptable. Currently I have to scroll through a huge, and I mean HUGE, list of inactive tabs to just get to the bottom of my tab list. Compare this to DuckDuckGo and its tab management, what a dream! Firefox must start to take usability way more seriously as it is going to make people abandon the browser!

**Comment by kbrosnan** [comment]
Firefox tabs are the same general design as DDG. It is possible that you are using the list view. 

* 3 dot menu in Firefox
* Settings
* Tabs
* Grid
