### ISSUE TITLE
show search suggestions from bottom when using bottom address bar

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21052]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
When bottom address bar is used, and you search anything ideally the results should show from the bottom like vilavldi browser..instead it is showing from the top..

### How do you know that this problem exists today? Why is this important?
Result should show up from bottom ...showing result from top defeat the purpose of having bottom address bar which is used with large devices for better comfort to the fingers

### Who will benefit from it?
Users will large devices who are using bottom address bar

Attaching image from vilvaldi...

![Screenshot_20210828-174629269](https://user-images.githubusercontent.com/58127841/131217681-e6491e3c-81fd-41a8-805b-9dd59bc66e17.png)
![Screenshot_20210828-174700619](https://user-images.githubusercontent.com/58127841/131217685-c79df706-5f59-445f-a6ff-fde6e290ea71.png)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/14017
