### ISSUE TITLE
[Feedback] The scan/shortcuts bar is not needed

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2106]
IMO the space used by this bar could be better used to show address bar suggestions. The QR code button may be place inside the address bar, to the right, until the user starts typing something, then it turns into a search button, no need for more elements using more space. The current search engine icon may be used as the shortcuts button itself. In fact, Opera Mobile behaves that way. Fenix could me more minimalist.
![Screenshot](https://user-images.githubusercontent.com/32398857/56844181-8f41c480-6882-11e9-8bda-d902ef7651bd.jpg)UNITO-UNDERSCORE!20190427-001003!UNITO-UNDERSCORE!Firefox Preview!

**Comment by lime124** [comment]
removing ux label. we can group all search screen related issues together to tackle at one time.

**Comment by kbrosnan** [comment]
We have some redesigns of the search view in the works. While this might not be addressed it is more compact. This is a very specific request and may choose to do something similar in the future.
