### ISSUE TITLE
Remove the Falcon dependency

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#21067]
Fenix includes https://github.com/jraska/Falcon as a dependency but it doesn't actually seem to be used. I could not find any invocations of the Falcon code. Let's remove this dependency.

**Comment by VitalyVPinchuk** [comment]
Hello Stefan!
It looks like pretty easy task. May I open PR?
@st3fan

**Comment by st3fan** [comment]
Oh I see the comment now `// This Falcon version is added to maven central now required for Screengrab`. So maybe this is required for making screenshots with Fastlane?

**Comment by st3fan** [comment]
See https://github.com/mozilla-mobile/focus-android/issues/5267
