### ISSUE TITLE
Make it possible to have a "default location" for bookmarks

### ISSUE THREAD

**Issue by satoshizzle** [mozilla-mobile/fenix#21068]
Hi, 

It would be great to have the ability to set a default location when saving bookmarks in Firefox mobile. Now they default into a mobile bookmarks folder but i would like to have them somewhere else. Sometimes firefox mobile remembers the last location when i'm still in the same session, but having a setting that makes it possible to set it as default would be a great feature.

Here a reddit thread about it: https://www.reddit.com/r/firefox/comments/pdnhaz/sunday_rantrage_20210829_your_weekly_complaint/harwrn3/

Thank you!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17734)

**Comment by LaurentiuApahideanSV** [comment]
Possibly related to https://github.com/mozilla-mobile/fenix/issues/4318.

**Comment by mortee** [comment]
This would be nice, or at least rememberig the last used folder across sessions. I see absolutely no reason why I would add new items in the "Mobile Bookmarks" folder, just because I visited on my cellphone.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813667

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
