### ISSUE TITLE
Make "send to device" destinations fixed in place

### ISSUE THREAD

**Issue by bxtom** [mozilla-mobile/fenix#21072]
I'm sending a lot of my tabs from Android to my private laptop and some tabs to my work laptop. Order of destination devices keeps changing couple of time per day. This is bad. Muscle memory is very powerful thing. Why I must stop for a second and wait for my devices to reorder itself each time I want to send something?

I fear I may someday lose my job by sending some NSFW content to my work laptop because Firefox decided to reorder destinations right when I tapped :)

**Comment by VitalyVPinchuk** [comment]
Hi all
May I open PR to sort the device list?
