### ISSUE TITLE
FNX-5459 ⁃ The address bar should show something as soon as it's touched

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2107]
### Why/User Benefit/User Problem
Once you touch the address bar Opera shows trending searches and recent searches, Chrome show the most visited websites, Samsung Internet show it's top websites, but Fenix doesn't show anything until the user starts typing. Showing something as soon as the user touches the address bar, without further interaction, saves time.

### What / Requirements
Some kind of suggestions once the address bar is touched.

### Acceptance Criteria (how do I know when I’m done?)
Touching the address bar triggers some kind of suggestions

**Comment by SKITTLE-LA** [comment]
I think this is similar to #1981 I created a few days ago, although I don't think suggestions should show until anything is typed.

**Comment by vesta0** [comment]
Thanks for the suggestion @Lululalu . We will look at this as part of #1981.
