### ISSUE TITLE
Investigate/remove the Master Password tip

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#21075]
We are removing the telemetry for the MP with regards to the migration from Fennec to Fenix ([PR](https://github.com/mozilla-mobile/fenix/pull/21076)). The `MasterPasswordTipProvider` was implemented at the same time to ease the transition for MP users. This class can probably be removed entirely.

https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/components/tips/providers/MasterPasswordTipProvider.kt

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17737)

**Comment by pocmo** [comment]
This work will likely be part of https://github.com/mozilla-mobile/fenix/issues/22489

**Comment by eliserichards** [comment]
Closing as resolved
