### ISSUE TITLE
FNX-5460 ⁃ [Bug] Downloaded files can't be opened

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2109]
### Steps to reproduce
1. open https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly.2019.4.26/latest
1. download public/target.aarch64.apk
1. go to your Android downloads and try to open the downloaded files

### Expected behavior
The .apk file will be opened so that you can install that Fenix build.

### Actual behavior
Only a error message appears: "Can't open file".

Doing exactly the same steps in Firefox works.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 11918d45f4ce97f9c64273fcbe6f7df1d6fd4365

**Comment by reinhart1010** [comment]
The file cannot be opened because you have to enable "Install unknown apps" permission in device settings (for individual apps). This is compulsory starting Android 8.0 (Oreo).

![Screenshot_20190501-183123_Settings](https://user-images.githubusercontent.com/17312341/57015516-5b2e2100-6c3f-11e9-8af2-255318265eb6.jpg)

There should be a good UX flow here.

**Comment by TitanNano** [comment]
I have android 7.1.1 and it doesn't work for APKs downloaded by Fenix. APKs downloaded by Fennec on the other hand can be installed just fine.

**Comment by cadeyrn** [comment]
@reinhart1010 On my device Fenix already *has* the permission and it doesn't work, so this can't be the reason.

**Comment by buttercookie42** [comment]
And AFAIK, the "install apps" permission should work somewhat like the other runtime permissions, i.e. the OS will prompt you about it and ask you whether you want to enable the permission for that app.

**Comment by cadeyrn** [comment]
Does anyone already have an idea what the reason is why downloaded files cannot be opened? Is this a Fenix / AC / GV issue?

**Comment by sblatz** [comment]
Some investigation shows this applies to *all* files including things like PDFs, so it's not specific to APKs.

**Comment by vesta0** [comment]
@sblatz is this issue specific to some devices or Android versions? It works for me.

**Comment by sblatz** [comment]
I'm seeing this on my Galaxy S9 on 9.0.0. @vesta0 do all files open normally on your Pixel?

**Comment by vesta0** [comment]
@sblatz I haven't tried all file types but APKs and PDFs work as long as they are not on a page requiring authentication.

**Comment by andreicristianpetcu** [comment]
This also happens on my [OnePlus 5](https://github.com/mozilla-mobile/fenix/issues/2283). I cannot install Fenix by downloading the Fenix APK with Fenix. Maybe listing the phones/OSes here that have the issue, helps understanding it.

**Comment by Amejia481** [comment]
There some combined issues here:

1. The default file manager is not understanding the file extension "target.**aarch64.apk**"
2. You may be trying to install the same app that you already have installed..

__________________________

####  1) The default file manager is not understanding the file extension "target.**aarch64.apk**"

 The default file manager is not understanding the file extension as the file ends on "target.**aarch64.apk**", the file manager doesn't know how to handle this file type and shows the message **"Can't open file"**. 

This can be demonstrated by downloading another apk file that the file name ends on **".apk"** like https://github.com/mozilla-tw/FirefoxLite/releases/download/v1.7.0/Firefox-Lite-12623.apk. You will be able to download it and install it without issues.

Also, you can try by using another file manager like [asus.filemanager](https://play.google.com/store/apps/details?id=com.asus.filemanager).

1) Download the "target.**aarch64.apk**" with Fenix.
2) If you already have [Fenix from the Play Store ](https://play.google.com/store/apps/details?id=org.mozilla.fenix) deleted it (**See 2** You may be trying to install the same app that you already have installed)
3) Navigate to download folder and open the apk. It should work as expected. On Android 7 or below be aware of https://github.com/mozilla-mobile/fenix/issues/3890.

 ___________________

#### 2) You may be trying to install the same app that you already has installed.
The **target.aarch64.apk** file has the same app id as the one [on the play store](https://play.google.com/store/apps/details?id=org.mozilla.fenix), you are not going to be able to install both at the same time.


@cadeyrn Let me know if that works for you.

**Comment by sarentz** [comment]
@mitchhentges Check the _ The default file manager is not understanding the file extension as the file ends on "target.aarch64.apk",_ part - maybe we want to change the naming of the resulting APKs because it is useful to being able to download them from TC.

**Comment by mitchhentges** [comment]
Created #3893 :)

**Comment by andreicristianpetcu** [comment]
Firefox Lite APK works @Amejia481
The Fenix build works fine in Fennec, it's broken only in Fenix. Same apk file.

**Comment by Amejia481** [comment]
@andreicristianpetcu in Fenix we are relaying for now on the default Android download manager while in Fennec we are using a custom download provider. We are working on improving downloads with our custom provider on https://github.com/mozilla-mobile/android-components/issues/1968 that will fix this and other related issues.

**Comment by sblatz** [comment]
To clarify: It sounds like this issue can be closed since #3893 addresses specifically nightly builds failing to open and https://github.com/mozilla-mobile/android-components/issues/1968 addresses implementing a custom download manager?

**Comment by andreicristianpetcu** [comment]
@sblatz the gecko download manager issue was closed. When will we see it in Nightly?

**Comment by Amejia481** [comment]
@andreicristianpetcu   I think It will be introduced to Fenix after further testing cycles.

**Comment by mitchhentges** [comment]
It [sounds like andrei is still running into this issue](https://github.com/mozilla-mobile/fenix/issues/3893#issuecomment-513899836).
@andreicristianpetcu, can you confirm that you're not being affected by either cause [described by Amejia](https://github.com/mozilla-mobile/fenix/issues/2109#issuecomment-508528688)? If you are indeed still running into this problem due to a different cause, then please re-open this ticket so we can track down the issue.

(if this comment double-posts, it's because GitHub appeared to lose my comment the first time)

**Comment by andreicristianpetcu** [comment]
@mitchhentges I'm not trying to install the same file. Once I download the file with Fenix, I can install it with a different file manager.

I will wait for the fancy new a-c download manager :)

**Comment by andreicristianpetcu** [comment]
Related to my other comment. I can install apk files in nightly without the need of an external file manager. Pretty nice!
