### ISSUE TITLE
Allow users to customize their home screen

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#21095]
https://mozilla-hub.atlassian.net/browse/FNXV2-17707

**Comment by Amejia481** [comment]
QA team please help us to verify

We added a new setting to customize what features users see in they home screen.

`Settings` -> `Customize` -> Home

We want to verify that features on the home screen are visible based on the toggles in this section

1. Jump back in
2. Recently bookmarked
3. Recently visited.

Additionally, we added two shortcuts to get to this page.

1. When one of these features are active at the bottom of the home screen it should be displayed a button called "**Customize home**".
2. In the three dotted menu "**Customize home**", this one should be always visible.

Both options should take the user to Customize settings page

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Preview Nightly 2021-09-23. The "Customize home" buttons are present and functioning as specified. The sections on the home page are also shown/hidden depending on the selected setting.
### Devices used:
- Oppo Find X3 Neo (Android 11)
- OnePlus 6T (Android 9)
