### ISSUE TITLE
FNX-5461 ⁃ Sessions Prototype: Lag between text input for URL bar and displayed text

### ISSUE THREAD

**Issue by hmcgaw** [mozilla-mobile/fenix#211]
## Steps to reproduce
1. Tap into URL bar
1. type search term 

### Expected behavior
See inputted text display in URL bar

### Actual behavior
Long pause
Unrelated URL appears in search (wait)
Search term in URL bar
One it appears the text become much more responsive (e.g., if editing the term)

### Device information
* Android device: Nexus 6P
* Fenix version: Sessions prototype, first version

**Comment by pocmo** [comment]
We have a related reference browser issue that may have the same cause:
https://github.com/mozilla-mobile/reference-browser/issues/395

**Comment by bbinto** [comment]
@pocmo will look into this and fix asap.

**Comment by boek** [comment]
Awesome! Will try that @pocmo
