### ISSUE TITLE
[Bug]: Can't edit shortcut names on the homescreen until they are deleted

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21101]
### Steps to reproduce

1. Open any web page (e.g. Reddit).
2. Go to Settings and tap Add to Home screen.
3. Return to the page from step one.
4. Tap to add to the homescreen but edit the name.

### Expected behaviour

The user should be able to change the name of the shortcut.

### Actual behaviour

The name of the duplicate shortcut is the same as the first one. The user has to delete the first shortcut in order to edit the title of the second one.

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

91.4.0

### Additional information

The user can edit the name of a shortcut but has to first leave the app, delete the first shortcut and return to the app to make changes persist.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17751)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 100.0a1 (2022-03-24) build.
Device used: Oppo Reno 6 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 109.0a1 (2022-12-12).
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807104

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
