### ISSUE TITLE
[Bug]: Certain text in the settings menu is truncated when the device font size is set to very large

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21105]
### Steps to reproduce

1. Set the device font size to very large
2. Open a tab in Nightly
3. Open the 3-dot menu
4. Navigate and observe the following sub menus:

- Add/Edit bookmarks button (also add the site to bookmarks)
- (Have a sign in credential saved) Logins and passwords > Saved logins > select any saved login > Edit
- Credit cards > Add credit card
- Exceptions > Delete all exceptions button
- Language
- ETP > select Custom > open the Cookies drop-down menu
- Delete browsing data > button at the bottom of the screen

### Expected behaviour

Text is clearly visible on all text sizes

### Actual behaviour

Text is truncated when the font size is set to very large

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1 2021-09-01

### Additional information

![241024117_179108410988012_682083374465367275_n](https://user-images.githubusercontent.com/89511597/131686704-70d2f6fc-6993-45a8-827a-401c108278d4.jpg)
![241141728_214127287253565_6207006146974496936_n](https://user-images.githubusercontent.com/89511597/131686708-f9808ef8-44b3-4334-bf44-867f67672556.jpg)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 99.0a1 (2022-03-02).

Devices used:
- Oppo Reno 6 (Android 11).
- Google Pixel 4 (Android 12).

Closing the ticket as fixed.
