### ISSUE TITLE
[Bug]: Firefox Account push events are ignored

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/fenix#21100]
### Steps to reproduce

1. Connect device to a sync account
2. From some other device, either disconnect this device, or change the account password, or delete the account entirely

### Expected behaviour

The device should immediately enter the "account needs attention" state (or, in the case of "account deleted", it should just be silently disconnected from sync entirely, as happens on desktop)

### Actual behaviour

The app looks like there's no account problem until the next sync

### Android version

All

### Firefox release type

Firefox

### Firefox version

All

### Additional information

Best I can tell, the account event magic in android-components is working fine, and is does deliver the events to all listeners - it's just that there are no listeners.

Best I can tell, it's inside one of the app's activities that should do this (eg, it's done in a-c's `samples/sync/src/main/java\org/mozilla/samples/sync/MainActivity.kt`) - so I think it should be done in Fenix. However, Fenix has no references to `AccountEvent` objects.

cc @grigoryk

**Comment by grigoryk** [comment]
I think the original intention was to expand this code to handle account-state events: https://github.com/mozilla-mobile/android-components/blob/main/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/AccountStorage.kt#L94-L108 (there's even a comment about it there).

Putting aside for a moment the odd placement of that code inside a class you'd never guess at first try (which IIRC has something to do with mocking stuff in tests?), I think that's generally right - e.g. if we receive an "account-level" push event, we should handle it in the account manager (via an event on the state machine).

And then Fenix stuff will work as-is without changes - it'll receive an event telling it that the account moved into a "needs authentication" state, or got logged-out entirely, or whatever, that wiring to the UI is already in place.

**Comment by mhammond** [comment]
I think we've solved this on a few other PRs.
