### ISSUE TITLE
FNX-5462 ⁃ [Bug] When opening an external link, pressing back should close the tab

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2110]
## Steps to reproduce
* open another app that is set to open links in browser apps and click on a link
* open the link in Fenix
* press the device back button

### Expected behavior
* tab closes
* this matches behavior that Chrome and Fennec has
* any navigation in the tab should cause Fenix to retain the tab

### Actual behavior
* tab is open

### Device information
* Android device: Pixel 3
* Fenix version: April 27th

**Comment by vesta0** [comment]
@kbrosnan is this happening with tabs? I just tried with both Gmail and Whatsapp and I don't see those open links in my tab list.

**Comment by kbrosnan** [comment]
Are you getting a custom tab? This is with gmail's custom tabs option disabled. The setting that needs to be turned off is "Open web links in Gmail" in the General Gmail settings.

**Comment by ekager** [comment]
Reference Browser has a function removeSessionIfNeeded in BrowserActivity that we could copy over here to fix most of this issue. But IIUC setting the behavior of "any navigation in the tab should cause Fenix to retain the tab" will not happen with this function in its current state.

https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/BrowserActivity.kt#L79-L92

**Comment by ekager** [comment]
I've addressed the closing of a session with source ACTION_VIEW in PR #2953 but I'm not sure how best to deal with "if user has navigated in the session, save the tab". I had an idea to remove the ACTION_VIEW source in onUrlChanged (if the session canGoBack as well), but it looks like I can't change the source of the session. This may require further AC work for this portion.

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/android-components/issues/3257 for the navigation portion of this ticket

**Comment by ekager** [comment]
I discussed with @pocmo in https://github.com/mozilla-mobile/android-components/issues/3257 and there is no further work to be done here. A tab opened from external link will maintain history, but should remove itself on last back press (with no more history).

**Comment by softvision-miralobontiu** [comment]
Verified that when opening an external link, and pressing back:
- closes the tab, and
- homescreen is displayed without the link displayed in "Open tabs".
Tested on the latest build 1.0.1923 (#11561806), with Huawei MediaPad M2 (Android 5.1.1), Motorola Nexus 6 (Android 7.1.1), Xiaomi Mi 8 Lite (Android 8.1).
