### ISSUE TITLE
Build with SDK for Android 12 / API 31

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#21102]
See A-C: https://github.com/mozilla-mobile/android-components/issues/10910

The [beta program for Android 12](https://developer.android.com/about/versions/12/overview) is in the "stability phase" now and the APIs are finalized. Now we can start using 31 as `compileSdkVersion` (not `targetSdkVersion` yet) and get blockers out of the way.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17752)

**Comment by Amejia481** [comment]
We can close this as it was already covered on https://github.com/mozilla-mobile/fenix/commit/099e463b4f8302fd4ab3bdc46b1e4ca277e00702

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/fenix/pull/25494
