### ISSUE TITLE
FNX-5463 ⁃ [Bug] No obvious way to "search" when "Show Search Suggestions" is disabled

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2111]
## Steps to reproduce
1. Disable "Show Search Suggestions" in search engine settings
1. type in something into search/location box

### Expected behavior
top "result" should be something that can be tapped to search using my default search engine. 

Fennec:

![signal-attachment-2019-04-27-142424](https://user-images.githubusercontent.com/152493/56853608-43c9fd80-68f8-11e9-9670-731a2bcbf141.png)

### Actual behavior
The only way to search is to tap the enter key on the on screen keyboard. 

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by ekager** [comment]
We have an issue to remove the suggestion that is your exact query anyway so I'm going to close this issue. Please leave your feedback here #1742
