### ISSUE TITLE
With Desktop mode YouTube videos go beyond the screen

### ISSUE THREAD

**Issue by doktorbob2000** [mozilla-mobile/fenix#21119]
### Steps to reproduce

1. open tab to desktop mode
2. go to YouTube and select any video on Android for mobile device.
3. select full screen

### Expected behaviour

Video should play at full screen and fit to the screen size

### Actual behaviour

YouTube video maximizes but it goes beyond the borders of the screen, accessing play controls involves scrolling down in the video while it is Fullscreened

### Device name

Samsung Galaxy 10E and LG G Pad 

### Android version

Android 11 on Samsung, Android 7 on LG G Pad X 8.0

### Firefox release type

Firefox 91.4 on both devices

### Firefox version

Android 11 on Samsung Galaxy s10e Android 7 on LG tablet 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17761)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 2022-12-01.
### Device used:
- OnePlus 6T (Android 9)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809251

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
