### ISSUE TITLE
1.8 MB APK size regression in v90.1.2 (7/20)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21114]
On the Google Play console for the release channel, we see a 1.8 MB regression from v90.1.1 to v90.1.2 on July 20th. This is especially surprising because this is a dot release.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17759)

**Comment by mcomella** [comment]
Triage: don't have a lot of APK size

**Comment by cpeterso** [comment]
Too late to debug a APK size regression in 2021.
