### ISSUE TITLE
Browser features broken after device screen timeout with an active alert notification

### ISSUE THREAD

**Issue by apromenschenkel** [mozilla-mobile/fenix#21122]
### Steps to reproduce

1. Open any page in Firefox mobile.
2. Connect your mobile device to the Firefox remote debugging interface on a desktop instance for Firefox and open the JavaScript console.
3. Call the alert function with any message: `alert('test')`
4. Do not dismiss the notification.  Allow your mobile devices screen to timeout (go to sleep).  You may need to remove your USB cable from your computer, as adb seems to keep the device awake when it has an active connection.
5. After the device has gone to sleep, unlock it again.  You should notice that the alert notification is gone, and the page is completely unresponsive.
6. Reconnect to the JavaScript console and run: `setTimeout(() => {console.warn("Testing")}, 1000)`.  The "Testing" string will never be printed.
7. Refresh the webpage.  The page should be responsive again, seeming to work as normal.
8. Run the command from step 6 again, and notice that the "Testing" string is still not printed.
9. Kill and restart Firefox on your mobile device.  Run the command from step 6 again.  The "Testing" string should now be printed as expected.

### Expected behaviour

The browser should work display responsive webpages and the `setTimeout` function should work as expected.

### Actual behaviour

Webpages become unresponsive after the device sleeps with an active alert notification.  This is recoverable by a page refresh.  The `setTimeout` function does not work after the device sleeps with an active alert notification.  This is only recoverable by restarting the browser.

These situations apply when creating an alert with the `alert` function, or through the 'unsaved data' message displayed from the `beforeunload` window event.

### Device name

Google Pixel 4a(5g)

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

91.4.0

### Additional information

This issue was seen on the listed Google Pixel phone, as well as a Samsung tablet.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17765)

**Comment by ichaoX** [comment]
From Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1754759#c0

### Steps to reproduce

 1. Open alert box on tab ([attachment](https://bugzilla.mozilla.org/attachment.cgi?id=9263291)).
 2. Switch browser to background.
 3. Switch browser to foreground.

### Expected results

The alert box should not close automatically, or at least not break the interactive input on the page.

### Actual results

The alert box is closed abnormally and the page can't interactive (the link in the attachment is not clickable).

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

97.2.0 or 81.1.4

**Comment by ichaoX** [comment]
This bug affects Firefox 105.

> From Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1754759#c0
> ### Steps to reproduce
> 
>     1. Open alert box on tab ([attachment](https://bugzilla.mozilla.org/attachment.cgi?id=9263291)).
> 
>     2. Switch browser to background.
> 
>     3. Switch browser to foreground.
> 
> 
> ### Expected results
> 
> The alert box should not close automatically, or at least not break the interactive input on the page.
> ### Actual results
> 
> The alert box is closed abnormally and the page can't interactive (the link in the attachment is not clickable).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811595

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
