### ISSUE TITLE
performancetest intent fails if device is plugged in through USB hub

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21126]
For performancetest intents, we measure ([source](https://searchfox.org/mozilla-mobile/rev/61a369a9f61dfa4179b7910e2f6061837fc44c1c/fenix/app/src/main/java/org/mozilla/fenix/perf/Performance.kt#52)):
```kotlin
            val isPhonePlugged = it.getIntExtra(BatteryManager.EXTRA_PLUGGED, -1) ==
                BatteryManager.BATTERY_PLUGGED_USB
```

However, I received `BATTERY_AC` when my phone goes through my USB hub. Given I'm running the backfill.py perf tests and others might run into this if they're trying to skip onboarding, I think we should change this to support both AC & USB.

**Comment by MarcLeclair** [comment]
We should add this to Focus too

**Comment by mcomella** [comment]
- Fenix: https://github.com/mozilla-mobile/fenix/pull/21272
- Focus: https://github.com/mozilla-mobile/focus-android/pull/5378

**Comment by mcomella** [comment]
Both PRs are merged.
