### ISSUE TITLE
Let the user to decide how to access a website. do not restrict user do not access it.

### ISSUE THREAD

**Issue by cnmade** [mozilla-mobile/fenix#21149]
I visit some website ,but firefox prevent me to access it .
![image](https://user-images.githubusercontent.com/278153/132106731-7aef04a2-f645-419d-89e8-c9422999f71e.png)

I think we should have a way to let browser allow me tempory access it .

You should not force user not to access it.

anyone face me with the same problem ?

not every website was dangerous. 

and you have no rights to control what website we can not access it .

**Comment by cadeyrn** [comment]
Your screenshot shows Firefox for desktop, not Firefox for Android. This is the issue tracker for the Android version of Firefox.

**Comment by kbrosnan** [comment]
Closing as a desktop issue. In desktop it is possible to disable safe browsing if the user chooses.
