### ISSUE TITLE
Always show both last media tab AND last non-media tab

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#21140]
If I am playing media on my phone, I always see the last media tab on my homescreen in the Jump back in section. 

If I have non-media tabs open, I always see the last non-media tab on my homescreen in the Jump back in section. 

(This is a change from always showing the last tab only regardless of type)

**Comment by jonalmeida** [comment]
(re-opening so that QA can close the issue when their testing is complete)

**Comment by abodea** [comment]
Hello @MozillaNoah!
So if I opened let's say 2 tabs, Wikipedia and Youtube, when I lock the device I should see both tabs, is that right?
Asking, because now I see only the media tab even tho I opened a new tab that is non-media.

**Comment by MozillaNoah** [comment]
> Hello @MozillaNoah!
> So if I opened let's say 2 tabs, Wikipedia and Youtube, when I lock the device I should see both tabs, is that right?
> Asking, because now I see only the media tab even tho I opened a new tab that is non-media.

For that case, you should see both tabs, as long as the Youtube tab was playing something prior to the lock.

**Comment by MozillaNoah** [comment]
Hi @abodea, here's what the use cases should be:

If the last active/selected tab was media, then that tab and the second-to-last accessed tab should be displayed in Jump Back In. 

(The last accessed tab was Youtube playing a video and the second-to-last tab was a wikipedia page)
![image](https://user-images.githubusercontent.com/87384386/133659258-3f3eebb4-8c13-4954-a929-e89e92c8e5cf.png)

----------------------------------------------------------------------------------------

If the last active/selected tab was NOT media, then that tab and the last-accessed media tab (regardless of when it was last selected/opened by the user) should be displayed in Jump Back In.

(last selected tab was a normal tab, media tab was actively playing content and was the third-to-last accessed tab)
![image](https://user-images.githubusercontent.com/87384386/133659746-697d7da2-3c2c-4467-9bfd-b20a2e1244aa.png)

----------------------------------------------------------------------------------------

If there are NO tabs that played any media, then ONLY the last active/selected tab should be displayed in Jump Back In. 

(Last accessed was a normal tab)
<img width="333" alt="image" src="https://user-images.githubusercontent.com/87384386/133659913-81492619-3331-4d6e-8330-b66fef6fe59b.png">

(Last accessed was YouTube but it's on the home page with no video playing)
![image](https://user-images.githubusercontent.com/87384386/133659949-5e7e8aab-be3d-4285-8b19-aac4a295fcdb.png)

----------------------------------------------------------------------------------------

Let me know if you have any other questions.

**Comment by abodea** [comment]
Thank you for the clarification @MozillaNoah!
Verified as fixed on the latest Nightly 17/9/21 with Google Pixel 4 XL (11).
Note that I was able to verify all 3 scenarios you provided above.
