### ISSUE TITLE
[Bug]: Scrolling of Flutter 2.x apps does not work but works fine in Google Chrome and in the desktop version of Firefox

### ISSUE THREAD

**Issue by dg76** [mozilla-mobile/fenix#21147]
### Steps to reproduce

Open https://flutterlistview.netlify.app/ and try to scroll the page. It cannot be scrolled (only very slow in very small steps and it stops after each scroll gesture) in Firefox on Android but in works fine in Firefox on macOS and Google Chrome on Android.

There is also a bug report for Flutter here:

https://github.com/flutter/flutter/issues/88358

But I thought I should also post it here because is might be a bug in Firefox for Android, not a bug in Flutter, if it works fine in Firefox for macOS and Google Chrome.

### Expected behaviour

The page should be scrollable.

### Actual behaviour

It cannot be scrolled (only very slow in very small steps and it stops after each scroll gesture).

### Device name

Google Pixel 2 XL

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

91.4.0

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1731840

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
