### ISSUE TITLE
[Bug]: Fenix 93.0a1 Crash Report [@ mozilla::dom::Element::GetClientAreaRect ]

### ISSUE THREAD

**Issue by sharbet** [mozilla-mobile/fenix#21153]
### Steps to reproduce

1. Open websites such as:
[(1)](https://m.inven.co.kr/board/maple/2299/7600221?my=chuchu&sort=PID)

### Expected behaviour

Website should open without problems

### Actual behaviour

Application crashes to crash page

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1

### Device logs

https://crash-stats.mozilla.org/report/index/e946ec8c-4226-4b90-bb30-f92c90210905

https://crash-stats.mozilla.org/report/index/fbcfc39f-4fa3-422d-99c2-01ba30210905

**Comment by kbrosnan** [comment]
fixed by bz-1728670
