### ISSUE TITLE
[Bug]: Viewing provided page crashes tab

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#21159]
### Steps to reproduce

Open the following URL...

https://arstechnica.com/gadgets/2021/09/ok-hear-me-out-having-a-desk-bike-is-actually-pretty-great/

Scroll down the page a bit and wait...

### Expected behaviour

Nothing happens, tab remains open.

### Actual behaviour

BOOM! Tab crashes!

### Device name

Samsung Note o

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1 (Build #2015831979

**Comment by kbrosnan** [comment]
Need a crash ID URL or a logcat. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by kbrosnan** [comment]
possibly bz-1728670.
