### ISSUE TITLE
[Bug]: Scrolling provided page crashes tab

### ISSUE THREAD

**Issue by mrandreastoth** [mozilla-mobile/fenix#21158]
### Steps to reproduce

Open the following URL...

https://www.japantimes.co.jp/opinion/2021/08/19/commentary/world-commentary/australia-authoritarian-covid-19-response/

Scroll down the page a bit...

### Expected behaviour

Paywall pop-up shown and tab remains open.

### Actual behaviour

BOOM! The tab crashes!

### Device name

Samsung Note 9

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1 (Build #2015831979

**Comment by kbrosnan** [comment]
possibly bz-1728670. If this is still happens please provide a [crash ID](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information)
