### ISSUE TITLE
Let the user to decide how to access a website.

### ISSUE THREAD

**Issue by amirod** [mozilla-mobile/fenix#21156]
## User Story
- As a us visit some website ,but firefox prevent me to access it .
image

I think we should have a way to let browser allow me tempory access it .

You should not force user not to access it.

anyone face me with the same problem[.](https://yt1s.me/)not every website was dangerous.
and you have no rights to control what website we can not access it .er, I want … so I can do … (keep it problem-centric)

## Dependencies
- List dependencies on other issues/teams etc.

### Acceptance Criteria
- I can do …  (e.g. add a bookmark)

**Comment by cadeyrn** [comment]
Probably a spam user? It's the user's first comment and the text is stolen from #21149.
