### ISSUE TITLE
Option to not remember search and form history

### ISSUE THREAD

**Issue by sebast889** [mozilla-mobile/fenix#2116]
### Why/User Benefit/User Problem
User has no need for them
Uncluttered search/form
Privacy

### What / Requirements
Option to not remember search and form history in Settings.

### Acceptance Criteria (how do I know when I’m done?)
Parity with Firefox desktop.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11173)

**Comment by vesta0** [comment]
@sebast889 how would this be different than using Private mode?

**Comment by sebast889** [comment]
@vesta0

I still want to keep browsing and download history

**Comment by vesta0** [comment]
@sebast889 I understand now, thanks for clarifying!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813102

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
