### ISSUE TITLE
[Bug]: CSS animation is slowing down the whole system

### ISSUE THREAD

**Issue by o-alquimista** [mozilla-mobile/fenix#21164]
### Steps to reproduce

1. Connect to an Android phone via remote debugging (adb) and open this page: https://web.archive.org/web/20210906184617/https://dougsilva.me/
2. Scroll up and down to get a feel for the current performance (it should be very slow and stuttering). You should also notice that everything else is slow (i.e. the browser UI, Android notification area, everything)
3. Inspect the element in which there is a "blinking cursor" animation, then stop the animation (uncheck the animation-name property, for example).
4. Scroll up and down again and you should see it's incredibly faster.

Alternatively, you can try to reproduce it with this fiddle instead, although it's not very mobile-friendly: https://jsfiddle.net/8vzLak0x/

### Expected behaviour

The web app is a lot faster without any animations running, and the very same animation doesn't slow down other browsers, such as Chrome.

### Actual behaviour

Noticeable impact on performance that doesn't only make the browser slow, but the whole Android UI.

### Device name

Motorola Moto G4 Play (codename: harpia)

### Android version

Android 10 (Lineage OS 17.1)

### Firefox release type

Firefox

### Firefox version

91.4.0

### Additional information

The desktop version of Firefox is not affected by this problem; only Firefox for Android is.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1734194

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
