### ISSUE TITLE
[Bug]: Password leaked in my button when Android autocompletes my JIRA account under a webpage.

### ISSUE THREAD

**Issue by julenuri** [mozilla-mobile/fenix#21161]
### Steps to reproduce

1. Use the Android autocomplete function to fill an account of f.e. User: bugpass Password: password under the web https://jira.reactos.org/secure/Dashboard.jspa . Save it.
2. Close the navigator.

3. Open the webpage https://jira.reactos.org/secure/Dashboard.jspa

![A](https://user-images.githubusercontent.com/27921286/132206242-51f87438-dfe0-4f0e-8a6c-9d28f8b190f1.jpeg)

4. Autocomplete the form.

![B](https://user-images.githubusercontent.com/27921286/132206274-7b03b220-aff9-4fac-99e4-389fd5d8e425.jpeg)

5. The login button text will be changed by the password, ergo leaked visually.

![C](https://user-images.githubusercontent.com/27921286/132206296-1421dcd2-9f4e-4398-bbf7-03c02a9c188a.jpeg)

### Expected behaviour

The password will be filled, and the button will be stable.

### Actual behaviour

Firefox leaks the password in a button, that is an unexpected behaviour.

### Device name

Oukitel WP5 Pro

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

93.0a1

### Additional information

Happens also in the Stable Firefox and the beta.

**Comment by kbrosnan** [comment]
The UI that shows your password is not Firefox. Firefox's password UI is just above the keyboard. You have a password app that is showing your password.

**Comment by julenuri** [comment]
> The UI that shows your password is not Firefox. Firefox's password UI is just above the keyboard. You have a password app that is showing your password.

It does not happen in Android with Chrome, but yes under Firefox. Can anyone test it?
