### ISSUE TITLE
Ability to resort and group tabs in the tab pane

### ISSUE THREAD

**Issue by omargoda** [mozilla-mobile/fenix#21166]
### What is the user problem or growth opportunity you want to see solved?
I want to be able to resort and group tabs in the tabs pane so that related tabs take less space and less used tabs be on the bottom of the list

### How do you know that this problem exists today? Why is this important?
The problem was noticed when I wanted to reach a recent tab in the tab pane, but I had to scroll all the way down to the bottom to get it. Conventionally, recent tabs are more used and so that they have to be on the top, not the bottom. Also, related tabs are better grouped together so that they take less space and can be closed as a whole group instead of closing them one by one manually.

### Who will benefit from it?
People who have a lot of tabs open at the same time and people who open a lot of related tabs together like for example e-commerce websites where you want to compare between a lot of items and each of them needs to be open in a separate tab.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/10344
