### ISSUE TITLE
Pull down the page to refresh

### ISSUE THREAD

**Issue by omargoda** [mozilla-mobile/fenix#21175]
### What is the user problem or growth opportunity you want to see solved?
I want when I need to refresh the page to be able to pull down the page to do the refresh as that is the conventional way to refresh on mobile devices.

### How do you know that this problem exists today? Why is this important?
Almost all applications have this refresh method as a conventional and easy way to do the refresh rather than opening the options menu and then choosing the refresh menu.

### Who will benefit from it?
Users who want to refresh their web pages often are the most likely to suffer from this problem and to benefit from this feature.

**Comment by cadeyrn** [comment]
Duplicate of #9766.

**Comment by omargoda** [comment]
So, is nightly the beta version, or a totally different distribution?

**Comment by cadeyrn** [comment]
Nightly is the stage before Beta. Unfortunately I don't know the timeline for enabling pull to refresh in Beta or stable releases.

**Comment by omargoda** [comment]
Oh, thanks a lot. I will definitely check it Inshallah. Now, I will close this issue as it appears to be duplicated.
