### ISSUE TITLE
[Bug] inconsistent shadow on Recently Saved first tile

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#21174]
### Steps to reproduce

1. Have two recently saved bookmarks
2. Go to the homescreen

### Expected behaviour

The shadow on the first tile isn't cut off

### Actual behaviour

On the left side of the first tile, the shadow looks wrong: 
<img width="333" src="https://user-images.githubusercontent.com/43795363/132390817-8fcb6662-f75c-42c8-9f87-30d6777e81d8.png">

### Device name

Pixel 3

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

93

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on on Firefox 94.0.0-beta.1 and Nightly 2021-10-07, based on the fact that the the recent bookmarks tiles do not have a shadow.
