### ISSUE TITLE
Replace BrowserAwesomeBar (browser-awesomebar) with AwesomeBar composable (compose-awesomebar)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#21172]
A while ago we integrated the `AwesomeBar()` composable into Focus. Now, after https://github.com/mozilla-mobile/android-components/issues/10922, we are ready to integrate it into Fenix too. I would like to land this change at the beginning of the 94 Nightly cycle.

**Comment by pocmo** [comment]
@AaronMT This is still an issue, right? I think there's a way to get the suggestion count. I'll take a look.

**Comment by AaronMT** [comment]
Andi is using a workaround in https://github.com/mozilla-mobile/fenix/pull/21517

**Comment by pocmo** [comment]
@AaronMT In https://github.com/mozilla-mobile/android-components/pull/11050 I am adding a tag to every suggestion (`mozac.awesomebar.suggestion`). With that I am able to find and count the suggestions:

```Kotlin
    fun ComposeTestRule.countSuggestions(): Int {
        val nodes = onAllNodesWithTag("mozac.awesomebar.suggestion")
        val matchedNodes = nodes.fetchSemanticsNodes(
            atLeastOneRootRequired = false
        )
        return matchedNodes.size
    }
```

And can also wait for them to appear:

```Kotlin
    fun ComposeTestRule.waitForSuggestions(timeoutMillis: Long = 1_000) {
        waitUntil(timeoutMillis) {
            countSuggestions() > 0
        }
    }
```

I guess that should work from an idle resource too, if we pass the `ComposeTestRule` to it.

**Comment by pocmo** [comment]
Closing the issue since the integration PR already landed.
