### ISSUE TITLE
Group pages from the same website on the history list, chronologically.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2118]
### Why/User Benefit/User Problem
It list gets shorter, easier and quicker to browser, more organized overall.

### What / Requirements
History has pages from the same website grouped in a drop down menu 

### Acceptance Criteria (how do I know when I’m done?)
History pages are group.

Example:
![Screenshot](https://user-images.githubusercontent.com/32398857/56902989-ca561a80-6a71-11e9-980e-759bb4a7ddbf.jpg)UNITO-UNDERSCORE!20190429-112239!UNITO-UNDERSCORE!Opera beta!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11175)

**Comment by yoasif** [comment]
@Lululalu What browser is that? Or is that a mockup you generated?

**Comment by Lululalu** [comment]
@yoasif it's Opera Mobile.

**Comment by lime124** [comment]
this is going to require a bit of design work to make sure all cases are covered. we'll wait on that until it's prioritized for the team. removing ux label.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812899

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
