### ISSUE TITLE
[Bug]: Not secured connection(icon) is displayed before changing to secured for every website

### ISSUE THREAD

**Issue by varun-70** [mozilla-mobile/fenix#21189]
### Steps to reproduce

1. Go to any link
2. Observe secured/not secured icon
![image](https://user-images.githubusercontent.com/84559910/132492872-ad6c26da-d0cd-4ab1-8f55-b2e4fee0c41a.png)

### Expected behaviour

Secured icon should be displayed for secured websites

### Actual behaviour

It is displaying unsecured and changes to secured (for secured websites)

### Device name

Samsung Galaxy F62

### Android version

Andriod 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

**Comment by kbrosnan** [comment]
Until the certificate is verified the insecure lock is displayed. This is expected behavior.
