### ISSUE TITLE
Lockwise android - enable generation of password

### ISSUE THREAD

**Issue by polrus** [mozilla-mobile/fenix#21186]
### What is the user problem or growth opportunity you want to see solved?
When using Lockwise as a password manager when I need to set up credentials for new app there is no option to generate password. there should be a button for that under the lookup button
### How do you know that this problem exists today? Why is this important?
Generation of strong passwords is important
### Who will benefit from it?
User

**Comment by cadeyrn** [comment]
You can find the issue tracker for Firefox Lockwise here:
https://github.com/mozilla-lockwise/lockwise-android/issues

This issue tracker is for the Firefox browser.
