### ISSUE TITLE
[Bug]: In new tab we cannot swipe to change tab

### ISSUE THREAD

**Issue by varun-70** [mozilla-mobile/fenix#21190]
### Steps to reproduce

1. Open multiple tabs
2. Click on New tab
3. Swipe left on top of URL
4. Observe tab is not changing

https://user-images.githubusercontent.com/84559910/132500560-8cb00482-8e6e-4ef3-9030-3a95bd8d68dc.mp4

### Expected behaviour

Tab should be switched to other tab

### Actual behaviour

Tab is not switching

### Device name

Samsung Galaxy F62

### Android version

Andriod 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

**Comment by kbrosnan** [comment]
Expected behavior. https://github.com/mozilla-mobile/fenix/issues/19839
