### ISSUE TITLE
FNX-5467 ⁃ [Fenix] Call link in search results doesn't launch phone app

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2119]
## Steps to reproduce
Search a business with a phone number in search bar (i.e "Alo Toronto")

### Expected behavior
Tapping on "Call" will launch the phone app to call (or permission to use the phone app)

### Actual behavior
Tapping on "Call" does nothing.

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1918
![](https://user-images.githubusercontent.com/5992746/56905476-43ec0980-6a6e-11e9-889c-0779aeae18d7.png)

**Comment by yoasif** [comment]
Looks like this is a tel: protocol, like tel:+14162602222 

This works in Fennec.

**Comment by ekager** [comment]
We currrently are not handling any external apps see #1570

**Comment by vesta0** [comment]
Will be addressed in #1570
