### ISSUE TITLE
[Bug]: Firefox crashes when a tab opened in grid tab style.

### ISSUE THREAD

**Issue by kyoyacchi** [mozilla-mobile/fenix#21195]
### Steps to reproduce

Have a tab open.
Open the tab list, and wait for the crash.

### Expected behaviour

Should not crash.

### Actual behaviour

Crashing.

### Device name

LG Q6

### Android version

Android 8.1.0

### Firefox release type

Firefox

### Firefox version

92.1.1

### Device logs

6288baca-9b20-4568-a081-34fe2dd816b0
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-94ac7e9a-084f-428f-a6dc-501960210908
----
<native crash>

### Additional information

I didn't tried this on other tab styles. 

Here's a record 

https://user-images.githubusercontent.com/63583961/132571172-36ae0498-8aad-4bca-bac3-2019f6941107.mp4

**Comment by kbrosnan** [comment]
This will be tracked in bz-1731639
