### ISSUE TITLE
FNX-5468 ⁃ [Meta] Firefox Account Setup/Management

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#212]
Allow users to access and share their data from different devices

As a Firefox account user, I want to move my data across different devices so I can revisit and retrieve gathered information/settings later

* User can sign-in and out of their Firefox Account
* User can define what data is being stored and synced

**Comment by st3fan** [comment]
@bbinto I am pretty sure password sync was not part of the MVP and instead delegated to password filling via a third party app like Lockbox. Please clarify.

**Comment by bbinto** [comment]
- History
- Open Tabs

**Comment by bbinto** [comment]
Changing this epic to reflect its actual purpose: Firefox Account Setup/Management
