### ISSUE TITLE
FNX-5469 ⁃ Clarify name

### ISSUE THREAD

**Issue by maverick74** [mozilla-mobile/fenix#2120]
This is not exactly a bug report, but please consider clarifying the browser name as it's being reported in the media (wrongly, i believe) that Mozilla is going to abandon Firefox in Android and replacing it by a different browser called Fenix.

Is the browser going to be called "*Firefox Fenix*" or just "*Fenix*"?

**Comment by kbrosnan** [comment]
Neither. Fenix is a project name.

**Comment by maverick74** [comment]
@kbrosnan thanks for your attention to the question :)

Can you please share if (as of now) Mozilla intents to keep "Firefox" as the final name for the project?

tks

**Comment by cadeyrn** [comment]
> Can you please share if (as of now) Mozilla intents to keep "Firefox" as the final name for the project?

well… it doesn't make much sense to choose "Firefox Preview" as the name if Mozilla doesn't plan to call the product "Firefox" later on. ;-)

**Comment by maverick74** [comment]
Yes, you're right! 
But these days you'll never know... 

just asking to make sure  there wouldn't be any crazy idea :p

thanks
