### ISSUE TITLE
[Bug] After tapping "Undo" for an empty collection deletion, the collection is restored with all the previous tabs 

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#21204]
### Steps to reproduce

1. Open several pages, and create a collection.
2. Go to the homescreen, and expand the collection.
3. Delete one-by-one all the tabs from the collection.
4. From the collection's menu, select to delete the collection.
5. Tap on "Undo" from the "Collection deleted" snackbar.
6. Expand again the restored collection, and observe.

### Expected behaviour

The collection is restored empty. 

### Actual behaviour

The restored collection has all the previous deleted tabs.

* Note: if the user does other actions in the app after step 3 (like opens a menu, opens a tab, switches to the private browsing etc), undo-ing the deletion brings back an empty collection.

https://user-images.githubusercontent.com/40694158/132655983-aedb4858-f7f8-4a0a-b896-af5ab920569b.mp4

### Device name

Lenovo Tab M10

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.1

### Device logs

Reproducible also on Nightly 94.0a1 from 9/9

**Comment by kyoyacchi** [comment]
I don't think it's a bug
