### ISSUE TITLE
[Bug]: The First ETP encounter info pop-up is not displayed

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#21205]
### Steps to reproduce

1. Open a page that contains trackers (i.e. https://edition.cnn.com/)

### Expected behaviour

The first time Firefox block trackers on a website a First ETP encounter info pop-up should be displayed.

### Actual behaviour

The First ETP encounter info pop-up is not displayed when blocking trackers for the first time.

### Device name

Oppo Find X3 Neo

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.1

**Comment by Amejia481** [comment]
👋🏽  @LaurentiuApahideanSV thanks for reporting, this is new expected behavior after merging the shield icon and the security icon, as we are not longer showing the shield icon on the toolbar, we decided to remove the pop-up.
