### ISSUE TITLE
[Bug]: The blue dot is not displayed on the navbar icon when autoplay is disabled

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21208]
### Steps to reproduce

1. Open Firefox and navigate to Settings > Site permissions > Autoplay
2. Select the option to block audio and video
3. Open a website that contains videos (i.e. www.cnn.com)
4. Observe the lock icon on the navbar

### Expected behaviour

A blue dot is displayed on the lock icon in the navbar

### Actual behaviour

There is no blue dot on the lock icon in the navbar

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta. 1 2021-09-08

### Additional information

Might be related to this issue https://github.com/mozilla-mobile/fenix/issues/21206

**Comment by Amejia481** [comment]
👋🏽  Thanks for reporting @mariansima, this is the new expected behavior as the setting on (Settings > Site permissions > Autoplay) is the default global settings, we only show the blue dot when a site has a changed the autoplay setting from the default global settings.

**Comment by Amejia481** [comment]
Now we want to show the blue dot every time a site has a permission or tracking protection different from the default global settings.
