### ISSUE TITLE
[Bug]: A blue dot is displayed when turning off ETP for a website

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#21206]
### Steps to reproduce

1. Open a website which contains vides (i.e. www.netflix.com, www.cnn.com)
2. Tap the lock icon left of the URL bar.
3. Disable Enhanced tracking protection.

### Expected behaviour

Enhanced tracking protection is disabled for the site.

### Actual behaviour

After returning to the website a blue dot is displayed in the lock icon.
The blue dot should be displayed when autoplay is blocked in a site, see issue: https://github.com/mozilla-mobile/fenix/issues/17534

### Device name

Oppo Find X3 Neo

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.1

**Comment by Amejia481** [comment]
👋🏽  Thanks for reporting @mariansima, this is the new expected behavior after merging the shield and the security icon to make users aware that the site has the tracking protection changed from the default value.
