### ISSUE TITLE
[Bug]: The options from the Connection and Tracking Protection menu are not inverted

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#21210]
### Steps to reproduce

1. Go to setting -> Customize;
2. Set the Toolbar to Top;
3. Open any website that contains trackers;
4. Tab the lock icon left of the URL bar.

### Expected behaviour

The options from the Connection and Tracking Protection menu should be inverted when the toolbar is set to top compared to when the toolbar is set to bottom.

### Actual behaviour

The options from the Connection and Tracking Protection menu are not inverted when the toolbar is set to top.

### Device name

Oppo Find X3 Neo

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.1

### Additional information

![inverted](https://user-images.githubusercontent.com/50983519/132685060-fd3889a9-ca0b-49cc-a546-aa943e0ca462.png)

**Comment by Amejia481** [comment]
@LaurentiuApahideanSV thanks for reporting,
I think this is the expected behavior, we never changed order on which items show on the doorhanger menu.
