### ISSUE TITLE
[Bug]: ETP shield icon is displayed on Custom Tabs & PWA toolbar

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#21211]
### Steps to reproduce

1. Open a custom tab or a pwa external link.
2. Check the toolbar options.

### Expected behaviour

ETP shield icon is not displayed on toolbar.

### Actual behaviour

ETP shield icon is displayed. When tapping on the shield no response is received.

### Device name

Huawei MediaPad M2, LG G7 Fit 

### Android version

5.1.1, 8.1

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.1, Nightly

### Additional information

<img src="https://user-images.githubusercontent.com/58466444/132693003-66c32e91-5292-4846-ad60-4b8a6b173588.png" width="300" height="550" />

**Comment by Amejia481** [comment]
This landed on `main` it should be available in the next nightly.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 9/15 with Huawei MediaPad M2 (Android 5.1.1).
