### ISSUE TITLE
[Bug]: privacy.resistFingerprinting breaks touch gestures

### ISSUE THREAD

**Issue by SkewedZeppelin** [mozilla-mobile/fenix#21225]
### Steps to reproduce

1. Ensure `privacy.resistFingerprinting` is true in `about:config`
2. Navigate to openstreetmap.org
3. Try to manipulate the map via panning or pinch-to-zoom

### Expected behaviour

Touch gestures should function properly

### Actual behaviour

Touch gestures do not work

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1

### Additional information

Can reproduce on:
- Firefox Beta 93.0.0-beta.1, with the exception that panning does work
- Firefox Nightly 94.0a1, with the exception that panning does work
- Mull 92.1.1, with the exception that panning does work
- Mull 91.2.0
- Fennec F-Droid 91.2.0
- Tor Browser for Android 10.5.5 (91.2.0)

Cannot reproduce on official 92.1.1 due to lack of about:config.

Other things:
- maybe related: https://bugzilla.mozilla.org/show_bug.cgi?id=1382499
- cannot reproduce on maps.google.com
- double-tap to zoom does work
- you will likely need to restart app via Quit button (NOT force kill) when toggling resistFingerprinting

Other user reports:
- https://forum.f-droid.org/t/welcome-a-new-fennec-f-droid/11113/331
- https://forum.f-droid.org/t/welcome-a-new-fennec-f-droid/11113/332

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17832)

**Comment by SkewedZeppelin** [comment]
I can still reproduce this issue on 98.1.1

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1800567

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
