### ISSUE TITLE
[Bug]: Main menu auto-closes after force stopping

### ISSUE THREAD

**Issue by nvxarm** [mozilla-mobile/fenix#21223]
### Steps to reproduce

1. Force stop Firefox in Android settings
2. Open main menu in Firefox
3. Wait for just a second
4. It closes automatically

### Expected behaviour

It should keep open

### Actual behaviour

It closes automatically

### Device name

ASUS ROG Phone 5s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1 (Build #2015832083)

### Device logs

Not crashing, just annoying

### Additional information

[Main-Menu-Auto-Closes.mp4](https://user-images.githubusercontent.com/16894061/132788247-131fe6f2-b0c3-4e04-a92b-1ec2ba90d169.mp4)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/21148

**Comment by nvxarm** [comment]
> Duplicate #21148

I believe you want to close https://github.com/mozilla-mobile/fenix/issues/21222 instead of the current one

**Comment by nvxarm** [comment]
@kbrosnan shall we reopen this one?
