### ISSUE TITLE
[Bug]: unable to add a rupay card in credit card

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21224]
### Steps to reproduce

Try to add a rupay card 
It says please enter a valid credit card

### Expected behaviour

Should allow the user to add the card

### Actual behaviour

Not allowing to add

### Device name

rog3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17831)

**Comment by jonalmeida** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/RuPay) tells me that it's supported through JCB and Discover, so maybe our credit card validator isn't working?

@sheikh-azharuddin can you successfully add the card on Desktop? If you have sync enabled, does it sync over?

**Comment by sheikh-azharuddin** [comment]
> Thanks, so that sounds like we need to double-check our validator checks.

I just noticed one more issue...this card I added in desktop with card type forcefully selected as discover.
In mobile it is not showing the logo...

![Screenshot_20211020-092514802 (1)](https://user-images.githubusercontent.com/58127841/138026040-913b6570-f650-405a-955d-1630f707795c.jpg)

**Comment by sheikh-azharuddin** [comment]
...

**Comment by sunilk9211** [comment]
hey @sheikh-azharuddin i would like to work on this, can you please assign this to me?

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810768

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
