### ISSUE TITLE
Hide "Customize Home" on site menu

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#21226]
Please hide the "Customize home" menu option in the site menu and only show it as part of the home menu. Thanks! 

cc @Amejia481

**Comment by Amejia481** [comment]
👍🏽

**Comment by Amejia481** [comment]
I put a PR for it https://github.com/mozilla-mobile/fenix/pull/21235, the menu should show only in the home screen in the next nightly version.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (94.0a1 - 2021-09-16T05:07:54.427449).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
