### ISSUE TITLE
Space for menu item on toolbar

### ISSUE THREAD

**Issue by iamkartk** [mozilla-mobile/fenix#21231]
Menu icon with three dots on toolbar have very less space. Its hard to touch it especially from left hand thumb.
Give more space for menu icon. Reduce width of URL address bar.

![Capture](https://user-images.githubusercontent.com/56734031/132845628-c301bcab-7879-437c-b852-0f58a26877a5.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17837)

**Comment by sheikh-azharuddin** [comment]
Personally I would say it is better to separate address bar from the toolbar like Brave/samsung internet browser implementation..most of the time people don't interact with the address bar so it can be placed on top..the bottom toolbar  can be customised by user to add most used items

**Comment by iamkartk** [comment]
you are right. but I dont think mozilla team would do such implementation any time soon, so atleast give more space to menu icon, address bar is taking up all space, which will be just fine with small address bar similar to yandex android browser.

**Comment by cadeyrn** [comment]
> Personally I would say it is better to separate address bar from the toolbar like Brave/samsung internet browser implementation..most of the time people don't interact with the address bar so it can be placed on top

I couldn't disagree more. I wouldn't use the bottom toolbar if I couldn't reach the address bar with one hand any more. It's strange to claim that "most people" wouldn't interact with a address bar - in a browser!

**Comment by weakit** [comment]
> Personally I would say it is better to separate address bar from the toolbar like Brave/samsung internet browser

> the bottom toolbar can be customised by user to add most used items

If we had the page URL displayed on top like other mobile browsers, but have a button on the bottom toolbar which pops up the address to bar to use, that would be very sweet imo.

![image](https://user-images.githubusercontent.com/34541656/132978285-bc5604a3-d561-400a-8793-6a5ac88dfe22.png)
Pardon my poor sketching skills.

Maybe not very intuitive, but certainly very pleasant to use.

**Comment by sheikh-azharuddin** [comment]
> > Personally I would say it is better to separate address bar from the toolbar like Brave/samsung internet browser
> 
> > the bottom toolbar can be customised by user to add most used items
> 
> If we had the page URL displayed on top like other mobile browsers, but have a button on the bottom toolbar which pops up the address to bar to use, that would be very sweet imo.
> 
> ![image](https://user-images.githubusercontent.com/34541656/132978285-bc5604a3-d561-400a-8793-6a5ac88dfe22.png)
> Pardon my poor sketching skills.
> 
> Maybe not very intuitive, but certainly very pleasant to use.

Exactly! You have brought my imagination to life 😅
If search button is added people won't have to click address bar and it can stay on top (samsung browser implementation) 

No doubt those browsers have good user base! People like cad*** are like automation stale bot who is ready destroy any idea or close any case... 

On a side note with more items in the 3 dot menu the list is becoming long defeating the sole purpose of having bottom address bar! This thing they won't understand..wish they use samsung or edge implementation for 3 dot menu which has horizontal menu and easily reachable with finger.
Violasong designed the menu earlier but again the idea was destroyed by mozilla!

Check this implementation as a example which was destroyed 

![Screenshot_20210912-133911361](https://user-images.githubusercontent.com/58127841/132979059-b62f7a63-b7e3-400c-9ce4-482cd351e530.png)

**Comment by weakit** [comment]
Afaik no browser with a bottom toolbar has an "address bar button". Samsung internet has a search button but you have to find and add it manually, and isn't enabled by default.

I would prefer to keep the address bar as is if it stays on the bottom instead of a bigger touch target for the options menu—it's not that hard to hit.

But I feel like having a customisable bottom toolbar like I proposed would he very helpful, especially with commonly used extensions.

**Comment by iamkartk** [comment]
> 
> 
> Afaik no browser with a bottom toolbar has an "address bar button". Samsung internet has a search button but you have to find and add it manually, and isn't enabled by default.
> 
> I would prefer to keep the address bar as is if it stays on the bottom instead of a bigger touch target for the options menu—it's not that hard to hit.
> 
> But I feel like having a customisable bottom toolbar like I proposed would he very helpful, especially with commonly used extensions.

use Opera browser. It has a search button at bottom toolbar, on clicking it, Address bar pops up. 
even firefox ios browser is also better

**Comment by weakit** [comment]
> use Opera browser. It has a search button at bottom toolbar, on clicking it, Address bar pops up.
> even firefox ios browser is also better

I'd like to stick with Firefox

Hope to see a similar design implemented

**Comment by Dunexus** [comment]
> 
> 
> > Personally I would say it is better to separate address bar from the toolbar like Brave/samsung internet browser
> 
> > the bottom toolbar can be customised by user to add most used items
> 
> If we had the page URL displayed on top like other mobile browsers, but have a button on the bottom toolbar which pops up the address to bar to use, that would be very sweet imo.
> 
> ![image](https://user-images.githubusercontent.com/34541656/132978285-bc5604a3-d561-400a-8793-6a5ac88dfe22.png)
> Pardon my poor sketching skills.
> 
> Maybe not very intuitive, but certainly very pleasant to use.

Looking at this sketches, 4 of the 5 buttons are already present in a certain way.
The search button is the equivalent of tapping the url bar, while the tabs button and the 3-dots menu are already present.
The back navigation button behavior is the same as the system back button.
The only addition is forward navigation button (which is one click away, inside 3-dots menu).

This is my very personal opinion but I'm not sure I would trade the vertical space a whole toolbar for so little benefit.

**Comment by weakit** [comment]
> Looking at this sketches, 4 of the 5 buttons are already present in a certain way.
> The search button is the equivalent of tapping the url bar, while the tabs button and the 3-dots menu are already present.
> The back navigation button behavior is the same as the system back button.
> The only addition is forward navigation button (which is one click away, inside 3-dots menu).

Completely agree. But I'd expect the toolbar to be user customisable—maybe have options that are more useful? I use the reload button a lot, and I'd like it if I didn't have to make an extra press.

Extensions as well which sometimes need 2-3 clicks to get to, would be much easier to use. And maybe have more than just 5 buttons depending on the user. 

Makes better use of the space on the bottom and definitely makes it more pleasant to use imo.

**Comment by sheikh-azharuddin** [comment]
Bottom toolback should be customisable like samsung browser

**Comment by iamkartk** [comment]
> 
> 
> Bottom toolback should be customisable like samsung browser

https://github.com/mozilla-mobile/fenix/issues/20967#issue-976870729
I have already suggested to come as optional as is in Vivaldi and yandex browser.
Still they should give proper space to Items in toolbar.
IMO Opera is best browser in android and firefox in android sucks; Its slow, and also very cumbersome to use, just increase the font size and look how bad web pages look.

**Comment by amedyne** [comment]
@topotropic on the 3-dot menu and toolbar

**Comment by sheikh-azharuddin** [comment]
Stale bot🤬

**Comment by sheikh-azharuddin** [comment]
..

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813668

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
