### ISSUE TITLE
Separate tabs with the same search term into a different section

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#21236]
JIRA link: https://mozilla-hub.atlassian.net/browse/FNXV2-17383

**Acceptance Criteria**
- When I open my tabs tray, I see my active search term group(s) originated by the same search term visually separated. 
- If a user already has a group for search term X and proceeds to search for X again and open new tabs from the search results, those tabs will be added to the original group.
- The group only moves to INACTIVE when all the tabs in the group become inactive.
- Order of groups will be based on creation date
- Order of tabs within group will be based on creation date
- User can disable groups in settings

**Comment by bb010g** [comment]
Discussion of the usability of this feature is occurring in <https://github.com/mozilla-mobile/fenix/issues/21360>.
