### ISSUE TITLE
[Bug]: Having a page open via an extension in a private tab adds to browsing history

### ISSUE THREAD

**Issue by weakit** [mozilla-mobile/fenix#21245]
### Steps to reproduce

1. Have the [Search by Image](https://addons.mozilla.org/en-US/firefox/addon/search_by_image/) extension installed and enabled for private browsing.
2. Visit a page with images in a private tab. Search for an Image with the extension.
3. In the newly opened tab, click on any link that takes you to another page.

### Expected behaviour

No browsing history should be recorded after following the above steps.

### Actual behaviour

The page visited in step 3, and sometimes even the image search page is recorded in the browsing history, even though the pages were all accessed in private tabs.

### Device name

Xiaomi Redmi K20 Pro (Mi 9T)

### Android version

Android 11 RKQ1.200826.002

### Firefox release type

Firefox

### Firefox version

91.4.0

### Additional information

This does not occur in Firefox Desktop, and is not a problem with the extension to my knowledge.
Any pages visited by the new tab opened via the extension is recorded in browsing history.
These records persist after closing the tab/browser.

Here is a video reproducing the bug in a fresh install of Firefox.
Note that the screenshots in private browsing are enabled for screen recording purposes and do not interfere with the bug.

https://user-images.githubusercontent.com/34541656/132949727-ca8b620a-cfa0-4648-bff3-1b559746858c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17843)

**Comment by SoftVision-LorandJanos** [comment]
Hi @weakit ! Thanks for the report!
I can reproduce the issue you described.
Tested on the latest Nightly (94.0a1 - 2021-09-17T02:58:52.277509).
Device used: Xiaomi Redmi 11 Lite (Android 11).
