### ISSUE TITLE
Ctrl + F keyboard shortcut (Find in page)

### ISSUE THREAD

**Issue by Scout2022** [mozilla-mobile/fenix#21250]
The Ctrl + F shortcut doesn't work with Firefox on my Chromebook, so I have to tap on the three dots and Find in page. This keyboard shortcut works with Chrome and Vivaldi and is very useful. Please could you update Firefox to include this basic feature?

**Comment by Dunexus** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/3729

**Comment by eUgEntOptIc44** [comment]
Any news on this one?

Also related to #17723, #13946, #18109 and #14713
