### ISSUE TITLE
[Bug]: Malformed content reply crashes Android Firefox 92

### ISSUE THREAD

**Issue by lulol** [mozilla-mobile/fenix#21257]
### Steps to reproduce

A malformed content reply crashes Android Firefox 92.1.1

The following sample script serves a payload that when retrieved crashes the app.
```
#!/bin/bash

PORT=8080

PAYLOAD="\
HTTP/1.1.200 OK\r
Transfer-Encoding: chunked\r
Content-Length: \r
\r
1000\r
RIFFd\xba\x00\x00WAVEfmt"
echo -ne "$PAYLOAD" | tee /dev/stderr | nc -lp $PORT -w 10
```

### Expected behaviour

App not closing when receiving a malformed HTTP reply.

### Actual behaviour

The app closes unexpectedly.

### Android version

Android 6.0, 7.0, 11

### Firefox release type

Firefox

### Firefox version

92.1.1

### Additional information

[Fenix 92.1.1 Crash Report [@ java.lang.NumberFormatException: at java.lang.Long.parseLong(Long.java) ]](https://crash-stats.mozilla.org/report/index/a5a7db5f-1f07-44b5-b8da-e41950210912)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1759519

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
