### ISSUE TITLE
[Bug] проблеми

### ISSUE THREAD

**Issue by tapac02** [mozilla-mobile/fenix#21258]
Проблеми баг, глючит сайт ![Screenshot_20210913-090040](https://user-images.githubusercontent.com/90596231/133034116-b8d9db63-43e3-440c-ab93-771918e16378.png)
![Screenshot_20210913-090029](https://user-images.githubusercontent.com/90596231/133034117-7f91056a-70ff-4712-ba80-3d386720aba7.png)

**Comment by jonalmeida** [comment]
It would be good if we can fix this by using the URL validation from Gecko itself which work the GV team have filed already.
