### ISSUE TITLE
Make homescreen more attractive by adding news snippets

### ISSUE THREAD

**Issue by Hubfront** [mozilla-mobile/fenix#21262]
News on the homescreen make firefox more attractive than just links to the most used sites of the user. The latter are mostly unnecessary, because he/she either reach them using bookmarks or by typing in the first letters of the preferred sites.

Unfortuately, the current homescreen of mobile firefox is the most boring and unattractive ever. Because fenix is not preinstalled like chrome, its not sufficient for the attractiveness/competitiveness of fenix to have a clean homescreen with links to statistically often used sites of the user, that he does not need and that he probably does not use, but it needs to present the user information on it, that is of interest. Why not use the space for daily news again instead of wasting it?

Like it was with fennec and still is with desktop firefox, the homescreen should therefore present a selection of news snippets with pictures and links to the full text of the news sites again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17855)

**Comment by boek** [comment]
Closing this as the home screen has been improved since this was reported. Feel free to open a new issue in bugzilla if you have more suggestions :)
