### ISSUE TITLE
[Bug]: The first 3-dot menu items are cycled through twice using the TalkBack navigation gestures

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21267]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Open a web page and open the 3-dot menu
3. Navigate using the swipe right gesture through the menu
4. Observe the order in which items are selected

### Expected behaviour

Each menu item is cycled through once when selected in order

### Actual behaviour

The first four menu items (back, forward, share, reload/stop) are cycled through twice

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.2 2021-09-13

### Additional information

Also occurs on Firefox Nightly 94.0a1 2021-09-13 and RC 92.1.1 2021-09-04

The same behavior is observed when navigating in the opposite direction
![241845430_179994407571910_405501597582738917_n](https://user-images.githubusercontent.com/89511597/133111996-85c0c611-86d8-4e5b-ada5-1ec07fa8ef12.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17858)

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the latest Beta 105.0b3 with Google Pixel (Android 10).
Swiping through the back, forward, share, and refresh options from the three-dot menu, re-takes the user again to the back option.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809246

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
