### ISSUE TITLE
[Bug]: First time users can not navigate to email input in account creation screen using TalkBack gestures

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21278]
### Steps to reproduce

1. Have a clean install
2. Turn TalkBack (or the available screen reader) on
3. Navigate to the Sign in to sync menu and create a new account
4. Use the swipe gestures to navigate to the email field
5. Observe the audio for the page

### Expected behaviour

The user can follow the audio ques to select the email input field and add details

### Actual behaviour

Following the audio ques does not work for the page and the user has to manually tap on the input field to add details

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.2 2021-09-13

### Additional information

This issue will resolve itself if leaving and returning to the screen. It might also occur if navigating very fast sometimes regardless of navigation history
![241990792_1028104764685094_7921122796710841895_n](https://user-images.githubusercontent.com/89511597/133225533-d274b3c1-ecca-43be-b567-5e8f75344499.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17864)

**Comment by sflorean** [comment]
This issue is still reproducible on Nightly 100.0a1 with Samsung A32 (Android 11).
