### ISSUE TITLE
[Bug]: firefox beta android no update to 93 via play store

### ISSUE THREAD

**Issue by xerxes1511** [mozilla-mobile/fenix#21270]
### Steps to reproduce

open playstore search firefox beta

the last version is 92.0.0 beta 8 but not the 93.0

### Expected behaviour

new beta update for security und stability

### Actual behaviour

no new update where the apk has already been released

### Android version

android 10

### Firefox release type

Firefox Beta

### Firefox version

92.0.0

**Comment by Xi-PP** [comment]
Google takes time to verify the package & other stuffs.. it's normal 🤷🏻

**Comment by xerxes1511** [comment]
yes that's true but as long as the second beta has already been released

**Comment by amedyne** [comment]
Beta 93 should be rolling out today

**Comment by xerxes1511** [comment]
update is already thank you :D
