### ISSUE TITLE
TalkBack mentions activate actions for read only items in ETP settings info panels 

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21281]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Navigate to Settings > Privacy and Security > Enhanced Tracking Protection
3. Tap and open the info panels for either Standard, Strict and Custom settings
4. Navigate and observe voice ques throughout the menu item descriptions (e.g. Social media trackers description in Standard)

### Expected behaviour

Only the selected item description is read out to the user

### Actual behaviour

The user is informed that there is a double tap action to activate the selected item. Double tapping the items does nothing

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.2 2021-09-13

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17866)

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the latest Beta 105.0b3 build with Google Pixel (Android 10).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807558

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
