### ISSUE TITLE
show the trackers blocked count

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21280]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
* Just a feature enhancement*
Currently there is no option to view how many trackers are blocked without going deep...similar to Microsoft edge it can show the count on the first page itself and on clicking details it will show the trackers as usual.

### How do you know that this problem exists today? Why is this important?
Adding this will add confidence and give a quick glance that shield is working and trackers are getting blocked

### Who will benefit from it?
Users

![Screenshot_20210914-143850](https://user-images.githubusercontent.com/58127841/133255654-f24ca7eb-2301-4dc7-bdf2-320d0473b26b.png)

![Screenshot_20210914-173956352 (1)](https://user-images.githubusercontent.com/58127841/133255627-88e5a4e6-c771-4956-8c55-a0d47e82e8a2.png)

**Comment by Amejia481** [comment]
cc: @brampitoyo

**Comment by brampitoyo** [comment]
@Amejia481 @sheikh-azharuddin We will show trackers blocked count on Focus, but there’s currently no plan to do the same on Fenix (or Firefox for iOS).

**Comment by Amejia481** [comment]
I think we can close this for now.
