### ISSUE TITLE
FNX-5473 ⁃ [Meta] Error Pages

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#213]
### Why/User Benefit/User Problem
User understand why the requested website is not shown

### What / Requirements
* Create error pages allowing the user to understand what the issue is

### Acceptance Criteria (how do I know when I’m done?)
* Corresponding error shows correct error page
* Error page only shows on error
* Error page explains why/what the error is

**Comment by st3fan** [comment]
We have an error pages component. It can be seen in the Reference Browser by triggering an error. For example try to visit http://dlejdklejde to see the Address Not Found error page.

It will be good to understand if any customization is needed for these pages. I think they can be styled with CSS.

**Comment by colintheshots** [comment]
This should get prioritized. I was having trouble figuring out why I was getting blank pages, then realized I was trying a new device that did not have my WiFi password.

**Comment by vesta0** [comment]
The work for MVP is completed.
