### ISSUE TITLE
 [Bug]: The "Learn more" button in Studies opens a "Page Not Found" link on support.mozilla.org in a random language

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21304]
### Steps to reproduce

1. Open the 3-dot menu and go to Settings > Data Collection > Studies
2. Tap on the "Learn more" link
3. Observe the opened page

### Expected behaviour

The user is directed to a webpage corresponding to studies

### Actual behaviour

https://support.mozilla.org/1/mobile/93.0.0-beta.2/Android/en-US/how-opt-out-studies-firefox-android This "Page not found" link is opened, and each time a new language is displayed
![241864467_559356785179599_3159299073380342272_n](https://user-images.githubusercontent.com/89511597/133393818-00443478-0401-4796-8f16-ac8cd6715cae.jpg)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.2 2021-09-13

### Additional information

Same behavior is encountered on desktop with the same link

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview 93.0.0-beta.3 and Nightly 2021-09-17.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by kbrosnan** [comment]
This is expected. support.m.o only documents release versions. If after 93 launches this is still a problem discuss it with the sumo team at https://support.mozilla.org/en-US/forums/knowledge-base-articles/
