### ISSUE TITLE
[Bug]: TalkBack reads the sync button in tabs tray as "Add tab" or "Add private tab"

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21308]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Sync an account with some history
3. Open the tabs tray and navigate to Synced tabs
4. Select the Sync button and observe the audio

### Expected behaviour

TalkBack reads out the corresponding "sync" button name and available action

### Actual behaviour

The sync button description is read as "Add tab". If Private tabs was selected before opening Synced tabs, the audio will be read as "Add private tab". Also, if a link from the Synced tabs list was selected beforehand, the description will additionally read as "Add (private) tab - not in list"

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.2 2021-09-13

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 100.0a1 (2022-03-24)  build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
