### ISSUE TITLE
[Bug]: TalkBack mentions actions for items that do not have them in About Firefox page

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21305]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Open the 3-dot menu and go to Settings > About Firefox (beta, nightly, etc.)
3. Tap the build number and build date items
4. Observe the full audio for each

### Expected behaviour

Only the "Double tap to long press" description should be heard after the build number and date are read out loud so that the user is informed that the copy/paste toolbar can be brought up

### Actual behaviour

After the build number and date are read out loud the "Double tap to activate" is heard before "Double tap and hold to long press"

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.2 2021-09-13

### Additional information

The double tap and hold action is mentioned after the double tap

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17882)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 100.0a1 (2022-03-25) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.

**Comment by SoftVision-LorandJanos** [comment]
I managed to reproduce this issue with a Samsung Galaxy Tab S3 (Android 9) device.
Tested on the latest Nightly 100.0a1 (2022-03-28) build.
Reopening the ticket.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Beta 109.0b4 and the latest Nightly 110.0a1 (2022-12-30) builds.
Device used: Google Pixel 4 (Android 13).
After tapping the above mentioned items, Talkback reader first reads the text, then reads: 
"Actions available: use tap with 3 fingers to view" after which the list of actions are corect.
Marking the ticket as verified.
