### ISSUE TITLE
[Bug]: The "Learn more" link in Studies can not be selected using TalkBack gestures

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21303]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Open Settings > Data Collection > Studies 
3. Use the swipe gesture (or tap an item and drag finger to navigate through other items)
4. Observe the highlighted items

### Expected behaviour

The "Learn more" link is selected

### Actual behaviour

The "Learn more" link is skipped
![241864326_157962999759227_3951365603560881608_n](https://user-images.githubusercontent.com/89511597/133386193-2eebcfef-b5df-4614-8155-f3cdfb35d4ba.gif)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.2 2021-09-13

### Additional information

Does not occur on RC since the menu layout is different there.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17880)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview 93.0.0-beta.2 and Nightly 2021-09-16.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 100.0a1 (2022-03-25) build.
Device used: Google Pixel 4 (Android 12).

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the latest Beta 105.0b3 build with Google Pixel (Android 10).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807125

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
