### ISSUE TITLE
[Telemetry] Renew/delete probes for Nov/Dec

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#21313]
Doc for approvals: https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit#

**Comment by lobontiumira** [comment]
Hi @eliserichards 
I've verified that the September-October-November telemetry probes were renewed, and updated the document.
I'll leave this ticket opened for the December verification.
