### ISSUE TITLE
[Bug]: History search in nav bar works intermittently 

### ISSUE THREAD

**Issue by noambonnie** [mozilla-mobile/fenix#21317]
### Steps to reproduce

The issue is intermittent but more frequent than not. Start typing in the navigation bar. Sometimes the history options don't show.

Attached are two screens shots taken within moments of each other. Same search term, different results. 

![Screenshot_20210915-202652_Firefox](https://user-images.githubusercontent.com/1557675/133500049-c77a74d7-2f65-4a9e-975f-e5733c7e1187.jpg)

![Screenshot_20210915-202615_Firefox](https://user-images.githubusercontent.com/1557675/133500041-d530a412-f8d4-4a36-b612-ae732aa6466f.jpg)

### Expected behaviour

History should be shown for selection 

### Actual behaviour

History is not shown

### Device name

Samsung Galaxy S10

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17891)

**Comment by marcel263** [comment]
Also some incidents co-occur with the loss of thumbnails on the home screen.

**Comment by harikrishnan120** [comment]
Yes i have the same issue. I have to restart firefox to fix this

**Comment by Qantas94Heavy** [comment]
Can reproduce intermittently as well. It seems to start happening after the activity is destroyed, then restored from state. Force killing then starting Firefox again seems to solve this issue.

**Comment by Qantas94Heavy** [comment]
Can reproduce intermittently as well. It seems to start happening after the activity is destroyed, then restored from state. Issue does not occur (for a while) after force killing then starting Firefox again.

Interestingly enough I'm also on a Samsung Galaxy S10 running Android 10, not sure if this would have any relevance though.

**Comment by cpeterso** [comment]
> This issue is not reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using the following devices: Samsung Galaxy S22 Ultra (Android 13), Huawei P40 Lite (Android 10).

Thanks for testing. In that case, I'll close this bug.
