### ISSUE TITLE
Inactive tabs changes

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#21319]
https://mozilla-hub.atlassian.net/browse/FNXV2-17822

**Acceptance Criteria**

- I see inactive tabs at the top of the tabs tray
- I can close all inactive tabs at once (and see the UNDO option)
- Tabs move to "inactive" by default after 14 days
- User has an option under Settings to disable/enable inactive tabs

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-10-04.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
