### ISSUE TITLE
Choosing "Close Private Tabs" from notification should not return the user to the New Private Tab page

### ISSUE THREAD

**Issue by msujaws** [mozilla-mobile/fenix#21326]
### Steps to reproduce

1. Open Firefox for Android
2. Open a new private tab to google.com
3. Open the notification tray
4. Click on "Close Private Tabs"

### Expected behaviour

The non-private New Tab page should be shown

This is important because ideally the user doesn't want someone else to know that they were just using private browsing. Returning to the private New Tab page leaks this prior use. 

### Actual behaviour

The private New Tab page is shown. 

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17899)

**Comment by SoftVision-LorandJanos** [comment]
Hi @msujaws ! Thank you for the report!
I can confirm the behavior is as you described.
Verified with the latest Nightly (94.0a1 - 2021-09-16T05:07:54.427449).
Device used: Xiaomi Redmi 11 Lite (Android 11).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807539

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
