### ISSUE TITLE
FNX-5475 ⁃ [Implementaton Review] Bookmarks - Bookmark items don't have favicons

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2132]
Each bookmark item should have a 24x24 favicon within a 40x40 Grey 30 (#E0E0E6) filled circle. 
![](https://user-images.githubusercontent.com/5992746/56917540-bc13f880-6a89-11e9-8187-fdb4829bb600.png)

**Comment by colintheshots** [comment]
We used the browser-icons Android Component. This was supposed to get fixed inside A-C and we'd benefit automatically, but it never happened. I'll check in with the A-C team.
