### ISSUE TITLE
FNX-5476 ⁃ [Implementation Review] History - "Delete History" button is missing the button container

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2133]
Text should be #C50042
![](https://user-images.githubusercontent.com/5992746/56919216-0bf4be80-6a8e-11e9-8cc2-5f826b1ec64f.png)

**Comment by softvision-miralobontiu** [comment]
@AmyYLee this is what "Delete history" button is displayed:

![Screenshot_20190530-114934_Firefox Preview](https://user-images.githubusercontent.com/40694158/58621163-70937b00-82d1-11e9-822f-9d82fea29c4e.jpg)

Tested on the latest build 1.0.1922 (#11500615), with Nexus 6P (Android 8.1.0), Nokia 6 (Android 7.1.1), Samsung Galaxy S8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
Is this expected?
