### ISSUE TITLE
FNX-5477 ⁃ [Bug] On Nightly release build, `adb shell am start` command never returns

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/fenix#2134]
## Steps to reproduce
Install Fenix Nightly release build, connect to PC via USB
send `adb shell am start -W ~~n org.mozilla.fenix/org.mozilla.fenix.IntentReceiverActivity~~ a
android.intent.action.VIEW ~~d 'www.mozilla.org'` to simulate app~~link startup

### Expected behavior
Fenix launches, and the command returns with the timing information on prompt.

### Actual behavior
Fenix launches, but the command never returns 

(It used to work on GreenfieldRelease, and it also still works on Debug, but not on Nightly)

### Device information
* Android device: Moto G5

**Comment by npark-mozilla** [comment]
FYI, This command is used to measure the app-link startup time of Fenix

**Comment by npark-mozilla** [comment]
This is resolved now, closing
