### ISSUE TITLE
[Bug]: Back Button Long Press doesn't Show History List on Nightly 94a Android

### ISSUE THREAD

**Issue by benyaminl** [mozilla-mobile/fenix#21352]
### Steps to reproduce

Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1408645 (Old bug)

suddenly last update #2015834283 - 0b349f48c9 

Not showing history list when long press on back button on Android. tested on different devices result the same behavior

1. Browse to any webpages, more than 3 pages on 1 tab
2. Press hold on back button
3. empty list

### Expected behaviour

1. Show History List

### Actual behaviour

2. Blank history list, not able to see the list

### Device name

XPERIA XZ Premium

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

Tested on other device, Asus Pegasus A5000, Android 5, resulting the same behavior

**Comment by benyaminl** [comment]
https://user-images.githubusercontent.com/2817332/133752295-618c707c-ece5-4cba-a939-23f9e5d6cbe1.mp4

There are also seperate issue that the back list is shown twice on Android 10 Realme 5 Pro.

**Comment by benyaminl** [comment]
Update: seems this is because of fission enabled. I don't know why but my fission flag enabled and disabling it fix the issue. 

The dev need to look into it more seems it's auto enabled. I remember fission hasn't landed on android but why they're fissoon enabled like..

**Comment by SoftVision-LorandJanos** [comment]
Hi @benyaminl ! Thank you for your report!
I cannot reproduce this issue.
I can see browsing history with holding the device back button and with the browser back button as well.
Tested it on the latest Nightly (94.0a1 - 2021-09-17T02:58:52.277509), the latest Beta (93.0.0-beta3) and latest Release (92.1.1).
I had no issue with Fission.
Can you reproduce it with Release or Beta?

Devices used for testing:
- Xiaomi Mi11 Lite (Android 11)
- Google Pixel 4 (Android 11)
- Samsung Galaxy Tab S3 (Android 9)
- Motorola Nexus 6 (Android 7.1.1)

**Comment by benyaminl** [comment]
2021-09-17T06:08:57.094238

tested on multiple devices like you do. Pocophone, Asus, Realme, Sony
Xperia XZ Premium. Behave like what I describe. If fission toggle turned
of, it works fine.




Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by benyaminl** [comment]
ˋˋˋjson
{
  "application": {
    "name": "Firefox Nightly",
    "osVersion": "Linux 28 #1 SMP PREEMPT Thu Jun 13 10:55:52 2019",
    "version": "94.0a1",
    "buildID": "20210916094303",
    "distributionID": "",
    "userAgent": "Mozilla/5.0 (Android 9; Mobile; rv:94.0) Gecko/94.0 Firefox/94.0",
    "safeMode": false,
    "supportURL": "https://support.mozilla.org/1/mobile/94.0a1/Android/en-US/",
    "osTheme": "",
    "numTotalWindows": 0,
    "numFissionWindows": 0,
    "numRemoteWindows": 0,
    "fissionAutoStart": true,
    "fissionDecisionStatus": "enabledByUserPref",
    "remoteAutoStart": true,
    "keyLocationServiceGoogleFound": true,
    "keySafebrowsingGoogleFound": true,
    "keyMozillaFound": true
  },
  "securitySoftware": {
    "registeredAntiVirus": "",
    "registeredAntiSpyware": "",
    "registeredFirewall": ""
  },
  "processes": {
    "remoteTypes": {
      "web": 1
    },
    "maxWebContentProcesses": 2
  },
  "environmentVariables": {},
  "modifiedPreferences": {
    "extensions.lastAppVersion": "94.0a1",
    "fission.autostart": true,
    "idle.lastDailyNotification": 1631853714,
    "media.gmp.storage.version.observed": 1,
    "network.dns.disablePrefetch": true,
    "network.http.speculative-parallel-limit": 0,
    "network.predictor.enabled": false,
    "network.prefetch-next": false,
    "network.trr.blocklist_cleanup_done": true,
    "privacy.purge_trackers.date_in_cookie_database": "0",
    "privacy.purge_trackers.last_purge": "1631853715110",
    "security.remote_settings.crlite_filters.checked": 1631741614,
    "security.remote_settings.intermediates.checked": 1631741614,
    "storage.vacuum.last.index": 0
  },
  "lockedPreferences": {
    "fission.autostart.session": true
  },
  "printingPreferences": {},
  "media": {
    "currentAudioBackend": "opensl",
    "currentMaxAudioChannels": 2,
    "currentPreferredSampleRate": 48000,
    "audioOutputDevices": [
      {
        "name": "Default audio output device",
        "groupId": "",
        "vendor": "",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 44100,
        "minRate": 44100,
        "maxLatency": 441,
        "minLatency": 128
      }
    ],
    "audioInputDevices": [
      {
        "name": "Default audio input device",
        "groupId": "",
        "vendor": "",
        "type": 1,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 16,
        "maxChannels": 1,
        "defaultRate": 44100,
        "maxRate": 44100,
        "minRate": 44100,
        "maxLatency": 441,
        "minLatency": 128
      }
    ]
  },
  "accessibility": {
    "isActive": true,
    "forceDisabled": 0,
    "handlerUsed": false,
    "instantiator": ""
  },
  "startupCache": {
    "DiskCachePath": "/data/user/0/org.mozilla.fenix/files/mozilla/dprhm6a9.default/startupCache/startupCache.8.little",
    "IgnoreDiskCache": false,
    "FoundDiskCacheOnInit": true,
    "WroteToDiskCache": false
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.32",
      "version": "4.32"
    },
    "NSS": {
      "minVersion": "3.70",
      "version": "3.70"
    },
    "NSSUTIL": {
      "minVersion": "3.70",
      "version": "3.70"
    },
    "NSSSSL": {
      "minVersion": "3.70",
      "version": "3.70"
    },
    "NSSSMIME": {
      "minVersion": "3.70",
      "version": "3.70"
    }
  },
  "userJS": {
    "exists": false
  },
  "intl": {
    "localeService": {
      "requested": [
        "en-HK",
        "id-ID"
      ],
      "available": [
        "an",
        "ar",
        "ast",
        "az",
        "be",
        "bg",
        "bn",
        "br",
        "bs",
        "ca",
        "cak",
        "cs",
        "cy",
        "da",
        "de",
        "dsb",
        "el",
        "en-CA",
        "en-GB",
        "en-US",
        "eo",
        "es-AR",
        "es-CL",
        "es-ES",
        "es-MX",
        "et",
        "eu",
        "fa",
        "ff",
        "fi",
        "fr",
        "fy-NL",
        "ga-IE",
        "gd",
        "gl",
        "gn",
        "gu-IN",
        "he",
        "hi-IN",
        "hr",
        "hsb",
        "hu",
        "hy-AM",
        "id",
        "is",
        "it",
        "ja",
        "ka",
        "kab",
        "kk",
        "kn",
        "ko",
        "lij",
        "lo",
        "lt",
        "lv",
        "ml",
        "mr",
        "ms",
        "my",
        "nb-NO",
        "ne-NP",
        "nl",
        "nn-NO",
        "oc",
        "pa-IN",
        "pl",
        "pt-BR",
        "pt-PT",
        "rm",
        "ro",
        "ru",
        "sk",
        "sl",
        "son",
        "sq",
        "sr",
        "sv-SE",
        "ta",
        "te",
        "th",
        "tr",
        "trs",
        "uk",
        "ur",
        "uz",
        "vi",
        "wo",
        "xh",
        "zam",
        "zh-CN",
        "zh-TW"
      ],
      "supported": [
        "en-US",
        "en-CA",
        "en-GB",
        "id"
      ],
      "regionalPrefs": [
        "en-HK",
        "id-ID"
      ],
      "defaultLocale": "en-US"
    },
    "osPrefs": {
      "systemLocales": [
        "en-HK",
        "id-ID"
      ],
      "regionalPrefsLocales": [
        "en-HK",
        "id-ID"
      ]
    }
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "remoteAgent": {
    "listening": false,
    "url": ""
  },
  "graphics": {
    "numTotalWindows": 3,
    "numAcceleratedWindows": 3,
    "windowLayerManagerType": "WebRender",
    "windowLayerManagerRemote": true,
    "windowUsingAdvancedLayers": false,
    "adapterDescription": "Model: G8142, Product: G8142, Manufacturer: Sony, Hardware: qcom, OpenGL: Qualcomm -- Adreno (TM) 540 -- OpenGL ES 3.2 V@331.0 (GIT@7ae04e7, Ia74c9b5270) (Date:09/20/18)",
    "adapterVendorID": "Qualcomm",
    "adapterDeviceID": "Adreno (TM) 540",
    "adapterRAM": 0,
    "adapterDrivers": "",
    "driverVendor": "",
    "driverVersion": "OpenGL ES 3.2 V@331.0 (GIT@7ae04e7, Ia74c9b5270) (Date:09/20/18)",
    "driverDate": "",
    "usesTiling": true,
    "targetFrameRate": 60,
    "webgl1Renderer": "Qualcomm -- Adreno (TM) 540",
    "webgl1Version": "OpenGL ES 3.2 V@331.0 (GIT@7ae04e7, Ia74c9b5270) (Date:09/20/18)",
    "webgl1DriverExtensions": "GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control ",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_float_blend EXT_sRGB EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context",
    "webgl1WSIInfo": "EGL_VENDOR: Android\nEGL_VERSION: 1.4 Android META-EGL\nEGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_lock_surface EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_create_context_no_error EGL_KHR_mutable_render_buffer EGL_EXT_yuv_surface EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context \nIsWebglOutOfProcessEnabled: 0",
    "webgl2Renderer": "Qualcomm -- Adreno (TM) 540",
    "webgl2Version": "OpenGL ES 3.2 V@331.0 (GIT@7ae04e7, Ia74c9b5270) (Date:09/20/18)",
    "webgl2DriverExtensions": "GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control ",
    "webgl2Extensions": "EXT_color_buffer_float EXT_float_blend EXT_texture_filter_anisotropic MOZ_debug OES_texture_float_linear OVR_multiview2 WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context",
    "webgl2WSIInfo": "EGL_VENDOR: Android\nEGL_VERSION: 1.4 Android META-EGL\nEGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_lock_surface EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_create_context_no_error EGL_KHR_mutable_render_buffer EGL_EXT_yuv_surface EGL_EXT_protected_content EGL_IMG_context_priority EGL_KHR_no_config_context \nIsWebglOutOfProcessEnabled: 0",
    "info": {
      "AzureFallbackCanvasBackend": "skia",
      "AzureCanvasBackend": "skia",
      "AzureContentBackend": "skia",
      "ApzTouchInput": 1,
      "ApzAutoscrollInput": 1,
      "ApzZoomingInput": 1,
      "TileHeight": 512,
      "TileWidth": 512,
      "CMSOutputProfile": "Empty profile data",
      "DisplayCount": 1,
      "Display0": "1080x1920"
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "force_enabled",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "force_enabled",
              "message": "Force-enabled by pref"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "force_enabled",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "force_enabled",
              "message": "Force-enabled by pref"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_QUALIFIED",
          "description": "WebRender qualified",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_COMPOSITOR",
          "description": "WebRender native compositor",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        },
        {
          "name": "WEBRENDER_PARTIAL",
          "description": "WebRender partial present",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_SHADER_CACHE",
          "description": "WebRender shader disk cache",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_OPTIMIZED_SHADERS",
          "description": "WebRender optimized shaders",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER_ANGLE",
          "description": "WebRender ANGLE",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "env",
              "status": "unavailable",
              "message": "OS not supported"
            }
          ]
        },
        {
          "name": "WEBRENDER_DCOMP_PRESENT",
          "description": "WebRender DirectComposition",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "user",
              "status": "disabled",
              "message": "User disabled via pref"
            },
            {
              "type": "env",
              "status": "unavailable",
              "message": "Requires Windows 10 or later"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Requires ANGLE"
            }
          ]
        },
        {
          "name": "WEBRENDER_SOFTWARE",
          "description": "WebRender software fallback",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBGPU",
          "description": "WebGPU",
          "status": "disabled",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "addons": [
    {
      "name": "Google Search Fixer",
      "type": "extension",
      "version": "1.6",
      "isActive": true,
      "id": "{58c32ac4-0d6c-4d6f-ae2c-96aaf8ffcb66}"
    },
    {
      "name": "Mozilla Android Components - Ads Telemetry",
      "type": "extension",
      "version": "94.0.20210916214430.0916215550",
      "isActive": true,
      "id": "ads@mozac.org"
    },
    {
      "name": "Mozilla Android Components - Browser Icons",
      "type": "extension",
      "version": "94.0.20210916214430.0916215831",
      "isActive": true,
      "id": "icons@mozac.org"
    },
    {
      "name": "Mozilla Android Components - Firefox Accounts WebChannel",
      "type": "extension",
      "version": "94.0.20210916214430.0916215425",
      "isActive": true,
      "id": "fxa@mozac.org"
    },
    {
      "name": "Mozilla Android Components - ReaderView",
      "type": "extension",
      "version": "94.0.20210916214430.0916220027",
      "isActive": true,
      "id": "readerview@mozac.org"
    },
    {
      "name": "Mozilla Android Components - Search Telemetry",
      "type": "extension",
      "version": "94.0.20210916214430.0916215550",
      "isActive": true,
      "id": "cookies@mozac.org"
    },
    {
      "name": "Mozilla Android Components - Web Compatibility Interventions",
      "type": "extension",
      "version": "26.0.0",
      "isActive": true,
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "Mozilla Android Components - WebCompat Reporter",
      "type": "extension",
      "version": "2.0.1",
      "isActive": true,
      "id": "webcompat-reporter@mozilla.org"
    },
    {
      "name": "SingleFile",
      "type": "extension",
      "version": "1.19.8",
      "isActive": true,
      "id": "{531906d3-e22f-4a6c-a102-8057b88a1a63}"
    },
    {
      "name": "Tampermonkey",
      "type": "extension",
      "version": "4.13.6136",
      "isActive": true,
      "id": "firefox@tampermonkey.net"
    },
    {
      "name": "Translate Web Pages",
      "type": "extension",
      "version": "9.4.2",
      "isActive": true,
      "id": "{036a55b4-5e72-4d05-a06c-cba2dfcc134a}"
    },
    {
      "name": "uBlock Origin",
      "type": "extension",
      "version": "1.37.2",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "Video Background Play Fix",
      "type": "extension",
      "version": "1.6.0",
      "isActive": true,
      "id": "video-bg-play@timdream.org"
    }
  ],
  "features": []
}
ˋˋˋ

**Comment by benyaminl** [comment]
Well on stable it's work as intended, on beta also. It seems really fissoon related bug. Because when I disable fission, it just work on 4 device I mention before.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1731718

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
