### ISSUE TITLE
[Bug]: No crash report notification is triggered after app crash on Xiaomi device

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#21356]
### Steps to reproduce

1. Open a few tabs and go to about:crashparent.
2. Observe the notifications after the crash.

### Expected behaviour

For devices with Android 10 or newer, the crash report sending is displayed as a notification.

### Actual behaviour

The notification is not displayed.

https://user-images.githubusercontent.com/48829350/133782864-491556b8-112a-465c-9572-2f2b841aac3c.mp4

### Device name

Xiaomi Mi11 Lite

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly (94.0a1 - 2021-09-17T02:58:52.277509)

### Additional information

It happens with the latest Release (92.1.1) and Beta (93.0.0-beta3) as well.

Not reproducible on devices with Android 9 or older.

Tested with the following devices where the issue was not reproducible:
- OnePlus Nord (Android 10).
- Google Pixel 4 (Android 11).
- Google Pixel 3 (Android 12).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17921)

**Comment by kbrosnan** [comment]
@SoftVision-LorandJanos would you check the [GVE](https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt) behavior?

**Comment by SoftVision-LorandJanos** [comment]
@kbrosnan sorry for the late response.
Yes it works on that build, the Crash report does appear as notification.

**Comment by csadilek** [comment]
We just had a report that this happened on Galaxy S21 using Nightly. Do we have this device or similar to verify if this is more wide-spread issue?

**Comment by dveditz** [comment]
I'm the report @csadilek just mentioned. Unlike the original reporter, I _did_ get the system notification about the crash, _did_ click on "report", saw the progress bar of it sending, and still have no crashes in my about:crashes page.

**Comment by abodea** [comment]
I was not able to reproduce what @dveditz mentioned above.
I used the latest nightly from **9/28 94.0a1** with **Samsung Galaxy S21 Ultra (Android 11).**
With `about:crashparent` I was able to report the crash and it was displayed in about -> Crashes.
`Socorro`: https://crash-stats.mozilla.org/report/index/bp-e7279075-b9d9-4efb-b90c-1fe260210928

Please, let me know if you want me to try on more devices.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 100.0a1 (2022-03-28) build.
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
I can still reproduce this issue on the latest Beta 108.0b4, using a Google Pixel 4 (Android 13).
