### ISSUE TITLE
[Bug]: pinch to zoom lag

### ISSUE THREAD

**Issue by harikrishnan120** [mozilla-mobile/fenix#21357]
### Steps to reproduce

1. Go to gsmarena.com
2. Switch to desktop view
3.Try zoom in and zoom out (either pinch to zoom or double tap hold and swipe to zoom)

### Expected behaviour

Smooth pinch to zoom animation

### Actual behaviour

Laggy animation and sometimes doesn't zoom out 

### Device name

Samsung Galaxy M51

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 

### Additional information

https://user-images.githubusercontent.com/90913333/133792396-3c518f1e-af77-4150-94bb-411fe23e89dd.mp4

**Comment by mcomella** [comment]
Thanks for filing! We're going to refile on Bugzilla for our platform teams to take a look!

**Comment by mcomella** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1732196

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
