### ISSUE TITLE
[Bug]: "Always start on home" is not applicable when Fenix is set as device assistant. 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#21351]
### Steps to reproduce

1. Go to Settings -Tabs - Start on Home and set to **"Always"**.
2. Open a page and close Fenix.
3. Set the device assistant app to Fenix.
4. Long tap the device home button to trigger the device assistant.

### Expected behaviour

Fenix homescreen is displayed.

### Actual behaviour

Last tab opened is displayed.

### Device name

Pixel 3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

94

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17917)

**Comment by SoftVision-LorandJanos** [comment]
I could reproduce the above described issue using the following devices with different Android versions:
- Xiaomi Mi11 Lite (Android 11)
- Google Pixel 4 (Android 11)
- Samsung Galaxy Tab S3 (Android 9)
- Motorola Nexus 6 (Android 7.1.1)

Firefox version used: Nightly (94.0a1 - 2021-09-17T02:58:52.277509).

**Comment by Matt-17** [comment]
This was a very useful feature on those old versions. Long tap on home, new page, address bar was selected, start typing (or insert from clipboard) without worrying about the open tabs. 
Now I click long, usually need to check if this tab is still needed, click either on new tab or address bar and start typing. Annoying and a bad user experience. Why is this not possible?

**Comment by delia-pop** [comment]
This is still reproducible on 101.0.0-beta.1. Last tab opened is displayed even if the Opening screen is set to "Homepage".

**Comment by Matt-17** [comment]
Oh boy

**Comment by SoftVision-LorandJanos** [comment]
As mentioned in a comment above, for the first step, instead of "Go to Settings -Tabs - Start on Home and set to "Always"", now is "Go to Settings -Homepage - Opening screen and set to "Homepage".
After taking the rest of the steps as well, this issue couldn't be reproduced anymore in the latest Nightly 109.0a1 (2022-12-07) build.
Device used: Google Pixel 4 (Android 13).
Leaving the ticket closed as verified.
