### ISSUE TITLE
[Bug]: The most visited sites icons are selected off screen using TalkBack navigation gestures

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21358]
### Steps to reproduce

1. Have an account with more than 8 most visited sites icons available on the app homepage
2. Turn TalkBack (or the available screen reader) on
2. Navigate through all the icons using the TalkBack swipe gestures
3. Observe the audio and visual ques

### Expected behaviour

The selected icons are brought into focus on the homepage screen.

### Actual behaviour

The icons are selected outside of the screen and the location on screen is read out lout with available actions. The user can double tap to open but can not double tap to long press icons to bring up contextual menus. The icons are brought into view when reaching the last item in the list.

![242226148_188901809996331_4106764792373948558_n](https://user-images.githubusercontent.com/89511597/133800893-f07db3f4-7038-4e5e-ba9c-e3a67cd0e807.gif)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.3 2021-09-16

### Additional information

Also occurs on Nightly 94.0.a1 2021-09-17

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17924)

**Comment by sflorean** [comment]
This issue is still reproducible on Nightly 100.0a1 with Samsung A32 (Android 11).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802974

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
