### ISSUE TITLE
FNX-5478 ⁃ [Implementation review] Library/Settings - Should transition between categories

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2136]
Should transition between categories - Please reference native android transitions for settings
https://cl.ly/a3836d72797d

**Comment by vesta0** [comment]
@mheubusch are we changing anything with library access (to ease access to bookmarks)? Moving this issue to UX backlog until we have confirmed design directions.

**Comment by AmyYLee** [comment]
Closed because because this is moved to the UX Product Quality checklist here https://github.com/mozilla-mobile/fenix/issues/2273
