### ISSUE TITLE
Excessive power use when clicking URL bar (for users with very large clipboard contents?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21363]
https://github.com/mozilla-mobile/fenix/issues/21291 had a long running task (`WebURLFinder.<init>`) to identify URLs in the clipboard contents which I believe occurs when the 1) user has very long clipboard contents and 2) clicks on the url bar or types into the url bar (via the dupe https://github.com/mozilla-mobile/fenix/issues/18142). The fix in that issue to avoid user visible delays was to do it once (cache it), do it before it was needed (prefetch it), & do it on a background thread.

However, this long running task still happens once. In the profile from #21291 https://share.firefox.dev/3kjnX5N this work takes 443ms on a Pixel 5a: that's a long time and **it will consume battery** (as well as heat up the device, potentially causing it to throttle). I don't think all this work is necessary. Here are some solution ideas:
1. Change the algorithm so getting URLs from a string doesn't take so long
1. Only get URLs from strings up to a max size. If the string is larger, we can get URLs from a subset or not at all

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17928)

**Comment by pocmo** [comment]
For Android 12 / API 31 specifically, we will likely not parse the Clipboard ourselves and use the new system API that can give us hints about the clipboard content ("Is it a URL?") without reading the content:
https://github.com/mozilla-mobile/android-components/issues/10761

Like #21291 this will not solve the problem, but will get rid of one more call. :)

**Comment by mcomella** [comment]
Triage: pretty big battery issue but we don't have a firm understanding or prioritization for battery so setting to P3.

**Comment by mcomella** [comment]
Triage: this case is unlikely so we should keep it simple: we should only parse URLs up to a max size.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807333

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
