### ISSUE TITLE
login and password from other apps are not saved

### ISSUE THREAD

**Issue by Rodze** [mozilla-mobile/fenix#21379]
### Steps to reproduce

1. Set Firefox Nightly as autofill app for Android
2. Open another app and login

### Expected behaviour

Firefox should ask to save the login from the other app

### Actual behaviour

Nothing happens

### Device name

Galaxy S20 FE

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17935)

**Comment by eliserichards** [comment]
Hi @Rodze! do you have an example of an app that this is not working on? (e.g. twitter)

**Comment by Rodze** [comment]
> Hi @Rodze! do you have an example of an app that this is not working on? (e.g. twitter)

Instagram for instance.

But, for me at least, Firefox doesn't ask to save logins from any other app. It only offers to autofill logins already saved using the browser 

And the autofill part is currently buggy too, for some apps it only fills the username or password but not both.

**Comment by pocmo** [comment]
This hasn't been implemented in the `feature-autofill` component yet ([backlog](https://github.com/orgs/mozilla-mobile/projects/74)).

**Comment by ghost007** [comment]
i can confirm that neither autofill nor password save is working in 94.1.2. on android 11, with autofill option enabled for firefox.
works in no app. tested in aliexpress and dji go 4

**Comment by RevBaker** [comment]
Can confirm that FF Android 95.1.0 still does not support App passwords for me. Web page logins to the same site work.
When signing in to an app you'll have to supply the UID to get to the password line entry and then the only thing that pops up is a text box containing "Unlock Firefox". That box does nothing. I'm already signed on to Firefox. In research there are multiple mentions of "biometrics" but my setup of FF on any device capable of supporting App Passwords does not use biometrics or password to login to the device (yeah, I know). I've now gotten three letters over the last two months from Mozilla trumpeting the Passwords for apps function and Lockwise demise....neither of which can be confirmed to be true.
Waiting .........

**Comment by boek** [comment]
Closing as a dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1794236
