### ISSUE TITLE
jump back in occupies too much space

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21373]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

The new jump back in design looks awesome but it occupies too much space i.e too much broader pushing other items further below..please use a square box similar to recently saved .this will  occupies a single row both for media and last tab without loosing favicon or details..plus it will match recently saved UI

### How do you know that this problem exists today? Why is this important?
Occupies too much space..pushing items down

### Who will benefit from it?
All users

![Screenshot_20210918-140824943](https://user-images.githubusercontent.com/58127841/133882673-b1b82936-f37d-4471-b6e2-d065700163e7.png)

**Comment by Octoton** [comment]
To add to this, it is strange to me that the jump back icon corner and size are not the same as the pinned site
 
![Screenshot_20210918-123654](https://user-images.githubusercontent.com/56130419/133885943-9ff6af86-f2e1-4535-b897-b94bf8ca53a8.png)
