### ISSUE TITLE
[Bug]: customize home button duplication

### ISSUE THREAD

**Issue by Octoton** [mozilla-mobile/fenix#21374]
### Steps to reproduce

Go to home screen
Go at the bottom, there is a customized button
Click on the menubar, there is another button
![Screenshot_20210918-124647](https://user-images.githubusercontent.com/56130419/133886292-b6cec7ff-bcc1-4f7f-933e-799aaa34c134.png)

### Expected behaviour

Only menubar button is needed as the bottom one isn't even easier to locate (not visible when opening home that have lot of collection or pinned site)

### Actual behaviour

Button duplication

### Device name

pixel 4a

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (Build #2015834667)

**Comment by sheikh-azharuddin** [comment]
You have configured too many things in collection..If someday you need to reinstall the app just remember everything will go!
Collection won't sync to cloud

**Comment by SoftVision-LorandJanos** [comment]
Hi @Octoton! Thank you for your report!
I can confirm that your description is correct.
However as at this moment it is intended this way, it is not considered a bug.
I will change the bug label to a feature request one.

**Comment by Amejia481** [comment]
This the expected behaviour as we want users to have multiple ways to access the setting
