### ISSUE TITLE
option to add tags while saving bookmarks

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21377]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The desktop version offers an option to add tags while saving a new bookmark however in Android version there is no such option.please add the option

### How do you know that this problem exists today? Why is this important?
Searching with tags make life easier

### Who will benefit from it?
All users

![Screenshot_20210918-212623](https://user-images.githubusercontent.com/58127841/133894850-feddbf12-0951-469f-b798-4c1f00c525b4.png)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/5880
