### ISSUE TITLE
Pixelated screenshots on the Play Store

### ISSUE THREAD

**Issue by MrSoke** [mozilla-mobile/fenix#21371]
The screenshots used for Firefox on the Play Store are pixelated, at first I thought it was the image not loading but then I realized all the shapes behind the phone on those images are perfectly sharp. This only affects certain languages, so far, I know spanish and japanese screenshots have this problema, English and Russian don't, I don't know about other languages.

![Captura de pantalla 2021-09-17 211533](https://user-images.githubusercontent.com/30415381/133870975-2fcdca4e-7631-4dee-8624-ca8b001e6788.png)

![Captura de pantalla 2021-09-17 222538](https://user-images.githubusercontent.com/30415381/133870990-53b83644-42cf-47b9-b16c-a6e8229f3a8b.png)

**Comment by hkaancaliskan** [comment]
In Turkish just 1 of the photos are pixelated.

![resim](https://user-images.githubusercontent.com/17825767/133886887-a06f2176-0a1a-499c-a158-8d11b45c805b.png)

Also as a side note: Firefox beta title in play store says "Firefox Beta For Android". Yeah it's in play store and it's clearly for android. Why say "for android" explicitly?

**Comment by kbrosnan** [comment]
I have let the team that manages the Play store content know about this. Closing because the dev team won't be the people fixing this.
