### ISSUE TITLE
Reduce unnecessary method calls by replacing consumeFrom() calls with individual observers

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#21385]
We have multiple fragments that contain code like:

```kotlin
consumeFrom(store) { state ->
    methodA(state)
    methodB(state)
    methodC(state)
    methodD(state)
    methodE(state)
}
```

This means method A - E will get called for every state change. This can get expensive when the state changes often and when calling the individual methods may come with a cost too.

I think one such an example is `SearchDialogFragment`:

https://github.com/mozilla-mobile/fenix/blob/f4397cc85e78f87a49b59a641743024f0543dab9/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt#L344-L359

`SearchFragmentState` contains the typed text and therefore changes quite often while typing into the toolbar. This means we are calling all methods in this block for every typed character. For example `awesomeBarView.update(it)` will create lists of providers to add and remove and then make the necessary changes. All those lists and comparisons are unnecessary for text changes since those do not change the list of awesome bar providers.

https://github.com/mozilla-mobile/fenix/blob/f4397cc85e78f87a49b59a641743024f0543dab9/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt#L218-L228

Instead we can write individual observers that only observe a subset of the state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17937)

**Comment by mcomella** [comment]
Triage: @jonalmeida please take a profile so we can understand the current impact of this code in order to prioritize.

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/fenix/pull/21359

**Comment by mcomella** [comment]
> Triage: @jonalmeida please take a profile so we can understand the current impact of this code in order to prioritize.

Triage: this is happening whether we measure or not so no need to measure. It doesn't seem like something the perf team needs to track so not putting in P1.

**Comment by mcomella** [comment]
Triage: the main impact is likely power use so we'll keep this open.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807334

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
