### ISSUE TITLE
[Bug]: no icon in pinned sites for Facebook.com

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#21393]
### Steps to reproduce

Open Facebook.com and log in
Add the site as pinned site 

### Expected behaviour
A pinned site should be created with Facebook favicon

### Actual behaviour

No favicon us displayed. Only the default F initial. 
Note that a shortcut on the launcher is created with the right icon 

### Device name

Redmi note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17941)

**Comment by SoftVision-LorandJanos** [comment]
Hi @klint ! Thank you for the report!
I could reproduce the issue you described.

Firefox versions tested:

- latest Nightly (94.0a1 - 2021-09-24T05:10:09.860159).
- latest Beta (93.0.0beta4).
- latest Release (92.1.1).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

Screenshot from the latest Nightly build:
![Screenshot_2021-09-24-17-58-05-475_org mozilla fenix](https://user-images.githubusercontent.com/48829350/134696532-fc68b344-92f8-4c8a-9750-a0caef98bcf6.jpg)
:

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 100.0a1 (2022-03-24) build.
Device used: Oppo Reno 6 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 100.0a1 (2022-03-24) build.
Device used: Google Pixel 4 (Android 12).

**Comment by klint** [comment]
This issue is still reproducible on the latest Nightly 109.0a1
Device used: Redmi Note 7
