### ISSUE TITLE
FNX-5481 ⁃ [Implementation review] Find in page – Missing 1dp drop-shadow

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2140]
Missing 1dp drop-shadow. Please reference Quick Action Menu 
![](https://user-images.githubusercontent.com/5992746/56922810-136c9580-6a97-11e9-8c55-2e25fe88e28f.png)

![](https://user-images.githubusercontent.com/5992746/56922772-fe900200-6a96-11e9-86d4-ec659e6f2e8a.png)

**Comment by yoasif** [comment]
Pretty sure Find in page is supposed to *replace* the location bar, so while this may be valid, I'm not sure it is worth "fixing" if it doesn't resolve the core issue.

See https://github.com/mozilla-mobile/fenix/issues/199#issuecomment-475107598

**Comment by sblatz** [comment]
Closing this as it's now tracked in the checklist of #2203.
