### ISSUE TITLE
[Bug]: Tab grouping and "open link in new tab" behave unexpectedly

### ISSUE THREAD

**Issue by WesleyAC** [mozilla-mobile/fenix#21406]
### Steps to reproduce

1. Search for something
2. Open a link from the search results in a new tab
3. Open a link from the page you just opened in a new tab

### Expected behaviour

The third tab should be in the initial tab group

### Actual behaviour

The third tab is opened in the linear tab view

### Device name

Google Pixel 3a

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

**Comment by csadilek** [comment]
Thank you, this will be covered by https://github.com/mozilla-mobile/fenix/issues/21408 and https://github.com/mozilla-mobile/android-components/pull/10997.
