### ISSUE TITLE
[Bug]: Add logins empty username inconsistency

### ISSUE THREAD

**Issue by bendk** [mozilla-mobile/fenix#21402]
### Steps to reproduce

- Open the add login dialog
- Add some text to the username field
- Delete all the text

### Expected behaviour

I think this should be a valid value because:
  - The edit login dialog allows blank username values
  - If I didn't add the text then delete it, then there's no error shown and you can save the login

If this is not valid, then:
 - the save button should be disabled until you add the text
 - Maybe there should be an some text shown initially saying that you need to enter a username, I'm not sure if it should look like an error though
 - Maybe the edit login dialog should be updated to not allow empty usernames

### Actual behaviour

The username field shows an error and the save button is disabled

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

**Comment by bendk** [comment]
I noticed these 3 logins issues while working on the logins API update.  If it would be useful I can make a PR against main with these fixes.

**Comment by SoftVision-LorandJanos** [comment]
Hi @bendk! Thank you for your report.
I can confirm the issue is reproducible as described.

Firefox versions tested:
- Nightly (94.0a1 - 2021-09-22).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).
