### ISSUE TITLE
[Bug]: If a nested scroll area is scrolled to the bottom, scrolling up triggers "pull to refresh"

### ISSUE THREAD

**Issue by nyanpasu64** [mozilla-mobile/fenix#21405]
### Steps to reproduce

- Visit https://tasvideos.mistflux.net/ on Firefox Fenix and close the gray message. If this URL goes down in the future, visit my [archived copy](https://nyanpasu64.github.io/tasvideos.mistflux.net/).
- Ensure you are scrolled to the *very top* of the page.
- Swipe up on any of the scrollable areas to scroll to the *very bottom* of the area. (If you're scrolled partway down, the bug doesn't happen.)
- Swipe down on the draggable areas to drag it down.

### Expected behaviour

The draggable area should move down.

### Actual behaviour

Firefox triggers a "pull to refresh" action.

If you drag sideways then down, the scrollable area scrolls down for a bit, *then* triggers a "pull to refresh". A second drag doesn't trigger the bug because the scroll area is no longer scrolled to the very bottom.

### Device name

Google Pixel 4a

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (Build #2015835243)

### Additional information

Possibly related to #16089.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17947)

**Comment by SoftVision-LorandJanos** [comment]
Hi @nyanpasu64 ! Thank you for the report!
I was unable to reproduce the issue you described.
I've tried it on the following builds:
- latest Nightly (94.0a1 - 2021-09-24T05:10:09.860159).
- latest Beta (93.0.0beta4)
- latest Release (92.1.1).
The pull to refresh wasn't triggered when scrolling back from the bottom.

Could you please make a video so if I didn't do something right, to be able to try again reproducing it? Thank you!

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

**Comment by nyanpasu64** [comment]
https://user-images.githubusercontent.com/913957/134703533-e54a5c79-cf9f-4783-80e3-e9a075a5f303.mp4

Moto G5 plus, unofficial Lineage OS (with built-in screen recorder), Android 11.
Freshly installed Firefox Nightly with no extensions, 94.0a1 (Build #2015835819), 2021-09-24T05:10:09.860159.

**Comment by SoftVision-LorandJanos** [comment]
Hi again! Thank you for the video and the extra information.
I did manage to reproduce it after trying a few more times.

**Comment by nyanpasu64** [comment]
still happens

**Comment by nyanpasu64** [comment]
Still happens. Maybe fix your bugs instead of closing them while they're still occurring.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813208

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
