### ISSUE TITLE
Investigate why conditioned profiles are faster & if users experience that perf

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21419]
In https://github.com/mozilla-mobile/fenix/issues/20936#issuecomment-921082945, we observed using conditioned profiles improves cold page load by ~300-400ms  on a P2. Let's **make sure users get the same advantages, if applicable.**

Possible task break-down:
- Identify why conditioned profiles are faster (first thought: start up cache?)
- Identify if users experience similar performance to the conditioned profiles
  - If not, file a follow-up to make improvements

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17956)

**Comment by mcomella** [comment]
Triage: if users aren't experiencing this, it can be a big win. However, it's pretty likely they are so it's not too urgent: P2.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807335

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
