### ISSUE TITLE
[Bug]: White bar above browser toolbar when scrolling up and down on homescreen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21421]
### Steps to reproduce

1. Scroll up and down on homescreen

### Expected behaviour

No white bar visual artifact above browser toolbar

### Actual behaviour

Just above the browser toolbar, there's a white bar that expands and collapses, sometimes scrolling with the content to do so. Here's the expanded state (notice how it sub-divides the "Save tabs to collection" button):

![image](https://user-images.githubusercontent.com/759372/134256698-a8a6d369-20fa-4f4c-87d5-c7422a35886d.png)

And here's a video demonstrating the scrolling behavior:

https://user-images.githubusercontent.com/759372/134256753-61e005f3-33dc-43c1-8bd9-e1c6011917d1.mp4

### Device name

Moto G5

### Android version

8.1

### Firefox release type

Firefox Nightly

### Firefox version

Sep 20 local build: 368d8cc214d23869063ba7fc5b0864a6bfa9223c

Actually, maybe this was Sep 20 nightly (I was unable to install over it just now with a local build).

**Comment by jonalmeida** [comment]
I can see this bug consistently if scroll down further. Not sure if we should still consider it as perceived perf bug though:

https://user-images.githubusercontent.com/1370580/134427172-90748e27-3dab-4e45-ad1b-e4e7f017afff.mp4

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1356706

**Comment by jonalmeida** [comment]
Closing as a duplicate for https://github.com/mozilla-mobile/fenix/issues/20833.
