### ISSUE TITLE
[Bug]: Jump Back-section disappears and appears while switching to regular window from private window

### ISSUE THREAD

**Issue by mMARUF** [mozilla-mobile/fenix#21429]
### Steps to reproduce

1. Open Firefox Nightly in Android 
2. Switch to the Private Window
3. Again switch to the regular window from the private window 
4. Observe the **JUMP BACK** section while switching back to the regular window 

### Expected behaviour

Jump Back-section should not disappear and appear while switching to regular window from private window

### Actual behaviour

Jump Back-section disappears and appears while switching to regular window from private window

### Device name

Xiomi Redmi Note 7

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

Mozilla/5.0 (Android 10; Mobile; rv:94.0) Gecko/94.0 Firefox/94.0

### Window Size

 (inner width and height): 396 x 756

### Screenshot

![Screenrecorder-2021-09-22-13-26-56-32](https://user-images.githubusercontent.com/45368054/134304131-679e1b77-9020-4d9d-946b-d01a6f934f4b.gif)

**Comment by SoftVision-LorandJanos** [comment]
Hi @mMARUF ! Thank you for the report.
I can reproduce the issue described by you.

Firefox versions tested: latest Nightly (94.0a1 - 2021-09-23T05:07:37.954955).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 100.0a1 (2022-03-23).
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as verified.
