### ISSUE TITLE
Identify why fenix is ~100ms slower than GeckoView Example on cold page load, P2

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21420]
_See also https://github.com/mozilla-mobile/fenix/issues/22026 for a similar issue with Focus_

After https://github.com/mozilla-mobile/fenix/issues/20936#issuecomment-921082945, fenix sits at the high-end of the geckoview_example cold page load results on arewefastyet. e.g. allrecipes:

![image](https://user-images.githubusercontent.com/759372/134256089-eda32935-0167-4df9-99be-c8ef40ec6be5.png)

Let's see if we can **identify the cause of this 100ms difference** and see if we can make fenix faster. My initial guess would be the web extensions framework.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17958)

**Comment by Rob--W** [comment]
> Let's see if we can **identify the cause of this 100ms difference** and see if we can make fenix faster. My initial guess would be the web extensions framework.

What points to the WebExtensions framework?

**Comment by mcomella** [comment]
@Rob--W When (we hypothesize) WebExtensions was temporarily disabled in our cold start up non-page load testing, we saw a 1089ms improvement in time to navigation start on a Moto G5 (note: the 100ms in this issue is on Pixel 2):
![image](https://user-images.githubusercontent.com/759372/134427006-23c3866f-a685-4e12-9bc2-ae554e98b269.png)

To be fair, this was before we were using the start up cache in our testing. However, using a few system WebExtensions is a known difference between GVE and fenix so it seems like a good place to start the investigation.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807336

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
