### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by broccolidood** [mozilla-mobile/fenix#21422]
### Steps to reproduce

1. Have phone be performing slowly at the moment (for example to to many apps being open)
2. Type in a search query whose first few letters are the same of a site that Firefox autocompletes
3. Hit enter before Firefox has time to remove the autocompleted site

### Expected behaviour

The search term I typed in gets searched

### Actual behaviour

The autocompleted site, followed by my search term gets searched. So for example, if I were to type in "You make my dreams come true" very fast, the actual query that gets put in the Google would be:

youtube.com make my dreams come true

Which obviously doesn't give any sensible result

### Device name

Motorola Moto G Pro

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1

**Comment by Dunexus** [comment]
Hello,
Could you retry using the latest [nightly version](https://play.google.com/store/apps/details?id=org.mozilla.fenix) ?
Some fixes from the perf team landed recently, drastically improving search autocompletion speed and stability.

See https://github.com/mozilla-mobile/fenix/issues/20351 for more details about the fixes.

**Comment by ohhai** [comment]
#18096 seems same

**Comment by ohhai** [comment]
@kbrosnan  why closing? Did it get a fix?

**Comment by cadeyrn** [comment]
> Did it get a fix?

Four months ago it was already said that there were fixes. And since the issue opener never responded I would say that it's a fair assumption that this issue is no longer valid. If you still have problems I suggest to open a new issue with details about your device.

**Comment by ohhai** [comment]
Still happens on 96.3.1:  https://github.com/mozilla-mobile/fenix/issues/18096#issuecomment-1032604884
