### ISSUE TITLE
[Bug]: Certain buttons do not work while the keyboard is displayed

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21430]
### Steps to reproduce

Prerequisites: Set the device keyboard mode to floating* and a clean Firefox Nightly install

1. Open Firefox home page
2. Scroll down to "Read our privacy notice" button on the onboarding screen
3. Bring up the keyboard and move it around to see the button
4. Tap the button
5. Alternatively bring up the home screen and tap "Customize home" or "Save tabs to collection" or access the private mode a couple of times to bring up the "Add shortcut" pop-up

### Expected behaviour

The app buttons are functional regardless of the keyboard displayed on the screen or not

### Actual behaviour

The user can tap the buttons but they have no functionality until closing the keyboard

![242619102_1041637213280137_1411696615590916421_n](https://user-images.githubusercontent.com/89511597/134306602-a4fb7ebf-29cc-429d-a9e2-b7196d6c2a27.gif)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-22

### Additional information

The issue also occurs on Firefox 93.0.0-beta.2 2021-09-13 and RC 92.1.1 2021-09-04 (with the difference being that the "Customize home" button is not implemented for these builds yet)

*The default keyboard can be used or from a third party. To reproduce the issue the keyboard can be set to normal mode. In this case the user can not reach the button in onboarding at all and to reach the customize button the top sites need to be removed from the home screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17968)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 2021-09-23.
### Device used:
- Oppo Find X3 (Android 11)
