### ISSUE TITLE
[Bug]: url bar dropdown item wrong layout cutout

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#21448]
### Steps to reproduce

I should be able to see url of dropdown items

### Expected behaviour

cannot see url of drop down items

### Actual behaviour

@today nighlty has a cut out layout for url dropdown items see screnshot in think is better than any words.. until yesterday was fine
screenshot : https://drive.google.com/file/d/19Ztekq-HlOAe4WjMgg0ZUWVzG8vBzKwi/view
can please confirm this abomination? 

### Device name

pixel 4

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

94

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17976)

**Comment by LaurentiuApahideanSV** [comment]
Could you give us further information about your problem, such as the website where you are encountering this issue? The link you provided to for the screenshot does not work.

**Comment by ale82to** [comment]
sorry i deleted the screenshot anyway its a a general ui issue not a website issue.
i ve got this problem on two different phones whit very different andoird version(7 and 11).
since i build fenix myself fenix may i know what i have to edit in layout or style to solve the issue,today build is still no fixed.
![index](https://user-images.githubusercontent.com/3341224/134555845-3af3c38d-2860-484c-af4e-c2e36a06d436.png)

**Comment by ale82to** [comment]
as suggested in reddit the bug happens on two very different phone one with lineage OS 14 and one with latest lineage OS 18.
also may I know exactly what changed in the app since I'm very short sighted I compile myself fenix from github (I mostly edit dimens. xml and some textSize in layout) to get bigger font for the app ui and now I cannot get title and urls as shown in the screenshot to get bigger like I did for the past year.

**Comment by pocmo** [comment]
This is a regression from the new toolbar. I can reproduce and will try to fix it.

**Comment by pocmo** [comment]
This was fixed in the Android Components repository and the fix should end up in the next Nightly build.
