### ISSUE TITLE
The delete history button works even when there is no browsing data

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21443]
### Steps to reproduce

1. Make sure Firefox has no previous browsing data (clean install or delete history)
2. Open the 3-dot menu > History
3. Tap the delete button (trashcan)
4. Select the Delete option from the prompt
5. Observe the snackbar

### Expected behaviour

The button is either hidden or inactive when there is no browsing data to display

### Actual behaviour

The "Browsing data deleted" snackbar is displayed each time the delete button is tapped

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-22

### Additional information

![242662878_2089967871180432_482069448327530717_n](https://user-images.githubusercontent.com/89511597/134362258-31453869-3f15-488a-a935-882a9e2ece1a.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17974)

**Comment by SoftVision-LorandJanos** [comment]
I can confirm that this behavior is as described above.

Firefox versions tested:

- latest Nightly (94.0a1 - 2021-09-23T05:07:37.954955).
- latest Beta (93.0.0beta4)
- On the latest release, deleting history is through a different button that is not displayed after deleting history.

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly build (100.0a1 - 2022-03-21).
Device used: Oppo Reno 6 (Android 11).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814192

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by delia-pop** [comment]
Removing the QA Needed label since the ticket was moved to Bugzilla.
