### ISSUE TITLE
UI test failure - SettingsBasicsTest.changeAccessibiltySettings

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#21441]
### Firebase Test Run:
Failed 2/2:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8278794498371878886/executions/bs.bf0a9fb6eeaeeb2b/testcases/1/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openThreeDotMenu(HomeScreenRobot.kt:173)
at org.mozilla.fenix.ui.SettingsBasicsTest.changeAccessibiltySettings(SettingsBasicsTest.kt:178)`
### Build: 
Main 9/22
Started with this commit https://github.com/mozilla-mobile/fenix/commit/87e4a250f14e264ed15b46065516c8a9d29ee71a

**Comment by AaronMT** [comment]
Looking into this today, intermittently, the 'goBack' to dismiss the awesome bar does not fire so the menu behind it can't be found.
 
```Kotlin
}.dismissSearchBar {
        }.openThreeDotMenu {
```

**Comment by Archaeopteryx** [comment]
@AaronMT We are still observing this [failure](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4942459413816379738/executions/bs.e38b5bb36afc1c1e/test-cases).

**Comment by sv-ohorvath** [comment]
The UIAutomator pressBack() method doesn't seem to be working in dismissSearchBar().
Same as in #21477, #21500, #21499 #21476.

**Comment by AndiAJ** [comment]
Failed 1x on 9/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4942459413816379738/executions/bs.e38b5bb36afc1c1e/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4942459413816379738/executions/bs.d03af1245584978/testcases/1/test-cases)

Flaky 1x on 9/27 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4795093841029907604/executions/bs.98321a0fe451fe0a/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
@AaronMT I'll try to fix it along with the other 4. Unassigning you.

**Comment by AndiAJ** [comment]
Failed 2x on 9/29 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6777693062739191218/executions/bs.235c56a99fb58b1b/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6777693062739191218/executions/bs.14cccc100129492/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6390497636658020768/executions/bs.507e629e7afc5ad5/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6390497636658020768/executions/bs.b5caf25d8b1b5bd/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Fixed in https://github.com/mozilla-mobile/fenix/pull/21598
