### ISSUE TITLE
[Bug]: "Find in page" doesn't work correctly with German Umlaute

### ISSUE THREAD

**Issue by kayschubertwebde** [mozilla-mobile/fenix#21454]
### Steps to reproduce

1. Open a German language website with Umlaute (ö,ä,ü), e. g. that contains the words können and Komponisten
2. Find in page for the string "kö"

### Expected behaviour

Only the match with "können" should be displayed

### Actual behaviour

Both matches "können" and "Komponisten" are displayed

### Device name

Sony Xperia XA2 Plus

### Android version

Android 8

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

Hint: in Firefox 68.11 the find in page was perfect, please implement in the same way also in Fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17980)

**Comment by mariansima** [comment]
Hey @kayschubertwebde Thanks for your submission. I managed to reproduce this issue on Samsung Galaxy A8 (Android 9) on 96.0a1 2021-11-29. This issue also happens for other languages. This issue happens also on Google Chrome (Visible in the first image.

![262119411_1048303719296409_1236989985383593660_n](https://user-images.githubusercontent.com/89511597/143892270-422848f1-0388-433d-ab64-9d314c59acdd.jpg)
![261871613_625537211826912_3928704835642013072_n](https://user-images.githubusercontent.com/89511597/143892278-6ce03e7e-062e-4720-8e9a-5bcee27ec690.jpg)

**Comment by LaviniaL99** [comment]
Hello @kayschubertwebde 

Thanks for your report!

I retested the above flow on the latest Nightly build (100.0a1) and latest RC build (99.1.0) and i was able to reproduce the issue. Also, the issue is reproducing for other languages as well (eg: romanian).

**Device used:**

- Samsung S10E - Android 10

**Comment by fice-t** [comment]
This behaviour matches with Firefox Desktop FWIW.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810589

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
