### ISSUE TITLE
FNX-501 ⁃ [Bug] Talkback reads the first item on a menu twice

### ISSUE THREAD

**Issue by asadotzler** [mozilla-mobile/fenix#2146]
## Steps to reproduce
Swipe to focus the More options button.
Double tap to activate the menu. 

### Expected behavior
The menu should read "Settings, in list of 3 items. Double tap to activate."

### Actual behavior
The menu reads "Settings... Settings, in list of 4 items. Double tap to activate."

The same behavior happens for the Tab menu button which reads "Share tab... Share tab. Double tap to activate."

### Device information
* Android device: Samsung Galaxy S6
* Fenix version: Firefox Preview 1.0.1918 (Build #11181249 68.0a1-20190422094240)

**Comment by asadotzler** [comment]
Others aren't able to reproduce this. Not sure why I can, possibly because of my ancient phone. I have Android Accessibility Suite v 7.3 installed for Talkback support. But I'm on an Android 7.0 device.

**Comment by asadotzler** [comment]
P2 until we can verify this happens on other devices.

**Comment by mcarare** [comment]
@asadotzler is this still an issue?

**Comment by corneliuze** [comment]
If it is @asadotzler , I would love to work on it.

**Comment by eliserichards** [comment]
@corneliuze it would be great if you could verify if this is still valid! If so, feel free to work on it!

**Comment by corneliuze** [comment]
Hi @eliserichards, I think I might need a visual flow because I don't understand the step to reproduce, Thanks

**Comment by asadotzler** [comment]
This no longer reproduces on the latest Fenix with an Android 10 device.

**Comment by corneliuze** [comment]
alright @asadotzler , thanks for the update.
