### ISSUE TITLE
[Bug]: TalkBack reads out wrong numbers of items on the tab tray pop up window

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21469]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Open Firefox and select the tab tray button
3. Double tap and hold to bring up the pop up menu
4. Observe the audio

### Expected behaviour

The number of items in the pop up list is read out

### Actual behaviour

TalkBack reads out "Showing items one to four of four" when the list contains only three items

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-23

### Additional information

Also occurs on 93.0.0-beta.2 2021-09-13. This issue does not occur on RC 92.1.1 2021-09-04 where there is only one menu item in the list.

I tried to upload a video but the audio for the menu does not trigger while recording

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17992)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 100.0a1 (2022-03-24) build.
On activating the tabs tray context menu, the first item is automatically focused and correctly read.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802973

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
