### ISSUE TITLE
Rethink behavior of deleting history

### ISSUE THREAD

**Issue by kayschubertwebde** [mozilla-mobile/fenix#21464]
### Steps to reproduce

1. Have some tabs with a browsing history open
2. Delete history

### Expected behaviour

Only all content under history should be deleted

### Actual behaviour

In addition to all content under history, also the browsing history of all open tabs (what you see, when you long press the back button) gets deleted.

### Device name

Sony Xperia XA2 Plus

### Android version

Android 8

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

In my opinion this behavior is wrong. The browsing history of all open tabs (what you see when you long press the back button) should remain after deleting the history. It's a question of taste and I would like to encourage a discussion about the current behavior.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17988)

**Comment by cadeyrn** [comment]
This doesn't make sense to me. The tab history is clearly part of the history. It would definitively be unexpected to me to leave these history entries when I delete the history and other browsers like Chrome does the same. Therefore it's not only a "question of taste" but could also be considered as a privacy issue to do it differently.

**Comment by SoftVision-LorandJanos** [comment]
Hi @kayschubertwebde ! Thank you for the report.
I believe this is the intended behavior. As mentioned above, I don't think this would make much sense either, but I will add a feature request label, and as this behavior is intended at this moment, it is not considered a bug, so I will remove the bug label.

Firefox versions tested:

- latest Nightly (94.0a1 - 2021-09-23T05:07:37.954955).
- latest Beta (93.0.0beta4).
- latest RC (92.1.1).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Mi11 Lite (Android 11).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813092

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
