### ISSUE TITLE
[Bug]: TalkBack audio for the password field in Firefox Sync reads out an error

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21468]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Open Firefox > 3-dot menu > Sign in to sync
3. Use a valid email and proceed to the password field
4. Select the password field and observe the audio

### Expected behaviour

TalkBack reads out the corresponding password input field name and available action

### Actual behaviour

The audio for the password field is "editing - enter password - edit box - error - null - password required - double tap to enter text"

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-22

### Additional information

Also occurs on 93.0.0-beta.2 2021-09-13 and RC 92.1.1 2021-09-04

https://user-images.githubusercontent.com/89511597/134481328-91b0006a-f565-4f7f-bef9-d5843629ccf8.mp4

**Comment by kbrosnan** [comment]
@mariansima Is this true for other websites logins password fields?

**Comment by mariansima** [comment]
@kbrosnan no, other websites read out "password" twice sometimes (because talkback also reads the text inside the field). I just opened https://accounts.firefox.com/signin in a normal tab and the same thing happens. If I open the address on Chrome browser the talkback readout is "enter password - edit box - pasword - double tap to enter text"

**Comment by mhammond** [comment]
I believe the form you are talking about is hosted on accounts.firefox.com, so not strictly part of Fenix. It would be interesting to know whether you can reproduce something similar when signing in to sync on a desktop firefox, but I believe we probably want a bug open on bugzilla in [this component](https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Server%3A%20Firefox%20Accounts)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 102.0a1 (2022-05-18T17:12:12.001240).
Device used: Samsung Galaxy Tab S3 (Android 9).

**Comment by mhammond** [comment]
As I wrote about 6 months ago:

> I believe the form you are talking about is hosted on accounts.firefox.com, so not strictly part of Fenix. It would be interesting to know whether you can reproduce something similar when signing in to sync on a desktop firefox, but I believe we probably want a bug open on bugzilla in [this component](https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Server%3A%20Firefox%20Accounts)

So I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1770097

**Comment by LZoog** [comment]
This is going to be tracked in https://github.com/mozilla/fxa/issues/12977. Thanks!
