### ISSUE TITLE
Search engine items can be accessed with TalkBack in the Scan screen

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21473]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Bring up the keyboard from the address bar
3. Select the Scan button and double tap
4. Navigate the Scan screen using swipe gestures

### Expected behaviour

The user has control over the Scan screen

### Actual behaviour

The user can navigate through menus behind the Scan screen (and can even navigate through search engines, open voice search, etc.)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-23

### Additional information

Also occurs on 93.0.0-beta.2 2021-09-13 and RC 92.1.1 2021-09-04

https://user-images.githubusercontent.com/89511597/134512075-98dc66e6-9fea-462f-b503-26f293dbaf1a.mp4

Camera is dark because the device is facing the desk

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17995)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 100.0a1 (2022-03-24) build.
Device used: Oppo Reno 6 (Android 11).

**Comment by amocirean** [comment]
This issue is still reproducible on the latest Nightly 109.0a1 (2022-11-24) build.
Device used: Xiaomi Pad5 (Android 12)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807383

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
