### ISSUE TITLE
[Bug]: "Open links from clipboard" widget got covered up by "choose search engine" widget which is automatically displayed

### ISSUE THREAD

**Issue by NewtMa** [mozilla-mobile/fenix#21479]
### Steps to reproduce

1. copy a website link;
2. open Firefox;
3. you could see that "Open links from clipboard" widget flashes, and got covered by "choose search engine" widget almost instantly;
4. when you close the "choose search engine" widget, you could see the "Open links from clipboard" widget.

### Expected behaviour

the "Open links from clipboard" widget is on the top of the display stacks(sorry I'm not familiar with the jargon), which is the same behavior offered by the last Firefox version.

### Actual behaviour

The  "choose search engine" widget is on the top of the display stacks, this happens after I updated Firefox to 92.1.1.

### Device name

Redmi Note 7

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

92.1.1

### Additional information

https://user-images.githubusercontent.com/48610536/134527403-71c34cf8-4f55-4ca3-8f66-92f78cdddff0.mp4

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce your issue on Firefox Preview RC 92.1.1 and Nightly 2021-09-28 but was unable too. Is there further information that you can provide that may help us reproduce the issue?
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by NewtMa** [comment]
Hi @LaurentiuApahideanSV , thanks for your reply. Maybe they fixed this in the latest version. This isn't an serious issue. 

It's high time I changed my phone anyway. I'll close this issue.
