### ISSUE TITLE
[Bug]: First item in tab tray header has a contradicting description in TalkBack

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21481]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on
2. Bring up the tab tray
3. Select the first item in the tab tray header
4. Navigate forward and backward using swipe gestures
5. Observe the audio description

### Expected behaviour

The description of the item is consistent while using talkback navigation gesture to select it

### Actual behaviour

Selecting from the left describes the object as the "first item" and selecting from the right describes it as "not in grid"

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-23

### Additional information

https://user-images.githubusercontent.com/89511597/134531694-6115b19b-c684-4582-8659-e8efa25fe87e.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18004)

**Comment by mcarare** [comment]
@mariansima Can you confirm if you are using Talkback or the Samsung screen reader?
Also, if you are using Talkback can you please mention the version listed in settings (should probably be the last item in list)?
Thank you!
