### ISSUE TITLE
[Bug]: When dark theme/ private mode is enabled the icons for bookmarks folders & downloads are not visible

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#21483]
### Steps to reproduce

1. Have dark theme enabled./ or go to private mode.
2. Add 2-3 bookmark folders./ Download some files.
3. Open Menu - > Bookmarks./ Menu - Downloads.

### Expected behaviour

The folder icons are visible.

### Actual behaviour

The icons are not visible with dark theme enabled (they are purple but the contrast is minimal).

### Device name

Samsung A8, Pixel 3

### Android version

Android 8, 12

### Firefox release type

Firefox Nightly

### Firefox version

94

### Device logs

![Screenshot_9](https://user-images.githubusercontent.com/58466444/134533889-ae6b5572-83dc-4597-864f-3244dc2171fd.png)

### Additional information
- Not reproducible on Nightly 9/22 and Beta 93.0.0-beta.4

**Comment by mariansima** [comment]
The issue can be also observed in private mode on Firefox Nightly 94.0a1 2021-09-2

<img width="346" alt="Screenshot 2021-09-24 at 16 37 30" src="https://user-images.githubusercontent.com/89511597/134683675-21a4b8a7-a3b1-4508-8683-42c310bcd9ed.png">
4

**Comment by Rishavgupta12345** [comment]
i can see all the icons properly in my device

**Comment by SoftVision-LorandJanos** [comment]
Reproducible on 95.0.0 beta.1, using a Samsung Galaxy Tab S3 (Android 9) and a Xiaomi Mi11 Lite (Android 11).

**Comment by M-itch** [comment]
When you select one of the folders in the dark theme then the icon is visible. The icon is same color as the background.
Also, the Download item icon in Downloads is the same as the light theme.

Version: 94.1.1

**Comment by SoftVision-LorandJanos** [comment]
Reproducible on 95.0.0 beta.3, using a Samsung Galaxy Tab S3 (Android 9) and a Xiaomi Mi11 Lite (Android 11).
![Screenshot_2021-11-12-08-21-53-267_org mozilla firefox_beta](https://user-images.githubusercontent.com/48829350/141420182-a813c1a1-ac1f-49b7-a542-c5b62330f1cf.jpg)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly (2021-12-29).
Tested on: Xiaomi Mi11 Lite (Android 11).
Still reproducible on the latest Beta (96.0.0-beta5) and latest Release (95.2.0).
