### ISSUE TITLE
Zooming & scrolling some pages, displays the pages' toolbar dynamic

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#21498]
### Steps to reproduce

1. Go to Settings - Accessibility, and enable "Zoom on all websites".
2. Open twitter.com, or instagram.com, zoom out/in the pages and scroll.

### Expected behaviour

The pages have no visual glitches, can be scrolled smoothly.

### Actual behaviour

The twitter.com or instagram.com toolbars become dynamic - please see the videos below.

https://user-images.githubusercontent.com/40694158/134646695-6e5a532b-3d72-4079-acbf-89e887b309db.mp4

https://user-images.githubusercontent.com/40694158/134646709-5f7359ff-584c-4e4d-9f59-5ff99ffd5f72.mp4

### Device name

OnePlus 5T

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

* Reproducible also on Beta 93.0.0-beta.4, and RC 92.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18015)

**Comment by delia-pop** [comment]
Reproducible on Firefox 95.2.0 (Build 2015851755) RC build with LG G7 fit (Android 8.1.0) on instagam.com.

**Comment by amocirean** [comment]
Reproducible on Firefox 102.0.0-beta.1 (Build 2015883547) with Huawei P40 Lite (Android 10) on twitter.com.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813855

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
