### ISSUE TITLE
[Bug]: Sometimes, a double tap is needed to open the tabs tray

### ISSUE THREAD

**Issue by DiegoARL38** [mozilla-mobile/fenix#21491]
### Steps to reproduce

1. Open Firefox.
2. Navigate to any URL.
3. Tap the tab counter to open the tabs tray.
4. Open a new tab and navigate to another URL.
5. Share the page with any application via the 3-dot menu.
6. Go back to Firefox.
7. Try opening the tabs tray, either via the tabs counter, or the See all button in the homepage's Jump back section, both produce the same behaviour.
8. Notice how the tabs tray doesn't open.
9. Try to open the tabs tray again.
10. Notice how the tabs tray opens finally.

### Expected behaviour

The tabs tray always opens when needed with only one attempt.

### Actual behaviour

There are occasions when the tabs tray requires two attempts to access it. This is quite frustrating when using a screen reader, since the focus jumps unexpectedly when the first attempt fails.

### Device name

Xiaomi Redmi Note 8

### Android version

MIUI 12.0.4.0, Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (Build #2015835723) from 2021-09-23T17:08:56.236491

### Additional information

* I've got TalkBack enabled. I don't know if this affects things.
* This is the only way I've found to reproduce the bug consistently. Don't know if there's others.
* TalkBack version 9.1.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18012)

**Comment by marcel263** [comment]
Switching to another app triggers the issue

**Comment by DiegoARL38** [comment]
In my case, it appears that just opening and closing the Sharing screen is enough to reproduce the issue.

**Comment by marcel263** [comment]
> In my case, it appears that just opening and closing the Sharing screen is enough to reproduce the issue.

I can confirm this on a Samsung phone running Android 11

**Comment by jonalmeida** [comment]
> In my case, it appears that just opening and closing the Sharing screen is enough to reproduce the issue.

Thanks, this is helpful. I don't think it's limited to being just an a11y bug from the looks of it.

**Comment by ohhai** [comment]
#20576 is same

**Comment by sivaraam** [comment]
I get bitten by this so often (via the steps mentioned in #20576). It would really be nice to see this get fixed.

For the note, I was thinking it was being caused because the "Tab sent" notification was somehow disabling interaction with elements near it but that wasn't the case. The issue appears to be happening even if I have the address bar at the top (the "Tab sent notification is always shown at the bottom).

**Comment by SlyJackHammer** [comment]
> > In my case, it appears that just opening and closing the Sharing screen is enough to reproduce the issue.
> 
> Thanks, this is helpful. I don't think it's limited to being just an a11y bug from the looks of it.

My experience is the same as @DiegoARL38, and on multiple versions of Firefox and Android. This has been an issue for quite a long time, and I hope this is addressed soon– it makes for a very inconsistent and error-prone UX.

Xiaomi Redmi Note 8
Firefox 98.3.0 (Build #2015870331)
Android 10, MIUI global 12.0.6

Huawei Tablet
Firefox 98.2.0 (Build #2015868579)
Android 7.0

**Comment by DiegoARL38** [comment]
This issue has been fixed. Closing.

**Comment by sivaraam** [comment]
> This issue has been fixed. Closing.

I'm able to reproduce the issue in v107.1.0. In which version is this fixed ? The nightly ?

**Comment by DiegoARL38** [comment]
> I'm able to reproduce the issue in v107.1.0. In which version is this fixed ? The nightly ?

Yes, I'm using Firefox Nightly 109.0a1 from 2022-11-27T05:16:40.335435.
