### ISSUE TITLE
Show onboarding dialog for home sections

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#21493]
Related ticket https://mozilla-hub.atlassian.net/browse/FNXV2-17820

**Comment by Amejia481** [comment]
QA team help us to verify that after one of this sections is visible Jump back in, Recently saved, Recent explorations and Pocket a on boarding dialog is displayed.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-10-04.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by Amejia481** [comment]
Thanks @LaurentiuApahideanSV :)
