### ISSUE TITLE
FNX-5484 ⁃ [Meta] Search Widget

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#215]
As a user, I want to be able to quickly launch search in Fenix from my device homescreen, so I can save time.

### Acceptance Criteria (how do I know when I’m done?)
-I can add a search widget to my homescreen.
-I can initiate a quick search from my home screen.
-I can search with my default search provider.

**Comment by vesta0** [comment]
See here for more comments: #201

**Comment by jonichan** [comment]
We've written a SUMO article on how to add a search widget: https://support.mozilla.org/en-US/kb/how-add-firefox-preview-search-widget-your-home-screen

**Comment by vesta0** [comment]
Thank you for the article @jonichan  :) It's great but can we change the screencap to one that includes the widget in at least 2 different sizes, not have the Google search bar in there, and possibly better resolution? I can send you a sample if that helps!

**Comment by sblatz** [comment]
This is done, and the individual tickets were already QA'd. 😄

**Comment by andreicristianpetcu** [comment]
I started using this feature when it landed and IT IS AWESOME!!!!

**Comment by jonichan** [comment]
> Thank you for the article @jonichan :) The article is great. Can we change the screencap to one that includes the widget in at least 2 different sizes, not have the Google search bar in there, and possibly better resolution? I can send you a sample if that helps!

Sure thing, I've updated the article: https://support.mozilla.org/en-US/kb/how-add-firefox-preview-search-widget-your-home-screen
