### ISSUE TITLE
[Bug]: Firefox reload page when upload photo

### ISSUE THREAD

**Issue by And96** [mozilla-mobile/fenix#21509]
### Steps to reproduce

Firefox reload current page after camera has been closed.
It's unpossible to take a phone. It happens on every page. 

Step
1. Press button
2. Take a photo
3. Confirm and close the camera
4. Firefox instead of get the photo, reload the entire page.

Simple example of code
`<input type="file" accept="image/*">`

Tested on LAN, webpage, both HTTP and HTTPS
Tested on both Firefox stable and beta.
Tested on Android 11 (6 GB Ram, high-end device)
No problem on Chrome.

### Expected behaviour

Firefox must get the photo

### Actual behaviour

Firefox reload the entire page.

### Device name

Xiaomi Mi9

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1

**Comment by SoftVision-LorandJanos** [comment]
Hi @And96 ! Thank you for the report.
I've tried uploading some photos and videos, using the camera, and I had no issue, the photo/video was successfully uploaded.
Could you provide with some examples for me to try reproducing where you have the issue? Or maybe see if it reproduces on the latest Nightly on your side. Thank you!

Tested on the latest Release (92.1.1).

Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by And96** [comment]
It was a ram available problem.
Rebooting my device solved the problem. 

Issue closed
