### ISSUE TITLE
[Bug]: Writing in the address bar crashes Firefox

### ISSUE THREAD

**Issue by DiegoARL38** [mozilla-mobile/fenix#21503]
### Steps to reproduce

1. Open Firefox.
2. Tap the address bar and start typing.

### Expected behaviour

Search suggestions are displayed and the app runs normally

### Actual behaviour

Firefox crashes.

### Device name

Xiaomi Redmi Note 8

### Android version

MIUI 12.0.4.0, Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (Build #2015835723) from 2021-09-23T17:08:56.236491

### Additional information

This also applies to the latest Nightly; 94.0a1 (Build #2015835915) from 2021-09-24T17:07:58.548822. I used yesterday's build because of the crash link.

**Comment by DiegoARL38** [comment]
Socorro link: https://crash-stats.mozilla.org/report/index/669eff09-0490-4498-a83f-221fc0210924

**Comment by DiegoARL38** [comment]
Finally got to submit today's crash. It's got a different description, but it's got the same steps to reproduce.
https://crash-stats.mozilla.org/report/index/e98cdb7a-b869-4e84-9b0d-1fae30210924

**Comment by rs-mkaiser** [comment]
Same here. Also any viewing of the tab selection screen will trigger it for me. This causes it to crash constantly for me.

**Comment by csadilek** [comment]
Last links shows the same cause as https://github.com/mozilla-mobile/fenix/issues/21506 which should be fixed in latest Nightly. Please re-open if this is still happening.

Nightly with fix:
94.0a1 (Build #2015836299)
AC: 94.0.20210926133629, cafbf98276

**Comment by rs-mkaiser** [comment]
Verified fix, great work, thanks!

**Comment by DiegoARL38** [comment]
Same on my case, thanks!
