### ISSUE TITLE
[Bug]: The "Learn more" link in "Allow search suggestions in private sessions?" pop up redirects to a deprecated page

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21502]
### Steps to reproduce

Preconditions: Open the 3-dot menu and go to Settings > Search. Scroll down to Show in private sessions checkbox and make sure it is unchecked

1. Open a new private tab
2. Bring up the keyboard and type in the search bar
3. Tap on the "Learn more" link 
4. Observe the opened web page

### Expected behaviour

A relevant up to date webpage is displayed

### Actual behaviour

The link redirects the user to the following webpage: 

https://support.mozilla.org/en-US/kb/how-search-firefox-android-beta?redirectslug=how-search-firefox-preview&redirectlocale=en-US&fbclid=IwAR21DZaDly5eEarJenHkUBcD-uf1Bw61KfsOHCUmFzSgTDSaajZHBS7uNJA 

The site is presented as follows:

<img width="928" alt="Screenshot 2021-09-24 at 16 50 17" src="https://user-images.githubusercontent.com/89511597/134685620-44cec928-efdc-450c-b213-4bb59f969898.png">

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

94.0.a1 2021-09-24

### Additional information

Also occurs on 93.0.0-beta.2 2021-09-13 and RC 92.1.1 2021-09-04

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18018)

**Comment by LaviniaL99** [comment]
The issue was verified on the latest Nightly build-> 98.0a1  and i was able to reproduce it.

**Devices used:**
- Samsung S10E -> Android 10
