### ISSUE TITLE
[Bug]: NullPointerException: getQueryParameter call at mozilla.components.feature.search.ext.SearchEngineKt, parseSearchTerms, SearchEngine.kt:9 if the search key in the search engine appears twice

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla-mobile/fenix#21508]
### Steps to reproduce

1. Add a custom search engine whose URL is `https://searchfox.org/mozilla-central/search?q=abc&q=%s&path=&case=false&regexp=false`
2. Search `EditorBase` with it in the URL bar
3. Tap a link in it to see a file

### Expected behaviour

No crash.

### Actual behaviour

Crashed.

### Device name

Galaxy Tab S5e

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (Build #2015836107)

### Device logs

https://crash-stats.mozilla.org/report/index/49e1d11c-6775-48cb-b20e-cacb90210926

**Comment by masayuki-nakano** [comment]
At here, `this.searchParameterName` is `null`:
https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/feature/search/src/main/java/mozilla/components/feature/search/ext/SearchEngine.kt#L111

**Comment by masayuki-nakano** [comment]
Okay, I got what's going on.

I copied the URL from a search result of the advanced search when I added it to search engines. At this time, there are 2 `name=` param in the query, and I rewrite only the later one's value with `%s`. It seems that having two same key causes that it can be `null` because if I remove the former key and value, I cannot reproduce this crash.

**Comment by masayuki-nakano** [comment]
Updated the STR to reproduce this crash with Searchfox.

**Comment by AndiAJ** [comment]
Verified as fixed on Firefox 93.2.0 using the following devices:
• Google Pixel 3a (Android 11)
• Samsung Galaxy Tab S3 (Android 9)
• OnePlus A3 (Android 6.0.1)
