### ISSUE TITLE
[Bug] Fenix Custom Tab support for start and exit animations

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2151]
This is probably something to do with start and exit animations not being implemented properly in Fenix: https://developer.chrome.com/multidevice/android/customtabs#configure-custom%20enter%20and%20exit%20animations

See also video:

* Fenix: https://i.imgur.com/fOOLrdI.mp4
* Fennec: https://i.imgur.com/EUU694A.mp4

## Steps to reproduce
* Fenix as default browser
* Load Gmail app
* Open a link
* Notice app transition

### Expected behavior
* Gmail app slides to the left and Fenix appears

### Actual behavior
* Fenix just appears on top (with a black flash, separate bug)

### Device information
* Android device: Samsung S10e
* Fenix version: latest from playstore

**Comment by lime124** [comment]
@boek @sblatz is this related to the start up issue #599? do we have animations already from amy or is this something  new she needs to provide? the answer will dictate the next step for this issue. removing ux label.

**Comment by sblatz** [comment]
Do we want a different animation than what we have now? :)

**Comment by sblatz** [comment]
Here's our current animation: 
![demo of custom 2020-05-05 13_51_03](https://user-images.githubusercontent.com/4400286/81114744-79c09b00-8ed7-11ea-9f21-c0a482b56849.gif)

**Comment by xcffl** [comment]
> Do we want a different animation than what we have now? :)

According to Chrome's doc, app developers are allowed to customize the enter and exit animation to make it look more native: https://developer.chrome.com/multidevice/android/customtabs

**Comment by Mugurell** [comment]
Asking UX if we need a custom animation for custom tabs and what should that be.
Saw no animations in https://github.com/mozilla-mobile/fenix/issues/599.

To get the animations shown in [the issue description](https://github.com/mozilla-mobile/fenix/issues/2151#issue-438559565) Fennec uses [simple slide right/left animations](https://searchfox.org/mozilla-esr68/rev/36da62fa7c4a3d41e5e6180aa734541ea036a021/mobile/android/base/java/org/mozilla/gecko/webapps/WebAppActivity.java#381-382)
Should we use the same?

**Comment by agi90** [comment]
On the engineering side, I would definitely recommend supporting custom animations. I can definitely see this as something that could make some app developers decide to hard code Chrome's app id to their custom tabs (which would make the app always open Chrome instead of the default browser) which would be pretty bad.

**Comment by AmyYLee** [comment]
> Here's our current animation:
> ![demo of custom 2020-05-05 13_51_03](https://user-images.githubusercontent.com/4400286/81114744-79c09b00-8ed7-11ea-9f21-c0a482b56849.gif)

Hi @sblatz - I don't see this animation when Fenix is set as default and I open links via email, slack, etc. It doesn't seem to be any animation and just appears. I'd be okay with the current animation you have.

**Comment by xcffl** [comment]
It's  not fixed yet. Transition between activities is actually well documented by material design: https://material.io/develop/android/theming/motion
