### ISSUE TITLE
Jump back in should provide a way to close the tab in addition to opening it

### ISSUE THREAD

**Issue by bjherbison** [mozilla-mobile/fenix#21513]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Many times when I am presented with "Jump back in" I am no longer interested in viewing the tab--I just want to close it.

There could be an "X" in part of the large area the Jump back in panel covers. Or have a long-press provide a menu with "Open" and "Close".

### How do you know that this problem exists today? Why is this important?

I hit this situation several times a day.

### Who will benefit from it?

Anyone with opened tabs they want to close.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18024)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812853

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
