### ISSUE TITLE
bookmarks menu buttons same action

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21515]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently the bookmarks menu has 2 buttons (back and cross) which serves the same function , close the bookmarks menu. So the cross button can be removed and replaced with a 3 dot menu to import or export bookmarks

### How do you know that this problem exists today? Why is this important?
Buttons action are redundant

### Who will benefit from it?
All users

![Screenshot_20210927-101605121 (1)](https://user-images.githubusercontent.com/58127841/134846795-e284dcf3-bfe1-4d78-bfd7-2100902f71ac.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18025)

**Comment by bigConifer** [comment]
> 2 buttons that serve the same function: close the bookmarks menu

@sheikh-azharuddin This is only the case when you are in the top level bookmarks folder.

As soon as you descend into a subfolder, you will see that the action differs. The x is always simply closing the whole bookmarks menu while the back button brings you back to the parent screen/folder.

**Comment by sheikh-azharuddin** [comment]
> > 2 buttons that serve the same function: close the bookmarks menu
> 
> @sheikh-azharuddin This is only the case when you are in the top level bookmarks folder.
> 
> As soon as you descend into a subfolder, you will see that the action differs. The x is always simply closing the whole bookmarks menu while the back button brings you back to the parent screen/folder.

Thanks for clarifying after months 😅
I missed it

Closing the case
