### ISSUE TITLE
Research vertical swipe-to-delete for search term groupings in grid view

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#21529]
Adding swipe-to-delete to search term groups is tricky because of our horizontal scrolling (how can we safely distinguish between a horizontal scroll and a swipe gesture?).

One solution is to consider a vertical swipe gesture for those tabs. This too can have conflicts when scrolling vertically, but we'd like to see how conflicting this is.

Some known drawbacks:
 - It may not be obvious to users why a tab that seemingly looks the rest requires a different gesture to delete it.
 - In list view, we don't require a different gesture, so we should keep the horizontal gesture. Our groupings are less distinguishable in a list view as well, so not having a swipe-to-delete gesture can be more confusing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18035)

**Comment by topotropic** [comment]
Closing since we're not doing tab groups on tab tray
