### ISSUE TITLE
Taking a screenshot on the main thread delays tabs tray from opening for ~178ms

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21526]
## Steps to reproduce
- Open a web page
- Click tabs tray

### Expected behavior
No delay from taking screenshots.

### Actual behavior
We see `runUiThreadCallback` on the main thread for 178ms (the exact time seems to vary – I've seen times as low as 120ms and higher than 178): https://share.firefox.dev/3m6UT10 In the native AndroidUI thread, we see `PUiCompositorController::Msg_ScreenPixels`. This was indicative of taking a screenshot. I commented out [this line that takes a screenshot](https://searchfox.org/mozilla-mobile/rev/983771903a4ed4bccd80b54bccb2f2116e52901a/fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#310) and the problem went away: https://share.firefox.dev/3zSFA12

**It's unclear how often this is called:** it may be cached and only called once per each tab (though that could still be pretty bad) and this may affect prioritization.

### Device information

* Android device: Moto G5
* Fenix version: main 8a15e8a6818554eb9c7d66f00e2058ecfcee6eed Sep 27

---

It's possible this call occurs _after_ the tabs tray is drawn and is of little consequence to users. I confirmed this is not the case: I did this by by sleeping in an `onPreDraw` listener and manually verifying the screen contents. Here's my patch:
```
diff --git a/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt b/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
index 509149b6e..0fa4202a5 100644
--- a/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
+++ b/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
@@ -13,6 +13,7 @@ import android.view.View
 import android.view.ViewGroup
 import androidx.annotation.VisibleForTesting
 import androidx.appcompat.app.AppCompatDialogFragment
+import androidx.core.view.doOnPreDraw
 import androidx.core.view.isVisible
 import androidx.fragment.app.activityViewModels
 import androidx.fragment.app.setFragmentResultListener
@@ -112,6 +113,13 @@ class TabsTrayFragment : AppCompatDialogFragment() {
             true
         )
 
+        tabsTrayBinding.tabWrapper.doOnPreDraw {
+            it.doOnPreDraw {
+                Thread.sleep(3000)
+                requireComponents.core.engine.profiler?.addMarker("onPreDraw", "tabsTrayBinding.tabWrapper")
+            }
+        }
+
         val args by navArgs<TabsTrayFragmentArgs>()
         val initialMode = if (args.enterMultiselect) {
             TabsTrayState.Mode.Select(emptySet())
```

When I ran this, I saw the screen freeze on the web page with the tabs tray counter highlighted with a click event (i.e. the tabs tray did not start drawing). Here's the profile that shows the `runUiThreadCallback` screenshot takes place before the sleep: https://share.firefox.dev/2Y45Zfi Note this is a debug build profile and the timing shouldn't be taken into account.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18034)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807337

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
