### ISSUE TITLE
[Bug]: Third tab in group not visible in the tab tray

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#21525]
### Steps to reproduce

I have a Samsung Galaxy S9, Android 10, Firefox Nightly 94.0a1 Build#2015836395

1. Search for something - e.g. "firefox"
2. Open 3 links in new tabs
3. Open the tab tray
4. Observe that there only appears to be 2 tabs in the group but if you try to scroll you'll discover that there are more tabs
![Screenshot_20210927-170413_Firefox Nightly](https://user-images.githubusercontent.com/107992/134991889-45219de5-b803-46fc-be6d-2cb4d7b9bf7d.jpg)
.

### Expected behaviour

I should see the 3rd tab peeking out on the right hand side.

### Actual behaviour

I don't see any indication that there is a 3rd tab.

### Device name

Samsung Galaxy S9

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 Build#2015836395

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18033)

**Comment by jonalmeida** [comment]
Hmm that's interesting.. we thought we covered this by making the tab width a fixed size, but seems like there are screen densities that equal to the sum total of two tabs.. or we calculated them incorrectly!

This is what it should look like on my Pixel 3 device for reference:
<img width="537" alt="Screen Shot 2021-09-27 at 7 06 11 PM" src="https://user-images.githubusercontent.com/1370580/134997087-5ff9d711-3d44-42cf-a467-7f66ad89436f.png">

**Comment by Cheap-Skate** [comment]
My Galaxy a40 has this issue too
