### ISSUE TITLE
[Bug]:  Address bar shortcuts not working

### ISSUE THREAD

**Issue by i-petko** [mozilla-mobile/fenix#21523]
### Steps to reproduce

1. Enter "*" (^ or other shortcuts)
2. Start typing bookmark keywords

### Expected behaviour

Bookmarked pages should be suggested

### Actual behaviour

No suggestions. Nothing happens.

### Device name

samsung galaxy s9+

### Android version

android 10

### Firefox release type

Firefox Beta

### Firefox version

93.0.0-beta.5

### Device logs

No crash, cannot get relevant logs on mobile

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18032)

**Comment by SoftVision-LorandJanos** [comment]
Hi @i-petko ! Thank you for the report!
As I understand the issue you describing, I cannot reproduce it. Could you please give me an example of bookmarked page that isn't suggested? Maybe even make a video of this issue? Thank you!

Tested Firefox builds: 
- latest Release (92.1.1).
- latest Beta (93.0.0-beta.5).
- latest Nightly 94.0a1 (2021-09-28T05:08:00.088727).

Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by i-petko** [comment]
Hi @SoftVision-LorandJanos , thanks for the quick response. I am uploading the screen recording. As you can see, there are no suggestions at all, neither by tag nor URL. It's the same for all bookmarks (and history), just chose these two as an example.

**Comment by i-petko** [comment]
It seems like video was not uploaded, sorry for spam. Here it is:

https://user-images.githubusercontent.com/10596182/135079819-80cf8546-8826-4edb-a541-cc5a1d267e6b.mp4

**Comment by SoftVision-LorandJanos** [comment]
Hi again! As far as I know, the browser only suggests previously visited pages that contains the letters or symbols that you begin to type in. If for example the bookmarked pages don't begin, or don't contain "*" or "^", there should be no result among the bookmarked pages.
If you meant that those symbols should serve as shortcuts to bookmarks or history, the ticket should be changed from bug to feature request and more details would be needed from your side.
If you meant something else, please explain a bit more specifically.
Thank you!

**Comment by i-petko** [comment]
Hi again. I'm not sure if we have a misunderstanding, but this already [is a feature](https://support.mozilla.org/en-US/kb/search-firefox-address-bar#w_search-shortcuts). I have been using it, both on mobile and desktop firefox for years. It only stopped working on mobile couple of days ago.
Thank you!

**Comment by SoftVision-LorandJanos** [comment]
I'm sorry, I honestly didn't know about it.
I did try to access that function on previous versions and I had no success, it looks to me that it's only for the desktop versions, based on the description from the support page that you linked. However I may be mistaken and possibly I do things wrong so I'll leave it open for a second opinion. Thank you again!

**Comment by i-petko** [comment]
Hi again! No need to apologize, I know that this is not the most popular feature. But it's useful. I couldn't find anything about it being discontinued in the changelog. But, as you said, the documentation is desktop related, and I cannot find mobile documentation about it. I would also like to get additional info :)

**Comment by psour** [comment]
I know for sure this keyword feature worked before flawlessly. I am back an android after a year of using ios. And even firefox for ios supports this, if you have firefox sync enabled.
However, this feature is amazing. You do not need several apps to search through amazon, ebay, idealo etc. It is all a keyword away.
Please bring back this festure and promote it more😀

**Comment by psour** [comment]
This issue should be investigated. This function is a huge timesaver.

**Comment by psour** [comment]
Any chance s/o is looking into this? Or could tell me when this regression happened?

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/17184

This is a new feature, not a regression.

**Comment by psour** [comment]
But it is not a new feature. It happened to be in Firefox for Android before. As it is/was in IOS and Desktop.
The report could be a duplicate, but imho it is a regression.

**Comment by i-petko** [comment]
Just a small update from my side (Firefox Beta on Android device).
It seems like the feature is 'unstable', as it works sometime. In fact, lately it works most of the time, but not always.
I have not been able to find a pattern, though, so cannot tell what might be a reason for it to work or stop working.
