### ISSUE TITLE
260-524ms between HomeActivity.load and GeckoSession.load when entered hitting enter on search

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21530]
## Steps to reproduce
- From a web page, Click url bar
- Type "goo"
- Hit enter to go to google.com as autocomplete suggestion

### Expected behavior
Gecko is notified of page load immediately in `GeckoSession.load`.

### Actual behavior
Gecko seems to be delayed by 260+ms because `HomeActivity.load` is called 260ms before `GeckoSession.load`: https://share.firefox.dev/3ATZEBu

In another profile to apple.com, this took 524ms: https://share.firefox.dev/3ulv15d Perhaps the time above was shorter because the code is JIT'd, the XML is cached, and stuff. And another 431ms on a Moto G5+: https://share.firefox.dev/3zM4gbk Maybe it bounces between them

I'm guessing the root cause is we call `HomeActivity.load` but we suspend rather than handling the request synchronously so the UI inflation happens and then we call `GeckoSession.load`. It's also possible we need the browser fragment to call this in the current code.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 2021-09-27

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18036)

**Comment by csadilek** [comment]
We implemented a fix for this a while back as part of https://github.com/mozilla-mobile/fenix/issues/17645, but the conclusion from the performance team was that it didn't make any actual difference in page load times, see https://github.com/mozilla-mobile/fenix/issues/17645#issuecomment-844420252, at least not for the case where a new tab was being opened (as in the profile above).

However, we did start work on optimizations in A-C now to make sure we prevent those context-switches where we can: https://github.com/mozilla-mobile/android-components/issues/11066

**Comment by csadilek** [comment]
We've landed a related optimization though for the direct load case: https://github.com/mozilla-mobile/android-components/pull/11067

For the above we need feedback from the performance team as the original conclusion was that it didn't make any difference.

**Comment by mcomella** [comment]
Triage: this is a very big delay to page load time so we want to address it: P1.

The remaining **action items** are to go through the checklist in https://github.com/mozilla-mobile/fenix/issues/21530#issuecomment-938954112 and, for each use case, verify if the delay exists (i.e. the `GeckoSession.load` call is blocked on the UI transition from `HomeActivity.load` or equivalent) and, if it exists, fix it.

**Comment by mcomella** [comment]
> User enters or autocompletes to a URL (e.g. apple.com)

This use case regressed: https://share.firefox.dev/3qdBFJd These fixes are fragile so I think we have to verify we have tests for each of them.

**Comment by mcomella** [comment]
Nevermind. I accidentally tested the "needs new engine session case" we haven't optimized yet. Here's a profile when we don't need a new engine session that shows this did not regress: https://share.firefox.dev/3yIguCM

**Comment by mcomella** [comment]
I measured [an 800ms improvement on a Moto G5 when we address the GV issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1734923#c15) so it is very much worth continuing to optimize this in fenix.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807338

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
