### ISSUE TITLE
Multirow URL bar

### ISSUE THREAD

**Issue by ohhai** [mozilla-mobile/fenix#21537]
Please make the URL bar expanding to multi row field when user is editing its content.

It's very annoying to edit long URLs with current one row bar - and rest of space on the page is not used in this case, so it should be easy to expand URL bar to halfscreen or more.

Beneficial for all users who need to view or edit address inside URL bar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18043)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807715

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
