### ISSUE TITLE
Scroll up fails every second time

### ISSUE THREAD

**Issue by Kinrany** [mozilla-mobile/fenix#21536]
### Steps to reproduce

1. Open https://github.com/mitsuhiko/insta/issues
2. Scroll down, wait for the animation to finish
3. Scroll up

### Expected behaviour

Scroll up action should move the window

### Actual behaviour

Every second scroll up action opens the tray but does not move the window.

### Device name

Samsung Galaxy A70

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

This only happens when I scroll up. Scrolling up second time always works. Scrolling down and up repeatedly always moves the window down but not up. Scrolling down always works.

This happens on some pages but not others. Opening a new tab doesn't help.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18042)

**Comment by mrxyzl** [comment]
Can confirm this behavior on latest nightly 28|9|21
After scrolling to the bottom of Google search page (using goolge search fixer addon to have chrome UI google), swiping up will bring the addresses bar up instead of scrolling the page up

Its very annoying and

**Comment by marcel263** [comment]
Disabling pull to refresh is a possible temporary fix

**Comment by Kinrany** [comment]
> Disabling pull to refresh is a possible temporary fix

Can confirm, definitely works for me.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-02-22.

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)

**Comment by Cheap-Skate** [comment]
This is still an issue please don't close

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811616

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
