### ISSUE TITLE
Duplicate search results for bookmarks, history, open tabs

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#21533]
### Steps to reproduce

1. Visit a few pages, bookmark some of them, keep some tabs (with some of the bookmarked pages) open.
2. Search in the URL bar for something related to those pages.

### Expected behaviour

A combined list of results for bookmarks, open tabs and history, with *one entry per URL* and the whole thing sorted by frecency, like it used to be in Fennec and *still is* on Desktop.

### Actual behaviour

I get up to three duplicated results for the same URL – one for each of bookmarks, history and open tabs.

### Device name

Moto G4 Play

### Android version

Android 6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (Build #2015836489)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18039)

**Comment by buttercookie42** [comment]
Still happens, and if I have the same page open multiple times then I even get separate entries for each individual tab with that page open.

**Comment by buttercookie42** [comment]
Begone, you overeager bot. (Still easily reproducible.)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810595

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
