### ISSUE TITLE
[REQ] Enhance undo snackbar to be clickable to 100%

### ISSUE THREAD

**Issue by zapy85** [mozilla-mobile/fenix#21548]
So, this is just such a simple fix/tweak i really dont know how much text i should put in to it!

When closing a tab regardless how, you need to actualy tap the Undo text on the snackbar presented, why not make the whole snackbar tapable instead of just the text?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18055)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807133

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
