### ISSUE TITLE
Enable Notification but Disable Web Push Notification Box

### ISSUE THREAD

**Issue by ttaylorbader** [mozilla-mobile/fenix#21544]
Would it be possible to leave notifications enabled but have the option to turn on web pushes or not? I, personally, don't want ot web push to show, but I prefer to get audio notifications.

**Comment by kbrosnan** [comment]
This depends on your version of Android and any manufacturer customization. By default on modern Android this is possible. Android allows the user to mute individual notification channels.

![Screenshot_1632867255](https://user-images.githubusercontent.com/250273/135173335-013d0781-80f8-4bea-97f6-4e18cd7a6238.png)
