### ISSUE TITLE
Perceived performance of tab tray scroll seems janky due to thumbnail loads

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/fenix#21547]
## Steps to reproduce
- Have multiple tabs open (on my g5+ I had at least 6 or 7 to be able to scroll, the more the better since it'll accentuate the effect)
- Open the tab tray
-  Scroll moderately fast

### Expected behavior
Thumbnails should have an image and shouldn't change while scrolling since it creates a "look" of jank.

### Actual behavior
Thumbnails shouldn't load sequentially and shouldn't show a no internet sign then load the thumbnail 

The thumbnails showing up later while scrolling gives a feeling of jank. I believe this issue has been brought up in the past. This seems to be the result of the asynchronous nature of loading our thumbnails.

### Device information

* Android device: Moto G5+
* Fenix version: Nightly 2021-09-22

This is a video showing that the thumbnail load creates a perceived perf issue.

https://user-images.githubusercontent.com/16614353/136271879-dfcbc731-a5fc-4b1a-9a8e-707689561074.mp4

**Comment by jonalmeida** [comment]
Engineering notes: we can make the perceived perf better as noted above by removing the [placeholder image that we set initially](https://github.com/mozilla-mobile/android-components/blob/86ec838abb6f8583296c1558b21efa822b21a97a/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/loader/ThumbnailLoader.kt#L49), which is then removed a few milliseconds later with an image from the cache.

**Comment by RotBolt** [comment]
hello, @mcomella @jonalmeida Can I take a stab at this?
Its a good performance issue to fix

**Comment by jonalmeida** [comment]
@RotBolt Yes, I think so! The notes above should still be valid. So can have a shot at that. I think what we need is something that follows:
 1. Try to get thumbnail and display.
 2. If not, only then show a placeholder.

Compared to what we have now:
1. Show a placeholder immediately.
 1. Try to get thumbnail.
 2. If possible, swap the placeholder for the thumbnail.

**Comment by RotBolt** [comment]
@jonalmeida
It seems, its a issue on Android components
Any recommended way on how to integrate the local android components build into Nightly Fenix build?

**Comment by RotBolt** [comment]
Also, I have a suggestion on performance
I see the Private tab and Normal Tab uses recyclerview of their own and items are similar
So I think we can share the recyclerviewPool among the two recyclerviews 

You can refer this article for more https://medium.com/@thagikura/reduce-the-number-of-inflation-of-viewholders-drastically-by-sharing-a-viewpool-across-multiple-249d5fc6d28

cc @jonalmeida @mcomella

**Comment by RotBolt** [comment]
>It seems, its a issue on Android components
Any recommended way on how to integrate the local android components build into Nightly Fenix build?

I am able to integrate the local android components library into fenix for Debug variant.

For nightly variant. It seems i need some signing key.

**Comment by RotBolt** [comment]
Also One more input, 
I see we are always loading thumbnails from the DiskLruCache, so everytime thumbnail is loaded, it reads a disk
I think we should have `inMemoryLRU cache` as well to do this

**Comment by jonalmeida** [comment]
> > It seems, its a issue on Android components
> > Any recommended way on how to integrate the local android components build into Nightly Fenix build?
> 
> I am able to integrate the local android components library into fenix for Debug variant.
> 
> For nightly variant. It seems i need some signing key.

On the Fenix README [here](https://github.com/mozilla-mobile/fenix#localproperties-helpers), there are instructions for how to build against a local android-components build as well as how to sign a release app with a local debug signing key.

> I see we are always loading thumbnails from the DiskLruCache, so every time thumbnail is loaded, it reads a disk
> I think we should have `inMemoryLRU cache` as well to do this.

Let's file a separate issue for this if we think it's important. We can fix the perceived performance first with this ticket and then profile the app to see how long it takes for us to read/load from the disk to gather whether it is worth optimizing after that.

> Also, I have a suggestion on performance
> I see the Private tab and Normal Tab uses recyclerview of their own and items are similar
> So I think we can share the recyclerviewPool among the two recyclerviews

The private and normal tabs use the same recyclerview with different adapter items, which you can see being constructed [here](https://github.com/mozilla-mobile/fenix/blob/d599cc7375a00ef808628cd36bc27c8a0db66152/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt#L155-L170).

There is a push to modernize our homescreen for performance but also for maintainability, so viewholders are being re-written into work within `ComposeView`, with the aim of having all the items in a [Compose list](https://developer.android.com/jetpack/compose/lists) as well. For that reason, I'm not convinced we should spend too much time optimizing for RecyclerView performance unless they are quick wins. 

@mcomella might have some considerations here too.

**Comment by RotBolt** [comment]
>The private and normal tabs use the same recyclerview with different adapter items, 

I checked the XML files and [NormalBrowserPageViewHolder](https://github.com/mozilla-mobile/fenix/blob/514a8c4437e74ad206321943e81d2671bc0e975a/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt#L195) and [PrivateBrowserPageViewHolder](https://github.com/mozilla-mobile/fenix/blob/514a8c4437e74ad206321943e81d2671bc0e975a/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/PrivateBrowserPageViewHolder.kt#L59)
The recyclerview used in these viewHolders are different instances.  so the recyclerpool would be different as well

> There is a push to modernize our homescreen for performance but also for maintainability, so viewholders are being re-written into work within ComposeView, with the aim of having all the items in a [Compose list](https://developer.android.com/jetpack/compose/lists) as well. For that reason, I'm not convinced we should spend too much time optimizing for RecyclerView performance unless they are quick wins.

I could check the number of inflation and performance impacts for this. If this makes difference will post here

Meanwhile, I would raise the PR on Android components for Perceived performance. I was able to test on debug variant.

**Comment by jonalmeida** [comment]
> I checked the XML files and [NormalBrowserPageViewHolder](https://github.com/mozilla-mobile/fenix/blob/514a8c4437e74ad206321943e81d2671bc0e975a/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/NormalBrowserPageViewHolder.kt#L195) and [PrivateBrowserPageViewHolder](https://github.com/mozilla-mobile/fenix/blob/514a8c4437e74ad206321943e81d2671bc0e975a/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/PrivateBrowserPageViewHolder.kt#L59) The recyclerview used in these viewHolders are different instances. so the recyclerpool would be different as well

Ah yes, you're right. I misunderstood the context of what we were talking about. The view pool would be different yes. However, I bet we could hold each view pool within the lifecycle of the fragment, so switching between normal and private tabs multiple times would benefit from that. Again, I'm not sure if that's worth optimizing for though.

> Meanwhile, I would raise the PR on Android components for Perceived performance. I was able to test on debug variant.

Excellent! 🎉

**Comment by mcomella** [comment]
>> I see we are always loading thumbnails from the DiskLruCache, so every time thumbnail is loaded, it reads a disk
>> I think we should have inMemoryLRU cache as well to do this.
>
> Let's file a separate issue for this if we think it's important. We can fix the perceived performance first with this ticket and then profile the app to see how long it takes for us to read/load from the disk to gather whether it is worth optimizing after that.

To take a step back, a key idea in performance is that we should only optimize our code for performance if it's A) trivial to do so or B) it's a known performance issue. The reason is that performance optimizations take time and frequently make the code more complex so if users aren't seeing a reasonable improvement, it's probably not worth it. So as jonalmeida says, if we identify this as a known performance issue (either by subjectively experiencing a delay or by objectively measuring the time it takes), only then we should work on it.

Thank you for thinking about possible additional optimizations! It's a good intuition to have. 😄

> @jsoriano I cannot see the Issue for this Android components, should I create one and raise the PR then ?

If there's only a fenix issue, I usually do something like: "For fenix#21547: made a change." But I'm not on the core team so maybe @jonalmeida would disagree.

**Comment by jonalmeida** [comment]
> > jsoriano I cannot see the Issue for this Android components, should I create one and raise the PR then ?
> 
> If there's only a fenix issue, I usually do something like: "For fenix#21547: made a change." But I'm not on the core team so maybe @jonalmeida would disagree.

You can create an issue on Android Components as well to describe the isolated problem and link to the Fenix one as well. That works too. 🙂

**Comment by RotBolt** [comment]
I see I issue with Tab Switching as well

Currently, `viewpager offscreen limit = 1` due to which with every switch, it loads the content for each fragment again. 
IMO, we should set it to `Three` as it would result in a smooth scroll across private, normal, synced tabs


Let me know WDYT @jonalmeida @mcomella

**Comment by mcomella** [comment]
I'm not familiar with this API to give an opinion off the top of my head. @jonalmeida Do you know?

**Comment by mcomella** [comment]
Triage: approved but not landing until we cut beta.
