### ISSUE TITLE
Show the site url in password suggestions

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21542]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently the password suggestions dialog is not showing the url name , so if there are multiple logins for same domain but different site it is getting difficult to select the correct one

### How do you know that this problem exists today? Why is this important?
Difficult to select correct account for the site

### Who will benefit from it?
All users

![Screenshot_20210928-211450521](https://user-images.githubusercontent.com/58127841/135121204-4cde82b2-d4e2-4aa2-84b8-fd2d877dec9d.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18049)

**Comment by sheikh-azharuddin** [comment]
Not solved

**Comment by delia-pop** [comment]
I will mark this ticket as a feature request.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812437

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
