### ISSUE TITLE
[Bug]: Add login form can create logins that look like duplicates

### ISSUE THREAD

**Issue by bendk** [mozilla-mobile/fenix#21543]
### Steps to reproduce

1. Save a login for any site
2. Go to the saved logins setting page
3. Click Add login
4. Add a login for the same site/username/password
5. Save the form

### Expected behaviour

The form should display an error saying this is a duplicate login

### Actual behaviour

The login successfully saves, then when you look at the login list you see two "duplicates".  They aren't low-level duplicates, since one has `form_action_origin` set and the other has `http_realm` set, but the user has no way of seeing that distinction.

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

It's actually not so simple to fix this one currently.  Desktop handles this by setting `form_action_origin=""`, then matches the duplicate.  I don't think the a-s code currently supports this, but we could add this.  I think that would be after the current logins work though.

I also think the way `form_action_origin` and `http_realm` are used in dupe-checking maybe should be changed, but that's a whole other subject.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 100.0a1 (2022-03-28) build.
An error message is displayed after if the username is the same for the same page as saved before.
Closing the ticket as fixed.
