### ISSUE TITLE
uploading files on virustotal doesn't work

### ISSUE THREAD

**Issue by Palloxin** [mozilla-mobile/fenix#21568]
### Does toggling Tracking Protection fix the issue? 
yes it does, but only if i disable the tracking protection
### Can you reproduce in Chrome (or other non-Mozilla browser)?
no
### Device information

* Android device: huawei p8 lite 2017
* Fenix version: 92.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18068)

**Comment by marcel263** [comment]
cannot reproduce with 93 beta 5 or nightly

**Comment by Palloxin** [comment]
> 
> 
> cannot reproduce with 93 beta 5 nor with nightly

you have to enable the tracking protection

**Comment by Amejia481** [comment]
@Palloxin would you mind sharing which tracking protection setting do you have? Recommended, Strict or Custom. It will be great if you could share a print-screen if possible.

**Comment by Palloxin** [comment]
> 
> 
> @Palloxin would you mind sharing which tracking protection setting do you have? Recommended, Strict or Custom. It will be great if you could share a print-screen if possible.

@Amejia481 i wrote the settings but if you need the screenshot... here you go
![IMG_20211002_095920](https://user-images.githubusercontent.com/75091899/135708620-7e9f96d2-e68e-4294-9401-c244b21b3a5b.jpg)

**Comment by Palloxin** [comment]
bug still there
