### ISSUE TITLE
FNXV2-17823 - Contextual message for Inactive tabs

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#21565]
Tracking for https://mozilla-hub.atlassian.net/browse/FNXV2-17823

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Beta 94.0.0 beta1.

On the latest Nightly (95.0a1 - 2021-10-06T05:11:35.245780) the contextual message was not activated.

Device used: Samsung Galaxy Tab S3 (Android 9).

Closing the ticket as verified.
