### ISSUE TITLE
[Bug]:"Recently visited" section

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#21570]
### Steps to reproduce

Open a few sites so the the "Recently visited" section is populated.

### Expected behaviour

I tap on an entry and go to the history section.

### Actual behaviour

I tap on an entry and nothing happens OR I see the "Remove" option; when I tap on "Remove" nothing happens.

### Device name

Google Pixel 3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 94.0a1

**Comment by vesta0** [comment]
@topotropic this is fixed now. Please verify and close.

**Comment by amedyne** [comment]
Closing as this has been fixed.
