### ISSUE TITLE
Only show "Other" section if tab groups exist

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#21576]
If there is only one tab group -- "other" -- it should not be shown. If the user has one or more group in addition to "other", we can show it.

**Comment by pocmo** [comment]
This is even more confusing if tab grouping is disabled (#21360) and all tabs are always "other tabs" :)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-10-05.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
