### ISSUE TITLE
Move "what's new" behind feature flag

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#21574]
Re: conversation with @betsymi and @vesta0, we should keep this behind a flag until the copy is finalized.

**Comment by eliserichards** [comment]
This onboarding will only be shown on debug for now. It should not appear on Nightly.

**Comment by eliserichards** [comment]
Removing qa-needed since this has been fixed and the feature flag is removed

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview 94.0.0-beta.2.

### Devices used:
- Huawei MediaPad M3 (Android 7)
- Oppo Find X3 (Android 11)
