### ISSUE TITLE
As a user I want to more easily open PDF files

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#21579]
## User Story

As a user, I want to be able to open PDF files quickly. As a use case, many restaurants now give you a QR code with a link to a PDF. This story is about going as quickly as possible from pointing your camera to the QR code to reading the menu on your device.

In Fenix there are currently a lot of steps to be done:

 - Tap the location bar
 - Tap the QR code button
 - Point your camera at the QR code
 - Allow Firefox to open http://.../foo.pdf
 - Tap the "Download" button in the toast that asks if you want to download the file
 - Tap the "Open" button when the download completes

At this point the PDF opens in the Android provided PDF reader.

Some thoughts:

Things get really tricky if you accidentally deny permission for the download (storage) or the camera. There is no easy way to correct that and I think many people struggle to find the right things in Android's settings.

Maybe it is possible to combine the last three steps into one. It feels like the first dialog that says `Allow Firefox to open https://.../menu.pdf` should be enough user permission to skip approving the download and opening of the file?

On Desktop, the PDF file is downloaded to memory or a temporary file (?) and then displayed inline with `pdf.js` - is that something we maybe want to do on Fenix too? Did we on Fennec?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18081)

**Comment by kbrosnan** [comment]
We looked at PDF.js about 10 years ago. bz-834358. There was a few megabyte hit on using it so it never made it past some test builds.

**Comment by BlackHoleFox** [comment]
I'd still enjoy seeing this story come about, so please don't close this out yet? Quick and easy temporary PDF viewing would be great.

**Comment by BlackHoleFox** [comment]
ugh I missed the stalebot notification this cycle.
