### ISSUE TITLE
[Bug]: Tab Closed Undo button covers the last tab

### ISSUE THREAD

**Issue by miketriple** [mozilla-mobile/fenix#21586]
### Steps to reproduce

1. Have tabs open. I usually have many tabs, so I have to scroll to see them all. Not sure if this is needed, or if it does the same with only 2 tabs. It always does this when I have 10+ tabs open.
2. Open tab view and close the bottom tab.
3. Try to close the last tab. It's covered by the Tab Closed Undo button.

### Expected behaviour

The tab closed undo button should not cover up the next tab. This is often the tab I want to go back to or also close right after closing another tab. 

### Actual behaviour

The Tab Closed Undo button covers up the next tab, making users wait several seconds until it disappears if they want to view that tab or close it.

### Device name

Google Pixel 4

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1

**Comment by kbrosnan** [comment]
Duplicate #19166
