### ISSUE TITLE
[Bug]: Two media tab items inJump Back In are shown for media related tab after reopening the app

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#21583]
### Steps to reproduce

1. Have a tab where you are viewing media (like video on Youtube)
2. Open another tab for regular browsing
3. Go to Home
4. Close/dismiss Fenix

### Expected behaviour

A media tab, a browsing tab and a group tab of my last activity are shown under jump back in

### Actual behaviour

Two media tabs are shown, the regular browsing related tab is no longer shown under jump back in

### Device name

Google Pixel3 XL

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

See attached vide

https://user-images.githubusercontent.com/68711330/135347801-a6dfad9b-b6c0-4756-986e-cd00bbf9988b.mp4

**Comment by mcarare** [comment]
Closing this, as it seems it is not valid anymore after https://github.com/mozilla-mobile/fenix/issues/21642.
