### ISSUE TITLE
[Bug]: Thumbnail images on Jump Back In do not persist after closing/reopening Fenix

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#21582]
### Steps to reproduce

1. Have several tabs open
2. Press on Home button to go back Home
3. Thumbnails for the page are shown on the section under jump back in
4. Close/dismiss Fenix
5. Open the app 

### Expected behaviour

Thumbnail images should still be displayed in the JumpBackIn section

### Actual behaviour

Thumbnails are replaced with Favicons for items under the JumpBackIn section

### Device name

Google Pixel3 XL

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

### Additional information

See attached video

https://user-images.githubusercontent.com/68711330/135344851-33346765-dd78-4bcc-a350-18165457a1f0.mp4

.

**Comment by jonalmeida** [comment]
We need to add an `if-else` branch [here](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt#L247) to look through the `BrowserThumbnailsStorage` for screenshots of the tab before we make our final fallback to the site favicon.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nigthly 2021-10-06 and 94.0.0-beta.1.

### Devices used:
- Huawei MediaPad M3 (Android 7)
- Oppo Find X3 (Android 11)
