### ISSUE TITLE
FNX-505 ⁃ [Bug] video playback aborted due to a network issue

### ISSUE THREAD

**Issue by rmbq** [mozilla-mobile/fenix#2159]
## Steps to reproduce
Open this video:
https://www.facebook.com/trynottolaughpets/videos/418428262272505/

and jump straight to an unbuffered point.

Step to reproduce video:
https://youtu.be/z8HvI7bkRTM

### Expected behavior
video plays at desired point

### Actual behavior
error popup "video playback aborted due to a network issue"

### Device information
* Android device: Oneplus 6 lastest stable
* Fenix version: 1.0.1920 (Build#11370606 68.0a1-20190508111321

**Comment by rmbq** [comment]
update OP with step to reproduce

**Comment by sv-ohorvath** [comment]
@rmbq URL signature expired. Can't access the link you shared.

**Comment by rmbq** [comment]
> @rmbq URL signature expired. Can't access the link you shared.

updated, should be fine now. it's another video but you can reproduce the issue

**Comment by sv-ohorvath** [comment]
I was able to reproduce this on the latest build: 5/20. 
Device: P9 lite (Android 6). 
Also reproducing on Fennec, but not Chrome.

**Comment by vesta0** [comment]
@cpeterso this seems like a GV issue since it's also reproducing on Fennec. Do we have a bug for it?

**Comment by cpeterso** [comment]
I filed a new Gecko media bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1555452

Is this bug reproducible in Chrome? A similar Facebook video seeking bug was reported in Fennec 10 months ago, but it was a Facebook network bug and was also reproducible in Chrome:

https://bugzilla.mozilla.org/show_bug.cgi?id=1477649#c14

**Comment by rmbq** [comment]
I can't reproduce it on Chrome, usually i use chrome to watch the video because of this bug

**Comment by cpeterso** [comment]
> I can't reproduce it on Chrome, usually i use chrome to watch the video because of this bug

Thanks for checking. That's helpful information. This bug must be a different issue than the old bug 1477649.

**Comment by cpeterso** [comment]
This bug is in the Gecko Media team's backlog, but we don't have an estimate of when they will have time to investigate.

A related Gecko Media bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1566572

**Comment by liuche** [comment]
@cpeterso I added this `needs:gecko` label, for things that also need a Gecko change (not just GV). Could you update the labels for the other bugs to reflect that? (and updating the `needs:gv` if that's still relevant, or simply a Gecko change)

**Comment by liuche** [comment]
@cpeterso I added this needs:gecko label, for things that also need a Gecko change (not just GV). Could you update the labels for the other bugs to reflect that? (and updating the needs:gv if that's still relevant, or simply a Gecko change)

cc @boek @bifleming

**Comment by cpeterso** [comment]
> @cpeterso I added this needs:gecko label, for things that also need a Gecko change (not just GV). Could you update the labels for the other bugs to reflect that? (and updating the needs:gv if that's still relevant, or simply a Gecko change)

OK. I'll add `needs:gecko` and remove `needs:gv` as needed for these bugs:

https://github.com/mozilla-mobile/fenix/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aneeds%3Agv+-label%3Aneeds%3Agecko

**Comment by boek** [comment]
The media team has investigated this and it is blocked on a 3rd party

**Comment by fluffyemily** [comment]
Bryce from the media team has spoken to @ekager about https://bugzilla.mozilla.org/show_bug.cgi?id=1566572. The media team can not reproduce and would like to get confirmation from the Fenix team that it is no longer an issue before they close the bug.

**Comment by ekager** [comment]
Closing because the media teams can't reproduce anymore. We can revisit if we get this report again.
