### ISSUE TITLE
Pocket recommended stories: Persistent topics selection

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#21593]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-17904

When people select a certain topic it should be persisted and not reset by a cold start.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (94.0a1 - 2021-10-05T05:10:10.350256).

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
