### ISSUE TITLE
Pocket recommended stories: Don't topup with general stories

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#21592]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-17991

Priya: 
> we should not top up with general stories if a user has chosen a category. It's okay to reduce the refresh rate and show older stories/stories a user may have already seen. What matters is the relevancy to the category chosen and not the recency.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (94.0a1 - 2021-10-05T05:10:10.350256).

All stories checked were relevant to the category selected.

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
