### ISSUE TITLE
FNX-5487 ⁃ [Meta] Private Browsing

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#216]
### Why/User Benefit/User Problem
* Help users be more protected on the web
* Help users not share cookies or other tracking related information with others
* Allow users to browse privately 

### What / Requirements
As a Fenix user, I want to browse to websites privately without the device nor the website knowing about my visit
(Do not collect telemetry around entering PB mode)

### Acceptance Criteria (how do I know when I’m done?)
* Users history, passwords or form and search fields are not being stored 
* Block cookies 
* Private tab management

**Comment by st3fan** [comment]
From an A-C perspective this should be good to go. Look at the Reference Browser for implementation details.

**Comment by st3fan** [comment]
@bbinto Just a note that *Blocking Cookies* is not what Private Mode does. If that is something you need then that is a departure from what PM currently does in our products.

**Comment by bbinto** [comment]
As long as the UX flow is not defined, eng is not confident to estimate and know how much A/C can be used.

**Comment by bbinto** [comment]
Removing blocked label as @brampitoyo has provided mocks, waiting for @colintheshots to confirm if it's enough for eng to start breaking down.

**Comment by bbinto** [comment]
As per [comment](https://github.com/mozilla-mobile/fenix/issues/240#issuecomment-473414507), we might pull this back into a Battery saving story after MVP, however it should land for MVP as an individual feature.
