### ISSUE TITLE
passwords & usernames don't autofill[Bug]: 

### ISSUE THREAD

**Issue by drbldrbl** [mozilla-mobile/fenix#21604]
### Steps to reproduce

1. go to an htpasswd protected site
2. username & password blank
3. filled in from memory
4. still doesn't work

### Expected behaviour

The form should autofill. Sync shows password and username is synced with desktop version

### Actual behaviour

form should autofill.

### Device name

Huawei 

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

92

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/13941

May be fixed in 93 by bz-1676216
