### ISSUE TITLE
FNX-5488 ⁃ [Bug] The keyboard remains displayed after a bookmark edit

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2160]
## Steps to reproduce
1. Edit a bookmark title. The keyboard is displayed.
1. Tap the back button to close the edit mode.
1. Close the bookmarks menu using the "x" close button.
    1. Expected behavior
When you exit edit mode, the keyboard is hidden.
    1. Actual behavior
The keyboard remains on top when you exist edit mode. 
On some devices (Galaxy Tab 3 (Android 8.0), Mi 4i (Android 5.0.2)), it also remains on top after closing the bookmarks menu.
    1. Device information

* Android device: Pixel (Android 9), Galaxy Tab 3 (Android 8.0), Mi 4i (Android 5.0.2)
* Fenix version: 4/29

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build 190718 (#11990608) with Sony Xperia Z5 Premium (Android 7.1.1), Google Pixel 3 (Android 9), Samsung Galaxy Tab A6 (Android 5.1.1).
