### ISSUE TITLE
FNX-5489 ⁃ [Bug] Restoring a crashed tab doesn't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2161]
## Steps to reproduce
1. Open a webpage.
1. Go to about:crashcontent.
1. Restore tab.
    1. Expected behavior
The initial webpage is restored.
    1. Actual behavior
about:crashcontent is restored. 
Not useful to restore the crashing URL.
    1. Device information

* Android device: Pixel (android 9), Mi 4i (Android 5.0.2)
* Fenix version: 4/29

**Comment by vesta0** [comment]
This may be a regression, I remember this was previously working. FYI @sblatz

**Comment by sblatz** [comment]
This is a regression, yes. Perhaps something changed in how AC is handling the navigation to about pages. I know @jonalmeida was working on those: https://github.com/mozilla-mobile/android-components/issues/2790

**Comment by jonalmeida** [comment]
> This is a regression, yes. Perhaps something changed in how AC is handling the navigation to about pages. I know @jonalmeida was working on those: [mozilla-mobile/android-components#2790](https://github.com/mozilla-mobile/android-components/issues/2790)

This issue is unrelated.

**Comment by sblatz** [comment]
Was there a GV change that may have caused this (about page change or crash handling change) @cpeterso? We haven't changed this portion of our code, so I'm not sure why it would be happening on our side.

**Comment by cpeterso** [comment]
> Was there a GV change that may have caused this (about page change or crash handling change) @cpeterso? We haven't changed this portion of our code, so I'm not sure why it would be happening on our side.

Restoring the page after about:crashcontent works for me in Fenix 1.0.198 (4/30) but not in RB 1.0.1918. (RB opens about:blank after the crash.) Fenix and RB are both using the GV 68.0a1-20190422094240 (which is eight days out of date, btw), so I don't think this is a GV bug.

**Comment by sblatz** [comment]
Yeah, very strange. This is working for me on master, but not on nightly. @sv-ohorvath can you verify this happens on tomorrow's build? I wonder if it's an issue with our "nightly" build config?

**Comment by sv-ohorvath** [comment]
Works fine now on Nightly 5/2. Thanks!
