### ISSUE TITLE
Jump back in Contextual Hints for Firefox Android 94 Release

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#21611]
https://mozilla-hub.atlassian.net/browse/FNXV2-17841

**Comment by Amejia481** [comment]
QA team please help us to verify that after one of this sections is visible Jump back in, Recently saved, Recent explorations and Pocket a on boarding dialog is displayed and after the **CRF dialog is displayed.** Thanks in advance.

![image](https://user-images.githubusercontent.com/773158/135862269-a281a86e-4ac1-40b9-bcc9-52de7a4943ab.png)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-10-05.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
