### ISSUE TITLE
Pocket recommended stories: Handle optional values

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#21626]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-17763

Defensive programming principles recommend to be prepared for every scenario.
Especially for malformed downloaded data over which we have no control.

Currently it is possible for the timeToRead property to be empty.

Nicole recommended to treat the following
- `url`
- `title`
- `imageUrl`
- 
as mandatory fields - if missing we should avoid showing that story

All other fields as optional - if missing we should just show blank.

The 3 mandatory properties [are enforced in AC already](https://github.com/mozilla-mobile/android-components/blob/ca8526ee6de67e9e6314f14300034e8a0973f31c/components/service/pocket/src/main/java/mozilla/components/service/pocket/api/PocketJSONParser.kt#L44-L47) ensuring that we won't receive any story with a mandatory property missing.

In Fenix we just need to handle the optional values.
- `category` is already handled by us storing in memory the list of stories to show based on their property https://github.com/mozilla-mobile/fenix/blob/526501160c453bc85750737677046ab3547ff3d2/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L259-L261 
- `publisher` and `timeToRead` are left to be ignored from showing if they have [default invalid values](https://github.com/mozilla-mobile/android-components/blob/ca8526ee6de67e9e6314f14300034e8a0973f31c/components/service/pocket/src/main/java/mozilla/components/service/pocket/api/PocketJSONParser.kt#L49-L51)

**Comment by Mugurell** [comment]
For QA : Testing side by side a new apk and an older one (from last week) would could show in some cases an empty publisher or "-1" for time to read while in the new apk these invalid values aren't shown at all.
If there isn't a story with invalid values I think it's also safe to close this as Done.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (94.0a1 - 2021-10-04T05:10:50.531272).

Devices used:

Samsung Galaxy Tab S3 (Android 9).
Huawei P30 (Android 10).
Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
