### ISSUE TITLE
[Bug]: Pocket stories horizontal shadows are clipped

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#21621]
### Steps to reproduce

App's homescreen - Pocket recommended stories section

### Expected behaviour

Horizontal shadows should be shown the same as they do for the above recent tab items.

### Actual behaviour

Horizontal shadows are clipped.

<img src="https://user-images.githubusercontent.com/11428869/135585813-a0341e62-0a7a-4052-9d04-5120630af96d.png" width="50%" />

### Android version

All

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly

### Additional information

Based on https://issuetracker.google.com/issues/186318448#comment4 clipping main axis shadows is the expected behavior but maybe we can work around this.

**Comment by Mugurell** [comment]
After talking with topotropic about the fact that the "Recently bookmarked" section is not clipped and so it can show shadows but also extend to the edge of the screen when scrolled it might be worth to remove the 16dp padding from the list and have each child declare it's own.
In this case Pocket could declare 0 dp for the composeView and 16 dp for the content needing that which would ensure enough space in which to show the shadow.
Have to test.

**Comment by Mugurell** [comment]
In the interim Nicole proposed adding a 4dp padding to the stories so that they'd have a bit of shadow.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (95.0a1 - 2021-10-06T05:11:35.245780) and on the latest Beta 94.0.0 beta1.

Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
