### ISSUE TITLE
In Dark mode, visual glitch/white outlines on "Recently visited" long-press/context menu

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#21624]
### Steps to reproduce

1 Dark mode enabled
2 Long-press item from Recently visited
3 observe white outline

### Expected behaviour

all dark including inner border and shadow

### Actual behaviour

White outline as if it was selected incorrectly during design phase, or was set incorrect style infirmation for dark mode

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (Build #2015836971)

### Additional information

![Screenshot_20211001-120423_Firefox Nightly](https://user-images.githubusercontent.com/76437842/135603330-65b09ee2-5312-4715-b211-307ca6010a85.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18120)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 100.0a1 (2022-04-01) build.
Device used: Oppo Reno 6 (Android 12).

**Comment by marcel263** [comment]
still present

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811615

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
