### ISSUE TITLE
Update Section Titles on Homepage

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#21646]
For https://mozilla-hub.atlassian.net/browse/FNXV2-18008

- Recently bookmarked -> Recent bookmarks
- Recently visited -> Recent searches
- Thought provoking stories -> Thought-provoking stories
- Customize home -> Customize homepage **Note: we are keeping the "customize home" string since it is not being changed in the home menu**
- Above strings are updated on both home and Customize settings

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (94.0a1 - 2021-10-04T05:10:50.531272).

The border is displayed in dark and light theme.

Devices used:

- Samsung Galaxy Tab S3 (Android 9).
- Huawei P30 (Android 10).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
