### ISSUE TITLE
FNX-5492 ⁃ [Bug] Sync automatically after a short while

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2164]
## Steps to reproduce
1. Sign in on 2 devices.
1. Add a few bookmarks on one of them.
1. Wait to sync automatically.
    1. Expected behavior
AFAIK on Fennec, the new bookmarks are synced automatically.
    1. Actual behavior
No automatic sync after 1 hour or more since new bookmarks were added.
    1. Device information

* Android devices: Pixel, Mi 4i (Android 5.0.2)
* Fenix version: 4/29

**Comment by grigoryk** [comment]
This is part of the a-c sync manager, aka "heuristic syncing". I'll look for a relevant issue.

**Comment by vesta0** [comment]
@grigoryk did you find a relevant issue? How often is sync scheduled at the moment?

**Comment by sv-ohorvath** [comment]
This has an impact on Sending tabs, which you expect to happen almost instantly.

**Comment by vesta0** [comment]
@sarentz will open a new bug for a workaround to this issue.

**Comment by grigoryk** [comment]
@sv-ohorvath sending/receiving tabs is no longer technically part of Sync like it was in Fennec, so this doesn't have impact on tabs. We have a separate mechanism to receive tabs; currently we poll for new tabs every 15 minutes, and soon we'll be landing push support which should make receiving tabs nearly-instant.

Also, we already sync on a schedule, every four hours. And now that https://github.com/mozilla-mobile/fenix/pull/2955 landed, we'll sync on app coming into foreground. So I'd say we should be in an OK place with regards to "data liveliness".

Given all of the above, I don't think this should be an MVP blocker.

**Comment by ekager** [comment]
Sounds like we can close this issue?

**Comment by pocmo** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/2727

**Comment by vesta0** [comment]
Closing this issue since this no longer impacts Send Tab + we will be implementing Sync Manager soon.
