### ISSUE TITLE
Do not display a tab tray grouping if only one tab exists for it

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#21641]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
- Tab groups take up a lot of space in the tray and do not provide much use if there is only one tab with that search term.

### How do you know that this problem exists today? Why is this important?
- Search term grouping with one tab only take up a full horizontal section of the screen therefore increasing the vertical scrolling real estate.

### Who will benefit from it?
Users of search term groupings.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-10-05.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
