### ISSUE TITLE
Consider exposing original search results page as part of the search group

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#21659]
Currently, we do capture the search results page on the tabs tray group, but not on the Home view or History view.

In the History view, it makes sense to have the results page appear within the group, as otherwise it appears _outside_ of the group as a single visit, which is a bit odd.

Within the Home view, it's less clear. Some kind of "resume this search" functionality (perhaps, available via the context menu?) could be more appropriate. Or, we could display the results page within the group itself, but with a title clearly indicating what it is.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on the latest Firefox Preview Nightly 2021-11-23. The initial search page is displayed in the search group when accessed from the home page or history section.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
![search](https://user-images.githubusercontent.com/50983519/143052403-79fecd7d-ac0d-44ae-963b-62c9cf57f104.JPEG)
