### ISSUE TITLE
[Bug]: Video jitter when speed increases to 1.5x or above

### ISSUE THREAD

**Issue by Thewisem** [mozilla-mobile/fenix#21651]
### Steps to reproduce

1. Play a video
2. Increase speed to 1.5x or above
3. See error

### Expected behaviour

No jitters

### Actual behaviour

Becomes a jittery mess

### Device name

Samsung Galaxy Tab A

### Android version

7.1.1 nougat

### Firefox release type

Firefox

### Firefox version

89.0.10

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1733991

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Thewisem** [comment]
I head this was reported to bugzilla but it hasn't been fixed for a year
