### ISSUE TITLE
[Bug]: close button in tab tray list view makes it too easy to close tab by accident and removes useful information 

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#21654]
Steps:
Set the tab tray to list view 
Open a lot of tabs 
Open tab tray 
Scroll on the right edge of the screen 

Actual behaviour:
Tab can close when button is tapped during scroll by accident
Site information is lost due to the presence of close button
Close button is redundant with more natural and less cluttering swiping method

Expected behaviour :
No tab should close by accident (even if there is a undo button). 
Also, precious information is lost because of the close button instead of extending displayed site title information 
Closing is done quite naturally by swiping as in many other applications

Thank you!

With Firefox 94 on Redmi Note 7 with Android 9

**Comment by jonalmeida** [comment]
I'm having a tough time reproducing this behaviour. When scrolling down the list the tap-and-drag motion event isn't passed down to the close button.

Could you possibly grab a video of this bug?

**Comment by klint** [comment]
Hi. Actually it is not a bug per se, I should have expressed it differently. Scrolling itself does not close the tab. It is more an annoying possibility to close a tab because there is an accessible button. Compared to before where a active gesture of swiping was needed.
Actually, like other users who have expressed themselves in github, I am using the tab tray in list view as my main management mechanism for site management. I don't use bookmarks, I don't use history, I don't use top sites, just the very efficient tab tray. But this means that the tray contents should be stable (no button to close, only swiping) and should also display as much site info as possible (instead of the close button). 
And last, the tray should be beautiful visually, which is not the case anymore with the column of crosses on the right hand 😉. 
Which applications show a close button in addition to swiping? I don't see any (I don't know what chrome or edge look like). 
Not sure I will change your mind though as the close button has already made it to beta. But that's was  step back in tab tray management. 
Or... Could there be a setting to remove those buttons, at least ? 😊 
I wonder what the telemetry says about this button...

**Comment by jonalmeida** [comment]
> Scrolling itself does not close the tab. It is more an annoying possibility to close a tab because there is an accessible button. Compared to before where a active gesture of swiping was needed.

Sorry, it's still not clear to me what you are referring to. What is the "accessible button"? Swipe-to-delete was always an _optional_ way to delete a tab, it was never needed, so this part is confusing: "Compared to before where a active gesture of swiping was needed."

**Comment by klint** [comment]
It's not clear to you.... because I'm quite stupid and I must apologize for wasting your time like this. I don't know why but I convinced myself that the close button on the tabs in list view was a new feature. Which it is absolutely not, silly me! 😊. And I was trying to prove that it was a regression in usability and information density in the tray.
So, sorry again. I'll close the ticket.
