### ISSUE TITLE
[Bug]: Add login not available in settings

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/fenix#21666]
### Steps to reproduce

1. Open Saved Credentials
2. Only the list of saved credentials appears, there's no trace of "Add login"

### Expected behaviour

"Add login" should be available in the section, I assume on top of existing credentials.

### Actual behaviour

If I tap an existing credential, then go back, I can briefly see the command flashing (maybe half a second), while all the other credentials are missing. I can even tap it if I'm fast enough, which brings me to the form to manually add a new login.

### Device name

OnePlus 6T

### Android version

10

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (2021-09-30)

**Comment by michrogit** [comment]
Same behavior on Motorola moto x4.
Android version: 9
Firefox Nightly version 94.0a1 (2021-10-02)  
Firefox Beta version 93.0.0-beta.5 (2021-09-23)

**Comment by mayankagarwal09** [comment]
@flodolo Is it same as #21714 ?

**Comment by flodolo** [comment]
It is, but it would work the other way around (this bug is 4 days old, that's a dupe of this one)

**Comment by amedyne** [comment]
This is fixed now. See instructions https://support.mozilla.org/en-US/kb/logins-sync-autofill-saving-firefox-preview#w_manually-add-saved-logins
