### ISSUE TITLE
Why is this cert invalid?

### ISSUE THREAD

**Issue by a1291762** [mozilla-mobile/fenix#21664]
Firefox 92.1.1 on Android 11 (Pixel 4a) is refusing to open https://ib.heritage.com.au/IB/Login.aspx due to a certificate issue.

I tried a few other browsers...

Firefox focus also rejects it.
Edge allows it.
Chrome allows it.

I can't get Firefox to tell me why it is rejecting the certificate, it only says "because its certificate issuer is unknown, the certificate is self-signed or the server is not sending the correct intermediate certificates".

Firefox 92 on macOS allows me to access the site.

**Comment by kbrosnan** [comment]
Incomplete certificate chain. https://www.ssllabs.com/ssltest/analyze.html?d=ib.heritage.com.au The owners of the website need to install the intermediate certificate.

bz-1520297 exists to preload all the known intermediates

Closing as invalid/duplicate
