### ISSUE TITLE
FNX-506 ⁃ Reload a page without tracking protection

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2166]
Often one stumbles upon web content that is content blocked breaking functionality. Other browsers including Safari on iOS include 'Reload Without Content Blockers' to temporarily work-around breakage. We should offer the same functionality. A one time non-persistent reload of a page without tracking protection enabled (via long tap hold on the fresh icon).

**Comment by yoasif** [comment]
The way it works in Safari is to tap and hold the reload button: https://gizmodo.com/theres-an-easy-way-to-quickly-disable-ios-9s-content-bl-1733327070

**Comment by kbrosnan** [comment]
Tapping the lock icon in the address bar allows the user to quickly disable tracking protection. I believe there is a bug to add the tracking protection shield but I can't find it atm.

**Comment by vesta0** [comment]
Would love UX feedback on a creative solution for this.

**Comment by adamopenweb** [comment]
As a new user of Fenix, it took a while to discover the position of the disable Tracking Protection button. Since TP is known to break pages, it's possible users are running into issues and reporting a higher number of invalid Webcompat issues due to it. (I can look into when back from PTO)

**Comment by vesta0** [comment]
We may want to have an "unbreak this page" button somewhere visible depending on what the designs in #3901  look like.

**Comment by lime124** [comment]
removing the ux label - this is on our radar already as it's part of Q3 plans.

**Comment by liuche** [comment]
Going to close this now that we have #6375 ETP Discovery & Education
