### ISSUE TITLE
Bug : "customize homage" button does not always appear on home page 

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#21662]
Go to customize home page settings
Uncheck all components of the home page there
Return to home page
Collections and pinned sites remain.
But no customize home page button anymore.
Ff94 last nightly build.

**Comment by Amejia481** [comment]
👋🏽 @klint,
Thanks for filing this ticket. This is the expected behavior as the "customize home" button only shows when one of the following sections like Jump back in, Recent bookmarks, Recent searches or pocket is available. I'm closing this for now, but please feel free to re-open if needed.
