### ISSUE TITLE
[Bug]: font size problem awesome bar 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#21673]
### Steps to reproduce

after the new compose for nighlty awesome bar I m no longer able to increase font size for bookmarks /history /serach suggestions from awesome bar).
I used to manually build from github and edit dimens. xml since I m very Short sighted now I can get bigger font size for the fenix ui except bookmarks /history /serach suggestions for when tapping awesome bar. 
can please tell where are now locateted font size for those elements? 
thank you very much 

### Expected behaviour

bigger font size for bookmarks /history /serach suggestions 

### Actual behaviour

very small font size for bookmarks /history /serach suggestions after tapping awesome bar 

### Device name

mi 10

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

94

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18151)

**Comment by ale82to** [comment]
thank you for explaining I do build fenix myself from github but I cannot find suggestion.kt I don't think android component are available to edit following github instruction, right?

**Comment by amedyne** [comment]
@ale82to Apologies for the super late response. If you still need instructions in modifying and building android-components, you can find them[ here](https://github.com/mozilla-mobile/android-components#building).
