### ISSUE TITLE
[Foxfooding Bug]: "Jump back in" section on home is hidden

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#21678]
### Steps to reproduce

1 - I type the address of a website (mozfr.org) - step 1
2 - I do previous - Step 1
3 - the home screen is empty - Step 2
4 - I type another website - Step 3
5 - I press the home button - Step 4
6 - the home page screen is empty - Step 5

### Expected behaviour

I need to see the screen "Jump back in" section on home

### Actual behaviour

see the picture, I don't see the part
Under Android 11, it works

### Device name

Android 1

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

94.0

### Additional information

![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/52a0c72f-68c5-45fb-8b18-6d4d2cd63c43.png)
[Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/52a0c72f-68c5-45fb-8b18-6d4d2cd63c43.png)

**Comment by Amejia481** [comment]
@amedyne could you share a screen-shot of your "Customize" settings page, `Setttings` -> `Customize` -> `Home`? :)

**Comment by amedyne** [comment]
@Amejia481 I asked thru the foxfooding ticket if we can get this from the reporter.
