### ISSUE TITLE
Do not display Recently Closed under Inactive tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#21671]
JIRA: https://mozilla-hub.atlassian.net/browse/FNXV2-18107

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (95.0a1 - 2021-10-06T05:11:35.245780) and on the latest Beta 94.0.0 beta1.

Devices used:

Samsung Galaxy Tab S3 (Android 9).
Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
