### ISSUE TITLE
[Bug]: Desktop Mode stops working after tab is unloaded from memory and reloaded

### ISSUE THREAD

**Issue by eberhardweber** [mozilla-mobile/fenix#21675]
### Steps to reproduce

1. Open a website
2. Set "Desktop Mode" on
3. Wait for tab to be unloaded (i.e. switch away and back to app after a while to force a reload)
4. Tab reloads, but no longer remains in desktop mode, yet the "Desktop Mode" switch remains set to "on"
5. "Desktop Mode" switch can no longer be set either "off" or "on"
6. Reloading the website does nothing, remains rendered in "mobile" view, "Desktop Mode" switch does nothing

### Expected behaviour

"Desktop Mode" functionality, both in the UI and for the open website, should work properly.

### Actual behaviour

"Desktop Mode" stops working and loses UI functionality after a window is unloaded and reloaded.

### Device name

Samsung Galaxy Tab S 

### Android version

Android 7.1.2.

### Firefox release type

Firefox

### Firefox version

92.1.1 (Build #921100)

### Additional information

Also see bug #2091

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/11552
