### ISSUE TITLE
Remove ads

### ISSUE THREAD

**Issue by trustwalletvn** [mozilla-mobile/fenix#21676]
Hello
Can I build firefox without ads or remove ads content?
Like as google ads or facebook ads..
How to do this?
Thank you

**Comment by cadeyrn** [comment]
There is already uBlock Origin for blocking ads. Just open the add-ons manager in Firefox, it's a "one click installation".

**Comment by kbrosnan** [comment]
Not a bug

**Comment by trustwalletvn** [comment]
> Not a bug

Yes.
I understand this is not bug.
I'm need to build firefox with remove ads
Please give me some guide 
Thank
