### ISSUE TITLE
Pocket recommended stories: Tests

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#21680]
We should ensure proper testing of all composables used for this feature.

**Comment by sheikh-azharuddin** [comment]
I see some commits related to pocket stories...how to enable the feature?

**Comment by Mugurell** [comment]
> I see some commits related to pocket stories...how to enable the feature?
There should already be a "Though-provoking stories" section on Nightly's homescreen.

**Comment by sheikh-azharuddin** [comment]
> > I see some commits related to pocket stories...how to enable the feature?
> 
> There should already be a "Though-provoking stories" section on Nightly's homescreen.

But this is not visible for me..
Rog3 android 11

![Screenshot_20211005-132026468](https://user-images.githubusercontent.com/58127841/135982314-9bd9d381-2945-4647-bfb3-901c4bcee551.jpg)

**Comment by Mugurell** [comment]
> > > I see some commits related to pocket stories...how to enable the feature?
> > 
> > 
> > There should already be a "Though-provoking stories" section on Nightly's homescreen.
> 
> But this is not visible for me.. Rog3 android 11

Only to en-US users, only if enabled in the customization settings.
Please open a new ticket if this conditions are met and and the section does not appear on the homescreen.

**Comment by sheikh-azharuddin** [comment]
> > > > I see some commits related to pocket stories...how to enable the feature?
> > > 
> > > 
> > > There should already be a "Though-provoking stories" section on Nightly's homescreen.
> > 
> > 
> > But this is not visible for me.. Rog3 android 11
> 
> Only to en-US users, only if enabled in the customization settings. Please open a new ticket if this conditions are met and the section does not appear on the homescreen.

After changing the launguage to English US , I got pocket stories
I am from india
