### ISSUE TITLE
[Bug]: No video can be played during a phone call

### ISSUE THREAD

**Issue by darkman088** [mozilla-mobile/fenix#21681]
### Steps to reproduce

1. Start a phone call
2. Open some webpage with videos, like youtube.com
3. Try to play a video
4. You can observe, that the video playback does not start !!!

This is a HUGE disappointment, because this used to work in previous Firefox versions!
So I am rolling back to my previous Firefox version, until this has been fixed!

Many thanks for taking care about this very annoying bug with high priority!

### Expected behaviour

The video playback starts

### Actual behaviour

No video playback starts. Eventually, half a second is being played and then the video stops immediately!

### Device name

Xiaomi Mi 9T

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

92.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18158)

**Comment by jamienicol** [comment]
I can reproduce this on a range of devices, but only in Fenix. I cannot reproduce in geckoview_example or samples-browser. I think it's most likely this is therefore a Fenix (or Android Components) bug.

My brief investigation showed that MediaSession.pause() is continually getting called, and I could also see mentions of AudioFocus in the logcat. Which points me to here as a first guess: https://searchfox.org/mozilla-mobile/rev/ec8d108e4475517178d2edd0ca3e64530cb13286/android-components/components/feature/media/src/main/java/mozilla/components/feature/media/focus/AudioFocus.kt#63

@kbrosnan I've closed the bug on bmo, could you reopen this one please?
