### ISSUE TITLE
FNX-5493 ⁃ [Bug] Fenix crashes when changing the default search engine on a clean install

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2168]
## Steps to reproduce
Uninstall Fenix
Install it again
Open Fenix
Change de default user agent from Google to DDG

### Expected behavior
The search engine is changed without any crash.

### Actual behavior
Fenix crashes, even though the search is changed.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1918

**Comment by yoasif** [comment]
I was able to reproduce this on a Pixel 2 - you don't need to use a fresh install.

**Comment by ekager** [comment]
> 2019-04-30 10:21:29.211 18765-18765/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.mozilla.fenix.debug, PID: 18765
>     java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
>         at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:326)
>         at org.mozilla.fenix.settings.SettingsFragment$onCreate$1.onSharedPreferenceChanged(SettingsFragment.kt:70)
>         at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
>         at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:489)
>         at org.mozilla.fenix.utils.Settings.setDefaultSearchEngineByName(Settings.kt:117)
>         at org.mozilla.fenix.settings.RadioSearchEngineListPreference.onCheckedChanged(RadioSearchEngineListPreference.kt:50)
>         at android.widget.RadioGroup.setCheckedId(RadioGroup.java:190)
>         at android.widget.RadioGroup.access$600(RadioGroup.java:57)
>         at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:375)
>         at android.widget.CompoundButton.setChecked(CompoundButton.java:174)
>         at android.widget.CompoundButton.toggle(CompoundButton.java:127)
>         at android.widget.RadioButton.toggle(RadioButton.java:76)
>         at android.widget.CompoundButton.performClick(CompoundButton.java:132)
>         at android.view.View.performClickInternal(View.java:6574)
>         at android.view.View.access$3100(View.java:778)
>         at android.view.View$PerformClick.run(View.java:25885)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)

**Comment by Amejia481** [comment]
Related : https://github.com/mozilla-mobile/fenix/issues/2170

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/6 build.
