### ISSUE TITLE
[Bug]: Tab Group - an ungrouped Search tab always stays at the bottom of the tab list

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#21692]
### Steps to reproduce

Switch to Grid view for tabs (probably also true for List view but I haven't checked)
Open a tab and search for something eg "cat"
(Do not open any links from the "cat" search so it is a normal tab not a group)
The "cat" search tab is last in the tab list
-> correct behavior
Open another tab and navigate to a normal site eg mozilla.org
Go to the tabs tray
The "cat" search tab is still last in the tab list
-> incorrect behavior, the last tab should be mozilla.org since it is the most recently opened

### Expected behaviour

The "cat" search tab should behave like any other tab since it is not a group, so more recently opened tabs should come after it in the list

### Actual behaviour

The "cat" search tab remains the last tab in the list even when I open newer tabs

### Device name

Galaxy A40

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Today's

**Comment by rocketsroger** [comment]
This should be fixed once https://github.com/mozilla-mobile/fenix/issues/22550 is fixed.

**Comment by rocketsroger** [comment]
Confirmed that this is now fixed in nightly
