### ISSUE TITLE
Tab Groups: changing to a more Chrome-like group might bring advantages

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#21693]
### What is the user problem or growth opportunity you want to see solved?
Current tab auto-group is a useful idea but it caused much wailing eg #21360. I think this is because the "ribbon" style group with horizontal scrolling occupies two "slots" in the tab tray, thus the move from a single tab (search) to a group (open a search result in a new tab) always changes the tab ordering in the tab tray.  For example at the moment the group moves to the top of the list and displaces other tabs down the list. The movement up and displacement down of other tabs can be annoying.   In "List" view it can be even more annoying because there is no ribbon scrolling, pre-existing tabs get displaced down further and further as more search results are opened

My suggestion would be to make an auto-tab group much more like a single tab, the transition from a single tab to a group then does not displace the tabs tray

eg in the diagram, (1) search for "cat". It's a normal tab. (2) open a link in a new tab, the "cat" search becomes a tab group BUT does not change its size or position in the tab list. Its icon makes it clear that it's a group, there are mini-tabs inside it. (3) tap the tab list to go into it and see the tabs. There is a strong animation and clear visual clues that you're inside the group, eg the group roundrect still appears, the title bar and the X to close. Maybe even a grayed-out background of the other tabs. Scroll within the group.

This is how Android Home screen handles groups of apps (on Samsung OneUI at least, I guess stock Android is similar). It's quite intuitive.

Advantages
- no jarring transition/displacements of tab list when moving from single tab to tab group
- compatibility with manual tab groups which I hope are on the way
- drag and drop a tab group just like a normal tab
- works for list view as well as grid,

Disadvantages
- how to tell the user of a transition from tab to group, eg if user uses the toast message to move to a link opened in a new tab, they will move into the newly created group which could cause confusion
- it's no longer "flat", have to navigate into and out of the group with a tap.

[Group.pdf](https://github.com/mozilla-mobile/fenix/files/7280184/Group.pdf)

### How do you know that this problem exists today? Why is this important?

#21360

### Who will benefit from it?

Users who complained in #21360, maybe others too :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18164)

**Comment by pocmo** [comment]
Thank you for this feedback and suggestion, @Cheap-Skate.

I turned your PDF into an image, so that we can add it to this issue directly:
<img width="913" alt="tab groups proposal" src="https://user-images.githubusercontent.com/89638/135985849-052d668b-5dc6-4bb7-926f-3c44f7bc696c.png">

**Comment by amedyne** [comment]
Tagging @topotropic for UX feedback.

**Comment by jonalmeida** [comment]
Closing as won't fix as this feature has been removed until it's re-worked.
