### ISSUE TITLE
[Bug]: Missing lower gray brorder for inactive tabs

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#21708]
### Steps to reproduce

1. Have at least 1 inactive tab in the inactive tabs section of the tabsTray ( can be achieved by having secret options enabled and using multi-select mode on several tabs + contextual tabs tray menu to make them inactive)
2. Open 8-15 tabs ( so they don't fit on one page)
3. Collapse inactive tabs section
4. Close tabs tray and re-open it

### Expected behaviour

The collapsed inactive tabs tray should have a gray border at the bottom.

<img src="https://user-images.githubusercontent.com/60002907/136017969-de4e00f6-64c2-44a0-ab56-2794ba4b1df0.png" width="300"/>

### Actual behaviour

<img src="https://user-images.githubusercontent.com/60002907/136017579-0dda440d-6206-4ce6-be30-262344725dfb.png" width="300"/>

### Device name

Google Pixel 4

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest master

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (95.0a1 - 2021-10-06T05:11:35.245780) and on the latest Beta 94.0.0 beta1.

Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Xiaomi Redmi 11 Lite (Android 11).

Closing the ticket as verified.
