### ISSUE TITLE
FNX-5495 ⁃ [Bug] Changing site permissions crashes Fenix

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2170]
## Steps to reproduce
Settings - site permissions - notifications - change the setting

### Expected behavior
The setting is changed and no crash is expected

### Actual behavior
The setting is changed but the browser also crashes.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1918

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/6 build.
