### ISSUE TITLE
Implement error handling for manual Add Login screen

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#21702]
Settings -> Logins and passwords -> Saved logins -> Add login

Confirm the following error handling exists/implement it: 

**Hostname**
* must contain "https://" or "http://"
* may not be blank
* must be a valid url (can't be something like "http://gggg")
* may not be blank

**Username**
* N/A
* **Can** be blank

**Password**
* May not be blank

<img width="234" alt="image" src="https://user-images.githubusercontent.com/43795363/135922492-5bb575bf-d0a4-40d4-a7fb-c7952d25b22d.png">

**Notes**
* When the Add login screen is first shown and all fields are empty, there should be no red error text
* Once the user begins typing/navigates between fields, error text should be shown
* The save button should not be enabled if there are any errors

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18170)

**Comment by surajeet310** [comment]
Is it still open ? Can I work on it ?

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 106.0a1 (2022-08-31). A login cannot be saved without entering a valid username. I did encounter a issue where a login cannot be saved without entering a username, I submitted a new issue regarding this: https://github.com/mozilla-mobile/fenix/issues/26736
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 (Android 12)
