### ISSUE TITLE
[Bug]: If the only tabs are a search group, "Other tabs" erroneously appears under the group, even though there are no other tabs

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#21712]
### Steps to reproduce

close all tabs
open a tab & search, eg "cat"
from the "cat" search, long press a link and open it in a new tab
go to the tab tray
"Cat" search is correctly labelled but there is "Other tabs" under it even though there are no other tabs
![Screenshot_20211005-145241_Firefox Nightly](https://user-images.githubusercontent.com/40568887/136037495-bfc385e6-09da-474f-9ceb-0ee0144f55ee.jpg)

### Expected behaviour

"Other tabs" should not appear since the "Other tabs" group is empty

### Actual behaviour

"Other tabs" text appears

### Device name

Galaxy A40

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Today's

**Comment by jonalmeida** [comment]
It's not possible to tell which build you have from "Today's", but this bug was already fixed in https://github.com/mozilla-mobile/fenix/pull/21663.

Closing, but re-open if you're able to see it newer builds.
