### ISSUE TITLE
[Bug]: Inactive tabs CFR does not always point to the inactive tabs section.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#21716]
### Steps to reproduce

1. Have many tabs in the tray.
2. Ensure that you haven't had inactive tabs before and the feature is enable.
3. Ensure the selected tab is at the bottom of the list (far away from inactive tabs).
3. Open the tabs tray.

### Expected behaviour

The CFR should be anchored to the inactive tabs section.

### Actual behaviour

The CFR is anchored to the _visual_ top of the tray but is not anchored to the inactive tabs, so we do not know what it is referencing. See screenshot below.

### Device name

All devices

### Android version

All versions

### Firefox release type

Firefox Nightly

### Firefox version

main @ 8a8bbd951

### Additional information

<img width="462" alt="Screen Shot 2021-10-05 at 2 22 37 PM" src="https://user-images.githubusercontent.com/1370580/136081692-67e5618a-0e54-4641-bfa9-4d6b91f2ba1a.png">

**Comment by eliserichards** [comment]
Tagging for QA to see if y'all can figure out the STR :/

**Comment by SoftVision-LorandJanos** [comment]
As inactive tabs section was moved to only the top of the tabs tray, according to #21319, this issue is no longer reproducible.
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.
