### ISSUE TITLE
[Bug] The "Jump back in" Contextual Hint is not displayed.

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#21736]
### Steps to reproduce

1. Perform a fresh install of Firefox Preview;
2. Launch Firefox;
3. Open a webpage;
4. Navigate to home screen;
5. Go to Setting-Tabs and set "Start on home" to Always;
6. Relaunch Firefox Preview.

### Expected behaviour

The "Jump back in" Contextual Hint should be displayed the 1st time users start on home after a new install.

### Actual behaviour

The "Jump back in" Contextual Hint is not displayed.

### Device name

Oppo Find X3 Neo

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

94.0.0-beta.1

**Comment by Amejia481** [comment]
👋🏽  @LaurentiuApahideanSV thanks for file the ticket. Does the "Jump back in" section is shown in the home screen?

**Comment by Amejia481** [comment]
Recently we disabled the **"What's new in firefox"** [dialog](https://github.com/mozilla-mobile/fenix/pull/21737), it should be on the branch [releases_v94.0.0 ](https://github.com/mozilla-mobile/fenix/tree/releases_v94.0.0), it looks like the build doesn't have the change. Now we are only showing the **"Jump back in"** Contextual Hint dialog. This section is hidden by default, unless it's activated by an [experiment](https://mozilla-hub.atlassian.net/browse/QA-1204), to be able to see it you have to got to `Settings` -> `Customize` -> `Home`, and toggle the **"Jump back in"** switch it's shown in the **working.mp4** video.

**Comment by LaurentiuApahideanSV** [comment]
Because the "What's new in firefox" dialog has been disabled I will close this issue. Once it will be enabled we will retest it.
