### ISSUE TITLE
URL bar is sometimes too small on narrow screens 

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#21742]
### Steps to reproduce

Open Firefox on a narrow screen (e.g., Samsung Fold 3 cover screen).

### Expected behaviour

The URL bar should be big enough to tap on.

### Actual behaviour

Unable to tap on url bar.  I'm not sure why, but sometimes the buttons to the left are hidden and there is enough room.  Maybe it doesn't always detect the change I'm screen size when switching between main and cover screen? 
![Screenshot_20211006-112902_Firefox Nightly](https://user-images.githubusercontent.com/22622548/136245781-d8564d9d-5db2-4ac2-a98f-640c2a8f3657.jpg)

### Device name

Samsung Fold 3

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

94a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18198)

**Comment by robsmith11** [comment]
It's not stale, just being ignored.

**Comment by robsmith11** [comment]
> It's not stale, just being ignored.

Still this 🙄

**Comment by Dunexus** [comment]
Same as https://github.com/mozilla-mobile/fenix/issues/22519

**Comment by robsmith11** [comment]
This isn't completed.  Fix your bot.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813844

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
