### ISSUE TITLE
Replace deprecated InputMethodManager.toggleSoftInput()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#21744]
Follow-up from: https://github.com/mozilla-mobile/fenix/pull/21738

`InputMethodManager.toggleSoftInput()` is deprecated in the Android 12 SDK.

> Use showSoftInput(android.view.View, int) or hideSoftInputFromWindow(android.os.IBinder, int) explicitly instead. In particular during focus changes, the current visibility of the IME is not well defined. Starting in Android S, this only has an effect if the calling app is the current IME focus. 

https://github.com/mozilla-mobile/fenix/blob/0b6e67a21b28b1d4fbf7b2ec92d1cd1b35a684f3/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt#L451-L452

https://github.com/mozilla-mobile/fenix/blob/0b6e67a21b28b1d4fbf7b2ec92d1cd1b35a684f3/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt#L112-L113

**Comment by mcarare** [comment]
For QA: Please test for any behavior changes in:
- the add login fragment (the keyboard should pop up when the screen is displayed in order to start typing. )
- the search fragment (the keyboard should be dismissed when the fragment is closed. )

Thank you!

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Preview 2022-01-18. The keyboard is dismissed after a search is performed, or is canceled. The keyboard does pop up when trying to manually add login but I did find one issue: https://github.com/mozilla-mobile/fenix/issues/23272.

### Device used:
- Google Pixel 6 (Android 12)
