### ISSUE TITLE
Replace deprecated Patterns.IP_ADDRESS 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#21743]
Follow-up from: https://github.com/mozilla-mobile/fenix/pull/21738

`Patterns.IP_ADDRESS` is deprecated in the Android 12 SDK.

> Please use InetAddresses.isNumericAddress(String) instead. 
> Kept for backward compatibility reasons. It does not match IPv6 addresses.

In our case that may just be okay and we could just suppress indefinitely?

https://github.com/mozilla-mobile/fenix/blob/0b6e67a21b28b1d4fbf7b2ec92d1cd1b35a684f3/app/src/main/java/org/mozilla/fenix/ext/String.kt#L83-L85

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/23859.

**Comment by Amejia481** [comment]
🎉 !
