### ISSUE TITLE
FNX-5497 ⁃ [Implementation review] App Menu - Icons should be vertically centered in the bottom row

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2175]
Icons should be vertically centered in the bottom row in the app menu (see screenshot)
![](https://user-images.githubusercontent.com/5992746/56982225-d237bc80-6b4e-11e9-8338-c7fedad6c56d.png)

**Comment by Lululalu** [comment]
@AmyYLee the text is also not horizontally centralized at the top and bottom of the 3-dots menus.

Example:

**Comment by pocmo** [comment]
They kind of are. But the menus have a top and bottom padding:
https://material.io/design/components/menus.html#specs

**Comment by ekager** [comment]
CC @topotropic for UX feedback. Should we continue to follow the material design spec linked above with padding in our menus?

**Comment by topotropic** [comment]
@ekager Yes, let's follow the guidelines. Amy also specified issues in https://github.com/mozilla-mobile/fenix/issues/2203. Thanks!

**Comment by mheubusch** [comment]
Actually, per @shorlander please follow  the  designs specs provided by Amy above.

**Comment by bogas04** [comment]
Also it would be nice if the separator aligns with the URL bar's border-top.

**Comment by sblatz** [comment]
Closing this as it's now tracked in the checklist of https://github.com/mozilla-mobile/fenix/issues/2203
