### ISSUE TITLE
[Bug]: The info panel doesn't always display the ETP details on some social media websites 

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#21768]
### Steps to reproduce

1. Load twitter.com, or instagram.com, or facebook.com, and login with valid credentials.
2. Let the page fully load, then tap on the lock icon.
3. From the ETP section, tap on the "Details" option from the lower right corner.

### Expected behaviour

The "Details" section is visible, and can be accessed.

### Actual behaviour

There is no "Details" option under the ETP section from the info panel. 
Reloading the page sometimes fixes this.

### Device name

Samsung Galaxy Tab A6 (Android 5.1.1)
NOT reproducible on Google Pixel (Android 10)

### Android version

5.1.1

### Firefox release type

Firefox Beta

### Firefox version

94.0.0-beta.1

### Additional information

https://user-images.githubusercontent.com/40694158/136385108-c57008fc-46b7-44a3-b09a-ac123b36d7b4.mp4

**Comment by Amejia481** [comment]
The details page is only visible when we get trackers blocked otherwise it's hidden.
