### ISSUE TITLE
[Bug]: “Thought-provoking stories” is wrongly enabled by default in Firefox Beta 94 for English-US

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [mozilla-mobile/fenix#21765]
### Steps to reproduce

**[Prerequisites]:**
- Have the system language-region be set to English - United States.
- Have Firefox Beta 94.0.0-beta.1 installed.

**[Steps to reproduce]:**
1. Open the app.
2. Tap “Start browsing”.
3. Navigate to a website.
4. Tap the homepage button.
5. Tap “Start browsing” and observe the homepage.

### Expected behaviour

- The “Thought-provoking stories” section is not displayed by default on the homepage.

### Actual behaviour

- The “Thought-provoking stories” section is displayed by default on the homepage.

### Device name

Samsung Galaxy S8, Huawei P20 Lite, Oneplus 6

### Android version

Android 9, Android 8, Android 10

### Firefox release type

Firefox Beta

### Firefox version

94.0.0-beta1 (Build #2015838099)

### Additional information

- This issue was not reproducible for other system language-region combinations tested(e.g. French-France, Spanish-US, English-Canada), where the second onboarding was also not displayed.
- The option also appears enabled from Setting > Customize - Home.
- The Settings > Data collection > Studies section does not display any study as active.
- Attached is a recording of the issue.
![pocket by default](https://user-images.githubusercontent.com/53752296/136349411-7822f24c-374f-4e10-a87a-41f0aa52ccd0.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18213)

**Comment by Amejia481** [comment]
@heres-maria Thanks for filing this, I'll take a look and report back.
