### ISSUE TITLE
[Bug]: Html5 "required" no longer shows a popup window with message.

### ISSUE THREAD

**Issue by Hiplobbe** [mozilla-mobile/fenix#21762]
### Steps to reproduce

1. Open a form with html5 validation
2. Leave field without value
3. Press submit 

### Expected behaviour

Should be the same as in the desktop app, that a popup window with the wanted error message shows up.

### Actual behaviour

No popup is shown, giving no information to the user.

### Device name

Samsung S8

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1

**Comment by makotokato** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1510450

**Comment by kbrosnan** [comment]
Closing as upstream. @pjs6747 this would require modifying Gecko see https://firefox-source-docs.mozilla.org/mobile/android/geckoview/contributor/index.html
