### ISSUE TITLE
[Bug]: Customize homepage button and menu entry still lead to Customize instead of Homepage settings

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#21773]
### Steps to reproduce

Click on Customize homepage button or menu entry

### Expected behaviour

Should lead you to the new Homepage settings

### Actual behaviour

Leads you to the Customize settings 

### Device name

Redmi Note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

95a1

**Comment by amedyne** [comment]
@klint Can you test this with [94 Beta 1 ](https://github.com/mozilla-mobile/fenix/releases/tag/v94.0.0-beta.1)

**Comment by klint** [comment]
I can confirm that it has been corrected in FF 95a1. I have no access to 94b1 to test it there, though.
Thanks

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-10-19.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
