### ISSUE TITLE
[Bug]: "Search groups" break chronological order of tabs in the tab list

### ISSUE THREAD

**Issue by dialmove** [mozilla-mobile/fenix#21777]
### Steps to reproduce

Opening links in new tabs from a search page now has several unexpected behavior in their relative positions and messes up with the vertical scroll position:

1. Scroll to a tab "T" in the middle of the tabs list and open it. It shows a visited page "P".
2. Click on the address bar and type a search term. It opens search page S in tab T. (Page P is placed as the previous page in the tab history list).
3. Long-press several links and open them in new tabs. This open pages S1, S2, S3...
4. Click the "Show tabs" icon. The tab T opened in step 1 is no longer placed in the same relative position of the tab list, and the view has been scrolled far away from the point in the list were it was previously placed.
5. Select again the same tab containing page S, and navigate back to the page P.
6. Click the "Show tabs" icon. The tab T is again shown in the relative point where it was located in step 1, but tabs with pages S1, S2, S3 are nowhere to be seen.
7. Select tab T. Swipe left on the address bar to change tab. This opens page S1 (even though it was not the page that was being shown below tab T on the tabs list).
8. Click the "Show tabs" icon. The view has been scrolled again far away from the point in the list where it was placed, and it now shows pages S1, S2, S3... but now tab T is nowhere to be seen.

### Expected behaviour

- The relative order of tabs shown on the tab list should always correspond to the tab order found when swiping the address bar left and right.

- Tabs should not be automatically moved from the point where they are created, except when the user drags them to a different place. Any pair of tabs should always keep the same relative order (a tab A further up in the list with respect to tab B should never be relocated to a position where it is now below tab B).

- The view in the tab list should never be automatically scrolled away from the vertical position of the current open tab (except when pressing the + new tab button, which scrolls all the way to the bottom).

- Search groups should be placed at the point in the list where the tab with the search page was located when creating the group, not at a different place at the top of the list.

- Ideally, tab groups should also be created when opening links in new tabs from any page, not only from a page with search results.

I have a navigation workflow strongly dependent on having tabs kept in the same relative place at all times. This ingrained workflow has been conditioned from years of the browser keeping a stable tab order. I've been relying on this invariant since the browser was still codenamed Fennec; so I would regretfully abandon the browser it in a heartbeat if the tabs start to jump around out of my control.

### Actual behaviour

I keep a few hundreds of tabs open (since I have tab behavior configured to close one-month-old tabs). I do this so that I can visually search for tabs that I opened in the few past days or weeks simply by scrolling up; thanks to the tabs being kept in order, I know I can rely on muscle memory and relative space orientation to find them. 

I also strongly rely on the scroll list being opened at the precise point of the current tab, which is needed to navigate to tabs that were open from the current one (as well as the tabs I was browsing prior to that but not opened as "open link as new tab"), keeping all them in the same sequence I opened them.

Activating "Search groups" breaks both conditions, and messes up my workflow conditioned by several years of usage of the Firefox browser. In the latest Fenix version, I am now afraid to open links in new tabs lest I lose the relative position in the vertical list of tabs from the page I am browsing.

Also now I often lose track of the groups of related tabs that I have manually created to read them in order (from the same page or at some earlier point from another page), as the tab view scrolls all the way to the top to show a search group, so I lose any other tab that previously was locally close to the active group.

Since I enabled Search groups, I've found myself being often forcibly scrolled all the way up to the "Search groups" section, losing the place with the other related tabs I was browsing before. Finding that point again now takes about one or two minutes of scrolling down. 

(In the past I would have used draggable scroll bars to quickly scroll down, to the estimated known fraction of the list size where I know the tab was located; but since draggable scroll bars went out of fashion I'm forced to rely on the horrible "_throw the screen upwards at full speed a lot of times, until you are close to the region you are interested in_" that is the current browsing style on mobile for long lists). Google's Chrome is also guilty of this, but they at least now group tabs together from the page with the originating links, so at least it's easier to keep a manageable number of groups in the tab list.

### Device name

Samsung Galaxy S20+

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 (Build #2015838315) 2021-10-07

### Additional information

Going back all the way down can take one or two minutes from here:

![2021_10_07_19_19_16_68bbd7c7_54c2_41f9_b2d6_b02657b053fd_921_2048_](https://user-images.githubusercontent.com/3824360/136433148-02263ef4-532c-4dee-bdcd-4e5b33d30659.png)

I'd expect these groups to show in the middle of the list, not at a separate section at the top:

![2021-10-07 19_23_25-72b99128-ef1f-40fd-b67f-0f788ad20e66 (921×2048)](https://user-images.githubusercontent.com/3824360/136433684-6828e527-2e77-4843-9534-2ddb753f42fc.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18223)

**Comment by robsmith11** [comment]
This new tab ordering is extremely annoying when one has 100+ tabs open.   Multiple times a day I will end up with a tab getting inserted into the stack in a non-chronological order and then have to painstakingly scroll through all the tabs looking for the last one I was using.
