### ISSUE TITLE
[Bug]: “Jump back in” cards do not always have titles

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [mozilla-mobile/fenix#21771]
### Steps to reproduce

**[Prerequisites]:**
- Have Firefox Beta 94.0.0-beta.1 installed and opened.
- Have the “Jump back in” section enabled.

**[Steps to reproduce]:**
1. Make a single search using a search engine other than Google (e.g. DuckDuckGo).
2. Tap the Home button.
3. Observe the “Jump back in” card created by the search.

### Expected behaviour

- The card has a title.

### Actual behaviour

- The card does not have a title.

### Device name

Samsung Galaxy S8

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

94.0.0-beta.1 (Build #2015838099, null (AC: 94.0.1) (Build #2015838387)

### Additional information

- This issue is reproducible for both address bar search engine options as well as organic searches (e.g. a search on Reddit created a similar card)
- Attached is a recording of the issue
![no title jump back in](https://user-images.githubusercontent.com/53752296/136406571-b4266995-6275-4e59-b13b-ab61a9f8edcd.gif)
.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18220)

**Comment by jonalmeida** [comment]
We changed the check for the list of RecentTabs [here](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/home/recenttabs/RecentTabsListFeature.kt#L35), so we might be missing the title update notifications in our logic.

(or maybe this is coming from the observer in Compose UI itself?)
