### ISSUE TITLE
FNX-5499 ⁃ [Bug] Bookmark button is undiscoverable

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#2178]
It took me a long time to find a way to bookmark a page, and in the end I've stumbled into the "quick action bar" by accident. Talking to others, people are having a similarly bad experience. 

This feature is pretty much non-discoverable.

**Comment by Lululalu** [comment]
I feel the same. Everytime I want to do something my instinct is to look for it on the main menu.

**Comment by colintheshots** [comment]
The quick action bar generally seems too slim and not noticeable. It seems like there should be a handle or tab sticking up so the user knows it's there.

**Comment by grigoryk** [comment]
This isn’t specifically about the quick action bar, but rather discoverability of the “bookmark current page” functionality.

Firefox for iOS has a Page Actions menu, which works quite well for this sort of thing (but the dual-menu split poses other problems).

In general, this is a page specific action; on some level, it’s no different than “Request Desktop Site”, for example, and yet the two are in completely different places.

**Comment by vesta0** [comment]
Thanks for raising this @grigoryk . We also learned the same thing in user testing and we are redesigning the QAB behaviour in #2245
