### ISSUE TITLE
[Crash] java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#21797]
### Steps to reproduce

Some UI tests are hitting this crash:
mainMenuInstallPWATest - while opening the 3 dot menu o a webpage
testStrictVisitDisableExceptionToggle - while opening the ETP info sheet 

### Expected behaviour

The 3 dot menu, in an open tab, should open.
The ETP info sheet should open, on a web page with trackers.

### Actual behaviour

App crashes:
► Stacktrace
07-03 10:15:33.290: W/CryptauthV2(5181): --------- beginning of crash
07-03 10:15:33.303: E/AndroidRuntime(7566): FATAL EXCEPTION: FinalizerWatchdogDaemon
07-03 10:15:33.303: E/AndroidRuntime(7566): Process: org.mozilla.fenix.debug, PID: 7566
07-03 10:15:33.303: E/AndroidRuntime(7566): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at android.view.ThreadedRenderer.nDeleteProxy(Native Method)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:967)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
07-03 10:15:33.303: E/AndroidRuntime(7566): 	at java.lang.Thread.run(Thread.java:764)
07-03 10:15:33.303: E/ExceptionHandler(7566): Uncaught exception handled: 
07-03 10:15:33.303: E/ExceptionHandler(7566): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at android.view.ThreadedRenderer.nDeleteProxy(Native Method)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:967)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
07-03 10:15:33.303: E/ExceptionHandler(7566): 	at java.lang.Thread.run(Thread.java:764)
07-03 10:15:33.328: I/CryptauthV2(5181): [ReEnrollmentCryptauthFramework] Performing SyncKeysRequest with 6 keys.
07-03 10:15:33.416: I/mozac/CrashReporter(7566): Received crash: UncaughtExceptionCrash(timestamp=1625332533304, throwable=java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds, breadcrumbs=[Breadcrumb(message=onCreate(), data={recreated=false, intent=android.intent.action.MAIN, instance=256362217}, category=HomeActivity, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:00 PDT 2021), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:01 PDT 2021), Breadcrumb(message=onStart(), data={instance=256362217}, category=HomeActivity, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:01 PDT 2021), Breadcrumb(message=onResume(), data={instance=256362217}, category=HomeActivity, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:01 PDT 2021), Breadcrumb(message=Changing to fragment searchDialogFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:07 PDT 2021), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:09 PDT 2021), Breadcrumb(message=onAttach(), data={instance=179028011, activityInstance=256362217, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:09 PDT 2021), Breadcrumb(message=onCreateView(), data={customTabSessionId=null, instance=179028011, activityInstance=256362217, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Sat Jul 03 10:15:09 PDT 2021)], uuid=b5911af2-ce80-4180-8aa8-7d0e196c0da0)
07-03 10:15:33.479: E/memtrack(2077): Couldn't load memtrack module
07-03 10:15:33.479: W/android.os.Debug(2077): failed to get memory consumption info: -1
07-03 10:15:33.515: W/GLSUser(2572): [DeviceKeyStore] Cannot load key: Device key file not found.
07-03 10:15:33.578: I/ActivityManager(2077): Start proc 10308:org.mozilla.fenix.debug:crashReportingProcess/u0a95 for service org.mozilla.fenix.debug/mozilla.components.lib.crash.service.SendCrashTelemetryService
07-03 10:15:33.598: I/mozac/CrashReporter(7566): Showing prompt

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

Debug version

### Device logs

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/7310146/logcat.txt)

**Comment by AndiAJ** [comment]
### Steps to reproduce - `mainMenuInstallPWATest`
1. Open https://mozilla-mobile.github.io/testapp/
2. Verify if the dot is displayed on the ⋮ button
3. Tap the ⋮ button and open the main menu

► Video

https://user-images.githubusercontent.com/51314259/137114545-af080da1-6699-4d22-9697-6f23bd385b96.mp4

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7020774727486573930/executions/bs.43bf4e4606a71bdd/testcases/1/logs)


### Steps to reproduce - `mainMenuInstallPWATest`
1. Open https://mozilla-mobile.github.io/testapp/
2. Verify if the dot is displayed on the ⋮ button
3. Tap the ⋮ button and open the main menu
4. Tap the "Install" button

►  Video

https://user-images.githubusercontent.com/51314259/137116118-6e8cbe2d-3d0a-4a24-9bc8-dd208eaf690a.mp4

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9190559462828656854/executions/bs.87e32407510eb455/testcases/1/logs)


### Steps to reproduce - `testStrictVisitDisableExceptionToggle `
1. Open a website
2. Open the tab drawer and close the previously opened tab
3. Open https://senglehardt.com/test/trackingprotection/test_pages/fingerprinting_and_cryptomining_and_cookies.html
4. Tap the security indicator 
5. Verify if ETP is enabled
6. Disable ETP using the toggle
7. Verify if ETP is disabled
8. Tap the "Details" button
9. Tap the "Protection Settings" button

►  Video

https://user-images.githubusercontent.com/51314259/137117705-71cd3ca3-7d40-4cf0-87ef-7f390a37551c.mp4

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7385133966857513402/executions/bs.8dfe7e2e8986eec0/testcases/1/logs)
