### ISSUE TITLE
[Bug]: The Search Groups card is not displayed on the homepage while enrolled in the experiments/rollout

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-mobile/fenix#21798]
### Steps to reproduce

**[Prerequisites]:**
- Be enrolled in one of these experiments/rollout: [New user experiment](https://experimenter.services.mozilla.com/nimbus/mr2-home-screen-impact-assessment-experiment), [Upgraded user experiment](https://experimenter.services.mozilla.com/nimbus/upgraded-user-home-screen-impact-assessment-experiment), [All users Rollout](https://experimenter.services.mozilla.com/nimbus/all-users-home-screen-android)

**[Steps to reproduce]:**   
1. Open a tab and search for anything like "Apple".
2. Open a link.
3. Long tap on any link and open it in a new tab.
4. Switch to the new tab using the prompt.
5. Repeat steps 4 and 5 one more time.
6. Tap the home button from the browser toolbar.

### Expected behaviour

- A Search Group card is displayed in the "Jump Back in" section.

### Actual behaviour

- No Search Group card is displayed in the "Jump Back in" section.

### Device name

Oneplus 6

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

94.0.0-beta.1

### Additional information

Other devices that can reproduce the issue:
- Huawei P20 Lite, Android 8
- Samsung Galaxy S8, Android 9

Attached a screen recording:

https://user-images.githubusercontent.com/18304511/136533149-70b00904-8b57-46ca-b047-e50fdebf97bb.mp4

**Comment by amedyne** [comment]
This is expected on 94 Beta since there was a product decision to not enable this and the search term tab grouping.
