### ISSUE TITLE
FNX-5500 ⁃ [Meta] Site Permissions

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#218]
See https://github.com/orgs/mozilla-mobile/projects/8 for breakdown of work.

Site permission flows: https://whimsical.co/QXGiB45gjs1iniprdrWdBG

**Comment by bbinto** [comment]
AC board: https://github.com/orgs/mozilla-mobile/projects/8

**Comment by vesta0** [comment]
Duplicate of #886
