### ISSUE TITLE
Improve notification bar message after removing "Inactive tabs"

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#21801]
After deleting the "Inactive tabs" section by tapping on "Delete all" (Trash icon) button, a notification bar is displayed at the bottom of the page with the following: "Tab closed" and "UNDO" button.

https://user-images.githubusercontent.com/48829350/136545482-a9990e31-dd21-463f-80d9-6c34da2a2d56.mp4

"Tabs closed" may be more appropriate, or some other message that informs the user that an entire section (list of tabs) is removed, instead of just one tab.

Device used: Xiaomi Mi11 Lite (Android 11).
Firefox build: Nightly 95.0a1.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18236)

**Comment by jonalmeida** [comment]
This is a bug, we should be using the correct toast message.

**Comment by sunil9211** [comment]
This same toast message is also displayed when multiple tabs are selected and closed. But if all tabs are selected and closed then correct message "Tabs closed" is displayed.

**Comment by sunil9211** [comment]
@SoftVision-LorandJanos I would like to fix this, can you assign it to me please?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812849

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
