### ISSUE TITLE
FNX-5501 ⁃ [Bug] Selected session is incorrect when opening from another app

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2181]
## Steps to reproduce
1. Have a tab already open.
1. Force close the app.
1. Click a link from an external source.
1. Observe the selected tab.

### Expected behavior
1. The link from the external source should be selected.

### Actual behavior
1. The previous selected tab is.

@csadilek and I investigated this issue and it seems to be occurring because of the async nature of the session restore which can sometimes be seen in to happen after the selected session was set by the IntentProcessor when an external tab is clicked.

The simplest solution would be to remove the coroutine and allow the updating to happen sequentially during the lazy initialization of the SessionManager.

This might have been added for performance reasons, so an alternative solution would be to hold on to the selected session, restore the state, and then re-set the selected session to it's prior one.

**Comment by sblatz** [comment]
Thank you for your investigation! 😄

**Comment by jonalmeida** [comment]
Here is some sample code on for the second solution:
```diff
diff --git a/app/src/main/java/org/mozilla/fenix/components/Core.kt b/app/src/main/java/org/mozilla/fenix/components/Core.kt
index 3867fee..8f93858 100644
--- a/app/src/main/java/org/mozilla/fenix/components/Core.kt
+++ b/app/src/main/java/org/mozilla/fenix/components/Core.kt
@@ -97,7 +97,11 @@ class Core(private val context: Context) {
                 // There's an active bundle with a snapshot: Feed it into the SessionManager.
                 snapshot.await()?.let {
                     try {
+                        val selected = sessionManager.selectedSession
                         sessionManager.restore(it)
+                        selected?.let {
+                            sessionManager.select(selected)
+                        }
                     } catch (_: IllegalArgumentException) {
                         return@let
                     }

```

**Comment by sv-ohorvath** [comment]
Isn't this the same as #1279?

**Comment by vesta0** [comment]
Yes it is @sv-ohorvath

**Comment by sv-ohorvath** [comment]
verified this is fixed on the 5/6 build.
New issue: #2290
