### ISSUE TITLE
[BZ] Page loads with redirects are blocked on UI transition when hitting enter from search screen in fenix

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21812]
https://bugzilla.mozilla.org/show_bug.cgi?id=1734916

This is heavily related to https://github.com/mozilla-mobile/fenix/issues/21530#issuecomment-938954112

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18240)

**Comment by cpeterso** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1734923
