### ISSUE TITLE
[Bug]: Incorrect removal of TLD "www" in address bar

### ISSUE THREAD

**Issue by GoogleSites** [mozilla-mobile/fenix#21833]
### Steps to reproduce

1. Go to www.com
2. URL bar shows "com", when it should show the whole website, "www.com", since "www" isn't the subdomain. On desktop Firefox and Chrome for Android, they both show "www.com"

### Expected behaviour

The URL bar should show "www.com"

### Actual behaviour

The URL bar shows "com"

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

93.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18254)

**Comment by critical-bug** [comment]
www[.]ne[.]jp too. You will see many sites in the domain by googling site:www.ne.jp. Only Firefox for Android hides the www component which is registered by Asahi Net. Chrome / Firefox desktop doesn't ellipsis it.
