### ISSUE TITLE
[Bug]: Autofill in other apps credentials saving without URL

### ISSUE THREAD

**Issue by heiserhorn** [mozilla-mobile/fenix#21839]
### Steps to reproduce

I have enabled the Autofill in other app.
I have imported my credentials from Bitwarden via a csv. The entries without a URL starting with http(s):// could not be imported. These are the one that only have an app and no website.
I went on the laptop version of firefox to manually add a new set of credentials.
I could only add http:// URLs, and for androidapps:// you cannot save.

### Expected behaviour

Save non web URLs credentials.
My example in particular is with andOTP app.

### Actual behaviour

No way to save credentials for non web URLs. I had to create a "fake" URL to be able to save my password.

### Device name

Pixel 4

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18256)

**Comment by galich** [comment]
It will be helpful to match logins by some app:// or androidapp:// URL scheme and offer matches so user does not have to go through search process.
