### ISSUE TITLE
Implement Bookmarks API

### ISSUE THREAD

**Issue by makintos90** [mozilla-mobile/fenix#21830]
### What is the user problem or growth opportunity you want to see solved?

Not being able to use Bookmark API functions, limiting the extensibility of extensions on mobile devices.

### How do you know that this problem exists today? Why is this important?

>How do you know this problem exists

According to you, it does - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks

This is important since it will users to use extenions like Floccus and xbrowsersync

### Who will benefit from it?
Firefox users on android

**Comment by kbrosnan** [comment]
Duplicate bz-1625231
