### ISSUE TITLE
add nickname label or bank logo and show it also while saving and autofill credit card

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21843]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently there is no option to add nickname or it does not show bank logo in credit card ,the problem is it is not possible to remember last 4 digit of multiple credit cards..so please add a custom field in credit card such as nickname which can be used to input custom data such as bank name HDFC,icici etc or show a logo of the bank to identify the issuer..(example screenshot attached)

This nickname or logo should also show in autofill option so that it is easier to identify the issuer

### How do you know that this problem exists today? Why is this important?
It is difficult to remember credit card numbers..so please add another identifer such as nickname or bank logo to make saving or identifying easier

### Who will benefit from it?
All users

![Screenshot_20211011-181805748 (1)](https://user-images.githubusercontent.com/58127841/136792769-1c0c007e-5102-43bb-9471-b08b50ed7b41.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18258)

**Comment by sheikh-azharuddin** [comment]
Stale bot go to hell

**Comment by sheikh-azharuddin** [comment]
,.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813674

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
