### ISSUE TITLE
[Bug]: Text selection stops at first word

### ISSUE THREAD

**Issue by alexmitev81** [mozilla-mobile/fenix#21855]
### Steps to reproduce

When selecting text with finger dragging, selection should follow finger.

### Expected behaviour

Text selection should follow finger.

### Actual behaviour

Text selection stops at the end of the first word, and I have to drag the "balloon" to further extend the selection.

### Device name

Blackberry KeyOne

### Android version

Android 8.1.0

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18267)

**Comment by makotokato** [comment]
@SoftVision-LorandJanos

Could you file this issue to BMO (Core:Layout)?  I believe that this is kind of AccessibleCaret implementation issue.

**Comment by makotokato** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1745686

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
