### ISSUE TITLE
allow pinned Top Sites to be rearranged 

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#21857]
Feature request: "pinned" Top sites (there is a pin icon beside it) should be rearrangeable. There could be a few reasons for doing this, but the reason I'm requesting it is because I use my phone with 1 hand and I would like to be able to rearrange the top site tiles so that the ones I use the most are closest to my thumb, and the ones I use the least would require a bit of a thumb stretch to tap. 

Apologies if this is a duplicate

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/20068
