### ISSUE TITLE
FNX-5504 ⁃ [Bug] Some elements on the home screen are not aligned

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2185]
## Steps to reproduce
Check the home screen.

### Expected behavior
These elements are aligned. Aligned elements look better.

### Actual behavior
The texts and the 3-dots menus are not aligned. This looks messier.

### Device information
* Android device: 8.0
* Fenix version: 1.0.1918

![Screenshot](https://user-images.githubusercontent.com/32398857/56997526-6c632900-6b7e-11e9-882a-95d6ac480937.jpg)UNITO-UNDERSCORE!20190430-114018!UNITO-UNDERSCORE!Firefox Preview!
![Screenshot](https://user-images.githubusercontent.com/32398857/56997533-7127dd00-6b7e-11e9-9c3c-f192613e5e88.jpg)UNITO-UNDERSCORE!20190430-114209!UNITO-UNDERSCORE!Firefox Preview!

**Comment by cadeyrn** [comment]
See #600.

**Comment by vesta0** [comment]
@Lululalu thank you for noticing and filing! For now this design is intentional but we will keep this feedback in mind when we user test.
