### ISSUE TITLE
[Bug]: Tabs menu animation should obey global Android animation settings

### ISSUE THREAD

**Issue by alexmitev81** [mozilla-mobile/fenix#21856]
### Steps to reproduce

1. In Android Developer Options, set Window animation scale, Transition animation scale and Animator duration scale all to off
2. In Firefox, press the number of tabs button
3. The menu still animates

### Expected behaviour

The menu should not animate, obeying the Android settings

### Actual behaviour

The menu is animated

### Device name

Blackberry KeyOne

### Android version

Android 8.1.0

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

**Comment by Dunexus** [comment]
Seems to be the same request as https://github.com/mozilla-mobile/fenix/issues/3597
