### ISSUE TITLE
FNX-5505 ⁃ [Bug] There's some unused space above the search bar

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2186]
## Steps to reproduce
Touch the search bar

### Expected behavior
The screen space should be used in a way that maximizes the visibility of content; in this case, search suggestions

### Actual behavior
There is a gap of unused space above the address bar
![Screenshot](https://user-images.githubusercontent.com/32398857/56997882-a84abe00-6b7f-11e9-876d-cb0e19c28fe9.jpg)UNITO-UNDERSCORE!20190430-193324!UNITO-UNDERSCORE!Gallery!

### Device information
* Android device: 8.0
* Fenix version: 1.0.1918

**Comment by topotropic** [comment]
@AmyYLee did you address this in your review? Thanks!

**Comment by AmyYLee** [comment]
We need a bit of margin space between the search bar and search suggestions list rather than these two components butting up against each other. Also in the current position the elements are equally spaced.

**Comment by topotropic** [comment]
@AmyYLee Sorry for not being more explicit, I was more worried about the top margin above the search field. Thanks!

**Comment by AmyYLee** [comment]
> @AmyYLee Sorry for not being more explicit, I was more worried about the top margin above the search field. Thanks!

Ah got it. I'll add it to the list
