### ISSUE TITLE
FNX-5506 ⁃ [Bug] Custom Tabs: Top of the browser viewport is hidden behind the BrowserToolbar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2187]
## Steps to reproduce
1. Open a site in a CT.

### Expected behavior
To be able to see the full top of the website visited.

### Actual behavior
The top of the site is hidden behind the BrowserToolbar that is at the top of the screen.

### Device information
* Fenix version: 30/04/19

**Comment by k0ur0x** [comment]
probably duplicate of #1727

**Comment by vesta0** [comment]
Will be addressed: A-C bug: mozilla-mobile/android-components#2675
