### ISSUE TITLE
Home screen search group removal tweaks

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#21871]
There are three problems with the group removals on home screen right now:
1) it appears the UI update after removal races with the actual delete operation; it looks like the delete didn't happen (group is still there), but going in and out of home screen clears the group from the screen. the this was called out in the review but we didn't address it then.
2) UI update after tapping "remove" scrolls the home screen to the top; it's quite jarring.
3) after removing a search group, the same group still remains present in the tabs tray and in "jump back in" section.

For (1), we should dispatch a store update alongside async delete operations, to update the UI state right away.
For (2), try to see if we can avoid scrolling the screen.
For (3), we should "ungroup" existing tabs - we can dispatch a metadata key update action with searchTerms/referrer set to `null`. The behaviour this should achieve is the following: removing a search group from the home screen will ungroup related tabs in the tabs tray (and move them to "other tabs"), and remove the search from the "jump back in" section.

Patches for (1) and (3) will need to be uplifted to current beta 94.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18273)

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview 94.0.0-beta.4.

### Devices used:
- Huawei MediaPad M3 (Android 7)
- Oppo Find X3 (Android 11)
