### ISSUE TITLE
[BZ] Consider making speculative connections to minimize redirection time

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#21872]
https://bugzilla.mozilla.org/show_bug.cgi?id=1681088

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18275)

**Comment by mcomella** [comment]
Triage: there may be some changes needed in fenix to achieve this so keeping tracking bug.

**Comment by cpeterso** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1681088
