### ISSUE TITLE
[Bug]: Swiping toolbar switches tabs in random order

### ISSUE THREAD

**Issue by alexmitev81** [mozilla-mobile/fenix#21879]
### Steps to reproduce

1. Open several tabs
2. Swipe the toolbar to switch between them

### Expected behaviour

When I'm on tab 1, swiping right should show tab 2
When I'm on tab 4, swiping left shold show tab 3

### Actual behaviour

Swiping left of right shows some random tab from the list and not the adjacent to the current tab

### Device name

Blackberry KeyOne

### Android version

Android 8.1.0

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18278)

**Comment by nyanpasu64** [comment]
I think the issue isn't that swiping the tab bar is a random order, but that the tab tray is in a random order.
