### ISSUE TITLE
[Bug]: Can't load certain page

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [mozilla-mobile/fenix#21878]
### Steps to reproduce

1. Open some page in Minecraft Wiki, like https://minecraft.fandom.com/wiki/Campfire in Firefox Nightly

### Expected behaviour

The page load normally.

### Actual behaviour

After the page loads half (loading bar goes around 2/3) it stopped loading, instead the browser displays a message said: Sorry, Firefox Nightly can't load that page. 

The page can be load on other browsers. Firefox Nightly can load almost every other page

### Device name

Google Pixel 3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 (Build #2015838891)

### Device logs

[Crash report](https://crash-stats.mozilla.org/report/index/5df0d8eb-e30d-4450-a5e1-c59960211013) shows there is a native crash on libc.so.

### Additional information

I'm using GrapheneOS.

**Comment by amedyne** [comment]
This is loading properly on Firefox v99.1.1. Closing ticket
