### ISSUE TITLE
Use Hero images for Jump back in

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#21888]
Fetch the pages' hero image (this is defined by <meta> properties such as og:image https://css-tricks.com/essential-meta-tags-social-media/#proprietary-meta-tags) and use it if it is available (hero image might not be available for every page if it is not defined, we should check if we can get thumbnail or favicon afterwards and display that as appropriate) for the "Jump back in" icon for individual tabs. 

The fallback order if the hero image is not available (first is preferred, last is least preferred):
- Hero image
- Thumbnail
- Favicon
- Background with a representative letter of the page

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (2021-11-02T05:08:21.122949).

Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.
