### ISSUE TITLE
Move Tabs Tray to compose: Gesture support

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#21896]
Gesture support - how to support swiping to delete by horizontal and vertical directions, see TabsTouchHelper
From #21318

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18292)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810776

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
