### ISSUE TITLE
Move Tabs Tray to compose:  Browser lists 

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#21899]
Browser lists - see NormalBrowserTrayList, PrivateBrowserTrayList, AbstractBrowserTrayList.
From meta #21318

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18289)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810777

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
