### ISSUE TITLE
Move Tabs Tray to compose:  Individual tab viewholders: GridViewHolder, ListViewHolder.

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#21894]
From: #21318

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18293)

**Comment by MozillaNoah** [comment]
@Amejia481, I noticed this issue wasn't flagged and auto closed with your PR the other day. Should this be closed or did it need to be formally QA'd?

**Comment by Amejia481** [comment]
Yes, I think we could close it. As at the moment it's [behind a feature flag that it's only active  on debug builds](https://github.com/mozilla-mobile/fenix/blob/bf522dbd508d9a89476cd8a3293b68cd90340ff3/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L104). Ideally we would like to active it on nightly for people to provide feedback, but not sure if we should as we we don't have support for tabs re-ordering in compose yet.
