### ISSUE TITLE
Move Tabs Tray to compose: Normal/Private page list 

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#21901]
Normal/Private page list - NormalBrowserPageViewHolder, PrivateBrowserPageViewHolder, SyncedTabsPageViewHolder

From meta #21318

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18294)

**Comment by mcarare** [comment]
This [bug](https://github.com/mozilla-mobile/fenix/issues/23106) should also be taken into consideration when working on this.
