### ISSUE TITLE
HTTPS shortly appears as insecure on new tabs

### ISSUE THREAD

**Issue by outhex** [mozilla-mobile/fenix#21909]
# Description 

When browsing any HTTPS websites (e.g. google[.]com, amazon[.]com...), 
the lock in the toolbar will show as if the website is not secured for a fraction of seconds and then show as secure.

# Steps to reproduce

1. Open a **new** tab
2. Type the URL of a popular, secured website 
    - e.g https://google.com, www.google.com, google.com
3. Press send

# Expected behaviour

The lock should appear as "secure" at all time when visiting any secure website with a valid certificate.

# Actual behavior

The lock appear as "insecure" for a few milliseconds when visiting the first website of a new tab.

# Device/Build Information

## Mobile device

- Pixel 5
- Android 11
- Build: RQ3A.211001.001

## Firefox

- 93.0.1 (Build #2015836707)
- AC: 93.0.11, 701ac90be7
- GV: 93.0-20210927210923
- AS: 82.1.0

_Originally posted by @outhex in https://github.com/mozilla-mobile/fenix/issues/14172#issuecomment-942606934_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18301)

**Comment by kbrosnan** [comment]
Closing as  a duplicate.
