### ISSUE TITLE
Move Tabs Tray to compose: Synced Tabs list 

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#21900]
Synced Tabs list - SyncedTabsTrayLayout, SyncedTabsAdapter
Note:    We can do this async; doesn't have to wait for the normal/private tab list.

In the SyncedTabsFeature, we do have a `SyncedTabsView.listener` which is tightly coupled to an instance for `SyncedTabsView` that probably needs to be decoupled so interactions can be invoked in a Composable which does not require 'View' classes.

From meta #21318 

https://mozilla-hub.atlassian.net/browse/FNXV2-18288

**Comment by jonalmeida** [comment]
We could probably fix this issue in the Compose UI too: https://github.com/mozilla-mobile/fenix/issues/19942

In Compose, I believe you use `stickyHeader` in a `LazyColumn` scope.
