### ISSUE TITLE
[Bug]: Preventing context menu / `"contextmenu"` event through `preventDefault` for an `img` element does not work.

### ISSUE THREAD

**Issue by MelvinWM** [mozilla-mobile/fenix#21929]
### Steps to reproduce

1. Have an `img` element and add a `"contextmenu"` listener to it that calls `preventDefault` (the listener can also have the argument `passive` set to `false` when adding the listener using `addEventListener`).
2. Use 'long tap' on the `img`.
3. Observe.
4. (see also https://jsfiddle.net/nc1zuref/ ).

### Expected behaviour

A context menu should not open.

### Actual behaviour

A context menu unexpectedly opens.

### Device name

Galaxy A20s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.1.0 (Build #2015836707)

### Additional information

**Somewhat minimal reproducible example**

https://jsfiddle.net/nc1zuref/ :

1. Right-click on the images or long-tap on them.
2. For Firefox on desktop, as well as Chrome on Android, using right-click or long tap, the first two `img`s correctly do not show context menus, while the third `img` correctly does show the context menu.
3. However, for Firefox on Android, all three `img`s show the context menu.

(note that the third `img` is added purely for the sake of having something to compare with).

**Related bugs**

This bug may be related to #14067 . I have tried searching for "context menu" and "contextmenu" with the label "🐞+bug", but did not find any open issue that matched.

**How this bug can cause problems**

One example where this bug can give problems is if you have a touch event listener on an `img`, where the user for some actions is meant to continue to touch down on the `img` for longer periods (for instance for moving some graphical element around while still being able to see the graphical element), detecting the specific touch position on the `img`, and where there is a real-time aspect to it. The context menu appearing suddenly is therefore troublesome. It works on Chrome on Android. I don't know what an easy work-around would be, apart from finding and using some element other than `img` where `preventDefault` does work for the `"contextmenu"` event for Firefox on Android (while I have not looked into it, I would assume that it would work for some element other than `img`).

**Comment by MelvinWM** [comment]
In #14067  , it turns out that, like for `img` elements, `a` HTML elements do not work for this either. Regular `p` elements, on the other hand, do work correctly, with `preventDefault` correctly preventing a menu from showing up. That said, `p` elements when long-tapped/pressed show a very different kind of menu (as well as text selection/highlighting) than for `img` and `a` elements.

**Comment by MelvinWM** [comment]
Upon the advice of helpful developers in chat.mozilla.org under Android Components, I have also posted a bug issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1736391 .

**Comment by amedyne** [comment]
Closing issue to track bugzilla instead.
