### ISSUE TITLE
[Bug] recent bookmarks section: much smaller border radius

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#21939]
### Steps to reproduce

1. open Firefox home screen

### Expected behaviour

All items have the same border radius.

### Actual behaviour

The items of the recent bookmarks sections have a much smaller border radius compared to the top sites, "jump back in", recent searches and Pocket.

### Device name

OnePlus 7T Pro McLaren Edition

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

main branch revision 625233f66488412287e3400a08d1c5c55439ff2e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18319)

**Comment by sunilk9211** [comment]
hi @amedyne @cadeyrn i would like to fix this, can you please assign this to me? 
And what should be the border radius?  should it be same as Jump back in and recently visited?

**Comment by cadeyrn** [comment]
This looks fixed.
