### ISSUE TITLE
[Bug]: Integrated iframe cannot download pdf

### ISSUE THREAD

**Issue by SimonChaumet** [mozilla-mobile/fenix#21930]
### Steps to reproduce

[Minimal Reproducible Example](https://codesandbox.io/s/wandering-leftpad-ehwl2?file=/index.html)
1. Create an html document
2. Add an iframe containing a pdf in data url (base64)
3. Open document in firefox

### Expected behaviour

The pdf should be visible or available for download

### Actual behaviour

The download button is not clickable and a part of the base64 data is shown.

![Screenshot_20211014-142422_Firefox](https://user-images.githubusercontent.com/7894362/137323006-7d8a5fe9-bfc9-433d-9313-6e531044c8f9.jpg)

### Device name

Samsung Galaxy S20

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18313)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on the latest Firefox Preview Nightly 2022-01-06.
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 12)

**Comment by Amejia481** [comment]
cc @mavduevskiy
