### ISSUE TITLE
[Bug]: Delete bookmark prompt can be triggered twice and crash the application after using it

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21932]
### Steps to reproduce

1. Add a webpage to bookmarks and select to edit
2. Tap twice, in quick succession on the Delete button (trashcan)
3. After the two prompts are displayed, select Delete on both of them

### Expected behaviour

The application is stable at all times. The button is locked after the first tap and the user can not bring up two prompts at the same time

### Actual behaviour

Two prompts are brought up if tapping on the delete button in quick succession. Selecting the Delete option twice will crash the application.

![245587314_899587563990749_6542973277887394489_n](https://user-images.githubusercontent.com/89511597/137339780-51c2622f-3b01-4fa5-ae2d-f1e071869d56.gif)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

94.0.0-beta.3 2021-10-13

### Device logs

6300aeff-92a2-4f11-ab56-e94891229614
java.lang.IllegalStateException: Fragment EditBookmarkFragment{c687e3d} (a0d3335f-29ef-4c6d-a3e7-8b9fa436af9d) not attached to a context.
----
java.lang.IllegalStateException: Fragment EditBookmarkFragment{c687e3d} (a0d3335f-29ef-4c6d-a3e7-8b9fa436af9d) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
	at org.mozilla.fenix.ext.FragmentKt.getRequireComponents(Fragment.kt:1)
	at org.mozilla.fenix.library.bookmarks.edit.EditBookmarkFragment$displayDeleteBookmarkDialog$1$1$2$1.invokeSuspend(EditBookmarkFragment.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

### Additional information

Also occurs on Firefox Nightly 95.0a1 2021-10-14 and RC 92.1.1 2021-09-28. 

Using the same steps for History, the prompt will be displayed twice but it will not cause a crash to occur.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18314)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 2021-10-19.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
