### ISSUE TITLE
[Bug]: When deleting a folder or a website from History, it doesn't disappear until re-entering the History section 

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#21933]
### Steps to reproduce

1. Do some searches on the same topic in order to save a folder in the recent searches.
2. Access the History folder via `recent searches` or the History menu.
3. Attempt to delete a folder or a website from recent searches.

### Expected behavior
The folder/website is deleted and the section is updated accordingly.

### Actual behavior
When deleting a folder or a website from recent searches, it doesn't disappear until re-entering the History section 

### Device name
Samsung Galaxy S21 Ultra

### Android version
Android 11

### Firefox release type
Firefox Nightly

### Firefox version
95.0a1(Build #2015839657)

### Notes
This is only a visual bug, after re-entering the History section, the deleted folders/websites are gone.
The folders/websites can be deleted from the home screen in the `Recent searches without issues.

https://user-images.githubusercontent.com/42831109/137346458-ffef3604-8d6d-4052-b708-0267c091ec04.mp4

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Nightly (2021-11-01T05:11:04.075119).
Device used: Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.
