### ISSUE TITLE
[Bug]: http://[::]:8000/ link in Firefox for Android is searched by google instead of going to said site

### ISSUE THREAD

**Issue by artisticfox8** [mozilla-mobile/fenix#21936]
### Steps to reproduce

Run a localserver at http://[::]:8000/ How I did it:

1. Download the Termux app from F-Droid
2. Grant the app storage permissions.
3. cd to any directory you like for example `cd /storage/emulated/0/Download`
4. Run `python3 -m http.server`
5. Go to `http://[::]:8000/`

### Expected behaviour

A directory page with the title "Directory listing for /" should appear (just like it does in any other browser)

### Actual behaviour

The http://[::]:8000/ is searched through Google.

### Device name

Samsung Galaxy A52

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.1.0

**Comment by kbrosnan** [comment]
duplicate #17606
