### ISSUE TITLE
[Bug] recent bookmarks section has a small horizontal offset

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#21941]
### Steps to reproduce

1. open Firefox home screen

### Expected behaviour

There should be the same margin for all sections on the home screen.

### Actual behaviour

The recent bookmarks sections has a slight offset compared to "jump back in", recent searches and Pocket.

![137390160-c61a1ea8-9534-4e43-ab8c-79d79e8fcd09-2](https://user-images.githubusercontent.com/1100614/137578985-99a0aa40-dc47-4172-96f7-a7895360e637.png)

### Device name

OnePlus 7T Pro McLaren Edition

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

main branch revision 625233f66488412287e3400a08d1c5c55439ff2e

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Verified on the latest Nightly 101.0a1 (2022-04-21) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
