### ISSUE TITLE
[Bug]: Infinite loading loop on 9to5google.com article with many audio elements

### ISSUE THREAD

**Issue by FranzPio** [mozilla-mobile/fenix#21968]
### Steps to reproduce

1. Visit the following webpage:
https://9to5google.com/2021/10/15/pixel-sounds-material-you/

### Expected behaviour

The site loads correctly in Chrome family browsers (namely Samsung Internet).

### Actual behaviour

Firefox enters a loop where the site is beginning to build up, but then the loading bar is reset and the whole loading process starts anew.

### Device name

Google Pixel 3a

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

The site contains a lot of "audio elements" (sorry, I don't know the technical term) and I think they're causing the problem. Notably, Samsung Internet lazy-loads these audio objects a few seconds after the page has been built up and the loading bar is complete.

**Comment by SoftVision-LorandJanos** [comment]
While the loading process is finished after a few seconds, the site is not scrollable downwards, as it can be on other browsers (eg. Chrome).
Device used: Xiaomi Mi11 Lite (Android 11).
@FranzPio how is the behavior on the latest nightly on your end? Thank you!

**Comment by FranzPio** [comment]
Actually, on the latest stable version (99.2.0), this is fixed for me.

**Comment by SoftVision-LorandJanos** [comment]
After the initial scrolling issues the website worked as expected on my end as well, so based on this and on the comment above, I will close this issue as fixed.
