### ISSUE TITLE
[Bug]: Disabling "Zoom on all websites" will not reset zoom level on certain webpages until refreshing

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21960]
### Steps to reproduce

1. Enable "zoom on all websites" in Settings > Accessibility
2. Sign in to facebook.com
3. Zoom in on the page
4. Disable the zoom on all websites and close the settings menu

### Expected behaviour

The zoom level is automatically reset after it is disabled

### Actual behaviour

The user can no longer zoom in or out until the page is refreshed manually

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

93.2.0 2021-10-14

### Additional information

https://user-images.githubusercontent.com/89511597/137505329-0d67e2ce-66d5-45d5-bd50-e906181921a7.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18332)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 101.0a1 (2022-04-21) build.
Device used: Google Pixel 4 (Android 12).

**Comment by AdinaPetridean** [comment]
Hello

**Comment by AdinaPetridean** [comment]
The issue is still reproducible on: Firefox 103.0.0 - Beta.3 with OnePlus 9 PRO (Android 12) even if the page is refreshed with this [link](http://introducinghtml5.com/examples/ch04/ch4-full-fallback.html.).

**Comment by amocirean** [comment]
I was not able to reproduce the issue on Firefox 103.0.0 - Beta.5 with Huawei P40 Lite (Android 10).

**Comment by delia-pop** [comment]
Still reproducible as descried on Fenix Beta 105.0b4 with Lenovo Yoga Tab 11 (Android 11).

**Comment by kbrosnan** [comment]
This sounds like expected behavior. I would not want Firefox to refresh the page in case it causes some data loss. This will fix itself the next time the user loads the page.
