### ISSUE TITLE
[Bug]: Error Uncaught (in promise) DOMException: The operation is insecure. when running screen.orientation.lock("landscape"); after document.documentElement.requestFullscreen();

### ISSUE THREAD

**Issue by artisticfox8** [mozilla-mobile/fenix#21970]
### Steps to reproduce

Have code that looks like this:
HTML:
```
<div style="padding-top: 80px">
		<input type="button" id="fullScreen" value="Vejít do režimu celé obrazovky">
	</div>
```
JS:
```
document.getElementById("fullScreen").addEventListener("click",function(){
  	if(!document.fullscreenElement){
			document.documentElement.requestFullscreen();
				try{
					screen.orientation.lock("landscape");
				}catch(e){ 
					console.log(e);
				}
	}
});
```
Steps to reproduce:
Launch the files on a localhost:8000 (I used Termux and `python3 -m http.server` command) 
Click the button.

### Expected behaviour

The document orientation should be landscape (just like it is in Chrome).

### Actual behaviour

Firefox raises `Uncaught (in promise) DOMException: The operation is insecure.` on `screen.orientation.lock("landscape");` 

### Device name

Samsung Galaxy A52

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18341)

**Comment by makotokato** [comment]
dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1744288.

You can resolve this when use `await document.documentElement.requestFullscreen()` instead.

**Comment by makotokato** [comment]
@kbrosnan could you close this since I don't have permission of fenix bug and this is dup of BMO?

**Comment by cpeterso** [comment]
Closing this bug as a dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1744288
