### ISSUE TITLE
[Bug]: address/form autofill

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#21978]
### Steps to reproduce

Autofill address/form is not working even though feature is enabled in the settings
Interestingly there is no ui to manage addresses whereas desktop version has one

### Expected behaviour

A menu should appear to fill addresses in forms similar to desktop version

### Actual behaviour

No autofill prompt shows to fill addresses

### Device name

rog3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18346)

**Comment by makotokato** [comment]
Actually, we only set hint for login type such as username and password.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1607114 for other hints.

**Comment by makotokato** [comment]
> > Actually, we only set hint for login type such as username and password.
> > See https://bugzilla.mozilla.org/show_bug.cgi?id=1607114 for other hints.
> 
> Ok but that was opened 2 years ago with no proper update and set to low priority neutral_face
> 
> So why add these settings then in Firefox?? ![Screenshot_20211019-150103657 (1)](https://user-images.githubusercontent.com/58127841/137883298-f59e4fc6-5f1a-440f-9df8-090cb3767397.jpg) ![Screenshot_20211019-150042622 (1)](https://user-images.githubusercontent.com/58127841/137883311-0727d879-6f93-458b-8ed4-8b707a0f4e6c.jpg)

Ah, I misunderstand this issue.  This is for builtin autofill from Firefox sync data. https://bugzilla.mozilla.org/show_bug.cgi?id=1607114 is for 3rd party autofill service.

**Comment by cfebs** [comment]
Looking forward to it being implemented! @amedyne is there another ticket/pr i could subscribe to track mobile Address Autofill progress?

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1367247

**Comment by weedz** [comment]
This seems to be added in a recent release of Firefox for Android, https://www.mozilla.org/en-US/firefox/android/104.0/releasenotes/

> Address autofill: Firefox will now remember and offer to fill common address forms. You can add, edit and manage your addresses in the Firefox settings.

But i still cannot seem to find anything related to this in the settings, and autofill for address forms does not work at all on android.

On the desktop version I think I needed to change the setting `extensions.formautofill.addresses.supportedCountries` to include `SE` (plus some other autofill configs) in order to show autofill settings. Is there anything similar on android?

**Comment by amedyne** [comment]
@weedz You can get to Address Autofill thru the following: 
Settings-> Autofill -> Addressess

Can you check if **Save and autofill addresses** is enabled for you?

**Comment by weedz** [comment]
> @weedz You can get to Address Autofill thru the following: Settings-> Autofill -> Addressess
> 
> Can you check if **Save and autofill addresses** is enabled for you?

Cannot find anything related to autofill in the settings.

This is my firefox version:
![Screenshot_20221030-193853_Firefox](https://user-images.githubusercontent.com/634476/198896028-c198c2cb-d7fb-4426-af4b-88835bd30646.png)

**Comment by plwt** [comment]
I believe that this is one of the features that is only available to people in the USA.

**Comment by sheikh-azharuddin** [comment]
But why US only 😔
You guys making it like alien invasion movies.. everything happens first in US🤣

**Comment by jonalmeida** [comment]
Closing this as won't fix until the priority of the feature changes. Currently the feature is disabled.
