### ISSUE TITLE
URL suggestions are not displayed when typing in the address bar

### ISSUE THREAD

**Issue by jhaiduce** [mozilla-mobile/fenix#21971]
URL suggestions are not displayed when typing in the address bar. 

Unlike #20351, the failure is not intermittent. I have not seen suggestions of any kind for at least a week. 

Firefox version: 93.1.0 (Build #2015836707)

Android version: 9

Hardware: Samsung Galaxy S8 (model SM-G950U1)

**Comment by sflorean** [comment]
A fix have been landed on Firefox versions (#20351). Closing as fixed.
