### ISSUE TITLE
Changing bad IP URL is not honored for new search

### ISSUE THREAD

**Issue by JustinWebDev** [mozilla-mobile/fenix#21975]
### Steps to reproduce

1) start a new tab (private or not)
2) type a not-found IP address (private or public) in the address bar, e.g., on my network http://192.168.3.54 would not be found since there is no such address on my LAN
3) while the browser is searching for the address (or after it fails), put focus in the address bar
4) change a portion of the address, .e.g, change http://192.168.3.54 to http://192.168.3.50, tap "Go" to start browsing to the new address - observe the original address is still being used
You have to close that tab and start over with the new address before Fx will find it.

### Expected behaviour

The browser should immediately honor any changes to the address after making changes.

### Actual behaviour

The browser does not honor the changes.

### Device name

Samsung A6

### Android version

5.1.1

### Firefox release type

Firefox

### Firefox version

93.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18344)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on the latest Firefox Preview Nightly 2021-11-18.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by JustinWebDev** [comment]
problem is still fresh

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813842

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
