### ISSUE TITLE
FNX-85 ⁃ SPIKE: Send download to external Downloader like ADM

### ISSUE THREAD

**Issue by spandan888** [mozilla-mobile/fenix#2197]

**Comment by vesta0** [comment]
@cpeterso would this be addressed by using the GV download API in the future? What makes this work in Fennec?

**Comment by pocmo** [comment]
This could be implemented in AC (in `feature-downloads`). For every download Fennec does a lookup whether there's an app installed that can handle the download URL /  MIME type combination. If there's at least one app then Fennec will show a dialog (like the intent chooser) where the user can select whether to download with Firefox or one of the available apps.

**Comment by abhimanyusingh0** [comment]
So is this feature coming in future? I really miss this.

**Comment by sblatz** [comment]
AC: are you able to help us understand: 
- How difficult is this to implement?
- Does this make sense to add as a part of the meta of download manager as we work on it?

**Comment by NotWoods** [comment]
I've been having trouble finding documentation on what intents need to be used with third-party downloaders. We may need to dig through Fennec and see what is done there. I think we chose to separate this from the main download manager meta.

**Comment by Amejia481** [comment]
@pocmo told us that we had worked on the Fennec implementation maybe he can give us some hints

**Comment by pocmo** [comment]
Fennec roughly does the following:
* It queries the package manager for apps that can handle the URL + mime type
* It filters out browsers
* It adds itself to the list

After that:
* If there's no app -> We can't handle that download
* If there's only one app (Usually Firefox itself) -> Use that
* If there are multiple options: Show an intent chooser like dialog where the user can select an option (and also select to always use this option).

Related code:
* https://searchfox.org/mozilla-esr68/source/mobile/android/components/HelperAppDialog.js#139-251
* https://searchfox.org/mozilla-esr68/source/mobile/android/modules/HelperApps.jsm#137-198
* https://searchfox.org/mozilla-esr68/source/mobile/android/base/java/org/mozilla/gecko/IntentHelper.java#430-437

**Comment by Amejia481** [comment]
Thanks!

**Comment by Amejia481** [comment]
For addressing this feature we need to:

- Be able to handle incoming intents for downloads https://github.com/mozilla-mobile/android-components/issues/4770
- Improve our download manger to forward downloads to external download managers https://github.com/mozilla-mobile/android-components/issues/4772

**Comment by Amejia481** [comment]
As we now have https://github.com/mozilla-mobile/android-components/issues/4770 and https://github.com/mozilla-mobile/android-components/issues/4772 we can close this issue.
