### ISSUE TITLE
Reduce redirection of colors variables between dark and light theme

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#21973]
Continuation of https://github.com/mozilla-mobile/fenix/issues/21935, we will  look at reducing the amount of redirection between variables between dark and light theme.

**Comment by gabrielluong** [comment]
https://github.com/mozilla-mobile/fenix/pull/22195
https://github.com/mozilla-mobile/fenix/pull/22203
https://github.com/mozilla-mobile/fenix/pull/22220
https://github.com/mozilla-mobile/fenix/pull/22228
https://github.com/mozilla-mobile/fenix/pull/22269
https://github.com/mozilla-mobile/fenix/pull/22273

**Comment by LaurentiuApahideanSV** [comment]
@gabrielluong Do we need to check here something from QA side? We took a look at 96.0.0-beta.1 but we didn't see any visual changes.

**Comment by gabrielluong** [comment]
> @gabrielluong Do we need to check here something from QA side? We took a look at 96.0.0-beta.1 but we didn't see any visual changes.

I think if no visual changes were found, then I think it's perfect. We don't expect any visual/color changes (hopefully) from cleaning up our color variable usage.

**Comment by LaurentiuApahideanSV** [comment]
We tested the  issue didn't find any visual changes. The issue is fixed.
### Device used:
- Huawei MediaPad M3 (Andoid 7)
