### ISSUE TITLE
Adding notes to a collection

### ISSUE THREAD

**Issue by gdnzz** [mozilla-mobile/fenix#21980]
### What is the user problem or growth opportunity you want to see solved
Being able to add notes to a collection.

### How do you know that this problem exists today? Why is this important?
It is really beneficial for researching etc. So your notes are all in the same place.

### Who will benefit from it?
Average users.

Example of notes in collections: Screenshot from ms edge on windows 10
![image](https://user-images.githubusercontent.com/76991571/137726656-a703cb1f-791c-461b-b450-035d58e5b5af.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18348)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812731

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
