### ISSUE TITLE
Deleting the last component of the collection shouldn't delete the whole collection

### ISSUE THREAD

**Issue by gdnzz** [mozilla-mobile/fenix#21985]
### What is the user problem or growth opportunity you want to see solved?
When there is only an element (site) in a collection and I delete that, the collection is deletes itself.
### How do you know that this problem exists today? Why is this important?
For instance if I have a reading collection and I delete every element after reading them, the whole collection is deleted. I think it would be better if the collection stood.
### Who will benefit from it?
Average users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18350)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813685

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
