### ISSUE TITLE
FNX-5510 ⁃ [Bug] Gecko about: tabs have no tab title on Fenix tab session screen

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#2199]
## Steps to reproduce
1. Open `about:about` or `about:config`.
1. Open Fenix's tab session screen.

### Expected behavior
The `about:` tabs should have a title.

### Actual behavior
The `about:` tabs have an "A" icon but the title is blank.

### Device information
* Android device: Moto G5
* Fenix version: 1.0.1918 (5/1)

**Comment by Lululalu** [comment]
I think it's the same as #2057

**Comment by cpeterso** [comment]
> I think it's the same as #2057

Yep! Thanks.
