### ISSUE TITLE
[Bug]: Firefox nightly google play channel does not update with nightly builds

### ISSUE THREAD

**Issue by Goog87354** [mozilla-mobile/fenix#22003]
### Steps to reproduce

[Bug]: Ff nightly google play channel does not update with nightly builds
1. install nightly from google play
2. check for updates the next night
3. after about a week see no updates

### Expected behaviour

I expected nightly builds to arrive each night as updates.

### Actual behaviour

Firefox nightly installs and does not update with nightly builds.

### Device name

android 10 arm64

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 (Build #2015839755)
AC: 95.0.20211013172120, 8f37c5da85
GV: 95.0a1-20211013034420
AS: 85.4.1

**Comment by kbrosnan** [comment]
We are currently using a staged rollout on nightly. Google Play does not provide for the user to force the update until we return to 100% rollout.
