### ISSUE TITLE
change tab viewer list style to jump back in card style

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22016]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently the tabs in the list view does not look attractive. The recently jump back in card style menu item looks awesome ..please implement this same for the list style tab view

### How do you know that this problem exists today? Why is this important?
List style tabs looks outdated ..the new card style item in jump back in can be used for tabs list view modernising the looks and make consistent

### Who will benefit from it?
All users

![Screenshot_20211019-210949368 (1)](https://user-images.githubusercontent.com/58127841/137944875-9f5de493-241c-4428-8b23-20a57dc425c1.jpg)
![Screenshot_20211019-211003967](https://user-images.githubusercontent.com/58127841/137944880-a377fcb9-1ebe-4679-b1db-69af1acb01ce.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18373)

**Comment by klint** [comment]
The purpose is not the same. Please keep the information density as it is on the tab tray. This would be a 3rd view between grid and list. Not a replacement for the list view.

**Comment by sheikh-azharuddin** [comment]
...

**Comment by sheikh-azharuddin** [comment]
..

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813686

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
