### ISSUE TITLE
[Bug]: Flat list of all history for given timeframe is inconsistently displayed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#22013]
### Steps to reproduce

1. Do some searches and set the device date and time 7 days ahead of the searches.
2. Do some searches and move the device date and time 2 days ahead of the searches.
3. Do some searches again and move the date and time again with 5 days ahead.
4. Do some searches again and move the date and time again with 7 days ahead.

### Expected behavior
The flat list of all history for the given timeframe should display: Today/Yesterday/7 days ago/14 days ago. (Based on my steps).

### Actual behavior
Flat list of all history for given timeframe is inconsistently displayed.

### Device name
Samsung Galaxy S21 Ultra

### Android version
Android 11

### Firefox release type
Firefox Nightly

### Firefox version
95.0a1

### Additional information

Note that changing the device date was the only way to test this faster.
The Flat list of all history for given timeframe sometimes displays only Today and 30 days or Older.

**Comment by athomasmoz** [comment]
@abodea Were you able to find steps to consistently reproduce the issue?

**Comment by Mugurell** [comment]
Based on https://github.com/mozilla-mobile/fenix/blob/d9847f952534e2e69cb197f1632faf51b05e9b2a/app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt#L105-L113
we have the following groupings: `Today`, `Yesterday`, `This Week`, `This Month`, `Older`

In my tests I saw the expected groupings based on time:
(each search contain the date and time set in system settings, screenshot taken on 26 Nov, 4:07)
<img src="https://user-images.githubusercontent.com/11428869/141149142-afebd16a-5719-4550-a4a4-a504af50642b.png" width="44%" />

**Comment by abodea** [comment]
> @abodea Were you able to find steps to consistently reproduce the issue?

Hello, Ashely, and sorry for the late response. 
I thought that the answer from the Jira ticked covered this.
Please note that I synced with @Mugurell and it looks that this is working accordingly after some other tests and after inspecting the code.
He added a new issue and I also added the missing part that was displayed in Jira/Figma https://github.com/mozilla-mobile/fenix/issues/22420.

**Comment by Mugurell** [comment]
I think this issue can then be closed with the remaining work for the feature to be completed being done in https://github.com/mozilla-mobile/fenix/issues/22420 and https://github.com/mozilla-mobile/fenix/issues/22014.
