### ISSUE TITLE
[Bug]: Synced history button is not implemented in the History section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#22014]
### Steps to reproduce
1. Access the History section while not being logged in.
2. Observe the section.

### Expected behavior
The Synced history button should be displayed even when the user is not logged in.

### Actual behavior
Synced history button is not implemented in the History section

### Device name
Samsung Galaxy S21 Ultra

### Android version
Android 11

### Firefox release type
Firefox Nightly

### Firefox version
95.0a1

![Screenshot_20211019-180632_Firefox Nightly](https://user-images.githubusercontent.com/42831109/137942858-3cd8338b-295b-43f6-bbd8-aecfc07e700d.jpg)

**Comment by gabrielluong** [comment]
I am not aware of any Product/UX requirement for this. I pinged @topotropic @athomasmoz about it, but please assume this is not needed for the time being.

**Comment by topotropic** [comment]
Thanks! This was part of the design but didn't get implemented – we'll do it in a future release. I'll close this issue.
