### ISSUE TITLE
934ms (108%) regression in time to raise keyboard when clicking URL bar (inflating homescreen behind awesomebar)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22027]
### STR
- Open app to browser screen
- Click URL bar

### Measurements
I took a screen capture of this interaction on release and nightly, aligned them when the "tap" target starts to fade, and placed them side-by-side with timestamps (release on the left):

https://user-images.githubusercontent.com/759372/138001660-1a37beaf-45cf-41d2-9cd7-a6923801c7ff.mp4

- Firefox 93.2.0 (current release): 866ms. https://share.firefox.dev/3lYnXsY
- Firefox Nightly 10/19: 1800ms. https://share.firefox.dev/3peUexT

There's an 934ms difference between the time when the tap is released to when the keyboard is fully in position (N.B. the exact timing may be off because this only one replicate & screen capture has overhead but the magnitude in the difference should be approximately correct).

---

**This regression is to be expected:** the functionality was changed to show the homescreen behind the search screen. We should explicitly decide if this regression is acceptable or not (1.8s seems like a long time to wait but keyboard interactions are frequently janky on this device). There may be some optimizations we can make like asynchronously inflating the homescreen content while we synchronously inflate the edit toolbar, or similar.

**Comment by hkaancaliskan** [comment]
What's the point of showing home behind search? If user wants to go home, user can tap to home icon. While there wasn't a dedicated home button, this was meaningful but now Fenix has home button and i think this move is unnecessary.

**Comment by mcomella** [comment]
Triage: the root cause is likely from the time to render the homescreen which we're improving in #22755. Closing as a dupe.

**Comment by allmeta** [comment]
I personally will never need to see homescreen when clicking the URL bar,
so I'm sticking with firefox 93.2.0 I guess T_T
