### ISSUE TITLE
[Bug]:  issues with adding tabs to homescreen

### ISSUE THREAD

**Issue by DrinkyCrow** [mozilla-mobile/fenix#22025]
### Steps to reproduce

1open tab
2find the site youd like to add to homescreen
3add site to homescreen
4 hours maybe days later the icons disappear

### Expected behaviour

The icons added to homescreen should remain and not disappear

### Actual behaviour

The icons i create on homescreen disappeared i dont know if this is due to storage management or what but i think this should be corrected so that it stays on your homescreen somehow??

### Device name

samsung galaxy s10+

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18382)

**Comment by plfstr** [comment]
I have experienced the same issue (Firefox Android, v94.1.1) after a phone reboot (battery flat), my homescreen PWA icons have disappeared. 

I am unable to re-add them either. Twitter.com > Install > Add Automatically etc. doesn’t work.

**Comment by sflorean** [comment]
@DrinkyCrow and @plfstr this is still reproducible on your side? Tested on latest Fenix builds with PWA's and with pages added to the Android home screen, and I wasn't able to reproduce it.

**Comment by DrinkyCrow** [comment]
It should be reproducible in those versions. it hasn't happened in any other recent updates. The problem for me with just adding them back however, is remembering what was lost to begin with. I tend to have quite a few of these icons myself.
