### ISSUE TITLE
Missing border radius of touch feedack (affects several elements on home screen)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#22022]
### Steps to reproduce

1. open Firefox home screen
2. long press elements on home screen

### Expected behaviour

When you do a long press on an element on the home screen there is some kind of "overlay" above the element (I don't know the correct term for this effect). It should match the form of the element.

### Actual behaviour

The border radius is missing and you can see _ugly corners_. It affects several elements on the homescreen:

- jump back in
- Pocket stories
- Pocket categories

The screenshot is from the Pocket stories:

<img width="703" alt="screenshot" src="https://user-images.githubusercontent.com/1100614/137978322-3e2eb03d-5f99-4dd2-abcf-317598b22d6c.png">

Additional notes:

- While the affect applies to the whole item in the above sections it only applies to a part in the recent searches section
- In the recent bookmarks section the effect is completely missing.

### Device name

OnePlus 7T Pro McLaren Edition

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

main branch revision f5431fbe01227cc3aedd460356d5d6bdd6f70701

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18380)

**Comment by cadeyrn** [comment]
It's still an issue.

**Comment by cadeyrn** [comment]
It's still an issue.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811612

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
