### ISSUE TITLE
[Bug]: There is no spacing between inactive tabs and active tabs

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#22021]
### Steps to reproduce

1. make sure you have inactive tabs
2. open the tabs tray

### Expected behaviour

Some spacing between inactive tabs and the first active tab.

### Actual behaviour

No spacing.

![Screenshot_20211017-093507](https://user-images.githubusercontent.com/1100614/137977292-b2d09c5f-27ef-4a97-a6dd-5888cb66bfa5.jpg)

### Device name

OnePlus 7T Pro McLaren Edition

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

main branch revision f5431fbe01227cc3aedd460356d5d6bdd6f70701

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18378)

**Comment by SoftVision-LorandJanos** [comment]
Hi @cadeyrn. Thank you for the report!
I can confirm that when selecting list view for the tabs, there is no spacing between the "Inactive tabs" section and the first active tab.

Tested on the latest Nightly (2021-10-20T05:12:07.893906).

Device used: Xiaomi Mi11 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Verified on the latest Nightly 101.0a1 (2022-04-20T17...) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.

**Comment by cadeyrn** [comment]
@SoftVision-LorandJanos It's still an issue. Please note that it's only reproducible in the list view, not in the grid view. And the first active tab should be selected so that the row has a background color.

**Comment by SoftVision-LorandJanos** [comment]
@cadeyrn yes, you are right, sorry! Thank you for pointing that out. I'm reopening the issue.

**Comment by cadeyrn** [comment]
It's fixed.
