### ISSUE TITLE
[Bug]: Addons page fails when there is a failing networking addon and there's no way to fix it (95.0a1)

### ISSUE THREAD

**Issue by ivan-aksamentov** [mozilla-mobile/fenix#22024]
### Steps to reproduce

1. Install Foxyproxy (or some of the other networking-related addons)
2. Have it misconfigured, such that there is no internet connection over the tunnel, and normal connection is not automatically restored either. This can be user's mistake, or if addon was updated or if the proxy provider changes something on their end.
3. Close Firefox and open again
4. Try to open "Addons" page from settings or from the menu
5. Observe "Failed to query addons" error and a blank page
6. Observe that there is no way to configure Foxyproxy now (or the offending networking addon in general) in order to fix the problem

### Expected behaviour

Addons page should not fail on network requests.

### Actual behaviour

Addons page fails entrely on broken network and there is no way to fix that, if the breakage is caused by an addon. Because there is no access to addons. Vicious circle.

### Device name

Does not matter

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

### Device logs

I don't think device logs would help. This is an issue with the flow in the logic of the addons page loading.

### Additional information

Listing and configuring installed addons is an offline functionality and should be available regardless of internet connection availability. 

This functionality can fail:
- installing new addons
- checking for updates
- updating addons
- reloading information about custom addon collection
- loading icons of addons

This functionality should never fail:
 - showing list of already installed addons
 - access to configuration pages of individual installed addons
 - disabling installed addons
 - deleting installed addons

**Comment by mdxe** [comment]
I get the same error message in Fennec v105.1 but it appears to be caused by something else because I dont use foxyproxy on mobile... I can't access the add-on manager until I find the cause.
