### ISSUE TITLE
[Bug]: Private browsing description has no padding on start/end

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#22032]
### Steps to reproduce

1. Click the private browsing icon on the home screen to enter PB mode.
2. Observe the PB description.

### Expected behaviour

There should be 16dp margin at the `start` and `end` of the `TextView`.

### Actual behaviour

There is none and the text touches the ends of the screen.

### Device name

All devices

### Android version

All versions

### Firefox release type

Firefox Beta

### Firefox version

93

### Additional information

This is a regression from https://github.com/mozilla-mobile/fenix/pull/21687

<img width="521" alt="Screen Shot 2021-10-19 at 10 03 48 PM" src="https://user-images.githubusercontent.com/1370580/138020277-ff2681a9-812d-4732-aec9-5a9779a6ae4a.png">

**Comment by jonalmeida** [comment]
Proposing this for the next sprint since it's a regression that we introduced during the 93 release that was uplifted.

**Comment by xlog-null** [comment]
Can I work on this please?
