### ISSUE TITLE
Support Split screen on Huawei Nova 7i

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/fenix#22048]
### Steps to reproduce

User selects to open Firefox for Android in split screen mode

### Expected behaviour

Firefox opens in split screen mode

### Actual behaviour

Error message that Firefox does not support split screen mode.

### Device name

Huawei Nova 7i

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

92

### Additional information

SUMO forum question (with images) https://support.mozilla.org/en-US/questions/1352216

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18396)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813689

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
