### ISSUE TITLE
Capture Long Screenshot

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#22049]
Please support the "Capture Long Screenshot" feature on the Android version of Firefox. (like Microsoft Edge)
https://winaero.com/capture-long-screenshot-in-microsoft-edge-on-android-full-page/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18397)

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1360136

**Comment by artisticfox8** [comment]
> User feedback: https://support.mozilla.org/en-US/questions/1360136

Saying the whole page as PDF and taking screenshot of some elements of the page are different features

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813690

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
