### ISSUE TITLE
FNX-5513 ⁃ View a tab group

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2205]
As a user, I'd like to _view_ my tab groups I've previously created on the home screen (underneath my current tabs). 

@bifleming: we didn't have a user story created for this, and it's a requirement for this feature. I've been working on it this week as a part of #1574, but this is less about the _creation_ flow and more about the end result of that (as seen in the [mocks here](https://mozilla.invisionapp.com/d/main#/console/16853870/359019534/preview)). Just wanted to have this work tracked somewhere. I've moved it into the current sprint, and I'd suggest it's sized at an 8 (based on the amount of work I've put in so far, and the work left). 

Not sure how this slipped through the cracks--perhaps there's a user story tracking this that I'm missing?

**Comment by bifleming** [comment]
@mheubusch could you take a look at this story and add some acceptance criteria for what you'd like to see?

**Comment by sblatz** [comment]
Waiting for some acceptance criteria from @mheubusch so I can move this to "QA needed"

**Comment by sv-ohorvath** [comment]
@mheubusch @sblatz no acceptance criteria defined here yet, but I started testing and saw one issue:
Open all tabs in a collection is not yet implemented and clicking it, directs me to this bug. Does it belong here?

**Comment by sblatz** [comment]
@mheubusch are we able to get acceptance criteria for this?

@sv-ohorvath the "opening" of a tab collection is covered by this ticket: https://github.com/mozilla-mobile/fenix/issues/2584

**Comment by sv-ohorvath** [comment]
New issue, which I think is related to this ticket: #2725

**Comment by sblatz** [comment]
@vesta0 are we able to close this ticket without #2725? I don't think it's feasible to have that done by Friday, and I don't think it should block.

**Comment by vesta0** [comment]
@sblatz thank you for being so thorough. I agree that #2725 is not a blocker. We can close this ticket.
