### ISSUE TITLE
[Feature] Deletion of browsing data when exiting app

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [mozilla-mobile/fenix#22064]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

We currently only have full browsing data wipe if we wipe data manually from the settings or enable deletion of data "when pressing Quit". I propose implement another toggle that when enabled, automatically wipe browsing data (or only store it temporaliry) after the browsing session is over and app has been "wiped" from the recents apps list.

### How do you know that this problem exists today? Why is this important?

I can see the lack of this option in the latest build. I think it's important because it would spare two additional button presses and would increase privacy and security.

### Who will benefit from it?

Those, who use Firefox as a temporary browser or homescreen shortcut opener for temporary tabs and/or sessions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18403)

**Comment by anuyts** [comment]
The options under 'tabs' should be grouped with the options under 'delete browsing data' and 'delete browsing data on quit'. For each item we should be able to choose
- never
- after a day/week/month
- on quit
- on exit
- there should be a button that says 'delete now'.

This is important. No other android app that I know of has a quit button (buried in a menu after scrolling down!). The hickup of tabs not closing when they should (for me that's upon exit by swiping) has me looking for another browser.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807538

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
