### ISSUE TITLE
Download dialog does not decode multibyte file name

### ISSUE THREAD

**Issue by FSpark** [mozilla-mobile/fenix#22062]
### Steps to reproduce

Download the test file here: https://wwa.lanzoui.com/iz4favlcrne

### Expected behaviour

Decoded as: 中文文件名测试.txt

### Actual behaviour

File name could not be decoded: %E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E5%90%8D%E6%B5%8B%E8%AF%95.txt

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 (Build #2015839563)

### Additional information

Only when `filename*` exists in `Content-Disposition` can the file name be decoded correctly, but if not, it can also be decoded on Firefox for PC and Chrome for Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18401)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 101.0a1 (2022-04-29) build.
Device used: Google Pixel 4 (Android 12).

**Comment by delia-pop** [comment]
This is still reproducible on the latest Nightly 105 from 07/28 with Google Pixel 6 (Android 12). Note that on Chrome the name of the file downloaded matches the Expected result. 

<img src="https://user-images.githubusercontent.com/89388888/181591006-43970949-14d7-4232-a47c-df3459e5600a.png" width="40%" />

**Comment by fice-t** [comment]
Found the problem: In Android Components' `DownloadUtils` there is `extractFileNameFromUrl` that calls `parseContentDisposition`, which returns a URL encoded filename (`%` escaped octets). Because of this, the `decodedUrl` segment in `extractFileNameFromUrl` is not run. 

Is there a reliable way for the procedure to check if it's indeed an encoded filename and then use `Uri.decode(filename)`? Or is it safe to use unconditionally?

CC @Amejia481 @csadilek

**Comment by Amejia481** [comment]
> `extractFileNameFromUrl`

Are you able to reproduce using the steps to reproduce [above](https://github.com/mozilla-mobile/fenix/issues/22062#issue-1032143319) ?

**Comment by fice-t** [comment]
Yes, I was able to reproduce using those steps and got the same result as shown [above](https://github.com/mozilla-mobile/fenix/issues/22062#issuecomment-1198380855).

I also was able to get the correct result (`中文文件名测试.txt`) by wrapping the filename with `Uri.decode`. My concern with that is some degenerate filenames that may look URL encoded but are not, but I don't know if that concern is valid.

**Comment by Amejia481** [comment]
I think it should be OK to decode the file name as long as we don't space in between words.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812793

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
