### ISSUE TITLE
FNX-5514 ⁃ [Bug] Issues with QAB

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#2206]
QAB:

* [ ] Does not start partially visible
* [ ] Possible to slide completely away
* [ ] Does not have a shadow between the browser toolbar and the QAB when it is partially visible

https://mozilla.invisionapp.com/share/K3RKVUJUG5B#/screens

**Comment by lime124** [comment]
I believe these bugs will impact the usability results? @shorlander @apbitner ?

**Comment by lime124** [comment]
FYI the answer is yes - the first two will. the shadow will not impact the study.

**Comment by lime124** [comment]
@vesta0 @colintheshots can we pull this in and get this fixed?

**Comment by sv-ohorvath** [comment]
New issue found: #2259

**Comment by apbitner** [comment]
@shorlander are we good to launch the QAB test despite the new issue found above?
