### ISSUE TITLE
[Bug]: Multiple links can be opened at once from "Thought provoking stories"

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22072]
### Steps to reproduce

1. Open the homepage
2. Tap and hold multiple articles from "Thought provoking stories" (between two and four works best)
3. Release and observe the tab tray

### Expected behaviour

The user can open each link, one at a time.

### Actual behaviour

Multiple links are opened in the tab tray

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 2021-10-21

### Additional information

https://user-images.githubusercontent.com/89511597/138305037-67798b92-30a3-41fc-9353-3425cc421c49.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18409)

**Comment by artisticfox8** [comment]
What's the problem with that? The user should be able to open as many stories as the user likes, IMO
