### ISSUE TITLE
MR2 telemetry: Additional recent bookmarks probes

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#22075]
https://mozilla-hub.atlassian.net/browse/FNXV2-18058

Improve telemetry for recent bookmarks on the home screen by adding probes to answer the following:
- Metric: how many recent bookmarks are shown?

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly 96.0a1 from 11/11 using a Google Pixel 3a (Android 11)

✔️  1 recent bookmark - Metrics ping d3b75d8b-3568-4506-8aa5-d5a7293b54f3 
`"recent_bookmarks.recent_bookmarks_count": 1,`
✔️  2 recent bookmarks - Metrics ping 407fef71-25c8-4655-9418-64d947045ce2
`"recent_bookmarks.recent_bookmarks_count": 2,`
✔️  3 recent bookmarks - Metrics ping d32a58a0-e06c-4fd8-acc1-47d0a8c1ffc7
`"recent_bookmarks.recent_bookmarks_count": 3,`
✔️  4 recent bookmarks - Metrics ping 7795dc59-7223-4a32-baf7-8c4f2a571870
` "recent_bookmarks.recent_bookmarks_count": 4,`
✔️  Deleted all recent bookmarks - Metrics ping d7b1aa19-af8a-4818-841f-442daae39a58
` "recent_bookmarks.recent_bookmarks_count": 0,`

[Logcat](https://github.com/mozilla-mobile/fenix/files/7519470/rcntbkcnt.txt)
