### ISSUE TITLE
[Bug]: Selecting search group in Jump back in switches active tab

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#22078]
### Steps to reproduce

1. Create a search group
2. Open another, non-related tab
3. Navigate to home
4. Tap on the search tile in Jump back in

### Expected behaviour

The search group in the tab tray should be in view. The tab in Step 2 should remain your active tab.

### Actual behaviour

The first tab in the selected search group becomes your active tab

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 96.0a1 (2021-11-05T05:12:49.870142).

Device used: Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.
