### ISSUE TITLE
FNX-5515 ⁃ [Bug] The search Engine Icon on the home screen search bar is not properly centered

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2208]
### Expected behavior
There is equal space above, below, and to the left of the search engine icon.

### Actual behavior
There is more space above and below the search engine icon than there is to the left.
![Screenshot](https://user-images.githubusercontent.com/32398857/57036917-1947af80-6c2c-11e9-9840-86c9baeedca5.jpg)UNITO-UNDERSCORE!20190501-141814!UNITO-UNDERSCORE!Firefox Preview!

### Device information
* Android device: 8.0
* Fenix version: 1.0.918

**Comment by Lululalu** [comment]
![Screenshot_20190503-002945_Firefox Preview](https://user-images.githubusercontent.com/32398857/57118583-9e20ef00-6d3a-11e9-8fab-6f562507e7cb.jpg)
It's worse on the lastest builds. Once you open the home screen by touching the tabs button the position of the icon on the address bar changes.

**Comment by vesta0** [comment]
@lime124 please confirm if this is intended or a bug.

**Comment by topotropic** [comment]
Current implementation looks good to me (field height 56dp, logo height 24dp, margin top + bottom 16dp, margin left 8dp, margin right 12dp).
(We don't have equal margin so that we can have a better transition once you scroll down)
