### ISSUE TITLE
[Bug]: Opening a link from a history search group should switch to the open tab if available

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#22080]
### Steps to reproduce

1. Create a search group
2. Navigate to the home screen
3. Open that search group under recent searches 
4. Open a tab from that list

### Expected behaviour

You should be taken to the already open tab.

### Actual behaviour

We open a duplicate tab.

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

**Comment by Mugurell** [comment]
Closing as a duplicate of https://github.com/mozilla-mobile/fenix/issues/22314 which already has a PR open.
