### ISSUE TITLE
[Bug]: Inconsistent hiding of the keyboard when scrolling homepage vertically depending on whether creating a new tab or using an existing tab

### ISSUE THREAD

**Issue by xlog-null** [mozilla-mobile/fenix#22096]
### Steps to reproduce

1. Create a new tab. The user will be taken to the homepage with the keyboard visible and input focus on the address bar.
2. Scroll the homepage vertically.
3. Compare the bevaviour to an existing tab - press the address bar in a tab that already had a website loaded.
4. Scroll the homepage vertically.

### Expected behaviour

On both tabs, the keyboard should hide automatically and the vertical scroll should work without issue.

### Actual behaviour

On the existing tab the homepage scrolls without issue, but the keyboard stays visible on screen. There is no way to close it, pressing back takes the user back to the tab's webpage.

When scrolling while creating a new tab, two actions are required from the user. The first scroll action hides the keyboard but disengages input from the homepage so the user, so the user has to perform a new scroll action to get desired behaviour. This was put in a seperate issue - #22019

### Device name

Samsung S21

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

### Additional information

Issue #22019 is about fixing the extra touch input required to scroll while creating a new tab. However there will still be inconsistency after that fix. I am creating this issue to ask whether this is actually incosistency, or whether it is a designed feature that the keyboard doesn't hide while scrolling homepage from an existing tab.

For now I am assuming that this indeed is an inconsistency and I will take up the task of fixing the problem by making the keyboard hide regardless whether scrolling from an existing or a new tab, however some reaffirmation would be appreciated that this is indeed the desired behaviour.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18432)

**Comment by marcel263** [comment]
Thank you for your contribution as the bug seems fixed
