### ISSUE TITLE
FNX-5517 ⁃ [Meta] History

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#221]
### Why/User Benefit/User Problem
As a user, I can retrieve and manage previously visited web content.

### Dependencies:
* [x] [History component](https://github.com/orgs/mozilla/projects/56#card-15875887) 

### Acceptance Criteria (how do I know when I’m done?)
-I can see a list of sites I’ve visited in the history section of the Fenix library.
-I can delete individual or all history items
~~I can see the addresses of sites I’ve visited when I begin typing an exact match on part of the URL in~~ the awesome bar.

**Comment by st3fan** [comment]
The A-C team is working on History Support, together with App Services. This includes recording of history, syncing of history, exposing history in autocomplete and in the awesomebar results.

A big piece that is missing is browsing and deleting of history. Both those need App Services work and A-C work. And possibly Fenix Frontend work.

**Comment by bbinto** [comment]
UX is in the library UI mocks

**Comment by bbinto** [comment]
Just local history for all sessions and not via sync (for milestone 2)

**Comment by sblatz** [comment]
https://github.com/mozilla-mobile/fenix/issues/18 is potentially another child ticket?

**Comment by boek** [comment]
@bbinto do we want to show the tab history anywhere? For example long pressing on the back button?

**Comment by bbinto** [comment]
Yes from product. adding @shorlander to provide feedback

**Comment by cpeterso** [comment]
Oops. I accidentally closed this meta issue by clicking on the wrong button in the Fenix project board.

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.
https://docs.google.com/spreadsheets/d/1RR9tIa8N9dJsyZ5EcUxEuGHsYCT63PAak2Jhtp_2f_A/edit?usp=sharing

**Comment by vesta0** [comment]
This feature is complete for MVP.
