### ISSUE TITLE
MR2 telemetry: Jump back in

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#22107]
https://mozilla-hub.atlassian.net/browse/FNXV2-18390

Add telemetry for the following: 
- Metric, boolean: Does the user see the Jump Back In section on the homepage

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly 96.0a1 from 11/11 using a Google Pixel 3a (Android 11)

✔️ Recent tabs / jump back in section is visible - Metrics ping 7e130271-2936-4534-a0ff-1b4ffff9bef2
`"recent_tabs.section_visible": true`

✔️ Recent tabs / jump back in section isn't displayed - Metrics ping 780d11db-8dc6-4590-bad5-9252cf282159
`"recent_tabs.section_visible": false`
