### ISSUE TITLE
Create a new tab if you swipe right at the end of the tab list

### ISSUE THREAD

**Issue by ScottBurfieldMills** [mozilla-mobile/fenix#22115]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

When swiping through tabs and the user reaches the end, swiping to the right (past the open tabs) I think it should create a new tab.

Example video of the current behaviour and where I would like to see it create a new tab: https://streamable.com/6bzopb

I have had a look at the Web Extensions API to see if it is possible to detect/hook into that swipe event but haven't had any success. If that is an option then I could create an extension to handle this use case.

### How do you know that this problem exists today? Why is this important?
This is a UX improvement that will remove a couple button clicks.

### Who will benefit from it?
General UX improvement for users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18446)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813691

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
