### ISSUE TITLE
Search suggestions block 64-130ms on UI transitions before fetching when typing characters in the awesome screen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22110]
## Steps to reproduce
- Start a profiler
- Type characters in the URL bar

### Expected behavior
Search suggestions occur immediately after characters are typed

### Actual behavior
Search suggestions block on UI transitions before being executed. Here are profiles:
- 64ms delay (timing via profiler) when typing "a" as the first character in the url bar: https://share.firefox.dev/3jvxRAB
- 130ms delay (timing via profiler; it may not always be this high) when typing "f" as next character in url bar: https://share.firefox.dev/3Gbhzq9

**This is a very large delay:** the search provider network request is a total of 156ms and 96.5ms in the profile. Note that these profiles are using unmerged markers from https://github.com/mozilla-mobile/android-components/issues/11161 as well as so far local-only markers for measure/layout/draw.

While this algorithm (block for UI transitions before fetching new providers) is not a regression, the durations have likely regressed due to the Compose implementation in v94+ (see #22020).

### Device information
* Android device: Moto G5
* Fenix version: upstream main a1ace964de29b259c9511328975fd17ac2b7c8ab

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18442)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807341

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
