### ISSUE TITLE
[Bug] Latest update changed the way my default search engine (Startpage) behaves

### ISSUE THREAD

**Issue by Scoffalot** [mozilla-mobile/fenix#22111]
Dear Firefox Android team,

I have been happily using firefox for android for some years now as my default browser, thanks for your good work! I like the recent slimmed down-version.

I would like to signal what seems to be a very small "bug" that appeared with the latest update 93.2.0 (Build #2015839747)
AC: 93.0.12, e39f5dba3f
GV: 93.0-20210927210923
AS: 82.1.0
2021-10-14T16:11:52.718145

My default search engine is Startpage. I always enter my search text in the your app's address bar (as this allows your app to also search browsing history, bookmarks, etc). Until very recently the search results from Startpage appeared immediately.

However, since the last update, after entering the search text and clicking "enter", only the empty  Startpage home page appears, ie with no results (see screenshot attached), and I then have to re-enter the search text into Startpage home page's search bar, which is a bit frustrating.

It would seem that the firefox address bar doesn't transfer the seach text to Startpage, as it used to. 

I hope you can find time to sort this out, but it's not very urgent! In the meantime I have put google as my default, as the results from the search text entered into the address bar appear immediately. For info, my tablet is Samsung Galaxy tab S7+ under android 11.

Thanks again for your great app.

![Screenshot_20211023-101255_Firefox](https://user-images.githubusercontent.com/93034058/138551347-0e1ee5c3-2532-422c-a1a4-626b57d187f9.jpg)

**Comment by amedyne** [comment]
@Scoffalot , @ckroenicke Can you help confirm/validate if you are still having the same problem with the latest version of Firefox, 93.2.0?

**Comment by Scoffalot** [comment]
@amedyne, I was already using 93.2.0 when I first got the bug (and still have it) and then posted (see first post above). @ckroenicke had a different problem, but I don't know if he/she updated since then.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Preview Nightly 2021-11-02. I was not able to reproduce the issue using the search query provided by the website (https://www.startpage.com/sp/search?query=%s) only when using https://startpage.com/search?q=%s as a search query the issue occurs.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by Scoffalot** [comment]
@LaurentiuApahidean, Indeed, looking at the History page, it would seem that if you enter a text (eg zut) in the address bar, it generates a search query .../search?q=zut which only opens a blank search page. If you enter zut into the search page bar, it generates .../sp/search?query=zut and you get a nice long list of search results.

**Comment by csadilek** [comment]
@Scoffalot It looks like `Startpage` is not configured correctly as a custom search engine in your Firefox. You can follow these instructions to set it up: https://support.startpage.com/index.php?/en/Knowledgebase/Article/View/1094/0/how-do-i-make-startpage-the-default-search-on-firefox-mobile-android-ios

Or if already configured, verify that the search URL ends with `?query=%s` and not `?q=%s`.

**Comment by Scoffalot** [comment]
@csadilek  Thanks, that worked! 
The funny thing is that before the last update I didn't have any problem with Startpage as my default and searching in the address bar.
IT indeed works in mysterious ways.
Thanks again, problem solved.

**Comment by csadilek** [comment]
Thanks for verifying @Scoffalot. I can't explain that either, but would think that may have been due to a change on startpage.com which may have supported `q=` at some point? Glad it works now!

**Comment by ckroenicke** [comment]
@amedyne, @cadeyrn:
The update to version 93.2.0 fixed the crash, but then I experienced the same strange behavior @Scoffalot described.

The url I used was "https://www.startpage.com/do/dsearch?query=%s".
Changing it to "https://www.startpage.com/sp/search?query=%s" fixed the problem for me.

Thanks to @LaurentiuApahideanSV and @csadilek for the tip!
