### ISSUE TITLE
[Bug]: fenix no longer suggests the plain domain when typing URL

### ISSUE THREAD

**Issue by ceisserer** [mozilla-mobile/fenix#22121]
### Steps to reproduce

1. Open a new Tab using firefox nightly 95a1 on Andoird
2. Start typing a URL of a domain, which has been visited before
3. to refer to the attached screenshot - despite phoronix.com has been visited and entered exactly this way - only articles of phoronix with a full path are suggested (and only 3 in this case). The plain domain is not suggested.
4. Because the plain domain is not suggested, the suggestions provided by fenix are useless and I have to type the domain-name myself.

### Expected behaviour

As previous versions of fenix (94?), suggestions should include the domain itself, too.

### Actual behaviour

only three seemingly random suggestions are made.  

### Device name

Dony Xpera XZ1 Compact

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18449)

**Comment by delia-pop** [comment]
Hi @ceisserer,
I was not able to reproduce the issue you described on Firefox 99.2.0 and latest Nightly from 04/27. On my end, upon previously accessing and closing web pages from phoronix.com, during the next search attempt, the entire domain (phoronix.com) is autocompleted and previously accessed links suggested.
Could you please re-test the issue using the latest Nightly build? 
Device used: Motorola Moto G30 (Android 11).

**Comment by ceisserer** [comment]
Indeed, this issue seems to be a mistake on my side - I can not reproduce it on my new phone, so it must have been a configuration issue. Sorry for the noise...
