### ISSUE TITLE
Refined search in result page may be added to wrong search group

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22129]
### Steps to reproduce

- Do some related searches
- Observe the "Recent searches" section now containing them
- Go to history

### Expected behaviour

The new search group from homescreen should also appear in history

### Actual behaviour

The new search group from homescreen does also appear in history.
Happens intermittently. Sometimes the new groups also immediately appears in history as expected.

### Android version

12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly

### Additional information

https://user-images.githubusercontent.com/11428869/138690953-e6554a35-41ac-4dee-b273-6a88c96f8fe9.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18453)

**Comment by AndiAJ** [comment]
Reproducible on Firefox 95.0.0 Beta 1 using a OnePlus A3 (android 6.0.1)

With this STR:
1. Search for "cat"
2. Open one of the result
3. Go back to the search results
4. Open another result
5. Open the tabs tray
6. Close the tab
7. Check the home screen
8. Check History

The search group is missing from History

► Video

https://user-images.githubusercontent.com/51314259/140309754-5b88aa1b-8991-407a-98dc-a06d0843ec30.mp4

**Comment by delia-pop** [comment]
Reproducible on Beta 100.0.0-beta.4 with Google Pixel 6 (Android 12). The second search accessed before closing the tab is not grouped in History.

![Screenshot (Apr 13, 2022 9 56 59 AM)](https://user-images.githubusercontent.com/89388888/163118227-e56cb100-fc4c-41d3-8a70-86db27156e4d.png)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813105

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
