### ISSUE TITLE
Bimodal results in COLD VIEW start up time to nav start (200ms improvement opportunity?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22144]
In our [start up testing results](https://earthangel-b40313e5.influxcloud.net/d/s3AT6t7nk/fenix-startup-nightly-via-backfill-py?orgId=1&from=now-90d&to=now), we see what appears to be a regression of 137ms between 10/23 and 10/24 in COLD VIEW.

![image](https://user-images.githubusercontent.com/759372/138755144-12eedc81-7898-4d52-a4ea-2d8f7d8d4fc1.png)

However, when I look at the results from 10/23 graphed, we see that there is a bimodal distribution:

![10_23](https://user-images.githubusercontent.com/759372/138755394-6d6b5a95-cf34-43e8-bd48-7c1879744284.png)

We see a "regression" because our results take the median and, in this particular run, we took the poor performance case in over 50% of the runs for the first time. This pattern continues back at least a month: here is a run from 9/22:

![9_22](https://user-images.githubusercontent.com/759372/138755516-37ce3e49-02bb-40bb-9300-e4bac18a070e.png)

I'm not seeing this pattern in:
- Late July
- COLD MAIN start up
- Focus start up, even COLD VIEW

### Problem
Bimodal behavior is bad for users because it implies there is an optimization we can make to improve their performance in a non-trivial number of cases (e.g. 50% as of 10/24).

Bimodal behavior is bad for us because, when we're on the threshold, it makes performance testing return inconsistent results, making it difficult (or impossible) to detect real regressions.

### Possible causes
This could be related to:
- the start up cache fixes and our methodology change
- whatever caused the increase in variability we've observed in results https://github.com/mozilla-mobile/fenix/issues/21853

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18461)

**Comment by mcomella** [comment]
I wonder if the bimodal behavior could be related to [bug 1734916](https://bugzilla.mozilla.org/show_bug.cgi?id=1734916), where GeckoView waits on the UI thread before continuing the request because the ALLOW/DENY request callbacks are running on the UI thread.

**Comment by mcomella** [comment]
We still see this on recent runs but more of the replicates are above the break in results than before. From 12/11 VIEW:
![image](https://user-images.githubusercontent.com/759372/145888533-c2a945bf-26a2-4f46-8872-75fe6333f7f9.png)

**Comment by mcomella** [comment]
This still exists **but the improvement looks to be around 200ms**. Here are the 9/11 results (which demonstrates it more than some adjacent dates):
![image](https://user-images.githubusercontent.com/759372/190463256-837fb061-8391-4150-9753-7ba102a2c34d.png)

Notice we're much more likely to run into the slow peaks which is why we don't bimodal behavior in our day-to-day nightly results. However, we can observe it over a longer period of time by comparing our lowest ever values, when the bimodal biased towards the fast valleys around 2022-05, to our current values where there is a difference of ~230ms:
![image](https://user-images.githubusercontent.com/759372/190464158-69b90e34-9717-425b-bd62-73240d4051b7.png)

**Comment by MarcLeclair** [comment]
Triage: We should figure out if this trends happens on other devices.  I'll try the A50

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807342

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
