### ISSUE TITLE
Annoy Tab Open

### ISSUE THREAD

**Issue by PseudonymIII** [mozilla-mobile/fenix#22143]
### Steps to reproduce

1. open [duckduckgo](https://duckduckgo.com)
2. open[ settings](https://duckduckgo.com/settings)
3. make sure "**Open Links in a New Tab**" button is **ON**
4. close all tabs and windows
5. add duckduckgo to your default search engine
6. try search some things
7. after resulting appearing click random results(until you found the probelm) 

### Expected behaviour

most of times you can see when you click a new results in duckduckgo and opening in new tab you can see the 2 or more duplicates tabs of opening link opened and if you close one of them, others not work and when you try to open them they just show stuck version of duckduckgo(you seached before) and you can't even scroll or other things!
some times when you click link from results firfox open about:blank duplicates!

i found this problem in recent version of firefox also see anony bug.zip pictures.
note that duplicate tabs not works only original one will work.
[Anony Bug.zip](https://github.com/mozilla-mobile/fenix/files/7412636/Anony.Bug.zip)

### Actual behaviour

just open results in new tabs correctly!

### Device name

poco x3 pro, redmi note 8, redmi note 9 pro, redmi note 9s, redmi 9c

### Android version

Android 10,11

### Firefox release type

Firefox

### Firefox version

93.2.0
94.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18460)

**Comment by LaurentiuApahideanSV** [comment]
I managed to reproduce the issue on both RC 95.1.0 and Nightly 2012-12-07. I could not find exact repro steps but managed to reproduce it reliably although rarely by opening a tab from a duckgogo search page, closing it very quickly and opening a new one (with the option to open pages in new tabs on).
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
