### ISSUE TITLE
FNX-5519 ⁃ [Bug] On Fresh Install, Fenix Opens in Private Mode

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#2214]
## Steps to reproduce
1. Clear data or uninstall
1. Open Fenix

### Expected behavior
Should be in normal browsing 

### Actual behavior
In private mode

### Device information
* Android device: Pixel
* Fenix version: Master

**Comment by vesta0** [comment]
This is fixed.

**Comment by joebloggs7657** [comment]
@vesta0  Unfix and make into an optional feature? 😂

**Comment by vesta0** [comment]
@joebloggs7657 we will build that feature here #419  :)
