### ISSUE TITLE
MR2 telemetry: Start on home preferences

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#22145]
## What questions will you answer with this data?

Implement telemetry to help us know which Start On Home settings are being used (Homescreen three-dot menu -> "Customize home" -> "Opening screen" section) 

This should be a Metric with a string that says what the current setting is: 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/43795363/138767695-7e1a8a61-b5f3-4793-8149-e65fda319c1d.png">

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Nightly 96.0a1 from 11/11 using a Google Pixel 3a (Android 11)

Opening screen preference set to:

✔️ "Homepage after four hours of inactivity" - Metrics ping ab7750e1-c2f3-4c8c-af44-4c7aa75e7392
`"customize_home.opening_screen": "homepage after four hours",`

✔️ "Last tab" - Metrics ping ae77208a-ce00-4b52-a556-437d32c0fbd3
`"customize_home.opening_screen": "last tab"`

✔️ "Homepage" - Metrics ping 20eec40d-afc7-44f5-b9cd-aec044e4e38f
`"customize_home.opening_screen": "homepage"`

[Logcat](https://github.com/mozilla-mobile/fenix/files/7519888/prf.txt)
[Glean dshboard](https://debug-ping-preview.firebaseapp.com/pings/AJ1111001)
