### ISSUE TITLE
MR2 telemetry: inactive tabs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22155]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-18425

--- 
We currently have `tabs_tray.has_inactive_tabs`, which is an Event with an extra for the count (`inactive_tabs_count`), but we want to split this out into two separate metrics. `has_inactive_tabs` does not need to be removed yet, that will happen in another issue.

Probes to implement: 

    Metric - boolean: Is the inactive tabs section showing?

    Metric - counter: How many inactive tabs does the user have?
    
-------

After talking with Kimmy we'll only go with one new probe: `inactive_tabs_count` sent in the metrics ping.
Whether the inactive tabs feature is enabled or not is already tracked by https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/preferences_inactive_tabs_enabled

**Comment by Mugurell** [comment]
Removing QA since the current implementation based on [Jon's comment](https://github.com/mozilla-mobile/fenix/pull/22163#discussion_r742482956).

**Comment by Mugurell** [comment]
This should be ready to test.

**Comment by AndiAJ** [comment]
Hi @Mugurell , I've just checked this matter on the latest Nightly 96.0a1 from 11/11 using a Google Pixel 3a (Android 11)

It looks like the inactive tabs counter from the metrics ping remains set to 0.

❌  3 inactive tabs - Metrics Ping 95c8ef82-c3e7-43f6-8844-6edcaa89e8b7
`"metrics.inactive_tabs_count": 0`

![image](https://user-images.githubusercontent.com/51314259/141290333-fb107292-67e9-405f-b4a3-d1a993482a64.png)

[count.txt](https://github.com/mozilla-mobile/fenix/files/7520014/count.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ1111004)

I'll re move the QA needed label until further notice.

**Comment by Mugurell** [comment]
Thank you Andi!
There was indeed an issue with when we were trying to read the number of inactive tabs. 
We'll now set this when the user opens tabs tray, which should happen more times in the day and so there should definitely be data for the `metrics` ping.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly build 96.0a1 from 11/19 using a Google Pixel 3a (Android 11)

✔️  3 inactive tabs - Metrics ping c70521b1-6833-498c-8e71-db69795e51cc
`"metrics.inactive_tabs_count": 3`

[Logcat](https://github.com/mozilla-mobile/fenix/files/7568609/incnt.txt)
