### ISSUE TITLE
[Bug]: History/Home Search Group tabs created from Google are duplicated

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#22158]
### Steps to reproduce

**[Prerequisites]:**
- Have the Recent searches section enabled. Testing was performed while enrolled in the [All Users Home Screen Android Production](https://experimenter.services.mozilla.com/nimbus/all-users-home-screen-android-production) experiment using the secret menu.

**[Steps]:**
1. Perform a Google search using the URL bar..
2. Long-press one of the results and tap “Open link in new tab”.
3. Tap “SWITCH” to switch to that tab.
4. Go to the homepage.
5. Tab the search group displayed for that search and observe the History entries

### Expected behaviour

- There are no duplicate entries in a search group.

### Actual behaviour

- Entries are duplicated. One is displayed as the page itself and another one is the search engine result URL that leads to the page.

### Device name

Samsung Galaxy S8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

Firefox Release null (AC: 94.0.10) (Build #2015842003) (built 10/26/2021)

### Additional information

- I was not able to reproduce this issue for Bing or DuckDuckGo.
- The search itself is not displayed in the search group.
- Attached is a [recording of the issue](https://drive.google.com/file/d/1Qfrr4pZpBtunmw12DsZYFxd23I-1bZQJ/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18471)

**Comment by SoftVision-LorandJanos** [comment]
Hi @heres-maria  ! Thank you for the report!
I could reproduce the issue you described on the latest Nightly (2021-11-01T05:11:04.075119).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Xiaomi Mi11 Lite (Android11).
