### ISSUE TITLE
[Bug]: incorrect video scale

### ISSUE THREAD

**Issue by ikhoeyZX** [mozilla-mobile/fenix#22157]
### Steps to reproduce

1. open any web that contain videos, this is my test link https://m.youtube.com/watch?v=KjfB6L0mRgU
2. play it
3. and video show wrong size with green screen in video background
4. older firefox mobile (87 or older) can play normaly

### Expected behaviour

video show exact in frame

### Actual behaviour

video show small size with green background

### Device name

Asus Zenfone 5 (T00F)

### Android version

Android 7.1.2

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

![Screenshot_20211026-182809](https://user-images.githubusercontent.com/79812109/138861224-a3a36ca8-486b-4454-bb47-7ab82bff6bed.png)

firefox nighty also tested and have same issue

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18470)

**Comment by Darkspirit** [comment]
If you open about:support in the address bar and search for "Compositing" (Main menu > Search in page), does it say "WebRender" or "WebRender (Software OpenGL)"?
