### ISSUE TITLE
[Bug]: The text on "Customize homepage" button is truncated when system font size is set to large

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22160]
### Steps to reproduce

1. Open device settings and choose the highest font size
2. Open Firefox homepage
3. Scroll down to the "Customize homepage" button
4. Observe the font

### Expected behaviour

The font is fully visible

### Actual behaviour

The font is truncated

![248809882_247440947435434_3451933037421738534_n](https://user-images.githubusercontent.com/89511597/138890058-286f0722-342f-4388-af1a-ba1efeb1c10f.jpg)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 2021-10-26

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18472)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest RC 107.1.0 and latest Nightly 108.0a1 (2022-11-14) builds.
Device used: Oppo Find X5 (Android 12).
