### ISSUE TITLE
FNX-5520 ⁃ [Bug] Secure connection failed on Sign in page

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2216]
## Steps to reproduce
This is not easy to reproduce, I saw this once before, on the same device: Pixel (Android 9).
Signed in and synced last time on Tuesday 4/30.
After 1.5 days of not using the device, on Thursday 5/2, I've updated the app.
In Settings>Account, tried to sync, didn't work.
Sign out. Sign in.

### Expected behavior
The account should still be signed in after a period of not using the app.

### Actual behavior
In Settings>Account, I wasn't seeing the account email, just "Firefox account". 
Sync didn't work, it kept showing "2 days ago". 
After a sign-out and trying to sign back in, the accounts.firefox.com page returns a "Secure connection failed" error.
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3137333/sign.in.-.logcat.txt)

### Device information
* Android device: Pixel (Android 9)
* Fenix version: 5/1 build

**Comment by vesta0** [comment]
@vladikoff do we know what might be causing this bug?

**Comment by kbrosnan** [comment]
Sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1546361

**Comment by vladikoff** [comment]
> @vladikoff do we know what might be causing this bug?

Yeah, we should keep an eye on https://bugzilla.mozilla.org/show_bug.cgi?id=1546361 

I've seen this happen, but I don't think it has anything to do with the FxA component

**Comment by ekager** [comment]
Closing because I don't think this is a problem anymore. Please reopen if it is
