### ISSUE TITLE
Consider adding telemetry to see which accessibility services are enabled

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#22169]
This would help us track impact of our efforts to improve accessibility within Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18474)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802972

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
