### ISSUE TITLE
MR2 telemetry: Recent searches (prev. recently visited)

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#22172]
Acceptance Criteria

Add telemetry for the following: 

    Metric Counter with extra: Number of times a search term group is clicked on from Recently visited

        Extra: what page is it on?

    Metric boolean: Is the recently visited section visible

**Comment by AndiAJ** [comment]
Hi @rocketsroger , I've just checked this matter on Firefox 95.0.0 Beta 1 using a OnePlus A3 (Android 6.0.1)


❓  Tap on recent searches from the home screen
I have 3 recent searches on the home screen, and opened each of them one by one.
When the event type ping is generated it seems that the `"page_number"` remains set to 1 

```
{
          "timestamp": 2314,
          "category": "history",
          "name": "recent_searches_tapped",
          "extra": {
            "page_number": "1"
          }
        },
        {
          "timestamp": 3424,
          "category": "home_screen",
          "name": "home_screen_displayed"
        },
        {
          "timestamp": 4289,
          "category": "history",
          "name": "recent_searches_tapped",
          "extra": {
            "page_number": "1"
          }
        },
        {
          "timestamp": 5141,
          "category": "home_screen",
          "name": "home_screen_displayed"
        },
        {
          "timestamp": 5791,
          "category": "history",
          "name": "recent_searches_tapped",
          "extra": {
            "page_number": "1"
          }
        }
```

✅ Recent searches enabled
`"customize_home.recently_visited": true`

✅ Recent searches disabled
`"customize_home.recently_visited": false`

Please review and share your thoughts ☺️

**Comment by rocketsroger** [comment]
> Please review and share your thoughts ☺️

Yes, that is the correct behaviour.  The page number is the column that the recent searches is on.  So for searches number 1-3 they are on page 1.  4-6 are on page 2.  7-9 is on page 3.  Try with 9 searches and you'll see the changes in the page number. Thanks,

**Comment by AndiAJ** [comment]
All good, thanks @rocketsroger !
 
```
       {
          "timestamp": 3355,
          "category": "history",
          "name": "recent_searches_tapped",
          "extra": {
            "page_number": "1"
          }
        {
          "timestamp": 6812,
          "category": "history",
          "name": "recent_searches_tapped",
          "extra": {
            "page_number": "2"
          }
        {
          "timestamp": 13440,
          "category": "history",
          "name": "recent_searches_tapped",
          "extra": {
            "page_number": "3"
          }
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/7475606/rcntss.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-04110)

**Comment by rocketsroger** [comment]
@AndiAJ Thanks!
