### ISSUE TITLE
FNX-5521 ⁃ Do raptor performance testing on a schedule

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-mobile/fenix#2218]
Right now, we run our raptor performance tests on every commit that lands on `master`.
As requested by Joel Maher via email, we should run these tests on a schedule (e.g.: nightly, or twice a day).

@jmaher can you confirm what schedule you'd like the tests to run? Twice a day? If you want to provide a cron string, that would work :grinning:

**Comment by jmaher** [comment]
I would like once/day for now, maybe:
00 01 * * *

**Comment by mitchhentges** [comment]
This depends on #2258

**Comment by mitchhentges** [comment]
I'll be able to look into this tomorrow, other Fenix automation PRs have just been merged

**Comment by mitchhentges** [comment]
There's currently an issue with a package-rename that's causing raptor tests to fail, I need to handle this issue before I can handle this schedule-change
