### ISSUE TITLE
show key symbol to save or update password

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22182]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
In some sites after entering username and password when it moves to the next page it does not show the option to save the credentials. In desktop version there is a persistent key symbol to save/update the credentials if not saved for the site or not updated..can u please add similar option in android version? The url bar is really small to accomodate the key icon ..maybe it can be added under site settings or 3 dot menu or maybe in url bar..whatever you like but please add the option

### How do you know that this problem exists today? Why is this important?
Difficult to save or update password for a site..it should be handled automatically or provide an option to user to save

### Who will benefit from it?
All users
![P_20211027_150800_1](https://user-images.githubusercontent.com/58127841/139040865-b7538b76-cd58-4dcc-8447-96441c2683fe.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18484)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813692

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
