### ISSUE TITLE
Consider introducing a setting that allows users to disable History Search Groups

### ISSUE THREAD

**Issue by heres-maria-sv-inactive** [mozilla-mobile/fenix#22181]
**[Versions used]:**
- Firefox Release 94.1.0 (Build #2015842083)
- Firefox Nightly 95.0a1 (Build #2015841963)

**[Platforms used]:**
- Samsung Galaxy S8 - Android 9

**[Scenario Steps]:**
1. Perform a search using the URL bar.
2. Long-press one of the results and tap “Open link in new tab”.
3. Tap “SWITCH” to change tabs.
4. Repeat steps 2 and 3 a few times to create more search group entries.
5. Open the History view.
6. Open the settings menu and try to find a setting to disable History Search groups.

**[Proposed result]:**
- As a user, I would like to be able to disable search groups from history. I do not like having to open an additional folder to access part of my history, especially if very recent.

**[Current result]:**
- I have not seen a toggle that allows users to disable History Search Groups at the moment. 
- The Recent searches section from the homepage can be disabled, but it does not affect the search groups created in history. In Nightly 95.0a1 a toggle for the tab version was also introduced for #21360, but it does not disable search groups from the history view. 

**[Notes]:**
- I am including a screenshot of the feature I would like to be able to disable.

![image](https://user-images.githubusercontent.com/53752296/139032961-05039da3-63f1-4808-ae5c-099a5560f7d8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18483)

**Comment by SoftVision-LorandJanos** [comment]
Hi @heres-maria. Thanks for the report!
I can confirm the behavior is as you described.
I will add a Feature request label.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1358349

**Comment by MintMain21** [comment]
If I may, the UI for the Tab Groups is in itself very nice, and the automation of tab grouping is also developing very nice, bit something I would appreciate is using this UI to allow custom tab groups, and in turn the option to move tabs between different tab groups. This can co-exist with the current behavior, and even compliment it, as users can both benefit from the automated behavior and rectify it when they are unhappy with it.

**Comment by cyatarow** [comment]
Is there any progress on this issue?

**Comment by L0to** [comment]
Please do this! I stopped using forefox android before because of the lack of a bookmark or history search. Now that I can do that I just want to be able to view my history in a clean chronoloigical view. Currently navigating history and actually finding anything is anightmare because of the random grouping.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813104

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
