### ISSUE TITLE
[Bug]: (critical) update/save password dialog getting popuped for each character typed or deleted in password field

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22180]
### Steps to reproduce

Signout from a website
In the password delete one character it will trigger the popup. after dismissing the popup when another character is deleted it is again triggering the popup

Similarly in a new site when entering a password every character typed is showing the popup dialog to save password

This is getting irritating. Please fix

### Expected behaviour

Password update or save menu should popup on going to next page

### Actual behaviour

Popup getting triggering for each character typed or deleted

### Device name

asus rog 3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Additional information

![Screenshot_20211027-094803128 (1)](https://user-images.githubusercontent.com/58127841/138999245-13875f15-a187-46bd-bdcf-72ccc7e458c1.jpg)

**Comment by sheikh-azharuddin** [comment]
This must be fixed..too irritating
Here is the video


https://user-images.githubusercontent.com/58127841/145664619-be63d869-f58d-4961-b8f3-95ed27d0917a.mp4

**Comment by sheikh-azharuddin** [comment]
@Amejia481 pls help🥺

**Comment by Amejia481** [comment]
@sheikh-azharuddin could you share a screenshot of your about Firefox page?  You could see it by going to *Settings* -> *About Firefox*

**Comment by sheikh-azharuddin** [comment]
Interestingly this issue is not there in latest firefox beta..

**Comment by sheikh-azharuddin** [comment]
Seems some about:config causing issue..
I have installed it freshly..no issue
Hence closing it

Thanks
