### ISSUE TITLE
[Bug]: "Jump back in" and "Recent bookmarks" options are focused when tapping on "View" after creating a collection

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#22186]
## Prerequisites
"Jump back in" and "Recent bookmarks" options are enabled on homescreen.

### Steps to reproduce

1. Open tabs tray and add a tab to collection 1.
2. Tap on "View" from the snackbar.

### Expected behaviour

The collection 1/new tab added is focused.

### Actual behaviour

"Jump back in" and "Recent bookmarks" options are focused.

### Device name

Pixel 3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1, 94 Beta, 94.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18486)

**Comment by mcarare** [comment]
To be handled after the merging of home screen improvements refactoring.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 104.0a1 (2022-07-20) build.
Each time a new collection is created and "View" tapped, the focus is on the newly created collection.
Although the collection is focused, it's not expanded for the added pages to be visible.
Device used: Google Pixel 4 (Android 12).
Marking this as verified.
