### ISSUE TITLE
Intermittent UI test failure - SettingsPrivacyTest.launchPageShortcutInPrivateModeTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#22188]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4612252897723412312/executions/bs.dc4b1fbad9f4b79d/testcases/1/test-cases
### Stacktrace:
`java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 242635902 Other activity: HomeActivity hashcode 134729616`
### Build: 
Debug 10/26

Crash reported here: https://github.com/mozilla-mobile/fenix/issues/21030

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18487)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5034637347635622287/executions/bs.340a67bd24f448bc/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: for text= "TestShortcut"
at androidx.test.uiautomator.UiCollection.getChildByText(UiCollection.java:126)
at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:215)
at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:190)
at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut$shortcut(AddToHomeScreenRobot.kt:77)
at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:78)
at org.mozilla.fenix.ui.SettingsPrivacyTest.launchPageShortcutInPrivateModeTest(SettingsPrivacyTest.kt:325)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7069559009155807900/executions/bs.bf9bba7620495147/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5174746648224360828/executions/bs.8b6f4035e2775a1c/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6437458115821522986/executions/bs.331e5fbad81aca52/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5685192328225647796/executions/bs.2b6ae4c1d7107396/testcases/1)

**Comment by AaronMT** [comment]
Failure on 4/27 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4732887427710658830/details?stepId=bs.aa13be1587969ea5&testCaseId=1)

Seems to be more frequent based on the dates here.

**Comment by AndiAJ** [comment]
Flaky 1x on 4/27 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7426066978220056767/executions/bs.ac82b6bd766376b5/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Since changing to an API 30 device, the search on the home screen is done differently and the device scrolls up/down instead of left/right resulting in the page shortcut not being found.
