### ISSUE TITLE
[Bug]: The homepage "Jump back in" message will sometimes be higher than expected

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#22191]
### Steps to reproduce

1. Open Firefox.
2. Navigate to a website to create a tab.
3. Tap the Firefox icon to enable the secret menu.
4. Change to the Preview Collection from Secret Settings.
5. Close and reopen the app thrice (this should enroll you in this process in the [All Users Home Screen Android Production](https://experimenter.services.mozilla.com/nimbus/all-users-home-screen-android-production) experiment).
6. Navigate to the homepage.

### Expected behaviour

- The homepage message is displayed directly above the “Jump back in” section.

### Actual behaviour

- The homepage message is displayed slightly higher than the "jump back in" section.

### Device name

Samsung Galaxy S8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

Firefox Release 94.1.0 (Build #2015842083)

### Additional information

- Attached is a [recording ](https://drive.google.com/file/d/12fBXs1UjjAc8WJSvBUSKPCmw8UXgWHwK/view?usp=sharing)of the issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18489)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 102.0a1 (2022-05-09) build.
![Screenshot_20220509-171007](https://user-images.githubusercontent.com/48829350/167428786-2e30cdc2-4c93-4e28-adcb-751988ef41ee.png)
Device used: Google Pixel 4 (Android 12).
