### ISSUE TITLE
FNX-5523 ⁃ [Meta] Custom Tab Support

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#222]
### Why/User Benefit/User Problem
As a user I want to be able to tap on a link within an app, launch a site with my default browser (Fenix) without leaving the app, and close the site to return to the app.

### What / Requirements
~~UI mock~~ups
~~Android Component: https://github.com/mozilla~~mobile/android-components/issues/1398

### Acceptance Criteria (how do I know when I’m done?)
-Customizable tab allowing to add toolbarcolour and menu items.
~~Allow for pre~~starting Fenix and pre-fetching content for faster loading.

**Comment by jonalmeida** [comment]
The original link was pointing to a sub-task for an r-b user story (which is similar-ish to a meta): https://github.com/mozilla-mobile/reference-browser/issues/137

**Comment by bbinto** [comment]
Need to chat with UX (@lime124) if we need any specific UX for this or can we use what A/C has done, @st3fan should have a bit more information

**Comment by bbinto** [comment]
Feature parity to Focus (minus the issues)

**Comment by bbinto** [comment]
Blocked on UX to figure out how to deal with this in regards to sessions
(cc @lime124 )

**Comment by shorlander** [comment]
> It is best to look at the Reference Browser to see the current UI to find out if that is adequate for a first release. There are probably some limitations about what we can do UI-wise I think, so we definitely need to get together to look at current and wanted designs.

When I try and use the Reference Browser for this it just loads the link in the browser. Not a Custom Tab.

@st3fan am I doing something wrong?

**Comment by jonalmeida** [comment]
@shorlander Sorry about that, Custom Tabs hasn't landed in the Reference Browser because of an integration bug that I'm currently looking into (see: https://github.com/mozilla-mobile/reference-browser/issues/487).

**Comment by jonalmeida** [comment]
@shorlander Custom Tabs has landed in R-B so feel free to have a look.

**Comment by st3fan** [comment]
@shorlander a good app to test this with is the official Reddit app. Custom Tabs should open with a blue location bar. Another app where this works well is GMail, which should open up a tab with a red location bar.

I don't think Twitter properly supports this - it seems links from Twitter are opened directly in the R-B by switching apps not by opening a custom tab.

**Comment by sblatz** [comment]
As a part of this, let's make sure we test our menu options work properly in a custom tab. Find in page and request desktop site do not function correctly as is.

**Comment by bbinto** [comment]
I remember @vesta0 mentioning we had some custom tabs issue in Focus, let's make sure we are addressing them / being aware of them for Fenix as well.

**Comment by jonalmeida** [comment]
> As a part of this, let's make sure we test our menu options work properly in a custom tab. Find in page and request desktop site do not function correctly as is.

I've filed an issue for this: https://github.com/mozilla-mobile/android-components/issues/2387

**Comment by vesta0** [comment]
All issues listed under this meta have been implemented.
