### ISSUE TITLE
[Bug]: Inactive tabs survey title overlaps the close button with Russian locale settings

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22200]
### Steps to reproduce

Prerequisites: Clean install or the "Help improve FIrefox" survey available in settings

1. Set the app language to Russian
2. Open the 3-dot menu > Settings > Tabs 
2. Disable the "Move old tabs to inactive" toggle to bring up the survey
3. Notice the title of the survey

### Expected behaviour

The title of the survey and the close button are separate and there are no overlaps in the prompt

### Actual behaviour

The title of the survey overlaps with the close button

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

94.1.0 2021-10-26

### Additional information

![249552597_310779870880414_1569286355937751763_n](https://user-images.githubusercontent.com/89511597/139274395-6dc12b29-ba30-431a-9604-610f0eaa2f7a.jpg)

**Comment by Delphine** [comment]
Russian is part of Tier 1 locales, and wouldn't be surprised this happens in other languages.
@mariansima Could you please let me know about this in German, Czech and Finnish please?

**Comment by mariansima** [comment]
@Delphine No, this only occurs for Russian so far. Checked on a few other different languages as well.

**Comment by Delphine** [comment]
Will ask localizer if he can in any way shorten that string. If not possible, we may need a UX fix.

**Comment by Delphine** [comment]
@unghost: Is it possible in any way to shorten the translation here? I know it's not ideal and perhaps not possible.
Otherwise we may need a UX fix here

**Comment by mariansima** [comment]
I've noticed that the text has changed. Now this happened instead, where the prompt is a little lower and the title beneath is slightly visible. (Might just occur of my device Samsung Galaxy A8, Android 9, RC 95.1.0 2021-12-06)
![263743143_978066179447465_4979953321368588627_n](https://user-images.githubusercontent.com/89511597/144871593-0b8a2794-11b1-4cfe-a01b-8ba7290a3329.jpg)

**Comment by SoftVision-LorandJanos** [comment]
Based on #22495, as the inactive tabs survey is turned off, I will close this ticket.
