### ISSUE TITLE
[Bug]: Inactive tabs survey can be opened multiple times

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22201]
### Steps to reproduce

Prerequisites: Clean install or the "Help improve FIrefox" survey available in settings

1. Open the 3-dot menu > Settings > Tabs 
2. Disable the "Move old tabs to inactive" toggle to bring up the survey
3. Scroll above the survey to reveal the toggle again
4. Tap the toggle and observe

### Expected behaviour

The survey can be opened only once

### Actual behaviour

The survey is opened several times

![249256394_570694254155712_8218073117971406753_n](https://user-images.githubusercontent.com/89511597/139278141-a390f8dd-b4fe-4e31-b860-76b6a5e642dc.jpg)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

94.1.0 2021-10-26

**Comment by SoftVision-LorandJanos** [comment]
Based on #24042, as Inactive tabs survey is no longer activated, I will close this ticket.
