### ISSUE TITLE
[Bug]: The text in the inactive tabs survey is truncated on larger fonts

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22202]
### Steps to reproduce

Prerequisites: Clean install or the "Help improve FIrefox" survey available in settings

1. Change the device font to the higher settings (*)
2. Open the 3-dot menu > Settings > Tabs
3. Disable the "Move old tabs to inactive" toggle to bring up the survey
4. Observe the text for the buttons

*Note that results may vary depending on the font style and size chosen. Screenshot shows Gothic bold on largest size.

### Expected behaviour

The text is fully visible inside the survey prompt

### Actual behaviour

The text is cut off on larger font size settings

![249774349_592248045530232_850559510135712574_n](https://user-images.githubusercontent.com/89511597/139281006-2e953417-1f07-487d-a497-c9ece7f5fbc9.jpg)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

94.1.0 2021-10-26

**Comment by SoftVision-LorandJanos** [comment]
Based on #24042, as Inactive tabs survey is no longer activated, I will close this ticket.
