### ISSUE TITLE
Use Hero images for Recent Bookmarks

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#22211]
This adds a hero image (if it is available) for items in the "Recent bookmarks" section. Fallback to the favicon if no hero image is available for the site.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 96.0a1 (2021-11-26).

Device used: Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.
