### ISSUE TITLE
FNX-5524 ⁃ Lose shortcuts/search results when going to landscape

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2221]
## Steps to reproduce
Search for something or open shortcuts, switch to landscape mode.

### Expected behavior
Results or shortcuts persist

### Actual behavior
Results or shortcuts disappear

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1918

**Comment by vesta0** [comment]
Dup of #1198
