### ISSUE TITLE
Overlaps in saved logins on RTL languages

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22222]
### Steps to reproduce

Prerequisites: Change app settings to RTL language (e.g. Arabic) or from developer system settings (force RTL layout)

1. Add a saved login (or sign in with an account that has one)
2. Open the 3-dot menu > Settings > Logins and passwords > Saved logins
3. Select and edit any of the available login entries
4. Observe the layout of the items in these screens

### Expected behaviour

The items are displayed separately on the screen layout

### Actual behaviour

Icons overlap with the password fields in edit and the redirect button overlaps with the website address

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

94.1.0 2021-10-26

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18508)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 2021-11-01. I have attached a screenshot to better illustrate the issue.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
![logins](https://user-images.githubusercontent.com/50983519/139671944-d2bba558-a84d-48be-a43c-015ba5e96938.JPEG)

**Comment by Delphine** [comment]
@ ItielMaN : Can you confirm this happens also in Hebrew? We should support right-to-left in all languages so hopefully let's get a fix in

**Comment by mariansima** [comment]
This issue also occurs on Samsung Galaxy A8, Android 9, RC 95.1.0 2021-12-06 

@Delphine This issue also occurs on Hebrew. Also, you might have tagged by mistake?

> @ ItielMaN

**Comment by Delphine** [comment]
Seems like I mistyped the tag so it never really tagged :/
@Itielman: seems like this also happens in Hebrew and would need a UX fix

**Comment by ItielMaN** [comment]
I'd expect the solution would be to align the 3 values to the right. That's what is being done on desktop and make the most sense to me.

**Comment by Delphine** [comment]
Tagging at @amedyne for visibility as this is an issue that affects right-to-left locales

**Comment by ItielMaN** [comment]
Still an issue.

**Comment by Delphine** [comment]
@cpeterso There are a few RTL issues that are still happening on Fenix for quite a while now. Do you know is someone can help with right-to-left issues please? I'm not sure how these are prioritized at the time. Thanks!

**Comment by cpeterso** [comment]
Thanks for the heads up. I'll ask the Android Experience team about prioritizing RTL issue https://github.com/mozilla-mobile/fenix/issues/7861.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 111.0a1 (2023-01-27) build.
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

![IMG_5329](https://user-images.githubusercontent.com/48829350/215122221-3a38b522-4dec-4f6d-bc53-85c6788d1eb9.jpg)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813693

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
