### ISSUE TITLE
[Bug]: HTML input required Attribute

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#22229]
### Steps to reproduce

Open https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_required
Select Submit Query without entering any input

### Expected behaviour

Message should appear "Please fill in this field"

(This displays in Firefox on desktop)

### Actual behaviour

No message

### Device name

Motorola Moto E5

### Android version

Android 8

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

### Additional information

User feedback - https://support.mozilla.org/en-US/questions/1355316

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue and can confirm it is reproducible on Firefox Preview Nightly 2021-11-01.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

https://user-images.githubusercontent.com/50983519/139687879-ce4598e1-627c-4345-8ff5-30d4c5b386ad.mp4

**Comment by kbrosnan** [comment]
dupe bz-1510450

**Comment by nu111** [comment]
This bug is closed, I am not sure why, cause the bug is still on Firefox Android Nightly 109.0a1 (Build #2015918955)

**Comment by cadeyrn** [comment]
> This bug is closed, I am not sure why, cause the bug is still on Firefox Android Nightly 109.0a1 (Build #2015918955)

Nope, BZ-1510450 is still open.
