### ISSUE TITLE
FNX-5525 ⁃ Lose "Find in Page" when going to landscape mode

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2222]
## Steps to reproduce
Use Find in Page, go to landscape mode

### Expected behavior
Find in Page is persistent

### Actual behavior
Find in Page disappears

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1918

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/31 build.
