### ISSUE TITLE
Microphone icon from Search Widget blinks and is no longer displayed

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#22221]
### Steps to reproduce

1. Create search widget on home screen
2. Widget blinks microphone icon on right side off and on 
3. Generally happens when closing and opening Firefox app

### Expected behaviour

The widget should stay solid not blinking the microphone icon.

### Actual behaviour

The widget blinks the microphone icon on and off.

### Device name

Galaxy S9+

### Android version

Android 10 (efoundation ROM)

### Firefox release type

Firefox

### Firefox version

94.1.1

### Device logs

N/A

### Additional information
N/A

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18507)

**Comment by SoftVision-LorandJanos** [comment]
Hi @GithubContributor832 ! Thank you for your report!
I couldn't reproduce your issue.
Please post a video of it here. Thank you!
Tested with Xiaomi Mi11 Lite (Android 11).
Firefox version: Release 94.1.1.

**Comment by GithubContributor832** [comment]
https://user-images.githubusercontent.com/92182796/139808289-86206c4b-8cc9-419f-a343-4828f4216db8.mp4

**Comment by amocirean** [comment]
Hi @GithubContributor832 , I was able to reproduce a similar issue.
After installing the widget, the microphone icon can be seen flashing for a split second. After that, the icon will not be displayed at all.
Device Used: Huawei P40 Lite (Android 10)
Firefox Version Release: Latest Nightly from 04/15, RC 99.2.0

https://user-images.githubusercontent.com/103257761/163585485-0b0e9572-3578-4668-a63d-f040ca6df201.mp4

**Comment by delia-pop** [comment]
I was able to reproduce this issue mentioned in the comment above on the latest Nightly 106.0a1 with Lenovo Yoga Tab 11 (Android 11). 

https://user-images.githubusercontent.com/89388888/188114051-c3502b9f-e3e0-44b4-a529-4226e5e9cf70.mp4

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807577

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
