### ISSUE TITLE
[Bug]: Private Tabs Are Shown as Normal Tabs

### ISSUE THREAD

**Issue by nvxarm** [mozilla-mobile/fenix#22223]
### Steps to reproduce

1. View any site in a normal tab.

2. Long-press and open some links in private tab randomly.

3. Close any private tab by the "×" button in the list of private tabs.

4. Private tabs are displayed under the icon of normal tabs.

The bug starts from 00:30 in the screen record as below.

https://user-images.githubusercontent.com/16894061/139393900-d42e3af3-489c-48cd-9716-9d10b5482ccc.mp4

### Expected behaviour

Private tabs are displayed under the icon of private tabs.

### Actual behaviour

Private tabs are displayed under the icon of normal tabs.

### Device name

ASUS ROG Phone 5s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.2.0 (Build #2015839747)

**Comment by marcel263** [comment]
Reproducible in latest nightly, has been there for months

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue and can confirm it is reproducible on Firefox Preview Nightly 2021-11-01. However the tabs opened in private browsing do not appear in the history section

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by Mugurell** [comment]
Jonathan proposed a fixed for this in https://github.com/mozilla-mobile/android-components/pull/11210#discussion_r743317097
Changing the assignee.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 96.0a1 (2021-11-15T05:09:26.668704).

Device used: Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.
