### ISSUE TITLE
[Bug]: Always zooms in on form input field when focused

### ISSUE THREAD

**Issue by makeworld-the-better-one** [mozilla-mobile/fenix#22235]
### Steps to reproduce

1. Go to a website that uses an HTML `form` with an `input` tag
2. Tag the input field

### Expected behaviour

The browser does not zoom by default. Or at least doesn't zoom when zooming is disabled in some way.

Zooming can be disabled with the viewport meta tag, but also with CSS like `touch-action:. manipulation`. But this has no effect on the form zooming Firefox Mobile does.

### Actual behaviour

The browser zooms in to focus on the input field.

There does not seem to be any way to disable this through CSS or meta tags. There are things that work for iOS, but nothing works for Firefox Mobile. Chrome on Android does not have this problem.

### Device name

Samsung Galaxy A50

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

See [this SO question](https://stackoverflow.com/questions/69495070/prevent-zooming-in-on-input-focus) (not by me) for some more detailed examples of things that work for other browsers, but just don't for Firefox Mobile.

**Comment by Mugurell** [comment]
This is a browser issue, moving it to Bugzilla.
Please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1738696

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
