### ISSUE TITLE
[Bug]: Page remains stretched after overscroll on Android 12

### ISSUE THREAD

**Issue by paolodepetrillo** [mozilla-mobile/fenix#22234]
### Steps to reproduce

1. Load a web page
2. Fling to scroll all the way to the bottom
3. Press on the page, scroll upwards until the page content starts to [stretch](https://developer.android.com/training/gestures/scroll#implement-stretch-overscroll), and wait for a second before taking your finger off the screen.

### Expected behaviour

The page content is no longer stretched and returns to its original aspect ratio.

### Actual behaviour

The page content remains stretched vertically.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

https://user-images.githubusercontent.com/3238173/139558115-03bc3899-25fe-4c6f-91cc-adb762ec7715.mp4

**Comment by Mugurell** [comment]
This happens on GVE also, moving to Bugzilla.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1738691

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
