### ISSUE TITLE
FNX-5526 ⁃ [Bug] Find in Page should replace browser toolbar

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2223]
## Steps to reproduce
Go to a site, use Find in Page

### Expected behavior
Find in Page replaces browser toolbar

### Actual behavior
Find in Page renders on top of browser toolbar

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy J7 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)
