### ISSUE TITLE
FNX-5527 ⁃ [Bug] Select bookmark folder present in the overflow menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2224]
## Steps to reproduce
1. Create a bookmark folder.
1. Tap to open its menu.
    1. Expected behavior
"Select" shouldn't be an option since you cannot select the folder with long-tap anymore.
    1. Actual behavior
Can select a folder from the overflow menu. The options available don't work, except edit and delete.
    1. Device information

* Android device: any
* Fenix version: 5/2

**Comment by vesta0** [comment]
When a folder is selected, the options in the 3 dot menu at the top right behave as follows:
-Open in new tab doesn't work regardless of how many bookmarks are in that folder
-Open in new private tab freezes Fenix
-Edit and Delete work as noted above in the bug description

Let's remove the Select option for folders.

**Comment by sblatz** [comment]
I think some of these issues are related to the state restoration we've been working on. I'm going to investigate.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/16 build.
