### ISSUE TITLE
ActivityTestRule is deprecated (for UI tests)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22248]
According to [the docs](https://developer.android.com/reference/androidx/test/rule/ActivityTestRule?hl=en), it should be replaced with [`ActivityScenario`](https://developer.android.com/reference/androidx/test/core/app/ActivityScenario?hl=en) or [`ActivityScenarioRule`](https://developer.android.com/reference/androidx/test/ext/junit/rules/ActivityScenarioRule?hl=en):

> This class is deprecated.
use ActivityScenario or ActivityScenarioRule instead. They offer a simpler, and safer way of controlling Activity lifecycles. 

I wonder **if switching will help reduce the number of intermittent failures we experience.**

This API apparently can also be used in robolectric tests: maybe it'd produce fewer failures there too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18522)

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/mobile-test-eng/issues/602

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807306

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
