### ISSUE TITLE
[Bug]: its not possible to use fenix-94.1.1-arm(...)apk with hardware keyboard only - no ctrl+L shortcut [TV sticks problem]

### ISSUE THREAD

**Issue by cmdroot** [mozilla-mobile/fenix#22242]
### Steps to reproduce

1. Firefox started 2. ctrl+L doesn't work 3. Tried everything to access address bar - without success

### Expected behaviour

ctrl+L (option: Move cursor to address box) should work without mouse or touchpad also on TV stick devices (no touchpad)

### Actual behaviour

its not possible to use fenix-94.1.1-arm(...)apk with hardware keyboard only - no ctrl+L shortcut (option: Move cursor to address box)

### Device name

All TV sticks without touchpad like: MII TV Stick

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

94.1.1

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/3729
