### ISSUE TITLE
 Sync issues between laptop and Android browsers

### ISSUE THREAD

**Issue by nakic** [mozilla-mobile/fenix#22249]
I have 2 Ubuntu laptops with Firefox (93.0 on the laptop I'm writing this) and an Android phone running Fennec (91.1.0).

I use sync to sync history and bookmarks and I search all of it from the address bar. I've noticed that sync works as expected between the 2 laptops, but does not work between Fennec and the laptops. I've tried accessing a never before visited URL on laptop A and I can soon see it on laptop B in history (as expected), but Fennec does not show it in its history. I then visited a never before visited URL from Fennec, synced Fennec, synced Firefox on a laptop, but did not see the URL in the history on the laptop.

I would expect the history on the laptop to include pages visited from Fennec and vice versa: they seem completely detached.

I've tried unsyncing and resyncing Fennec, but it had no effect.

Finally, I've reported one other sync-related [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1634962) 2 years ago: it looks unrelated to me, but I'm not 100% sure so I mention it anyway.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18523)

**Comment by simpz** [comment]
I see the same thing. I believe my sync is in place as the one thing that is working correctly is I can see open "Synced Tabs" display correctly on Fennec and Linux Firefox for each other, so communication must be happening. 

But Bookmarks and History is as you say completely broken. I have 94.1.1 Fenix. 

Not sure why more people aren't seeing this as broken and a big issue.

**Comment by simpz** [comment]
I did get mine to work again. But I had to sign out of my account on the Android browser, I removed it from connected services and reconnected (this still wasn't enough), so I also had to clear the storage for Fenix and go back to a clean Android firefox and reconnect to my account.  That worked.

A pain, and working okay now, we'll see how long for.
