### ISSUE TITLE
Intermittent UI test failure - < SmokeTest.editCustomSearchEngineTest >

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#22256]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9223008020099075063/executions/bs.38fc48eea92dfdb7/testcases/1/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.SettingsSubMenuSearchRobot.saveEditSearchEngine(SettingsSubMenuSearchRobot.kt:140)
at org.mozilla.fenix.ui.SmokeTest$editCustomSearchEngineTest$4.invoke(SmokeTest.kt:571)
at org.mozilla.fenix.ui.SmokeTest$editCustomSearchEngineTest$4.invoke(SmokeTest.kt:563)
at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openSearchSubMenu(SettingsRobot.kt:136)
at org.mozilla.fenix.ui.SmokeTest.editCustomSearchEngineTest(SmokeTest.kt:563)`
### Build: 
Debug 11/2

Started with https://github.com/mozilla-mobile/fenix/pull/22244

**Blocked** by https://github.com/mozilla-mobile/fenix/issues/23536

**Comment by csadilek** [comment]
Happened again in: https://github.com/mozilla-mobile/fenix/pull/22296

**Comment by sv-ohorvath** [comment]
The problem is with the snackbar - even if it's visible the test doesn't recognize it. Same thing happens in https://github.com/mozilla-mobile/fenix/issues/17484#issuecomment-948539468 or in the context menu tests.

**Comment by sv-ohorvath** [comment]
Started failing 2/2 tries on 11/4:
[logs](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9215873714164574013/executions/bs.e2d03157593b7b2e/test-cases)
[logs](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6249743883900558438/executions/bs.86f5161bc9e66f50/test-cases)

**Comment by AndiAJ** [comment]
Re-enabled in #22339

Based on the [logs](https://github.com/mozilla-mobile/fenix/issues/22256#issuecomment-960954454) the failures were caused due to a URL request related issue which happened at a certain time.
`I//system/bin/netd(1912): gethostby*.getanswer: asked for "www.elefant.ro IN A", got type "RRSIG"`

We decided to re-enable the test as it is and if the problem is recurring try a different solution.

**Comment by sv-ohorvath** [comment]
Let's leave it open for the initial issue here: the snackbar verification.

**Comment by csadilek** [comment]
>  Re-enabled in #22339

Hi @AndiAJ, I wasn't able to reproduce the failure locally (on different devices) and since it was blocking the A-C Nightly upgrade I set it to ignored again for now. Could you take another look at this test to double-check? Thanks!

**Comment by AndiAJ** [comment]
Hi @csadilek ,thanks for disabling it, sure, we'll take a look.

**Comment by sv-ohorvath** [comment]
I found this issue: https://github.com/mozilla-mobile/fenix/issues/23536 which explains the intermittent failures of this test. Setting this as waiting for a bug fix, won't re-enable until then.
