### ISSUE TITLE
FNX-5528 ⁃ [Bug] Accidently trigger bookmark when using Find in Page arrows

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2225]
## Steps to reproduce
Search for something on a page using Find in Page and navigate through the results using the arrows

### Expected behavior
Navigate through results

### Actual behavior
Accidentally triggered add a bookmark

**Comment by bsurd** [comment]
Checked on a Pixel (A9) and Galaxy S8 (A9) with the latest Fenix (5/6), this issue was no longer reproducible on those devices. Closing.
