### ISSUE TITLE
Tapping a normal tab after the selected private tab is closed brings the user to home

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22261]
STRs:
- have a few normal tabs and a few private tabs open
- close the selected private tab
- open tabs tray and tap on any tabs

Expected result:
- the just tapped normal tab is opened

Expected result:
- the intended tab is opened but the user is immediately navigated to the homescreen

https://user-images.githubusercontent.com/11428869/139906051-e51f536c-74c7-4bb5-ba7f-72f16e66eae2.mov

**Comment by marcel263** [comment]
reproducible. switches to the homepage with focus on the tab card of the tabt hat was just supposed to be opened .
