### ISSUE TITLE
[Bug]: Desktop mode scaling too large on Android tablets, but window.devicePixelRatio remains the same

### ISSUE THREAD

**Issue by chenxiaolong** [mozilla-mobile/fenix#22263]
### Steps to reproduce

1. Open https://support.mozilla.org/en-US/kb/whats-new-firefox-android on an Android tablet
2. Note that the scaling matches other browsers, like Chrome
3. Toggle desktop mode

### Expected behaviour

The page should render with the correct scaling factor.

### Actual behaviour

The scaling is significantly larger than in mobile mode. (Screenshots below)

### Device name

Samsung Galaxy Tab S7+

### Android version

Android 11 (build T970XXU2BUJ3)

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 (Build #2015843307)

### Additional information

Screenshots:

* Mobile mode (top: Firefox, bottom: Chrome): [Screenshot](https://user-images.githubusercontent.com/646253/139915953-588971e4-313d-449d-911d-03441ed444f3.png)
* Desktop mode (top: Firefox, bottom: Chrome): [Screenshot](https://user-images.githubusercontent.com/646253/139915997-6772e4a2-51b9-4f3a-81f2-c17149fd30c2.png)

I tried to do some troubleshooting and it seems that the `window.devicePixelRatio`, `window.innerHeight`, and `window.innerWidth` remain the same between mobile and desktop mode. However, a `px` in desktop mode is significantly larger than a `px` in mobile mode.

Example:
* Mobile mode (top: Firefox, bottom: Chrome): [Screenshot](https://user-images.githubusercontent.com/646253/139916235-c2358da9-5a8a-4438-899f-751a65c0228d.png)
* Desktop mode (top: Firefox, bottom: Chrome): [Screenshot](https://user-images.githubusercontent.com/646253/139916271-342d7b9a-9c13-44c3-bde4-04407dbca96a.png)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1738992

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
