### ISSUE TITLE
Tab reordering: Go out of selection mode on long press and dragging

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#22264]
Follow up for https://github.com/mozilla-mobile/fenix/pull/21157

When you long press on a card, Firefox switches to selection mode on the tab tray. Once you start dragging the card around, Firefox exits selection mode (header switches back to the default one, check mark on card disappears) and you can move the card around.

**Comment by pocmo** [comment]
"Google Keep" is a great example of an app that allows selecting, but also moving cards - using the mechanism described above.

**Comment by topotropic** [comment]
This works in Nightly when search groups are disabled
