### ISSUE TITLE
FNX-5530 ⁃ [Bug] Select a bookmark then cancel and select a different item, selects both

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2227]
## Steps to reproduce
1. Go to bookmarks, long tap to select an item.
1. Tap the system back button to cancel the selection.
1. Long tap to select a different bookmark.
1. Cancel and select the same items again.
    1. Expected behavior
If a selection is canceled, the items are not selected anymore. Can re-select an item after it was once dropped.
    1. Actual behavior
On step 3, the first bookmark is selected along with the second.
On step 4, can't long tap to select the same item that was selected before.
    1. Device information

* Android device: Pixel (android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 5/2 build

**Comment by vesta0** [comment]
I can't reproduce this. Please test again :)

**Comment by sv-ohorvath** [comment]
Still reproducing on the 5/14 build:
![20190514_104337](https://user-images.githubusercontent.com/4037709/57679954-340b2280-7635-11e9-8f4b-9e848afa1ac5.gif)

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/3 build.
