### ISSUE TITLE
[Bug]: The "Show Search Engines" setting seems to prevent the "Show clipboard suggestions" UI from appearing

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#22272]
### Steps to reproduce

1. Go to Settings | Search, and scroll down to the bottom.
2. Enable `Show search engines` (first entry) and `Show clipboard suggestions` (third entry)
3. Copy a URL to your clipboard (in an external app or in Firefox)
4. Open a new tab (which pops up the address/searchbar-editing UI)

### Expected behaviour

There should be a "Fill link from clipboard" pane (showing the copied URL) just above my editable address bar (because I have "Show clipboard suggestions" enabled).

### Actual behaviour

There is no "Fill link from clipboard" pane.

### Device name

Google Pixel 4a

### Android version

Andoird 12

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1

### Additional information

If I disable `Show search engines`, then I get the "Expected Behavior" (i.e. then the "Fill link from clipboard" pane shows up as I expect it to).

So it seems like `Show search engines` is specifically turning off the clipboard suggestions for some reason.  Probably these two features just weren't tested together, and we need some tweaks to make them play nicely?

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-18538)

**Comment by e-t-l** [comment]
@dholbert , some troubleshooting for you:

1. When you open a new tab and tap the address bar to make a search, do you see a button right above your address bar with a magnifying glass that says "Search Engine"? 
2. When you have the settings "Show search engines" enabled, does this button appear highlighted?
3. If you tap this button, does it make the list of search engines disappear AND then show "Fill from clipboard" prompt?

(I'll try to screen record a video to show what I mean, because theses options are working as expected for me)

...
Firefox (Play store) v94.1.2 (Build #2015844587)
Google Pixel 3, Android 12 (non-root)

**Comment by e-t-l** [comment]
@dholbert please confirm if you can perform the steps above, as described in the video in this comment.
https://user-images.githubusercontent.com/40775958/141482628-375adf42-db29-4710-ae7b-2100911e6993.mp4

**EDIT:** I just noticed you said this is an issue for Nightly. I installed Nightly (v96.0.1) and can confirm that it still works exactly as shown in my video, so either this bug has been fixed, it's specific to your device, or it's not reproducible.

**Comment by dholbert** [comment]
The behavior that I'm seeing does exactly match your video. And my answer is "yes" to all three questions.

Given that, this bug-report seems to be a usability issue with the "search engine" button -- it seems that Firefox is intentionally hiding the "Fill link from clipboard" entry when that button is activated.   This might even be an intentional design choice?  This makes some sense for the flow **when the user actively taps that button**, because that action is an active signal that the user is about to perform a search (and hence probably doesn't want to paste a URL).

But for the case where the user has "Show Search Engines" always-enabled (as in this bug's STR), we don't have any such "the user is probably searching" signal; so it doesn't make as much sense to hide this paste-URL button.  It means we never offer "paste URL" to such users, which is unfortunate. (unless they manually tap-to-disable the "search engine" button, but it's not super-obvious to users that they might want to try that).

**Comment by e-t-l** [comment]
Okay, so this doesn't seem so much like a bug as a feature/enhancement request for these two options (clipboard and search engines) to be shown in the same view rather than in separate views.

The reason it's currently designed how it is, to my understanding at least, is that the list of search engines is basically obscuring the clipboard prompt, and were they stacked the other way around, the clipboard prompt would obscure one or two search engines in the list. 

Yes this could be programmed differently, perhaps adding some padding to the search engine list to make room for the clipboard prompt to be integrated into it, but for the time being they're just considered two separate views that the user is free to switch between. (I'm actually planning to open a new issue proposing an alternative search engine view anyway, and if people like that, it would solve your problem as well. Stay tuned!)

**Comment by dholbert** [comment]
> Okay, so this doesn't seem so much like a bug as a feature/enhancement request for these two options (clipboard and search engines) to be shown in the same view rather than in separate views.

Sort of.  It's a usability papercut, really, since this helpful paste-url button just never shows up for a certain class of user (users who have "show search engines" selected).
 
> The reason it's currently designed how it is, to my understanding at least, is that the list of search engines is basically obscuring the clipboard prompt, and were they stacked the other way around, the clipboard prompt would obscure one or two search engines in the list

That reasoning for this behavior doesn't make a whole lot of sense to me.  Counterpoints:
- Depending on screen dimensions and the user's configured number of search engines, everything might fit just fine, with no overlap. (e.g. I only have 3 search engines enabled, and there's plenty of space below them to show the clipboard prompt)
- Similarly: if the user has a small screen and/or lots of search engines, then there will be overlap *regardless* (between the search engine list and the keyboard/address bar).  Hiding this clipboard prompt reduces the overlap in that scenario, but it doesn't prevent overlap.
- RE "which way would things even stack": the clipboard prompt is visually "attached" to the address-bar.  When it's displayed, it looks like it's attached to the `Scan | Search Engine` widget, which is attached to the address bar, which is attached to the keyboard. (And there's a horizontal separator line at the top of all of this, indicating that this is one cohesive widget).  So it would be part of that same layer, stacking-order wise.
 
> Yes this could be programmed differently, perhaps adding some padding to the search engine list to make room for the clipboard prompt to be integrated into 

Padding shouldn't be necessary. They can overlap, and that's ~fine (except maybe for extremely-small screens), and the desirable stacking order is well-defined, since this widget is attached to the address bar.

> (I'm actually planning to open a new issue proposing an alternative search engine view anyway, and if people like that, it would solve your problem as well. Stay tuned!)

That's good news - thanks for the heads up!

**Comment by dholbert** [comment]
The other thing that makes this a pretty-bad papercut (which I don't think I've mentioned here) is: when you perform this bug's STR in Android 12 (on Firefox or Firefox Beta or Nightly from ~1 week ago), **Android shows a notification saying "Firefox pasted from your clipboard"**.   And there's zero visual indication of where/why Firefox pasted that value, or what it found in my clipboard, or what it's done with whatever it found.

This is apparently because we're instantiating this paste-from-clipboard widget under the hood, which is ~innocuous; but that's not at all obvious to a user, so it just ends up feeling super sketchy.

Fortunately that's been addressed in #22271 -- but this bug here (i.e. actually showing the "paste from clipboard button") is another way of addressing it (on top of being a usability win in its own right, from my perspective).
