### ISSUE TITLE
Try to use getPrimaryClipDescription on Android 12 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#22271]
On Android 12 there is a new behavior change when accessing the clipboard, the OS shows a toast indicating that the app is is accessing it, more details can be found [here](https://developer.android.com/about/versions/12/behavior-changes-all#clipboard-access-notifications).

When users try to search or open an URL in the toolbar Fenix tries to check on the clipboard to see if there is an URL on the clipboard that the user wants to navigates to, we use these [extension functions](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt#L28-L29) to try to figure out, but they are triggering [the Clipboard access notifications on Android 12](https://developer.android.com/about/versions/12/behavior-changes-all#clipboard-access-notifications), to avoid that we want to use  [getPrimaryClipDescription()](https://developer.android.com/reference/android/content/ClipboardManager#getPrimaryClipDescription())   

### Steps to show the reproduce [the Clipboard access notifications on Android 12](https://developer.android.com/about/versions/12/behavior-changes-all#clipboard-access-notifications):

1.  Copy a URL to clipboard in some other app (e.g. https://example.org )  
2.  Start Firefox Nightly

**Comment by dholbert** [comment]
One particularly-important use case to consider here:  under some configurations[1] we never show the "Fill link from clipboard" UI, but nonetheless we seem to check the clipboard as if we were going to show the UI.  This ends up meaning that the user sees a "Firefox Nightly pasted from your clipboard" system notification **when there's no clear user-visible indication about why/where Firefox pasted the clipboard contents (or what Firefox found there)**.  This ends up feeling unsettling/concerning from a user perspective.

[1] In particular: on my phone, the "Settings | Search | Show search engines: [enabled]" setting causes the "fill link from clipboard" UI to never appear. (but Firefox still queries my clipboard for apparently no reason)

**Comment by nathan-castlehow** [comment]
Hi,
I'm happy to give this a stab if that will help at all. New to this project so forgive me If I've missed any steps here

I had an initial look into this.
The extension functions listed are already using getPrimaryDescription before then reading the clipboard.

` private fun ClipboardManager.isPrimaryClipPlainText() =
        primaryClipDescription?.hasMimeType(MIME_TYPE_TEXT_PLAIN) ?: false`

   ` private fun ClipboardManager.isPrimaryClipHtmlText() =
        primaryClipDescription?.hasMimeType(MIME_TYPE_TEXT_HTML) ?: false`

Api 31 has introduced [getConfidenceScore ](https://developer.android.com/reference/android/content/ClipDescription#getConfidenceScore(java.lang.String) )on the clipboard description class which we can use to check if an item is a URL or not.

We could use this before deciding to then read the clipboard
Something similar (just threw this together, needs api checks etc) to
`    private fun ClipboardManager.isPrimaryClipURI() =
            0.5f < (primaryClipDescription?.getConfidenceScore(TextClassifier.TYPE_URL) ?: 0f)
`

 If the confidence score is unavailable (it may not be calculated at the time this runs) what behaviour do we fall back to? (I presume the existing behaviour?
Ultimately though when we do eventually decide to read the clipboard it looks like the notification toast will always appear.

I've noticed on Android12 that the default keyboard already has the option to paste the url into the search bar (see image below). I wonder if there is a separate conversation about deprecating the feature for 12 and up as the clipboard read toast is pretty scary.

![image](https://user-images.githubusercontent.com/8556134/140633072-eb8f8361-7deb-4f0c-aa9f-6cf5ca54e3cd.png)

**Comment by Amejia481** [comment]
Thanks @dholbert, I'll take a look to confirm this https://github.com/mozilla-mobile/fenix/issues/22271#issuecomment-962552957.

**Comment by Amejia481** [comment]
> I've noticed on Android12 that the default keyboard already has the option to paste the url into the search bar (see image below). I wonder if there is a separate conversation about deprecating the feature for 12 and up as the clipboard read toast is pretty scary.

@nathan-castlehow thanks for bring this out, yeah I noticed Chrome resigned the functionality to only copy from the clipboard upon user's request. I think it will be better for me to clarify with the UI/UX team, before doing the changes I'm not sure how we should proceed. Let's not do any changes until confirming, thanks for interesting on this bug.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/773158/140792087-235cf28e-1f90-4741-a321-8721457ad2fe.png">

**Comment by Amejia481** [comment]
> One particularly-important use case to consider here, from a user-confusion/suspicion perspective: under some configurations[1], Firefox apparently _never_ shows the "Fill link from clipboard" UI, but nonetheless we seem to check the clipboard _as if we were going to show that UI_. This ends up meaning that the user still sees a "Firefox Nightly pasted from your clipboard" system notification **when there's no clear user-visible indication about why/where Firefox pasted the clipboard contents (or what Firefox found there)**. This ends up feeling unsettling/concerning from a user perspective.
> 
> As part of fixing this bug, perhaps we should bypass the clipboard access entirely for this configuration (assuming that we're hiding the UI intentionally).
> 
> [1] In particular: on my phone, "Settings | Search | Show clipboard suggestions: [disabled]" setting causes the "fill link from clipboard" UI to never appear. (but Firefox still queries my clipboard for apparently no reason). (The "Show search engines: [enabled]" setting is another way to hide the fill-link-from-clipboard UI, but I think that's a bug; I filed #22272 on that.)

It looks like we are still accessing the API even the setting is off, we are only not showing the result, for this reason the notification is still showing.

**Comment by Amejia481** [comment]
@nathan-castlehow as this became a pressing issue I had to address it myself sorry for that, hope you could understand. 
I put a [PR](https://github.com/mozilla-mobile/fenix/pull/22391) where you can see the approach that we took. Please take a look your input it's really helpful and really appreciate ❤️.

**Comment by Amejia481** [comment]
This landed on [main](https://github.com/mozilla-mobile/fenix/commit/94a543a4032feac18a90e3d1449587631a9595fe), the fix should be available in the next nightly.

QA team please help use to verify that issue is fixed.

**Comment by Amejia481** [comment]
@dholbert are you able to reproduce in the latest nightly?

**Comment by sflorean** [comment]
I wasn't able to reproduce the issue on latest Nightly (11/17) with Pixel 3 (Android 12).

**Comment by dholbert** [comment]
>  @dholbert are you able to reproduce in the latest nightly?

No, I can't. This does indeed seem to be fixed. Thanks!

**Comment by Amejia481** [comment]
@Mergifyio backport releases_v95.0.0

**Comment by dholbert** [comment]
FWIW, I've just filed a bug for a different set of STR that trigger this same "Firefox Nightly pasted from your clipboard" system-notification, in a way that annoyingly **prevents me from pasting** for a few seconds (because the notification covers up our "Paste" menu item).

See details over in #26564.
