### ISSUE TITLE
Automate telemetry renewals

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#22274]
We are currently gathering all of the telemetry probes that need to be renewed each month manually. We should automate this so that it is easier for the team.

[Telemetry renewals doc](https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit#)

[Brainstorming doc](https://docs.google.com/document/d/1wNnOe4XqUPx4RxJD59mJYrGyDeomF1fraoa7mt1ARGI/edit)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18539)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809324

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
