### ISSUE TITLE
FNX-5531 ⁃ [Bug] If you bookmark a page on youtube, all pages on this site will appear as bookmarked

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2228]
## Steps to reproduce
1. Go to youtube.com. Bookmark the page.
1. Select a video from the homepage. Observe the quick action toolbar.
    1. Expected behavior
The 2nd page shouldn't appear as bookmarked.
    1. Actual behavior
The bookmark icon indicates the page as bookmarked. If you tap the icon it will bookmark the page.
    1. Device information

* Android device: Pixel
* Fenix version: 5/2

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/28 build.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11490609), with Google Pixel (Android 9), Nexus 6P (Android 8.1.0), Huawei MediaPad M2 (Android 5.0.1).
