### ISSUE TITLE
[Bug]: The Learn more link in Studies is broken

### ISSUE THREAD

**Issue by matt-boris** [mozilla-mobile/fenix#22281]
### Steps to reproduce

1. Go to `Settings`
2. Go to `Data collection`
3. Go to `Studies`
4. Press `Learn more`
5. See broken link it takes you to

### Expected behaviour

It should link to [here](https://support.mozilla.org/en-US/kb/how-opt-out-studies-firefox-android). The link should be independent of the installed version of Firefox.

### Actual behaviour

Firefox Nightly takes me to [here](https://support.mozilla.org/1/mobile/95.0a1/Android/en-US/how-opt-out-studies-firefox-android) and Firefox Stable takes me to [here](https://support.mozilla.org/1/mobile/93.2.0/Android/en-US/how-opt-out-studies-firefox-android).

### Device name

Samsung Galaxy S21 Ultra

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 (Build #2015843499)

### Additional information

Just wanted to reiterate that this is occurring even in the Stable release.

**Comment by Amejia481** [comment]
QA team please help us to verify that the issue is fixed, thanks in advance!

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 96.0a1 (2021-11-05T05:12:49.870142).

Device used: Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.
