### ISSUE TITLE
`beforeinstallprompt` not fired if manifest link is added after DOM load

### ISSUE THREAD

**Issue by vanillajonathan** [mozilla-mobile/fenix#22286]
### Steps to reproduce

I have a multi-tenant single-page application (SPA), so each tenant have their own manifest file, and it cannot be part of the `index.html` file, so it gets added dynamically at runtime by adding a `link` element to the DOM.

Each tenant gets a path with their tenant name in route, so the route looks like this `example.com/{tenant-name-here}/`, example `example.com/tenant-one/`.

So the `index.html` have no link element to any manifest file, but it gets added and appended to the DOM at runtime. Example:
```html
<link rel="manifest" href="/tenant-one/manifest.json">
```

### Expected behaviour

Firefox should have fired the `beforeinstallprompt` event and shown a "Install" option in the menu. Just like Chrome.

### Actual behaviour

Nothing happened. Firefox did not fire any `beforeinstallprompt`, nor present any "Install" option in the menu.

### Device name

OnePlus 6T (real), Samsung Galaxy 21 Ultra (BrowserStack)

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.2.0

### Additional information

This occurred on a [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor) application with OpenID Connect (OIDC) authentication, using the authorization code flow (`code`) with PKCE.

`example.com/tenant-one/` redirects to `example.com/authentication/login` which redirects to an Identity Provider (IdP) which upon authentication redirects to `example.com/authentication/login-callback` which in turn redirects to `example.com/tenant-one/`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18547)

**Comment by aricooperdavis** [comment]
As far as I'm aware `beforeinstallprompt` isn't supported at all on Firefox for Android, regardless of when the manifest link is added (see [https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeinstallprompt_event#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeinstallprompt_event#browser_compatibility)). As such this may be a feature request rather than a bug?

**Comment by vanillajonathan** [comment]
No, that would be another issue then, because regardless of the `beforeinstallprompt` being fired or not, when having the manifest linked from the `.html` file Firefox would let the user install the site, but when the manifest was appended to the DOM at runtime then it would not trigger the behavior which lets the user install the site.

**Comment by aricooperdavis** [comment]
Ah I see, my mistake!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811609

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
