### ISSUE TITLE
MR2 telemetry: Inactive tabs CFR telemetry

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#22298]
https://mozilla-hub.atlassian.net/browse/FNXV2-18424

Implement telemetry for the purple CFR on inactive tabs by adding probes to answer the following:
- Event: Click on purple CFR "go to settings" link
- Event: Click to dismiss the CFR
- Event: The CFR is displayed to the user

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Nightly 96.0a1 from 11/11 using a Google Pixel 3a (Android 11)

✔️  Inactive tabs CFR is visible - Event Ping ab58e1a0-e4ae-4a0d-a4ad-bf8cb4744cf2
```
{
          "timestamp": 1796,
          "category": "tabs_tray",
          "name": "inactive_tabs_cfr_visible"
        }
```

✔️  Dismissed the inactive tabs CFR - Event Ping ab58e1a0-e4ae-4a0d-a4ad-bf8cb4744cf2
```
        {
          "timestamp": 4597,
          "category": "tabs_tray",
          "name": "inactive_tabs_cfr_dismissed"
        }
```

✔️  Opened settings via the inactive tabs CFR - Event Ping b9c8c127-8a2b-493f-84a7-f8e79dafc595
```
{
          "timestamp": 3801,
          "category": "tabs_tray",
          "name": "inactive_tabs_cfr_settings"
        },
        {
          "timestamp": 3825,
          "category": "tabs",
          "name": "setting_opened"
        }
```

[Logcat](https://github.com/mozilla-mobile/fenix/files/7520400/count.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ1111005)
