### ISSUE TITLE
Clear button for input type=search

### ISSUE THREAD

**Issue by vanillajonathan** [mozilla-mobile/fenix#22291]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

![image](https://user-images.githubusercontent.com/10222521/140134255-fcfe105e-17fa-4c3b-9e8c-f94a5acb02be.png)

### What is the user problem or growth opportunity you want to see solved?
Easier to search, faster to search, more familiar to users, and work as expected by users.

### How do you know that this problem exists today? Why is this important?
Other browsers support clearing the input.

### Who will benefit from it?
Users who search.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1739174

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
