### ISSUE TITLE
MR2 telemetry: Opening search term groups in history

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#22299]
For https://mozilla-hub.atlassian.net/browse/FNXV2-18429

Implement the following probes: 

    Metric - Counter: Counts the number of times a user opens a search term group from history

**Comment by AndiAJ** [comment]
Hi @rocketsroger , I've just checked this matter on both the latest Nightly build and Firefox 96.0.0 Beta 1 using a Google Pixel 3a (Android 11)

On both builds the `search_term_group_tapped` counter doesn't get generated in the metrics ping

Another worth mentioning matter is that the `preferences.search_term_groups_enabled` remains set to false on Firefox 96.0.0 Beta 1 even if it's actually enabled.

Nightly - Metrics ping cf10d9d6-1fca-4e6d-b324-bff74461aff6
[Logcat](https://github.com/mozilla-mobile/fenix/files/7676681/nightly.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-0812001)

Beta - Metrics ping a87502a1-5da8-401b-94aa-a6636ddd1c0a
[Logcat](https://github.com/mozilla-mobile/fenix/files/7676705/beta.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-0812000)

Please review and share your thoughts ☺️ 
Thanks!

**Comment by rocketsroger** [comment]
> Hi @rocketsroger , I've just checked this matter on both the latest Nightly build and Firefox 96.0.0 Beta 1 using a Google Pixel 3a (Android 11)
> 
> On both builds the `search_term_group_tapped` counter doesn't get generated in the metrics ping
> 
> Another worth mentioning matter is that the `preferences.search_term_groups_enabled` remains set to false on Firefox 96.0.0 Beta 1 even if it's actually enabled.
> 
> Nightly - Metrics ping cf10d9d6-1fca-4e6d-b324-bff74461aff6 [Logcat](https://github.com/mozilla-mobile/fenix/files/7676681/nightly.txt) [Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-0812001)
> 
> Beta - Metrics ping a87502a1-5da8-401b-94aa-a6636ddd1c0a [Logcat](https://github.com/mozilla-mobile/fenix/files/7676705/beta.txt) [Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/AJ-0812000)
> 
> Please review and share your thoughts ☺️ Thanks!

@AndiAJ to clarify, search term groups should only be available to Nightly/Debug.  You should not see that functionality on Beta.  Are you seeing search term group functionality on Beta?

**Comment by rocketsroger** [comment]
@AndiAJ my mistake.  I've mistaken this as tabstray search term group.  Yes this feature is in Beta.  You're not seeing history.search_term_group_tapped event recorded?  I double check the implementation and confirmed that it is being sent.  Can you please double check if you see other history events showing up with your test setup?
