### ISSUE TITLE
FNX-5532 ⁃ [Meta] PWA support [1]

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#223]
This Epic is about the first phase of implementing PWA support for Fenix. This refers to the “classic” shortcut-based approach, similar to the one that has been implemented in Fennec.

### Dependencies
* PWA Support in Android Components - [Project Board](https://github.com/orgs/mozilla-mobile/projects/13)

**Comment by bbinto** [comment]
Need to chat with UX (@lime124) if we need any specific UX for this or can we use what A/C has done, @st3fan should have a bit more information

**Comment by st3fan** [comment]
We have the following user stories in the Reference Browser about PWA:

https://github.com/mozilla-mobile/reference-browser/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+pwa

**Comment by bbinto** [comment]
Here is the reference from product (AirTable) (PWA stories): https://airtable.com/tblf2pIqYnRNTtPAa/viw3YIfFxAcOgB2S7

**Comment by vesta0** [comment]
Will be tracked [here](https://github.com/orgs/mozilla-mobile/projects/13) and also tracked by `PWA` label.
