### ISSUE TITLE
FNX-5533 ⁃ [Bug] Theme selection is reset - only some devices

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2230]
## Steps to reproduce
1. Go to Settings>Theme
1. Select a theme. Exit from the sub-menu
1. Return to the Theme sub-menu. check the selection.
    1. Expected behavior
The selected radio button is displayed.
    1. Actual behavior
No selection displayed.
    1. Device information

* Android device: HTC Desire 820 (Android 6.0.1), Nexus 5 (Android 6.0.1). Same as #1414
* Fenix version: 5/2

**Comment by sv-ohorvath** [comment]
@ekager Has this landed? Verified on a debug build & I can still reproduce this. 
![20190503_152246](https://user-images.githubusercontent.com/4037709/57137105-86d41700-6db7-11e9-8a3d-e6490df44dd7.gif)

**Comment by ekager** [comment]
My changes landed in Nightly yesterday. Ah gotcha it's the visual of it sticking. Let me look into it on an older device

**Comment by softvision-miralobontiu** [comment]
The issue still reproduces, exactly like in this [comment](https://github.com/mozilla-mobile/fenix/issues/2230#issuecomment-489077585).
Tested on the latest build 1.0.1921 (#build11440149), with Nexus 5 (Android 6.0.1).

**Comment by ekager** [comment]
Okay sorry for the delay! I think I have finally fixed this, thanks for the tip about  #1414

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11510609), with Motorola Moto G6 (Android 7.0), Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Tab A6 (Android 5.1.1).
