### ISSUE TITLE
[Bug]: Collapsing/expanding inactive tabs list doesn't work after switching the orientation of the device 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#22309]
### Prerequsites
 Have "Inactive tabs" list populated.

### Steps to reproduce
1. Go to Tabs Tray and open the "Inactive tabs" list.
2. Switch the device to landscape mode.
3. Tap the arrow, next to "Inactive tabs".

### Expected behaviour

Inactive tabs list is not displayed.

### Actual behaviour

The list is still displayed.

### Device name

Huawei MediaPad M2, Samsung

### Android version

5.1.1, 9.0

### Firefox release type

Firefox Beta

### Firefox version

95.0.0-beta.1

**Comment by SoftVision-LorandJanos** [comment]
I managed to reproduce this with both expanded list not collapsed at first and the collapsed list expanding only after 3 taps on the chevron. See videos below:

https://user-images.githubusercontent.com/48829350/140294268-03505f8a-e5bd-4616-a7f1-f3781a5e3775.mp4

https://user-images.githubusercontent.com/48829350/140294302-2733721b-3788-4819-aac3-02aa1813da8c.mp4

**Comment by Alexandru2909** [comment]
I could not reproduce this bug on both Beta and Nightly versions on Samsung J7 (Android 7) and Samsung Note 10 (Android 11). Can someone from QA confirm this is still an issue? Thank you!

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible.
Verified on the latest Nightly (2022-01-10).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.
