### ISSUE TITLE
[Bug]: Improperly displayed tabs tray more options menu after rotation

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#22308]
### Steps to reproduce

1. Open a tab
2. Open the tabs tray
3. Tap the ⋮ more options button
4. Rotate the device to landscape view
5. Rotate the device back to portrait mode

### Expected behaviour
Properly displayed menu

### Actual behaviour
Improperly displayed menu

### Device name
OnePlus A3 Android 6.0.1

### Firefox version
Firefox 95.0.0 Beta 1
Firefox Nightly 96 from 11/04

### Additional information

► Video

https://user-images.githubusercontent.com/51314259/140285360-a69db93d-769c-4553-bcc6-8245b2c2683e.mp4

**Comment by fevziomurtekin** [comment]
Can I work for this issue?

**Comment by pedroldk** [comment]
Hi! This is still reproducible in 92.2.0. Don't know if @fevziomurtekin is already working on it, but if he isn't, could I pick this one? (@AndiAJ @amedyne)

**Comment by pedroldk** [comment]
I've opened a PR which fixes the problem https://github.com/mozilla-mobile/fenix/issues/22308

**Comment by SoftVision-LorandJanos** [comment]
Tested on a previous build (eg. 99.1.0RC) where I could reproduce the issue.
Verified as fixed on the latest Nightly 100.0a1 (2022-04-01) build.
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.
