### ISSUE TITLE
[Bug]: Unable to dismiss the context menu when long tapping on the tabs counter on Android 5.1.1

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#22312]
### Steps to reproduce

1. Open Fenix.
2. Perform a long tap on the "Tabs counter button".
3. Tap on the page, tap the device back button.

### Expected behaviour

The context menu is dismissed.

### Actual behaviour

The context menu can't be dismissed, but is no longer displayed when a option is tapped.

### Device name

Huawei MediaPad M2 

### Android version

5.1.1

### Firefox release type

Firefox Nightly

### Firefox version

95.0.0-beta.1

### Additional information

Not reproducible on OnePlus A3 (Android 6.0.1), Samsung Galaxy Tab S3 (Android 9).

**Comment by Siva981** [comment]
I believe that this is a duplicate of issue #19664.

**Comment by Siva981** [comment]
All 3 issues are reporting the same defect.

#19664 
#17104 
#22312 (this issue)

**Comment by sflorean** [comment]
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/17104.
