### ISSUE TITLE
Toolbar does not animate until inertia scroll has stopped

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#22311]
### Steps to reproduce

Ensure toolbar is set to auto-hide / unhide
Go to mozilla.org or any other page
Ensure toolbar is visible
fling page up to start an inertia scroll
-> toolbar hides, correct behavior
before the inertia scroll stops, touch the screen to stop the inertia scroll then drag page down slowly
-> toolbar does **not** re-appear, **incorrect behavior**
The reverse is true, fling page down to re-appear the toolbar, the toolbar will not disappear unless the inertia scroll has stopped on its own first

I think this first started happening for me in Nightlies a few weeks ago & it has happened in every Nightly since

### Expected behaviour

I think the correct behavior is that touching the screen should cancel the inertia scroll AND a touch then drag should immediately animate the toolbar

### Actual behaviour

Touch correctly cancels the inertia scroll but touch then drag does not animate toolbar

### Device name

Galaxy A40

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly build #2015843499   2021-11-03T05:10:24:120708

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18560)

**Comment by SamuelMezger** [comment]
Still relevant.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813839

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
