### ISSUE TITLE
[Bug]: Tapping a search group item should switch to the previously opened website

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#22314]
### Steps to reproduce

1. Search for a term 
2. Open one of the results
3. Exit to the home screen
4. Tap the search group
5. Tap the item
6. Check tab counter
7. Open tabs tray
8. Check open tabs

### Expected behaviour

If the search group item is the same as the tab opened previously it should switch automatically to already existing tab

### Actual behaviour

The search group item is opened in a new tab

### Device name
OnePlus A3 Android 6.0.1

### Firefox version
Firefox 95.0.0 Beta 1
Firefox Nightly 96 from 11/04

### Additional information

► Video

https://user-images.githubusercontent.com/51314259/140317395-9a4e8d2e-9fc0-49f8-bf6b-50f59660cf0b.mp4

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 98.0a1 (2022-01-26).

Device used for testing:
- Oppo Reno 6 (Android 11).
- Google Pixel 4 (Android 12).

Closing the ticket as fixed.
