### ISSUE TITLE
[Bug]: Inconsistent behaviour when opening multiple items in a new tab from history compared to bookmarks

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#22315]
### Prerequisites
Have a couple history items
Have a couple bookmarked items

### Steps to reproduce
1. Open History
2. Multi-select a couple of items
3. Open them in a new tab
4. Dismiss the tabs tray
5. Check the toolbar 
6. Repeat the steps for Bookmarked items

### Expected behaviour
Same behaviour for both cases

### Actual behaviour
After opening the tabs from history the toolbar remains set to multi select mode (❗ Applicable for history search term groups as well)
After opening the tabs from bookmarks the toolbar returns to the default mode

### Device name
OnePlus A3 Android 6.0.1

### Firefox version
Firefox 95.0.0 Beta 1
Firefox Nightly 96 from 11/04

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18564)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 102.0a1 (2022-05-11) build.
Device used: Google Pixel 4 (Android 12).
