### ISSUE TITLE
[Bug] Private tab content should be blurred out in the app switcher

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2231]
Akin to Focus/Firefox on Android

https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE

**Comment by ekager** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/2768

**Comment by kbrosnan** [comment]
Closing in favor of #11153
