### ISSUE TITLE
[Bug]:Collections - Tapping on "Deselect all" doesn't change the state for tabs previously selected

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#22310]
### Steps to reproduce

1. Add a collection.
2. Go to homescreen and tap on the collection.
3. Open the 3dotmenu and select "Add tab".
4. Select 2-3 tabs.
5. Tap on "Select All".
6. Tap on "Deselect All".

### Expected behaviour

The tabs are not selected, the checkboxes are clear.

### Actual behaviour

The tabs selected at step 4 are still selected. 

### Device name

Huawei MediaPad M2 , Pixel

### Android version

Android 5.1.1, 12

### Firefox release type

Firefox Beta

### Firefox version

95.0.0-beta.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18559)

**Comment by Robert-Aron293** [comment]
Can I work on this?

**Comment by sflorean** [comment]
Verified as fixed on Nightly 5/24 with Nokia 6 (Android 7.1.1).
