### ISSUE TITLE
FNX-5534 ⁃ [Bug] Turning the QR code scanner in landscape triggers the keyboard

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2232]
## Steps to reproduce
1. Tap the search bar, tap the Scan button.
1. Turn the device in landscape mode.
    1. Expected behavior
QR scan camera turns to landscape, no keyboard displayed.
    1. Actual behavior
The keyboard pops up in landscape mode.
    1. Device information

* Android device: Pixel
* Fenix version: 5/2 build

**Comment by vesta0** [comment]
This seems to be fixed.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Fenix Build `#11850611 from 4/7 ` using the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)
• Sony Xperia Z3 (Android 5.1.1)
