### ISSUE TITLE
FNX-5535 ⁃ [Bug] tapping in QR Scan window shows search engine UI/keyboard

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/fenix#2233]
## Steps to reproduce
Pre-condition: Fenix homescreen. Camera has permission.

1. Tap on search bar
1. Tap on "shortcuts" button
1. Tap on "scan" button
1. Tap in middle of screen

### Expected behavior
Focusing the camera

### Actual behavior
The search engine settings page comes up or the keyboard pops up. It seems like the UI behind the camera view is what is getting selected??

### Device information
* Android device: A pixel something
* Fenix version: 1.0.1918

**Comment by ekager** [comment]
Opened and picked up https://github.com/mozilla-mobile/android-components/issues/3015

**Comment by ekager** [comment]
Fixed and merged in AC so should be working in tomorrow's build

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.1.1920 (#11360657), with HTC 10 (Android 8), Google Pixel (Android 9), Sony Xperia Z5 Premium (Android 7.1.1).
