### ISSUE TITLE
[Bug]: Constant Life In Color popup

### ISSUE THREAD

**Issue by tonycstech** [mozilla-mobile/fenix#22338]
### Steps to reproduce

Start firefox.
Thats it.
Every time it starts, i get this prompt
![0](https://user-images.githubusercontent.com/61446662/140461412-b50512fc-bacd-43cb-bfdf-a089b13e32ff.jpg)
t.

### Expected behaviour

Never show

### Actual behaviour

Shows every time firefox starts

### Device name

PC

### Android version

Windows 10

### Firefox release type

Firefox

### Firefox version

94.0.1 (64-bit)

**Comment by cadeyrn** [comment]
This is the issues tracker for Firefox for Android. If you want to report bugs in Firefox for desktop you can do it there: https://bugzilla.mozilla.org/

**Comment by tonycstech** [comment]
i dont want to signup for another account to report the bug
too many logins, too many passwords to remember. too many places to store
my email address for spammers to access.
hell no

**Comment by cadeyrn** [comment]
Maybe just click the link before complaining? You can use your GitHub login on bugzilla.mozilla.org…

**Comment by tonycstech** [comment]
I did click that link.
Maybe I didn't see a way to login GitHub.
I don't care. I deleted my profile files and problem went away.
What's weird is that it happened only on one computer, not two.
Both are identical.

While back I was able to submit feedback but now they removed that feature.

Eve if it was there,.it would not be an issue they would resolve next day.

**Comment by kbrosnan** [comment]
Not related to Firefox for Android.
