### ISSUE TITLE
[Bug]: Incorrect visual alignment of Home Screen section titles and their 'show all' subtitles

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#22342]
### Steps to reproduce

Open home screen

### Expected behaviour

"Recent bookmarks" title and "Show all" to its right should be aligned the same way other section headers are (e.g. "Jump back in" and its "Show all")

### Actual behaviour

Different visual alignment of header and "Show all".

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

### Additional information

![image](https://user-images.githubusercontent.com/465422/140579864-f763bce0-88d9-4853-8960-5c498ee0cc98.png)

**Comment by grigoryk** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/22343

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on 96.0.0-beta.1 and Nightly 2021-12-08 and the "Show all" button is in level with the "Recent bookmarks" text.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- Oppo Find X3 (Android 11)
![Screenshot_20211208-152857](https://user-images.githubusercontent.com/50983519/145217095-988af1f7-e9d8-454a-a684-1597a18b8894.png)
