### ISSUE TITLE
browserAction not seen as user interaction for permissions.request

### ISSUE THREAD

**Issue by diafygi** [mozilla-mobile/fenix#22348]
### Steps to reproduce

1. Write an add-on that calls `browser.permissions.request(...)` inside the `browser.browserAction.onClicked` event listener (i.e. when the user taps the browser action icon in Menu > Add-ons > MyTestAddOn) (see example below).
2. The `browser.permissions.request` promise throws a `Error: permissions.request may only be called from a user input handler` error.

#### Test Add-on Example
`manifest.json`:
```json
{
    "manifest_version": 2,
    "name": "Test123",
    "version": "1.0",
    "background": { "scripts": [ "/background.js" ] },
    "browser_action": { "default_title": "Test234" },
    "permissions": [ "https://www.example.com/" ],
    "optional_permissions": [ "<all_urls>" ]
}
```

`background.js`:
```js
console.log("background.js!!!");

browser.browserAction.onClicked.addListener((currentTab) => {
    console.log("action click!!!");

    browser.permissions.request({ origins: ["https://www.example.com/"] })
    .then((givenPermission) => {
        console.log("givenPermission", givenPermission);
    })
    .catch((err) => {
        console.log("error", err);
    });
    // Output on Firefox for Android:
    //  action click!!!
    //  error [Error: permissions.request may only be called from a user input handler]
});

```

### Expected behaviour

On Firefox desktop, since the permission for the origin is already provided in the manifest, the promise returns `givenPermission = true`.

### Actual behaviour

On Firefox for Android, the promise throws an error: `Error: permissions.request may only be called from a user input handler`.

### Device name

Google Pixel 4a

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 (Build #2015843979)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18573)

**Comment by diafygi** [comment]
This issue is still present

**Comment by diafygi** [comment]
This issue is still present

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811608

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
