### ISSUE TITLE
[Bug]: Fennec crashes opening new tab

### ISSUE THREAD

**Issue by riveravaldez** [mozilla-mobile/fenix#22346]
### Steps to reproduce

1. Start Fennec
2. Hold the tabs counter box (right to the address bar)
3. Choose "+ new tab"

### Expected behaviour

New tab.

### Actual behaviour

Fennec crashes.

### Device name

Moto E LTE

### Android version

Android 10 (updated LineageOS 17.1-20211105-NIGHTLY-surnia)

### Firefox release type

Firefox

### Firefox version

93.1.0 (931000) [Fennec from F-Droid]

### Device logs

https://crash-stats.mozilla.org/report/index/b130eeb8-96a8-47ad-abbf-5e7ea0211106

https://crash-stats.mozilla.org/report/index/d1e5f8cb-3345-419c-a20d-a61920211106

https://crash-stats.mozilla.org/report/index/60bb51f2-0a1b-4f5e-9f33-dc5260211106

https://crash-stats.mozilla.org/report/index/76f18c0e-bfec-4abd-8107-f44de0211106

### Additional information

Several crash reports were sent immediately after each crash, those are the last four. Let me know if it's useful to provide more.
Fennec also crashes with other actions, for instance, when I tried to fill this bug report from Fennec itself (now I'm doing it from another computer).
Hope this helps. Right now I cant' use the browser...
Thanks a lot and kind regards!

**Comment by rgabbo** [comment]
I'm able to reproduce this also in Fennec 94.1.1 (941120) OS: Android 10.

**Comment by csadilek** [comment]
This has been fixed early in the 94 cycle: https://github.com/mozilla-mobile/fenix/issues/21506 and a crash with this signature should no longer be possible (as we handle and log the problem instead.)

@riveravaldez please try and upgrade to 94. Also, the feature crashing for you is not enabled in official builds of 93. So either something is wrong with the Fennec from F-Droid build (the feature should only be active in debug builds of 93), or maybe you enabled the history metadata feature manually in the debug UI in 93?

If you still experience this in 94, please share the version details from Settings->About Firefox, as well as a 94 crashreport link.

Fow now I'll dupe this to https://github.com/mozilla-mobile/fenix/issues/21506 , but please share ^^ and re-open if still a problem in 94.

**Comment by riveravaldez** [comment]
> maybe you enabled the history metadata feature manually in the debug UI in 93?

Thanks *an awesome lot* , @csadilek !!
That was precisely what I did and thanks to your explanation I just undoed, with the immediate result of an apparently perfect fix. ^o^

You saved me instantaneously. Thanks again.

Kind regards! <3
