### ISSUE TITLE
Addon settings pages moz-extension:// are shown as insecure

### ISSUE THREAD

**Issue by diafygi** [mozilla-mobile/fenix#22340]
### Steps to reproduce

1. Install an Add-On (e.g. Ublock Origin)
2. Go to that add-on's settings page (e.g. `moz-extension://484y3...`)
3. The extension's page is shown as insecure (see screenshot)

### Expected behaviour

Web extension pages should be not marked as insecure. This is the case for normal Firefox on the desktop (see screenshot).
![Screenshot_2021-11-05_07-04-10](https://user-images.githubusercontent.com/643187/140508215-c79f47cc-90ee-4b53-9399-b9fca2e50bfa.png)

### Actual behaviour

Firefox for Android shows extensions as not secure (the lock with a red line through it).

![Firefox_for_Android_web_extension_page](https://user-images.githubusercontent.com/643187/140508103-1232a23f-6bfe-4f32-b7b3-fc02e1ea2d34.png)

### Device name

Google Pixel 4a

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 (Build #2015843787)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18568)

**Comment by diafygi** [comment]
I just checked on Nightly `102.0a1` and this is still an issue.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813917

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
