### ISSUE TITLE
[Bug]: Swiping between tabs shows incorrect scroll state initially

### ISSUE THREAD

**Issue by mduchev** [mozilla-mobile/fenix#22352]
### Steps to reproduce

1. Open some site that is scrollable on one tab and scroll to some random position
2. Open another site that is scrollable on another tab and scroll to some random position
3. Swipe between these 2 sites

### Expected behaviour

Swiping between tabs will show the last scroll state of the page that's been swiped to.

### Actual behaviour

Swiping between tabs shows incorrect page scroll state and after some ms the correct one appears.

### Device name

Google Pixel 4a 5G

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

94.1.1

### Additional information

Here's a demo for the issue:
![screen-20211106-225012~2](https://user-images.githubusercontent.com/8217099/140623786-acdc9372-7391-45a1-ad58-fd8eae9ed6fe.gif)

The same thing happens if there was some temporary scrollable element when the page loaded (like a cookie popup). I've opened a page and the popup for cookies appeared. I've accepted it but when I swiped between the pages, the popup appeared for some time. 
See the second demo:
![screen-20211104-232004~2](https://user-images.githubusercontent.com/8217099/140623811-f0eaa519-61d6-4ab2-a083-aa47ee18999c.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18575)

**Comment by mariansima** [comment]
This issue also occurs on Samsung Galaxy A8 (Android 9) with:

- Firefox Nightly 95.0a1 2021-11-18
- 95.0.0-beta.4 2021-11-15
- RC 94.1.2 2021-11-08

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813206

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
