### ISSUE TITLE
Right click context menu does not work when using mouse

### ISSUE THREAD

**Issue by FSpark** [mozilla-mobile/fenix#22350]
### Steps to reproduce

1. Connect a mouse via Bluetooth or OTG
2. Visit https://vscode.dev or  https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/oncontextmenu with Fenix
3. Try to right-click

### Expected behaviour

Pop up menu when right clicking, like this

![firefox_RCLYHhXaie](https://user-images.githubusercontent.com/20501721/141147129-5f6916ec-3287-409e-947d-001e96e25b82.png)

It's necessary to distinguish from https://github.com/mozilla-mobile/fenix/issues/14412 . This menu is customized by the web page, not Fenix

### Actual behaviour

`oncontextmenu` cannot be triggered unless long pressed

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

### Additional information

Chromium-based browsers are all working well

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18574)

**Comment by Hussain-P99** [comment]
i would like to work on this issue.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1366274

**Comment by Aman0307** [comment]
@FSpark I would like to work on this issue if it is still not resolved.

**Comment by FSpark** [comment]
@Aman0307  Oh well, I just tested it and it still doesn't work, waiting for your good news, I'm willing to provide the test. :)

**Comment by Aman0307** [comment]
@FSpark could you please elaborate on how I can reproduce this issue?? I mean on which device and browser.

**Comment by FSpark** [comment]
@Aman0307 Firefox v107 is still the same, the conditions are obvious, just connect the Android mobile phone with a Bluetooth mouse and follow the above steps to reproduce. Did you already show the menu as shown above?

**Comment by Aman0307** [comment]
@FSpark  Thanks for the reply. Will update you in case of any progress.

**Comment by userse31** [comment]
Similar boat, the menu you get when "tapping&holding" cannot be summoned when using a mouse.

Also, clicking and dragging doesn't pan the screen, scroll through the page/menues, etc.

**Comment by Vasili-Sk** [comment]
Samsung Tab S8 in DEX mode, wire mouse connected to usb.
Browser have overall bad DEX-top expierence, mouse RMB does not work, MMB does work only for scroll. 
Also copy-paste from keyboard works only with english language, switching to latin makes it impossible to copypaste

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811607

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
