### ISSUE TITLE
[Bug]: The inactive tabs survey is not translated in Japanese

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22365]
### Steps to reproduce

Prerequisites: Fresh install or survey not accessed previously

1. Set the app language to Japanese
2. Open the 3-dot menu > Settings > Tabs
3. Tap the "Move old tabs to inactive" toggle to bring up the survey
4. Observe the title and the rest of the header options

### Expected behaviour

The survey is translated

### Actual behaviour

The survey is not translated

![254779801_3135874450070702_2120084206152257312_n](https://user-images.githubusercontent.com/89511597/140763740-391ba113-2d64-4c2c-a00f-45b018da694b.jpg)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

95.0.0-beta 1 2021-11-02

**Comment by Delphine** [comment]
Good catch!
This was brought up with @amedyne and Ashley on Slack, and seems like it's ok to take that risk until v95 comes out and we get these localized/

**Comment by SoftVision-LorandJanos** [comment]
Based on #22495, as the inactive tabs survey is turned off, I will close this ticket.
