### ISSUE TITLE
Bug 1740016 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#22364]

**Comment by Amejia481** [comment]
cc @bugbaru if you could provide us your Bugzilla username, we can add you to bug [1740016](https://bugzilla.mozilla.org/show_bug.cgi?id=1740016)

**Comment by Bugbaru** [comment]
sorry I was wrong, but I have corrected it earlier, look at the ticket
https://bugzilla.mozilla.org/show_bug.cgi?id=1739934
By email: ***@***.***

Pada tanggal Sen, 8 Nov 2021 22.45, Arturo Mejia ***@***.***>
menulis:

**Comment by Amejia481** [comment]
@Bugbaru no problem, could you add me to the cc list amejiamarmol@mozilla.com?

**Comment by Bugbaru** [comment]
yes it has been added can you confirm this bug immediately with your team?

Pada tanggal Sen, 8 Nov 2021 23.26, Arturo Mejia ***@***.***>
menulis:

**Comment by Amejia481** [comment]
Thanks, we can continue discussing there.
