### ISSUE TITLE
[Bug]: Opening a recently closed tab opens it at top

### ISSUE THREAD

**Issue by vanillajonathan** [mozilla-mobile/fenix#22372]
### Steps to reproduce

1. Have a tab open.
2. Close it.
3. Click on the ... menu
4. Chose "Recently closed tabs"
5. Open the tab you just closed

### Expected behaviour

The tab should open at the bottom of your tab list.

### Actual behaviour

The tab opened at the top of your tab list.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18583)

**Comment by Choucroute-melba** [comment]
Hi, I wanted to work on this issue but it seems that the restore location is hard-coded in mozilla.components.feature.tabs, wich is in another repos _(Houston, we have a problem...)_

It's my first contribution and I am a little bit confused, what should we do in this case ?

Thanks :)

**Comment by vanillajonathan** [comment]
It  seems this is located in the `android-components` repository.
https://github.com/mozilla-mobile/android-components/tree/main/components/feature/tabs/src/main/java/mozilla/components/feature/tabs

**Comment by Choucroute-melba** [comment]
Ok, so I need to modify this repos ?

**Comment by vanillajonathan** [comment]
I would think so.

**Comment by jonalmeida** [comment]
@amedyne (who triaged this) it was originally intended for tab to be restored to the top of list. Did that change?

**Comment by vanillajonathan** [comment]
@jonalmeida Seems rather counterintuitive.

**Comment by vanillajonathan** [comment]
This seems to have been fixed, so I'll close this issue now.
