### ISSUE TITLE
IllegalStateException: Composed into the View which doesn't propagate ViewTreeLifecycleOwner!

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22383]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/13334589/?referrer=github_plugin

```
IllegalStateException: Composed into the View which doesn't propagate ViewTreeLifecycleOwner!
    at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:20)
    at android.view.View.dispatchAttachedToWindow(View.java:20190)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3463)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3470)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2138)
...
(13 additional frame(s) were not displayed)

Composed into the View which doesn't propagate ViewTreeLifecycleOwner!
```

**Comment by pocmo** [comment]
The stack trace doesn't contain any of our code. But it happens enough that it may be worth investigating - and maybe filing against Compose.

It shows up in our list of top crashes in Nightly too.

https://crash-stats.mozilla.org/signature/?product=Fenix&version=96.0a1&signature=java.lang.IllegalStateException%3A%20at%20androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow%28AndroidComposeView.android.kt%3A20%29&date=%3E%3D2021-11-02T09%3A54%3A00.000Z&date=%3C2021-11-09T09%3A54%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#summary

**Comment by pocmo** [comment]
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/platform/AndroidComposeView.android.kt;l=968;drc=6eace1ebfa98add8b00ee1b312204a2efd4140e6

**Comment by rvandermeulen** [comment]
This is showing up in the Fenix 95 topcrash list: https://bugzilla.mozilla.org/show_bug.cgi?id=1747118

**Comment by mcarare** [comment]
This is quite easily reproducible. All you have to do is fling the home screen top to bottom and back a few times.

**Comment by mcarare** [comment]
Fixed in https://github.com/mozilla-mobile/fenix/pull/22952. Will reopen and investigate if the crash will reoccur in the future.
