### ISSUE TITLE
[Bug]: History delete button labeled as "more options" for screenreader

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#22388]
### Steps to reproduce

1. Enable the screenreader on your device.
2. Open Firefox and access a recent searches history group or the full history list.
3. Select the "X" delete button.

### Expected behaviour

The screenreader should call this "delete item" or something similar.

### Actual behaviour

The screenreader announces this button as "more options."

### Device name

Samsung Galaxy S9

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

**Comment by SoftVision-LorandJanos** [comment]
Hi @Verdi! Thank you for your report.
I could reproduce the issue you described.
Tested on the latest Nightly (2021-11-09T20:53:41.748554).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on the latest Firefox Preview Nightly 2021-11-19. When navigating to the delete option from recent searches history group and the full history list using talkback gestures it is read as "Delete button".

![search](https://user-images.githubusercontent.com/50983519/142646965-bf725ac6-c1dd-4f66-b6ff-d2c48fd9796b.png)
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
