### ISSUE TITLE
[Bug]: Firefox 94 android uses multiple codecs is that the correct behavior?

### ISSUE THREAD

**Issue by Mohmoulay** [mozilla-mobile/fenix#22396]
### Steps to reproduce

1. Having Kurento Media server installed.
2. Creating a simple WebRTC client via JS to communicate with the media server and record videos.
3. Open client from Firefox 94 via Android.
3. Record the video and save it.
4. (I can give you access to try it with our product).

### Expected behaviour

Video can be recorded the process can be finished. Fully recorded video and no problem
![Screenshot_20211108-164146_Firefox (1)](https://user-images.githubusercontent.com/28956501/141084376-cff66b45-d854-44be-aa84-364e76564e8d.jpg)
s.

### Actual behaviour

Video is recorded but is all in black. Most probably due to the codecs used in Firefox 94 version.
![Screenshot_20211108-144745_Firefox (1)](https://user-images.githubusercontent.com/28956501/141084342-b93aa4ca-c7f5-4881-b31a-d46ba54bf85a.jpg)
.

### Device name

Samsung S10+

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94

### Device logs

![Screenshot_20211108-144745_Firefox (1)](https://user-images.githubusercontent.com/28956501/141084433-dbc1de95-5e3a-47f9-af50-ce07b27b8263.jpg)

### Additional information

I think it's due to the extra Codecs added. Since, I checked with an older version of Firefox (67) and the rtpmap is (H264 and VP8) on the other hand with Firefox (94) it's attached in this screenshot. Is that the behavior that you guys want?
![Screenshot_20211108-144745_Firefox (1)](https://user-images.githubusercontent.com/28956501/141084618-f1decbc9-8efc-45a5-b84f-8084c3a31c3f.jpg)
t

**Comment by Mugurell** [comment]
Moving to Bugzilla for more investigations from the media team.
Please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1740505

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
