### ISSUE TITLE
2s+ between hitting PWA app icon and displaying an content (white screen) from the app

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22408]
_Maybe a dupe of https://github.com/mozilla-mobile/fenix/issues/14897_

## Steps to reproduce
- Install PWA: go to twitter.com and click "Install" in the 3-dot. "Add automatically"
- Force-stop the app
- Click the new twitter PWA icon

### Expected behavior
App launches quickly

### Actual behavior
A delay of 2s+ from hitting the app icon until we display any content – a white screen. This doesn't happen with the main app start up.

https://user-images.githubusercontent.com/759372/141176034-da8e45b0-234f-4186-9e8f-4a9b6602c2cf.mp4

durations > 1s interrupt a user's flow, making their thought processes no longer seamless.

### Device information

* Android device: Moto G5 (csadilek can't reproduce on Pixel 3)
* Fenix version: Nightly 11/9-ish

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18606)

**Comment by mcomella** [comment]
help wanted: this may be difficult to fix unless you can reproduce – i.e. have a low-end device (Samsung A* series, older flagship phones like Galaxy S7)

**Comment by reyis4402** [comment]
Time increases more if any addons is installed
https://user-images.githubusercontent.com/60405617/141201832-ba093e90-cd38-43f4-b904-3f2d0371253b.mp4

**Comment by reyis4402** [comment]
Xiaomi Mi 9t
uBlock + Noscript

**Comment by oddgrd** [comment]
I have the same issue, about 2+ second delay from hitting the app icon until content loads. I tested on a PWA with 100 pagespeed-insights score on the landing page. When I install and run the PWA with Chrome, the delay is much shorter and also alleviated by the splash screen.

Galaxy S9 with uBlock, strong internet connection.

**Comment by mraonea** [comment]
@reyis4402 @oddgrd 

You need to set `suspendTabsUntilReady no` in advanced settings to prevent uBlock from blocking browser startup during its initialization:

https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready

I dont know why that is not set as `no` by default on mobile as it causes a heavy delay opening Firefox and this particular issue keeps repeatedly surfacing itself as dupes. Maybe take it up with @gorhill

**Comment by gorhill** [comment]
> I dont know why that is not set as `no` by default on mobile

Because the page won't be filtered properly by uBO, meaning trackers/ads will get through before uBO is fully ready.

**Comment by mraonea** [comment]
Yeah, meanwhile people keep creating duplicate issues here or clogging legit issues with irrelevant comments about the behaviour like in this instance because they dont understand uBlock is the root cause of their issues.

**Comment by gorhill** [comment]
When uBO launches with a memory snapshot, it's launch the fastest.

A memory snapshot is present when filter lists haven't been updated in the last few minutes. 

Also, how many filter lists are enabled affect launch speed -- ultimately if uBO is found to be the issue, there need to be a disclosure of how many filter lists are enabled, and whether the issue occurs after the filter lists have been updated and uBO had opportunity to save a memory snapshot, which should occur after ~4 minutes when mo filter lists are out of date.

**Comment by kudlav** [comment]
`suspendTabsUntilReady` was removed and disabling 
_Suspend network activity until all filter lists are loaded_ doen't make any difference

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807344

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
