### ISSUE TITLE
[Bug]: Safe Browsing does not block malware page

### ISSUE THREAD

**Issue by mraonea** [mozilla-mobile/fenix#22407]
### Steps to reproduce

Go to https://testsafebrowsing.appspot.com/

Click on Should show a malware warning link

Firefox does not display a malware warning

### Expected behaviour

Page should be blocked

### Actual behaviour

Page is not blocked

### Android version

10

### Firefox release type

Firefox

### Firefox version

94.1.2

**Comment by Mugurell** [comment]
Thank you for the report!
I see that link being blocked on desktop but not on mobile.
Moving to Bugzilla for more investigation by the GeckoView team, please follow the progreess there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1740694

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
