### ISSUE TITLE
[Bug]: Pull to refresh (and scroll) issues on reuters.com

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#22419]
### Steps to reproduce

Navigate to reuters.com
drag upwards to move the page a few inches
release finger
drag downwards a little, release, repeat drag downwards, again and again
every 2nd drag down does not move the content
ie 
drag downwards -> content moves
release
drag downwards -> content does not move
release
drag downwards ->  content moves

Sometimes I think pull to refresh gets triggered but I don't have STR for that

### Expected behaviour

drag downwards should always move content (except at end stops)

### Actual behaviour

only every 2nd drag downward works

### Device name

Galaxy A40

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Build #2015845035 2021-11-11T05:12:02.656238

**Comment by SoftVision-LorandJanos** [comment]
Hi @Cheap-Skate! Thank you for your report!
I managed to reproduce your issue, except for the pull to refresh part, that worked fine for me, only at the top of the page.
Tested on the latest Nightly 96.0a1 (2021-11-15T05:09:26.668704).
Verified on Chrome as well for comparison where scrolling works as expected.
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by Cheap-Skate** [comment]
(1) the same "every second drag" problem occurs on https://m.gsmarena.com/samsung_officially_starts_one_ui_4_with_android_12_rollout_for_the_galaxy_s21_family-news-51845.php and other stories on gsmarena.com.

(2) If you scroll to the middle of the reuters.com page, put Fenix into the background for some time (half an hour???) and then bring it to the front and swipe down with your thumb, sometimes it triggers pull to refresh when it should not. But I do not have reliable STR for this.

Galaxy A40, Android 11

**Comment by Cheap-Skate** [comment]
This is a pull to refresh issue. If I disable pull to refresh in the Fenix menus the scrolling behaves properly ie every drag results in a scroll.  I have amended the issue title.

**Comment by Cheap-Skate** [comment]
Duplicate of #21536
