### ISSUE TITLE
Add copy/share link buttons when inside the address bar

### ISSUE THREAD

**Issue by Tursko** [mozilla-mobile/fenix#22417]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Other browsers give us the option to either quickly copy and share the link in the address bar with dedicated action buttons. This would make links much easier to share.
### How do you know that this problem exists today? Why is this important?
Currently you have to long press, select all, and then copy. This experience is a bit slow. I want to be able to at least copy links quickly.
### Who will benefit from it?
All users. It will be easier to share links.

Example from Vivaldi (and other chromium based browsers)
![signal-2021-11-10-22-45-19-962~2.png](https://user-images.githubusercontent.com/18274896/141324195-faa8b1ef-2622-48ae-a2cd-f677f2fe4c15.png)

Similar request: https://github.com/mozilla-mobile/fenix/issues/14313

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18615)

**Comment by basings** [comment]
I am not sure if the browser should fix the shortcoming of the keyboard. I use [florisboard](https://f-droid.org/en/packages/dev.patrickgold.florisboard/) and I have a copy and a paste button.

![ss](https://user-images.githubusercontent.com/92867705/141677734-ddf7fdbd-5c47-41a9-bd25-da3b464aa059.jpg)

**Comment by czlucius** [comment]
![Screenshot_20211230-172147_Firefox Nightly](https://user-images.githubusercontent.com/58442255/147738652-ae750299-ad90-49f5-bcc9-77bd6fcd7472.jpg)
For the copy links feature, perhaps you can try long-clicking the address bar? A list of options will appear, allowing you to quickly copy the URL.

**Comment by Tursko** [comment]
> ![Screenshot_20211230-172147_Firefox Nightly](https://user-images.githubusercontent.com/58442255/147738652-ae750299-ad90-49f5-bcc9-77bd6fcd7472.jpg) For the copy links feature, perhaps you can try long-clicking the address bar? A list of options will appear, allowing you to quickly copy the URL.

Thanks that actually really helps. I have always had a habit of single pressing the address bar, and then looking for a way to share/copy. I still would like a dedicated button for copy (and even sharing), but this helps me out a lot!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813695

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
