### ISSUE TITLE
MR2 telemetry: How many tabs are in tab groups

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#22410]
https://mozilla-hub.atlassian.net/browse/FNXV2-18428

We want to have a histogram-style breakdown of the number of tabs in each tab group in the tabs tray. Ideally, we want to know:
- Counter: How many tab groups have 2 tabs? 
- Counter: How many tab groups have 3-5 tabs? 
- Counter: How many tab groups have 6-10 tabs?
- Counter: How many tab groups have 11+ tabs?

**Comment by MozillaNoah** [comment]
Copying the description of this metric from metrics.yaml for convenience:

> The distribution of search term tab group sizes. Rather than reporting
      individual sizes directly as integers, it is currently desired to
      report the sizes according to certain size ranges.
      The "buckets" for reporting group sizes will be mapped as follows:
      * 2 tabs -> 1
      * 3-5 tabs -> 2
      * 6-10 tabs -> 3
      * 11+ tabs -> 4
      Where the reported number will be 1, 2, 3, or 4, accordingly.
      As an example, say a user has three groups of sizes 3, 6, and 15. The
      app will report 2, 3, and 4 when this metric is tracked.

**Comment by sflorean** [comment]
Tested on latest Nightly with Samsun A32 (Android 11) and here is the results based on the example above:

 "search_terms.group_size_distribution": {
            "values": {
              "2": 8,
              "4": 6,
              "3": 3,
              "1": 0,
              "0": 0
            },
@MozillaNoah let me know if anything else is needed.
