### ISSUE TITLE
[a11y] The Talkback frame can get out of the app-window on swipe 

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#22414]
### Steps to reproduce

1. Turn TalkBack (or the available screen reader) on.
2. Have some items on the "Jump back in" and "Recent searches" sections.
3. Have Pocket enabled.
4. Go to Homescreen, select each element and swipe the screen up and down to hide the selected element.

### Expected behaviour

The frame for every selected element gradually gets out of the window.

### Actual behaviour

The frame for some elements are shaking while swiping, and they get beyond the window, overlapping the content in both directions. (Private browsing button, Jump back in content, Recent searches content, The stories, topics and branding from the pocket section)

https://user-images.githubusercontent.com/48829350/141302459-492a2768-c12e-4119-b16e-e6b87ef7096b.mp4

### Device name

Xiaomi Mi11 Lite

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

95.0.0 beta2

### Additional information

The frame for the Private browser icon sometimes remains between the tab counter button and the settings button while swiping.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18612)

**Comment by mcarare** [comment]
This is not something configurable from inside the app, but a shortcoming of the way the Talkback selection frame is implemented.
Adding to this, I do not think the behavior described (the green selection frame being shaky) impacts the user experience as long as navigation and screen content reading is not affected.

cc @MReschenberg for input in this.

**Comment by LaviniaL99** [comment]
The issue is still reproducing on Firefox 96.0.0-beta4.

**Device model:**
Samsung S10e -> Android 10

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Beta 109.0b3 build.
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809831

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
