### ISSUE TITLE
[Bug]: Sending tabs to a device AND closing them not anymore possible

### ISSUE THREAD

**Issue by MissTcat** [mozilla-mobile/fenix#22426]
### Steps to reproduce

1. Have some tabs open
2. Go to tab list
3. Select one or multiple tabs
4. Send tabs to a device

### Expected behaviour

1. Desired action happens, in this case tabs are sent to device.
2. Screen returns to the tab list, with the selected tabs still selected. 
3. Then more actions can be done with the already chosen selection. For example, close those tabs.

This used to be working but after some updates it disappeared.

### Actual behaviour

1. Desired action happens, in this case tabs are sent to device.
2. Firefox switches directly to the last open tab.

For closing the exact same tabs, you have to go back and select them again.

### Device name

Note 20 Ultra 

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

93.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18620)

**Comment by SoftVision-LorandJanos** [comment]
Hi @intrnl! Thank you for the report!
I could reproduce the behavior you described.
Tested with the latest Nightly 102.0a1 (2022-05-18T17:12:12.001240).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Google Pixel 4 (Android 12).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810634

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
