### ISSUE TITLE
[Feature] I want to reach "add to home screen" quicker

### ISSUE THREAD

**Issue by basings** [mozilla-mobile/fenix#22423]
### What is the user problem or growth opportunity you want to see solved?

The hamburger menu always opens collapsed instead of utilizing the full screeen height.

![menu_collapsed](https://user-images.githubusercontent.com/92867705/141372253-681d8496-2d19-4d84-9eff-622d39e345db.jpg)

![menu_full](https://user-images.githubusercontent.com/92867705/141372294-7bea839c-6aba-41bf-8834-eec6f24917c3.jpg)

### How do you know that this problem exists today? Why is this important?

It is based on user experience. It is important because it enhances the usability and the overall browsing experience.

### Who will benefit from it?

All users that have a screen height that is larger than the predefined menu hight.

**Comment by basings** [comment]
This could also be solved by a quick access toolbar. E.g. instead of the Home button a quick access buttom that opens up quickly with all cool features like add to home screen, add to top site, add to bookmarks, add to collections, install. Only buttons no text.

Or that toolbar is at the other end of the url bar with x custom quick access icons that is either shown always or disappears like the url bar when scrolling down.

**Comment by kbrosnan** [comment]
This would push commonly used items such as new tab out of the right thumb radius. In a future version we may reexamine the ordering.

**Comment by basings** [comment]
Thank you @kbrosnan. I tried to follow the guidelines of opening issues and keep the issue as open as possible. 

The ordering of the items is not a problem. If you move up "quit", you'll loose e.g. "find in page". There are 13 items in total, and only 8 are displayed when opening the menu. Although my screen is larger than 8 items, the menu does not open more than that, limiting me in the choices before I need to make another input. 

A quick fix to this, is not to limit the menu height by a fixed height but rather the screen height.
In #22446 this problem is described as well. There is an inconsistent behaviour of the menu bar. If you open it from a tab, you'll only see 8 items. If you open it from home, you'll see 11 items. Even thiugh you could directly have 13 items in the first option.

In the previous comment I proposed a quick access toolbar that would solve the problem as well. If you'd like to I can create a couple of mock examples so that it is easier to see what I mean. Although I'm no designer, but I'll give my best.

**Comment by basings** [comment]
On smaller screens, or in horizontal mode, quick access to cool features is missing as well. YOu don't need the description for "add to home screen". Magnifying glass is already recognized as a universal emoticon for search, it doesn't need a description. Maybe you can misunderstand it the first time as "search the web", but you'll learn that it means "find in page". 

If you then add search shortcuts like one for google, ddg, wikipedia, etc. this ambiguity goes away. Just a customizable quick access toolbar so you can have access to the cool features directly.

**Comment by basings** [comment]
I found this #21231. They talked about that as well and provided first drafts of mock apps. And appearantly other browsers have quick access features.

**Comment by basings** [comment]
#7151 is related to this as well
