### ISSUE TITLE
[Bug]:  The "14 days" section for the Flat list in history is not implemented

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#22420]
### Steps to reproduce

This is related to https://github.com/mozilla-mobile/fenix/issues/22013.

1. Do some searches and set the device date and time 7 days ahead of the searches.
2. Do some searches and move the device date and time 2 days ahead of the searches.
3. Do some searches again and move the date and time again with 5 days ahead.
4. Do some searches again and move the date and time again with 7 days ahead.

### Expected behavior
The flat list of all history for the given timeframe should display: Today/Yesterday/7 days ago/14 days ago. (Based on my steps).

### Actual behavior
Note that the 14 days ago option is not implemented. 

### Device name
Samsung Galaxy S21 Ultra

### Android version
Android 11

### Firefox release type
Firefox Nightly

### Firefox version
96.0.0 

### Additional information
Note that this info can be seen in the Jira ticket that is related to the Organised History. And there is Figma with the mentioned option.

![image](https://user-images.githubusercontent.com/42831109/141326890-1da5a992-d9ab-4279-a4aa-4629ec30c5bf.png)

**Comment by abodea** [comment]
Based on https://github.com/mozilla-mobile/fenix/blob/d9847f952534e2e69cb197f1632faf51b05e9b2a/app/src/main/java/org/mozilla/fenix/library/history/HistoryAdapter.kt#L105-L113
we have the following groupings: `Today`, `Yesterday`, `This Week`, `This Month`, `Older`

In my tests I saw the expected groupings based on time:
(each search contain the date and time set in system settings, screenshot taken on 26 Nov, 4:07)
<img src="https://user-images.githubusercontent.com/11428869/141149142-afebd16a-5719-4550-a4a4-a504af50642b.png" width="44%" />

**Comment by gabrielluong** [comment]
I pinged @topotropic to double check if we were suppose to have a 14 day section

**Comment by gabrielluong** [comment]
Spoke to @topotropic about this. She didn't really think we need the 14 day section since we already have a 30 day section. Unfortunately, I think we are filing issues because on mockups, but in @topotropic's words "never trust a mockup". We should make sure we validate these types of bugs with UX/Product or have them filed it.

**Comment by MatthewTighe** [comment]
Good advice! Closing this issue based on that
