### ISSUE TITLE
[Bug]: cannot install on Fly FS526 Power Plus 2, Android 7

### ISSUE THREAD

**Issue by Sergei-Alekseev** [mozilla-mobile/fenix#22436]
### Steps to reproduce

download latest apk from f-droid (android 5+ in description)
install in regular way.
message about incompatibility with device after some time installing.

### Expected behaviour

app installed

### Actual behaviour

nope

### Device name

Fly FS526 Power Plus 2

### Android version

Android 7

### Firefox release type

Firefox

### Firefox version

94.1.1

**Comment by Mugurell** [comment]
What is the incompatibility message you're seeing?
Have you tried installing it from Playstore - https://play.google.com/store/apps/details?id=org.mozilla.firefox

**Comment by kbrosnan** [comment]
We do not build APKs for F-droid. You can report problems with their APKs at https://forum.f-droid.org/c/apps/9
