### ISSUE TITLE
Android Autofill not working with Firefox for Android

### ISSUE THREAD

**Issue by jjpinom** [mozilla-mobile/fenix#22440]
I have an Android 11 mobile phone, with Firefox configured as the default browser, and Bitwarden as a Password Manager.

When I try to access a authentication page of any website, the autofill interface to select the credential stored in bitwarden does not work.

I need to copy the credentials in the Bitwarden app, and then paste them manually on Firefox

**Comment by Mugurell** [comment]
This should've been resolved in the last version of Bitwarden for all current Firefox releases.
Please try to update and if the problem still reproduces leave a comment here - https://bugzilla.mozilla.org/show_bug.cgi?id=1715549 with the versions of Bitwarden and Firefox you're using for more investigations.
