### ISSUE TITLE
Page elements not rendered correctly when overlay is triggered with address bar at bottom of screen

### ISSUE THREAD

**Issue by abhishekk07** [mozilla-mobile/fenix#22441]
### Steps to reproduce

1. Set Firefox address bar to bottom of screen
2. Open Twitter.com and scroll till address bar is hidden from view
3. click on retweet button 
4. "Close" button of Retweet/Quote Tweet overlay is hidden by black bar

### Expected behaviour

"Close" button of overlay should not be hidden by black bar

Uploading Kiwi-browser.mp4…

### Actual behaviour

"Close" button of Retweet/Quote Tweet overlay is hidden by black bar

https://user-images.githubusercontent.com/38587833/141735868-9b88e56d-dfdf-45b8-9f04-0d9534ae10c2.mp4

![Screenshot_20211115-121142](https://user-images.githubusercontent.com/38587833/141735889-8f535e08-7a39-458f-997b-67a24585b73b.jpg)

### Device name

Oneplus Nord

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

I have not tested this on any other similar websites.

Tested on different browser(Kiwi Broswer for Android), could not reproduce the issue. So this is not a twitter issue

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18630)

**Comment by Mugurell** [comment]
The related functionality is currently being updated in https://bugzilla.mozilla.org/show_bug.cgi?id=1740289
We should recheck this after that lands.

**Comment by KevinBertjr** [comment]
[LoveDog](https://www.lovedoginc.pet) Inc” is the Certified Organization of Dogs top-notch Services Includes Dog Training, Boarding, Adoption Service, and much more.We strongly accept as true with in developing a trusting courting and an unbreakable bond among you and your canine via secure and demonstrated clinical education strategies and the information that each canine is unique.

**Comment by Carlostert** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Ibadat\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Ibadat\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



https://github.com/mozilla-mobile/fenix/issues/22441
--




</body>

</html>

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813698

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
