### ISSUE TITLE
Search Groups in Jump Back In do not also display in Recently Searched

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22442]
**Vision:**

As a user with a search term group, I find it confusing that I see the search term group in the Jump Back In section and Recent Searches section on my homepage, especially when they have different site counts

I want to see my recent searches once on the homescreen, so that it's immediately obvious where to click if I want to return to my search

**Acceptance Criteria**
- If a Search Group is displayed in Jump Back In, then it's not displayed in Recent Searches. Instead, the next Search Group from history will be displayed
- If the most recent tab is part of the Search Group displayed in Jump Back In, then it is not displayed in Jump Back In. Instead, the next most recent tab that is not part of the Search Group is displayed. If all recent tabs are part of the Search Term Group, then no tabs will be displayed in Jump Back In

Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-18423

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build.
Device:
- Pixel 3 (Android 12).
