### ISSUE TITLE
[Bug] Recent searches layout issues

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22445]
The recent searches layout is horizontally scrollable but when scrolled the items have a different layout and the menu is not properly anchored.

Another issue is that the divider is not showing.

https://user-images.githubusercontent.com/11428869/141793072-dec387ca-d5fe-4320-a377-d4bfa8612f10.mp4

cc @gabrielluong @topotropic

**Comment by Mugurell** [comment]
@topotropic  Seeing that this issues will only get worse with the addition of history highlights - there will definetly be more pages of "recent visits" to display now I was wondering if this section could have the same behavior as the Pocket articles - snap to the next page instead of scrolling to any position which can easily lead to strange situations.

The issue with the menu will then easily be solvable (if not automatically solved) and the only other needed change would be making sure that the group dividers also show - they are set to show but for some reason they don't.

https://user-images.githubusercontent.com/11428869/142909149-8d13057d-679f-4b94-8e14-b45c84cdfbc4.mp4

**Comment by topotropic** [comment]
Yes, we can follow the same snapping behavior that Pocket has. Thanks!
