### ISSUE TITLE
[Bug]: The icon for "close and erase history" hasn't been updated with the Proton iconography

### ISSUE THREAD

**Issue by redudant-overflowing** [mozilla-mobile/fenix#22450]
### Steps to reproduce

1. Go to Settings > Clear history on exit  > enable this option.
2. Go back to the Firefox main page and tap on the ellipsis menu.

### Expected behaviour

The icon for this menu item is not aligned with the new Proton iconography, in which icons have a thinner stroke.

### Actual behaviour

The icon having a thinner stroke.

### Device name

Galaxy A50

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

![WhatsApp Image 2021-11-15 at 19 45 26](https://user-images.githubusercontent.com/93951203/141865023-927d5d38-31a0-4fa2-af32-93335bc2075a.jpeg)

**Comment by zetastormy** [comment]
I think you mean Proton, which is the name of the new iconography. Photon is the old one.

**Comment by kbrosnan** [comment]
Need @mozilla-mobile/ux  to provide an icon.

**Comment by cwzilla** [comment]
@kbrosnan Here is the [updated icon](https://www.figma.com/file/Kv7wWr8vH6AQrGhu9vmjdE/Fx-Mobile-Icons?node-id=615%3A1165)! The link should take you directly to the icon with it already selected. Press **cmd + shift + E** and an export panel with x1, x2, x3, and SVG should be available for download. Let me know if you have any issues.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build, with Pixel 3 (Android 12).
