### ISSUE TITLE
Implement safe browsing/block deceptive sites

### ISSUE THREAD

**Issue by SpitFire-666** [mozilla-mobile/fenix#22452]
EDIT: I think FF Android just took some time to realise the site was a scam - you can probably close this ticket if all is in place already. Sorry!

[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I just got an scam SMS and clicked the link (for testing), **Firefox Android opened the scam site without any warnings**.

![image](https://user-images.githubusercontent.com/38451588/141886489-717776ac-5f22-460d-aaf5-22f661865a7c.png)

I then tested on **desktop firefox and it successfully warned me**:
![image](https://user-images.githubusercontent.com/38451588/141885677-9edb8c9b-d81c-4c62-a5ce-c71cfed7972e.png)

The site looks convincingly real and a non-technical person could easily be phished.

I tested on Chrome Android and it gave a deception warning too:

![image](https://user-images.githubusercontent.com/38451588/141886529-e3724144-800a-4293-80d8-7a9c9ea49c46.png)

### How do you know that this problem exists today? Why is this important?
Many scams/deceptions target mobile devices, especially SMSes. It is important that people are protected against phishing and other bad sites.

### Who will benefit from it?

Everyone!

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue and the site is blocked now. I will close this issue.
