### ISSUE TITLE
[Bug]: Scroll to collection is not working

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#22462]
### Steps to reproduce

1. Open tabs tray
2. Select a few tabs and add to collection
3. Tap on view collection

### Expected behaviour

Home is shown and scrolled to the collection

### Actual behaviour

Home is shown but not scrolled to the collection

### Device name

Google Pixel 3 XL

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18647)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on the latest Firefox Preview Nightly 2021-11-23.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
