### ISSUE TITLE
Get Jetpack Benchmark working on a wider range of devices

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22480]
_blocked by https://github.com/mozilla-mobile/fenix/issues/22649_.

Jetpack Benchmark seems to work on Android 10 and lower – our Moto G5 and A50 – but not our Pixel 2, Pixel 4, or Huawei device which run on Android 11 and greater. We should get it working on those devices because they're the future.

Here are some issues we ran into:
* [BLOCKED] Failed to grant permissions (all Android 11 UI tests fail?): https://github.com/mozilla-mobile/fenix/issues/22649
* Tried to convert fenix to a library module but ran into issues (same error as above)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18657)

**Comment by mcomella** [comment]
Triage: let's try again after https://github.com/mozilla-mobile/fenix/issues/22649 is addressed.

**Comment by mcomella** [comment]
Triage: #22649 doesn't look like it's getting prioritized so putting in low impact for now.

**Comment by mcomella** [comment]
Triage: the perf test team is prioritizing this work to start in H2. Putting in Waiting column so we remember to follow-up.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807345

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
