### ISSUE TITLE
I think you mean Proton, which is the name of the new iconography. Photon is the old one.

### ISSUE THREAD

**Issue by redudant-overflowing** [mozilla-mobile/fenix#22482]
I think you mean Proton, which is the name of the new iconography. Photon is the old one.

_Originally posted by @zetastormy in https://github.com/mozilla-mobile/fenix/issues/22450#issuecomment-970241108_

oops

thanks!

**Comment by grigoryk** [comment]
Must have been filed in error.

**Comment by redudant-overflowing** [comment]
Oh noes, sorry D:

**Comment by redudant-overflowing** [comment]
How can I delete this?
