### ISSUE TITLE
History UI deletion of items is very buggy

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#22486]
Hard to describe specific problems, but it appears to barely work for search groups (multiple deletion steps are required, e.g. delete a group, close the ui, open the ui, delete what's still remaining of the group, etc), and possibly for visits matching items in the groups.

STRs is to have a bunch of history, a few search groups, then try deleting items, closing the history UI, reopening it, and observing items re-appear.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18660)

**Comment by mariansima** [comment]
Alternative steps to reproduce:

1. Create a search group
2. Close the tabs belonging to the group
3. Remove them from Recently closed tabs in History UI
4. Remove items from the group in History UI

Expected: The group items are removed from the group and history

Actual: The history items show up again without the search group

**Comment by delia-pop** [comment]
Reproducible on Beta 100.0.0-beta.4 with Google Pixel 6 (Android 12).

**Comment by mavduevskiy** [comment]
@delia-pop 
Could you please verify if the issue was fixed?
I was doing some [work](https://github.com/mozilla-mobile/fenix/pull/23520) on history in March, and the usecase that @mariansima has described was working as intended.

**Comment by delia-pop** [comment]
Tested with the latest Fenix versions (Nightly 110.0a1 from 01/17, Beta 109.0b6 and RC 109.1.1 with Xiaomi 12 Pro (Android 13). I can no longer reproduce the issues mentioned above.
