### ISSUE TITLE
FNX-5540 ⁃ A Switch in Settings Menu to avoid taking Screenshot during browsing session

### ISSUE THREAD

**Issue by dg28gadhavi** [mozilla-mobile/fenix#2248]
It might help somewhat To those who are concerned with Privacy.Secondly,it might also save some user from family kids or some friend or some third-party user having access to the device physically who might take screenshots of some of the personal sessions or private sessions.

To enable/disable this settlings A Firefox Password ( kinda master password ) should be set.Some sorta encryption in general.

The mass might love this feature and their are strong chances of it being strongly accepted.

One last suggestion it should be enabled by default in Private/Incognito Mode/Tab.

**Comment by yoasif** [comment]
This makes sense as an option for private tabs, imo.

**Comment by vesta0** [comment]
Thank you @dg28gadhavi we are going to address your request in #2768
