### ISSUE TITLE
Turn off Inactive Tabs Survey

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#22495]
## User Story
[Jira link](https://mozilla-hub.atlassian.net/browse/FNXV2-18528)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (2021-12-07).

The survey is no longer activated.

Device used: Xiaomi Mi11 Lite (Android 11).

Closing the ticket as fixed.
