### ISSUE TITLE
PWA notification is not displayed at amazon.in

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#22492]
### Preconditions:
Fresh clean profile.

### Steps to reproduce:

1. Navigate to https://www.amazon.in/ .
2. Observe the footer of the page.

### Expected behaviour:

A notification pop-up is displayed regarding PWA  installation.

### Actual behaviour:

The notification is not displayed.

### Device name:

Operating System: Samsung A51 -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)

### Android version:

Android 11

### Firefox release type

Firefox Nightly

### Firefox version:

 Firefox Nightly 96.0a1 (2015846379 -lizard96.0a1-20211117094929lizard)/ Chrome Mobile Version 96.0.4664.45

### Additional information:

 1. Originally reported here: https://github.com/webcompat/web-bugs/issues/93704
 2. Reproducible regardless of the status of ETP.
 3. Also reproducible when navigating to: https://app.electricitymap.org/map
 4. Reproducible on the latest build of Firefox Nightly.
 5. Works as expected using Chrome:
![Screenshot_9](https://user-images.githubusercontent.com/75027050/142432277-6f50c3ad-0df3-40cc-9d05-6f91acbf525a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18665)

**Comment by SoftVision-LorandJanos** [comment]
Hi @softvision-raul-bucata, thanks for your report!
I was able to reproduce your issue.
Tested on the latest Nightly 96.0a1 (2021-11-19).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807417

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
