### ISSUE TITLE
[Bug]: Sharesheet labels do not have enough contrast in Dark Mode

### ISSUE THREAD

**Issue by czlucius** [mozilla-mobile/fenix#22490]
### Steps to reproduce

1. Turn on Dark Mode in Fenix Settings
2. Navigate to a webpage (e.g. https://mozilla.org)
3. Press the 3 dot menu
4. Share the website

### Expected behaviour

A sharesheet opens, and the labels beneath the icons for the apps are in white text on a dark gray background (or at least colors that provide adequate contrast)

### Actual behaviour

The labels in the sharesheet are practically illegible, black text in a gray background.

### Device name

Samsung Galaxy S20 FE 5G

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

The cropped screenshot below illustrates this issue.
![image](https://user-images.githubusercontent.com/58442255/142410856-fc00205f-5e22-49fb-a84f-850387fd8dde.png)
As seen, the labels and the background do not have enough contrast and this could annoy the user.

**Comment by czlucius** [comment]
Is this a duplicate of https://github.com/mozilla-mobile/fenix/issues/18768?
If it is, I will close this issue.

**Comment by kbrosnan** [comment]
Looks like it is.
