### ISSUE TITLE
[Bug]: text is unreadable

### ISSUE THREAD

**Issue by bornolbers** [mozilla-mobile/fenix#22504]
### Steps to reproduce

Install firefox 94.1.2 android.
At the most websites, text is not readable. I didn't make any change in firefox. I didn't notice if it happened after an update, but it happens for about 3 days. See files attached.

What I checked: about 30 websites. At everyone except from duckduckgo and 90% of support.mozilla the text was unreadable. I tried to take screenshots.

What I tried:
removed ublock origin (the only plugin installed) -->the problem remains
changed firefox language from system default (greek) to english --> the problem remains
removed my profile from firefox -->the problem remains
deleted cache (througn android options) -->the problem remains
deleted all firefox storage -->the problem remains
installed and used duckduckgo browser (that I think is a port of firefox) --> everything was ok
uninstall and install again firefox android --> in the beginning everything was ok!
in about an hour or one-two times close and start firefox --> the problem is here again.
I don't know what else I should try to fix it neither found any relevant article for help.

![Screenshot_20211119-010803_Firefox](https://user-images.githubusercontent.com/43625413/142596821-45bae702-0224-49d5-9358-de95040003aa.png)

![Screenshot_20211119-010825_Firefox](https://user-images.githubusercontent.com/43625413/142596836-116320fa-c164-4428-b591-e304fd2f95db.png)

![Screenshot_20211119-010834_Firefox](https://user-images.githubusercontent.com/43625413/142596857-b45d4940-fa0e-4e0e-90b0-02d0089ccba3.png)

![Screenshot_20211119-010846_Firefox](https://user-images.githubusercontent.com/43625413/142596868-32526329-8d67-423a-9e17-278e533b96de.png)

![Screenshot_20211119-010914_Firefox](https://user-images.githubusercontent.com/43625413/142596887-1b606b88-f122-4856-85a0-5671cc1586d6.png)

![Screenshot_20211119-010939_Firefox](https://user-images.githubusercontent.com/43625413/142596903-f0ef3832-d027-4409-aa58-38d7ee8a4776.png)

![Screenshot_20211119-010949_Firefox](https://user-images.githubusercontent.com/43625413/142596924-cbaa1065-55e7-4943-a4cc-f78b39b63c96.png)

![Screenshot_20211119-011005_Firefox](https://user-images.githubusercontent.com/43625413/142596938-d7f8ba9e-71b6-4457-889b-3fc3bf46b71f.png)

![Screenshot_20211119-011036_Firefox](https://user-images.githubusercontent.com/43625413/142596957-d904aa91-2e29-4580-ba4b-d1b8ebd4d64e.png)

![Screenshot_20211119-084553_Firefox](https://user-images.githubusercontent.com/43625413/142596978-923195b4-b4bb-4b08-ae01-f7fc5f799308.png)

![Screenshot_20211119-084633_Firefox](https://user-images.githubusercontent.com/43625413/142597000-bb10e071-ad7b-4a97-b113-20a55c9decb2.png)

![Screenshot_20211119-085145_Firefox](https://user-images.githubusercontent.com/43625413/142597021-988b0d83-744e-4056-b90f-201fbec459f7.png)

![Screenshot_20211119-085349_Firefox](https://user-images.githubusercontent.com/43625413/142597034-2656c8ef-640f-45dd-9d47-0a0ad759e191.png)

### Expected behaviour

text should be readable

### Actual behaviour

At the most websites, text is not readable.

### Device name

xiaomi redmi 4x

### Android version

android 9

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

I'm using lineage microg 16 (updated 12 November 2021)

I noticed that also in firefox support site, when it loads seems as it first loads the text in non-readable version and after that it corrects the 90% of it before the hole site is loaded.

when I copy from firefox and paste the text in another app, the text becomes readable

**Comment by Mugurell** [comment]
Thank you for reporting this and the thorough testing!
The step about `in about an hour or one-two times close and start firefox --> the problem is here again.` makes this harder to reason about. Is there any action in between that would lead to this? Any correlations that could help reproduce this is welcomed.

Could you try the current Nighly from Playstore - https://play.google.com/store/apps/details?id=org.mozilla.fenix and report if it happens there also?

In the meantime it would also help if you could go to about:support, click "copy text to clipboard", and attach the text here.

cc @jamienicol

**Comment by kbrosnan** [comment]
I wonder if this is a version of bz-1738700? The Nightly from the Play Store would be a good thing to check as the bug I mentioned is fixed there.

**Comment by bornolbers** [comment]
I tried something new that works. After uninstall and reinstall I didn't connect the firefox android to my firefox profile. Two days now everything is fine.

So, I suppose it is something that it couldn't be erased after delete all the used space of the app through android setting (strange), but it only is deleted with app uninstall. So after I connect again my profile the first time, this (wrong setting?) took some time to load again to firefox android and break it again.

I will sign in on firefox android again (after the 2-days test) to see if it broke again the text. Should I paste both about:support before and after or only during the problem?

**Comment by Mugurell** [comment]
Since it seems there is a particular configuration that leads to this, being able to compare the output from `about:support` before and after the issue would be nice.
Would be also interesting to know if this reproduces in the current Nightly.

**Comment by Mugurell** [comment]
This seems to be the same as https://github.com/mozilla-mobile/fenix/issues/22435 though there the effect is bigger with even image rendering being affected.
There is a test build in the second link from https://github.com/mozilla-mobile/fenix/issues/22435#issuecomment-970256275 which should have the issue fixed. Would be great if you could test that build @bornolbers and report if the issue is still there or seems fixed.
Unfortunately this seems like a device specific issue so it's hard for us to test and reproduce if not on that specific device.

**Comment by bornolbers** [comment]
As @Mugurell said in the beginning, I cannot either reason with this issue..
I use firefox for two days without sign in --> everything ok.
I sign in after that --> first day it was fine --> (thought that it has to be about signing in direct after install --> on the second day the problem is here again.. (I didn't change any setting, I avoid to even open the settings tab. I have just surfed).
I hope this is a device-specific problem. But it is the first time that happens (I use firefox on this device since I've bought it (3y)).

I tried both apks on #22435 (comment). In both everything works fine (I just tried google and wikipedia - both pages have the issue when it occurs). Unfortunately 

Now I uninstall and reinstall it without removing the profile first. I took snapshots of the about:support during the issue and after the new install (in new install again everything is fine). In new install I also include the raw data (I didn't notice the button in the first place). You can find the snapshots here: https://bit.ly/3FF4jZY

Now I want to try without login for more days to see if it the error comes back. What else I could try? This "on the second day" it also makes no sense to me either, because I didn't make any change. Should I try nightly with signing in?

**Comment by jamienicol** [comment]
I don't think bug 22435 is related to this.

@bornolbers yes, please try nightly for a few days and see if the problem comes back.

When the bug happens, does it happen all the time? No bug for a day, and then something happens and every time you open Firefox you see the bug? Or does it just happen some of the time?

**Comment by bornolbers** [comment]
When the bug happens, it happen all the time. Not in every website, but unfortunately in the most of them. So, a webpage might me either full (eg duckduckgo), either partial (eg firefox support page) and either no (most of them) readable.

**Comment by bornolbers** [comment]
As checked all these days.. On Firefox Nightly in all situations didn't occur the issue (although it was not the same firefox (?) cause it was updating almost daily). In the other hand, in default firefox for android installation, I don't know how, but the issue occur even with the above steps:
1. clean install
2. don't use it at all for a few days after install (for me it was 4 days)
3. the issue occurs when opened... without any change or usage or profile connect.
4. If it is only for me, maybe it is device specific after all...? Or others didn't report it? I don't know. I hope the first one.

**Comment by kbrosnan** [comment]
The possible fix is in our [beta release](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) now which gets updates 1-2 times a week. If that is still too frequent to check if this problem is still happening the Gecko 96 release will be on 2022-01-11 and you should get an update in 2-4 days after the 11th.

**Comment by bornolbers** [comment]
The issue remains on Firefox 95.1.0, but it didn't occur at all on nightly from 96 till 97.0a1. So, I will use nightly and I am going to  wait the 96 version. I hope that it will be fixed.

**Comment by bornolbers** [comment]
It happens again on Firefox 96. But it is still ok on Firefox beta.

**Comment by bornolbers** [comment]
@kbrosnan, Firefox 96 stable causes the same issue. Also after remove and reinstall. Although 96 beta, is ok since the beginning.

**Comment by bornolbers** [comment]
on 96.2 is fixed.
