### ISSUE TITLE
[Bug]: The "Remove" button has scrollable text when using holding gesture in "Recent searches" categories

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22508]
### Steps to reproduce

1. Create some recent search categories on the app homepage
2. Hold a finger down on a recent search group to display the contextual "Remove" button
3. Hold down a finger on the "Remove" button
4. Scroll up and down

### Expected behaviour

The text inside the button is static

### Actual behaviour

The text on the button can be scrolled up and down

https://user-images.githubusercontent.com/89511597/142649932-f702514f-03eb-415c-afcc-183be2543319.mp4

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 2021-11-19

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with Pixel 3 (Android 12).
