### ISSUE TITLE
Align label on home

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#22502]
Re-label "Sites: 3" to "3 sites" for search groups in the "Jump back in" section so that it aligns with how it works in the "Recent searches" section. Thanks!

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 96.0a1 (2021-11-23T05:55:53.255492).

Device used: Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.
