### ISSUE TITLE
Option to open browser Using Fingerprint sensor (Biometrics API) or Some Other Encryption (password/screenlock password)

### ISSUE THREAD

**Issue by dg28gadhavi** [mozilla-mobile/fenix#2250]
### Why/User Benefit/User Problem
It might benefit user in many ways.
First of all the user's who are concerned with privacy will love this feature as they might keep their browsing history or opened tabs or browsing session really private with this feature Secondly it might save a user from some other persona having physical access to his device.

### Acceptance Criteria (how do I know when I’m done?)
It might be widely accepted by mass and privacy focused users mainly.

**Comment by kbrosnan** [comment]
This is in current builds of Fenix.
