### ISSUE TITLE
[Bug]: setting of videos (youtube) not working

### ISSUE THREAD

**Issue by Palloxin** [mozilla-mobile/fenix#22513]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/142684573-958fc3aa-c2be-4b27-9d54-ca959dbc2e55.mp4

1-go to youtube and open a video
2-try to change the resolution through gear (top-right) 

### Expected behaviour

The gear should open the video setting once i tap on it.

### Actual behaviour

nothing, happens when i click on the gear

### Device name

huawei p8 lite 2017

### Android version

android 8

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

I can't turn on the loop of then video as well. i tried pressing the finger on the video to open the setting of the loop video but nothing happens.

**Comment by kbrosnan** [comment]
This works for me on a Pixel 2XL, Note 10 and an Android 8 emulator.

**Comment by Palloxin** [comment]
> This works for me on a Pixel 2XL, Note 10 and an Android 8 emulator.

i tried to disactivate the tracking protection but it still doesn't work.

**Comment by sflorean** [comment]
I wasn't able to reproduce this issue, following the steps, on Release build & Nightly. @Palloxin could you please check again, on latest Nightly? Thank you!
Devices:
- Huawei P40 Lite (Android 11)

**Comment by Palloxin** [comment]
The bug has been fixed, so i will close it.
