### ISSUE TITLE
[Bug]: Reader View button never shows up in first go

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#22514]
### Steps to reproduce

1. Open any page that you know for sure is supported by Reader View.
2. See that the icon is not there.
3. Switch tabs/tap on address bar/open settings.
4. Go back to the page.
5. Button appears.

### Expected behaviour

The button should show up the first time, without any user action.

### Actual behaviour

The button only appears when the "view" is recreated.

### Device name

Xiaomi Mi 5

### Android version

Android 10 (LOS 17.1)

### Firefox release type

Firefox

### Firefox version

94.1.1

**Comment by mariansima** [comment]
Hey @opusforlife2 thanks for submitting this issue. 

I have checked on several news outlets and Wikipedia articles but could not reproduce this issue. Can you give some examples of webpages where this happened? 

Please note that the button does not show up unless the page has finished loading.

Also, there is a newer version of Firefox available, which isn't guaranteed to fix the issue, but it is worth a try.

**Comment by opusforlife2** [comment]
Hi, thanks for looking into this!

Example webpages:
- https://anildash.com/2012/12/13/the_web_we_lost/
- https://indianexpress.com/article/explained/explained-el-salvador-bitcoin-city-7635303/
- https://www.thehindu.com/opinion/editorial/falling-short-on-data-protection-provisos/article37633990.ece

**Comment by mariansima** [comment]
Hey @opusforlife2 I could not reproduce the issue on the specified webpages. Could you record and add a video of the issue? 

Verified on Xiaomi Redmi Note 8T (Android 9) and Samsung Galaxy A8 (Android 9) with Firefox RC 94.1.2 2021-11-08

**Comment by opusforlife2** [comment]
@mariansima I have been betrayed. Those URLs worked just fine for me when I tested them again. I'll reopen the issue if I encounter this problem again _and_ am able to reproduce it more reliably.
