### ISSUE TITLE
Camera being crippled...

### ISSUE THREAD

**Issue by bitmodeler** [mozilla-mobile/fenix#22518]
I tried using camera capture, and markup+JS that works fine in Chrome, Edge, Opera, and Vivaldi does not work in Firefox. According to online articles, it was claimed that settings need to be set on a per-site basis.

Expecting somebody is going to go into their settings and do that?
NOT going to happen!

So a practical suggestion: make a readily available toolbar toggle to adjust the permissions for the currently visited site. When it is toggled to "on", the page can get automatically reloaded (so the camera setup will be done...)

If I am in error about settings needing to be set, please do point me to a good example that shows how to launch camera capture upon visit of a web page...

**Comment by kbrosnan** [comment]
Firefox is no different than Chrome AFIK. All Android apps need to be explicitly granted access to the camera by the user. Additionally web browser further check that the user wants the website to have access to the camera. So if you have not used the app before you will need to agree to two prompts for access to the camera.

**Comment by bitmodeler** [comment]
For some odd reason then I'm not getting those prompts on Android; I get them for every other major browser (or no prompts, but a camera immediately working...)

**Comment by bitmodeler** [comment]
(I suspect if I were to burrow into the browser's settings I could add it to a whitelist; but that's not practical for end-users...)
