### ISSUE TITLE
FNX-5542 ⁃ [Bug] Multiple selecting bookmarks cause flickering in other bookmarks in list

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2251]
## Steps to reproduce
1. Navigate to bookmarks
1. Tap three dot menu next to a bookmark, select "Select"
1. Select another bookmark

### Expected behavior
No flickering of other bookmarks.

### Actual behavior
Other bookmarks flicker as I tap to select a bookmark

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

[signal-attachment-2019-05-02-200653.zip](https://github.com/mozilla-mobile/fenix/files/3140325/signal-attachment-2019-05-02-200653.zip)

**Comment by ekager** [comment]
No longer an issue as far as I can tell, closing

**Comment by yoasif** [comment]
@ekager still seeing it - I can attach a new screencast if you like.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly 7/10. Device; Galaxy Note 8 (Android 9), Pixel (Android Q).
