### ISSUE TITLE
Opening links from saved logins in PWA will show the device homescreen

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22510]
### Steps to reproduce

Prerequisites: Have a PWA installed, with saved login credentials

1. Launch the PWA and open the login screen
2. Tap one of the fields to bring up the suggested logins menu
3. Select Suggested logins > Manage Logins > Saved logins
4. Tap on any item from the ones available in the list
5. Tap the button that opens the selected site (next to the URL)

### Expected behaviour

The user is redirected towards the link

### Actual behaviour

The PWA will go into background and the device homescreen is displayed. The link is still opened in Firefox, even if it is closed but is not brought into view

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 2021-11-19

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18676)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807416

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
