### ISSUE TITLE
Android Autofill not working

### ISSUE THREAD

**Issue by REVENTOR-EU** [mozilla-mobile/fenix#22521]
### Steps to reproduce

1. Open a App (example Aliexpress)
2. Go to user account login
3. Tap name or password form
4. Unlock Firefox note appears
5. Clicking this note does nothing

### Expected behaviour

Firefox should fill in the password, or ask for the master-password in order to fill in the password

### Actual behaviour

nothing happens

### Device name

Xiaomi Redmi Note 10 Pro

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18684)

**Comment by pocmo** [comment]
@ghost007 Thank you for reporting this. Can you help me reproducing this by answering the following question:

* Can you verify that Firefox is set as the autofill provider in the Android system settings?
* Is this the Aliexpress app you are using? https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd
* Can you go to Settings -> Logins & Passwords -> Saved logins and tell me the URL that is linked to your aliexpress account?

If you know any other apps that cause problems, please post them with the matching URL from your settings screen too. There can be different causes per app that I can investigate.

**Comment by ghost007** [comment]
- Yes, Firefox is set as autofill provider in Android.
- yes, thats the right Aliexpress App from PlayStore
- when saving the password in firefox on the mobile site of aliexpress the URL m.aliexpress.com is used to store the password.
- firefox isn't asking to save a password when filling in the details in aliexpress app.

when i set bitwarden to autofill, it is asking to save the password with the URL androidapp://com.alibaba.aliexpresshd
also autofill works on bitwarden. i tried to manually add this URL to firefox, but it only gives me the error "valid hostname required".

**Comment by pocmo** [comment]
> firefox isn't asking to save a password when filling in the details in aliexpress app.

Yeah, this part isn't implemented yet. This is https://github.com/mozilla-mobile/android-components/issues/11145

Nevertheless it should autofill from an already existing account. I'll try to debug this.

> I tried to manually add this URL to firefox, but it only gives me the error "valid hostname required".

Yeah, that won't work. Turning it into a (reversed) URL again, should work and autofill (if Aliexpress allows it): `https://aliexpresshd.alibaba.com`.

**Comment by chgayot** [comment]
I am having the same problem with all third party apps, the Unlock Firefox button can be pressed and nothing happens, then either disappear for 0.5sec and reappear immediately, or disappear completely. Lockwise was perfectly working. 

If this can help (on flipboard, but it's the same everywhere):
`12-26 12:50:01.575 I/ActivityTaskManager(3860): START u0 {cmp=org.mozilla.firefox/org.mozilla.fenix.autofill.AutofillUnlockActivity (has extras)} from uid 10211
12-26 12:50:01.605 W/ActivityTaskManager(3860): Tried to set launchTime (0) < mLastActivityLaunchTime (15478508)
12-26 12:50:01.640 I/System.out(2099): Lookup: webDomain=null, packageName=flipboard.app
12-26 12:50:01.641 D/BiometricService(3860): canAuthenticate: User=0, Caller=0, Authenticators=33023
12-26 12:50:01.641 D/BiometricService(3860): Package: org.mozilla.firefox Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
12-26 12:50:01.641 D/AuthService(3860): canAuthenticate, userId: 0, callingUserId: 0, authenticators: 33023, result: 11
12-26 12:50:01.689 W/logins::login(2099): Fixing login record {4540fb19-299a-43d3-b887-55399b0eaed8}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.689 W/logins::login(2099): Fixing login record {c440cfbd-c381-4aff-88ee-2d68287f7eb8}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.690 W/logins::login(2099): Fixing login record {c333eaa0-9814-47b9-89d6-ae3ed872e3c1}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.690 W/logins::login(2099): Fixing login record {7af5ae76-2cda-417a-8b84-004a1d952aa7}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.691 W/logins::login(2099): Fixing login record {26687e99-b54e-4dce-951a-49417e8cd468}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.692 W/logins::login(2099): Fixing login record {a9e45cad-f735-4cc6-86a0-7f9bbe18500a}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.692 W/logins::login(2099): Fixing login record {460d437b-56e8-49d8-83bf-f05f5d51144f}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.693 W/logins::login(2099): Fixing login record {cb98db33-2574-4131-ac50-7f402354a1c5}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.694 W/logins::login(2099): Fixing login record {14711992-dd2a-451e-9dd2-08398300012b}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.694 W/logins::login(2099): Fixing login record {38478788-7a92-416f-aeec-df6c6b715be9}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.695 W/logins::login(2099): Fixing login record {c459690e-5340-40bc-9b35-9fe1f9640e46}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.695 W/logins::login(2099): Fixing login record {80835c1b-4129-4a3f-a663-bee30fff3ed5}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.697 W/logins::login(2099): Fixing login record {370e1cae-8770-4e26-af99-52f215e73a09}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.697 W/logins::login(2099): Fixing login record {39694486-3723-4b57-a0d2-54f0a948e220}: IllegalFieldValue { field_info: "Origin is not normalized" }
12-26 12:50:01.794 I/FenixApplication(2099): onTrimMemory(), level=20, main=true
12-26 12:50:01.826 W/System  (4261): A resource failed to call release. `

**Comment by maddawg836** [comment]
I can confirm this issue is because there is no lockscreen password. I set a pass and the unlock prompts for it. Once I entered it, i removed and tested the feature again, it worked for about 10 minutes until the issue re-appeared. 

Please remove the restriction or check for password. I believe I tried to set a master password for login but the app only seems to look for the phone lock info.

**Comment by Juriyx** [comment]
My proposition is to remove the request for entering the password or fingerprint, because the device is already unlocked!

**Comment by buscon** [comment]
any update on this issue?

**Comment by maddawg836** [comment]
> 

I ended up download the old lockwise, apparently no one told it to stop working.

https://github.com/mozilla-lockwise/lockwise-android/releases

**Comment by cadeyrn** [comment]
Using a password manager (!) that no longer receives security updates (!). What could possibly go wrong with that? *facepalm*

**Comment by buscon** [comment]
I actually followed this steps and now it works as it should: https://support.nordpass.com/hc/en-us/articles/360006703397-How-to-enable-Autofill-on-Xiaomi-devices-

**Comment by maddawg836** [comment]
> Using a password manager (!) that no longer receives security updates (!). What could possibly go wrong with that? _facepalm_

having firefox not update and you being a douche? world is full of interesting people.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812436

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
