### ISSUE TITLE
FNX-5543 ⁃ [Bug] No way to view desktop bookmarks

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2252]
## Steps to reproduce
1. Open Bookmarks

### Expected behavior
Option to view "Desktop Bookmarks" like in Fennec.

### Actual behavior
No way to view desktop bookmarks.

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by ReekyMarko** [comment]
Totally unrelated but how do you get Fenix from the play store? Would be great to not have to manually update

**Comment by ArnauNinerola** [comment]
@ReekyMarko  You have to join the android beta program. I got an email with instructions.

**Comment by softvision-miralobontiu** [comment]
Verified that the "Desktop Bookmarks" folder is displayed in Bookmarks, with the latest build 1.0.1921 (#11440614), with Google Pixel (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by klint** [comment]
Maybe related to another bug: yes I can see the desktop bookmarks entry, but it is still  empty.

**Comment by ArnauNinerola** [comment]
It also works for me. I can see the desktop bookmarks. Fenix build (1.0.1921) and Android (9) Oneplus 6T (Oxygen OS 9.0.13)

**Comment by grigoryk** [comment]
@klint are you logged into Firefox Account? If you check in Firefox Desktop's sync settings, do you see that bookmarks are enabled to sync?

**Comment by klint** [comment]
> 
> 
> @klint are you logged into Firefox Account? If you check in Firefox Desktop's sync settings, do you see that bookmarks are enabled to sync?

Silly me, I had 2 Firefox accounts and I just have noticed that I was using the wrong one. I changed to the other one, and I'm happy to report that all the bookmarks are visible now. 
Thanks
