### ISSUE TITLE
firefox nightly uses https rr as altsvc only when DoH is enabled

### ISSUE THREAD

**Issue by Lanius-collaris** [mozilla-mobile/fenix#22520]
### Steps to reproduce

1. set trr.mode=0
2. open "https://cloudflare.com"

### Expected behaviour

firefox also querys https rr then loads it using HTTP3

### Actual behaviour

firefox loads it using HTTP2

### Device name

Huawei Nova 5 Pro (SEA-AL10)

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 (Build #2015846571), f0a3653d7+ AC: 96.0.20211117143034, be2606b611 GV: 96.0a1-20211117094929 AS: 86.2.0

### Additional information

The https rr of cloudflare.com is <br>1 cloudflare.com (alpn="h3,h3-29,h3-28,h3-27,h2" ipv4hint="104.16.132.229, 104.16.133.229" ipv6hint="2606:4700::6810:84e5, 2606:4700::6810:85e5" )<br>
I use quad9 dnscrypt server.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18683)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813704

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
