### ISSUE TITLE
Issue with firefox new feature of creating groups in history 

### ISSUE THREAD

**Issue by honnybee7** [mozilla-mobile/fenix#22527]
### Steps to reproduce

1. Search a term in browser
2. You see it in the history

### Expected behaviour

In the past searchs just show up by themselves in the history 

### Actual behaviour

Now searches create folders of searches in history, it also messes with scrolling down in your history and random sites unrelated to the search end up with the folder the messed with your viewing of your history 

### Device name

Samsung galaxy a6

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

94.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18689)

**Comment by mariansima** [comment]
Hey @honnybee7 Thanks for submitting this issue! This is not a bug, this is the intended behavior. 

So when performing a searching from the app toolbar, every link opened from that tab will be added to a group related to the initial search term.

There is already a suggestion for changing this functionality here: https://github.com/mozilla-mobile/fenix/issues/22181

**Comment by mariansima** [comment]
Hey @honnybee7 if there is a problem in how scrolling works, can you record a video?

**Comment by honnybee7** [comment]
Right now its functioning normally but what happens on occassions when I try to scroll down is that it stops going down where one of these search results grouping files is

Also these files sometimes keep putting whatever site I'm on in the files that's unrelated to the search 

Is it possible that a disabling feature will be added soon

**Comment by honnybee7** [comment]
@mariansima hello is my issue being looked into?

**Comment by mariansima** [comment]
> Right now its functioning normally but what happens on occassions when I try to scroll down is that it stops going down where one of these search results grouping files is
> 
> Also these files sometimes keep putting whatever site I'm on in the files that's unrelated to the search
> 

Hey @honnybee7 I haven't been able to reproduce your issue on either Firefox, Beta or even Nightly builds. A video of the issue would have been very helpful in absence of more specific steps to reproduce. 

> Is it possible that a disabling feature will be added soon

Features are constantly improved, and there are other issues already submitted related to search groups that are being worked on which might solve your problem on one of the next updates. Please understand that development takes some time and if you want early fixes and updates you can also check out Firefox Nightly for daily updates.

**Comment by honnybee7** [comment]
Well the only thing that's easy to reproduce is the group files putting random files in. Try getting an image link put in google reverse search if text search result comes up than group in history is created than try visiting a different site like reddit and it will put every search in that folder after.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813707

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
