### ISSUE TITLE
Consider making bookmark folder selection more easy

### ISSUE THREAD

**Issue by chartmix** [mozilla-mobile/fenix#22524]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Make it easier to change the bookmark folder. 
### How do you know that this problem exists today? Why is this important?
After I add a bookmark I want to change the folder.
When I select the right folder I would expect that Firefox applies it automatically. 
But I have to press the arrow and then the checkbox. 

### Who will benefit from it?
Everyone who wants to organize bookmarks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18686)

**Comment by bigConifer** [comment]
This issue has been already filed [here](https://github.com/mozilla-mobile/fenix/issues/1514) by @yoasif a long time ago but was then mistakenly closed as dupe...

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812702

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
