### ISSUE TITLE
Show history highlights in "Recently visited"

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22534]
Help users easily locate relevant content from a previous browsing session by organizing and highlighting content that was meaningful and engaging, and filtering out the noise. 

Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-17824

### Acceptance criteria
- Section has been renamed from “Recent Searches” to “Recently Visited”
- When I open Home, I see a combination of individual tabs that are history highlights and history search term Groups in the “Recently Visited” section. 
- We will show the top 9 scored items. 
- We will show a min of 3 and a max of 6 groups (when available) and a min of 3 and a max of 6 highlights (when available) up to a total of 9 items.
- ~~“Recently Visited” section will include only closed tabs + groups with ALL closed tabs~~

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox 96.0.0-beta.1. The history highlights are displayed in the Recently visited section alongside regular websites. I will mark this issue as fixed.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- OnePlus 6T (Android 11)
![Screenshot_20211209-180408](https://user-images.githubusercontent.com/50983519/145432684-9744c87a-4dd3-4a84-80d2-556c67a83fbf.png)
