### ISSUE TITLE
FNX-5544 ⁃ [Bug] "Entering full screen mode" snackbar covers media players' controls.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2253]
## Steps to reproduce
Go to a website that contains videos
Play a video
Go full screen

### Expected behavior
Video controls are not covered

### Actual behavior
Controls are covered
![Screenshot](https://user-images.githubusercontent.com/32398857/57118546-6619ac00-6d3a-11e9-83a1-5e14ca3c06fb.jpg)UNITO-UNDERSCORE!20190503-001622!UNITO-UNDERSCORE!Gallery!

### Device information
* Android device: 8.0
* Fenix version: 1.0.1918

**Comment by cadeyrn** [comment]
I don't see a bug in the described behaviour. The snackbar is always on the same position and disappers after a few seconds.

**Comment by ekager** [comment]
Is this about the time it takes for the snackbar to disappear? It's currently Snackbar.LENGTH_LONG we could easily change it so Snackbar.LENGTH_SHORT

**Comment by ekager** [comment]
Could we get UX feedback on the time length of this snackbar (and this snackbar in general I suppose)?

**Comment by lime124** [comment]
i believe @topotropic has some rules for snackbar behaviour.

**Comment by topotropic** [comment]
@ekager what's the rational behind having a Snackbar here? I'm just wondering if we need it at all – if  we want to keep it, we'd have to render it above the navigational controls.

**Comment by lime124** [comment]
From UX meeting:
Make the duration shorter and offset it so it doesn't cover the controls.

**Comment by ekager** [comment]
There is not a simple way to place the snackbar above media controls since different sites may place these controls in different places. For now I've discussed a short term solution with @topotropic to just shorten the snackbar length, but we should revisit this later.

**Comment by kbrosnan** [comment]
For the fullscreen case we should be able to position the notification above our default controls which we fail to do. 

* go to https://commons.wikimedia.org/w/index.php?title=File%3AIBM_Selectric_II_typewriter.ogv
* rotate the phone to landscape if needed
* click the fullscreen button

We should verify this works in the portrait case as well.

**Comment by ekager** [comment]
Alright I've updated this for the snackbar to appear over the normal toolbar location. Do we think we can close this bug?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1924 (#11630619), with Samsung Galaxy A 6 (Android 5.1.1), and Google Pixel 3 (Android 9).
The "Entering full screen mode" is displayed shortly and doesn't cover the control buttons.
