### ISSUE TITLE
Opening pinned site on an existing tab shouldn't open a new tab

### ISSUE THREAD

**Issue by eylenburg** [mozilla-mobile/fenix#22531]
### Steps to reproduce

1. Have a tab open with any website
2. Tap on URL bar to show pinned websites
3. Open a pinned website
4. The website will open in a new tab

### Expected behaviour

The website should open in the same tab. Unless the user has opened an empty new tab first, the user most certainly wants to open the website in the same tab. 

### Actual behaviour

The website should open in a new tab, leaving the old tab open. Over time this accumulates many "dead" tabs.

### Android version

any

### Firefox release type

Firefox

### Firefox version

94.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18691)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813708

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
