### ISSUE TITLE
Intermittent gradle-dependencies - Java heap space

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#22536]
### Firebase Test Run:
[Provide a Firebase test run report link here showcasing the problem](https://treeherder.mozilla.org/logviewer?job_id=358848465&repo=fenix)
### Stacktrace:
```
> Task :app:shrinkReleaseRes

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > Java heap space
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > Java heap space
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/23ea13a3cfd590c957b83fdead555b1889072f51

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18695)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807296

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
