### ISSUE TITLE
Search history and bookmarks in the address bar doesn't work

### ISSUE THREAD

**Issue by fox7634** [mozilla-mobile/fenix#22546]
### Steps to reproduce

Search for any bookmarked or visited (history) website in the address bar by typing the initial letter(s) of that website.

### Expected behaviour

Bookmarked or already visited websites starting with that letter (or letters) are suggested.

### Actual behaviour

There are three types of behavior:
1) no suggestion appears at all
2) suggestions very briefly appear (too fast to be useful) and disappear
3) suggestions _do_ appear - this only happens after the application has just been restarted.

### Device name

Huawei P10

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

Disabling and re-enabling the "search bookmarks/history" in addressbar doesn't fix the problem. Neither does deleting the cache.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18703)

**Comment by amedyne** [comment]
@fox7634 There has been recent improvements related to this. Can you try Firefox Nightly and let us know if you are encountering the same problem?

**Comment by glock24** [comment]
Hello,

I have this same problem with Firefox since a couple of months, interestingly Fennec (from F-Droid) does not exhibit this problem.

**Firefox version:**
95.2.0

**Fennec version:**
95.2.0

**Device name**
Redmi Note 9S

**Android version**
Android 11 (LineageOS 18.1)

**Comment by boek** [comment]
I'm no longer able to reproduce. Bookmarks and history now show up under Firefox suggest. feel free to open a new issue on Bugzilla if you're still able to reproduce
