### ISSUE TITLE
Cannot use security keyboard in Android 11(MIUI 12.5 by Xiao Mi) 

### ISSUE THREAD

**Issue by RealMuDao** [mozilla-mobile/fenix#22542]
### Steps to reproduce

1.enter seetings
2.log in
3.input account
4.input password
The keyboard will not pop up when click the filling box,only if the security keyboard is disable.
![截图_选择区域_20211123203259](https://user-images.githubusercontent.com/19743480/143024785-0b8c8ba3-11df-4098-a1f8-4164bd49b154.png)

### Expected behaviour

use secury keyboard to input password

### Actual behaviour

the keyboard do not show

### Device name

MIUI 12.5

### Android version

android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18700)

**Comment by longmoon77** [comment]
I'm also using a Xiaomi phone and also had this problem. But you'd better do a screen recording to reproduce your problem, otherwise the developer may not understand it better.

**Comment by RealMuDao** [comment]
> Hi @RealMuDao! Thank you for your report! I also have a similar device, a Xiaomi Mi11 with Android 11 and MIUI 12.5 but I wasn't able to reproduce your issue. As mentioned in the above comment, please attach a video about your issue. Alternatively if you can clear your data, and try it on a clean build, it might help. Or maybe see if it reproduces on the latest Nightly. Thank you! Tested on the:
> 
>     * latest Release (94.1.2).
> 
>     * latest Beta (95.0.0 beta5).
> 
>     * latest Nightly 96.0a1 (2021-11-23T05:55:53.255492).
Thanks!Did you enable the security keyboard？I am from  China, maybe the Chinese edition is different from the international edition.

**Comment by longmoon77** [comment]
> > Hi @RealMuDao! Thank you for your report! I also have a similar device, a Xiaomi Mi11 with Android 11 and MIUI 12.5 but I wasn't able to reproduce your issue. As mentioned in the above comment, please attach a video about your issue. Alternatively if you can clear your data, and try it on a clean build, it might help. Or maybe see if it reproduces on the latest Nightly. Thank you! Tested on the:
> > 
> >     * latest Release (94.1.2).
> > 
> >     * latest Beta (95.0.0 beta5).
> > 
> >     * latest Nightly 96.0a1 (2021-11-23T05:55:53.255492).
> Thanks!Did you enable the security keyboard？I am from  China, maybe the Chinese edition is different from the international edition.
> 

please record a video to show that, thanks.

**Comment by longmoon77** [comment]
You could send the video to YouTube, then copy the link here. Thanks.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812069

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
