### ISSUE TITLE
The Play/Pause button is missing from the media notification from rockfm.ro stream 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#22548]
### Steps to reproduce

1. Go to rockfm.ro.
2. Play the audio stream.
3. Invoke the notifications bar.
4. Observe that the Pause/Play button is missing from the media notification.

### Expected behaviour

A Play/Pause button should be displayed on the media notification.

### Actual behaviour

The Play/Pause button is missing from the media notification.
Please note that if the audio stream is Played/Stopped from the lcok screen media notification repeatedly, then the notification bar is accessed, a proper media notification with a "Play" button will be displayed. The user can interact with the Play button only once, as presented in the video below.

### Device name

Samsung Galaxy Note10 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 (Build 2015847339)

### Additional information

https://user-images.githubusercontent.com/89388888/143051693-638a5451-f594-4b48-9442-633bacc2d31c.mp4

https://user-images.githubusercontent.com/89388888/143051132-c4c9c9a5-d603-4355-95a5-7f04abd792a5.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18705)

**Comment by delia-pop** [comment]
This is reproducible on 96.0.0-beta.3 with Samsung Galaxy Note10 (Android 11).

**Comment by delia-pop** [comment]
This is reproducible on RC 98.1.1 with Motorola Moto G30 (Android 11).

**Comment by delia-pop** [comment]
This is still reproducible on RC 100.1.2 with Huawei MediaPad M2 (Android 5.1.1).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809285

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
