### ISSUE TITLE
FNX-5545 ⁃ [Bug] no tab title on home

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2254]
## Steps to reproduce
1. Open https://www.theverge.com/platform/amp/2019/4/29/18522287/samsung-sero-vertical-tv-price-release-date-millennials
1. Open home

### Expected behavior
See tab title

### Actual behavior
No tab title is shown

![signal-attachment-2019-05-02-233925](https://user-images.githubusercontent.com/152493/57120355-e93d0100-6d3e-11e9-9cd1-826d05b7d3e7.png)

### Device information
* Android device: pixel 2
* Fenix version: latest from play store

**Comment by dector** [comment]
I'll investigate this.

**Comment by kbrosnan** [comment]
Sounds similar to #2709

**Comment by dector** [comment]
@kbrosnan Thanks! It is.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11500615), with Google Pixel (Android 9), and Nokia 6 (Android 7.1.1).
