### ISSUE TITLE
[Bug]: Pausing/Playing an audio file from soundcloud.com from the media notification causes a visual defect

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#22547]
### Steps to reproduce

1. Go to soundcloud.com.
2. Play the audio stream.
3. Invoke the notifications bar.
4. Pause/Play repeatedly the audio file from the media notification.
5. Observe the visual defect.

### Expected behaviour

The media notification should be displayed without any visual issue/color flicker when the audio file is Paused/Played. 

### Actual behaviour

The media notification displays a visual defect/color flicker when the audio file is Paused/Played. 

### Device name

Samsung Galaxy Note10

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 (Build 2015847339)

### Additional information

https://user-images.githubusercontent.com/89388888/143049676-3a7b3b5a-b9ee-4574-a7fb-bd2dc6f7ae6a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18704)

**Comment by delia-pop** [comment]
This also occurs on 95.0.0-beta.6 ( Build 2015847755) with LG G7 fit (Android 8.1.0).

https://user-images.githubusercontent.com/89388888/143452659-eb2b1e6b-73ec-4aca-9ac4-f1dba0b5f203.mp4

**Comment by LaviniaL99** [comment]
The issue is also present on RC 96.1.0 (Build 2015855507) -> **device used**: Samsung S10E - Android 10

**Comment by Mugurell** [comment]
Issue should be fixed by https://github.com/mozilla-mobile/android-components/pull/12492.
Please recheck.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 104.0a1 (2022-07-25) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Beta 104.0b1 build.
Device used: Samsung Galaxy Tab S3 (Android 9).
