### ISSUE TITLE
Main menu auto-closes after force stopping

### ISSUE THREAD

**Issue by nvxarm** [mozilla-mobile/fenix#22540]
### Steps to reproduce

1. **Must be logged in to FxA.** Force stop Firefox in Android settings
2. Open main menu in Firefox
3. Wait for just a second
4. It closes automatically

### Expected behaviour

It should keep open

### Actual behaviour

It closes automatically

### Device name

ASUS ROG Phone 5s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1 (Build #2015832083)

### Additional information

[Main-Menu-Auto-Closes.mp4](https://user-images.githubusercontent.com/16894061/132788247-131fe6f2-b0c3-4e04-a92b-1ec2ba90d169.mp4)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18699)

**Comment by LaurentiuApahideanSV** [comment]
I am able to reproduce the issue on Firefox RC 94.1.2 but not on the latest Nightly 2021-11-24. @nvxarm Could you download the latest Firefox Preview Nightly and see if the issue occurs on that build as well?

**Comment by nvxarm** [comment]
@LaurentiuApahideanSV I installed the nightly version from Play Store on the same device, and find the case can only be reproduced after you've logged in.

Below is what I saw after I logged in with my Firefox account.

As for why my mail is not displayed in the main menu, that's another known issue  (#22284)


https://user-images.githubusercontent.com/16894061/143253424-9ec7cf18-4f64-4370-ada8-9780f87cc43f.mp4


```
96.0a1 (Build #2015847531), 693a1dd8f+
AC: 96.0.20211123143336, 84bfc17589
GV: 96.0a1-20211123094249
AS: 86.2.0

2021-11-24T05:12:22.494674
```

**Comment by LaurentiuApahideanSV** [comment]
I am now able to reproduce the issue on latest Nightly 2021-11-24 as well. Being logged in is a necessary step in order to reproduce the issue.
