### ISSUE TITLE
Toolbar URL autocompletion doesn't match (some) urls present in history

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#22555]
STR:
- on fenix...
- visits https://www.bcferries.com/, follow a link to https://www.bcferries.com/current-conditions
- let it all load to make sure we have history recorded (and double check in the History view that visits were recorded)
- open a new tab, start typing bcferries. You'll note that it aucompletes the domain. However, keep typing (e.g. bcferries.com/curr...) - it should autocomplete into bcferries.com/current-conditions, but it doesn't.

Same thing happens for lots of other URLs - e.g. `reddit.com/r/vancouver`, etc.

On desktop, we autocomplete these cases as you'd expect - part by part going through the url path.

**Comment by MatthewTighe** [comment]
Looks like this was a [previously known issue](https://github.com/mozilla-mobile/android-components/issues/1279)
