### ISSUE TITLE
Refactor inactive tabs feature to rely on middleware

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#22551]
In https://github.com/mozilla-mobile/android-components/pull/11272 we have added tab partitions/groups to `BrowserState` which will make it easier to represent the state of tab groups, as opposed to inferring those groups on demand.

Inactive tabs can be represented as a tab partition/group as well.

We will need to add a `middleware` to Fenix that manages the corresponding tab group. The `middleware` will have to react to:
- `RestoreCompleteAction` to check the `lastAccess` timestamp after the tabs have been restored and add the corresponding tabs to an inactive group. We think it's good enough to do this after startup only i.e., a tab doesn't have to become inactive will the app is being used.
- `SelectTabAction` to remove a tab from the inactive group when it's selected again. Alternatively, we could also use `UpdateLastAccessAction` to achieve this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18708)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813709

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
