### ISSUE TITLE
FNX3-16178 ⁃ [Bug] When typing in the url bar, content disappears if fenix is put to background

### ISSUE THREAD

**Issue by ReekyMarko** [mozilla-mobile/fenix#2255]
Like the title says

**Steps to reproduce**

1. Type something in the url bar but don't press enter
1. Switch to another app and switch back 

**Expected behaviour** 
The text you typed should still be there

**Actual behaviour** 
The text you typed is now gone

**Comment by ekager** [comment]
Related: #1198

**Comment by colintheshots** [comment]
I moved save/restore to #2418. This is blocked on that, but we can possibly save and restore instance state directly without an architectural solution, if needed before MVP.

**Comment by ReekyMarko** [comment]
This seems to be fixed in the latest build

**Comment by ReekyMarko** [comment]
Why was this reopened? I can't reproduce it on the latest builds

**Comment by Amejia481** [comment]
Sorry about that @ReekyMarko  I think it was a mistake from automation
