### ISSUE TITLE
Add a widget for direct access to saved logins

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#22564]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

People who may not have been using Fenix as their browser on Android may have been using Lockwise to have access to their desktop Firefox saved logins. 

With the imminent demise of Lockwise, they will hopefully be installing Firefox to maintain access to their passwords. They still might not choose to use Firefox as their Android browser, so we've now added a bunch of extra taps to get from their homescreen to their list of saved passwords. 

This migration has the potential to drive these users to using a different password manager, which might eventually give them no reason to continue using Firefox on the desktop. 

Creating a "saved logins" widget would allow these users to have direct, one-tap access to their saved logins. Less friction for them, and maybe eventually these users will realize that Fenix is a good browser and eventually start using the rest of the browser. :) 

### How do you know that this problem exists today? Why is this important?

Comments on reddit like https://reddit.com/r/firefox/comments/r0kpke/lockwise_is_officially_dying/hltm1e3

### Who will benefit from it?

Users who want more direct access to their saved/synced passwords on Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18725)

**Comment by KWierso** [comment]
The two Lockwise usage patterns:
Tap a login field in any app > (optionally filter Lockwise results) >Tap suggested Lockwise login > Done

Open Lockwise app > interact with saved logins list

Currently with Firefox as the autofill app:
Tap a login field in any app > (optionally filter saved Firefox logins) > select saved Firefox login > Done

Open Firefox > Open the app menu > Scroll down and select Settings > Logins and Passwords > interact with saved logins list

It's that second usage pattern that's suddenly become much more tedious with the death of Lockwise.

**Comment by KWierso** [comment]
I guess another way might be to just add a top level "saved logins" item in the main Fenix menu, similar to desktop Firefox's "Passwords" entry. That would cut out two of the steps in reaching the list of logins, but might make the main menu excessively tall...

**Comment by bwat47** [comment]
A top level menu entry would be a nice improvement IMO.

It took me a few minutes to find where the saved passwords were in firefox on android, because it's un-intuitively stuffed under 'settings'

**Comment by boek** [comment]
Dup of #22677
