### ISSUE TITLE
[Bug]: Issue #19783 Closed Without Resolution

### ISSUE THREAD

**Issue by Siva981** [mozilla-mobile/fenix#22563]
### Steps to reproduce

Please refer Github issue #19783 

### Expected behaviour

The weird shapes and structures issue, which is explained in detail in issue #19783, should be resolved.

### Actual behaviour

The issue #19783 has been closed without any resolution. The related Bugzilla issue has also been closed. 

I created issue #19783 on Jun 3. It has been almost 6 months. The issue still occurs on my phone.

I have created this issue only because there has been no replies to my queries on issue #19783 since this October. Please reopen that issue and close this. Or, we can can follow-up further progress using this issue.

### Device name

Swipe Elite Plus (Country: India) 

### Android version

Android 5.0.2

### Firefox release type

Firefox

### Firefox version

94.1.2 (Build #2015844587) AC: 94.0.12, e5eb726f81 GV: 94.0-20211028161635 AS: 85.4.0

**Comment by Mugurell** [comment]
I see https://bugzilla.mozilla.org/show_bug.cgi?id=1714227 has been closed as resolved. 
There was a patch merged that should mitigate the problem.

Does the issue reproduces exactly the same as reported initially, do you see any improvement?

**Comment by Siva981** [comment]
Thank you for responding. 

There have been no improvements at all. It is still the same, as far as the odd shapes & structures issue goes, which I had reported as part of issue #19783.

Firefox For Android version 89.1.1 actually introduced 3 different type of issues on my Android 5.0.2 device. I had reported them as part of 3 separate issues: 

#19782
#19783 
#19787 

Out of these 3, #19782 was resolved successfully. The other 2 are yet to be resolved.

As far as the issue with #19783 goes, I was informed (please see the comments section of #19783), that whatever solution they brought forth to solve my issue, further created unrelated rendering problems. So they had to pull the code (that solved my issue) from going live. I was also informed, that a new solution was being worked on at the time. 

Furthermore, even I got to test the resolution that was supposed to solve my issue (by installing Nightly, and also by installing a few test builds for which I was provided download links). However, my test results showed that the solution slowed down my Firefox almost to the point of non-scrollable (up/right/bottom/top). 

I had documented all my test results (with screenshots, wherever necessary) in issue #19783.

**Comment by delia-pop** [comment]
Hello @Siva981, 
Thank you for your report!

I requested your input on ticket #19782. I will close this ticket for now, as both #19783 and #22563 are mentioned on #19782, and you can follow-up the updates there.
