### ISSUE TITLE
Searching for saved logins from another app shouldn't add spaces after periods

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#22562]
I have my keyboard set to automatically put a space after a period. 

This is good for most text inputs. I can type "google" followed by a period, and the space gets added as desired. ("google. ") 

When I type into Firefox's address bar, it knows not to do that, because it's much more likely that I would be typing a domain into the field. If I type "google" followed by a period, it doesn't add the space. ("google.") 

But with Firefox set as my autofill app for other apps on my phone, if I search Firefox for a saved password, it acts more like a plain text input rather than the address bar. (Search for "google" with a period adds the space, which causes no matches, because the passwords are saved to "google.com" not "google. com")

**Comment by KWierso** [comment]
This doesn't match the behavior of Lockwise, which had the more addressbar-esque behavior. With Lockwise being end-of-lifed soon, this might be a bigger issue for more people.

**Comment by SoftVision-LorandJanos** [comment]
Hi @KWierso! Thanks for your report!
I activated the auto spacing feature and checked on the address bar, and around the saved login feature, but as far as I could observe the space wasn't added where there shouldn't be.
If you have some additional settings that may have lead to adding space where it shouldn't, please share.
Making a video of this issue may help also. Thank you!
Tested on the latest builds:
- Release (94.1.2).
- Beta (95.0.0beta5).
- Nightly 96.0a1 (2021-11-24)

Also checked on Chrome where the behavior is also as expected on my side.
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by KWierso** [comment]
Here's a video of my interaction https://www.youtube.com/watch?v=IMuQ85sScos

I'm using Swiftkey keyboard, if that makes a difference.
