### ISSUE TITLE
FNX-5548 ⁃ Support for custom searches

### ISSUE THREAD

**Issue by bjo81** [mozilla-mobile/fenix#2257]
### Why
Users would like to use e.g. searx instances like they did with firefox.

### What
Atm Fenix has no "add search engine" icon. Adding https://searxinstance/opensearch.xml works somehow, as Fenix states "already exists" when trying to add it again, but it does not appear in the search engines overview.

**Comment by maverick74** [comment]
duplicate of #1437  ?

**Comment by kbrosnan** [comment]
Yes. Thank you.
