### ISSUE TITLE
[Bug]: Grey area appears at the bottom of the screen when popup is opened and address bar is hidden

### ISSUE THREAD

**Issue by VolhaMalevich** [mozilla-mobile/fenix#22586]
### Steps to reproduce

This issue is still actual: https://github.com/mozilla-mobile/fenix/issues/18004.
1. Open Mozilla Firefox (or Mozilla Firefox Nightly) for Android
2. Go to any site where popups are opened. For example https://www.oracle.com/java/ or https://www.jetbrains.com/ru-ru/idea/
3. Scroll down untill status bar is hidden
4. Open popup

Firefox Nightly information:
![Firefox version](https://user-images.githubusercontent.com/83364258/143412808-be55a3b2-6025-4959-8ed2-e6dac63b3930.jpg)

### Expected behaviour

Popup is fully visible. No empty extra space are shown at the bottom of the page.

### Actual behaviour

Grey block appears at the bottom of the page and hides part of content
https://www.jetbrains.com/ru-ru/idea/:
https://user-images.githubusercontent.com/83364258/143412161-7b99d39c-5809-4a5c-b2b1-a85dce56bc73.mp4
https://www.oracle.com/java/:
https://user-images.githubusercontent.com/83364258/143412229-4717b485-4c8b-4ae7-be53-5eec5340a429.mp4

### Device name

Xiaomi MI A1

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

**Comment by Mugurell** [comment]
Thank you for the report!
This is indeed still a problematic edgecase that is to be investigated in https://bugzilla.mozilla.org/show_bug.cgi?id=1694607 
Will reopen which has more context and close this as a dupe.
