### ISSUE TITLE
[Bug]: Status bar is overlapped by website details in Landscape mode 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#22589]
### Steps to reproduce

1. Set the Toolbar to "Top" from Settings > Customize > Toolbar.
2. Open a webpage. 
2. Rotate the device in Landscape mode.
3. Tap the Lock icon. 
4. Observe the status bar.

### Expected behaviour

In Landscape mode, the menu opened after tapping the lock icon is displayed under the status bar.

### Actual behaviour

After tapping the lock icon in Landscape mode, the webpage name and icon overlaps the status bar.

### Device name

LG G7 fit

### Android version

Android 8.1.0

### Firefox release type

Firefox Beta

### Firefox version

95.0.0-beta.6 ( Build 2015847755)

### Additional information

The issue was not reproduced on other devices.

![Screenshot (Nov 25, 2021 13 57 56)](https://user-images.githubusercontent.com/89388888/143440799-a0f6dc96-ae32-4ca9-81e2-d4e2b9193e12.png)

https://user-images.githubusercontent.com/89388888/143440775-a78691db-4210-472a-96eb-056e8e884202.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18747)

**Comment by delia-pop** [comment]
This is still reproducible on 96.0.0-beta.2 with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
This is still reproducible on 96.0.0-beta.3 with LG G7 fit (Android 8.1.0). However, the issue is not encountered on other devices.

**Comment by mcarare** [comment]
For QA: Can this be tested on other devices with Android 8? I haven't been able to reproduce it on any device/ emulator. Thank you!

**Comment by delia-pop** [comment]
Tested with the following devices:
- LG G7 fit (Android 8.1.0): the issue is no longer present on the Nightly 12/20 build (still reproducible on 96.0.0-beta.3 build).

- Huawei P9 Lite (Android 8): the issue could not be reproduced on the Nightly 12/20 or 96.0.0-beta.3 builds.

 LG G7 fit (Android 8.1.0) with  Nightly 12/20:

![1639994370590](https://user-images.githubusercontent.com/89388888/146751570-0fe13905-824d-4ae9-be33-93248ba45a13.JPEG)

**Comment by delia-pop** [comment]
This is still reproducible on 96.0.0-beta.4 with LG G7 fit (Android 8.1.0).

**Comment by rocketsroger** [comment]
Confirmed on Nightly this is not reproducible.  This should be fixed in Beta on the next cut.  Thanks

**Comment by jonalmeida** [comment]
Closing as fixed as per the last comment.
