### ISSUE TITLE
Track APK size on perfherder

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22580]
Let's use perfherder to track our APK size(s) in order to see the changes over time and identify regressions. Using perfherder has the advantage that it will be linked to individual commits / pushes, making it easier to identify the cause.

**Comment by kbrosnan** [comment]
https://treeherder.mozilla.org/perfherder/graphs?highlightAlerts=1&highlightChangelogData=1&highlightCommonAlerts=0&series=fenix,4063376,1,2&series=fenix,4063381,1,2
