### ISSUE TITLE
FNX-5549 ⁃ [Bug] The QAB is partially visible all the time

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2259]
## Steps to reproduce
1. Open a web page.
1. Observe the quick action bar.
    1. Expected behavior
Only the bar handle is visible after the first-time animation.
    1. Actual behavior
Half the bar is still visible all the time, doesn't fully dock behind the url bar.
    1. Device information

* Android device: any
* Fenix version: 5/3

**Comment by cadeyrn** [comment]
Sounds like #2245.

**Comment by sv-ohorvath** [comment]
> Sounds like #2245.

That's true, thank you!
