### ISSUE TITLE
FNX-5550 ⁃ [Meta] Search Provider

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#226]
### Why/User Benefit/User Problem
This Epic is about two things:

1. Picking the right default search provider for a new install of Fenix, based on the user's country or locale
1. The ability to change the default search provider in the Search Settings

### Notes
Search is very important to get right because it is directly related to revenue. It is essential that we use the correct default search provider for a new install of Fenix.

In a lot of places in this epic and stories we say _based on the user's country or locale_. However, it is not entirely clear how the default search provider or selection of available search providers should be determined. In some products we use the device's country, inother's the locale. In Desktop we talk to a remote service that tells us the right choices. We need to understand how we should address this in Fenix.

### Dependencies
* A lot of the search provider selection logic is abstracted in Android-Components.
* The search team knows about the most up to date list of search providers

### Stakeholders
Because search is essential to get right, this Epic may need additional sign off from the Search Team.

### What / Requirements
The requirements are listed in the individual user stories linked to this epic.

### Acceptance Criteria (how do I know when I’m done?)
The acceptance criteria are listed in the individual user stories linked to this epic.

There is also this [Search - Release Testing Requirements](https://docs.google.com/document/d/1N3I8uWPKxudN8uIbeI2-vnP1qQdO1OolZNVypleV9DQ/edit#) document that should give some strong guidance on testing search specifics.

**Comment by sblatz** [comment]
We should include making a [search engine settings page](https://github.com/mozilla-mobile/fenix/issues/226) as part of this ticket.

**Comment by lime124** [comment]
I think this is covered by the work @brampitoyo did in the UX settings ticket #187 .

Is there something more needed for this @bbinto , @vesta0 ?
