### ISSUE TITLE
[Bug]:  sometime unable to scroll pages 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22600]
### Steps to reproduce

Search anything in google
Click google search result
Sometime the target page is fully scrollable some time unable to scroll kind of getting hanged
Reloading the target page is fixing it

Attaching a video 

I feel this is for webpages where automatic google sign in is happening amp pages I guess

### Expected behaviour

Target page should load properly and able to login

### Actual behaviour

Page getting hanged.unable to scroll
Need to reload page 

### Device name

Asus Rog phone 3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

https://user-images.githubusercontent.com/58127841/143547162-49b1e0b8-19fc-4871-b38a-077fab85b365.mp4

**Comment by LaviniaL99** [comment]
Hello @sheikh-azharuddin 

Thanks for your report!
I tested the above flow on the latest Nightly 98.0a1 (2022-01-20) and i was not able to reproduce the issue - I'm able to scroll on different pages (also verified on the same site as per your video).

**Devices used:**
- Samsung S10E -> Android 10
- Samsung Galaxy A32 5G -> Android 11

Can you verify if you are still able to reproduce the issue on the latest Nightly?

**Comment by sheikh-azharuddin** [comment]
Seems fixed
