### ISSUE TITLE
Special characters not showing correctly

### ISSUE THREAD

**Issue by joaojotta** [mozilla-mobile/fenix#22615]
## Site with issue and any steps to reproduce
https://metenamesa.pt/wip.html

### Expected behavior
I'm using a custom font (Hack) and the browser isn't rendering the characters (`●◐○` or `&#9679; &#9680; &#9675;`) are not show the same size.

### Actual behavior
`&#9680;` is much bigger than `&#9679;` and `&#9675;`.

### Does toggling Tracking Protection fix the issue? 
No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No. Works as it should.
Al the desktop browsers display the characters as they should as well. At least the top ones, Firefox (both Firefox and Firefox Developer Edition) included.

### Device information
* Android device: Andorid 11, Redmi Note 9 Pro with Lineage - same as stock Huawei my friend tried it on
* Fenix version: 94.1.2

Hope this is the right place to report this.
I have also checked the font in every possible way and the characters ARE the same size.

**Comment by kbrosnan** [comment]
I don't believe that it is expected that the characters are the same size. For example in Consolas the characters are not the same size. Either way this is a Gecko issues.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1743470

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
