### ISSUE TITLE
FNX-5553 ⁃ [Bug] After updating I lost my dark theme

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2262]
## Steps to reproduce
* Updated to the latest Fenix build. I previously had dark theme set and it is set on my device in the Android Settings as well.

### Expected behavior
* Fenix would launch with the dark theme

### Actual behavior
* Fenix launched without the dark theme. I had to toggle back and forth several times in the Fenix settings to get the browser to show the dark theme.

### Device information
* Android device: Pixel 3
* Fenix version: 1.01.1918 (Build #11231225)

**Comment by ekager** [comment]
I had to change the way preferences were stored in #2215 and I changed more about the theme default values in #2235, so probably a combination of those messed up your stored preference. I'm less concerned about this if it's only happening on Nightly builds where users had already changed preferences than on fresh builds. Please update us if the new preference doesn't stick.

**Comment by vesta0** [comment]
@mozillamarcia please file a new bug if this issue comes back.
