### ISSUE TITLE
javascript DatePickers not working on Firefox mobile

### ISSUE THREAD

**Issue by WiertD** [mozilla-mobile/fenix#22620]
https://www.jqueryscript.net/blog/best-date-time-picker.html
All pickers on this page do not work in firefox 94.1.2 on Android 11 (xiaomi).
On Chrome and Opera it works fine.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18764)

**Comment by cadeyrn** [comment]
I only tested the first three datepickers, but all of these work for me in Firefox 94 for Android. Did you test without add-ons?

**Comment by kbrosnan** [comment]
Which specific ones are you having problems with?

**Comment by boek** [comment]
This has not revived any duplicates or other interactions since it was filed. We will not be moving this request to Bugzilla. Feel free to re-open if you're still able to reproduce.
