### ISSUE TITLE
[Bug]: Not giving copy to clipboard option on share

### ISSUE THREAD

**Issue by Breigner01** [mozilla-mobile/fenix#22626]
### Steps to reproduce

I observed this on Flickr particularly.
1. Go to an album on Flickr (let's say https://www.flickr.com/photos/breigner01/albums/72157716254558673)
2. Click on the share button

### Expected behaviour

It should prompt me with all the share options as well as the `Copy to Clipboard` option

### Actual behaviour

It displays all the options except the `Copy to Clipboard` one.

### Device name

OnePlus 9 Pro

### Android version

Oxygen OS 11.2.9.9.LE15BA

### Firefox release type

Firefox

### Firefox version

94.1.2 (Build: #2015844587)

**Comment by eliserichards** [comment]
Just to confirm, the `copy to clipboard` option **is available** on other sites?

**Comment by Breigner01** [comment]
So,
I kinda forgot to come back to this (my bad).
Since then I switched to android 12 and I don't have the issue anymore (I don't know if it's still present on android 11 and I don't have a way to test this).
I also checked real quick and I also have the copy to clipboard option on youtube.
So it seems fixed under android 12.
