### ISSUE TITLE
"Copy URL" button in the Share menu

### ISSUE THREAD

**Issue by redudant-overflowing** [mozilla-mobile/fenix#22632]
### What is the user problem or growth opportunity you want to see solved?
There is a way to copy the URL in a fast way when the address bar is not opened, but this isn't too obvious. 
<img src="https://user-images.githubusercontent.com/93951203/143975521-c5b090e6-db4a-404e-a6bb-5428eff23269.gif" width="400"/>

### How do you know that this problem exists today? Why is this important?
I just found out today that it was possible to copy the URL quicker in the way I described earlier. I think this isn't too clear to discover and the "copy URL" button in the Share menu would help people that aren't aware of this.

### Who will benefit from it?
Anyone. I don't know exactly how to answer this question. The problem is that the quick copying feature is too hidden.

**Comment by lf-** [comment]
This is more problematic outside the share button in the menu: another way that the share menu appears is when invoked by JavaScript `navigator.share`, in which case there is no way to copy to the clipboard at all.

**Comment by Remu-rin** [comment]
Duplicate of #14313. Should be fixed in version 100.
