### ISSUE TITLE
Prevent this site from opening a pop-up window choice does not persist

### ISSUE THREAD

**Issue by johngeoffrey** [mozilla-mobile/fenix#22641]
### Steps to reproduce

1. Open a site with a link that opens a pop up
2. Click the link
3. See notification about preventing site from opening a pop-up window
4. Click allow
5. Close pop-up (new tab)
6. Click the link on original site
7. Notification for pop-up window is shown again

### Expected behaviour

Pop-up notification only appears once and choice for site is persisted

### Actual behaviour

Pop-up notification appears every time regardless of how many time option is allowed

### Device name

Sony Xperia 5 ii

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18778)

**Comment by LaurentiuApahideanSV** [comment]
@johngeoffrey Could you share the site or sites where you encountered this problem? A short video illustrating the issue would also help in trying to reproduce it.

**Comment by smac89** [comment]
Here is one such place it fails:
https://github.com/firebase/firebase-js-sdk/issues/1003#issuecomment-1077894894

Two things to point out in the screenshot:
1. firebase already got a notice that the popup was blocked before the user even had a chance to click "Allow"
2. Even after clicking "Allow", the next time we attempt to login with firebase popup, the same dialog is once again displayed

The fix I found to get around this issue (i.e. the popup being blocked) is described in that issue comment.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811617

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
