### ISSUE TITLE
ANR after sharing image from https://youcantdownloadthisimage.online/

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#22644]
### Steps to reproduce

1. Open https://youcantdownloadthisimage.online/
2. Long-press the image
3. Select "Share image"

### Expected behaviour

The browser should not block when sharing fails.

### Actual behaviour

The OS shows an ANR warning for the browser.

### Device name

Sony Xperia Z2

### Android version

Android 6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 (Build #2015848873), 9fa9ae337+ AC: 96.0.20211130143618, 395aa21e64 GV: 96.0a1-20211130093553 AS: 86.2.0, 2021-12-01T05:13:00.119862

### Additional information

This website does not close the connection after the image has been sent, see the description below the image when clicking "The answer".

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18781)

**Comment by LaviniaL99** [comment]
Hello @hwinnemoe 
Thanks for your report!
I tested the above issue on the latest Nightly build 97.0a1(Build #2015856555) and I was able to reproduce the issue.

**Devices used:**

Samsung S10E -> Android 10
Pixel 6 -> Android 12

![1641822504251](https://user-images.githubusercontent.com/96047134/148777423-6fa104e9-c70f-4c43-ab4d-39997a2722b8.JPEG)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809783

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
The original website has moved to https://youcantdownloadthisimage.com/.
