### ISSUE TITLE
UI tests fail on Android 11 with junit.framework.AssertionFailedError: Failed to grant permissions, see logcat for details

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22649]
### Steps to reproduce

1. With a device running Android 11 (I used a Pixel 2)...
2. Run `./gradlew connectedDebugAndroidTest`

### Expected behaviour

Tests pass

### Actual behaviour

All tests fail with something like:

```
org.mozilla.fenix.screenshots.DefaultHomeScreenTest > privateBrowsingTest[Pixel 2 - 11] FAILED 
        junit.framework.AssertionFailedError: Failed to grant permissions, see logcat for details
        at junit.framework.Assert.fail(Assert.java:50)
```

The logcat says: 
```
12-01 09:34:07.836 19782 19904 E GrantPermissionCallable: Permission: android.permission.WRITE_EXTERNAL_STORAGE cannot be granted!
```

It sounds like this may be related to [the storage changes in Android 11](https://developer.android.com/about/versions/11/privacy/storage).

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

up/main: 9fa9ae3375593e9f7bfd49e4449e5012b0c83d4f

### Additional information

I don't think we experienced this in a new Android project so it's probably something specific to our Gradle build configuration.

This issue may have blocked our progress on successfully integrating Jetpack Benchmark. The follow-up is get it working is https://github.com/mozilla-mobile/fenix/issues/22480

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18783)

**Comment by mcomella** [comment]
MarcLeclair suggested updating the version of androidx.test or whatever should fix this but `ActivityTestRule` will be deprecated (need to migrate to `ActivityScenario`).

**Comment by AaronMT** [comment]
Thanks for filing, yeah adopting `ActivityScenario` across the custom helper test rules is the first hurdle to running on API30+ and then adopting the new permission grant style 👍🏼 
(just linking this in https://github.com/mozilla-mobile/mobile-test-eng/issues/602)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807305

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
