### ISSUE TITLE
Bottom padding and scrolling if the input element is very low

### ISSUE THREAD

**Issue by serg-co** [mozilla-mobile/fenix#22643]
### Steps to reproduce

https://coffee-cms.com/ff_mob_bug.html

![InkedScreenshot_20211201-134255_Firefox](https://user-images.githubusercontent.com/77325397/144221949-12782cd1-c9b2-4a20-bf7b-d87c065ed4a7.jpg)

### Expected behaviour

No scroll and bottom padding

### Actual behaviour

Scroll and bottom padding

### Android version

11

### Firefox release type

Firefox

### Firefox version

94.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18780)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 2022-02-11.
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813725

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
