### ISSUE TITLE
Firefox does not load any site for few seconds after switching back and forth between apps

### ISSUE THREAD

**Issue by Shaurya-Kalia** [mozilla-mobile/fenix#22642]
Steps:
1. Open firefox
2. Go to home or switch to another app without closing firefox
3. Reopen firefox
4. Try opening any site
5. There is 10-15 seconds delay in which nothing loads. After that everything is normal.

Could not replicate it in any other browser.

Using firefox nightly 96

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18779)

**Comment by lucy** [comment]
I've been hitting this for a long time now and have to cancel and reload the page for it to get unstuck. Still reproducing on current nightly as of today.

**Comment by vehosah** [comment]
Three years and no updates

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813710

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
