### ISSUE TITLE
[Bug]: Nit - tab tray still has its intermediate open position accessible only with a quick flick

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#22659]
### Steps to reproduce

Open the tab tray fully, it covers ~90% of the screen height
flick the grab handle slightly downwards
-> the tab tray goes to its partially closed position covering ~70% of the screen height
there is no other way to get the intermediate position, eg a drag to the right place does not work.

This is a nit, IIRC the intermediate position was taken away. I don't think it serves much purpose to have it appearing with this particular flick.

Of course, the intermediate position is useful for reaching the top with a thumb, perhaps there is some consistent approach involving the intermediate position?

### Expected behaviour

Intermediate position should not exist or should be always accessible

### Actual behaviour

Intermediate position is only accessible with a slight flick

### Device name

Galaxy M32

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

#2015848875  2021-12-01T05:13:00

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18789)

**Comment by amocirean** [comment]
Hello @Cheap-Skate , this is more a feature request than a bug. 
Based on the following situation, this ticket will be closed.
