### ISSUE TITLE
Homepage is scrolled to the bottom if onboarding was scrolled to the bottom

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#22653]
### Steps to reproduce

1. Have a fresh build (mine is Dec 1 build from `main`)
2. On the onboarding screen, scroll all the way to the bottom
3. Open the three-dot menu. Click "Sign in to sync"
4. Click the back button

### Expected behaviour

The user sees the top of the homescreen (so we can see the name of the browser and top sites)

### Actual behaviour

The top of the homescreen isn't shown (you can't see "Firefox Preview"/the browser name) and you have to scroll up to see the top.

This isn't necessarily _broken_... but it does speak to the larger issues of which sections are rendered first and the relationship between onboarding content and home content. Scrolling onboarding should have no impact on what you see on the home screen once you navigate away.

https://user-images.githubusercontent.com/43795363/144327156-fb6d94ac-ca6b-4836-8742-19195bc0a109.mov

### Device name

Pixel 3

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

debug build

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18785)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809830

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
