### ISSUE TITLE
[Bug]: page title in tabs tray gets replaced by url when forward/back navigating

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#22667]
### Steps to reproduce

Navigate to https://www.mozilla.org/en-GB/
Open the tabs tray
The tab has the page title... "Internet for people not profit" or whatever
Tap any link on the page & wait for it to load
Tap Back button 
Open the tabs tray
The tab has the url instead of the title **<--- incorrect behavior**
 

### Expected behaviour

The tab should keep the page title

### Actual behaviour

The tab's title gets replaced with its url

### Device name

Galaxy M32

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

#2015848875

**Comment by SoftVision-LorandJanos** [comment]
Hi @Cheap-Skate! Thanks for the report!
I managed to reproduce your issue on the latest Nightly, but it doesn't happen with any link accessed, I tried a "Visit the Mozilla Foundation" link in the middle of the page, and when turned back from that, the page title was correct in the tabs tray. The links from the bottom of the page however have the effect described by you.
Tested on the latest Nightly (2021-12-03).
Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by Cheap-Skate** [comment]
The "visit the Mozilla Foundation" link **does** exhibit the incorrect behavior on my phone. So it's more complicated than we thought!

Thanks for confirming.

**Comment by marcel263** [comment]
#20546 in the similar case, issue is javascript related

**Comment by SoftVision-LorandJanos** [comment]
Thank you for pointing this out @marcel263!
As the mentioned issue should cover the one described here, I will close this one as duplicate.
