### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by darmstadt40** [mozilla-mobile/fenix#22662]
After finishing a video in full screen mode on Android, the screen does not switch off and remains lit.  Must be fixed.  The key lock must be activated automatically when the video is over.

Google Pixel 3 XL, Firmware and akp newest version.

**Comment by LaurentiuApahideanSV** [comment]
This is the intended behavior. After a full screen video is finished Firefox will return to the default view and not lock the device automatically.

**Comment by darmstadt40** [comment]
The device then stays in full screen mode for hours. This is intended?

Laurentiu Apahidean ***@***.***> schrieb am Di., 7. Dez.
2021, 14:11:

**Comment by LaurentiuApahideanSV** [comment]
@darmstadt40 After the full screen video is finished and Firefox returns to the default view the device's Display Sleep or Auto screen off feature will automatically turn of the screen and lock the device.

**Comment by darmstadt40** [comment]
In my case not.

Laurentiu Apahidean ***@***.***> schrieb am Di., 7. Dez.
2021, 15:41:
