### ISSUE TITLE
[Bug]: Long file names are truncated in download notifications

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22663]
### Steps to reproduce

1. Find an image with a long name e.g. [https://en.wikipedia.org/wiki/Main_Page#/media/File:HMS_Seringapatam_at_anchor_in_Valetta_Harbour_-_Anton_Schranz.jpg](url)
2. Save the image
3. Observe the notification after download is finished

### Expected behaviour

The name is fully visible

### Actual behaviour

The name is truncated
![262621408_944622912817064_9094628654769730354_n](https://user-images.githubusercontent.com/89511597/144436907-52df7523-3863-4362-bbd8-c1fdb87f1589.jpg)

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

95.1.0 2021-11-30

### Additional information

Not sure if this occurs in landscape as the name was not long enough. Could not reproduce on Nightly 96.0a1 2021-12-02

**Comment by mariansima** [comment]
@Amejia481 In the screenshot attached the word "Anton" is missing. In landscape you can see the full name
![262621128_235061608698794_690530857782998529_n](https://user-images.githubusercontent.com/89511597/144444698-e9fe3634-e41d-4903-adc7-4bd856297cfc.jpg)

**Comment by Amejia481** [comment]
Thanks for the clarification!

**Comment by surajeet310** [comment]
Can I take up this bug ?

**Comment by Alexandru2909** [comment]
@mariansima I can't reproduce this issue on Nightly, I tried on multiple devices with different downloads (including the one sent by you) but the problem seems fixed. Can you confirm this is still an issue?

**Comment by Alexandru2909** [comment]
The issue should not reproduce on Release now, can QA check this?

**Comment by SoftVision-LorandJanos** [comment]
Verified with the same example.
Fixed on the latest Nightly 98.0a1 (2022-02-08).
Closing the ticket as fixed.
![Screenshot_2022-02-08-09-04-18-36_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/48829350/152948907-64da4aab-0e16-46d0-9f8c-ec52e899aa57.jpg)
