### ISSUE TITLE
Make it easier to access top of tabs tray with thumb

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#22661]
### What is the user problem or growth opportunity you want to see solved?
Tabs tray:-
On a tall screen can't reach topmost tabs or tab counter / private / synced tabs row. 
IMHO quite important to be able to do so especially with Search Groups enabled where useful search stuff is at top of tabs list & currently unreachable by thumb

Somehow make it easier to reach them. The intermediate tab tray open position had that but had some other difficulties & can't currently be accessed using thumb. 

eg
- Samsung native apps (Email, Messages etc) have a nice drag down where can pull down with a thumb until topmost content is in middle of screen (could just add a couple of blank rows above topmost tab), or
- once the tabs tray has moved to its end stop, a further drag down closes the tab tray to its intermediate position, or
- something else???

### How do you know that this problem exists today? Why is this important?
I can't reach topmost tabs with my thumb and I have big hands. This is particularly an issue when using Search Groups because the useful search results are effectively out of reach of one hand. One handed use is a big part of the Fenix story.

### Who will benefit from it?
Me! And no doubt millions of others ;)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18792)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813712

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
