### ISSUE TITLE
nha.chotot.com - Image content doesn't load

### ISSUE THREAD

**Issue by mrxyzl** [mozilla-mobile/fenix#22674]
URL: https://nha.chotot.com/mua-ban-nha-dat-quan-phu-nhuan-tp-ho-chi-minh/88663312.htm

Browser / Version: Firefox 96.0a1 (Build #2015849163)
Operating System: Android 12, One UI 4.0
Tested Another Browser: Yes Edge, Chrome, Vivaldi

Problem type: Image is not usable
Description: Image not loading correctly
Steps to Reproduce:
Site is loaded with correct layout but image doesnt show up
(i send you a specific link but its for every listing in that website)
Browser is freshly  installed with Enhance tracking disable

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18798)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on the latest Firefox Preview Nightly 2021-12-06.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by boek** [comment]
The link provided in the ticket no longer works. I'm also not able to reproduce while navigating around nhatot. Please re-open in Bugzilla if you continue to notice this behavior.
