### ISSUE TITLE
Add a "Logins & passwords" home screen shortcut

### ISSUE THREAD

**Issue by Booligoosh** [mozilla-mobile/fenix#22677]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
With the sunsetting of the Lockwise Android app, there's no way to see my passwords in 1-2 taps. With Lockwise, to get to my passwords list, all I had to do was:
1. Open the Lockwise app
2. Tap the unlock button
3. Enter fingerprint

With the Firefox app as of now, I have to:
1. Open the Firefox app
2. Tap the "..." next to the URL bar
3. Tap "Settings"
4. Tap "Logins & passwords"
5. Tap "Saved logins"
6. Enter fingerprint

This could be solved by adding an Android homescreen shortcut, similar to the existing ones for "new tab" and "new private tab", called "logins & passwords", that either takes the user to the logins & passwords screen or straight to the "saved logins" screen. This would also enable the user to add that shortcut to their homescreen as a separate icon from the main Firefox app, thus 'replacing' the Lockwise app.

The reason that I'd want to see my list of passwords is that sometimes I have to type one on someone else's device or a public computer, and the easiest way is just to get out my phone, show the password, and then type it into the computer manually.

### How do you know that this problem exists today? Why is this important?
As above, with the sunsetting of the Lockwise app, accessing my passwords list goes from 3 simple steps to 6 rather finnicky steps

### Who will benefit from it?
Ex-Lockwise app users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18800)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812434

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
