### ISSUE TITLE
[Bug]: History has wrong order 

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#22671]
### Steps to reproduce

Go to history

### Expected behaviour

Sections are ordered from newest to oldest

### Actual behaviour

Oldest section shows up first, followed today and last 7 days
![Screenshot (Dec 2, 2021 7 12 07 PM)](https://user-images.githubusercontent.com/353960/144500224-422a9794-5794-45f7-8a42-ba8142be3e47.png)
 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

96

**Comment by rocketsroger** [comment]
To reproduce, move time forward by 5 days or so.  Open some tabs and closed them to create the history.  Move time back to current time.  Anything that's "in the future" will show up as older.

**Comment by topotropic** [comment]
oh right, I messed around with my system time... maybe not a very common issue

**Comment by rocketsroger** [comment]
> oh right, I messed around with my system time... maybe not a very common issue

Agreed, but while investigating this I see some obvious problem with the current algorithm.  I'll fix this issue while improve the current algorithm as well. 👍
