### ISSUE TITLE
FNX-5557 ⁃ Telemetry for Reader View

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#2267]
#### Description & Product Manager / Data Scientist User Story
* As a product owner, I want to know how often users access the reader mode, so I can assess whether this feature is discoverable and useful and how it can be improved. 

#### Hypothesis
We believe this feature is useful to users, and successful when

* % of users switching to reader mode increases

#### What questions will you answer with this data?
* How often users switch to reader mode?
* How often users switch to reader mode, on sites where reader mode is available?
* How often users tap on the Appearance icon to change the font, etc?

#### What probes
* Reader mode available
* Tap on reader mode icon
* Tap on Appearance icon

### Acceptance Criteria
* Event pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by AndiAJ** [comment]
Hi, the "Tap on Appearance icon" event doesn't seem to be generated on the latest Nightly Build #190724 from 24/7.

<details>
    <summary>Logcat & Glean dashboard</summary>

[Logcat](https://github.com/mozilla-mobile/fenix/files/3427028/R2.txt)
• Ping 6b4fe73c-789c-4dac-92c7-65194fc8649c - Tap Reader view ✅
• Ping 6deb2726-928f-4584-8e07-4af8efc26cfc - Tap on Appearance ❌
• Ping 86472ba7-b45f-4e10-b2e3-3b862b280a23 - Tap Close Reader view ✅

[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-240701)



</details>

@boek & @sblatz -  Shouldn't the name be more suggestive? I'm asking because it looks like in both opening and closing the Reader view the name is "read_tapped"

**Comment by AndiAJ** [comment]
Hi, I've retested this on **RC 1.2-rc2** using a Google Pixel 3a (Android 9) and it seems that the tap on the "Reader Mode" icon event doesn't get generated.

<details>
    <summary>Logcat  & Glean dashboard</summary>

• Ping 2287315b-10de-41d2-bdf3-be8077cef85b - Tap Reader view ❌
• Ping 7f30fe45-cddc-40b9-8827-38d40492052d- Tap on Appearance ✅ 
• Ping c022e796-230b-44be-addc-5130a99e6caa - Tap Close Reader view ❓

[Logcat](https://github.com/mozilla-mobile/fenix/files/3461274/ReaderMode.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-020802)
</details>

@sblatz & @boek -Not sure if the "Close Reader mode" is generate properly.
Wouldn't it be better to implement it as the "Appearance" ?

E.g.
 {
          "timestamp": 2530,
          "category": "reader_mode",
          "name": "close"
        },

**Comment by sblatz** [comment]
> • Ping 2287315b-10de-41d2-bdf3-be8077cef85b - Tap Reader view ❌

@AndiAJ this ping was intentionally removed. It was redundant as we added the "reader mode opened" ping

> • Ping c022e796-230b-44be-addc-5130a99e6caa - Tap Close Reader view ❓

This ping is also being generated properly. It is sent when the whole reader mode is closed, not when the "appearance" settings are closed.

**Comment by sblatz** [comment]
Going to close this as those pings are working as expected. Please re-open if you find any other issues!
