### ISSUE TITLE
FNX-5558 ⁃ [Bug] "Share tab" pop-up menu for last tab tile is tiny and empty

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#2268]
## Steps to reproduce
1. Open at least three tabs in Fenix.
1. Go to the Fenix home screen.
1. Tap the "..." button of the first tab tile on screen.
1. See the "Share tab" pop-up menu.
1. Tap the "..." button of the bottom tab tile visible on screen.

### Expected behavior
A "Share tab" pop-up menu should open.

### Actual behavior
An tiny, empty pop-up menu is opened and you must scroll the tiny pop-up to see the "Share tab" menu item.

A similar issue for the bookmarks menu: https://github.com/mozilla-mobile/fenix/issues/2162

### Device information
* Android device: Moto G5 Plus
* Fenix version: 5/3

**Comment by vesta0** [comment]
@cpeterso I don't know how to reproduce this, can you please try again?

**Comment by cpeterso** [comment]
I'm closing this bug because the Fenix home screen's design has changed. Tap the tab tiles no longer have "..." buttons.
