### ISSUE TITLE
Some videos in PiP player have a black bar on top

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#22680]
# Issue

Sometimes there's a black bar above a video in the PiP player. Note that it doesn't happen on all videos (might be an aspect ratio-related issue?). It happens both in Nightly and release.

## Screenshot
![Screenshot_20211203_121349.jpg](https://user-images.githubusercontent.com/20287690/144594456-eb5080e5-d94b-4448-99d6-9f3434946c04.jpg)

# Steps to reproduce

1. Open this YouTube video: https://m.youtube.com/watch?v=AgibZPCkreQ

2. Play the video and enter full-screen mode.

3. Go to home screen to enter picture-in-picture mode.

## Expected result

The video fills the whole PiP window.

## Actual result

There's a black bar above the video in the PiP window.

# Device info

Huawei Mate 20 lite running Android 10 (EMUI 10.0)

# Firefox version

## Nightly

96.0a1 (Build #2015849163), 0ac7bc80a+
AC: 96.0.20211130143618, 395aa21e64
GV: 96.0a1-20211130093553
AS: 86.2.0

2021-12-02T17:08:05.316839

## Release

94.1.2 (Build #2015844587)
AC: 94.0.12, e5eb726f81
GV: 94.0-20211028161635
AS: 85.4.0

2021-11-08T21:26:04.605951

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18803)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on the latest Firefox Preview Nightly 2021-12-06 and managed to reproduce it. The issue might be related to https://github.com/mozilla-mobile/fenix/issues/8252.
### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)

**Comment by LaviniaL99** [comment]
The issue is still reproducing on the latest Nightly build (99.0a1 Build#2015865003) and latest RC build 97.2.0.

**Device used:**
- Samsung S10E-> Android 10

**Comment by delia-pop** [comment]
This is still reproducible on Nightly 105 from 08/09 with Lenovo Yoga Tab 11 (Android 11).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813890

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
