### ISSUE TITLE
FNX-5559 ⁃ [Meta] Site controls

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#227]
### Why/User Benefit/User Problem
As a user, I want to know if I can trust the website provider before entering any sensitive data (e.g. credit cards, login information)

### What / Requirements
I can easily access information about a site, secure/unsecure connection, untrusted connection warning

**Comment by st3fan** [comment]
@bbinto can you be more specific what this is? Can you post a fennec screenshot of the functionality that covers this?

**Comment by bbinto** [comment]
@st3fan it's the doorhanger in Fennec.

![screenshot_20190124-103418](https://user-images.githubusercontent.com/122897/51688989-bd81e080-1fc3-11e9-9cec-b0f2e3203333.png)

**Comment by bbinto** [comment]
Not currently on the milestone board as the A/C team will cover the entire work for this: https://github.com/mozilla-mobile/android-components/issues/1852
