### ISSUE TITLE
[webcontent] Camera switching bug when remembering decision for site

### ISSUE THREAD

**Issue by timsun28** [mozilla-mobile/fenix#22704]
## Site with issue and any steps to reproduce
The following issue happens when toggling between cameras and telling Firefox to remember decision for this site. 
It can be tested in the following example: https://codepen.io/mozmorris/pen/mddvKBE (this is not my code, but has the same issue I have in my own code that is not publicly available).

### Expected behavior
When using the example and pressing the Switch camera button, the camera is supposed to switch between facing modes. When not remembering the decision, this functionality works properly, but once you selected remember it will crash and give the following error: 
Error: DOMException: Starting videoinput failed

### Actual behavior
Once remembered, the view crashes and the following error is thrown in the console: Error: DOMException: Starting videoinput failed

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No, this does not fix the issue

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No, in Chrome and Safari this is not an issue. The camera switching is done properly. 

### Device information
* Android device: Google pixel 4a (but I can confirm this is also not working on other android devices)
* Fenix version: 94.1.2

**Comment by marcel263** [comment]
Reproducible with nightly #2015849547 Having remember the preferred camera and pressing "switch camera" (have to scroll to reveal button), image becomes still

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on the latest Firefox Preview Nightly 2021-12-07. I wasn't able to reproduce the crash but can confirm the image becomes still when switching cameras.
### Device used:
- OnePlus 6T (Android 9)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1744807

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jan-ivar** [comment]
Hi @marcel263 and @LaurentiuApahideanSV, thanks for filing! It WFM but I don't have those devices. Does it work any better [here](https://jsfiddle.net/jib1/fsexmu8v/show)?

@marcel263 when you say it "crashes" do you mean Firefox crashes, or the page just shows an error?

**Comment by jan-ivar** [comment]
Thanks @StigoSvK for reporting and providing valuable info!

Our previous fix was to retry once after 200ms, so if it takes 450 ms on Samsung S21 and S22 that would explain why it didn't help.

Sorry for the inconvenience, and glad to hear you were able to mitigate it on your end for now. I've opened a new issue on it https://bugzil.la/1805719 and will attempt to improve our mitigation (I need a newer phone clearly).
