### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Ryan31276** [mozilla-mobile/fenix#22706]
Bugs/Performance/Addon 

Hey mozilla i might have some serious discussion about your broswer.

Bugs / Performance
Firstly, firefox uses over 500MB of ram which is not ok when i was on some website. And i understand addons use more memory but i hate if there no to change darkmode or lightmode on website. Meaning completely.

Secondly, audio cannot play on the background unlike some broswer and i don't like that at all and your broswer decided to reload the website and it takes about 5 to 8 seconds to load a website.

Third, the links to external apps not perfoming properly, again if i left it run at the background on a short period of time it straight up blank. I tried to reload it but no matter how much time i tried to reload it will not load at all unless i close it and open it again. But that not the case it happen on the broswer itself same thing like the link to external app. I have to close the app and add a new normal / private tab and download option not working on some sites like newgrounds.com .

Fourth, website was performing ok but a little glitch it have on youtube, i set a full screen but when i select anything like speed or quality the buttons on the tablet will appear and not go down back automatically until i left full screen and go back again.

Addon
Now i know you guys introduces ads on the broswer but i hate if it has no ad blocker, i hate using addons to block ads. If you would mind add a feature to turn on ad blocker and turn it off.

____________________________________

I expect you do this so more people can use firefox.
If firefox has an update but not improve, i will switch to microsoft edge or opera. 
If it was updated but improved, i will use this broswer in the future.
But right now, firefox is a memory eater (i mean it using too much memory) not performing that great and tab sometimes not loading when reload until open a new tab.

**Comment by kbrosnan** [comment]
This needs to be separate issues. We cannot take issues that have more than one report per issue.
