### ISSUE TITLE
Open new tabs in foreground and turn off the "New tab opened" snackbar

### ISSUE THREAD

**Issue by DavidZidar** [mozilla-mobile/fenix#22703]
### Steps to reproduce

1. Long press a link
2. Select "Open link in new tab" or "Open link in a private tab"

### Expected behaviour

I expect the tab to open immediately like every other browser and not have to perform additional steps to switch to the tab that I want to interact with.

### Actual behaviour

Tabs open in the background and there is a snackbar notification in which the user is forced to press a button to switch the tab.

This snackbar is at the bottom of the screen, often far away from the link that was pressed and if I don't have both hands immediately available I often have to change my grip on my phone to be able to reach the switch button and by the time I get there it is often too late because the snackbar is now gone because it is only there for 2 seconds. Now I have to navigate to the tab switcher and find the tab wherever it may be, if it's a private tab there are even more buttons to press. This happens to me many times a day and is incredibly frustrating.

A simple long press and open in new tab has become an arduous process.

### Device name

Google Pixel 6 Pro

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

I'm reporting this as a bug because this is terrible UX that should be fixed. I understand that some users wants to perform more steps in case they want to open more than one tab but it needs to be an option.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18822)

**Comment by DavidZidar** [comment]
I seem to have received a down vote. Some context then, I've very nearly dropped my phone on more than one occasion on account of having to hastily change my grip to be able to reach the switch-button in time. I don't think it should be this difficult to open tabs in private windows, other browsers do not have this barrier.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1362862

**Comment by DavidZidar** [comment]
@revad Thanks for the tip, appreciate it, but that's too many hoops for me. This is a really basic usability issue that should be fixed in Firefox.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812867

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
