### ISSUE TITLE
[Bug]: Password autofill not supported on Android 7

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/fenix#22719]
### Steps to reproduce

User has credentials for Amazon and eBay saved in Firefox for Android
Amazon and eBay apps are installed
Password autofill turned on in Firefox for Android

### Expected behaviour

Password autofill supported

### Actual behaviour

Password autofill not supported

### Android version

Android 7

### Firefox release type

Firefox

### Firefox version

94.1.2

### Additional information

SUMO Forum question: https://support.mozilla.org/en-US/questions/1359849

**Comment by kbrosnan** [comment]
[Autofill requires Android 8 or newer](https://developer.android.com/guide/topics/text/autofill). Creating our own shim for older Android would be a large amount of work.
