### ISSUE TITLE
[Bug]: fetch + XMLHttpRequest.open stall for 30+ seconds after browser is minimized

### ISSUE THREAD

**Issue by patr-ck** [mozilla-mobile/fenix#22714]
### Steps to reproduce

Serve yourself the following page ...
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <script>
     function test() {
       var r = new XMLHttpRequest();

       r.onreadystatechange = function() {
         document.querySelector("#log").textContent = r.readyState;
       };

       r.open("DELETE", "/thing");
       r.send();
     }
    </script>
  </head>
  <body>
    <a onclick="test();">CLICK IT</a>
    <div id="log"></div>
  </body>
</html>
```

When you initially navigate to the page, clicking the link opens and sends the request immediately as would be expected.  If you minimize Firefox, go to a different app on your phone, and then return to Firefox and click the link the request stalls on state 1 (the open call) for 30+ seconds.  It does eventually come out, but only after a long delay.

If you press the link again before the first request has finished, both requests come out immediately, and then future requests are normal speed.

`fetch` has the same behavior as the example above.

This is different behavior then all the other browsers I have tested.

### Expected behaviour

The open call should not take so long

### Actual behaviour

The open call takes a long time

### Device name

Google Pixel 4

### Android version

12

### Firefox release type

Firefox

### Firefox version

95.1.0

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1745840

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
