### ISSUE TITLE
Removal of non-compliant search engines

### ISSUE THREAD

**Issue by lwa-moz** [mozilla-mobile/fenix#22718]
Firefox BD and Legal report that there are 55 search engines made available in various locales on Firefox for Android that are not compliant with our current contracts. These search engines should be removed to avoid legal risks.

A list of these engines can be found [here](https://docs.google.com/spreadsheets/d/1lO3qkbpMzhU7NxXPffZ93T7-7W0SSFxJTJwsHNqBu-s/edit?usp=sharing).

The volume of traffic on non-compliant search engines on Firefox for Android can be found [here](https://sql.telemetry.mozilla.org/queries/83126).

In order to remove these engines, the following steps should be taken:

- Remove engines from list.json
- Remove any related XML files

Mike Kaply was on point for Engineering during the audit process and should be able to provide clarification where needed.

Acceptance criteria are that these engines are removed from Firefox for Android. Suggested timing is Q1 2022.

**Comment by flodolo** [comment]
I strongly suggest to also review the URLs for the remaining search engines, comparing them to Firefox desktop.

We used to have scripts syncing mobile (at least Firefox for Android) and desktop products, but they were probably run once or twice, then abandoned.

**Comment by Mugurell** [comment]
Changes landed in AC - https://github.com/mozilla-mobile/android-components/pull/11665
Closing the ticket.
