### ISSUE TITLE
Add Contile to Top Sites

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#22727]
https://mozilla-hub.atlassian.net/browse/FNXV2-18722

**Comment by LaurentiuApahideanSV** [comment]
tested the issue on a Nightly debug build 2022-03-03. Sponsored tiles are displayed in the top sites section if the device is set to a region where these tiles are active.
![google_pinned](https://user-images.githubusercontent.com/50983519/157234832-8c2bef73-1d6b-4600-9158-f942630b5fac.JPEG)
