### ISSUE TITLE
Microsoft Teams app doesn't launch from URI

### ISSUE THREAD

**Issue by ShintoPlasm** [mozilla-mobile/fenix#22734]
When I try to join a MS Teams meeting by clicking on the invite link, the following page opens up in Firefox:
https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3Ameeting_Y2JiMjA0YTgtN2Q1OC00ZjNlLTk4Y2UtNTQ1YjZhZDAyY2Q0%40thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%2522deff24bb-2089-4400-8c8e-f71e680378b2%2522%252c%2522Oid%2522%253a%25223e572c6a-719f-458e-81be-d5387ec7ab23%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=0e6b5e15-91f5-4560-80a8-52776089e6c1&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true

However, when I click 'Join meeting' nothing happens. I've enabled the launching of external apps, and disabled adblocking (in uBO) and tracking protection. Clicking 'Get Teams' works as expected and switches me to the Play Store. Clicking 'Join meeting' works fine in Brave and other Chromium-based Android browsers.

Version information:
- Branch: Stable
- Version: 94.1.2
- Build: #2015844587
- OS: Android 12
- Device: Google Pixel 5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18843)

**Comment by PhoenixIV** [comment]
Confirmed from Samsung a52s and OnePlus 2 using version 95.1.0

**Comment by ShintoPlasm** [comment]
Still the same using version 95.2.0

**Comment by ShintoPlasm** [comment]
Still the same on version 96.2.0 (Build #2015858259).

**Comment by PhoenixIV** [comment]
To give this a little more urgency: I am taking care of some business people who you cannot explain to why and how they should copy an invitation link to a different browser in order to make it work. Therefore not being able to use Firefox on Android. Just because of this...

**Comment by ShintoPlasm** [comment]
Still the same on version 103.2.0

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813717

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
