### ISSUE TITLE
[Bug]: Dismissing the keyboard from the toolbar will hide the 3-dot menu

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22736]
### Steps to reproduce

1. Launch Firefox and tap on the toolbar to bring up the keyboard
2. Tap on the screen to dismiss the keyboard
3. Observe the toolbar

### Expected behaviour

The keyboard is dismissed and the 3-dot menu button is displayed

### Actual behaviour

The keyboard is dismissed but only the search bar is visible

https://user-images.githubusercontent.com/89511597/145047542-43700158-1049-4a3b-836f-92fdbb34c686.mp4

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1 2021-12-07

### Additional information

This issue does not occur when using the back button. Could not reproduce on RC build

**Comment by SoftVision-LorandJanos** [comment]
This issue is reproducible on the latest builds:

- latest Release (95.1.0).
- latest Beta (96.0.0-beta1).
- latest Nightly 97.0a1 (2021-12-10).

Device used: Xiaomi Mi11 Lite (Android 11).

**Comment by mcarare** [comment]
After trying some fixes I came upon some questions that might need answering before trying to tackle this, by better describing the expected app behavior to these user actions.

- Displaying home behind the search fragment means that when you scroll, touch the home area you do not actually leave the search screen/ fragment. So I am not sure having the menu on the toolbar is expected, as you are actually still in the search screen.
- If we choose to navigate to home and as a result also display the menu it should be expected that the first screen interaction would just handle the navigation and keyboard dismissal and we would have the problem described in [this](https://github.com/mozilla-mobile/fenix/issues/20701) issue.

So it is a matter of choice between one behavior or the other and as it is something that can be very subjective I think UX should weigh in on this, having also in mind the context of showing home behind search reasoning.

cc: @topotropic

**Comment by rocketsroger** [comment]
After some investigation, I have the same conclusion as @mcarare.  There's no good way to keep both the scrolling behaviour that we want but to show the 3-dot menu if the user does not press back.  I've put up a PR that will not remove focus from the toolbar so the user will have some hint that they are still in input mode.  Hopefully this way it will give the user enough hint that they need to press back or tap on the toolbar to continue their input.

**Comment by topotropic** [comment]
> * If we choose to navigate to home and as a result also display the menu it should be expected that the first screen interaction would just handle the navigation and keyboard dismissal and we would have the problem described in [this](https://github.com/mozilla-mobile/fenix/issues/20701) issue.

I couldn't figure out what the issue is – could you elaborate? Thanks!

**Comment by rocketsroger** [comment]
> I couldn't figure out what the issue is – could you elaborate? Thanks!

Sure, to reproduce this:
1. While in a page (or at home page), tap on the URL to enter a new address or search term.
2. Home page will show.  Scroll the homepage to make sure keyboard is hidden.
3. 3-dot menu is now hidden since we're still in an input mode.

**Comment by topotropic** [comment]
Thanks, Roger! 

Can you help me understand what the experience would be if we switch from search bar to location bar with menu on scroll, it sounds like it's not possible or requires extra steps, yes?

**Comment by rocketsroger** [comment]
> Thanks, Roger!
> 
> Can you help me understand what the experience would be if we switch from search bar to location bar with menu on scroll, it sounds like it's not possible or requires extra steps, yes?

Sure.  If we force a switch from search bar to location bar while user is scrolling, it will cause the first scroll to be ignored.  From the user point of view, they will think that Fenix has ignored their input, or there's was a performance issue.  After some investigate with @mcarare, we basically either have to ignore a scroll to for the switch, or not switch but to leave some hint to the user that they are still in input mode.

**Comment by bli-mozbj** [comment]
One more thing, when the 3-dot is hidden, and "adjust home page" button appears at the bottom, tapping on the button, nothing will happen, which may confuse users.

**Comment by rocketsroger** [comment]
> One more thing, when the 3-dot is hidden, and "adjust home page" button appears at the bottom, tapping on the button, nothing will happen, which may confuse users.

This should be fixed with https://github.com/mozilla-mobile/fenix/issues/22754.  Thanks
