### ISSUE TITLE
Tracking pixel

### ISSUE THREAD

**Issue by PseudonymIII** [mozilla-mobile/fenix#22731]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

The website operator or sender of an email adds the tracking pixel using a code in the website’s HTML code or email. This code contains an external link to the pixel server. If a user visits the destination website, the HTML code is processed by the client – usually the user’s browser. The browser follows the link and opens the (invisible) graphic. This is registered and noted in the server’s log files.

In addition, various information about the user is also transmitted using this method. To some extent, combination with JavaScript is necessary in order to collect information about the operating system or browser type.

The following data can be acquired and analyzed with a tracking pixel.

Operating system used (gives information on the use of mobile devices)
Type of website or email used, for example on mobile or desktop
Type of client used, for example a browser or mail program.
Client’s screen resolution
Time the email was read or website was visited
Activities on the website during a session (when using multiple tracking pixels)
IP address (gives information on the Internet Service Provider and location).

also please visit this sites for more information:
https://en.ryte.com/wiki/Tracking_Pixel
https://www.indeed.com/career-advice/career-development/what-is-tracking-pixel

### How do you know that this problem exists today? Why is this important?

tracking pixel (also called 1x1 pixel or pixel tag) is a graphic with dimensions of 1x1 pixels that is loaded when a user visits a webpage or opens an email. Because it is so small, it can hardly be seen by visitors of a website or email recipients. These tracking pixels are partly or fully designed to be transparent, or camouflaged in the background color of the website so that they don't stand out to users. Users are usually not supposed to see the tracking pixel. The focus is mainly on the processes that are initiated by downloading the tracking pixel.

Tracking pixels within the source code might look like this:

```
<img style="“position: absolute;" src="“Tracking">

<img style="“display: none”;" src="“Tracking">

<img src="“Tracking" width="“0”" height="“0”">
```

The tracking pixel URL is the memory location on the server. When the user visits a website, the image with the tag is loaded from this server. Optical properties such as visibility, or a very small size are defined using the style attribute.

### Who will benefit from it?
users have more control data they shared in internet by blocking tracking pixel, also add the Smart Anti-Tracking feature(blocking tracking pixel) and It will allow users to block tracking by using small pixel images like samsung internet browser.

**Comment by kbrosnan** [comment]
This is platform work whatever the Gecko team chooses to do with bz-1744692 is enough for Fenix.

**Comment by PseudonymIII** [comment]
> This is platform work whatever the Gecko team chooses to do with [bz-1744692](https://bugzilla.mozilla.org/show_bug.cgi?id=1744692) is enough for Fenix.

Give me a break, are you saying fenix base is gecko and if they add in gecko will be add to fenix?

**Comment by kbrosnan** [comment]
Yes, Gecko is the rendering engine powering Fenix. Fenix does not directly interact with web content. It is largely focused on the UI for a browser.
