### ISSUE TITLE
notify out of date users and direct them to the store

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22747]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Many applications supports in the in app update wherein it will show a notification that an update is available and on clicking it , it will download in the background and once downloaded it will show Google Play page with the installing message
Can same be implemented for Firefox?

### How do you know that this problem exists today? Why is this important?
App must support in app update 

### Who will benefit from it?
Users who have disabled playstore automatic download and are not aware new version available

![Screenshot_20211208-150243033](https://user-images.githubusercontent.com/58127841/145185113-c0dd8221-314a-4f16-9d47-6a301ff9094e.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18858)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813721

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
