### ISSUE TITLE
Android Nightly Builds Changelogs

### ISSUE THREAD

**Issue by blogmangit** [mozilla-mobile/fenix#22750]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

I want to see the android nightly build changelogs to check out what's new has been implemented or removed.

### How do you know that this problem exists today? Why is this important?

At present we are unable to find any changelogs on android nightly builds.

### Who will benefit from it?

Everyone who keeps track of latest developments.

**Comment by cadeyrn** [comment]
> At present we are unable to find any changelogs on android nightly builds.

https://github.com/mozilla-mobile/fenix/commits/main

**Comment by kbrosnan** [comment]
The commits of the several projects Fenix uses are the best source of the information you want.
