### ISSUE TITLE
[Bug]: crash on settings -> delete browsing data 

### ISSUE THREAD

**Issue by gwarser** [mozilla-mobile/fenix#22752]
### Steps to reproduce

1. open settings
2. open delete browsing data
3. wait

### Expected behaviour

use the interface

### Actual behaviour

crash after few seconds

### Device name

lg l65

### Android version

7.1.2 (lineage os 14.1)

### Firefox release type

Firefox Nightly

### Firefox version

2015850217

### Device logs

https://crash-stats.mozilla.org/report/index/b738be15-cce7-43a9-9220-7b25d0211208

### Additional information

Can be related to this new label with number of addresses under history section - does not show up before crash on this device, but I see it on another.

Android RAM stats show that Firefox maxed at 0.98 out of 1GB which never happened to me before.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18861)

**Comment by SoftVision-LorandJanos** [comment]
Hi @gwarser . Thank you for your report!
I couldn't reproduce the issue you reported.
My device with the closest Android version to yours is a Motorola Nexus 6 with Android 7.1.1.
Also tried on the following devices:
- Xiaomi Mi11 Lite (Android 11).
- Google Pixel 3 (Android 12).

Aside from the build it was logged with, I tested on the following builds:
- latest Nightly 97.0a1 (2021-12-28).
- latest Beta (96.0.0-beta5).
- latest Release (95.2.0).

**Comment by gwarser** [comment]
https://crash-stats.mozilla.org/report/index/ef874a4e-36df-4bb8-a6dc-444f60211228

**Comment by gwarser** [comment]
Did not happened in stable or beta. I synced them, and they correctly show little under 5k addresses under history cleaning option. Then I also cleaned Nightly storage from android settings, synced, and it no longer crashes. Maybe it crashes if enough history is logged from actually using it on phone?

**Comment by SoftVision-LorandJanos** [comment]
@gwarser , is this issue still reproducible for you?
