### ISSUE TITLE
FNX-5561 ⁃ [Bug] Investigate: Sentry.init blocks main thread on startup from `Lookup` static init

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#2276]
According to https://github.com/getsentry/sentry-java/issues/708 , Sentry blocks the main thread for a long time on startup (on some devices) because the `Lookup` class' static initialization block.

**I do not know if this affects Fenix** but I wanted to file it for others to investigate because I heard startup performance was a goal.

### Device information
* Android device: ?
* Fenix version: ?

**Comment by ekager** [comment]
CC @hawkinsw may be something to check out !

**Comment by hawkinsw** [comment]
Thanks for pointing this out to me. I will absolutely take a look at it immediately. Thanks for the pointer to this issue.

**Comment by hawkinsw** [comment]
@mcomella How did you discover this. Did you see it in a profile or on a nimbledroid run? Also, @ekager should we tag this with performance?

**Comment by mcomella** [comment]
> @mcomella How did you discover this. Did you see it in a profile or on a nimbledroid run?

I saw the bug filed with Sentry: I have no personal experience seeing the issue.

**Comment by hawkinsw** [comment]
I am flagging @colintheshots for more information, here. 

After investigation, at this point this is not a problem for startup. Sentry initialization takes ~40ms on a Pixel 2. In terms of all the things that we need to optimize at application startup, there are bigger fish to fry at this point.

That said, those initialization times were measured with a noop protocol or configuration pointing to an inactive web server. Sentry initialization does take place on the main thread so I want to measure the initialization time in a real scenario where it connects to a real service. 

That's where @colintheshots comes in. Can you provide me with the actual DSN that we would use for the release? According to the comments in the Gradle build files, that configuration 

> Reading sentry token from local file (if it exists). In a release task on taskcluster it will be available.

Can you help me track that down? Thank you!

**Comment by mcomella** [comment]
> That's where @colintheshots comes in. Can you provide me with the actual DSN that we would use for the release? According to the comments in the Gradle build files, that configuration
> 
> Can you help me track that down? Thank you!

@hawkinsw Assuming you have access to the Sentry dashboards, check out our guide: https://github.com/mozilla-mobile/shared-docs/blob/master/sentry_guide.md Note that they may have moved it though.

**Comment by hawkinsw** [comment]
Thanks. Not sure I have that access, sorry. I will investigate, though.

**Comment by hawkinsw** [comment]
I have completed the investigation. Thanks to @mcomella for providing me with the proper Sentry configuration for debugging. It does not appear that there is any additional initialization overhead when connecting to a real server. 

Since there are other problems to solve before this becomes an issue, I recommend leaving this open but only revisiting it after we have sorted other problems. I will defer to @ekager and @colintheshots and @mcomella, though.

**Comment by mcomella** [comment]
fwiw, one thing that stands out to me in the original issue is:

> On some android devices Sentry initialization may take up to 1-2 seconds

I wonder what this means: is this devices with certain hardware configurations (e.g. slow disk) or perhaps different devices from certain vendors (e.g. Samsung) who modify some amount of the Android OS?

**Comment by hawkinsw** [comment]
This is an incredibly interesting question. One thing that I noticed was
that it *seems* to be related to a network proxy. Is it possible that the
performance bottleneck is related to if/how a device is configured with the
proxy to get access to the net? Just something that stuck out at me when I
was looking at the profile referenced in the ticket.

What do you think?

**Comment by mcomella** [comment]
> Is it possible that the performance bottleneck is related to if/how a device is configured with the proxy to get access to the net?

It looks like the problem method gets called whether or not a proxy is configured: the stack is:
```
createHttpConnection
  createProxyHost
    Lookup.<something>
```

Where the core problem is that the static initialization block of `Lookup` is accessing Android resources on the disk.

According to [the createHttpConnection javadoc](https://github.com/getsentry/sentry-java/blob/94862776b8825bad12a94fdeacb654ba7b2ac0aa/sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java#L396), it gets called to "Creates an HTTP connection to the Sentry server." – because of the doc, I'd expect this to get called with any real DSN. [Unconditionally, getProxyHost](https://github.com/getsentry/sentry-java/blob/94862776b8825bad12a94fdeacb654ba7b2ac0aa/sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java#L404) and [then Lookup](https://github.com/getsentry/sentry-java/blob/94862776b8825bad12a94fdeacb654ba7b2ac0aa/sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java#L692) get called, triggering the Lookup static initialization.

**Comment by vesta0** [comment]
@hawkinsw are you looking into this bug ? Please let us know if this can be closed if it's tracked somewhere else.

**Comment by hawkinsw** [comment]
I was looking into this and swore that I commented on the result of my investigation. I am not sure where it went, though. I will point to it. Sorry for the lack-of-update. I thought that I had posted here.

**Comment by hawkinsw** [comment]
See https://github.com/mozilla-mobile/fenix/issues/2276#issuecomment-490281060 above. I think that will be our "resolution" at this point.
