### ISSUE TITLE
[Bug]: System allowed permissions status is not reflected in Fenix settings 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#22762]
### Steps to reproduce

1. Go to system settings>Apps>Fenix>Permissions and change to **don't allow** for all permissions.
2. Go to Fenix>Settings>Site permissions and check the status.
3. Go to system settings>Apps>Fenix>Permissions and change to **ask every time** for all permissions.
4. Go to Fenix>Settings>Site permissions and check the status.

### Expected behaviour

"Ask to allow" is the status displayed.

### Actual behaviour

"Blocked by Android" is the status displayed.

### Device name

Pixel 3

### Android version

12

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.1

**Comment by Amejia481** [comment]
Unfortunately, there is not much what we can do as there's a limitation on the Android OS, we only get notified about two status for permissions either [PERMISSION_DENIED](https://developer.android.com/reference/android/content/pm/PackageManager#PERMISSION_DENIED) OR [PERMISSION_GRANTED](https://developer.android.com/reference/android/content/pm/PackageManager#PERMISSION_GRANTED), and the option **"ask every time"** is reported [PERMISSION_GRANTED](https://developer.android.com/reference/android/content/pm/PackageManager#PERMISSION_GRANTED).

Closing we can not address this issue.
