### ISSUE TITLE
[Bug]: The same search group is displayed multiple times in the History section

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#22764]
### Steps to reproduce

1. Search for a term
2. Open one of the results
3. Open history

### Expected behaviour

One search group should be displayed

### Actual behaviour

The same search group is displayed multiple times

### Device name
OnePlus A3 Android 6.0.1

### Firefox version
Firefox 96.0.0 Beta 1
Firefox Nightly from 12/09

### Additional information

► Video

https://user-images.githubusercontent.com/51314259/145415480-59a08104-cec4-4619-b4f4-cb1a110ff8c2.mp4

**Comment by Mugurell** [comment]
Saw this also in https://github.com/mozilla-mobile/fenix/issues/22404

**Comment by grigoryk** [comment]
Wow, yup.
STR below:
-on a clean profile
- search for cat
- click on Wikipedia results page
- open history

![Screenshot_20211215-230649](https://user-images.githubusercontent.com/465422/146324254-e13cb4a5-8dec-4fb4-9186-b090d1b1f5d9.png)

**Comment by grigoryk** [comment]
Just from the way this looks - It’s probably a bug while interacting with the paging API; in `DefaultPagedHistoryProvider` we are supposed to stop returning results at some point - then the OS will stop asking us for more results. But here, we must be always returning the same few things, never return nothing on a page request regardless of the offset, and so it ends up in a infinite scroll.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (2021-12-22) using the steps mentioned above.
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.
