### ISSUE TITLE
Searches originated from the same search term are not grouped under the term used.

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#22763]
### Steps to reproduce

1. Search for a term using a search engine;
2. Open several results;
3. Visit and the close the pages;
4. Open a random website;
5. Perform a new search using the same term from step 1;
6. Open several results;
7. Visit and the close the pages;
8. Check the Recently visited section from the Homepage and the History section.

### Expected behaviour

Searches originated by the same term are grouped.

### Actual behaviour

Searches originated from the same search term are not grouped under the term used and search grouping with the same name are created.

### Device name

Oppo Find X3 Neo

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.1

### Additional information

![1639058127280](https://user-images.githubusercontent.com/50983519/145410528-615e3990-e0ea-47d3-9db3-14bb717a02c1.JPEG)
![1639058127411](https://user-images.githubusercontent.com/50983519/145410532-eb2ab137-43ce-46ce-a60e-708083d58019.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18871)

**Comment by delia-pop** [comment]
Reproducible on Beta 100.0.0-beta.4 with Google Pixel 6 (Android 12).

![Screenshot (Apr 13, 2022 10 02 44 AM)](https://user-images.githubusercontent.com/89388888/163119099-a9b20221-e08b-4bfb-9aa1-c9e55cf6f340.png)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813103

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
