### ISSUE TITLE
Sync Top Sites using Mobile Bookmarks folder

### ISSUE THREAD

**Issue by lucianmarin** [mozilla-mobile/fenix#22768]
In the old version of Firefox for Android, Top Sites were synced using the Mobile Bookmarks folder. In Fenix this isn't possible.

### What is the user problem or growth opportunity you want to see solved?

Restore Top Sites using account bookmarks backup.

### How do you know that this problem exists today? Why is this important?

It's hard to arrange Top Sites in order. They should keep the same order as in Mobile Bookmarks folder. There isn't possible to backup Top Sites at this moment. There many benefits if Mobile Bookmarks folder becomes Top Sites on Fenix.

### Who will benefit from it?

Everyone who restores the account from backup or wants to add a top site from desktop.

**Comment by kbrosnan** [comment]
Firefox for Android <68 never had a feature that sync'ed top sites. Sync top sites request is tracked at https://github.com/mozilla-mobile/fenix/issues/10583
