### ISSUE TITLE
[Bug]: Search term groupings don't disappear after 14 days

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#22765]
### Steps to reproduce
1. Create a search term group
2. Force stop Fenix
3. Set date to 14 days in the future

### Expected behaviour
The search term group should disappear

### Actual behaviour
The search term group remains displayed

### Device name
OnePlus A3 Android 6.0.1

### Firefox version
Firefox 96.0.0 Beta 1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18873)

**Comment by csadilek** [comment]
@AndiAJ I think this may just be a misunderstanding. Groups do not necessarily disappear after 14 days. After a cold start and on visual completeness (~5s after startup) we clean up our database and remove metadata that's older than 14 days.

However, that doesn't mean that the entire group necessarily goes away as it could contain items that are newer / have been updated more recently e.g. if you launch right into tab that's in the group then that counts as an update. So currently that group wouldn't disappear then.

It's worth discussing if we want to be more strict here, but we didn't see this as a requirement to have groups guaranteed to disappear after two weeks.

**Comment by csadilek** [comment]
Note that we're deleting history metadata from the storage older than two weeks, but we're not removing metadata from open tabs. Here's are some STR to test the current behaviour:

- Open a tab and search for "cat"
- Open a few links (actually switch to the tabs too and view them)
- Now you should have a tab group and a group in recently visited and history
- Close the tabs in this group
- Now you should have a group in recently visited and history only
- Stop Fenix
- Set data to more than 14 days in the future
- Start Fenix and wait at least 5 seconds (for the cleanup task to kick in)
- The group should be gone

@AndiAJ if this works correctly ^^ I think we can close this ticket. We need to separtely discuss if tab groups should also be disbanded after two weeks, but I don't think so. (Note that any interaction with a tab groups would also bring back the group in history.)

**Comment by delia-pop** [comment]
@csadilek I tested the flow above and I can confirm that the search group was no longer available in History after more that 14 days. The tabs previously grouped under "cat" are now displayed under "Last 30 days".

After Step 8, upon opening Fenix the group was still displayed in recently visited, but is was properly removed after waiting ~ 5 seconds >  accessing History > returning to the homepage. 

Please see the short video below.
https://user-images.githubusercontent.com/89388888/163122588-818845d1-baa0-425e-b228-141ca2c1f648.mp4

**Comment by csadilek** [comment]
Thanks, @delia-pop. This seems all as designed to me then.
