### ISSUE TITLE
[Bug]: Not have icon when adding search engine

### ISSUE THREAD

**Issue by Rosabis** [mozilla-mobile/fenix#22760]
### Steps to reproduce

1.select search
2.add a new search engine such as findx
3.not have icon which sites use,only F icon.

### Expected behaviour

Use the icon which sites use

### Actual behaviour

Only choose the first letter as icon.

### Device name

Xiaomi 6

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

**Comment by kbrosnan** [comment]
duplicate https://github.com/mozilla-mobile/fenix/issues/7491
