### ISSUE TITLE
Reader Mode: Fit the overall text to the width, not the longest unbreakable line or entity.

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#22761]
### What is the user problem or growth opportunity you want to see solved?
Reader Mode usually makes  the text fit to the screen width. But in some cases, it can't, because is the document contains one or two entity that needs more space, like a table or an unbreakable long string. Then, FireFox starts Reader Mode fitting the width to that widest element, making the whole font smaller leaving a lot of space on the right.

I have to manually pinch-to-zoom to fit the text to the window like a normal case, and this is tedious and annoying. Most of the time, that one element is not really what I care, so I do not mind if that is clipped, or I have to scroll once to see that thing.

So, instead of fitting the view to the widest element, just fit the text to the screen by default, and show some indicator to tell the user that the Reader Mode can be scrolled horizontally to show the overflow entity. Something like flashing bottom horizontal bar for a brief moment at the start, or a right arrow above the overflow entity.

**Illustration of current problem**

[This article](https://www.techrepublic.com/google-amp/article/android-malware-infected-more-than-300000-devices-with-banking-trojans/) looks like below when first opened in Reader Mode:

![current](https://user-images.githubusercontent.com/10900489/145357950-56b9dffd-4042-4541-bf5b-88266003bbb1.png)

, and that is probably this line that has a long word and a URL.

![culprit](https://user-images.githubusercontent.com/10900489/145357942-b1670e38-769e-4555-af8f-686f609f731d.png)

What I am suggesting is starting with the text fit to screen by default like below, and let the user know that he can scroll horizontally.

![suggestion](https://user-images.githubusercontent.com/10900489/145357951-bc8f2f27-3949-4b17-b9e3-41af3afa6527.png)

### How do you know that this problem exists today? Why is this important?
Because I use Reader Mode all the time, and this problem happens a lot with a small phone.

### Who will benefit from it?
People who read articles in Reader Mode on a small phone.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18869)

**Comment by fice-t** [comment]
The linked article appears normally for me with the latest Firefox Nightly. Could you try with a newer Firefox version to see if this issue is still present?
