### ISSUE TITLE
PWA should use android-components lib-publicsuffixlist to display the domain +1

### ISSUE THREAD

**Issue by catdevnull** [mozilla-mobile/fenix#22772]
### Steps to reproduce

1. Open a link like <https://sutty.coop.ar> from another app into Fenix

### Expected behaviour

The domain in the bar should be "sutty.coop.ar"

### Actual behaviour

The domain in the bar is "coop.ar"

### Device name

OnePlus 5T

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

94.1.1

### Additional information

In this case, it is wrong because coop.ar is just the TLD. But even in other cases, it could act as a phishing vector (for example, fake-login.neocities.org looking like neocities.org.)

![image](https://user-images.githubusercontent.com/86896666/145489001-eb8a4da3-4f1e-4529-b84c-6616d21fa2e8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18878)

**Comment by kbrosnan** [comment]
https://github.com/mozilla-mobile/android-components/tree/main/components/lib/publicsuffixlist

**Comment by catdevnull** [comment]
That's not quite true. As I said,
> In this case, it is wrong because coop.ar is just the TLD. But even in other cases, it could act as a phishing vector (for example, fake-login.neocities.org looking like neocities.org.)

**Comment by kbrosnan** [comment]
coop.ar is listed on https://www.publicsuffix.org/list/public_suffix_list.dat so domain + 1 is an accurate description of the request. Compare a subdomain on coop.ar to https://bugzilla.mozilla.org in desktop. Because of the PSL Firefox understands what the important part of the domain is.

**Comment by catdevnull** [comment]
Still no attention to this bug :(

I also didn't quite understand the answer; as Sutty [which I'm part of], Neocities, WordPress and others operate user-provided sites under subdomains, it could be a way to allow for phishing under these platforms. I understand the official solution is "just add yourself to the PSL", but that's just not a possibility for folks starting out. From the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-and-non-acceptance-factors):

> It should be expected that despite whatever site or service referred a requestor to seek addition of their domain(s) to the list, projects not serving more then thousands of users are quite likely to be declined.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807415

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
