### ISSUE TITLE
FNX3-16196 ⁃ [Bug] regression: strange tab closing behavior

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2277]
### Steps to reproduce
1. go to your home screen and close tabs

### Expected behavior
Every time you close a tab there is one tab less in your tabs list.

### Actual behavior
See the attached video:

![20190504](https://user-images.githubusercontent.com/1100614/57167979-1c939480-6e00-11e9-9cbc-b20e267d01ef.gif)UNITO-UNDERSCORE!000012!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 9b0422b062153727e6fde952c439970b1a7812d2

**Comment by cadeyrn** [comment]
@ekager This is a regression of your PR #2246.

**Comment by colintheshots** [comment]
I noticed this as well. This regression seems to be caused by the undo snackbar. If the user browses away while the undo snackbar is onscreen or deletes more than one tab, various bugs occur.

**Comment by cadeyrn** [comment]
I can verifiy that it's fixed by #2281.

**Comment by ekager** [comment]
Great thanks @cadeyrn !
