### ISSUE TITLE
[Bug]: Web RTC problem Firefox 95.0.0-beta6 

### ISSUE THREAD

**Issue by vakya** [mozilla-mobile/fenix#22782]
### Steps to reproduce

Put the url: https://www.webrtc-experiment.com/DetectRTC/

In a few seconds a table appears with the version of the browser, if you have cameras, ...

Then put the same url again:: https://www.webrtc-experiment.com/DetectRTC/

The table does not appear until the touch screen of the device is touched.
This creates many problems when developing camera applications.

### Expected behaviour

The table should always appear in a few seconds with all the same RTC information.

### Actual behaviour

The table does not appear until the touch screen of the device is touched.

### Device name

Xiaomi Poco F3 Android 11 with MIUI 12.5.18, and other devices

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

95.0.0-Beta 6

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1745493

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by docfaraday** [comment]
@vakya I can reproduce this on Beta on my android device, but Nightly seems to work fine. Could you check to see whether Nightly works for you?

**Comment by vakya** [comment]
Thanks DocFaraday, yes this part of RTC works fine in firefox Nightly.
