### ISSUE TITLE
[Bug]: (Custom collection) Extension install failing without any explanation

### ISSUE THREAD

**Issue by ttyridal** [mozilla-mobile/fenix#22786]
### Steps to reproduce

fresh install of Firefox nightly

enable files permission (required?)

Following directions from [expanded-extension-support-in-firefox-for-android-nightly](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)
(with collection 11451974 - masterpassword)

install addon

### Expected behaviour

addon installs correctly or gives a reason for why it's failing

### Actual behaviour

Toast with "Failed to install ..." message

### Device name

Galaxy s10 / Emulator

### Android version

Several (8, 11)

### Firefox release type

Firefox Nightly

### Firefox version

96.0a1

### Additional information

The same extension runs as expected without any error messages observed when loaded in debugging mode (web-ext / adb)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/22716
