### ISSUE TITLE
security lock items separator not visible  in light theme

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22789]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
On clicking the security lock icon, it has various sections- site security,  site permissions, etp and clear site specific data, the separator horizontal line is not visible clearly..Yes it has separator but visible faintly when screen brightness is high

### How do you know that this problem exists today? Why is this important?
Separator line not visible. Please change the separator line color to some dark color

### Who will benefit from it?
All users

![Screenshot_20211210-195224558](https://user-images.githubusercontent.com/58127841/145589264-df7c5760-dbc0-46cb-911f-661dec0cee41.jpg)

**Comment by sheikh-azharuddin** [comment]
In dark theme the separator line is clearly visible
Also the separator line is very close for the enhanced tracking protection section

![Screenshot_20211217-231431519 (1)](https://user-images.githubusercontent.com/58127841/146586291-ab5ae67b-58ef-4789-8393-0073d13e0b7e.jpg)

**Comment by sheikh-azharuddin** [comment]
Hello team
Any update?

**Comment by LaurentiuApahideanSV** [comment]
The issue has been fixed in Firefox Nightly 2022-05-11. I will close this issue:
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
![1652281621583](https://user-images.githubusercontent.com/50983519/167883981-f543906d-c0e9-47d9-85ae-b46cdffdb6ba.JPEG)
