### ISSUE TITLE
[Bug]: double tap on editable text doesn't select word

### ISSUE THREAD

**Issue by Yajo** [mozilla-mobile/fenix#22781]
### Steps to reproduce

1. Open duckduckgo.com
2. Write some words on search box
3. Double tap on one word of those

### Expected behaviour

That entire word is selected. 

### Actual behaviour

Just the caret moves. 

### Device name

samsung galaxy a72

### Android version

11

### Firefox release type

Firefox

### Firefox version

95.1.0 (Build 2015848803)

### Additional information

Non-editable text already works as expected in Firefox.

**Comment by SoftVision-LorandJanos** [comment]
Hi @Yajo ! Thank you for the report!
The behavior you described is correct.
As far as I know it was intended this way, it was the same before.
Checked on Chrome as well where the behavior is as you described it would be expected.
I will change this ticket from bug to feature request.

**Comment by issue-dispenser** [comment]
@SoftVision-LorandJanos Do you mean that the Chrome behavior is the same as Firefox for you? On my device double-tap selects the word in Chrome, and on my desktop double-click in Firefox selects the word.

**Comment by makotokato** [comment]
@Yajo  @issue-dispenser 
This is known issue such as https://github.com/mozilla-mobile/fenix/issues/9714. This is dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1365119.

**Comment by Yajo** [comment]
> Do you mean that the Chrome behavior is the same as Firefox for you?

I mean Chrome behaves OK and Firefox doesn't.

**Comment by kbrosnan** [comment]
This is platform work. As such it is tracked in Bugzilla. Closing as upstream.
