### ISSUE TITLE
[Bug]: Search grouping deleted from history are not removed from the homepage immediately

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#22792]
### Steps to reproduce

1. Delete a search grouping from the history section by tapping the X button.
2. Go to the Homepage and observe the Recently visited section.

### Expected behaviour

The search grouping deleted from the history should be deleted from the Recently visited section from the homepage.

### Actual behaviour

The search grouping is not deleted until a new page is loaded or a new section is accessed.

### Device name

Oppo Find X3 Neo

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

2021-12-10

### Device logs

https://user-images.githubusercontent.com/50983519/145601635-4d39d49c-2b22-4127-8f1c-fe127920dd4a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18889)

**Comment by MohitMandalia** [comment]
Yes @LaurentiuApahideanSV  correct I also found the same issue with recently visited List on home page
