### ISSUE TITLE
Simplify access to saved logins

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#22797]
### What is the user problem or growth opportunity you want to see solved?

In the current implementation, accessing your saved logins on Fenix takes quite a few clicks (three dot menu -> settings -> logins -> saved logins -> authenticate with password -> logins lists). We should make them easier to access. 

Related requests: 
https://github.com/mozilla-mobile/fenix/issues/22677
https://github.com/mozilla-mobile/fenix/issues/22564

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18894)

**Comment by pbhj** [comment]
Agreed, IIRC it used to be a top level menu item, not sure why it got hidden?
