### ISSUE TITLE
FNX-5564 ⁃ [Meta] Authentication / Logging into websites

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#228]
### Why/User Benefit/User Problem
User wants to use their credentials to log into to password protected websites

### What / Requirements
Provide a UI to let users authenticate themselves to log in to websites

### Acceptance Criteria (how do I know when I’m done?)
User can login to website via browser UI

**Comment by st3fan** [comment]
Assuming this is about basic authentication, this work landed as core browser functionality and will not require additional work in Fenix. See https://github.com/mozilla-mobile/android-components/pull/1702

**Comment by bbinto** [comment]
I think we can close this, right @st3fan?
