### ISSUE TITLE
[Bug]: Cannot add a link to the home screen

### ISSUE THREAD

**Issue by PeopleInside** [mozilla-mobile/fenix#22805]
### Steps to reproduce

1. Open a web address
2. Click on tre dots menu and try to add the page to the Android home screen

### Expected behaviour

Page is added to the home Android screen

### Actual behaviour

No page added to the home Android screen

### Device name

Xiaomi Poco X3

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

95.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18901)

**Comment by LaviniaL99** [comment]
Hello @PeopleInside 
Thanks for your report!
I tested the above issue on the **latest Nightly build** 97.0a1(Build #2015856555) and **latest release version** RC 96.1.1 (Build #2015855931) and I was not able to reproduce the issue.

Devices used: Samsung S10E -> Android 10 / Xioami Mi11 Lite (Android 11)

Can you please confirm if you are still able to reproduce the problem on the latest builds? If yes, please attach a video.
Thanks!

**Comment by PeopleInside** [comment]
Hi @LaviniaL99 ,
I'm still able to reproduce this with Firefox 95.2.0 that is the stable Firefox that is present in the play store.

My report is valid for the stable Firefox version that users are able to download from the official Google Play Store.
As my phone is private and I have not a test phone I cannot attach a video but you should be able to reproduce easily.

Android 11, Xiaomi Poco X3

**Comment by LaviniaL99** [comment]
Hi @PeopleInside 

I just installed the latest version of Firefox that is available on Play Store(95.2.0) and i'm still not able to reproduce the issue.

Are there any additional steps that you follow other than the ones mentioned in the ticket?

**Comment by PeopleInside** [comment]
@LaviniaL99 

I visit a website than in the browser menu i press to add to the home screen.
No link is added on the home screen.


https://user-images.githubusercontent.com/5006150/148765891-01a1fbcf-2787-4340-b357-9df9cfe17e2f.mp4

![photo_2022-01-10_13-27-58](https://user-images.githubusercontent.com/5006150/148765908-18128261-5062-4b5a-9230-237adcf8ae8e.jpg)

**Comment by chascode** [comment]
For me, websites are added to my phone's stock launcher but not my chosen default launcher (Nova Launcher Prime).

Maybe it's the same bug?
