### ISSUE TITLE
[Bug]: CSS rule touch-action: none fails when the HTML element has a "wheel" event listener added

### ISSUE THREAD

**Issue by simonsarris** [mozilla-mobile/fenix#22807]
### Steps to reproduce

The CSS `touch-action: none;` works in Firefox for Android unless your HTML Element adds a `"wheel"` event listener. Then it fails to hold the address bar still, so the screen jumps up and down. This is true even if you try to ensure the wheel event is prevented, eg calling `preventDefault()` or `stopPropagation` do nothing.

You can reproduce the bug by pasting this into an .html file:

```
<canvas id="canvas" style="touch-action: none; border: solid 3px red; width:400px; height:400px;"></canvas>
<canvas id="canvas2" style="touch-action: none; border: solid 3px blue; width:400px; height:400px;"></canvas>
<p>
  Above are two canvas elements, both have touch-action: none. But the red one has a "wheel" event defined.
</p><p>
  Tap and hold (moving up and down) in the red canvas and the address bar moves up and down (bug).
  In the blue canvas this does not happen (it is correct).
</p>
<script>
  var can = document.getElementById('canvas');

  can.addEventListener('wheel', function(e) {
    e.preventDefault();
    e.cancelBubble = true;
    e.stopPropagation();
    return true;
  });
</script>
</body>
</html>
```

And seeing the behavior difference in the red and blue bordered canvas elements. (This bug has nothing to do with canvas, the same issue exists if they are just divs)

### Expected behaviour

Both HTML elements should act the same, allowing touches without jumping the address bar up and down

### Actual behaviour

The red canvas ceases to respect `touch-action: none;` once a wheel event is present.

### Device name

Google Pixel 5

### Android version

12

### Firefox release type

Firefox

### Firefox version

95.1.0

**Comment by Amejia481** [comment]
This is very likely to be in the GeckoView/Gecko layer, tagging some folks from the GV team to help to clarify. cc: @agi @jonalmeida

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1746336

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
