### ISSUE TITLE
[Bug]: double tap on editable text doesn't select word

### ISSUE THREAD

**Issue by amirod** [mozilla-mobile/fenix#22804]
Steps to reproduce
Open duckduckgo.com
Write some words on search box
Double tap on one word of those
Expected behaviour
That entire word is selected.

Actual behaviour
Just the caret moves.

Device name
samsung galaxy a72

Android version
11

Firefox release type
Firefox

Firefox version
95.1.0 (Build 2015848803)

Device logs
No response

Additional information
Non-editable text already works as expected in Firefox[.](https://newshungama.com/)

**Comment by makotokato** [comment]
This is known issue such as https://github.com/mozilla-mobile/fenix/issues/9714 and https://github.com/mozilla-mobile/fenix/issues/22781. Dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1365119.

**Comment by Yajo** [comment]
This is an exact copy of https://github.com/mozilla-mobile/fenix/issues/22781#issue-1076485476.

**Comment by kbrosnan** [comment]
Closing as a duplicate

**Comment by khalidmamoona4** [comment]
This is known issue such as https://github.com/mozilla-mobile/fenix/issues/9714 and https://github.com/mozilla-mobile/fenix/issues/22781 [/Soprapk ](https://soprapk.com/).Dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1365119.
