### ISSUE TITLE
FNX-5565 ⁃ [Bug] Crash after swipe to close tab

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#2280]
## Steps to reproduce
Open 2 or 3 tabs.
Swipe one of them to close.

### Expected behavior
Tab closes

### Actual behavior
It shows the undo tab close notification and then the browser crases.
https://crash-stats.mozilla.org/report/index/863b3342-29b2-4977-9390-0687a0190504

### Device information
* Android device: OnePlus 5t
![Screenshot](https://user-images.githubusercontent.com/922368/57177395-e8ee5400-6e6b-11e9-87d4-64a55e4f3507.png)UNITO-UNDERSCORE!20190428-135941!UNITO-UNDERSCORE!Settings!
* Fenix version: 4th of May build but it started happening a few days ago.

**Comment by andreicristianpetcu** [comment]
https://crash-stats.mozilla.org/report/index/0536a1ae-f692-445a-94c7-063ab0190504

https://crash-stats.mozilla.org/report/index/a985d7f6-8ae4-4828-9dca-97bd70190504

https://crash-stats.mozilla.org/report/index/1a1f122a-8de9-45ba-8956-8512a0190504

https://crash-stats.mozilla.org/report/index/c991041a-eea4-485a-95c9-9aa060190504

**Comment by andreicristianpetcu** [comment]
https://imgur.com/a/oisAt4A

**Comment by ekager** [comment]
Should be closed by #2281 :)

**Comment by andreicristianpetcu** [comment]
it works! thank you!
