### ISSUE TITLE
[Bug]: Recently visited's context menu unwanted behavior while scrolling

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#22803]
### Steps to reproduce

1 Untouched new instance of new tabs page. Long-press collection under Recently visited
2. While menu is open, scroll the Recently Visited horizontally
3. Scroll the view vertically

### Expected behaviour

Menu gets dismissed or the menu stays open but works

### Actual behaviour

Menu moves around like behavior expected of carrousel, or stays fixed on screen. It becomes unresponsive but is still present on the screen. The menu itself can also be overscrolled, this seems incorrect for context menu.
![Screenshot_20211211-130312_Firefox Nightly](https://user-images.githubusercontent.com/76437842/145675867-1adb76c1-dfe7-43ff-9c87-4e0e12f20f89.png)

### Device name

OneUI 3.1

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

2015850795

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18899)

**Comment by LaviniaL99** [comment]
Hello @marcel263 
Thanks for your report!
I tested the above issue on the latest Nightly build 97.0a1(Build #2015856555) and latest release version RC 96.1.1 (Build #2015855931) and I was not able to reproduce the issue.

After long tapping on a tab from **Recently visited section** and the "remove" menu is displayed, I'm not able to scroll horizontally on **"Recently visited section"** neither vertically on the Home screen.

Devices used:

Samsung S10E -> Android 10

Can you please confirm if you are still able to reproduce the problem on the latest builds? If yes, please attach a video of the interest flow.
Thanks!

**Comment by marcel263** [comment]
Hello @LaviniaL99 

The bug is still reproducible. It may be affected by the state of the keyboard. In the screen where one arrives after pressing the address bar, after opening and closing the keyboard, it becomes reproducible. And even more, pressing the "remove" just opens the item behind, like it's transparent. Please see the video evidence.

https://user-images.githubusercontent.com/76437842/148762459-d570edec-3882-4ac6-96f7-81f1492c1336.mp4

**Comment by LaviniaL99** [comment]
Hello @marcel263 

I followed the flow as per your video and i was able to reproduce the issue on the latest Nightly 98.0a1 (2022-01-20).

**Devices used:**
- Samsung S10E -> Android 10
- Samsung Galaxy A32 5G -> Android 11


https://user-images.githubusercontent.com/96047134/150327418-7533610a-d102-498f-9796-f8545fcc37e9.mp4

**Comment by marcel263** [comment]
> Hello @marcel263
> 
> I followed the flow as per your video and i was able to reproduce the issue on the latest Nightly 98.0a1 (2022-01-20).
> 
> **Devices used:**
> 
>     * Samsung S10E -> Android 10
> 
>     * Samsung Galaxy A32 5G -> Android 11
> 
> 
> Remove.menu.mp4

This indicates an identical issue, yes. Can you also reproduce its unwanted persistance on-screen when scrolling through Fenix's home screen vertically? It may become anchored to the edge of the viewport, masking other elements.

**Comment by marcel263** [comment]
does not appear anymore
