### ISSUE TITLE
[Bug]: Videos not opening in full screen as landscape/horizontal always

### ISSUE THREAD

**Issue by achaudhral629** [mozilla-mobile/fenix#22819]
### Steps to reproduce

1. Open incognito
2. Open a video
3. Click full screen button on video

### Expected behaviour

Video rotates clockwise to horizontal/landscape view

### Actual behaviour

video stays in vertical view 

### Device name

OnePlus 7t

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

95.1.0

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/7602
