### ISSUE TITLE
[Bug]: HTML select multiple attribute: unconfirmed selections disappear when scrolled offscreen

### ISSUE THREAD

**Issue by issue-dispenser** [mozilla-mobile/fenix#22821]
### Steps to reproduce

1. Open Fenix
2. Go to https://www.imdb.com/search/title/
3. Tap on either the Countries or Languages field (there needs to be a large number of options)
4. Tap on any number of entries and then scroll enough that the selections are scrolled out of view
5. Scroll the selected entries back into view

### Expected behaviour

The entries should still be marked as selected (checkbox present).

### Actual behaviour

The entries are not marked as selected (checkbox is not present).

### Device name

Samsung Galaxy S7

### Android version

Android 8.0

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1

### Additional information

Note that if you confirm the selection of some attributes, then the above will instead show the previously confirmed set of values marked instead of the newly selected set. For example:

1. Select and confirm Argentina and Antarctica as values.
2. De-select Antarctica and select Armenia. Scroll down to push these countries out of view.
3. Scroll back up.
4. Note that Argentina and Antarctica are shown as marked instead of Argentina and Armenia.
5. Confirm selection.
6. Note that Argentina and Armenia. despite showing otherwise, were correctly selected.

So Fenix internally tracks and produces the correct values, but it does not show the current marked set correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18910)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1745832

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by agi** [comment]
This UI is painted by the app so this is an android-components or fenix bug.
