### ISSUE TITLE
Bookmark Page Address

### ISSUE THREAD

**Issue by blogmangit** [mozilla-mobile/fenix#22820]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

I want to set bookmark as my homepage for that reason I need to know the exact address of bookmark page.

For example say about:bookmarks or something  else.

### How do you know that this problem exists today? Why is this important?

I tried and nothing happens & this is important because I want my bookmarks as homepage.

### Who will benefit from it?

Everyone who wants to customize their homepage.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/10103
