### ISSUE TITLE
[Bug]: Downloaded Files doesn't get Deleted

### ISSUE THREAD

**Issue by startadv** [mozilla-mobile/fenix#22824]
### Steps to reproduce

1. Go to any website (here google.com) to download any file.
2. Go to Download section by using the three dot menu.
3. Delete the file using the Delete option.
4. Go to your File Manager 
5. Open Downloads Folder  

### Expected behaviour

The file should be deleted. 

### Actual behaviour

The file doesn't get deleted.
The file just gets removed from the Download section in Firefox. 

### Device name

Xiaomi Redmi Y3

### Android version

Android 10 [MIUI Global 11.0.6.0 Stable (QFFINXM) ]

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.1

### Additional information

https://user-images.githubusercontent.com/94285692/145826494-b0f1cf36-58c2-4a8f-8c5a-7fccff07bc47.mp4

Video demonstrating the bug.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-01-06 and can confirm the issue occurs, however according to comment https://github.com/mozilla-mobile/fenix/issues/352#issuecomment-726805938 this may be the intended behavior.

**Comment by startadv** [comment]
I have tested in Chrome Beta 98.0.4758.46 (on the same device) and when i deleted a downloaded image from Chrome's download section it got removed from my device. 
In Firefox desktop browser (I am using Manjaro) the options are 'Remove from History' and 'Clear Downloads'.  From words itself it is understandable both options delete download history
![Screenshot_20220108_172906](https://user-images.githubusercontent.com/94285692/148643377-d262f462-f5e0-4828-ade5-638f50fba756.png)
