### ISSUE TITLE
[Bug]: Unable to save images on Google

### ISSUE THREAD

**Issue by CptNoHands** [mozilla-mobile/fenix#22835]
### Steps to reproduce

1. Navigate to https://google.com/images
2. Search for an image
3. Click an image thumbnail
4. Press and hold to attempt to bring up the context menu

### Expected behaviour

The context menu containing the ability to save an image should pop up.

### Actual behaviour

https://user-images.githubusercontent.com/96094812/145919301-ab9c45a7-2d8d-4a84-9a11-46abbb8c4d6a.mp4

### Device name

Samsung Galaxy S21 Ultra

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18917)

**Comment by SoftVision-LorandJanos** [comment]
Hi @CptNoHands. Thank you for the report!
I was able to reproduce the issue you described.
For comparison, I also checked on Chrome with the same steps and the context menu is displayed, and the image is downloadable.
Device used: Xiaomi Mi11 Lite (Android 11).
Tested on the latest Nightly (2021-12-15).

**Comment by delia-pop** [comment]
Hi, @CptNoHands, 
Enabling the Google Search Fixer addon from Settings > Add-ons will fix the issue you're experiencing. Please let us know if this works for you and feel free to re-open the ticket if needed. 

https://user-images.githubusercontent.com/89388888/183702722-6bde7cf3-0715-4233-a3ea-b01d10a7de0f.mp4
