### ISSUE TITLE
Version.txt file should contain enough information for nightly, beta and release

### ISSUE THREAD

**Issue by hneiva** [mozilla-mobile/fenix#22830]
Beetmover uses the `version.txt` file to save to __archive.m.o__. We should either update it at the right time, or change how the data is stored in the file (yaml?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18914)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802970

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
