### ISSUE TITLE
Create a settings page for allowing users to change home screen background 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#22831]
This feature should be only visible in nightly

**Comment by Amejia481** [comment]
This settings page will read from a specific internal folder `fenix/wallpapers` where wallpapers will be.

- [ ] List the wallpapers.
- [ ] Allow users to select one.
- [ ] Allow users to select none.
- [ ]  Store user's choice.

**Comment by delia-pop** [comment]
Verified as fixed on Beta 99.0.0-beta.5, Nightly 100.0a1. and RC 98.3.0.
