### ISSUE TITLE
[Bug]: "Account settings" page is grayed out after signing in

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#22848]
### Steps to reproduce

Preconditions
The user is logged in on Firefox Desktop with a valid account.
The user just installed the Fenix app and is not logged with a Firefox account on phone.

1. Tap on the 3-dot menu.
2. Tap on the "Sign in to sync" option.
3. From the "Turn on Sync" page tap on "Ready to scan" button.
4. Confirm the pairing on both devices (phone and Desktop).
5. Tap the "X" button on the "Approval now required" screen or wait for it to be dismissed.
6. Once returned to the homescreen, tap on the 3-dot menu.
7. Tap on the "Sign in to sync" option.
8. Notice the "Account settings" page is grayed out.
9. Tap on the "Syncing" button pictogram.
10. Observe if the sync is performed.

### Expected behaviour

The page loads properly and "Syncing"/"Sync now" and "Last synced: x minutes ago" on the second row text is displayed. 

### Actual behaviour

The page is not loaded properly, the options are grayed out and "Syncing" "Last synced: never" text is displayed. Tapping the "Syncing.." button pictogram will not trigger the sync. 
The user has to use the back option to return to the homescreen then access the "Account settings" again several times before the page is properly loaded.

### Device name

LG G7 fit, Xiaomi Redmi Note 8T.

### Android version

Android 8.1.0, Android 9.

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.2

### Additional information

This was reproducible on Nightly 12/14, RC 95.1.0 and Firefox Beta 96.0.0-beta.2. 
Might relate tickets https://github.com/mozilla-mobile/fenix/issues/15671, https://github.com/mozilla-mobile/fenix/issues/15818 .

https://user-images.githubusercontent.com/89388888/146003890-9083350f-6c61-4c78-95e9-1c0cdee78123.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18928)

**Comment by 424344** [comment]
please fix this issue.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810648

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
