### ISSUE TITLE
[Bug]: H264 video corrupt on Pixel 3

### ISSUE THREAD

**Issue by v-kpheng** [mozilla-mobile/fenix#22840]
### Steps to reproduce

1. Hold phone in portrait orientation
2. Using Firefox on Android, go to https://jsfiddle.net/jib1/90gznte9/
3. Click `Run` button
4. A `Start!` button will appear.  Click it.
5. When prompted for access to camera and microphone, grant it.
6. Two videos will appear
7. Change orientation of your phone from portrait to landscape
8. Look at the two videos again

### Expected behaviour

Both videos should mirror each other, regardless of orientation.

### Actual behaviour

Depending on orientation of phone, the received video (the second video element) is corrupt.

### Device name

Google Pixel 3

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

84.1.1

### Additional information

Might be related to https://bugs.chromium.org/p/chromium/issues/detail?id=1237677.

(Issue was fixed on Google Chrome and is scheduled for M97, ETA Jan. 4, 2022)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18920)

**Comment by kbrosnan** [comment]
Works for me using a Pixel 2XL and Android 11 using Firefox Beta 96. Are you using version 84? That is 11 versions out of date. Please try v95 or newer.

**Comment by sflorean** [comment]
I was able to reproduce the issue on Pixel 3 (Android 12) and Nightly 1/10 using the link from description. The second video is corrupt, but switching to landscape - resolve the issue.

**Comment by v-kpheng** [comment]
Thanks, @sflorean 🙏 

@kbrosnan, issue is only reproducible on certain phone models.  Both @sflorean and I were able to reproduce on Pixel 3s.
