### ISSUE TITLE
[Bug]: Unable to set punycode visible

### ISSUE THREAD

**Issue by PeopleInside** [mozilla-mobile/fenix#22849]
### Steps to reproduce

1. In Firefox stable for Android there is no option to show punycode domain to avoid phishing and security issue like for the address: https://www.xn--80ak6aa92e.com/
2. about:config is not avaiable so cannot set punycode to true

### Expected behaviour

Be able to activate punycode to true

### Actual behaviour

Unable to set punycode domain to true to avoid phishing and fake urls

### Device name

Xiaomi Poco X3

### Android version

Andorid 11

### Firefox release type

Firefox

### Firefox version

95.1.0

**Comment by cadeyrn** [comment]
Duplicate of #5640.
