### ISSUE TITLE
FNX-5567 ⁃ [Bug] I cannot upload files

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#2284]
## Steps to reproduce
Visit https://imgur.com/upload (make sure it's desktop version of thesite)
Click browse to upload a file

### Expected behavior
It should start uploading. It works in Fennec.

### Actual behavior
It does not upload, no error is shown.

This doesn't work in any site. It fails the same way in https://send.firefox.com/ and on guthub issues (desktop mode github, not mobile github). Fennec works fine in all 3 situations. I have to use Fennec to report Fenix issues :open_mouth:

### Device information
* Android device: OnePlus 5T
* Fenix version: May 4th build but it never worked.
![57192630-3eddfd00-6f3b-11e9-8b4c-991f007134e2](https://user-images.githubusercontent.com/922368/57192764-9d57ab00-6f3c-11e9-845a-43c96a923823.png)

**Comment by ekager** [comment]
Is this the same as #1467 ?
