### ISSUE TITLE
[Bug]: Softkeys are barely visible on specific devices with Android 8/9

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#22846]
### Steps to reproduce

1. Launch Fenix.
2. From Settings > Customize > Theme, change select the Light theme.
3. Return to homescreen and invoke the keyboard.
4. Observe the softkeys are incorrectly displayed.
5. Repeat steps 2-4 with Dark theme for other specific device (e.g. Huawei P9 Lite (Android 8)).

### Expected behaviour

The device buttons should be visible at all times.

### Actual behaviour

The device buttons are barely visible in Light mode when the keyboard is invoked on Huawei P9 Lite (Android 8).
The device buttons are incorrectly displayed in Light mode and Dark mode when the keyboard is invoked on Xiaomi Redmi Note 8T (Android 9).

### Device name

Xiaomi Redmi Note 8T, Huawei P9 Lite.

### Android version

Android 9, Android 8.

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.2

### Additional information

This was reproducible on Nightly 12/14, RC 95.1.0 and Firefox Beta 96.0.0-beta.2. with Xiaomi Redmi Note 8T (Android 9).

![keys](https://user-images.githubusercontent.com/89388888/145994930-30ad8811-825e-4e24-852c-68904133e79a.png)

Huawei P9 Lite:

https://user-images.githubusercontent.com/89388888/145994337-c05b64c2-8df9-4308-8aaa-085af494adf2.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18925)

**Comment by delia-pop** [comment]
A similar issue is reproducible on Firefox Beta 103.0.0-beta.1 with tablet Huawei MediaPad M2 (Android 5.1.1). 
In this case, when light theme is enabled and the keyboard is evoked, the softkeys are not visible in landscape mode. 
Note that even when dark theme is enabled, the softkeys bar turns white with softkeys not visible when rotating the device in landscape mode with the keyboard invoked. 

https://user-images.githubusercontent.com/89388888/176463906-14df36aa-16ef-4669-94d2-551f12470d06.mp4

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807093

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
