### ISSUE TITLE
FNX-5568 ⁃ [Bug] Strange Reader Mode Flickering , Can't Exit Reader Mode

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#2285]
## Steps to reproduce
1. Go to forbes.com
1. Select an article 
1. Swipe up QAS and select Reader Mode
1. Swipe up QAS once reader mode has loaded (notice it has the correct Text Size and Close options)
1. Close the QAS and scroll the page
1. Open QAS -> Notice you now see "Reader Mode" option and not "Text Size" and "Close"
1. Press Back

### Expected behavior
IIUC Should see Close and Text Size options while in Reader Mode
Pressing back should take you to the previous page?

### Actual behavior
Can no longer exit reader mode by QAS.
Have to click back many times (3-4) to get back to article page.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25442310/57198267-ad17c500-6f25-11e9-9314-2eb7edbe95f6.gif)

### Device information
* Android device: Pixel 3
* Fenix version: Nightly 5/6

**Comment by csadilek** [comment]
@ekager I can no longer reproduce this one with the latest A-C snapshots (we landed a bunch of fixes today). Could you verify / close?

/cc @vesta0

**Comment by ekager** [comment]
Can't reproduce anymore, closing
