### ISSUE TITLE
Allow to change the home screen background by tapping on the firefox logo

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#22851]

**Comment by sheikh-azharuddin** [comment]
Nice implementation 👍
These 2 backgrounds color have issue with the text color ...

![Screenshot_20211220-231215104](https://user-images.githubusercontent.com/58127841/146809690-07f8c015-10a4-4b9f-96b2-fec2f9febdc2.jpg)
![Screenshot_20211220-231234021](https://user-images.githubusercontent.com/58127841/146809698-9e756d7e-5d8d-4c1e-a09b-341168d1deac.jpg)

**Comment by pocmo** [comment]
@Amejia481 Two suggestions:
* I found the commit and this issue by looking at the APK size graphs and saw a bump, which seems to be coming from the new wallpaper PNGs. Did you run them through ImageOptim? It looks like we could optimize them.
* I'd consider adding such state either to the screen or app store (based on whether it's needed locally only or globally) and using the known mechanisms to update/observe state. Every `*Manager` creates another source of truth/state and will make it harder to reason about the app's state.

**Comment by Amejia481** [comment]
👋🏽 thanks for the suggestions.

> Did you run them through ImageOptim?

No I didn't, but I will do :) . These images are the final ones, they are only for gathering feedback about the feature.

> I'd consider adding such state either to the screen or app store (based on whether it's needed locally only or globally) and using the known mechanisms to update/observe state. Every *Manager creates another source of truth/state and will make it harder to reason about the app's state.

Yeah that make sense 👍🏽

**Comment by Amejia481** [comment]
@pocmo I filed https://github.com/mozilla-mobile/fenix/pull/22937 for addressing the images optimization.

**Comment by delia-pop** [comment]
Verified as fixed on Beta 99.0.0-beta.5, Nightly 100.0a1. and RC 98.3.0.
