### ISSUE TITLE
Add support for the new storage access permission

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22852]
https://github.com/mozilla-mobile/android-components/issues/10739 will implement the `storage_access` API prompt so we need to also add UI to allow user check the current setting or update it.

**Comment by Mugurell** [comment]
@ QA: To test this https://senglehardt.com/test/dfpi/storage_access_api.html can be used, specifically the 3rd and 4th iframes after changing in about:config:

- `dom.storage_access.auto_grants` to `false`
(to disable Gecko automatically granting the permission)
- `network.cookie.cookieBehavior` to `5`
- `network.cookies.cookieBehavior.pbmode` to `5`
(to enable cross origin cookie blocking)

Please note there is an open issue - https://bugzilla.mozilla.org/show_bug.cgi?id=1746031 the permission not being requested again for previously blocked requests and changing the initial allow/block option.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (2021-12-22) with the steps from the above comment.
Device used: Xioami Mi11 Lite (Android 11).
Closing the ticket as fixed.
