### ISSUE TITLE
Allow Users To Install Security Certificates

### ISSUE THREAD

**Issue by kah0922** [mozilla-mobile/fenix#2286]
Allow Users To Install Security Certificates similarly to Firefox Nightly, as Fenix currently also uses its own certificate store. This allows things like AdGuard For Android and various Anti viruses to function properly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11303)

**Comment by kbrosnan** [comment]
dupe #1168

**Comment by tsvi** [comment]
Also allows for the use of Netspark and other parental protection

**Comment by krzyk** [comment]
It will also allow using corporate websites that frequently use client side certificates to allow users to get in.
Lack of this (https://bugzilla.mozilla.org/show_bug.cgi?id=868370) was a major PITA when using Fennec. I hope Fenix will have that.

**Comment by Xophile** [comment]
Hi!

Any updates regarding this topic?

Thanks!

**Comment by rcdailey** [comment]
At the risk of my comment getting flagged, I'd like to ask when this will be implemented. Haven't seen any updates in 3 months. Thanks for any updates.

**Comment by JpegXguy** [comment]
Yeah I'd like to see it as well, but it doesn't seem high on any priority list. They're looking at stuff such as addon support, but this is essential for me

**Comment by GyokuroT** [comment]
This feature is definitely a must!

**Comment by 3xploiton3** [comment]
Please move to high priority, need for filter ads with https

**Comment by Xophile** [comment]
I would like to have this feature.

Any news about progress or priority changes?

Thanks

**Comment by JSBmanD** [comment]
Will anyone answer about this feature? It's very important for me and I can't use firefox without it.

**Comment by Xophile** [comment]
Any updates?

**Comment by Xophile** [comment]
No one?

**Comment by kbrosnan** [comment]
It requires platform work that is not done. The last several comments have been non-constructive. Locking this to team only.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809964

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
