### ISSUE TITLE
Try switching to Navigation library Kotlin DSL (35ms COLD start improvement?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22862]
For cold start up, we identified the Navigation library takes 35ms on a Moto G5 (via profiler) to inflate the nav graph XML: see https://issuetracker.google.com/issues/181320543. It turns out there is a Kotlin DSL to perform the same operation that theoretically take much less time: https://developer.android.com/guide/navigation/navigation-kotlin-dsl We should implement it as a prototype and measure the difference in start up.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-18933)

**Comment by RotBolt** [comment]
Hey @mcomella can I take stab at this ?

**Comment by RotBolt** [comment]
I Will  be starting a experiment with it

**Comment by RotBolt** [comment]
According to this comment on the original thread (here: https://issuetracker.google.com/issues/181320543#comment4), the navigation library graph work as expected and its measures for one-time startup case only which counters the @mcomella 's statement for using the `heavily cached version of views` for testing.

So if the above comment in the link is correct, then is this not an issue in Fenix layouts themselves?

cc @MarcLeclair @mcomella

**Comment by mcomella** [comment]
I think my original concerns are still valid but I don't fully understand the other commenter. My main concerns were that their benchmarks are unrepresentative of the user experience because 1) they use Jetpack Microbenchmark (but they should use Jetpack Macrobenchmark) and 2) their test inflates an unrealistic navigation graph. The other commenter did not directly address these points. Though I think they may have tried to address 1) but confused the terminology (Jetpack Macrobenchmark and Baseline Profiles).

Since that bug was filed, Google released more information on [Baseline Profiles](https://developer.android.com/topic/performance/baselineprofiles) and we learned that any measurements we take on code bundled in the APK are inaccurate to what users experience on Google Play since they get Cloud Profiles (see the link above). Since the navigation library is bundled with the app, **our measurements in this bug might be inaccurate.**

To ensure we're not doing unnecessary work, I think the next step for this bug is to get more accurate measurements to ensure this is a real performance issue. At a lower level, the next steps are:
1. add support for baseline profiles (that's https://github.com/mozilla-mobile/fenix/issues/25259)
2. Retake our profile/measurements to see if this is a real performance problem or not

I think the fenix team was considering implementing the Baseline Profiles so maybe it would be good to sync up with them. CC @Amejia481

**Comment by RotBolt** [comment]
Ok I think I can take a stab at supporting baseline profile as well 


But IMO, I can still do some priliminary testing on my device as discussed over matrix channel

This work which I would do not need to be merged right away, we can wait for baseline profile issue to be resovlved first and re-visit the things

Let me know your thoughts 

PS: I can work on these two issues baseline and navigation dsl

cc @mcomella @Amejia481

**Comment by Amejia481** [comment]
Thanks for being interested, I will be working on supporting https://github.com/mozilla-mobile/fenix/issues/25259 later, I think it depends on [Jetpack macrobenchmark](https://developer.android.com/topic/performance/benchmarking/macrobenchmark-overview). If you would like to take a look, we could work together, @mcomella shared that there is some previous work in progress more details below. The idea is to start from what we already have to push the functionality forward :)


> For Jetpack macrobenchmark, this [is my WIP branch to add it](https://github.com/mcomella/fenix/tree/host-macrobenchmark) and [this bug has notes on why I failed](https://github.com/mozilla-mobile/fenix/issues/19576#issuecomment-844592766). It looks like I struggled to update dependencies which have probably been updated by now.More generally, Jetpack Benchmark was always difficult to set up – for example, we'd run into issues where it wouldn't find tests, where it would only work on certain API levels (probably due to the storage scope change) or devices (because they probably only test on Pixels), or it wouldn't print the results to Android Studio. Google may have made it much easier since then so it might be worth trying to use their instructions directly rather than building off my change.If you need to access Jetpack microbenchmark, we integrated it but slightly differently than they recommend. [We have a <fenix>/tools/run_benchmark.py script](https://github.com/mozilla-mobile/fenix/blob/main/tools/run_benchmark.py) to run it because running it in Android Studio was broken for us at the time. [Marc had a WIP sample test](https://github.com/mozilla-mobile/fenix/pull/22168) but ran into issues, also related to dependency versions, I think.Let me know if you have questions! I'm also happy to jump on a call to clarify or go into more details.

**Comment by RotBolt** [comment]
Sure, I have started the navigation kotlin dsl experiment. I can do that independently. Meanwhile I could work with you on #25259 for baseline profile. 
Let me know when can we sync @Amejia481

**Comment by Amejia481** [comment]
> Sure, I have started the navigation kotlin dsl experiment. I can do that independently. Meanwhile I could work with you on #25259 for baseline profile. Let me know when can we sync @Amejia481

Awesome!

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807347

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
