### ISSUE TITLE
[Bug]: latest firefox nightly crashing

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22877]
### Steps to reproduce

Open GitHub firefox page 
Try to file a new bug
Firefox crashing

Similarly when trying to login to some site it is crashing

### Expected behaviour

Firefox should not crash
I feel this is caused by the recent commit
https://github.com/mozilla-mobile/fenix/commit/33af7d872967a5507b02083e07a5625102c5736a

### Actual behaviour

Crashing
![Screenshot_20211216-123555657](https://user-images.githubusercontent.com/58127841/146324117-c958b01d-6c40-49dc-969a-75fffb8cc07c.jpg)

### Device name

asus rog3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

080460a5-b4e9-4071-a7af-b7708007f080
java.lang.IllegalStateException: Already locked by mozilla.components.service.sync.autofill.AutofillCrypto@66f8f1f
----
java.lang.IllegalStateException: Already locked by mozilla.components.service.sync.autofill.AutofillCrypto@66f8f1f
	at kotlinx.coroutines.sync.MutexImpl.lock(Mutex.kt:23)
	at mozilla.components.concept.storage.KeyManager.getOrGenerateKey$suspendImpl(KeyManager.kt:4)
	at mozilla.components.concept.storage.KeyManager.getOrGenerateKey(Unknown Source:0)
	at mozilla.components.service.sync.autofill.GeckoCreditCardsAddressesStorageDelegate.decrypt(GeckoCreditCardsAddressesStorageDelegate.kt:5)
	at mozilla.components.browser.engine.gecko.autofill.GeckoAutocompleteStorageDelegate$onCreditCardFetch$1.invokeSuspend(GeckoAutocompleteStorageDelegate.kt:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

**Comment by sheikh-azharuddin** [comment]
Interestingly issue fixed post reinstalling the app..weird though 😅
Hence closing the case

**Comment by csadilek** [comment]
Thanks for reporting! 

Adding Sentry links:
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16146605/
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16146651/

**Comment by Amejia481** [comment]
Sentry issue: [FIREFOX-NIGHTLY-E5D](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16146651/?referrer=github_plugin)

**Comment by Amejia481** [comment]
cc @grigoryk it looks like it maybe related to https://github.com/mozilla-mobile/android-components/pull/11371/

**Comment by kbrosnan** [comment]
[Crash stats link](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A%20at%20kotlinx.coroutines.sync.MutexImpl.lock%28Mutex.kt%3A23%29&version=97.0a1) this looks pretty bad for the affected users.

**Comment by parcelcat** [comment]
Seems to be fixed as of version code 2015851907, which is currently the latest Nightly version on Google Play. Thanks for the quick fix.

**Comment by benyaminl** [comment]
> Seems to be fixed as of version code 2015851907, which is currently the latest Nightly version on Google Play. Thanks for the quick fix.

Please close this @parcelcat

**Comment by sheikh-azharuddin** [comment]
Seems issue is fixed..shall I close it?

**Comment by benyaminl** [comment]
@sheikh-azharuddin yes sire.

**Comment by sheikh-azharuddin** [comment]
Today faced 2 crashes..not similar to previous ones but probably some other bug

dadb6d2e-3da0-4f22-817f-0f7c1b486871
<native crash>
----
<native crash>

**Comment by benyaminl** [comment]
> 

What site? I'm not facing any crash, probably I have not update to Today Build
