### ISSUE TITLE
Investigate default engine metrics and align with desktop

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#22879]
_Originally posted by @Standard8 in https://github.com/mozilla-mobile/fenix/issues/22787#issuecomment-995539998_ :

> As I commented in slack, we would like to get to reporting submission urls the same way as desktop, if it is more appropriate to move this out to a separate issue, please do.
> 
> Desktop currently records the url if:
> 
> * The search engine is one of the ones Firefox provides.
> * The hostname is the same domain as Firefox provides.
> * The hostname matches one of the well known search domains.
> 
> [Code is here](https://searchfox.org/mozilla-central/rev/dc323d0d9a3b722ca8ff0d1b2b752e5bd00dab9b/toolkit/components/search/SearchService.jsm#2351-2419).
> [Original bug that added the code](https://bugzilla.mozilla.org/show_bug.cgi?id=1164159).
> 
>

**Comment by mcarare** [comment]
Upon testing this, it seems that the name and the submission URL are not replaced with "custom" for user-added engines.
Could someone with access to running queries for this data source confirm that we have such values recorded? Thank you!

**Comment by sflorean** [comment]
Verified as fixed on Nightly build with Pixel 3 (Android 12). _Custom_ is displayed for custom search engines added as default.
