### ISSUE TITLE
Renew telemetry for February

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#22870]
[Renewal doc](https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit#)

Remove or renew the metrics in `metrics.yaml` that will be expiring in February.

- [x] update on nightly
- [x] update on beta 97 before Feb 1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18937)

**Comment by mcomella** [comment]
Note: these expire Feb. 1.

**Comment by eliserichards** [comment]
Meeting with Ashley/Kevin tomorrow to get product input on renewals
