### ISSUE TITLE
[Bug]: about:memory is very crashy

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#22880]
### Steps to reproduce

Go to about:memory
Tab the Measure button a few times
Fenix crashes about one time in four measurements.

Nightly 

### Expected behaviour

No crashes! 

### Actual behaviour

Frequent crashes! 

### Device name

Galaxy M32

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 (Build #2015851371), 8092b0399+

**Comment by sflorean** [comment]
I was able to reproduce this on latest Nightly build, with Samsung A32 (Android 11).
Crash: https://crash-stats.mozilla.org/report/index/cb23e6d0-d144-4023-9fd6-8660b0211223

**Comment by makotokato** [comment]
I believe that [this is fixed by 97](https://bugzilla.mozilla.org/show_bug.cgi?id=1747116) if your crash data is same as https://github.com/mozilla-mobile/fenix/issues/22880#issuecomment-1000235599

**Comment by makotokato** [comment]
@sflorean could you verify this on 97 beta?

**Comment by Cheap-Skate** [comment]
Yes this seems fixed for me on today's Nightly. Let's wait until @sflorean confirms before closing.

Thanks
