### ISSUE TITLE
RTC switch cameras repeatedly blocks browser

### ISSUE THREAD

**Issue by vakya** [mozilla-mobile/fenix#22884]
### Steps to reproduce

1. Open firefox in android a put the url: https://webrtc.github.io/samples/src/content/devices/input-output/
2. By changing the "Video Source" field, you must change the camera.
3. Then, allow the use of camera but not to remember.
4. Repeat step 2 a few times. It depends on the mobile between 5 and 20.
The process is OK. 
5. But now, press remember this site and to allow.
6. Change de camera.
Apears in console: navigator.MediaDevices.getUserMedia error: Starting videoinput failed AbortError main.js:87:11
The camera is locked

### Expected behaviour

The camera works.

### Actual behaviour

The camera is locked

### Device name

SONY XPERIA XZ Premium and other devices.

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

95.1.0 (Build #2015848803)

### Device logs

navigator.MediaDevices.getUserMedia error: Starting videoinput failed AbortError main.js:87:11

### Additional information

In my device Xiaomi Poco F3  with Android 11 and MIUI 12.5.18 it happens very rarely

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18945)

**Comment by leoshusar** [comment]
+1, This also affects our Flutter app.
The official Flutter camera library enumerates all cameras details by asking permissions for all of them, then stops all streams and then user can select camera by resolution etc.

Due to this bug this fails 100 % of the time, that means my Flutter app doesn't work at all.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812067

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
