### ISSUE TITLE
[Bug]: Updated Synced tabs are not displayed on Android after sync

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#22895]
### Steps to reproduce

Prerequisites: have 2-3 pages opened on both Android and Desktop. 

1. Log in with the same account on Android & Desktop.
2. Perform a sync on both devices.
3. Open 1-2 different pages on Desktop (same tabs, not new tab).
4. Perform a sync on both devices.
5. On Android, open tabs tray - > Synced tabs.
6. Check the updated tabs.

### Expected behaviour

The pages are updated after sync.

### Actual behaviour

The tabs are not updated, the pages opened previously (prerequisites) are displayed. 

### Device name

Sony Xperia

### Android version

6.0.1

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18949)

**Comment by jdragojevic** [comment]
We have a desktop bug fix in Fx98 + SYNC-3018 landing in Fenix 99 - this should be able to be retested - with those versions.

**Comment by sflorean** [comment]
Tested on latest Fenix versions, and this is no longer reproducible. Closing as fixed.

**Comment by sflorean** [comment]
This is still reproducible on 100.beta.5 - with Nokia 6 (Android 7.1.1).
