### ISSUE TITLE
FNX-5571 ⁃ [Bug] Undo from close tab snackbar does not bring back your tab if used multiple times

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2289]
## Steps to reproduce
1. Open any page.
1. Tap on the tab counter.
1. Close the tab.
1. In the snackbar tap on undo.
1. Repeat steps 3 and 4.

### Expected behavior
The tab is restored again.

### Actual behavior
The tab is no longer restored.

### Device information
* Android device:
  * Samsung Galaxy S8 (Android 9)
  * Google Pixel (Android 9)
  * HTC Desire 820 (Android 6.0.1)
* Fenix version: 5/6

![20190506](https://user-images.githubusercontent.com/17178945/57212709-4231c100-6fed-11e9-881b-81e207c6590e.gif)UNITO-UNDERSCORE!105118!

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/14 build.
Samsung Galaxy S8 (Android 9)
HTC Desire 820 (Android 6.0.1)
