### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by WinHotFix** [mozilla-mobile/fenix#22892]
## Site with issue and any steps to reproduce
launching Mozilla Firefox android
opening a new tab
I go to the website youtube.com (without logging in)
I choose a video to watch
I start watching videos, (the incoming Internet speed is low, in the best layouts, the maximum can be viewed in 720p resolution at 30fps; in fact, 480p and then lower; because there are several devices on the local network.)
the video is played with a resolution of 480p, but the rest of the viewing area is painted in a green background. ((I.e. the current viewing area is 1280x720 , the video is located in the upper left corner at a resolution of 480p or in lower resolutions, but the remaining part of the viewing area is painted in a green background)

in others , the situation
if you open in full-screen mode, the field of view is already 1920x1080
all the same, the video is located in the upper left corner at a resolution of 480p or in lower resolutions, but the remaining part of the viewing area is painted over in a green background
but sometimes this problem does not manifest itself, it is worth pausing playback, then the problem occurs again.

In other browsers, Chrome android works without problems

Device name
Mini M8S II

Android version
Android 6.0.1

Firefox release type
Firefox

Firefox version
starting approximately from version 79.0 to the latest at the moment 95.2.0

Device logs
No response

**Comment by kbrosnan** [comment]
duplicate bz-1731980

**Comment by Darkspirit** [comment]
If you open about:support in the address bar, and search for "Compositing" (Main menu > Search in page), does it say "WebRender" or "WebRender (Software OpenGL)"?
