### ISSUE TITLE
Use third party CA certificates doesn't work in stable (Android)

### ISSUE THREAD

**Issue by Gitoffomalawn** [mozilla-mobile/fenix#22906]
### Steps to reproduce

First you'll need to prepare a server with a CA and installed signed certificate. Then import the CA certificate to the Trusted Credentials in Android:
1.Create a CA and self-signed certificate as explained [here](https://gist.github.com/Soarez/9688998).
2. Install the server certificate on your server
3. Install the CA certificate on your mobile device (Settings -> Encryption & credetials -> Install from storage)

After that, you should be able to use that installed CA to access your server without accepting security exceptions:
1. Open Firefox
2. Click on the three dots to go to the menu, en go to 'Settings'
3. Go to 'About Firefox'.
4. Tap the Firefox logo 7 times to enable the debug menu options
5. Go back to the settings menu, and scroll down to 'Secret Settings' (third from the bottom), and open it
6. Set the option 'Use third party CA certificates' to be on
7. Browse to server address

### Expected behaviour

The website should open without producing security errors after restarting Firefox.

### Actual behaviour

The website keeps producing security exceptions just as if the CA hasn't been installed. Following these same steps on Firefox Nightly produces the expected behavior. This means the setting in stable is not working properly.

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

95.1.0

### Device logs

No logs available.

### Additional information

No additional information available.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18956)

**Comment by uok** [comment]
this issue is still valid (v107.1)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812068

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
