### ISSUE TITLE
Closing an old active tab sometimes causes an inactive tab to open

### ISSUE THREAD

**Issue by 994PhiJ** [mozilla-mobile/fenix#22904]
### Steps to reproduce

I've had some tabs open for a very long time and on the recent update many (not all) of them have been marked as inactive.  If I close a tab that is not selected (the blue box is around another tab) then it closes as expected.  If I have an old (but active) tab that is currently selected, and I close it, then it will close the selected tab but replace it with a tab from the inactive tabs list.

My best guess at steps to reproduce:

1. Open loads of tabs.
2. Wait for these to become inactive
3. Open more tabs
4. Select a tab in the middle of the list of inactive tabs to make it active and view it.
5. Without switching to a different tab, close the current one (which is very old).

### Expected behaviour

What should happen: the tab closes and your selection moves to one of the active tabs.

### Actual behaviour

What happens to me: the tab closes and one of the inactive tabs opens in its place.

### Device name

Moto G4

### Android version

Anroid 7.0

### Firefox release type

Firefox

### Firefox version

95.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18955)

**Comment by LaviniaL99** [comment]
Hello @994PhiJ 
Thanks for your report!
I tested the above issue on the latest Nightly build 98.0a1 and latest release version RC 96.1.1 and I was not able to reproduce the issue.

Devices used:

- Samsung S10E -> Android 10
- Galaxy A32 5G-> Android 11

Can you please confirm if you are still able to reproduce the problem on the latest builds? If yes, please attach a video.
Thanks!

**Comment by 994PhiJ** [comment]
Here's a screen record.  I have an old browser open with lots of tabs (some of which I want to keep) so I can show you the issue but can't wipe my tabs and try to start from scratch: I can only guess at steps to reproduce from an empty browser.  But starting with my browser as it is, in the video I open the first tab from the archive, if it is selected when I close it then it is replaced by the next tab from the archive.  If it is not selected when I close it, then it closes properly.  This is firefox 96.3.0

https://drive.google.com/file/d/1gyq4XrDl-uB3tRIDSLK2t6MQon9Rmh6L/view?usp=sharing

![Screenshot_20220130-200254](https://user-images.githubusercontent.com/10966497/151715678-e9748b13-b0df-46c7-b64e-ac7d148c9bca.png)

![Screenshot_20220130-200324](https://user-images.githubusercontent.com/10966497/151715680-85457893-b773-4581-92dc-12af81a518fd.png)

**Comment by LaviniaL99** [comment]
Hello @994PhiJ 

I was able to reproduce the issue based on your recording ->  latest Nightly build 98.0a1 and latest RC build 96.3.0.

Devices used:

- Samsung S10E -> Android 10
- Galaxy A32 5G-> Android 11

**Comment by 994PhiJ** [comment]
This issue is still happening for me in version 107.2.0

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812066

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
