### ISSUE TITLE
Clear address bar button is way too small

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#22900]
### Steps to reproduce

Tap on address bar

### Expected behaviour

The "clear address bar" button should be reasonably sized

### Actual behaviour

The "clear address bar" button is way too small. Surely this is not by design? Screenshot comparison with Chrome below (red arrow is Fenix, green arrow is Chrome)
![FenixClearURLbutton](https://user-images.githubusercontent.com/47801466/146609316-3518f053-04e5-4942-a258-0441d48a5c50.png)

### Android version

12

### Firefox release type

Firefox Nightly

### Firefox version

97

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18953)

**Comment by SoftVision-LorandJanos** [comment]
Hi @willfs84 ! Thank you for your report!
I can confirm the size of the button is as you described.
However this will not be considered as a bug, as it was the intended size.
I will switch the bug label to a feature request one.

**Comment by willfs84** [comment]
Are you sure they intended for it to be this small? For example, the size of the "X" inside it doesn't even meet accessibility minimum size for icons and text (a lot of people won't be able to clearly, easily see that it's an X inside the tiny circle button)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814154

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
