### ISSUE TITLE
[Bug]: No "Paste" button when long pressing the address bar in unfocused state

### ISSUE THREAD

**Issue by upsuper** [mozilla-mobile/fenix#22902]
### Steps to reproduce

1. copy some random text (not url) somewhere
2. open Firefox Android, keep address bar unfocused
3. long press the address bar
4. see the contextual toolbar shown above the address bar

### Expected behaviour

There should always be a contextual toolbar showing at least "Paste"

### Actual behaviour

There is no "Paste" button

### Device name

Sony Xperia 1

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.2

### Additional information

When the text copied is a URL, there is "Paste" and "Paste and Go" in the contextual toolbar, but I would expect there always to be "Paste", because I often want to paste search terms onto the address bar to start searching. I think this is a recent regression.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18954)

**Comment by Oymate** [comment]
Just as upsuper said, I like to paste and go with an unknown word in the search bar

**Comment by LaviniaL99** [comment]
Hello @upsuper 

Thanks for your report!
I tested the above issue on the latest Nightly 98.0a1 (2022-01-20) and latest Beta 97.0.0 -beta 2 (2022-01-14) and I was able to reproduce the issue.

**Devices used:**

Samsung S10E -> Android 10
Samsung Galaxy A32 5G -> Android 11

There is a similar issue raised about "Paste" button,  but the flow is a little differently:https://bugzilla.mozilla.org/show_bug.cgi?id=1748468

**Comment by g-l-n** [comment]
I have also experienced this issue both on my Samsung a02, android 11 in firefoxnightly and my pixel xl android 10 firefixbeta. It only arises after long period of use, and the only way to fix it is to uninstall and reinstall the phone and that fix is only temporary. This is a serious issue and needs to be addressed. 
![20220215_160931](https://user-images.githubusercontent.com/99520861/154049260-ad0351ca-cc95-4457-8f61-a7ac6298a74d.jpg)
![20220215_160741](https://user-images.githubusercontent.com/99520861/154049271-f695b94b-7af6-43f6-b32b-a510f840cf3d.jpg)
![Screenshot_20220215-144619_Firefox Nightly](https://user-images.githubusercontent.com/99520861/154049281-11ad9b0b-eba8-490e-afc0-6425938d0429.jpg)

**Comment by grigoryk** [comment]
This should be fixed by https://github.com/mozilla-mobile/fenix/pull/24294 - it adds `Paste` for non-url clipboard contents.

**Comment by Oymate** [comment]
What about 'paste and go'? or will that only be for url's
