### ISSUE TITLE
Open tabs are not scrolled

### ISSUE THREAD

**Issue by pivasikkost** [mozilla-mobile/fenix#22915]
Open tabs are not scrolled, instead the entire curtain with open tabs leaves.
I use Mozilla 95.1.0 (Build #2015848803) on my Samsung Galaxy S7 SM-G930V with Android 8.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18960)

**Comment by pivasikkost** [comment]
This does not always happen, now this glitch was observed for 15 minutes, but it disappeared.

**Comment by sflorean** [comment]
@pivasikkost can you please attach a video of the issue?
