### ISSUE TITLE
[Bug] Javascript URLs stopped working

### ISSUE THREAD

**Issue by bigConifer** [mozilla-mobile/fenix#22914]
### Steps to reproduce

Since Fenix [v95.1.0](https://github.com/mozilla-mobile/fenix/releases/tag/v95.1.0) (Build #2015848801, AC: 95.0.13) Javascript URLs that are on web pages have stopped working. When you ~click or~ long press them, nothing happens.

### Expected behaviour

The bookmarklet gets executed when clicking on a Javascript link, resp. a context menu (with "copy link" and "share link" entries) pops up when long pressing. 
The last build with this behavior is Fenix [v95.0.0-beta.6](https://github.com/mozilla-mobile/fenix/releases/tag/v96.0.0-beta.1) (Build #2015847753, AC: 95.0.10).

### Actual behaviour

~Javascript URLs fortunately still work via awsomebar when bookmarked, but embedded ones on a web page no longer do.~

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.3

**Comment by bigConifer** [comment]
Comparing the Versions I came across the following commit: Improve loading URLs (https://github.com/mozilla-mobile/fenix/commit/4ebfb892ceddaec445ada24eebee4920b7bfdec9,
https://github.com/mozilla-mobile/android-components/commit/a2277bc2fffc38d13137bef5ffaa579c558954df). @Amejia481
As it seems to be the breaking one and I didn't find any comment on this, could you please briefly describe what it was intended for? 

I think Javascript URLs on web pages should continue to be supported and hope that the bug can be fixed relatively easily.

**Comment by Amejia481** [comment]
Thanks @bigConifer for the report, we will take a look and report back.

**Comment by Amejia481** [comment]
After checking, I think we are in line with Firefox desktop.

* Clicking on regular link still works.
* Clicking on a bookmark that contains JS URLs still works.
* Long press doesn't show a contextual menu, similar to desktop right click doesn't show an option to open the link. 

You can give it a try on https://csadilek.github.io/test12.html

**Comment by bigConifer** [comment]
Thanks for the quick response, @Amejia481.

You're right, I missed that clicking Javascript URLs still works as expected.
However it looks like there are two separate bugs and somehow one of them even makes ALL links on the page unclickable.

[Context Menu]

I would not agree that we are in line with Firefox desktop. It's not about an option to open the link but about the "copy link" option. This is of course available in Firefox desktop and was it in Fenix until v95.1.0.

<p>
  <img src="https://user-images.githubusercontent.com/64743731/147020501-c055e2b9-0cb5-4207-a55c-0b26704e1250.jpg" width="45%" title="Fenix 95.0.0-beta.6"/>
  <img src="https://user-images.githubusercontent.com/64743731/147020570-a978916a-a6b6-46f7-ad5f-b6c4b6aa599c.jpg" width="45%" title="Firefox 95.0.2"/> 
</p>

[Awesomebar]

Little more investigation revealed that already since Fenix v94.0.0-beta.1 (Build #2015838097, AC: 94.0.1) the execution of Bookmarklets via the Awesomebar is extremely limited and buggy.
I filed up a new bug report for it (https://github.com/mozilla-mobile/fenix/issues/22946)

**Comment by Amejia481** [comment]
@bigConifer I think we could close this ticket and continue the conversion on the new one

**Comment by bigConifer** [comment]
> I think we could close this ticket 

Hm, but this one here still contains the relevant information for the context menu bug, which revealed as completely independent from https://github.com/mozilla-mobile/fenix/issues/22946.

@Amejia481, if you want, I can open a new one regarding only the context menu ...
