### ISSUE TITLE
Reopen https://github.com/mozilla-mobile/fenix/issues/17093

### ISSUE THREAD

**Issue by henricook** [mozilla-mobile/fenix#22918]
https://github.com/mozilla-mobile/fenix/issues/17093 has been closed incorrectly and I can't think of a better way to draw attention to this issue, tagged moderators appear not to be reading their notifications.

**Comment by kbrosnan** [comment]
We are not keeping individual issues open for specific extensions. We track the extension APIs that are needed at https://bugzilla.mozilla.org Geckoview::WebExtensions

**Comment by AnderssonPeter** [comment]
@kbrosnan it has been working in nightly since https://github.com/mozilla-mobile/fenix/issues/17093#issuecomment-796572498 if I'm reading this correctly, so it should not be a problem at the API level?
