### ISSUE TITLE
Tab shifting when switching tabs

### ISSUE THREAD

**Issue by ProperBrgdbald** [mozilla-mobile/fenix#22929]
### Steps to reproduce

0. Tab List set to Grid view
1. Have multiple tabs open (5-6 tabs)
2. Press Tab button to get to Tab List
3. Select tab 3 or 4 to view this tab
4. Press Tab button to get to Tab List
5. observe that tab 3 and 4 are placed on top of Tab List, then view scrolls up one row of tabs after a small delay
6. When attempted from tab 5 or 6, view places Tab 5 or 6 in mid scroll, but does not move view
7. Steps 0-5 attempted with 7 or 8 tabs, it requires being on Tab 5 or 6 to reproduce this behaviour.

### Expected behaviour

Tabs should not unexpectedly scroll

### Actual behaviour

Tabs unexpectedly scroll (on second-last row of tabs in Grid view)

### Device name

Motorola G4 Play

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

95.2.0

### Additional information

Also experienced with Motorola G 1st Gen using Android 7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18968)

**Comment by SoftVision-LorandJanos** [comment]
Hi @ProperBrgdbald. Thank you for your report!
I couldn't reproduce the issue you described on the latest builds:
- latest Nightly 97.0a1 (2021-12-29).
- latest Beta (96.0.0-beta5).
- latest Release (95.2.0).

Devices used:
- Xiaomi Mi11 Lite (Android11).
- Samsung Galaxy Tab S3 (Android 9).
- Motorola Nexus 6 (Android 7.1.1).

Could you upload a video about your issue, please? Thank you!

**Comment by ProperBrgdbald** [comment]
Videos attached using Nightly 97.0a1 on Android 7 and Android 10.

Process shows explicitly up to steps 5 in original posting:
0. Tab List set to Grid view
1. Have multiple tabs open (5-6 tabs)
2. Press Tab button to get to Tab List
3. Select tab 3 or 4 to view this tab
4. Press Tab button to get to Tab List
5. observe that tab 3 and 4 are placed on top of Tab List, then view scrolls up one row of tabs after a small delay

https://user-images.githubusercontent.com/64764903/147810322-a0ca9400-7c93-4570-81d3-69ca4ebe886c.mp4

https://user-images.githubusercontent.com/64764903/147810326-da227dd2-315e-4770-ae5b-32a2afcb7181.mp4

Shifting that occurs is not due to finger dragging; third video shows proves no finger dragging occurs.

https://user-images.githubusercontent.com/64764903/147810308-fb66ea6b-c88c-4627-8bf2-addf8254f5e0.mp4

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 98.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 99.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 100.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 101.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 102.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 103.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 104.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 105.0a1. May be related to issue #26371

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 106.0a1. May be related to issue https://github.com/mozilla-mobile/fenix/issues/26371

**Comment by issue-dispenser** [comment]
I have been able to reproduce this bug in Android 8.0 and Android 12 since switching over to Fenix (past year or so).

**Comment by bigConifer** [comment]
https://github.com/mozilla-mobile/fenix/issues/26371 is about loosing the focus at all and scrolling to the top of the list, not about scrolling one row up in grid view.

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 107.0a1

**Comment by ProperBrgdbald** [comment]
Issue appears to not persist in Android 7 and Android 10 builds 109.0a1. Will check again next version to confirm.

**Comment by ProperBrgdbald** [comment]
When switching applications and then re-attempting to switch tabs in Nightly 109.0a1 in Android 7 and Android 10

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812863

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by ProperBrgdbald** [comment]
Unsure why this was moved to Bugzilla, but accepted.

When switching applications and then re-attempting to switch tabs in Nightly 111.0a1 in Android 7 and Android 10.

**Comment by cadeyrn** [comment]
> Unsure why this was moved to Bugzilla

Please see https://github.com/mozilla-mobile/fenix/issues/26855.
