### ISSUE TITLE
[Bug]: Pasting "about:<term>" pastes only "<term>"

### ISSUE THREAD

**Issue by ProperBrgdbald** [mozilla-mobile/fenix#22928]
### Steps to reproduce

1. Enter about:telemetry into the URL bar (without quotation marks
2. Select this value, and copy into clipboard (hold and copy)
3. clear the URL bar
4. Paste into the URL bar

### Expected behaviour

"about:telemetry" should appear

This value appears when pasting into other applications.

### Actual behaviour

"telemetry" appears.

If quotations are used ("about:telemetry"), the full value of ""about:telemetry"" appears.

### Device name

Motorola G4 Play

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

95.2.0

### Additional information

Also experienced with Motorola G 1st Gen using Android 7

**Comment by sflorean** [comment]
I was able to reproduce this on latest Nightly build with Samsung A32(Android 11).

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 98.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 99.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 100.0a1

**Comment by Alexandru2909** [comment]
Hi @ProperBrgdbald, I believe this is the intended behavior. Fenix is [filtering](https://github.com/mozilla-mobile/fenix/blob/94a543a4032feac18a90e3d1449587631a9595fe/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt#L93) the urls containing `about:`, `chrome://` and `resource://` [from the clipboard](https://github.com/mozilla-mobile/fenix/blob/9f57b2408295794765ed3e1679dc8205e82ba1b0/app/src/main/res/values/arrays.xml#L39). For more details you can follow the discussion [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1664746).

**Comment by ProperBrgdbald** [comment]
> Hi @ProperBrgdbald, I believe this is the intended behavior. Fenix is [filtering](https://github.com/mozilla-mobile/fenix/blob/94a543a4032feac18a90e3d1449587631a9595fe/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt#L93) the urls containing `about:`, `chrome://` and `resource://` [from the clipboard](https://github.com/mozilla-mobile/fenix/blob/9f57b2408295794765ed3e1679dc8205e82ba1b0/app/src/main/res/values/arrays.xml#L39). For more details you can follow the discussion [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1664746).

Thank you for finding this.

Closed per https://bugzilla.mozilla.org/show_bug.cgi?id=1664746 with the following notes:

- "about" is being filtered in mobile only as part of a blocklist on mobile.
- From [Daniel Veditz [:dveditz]](https://bugzilla.mozilla.org/user_profile?user_id=1689): "On Desktop we strip the protocol on paste (whether manual or paste&go) from javascript urls. We should definitely make sure we're doing that on Fenix, too."
- "about" is not stripped upon pasting or using "Paste & Go" on the Desktop (outside the scope of this report, stated here for comparison to Fenix and discussion had in the Bugzilla link).
