### ISSUE TITLE
[Bug]: 3-dot menu unexpectedly gets wider when signed into sync

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#22924]
### Steps to reproduce

1. Sign into sync
2. Go back to a loaded web page
3. Hit 3-dot menu

### Expected behaviour

3-dot menu remains the same width:
![device-2021-12-20-164000](https://user-images.githubusercontent.com/759372/146846971-b03b9bd1-a9e4-44d2-9d09-9645efad5476.png)

### Actual behaviour

3-dot menu expands horizontally to fit the email address of the signed in account (my email is redacted in the photo):
![device-2021-12-20-163859](https://user-images.githubusercontent.com/759372/146847014-b85077bd-086d-4703-829f-0d0610f7a848.png)

I think there are two competing design constraints:
1. we don't want the menu to take up the whole screen so you retain more of your browsing context (and arguably it looks nicer)
1. this menu needs to be able to expand based on different locales

However, it seems weird to expand due to the signed in account's email address that I probably don't need to see the entirety of on this menu. It looks awkwardly wide and isn't providing much more information.

I think it's reasonable to close this as working-as-designed or not-worth-our-time though.

### Device name

Moto G5

### Android version

?

### Firefox release type

Firefox Nightly

### Firefox version

Nightly: 97.0a1 12/20

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18964)

**Comment by Oymate** [comment]
Reproducable on firefox but not tor browser

**Comment by Oymate** [comment]
Maybe use the profile name?

**Comment by Oymate** [comment]
Not stale
