### ISSUE TITLE
[Bug]: Text Searches do not consistently launch

### ISSUE THREAD

**Issue by ProperBrgdbald** [mozilla-mobile/fenix#22927]
### Steps to reproduce

1. Open tab with text (Tab X)
2. Select text to search (by holding)
3. Select Search (or Private Search)
4. Navigate back to Tab X
5. Press and hold on text (to search again)
6. Select Search (or Private Search)
7. Observe no action occurs

In addition to above
8. Open new tab (Tab Y) with text to search
9. Select text in Tab Y
10. Press and hold on text
11. Select Search (or Private Search)
12. Observe new tab opens
13. Navigate to Tab X
14. Observe that a new search tab opens from previous Tab X search (from step 6)

Behaviour does not occur in Step 6,7 if selection changes (increasing or decreasing by a character), will occur if selection changes, and then the same characters are reselected

### Expected behaviour

Every time Search/Private Search is selected from steps 2 and 3, or 5 and 6, a new tab with the search is expected to occur (like on Desktop Firefox)

### Actual behaviour

Repeated search of same terms does not initiate a search.

Later re-selecting a tab a search failed to initiate from causes the search to occur unexpectedly.

### Device name

Motorola G4 Play

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

95.2.0

### Additional information

Also experienced with Motorola G 1st Gen using Android 7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18966)

**Comment by sflorean** [comment]
@ProperBrgdbald i wasn't able to reproduce this on latest Nightly build with Samsung A32 (Android 11). 
Please check again on Nightly, and add a video of your issue.

Thank you!

**Comment by ProperBrgdbald** [comment]
Testing on 97.0a1 video captures attached.
Found that the following do not allow for the same search to be performed in the same tab:
- Refreshing the tab
- Closing the tab, then undoing tab close

Replicating requires closing the tab used for search, and re-navigating back to the test page

https://user-images.githubusercontent.com/64764903/147296267-c3d7fc46-6183-48c8-b74d-d878c12f3e4e.mp4


https://user-images.githubusercontent.com/64764903/147296270-a6f2a095-448a-4139-a3c7-d0be7608d328.mp4

.

**Comment by ProperBrgdbald** [comment]
When re-recording both inability to re-launch a search (not triggered), and showing when a search would unexpectedly launch, I found that switching to another application and then switching back will trigger the launching of the delayed search.

"search not triggered" means the search was attempted but did not occur.
"unexpected search" means a tab was revisited which caused something to trigger the search that did not occur when "search not triggered"

https://user-images.githubusercontent.com/64764903/147330696-7b659efb-eb81-4d77-9cfb-c958d5de7e06.mp4


https://user-images.githubusercontent.com/64764903/147330701-e5b07a4b-df39-4e9b-ae94-35458c8264e6.mp4


https://user-images.githubusercontent.com/64764903/147330703-f0c62878-4194-41fb-9507-2147f601539a.mp4


https://user-images.githubusercontent.com/64764903/147330691-253e9bfb-1696-4e17-9e03-70cd4bcffd5c.mp4

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 98.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 99.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 100.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 101.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 102.0a1

**Comment by ProperBrgdbald** [comment]
Issue persists in Android 7 and Android 10 builds 103.0a1

**Comment by ProperBrgdbald** [comment]
Issue appears fixed in Android 7 and Android 10 builds 104.0a1; launching similar search from same tab launches consistently. Will check one more version next month before closing.

**Comment by ProperBrgdbald** [comment]
Issue appears fixed in Android 7 and Android 10 builds 105.0a1; launching similar search from same tab launches consistently.
