### ISSUE TITLE
[Bug]: Firefox homepage's initial scroll position is random on Android 8.1 device

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#22939]
### Steps to reproduce

1. Make sure Firefox is configured to open to the Firefox homepage.
2. Cold or warm start Fenix on a device running Android 8.1.

(I can reproduce this bug in Firefox 95, Beta 96, and Nightly 97 on my Moto G5 Plus running Android 8.1.)

### Expected behaviour

The homepage should either always start at the top or its previous scroll position.

### Actual behaviour

* In a cold app start, the homepage is always positioned at "Stories by topic" near the bottom of the page.
* In a warm app start after my recent homepage scroll position was showing the "Recently visited" section or above, the homepage will start at some random position near the second row of Top Sites (with the first row of Top Sites usually off screen).
* In a warm app start after my recent homepage scroll position was showing below the "Recently visited" section (so only showing the "Thought-provoking stories" or "Stories by topic" sections), the homepage usually restores that scroll position correctly.

@rocketsroger can reproduce this bug in an emulator running Android 8.1, but not Android 10. TBD whether this bug also affects Android 5.0-8.0 or Android 9.

This is a bug where different data sources are racing.

Similar to https://github.com/mozilla-mobile/fenix/issues/22402

### Device name

Moto G5 Plus

### Android version

Android 8.1

### Firefox release type

Firefox Nightly

### Firefox version

97

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18973)

**Comment by rocketsroger** [comment]
There is one case when this can also be reproduce in Android 10+.  When the user first starts using Fenix, after they selected their Theme and Toolbar position, home is not scrolled to the top.  I'll also fix it with this issue.

**Comment by rocketsroger** [comment]
Tried different workarounds and they all causes regression in other areas.  The best solution for this issue is to implement https://github.com/mozilla-mobile/fenix/issues/22755.
