### ISSUE TITLE
[Bug]: background color of new private window is broken

### ISSUE THREAD

**Issue by orangepizza** [mozilla-mobile/fenix#22931]
### Steps to reproduce

1. open private tab

### Expected behaviour

background has gradation in it, which color matchs with buttom toolbar.

### Actual behaviour

background color is flat, neon violet , no background gradation
![Screenshot_20211221-154452_Firefox Nightly](https://user-images.githubusercontent.com/23009540/146884584-e2972aac-423c-4b6c-854b-f18c44b46a62.jpg)

not sure if it's a bug or intended design change 

### Device name

Samsung Galaxy A60

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

nightly 97.0.a1 (2021-12-20T11:11:33

**Comment by jonalmeida** [comment]
I see this too after the update.

cc: @Amejia481

**Comment by marcel263** [comment]
Tap the Nigthly logo to see

**Comment by orangepizza** [comment]
> Tap the Nigthly logo to see

did it really have to be that eye burning neon color by default?

**Comment by Amejia481** [comment]
Thanks for the report. I'll put a patch for addressing it.

**Comment by Amejia481** [comment]
The issue will be address on https://github.com/mozilla-mobile/fenix/pull/22935

**Comment by provsalt** [comment]
Seems to be fixed for me.

**Comment by sflorean** [comment]
Verified as fixed with Samsung A32 (Android 11) on latest Nightly build.
