### ISSUE TITLE
Wasm built with Emscripten >2.0 is 8 times slower to compile than WASM built with Emscripten 1.40.1 on Android phones RAM <=6GB

### ISSUE THREAD

**Issue by Nancyyuan** [mozilla-mobile/fenix#22947]
with firefox defaut profile, WebAssembly.compile time of built with Emscripten >2.0 is 8,9s (em3.0.1.wasm in tha attachment) ，while WASM built with Emscripten 1.40.1 is 1,2s (em1.40.1.wasm in the attachment), tested on Xiaomi K30(Ram= 6GB, 8 cores), firefox 96.0.0 beta.  
[wasm.zip](https://github.com/mozilla-mobile/fenix/files/7760168/wasm.zip)
Then I observed the CPU used of wasm (Emscripten >2.0) compilation is 48%,  I guess wasm (Emscripten >2.0) compilation maybe only use one core. 
I set javascript.options.wasm_optimizingjit false and compile time for both the wasms  is  about 140ms compared to 100ms for Chromium 94.  I saw a "wasm_verbose" switch, is there a relevant guidance document link?

Refer to * When wasm bytecode arrives, we choose the compilation strategy based on  * switches and on aspects of the code and the hardware.  If switches allow  * tiered compilation to happen (the normal case), the following logic applies.  *  * If the code is sufficiently large that tiered compilation would be beneficial  * but not so large that it might blow our compiled code budget and make  * compilation fail, we choose tiered compilation.  Otherwise we go straight to  * optimized code.  
it seems with default profile, the compile goes to "optimized code".  is this reasonable?

* Android device: SAMSUNG A51 (RAM 4G),Xiaomi K30(Ram= 6GB),etc
* Fenix version: firefox android 96.0.0 beta

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1747265

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Nancyyuan** [comment]
Thanks for the quick fix！
I wonder if the condiftion of " go straight to * optimized code" need to be improved on Android phones?
