### ISSUE TITLE
[Bug]: Homepage text not visible when switching backgrounds (light & dark mode)

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#22950]
### Steps to reproduce1
1. Have light theme enabled.
2. Change the background 2-3 times.
3. Pay attention to the homepage.

### Steps to reproduce2
1. Have dark theme enabled.
2. Change the background 2-3 times.
3. Pay attention to the homepage.

### Expected behaviour
Text is visible on the homepage.

### Actual behaviour
The text is not visible, more contrast will be helpful. 

### Device name
Samsung A 32

### Android version
Android 11

### Firefox release type
Firefox Nightly

### Firefox version
97

### Additional information

- Dark theme
<img src="https://user-images.githubusercontent.com/58466444/147089198-626afec5-ad00-4d92-9921-fe17d2d41ccc.jpg" width="300" height="550" />

- Light theme
<img src="https://user-images.githubusercontent.com/58466444/147089207-b0edda9e-dc8a-4c59-a6a3-a9d4ae25e2db.jpg" width="300" height="550" />

**Comment by Amejia481** [comment]
At the moment this is only a test wallpaper, that we are only using on nightly. This should be fixed when we remove it and just leave the final wallpapers.

**Comment by delia-pop** [comment]
Verified as fixed on Beta 99.0.0-beta.5, Nightly 100.0a1. and RC 98.3.0.
