### ISSUE TITLE
Bring back "Send to device" dialog via share menu from old firefox mobile

### ISSUE THREAD

**Issue by gringofe** [mozilla-mobile/fenix#22963]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Before the rewrite, Firefox was integrated in the Android share menu, which meant that sending a webpage to a linked device worked like this:

`Tap share icon in some app, e.g. Twitter` -> `Tap firefox` -> `Dialog shows up at the bottom and hovers over currently open app` -> `Select device` -> Done

As opposed to the new way:

`Tap share icon in some app, e.g. Twitter` -> `Tap firefox` -> `Wait for webpage to load` -> `Tap menu next to omnibar` -> `Tap share button` -> `Wait for device to show up` -> `Tap device` -> `Go back to the app you came from` -> Done

### How do you know that this problem exists today? Why is this important?

Re-adding this functionality would save users a lot of time, also it was very convenient 

### Who will benefit from it?

Everyone that uses Firefox Sync

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/1523
