### ISSUE TITLE
when links are opened from history/bookmarks and a new tab is created, the back button should then return to the tab the user was first on 

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#22962]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently it goes to the "new tab page"/homescreen

### How do you know that this problem exists today? Why is this important?
I've found myself trying to go back and tapping to open a new tab isn't an action I expect so I at least expect to be able to go back. I believe you guys said you wanted to keep the behaviour where it opens a new tab. Either that or that issue was left to lament. 

### Who will benefit from it?

Users?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18987)

**Comment by Poopooracoocoo** [comment]
And what happened to features requested years ago like tab search, bookmark all tabs and other changes for parity with desktop?? And add-ons... In praying it hasn't gone into a maintenance only state.

**Comment by Poopooracoocoo** [comment]
I don't use Firefox anymore but I doubt this was fixed

**Comment by 424344** [comment]
I still use firefox and it's not fixed.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813724

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
