### ISSUE TITLE
FNX-5576 ⁃ [Bug] Unable to access browser Settings in x86 emulator

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2296]
* Build master (e04d7837b352fbdea45cfb58e30ce8027043f241)
* Run in an x86 AVD (e.g, Pixel 2) (Build Variant: x86 Debug, Arch: Debug)
* Access browser Settings

Not-responding UI shown

![Screenshot](https://user-images.githubusercontent.com/102331/57240075-ab203580-6ffb-11e9-973c-f441ee2772e9.png)UNITO-UNDERSCORE!1557160591!

This blocks targeted UI testing on emulator.

(CC @rpappalax)

**Comment by sv-ohorvath** [comment]
An issue only for emulators, it doesn't happen on physical devices running x86.

**Comment by dector** [comment]
I have same issue. Discovered that ANR starts [here](https://github.com/mozilla-mobile/fenix/blob/e5f27a2e8d0edd2e72a1defc9bcc1a958fcfec4d/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt#L96).

**Comment by sblatz** [comment]
Since this is only affecting emulators I'm re-assigning it as p3.

**Comment by ekager** [comment]
I don't think this is an issue any longer, I'm able to open Settings on an x86 emulator. @AaronMT are you still seeing this not responding UI on your x86 emulator?

**Comment by AaronMT** [comment]
WFM now.
