### ISSUE TITLE
FNX-5577 ⁃ NullPointerException: Compositor.setFixedBottomOffset

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2297]
https://sentry.prod.mozaws.net/operations/fenix/issues/5686517/

```
NullPointerException: NullHandle
    at org.mozilla.fenix.components.FenixSnackbar$setAction$$inlined$apply$lambda$1.onClick(FenixSnackbar.kt:1)
...
(27 additional frame(s) were not displayed)

NullHandle
```

**Comment by agi90** [comment]
I just got this crash, started Fenix from the android home menu after it hadn't been used for a while.

**Comment by csadilek** [comment]
See: https://github.com/mozilla-mobile/android-components/issues/2935 and https://bugzilla.mozilla.org/show_bug.cgi?id=1549576
