### ISSUE TITLE
Android 11 notification bar background color is wrongly determined, causing unreadable result

### ISSUE THREAD

**Issue by adam900710** [mozilla-mobile/fenix#22988]
### Steps to reproduce

0. Set "Dark" system theme (Lineage OS 18.1 in my case)
1. "Install" Twitter as PWA
2. Open Twitter PWA
3. Check the notification bar background

### Expected behaviour

For the same "Dark" theme, weather.com results a much better background color:
![Screenshot_20211225-164639_Firefox](https://user-images.githubusercontent.com/460269/147381610-93b6bc65-1a8f-46ad-a63f-cb2f9ce3ce8f.png)

### Actual behaviour

The result for twitter.com can be seen here
![Screenshot_20211225-164632_Firefox](https://user-images.githubusercontent.com/460269/147381479-6801b921-db9e-4841-a415-fc86923b7a83.png)

Note the white notification bar, and since it's in dark mode, the text are also white, making things unreadable.

### Device name

OnePlus 7t

### Android version

Android 11 (lineage OS 18.1)

### Firefox release type

Firefox

### Firefox version

95.2.0

### Additional information

It looks like the background color of the notification bar is determined by the main color used in the favicon.

Thus for weather.com it's blue, but unfortunately for twitter, the white bird makes the background to be white.

I'd say the behavior is completely unnecessary. Just use the default color is good enough.
The favicon never really indicate the main color of the web, not to mention users may use add-ons like the darkreader to change the look.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19000)

**Comment by sflorean** [comment]
Tested on Samsung A32 (Android 11) and the same behavior is displayed for both Firefox and Chrome.
@adam900710 can you please confirm this?

**Comment by adam900710** [comment]
@sflorean For chrome, it's not changing the notification bar color at all for both installed PWA twitter.com or weather.com.
(Aka, black notification bar)

So is this ROM related? Or maybe there is some lineageOS specific setting to prevent the background color change of notification bar?

**Comment by Tesseeaye** [comment]
I'm having this same issue with Twitter's PWA on a Samsung Galaxy S21 (Android 12) in Firefox Nightly 97.0a1 (Build #2015854347)

**Comment by makotokato** [comment]
I can still reproduce this with Android 13 + Pixel 4a (See https://github.com/mozilla-mobile/fenix/issues/27221#issuecomment-1311026892 for Chrome behavior)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807414

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
