### ISSUE TITLE
Site search field should remember search

### ISSUE THREAD

**Issue by chartmix** [mozilla-mobile/fenix#22986]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
When I search something on a website and go to the next page (for example in a forum) the field is empty. I would expect that it remembers the input.
Furthermore it would be cool if the search box stays open when navigating trough the pages.
### How do you know that this problem exists today? Why is this important?
It annoys that the field doesn't remember the search input. It's a step extra that should not be necessary.
### Who will benefit from it?
Everyone who does a search on different pages. For example searching something where you don't know on which page it was located.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18999)

**Comment by glokta1** [comment]
Hi, I would like to work on this issue

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807713

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
