### ISSUE TITLE
[Bug]: Home screen gradient background jumps when keyboard raised

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#22989]
### Steps to reproduce

Choose the gradient background for the Home screen
Raise & lower the keyboard 

### Expected behaviour

The gradient should not move

### Actual behaviour

The gradient moves vertically, most obvious behind Top Sites

### Device name

Galaxy M32

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

#2015852907

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19001)

**Comment by SoftVision-LorandJanos** [comment]
Hi @Cheap-Skate! Thank you for the report!
I can confirm the issue is as you described.
Tested on the latest Nightly (2021-12-28).
Device used: Xiaomi Mi11 Lite (Android 11).
