### ISSUE TITLE
add an icon for clear cookies and site data

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#22981]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
All menus under security lock have icons except clear cookies and site data..please add one icon
Other chromium browsers have it

### How do you know that this problem exists today? Why is this important?
Will give uniform look

### Who will benefit from it?
All users

![Screenshot_20211224-181806923 (1)](https://user-images.githubusercontent.com/58127841/147353799-be39dd60-55b1-44c7-823a-273db5c37c79.jpg)

![Screenshot_20211224-181858449 (1)](https://user-images.githubusercontent.com/58127841/147353840-70368e15-22aa-4e44-96ae-4c6204f4d553.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18997)

**Comment by SoftVision-LorandJanos** [comment]
Hi @sheikh-azharuddin! Thank you for your report!
I can confirm the cookies icon is not displayed for the pages I tested (wikipedia, twitter, youtube...)
Tested on the latest Nightly (2021-12-27).
Device used: Google Pixel 4 (Android 11).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807441

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
