### ISSUE TITLE
FNX-5578 ⁃ [Bug] Content awkwardly disappears and reappears when I enter "Save to collection" screen

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#2299]
## Steps to reproduce
1. Visit https://example.org/
1. Tap the Fenix menu in bottom right corner of screen.
1. Tap "Save to Collection" (final entry in the menu)

### Expected behavior
No weird disappearing content.

### Actual behavior
* Near the bottom of the screen: Content slides onto my screen from the bottom (my tab and an "Add new collection" menu), and then disappears that content disappears, and then after a short delay, it fades into view again.
* Near the top of the screen: "Select coll..." starts expanding to "collection", and then some of letters disappear, and then reappear.

### Device information
* Android device: Pixel 3 running Android Q (beta)
* Fenix version: 1.0.1919

**Comment by dholbert** [comment]
Screencast: https://www.dropbox.com/s/e2req1lmmyv9qyq/collection.mp4?dl=0

**Comment by vesta0** [comment]
Will be addressed in #2359
