### ISSUE TITLE
[Bug]: search history is not maintained in the webpage search

### ISSUE THREAD

**Issue by lovachittumuri** [mozilla-mobile/fenix#22993]
### Steps to reproduce

open a new tab.
Search for content in google
thereby keeps on searching for some word in the web page search.
but search history is not maintained and it's not auto-populate.auto-populated

### Expected behaviour

![image](https://user-images.githubusercontent.com/24685721/147400690-650b38fd-0c6f-4ed4-bffd-b203b8ecafe8.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/24685721/147400753-815a8d7c-38be-4270-a0a5-a17056f09bc5.png)

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

89.0.10

### Device logs

none

### Additional information

none

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19004)

**Comment by Mugurell** [comment]
Thank you for the report @lovachittumuri!
Though I'm not sure about the specific scenario. I see in your comment both the `expected` and the `actual` result showing the same image.
Also seeing you're using a bit of an old version of Firefox.
Can you please update to the latest version from Playstore and if the issue still reproduces do a small screen recording showing the issue?

**Comment by sflorean** [comment]
Closing this ticket based on the lack of information.
