### ISSUE TITLE
Changing the system language does not update addon details

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22996]
Saw in https://github.com/mozilla-mobile/fenix/issues/22995 that the app would crash if changing system language while in the addon details screen.

There is another visual bug here: changing the system language does not update the addon details [because the fragment gets passed an addon to be displayed on screen](https://github.com/mozilla-mobile/fenix/blob/fa377bf0d62aa72206450686858801e731da26fa/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt#L43) and that addon's details are not updated when the language changes.

https://user-images.githubusercontent.com/11428869/147477429-e6e6cb12-bd9f-4e71-96b8-b04b23c771ef.mp4

Maybe it would be better for this fragment to have it's own `Store`/`State` populated based on the addon id.
This seems though like a bigger refactoring of how all the functionality related to showing the addons work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19007)

**Comment by sflorean** [comment]
Related issues: https://github.com/mozilla-mobile/fenix/issues/8188 and https://github.com/mozilla-mobile/fenix/issues/11729.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813726

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
