### ISSUE TITLE
Autofill Addresses on sites

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#230]
### Why/User Benefit/User Problem
As a user, I want to reuse previously inputted information for postal address so I can save time and complete my task faster.

### Dependency
* Solution pending #5492 

### Acceptance Criteria
* When I tap on a form field, my browser suggests auto-filling basic address data
* When we have multiple addresses, we will auto-fill using the most recently used (phase 1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11318)

**Comment by st3fan** [comment]
@bbinto this should probably be moved out of the MVP. It only makes sense in combination with sync (to get values you entered on other devices) and that work is on nobody's radar yet.

**Comment by agi90** [comment]
Related GV bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1512639

**Comment by bbinto** [comment]
@st3fan - let's discuss minimal implementation, I was hoping for feature parity to Fennec/Desktop. Are you saying that's all coming from sync? I thought more along those lines: https://developer.android.com/guide/topics/text/autofill

**Comment by bbinto** [comment]
We need to know when GV is finished with the bug and if/how A/C can help. Too many unknowns for eng to estimate

**Comment by snorp** [comment]
GV supports autofill for username/password currently. If we want to support other stuff (credit cards, addresses, etc.) we'd need to do more work.

**Comment by vesta0** [comment]
@snorp I saw your comment from January about GV supporting username/password auto-fill only. Has that changed since?

**Comment by madb1lly** [comment]
Hi all,

I was very surprised to discover that this feature doesn't exist in Fenix yet, I was sure I had used it before, but maybe I was getting mixed up with Fennec (I'm not sure why this isn't labelled for Fennec parity though).

Specifically, I wanted autofill from synced form data, but I suppose that's another issue.

Cheers 🙂

**Comment by vesta0** [comment]
@madb1lly we didn't have this feature in Fennec, that's why it wasn't marked as parity feature.

**Comment by madb1lly** [comment]
Hi @vesta0,

Okay maybe I've got confused about the scope of the issue; I was thinking it applied to all form data but maybe this is only about recognising and autofilling addresses.

I just checked my online banking site in Fennec and it autofilled my 10-digit user ID, so there's definitely some autofilling takes place in Fennec. Is there a separate issue open for form data in general, or different types of form data? #3277?

Cheers 🙂

**Comment by vesta0** [comment]
Yes we do autofill user IDs (logins) in both Fennec and [Fenix](https://github.com/mozilla-mobile/fenix/issues/1284) but address autofill is a new feature :)

**Comment by mnoorenberghe** [comment]
> I just checked my online banking site in Fennec and it autofilled my 10-digit user ID, so there's definitely some autofilling takes place in Fennec. Is there a separate issue open for form data in general, or different types of form data?

I think you are referring to Form History which is separate from login and address autofill. I don’t believe that was brought to GeckoView or Fenix yet and would be a separate issue.

**Comment by SeburoSUMO** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1354202

**Comment by kbrosnan** [comment]
This is done for en-US and a couple other locales.

As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report has been moved to Bugzilla as bz-1806190
