### ISSUE TITLE
Notify the user when trying to leave private browsing from notification with active downloads

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#23003]
- When a user is trying to leave private browsing with active downloads, a prompt is displayed notifying the user that the downloads will cancel if they close all private tabs.
- When the user closes private tabs from the device notifications, the prompt is not displayed, and the downloads are canceled.
- For consistency it would be useful maybe to have the same prompt in this case, or another warning that the downloads will stop this way.
Related to: #18160.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19008)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812792

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
