### ISSUE TITLE
No "copy URL to clipboard" button on share menu

### ISSUE THREAD

**Issue by yagueto** [mozilla-mobile/fenix#23006]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
When I click on the share menu, I cannot find any option to copy the link into the clipboard.

### How do you know that this problem exists today? Why is this important?
It would be very helpful to have one there, as it's the first place I would expect to find it. Other browsers (Safari, Chromium-based, etc.) do have a copy link in the share menu

### Who will benefit from it?
Everyone who needs to copy the URL to clipboard, as I just can't seem to find how to do it right now (apart from obviously clicking the address bar and selecting it manually, which is rather annoying).

Also related:  #22417

**Comment by czlucius** [comment]
I think this issue here: https://github.com/mozilla-mobile/fenix/issues/14313 looks similar. Perhaps you would like to check it out.

**Comment by yagueto** [comment]
Oh yeah, thanks! I looked over but couldn't find it.
