### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sojudu** [mozilla-mobile/fenix#23007]
Sometimes while resuming previous session, web page is not there, sometimes when web page is closed, it gets opened automatically upon resuming previous session, using Realme x, kindly

https://user-images.githubusercontent.com/95345118/147673614-29601434-fdc3-4da2-9662-71c883e839fe.mp4

 help

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19012)

**Comment by LaurentiuApahideanSV** [comment]
@sojudu Could you reupload the video? I am unable to view it.

**Comment by sojudu** [comment]
Sorry can't re-record video again, it uses h265 codec, you can convert and watch or use h265 compliant player, thanks

**Comment by sojudu** [comment]
Although seeing is believing, I will describe the issue, if I close tabs they re-appear once I re-open browser, and if I open tabs and check up later, then they are gone, I am using 96.1.1 Build #2015855929 and the problem is still there, I am using Realme x smart-phone,  on android 11, thank you

**Comment by sojudu** [comment]
I was forced to change the browser

**Comment by sojudu** [comment]
I today updated to 96.2, The problem persists in 96.2,thanks
