### ISSUE TITLE
[Bug] ask for a new option 

### ISSUE THREAD

**Issue by Tit2402** [mozilla-mobile/fenix#23019]
Hey, I just write to s'y that it would be a good idea to have an official translator extension who could traduce the pages in other languages directly. I know there is some extention but they aren't official and it would be really cool if there was something like a FIREFOX TRANSLATOR or the official Google translator. I know other people who want the same and I think you should do it.
Thank you for the time you spent to read it. I hope you'll do something.

**Comment by SoftVision-LorandJanos** [comment]
Hi @Tit2402! I can add a "feature request" label and we'll see what will be done.

**Comment by Tit2402** [comment]
OK thank you so much!
Please keep me informed for the future  and let me know how it's going.
Thanks again ;-)

**Comment by kbrosnan** [comment]
We don't keep extension requests open.

**Comment by Tit2402** [comment]
OK no problem. I really hope it will be accepted!

Le ven. 31 déc. 2021 à 15:12, Kevin Brosnan ***@***.***> a
écrit :
