### ISSUE TITLE
FNX-5580 ⁃ [Bug] Undo tab restoration is buggy

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2301]
Looks like we're not **fully** restoring the tab somehow, as closing the other tab closes both.

![buggy undo](https://user-images.githubusercontent.com/4400286/57245420-b2d9dd00-6fef-11e9-9f5c-b5b14774db28.gif)

**Comment by ekager** [comment]
I think this will also be fixed by #2303

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/14 build.
Samsung Galaxy S8 (Android 9)
HTC Desire 820 (Android 6.0.1)
