### ISSUE TITLE
[Bug]: Recently Visited List on Homepage is not updating properly when you delete that recently visited URL from history , it still remains the same in the recently visited list

### ISSUE THREAD

**Issue by MohitMandalia** [mozilla-mobile/fenix#23018]
### Steps to reproduce

1. Open more than 2 websites.
2. Go to show all for Recently Visited list.
3. Then delete any URL by pressing 'x'
4. then navigate back to the homepage you will see that URL.
5. Try deleting all the URL's by pressing 'x' on each URL then navigate back still you will see the recently visited URL's it wont get removed unless you remove it individually or by clearing all history at once.

### Expected behaviour

When we delete a URL from history it should not appear in the Recently visited list

### Actual behaviour

When we delete a URL from history it should still appears in the recently visited list on homepage

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

1.0.2101

### Additional information

This issue is in Firefox Preview version 1.0.2101(Build#1)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19018)

**Comment by MohitMandalia** [comment]
Please let me know if I can work on this issue and you are able to reproduce it.
Regards

**Comment by amocirean** [comment]
Hello @MohitMandalia, and thanks for reporting the issue to us.
I was not able to reproduce the issue on Latest Nightly 101.0a1 (2022-04-28).
Does the issue still occur on the latest RC/Nightly on your device? 

Android Version: 12
Devices Used: Google Pixel 4
