### ISSUE TITLE
Bookmarklets with native Javascript dialogs stopped working

### ISSUE THREAD

**Issue by bigConifer** [mozilla-mobile/fenix#23023]
### Steps to reproduce

1. Set a bookmark with the following Javascript URL:
`javascript:document.body.style.border="1em solid red"; alert(1); document.body.style.borderColor="blue"; void(0)`
2. Open any website e.g. https://csadilek.github.io/test12.html 
[Edit: when the page is opened out of github via the "open link in new tab" context menu option, bookmarklets won't run at all... Maybe another bug]
3. Run the bookmarklet from Bookmarks Menu or Awesomebar. 

### Expected behaviour

The bookmarklet is executed. The page gets surrounded by a red border, then an alert dialog pops up displaying "1" and if you close it, the border color changes to blue.

This was the behavior until Nightly 92.0a1 (Build #2015826985), [1c9af7c24+](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2021.08.09.revision.1c9af7c24a1c5099d954eba299d8e3214b85c8e9) from 2021-08-09 05:09.

### Actual behaviour

The bookmarklet is executed until the alert() call, however: 
- no dialog pops up
- the bookmarklet's execution stops at that point. 

Moreover this is blocking all further user interaction with the page in the current tab:
- the elements on the page become unclickable.

This is the behavior since Nightly 92.0a1 (Build #2015827081), [a769052cc+](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2021.08.09.revision.a769052ccb5fede253efa9e495079b6c1b16bc02) from 2021-08-09 17:53.

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.5

### Additional information

Notes:
- This bug occurs when a Bookmarklet synchronously calls a Javascript dialog, regardless of whether it is an `alert()`, `confirm()` or `prompt()` dialog.

- This bug does NOT occur, if the Javascript dialog is called asynchronously e.g.
`setTimeout(()=>{alert(1)})`, or if the Bookmarklet gets executed on the new-tab page/ homepage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19024)

**Comment by bigConifer** [comment]
Comparing the Nightly builds (https://github.com/mozilla-mobile/fenix/compare/1c9af7c24...a769052cc) it seems to be something like PR https://github.com/mozilla-mobile/fenix/pull/20573 ("always show home in background behind search dialog") that causes the bug.

**Comment by bigConifer** [comment]
Interestingly, when you switch to another tab and back, the blocking is released and the bookmarklet executes to its end. After that, the elements are clickable again.
However, the alert() dialog still does not pop up.

This is the case since Nightly 102.0a1 (Build #2015881057), [c1d7d0b29+](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2022.05.17.revision.c1d7d0b29cef8f511c89a56a535b4cbef72ade9c) from 2022-05-17 20:19.

**Comment by bigConifer** [comment]
The bug persists in Firefox Nightly 106.0a1.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813729

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
