### ISSUE TITLE
[Feature Request] Add scrollbar above certain page length

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#23027]
When browsing certain sites on mobile, they are quite large (like 100 pages mobile-equivalent) and can take quite some time to browse through. So my request, is to enlarge the scroll bar rectangle for a couple of seconds after dragging, then let it be so I can pinch it and move up and down for fast scrolling.

Currently the bar appears but can't be dragged. Example on this page browsing from mobile. The desired scroll bar in surrounded in red:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10916

![](https://i.imgur.com/0TcHB3r.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19026)

**Comment by jackyzy823** [comment]
I also would like fenix to have this feature.

Far more than **web page**, I hope **tabstray** (do not have scrollbar) , **bookmarks**  , **history** ,**downloads** ,**recently closed**  's scrollbar should be draggable too.

**bookmarks**  , **history** ,**downloads**, **recently closed**  these use the same `RecyclerView` . so they can be improved at same time.

**Comment by superbonaci** [comment]
Thank you @stale, you fix bugs like no tomorrow.
