### ISSUE TITLE
Context menu stopped working for Javascript links

### ISSUE THREAD

**Issue by bigConifer** [mozilla-mobile/fenix#23022]
### Steps to reproduce

1. Go to a page containing an anchor-tag with a Javascript URL (e.g. https://csadilek.github.io/test12.html)
2. Long press on that JS Link

### Expected behaviour

A context menu pops up. 

This is how it works with Firefox desktop and with the deprecated Fennec on Android. 
It also worked with Fenix up to Nightly 96.0a1 (Build #2015847817), [a6d5d21e0+](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2021.11.25.revision.a6d5d21e0ba58bc95fbf1ac44f1707588911ccf4) from 2021-11-25 17:44. Each of them at least gives the user the option to copy a Javascript link just like a regular link.

<p>
  <img src="https://user-images.githubusercontent.com/64743731/147020501-c055e2b9-0cb5-4207-a55c-0b26704e1250.jpg" width="45%" title="Fenix 95.0.0-beta.6"/>
  <img src="https://user-images.githubusercontent.com/64743731/147836588-e0eac632-29f4-4458-a323-02c5137e031d.jpg" width="45%" title="Fennec 68.9.0"/> 
  <br>
  <img src="https://user-images.githubusercontent.com/64743731/147836603-b11def4f-2b15-46e0-b252-7507df11b320.jpg" title="Firefox Desktop"/> 
</p>

### Actual behaviour

Nothing happens.

This is the behavior since Nightly 96.0a1 (Build #2015847913), [91da5318e+](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2021.11.26.revision.91da5318e34ee3a5bd046b3e8997df278b2df202) from 2021-11-26 05:10.

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19023)

**Comment by bigConifer** [comment]
@Amejia481, comparing the Nightly builds (https://github.com/mozilla-mobile/fenix/compare/a6d5d21e0...91da5318e, https://github.com/mozilla-mobile/android-components/compare/677e24ca0d...309af240a7) I've identified your PR "Improve loading URLs" (https://github.com/mozilla-mobile/fenix/pull/22594, https://github.com/mozilla-mobile/android-components/pull/11321) to be the breaking one, which causes the bug.
Can you please take a look into it to restore the previous behavior. Thanks a lot.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-02-08.

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)

**Comment by bigConifer** [comment]
This bug still persists in v108.0b3

**Comment by bigConifer** [comment]
> It was caused by PR [#11321](https://github.com/mozilla-mobile/android-components/pull/11321) on AC ("Improve loading URLs") which added `"javascript"` to `BLOCKED_SCHEMES`

@Amejia481 @csadilek @mcarare this bug exists for almost one year now. Can you please take a look to restore the previous behavior? Many thanks in advance!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813727

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
