### ISSUE TITLE
[Bug]: Firefox player not working

### ISSUE THREAD

**Issue by Palloxin** [mozilla-mobile/fenix#23020]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/147818688-cc0845f9-e165-4450-951b-223160795a7f.mp4

### Expected behaviour

the default player buttons should work when on fullscreen

### Actual behaviour

the default player of firefox buttons don't work when on full screen like in the video i uploaded.

### Device name

Huawei p8 lite 2017

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

95.2.0

### Additional information

Automatic rotation of android disabled while i recorded the video in "Steps to Reproduce".
..,..............
 With automatic rotation enabled the bug will show up under a certain condition: before you press the fullscreen button turn the phone vertically until the screen is stabilized. if you press the fullscreen button when the phone is horizontal, the bug will not show up and the buttons will work when on fullscreen. remember that in this case the automatic rotation is enabled and this is the video: 

https://user-images.githubusercontent.com/75091899/147819477-d54e2f99-1c22-4735-a228-304e34eadba7.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19021)

**Comment by marcel263** [comment]
Please provide a link to the page

**Comment by Palloxin** [comment]
> Please provide a link to the page

@marcel263 https://www.animeworld.tv/play/mushoku-tensei-isekai-ittara-honki-dasu-2.UNNMY/kF8qtG

**Comment by marcel263** [comment]
Can not replicate using Firefox Nightly 2015854827 on Samsung OneUI 3.1. With strict Tracking Protection enabled & no add-ons.

**Comment by Palloxin** [comment]
> Can not replicate using Firefox Nightly 2015854827 on Samsung OneUI 3.1. With strict Tracking Protection enabled & no add-ons.

i also had traclih protection enabled but with uBlock activated

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on the latest Firefox Preview Nightly 2022-01-04, but was unable to.
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 12)

**Comment by Palloxin** [comment]
https://user-images.githubusercontent.com/75091899/148384426-f928915b-2529-42da-9e07-501e6b807891.mp4

i don't know if it can help but i managed to make the buttons while i was fullscreen work at the third attempt continuosly going fullscreen. see the video
