### ISSUE TITLE
FNX-5581 ⁃ [Bug] site info panel can get outdated if you switch to new site pretty quickly

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2302]
## Steps to reproduce
* Go to [cbc.ca|url]
* Go to [amazon.ca|url]
* Hit the site panel info before the page finishes loading.

![Screenshot](https://user-images.githubusercontent.com/773158/57246116-82ec0300-700a-11e9-81fb-ab1edc09193c.png)UNITO-UNDERSCORE!20190506-142211!

### Expected behavior
The info panel must show the latest actual site.

### Actual behavior
The info panel  shows the old site before redirecting.

### Device information
* Android device: Pixel 3

**Comment by bsurd** [comment]
The issue is not reproducible in the latest build (5/15). Tested with a OnePlus 5T and Nexus 5. The site info panel is now updated instantly.
