### ISSUE TITLE
[Bug]: Lost inactive tabs on app update

### ISSUE THREAD

**Issue by AmirGamilDev** [mozilla-mobile/fenix#23029]
### Steps to reproduce

I'm not 100% certain of the steps but I _think_ this is what happened.

1. Have inactive tabs
2. Perform an app update

### Expected behaviour

Inactive tabs should still be there.

### Actual behaviour

Inactive tabs are gone (active tabs are still there).

### Device name

Samsung Galaxy s7

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

95.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19027)

**Comment by SoftVision-LorandJanos** [comment]
Hi @AmirGamilDev ! Thanks for your report!
I couldn't reproduce the issue you described.
I've installed the 95.1.2 version, created some inactive tabs, and updated to 95.2.0.
The inactive tabs were transferred the same way to the new version, without any change.
I've also tried it on Nightly, from 2021-12-31 to 2022-01-03, with the same result (Inactive tabs are transferred as expected).
Did you memorize what version did you upgrade it from?
Could you try with a previous version of Nightly with upgrading to the current one? Thank you!

**Comment by AmirGamilDev** [comment]
Hi @SoftVision-LorandJanos 

I'm afraid I can't remember which version I had previously.  I hadn't updated in a long time (I have auto updated off on my phone).

I'm afraid I'm a little too tied up at the moment to be able to try to reproduce this.  It's not really the time it will take to reproduce this as this should only take 5 minutes.  But just the stuff around it: re-adding device to Firefox devices and resolving issues that arise as a result - it wasn't plain sailing last time.

If I do get the opportunity, is there a way to force a tab to become inactive?  Will changing the system clock be enough?

**Comment by SoftVision-LorandJanos** [comment]
> If I do get the opportunity, is there a way to force a tab to become inactive? Will changing the system clock be enough?

There's an alternative way, here are the steps:
1. Have a few tabs open.
2. Go to Settings>About Firefox and tap on the icon 5 times, you will see a "Debug menu enabled" message.
3. Go to tabs tray and select a few tabs you'd like to make "inactive", selecting them after long tap on the first one.
4. Go to the 3 dot menu in the tabs tray and you'll have a "Make inactive" option.

**Comment by SoftVision-LorandJanos** [comment]
Hi @AmirGamilDev! Could you check if you can still reproduce the issue?
If not, I think the ticket can be closed.
Thank you!

**Comment by AmirGamilDev** [comment]
Hi. I recently performed an update and didn't lose inactive tabs so all good 👍

**Comment by SoftVision-LorandJanos** [comment]
Thanks! Based on the comment above, and on not reproducing on my end, I will close this ticket.
