### ISSUE TITLE
[Bug]: Firefox reloads the mobile site despite the Desktop site switch is on

### ISSUE THREAD

**Issue by boszormenyip** [mozilla-mobile/fenix#23034]
### Steps to reproduce

The timestamps at the and of the steps are the time in the video where the particular step is executed.

1. Open reddit.com. (00:00 - 00:02)
2. Switch to desktop site. (00:03 - 00:13)
3. Open several posts in new tab. The point is to open enough tab to force firefox to reload the first tab. (00:14 - 00:31)
4. Switch to each new tab, so firefox will load them. (00:32 - 00:58)
5. Switch back to the first tab, where reddit as desktop site is open. (00:59 - 01:31)

This shows the bug:
https://user-images.githubusercontent.com/3147180/147884621-318d3f47-51ee-4c38-8e4d-918c677c0979.mp4

### Expected behaviour

reddit.com is reload as desktop site.

### Actual behaviour

The timestamps at the and of the end are the time in the video where the particular behaviour is shown.

* reddit.com is reloaded as mobile site. (00:59 - 01:03)
* In the menu the desktop site is on. (01:04 - 01:13)
* It is not possible to switch between desktop and mobile site. (01:14 - 01:31, here I tried to turn of the desktop site switch)

### Device name

Galaxy Tab S5e

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

95.2.0

### Additional information

I also tried with Nightly (version 97.0a1), the bugs exists there, too.

**Comment by SoftVision-LorandJanos** [comment]
Hi @boszormenyip ! Thank you for your report!
I've tried reproducing your issue while logged in and logged out and had no success.
The main page remained on desktop site on every occasion.
Tested on the latest Release (95.2.0) and latest Nightly (2022-01-03).
Devices used:
- Xiaomi Mi11 Lite (Android 11).
- Oppo Reno 6 5G (Android 11).

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/11552
