### ISSUE TITLE
[Bug]: keyboard not active on a new tab

### ISSUE THREAD

**Issue by SosPosos** [mozilla-mobile/fenix#23036]
### Steps to reproduce

1. Open tab list
2. Open privates
3. Tap on new tab

### Expected behaviour

Keyboard must open and be active (or have a setting to turn off keyboard on a new tab)

### Actual behaviour

After long delay keyboard appears, but it is not active 
https://drive.google.com/file/d/1kJngdIy8OGZA1i34aXCmQGLnq6A13PWp/view?usp=sharing
It works like this after switching to private or normal view

### Device name

Meizu 15 light

### Android version

Android 7.1.2

### Firefox release type

Firefox

### Firefox version

95.2.0

**Comment by SosPosos** [comment]
It works well if use key in right top corner

**Comment by LaviniaL99** [comment]
Hello @SosPosos 

Thanks for your report!
I tested the above issue on the latest Nightly 98.0a1 (2022-01-20) and latest RC 96.2.0 (2022-01-19) and I was  not able to reproduce the issue.

**Devices used:**

Samsung S10E -> Android 10
Samsung Galaxy A32 5G -> Android 11

Can you retest the flow on the latest builds and let me know if you are still able to reproduce the issue? If yes, please attach a video for it.
