### ISSUE TITLE
Unable to unmute rte.ie video

### ISSUE THREAD

**Issue by AmirGamilDev** [mozilla-mobile/fenix#23030]
### Steps to reproduce

1. Open following URL: https://www.rte.ie/news/coronavirus/2022/0101/1269381-coronavirus-ireland/
2. Play video
3. Attempt to unmute

### Expected behaviour

Video should play (unmuted by default)

### Actual behaviour

Video plays muted.  Attempting to tap unmute icon does not unmute video.  Works in Chrome for Android.

### Device name

Samsung Galaxy s7

### Android version

Android 8

### Firefox release type

Firefox

### Firefox version

95.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19028)

**Comment by marcel263** [comment]
Reproducible using Nightly 2015854827 strict ETP

**Comment by SoftVision-LorandJanos** [comment]
Hi @AmirGamilDev. Thank you for the report!
I could reproduce the issue you described.
Also checked on Chrome where it works as intended.
Device used: Oppo Reno 6 (Android 11).
Tested on the latest Release (95.2.0) and latest Nightly (2022-01-03).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802969

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
