### ISSUE TITLE
[Bug]: Drag and Drop is Broken

### ISSUE THREAD

**Issue by locuturus** [mozilla-mobile/fenix#23031]
### Steps to reproduce

1. Navigate to some website with drag and drop able elements. Example: https://codepen.io/Goldfsh/pen/zBbOqm
2. Note that Firefox for Android cannot drag the indicated elements. This is broken for both mouse and touch input.

### Expected behaviour

Draggable elements should be able to be grabbed by a long mouse click + drag or similar with touch. Open a page with drag and drop elements in Android Chrome to observe this feature working very well with both mouse and touch input.

### Actual behaviour

Long click (or touch) + drag selects text or scrolls or similar. What it does not do is select the entire element. 

### Device name

Samsung Galaxy Tab S6

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

96.0.0 beta 5

**Comment by SoftVision-LorandJanos** [comment]
Hi @locuturus! Thank you for your report!
I can confirm the issue you logged is reproducible.
Tested with the latest Nightly (2022-01-03).
Also checked on Chrome where it works as intended.
Device used: Xioami Mi11 Lite (Android 11).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1748300

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
