### ISSUE TITLE
[Bug]: scrolling gets locked to horizontal-only or vertical-only

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#23044]
### Steps to reproduce

Go to any webpage that allows you to zoom in. Zoom in a good amount. Start scrolling vertically or horizontally, and then try to move in a diagonal or circular motion while your finger is still on the screen.

### Expected behaviour

The scrolling should allow you to any way you want, diagonally, circular etc. 

### Actual behaviour

Scrolling is "locked" to either horizontal-only or vertical-only (depending on how you initially started scrolling).

### Device name

Google Pixel 3a XL

### Android version

12

### Firefox release type

Firefox Nightly

### Firefox version

97

### Additional information

This seems like a bug. Firefox for Windows doesn't have this problem and Chrome does not have this problem on Android or Windows either.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19037)

**Comment by willfs84** [comment]
Ah, apparently this is called "axis locking". This is not good...

**Comment by SoftVision-LorandJanos** [comment]
Hi @willfs84 ! Thank you for your report!
I could reproduce the issue you described.
Tested on the latest Nightly (2022-01-04).
Device used: Oppo Reno 6 (Android 11).

**Comment by theres-waldo** [comment]
Yes, this is a deliberate behaviour called "axis locking". It dates back to (at least) [bug 1226655](https://bugzilla.mozilla.org/show_bug.cgi?id=1226655) on mobile.

**Comment by theres-waldo** [comment]
Windows also has axis locking, but it operates in a different mode (["sticky"](https://searchfox.org/mozilla-central/rev/3de56eb5f266f523340e739ae1b53258e0a95dfe/modules/libpref/init/StaticPrefList.yaml#368) rather than "strict") which allows the axis lock to be broken if the angle becomes sufficiently diagonal.

**Comment by SamuelMezger** [comment]
Still relevant.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813204

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
