### ISSUE TITLE
[Bug]: variable refresh rate is pinned to max value after and while scrolling to the top of a page

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#23043]
### Steps to reproduce

1. Use a device with a variable refresh rate
2. Enable the Android dev setting to show the refresh rate
3. Open a webpage
4. Scroll down the page and notice how the refresh rate changes on touch
5. Scroll back all the way to the top
6.  Scroll back down and up refresh rate should be pinned to max value
7.  Minimizing the app or switching tabs returns to the variable refresh rate

### Expected behaviour

The refresh rate should dynamically change depending on the user interaction

### Actual behaviour

After scrolling to the top of the page the refresh rate is pinned to the max value even after the user stops scrolling

### Device name

Pixel 6 Pro

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 (Beta and Release show this as well) Geckoview example is not affected so this is an AC/Fenix bug

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19036)

**Comment by kbrosnan** [comment]
https://www.youtube.com/watch?v=roGLZlFDxTQ

**Comment by kbrosnan** [comment]
@mcomella is there other information that would be good to provide in this bug?

**Comment by mcomella** [comment]
> ### Expected behaviour
> 
> The refresh rate should dynamically change depending on the user interaction

@kbrosnan I'm not too familiar with variable refresh rates and how it's expected to change with user interaction. What kind of changes do you expect to see? What is your concern with the frame rate being pinned to the maximum? What priority do you think this change should be? (note: I read [this article](https://android-developers.googleblog.com/2020/04/high-refresh-rate-rendering-on-android.html) but I'm still not sure what to expect for Firefox)

I did a quick search through the code using the methods mentioned in the article and I don't see us adapting to the frame rate but I'm not sure exactly what to look for. Once I understand what the expectation is, this is probably an issue to send over to the graphics team.

See also this issue where 90 Hz displays are locked at 60 Hz: https://github.com/mozilla-mobile/fenix/issues/20630

Sorry for the delay!

**Comment by kbrosnan** [comment]
The video shows the behavior. With a device set to use a dynamic refresh rate the refresh rate goes up to 120hz when interacting with the screen and drops to 60 when not interacting. There seems to be something that happens when scrolling back to the top of the page that breaks the dynamic refresh rate.

**Comment by mcomella** [comment]
Okay, now I understand – I think there's enough info here, thanks!
