### ISSUE TITLE
Add snackbar when selecting a new wallpaper

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#23045]
Match design work for wallpaper selection feature with the following criteria:

- Snackbar should be displayed when new wallpaper selected
- Snackbar should include "view" action which navigates back to home screen

**Comment by MatthewTighe** [comment]
Closed by #23196

**Comment by delia-pop** [comment]
Verified as fixed on Beta 99.0.0-beta.5, Nightly 100.0a1. and RC 98.3.0.
