### ISSUE TITLE
[Bug]: "Paste as plain text" in search box is redundant/confusing and has no effect

### ISSUE THREAD

**Issue by kevinoid** [mozilla-mobile/fenix#23047]
### Steps to reproduce

1. Navigate to https://archive.org
2. Select "Internet Archive" at the beginning of the paragraph "Internet Archive is a non-profit [...]" then copy to the clipboard.
3. Long-tap in the "Search" box below that paragraph.

### Expected behaviour

"Paste" would be the only option shown.

### Actual behaviour

"Paste" and "Paste as plain text" are shown.  If "Paste as plain text" is selected, nothing is pasted.
<img src="https://user-images.githubusercontent.com/336433/147991822-c7dd84fd-54d7-4b1b-8229-6a0ccb6ee78b.png" alt="Screenshot of &quot;Paste&quot; and &quot;Paste as plain text&quot; options" style="max-width: 100%" height="600" width="270">

### Device name

Google Pixel 5a

### Android version

Android 12 (SQ1A.211205.008)

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 (Build #2015855307)

**Comment by kevinoid** [comment]
Mozregression Pushlog: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=da76ee7195832a71ca2c79fd2474bdae87511316&tochange=ace2f4af2c29de1886e1e627d0fdb583e7573b59
Presumably from [Bug 1740414](https://bugzilla.mozilla.org/1740414)

**Comment by SoftVision-LorandJanos** [comment]
Hi @kevinoid ! Thank you for your report!
I could reproduce this issue on the latest Nightly (2022-01-04).
Device used: Oppo Reno 6 (Android 11).

**Comment by Mugurell** [comment]
Thank you @kevinoid for tracking down even the source of this!
Moving the issue to Bugzilla to be investigated by the GeckoView team.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1748417

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
