### ISSUE TITLE
[Bug]: Unable to paste in Google search box without focus first

### ISSUE THREAD

**Issue by kevinoid** [mozilla-mobile/fenix#23053]
### Steps to reproduce

1. Navigate to https://www.google.com
2. Ensure something is in the clipboard (e.g. copy the URL from the URL bar)
3. Long-tap on the search box.

### Expected behaviour

Focus would move to the search box and the "Paste" button would appear above it.  (As it does for most text boxes on most other pages.)

### Actual behaviour

The page scrolls to the bottom, the Paste button appears briefly in the top left corner of the screen then disappears, the text box does not receive focus.  If the search box is short-tapped to gain focus before the long-tap to paste, it behaves as expected:

https://user-images.githubusercontent.com/336433/148075302-946ea098-f418-4110-929f-a11751362304.mp4

### Device name

Google Pixel 5a

### Android version

Android 12 (SQ1A.211205.008)

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 (Build #2015855403)

### Additional information

On Chrome, focusing the search box causes it to move to the top of the page and fill the rest with search suggestions.  (The Paste button also disappears during the move.)  So it's harder to determine what the expected behavior is for Firefox.

I'm able to reproduce the issue with `mozregression --app gve --launch 86`, so it's not likely a recent regression.  Not sure if it's a recent issue, since I rarely use Google, especially from their homepage.

Using Developer Tools I was able to confirm that the issue is due to [`window.scrollTo()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) being called from a focus event listener on the text box.  (By calling `window.scrollTo = console.debug` in the Console before attempting to paste.)  I'm not sure whether preventing focus and hiding the Paste button on scroll is reasonable/expected behavior.  If so, feel free to close.

**Comment by SoftVision-LorandJanos** [comment]
Hi @kevinoid ! Thanks for the report!
I can reproduce your issue on the latest Nightly 97.0a1 (2022-01-04).
Device used: Oppo Reno 6 (Android 11).

**Comment by kbrosnan** [comment]
This reproduces in GV example.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1748468

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
