### ISSUE TITLE
[Bug]: Extension Google Search Fixer makes something strange

### ISSUE THREAD

**Issue by paleparanoid** [mozilla-mobile/fenix#23058]
### Steps to reproduce

1) In Extensions install "Google Search Fixer"
2) Type Something in Search bar (accordingly, the default search engine must be Google). I wrote "BDRip" word. 
After results are loaded, in a few seconds, a random link from the search results starts to open. If you go back, it will happen again. 
On screenrecord I enabled "Showing Touches" feature, so you can make sure that it happens on its own. Touchscreen is fine, it can't be phone's or ROM's problem. Also after deleting this extension everything becomes normal.

https://user-images.githubusercontent.com/86261854/148112833-c63bcf43-6a3d-4e32-9e4b-f76673b71a14.mp4

### Expected behaviour

It should just show search results.

### Actual behaviour

Described in "Steps to reproduce"

### Device name

Redmi Note 9s (not MIUI, ArrowOS installed)

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1

### Device logs

No logs needed here

**Comment by paleparanoid** [comment]
I'm not alone
![Screenshot_20220105-115300](https://user-images.githubusercontent.com/86261854/148188835-13333b51-199f-4659-94e2-1d7b32702ba4.png)

**Comment by kbrosnan** [comment]
@wisniewskit does Google Search Fixer have a bug on this or is it a Gecko/Fenix problem?

**Comment by wisniewskit** [comment]
Thanks, this slipped under my radar. I've just [filed a bug](https://github.com/wisniewskit/google-search-fixer/issues/23) on this on the addon's project page to investigate it ASAP. @paleparanoid , could we move the discussion there for now?

**Comment by paleparanoid** [comment]
> @wisniewskit does Google Search Fixer have a bug on this or is it a Gecko/Fenix problem?

Yes.
Look here, i posted a reply - https://github.com/wisniewskit/google-search-fixer/issues/23#issuecomment-1006396805
