### ISSUE TITLE
Regression: Visibility status  of the Tab selector and 3-dot buttons

### ISSUE THREAD

**Issue by sonora** [mozilla-mobile/fenix#23063]
### Steps to reproduce

When in Firefox Mobile you open a new tab, both
- the Tab selector button (facilitating access to other tabs) and
- the 3-dots menu (facilitating e.g. access to the Bookmarks and History)
become hidden. (The focus is on the URL box and the onscreen keyboard is visible by default).

To make them visible again:
- Up until version 95.2.0 it was already necessary to  hide the keyboard (e.g. by tapping anywhere outside the keyboard), which was awkward enough.
- Now in version 96.1 hiding the keyboard is not even enough anymore.  It seems you now have to tap the device's Back button, which is un-intuitive to the user.

![Screenshot 2022-01-05 094714](https://user-images.githubusercontent.com/845735/148188001-93022bad-b09c-44ee-afb0-8fcbcec7885b.jpg)

### Expected behaviour

The best solution would be to leave the Tab and 3-dots buttons visible all the time.

At the very most, if you want to hide them, please only hide them after the user has really started to type a URL, because then it is less likely that access to e.g. bookmarks or history and other functions is needed.

### Actual behaviour

The  Tab and 3-dots button frequently become hidden unexpectedly, it is un-intuitive to the user how to get them back.

### Device name

Samsung XCovwer 4s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19052)

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1365516

**Comment by kbrosnan** [comment]
I think this is https://github.com/mozilla-mobile/fenix/issues/22754 can we check Beta/Nightly to see if the problem is still present in 97 or 98?

**Comment by tanriol** [comment]
I'm having this issue on Nightly 98.0a1 build 2015859145 updated on 2022-01-23.

**Comment by sonora** [comment]
Still present in Release 97.1.0.

**Comment by amocirean** [comment]
Hello @sonora  and thanks for reporting the issue to us.
I was not able to reproduce the issue on latest RC (101.1.0) or Latest Nightly 101.0a1 (2022-04-28).
Does the issue still occur on the latest RC/Nightly on your device? I would suggest using latest versior, or at least a version that is at least equal to 100 for both.

Android Version: 11
Devices Used: Xiaomi Mi 11 Lite

**Comment by sonora** [comment]
Still present in release version 103.1.

Well, it's a clear regression, has benn introduced in v96.1, and has now been present in 8 consecutive versions(!).

I am wondering if anybody is raking regression reports serious? Why wouldn't code updates be rolled back until regressions like this are sorted out?

This has a clear impact on usability and I know of users who have finally resorted to abandon using Firefox...

**Comment by fice-t** [comment]
I can reproduce this on the latest Nightly, but only if I tap outside of the keyboard to dismiss it instead of using the back button or the built-in keyboard dismiss button.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807710

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
