### ISSUE TITLE
Tapping and holding on a GitHub reaction doesn't show tooltip

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/fenix#23062]
### Steps to reproduce

1. Open https://github.com/mozilla-mobile/fenix/issues/22962
2. Press and hold on thumb reaction button

### Expected behaviour

GitHub's tooltip should appear, telling you who upvoted the issue. This works on Chrome. It appears on hover and similar issues can be found elsewhere.

### Actual behaviour

The tooltip does not appear.

### Device name

Samsung Galaxy S10

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

95.2.0

If I can be bothered, I might test with an actual mouse on both Firefox and Chrome. But I believe Chrome works properly with mice on Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19051)

**Comment by marcel263** [comment]
Reproducible. Attempted to report it on the Webcompat initiative's issue tracker. https://webcompat.com/issues/97787

**Comment by SoftVision-LorandJanos** [comment]
Hi @Poopooracoocoo. Thank you for your report!
I was able to reproduce this issue in the latest Nightly (2022-01-06).
Tested with Google Pixel 4 (Android 11).
On Chrome however it seems intermittent, sometimes the tooltip does not appear there either.

**Comment by Poopooracoocoo** [comment]
I've used Chrome for years. I don't feel that it's 'intermittent'

**Comment by Poopooracoocoo** [comment]
I don't use Firefox anymore but I don't think this was fixed

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809307

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
