### ISSUE TITLE
[Bug]: Find on page make youtube menu float. Leaving gap at bottom.

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#23066]
### Steps to reproduce

1. Open youtube.com
2. Click on 3 dots on toolbar
3. Click on find in page

### Expected behaviour

Youtube menu option should not float and there should not be any gap.

### Actual behaviour

Youtube menu floats and there is gap at bottom. Checked the issue on Firefox Beta and Nightly. Both have this issue. Refer attached screenshot. Samsung internet browser doesn't let youtube menu appear when find on page selected.
![Screenshot_20220105-214910_Firefox Beta](https://user-images.githubusercontent.com/76210878/148254056-a6485ef8-e4ee-4767-a70b-f749f04d2110.jpg)
![Screenshot_20220105-215635_Samsung Internet](https://user-images.githubusercontent.com/76210878/148254097-ae1af0f1-1c6d-4055-a3d5-e0e09fe192bf.jpg)

 

### Device name

Samsung Galaxy A71

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19054)

**Comment by SoftVision-LorandJanos** [comment]
Hi @iamiceparticle! Thank you for your report!
I can reproduce the issue you reported.
Tested on the latest Nightly (2022-01-06).
Device used: Google Pixel 4 (Android 11).

**Comment by sonora** [comment]
Other web sites are affected by the 'gap' issue as well. As an example, go to https://web.de, accept the cookie disclaimer, then tap on any news article. The site produces a floating social media bar at the bottom (with facebook,  twitter, insta etc. logos). When scrolling up the page, this bar often also partially scrolls up, producing the 'gap'.

Interestingly, it it most easily reproduced when pinch-zooming the article just a little before scrolling. (I have the Firefox accesibility setting ''Zoom all web sites' set to 'on', which seems to make it even more reproducible.)
![Screenshot_20220107-091707_Firefox](https://user-images.githubusercontent.com/845735/148515502-2950e5e9-75e1-4adc-b6c8-6014da394de5.jpg)

**Comment by tasosb** [comment]
I will try to fix this issue

**Comment by sonora** [comment]
Well, it's not yet fixed, I think ...

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809247

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
