### ISSUE TITLE
[Bug]: "Jump back in" tabs are not visible on homescreen

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#23064]
### Prerequisites:
All previously opened tabs are closed.

### Steps to reproduce

1. Make a random search (dogs).
2. Perform a long tap on links and open 2-3 pages from the search engine results using "Open link in new tab".
3. Tap on Home button.
4. Observe the homepage sections.

### Expected behaviour

"Jump back in" section is displayed and the tabs are visible.

### Actual behaviour

"Jump back in" section is displayed but the tabs are not visible.

### Device name

OnePlus 9

### Android version
11

### Firefox version
96.1.0

### Additional information

<img src="https://user-images.githubusercontent.com/58466444/148235318-c0e1f64a-dd06-4e7a-a1d4-a2e0a0566de8.jpg" width="300" height="550" />

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19053)

**Comment by sv-ohorvath** [comment]
I also noticed the Recently visited section not being shown immediately after closing the tabs. As a workaround, you have to open another tab/the settings menu, or something, in order to refresh the homepage when you return to it.

**Comment by delia-pop** [comment]
Reproducible on RC 99.1.0 with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
Reproducible on Beta 100.0.0-beta.4 with Google Pixel 6 (Android 12).

**Comment by LaurentiuApahideanSV** [comment]
Reproducible on Beta 101.0.0-beta.3 with Google Pixel 6 (Android 13).

**Comment by delia-pop** [comment]
Reproducible on the latest Nightly from 05/17 with Google Pixel 6 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 108.0a1 (2022-11-14) and latest RC (107.1.0) builds.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
