### ISSUE TITLE
Despite being logged in here and synced but CANNOT finish logging into Firefox Beta for Android on this same device

### ISSUE THREAD

**Issue by thetriune14** [mozilla-mobile/fenix#23078]
### Steps to reproduce

I have a screenshot to add
![Screenshot_20220106-001902](https://user-images.githubusercontent.com/81508647/148345994-cff6bfe1-8cf5-40d1-826c-c2e4e3049502.png)

### Expected behaviour

Sync across 2 Android firefox versions on this device

### Actual behaviour

Despite showing being logged in on the Android Beta version sync States account needs to be verified

### Device name

Motorola moto g power 2021

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

95.2.0 (Build #2015851755

### Additional information

the firefox gmail account is NOT accessable to retrieve the required 6 digit code despite being already logged in here and synced acrossed my different devices one of which only has the Beta version installed ... IE: 1 Beta doesn't  sync with the Beta version on this device ?!???

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19060)

**Comment by jdragojevic** [comment]
If you are not able to access the associated gmail account to validate the sign-in attempt, then you are not going to be able to sign in.  This should be wontfix unless there's something else going on that's not obvious to me.
