### ISSUE TITLE
Implement a standard way to increase tap area in Compose

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23087]
For Android Views we have a [View.increaseTapArea(extraDps)`](https://github.com/mozilla-mobile/fenix/blob/8b13e382fdca2e8344b057295741f7f14e9d7a70/app/src/main/java/org/mozilla/fenix/ext/View.kt#L21-L30) method to help with respecting accessibility best practices while also showing smaller views based on UX specification.

We need a similar method for composables.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19064)

**Comment by mcarare** [comment]
AFAIK, currently, there is no equivalent of a touch delegate in Compose. 

One of the possible solutions would be wrapping the element in a `Box` or another custom composable that imposes the minimum dimensions for a11y.

I did see some chatter a few months ago about work in this area post compose 1.0 so maybe we could wait for a solution in the API.
