### ISSUE TITLE
[Crash reporter] Misleading tab previews in tabs tray or when swiping between tabs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23089]
Following https://github.com/mozilla-mobile/fenix/issues/22722 which adds an in-app crash reporter the user will still be able to continue using the app while having crashed tabs.
When swiping between tabs using the toolbar or when opening the tabs tray a missleading preview/thumbnail will be shown instead of the crash reporter.

[AbstractBrowserTabViewHolder](https://github.com/mozilla-mobile/fenix/blob/01ba8959ce99571c7de76bdb8caba80591b234d8/app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt#L116L120) and [ToolbarGestureHandler](https://github.com/mozilla-mobile/fenix/blob/51cec928b2c9d56b9fc380e0bbe44fd2d74025ab/app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt) will have to be updated with support for the crash reporter UI.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19070)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802968

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
