### ISSUE TITLE
[Bug]: Enabled scroll to hide changes logout+language selection in CV

### ISSUE THREAD

**Issue by robovoice1** [mozilla-mobile/fenix#23081]
### Steps to reproduce

1.  Log into Common Voice account
2. Change to german language
3. In stats page tap on avatar (top right)
4.  Make sure "scroll to hide toolbar" is enabled in Fx mobile (settings/customize)
5. swipe up and down

### Expected behaviour

no moving (changing size) of log out button and language selection at all.

### Actual behaviour

Please see screen recording!
If the "scroll to hide toolbar" option is enabled in Fx mobile (settings/customize), the size of the log out button and the box for speach selection is changing when swiping up + down. This is in selected german language in Cv website, but not in the english section.

### Device name

Fairphone 3 plus

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 (Build #2015855787)

### Device logs

None

### Additional information

add ons were disabled,
i reported also on github/common voice
https://github.com/common-voice/common-voice/issues/3390

https://user-images.githubusercontent.com/92784377/148389267-9d9a18e5-87fd-4c07-945d-b284da7fe191.mp4

The same bug also on latest Fx mobile stable (android).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1750783

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
