### ISSUE TITLE
Firefox issues are not being prioritized in a reasonable way

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#23084]
There seems to be a problem with Mozilla ignoring longstanding fundamental usability issues where core pieces of Firefox are broken.   Instead, the majority of the development effort seems to be on adding endless iterations of superficial features like color themeing. 

For example, the following issue has been open for 1.5 years with almost no developer attention despite 147 comments from 63 users.   There are multiple cases of users abandoning Firefox for other browsers. 
https://github.com/mozilla-mobile/fenix/issues/12731#issuecomment-1006670796

**Comment by Siva981** [comment]
:(

**Comment by kbrosnan** [comment]
Opening additional issues creates more work. The problem is multi-faceted and we have done a few things to try and improve it. There may be some regressions when it comes to the multiprocess work that was done. I'll see if one of the dev engineering team can provide a summary of the plans.

**Comment by robsmith11** [comment]
@kbrosnan
Could the devs who is currently working on the issue at least comment publicly on the issue's github page?

I think part of the problem is that unlike most open source projects, with Firefox a lot of the planning and development discussions happen behind closed doors rather than in a public forum, so it's not possible for users to tell whether in issue is being ignored or progress is slowly being made.
