### ISSUE TITLE
 [Crash reporter] Crashes will show misleading notifications

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23088]
Steps to reproduce:
- load about:crashcontent / about:crashparent in any of the tabs
- check the system notification

Actual:
- A notification with the text "Sending crash report to Mozilla" is shown

Expected:
- Better wording. The crash report might contain sensitive information so everything should be treated with care.
The crash report is not sent without user consent to Mozilla that only happening when users will tick the "Send crash report to Mozilla" checkbox in the crash report.

https://user-images.githubusercontent.com/11428869/148432136-5a31b724-17fa-4558-a83a-55b5a4d2826a.mp4

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19071)

**Comment by rocketsroger** [comment]
This is related to https://github.com/mozilla-mobile/android-components/issues/10112

**Comment by rocketsroger** [comment]
@Mugurell Did https://github.com/mozilla-mobile/android-components/issues/10112 fixes this issue as well?

**Comment by Mugurell** [comment]
> @Mugurell Did [mozilla-mobile/android-components#10112](https://github.com/mozilla-mobile/android-components/issues/10112) fixes this issue as well?

I think so. Thank you!
