### ISSUE TITLE
[Crash reporter] A content crash will crash more tabs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23091]
Seen while working on https://github.com/mozilla-mobile/fenix/issues/22722, can be reproduced on GVE also.

Steps to reproduce:
- have >= 3 tabs opened (doesn't happen with < 3 opened tabs). Don't have to have a parent-child relation.
- load about:crashcontent in any of the tabs

Actual:
Multiple tabs are shown as crashed

Expected:
Only one tab - the one in which about:crashcontent was loaded should be shown as crashed.

Seems like an issue with GeckoView reusing the same process for multiple tabs, reported on https://bugzilla.mozilla.org/show_bug.cgi?id=1747802

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19068)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802967

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
