### ISSUE TITLE
Make time segments in history view sticky

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#23095]
Time segments like "Today", "Yesterday" and so on should be sticky so that people have a better idea in which section they are.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19072)

**Comment by topotropic** [comment]
related: https://github.com/mozilla-mobile/fenix/issues/19942

**Comment by topotropic** [comment]
This seems to work for synced tabs on the tab tray, it would be helpful to people to have a sticky 'time' header for additional  context also in history view. Thanks!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813090

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
