### ISSUE TITLE
[Crash reporter] Persist the crashed status even after restart

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23090]
Seen while working on https://github.com/mozilla-mobile/fenix/issues/22722 which adds an in-app crash reporter the user will still be able to continue using the app while having crashed tabs.

For each crash Gecko will gather valuable information and persist them locally for the eventuality users will want to share these crash reports with Mozilla to help debug the crash events.

But if the app is restarted all tabs will be reloaded and if the app was closed with crashed tabs before the user had the opportunity to decide what to do with that tab - close/restore/send crash report to Mozilla the crash report will be lost.

Saw that we still have the crashes available after the app is restarted so as a supplement to https://github.com/mozilla-mobile/fenix/issues/22722 for more of a "pick up where you've left off" scenario and to also help Mozilla debug crashes we might want to show the tabs as crashed and allow users to report these crashes even after an app restart.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19069)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802965

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
