### ISSUE TITLE
[Crash reporter] No mapping between a crash and a tab

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23092]
Seen while working on https://github.com/mozilla-mobile/fenix/issues/22722 which adds an in-app crash reporter allowing to continue using the app while some tabs might have crashed.

As an edgecase it is possible that multiple tabs might have crashes and each will have it's own crash report.
Based on the sensitive nature of the crash reports users might choose to send one crash to Mozilla but not others but currently this isn't possible. All pending content crashes will be sent or all will be dropped whenever user interacts with any of the crashed tabs.

See also https://github.com/mozilla-mobile/fenix/issues/23090 and https://github.com/mozilla-mobile/fenix/issues/23091

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19067)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802964

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
