### ISSUE TITLE
FNX-5583 ⁃ [Meta] Contextual Menus

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#231]
### Why/User Benefit/User Problem
As a user, I want to copy or share specific items of viewed web content

### What / Requirements
Interaction with in-context content

### Acceptance Criteria (how do I know when I’m done?)
UI to allow users to select/copy/share text/images

**Comment by st3fan** [comment]
Here is a list of of issues around 'long pressing on content in GeckoView' that we on file in the Reference Browser:

https://github.com/mozilla-mobile/reference-browser/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3AFeature%3AContentContextMenus+

Most of these can be seen in action in the Reference Browser. Few are left.

**Comment by bbinto** [comment]
These are great, @sarentz - I currently see three remaining issues open, @vesta0 - let's make sure that these are prioritized in your upcoming sprints and ready to be picked up once Fenix eng and UX starts working on them (sprint 3 or 4)
