### ISSUE TITLE
[Bug]: Security: Address bar, security windows show origin elided insecurely, allows URL spoofing

### ISSUE THREAD

**Issue by alesandroortiz** [mozilla-mobile/fenix#23101]
### Steps to reproduce

In Firefox for Android:

1. Go to https://badssl.com
2. Navigate to any of their long origin examples
3. Observe address bar and tap security indicator

### Expected behaviour

Address bar: Shows end of origin (`https://...badssl.com`)

When tapping security indicator: Full origin is shown; if elision is needed, show end of origin

When focusing address bar: End of origin is shown (note: not end of URL)

### Actual behaviour

Address bar: Shows beginning of origin (`https://subdomain...`) (unsafe)

When tapping security indicator: Full origin is shown (safe)

When focusing address bar: End of URL is shown (unsafe because long path can also hide origin)

### Device name

Samsung Galaxy S10

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

Firefox 92.1.1

### Additional information

Creating new report per instructions in https://github.com/mozilla-mobile/fenix/issues/17373:
> Users are welcome to re-submit bug reports that follow the updated issue template and that still affect the current release of Firefox for Android (aka Fenix).

Original reports:
https://github.com/mozilla-mobile/fenix/issues/6762
https://bugzilla.mozilla.org/show_bug.cgi?id=1598175
https://bugzilla.mozilla.org/show_bug.cgi?id=1731181 (also discusses insecure elision in other Mozilla products)

This was discovered/discussed publicly on Twitter: https://twitter.com/AlesandroOrtizR/status/1438675521555025922

For reference, Chromium has URL guidelines on how to elide URLs safely: https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/url_display_guidelines/url_display_guidelines.md#Eliding-URLs

This is also part of the URL Standard: https://url.spec.whatwg.org/#url-rendering-elision

### Address bar:
![Firefox-Android](https://user-images.githubusercontent.com/1619599/148480945-f11e0a10-ec89-45df-8b02-1d045caf30ce.jpg)

### When focusing address bar:
![Firefox-Android-AddrBarFocused](https://user-images.githubusercontent.com/1619599/148480950-0356bba0-b7ec-43e1-85f4-6a6287e19781.jpg)

### When tapping security indicator:
![Firefox-Android-SecurityInfo](https://user-images.githubusercontent.com/1619599/148480966-9beb2069-9604-4621-8f0c-c551de38b9cf.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19074)

**Comment by alesandroortiz** [comment]
Still repros on Firefox for Android 107.1.0 (Build #2015915067)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/6762
