### ISSUE TITLE
[Bug]: Bottom page menu does not remain stuck at the bottom of the screen on different webpages

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23110]
### Steps to reproduce

1. Access the following websites: soundcloud.com, twitter.com, canva.com, aliexpress.com, linkedin.com.
2. Log into your account when necessary (twitter.com, linkedin.com).
3. Scroll the webpages.
4. Observe the bottom menu navigation bar.

### Expected behaviour

The bottom bar should always remain stuck on the screen when scrolling, as it does on Chrome.

### Actual behaviour

The bottom bar displays a flicker when scrolling on different websites when the dynamic toolbar is animated.

On soundcloud.com, linkedin.com: the flicker was not observed on Chrome and Gecko View Example.
On twitter.com, canva.com, aliexpress.com, the flicker was not observed on Chrome, but it was present on Gecko View Example.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 (Build 2015855787)

### Additional information

https://user-images.githubusercontent.com/89388888/148566930-dfb7f2e3-cf96-44d0-a45e-d1e6663ad057.mp4

https://user-images.githubusercontent.com/89388888/148566956-8793cf15-3b01-4100-9f54-99b23081722e.mp4

https://user-images.githubusercontent.com/89388888/148566971-e85455ae-33a0-42c9-b01f-6872e79cd34f.mp4

https://user-images.githubusercontent.com/89388888/148567013-02e34c49-43dd-4a46-9019-2ebcbb9debc9.mp4

https://user-images.githubusercontent.com/89388888/148567025-8845052a-0621-4207-a52a-0b6527da447f.mp4

https://user-images.githubusercontent.com/89388888/148567044-6ef43aec-4b04-448c-ad24-1d970ae3d9ff.mp4

**Comment by amedyne** [comment]
@Mugurell Any thoughts on this?

**Comment by Mugurell** [comment]
Tested linkedin and soundcloud on latest GVE and I see this kind of issues here also


https://user-images.githubusercontent.com/11428869/150086780-50aed271-9296-4190-b819-e3ea8ae95e92.mp4


https://user-images.githubusercontent.com/11428869/150086833-949c0349-9f9a-4b13-a27e-e0f387a88f6d.mp4

**Comment by Mugurell** [comment]
These almost seem like expected but maybe there is something to be improved.
Moving to Bugzilla for more investigation by the GV team.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1750918

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
