### ISSUE TITLE
Improve download management

### ISSUE THREAD

**Issue by steve121418** [mozilla-mobile/fenix#23118]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The user wants to know the download progress and control downloads in the Downloads page, such as pausing, cancelling, resuming and retrying downloads, and info on download speed, size downloaded over download file size, and download progress bar.
### How do you know that this problem exists today? Why is this important?
The user would have to go to the download notification to view the progress. 
To pause/cancel/resume/retry a download, you have to go in the download notification to pause/cancel/resume/retry it. 
In addition, the Downloads page only displays downloaded files.
### Who will benefit from it?
Users who want more control and more information on downloads and download progress, especially for users experiencing slow internet speeds and/or using mobile data connections.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19091)

**Comment by Hussain-P99** [comment]
Hi I would like to work on this issue.

**Comment by steve121418** [comment]
Sure.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812790

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
