### ISSUE TITLE
[Bug]: critical status bar and navigation pill hiding kind of full screen mode

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#23119]
### Steps to reproduce

After latest firefox update it is kind of going to full screen mode in portrait mode....status bar and navigation pill is getting hidden
Is it expected? Seems bug to me 

Attaching video and screenshot

### Expected behaviour

Navigation pill and status should not hide

### Actual behaviour

Navigation pill and status bar hiding

### Device name

asus rog 3

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

![Screenshot_20220108-191521861](https://user-images.githubusercontent.com/58127841/148646492-001469e8-8825-427d-8005-a71e68c97628.jpg)

https://user-images.githubusercontent.com/58127841/148646498-a6d8f1b4-7aaf-4595-890d-9f58e57a2397.mp4

**Comment by marcel263** [comment]
Became reproducible after playing a video (not full-screen). Toolbar receded a little, gesture bar (pill), disappeared

**Comment by D4rk3vi1** [comment]
This big is of huge annoyance and arrived in beta as well. How can priority be increased? Thanks!

**Comment by vinc17fr** [comment]
This issue currently occurs on my smartphone. Perhaps because this is after I attempted to play a video full screen (the video could not be started, though). Opening the tab list or the menu temporarily makes the Android navigation bar appear. Ditto with a page opened in a new tab.

**Comment by sheikh-azharuddin** [comment]
Works fine ...try latest nightly

**Comment by D4rk3vi1** [comment]
Is also not present in pre-release 68 beta anymore. Issue can be closed.
