### ISSUE TITLE
[Bug]: Black strip at top in fullscreen of all video elements

### ISSUE THREAD

**Issue by cudla100** [mozilla-mobile/fenix#23129]
### Steps to reproduce

1 Start video, for example at youtube.com.
2 Setting fullscreen.

### Expected behaviour

Video should be fullscreen, but instead it resizes to smaller scale.

### Actual behaviour

Resized video, because of black strip.

### Device name

Huawei MYA-L11

### Android version

Android 6.0

### Firefox release type

Firefox

### Firefox version

95.2.0

### Device logs

https://crash-stats.mozilla.org/report/index/20e3b459-c78d-4f3e-beb8-9a4ed0211115

https://crash-stats.mozilla.org/report/index/bp-3a1bc6c0-d843-4efe-af6a-657ad0211021

### Additional information

![Screenshot_2022-01-09-19-25-09](https://user-images.githubusercontent.com/27821549/148695378-ee012a3f-f80a-4b99-9279-226bd45b226f.png)

![Screenshot_2022-01-09-19-15-26](https://user-images.githubusercontent.com/27821549/148695422-5b1f8e69-710a-41ad-bc93-09b4a4e86029.png)

![Screenshot_2022-01-09-19-15-34](https://user-images.githubusercontent.com/27821549/148695452-fa5464de-5226-4479-86e9-4eb1e1161ab7.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19098)

**Comment by kbrosnan** [comment]
The crashes are tracked at https://github.com/mozilla-mobile/fenix/issues/20872 and unrelated to this problem.
