### ISSUE TITLE
Enable detekt with type solving in the project

### ISSUE THREAD

**Issue by BraisGabin** [mozilla-mobile/fenix#23124]
Would you be interested on enable detekt with type-solving on? That will allow to perform richer analysis on the code but with a drawback in execution time (it's slower than the current "plain" detekt).

Why am I asking this? At detekt we are looking projects where we could try our new rules. Basically we want to run out new rules over the Fenix source code to ensure that all the issues that they find are actual issues and there are not false-positives. (More context here https://github.com/detekt/detekt/issues/4408). To accomplish this we don't need your help: we can fork the project, setup the type solving and use that fork for our tests. But, because we are going to do it I would like to know if you are interested in use it. Because, if you are, we can create a PR enabling it.

As side note I already creates a PR just updating detekt and "refreshing" a bit the configuration: #23123.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19094)

**Comment by gabrielluong** [comment]
I will bring this up with the team tomorrow. It may take some time to reach a consensus. I think it's great to see that our projects can mutually benefit for each other's support.

**Comment by cortinico** [comment]
As a little side note: we're happy to showcase the project somewhere on our website as well if we end up doing it 👍

**Comment by cortinico** [comment]
This is still a thing if someone from Mozilla wants to take this on :)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802971

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
Looks like we're already using Detekt: https://github.com/mozilla-mobile/fenix/commits/main/config/detekt.yml

**Comment by cortinico** [comment]
> Looks like we're already using Detekt: [`main`/config/detekt.yml (commits)](https://github.com/mozilla-mobile/fenix/commits/main/config/detekt.yml)

Yes, but the point of this issue was if you were up to investigate the usage of more advanced rules with Type Resolution

**Comment by cpeterso** [comment]
> Yes, but the point of this issue was if you were up to investigate the usage of more advanced rules with Type Resolution

Thanks for clarifying! I'll reopen the Bugzilla bug and add a comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1802971
