### ISSUE TITLE
Write performance test to prevent regressions to number of open tabs

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#23126]
Fenix sucks at handling multiple tabs. It's really bad and possibly getting worse. Eg on #12731 there are multiple reports that Fenix 95.2.0 *cannot reliably keep one single tab open* on a Galaxy S9. On my 6 GB M32 Fenix can reliably keep less than ten tabs open. *Chrome can keep at least forty, maybe more*. The difference between Fenix and Chrome, and between Fenix and reasonable user expectations, seems enormous.

There are three issues here
1. how bad is the problem?
2. is it getting worse?
3. what causes the problem?

This Feature Request is only about (1) and (2). 

IMHO dev team urgently needs to implement a procedure to measure how bad this problem is, ie how many tabs Fenix can keep open, and compare it with some benchmarks eg Fennec, Chrom(ium).

This procedure would be like @mcomella's work on cold launch time, only for number of tabs.

eg

Once a week:-
- reboot reference phone
- open an increasing number of defined tabs in Fenix & swipe between them
- note how many tabs before Fenix starts unloading and reloading tabs
- maybe put phone to sleep or put Fenix in the background & bring it back to the front, check tabs are still loaded, something like that
- repeat on Chrome and Fennec (?)

I think the results would be quite shocking. Much work needs to be done. I also think you might catch some major regressions as new features are introduced. Perhaps WebRender caused a regression. Perhaps https://github.com/mozilla-mobile/android-components/pull/6170 did. But at the moment we just don't know because AFAIK number of active tabs doesn't get measured.

If you *do* measure active tabs then please ignore this request, and maybe post a link to the test results, thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19096)

**Comment by Cheap-Skate** [comment]
See also #23140, I think there needs to be a long term stability test too, eg open X tabs, check they are all loaded, leave phone with screen off for 24 hours, are all X tabs always still loaded, or do some/all reload?  I think X should be a fairly big number.

**Comment by mcomella** [comment]
Triage: Thanks for filing. We're aware of the tab unloading problem from https://github.com/mozilla-mobile/fenix/issues/12731 and it's something we're working to address. This issue sounds like a good reminder to write a test for that issue so I'll leave this open so we remember to write the test. We'll likely address the root problem in https://github.com/mozilla-mobile/fenix/issues/12731.

**Comment by echuber2** [comment]
Should this really be closed due to staleness? I thought @mcomella said it was meant to be left as a reminder. I can't see the Jira task associated with it, but maybe that is still tracking it?
