### ISSUE TITLE
redesign 3 dot menu

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#23125]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I know there were few changes in 3 dot menu few months ago but in reality it is not so user friendly and hectic ...it is quite taller and more than 50% wider...also when we are using Bottom address bar it does not make any sense finger trying to reach to the top to click an option defeating the sole puprose of having bottom address bar for large devices...so why follow chrome and brave implementation to have a taller menu rather you can implement short height, wider and friendly menu like samsung internet browser... Even your firefox lite browser had this implementation...

### How do you know that this problem exists today? Why is this important?

It is really difficult to reach all items of the menu when using Bottom address bar and large device

### Who will benefit from it?
All users

Samsung browser( beautiful, short menu)
![Screenshot_20220109-101946038](https://user-images.githubusercontent.com/58127841/148669997-72784585-9647-4a1d-bc5c-7c4b8689b150.jpg)

Firefox ( taller, wider ugly menu)
![Screenshot_20220109-102359562](https://user-images.githubusercontent.com/58127841/148670012-0d18b2dc-45b6-4584-986c-a58138b94bff.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19095)

**Comment by sheikh-azharuddin** [comment]
..

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809248

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
