### ISSUE TITLE
setting up the website design theme

### ISSUE THREAD

**Issue by NektoNektovich** [mozilla-mobile/fenix#23139]
although I really liked the interface of firefox android up to version 57, which was nicer to the eyes and more convenient, but the current dark theme is also not bad. However, I really don't like that some sites, such as github, automatically include a dark site theme if firefox has a dark interface theme enabled, and I like light site themes, but a dark browser interface theme. I ask you to make a setting for the theme of the sites, which will not depend on the theme of the browser interface.

хотя мне очень нравился интерфейс firefox android до 57 версии, который был приятнее глазам и удобнее, но нынешняя темная тема тоже не плохо. Однако мне очень не нравится, что некоторые сайты, как например github, автоматически включают темную тему сайта, если у firefox включена темная тема интерфейса, а мне нравятся светлые темы сайтов, но темная тема интерфейса браузера. Прошу сделать настройку для темы сайтов, которая не будет зависеть от темы интерфейса браузера

**Comment by emilio** [comment]
This is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1736218, fwiw.

**Comment by emilio** [comment]
In nightly you can achieve it via `about:config`, setting `layout.css.prefers-color-scheme.content-override`

**Comment by NektoNektovich** [comment]
> В nightly вы можете достичь этого с помощью `about:config`, установка `layout.css.prefers-color-scheme.content-override`

thanks, it worked in fennec f-droid! it's a pity that there is no obvious setting :) please tell me more: 1- how to configure the opening of a bookmark in the current tab? 2- how to remove the house button near the address bar, or replace it with the refresh/stop button?

спасибо, сработало в fennec f-droid! жаль, что нет очевидной настройки :) подскажите пожалуйста еще: 1- как настроить открытие закладки в текущей вкладке? 2- как убрать кнопку домика возле адресной строки, или заменить ее на кнопку обновить/остановить?

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/20635
