### ISSUE TITLE
[Bug]: "Recently visited section" - Switching between portrait and landscape mode, the Remove menu is overlapping the URL bar 

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23138]
### Steps to reproduce

1. Enable Portrait mode from your device
2. Open some sites
2. Navigate to the Homepage -> Recently visited section
3. Long tap on a tab from Recently visited section
4. Switch from portrait to landscape mode 

### Expected behaviour

The Remove menu must not overlap the URL bar when switching between portrait and landscape mode.

### Actual behaviour

The Remove menu is overlapping the URL bar when switching between portrait and landscape mode. For more details 
 please see the video attached.

https://user-images.githubusercontent.com/96047134/148762056-c9eb6c65-a02c-4be0-9340-5372ac100f5f.mp4

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1

**Comment by Mugurell** [comment]
We could close the menu when the screen is rotated.

**Comment by LaviniaL99** [comment]
Hi @Mugurell 

For consistency, the "remove" menu remains open when switching from portrait to landscape mode.

**Comment by mcarare** [comment]
We close the menu on screen rotation for multiple menus in the app, I think we should maybe do it everywhere?

**Comment by sflorean** [comment]
This is still reproducible on Nightly 1/18 with OnePlus 9 (Android 11).
cc @gabrielluong @sarah541

**Comment by mcarare** [comment]
It seems that the PR with the fix is not merged yet.

**Comment by mcarare** [comment]
Reopened for QA.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with OnePlus 9(Android 11).
The menu is not displayed when the orientation is changed.
