### ISSUE TITLE
Intermittent UI test failure - <Classname.testName>

### ISSUE THREAD

**Issue by NektoNektovich** [mozilla-mobile/fenix#23133]
Firefox 95.2.0 android 7.1.2
The logic for working with inserts and bookmarks is terribly inconvenient. In version 68, I opened a bookmark in the current tab if a new tab was not needed. Now the bookmark is forced to open in a new tab and I have to go to the tab bar to remove the unnecessary one 😖 are you kidding me? 😤 make a setting so that you can open a bookmark in the current tab! 2- remove keyboard autostart when opening a new tab! 😤 3 - twenty years I have been use the Internet and have never pressed the button of the house! Make the setting for replacing the house next to the address bar with the refresh / stop button! And 4- add the translate web pages extension already!

Ужасно неудобно сделана логика работы с вкдадками и закладками. В версии 68 я открывал закладку в текущей вкладке, если новая вкладка была не нужна. Теперь же закладка принудительно открывается в новой вкладке и мне приходится идти в панель вкладок, чтобы убрать ненужную 😖 вы издеваетесь? 😤 сделайте настройку, чтобы можно было открывать закладку в текущей вкладке! 2- уберите автозапуск клавиатуры при открытии новой вкладки! 😤 3- двадцать лет пользуюсь интернетом и ни разу не нажимал на кнопку домика! Сделайте настройку замены домика рядом с адресной строкой на кнопку обновить/остановить! И 4- добавьте уже расширение translate web pages!

**Comment by kbrosnan** [comment]
This is feedback on several ideas and not a single report. Closing as we have issues opened for many of these requests.
