### ISSUE TITLE
[Bug]: Auto-completed domain is not erased when user keeps typing

### ISSUE THREAD

**Issue by boppreh** [mozilla-mobile/fenix#23131]
### Steps to reproduce

1. Start entering a domain in the address bar (e.g. "unipr" from "unipraias.com.br")
2. Watch the rest of the domain be auto-completed after the cursor ("**unipr***aias.com.br*").
3. Keep typing something else (e.g. "uniprsomethingelse").

https://user-images.githubusercontent.com/231856/148701341-c9870e11-c271-4492-80d1-048524b25dc2.mp4

.

### Expected behaviour

When I keep typing a different word the auto-completed domain should be erased, leaving only what I typed, e.g. "uniprsomethingelse".

### Actual behaviour

The auto-completed part stays, resulting in a invalid URL, e.g. "**uniprsomethingelse***aias.com.br*".

This is especially bad because the auto-completion often fails (notice how many times I typed "unipr" in the video without getting any completion), or loads after a couple of seconds just when I'm about to navigate to that address. This results in frequent but unpredictable navigation failures.

### Device name

OnePlus 6

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

95.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19100)

**Comment by LaviniaL99** [comment]
Hello @boppreh 
Thanks for your report!
I tested the above issue on the latest Nightly build 98.0a1 and latest release version RC 96.1.1 and I was not able to reproduce the issue.

Devices used:

- Samsung S10E -> Android 10
- Galaxy A32 5G-> Android 11

**Comment by boppreh** [comment]
> Hello @boppreh Thanks for your report! I tested the above issue on the latest Nightly build 98.0a1 and latest release version RC 96.1.1 and I was not able to reproduce the issue.
> 
> Devices used:
> 
>     * Samsung S10E -> Android 10
> 
>     * Galaxy A32 5G-> Android 11

Seems to be fixed on Nightly, thanks!

**Comment by boppreh** [comment]
This bug is back on nightly version 101.0a1.

**Comment by amocirean** [comment]
Hello @boppreh, and thanks for reporting the issue to us.
I was not able to reproduce the issue on latest RC (101.1.0) or Latest Nightly 101.0a1 (2022-04-28).
Does the issue still occur on the latest RC/Nightly on your device?

Android Version: 11
Devices Used: Xiaomi Mi 11 Lite

**Comment by boppreh** [comment]
I've been using nightly ever since this issue happen, and I can reproduce it most times on version 101.0a1 (Android 11, OnePlus 6).

![Screenshot_20220428-160908](https://user-images.githubusercontent.com/231856/165772735-1e4a7a65-1177-4c08-86aa-c04b45309b99.jpg)

https://user-images.githubusercontent.com/231856/165775139-5546ff72-8a57-4e72-8780-cc8a9acea0ff.mp4

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Nightly 102.0a1 2020-05-25 but was unable to.
### Device used:
- OnePlus 6T (Android 9)

**Comment by aphedges** [comment]
I used to have this problem, but testing on 107.1.0 on Android 11 on a Pixel 2, I can confirm I no longer experience it.
