### ISSUE TITLE
111% regression in COLD start MAIN time to first frame from 1/5-1/7

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#23144]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/759372/148855499-0587f5c6-ba5a-43e3-8da2-d75757280bfe.png">

We see a recent regression in COLD start MAIN time to first frame:
- 1/5: 1.474s
- 1/6: 2.875s
- 1/7: 3.113s (and it stabilizes)

From **1/5-1/7 is a regression of 111.2% or 1639ms.** Let's investigate to find out the cause.

I took a profile with `Debug` on Jan. 10 upstream/main: https://share.firefox.dev/3HPYaer A profile from the Firefox Profiler would be preferred because of the markers (i.e. shows when first frame is drawn) but that's blocked on crashes: BZ-1749418.

It could be that the time to visual completeness has not regressed and the time to first frame is much closer to it, i.e. the time to fully functional has not regressed. However, this is likely to be a perceived performance issue for users.

**Comment by mcomella** [comment]
I took start up profiles with the Firefox Profiler. Here they are trimmed to the first frame (onPreDraw):
- Nightly 1/5 (1s): https://share.firefox.dev/3zOY8Ra
- Nightly 1/10 (4.5s): https://share.firefox.dev/3nhRzBP

Curiously, they look very similar (i.e. similar proportions to the calls): it's just that in the later Nightly, everything seems to take longer. 🤔 This reminds me of what we saw with https://github.com/mozilla-mobile/fenix/issues/18753. Other possibilities could be increased CPU/disk/memory contention or https://github.com/mozilla-mobile/fenix/issues/17703.

**Comment by mcomella** [comment]
I was able to reproduce this problem locally so worst case we can bisect:
- Nightly 1/5 32bf020b7 (1s): https://share.firefox.dev/3qjhJWE
- Nightly 1/10 7582bce89 (2.3s): https://share.firefox.dev/3Fz5gmd (and I was able to reproduce this behavior again)

The 1/10 local profile looks different from the Nightly one. There is an obviously longer layout call before the first frame is drawn. It looks like we're synchronously handling compose content whereas we were not doing so before:
- before: https://share.firefox.dev/3K92oj6
- after: https://share.firefox.dev/3tk0C95

From a visual perspective, the 1/5 local build starts with the homescreen scrolled to the top while the 1/10 local build is scrolled to focus on Pocket, i.e. https://github.com/mozilla-mobile/fenix/issues/22939. In 1/5, top sites and Pocket seem to appear async whereas Pocket appears synchronously in 1/10. It's possible there was a functional change (if not our code, could Compose have been updated?) or there's a race condition that caused the behavior to change.

**Comment by mcomella** [comment]
Triage: P1 because we may need to uplift since we recently cut beta.

**Comment by mcomella** [comment]
I did a bisection via `python3 backfill.py --tests cold_main_first_frame --startcommit 32bf020 --endcommit c8ddd401bb4d347b7e78d255b5cd9e63b43b0be3 --git_remote_name up --repository_to_test_path ../fenix fenix nightly armeabi-v7a commitsRange`. Assuming the script works correctly, I think the cause is 09fdee651090784e617d534e67c7b7e3ff5f4885, https://github.com/mozilla-mobile/fenix/issues/22851.

Timing:
- (earliest commit) 32bf020b7cc26cc720a50cd771b482d448b2e5c2: 1373.0
- (next) 09fdee651090784e617d534e67c7b7e3ff5f4885: 2667.0
- Later commits are also in 2k ranges

**Comment by mcomella** [comment]
I manually confirmed that I can reproduce in https://github.com/mozilla-mobile/fenix/commit/09fdee651090784e617d534e67c7b7e3ff5f4885 but can't reproduce one commit earlier in https://github.com/mozilla-mobile/fenix/commit/32bf020b7cc26cc720a50cd771b482d448b2e5c2 so the script appears to be working correctly.

**Comment by csadilek** [comment]
@Amejia481 @MatthewTighe Hey, Could you take a look at this and investigate alternatives? Looks like https://github.com/mozilla-mobile/fenix/commit/09fdee651090784e617d534e67c7b7e3ff5f4885 introduced this performance regression, which we need to address and uplift to 97 as well.

Possibly caused by recreating the activity? https://github.com/mozilla-mobile/fenix/commit/09fdee651090784e617d534e67c7b7e3ff5f4885#diff-a7c5f2e3af1379b1bec69cefb02e6644b6d8a9a90d3d0d000b92f78c4e07dd41R55-R56

**Comment by MatthewTighe** [comment]
Took a shot at a solve for this for now in #23172. Thanks @csadilek for bringing it to our attention!

**Comment by Amejia481** [comment]
Thanks @MatthewTighefor the patch. I think it will require some investigation as the only places where we are executing the code that recreates the activity run conditionally only on nightly or debug.  

https://github.com/mozilla-mobile/fenix/blob/cf31bc408a14cdacd184d23756a3415b0735e6e5/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L400

https://github.com/mozilla-mobile/fenix/blob/cf31bc408a14cdacd184d23756a3415b0735e6e5/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L764

**Comment by Amejia481** [comment]
I think the regression could be linked to we are changing the background even though there is not a wallpaper set, when we have the default wallpaper.   https://github.com/mozilla-mobile/fenix/blob/afd13fec858b6b25ef0f8443f9c506e63b2282d5/app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt#L31

**Comment by Amejia481** [comment]
After manually testing locally, I verified the regression is addressed. 

```

==> results2.txt <==
{'max': 922.0,
 'mean': 648.12,
 'median': 633.0,
 'min': 582.0,
 'replicate_count': 25,
 'replicates': [922.0, 625.0, 615.0, 617.0, 663.0, 625.0, 582.0, 629.0, 633.0,
                593.0, 636.0, 616.0, 613.0, 639.0, 650.0, 664.0, 630.0, 614.0,
                632.0, 689.0, 701.0, 676.0, 638.0, 652.0, 649.0]}

```

**Comment by mcomella** [comment]
I verified with our Nightly perf tests that we've returned to pre-regression performance numbers (actually an improvement of 10s of ms 😄):
<img width="643" alt="image" src="https://user-images.githubusercontent.com/759372/150011027-8453f7f1-07a3-49e9-a216-9727a998d471.png">

Thanks for the quick fix, Amejia481!
