### ISSUE TITLE
how to remove the house button from the address bar?

### ISSUE THREAD

**Issue by NektoNektovich** [mozilla-mobile/fenix#23147]
Never used the home button in browsers. How can I remove it from the panel or replace it with the refresh / stop button? This is configurable on a computer browser, please do the setting here too!

Никогда не пользовался кнопкой дом в браузерах. Как ее убрать с панели и заменить кнопкой обновить/остановить? На компьютерном браузере это настраивается, сделайте пожалуста настройку и здесь!

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/19918

**Comment by garyyeap** [comment]
Very disappointed with the final decision. I have a small screen phone every spaces matter and Firefox decided to put a useless button occupying the already crowded URL bar for me. Uninstalled but maybe you don't care about the little user like me. Good luck with your market share.
