### ISSUE TITLE
[Bug]: permanently loading when trying to download a file.

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#23146]
### Steps to reproduce

1. Go to https://t.co/OD0YuiXnF3

### Expected behaviour

A download popup appears and I can download the file.

### Actual behaviour

The loading bar keeps gets stuck, nothing apparently happens.

Release works correctly.

### Device name

OnePlus 9 pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 (Build #2015856555), 39a211c1c+ AC: 97.0.20220109143152, 324faa4260 GV: 97.0a1-20220108220226 AS: 87.1.0

**Comment by emilio** [comment]
Beta also behaves correctly.

**Comment by mcarare** [comment]
I cannot reproduce this on latest main.

**Comment by emilio** [comment]
Huh, now it works. I guess I might have gotten unlucky with my network or something? Let's call this WFM, I'll reopen if I find a way to repro it consistently again.

**Comment by sflorean** [comment]
I wasn't able to reproduce this issue following the steps, on latest Nightly with OnePlus 9. Removing the qa label.
