### ISSUE TITLE
Add setting for Contile to turn off shortcuts

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#23159]
https://mozilla-hub.atlassian.net/browse/FNXV2-18742

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Nightly debug build 2022-03-03 and can confirm the "Sponsored shortcuts" setting is present in the Homepage menu. If the option is turned on sponsored tiles are displayed on the home screen (if they are available), turning the option off will remove them.
![Sponsored shortcuts](https://user-images.githubusercontent.com/50983519/157219000-40a47038-3cf7-4b1d-81a2-01c11fc6f0b2.JPEG)

**Comment by alexolog** [comment]
Why can't I have only shortcuts, without recent history?

**Comment by cadeyrn** [comment]
@alexolog Your question is not related to this issue. 🤔

**Comment by alexolog** [comment]
@cadeyrn This change led to #25739 (and others) that were closed referencing this issue.
So it is very much related.
