### ISSUE TITLE
FNX-5587 ⁃ Hide URL bar when scrolling down a custom tab

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#2315]
As a user, I want the top URL bar to be hidden when I scroll down in a custom tab, so I can have a full page viewing experience.

UX feedback [here](https://github.com/mozilla-mobile/fenix/issues/203#issuecomment-488585627).

### Acceptance criteria:
-When I scroll down in a custom tab, the top URL bar is hidden.

**Comment by softvision-miralobontiu** [comment]
Verified that when a page is scrolled down in a custom tab, the top URL bar is hidden, on the latest build 1.0.1920 (#11360657) with: Google Pixel (Android 9), Samsung Galaxy Note 8 (Android 9), Sony Xperia Z2 tablet (Android 6.0.1), and Sony Xperia Z5 Premium (Android 7.1.1).
