### ISSUE TITLE
Remove the "threads" profiler feature from the setup-startup-profiling.py script

### ISSUE THREAD

**Issue by canova** [mozilla-mobile/fenix#23150]
Previously we had the "threads" feature in the gecko profiler but we removed it in [Bug 1729815](https://bugzilla.mozilla.org/show_bug.cgi?id=1729815). This feature is still provided in the `tools/setup-startup-profiling.py` file here:
https://github.com/mozilla-mobile/fenix/blob/622a4f57d0f03dcac157d9d5ece9c5bc74289b98/tools/setup-startup-profiling.py#L23-L28

This feature was removed because it was not being used. Keeping the "threads" feature will print a warning all the time. We can remove this feature from this list now.

cc @mcomella

**Comment by canova** [comment]
@mcomella I just got a chance to test it on my Android phone and I can confirm that it fixes the crash that was happening before. The crash shouldn't usually happen though, it should skip the unrecognized features with a warning. I filed [Bug 1749498](https://bugzilla.mozilla.org/show_bug.cgi?id=1749498) for that.

**Comment by mcomella** [comment]
I confirmed the fix and opened a PR: https://github.com/mozilla-mobile/fenix/pull/23162

**Comment by mcomella** [comment]
Thanks @canova for the quick diagnosis and suggested fix!
