### ISSUE TITLE
[Bug]: part of 3dot popup menu hidden

### ISSUE THREAD

**Issue by ANDREW007CZ** [mozilla-mobile/fenix#23151]
### Steps to reproduce

Tap on 3dot menu in normal mode (no keyboard showed). 

### Expected behaviour

Whole menu should be visible or scrollable

### Actual behaviour

Menu is not visible as whole and is not scrollable. Settings line is not visible. Need to go to portrait to be able to scroll. 

### Device name

Lenovo Tab 3 8 Plus

### Android version

Android 6

### Firefox release type

Firefox Beta

### Firefox version

96.0.0-beta.5 (Build #2015853259), e20176743

**Comment by sflorean** [comment]
@ANDREW007CZ thank you for report! This issue was reported also [here](19375), please follow the discussions there; I will close this as duplicate.
