### ISSUE TITLE
[Bug]: White buttom bar GUI glitch with latest OneUI 4.

### ISSUE THREAD

**Issue by INTRASERVER** [mozilla-mobile/fenix#23165]
### Steps to reproduce

Firefox GUI issue on Samsung Galaxy Note 20 Ultra with latest OneUI4 stable update. I've been reporting UI issue to Samsung while ago since beta was available. So now with final/stable issue persist. It is random. When firefox not been open for while and you open it then it comes with this GUI glitch. 
![Screenshot_20220112-031325_Firefox](https://user-images.githubusercontent.com/97578992/149063835-0e6b7ccd-bc9b-48e4-bcfe-0cb5a14aad06.jpg)
![Screenshot_20220112-031333_Firefox](https://user-images.githubusercontent.com/97578992/149063836-57320a97-489f-45ed-9a41-d074714526a8.jpg)

### Expected behaviour

White url bar.

### Actual behaviour

In some scenarios when you open firefox buttom url bar is white. This most happen when firefox not been open for while. When you go to website then this glitch dissapear.

### Device name

Samsung Galaxy Note 20 Ultra

### Android version

Android 12 OneUI4

### Firefox release type

Firefox

### Firefox version

95.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19122)

**Comment by Frivolous2** [comment]
Can reproduce on Galaxy A52s, One UI 4/Android 12. I think it happened on Android 11 as well though.

I've set Firefox to open links in private mode, and sometimes the URL bar will glitch.

Firefox 97.2.0

![Uploading Screenshot_20220305-234601_Firefox.png…]()
