### ISSUE TITLE
[Bug]: HMTL files saved as HTM on Android 9 &8

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#23167]
### Steps to reproduce

1. Go to one of these pages:
https://storage.googleapis.com/mobile_test_assets/test_app/downloads.html
https://filesamples.com/formats/html
2. Download the HTML files.
3. Observe the file extension in the download prompt.
4. Check the file extension in the Downloads menu
5. Check the file extension in the device Downloads folder.

### Expected behaviour

The file is saved with the given extension (HTML)

### Actual behaviour

The file is saved as HTM on Android 8 & 9. On Chrome, they have no extension.
As HTML on Android 10, 11.

### Device name

Nexus 6P, Pixel 2

### Android version

Android 8, 9

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19123)

**Comment by kbrosnan** [comment]
This does not seem to be a recent regression v94 on Android 8 behaves the same.
