### ISSUE TITLE
URLs describing Megazord do not work

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#23171]
https://github.com/mozilla-mobile/fenix/blob/cdbe7983f57c2d1c679e0a94b77c903ba992b9fc/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L391-L392

These lines should be updated to working links. @jdragojevic Does the A-S team still have these documents somewhere or shall we remove them?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19126)

**Comment by eliserichards** [comment]
Looks like the new link is here: https://mozilla.github.io/application-services/book/design/megazords.html

**Comment by bendk** [comment]
And that first link needs `s/master/main/`:     https://github.com/mozilla/application-services/blob/main/docs/design/megazords.md

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813166

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
