### ISSUE TITLE
Investigate CheckChanged shouldBeUnchecked use cases

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#23173]
## Description
We want to check whether the property `shouldBeUnchecked` of class `CheckChanged` is required or if `shouldBeUnchecked` together with `shouldBeChecked` could be reduced to a single boolean describing if the check changed to true or false.

The problem is described [here](https://github.com/mozilla-mobile/fenix/pull/22437#discussion_r783233014)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19131)

**Comment by Alexandru2909** [comment]
QA should test if the checkbox in the `Select Tabs` screen are updated correctly for each item on select/deselect all.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 102.0a1 (2022-05-24) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
