### ISSUE TITLE
Estimated reading time and photo are missing from some stories when "quick-reads" topic is selected

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23174]
### Steps to reproduce

1. Open some pages in order to have some history available
2. Navigate to the homepage
3. Scroll down and for **"Stories by topic"** section select **"Quick-reads"**
4. Verify that the stories available from " Thought-provoking stories" section have the estimated reading time and picture displayed.

### Expected behaviour

Estimated reading time and photo must be available for all stories when "quick-reads" topic is selected.

### Actual behaviour

Estimated reading time and photo is not available for the following stories when "quick-reads" topic is selected:

- Pocket's Top 10 Stories for December 2021
- The Choose your Own Adventure Guide to a Better Tomorrow
- Pocket's Best of 2021: Science

https://user-images.githubusercontent.com/96047134/149313273-c22bed23-3c4d-404e-993e-d3b90911a000.mp4

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19133)

**Comment by kbrosnan** [comment]
This appears in 95 as well. Maybe the API is not giving us the data? In some cases the Pocket stories suggestions are collections of articles on the same topic so a reading time does not make sense. Though there are what looks like full articles that don't have a suggested reading time.

**Comment by delia-pop** [comment]
Tested on 99.0.0-beta.1 with Motorola Moto G30 (Android 11).

@kbrosnan I noticed that before selecting "Quick-reads" all the stories were properly displayed with images and estimated reading time. Upon selecting the said topic, at least one story without image and **"Pocket" as the website address** becomes available. 

After un-selecting "Quick-reads", and continue filtering, some stories from "Pocket" as the website address without picture might become available again. 
Also noticed that **none** of the stories from "Pocket" website address have an estimated reading time, with or without picture.

https://user-images.githubusercontent.com/89388888/157432159-6bac58dd-5708-410f-8faa-aabcf0df659d.mp4

**Comment by delia-pop** [comment]
This issue is still reproducible on Beta 100.0.0-beta.1 with Google Pixel 6 (Android 12). Relates #https://github.com/mozilla-mobile/fenix/issues/24362 . 

![Screenshot (Apr 5, 2022 1 40 43 PM)](https://user-images.githubusercontent.com/89388888/161736929-6978715a-d4a3-4af8-b797-7a5a9e158f93.png)

**Comment by delia-pop** [comment]
This issue is still reproducible on Beta 104.0b1 with Google Pixel 6 (Android 12).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807373

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
