### ISSUE TITLE
URL Bug

### ISSUE THREAD

**Issue by Nom544ad** [mozilla-mobile/fenix#23182]
### Steps to reproduce

 1.  Have To Look after the full code of website.
 2.  Edit Code If code is not correct.
 

### Expected behaviour

When We type Url in FireFox Browser  Like  https://www.example.com/search?client=chrome0-b-e&q=what++you+search   
Here The Search Engine is FireFox So when we put chrome insted of Firefox When we put chrome it should so eror but it is not showing eror

### Actual behaviour

When We type Url in FireFox Browser  Like  https://www.example.com/search?client=chrome0-b-e&q=what++you+search   
Here The Search Engine is FireFox So when we put chrome insted of Firefox When we put chrome it should so eror but it is not showing eror

### Device name

Oneplus Nord ce

### Android version

11

### Firefox release type

Firefox

### Firefox version

89.0.10

### Device logs

When We type Url in FireFox Browser  Like  https://www.example.com/search?client=chrome0-b-e&q=what++you+search   
Here The Search Engine is FireFox So when we put chrome insted of Firefox When we put chrome it should so eror but it is not showing Erorr

**Comment by kbrosnan** [comment]
The query parameters of a URL, `?client=chrome0-b-e&q=what++you+search`, require the website that is accepting the query parameter to act on it. There is nothing Firefox should be doing to the query parameters to modify them.
