### ISSUE TITLE
The collapsed "Inactive Tabs" button looks like a title that's describing all of your actually-active tabs (which are listed directly below it)

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#23189]
### Steps to reproduce

1. Have Firefox configured to hide inactive tabs (in Settings|Tabs,  "Close tabs: never" and "Move old tabs to inactive: [enabled]".
2. Have some inactive tabs (unviewed for 2 weeks) (I'm not sure if this is required or not for the inactive tabs section to show up, but I'm guessing it might be).
3. Open some new tabs with e.g. news articles.
4. Look at your tab list (e.g. by tapping the tab icon in the location bar), and scroll to the top.

### Expected behaviour

The UI shouldn't be confusing about which tabs are vs. aren't considered inactive.

### Actual behaviour

Right now the UI is confusing, and **it looks like it's saying all my tabs are inactive**.

At the top of my tab list, there's an outlined area (that kind of looks like a header/title) which says:
`[Inactive tabs   v           ]`

And then below that is a list of all of my tabs, including the ones that I opened today (which are definitely not inactive).

If I tap that header (which I didn't initially realize was something that I could do), then it expands into an area which actually contains the truly-inactive tabs.  So it seems this "header" is actually an autocollapsed section, which contains the inactive tabs.  But it very-much looks like a title for the tabs below it (particularly given the `v` downarrow, which I think we intend to be a "click to expand" signal, but it looks like it's just pointing to the list of things that follow).

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19139)

**Comment by dholbert** [comment]
![Screenshot_20220113-152857](https://user-images.githubusercontent.com/426803/149424958-4e4fb8a9-67be-4111-894b-62cd10655520.png)

**Comment by dholbert** [comment]
Previous comment has a screenshot for how this looks in my Firefox Nightly on Android right now.

As shown in the screenshot, there is:
(1) an outlined area saying "Inactive tabs" with a downarrow
(2) And then a list of all of my **active tabs**

...and this is easy to misunderstand as Firefox declaring all of your active tabs to be inactive (and under that misinterpretation, it makes it feel like our inactive-tab-determination-logic must be pretty-broken, because we seem to be saying all tabs are inactive).

**Comment by amedyne** [comment]
Tagging @topotropic

**Comment by dholbert** [comment]
Commenting to avoid stalebot auto-close. I assume the issue still exists, though I have the inactive tabs feature currently disabled so I can't tell for sure.

(I reenabled it just now, but tabs won't become inactive for 2 weeks.)

**Comment by dholbert** [comment]
> Commenting to avoid stalebot auto-close. I assume the issue still exists, though I have the inactive tabs feature currently disabled so I can't tell for sure.

Following up: I confirmed this still looks like my screenshot above in https://github.com/mozilla-mobile/fenix/issues/23189#issuecomment-1012612619

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813731

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
