### ISSUE TITLE
[Meta] Distribution Setup

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#232]
### Why/User Benefit/User Problem
* Allow partners to distribute Fenix

### What / Requirements
* Configurations

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11328)

**Comment by mkaply** [comment]
I'm going to update this issue with more details about what this means.

Partners need to customize these things (so far):

1. Homepage (and if that homepage can be displayed when a new tab i opened)
2. Bookmarks
3. Suggested sites (if applicable)
4. Additional search engines
5. Default search engine
6. Possible additions to user agent (device information primarily)

There also needs to be a unique distirbution ID that is reported via telemetry.

For Fennec, we had a few mechanisms:

https://wiki.mozilla.org/Mobile/Distribution_Files

Going forward, what would be preferred is a 100% server side solution that is can be updated as it changes. (Fennec was only updated at first install).

A unique partner identifier could be the only thing stored on the device and then the actual customizations could be queried from a server and loaded dynamically (and updated as necessary).

**Comment by cpeterso** [comment]
Of the partner customizations listed above, I think the only ones that might affect GeckoView are:

> 6. Possible additions to user agent (device information primarily)

Fennec's existing `general.useragent.device_id` code (from https://bugzilla.mozilla.org/show_bug.cgi?id=1262591) should already work in GeckoView, but we will need to test when the time comes.

> There also needs to be a unique distirbution ID that is reported via telemetry.

We might need to update the telemetry API between Fenix and GeckoView.

**Comment by fbertsch** [comment]
I just want to ensure we're planning on including a `distribution_id` as a new metric, which also needs to be included in the activation ping (along with every other ping). cc @vesta0 @Dexterp37

**Comment by vesta0** [comment]
Thanks @fbertsch for calling that out.

**Comment by kbrosnan** [comment]
Closing as this as part of https://github.com/mozilla-mobile/fenix/issues/26855. It does not have a clear set of requirements.
