### ISSUE TITLE
[Bug] The same site can be added multiple times to home screen

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#23202]
Depends on three-dot menu redesign: https://github.com/mozilla-mobile/fenix/issues/17796

## Steps to reproduce
1. Browse any site(wikipedia.com).
2. Tap on 3dot menu and select "Add to Home screen".
3. Tap again on the 3dot menu and select "Add to Home screen".

### Expected behavior
The "add to home screen" item will say "Remove from home screen" if the site has already been added.
~The option is greyed out for the pages that are already added to the home screen /or a message is displayed that the page is already added.~

### Actual behavior
The same page can be added multiple times to the home screen. 

### Device information
* Android device: Sony Xperia Z5 Premium (Android 7.1.1), Samsung Note 8 (Android 9.0)
* Fenix version: Firefox Nightly 2/5 #20360607

> Originally from https://github.com/mozilla-mobile/fenix/issues/8108

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19143)

**Comment by sflorean** [comment]
@gabrielluong we can close this? given the fact that 8108 is fixed and verified. Thank you!

**Comment by gabrielluong** [comment]
> @gabrielluong we can close this? given the fact that 8108 is fixed and verified. Thank you!

This is different from top sites and about adding it to your Android Home screen.
