### ISSUE TITLE
No success pop-up/ snackbar is displayed after adding manually a login 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#23214]
### Steps to reproduce

1. Go to settings - logins & password - saved logins.
2. Tap on "Add login" (bottom of the screen) and perform all the steps.
3. Tap on check mark.

### Expected behaviour

A message / pop-up is displayed informing the user that the login was added. 

### Actual behaviour

The screen is dismissed and the saved logins are displayed.

### Device name

Sony Xperia

### Android version

6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

97.0.0-beta.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19153)

**Comment by kbrosnan** [comment]
@mozilla-mobile/ux do we expect a toast in the case of manually adding a login or is the explicit action of adding it enough feedback?

**Comment by topotropic** [comment]
cc @ewachowiak

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812430

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
