### ISSUE TITLE
[Bug]: Content Tracking gets disabled after exiting Reader Mode

### ISSUE THREAD

**Issue by kelimuttu** [mozilla-mobile/fenix#23211]
### Steps to reproduce

1. Open an article page
2. Check content tracking by tapping on the padlock icon → Details → Tracking Content
3. Trackers are on the blocked list
4. Go back to the article and activate reader mode
5. Deactivate reader mode
6. Check the Content Tracking again as described in step 2
7. Trackers are now on the allowed list

### Expected behaviour

Trackers should remain on the block list

### Actual behaviour

Trackers are now on the allowed list after exit reader mode

### Device name

Huawei P30 Pro

### Android version

10

### Firefox release type

Firefox

### Firefox version

95.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19150)

**Comment by kelimuttu** [comment]
Before enabling reader mode: 
![photo_2022-01-14 17 31 51](https://user-images.githubusercontent.com/4922388/149501363-86aa556c-665f-4a60-9558-be177bc1c4ac.jpeg)


After disabling reader mode: 
![photo_2022-01-14 17 31 49](https://user-images.githubusercontent.com/4922388/149501375-bbebeebe-bad5-44ae-9388-72b023302220.jpeg)

**Comment by kelimuttu** [comment]
Originally reported at: https://twitter.com/tabulla_rassa/status/1479404998647758850

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-02-04.
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)
