### ISSUE TITLE
[Bug]: about:crashcontent/about:crashparent not working on different devices 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23215]
### Steps to reproduce

1. Open several tabs in Fenix.
2. Insert about:crashcontent in the URL field to trigger a crash in tab.
3. Observe if the tab crashes.
4. Open several tabs in Fenix.
5. Insert about:crashparent in the URL field to trigger a crash in app.
6. Observe if the app crashes.

### Expected behaviour

3. The tab crashes and a "Tab crashed" page is displayed in-app.
6. The app crashes and closes. A dialog is displayed.

### Actual behaviour

After both about:crashcontent and about:crashparent, the tab/app do not crash and the previous page is loaded and displayed.

### Device name

Tab Sony Xperia, Tab Huawei MediaPad M2

### Android version

 (Android 6.0.1),  (Android 5.1.1)

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.1

### Additional information

https://user-images.githubusercontent.com/89388888/149524736-f0ddc1df-b039-429b-aa6c-930386b3401a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19154)

**Comment by sflorean** [comment]
I was able to reproduce this ( only about:crashparent) on OnePlus 9 (Android 11) on 97.0.0-beta.2.

**Comment by delia-pop** [comment]
Reproducible on Beta 102.0.0-beta.3 with Tab Huawei MediaPad M2 (Android 5.1.1).

**Comment by delia-pop** [comment]
Still reproducible on Beta 109.0.0-beta.5 with Tab Huawei MediaPad M2 (Android 5.1.1).
