### ISSUE TITLE
Deleting a saved login, the account is still displayed on the list

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23212]
### Steps to reproduce

1. Navigate to some sites and save the logins
2.  Go to Settings -> Logins and passwords -> Saved logins 
3. Select a saved login from the list
4. Tap on the three dot menu from the top-right corner and select Delete option
5. Verify if the saved login is deleted from the list

### Expected behaviour

After deleting a saved login, the account must be deleted from the list automatically.

### Actual behaviour

After deleting a saved login, the account is still displayed on the list and can be tapped on.

- the user needs to navigate back to "Logins and passwords" section -> Saved Logins in order to have the list updated correctly.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19151)

**Comment by sflorean** [comment]
This is still reproducible on 101.0.0-beta.1.

**Comment by SoftVision-LorandJanos** [comment]
This is still reproducible on 102.0.0-beta.1.

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 109.0a1 (2022-12-12) build.
Device used: Oppo Find X5 (Android 12).
Reopening the ticket.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812431

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
