### ISSUE TITLE
FNX-5589 ⁃ [Bug] Selected collection creation item has clipped title

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2321]
## Steps to reproduce
1. Open several tabs
1. Select "save to collection"
1. Select a tab that has a long(ish) title

### Expected behavior
1. The tab is selected and the title is not clipped

### Actual behavior
1. The title is clipped

![](https://user-images.githubusercontent.com/4400286/57324768-6230b580-70bd-11e9-946f-8faa5bc55c86.png)

**Comment by cadeyrn** [comment]
Is still an issue? I cannot reproduce.

**Comment by sblatz** [comment]
I can't produce this anymore either. Labeling as QA needed.

**Comment by softvision-miralobontiu** [comment]
I wasn't able to reproduce either on the latest build 1.0.1920 (@11391807), with Samsung Galaxy S8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
