### ISSUE TITLE
False triggering of the clear buttons in edit bookmark UI

### ISSUE THREAD

**Issue by bigConifer** [mozilla-mobile/fenix#23228]
### Steps to reproduce

1. Open a bookmark in edit mode
2. Scroll through the text input fields using swipe gestures towards the right edge of the screen.
3. As soon as you release your finger at the right end where the clear button is located, it will be triggered and the text field will be emptied.

### Expected behaviour

In bookmark edit mode you could scroll through long URLs or bookmark titles without accidentally clearing them. The clear button should only be triggered by real click events.

See `EditToolbar` for reference on how it could be implemented:
- https://github.com/mozilla-mobile/firefox-android/blob/7776c2d600ead933a4736964530b304a8317a954/android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt#L98-L102
- https://github.com/mozilla-mobile/firefox-android/blob/7776c2d600ead933a4736964530b304a8317a954/android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_edittoolbar.xml#L77-L89

### Actual behaviour

The current `ClearableEditText` construct just listens to `ACTION_UP` motion events with a X-coordinate at the right end of the screen.
This leads to false triggering if not explicitly clicked!
https://github.com/mozilla-mobile/fenix/blob/1bc9ee5367d24e651ab3f3a7e39620b0a709eae5/app/src/main/java/org/mozilla/fenix/utils/ClearableEditText.kt#L30-L43
https://github.com/mozilla-mobile/fenix/blob/fb0db112656c51ad64ab316b77d453ceb2c62c65/app/src/main/res/layout/fragment_edit_bookmark.xml#L67-L79

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19164)

**Comment by bigConifer** [comment]
Is there anything against designing the clear button for edit_bookmark in the same way as for browser_toolbar_edittoolbar, by using a real UI-Element with onClickListener?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812171

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
