### ISSUE TITLE
Send tabs to device does not also help close them

### ISSUE THREAD

**Issue by MissTcat** [mozilla-mobile/fenix#23222]
### Steps to reproduce
1. Select some tabs
2. Send to device

### Expected behavior
Tabs get sent AND
Selection stays selected so a new action can be done such as closing multiple tabs at a time.
It used to be like this a few months ago before an update.

OR

'Send and close tabs' button should be there.

### Actual behavior
Tabs get sent and screen immediately switches to the last open tab.

### Device information

* Android device: SM-N986B/DS
* Reference Browser version: 95.2.0 (Build #2015851755)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19161)

**Comment by MissTcat** [comment]
> > It used to be like this a few months ago before 'collections' arrived.
> 
> There are no collections in Reference Browser. If this was meant for Fenix, Collections have been there since the 1.0 release.
> 
> This is still a valid bug, so I'm going to move it from Reference Browser to Fenix.

I edited the original comment.
Thanks for moving it to the right place.

**Comment by MissTcat** [comment]
I wonder if there is anyone I can buy a coffee, a meal or whatever to look into this issue. It drives me crazy!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813732

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
