### ISSUE TITLE
Support displaying all bookmarks on home page (not just recent ones).

### ISSUE THREAD

**Issue by Imold** [mozilla-mobile/fenix#23227]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
The ability to basically have the bookmarks dialog be my home page

### How do you know that this problem exists today? Why is this important?
The closest thing to having bookmarks on home page is "Recent bookmarks"

### Who will benefit from it?
Every one who has been asking for bookmarks to be put back on the home page 

### Note
This is not a duplicate of #9193. #9193 is about bookmarks on the homescreen of the phone, This is about bookmarks on the browser home page.
#23218 was Incorrectly closed as a duplicate of #9193 when it was not.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19163)

**Comment by mispp** [comment]
The current ux is really bad. I also find 'top pages' to be crap ... not only 'recently bookmarked'.

This ux seems as reimplementation of 'same feeling as chrome' but in much worse and slower toolkit. In that case bromite might be a better option.

**Comment by litLizard69** [comment]
> The current ux is really bad. I also find 'top pages' to be crap ... not only 'recently bookmarked'.
> 
> This ux seems as reimplementation of 'same feeling as chrome' but in much worse and slower toolkit. In that case bromite might be a better option.

It's sad to see how much better v68 was compared to today. It had much more feature and was much more logical in UI/UX..

Mozilla, bring back the old UI, maybe give a little facelift BUT don't change it in features, please!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812406

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
