### ISSUE TITLE
Add a generalized `FenixSnackbar` composable

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#23221]
As of Compose 1.0.5, the platform version of a `Snackbar` is missing parameters that we require in order to easily match the [design spec](https://www.figma.com/file/TebIgESfWmQkMcEmwNaYZl/Android?node-id=1399%3A590) for our snackbars. 

Add a general version that use our designs but still expose customizable messages and actions. 

See also the [XML layout](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/res/layout/fenix_snackbar.xml) for our snackbar to match previous design.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19160)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814198

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
