### ISSUE TITLE
[Bug]: Context Menu Search doesn't trigger reliably the second time it is used on the same word

### ISSUE THREAD

**Issue by Sayrus** [mozilla-mobile/fenix#23224]
### Steps to reproduce

1. Open a tab to any website where you can select text
2. Highlight a term and use `Search` from the context menu
3. Close the tab (tested using the Back button and by opening the Tab List and pressing X). This closes the tab and return to the tab from 1.
4. Highlight the same term again (it can be from a different location but it must be the same content) and use `Search` from the context menu
5. Bug triggered (Nothing happens)
6. Bonus: Leave (without fully closing) the app and come back or lock/unlock the phone: the search triggers

### Expected behaviour

A new tab with the Search opens just like the first time

### Actual behaviour

Nothing happens

### Device name

Xiaomi Mi Mix 3

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015857227)

### Additional information

Video:
![output](https://user-images.githubusercontent.com/22404472/149602108-9ac964b7-b0ee-481f-a0b0-bf2b74a85701.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19162)

**Comment by marcel263** [comment]
Thank you for reporting, this is a duplicate see  #19363 then info provided especially 6th step is worth mentioning

**Comment by Sayrus** [comment]
> Thank you for reporting, this is a duplicate see #19363 then info provided especially 6th step is worth mentioning

I searched for it but didn't find the issue. Shall I close this one?
