### ISSUE TITLE
[Bug]: Don't detect the theme

### ISSUE THREAD

**Issue by casoftcol** [mozilla-mobile/fenix#23231]
### Steps to reproduce

When Open Firefox bye default the theme is dark, but My phone is black.

If Open Settings and change the theme bye black ir phone default, when exit tonhome screen automático return yo dark

### Expected behaviour

My phone theme ir black theme

### Actual behaviour

Dark theme

### Device name

Samsung galaxy note 20 plus

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19167)

**Comment by kbrosnan** [comment]
What phone?

**Comment by casoftcol** [comment]
Samsung Galaxy Note 20 Ultra with Android 12 Secure Pach Dicember
UI 4.0

**Comment by kgorol** [comment]
Firefox literally stopped detecting my system theme. Every time it changes I have to manually restart Firefox if it was in background during the theme switch.

S20 FE with Android 12.

**Comment by dipeve** [comment]
Same thing (S21, android 12 January patch), but from my experience, when the theme change is manual it changes correctly. It is in the morning, after the automatically set change from dark mode, that it keeps the dark mode instead of getting the light one.

**Comment by kgorol** [comment]
Does anybody even look at these issues?

**Comment by hkaancaliskan** [comment]
I can confirm what @kgorol said on A52 Android 12 with 5/27 nightly.
Theme stays white when phone switched to dark theme automatically vice versa, need to close the Firefox and restart to apply theme correctly. There is no problem on other apps or system itself.

**Comment by hkaancaliskan** [comment]
https://user-images.githubusercontent.com/17825767/171384610-fff6a856-3754-4858-89d0-bc0d1e2d1289.mp4

**Comment by hkaancaliskan** [comment]
https://user-images.githubusercontent.com/17825767/171384954-0fef2d54-30ed-41ca-8102-8230afa7f4f6.mp4
