### ISSUE TITLE
Firefox not detecting download link

### ISSUE THREAD

**Issue by rsssxd** [mozilla-mobile/fenix#23230]
### Steps to reproduce

Visit the download link below on Firefox and Chromium.

https://bigota.d.miui.com/V12.1.1.0.RFJEUXM/davinci_eea_global_images_V12.1.1.0.RFJEUXM_20210903.0000.00_11.0_eea_3c22137238.tgz

### Expected behaviour

Firefox and Chromium offer file download option

### Actual behaviour

Chromium browsers offer a download option, but Firefox does nothing.
![Screenshot_20220116-110910_Mull](https://user-images.githubusercontent.com/60405617/149652582-1104d84f-b568-44de-9498-803632909ec2.png)
![Screenshot_20220116-110921_Mulch](https://user-images.githubusercontent.com/60405617/149652584-b7a3f9b8-212b-4678-8f0b-0d2a4ba40b55.png)

### Device name

Mi 9T

### Android version

Android 10 

### Firefox release type

Firefox Nightly

### Firefox version

98 0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19166)

**Comment by LaviniaL99** [comment]
Hello @rsssxd 

Thanks for your report!

I retested the above flow on the latest Nightly build (100.0a1) and latest RC build (98.3.0) and i was not able to reproduce the issue -> before retesting the flow, the device language was changed to Turkish.

**Device used:**

- Samsung S10E - Android 10

Can you please retest the issue on the latest builds and verify if you are still able to reproduce the above flow? If yes, please attach a video of it.

**Comment by rsssxd** [comment]
https://user-images.githubusercontent.com/60405617/160402535-3828f9f1-2eab-4731-bc28-1347a69df912.mp4

**Comment by rsssxd** [comment]
The problem still persists for me.
