### ISSUE TITLE
Show favicons in List-style tab view

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#23234]
When the user has selected List-style tab view (Settings > Tabs > List), the favicons for websites aren't shown. Favicons are important for familiarity and fast recognition/identification of websites. Not showing them is bad. Also, Grid-style tab view _does_ show favicons, so it makes sense to do this.

**Comment by willfs84** [comment]
Oops I just filed a duplicate, but I think my title and description is better :D https://github.com/mozilla-mobile/fenix/issues/13339

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/13339
