### ISSUE TITLE
FNX-5592 ⁃ Implement a confirmation / instructions dialog

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#2324]
For Firefox Accounts and Sync features, we need the following dialog paradigm implemented:

<img src=https://user-images.githubusercontent.com/128755/57331273-30801480-70e6-11e9-8d3b-30fe11e2243a.png width=250 />

<img src=https://user-images.githubusercontent.com/128755/57331296-3970e600-70e6-11e9-8400-b3c00808e460.png   width=250 />

**Comment by Amejia481** [comment]
I did something similar for site permissions [here](https://github.com/mozilla-mobile/android-components/pull/2909) or you can use [BottomSheetDialogFragment](https://developer.android.com/reference/android/support/design/widget/BottomSheetDialogFragment) but it comes with extra animations and behavior.

![Screenshot_20190507-160113](https://user-images.githubusercontent.com/773158/57335709-755d7880-70f1-11e9-8d51-1809076d3fb7.png)

**Comment by ekager** [comment]
See https://github.com/mozilla-mobile/fenix/issues/2528 for follow up issue for bottom sheet dialog UI

**Comment by sv-ohorvath** [comment]
@ekager The dialog in the second image from the description, the one with the Disconnect button, I assumed it would appear at sign out, but it doesn't. Could you help me with some details, how can I get to it?

**Comment by boek** [comment]
@sv-ohorvath There won't be a modal for sign out in the MVP. We passed string freeze so we will have to get to it post MVP

**Comment by boek** [comment]
Filed a follow up: #3134
