### ISSUE TITLE
[Bug] [L10N]: ETP - The first two options are not fully translated in Hindi

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23268]
### Steps to reproduce

1. Set the app language to Hindi.
2. Navigate to the main menu -> Enhanced Tracking Protection
3. Verify if the first 2 options are fully translated.

### Expected behaviour

The first 2 options from ETP must be fully translated in Hindi.

### Actual behaviour

The first 2 options from ETP are not fully translated in Hindi. Please see the screenshot attached for evidence.

![ETP](https://user-images.githubusercontent.com/96047134/149951289-9efe9773-4768-46c3-8f20-ba74c756a485.JPEG)

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.2

**Comment by Delphine** [comment]
Seems like this has never been updated in Pontoon.
@ShivanshGoel221B Could you please help update this on Pontoon, as explained in #23295?
In the meantime, I'm closing this bug as it shouldn't be an issue  - since the localizations don't exist in Pontoon yet. thanks
