### ISSUE TITLE
[Bug]: Unable to connect to websites when using Google DoH

### ISSUE THREAD

**Issue by wangyifan349** [mozilla-mobile/fenix#23265]
### Steps to reproduce

about:config
network.trr.mode  3
network.trr.uri      https://dns.google
network.trr.bootstrapAddress   223.5.5.5
network.proxy.http  127.0.0.1
network.proxy.http_port    1080
network.proxy.type   1
network.proxy.socks_remote_dns  False
I did not configure socket parameters

However, a valid HTTPS proxy is configured
In any Windows version of Firefox, it can surf the Internet

However, in the Android version, it will not be able to access the Internet. I guess the reason is that DNS query(https://dns.google) does not use  proxy!

### Expected behaviour

223.5.5.5  not use  proxy.
https://dns.google  use  proxy(127.0.0.1:1080).

### Actual behaviour

Android devices cannot be used, but windows devices can be used

### Android version

android  11 （xiaomi 11 pro）

### Firefox release type

Firefox Beta

### Firefox version

97.0a1

### Device logs

about:config
network.trr.mode  3
network.trr.uri      https://dns.google
network.trr.bootstrapAddress   223.5.5.5
network.proxy.http  127.0.0.1
network.proxy.http_port    1080
network.proxy.type   1
network.proxy.socks_remote_dns  False
I did not configure socket parameters

However, a valid HTTPS proxy is configured
In any Windows version of Firefox, it can surf the Internet

However, in the Android version, it will not be able to access the Internet. I guess the reason is that DNS query(https://dns.google) does not use  proxy!

### Additional information

about:config
network.trr.mode  3
network.trr.uri      https://dns.google
network.trr.bootstrapAddress   223.5.5.5
network.proxy.http  127.0.0.1
network.proxy.http_port    1080
network.proxy.type   1
network.proxy.socks_remote_dns  False
I did not configure socket parameters

However, a valid HTTPS proxy is configured
In any Windows version of Firefox, it can surf the Internet

However, in the Android version, it will not be able to access the Internet. I guess the reason is that DNS query(https://dns.google) does not use  proxy!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19191)

**Comment by kbrosnan** [comment]
@agi or @jonalmeida do you think this is a Core bug?

**Comment by jonalmeida** [comment]
Yeah, this probably is.
