### ISSUE TITLE
FNX-5594 ⁃ Develop UI for SendTab to "send" tabs

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#2326]
<img src=https://user-images.githubusercontent.com/128755/57334721-8bb60500-70ee-11e9-92fb-bca32133f5ff.png width=200 />

Related to https://github.com/mozilla-mobile/fenix/issues/246
Ref: https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357470302

cc @grigoryk

**Comment by grigoryk** [comment]
Discoverability issues aside, a Quck action bar would be a cool place to place devices "most used" as targets.

**Comment by vesta0** [comment]
@vladikoff @bifleming  is the send tab component ready?

**Comment by vesta0** [comment]
Dup of #331
