### ISSUE TITLE
FNX-5595 ⁃ Add Firefox Sync error states to Settings and Browser UI

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#2327]
This depends on a-c to provide these errors

Ref: https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357473105

<img src=https://user-images.githubusercontent.com/128755/57334779-b99b4980-70ee-11e9-87ff-d00148d60f47.png width=270 />

- - -
<img src=https://user-images.githubusercontent.com/128755/57334784-bdc76700-70ee-11e9-9104-42549bd82ef9.png width=270 />

cc @grigoryk

**Comment by vladikoff** [comment]
Reconnect Sync UI as well: 

<img src=https://user-images.githubusercontent.com/128755/57334845-e4859d80-70ee-11e9-9ffd-cc04f72d3891.png width=300 />

Ref: https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/357473106

**Comment by grigoryk** [comment]
A-C pre-req: mozilla-mobile/android-components#2724

**Comment by sblatz** [comment]
Can we drop the "notification dot" on the menu icon for MVP? After speaking with @pocmo it sounds like it'll be difficult to do in the next 24 hours, and require a bit of a-c work.
@vesta0

**Comment by sblatz** [comment]
Verified with Vesta we are bumping that feature to post MVP.

Fenix ticket [here](https://github.com/mozilla-mobile/fenix/issues/2793)

**Comment by grigoryk** [comment]
Done in #2802

**Comment by sblatz** [comment]
@grigoryk let's have QA test this, then they'll close 😄

**Comment by softvision-miralobontiu** [comment]
Hi,
Tested with build 1.0.1922 (#11510609), with Sony Xperia Z5 Premium (Android 7.1.1), and I got two scenarios:
1. I've signed in on a single device. Tried to share a tab on another device. This is what was displayed:

![2019-05-31](https://user-images.githubusercontent.com/40694158/58696784-ec102d80-83a0-11e9-812e-07e81dd3d90a.gif)

2. Filed a bug #3036 

![crash](https://user-images.githubusercontent.com/40694158/58696776-e9153d00-83a0-11e9-8435-56a27a93d364.gif)

@vladikoff could you guide me with some STR? I was not able to encounter all error sync states from https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/364885746.
Thank you!

**Comment by sblatz** [comment]
@grigoryk are these issues you can investigate?

**Comment by jonalmeida** [comment]
> I've signed in on a single device. Tried to share a tab on another device. 

For 1, this is an expected issue since not all device info will have sync'd after the initial sign in. Could you file a bug for this and cc me please? Thanks @softvision-miralobontiu !

**Comment by grigoryk** [comment]
I'm testing this locally and seeing lots of issues with account state not being correctly reflected in the UI. Started to work on this in https://github.com/mozilla-mobile/fenix/pull/3116.

Some a-c changes are required, see relevant PRs: https://github.com/mozilla-mobile/android-components/pull/3234 and https://github.com/mozilla-mobile/android-components/pull/3233.

**Comment by grigoryk** [comment]
@sblatz a-c changes are transparent to fenix; it just makes the api function as you'd expect. But other than that, I'm making other fenix-side changes in #3116.

**Comment by grigoryk** [comment]
After testing error states with very large fonts, it's obvious we can't fit the warning icon on the right as well as text. I think that's okay for now - we already have a warning icon on the left!

So we'll ship with just the icon on the left, as is seen in the screenshot below.
![image](https://user-images.githubusercontent.com/465422/58988962-b6e84e80-8797-11e9-8aef-aba8e0622e6e.png)

**Comment by sblatz** [comment]
Should be ready for qa now that https://github.com/mozilla-mobile/fenix/pull/3116 is merged!

**Comment by softvision-miralobontiu** [comment]
@sblatz I'm still confused about what steps are required in order for us to encounter the Sync errors.

I've created a new account, did not verify it on email, and expected to see an error on Settings, but nothing was displayed. I'm just being redirected to the Sign-in page. 
I tried to share a page, and I still got redirected to Sign-in form. None of the messages from the attached screenshot were displayed.

![Screenshot_1](https://user-images.githubusercontent.com/40694158/59104333-00709f00-893a-11e9-8ea7-b650581957f3.png)

I didn't get any of the error messages from https://mozilla.invisionapp.com/share/QSR2F8UD4PN#/screens/364885748

**Comment by sblatz** [comment]
@softvision-miralobontiu the easiest way to trigger a sync error is:
1. Sign into FxA on Fenix
2. Verify through email if needed
3. Change your password on the desktop client
4. Wait for a minute (may need to force quit and re-open the Fenix app to get it to trigger a sync)


Then Fenix should show all the relevant UI in browser and in settings!

**Comment by softvision-miralobontiu** [comment]
Thanks, Sawyer!
I've followed the steps you recommended. The error message "Reconnect to resume syncing" was displayed.
Tested with Samsung Galaxy Tab A 6 (Android 5.1.1), and Motorola Nexus 6 (Android 7.1.1), with the latest build 1.0.1924 (6/10).
