### ISSUE TITLE
[Bug]: The keyboard is dismissed when trying to manually add a login after tapping the search button

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#23272]
### Steps to reproduce

1. Login in to Firefox with an account that has several saved logins or store a few logins;
2. Go to the Saved logins section;
3. Tap on the search icon in the upper right corner;
4. Tap the Add login button located above the keyboard.

### Expected behaviour

The keyboard should remain open allowing the user to manually enter a login.

### Actual behaviour

The keyboard is dismissed and the input fields need to be tapped again in order to bring it up.

### Device name

Google Pixel 6

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 2022-01-18.

### Additional information

![Logins](https://user-images.githubusercontent.com/50983519/149982400-defc9ab5-b1f0-4c9b-98c6-5130a76fa5ba.gif)

**Comment by kbrosnan** [comment]
Looks like we should pull focus from the search bar.

**Comment by mcarare** [comment]
This also reproduces on the play store version.

**Comment by Alexandru2909** [comment]
I would like to work on this.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Preview Nightly 2022-01-20 and the issue no longer occurs. When the add login button is tapped after tapping the search logins button, the keyboard is no longer dismissed. I will mark this issue as closed:

### Device used:
- Google Pixel 6 (Android 12)
