### ISSUE TITLE
FNX-5596 ⁃ [Bug] Tab count takes a very long time to update

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2329]
I **believe** this is because we're now allowing users to "undo" tab removal. Perhaps when we select a tab, though, it should automatically remove the tab as the user wouldn't want to "undo" at this point anyway.

![Tab count 2019-05-07 16](https://user-images.githubusercontent.com/4400286/57338699-33c5d100-70e3-11e9-8c9b-3dd6d7174266.gif)UNITO-UNDERSCORE!14!UNITO-UNDERSCORE!23!

**Comment by bsurd** [comment]
Verified on a Nexus 5 and OnePlus 5T. The issue is no longer reproducible with the latest build (5/15).
