### ISSUE TITLE
FNX-5597 ⁃ [Meta] Request Desktop Site

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#233]
## Why/User Benefit
* Some websites don't work well for users because the mobile website is being loaded
* Some websites provide a different version of their offering on mobile vs. desktop
* Many user reviews (see below) have been asking for a solution to switch to a website's desktop site

## What
* Include option to switch to Desktop site

## Acceptance Criteria (how do I know when I’m done?)
* Option to switch to desktop website and back to mobile (if needed)
* Correct version of website is shown
* Probe how often users switch between desktop and mobile

**Comment by ekager** [comment]
We have request desktop site working now in the browser menu, but we will need to add telemetry for the last point.
