### ISSUE TITLE
Add Settings for enabling Contile Feature

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#23304]

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Nightly debug build 2022-03-03 and can confirm the "Sponsored shortcuts" setting is present in the Homepage menu. If the option is turned on sponsored tiles are displayed on the home screen (if they are available), turning the option off will remove them.
![Sponsored shortcuts](https://user-images.githubusercontent.com/50983519/157219202-aec3c4ca-b0f4-488f-9cf0-a68e266483a5.JPEG)
