### ISSUE TITLE
[Bug]: Firefox for Android crashes on Vodafone's speedtest page

### ISSUE THREAD

**Issue by GiantCrocodile** [mozilla-mobile/fenix#23307]
### Steps to reproduce

1. Go to https://speedtest.vodafone.de/ in Firefox's private mode on your Android smartphone
2. Execute a speedtest
3. Firefox just closes (looks like crashed; about:crashes shows no recent crash report)

### Expected behaviour

Speedtest is properly executed

### Actual behaviour

Firefox/App just closes

### Device name

Huawei P30 Pro

### Android version

11

### Firefox release type

Firefox

### Firefox version

95.2.0 (Build #2015851755)

### Additional information

Test performed in Germany via WIFI

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19209)

**Comment by kbrosnan** [comment]
Is there a crash ID for the crash? https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by GiantCrocodile** [comment]
There is no crash with date of yesterday thus about:crashes shows nothing I can provide. There are only older entries.

**Comment by reyis4402** [comment]
Tested with Firefox 96. Firefox crashes or fails in the speed test.

Device : Redmi k20 Android 10

**Comment by kbrosnan** [comment]
Using the `Using adb logcat to get crash information` section would be helpful if there is not any information in the crash reporter section.

**Comment by sheikh-azharuddin** [comment]
I too faced same issue...after running the test firefox simply closed no crash message or report nothing

I am using asus rog3 running on A11

**Comment by GiantCrocodile** [comment]
I can't provide this information as my environment wouldn't allow it. I think someone else has to provide this if it's strictly necessary.

**Comment by GiantCrocodile** [comment]
Still crashing for Firefox 100.3.0 (build #2015881499), 409a30ff0+ on EMUI v12 (Huawei P30 Pro).

**Comment by GiantCrocodile** [comment]
Reopen.

**Comment by sheikh-azharuddin** [comment]
> Reopen.

They won't ..anyway no use
You need to live at the mercy of mozilla to fix issues when they want ..don't expect immediate resolution they have deployed bot to close issues which were not taken care by mozilla
