### ISSUE TITLE
add reload button in the address bar

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#23316]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently pull to refresh is very buggy in firefox...in some sites it works fine other site it gets triggered on simple scrolling and in some sites not working..so to reload the page one has to do 2 clicks...please add the reload button in the address bar itself.
This can be achieved easily by showing only the primary domain name in the address bar same as samsung or yandex browser which will add sufficient space to add reload button, add on button , open in app button and bookmark
.also I feel the font size can be reduced for the url and other menu items which will make it more compact

### How do you know that this problem exists today? Why is this important?
It always takes 2 steps to reload the page

### Who will benefit from it?
All users

![Screenshot_20220120-091934340 (1)](https://user-images.githubusercontent.com/58127841/150269997-199d61bb-f935-45c3-9311-0876df61f805.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19214)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814155

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
