### ISSUE TITLE
Ensure visualCompletessQueue is not impacting cold page load, first user interactions

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#23310]
_edit: see 2nd comment because this one isn't quite what we want: https://github.com/mozilla-mobile/fenix/issues/23310#issuecomment-1028390938_

The visualCompletenessQueue continues to execute more code. We've neglected it for a while. We should consider improving it in these ways:
1. iirc, the queue executes tasks synchronously. This could cause jank or slow page load if the user tries interact while the queue is running. It would be better if we executed a task, yielded, executed a task, yielded, etc.
1. the queue runs ~5s after start up starts, i.e. it's not a visualCompletenessQueue. It's difficult to implement that – perhaps we should change the goal to be a `runWhenIdleQueue` or `runWhenIdleStartupQueue` so that the queue doesn't execute at an arbitrary 5s, potentially blocking user interactions and so that it can resume running after a page load completes
1. we never want it to get cancelled because then we have to re-run it. Verify it doesn't run on a cancellable scope (is it MainScope? is it cancellable? does it benefit from being a coroutine?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19213)

**Comment by mcomella** [comment]
Triage: we're concerned that the visual completeness queue is slows page load or the first user interactions, both because it blocks the UI thread but also that it triggers background (IO?) jobs. **We should run tests/telemetry to understand the impact.** For example, we could add:
- a local cold page load test where we a) trigger visual completeness queue to start when page load measurement starts and B) ensure it doesn't overlap and compare if it has an impact on page load
- (limiting learning b/c doesn't show overlap) add telemetry to measure the time visual completeness queue takes to run
- add telemetry to measure overlap of queue and page load

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807348

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
