### ISSUE TITLE
FNX-5599 ⁃ [Bug] Closing tabs, starting to open a new one, and backing out incorrectly displays previously closed tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#2332]
## Steps to reproduce
* Load a page
* Click tabs tray
* Press "x" on each tab to close all tabs
* Press "+" to open tab
* Press back to return to tab home screen

### Expected behavior
"No tabs opened" is displayed

### Actual behavior
A previously opened tab is displayed. This tab will disappear a few moments later by itself.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1919

Related? #1909 #2329 #2331

**Comment by ekager** [comment]
Closed by #2333
