### ISSUE TITLE
[Bug]: Bck2Brwsr benchmark gets slower and slower with fenix on each iteration

### ISSUE THREAD

**Issue by ceisserer** [mozilla-mobile/fenix#23336]
### Steps to reproduce

1. Go to: https://www.teavm.org/live-examples/jbox2d-benchmark/bck2brwsr.html (benchmark of a Java->JavaScript compiler benchmaring some physics simulation)
2. the benchmark runs an infinite number of repititions

### Expected behaviour

While with firefox on desktop as well as chrome on android, the runtime of each iteration stays more or less constant after the JIT warm-up. I would expect Fenix on Android would behave the same.

### Actual behaviour

The benchmark gets slower and slower each iteration when running it within Fenix. I was able to reproduce the behaviour Sony Xpera XZ1 Compact as well as a Snapdragon-652 based Xiaomi smartphone. I was able to oserve it with beta and nightly.

### Device name

Sony Xpera XZ1 Compact

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19222)

**Comment by kbrosnan** [comment]
Does this happen using the Geckoview example browser? https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt
