### ISSUE TITLE
Https-only mode error page

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23337]
Following https://github.com/mozilla-mobile/fenix/issues/16952 we need to update the default error page to something offering more context and probably a "Continue to HTTP site" button similar to what's been done on Focus.

| Default error page | Focus error page |
| -- | -- | 
| ![image](https://user-images.githubusercontent.com/11428869/150400975-dcd6241c-69ca-40cf-90ae-621749513a5a.png) | ![image](https://user-images.githubusercontent.com/11428869/150400910-b6bf237b-55b2-4f65-891a-a1ded15317aa.png) | 

We could have a different error page offering more context, as suggested in https://github.com/mozilla-mobile/android-components/issues/11306.

Asking UX about the design and text to use. 
cc @topotropic 

-------

Fenix design is available at https://www.figma.com/file/RyIADLmC3B0BIS9jSiAti3/?node-id=1238%3A63076

<img width="399" alt="image" src="https://user-images.githubusercontent.com/11428869/156724139-c3ab9771-6436-497a-b94a-9725553ffb63.png">

**Comment by Mugurell** [comment]
@Amejia481 Regarding the "continue" button which should store an exception from erroring on http I think the exceptions should be handled by GeckoView to allow for a smooth UX that would load the http webpage without any hiccup.
I imagine rather GV/Gecko seeing that the webpage is using http and deciding whether to send an error or continue to load the webpage anyway.
The API Focus uses - `document.reloadWithHttpsOnlyException()` doesn't seem useful on Fenix.
Thoughts?

**Comment by Amejia481** [comment]
> @Amejia481 Regarding the "continue" button which should store an exception from erroring on http I think the exceptions should be handled by GeckoView to allow for a smooth UX that would load the http webpage without any hiccup.
> I imagine rather GV/Gecko seeing that the webpage is using http and deciding whether to send an error or continue to load the webpage anyway.

Yes, agree, I'm not completely sure if this API is already implemented on GV, maybe @agi could help to clarify, maybe the could expose the same API that desktop is using.

> The API Focus uses - document.reloadWithHttpsOnlyException() doesn't seem useful on Fenix.
> Thoughts?

I think we could use it, as we'll only need the API for storing the exemption to run before that, maybe the API is also on JS and we just need to expose reading the exception on GV.

**Comment by agi** [comment]
I'm not sure I'm following, what's the problem with `reloadWithHttpsOnlyException`? If you call that after the user taps on "Continue to HTTP site" the pageload will go through using HTTP. What's the piece of functionality that's missing?

**Comment by Amejia481** [comment]
In desktop, we after users indicate that they want to allow an HTTPS to load the page, they can [persist that decision ](https://support.mozilla.org/en-US/kb/https-only-prefs#w_add-exceptions-for-http-websites-when-youre-in-https-only-mode). The API we are thinking should be on the GV side is the storage part for this exceptions, I'm not sure if GV could expose the same storage that desktop is using.

**Comment by Mugurell** [comment]
> I'm not sure I'm following, what's the problem with `reloadWithHttpsOnlyException`? If you call that after the user taps on "Continue to HTTP site" the pageload will go through using HTTP. What's the piece of functionality that's missing?

@agi 
When users first click "continue.." we'd want to:
- store the http exception for that specific website
- use `reloadWithHttpsOnlyException` to reload the webpage and access it through http

&nbsp;
When users access a previous page for which they tapped "continue.." we'd want to:
- just load the webpage, in one go, withough GV erroring and then us calling reload - like it would happen if we persist the exception in the client.

If GV would persist the http exception it could know to not send us the error and load the http page without us having to reload it so this will be totally transparent to the user.

**Comment by agi** [comment]
Makes sense! Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1753099

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 100.0a1 (2022-03-30) build.
Devices used:
- Google Pixel 4 (Android 11).
- Oppo Reno 6 (Android 12).

Closing the ticket as fixed.
