### ISSUE TITLE
wordpress gallery is not displayed on Android

### ISSUE THREAD

**Issue by ChristianNext** [mozilla-mobile/fenix#23347]
Wordpress gallery is blank when displayed with Firefox Android. It shows with Chrome Android and on Ubuntu desktop with Firefox 96.0.1

95.2.
![AndroidChrome](https://user-images.githubusercontent.com/29887671/150528019-2af9d050-5e88-4e96-b120-1d4cdb2f668d.jpg)
![AndroidFirefox](https://user-images.githubusercontent.com/29887671/150528022-1b44e8da-0bf5-4279-9348-4ace0eecce89.jpg)
0

**Comment by kbrosnan** [comment]
Website in screenshots is https://seidear.com/

This works for me using Firefox 96 and Nightly 98 on a Pixel 6 Pro

**Comment by ChristianNext** [comment]
Confirm: works with 96.2.0
