### ISSUE TITLE
Firefox endless crash after using a specific page (SQLLiteBlobTooBigException)

### ISSUE THREAD

**Issue by SpraxDev** [mozilla-mobile/fenix#23349]
## Steps to reproduce
Can't test it myself as it endlessly crashes but I suspect:
1. Visit https://huggingface.co/spaces/akhaliq/Detic, a demo page for an AI model if I am not mistaken
2. Upload an image twice (in my case trying to upload a second one made it crash and never recover from it), not reloading a page

### Expected behavior
When Firefox crashes to at least only mark the tab as broke or crashed

### Actual behavior
* The whole app crashes and occasionally crashes while in the background (Firefox's auto crash reporter seems to work/run just fine)
* I can no longer open the App
* I can not click on URLs in other apps that would normally open Firefox (I don't see it crash or trying to open but it probably does?)
* Clearing the cache in Android settings doesn't help (clearing app data probably would but I'd like to avoid that)

I'd like to add the stack trace I can see in  the Android Feedback/Bug report dialog but I cannot copy from it so here is a part of it I wrote down (Tell me if you need the whole thing, but maybe you can see my report in your dashboard already):
```
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=11
  at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
  at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
//  ... # Getting tiered of android.database stuff
  at mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabDao_Impl$4.call(RecentlyClosedTabDao_Impl.java:12)
  at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:8)
// ... # The following is kotlin coroutines androidx.room.TransactionExecutor and finally some java ThreadPoolExecutor worker
```

### Device information

* Android device: OnePlus Nord (AC2003)
* Fenix version: ?

* SDK version: 30
* Android/Release version: 11
* Firefox app version: 96.2.0

edit: after writing down the stack trace from my phone, it should probably have been a bug report 😅

**Comment by Kita2345** [comment]
> 



> ## Langkah-langkah untuk mereproduksi
> Tidak dapat mengujinya sendiri karena crash tanpa henti tetapi saya curiga:
> 
> 1. Kunjungi https://huggingface.co/spaces/akhaliq/Detic , halaman demo untuk model AI jika saya tidak salah
> 2. Unggah gambar dua kali (dalam kasus saya mencoba mengunggah yang kedua buat macet dan tidak pernah pulih darinya), tidak memuat ulang halaman
> 
> ### Perilaku yang diharapkan
> Ketika Firefox mogok hanya ada satu tab sebagai rusak atau macet
> 
> ### Perilaku sebenarnya
> * Seluruh aplikasi mogok dan macet saat berada di latar belakang (pelaporan kerusakan otomatis Firefox bekerja/berjalan dengan baik)
> * Saya tidak bisa lagi membuka Aplikasi
> * Saya tidak dapat mengeklik URL di aplikasi lain yang biasanya membuka Firefox (saya tidak melihatnya atau mencoba membuka tetapi mungkin demikian?)
> * Menghapus cache di pengaturan Android tidak membantu (menghapus data aplikasi mungkin akan tetapi saya ingin menghindarinya)
> 
> Saya ingin menambahkan jejak yang dapat saya lihat di dialog Laporan Umpan Balik/Bug Android tetapi saya tidak dapat menyalinnya, jadi inilah bagian yang saya tulis (Beri tahu saya jika Anda memerlukan semuanya, tapi mungkin Anda bisa melihat laporan saya di dasbor Anda):
> 
> ```
> android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=11
>   at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
>   at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
> //  ... # Getting tiered of android.database stuff
>   at mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabDao_Impl$4.call(RecentlyClosedTabDao_Impl.java:12)
>   at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:8)
> // ... # The following is kotlin coroutines androidx.room.TransactionExecutor and finally some java ThreadPoolExecutor worker
> ```
> 
> ### Informasi perangkat
> * Perangkat Android: OnePlus Nord (AC2003)
> * Versi Fenix: ?
> * Versi SDK: 30
> * Versi Android/Rilis: 11
> * Versi aplikasi Firefox: 96.2.0
> 
> edit: setelah jejak-jejak tumpukan dari ponsel saya, itu mungkin laporan bug .

**Comment by mcarare** [comment]
The app on the link provided does not work anymore.
We should re-evaluate this after [changes](https://github.com/mozilla-mobile/android-components/pull/11688) in Recently tabs are merged and the corresponding changes in Fenix are merged.

**Comment by grigoryk** [comment]
This should be fixed by https://github.com/mozilla-mobile/android-components/pull/11688. We are now try/catching get/add interactions with the recently closed tabs storage, so any issues there won't resolve in a crash. We can monitor volume of these via `RecentlyClosedTabsStorageException` in Sentry.

Related - interactions with the file storage part of this is now off the startup path, so any IO issues encountered there won't result in a startup crash either.

Please re-open this if you're still having issues.

**Comment by SpraxDev** [comment]
I've received (at least) 2 Firefox updates via the Google Play Store and am still unable to open Firefox without crashing instantly.

I am on version 97.3.0 (package version is 2015866875). I found my error on [crash-stats.mozilla.org](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=android.database.sqlite.SQLiteBlobTooBigException%3A%20at%20android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow%28Native%20Method%29&version=97.3.0&date=%3C2022-03-05T17%3A59%3A04%2B00%3A00&date=%3E%3D2022-02-26T17%3A59%3A04%2B00%3A00)

**Comment by SpraxDev** [comment]
> Please re-open this if you're still having issues.

Sorry @grigoryk but can this be reopened? Or should I create a new ticket instead?
