### ISSUE TITLE
[Bug]: crash at Web.de

### ISSUE THREAD

**Issue by OlliKn** [mozilla-mobile/fenix#23346]
### Steps to reproduce

Open a new tab
Goto Web.de
Scroll down the page

### Expected behaviour

No crash

### Actual behaviour

Crash

https://crash-stats.mozilla.org/report/index/a7d417f6-4b07-4e14-8cdd-ddac90220121

### Device name

Honor 6x 

### Android version

9

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015858699), 9ceb06e55+ AC: 98.0.20220121045448, 70892aea03 GV: 98.0a1-20220120100401 AS: 90.0.0

**Comment by sheikh-azharuddin** [comment]
Works fine here
![Screenshot_20220121-205948047](https://user-images.githubusercontent.com/58127841/150554084-90dea042-b616-4fca-861f-dcf923882fb4.jpg)

**Comment by OlliKn** [comment]
Did you Scroll down towards the end of the Page? Just tried again and FF crashed again...

**Comment by sheikh-azharuddin** [comment]
However it is better to report site specific issues using report site issue option...let me report me

**Comment by OlliKn** [comment]
Okay! Thank you!
Can I close the issue here?

----------------------------------------

*Von: *sheikh-azharuddin ***@***.***>
*An: *mozilla-mobile/fenix ***@***.***>
*Kopie: *OlliKn ***@***.***>; Author ***@***.***>
*Datum: *21. Januar 2022 16:47:37 MEZ
*Betreff: *Re: [mozilla-mobile/fenix] [Bug]: crash at Web.de (Issue #23346)

**Comment by cadeyrn** [comment]
> it is better to report site specific issues using report site issue option

Since it's not about a web compatibility issue but a Firefox crash it belongs to this issue tracker.

**Comment by kbrosnan** [comment]
Looks like this is bz-1751268 it should be fixed by an update or two assuming the GV version is upgraded.
