### ISSUE TITLE
[Bug]: The vast majority of browser icons disappeared

### ISSUE THREAD

**Issue by CaFI0** [mozilla-mobile/fenix#23350]
### Steps to reproduce

1. Open the browser
2. Navigate the browser menus and options

### Expected behaviour

That all the icons will be displayed correctly

### Actual behaviour

Most of the browser icons have disappeared
![Screenshot_20220121-103138](https://user-images.githubusercontent.com/77524578/150564301-ab67ad5b-7ee1-4061-ac31-f753bb9703cb.png)
![Screenshot_20220121-103107](https://user-images.githubusercontent.com/77524578/150564303-2af71f3d-2e5c-4680-b223-be2f265ccb95.png)

### Device name

Motorola g4 play

### Android version

Android 6

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015858697)

**Comment by kbrosnan** [comment]
Does this happen all the time or is it something that comes and goes? If you force stop Firefox in the Android app settings (not swipe close) or reboot the phone does the problem go away for a while?

**Comment by CaFI0** [comment]
> ¿Esto sucede todo el tiempo o es algo que va y viene? Si fuerza la detención de Firefox en la configuración de la aplicación de Android (no desliza el dedo para cerrar) o reinicia el teléfono, ¿el problema desaparece por un tiempo?

It happens all the time, I did everything you told me but it had no effect on the browser, the icons still do not appear

**Comment by Nov4ou** [comment]
I occurred this bug too.

Device name:
vivo Y55A

Android version:
6.0.1

Firefox release type:
Firefox Nightly

Firefox version:
98.0al(Build #2015859049)

**Comment by yoasif** [comment]
Issue also exists on LG G4 (Android 6)
