### ISSUE TITLE
FNX-5601 ⁃ [Bug] (regression) Tab crash error page doesn't appear

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2335]
## Steps to reproduce
1. Go to about:crashcontent.
    1. Expected behavior
Tab crash reporter appears.
    1. Actual behavior
App crashes, not the tab. Tab crash reporter not displayed.
    1. Device information

* Android device: Pixel, Note 8 (android 9), P9 lite (Android 6)
* Fenix version: 5/6 build

**Comment by bsurd** [comment]
This issue is no longer reproducible, tested with a OnePlus 5T and a Nexus 5, closing.
