### ISSUE TITLE
[Bug]: Can't play video on ceskatelevize.cz

### ISSUE THREAD

**Issue by Scytheroid** [mozilla-mobile/fenix#23367]
### Steps to reproduce

1. Have a tab open
2. Go to `ceskatelevize.cz` (eg, [here](https://ct24.ceskatelevize.cz/ekonomika/3431946-vlada-chce-projednat-zvyseni-minimalni-mzdy-i-automaticky-vzorec-pro-jeji))
3. Play a video

### Expected behaviour

The video player should load and play the video.

### Actual behaviour

The video shows a loading screen indefinitely.

### Device name

Samsung Galaxy M20

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

95.2.0

### Device logs

No chrashes recently

### Additional information

I'm using uBlock Origin and Dark Reader extensions, but having them off didn't make any change.

**Comment by kbrosnan** [comment]
This seems like a webcompat issue. The site works in request desktop mode. Reported it to them.
