### ISSUE TITLE
Problems with the correct page opening

### ISSUE THREAD

**Issue by Rabatte** [mozilla-mobile/fenix#23366]
On Firefox, my website [Rabatt-Guru.de](https://rabatt-guru.de) does not open properly. It behaves as if there was still a supply of graphics and you can move it freely. This is not the case in other web browsers.

### Device information

* Android device: Samsung Galaxy S8+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19241)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-05-11 and didn't encountered any issues with the site. @Rabatte Could you specify in more detail what is the issue you are encountering? Also a short video highlighting the issue would help.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
