### ISSUE TITLE
FNX-5602 ⁃ [Bug] TP always off in custom tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2336]
## Steps to reproduce
1. Make Fenix default browser. Open a link in a custom tab.
1. Open the site info panel, observe the TP toggle.
    1. Expected behavior
TP is on by default.
    1. Actual behavior
TP toggle is off by default in custom tabs. If you open the same link in the browser, it will be On.
    1. Device information

* Android device: 
* Fenix version: 5/8 debug build.

**Comment by ekager** [comment]
Tracking Protection is actually on (tested by opening mozilla.github.io/tracking-test in a custom tab), but the doorhanger is getting the wrong value from `session.trackerBlockingEnabled`.

**Comment by ekager** [comment]
@vesta0 I just made a commit that should fix this if you want to move it to this sprint

**Comment by bsurd** [comment]
Removing the QA needed flag until the blocking issue is fixed.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/17 build. Note 8 (Android 9), P9 lite (Android 6).
