### ISSUE TITLE
[Bug]: ↖️/↙️ buttons' icons in Search Suggestions are not visible in Nightly 

### ISSUE THREAD

**Issue by czlucius** [mozilla-mobile/fenix#23378]
### Steps to reproduce

1. Click on the address bar
2. Type something in the address bar that triggers search suggestions

### Expected behaviour

↖️/↙️ buttons are shown on the right of search suggestions. (I don't know the name of the button)

### Actual behaviour

The buttons are still there, but icons are invisible. 

### Device name

Samsung Galaxy S20 FE 5G 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015859243)

### Additional information

This does not occur in Firefox Stable.
See attached screenshot.
Nightly:
![Screenshot_20220125-005143_Firefox Nightly](https://user-images.githubusercontent.com/58442255/150827628-ff0072ed-6d13-4f5d-beff-62e39997a717.jpg)
(You can see that the buttons are still clickable in the 1st bugzilla entry)
Stable:
![Screenshot_20220125-005001_Firefox](https://user-images.githubusercontent.com/58442255/150827495-fde44924-6e80-408c-bfbf-5f4d46f65fdf.jpg)

**Comment by kbrosnan** [comment]
Similar to https://github.com/mozilla-mobile/fenix/issues/23350 but this is on modern Android

**Comment by czlucius** [comment]
Yes, I saw that issue before posting this one.
But the icons in the other issue are still visible to me.
The issue is also not present in Firefox Stable/Release.

**Comment by mcarare** [comment]
I am inclined to say this is not an issue in AC but in the way we override the `mozac_ui_icons_fill` value. Not sure what are the colors ids for this so I am tagging @gabrielluong for input.

**Comment by gabrielluong** [comment]
Should be fixed with the changes reverted in https://github.com/mozilla-mobile/fenix/issues/23350
