### ISSUE TITLE
FNX-5603 ⁃ [Bug] Show the report site issue link from custom tabs opening in the browser

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2337]
## Steps to reproduce
1. Open a link in a custom tab. 
1. Open the site info panel.
1. Tap the report site issue link.
    1. Expected behavior
The browser is opened showing the page loading.
    1. Actual behavior
The link is sent to the browser in the background, but the user doesn't know it's there.
    1. Device information

* Android device: Note 8 (android 9), MediaPad M2 (Android 5.1.1)
* Fenix version: 5/8 debug build

**Comment by vesta0** [comment]
For me tapping on the Report site issue from the custom tab site panel doesn't work at all. @sv-ohorvath would you please confirm?

**Comment by sv-ohorvath** [comment]
Still reproducing the same way, with a few notes:
1. If your browser is closed, it seems like it's not working, because it doesn't launch the app.
When you open the browser later, you will see the webcompat tab opened.
2. If your browser is already open, and has an opened tab, the webcompat link will replace the existing tab. Still not launching the browser.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11490609), with Google Pixel (Android 9), Nexus 6P (Android 8.1.0), and Huawei MediaPad M2 (Android 5.0.1).
