### ISSUE TITLE
[Bug]: website hamburger buttons nonclicable in firefox Android browser 

### ISSUE THREAD

**Issue by bartsanicki** [mozilla-mobile/fenix#23375]
### Steps to reproduce

1. Have a website with hamburger button opened,
2. Try to click on hamburger button,
3. Menu does not appear. Context menu with 'open link in new card' appears instead.
4. Really dissapointed. 

### Expected behaviour

Tapping on website's hamburger button does nothing. Context menu appears instead. 

### Actual behaviour

Actual behaviour is shown in the Google photos / YouTube link below: [LINK](https://photos.app.goo.gl/tDEkjZ8ReGWKqntv9)
Happens on every site with hamburger button. Menu cannot be opened. 

### Device name

Realme x2 pro 

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19245)

**Comment by amedyne** [comment]
Tested Firefox 96.2, on both Pixel 3 and Pixel 6, on Android 11 and this issue is not reproducible. 
Tagging QA to verify on other devices.

**Comment by bartsanicki** [comment]
It seems that bug occurs on realme phones. Bug is reproductive on both realme x2 pro and realme 6 pro smartphones.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue the issue on Firefox RC 96.2.0 using a Realme GT Master Edition (Android 11) but was unable to reproduce it. The hamburger menu is clickable.

https://user-images.githubusercontent.com/50983519/151790781-17aca01a-abda-4591-881f-1af9da916ee0.mp4
