### ISSUE TITLE
Wallpaper Telemetry

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#23381]
https://mozilla-hub.atlassian.net/browse/FNXV2-18853

- How many users found the wallpaper customization?

- How many wallpapers were applied?

- How many users chose themed wallpapers?

- How many users chose non-themed wallpapers?

- How many users reset to no wallpaper?

**Comment by Amejia481** [comment]
👋🏽 
QA team we would like to verify these new telemetry events are working as expected:

https://github.com/mozilla-mobile/fenix/issues/23381

STR:
Every time the user goes to Settings ->  Homepage ->  Wallpaper -> we sent `wallpapers`.`wallpaper_settings_opened`.


Every time the user goes to Settings ->  Homepage ->  Wallpaper -> And selects one of the wallpapers we sent `wallpapers`.`wallpaper_selected`.

Every time the user goes to the home screen and tap the Firefox logo, we sent `wallpapers`.`wallpaper_switched`.

Every time the user goes to Settings ->  Homepage ->  Wallpaper -> and tap the switch, we sent `wallpapers`.`wallpaper_settings_opened`., we sent `wallpapers`.`change_wallpaper_logo_toggled`.

**Comment by delia-pop** [comment]
Verified as fixed on latest Nightly build from 02/02 with Google Pixel 6 (Android 12) and OnePlus 9 (Android 11).
More information [here](https://debug-ping-preview.firebaseapp.com/pings/test-00001).

**Comment by Amejia481** [comment]
Thanks @delia-pop!
