### ISSUE TITLE
Problem when trying to open intent

### ISSUE THREAD

**Issue by fdocr** [mozilla-mobile/fenix#23397]
### Steps to reproduce

1. Open a link on a website that uses an intent to direct users towards an app using a fallback url
2. The link won't open the app if `S.browser_fallback_url` is provided to the Google Play Store
   - It always opens the Google Play Store despite the app being installed on the device
3. Attempt using the same intent but without providing `S.browser_fallback_url`
   - It works (opens the app) but we lose the ability to provide a fallback URL to the Google Play Store

### Expected behaviour

When the package of the app is available on the device it should open the app. If the app isn't available the link should redirect to the fallback URL (i.e. opening the Play Store link provided as fallback)

### Actual behaviour

The behavior matches the expectation on Chrome/Chromium based browsers (tested on Chrome/Edge). On Firefox we're experiencing always being redirected to the `S.browser_fallback_url` if provided. It works without the fallback url but we lose on the functionality when users don't have the target app installed.

Here's an example intent that we're using for our open beta app (line breaks added for readability):

```
intent://scan/#Intent;
action=android.intent.action.SEND;
type=text/plain;
S.browser_fallback_url=https://play.google.com/store/apps/details?id=com.forem.android;
S.android.intent.extra.TEXT=https://forem.dev/;
scheme=com.forem.app;
package=com.forem.android;
end
```

### Device name

Samsung  A21s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.2.0

### Device logs

No crash detected

### Additional information

[This bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=851693) from a previous stage in the Firefox browser project mentions this problem was solved but I can't seem to make this work and we've had multiple collaborators confirmed this bug is happening for them too.

Should the Intent structure be different from how Chrome handles it? [This site](https://developer.chrome.com/docs/multidevice/android/intents/) documents the structure Chrome expects, but is this documented for Firefox somewhere?

Thanks for the help.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19260)

**Comment by hemant-cloudfeather** [comment]
Hi @fdocr ,
We are facing the exact same issue. Did you found any workaround or fix for this issue?

**Comment by fdocr** [comment]
Hi @hemant-cloudfeather, we did not find a fix for this problem. We keep a guard clause to avoid displaying the CTA that would trigger the intent on an Android Firefox browser. Something along these lines:

```js
if (navigator.userAgent.match(/Gecko\/.+Firefox\/.+$/)) { return }
```

**Comment by iAmmar7** [comment]
I think if you want to open the play store in case the app is not installed then you do not need to pass the fallback URL. For me, Firefox is automatically redirecting to the play store if the app is not installed.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812827

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
