### ISSUE TITLE
Downloaded Pdf has squished text

### ISSUE THREAD

**Issue by ralphcrew** [mozilla-mobile/fenix#23393]
Sites- www.goindigo.in 
           https://ausopen.com
           manjaro.org and others
Also encountered while downloading pdfs. 

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No. Sites look normal, text is properly displayed. 
Pdfs downloaded are also normal.
(Tested on Brave browser 1.34.81)

### Device information-Samsung J7 Duo

* Android device: Android 10 
![Screenshot_20220206-150120_Firefox](https://user-images.githubusercontent.com/86315138/152675024-657462e1-3027-4eaf-a6d6-cb8cd99dd031.jpg)

* Fenix version: Firefox Daylight 96

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19255)

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Nightly 2022-04-20 but was unable to.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
