### ISSUE TITLE
[Telemetry] Multi-select on tabs tray

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#23399]
## What questions will you answer with this data?
What do people do when they are in mutli-select mode on the tabs tray?
- How many people enter multi-select on tabs tray out of all people visiting the tabs tray?
- How many tabs do people select on average?
- What do people do with the selected tabs? Save to collection, share, bookmark or close

## Acceptance Criteria
- [x] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [x] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on latest Nightly  2022-03-10 and 99.0.0-Beta.1.
Device used: OnePlus 6T (Android 9).
The logs can be find [here](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-0005).

**Comment by mcarare** [comment]
Closing this as per the above comment.
