### ISSUE TITLE
[Bug]: Select elements don't seem to work anymore

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#23394]
(Duplicating https://bugzilla.mozilla.org/show_bug.cgi?id=1751864 here, feel free to close one of them)

### Steps to reproduce

1. Open the attachment in https://bugzilla.mozilla.org/show_bug.cgi?id=1751864 or https://everlong.org/mozilla/select.html.
2. Tap the `<select>`

### Expected behaviour

* We should see something to select an option.

### Actual behaviour

* Nothing happens, only the `<select>` element is seen to be pressed but there's no window to select an option.

### Device name

Samsung S10e

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (build #2015859339)

### Additional information

* AC: 98.0.20220123143137, de26ff7e53
* GV: 98.0a1-20220123093907
* AS: 90.0.0

I've seen this originally on https://www.wordreference.com today.

**Comment by caugner** [comment]
Noticed this bug as well, and can confirm it's fixed in the following build:

* 98.0a1 (Build #2015859819), 46a228796+
* AC: 98.0.20220126143158, be27a8afbe
* GV: 98.0a1-20220126065618
* AS: 90.0.1

**Comment by julienw** [comment]
I'm closing
