### ISSUE TITLE
FNX-5604 ⁃ [Bug] The back button in Library & History is gray

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2340]
## Steps to reproduce
1. Go to Your library. Examine the back button.
1. Go to History. Examine the back button.
1. Return and go to Bookmarks. Examine the back button.
1. Return to Library. Examine the back button.
    1. Expected behavior
The back button is always black.
    1. Actual behavior
On the first visit of Library and History menus, it's light gray.
    1. Device information

* Android device: Pixel, MediaPad M2 (Android 5.1.1)
* Fenix version: 5/8

**Comment by bsurd** [comment]
This has now been verified, the buck button is constantly displayed in a black.
