### ISSUE TITLE
Limit themed wallpaper to certain audience

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#23406]
Only show theme wallpaper to certain audience https://mozilla-hub.atlassian.net/browse/FNXV2-18851

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19265)

**Comment by cpeterso** [comment]
Fixed in https://mozilla-hub.atlassian.net/browse/FNXV2-19289
