### ISSUE TITLE
Get desktop view instead of mobile view

### ISSUE THREAD

**Issue by Engztrom** [mozilla-mobile/fenix#23403]
## Site with issue and any steps to reproduce
www.di.se and expressen.se

### Expected behavior
I get desktop view instead of mobile view at e.g. di.se and expressen.se, despite setting "desktop site" off. 
It works with Chrome and other browsers, and also with my old Samsung S10e cellphone.

NOTE: I had exactly the same problem with Firefox for Android 95.0 but after upgrading to a later version (not sure which) it worked fine. But yesterday, when upgrading to 96.2.0, this problem came back again.
(See also previous report #95865. The behaviour is exactly the same now).

### Actual behavior
Stuck on desktop view on certain webpages.

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
I have tried all settings I can find, but I see no shield icon...

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No

### Device information
Samsung S21

* Android device: ?
Yes

* Fenix version: ?
96.2.0 (Build #2015858259)

![bild](https://user-images.githubusercontent.com/11235163/151008641-964b1757-bfdf-48e5-8920-415f2cf648b2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19262)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-02-02.

### Devices used:
- Google Pixel 6 (Android 12)
- Realme GT Master Edition (Android 11)
