### ISSUE TITLE
[Bug]: Selection menu doesn't opens 

### ISSUE THREAD

**Issue by paleparanoid** [mozilla-mobile/fenix#23407]
### Steps to reproduce

1. Go to ezgif.com (or another website where are selection menus used)
2. Upload video, press convert to gif
3. Decide to choose frame rate or another gif parameters, but you can't, because selection menu doesn't opens

It's not because of Ublock Origin or other extensions, I have reinstalled Firefox nightly and checked this bug on clean app to make sure it's not because of extensions/filters.

I also checked this on other websites with selection menus, it's a bug of Firefox, not sites'

### Expected behaviour

It should open and let me choose parameters for expirted gif

### Actual behaviour

It just doesn't opens. 

https://user-images.githubusercontent.com/86261854/151048746-77b5fca4-64bf-42cf-a6b0-2880b44c58b3.mp4

### Device name

Xiaomi Redmi Note 9s

### Android version

Android 11, MIUI 12.0.5.0 

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015859435)

### Device logs

No logs needed here (Also I can't attach them because I don't have Magisk or other root access)

**Comment by paleparanoid** [comment]
Firefox Nightly Build #2015859539 appeared, this bug was mystically fixed

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/23370
