### ISSUE TITLE
Support lock screen / unlock screen in Screen Orientaion API on Fenix

### ISSUE THREAD

**Issue by makotokato** [mozilla-mobile/fenix#23415]
GeckoView adds [OrientationController](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/OrientationController.html) to implement `orientation.lock` and `orientation.unlock` in screen orientation API. This controller delegates `lock` and `unlock` to browser application.

So please implement `OrientationController.OrientationDelegate` on Fenix (Android Component) to support screen orientation API. Fennec supported this API.

Also, this delegate is turned on when `dom.screenorientation.allow-lock=true`.

Bugzilla
* https://bugzilla.mozilla.org/show_bug.cgi?id=1697647
* https://bugzilla.mozilla.org/show_bug.cgi?id=1744101

**Comment by Mugurell** [comment]
@ QA Please note this needs `dom.screenorientation.allow-lock` set to `true`.
Can be tested on 
https://usefulangle.com/demos/105/screen.html
https://bug1681572.bmoattachments.org/attachment.cgi?id=9192275
https://w3c-test.org/screen-orientation/lock-basic.html

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 100.0a1 2022-03-17 and these are the results:
On https://usefulangle.com/demos/105/screen.html, after going fullscreen the orientation is successfully locked in landscape mode.
On https://bug1681572.bmoattachments.org/attachment.cgi?id=9192275 tapping the Lock button will display an error message. If the Fullscreen button is tapped before the Lock is tapped the orientation is successfully locked in landscape mode.
On https://w3c-test.org/screen-orientation/lock-basic.html 4 tests are passed and one timeout, the error: The operation is insecure was also displayed.
I have submitted a separate issue regarding the The operation is insecure error message here: https://github.com/mozilla-mobile/fenix/issues/24320
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)
![Screenshot_20220317-181558](https://user-images.githubusercontent.com/50983519/158846059-de060b28-e79c-4041-88f2-3db5975e82d6.png)

**Comment by gabrielluong** [comment]
Assuming this was meant to be closed when it was verified.
