### ISSUE TITLE
Potential improvements to password manager.

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#23421]
As compared to other password manager I feel firefox password manager is not so robust or user friendly-

1. Suggest login: when multiple logins exist it does not show the website url for the password , just the username and password. So how a user will know which one to select?
2. Password save key: when a user updates a password or enter/create a new one in a website, sometime it does not show option to update /save password kind of prompt is dismissed when url navigates to another one post sign in.ideally it should show a key symbol to save password like desktop variant
3. Password generator: one of the important feature is missing, still need to rely on password generator site
4. Inline keyboard not so friendly: recently you have forced inline keyboard fill option which may not be user friendly for all..other password manager have a option to disable inline keyboard fill and use popup to fill

5.Import/export password: there must an option like desktop browser to import or export password

6. Ability to save password from other app: when firefox is selected as autofill provider ,it should have the ability to save the credentials when entered in other apps.atleast should show one prompt to save.
7. Clear clipboard: like other password manager it should have the option to clear the clipboard after few seconds when a password is copied from firefox

Please improve the features 🙏

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19275)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812428

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
