### ISSUE TITLE
Make expiring performance telemetry permanent (Feb 2022)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#23426]
Let's change the performance telemetry probes (if relevant) to be permanent fixtures rather than renewing. This assumes they don't affect performance and they don't have privacy implications.

Note: the fenix team has a renewal ticket in  https://github.com/mozilla-mobile/fenix/issues/22870.

**Comment by mcomella** [comment]
Data renewal request: https://github.com/mozilla/data-review/blob/main/renewal_request.md

And we need to change the metrics.yaml so they don't expire too. This needs to land before Feb. 1.

**Comment by eliserichards** [comment]
@MarcLeclair you can tag me or @rocketsroger for data reviews on this :)

**Comment by eliserichards** [comment]
Any updates on this? 👀
