### ISSUE TITLE
Add context menu for Contile Top Sites

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#23424]
https://mozilla-hub.atlassian.net/browse/FNXV2-18723

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Nightly debug build 2022-03-03. Long tapping a sponsored shortcut will bring the following options: 
- Open in private tab
- Settings
- Our sponsors & your privacy
![context_menu](https://user-images.githubusercontent.com/50983519/157219967-62499252-490d-4505-8be5-3df7a36934be.JPEG)
