### ISSUE TITLE
[Bug]: download.mozilla.org serving months-old download as "latest"

### ISSUE THREAD

**Issue by wonbug** [mozilla-mobile/fenix#23425]
### Steps to reproduce

Try to download the latest Firefox APK for Android from https://download.mozilla.org/?product=fennec-beta-latest&os=android
This link has worked well for years.

### Expected behaviour

I get the latest version of Firefox for Android.

### Actual behaviour

I get Firefox 68, which is months out of date, without any warning or indication it isn't the "latest" version available.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

68

### Device logs

N/A

### Additional information

Firefox should warn when it's over a year out of date. I had no idea the download you're serving is no longer updated.

**Comment by kbrosnan** [comment]
The mozilla.org website is not part of this project. This should be reported to [Mozilla's Bedrock project](https://github.com/mozilla/bedrock/issues)
