### ISSUE TITLE
[Bug]: I search a app in firefox, it cannot direct towards to open the google play store.

### ISSUE THREAD

**Issue by BugRMSys** [mozilla-mobile/fenix#23436]
### Steps to reproduce

1. search any app you of google play store
2. click the app install link
3. you will get a google play store page in your firefox, not open the google play store on your phone

### Expected behaviour

Open google play store and pass the parameter of app name

### Actual behaviour

it only opens a google play store page in firefox

### Device name

Xiaomi 11 Ultra

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.2.0

**Comment by BugRMSys** [comment]
[
![firefox-01](https://user-images.githubusercontent.com/15137182/151359981-a5063aa8-123c-482e-909a-3b4652551fba.jpeg)
](url)

**Comment by Tursko** [comment]
Settings -> Advanced ->: Open links in apps (enable)

**Comment by BugRMSys** [comment]
> 
Thank you very much, this option is default as disable.
It works now

**Comment by Tursko** [comment]
That's great! Since this wasn't a bug you should go ahead and close the issue.

**Comment by BugRMSys** [comment]
> That's great! Since this wasn't a bug you should go ahead and close the issue. I certainly think it should be enabled by default though :)

I will close this item. Thanks
