### ISSUE TITLE
FNX-5606 ⁃ [Bug] In custom tabs, the location, mic & camera are not running after the permission is given

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2343]
## Steps to reproduce
1. Make sure the app has all permissions off.
1. Open in a custom tab the https://permission.site link.
1. Tap the Location, Camera & Microphone tests.
    1. Expected behavior
Both system & app permission request dialogs are displayed.
After granting permission, all should work.
    1. Actual behavior
For location: both dialogs are displayed. After allowing the permission, the location is not returned. (can also verify this on https://daleharvey.github.io/testapp/)
For camera & mic: The app permission doorhangers are not displayed. Camera & mic can't be turned on.
*Not reproducing in the main browser activity.
    1. Device information

* Android device: Pixel, P9 Lite (Android 6.0)
* Fenix version: 5/8 debug build

**Comment by bsurd** [comment]
Verified in the latest build (5/13) on a Galaxy Note 8 & OnePlus 5T. Permissions work without any kind of issue in custom tabs.
