### ISSUE TITLE
Display the order of Contile Top Sites correctly

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#23431]
https://mozilla-hub.atlassian.net/browse/FNXV2-18722

- Only fetch top sites from the provider when there are <8 default+pinned sites.
- Default Google top site should always appear first

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Nightly debug build 2022-03-03. Sponsored tiles are displayed in the 2nd and 3rd position if google is pinned on top sites, if the google tile is unpinned they are displayed in the 1st and 2nd position. We also tested the cases when multiple sites are pinned to the top sites section from https://mozilla-hub.atlassian.net/browse/FNXV2-18722 and they are displayed correctly.
![google_pinned](https://user-images.githubusercontent.com/50983519/157234521-a8a102f8-3e5d-4326-9c43-057cf2c992e5.JPEG)
![google_unpinned](https://user-images.githubusercontent.com/50983519/157234530-7cb00aab-37a7-4798-b077-51ad2e16efb5.JPEG)
