### ISSUE TITLE
[Bug]: The wallpapers affect changing the theme from settings

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23441]
### Steps to reproduce

1. Go to Settings > Customize and enable the Light theme.
2. Return to the homepage, and tap on the Firefox Browser Logo. The wallpaper changes and the Dark theme is now enabled.
3. Go to Settings > Customize and enable the Light theme.
4. Return to the homepage. Observe the wallpaper.
5. Go to Settings > Customize and enable "Follow device theme".
6. Return to the homepage. Observe the wallpaper.
7. Redo all steps with Dark theme selected in step 1.

### Expected behaviour

4. The wallpaper should change to default white, since the Light theme was previously selected by user.
6. The wallpaper should change to default white/dark according to the device theme.

### Actual behaviour

The dark purple/light purple wallpapers do not allow changing the theme. Changing the theme from Setting is only possible when the default wallpaper is selected.

Relates https://github.com/mozilla-mobile/fenix/issues/23440.

### Device name

Motorola Moto G30

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly from 01/27

### Additional information

https://user-images.githubusercontent.com/89388888/151408798-47c742da-4818-4939-ba7e-3ff240b3d324.mp4

**Comment by Amejia481** [comment]
👋🏽  
@delia-pop would you mind re-testing? A fix should be on the latest `main` branch :)

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with OnePlus 9 (Android 11).

**Comment by Amejia481** [comment]
Thanks @sflorean!
