### ISSUE TITLE
[Bug]: Changing the wallpaper affects selecting the theme in the onboarding screen

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23440]
### Steps to reproduce

1. Install and launch the Fenix browser. 
2. From the onboarding screen, tap on the Firefox Browser Logo to change the wallpaper to dark purple or light purple.
3. Tap on a different theme option from the "Chose your theme" card. Observe the wallpaper and the selected theme.

### Expected behaviour

Selecting a different theme card within the onboarding screen should be possible even if prior to this the wallpaper was changed to other than the default.

### Actual behaviour

The Light/Dark theme card is automatically selected in accordance with the wallpaper displayed. However, the dark purple/light purple wallpapers affect the theme selection. 

Changing the theme card is only possible when the default wallpaper is selected.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly from 01/27

### Additional information

https://user-images.githubusercontent.com/89388888/151403809-ccb8cbb9-6d3d-4cc0-8cf8-f38e1a765d1d.mp4

**Comment by Amejia481** [comment]
👋🏽  
@delia-pop would you mind re-testing? A fix should be on the latest `main` branch :)

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with OnePlus 9 (Android 11).
However, if the theme selected is the light one, after switching to different wallpapers the bug https://github.com/mozilla-mobile/fenix/issues/22950 is displayed. 
cc @Amejia481

**Comment by Amejia481** [comment]
Thanks @sflorean, I'll response on #22950.
