### ISSUE TITLE
[Bug]: Switching between wallpapers should be smoother

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23442]
### Steps to reproduce

1. From the homepage, tap on the Firefox Browser Logo. 
2. Observe the wallpaper changing.
3. Repeat the steps above multiple times. Observe the wallpaper after each tap.

### Expected behaviour

The transition is done smoothly, with no glitches.

### Actual behaviour

After tapping on the FF logo to change the wallpaper, a black flicker is displayed during the transition.

Note that the visual defect is more or less prominent depending on the device. e.g. this is less visible on Google Pixel 6 (Android 12) compared to Motorola Moto G30 (Android 11).

### Device name

Motorola Moto G30, Google Pixel 6

### Android version

Android 11, Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly from 01/27

### Additional information

https://user-images.githubusercontent.com/89388888/151410649-efaebc9f-e466-43b8-8f25-16822da22f8a.mp4

https://user-images.githubusercontent.com/89388888/151410663-e6bced49-8706-4e27-81fe-f962a47fcfec.mp4

**Comment by amedyne** [comment]
@kbrosnan Update with options on how to make this looks smoother for users.

**Comment by kbrosnan** [comment]
Talked with Arturo about this and it is due to the way themes were being handled. The above PR should handle it.

**Comment by Amejia481** [comment]
👋🏽  
@kdelia-pop would you mind re-testing? A fixed should be on the latest `main` branch :)

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build, with OnePlus 9 (Android 11).
