### ISSUE TITLE
[Feature] Enable 'Open links in app' by default

### ISSUE THREAD

**Issue by Tursko** [mozilla-mobile/fenix#23443]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I think most users expect app links to open in the corresponding app.

### How do you know that this problem exists today? Why is this important?
Read above. 

### Who will benefit from it?
Normal users. Power users can disable the option if they don't want it to auto open. You can't expect normal users to think its even an option. Thus the reason the issue below was opened in the first place. I was also surprised when I first started using Fenix that I had to enable it.

Related: https://github.com/mozilla-mobile/fenix/issues/23436

**Comment by Tursko** [comment]
I see that their is an on boarding function that gets called when visiting one of these sites, but that can easily be overlooked. 
https://github.com/mozilla-mobile/fenix/blob/170fa9705e06d63554472989c372eb52b9e01a25/app/src/main/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserver.kt

**Comment by issue-dispenser** [comment]
What about an onboarding popup that asks if you want to open the link in the app and only remembers the option if you ask it to?

Something like:

```
Do you wish to open links in external apps?

Yes      No

[ ] Remember this option
```

**Comment by Tursko** [comment]
> What about an onboarding popup that asks if you want to open the link in the app and only remembers the option if you ask it to?
> 
> Something like:
> 
> ```
> Do you wish to open links in external apps?
> 
> Yes      No
> 
> [ ] Remember this option
> ```

It's supposed to do something like that currently. I don't remember if there's a setup wizard when you first install the app, but that would also be a good place to present the option.

**Comment by kbrosnan** [comment]
We are first and foremost a browser, handling http/https links is our primary task. We have a prompt the first time navigating to a page supported by your apps along with [documentation about how to change to enable open in app](https://support.mozilla.org/en-US/kb/set-firefox-android-open-links-native-apps). If the website wants to send the user to their app always they can use an [intent URI](https://developer.chrome.com/docs/multidevice/android/intents/).
