### ISSUE TITLE
FNX-5607 ⁃ Remove 3-dot menu from tab card on start screen

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2345]
### Why/User Benefit/User Problem
The 3-dot menu adds visual noise on the card on start screen and has just one item. For MVP we want to remove the 3-dot menu and re-evaluate post MVP.

### What/Requirements
Remove 3-dot menu from home screen tab card.

**Comment by vesta0** [comment]
@lime124 @bifleming is this a design change request from UX? Can we have updated mocks?

**Comment by lime124** [comment]
@topotropic ^

**Comment by topotropic** [comment]
that's done in 1.0.1919

**Comment by liuche** [comment]
@topotropic I was looking at tabs crash (unrelated to this) but there's still code in the tree to handle Tab Share from an individual tab (which was removed in this issue). Do we think individual tab actions is coming back? Otherwise I'll remove it.
