### ISSUE TITLE
[Bug]: Full screen content not fitting the screen correctly.

### ISSUE THREAD

**Issue by asisnil** [mozilla-mobile/fenix#23461]
### Steps to reproduce

1. Turn on miui full screen mode
2. Go to fullscreen in any video

### Expected behaviour

Contents should fit correctly.

### Actual behaviour

Content goes under the screen.

### Device name

Redmi 9a

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

96.2.0

### Additional information

Youtube
<img src="https://user-images.githubusercontent.com/46134036/151525035-f9d8181d-de25-488f-a964-d2de046b3e70.jpg" width="30%">

Instagram
<img src="https://user-images.githubusercontent.com/46134036/151525100-eb257c38-56f6-4331-8b21-c2270e779d50.jpg" width="30%">

miui full screen mode
<img src="https://user-images.githubusercontent.com/46134036/151525157-35c5a554-f0ac-426a-b2de-2810b1c85992.jpg" width="30%">

It works alright if I turn on navigation buttons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19309)

**Comment by LaviniaL99** [comment]
Hello @asisnil 

Thanks for your report!

I retested the above flow on the latest Nightly build (100.0a1) and latest RC build (98.3.0) and i was not able to reproduce the issue.

**Device used:**

Samsung S10E - Android 10

Can you please retest the issue on the latest builds and verify if you are still able to reproduce the above flow? If yes, please attach a video of it.

**Comment by asisnil** [comment]
@SoftVision-LorandJanos 
I think its a Xiaomi Miui(full screen mode) only problem. I used Firefox in other custom roms (same device), the problem didn't occur.
Here are screen records with and without full screen mode on.

Without full screen mode (working fine)
[YT](https://youtu.be/oPILCtV-a6E)

With full screen mode
[YT](https://youtu.be/PfvYoOXrfXo)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Is this identical to ![Screenshot_20220803-180558](https://user-images.githubusercontent.com/42837531/182667785-b3565b67-9404-4a60-8ca6-f6d98a9244b1.png) becoming 
![Screenshot_20220803-180548](https://user-images.githubusercontent.com/42837531/182667821-8c32988f-6d7c-4982-a057-3b9e8b20e8f7.png)?

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813889

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
