### ISSUE TITLE
Provide some sort of way to edit CSS for sites.

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#23466]
### What is the user problem or growth opportunity you want to see solved?
A lot of mobile web sites use tiny fonts, and do not provide a way to increase the font size enough. Reader Mode can help, but not all sites work well with Reader Mode. One could increase the font size in Settings->Accessibility, but that often break's the site's layout or make text clipped (e.g., the line height is fixed to be 20px in the CSS, so increasing the font size to 40px makes the bottom half clipped out).

On desktop, I use the [Stylus extension](https://addons.mozilla.org/en-GB/firefox/addon/styl-us/), and I have been checking if Stylus is added to the approved extension from time to time since Android FireFox restricted extensions, but years later, it is still not added, and I am not sure if it will ever be added.

If you are not going to allow Stylus, at least add some basic ability to edit the CSS. 

### How do you know that this problem exists today? Why is this important?
This is not a trifle issue for a lot of people. It is a matter of whether they can read the page or not. So, I think this should be one of top priorities. After all, what fancy features of a browser matter, if one cannot read the text on web pages?

### Who will benefit from it?
People who are struggling to read small text on mobile websites that do not work well with the Reader Mode.

**Comment by kbrosnan** [comment]
You can use a custom extension list by following https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
