### ISSUE TITLE
[Bug]: previous tab reloads in a flash before next tab is painted when switching tabs by swiping 

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#23469]
### Steps to reproduce

Open new multiple tabs
Swipe between them until a tab needs to be reloaded (the issue also happens when the next tab is reloaded from memory but less visible)

### Expected behaviour

The next tab should be painted directly 

### Actual behaviour

On swiping :
The url changes to the one of the next tab 
The screen gets dark
The previous page is re-displayed as a flash, for a very short time
Then only the new page is painted, either from memory or by reloading it
See here : https://photos.app.goo.gl/2bLSzhhxdbpZ59pn9

### Device name

Redmi note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

98

**Comment by Cheap-Skate** [comment]
I see this too, Galaxy M32 Android 11.

It might be two separate issues:- 
1. the black screen; and 
2. the flash of previous page.

I think I only see (1) when the tab is un-suspended. IIRC a while back a black screen was added to the page load in Dark Mode to stop the white flash when Fenix is in Dark Mode. Perhaps that black screen now appears when the tab gets un-suspended?  I can't find the issue.

I think I see (2) more often, but I have not really looked into it.

IMHO there could be a whole meta-bug of graphics glitches when Fenix switches tabs.

**Comment by Cheap-Skate** [comment]
#18131

**Comment by agi** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1753085

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
