### ISSUE TITLE
[Bug]: Favorite icon in website is not used when transforming XML with XSL to HTML inside browser

### ISSUE THREAD

**Issue by bartensud** [mozilla-mobile/fenix#23479]
### Steps to reproduce

- Upload attached favicon.xml, favicon.xsl and favicon.png to an arbitrary web server, e.g. to my.site.com
- Open URL with favicon.xml in Firefox, e.g. https://my.site.com/favicon.xml
- The resulting HTML contains the favicon link in header section: ```<link rel="shortcut icon" href="favicon.png">```
- Observe areas where the favicon (favicon.png) should be displayed, but isn't. For example:
  1. Firefox tab list (important: Tab view settings must be "Grid", for "List" it's in general not shown)
  2. Add website to home screen

Note: Only for using XML/XSLT the favicon is missing (see actual behavior). When opening the same markup directly as HTML (favicon.html) it works as epexted.

[favicon_bug_for_xml-xsl.zip](https://github.com/mozilla-mobile/fenix/files/7967001/favicon_bug_for_xml-xsl.zip)

### Expected behaviour

Expected behaviour is demonstrated by a HTML site with the same markup as the XML/XSL-tranformation should result in (see favicon.html and favicon.png in attachment). The favicon is used/shown correctly e.g. in
- in tab view (see first screenshot)
- when adding web site to home screen (see last 3 screenshots)

![index html_33p_marker](https://user-images.githubusercontent.com/156340/151719508-4bce9fcb-ab03-48c6-9d1d-359f9c8a7c1d.png)

### Actual behaviour

The favicon is 
- in tab view: not shown at all (see first screenshot)
- on adding web site to home screen: shown as default/fallback icon (see last 3 screenshots)

![index xml_33p_marker](https://user-images.githubusercontent.com/156340/151719623-46a43bc3-b39c-4700-bffa-52b906250244.png)

### Device name

Samsung Galaxy A3 (2017)

### Android version

Android 8.0.0

### Firefox release type

Firefox

### Firefox version

96.3.0 

### Additional information

- Same behavior on Google Pixel 4a under Android 12 (CalyxOS 3) with Fennec 96.1.1 (from F-Droid)
- The favicon is shown as expected on Firefox Desktop browser.
- As the used way of defining a favorite icon (```<link rel="shortcut icon" href="favicon.png">```) is only one of many, I assume the general handling of favorite icon may be affected when using XML/XSL.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19324)

**Comment by kbrosnan** [comment]
From the attached file this is a 32px favicon, so the 16px favicon issues do not apply here.

**Comment by bartensud** [comment]
Yes, the original bug report was done with 32px image in PNG format as favicon.

I've tested it also with a 16px favicon (ico format): Same behavior as reported initially. 
See attachment for test data: [favicon-ico-16px_bug_for_xml-xsl.zip](https://github.com/mozilla-mobile/fenix/files/7974864/favicon-ico-16px_bug_for_xml-xsl.zip)

**Comment by kbrosnan** [comment]
We don't use 16px favicons, that is why I called out 32px. This may need bz-1722500.
