### ISSUE TITLE
Update the Sentry dependency's version for the Sentry migration

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#23489]
We're moving to a new instance of Sentry, we need to investigate and update the Sentry dependency's version  if required

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19330)

**Comment by Amejia481** [comment]
[Related (https://github.com/mozilla-mobile/android-components/issues/11646)

**Comment by jonalmeida** [comment]
The sentry dependency version [here](https://github.com/mozilla-mobile/fenix/blob/main/buildSrc/src/main/java/Dependencies.kt#L17) isn't used for anything I think. Maybe we should remove it?

**Comment by Amejia481** [comment]
Agree, but it's a bit odd.
