### ISSUE TITLE
[Bug]: Netflix can't play title

### ISSUE THREAD

**Issue by Csaba8472** [mozilla-mobile/fenix#23482]
### Steps to reproduce

1. Open netflix
2. Log in
3. Select a movie/series
4. Tap play

### Expected behaviour

The title should start

### Actual behaviour

Netflix error: F7121-1331

### Device name

Galaxy Fold 2

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

96.3.0

### Additional information

I've tried firefox, firefox beta(97.0.0-beta6) and firefox nightly(98.0a1) but same issue. I've also set manually `media.eme.enabled` manually to true and tried to turn off enhanced tracking protection.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1752864

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
