### ISSUE TITLE
Add content description for wallpapers

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#23498]
https://mozilla-hub.atlassian.net/browse/FNXV2-19315

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19337)

**Comment by cpeterso** [comment]
@Amejia481 Is this issue complete? The Jira issue https://mozilla-hub.atlassian.net/browse/FNXV2-19315 was closed as "Done", but this issue is still open.

**Comment by Amejia481** [comment]
Yes, I think it's OK to close
