### ISSUE TITLE
[Bug]: Firefox doesn't show a dedicated "share" button in In-App-Browser in Slack (but Chrome does, and Firefox does for other apps)

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#23493]
### Steps to reproduce

1. Have Firefox set as your default browser (and configured to open links from apps, if there's additional configuration required)
2. Tap some link in the Slack android app, so that the in-app browser (aka "custom tabs" I think?) gets launched.
3. Look at the browser toolbar.

### Expected behaviour

There should perhaps be a "share" button on the toolbar (in part for ease-of-use, and in part because the menu-entries for "share" happen to currently be broken in Slack, per https://github.com/mozilla-mobile/fenix/issues/23438#issuecomment-1026055750 ).

### Actual behaviour

There is no share button on the toolbar.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

### Additional information

If I perform the STR from certain other apps (e.g. Gmail), then there is a share button ("expected results")

If I perform the STR with Slack and using Chrome as my default-browser, then there is a share button ("expected results")

So it seems Firefox and Chrome are both able to show this button in our in-app browsers, but we're disagreeing about whether it should be shown in this case with Slack (and given the aforementioned slack bug, it's nicer to show it in this case).

**Comment by dholbert** [comment]
Screenshots (using an article *about* TorBrowser, since that's what I had handy in Slack.  Note that none of these are using the Tor Browser; that just happens to be the subject of the article).

* Firefox Nightly in-app-browser launched from Slack (share button missing):
![image](https://user-images.githubusercontent.com/426803/151854031-78cbf9c3-199b-4400-9b08-1bcfd3d47783.png)

* Firefox Nightly in-app-browser launched from Gmail (share button present):
![image](https://user-images.githubusercontent.com/426803/151854138-37552348-5f69-43a5-8be3-a4f6b18586c1.png)

* Chrome in-app-browser launched from Slack (share button present):
![image](https://user-images.githubusercontent.com/426803/151854221-639bd8d4-e9e3-4383-b5d4-d70ae509314c.png)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/8674
