### ISSUE TITLE
FNX-5609 ⁃ Send crash reports to Glean

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#235]
### Why/User Benefit/User Problem
Crash pings would help us to calculate crash rates... something we do not get with Sentry (#2326).

Fennec implementation:
https://bugzilla.mozilla.org/show_bug.cgi?id=1407557

This is something we'd implement in the telemetry library:
https://github.com/mozilla-mobile/telemetry-android

### What/Requirements
Add Glean crash reporter to CrashReporter services.

https://github.com/mozilla-mobile/android-components/tree/master/components/lib/crash#sending-crash-reports-to-glean

### Acceptance Criteria (how do I know when I’m done?)
* Glean Crash reporter is added, and crash counts are being sent
* Documentation added to Fenix telemetry docs, explaining what the crash reporter collects
* Data review for adding new telemetry collection of Glean crash reporter

**Comment by bbinto** [comment]
Is this still a valid issues? If so, we are aiming for crash reporting / good stats for milestone 2 or 3, so feel free to size during triage AND move it into milestone 2 backlog.

**Comment by pocmo** [comment]
Yes, this is still valid. The crash ping will help us to measure the health of the app and hopefully avoid situations like we had in Focus where we couldn't really pinpoint certain issues.

The glean, app and AC teams have met and are going to work on a solution to collect this data with Glean from the crash reporter component.

In AC that is tracked by the meta "Good crash statistics":
https://github.com/mozilla-mobile/android-components/issues/1820

The related Glean issue is:
https://bugzilla.mozilla.org/show_bug.cgi?id=1522461

**Comment by vesta0** [comment]
@bbinto please advise.

**Comment by bbinto** [comment]
@pocmo can you help me understand what work is left to do for the A-C team, and Fenix, and do you have everything you need from the Glean team to send this ping?

If we don't get any update on this before sprint planning, I'm fine with moving this down the backlog for now.

/cc @vesta0

**Comment by vesta0** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1522461

**Comment by st3fan** [comment]
@liuche this will require a data review and new dashboarding.

There are good instructions for the integration here, which looks pretty low effort:

  https://github.com/mozilla-mobile/android-components/tree/master/components/lib/crash#sending-crash-reports-to-glean

This has been running on Reference Browser for a few weeks now and should be ready to go into Fenix.

**Comment by liuche** [comment]
Updated initial comment to include more info.

One concern I have @travis79 is that when Glean upgrades its crash reporter to collect more data, consumers might automatically start collecting more crash data than they were aware of. Is there a way to require explicit versioning? It's unclear how to message all consumers of Glean/AC. Not super urgent, but something to think about.

I guess that consumers can just link to the Glean docs, and expect that those will be up to date, and I guess that's what we do w/ other Glean pings.

**Comment by travis79** [comment]
@liuche that's a great point, and one of the reasons why I was envisioning making it possible for the consuming application to control which metrics are collected when it initializes the GleanCrashReporterService. That at least gives the consuming application fine grained control over what it is collecting and allows for additional data reviews when instrumenting additional crash metrics.

**Comment by st3fan** [comment]
@liuche afaik the only thing we send for now is a count of crashes, a single number.

**Comment by liuche** [comment]
@pocmo I'm writing up some crash docs, and I have a question:
Based on this comment (from digging through crash reporter changes), it sounds like non-fatal crashes require a user to submit the crash report
https://github.com/mozilla-mobile/fenix/pull/1062#issue-262173043

What about fatal crashes? Do we also prompt the user for that, or does it send automatically in the background? I wasn't able to find clear explanation in the [AC Crash docs](https://github.com/mozilla-mobile/android-components/tree/master/components/lib/crash#sending-crash-reports-to-sentry), and the [old Focus docs](https://github.com/mozilla-mobile/focus-android/wiki/Crash-Reporting-with-Sentry) seem to say Sentry will submit in the background (but in Focus it was gated on the telemetry switch). I also only see `shouldPromptForCrash` used [only in one place](https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt#L109), for non-fatal crashes.

**Comment by pocmo** [comment]
@liuche This is up to the app and can be configured when using the component, see:
https://github.com/mozilla-mobile/android-components/tree/master/components/lib/crash#showing-a-crash-reporter-prompt

Fenix (and RB) are using the `PROMPT_AWAYS` configuration to always show a confirmation prompt for crash reports:
https://github.com/mozilla-mobile/fenix/blob/a31eb1f371750942ffd950403d6c350e187222d3/app/src/main/java/org/mozilla/fenix/components/Analytics.kt#L67

If I remember correctly this was a UX decision introduced back in Focus (when we added GeckoView) to avoid user confusion when only prompting sometimes (since a user wouldn't be able to distinguish between native and other crashes).

In addition to that non fatal crashes (which basically means only Gecko crashes but the app process is still okay) are configured to be handled by Fenix via an Intent (instead of showing the prompt). This allows Fenix to show its in-app crash UI ("This tab crashed"). This UI can (and I think does) can ask for confirmation too (up to the app in this case).
https://github.com/mozilla-mobile/fenix/blob/a31eb1f371750942ffd950403d6c350e187222d3/app/src/main/java/org/mozilla/fenix/components/Analytics.kt#L73

**Comment by liuche** [comment]
Oh right, I just misread that block entirely - regardless of fatality, it won't send the crash if `showPrompt` is true 😅

**Comment by liuche** [comment]
This unblocks #5113, which has a bugzilla bug.

**Comment by sblatz** [comment]
@liuche Should I put a QA needed on this?

**Comment by liuche** [comment]
Don't need a QA-label here - we'll wait for the dashboard #5113, which should be the verification. I'll close this then.
