### ISSUE TITLE
[Bug]: Add credit card screen focus and keyboard issues

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#23500]
## Focus should be set to the editable card number field

Steps to reproduce: 
1. Go to Settings -> Credit cards -> Add card
2. See that the focus starts out on the "Card number" title instead of the first field

<img width="328" alt="image" src="https://user-images.githubusercontent.com/43795363/151879081-91b74abc-f1c6-4727-a3e2-025d8674cb31.png">

## Keyboard should close when exiting "Add card" screen

Steps to reproduce: 
1. Go to Settings -> Credit cards -> Add card
2. Click on any field (e.g. Card Number)
3. Hit back button to exit "Add card" screen
4. Keyboard should be closed instead of remaining open:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/151879548-a429631a-62eb-43de-bd6b-49b47866d93c.png">

**Comment by eliserichards** [comment]
This can be broken out into two different issues if needed, but it'll probably be easy to fix them together

**Comment by geneukum** [comment]
Hey @eliserichards, I'd be happy to take a look at these two issues if they're still unclaimed.

**Comment by geneukum** [comment]
@gabrielluong, can this bug be closed out?
