### ISSUE TITLE
FNX-5610 ⁃ [Bug] Can't rename collection

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2351]
## Steps to reproduce
1. Open a few tabs
1. "Save to collection"
1. Select some tabs
1. Press "Save"
1. Press "Add new collection"
1. Backspace to rename the collection

### Expected behavior
1. Can backspace the given collection text

### Actual behavior
1. Cannot backspace

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/21 build.
