### ISSUE TITLE
"Open in app" is not reliable for instant apps

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23522]
Tested as a comparison with Focus where trying to open a link in an instant app would crash Focus - https://github.com/mozilla-mobile/focus-android/issues/5841

STRs:
- enable instant apps support in system settings - https://support.google.com/googleplay/answer/7683278
- access a vimeo video
- open menu -> "Open in app"
(the Vimeo instant app should now be installed to then automatically open the shared video link)
- go back to Fenix and refresh the page
- open menu

Expected:
"Open in app" option available to open the link in the Vimeo instant app

Actual:
No "Open in app" button.

https://user-images.githubusercontent.com/11428869/151929569-5bd4bdad-c57b-4747-8562-8e44d59212cd.mp4

&nbsp;
/*This needs to be tested in multiple scenarios as it may also be a framework bug.
&nbsp;

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19350)

**Comment by TrianguloY** [comment]
In case you want other instant app for testing, I have an experimental one to launch any intent.

[https://trianguloy.github.io/intent/#Intent;action=android.intent.action.SEND;type=text/plain;S.android.intent.extra.TEXT=test;end](https://trianguloy.github.io/intent/#Intent;action=android.intent.action.SEND;type=text/plain;S.android.intent.extra.TEXT=test;end)

This link for example should ask you to send a text. (Note: some intents are not supported on instant apps)

With this test for example I was unable to reproduce the issue on latest stable version.
