### ISSUE TITLE
FNX-5611 ⁃ [Bug] QR Scanner snackbar does not appear

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2353]
## Steps to reproduce
1. Open Search Fragment
1. Press "Scan"
1. Hold up to a QR code

### Expected behavior
1. A snackbar confirmation is displayed

### Actual behavior
1. Nothing happens

**Comment by dector** [comment]
Not reproducible for me for latest `master` build. However picture is visibly squeezed horizontally.

**Comment by ekager** [comment]
@sblatz are you still seeing this? I'm not sure what you mean by "snackbar confirmation" but I am seeing an alert dialog to take me to the site with "allow" and "deny" actions?

**Comment by sblatz** [comment]
I'm no longer able to reproduce.
