### ISSUE TITLE
[Bug]: Reader view icon flickers on scroll

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#23535]
### Steps to reproduce

1. Go to https://www.delicious.com.au/recipes/collections/gallery/60-easy-desserts-for-effortless-entertaining/77cijfrr
2. Scroll the page so that the URL bar remains displayed.
3. Observe the reader view icon area.

### Expected behaviour

The reader view icon is continuously displayed.

### Actual behaviour

The reader view icon is flickering. Sometimes just part of the URL behind the icon.

### Device name

Google Pixel 4, Oppo Reno 6

### Android version

Android 11, 12

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (2022-02-02)

### Additional information

1. The URL bar is sometimes displayed when it should hide, and the issue is reproducible with scrolling both ways.
2. After activating the reader view, the icon behaves as expected.

https://user-images.githubusercontent.com/48829350/152172597-2903d314-63af-4167-a44e-95ffe34ba9cf.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19361)

**Comment by kbrosnan** [comment]
@amedyne maybe more fallout from the icon work?

**Comment by gabrielluong** [comment]
> @amedyne maybe more fallout from the icon work?

This is probably unrelated, we reverted the work to remove duplicate icons on fenix to use the icons that are already in AC.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 109.0a1 (2022-11-29) build.
Device used: Oppo Find X5 (Android 12).
