### ISSUE TITLE
97.1.0 bug 

### ISSUE THREAD

**Issue by sojudu** [mozilla-mobile/fenix#23530]
### Steps to reproduce

Go to bing.com
Close browser
Open browser, the tab is not there
Close a webpage
Re-open browser
Webpage still there and not closed

### Expected behaviour

It should close the tab

### Actual behaviour

The tab is there even after closing it when browser reopened

### Device name

Realme x

### Android version

11

### Firefox release type

Firefox

### Firefox version

97.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19354)

**Comment by sojudu** [comment]
https://user-images.githubusercontent.com/95345118/152091667-92af535e-ce38-4a0e-a3e2-bdd40e74f722.mp4


https://user-images.githubusercontent.com/95345118/152091675-fd06842c-30ff-4b89-b816-6e5cfe8fda61.mp4

**Comment by delia-pop** [comment]
Hi @sojudu, thanks for your report!
I was not able to reproduce the issue with Xiaomi Redmi Note 8T (Android 9).
Could you try to reproduce this on the latest Release version (RC 100.1.1)?
Thank you!

**Comment by sojudu** [comment]
Using version,107.1.0 (Build #2015915067), the bug still exists, no worries though i moved away from firefox.

**Comment by sojudu** [comment]
Miss pop, I am only seeing your message 7 months later as git hub didnt send me an e-mail

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813187

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
