### ISSUE TITLE
Add search engine - Clear icon is not displayed when the user starts typing in fields

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23532]
### Steps to reproduce

1. Navigate to Settings -> Search-> Add search engine
2. Tap on the Other option
3. Start typing something in the "Name" / "Search string to use" fields
4. Verify if the clear icon is available at the end of the fields

### Expected behaviour

Clear icon must be displayed when the user starts typing in any field.

### Actual behaviour

Clear icon is not displayed when the user starts typing in any field.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.6

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19358)

**Comment by delia-pop** [comment]
Reproducible on Beta 100.0.0-beta.4 with Google Pixel 6 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
Reproducible on Beta 101.0.0-beta.1 with Google Pixel 4 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest RC 107.1.0 and latest Nightly 108.0a1 (2022-11-14) builds.
Device used: Oppo Find X5 (Android 12).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807709

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
