### ISSUE TITLE
Long clicking to reveal edit menu in text fields shows Copy to Clipboard alert (Android 12)

### ISSUE THREAD

**Issue by czlucius** [mozilla-mobile/fenix#23539]
### Steps to reproduce

1. On Android 12, enable toast notifications when clipboard is accessed
2. Visit a site with a text box in it
3. Long click in the text box to reveal the edit menu

### Expected behaviour

Clipboard should not be read from.

### Actual behaviour

A toast notification pops up saying that the clipboard is pasted from.

### Device name

Samsung Galaxy S20 FE 5G 

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

96.3.1 (Build #2015860755)

### Device logs

N/A

### Additional information

https://user-images.githubusercontent.com/58442255/152194533-75792fa9-f6a0-4218-adef-9c560db4b207.mp4

**Comment by kbrosnan** [comment]
@makotokato this looks like Gecko behavior? Is that correct? Should we move this to Bugzilla?

**Comment by makotokato** [comment]
Yes, as current design. This is https://developer.android.com/guide/topics/text/copy-paste#PastingSystemNotifications.

But this is a kind of feature request to improve clipboard support.

**Comment by makotokato** [comment]
(User can show/hide this notification by Settings in Android system - Privacy - Show clipboard access)

**Comment by kbrosnan** [comment]
Opened bz-1755052 to track using the modern API. Going to close this as it is work that will not directly be done by the Fenix team.

**Comment by czlucius** [comment]
Thanks
