### ISSUE TITLE
[Bug]: Add search engine -  Error icon is not displayed on error message

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23533]
### Steps to reproduce

1. Navigate to Settings -> Search-> Add search engine
2. Tap on the Other option
3. Start filling the URL address in the "Search string to use" field.
4. Tap on the check icon from the top-right corner.
5. Verify if the **"Enter search engine name"** error message is displayed along with the **specific error icon** for "Name" field.

### Expected behaviour

The error icon must be displayed along with "Enter search engine name" error message for the "Name" field. (Please see the screenshot attached for reference).

<img width="357" alt="Screenshot 2022-02-02 at 15 59 54" src="https://user-images.githubusercontent.com/96047134/152168345-c648aae9-2fe2-444e-8078-c82cee083514.png">

### Actual behaviour

The error icon is not displayed along with "Enter search engine name" error message for the "Name" field.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.6

**Comment by gabrielluong** [comment]
This is actually expected with Material Design https://material.io/components/text-fields#anatomy
