### ISSUE TITLE
Add-on icons animate in slowly in Add-ons menu

### ISSUE THREAD

**Issue by ganeshghutugade** [mozilla-mobile/fenix#23531]
https://user-images.githubusercontent.com/53371927/152152999-eb011cd6-3db4-44ce-9252-f5683dc6fad6.mp4

* Android device: 98.0a1 (Build #2015860971)
* Fenix version:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19357)

**Comment by ganeshghutugade** [comment]
See video add-ons loading slowly.
Sorry I have no technical  knowledge

**Comment by mcomella** [comment]
@ganeshghutugade Is it only the add-on icons that are loading slowly?

Triage: the animation looks unnecessarily slow though csadilek mentioned it might be covering up a network delay.

**Comment by ganeshghutugade** [comment]
![Screenshot_2022-02-02-09-53-08-75_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/53371927/152347286-dff37489-4dab-4659-bea0-5ca408c3a126.jpg)
  

No add-on loading slowly i open browser two or three times and then add-on is loaded

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807349

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
