### ISSUE TITLE
[Bug]: The default search engines are not arranged alphabetically

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23534]
### Steps to reproduce

1. Go to Settings - Search
2. Observe the default search engine list

### Expected behaviour

The default search engine must be arranged alphabetically.

### Actual behaviour

The default search engine are not arranged alphabetically. (See screenshot attached for reference).

![search engine list](https://user-images.githubusercontent.com/96047134/152171749-d2c42756-6172-406d-a74e-cc78c8db0976.JPEG)

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.6

**Comment by kbrosnan** [comment]
This is intentional.
