### ISSUE TITLE
[Bug]: Strange side scrolling on website

### ISSUE THREAD

**Issue by rsssxd** [mozilla-mobile/fenix#23542]
### Steps to reproduce

Open the Rudaw website. Side scroll and go to chapter 3.
https://www.rudaw.net/Turkish

### Expected behaviour

The 3rd news should load smoothly when side-scrolling.

### Actual behaviour

3. A white blank content appears instead of the title

### Device name

Xiaomi Mi 9T

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

86

### Additional information

Chromium browsers do not have such a problem.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19366)

**Comment by SoftVision-LorandJanos** [comment]
Hi @reyis4402! Thank you for your report!
I could reproduce the issue described by you, but only the 3rd or 4th time i scrolled, so it's not a constant issue (On Beta I got this result the first time).
And as I observed the title looks as expected, and the but the picture is white.
Also checked on Chrome where it works as expected.

This is how the third slide appears to me on Firefox (after accessing the slide 3rd, 4th time):
![Screenshot_2022-02-03-16-45-31-44_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/48829350/152365960-5d988e50-d660-4454-be03-e851f139497f.jpg)
This is how the slide should look like:
![Screenshot_2022-02-03-16-45-55-22_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/48829350/152366375-3e9d05b1-01b3-4784-86b3-9bbcb9760d11.jpg)

Tested on:
- Firefox Nightly 98.0a1 (2022-02-03).
- Firefox Beta 97.0.0-beta6.
- Firefox Release (97.1.0).

Device used: Oppo Reno 6 (Android 11).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 110.0a1 (2022-12-14) build.
Device used: Oppo Find X5 (Android 12).
Not reproducible on Chrome.
Reopening the ticket.
![Screenshot_2022-12-14-10-04-49-90_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/48829350/207543527-2cffce8a-99e6-4228-868c-20adb914b4ba.jpg)
