### ISSUE TITLE
[Bug]: Cannot enter unlock code using a secondary account

### ISSUE THREAD

**Issue by sherip99** [mozilla-mobile/fenix#23548]
### Steps to reproduce

To access saved passwords in Settings you must enter the unlock code for the android device. My Firefox app auto updated today and now the entry field for the unlock code does not accept any characters.

### Expected behaviour

Prompt for unlock code, accept characters for device pin from keyboard entry.

### Actual behaviour

Prompts for unlock code but keyboard input doesn't appear in the field and submission of input is not available.

### Device name

Samsung S6 Lite tablet

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.3.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19370)

**Comment by mcarare** [comment]
@sherip99 Can you provide a recording of the issue? It would help with debugging and fixing the issue. Thank you!

**Comment by sherip99** [comment]
Hopefully these screenshots will help. Actually the last frame is a photo, because I couldn't take a screenshot there, there was a popup saying no screenshot could be taken there due to security policy.

![FirefoxBug](https://user-images.githubusercontent.com/4652094/152408088-ed955ca4-fa54-428b-bbc2-f2b9755a810e.jpg)

**Comment by sherip99** [comment]
> @sherip99 Can you provide a recording of the issue? It would help with debugging and fixing the issue. Thank you!

https://github.com/mozilla-mobile/fenix/issues/23548#issuecomment-1029293802

**Comment by sherip99** [comment]
@mcarare hope you've seen my posted pics in lieu of a screen recording. Can't view Firefox saved passwords except after removing device lock protection altogether.

**Comment by sherip99** [comment]
@mcarare Keyboard input doesn't appear in any form on that control. The "continue" option is never available. I did have to enter the pin on the device in order to remove the pin, but it the input control was different.

**Comment by sherip99** [comment]
@mcarare Looked again at the dialog they show for collecting the Pin for changing lock screen protection. It specifically asks for the Pin and presents a numerical keyboard to type it in. Pin is not the only option. Perhaps Firefox needs to ask for right type of input dialog to be shown.

**Comment by kbrosnan** [comment]
Seems similar to https://github.com/mozilla-mobile/fenix/issues/22464

**Comment by sherip99** [comment]
@mcarare @kbrosnan This issue may apply only to secondary android accounts. I was not the primary account on the tablet. Have just factory reset it, and started over. I'm now the first profile. I am now able to access saved passwords with a Pin and the system dialog for unlocking opens with a numeric keyboard.
