### ISSUE TITLE
Glean JNA via `CounterMetricType.<clinit>` via `PerfStartup.<clinit>` delays Gecko start up (58ms w/ Debug API)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#23559]
When using the `Debug` API (i.e. has additional overhead) to take a start up profile, we see `PerfStartup.<clinit>` take 58ms to run, due to the time it takes to init the Glean component it uses: https://share.firefox.dev/3HvSTcb

There are three key points in COLD VIEW start up:
1. time to display the UI (i.e. first frame / visual completeness)
2. how early we start Gecko (because it takes a while to start)
3. how early we call `GeckoSession.load` to start the page load

This code affects all three. If we execute this code later on the foreground, we can avoid 3 if not 2. If we init it on a background thread (which the existing `mozilla.telemetry.glean.GleanInternalAPI.initialize` might do for us), we can probably avoid 1 as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19374)

**Comment by badboy** [comment]
Looks like the overhead is from loading the shared library

**Comment by mcomella** [comment]
Triage: https://github.com/mozilla-mobile/focus-android/issues/7261 might have the same cause (glean native library load) in Focus so let's wait to see how that is resolved before triaging further.

**Comment by mcomella** [comment]
Triage: we're making a glean fix in https://github.com/mozilla-mobile/fenix/issues/25607 so let's retest this after that merges.

**Comment by MarcLeclair** [comment]
Triage: Patch is waiting to be be landed https://github.com/mozilla-mobile/fenix/pull/26165 which should fix this issue.

**Comment by Amejia481** [comment]
We can close this as we addressed it on https://github.com/mozilla-mobile/fenix/pull/26165
