### ISSUE TITLE
Update menu copy for What's new and Customize homepage

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#23558]
We want to make the following menu changes in preparation of wallpapers. Partial work of https://mozilla-hub.atlassian.net/browse/FNXV2-19084

![image (2)](https://user-images.githubusercontent.com/1190888/152410264-5b55e4ba-010c-4fe5-afc6-7a4fc0d30039.png)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly build from 02/08 with Huawei MediaPad M2 (Android 5.1.1).

![Screenshot_2022-02-08-13-55-13](https://user-images.githubusercontent.com/89388888/152983170-7d5d3d5d-aa13-4885-a7cf-3526dbe32f16.png)
