### ISSUE TITLE
FNX-5613 ⁃ [releng] Setup Firebase push configuration for nightly builds

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2356]
For push notification support (needed for send tab), we need to integrate with firebase to retrieve registration tokens and messages to be forwarded to our Autopush server. This is being done in https://github.com/mozilla-mobile/android-components/issues/1917.

Integration into Fenix has some releng requirements:

1. Firebase needs to have a `google-services.json` file in the `app/` directory and the google services plugin needs to be added to the build.gradle. More details can be found on [their setup here](https://firebase.google.com/docs/cloud-messaging/android/client).
1. Autopush needs some configuration options as well, the sender ID (the project name on Firebase) being the one that we'd care about the most for providing.
  1. This would be something like a PushConfig in code:
```kotlin
AutoPushFeature(
context,
config = PushConfig(
senderId = "push-test-f408f",
serverHost = "push.service.mozilla.com",
serviceType = ServiceType.FCM,
protocol = Protocol.HTTPS
)
)
```

We would also need a way to stub this out for local dev environments similar to Adjust/Sentry tokens.

**Comment by jonalmeida** [comment]
Fennec seems to remove the code from the sourceSets based on this env var `MOZ_ANDROID_GCM`: https://searchfox.org/mozilla-central/source/mobile/android/app/build.gradle#147-150

**Comment by jonalmeida** [comment]
We've found a better way for Firebase that doesn't involve running their plugin.

We can keep the generated XML attributes in a file that can be read by the client at run-time. It would go in `app/src/main/res/values/values.xml`.

This a supported method as seen here, we just need to figure out storing the prod attributes and disabling push from working (for now) to get this into prod.

**Comment by jonalmeida** [comment]
@sylvestre will follow up on the app keys we would need to go in.

**Comment by sylvestre** [comment]
sent to @mitchhentges (crypted)

**Comment by mitchhentges** [comment]
Do we want to share a Firebase project between all three [Nightly, Beta, Production]?
And how do we want to handle local development builds - will they be able to communicate with Firebase?

**Comment by sarentz** [comment]
The you received is for `org.mozilla.fenix` and should go on our currently (misnamed) Nightly and to the release builds.

AFAIK these keys are bound to the app identifier, so I think we will eventually need two additional ones for `org.mozila.fenix.beta` and `org.mozilla.fenix.nightly`.

Not clear what the local development situation is - we can probably ignore that for now.

**Comment by mitchhentges** [comment]
The credentials file from Google Play had information for "Firefox" and "Firefox Beta", which threw me off.
I looked into separating Fenix into it's own "Project", but that's [not possible/the intended workflow](https://stackoverflow.com/a/37249349)

I'll set this up tomorrow

**Comment by jonalmeida** [comment]
Taking this off the MVP Blocker train.

**Comment by mitchhentges** [comment]
This depends on [this landing](https://github.com/mozilla-mobile/fenix/pull/3225), then I'll wire up the secret to `production` automation

**Comment by mitchhentges** [comment]
After some direct-message discussion with Jon, it sounds like the first channel that we want Firebase working with is `nightly`, not `production`.
We will add support for `beta` and `production` afterwards

**Comment by mitchhentges** [comment]
We need [app keys](https://github.com/mozilla-mobile/fenix/issues/2356#issuecomment-496251650) for `org.mozilla.fenix.nightly`. I'll talk to RelMan
