### ISSUE TITLE
[Bug]: Scrolling to the bottom of the page doesn't actually goes to the bottom

### ISSUE THREAD

**Issue by Jonatan7BR** [mozilla-mobile/fenix#23561]
### Steps to reproduce

Open a website that automatically scrolls to the bottom of the page (using JavaScript scrollTo or scrollIntoView)

### Expected behaviour

The bottom part of the page should be shown

### Actual behaviour

The page scrolls to almost the bottom with a portion hidden. When scrolling manually, the address bar at the top gets hidden and then the bottom part of the page appears.

### Device name

Samsung Galaxy A22

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.0

### Additional information

The same problem doesn't happen in other mobile browsers (such as Google Chrome) and also doesn't happen in the desktop version of Firefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19375)

**Comment by kbrosnan** [comment]
It would be helpful to provide a link to a live page that uses this.

**Comment by Jonatan7BR** [comment]
It's a page I'm building locally, but I've published an HTML on GitHub that does the same thing.
It's on https://jonatan7br.github.io/

Basically, the page writes text on the screen using a typewriter-like effect while keeping the page at the bottom.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-02-04.

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)

**Comment by Sxderp** [comment]
If you have have the pref to always show address bar then scrolling manually doesn't work either. The address bar covers content. I would think that Firefox would set the "content window size" to screen minus the address bar if it's configured to always show..
