### ISSUE TITLE
FNX-5614 ⁃ [Homescreen] Threshold for snapping back into position is too generous when scrolling on homescreen

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2357]
When scrolling on homescreen the snap point is too large and the position of where it ends up is too far. 
[20190508-152626-720x1480.mp4.zip](https://github.com/mozilla-mobile/fenix/files/3159035/20190508-152626-720x1480.mp4.zip)

**Comment by topotropic** [comment]
whoever is working on it, please ping me and we can quickly discuss it

**Comment by Cheap-Skate** [comment]
I think this is the same as or similar to #695 and #786

https://github.com/mozilla-mobile/fenix/issues/695
https://github.com/mozilla-mobile/fenix/issues/786

**Comment by AmyYLee** [comment]
@sblatz please take a look at the video as a guide for updating https://cl.ly/4b8ee336c0db

**Comment by sblatz** [comment]
Here's a demo of the new behavior:
![demo 2019-07-03 12_37_23](https://user-images.githubusercontent.com/4400286/60620239-880dca00-9d8f-11e9-8d3e-f5ccb543ed2b.gif)

**Comment by AndiAJ** [comment]
Hi, verified as fixed on the latest Nightly #11900609 from 9/7/2019 using the following devices:
• Google Pixel 3XL (Android 9)                                                                                                             • 
• Samsung Galaxy S9 (Android 8)
• Samsung Galaxy S7 (Android 7.0)
• Samsung Galaxy S6 (Android 6.0.1)

[Video Samsung S9](https://drive.google.com/file/d/1e2L-BbGMIlW-L7PdhjBh1wOZs7hoyRP-/view?usp=sharing)
