### ISSUE TITLE
Increase tap area for 'Show all' links

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#23570]
We want to make 'Show all' buttons from home fragment touch targets larger.
This will improve the user experience for people with poor eyesight and coordination issues. 

![Screenshot 2022-02-04 at 16 53 31](https://user-images.githubusercontent.com/35462038/152550002-3e7c806d-3f04-49b4-88c8-49b6d382eb75.png)

**Comment by sarah541** [comment]
This will be addressed in the Ui refactoring to compose here : https://github.com/mozilla-mobile/fenix/pull/24171
