### ISSUE TITLE
In the wallpaper setting papge make the text description align with the start of the switch

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#23577]
https://mozilla-hub.atlassian.net/browse/FNXV2-19377

**Comment by delia-pop** [comment]
@Amejia481 This is the current design in the latest Nightly build from 02/28. 
Is this the expected design? 

![Text aligned ](https://user-images.githubusercontent.com/89388888/155993587-b0223cbc-c103-4107-b92f-45382b913f7d.jpg)

**Comment by Amejia481** [comment]
> @Amejia481 This is the current design in the latest Nightly build from 02/28. Is this the expected design?
> 
> ![Text aligned ](https://user-images.githubusercontent.com/89388888/155993587-b0223cbc-c103-4107-b92f-45382b913f7d.jpg)

Yes, it's the request was filed on https://mozilla-hub.atlassian.net/browse/FNXV2-19390 :)
