### ISSUE TITLE
[Bug]: Crash @ specific Reuters URL

### ISSUE THREAD

**Issue by shtstorm** [mozilla-mobile/fenix#23588]
### Steps to reproduce

1. Navigate to https://www.reuters.com/business/healthcare-pharmaceuticals/jj-tried-get-federal-judge-block-publication-reuters-story-2022-02-04/
2. Use either normal or PB mode
3. The URL never finishes loading. Clicking X in the browser menu to stop loading doesn't work either.
4. Browser may reload the site a few times. After waiting for a few seconds, browser crashes without any crash report.

### Expected behaviour

1. The site finishes loading without browser crashing.
2. Clicking X in the menu instantaneously stops loading of any site.

### Actual behaviour

The app closes unexpectedly...

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1

### Device logs

No crash info is being recorded by the browser in regular or PB mode.

### Additional information

* Report Site Issue menu item doesn't work while all this loading is happening.
* __uBlock Origin__ and __Video Background Play Fix__ add-ons are enabled

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19396)

**Comment by OlliKn** [comment]
Does *not* load on ecosia (chromium) and duckduckgo.
But no crash but a message the Page could not be loaded.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Preview Nightly 2022-02-07 but was unable to reproduce it.
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus (Android 9)

**Comment by kbrosnan** [comment]
@shtstorm please provide crash IDs or a logcat of the crash https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information
