### ISSUE TITLE
[Bug]: Issue with multiple tabs selection - showing incorrect number of selected tabs

### ISSUE THREAD

**Issue by sunilk9211** [mozilla-mobile/fenix#23582]
### Steps to reproduce

This was reproducible only sometimes, and after when there were multiple tabs (at least 2) selected, closed and Undo was done. Then if we try to select multiple tabs again it behaves inconsistently.

1. There should be multiple active tabs
2. Open tabs tray
3. Select and close at least 2 tabs in multi-select mode, tab Undo in snackbar to restore tabs
4. Without closing tabs try, repeat step 3  

One more way it can be reproduced -
Put the app in background when at least 1 tab is selected.
https://user-images.githubusercontent.com/36289013/152630734-60c6c01c-142b-4d36-9549-f3b487b5bc70.mp4

Found it on Nightly and Firefox.

### Expected behaviour

- A tab should be selected if we tab on it
- Number of selected tabs should be correctly shown

### Actual behaviour

- It doesn't display the select tabs correctly (blue tick mark drawable is not visiable on it)
- Number of selected tabs in incorrect.

### Device name

Xiaomi Redmi 9A

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

98.0

### Additional information

<img src="https://user-images.githubusercontent.com/36289013/152629034-7cd47704-bdc5-4004-b2b5-bf2c13824ea6.jpg" width="100" height="100">

<img src="https://user-images.githubusercontent.com/36289013/152629042-88db64ec-6bd4-4db9-896a-1ffc3c56202e.jpg" width="100" height="100">
(below screenshot is taken just after 4 selected tabs are closed in above screenshot. So there were actually 2 selected)
<img src="https://user-images.githubusercontent.com/36289013/152629047-5e0af426-94cf-404a-b1f9-697ce73e5f72.jpg" width="100" height="100">

**Comment by Mugurell** [comment]
The video helped greatly in reproducing the issue with putting the app in background, thank you!
Curious about any other details for the first scenario or how easy it is to reproduce it - is there a number of tabs needed, maybe some fast action? Just closing and then restoring tabs doesn't seem buggy for me.

**Comment by sunilk9211** [comment]
> The video helped greatly in reproducing the issue with putting the app in background, thank you! Curious about any other details for the first scenario or how easy it is to reproduce it - is there a number of tabs needed, maybe some fast action? Just closing and then restoring tabs doesn't seem buggy for me.

Sometimes it happens when we do in a fast way. Means open tabs tray and immediately start selecting. At this point, for some random selected tab the selected drawable (tick mark) may disappear(like in the video for 2nd scenario). 
Yes this was not easy to reproduce. if i could reproduce this i will share recording.

**Comment by sunilk9211** [comment]
This may help - https://user-images.githubusercontent.com/36289013/153005180-99e74531-9f4f-4d62-ae08-6bc3f79a0e80.mp4
Also was able to record the crash, but the video size is large not able to upload

**Comment by Mugurell** [comment]
This should be rechecked after https://github.com/mozilla-mobile/fenix/pull/23435 which seems to address the same underlying issue.

**Comment by sunilk9211** [comment]
@Alexandru2909 It seems fixed to me also. Could not reproduce it.
