### ISSUE TITLE
FNX-5615 ⁃ [UX] Navigation history management

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2358]
UX breakout ticket from https://github.com/mozilla-mobile/fenix/issues/966. We need UX to design a view that will allow users to view their navigation history.

@vesta0 can chime in with more detail.

**As mentioned in #966, this is POST MVP work**

**Comment by yoasif** [comment]
Will this also apply to  #1048 or is it only for the "opened from custom tab" use case?

**Comment by sblatz** [comment]
Ah, closing this as dupe of #1048.

Good catch, @yoasif!
