### ISSUE TITLE
FNX-92 ⁃ [Collections] Animations for Collections

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2359]
* [x] #9243 **RESOLVED** Pressing "Save to collection" should match the same animation as long pressing on an open tab. Currently it's different.
* [x] **RESOLVED** The background/top header fades in and tabs slide up from the bottom (this is the same as the share sheet).
* [x] **RESOLVED**  "Select All" in multi-select tabs mode
There should be no animation here (it looks like there's a flash before all the tabs are selected)
* [x] **RESOLVED** There should be no transition animation between "Select tabs" to "Select collection" (fading in/out transitions of the tabs). 
* [x] #9280 **RESOLVED** There's a lag where after tapping on "Add new collection", the control fades out leaving a blank space before the keyboard appears. 
* [x] **RESOLVED** There's something weird happening with the header when transitioning from "Select tabs" to "Select collection" part of "collection" gets cut off
* [x] **RESOLVED** Right now, when multi-select tabs, there's a lot of fade-in/fade-out and reordering of tabs. 
Please fade out items that are not selected and keep order of things that are selected so they don't reshuffle.

Collections bug
https://github.com/mozilla-mobile/fenix/issues/1568

**Comment by AmyYLee** [comment]
@sblatz @ekager I've posted animation edits above. I'll be on PTO so please reach out to @topotropic if you need a UX person to review.

**Comment by vesta0** [comment]
@AmyYLee is this a P1?

**Comment by AmyYLee** [comment]
@vesta0 This should be the same priority as https://github.com/mozilla-mobile/fenix/issues/2896
This is the animation portion

**Comment by topotropic** [comment]
@AmyYLee can you review this and see if it's still relevant? Thanks!

**Comment by AmyYLee** [comment]
@topotropic Hi, I've updated the above. Let me know if you need any new issues filed.

**Comment by ValentinTimisica** [comment]
Hello @AmyYLee , I have a question regarding "** Pressing "Save to collection" should match the same animation as long pressing on an open tab. Currently it's different." It's not clear for me which of them is the correct animation and which is the wrong one.

**Comment by AmyYLee** [comment]
> Hello @AmyYLee , I have a question regarding "** Pressing "Save to collection" should match the same animation as long pressing on an open tab. Currently it's different." It's not clear for me which of them is the correct animation and which is the wrong one.

Hi @ValentinTimisica 

It should copy the "long pressing on an open tab" animation. Let me know if this is clear.

**Comment by ValentinTimisica** [comment]
Hello @AmyYLee, I need a feedback regarding a possible fix for this issue: "There's a lag where after tapping on "Add new collection", the control fades out leaving a blank space before the keyboard appears."

Looks like right now there is a fade in animation with 200 ms of duration in `Name collection` (after pressing `Add new collection`). After this animation ends, then the keyboard is shown. I tried showing the keyboard before the animation starts but this introduces another bugs. The only fix I can think about right now is to remove this fade in animation.

Here you can see the [before video](https://drive.google.com/file/d/1Y_4XLfJR_rhfZ4VXR_8KTfcu-GownF-g/view?usp=sharing) with the fade in animation and the [after video](https://drive.google.com/file/d/1COtwttcf1xQIh7y5LtY9xN5wwtG0pm9S/view?usp=sharing) with no animation. What do you think, should we go on with this fix?

**Comment by AmyYLee** [comment]
@ValentinTimisica Hi, the new version looks good to me. Yes let's go with that. Thank you.

**Comment by ValentinTimisica** [comment]
Hello @AmyYLee, should we close this since all the dependencies are done?
