### ISSUE TITLE
Missing translation for Hindi language

### ISSUE THREAD

**Issue by sunil9211** [mozilla-mobile/fenix#23590]
### Steps to reproduce

Wallpapers screen and some other screens have strings which don't have translation in Hindi.

<img src="https://user-images.githubusercontent.com/36289013/152670422-75f8f964-2fed-478b-93c2-a6bd6026b98e.jpg" width="30%" height="30%">

<img src="https://user-images.githubusercontent.com/36289013/152670426-b7cfd92c-3f6a-411d-b775-e883aa885fe0.jpg" width="30%" height="30%">

<img src="https://user-images.githubusercontent.com/36289013/152670434-025cc6e4-1a12-4b5b-8c90-d48a123fd019.jpg" width="30%" height="30%">

<img src="https://user-images.githubusercontent.com/36289013/152670437-40f70786-22fe-451b-87be-bb6042d78a15.jpg" width="30%" height="30%">

<img src="https://user-images.githubusercontent.com/36289013/152670430-960af1d9-b5cf-4f7d-aef4-854f454d3de8.jpg" width="30%" height="30%">

### Expected behaviour

Translation in Hindi should be available.

### Actual behaviour

Translation in Hindi is not available.

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

98.0

**Comment by sunil9211** [comment]
I would like to add these translations. Can someone assign this issue to me please?

**Comment by robovoice1** [comment]
https://pontoon.mozilla.org/hi-IN/
https://pontoon.mozilla.org/hi/

I cannot assign you, but for localization moz, pontoon  is used.

**Comment by sunil9211** [comment]
Thank you @robovoice1 :slightly_smiling_face:

**Comment by sunil9211** [comment]
@robovoice1 Hi. Can you please tell me how to join the teams on Pontoon. The mailing list links given in Info section are not working (Error 404).

**Comment by robovoice1** [comment]
Just create a mozilla account, log in pontoon, search for a moz project you want to translate, start translating the strings.
For questions/issues/feedback/faq/help please take a look at discourse.
https://discourse.mozilla.org/c/pontoon/258
https://discourse.mozilla.org/c/l10n/547

Hope this helps.

**Comment by sunil9211** [comment]
Okay. Thank you.
