### ISSUE TITLE
[Bug]: The logo animation is not displayed right after a fresh install or update

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23608]
### Steps to reproduce

1. As a new user, install and launch Firefox Browser app.
2. Dismiss the Onboarding screen.
3. From the homepage, observe the logo.
 OR
1. As an existing user, update and launch Firefox Browser app.
2. From the homepage observe the logo.

### Expected behaviour

As a new user, after dismissing the onboarding and landing on the homepage, the Firefox logo displays an animation, to draw attention.
As an existing user, after update and launch, the Firefox logo displays an animation, to draw attention.

### Actual behaviour

As a new user, the Firefox logo displays an animation only after restarting the application 2 more times.
As an existing user, after update, the Firefox logo displays an animation only after restarting the application one more time.

### Device name

all

### Android version

all

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 from 02/07.

### Additional information

New user Xiaomi Redmi Note 8T (Android 9):
https://user-images.githubusercontent.com/89388888/152824108-3763447f-cf8e-4721-bcea-c466c550c055.mp4

Existing user Huawei MediaPad M2 (Android 5.1.1):
https://user-images.githubusercontent.com/89388888/152824358-324bda9a-1b65-4e85-9dde-d83791aedc52.mp4

**Comment by Amejia481** [comment]
We want to show the animation in a time when the user is less distracted

> The Heuristics are:
> 1) The animation hasn't shown before.
> 2) The user has been onboarded.
> 3) The user has use the app at least three times or more.
> 4) The user is part of the right audience locale "en-US" and "es-US".

**Comment by delia-pop** [comment]
Verified as fixed on Beta 99.0.0-beta.5, Nightly 100.0a1. and RC 98.3.0.
