### ISSUE TITLE
Scroll to top navigation element

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/fenix#23602]
When reading long articles, sometimes I want to scroll to the top to use the site navigation elements or title and author.  This requires "rage scrolling", or repeated long top-to-bottom swipes, to accomplish.  I would like to add an element to the hamburger menu that allows doing this in two taps.  This is similar to hitting "Home" on a desktop computer.

A  more generalized version of this would allow navigating to any `<h1>` element, top, bottom, etc.  This could also be accomplished via an addon if Firefox had a more accommodating policy.

This would benefit all users to a small degree but has a primarily a11y benefit for users with reduced motor control.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19404)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813179

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
