### ISSUE TITLE
Do not use simpleName to construct a URI in wallpapers

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#23619]
`simpleName` is not a safe value to use for constructing a URI.

https://github.com/mozilla-mobile/fenix/blob/b7b601eee1580bfb21a32e253e58b7eae016a31e/app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt#L76-L78

We've had this bug before where the platform underneath can change the output of what we expect `simpleName` to be.

See: https://github.com/mozilla-mobile/fenix/issues/20830

cc: @Amejia481 @MatthewTighe

**Comment by MatthewTighe** [comment]
Thanks for pointing this out! I'll put up a patch shortly
