### ISSUE TITLE
[Bug]: Long-pressing on text in a textarea should not only select text, but also open the on-screen keyboard

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#23612]
### Steps to reproduce

1. Install Google Keyboard.
2. Go to reddit's mobile site while logged in, and begin to write a comment. Type some text, but do not submit the comment.
3. Unfocus the comment textbox, e.g. by tapping a non-interactive page element.
4. Long-press on a word or phrase in the comment textbox to select it.

### Expected behaviour

The textbox should receive focus, the text should be selected, and the on-screen keyboard should open.

### Actual behaviour

The textbox receives focus (indicated visually by a blue outline, at least in the site's dark theme) and the text is selected, but the on-screen keyboard is not opened. It will not open until you tap the textarea, which also deselects the selected text.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.3.1 (Build #2015860755), 5e0953d24+

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1754043

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
