### ISSUE TITLE
[Bug]: cannot play Facebook watch video

### ISSUE THREAD

**Issue by ICHx** [mozilla-mobile/fenix#23628]
### Steps to reproduce

1. Join a Facebook watch Livestream 
https://m.facebook.com/icable.news/videos/%E8%A1%8C%E6%94%BF%E9%95%B7%E5%AE%98%E6%9E%97%E9%84%AD%E6%9C%88%E5%A8%A5%E6%99%A4%E5%82%B3%E5%AA%92/499179788260622/?_rdr
2. Try to play
3. Disable addon and privacy protection and try again

While Livestream cannot play, normal video can.

### Expected behaviour

The livestream should play

### Actual behaviour

It didn't, black screen
![Screenshot_20220208-101403~2](https://user-images.githubusercontent.com/11556527/152904987-526a1536-77cf-417b-9ead-c91afd057252.png)

### Device name

Sony Xperia 10 iii

### Android version

android 11

### Firefox release type

Firefox

### Firefox version

96.3.1 (Build #2015860755), 5e0953d24+ AC: 96.0.15, 0178a6fde9 GV: 96.0.3-20220126154723 AS: 86.2.2

### Device logs

Didn't crash

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19423)

**Comment by kbrosnan** [comment]
This works for me using Firefox 96 and 98 on a Pixel 6 Pro

**Comment by Amejia481** [comment]
@ICHx, would you mind sharing your Tracking protection settings? Go to Settings -> Enhanced Tracking Protection and take a print-screen of the settings page.

<img width="102" alt="image" src="https://user-images.githubusercontent.com/773158/153221762-ec463088-2875-4cf9-a3ec-3a6d672e15bb.png">

Additionally, it looks like some permissions has changed from the default ones on this site. Would you mind to also share a print-screen of the permissions for this site? You could do that by tapping on the shield icon on the toolbar, a dialog will show up, showing the permissions that have been granted/blocked for the site. Something similar this dialog below: 

![image](https://user-images.githubusercontent.com/773158/153222483-fb2d3420-604f-4a0a-a047-2b34063c066d.png)

**Comment by ICHx** [comment]
> 
https://youtu.be/kQBSyCsb3-Q

**Comment by ICHx** [comment]
> This works for me using Firefox 96 and 98 on a Pixel 6 Pro

Hi, are you trying the replay or grabbing a randomly live stream

**Comment by Amejia481** [comment]
@ICHx ,sorry, if it's not much trouble would you mind translating into English  the auto play status label? 
![image](https://user-images.githubusercontent.com/773158/153427250-b9c025e1-2423-4039-9ccf-eef7aaeca3cb.png)

**Comment by ICHx** [comment]
It means, autoplay is explicitly allowed.

**Comment by Amejia481** [comment]
Thanks 👍🏽 .
It's really odd, the only things that I could think that cause this issues are:

* Auto play -> that It's enabled.
* Tracking protection -> it's off for this site. 

This will require further investigation.

**Comment by delia-pop** [comment]
Hi, @ICHx are you still encountering this issue on the latest Firefox version?

**Comment by ICHx** [comment]
> Hi, @ICHx are you still encountering this issue on the latest Firefox version?

Yes, still not working.

please test with any live Facebook video.

106.1.0 (Build #2015909131), 71ca6c1f7+
AC: 106.0.5, 5f06485fc3
GV: 106.0-20221010181815
AS: 94.2.1

**Comment by ICHx** [comment]
> Thanks 👍🏽 . It's really odd, the only things that I could think that cause this issues are:
> 
> * Auto play -> that It's enabled.
> * Tracking protection -> it's off for this site.
> 
> This will require further investigation.

It is the video is not playing, and seems unrelated to the settings.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813887

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
