### ISSUE TITLE
The website not working correctly

### ISSUE THREAD

**Issue by ojedaclaudio** [mozilla-mobile/fenix#23620]
Hi.
I have a problem with the website: bbva.com.ar
The web page does not load, leaving a blank page.  sometimes it loads, after a long time and with many errors (images, menus, etc. 
It only happens with the app on Android, in the Windows browser it works correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19418)

**Comment by sflorean** [comment]
I wasn't able to reproduce this issue on Nightly 99, with One Plus 9 (Android 11). The page was loaded fast, and the images were displayed. 
@clauudeL what device are you using? Can you please try again on Chrome? Might be site issue for specific device, and you can file those bugs under settings->report site issue.
