### ISSUE TITLE
FNX-5616 ⁃ Telemetry for History Management

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2362]
#### Description & Product Manager / Data Scientist User Story
As a product owner, I want to track the usage of history management section in Fenix so that I can understand how our users leverage this feature, and detect anomalies or issues in user flow and usage.

#### Hypothesis
We believe this feature is useful to users, and successful when

* % of users browsing history increases
* % of users opening website via history section

#### What questions will you answer with this data?
* How often do users open the history section?
* Do users delete or share a previously visited site?
* Do users open a previously visited site in a new regular or private tab?
* Do users delete all history?

#### What probes
* History section opened
* History items deleted or shared
* History items opened in a new regular or private tab
* Tap on delete all history

Dependencies (Added by PM and Eng)

* Glean SDK (Event ping)

### Acceptance Criteria
* Event pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to review the telemetry

NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by sblatz** [comment]
@vesta0 will likely want to create this data request.

**Comment by AndiAJ** [comment]
Hi, the History Management telemetry still doesn't work properly on the latest Nightly Build #11980613.

<details>
    <summary> What works ✅</summary>

• History section opened
• History items deleted or shared
• Delete all history

[Logcat](https://github.com/mozilla-mobile/fenix/files/3402049/one.txt)

[Dashboard ](https://debug-ping-preview.firebaseapp.com/pings/aj-test-170716)
</details>


<details>
    <summary>What doesn't seem to be working ❌</summary>

► History items opened in a new regular or private tab
I've used the following steps:
1. Perform a search  - Ping 8b7d8084-62a0-4c50-9f84-6d44a1f66760
2. Navigate to History  - Ping 48e7cecb-eca5-4521-90ce-d6b71e9ffc68
3. Select a history item
4. Open in private tab - Ping 8b0e2338-b0f3-4906-9b25-83b07d237976
5. Switch back - Ping 12e7af78-1b87-4906-b653-feb52b72c1be
6. Go to history - Ping 2fd7824d-8f98-4a9c-bb39-d7da1d3288aa
7. Open in new tab - ❌no ping generated

[Logcat](https://github.com/mozilla-mobile/fenix/files/3402177/jiji.txt)
[Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test-170720)

► Delete a single history item using the 3dot button 
❌No ping is generated
![20190717_163055](https://user-images.githubusercontent.com/51314259/61380137-8248d600-a8b1-11e9-8855-ba2566ea7821.gif)


@sblatz - Could you also please confirm if the Open in private tab events ping was correctly generated?

**Comment by AndiAJ** [comment]
Hi, I've retested the History Management telemetry and it looks like it works fine on the latest Nightly Build #190724 from 24/7.

<details>
    <summary>Actions using single history item </summary>

• History section opened **Ping 9535edce-27be-49df-b979-bb7c7f43e9f1**
• History items deleted or shared **Ping d67235aa-6470-4c7e-a591-8806a039bee0**
• History items opened in a new regular **Ping f40cece6-d2b5-4f7a-9af7-9991ee2c8b48**
• History items opened private tab **Ping 8f89164e-41ea-4726-ac20-3ce773e47d92**
• Delete all history **Ping d8b02dc7-59ec-49c5-ba3b-f20dfb62b41a**

[Logcat](https://github.com/mozilla-mobile/fenix/files/3427340/gg.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-240707)


</details>

<details>
    <summary>Actions using multiple history items </summary>

• History section opened **Ping d367292e-9d65-47fa-b8ef-f4821bbd0767**
• History items deleted or shared **Ping a08439c8-d585-41f3-9de2-9e0db5ababaa**
• History items opened in a new regular **Ping 4921a975-30e3-4b7f-bff3-d1ee1df7ad7e**
• History items opened private tab **Ping 619bf6c1-8d99-47e1-8135-f7d3a3cca2a6**
• Delete all history **Ping fa0cefef-52b3-422c-8403-d251a486611d**

[Logcat](https://github.com/mozilla-mobile/fenix/files/3427371/gg2.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-240708)



</details>

But before closing this ticket I would highly appreciate if @boek & @sblatz could help me clarify some aspects regarding the opening of history items in private tabs:

• To recognize a history item opened in a private tab should we relate only on the switch from normal to private browsing ?

<details>
    <summary>Example from Ping 8f89164e-41ea-4726-ac20-3ce773e47d92</summary>

"category": "events",
          "name": "app_opened",
          "extra": {
            "source": "APP_ICON"
 
</details>

• Why do we have in both single & multiple History items opened private tab 2x library closed and 2x history opened?

<details>
    <summary>Example from Ping 8f89164e-41ea-4726-ac20-3ce773e47d92 (Single history item opened in PB)</summary>
 {
      "events": [
        {
          "timestamp": 0,
          "category": "history",
          "name": "opened_item"
        },
        {
          "timestamp": 65,
          "category": "library",
          "name": "closed"
        },
        {
          "timestamp": 66,
          "category": "library",
          "name": "closed"
        },
        {
          "timestamp": 104,
          "category": "history",
          "name": "opened"
        },
        {
          "timestamp": 104,
          "category": "history",
          "name": "opened"
        },
        {
          "timestamp": 117,
          "category": "events",
          "name": "app_opened",
          "extra": {
            "source": "APP_ICON"
          }
 
</details>

**I'll remove the QA needed label, and will close it after your confirmation.**

**Comment by sblatz** [comment]
> To recognize a history item opened in a private tab should we relate only on the switch from normal to private browsing ?
I think this seems reasonable.

> Why do we have in both single & multiple History items opened private tab 2x library closed and 2x history opened?

This is happening because we're changing the theme which requires the app to recreate. Unfortunately I don't think there's a way around it. 

@boek what are your thoughts on this?

**Comment by sblatz** [comment]
Bumping @boek on this :)

**Comment by AndiAJ** [comment]
Hi **verified as fixed** on RC 1.2-rc2 using a Google Pixel 3a (Android 9).

<details>
    <summary>Actions using single history item</summary>

• History section opened Ping 92f947ec-1586-484e-b519-68319bbc3964
• History item deleted 3dot button Ping bc1b743f-c193-4a0b-a723-b17c19a2d5b1
• History items deleted or shared Ping f633c7a4-a6a9-4c9b-87f4-c06b5dd7ad8c
• History items opened in a new regular Ping 9b45cee5-afca-41f1-b6c9-5e57463e9c7b
• History items opened private tab Ping 9ef1e09b-4983-4822-aaf3-b168068d3844

[Logcat](https://github.com/mozilla-mobile/fenix/files/3461487/single.history.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-020804)

</details>



<details>
    <summary>Actions using multiple history item</summary>

• History section opened Ping 7c0c041f-6e98-45c5-ab5d-708a1a067298
• History items deleted or shared Ping 0e4a8a76-221f-4818-aa6f-22cfe5959a78
• History items opened in a new regular Ping d085cc36-81b3-4898-9bab-214c172c4e2f
• History items opened private tab Ping 5c515c77-6d26-4e49-80ba-3fd10a5b1ff1
• Delete all history Ping 66d1f363-8b6f-4d29-8695-9b24323e04d2

[Logcat](https://github.com/mozilla-mobile/fenix/files/3461501/multihistory.txt)
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-020805)

</details>

@boek - It would be great to clarify the above mentioned two aspects.

**Comment by boek** [comment]
@AndiAJ unfortunately that is correct. I filed https://github.com/mozilla-mobile/fenix/issues/4509 to track/follow up later
