### ISSUE TITLE
[Bug]:  Secret Settings not translated in selected de language

### ISSUE THREAD

**Issue by robovoice1** [mozilla-mobile/fenix#23632]
### Steps to reproduce

1. Open Fenix browser
2. Go to settings/about Firefox nightly
3. Tap 5 times on the firefox logo to enable secret settings
4. Change to german language
5. Result is: Secret settings, Secret debug info, nimbus experiments are in english

### Expected behaviour

Fully translated Firefox nightly.
On pontoon everything is translated 100%

https://pontoon.mozilla.org/de/

### Actual behaviour

3 hidden options (and the pages behind them)  are displayed in english in selected german language

### Device name

Google 6 pro

### Android version

Android 12 GrapheneOs

### Firefox release type

Firefox Nightly

### Firefox version

98.0a1 (Build #2015862027), bae20d650+

### Additional information

![Screenshot_20220208-074805](https://user-images.githubusercontent.com/92784377/152933397-dd7da23e-8ab0-4bbc-9da6-7b81ab3658e9.png)
![Screenshot_20220208-074826](https://user-images.githubusercontent.com/92784377/152933544-1deb7a40-1470-4fbe-ae74-9af14ee51aa7.png)
![Screenshot_20220208-074850](https://user-images.githubusercontent.com/92784377/152933578-3a736bfe-1bc4-452e-b632-793bad13f094.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19426)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-02-08.
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)

**Comment by koehlermichael** [comment]
Of note, these strings don’t seem to be available on Pontoon right now.

**Comment by koehlermichael** [comment]
Interesting point, thanks, I didn’t realize that.

**Comment by robovoice1** [comment]
Same here, and thanks for the info
@cadeyrn and @koehlermichael
