### ISSUE TITLE
Open existing tab instead of new one if website address is exactly same

### ISSUE THREAD

**Issue by sunilk9211** [mozilla-mobile/fenix#23630]
### Steps to reproduce

https://user-images.githubusercontent.com/36289013/152916447-9f1d0ef0-64a7-4c6e-86b2-5e875105311e.mp4

1. Open any website link
2. Go back to home screen
3. Again open the same website link

### Expected behaviour

If a tab already exists with exactly same address, then that should open, not a new tab.
User might end up having several tabs of the same web address.

### Actual behaviour

A new tab will open even if a tab exists with same address.

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

98.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19424)

**Comment by klint** [comment]
Is that the default behavior on desktop? Not sure

**Comment by sunilk9211** [comment]
> Is that the default behavior on desktop? Not sure

Yes

**Comment by klint** [comment]
yeah I see what you mean, but any url will open in the current tab on desktop : it's not linked to the URL being the same or not.

**Comment by sunilk9211** [comment]
If i have a bookmark, i will be probably clicking on it in home screen everytime i want to open it.
That opens a new tab.
Now after visiting that website, if go back to home screen or back press. That tab will remain open.
Again i open bookmarked website, again i get new tab.
What if there is an option to enable opening any website in same tab(home screen) and if back press is clicked it gets back to home screen without letting that new tab remain open.

**Comment by sunilk9211** [comment]
thanks @klint

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813734

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
