### ISSUE TITLE
[Bug] Unable to see detailed logging from application-services components

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/fenix#2363]
When using Fenix, log messages from application-services components are limited to "INFO" logs, which is good for performance but not good when diagnosing issues.

@grigoryk, @thomcc and myself had a chat in slack about this, and it turns out that because Fenix is using a megazord build, it must make a call to `RustLog.setMaxLevel(Log.Priority.DEBUG, includePII = <bool_value>)` to see more detailed logging.

`includePII` set to true gives the most detailed logging but it (obviously) may include PII, so isn't for everyone.

So in an ideal world, we'd have some hidden/advanced UI, or something like about:config :wave:  that allows you to choose between "default logging" (ie, the status quo), "debug logging" or "very verbose logging which may include PII"

**Comment by ekager** [comment]
Could we turn on debug level logs only on debug builds?
