### ISSUE TITLE
[Bug]: For random History item(s) delete icon is still visible in Multiple selection mode

### ISSUE THREAD

**Issue by sunilk9211** [mozilla-mobile/fenix#23635]
### Steps to reproduce

1. Open history (Make sure there are enough items in list, maybe above 15)
2. Long click to select any random item
3. Check the delete icon should not be visible for any item

https://user-images.githubusercontent.com/36289013/152956307-0c7eded6-63db-45d2-9766-a392cadb5453.mp4

### Expected behaviour

 The delete icon should not be visible for any history item in multiple selected mode.

### Actual behaviour

The delete icon is still visible for some random history item.

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

98.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19427)

**Comment by sunilk9211** [comment]
Please, can someone assign this to me?

**Comment by amocirean** [comment]
Hello @sunilk9211 , I was not able to reproduce the issue on the latest RC and Nightly.
Please let us know if the issue still occurs, as it could be related to settings or device.
You could try re-testing this by using a clean profile or on the latest version of RC. Could you also provide a video if it is still occuring?

Tested on:

Huawei P40 Lite (Android 10)
Xiaomi Mi 11 Lite (Android 11)

**Comment by sunilk9211** [comment]
> Hello @sunilk9211 , I was not able to reproduce the issue on the latest RC and Nightly. Please let us know if the issue still occurs, as it could be related to settings or device. You could try re-testing this by using a clean profile or on the latest version of RC. Could you also provide a video if it is still occuring?
> 
> Tested on:
> 
> Huawei P40 Lite (Android 10) Xiaomi Mi 11 Lite (Android 11)

Thank you for checking this. Sure, i will test it again.
