### ISSUE TITLE
Smooth scroll activated position issue

### ISSUE THREAD

**Issue by heavyrocks** [mozilla-mobile/fenix#23646]
## Site with issue and any steps to reproduce
[Test.bookthewaxroom.com](http://test.bookthewaxroom.com) 
### Expected behavior
On page anchor links always scroll page so anchor is at top of page.
### Actual behavior
Clicking a link that is above or visible in the viewport works correctly. If the anchor is below the viewport the page will scroll until the bottom of the anchor element is at the bottom of the page only, instead of the top of the element to the top of the page. 
This issue goes away when you set scroll-behavior to auto. Setting scroll-behavior to smooth seems to cause it.
### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
This does not affect the issue. 
### Can you reproduce in Chrome (or other non-Mozilla browser)?
No, I do not see this issue on chrome for Android, nor in desktop Firefox or chrome. 

### Device information

* Android device: Pixel 6 with Android 12
* Fenix version: 96.3.1 (Build #2015860755),

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19433)

**Comment by somewhat-heavy-rocks** [comment]
Here is a link to a video showing the behavior. 

https://drive.google.com/file/d/1lYMhZVJglOG8EXg-BCfqKw01Jx2Ki3xE/view?usp=drivesdk

**Comment by kbrosnan** [comment]
Please check the behavior of https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.mobile/android-aarch64-gcp-opt It is a bare bones browser that will tell us if this is a Gecko team bug or a Fenix team issue.

**Comment by somewhat-heavy-rocks** [comment]
I believe you are asking me to install a bare bones Fenix browser to check and see if the issue persists. When I go to the page you linked, the two apk lines I see do not appear to link to a download, I get a site cannot be reached error.
