### ISSUE TITLE
FNX-5617 ⁃ [Bug] Video player image appears behind video

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2364]
## Steps to reproduce
Navigate to https://www.cbsnews.com/amp/news/barr-in-contempt-of-congress-hearing-judiciary-committee-vote-attorney-general-barr-mueller-report-today-2019-05-08/

Doesn't matter if TP is on or off.

### Expected behavior
No play icon appearing behind video.

### Actual behavior
Large play icon appearing behind video.

![signal-attachment-2019-05-08-230454](https://user-images.githubusercontent.com/152493/57427563-6ca09b80-71f2-11e9-8b01-3dd87b85ce49.png)

Does not appear in Fennec, Focus, or Reference Browser. 

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by sv-ohorvath** [comment]
Moved to webcompat: https://webcompat.com/issues/31248
