### ISSUE TITLE
Wallpapers do not switch their version based on orientation when changed

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#23644]
Steps to reproduce:

1. Navigate to wallpaper settings screen
2. Rotate device

Expected Results:

Wallpapers thumbnails switch their image based on orientation

Actual Results:

Wallpaper thumbnails continue using image based on their original orientation

**Comment by sflorean** [comment]
Verified as fixed on Beta 99.0.0-beta.1 and 100.0a1.
