### ISSUE TITLE
Bookmark sorting

### ISSUE THREAD

**Issue by sergioad** [mozilla-mobile/fenix#23647]
Hello everyone, could you please add an option in the bookmarks menu to manually sort bookmarks by dragging them?

### What is the user problem or growth 
This would allow people without Firefox for PC or without a PC to sort new bookmarks

### How do you know that this problem exists 
Since the older code base

### Who will benefit from it?
Everyone

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/4348
