### ISSUE TITLE
Login entry is not put first when password is copied if sorted by recently used

### ISSUE THREAD

**Issue by leplatrem** [mozilla-mobile/fenix#23652]
### Steps to reproduce

1. Open parameters
2. Saved Logins
3. Sort by «Recently Used»
4. Click on a login entry down the list
5. Copy password

### Expected behaviour

When going back to the list of saved logins, the entry from which we copied the password should be first now

### Actual behaviour

The fact that we copied the password did not affect the login «last usage» and it remains down the list.

This is quite annoying when using Fenix's password manager as a replacement of Lockwise.

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

 98.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19435)

**Comment by LaviniaL99** [comment]
Hello @leplatrem 

Thanks for your report!
I retested the above flow on the latest Nightly 99.0a1(Build #2015864619) and i was able to reproduce the issue.

**Device used:**

Samsung S10E -> Android 10

**Comment by fice-t** [comment]
FWIW this behaviour is the same as Firefox Desktop as of v105.0.3. Not sure what the default should be, but at least an option for this would be nice.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812427

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
