### ISSUE TITLE
Intermittent UI test failure - < NoNetworkAccessStartupTests. noNetworkConnectionStartupTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#23653]
### Stacktrace:
02-09 01:34:06.462: D/AndroidRuntime(7882): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
02-09 01:34:06.473: W/libprocessgroup(2070): kill(-7895, 9) failed: No such process
02-09 01:34:06.473: I/libprocessgroup(2070): Successfully killed process cgroup uid 10094 pid 7895 in 42ms
02-09 01:34:06.544: W/app_process(7882): Unexpected CPU variant for X86 using defaults: x86
02-09 01:34:06.548: I/app_process(7882): The ClassLoaderContext is a special shared library.
02-09 01:34:06.549: W/nativebridge(7882): Failed to bind-mount /system/lib/x86/cpuinfo as /proc/cpuinfo: No such file or directory
02-09 01:34:06.567: D/AndroidRuntime(7882): Calling main entry com.android.commands.svc.Svc
02-09 01:34:06.569: D/AndroidRuntime(7882): Shutting down VM
02-09 01:34:06.570: V/SettingsProvider(2070): Notifying for 0: content://settings/global/mobile_data
02-09 01:34:06.582: D/ConnectivityService(2070): NetworkAgentInfo [MOBILE (LTE) - 100] EVENT_NETWORK_INFO_CHANGED, going from CONNECTED to DISCONNECTED
02-09 01:34:06.582: D/ConnectivityService(2070): NetworkAgentInfo [MOBILE (LTE) - 100] got DISCONNECTED, was satisfying 20
02-09 01:34:06.585: D/DcNetworkAgent(2373): NetworkAgent: NetworkAgent channel lost
02-09 01:34:06.585: D/DcNetworkAgent(2373): NetworkAgent: DcNetworkAgent: unwanted found mNetworkAgent=null, which isn't me.  Aborting unwanted
02-09 01:34:06.587: I/Zygote(7950): seccomp disabled by setenforce 0
02-09 01:34:06.591: I/ActivityManager(2070): Start proc 7950:com.android.carrierdefaultapp/u0a70 for broadcast com.android.carrierdefaultapp/.CarrierDefaultBroadcastReceiver
02-09 01:34:06.606: I/GnssLocationProvider(2070): WakeLock acquired by sendMessage(UPDATE_NETWORK_STATE, 0, 100)
02-09 01:34:06.608: I/GnssLocationProvider(2070): WakeLock released by handleMessage(UPDATE_NETWORK_STATE, 0, 100)
02-09 01:34:06.613: W/rrierdefaultap(7950): Unexpected CPU variant for X86 using defaults: x86
02-09 01:34:06.616: D/ConnectivityService(2070): Sending DISCONNECTED broadcast for type 0 NetworkAgentInfo [MOBILE (LTE) - 100] isDefaultNetwork=true
02-09 01:34:06.617: I/FTLNetworkMonitor(5889): No Internet access!!
02-09 01:34:06.618: I/FTLNetworkMonitor(5889): Network Info: null
02-09 01:34:06.619: I/GceBroadcastReceiver(3075): Received broadcast: android.net.conn.CONNECTIVITY_CHANGE
02-09 01:34:06.619: W/ContextImpl(3075): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1531 android.content.ContextWrapper.startService:664 com.android.google.gce.gceservice.GceBroadcastReceiver.reportIntent:36 com.android.google.gce.gceservice.GceBroadcastReceiver.onReceive:55 android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0:1391 
02-09 01:34:06.624: D/TcpSocketMonitor(1907): suspending tcpinfo polling
02-09 01:34:06.626: E/ServiceManager(1839): add_service('gce',8b) uid=1000 - ALREADY REGISTERED, OVERRIDE
02-09 01:34:06.626: I/ServiceManager(1839): service 'gce' died
02-09 01:34:06.627: I/NearbyDiscovery(2521): FastPairHandler: Received action android.net.conn.CONNECTIVITY_CHANGE [CONTEXT service_id=49 ]
02-09 01:34:06.651: E/GceRil(1990): Request 135 not supported.
02-09 01:34:06.651: E/WakeLock(2521): GCM_HB_ALARM release without a matched acquire!
02-09 01:34:06.651: W/WakeLock(2521): GCM_HB_ALARM counter does not exist
02-09 01:34:06.655: E/KernelWakelockReader(2070): neither /proc/wakelocks nor /d/wakeup_sources exists
02-09 01:34:06.656: W/BatteryStatsImpl(2070): Couldn't get kernel wake lock stats
02-09 01:34:06.656: W/BatteryExternalStatsWorker(2070): modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
02-09 01:34:06.657: W/BroadcastQueue(2070): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02-09 01:34:06.657: W/BroadcastQueue(2070): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-09 01:34:06.670: I/rrierdefaultap(7950): The ClassLoaderContext is a special shared library.
02-09 01:34:06.675: D/CarrierDefaultBroadcastReceiver(7950): onReceive intent: com.android.internal.telephony.CARRIER_SIGNAL_RESET
02-09 01:34:06.682: D/CarrierDefaultBroadcastReceiver(7950): apply carrier action idx: 6
02-09 01:34:06.682: D/CarrierActionUtils(7950): onCancelAllNotifications
02-09 01:34:06.683: D/CarrierDefaultBroadcastReceiver(7950): apply carrier action idx: 8
02-09 01:34:06.683: D/CarrierActionUtils(7950): onDisableDefaultURLHandler
02-09 01:34:06.686: I/ActivityManager(2070): Killing 2740:com.google.android.gm/u0a82 (adj 906): empty #17
02-09 01:34:06.687: W/libprocessgroup(2070): kill(-2740, 9) failed: No such process
02-09 01:34:06.694: E/WakeLock(2521): GCM_CONN_ALARM release without a matched acquire!
02-09 01:34:06.694: W/WakeLock(2521): GCM_CONN_ALARM counter does not exist
02-09 01:34:06.731: W/libprocessgroup(2070): kill(-2740, 9) failed: No such process
02-09 01:34:06.732: I/Zygote(1908): Process 2740 exited due to signal (9)
02-09 01:34:06.773: W/libprocessgroup(2070): kill(-2740, 9) failed: No such process
02-09 01:34:06.773: I/libprocessgroup(2070): Successfully killed process cgroup uid 10082 pid 2740 in 86ms
02-09 01:34:06.811: I/Remoter(1911): Saved screenshot to '/data/screenshots/__pmv__-0163.jpg'
02-09 01:34:06.891: I/ActivityManager(2070): Force stopping androidx.test.orchestrator appid=10088 user=0: finished inst
02-09 01:34:06.891: W/Binder(2070): Outgoing transactions from this process must be FLAG_ONEWAY
02-09 01:34:06.891: W/Binder(2070): java.lang.Throwable
02-09 01:34:06.891: W/Binder(2070): 	at android.os.BinderProxy.transact(Binder.java:1114)
02-09 01:34:06.891: W/Binder(2070): 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:164)
02-09 01:34:06.891: W/Binder(2070): 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
02-09 01:34:06.891: I/ActivityManager(2070): Killing 7335:androidx.test.orchestrator/u0a88 (adj 0): stop androidx.test.orchestrator
02-09 01:34:06.891: W/libprocessgroup(2070): kill(-7335, 9) failed: No such process
02-09 01:34:06.891: D/AndroidRuntime(7305): Shutting down VM
02-09 01:34:06.931: W/libprocessgroup(2070): kill(-7335, 9) failed: No such process
02-09 01:34:06.951: I/Zygote(1908): Process 7335 exited due to signal (9)
02-09 01:34:06.971: W/libprocessgroup(2070): kill(-7335, 9) failed: No such process
02-09 01:34:06.971: I/libprocessgroup(2070): Successfully killed process cgroup uid 10088 pid 7335 in 79ms
02-09 01:34:06.972: I/app_process(7236): System.exit called, status: 0
02-09 01:34:06.972: I/AndroidRuntime(7236): VM exiting with result code 0.

### Notes
[Logcat.txt](https://github.com/mozilla-mobile/fenix/files/8032981/Logcat.txt)

**Comment by Mugurell** [comment]
I see in logs
```
02-09 01:34:06.142: I/TestRunner(7494): started: noNetworkConnectionStartupTest(org.mozilla.fenix.ui.NoNetworkAccessStartupTests)
02-09 01:34:06.152: I/ConfigStore(7494): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
02-09 01:34:06.152: I/ConfigStore(7494): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
02-09 01:34:06.152: I/oid.documentsu(7371): Waiting for a blocking GC ProfileSaver
02-09 01:34:06.162: E/memtrack(2070): Couldn't load memtrack module
02-09 01:34:06.162: W/android.os.Debug(2070): failed to get memory consumption info: -1
02-09 01:34:06.166: I/oid.documentsu(7371): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 13.421ms
02-09 01:34:06.178: V/SettingsProvider(2070): Notifying for 0: content://settings/secure/accessibility_enabled
02-09 01:34:06.207: D/GeckoNetworkManager(7494): Incoming event enableNotifications for state OffNoListeners -> OffWithListeners
02-09 01:34:06.212: D/GeckoNetworkManager(7494): New network state: UP, CELLULAR, CELL_4G
02-09 01:34:06.247: I/oid.apps.photo(7398): Waiting for a blocking GC ProfileSaver
02-09 01:34:06.262: I/ActivityManager(2070): Start proc 7895:org.mozilla.fenix:mozilla.components.lib.crash.CrashHandler/u0a94 for service org.mozilla.fenix/mozilla.components.lib.crash.handler.CrashHandlerService
```

`CrashHandlerService` is started by GV for native crashes. So it seems something crashed though we don't know what or why.

If this is the only time this test crashed with this logcat I don't think more investigations are needed.
If this test will show more crashes then the crash should also be reproduceable locally where we'll be able to investigate the native crash.

**Comment by AndiAJ** [comment]
Closing as it didn't fail for months.
