### ISSUE TITLE
FNX-5619 ⁃ [Bug] Reader view slow to display after display has been turned off

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2366]
## Steps to reproduce
1. Navigate to :https://www.nbcnews.com/news/amp/ncna1003271
1. Swipe up quick actions bar, tap "Read"
1. Wait for reader view to appear
1. press power button on device
1. unlock device

### Expected behavior
Reader view is displayed as soon as screen is powered on.

### Actual behavior
Reader view is displayed after around 7 seconds.

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by csadilek** [comment]
This has the same cause as https://github.com/mozilla-mobile/fenix/issues/2365 and fix should roll out with next update. @yoasif please re-open if that's not the case.
