### ISSUE TITLE
[Bug]: Firefox changes the status of the login after restarting the app

### ISSUE THREAD

**Issue by BugRMSys** [mozilla-mobile/fenix#23669]
### Steps to reproduce

1. Click the three dot menu.
2. Press to "Sign in to Sync" button.
3. Enter your credentials or use a QR Code based login.
4. Force close the app.
5. Open the app once again.
6. Repeat step 1.
7. Observe.

https://user-images.githubusercontent.com/15137182/153390857-a2452381-828e-4d89-be9e-887311ead4ce.mp4

### Expected behaviour

The logon status is not changed after restarting Firefox.

### Actual behaviour

The user gets disconnected from their account after restarting the browser.

### Device name

Xiaomi 11 Ultra

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

97.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19446)

**Comment by amocirean** [comment]
Hello @BugRMSys , I was not able to reproduce the issue on the latest RC and Nightly.
Please let us know if the issue still occurs, as it could be related to settings or device.
You could try re-testing this by using a clean profile or on the latest version of RC. Could you also provide a video if it is still occuring?

Tested on:

- Huawei P40 Lite (Android 10)
- Xiaomi Mi 11 Lite (Android 11)
