### ISSUE TITLE
Can not Synchronize history from desktop-firefox to android-firefox

### ISSUE THREAD

**Issue by BugRMSys** [mozilla-mobile/fenix#23668]
## Steps to reproduce
1. Search something in desktop-firefox
2. login and synchronize on anroid-firefox
3. click the history in android-firefox: settings->history
4. it showed no releant history that I searched on desktop-firefox

![firefox-02_01](https://user-images.githubusercontent.com/15137182/153388314-4cd43ea6-87e5-4718-a144-30a6a64b69cc.jpeg)

### Expected behavior
![firefox-02_02](https://user-images.githubusercontent.com/15137182/153388326-70ee2ec7-0c97-4be2-8d17-2796de0bab80.jpeg)

### Actual behavior
history from desktop-firefox should be synchronized to android-firefox

### Device information

* Android device: ? xiaomi 11 Ultra
* Fenix version: ? 97.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19445)

**Comment by amedyne** [comment]
@grigoryk Can you take a look?

**Comment by BugRMSys** [comment]
> @grigoryk Can you take a look?

Waiting for your fix. Thank you very much.
