### ISSUE TITLE
[Bug] Undo snackbar not working after leaving the screen it originated from

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#23665]
Steps to reproduce: delete an item from download, bookmarks and history screens, the snackbar with an undo action will popup. Go back to the main screen – Snackbar is there, but pressing the Undo button doesn't actually work, the item is gone.

**Comment by SoftVision-LorandJanos** [comment]
Managed to reproduce on a earlier build (Nightly from 2022-02-10).
Verified as fixed on the latest Nightly (2022-04-28).
The Undo button works as expected on the previous screen.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
