### ISSUE TITLE
In the Firefox mobile share menu, allow me to hide / remove apps

### ISSUE THREAD

**Issue by eyaler** [mozilla-mobile/fenix#23674]
### Steps to reproduce

firefox menu -> share

### Expected behaviour

allow me to control which app appear in the share menu and what order + block certain apps from reappearing.

### Actual behaviour

a list of apps opens with no option to remove or hide apps thus causing a privacy issue (as well as a usability issue). the problem is worsen by the fact that some applications remain stuck in the highlighted "recently used" section although even if not used recently.

### Device name

xiaomi 9 pri

### Android version

android 12

### Firefox release type

Firefox

### Firefox version

97.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19451)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809782

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
