### ISSUE TITLE
FNX-5620 ⁃ [Bug] CNBC - Reader view shows images and text off screen

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2367]
## Steps to reproduce
1. Navigate to https://www.cnbc.com/amp/2019/05/09/trump-on-new-trade-war-tariff-threat-china-broke-the-deal-in-talks.html
1. Swipe up quick actions bar, tap "Read"

### Expected behavior
Text and images are formatted to fit on screen. 

### Actual behavior
Top image looks too large, is displayed extending past expected margin; text runs off screen to right side. 

![signal-attachment-2019-05-09-004626](https://user-images.githubusercontent.com/152493/57428033-7e833e00-71f4-11e9-969d-39ab8c85f9dd.png)

FWIW, Fennec's reader view doesn't seem to have this problem. 

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by csadilek** [comment]
This had the same cause as https://github.com/mozilla-mobile/fenix/issues/2374 and will be fixed in the next update.
