### ISSUE TITLE
 If you collapse the "Inactive Tabs" button, all of your currently-active tabs (listed directly below it) will be described by the title. 

### ISSUE THREAD

**Issue by oserlab** [mozilla-mobile/fenix#23682]
Steps to reproduce
Have Firefox configured to hide inactive tabs (in Settings|Tabs, "Close tabs: never" and "Move old tabs to inactive: [enabled]".
Have some inactive tabs (unviewed for 2 weeks) (I'm not sure if this is required or not for the inactive tabs section to show up, but I'm guessing it might be). Open some new tabs with e.g. news articles.
Look at your tab list (e.g. by tapping the tab icon in the location bar), and scroll to the top.
Expected behavior
The UI shouldn't be confusing about which tabs are vs[.](https://pokkesaves.net/)aren't considered inactive.

Actual behaviour
Right now the UI is confusing, and it looks like it's saying all my tabs are inactive.

At the top of my tab list, there's an outlined area (that kind of looks like a header/title) which says:
[Inactive tabs v ]

And then below that is a list of all of my tabs, including the ones that I opened today (which are definitely not inactive).

If I tap that header (which I didn't initially realize was something that I could do), then it expands into an area which actually contains the truly-inactive tabs. So it seems this "header" is actually an autocollapsed section, which contains the inactive tabs. But it very-much looks like a title for the tabs below it (particularly given the v downarrow, which I think we intend to be a "click to expand" signal, but it looks like it's just pointing to the list of things that follow).

Device name
Google Pixel 4a

Android version
Android 12

Firefox release type
Firefox Nightly

Firefox version
98.0a1

Device logs
No response

Additional information
No response

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19457)

**Comment by amedyne** [comment]
Need UX input to review the user the user feedback on when Inactive Tabs is collapsed.
