### ISSUE TITLE
[Bug]: Smooth scrolling feels heavy for small flicks

### ISSUE THREAD

**Issue by BlitW0** [mozilla-mobile/fenix#23687]
### Steps to reproduce

Scroll any website with small and light flicks.

### Expected behaviour

Ideally page should move exactly with the finger. Scrolling is smoother and feels lighter on chrome or samsung internet. Can also compare with scrolling with small flicks in WhatsApp, it is much much smoother.

### Actual behaviour

Webpage feels heavy and sticky. It takes effort to move the page with small flicks.

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

97.0.0-beta.6

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1755044

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by theres-waldo** [comment]
@BlitW0 would you be able to try the following to see if it improves the experience:

  1. Download and run a [nightly build](https://play.google.com/store/apps/details?id=org.mozilla.fenix) of Firefox for Android. (This is to give you access to the `about:config` page.)
  2. Navigate to `about:config`.
  3. Change the value of the `apz.touch_start_tolerance` preference, from its initial value of `0.06` to something lower. This is the distance of initial finger movement, in inches, that the browser ignores before starting to scroll the page, to avoid scrolling in cases where the gesture is intended to be a tap but still generates a small number of touch-move events. If we can lower this value while still avoiding spurious scrolling when tapping, that could provide a more responsive scrolling experience.

**Comment by BlitW0** [comment]
I tried the config you mentioned and while it was somewhat better, I think you are looking in the wrong direction.

The delay in starting the scrolling is not the problem, but the scrolling itself is. It feels like the scroll acceleration grows too slowly and one can see the page moving like a heavy plank moves up and down.

Whereas in something like WhatsApp, the scroll looks like a slot machine game and stuff that scrolls feels like a blur. As a result it feels smoother.

**Comment by theres-waldo** [comment]
> The delay in starting the scrolling is not the problem, but the scrolling itself is. It feels like the scroll acceleration grows too slowly and one can see the page moving like a heavy plank moves up and down.

Thanks for this clarification. We actually tried to [explicitly align](https://bugzilla.mozilla.org/show_bug.cgi?id=1448439) our behaviour in this area with Chrome's, but its possible their behaviour has changed since then.

There is a tunable pref that may be relevant for this as well: `apz.android.chrome_fling_physics.friction`; decreasing it from its current value of `0.015` should make the fling faster / more frictionless. (See [here](https://searchfox.org/mozilla-central/source/gfx/layers/apz/src/AsyncPanZoomController.cpp#149-162) for a desription of this and other prefs governing the fling animation behaviour.) Would be curious to know if that improves things for you.

**Comment by BlitW0** [comment]
This pref does make the speed increase faster a little. Scrolling still feels heavy though, I think because the initial growth of the acceleration is too slow.

I set the `apz.android.chrome_fling_physics.friction` to `0.08`. But this results in a new problem, there is too much overscroll. The whole page scrolls in almost one flick.

**Comment by theres-waldo** [comment]
Thanks for the feedback. I filed an [additional Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1756275) to track potential further changes to the physics of our fling animation.
