### ISSUE TITLE
FNX-5621 ⁃ [Bug] Fill link from clipboard is only available when location bar is empty

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2368]
## Steps to reproduce
1. copy a URL to clipboard, like https://www.google.com
1. open any page in fenix, like apple.com
1. tap location bar

### Expected behavior
There should be an option to fill link from clipboard. 

On Brave and Kiwi, this is the second option, after the current URL.

### Actual behavior
Fill link from clipboard does not appear.

### Device information
* Android device: pixel 2
* Fenix version: latest from play store

**Comment by ekager** [comment]
This is intentional see #1619 / #2081

**Comment by yoasif** [comment]
In @Verdi's STR in #1619 he says that he typed into the location bar; in my use case, I just tapped the location bar. 

To accomplish what I *want* to do (paste a URL), I have to:

1. tap the location bar
2. clear the url of the page I am on (tap the x on the right of the location bar)
3. tap the fill shortcut

This feels annoying when Brave and Kiwi do what I want, and copying and pasting text is *awful* on mobile (sorry, it always feels fiddly to me - maybe iOS is better). 

Additionally, I'm not sure that the current behavior for autocomplete makes sense - opened bug #2406 around this.

**Comment by vesta0** [comment]
Hi @yoasif thanks for sharing your use case. We will address this use case in either #2089 or #1207. Please let us know what you think of those proposed solutions.
