### ISSUE TITLE
[Bug]: crash with  java.lang.NullPointerException in "org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda1.onClick(Unknown Source:38)"

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#23697]
### Steps to reproduce

Sorry, I unfortunately don't have concrete STR right now, but here's what I've got:

(1) Somehow, last night I ended up with a URL in my clipboard which Android would gladly paste into some apps (e.g. Firefox Nightly and Chrome) but not others (e.g. if I tried to paste into Gmail, I got an empty pasted string; and it'd crash Firefox-for-Android as described below).  The URL happened to be https://mashable.com/video/super-pumped-uber-trailer though I don't think the specific URL is important; rather, there was something special about my clipboard state that made it pastable-for-some-apps-but-not-others.  I unfortunately haven't been able to get back into that state, but I was quite-reliably in that state for a while (most of an hour as shown in my logcat) and I could reproduce this bug 100% reliably while I was in that state.

(2) With the aforementioned URL in my clipboard... Open Firefox or Firefox Beta.

(3) Long-press the URL bar and choose "Paste & Go"

### Expected behaviour

No crash.

### Actual behaviour

Immediate crash (the whole app is taken down).

### Device name

Google Pixel 4a

### Android version

Andoird 12

### Firefox release type

Firefox

### Firefox version

97.1.0

### Device logs

Here's the logcat output from when I crashed a bunch of times in a row when testing this with Firefox Release (currently version 97.1.0, though I was hitting this yesterday so it's possible I was on a slightly-earlier version)

Note that the last crash here is from beta, which I freshly installed from the Play Store last night to see if it was affected (and it was).  It reports itself as being version 97.0.0.beta-6 right now.  (Interesting that release and beta are both currently version 97.something; I assume beta is about to go to v98 but hasn't quite yet).

```
02-10 21:45:33.697 17304 17304 E AndroidRuntime: FATAL EXCEPTION: main
02-10 21:45:33.697 17304 17304 E AndroidRuntime: Process: org.mozilla.firefox, PID: 17304
02-10 21:45:33.697 17304 17304 E AndroidRuntime: java.lang.NullPointerException
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda1.onClick(Unknown Source:38)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-10 21:45:33.697 17304 17304 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: FATAL EXCEPTION: main
02-10 21:45:38.830 17715 17715 E AndroidRuntime: Process: org.mozilla.firefox, PID: 17715
02-10 21:45:38.830 17715 17715 E AndroidRuntime: java.lang.NullPointerException
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda1.onClick(Unknown Source:38)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-10 21:45:38.830 17715 17715 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: FATAL EXCEPTION: main
02-10 21:46:08.246 17972 17972 E AndroidRuntime: Process: org.mozilla.firefox, PID: 17972
02-10 21:46:08.246 17972 17972 E AndroidRuntime: java.lang.NullPointerException
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda0.onClick(Unknown Source:21)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-10 21:46:08.246 17972 17972 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: FATAL EXCEPTION: main
02-10 21:57:15.314 18598 18598 E AndroidRuntime: Process: org.mozilla.firefox, PID: 18598
02-10 21:57:15.314 18598 18598 E AndroidRuntime: java.lang.NullPointerException
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda1.onClick(Unknown Source:38)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-10 21:57:15.314 18598 18598 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: FATAL EXCEPTION: main
02-10 21:57:30.565 19433 19433 E AndroidRuntime: Process: org.mozilla.firefox, PID: 19433
02-10 21:57:30.565 19433 19433 E AndroidRuntime: java.lang.NullPointerException
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda1.onClick(Unknown Source:38)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-10 21:57:30.565 19433 19433 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: FATAL EXCEPTION: main
02-10 21:57:45.437 19870 19870 E AndroidRuntime: Process: org.mozilla.firefox, PID: 19870
02-10 21:57:45.437 19870 19870 E AndroidRuntime: java.lang.NullPointerException
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda1.onClick(Unknown Source:38)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-10 21:57:45.437 19870 19870 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: FATAL EXCEPTION: main
02-10 22:22:55.766 23868 23868 E AndroidRuntime: Process: org.mozilla.firefox, PID: 23868
02-10 22:22:55.766 23868 23868 E AndroidRuntime: java.lang.NullPointerException
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda0.onClick(Unknown Source:23)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-10 22:22:55.766 23868 23868 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: FATAL EXCEPTION: main
02-10 22:23:19.899 24510 24510 E AndroidRuntime: Process: org.mozilla.firefox_beta, PID: 24510
02-10 22:23:19.899 24510 24510 E AndroidRuntime: java.lang.NullPointerException
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda0.onClick(Unknown Source:23)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-10 22:23:19.899 24510 24510 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19470)

**Comment by dholbert** [comment]
My crashes show up on `about:crashes` but only one of them has a socorro link, for some reason (maybe I hit the wrong yes/share option after crashing for the other ones).

Here's that one crash report:
https://crash-stats.mozilla.org/report/index/043318a8-1e85-482c-8c6a-f6e760220211

According to that crash report, my Firefox release installation was actually at version 96.3.1 at that time (and must have later received the update to Firefox 97.1.0 which I have now). But I'm pretty sure 97 is affected as well, since I did indeed crash with installed-fresh-from-play-store-last-night Firefox Beta, as shown in logcat, and that would have been at version 97.

**Comment by kbrosnan** [comment]
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.NullPointerException%3A%20at%20org.mozilla.fenix.utils.ToolbarPopupWindow%24%24ExternalSyntheticLambda1.onClick%28Unknown%20Source%3A36%29

**Comment by grigoryk** [comment]
Nightly: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/17071405/?query=is%3Aunresolved
Release: https://sentry.prod.mozaws.net/operations/firefox/issues/17521062/?query=is%3Aunresolved%20ToolbarPopupWindow

This happens quite regularly!

**Comment by grigoryk** [comment]
Since the STRs here involve Paste&Go, the obvious (and, only..?) place where we can hit an NPE is when we're doing `handlePasteAndGo(clipboard.text!!)` - that is, assuming `clipboard.text` isn't null. I suppose it must be possible for the clipboard contents to have changed in the time between we've constructed these onClick listeners and when they were actually invoked. Or, it's also possible that we're incorrectly reading the clipboard state in `ClipboardHandler#text` (e.g. s).

**Comment by dholbert** [comment]
I just happened to hit this again today, after copying a URL from the Focus's URL bar and then pasting it into Firefox by long-pressing our URL bar and choosing either "Paste" or "Paste & Go".

**Comment by dholbert** [comment]
Crash report from one of the crashes I hit just now:
https://crash-stats.mozilla.org/report/index/40bcc8c1-7aa5-4d67-ad72-88ef30220310

(Backtrace looks the same as [my crash above](https://github.com/mozilla-mobile/fenix/issues/23697#issuecomment-1036703520).

I've confirmed that the crash does *not* happen if I paste from our UI when the keyboard is showing (after I tap the URL bar and allow the keyboard to appear).  From that UI, I tried long-pressing the URL bar and choosing "Paste" (my only option), and I also tried tapping the clipboard contents as a suggestion that appeared at the top of the keyboard (where autocompletions normally appear), and neither of those caused the crash.  But if I then  e.g. hit the "enter" button to load the web page and leave that UI, and then long-press the URL bar and choose paste&go, then I crash.

**Comment by dholbert** [comment]
Ah, I was wrong about my STR.  Here are the actual STR (I think), which seem to be reproducing this reliably after several repeated trials:

(1) Open Chrome.
(2) Visit any site, e.g. https://example.org
(3) Tap Chrome's URL bar at the top of the screen, to make the keyboard appear.
(4) On the line that appears just below the URL bar, **tap the two-overlapping-squares button** (which is "copy to clipboard")
(5) Open Firefox
(6) Long-press Firefox's URL bar and choose "Paste & Go" or "Paste".

ACTUAL RESULTS: Crash.

**Comment by dholbert** [comment]
@kbrosnan / @grigoryk , would you mind testing my STR in previous comment and see if they repro the issue for you as well?

**Comment by dholbert** [comment]
note: I tried my STR on a Pixel 2 w/ Android 11, and on a Samsung SM-T713 Tablet with Android 9 (really "LineageOS" Android reskin/fork)

On both of those devices, when I get to step 6, Firefox simply doesn't offer me "Paste" or "Paste & Go" as options.  If my Firefox URL bar is blank (i.e. it's a new tab), then I just don't get any context menu at all.  Or if it's not a new tab, then Firefox offers me a context menu with "Copy" as the only option.  (And if I try the STR on these devices, except with my clipboard containing a URL **that I copied from within Firefox**, then Paste and Paste&Go do appear and do work properly.)

So: from my own testing, it seems:
* Chrome's "two-overlapping-squares button" (copy-to-clipboard) produces some specially-tainted URL in the clipboard.
* Its specialness causes "Paste"/"Paste&Go" to simply not-be-offered on my two older devices (Pixel 2 w/ Android 11, Samsung SM-T713 Tablet with Android 9)
* ...but on my Pixel 4a with Android 12, the specialness doesn't prevent us from offering these options -- but it causes us to crash if we use them.

**Comment by grigoryk** [comment]
> Ah, I was wrong about my STR. Here are the actual STR (I think), which seem to be reproducing this reliably after several repeated trials:
> 
> (1) Open Chrome (I have version 99 "Official Build") (2) Visit any site, e.g. https://example.org (3) Tap Chrome's URL bar at the top of the screen, to make the keyboard appear. (4) On the line that appears just below the URL bar, **tap the two-overlapping-squares button** (which is "copy to clipboard") (5) Open Firefox (6) Long-press Firefox's URL bar and choose "Paste & Go" or "Paste".
> 
> ACTUAL RESULTS: Crash.

I can confirm that this crash reproduces for me on Pixel 5 + Android 12. With https://github.com/mozilla-mobile/fenix/pull/24180 we won't crash, but I suspect Paste won't actually work out in these case either. Confirming..

**Comment by grigoryk** [comment]
So, yeah, we're not crashing post-#24180, but neither are Paste/Paste Go working as desired in case of these STRs. Interestingly, if the awesomebar is first selected (and we enter an input mode), and then long-pressed, Paste works as expected. So, we're interacting with the clipboard differently there. I'll investigate this more next week.

**Comment by grigoryk** [comment]
https://github.com/mozilla-mobile/fenix/pull/24294 makes Paste/Paste-Go work correctly for me in STRs described in https://github.com/mozilla-mobile/fenix/issues/23697#issuecomment-1063687693.

**Comment by miketaylr** [comment]
> * Chrome's "two-overlapping-squares button" (copy-to-clipboard) produces some specially-tainted URL in the clipboard.

I guess that's happening here, https://source.chromium.org/chromium/chromium/src/+/main:ui/android/java/src/org/chromium/ui/base/ClipboardImpl.java;l=64-65
