### ISSUE TITLE
[Bug]: RBI website doesn't open

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#23701]
### Steps to reproduce

Open website https://rbi.org.in/

### Expected behaviour

Website should open

### Actual behaviour

Website doesn't open. It opens in chrome browser.

### Device name

Samsung A71

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

![Screenshot_20220212-140201_Firefox Nightly](https://user-images.githubusercontent.com/76210878/153703997-daeb29bd-a2a3-4398-9ff1-e6000605e38d.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19472)

**Comment by kbrosnan** [comment]
Looks like a redirect loop. Will try to check on Monday with the desktop devtools.

**Comment by SoftVision-LorandJanos** [comment]
Still reproducible with the latest nightly 109.0a1 (2022-11-29) build.
Device used: Oppo Find X5 (Android 12).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813177

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
