### ISSUE TITLE
[Bug]: On-screen keyboard word suggestions and Fenix address bar autocomplete don't play nice with each other

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#23709]
### Steps to reproduce

1. Visit `https://reddit.com/r/JavaScript/new`, so that it's in your browsing history.
2. Open the address bar.
3. Type `redd`. The browser should autosuggest it to `reddit.com`, with `it.com` placed after the text cursor and displayed as selected text.
4. Tap in the address bar after `reddit.com`. The end of the domain name should cease to display as selected text, and the text cursor should be placed after it.
5. Type `/r/JavaS`. The browser should now autosuggest the `JavaScript` subreddit name, with `cript` placed after the cursor and displayed as selected text.
6. Use your keyboard's own suggestions feature (which will hopefully now suggest the word `JavaScript`) to complete the word `JavaScript`. I use Google Keyboard.

### Expected behaviour

The URL should become `reddit.com/r/JavaScript`. Selecting a word from the onscreen keyboard's word suggestions should count as typing more text, and update Firefox's autocomplete state.

### Actual behaviour

The URL becomes `reddit.com/r/JavaScriptcript`, with the trailing `cript` displayed as selected text and the cursor located before it.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

97.1.0 (Build #2015860771), 365e9fb59+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19476)

**Comment by DavidJCobb** [comment]
I want to point out that 15 days after running into this, Firefox nearly always autocompletes `reddit.com/r/Jav` to `reddit.com/r/JavaScriptcript` even if I just type it manually. This sucks.

**Comment by amocirean** [comment]
Hello @DavidJCobb, thanks for submitting your issue.
I was able to reproduce this on both Latest RC & Nightly.

Tested on:
- Huawei P40 Lite (Android 10)
- Xiaomi Mi 11 Lite (Android 11)

**Comment by lilydjwg** [comment]
This issue is still there.

**Comment by lilydjwg** [comment]
The stalebot is misbehaving???

**Comment by lilydjwg** [comment]
Now I can't agree more with [this article](https://drewdevault.com/2021/10/26/stalebot.html):

> This [the stale bot] is a terrible, horrible, no good, very bad idea.

It just helps to close issues the maintainers don't want to fix and pretend issues have fixed themselves magically.
