### ISSUE TITLE
[Bug] fenix flashes behind homescreen

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#2370]
## Steps to reproduce
1. Open fenix
1. Hide it again by pressing the home button

### Expected behavior
Fenix hides with the normal exit animation

### Actual behavior
In addition to the usual exit animation you can also see the fenix activity quickly flash behind the homescreen icons.

![fenix](https://user-images.githubusercontent.com/4500858/57437820-dd6fa400-7242-11e9-81e6-9ec89db12313.gif)UNITO-UNDERSCORE!homescreen!UNITO-UNDERSCORE!flash!

### Device information
* Android device: 7.1.1
* Fenix version: 1.0.1919

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11367)

**Comment by sv-ohorvath** [comment]
@TitanNano I can't reproduce this issue. Do you still see have this problem? Could you please give us more details about your device?

**Comment by TitanNano** [comment]
@sv-ohorvath yes I'm still seeing this. I have a Sony Z3+ (Model E6533) device with Sony Android 7.1.1. I'm using a third-party home screen but I can reproduce the issue with the Xperia Home launcher too, so it's not an issue with the launcher.
Current Fenix build is 1.0.1920 (Build #11370606 🦎 68.0a1-20190508111321) Friday 5/17 @ 6:05 AM

**Comment by sv-ohorvath** [comment]
I can reproduce this only with animations on, on a Sony Xperia Z5 Premium (Android 7.1.1).
Other apps don't have this behavior.

**Comment by ekager** [comment]
Could we retest this?

**Comment by softvision-miralobontiu** [comment]
This is not reproducible on the latest Nightly build 190809 with Samsung Galaxy Note 8 (Android 9), OnePlus 5T (Android 9), and Nexus 5 (Android 6.0.1).

**Comment by TitanNano** [comment]
@ekager @softvision-miralobontiu I can still reproduce this with `Nightly 190812 06:05 (Build #12240721)`

![bug_reprod](https://user-images.githubusercontent.com/4500858/62899691-a84e8280-bd58-11e9-914b-3d1d43c482c3.gif)

**Comment by softvision-miralobontiu** [comment]
Yes, I was able to reproduce the flash with Sony Xperia z5 Premium (Android 7.1.1) with the latest Nightly build 190812 (#12241855). It wasn't 100% reproducible, but I was able to obtain a logcat, hope it helps.

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3495530/logcat.txt)

![20190813_090614_Trim](https://user-images.githubusercontent.com/40694158/62919239-bd540180-bdaa-11e9-883a-24b101c6ec59.gif)

**Comment by mcarare** [comment]
Could we retest this? Some of the animation have changed since. TY!

**Comment by softvision-miralobontiu** [comment]
This issue is still reproducible on the latest Nightly build from 4/22 with Sony Xperia Z5 (Android 7), and Sony Xperia Z5 Premium (Android 7.1.1).

![flicker](https://user-images.githubusercontent.com/40694158/79980490-dc637100-84ab-11ea-995f-f8bc1bc924cb.gif)

**Comment by softvision-miralobontiu** [comment]
Hi all,
This issue still reproduces on both Sony Xperia Z5 (Android 7), and Sony Xperia Z5 Premium (Android 7.1.1), on the latest Nightly build from 6/11:

<img src="https://user-images.githubusercontent.com/40694158/84485174-6eb21500-aca4-11ea-97ba-45a1fe710de3.gif" width="300" height="550" />

**Comment by liuche** [comment]
This seems to only affect Sony launcher, so this is slightly lower priority

**Comment by hwinnemoe** [comment]
I can reproduce on my Sony Xperia Z2 with the default launcher. Also, switching to home with an open tab only flashes the non-GeckoView parts of the browser. If no tab is currently open, the whole screen flashes with the content of the browser.

**Comment by bswe** [comment]
I have this same issue on my Moto Z Force Droid that's running Android 8.0.0 with Firefox 81.1.2.  This has been happening for several months now.

**Comment by bswe** [comment]
I still have this issue on my Moto Z Force Droid that's running Android 8.0.0 (updated to OCL27.76-69-6-3-1 on Dec 10, 2020) with Firefox 87.0.0-rc.1 (build #2015799099); AC: 73.0.1.1,bea80bbac; GV: 87.0-20210315170302; AS: 71.0.0.

**Comment by hwinnemoe** [comment]
I can also reproduce on my Sony Xperia Z2 with the default launcher, Android 6.0.1, on
Nightly 210428 17:01 (Build #2015807305)
AC: 90.0.20210426143115, feb080f12
GV: 90.0a1-20210426094327
AS: 75.2.0

@bswe  Do you still see the issue? You are the only user without a Sony device that mentioned experiencing this issue.

**Comment by bswe** [comment]
Yes I still see this. I added a comment yesterday that I was still seeing
the flash when Firefox closes.

**Comment by lobontiumira** [comment]
I am able to reproduce this on the 5/28 Nightly build with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by bswe** [comment]
Yes it is and it is annoying.
