### ISSUE TITLE
[Bug]: Firefox Nightly does not respect full-screen-api.warning.timeout

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla-mobile/fenix#23704]
### Steps to reproduce

1. Open `about:config` in Firefox Nightly
2. Change `full-screen-api.warning.timeout` to 0
3. Open any video in full screen

### Expected behaviour

No "Entering full screen mode" message is printed.

### Actual behaviour

"Entering full screen mode" message appears, obstructing the view. The default value of `full-screen-api.warning.timeout` (3000) is not respected either, the message is removed quicker than that.

### Device name

Samsung Galaxy Note 10+

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

**Comment by kbrosnan** [comment]
`about:config` is completely unsupported.
