### ISSUE TITLE
[Bug]: a thin white line appears on scrolling when dark theme is enabled.

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#23715]
### Steps to reproduce

1. With Firefox Nightly 99. 
2. Set Dark Theme
3. Go to https://n.news.naver.com/article/001/0012456219?cds=news_my
4. Scroll up and down

### Expected behaviour

The area in between the top black status bar and the blue top navigation of the website doesn't change

### Actual behaviour

A thin white line appears in between the top black status bar and the blue top navigation.

### Device name

Google Pixel 2

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0

### Additional information

This was reported as a webcompat issue. The issue doesn't reproduce in Chrome.
https://github.com/webcompat/web-bugs/issues/77085

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 2022-02-16. The issue might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1734261.

Devices used:
Google Pixel 6 (Android 12)
OnePlus 6T (Android)

**Comment by kbrosnan** [comment]
Agree that this is the upstream issue that Laurentiu mentions.
