### ISSUE TITLE
[Bug]: Changing the inputmode of an input without losing the focus doesn't work properly.

### ISSUE THREAD

**Issue by RaulPROP** [mozilla-mobile/fenix#23724]
### Steps to reproduce

1. Go to [https://codepen.io/raulprop/pen/KKyXPmy](https://codepen.io/raulprop/pen/KKyXPmy), which has a setup that can reproduce the bug.
2. Focus the editor (in this case a div with a `contenteditable` attribute, but it also happens in an input).
3. Click on the bottom buttons that changes the `inputmode` of the editor element. The focus is not lost because we prevent the default behavior of the `mousedown` event.

### Expected behaviour

The keyboard changes to the desired one.

### Actual behaviour

The keyboard doesn't change and gets stuck in the previous one. Furthermore, if you change the `inputmode` to `none`, the keyboard disappears until the editor loses focus and then gets it back.

### Device name

Xiaomi Mi 10T

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

97.1.0

### Device logs

(There are no logs).

### Additional information

- If the `inputmode` is changed using `requestAnimationFrame` it properly changes it.
- If the `inputmode` is changed from a timeout or an interval, it properly works.
- This was tested also on an iPhone and it doesn't have this problem.
- Any other mobile browsers doesn't have this problem.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19488)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 2022-02-15.

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android)
