### ISSUE TITLE
Reload all tabs option in tab list

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#23728]
Would like to have also the option to `Reload all tabs`. No idea if that option already exists but if does it's not intuitive. The menu would be this:

![](https://i.imgur.com/ViqRzpB.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19492)

**Comment by Disil** [comment]
Why we want to do that? Tabs reload everytime on low-end users, there's no need to provide a button for that. Instead we should fix our memory management, in my opinion.

**Comment by superbonaci** [comment]
@Disil it's just a trivial request. About auto reloading check the problems it causes:
https://github.com/mozilla-mobile/fenix/issues/23743

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812861

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812860

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
