### ISSUE TITLE
~128ms regression to COLD VIEW nav start (ac update?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#23725]
_See also https://github.com/mozilla-mobile/focus-android/issues/6432 for a possibly related regression in focus._

From our backfill regression system:

![image](https://user-images.githubusercontent.com/759372/153925415-256a5658-b93d-41e7-81a0-1f4345c0f283.png)

- 2/9: 2.067s
- 2/10: 2.195s

That's a regression of 128ms to our COLD VIEW nav start metric. Let's find the cause.

**Comment by mcomella** [comment]
Bisection from 2/9 (5bd6f1cb8) to 2/10 (eea4b07cb):
- Good: 80c9ad9100f6e89d15394e05ad86fdbefcfa1515
- Bad: 974653084a6d74fe6a1d785e0392dd3a64aa5da2

Regressing commit: "Update Android Components version to 99.0.20220209143350." ([diff](https://github.com/mozilla-mobile/fenix/commit/974653084a6d74fe6a1d785e0392dd3a64aa5da2))

Unfortunately, we don't have tools to bisect regressions within android-components at this time.

**Comment by mcomella** [comment]
We see a similar regression in focus: https://github.com/mozilla-mobile/focus-android/issues/6432

**Comment by mcomella** [comment]
A profile of the latest Nightly shows we have a GPU process now: https://share.firefox.dev/3BmosCW I don't see this in my profiles from a local mc build from Feb 8 (before the regression). I wonder if this is at all related.

**Comment by csadilek** [comment]
@mcomella GPU process was disabled again in latest Nightly due to us incorrectly handling process kills:
https://bugzilla.mozilla.org/show_bug.cgi?id=1755375
https://bugzilla.mozilla.org/show_bug.cgi?id=1331109

So, if it's the GPU process, you should this fixed in latest Nightly. We will enable again soon though.

**Comment by mcomella** [comment]
fwiw, in two recent profiles, I see:
- a long delay (370ms) in the Parent Process stack trace for `GeckoChildProcessHost::WaitUntilConnected` https://share.firefox.dev/3JCcZlR
- a new SyncIPC call that takes 33.9ms: `PGPU::Msg_GetDeviceStatus — sent to GPU Process (Thread ID: 24093)`https://share.firefox.dev/354IV2Y

2nd profile: https://share.firefox.dev/3gU2TQV

**Comment by mcomella** [comment]
> So, if it's the GPU process, you should this fixed in latest Nightly. We will enable again soon though.

Thanks for the context. To be explicit, we'll get the results for this on Monday when the regression tests run.

**Comment by mcomella** [comment]
The regression was undone so it's likely this was caused by enabling the GPU process. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1756700 upstream for the upstream team to investigate. Since this regression is no longer in the product, I think we can close this bug and take care of the rest in the upstream issue.
