### ISSUE TITLE
FNX-5624 ⁃ [Bug] Redirect back to the app after signing in

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2372]
## Steps to reproduce
1. Make Fenix the default browser.
1. Go to the Slack app, select login with auth0. The auth login will open in the browser.
1. Complete the login in the browser.
    1. Expected behavior
Get redirected to the app after the auth0 login.
    1. Actual behavior
Not redirected, the browser stays on a blank page after login. Slack is not logged in.
    1. Device information

* Android device: Pixel, P9 lite (Android 6)
* Fenix version: 5/8 build.

**Comment by vesta0** [comment]
Will be addressed in #1213
