### ISSUE TITLE
[Bug]: String/message when sending crash reports should reflect Firefox instead of Mozilla

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#23721]
### Steps to reproduce

Try to send a crash report after the application crashed.

Looks like string is from here: https://github.com/mozilla-mobile/android-components/blob/main/components/lib/crash/src/main/res/values/strings.xml#L7

### Expected behaviour

2nd string on the image should say "Firefox had a problem and crashed" instead of "Mozilla had a problem and crashed"

### Actual behaviour

![image](https://user-images.githubusercontent.com/68711330/153889789-3a60cdd6-b1fb-4ac1-b07e-e92b63b99ae5.png)

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

98

**Comment by mcarare** [comment]
AC issue: https://github.com/mozilla-mobile/android-components/issues/11717

**Comment by SoftVision-LorandJanos** [comment]
I have managed to reproduce the issue with the Nightly from the day this was logged in (99.0a1 - 2022-02-14).
Verified as fixed on the latest Nightly 99.0a1 (2022-02-18).
The string now is "Sorry. Firefox Nightly had a problem and crashed." (For Nightly).
Closing the ticket as fixed.
