### ISSUE TITLE
[Bug]: Going "back" after focusing address bar stays on homepage instead of returning to opened page

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#23735]
### Steps to reproduce

1. Be on a web page
2. tap address bar
3. tap "back" button in android nav

### Expected behaviour

I return to the page open in step 1 above.

### Actual behaviour

The browser is on the home page with top sites etc.

### Device name

LG G4

### Android version

Android 6

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build #2015862891), 2fee285f7+
AC: 99.0.20220211143103, f62e501d67
GV: 99.0a1-20220211094209
AS: 91.0.1

**Comment by LaviniaL99** [comment]
Hello @yoasif 

Thanks for your report! I just tested the above flow and i was able to reproduce the issue. 
Tested on the latest Nightly ->99.0a1

**Device used:**
- Samsung S10E -> Android 10

**Comment by LaurentiuApahideanSV** [comment]
I underrated the severity of the issue, I've changed it to S2.

**Comment by czlucius** [comment]
This bug isn't present in Stable Fenix.

**Comment by csadilek** [comment]
This is a regression of https://github.com/mozilla-mobile/fenix/pull/23552. I agree it's high priority so let's back out the fix and improve before landing again. /cc @Alexandru2909 @MozillaNoah
