### ISSUE TITLE
FNX-5625 ⁃ [Bug] Wikipedia title & reading time are misplaced in reading mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2374]
## Steps to reproduce
1. Go to wikipedia.com, pick an article.
1. Switch to reading mode.
    1. Expected behavior
The title & reading time are below the page url.
    1. Actual behavior
title & reading time are in line with the page url.
![Screenshot](https://user-images.githubusercontent.com/4037709/57453438-14f44580-726f-11e9-86fb-1676d2fd6a40.jpg)UNITO-UNDERSCORE!20190509-151446!UNITO-UNDERSCORE!Firefox Preview!
    1. Device information

* Android device: Pixel, Galaxy Tab 3
* Fenix version: 5/8

**Comment by csadilek** [comment]
Thanks for filing! I ran into this as well yesterday. I know what's causing this and will work on a fix in Android Components: https://github.com/mozilla-mobile/android-components/issues/2962

**Comment by csadilek** [comment]
@sv-ohorvath the issue in A-C is resolved now and this should work in the next Fenix Nightly.

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5.10 build.
