### ISSUE TITLE
Remove deprecated layout_constraintHeight_default

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#23747]
```
ConstraintLayout: layout_constraintHeight_default="wrap" is deprecated.
    Use layout_height="WRAP_CONTENT" and layout_constrainedHeight="true" instead.
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19504)

**Comment by mcarare** [comment]
@sunilk9211 Sure, go ahead!

**Comment by sunilk9211** [comment]
should i do it for `layout_constraintWidth_default="wrap"` as well?

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/25066.
