### ISSUE TITLE
[Bug]: tab is auto reloaded even when filling forms

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#23743]
### Steps to reproduce

Sometimes I'm filling a form on a website, and I need to open another tab or application to gather information to put in the form. Well, after returning to that tab, it's reloaded and the form is lost.

Maybe a preference should exist to prevent reloading automatically tabs that have forms.

### Expected behaviour

Tabs are not reloaded.

### Actual behaviour

Tabs are reloaded unexpectedly.

### Device name

Samsung Galaxy S9

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

89.0.10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19500)

**Comment by superbonaci** [comment]
It happens also here on GitHub replies.

**Comment by cadeyrn** [comment]
> Firefox Nightly
> 89.0.10

Does it reproduce with a current build? Firefox Nightly has the version numbrer 99.0a1, the current stable release is 97.1.0.

**Comment by superbonaci** [comment]
Of course it forces me to write everything to a paper to fill the form at once or use apps in split screen, but sometimes just accessing the split screen menu also triggers the reload thing.

**Comment by superbonaci** [comment]
I'll check with certain websites and try to make a video, keep the bug open.

**Comment by cadeyrn** [comment]
> Firefox Nightly
> 89.0.10

Does it reproduce with a current build? Firefox Nightly has the version number 99.0a1, the current stable release is 97.1.0.

By the way, you can edit your comments.

**Comment by Disil** [comment]
I can confirmed this happened in Firefox 98 beta, although it does not happen everytime. We still can't get the tab behaviour to be like Fennec (before Fenix).

**Comment by superbonaci** [comment]
It happens with Galaxy S10 as well, wait for the video please.

**Comment by code-to-joy** [comment]
Can confirm, happens every single time I switch from FF to my password manager to get credentials.

**Comment by superbonaci** [comment]
Just tested latest Play Store Nightly 99.0a1 and find it much more difficult to happen, mainly happens if you switch from FF to YouTube app and browse some videos then switch back to FF and close some other tabs.

Probably this is related to some mobile memory management, of course I'm used to this never happening on the desktop, so I tried to do the same and got the issue with forms reloading. Some text boxes may retain the data and others not.

Wonder if this is an Android issue which is working as intended...

**Comment by superbonaci** [comment]
@code-to-joy which password manager, Lockwise?

**Comment by rgueldenpfennig** [comment]
I have the same problem with my Samsung Galaxy S9 (SM-G960F), Android 10 with latest stock provider patches.
I am using Firefox 97.1.0 (Build #2015860771) and Keepass2 Android as my password manager.

The reload happens almost all the time when switching single tabs or minimizing and maximizing the Firefox app just as described in this issue here: https://github.com/mozilla-mobile/fenix/issues/12731

**Comment by Drawing12** [comment]
hi, if you want to draw for Youtube video monetization then you can read my all these articles. This is very helpful for drawing TY channel monetization. 
1.	https://3dvkarts.net/how-to-draw-easy-bat-drawing/
2.	https://3dvkarts.net/pumpkin-drawing/
3.https://3dvkarts.net/ghost-drawing-step-by-step/
this is article for creating YT videos on drawing. This is very easy drawing and you can learn how to draw these drawing step by step. AFter that you can draw and make video uplaod YT channel and get monetization and earn with YT. Thank. I need just Pray

**Comment by code-to-joy** [comment]
> @code-to-joy which password manager, Lockwise?

BitWarden. The point is that I switch app from FF to any other app for like three seconds, and when I get back the tab reloads. Happens even with a restarted phone and no other tabs open.

**Comment by superbonaci** [comment]
Would be interesting to test this on a Pixel device.

**Comment by dylantrevor87** [comment]
please don't close the bug

**Comment by csadilek** [comment]
We're working on all tab reload issues incl. this one as part of this meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1752594. Please follow along there.
