### ISSUE TITLE
Play store web page for any app not showing Open In Play Store App button

### ISSUE THREAD

**Issue by sunilk9211** [mozilla-mobile/fenix#23778]
### Steps to reproduce

Open any play store app link.
for example this one - https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android

**In Other browsers**, we get a button at bottom center of screen that says "Open In Play Store App".
![Screenshot from 2022-02-16 18-44-11](https://user-images.githubusercontent.com/36289013/154272167-589c0e1f-a0bf-414c-a838-f9843c014ec1.png)

That makes it a little difficult for a user to install any Android app through its play store web address.

https://user-images.githubusercontent.com/36289013/154269451-f914b8a1-d056-46b0-8547-9f647c8a22ea.mp4

### Expected behaviour

It should show the button, clicking on which Play store app opens.

### Actual behaviour

It doesn't show "Open In Play Store App"

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

98.0

### Additional information

We can see that button even in normal WebViews.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19525)

**Comment by Mugurell** [comment]
Fenix has a similar "Open in app" feature shown in menu that works with any app, not just with the Playstore.
When the currently viewed page can be opened in an external app there is a blue indicator signaling this to the user.

https://user-images.githubusercontent.com/11428869/154277905-dd5d008d-3882-43fd-b699-c98c78d7c462.mp4

**Comment by SoftVision-LorandJanos** [comment]
Hi @sunilk9211! Thanks for your report!
I could reproduce your issue.
Also checked on Chrome where the behavior is as expected.
Tested on the latest Nightly 99.0a1 (2022-02-16).
Device used: Oppo Reno 6 (Android 11).

**Comment by czlucius** [comment]
Samsung Internet also does not seem to have the button.
![Screenshot_20220222-234841_Samsung Internet](https://user-images.githubusercontent.com/58442255/155168391-009c9308-16eb-4ebd-8a16-d7375098f45b.jpg)

**Comment by MoustafaElsaghier** [comment]
is android no longer have this `open in app` button?

**Comment by SoftVision-LorandJanos** [comment]
I don't see it in Chrome anymore either so it might no longer be available. However as Mugurell mentioned above, Fenix has this feature accessible through 3 dot menu>"Open in app" (If the page can be opened with an available external app).

**Comment by MoustafaElsaghier** [comment]
I think it's no longer available as Facebook, Instagram, Twitter and LinkedIn not having this feature anymore and LinkedIn now have popup animation with button to open in App
