### ISSUE TITLE
FNX3-16275 ⁃ Add "Share Tabs" functionality to share icon in history fragment

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2377]
### User Story:
As a user, I want to be able to share multiple history entries when multi selecting.

### Acceptance Criteria
I can tap on the history fragment's share intent to share multiple selected history entries. 

[Design found here](https://mozilla.invisionapp.com/d/main#/console/16853870/350827898/inspect)

**Comment by sv-ohorvath** [comment]
Verified this on the 5/22 build.
devices: Galaxy Note 8 (Android 9), P9 Lite (Android 6.0)
