### ISSUE TITLE
[Bug]: Unable to download images from hitomi.la

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#23798]
### Steps to reproduce

1. Navigate to https://hitomi.la/reader/2139470.html#3
2. Long press on an image.
3. Select "Save image" from "Context" menu.
4. Observe behavior.

### Expected behaviour

Image is downloaded and available on the device.

### Actual behaviour

Download fails.

### Device name

Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

### Android version

Android 9, Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 99.0a1 (🦎 99.0a1-20220216094238)

### Device logs

![ConsoleLog](https://user-images.githubusercontent.com/12184325/154501894-ca8b7e98-1b48-40e9-b69f-4dec7af9e429.png)

### Additional information

1. The issue is not reproducible on Chrome.
2. The issue is reproducible on Firefox Release.
3. This was reported here: https://github.com/webcompat/web-bugs/issues/99742
4. This might be dependent on https://bugzilla.mozilla.org/show_bug.cgi?id=1690037 
5. Screenshot attached.

![image](https://user-images.githubusercontent.com/12184325/154500281-cf120a88-2e3f-4918-8a10-6ec1811db282.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19538)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the is reproducible on Nightly 2022-02-17. An error message is displayed when trying to download an image.
### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)
