### ISSUE TITLE
Rework history multi select and bookmark multi select to use generic solution

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2379]
Currently our history multi selection uses a subset of code from bookmark multi select. It'd be great if we had a generic solution that both could inherit from. Doing so would drastically reduce code duplication.

**Comment by sblatz** [comment]
@NotWoods was working on a related issue. Does https://github.com/mozilla-mobile/fenix/pull/3707 cover this?

**Comment by NotWoods** [comment]
It doesn't but was meant to build towards it. Once it's merged I can write some generic selection code.
