### ISSUE TITLE
[Bug]: search select blocks new tab features

### ISSUE THREAD

**Issue by clientenq** [mozilla-mobile/fenix#23796]
### Steps to reproduce

1 Open new tab
2 cursor automatically starts in search field
3 causes automatc dropdown of search engine options
4 blocks view and select of other options in new tab
5 after new tab user has to unselect cursor focus from search engine field to be able to view or use other new tab features.

### Expected behaviour

1 open new tab
2 no automatic focus on search engine field

Or
1 open new tab
2 automatic focus on search engine field
3 no automatic dropdown of search engine selection box

### Actual behaviour

Opening new tab automatically focuses and 'domino causes' blocking of view and use of other features in new tab.
User has to do multiple actions when not wanting to select search engine or not wanting to search.

### Android version

10

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

**Comment by kbrosnan** [comment]
Sounds like you have  `Show search engines` enabled. This sounds like expected behavior if you have that enabled. The default is disabled.

* 3 dot menu
* Settings
* Search
* Toggle `Show search engines`
