### ISSUE TITLE
Enable devs to run perf tests against their changes

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#23792]
Our main perf benchmarks (start up) can be run locally but can't be run in CI. This makes it more challenging for developers to get perf results at all (by having to figure out how to run it locally) and makes perf results less accurate (because they have to choose the right device, configure it correctly, not interrupt the test, etc.).

This ticket is to track the (likely) perf test team's work to implement this functionality.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19534)

**Comment by MarcLeclair** [comment]
We'll keep following up on this one to make sure it gets added to CI.
