### ISSUE TITLE
FNX3-16277 ⁃ [UX] History

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#238]
* Record history
* Recall history in awesomebar
* Autocompletion

Currently not available: 

* List of history

**Prototype: (part of library)**
https://mozilla.invisionapp.com/share/7KQ5AVZ2A5D

**Fenix Flows (WIP)**
https://docs.google.com/drawings/d/11Kj7OAvit6bE6QQt_ven0xnHGhmwu4Jc_N_oazdryAo/edit

**Comment by bbinto** [comment]
@lime124 added those two myself - would you mind checking with the the team about t-shirt sizing, progress, mocks etc.

Since this has to go into milestone 2 for eng, we should have this set as a P1?

**Comment by lime124** [comment]
@colintheshots can you (or another dev) let us know if you have enough to get started? Thanks!

**Comment by ekager** [comment]
Yes I believe we have enough to get started on History!

**Comment by lime124** [comment]
closing this issue so we can wrap up our sprint. @ekager can you file follow up [ux] issues for the team to address follow up stuff? thanks!
