### ISSUE TITLE
FNX3-16278 ⁃ Onboarding - Sign in for Sync

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#2380]
As a user with a FxA, I want to sign in to sync my data. 

## Dependencies
* UX  sign in module in InVision
https://mozilla.invisionapp.com/d/#/projects/prototypes/17334494
![](https://user-images.githubusercontent.com/20115914/57798670-e5cc5100-7712-11e9-96e7-c37c31e4806e.png)

### Acceptance Criteria
* I can access the sign in page
* I can view the sync cta
i can  dismiss the cta

**Comment by vesta0** [comment]
Dup of #2395
