### ISSUE TITLE
[Bug]: Unable to hide bottom bar about push notifications

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#23801]
### Steps to reproduce

Go to site [https://www.australianfrequentflyer.com.au/community/forums/open-discussion.77/](https://www.australianfrequentflyer.com.au/community/forums/open-discussion.77/) or any other subforum, and try to hide bottom message about push notificacions. Clicking on `Never ask again` does't work as intended.

### Expected behaviour

Hide the nagging bar.

### Actual behaviour

Does nothing.

### Device name

Samsung Galaxy S10

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19540)

**Comment by kbrosnan** [comment]
This looks like a website design bug. It is possible that the layer that holds the Google ads is still present just transparent. Looks like getting the push notification message requires an account.

**Comment by superbonaci** [comment]
Yes, I am logged in with my account.

**Comment by superbonaci** [comment]
Found how to "fix" it:

1. Click on `enable push notifications` just after reloading the page, don't wait until further messages appear.
![](https://i.imgur.com/UloDnKr.png)

2. Forbid Firefox itself from sending notifications although the website wants to.
![](https://i.imgur.com/fGSIu6P.png)

3. This is the result.
![](https://i.imgur.com/w217yy0.png)

4. Now it must show that are blocked.
![](https://i.imgur.com/BvUg1Rs.png)

**Comment by delia-pop** [comment]
Hi, @superbonaci. I will close this ticket since you managed to find the workaround, but feel free to reopen if that no longer works for you. Thank you.

**Comment by superbonaci** [comment]
Thanks a lot!!!
