### ISSUE TITLE
[Bug]: Cant add top site due "Top site limit reached"

### ISSUE THREAD

**Issue by santo998** [mozilla-mobile/fenix#23812]
### Steps to reproduce

1. Browse to some website
2. Three dots menu
3. Add to top sites

### Expected behaviour

The site is added to the top sites

### Actual behaviour

I get the following error:
"Top site limit reached
To add a new top site, remove one.
Touch and hold the site and select remove."

### Device name

Samsung J7 Prime

### Android version

Android 8.1

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

I had 7 top sites, and got the error.
Then i deleted one and tried again to add another one, with no success.
Finally, i reinstalled the app and tried again without any top site defined, and got the same error.

In the top sites section (shortcuts section of the homepage) i only see recent visited sites (16 of them) and if i delete one, then other old site replace the last one of the list.
I think one possible cause would be that Firefox is counting "shortcuts" to recent visited sites as top sites.
But like i said, right now i have 0 top sites (0 pinned sites in my homepage).

**Comment by bonyjose** [comment]
Reproduced same issue in Android 12 device, in Firefox 99.0a1. I only have one top site pinned in Firefox nightly, when I click on adding a new top site, unable to do so and is mshown with error message " top site limit is reached".

**Comment by plwt** [comment]
I am seeing the same - Nightly 99.0a1 on Android 11 and have a user seeing the same in SUMO in 98.0a1 on Android 11.

**Comment by EekaDroid** [comment]
Same issue, 99.0a1, LOS 18.1 (Android 11). Top sites is just unusable
