### ISSUE TITLE
Search result page not always included in Recently visited search group

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#23814]
### Steps to reproduce

Similar to https://github.com/mozilla-mobile/fenix/issues/21852.

**On a fresh install of Fenix.**
1. Search for something with any search engine
2. From the search results, open two results in new tabs
3. Open the tabs and visit the websites.
4. Open the tab drawer and close all tabs.
5. Return to homescreen, check the search group in the Recently visited section.

### Expected behaviour

All 3 tabs are included in the search group.

### Actual behaviour

The search results page isn't always included in the search group (100% reproducible but only on a fresh install)
The search group was correctly showing the initial search results page in the "Jump back in" section and in the tabs tray.

### Device name

Pixel 2 

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

![1](https://user-images.githubusercontent.com/4037709/154684096-c67994fe-431d-42ed-95fe-109bdf212a4a.png)
![2](https://user-images.githubusercontent.com/4037709/154684097-3445700a-d079-4cd4-b9dd-1b9ed4d775d4.png)
![3](https://user-images.githubusercontent.com/4037709/154684094-b8696b7b-9984-4220-9945-cdae4c90561f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19546)

**Comment by sv-ohorvath** [comment]
Still reproducing, see https://github.com/mozilla-mobile/fenix/issues/23818

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807706

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
