### ISSUE TITLE
FNX3-16279 ⁃ need a notification when getusermedia is consuming the camera and/or microphone

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2381]
### Why/User Benefit/User Problem
Users know when Fenix is consuming the camera and/or microphone

### What/Requirements
The user gets a notification when a page is consuming camera individually, microphone individually or camera with the microphone. Tapping on the notification should take me to the tab that is using the camera and/or microphone. 

### Acceptance Criteria (how do I know when I’m done?)
When visiting https://appr.tc/  https://test.webrtc.org/ https://www.floodgap.com/software/tenfourfox/gum_test.html there is a notification if the permission to the camera/mic is granted

**Comment by cpeterso** [comment]
The app doesn't know when the page starts or stops using the microphone, so GV will need to some new delegates. The app should be responsible for notification UI.

GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1549633

**Comment by kbrosnan** [comment]
Example notifications from Fennec. 

![Screenshot_20190509-115526](https://user-images.githubusercontent.com/250273/57479558-8a9de880-7252-11e9-8897-66ea12bd43b2.png)
![Screenshot_20190509-115544](https://user-images.githubusercontent.com/250273/57479562-8d004280-7252-11e9-9c79-01661dea13f8.png)
![Screenshot_20190509-115604](https://user-images.githubusercontent.com/250273/57479568-8eca0600-7252-11e9-948b-ce023fd13eab.png)

**Comment by lime124** [comment]
@AmyYLee to provide icons if we need them for the notification tray.

**Comment by AmyYLee** [comment]
Here are the icons for camera and mic

[icons.zip](https://github.com/mozilla-mobile/fenix/files/3164062/icons.zip)

**Comment by cpeterso** [comment]
The GV API to provide camera/microphone notifications (GV bug 1549633) is in progress. In the meantime, Fenix engineers can write the preliminary UI code to show the new camera and microphone icons. After the GV API is delivered, Fenix can connect the UI code to the new API.

**Comment by pocmo** [comment]
@kbrosnan This is available in Reference Browser Nightly builds now (on GV 69). Maybe we can already QA it there (since all the code for this feature is coming from AC) and look for issues. Once the GV patches are uplifted to GV 68 I will take care of landing this in Fenix.

**Comment by cpeterso** [comment]
The GV fix has been uplifted to GV 68 Beta and should be available in today's GV 68.0.20190603093516 beta build:

https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview-beta-armeabi-v7a/68.0.20190603093516/

**Comment by pocmo** [comment]
I just enabled this in Fenix. I'll add the QA label now.

**Comment by softvision-miralobontiu** [comment]
Verified with https://mozilla.github.io/webrtc-landing/gum_test.html that notifications that camera and/or microphone are on are displayed.
Tested with the latest build 1.0.1923 (#11570615), with Nexus 5 (Android 6.0.1), Google Pixel (Android 9).
