### ISSUE TITLE
Intermittent UI test failure - SearchTest#searchGroupGeneratedInTheSameTabTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#23818]
### Firebase Test Run:
deleteItemsFromSearchGroupsHistoryTest
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5608941059826265465/executions/bs.18e7efdd522f0f0c/test-cases

searchGroupShowsInRecentlyVisitedTest
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5608941059826265465/executions/bs.d51893b1bcad9fd/test-cases
### Build: 
debug

After multiple runs on Firebase, I encountered a few problems with the search groups feature that affect the tests. They will be disabled until the bugs are fixed.
Failures caused by :
https://github.com/mozilla-mobile/fenix/issues/23815
https://github.com/mozilla-mobile/fenix/issues/23814

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19550)

**Comment by sv-ohorvath** [comment]
I'll give it a run to see how they presently behave.

**Comment by sv-ohorvath** [comment]
Will remain disabled until the tabs tray refactoring is done and I'll give them another try.

**Comment by sv-ohorvath** [comment]
SearchTest deleteItemsFromSearchGroupsHistoryTest and searchGroupShowsInRecentlyVisitedTest are now re-enabled. searchGroupGeneratedInTheSameTabTest will remain disabled because of https://github.com/mozilla-mobile/fenix/issues/23814

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807294

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
