### ISSUE TITLE
Recently Visited Homepage Telemetry

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#23821]
https://mozilla-hub.atlassian.net/browse/FNXV2-19135

- How often do people open a search group?

- Do people who interact with search groups retain better?

- What % of core actives interact with search groups? 

- How often do people open a history highlight?

- Do people who interact with history highlights retain better?

- What % of core actives interact with history highlights?

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on latest Nightly 99.0a1 (2022-03-02).
Device used: Samsung S10E (Android 10).
The logs can be find [here](https://debug-ping-preview.firebaseapp.com/pings/test-00001).
