### ISSUE TITLE
[Bug]: Some Fullscreen YouTube videos shows gap (affecting 97.2.0)

### ISSUE THREAD

**Issue by acalarch** [mozilla-mobile/fenix#23823]
### Steps to reproduce

1. Go to a YouTube video like: https://www.youtube.com/watch?v=PfF_JgNvJfQ
2. Go full-screen - landscaped

Note: This 'bug' does not appear with all YouTube videos. I believe only certain aspect ratios.

### Expected behaviour

The video takes up the entire screen

### Actual behaviour

The top of the video does not align with the top of the phone screen. The video is dropped ~10% from the top of the screen, and is clipped. 

The left margin is also pushed ~5% from the side of the phone screen (I think to account for camera) but is clipped.

### Device name

Samsung Galaxy S21

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

97.2.0

### Additional information

![Screenshot_20220218-150723_Firefox](https://user-images.githubusercontent.com/21689928/154754493-504588c1-2cb1-4a00-8d70-8eea12fdb539.jpg)

I use this CSS 'hack' in uBlock Origin as a workaround for this problem:
`m.youtube.com##video:style(max-height: 100% !important; position: fixed !important; top: 0px !important)`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19558)

**Comment by acalarch** [comment]
Also impacts Firefox nightly 99.0a1

**Comment by ComfortableEast** [comment]
> Duplicate of #8252
> 
> According to investigation this is a Youtube bug.

I don't think this is a Youtube bug, I have tried opening m.youtube.com on other browsers such as chrome, kiwi, and samsung internet browser, none have this problem with the exact same videos.
