### ISSUE TITLE
Lock icon not working, site information not opening

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#23835]
### Steps to reproduce

In the browser view, left from URL, tapping the lock icon

### Expected behaviour

Opening information panel

https://user-images.githubusercontent.com/76437842/154811992-59ffa7e5-cef1-4c51-a08b-a3c0aa5af31b.mp4

### Actual behaviour

Sometimes, nothing happens.

### Device name

Samsung Galaxy OneUI 3.1

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build #2015864235), c52880ecb+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19566)

**Comment by LaviniaL99** [comment]
Hello @marcel263 

Thanks for your report! 
I retested the above flow on the latest Nightly 99.0a1(Build #2015864619) and i wasn't able to reproduce the issue.

**Device used:**
- Samsung S10E -> Android 10

**Comment by marcel263** [comment]
still relevant on slow connections / DNS resolver

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807557

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
