### ISSUE TITLE
[Bug]: Texts in github commits are not displayed correctly

### ISSUE THREAD

**Issue by CaFI0** [mozilla-mobile/fenix#23831]
### Steps to reproduce

1. Open the page where the commits of any repository are located on github e.g. https://github.com/mozilla-mobile/fenix/commits/main 
2. Move around the page 

### Expected behaviour

That they will be displayed well and without any problem

### Actual behaviour

The vast majority of the text of the commits is not displayed correctly or you need to zoom in on the page so that the text can be seen
![20220217_214129](https://user-images.githubusercontent.com/77524578/154786985-95c8e341-291d-4096-b24d-c5df4ab2bb24.png)

### Device name

Samsung J610G

### Android version

Android 10.0

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build #2015864137)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19563)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-02-21, but was unable to reproduce it.
### Devices used:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 6 (Android 12)

**Comment by CaFI0** [comment]
Update: this problem has not been presented anymore, it just disappeared and now the github commits appear correctly.  The version I'm on now is 100.0a1 (Build #2015871241)
