### ISSUE TITLE
Add an option to remove the "Entering full screen mode" nag

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla-mobile/fenix#23833]
### What is the user problem or growth opportunity you want to see solved?
Every time a full screen video is opened, a nag message is displayed: "Entering full screen mode". Therefore, the process of opening a full screen involves 2 steps:

1) Tap whatever button opens the full screen;
2) Swipe the nag away or wait for it to stop obstructing the view.

It is not at all useful or provide any security benefits to display the nag 100 times for 100 videos going full screen on YouTube, so advanced users should be given an opportunity to opt-out of this behavior.

In Firefox for desktop, one can disable the nag through `full-screen-api.warning.timeout` preference in `about:config`. The mobile versions lack this option -- per #23704, about:config is unsupported, so an option would be needed to remove the nag.

**Comment by kbrosnan** [comment]
This is a security feature. A primary setting for disabling this will not be accepted.
