### ISSUE TITLE
[Bug]: Bookmarks open in non-private tabs (beta regression)

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#23837]
### Steps to reproduce

From: https://www.reddit.com/r/firefox/comments/swia4c/android_firefox_beta_problem_bookmarks_open_in/

1. Open new tab
2. Tap mask icon to enter private browsing
3. open bookmarks UI
4. open any bookmark

### Expected behaviour

Bookmark is opened in a private tab.

### Actual behaviour

Bookmark is opened in a non-private, background tab.

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

98.0.0-beta.3

**Comment by czlucius** [comment]
https://github.com/mozilla-mobile/fenix/issues/23746

**Comment by SoftVision-LorandJanos** [comment]
I could reproduce this issue on the:
- Nightly 99.0a1 from 3 days ago (2022-02-21).
- latest Beta (98.0.0-beta3).
However it looks to be fixed on the latest Nightly 99.0a1 (2022-02-24).
Device used: Oppo Reno 6 (Android 11).
