### ISSUE TITLE
FNX3-16281 ⁃ [Scrim] Update scrim colour

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2384]
Update scrim on-light to Dark Grey 30 (#42414D) ⇒ Dark Grey 90 (#15141A) @ 96%

See reference below

![](https://user-images.githubusercontent.com/5992746/57490201-7b389280-7286-11e9-994b-af6d147afca7.png)

This applies to collections modal, share sheets, all on-light modal backgrounds.

**Comment by sv-ohorvath** [comment]
Fixed on 5/20.
