### ISSUE TITLE
wrong video scale

### ISSUE THREAD

**Issue by NektoNektovich** [mozilla-mobile/fenix#23847]
### Steps to reproduce

any video online

### Expected behaviour

the video should be the full height or width of the window

### Actual behaviour

wrong video scale

### Device name

texet tm 4510

### Android version

Android 6.0

### Firefox release type

Firefox

### Firefox version

97.1.1

### Additional information

![Screenshot_20211113-212532](https://user-images.githubusercontent.com/53621368/154866146-3630da4b-29e2-4cd1-b030-805b7b087519.jpg)

**Comment by Mugurell** [comment]
Videos will have a fixed size. 
Us stretching or withdrawing the video to make it exactly fit the window would change it's aspect ratio.
The other alternative used by the native YouTube client will have the video fit the screen but cut the parts that do not fit resulting in loosing parts of the video.

Testing the video shown in your screenshot I see we have the same behavior as Chrome and correctly frame the video to not change it's aspect ratio, not cut parts of it and shown it in the middle of the screen.

https://user-images.githubusercontent.com/11428869/154950331-a9d3bdac-713d-4404-a938-ee435f4b553f.mp4

**Comment by NektoNektovich** [comment]
> Videos will have a fixed size. Us stretching or withdrawing the video to make it exactly fit the window would change it's aspect ratio. The other alternative used by the native YouTube client will have the video fit the screen but cut the parts that do not fit resulting in loosing parts of the video.
> 
> Testing the video shown in your screenshot I see we have the same behavior as Chrome and correctly frame the video to not change it's aspect ratio, not cut parts of it and shown it in the middle of the screen.
> VideoCorrectlyFramed.mp4

you must be joking?!?! I showed that the video error is only on android 6.0, and on other versions of android the video shows normally with the window scale! Yes, and the version of firefox 68.11 shows the video in aedroid 6.0 correctly !!! fix it!!!!!

**Comment by NektoNektovich** [comment]
> Видео будет иметь фиксированный размер. Если мы растянем или удалим видео, чтобы оно точно соответствовало окну, это изменит его соотношение сторон. Другая альтернатива, используемая родным клиентом YouTube, будет заключаться в том, что видео будет соответствовать экрану, но вырезать части, которые не подходят, что приведет к потере частей видео.
> 
> Тестируя видео, показанное на вашем скриншоте, я вижу, что мы ведем себя так же, как Chrome, и правильно кадрируем видео, чтобы не изменять его соотношение сторон, не вырезать его части и не показывать в середине экрана.
> VideoCorrectlyFramed.mp4

in your opinion, the size of the video in my screenshot is equal to the physical 240p?  blind?!

**Comment by kbrosnan** [comment]
Looks like bz-1731980

**Comment by jamienicol** [comment]
@NektoNektovich could you please go to about:support, click on "copy text to clipboard" and attach the text to this bug? Thanks.

**Comment by NektoNektovich** [comment]
> @NektoNektovich could you please go to about:support, click on "copy text to clipboard" and attach the text to this bug? Thanks.

Application Basics
------------------

Name: Fennec
Version: 97.0
Build ID: 20220214023640
Distribution ID:
User Agent: Mozilla/5.0 (Android 6.0; Mobile; rv:97.0) Gecko/97.0 Firefox/97.0
OS: Linux 23 #2 SMP PREEMPT Mon Feb 13 21:15:15 CST 2017
Multiprocess Windows: 0/0
Fission Windows: 0/0 Disabled by default
Remote Processes: 2
Google Location Service Key: Missing
Google Safebrowsing Key: Missing
Mozilla Location Service Key: Missing
Safe Mode: false

Fennec Features
---------------

Remote Processes
----------------

Type: Web Content
Count: 2 / 2

Add-ons
-------

Name: Mozilla Android Components - Ads Telemetry
Type: extension
Version: 97.0.11.0214040809
Enabled: true
ID: ads@mozac.org

Name: Mozilla Android Components - Browser Icons
Type: extension
Version: 97.0.11.0214040729
Enabled: true
ID: icons@mozac.org

Name: Mozilla Android Components - Firefox Accounts WebChannel
Type: extension
Version: 97.0.11.0214040734
Enabled: true
ID: fxa@mozac.org

Name: Mozilla Android Components - ReaderView
Type: extension
Version: 97.0.11.0214040738
Enabled: true
ID: readerview@mozac.org

Name: Mozilla Android Components - Search Telemetry
Type: extension
Version: 97.0.11.0214040809
Enabled: true
ID: cookies@mozac.org

Name: Mozilla Android Components - Web Compatibility Interventions
Type: extension
Version: 29.1.0
Enabled: true
ID: webcompat@mozilla.org

Name: Translate Web Pages
Type: extension
Version: 9.4.2
Enabled: true
ID: {036a55b4-5e72-4d05-a06c-cba2dfcc134a}

Name: uBlock Origin
Type: extension
Version: 1.41.6
Enabled: true
ID: uBlock0@raymondhill.net

Name: YouTube High Definition
Type: extension
Version: 85.0.0
Enabled: false
ID: {7b1bf0b6-a1b9-42b0-b75d-252036438bdc}

Graphics
--------

Features
Compositing: WebRender
Asynchronous Pan/Zoom: touch input enabled; autoscroll enabled; smooth pinch-zoom enabled
WebGL 1 Driver WSI Info: EGL_VENDOR: ARM EGL_VERSION: 1.4 Midgard-"r7p0-02rel0" EGL_EXTENSIONS: EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_framebuffer_target EGL_ANDROID_blob_cache EGL_KHR_partial_update EGL_KHR_config_attribs EGL_KHR_image EGL_KHR_image_base EGL_KHR_fence_sync EGL_KHR_wait_sync EGL_KHR_gl_colorspace EGL_KHR_get_all_proc_addresses EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_renderbuffer_image EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_KHR_gl_texture_cubemap_image EGL_EXT_create_context_robustness EGL_KHR_cl_event2 IsWebglOutOfProcessEnabled: 0
WebGL 1 Driver Renderer: ARM -- Mali-T720
WebGL 1 Driver Version: OpenGL ES 3.1 v1.r7p0-02rel0.4ea33e6671ff828e33c99c982634cd65
WebGL 1 Driver Extensions: GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image
WebGL 1 Extensions: ANGLE_instanced_arrays EXT_blend_minmax EXT_sRGB MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context
WebGL 2 Driver WSI Info: EGL_VENDOR: ARM EGL_VERSION: 1.4 Midgard-"r7p0-02rel0" EGL_EXTENSIONS: EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_framebuffer_target EGL_ANDROID_blob_cache EGL_KHR_partial_update EGL_KHR_config_attribs EGL_KHR_image EGL_KHR_image_base EGL_KHR_fence_sync EGL_KHR_wait_sync EGL_KHR_gl_colorspace EGL_KHR_get_all_proc_addresses EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_renderbuffer_image EGL_KHR_create_context EGL_KHR_surfaceless_context EGL_KHR_gl_texture_cubemap_image EGL_EXT_create_context_robustness EGL_KHR_cl_event2 IsWebglOutOfProcessEnabled: 0
WebGL 2 Driver Renderer: ARM -- Mali-T720
WebGL 2 Driver Version: OpenGL ES 3.1 v1.r7p0-02rel0.4ea33e6671ff828e33c99c982634cd65
WebGL 2 Driver Extensions: GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image
WebGL 2 Extensions: MOZ_debug WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context
Target Frame Rate: 57
GPU #1
Active: Yes
Description: Model: TM-4510, Product: TM-4510, Manufacturer: Texet, Hardware: mt6735, OpenGL: ARM -- Mali-T720 -- OpenGL ES 3.1 v1.r7p0-02rel0.4ea33e6671ff828e33c99c982634cd65
Vendor ID: ARM
Device ID: Mali-T720
Driver Version: OpenGL ES 3.1 v1.r7p0-02rel0.4ea33e6671ff828e33c99c982634cd65
RAM: 0

Diagnostics
AzureCanvasBackend: skia
AzureContentBackend: skia
AzureFallbackCanvasBackend: skia
CMSOutputProfile: Empty profile data
Display0: 480x854
DisplayCount: 1
Decision Log
HW_COMPOSITING:
available by default
force_enabled by user: Force-enabled by pref
OPENGL_COMPOSITING:
available by default
force_enabled by user: Force-enabled by pref
WEBRENDER:
available by default
WEBRENDER_QUALIFIED:
available by default
WEBRENDER_COMPOSITOR:
disabled by default: Disabled by default
WEBRENDER_PARTIAL:
available by default
blocked by env: Partial present blocked
WEBRENDER_SHADER_CACHE:
available by default
WEBRENDER_OPTIMIZED_SHADERS:
available by default
blocklisted by env: Blocklisted by gfxInfo
WEBRENDER_ANGLE:
available by default
unavailable by env: OS not supported
WEBRENDER_DCOMP_PRESENT:
available by default
disabled by user: User disabled via pref
unavailable by env: Requires Windows 10 or later
unavailable by runtime: Requires ANGLE
WEBRENDER_SOFTWARE:
available by default
WEBGPU:
disabled by default: Disabled by default
blocked by runtime: WebGPU can only be enabled in nightly




Media
-----

Audio Backend: opensl
Max Channels: 2
Preferred Sample Rate: 44100
Roundtrip latency (standard deviation): ...
Output Devices
Name: Group
Default audio output device:
Input Devices
Name: Group
Default audio input device:

Enumerate database

Environment Variables
---------------------

Important Modified Preferences
------------------------------

browser.cache.disk_cache_ssl: false
browser.cache.disk.enable: false
browser.cache.disk.preload_chunk_count: 0
browser.cache.disk.smart_size.enabled: false
browser.cache.offline.enable: false
dom.caches.enabled: false
extensions.lastAppVersion: 97.0
idle.lastDailyNotification: 1645485505
media.gmp.storage.version.observed: 1
media.peerconnection.ice.default_address_only: true
media.peerconnection.ice.no_host: true
network.dns.disablePrefetch: true
network.http.speculative-parallel-limit: 0
network.predictor.enabled: false
network.prefetch-next: false
network.trr.blocklist_cleanup_done: true
privacy.purge_trackers.date_in_cookie_database: 0
privacy.purge_trackers.last_purge: 1645485507007
security.remote_settings.crlite_filters.checked: 1637180001
security.remote_settings.intermediates.checked: 1637180001
storage.vacuum.last.index: 0

Important Locked Preferences
----------------------------

fission.autostart.session: false

Accessibility
-------------

Activated: false
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.33
Version in use: 4.33

NSS
Expected minimum version: 3.74
Version in use: 3.74

NSSSMIME
Expected minimum version: 3.74
Version in use: 3.74

NSSSSL
Expected minimum version: 3.74
Version in use: 3.74

NSSUTIL
Expected minimum version: 3.74
Version in use: 3.74

Startup Cache
-------------

Disk Cache Path: /data/user/0/org.mozilla.fennec_fdroid/files/mozilla/e22wqxmd.default/startupCache/startupCache.4.little
Ignore Disk Cache: false
Found Disk Cache on Init: true
Wrote to Disk Cache: false

Internationalization & Localization
-----------------------------------

Application Settings
Requested Locales: ["ru"]
Available Locales: ["en-US"]
App Locales: ["en-US"]
Regional Preferences: ["en-US"]
Default Locale: "en-US"
Operating System
System Locales: ["ru"]
Regional Preferences: ["ru"]

Remote Debugging (Chromium Protocol)
------------------------------------

Accepting Connections: false
URL:

**Comment by NektoNektovich** [comment]
![Screenshot_20220228-021413](https://user-images.githubusercontent.com/53621368/155904226-785fc50f-c2e0-4886-a496-f265544c530b.png)
