### ISSUE TITLE
Credit cards: hide keyboard when selecting month or year

### ISSUE THREAD

**Issue by sunilk9211** [mozilla-mobile/fenix#23841]
### Steps to reproduce

https://user-images.githubusercontent.com/36289013/154830205-64873b24-9f4e-4b92-981a-694b839f99a8.mp4

### Expected behaviour

Keyboard should be hidden when selecting Expiry month or year.

### Actual behaviour

It's visible.

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19569)

**Comment by amocirean** [comment]
Hello @sunilk9211, thank you for submitting the issue.
I was able to reproduce the issue on the latest RC & Nightly.

Tested on:

- Huawei P40 Lite (Android 10)
- Xiaomi Mi 11 Lite (Android 11)
