### ISSUE TITLE
[Bug]: Tab group label doesn't change when google search text is changed

### ISSUE THREAD

**Issue by iamiceparticle** [mozilla-mobile/fenix#23842]
### Steps to reproduce

1. Enable search groups in tab setting.
2. Open a tab search for any text.
3. Open any link from the search result.
4. Now go back to the Google search page.
5. Search for another text.
6. Tab group label remains unchanged.

### Expected behaviour

Tab group label should change.

### Actual behaviour

Tab group label remains unchanged.
![Screenshot_20220220-122823_Firefox Nightly](https://user-images.githubusercontent.com/76210878/154832506-02ef3f8c-6f38-4947-bbb1-f33ec651fae9.jpg)

### Device name

Samsung A71

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19570)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Preview Nightly 2022-02-21.

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android)
