### ISSUE TITLE
[Bug]: Firefox Android all tabs lost

### ISSUE THREAD

**Issue by Opor97** [mozilla-mobile/fenix#23846]
### Steps to reproduce

Now for the second time in 1 Month. You tab out of your Firefox (Android) with 90 open tabs, come back in and... the tab count is on 0 and stays on 0. No tabs reopen no session is restored. 

This happened to me now the second time this month. Tabs are set to only close manually ofc.
And Firefox did NOT crash I just tabbed out. 
Also I dont have any application killing apps installed. 

Most funny thing is: In the recently closed tabs category only the manually closed tabs are listed not the automatically magically closed ones.

### Expected behaviour

The tabs should not close on their own if set to only manually close.  And if they do they should either reopen themselves like on the PC or tgey should at least show up in the recently closed tabs chronic. 

### Actual behaviour

The tabs are gone without a trace. 

### Device name

Honor 8x

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

97.2.0

### Device logs

There was no crash from either Firefox or my device.
Just tabbed out to WhatsApp for 8 seconds and when tabbing back in the tabs were gone. 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19573)

**Comment by amedyne** [comment]
@Opor97 Thank you for reporting this. What setting do you have selected for "Close Tabs" (goto Settings-> Tabs -> Close Tabs) ?

**Comment by Opor97** [comment]
"Tabs are set to only close manually ofc."
this as mentioned above.
And displayed as list but that shouldn't matter

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox RC 98.1.0 by having 100 tabs opened and periodically restarting Firefox, but was unable to reproduce it.
### Device used:
- Google Pixel 6 (Android 12)

**Comment by Opor97** [comment]
the bug mentioned above just happened again with ca. 150 tabs. That is horrid.
