### ISSUE TITLE
Incorrect tab number appears for a moment on swipe

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#23860]
### Steps to reproduce

1. Have at least 2 tabs open (Ideally at least 4).
2. Swipe between the tabs.
3. Observe the tab counter.

### Expected behaviour

The tab counter shows the correct tab number.

### Actual behaviour

The number shows 1 tab extra or 1 tab less for a moment.

### Device name

Oppo Reno 6

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

https://user-images.githubusercontent.com/48829350/154974505-9b820d07-ec12-4f25-a269-0b0c389dab84.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19579)

**Comment by Remu-rin** [comment]
Still relevant for 107 and 108 versions.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812859

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
