### ISSUE TITLE
[Bug]: Search suggestions don't show up on cold run

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#23864]
### Steps to reproduce

Scenario 1:
1. Clear app data.
2. Open the app, type something into the search bar, wait for search suggestions.
3. Dismiss the search bar by pressing the device back button (don't press search).
4. Type something again, wait for search suggestions.

Scenario 2:
1. Open a webpage.
2. Close the app
3. Restart the app.
4. Tap the URL bar, type something into the search bar, wait for search suggestions.
5. Dismiss the search bar by pressing the device back button  (don't press search) - the search bar should now be empty.
6. Type something again, wait for search suggestions.

### Expected behaviour

There should be some search suggestions displayed.

### Actual behaviour

The search suggestions list is empty.

### Device name

Pixel 2, Pixel 3, Oppo Reno 6

### Android version

9, 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1, 97.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19581)

**Comment by Alexandru2909** [comment]
While investigating this, I found out that in the described scenarios, the suggestion [`fetch`](https://github.com/mozilla-mobile/android-components/blob/f1661b79e676fba03446cb017cbc94b35c60179a/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt#L262) call [throws](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt#L59) `TimeoutException`. This also happens for timeout values larger than 2s.

**Comment by Alexandru2909** [comment]
I noticed that `TimeoutException` is thrown for the first few `AwesomeBar` searches on a cold boot. This also occurs on Sample Browser from AC, the only fix I could find was to increase the `READ_TIMEOUT_IN_MS` [from `SearchSuggestionProvider`](https://github.com/mozilla-mobile/android-components/blob/f1661b79e676fba03446cb017cbc94b35c60179a/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt#L248) to ~30s. I'm not sure that the Kotlin update caused this behavior.

**Comment by AndiAJ** [comment]
Managed to reproduce this matter with a slightly different STR

### Prerequisites
"Show search engines" should be enabled in the "Search" settings

### Steps to reproduce
1. Tap the toolbar
2. Select DuckDuckGo from the "Search engine" shortcut list
3. Set the toolbar text to "mozilla"
4. Check the awesome bar for suggestions

► Video

https://user-images.githubusercontent.com/51314259/174320602-8dc27939-1b6a-4cf4-a705-4909245f9c29.mp4

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813587

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
