### ISSUE TITLE
[Bug]: Status bar sticky on top of fullscreen video

### ISSUE THREAD

**Issue by lkebin** [mozilla-mobile/fenix#23878]
### Steps to reproduce

1. Open any YouTube.com video or Vimeo.com video
2. Enable fullscreen for playing video

### Expected behaviour

No dark or white bar (status bar) on the top of fullscreen

### Actual behaviour

By default, fullscreen video will display a dark or white bar on the top

![image](https://user-images.githubusercontent.com/1335935/155140155-1a093e5a-657d-4beb-b54f-e8cf0360bcb9.png)

When I touch the dark or white bar and swipe from top to bottom, the status bar info will display on it.
![image](https://user-images.githubusercontent.com/1335935/155140053-6738262a-c186-4da1-a82d-17284c94d5d3.png)

### Device name

HUAWEI MATE 40 PRO

### Android version

HarmonyOS 2.0.0

### Firefox release type

Firefox

### Firefox version

97.2.0 (Build #2015863827)

### Additional information

I tried other browser on the same site video, they are working as expected. such as Opera and HUAWEI Browser (built-in)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19593)

**Comment by delia-pop** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1756824

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by delia-pop** [comment]
Please note that when using **GeckoView Example**, I noticed that an improper white/dark black bar is displayed, depending if the toolbar was displayed or not when the full-screen was accessed, therefore this could be an issue that the GV team could look into.

**Comment by lkebin** [comment]
> Hello @lkebin,
> 
> Thanks for the report!
> 
> I tested the flow with Google Pixel 6 (Android 12) on the latest Nightly build (99.0a1 Build#2015865003) and latest RC build 97.2.0 and I was not able to reproduce the issue.
> 
> Can you please re-test the issue on the latest Firefox Nightly and Firefox Beta builds and let me know if you are still able to reproduce it?

Thanks for the reply, I just try Nightly build, the problem still persists.

https://user-images.githubusercontent.com/1335935/155440569-899187a6-39bb-45e3-9f94-7db4d09ca550.mp4

**Comment by gitt0r** [comment]
Is there still being worked on? 
My device is also a Huawei Mate 40 Pro with EMUI 12.0.0.

I'm on Firefox Nightly 103.0a1 (Build #2015884011).

https://user-images.githubusercontent.com/65116394/171699504-50843cbf-6809-40e6-a6d7-54ed093423f9.mp4

**Comment by lkebin** [comment]
Hi @delia-pop, seems bugzilla issue was closed, but the problem still here on latest stable version
