### ISSUE TITLE
[a11y] - Consider making "reader mode" icon from navigation bar larger

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23873]
### Steps to reproduce

1. Have the Accessibility scanner installed and opened.
2. Go to a site with a lot of text content (e.g.wikipedia).
3. Enable "Reader view" from the navigation bar.
4. Scan the page

### Expected behaviour

No suggestions are made.

### Actual behaviour

After the page is scanned, the **Touch target suggestion** is displayed for **"reader mode" icon** from the navigation bar. Please see the screenshot attached for reference.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

98.0.0-beta.3

### Additional information

![Reader view](https://user-images.githubusercontent.com/96047134/155119072-0b54a78d-d271-4662-b8c4-d0b2bb0f1d61.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19588)

**Comment by lobontiumira** [comment]
Still reproducible on the latest Beta 105.0b5 build with Samsung Galaxy Note 8 (Android 9).

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813893

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
