### ISSUE TITLE
[Bug]: [a11y] Download notification - "Pause" and "Cancel" buttons need to be larger

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23879]
### Steps to reproduce

1. Have the Accessibility scanner installed and opened.
2. Navigate to www.thinkbroadband.com/download
3. Tap on the 1GB file in order to downloaded it and tap on the "Download" button
4. Expand the download notification and scan it using the accessibility scanner.

### Expected behaviour

There are no suggestions to make any changes.

### Actual behaviour

After the download notification is scanned, the **Touch Target suggestion** is displayed for **"Pause"** and **"Cancel"** buttons. Please see the screenshots attached for reference.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

98.0.0-beta.3

### Additional information

![Pause](https://user-images.githubusercontent.com/96047134/155142267-3cb4cf89-b0d1-428a-9167-79bf81ab6a56.JPEG)

![Cancel](https://user-images.githubusercontent.com/96047134/155142316-48738e82-2f64-4b47-8c5c-9b145c151052.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19594)

**Comment by Amejia481** [comment]
> Hi @LaviniaL99 , can i make these changes?

Sure, feel free to work on that!
