### ISSUE TITLE
[Bug]: Allow for inserted urls to open in current tab

### ISSUE THREAD

**Issue by Thefalas** [mozilla-mobile/fenix#23875]
### Steps to reproduce

1. Have a tab open
2. Write any url in the url bar
3. Press Enter

### Expected behaviour

The desired url should open in the same tab

### Actual behaviour

A new tab with the desired url opens

### Device name

Oneplus 8T

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96

### Additional information

The configuration option that regulates this behavior (about:config  **browser.urlbar.openintab** ) which is available in the desktop version of firefox is not accesible in Android

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19590)

**Comment by LaviniaL99** [comment]
Hello @Thefalas 

Thanks for your report! I verified the above issue on the l**atest Nightly build (100.0a1)** and **latest RC build (98.2.0)** and i was not able to reproduce the issue.

**Device used:**

- Samsung S10E -> Android 10

Can you please retest the flow on the latest builds and let me know if you are still able to reproduce the issue? If yes, please attach a video of the interest flow.
