### ISSUE TITLE
Touch target - The lock icon from URL search bar needs to be resized

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#23872]
### Steps to reproduce

1. Install Accessibility Scanner from Play store
2. Open the Firefox app and tap on "Start browsing" button
3. Navigate to cnn.com
4. Using the accessibility scanner app, scan the page

### Expected behaviour

After the page is scanned, there are no suggestions to make any changes.

### Actual behaviour

After the page is scanned, the **Lock icon** is recomanded to be resiezed -> Touch target suggestion. Please see the screenshot attached for evidence.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

98.0.0-beta.3

### Additional information

![Lock icon](https://user-images.githubusercontent.com/96047134/155116325-d976a2ba-23d3-4332-bd00-d233356b92a8.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19587)

**Comment by lobontiumira** [comment]
Still reproducible on the Fenix 105.0b5 Beta build with Samsung Galaxy Note 8 (Android 9).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812176

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
