### ISSUE TITLE
Improper blank space remains displayed on homepage after dismissing the keyboard 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23884]
### Steps to reproduce

1. Install and launch the Fenix browser in Portrait mode.
2. Tap on the Firefox Browser Logo to set a wallpaper.
3. Select the toolbar placement to "Bottom".
4. Tap on "Start browsing" to dismiss the onboarding tour.
4. Tap the device's back button to dismiss the keyboard.
5. Observe the homepage.

### Expected behaviour

After dismissing the keyboard, the homepage is properly displayed when a wallpaper is applied.

### Actual behaviour

After dismissing the keyboard, an improper blank space is displayed on homepage instead, when a wallpaper is applied.
This issue is not 100% reproducible and was not encountered when selecting the toolbar placement to "Top".
However, the issue occurs regardless of the theme or locale selected.

### Device name

Google Pixel 6, Huawei MediaPad M2

### Android version

Android 12, Android 5.1.1

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build 2015864811) from 02/22

### Device logs

[Blank space wallpapers_pixel6.txt](https://github.com/mozilla-mobile/fenix/files/8117842/Blank.space.wallpapers_pixel6.txt)

### Additional information

https://user-images.githubusercontent.com/89388888/155161604-6cd93c3a-6740-4b73-a43e-eb094d65d3aa.mp4

![Screenshot_2022-02-22-17-22-20](https://user-images.githubusercontent.com/89388888/155163502-70240775-52b1-4148-86ed-c64cd1254d9d.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19597)

**Comment by delia-pop** [comment]
This is still reproducible on the latest Nightly from 03/03 with Motorola Moto G30 (Android 11).

**Comment by delia-pop** [comment]
The blank space was also observed on RC 103.2.0 when crashing the app using about:crashparent, with Lenovo Yoga Tab 11 (Android 11).

https://user-images.githubusercontent.com/89388888/182811010-b8f12ff0-6784-4347-bff7-6ffb6c4f2ac3.mp4

.

**Comment by ghostsquad** [comment]
This is not specific to the home page. I've encountered the same problem generally when using the keyboard on any page.

Work around is simply press the square "switch app" button, then tap on Firefox again.

**Comment by ghmn256** [comment]
I have what seems to be the same issue. 

Sometimes when I visit a different site by typing in the url bar the space that the keyboard had occupied will remain blank. (see screenshot) Scrolling down the website will fix it.
Like mentioned, it doesn't always occur so probably a race condition of sorts.
![Screenshot_20221017-144334_Firefox Beta](https://user-images.githubusercontent.com/111056240/196180178-50311e1b-a624-42c4-8648-32b187f3dddc.jpg)

My toolbar is at the bottom, no addons, issue occurs both in Firefox and Firefox beta. Android 12, Samsung s22+

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809808

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
