### ISSUE TITLE
[Bug]: large filename to download

### ISSUE THREAD

**Issue by vinihvc** [mozilla-mobile/fenix#23895]
### Steps to reproduce

Download a file with large name

### Expected behaviour

Show button tô download 

### Actual behaviour

Dont show button

### Device name

One plus 7T

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

97.2.0

### Additional information

![Screenshot_20220222-150805](https://user-images.githubusercontent.com/16567830/155195111-de9a5582-c549-4073-b8ef-76d60045557c.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19605)

**Comment by sunilk9211** [comment]
I could reproduce it. File name has to be unusually large for this. I checked the layout file. @viniciushvc can i work on it?

**Comment by viniciushvc** [comment]
Absolutely, go ahead
