### ISSUE TITLE
[Bug]: History is truncated if `FeatureFlag.historyImprovementFeatures` is turned on

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#23894]
### Steps to reproduce

1. Open Fenix with profile that has multiple (>5) pages of history visits
1. Navigate to three dot menu -> History
2. Scroll down

### Expected behaviour

User can scroll and search through entire history.

### Actual behaviour

Scrolling only works for up to 5 pages (note that searching works fine.)

### Device name

Pixel 3a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99

### Additional information

This only reproduces on Nightly for me, so thinking it's related to the `historyImprovementFeatures` feature flag.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Nightly 2022-03-09 and 99.0.0-Beta.1. The History section can be scrolled to the end even with on longer lists.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- Google Pixel 6 (Android 12)
