### ISSUE TITLE
FNX3-16283 ⁃ Onboarding - Custom Setting Card: Choose Theme

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#2389]
As a user who views a custom setting  card for choice of themes, I want to be able to keep my current theme or select a new one within the onboarding flow. 

## Dependencies
* List dependencies on other issues/teams etc.

### Acceptance Criteria
* I can do nothing and will still have the light theme
* I can select the dark theme and see the app switch to the dark theme
* I can choose to have my theme match my device theme, and have the light theme persist if i am using device light theme or switch to the dark theme if I am using device dark theme
* I will remain within the onboarding context while I make changes to the theme and can access the theme choices until the onboarding flow is dismissed

**Comment by softvision-miralobontiu** [comment]
Verified that the user can:
- do nothing and still have the light theme;
- select the dark theme and see the app switch to the dark theme;
- choose that theme matches the device's theme, and have the light theme persist if the user is using the device light theme, or switch to the dark theme if the user is using the device dark theme;
- remain within the onboarding context while making changes to the theme and can access the theme choices until the onboarding flow is dismissed.
Tested on the latest build 1.0.1921 (#11410622), with Google Pixel (Android 9), Huawei Honor 8 (Android 7), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by softvision-miralobontiu** [comment]
I will remove the QA needed flag until #2721 is fixed.

**Comment by softvision-miralobontiu** [comment]
I will close this issue, hence #2721 is fixed.
