### ISSUE TITLE
FNX3-16285 ⁃ Onboarding - View Tour

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#2390]
User Story
As a user who has just installed and opened Fenix, I want to be welcomed to the  product and may want to learn about the key features that will help me use Fenix. 

## Dependencies
* List dependencies on other issues/teams etc.

### Acceptance Criteria
* I can see a welcome message
* I can see content that helps me learn about key features
* I am not blocked by this content from using the product to access settings or access the internet

**NOTE FOR ENG: Let's make sure we build this in a way that's flexible for future use if we want to incorporate tips! Perhaps we should even name them in a generic way because of this like "TipContainer" etc.**

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1921 (#11420606), with:
- Sony Xperia Z2 tablet (Android 6.0.1),
- HTC 10 (Android 8),
- Nexus 5 (Android 6.0.1),
- Sony Xperia Z5 Premium (Android 7.1.1).
