### ISSUE TITLE
FNX3-16286 ⁃ Onboarding - Dismiss Tour

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#2391]
User Story
As a user who can see onboarding content cards, I want to remove cards or have them disappear  once I start to use features of the browser. 
Dependencies

List dependencies on other issues/teams etc.

Acceptance Criteria

I can remove all content cards at once by selecting Start Browsing
I no longer see all content cards once I use the search box or access settings
Once all cards are removed, I can see my open tabs

**Comment by sblatz** [comment]
**Let's make sure that [sign in to sync](https://github.com/mozilla-mobile/fenix/issues/2395) does not dismiss the tour**

**Comment by softvision-miralobontiu** [comment]
Verified that the user can dismiss onboarding tour by:
- tapping on Settings or Your Library, from the main menu,
- tapping on the search bar,
- tapping on Start browsing.

Testing with the build from 5/22, on the following devices: Nexus 5 (Android 6.0.1), Sony Xperia Z2 tablet (Android 6.0.1), HTC 10 (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by vesta0** [comment]
Is this QA verified @softvision-miralobontiu

**Comment by softvision-miralobontiu** [comment]
Hi Vesta,
Yes, it is, but I removed the flag until [issue 2726](https://github.com/mozilla-mobile/fenix/issues/2726) is fixed.

**Comment by vesta0** [comment]
Let's please close this since #2726 will be separately tracked and prioritized.
