### ISSUE TITLE
FNX3-16287 ⁃ Onboarding - Feature Card: Private Browsing

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#2392]
User Story
As a user who sees an onboarding feature card about private browsing, I want to read about private browsing. 

## Dependencies
* List dependencies on other issues/teams etc.

### Acceptance Criteria
* I can read about private browsing.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1921 (11420606), with:
- Sony Xperia Z5 Premium (Android 7.1.1), 
- Nexus 5 (Android 6.0.1), 
- Sony Xperia Z2 tablet (Android 6.0.1), 
- HTC 10 (Android 8).
