### ISSUE TITLE
[webcontent] sites broken in nightly

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#23927]
## Site with issue and any steps to reproduce
https://www.zee5.com/

### Expected behavior
Site should load properly

### Actual behavior
Site not loading..whereas it works fine in firefox beta and other browsers..this is one of the site

Yesterday I found the bug in another site also but forgot it's link. Seems some recent commits introduced the bug

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No..even with fresh installation it does not work

### Can you reproduce in Chrome (or other non-Mozilla browser)?

Works fine in chrome and firefox beta
### Device information

* Android device: ? A11 rog3
* Fenix version: ? Latest nightly

**Comment by sflorean** [comment]
I was able to reproduce this on latest Nightly build 2/23 with OnePlus 9 (Android 11) but not on Beta 98.0.0-beta.3. 
The site is loaded and a black page/ screen is displayed.

**Comment by Mugurell** [comment]
This reproduces also on latest GVE.
Moving to Bugzilla for more investigation.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1756760

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
