### ISSUE TITLE
Canon.com/ijsetup

### ISSUE THREAD

**Issue by jessicaynch105** [mozilla-mobile/fenix#23923]
### Steps to reproduce

Canon inkjet printers are widely used the allover globe. It’s the combination of ink, print text, images, and graphics print output. These models are easy to use and offer outstanding creative printing solutions  <a href="https://istartsetup.com/canon-com-ijsetup">Canon.com/ijsetup</a> .

### Expected behaviour

Canon inkjet printers are widely used the allover globe. It’s the combination of ink, print text, images, and graphics print output. These models are easy to use and offer outstanding creative printing solutions  <a href="https://istartsetup.com/canon-com-ijsetup">Canon.com/ijsetup</a> .

### Actual behaviour

Canon inkjet printers are widely used the allover globe. It’s the combination of ink, print text, images, and graphics print output. These models are easy to use and offer outstanding creative printing solutions  <a href="https://istartsetup.com/canon-com-ijsetup">Canon.com/ijsetup</a> .

### Device name

samsung galaxy note 1

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

89.0.1

### Device logs

Canon inkjet printers are widely used the allover globe. It’s the combination of ink, print text, images, and graphics print output. These models are easy to use and offer outstanding creative printing solutions [Canon.com/ijsetup](https://istartsetup.com/canon-com-ijsetup) .

**Comment by LaurentiuApahideanSV** [comment]
I don't see what the issue is here. Please refer to the [Guide to Contributing](https://github.com/mozilla-mobile/shared-docs/blob/master/android/CONTRIBUTING.md) before filling an issue.
