### ISSUE TITLE
ij.start canon

### ISSUE THREAD

**Issue by travissmith39** [mozilla-mobile/fenix#23924]
### Steps to reproduce

<a href="https://www.cijstartcanone.org/">ij.start canon</a>  is the manufacturer's site to download Canon printer drivers. You can easily download the driver according to your model as <a href="https://www.cijstartcanone.org/">ij.start.canon</a> is designed with a user-friendly interface . <a href="https://www.mijstartcano-n.org/https-ij-start-cannon/">Https //ij.start.cannon</a> . <a href="https://istartsetup.com/canon-ij-network-tool/">Canon IJ Network Tool</a> is a toolkit software with the options to keep a check on most of your Canon printer network settings and adjust them according to your requirements.

### Expected behaviour

Ij start canon is a platform for getting the canon printer driver. You can easily download the driver according to your model as ij start canon is designed with a user-friendly interface. 

### Actual behaviour

Ij start canon is a platform for getting the canon printer driver. You can easily download the driver according to your model as ij start canon is designed with a user-friendly interface. 

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

89.0.10

**Comment by LaurentiuApahideanSV** [comment]
I don't see what the issue is here. Please refer to the [Guide to Contributing](https://github.com/mozilla-mobile/shared-docs/blob/master/android/CONTRIBUTING.md) before filling an issue.
