### ISSUE TITLE
Taping on the Pause button on a downloading file and nothing happens

### ISSUE THREAD

**Issue by Umeaboy** [mozilla-mobile/fenix#23933]
### Steps to reproduce

1. Start 3 or more downloads.
2. Watch the progress by pulling down the drawer.
3. One file seems to stop downloading so you click on the Pause link on the one that has "stopped" and nothing happens.

### Expected behaviour

When you click on the link Pause the download should be paused.

### Actual behaviour

Nothing happens when you tap on the linked word Pause, but the linked word Cancel on the right aborts the download.

### Device name

Samsung Galaxy S10+ (SM-G975F)

### Android version

Android 12 (Lineage 19.0)

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19623)

**Comment by LaviniaL99** [comment]
Hello @Umeaboy 

Thanks for you report! I verified the issue on the latest Nightly build (99.0a1 from 03/08) and latest RC build (98.1.1) and i was not able to reproduce the issue -> verified with 3 and more files and the flow works as expected.

**Device used:**

- Samsung S10E-> Android 10

Can you please verify if you are still able to reproduce the issue on the latest builds and if so, please let me know if there is a **specific website**  from where you download the files and please attach a video of the interest flow.

**Comment by Umeaboy** [comment]
> Hello @Umeaboy
> 
> Thanks for you report! I verified the issue on the latest Nightly build (99.0a1 from 03/08) and latest RC build (98.1.1) and i was not able to reproduce the issue -> verified with 3 and more files and the flow works as expected.
> 
> **Device used:**
> 
>     * Samsung S10E-> Android 10
> 
> 
> Can you please verify if you are still able to reproduce the issue on the latest builds and if so, please let me know if there is a **specific website** from where you download the files and please attach a video of the interest flow.

Is that stock Android 10 or Lineage?
I'm using Lineage without GApps if that matters somehow.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812789

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
