### ISSUE TITLE
Show dialog when I want to delete a credit card

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#23936]
When people tap on delete a credit card, show the following dialog (similar to what's there   for logins):

```
Are you sure you want to delete this credit card?
Cancel   Delete
```

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-03-05. When tapping the trashcan icon or the "Delete card" text the following prompt is displayed. Tapping the cancel button will dismiss the prompt and the Delete option will delete the card. I will close this issue as fixed.
![1646238117710](https://user-images.githubusercontent.com/50983519/156404095-af89d071-0def-4575-bc0e-84b9f59523df.JPEG)
![1646238117603](https://user-images.githubusercontent.com/50983519/156404098-ab0b7ccf-f16c-4715-bee7-4a5085dce008.JPEG)
### Device used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)
