### ISSUE TITLE
Segment credit card entries

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#23934]
Segment credit card entries in number blocks of 4 (5555 5555 5555 4444) so that it's easier for people to enter them without making mistakes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19624)

**Comment by gabrielluong** [comment]
We might want to consider the credit card provider and format it as appropriate. I can see 2 scenarios with the list of credit cards and credit card number editing.

**Comment by topotropic** [comment]
Let's keep this open, it will make it easier for people to input and verify their credit card numbers. 

@gabrielluong not sure I understand your comment, would it make sense to have a xxxx xxxx xxxx xxxxx structure, so that we have a space after 4 digits?

**Comment by gabrielluong** [comment]
@topotropic To circle back on this, I meant that it's not so simple to assume that the 4 digit separation will work for all credit cards. 

<img width="797" alt="Screen Shot 2022-11-21 at 6 58 33 PM" src="https://user-images.githubusercontent.com/1190888/203181948-6e8ee5b1-7ffd-4d7e-a400-5a7c1223e2d0.png">
Taken from https://stripe.com/docs/testing, you will see that 4 digit separation will work for quite a lot of credit cards. However, AMEX credit cards have their own formatting.

I see 2 options that we can proceed with: 
1) We could use 4 digit separation. This will probably improve things for a number of cases and it is the most easiest solution to implement. So, I don't have any concerns about pursuing this option. 
2) We could take option 1 and go one step further by recognizing the credit card brand (eg, Visa, American Express, etc) as the user is typing and dynamically formatting to match the expected number format you would see on the credit card. I imagine this will require more work compare to option 1, but I would consider this the ultimate solution.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814156

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
