### ISSUE TITLE
[Bug]: Credit Card sync overwrites data

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#23932]
### Steps to reproduce

1. Have two credit cards stored on desktop and 1 on mobile or so
2. Enable sync and sync cards

### Expected behaviour

I expected that cards are merged and I have desktop and mobile entries 

### Actual behaviour

Either the entry on mobile or on desktop is lost

### Device name

Google Pixel 3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19622)

**Comment by kbrosnan** [comment]
SV are you able to reproduce this behavior?

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue by performing the following scenarios:
1. On Firefox mobile log in with a new account that doesn't have any credit cards stored;
2. Turn off credit card sync;
3. Save a credit card;
4. On Firefox for Windows log in the same account;
5. Save 2 Credit cards;
6. Enable credit card sync on Firefox mobile and sync;
7. On Firefox for Windows perform a sync.

1. On a fresh install of Firefox mobile store a credit card without being logged in;
2. On Firefox for Windows log in with a new account that doesn't have any credit cards stored;
3. Save 2 credit cards;
4. On Firefox mobile log in with the same account;
5. Perform a sync;

I wasn't able to reproduce the issue, after performing the scenarios all 3 credit cards appeared on both mobile and Windows.
@topotropic Is the further information that you can provide us that may help us reproduce the issue?
