### ISSUE TITLE
FNX3-16288 ⁃ [Bug] When I try to search for info about a domain, Fenix just directly visits the domain instead

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#2393]
## Steps to reproduce
1. Type a domain into the URL bar (e.g. type "example.org")
1. Don't hit enter -- instead, tap the suggestion that looks like this (it's the first suggestion for me)
> :mag:  example.org
>    Google

### Expected behavior
I should end up at Google Search Results for the search string "example.org". i.e. I should end up at this page: https://www.google.com/search?q=example.org

### Actual behavior
Fenix sends me directly to http://example.org , despite the fact that I tapped a box that implied it'd give me Google search results for this search string.

Note that if I were trying to do this for a more-shady domain (if I were trying to search for information about some `maybeBadGuys.biz` domain, after receiving a shady email from them, and unexpectedly ended up being taken directly to their site), this mistake could potentially be dangerous and/or a privacy issue.

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1919

Note: Fennec gives EXPECTED RESULTS. Its Google autocomplete suggestions take me to a google search results page, including when my search query happens to be a domain name.

**Comment by ekager** [comment]
@vesta0 I have a quick fix for this :)

**Comment by ekager** [comment]
@vesta0 this is done but I'm not sure which board to put it in

**Comment by dholbert** [comment]
I've verified that this is fixed on my end, w/ current Fenix from Google Play store, BTW (same device used when filing the bug).

Thanks, @ekager!

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with Google Pixel (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1), on the latest build 1.0.1920 (Build #11350639).
