### ISSUE TITLE
[Bug]: cannot play OGG files when the OGG sandbox is enabled

### ISSUE THREAD

**Issue by svillar** [mozilla-mobile/fenix#23931]
### Steps to reproduce

1. Open https://moonrider.xyz (this is meant to be played in immersive mode but it works without VR capabilities)
2. Select one song and click on Play

### Expected behaviour

The music plays

### Actual behaviour

No music

### Device name

Oculus Quest 2

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

90

### Device logs

I cannot provide logs ATM but will get them on request.

What I can mention is that I tracked the issue to `OggDemuxer::CreateSandbox()`. The logs were showing an OOM error but that's just because that's the error that is reported by Gecko when it cannot create the rlbox sandbox.

Disabling the sandbox for Ogg (by removing it from `wasm_sandboxing_libraries` in `moz.configure` "fixes" the issue, no more OOM errors and ogg play seamlessly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19621)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Nightly 2022-02-23.

### Devices used:
- Google Pixel 6 (Android 12)
- OnePlus 6T (Android 9)
