### ISSUE TITLE
FNX3-16290 ⁃ Onboarding - Action card: Sign in to Sync

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#2395]
As a user who sees an onboarding action card for Sync, I want to set up sync
Dependencies 
FxA flows

### Acceptance Criteria
* I can select the action button to initiate the account sign up or sign in flow in a tab
* If I have successfully signed in to my account from the card, I see an indication that I am syncing
* If  I have successfully signed in to my account from the card, the FxA tab closes and I am returned to the homescreen where I no longer see the card for sync but can see the Welcome message and any other onboarding cards

**Comment by softvision-miralobontiu** [comment]
The user can sign in from the onboarding sign in action card. But, after entering the valid credentials, the app displays a page that let the user know it is connected (please see the screenshot) - no syncing indicator is displayed.

Only when the user taps on the tab counter, the user can see the welcome message and the rest of the onboarding cards.

@mheubusch, please let me know if this behavior is expected. 
Thank you!


![Screenshot_20190524-155200](https://user-images.githubusercontent.com/40694158/58329040-4870cb80-7e3c-11e9-95f9-db5a2cc4d28d.png)

**Comment by softvision-miralobontiu** [comment]
After tapping on "Sign in" from the Onboarding sign-in card, the user is redirected to a custom tab to register. 

![signin](https://user-images.githubusercontent.com/40694158/59022799-296c3380-8857-11e9-8cb0-812b90fad017.gif)

**Comment by boek** [comment]
@softvision-miralobontiu It is :+1:.

**Comment by softvision-miralobontiu** [comment]
Well then, I will close the issue and label it as verified.
Thank you!
