### ISSUE TITLE
Migrate MessageCardViewHolder to Compose

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23966]
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

Refers to [MessageCardViewHolder](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt) which is used to show a card letting users easily set Fenix as the default browser.

The compose version can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

**Comment by gabrielluong** [comment]
Note this seems to be undergoing some work and even being refactored in https://github.com/mozilla-mobile/fenix/pull/24340. I would suggest holding off.
