### ISSUE TITLE
Migrate homescreen Tip to Compose

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23965]
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

Refers to [ButtonTipViewHolder](https://github.com/mozilla-mobile/fenix/blob/f7d317fb4ea76428d4cc9578b76bd9ef6edf8ca0/app/src/main/java/org/mozilla/fenix/home/tips/ButtonTipViewHolder.kt) which is used to show various update messages to users.

The compose version can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

**Comment by gabrielluong** [comment]
I have been meaning to investigate whether or not we even need this. I think this was only showing the Master Password Tip, but with the migration code being removed. We might not even need this anymorre.

**Comment by gabrielluong** [comment]
My conclusion is that we will remove this after we are done with the Fennec to Fenix migration removal.

**Comment by gabrielluong** [comment]
Closing this since we're removing Tips in https://github.com/mozilla-mobile/fenix/pull/24236
