### ISSUE TITLE
Improper flicker displayed on fullscreen video after dismissing the Android notification bar

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#23963]
### Steps to reproduce

1. Open a video on vimeo.com/yahoo.com.
2. Enter the fullscreen mode.
3. Invoke the Android notification bar.
4. Dismiss the Android notification bar.
5. Observe Improper flicker displayed.

### Expected behaviour

The transition is done smoothly, with no visual glitches.

### Actual behaviour

A flicker can be observed when when the Android notification is dismissed. 
Note that the visual defect is more prominent when using the Light theme.

### Device name

Google Pixel 6

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 Latest Nightly from 02/24, RC 97.2.0

### Additional information

Note that the issue is not reproducible with GVE.
https://user-images.githubusercontent.com/89388888/155514193-9accf7e1-7630-45af-b69b-8c7971849bb4.mp4

https://user-images.githubusercontent.com/89388888/155704886-d7e54380-a8e6-4ba3-8ab8-7b5bb3882740.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19640)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813736

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
