### ISSUE TITLE
Migrate homescreen top sites to Compose

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23967]
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

Refers to [TopSitePagerViewHolder](https://github.com/mozilla-mobile/fenix/blob/f7d317fb4ea76428d4cc9578b76bd9ef6edf8ca0/app/src/main/java/org/mozilla/fenix/home/topsites/TopSitePagerViewHolder.kt) which is used to a scrollable list of top sites to users.

The compose version can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19646)

**Comment by gabrielluong** [comment]
I already have WIP for rmigating top sites. Self assigning.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809999

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
