### ISSUE TITLE
add ultrawideo add on to the current add on list

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#23960]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently to scale the video to full screen I am using ultrawideo add on in nightly but lately I see nightly getting very unstable so please add this add on to the general add on list in beta and stable release so that I can switch happily..

Samsung browser already has custom video control natively built in but firefox does not have and I am sure it will never have..
So please add this add on

### How do you know that this problem exists today? Why is this important?
Without this add on it is not possible to scale the videos to full screen or as per user liking

### Who will benefit from it?
All users

**Comment by kbrosnan** [comment]
We are not keeping issues open for individual extension requests.
