### ISSUE TITLE
Fenix crash reporter's Socorro crash reports for Java exceptions have "Platform" = "Unknown" instead of "Android"

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#23977]
### Steps to reproduce

More than half of the [Socorro crash reports from Fenix or Focus](https://crash-stats.mozilla.org/search/?product=Focus&date=%3E%3D2022-02-17T19%3A55%3A00.000Z&date=%3C2022-02-24T19%3A55%3A00.000Z&_facets=signature&_facets=build_id&_facets=product&_facets=release_channel&_facets=platform&_facets=platform_pretty_version&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-platform) have "Platform" == "Unknown" instead of "Android".

The [Socorro crash reports with Platform == "Android"](https://crash-stats.mozilla.org/search/?product=Focus&platform=Android&date=%3E%3D2022-02-17T19%3A55%3A00.000Z&date=%3C2022-02-24T19%3A55%3A00.000Z&_facets=signature&_facets=build_id&_facets=product&_facets=release_channel&_facets=platform&_facets=platform_pretty_version&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature) are all native code crashes.

The [Socorro crash reports with Platform == "Unknown"](https://crash-stats.mozilla.org/search/?product=Focus&platform=Unknown&date=%3E%3D2022-02-17T19%3A55%3A00.000Z&date=%3C2022-02-24T19%3A55%3A00.000Z&_facets=signature&_facets=build_id&_facets=product&_facets=release_channel&_facets=platform&_facets=platform_pretty_version&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature) are all Java exceptions.

### Expected behaviour

All Socorro crash reports from Fenix or Focus should have "Platform" == "Android".

### Actual behaviour

Socorro crash reports for Java exceptions from Fenix or Focus have "Platform" == "Unknown".

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

97.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19650)

**Comment by kbrosnan** [comment]
Sounds like part of lib-crash needs to be updated. https://github.com/mozilla-mobile/android-components/tree/main/components/lib/crash

**Comment by cpeterso** [comment]
This bug is still relevant. 99.99% of Fenix and Focus crashes with Platform "Unknown" are parent process crashes. Seems like the crash reporter ought to know at compile time that Platform will always be "Android".

https://crash-stats.mozilla.org/search/?product=Fenix&product=Focus&platform=Unknown&_facets=signature&_facets=process_type&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-process_type

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812771

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
