### ISSUE TITLE
Migrate homescreen from RecyclerView to just Compose

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23972]
This completes the work from https://github.com/mozilla-mobile/fenix/issues/22755 and should be done after all homescreen sections are implemented as composables.

The performance of the end composable must be profiled against the current RecyclerView based implementation and must be validated by the performance team also.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19641)

**Comment by indurs** [comment]
Can I be involved in migrating the home screen to Jetpack Compose?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809829

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
