### ISSUE TITLE
Migrate CollectionHeaderViewHolder to Compose

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23971]
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

This refers to:
- [CollectionHeaderViewHolder](https://github.com/mozilla-mobile/fenix/blob/f7d317fb4ea76428d4cc9578b76bd9ef6edf8ca0/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/CollectionHeaderViewHolder.kt) showing a simple "Collections" header

The compose versions can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

**Comment by gabrielluong** [comment]
I separated out all the different viewholders for the Collections from this issue into their own individual issues since doing one should not affect the other.
