### ISSUE TITLE
Migrate RecentVisitsHeaderViewHolder to Compose

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#23970]
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

Refers to just the [RecentVisitsHeaderViewHolder](https://github.com/mozilla-mobile/fenix/blob/f7d317fb4ea76428d4cc9578b76bd9ef6edf8ca0/app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentVisitsHeaderViewHolder.kt) which adds a "Recently visited" header.
[RecentlyVisitedViewHolder](https://github.com/mozilla-mobile/fenix/blob/f7d317fb4ea76428d4cc9578b76bd9ef6edf8ca0/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisitedViewHolder.kt)) which shows a scrollable list of the recent history items/groups is already based on the compose framework.

The compose version can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

**Comment by gabrielluong** [comment]
Delegated this to @sarah541 to give her a starter experience for writing Compose.
