### ISSUE TITLE
No message is displayed when pages are not found in history

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#23986]
### Steps to reproduce

1. Make some browsing.
2. Go to history and tap on search.
3. Search for a site that is not displayed in history.

### Expected behaviour

"No history found" message is displayed.

### Actual behaviour

Nothing is displayed.  Reproducible also when voice search is used.

### Device name

Samsung A32

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19652)

**Comment by indurs** [comment]
Can I work on this issue? I can reproduce the above bug


![Screenshot_20220228-114601](https://user-images.githubusercontent.com/12825812/155933939-e332fe74-3268-4918-b170-331ac290982c.png)

**Comment by amocirean** [comment]
This issue is still reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using Samsung Galaxy S22 Ultra (Android 13) and Oppo Find X3 Neo.
Removing the wontfix label.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807705

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
