### ISSUE TITLE
[Bug]: Different padding for titles from tabs tray - search groups

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#23987]
### Steps to reproduce

1. Go and create 2-3 search groups.
2. Open tabs tray and check the padding for the summary.

### Expected behaviour

The padding is the same and no visual defects should be displayed/ visible. 

### Actual behaviour

<img src="https://user-images.githubusercontent.com/58466444/155735408-61307a52-30c1-4e10-a21b-9d752eba3d0d.jpg" width="300" height="550" />

### Device name

Samsung A32

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19653)

**Comment by DoozyDoz** [comment]
@sflorean The padding is the same but the once a word does not fit a line its pushed to the second line which is normal for all text views, I see no bug here
