### ISSUE TITLE
FNX3-16292 ⁃ Onboarding - Settings Card: Tracking Protection

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#2399]
As a user who views a setting card for tracking  protection, I want to be able to keep my tracking protect on or turn it off within the onboarding flow.
Dependencies

```
List dependencies on other issues/teams etc.
```

Acceptance Criteria

```
I can do nothing and will still have tracking protection
I can toggle off tracking protection  and no longer have tracking protection
I can toggle on tracking protection and  restore tracking protection
I will remain within the onboarding context while I make changes to tracking protection and can access the choices until the onboarding flow is dismissed
```

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1921 (11420606), with Sony Xperia Z5 Premium (Android 7.1.1), Nexus 5 (Android 6.0.1), Sony Xperia Z2 tablet (Android 6.0.1), and HTC 10 (Android 8).
