### ISSUE TITLE
FNX3-16293 ⁃ [UX] Request Desktop Site

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#24]
Mockup:
https://mozilla.invisionapp.com/share/ZJQ27Q578M3#/341830172_Request_Desktop_Site

**Comment by shorlander** [comment]
**Mockup:**
https://mozilla.invisionapp.com/share/ZJQ27Q578M3#/341830172_Request_Desktop_Site

**Comment by topotropic** [comment]
@lime124 I think that one's done

**Comment by lime124** [comment]
done as per shorlander
