### ISSUE TITLE
Enable Battery Saver settings

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#240]
This is about packaging existing features that help users save battery.

### User Story
As a user, I want to be able to enable battery saver mode in my browser, so I can browse for longer without having to charge my phone. 

### Requirements
Surface a battery saver mode that includes the following battery saving features:
-Block Trackers
-Disable media autoplay
-Enable dark theme
-Enable dark mode (webpage)
-Auto Reader Mode (when available)
Later:
-Lower Image Quality
-Throttle Streaming Bandwidth (use lower quality video streams)

### Acceptance Criteria
* I can enable battery saving mode (enabling all features)
* I can individually toggle off each feature

![image](https://user-images.githubusercontent.com/42752644/66096834-392c2800-e56a-11e9-9bdc-6da8b65d3455.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11392)

**Comment by st3fan** [comment]
@bbinto Can we reference the ideas we previously talked about? I don't know where to find those. Maybe @shorlander knows?

**Comment by shorlander** [comment]
@st3fan this is the list I have of things we have discussed that could potentially create battery savings:
* Block Ads
* Block Trackers
* Disable Autoplay
* Reader Mode as Default
* Dark Mode (Theme)
* Lowering Image Quality
* Throttle Streaming Bandwidth (use lower quality video streams)

There was also some discussion around things we might not being optimizing on the platform side because we haven't been thinking about them primarily from an energy saving perspective. This included some discussion around maybe more aggressively caching things to avoid using the radio.

**Comment by colintheshots** [comment]
I guess I misunderstood the feature based on older discussions. We'd mentioned removing native apps and replacing them with PWAs or web apps. Also, we seemed to indicate we'd somehow measure the benefit of various steps, which is tremendously hard on Android.

The list you mention doesn't seem too difficult, but there's the overhead of keeping extra code branches across the app. We could probably handle this type of configuration with the component architecture we have planned-- the same way we're handling layout A/B experiments.

**Comment by bbinto** [comment]
This includes the UI to enable it, the individual functionalities should be split into different tickets

**Comment by sblatz** [comment]
Checklist:

- [ ] Adblocking: #96
- [ ] Block trackers: #216 (child of this)
- [ ] Disable autoplay: #255
- [ ] Reader mode: #74
- [ ] Dark mode: #252 
- [ ] Lower image quality: #253
- [ ] Throttle video: #254

**Comment by Cheap-Skate** [comment]
Some suggestions on power saving

- Reduce frame rate

I think animating, scrolling and flinging use quite a lot of CPU power (GPU in the case of WebRender). You could reduce layout.frame-rate to 30 fps. (I think Firefox Desktop is talking about doing this on low power machines but to speed things up not save battery???).

IIRC my previous Sony Xperia phone had "Stamina" mode which I think downclocked the GPU and limited the frame rate, on Android native animations at least. It got quite janky.

- Downclock CPU cores??

A guess but...

Most phone CPUs have some kind of big.LITTLE architecture. The big cores will likely use more energy for a given task than the LITTLE cores, but will do the task faster.  Is it possible to force a phone to use only its LITTLE cores for page load, JS etc? Even with no big.LITTLE, energy consumption should drop somewhat with a bit of downclocking, so e.g. a CPU limited to say 1500 MHz might use a bunch less energy than clocked right up to 2000 MHz.

For example, you might see 30% longer page loads by doing this, but get but 20% power saving. Or something. No idea if it's practical.

My Galaxy S7 has a power saving mode which allegedly reduces the CPU speed.

- Reduce screen resolution

Doubt it's possible but again GPU workload could be reduced by forcing the phone to use a lower resolution. I doubt you can do this app by app, it's probably a system wide setting. Again my Galaxy S7 has a power saving mode which reduces screen resolution to HD.

No idea if it's any help!

**Comment by Sdaswani** [comment]
@sblatz this may not have been ready for breakdown, did someone ask you to break it down?

**Comment by sblatz** [comment]
@Sdaswani I must have mistakenly thought this was ready when I was looking for work last week (and was directed to breakdown meta tickets). Sorry for any confusion

**Comment by Sdaswani** [comment]
No worries @sblatz ! We may want to reverse the breakdown as _what_ we are doing here is still not clear.

**Comment by bbinto** [comment]
More investigation here: https://docs.google.com/spreadsheets/d/14oul9bD0cYvYUIJxWjSy6O0MsEsbirsvcA6898EP2iA/edit#gid=749105600

**Comment by bbinto** [comment]
We decided on March 15 that we will take individual features out of the batter context, add them individually and in the future, in past MVP version, we might bundle it all back together, with solid data and measurements.

**Comment by sblatz** [comment]
@vesta0 can this get a could or should or must. If it doesn't have a `feature request` label nor any of those, it gets kicked back to our triage list.

**Comment by vesta0** [comment]
Thanks for adding back the Feature request label. We need more investigation before building this so it's on the roadmap but not prioritized.

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report is closed. I think we would want to do this differently.
