### ISSUE TITLE
[Bug]: Homepage not fixed with all options disabled

### ISSUE THREAD

**Issue by robovoice1** [mozilla-mobile/fenix#24004]
### Steps to reproduce

1. Start Fx nightly android 
2. Turn off all options in settings/homepage
3. return to homepage 
4. swipe up and down
See also screen recording

### Expected behaviour

Fixed homepage (with everything disabled)

### Actual behaviour

Swiping up and down possible, but in this case not needed.

### Device name

Google Pixel 6 pro

### Android version

Android 12 GrapheneOS

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build #2015865675), 12efddd64+

### Additional information

https://user-images.githubusercontent.com/92784377/155860931-a55a27a5-2d62-4089-8513-58ed1a0a8a48.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19661)

**Comment by sflorean** [comment]
Thank you for report! Please follow #8545, where this issue is covered.
