### ISSUE TITLE
Return a null change payload if the new top sites list is larger than the old

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24006]
STR:
1. In a fresh profile, observe the 3 default top sites
1. Enable Sponsored Shortcuts in the Homepage Settings
2. Observe that there are only 3 top sites and "Top Articles" is missing

Expected:
Should be able to see all the default + contile top sites.

This seems to be happening since our [getChangePayload](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt#87) expects to only handle deletion and computes a change that will remove 'Top Articles'.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Nightly debug build 2022-03-03. The Top Articles tile is present when Sponsored tiles are also present in the top sites section.
![Top_Articles](https://user-images.githubusercontent.com/50983519/157235823-a3d249a0-e811-406f-a252-7562efd5786d.JPEG)
