### ISSUE TITLE
Doesn't open extenal link from a Telegam group

### ISSUE THREAD

**Issue by gaby2300** [mozilla-mobile/fenix#2400]
## Steps to reproduce
1. Copy link in a Telegram group.
1. Open Fenix and paste the link.
1. Press "Go".
1. Notice message: "Message in a private group or channel. This link will only work if you are a member.
1. Notice a green "Open message" button
1. Press button, notice nothing happens

### Expected behavior
As I belong to the group, pressing the button should show the Telegram group. Works fine in Firefox Release.

### Actual behavior 
I see the following message: "Message in a private group or channel. This link will only work if you are a member. Also a green "Open message" button. Pressing it nothing happens.

### Device information
* Android device: Sony Z3C, Android 6.0.1
* Fenix version: Build #11281647

**Comment by sarentz** [comment]
URL Encoding/decoding of query params? Do we do that properly in the place where we take the paste?

**Comment by kbrosnan** [comment]
Specifically we need to know what step 5 does in Fennec and/or Chrome. Does it send you back to the telegram app or does it take you into the telegram website?

**Comment by jonalmeida** [comment]
@kbrosnan this might also be tracking protection that's blocking functionality.

**Comment by softvision-miralobontiu** [comment]
@gaby2300 could you, please retry and see if this issue is still reproducible?
And could you also try using Fennec or Chrome?
Thank you!

**Comment by kbrosnan** [comment]
Closing this as several issues similar to this have been addressed in the past few months. Gaby please comment if you can still reproduce this and we can reopen this issue.
