### ISSUE TITLE
Feature Request : Close Tab Group on Firefox Fenix

### ISSUE THREAD

**Issue by benyaminl** [mozilla-mobile/fenix#24002]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Closing tab group, make the tab not cluttered, even there are inactive tab, sometimes closing it directly is powerful than one by one to close. Technology make User experience better. 

### How do you know that this problem exists today? Why is this important?
Because as tab group is automatically generated, and can't be swipped, closing the group a hole is good, and if there is an flipable question to ask before close, or directly close it will be awesome

### Who will benefit from it?
User that constantly use web browser for searching web.

### Another Comment
It is good if the browser 

Example : 
![220226_151907](https://user-images.githubusercontent.com/2817332/155836016-4b3223f2-b209-4ebb-b66c-029ed4b9a431.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19660)

**Comment by benyaminl** [comment]
Why it's added as wontfix.. what...

**Comment by cadeyrn** [comment]
@benyaminl Do you still the tab groups in the tabs tray? I thought they got removed in #21898? And I am not able to produce a tab group in the tabs tray in Firefox 107, they are only grouped in the history view…

**Comment by benyaminl** [comment]
@cadeyrn Thanks for replying back. Hmm... if they remove this, this is really unfortunate, yeah, I haven't check it for months, probably. I will close this for now. Hope if this get re implemented, it will be good. 

Thanks for clarifying.
