### ISSUE TITLE
[Bug]: Images displayed too small on Hitomi.la Reader page.

### ISSUE THREAD

**Issue by Kafu-Yukimura** [mozilla-mobile/fenix#24013]
### Steps to reproduce

1. Have a tab open..
2. Go to https://hitomi.la/reader/2064130.html#17

### Expected behaviour

![Screenshot_20220225-031649_Bromite](https://user-images.githubusercontent.com/70040738/155889853-966e4c76-a16a-4874-b601-913810750f54.png)

The Bromite based on Chromium.

### Actual behaviour

![Screenshot_20220225-031928_Iceraven](https://user-images.githubusercontent.com/70040738/155889855-f6e7717e-0569-428d-b046-ddf25b970229.png)

All Firefox-based browsers, including Firefox.

### Device name

Samsung Galaxy Note9

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

97.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19666)

**Comment by kbrosnan** [comment]
This works for me on a Pixel 6 Pro using Firefox Nightly 99.0a1 and release 97.2.0

**Comment by LaviniaL99** [comment]
Hello @Kafu-Yukimura 

Thanks for you report! I verified the issue on the latest Nightly build (99.0a1 from 03/08) and latest RC build (98.1.1) and i was not able to reproduce the issue.

**Device used:**

Samsung S10E-> Android 10

Can you please let me know if you are still able to reproduce the issue on the latest builds?
Thanks!

**Comment by Kafu-Yukimura** [comment]
I'm use Samsung Galaxy Note9 and LG V50s, however, there is a problem that the image output is small on all devices.

The Android version of the V50s is 11, and firefox version is Nightly 100.0a1(2015867883).
![Screenshot_20220310-193934](https://user-images.githubusercontent.com/70040738/157645603-642ade55-45d1-4206-af1f-af73bd264f5e.png)

96.0.3 (Iceraven)
![Screenshot_20220310-193438](https://user-images.githubusercontent.com/70040738/157645948-9be0f028-e1a5-4daa-9b28-681a28424b06.png)

**Comment by Kafu-Yukimura** [comment]
The resolved in 100.0.10. (Tested Xperia PRO-I / Android 12)
