### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mohiuddinofficial** [mozilla-mobile/fenix#24011]
hello Sir, 
i found a bug on your Android Regular latest version.
Bug: this problem is your address bar.
When we type a address and press go, Your address bar show your older version lock/security icon and then show latest version security icon.
That's mean, your Firefox team don't properly clean the older version security icon. It's behind your older version "connection secured icon"

please solve this bug

**Comment by kbrosnan** [comment]
Sounds like a duplicate of https://github.com/mozilla-mobile/fenix/issues/14172
