### ISSUE TITLE
Set private browsing default search engine

### ISSUE THREAD

**Issue by santo998** [mozilla-mobile/fenix#24021]
I would like to set a default private browsing search engine, instead of using the default one.
e.g.: i would like to set Google as my main search engine, but if i open a private browsing tab, then have DuckDuckGo as my default search engine.

I need this, because its annoying every time i open a private browsing tab, having to switch my search engine. So this would make my life easier in private browsing.

I use Google as main search engine for convenience, but in private browsing i use DuckDuckGo for more privacy.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19671)

**Comment by santo998** [comment]
is there any news about this?

**Comment by santo998** [comment]
@badboy @badboy @eeejay is this closed as solved or by inactivity?

**Comment by badboy** [comment]
@santo998 Please avoid tagging random people. Bugs get triaged by the responsible teams. If there's no update in the bug then there's no update. As there's no linked other bug or PR you can probably assume that it's not being worked on.
