### ISSUE TITLE
[Bug]: Only default camera app choosable since Android 11 for external cameras/files

### ISSUE THREAD

**Issue by rugk** [mozilla-mobile/fenix#24029]
### Steps to reproduce

1. Go to a website that just triggers an intent to open files/only images/open the camera. E.g. I can reproduce this with the default file picker example on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file (Note that it has to include at least one image MIME type)
2. You cannot actually set the app as the default app for the camera or even choose it when such an intend is sent/other app requests pictures.

### Expected behaviour

One should be able to choose all common camera apps.

### Actual behaviour

 It e.g. looks like this (you can only choose one app):
  ![camer-app-selection](https://user-images.githubusercontent.com/11966684/156040484-caf78f62-73be-46d1-ad0e-d2d79cc0e62f.png)

### Device name

PIxel 4

### Android version

Android 12
CalyxOS 3.2.0

### Firefox release type

Firefox

### Firefox version

97.2.0

### Device logs

N/A

### Additional information

I've reported this to the camera apps like https://github.com/SimpleMobileTools/Simple-Camera-Abandoned/issues/310 or [OpenCamera](https://sourceforge.net/p/opencamera/discussion/qa/thread/9b0292b70d/) and other affected apps (https://github.com/k3b/CameraFolder/issues/5).
Apparently, the issue is however an Android one related to how [camera apps are handled since Android 11](https://www.theverge.com/2020/8/20/21376391/google-android-11-third-party-camera-picker-intents). See 
See https://www.xda-developers.com/android-11-blocks-third-party-camera-apps-appearing-image-video-picking-intents/

In case I understood it correctly, the calling app needs to **whitelist** all the camera apps it wants the user to be able to choose.

So could we go [though F-Droid](https://search.f-droid.org/?q=camera) at least and whitelist all good/known camera apps?

I'd specifically suggest these:
* [OpenCamera](https://f-droid.org/packages/net.sourceforge.opencamera/) aka `net.sourceforge.opencamera`
* [SimpleCamera](https://f-droid.org/de/packages/com.simplemobiletools.camera/) aka `com.simplemobiletools.camera`  (even though deprecated, may still be useful for those who still use and like it, like me)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19676)

**Comment by k3b** [comment]
By reading https://commonsware.com/blog/2020/08/16/action-image-capture-android-r.html i found this kotlin implementation:

https://gitlab.com/commonsguy/cw-android-r/-/blob/v0.3/CamChooser/src/main/java/com/commonsware/android/r/camchooser/CameraIntent.kt

in f-droid and izzy repository i found these potential camera apps:

    private static final String[] AO10_ADDITIONAL_KNOWN_CAMERA_APPS = new String[] {
            "net.sourceforge.opencamera", // https://sourceforge.net/p/opencamera/code
            "com.simplemobiletools.camera", // https://github.com/SimpleMobileTools/Simple-Camera
            "com.flipcamera", // https://bitbucket.org/kingsimmy/frontcamera/src
            "org.witness.sscphase1", // https://github.com/guardianproject/ObscuraCam
            "com.lun.chin.aicamera", // https://bitbucket.org/chlun/aicamera
            "com.lightbox.android.camera" , // https://github.com/lightbox/QuickSnap
    };

my (untested) java implementation from https://github.com/k3b/CameraFolder/issues/5 can be found here:

https://github.com/k3b/CameraFolder/blob/master/app/src/main/java/de/k3b/android/camerafolder/GetDocument2CameraActivity.java

**Comment by k3b** [comment]
unfortunately my whitelisting code does not work on android11 :-(.

I have created a [stackoverflow question](https://stackoverflow.com/questions/71338593/action-image-capture-how-to-whitelist-a-different-camerapp-in-android-11-and-la) for this with a bounty but there was no reply yet :-(

**Comment by rugk** [comment]
Hmm yeha, I am no Android dev either. However, here is another camera you may add, as it is quite famous: Google Camera: https://play.google.com/store/apps/details?id=com.google.android.GoogleCamera&gl=us

(It can apparently also be used on some CustomROMs with microG or so)

**Comment by rugk** [comment]
It is still valid…
