### ISSUE TITLE
Bad contrast in search widget.

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#24020]
### Steps to reproduce

1. In dark mode, use the search widget.

### Expected behaviour

Microphone icon should be visible.

### Actual behaviour

It's barely visible.

### Device name

One Plus 9

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build #2015865579), 12efddd64+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19670)

**Comment by emilio** [comment]
Screenshot:

![Screenshot_2022-02-28-01-26-59-76_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/1323194/155906690-0de6e7e5-0496-45e6-844d-97de403fe96a.jpg)

**Comment by gabrielluong** [comment]
@emilio I have not been able to reproduce this. Can you let me know if you are still experiencing this with the latest nightly?

**Comment by emilio** [comment]
@gabrielluong I can still repro with the latest Nightly. It also reproduces in Release and Beta.

**Comment by emilio** [comment]
If there's anything you want me to try to assist with debugging I'm happy to poke, even if it involves building Fenix.

**Comment by emilio** [comment]
Light mode:

![Screenshot_2022-03-02-00-15-19-85_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/1323194/156264855-9ae91786-ab07-4cc7-a6ad-e556555ca233.jpg)

Dark mode:

![Screenshot_2022-03-02-00-14-32-53_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/1323194/156264884-e7dc3ca2-9da3-4756-9f15-3bd149cef7d5.jpg)

**Comment by gabrielluong** [comment]
Thanks! This just confirms to me that it's not fully due to our recent change in https://github.com/mozilla-mobile/fenix/issues/23900. However, the color change did make it slightly more visible now.

**Comment by gabrielluong** [comment]
We got an initial idea on how to approach a fix.

**Comment by jonalmeida** [comment]
> We got an initial idea on how to approach a fix involving switching ImageButton to AppCompatImageView

There is an [`AppCompatImageButton`](https://developer.android.com/reference/androidx/appcompat/widget/AppCompatImageButton) as well that I didn't realize existed as well and will probably be easier.

**Comment by AdinaPetridean** [comment]
This issues is also reproducible on Firefox  Nightly 106.0a1 09/12, Firefox Beta 105.0b6 and Firefox RC 104.2.0 build2 with OnePlus 9 PRO 5G device. 

![Widget](https://user-images.githubusercontent.com/108326843/189600045-cd323981-a759-4a36-9fa3-1c47099a23cf.JPEG)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813737

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
