### ISSUE TITLE
Search/URL field cleared when rotating the device.

### ISSUE THREAD

**Issue by jyavenard** [mozilla-mobile/fenix#2402]
Press the button in the bottom right corner to open a new tab or perform a new search.

Start typing text. Rotate the device.

What happens:
The text field is cleared.

What should happpen:
The text field isn't cleared and the data entered so far is still there.

* Android device: ? Samsung S8
* Fenix version: ? 1.0.1919

**Comment by dector** [comment]
Probably duplication of #1198.

**Comment by bsurd** [comment]
@dector is right, closing this as it has been addressed there.
