### ISSUE TITLE
Closed tabs reappear when reopen app

### ISSUE THREAD

**Issue by santo998** [mozilla-mobile/fenix#24034]
### Steps to reproduce

Open Firefox with some open tabs.
Close some of those tabs and close the app inmediately.
Reopen the app

### Expected behaviour

The closed tabs are gone

### Actual behaviour

The closed tabs reappear

### Device name

Samsung J7 Prime

### Android version

Android 8.1

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

If i have 5 open tabs and close one of them, usually it works ok...

Having 15 open tabs (like now) the problem usually arises...

With 50 open tabs or more, the problem happens almost always.

So, the problem seems to be related to open tabs quantity and the time it takes to persist / sync closed tabs state.
Maybe related to app performance, device performance, or sync issues...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19678)

**Comment by LaviniaL99** [comment]
Hello @santo998 

Thank you for your report!

I verified the flow on the **latest Nightly build** (99.0a1 -Build#2015866347) and i was not able to reproduce the issue. The tabs remain deleted after the app is reopened-> verified with 5, 15, 50, more than 50 opened tabs.

**Device used:**
- Samsung S10E->Android 10

Can you please retest with the latest Nightly build and let me know if you are still able to reproduce the issue? If so, can you please attach a video of the interest flow?

Thanks!

**Comment by santo998** [comment]
Hello @LaviniaL99 

Sorry for keep you waiting.

Here is a video where i reproduce the issue:

https://user-images.githubusercontent.com/15607273/157303281-0c738ad8-a40e-4e51-b02f-0c3d4105ab82.mp4

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1381122

**Comment by davidrpk** [comment]
I get this issue as well on a Samsung Galaxy A70 with
103.0.0-beta.3 (Build #2015890891), 4e393a923+
AC: 103.0.5, d366e1a3db
GV: 103.0-20220707185904
AS: 93.5.0

**Comment by sfk90** [comment]
This issue is open for months. So now I am using Chrome. Thanks:(

**Comment by ShubhamTariyal** [comment]
Same issue on Samsung m31s Android 12, One UI Core Version 4.1 with Firefox version 106.1.0.

**Comment by echuber2** [comment]
I commented on the duplicate issues about this already, but when I had the same issue, I thought it was partly my fault for having too many tabs open. Now I see from the comments here that it affects those with very few tabs open, too. There's probably a fundamental error in how FF is serializing the session store when the app goes to sleep. (To be honest, I also had to give up and switch to Brave. The app simply isn't usable if tabs cannot stay closed.)

**Comment by santo998** [comment]
@amedyne any clue on this?

**Comment by vehosah** [comment]
> Hello @santo998
> 
> Thank you for your report!
> 
> I verified the flow on the **latest Nightly build** (99.0a1 -Build#2015866347) and i was not able to reproduce the issue. The tabs remain deleted after the app is reopened-> verified with 5, 15, 50, more than 50 opened tabs.
> 
> **Device used:**
> 
>     * Samsung S10E->Android 10
> 
> 
> Can you please retest with the latest Nightly build and let me know if you are still able to reproduce the issue? If so, can you please attach a video of the interest flow?
> 
> Thanks!

Everyone else can produce the issue except you :)

**Comment by vehosah** [comment]
Can we please have an update at least :)

**Comment by vehosah** [comment]
> This issue is open for months. So now I am using Chrome. Thanks:(

I have this damn issue for years :)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812858

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by santo998** [comment]
@boek why closing?
I dont think this is solved yet...

**Comment by echuber2** [comment]
> why closing? I dont think this is solved yet...

It appears that they have internal procedures to move bugs from here to Bugzilla. You can follow the issue over there.
