### ISSUE TITLE
FNX3-16297 ⁃ [Bug] Camera and microphone permission request should default to unchecked "Remember my decision"

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#2403]
## Steps to reproduce
1. In Fenix, open https://voice.mozilla.org/speak
1. Click the :microphone: symbol to begin recording
1. Allow Firefox permission to record audio (if necessary)
1. Observe permission request: "voice.mozilla.org wants to use your microphone"

### Expected behavior
`☐ Remember this decision` should be unchecked by default.

### Actual behavior
`☑ Remember this decision` is checked by default.

This is inconsistent with other Firefox products and our policy thus far on camera and mic permissions, and is worse on privacy.

Persistent permissions give sites carte blanche to spy on users in the future without their knowledge.

Additionally, ☑ raises the UX stakes on both "Allow" and "Deny", the latter blocking web sites permanently by default, which may be unintentional and hard to recover from without a control center. Fenix appears to have no prominent indicators or control center to handle the demands of a "persistent by default" permission model.

This bug was originally filed in Bugzilla by @jan-ivar, but this is not a GV bug. Fenix is responsible for showing the permission UI and remembering permission decisions.

https://bugzilla.mozilla.org/show_bug.cgi?id=1549644

**Comment by dector** [comment]
[Please advice}(https://github.com/mozilla-mobile/android-components/issues/2988) about proper solution.

**Comment by Amejia481** [comment]
Thanks for taking this @dector  I've already replied on https://github.com/mozilla-mobile/android-components/issues/2988

**Comment by sv-ohorvath** [comment]
Verified the checkbox is off by default, checking it adds the exceptions. Not checking it, will not create exceptions.
