### ISSUE TITLE
Voice search should not be possible in PIP

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24037]
Prerequisites:
Have the search widget added to homescreen

STRs:
- open a new tab for a video, enter fullscreen, enter PIP
- tap the microphone on the search widget

Expected result:
- the app opens showing the voice search UX in it's entirety

Actual result:
- the voice search starts while in pip, the layout does not fit
- upon returning to the app the layout is broken

https://user-images.githubusercontent.com/11428869/156131387-a8d76b24-5f18-4d5e-a0dc-b1d3d73928b0.mp4

**Comment by indurs** [comment]
@Mugurell , can I explore this issue?

**Comment by Mugurell** [comment]
> @Mugurell , can I explore this issue?

Would be awesome to. Thank you!

**Comment by indurs** [comment]
Sure. Thank You..

**Comment by indurs** [comment]
@Mugurell , after adding taskAffinity="" for VoiceSearchActivity, voice search can be displayed in a separate window.

        <activity android:name=".widget.VoiceSearchActivity"
            android:theme="@style/Theme.AppCompat.Translucent"
            android:taskAffinity=""
            android:excludeFromRecents="true"/>
From android documentation

In your manifest, add the following attributes to the [<activity>](https://developer.android.com/guide/topics/manifest/activity-element) element.

[android:taskAffinity](https://developer.android.com/guide/topics/manifest/activity-element#aff)=""
    Combined with the [FLAG_ACTIVITY_NEW_TASK](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_NEW_TASK) flag that you'll use in code, setting this attribute blank ensures that this activity doesn't go into the app's default task. Any existing tasks that have the app's default affinity are not affected.

So after adding taskAffinity=""

https://user-images.githubusercontent.com/12825812/158010443-15fa5641-ef40-45bd-b5ca-2c140d8db3b4.mp4

**Comment by Mugurell** [comment]
> @Mugurell , after adding taskAffinity="" for VoiceSearchActivity, voice search can be displayed in a separate window.

This seems like a nice way of excluding the `VoiceSearchActivity` opening in the existing PIP UX. 
`excludeFromRecents` is a nice addition also 👍

**Comment by indurs** [comment]
Thank You @Mugurell !!

**Comment by indurs** [comment]
@Mugurell , shall I open a PR for this issue?

**Comment by indurs** [comment]
@Mugurell , even though I modified only AndroidManifest.xml, github desktop shows that AndroidManifest.xml and experimentor.json have changed. I should not commit experimentor.json right?

**Comment by Mugurell** [comment]
> @Mugurell , even though I modified only AndroidManifest.xml, github desktop shows that AndroidManifest.xml and experimentor.json have changed. I should not commit experimentor.json right?

Indeed, changes to `experimenter.json` should not be commited.

**Comment by indurs** [comment]
Ok. Thank You

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-18-03. When voice search is used while a PiP video is playing the video will be paused and a new tab with the search results is opened.
### Device used:
- Google Pixel 6 (Android 12)

https://user-images.githubusercontent.com/50983519/159010348-9da793ae-bd69-45e2-ae01-b63e7115877e.mp4
