### ISSUE TITLE
Firefox on Android not deleting data on quit reliably[Bug]: 

### ISSUE THREAD

**Issue by Ghostily-Boo** [mozilla-mobile/fenix#24044]
### Steps to reproduce

1. Log in to a site or play wordle
2. Click 'quit' in the three dots menu or quit from Android
3. Go back to previous site

### Expected behaviour

The site should be logged out or wordle should be blank

### Actual behaviour

Site is still logged in or your previous wordle game is still there

### Android version

12

### Firefox release type

Firefox

### Firefox version

97.2.0

### Additional information

Quitting repeatedly eventually deletes the data so it works sometimes

**Comment by sflorean** [comment]
Thank you for report! Please follow #11467, where the same issue is described.
