### ISSUE TITLE
FNX3-16299 ⁃ [Bug] [Crash]: Open a link from external apps while in split screen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2405]
## Steps to reproduce
1. On an Android 8 or higher (which support split-screen mode), open Fenix and play a youtube/other video.
1. From task tray, put Fenix in split screen with another app.
1. Open a link from the second app into Fenix.
    1. Expected behavior
Link is sent to Fenix.
    1. Actual behavior
Fenix crashes.
[recording](https://drive.google.com/file/d/1whecHaJnSqZOr7nbYCgGUrQPj2v_ahWf/view?usp=sharing)
[logcat](https://github.com/mozilla-mobile/fenix/files/3165709/splitscreen.crash.txt)

### Device information
* Android device: Pixel, OnePlus 5T (Android 9)
* Fenix version: 5/10

**Comment by sv-ohorvath** [comment]
The crash reporter freezes sometimes after this crash, can't close/restart the app.
After restarting the app from this crash, there are 2 app instances open. Check the recent apps tray.

**Comment by ekager** [comment]
Are you still able to reproduce this?

**Comment by sv-ohorvath** [comment]
Yes, it's still reproducing on Nightly 7/16. devices: Huawei p20 lite, Pixel 3A (Android 9)

**Comment by NotWoods** [comment]
I wasn't able to reproduce on the latest version (Sony Xperia XZ1)

**Comment by sv-ohorvath** [comment]
Doesn't reproduce on Pixel 3(Android 9), OnePlus 5T (Android 9), Pixel (Android Q).
