### ISSUE TITLE
[Bug]: The text selector handle disappears in address bar 

### ISSUE THREAD

**Issue by Xashyar** [mozilla-mobile/fenix#24058]
### Steps to reproduce

**Disclaimer:** This issue happens so randomly, but this is the only 100% repro step I've found so far.

1. Open a new tab
2. Start by searching (e.g. "best" so it would provide you with auto-complete results):
<img src="https://user-images.githubusercontent.com/34171942/156310361-c98b38ed-ed4c-484e-aea8-b2e68b0a4aa4.png" width=30% height=30%>

3. Remove the already-selected, auto-suggested text (e.g. "buy.com") without touching the address bar and only using the backspace on the keyboard
4. Notice how the handle won't appear anymore when you select the text:
<img src="https://user-images.githubusercontent.com/34171942/156311088-b51de175-bbe6-4dfc-93de-1514316a545d.png" width=30% height=30%>

### Expected behaviour

How the handle should normally appear when you select the text:

<img src="https://user-images.githubusercontent.com/34171942/156311647-6bd0c2b1-2e22-4721-a53e-66b30bdd78b6.png" width=30% height=30%>

### Actual behaviour

The text selector handle doesn't appear making it hard to navigate the text.

### Device name

Huawei ALE-L21

### Android version

Android 6.0

### Firefox release type

Firefox Beta

### Firefox version

98.0.0-beta.4 (Build #2015865235)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19696)

**Comment by LaviniaL99** [comment]
Hello @Xashyar 

Thanks for your report!
I retested the flow multiple times on the **latest Nightly build** (99.0a1 -Build#2015866347) and **latest Beta build** (98.0.0-beta.4 -Build #2015865235) and i was not able to reproduce the issue.

**Device used:**
- Samsung S10E (Android 10)

**Comment by kbrosnan** [comment]
Are you using a RTL language? If so which one? What specific Android 6 device are you using?

**Comment by Xashyar** [comment]
@kbrosnan, Yes, but the issue is reproducible independent of what language you are using. It also happens with LTR.

Also updated the issue to reflect the device model.
