### ISSUE TITLE
FNX3-16301 ⁃ [Bug] Can't scroll the homescreen while in split-screen mode

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2407]
## Steps to reproduce
1. On an Android 8 or higher (which support split-screen mode), open Fenix and view the homescreen.
1. From task tray, put Fenix in split screen with another app.
1. Try to scroll down from the top half, to the tabs view.
    1. Expected behavior
Can scroll on the homescreen to view the tabs.
    1. Actual behavior
Can't scroll down from the top half. Can scroll only if the tabs are visible.
    1. Device information

* Android device: Pixel
* Fenix version: 5/10 build

**Comment by sblatz** [comment]
@sv-ohorvath I believe this is fixed. Marking as QA needed :)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly **Build #11980613 from 17/7** using the following devices:
• Google Pixel 3a (Android 9)
• Samsung Galaxy S8+ (Android 8)
• Huawei Mate 20 Lite (android 8.1.0)

►Video from Google Pixel 3a

![20190717_104435](https://user-images.githubusercontent.com/51314259/61357014-231e9d80-a880-11e9-9ea2-ac6d3e324085.gif)
