### ISSUE TITLE
insights

### ISSUE THREAD

**Issue by AroKol78** [mozilla-mobile/fenix#24077]
Hello
fenix 98.1.0
- no favicon on `https://www.google.pl/`and on most websites
- no dark theme on the pages `https://www.google.pl/` `https://www.google.com/`
- if I go to the site `https://www.google.com/` normally the address is correct
and if "add to top sites" then the address `https://www.google.com/webhp?client=firefox-b-m&channel=ts`
there is no such problem with `https://www.google.pl/`
- on youtube it lowers the quality of the video after a certain viewing time when it is automatic - every time I have to set the quality to hard (i do not have such a problem, e.g. on "kiwibrowser")
- is it possible to disable the opening of new tabs with bookmarks/history

**Comment by kbrosnan** [comment]
This has multiple reports and parts of it are support questions.
