### ISSUE TITLE
no favicon

### ISSUE THREAD

**Issue by AroKol78** [mozilla-mobile/fenix#24083]
fenix 98.1.0
no favicon on `https://www.google.pl/` and on most websites

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19715)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-05-11.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
