### ISSUE TITLE
No dark theme for https://www.google.com/ website

### ISSUE THREAD

**Issue by AroKol78** [mozilla-mobile/fenix#24084]
fenix 98.1.0
no dark theme on the pages `https://www.google.pl/` `https://www.google.com/`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19714)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-03-30.

### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
