### ISSUE TITLE
[Bug]: Sponsored shortcuts icon loading are delayed

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#24093]
### Steps to reproduce

1. Have the Sponsored shortcuts feature enabled.
2. Go to homepage and observe the Sponsored shortcuts icon.

### Expected behaviour

The Sponsored shortcuts icons are loaded without delay along with the pinned ones.

### Actual behaviour

The Sponsored shortcuts icons loading is delayed.

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

https://user-images.githubusercontent.com/48829350/156722453-a853d91c-4387-4556-986d-856162cd31e6.mp4

1.0.2210 (Build 1)
AC: 99.0.20220228143604,
5330648f35
GV: 99.0a1-20220228090129
AS: 91.1.0
debud build

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19720)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 109.0a1 (2022-11-23) build.
Device used: Oppo Find X5 (Android 12).

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813644

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
