### ISSUE TITLE
[Bug]: Sponsored shortcuts feature is active with non-targeted region set

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#24096]
### Steps to reproduce

1. Have the Sponsored shortcuts feature enabled.
2. Close the browser.
3. Have a VPN set to a non-targeted region (Ex: RO).
4. Restart the browser and observe the Sponsored shortcuts.

### Expected behaviour

The Sponsored shortcuts feature is disabled.

### Actual behaviour

The Sponsored shortcuts feature is enabled.

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Additional information

https://user-images.githubusercontent.com/48829350/156723820-51cefa87-296d-490f-b637-6f30bb64f945.mp4

1.0.2210 (Build 1)
AC: 99.0.20220228143604,
5330648f35
GV: 99.0a1-20220228090129
AS: 91.1.0
debud build

**Comment by gabrielluong** [comment]
This toggle is always enabled on desktop even for non-targeted region. Closing as WONTFIX.
