### ISSUE TITLE
Remove wrapper for Collections telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24099]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-04 by performing operations with collections observing the events that are generated.
Track share button
{
          "timestamp": 124439,
          "category": "collections",
          "name": "shared"
        }

Track "Add tab" to existing collection from 3dot button Ping
{
          "timestamp": 5649,
          "category": "collections",
          "name": "tabs_added",
          "extra": {
            "tabs_selected": "1",
            "tabs_open": "8"
          }

Track Rename collection from 3dot button
{
          "timestamp": 5610,
          "category": "collections",
          "name": "rename_button"
        },

 {
          "timestamp": 9744,
          "category": "collections",
          "name": "renamed"
        }

Track Open tabs from 3dot button Ping
 {
          "timestamp": 9744,
          "category": "collections",
          "name": "renamed"
        }




Add to existing collection
{
          "timestamp": 48956,
          "category": "collections",
          "name": "tabs_added",
          "extra": {
            "tabs_selected": "1",
            "tabs_open": "4"
          }

Select tabs
{
          "timestamp": 140662,
          "category": "tabs_tray",
          "name": "selected_tabs_to_collection",
          "extra": {
            "tab_count": "3"
          }

Save to a new collection
{
          "timestamp": 140662,
          "category": "tabs_tray",
          "name": "selected_tabs_to_collection",
          "extra": {
            "tab_count": "3"
          }

Track Delete collection from 3dot button

Track tap x to delete individual tab from 3dot button Ping
{
          "timestamp": 18208,
          "category": "collections",
          "name": "tab_removed"
        }

No ping was registered when deleting a collection, I have submitted a separate issue regarding this: https://github.com/mozilla-mobile/fenix/issues/24576

[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-0404)
### Device used:
- OnePlus 6T (Android 9)
