### ISSUE TITLE
Remove wrapper for Tabs Tray telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24098]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2020-30-03 by testing the following tabs tray interaction and inactive tabs interactions:
Tabs tray interactions and the events these interaction ganerate:

Opening the tray
{
          "timestamp": 8699,
          "category": "tabs_tray",
          "name": "opened"
        },

Opening an existing tab
{
          "timestamp": 27583,
          "category": "tabs_tray",
          "name": "opened_existing_tab",
          "extra": {
            "source": "Tabs tray"
          }

Closing an existing tab
{
          "timestamp": 5937,
          "category": "tabs_tray",
          "name": "closed_existing_tab",
          "extra": {
            "source": "Tabs tray"
          }

Switching to private browsing
{
          "timestamp": 31416,
          "category": "tabs_tray",
          "name": "private_mode_tapped"
        },

Switching to normal browsing
{
          "timestamp": 32539,
          "category": "tabs_tray",
          "name": "normal_mode_tapped"
        },

New tab button pressed
{
          "timestamp": 33467,
          "category": "tabs_tray",
          "name": "new_tab_tapped"
        },

New private tab button pressed
{
          "timestamp": 9032,
          "category": "tabs_tray",
          "name": "new_private_tab_tapped"
        },
3 dot menu opened
{
          "timestamp": 3273,
          "category": "tabs_tray",
          "name": "menu_opened"
        },

Bookmark sites from tab tray
{
          "timestamp": 43421,
          "category": "tabs_tray",
          "name": "bookmark_selected_tabs",
          "extra": {
            "tab_count": "2"
          }

Tab tray dismissed (by swiping down)

save to collection
{
          "timestamp": 21403,
          "category": "tabs_tray",
          "name": "save_to_collection"
        },
share all tabs
{
          "timestamp": 13316,
          "category": "tabs_tray",
          "name": "share_all_tabs"
        }
close all tabs
{
          "timestamp": 6853,
          "category": "tabs_tray",
          "name": "close_all_tabs"
        },


Inactive tabs

Whether the inactive tab section is showing & the count of inactive tabs
{
          "timestamp": 284,
          "category": "tabs_tray",
          "name": "has_inactive_tabs",
          "extra": {
            "inactive_tabs_count": "5"
          }

Expand / collapse the inactive tabs
{
          "timestamp": 4802,
          "category": "tabs_tray",
          "name": "inactive_tabs_expanded"
        },

        {
          "timestamp": 7165,
          "category": "tabs_tray",
          "name": "inactive_tabs_collapsed"
        },
Opening an inactive tab:
{
          "timestamp": 5108,
          "category": "tabs_tray",
          "name": "opened_existing_tab",
          "extra": {
            "source": "Inactive tabs"
          }
Deleting/closing a single inactive tab
{
          "timestamp": 9416,
          "category": "tabs_tray",
          "name": "closed_existing_tab",
          "extra": {
            "source": "Inactive tabs"
          }

Deleting/closing all inactive tabs
{
          "timestamp": 21987,
          "category": "tabs_tray",
          "name": "close_all_inactive_tabs"
        }

### Device used:
- OnePlus 6T (Android 9)

**Comment by mcarare** [comment]
Closing as verified per the above comment.
