### ISSUE TITLE
[Bug]: [Sponsored shortcut] Our Sponsors & your privacy page - No specific mobile data is displayed

### ISSUE THREAD

**Issue by LaviniaL99** [mozilla-mobile/fenix#24097]
### Steps to reproduce

1. Navigate to Settings -> Homepage and enable the "Sponsored shortcuts" functionality
2. Set the VPN to a targeted region (e.g: US)
3. Verify if the sponsored shortcuts are displayed on the top sites list
4. Long tap on a sponsored tile and tap on "Our sponsors & your privacy" option
5. Verify if the information available on the page are mobile specific

### Expected behaviour

Our sponsors & your privacy page must contain the mobile specific information.

### Actual behaviour

Our sponsors & your privacy page is not displaying the mobile specific information, e.g:
- "How to delete a specific sponsored tile" section -> the screenshot and the information available are not applicable for mobile.
- "How to disable the feature" section -> the information available are not applicable for mobile.

Please see the screenshots attached for reference.

### Device name

Samsung S10E

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build #2015866635)

### Additional information

![Contile](https://user-images.githubusercontent.com/96047134/156758576-9385f1a8-21cf-4321-b638-c814b195887c.JPEG)

![Contile1](https://user-images.githubusercontent.com/96047134/156758613-b8027bda-9a70-4740-a881-54ce7de8b472.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19723)

**Comment by lwa-moz** [comment]
SUMO will be making an update to the existing article this Friday, March 18.

**Comment by lwa-moz** [comment]
SUMO has completed their update. Closing this out.

**Comment by yoasif** [comment]
I think this article needs to be split, because I attempted to "dismiss" a shortcut because I missed the word "desktop" in "You can disable a specific sponsored shortcut on desktop by taking the following steps: ". Too easy to miss.
