### ISSUE TITLE
Addon popup pages on android do not load iframes

### ISSUE THREAD

**Issue by MGibson1** [mozilla-mobile/fenix#24118]
Android addons do not properly load iframes in popup pages

### Steps to reproduce

1. unzip minimal example: [iframe-issue.zip](https://github.com/mozilla-mobile/fenix/files/8193885/iframe-issue.zip)
2. Build and load the addon onto an android emulator running firefox:
  ```bash
  web-ext run -t firefox-android --android-device=emulator-5554 --firefox-apk org.mozilla.firefox                                                       
  ```
3. On the host machine, Connect to the main window's dbug network tab
4. On the sim, Navigate to the addon popup page
5. On the sim, Observe iframe does not load
6. On the host machine, Observe that the iframe element's initial `GET` request occurs, but not subsequent css or js requests occur

### Expected behaviour

The iframe should be fully loaded as a regular webpage and presented to the user.

### Actual behaviour

Initial `GET` request, but no further iframe processing.
UI presents as an blank element.

### Device name

Pixel 3A

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

97.2.0

### Additional information

# Missing iframe content
<img width="369" alt="image" src="https://user-images.githubusercontent.com/18214891/156948837-15fde7d6-d66c-4ef7-b170-173882bb041d.png">

# Debugging main process
No iframe content is loaded.
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/18214891/156948890-8119a7b3-3736-4fa7-91eb-15a15137fd60.png">

# Approximate expected network activity
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/18214891/156948926-b8a4bd8b-ff6c-4cd6-b030-89883a7308b9.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19743)

**Comment by kspearrin** [comment]
Not stale

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810600

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
