### ISSUE TITLE
'Sign in to sync' browser menu item displayed when account is in AuthenticationProblem state

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#24112]
See screenshot. If the account is in "needs recovery" state (for example, password was changed remotely), we currently correctly display "Reconnect to Sync" item, but we incorrectly also display a "Sign in to sync" item right above it.

Also, note that capitalization of "Sync" is inconsistent - it should be capitalized.

![image](https://user-images.githubusercontent.com/465422/156852999-28b8a042-b3cb-4900-9080-ba40ba53c579.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19739)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Do you mean that it should not be capitalised?
