### ISSUE TITLE
[Bug]: Pull to refresh does not work in all parts of website

### ISSUE THREAD

**Issue by robovoice1** [mozilla-mobile/fenix#24117]
### Steps to reproduce

1. Go to https://commonvoice.mozilla.org/en
2. swipe down to refresh main page (works as expected)
3. Tap on the 3 dots (top right) of website
4. choose contribute 
5. swipe down to refresh speak page (not working)
6. choose listen and swipe down to refresh (not working)
7. Refreshing speak/listen page was possible before!

### Expected behaviour

With pull to refresh enabled, all parts of the website can be refreshed

### Actual behaviour

Refreshing speak/listen page by swiping down not possible

### Device name

Google Pixel 6 pro

### Android version

Android 12 GrapheneOS

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1 (Build #2015866923), ded426692+

### Device logs

NONE

### Additional information

https://user-images.githubusercontent.com/92784377/156881423-d2a2d928-1c6b-4a97-99e1-a6699be23948.mp4

I tested this also with latest vanadium browser.
Refreshing speak listen page is possible by swiping down.(so this is not cv related)

I can remember this was also possible in nightly a few updates before!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19742)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-18-03.

### Devices used:
- Google Pixel 6 (Android 9)
- OnePlus 6T (Android 9)
