### ISSUE TITLE
FNX3-16303 ⁃ [Bug] private mode shows tabs from normal mode

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#2411]
## Steps to reproduce
Open one or more tabs in normal mode
Switch to private mode

### Expected behavior
no tabs are shown in private mode

### Actual behavior
Tabs from normal browsing mode are shown in private mode

### Device information
* Android device: Samsung Galaxy Tab SM-T580, Huawei P smart 
* Fenix version: 1.0.1919 (11300607) 5/10

![Screenshot](https://user-images.githubusercontent.com/44252450/57533191-77b41280-733d-11e9-899f-d71f623c530c.jpg)UNITO-UNDERSCORE!20190510-160116!UNITO-UNDERSCORE!Firefox Preview!
![Screenshot](https://user-images.githubusercontent.com/44252450/57533205-7e428a00-733d-11e9-8aad-66f9cf0fbcc9.jpg)UNITO-UNDERSCORE!20190510-160125!UNITO-UNDERSCORE!Firefox Preview!

**Comment by cadeyrn** [comment]
@colintheshots It's a regression of your PR #2382.

**Comment by LittleAngelwings** [comment]
it's still there in nightly (11310606)

**Comment by LittleAngelwings** [comment]
Issue fixed: https://github.com/mozilla-mobile/fenix/pull/2457
