### ISSUE TITLE
[Bug]: many tab crash lately

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#24125]
### Steps to reproduce

going back and forward on this url after sometimes makes tab crash
url :https://www.subito.it/annunci-piemonte/vendita/telefonia/?from=top-bar
log show this error :
"MOZ_DIAGNOSTIC_ASSERT(!mWhen.IsNull())","Notes":"FP(D00-L1010-W00000100-T000) WR! WR+ "

### Expected behaviour

tab should not crash

### Actual behaviour

tab crash

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

99

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19747)

**Comment by csadilek** [comment]
Thanks for reporting. Can you share crash info from about:crashes (or Settings->About Nightly->Crashes)?

This looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1753002 which should be fixed in latest Nightly.
