### ISSUE TITLE
[Bug]: Web notifications don't work properly in Firefox for Android

### ISSUE THREAD

**Issue by osunick** [mozilla-mobile/fenix#24139]
### Steps to reproduce

Use any site that does a web notification (like teslamotorsclub.com) and subscribe to an active thread. Notifications appear but do not open the website when tapped, they just open Fx.

### Expected behaviour

Open https://cleverpush.com/en/test-notifications/ and subscribe to a topic notification. Close all tabs and change to another app. Notification appears and opens the browser but just to the start page.

### Actual behaviour

App just opens.

### Device name

Samsung Galaxy Z Flip 3 5G

### Android version

12

### Firefox release type

Firefox

### Firefox version

98.1.1

-------
Needed functionality:
[x] clicking notifications with the app opened will navigate to a new tab - verified in https://github.com/mozilla-mobile/fenix/issues/24618#issuecomment-1101576771
[ ] clicking notifications with the app closed will navigate to a new tab - needs https://bugzilla.mozilla.org/show_bug.cgi?id=1762032

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19754)

**Comment by LaviniaL99** [comment]
Hello @osunick 

Thanks for your report!

I retested the above flow on the latest Nightly build (100.0a1) and latest RC build (99.1.0) and i was not able to reproduce the issue.

**Device used:**

- Samsung S10E - Android 10

Can you please retest the issue on the latest builds and verify if you are still able to reproduce the above flow? If yes, please attach a video of it.

**Comment by Mugurell** [comment]
Updated the initial comment with details on the progress.

**Comment by redbob365** [comment]
My smartphone is Android Xiaomi Redmi 9t and Firefox does exactly this way! This issue is not solved at all. FF release 109.2.0
