### ISSUE TITLE
Referer is leaked when opening private tab from non-private tab

### ISSUE THREAD

**Issue by aplaice** [mozilla-mobile/fenix#24135]
### Steps to reproduce

1. Have this issue page open in Firefox for Android (Fenix).
2. Long-press https://referer.rustybrick.com/ and select "Open link in private tab".
3. Open in "Desktop site" view. (This is not part of the bug, it's just necessary for the relevant data to be visible.)

(https://referer.rustybrick.com/ was the first public website that displays referers, that I could find, that actually worked, and did not look dodgy, though the UI is pretty terrible on mobile. https://anonymiz.com/myreferer also seems to work, but looks mildly suspicious.)

### Expected behaviour

"No referer." is displayed, as the referer.

### Actual behaviour

"https://github.com" is displayed, as the referer.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

97.3.0

### Additional information

(Also tested on latest Firefox nightly (99.0a1).)

This is a minor privacy issue. Testing with desktop Firefox and mobile chrome, the referer is not leaked, in this situation (opening a private ("incognito" for chrome) tab from a non-private tab).

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19753)

**Comment by amocirean** [comment]
Hello @aplaice, thank you for submitting the issue.
I was able to reproduce it on the latest RC and Nightly


Device Used: Huawei P40 Lite
Android Version: 10

**Comment by fice-t** [comment]
I can reproduce this on the latest Nightly even when opening the link via this page in a private tab. Would this be a GeckoView issue?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807537

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
