### ISSUE TITLE
Jump Back In thumbnail image is not displayed sometimes

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#24132]
### Steps to reproduce

1. Open a few pages (especially wikipedia articles and addons pages).
2. Reopen a wikipedia article (other than the last accessed page) from  Recently visited section.
3. Observe the Jump back in thumbnail image.

### Expected behaviour

The Jump back in thumbnail image is displayed.

### Actual behaviour

The Jump back in thumbnail image is not displayed.

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox
Firefox Nightly

### Firefox version

98.1.1
99.0a1 (2022-03-07)

### Additional information

https://user-images.githubusercontent.com/48829350/157034283-d6e08b3a-f86e-47b7-9ee8-b4f2b89fde73.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19750)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809828

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
