### ISSUE TITLE
[Bug]: "Disconnect" button is not working after a period of time

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#24131]
### Prerequisites
- Log in with a Firefox account on 2/ more devices on 98.1.0 RC build.

### Steps to reproduce
1. Go to desktop and change the password.
2. Perform an update to 98.1.1 - Android.
3. Go on Android -> Settings-Account-Remove account.
4. Tap on "Disconnect".

### Expected behaviour
The account is disconnected. 

### Actual behaviour
Nothing is happening, the button is not working.

### Device name
Sony Xperia

### Android version
6.0.1

### Firefox release type
Firefox

### Firefox version
98.1.1

### Additional information
- not reproducible with clean profile **on Nightly** or **RC 98.1.1**
- 2 days of inactivity have passed until de update was performed
- intermittent issue 

https://user-images.githubusercontent.com/58466444/157028372-72b44155-7c1b-4001-ba4c-573421029e29.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19749)

**Comment by delia-pop** [comment]
Reproducible on Firefox 99.0.0 Beta 1 with Huawei MediaPad M2 (Android 5.1.1).

**Comment by delia-pop** [comment]
Reproducible on RC 99.1.0 with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1817226

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
