### ISSUE TITLE
Improper flicker displayed on engine pictogram and cursor when tapping the URL bar

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#24134]
### Steps to reproduce

1. From homepage, tap on the URL bar.
2. Observe the visual defect on the engine pictogram/cursor.

### Expected behaviour

The transition is done smoothly, with no glitches. The engine pictogram remains properly displayed.

### Actual behaviour

When tapping on the URL bar, the engine pictogram disappears for s split second, and the cursor is displayed in front of the pictogram.

### Device name

Motorola Moto G30

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly from 03/07.
Also encountered on RC 98.1.1, RC 98.1.0.

### Additional information

Also reproducible with Samsung Galaxy Tab S3 (Android 9) and Sony Xperia (Android 6.0.1).
Note that on Motorola Moto G30 (Android 11), the engine pictogram presents the flicker when the URL bar is tapped from a webpage.
Also note that the issue is partially reproducible on Nightly/RC 98.1.1/RC 98.1.0 with Google Pixel 6 (Android 12), where only the engine pictogram flickers subtle.

https://user-images.githubusercontent.com/89388888/157046288-75bf1873-56fe-4467-a4c4-abc01bc91dd1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19752)

**Comment by indurs** [comment]
@Mugurell , can I work on this issue? As @delia-pop mentioned, the transition in the tool bar is not smooth.

**Comment by indurs** [comment]
@Mugurell, probably that is the excepted way. Just going thru this code.

```
override fun handleToolbarClick() {
        metrics.track(Event.SearchBarTapped(Event.SearchBarTapped.Source.BROWSER))
        // If we're displaying awesomebar search results, Home screen will not be visible (it's
        // covered up with the search results). So, skip the navigation event in that case.
        // If we don't, there's a visual flickr as we navigate to Home and then display search
        // results on top it.
        if (currentSession?.content?.searchTerms.isNullOrBlank()) {
            browserAnimator.captureEngineViewAndDrawStatically {
                navController.navigate(
                    BrowserFragmentDirections.actionGlobalHome()
                )
                navController.navigate(
                    BrowserFragmentDirections.actionGlobalSearchDialog(
                        currentSession?.id
                    ),
                    getToolbarNavOptions(activity)
                )
            }
        } else {
            navController.navigate(
                BrowserFragmentDirections.actionGlobalSearchDialog(
                    currentSession?.id
                ),
                getToolbarNavOptions(activity)
            )
        }
    }
```

**Comment by Mugurell** [comment]
Thank you for looking into this @indurs 

I'd say that here there are two issues:
- The search icon shown in EditToolbar [starts as gone](https://github.com/mozilla-mobile/android-components/blob/main/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_edittoolbar.xml#L35) and as such there will be a visible effect when that is made visible afterwards
- The toolbar shown in HomeFragment is different than the one from SearchFragment - It could've been just one shared element.

Agree that fixing this isn't easy and any approach will need more consideration.

**Comment by indurs** [comment]
Thank You @Mugurell . Will look  deeper into the issue

**Comment by amocirean** [comment]
Reopened, as still reproducible on Firefox Beta 109.0b1.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813680

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
