### ISSUE TITLE
[Bug]: children change at onfocus event not reflected for a `select` element

### ISSUE THREAD

**Issue by danny0838** [mozilla-mobile/fenix#24145]
### Steps to reproduce

1. Download, unpack, and open the test page in the browser: [bug-select-change.zip](https://github.com/mozilla-mobile/fenix/files/8207107/bug-select-change.zip)
2. Click on the `select`.

### Expected behaviour

`...`, `Value 1`, and `Value 2` should shown when the `select` is clicked.

### Actual behaviour

Only `...` is shown when the `select` is clicked.

### Device name

ASUS ZenFone 8

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19764)

**Comment by makotokato** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1758800

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by amocirean** [comment]
> Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1758800
> 
> Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

Based on the above reply, this ticket will be closed. Thanks for submitting your issue!

**Comment by makotokato** [comment]
After landing this, android-component has to handle new API. (Also, android-component should handle `PromptInstanceDelegate` well for `<select>` element)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 103.0a1 2022-06-07 using https://bug1758800.bmoattachments.org/attachment.cgi?id=9267098 and the issue no longer occurs.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
