### ISSUE TITLE
[Bug]: System reboot after run firefox

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#24142]
### Steps to reproduce

1. Open Firefox

### Expected behaviour

Opened Firefox browser

### Actual behaviour

After white screen system reboot

### Device name

Sony Xperia Z1 Compact

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

97.2.0

### Additional information

https://media.discordapp.net/attachments/821695511768727569/950664508387508244/VID_20220308_105320.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19756)

**Comment by delia-pop** [comment]
Hi @doesnmisclown,  
thank you for your report!

I cannot reproduce this issue.
Tested it on the latest Nightly (99.0a1 from 03/08), the latest Beta (98.0.0-beta4), Release (97.2.0, 98.1.1, 97.3.0).

Could you please try to reproduce it with the latest Release 97.3.0 or Beta and if you succeed, provide more information? 

Devices used:
Google Pixel 6 (Android 12)
Motorola Moto G30 (Android 11)
Xiaomi Redmi Note 8T (Android 9)
LG G7 fit (Android 8.1.0)
