### ISSUE TITLE
FNX3-16305 ⁃ [Bug] RuntimeExceptionandroid.app.ActivityThread in callActivityOnStop - Crash when closing a custom tab

### ISSUE THREAD

**Issue by Seqularise** [mozilla-mobile/fenix#2414]
## Steps to reproduce
1.Open link as a custom tab
2.Close it

## Additional information
logcat
[2019-05-10-21-33-07.txt](https://github.com/mozilla-mobile/fenix/files/3167384/2019-05-10-21-33-07.txt)
crash log url
https://del.dog/hovasomole

## Device information
Android device: Redmi note 4x, android 9
Fenix version: nightly aarch64 2019-05-10

**Comment by pwd-github** [comment]
I'm seeing this too. Have been reporting it via both the Fenix crash dialog and GPS crash dialog.

**Comment by agi90** [comment]
Sentry issue: [FENIX-Y9](https://sentry.prod.mozaws.net/operations/fenix/issues/5713056/)

**Comment by Seqularise** [comment]
Seems like its gone now

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 5/22, with Sony Xperia Z2 tablet (Android 6.0.1), HTC 10 (Android 8), and  Sony Xperia Z5 Premium (Android 7.1.1).
