### ISSUE TITLE
[Bug]: Roboto font in Android 12 not rendered correctly

### ISSUE THREAD

**Issue by dantmnf** [mozilla-mobile/fenix#24164]
### Steps to reproduce

1. Open a page that will use multiple weights of the default Roboto font (e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight )
2. Check rendering of bold/light weights.

### Expected behaviour

Bold/Light weights should be rendered correctly, resulting in something like in a system webview.

### Actual behaviour

Got faux/synthesized bold and no light font.

### Device name

Android SDK Emulator

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1 (Build #2015867695), a320d75b6+

### Additional information

WebView rendering:
![Screenshot_1646827769](https://user-images.githubusercontent.com/2252500/157440135-c78098cd-a609-4bfa-b398-9c59f0cc3704.png)
![image](https://user-images.githubusercontent.com/2252500/157440575-97847949-8049-4113-92da-16d3203867c9.png)

Firefox rendering:
![Screenshot_1646827759](https://user-images.githubusercontent.com/2252500/157440156-1c920b56-6b92-4abf-9f41-8d70342f85f6.png)
![image](https://user-images.githubusercontent.com/2252500/157440606-a1fe3db2-e14b-4679-bb73-429e543c3ba3.png)

PS. I pulled the font file to a Windows PC and it just works.

**Comment by kbrosnan** [comment]
It is not expected that Gecko and Blink will render text exactly the same. Forwarding to Bugzilla but this may be invalid.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1759567

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
One of the Gecko developers looked at this and believes it may be fixed on a current nightly build. Please re-test and comment in the Bugzilla bug.
