### ISSUE TITLE
[Bug]: When scrolling down (or up) quickly, top (or bottom) of screen flashes white

### ISSUE THREAD

**Issue by nyanpasu64** [mozilla-mobile/fenix#24161]
### Steps to reproduce

1. Visit a very long page like https://gitlab.com/exotracker/exotracker-cpp/-/blob/dev/src/gui/pattern_editor.cpp.
2. Swipe the screen to scroll down quickly.
3. Swipe the screen to scroll up quickly.

### Expected behaviour

No rendering errors appear.

### Actual behaviour

When scrolling down, the top 25-50% of the screen flickers between proper text content and white. When scrolling up, the bottom 25-50% of the screen flickers between content and white.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1 (Build #2015867691), a320d75b6+

### Additional information

This bug has been going on for weeks or months. I suspect it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1758352 and https://bugzilla.mozilla.org/show_bug.cgi?id=1758352, both of which are (desktop Firefox) bugs where the screen is partly replaced with white upon scrolling.

![firefox android scroll up white](https://user-images.githubusercontent.com/913957/157424131-01bc3450-6f62-4cab-9673-fba84059f205.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19770)

**Comment by SoftVision-LorandJanos** [comment]
Hi @nyanpasu64! Thank you for your report!
I couldn't reproduce the issue you described on the latest Nightly 100.0a1 (2022-03-28) build.
I've used a device close to what you had this issue with, using the example you gave: Google Pixel 4 (Android 12).
Also tried on an Oppo Reno 6 (Android 12) with the same result.
Could you make a video of your issue? Thank you!

**Comment by nyanpasu64** [comment]
Used Insular to create a clean work "profile" of Firefox 2022-03-28. I had a harder time reproducing the bug because the clean profile had less extensions than my regular profile, but when I turned on the screen recorder (which caused the screen frame rate to drop), the bug was easier to reproduce even in the clean profile. Video at https://youtu.be/zcpit0aAD_A.

**Comment by nyanpasu64** [comment]
- On desktop, deleting GitLab's top purple bar makes it easier to see flickering at the top of the screen. 
- On desktop, disabling `apz.force_disable_desktop_zooming_scrollbars` on desktop reduces flickering by 90-100% (I'm not sure whether it fixes it entirely or not).
- On Android, disabling `apz.force_disable_desktop_zooming_scrollbars` doesn't prevent flickering.

**Comment by nyanpasu64** [comment]
Still happens. If you scroll enough the whole screen turns white for up to a second.

![Screenshot_20221119-074628_Firefox Nightly](https://user-images.githubusercontent.com/913957/202859254-4d643a0e-3eb2-4a45-b3d2-881e9de97135.png)

109.0a1 (Build #2015916651), 63a517171+
AC: 109.0.20221118221738, f093035e6b
GV: 109.0a1-20221118154632
AS: 95.0.1

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813174

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
