### ISSUE TITLE
[Bug]: Cant fast multiply open links with search bar on when violet info popsup

### ISSUE THREAD

**Issue by 313374** [mozilla-mobile/fenix#24166]
### Steps to reproduce

1. Open a tab.
2. Start searching a phrase (succesfully or not).
3. Open new tab in background in actual tab (with search results on).
4. U must wait few seconds (actually it is violet info which it triggers) before u can edit or close search results (on bottom). U cant multiply fast open new tabs when there is violet info about opening new tab.

### Expected behaviour

Editing and closing search results without waiting extra seconds with violet info on.

### Actual behaviour

Freeze (on search bar) when violet info about opening new tab pop ups.

### Device name

Samsung A52S 5G

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19775)

**Comment by 313374** [comment]
@LaurentiuApahideanSV my description is little chaotic, video - https://streamable.com/3dp1tt

**Comment by amocirean** [comment]
This issue is not reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using the following devices: Samsung Galaxy S22 Ultra (Android 13), Oppo Find X3 Neo (Android 11).
Closing this as fixed.
