### ISSUE TITLE
[Bug]: Search groups not displayed under Jump Back in section

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#24165]
### Steps to reproduce

1. Type a search term in the URL bar and perform the search.
2. Long tap on a few links, open them in normal browsing and visit the sites.
3. Check the homepage -> Jump Back in section.

### Expected behaviour

The search grouping will appear in the Jump back in section if the tabs are opened.

### Actual behaviour

The search grouping is not displayed in the Jump back in section.

### Device name

Sony Xperia

### Android version

6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1, 99.0.0-beta.1, 98.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19774)

**Comment by Alexandru2909** [comment]
I believe we can close this ticket since the work for https://github.com/mozilla-mobile/fenix/issues/26227 intentionally removed search groups from the "Jump back in" section. We cant revisit this issue after the tabs tray to compose migration.
