### ISSUE TITLE
[Bug]: Menu button nearly untouchable. Should be moved e a little to the left.

### ISSUE THREAD

**Issue by Rodze** [mozilla-mobile/fenix#24172]
### Steps to reproduce

1. Open Firefox.

### Expected behaviour

Menu button should be moved a little to the left

### Actual behaviour

Menu button almost disappears in curved corners

### Device name

Galaxy s20 fe

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100a1

### Additional information

It's basic usability. The menu button is simply too far away on the right, almost off screen on curved corners, making it very hard to touch. 

As a comparison, you can see the Chrome menu button is more distant from the corner of the screen so people can touch it. 

![20220309_160605](https://user-images.githubusercontent.com/499237/157514522-e7b45035-e286-4b91-a7b5-5fbb1589d765.jpg)

**Comment by amocirean** [comment]
Hello @Rodze and thank you for submitting the issue you've encountered.
As far as I can see, this is more of a feature request rather than a bug.
This is related to #16719, where this feature you're asking for should be implemented.

Based on the following situation, this ticket will be closed.
