### ISSUE TITLE
Always show the Custom Tab toolbar at the top, regardless of in-app preference

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#24179]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Toolbars in regular Android apps are exclusively at the top and when displaying web content in a Custom Tab, we want to retain the feeling that the user is still in the third party app.

### How do you know that this problem exists today? Why is this important?
Today, if you have the toolbar set as the bottom and when you're in a custom tab, you see the styled toolbar (Custom Tab) move to the bottom. A contrasting toolbar position that pulls you away from the experience that you are meant to have with a Custom Tab - that you are still in the third party app.

### Who will benefit from it?
Users that have Fenix as their default browser.

cc: @agi

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19784)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812839

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
