### ISSUE TITLE
FNX3-16307 ⁃ [Bookmarks] Edit bookmark URL is covered by "clear" icon

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#2417]
The text should be faded out before the "x" icon.

![Screen Shot 2019-05-10 at 2 33 33 PM](https://user-images.githubusercontent.com/5992746/57549124-b42d4180-7330-11e9-9603-b2101464ce26.png)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1922 (#11500615), with Samsung Galaxy S8 (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), and Nexus 6P (Android 8.1.0).
