### ISSUE TITLE
[Bug]: Placeholder displayed instead of product name in Inactive Tabs auto-close prompt

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24188]
## Prerequisites
Have 20+ Inactive tabs

## Steps to reproduce
1. Open the tabs tray
2. Check the Inactive tabs auto-close prompt is displayed

### Expected behavior
The auto-close prompt should display: "**Firefox** can close tabs you haven’t viewed over the past month."

### Actual behavior
The auto-close prompt should display: "%1$s can close tabs you haven’t viewed over the past month."

### Device information

* Android device: OnePlus A3 (Android 6.0.1)
• Firefox Nightly 100.0a1
• Firefox 99.0.0 Beta 1

### Notes
► Screenshot
<img width="530" alt="image" src="https://user-images.githubusercontent.com/51314259/157665148-96f7bca9-c343-4af3-9cad-43805f5acfa9.png">

**Comment by Alexandru2909** [comment]
Issue is not QA Verified.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 100.0a1 (2022-03-28) build.
With 20+ inactive tabs, the error message displayed is: "Firefox can close tabs you haven’t viewed over the past month."
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.
