### ISSUE TITLE
Provide save/restore instance state solution in Fenix architecture

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#2418]
### Why/User Benefit/User Problem
When the Android OS evicts Fenix from memory to make space for another app or game, we don't want our users to lose app state.

Let's say a user is browsing in reader mode and then jumps into a video game on a low specs phone. It's not unlikely the state of the browser will be lost when the user returns because the OS will evict our app from memory to make room for the game. By having our architecture save its state into instance state, that state will still be there when the user returns.

### What/Requirements
Essentially, the requirement is to store state to instance state when the app gets evicted.

There is some complexity, however, as we have a hard limit of 1 MB to store and should really store no more than 100 KB. This means the solution chosen will require the programmer to choose which state gets stored.

### Acceptance Criteria (how do I know when I’m done?)
If I minimize the app and then stop it from Android Studio, state chosen to be kept by the programmer will be kept when the app is reopened from the Recents screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11406)

**Comment by kbrosnan** [comment]
This is being looked at as part of bz-1752594
