### ISSUE TITLE
Add ability to use custom background for new tabs

### ISSUE THREAD

**Issue by Andereoo** [mozilla-mobile/fenix#24189]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I recently noticed that Fenix now has the ability to change the new tab background. However, the available backgrounds are very limited. I think that many people would benefit from having the ability to set a custom background for a new tab. 

Perhaps it would be beneficial to add a way to allow the user to use an image from the phone's local hard drive as the new tab background?

Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19791)

**Comment by TheGreySquare** [comment]
And just in addition: ability to pick custom home/new tab background images for either dark or light theme would make perfect sense.

**Comment by delia-pop** [comment]
Hello @Andereoo ,

Thank you for your report! I will mark this ticket as a feature request.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807090

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
