### ISSUE TITLE
Remove wrapper for onboarding metrics

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24203]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-01 by toggling the options found in the onboarding screen.
Theme set to light
{
          "timestamp": 5503,
          "category": "onboarding",
          "name": "pref_toggled_theme_picker",
          "extra": {
            "theme": "LIGHT"
          }

Theme set to dark
{
          "timestamp": 15357,
          "category": "onboarding",
          "name": "pref_toggled_theme_picker",
          "extra": {
            "theme": "DARK"
          }

Theme set to automatic
{
          "timestamp": 20424,
          "category": "onboarding",
          "name": "pref_toggled_theme_picker",
          "extra": {
            "theme": "FOLLOW_DEVICE"
          }

Toolbar set to top
{
          "timestamp": 23382,
          "category": "onboarding",
          "name": "pref_toggled_toolbar_position",
          "extra": {
            "position": "TOP"
          }

Toolbar set to bottom
{
          "timestamp": 12127,
          "category": "onboarding",
          "name": "pref_toggled_toolbar_position",
          "extra": {
            "position": "BOTTOM"
          }

Tracking protection set to Standard
{
          "timestamp": 5192,
          "category": "onboarding",
          "name": "pref_toggled_tracking_prot",
          "extra": {
            "setting": "STANDARD"
          }

Tracking protection set to Strict
{
          "timestamp": 27979,
          "category": "onboarding",
          "name": "pref_toggled_tracking_prot",
          "extra": {
            "setting": "STRICT"
          }
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-0104)
### Device used:
- OnePlus 6T (Android 9)
