### ISSUE TITLE
Remove wrapper for toolbar settings metrics 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24207]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-01 by switching the position of the toolbar and observing the events that are generated.

When the toolbar position is switched to top
{
          "timestamp": 23109,
          "category": "toolbar_settings",
          "name": "changed_position",
          "extra": {
            "position": "TOP"
          }


Metrics that are sent when the toolbar is set to top
"metrics.toolbar_position":"TOP"
      
When the toolbar position is switched to bottom  
{
          "timestamp": 36336,
          "category": "toolbar_settings",
          "name": "changed_position",
          "extra": {
            "position": "BOTTOM"
          }

Metrics that are sent when the toolbar is set to bottom
"metrics.toolbar_position":"BOTTOM"

[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-0104)
### Device used:
- OnePlus 6T (Android 9)
