### ISSUE TITLE
FNX3-16311 ⁃ [Bug] broken state after closing a tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2420]
### Steps to reproduce
I don't have STR because closing tabs almost always works without problems but the following already happened a few times in the last few weeks after I closed a tab with a swipe gesture:

![Screenshot](https://user-images.githubusercontent.com/1100614/57552519-70582d80-736c-11e9-9e1c-6ba35df46fce.png)UNITO-UNDERSCORE!20190510-212329!

Please note the the grey row with the red icon. It's not possible to remove this row. After closing Fenix via Android recent apps and opening Fenix again the problem is gone.

It's not a regression, it already happened a few weeks ago.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision e1cdeffe8c7168141a586b7c9126555df4c0fb53

**Comment by kbrosnan** [comment]
I can't reproduce this on a Pixel 3, Note 9 or a Galaxy S6 using Fenix from June 6th.
