### ISSUE TITLE
Remove wrapper for login dialog

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24208]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-01 by performing the following interaction with logins and observing the events that are generated.
Sync logins
{"timestamp": 6193,
"category": "sync_account",
"name": "sync_now"}

Turn ON Logins sync
{"timestamp": 7134,
"category": "events",
"name": "preference_toggled",
"extra": {
            "preference_key": "pref_key_sync_logins",
            "enabled": "true"
          }

Turn OFF Logins sync
{"timestamp": 4842,
"category": "events",
"name": "preference_toggled",
"extra": {
            "preference_key": "pref_key_sync_logins",
            "enabled": "false"
          }

Access Logins in settings
{"timestamp":7524,
"category":"logins",
"name":"open_logins"}

Open an individual login
{"timestamp":8878,
"category":"logins",
"name":"open_individual_login"}

Delete a login
{"timestamp":13104,
"category":"logins",
"name":"delete_saved_login"},

Copy a login (Site, Username, Password)
{"timestamp": 97790,
"category": "logins",
"name": "copy_login"}

View a password Ping - Ping be8365e9-708b-437e-9c1e-446864614bee
{"timestamp": 96000,
"category": "logins",
"name": "view_password_login"}

Choose whether Fenix will remember logins:

NEVER_SAVE
{"timestamp":41999,
"category":"login_dialog",
"name":"never_save"}

ASK_TO_SAVE
{"timestamp":81874,
"category":"login_dialog",
"name":"saved"}

[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-0104)
### Device used:
- OnePlus 6T (Android 9)
