### ISSUE TITLE
Remove wrapper for search_shortcuts metrics

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24204]
Implemented in https://github.com/mozilla-mobile/fenix/issues/793.

Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-01 by performing searches using the search shortcuts with all available search engines and custom ones and observing the events that are generated.

Selecting Google as a search engine
{
          "timestamp": 9754,
          "category": "search_shortcuts",
          "name": "selected",
          "extra": {
            "engine": "Google"
          }

Selecting Amazon as a search engine
{
          "timestamp": 21355,
          "category": "search_shortcuts",
          "name": "selected",
          "extra": {
            "engine": "Amazon.com"
          }

Selecting Bing as a search engine
{
          "timestamp": 23735,
          "category": "search_shortcuts",
          "name": "selected",
          "extra": {
            "engine": "Bing"
          }

Selecting DuckDuckGo as a search engine
{
          "timestamp": 33757,
          "category": "search_shortcuts",
          "name": "selected",
          "extra": {
            "engine": "DuckDuckGo"
          }

Selecting Wikipedia as a search engine
{
          "timestamp": 61841,
          "category": "search_shortcuts",
          "name": "selected",
          "extra": {
            "engine": "Wikipedia"
          }

Selecting Google as a search engine
{
          "timestamp": 74526,
          "category": "search_shortcuts",
          "name": "selected",
          "extra": {
            "engine": "eBay"
          }
Selecting Reddit as a search engine
{
          "timestamp": 8757,
          "category": "search_shortcuts",
          "name": "selected",
          "extra": {
            "engine": "Reddit"
          }
Selecting a custom search engine (when using any custom search engine the engine will always be custom)
{
          "timestamp": 7309,
          "category": "search_shortcuts",
          "name": "selected",
          "extra": {
            "engine": "custom"
          }

When any search is performed using search engine shortcuts
{
          "timestamp": 26222,
          "category": "events",
          "name": "performed_search",
          "extra": {
            "source": "shortcut.action"
          }
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-0104)
### Device used:
- OnePlus 6T (Android 9)
