### ISSUE TITLE
firefox preview version

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#24216]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
In some pull requests and commits I saw some videos and screenshots which shows the firefox preview browser.

What is the link to download the app? Just curious to try out new features 🙂

**Comment by Amejia481** [comment]
👋🏽  @sheikh-azharuddin, thanks for interesting on trying out new features.
 
Firefox preview is our debug build, this variant is created when developers build the source code locally, to see all the new functionalities you could download [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)  (practically the same as preview) that contains everything that has been commit to the [main](https://github.com/mozilla-mobile/fenix/tree/main) branch, this also help us to identify/fix bugs early.     

I'm closing this ticket for now, if you need any additional help please feel free to comment on the ticket :)
