### ISSUE TITLE
Remove wrapper for bookmarks management

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24214]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by sflorean** [comment]
Tested on latest Nightly with OnePlus 9 Pro (Android 12) and under category "bookmarks_management" the following were displayed:
        "edited"
	"folder_add"
	"copied"
	"shared"
	"open_in_new_tab"
	"open_in_private_tab"
	"removed"
        "folder_remove"
	"moved"
	"open"
        "bookmarks"
	"folder_remove".
Scenarios covered can be found [here](https://testrail.stage.mozaws.net/index.php?/cases/view/352026).
