### ISSUE TITLE
Remove wrapper for metrics in the "events" category

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24210]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

Note: The category is a legacy "mistake" but creating separate elements is not the scope of this ticket, as it would break existing dashboards.

**Comment by mcarare** [comment]
Note for QA: the list of events to be re-tested can be drawn from the commit [list](https://github.com/mozilla-mobile/fenix/pull/24483/commits) in the PR or from the `metrics.yaml` file, looking in the "events" category: https://github.com/mozilla-mobile/fenix/blob/49f352d52da55bed7ab1cc7dc90f75953a112c86/app/metrics.yaml#L10

**Comment by sflorean** [comment]
Verified as fixed on Nightly 13/4 with OnePlus 9 (Android 12). 
[Glean](data:application/json;charset=utf-8,%7B%22metadata%22%3A%7B%22geo%22%3A%7B%22city%22%3A%22Baia%20Mare%22%2C%22subdivision1%22%3A%22MM%22%2C%22country%22%3A%22RO%22%2C%22db_version%22%3A%222022-04-11T19%3A48%3A38Z%22%7D%2C%22isp%22%3A%7B%22organization%22%3A%22Digi%20Romania%22%2C%22db_version%22%3A%222022-04-11T20%3A19%3A07Z%22%2C%22name%22%3A%22Digi%20Romania%22%7D%2C%22user_agent%22%3A%7B%22os%22%3A%22Android%22%7D%2C%22header%22%3A%7B%22date%22%3A%22Wed%2C%2013%20Apr%202022%2007%3A49%3A42%20GMT%22%2C%22x_lb_tags%22%3A%22TLSv1.2%2C%20c02f%22%2C%22x_debug_id%22%3A%22test-qaAndroid%22%7D%2C%22document_namespace%22%3A%22org-mozilla-fenix%22%2C%22document_type%22%3A%22events%22%2C%22document_version%22%3A%221%22%7D%2C%22submission_timestamp%22%3A%222022-04-13T07%3A49%3A42.403074Z%22%2C%22document_id%22%3A%22ee0c955a-a8bb-4b6a-98f7-e915e93ba0be%22%2C%22normalized_channel%22%3A%22nightly%22%2C%22normalized_os%22%3A%22Android%22%2C%22normalized_os_version%22%3A%2212%22%2C%22normalized_country_code%22%3A%22RO%22%2C%22sample_id%22%3A89%2C%22ping_info%22%3A%7B%22seq%22%3A1%2C%22start_time%22%3A%222022-04-13T10%3A33%2B03%3A00%22%2C%22end_time%22%3A%222022-04-13T10%3A49%2B03%3A00%22%2C%22reason%22%3A%22inactive%22%7D%2C%22client_info%22%3A%7B%22telemetry_sdk_build%22%3A%2244.0.0%22%2C%22build_date%22%3A%222022-04-05T17%3A10%3A19%2B00%3A00%22%2C%22first_run_date%22%3A%222022-04-13%2B03%3A00%22%2C%22client_id%22%3A%22e28168ac-e096-4267-bccc-f2ec7ef79160%22%2C%22locale%22%3A%22en-US%22%2C%22device_manufacturer%22%3A%22OnePlus%22%2C%22app_display_version%22%3A%22101.0a1%22%2C%22architecture%22%3A%22arm64-v8a%22%2C%22os_version%22%3A%2212%22%2C%22app_channel%22%3A%22nightly%22%2C%22android_sdk_version%22%3A%2231%22%2C%22os%22%3A%22Android%22%2C%22device_model%22%3A%22LE2121%22%2C%22app_build%22%3A%222015872975%22%7D%2C%22events%22%3A%5B%7B%22timestamp%22%3A0%2C%22category%22%3A%22engine_tab%22%2C%22name%22%3A%22foreground_metrics%22%2C%22extra%22%3A%7B%22background_crashed_tabs%22%3A%220%22%2C%22background_total_tabs%22%3A%222%22%2C%22foreground_crashed_tabs%22%3A%220%22%2C%22background_active_tabs%22%3A%222%22%2C%22foreground_total_tabs%22%3A%222%22%2C%22time_in_background%22%3A%22370755%22%2C%22foreground_active_tabs%22%3A%222%22%7D%7D%2C%7B%22timestamp%22%3A5077%2C%22category%22%3A%22events%22%2C%22name%22%3A%22search_bar_tapped%22%2C%22extra%22%3A%7B%22source%22%3A%22HOME%22%7D%7D%2C%7B%22timestamp%22%3A7431%2C%22category%22%3A%22events%22%2C%22name%22%3A%22entered_url%22%2C%22extra%22%3A%7B%22autocomplete%22%3A%22false%22%7D%7D%2C%7B%22timestamp%22%3A7431%2C%22category%22%3A%22awesomebar%22%2C%22name%22%3A%22history_suggestion_clicked%22%7D%2C%7B%22timestamp%22%3A53084%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A60636%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22downloads%22%7D%7D%2C%7B%22timestamp%22%3A63001%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A64842%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22history%22%7D%7D%2C%7B%22timestamp%22%3A64929%2C%22category%22%3A%22history%22%2C%22name%22%3A%22opened%22%7D%2C%7B%22timestamp%22%3A67190%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A69110%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22add_to_top_sites%22%7D%7D%2C%7B%22timestamp%22%3A70460%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A72308%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22save_to_collection%22%7D%7D%2C%7B%22timestamp%22%3A72311%2C%22category%22%3A%22collections%22%2C%22name%22%3A%22save_button%22%2C%22extra%22%3A%7B%22from_screen%22%3A%22browserMenu%22%7D%7D%2C%7B%22timestamp%22%3A73920%2C%22category%22%3A%22collections%22%2C%22name%22%3A%22saved%22%2C%22extra%22%3A%7B%22tabs_selected%22%3A%221%22%2C%22tabs_open%22%3A%223%22%7D%7D%2C%7B%22timestamp%22%3A75182%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A82848%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22share%22%7D%7D%2C%7B%22timestamp%22%3A85398%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A86123%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22reload%22%7D%7D%2C%7B%22timestamp%22%3A97369%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A102053%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22addons_manager%22%7D%7D%2C%7B%22timestamp%22%3A104374%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A105245%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22sync_account%22%7D%7D%2C%7B%22timestamp%22%3A105331%2C%22category%22%3A%22sync_auth%22%2C%22name%22%3A%22opened%22%7D%2C%7B%22timestamp%22%3A106695%2C%22category%22%3A%22sync_auth%22%2C%22name%22%3A%22closed%22%7D%2C%7B%22timestamp%22%3A107584%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A109656%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22desktop_view_on%22%7D%7D%2C%7B%22timestamp%22%3A111240%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A117902%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22find_in_page%22%7D%7D%2C%7B%22timestamp%22%3A153523%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_toolbar_home_tapped%22%7D%2C%7B%22timestamp%22%3A153660%2C%22category%22%3A%22home_screen%22%2C%22name%22%3A%22home_screen_displayed%22%7D%2C%7B%22timestamp%22%3A153744%2C%22category%22%3A%22pocket%22%2C%22name%22%3A%22home_recs_shown%22%7D%2C%7B%22timestamp%22%3A159836%2C%22category%22%3A%22home_screen%22%2C%22name%22%3A%22customize_home_clicked%22%7D%2C%7B%22timestamp%22%3A162570%2C%22category%22%3A%22home_screen%22%2C%22name%22%3A%22home_screen_displayed%22%7D%2C%7B%22timestamp%22%3A162608%2C%22category%22%3A%22pocket%22%2C%22name%22%3A%22home_recs_shown%22%7D%2C%7B%22timestamp%22%3A198717%2C%22category%22%3A%22events%22%2C%22name%22%3A%22search_bar_tapped%22%2C%22extra%22%3A%7B%22source%22%3A%22HOME%22%7D%7D%2C%7B%22timestamp%22%3A207543%2C%22category%22%3A%22home_screen%22%2C%22name%22%3A%22home_screen_displayed%22%7D%2C%7B%22timestamp%22%3A207580%2C%22category%22%3A%22pocket%22%2C%22name%22%3A%22home_recs_shown%22%7D%2C%7B%22timestamp%22%3A220556%2C%22category%22%3A%22events%22%2C%22name%22%3A%22whats_new_tapped%22%7D%2C%7B%22timestamp%22%3A245193%2C%22category%22%3A%22context_menu%22%2C%22name%22%3A%22item_tapped%22%2C%22extra%22%3A%7B%22named%22%3A%22open_in_new_tab%22%7D%7D%2C%7B%22timestamp%22%3A277854%2C%22category%22%3A%22events%22%2C%22name%22%3A%22copy_url_tapped%22%7D%2C%7B%22timestamp%22%3A369334%2C%22category%22%3A%22events%22%2C%22name%22%3A%22search_bar_tapped%22%2C%22extra%22%3A%7B%22source%22%3A%22BROWSER%22%7D%7D%2C%7B%22timestamp%22%3A369479%2C%22category%22%3A%22home_screen%22%2C%22name%22%3A%22home_screen_displayed%22%7D%2C%7B%22timestamp%22%3A369659%2C%22category%22%3A%22pocket%22%2C%22name%22%3A%22home_recs_shown%22%7D%2C%7B%22timestamp%22%3A372333%2C%22category%22%3A%22search_shortcuts%22%2C%22name%22%3A%22selected%22%2C%22extra%22%3A%7B%22engine%22%3A%22DuckDuckGo%22%7D%7D%2C%7B%22timestamp%22%3A375231%2C%22category%22%3A%22events%22%2C%22name%22%3A%22performed_search%22%2C%22extra%22%3A%7B%22source%22%3A%22shortcut.action%22%7D%7D%2C%7B%22timestamp%22%3A389201%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A391166%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22settings%22%7D%7D%2C%7B%22timestamp%22%3A396196%2C%22category%22%3A%22toolbar_settings%22%2C%22name%22%3A%22changed_position%22%2C%22extra%22%3A%7B%22position%22%3A%22TOP%22%7D%7D%2C%7B%22timestamp%22%3A397638%2C%22category%22%3A%22app_theme%22%2C%22name%22%3A%22dark_theme_selected%22%2C%22extra%22%3A%7B%22source%22%3A%22SETTINGS%22%7D%7D%2C%7B%22timestamp%22%3A397671%2C%22category%22%3A%22start_on_home%22%2C%22name%22%3A%22enter_home_screen%22%7D%2C%7B%22timestamp%22%3A549862%2C%22category%22%3A%22events%22%2C%22name%22%3A%22toolbar_menu_visible%22%7D%2C%7B%22timestamp%22%3A551881%2C%22category%22%3A%22events%22%2C%22name%22%3A%22browser_menu_action%22%2C%22extra%22%3A%7B%22item%22%3A%22sync_account%22%7D%7D%2C%7B%22timestamp%22%3A551987%2C%22category%22%3A%22sync_auth%22%2C%22name%22%3A%22opened%22%7D%2C%7B%22timestamp%22%3A554083%2C%22category%22%3A%22sync_auth%22%2C%22name%22%3A%22scan_pairing%22%7D%2C%7B%22timestamp%22%3A569848%2C%22category%22%3A%22engine_tab%22%2C%22name%22%3A%22foreground_metrics%22%2C%22extra%22%3A%7B%22background_total_tabs%22%3A%225%22%2C%22background_crashed_tabs%22%3A%220%22%2C%22foreground_crashed_tabs%22%3A%220%22%2C%22time_in_background%22%3A%2215037%22%2C%22background_active_tabs%22%3A%225%22%2C%22foreground_active_tabs%22%3A%225%22%2C%22foreground_total_tabs%22%3A%225%22%7D%7D%2C%7B%22timestamp%22%3A571711%2C%22category%22%3A%22start_on_home%22%2C%22name%22%3A%22enter_home_screen%22%7D%2C%7B%22timestamp%22%3A571711%2C%22category%22%3A%22events%22%2C%22name%22%3A%22app_opened%22%2C%22extra%22%3A%7B%22source%22%3A%22CUSTOM_TAB%22%7D%7D%2C%7B%22timestamp%22%3A584609%2C%22category%22%3A%22sync_auth%22%2C%22name%22%3A%22paired%22%7D%2C%7B%22timestamp%22%3A584695%2C%22category%22%3A%22sync_auth%22%2C%22name%22%3A%22closed%22%7D%5D%7D):
