### ISSUE TITLE
Remove wrapper for preferences (settings) metrics

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24212]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-13 by enabling several settings tapping on the voice search and observing the metrics that are sent.
    
Metric sent with studies enabled and disabled      
preferences.studies_enabled	true
preferences.studies_enabled	false

Events sent when tapping the voice search from the URL bar and search widget
{
          "timestamp": 8459,
          "category": "voice_search",
          "name": "tapped"
        },

{
          "timestamp": 0,
          "category": "search_widget",
          "name": "voice_button"
        },

{
          "timestamp": 3452,
          "category": "events",
          "name": "performed_search",
          "extra": {
            "source": "default.widget"
          }

   
Metrics sent with the search widget not installed and installed
metrics.search_widget_installed	false
metrics.search_widget_installed	true

Metrics sent when Fenix is not the default browser and when it is set
metrics.default_browser	false
metrics.default_browser	true

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-1304)
### Device used:
- OnePlus 6T (Android 9)
