### ISSUE TITLE
[Bug]: Crash when taping a link in extension popup

### ISSUE THREAD

**Issue by Semro** [mozilla-mobile/fenix#24228]
### Steps to reproduce

1. Install extension [Privacy Possum](https://addons.mozilla.org/ru/firefox/addon/privacy-possum/)
2. Open extension popup
3. Tap on link (for this particular extension is "Report a bug")

### Expected behaviour

A new tab with desired link should open

### Actual behaviour

The app crashes

### Device name

HUAWEI STK-LX1

### Android version

29 (REL)

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

### Device logs

Crash report: https://crash-stats.mozilla.org/report/index/bp-9aedfb0a-a029-48d1-8e6b-c80ff0220311
Logs from ADB: https://gist.github.com/Semro/f768d0099f99f2ef2eac2bd5a389227f

### Additional information

I also can reproduce it in my own extension, taping on following link: https://github.com/Semro/syncwatch/blob/e476cfbe68ffd4755eede6f12daf5870f6ccfece/plugin/popup.html#L17-L22

But I can't reproduce bug when opening links in [Dark Reader](https://addons.mozilla.org/ru/firefox/addon/darkreader/) extension.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1759560

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
