### ISSUE TITLE
[Bug]: Failed to query Add-ons on Redmi Note 10 Pro

### ISSUE THREAD

**Issue by vic958420** [mozilla-mobile/fenix#24241]
### Steps to reproduce

1. Enter custom add-on collection
2. Select "Add-ons"

### Expected behaviour

My add-on collection should be available

### Actual behaviour

Failed to query Add-ons message appears instead

### Device name

Redmi Note 10 Pro

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

### Additional information

This issue does not occur on my other Android device (Xiaomi Mi 8) which suggests to me that this is probably a server side error.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19825)

**Comment by amedyne** [comment]
Hi @vic958420 , 
  Wanted to get more information about this bug report. Can you attach a screenshot of the error page/message that you get? 
Also,
To understand this better, can you confirm if you followed the steps here when creating the custom addons: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/ ? Can you attach screenshots of what you filled-out on the input fields when you add custom add-ons?

Thank you
