### ISSUE TITLE
allow one of the search engine choices to be local URL

### ISSUE THREAD

**Issue by jidanni** [mozilla-mobile/fenix#24248]
https://support.mozilla.org/en-US/questions/1329243 mentions the serious problem of not being able to use local urls, it's almost unconstitutional!
Therefore, as a workaround, I propose that one of the search engine choices should be simply: local URL!
That way one could browse the files on one's SD card here on Android.

**Comment by kbrosnan** [comment]
Firefox is not a file browser. There is no such thing as a local file search engine. 1327 is the local file issue. There are some complexities that make displaying local files risky/complicated.
