### ISSUE TITLE
FNX3-16315 ⁃ [Bug] (L10N) QAB shows wrong text for bookmarked pages

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2425]
_It's not an issue in the EN version of Fenix but in the German translation and probably also in other translations because of a misleading localization comment - the localization comment does not reflect the implementation._

The EN version of Fenix only displays "Bookmark" in the QAB. But in the German translation it's "Als Lesezeichen hinzufügen" (would be "add as bookmark" in English). That's because the localization comment says: "Button in the browser chrome in the browser **to bookmark the current page**" (I highlighted the important part).

That's a problem because if you bookmark a website in Fenix the QAB shows a different icon but still the same text. In the EN version you don't see a problem because it's still "Bookmark" and that's not wrong because it's not very precise. But to say "add as bookmark" is only correct for websites which are not yet bookmarks and it's wrong for already bookmarked websites. And that's the case in the German translation at the moment.

So there are two options:

1) The translations have to be changed to "Bookmark" as in the EN version. Also the localization comment has to be changed so that translators don't introduce the problem again. The localization comment must clarify that the string is used for not bookmarked _AND_ for bookmarked websites.

or…

2) Not only change the icon but also the text in the QAB for bookmarked pages. Then you have to add a second string for bookmarked pages. Of course you can still use "Bookmark" for both strings in the EN version if you want.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision e1cdeffe8c7168141a586b7c9126555df4c0fb53

**Comment by ekager** [comment]
Good point! We could possibly change the string to something like "Edit Bookmark" since we are updating the visual state of the button anyway. Adding for UX feedback

**Comment by topotropic** [comment]
@ekager what do we do with words that are too long, use ellipses? 
I noticed that the german translation is quite long atm and although it fits currently it won't fit once we have 4 items in the QAB.

**Comment by mheubusch** [comment]
@topotropic We shouldn't be using ellipses - especially if we have no way to expand them - is there another way to solve this?

**Comment by topotropic** [comment]
@cadeyrn It would be nice to follow your 2. suggestion and have two strings (Bookmark, Edit Bookmark) here, also helps to decode the icon.

**Comment by cadeyrn** [comment]
> bifleming added this to the Release MVP Release 12 days ago

Since we already reached _string freeze_ it's no longer possible for MVP, right?

**Comment by cadeyrn** [comment]
It's fixed. Can be verified by QA (I can't set labels) or closed. ;)
