### ISSUE TITLE
[Bug]: Dark mode makes Share menu titles and icon labels almost or completely invisible

### ISSUE THREAD

**Issue by mr-brunes** [mozilla-mobile/fenix#24263]
### Steps to reproduce

Open web page
Tap Share
observe Share menu titles and icons' labels

### Expected behaviour

In Light mode, observe visible Share menu titles and icons' labels:

![2022-03-14 11 05 35](https://user-images.githubusercontent.com/1270750/158162673-829aba55-c828-4d32-add7-0bca9e9566d7.jpg)

### Actual behaviour

In dark mode, Share menu titles and icons' labels are hard to see if not invisible:

![2022-03-14 11 05 06](https://user-images.githubusercontent.com/1270750/158162694-82929a2a-7eef-49f9-9bae-b6d3cec24f06.jpg)

### Device name

Samsung S10e and Tab S6

### Android version

Android 12 and 11

### Firefox release type

Firefox

### Firefox version

98.1.1

### Additional information

There's a time and a place for minimalism but dark mode isn't necessarily it.

**Comment by Dunexus** [comment]
This has been recently [fixed](https://github.com/mozilla-mobile/fenix/pull/23038). It is part of version 99.
You can test it by using the [beta version of Firefox](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) and should release in early April as stable.

**Comment by mr-brunes** [comment]
Great thanks.
