### ISSUE TITLE
[Bug]: Amazon/eBay Sponsored tiles are still available after the default search engine is set as Amazon/eBay

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-mobile/fenix#24262]
### Prerequisites
- Make sure you have eBay or Amazon as sponsored tile available.

### Steps to reproduce

1. Open the Nightly browser.
2. Tap the "..." settings menu button.
3. Tap the "Settings" option.
4. Tap the "Search" option.
5. Select "Amazon" or "eBay" depending on the sponsored tile available. 
6. Return to the homepage and observe the Top Sites area.

### Expected behaviour

- The eBay/Amazon sponsored tiles are no longer visible because the default search engine was changed to eBay/Amazon. 

### Actual behaviour

- The eBay/Amazon sponsored tile are visible even if the default search engine was changed to eBay/Amazon. 

### Device name

One Plus 8 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

### Additional information

- On Desktop, the Amazon/eBay sponsored tile disappears if the default search engine is set to Amazon/eBay. Considering this, for consistency between mobile and desktop I have logged this behavior.
- Here is a screen recording for the Mobile experience:

https://user-images.githubusercontent.com/19226534/158160553-3b84776e-3884-462a-9873-12bba4745b08.mp4

- Here is a screen recording for the Desktop experience:
![amazon default engine vs amazon sponsored tile](https://user-images.githubusercontent.com/19226534/158160787-446947b0-3f16-4d77-8f74-3ffd823d5c0a.gif)

**Comment by lwa-moz** [comment]
Confirming that Amazon/eBay sponsored shortcuts should not be shown if the user has set Amazon/eBay as their default search engine.

**Comment by Alexandru2909** [comment]
I noticed in the Desktop recording that when the Amazon search engine is applied, not only is the Amazon sponsored shortcut removed, but also the number of sponsored tiles is decreased from `2` to `1`. Is this also the expected behavior for Fenix, or do we want to have the same number after Amazon is set as default search engine, with another sponsored tile replacing Amazon?

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nighgly 102.0a1 (2022-05-06) build.
After Amazon/ebay is selected as default search engine, they are no longer displayed as sponsored tiles.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
