### ISSUE TITLE
[Bug]: topsites / shortcut merged

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#24271]
### Steps to reproduce

in latest android nighlty v100 topsites and shortcut have been merged .
what are the developers thinking ?
let's say I want a clean on page with just 4 top sites why do the hell history items now are added to free top sites slots ?
there 's already a recently visited section that can be enabled so why messing mixing topsites and shortcuts treating as same thing ,ruining fenix even more ?

### Expected behaviour

top sites and shortcuts must be separate as previous android versions

### Actual behaviour

Fenix is now an ugly mess 

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

100

**Comment by kbrosnan** [comment]
This matches desktop new tab wording and behavior.

**Comment by ale82to** [comment]
well done it makes fenix even worse and messy !

**Comment by ale82to** [comment]
oh and well ...since it's so important to match desktop behaviour why after so much time desktop button in fenix is still opening top sites in New tab instead of the original tab is tapped from ??????!!!!??????!!!!

**Comment by sharbet** [comment]
@kbrosnan

> This matches desktop new tab wording and behavior.

Although I understand the team's intent, I cannot fully agree with the decision.

![356f7100-83f1-40b3-bd22-74b4d3d7a3a4](https://user-images.githubusercontent.com/73639287/158289556-ba2a0bd1-5e7e-4ff2-b3e9-73e24ab719e1.png)
 
- With smartphones having confined space, unlike the desktop, efficiently managing space is very important. As evidenced in screenshot, everytime we visit webpages (similar domains), it automatically clutters up the precious space. 

- There is also an issue of redundancy. There is a similar function already provided by `recently visited`.

Please reconsider the decision. or at least give the user an opt-out feature (to only display pinned sites)
