### ISSUE TITLE
Update pagination library

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#24276]
It is a preparation for [...issues/24057](https://github.com/mozilla-mobile/fenix/issues/24057).
We use the 2.1.2 version of pagination library, that was released on March 18, 2020.
New design requirements for history screen (sticky headers, collapsible) require a more fresh version, to be able to work with Composable. 
The idea is to update it upfront and make it sure, that there is a safe option to fallback to, in case we decide to turn off synced history and the new design for history screen.

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Nightly 100.0a1 (2022-04-01) build.
Focused on checking the right history entries, scrolling functionality, deleting one or more by selecting multiple entries, and exploratory testing.
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.
