### ISSUE TITLE
Add edit option for results from history search

### ISSUE THREAD

**Issue by WebworkrNet** [mozilla-mobile/fenix#24279]
### What is the user problem or growth opportunity you want to see solved?
Add an option to edit a result from history search.
a) Save as bookmark.
b) Delete entry from history.

### How do you know that this problem exists today? Why is this important?
It would reduce the number of working steps.

### Who will benefit from it?
Everybody

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19846)

**Comment by WebworkrNet** [comment]
Based on #10046.

**Comment by WebworkrNet** [comment]
Related to #19995.

**Comment by WebworkrNet** [comment]
Related to #6358.

**Comment by LaurentiuApahideanSV** [comment]
I will mark this issue as a feature request.

**Comment by WebworkrNet** [comment]
> Please change the title from "search history" to "history search."

Title updated.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813089

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
