### ISSUE TITLE
FNX3-16316 ⁃ Support Add-ons

### ISSUE THREAD

**Issue by maverick74** [mozilla-mobile/fenix#2428]
### Why/User Benefit/User Problem
Add-ons allow users to customize the browser with extra features

### Acceptance Criteria (how do I know when I’m done?)
When one goes to AMO and is able to install add-ons

I think this is probably already planned (i can't even imagine Firefox without it), but the intention is to have a bug report where one can follow the implementation progress of this feature.

**Comment by yoasif** [comment]
Dupe of #574

**Comment by kbrosnan** [comment]
Closing dupe

**Comment by maverick74** [comment]
Ups. 

Didn't search for "Web extensions"!

Sorry about that, guys. My fault.

**Comment by NatoBoram** [comment]
#574 got closed in favour of #5315, which got its scope arbitrarily changed then closed by @vesta0. This is no longer a duplicate.

**Comment by maverick74** [comment]
@data-sync-user Why is this reopened? It was a dupe!

**Comment by Dunexus** [comment]
@maverick74 data-sync-user is a bot and it didn't behave as expected. It re-opened some issues by mistake.

**Comment by NatoBoram** [comment]
Still not a dupe, but the closest I found was https://github.com/mozilla-mobile/fenix/issues/14034.
