### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest. privateSelectAndSearchTextTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24281]
### Stacktrace:
❗ Not sure what caused the crash, based on the logs the test ran to completion
[Logcat](https://github.com/mozilla-mobile/fenix/files/8252535/privateSelectAndSearchTextTest.txt)

### Build: 3/14 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19848)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4854601731823763084/executions/bs.5b9a180ba8df3b1/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Crashed 1/2 runs on 3/25 debug:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7586116168220898567/executions/bs.154bdbab8b294cd0

**Comment by AndiAJ** [comment]
Flaky 1x on 3/31 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7571716381124233523/executions/bs.889bd9fe9d69b1ea/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5367013651837550720/executions/bs.2dc7e8605ba8ebb1/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Not sure if still related to [a11y problems](https://bugzilla.mozilla.org/show_bug.cgi?id=1758540)
`04-05 14:28:48.667: W/BinderNative(2070): Uncaught exception from death notification
04-05 14:28:48.667: W/BinderNative(2070): java.lang.NullPointerException: Attempt to read from field 'android.accessibilityservice.IAccessibilityServiceClient com.android.server.accessibility.AbstractAccessibilityServiceConnection.mServiceInterface' on a null object reference
04-05 14:28:48.667: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager.destroyUiAutomationService(UiAutomationManager.java:179)
04-05 14:28:48.667: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager.access$200(UiAutomationManager.java:41)
04-05 14:28:48.667: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager$UiAutomationService.binderDied(UiAutomationManager.java:230)
04-05 14:28:48.667: W/BinderNative(2070): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:1193)
04-05 14:28:48.668: W/SurfaceFlinger(1943): Attempting to destroy on removed layer: AppWindowToken{28d9acb token=Token{221119a ActivityRecord{2f5f645 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t4}}}#0
04-05 14:28:48.669: W/ActivityManager(2070): Crash of app org.mozilla.fenix.debug running instrumentation ComponentInfo{org.mozilla.fenix.debug.test/androidx.test.runner.AndroidJUnitRunner}
04-05 14:28:48.669: I/ActivityManager(2070): Force stopping org.mozilla.fenix.debug appid=10092 user=0: finished inst
04-05 14:28:48.669: I/ActivityManager(2070): Killing 7028:org.mozilla.fenix.debug:tab7/u0a92 (adj 0): stop org.mozilla.fenix.debug`

**Comment by AndiAJ** [comment]
Flaky 1x on 4/12 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5023694527692422781/executions/bs.52c39574d4b6d3c7/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/23 Main [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8404218889311543836/executions/bs.39cb7ca6669728f8/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7459179005826810994/executions/bs.ec7c8a71180443b8/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7895136826650810418/executions/bs.a1d824e129455df/test-cases)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
