### ISSUE TITLE
Make Sure Fenix Works for Android Q Gestural Navigation

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#2429]
> Android Q introduces an option for fully gestural system navigation. There are two things that app developers should do to prepare for this feature:
> 
>     Extend app content from edge to edge.
>     Handle conflicting app gestures.
>

Things we should check out: 

* We should ensure our bottom swipe gesture starts outside of the bottom navigation swipe.
* Set the flags for edge to edge window content

See Android Developer Guide for more information on Gestural Navigation: https://developer.android.com/preview/features/gesturalnav

**Comment by mheubusch** [comment]
@vesta0 @ekager this seems like an engineering implementation request Not sure why UX is  needed. Please clarify

**Comment by vesta0** [comment]
@mheubusch you are right, not sure why that label was added initially. @ekager let us know if you are blocked on anything.

**Comment by ekager** [comment]
I'm going to close this because I've been using Android Q gestures and don't think anything will conflict currently. Something to keep in mind for further gesture work though.
