### ISSUE TITLE
Refactor Scan button from the search toolbar into the display toolbar

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24298]
https://mozilla-hub.atlassian.net/browse/FNXV2-19759

**Comment by Dunexus** [comment]
Isn't this the same as https://github.com/mozilla-mobile/fenix/issues/16658 ?

**Comment by gabrielluong** [comment]
> Isn't this the same as #16658 ?

They are similar. I will close https://github.com/mozilla-mobile/fenix/issues/16658 and prefer this one.

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Nightly 101.0a1 (2022-04-18) build.
I  opened the secret setting and turned on unified search
The QR code icon is displayed in the toolbar.
Device used: Oppo Reno 6 (Android 12).
