### ISSUE TITLE
[Bug]: Pocket tiles displaying HTML code in title 

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#24295]
### Steps to reproduce

1. Out of coinvodence, find a Pocket tile that has HTML code in it

### Expected behaviour

Either render or strip the code. This could be a security concern i.e. code injection.

### Actual behaviour

It shows "\<em>"
![Screenshot_20220313-115359_Firefox Beta](https://user-images.githubusercontent.com/76437842/158574627-30ed9493-6ae9-4d29-be9c-2ef8c196316b.png)

### Device name

Samsung 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1 (Build #2015868171),

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19856)

**Comment by gabrielluong** [comment]
It might be reason to forward this request to Pocket services team to fix this in their backend instead of us handling the stripping in the client side.

**Comment by Mugurell** [comment]
Contacted Priya from Pocket.

**Comment by Mugurell** [comment]
Closing the issue with the problem being resolved upstream by Pocket.
If the problem reappears we can investigate later.
