### ISSUE TITLE
Add Tabs to the search engine menu

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24300]
https://mozilla-hub.atlassian.net/browse/FNXV2-19758

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19859)

**Comment by delia-pop** [comment]
Verified as fixed in the latest Nightly from 05/30 with Google Pixel 6 (Android 12).
![tabs2](https://user-images.githubusercontent.com/89388888/171017192-0e8ffc05-4d8c-4595-beb1-84b7393c1096.JPG)
