### ISSUE TITLE
Refactor Onboarding into its own fragment

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24303]
We would like to refactor the Onboarding first run content into their own fragment so that it will reduce the complexity of the HomeFragment and the number of things to convert to Jetpack Compose for the Homescreen performance work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19863)

**Comment by cpeterso** [comment]
Duplicate of Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1808358

**Comment by gabrielluong** [comment]
@cpeterso This isn't a duplicate and they are actually unrelated.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809998

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
