### ISSUE TITLE
[Bug]: SERIOUS Bug font rendering latest nighlty

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#24309]
### Steps to reproduce

since a week fenix nighlty if used with this specific style :
-webkit-text-stroke-width: 0.3px
messes up webpages font turning letters into symbol and or emoji !!
screnshot :
https://i.imgur.com/C1N66Fe.jpg

### Expected behaviour

font should look normal 

### Actual behaviour

webpage fonts are deeply meesed up

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

100

**Comment by kbrosnan** [comment]
You already filed this. #24269
