### ISSUE TITLE
Migrate TabInCollectionViewHolder to Compose

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24316]
Breakage of https://github.com/mozilla-mobile/fenix/issues/22755

This refers to:
- [TabInCollectionViewHolder](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/TabInCollectionViewHolder.kt) showing an individual collection. (maybe instead of adding individual composables to the homescreen for each collection we could wrap them all in a list)

The compose versions can be added to the current RecyclerView but before doing so we should ensure there will be no performance regression introduced.
To profile the differences the steps from https://github.com/mozilla-mobile/fenix/issues/21854#issuecomment-1049392266 can be used.

**Comment by gabrielluong** [comment]
I think we should wait to see how the Synced History and Inactive Tabs compose work goes since this all implements WidgetSiteItem. We shouldn't need a 3rd rewrite of WidgetSiteItem and ideally just reuse a shared component.

**Comment by Mugurell** [comment]
Looking at the design from https://www.figma.com/file/hJfV1KGZuOK7OYr29pooL5/Synced-tabs?node-id=229%3A14717 there are also some important differences - the favicon and close button.
I think this can be worked on alongside with https://github.com/mozilla-mobile/fenix/issues/24333 which again has important differences when compared to synced history.

Not sure about the new design for inactive tabs. @gabrielluong Do you have any resources that can be linked here about that?

**Comment by gabrielluong** [comment]
> Looking at the design from https://www.figma.com/file/hJfV1KGZuOK7OYr29pooL5/Synced-tabs?node-id=229%3A14717 there are also some important differences - the favicon and close button. I think this can be worked on alongside with #24333 which again has important differences when compared to synced history.
> 
> Not sure about the new design for inactive tabs. @gabrielluong Do you have any resources that can be linked here about that?

There's no new inactive tabs designs, but the 2 components are fairly similar.

**Comment by Mugurell** [comment]
@gabrielluong  Regarding migrating the list for collection tabs to a `LazyColumn` that might not be easily possible because we are already in a vertically scrollable parent.
Tried that and I am getting `Nesting scrollable in the same direction layouts like LazyColumn and Column(Modifier.verticalScroll()) is not allowed`.

We could use a plain `Column` instead of a scrollable one (lazy or not) but that will mean all tabs will have to be loaded at once. And there maybe be many such tabs to load which might mean a performance impact especially since we are keeping in memory the expanded status of a collection for when users come back to homescreen.

I think keeping the current implementation with tabs added / recycled on the fly is still the best option.
Thoughts?

**Comment by gabrielluong** [comment]
> @gabrielluong Regarding migrating the list for collection tabs to a `LazyColumn` that might not be easily possible because we are already in a vertically scrollable parent. Tried that and I am getting `Nesting scrollable in the same direction layouts like LazyColumn and Column(Modifier.verticalScroll()) is not allowed`.
> 
> We could use a plain `Column` instead of a scrollable one (lazy or not) but that will mean all tabs will have to be loaded at once. And there maybe be many such tabs to load which might mean a performance impact especially since we are keeping in memory the expanded status of a collection for when users come back to homescreen.
> 
> I think keeping the current implementation with tabs added / recycled on the fly is still the best option. Thoughts?

Makes sense. We can revisit this when we are no longer nesting in a RecyclerView.

**Comment by Mugurell** [comment]
@ QA This changed how the collection tabs work under the hood but the UX should be exactly the same as before.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed with the latest Nightly 102.0a1 (2022-05-18T17:12:12.001240).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Google Pixel 4 (Android 12).

Closing the ticket as fixed.
