### ISSUE TITLE
 UI test failure - Refactor code to include composable UI tests

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#24315]
### Firebase Test Run:
[Provide a Firebase test run report link here showcasing the problem](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7394319369318349606/details?stepId=bs.e4d46f1b7d3f231e&testCaseId=1)
### Build: 
No builds yet since code isn't merged.
Will update as soon as a build is out.

**Comment by sv-ohorvath** [comment]
Fixed in https://github.com/mozilla-mobile/fenix/pull/24574
