### ISSUE TITLE
SecurityError: The operation is insecure message is displayed when trying to lock screen orientation

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#24320]
### Steps to reproduce

1. Go to https://usefulangle.com/demos/105/screen.html
2. Tap the "Lock to landscape Mode"
3. Go to https://bug1681572.bmoattachments.org/attachment.cgi?id=9192275
4. Tap the "Lock" button
5. Go to https://w3c-test.org/screen-orientation/lock-basic.html
6. Perform the test.

### Expected behaviour

No error message should be displayed when trying to lock screen orientation.

### Actual behaviour

The SecurityError: The operation is insecure message is displayed on all 3 websites when trying to lock screen orientation.

### Device name

Google Pixel 6

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1 2022-03-17

### Additional information

![1647532552115](https://user-images.githubusercontent.com/50983519/158843494-bbf18bd3-e532-4da6-a361-64969ffd7740.JPEG)
![1647532551936](https://user-images.githubusercontent.com/50983519/158843517-2f33dfaf-af03-4777-9c3d-10ea416d675b.JPEG)
![Screenshot_20220317-175828](https://user-images.githubusercontent.com/50983519/158843540-1394c777-9c4d-4bab-bd2b-86f12179ee28.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19885)

**Comment by Mugurell** [comment]
@calumozilla I see the same on GVE. Are this results expected?

**Comment by calumozilla** [comment]
Yes, it's expected as of now. The corresponding bug for GV is https://bugzilla.mozilla.org/show_bug.cgi?id=1744288.

**Comment by robovoice1** [comment]
This are the results:
![Screenshot_20220318-145118](https://user-images.githubusercontent.com/92784377/159017933-df11544e-d0f6-4fb0-8643-062623b71f5e.png)
![Screenshot_20220318-150120](https://user-images.githubusercontent.com/92784377/159017996-a0a1442d-55db-40fd-bf53-1f839116f773.png)
![Screenshot_20220318-150207](https://user-images.githubusercontent.com/92784377/159018097-d456b2c5-a1d8-4ebf-b339-76fb52ba7798.png)

Google Pixel 6 pro
Android 12 GrapheneOS (latest beta channel release)
Firefox nightly mobile android
100.0a1 (Build #2015869419), 55c707a41+
AC: 100.0.20220317143136, 57163139b4
GV: 100.0a1-20220317092857
AS: 91.1.0

**Comment by robovoice1** [comment]
Vanadium (chromium based) browser:
![Screenshot_20220318-154421](https://user-images.githubusercontent.com/92784377/159025131-d548862c-af37-4986-b506-5088bf797d43.png)
![Screenshot_20220318-154521](https://user-images.githubusercontent.com/92784377/159025196-b148d99d-814f-4305-ac1c-75cdaf6e62f9.png)
![Screenshot_20220318-153646](https://user-images.githubusercontent.com/92784377/159025258-221762ae-0284-4a4f-944f-8a3f888777ba.png)
![Screenshot_20220318-153223](https://user-images.githubusercontent.com/92784377/159025324-90b255ac-48cd-42e6-aabf-f639535ecc7f.png)

**Comment by makotokato** [comment]
I think that this issue may be https://bugzilla.mozilla.org/show_bug.cgi?id=1763052

**Comment by Mugurell** [comment]
> I think that this issue may be https://bugzilla.mozilla.org/show_bug.cgi?id=1763052

Tested on the current Nightly which should include that fix and the `SecurityError` popup still shows.

**Comment by makotokato** [comment]
> > I think that this issue may be https://bugzilla.mozilla.org/show_bug.cgi?id=1763052
> 
> Tested on the current Nightly which should include that fix and the `SecurityError` popup still shows.

My comment is for [WPT failure](https://github.com/mozilla-mobile/fenix/issues/24320#issuecomment-1072448740).

I guess that your issue is out of scope of screen orientation API (https://w3c.github.io/screen-orientation/#locking-the-screen-orientation) spec. Blink is that "pre-lock conditions" includes fullscreen request is pending too. But Gecko doesn't. It will be https://bugzilla.mozilla.org/show_bug.cgi?id=1744288. We will be fix it for web compatibility.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810199

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
