### ISSUE TITLE
[Bug]: ﻿On Android 13 DP2 and the context menu is completely broken

### ISSUE THREAD

**Issue by D4v1dH03** [mozilla-mobile/fenix#24341]
### Steps to reproduce

1. Have any tab with text open (e.g. the Mozilla CPG)
2. Select any text

### Expected behaviour

should be able to copy/cut/paste text

### Actual behaviour

Discovered that the context menu hangs and users cannot select anything from the menu
and they can select other text but the context menu still stucks in there

### Device name

Google Pixel 4a (5G) [bramble]

### Android version

Android 13 DP2

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1 (Build #2015869419), 55c707a41+

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1760569

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by makotokato** [comment]
@ghost
If you can reproduce this on Android 13 beta or GA, let me know. I cannot reproduce this with Pixel 4a + Android 13 beta.
