### ISSUE TITLE
[Bug]: Possible dead code. Used method reference instead of invoking.

### ISSUE THREAD

**Issue by jknair0** [mozilla-mobile/fenix#24342]
> @Mugurell  i think there is a problem here! you forgot to invoke this method. instead used a method reference
> 
> _Originally posted by @jknair0 in https://github.com/mozilla-mobile/fenix/pull/22067#r830304436_

**Comment by Becky-art** [comment]
> @Mugurell  i think there is a problem here! you forgot to invoke this method. instead used a method reference
> 
> _Originally posted by @jknair0 in https://github.com/mozilla-mobile/fenix/pull/22067#r830304436_

**Comment by Mugurell** [comment]
@ QA This can be verified based on whether the telemetry for [pocket.home_recs_shown](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/pocket_home_recs_shown) is correctly registered.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox RC 99.1.0 and the pocket.home_recs_shown event is registered correctly. https://debug-ping-preview.firebaseapp.com/pings/Laur-001
### Device used:
- OnePlus 6T (Android 9)
