### ISSUE TITLE
Android Add-ons / Extensions 

### ISSUE THREAD

**Issue by PeterKW** [mozilla-mobile/fenix#24348]
https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/

Is there a way of installing add-ons such as sponsor Block/skip for YouTube?

**Comment by Nojuuu** [comment]
At the moment it is still only possible in Nightly.

Here is a better guide on how to do it:
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by PeterKW** [comment]
> At the moment it is still only possible in Nightly.
> 
> Here is a better guide on how to do it:
> https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

Oh, how strange. I thought that's what I had done but it seems to be working now. Thanks!
