### ISSUE TITLE
FNX3-16322 ⁃ harmonize history and bookmarks style in library

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2435]
_It's more polish than a feature request. The feature request label was automatically added because I accidentally used an issue template._

History and bookmarks are both part of the library but there are a few visual differences that should be eliminated so that the overall picture is consistent.

### What / Requirements
* [x] Show url for bookmarks
* [x] unify spacing
* [ ] Add additional options to the History item menu (Copy, Share, Open in new tab, Open in private tab, Delete)
* [ ] Replace the edit with a share icon in top bar on Bookmarks multi-select view to match History

### More details
1) List view:

![fenix](https://user-images.githubusercontent.com/1100614/57573089-72c98e80-7423-11e9-8cee-c181a243f514.png)UNITO-UNDERSCORE!1!

There are three obvious differences:

* [x] FIXED - a) Both views have a different icon style. This should be unified in any case.
* [x] FIXED - b) The history shows URLs, bookmarks not. Fennec and Chrome both shows the URLs also for bookmarks so I vote for doing the same.
* [x] FIXED - c) There is another difference: In the history the menu icons of the items are below the [x] icon in the toolbar. In the bookmarks view the position is too far left.
* [x] FIXED - d) I also suggest to reduce the spacing between the page title and the URL similar to the spacing on the tabs view on the home screen.

2) Menu:

![fenix](https://user-images.githubusercontent.com/1100614/57573197-3c404380-7424-11e9-996a-27dd490f952f.png)UNITO-UNDERSCORE!2!

* [ ] a) The menu in the history has only a "Delete" menu item, the menu in the bookmarks view has a few more. "Edit" and "Copy" make no sense in history, but all others make sense in both menus: Select, Share, Open in new tab, Open in private tab. These items should either be in history _AND_ bookmarks or in none of them.

3) Multi select:

![fenix](https://user-images.githubusercontent.com/1100614/57573225-a822ac00-7424-11e9-993a-7bbd900ca8e8.png)UNITO-UNDERSCORE!3!

There are two obvious differences:

* [x] FIXED - a) Both views have a different checkmark style. This should be unified in any case.
* [ ] b) The toolbar in the history has a share icon, the toolbar in the bookmarks view a edit icon. First I thought this difference is okay because edit as primary action makes sense in the bookmarks view. But then I noticed that you can't edit more than one bookmark at the same time. Once you select two bookmarks the edit icon disappears. So a edit icon as action in the multi select view doesn't make sense at all because if you only want to edit one bookmark you won't use the multi select mode. So this should probably be changed to the share icon. This will work for more than one tab (according to #2377) and would be consistent with the history view.

**Comment by boek** [comment]
@topotropic could you take a look at #2435? :)

**Comment by topotropic** [comment]
Thanks @cadeyrn for the feedback!

1b) I agree that showing the URL for bookmarks might add helpful information.
1d) I'll look into the spacing issues.
2a) Makes sense to add additional options to the History item menu (Copy, Share, Open in new tab, Open in private tab, Delete)
3b) Yes, sounds reasonable to replace the edit with a share icon in top bar on Bookmarks multi-select view

**Comment by cadeyrn** [comment]
For 1b and 1d I already created PRs with screnshots for comparison: #2580 and #2626.

**Comment by obarzpaw** [comment]
I would like to work on this

**Comment by obarzpaw** [comment]
@NotWoods @boek @cadeyrn 

I've changed icon on the bookmark toolbar and create PR for that bug.

And after merge I can fix the last one bug in the seperate PR.

**Comment by ekager** [comment]
Reopening because a few of these items in the checklist were not completed. ie matching the 3 dot menu options

**Comment by obarzpaw** [comment]
I can take care about this issue one more time :)

**Comment by KaairaGupta** [comment]
@ekager may I be assigned this?
I have noticed two of the requested features missing in the latest master and would like to work on those, they are:
- matching the three-dot menu
- though the bookmark shows 'share' icon instead of 'edit' in the bookmarks tab, but it doesn't show any option on multi-selecting the bookmarks.

**Comment by topotropic** [comment]
I'll close this issue. We have follow up issues for 
- sharing multiple bookmarks https://github.com/mozilla-mobile/fenix/issues/8652
- aligning 3-dot menus between bookmarks and history https://github.com/mozilla-mobile/fenix/issues/8651
