### ISSUE TITLE
Please make bookmark list collapsible 

### ISSUE THREAD

**Issue by Deweywsu** [mozilla-mobile/fenix#24356]
When I go to add a new bookmark in Firefox for Android, I have to scroll through a huge list of my bookmarks because they're all shown fully expanded, and can't be collapsed. Please make this collapsible.

**Comment by DavidJCobb** [comment]
Included in #15484.

**Comment by sflorean** [comment]
@Deweywsu please follow #15484 for more infos. Closing as duplicate since the same issue is already reported.
