### ISSUE TITLE
[Bug]: Emoji don't work on Android DP2

### ISSUE THREAD

**Issue by rsheeter** [mozilla-mobile/fenix#24350]
### Steps to reproduce

1. Open a page that renders emoji using the OS font.
   * I tested with https://codepen.io/rs42/full/Rwxavvx ("FRESH" rendered using a color font from Google Fonts, Mango emoji rendered using default system font)

### Expected behaviour

Text and emoji should both render, preferably using COLRv1 vector fonts, but if not then perhaps using the fallback glyphs for "Fresh" and the system bitmap font for the mango.

### Actual behaviour

Firefox renders the color font using fallback monochrome glyphs (makes sense) and doesn't render the emoji at all (sad panda). Chrome renders both in color.

| Firefox | Chrome |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/6466432/159136217-4211062d-a223-461b-8845-c4cbdb2e7a31.png" width="256"> | <img src="https://user-images.githubusercontent.com/6466432/159136220-750f108c-0505-480e-ab78-8bafb39aa9ed.png" width="256"> |

### Device name

Google Pixel 5a

### Android version

Android 13 DP2 (TPP2.220218.010)

### Firefox release type

Firefox

### Firefox version

98.2.0 (Build #2015868579), 2b529a583+ AC: 98.0.12, 9ad94b2a33 GV: 98.0.1-20220313140707 AS: 91.0.1

### Device logs

N/A, no crash occurs

### Additional information

This occurs because the system emoji font has moved from being a bitmap font to being a color vector font. Further details:

* https://android-developers.googleblog.com/2022/03/second-preview-android-13.html notes the use of Color vector fonts. * https://developer.chrome.com/blog/colrv1-fonts/ has additional context on the format.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1740525 covers core support for COLRv1. 

I _think_ filing this bug specifically for the Android issue is right, apologies if not. 

A bit of additional context: In DP2 the only emoji in the system image is COLRv1. In future builds of Android 13 we expect to add the bitmap font back as NotoColorEmojiLegacy.ttf. However, this will be marked with `ignore="true"` in fonts.xml and none of the system APIs will "see" it. That is, the API Firefox uses to find emoji (https://searchfox.org/mozilla-central/source/gfx/thebes/gfxFT2FontList.cpp#1402) will still return the COLRv1 font. I believe for emoji to render Firefox needs to do one of:

1. Implement support for COLRv1
   * Preferred as Android 14 is expected to only ship a COLRv1 font for emoji. 
1. Write custom code to ensure the legacy CBDT font is selected when present
   * It will be the first und-Zyse font in fonts.xml, as shown below

   ```xml
    <family lang="und-Zsye" ignore="true">
        <font weight="400" style="normal">NotoColorEmojiLegacy.ttf</font>
    </family>
    <family lang="und-Zsye">
        <font weight="400" style="normal">NotoColorEmoji.ttf</font>
    </family>
    <family lang="und-Zsye">
        <font weight="400" style="normal">NotoColorEmojiFlags.ttf</font>
    </family>
   ```

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1760567

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
Thank you for the detailed report. The Fenix team does not work on the Gecko core. I have moved your report to Bugzilla where the correct developers can evaluate it.
