### ISSUE TITLE
improvement for add-on manager

### ISSUE THREAD

**Issue by koritime** [mozilla-mobile/fenix#24355]
### What is the user problem or growth opportunity you want to see solved?
- would like additional functionality to current firefox android add-on manager to search for other add ons and add them in the add-on manager
- firefox nightly has a similar function existing, would like this to be made more available to the public 
- currently add on manager only shows recommended and I dont like to open a whole website to search for the add ons
- 
### How do you know that this problem exists today? Why is this important?
- currently add on manager only shows and can add reccomended add on
- if we want to search for other add ons would need to navigate out of the settinfs

### Who will benefit from it?

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19906)

**Comment by PranavBhattarai** [comment]
Firefox's whole idea to restrict/limit users to modify their browser is a bad thing for Firefox in a long run.
The longer it gets the more Kiwi Browser wins.

**Comment by bat999** [comment]
Maybe (for now) make the ~17 "Add-ons" available to all **Firefox for Android** users.
Or at least for **Firefox for Android Beta** users.
But leave the "Custom Add-on collection" to **Nightly** users.

**Comment by lindongbin** [comment]
It's time to open up installation permissions for all extensions, instead of replacing them with a collection of extensions. Also remove the option to block dangerous and scam content, Internet access is my freedom, not Firefox to decide what I should and shouldn't access, at least it should be an option.

**Comment by PandoraHayami** [comment]
I think it would be more accurate that the extensions parts of Android components is not complete yet and few extensions (But definitely more than in the add-on manager) do actually work.

**Comment by gomarcus** [comment]
No more excuses! I have been donating regularly just to watch how more and more liberties and decision-making authority were taken away. I think this "big brother knows what's best for you" attitude is in stark contrast to the former "all power to the user" approach. Would feel guilty to fund this even longer. 😢

If I wanted to be restricted, pampered and told what to do, I would use Apple, Google or Microsoft... ✊
