### ISSUE TITLE
Can't force psychologytoday website to dark mode

### ISSUE THREAD

**Issue by superbonaci** [mozilla-mobile/fenix#24361]
Can't force this website to dark mode, even though Firefox Nightly is set to it:

https://www.psychologytoday.com/us/blog/my-side-the-couch/202203/why-you-need-be-happy-alone-be-close-another-person

![](https://i.imgur.com/5SdGhvh.jpg)

**Comment by kbrosnan** [comment]
Looks to be a duplicate of https://github.com/mozilla-mobile/fenix/issues/2139

The website does not seem to have a dark mode. You can use the dark reader extension to resolve this problem.

**Comment by superbonaci** [comment]
> Looks to be a duplicate of #2139
> 
> The website does not seem to have a dark mode. You can use the dark reader extension to resolve this problem.

Great, this worked:
[Dark Reader](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) by Alexander Shutau
