### ISSUE TITLE
Pocket stories show empty images

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24362]
Most of the stories from Pocket (having Pocket as publisher) show an empty image.

<img src="https://user-images.githubusercontent.com/11428869/159221259-0fb7a513-b2ae-4f78-a9e9-6f02adb88c3d.png" width="33%" />

The response we get from server has `null` for the `imageUrl` so there is little we can do.
Opened the tickets just to raise awareness of this situation. Will inform Priya from Pocket about it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19909)

**Comment by Mugurell** [comment]
Based on https://github.com/mozilla-mobile/fenix/issues/21626 we should've filtered out these stories.
Not happening atm because in these cases the url actually has the form "https://img-getpocket.cdn.mozilla.net/{wh}/filters:format(jpeg):quality(60):no_upscale():strip_exif()/ **null** "
Will do that in AC.

**Comment by Mugurell** [comment]
This will first be tried to be fixed on Pocket's side.

**Comment by Mugurell** [comment]
This should be fixed by https://github.com/mozilla-mobile/android-components/issues/11905 by allowing the image of an existing article to be updated but for actually testing this in the real world we depend on the data Pocket sends and at the moment this issue is not entirely fixed on their end so it may still be possible for the app to show empty images.

Checking just now the response we get from Pocket I still see 5 stories with blank images.

**Comment by kbrosnan** [comment]
Can we try again to get a non-null result?

**Comment by cpeterso** [comment]
> This should be fixed by [mozilla-mobile/android-components#11905](https://github.com/mozilla-mobile/android-components/issues/11905) by allowing the image of an existing article to be updated but for actually testing this in the real world we depend on the data Pocket sends and at the moment this issue is not entirely fixed on their end so it may still be possible for the app to show empty images.
> 
> Checking just now the response we get from Pocket I still see 5 stories with blank images.
