### ISSUE TITLE
[Bug] Fenix stuck on opening a link after startup

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2438]
## Steps to reproduce
1. Open https://www.latimes.com/entertainment/movies/la-me-peggy-lipton-dead-20190511-story.html?outputType=amp 
1. Fenix doesn't load it
1. Force close Fenix
1. Open Fenix, wait for page to load/tap location bar, hit enter

### Expected behavior
Fenix should load page pretty much immediately 

### Actual behavior
Fenix looked stuck. After a few minutes, it eventually loaded.

Hopefully the logcat will be interesting.

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3169756/logcat.txt)

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by sarentz** [comment]
Is there a difference if the `?outputType=amp` is removed?

**Comment by sarentz** [comment]
@yoasif is this still happening?

**Comment by vesta0** [comment]
Closing. @yoasif please re-open if this is still happening.

**Comment by yoasif** [comment]
WFM, sorry - missed the last email.
