### ISSUE TITLE
Newly created collections are not highlighted

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24389]
Creating a new collection from tabs tray and pressing "View" in the snackbar should scroll to and focus to the newly created collection while also animating a border around it, something implemented in https://github.com/mozilla-mobile/fenix/issues/2899.

Seems like this functionality has been broken for a while because it was based on a [hardcoded number of homescreen sections above collections](https://github.com/mozilla-mobile/fenix/blob/389cb91267f9113c3679120026d081b4a068f573/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L1183-L1187) and there have been many updates to these sections including an option to enabled or disable them which would've affect the functionality.

The old functionality can still be seen if disabling all homescreen sections above collections:

https://user-images.githubusercontent.com/11428869/159529127-cbe07d07-b47c-40e6-b9f0-fa6d0b0ae794.mp4

&nbsp;

Since this isn't working for quite some time maybe the homescreen migration to compose is the right time to assess whether this functionality is needed and should be migrated or not.
@topotropic  @kbrosnan

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19924)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809827

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
