### ISSUE TITLE
The credit card autofill behaves incorrectly 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#24387]
Preconditions
On Fenix, go to about:config and set the following preferences:
- search for browser.search.region and set it to one of the following regions: US, CA, GB, FR, DE.
- search for extensions.formautofill.supportedCountries check that the following are displayed: US, CA, GB, FR, DE.

### Steps to reproduce
1. Have one or more credit cards saved.
2. Access a purchasing website what has a credit card form (https://checkout.stripe.dev/, https://www.instant-gaming.com).
3. Tap on the credit card number/credit card name field -> observe if the "Select credit card" prompt is displayed.
4. Select a saved card from the prompt -> Observe the data displayed on the card.
5. Tap on the CC number/CC name fields and delete/add some numbers/characters -> Observe if the prompt is displayed.
6. Tap on the CC number or on the CC name fields and delete/add some numbers/characters -> Select a saved card from the prompt (does not have to be the credit card previously used).
7. Observe if the fields are properly updated with the selected data.

### Expected behaviour

After Step 3, the "Select credit card" prompt should be displayed right after tapping on the CC number/CC name field the first time.
After Step 4, the CC data is correctly imported.
After Step 5, when deleting characters from a field, the "Select credit card" prompt should be displayed.
After Step 7, all the fields are updated with the correct data from de selected card.

### Actual behaviour
After Step 3, the "Select credit card" prompt is only displayed after tapping the second time on the CC number/CC name field or on another field.
After Step 4, the card name is not passed to the CC name field, unless manually edited and the expiration date is not passed at all (https://github.com/mozilla-mobile/fenix/issues/19559).
After Step 5, the "Select credit card" prompt is not displayed at all times. Sometimes, the prompt will be displayed only if the field is cleared and taps again.
After Step 7, only the field not edited in Step 6 with be updated with the correct data. The field edited in step 6 remains unchanged.  
If both the CC number/CC name fields are edited (characters are removed/added, but the field is not empty), after accessing the prompt and selected the same previously used saved card, only one field will be updated, the field from which the prompt was accessed.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

98.2.0

### Additional information

Note that this is a regression on Firefox Android after Credit Card Autofill for UK, FR, and DE regions PI on Desktop https://mozilla-hub.atlassian.net/browse/QA-1258.

https://user-images.githubusercontent.com/89388888/159447826-03ab2e94-8744-4cb2-b55f-7e996c1c18bc.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19923)

**Comment by delia-pop** [comment]
Furthermore, after Step 7 is was also observed that the data in the the edited fields might not be properly updated: 

- on https://www.instant-gaming.com, after selecting a saved card, the card name will not be displayed on the card unless the user taps on the page.
- on https://www.instant-gaming.com, if both the CC number/CC name field are edited (characters are removed/added, but the field is not empty), after accessing the prompt and selected the same previously used saved card, only one field will be updated, the field from which the prompt was accessed.
- on https://checkout.stripe.dev/preview, if both the CC number/CC name field are edited, after accessing the prompt and selected the same previously used saved card, both fields will be updated with the data saved on the card, regardless of the field from which the prompt was accessed.

https://user-images.githubusercontent.com/89388888/159523775-c811fcd5-009f-4f00-ba1d-f373b38a84bd.mp4

**Comment by cpeterso** [comment]
The corresponding Jira issue: https://mozilla-hub.atlassian.net/browse/FNXV2-19923

**Comment by cpeterso** [comment]
This issue has not been fixed.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814162

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
