### ISSUE TITLE
[Bug]Fenix crashes while switching tabs

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#2439]
## Steps to reproduce
Open fenix with several tabs. Select one tab. Go back to tab overview page. Hit android home button to minimise all apps.

### Expected behavior
Not to crash

### Actual behavior
Crashed. No crash report in about:crashes

### Device information
* Fenix version: latest apk

![Screenshot](https://user-images.githubusercontent.com/922368/57581116-abb54200-74bb-11e9-8bf4-6fcdd6031e8a.png)UNITO-UNDERSCORE!20190428-135941!UNITO-UNDERSCORE!Settings!

**Comment by andreicristianpetcu** [comment]
video here https://imgur.com/a/mN7Mz62

**Comment by cadeyrn** [comment]
#2436 has the exception message.

**Comment by andreicristianpetcu** [comment]
Should I close this one then? @cadeyrn

**Comment by sv-ohorvath** [comment]
Does this still happen on your device, @andreicristianpetcu? If it was fixed by #2436, then you can close it.

**Comment by andreicristianpetcu** [comment]
It works now. No crash.
