### ISSUE TITLE
FNX3-16326 ⁃ [Meta] Sharing Sessions

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#244]

**Comment by bbinto** [comment]
@shorlander and @lime124 to help me out what the minimal MVP could be for this one, e.g. maybe without building the entire infrastructure of bundling sharing sessions in a convenient, smart way, we might just collect some sort of URLs in a format that is very easily shareable, we could then learn how many people try to share it to evaluate a better solution.

I'm really trying to iterate/validate as quickly as possible.

My questions to you
What do we believe is a the first minimal (not perfect) solution of this? Include all URLs in a session, share it via email and include all URLs in it?

**Comment by shorlander** [comment]
I think there are a few options for this. Will report back with some potential flows.

**Comment by vesta0** [comment]
Dup of #1585
