### ISSUE TITLE
Investigate why we are sending native crash to Sentry even when sendEventForNativeCrashes is disabled

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#24403]
https://sentry.io/organizations/mozilla/issues/3109753317/?project=6176959&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-1w&statsPeriod=14d

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/issues/11940.

**Comment by csadilek** [comment]
This appears to still be happening in 101 Nightlies. The fix above landed in 100. Reopening.

https://github.com/mozilla-mobile/android-components/commit/1937af35cc2166b8082f0bda368895902208db47

**Comment by csadilek** [comment]
Correction. This is trending down now. So these 101 reports must've been pending submissions from earlier crashes before the fix landed. Closing.
