### ISSUE TITLE
[Library update] Update LeakCanary to 2.0

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/fenix#2441]
:construction: :construction: :construction:

Status: **ON HOLD**.
LeakCanary `2.0-alpha-1` can't be used with Flipper yet. See [this comment](https://github.com/mozilla-mobile/fenix/issues/2441#issuecomment-491593129) for details.

:construction: :construction: :construction:

### What
Some time ago [@pyricau](https://github.com/pyricau) released Leak Canary version `2.0-alpha-1`. I think we should update to it.

### Why?
Version 2 has some very nice improvements, e.g.:

* easier setup and configuration;
* faster and more efficient heap dump analyzing (rewritten from scratch);
* some helpful heuristics for finding/fixing leaks;
* better [logo](https://raw.githubusercontent.com/wiki/square/leakcanary/assets/logo-2.0.png) :cat: ;
* and [much more](https://github.com/square/leakcanary/issues/1211)

### Acceptance Criteria (how do I know when I’m done?)
New LeakCanary functionality still detect memory leaks.

### Usefull links
* [(Youtube) LeakCanary 2 presentation on Android Makers 2019](https://www.youtube.com/watch?v=LEX8dn4BLUw).
* [Changelog for Version 2.0 Alpha 1](https://github.com/square/leakcanary/blob/master/CHANGELOG.md#version-20-alpha-1-2019-04-23).
* [Migration Guide](https://github.com/square/leakcanary/wiki/Migrating-to-LeakCanary-2.0).

P.S. I'm preparing PR for Fenix project codebase. It'll be ready soon.

**Comment by dector** [comment]
**Update**. Seems like we need to wait for [next release](https://github.com/square/leakcanary/milestone/7) to use LeakCanary 2 with Flipper.

[Required API](https://github.com/square/leakcanary/pull/1314/files#diff-f034851ce0acffe68735cf7f6e4a2e5eR28) was added into LeakCanary after `2.0-alpha-1` release.

**Comment by ekager** [comment]
Hi @dector we have since removed Flipper from our project. Do you still want to handle updating the library? It should be easier now :)

**Comment by dector** [comment]
Awesome. :D

Sure. I'll update my PR today / on weekend.
