### ISSUE TITLE
Enable Clear Site Data 

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/fenix#24414]
per advise from @kbrosnan let's enable this to v99 Beta.

val **showClearSiteData** = Config.channel.isNightlyOrDebug

**Comment by maglieria** [comment]
want boots for men?
Maglieriapelle  is derived from "woven leather" in Italian. We have a storied history of handcrafting premium leather shoes and proudly serve the apparel needs of men who appreciate originality, creativity and a profound sense of achievement
[boots for men](https://www.maglieriapelle.com/collections/boots)
