### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest.verifyContextOpenLinkNewTab>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24419]
### Firebase Test Run:
Failed 1x on 3/22 Main 
[Firebase link](url)
[Firebase link](url)

### Stacktrace:
[Logcat](https://github.com/mozilla-mobile/fenix/files/8334472/verifyContextOpenLinkPrivateTab.txt)
[Logcat](https://github.com/mozilla-mobile/fenix/files/8334473/verifyContextOpenLinkPrivateTab2.txt)

**Comment by AndiAJ** [comment]
Failed 1x on 3/23 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.a7bc7b0ca0808b84/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.3417c1ece10bfd0d/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
A11y issue causing the failure was fixed, can be reopened if it fails again.
