### ISSUE TITLE
Unlock Firefox button doesn't work

### ISSUE THREAD

**Issue by mike-pt** [mozilla-mobile/fenix#24423]
### Steps to reproduce

1. Enable Firefox has your autofill service
2. Open an app that requires login and you know you have it in Firefox (my test is plex in logs and video but happens in all apps)
3. Press Unlock Firefox 

Please note that this happen in Firefox, Firefox Beta, and nightly

### Expected behaviour

I should be prompted to unlock 

### Actual behaviour

Nothing happens

### Device name

Poco F2 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

### Device logs
[log.log](https://github.com/mozilla-mobile/fenix/files/8335330/log.log)

### Additional information

https://user-images.githubusercontent.com/2327910/159762596-6985363b-5f5e-4906-92b7-453513ee22c1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19950)

**Comment by mike-pt** [comment]
Also please note that the device has a PIN and Fingerprint for lock/unlock

**Comment by mike-pt** [comment]
So I got it to prompt for it, I went to permessions -> other -> Display pop-up windows wile running in the background, and it prompts, but no passwords or logins show.

**Comment by DiegoARL38** [comment]
Giving the permission to Firefox as suggested by @mike-pt has solved this issue for me (reported in a [#2307 comment](https://github.com/mozilla-mobile/fenix/issues/23707#issuecomment-1072605939)).

Sadly, after unlocking, no login suggestions appear. Fortunately, going to another screen in the app, going back to the login screen, and tapping the username field makes a Search Firefox Nightly button appear, and tapping it displays the Firefox's login search UI.

I'd recommend adding a message to inform users of the possible need to give the permission when enabling autofill in other apps in Firefox settings. I wouldn't have known to do it, nor that it is needed in my device or use case.

**Comment by darkship** [comment]
> So I got it to prompt for it, I went to permessions -> other -> Display pop-up windows wile running in the background, and it prompts, but no passwords or logins show.

- I added the permission
- taped on "unlock firefox"
- fingerprint unlock prompted
- taped on the email input -> nothing
- closed the app
- reopen the app
- taped on the email input -> "search in firefox" appeared

**Comment by Mugurell** [comment]
Having to switch apps after unlocking should soon be fixed.
Curious about the need of that system permission (great finding @mike-pt !), it might be needed only on specific devices.
I see @mike-pt using a `Poco F2 Pro` with Android 11.
@darkship , @DiegoARL38 Can you share what devices you saw this issue on?

**Comment by DiegoARL38** [comment]
@Mugurell I've got a Xiaomi Redmi Note 8 with MIUI 12.5.1.0 (Android 11).

**Comment by darkship** [comment]
@Mugurell 
I've got a Xiaomi Redmi Note 10 Pro with MIUI 12.5.7 (Android 11). It works here now.

I still can't make it work on my Moto X4 (android 9). I didn't find "Display pop-up windows wile running in the background", it might be too old

**Comment by mike-pt** [comment]
Yeah I questioned the same in the other thread about issues with getting the auto fill to work even after having this done, it seems most are using MIUI and android11.

But MIUI is not the only ROM offering more control over privacy / permissions especially since android 11, so this is likely to affect more ROMs.

`Display pop-up windows wile running in the background"` shows in "Other Permissions" in the app details screen, but I think this is only an option since 11 or maybe 10

**Comment by darkship** [comment]
Ha! I just found about my Moto X4 (android 9).

I had to long press on the password field so that "auto fill" can be selected.
Then it asks me unlocking firefox and tells me that firefox couldn't validate the app (discord).

Depending on which app I try to unlock, the login isn't filled, for example with the steam app it works but not with discord.
I suppose that when the login isn't/can't be filled it is the same issue as for web pages where the login isn't marked as "login"

**Comment by Juriyx** [comment]
> Then it asks me unlocking firefox and tells me that firefox couldn't validate the app (discord).

The same situation when the mentioned "Other permission" is allowed

**Comment by thomasleplus** [comment]
I am facing the same issue so I wanted to try what https://github.com/mozilla-mobile/fenix/issues/24423#issuecomment-1079584213 suggests but I can't find the Permissions -> Other -> Display pop-up windows while running in the background. I am on a Pixel 6 with Android 12 in case it's relevant.

**Comment by Mugurell** [comment]
Continuing from https://github.com/mozilla-mobile/fenix/issues/24257#issuecomment-1119918601, does this issue seem resolved in the current Nightly?

**Comment by peterjanes** [comment]
Nightly works here, for the most part; it doesn't detect the current site/app, i.e. I always have to go through the search UI, but it does show the search prompt after unlocking (which I believe is the specific bug that was reported/fixed) and will fill the credentials fields once I've selected an account.

Pixel 2 XL, Android 11.

**Comment by mike-pt** [comment]
This mostly works however for example in IMDB I'm seeing the same issue where the the unlock button was inactive.

This is actually do to the same permission as I noted I the other ticket.

I've actually reset my phone a week ago, and other apps where working without me messing with any permissios at all.

I'm not sure if this is a regression with this fix (since my phone was reset) or its just due to how some apps work, but the fact is it's mostly working fine with the majority of apps, enabling draw over other apps permission just makes it work everywhere.

**Comment by twoexem** [comment]
Same thing happening to me on a Fairphone FP4 with Android 11. It worked shortly but now it doesn't anymore on normal Fenix.

**Comment by mike-pt** [comment]
So I switched to S22 Ultra and funny enough I don't need any extra permissions for autofill but I noticed passwords weren't getting suggested. It seems on s22 there's 2 settings so this is now broken for me again, should I file a separate issue for this?

![Screenshot_20220824-223049_Settings](https://user-images.githubusercontent.com/2327910/186527381-7ad45959-e613-44e4-bac7-0282fb445d16.jpg)

**Comment by twoexem** [comment]
This issue is fixed for me on Fenix 103.2.0 on stock Android 11. It just started working again one day, I can't provide a solution.

**Comment by mike-pt** [comment]
Actually it seem to work with some apps fine but not others (I'm on android 12) Instagram and teams don't autofill passwords but plex did... maybe there's something blocking it in the app.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813739

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
