### ISSUE TITLE
Enabling 'desktop site' toggled permently

### ISSUE THREAD

**Issue by PeterKW** [mozilla-mobile/fenix#24428]
Is there a way of enabling the 'desktop site' to be toggled permently for all website tabs from the settings page?

**Comment by cadeyrn** [comment]
No, it's not possible. If it was meant as feature request and not just as a question it's a duplicate of #7039.

**Comment by LaurentiuApahideanSV** [comment]
I will close this issue as duplicate of https://github.com/mozilla-mobile/fenix/issues/7039.

**Comment by PeterKW** [comment]
> I will close this issue as duplicate of https://github.com/mozilla-mobile/fenix/issues/7039. 

Ah right, okay. I ended up adding the UA extension to my Android Collection to pretend to be a desktop device for the equivalent result of desktop mode.
https://addons.mozilla.org/en-GB/firefox/addon/user-agent-string-switcher/
