### ISSUE TITLE
Try speculative connection earlier on start up (e.g. by moving the loadUrl call earlier, e.g. in IntentProcessor?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#24427]
We previously tried moving `loadUrl` early but found it actually made start up performance worse. However, since then we've discovered BZ-1734916 where we found out `loadUrl` calls may be posted to the UI thread and blocked by other operations which may have explained why this change didn't see an improvement.

We should try this again, particularly after that bug, and its suggested improvement in BZ-1734916, are addressed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19951)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802939

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
