### ISSUE TITLE
[Bug]: Cannot share files with the Web Share API.

### ISSUE THREAD

**Issue by ericmackrodt** [mozilla-mobile/fenix#24429]
### Steps to reproduce

1. Browse to this page on Firefox on Android: https://benkaiser.github.io/web-share-images/#/image
2. Tap the "Share Image" button

### Expected behaviour

The OS share dialog should open giving the user the ability to share the image with other apps.

### Actual behaviour

Nothing happens because navigator.canShare() apparently returns false for files.

It does work with text shares like this one:
https://w3c.github.io/web-share/demos/share-files.html

### Device name

Samsung Galaxy S20 FE

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

98.2.0

### Additional information

This issue has happened on all Android devices I tested, not only the one I put in the `Device Name`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19953)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-03-24. Might be related to https://github.com/mozilla-mobile/fenix/issues/24120
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by makotokato** [comment]
We don't support it yet (https://searchfox.org/mozilla-central/rev/b671b6390e88672543b9b7c82132be655bd98856/dom/base/Navigator.cpp#1520)
