### ISSUE TITLE
[Bug] default input rendering has rounded corners

### ISSUE THREAD

**Issue by karlcow** [mozilla-mobile/fenix#2443]
## Steps to reproduce
Create a document with 

```
<body>
<input type="search">
</body>
```

### Expected behavior
Have the corners of the input being square

### Actual behavior
The corners are round.
The only way for a designer to revert to the default rendering of every other browsers is to do 
 `border-radius: 0` so basically we are breaking the default expectations with regards to input.

### Device information
* Android device: Pixel 2 
* Fenix version: Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0

This was reported on https://github.com/webcompat/web-bugs/issues/29721

**Comment by cpeterso** [comment]
I filed GeckoView bug https://bugzilla.mozilla.org/show_bug.cgi?id=1574323 for this widget styling issue.

**Comment by cpeterso** [comment]
btw, we closed the GV bug as WONTFIX. Gecko's rounded widget corners (like iOS's) was a conscious design decision. The web doesn't promise pixel-perfect rendering across browsers or platforms. The difference between the round and square corners is pretty subtle.

https://bugzilla.mozilla.org/show_bug.cgi?id=1574323#c2
