### ISSUE TITLE
[Bug]: [Crash] Fenix 100.0a1 Crash Report [@ PLDHashTable::Search | mozilla::a11y::RemoteAccessibleBase<T>::RetrieveCachedBounds ]

### ISSUE THREAD

**Issue by sharbet** [mozilla-mobile/fenix#24430]
### Steps to reproduce

visit domains and subdomains such as

https://m.dcinside.com/board/galaxy

and browse each thread (to the comments at the bottom)

experience crash

### Expected behaviour

no crash

### Actual behaviour

crash

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

100

### Device logs

https://crash-stats.mozilla.org/report/index/f25e16ca-78b9-4fc6-a21c-3960f0220323

https://crash-stats.mozilla.org/report/index/168f12d8-77c4-4ab0-9779-54f9f0220324

https://crash-stats.mozilla.org/report/index/c9b9ba6d-5076-4bd4-abd3-28efc0220323

https://crash-stats.mozilla.org/report/index/14205251-aa3f-4005-90b0-393f00220323

### Additional information

other instances of crash id:

https://imgur.com/a/dLBo3dw

**Comment by sharbet** [comment]
After 100.0a1 20220323094932 update, it crashes almost immediately.

https://crash-stats.mozilla.org/report/index/fafafd48-2166-4d8c-9045-399820220324

**Comment by csadilek** [comment]
Thanks for reporting! We're tracking this in https://bugzilla.mozilla.org/show_bug.cgi?id=1761200.
