### ISSUE TITLE
[Bug]: tab_tray_inactive_auto_close_body_2 does not interpolate the placeholder

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/fenix#24439]
### Steps to reproduce

See the prompt offer to automatically closing inactive tabs. This have been reported by a user, I haven't seen it myself and I am not sure how to make the prompt to show up.

![photo1648140405](https://user-images.githubusercontent.com/3941344/159975343-fe332fee-4789-479d-8d44-fe2ca4fedde7.jpeg)

### Expected behaviour

`%1$s` in `tab_tray_inactive_auto_close_body_2` should be replaced by the application name.

### Actual behaviour

The text is rendered with `%1$s`.

### Android version

unknown

### Firefox release type

Firefox Beta

### Firefox version

unknown

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19962)

**Comment by Alexandru2909** [comment]
Hi @MikkCZ, this issue has already been addressed in #24188, it should be fixed in the latest Nightly.
