### ISSUE TITLE
[Bug]: "Report Site Issue" string is not localizable

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-mobile/fenix#24440]
### Steps to reproduce

1. In Firefox Beta or Nightly.
2. Navigate to an arbitrary page.
3. Open the menu.
4. There is _Report Site Issue_ item in the menu.

### Expected behaviour

The _Report Site Issue_ item in the menu, should be localized in the language same as the rest of Firefox UI.

### Actual behaviour

The _Report Site Issue_ item in the menu is always in English.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100a1

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/17166

See Delphine's comment in the dupe issue.
