### ISSUE TITLE
FNX3-16329 ⁃ [Bug] Fenix crashes when unlock device

### ISSUE THREAD

**Issue by LittleAngelwings** [mozilla-mobile/fenix#2444]
## Steps to reproduce
Open fenix
Open any site
Lock mobile or tablet
Unlock device

### Expected behavior
No crashes of fenix

### Actual behavior
Fenix crashes immediately after unlocking

### Device information
* Android device: Huawei P smart with Android / EMUI 8.0.0,SSamsung Galaxy Tab A (2016) SM-T580 with Android 8.1.0 
* Fenix version: 1.0.1919 (11321806) 5/12

**Comment by sblatz** [comment]
I cannot reproduce this. I believe it was an issue with our state restoration refactor.

**Comment by sv-ohorvath** [comment]
Cannot reproduce it either. Closing.
