### ISSUE TITLE
Remove Event.wrapper for SyncAccount metrics

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24454]
Breakout from #21292.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 100.0a1 (2022-04-04) by syncing with a browser from a desktop device.
Some events that were generated:
![image](https://user-images.githubusercontent.com/48829350/161561363-95e6e9f6-37c8-4251-823b-3fec05ef5510.png)
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.
