### ISSUE TITLE
Cross platform bookmarks management

### ISSUE THREAD

**Issue by Altair1234** [mozilla-mobile/fenix#2446]
Why does it have a separate folder for mobile bookmarks and then a bookmark toolbar on desktop and desktop/toolbar bookmarks on Android? Would be great if there was a unified approach: you bookmark a page and it appears on the tab as well as the mobile without any hassle of sorting between toolbar, mobile and desktop bookmarks.

**Comment by vesta0** [comment]
Closing for now and will re-open once we have completed user testing validating this use case.
