### ISSUE TITLE
Copy /paste image to/from clipboard 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#24474]
### Steps to reproduce

if I'm not wrong in 2020 chrome for Android added copy paste to/from clipboard feature can fenix get this too ?

### Expected behaviour

Fenix should be able to copy paste image from android clipboard 

### Actual behaviour

feature is lacking in fenix 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

100

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19978)

**Comment by LaurentiuApahideanSV** [comment]
I will mark this issue as a feature request.

**Comment by yoasif** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/17780.

**Comment by boek** [comment]
Closing as a dup #17780
