### ISSUE TITLE
[Bug]: Possible Epilepsy Warning (Ad/image flicker) 

### ISSUE THREAD

**Issue by funnyhowthatworks** [mozilla-mobile/fenix#24477]
### Steps to reproduce

**Possible Epilepsy Warning! **
**Please proceed with caution!**

Hello first time bug reporter! Sorry if I mess this up, and I really appreciate all the work you do!

I'm not sure if this is an isolated incident or an issue with the web page itself, but I did try this on Chrome too and it didn't seem to have the issue. Originally I was using the spin Android browser but was directed to try it on Firefox and report to you directly.

Here's the link https://www.usatoday.com/story/money/reviewed/2022/01/20/how-find-real-n-95-kn-95-mask-and-avoid-fake-ones/6579066001/
I happened to zoom into an ad and the whole page went all over the place. And started sorta flashing rapidity as a result. I'm not sure if it would be enough to cause any issues for someone with Epilepsy but I thought I'd report it in case because it can get quite flickery. It doesn't seem to happen every time,  I think maybe it has to do with how the ad is loaded in because sometimes the first add on the page doesn't seem to cause issue but the layer ones that load in as you scroll down do. *Be careful though the harshness of the flashing seems to depend on the color and design of the ad it can get pretty rapid! * while testing it looks like not just ads are affected but also at least some images too but I didn't try all the images and all the ad types on the page. Zooming just below and to the left of the ad or image seems to start the issue but other areas may start the issue too. I wrote the part about it not happening every time before I did more testing so I could be wrong although my phone might just be caching the page. After test the first image on the page after clearing the cache but not app data I was able to get the problem to occur. 

### Expected behaviour

Ad should enlarge on the screen, or images too. 

### Actual behaviour

Page seems to scroll by itself and ad image begins flashing rapidly

### Device name

Samsung Galaxy S21 5G

### Android version

12

### Firefox release type

Firefox

### Firefox version

98.3.0

### Additional information

I have a couple developer settings enabled

Veryfiying byte code of debuggable apps

WiFi Scan Throttling

Mobile data always active

And sometimes I have animations turned off

I tested with the slider for dev options on and off but not thoroughly and didn't restart phone between tests

If I can provide anything else to help please let me know :) also I'm assuming Firefox daylight is just Firefox, I didn't see just firefox in release type but I could be wrong

**Comment by marcel263** [comment]
This is an enormous amount of text while a screen recording would suffice just as well. please provide a recording

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Nightly 2022-03-28, but was unable to. @funnyhowthatworks  Could you upload a short video illustrating the issue?
### Devices used:
- Google Pixel 6 (Android 13)
- Oppo Find X3 (Android 11)

**Comment by funnyhowthatworks** [comment]
> I tried to reproduce the issue on Firefox Nightly 2022-03-28, but was unable to. @funnyhowthatworks Could you upload a short video illustrating the issue?
> ### Devices used:
> 
>     * Google Pixel 6 (Android 13)
> 
>     * Oppo Find X3 (Android 11)

Sure thing would you prefer a screen capture or just a video of the phone?

**Comment by kbrosnan** [comment]
Sounds like bz-1685648 though the website does not fix the viewport.

**Comment by kbrosnan** [comment]
Talked with some other folks and we agree that this is 1685648
