### ISSUE TITLE
[Bug]: Browser crashes

### ISSUE THREAD

**Issue by QARom** [mozilla-mobile/fenix#24488]
Galaxy A52 (Android 12)
Precondition:
1. The browser is installed and running
2. Any URL has been copied to the buffer in advance.

Steps:
1. Click the browser icon "Mozilla FireFox"
2. Touch and hold the address bar area until the context menu appears.
3. Touch the "paste" item in the context menu.

Expected Result:
Pasted URL is displayed in the address bar

Actual result:
Browser crashes.

A comment:
If the keyboard opens during step 2, close it otherwise the bug will not reproduce.

Screen record:
https://drive.google.com/file/d/1SoQVlM0lfOct1KXl9RbB1BDQaD8GxFup/view?usp=sharing

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19983)

**Comment by Mugurell** [comment]
@QARom Can you please use this steps - https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information to share a crash report or the logs for when that crash is occuring?

**Comment by delia-pop** [comment]
I also tried testing the flow on Release (98.3.0 and latest 99.1.0), latest Nightly (100.0a1 from 03/30) and latest Beta (99.0.0-beta5), but I was not able to reproduce the crash. 

Devices used:
Samsung Galaxy Note10 (Android 11).
Google Pixel 6 (Android 12).

https://user-images.githubusercontent.com/89388888/160852946-7c63d11c-4c00-4db0-b7ba-6522600e5043.mp4

**Comment by QARom** [comment]
@Mugurell @delia-pop @mavduevskiy This bug is currently unreproducible. Maybe I submitted too many bug reports and now the bug is strange. Thanks)
