### ISSUE TITLE
[Bug]: 429 error on swisscows.com

### ISSUE THREAD

**Issue by plwt** [mozilla-mobile/fenix#24481]
### Steps to reproduce

Go to https://swisscows.com/

### Expected behaviour

Page opens.

### Actual behaviour

429 Too Many Requests error

### Device name

Motorola Moto G30

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

98.0.2

### Additional information

Tested in Firefox for Android, Release, Beta, and Nightly.

Page opens in Chrome for Android and Firefox for Desktop.

User feedback - https://support.mozilla.org/en-US/questions/1371530

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19981)

**Comment by kbrosnan** [comment]
@plwt are you able to reproduce this? I am not able to reproduce using several devices. Is the user on a VPN or proxy?

**Comment by plwt** [comment]
Yes, I am able to reproduce this.

**Comment by plwt** [comment]
It is also reproducible on RB and Focus for Android Release.

**Comment by plwt** [comment]
I do not have mobile data, but I am able to reproduce on WiFi.

**Comment by kbrosnan** [comment]
Could you check with the user in support to see if you both use the same ISP?

**Comment by plwt** [comment]
Question has been asked.

**Comment by SternByName** [comment]
My mobile data provider is GiffGaff (=O2). My broadband provider is VirginMedia. The problem is exactly the same with either.
Also the same on another phone I've tried - both phones are Samsungs (Galaxy S10+ and S20+), though hard to believe that could make a difference. 
swisscows.com works fine in Chrome, whether mobile or broadband data.

**Comment by plwt** [comment]
That is different to my ISP.

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1373510

**Comment by kd353** [comment]
I can confirm same. Firefox 100.3.0 (on android). I live in Ireland and this occurs both on my mobile data (gomo) and home WiFi (Vodafone broadband). Phone is a Nokia G20. 
![Screenshot_20220526-195051](https://user-images.githubusercontent.com/85876758/170558211-7e46ebcd-a27b-4c8e-a742-ecf1fcbb653d.png)
