### ISSUE TITLE
FNX3-16333 ⁃ [Bug] Crash when rotating the device portrait > landscape > portrait

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2448]
## Steps to reproduce
1. Open Fenix and tap in the search field.
1. Rotate the device to landscape mode.
1. Rotate the to portrait mode.

### Expected behavior
Fenix rotates to the desired mode, with focus on the search field.

### Actual behavior
Fenix crashes.

### Device information
* Android device:
  * OnePlus 5T (Android 9)
  * Samsung Galaxy Note 8 (Android 8.1)
* Fenix version: 5/13
* [Logcat](https://github.com/mozilla-mobile/fenix/files/3172698/log.txt)

**Comment by sblatz** [comment]
I cannot reproduce this. Can you get this to happen on the latest nightly?

**Comment by bsurd** [comment]
This is not reproducible with the latest build. Closing.
