### ISSUE TITLE
Remove Event.wrapper for History metrics

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24498]
Breakout from #21292.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 101.0a1 (2022-04-13) by accessing history, opening tabs from history, checking closed tabs, term group, deleting history items, deleting all history.
Some events that were generated:
![image](https://user-images.githubusercontent.com/48829350/163188907-990c3297-f833-4fd5-8ac1-c96bb070c4f8.png)
![image](https://user-images.githubusercontent.com/48829350/163188961-dfc3b5a9-5ffe-44f7-b7ec-dd4e259d26b2.png)
Device used: Samsung Galaxy Tab S3 (Android 9).
Closing the ticket as fixed.
