### ISSUE TITLE
[Bug] [NSFW]: Scrolling the page does not hide the toolbar at luna.titdang.me

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#24494]
### Steps to reproduce

1. Navigate to: https://luna.titdang.me/.
2. Follow the screen instructions.
3. Scroll the page.
4. Observe the result.

### Expected behaviour

Scrolling the page hides the toolbar.

### Actual behaviour

The toolbar has a fixed position when scrolling the page.

### Device name

Google Pixel 3

### Android version

(Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 100.0a1 (2015871531 -🦎100.0a1-20220328093900🦎)

### Additional information

1. Reproducible regardless of the status of ETP.
2. Reproducible on the latest build of Firefox Nightly.
3. Works as expected using Chrome.
4. Reproducible regardless of the position of the toolbar.
5. Screenshots are not attached due to the page being `NSFW`.

**Comment by Mugurell** [comment]
Reproducible on GVE also.
Moving to Bugzilla for investigations.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1761937

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
