### ISSUE TITLE
Update disabled ui test settingsPrivacyItemsTest

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24495]
Test was disabled following https://github.com/mozilla-mobile/fenix/issues/16952 which added new setting in the "Privacy and security" section: "HTTPS-Only Mode".

Some changes needed:
- verify the new setting title and summary in the general settings screen
- verify the details shown when opening the new "HTTPS-Only Mode" settings screen
- update test to avoid the current ` androidx.test.espresso.AmbiguousViewMatcherException: 'with text: is "Off"' matches multiple views in the hierarchy. ` exception.

**Comment by Mugurell** [comment]
cc @sv-ohorvath

**Comment by AndiAJ** [comment]
Fixed in #24705 added the verification for "HTTPS-Only Mode" in "Privacy and security" section and fixed the `AmbiguousViewMatcherException`

The details when opening the "HTTPS-Only Mode" will be covered in a different test
