### ISSUE TITLE
[Bug]: Disabled select options can be selected

### ISSUE THREAD

**Issue by nexxome** [mozilla-mobile/fenix#24504]
### Steps to reproduce

1. Go to https://jsfiddle.net/dy05fpxs/1/
2. Select one of the last options in the select

### Expected behaviour

Disabled options should not be able to be selected

### Actual behaviour

Disabled option selected

### Device name

Galaxy S21

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

98.3.0

### Additional information

It seems that even if I can select the disabled option, the change event of the select isn't fired

**Comment by delia-pop** [comment]
Hi @nexxome, 
thank you for your report!

I was able to reproduce this issue as you described it.
Tested and reproduced on the latest Nightly (100.0a1 from 03/30), the latest Beta (99.0.0-beta5), Release (98.3.0 and latest 99.1.0).

The issue does not occur on Chrome or GVE, where the disabled options from the Time dropdown cannot be selected.
Device used:
Samsung Galaxy Note10 (Android 11).

Attaching a screenshot of the issue:
![Screenshot_20220330-123116_Firefox](https://user-images.githubusercontent.com/89388888/160801313-0332362a-96e1-433d-ba42-1bf6907c880a.jpg)

**Comment by SoftVision-LorandJanos** [comment]
I was able to reproduce this issue on an earlier Nightly 101.0a1 (up to 2022-04-28) build.
Verified as fixed on the latest Nightly 101.0a1 (2022-04-29) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
