### ISSUE TITLE
Refactor private browsing tests to work with Compose

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24508]
In https://github.com/mozilla-mobile/fenix/pull/24505, we had to ignore some UI tests due to the Home Screen Compose refactoring of the PrivateBrowsingDescriptionViewHolder. 

The test failure occurs in [`verifyPrivateSessionMessage`](https://searchfox.org/mozilla-mobile/search?q=verifyPrivateSessionMessage&path=) calls since the description message is now in Compose.

We had to disable the following tests:
- privateBrowsingUseAppWhileTabIsCrashedTest
- privateModeScreenItemsTest
- addPrivateBrowsingShortcutTest
- verifyContextMenuShortcuts

**Comment by AndiAJ** [comment]
@sv-ohorvath

**Comment by AndiAJ** [comment]
Fixed and re-enabled in #24595
