### ISSUE TITLE
[Bug]: Unable to show only pinned top sites on home screen

### ISSUE THREAD

**Issue by Smaehtin** [mozilla-mobile/fenix#24506]
### Steps to reproduce

1. Go to Settings -> Homepage
2. Disable everything except Shortcuts
3. Pin sites to your homepage

### Expected behaviour

I only see my pinned sites on my homepage.

### Actual behaviour

I see my pinned sites **and** other, seemingly random sites that I have recently visited.

### Device name

Motorola Moto G100

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

98.3.0

### Additional information

![Screenshot](https://user-images.githubusercontent.com/26857259/160691111-8963e82e-ad15-4986-9a9c-9574485a1b0f.jpg)

**Comment by kbrosnan** [comment]
This was changed to match desktop behavior.

**Comment by cadeyrn** [comment]
@Smaehtin: If you **disable** the shortcuts you still see the pinned sites an no recently visited sites.

**Comment by cadeyrn** [comment]
To be honest, I think the Nightly behaviour is the new _expected behaviour_ because, as @kbrosnan said, they changed it to match the desktop behaviour and on desktop it's indeed the same behaviour as in Firefox Nightly on Android.

**Comment by Smaehtin** [comment]
> To be honest, I think the Nightly behaviour is the new _expected behaviour_ because, as @kbrosnan said, they changed it to match the desktop behaviour and on desktop it's indeed the same behaviour as in Firefox Nightly on Android.

Ah, dang. That sucks. Thanks, though.
