### ISSUE TITLE
PWA: open abitrary url

### ISSUE THREAD

**Issue by opk12** [mozilla-mobile/fenix#24503]
### What is the user problem or growth opportunity you want to see solved?
I have two use cases.

I am logged into a PWA and want to visit an arbitrary URL that the badly designed website does not link to, but I can trivially construct by hand.

I dig through the links to a page that I want to visit later, tap on the PWA notification `Tap to copy the URL for this app`, but later there is nowhere to paste it.
In both cases the webpage requires to be logged in to be visited, so I cannot just paste it into Fennec's address bar in browser mode.

### How do you know that this problem exists today? Why is this important?
The notification does say `Tap to copy the URL for this app` so I assume there should be a place in the PWA where to paste it.

### Who will benefit from it?
PWA users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19991)

**Comment by LaurentiuApahideanSV** [comment]
@opk12 Could you specify the PWA where you encountered this issue?
