### ISSUE TITLE
Remove Fact.toEvent after refactoring FactProcessor

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24514]
Issue based on https://github.com/mozilla-mobile/fenix/pull/24378#discussion_r835567398.

In #21292 we are removing the `Event.wrapper`and record metrics using Glean directly. For the events coming from `FactProcessor`, this means that instead of parsing the `Fact` as an Event in `Fact.toEvent()` and then tracking it, we will process it, similar to what Focus [does](https://github.com/mozilla-mobile/focus-android/blob/51411db7c901b39545b09b2df7c2ea3f3dae0eba/app/src/main/java/org/mozilla/focus/telemetry/FactsProcessor.kt#L38). 

After all the events coming from `FactProcessor` will be processed, we should remove the `else` [case](https://github.com/mozilla-mobile/fenix/blob/7cedc8b440ed5ba5fd61735a6f61cf911070dbd8/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt#L117).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19998)

**Comment by mcarare** [comment]
Looking at the code I think we might not be able to remove the else case because we have a `when(Pair<>)`. We should think of a way to handle the else case.

**Comment by Alexandru2909** [comment]
We can change the scope of this issue to removing the `Fact.toEvent` function from the else case.
