### ISSUE TITLE
Undo snackbar for history groups

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#24513]
Part of this [jira](https://mozilla-hub.atlassian.net/browse/FNXV2-18111?focusedCommentId=466569) ticket.

Implement undo mechanism on history group screen to reduce accidental removals and make it consistent with the History Screen.

**Comment by mavduevskiy** [comment]
Added complexity came from the need to appropriately update the group item count or hide it completely inside the history screen: item deleted inside history group screen -> user backs to history screen -> the group item should consider items pending for removal –> Undo action should updated the group item again.

**Comment by delia-pop** [comment]
Verified as fixed on the 04/28 Nightly build with Google Pixel (Android 12). An Undo snackbar is displayed after deleting items from a history group, bookmarks or downloaded files. 

https://user-images.githubusercontent.com/89388888/165742834-6675a674-b000-4357-93e6-a520912168c2.mp4
