### ISSUE TITLE
Remove Event.wrapper for RecentlyCloseTabs metrics

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24512]
Breakout from #21292.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with OnePlus 9 (Android 12).

Under category "recently_closed_tabs" the following were displayed:
        "enter_multiselect"
        "recently_closed_tabs_opened"
	"opened"
        "menu_share"
	"menu_open_in_normal_tab"
	"menu_open_in_private_tab"
	"menu_delete"
	"exit_multiselect"
	"open_tab"
	"delete_tab"
	"closed"
	"menu_close"
