### ISSUE TITLE
Telemetry for unified search

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24522]
As a product owner I want to understand how our users engage with this design. 

https://mozilla-hub.atlassian.net/browse/FNXV2-19763

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20003)

**Comment by rocketsroger** [comment]
Adding telemetry for when history, bookmarks and tabs search engine is selected.  Also when user taps on the unified search selector menu.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 103.0a1 2022-06-09 by interacting with the Unified search and observing the resuts.

Tapping the unified search:
{
          "timestamp": 4875,
          "category": "unified_search",
          "name": "search_menu_tapped"
        },
Selecting the history option from the unified search:
{
          "timestamp": 88144,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "history"
          }
Selecting the tabs option from the unified search:
{
          "timestamp": 92144,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "tabs"
          }
Selecting the bookmarks option from the unified search:
{
          "timestamp": 94473,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "bookmarks"
          }
Selecting different search engines from the unified search:
{
          "timestamp": 17586,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "Google"
          }

{
          "timestamp": 6180,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "Wikipedia"
          }

{
          "timestamp": 9277,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "eBay"
          }

{
          "timestamp": 11304,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "DuckDuckGo"
          }

        {
          "timestamp": 8195,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "Amazon.com"
          }

{
          "timestamp": 15717,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "Bing"
          }

{
          "timestamp": 7532,
          "category": "unified_search",
          "name": "engine_selected",
          "extra": {
            "engine": "custom"
          }
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-1006)

### Device used:
- OnePlus 6T (Android 9)
