### ISSUE TITLE
Add support for a disabled state to ListItem

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#24525]
Add the ability to enable/disable a list item, where the UI takes on a conventional disabled state and can no longer be interacted with.

https://www.figma.com/file/ujdiReypSypu2GhRgzArea/branch/ddGnMfYggXGmcTYfoI0aS8/Mobile-Android-Components?node-id=1802%3A1042

![image](https://user-images.githubusercontent.com/87384386/160927544-388b5c00-846b-49f1-b382-b7776a18b90a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20004)

**Comment by indurs** [comment]
@MozillaNoah , I'm interested in working on this. Is this issue intended only for Mozilla team?

**Comment by MozillaNoah** [comment]
> @MozillaNoah , I'm interested in working on this. Is this issue intended only for Mozilla team?

HI @indurs, thank you for your interest!! I honestly made this issue too preemptively. `ListItem` is still in active development and hasn't landed yet. We'll probably circle back to this enhancement later this year as more of the Compose work gets crystalized.
