### ISSUE TITLE
Remove the isPrivate conditional in getTheme in favor of inComposePreview

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24528]
I wanted to do `!inComposePreview && LocalContext.current.settings().lastKnownMode.isPrivate` for this conditional but hit a compiler error that looked like https://stackoverflow.com/questions/68375629/andand-condition-should-have-an-if-true-then-false, which is fixed in Compose 1.1.0 so we will revisit this when we get a Compose upgrade from 1.0.5

_Originally posted by @gabrielluong in https://github.com/mozilla-mobile/fenix/pull/24527#discussion_r838957235_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20006)

**Comment by Alexandru2909** [comment]
Hi @gabrielluong ! The compose version we are [using now](https://github.com/mozilla-mobile/fenix/blob/bf522dbd508d9a89476cd8a3293b68cd90340ff3/buildSrc/src/main/java/Dependencies.kt#L23) is `1.1.1`, do you think we could use the change now?

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 104.0a1 (2022-07-06T17:08:39.656289).
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.
