### ISSUE TITLE
Collection is automatically deleted while still containing tabs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24539]
STRs:
- have a collection already created
- from the 3dot menu add new tabs (one or more)
- delete the all the tabs the collection originally had

Expected result:
- collection stays on screen until it or all the tabs it contains are deleted

Actual result:
- collection is removed from the screen although it still showed the newly added tabs

https://user-images.githubusercontent.com/11428869/161080921-e9d00c48-5450-474d-9d23-4f5f422357de.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20018)

**Comment by SoftVision-LorandJanos** [comment]
Alternative steps:
1. Access a webpage.
2. Add the webpage to a collection.
3. From tabs tray add some additional sites.
4. From homescreen expand the collection and delete the bottom one (the one which the collection was created with).
5. Tap "UNDO".

Actual result:
4. The collection is closed with all its elements.
5. Undoing the closing reopens the collection but only with the original (deleted) webpage in the collection.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809826

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
