### ISSUE TITLE
Compose menus have broken Talkback readouts

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24534]
https://user-images.githubusercontent.com/11428869/160995721-1c5685a7-20df-4675-b962-2e60a058c610.mp4

Issues was fixed upstream - https://issuetracker.google.com/issues/190080692
Fixing in our app depends on when we'll update the compose libraries.

**Comment by mcarare** [comment]
Tagging QA to retest this.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 101.0a1 (2022-04-27) build.
Talkback reads "Remove. Double tap to activate".
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
