### ISSUE TITLE
"Appswitch" for switching from bank app to secure verification app fails with Firefox as default App

### ISSUE THREAD

**Issue by Aephir** [mozilla-mobile/fenix#24537]
### Steps to reproduce

1. Have both the [bank](https://play.google.com/store/apps/details?id=dk.bec.android.mb1.b00032.prod&gl=US) app and "[MitID](https://play.google.com/store/apps/details?id=dk.mitid.app.android&gl=US)" (the secure goverment issued two factor app) and Firefox for Android installed.
2. Have the default web browser set to Firefox for Android.
3. Open bank app, try to log in, and you'll be prompted to verify using "MitID"
4. Click "Open  MitID app" (from within the bank app redirect, which uses the default browser), then it tries to switch to that app (using something called "appswitch").

Note: This was tested on both Huawei P30 Pro and Moto G 5G, with Android 10 or 11, respectively.

### Expected behaviour

It should switch to the "MitID" app, so you can varify you identity.

### Actual behaviour

I get the screenshot below, instead of it switching to the verification app (MitID):
![bank_mitid](https://user-images.githubusercontent.com/20152788/161055028-2c826c49-65cc-414e-9dca-b3aed545f2c8.png)

Note: You can circumvent this by not clicking "Open  MitID app" (step 4), but instead manually opening the app. It's only through the "appswitch" in firefox (tech supports solution was: "use Chrome") that it does not open to verify.

### Device name

Moto G 5G

### Android version

Andriod 11

### Firefox release type

Firefox

### Firefox version

98.3.0

### Device logs

No crash log.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20013)

**Comment by kbrosnan** [comment]
@csadilek What info do we need here? Maybe a problem with intents? Maybe the website is not sending the same content to Firefox and Chrome?

**Comment by csadilek** [comment]
@Aephir Can you check if you have Settings -> Open links is apps enabled in your Firefox for Android? If not, can you try again with the setting enabled?

**Comment by csadilek** [comment]
Thanks @Aephir for reporting and confirming this works with app links enabled. 

@kbrosnan We should maybe revisit the default for the app links feature, and talk through trade-offs again. I can see a lot of users falling into this, and automatic detection seems difficult.

**Comment by alpha-gub** [comment]
Samsung M30s. Android 11. Firefox.

I have no functioning workaround (well.. changing default browser every time has worked before, but its too ridiculous to actually call functioning). I lost access to my bank accounts over a month ago when NemID was removed as an authentication option in my bank. Goodbye consumer confidence.

**Comment by tehkillerbee** [comment]
I have the same issue when using my bank app (Nykredit) together with MitID. It looks like the issue is similar, as using chrome as default browser works fine.

As a workaround to changing default browser, it also works if I open the browser window in app by clicking "open in Firefox".

I've been in contact with the app / MitID support, but the conclusion is the bug is caused by Firefox, not the app itself..

![Screenshot_20221113-135028_Firefox Beta](https://user-images.githubusercontent.com/815886/202897808-37d032c6-25b1-4ce5-8af2-7bf4fc43e1b3.jpg)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809270

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
