### ISSUE TITLE
[Bug]: "security.enterprise_roots.enabled" gets reset each restart

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/fenix#24538]
### Steps to reproduce

1. go to `about:config`
2. search for `security.enterprise_roots.enabled`
3. toggle it to `true`
4. enjoy fenix trusting your system imported root certificates 
5. close fenix
6. restart the app
7. go to `about:config`
8. search for `security.enterprise_roots.enabled`

### Expected behaviour

The config property `security.enterprise_roots.enabled` is stored indefinetely even accross app restarts.

### Actual behaviour

The property is reset every time the browsers gets restarted. 

### Device name

Sony Xperia 10

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-03-31.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by kbrosnan** [comment]
This is expected behavior for prefs owned by GV. Users should use the secret settings to enable 3rd party CA certificates.
