### ISSUE TITLE
Adding new tabs to an existing collection from tabs tray allows to delete all tabs in it and it being kept as empty

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24542]
STRs:
- have a collection already created
- open the tabs tray (optionally switch to a tab)
- select new tabs to add to the existing collection
- switch to app's homescreen
- one by one delete all the tabs it contains

Expected result:
- when the last tab it contains is deleted the collection should be deleted and removed from the screen

Actual result:
- the restored collection doesn't contain the tabs added just before the deletion

https://user-images.githubusercontent.com/11428869/161084863-5bf20c02-4dbf-4e97-9d3a-24cfbe48f7ee.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20015)

**Comment by indurs** [comment]
@Mugurell , can I work on this?

**Comment by Mugurell** [comment]
@indurs Thank you for your interest but this functionality is currently being refactored.
Opened the ticket just for tracking the bug. Actually working on it can be a followup to the refactoring.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809823

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
