### ISSUE TITLE
Collection is not deleted after renaming it and then deleting all its tabs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24541]
STRs:
- have a collection already created
- add new tabs
- rename the collection
- one by one delete all the tabs it contains

Expected result:
- when the last tab it contains is deleted the collection should be deleted and removed from the screen

Actual result:
- the restored collection doesn't contain the tabs added just before the deletion

https://user-images.githubusercontent.com/11428869/161084095-f6161763-636c-41e6-8543-566d5729d583.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20016)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809824

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
