### ISSUE TITLE
Restored collection has fewer tabs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24540]
STRs:
- have a collection already created
- from the 3dot menu add new tabs (one or more)
- delete the collection
- immediately after deletion press the undo button for it to be restored

Expected result:
- the deleted collection is restored with the same name and containing tabs

Actual result:
- the restored collection doesn't contain the tabs added just before the deletion

&nbsp;
* Might be the same underlying issue as on https://github.com/mozilla-mobile/fenix/issues/24539

https://user-images.githubusercontent.com/11428869/161082905-86fb7c87-6fdf-40e4-a2bb-4fcb0b38b001.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20017)

**Comment by indurs** [comment]
@Mugurell , I can reproduce this issue. Can I work on this issue?

**Comment by Mugurell** [comment]
@indurs Thank you for your interest but this functionality is currently being refactored.
Opened the ticket just for tracking the bug. Actually working on it can be a followup to the refactoring.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809825

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
