### ISSUE TITLE
[Bug] Private mode does not switch anymore

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#2454]
## Steps to reproduce
1. Open a private tab in Fenix, viewing e.g. example.org
1. Tap the tab-switcher icon at bottom right
1. Tap the "x" to close your open tab, so that you're just viewing the home-screen.
--> Notice the "You're in a private session" paragraph
1. Tap the Private-Browsing-Mask icon at top right of home screen

### Expected behavior
As I leave Private Browsing, the "You're in a private session" message should disappear (and probably be replaced by my non-private-browsing tab-stacks)

### Actual behavior
The "You're in a private session" message remains, even though I've now left my private session.

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1919

I'm guessing @sblatz might know what to do with this, since he worked on other stuff related to PB homescreen UI e.g. #347.

**Comment by dholbert** [comment]
Screencast of bug: https://www.dropbox.com/s/gjf8rlgifda2qor/pb-bug.mp4?dl=0

**Comment by dholbert** [comment]
In general, it looks like the homescreen doesn't change when I switch into/out-of PB mode.  (i.e. this bug exists in the opposite direction as well -- for example, when I tap the mask to switch from normal into PB mode, my normal-mode tab-stacks are still visible on the homescreen.)

So that might be the general root issue.  But it's particularly problematic for this switching-from-Private-to-normal user flow, because it results in us making a privacy-related declaration that is not actually true ("You're in a private session" etc)

**Comment by sblatz** [comment]
Thanks for reporting, @dholbert. Looks like an issue that was introduced with https://github.com/mozilla-mobile/fenix/commit/ccbc14a71fd83ca4b2d8dc9bc60fd8d0e75df6cc.

**Comment by LittleAngelwings** [comment]
Maybe similar with this issue: https://github.com/mozilla-mobile/fenix/issues/2411

**Comment by dholbert** [comment]
Yeah -- that issue is about stale content on the homescreen when swapping from normal to PB mode, vs. this issue is about stale content on homescreen when swapping from PB to normal mode.

Likely the same underlying problem.

**Comment by sblatz** [comment]
This is almost certainly due to our [ViewModel changes](https://github.com/mozilla-mobile/fenix/pull/2457).

@boek is investigating.
