### ISSUE TITLE
History and Bookmark search should not have downward arrows in the result

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#24550]
Currently both history and bookmark search results in entries that have a arrow on the right side.  It should not be there.  Please remove.

![Screenshot_20220331_172252](https://user-images.githubusercontent.com/6579541/161151654-f3710630-da0e-4b36-b39d-77b2350d39fd.png)
.

**Comment by rocketsroger** [comment]
This issue requires an A-C side fix.  Issue created https://github.com/mozilla-mobile/android-components/issues/11948

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 101.0a1 (2022-04-07).
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.
