### ISSUE TITLE
[Bug]: The Sponsored shortcuts cannot be enabled or disabled

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-mobile/fenix#24556]
### Steps to reproduce

1. Open the latest Nightly build.
2. Navigate to Settings -> Homepage.
3. Tap the "Sponsored shortcuts" option.
4. Click the "Back" button.
5. Navigate back to Settings -> Homepage.
6. Observe the "Sponsored shortcuts" option.

### Expected behaviour

- The "Sponsored shortcuts" option is enabled.

### Actual behaviour

- The "Sponsored shortcuts" option remains disabled.

### Device name

One Plus 8 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

### Additional information

- If you are enrolled in the Nimbus experiment in the treatment branch and you have Sponsored shortcuts enabled by default, you cannot disable "Sponsored shortcuts" option.
- Attached is a screen recording of the issue when you are NOT enrolled in the experiment:
https://user-images.githubusercontent.com/19226534/161267494-18a3208f-f73d-4ff2-9007-2509813099ac.mp4

- Attached is a screen recording of the issue when you are enrolled in the experiment:
https://user-images.githubusercontent.com/19226534/161267628-e2b82af7-9ecb-4a00-a6c8-391fbf1a1d7d.mp4

**Comment by SoftVision-LorandJanos** [comment]
This issue was reproducible on the Nightly 100.0a1 from 2022-04-01.
Verified as fixed on the latest Nightly 100.0a1 (2022-04-04).
Device used: Oppo Reno 6 (Android 12).
Closing the ticket as fixed.
