### ISSUE TITLE
[Bug]: Can't run YouTube 60fps video(Laggy-less fps)

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#24552]
### Steps to reproduce

1.Go to youtube.com 
2.Run a 60fps video at 720p/1080p

### Expected behaviour

It should run 60fps video.My chromium based kiwi browser can run at 60fps.

### Actual behaviour

It can't run 60fps

### Device name

Realme C15 qcom(RMX2195)

### Android version

Android  11

### Firefox release type

Firefox

### Firefox version

98.3.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20028)

**Comment by kbrosnan** [comment]
We would need to have a performance profile to forward this to the Gecko team. https://profiler.firefox.com/docs/#/./guide-remote-profiling
