### ISSUE TITLE
[Bug]: Rapidly closing adjacent tabs also switches to an adjacent non-closed tab for no reason

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#24562]
### Steps to reproduce

1. Have several tabs open.
2. Open the tab tray. Have it in list view, not grid view.
3. Scroll up.
4. Decide on any two tabs to close.
5. Close them by tapping the X buttons, closing the lower tab first. Do this rapidly -- two quick taps.

### Expected behaviour

Both tabs close, and nothing else happens.

### Actual behaviour

Both tabs close, and Firefox switches to the tab directly above them. The tab tray remains open, but the switched-to tab is now the active tab; if it was inactive, restored from a previous session, then it will now load.

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

98.3.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20035)

**Comment by DavidJCobb** [comment]
Apparently the switched-to tab can be just about any on-screen tabs, not only ones adjacent to or above the closed pair.

Tests show that it can happen with taps about 0.2s apart or faster, but it should be more consistent with faster taps.

The fact that the tab tray isn't closed suggests that this shouldn't just be the taps to close tabs mistakenly registering as also being a tap on the switched-to tab, but y'all'll have to be the ones to confirm that.

**Comment by echuber2** [comment]
This happens to me too sometimes even if I only scroll up and close a single tab.

**Comment by delia-pop** [comment]
Hi @DavidJCobb, 
Thank you for your report!
I was not able to reproduce the issue you described on Firefox 98.3.0, latest release 100.1.2 or the latest Nightly from 05/11.
Could you please re-test the issue using the latest RC and Nightly builds? Also please let us know what device are you using. 
Device used: Xiaomi Redmi Note 8T (Android 9); Motorola Moto G30 (Android 11).
