### ISSUE TITLE
Reduce clutter in 3-dot-menu ( hide some options in a "More >" button?)

### ISSUE THREAD

**Issue by opusforlife2** [mozilla-mobile/fenix#24561]
### What is the user problem or growth opportunity you want to see solved?

The 3-dot-menu has quite a few options, such that the user needs to actively search for the button they want, and it often needs to be scrolled.
It also contains buttons that probably don't see frequent use, or have one-time utility (such as "Sign in to synchronise").

I think some of these buttons can be removed completely, removed after a while, or placed inside a "More >" menu button, just like "Add-ons >" in the current release.

Some buttons I _personally_ use rarely, or don't use at all, as an example of potential clutter for a user:
- **New tab**: opening a new tab through the tab counter is much, much faster: you basically just double tap slowly, instead of taking your finger all the way to the top of the 3-dot-menu.
- **Sign in to synchronise**: good for one-time discovery, but useless for those who know they don't want to sign in. Also, available in Settings.
- **Open in app**: good for one-time discovery, but available in long-press menu for links. Also, permanent toggle exists in Settings.
- **Add to Home screen**: I'm pretty sure only a few websites are worth keeping a shortcut/PWA for, regardless of the user. This should definitely go under "More")
- **Add to top sites**: same as above. Only a few websites are worthy of the top site status. Otherwise it just becomes a substitute for a bookmarks list.
- **Save to collection**: it is a variation of the Bookmarks feature. Bookmarks have folders for organisation.
- **What's New**: it should be manually dismissable, or should vanish automatically after some days. Also, available in Settings > About.
- **Help**: available in Settings > About. 
- **Customise homepage**: just a shortcut to Settings > Homepage. Browser customisation is usually always done through Settings. Why was this added at all? Short-term promotion of a new feature?

### How do you know that this problem exists today? Why is this important?

It will reduce inconvenience and time wasted when using the 3-dot-menu.

### Who will benefit from it?

Users with smaller screens, smaller hands, and those users who use few of the several options listed currently.

**Comment by kbrosnan** [comment]
Thanks for the feedback. We want to have a unified place to access features so it is expected that features can be accessed multiple ways.

**Comment by opusforlife2** [comment]
That's fine. How does a "More" sub-menu prevent that? It will let users access the options from the 3-dot-menu, yet reduce the number of options for those who don't need them. Desktop Firefox also places less frequently used options under sub-menus.
