### ISSUE TITLE
[privacy] disable amp links

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#24566]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
On clicking on Google search result it is opening amp link of the website which is a privacy concern..since firefox is built on privacy theme, it should add the option to disable amp links of the website 
Some browsers already has the option to disable amp links

### How do you know that this problem exists today? Why is this important?
Disabling amp links is important to maintain privacy and keep user data less known to Google.

### Who will benefit from it?
All users

![Screenshot_20220403-121431206 (1)](https://user-images.githubusercontent.com/58127841/161415352-25bee2d9-2359-4d1b-a464-0b58b39387b7.jpg)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/13058

**Comment by sheikh-azharuddin** [comment]
> Duplicate #13058

That issue is closed ..
Besides it says to allow a third party add on ..why are you supporting a third party add on .Its not a recommended one too!

This feature should be inbuilt for better privacy!
