### ISSUE TITLE
[Bug]add to home screen doesn't work 

### ISSUE THREAD

**Issue by paymanz** [mozilla-mobile/fenix#24568]
On MIUI global 12.5.6 add to home screen doesn't works.it doesn't add shortcut of website to home screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20039)

**Comment by amedyne** [comment]
@paymanz What version of the app did you encounter this?

**Comment by paymanz** [comment]
> @paymanz What version of the app did you encounter this?

Right now i have this problem with the latest version of 99.2 but i had this issue even before this version.
