### ISSUE TITLE
[Bug][Telemetry]: No ping is registered when deleting a collection

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#24576]
### Steps to reproduce

1. Create several collections;
2. Delete the collections;
3. Check the https://debug-ping-preview.firebaseapp.com/ for the triggered pings or the Android Studio logcat;

### Expected behaviour

A ping should register when deleting a collection.

### Actual behaviour

No ping is registered when deleting a collection.

### Device name

OnePlus 6T

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1 2022-04-04

### Additional information

[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-04042022)

**Comment by mcarare** [comment]
This seems to have been lost in [this](https://github.com/mozilla-mobile/fenix/pull/20538/commits/500ed703ccd3493924fff2d3fe5b424887bca8d0) commit.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed with the latest Nightly 101.0a1 (2022-05-01T17:11:31.722002) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
