### ISSUE TITLE
[Bug] Fenix does not appear to be submitting GV crash reports

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#2458]
Fenix's current GV version is 20190508111321, but Socorro has no Fenix+GV crash reports since GV version 20190422094240:

https://crash-stats.mozilla.com/search/?product=Fenix&date=%3E%3D2018-11-13T20%3A13%3A00.000Z&date=%3C2019-05-13T20%3A13%3A00.000Z&_facets=signature&_facets=build_id&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-build_id

Focus+GV has submitted crash reports for a more recent GV version (20190429095544), suggesting this is a problem in Fenix or A-C, not GV.

https://crash-stats.mozilla.com/search/?product=Focus&version=68.0a1&date=%3E%3D2018-11-13T20%3A13%3A00.000Z&date=%3C2019-05-13T20%3A13%3A00.000Z&_facets=signature&_facets=build_id&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-build_id

Fenix is successfully submitting unhandled Java exceptions to Sentry, so this problem only affects GV crashes:

https://sentry.prod.mozaws.net/operations/fenix/releases/

**Comment by pocmo** [comment]
Reference Browser crashes are still coming in:
https://crash-stats.mozilla.com/topcrashers/?product=ReferenceBrowser&version=68.0a1

This seems to be related to #1577 where Fenix is not showing the "tab has crashed" UI (and therefore probably never asks to send reports).

**Comment by cpeterso** [comment]
> Reference Browser crashes are still coming in:

Interesting. So that confirms this is not a GV bug. I see Reference Browser crashes as recently as GV version 20190508111321:

https://crash-stats.mozilla.com/search/?product=ReferenceBrowser&date=%3E%3D2019-04-29T22%3A36%3A00.000Z&date=%3C2019-05-13T22%3A36%3A00.000Z&_facets=signature&_facets=build_id&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-build_id

**Comment by pocmo** [comment]
Okay, one obvious error here is that we replaced "Fenix" with the app name here. Which means we are uploading crashes to a "Firefox Preview" bucket that doesn't exist. I'll patch that.

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/Analytics.kt#L66

**Comment by dbolter** [comment]
Can we catch/flag crash reports with unexpected app names on the ingestion side (socorro)?
@cpeterso (let's figure this out)

**Comment by willkg** [comment]
Socorro gets so many crash reports from unsupported products, there really isn't a way to get notified that something that should be getting into Socorro is getting denied from the Socorro side.

Maybe you could create a script or a report that keeps an eye on incoming crash report numbers and notifies you when the number is lower than "normal"?

**Comment by willkg** [comment]
Socorro is allowing/rejecting incoming crash reports based on the `ProductName` value in the crash report. I don't know where that comes from in Fenix.

There's some mediocre documentation on product support here:

https://crash-stats.mozilla.com/documentation/products/

If that doesn't help or doesn't meet Fenix's needs, we should talk.

**Comment by ekager** [comment]
FYI just merged @pocmo 's PR #2515 if someone wants to check out these reports after the next nightly build is pushed out

**Comment by cpeterso** [comment]
> FYI just merged @pocmo 's PR #2515 if someone wants to check out these reports after the next nightly build is pushed out

Thanks! I'll watch for incoming crash reports and then close this issue.

I see that PR #2515 reverts Fenix's Socorro product name from "Firefox Preview" back to "Fenix". That makes sense because "Firefox Preview" is not the final product name and we'll want Fenix's future Nightly/Beta/Release channels to all report into the same Socorro product name.

**Comment by cpeterso** [comment]
I now see Fenix crash reports with GV version 20190508111321, so the Fenix product name fix appears to be working! 🎉
