### ISSUE TITLE
firefox for termux

### ISSUE THREAD

**Issue by ghalibansari** [mozilla-mobile/fenix#24584]
can u guys plz port firefox to termux x11, it can help a lot of students who don't have money to buy a new pc, yet they can use their device for development and research. I use termux nodejs-lts for collage project and learning via vnc but there is no good browser for termux I used otter-browser but the video play is not working and other issues as well.
as we know single computing device will be the future, other many package are natively avaliable in termux(node, golang, code-server n etc...)

**Comment by kbrosnan** [comment]
This is not related to Firefox for Android. You can make requests at https://connect.mozilla.org/
