### ISSUE TITLE
[Bug] Browser html demos are partially visible

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#2459]
## Steps to reproduce
visit either http://browserhtml.github.io/browserhtml/components/about/newtab/demos/spheres.html or http://browserhtml.github.io/browserhtml/components/about/newtab/demos/transparent_rects.html

### Expected behavior
the pages should take the whole screen like chrommium
![Screenshot](https://user-images.githubusercontent.com/922368/57655728-317dde00-75df-11e9-8252-72ec10950c72.png)UNITO-UNDERSCORE!20190514-002727!UNITO-UNDERSCORE!Chromium!
![Screenshot](https://user-images.githubusercontent.com/922368/57655736-36db2880-75df-11e9-84dc-f9d6abef4948.png)UNITO-UNDERSCORE!20190514-002648!UNITO-UNDERSCORE!Chromium!

### Actual behavior
demos rendered in corner
![Screenshot](https://user-images.githubusercontent.com/922368/57655761-4a868f00-75df-11e9-9b50-61239e894ffa.png)UNITO-UNDERSCORE!20190514-002252!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!
![Screenshot](https://user-images.githubusercontent.com/922368/57655765-4f4b4300-75df-11e9-9d96-4c6ec28dfa79.png)UNITO-UNDERSCORE!20190514-002304!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Preview!

### Device information
* Android device: 
![Screenshot](https://user-images.githubusercontent.com/922368/57655775-58d4ab00-75df-11e9-94c8-e6ea0b1d2cb7.png)UNITO-UNDERSCORE!20190428-135941!UNITO-UNDERSCORE!Settings!
* Fenix version: latest

**Comment by cpeterso** [comment]
What GV work is needed here? Do we still need the `needs:gv` label? Is the web content trying and failing to go full screen?

**Comment by boek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639086

**Comment by hiikezoe** [comment]
Though I've already commented in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1639086#c5). This is an issue in the site.

**Comment by kbrosnan** [comment]
Closing as invalid.
