### ISSUE TITLE
Remove Event.wrapper for ReaderMode metrics.

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24591]
Breakout from #21292

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-4-12 by entering reader mode and observing the events generated.
Reader mode available
{
          "timestamp": 16101,
          "category": "reader_mode",
          "name": "available"
        },
Reader mode is enabled
        {
          "timestamp": 17278,
          "category": "reader_mode",
          "name": "opened"
        },
Reader mode is closed
{
          "timestamp": 17418,
          "category": "reader_mode",
          "name": "closed"
        },
Tapping on the Reader mode Appearance menu
{
          "timestamp": 20639,
          "category": "events",
          "name": "browser_menu_action",
          "extra": {
            "item": "reader_mode_appearance"
          }
        },
        {
          "timestamp": 20653,
          "category": "reader_mode",
          "name": "appearance"
        }
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-1204)
### Device used:
- OnePlus 6T (Android 9)
