### ISSUE TITLE
[Bug]: Pocket stories disappear unexpectedly when tapping on story topics after fresh install/clear data, until restarting the app

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#24596]
### Steps to reproduce

1. Perform a fresh install/Clear data of the app.
2. Have the region set to US and the pocket section enabled from Settings.
3. From the "Stories by topic" section on homepage, select one or more topics.
4. Observe if the Pocket stories section remains displayed.

### Expected behaviour

The Pocket stories section should remain displayed when quickly selecting the stories topics.

### Actual behaviour

The Pocket stories section should disappears unexpectedly when quickly selecting the stories topics. 
Please note that the issue will no longer occur after restarting Fenix.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1 from 04/05

### Additional information

The issue also occurs on Beta 100.0.0-beta.1. 
Notes: 
- sometimes the issue occurs after the first tap on a topic, or after multiple/alternated taps of topics;
- the issue occurs with and without browsing history;
- sometimes, when browsing history is available, instead of disappearing, the Pocket section falls out of focus, and the focus is moved on the Jump in/Recently visited section of the homepage; 
- the Pocket section is restored after sending the app in background or accessing Settings/a webpage;
- after restarting the app, the issue is no longer encountered.

[Moto_ReproAfterClearData.txt](https://github.com/mozilla-mobile/fenix/files/8443302/Moto_ReproAfterClearData.txt)

Reproduced as described with the Debug build provided by Petru:

[Moto_DebugBuildPocket.txt](https://github.com/mozilla-mobile/fenix/files/8443311/Moto_DebugBuildPocket.txt)

https://user-images.githubusercontent.com/89388888/161742082-dd2fb237-3c07-4fe4-89f4-8e8b4b9d646f.mp4

https://user-images.githubusercontent.com/89388888/161743539-5831b20e-aa3d-4a0b-8620-e833d46385e1.mp4

https://user-images.githubusercontent.com/89388888/161743522-6ee64f6b-9bd9-4ab2-acd4-5ca01cb221e2.mp4

**Comment by SoftVision-LorandJanos** [comment]
I managed to reproduce this issue on an earlier build (100.0.0-beta2), using a Google Pixel 4 with Android 12.
Verified as fixed on the latest Nightly 101.0a1 (2022-04-13) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
