### ISSUE TITLE
Remove Event.wrapper for MediaNotification telemetry

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24603]
Breakout from #21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-4-12 by interacting with videos and observing the events.
When a video or audio starts and is paused
{
          "timestamp": 15714,
          "category": "media_state",
          "name": "play"
        },

{
          "timestamp": 22335,
          "category": "media_state",
          "name": "pause"
        },

When a video is put in fullscreen mode
{
          "timestamp": 26244,
          "category": "media_state",
          "name": "fullscreen"
        },
When a video is put in picture in picture mode
{
          "timestamp": 28956,
          "category": "media_state",
          "name": "picture_in_picture"
        },
When audio is started and paused from the push notification
{
          "timestamp": 14138,
          "category": "media_notification",
          "name": "pause"
        },

{
          "timestamp": 15384,
          "category": "media_notification",
          "name": "play"
        },

When audio is started and paused from the tabs tray
{
          "timestamp": 7515,
          "category": "tab",
          "name": "media_play"
        },

{
          "timestamp": 8910,
          "category": "tab",
          "name": "media_pause"
        },
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-1204)
### Device used:
- OnePlus 6T (Android 9)
