### ISSUE TITLE
[Bug]: "Clear cookies and site data" not working when a permission/ site is added to the exception list 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#24606]
### Steps to reproduce

1. Go to https://permission.site/.
2. Tap on "Camera"-> allow and remember the setting for permission.
3. Tap on lock icon -> Clear cookies and site data.
4. Tap on "Delete".
5. Reload the page.
6. Tap on "Camera" again. 

### Expected behaviour

The pop-up is displayed again, asking to allow or to deny the permission. 

### Actual behaviour

The pop-up is not displayed.
Not reproducible when the remember decision is not checked. 

### Device name

Sony Xperia, Pixel 6

### Android version

6.0.1, 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0.0-beta.1, Nightly 101.0a1, 99.1.0

**Comment by Amejia481** [comment]
The desktop team confirmed, that this is the expected behavior as it's in alignment with Desktop. I'll close this ticket, please feel free to reopen if it's needed.
