### ISSUE TITLE
The last private tab will disappear when resuming a download

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#24610]
### Steps to reproduce

1. Enter private browsing;
2. Go to a site from where you can download a large file like https://www.thinkbroadband.com/download;
3. Begin downloading a large file;
4. Close the tab by swiping it;
5. When prompted by the "Cancel private download? popup select "stay in private browsing".

### Expected behaviour

The tab opened in private browsing should remain open.

### Actual behaviour

The tab appears to close and the private browsing tabs tray seems empty until the normal tabs tray is tapped.

### Device name

OnePlus 6T

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

100.0.0-Beta.1

### Additional information

https://user-images.githubusercontent.com/50983519/161784270-40dd6efb-9083-415e-9cdc-f77a34453454.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20064)

**Comment by amocirean** [comment]
Reopened as the issue is still reproducible on Firefox Beta 109.0b1.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807536

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
