### ISSUE TITLE
Remove history improvement feature flag

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#24613]
Once history improvement is stable in release.  Remove history improvement feature flag in Nightly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20066)

**Comment by SoftVision-LorandJanos** [comment]
Hi @rocketsroger!
What scenarios need to be tested here?
Thank you!

**Comment by rocketsroger** [comment]
> Hi @rocketsroger! What scenarios need to be tested here? Thank you!

Hi @SoftVision-LorandJanos, just some history sanity tests to make sure I didn't break anything when removing the flag.  Thanks.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 108.0a1 (2022-11-09).
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Beta 108.0b1.
Device used: Oppo Find X5 (Android 12).
