### ISSUE TITLE
Handle web notification clicks

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24618]
https://github.com/mozilla-mobile/android-components/issues/7477 adds support for persisting web notifications and executing a `click` action on them when the user clicks on the native notification.

Fenix needs to catch user's click on the native notification and send that to Android-Components for further processing.

This can be tested on :
- https://cleverpush.com/en/test-notifications/ or
- by following the steps from https://github.com/mozilla-mobile/android-components/issues/7477#issuecomment-808938240 or
- by following the steps from https://github.com/mozilla-mobile/android-components/issues/7477#issuecomment-1035711682

There is still an issue with clicks not opening a new tab if the app was exited - https://bugzilla.mozilla.org/show_bug.cgi?id=1763784 but this should work if the app was just put into background.

**Comment by sheikh-azharuddin** [comment]
Finally this is fixed..
Works fine from my side 🙏🙂

**Comment by sheikh-azharuddin** [comment]
Not sure if this is the right thread to post...the push notification click not working when browser is running in foreground..on clicking the notification it simply opens the homepage of the browser


https://user-images.githubusercontent.com/58127841/162623071-93bf1329-685c-4b6c-b348-d9aea1ff0ae1.mp4

**Comment by Mugurell** [comment]
> Not sure if this is the right thread to post...the push notification click not working when browser is not running in foreground (not in recent page)..on clicking the notification it simply opens the homepage of the browser

This seems like the situation described in the top comment about the functionality only working if the app is in foreground (or if the app was put in background using the home button but not if exited by pressing the back button).
This issues needs more investigations. To be done in https://bugzilla.mozilla.org/show_bug.cgi?id=1762032.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-18 by generating push notification from https://cleverpush.com/en/test-notifications/ and https://tests.peter.sh/notification-generator/. After tapping on the push notification the correct webpage is opened if Fenix is in the background.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
