### ISSUE TITLE
website appearance

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#24615]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
I see this feature was added to firefox desktop version wherein user can choose the websiite color scheme
Can this feature be added to firefox android too

### How do you know that this problem exists today? Why is this important?
Currently some website follows device theme( dark/light) but users might want to have different color scheme for the sites
### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20067)

**Comment by Disil** [comment]
As far as I know there is no such thing as 'custom website color scheme' in desktop and mobile. We have dark/light mode that website can 'follow if they have the scheme'. Did you mean a 'custom' toolbar color?

**Comment by Disil** [comment]
If you mean 'Website Appearance' settings, this can be achieved by changing Theme in settings you can achieve this too:
![Screenshot_20220411-040958_Firefox Beta](https://user-images.githubusercontent.com/26422376/162640053-b4968587-273c-4728-b969-9c98ca84103f.jpg)
Although not all websites will follow it.

If you mean the 'colors option' (in ur screenshoot) then I dont think we have it yet.

**Comment by sheikh-azharuddin** [comment]
This is website appearance which is different from browser theme...for example if I set browser theme to dark, some website like Google and Microsoft automatically follows browser theme and change the webpages to dark which is not expected by some users..
For this reason the website appearance feature is added in desktop variant to tell the websites to follow or not follow browser theme (light/dark)

I remember there was a preference setting in about:config to handle this....now it seems Mozilla added the setting in the front end

**Comment by sheikh-azharuddin** [comment]
I found the preference 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/overrideContentColorScheme

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/20635
