### ISSUE TITLE
[Bug]: Some pages show address-bar sized space when scrolling

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#24625]
### Steps to reproduce

1. Go to https://gankra.github.io/blah/tower-of-weakenings/ (but I've seen it in other pages recently)
2. Scroll down.
3. For a bit, after the address bar disappears, you see a black space.

This doesn't happen in other pages like GitHub, and I have only noticed recently.

### Expected behaviour

The address bar shows and hides smoothly.

### Actual behaviour

It doesn't 

### Device name

OnePlus 9 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1 (Build #2015872779), 70d7e8fc2+ AC: 100.0.20220404143034, bb1ef6830e GV: 100.0a1-20220404093932 AS: 91.1.1

### Additional information

![Screenshot_2022-04-06-00-03-39-06_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/1323194/161857377-3808078b-d18e-4020-92fb-33b1d95515a5.jpg)

**Comment by agi** [comment]
I can reproduce in GVE with the following step:

- Settings -> Preferred Color Scheme: Dark
- Open new tab (this is important, I don't know why the setting doesn't apply fully to the current tab)
- Paste https://gankra.github.io/blah/tower-of-weakenings/ and scroll down

I can repro from the earliest GVE available in mozregression (2021-04-14) so this doesn't appear to be a recent regression.

**Comment by emilio** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1764606

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
