### ISSUE TITLE
Password suggestions while creating accounts on Android. A password generator feature on firefox.

### ISSUE THREAD

**Issue by mahidhar96** [mozilla-mobile/fenix#24626]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Firefox android doesn't suggest passwords while creating new accounts on android apps. Sometimes it doesn't suggest passwords when logging into the app.
### How do you know that this problem exists today? Why is this important?
I have tried creating new accounts on multiple android apps, it never suggests passwords while creating the apps.
### Who will benefit from it?
Every android user when creating a new account.

In general, having a strong password generator on Firefox Fenix would help, we can simply generate and copy the password from the feature, a fully working feature that suggests and auto-filled can be developed later.

**Comment by delia-pop** [comment]
Hello @mahidhar96 ,

Thank you for your report! Please also note that a feature request for the behavior your ticket describes was already opened under ticket https://github.com/mozilla-mobile/fenix/issues/23421, on point 3. Here you can follow up on the discussions over this topic. I will close this ticket for now.
