### ISSUE TITLE
[Bug]: Can't manage optional/additional permissions in Add-ons Manager

### ISSUE THREAD

**Issue by Janghou** [mozilla-mobile/fenix#24637]
### Steps to reproduce

- Install add-on with optional permissions
- open Add-on Manager
- Select Add-on
- Open Permissions

### Expected behaviour

A GUI with checkboxes/toggle-switches for the `https://support.mozilla.org/en-US/kb/manage-optional-permissions-extensions` 
See:
https://support.mozilla.org/en-US/kb/manage-optional-permissions-extensions

### Actual behaviour

Empty page. just a `Learn more about permissions` link, no permissions showing.
Means optional_permissions are not working on Android, despite the full support check  here:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions#browser_compatibility

### Device name

Samsung S20

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

98.2.0

### Additional information

Tested with 
https://addons.mozilla.org/en-US/firefox/addon/file-this-for-me/

Forum:
https://discourse.mozilla.org/t/no-gui-for-setting-additional-optional-permissions-in-firefox-android/95580

**Comment by Janghou** [comment]
Related bug:
https://github.com/mozilla-mobile/fenix/issues/16912

**Comment by kbrosnan** [comment]
This may just work when the Gecko bug is fixed. Going to close this for now in favor of the Bugzilla bug.
