### ISSUE TITLE
[Bug]: With some input method, when inputting at the first to an input field, unexpected text is committed

### ISSUE THREAD

**Issue by lilydjwg** [mozilla-mobile/fenix#24636]
### Steps to reproduce

1. use the [trime input method](https://f-droid.org/packages/com.osfans.trime/)
2. find an empty <input> and focus it
3. try to type `你好` into it with key strokes `nihao<space>`

### Expected behaviour

`你好` is in the input field

### Actual behaviour

`你好你好` is in the input field.

It not always duplicates. Sometimes a candidate during composing is erroneously committed. This only happens when there is no text and it's the first time to input into an input field.

### Device name

Sony Xperia XZ2 Compact

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

### Additional information

https://user-images.githubusercontent.com/440661/161956266-07180fe4-4db3-4844-aefc-9b3e93f822e1.mp4

**Comment by Mugurell** [comment]
Thank you for the report!
Moving the issue to Bugzilla for more investigations regarding page interactions.
Please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1763381

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by walk143** [comment]
@lilydjwg 修改同文设置>偏好设置>嵌入式编辑模式：选择“无”

**Comment by lilydjwg** [comment]
@walk143 嗯，这样可以绕过。不过我挺喜欢嵌入式编辑的，还是希望火狐能够修复问题。

**Comment by walk143** [comment]
> @walk143 嗯，这样可以绕过。不过我挺喜欢嵌入式编辑的，还是希望火狐能够修复问题。

目前原因未知，也不仅是firefox的原因，最好还是关闭嵌入模式。相关issue https://github.com/osfans/trime/issues/456 https://github.com/osfans/trime/issues/710

**Comment by lilydjwg** [comment]
Yes, I can still reproduce this issue.

**Comment by rvandermeulen** [comment]
@lilydjwg A hopeful fix for this issue is now in Nightly builds. Can you please update to the latest version and re-test? Thanks!

**Comment by rvandermeulen** [comment]
Thanks for confirming! We'll probably backport the fix to Beta as well so it ships in the Firefox 101 release in a couple weeks.
