### ISSUE TITLE
Remove Event.wrapper for Logins telemetry

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24638]
Breakout from #21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-13 by changing the setting to save logins and observing the events that are sent

Save logins and passwords setting is set to "Ask to save"
{
          "timestamp": 51110,
          "category": "logins",
          "name": "save_logins_setting_changed",
          "extra": {
            "setting": "NEVER_SAVE"
          }
        },

Save logins and passwords setting is set to "Never save"
        {
          "timestamp": 52308,
          "category": "logins",
          "name": "save_logins_setting_changed",
          "extra": {
            "setting": "ASK_TO_SAVE"
          }
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-1304)
### Device used:
- OnePlus 6T (Android 9)
