### ISSUE TITLE
[Bug]: WebGL Canvas rendering issue

### ISSUE THREAD

**Issue by fabry24** [mozilla-mobile/fenix#24635]
### Steps to reproduce

1. Open page where is WebGL used developer.mozilla.org
    - https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL
2. Scroll through page and a white rectangle will appear on the webGL canvas for a while

### Expected behaviour

Expected behaviour is correct displayed WebGL canvas

### Actual behaviour

A white rectangle will appear over WebGL canvas.
It is not based on android or firefox version. I have been  tested more android versions (10, 11) on different devices.
![bug1](https://user-images.githubusercontent.com/78112061/161943382-dcd924f3-86d4-414d-b581-61b47ff7729d.png)

### Device name

Samsung Galaxy Tab A

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

98.3.0

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1763503

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
