### ISSUE TITLE
[Bug]: Deleted tabs from a collection are still displayed when share dialog is open

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#24634]
### Steps to reproduce

1. Add a collection with 5 tabs.
2. Delete 2.
3. Tap on Share button.
4. Check the tabs displayed. 

### Expected behaviour

Only 3 tabs are displayed.

### Actual behaviour

All 5 tabs are displayed.

### Device name

Sony Xperia,  Xiaomi Mi11 Lite

### Android version

6.0.1, 11

### Firefox release type

Firefox Beta

### Firefox version

100.0.0-beta.1, Nightly 101.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20077)

**Comment by echuber2** [comment]
I can reproduce this. It seems like if you remove the tab from the collection, "Jump back in" to the current tab, then go back to the share collection popup, it will register the change finally.

There is another problem I've noticed where tabs themselves (not just collection entries) reappear if the app goes to sleep, but I'm not sure if there's already an issue for that.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Beta 105.0b2,  and the latest Nightly 106.0a1 (2022-08-26).
Tested with an Oppo Find X5 (Android 12).
Closing the ticket as verified.
