### ISSUE TITLE
Remove Glide

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/fenix#2464]
Undo #622, essentially. We do not use Glide. Although ProGuard will remove most of the unused code, there is a rule in Glide's ProGuard configuration that forces its users to keep a few constants. Mostly annoying, but may as well remove it anyway. Patch coming.

**Comment by vesta0** [comment]
@sblatz @colintheshots see ^^

**Comment by sblatz** [comment]
Agreed, we should remove this. Adding it to our dev stories.

**Comment by hawkinsw** [comment]
Sorry the patch hasn't been forthcoming. I got sidetracked today.

**Comment by ekager** [comment]
@hawkinsw it looked like this wasn't ever merged in? The PR was closed? Do we still want to do this or do we want to close this issue?
