### ISSUE TITLE
Remove Event.wrapper for VoiceSearch telemetry

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24640]
Breakout from #21292.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 101.0a1 (2022-04-13) by performing a search through voice search.
Some events that were generated:
![image](https://user-images.githubusercontent.com/48829350/163174472-c3aeadaf-339f-4a55-8609-331982230164.png)
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
