### ISSUE TITLE
Recently visited tabs are cut off

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24643]
Issue stems from the fact that these history items are to be presented in a horizontally scrolling list.
But when there are only 3 or fewer items and the list is not scrollable those items still have a lower width.
Issue seems even bigger when only one item is shown and it's ripple does not extend to the entire view.

| <img src="https://user-images.githubusercontent.com/11428869/161998491-6fbb9ded-19df-47c5-ac33-76671b2d50d1.png" width="33%" /> | <img src="https://user-images.githubusercontent.com/11428869/161999103-2e549d49-e297-432f-8e74-a96299b67811.png" width="33%" /> |

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20084)

**Comment by kbrosnan** [comment]
Is this https://www.androidpolice.com/stable-android-12l-exhibits-a-status-bar-glitch-that-wasnt-caught-in-months-of-beta-testing/

**Comment by Mugurell** [comment]
> Is this https://www.androidpolice.com/stable-android-12l-exhibits-a-status-bar-glitch-that-wasnt-caught-in-months-of-beta-testing/

It's just that [we hardcode a width smaller that the screen](https://github.com/mozilla-mobile/fenix/blob/dbfd5ffca0f54cf296657c44581ea1a3ecdd9dff/app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt#L217) for the items.
This allows the siblings to peek just a little and indicate to users that there are more items to be scrolled.

![image](https://user-images.githubusercontent.com/11428869/162147187-86f1fbf1-3612-4a33-92cf-86dd29ee0b6c.png)


But if there are no other items to scroll to then the first 3 items are smaller without benefiting in any way (TBD).
