### ISSUE TITLE
Remove Event.wrapper for TopSites telemetry

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#24642]
Breakout from #21292.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 101.0a1 (2022-04-14) by adding, removing a top site, opening a top site.
Some events that were generated:![image](https://user-images.githubusercontent.com/48829350/163349025-1220977a-0480-4d84-93c4-a6b2b42e8a7f.png)
![image](https://user-images.githubusercontent.com/48829350/163349163-14546d34-7233-4a31-b103-e22e1f1a3350.png)
![image](https://user-images.githubusercontent.com/48829350/163349514-d1aafa0c-1798-4ce7-8381-ab98f6b66bec.png)
![image](https://user-images.githubusercontent.com/48829350/163349628-b760784c-ff26-460b-88d7-bc88422d1523.png)
![image](https://user-images.githubusercontent.com/48829350/163350380-44754885-84f4-406d-9a65-897ceca044f9.png)
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
