### ISSUE TITLE
[Bug]: [L10N] "HTTPS-Only Mode" and its content is not translated many languages

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#24659]
### Steps to reproduce

1. Set the app language toa different language than English (Eg. Chinese).
2. Go to Settings and check the "HTTPS-Only Mode" string.
3. Tap on the "HTTPS-Only Mode" button and observe the content.

### Expected behaviour

The "HTTPS-Only Mode" string and its content are not translated.
Example: According to [Transvision](https://transvision.mozfr.org/?recherche=HTTPS-Only+Mode&repo=gecko_strings&sourcelocale=en-US&locale=zh-CN&search_type=strings) the word "Mode" should be translated.

### Actual behaviour

"HTTPS-Only Mode" and its content are partially or entirely translated.
In the example the word "Mode" is not translated.

### Device name

Oppo Reno 6

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

100.0.0-beta2

### Additional information

![Screenshot_2022-04-07-10-34-00-40_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/48829350/162145234-bbe4aaeb-2a04-4264-9ef5-e491a195cd46.jpg)

There are languages on which the Strings are correctly translated (Eg. Portugese).

**Comment by Delphine** [comment]
So this string landed late and was covered just a few days ago by most locales (example with [Italian](https://pontoon.mozilla.org/it/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?search=https+only+mode&string=243484) here).
I looked at your link to Transvision, and I noticed the toggle was on "gecko" vs "android".
But a quick look on Pontoon (you can change the locale code from the url) shows many locales have caught up with this string.
I will update instructions to look at Pontoon as "the source of truth" for this.
In the meantime, we will need to wait for the next l10n import into beta I believe, to see this fixed on v100

**Comment by SoftVision-LorandJanos** [comment]
I've already seen a this updated on many languages for 100.0.0-beta3. I've rechecked these strings on the languages tested on Beta 2:

Examples where the strings are now translated:
Spanish, German, Portuguese, Italian, Turkish, Ukrainian, Dutch, Swedish, Upper Sorbian.

Examples where the strings are still in English:
Partially Chinese, Arabic, Russian, French, Welsh, Armenian, Croatian, Indonesian, Slovenian

**Comment by Delphine** [comment]
Thanks for checking. I imagine that with each string import on beta, things will look better across locales. (checking on Pontoon seems like many have covered it now)
I think this issue can be closed for now. thanks!
