### ISSUE TITLE
[Bug]: localized text on main menu overlaps

### ISSUE THREAD

**Issue by farag2** [mozilla-mobile/fenix#24652]
### Steps to reproduce

1. Enable the Russian translation in the browser;
2. Open any tabs with one from bookmarks;
3. Kill Firefox process;
4. Open Firefox back;
5. Open sync page fast and return back;
6. Firefox logs into sync account;
7. Open menu;
8. The bookmark icon (indicated that the page is bookmarked) overlapped the text;

### Expected behaviour

It has to have space between "Bookmarks" word and the icon in Russian

### Actual behaviour

The bookmark icon indicated that the page is from bookmarks overlapped the text. In opinion, the menu is too narrow to fit all words.

![photo_2022-04-06_22-29-53](https://user-images.githubusercontent.com/10544660/162064447-05ba1ce4-9ae9-4727-a562-34be8a264f1c.jpg)

### Device name

Xiaomi Mi 10T

### Android version

12

### Firefox release type

Firefox Beta

### Firefox version

100.0.0-beta.2

### Additional information

I have been facing this bug for 1,5 years already.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20094)

**Comment by farag2** [comment]
Since 108.0b2 release the string was translated to a string with more characters in it, so the bug is gone for now. Closing...

![Screenshot_2022-11-19-16-18-42-975-edit_org mozilla firefox_beta](https://user-images.githubusercontent.com/10544660/202852723-d8a02214-dd38-4b03-9425-b2f610d85194.jpg)

**Comment by farag2** [comment]
108.0b4
The bug is back again: the string translation was reverted and now the bookmark star overlaps the text. Why it's so difficult to fix it for all years?..

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809249

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
