### ISSUE TITLE
Bad alignment of number in tabs button when using OnePlus font

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#24667]
### Steps to reproduce

0. use a OnePlus smartphone with OnePlus Sans instead of Roboto as system font
1. open Firefox

### Expected behaviour

The number in the tabs button is well aligned.

### Actual behaviour

The number in the tabs button sticks to the top.

![Screenshot_2022-04-07-21-35-15-08_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/1100614/162282896-36d9a2ee-ff3f-4051-967d-04bba323d275.jpg)

### Device name

OnePlus 10 Pro

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20104)

**Comment by cadeyrn** [comment]
This is still an issue.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813679

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
