### ISSUE TITLE
[Bug]: No support for Hardcoded Preferences

### ISSUE THREAD

**Issue by davidBar-On** [mozilla-mobile/fenix#24668]
### Steps to reproduce

We are developing an Android mobile device, including Firefox as part of the device firmware.  We want to use the standard Firefox release APK, but be able to set some preferences to harden the device.  These preferences settings should be hardcoded in the firmware, so there will be no way to change them.

The problem is that **we did not find anyway to do that**.  For example, if hardcoded `user.js` was supported, then it could be a solution.

The response to issue #18679 is `We are not going to allow browser prefs to be stored in a world writable location`.  However, we don't need a writable prefs.  We just need a way to specify such hardcoded prefs, using the standard Firefox released APK, without building the browser ourselves.

Is there a way that we can set the prefs as described above?

### Expected behaviour

NA

### Actual behaviour

NA

### Device name

Private

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

Latest

**Comment by kbrosnan** [comment]
Not a Fenix bug. You should talk to the Geckoview team info at https://mozilla.github.io/geckoview/ you may need to compile a custom GV to get that behavior.
