### ISSUE TITLE
[Bug]: tracking protection text in identity panel is truncated in German version

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#24666]
### Steps to reproduce

0. use German as language
1. open google.com
2. tap the lock icon in the address bar

### Expected behaviour

No truncated text.

### Actual behaviour

Truncated text.

![Screenshot_2022-04-07-21-01-26-76_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/1100614/162282040-5885825f-aa0a-4eec-8216-560294bd2710.jpg)

### Device name

OnePlus 10 Pro

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.1.1

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20103)

**Comment by kbrosnan** [comment]
We should provide a bit more space for the text.

**Comment by SoftVision-LorandJanos** [comment]
Hi @cadeyrn ! Thanks for the report!
I could reproduce your issue on the latest Nightly 101.0a1 (2022-04-15).
Device used: Oppo Reno 6 (Android 12).

**Comment by lapaz17** [comment]
I'd like to work on this.

**Comment by Amejia481** [comment]
👋🏽 
@lapaz17 please feel free to take it!
If you need any help just let me know, happy to help!

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 102.0a1 (2022-05-17) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
