### ISSUE TITLE
[Bug]: File is not uploaded in Open-Xchange OX Drive

### ISSUE THREAD

**Issue by ITfee** [mozilla-mobile/fenix#24662]
### Steps to reproduce

1. Open https://www.open-xchange.com/ox-cloud-demo/
2. Hit the button "Try full features now"
3. After that move to https://try-gold.ox.io/appsuite/#!!&app=io.ox/files
4. In the bottom choose the secon icon (a cloud with a top arrow inside)
5. Choose "Upload file"
6. Upload any file
7. No file was uploaded

### Expected behaviour

File should be uploaded

### Actual behaviour

File is not uploaded

### Android version

11

### Firefox release type

Firefox

### Firefox version

98.3.0

### Additional information

Works pretty well with the desktop version of Firefox under Windows 10...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20099)

**Comment by kbrosnan** [comment]
This needs to be tested in GVE to understand if this is a Gecko bug
