### ISSUE TITLE
Removing last tab from a collection does not update the shape for the new last tab

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24660]
STRs:
-  have a collection already created with multiple tabs
- expand the collection
- remove the last tab shown in the collection

Expected result:
- the new last tab has rounded bottom corners

Actual result:
- the new last tab has only right angles

https://user-images.githubusercontent.com/11428869/162208239-dbc02b73-dcee-48c6-a5ba-5a0a9e313e00.mp4

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20098)

**Comment by lapaz17** [comment]
I would like to proffer me working on this.

**Comment by lapaz17** [comment]
@Mugurell  I opened a PR, Could you confirm workflow approval for https://github.com/mozilla-mobile/fenix/pull/24985 also?

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly from 05/18 with Google Pixel 6 (Android 12). After deleting the last tab from a collection, the collection's bottom side/last tab remained have rounded shape.

https://user-images.githubusercontent.com/89388888/168989236-9c572810-3d1c-4ec3-8170-1b5a7cd45e62.mp4
