### ISSUE TITLE
crash maybe due to Tesla app

### ISSUE THREAD

**Issue by Frankadams1g** [mozilla-mobile/fenix#24670]
Very slow to load pages, can only open one or two at a time, seems to also correspond with the Tesla logo disappearing from the top of screen next to the time. New problem in the last month. Tried restarting etc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20106)

**Comment by kbrosnan** [comment]
We would need a performance profile of this behavior to understand what is going on. https://profiler.firefox.com/docs/#/./guide-remote-profiling
