### ISSUE TITLE
Add bookmark when sharing a link to the browser like in Fennec 68

### ISSUE THREAD

**Issue by mollyrealized** [mozilla-mobile/fenix#24674]
The prior 'share' functionality of Firefox was useful and robust.

If you were reading an e-mail and wanted to bookmark only certain links within the e-mail, you could share and bookmark them directly from the share menu.

If you knew a particular link belonged on your home or work machine, you could direct it there.

You're now required to open each one in Firefox, bookmark it, and close the tab.  It is **_phenomenally_** less useful and less functional.  Respectfully, I fail to understand why the change was made.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20107)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813743

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
