### ISSUE TITLE
[Bug]: Unify Accept-Language header with Firefox Desktop and Chrome

### ISSUE THREAD

**Issue by Remu-rin** [mozilla-mobile/fenix#24689]
### Steps to reproduce

Non-English:
1. Have a non-English language in OS (e.g. Russian)
2. Open https://httpbin.org/headers

English:
1. Have an en-US language in OS
2. Open https://httpbin.org/headers

### Expected behaviour

Should be similar to other platforms and browsers.

English:
Firefox (Windows): `en-US,en;q=0.5`
Chrome (Android and Windows): `en-US,en;q=0.9`

Non-English OS, default in browser:
Firefox (Windows): `ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3`
Chrome (Android and Windows): `ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7`

Non-English OS, English in browser (after changing language and removing non-English in settings):
Firefox (Windows): `en-US,en;q=0.5`
Chrome (Android and Windows): `en-US,en;q=0.9`

Also Javascript seems to report only first preferred language everywhere (including Fenix), e.g. `en-US` for English and `ru-RU` for non-English, so no change is needed.

### Actual behaviour

English:
Fenix: `en-US`

Non-English OS, default in browser:
Fenix: `ru-RU`

Non-English OS, English in browser (not possible to remove non-English from header due to #6502):
Fenix: `en-US,ru-RU;q=0.5`

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

99.1.1

### Additional information

I'm not sure if it belongs here or to Geckoview.
I find it strange that Fenix is so different in this aspect to other browsers and even to desktop Firefox.

**Comment by kbrosnan** [comment]
Need to check this against GVE and see if this is a platform issue or something for the Fenix team.

**Comment by kbrosnan** [comment]
Think this is being tracked at bz-1765375
