### ISSUE TITLE
[Bug]: JSON viewer does not work

### ISSUE THREAD

**Issue by mintyhaze** [mozilla-mobile/fenix#24693]
### Steps to reproduce

1. Open any JSON document with application/json Content-Type

### Expected behaviour

JSON should be rendered in the same (or at least similar) viewer as on desktop Firefox.

### Actual behaviour

JSON renders as plain text, whcih makes it unreadable if it was minimized and unicode-escaped.

### Android version

10

### Firefox release type

Firefox Beta

### Firefox version

100.0.0-beta3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20116)

**Comment by qrqhuang** [comment]
+1
