### ISSUE TITLE
add an option to disable download confirmation each time !!!!!!

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#24695]
### Steps to reproduce

many browsers like Chrome or let's say kiwi in download setting have an option to disable ask for download confirmation ,it would be nice if fenix added that option too ,see screnshot  : 
https://i.imgur.com/yTlbY64.png

### Expected behaviour

Fenix alway offers a subpar experience compared to other browser 

### Actual behaviour

I d like to download files without download conformation .

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

101

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20117)

**Comment by lapaz17** [comment]
I'd like to work on this.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812787

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
