### ISSUE TITLE
[Bug]: QR code scanner doesn't work if protocol is written in capitals

### ISSUE THREAD

**Issue by selimsumlu** [mozilla-mobile/fenix#24692]
### Steps to reproduce

1. Open QR code scanner.
2. Scan the sample QR codes provided [here](https://connect.mozilla.org/t5/ideas/http-and-https-support-android-qr-scanner/idc-p/3891).

### Expected behaviour

The HTTPS://www.mozilla.org address should work as intended.

### Actual behaviour

"Web address not valid." error is displayed.

### Device name

realme 6

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1

### Additional information

This affects all Yandex Disk links as reported [here](https://support.mozilla.org/tr/questions/1373577).

**Comment by kbrosnan** [comment]
This seems like something a contributor could help us with. We should convert the URI to lowercase before making sure it is an acceptable protocol.

**Comment by jknair0** [comment]
Hi! Can I pick this up?

**Comment by jknair0** [comment]
I have found the issue was due to the comparision that was happening in Uri's `isHttpOrHttps` is case sensitive. I have raised the PR.
I haven't modified the normalizedUrl's case since it could affect the query parameters which might be case sensitive.

**Comment by Mugurell** [comment]
Based on @jknair0's initial PR for this - https://github.com/mozilla-mobile/fenix/pull/24766 it seems like the cleanest solution would involve a change in AC for which I've opened https://github.com/mozilla-mobile/android-components/issues/11998.

A local version of Android-Components can be used when working on this by following the guide from https://github.com/mozilla-mobile/fenix#auto-publication-workflow-for-android-components-and-application-services.

**Comment by Mugurell** [comment]
Fix should be available in the next Nightly.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 15/4 with OnePlus 9 (Android 12).
