### ISSUE TITLE
Remove Event.wrapper for credit card telemetry 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24707]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 101.0a1 (2022-04-13) by accessing the checkout.stripe.com test page. After selecting different credit cards from the "Select credit card prompt.", the Card numer/card name fields were autofilled with the correct data. 
Some events that were generated:
![image](https://user-images.githubusercontent.com/89388888/163588481-dc02a8fc-8fac-4033-8f74-b3b36f28985e.png)
Device used: Google Pixel 6 (Android 12).
