### ISSUE TITLE
Replace Mockito mocks with Mockk mocks

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#24703]
There are placed in our unit tests where Mockito mocks are used and this is causing intermittent test fails.

Saw this issue and fixed two cases on https://github.com/mozilla-mobile/fenix/pull/24620, today I saw [another occurrence](https://firefoxci.taskcluster-artifacts.net/OmWdljybRhGtBDdPjfFisQ/0/public/reports/test/testDebugUnitTest/classes/org.mozilla.fenix.wifi.WifiConnectionMonitorTest.html#WHEN%20the%20connection%20is%20available%20THEN%20listeners%20will%20be%20notified) for another PR.

We'll need to search for all places where `mock` is used and replace it with `mockk`. 
Special care is needed for deciding where to use a relaxed mockk or not. (behavior is different between Mockito and Mockk)

**Comment by Alexandru2909** [comment]
Nothing to test for QA, issue deals with unit tests.
