### ISSUE TITLE
Remove Event.wrapper for Pocket related telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24701]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by sflorean** [comment]
Verified as fixed on OnePlus 9 Pro (Android 12).
Glean: 

`{"timestamp":358,"category": "pocket", "name": "home_recs_shown"},{"timestamp":3856,"category": "pocket", "name": "home_recs_category_clicked", "extra":{"new_state": "selected", "category_name": "quick-reads", "selected_total": "0"}},{"timestamp":3900,"category": "pocket", "name": "home_recs_shown"},{"timestamp":4598,"category": "pocket", "name": "home_recs_category_clicked", "extra":{"selected_total": "1", "new_state": "selected", "category_name": "health"}},{"timestamp":4637,"category": "pocket", "name": "home_recs_shown"},{"timestamp":5106,"category": "pocket", "name": "home_recs_category_clicked", "extra":{"category_name": "self-improvement", "selected_total": "2", "new_state": "selected"}},{"timestamp":5149,"category": "pocket", "name": "home_recs_shown"},{"timestamp":5601,"category": "pocket", "name": "home_recs_category_clicked", "extra":{"category_name": "science", "new_state": "selected", "selected_total": "3"}},{"timestamp":5632,"category": "pocket", "name": "home_recs_shown"}.`
