### ISSUE TITLE
Intermittent UI test failure - org.mozilla.fenix.settings.sitepermissions.SitePermissionsManageExceptionsPhoneFeatureFragmentTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#24700]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=373954344&repo=fenix
### Stacktrace:
```
  TEST: GIVEN a BlockAudible WHEN updateSitePermissions is called THEN site permissions will include autoplayAudible BLOCKED and autoplayInaudible ALLOWED
    W/PackageParser: Unknown element under <manifest>: queries at /builds/worker/checkouts/vcs/app/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_ Binary XML file line #40
  FAILURE

org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced or misused argument matcher detected here:

-> at mozilla.components.support.test.MatchersKt.eq(Matchers.kt:27)
-> at mozilla.components.support.test.MatchersKt.eq(Matchers.kt:27)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/42b9e95585b4d28cec6d2c439c35c2a992b195d3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20119)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813764

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
