### ISSUE TITLE
Remove Event.wrapper for addons telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24715]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 101.0a1 (2022-04-13) by accessing the addons page, installing an addon, disabling/enabling entirely and only for a site, uninstalling it.
Some events that were generated:![image](https://user-images.githubusercontent.com/48829350/163196686-c6f9fe19-0938-44ca-b1e6-29b5293aae36.png)
![image](https://user-images.githubusercontent.com/48829350/163196915-30052bad-6434-41f1-a7db-2c7c7ab8ff64.png)
Device used: Samsung Galaxy Tab S3 (Android 9).
Closing the ticket as fixed.
