### ISSUE TITLE
[Bug]: firefox app cant paste 

### ISSUE THREAD

**Issue by honnybee7** [mozilla-mobile/fenix#24717]
### Steps to reproduce

Try to paste something in site 
Doesnt work 

### Expected behaviour

Should paste 

### Actual behaviour

Doesnt paste 

### Device name

Samsung galaxy a6

### Android version

Not sure 

### Firefox release type

Firefox

### Firefox version

99.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20129)

**Comment by honnybee7** [comment]
Is anyone there to help me?

**Comment by marcel263** [comment]
> Is anyone there to help me?

thisnis not a support forum, although your provifing of a screen recording for a mentioned site , version of android, etc. would contribute to a solution 

thank you

**Comment by honnybee7** [comment]
> > Is anyone there to help me?
> 
> thisnis not a support forum, although your provifing of a screen recording for a mentioned site , version of android, etc. would contribute to a solution
> 
> thank you

Screenshot not necessary just check the paste function in firefox

**Comment by cadeyrn** [comment]
And providing all the other information you were asked are for is not necessary because…?

**Comment by honnybee7** [comment]
> And providing all the other information you were asked for is not necessary because…? You pushed your own issue only one day after the creation so it seems important to you. Then you should provide as much information as possible at least.

How do I show a screenshot it's not pasting?

**Comment by marcel263** [comment]
Provide a website where this is reproducible.
Show a screen recording of the process
Please considef reading the contribution guidelines on the "fenix" home page on github.
repeatedly said, here, fixing bug and analysing their details is the main objective, not support.

**Comment by honnybee7** [comment]
> Provide a website where this is reproducible. Show a screen recording of the process Please considef reading the contribution guidelines on the "fenix" home page on github. repeatedly said, here, fixing bug and analysing their details is the main objective, not support.

This is reproducible in any site but you can try google. It seems so far what I copy outside of firefox like my chrome app it cant paste and it seems to not work at night in the day it works fine.

So to be clear at the steps to reproduce it copy something from the chrome app then go to the firefox app go to google go to the search bar and paste. And periodically try it throughout the day since for me in the day it works fine but night it doesnt work. I'm not sure how to do screen recording on my phone so should I download an app or should it come with that feature? 

Also I'm confused what's the difference of this site here reporting bugs but not being support so do you mean all we do here is report bugs it doesnt get fixed here?

**Comment by honnybee7** [comment]
I guess with one of you guys giving my reply a dislike and not replying you found it unsatisfactory if you still need the screen recording let me know how to do it.

**Comment by honnybee7** [comment]
Uhhh if you find my reply unsatisfactory then say so if your issue is about the screen recording please tell me how to do it. Giving me the silent treatment is childish and unhelpful.

**Comment by marcel263** [comment]
> Uhhh if you find my reply unsatisfactory then say so if your issue is about the screen recording please tell me how to do it. Giving me the silent treatment is childish and unhelpful.

Does this help: https://infos-geek.com/en/comment-enregistrer-un-appel-video-sur-samsung-galaxy-a6/

Please be mindful of the contribution guidelines. You are not entitled to any service

**Comment by honnybee7** [comment]
My firefox seems to go back to normal I'm going to give it a couple more days to see if the issue pops up back again.

**Comment by honnybee7** [comment]
https://user-images.githubusercontent.com/36801964/165027507-59ecf592-ee6f-4501-918c-9d7957f01b28.mp4

**Comment by honnybee7** [comment]
It's still not working for some reason at nights it stops pasting I see its linked to copying from my chrome.

**Comment by honnybee7** [comment]
> > Uhhh if you find my reply unsatisfactory then say so if your issue is about the screen recording please tell me how to do it. Giving me the silent treatment is childish and unhelpful.
> 
> Does this help: https://infos-geek.com/en/comment-enregistrer-un-appel-video-sur-samsung-galaxy-a6/
> 
> Please be mindful of the [contribution guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/). You are not entitled to any service

Can check out the video I posted

**Comment by honnybee7** [comment]
What's the steps you did to reproduce

**Comment by honnybee7** [comment]
Can someone please respond

**Comment by honnybee7** [comment]
@amocirean can you get back to me
