### ISSUE TITLE
Remove Event.wrapper for recent bookmarks telemetry 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24710]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-15 by interacting with the recently bookmarked section on the homepage and observing the results.
The times a recent bookmark was clicked
recent_bookmarks.bookmark_clicked	3
The time the show all recent bookmark was clicked 
recent_bookmarks.show_all_bookmarks	3

When the recently bookmarked section is seen on the homepage
{
          "timestamp": 725,
          "category": "recent_bookmarks",
          "name": "shown"
        }

The number of recently bookmarked page    
recent_bookmarks.recent_bookmarks_count	4

[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/LaurentiuForce-1504)
### Device used:
- OnePlus 6T (Android 9)
