### ISSUE TITLE
[Bug]: Page renders in partial display area

### ISSUE THREAD

**Issue by staktrace** [mozilla-mobile/fenix#24729]
### Steps to reproduce

1. Go to https://www.cbc.ca/news/canada/hamilton/abby-post-newspaper-port-dover-1.6415704?cmp=rss
2. The page should be in a state where horizontal scrolling is required to view the content. Pinch zoom out so that the entire content width is visible and horizontal scrolling is not required
3. Scroll down past the article content to the "Popular now in news" section.
4. Click on one of the news articles linked in that section. Section is dynamic so you may get different articles but I went to https://www.cbc.ca/news/politics/poilievre-conservative-leadership-1.6416183

### Expected behaviour

New article should render normally

### Actual behaviour

Article renders in a viewport area that is smaller than the tab content area, with the rest of the space being gray. Scrolling around also moves the viewport within the tab content area. See screenshots

### Device name

Sony Xperia XZ1C

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

99.1.1 (Build #2015871915), 6679da615+

### Additional information

![Screenshot_20220412-090334](https://user-images.githubusercontent.com/485789/162969303-2fbff780-442b-4c28-baeb-4b54596a4cb3.png)
![Screenshot_20220412-090345](https://user-images.githubusercontent.com/485789/162969554-ceeb59d1-998a-4bd9-a8b8-521815ab4c4e.png)

**Comment by tnikkel** [comment]
If it's broken in other browsers then wouldn't it  be a site issue? Not a firefox issue?

**Comment by Dunexus** [comment]
Based on the latest comments on bugzilla, it seems like there is both a site issue and firefox issue behind this weird behavior.
