### ISSUE TITLE
Typing some text and deleting it all should re-show the QR code button

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#24739]

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 101.0a1 (2022-04-27) build.
After the "Enable unified search" toggle is turned on from secret settings, the scan icon appears in the address bar with the following behavior:
- tapping on the address/search bar displays the scan icon.
- typing in the address/search bar hides the scan icon.
- after deleting the content of the address/search bar, the scan icon is re-displayed.

Closing the ticket as fixed.
