### ISSUE TITLE
[Bug] Private Tabs leaking into regular 'Open Tabs' category

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2473]
Build: 917399d8971c97e6d9b7c197c30b70ff75d74670
Device: Pixel 2 (x86)

* Open private browsing mode
* visit mozilla.org
* Return to the 'regular tabs' home-screen
* see mozilla.org in the open tabs category

**Comment by sblatz** [comment]
This is almost certainly due to our [ViewModel changes](https://github.com/mozilla-mobile/fenix/pull/2457).

@boek is investigating.

**Comment by sblatz** [comment]
Dupe of #2411
