### ISSUE TITLE
[Bug]: clicking on web notification makes fenix crash 

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#24736]
### Steps to reproduce

following very recent changes on push notification in fenix (notification click should finally open corresponding tab eg :.intagram )make today nightly crash .
not all notifications in my case Instagram push notification on click crash the browser ,telegram 's one are OK (even though fail to open correct telegram chat)

### Expected behaviour

browser should not crash

### Actual behaviour

Fenix crash :
log :
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.IntentReceiverActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

101 

### Device logs

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.IntentReceiverActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

**Comment by amocirean** [comment]
Hello @ale82to, thanks for submitting the issue.
I was not able to reproduce the steps on latest RC (101.1.0) or Latest Nightly 101.0a1 (2022-04-28).
Does the issue still occur on the latest RC/Nightly on your device?

- Android Version: 11
- Devices Used: Xiaomi Mi 11 Lite

**Comment by ale82to** [comment]
yes I've just received an Instagram notification and tapping on it made fenix crash.

**Comment by jonalmeida** [comment]
Thanks for filing this. I found the crash full crash signatures here: https://sentry.io/organizations/mozilla/issues/3178677128

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1768574

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jonalmeida** [comment]
This should be fixed in nightly and the next beta.
