### ISSUE TITLE
Switching to a vertical search engine (Amazon, eBay, etc.) or bookmarks/history should hide the QR code button

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#24738]
1. It is shown only on a blank general search (Google, Bing, DDG, etc.)
2. Switching to a vertical search engine (Amazon, eBay, etc.) or bookmarks/history should hide the QR code button

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 102 from 05/25.
