### ISSUE TITLE
Investigate whether a weak reference is still needed in SearchSelectorToolbarAction

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24744]
This is a follow up from a conversation with @csadilek regarding https://github.com/mozilla-mobile/fenix/pull/24732/files#diff-6878fa8bd134525847765379db3ae0d3d37bdef58007c8dbc6c596c329366d47. 

Notes from @csadilek
> This looks good to me relative to what we have, but we really shouldn't need that weak reference. I can't find the blame, but this looks like a bug workaround for the lifecyclescope thingy.
> 
> If the observer is bound to the viewLifecycleOwner there shouldn't be a case where we collect and update the UI if the view is no longer alive.
> 
> Unless this leaked in a different way I don't understand right now.
> 
> I think we can dig up the blame on the fenix side where this was changed before we upstreamed to A-C.
> 
> It really shouldn't make a differences, unless the Action lives longer than the view  then we would leak.
> 
> (And I am not sure that's true anymore.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20144)

**Comment by Mugurell** [comment]
@ QA: This ticket was about refactoring code, please ensure the app functions the same as before in regards to the search engine selector from toolbar (part of unified search).

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 103.0a1 2022-06-09 by selecting different search engines from the toolbar and didn't encounter any issues.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
