### ISSUE TITLE
[Bug] color contrast issues with wallpapers

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#24754]
### Steps to reproduce

1. use a wallpaper

### Expected behaviour

There are no issues with the legibility of the home screen content.

### Actual behaviour

Depending on the used wallpaper and enabled home screen content there are issues with the legibility. Of course it's more difficult with an image than with a solid background color but maybe some things can be improved in a general way. For example the collections box could use a background color. What the following screenshot shows is not readable at all:

![Screenshot_2022-04-13-09-15-00-98_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/1100614/163121148-1053ec37-1d21-47eb-abd7-571a09714b92.jpg)

Another example is the "Show all" link. When using a dark theme it can be hard to read:

![Screenshot_2022-04-13-09-15-43-47_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/1100614/163121181-194c459d-3ffe-4633-843b-301d8b228c91.jpg)

### Device name

OnePlus 10 Pro

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20149)

**Comment by SoftVision-LorandJanos** [comment]
Hi @cadeyrn ! Thanks for the report!
I could reproduce your issue on the latest Nightly 101.0a1 (2022-04-15).
However there's an easy workaround by scrolling the page in a position where the text is readable.
Also there was a bug related, which was fixed: #22950.
I would change this ticket from a bug to feature request to make the text easier to read with better contrast if possible.
Device used: Oppo Reno 6 (Android 12).

**Comment by delia-pop** [comment]
This issue was fixed in https://github.com/mozilla-mobile/fenix/issues/27026 and is verified as fixed on the latest Nightly 107.0a1 from 09/23 with Google Pixel 6 (Android 13). The Collections placeholder adapts to the text color.

![1663946708354](https://user-images.githubusercontent.com/89388888/191996742-8653d6fa-6936-48fe-bcad-65e39b56a625.JPEG)
