### ISSUE TITLE
Remove Event.wrapper for BrowserSearch telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24758]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 101.0a1 (2022-04-27).
Some events that were generated:
![image](https://user-images.githubusercontent.com/48829350/165523165-e4add441-cfe5-41f9-9c34-456c0000b664.png)
![image](https://user-images.githubusercontent.com/48829350/165523368-ef596fe1-1a1d-4117-974a-99c0ee8ebde7.png)
![image](https://user-images.githubusercontent.com/48829350/165523454-a2dc2a22-7975-4827-965c-4b09b52238f8.png)

Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
