### ISSUE TITLE
[Bug]: Remote wallpapers look squashed in wallpaper settings

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#24753]
### Steps to reproduce

0. Make sure you use Firefox in a language with enabled remote wallpapers
1. Open the wallpaper settings

### Expected behaviour

Wallpapers look good.

### Actual behaviour

The remote wallpapers look squashed. Maybe it affects the other wallpapers as well but since the other wallpapers only show patterns and not "real things" it's difficult to say.

![Screenshot_2022-04-13-08-54-49-02_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/1100614/163119858-47664eb7-c342-4806-9993-c209f6b79bfc.jpg)

### Device name

OnePlus 10 Pro

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20148)

**Comment by delia-pop** [comment]
Hello, @cadeyrn ,

Please note that we reported issue [FNXV2-19464](https://mozilla-hub.atlassian.net/browse/FNXV2-19464) during the early testing stage of the feature. At that time and until now, the wallpapers on Portrait orientation have looked the same.
