### ISSUE TITLE
Enable Pocket recommendations for more languages

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#24752]
It would be great if you could enable Pocket recommendations for more languages. Currently Pocket recommenations are only enabled for en-US and en-CA. In Firefox for desktop they are also enabled for other languages, like German. So I hope you can enable it for other supported languages as well, since it doesn't look like that Firefox for Android shows anything that Firefox for desktop does not show, so we seem to have everything we need.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20147)

**Comment by Mugurell** [comment]
I'd say this is more to ensure the best user experience with all stories recommendations only being in english for now.
There is no actual geo restriction so if a user has en-US / en-CA locale set chances are she will be ok with english content, and will get to see english stories recommendations, otherwise it might be seen as an issue.
I think it's the same for iOS.

**Comment by cadeyrn** [comment]
Thank you for the answer, @Mugurell.

> There is no actual geo restriction so if a user has en-US / en-CA locale set chances are she will be ok with english content, and will get to see english stories recommendations

That's true. But I would like to continue using Firefox in German, especially since it's not only about the localization of the feature: users with German locale get different recommendations than users with English locale. I want to see the same recommendations on Android as on desktop because most of the English recommendations are not relevant to me. I also want to highlight that Firefox for desktop is very similar to Firefox for Android with regards to Pocket recommendations: There is only a small headline, the source, the reading time and an image. So if it works for German in Firefox for desktop and works for English in Firefox for Android then I am pretty sure it will also work for German in Firefox for Android, from an user experience POV.

That's why I hope that it can soon be enabled for other laguages as well if you don't see technical reasons (like a different API on Android that only supports English) why it couldn't be done.

**Comment by cadeyrn** [comment]
Comment for bot:

Pocket is still not available for other regions, like Germany and Austria. So please keep this issue open.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810844

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
