### ISSUE TITLE
[Bug]: Toolbar doesn't hide when css transformation is on going.

### ISSUE THREAD

**Issue by jeongoon** [mozilla-mobile/fenix#24751]
### Steps to reproduce

1. Go to Settings -> Customise 
2. Set to Toolbar: Bottom; Gesture: Scroll to hide toolbar
3. Visit the following site
    https://keithclark.co.uk/articles/pure-css-parallax-websites/demo3/
4. Scroll up
5. Scroll down

### Expected behaviour

4. "Scroll up" should hide the toolbar at the bottom
5. "Scroll down" should reveal the toolbar again.

### Actual behaviour

4. "Scroll up" doesn't hide toolbar
which makes impossible to see the content at the bottom if the content position is relative or absolute.

### Device name

Galaxy Note 10+

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.1.1

**Comment by Mugurell** [comment]
At a quick look there doesn't seem to be any layout issue in the linked website and the toolbar is behaving as expected - the scroll is consumed by the parallax. The same is happening on Chrome.

Moving to Bugzilla for more investigation. Please follow the issue there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1764498

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
