### ISSUE TITLE
FNX3-16351 ⁃ [Bug] On closing the last tab in private browsing, mismatched home-screen state on regular tab screen

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#2476]
* Build: 917399d8971c97e6d9b7c197c30b70ff75d74670
* Device: Pixel 2 (Android 9)

E.g, Crash via https://github.com/mozilla-mobile/fenix/issues/2475

> 1. From the Library, open a bookmark in a new private tab
> 2. Tap the 'All Tabs' button on the address bar

Then switch to 'normal' tab mode.

See screenshot.

![device-2019-05-14-113929](https://user-images.githubusercontent.com/102331/57711708-3e311f00-763d-11e9-9540-78dd79062abd.png)

**Comment by AaronMT** [comment]
Reproducible by closing the last tab in private browsing and swapping back out of the mode

**Comment by sblatz** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/2499

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 5/20 build.
device: Note 8 (Android 9)
