### ISSUE TITLE
[Bug]: The Firefox Homepage Messaging Banner is not displayed if Homepage is set as opening screen

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#24771]
### Steps to reproduce

1. Launch Fenix;
2. Go to Settings -> Homepage and select Homepage as opening screen;
3. Relaunch Fenix.

### Expected behaviour

The Firefox Homepage Messaging Banner should be displayed above the top sites section.

### Actual behaviour

The Firefox Homepage Messaging Banner is not displayed until a webpage is opened.

### Device name

Google Pixel 6

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 2022-13-04

### Additional information

https://user-images.githubusercontent.com/50983519/163211180-d115a4f5-8ece-4b53-92a7-b3ed4577b8ae.mp4

**Comment by cpeterso** [comment]
https://mozilla-hub.atlassian.net/browse/FNXV2-20160

**Comment by Amejia481** [comment]
Same as https://github.com/mozilla-mobile/fenix/issues/24773#issuecomment-1098632832
