### ISSUE TITLE
[Bug]: The Firefox Homepage Messaging Banner is not displayed if there are no tabs opened

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#24770]
### Steps to reproduce

1. Launch Fenix and close all tabs;
2. Restart Fenix;
3. Open any webpage;
4. Navigate to the homepage.

### Expected behaviour

The Firefox Homepage Messaging Banner should be displayed above the top sites section.

### Actual behaviour

The Firefox Homepage Messaging Banner is not displayed until a webpage is opened.

### Device name

OnePlus 6T

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 2022-04-13

### Additional information

https://user-images.githubusercontent.com/50983519/163209019-0e82f13d-30e3-489a-bd1c-e9ba3f5cbb22.mp4

**Comment by cpeterso** [comment]
https://mozilla-hub.atlassian.net/browse/FNXV2-20159

**Comment by Amejia481** [comment]
Same as https://github.com/mozilla-mobile/fenix/issues/24773#issuecomment-1098632832
