### ISSUE TITLE
RE: Add a "Copy Link Text" button in link's long press menu Firefox Android

### ISSUE THREAD

**Issue by ganon69** [mozilla-mobile/fenix#24777]
Hello, this request was submitted more than a year ago. It was never solved and subsequently closed. This feature for Firefox on Android is a must. Needless to say, practically all the other browsers on Android that use Blink have this feature. Don't understand why it can't/won't be implemented under Gecko. Please advise. Thx.

![Copy Link As Text](https://user-images.githubusercontent.com/34172976/163276886-2c755001-3ee6-44fd-91d5-fd9d9e62d0c5.jpg)

**Comment by DavidJCobb** [comment]
#16582
