### ISSUE TITLE
[Bug]: The Firefox Homepage Messaging Banner is not displayed right after updating Fenix to the latest version

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#24773]
### Steps to reproduce

Preconditions:

Make sure Fenix is not set as Default browser in Device settings.
Have an older version of the application installed, on which the Homepage Messaging Banner is not available.

STR:
1. Update and launch Fenix.
2. Verify the default browser banner is displayed on homepage.

### Expected behaviour

The Firefox Homepage Messaging Banner (default browser) should displayed on homepage after updating the app to the latest version containing the feature.

### Actual behaviour

The Firefox Homepage Messaging Banner (default browser) is not displayed on homepage after updating the app.
The banner will be triggered only of the user visits another page/menu or send the application in background and then returns on homepage.

### Device name

Motorola Moto G30

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 2022-13-04

### Additional information

https://user-images.githubusercontent.com/89388888/163213499-4614e294-987e-403b-864e-1274e4397781.mp4

**Comment by Amejia481** [comment]
As we are fetching the messages from nimbus async on a background thread, there is no a warranty that we are going to see the messaging banner just after launching the app, as it could take some time after we get the messages.  What we can warranty is that eventually after the second app launch the user will see the message on the homepage. We are evaluating when we should show the message every time we enter to the home screen, to test you could leave/enter the app by pressing the middle button and then switching to the app again.

**Comment by cpeterso** [comment]
https://mozilla-hub.atlassian.net/browse/FNXV2-20161
