### ISSUE TITLE
[Bug]: Zooming page on "t.me", telegram shared msg, hangs browser

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#24787]
dear, Evidence from the occuring problem, included you may find the screencast.

https://user-images.githubusercontent.com/76437842/163344520-418f1e0a-bb52-4b40-9865-384696fddbda.mp4

### Steps to reproduce

1. Open specified Telegram share link, or hypothetically any (untested) - notice for 18+ material: https://t.me/bmpd_cast/11362
2. zoom and by pinching routine of in and out, cause lockup

### Expected behaviour

normal operation

### Actual behaviour

Zooming causes browser lock up, eventually causing full disruption and the freezing of the UI. Must force close through Android popup.

### Device name

Samsung

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 (Build #2015874507), 1a49d795d+ AC: 101.0.20220413143058, f1a8114ad7 GV: 101.0a1-20220413094328 AS: 91.1.1

### Device logs

```
Qualcomm -- Adreno (TM) 618
OpenGL ES 3.2 V@0502.0 (GIT@e1ac91e, I2b3b5fbd00, 1605636002) (Date:11/17/20)



### Additional information

_No response_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20167)

**Comment by SoftVision-LorandJanos** [comment]
Hi @marcel263! Thank you for your report!
I can confirm that the issue you described is reproducible.
Tested it on Chrome as well where it is reproducible also.
Device used: Google Pixel 4 (Android 12).
Firefox version: Nightly 101.0a1 (2022-04-14).

**Comment by marcel263** [comment]
still relevant

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813173

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
