### ISSUE TITLE
[Bug]: sometime getting black screen on webpages

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#24782]
### Steps to reproduce

Issue is random..sometime while opening sites from shortcuts I am getting a black screen..even after reloading it shows the same

### Expected behaviour

Page should display

### Actual behaviour

Getting black screen

### Device name

rog 3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Additional information

![Screenshot_20220414-101653546](https://user-images.githubusercontent.com/58127841/163318571-451298b8-2114-4d89-b34e-1662e732f878.jpg)

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Nightly 2022-04-20 but was unable to.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by sheikh-azharuddin** [comment]
Here is the video....


https://user-images.githubusercontent.com/58127841/164280225-7cc765d9-6a08-4a60-b2e6-30aec73875c8.mp4

**Comment by sheikh-azharuddin** [comment]
Here is another video...check after 30 seconds


https://user-images.githubusercontent.com/58127841/164430608-af2515a8-cdc7-4c9d-88ce-fa09f2ffdc06.mp4

**Comment by csadilek** [comment]
This happened to me a few time lately just following a link, and I can reproduce on a Pixel 3a reliably by repeatedly opening the wikipedia shortcut from the home screen. 

Moving to Bugzilla/GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1766127
