### ISSUE TITLE
[a11y] The Firefox messaging banner and its close button need to be larger

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#24798]
### Steps to reproduce

1. Launch Fenix;
2. Using accessibility scanner scan the Firefox messaging banner

### Expected behaviour

There are no suggestions to make any changes.

### Actual behaviour

The following suggestions are displayed for the Firefox messaging banner
org.mozilla.fenix.nightly:id/message_button
Consider making this clickable item larger

org.mozilla.fenix.nightly:id/close
Consider making this clickable item larger

### Device name

Huawei MediaPad M3

### Android version

Android 7

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 2022-04-14

### Additional information

![Screenshot_20220414-172341](https://user-images.githubusercontent.com/50983519/163412865-c534eec0-b51c-43ff-a8b5-f2a79d8a0265.png)
![Screenshot_20220414-172408](https://user-images.githubusercontent.com/50983519/163412866-edd3b395-212a-44c4-b85e-764d35922b16.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20174)

**Comment by cpeterso** [comment]
https://mozilla-hub.atlassian.net/browse/FNXV2-20174

**Comment by Amejia481** [comment]
This will be covered as part of https://github.com/mozilla-mobile/fenix/issues/23966 as we migrating it to compose

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809822

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
