### ISSUE TITLE
Remove Event.wrapper for home screen related telemetry

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#24790]
Breakout from https://github.com/mozilla-mobile/fenix/issues/21292.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 2022-04-19 by interacting with the home screen and observing the results.
Tapping the Settings button from the 3 dot menu
{
          "timestamp": 4936,
          "category": "home_menu",
          "name": "settings_item_clicked"
        }

When the home screen is displayed
{
          "timestamp": 0,
          "category": "home_screen",
          "name": "home_screen_displayed"
        },

Tapping the Customize button from the 3 dot menu
{
          "timestamp": 14677,
          "category": "home_screen",
          "name": "customize_home_clicked"
        },

When the home screen is accessed
{
          "timestamp": 0,
          "category": "start_on_home",
          "name": "enter_home_screen"
        },

When opening the tabs tray
{
          "timestamp": 10064,
          "category": "start_on_home",
          "name": "open_tabs_tray"
        },
[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-1904)
### Device used:
- OnePlus 6T (Android 9)
