### ISSUE TITLE
View:source does not show the source code

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#24797]
### Steps to reproduce

1. Navigate to: `view-source:https://www.google.com/search?q=firefox%20view%20source&ie=utf-8&oe=utf-8&client=firefox-b-m`
2. Observe the result.

### Expected behaviour

The source code should be shown.

### Actual behaviour

The CSS code of the page is shown, different from other browsers.

### Device name

Google Pixel 3  -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 101.0a1 (2015874219 -🦎101.0a1-20220410065930🦎)

### Additional information

**Notes:**
1. Reproducible regardless of the status of ETP.
2. Reproducible on the latest build of Firefox Nightly.
3. Works as expected using Chrome, Opera.
4. Originally reported here: https://github.com/webcompat/web-bugs/issues/102379#issuecomment-1097268866
5. Screenshot attached:

Firefox:
![Screenshot_7](https://user-images.githubusercontent.com/75027050/162961494-8c9de9d0-6cc4-4787-abee-25be55f4ffa0.png)

Chrome:
![Screenshot_8](https://user-images.githubusercontent.com/75027050/162961498-8df56f4c-0090-4f60-bd35-68b82305dc18.png)

Opera:

![Screenshot_9](https://user-images.githubusercontent.com/75027050/162961506-cd81155f-081c-4cc9-a4c1-379df4a7f31e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20173)

**Comment by Mugurell** [comment]
For me loading that link seems to redirect to view-source:https://consent.google.com/ml?continue=https://www.google.com/search%3Fq%3Dfirefox%2520view%2520source%26ie%3Dutf-8%26oe%3Dutf-8%26client%3Dfirefox-b-m&gl=RO&m=1&pc=srp&uxe=none&hl=en&src=1 and this will indeed show only the css code in all browsers.

**Comment by SoftVision-LorandJanos** [comment]
I can confirm the behavior is as described above.
Tested on the latest Nightly 101.0a1 (2022-04-21).
Device used: Google Pixel 4 (Android 12).

**Comment by Mugurell** [comment]
@kbrosnan I think the issue here is with Google redirecting / serving us another page. Not sure on who knows more about this situations, whether GV or Gecko can help.
