### ISSUE TITLE
Intermittent UI test failure - cameraPermissionChoiceOnEachRequestTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#24793]
### Firebase Test Run:
Flaky, failed 1/2 tries.
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5999639850219991053/executions/bs.d614c7363c27fe1e
### Stacktrace:
`04-14 05:22:28.650: D/AndroidRuntime(2240): --------- beginning of crash
04-14 05:22:28.655: E/AndroidRuntime(2240): FATAL EXCEPTION: main
04-14 05:22:28.655: E/AndroidRuntime(2240): Process: com.android.systemui, PID: 2240
04-14 05:22:28.655: E/AndroidRuntime(2240): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:61)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at com.android.systemui.statusbar.phone.ShadowKeyDrawable.draw(ShadowKeyDrawable.java:88)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1011)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.widget.ImageView.onDraw(ImageView.java:1360)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.draw(View.java:20207)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19082)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.draw(View.java:19935)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19073)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.draw(View.java:19935)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.draw(View.java:20210)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19082)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.View.updateDisplayListIfDirty(View.java:19042)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3312)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3116)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2485)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.Choreographer.doFrame(Choreographer.java:696)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.os.Handler.handleCallback(Handler.java:873)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.os.Looper.loop(Looper.java:193)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at java.lang.reflect.Method.invoke(Native Method)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-14 05:22:28.655: E/AndroidRuntime(2240): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`
### Build: 
Debug 4/14

First failure found on https://github.com/mozilla-mobile/fenix/pull/24764

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
