### ISSUE TITLE
[Bug]: The Scan button is no longer displayed if voice search is disabled from settings

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#24817]
### Steps to reproduce

1. Enable unified search.
2. Go to search settings - disable "Show voice search".
3. Tap on URL bar.
4. Check the scan button. 

### Expected behaviour

The scan button is displayed, only the voice search option is missing.

### Actual behaviour

The scan button is not displayed, if the voice search is disabled. 

### Device name

- OnePlus 9
- Oppo Reno 6 (Android 12)

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

100.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20183)

**Comment by amocirean** [comment]
This issue is not reproducible on the latest Nightly of 24th of November 2022 (109.0a1). Tested using the following devices: Samsung Galaxy S22 Ultra (Android 13), Huawei P40 Lite (Android 10).
Closing this as fixed.
