### ISSUE TITLE
allow advanced customization similar to userchrome/userjs on desktop

### ISSUE THREAD

**Issue by brudolp** [mozilla-mobile/fenix#2481]
there is no android browser I know of with support for advanced UI/UX customization (change button/navbar size/color/style, remove buttons like "add as launcher", change animations/gestures, integrate extensions into the navbar, etc.) comparable to firefox on desktop. While I have seen screenshots of patched/modified fennec apks with a native dark homepage, it seems that currently such changes are impossible without root access (and probably not really possible with root access either).
I don't know, if this feature is already available and not enabled (meaning the UI of fenix can be modified, without the need to rebuild/reinstall the apk), if this feature or something similar is supposed to be provided via extensions or if there are (security)concerns preventing this feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11453)

**Comment by lime124** [comment]
removing ux label - this will take some more detailed design thinking around what should be customizable and how we surface that in our UI. we can take a look at the design work when it comes up as a priority for the team.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809965

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
