### ISSUE TITLE
Videos only play in the upper left corner of the player

### ISSUE THREAD

**Issue by Bubser** [mozilla-mobile/fenix#24819]
When playing any video on any website, the video only plays in the upper left corner of the player, the rest of the player being all green. It appears that the higher the resolution, the bigger the video will be, up to 1080p (the video fills the whole player). Trouble is I can't play videos in 1080p, my smartphone isn't powerful enough.
Firefox version 99.2.0
Samsung Galaxy Grand Prime
Android 5.1.1
![firefox version](https://user-images.githubusercontent.com/61021633/163585775-6aa34f01-ce1b-475e-812d-c3dfcc12aa43.png)
![video 360p](https://user-images.githubusercontent.com/61021633/163585780-53cea4cb-27d2-4aa0-a03b-ebe0d70e3f36.png)
![video 720p](https://user-images.githubusercontent.com/61021633/163585782-a05e0394-1dbb-45dc-9b7c-a0d69f5f160f.png)

**Comment by kbrosnan** [comment]
Duplicate bz-1731980

**Comment by jamienicol** [comment]
Hi @Bubser, you could please go to about:support, click "copy text to clipboard" and post the contents here? Thanks.
