### ISSUE TITLE
[Bug]: Some CSS properties such as `box-shadow` `filter`(blur) don't work on Android 5.1(API 22)

### ISSUE THREAD

**Issue by Keritial** [mozilla-mobile/fenix#24820]
### Steps to reproduce

1. Apply `box-shadow` or `filter: blur()` to a element.

### Expected behaviour

The properties should work properly.

Chrome 95 (WebView) on the same device:
![](https://user-images.githubusercontent.com/50075277/163587265-384fc2fc-7fa2-4577-a9a2-a02b417cbce8.jpg)
 

### Actual behaviour

`box-shadow` has no effects and `fliter: blur()` makes the element invisible.

The picture on the left has a `box-shadow` property, and the texts on the right has `filter: blur()`
![](https://user-images.githubusercontent.com/50075277/163586466-de804f68-f239-46a0-a6be-e68e6a846131.jpg)

with `filter: blur(0px)`
![](https://user-images.githubusercontent.com/50075277/163586771-01208854-44a1-409d-860d-5bf134150dbe.jpg)

### Device name

HUAWEI M2-A01L

### Android version

Android 5.1.1(API 22)

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 (Build #2015874795)

### Additional information

This bug only appears on my old devices (like the Android 5.1.1 one), it doesn't exist on my newer ones like Android 11 or 12
![](https://user-images.githubusercontent.com/50075277/163587848-bd799b84-e8e1-47b5-99da-eb9d8922858b.jpg)
.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1764941

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
