### ISSUE TITLE
Android 10 style media controls

### ISSUE THREAD

**Issue by xt2345** [mozilla-mobile/fenix#24826]
Ive been using the nightly fork of firefox ever since youtube vanced died but the one feature id like for firefox to have is the android 10 style media controls. On android 10 apps it has been super useful to control the video without needing to go back into the app everytime. Im wondering if something like that can be added to firefox.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20188)

**Comment by sheikh-azharuddin** [comment]
The advance media controls are missing in firefox
They are not planning to fix it

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@xt2345, what media-controls do you refer to? Are you able to provide any depiction of them?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813745

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by rokejulianlockhart** [comment]
@xt2345, I ask because https://bugzilla.mozilla.org/show_bug.cgi?id=1813745#c1.
