### ISSUE TITLE
Recent synced tab does not appear after signing in

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#24823]
Steps to reproduce:
- Make sure there isn't a synced tab on home screen
- Sign in to sync

Expected behavior:
The recent synced tab placeholders appear, and then a synced tab is shown.

Actual behavior:
A recent synced tab does not appear until the home screen is reloaded again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20187)

**Comment by cpeterso** [comment]
Jira issue: https://mozilla-hub.atlassian.net/browse/FNXV2-20187
