### ISSUE TITLE
Any devs can fork a browser without the scrollable menu, im stuck using samsung browser until otherwise

### ISSUE THREAD

**Issue by MrNxbxdii** [mozilla-mobile/fenix#24828]
Can i pay anybody on here to make me a fork without the scrollable menu because you akwardly have the settings last which is utter nonsense, every release firefox devs pick up more google tendancies, always fixing unbroke features new isnt always better

**Comment by sheikh-azharuddin** [comment]
Long list of 3 dot menu...why cant they have small height horizontal menu like samsung , edge or even their own firefox lite

**Comment by kbrosnan** [comment]
Not a Fenix issue.
