### ISSUE TITLE
Telemetry for address autofill

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24857]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20209)

**Comment by mcarare** [comment]
Needs https://github.com/mozilla-mobile/android-components/issues/12132.

**Comment by delia-pop** [comment]
Verified as fixed in the latest Nightly from 06/29 with Google Pixel 6 (Android 12). These are the events generated: 
![Events_Autofill_Addresses](https://user-images.githubusercontent.com/89388888/176694671-5a26346f-0e2d-4bab-9ddc-92300d997f68.JPG)
