### ISSUE TITLE
Update a saved address information

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24855]
This issue is to display an existing address in the address editor and allow users to update any address field and save it.

<img width="207" alt="Screen Shot 2022-04-18 at 12 29 11 PM" src="https://user-images.githubusercontent.com/1190888/163840000-b2566c68-4dd7-4817-93cf-c0910c94121d.png">

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 102 from 05/25.
