### ISSUE TITLE
[Bug]: Status bar text is unreadable when opening link within another app

### ISSUE THREAD

**Issue by Remu-rin** [mozilla-mobile/fenix#24858]
### Steps to reproduce

1. Have an app with `In-App Browser` feature, e.g. Telegram or Gmail. It opens link by default browser.
2. Open link in app when Firefox is default browser
3. Look at status bar
4. Repeat with Chrome as default browser (app should be reopened after change)

### Expected behaviour

Status bar text should be readable, like in Chrome.
Btw, it's readable in Firefox Focus, and in Fenix with private mode enabled (purple toolbar).
![chr dark Screenshot_2022-04-18-21-32-52-494_com android chrome](https://user-images.githubusercontent.com/28995228/163841196-4fef141b-dc65-4f3b-a97d-1fbca6ffd7e2.jpg)
![chr light Screenshot_2022-04-18-21-02-58-398_com android chrome](https://user-images.githubusercontent.com/28995228/163841269-11ab409a-73fe-4a2e-af51-03c40cf2d9fe.jpg)
![ff private Screenshot_2022-04-18-21-38-25-689_org mozilla firefox](https://user-images.githubusercontent.com/28995228/163841288-874f5fa7-4b9b-4f5a-8570-62a9cc13ae6f.jpg)

### Actual behaviour

Status bar text is unreadable in both themes (Telegram/external app). Firefox theme and position of toolbar doesn't matter, as well as Android color theme.
(The dark one is a little readable when viewing screenshot on PC, but it is not readable on device)
![ff dark Screenshot_2022-04-18-21-28-32-578_org mozilla firefox](https://user-images.githubusercontent.com/28995228/163841472-93add5f6-af61-4c35-a27f-e2fa86019522.jpg)
![ff light Screenshot_2022-04-18-21-00-50-236_org mozilla firefox](https://user-images.githubusercontent.com/28995228/163841485-38ba6a0b-fe05-4a05-b565-ad57adbf7e5e.jpg)

### Android version

Android 9, MIUI 11

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20210)

**Comment by marcel263** [comment]
Related  #22988

**Comment by SoftVision-LorandJanos** [comment]
Hi @Remu-rin! Thank you for your report! Nicely detailed.
I did manage to reproduce the issue you described, however as mentioned above, the issue is already covered on the still opened #22988 ticket. Please leave extra details in a comment there, maybe about your device, the independence of the origin, the address bar position and theme. Thank you!
Device used: Xioami Mi11 Lite (Android 11).
Closing the ticket as duplicate.

**Comment by Remu-rin** [comment]
Seems fixed in 108 beta. Probably by:
https://github.com/mozilla-mobile/focus-android/issues/7860
https://github.com/mozilla-mobile/android-components/pull/12955
