### ISSUE TITLE
[Bug]: DoorDash (https://www.doordash.com/) Renders Add to Cart button Below Viewport 

### ISSUE THREAD

**Issue by xcjs** [mozilla-mobile/fenix#24851]
### Steps to reproduce

1. Open new tab
2. Navigate to https://www.doordash.com/
3. Locate a restaurant you want to order from
4. Click on a food item with enough customization options that you can scroll up and down
5. Scroll up/down a few times
6. The Add to cart button on the bottom right falls below the viewport and cannot be moved back up by scrolling.

### Expected behaviour

The button should remain visible at the bottom of the viewport at all times.

### Actual behaviour

The button hides below the bottom of the viewport with only a single row of pixels visible.

### Device name

Google Pixel 6 Pro, Google Pixel 4 XL, Google Pixel 2 XL

### Android version

Android 8-12

### Firefox release type

Firefox

### Firefox version

99.2.0

### Additional information

I've included screenshots with private information removed, except for my sandwich preference.

![image](https://user-images.githubusercontent.com/5085205/163829383-6ece1ae5-eea4-452c-a024-a36edc0ff98b.png)
![image](https://user-images.githubusercontent.com/5085205/163829394-6bcbc736-b1dc-4eaf-a478-3230ce6d4eb8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20203)

**Comment by xcjs** [comment]
An additional note: this may be related to #8768

**Comment by amedyne** [comment]
@xcjs are you able to scroll up to make the button visible?

**Comment by xcjs** [comment]
@amedyne No, as mentioned in the issue, I cannot make the button reappear by scrolling.

Each screenshot I included shows a fully scrolled up and fully scrolled down overflow respectively after the button is pushed past the viewport.

I've confirmed this issue does not occur for me in Chromium based browsers, though I realize this could be an issue with the way Doordash creates the overflow and Chromium may work due to an engine-specific feature or bug, though I haven't investigated that possibility.

**Comment by amedyne** [comment]
Thank you for the clarification @xcjs . We will investigate further on our end.

**Comment by SoftVision-LorandJanos** [comment]
Hi @xcjs ! Thanks for your report!
I can confirm the issue is reproducible on the latest Nightly 101.0a1 (2022-04-20)
I can also confirm that on Chrome it works as expected.
Device used: Oppo Reno 6 (Android 12).

**Comment by marcel263** [comment]
This happens all the time with similar web shops and their check-out systems. It happens with e.g. AliExpress. The immediate fix is to disable the auto-hide of the address bar.

**Comment by xcjs** [comment]
> This happens all the time with similar web shops and their check-out systems. It happens with e.g. AliExpress. The immediate fix is to disable the auto-hide of the address bar.

@marcel263  Right - I initially commented on this on #8768 which reported issues with the disappearing navigation bar. Despite examples being provided and multiple people confirming the issue, it was closed.

I'm surprised more people haven't reported issues with this, but my assumption is that they're just moving on to other browsers anyway.

I want Firefox to succeed and get issues like this fixed.

**Comment by xcjs** [comment]
> This happens all the time with similar web shops and their check-out systems. It happens with e.g. AliExpress. The immediate fix is to disable the auto-hide of the address bar.

@marcel263 I just tried your suggestion out and discovered another toolbar-related bug that I've reported as #24989

**Comment by xcjs** [comment]
Forgive me as I lost the page I saw this on, but I located a page where the header at the top of the page appeared below the URL bar, and there was no way to scroll the page down far enough to uncover it. There appear to be a lot of issues with calculating and adjusting the proper viewport size, both at the top and bottom of the viewport.

**Comment by xcjs** [comment]
I can confirm this issue still occurs.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813172

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
