### ISSUE TITLE
Whitelist WebSites from Automatic Feature - Open Links in PrivateTab

### ISSUE THREAD

**Issue by Cebrain** [mozilla-mobile/fenix#24862]
### What is the user problem or growth opportunity you want to see solved?
I really like the "Open in Private Tab" feature, but i have one big problem. 
I have webpages i use fairly often with my accounts and wanna use them with shortcuts from my HomeScreen.

So i want to create shortcuts on the HomeScreen and open the webpage but the big problem is now the page will be open in a PrivateWindow and i have to relogin or switch to the normal Firefox Tabs. So the shortcut is more or less useless.

### How do you know that this problem exists today? Why is this important?
Occurs every time

### Who will benefit from it?
Everyone who uses the "Open in private Tab" feature and uses accounts in the normal Tabs

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20212)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807535

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
