### ISSUE TITLE
[Bug]: Search engines aren't displayed when tapping the "Search engine" button from the awesome bar

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24866]
### Prerequisites
"Show search engines" should be disabled in Search Settings

### Steps to reproduce
1. Tap the search bar
2. Tap the "Search engine" button from the awesome bar

### Expected behaviour
The list of search engines should be displayed

<details>

<summary> 🎬  Video from 100.0.0 Beta 6 (dropdown)</summary>

https://user-images.githubusercontent.com/51314259/163981733-a39c68df-649d-4671-a54d-75b486c21c9d.mp4

</details>

### Actual behaviour
Nothing is displayed

<details>

<summary> 🎬  Video from Nightly 101.0a1 (dropdown)</summary>

https://user-images.githubusercontent.com/51314259/163981604-30fd62ae-aa94-43d1-a92c-db9499787ec0.mp4

</details>

### Device name
Google Pixel 3a (Android 11)

### Firefox version

Firefox Nightly 101.0a1 4/19

**Comment by Mugurell** [comment]
Seems like a regression from https://github.com/mozilla-mobile/android-components/pull/12000

**Comment by Mugurell** [comment]
Should be fixed in today's Nightly.

**Comment by SoftVision-LorandJanos** [comment]
This issue is not reproducible on the latest Nightly 101.0a1 (2022-04-19T17:47:17:277588) build.
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.
