### ISSUE TITLE
[Bug]: Search suggestions aren't displayed

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24867]
### Prerequisites
"Show search engines" should be enabled in Search Settings

### Steps to reproduce
1. Search for a term E.g. "Cat"
2. Check the search suggestions

### Alternative steps to reproduce
1. Tap the search bar
2. Select one of the featured search engines
3. Search for a term E.g. "Cat"
4. Check the search suggestions

### Expected behaviour
Search suggestions should be displayed

<details>

<summary> 🎬  Video from 100.0.0 Beta 6 (dropdown)</summary>

https://user-images.githubusercontent.com/51314259/163984872-02423294-ba1d-4492-9c0f-5f2a176d493b.mp4

</details>

### Actual behaviour
The search engines list remains displayed

<details>

<summary> 🎬  Video from Nightly 101.0a1 (dropdown)</summary>

https://user-images.githubusercontent.com/51314259/163984787-806a9c2a-8707-4def-a01f-1f3fd1fe6f73.mp4

</details>

### Device name
Google Pixel 3a (Android 11)

### Firefox version
Firefox Nightly 101.0a1 4/19

**Comment by Mugurell** [comment]
Seems like a regression of https://github.com/mozilla-mobile/android-components/pull/12000.

**Comment by AaronMT** [comment]
I noticed this in the failing search results UI tests. It types 'mozilla' and expects to see a 'mozilla firefox' result, but just yields 'mozilla'.

**Comment by Mugurell** [comment]
Should be fixed in today's Nightly.

**Comment by SoftVision-LorandJanos** [comment]
This issue is not reproducible on the latest Nightly 101.0a1 (2022-04-19T17:47:17:277588) build.
Device used: Xiaomi Mi11 Lite (Android 11)
Closing the ticket as fixed.
