### ISSUE TITLE
[Bug]: Virtual Keyboard causes jQuery UI Autocomplete widget search dropdown to display 2 times

### ISSUE THREAD

**Issue by Cylon6** [mozilla-mobile/fenix#24874]
### Steps to reproduce

1. Open a page that is using the jquery autocomplete widget on FireFox 99 on Android (example www.hotelslash.com "Where do you want to stay" field or the demo site for jquery ui autocomplete https://jqueryui.com/autocomplete/)
2. Enter text using the virtual keyboard in android and select a result.  Popup goes away and immediately comes back again.

This appears to be a behavior change in FF around the virtual keyboard.  Not positive it belongs here but entering just in case as this is a very popular software widget and the behavior has changed only under android and FF 99.

### Expected behaviour

Popup search results should only display one time.

### Actual behaviour

Popup displays 2 times before and selection must be made again.

### Device name

Any Android device (used Google Pixel 3a to confirm)

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

99.2.0

### Device logs

n/a

### Additional information

I am submitting here as the jquery ui autocomplete widget is used in many websites.  A issue was also submitted on the jquery ui project as well.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1765421

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
Is this a new regression in Firefox 99? I can reproduce in versions 99-101, but I didn't test 98.
