### ISSUE TITLE
Document Telemetry process

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2488]
Currently it's really difficult to understand how to add new telemetry with the new process as it requires adding boilerplate code in many files. It's also confusing due to how messy metrics.kt is right now. We should clean this up and add some documentation in a wiki.

**Comment by sblatz** [comment]
As part of this, let's work on making the process **better**. It shouldn't be so error prone :)

**Comment by liuche** [comment]
Also, consider what things that the Glean team can do to make multiple data collection destinations easier. I understand that it is an open source generic library for telemetry collection, but every single mobile app made by Mozilla is going to have multiple data destinations, so it's worth having a conversation about, even if that's not what Glean was "originally" designed to do.

**Comment by mdboom** [comment]
Definitely!  It would be good to have a conversation about whether we could move this event abstraction into a different layer, such as Glean itself.
