### ISSUE TITLE
Close other tabs

### ISSUE THREAD

**Issue by XXDRD** [mozilla-mobile/fenix#24885]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Option to close all the tabs other than the one currently opened.

### How do you know that this problem exists today? Why is this important?
Problem - Someimes It have to manually close all the tabs.
It is important for earsier tab management.

### Who will benefit from it?
Everyone

**Comment by kbrosnan** [comment]
dupe https://github.com/mozilla-mobile/fenix/issues/19889
