### ISSUE TITLE
[Bug]: Password Manager not showing all logins some times

### ISSUE THREAD

**Issue by akshatcoder-hash** [mozilla-mobile/fenix#24883]
### Steps to reproduce

1. Have a site open with multiple saved logins.
2. Go to the 'Enter Password' field.

### Expected behaviour

Firefox should display all the possible logins for the site

### Actual behaviour

Firefox shows only the last login.

### Device name

Redmi Note 5 Pro

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

99.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20225)

**Comment by akshatcoder-hash** [comment]
Hey @badboy , I would love to work on this issue. Could you please assign it to me?

**Comment by badboy** [comment]
> Hey @badboy , I would love to work on this issue. Could you please assign it to me?

I'm not a Fenix maintainer. I leave this up to the team to triage. You can get in contact with them [on Matrix](https://github.com/mozilla-mobile/fenix#getting-involved) though. But of course you can get started on the issue without being assigned already.

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Nightly 2022-20-04 but was unable to. @akshatcoder-hash Could you specify the website where you encountered this issue?
### Device used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by akshatcoder-hash** [comment]
I found it on Google accounts login page

**Comment by kbrosnan** [comment]
Would you try our nightly version @akshatcoder-hash? We have made some fixes for autofilling in other apps. https://github.com/mozilla-mobile/fenix/wiki#download

**Comment by delia-pop** [comment]
Hello, @akshatcoder-hash. 
I was not able to reproduce this issue on the latest Nightly from 05/19 or GVE with Google Pixel 6 (Android 12). 
With Firefox Nightly set as default autofill app, all the saved logins for the websites were displayed for both Email/Password fields (google.com included).
Is this still an issue for you on the latest Nightly build?

**Comment by akshatcoder-hash** [comment]
Hey @delia-pop .
I found the same issue on an internet login page. I also have the screenshot of the issue I am facing. Can I share it here?

**Comment by delia-pop** [comment]
@akshatcoder-hash , Sure, please share a screenshot or a video recording of the issue. 
Also, please let us know the Firefox version and a website you last reproduced the issue on. Thank you!

**Comment by akshatcoder-hash** [comment]
The issue is fixed on Nightly build!
