### ISSUE TITLE
[Bug]: The option enableHighAccuracy is broken for navigator.geolocation.watchPosition

### ISSUE THREAD

**Issue by Eccenux** [mozilla-mobile/fenix#24901]
### Steps to reproduce

1.  Use enableHighAccuracy in a browser app to display location on a map.
2.  Walk around with FF open on Android phone.
3.  Observe location -> you are up to 1000 m (!) away from your actual location.
4.  Switch to a different gps app (e.g. Ingress). Switch to Firefox.
5.  Notice the location becomes accurate.

### Expected behaviour

Firefox should give me accuracy around 5-10 meters when I'm outside and in good weather.

### Actual behaviour

So it seems like Firefox fails to ask for high accuracy GPS. In the current state of things there is no point in showing my location on a city map. Note that I used the same code before and it worked fine. I used to have better accuracy indoors (under a roof) in old Firefox.

### Device name

Samsung s10e

### Android version

Android 12, One UI 4.1

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1

### Additional information

Example code:

```
SelfLocation.prototype.setupWatch = function() {
    var me = this;
    function success(location) {
        me.receiver(location);
    }
    function error(err) {
        console.warn('location error(' + err.code + '): ' + err.message);
    }
    // see: https://developer.mozilla.org/en-US/docs/Web/API/PositionOptions
    var options = {
        enableHighAccuracy: true,    // Ingress will probably enfoce it anyway
        //timeout: 5000,
        maximumAge: 0                // we want real position, no cache
    };
    this._watchId = navigator.geolocation.watchPosition(success, error, options);
};
```

See also:  
https://github.com/Eccenux/iitc-plugin-self-location  
You can install main iitc plugin from here:  
https://iitc.app/build/release/total-conversion-build.user.js  
And then open:  
https://intel.ingress.com/intel

Oh, you would have to use FF Nightly builds to test this in IITC because you don't allow Tampermonkey on a standard FF mobile ☹...

**Comment by Eccenux** [comment]
Here is a log with accuracy (declared) from some test walk 5 years ago. This is beside buildings, but in the open. In old Firefox (pre-Fenix). You can see accuracy is about 5 meters and time resolution is quite high too (once per second). Which gives a nice trace on a map (when user enables it).

```javascript
var points = [
 {"dt":"2017-11-19 17:27:34","ll":["54.522214570","18.520907940"],"accuracy":"6.07","speed":"1.430","timestamp":1511108854000}
,{"dt":"2017-11-19 17:27:35","ll":["54.522225990","18.520922860"],"accuracy":"6.07","speed":"1.550","timestamp":1511108855000}
,{"dt":"2017-11-19 17:27:36","ll":["54.522237440","18.520938040"],"accuracy":"6.07","speed":"1.680","timestamp":1511108856000}
,{"dt":"2017-11-19 17:27:37","ll":["54.522250630","18.520952400"],"accuracy":"6.07","speed":"1.820","timestamp":1511108857000}
,{"dt":"2017-11-19 17:27:38","ll":["54.522262150","18.520967230"],"accuracy":"6.07","speed":"1.680","timestamp":1511108858000}
,{"dt":"2017-11-19 17:27:39","ll":["54.522271230","18.520985070"],"accuracy":"6.07","speed":"1.850","timestamp":1511108859000}
,{"dt":"2017-11-19 17:27:40","ll":["54.522278870","18.521002970"],"accuracy":"6.07","speed":"1.450","timestamp":1511108860000}
,{"dt":"2017-11-19 17:27:41","ll":["54.522287590","18.521019720"],"accuracy":"6.07","speed":"1.590","timestamp":1511108861000}
,{"dt":"2017-11-19 17:27:42","ll":["54.522297260","18.521037260"],"accuracy":"6.07","speed":"1.730","timestamp":1511108862000}
,{"dt":"2017-11-19 17:27:43","ll":["54.522310290","18.521054020"],"accuracy":"6.07","speed":"1.730","timestamp":1511108863000}
,{"dt":"2017-11-19 17:27:44","ll":["54.522323260","18.521069160"],"accuracy":"4.55","speed":"1.690","timestamp":1511108864000}
,{"dt":"2017-11-19 17:27:45","ll":["54.522334250","18.521082080"],"accuracy":"4.55","speed":"1.340","timestamp":1511108865000}
,{"dt":"2017-11-19 17:27:46","ll":["54.522344890","18.521092890"],"accuracy":"4.55","speed":"1.170","timestamp":1511108866000}
,{"dt":"2017-11-19 17:27:47","ll":["54.522354800","18.521101390"],"accuracy":"4.55","speed":"1.350","timestamp":1511108867000}
,{"dt":"2017-11-19 17:27:48","ll":["54.522365120","18.521111040"],"accuracy":"4.55","speed":"1.320","timestamp":1511108868000}
,{"dt":"2017-11-19 17:27:49","ll":["54.522376610","18.521122290"],"accuracy":"4.55","speed":"1.750","timestamp":1511108869000}
]
```

**Comment by Eccenux** [comment]
![](https://user-images.githubusercontent.com/1045235/164418262-4cb9b0b1-e195-4f3e-9798-1a9a432bdf88.png)

Here are some measurements in a corner (6 stories building around me). Again this is in old Firefox.  
\`\`\`js  
,{"dt":"2017-11-19 17:28:44","ll":\["54.522620260","18.521838830"\],"accuracy":"6.07","speed":"0.580","timestamp":1511108924000}  
,{"dt":"2017-11-19 17:28:45","ll":\["54.522607520","18.521840980"\],"accuracy":"9.10","speed":"1.270","timestamp":1511108925000}  
,{"dt":"2017-11-19 17:28:46","ll":\["54.522593130","18.521846630"\],"accuracy":"10.62","speed":"1.270","timestamp":1511108926000}  
,{"dt":"2017-11-19 17:28:47","ll":\["54.522578250","18.521860300"\],"accuracy":"9.10","speed":"1.270","timestamp":1511108927000}  
,{"dt":"2017-11-19 17:28:48","ll":\["54.522565630","18.521876020"\],"accuracy":"10.62","speed":"1.270","timestamp":1511108928000}  
,{"dt":"2017-11-19 17:28:49","ll":\["54.522556500","18.521888390"\],"accuracy":"10.62","speed":"0.540","timestamp":1511108929000}  
,{"dt":"2017-11-19 17:28:50","ll":\["54.522550350","18.521896310"\],"accuracy":"12.14","speed":"0.540","timestamp":1511108930000}  
,{"dt":"2017-11-19 17:28:51","ll":\["54.522547330","18.521920070"\],"accuracy":"12.14","speed":"1.240","timestamp":1511108931000}  
,{"dt":"2017-11-19 17:28:52","ll":\["54.522536540","18.521939720"\],"accuracy":"12.14","speed":"1.170","timestamp":1511108932000}  
\`\`\`

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1765835

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
