### ISSUE TITLE
Update metrics.yaml owners

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#24913]
There are a number of metrics that have owners who have since left the team/company, so we need to update the owners to someone more current

[example](https://github.com/mozilla-mobile/fenix/blob/ccb3d33e8b791640cfa36e3d64a3c376626d5070/app/metrics.yaml#L6037)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20244)

**Comment by eliserichards** [comment]
@rocketsroger fyi

**Comment by kbrosnan** [comment]
Looks that applies to most of the emails in that file. Work with Amedyne to replace Elise, Mike C. and Grisha's emails with current info.
