### ISSUE TITLE
Add a State / Province dropdown in Address Editor

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24918]
Replace the existing state input text field with a dropdown that displays a dropdown with the appropriate state / province values depending on the selected country. This should be done after https://github.com/mozilla-mobile/fenix/issues/24917

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20250)

**Comment by MatthewTighe** [comment]
I think there may be a discrepancy in data expected by A-S and what's delivered by desktop. The [sql schema](https://www.google.com/search?client=firefox-b-1-d&q=ISO+3166-2) for an address has a comment suggesting that the ISO 3166-2 codes be used. However, the [address reference data](https://searchfox.org/mozilla-central/source/toolkit/components/formautofill/addressmetadata/addressReferences.js) defines the subregion names as the `sub_names` field. I've been unable to find any other applied transformations so far.

Subregions, unlike countries, do [not appear to be normalized](https://searchfox.org/mozilla-central/rev/c6620104602decf1af7c6a9f78692426db6a5da2/toolkit/components/formautofill/FormAutofillStorageBase.jsm#1554). Additionally, when the [full list of subregions](https://searchfox.org/mozilla-central/rev/c6620104602decf1af7c6a9f78692426db6a5da2/toolkit/components/formautofill/FormAutofillUtils.jsm#654) are built, there does not appear to be any formatting or localization. This is in contrast to the countries, which [are localized](https://searchfox.org/mozilla-central/rev/c6620104602decf1af7c6a9f78692426db6a5da2/toolkit/components/mozintl/mozIntl.jsm#934).
