### ISSUE TITLE
Page load is slower when using enhanced tracking protection

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#24927]
https://support.mozilla.org/en-US/questions/1374523

> When enhanced tracking protection is on (android devices) it is very slow loading pages. With it off is quicker.

---

@acreskeyMoz Would it be low effort to measure the performance difference using our page load test frameworks?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20257)

**Comment by acreskeyMoz** [comment]
Yes, I would want some data on the observation that tracking protection slows down page load.

A couple of years back I compared standard tracking protection (which I believe is now called Enhanced) vs Strict tracking protection.
Strict tracking protection was measurably faster, presumably because so many resources were dropped.
[Tracking Protection Performance in Fenix](https://docs.google.com/document/d/16WV7D_lEqa9BGPIAzKI3qCQ8mBKZiJcC8T5hv_JE3kg/edit#)

I think we could try to compare tracking and no tracking protection via try pushes in Geckoview example. Using live sites, because the http recordings may not include all of the resources.

But I think it would be better to capture profiles on a device where tracking protection was introducing slow down.

**Comment by plwt** [comment]
To save the user walking through the profile process (and since I can replicate it), please find attached two profiles:

[Firefox 2022-04-24 21.58 profile with ETP.json.gz](https://github.com/mozilla-mobile/fenix/files/8550563/Firefox.2022-04-24.21.58.profile.with.ETP.json.gz)
[Firefox 2022-04-24 22.45 profile no ETP.json.gz](https://github.com/mozilla-mobile/fenix/files/8550564/Firefox.2022-04-24.22.45.profile.no.ETP.json.gz)

**Comment by acreskeyMoz** [comment]
> 
Thank you for capturing these @plwt 
I've named those profiles shared them as links below.
In this case with ETP, the main document loads in about 7200ms. 
Without ETP, the load takes about 5700ms.

If this reproduces across multiple sites then it's clearly a serious problem!

@mcomella Do you have any capacity to investigate this further?

With ETP
https://share.firefox.dev/3Mv9wqs

No ETP
https://share.firefox.dev/3KiZ3gd

**Comment by kbrosnan** [comment]
Do we have shimming for common trackers to avoid stalling out JS calls on Android? @csadilek

**Comment by csadilek** [comment]
@kbrosnan We don't have anything specifically for Android, afaik. We'll bring this up and talk this through in the next performance triage.

**Comment by csadilek** [comment]
(I tried it on my Pixel 3a and don't see a difference, but this needs more testing.)

**Comment by kbrosnan** [comment]
bz-1637329 might have some info.

**Comment by mcomella** [comment]
Initial investigation:
- DOMContentFlushed takes the same time in both profiles but later code seems to take longer in the ETP profile (like `PresShell::DoFlushPendingNotifications Layout` and `WebGLContext::Create`). Since these methods take longer, despite running on the main thread in presumably similar orders, **I wonder if the CPU gets overloaded sometime after `DOMContentFlushed`**
- I put these profiles [into the comparison view](https://share.firefox.dev/38tf9Xw) and noticed that `ScriptCompileOffThread` only occurs in the profile with tracking protection. The `Bailout` markers (I don't know what they mean) occur after `DOMContentFlushed` in the ETP profile while they occur during it in the non-ETP profile. **I wonder if the code in the ETP profile causes JS to do more work, possibly changing the scheduling and delaying things.**

**Comment by mcomella** [comment]
Triage: we think the platform performance should continue to investigate. I'll take an action item to find an owner.

**Comment by mcomella** [comment]
In the first 0.5s, [the version with ETP triggers a reflow](https://share.firefox.dev/3xZdunn) while the version without does not. I wonder if that causes the lengthened jank markers in the ETP version and later causes scheduling issues that cause the changes I mention above.

**Comment by mcomella** [comment]
I was not able to reproduce on my Moto G5 or Pixel 2.

**Comment by mcomella** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1767103 so I can get help from the platform performance team in looking into this issue. If we determine it is definitely a platform perf issue, we should close this GitHub ticket.

**Comment by plwt** [comment]
It felt visible on my Moto G30.  Happy to go back to the user to establish what device they have.

**Comment by mcomella** [comment]
I'll be OOO so I won't be able to continue investigating this for a bit. Some thoughts from Element:

> mstange
mcomella: that's a tricky one. The lack of URLs in these profile make it hard. I agree that the reflow you found is suspicious, but I couldn't figure out what causes it or why it takes so long, maybe something to do with uncached fonts. One thing I noticed is that the slow profile has a few more woff2 requests in the network chart. And WebGL initialization takes longer in it. And I think the fast profile might have been recorded with a warm network cache - the "solid bars" in the network chart often indicate that the response came from the cache and doesn't have subphase timing information.

**Comment by mcomella** [comment]
@plwt Would it be possible to capture another profile with "Include resource URLs and paths" selected when uploading the profile? We found it difficult to analyze the last profile due to the obfuscation.

**Comment by plwt** [comment]
With apologies for the delay, new profiles attached produced using the latest version of Release (101.1.1):

[Firefox 2022-06-09 10.52 profile with ETP.json.gz](https://github.com/mozilla-mobile/fenix/files/8869259/Firefox.2022-06-09.10.52.profile.with.ETP.json.gz)
[Firefox 2022-06-09 10.55 profile no ETP.json.gz](https://github.com/mozilla-mobile/fenix/files/8869260/Firefox.2022-06-09.10.55.profile.no.ETP.json.gz)

**Comment by MarcLeclair** [comment]
without etp: https://share.firefox.dev/3MYPvIG
w/ etp: https://share.firefox.dev/3HpkZXq

**Comment by mcomella** [comment]
In the w/ ETP version, we notice that "After DNS request" takes a long time for some network requests. For example:
![image](https://user-images.githubusercontent.com/759372/173923986-78321333-7299-435d-b94c-8635ac0927da.png)

Maybe this is related.

**Comment by mcomella** [comment]
Triage: let's post the profiles to Joy of Profiling channel and see what they think.

**Comment by mcomella** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1776714

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
