### ISSUE TITLE
Ablity to rename downloads

### ISSUE THREAD

**Issue by RaSan147** [mozilla-mobile/fenix#24923]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Since your opponent browsers support Download file rename (before downloading) It would be great if you allow us to use that feature.

### How do you know that this problem exists today? Why is this important?
Many download files don't provide content-disposition header. So the file name gets scrambled or gets a random name from somewhere in the page. So there should be a option to fix such problem.

### Who will benefit from it?
Everyone ✌️

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20254)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812786

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
