### ISSUE TITLE
[Bug]: Inprogress Downloads not showing in Downloads History

### ISSUE THREAD

**Issue by shubhamg13** [mozilla-mobile/fenix#24926]
### Steps to reproduce

1. Start a download
2. While download is in-progress, Open Download History.

### Expected behaviour

In-Progress Download should be shown in Download History.

### Actual behaviour

In-Progress downloads are not shown.

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.2.0

**Comment by delia-pop** [comment]
Hello,

Thank you for your report! 
Please also note that a feature request for the behavior your ticket describes was already opened under ticket https://github.com/mozilla-mobile/fenix/issues/23118. Here you can follow up on the discussions over this topic. 
I will close this ticket for now.
