### ISSUE TITLE
Display the proper label and description for an Address item

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24931]
> I will file a follow to display the proper label and description. I think we will want to investigate how Desktop formats this.

_Originally posted by @gabrielluong in https://github.com/mozilla-mobile/fenix/pull/24928#discussion_r856524889_

We want to investigate how Desktop formats their Name and Address description and ensure we are following the same format in our address list.

**Comment by gabrielluong** [comment]
Please also link to the Desktop code that does the formatting.

**Comment by MatthewTighe** [comment]
Core of the desktop code can be found [here](https://searchfox.org/mozilla-central/source/toolkit/components/formautofill/FormAutofillUtils.jsm#323)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 102 from 05/25.
