### ISSUE TITLE
[Bug]: Firefox mobile lost inactive tabs and Firefox focus lost all tabs on 2 application switch (99+ tabs)

### ISSUE THREAD

**Issue by lunajelly** [mozilla-mobile/fenix#24937]
### Steps to reproduce

(I am unclear on how to reproduce exactly; as we are uncertain what happened and I'm a bit too exhausted to replicate 100%, but I gather this)

1. infinity/probably 99+ tabs on firefox.  Infinity tabs on chrome.  Inactive apps:  Game (lily's garden), evernote, chrome, phone)
2. ~100 tabs opened on firefox focus.  
3. Phone screen turned off for a bit and turned on again.
4. phone call taken.
5. swapped foreground to text messaging app (qksms) and evernote app.  
6. Swap back to firefox focus- all the tabs have vanished.  
7. Swap back to firefox mobile - all the tabs except the most recent tab is gone.  one of hte recent tab groups managed to be saved in "collections"

No idea if there was some kind of background process. or the resource use was too much or what happened.  I don't know how to look at background process off the top.  If I should be putting this in firefox focus instead of firefox mobile or editing anythingl et me know.

My installation of firefox mobile has ublock origin and privacy badger.

This hasn't happened to me in years (I've had firefox mobile for like 5-6 years now) so I think it's a weird edge case 

### Expected behaviour

Tabs should be retained on firefox mobile and firefox focus on swap of foreground app.  On crash, rest of tabs should be saved in a collection or something. 

### Actual behaviour

All tabs in firefox mobile are gone except the most recent one without a trace.  Some of the tabs were saved in a collection, but the rest are gone without a trace.

All tabs in firefox focus are missing as well.

### Device name

Samsung Galaxy S10e

### Android version

Android 

### Firefox release type

Firefox

### Firefox version

99.2.0

### Additional information

No crash log is listed. The last one is from 6 days ago.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20264)

**Comment by kbrosnan** [comment]
It is unfortunate that you experienced this.

Firefox Focus is not designed to retain your tabs. Restarting your phone, updating Focus or Focus crashing are all events that could cause Focus to discard your tabs. Bookmarking important URLs in Focus or Firefox is one way to retain important information.

For Firefox browser it should have retained your tabs if you have it set to do so. You should make sure that tabs are never set to be discarded https://support.mozilla.org/en-US/kb/auto-close-open-tabs-firefox-android. There is another feature that will collapse unused tabs into an inactive tabs section https://support.mozilla.org/en-US/kb/manage-tabs-firefox-android#w_inactive-tabs you may want to turn that off. 

If this is a repeatable problem then we should be able to debug the problem. If it is not repeatable then it is unlikely there is anything we can do to fix this.
