### ISSUE TITLE
Hide the keyboard when navigating away from the address editor

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24935]
Found a small issue. When navigating back to the address list from the "Add address" screen, the keyboard stays open.

_Originally posted by @MozillaNoah in https://github.com/mozilla-mobile/fenix/issues/24928#issuecomment-1106955692_

**Comment by mcarare** [comment]
Reopened for QA.

**Comment by gabrielluong** [comment]
Gonna close this and remove the qa:needed. We'll open a separate QA ticket when the address editor is ready.
