### ISSUE TITLE
[Bug]: Improve padlock information text visuals

### ISSUE THREAD

**Issue by Bardock88** [mozilla-mobile/fenix#24948]
### Steps to reproduce

1. open Firefox Nightly
2. enter some website
3. click the security padlock
4. note the security padlock information.

### Expected behaviour

Have proper spacing of padlock information text boxes

### Actual behaviour

Note the padlock text box touching the info box separator line.

![Screenshot_20220424-174022_1](https://user-images.githubusercontent.com/102046116/164996906-174f4df2-bc15-492a-bfb5-6d61a2308c60.png)

### Device name

Asus ZB602KL

### Android version

Android 8.1

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1

**Comment by cadeyrn** [comment]
Duplicate of #24666.

**Comment by Bardock88** [comment]
> Duplicate of #24666.
Thanks for mentioning this information, I didn't know you had already commented on this error. But it was really worth it for the information. 🙋🏻‍♂️
