### ISSUE TITLE
Menu UI simplification for improved accessibility

### ISSUE THREAD

**Issue by basings** [mozilla-mobile/fenix#24941]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I want an easier way to access menu items.

### What is the user problem or growth opportunity you want to see solved?

The current implementation hides important menu items and makes all items less accessible. 

### Who will benefit from it?

Every user that actually uses the menu more than once a day.

### Suggestion

Remove the labels from the entries and put them together into a row for easier access like in the version shown below.

![Screenshot_20220422_151302](https://user-images.githubusercontent.com/92867705/164889701-0a54fd83-b8ca-4610-a3d4-4fdab431e75b.jpg)

**Comment by cadeyrn** [comment]
Removing the labels from important menu items does not "improve accessibility" but the opposite…

**Comment by sheikh-azharuddin** [comment]
A picture is worth a thousand words

**Comment by marcel263** [comment]
The narrow spacing increases chances of involuntary pressing. Now you refresh the page instead of sharing it.


+1 for allowing user to rearrange menu item,-1 for your suggestion

**Comment by sheikh-azharuddin** [comment]
> The narrow spacing increases chances of involuntary pressing. Now you refresh the page instead of sharing it.
> 
> +1 for allowing user to rearrange menu item,-1 for your suggestion

Then why not extend the 3 dot menu width to full screen? This will give sufficient space for each item like Microsoft edge or Samsung browser
![Screenshot_20220425-190159203 (1)](https://user-images.githubusercontent.com/58127841/165099519-9a9a0df0-cbbe-4581-b929-5fb37cf00010.jpg)

**Comment by kbrosnan** [comment]
This is a specific design. We don't have immediate plans to redesign this menu. I'll let the UX team know about this suggestion. For now I am going to close this out.
