### ISSUE TITLE
[Bug] browser crashes often

### ISSUE THREAD

**Issue by 01deNchiK01vLadiMiRoViCh01** [mozilla-mobile/fenix#24943]
Здравствуйте .!у меня все время сварачивается вылетает падает браузер,уже было много,обновлений а проблема так и не Решина,вы можете в конце концов исправить раньше ведь хорошо работал,уменьшите его в развмере,телефон Android,Redmi go,модель M1903C3GG,версия 8.1.0.!!!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20266)

**Comment by kbrosnan** [comment]
Please get crash ID URLs. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information
