### ISSUE TITLE
Add support for reordering search engines

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2495]
### Why/User Benefit/User Problem
I want my most important search engines at the start of the list for quicker access.

### Acceptance Criteria (how do I know when I’m done?)
The order of search engines in the settings reflects the order of engines during the actual search (currently, the settings list orders them alphabetically, but when actually searching Google seems always at the top of the list).
I can then reorder the engines by dragging them around.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11463)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809968

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
