### ISSUE TITLE
Intermittent UI test failure - < SettingsAddonsTest.installAddonTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24958]
### Stacktrace:
04-25 10:39:04.528: D/AndroidRuntime(8695): --------- beginning of crash
04-25 10:39:04.529: E/AndroidRuntime(8695): FATAL EXCEPTION: main
04-25 10:39:04.529: E/AndroidRuntime(8695): Process: org.mozilla.fenix.debug, PID: 8695
04-25 10:39:04.529: E/AndroidRuntime(8695): java.lang.SecurityException: ConnectivityService: Neither user 10092 nor current process has android.permission.ACCESS_NETWORK_STATE.
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.os.Parcel.createException(Parcel.java:1942)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.os.Parcel.readException(Parcel.java:1910)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.os.Parcel.readException(Parcel.java:1860)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1207)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:883)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at org.mozilla.gecko.util.NetworkUtils.getConnectionType(NetworkUtils.java:109)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at org.mozilla.gecko.GeckoNetworkManager.updateNetworkStateAndConnectionType(GeckoNetworkManager.java:303)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at org.mozilla.gecko.GeckoNetworkManager.performActionsForStateEvent(GeckoNetworkManager.java:258)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at org.mozilla.gecko.GeckoNetworkManager.handleManagerEvent(GeckoNetworkManager.java:172)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at org.mozilla.gecko.GeckoNetworkManager.enableNotifications(GeckoNetworkManager.java:123)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at org.mozilla.gecko.GeckoAppShell.lambda$enableNetworkNotifications$0(GeckoAppShell.java:1194)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at org.mozilla.gecko.GeckoAppShell$$ExternalSyntheticLambda0.run(Unknown Source:0)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.os.Handler.handleCallback(Handler.java:873)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.os.Looper.loop(Looper.java:193)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at java.lang.reflect.Method.invoke(Native Method)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-25 10:39:04.529: E/AndroidRuntime(8695): Caused by: android.os.RemoteException: Remote stack trace:
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.app.ContextImpl.enforce(ContextImpl.java:1812)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1840)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at com.android.server.ConnectivityService.enforceAccessPermission(ConnectivityService.java:1661)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at com.android.server.ConnectivityService.getActiveNetworkInfo(ConnectivityService.java:1170)
04-25 10:39:04.529: E/AndroidRuntime(8695): 	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:85)
04-25 10:39:04.530: E/ExceptionHandler(8695): Uncaught exception handled: 
04-25 10:39:04.530: E/ExceptionHandler(8695): java.lang.SecurityException: ConnectivityService: Neither user 10092 nor current process has android.permission.ACCESS_NETWORK_STATE.
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.os.Parcel.createException(Parcel.java:1942)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.os.Parcel.readException(Parcel.java:1910)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.os.Parcel.readException(Parcel.java:1860)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1207)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:883)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at org.mozilla.gecko.util.NetworkUtils.getConnectionType(NetworkUtils.java:109)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at org.mozilla.gecko.GeckoNetworkManager.updateNetworkStateAndConnectionType(GeckoNetworkManager.java:303)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at org.mozilla.gecko.GeckoNetworkManager.performActionsForStateEvent(GeckoNetworkManager.java:258)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at org.mozilla.gecko.GeckoNetworkManager.handleManagerEvent(GeckoNetworkManager.java:172)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at org.mozilla.gecko.GeckoNetworkManager.enableNotifications(GeckoNetworkManager.java:123)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at org.mozilla.gecko.GeckoAppShell.lambda$enableNetworkNotifications$0(GeckoAppShell.java:1194)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at org.mozilla.gecko.GeckoAppShell$$ExternalSyntheticLambda0.run(Unknown Source:0)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.os.Handler.handleCallback(Handler.java:873)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.os.Looper.loop(Looper.java:193)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at java.lang.reflect.Method.invoke(Native Method)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-25 10:39:04.530: E/ExceptionHandler(8695): Caused by: android.os.RemoteException: Remote stack trace:
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.app.ContextImpl.enforce(ContextImpl.java:1812)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1840)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at com.android.server.ConnectivityService.enforceAccessPermission(ConnectivityService.java:1661)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at com.android.server.ConnectivityService.getActiveNetworkInfo(ConnectivityService.java:1170)
04-25 10:39:04.530: E/ExceptionHandler(8695): 	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:85)
04-25 10:39:04.531: W/system_server(2070): Long monitor contention with owner android.bg (2084) at int com.android.server.am.ActivityManagerService.broadcastIntent(android.app.IApplicationThread, android.content.Intent, java.lang.String, android.content.IIntentReceiver, int, java.lang.String, android.os.Bundle, java.lang.String[], int, android.os.Bundle, boolean, boolean, int)(ActivityManagerService.java:21935) waiters=4 in android.content.Intent com.android.server.am.ActivityManagerService.registerReceiver(android.app.IApplicationThread, java.lang.String, android.content.IIntentReceiver, android.content.IntentFilter, java.lang.String, int, int) for 284ms
04-25 10:39:04.531: W/system_server(2070): Long monitor contention with owner android.bg (2084) at int com.android.server.am.ActivityManagerService.broadcastIntent(android.app.IApplicationThread, android.content.Intent, java.lang.String, android.content.IIntentReceiver, int, java.lang.String, android.os.Bundle, java.lang.String[], int, android.os.Bundle, boolean, boolean, int)(ActivityManagerService.java:21935) waiters=5 in void com.android.server.am.ActivityManagerService.attachApplication(android.app.IApplicationThread, long) for 282ms
04-25 10:39:04.533: W/ActivityManager(2070): Permission Denial: getIntentSender() from pid=8695, uid=10092, (need uid=-1) is not allowed to send as package org.mozilla.fenix.debug
04-25 10:39:04.533: W/system_server(2070): Long monitor contention with owner android.bg (2084) at int com.android.server.am.ActivityManagerService.broadcastIntent(android.app.IApplicationThread, android.content.Intent, java.lang.String, android.content.IIntentReceiver, int, java.lang.String, android.os.Bundle, java.lang.String[], int, android.os.Bundle, boolean, boolean, int)(ActivityManagerService.java:21935) waiters=7 in void com.android.server.am.ActivityManagerService$MainHandler.handleMessage(android.os.Message) for 254ms
04-25 10:39:04.533: I/ActivityManager(2070): Force stopping org.mozilla.fenix.debug appid=10092 user=-1: deletePackageX
04-25 10:39:04.533: I/ActivityManager(2070): Killing 8695:org.mozilla.fenix.debug/u0a92 (adj 100): stop org.mozilla.fenix.debug
04-25 10:39:04.534: W/ActivityManager(2070): Scheduling restart of crashed service org.mozilla.fenix.debug/androidx.work.impl.background.systemjob.SystemJobService in 1000ms
04-25 10:39:04.535: W/libprocessgroup(2070): kill(-8695, 9) failed: No such process
04-25 10:39:04.537: D/AutofillUI(2070): destroySaveUiUiThread(): already destroyed
04-25 10:39:04.537: D/AutofillManagerServiceImpl(2070): Reset component for user 0 (null)
04-25 10:39:04.537: D/FieldClassificationStrategy(2070): reset(): service is not bound. Do nothing.
04-25 10:39:04.538: I/ActivityManager(2070): Killing 8739:org.mozilla.fenix.debug:tab15/u0a92 (adj 0): stop org.mozilla.fenix.debug
04-25 10:39:04.539: I/ActivityManager(2070):   Force stopping service ServiceRecord{ceb619e u0 org.mozilla.fenix.debug/androidx.work.impl.background.systemjob.SystemJobService}
04-25 10:39:04.539: W/system_server(2070): Long monitor contention with owner android.bg (2084) at int com.android.server.am.ActivityManagerService.broadcastIntent(android.app.IApplicationThread, android.content.Intent, java.lang.String, android.content.IIntentReceiver, int, java.lang.String, android.os.Bundle, java.lang.String[], int, android.os.Bundle, boolean, boolean, int)(ActivityManagerService.java:21935) waiters=8 in int com.android.server.am.ActivityManagerService.bindService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, int) for 245ms
04-25 10:39:04.540: W/Looper(2070): Slow dispatch took 317ms main h=com.android.server.job.JobSchedulerService$JobHandler c=null m=4
04-25 10:39:04.541: I/Finsky(2939): [2] ProfileStateService.onCreate(5): creating profileStateService
04-25 10:39:04.551: I/keystore(1963): clear_uid 10092

### Build: 4/25 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20273)

**Comment by Mugurell** [comment]
Also seen in https://github.com/mozilla-mobile/fenix/pull/25051

**Comment by sv-ohorvath** [comment]
This crash hasn't shown up in more than a month, here or on https://github.com/mozilla-mobile/fenix/issues/24959. We can close this
