### ISSUE TITLE
open svg file with firefox

### ISSUE THREAD

**Issue by lilydjwg** [mozilla-mobile/fenix#24960]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Firefox could be used to open an svg file obtained in another application.

### How do you know that this problem exists today? Why is this important?

I receive an svg file, possibly with some javascript logic. The best application to open such a file is a browser, but firefox does not show up in the application list that could be used to open it.

### Who will benefit from it?

People who receive svg files on their phone, e.g. systemd-analyse plots, flamegraph plots.

**Comment by kbrosnan** [comment]
Duplicate #7546

**Comment by kbrosnan** [comment]
Viewing local content has different security properties than web content. We would need to do a significant audit to enable viewing of local files.
