### ISSUE TITLE
Add a "Save and fill addresses" preference toggle in Autofill settings

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24968]
This issue is about wiring up the "Save and fill addresses" preference toggle in the "Autofill" screen

When "Save and fill addresses" preference is toggled, we should update the engine setting for whether or not the address autofill enable setting is enabled.

This depends on https://github.com/mozilla-mobile/android-components/issues/12062 and should follow closely with https://github.com/mozilla-mobile/fenix/issues/18263

<img width="203" alt="Screen Shot 2022-04-26 at 12 03 46 PM" src="https://user-images.githubusercontent.com/1190888/165343647-c8f75a75-277d-4de8-b747-1d6270b83059.png">

[Figma designs](https://www.figma.com/file/cSKRUEvfJSzNBv2Mp65Pdv/Mobile-CC-Autofill?node-id=1356%3A36515 )

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20285)

**Comment by delia-pop** [comment]
Verified as fixed on latest Nightly 102 from 05/25.
![Addresses_Toggle_24968](https://user-images.githubusercontent.com/89388888/170248169-92a71265-cad7-4fc3-b487-b5e56ca7a866.JPG)
