### ISSUE TITLE
[Bug] Link/image title attribute isn't shown in context menu

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2496]
## Steps to reproduce
1. Visit https://bugzilla.mozilla.org/show_bug.cgi?id=1550073#c1 and long press the bug link in comment 1.
1. Visit https://xkcd.com/2149/ and long press the image.

### Expected behavior
The context menu shows the content of the title attribute, as in Fennec.

### Actual behavior
The context menu shows the URL.

### Device information
* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: 1.0.9020, Build #11341807

**Comment by kbrosnan** [comment]
Dupe #580
