### ISSUE TITLE
Display an address autofill prompt

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24969]
This issue is to integrate the "Select address" prompt when an address is encountered that can be autofilled. This will depend on AC work to wire everything up for this to be displayed. 

This depends on https://github.com/mozilla-mobile/android-components/issues/12061. This should follow closely with https://github.com/mozilla-mobile/fenix/issues/18287

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20287)

**Comment by Alexandru2909** [comment]
For QA: issue can't be tested for now because the [onAddressSelect callback is not triggered](https://bugzilla.mozilla.org/show_bug.cgi?id=1769014) when the user focuses on a form.

**Comment by Alexandru2909** [comment]
Bugzilla ticket was marked as resolved.

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 104 from 07/20 with Google Pixel 6 (Android 12). The "Select addresses" is displayed for the US/CA region (browser.search.region="US,CA") and the autofill works as expected. 
![Screenshot (Jul 20, 2022 11 09 25 AM)](https://user-images.githubusercontent.com/89388888/179934369-c4812419-3159-4f80-9493-ac2f459d04a1.png)
