### ISSUE TITLE
[Bug]: extension "save to bookmark os" doesn't work

### ISSUE THREAD

**Issue by 424344** [mozilla-mobile/fenix#24961]
### Steps to reproduce

1. on nightly install the "save to bookmark os" extension (you'll need to create a custom extension collection). link to extension: https://addons.mozilla.org/en-US/firefox/addon/bookmarkos/
2. load a page and click on the extension icon

### Expected behaviour

the extension should show the ui for adding a new bookmark in the BookmarkOS system

### Actual behaviour

the extension opens an empty page

### Device name

samsung galaxay a50

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

101

### Additional information

the extension work correctly on firefox desktop and also on kiwi browser on android, so I expect to work on fenix too.

**Comment by kbrosnan** [comment]
The bookmark API is not supported currently. You can follow bz-1625231 for updates.

**Comment by 424344** [comment]
Hello @kbrosnan, thanks for your fast response.
I believe that this extension doesn't use bookmarks api, so I think this bug should be reopened.
BookmarkOS.com is a web site that stores online the users' bookmarks, it has no need to use the firefox bookmarks api.
The extension just opens a popup that shows a web page from the bookmarkos.com web site, that allows the user to choose a folder (this is an example from firefox on desktop, but loaded in the sidebar to simulate a mobile screen).
![add-new-bookmark](https://user-images.githubusercontent.com/26486758/165467750-e2d0df56-968b-413a-8a08-71f0fade82d0.jpg)

**Comment by 424344** [comment]
I also managed to get the url loaded for the page in my previous comment, using firefox's remote debugging functionality.
this page is correctly loaded in the popup extension in firefox desktop and on kiwi browser.
but on fenix it just shows an empty page.
[log.txt](https://github.com/mozilla-mobile/fenix/files/8570048/log.txt)

**Comment by 424344** [comment]
@kbrosnan so any news on reopening this issue?
thank you.

**Comment by kbrosnan** [comment]
We don't keep bugs open for individual extension support. If there is specific data about the API that is not working we can make sure that there is a Geckoview bug.

**Comment by kbrosnan** [comment]
I don't know. You should read the add-on debugging information that addons.mozilla.org links to.
