### ISSUE TITLE
PWA Confusion 

### ISSUE THREAD

**Issue by PeterKW** [mozilla-mobile/fenix#24963]
Don't seem to be able to install facebook.com as an app / pwa?

There's only an add to desktop link to open in Firefox nightly application. Is there a way to force this option to appear?

Thank you very much

![Screenshot_20220426-153326.png](https://user-images.githubusercontent.com/13779157/165324670-7ee7bd6b-6e41-4075-ac95-61cd89ae39ee.png)

![Screenshot_20220426-153358.png](https://user-images.githubusercontent.com/13779157/165324725-6a6b7bf0-47f8-40c3-85e1-56e721002dbe.png)

**Comment by kbrosnan** [comment]
Facebook dynamically builds the site you view. They do not supply a PWA manifest to Firefox. This is a Facebook bug.
