### ISSUE TITLE
Split full name in the Address Editor into First, Middle, and Last name

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#24971]
The AS Address data type currently expects first, middle, and last name instead of a single full name field. Rather than parsing the full name into its first, middle and last name, I have requested UX to provide designs that would align with desktop.

<img width="636" alt="Screen Shot 2022-04-26 at 4 07 40 PM" src="https://user-images.githubusercontent.com/1190888/165383410-547cfdce-1f82-4ce8-95ab-190e50c88cdb.png">

This is pending designs.

**Comment by mcarare** [comment]
@gabrielluong Does the A-S entity map exactly to the [one](https://github.com/mozilla-mobile/android-components/blob/1d8addca6cddb8c5b990df440b69b771ede1f66a/components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt#L286) in AC? In A-S I see this [address](https://github.com/mozilla/application-services/blob/b4db42558752d6b17ff219e1bda4a81ba94a56bf/components/autofill/src/autofill.udl#L61) 

I do not see a city field, for example, and different naming for name parts ("first name" versus  "given name") might be confusing when coding.

**Comment by gabrielluong** [comment]
> @gabrielluong Does the A-S entity map exactly to the [one](https://github.com/mozilla-mobile/android-components/blob/1d8addca6cddb8c5b990df440b69b771ede1f66a/components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt#L286) in AC? In A-S I see this [address](https://github.com/mozilla/application-services/blob/b4db42558752d6b17ff219e1bda4a81ba94a56bf/components/autofill/src/autofill.udl#L61)
> 
> I do not see a city field, for example, and different naming for name parts ("first name" versus "given name") might be confusing when coding.

Yes the `Address` in AC maps directly to the AS `autofill.udl`. The city might be `addressLevel2` based on the description and desktop https://searchfox.org/mozilla-central/source/toolkit/components/formautofill/FormAutofillUtils.jsm#1083. Regarding the naming vs AS, I think this is more of a UX consideration and we should just follow what makes sense from a UX content strategy.

@Alexandru2909 I am not expecting this to be ready to implement since we don't have designs for this.

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 102 from 05/25.
