### ISSUE TITLE
Bookmark keywords

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2497]
### Why/User Benefit/User Problem
On my desktop, I have a few custom searches defined via bookmark keywords, and through sync those are available in Fennec and work there, too (and can actually even be edited purely within Fennec, too).

### Acceptance Criteria (how do I know when I’m done?)
Entering a bookmark keyword in the address bar opens the bookmark.
Entering a bookmark keyword followed by one or more search terms starts the corresponding search if the bookmark URL contains a %s/%S placeholder. %s URL-encodes the search query, %S doesn't.
Bookmark keywords can be reviewed and edited as part of bookmark editing.

**Comment by mheubusch** [comment]
Assigning to Nicole to address as part of any updates to bookmark folders or when this issue gets added to a sprint.

**Comment by lime124** [comment]
we are in the process of collecting bookmark related issues for consideration in one design effort - removing ux label

**Comment by julian-alarcon** [comment]
I will like to have this, I think that this is not too complex.

**Comment by buttercookie42** [comment]
Also requested in https://bugzilla.mozilla.org/show_bug.cgi?id=1619084.

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/issues/12099 and #12100
