### ISSUE TITLE
Tracking UI Tests disabled with frequent ANR [API 30]

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#24978]
See: https://github.com/mozilla-mobile/fenix/issues/24047
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1764605

The following tests were disabled to land API30 work as they were frequently hitting ANRs in the Client on Firebase.

* mediaSystemNotificationInPrivateModeTest
* launchLinksInPrivateToggleOffStateDoesntChangeTest
* testStrictVisitDisableExceptionToggle
* homeThreeDotMenuItemsTest
* testSignInPageWithNoNetworkConnection

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20293)

**Comment by AndiAJ** [comment]
`verifyContextMixedVariations` got disabled today in #25277

**Comment by sv-ohorvath** [comment]
[videoPlaybackSystemNotificationTest](https://github.com/mozilla-mobile/fenix/issues/15754#) hit this crash too.

**Comment by AndiAJ** [comment]
`verifyAboutFirefoxPreview` got disabled today in #25694

**Comment by AndiAJ** [comment]
`testDownloadPrompt` got disabled today in #26266

**Comment by AndiAJ** [comment]
`mainMenuOpenInAppTest`got disabled today in #26317

**Comment by AndiAJ** [comment]
Re-enabled in #27058
`testDownloadPrompt` 
`testSignInPageWithNoNetworkConnection` 
`launchLinksInPrivateToggleOffStateDoesntChangeTest`

**Comment by AndiAJ** [comment]
`verifyAboutFirefoxPreview` re-enabled in #27134
`videoPlaybackSystemNotificationTest` re-enabled in #27060
`mediaSystemNotificationInPrivateModeTest` re-enabled in #27060
`mainMenuOpenInAppTest` re-enabled in #27060
`verifyContextMixedVariations` re-enabled in #27060
`homeThreeDotMenuItemsTest` re-enabled in #27060
`audioPlaybackSystemNotificationTest` re-enabled in #27060
testStrictVisitDisableExceptionToggle re-enabled in #27060
