### ISSUE TITLE
Why I can't install a pwa app like Twitter lite?

### ISSUE THREAD

**Issue by 1human** [mozilla-mobile/fenix#24990]
Android 12 miui 13
Firefox nightly 101.0a1
It was fine a few days ago and I think this is a new bug

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20298)

**Comment by 1human** [comment]
![IMG_20220428_090521](https://user-images.githubusercontent.com/18576031/165656024-ea9e3d5b-e5ed-422a-90e1-c0d4ae9bcca8.jpg)
![IMG_20220428_090546](https://user-images.githubusercontent.com/18576031/165656033-471467af-23ce-426d-acc2-262780fc9316.jpg)
Add to home screen will create an ordinary shortcut.

**Comment by rokejulianlockhart** [comment]
@1human, you need to monitor the issues that you create, else they are marked as stale and closed. Better luck next time, or create a new issue.
