### ISSUE TITLE
WebGL Canvas rendering issue (Mali-G76)

### ISSUE THREAD

**Issue by Lanius-collaris** [mozilla-mobile/fenix#24992]
### Steps to reproduce

1. Open page https://regl-project.github.io/regl/www/gallery/lighting.js.html

### Expected behaviour

Render properly.

### Actual behaviour

Not render properly

### Device name

Huawei Nova 5 pro

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 (Build #2015876715), 405f406f1+

### Additional information

![Screenshot_20220415_124644_org mozilla fenix_edit_559168636041756](https://user-images.githubusercontent.com/55432068/165678245-803714aa-9b0a-41a8-a2ce-c2c3328150a3.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20300)

**Comment by delia-pop** [comment]
Hi @Lanius-collaris, thank you for your report! 

I was able to reproduce this issue on one device.

Reproducible with:
- Google Pixel 4 (Android 12) - with latest Nightly 101.0a1 from 04/28., Beta and RC builds + Chrome.

Not reproducible with:
- Motorola Moto G30 (Android 11).
- Samsung Galaxy Note10 (Android 11).
- Xiaomi Redmi Note 8T (Android 9).
![Rendering](https://user-images.githubusercontent.com/89388888/165839999-be42b209-1693-447d-8af2-a1288e3af735.jpg)

**Comment by Lanius-collaris** [comment]
Reproducible with:

- Huawei MatePad Pro 5G MRX-AN19 - with 101.0a1 (Build #2015876715), 405f406+
- Xiaomi Redmi K50 - with 101.0a1 (Build #2015876715), 405f406+

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802856

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
