### ISSUE TITLE
[Bug]: "back" button/gesture with an open `<dialog>` does a navigation

### ISSUE THREAD

**Issue by simonflk** [mozilla-mobile/fenix#25006]
### Steps to reproduce

1. Have a tab open
2. Go to https://zippy-pineapple-notebook.glitch.me/
3. Press "Open dialog"
4. Press device "back" button (or use "back" gesture)

### Expected behaviour

The dialog should close

### Actual behaviour

The browser navigates back in the history stack (e.g. `window.history.go(-1)`)

### Device name

Google Pixel 5

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20312)

**Comment by simonflk** [comment]
The reason I think this is a bug is the contrasting behaviour of the following elements on Android vs Desktop Firefox:

1. window.alert()
2. <select>
3. input[type=color]
4. input[type=date]
5. input[type=time]
6. etc

When any of these interactive elements are open, the behaviour of "Back" on Android matches the behaviour of pressing the "Escape" key on desktop.

My position is that <dialog> should be treated in the same way as all of these other interactive elements.
With a keyboard, if I press "Escape", the <dialog> will close.
But using Android "back" button is does a navigation.

Is it your position that <dialog> is not like those other elements?

There are efforts to make it easier to develop native-like apps on the web platform. This bug (IMO), creates an expectation gap in users that developers are left to fill themselves without really having the right tools to do so. As a developer, my only option is to cobble together a hack that uses the history stack to convert a `window.back()` into a `dialog.close()`. Even this is not as easy as it sounds and it is not easily ported between frontend frameworks.

For transparency, the current behaviour in Firefox is consistent with Chromium browsers on Android, and Safari on iOS. I will be filing issues with them also

**Comment by SoftVision-LorandJanos** [comment]
Hi @simonflk! Thanks for your report!
I managed to reproduce your issue using the latest Nightly 101.0a1 (2022-04-29) build.
Device used: Google Pixel 4 (Android 12).

**Comment by simonflk** [comment]
Update: Chromium team [are working](https://bugs.chromium.org/p/chromium/issues/detail?id=1319915) on this

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Nightly 109.0a1 (2022-11-24) build.
Device used: Oppo Find X5 (Android 12).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812822

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
