### ISSUE TITLE
Renew telemetry for Firefox 102

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#25001]
There are [telemetry probes](https://github.com/mozilla-mobile/fenix/blob/808ce5a564a8c652b47f55f4e3e591f99ac809a0/app/metrics.yaml#L2452) which expire with version 102 which starts to get used next Monday (May 2).

**Comment by mcarare** [comment]
I think it is handled in this PR: https://github.com/mozilla-mobile/fenix/pull/24982
