### ISSUE TITLE
[Bug]: Firefox Nightly crashes when deleting a history group by tapping the trashcan icon

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25003]
### Steps to reproduce

1. Perform a search in the URL bar.
2. Long press to open a few results and visit them to create a search group.
3. Go to History.
4. Access the history group created for the search term from step 1.
5. Tap the trashcan icon in the right upper corner.
6. Select "DELETE" on the prompt.
7. Observe that the application crashes.

### Expected behaviour

The application should remain stable at all times.

### Actual behaviour

The application crashes after deleting the history group using the trashcan icon.
Note that the crash does not occur when deleting the search group from the History screen by tapping the "X" button.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly 101 from 04/28

### Device logs

Logcat: [Delete_HistoryGroup_Crash_Pixel6.txt](https://github.com/mozilla-mobile/fenix/files/8581817/Delete_HistoryGroup_Crash_Pixel6.txt)

Crash report: [40ea6504-da99-4.txt](https://github.com/mozilla-mobile/fenix/files/8581833/40ea6504-da99-4.txt)

### Additional information

The issue occurs on multiple devices. Could not be reproduced on the latest RC or Beta builds.

https://user-images.githubusercontent.com/89388888/165731937-d65d632b-fe3d-447e-95e1-ba8184be49a8.mp4

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed with the latest Nightly 101.0a1 (2022-05-01T17:11:31.722002) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
