### ISSUE TITLE
[Bug]: firefox is crashing sometime when closing tabs

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#25008]
### Steps to reproduce

Sometime when closing tab firefox is crashing..the crash logs does not say much native crash

This is mostly happening when suddenly closing the tab while the page is loading or closing the last tab

### Expected behaviour

Firefox should not crash

### Actual behaviour

Firefox crashing

### Device name

asus rog 3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

7b5ee1a2-1303-48cd-80b4-73d1cb8398e2
<native crash>
----
<native crash>

### Additional information

![Screenshot_20220428-184751212](https://user-images.githubusercontent.com/58127841/165761014-c69348a0-7cfe-41c4-9b08-915d6317aad3.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20314)

**Comment by sheikh-azharuddin** [comment]
https://crash-stats.mozilla.org/report/index/cd488519-8674-4036-bfc9-eb5940220509

**Comment by maxreuben** [comment]
Face the same issue on Firefox nightly version 103.0a1 on Android 12 on Pixel 6. It also happens when you push the app to the background, return and close the tab using the tab number button beside the (bottom-placed) address bar

**Comment by amocirean** [comment]
Hello, thank you for submitting the issue.
It looks like the issue was discussed in this thread as well. #25102 

This issue will be closed.
