### ISSUE TITLE
Cannot quickly cancel page load

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2500]
## Steps to reproduce
1. Mistakenly click a link.
1. Try to cancel the load as fast as possible, ideally _before_ the browser navigates away from the current page.

### Expected behavior
1. A cancel button appears somewhere easily accessible, probably in the address bar.

### Actual behavior
1. Nothing.

### Device information
* Android device:  Moto G4 Play
* Fenix version: 1.0.1920 (#11341807)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11468)

**Comment by AaronMT** [comment]
Is the bottom right menu button and stop button not sufficient?

**Comment by buttercookie42** [comment]
It's not as easily discoverable, and more importantly, more cumbersome to reach.

The thing is that if you react quickly, you can stop the page load *before* Gecko navigates away from the current page so you don't have to go back afterwards, which can be a hassle, especially if the bfcache doesn't kick in (loading time, lost state on more complex pages, etc.). For that however every second counts, hence the cancel button should be *directly* accessible.

**Comment by brampitoyo** [comment]
@buttercookie42 I suppose we can add a stop button on the URL bar, but we will need to think about all the dependencies that this button will cause. For example: animate in/out, what happens to the URL that’s being cut off, etc.

I will size this issue for now.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809981

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
