### ISSUE TITLE
[Bug] Domain highlighting and alignment

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2501]
## Steps to reproduce
Visit something with a subdomain, like https://bugzilla.mozilla.org.

### Expected behavior
The base domain (eTLD+1) is highlighted (respectively the rest of the URL is displayed muted), as in Fennec or Desktop Firefox.
The base domain is right-aligned with the right edge of the URL bar, as in Fennec.

### Actual behavior
Nothing. All the URL is displayed in the same font style, and long subdomains can push the base domain off the screen.

Compare also [bug 1271998](https://bugzilla.mozilla.org/show_bug.cgi?id=1271998).

### Device information
* Android device: Moto G4 Play, Android 6.0.1
* Fenix version: 1.0.9020, Build #11341807

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11469)

**Comment by bifleming** [comment]
@vesta changed to feature request

**Comment by mimi89999** [comment]
Hello. Is there any progress on this?

**Comment by Madis0** [comment]
It occurs on paths as well, not just subdomains. 

And I wouldn't really consider it a _feature request_ as it exists on every major desktop and mobile browser, including the previous Fennec.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812898

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
