### ISSUE TITLE
FNX3-16371 ⁃ [Bug] (regression) Reader mode button is not displayed

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2502]
## Steps to reproduce
1. Go to any wikipedia page or news article.
1. Open the Quick Action Bar.

### Expected behavior
The reader mode button is available.

### Actual behavior
The reader mode button is not displayed.

### Device information
* Android device: 
  * OnePlus 5T (Android 9)
  * Nexus 5 (Android 6.0.1)
  * Sony Xperia Z5 Premium (Android 6.0.1)
* Fenix version: 5/15
* The option was available in the build from 5/14

**Comment by csadilek** [comment]
Regression is introduced by this Fenix commit: https://github.com/mozilla-mobile/fenix/commit/c5e5ef4b258751dc444370ff9a032692f4b5851f

**Comment by ekager** [comment]
CC @boek

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.1.1920 (#11360657), with OnePlus 5T (Android 9), Nexus 5 (Android 6.0.1), Sony Xperia Z5 Premium (Android 7.1.1).
