### ISSUE TITLE
Hope you guys can add support on translucent statusbar....

### ISSUE THREAD

**Issue by 1human** [mozilla-mobile/fenix#25026]
Many websites have their own styles. 
In order to have an immersive experience when browsing web pages, I hope to add an translucent status bar support on Android phones.
Thanks!!!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20322)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@cadeyrn, I agree.

**Comment by sheikh-azharuddin** [comment]
> In my opinion translucent user interface elements are very annoying. I would be more in favour of supporting the theme color property instead, like Chrome. That would be #1178.

Interestingly this is already present in geckoview (earlier it used to color the status bar too)but not sure why they are not adding to the main browser...

![Screenshot_20220502-130542952 (1)](https://user-images.githubusercontent.com/58127841/166200391-a332a9c1-3bc0-45c1-9b25-510b42ef0bd3.jpg)

**Comment by amocirean** [comment]
Hello @1human  , thank you for submitting the issue
Based on the following situation, the correct label (Feature Request) will be assigned.

**Comment by csadilek** [comment]
Duping to https://bugzilla.mozilla.org/show_bug.cgi?id=1807087.
