### ISSUE TITLE
[Bug]: In Android an <input type="time"> tag with seconds resolution does not allow the user access to the seconds field.

### ISSUE THREAD

**Issue by Bagunceiro** [mozilla-mobile/fenix#25020]
### Steps to reproduce

In Android, access a web site containing the following tag:

`<input type="time" step="1">`

### Expected behaviour

There should be some way to modify the seconds field

### Actual behaviour

Seconds field appears in the render, but as selection causes the the picker to pop-up and there is no seconds field in either form of the picker it cannot be modified.

### Device name

Moto G31

### Android version

11

### Firefox release type

Firefox

### Firefox version

99.2.0

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20319)

**Comment by makotokato** [comment]
GV adds [stepValue](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.PromptDelegate.DateTimePrompt.html#stepValue), so android-component has to look and parse this value to fix this issue.

**Comment by amocirean** [comment]
Hello @Bagunceiro , thanks for submitting your issue.

> `step` attribute is unimplemented yet in GeckoView and Fenix (https://bugzilla.mozilla.org/show_bug.cgi?id=1499635). I will fix it soon on GeckoView side. (Then Fenix/a-c should look it).

Based on the comment above, this ticket will be closed, as this behaviour seems to be as intended at the moment.

**Comment by Dunexus** [comment]
GV bug is fixed, it is now up to Fenix/AC to handle it.
Shoudn't this bug be reopened or an issue opened on AC side to track this ?

**Comment by makotokato** [comment]
@Dunexus
I filed this in a-c.

**Comment by Amejia481** [comment]
Let's keep this open until address https://github.com/mozilla-mobile/android-components/issues/12151
