### ISSUE TITLE
Add an option to automatically submit crash reports

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25021]
### What is the user problem or growth opportunity you want to see solved?

The Fenix team would like to receive crash reports for more crashes affecting users.

### How do you know that this problem exists today? Why is this important?

Fenix's crash reporter requires the user to manually submit each crash report. Users might just close the tab or browser without submitting the crash report.

For parent or background process crashes, the user doesn't see a crash reporter dialog. The user has to open the system notification tray and tap the "Sorry. Firefox had a problem and crashed" notification before they are asked if they'd like to submit a crash report.

### Who will benefit from it?

Users will benefit because the Fenix team will be better able to prioritize and debug the top crashes affecting users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20320)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Please allow synchronisation of configuration of this ability.

**Comment by cpeterso** [comment]
> Please allow synchronisation of configuration of this ability so that my automation of submission is autonatically configured.

Synchronized using Firefox Sync? So your crash setting is the same on different Android devices and on desktop Firefox?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812770

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
