### ISSUE TITLE
Add Pocket sponsored stories

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25025]
Tracking Jira issue - https://mozilla-hub.atlassian.net/browse/FNXV2-19877

Needs https://github.com/mozilla-mobile/android-components/pull/12070

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20321)

**Comment by gabrielluong** [comment]
@Mugurell should this be closed or set for qa-needed?

**Comment by Mugurell** [comment]
Since this is hidden in debug I'll set `qa:not-needed` for now.
