### ISSUE TITLE
[Bug]: Firefox prevents device from turning the screen off after YouTube video finished

### ISSUE THREAD

**Issue by phd** [mozilla-mobile/fenix#25041]
### Steps to reproduce

1. open YouTube website
2. play a video in full-screen mode
3. let the video finish
4. wait, do not touch the device

### Expected behaviour

After video finishes (and the device goes idle), the device should be let to turn the screen off after some time.

### Actual behaviour

The device is still prevented from turning the screen off even after YouTube video finishes.
This **may damage the device** causing screen burn-in.

### Device name

Samsung Galaxy A52s

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.2.0
102.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20330)

**Comment by amocirean** [comment]
Hello @phd , thank you for submitting the issue.
I was able to reproduce it on the latest RC, Nightly or Beta.


Device Used: Huawei P40 Lite
Android Version: 10

**Comment by plwt** [comment]
User feedback - https://support.mozilla.org/en-US/questions/1373974

**Comment by phd** [comment]
Still happening in Firefox 102.1.1 (Build #2015887771)

**Comment by indurs** [comment]
@Mugurell, can I work on this issue?

**Comment by Mugurell** [comment]
> @Mugurell, can I work on this issue?

Sure, thank you!
I think what we can try is exiting immersive and fullscreen mode when the media state becomes stopped this also removing `FLAG_KEEP_SCREEN_ON`.
But this becomes problematic in case of YouTube - Autoplay.
So maybe as a workaround we can delay exiting fullscreen and immersive mode after a timeout started when media is stopped.
I've opened https://github.com/mozilla-mobile/android-components/issues/12544 for the needed changes on AC.

**Comment by indurs** [comment]
Thank you  for the suggestions, @Mugurell .

**Comment by Mugurell** [comment]
This should be fixed after https://github.com/mozilla-mobile/fenix/issues/26236 and https://github.com/mozilla-mobile/android-components/pull/12560.

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue was fixed by https://github.com/mozilla-mobile/fenix/issues/26236. I tested the issue on Firefox Nightly 105.0a1 2022-08-08 on several video sites such as https://www.youtube.com/, https://www.twitch.tv/, https://www.dailymotion.com/. I watched videos in full screen mode and pause them or wait until de video finished, in both cases the screen would lock after the screen timeout duration was met.

### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)

**Comment by phd** [comment]
I confirm this is fixed in Firefox Nightly 105.0a1 (Build #2015896979).

**Comment by monolied** [comment]
I'm using Firefox 108 and it is still preventing Android from switching off the screen. Even when it's not even a youtube tab in the foreground; there only was one in the background.
