### ISSUE TITLE
[Bug]: Unable to input Japanese using Gboard in texarea.

### ISSUE THREAD

**Issue by ncaq** [mozilla-mobile/fenix#25043]
### Steps to reproduce

1. Open a site with a textarea element. For example, the issue page of GitHub, the translation page of DeepL, or the search page of 英辞郎 on the web.
2. Type in textarea with Gboard, not reproducible with Galaxy keyboard.
3. Confirm that proper Japanese input is not possible.

### Expected behaviour

It is possible to input proper Japanese.

### Actual behaviour

A video is attached for clarity.
As shown in the video, the words before conversion are determined by themselves and cannot be converted together.
This may be manageable in English, but in Japanese this is a fatal problem.

<https://user-images.githubusercontent.com/2913112/166104051-8309ecae-b24e-4145-bb66-17899496fce5.mp4>

### Device name

Galaxy Z Fold3 5G(SCG11)

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

99.2.0

### Additional information

Gboard version is 11.6.10.

This problem is not reproduced on the Samsung Galaxy keyboard, which is included in the Galaxy from the start.
Given that, I have a feeling that it is a bug in Gboard.
However, even when using Gboard, this bug does not occur with anything other than Firefox for Android.
So whichever is responsible, it is clear that Gboard and Firefox are incompatible.
Google doesn't seem to take civilian bug reports seriously.
Therefore, we will file a bug report to the friendly Mozilla first.

**Comment by makotokato** [comment]
I cannot reproduce this with Pixel 4a and OPPO A5 with simple `<textarea>`.

I can reproduce this with deepl.com, but this is strange issue since I cannot reproduce this when typing is slow. So I need analyze content since this code has a lot of event handlers for inputting.

**Comment by makotokato** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1767556

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by makotokato** [comment]
@ncaq 
Could you verify this using Firefox nightly since I have landed fix in Nightly?

**Comment by ncaq** [comment]
I replied on Twitter.
[エヌユルさんはTwitterを使っています: 「@makoto_kato DeepLで確認した限り治っているようです!」 / Twitter](https://twitter.com/ncaq/status/1526454557802635264)
