### ISSUE TITLE
FNX3-16373 ⁃ [Bug] Crash when saving a bookmarked page to a folder

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2504]
## Steps to reproduce
1. Go to a page and bookmark it.
1. Tap "Edit" in the snackbar.
1. Save the bookmarked page in a folder.

### Expected behavior
The page should be saved in a folder.

### Actual behavior
Fenix crashes.

### Device information
* Android device: Google Pixel (Android 9), Sony Xperia Z5 Premium (Android 7.1.1)
* Fenix version: 1.0.1920 (Build#11350639)

### Note
Please see the attached logcat, and GIF.

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3181805/fenix.txt)

![2019](https://user-images.githubusercontent.com/40694158/57763411-fd530c00-7709-11e9-9b94-1456eda786ed.gif)UNITO-UNDERSCORE!05!UNITO-UNDERSCORE!15!UNITO-UNDERSCORE!04!UNITO-UNDERSCORE!56!UNITO-UNDERSCORE!57!

**Comment by ekager** [comment]
Fixed today by #2526

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.1.1920 (#11360657), with Google Pixel (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
