### ISSUE TITLE
Synchronise all configuration.

### ISSUE THREAD

**Issue by rokejulianlockhart** [mozilla-mobile/fenix#25052]
### What is the user problem or growth opportunity you want to see solved?
I waste time by configuring Firefox when I install it. This is unnecessary because nothing has necessitated divergence from how I have configured Firefox upon another machine.

### How do you know that this problem exists today? Why is this important?
This is important because I have not ever needed to configure different installations of Firefox differently, so immediate automatic configuration subsequent to authentication of my Firefox-account is immensely desirable. However, this may not be applicable to some, but this feature is desirable to them because if implemented configurably, would allow them to synchronise as much a they are able to whilst allowing individual customisation. This is already how synchronisation of configuration of Firefox works. I am consequently merely suggesting expansion of that behaviour.

### Who will benefit from it?
All that utilise this software.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20336)

**Comment by kbrosnan** [comment]
This is too general to be a good feature request. We already have reports for preferences, extensions and search engines among other things.

**Comment by rokejulianlockhart** [comment]
@kbrosnan, I am glad to hear that – indeed, that was all that I wanted to be synchronized. Do you know what those reports’ GitHub issue IDs are?
