### ISSUE TITLE
Intermittent UI test failure - < SmokeTest.audioPlaybackSystemNotificationTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25055]
### Stacktrace:
04-29 15:44:36.580: I/WindowManager(480): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 5c64224 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=true)
04-29 15:44:36.661: D/sql_support::conn_ext(12550): Transaction commited after 127.233834ms
04-29 15:44:36.670: W/FenixPerf(12550): StrictMode violation suppressed: #50
04-29 15:44:36.792: D/nimbus(12550): nimbus_302d_NimbusClient_get_active_experiments
04-29 15:44:36.796: D/nimbus(12550): nimbus_302d_NimbusClient_get_feature_config_variables
04-29 15:44:36.798: W/FenixPerf(12550): StrictMode violation suppressed: #51
04-29 15:44:36.814: D/DefaultHistoryMetadataService(12550): Updating metadata for tab TabSessionState(id=db7d02ea-5aed-4617-bc2d-4bbd2621ccd9, content=ContentState(url=http://localhost:39213/pages/audioMediaPage.html, private=false, title=Audio_Test_Page, progress=100, loading=false, searchTerms=, securityInfo=SecurityInfoState(secure=false, host=, issuer=), thumbnail=null, icon=android.graphics.Bitmap@f6cc7a3, download=null, share=null, hitResult=null, promptRequests=[], findResults=[], windowRequest=null, searchRequest=null, fullScreen=false, layoutInDisplayCutoutMode=0, canGoBack=false, canGoForward=false, webAppManifest=null, firstContentfulPaint=true, history=HistoryState(items=[HistoryItem(title=Audio_Test_Page, uri=http://localhost:39213/pages/audioMediaPage.html)], currentIndex=0), permissionHighlights=PermissionHighlightsState(notificationChanged=false, cameraChanged=false, locationChanged=false, microphoneChanged=false, persistentStorageChanged=false, mediaKeySystemAccessChanged=false, autoPlayAudibleChanged=false, autoPlayInaudibleChanged=false, autoPlayAudibleBlocking=true, autoPlayInaudibleBlocking=false), permissionRequestsList=[], appPermissionRequestsList=[], pictureInPictureEnabled=false, loadRequest=LoadRequestState(url=http://localhost:39213/pages/audioMediaPage.html, triggeredByRedirect=false, triggeredByUser=false), refreshCanceled=false, recordingDevices=[], desktopMode=false, appIntent=null, showToolbarAsExpanded=false, previewImageUrl=null), trackingProtection=TrackingProtectionState(enabled=true, blockedTrackers=[], loadedTrackers=[], ignoredOnTrackingProtection=false), engineState=EngineState(engineSession=mozilla.components.browser.engine.gecko.GeckoEngineSession@fb9d4ba, engineSessionState=mozilla.components.browser.engine.gecko.GeckoEngineSessionState@136daa0, initializing=false, engineObserver=mozilla.components.browser.state.engine.EngineObserver@45c2175, crashed=false, timestamp=6692999, initialLoadFlags=mozilla.components.concept.engine.EngineSession$LoadUrlFlags@0), extensionState={webcompat-reporter@mozilla.org=WebExtensionState(id=webcompat-reporter@mozilla.org, url=null, name=null, enabled=true, allowedInPrivateBrowsing=false, browserAction=null, pageAction=Action(title=null, enabled=true, loadIcon=null, badgeText=null, badgeTextColor=null, badgeBackgroundColor=null, onClick=Function0<kotlin.Unit>), popupSessionId=null, popupSession=null)}, mediaSessionState=MediaSessionState(controller=mozilla.components.browser.engine.gecko.mediasession.GeckoMediaSessionController@c20021e, metadata=null, elementMetadata=null, playbackState=PAUSED, features=Feature(flags=0), positionState=PositionState(duration=-1.0, position=0.0, playbackRate=0.0), muted=false, fullscreen=false, timestamp=1651272258375), contextId=null, source=mozilla.components.browser.state.state.SessionState$Source$Internal$NewTab@b7a3aff, restored=false, parentId=null, lastAccess=1651272255620, createdAt=1651272250027, lastMediaAccessState=LastMediaAccessState(lastMediaUrl=http://localhost:39213/pages/audioMediaPage.html, lastMediaAccess=1651272258394, mediaSessionActive=true), readerState=ReaderState(readerable=false, active=false, checkRequired=false, connectRequired=false, baseUrl=null, activeUrl=null), historyMetadata=HistoryMetadataKey(url=http://localhost:39213/pages/audioMediaPage.html, searchTerm=null, referrerUrl=null))
04-29 15:44:36.814: D/DefaultHistoryMetadataService(12550): Failed to update metadata because it was already recorded or lastAccess is incorrect
04-29 15:44:36.816: D/GeckoViewModule(12550): dispatch GeckoView:WebExtension:SetTabActive, data={"active":false}
04-29 15:44:36.816: D/GeckoViewTab(12550): onEvent: event=GeckoView:WebExtension:SetTabActive, data={"active":false}
04-29 15:44:36.820: I/SessionStorage/AutoSave(12550): Save: New tab selected
04-29 15:44:36.820: D/SessionStorage/AutoSave(12550): Saved state to disk [0ms]
04-29 15:44:36.822: D/WebExtensionsMiddleware(12550): No engine session for new active tab (null)
04-29 15:44:36.842: D/places::ffi(12550): places_de65_PlacesConnection_get_history_metadata_since
04-29 15:44:36.851: D/LeakCanary(12550): Watching instance of org.mozilla.fenix.browser.SwipeGestureLayout (org.mozilla.fenix.browser.BrowserFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 27156ed2-3a49-4a0d-a790-25091f78a9fa
04-29 15:44:36.851: D/LeakCanary(12550): Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key db08576e-4372-4009-9ebe-df57f4e34962
04-29 15:44:36.851: D/LeakCanary(12550): Watching instance of org.mozilla.fenix.components.StoreProvider (org.mozilla.fenix.components.StoreProvider received ViewModel#onCleared() callback) with key bc948c3f-2249-47c8-99d1-1f2bff935a89
04-29 15:44:36.851: D/LeakCanary(12550): Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 4a441472-6e3a-4cc3-a323-00b107b36a0c
04-29 15:44:36.852: D/ThumbnailStorage(12550): Removed thumbnail from disk (sessionIdOrUrl = db7d02ea-5aed-4617-bc2d-4bbd2621ccd9)
04-29 15:44:36.852: D/LeakCanary(12550): Watching instance of org.mozilla.fenix.browser.BrowserFragment (org.mozilla.fenix.browser.BrowserFragment received Fragment#onDestroy() callback) with key a3241c9e-590f-4c26-9bca-f30b942557cf
04-29 15:44:36.854: W/FenixPerf(12550): StrictMode violation suppressed: #52
04-29 15:44:36.856: I/ActivityManager(480): Force stopping org.mozilla.fenix.debug appid=10151 user=0: finished inst
04-29 15:44:36.857: I/ActivityManager(480): Killing 12550:org.mozilla.fenix.debug/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 15:44:36.857: W/Binder(12500): Caught a RuntimeException from the binder stub implementation.
04-29 15:44:36.857: W/Binder(12500): java.lang.SecurityException: Calling from not trusted UID!
04-29 15:44:36.857: W/Binder(12500): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
04-29 15:44:36.857: W/Binder(12500): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
04-29 15:44:36.857: W/Binder(12500): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
04-29 15:44:36.857: W/Binder(12500): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
04-29 15:44:36.857: W/Binder(12500): 	at android.os.Binder.execTransact(Binder.java:1123)
04-29 15:44:36.862: I/ServiceChildProcess(13165): Destroying GeckoServiceChildProcess
04-29 15:44:36.863: W/ActivityTaskManager(480): Force removing ActivityRecord{b821848 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
04-29 15:44:36.870: I/ActivityManager(480): Killing 13165:org.mozilla.fenix.debug:tab9/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 15:44:36.870: I/ActivityManager(480): Killing 13370:org.mozilla.fenix.debug:gpu/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 15:44:36.901: D/AndroidRuntime(12500): Shutting down VM
04-29 15:44:36.924: D/WindowManager(480): notifyANR took 357ms
### Notes Similar with #24047

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20340)

**Comment by AndiAJ** [comment]
Flaky again due to the ANR [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6980551312252686855/executions/bs.a8a9393733087dc4/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky on 5/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8284089589761317682/executions/bs.d91f5cc4c9c475ea/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5262751007738123275/executions/bs.f16add0467293a8b/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x o 5/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8437708699014556243/executions/bs.54a34af3c544d309/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7735792011573226913/executions/bs.f7020829d19f6639/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5053195014919851165/executions/bs.7dddddcbb9e55c5a/test-cases)

**Comment by AaronMT** [comment]
1x on 5/6 PR [Firebase link](https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8541816937527319761/details?stepId=bs.5dad88947854a43a&testCaseId=1)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5256751449734227182/executions/bs.8b71671386c22f04/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7794165154069236719/executions/bs.5f78bbcdebc583e9/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5033474532246976111/executions/bs.1f36c840c322b75c/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/17 Main 

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6205589146968146110/executions/bs.2d9a4d314ed0d06f/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8564908508280342891/executions/bs.f6d366061d4f8a07/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4902703621315048994/executions/bs.51ac75cd4e4540ec/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8018778787200624400/executions/bs.61543e87604a7b7c/test-cases)

Flaky 1x on 5/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4902703621315048994/executions/bs.51ac75cd4e4540ec/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7594689482728574533/executions/bs.dc541456d12b3a33/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Closing as dupe, in favor of https://github.com/mozilla-mobile/fenix/issues/25926 - tracking all ANR reports
