### ISSUE TITLE
[Bug] Provide Access to Awesome Bar (and subsequently the Quick Action Bar) Without Requiring the User to Scrolling the Page

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2505]
## Steps to reproduce
1. Go to a page with a lot of text
1. Scroll down some
1. Want to access the Awesome (URL) Bar or the Quick Action Bar

### Expected behavior
A swipe from the edge should show the Awesome (URL) Bar.

### Actual behavior
The page just scrolls back up, forcing the user to then scroll down once more. This isn't intuitive and it's annoying.

### Device information
* Android device: Android 7.0, Nvidia Shield Tablet
* Fenix version: 1.0.1920 (Build #11340607)

**Comment by bifleming** [comment]
@vesta0 changed to feature request.

**Comment by kbrosnan** [comment]
This is mostly about the QAB/Address bar interaction. We have better issues for always showing the address bar like #10240
