### ISSUE TITLE
[Bug]: Most buttons on gamepads don't work

### ISSUE THREAD

**Issue by xfix** [mozilla-mobile/fenix#25053]
### Steps to reproduce

1. Visit https://gamepad-tester.com/
2. Pair a controller
3. Try pressing a button such as A, B, X, Y, L, R, Start, Select, Home

### Expected behaviour

A button press should be noticed.

### Actual behaviour

Only d-pad, sticks and analog triggers are noticed.

### Device name

Xioami Pocophone F1

### Android version

Android 12 (LineageOS)

### Firefox release type

Firefox

### Firefox version

99.2.0

### Additional information

This compares behavior of Firefox with LineageOS's built-in web browser.

https://user-images.githubusercontent.com/1297598/166183957-7317299e-09fe-4626-a2d4-a03628d3c41a.mp4

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1768515

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
