### ISSUE TITLE
[Bug]: URLs with underscores in "Fill link from clipboard" not displaying correctly

### ISSUE THREAD

**Issue by alex-bellon** [mozilla-mobile/fenix#25065]
### Steps to reproduce

1. Copy a link that has an underscore to clipboard
2. Go to open new tab
3. Look at URL in the "Fill link from clipboard" section

### Expected behaviour

The underscored should take up the appropriate amount of space for a character

### Actual behaviour

Depending on the link, some of the following/previous characters are overlapping the underscore

### Device name

Samsung Galaxy S9+

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

99.2.0 (Build #2015874211)

### Additional information

![image](https://user-images.githubusercontent.com/24237402/166306036-75b55e45-94b5-44d6-b173-c37e4ea21d50.png)

![image](https://user-images.githubusercontent.com/24237402/166306054-eb9344ac-fe56-4d03-8e41-982db5de2c25.png)

![image](https://user-images.githubusercontent.com/24237402/166306068-291f8c82-43a4-45a4-95ce-7d6862aa09c6.png)

![image](https://user-images.githubusercontent.com/24237402/166306085-93300ceb-2cbc-49b3-bcf7-7a0144be000e.png)

As you can see, this only happens with some of the links. I'm not sure what makes the difference between how much the characters overlap the underscore, some instances are worse than others.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20347)

**Comment by Alexandru2909** [comment]
Since we removed the metropolis font, I found no lapping underscores.
|||
| --- | --- |
| ![Screenshot_20221123_103255](https://user-images.githubusercontent.com/35462038/203501736-ee6b9436-e4ca-4ccb-af86-87844b2b545c.png) | ![Screenshot_20221123_103318](https://user-images.githubusercontent.com/35462038/203501999-4fdcff8c-ed60-4120-a541-0e31ab557f4f.png) |

@alex-bellon can you still reproduce this?

**Comment by alex-bellon** [comment]
I am not seeing the issues anymore either! Seems to be fixed for me.
