### ISSUE TITLE
Intermittent nightly build failure - Plugin [id: 'com.jetbrains.python.envs', version: '0.0.26'] was not found in any of the following sources

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#25063]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=376430789&repo=fenix
### Stacktrace:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/builds/worker/checkouts/vcs/app/build.gradle' line: 4

* What went wrong:
Plugin [id: 'com.jetbrains.python.envs', version: '0.0.26'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.jetbrains.python.envs:com.jetbrains.python.envs.gradle.plugin:0.0.26')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/2cf9f3fa5caeaa8f978ce4c8e6254c1864b248e0

Connectivity issue tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1619659 ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20346)

**Comment by csadilek** [comment]
Duping to https://bugzilla.mozilla.org/show_bug.cgi?id=1619659.
