### ISSUE TITLE
Double click for previous tab

### ISSUE THREAD

**Issue by mavit** [mozilla-mobile/fenix#25067]
In Android, you can click once on the square icon at the bottom of the screen to see a list of all running apps, or you can double click on it to jump straight to the last app used.

It would be convenient if Firefox for Android exhibited similar behaviour, jumping directly to the most recently viewed tab when you double click on the tabs icon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20348)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813939

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
