### ISSUE TITLE
[Bug] Tabs Icon Needs Correcting

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2506]
## Steps to reproduce
1. Open a tab
1. Open another tab
1. Open another tab

### Expected behavior
Both sides of the background tab should have the same curve.

### Actual behavior
The background tab on the icon has a larger curve on the right side than the left side. 

### Device information
* Android device: Android 7, Nvidia Shield
* Fenix version: 1.0.1920 (Build #11340607)

**Comment by pwd-github** [comment]
![Screenshot_20190515-105257](https://user-images.githubusercontent.com/203217/57766915-2078be00-7700-11e9-84f0-054033f16726.png)

This icon.

**Comment by ekager** [comment]
Closing this issue for now, because we've discussed this icon before, and UX is currently happy with it
