### ISSUE TITLE
FNX3-16376 ⁃ [Bug] Saved collection is not displayed

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2507]
## Steps to reproduce
1. Open a few pages.
1. Tap on three-dot menu from Open tabs section.
1. Tap on Save to collection.
1. Select all tabs and save to a collection.

### Expected behavior
The saved collection should be displayed under the opened tabs.

### Actual behavior
There is no saved collection displayed.

### Device information
* Android devices: Google Pixel (Android 9), Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8.0)
* Fenix version: 1.0.1920 (#11350639)

### Notes
Even when Fenix is closed and reopened, the saved collection is not displayed.
Please see the attached logcat and GIF.

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3182433/logcat.txt)

![2019](https://user-images.githubusercontent.com/40694158/57774201-955cef80-7722-11e9-8dfa-8a5a39ea9c09.gif)UNITO-UNDERSCORE!05!UNITO-UNDERSCORE!15!

**Comment by vesta0** [comment]
I believe this feature was behind a feature flag up until yesterday. Please test again @softvision-miralobontiu  :)

**Comment by softvision-miralobontiu** [comment]
Hi, @vesta0 
I cannot retest, the "Save to collection" button is not displayed in the latest build 1.0.1920 (#11391807).

**Comment by softvision-miralobontiu** [comment]
Hi, @vesta0
I cannot retest, the "Save to collection" button is not displayed in the latest build 1.0.1920 (#11391807).

**Comment by sv-ohorvath** [comment]
Collections are now displayed, using the long tap to select method.
The missing button issue is logged here: #2412.
