### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. goToHomeScreenTopToolbarPrivateModeTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25086]
### Stacktrace:
05-03 06:18:58.021: I/WindowManager(472): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 11a009a org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5000ms for KeyEvent(deviceId=-1, source=0x00000101, displayId=-1, action=UP, flags=0x00000000, keyCode=66, scanCode=0, metaState=0x00000000, repeatCount=0), policyFlags=0x6b000000
05-03 06:18:58.053: I/OpenGLRenderer(12693): Davey! duration=2999ms; Flags=1, IntendedVsync=796274118510, Vsync=796374118506, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=796381662736, AnimationStart=796381665216, PerformTraversalsStart=796382343782, DrawStart=799144721312, SyncQueued=799146185172, SyncStart=799147523060, IssueDrawCommandsStart=799147989102, SwapBuffers=799227498326, FrameCompleted=799274565674, DequeueBufferDuration=12574124, QueueBufferDuration=620547, GpuCompleted=0, 
05-03 06:18:58.149: I/Choreographer(12693): Skipped 177 frames!  The application may be doing too much work on its main thread.
05-03 06:18:58.176: I/ActivityManager(472): Force stopping org.mozilla.fenix.debug appid=10151 user=0: finished inst
05-03 06:18:58.176: I/ActivityManager(472): Killing 12693:org.mozilla.fenix.debug/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-03 06:18:58.179: W/ActivityTaskManager(472): Force removing ActivityRecord{128b7 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
05-03 06:18:58.180: W/Binder(12665): Caught a RuntimeException from the binder stub implementation.
05-03 06:18:58.180: W/Binder(12665): java.lang.SecurityException: Calling from not trusted UID!
05-03 06:18:58.180: W/Binder(12665): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-03 06:18:58.180: W/Binder(12665): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-03 06:18:58.180: W/Binder(12665): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-03 06:18:58.180: W/Binder(12665): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-03 06:18:58.180: W/Binder(12665): 	at android.os.Binder.execTransact(Binder.java:1123)
05-03 06:18:58.182: I/ServiceChildProcess(13381): Destroying GeckoServiceChildProcess
05-03 06:18:58.207: I/nix.debug:tab1(13381): System.exit called, status: 0
05-03 06:18:58.207: I/AndroidRuntime(13381): VM exiting with result code 0, cleanup skipped.
05-03 06:18:58.208: I/ServiceChildProcess(13576): Destroying GeckoServiceChildProcess
05-03 06:18:58.212: D/AndroidRuntime(12665): Shutting down VM
05-03 06:18:58.213: E/JavaBinder(12665): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
05-03 06:18:58.213: E/JavaBinder(12665): java.lang.RuntimeException: Bad file descriptor
05-03 06:18:58.213: E/JavaBinder(12665): 	at android.os.BinderProxy.transactNative(Native Method)
05-03 06:18:58.213: E/JavaBinder(12665): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
05-03 06:18:58.213: E/JavaBinder(12665): 	at android.view.IWindowManager$Stub$Proxy.injectInputAfterTransactionsApplied(IWindowManager.java:5262)
05-03 06:18:58.213: E/JavaBinder(12665): 	at android.app.UiAutomationConnection.injectInputEvent(UiAutomationConnection.java:136)
05-03 06:18:58.213: E/JavaBinder(12665): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:228)
05-03 06:18:58.213: E/JavaBinder(12665): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
05-03 06:18:58.213: E/JavaBinder(12665): 	at android.os.Binder.execTransact(Binder.java:1123)
05-03 06:18:58.271: I/fenix.debug:gp(13576): System.exit called, status: 0
05-03 06:18:58.271: I/AndroidRuntime(13576): VM exiting with result code 0, cleanup skipped.
05-03 06:18:58.345: I/Zygote(289): Process 12693 exited due to signal 9 (Killed)
05-03 06:18:58.354: I/libprocessgroup(472): Successfully killed process cgroup uid 10151 pid 12693 in 175ms
05-03 06:18:58.378: I/Zygote(289): Process 13576 exited cleanly (0)
05-03 06:18:58.409: I/Zygote(289): Process 13381 exited cleanly (0)
05-03 06:18:58.479: E/MmTelFeatureConnection [0](1814): ImsRegistrationCallbackAdapter: ImsRegistration is null
05-03 06:18:58.628: I/binder(0): release 12693:13455 transaction 1177317 out, still active
05-03 06:18:58.629: I/binder(0): undelivered TRANSACTION_COMPLETE
05-03 06:18:58.632: I/binder(0): undelivered transaction 1179199, process died.
05-03 06:18:58.543: I/RenderThread(472): type=1400 audit(0.0:180): avc: denied { execmem } for scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=process permissive=1 b/65201432
05-03 06:18:58.858: I/binder(0): release 12665:12691 transaction 1177319 out, still active
05-03 06:18:58.859: I/binder(0): release 12665:12691 transaction 1177317 in, still active
05-03 06:18:58.829: W/LatinCountersMetricsProcessor(2205): LatinCountersMetricsProcessor$DelightProblemReporter.run():1362 Missing LM for 'en'
05-03 06:18:58.886: E/FrameEvents(472): updateAcquireFence: Did not find frame.
05-03 06:18:58.907: I/ActivityManager(472): Killing 13381:org.mozilla.fenix.debug:tab13/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-03 06:18:58.907: I/libprocessgroup(472): Successfully killed process cgroup uid 10151 pid 13381 in 0ms
05-03 06:18:58.908: W/system_server(472): Long monitor contention with owner InputDispatcher (1493) at void com.android.server.wm.TaskChangeNotificationController.forAllLocalListeners(com.android.server.wm.TaskChangeNotificationController$TaskStackConsumer, android.os.Message)(TaskChangeNotificationController.java:351) waiters=3 in void com.android.server.wm.Session.binderDied() for 334ms
05-03 06:18:58.908: W/system_server(472): Long monitor contention with owner InputDispatcher (1493) at void com.android.server.wm.TaskChangeNotificationController.forAllLocalListeners(com.android.server.wm.TaskChangeNotificationController$TaskStackConsumer, android.os.Message)(TaskChangeNotificationController.java:351) waiters=0 in void com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$1$SurfaceAnimator(com.android.server.wm.SurfaceAnimator$OnAnimationFinishedCallback, int, com.android.server.wm.AnimationAdapter) for 713ms
05-03 06:18:58.908: W/system_server(472): Long monitor contention with owner InputDispatcher (1493) at void com.android.server.wm.TaskChangeNotificationController.forAllLocalListeners(com.android.server.wm.TaskChangeNotificationController$TaskStackConsumer, android.os.Message)(TaskChangeNotificationController.java:351) waiters=1 in void com.android.server.wm.WindowState$DeathRecipient.binderDied() for 337ms
05-03 06:18:58.909: I/WindowManager(472): WIN DEATH: Window{11a009a u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}
05-03 06:18:58.913: W/WindowManager(472): Cannot find window which accessibility connection is added to
05-03 06:18:58.913: W/system_server(472): Long monitor contention with owner Binder:472_5 (1488) at void com.android.server.accessibility.AccessibilityWindowManager$RemoteAccessibilityConnection.binderDied()(AccessibilityWindowManager.java:830) waiters=0 in void com.android.server.accessibility.UiAutomationManager.destroyUiAutomationService() for 337ms
05-03 06:18:58.914: I/Choreographer(472): Skipped 42 frames!  The application may be doing too much work on its main thread.
05-03 06:18:58.917: W/WindowManager(472): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@1b78d95
05-03 06:18:58.917: I/ActivityManager(472): Killing 13576:org.mozilla.fenix.debug:gpu/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-03 06:18:58.919: I/libprocessgroup(472): Successfully killed process cgroup uid 10151 pid 13576 in 1ms
05-03 06:18:58.919: V/UiAutomationManager(472): UiAutomation service owner died
05-03 06:18:58.920: D/WindowManager(472): notifyANR took 907ms
### Notes Similar with #24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20359)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5788891211849078919/executions/bs.7f53a4b39f38dde4/testcases/1/test-cases)

**Comment by AaronMT** [comment]
This is triggering the ANR http://bugzilla.mozilla.org/show_bug.cgi?id=1764605

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
