### ISSUE TITLE
[Bug]: Custom Add-on on collections option can be seen disappearing when accessing Settings menu from CFR in Fenix

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25083]
### Steps to reproduce

1. Make sure you have a clean profile and Instagram app installed on your device.
2. In Fenix, open instagram.com.
3. When the CFR is displayed, tap on GO TO SETTINGS.
4. Observe the result.

### Expected behaviour

The transition is smooth, and the Settings page is opened without visual issues.

### Actual behaviour

As the Settings page is opened, Custom Add-on on collections option can be seen disappearing from under the Add-ons option.

### Device name

Motorola Moto G30

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

101.0a1 (Build 2015877963) from 05/02

### Additional information
Also Reproducible on Firefox Beta 101.beta.1, RC 100.1.1.
The "Custom Add-on on collections" option can be enabled in Nightly when enabling the Secret settings, but is not available on the Beta/RC versions.

https://user-images.githubusercontent.com/89388888/166450216-3d33b03a-4b43-4412-86fb-438109d95a35.mp4

![Screenshot_20220503-132404](https://user-images.githubusercontent.com/89388888/166450304-001f2288-55b5-43c7-a14b-610bf068f28e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20356)

**Comment by mamunabcoder** [comment]
Please follow the below link process then you could see the "Custom Add-on Collection" menu into the settings screen.

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807124

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
