### ISSUE TITLE
[Bug]: File name is not shown in the download prompt at southmp3.org

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#25081]
### Steps to reproduce

1. Navigate to: https://southmp3.org/kanchana/.
2. Download a file.
3. Observe the download prompt.

### Expected behaviour

The file name is shown.

### Actual behaviour

The file name is blank.

### Device name

Google Pixel 3 -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)

### Android version

Android 12
### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 102.0a1 (2015878251 -🦎102.0a1-20220502144301🦎)

### Additional information

1. Originally reported here: https://github.com/webcompat/web-bugs/issues/103483.
2. Reproducible on: https://github.com/webcompat/web-bugs/issues/102412 and https://github.com/webcompat/web-bugs/issues/102757

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20355)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 2022-05-06.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
