### ISSUE TITLE
[Bug]: *critical* all other sites are not loading after trying to open sonyliv site

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#25093]
### Steps to reproduce

Browse the URL sonyliv.com
This tab/website is not loading properly
Because of this other websites in other tabs are no longer reloading or connecting to Internet

### Expected behaviour

A particular site should not affect other sites

### Actual behaviour

This website is affecting other sites seems it is causing some issue to networking ..issue is there even in beta

Only resolution to fix is force stop the browser

### Device name

asus rog 3

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

latest 

### Additional information

https://user-images.githubusercontent.com/58127841/166552908-952ad3ac-5bfd-44d7-9831-b75764f17140.mp4

**Comment by SoftVision-LorandJanos** [comment]
Hi @sheikh-azharuddin ! Thanks for your report!
I couldn't reproduce your issue. However the mentioned site is now different than how I saw it on your video.
Could you recheck using the latest build(s)? Thank you!
Tested on the latest:
- Nightly 102.0a1 (2022-05-11).
- Beta (101.0.0-beta3).
- Release (100.1.2RC).

Device used: Google Pixel 4 (Android 12).

**Comment by sheikh-azharuddin** [comment]
Seems fixed..what I think the site was using too much resources due to which the other sites were crashing
