### ISSUE TITLE
[Bug]: "Unable to send RETRY" snackbar is not displayed again after tapping "Retry" on Motorola device

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25106]
### Steps to reproduce

1. Sign in with the same account on Desktop and on Fenix.
2. On Android, open a webpage and tap Share from the main menu. Don't tap on the account displayed yet.
3. Go to Desktop - your account - Manage account and change the password or disconnect.
4. Immediately after the password is changed/devices disconnected, go to Android and tap on the desktop account.
5. When the "Unable to send RETRY" snackbar is presented, tap on RETRY.

### Expected behaviour

The same snackbar should be displayed.

### Actual behaviour

The snackbar is not displayed again after tapping "Retry". 
On Google Pixel 6 (Android 13) and Google Pixel 6 (Android 12) the snackbar will continue to be displayed as long as the user taps on "Retry".

### Device name

Motorola Moto G30

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly from 05/04

### Additional information

Reproducible on Beta 101.0.0-beta.1.

https://user-images.githubusercontent.com/89388888/166703277-8814c3c6-3a89-4086-ae8a-350d72a98610.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20369)

**Comment by delia-pop** [comment]
Tested with Motorola Moto G30 (Android 12) on Beta 108.0b1. The issues is no longer present. The snackbar is displayed again after tapping the "Retry" button.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807137

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
