### ISSUE TITLE
Please synchronise configuration of extensions.

### ISSUE THREAD

**Issue by rokejulianlockhart** [mozilla-mobile/fenix#25109]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

I want configuration of extensions subsequent to installation to become unnecessary.

### How do you know that this problem exists today? Why is this important?

This is important because configuration unnecessarily requires much time and potentially introduces inconsistency of configuration.

### Who will benefit from it?
All that utilise extensions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20373)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811313

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
