### ISSUE TITLE
[Bug]: Native crash recorded when closing a tab

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25102]
### Steps to reproduce

1. Open "Pocket top site"
2. Quickly open the tabs tray and close the tab

### Expected behaviour
The tab is properly closed without any issues.

### Actual behaviour
Native crash

### Device name
Google Pixel 3a (Android 11)

### Firefox version
102.0a1 from 5/4

### Notes
► About crashes screenshot
<img width="460" alt="image" src="https://user-images.githubusercontent.com/51314259/166650836-45a82eee-5072-43ba-afea-f272872a8fe7.png">

► Reports
9319208d-6f6d-4dc4-bf0c-1ad115a7a539
<native crash>
* Socorro: https://crash-stats.mozilla.org/report/index/bp-5b3025ab-e119-4741-896b-86a3b0220504
- - - -
<native crash>

f5b09a9b-4ba5-438e-a802-c00710ea807c
< native crash>
- - - -
<native crash>

fb54f46d-2ad4-44dd-a7f2-0d1ea5d086d5
< native crash>
- - - -
< native crash>

fb54f46d-2ad4-44dd-a7f2-0d1ea5d086d5
< native crash>
- -- -
< native crash>

Similar STR (close a tab) as the ANR's encountered in our automated UI tests [#24978](https://github.com/mozilla-mobile/fenix/issues/24978#issuecomment-1112260675)
Seems to be be similar with #25008

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20366)

**Comment by agi** [comment]
Hey @AndiAJ could capture logs while reproducing this (if possible with a debug build)? Also are you able to reproduce this on Android 12 too? And finally, a video of you trying to reproduce it would help too. Thanks!

**Comment by sheikh-azharuddin** [comment]
> Hey @AndiAJ could capture logs while reproducing this (if possible with a debug build)? Also are you able to reproduce this on Android 12 too? And finally, a video of you trying to reproduce it would help too. Thanks!

I am getting same crash in android 12 too
https://crash-stats.mozilla.org/report/index/cd488519-8674-4036-bfc9-eb5940220509

**Comment by sheikh-azharuddin** [comment]
> 

Happy to help but I don't know how to collect logcat..also I don't have any PC. please suggest

**Comment by sheikh-azharuddin** [comment]
Here is the video
Not sure how to take logcat..pls guide

https://user-images.githubusercontent.com/58127841/167994134-49fdb3be-ac11-4080-9779-75dbe1ec719f.mp4

**Comment by alsuren** [comment]
I get this occasionally on android 12 (Samsung A-series phone) on Firefox for Android nightly.

So far this morning, I have:

https://crash-stats.mozilla.org/report/index/26640b23-e127-472e-8cdc-379cc0220623

https://crash-stats.mozilla.org/report/index/08d5c896-b34a-424a-a3d5-db4810220623

And https://crash-stats.mozilla.org/report/index/344b693a-4b22-4cbe-bce1-550260220623 when selecting a tab after closing a tab

I am currently collecting Socorro links in Trello, to avoid spamming the issue too much https://trello.com/c/v4iUxEpv . Once I have a few more, I will try to find some common themes and report back.

**Comment by agi** [comment]
Hi @alsuren , the crash linked in those reports is being fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1771934

**Comment by cpeterso** [comment]
> the crash linked in those reports is being fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1771934
