### ISSUE TITLE
Enable the messaging framework feature

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#25110]
We need to enable the `messagingFeature` feature.

**Comment by Amejia481** [comment]
https://mozilla-hub.atlassian.net/browse/FNXV2-20374

**Comment by amedyne** [comment]
@Amejia481 I believe based on the discussion we also have to enable the [Default Browser(?)](https://github.com/mozilla-mobile/fenix/blob/94b934290d1ff0a9c0887c4eebfdfee7625c4cef/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L68)

**Comment by Amejia481** [comment]
Thanks for noticing it :) 
Yes, that's correct. Now we are showing the default browser message via the messaging framework, which gets its default values from the [nimbus.fml.yaml](https://github.com/mozilla-mobile/fenix/commit/b22a34db2e7b33a43c848938af35fc23546fb24a#diff-680637c1a9cdbef47ee7a3333ef917b741c19c3266663c0c760c0cbbc69b1928R163-R169), previously the default browser message was only available on nightly now we are moving it to all channels :)

**Comment by Amejia481** [comment]
> Verified as fixed on Firefox Beta 101.0.0-beta.3 with LG G7 fit (Android 8.1.0). The "Set as default browser" message is displayed on home page. ![Screenshot (May 9, 2022 16 25 24)](https://user-images.githubusercontent.com/89388888/167422143-030fac32-0359-44d4-a5f8-64c9b18dfa96.png)

Thanks for verifying @delia-pop 🎉
