### ISSUE TITLE
Primary / master password for mobile browsers

### ISSUE THREAD

**Issue by devmet34** [mozilla-mobile/fenix#25137]
Hello,

Primary/master password feature is a good one. It definitely gives extra security to users, actually it should be dafault on every mobile browsers considering there is only 1 step protection on mobile devices which is  pin/password or even a simple pattern or even just swiping. Therefore, a second step security like primary password is a great security practice for browsers. 2/3 step security are everywhere nowadays.

In addition to functionality, chrome doesnt have this one yet so would be wise to have this feature.

**Comment by cadeyrn** [comment]
Duplicate of #14501, #15147, #17090 and probably a few more.

It was explained in https://github.com/mozilla-mobile/fenix/issues/14501#issuecomment-683888369 why Mozilla decided against it (and why it's not true that it gives more security).
