### ISSUE TITLE
Errors in creating and maintaining UiAutomation connection in Instrumented tests

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#25132]
Intermittently, an early `getInstrumentation()` call in `beforeActivityLaunched` for our `HomeActivityTestRule.kt`  will throw a `java.lang.RuntimeException` with a `Error while connecting UiAutomation`. This seems to happen more frequent on 1.4.0 and espresso 3.4.0 libraries [2] - just getting a ticket on file here to wrap this call and try again (although I don't know if multiple attempts to get a handle on the running instrumentation will do anything). This is for executing a shell command to set a timeout on long tap. 

Stack:

```Kotlin
java.lang.RuntimeException: Error while connecting UiAutomation@afc456f[id=-1, flags=0]
at android.app.UiAutomation.connect(UiAutomation.java:259)
at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
at org.mozilla.fenix.helpers.HomeActivityTestRuleKt.setLongTapTimeout(HomeActivityTestRule.kt:78)
```

[1]  [Firebase Log](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5262751007738123275/executions/bs.a7816152eb688985/testcases/1/test-cases)
[2] Ticket filed as https://github.com/android/android-test/issues/1305

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20390)

**Comment by AndiAJ** [comment]
Corresponding intermitent tests:
`customTabShareTextTest` #25099
`privateBrowsingUseAppWhileTabIsCrashedTest` #25076
`verifyExpandedCollectionItemsTest` #25075
`verifyContextOpenImageNewTab` #25054

**Comment by AndiAJ** [comment]
Hey @AaronMT , it's still happening.
`closeAllTabsTest` #25341
`openMainMenuSettingsItemTest` #25342

**Comment by sv-ohorvath** [comment]
New cases started to appear:
`saveLoginFromPromptTest ` #25414
`addPrivateBrowsingShortcut` #25416
`customTabsOpenExternalLinkTest` #25028
`downloadMultipleFileTypesTest` #25296

**Comment by AaronMT** [comment]
I filed an issue on a Google issue tracker, I have no idea what causes this. I suspect it's a particular in androidx.test.uiautomator:uiautomator

https://issuetracker.google.com/u/1/issues/233914320

**Comment by sv-ohorvath** [comment]
`java.lang.IllegalStateException: UiAutomation not connected, UiAutomation` in the following issues:
https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aopen+java.lang.IllegalStateException%3A+UiAutomation+not+connected%2C+UiAutomation

**Comment by AaronMT** [comment]
FTL team responded back on Slack that a potential fix should be in as of yesterday (06/29), let's keep a track on any reoccurrence and I'll reply back.

**Comment by AndiAJ** [comment]
### ► 6/30
`java.lang.IllegalStateException: UiAutomation not connected, UiAutomation`
• [searchSettingsItemsTest](https://github.com/mozilla-mobile/fenix/issues/25853) 

`java.lang.RuntimeException: Error while connecting UiAutomation`
• [verifyMultipleLoginsSelectionsTest](https://github.com/mozilla-mobile/fenix/issues/25854) 
• [mainMenuShareButtonTest](https://github.com/mozilla-mobile/fenix/issues/25711#issuecomment-1172040123) 
• [closePrivateTabTest](https://github.com/mozilla-mobile/fenix/issues/25727#issuecomment-1172037192) 
• [emptyTabsTrayViewPrivateBrowsingTest](https://github.com/mozilla-mobile/fenix/issues/25835) 
• [openMainMenuAddToCollectionTest](https://github.com/mozilla-mobile/fenix/issues/25834)

**Comment by AndiAJ** [comment]
7/4
`java.lang.RuntimeException: Error while connecting UiAutomation`
• [deleteTabsDataWithNoOpenTabsTest](https://github.com/mozilla-mobile/fenix/issues/25873)

**Comment by AndiAJ** [comment]
### ► 7/5
`java.lang.IllegalStateException: UiAutomation not connected, UiAutomation`
• [navigateBookmarksFoldersTest](https://github.com/mozilla-mobile/fenix/issues/25340#issuecomment-1174885924)
• [emailLinkPWATest](https://github.com/mozilla-mobile/fenix/issues/25340#issuecomment-1174885924)

**Comment by AaronMT** [comment]
Firebase Team Update:

> Hello Aaron, 
> Thank you for your patience while this issue was troubleshooted. 
>The product team have narrowed down the issue to GmsCore, which is encountering issues with virtual images. 
>An update is scheduled sometime in the next few weeks which should address this issue. 
>Until the update is rolled out, the Test Lab team suggests that we should monitor the public issue [1]. 
>Please let me know if you have any further questions regarding this issue. 
>Thank you

Also in communication with a member on the Firebase Community Slack about a fix too.

**Comment by AndiAJ** [comment]
### ► 7/5
`java.lang.IllegalStateException: UiAutomation not connected, UiAutomation`
• [deleteHistoryItemTest](https://github.com/mozilla-mobile/fenix/issues/25903)
• [multipleBookmarkDeletionsTest](https://github.com/mozilla-mobile/fenix/issues/25907)
• [editBookmarkTest](https://github.com/mozilla-mobile/fenix/issues/25908)

`java.lang.RuntimeException: Error while connecting UiAutomation`
• [verifyAddToFirefoxHome](https://github.com/mozilla-mobile/fenix/issues/25900)
• [verifyUndoSnackBarTest](https://github.com/mozilla-mobile/fenix/issues/25901)
• [openLinkInAppTest](https://github.com/mozilla-mobile/fenix/issues/25902)
• [testCloseDownloadPrompt](https://github.com/mozilla-mobile/fenix/issues/25904)
• [testDownloadCompleteNotification](https://github.com/mozilla-mobile/fenix/issues/25905)
• [editBookmarkTest](https://github.com/mozilla-mobile/fenix/issues/25908)

**Comment by Mugurell** [comment]
Saw the issue again in https://github.com/mozilla-mobile/fenix/pull/26299 for `verifyEmptyTabTray`.

**Comment by AaronMT** [comment]
Currently waiting on Google to push out an update to Firebase Test Lab to ensure all devices are using newer GMSCore (FLOSS Play Services) version which was the culprit of this problem.

**Comment by AaronMT** [comment]
FTL Update (09.15)
> The fix has finally been pushed to production. The issue should be resolved now, please give it a try.

We've also switched to `Pixel2.arm` (ARM) running a new GMSCore (Play Services), and have *knock on wood* yet to see see too. We can re-enable the affected tests and close this out.

**Comment by AaronMT** [comment]
This was resolved on their end.
