### ISSUE TITLE
Stop automatic page refresh

### ISSUE THREAD

**Issue by Lampoil** [mozilla-mobile/fenix#25136]
Ffox on Android,
When I press the send 2FA request on "SOME" websites then open my email or the messages app to retrieve that code I then have to bring Ffox back to the foreground, but on doing so the page automatically refreshes itself and a new code is sent creating an endless loop.
NOTE: This happens only on SOME websites with FF for android. It doesn't happen with Chrome on Android or with FF on my laptop.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20394)

**Comment by cadeyrn** [comment]
> NOTE: This happens only on SOME websites

Then you should mention the affected sites, I guess?

**Comment by 424344** [comment]
please don't close this issue.

**Comment by csadilek** [comment]
The work to address this problem is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1752594.
