### ISSUE TITLE
[Bug]: string "history_multi_select_title" is incorrectly translated in zh-CN and zh-TW

### ISSUE THREAD

**Issue by jackyzy823** [mozilla-mobile/fenix#25148]
### Steps to reproduce

1. Open "History"
2. Long Press "History Item"

### Expected behaviour

in zh-CN https://github.com/mozilla-mobile/fenix/blob/94b934290d1ff0a9c0887c4eebfdfee7625c4cef/app/src/main/res/values-zh-rCN/strings.xml#L805
`%1$d selected` should be translate to `已选择 %1$d 条历史记录`  not  `已选择 %1$d 条书签` (which means bookmark)

the same as zh-TW https://github.com/mozilla-mobile/fenix/blob/94b934290d1ff0a9c0887c4eebfdfee7625c4cef/app/src/main/res/values-zh-rTW/strings.xml#L795
`%1$d selected` should be translate to `已選擇 %1$d 筆瀏覽紀錄`   not `已選擇 %1$d 筆書籤` 

### Actual behaviour

![Screenshot_2022-05-06-23-43-31-247](https://user-images.githubusercontent.com/2900871/167167508-b83001ce-750f-4a86-bf63-83d81b9e55d4.jpeg)

### Device name

Huawei

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

Nightly Build

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20402)

**Comment by kbrosnan** [comment]
@flodolo would you let the Chinese localization teams about this suggestion?

**Comment by flodolo** [comment]
@petercpg
Could you take a look at the suggestion here for zh-TW and let me know?

**Comment by petercpg** [comment]
This is a wrong translation indeed, I just corrected it on Pontoon. 

https://pontoon.mozilla.org/zh-TW/firefox-for-android/all-resources/?search=%251%24d+selected&status=translated&string=198758

**Comment by jackyzy823** [comment]
@petercpg  thanks for your correction. and also please don't forget zh-CN , thanks.

**Comment by flodolo** [comment]
He's the translator for zh-TW, not zh-CN. I put a suggestion in zh-CN, but it hasn't been reviewed yet.

**Comment by haiwx** [comment]
已修正，最近有些忙，抱歉。

**Comment by flodolo** [comment]
https://github.com/mozilla-l10n/android-l10n/commit/fe1c687e5e309cf5fb32829e7371dac0d26e99c2#diff-eed0d675698994d6bb7e8e301156130cd4e27e8c5e997a214391d8c90e8a6bd5R787
