### ISSUE TITLE
[Bug]: Homepage Links

### ISSUE THREAD

**Issue by BrokenShoeLace** [mozilla-mobile/fenix#25141]
### Steps to reproduce

Open Firefox 100.1.1
Click the ... and click Settings
Click Homepage
Turn on top option
Make sure the checkbox is unticked
Turn off the other 3
Visit a few pages and links to recent visited sites are now on the hompage even though those options are disabled and will always be disabled

### Expected behaviour

No visited links to appear on the homepage.

### Actual behaviour

See the steps above

### Device name

Samsuns S21 Ultra 5G

### Android version

Android 12 1st May 2022 patch)

### Firefox release type

Firefox

### Firefox version

100.1.1

**Comment by LaurentiuApahideanSV** [comment]
This was changed to match desktop behavior as per @kbrosnan comment: https://github.com/mozilla-mobile/fenix/issues/24506#issuecomment-1084208678.
