### ISSUE TITLE
FNX3-16381 ⁃ [Bug] Hide tabs menu when there is no tab opened

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2514]
### Expected behavior
When there is nottab, there is no need to show options like "close tabs", after all there are not tabs to be closed.

### Actual behavior
The tabs menu e exhibited even is there is no tab available.

### Device information
* Android device: Galaxy A5 8.0
* Fenix version: 1.0.1920

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.1.1920 (#11360657), with HTC 10 (Android 8), Google Pixel (Android 9), Sony Xperia Z5 Premium (Android 7.1.1).
