### ISSUE TITLE
change fox logo to purple in push notification

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#25153]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently the logo is grey and boring..the notification seems all boring and does not indicate/highlight it is from firefox

Like your firefox focus browser, (pink fox logo) please change the fox logo color to purple 

### How do you know that this problem exists today? Why is this important?
The push notification will look more pleasing

### Who will benefit from it?
All users

![Screenshot_20220507-155355846 (1)](https://user-images.githubusercontent.com/58127841/167250377-7cb23a23-6480-492c-84a5-2cafe1605299.jpg)

**Comment by kbrosnan** [comment]
Purple is a Focus color we won't be using that in Fenix.

**Comment by sheikh-azharuddin** [comment]
> Purple is a Focus color we won't be using that in Fenix.

Firefox focus is using pink color logo not purple
