### ISSUE TITLE
firefox refuses to load any imgur image in private tab.

### ISSUE THREAD

**Issue by DontTheyNeedYourhelp** [mozilla-mobile/fenix#25157]
![Screenshot_20220507-184738_Firefox](https://user-images.githubusercontent.com/75945163/167274278-ee8e1aa7-b903-4636-a71a-547ceb68660a.jpg)
For some reason, whenever I visit imgur in a private tab in firefox, it refuses to show the image.

**Comment by kbrosnan** [comment]
Duplicate bz-1742344
