### ISSUE TITLE
[Bug]: live.foli.fi location permission resets to denied

### ISSUE THREAD

**Issue by ilmaisin** [mozilla-mobile/fenix#25150]
### Steps to reproduce

1. Go to live.foli.fi
2. Tap the "current location" button
3. Close the browser
4. Open the browser again
5. Navigate back to live.foli.fi and tap the current location button

### Expected behaviour

It should focus on the current gps location.

### Actual behaviour

The site complains that it cannot get access to location. The permission has been set to denied. Changing it back to "allowed" from Firefox settings helps for a while, but after browser restart it is denied again.

I have only observed the problem to reproduce for this site only. Other sites work fine.

### Android version

11

### Firefox release type

Firefox

### Firefox version

99.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20404)

**Comment by zevelorgani** [comment]
Similar issue on www.olg.ca with FF 106.1.0 on Android 10
Except that I explicitly set the permission to "allowed" and it is rest to "denied" during the browsing session (without restarting FF)

**Comment by zevelorgani** [comment]
Opened #27802

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813230

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
