### ISSUE TITLE
"Customize homepage" behavior broken in latest release

### ISSUE THREAD

**Issue by pabrown1975** [mozilla-mobile/fenix#25163]
In previous versions the home screen had the option to display "top sites" (as tiles with a pin icon).  In the latest versions, there is only the option to display "shortcuts," which does include top sites but also **everything in the browser history**, which is not useful.  The home page just fills up with random noise.  This behavior occurs **even when "recently visited" is not checked** in the "customize homepage" options.

Steps to reproduce:
- Customize homepage
- Unselect all options except for "shortcuts"
- Visit a site
- Go back to homepage
- Observe that link to site is now shown in shortcuts

**Comment by tactical-snail** [comment]
Yeah I also find it annoying. In earlier versions, if you turned off shortcuts it didn't show history shortcuts but showed pinned shortcuts. But in the latest release turning off shortcuts removes both shortcuts altogether.

**Comment by sflorean** [comment]
@pabrown1975 thank you for filing this! The behavior was changed here #23159, meaning this bug is expected behavior. Please log a feature request.

**Comment by jawz101** [comment]
How can I turn this off?

**Comment by pras92** [comment]
> The behavior was changed here #23159, meaning this bug is expected behavior.

Clearly, Top sites (manually pinned sites) and history (automatic logs from history pages) shouldn't have been merged while implementing a toggle for "Shortcuts".
