### ISSUE TITLE
ae728a09-c7eb-4eeb-9274-f6793bc266f4 <native crash>  * Socorro: https://crash-stats.mozilla.org/report/index/bp-c47fc38c-5e85-450a-af10-ae00e0220509 ---- <native crash>

### ISSUE THREAD

**Issue by akalmaty** [mozilla-mobile/fenix#25168]

**Comment by kbrosnan** [comment]
This looks like a local crash ID from logcat. There is no way to connect that to a submitted crash report. We will need a crash ID that ends with the date that the crash was submitted. See https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information for steps.
