### ISSUE TITLE
`handleDeleteAbnormal` unit test intermittently failing

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25167]
Seen in https://github.com/mozilla-mobile/fenix/pull/25165#issuecomment-1120699709

`test-debug` [failed because](https://firefoxci.taskcluster-artifacts.net/ZqEL4UaMSZ-Hg-0LR4Unfg/0/public/reports/test/testDebugUnitTest/classes/org.mozilla.fenix.library.historymetadata.controller.HistoryMetadataGroupControllerTest.html#handleDeleteAbnormal)
> org.mozilla.fenix.library.historymetadata.controller > HistoryMetadataGroupControllerTest > handleDeleteAbnormal
```
java.lang.AssertionError: Verification failed: call 4 of 4: PlacesHistoryStorage(#3044).deleteVisitsFor(eq(firefox.com), any())). Only one matching call to PlacesHistoryStorage(#3044)/deleteVisitsFor(String, Continuation) happened, but arguments are not matching:
[0]: argument: mozilla.org, matcher: eq(firefox.com), result: -
[1]: argument: continuation {}, matcher: any(), result: +
```

&nbsp;

Seems like [`handleDelete` dispatches an action to hide the items from the screen](https://github.com/mozilla-mobile/fenix/blob/f028dbc03bae8644f2538c7d04f3821b30159e7c/app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt#L136) then [on a separate coroutine actually delete the items](https://github.com/mozilla-mobile/fenix/blob/f028dbc03bae8644f2538c7d04f3821b30159e7c/app/src/main/java/org/mozilla/fenix/library/historymetadata/controller/HistoryMetadataGroupController.kt#L147-L161).
We'll need to somehow wait for the actual removal (that is being tested) to happen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20417)

**Comment by MatthewTighe** [comment]
I'm still familiarizing myself with the new coroutine testing setup, but I'm wondering if the issue relates to either the IO dispatcher being different than the test dispatcher, or perhaps the use of `UnconfinedTestDispatcher`?
