### ISSUE TITLE
92d05f1d-5daa-4008-99d0-2ab991b93ca9 <native crash>  * Socorro: https://crash-stats.mozilla.org/report/index/bp-68347031-0cc1-4fcd-8bf9-ef8260220429 ---- <native crash>

### ISSUE THREAD

**Issue by akalmaty** [mozilla-mobile/fenix#25169]

**Comment by kbrosnan** [comment]
This looks like a local crash ID from logcat. There is no way to connect that to a submitted crash report. We will need a crash ID that ends with the date that the crash was submitted. See https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information for steps.

**Comment by akalmaty** [comment]
Спасибо большое. Через 3-4 часа исправилось. Сейчас все работает.
Спасибо, что не оставляете пользователей без помощи и внимания.


пн, 9 мая 2022 г., 21:40 Kevin Brosnan ***@***.***>:

**Comment by kbrosnan** [comment]
User says that this stopped happening.
