### ISSUE TITLE
[Bug]: Main Menu: Stop/Reload icon is not updated when the menu is open

### ISSUE THREAD

**Issue by phd** [mozilla-mobile/fenix#25166]
### Steps to reproduce

1. Start loading a page (that takes some time to load)
2. Open the Main Menu: it shows the Stop button ("X")
3. Wait for the page to load (progress bar disappears)
4. Check the Stop/Reload button

### Expected behaviour

Stop/Reload button now acts as Reload, and so its icon should change to Reload.

### Actual behaviour

Stop/Reload button now acts as Reload, but its icon still shows Stop ("X").
You need to close and reopen the Main Menu to see the updated icon for this button.

### Device name

Samsung A52s

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

100.1.1
103.2.0
104.2.0
105.0b6
106.0a1
106.1.0
108.0a1

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20416)

**Comment by SoftVision-LorandJanos** [comment]
Hi @phd! Thank you for your report!
I was not able to reproduce your issue using the latest builds:
- latest Nightly 102.0a1 (2022-05-11)
- latest Beta (101.0.0-beta3)
- latest Release (100.1.2RC)

Device used: Google Pixel 4 (Android 12).

Please see if you also reproduce with the latest version(s) of the browser. Preferably with a clean profile.
If you still reproduce it, please share a video about it. Thank you!

**Comment by phd** [comment]
Release 100.1.1:

https://user-images.githubusercontent.com/41565539/168412100-219cdb7f-7bb4-4822-8dff-7aeeb3cdde76.mp4

**Comment by phd** [comment]
This issue is still present in Firefox 103.2.0.

**Comment by phd** [comment]
Still occurs in 104.2.0, beta 105.0b6 and nightly 106.0a1, just like in the attached video.

**Comment by phd** [comment]
Still 108.0a1

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812821

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
