### ISSUE TITLE
Intermittent debug(T) - org.mozilla.fenix.search.SearchFragmentStoreTest - Updating SearchFragmentState from SearchState - shortcuts disabled

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#25170]
### Firebase Test Run:
Provide a Firebase test run report link here showcasing the problem
### Stacktrace:
```
  TEST: Updating SearchFragmentState from SearchState - shortcuts disabled
  FAILURE

org.junit.ComparisonFailure: expected:<[Engine B]> but was:<[eBay]>
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/5f4ba5e3494659104b7e0ac7cf697a5d8ff4bfd7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20420)

**Comment by Mugurell** [comment]
Seen this also in https://github.com/mozilla-mobile/fenix/pull/24501/checks?check_run_id=6373454375.
https://firefoxci.taskcluster-artifacts.net/FAmfnbYyRdS6mIRvStp7NQ/0/public/reports/test/testDebugUnitTest/index.html

Two tests failed: 
> SearchFragmentStoreTest. Updating SearchFragmentState from SearchState
> SearchFragmentStoreTest. Updating SearchFragmentState from SearchState - shortcuts disabled

**Comment by Mugurell** [comment]
Saw this now again in https://firefoxci.taskcluster-artifacts.net/eOHHlf3dSE6C4ZrIbviC1A/0/public/reports/test/testDebugUnitTest/index.html

Two tests failed: 
> SearchFragmentStoreTest. Updating SearchFragmentState from SearchState
> SearchFragmentStoreTest. Updating SearchFragmentState from SearchState - shortcuts disabled
