### ISSUE TITLE
[Bug]: Update the Sentry base URL to use the new instance

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#25183]
We're still using the old Sentry base URL for the crash reporter UI [here](https://github.com/mozilla-mobile/fenix/blob/72b9e7e1747b547640f55646bb0582fe00a4e8f3/app/src/main/java/org/mozilla/fenix/components/Analytics.kt#L149=). 

So when a user clicks on the Sentry link in the crash reporter UI, it will try to load the crash ID at the wrong cloud instance.

Old: `https://sentry.prod.mozaws.net/operations/{project_name}`
**New**: `https://sentry.io/organizations/mozilla/issues/?project={project_id}`

Before, we appended the project name to the end of the base URL:
- Release: `/fenix-fennec`
- Beta: `/fenix-fennec-beta`
- Nightly: `fenix`

Now (**new**), each project now has an integer instead of a project string:
- Release: `6375561`
- Beta: `6295551`
- Nightly: `6295546`

An example constructed URL for beta would be: `https://sentry.io/organizations/mozilla/issues/?project=6295551&query=a27d4fc0a8ba4c229a6136e3982a9e7c`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20426)

**Comment by jonalmeida** [comment]
cc: @Amejia481 for reference.

**Comment by cschanaj** [comment]
Hi, I created https://github.com/mozilla-mobile/fenix/pull/25323  but I am not sure how to test it. Is there any suggestion?
