### ISSUE TITLE
[Bug]: The default browser banner is not auto dismissed after a certain number of views in RC 100.1.2

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25186]
### Steps to reproduce

Preconditions:

Make sure Firefox RC 100.1.2 is not set as Default browser in Device settings.

STR:
1. Install and launch Firefox RC 100.1.2.
2. Verify the default browser banner is displayed on homepage.
3. Open a tab and return on the homepage. 
4. Repeat Step 3 several times.
5. Observe if the default browser banner is auto dismissed after 5 views.

### Expected behaviour

The default browser banner is auto dismissed after being viewed 5 times. 

### Actual behaviour

In Firefox RC 100.1.2, the default browser banner is evergreen and not auto dismissed after a certain number of views, compared to Nightly and Beta 101.0.0-beta.3 where the banner is auto dismissed after being viewed 5 times. 

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

100.1.2

### Additional information

Note that sometimes, after step 2, the prompt will only be displayed after 3-4 restarts.

**Comment by Amejia481** [comment]
Thanks for reporting :)
At the moment, we have two behaviors of the default browser cards:

* Provided by the messaging framework (only available in Beta 102 and nightly),it  hides after some numbers of views.
* The one no provided by the messaging framework only available in release 100.1.2, this one doesn't hides after some numbers of views.

Hopefully by the next release, we will only have the behavior provided by the messaging framework on all releases.

I think we could close this ticket, please feel free to re-open if needed.
