### ISSUE TITLE
[Bug]: The Firefox Homepage Messaging Banner is still displayed after Fenix is set as default browser until a restart is made

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#25187]
### Steps to reproduce

Preconditions: Make sure Fenix is not set as Default browser in Device settings.
1. Launch Fenix;
2. Navigate to the Homepage;
3. Tap the "Set as default" button from the Firefox Homepage Messaging Banner;
4. Set Firefox as the default browser application.

### Expected behaviour

The Firefox Homepage Messaging Banner should be dismissed.

### Actual behaviour

The Firefox Homepage Messaging Banner in not dismissed and a restart of Firefox is needed.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

100.1.2

### Additional information

https://user-images.githubusercontent.com/50983519/167637990-1fe6e1ab-fd41-45d0-b156-67c5b3165d29.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20429)

**Comment by delia-pop** [comment]
Verified as fixed on the latest RC 100.3.0 with Motorola Moto G30 (Android 11) and Google Pixel 6 (Android 13). After selecting Fenix as default app using the banner, the messaging banner is dismissed right away.
