### ISSUE TITLE
[Bug]: Find in page count displays negative number

### ISSUE THREAD

**Issue by plfstr** [mozilla-mobile/fenix#25195]
### Steps to reproduce

+ Navigate to a URL.
+ Menu > Find in page
+ Search for a character
+ Count total sometimes displaying ‘0/-1’ (despite that character in the page) OR ’N/-1’ (N being a number found)

I noticed it on https://html.spec.whatwg.org searching for ‘>‘, but was also able to reproduce on other random tabs. 

### Expected behaviour

The total found should display.

### Actual behaviour

+ ‘-1’ is not a valid total. 
+ ‘0/-1’ is (sometimes) not the correct number of characters found.
+ ‘N/-1’ (N being number found). 
+ Pressing the prev/next arrows can sometimes fix the total or show a negative number.
+ Sometimes the feature works perfectly, correctly displaying ‘1/23’ etc.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

100.1.1

**Comment by kbrosnan** [comment]
duplicate #19369
