### ISSUE TITLE
[Bug][Telemetry]: No ping is registered when dismissing the default browser banner on RC 100.1.2

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25194]
### Steps to reproduce

1. Launch Fenix and observe the mobile message on homepage.
2. Tap on the "X" icon on the right corner of the mobile message.
3. Send Fenix in background.
4. Check the https://debug-ping-preview.firebaseapp.com/ for the triggered pings or the Android Studio logcat;

### Expected behaviour

A ping containing "message-dismissed" should register when dismissing the prompt.

### Actual behaviour

No ping is registered when dismissing the prompt.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox

### Firefox version

100.1.2

**Comment by Amejia481** [comment]
Thanks for reporting :) 
I noticed we intentionally removed this event on the last renewable metric process https://github.com/mozilla-mobile/fenix/pull/23786/

I'll close the ticket please feel free to reopen if it's need :)
