### ISSUE TITLE
[Bug]: The Firefox Homepage Messaging Banner is still displayed when Fenix is already set as default browser on Android 5 device

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25192]
### Steps to reproduce

Preconditions:

Make sure Fenix is set as Default browser in Device settings.

STR:

1. Install and launch Fenix.
2. Dismiss the Onboarding tour.
3. Verify if the default browser banner is displayed on homepage.
4. Restart Fenix several times.
5. Verify if the default browser banner is displayed on homepage.

### Expected behaviour

The default browser banner is not displayed on homepage when the app was already set as default browser is device settings.

### Actual behaviour

After setting Fenix as set as default browser is device settings and launching Fenix for the first time, the default browser banner is displayed on homepage. 
It was noticed that if the banner is not displayed after launching the app, it will become available after performing a restart.
Moreover, if opening a tab and returning to homepage the banner will dismiss the banner, restarting Fenix again will cause the banner to reappear. 

### Device name

Huawei MediaPad M2

### Android version

Android 5.1.1.

### Firefox release type

Firefox Beta

### Firefox version

Beta 101.0.0-beta.3

### Additional information

This issue was only encountered on this specific device with Android 5.
The issue is also reproducible when updating the app to the latest version, for existing users.

https://user-images.githubusercontent.com/89388888/167672534-3bfce4a2-362c-42f9-804a-32152b10a330.mp4

https://user-images.githubusercontent.com/89388888/167672072-4433ae9f-aae4-4edc-bd34-c759247affee.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20432)

**Comment by sheikh-azharuddin** [comment]
Android 5? 😅
