### ISSUE TITLE
[Bug][Telemetry]: No ping is registered when the Firefox Messaging Banner is shown

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#25193]
### Steps to reproduce

Preconditions: Make sure Fenix is not set as Default browser in Device settings.

1. Launch Fenix;
2. Navigate to the Homepage;
3. Observe the Firefox Messaging Banner;
4. Check the https://debug-ping-preview.firebaseapp.com/ for the triggered pings or the Android Studio logcat.

### Expected behaviour

A ping should register when the Firefox Messaging Banner is shown.

### Actual behaviour

No ping is registered when Firefox Messaging Banner is shown.

### Device name

OnePlus 6T

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

100.1.2

### Additional information

[Glean Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-test)

**Comment by Amejia481** [comment]
Thanks for the report.
For the version [that we have in the release](https://github.com/mozilla-mobile/fenix/issues/25186#issuecomment-1122460731) `100.1.2`, we were not reporting when the message was shown. Additionally, just for reference we intentionally removed all the telemetry events related default browser card for 100.1.2 on the last renewable metric process https://github.com/mozilla-mobile/fenix/pull/23786

I'll close the ticket please feel free to reopen if it's need :)
