### ISSUE TITLE
[Meta] Dark Mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#252]
Parent: #240

**Comment by bbinto** [comment]
For TRIAGE: This should probably go into milestone 3 backlog, please size first though and indicate dependencies (planned currently for milestone 3 or 4)

**Comment by yoasif** [comment]
I had previously opened #208 and #209 but I was wondering whether this was a ticket for what Samsung Internet calls "Night Mode" -- where page _content_ is darkened -- #208 and #209 talk specifically about the browser chrome not the content.

#240 says "Dark Mode (Theme)", so I'm not sure you have "night mode" logged. Can we re-purpose this ticket for that or should we create a new one?

**Comment by sblatz** [comment]
I believe this ticket is still waiting on UX. Hard to breakdown without it, and I'm not sure if it includes darkening of web content.

I will also add #209 as a child of #240 as that should be included as well :)

**Comment by bbinto** [comment]
As per [comment](https://github.com/mozilla-mobile/fenix/issues/240#issuecomment-473414507), we might pull this back into a Battery saving story after MVP, however it should land for MVP as an individual feature.

**Comment by mheubusch** [comment]
Engineering - please review the items on this spreadsheet - this is a punchlist showing fit and finish issues blocking feature completeness.
https://docs.google.com/spreadsheets/d/11iULib1ePcpadfibEW_9wEVX5aBiRsadMSi84fsJ9KM/edit?usp=sharing
