### ISSUE TITLE
Set foreground tab's GeckoSession priority to PRIORITY_HIGH

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25212]
Fenix needs to use GV's `setPriorityHint` API to set the foreground tab's `GeckoSession` priority to `PRIORITY_HIGH` and background tabs' `GeckoSession` priority to `PRIORITY_DEFAULT`. These priorities will tell Android's OOM killer to please kill not kill processes that the foreground tab needs.

In v100 and v101, GV set the priorities automatically, but starting in v102, Fenix will need to set the priorities manually.

@calumozilla added the `setPriorityHint` API in https://bugzilla.mozilla.org/show_bug.cgi?id=1764998.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20444)

**Comment by csadilek** [comment]
Adding some details on how I think we should implement this:

The [`WebExtensionMiddleware`](https://github.com/mozilla-mobile/android-components/blob/main/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/WebExtensionMiddleware.kt) in A-C already does something very similar to what we need here. When an `engineSession` (a GeckoSession) is associated with (linked to) the selected tab we call `markActiveForWebExtensions(true)`. he gecko session of previously selected tab will get a call to `markActiveForWebExtensions(false)`. When a engine session is unlinked we also we make sure to call  `markActiveForWebExtensions(false)`.

We should add a new middleware that follows the same pattern, but calls `setPriorityHint(PRIORITY_HIGH)` for the selected tab's gecko session, and `setPriorityHint(PRIORITY_DEFAULT)` for everything else, even the previously selected tab. The reason we want a separate middleware is to make it easy to run an experiment for this functionality i.e., for the control branch we would not add the middleware to the store, for the treatment branch we would.

**Comment by csadilek** [comment]
The new middleware e.g., `EngineProcessPriorityMiddleware` should be added to A-C, so we can reuse it in Focus. Then conditionally be added to the store in Fenix based on the experiment.

The `setPriorityHint` function will need to be exposed on the `EngineSession` interface in A-C.

**Comment by calumozilla** [comment]
@Amejia481 yup, set the priority based on the active tab. Previously on Geckoview it was set in `mobile/android/modules/geckoview/GeckoViewWebExtension.jsm` `setTabActive`. (https://phabricator.services.mozilla.com/D145789)

**Comment by Amejia481** [comment]
Awesome thanks for the clarification :)

**Comment by Amejia481** [comment]
Addressed on https://github.com/mozilla-mobile/fenix/commit/d2c1893cf90aed3bdfb33e0cea8763a68317c5e4
