### ISSUE TITLE
Intermittent UI test failure - multipleBookmarkDeletionsTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#25219]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5883191455224242839/details?stepId=bs.87b3d9b2a538dfd4&testCaseId=1&query=et.493b2b8900c692ae&deeplink=true
### Stacktrace:
Crashed.
`Uncaught exception handled: 
05-11 14:37:03.711: E/ExceptionHandler(11834): java.lang.NullPointerException
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at org.mozilla.fenix.library.bookmarks.BookmarkFragment.getBookmarkInteractor(BookmarkFragment.kt:70)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at org.mozilla.fenix.library.bookmarks.BookmarkFragment.refreshBookmarks(BookmarkFragment.kt:290)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at org.mozilla.fenix.library.bookmarks.BookmarkFragment.access$refreshBookmarks(BookmarkFragment.kt:63)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at org.mozilla.fenix.library.bookmarks.BookmarkFragment$refreshBookmarks$1.invokeSuspend(Unknown Source:14)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at android.os.Handler.handleCallback(Handler.java:938)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:7)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.action.Tap.access$100(Tap.java:1)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:3)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:6)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:22)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at android.os.Handler.handleCallback(Handler.java:938)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at android.os.Looper.loop(Looper.java:223)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at java.lang.reflect.Method.invoke(Native Method)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-11 14:37:03.711: E/ExceptionHandler(11834): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f40ea22, Dispatchers.Main]
05-11 14:37:03.720: I/mozac/CrashReporter(11834): Received crash: UncaughtExceptionCrash(timestamp=1652305023712, throwable=java.lang.NullPointerException, breadcrumbs=[Breadcrumb(message=onCreate(), data={recreated=false, intent=android.intent.action.MAIN, instance=227780807}, category=HomeActivity, level=INFO, type=DEFAULT, date=Wed May 11 14:36:33 PDT 2022), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:36:34 PDT 2022), Breadcrumb(message=onStart(), data={instance=227780807}, category=HomeActivity, level=INFO, type=DEFAULT, date=Wed May 11 14:36:34 PDT 2022), Breadcrumb(message=onResume(), data={instance=227780807}, category=HomeActivity, level=INFO, type=DEFAULT, date=Wed May 11 14:36:34 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:36:46 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkAddFolderFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:36:48 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:36:49 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkAddFolderFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:36:50 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:36:51 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkAddFolderFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:36:53 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:36:54 PDT 2022), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed May 11 14:37:01 PDT 2022)], uuid=f00c7acb-0588-43d7-b73d-0fbbdaae0376)`
### Build: 
5/12 main
Started with https://github.com/mozilla-mobile/fenix/pull/25211

Logged crash report in https://github.com/mozilla-mobile/fenix/issues/25220

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20451)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5659912606256936879/executions/bs.4e02603c05258060/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5776357103126378758/executions/bs.4f7f298075f1c99a/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
