### ISSUE TITLE
[Bug] Downloads: show how much has downloaded and how much times it takes

### ISSUE THREAD

**Issue by StrangerE** [mozilla-mobile/fenix#25210]
I can't see how much has downloaded and how much times it takes.... Full trash for download.... I can't see any file in download option when it's download running...... Plz fix it quickly..also enable background download... It is hard to say that low quality n browser also have those feature...i am facing irritating and the problem very much.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20443)

**Comment by cpeterso** [comment]
I thought Firefox handed the downloads off to Android's download manager. Does it show the current downloads and how much time is remaining?

**Comment by marcel263** [comment]
See issue #23118 for people wanting to collaborate on this
