### ISSUE TITLE
[Bug]: Touch target - consider making "Search engine" clickable item larger

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#25217]
### Steps to reproduce

1.Open Fenix.
2. Tap on URL bar.
3. Scan the page.

### Expected behaviour

No suggestions are made. 

### Actual behaviour

<img src="https://user-images.githubusercontent.com/58466444/168077068-a52a03ed-1dbe-4542-a33c-2980ab75335e.jpg" width="300" height="550" />

### Device name

Samsung A32

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

101.0.0-beta.3, Nightly 102.0a1

**Comment by kbrosnan** [comment]
This UI is going away in the near future with unified search.
