### ISSUE TITLE
[Bug]: custom tab cross button not visible

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#25246]
### Steps to reproduce

I clicked a link from upstox app and it opened custom tab but the cross button was not visible as it was white..
Seems some bug

### Expected behaviour

The cross button should be black to be visible

### Actual behaviour

Button is white

### Device name

asus rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Additional information

![Screenshot_20220516-094905730 (1)](https://user-images.githubusercontent.com/58127841/168520983-3e54ad15-da56-4e30-a4c5-03f9acefe9ce.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20460)

**Comment by Mugurell** [comment]
Looks similar to https://github.com/mozilla-mobile/focus-android/issues/6792.

**Comment by SoftVision-LorandJanos** [comment]
Hi @sheikh-azharuddin! Thanks for your report!
I only have "back" button whenever I access any page through custom tab, so I wasn't able to reproduce your issue. And the "back" button is correctly displayed, very visible, black on white.
Could you maybe share the exact link you were accessing? Maybe share a video of your issue? Thank you!
Device used: Google Pixel 4 (Android 12).
Firefox version: latest Nightly 102.0a1 (2022-05-17).

**Comment by sheikh-azharuddin** [comment]
> Hi @sheikh-azharuddin! Thanks for your report! I only have "back" button whenever I access any page through custom tab, so I wasn't able to reproduce your issue. And the "back" button is correctly displayed, very visible, black on white. Could you maybe share the exact link you were accessing? Maybe share a video of your issue? Thank you! Device used: Google Pixel 4 (Android 12). Firefox version: latest Nightly 102.0a1 (2022-05-17).

I am clicking the link from inside an app upstox which is opening a custom tab

**Comment by sheikh-azharuddin** [comment]
When firefox theme is set to dark, then only the cross button is visible

![Screenshot_20220517-132343565](https://user-images.githubusercontent.com/58127841/168759217-4d337471-0192-453a-a5da-61bf1dbe01e0.jpg)
