### ISSUE TITLE
Inconsistent share menu

### ISSUE THREAD

**Issue by intrnl** [mozilla-mobile/fenix#25257]
### Steps to reproduce

1. Open a website containing a link
2. Tap and hold the link and tap Share link
3. Close, now try sharing the current page from the menu

### Expected behaviour

Both options should open the same share menu

### Actual behaviour

It doesn't, the share current page option opens up a custom share menu, while the share link option opens native share menu.

### Device name

Poco M3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20470)

**Comment by intrnl** [comment]
This is currently preventing me from sending a link to another device without opening it first, unless #1523 is resolved.

**Comment by SoftVision-LorandJanos** [comment]
Hi @intrnl! Thank you for the report!
I could reproduce the behavior you described.
Tested with the latest Nightly 102.0a1 (2022-05-18T17:12:12.001240).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Google Pixel 4 (Android 12).

**Comment by intrnl** [comment]
This also happens on a CCT/custom tab, where if you open a link from Twitter app it launches Firefox on a special mode.

The `Share via...` menu item here doesn't open Firefox' share menu, it opens the system's share menu instead.

![Screenshot_2022-10-10-11-42-30-73_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/20620901/194800428-866d30b0-3d4e-4b9d-aaf8-71992799665e.jpg)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809781

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
