### ISSUE TITLE
NoCollectionsViewHolder to Compose caused 333ms regression in cold main start up (5/10/22)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#25253]
From our nightly regression detection:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/759372/168681799-c281fe3f-2bf1-432b-ac4d-5b4130c5e5d4.png">

- 5/9: 1.464s
- 5/10: 1.797s

We regressed 333ms – we should find out the cause and address it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20468)

**Comment by Mugurell** [comment]
Following the above graph [these are all the merged between 8-10 of May](https://github.com/mozilla-mobile/fenix/pulls?q=is%3Apr+is%3Aclosed+merged%3A2022-05-08..2022-05-10+base%3Amain+sort%3Aupdated-desc+).
