### ISSUE TITLE
[Bug]: recently visited bookmarks shouldn't display below pinned bookmarks on new tab page

### ISSUE THREAD

**Issue by user4815162342** [mozilla-mobile/fenix#25254]
### Steps to reproduce

1. Go to settings, homepage
2. Make sure recently visited sites are turned off
2. Open a new tab
3. Recently visited shortcuts still appear alongside pinned shortcuts

### Expected behaviour

Only pinned shortcuts should appear on the new tab page. This was how it worked in older versions.

### Actual behaviour

After the recent update, shortcuts from recent history appear next to the pinned shortcuts on the new tab page.

### Device name

moto g play

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

100.1.2

### Additional information

![Screenshot_20220511-110815-231](https://user-images.githubusercontent.com/2445585/168692111-2d432ac4-fab3-4c2c-a663-34084ee46998.png)

The four shortcuts on the top we're pinned, and have always shown. The four on the bottom are from my history, and they did not show up until the recent update. 

I need some way to prevent them from showing, to keep my new tab page from being too cluttered.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20469)

**Comment by LaurentiuApahideanSV** [comment]
This was changed to match desktop behavior as per @kbrosnan comment: https://github.com/mozilla-mobile/fenix/issues/24506#issuecomment-1084208678.

**Comment by SoftVision-LorandJanos** [comment]
I was able to reproduce this issue on the latest Nightly 102.0a1 (2022-05-23) build.
Device used: Google Pixel 4 (Android 12).
Since after turning recently visited sites off from settings shouldn't display the recently visited pages on homescreen, I will reopen this ticket.

**Comment by chloekek** [comment]
If this matches the desktop behavior, then that means the desktop version is likewise bugged.

**Comment by kbrosnan** [comment]
Recently visited is a heading on the homepage. It is not intended to have any other effect. This is the same as the other bugs.

![Screenshot_20220601-204435](https://user-images.githubusercontent.com/250273/171524494-1cea6050-0952-43bf-a787-4158d1db6dd6.jpg)

**Comment by user4815162342** [comment]
@kbrosnan The toggle in settings says "recently visited". This implies that it will not display any "recently visited" links on my home page. While it does turn off the section you highlighted, it does not hide the recently visited bookmarks that appear after my pinned shortcuts. 

So if you are saying that the recently visited setting has nothing to do with the other shortcuts, then there are still two problems:

1) The "recently visited" setting is misleading, as it does not turn off *all* recently visited bookmarks on the new tab page.
2) There should be an additional setting that turns off the other shortcuts so that only pinned shortcuts show up. 

Perhaps this should be a feature request? My desktop Firefox has a bookmarks toolbar which I can customize exactly as I like. This is not available on Firefox android as it would not fit in the user interface. In order to make Firefox android match the functionality of Firefox desktop, there should be a way to customize the home page as a bookmarks toolbar, exactly the way I like.

**Comment by kbrosnan** [comment]
The shortcuts section behavior modeled after desktop's new tab page, not the bookmarks toolbar. There are some notes at https://connect.mozilla.org/t5/discussions/android-v100-history-update/m-p/6789
