### ISSUE TITLE
Add a new multipreview annotations for Composables

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25258]
Android Studio Dolphin (now Beta) comes with support for [Compose Multipreview Annotations](https://developer.android.com/studio/preview/features#compose_multipreview_annotations).

We can use this feature to ensure an easier way of generating a standard set of previews for all composables covering:
- all thems - light / dark / private
- various device forms and sizes
- ltr and rtl

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20471)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810843

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
