### ISSUE TITLE
Intermittent UI test failure - verifyContextMixedVariations

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#25265]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8564908508280342891/executions/bs.878f490e971d073f/test-cases
### Stacktrace:
Test instrumentation process crashed. Check org.mozilla.fenix.ui.ContextMenusTest#verifyContextMixedVariations.txt for details
### Build: 
https://github.com/mozilla-mobile/fenix/commit/c09f899da47a08faddf7fd18a1f0daa57fc3a55e

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20482)

**Comment by AaronMT** [comment]
https://github.com/mozilla-mobile/fenix/issues/24047

**Comment by AndiAJ** [comment]
Failed 1x on 5/17 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8564908508280342891/executions/bs.878f490e971d073f/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8564908508280342891/executions/bs.b24281f9e00671e3/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closing in favour of #24978
