### ISSUE TITLE
show advance security details of website

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#25260]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Currently on clicking the security icon of a website , it is showing only the message connection is secure however like other chromium browsers it does not show advance security information such as cipher suite used or can't view the certificate information/details

### How do you know that this problem exists today? Why is this important?
As a firefox focussed browser, it should show all the security parameters of any website..a functionality which is present in chromium browsers!

### Who will benefit from it?
Advance users who checks website details

![Screenshot_20220517-131849039 (1)](https://user-images.githubusercontent.com/58127841/168760129-dbdf55dd-1ab8-4c46-bd9e-2edc08405c75.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20473)

**Comment by cpeterso** [comment]
For comparison, Firefox desktop shares some of this advanced security information (such as TLS version) in address bar’s lock icon > “Connection secure” menu item > “More information” menu item.
