### ISSUE TITLE
Refactor toShortUrl extension function from TabSessionState to String

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#25264]
We landed an extension function for `TabSessionState` that does the same thing in https://github.com/mozilla-mobile/fenix/pull/25242. It's kinda unfortunate, but maybe we should've actually add a `String` extension function instead of `TabSessionState`

_Originally posted by @gabrielluong in https://github.com/mozilla-mobile/fenix/pull/24682#discussion_r875020408_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20479)

**Comment by gabrielluong** [comment]
@Amejia481 @MozillaNoah Any issues with what is described here?

**Comment by MozillaNoah** [comment]
> @Amejia481 @MozillaNoah Any issues with what is described here?

I think this makes sense
