### ISSUE TITLE
Grey softkeys bar displayed after tapping "Go" on keyboard in Bookmarks/History menus.

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25279]
### Steps to reproduce

1. Go to Bookmarks/History.
2. Tap on the magnifying glass.
3. Once the keyboard is invoked, press "Go" on the keyboard (it is not necessary to start typing characters before hitting "Go").
4. Observe the softkeys bar. 

### Expected behaviour

After tapping "Go" on the keyboard, the softkeys bar is displayed without visual defects.

### Actual behaviour

After tapping "Go" on the keyboard, a grey bar is displayed over the softkeys bar. On certain devices (Google Pixel 6 (Android 12), Google Pixel 4 (Android 12)) the softkeys are **not visible**.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 102.0a1 from 05/18

### Additional information

Also reproducible on the latest RC 100.2.0 and Beta 101.beta.5. 
Also reproduced with Motorola Moto G30 (Android 11) and Samsung Galaxy Note10 (Android 11).

Note that the issue is not encountered in the "Language" or "Saved logins" menus.

https://user-images.githubusercontent.com/89388888/169046790-e8eaba50-c772-442c-ac09-1eb5118e615f.mp4

https://user-images.githubusercontent.com/89388888/169046806-d676baca-aa24-4488-882f-0d2c89a0b39f.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21987)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807595

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
