### ISSUE TITLE
[Bug]: window reports wrong scroll Y position (unable to scroll to 0)

### ISSUE THREAD

**Issue by mulahasanovic** [mozilla-mobile/fenix#25278]
### Steps to reproduce

1. Open https://developer.mozilla.org/en-US/
2. Scroll around the page
3. Check window.scrollY value
4. Observe that it's not `0` even if visibly at the top of the page

### Expected behaviour

`window.scrollY` should be `0`

### Actual behaviour

`window.scrollY` is `0.7333333492279053`

### Device name

Pixel 4 API 30

### Android version

Android 11.0

### Firefox release type

Firefox

### Firefox version

100.2.0

### Additional information

Noticed the issue on my latest personal phone Firefox mobile app version from App store on Redmi 8T and some further testing was completed with remote debugging on emulated app (device info).

Things I've tried so far:
* I've tested on Firefox Mobile on my device and on emulator scrolling/dragging completely to the top.
Visually it looks at top (impossible to scroll further top with "finger" or the mouse wheel)
![scrollYdebug](https://user-images.githubusercontent.com/8067014/169012907-ba85364d-63f6-4ece-aa5d-f07b6022f67c.png)
* On emulator I've also tried to scroll with mouse wheel and it never gets to 0. It's usually stuck at `0.7333333492279053`.
* I went on ahead and tested on some other web pages and the problem is there also.
* Tested with the address bar on bottom and on top. Same issue.
* Tried programmatically moving scroll to 0, same.
![image](https://user-images.githubusercontent.com/8067014/169013608-3860eb8c-c7e9-4faf-ac62-170ae240f34b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20500)

**Comment by kbrosnan** [comment]
@mulahasanovic we have a more striped down version of Firefox that can let us know if this is platform work or Fenix team work. If you would try [Geckoview example x86-64](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-x86_64-gcp-opt/artifacts/public%2Fbuild%2Fgeckoview_example.apk), the [x86](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-x86-gcp-opt/artifacts/public%2Fbuild%2Fgeckoview_example.apk) or the [ARM 64-bit](https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.mobile.android-aarch64-gcp-opt/artifacts/public%2Fbuild%2Fgeckoview_example.apk) build and let us know if the problem reproduces in it.

**Comment by mulahasanovic** [comment]
On `geckoview` example it "jiggles" when dragging to top, it sometimes lands on `0` sometimes slightly below but moving it programmatically with `window.scrollTo(0,0)` will move it to `0` correctly.

Interestingly the amount it bounces back on `geckoview` is `0.36666667461395264` exactly two times less than release version.

I've also tried it again on `v100.3.0` and this jiggle is present also, it feels like it bounces of top and scrolls back down a bit.
Also the `window.scrollTo(0,0)` will move it to `0` correctly now.

I am not sure if my phone and emulator are enough, if someone else could confirming this it would be great. 😃

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802941

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
