### ISSUE TITLE
Messaging banners are briefly displayed after expiration

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#25280]
https://mozilla-hub.atlassian.net/browse/EXP-2403

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20485)

**Comment by Mugurell** [comment]
QA: is this bug still happening?

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 104.0a1 (2022-07-25) but could not reproduce it. I will mark this issue as fixed.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by Amejia481** [comment]
🎉 !

**Comment by Amejia481** [comment]
Thanks for testing @LaurentiuApahideanSV and @Mugurell to coordinate!
