### ISSUE TITLE
Make a top-level TextButton Composable component

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#25291]
[Specs](https://www.figma.com/file/ujdiReypSypu2GhRgzArea/Android-Components?node-id=1430%3A3433)

Replace the current `TextButton` usages in Wallpaper with the new component.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20507)

**Comment by MozillaNoah** [comment]
@cwzilla, just to confirm for text-only buttons, should the button label _always_ be capitalized?

**Comment by cwzilla** [comment]
@MozillaNoah I think it's safe to say text-only buttons will always be capitalized and the same component can be used in Snackbars.

**Comment by gabrielluong** [comment]
@MozillaNoah just a friendly reminder to close your issues. 🫡
