### ISSUE TITLE
FNX3-16389 ⁃ [Bug] Remove "delete collection" from private browsing homescreen

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2529]
### Steps to reproduce
1. switch to private mode
1. open one tab or more
1. go to home screen

### Expected behavior
The button below the tab(s) has the text "Delete session",  "Close private tabs" or something similar.

### Actual behavior
The button has the text "Delete collection".

It almost looks like it was intentionally changed in #2249 but I don't think this button text makes much sense for closing the private tabs. I know that I can create collections in regular mode and still I was very confused to read "Delete collection" in private mode. "Close private tabs" would be more clear in my opinion.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision a1c6e0127bc2faf2fbaa7c02a1bb62598fa3cfd3

**Comment by topotropic** [comment]
Let's remove the button for now and we will look into re-positioning/designing it post MVP. 

Background: It's potentially confusing to have a button with a destructive action ("Close private tabs")  in the same position, same look and feel, as the "Save to Collection" one in normal mode.

**Comment by vesta0** [comment]
@topotropic I agree with you that "Delete Collection" is just inaccurate and should be removed but perhaps we should keep the button and change the text to "Delete private tabs" to further draw focus to the destructive action of it? One learning from Firefox Focus has been that users really like having that option.

**Comment by cadeyrn** [comment]
If the button will be kept it could be a good idea to implement either a confirmation or an undo option to reduce the data loss risk.

**Comment by yoasif** [comment]
The three dot menu near "Private session" has an option for "Close all tabs" - I don't think it makes sense to invent new language here (if the button is kept) when the three dot menu already contains a good template.

**Comment by klint** [comment]
I like the perfect visibility of the trash button in FF Focus, immediately at hand. Why not have the same in Fenix in private browsing? In my opinion it is too hidden in the tab screens where it resides today.
This way, and as Fenix private browsing mode is persistent, Fenix could be a perfect replacement of Focus (which I actually did on my phone already).

**Comment by cadeyrn** [comment]
In Focus you almost always have only one open tab (multi tab browsing in Focus is very hidden and "special", it's still a single tab browser). The same can't be said about Fenix. So if you use the garbage icon in Focus it's clear that you close the one open tab. But this issue is about a button in Fenix to close *all* tabs, so it's not the same situation and what works for Focus does not necessarily work for Fenix. My expectation with such a button in Fenix would be to close only this one tab.

By the way, this was already discussed in another issue when there was a similar button in Fenix for a few days which was removed then.

**Comment by topotropic** [comment]
I agree that a shortcut to "Close all tabs" is helpful but I'd recommend to review it as part of other open design questions around the home screen (https://github.com/mozilla-mobile/fenix/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22%F0%9F%A6%84+Needs+UX+Feedback%22+label%3AFeature%3AHomeScreen+) and to come up with a better less ambiguous solution then reusing the "save collection" button. The issue I see is that both buttons look the same, are in the same position but have a very different purposes (save, delete).

**Comment by vesta0** [comment]
@topotropic I see your point about having the 2 buttons with opposite functions in the same position. Let's remove it for now and wait for a UX recommendation for post-mvp.

**Comment by abodea** [comment]
Verified as fixed on the latest build **`1.0.1922(Build #11470614 68.0-20190520141152) 5/27`** with **`Samsung Galaxy Note 9(Android 8.1.0).`**
