### ISSUE TITLE
Lower Image Quality for Power Save Mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#253]
Parent: #240

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11488)

**Comment by cpeterso** [comment]
Selecting different image qualities might require new GV APIs. A GV and/or Gecko engineer should probably be involved in the scoping and estimation of this feature.

**Comment by bbinto** [comment]
For TRIAGE: This should probably go into milestone 2 backlog, please size first though and indicate dependencies

**Comment by cpeterso** [comment]
I spoke with maintainers of Gecko's Image decoders ("ImageLib" module owners Timothy Nikkel and Andrew Osmond). They said there aren't any image decoder settings that would be useful for a mobile power-saving mode, short of just disabling image loading. If you have information about techniques used by other browsers, I can share it with them.

**Comment by bbinto** [comment]
As per [comment](https://github.com/mozilla-mobile/fenix/issues/240#issuecomment-473414507), we might pull this back into a Battery saving story after MVP.

Out of scope for MVP.

**Comment by vesta0** [comment]
@cpeterso @bifleming  does this require GV work?

**Comment by cpeterso** [comment]
> @cpeterso @bifleming does this require GV work?

I spoke with maintainers of Gecko's Image decoders. They said there aren't any image decoder settings that would be useful for a mobile power-saving mode, short of just disabling image loading.

Fennec has an "Advanced > Show images" option: "Always", "Only over Wi-Fi", or "Blocked". Fennec's image blocking mode has no way to reload images on the current page. Perhaps the user could selectively load blocked images by tapping on the blocked image placeholder?

If you have information about techniques used by other browsers, I can share it with them. Chrome on desktop has an option to disable image loading. Chrome on Android doesn't, but it has a "Lite Mode" that uses a data compression proxy server:

https://support.google.com/chrome/answer/2392284?co=GENIE.Platform%3DAndroid&oco=1

**Comment by black7375** [comment]
What is also an option to set the value of [Save-Data](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Save-Data) header field to `on`?

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report is closed. I think we would want to do this differently.
