### ISSUE TITLE
Set tokens used for sponsored Pocket stories 

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25311]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-20329

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20515)

**Comment by gabrielluong** [comment]
@Mugurell should this be closed or set for qa-needed?

**Comment by Mugurell** [comment]
Nothing for QA to check, closing with `qa:not-needed`.
