### ISSUE TITLE
FNX3-16392 ⁃ Settings - Persistent link to privacy notice

### ISSUE THREAD

**Issue by mheubusch** [mozilla-mobile/fenix#2531]
As a user, I want to learn about how Mozilla collects data from my use of Firefox Preview so that I understand how I can manage data collection and control the amount of information I share with Mozilla.

Acceptance Criteria
I can access the Privacy Notice any time I use Firefox Preview

**Comment by topotropic** [comment]
Ok, here's how to open a single tab from a Collection:
1. Tap on single tab
2. Site opens
3. When you go back to start screen, new tab is first in list

**Comment by sv-ohorvath** [comment]
3 issues found: #2731, #2724, #2723

**Comment by sv-ohorvath** [comment]
All blocking issues are fixed and closed.
