### ISSUE TITLE
Visiting website with port number provided (but not providing protocol) did nothing.

### ISSUE THREAD

**Issue by Yonle** [mozilla-mobile/fenix#25310]
### Steps to reproduce

Say, You have a local HTTP server in your phone that were listening on port `8080`.

Open Firefox, then go to `localhost:8080` without `http://` or `https://` at beginning of URL.

### Expected behaviour

Should load the website

### Actual behaviour

Do nothing.

### Device name

vivo 1820

### Android version

Android 8.1 Oreo

### Firefox release type

Firefox

### Firefox version

100.2.0 (Build #2015880363)

### Additional information

When you visit `http://localhost:8080`, The website is loaded as intended, but not when you're visit `localhost:8080` without `protocol://`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20514)

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1382709

**Comment by Yonle** [comment]
Seems fixed at 107.2.0 (Build #2015918523), 1490acda7+. Anyone can confirm?

**Comment by csadilek** [comment]
Closing based on comment above. Please re-open if this problem still exists.
