### ISSUE TITLE
[Feature Req: FF android] Preview a Web page without having to navigate to a new tab. 

### ISSUE THREAD

**Issue by iammrigank** [mozilla-mobile/fenix#25324]
Hi,

I am here to make a request for a new feature for FF android mobile app (perhaps for ipad and iPhone OS too). It is to incorporate a page-preview when long pressing a hyperlink in a website. Such a feature is available in many browsers like Brave or Safari (for iPhone).

Any add-on that does it is perfectly fine for me too!

It is most useful to me when reading articles which has tons of secondary info linked along with the main content. In such cases a quick preview saves a lot of time as opposed to say opening the link in a new tab, switch to it, read it, and navigate back to main content.

I hope the ask was clear. 
Thank you!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20520)

**Comment by iammrigank** [comment]
Oh and i did search for a similar issue before creating this one, but couldn't find any. Ty.

**Comment by marcel263** [comment]
Recommended to post such ideas on https://discourse.mozilla.org for exposing the brainstorming to them and gaining community support.

**Comment by iammrigank** [comment]
@marcel263 Thank you for your suggestion. I have created a future request on discourse : https://discourse.mozilla.org/t/feature-request-preview-a-web-page-without-having-to-navigate-to-a-new-tab/97490

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812228

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
