### ISSUE TITLE
Offline page

### ISSUE THREAD

**Issue by FabriceSalvaire** [mozilla-mobile/fenix#25329]
Google Chrome is able to show a page in offline if the page is bookmarked. Thanks to voodoo cache ???

It would be great to implement such a feature properly :
- a button to save the page for offline use
- an offline list of pages to open the page in a new tab

Use case is for example the site https://www.camptocamp.org/routes/1422200/fr/aiguille-du-pelvoux-traversee-des-cols-w-e where users want to be able to read a page without a network connection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20524)

**Comment by sflorean** [comment]
Thank you for filing this! This scenario is already covered in #219, please follow the discussions there.
