### ISSUE TITLE
Think about aligning tab counter and new tab button

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2532]
Fennec has the design element (and @antlam confirmed it was [done intentionally](https://github.com/mozilla-mobile/reference-browser/issues/235#issuecomment-440369397)) where the "+" button on the tabs screen sits at the same position as the tabs button in the address bar, which gives the neat effect that you can double tap the tabs button in order to open a new tab.
It would be nice if we could reintroduce that design element in Fenix, too. (We already have the reload button and the three dots menu sort of aligned again)

**Comment by lime124** [comment]
this should be part of a larger effort to look at some issues we've collected about tabs and homescreen. removing ux label

**Comment by ekager** [comment]
We did this in the homescreen redesign. Closing
