### ISSUE TITLE
[Bug]: Find in page count is 0 / zero, broken during fast usage

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#25322]
### Steps to reproduce

1. Use "Find in page..." function
2. Type a letter or character
3. Hit Prev or Next as fast aa you can

### Expected behaviour

No disruption

### Actual behaviour

Hit count becomes zero after a certain threshold, which is around ~4 per second. Sometimes, the counter resets to a position relative to the previous hit. 

https://user-images.githubusercontent.com/76437842/169640572-12c65cd1-e008-4653-ba08-68ceb57579eb.mp4

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1 (Build #2015880275), 2af9e832c+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20519)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/19369

**Comment by marcel263** [comment]
> Duplicate #19369

dear, the bug is somewhat different in that the numbers reset to zero, and always restore if the user taps more slowly
