### ISSUE TITLE
Settings page transitions doesn't respect Android's reduce motion option

### ISSUE THREAD

**Issue by intrnl** [mozilla-mobile/fenix#25327]
### Steps to reproduce

1. Enable reduce motion/disable animations option in Android's accessibility settings
2. Open Firefox, head to the Settings page
3. Now head to any subpage

### Expected behaviour

Settings subpage should open without any transitions because of the reduce motion option

### Actual behaviour

It doesn't, the pages still does a fade-slide transition anyway.

### Device name

Xiaomi Poco M3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20522)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue Firefox Nightly 102.0a1 2022-05-24 and can confirm is is reproducible.
### Device used:
- Google Plixel 6 (Android 13)

**Comment by intrnl** [comment]
This is still a valid issue

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813754

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
