### ISSUE TITLE
[Bug]: Black Flash when switching to Firefox

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#25334]
### Steps to reproduce

1. Open Firefox and any web page
2. Open any other Android app - I used Google Calculator 
3. Switch to calculator
4. Switch back to Firefox

### Expected behaviour

Page appears.

### Actual behaviour

Firefox flashes black before showing the UI. 

### Device name

moto g pure

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1

### Additional information

https://user-images.githubusercontent.com/152493/169710901-bb6b3329-a8dd-4ae7-ab23-0119a8dcfec2.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20527)

**Comment by yoasif** [comment]
[black flash log](https://github.com/mozilla-mobile/fenix/files/8750063/black.flash.log)

**Comment by amocirean** [comment]
Hello @yoasif , thank you for submitting the issue.
I was able to reproduce it on the latest RC and Nightly.

Device Used: Huawei P40 Lite
Android Version: 10
