### ISSUE TITLE
[Bug]: Homepage showing recently visited even when recently visited is unselected 

### ISSUE THREAD

**Issue by cneuzil** [mozilla-mobile/fenix#25330]
### Steps to reproduce

1. Go to settings
2. Go to Homepage
3. Unselect recently visited
4. Go to the homepage
5. Recently visited sites are shown along with pinned sites 

### Expected behaviour

Only pinned sites should show up on the homepage 

### Actual behaviour

Homepage shows both pinned and recently visited 

### Device name

Pixel 2 and Tab 8+

### Android version

Android 12 on tab 8+, android 11 on pixel 2

### Firefox release type

Firefox

### Firefox version

100.3.1 on tab 8+, 100.3.0 on pixel 2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20525)

**Comment by SoftVision-LorandJanos** [comment]
Hi @cneuzil! Thank you for your reprort! According to [this](https://github.com/mozilla-mobile/fenix/issues/24506#issuecomment-1084208678) comment this behavior is expected. Based on that, I will close this ticket.

**Comment by cneuzil** [comment]
This may have been closed prematurely.  From the comments one of the fixes was to disable ALL shortcuts and then the pinned shortcuts still remained, this has been changed so the pinned shortcuts do not show up.

This still doesn’t fix the problem where the recently visited sites still show up on the homepage even though it is not selected in settings.

Clint
