### ISSUE TITLE
Support first-class internet filtering (or domain whitelist)

### ISSUE THREAD

**Issue by Sternbach-Software** [mozilla-mobile/fenix#25335]
### What is the user problem or growth opportunity you want to see solved?

The ability to filter browsing activity, such as by enforcing a list of user-defined black/whitelisted domains.

### How do you know that this problem exists today? Why is this important?

There have been many movements in recent years to facilitate healthy internet use (e.g. screen time limits; internet filters for adult content, social media, etc.; internet use insights and analytics; etc.). These movements are especially strong in the religious communities. Companies such as Covenant Eyes, NetSpark, etc. are quite financially successful in catering to these needs. [The Android philosophy](https://developer.android.com/guide/components/fundamentals) of the principle of least privilege complicates the task of one app filtering another app. The issues of such an approach are many: workarounds are near-impossible to avoid; significant performance reductions and increased battery consumption (every request needs to be vetted before being authorized and forwarded); users are sometimes forced to use the filter's VPN instead of their preferred VPN; among many others. There are currently no high-profile browsers that support first-class filtering. In fact, I was only able to find one [app](https://play.google.com/store/apps/details?id=com.yehudak.whitelistbrowser) on the app store that allows setting a whitelist, and it leaves much to be desired.

### Who will benefit from it?

Those who are looking to minimize or monitor/filter their use of the Internet, either restricting it to sole use of specific websites through a whitelist, or restrict specific websites through a blacklist. They may also want to filter categories of sites (e.g. adult content, social media, etc.). An employer may also want to impose restrictions on the sites an employee can visit, such as limiting the possible sites visited to work-related sites.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20528)

**Comment by shmueldabomb441** [comment]
To be clear, my desire specifically is to be able to use the facilities of Mozilla while only using a whitelist. My use case specifically would be that my entrusted individual would hold a password, and the whitelist would only be able to be edited once that password is entered.

**Comment by shmueldabomb441** [comment]
At the very least, if this is not a feature the moderators are interested in implementing, I would be appreciative if I could be pointed to where I can make code edits to only allow requests to go through if they are in the whitelist.
