### ISSUE TITLE
[Bug]: deezer.com broken in Fenix 100.2.0 (regression)

### ISSUE THREAD

**Issue by Noob729** [mozilla-mobile/fenix#25336]
### Steps to reproduce

1. Open deezer.com in a new tab
2. Switch to "Desktop mode" (Options > "Desktop site" slider)
3. Log in
4. Try to play any song

### Expected behaviour

Fenix should start playing the requested song.

### Actual behaviour

Even before trying to play a song, a gray error bar states:  
"Your computer seems to be offline. We'll keep trying to reconnect."

After trying to play a song, a pink error bar immediately states:
"The requested content is not loading. Error: MS0610"

### Device name

Xiaomi Redmi Note 5 Pro (whyred)

### Android version

Android 8.1.0

### Firefox release type

Firefox

### Firefox version

100.2.0

### Additional information

The deezer.com site works flawlessly in Fenix 99.  
As soon as I updated to Fenix 100, the site stopped working.  
The deezer.com site works flawlessly in Firefox 100.0 (desktop)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20529)

**Comment by AdinaPetridean** [comment]
@Noob729 Please check  Firefox Release Version 102.1.1 and let us know if this issue is no longer reproducible.

**Comment by Noob729** [comment]
@AdinaPetridean @sflorean 
Using version 102.2.0 (Build #2015890451) GV: 102.0.1-20220705093820  

Even with cache & cookies cleared, trying to login from a normal window fails with:  
"Your details are incorrect. Please try again"  
Using the same credentials in a private window, login succeeds, and music plays normally.
