### ISSUE TITLE
[Bug]: Autocomplete malfunctions when typing quickly

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#25333]
### Steps to reproduce

1. Go to `shutterfly.com` to get it into your autocomplete history.
2. Open a new tab, and slowly type `shutter island`.
3. Clear the typed text.
4. Very, very quickly type `shutter island`.

### Expected behaviour

At steps 2 and 4, autocomplete should suggest `shutterfly.com` until you type a space, at which point the suggestion disappears. If you were to press your keyboard's Enter button after typing, then you'd end up doing a search for "shutter island."

### Actual behaviour

Step 2 behaves properly, but step 4 does not. Typing quickly enough causes the autocomplete to fail to update, so that when you're done typing, the current input is something like `shutter islandfly.com`. Pressing Enter at this stage will navigate you to a bogus URL.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

100.3.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20526)

**Comment by DavidJCobb** [comment]
Related to or duplicate of #23131.

**Comment by SoftVision-LorandJanos** [comment]
Hi @DavidJCobb. Thank you for your report!
I couldn't reproduce the issue you described, or the one it's mentioned being a duplicate of.
However it seems to be covered by the issue mentioned above. Based on that, I will close this one as a duplicate.
