### ISSUE TITLE
[Bug] Tabs can't be saved in Collections

### ISSUE THREAD

**Issue by nikoloskid** [mozilla-mobile/fenix#2533]
## Steps to reproduce
![image](https://user-images.githubusercontent.com/12738743/57805383-0f11cf00-775d-11e9-91cd-133496dc2cb8.jpeg)

1. Open tab
1. Save to Collection
1. Add new collection 
    1. Expected behavior

* When you save a tab to the collection, it should be shown in Home Page of Fenix aka Collections

### Actual behavior
* You open a tab, and you want to save it in your Collections, you click Preferences and on the opened tab and click Save to Collection you add a Collection or you save it on existing Collection. When you check for Collections, there will be none.

### Device information
* Android device: Huawei P20 Lite / Android Version 8.0
* Fenix version: ?

**Comment by ekager** [comment]
This feature isn't implemented yet see https://github.com/mozilla-mobile/fenix/issues/1575

**Comment by boek** [comment]
Added that menu item to the feature flag in #2535
