### ISSUE TITLE
Intermittent UI test failure - < SettingsAboutTest.verifyAboutFirefoxPreview>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25355]
### Stacktrace:
05-23 18:07:30.764: I/WindowManager(477): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: b9a2d0b org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=true)
05-23 18:07:30.932: I/ActivityManager(477): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
05-23 18:07:30.932: I/ActivityManager(477): Killing 12969:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-23 18:07:30.937: W/ActivityTaskManager(477): Force removing ActivityRecord{27abe61 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
05-23 18:07:30.940: D/AndroidRuntime(12952): Shutting down VM
05-23 18:07:30.940: I/ServiceChildProcess(13786): Destroying GeckoServiceChildProcess
05-23 18:07:30.941: I/ServiceChildProcess(13621): Destroying GeckoServiceChildProcess
05-23 18:07:30.976: I/ActivityManager(477): Killing 13621:org.mozilla.fenix.debug:tab33/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-23 18:07:30.978: I/ActivityManager(477): Killing 13786:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-23 18:07:30.983: D/WindowManager(477): notifyANR took 231ms
### Notes: Similar with #24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20541)

**Comment by AndiAJ** [comment]
Failed 1x on 6/21 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8411743978763855001/executions/bs.40d94c67e30dfb4/test-cases)
06-20 18:17:06.380: I/WindowManager(477): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 58c8e93 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5005ms for FocusEvent(hasFocus=true)
06-20 18:17:06.406: E/MmTelFeatureConnection [0](1777): ImsRegistrationCallbackAdapter: ImsRegistration is null
06-20 18:17:06.437: I/Icing(9151): Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
06-20 18:17:06.467: I/NetworkScheduler.Stats(2297): Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService finished executing. cause:5 result: 3 elapsed_millis: 2257 uptime_millis: 2257 exec_start_elapsed_seconds: 2452 [CONTEXT service_id=218 ]
06-20 18:17:06.479: I/ActivityManager(477): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
06-20 18:17:06.479: I/ActivityManager(477): Killing 12207:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-20 18:17:06.483: W/Binder(12152): Caught a RuntimeException from the binder stub implementation.
06-20 18:17:06.483: W/Binder(12152): java.lang.SecurityException: Calling from not trusted UID!
06-20 18:17:06.483: W/Binder(12152): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-20 18:17:06.483: W/Binder(12152): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-20 18:17:06.483: W/Binder(12152): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-20 18:17:06.483: W/Binder(12152): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-20 18:17:06.483: W/Binder(12152): 	at android.os.Binder.execTransact(Binder.java:1123)
06-20 18:17:06.483: I/ServiceChildProcess(12782): Destroying GeckoServiceChildProcess
06-20 18:17:06.483: I/ServiceChildProcess(13005): Destroying GeckoServiceChildProcess
06-20 18:17:06.486: D/AndroidRuntime(12152): Shutting down VM
06-20 18:17:06.486: W/ActivityTaskManager(477): Force removing ActivityRecord{2878252 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
06-20 18:17:06.495: I/ActivityManager(477): Killing 12782:org.mozilla.fenix.debug:tab38/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-20 18:17:06.510: I/ActivityManager(477): Killing 13005:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-20 18:17:06.528: D/WindowManager(477): notifyANR took 157ms


[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8411743978763855001/executions/bs.812bb9da5c1a714d/test-cases)

06-20 18:23:11.951: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: e05e1ee org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5003ms for FocusEvent(hasFocus=true)
06-20 18:23:12.001: D/StrictMode(13762): StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. Callsite: readFromParcel
06-20 18:23:12.001: D/StrictMode(13762): 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1929)
06-20 18:23:12.001: D/StrictMode(13762): 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:305)
06-20 18:23:12.001: D/StrictMode(13762): 	at android.view.SurfaceControl.finalize(SurfaceControl.java:1104)
06-20 18:23:12.001: D/StrictMode(13762): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
06-20 18:23:12.001: D/StrictMode(13762): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
06-20 18:23:12.001: D/StrictMode(13762): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
06-20 18:23:12.001: D/StrictMode(13762): 	at java.lang.Thread.run(Thread.java:923)
06-20 18:23:12.028: I/ActivityManager(479): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
06-20 18:23:12.028: I/ActivityManager(479): Killing 13762:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-20 18:23:12.032: W/Binder(13713): Caught a RuntimeException from the binder stub implementation.
06-20 18:23:12.032: W/Binder(13713): java.lang.SecurityException: Calling from not trusted UID!
06-20 18:23:12.032: W/Binder(13713): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-20 18:23:12.032: W/Binder(13713): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-20 18:23:12.032: W/Binder(13713): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-20 18:23:12.032: W/Binder(13713): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-20 18:23:12.032: W/Binder(13713): 	at android.os.Binder.execTransact(Binder.java:1123)
06-20 18:23:12.035: I/ServiceChildProcess(14403): Destroying GeckoServiceChildProcess
06-20 18:23:12.036: W/ActivityTaskManager(479): Force removing ActivityRecord{b42f77d u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
06-20 18:23:12.049: D/AndroidRuntime(13713): Shutting down VM
06-20 18:23:12.105: I/ActivityManager(479): Killing 14403:org.mozilla.fenix.debug:tab2/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-20 18:23:12.106: I/ActivityManager(479): Killing 14587:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-20 18:23:12.108: I/ActivityManager(479): Killing 11199:com.google.android.apps.tachyon/u0a120 (adj 995): empty for 1807s
06-20 18:23:12.113: I/BackdropActivity(12944): onResume()
06-20 18:23:12.120: I/ActivityTaskManager(479): Activity requesting to dismiss Keyguard: ActivityRecord{94a7c91 u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t8}
06-20 18:23:12.121: D/WindowManager(479): notifyANR took 178ms

**Comment by AndiAJ** [comment]
Disabled in #25694

**Comment by sv-ohorvath** [comment]
Closing as dupe in favor of https://github.com/mozilla-mobile/fenix/issues/25926 - tracking all the ANR reports
