### ISSUE TITLE
[Bug]: my websites that allow zooming, text it's not reflowing

### ISSUE THREAD

**Issue by xucaen** [mozilla-mobile/fenix#25359]
### Steps to reproduce

It looks like this was fixed years ago? But now it's not working again. When I zoom in on a website that allows zooming I then have to scroll left and right to read the text.

https://bugzilla.mozilla.org/show_bug.cgi?id=795552

### Expected behaviour

Textured automatically wrap so that I don't have to scroll left and right to read text

### Actual behaviour

And forced to scroll left and right to read text

### Device name

moto g power (2021)

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

100.3.0 (Build #2015881499), 409a30ff0+

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20544)

**Comment by SoftVision-LorandJanos** [comment]
Hi @xucaen! Thanks for your report!
Could you please add some steps to reproduce your issue?
Maybe even make a video of your issue. Thank you!
As I understand the issue from your description, it seems intended this way.
Device used: Google Pixel 4 (Android 12).

**Comment by kbrosnan** [comment]
Duplicate bz-1547181
