### ISSUE TITLE
 Firefox Desktop partitions window.name, but Fenix does not

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25367]
According to https://privacytests.org/private.html and https://privacytests.org/android.html, Firefox Desktop partitions `window.name`, but Fenix does not. The website has some example JS test case.

Note that the desktop results are from Private Browsing mode, but the Android results are not.

Is `window.name` partitioning handled by Gecko, GeckoView, or Fenix?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20549)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813791

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
