### ISSUE TITLE
[Bug]: Firefox Nightly crashes when accessing the Credit cards section in Settings

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25360]
### Steps to reproduce

1. Launch the latest Nightly 102 from 05/24. 
2. Go to Settings > Credit cards.
3. Observe that the application crashes.

### Expected behaviour

The application should remain stable at all times.

### Actual behaviour

The application crashes when accessing the Credit cards menu.
The application also crashes when accessing "Manage credit cards" from the "Select credit card" prompt.
### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly 102.0a1 from 05/24

### Device logs

[[Bug] Firefox Nightly crashes when accessing the Credit cards section in Settings.txt](https://github.com/mozilla-mobile/fenix/files/8763732/Bug.Firefox.Nightly.crashes.when.accessing.the.Credit.cards.section.in.Settings.txt)
[7d8ea0bc-0d08-4.txt](https://github.com/mozilla-mobile/fenix/files/8763733/7d8ea0bc-0d08-4.txt)

### Additional information

This crash is 100% reproducible on other devices as well (Xiaomi Redmi Note 8T (Android 9), Google Pixel 2 (Android 9), OnePlus 6T (Android 9), Motorola Moto G30 (Android 11)). 
This did not occur on the previous Nightly build, from 05/23.

https://user-images.githubusercontent.com/89388888/170062060-7ecd6da7-1a69-4526-856b-2bfa6e9c1358.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20545)

**Comment by Amejia481** [comment]
cc: @gabrielluong

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 102.0a1 (2022-05-25) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
