### ISSUE TITLE
Firefox Desktop partitions its favicon cache, but Fenix does not

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25366]
According to https://privacytests.org/private.html and https://privacytests.org/android.html, Firefox Desktop partitions its favicon cache but Fenix does not. The website has some example JS test case.

Note that the desktop results are from Private Browsing mode, but the Android results are not.

Firefox Desktop stores favicons in [nsIFaviconService](https://searchfox.org/mozilla-central/source/toolkit/components/places/nsIFaviconService). Does Fenix implement its own favicon cache?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20550)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813780

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
