### ISSUE TITLE
Support search in Settings

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#25364]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
There is no way to be able to search through the settings in the mobile version of Firefox.

### How do you know that this problem exists today? Why is this important?
Faced this a couple of times myself. With increasing number of things in the settings page, it will be easier to search a particular setting.

### Who will benefit from it?
Users who wish to go to a particular setting by remembering/assuming what that setting is called.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20548)

**Comment by alittlebitofit** [comment]
I too, want this.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813757

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
