### ISSUE TITLE
The string on the "Update card expiration date" prompt should be generalized 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25363]
### Steps to reproduce

1. Have a credit card saved in Fenix.
2. Access a purchasing website what has a credit card form (https://checkout.stripe.dev).
3. Fill in the form with the data of the saved credit card.
4. Modify the data in any field except the credit card number.
5. Tap on "Pay".
6. Observe the prompt.

### Expected behaviour

The "Update card expiation date?" string should be changed to a more generalized string as "Update card data/information?".

### Actual behaviour

The "Update card expiration date?" string is misleading for the user. The string is displayed when entering and modifying any data of an already saved credit card (CC name, CVC, expiration date), not only the expiration date.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly 102 from 05/24

### Additional information

https://user-images.githubusercontent.com/89388888/170069869-f9ab119f-3767-4a35-a95d-fe4e6831524a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20547)

**Comment by delia-pop** [comment]
cc: @gabrielluong

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814163

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
