### ISSUE TITLE
Duplicate items in History

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#25368]
When scrolling down history, items close to pagination get duplicated.

Let's say, we uploaded 75 items, scrolled down a bit, and loaded another 25.
What happens technically is, `HistoryDataSource` asks `PagedHistoryProvider` to get 75 items of `HistoryDB`, assigns each of them a position. Then uses the position of the last element as an offset for a next pagination call.
The problem comes from `PagedHistoryProvider` doing some operations on the list, like [removing duplicates](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt#219). Although 75 items were requested and pulled out of the DB, let's say after removing 5 duplicated, 70 items were returned. `HistoryDataSource` will use 70 as an offset for the next call, and 5 items from the previous page will get into the next one.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20551)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 102.0a1 (2022-05-25) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
