### ISSUE TITLE
Don't evalute action when in control message

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#25374]
Actions are not require for a control message instead of reporting it as malformed, we should skip the action validation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20557)

**Comment by gabrielluong** [comment]
@Amejia481 should this be closed or set for qa-needed?

**Comment by Amejia481** [comment]
Thanks for taking a look!
We can close this as there is a member of the  Data Science/Experimentation team that is checking if the issue is addressed.
