### ISSUE TITLE
Reset block list for items on homescreen

### ISSUE THREAD

**Issue by highroller** [mozilla-mobile/fenix#25371]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

This is referring to issue #23069. 

### How do you know that this problem exists today? Why is this important?

There should be a way to remove website from block list instead of clear app data. I would suggest to add a simple Reset Blocklist button in settings instead of option of removing specific website. 

### Who will benefit from it?
Anyone who changes their minds about blocking a website and don't want to clear app data and reset custom settings.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20553)

**Comment by LaurentiuApahideanSV** [comment]
I will mark this issue as a feature request.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809821

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
