### ISSUE TITLE
Add a setting allowing to toggle Pocket sponsored stories

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25381]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-19886

**Comment by SoftVision-LorandJanos** [comment]
I've tested build on a debug build (GV: 103.0a1-20220626094153) using a Google Pixel 4 (Android 12).
The toggle for the Pocket sponsored stories is displayed in the settings.
However, according to the description of the ticket the feature should be OFF by default, and it appears ON.

**Comment by Mugurell** [comment]
Thank you for checking @SoftVision-LorandJanos .
Doubled checked now in code and saw that [the sponsored stories feature](https://github.com/mozilla-mobile/fenix/blob/8c752c3be1a0853368fb98faca69767a0dc331b1/app/src/main/java/org/mozilla/fenix/utils/Settings.kt#L1314-L1318) is controlled by an experiment [which is be default disabled](https://github.com/mozilla-mobile/fenix/blob/8c752c3be1a0853368fb98faca69767a0dc331b1/nimbus.fml.yaml#L200) and even then gated to [only be enabled in debug](https://github.com/mozilla-mobile/fenix/blob/83e19be3850ff7852580173cfd4dd58175ab796f/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L69).
Saw with the debugger that the FML feature is enabled and given that the testing was done on a debug build I think the results are expected.
This should be retested again when the feature is in a release build.

**Comment by cpeterso** [comment]
merged
