### ISSUE TITLE
Crash Report [@ PLDHashTable::Search | mozilla::a11y::RemoteAccessibleBase<T>::RetrieveCachedBounds ]

### ISSUE THREAD

**Issue by sharbet** [mozilla-mobile/fenix#25395]
### Steps to reproduce

Randomly crashes, no specific site.

### Expected behaviour

n/a

### Actual behaviour

n/a

### Device name

Galaxy

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1

### Device logs

Refer to this Socorro

https://crash-stats.mozilla.org/report/index/f41d3b5a-53f6-4f21-9620-d6e390220526

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20570)

**Comment by kbrosnan** [comment]
this is tracked by bz-1771271
