### ISSUE TITLE
Intermittent UI test failure - < DownloadTest.testCloseDownloadPrompt>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25391]
### Stacktrace:
05-25 08:22:01.405: I/WindowManager(478): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 38f282e org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5004ms for FocusEvent(hasFocus=true)
05-25 08:22:01.411: D/GeckoViewProgressDelegate[C](13552): handleEvent: MozAfterPaint
05-25 08:22:01.414: D/GeckoViewSessionStateAggregator[C](13552): receiveMessage: GeckoView:FlushSessionState
05-25 08:22:01.416: D/GeckoViewContent(12680): onEvent: event=GeckoView:SetFocused, data={"focused":false}
05-25 08:22:01.432: D/GeckoViewAutoFill[C](13552): handleEvent: focusout
05-25 08:22:01.439: D/GeckoViewProgress(12680): receiveMessage: MozAfterPaint
05-25 08:22:01.439: D/GeckoViewProgress(12680): receiveMessage: MozAfterPaint
05-25 08:22:01.469: D/LeakCanary(12680): Watching instance of org.mozilla.fenix.browser.SwipeGestureLayout (org.mozilla.fenix.browser.BrowserFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 0a510d81-89a0-4c03-b6d8-168640669a62
05-25 08:22:01.515: I/Choreographer(12680): Skipped 310 frames!  The application may be doing too much work on its main thread.
05-25 08:22:01.550: D/sql_support::conn_ext(12680): Transaction commited after 149.857142ms
05-25 08:22:01.620: I/ActivityManager(478): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
05-25 08:22:01.620: I/ActivityManager(478): Killing 12680:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-25 08:22:01.629: D/AndroidRuntime(12659): Shutting down VM
05-25 08:22:01.643: W/Binder(12659): Caught a RuntimeException from the binder stub implementation.
05-25 08:22:01.643: W/Binder(12659): java.lang.SecurityException: Calling from not trusted UID!
05-25 08:22:01.643: W/Binder(12659): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-25 08:22:01.643: W/Binder(12659): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-25 08:22:01.643: W/Binder(12659): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-25 08:22:01.643: W/Binder(12659): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-25 08:22:01.643: W/Binder(12659): 	at android.os.Binder.execTransact(Binder.java:1123)
05-25 08:22:01.651: W/ActivityTaskManager(478): Force removing ActivityRecord{74dd6ac u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
05-25 08:22:01.652: I/ServiceChildProcess(13552): Destroying GeckoServiceChildProcess
05-25 08:22:01.654: I/ServiceChildProcess(13756): Destroying GeckoServiceChildProcess
05-25 08:22:01.713: I/ActivityManager(478): Killing 13552:org.mozilla.fenix.debug:tab25/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-25 08:22:01.715: I/ActivityManager(478): Killing 13756:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-25 08:22:01.719: D/WindowManager(478): notifyANR took 340ms
### Notes: Similar with #24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20567)

**Comment by sv-ohorvath** [comment]
Flaky 1x on main 6/9, different cause: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6696243506005561227/executions/bs.6efb3b6fc14939e7
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (view.getContentDescription() is "Menu")
`

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
