### ISSUE TITLE
Throttle Streaming Bandwidth (use lower quality video streams) for Power Saving mode

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#254]
Parent: #240

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11495)

**Comment by cpeterso** [comment]
Throttling streaming video might require new GV APIs.

**Comment by bbinto** [comment]
For TRIAGE: This should probably go into milestone 2 backlog, please size first though. 

Any work from A/C?

Added to Airtable: https://airtable.com/tbl9Z7oZZ5v8lgP5W/viwZlykqS5yzXCKQh

**Comment by nils-ohlmeier** [comment]
I believe the proper solution for this is to connect the power saving mode to Media Capabilities. So that Gecko changes it's answer what is playing smoothly if the power saving mode is on. And then the page can make the decision what video to serve to the user.

**Comment by cpeterso** [comment]
Here are the MDN docs for `MediaCapabilitiesInfo`:
https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilitiesInfo

I filed a new GV bug asking for an API for Fenix to toggle a power-saving mode flag in Gecko. Gecko features that have performance/power tradeoffs can then check this one flag to decide when to prioritize power savings over performance.

https://bugzilla.mozilla.org/show_bug.cgi?id=1525466

**Comment by bbinto** [comment]
As per [comment](https://github.com/mozilla-mobile/fenix/issues/240#issuecomment-473414507), we might pull this back into a Battery saving story after MVP.

Out of scope for MVP.

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report is closed. I think we would want to do this differently.
