### ISSUE TITLE
Add telemetry for Pocket sponsored stories

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25401]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-19878

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20574)

**Comment by SoftVision-LorandJanos** [comment]
I will wait for the feature to be available on nightly, since we don't have setting for debug version for the telemetry data to be checked on Glean.

**Comment by cpeterso** [comment]
merged
