### ISSUE TITLE
[Bug]: Inconsistent History search settings

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#25409]
### Steps to reproduce

1. Activate Debug menu by tapping 5 times the Firefox logo from About Firefox Nightly on the latest Nightly build.
2. Enable "Unified search" from the Secret settings (Requires restart).
3. Go to Settings>Search and disable "Search browsing history".
4. Go to address bar, select "History" from the search dropdown menu and start typing a valid string (part of a history item) and tap on "Go".

### Expected behaviour

No search suggestions are displayed.
There are no search results.

### Actual behaviour

Search suggestions/results are displayed.

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1

### Additional information

https://user-images.githubusercontent.com/48829350/170665127-49fb0a93-2a70-4960-bbc1-2b52c7aa77ce.mp4

This behavior would probably be the same on Bookmarks search.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20576)

**Comment by SoftVision-LorandJanos** [comment]
Alternative to the expected result would be that when you switch to "History" search engine the "Search browsing history" automatically switches back on, maybe even notifies the user about it.

**Comment by rocketsroger** [comment]
> Alternative to the expected result would be that when you switch to "History" search engine the "Search browsing history" automatically switches back on, maybe even notifies the user about it.

That might confuse the user.  A possible solution is to hide the history search engine as a choice when user switch it off.  But the question remains that if that switch should affect history search.

**Comment by SoftVision-LorandJanos** [comment]
As the history search option is no longer available through the "Unified search" feature, this issue as described is no longer valid.
Tested on the latest Nightly 109.0a1 (2022-11-24) build.
Device used: Oppo find X5 (Android 12).
Closing the issue as not planned.
