### ISSUE TITLE
NYTimes Crossword Mini is not loading

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/fenix#25412]
### Steps to reproduce

1. open https://www.nytimes.com/crosswords/game/mini
2. Cannot load the page

### Expected behaviour

Should open the page. Recent update changed this behavior (I think 2 days ago?)

### Actual behaviour

The page doesn't load. Firefox says it can't load the page.

### Device name

Samsung s10e

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1

### Device logs

3c904807-de33-4be1-82c5-b0dd42bf9f97
<native crash>
----
<native crash>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20577)

**Comment by kbrosnan** [comment]
If possible connect desktop's devtools and check if the number is in the +520k range. If so then this is bz-1755206

* https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/
* https://bugzilla.mozilla.org/show_bug.cgi?id=1755206#c1

**Comment by fbertsch** [comment]
@kbrosnan I managed to get debugging working. When the tab loads, it starts spitting out some JS, and the last console log is a cross-origin request error. It then completely dies on the entire tab looks like this (no logs, no nuthin'):

<img width="1271" alt="Screen Shot 2022-05-28 at 1 15 25 PM" src="https://user-images.githubusercontent.com/20819040/170835805-1ea33113-a18e-458b-a004-f742198b67f7.png">
n

**Comment by fbertsch** [comment]
I also noticed that it happens on the regular crossword site as well: https://www.nytimes.com/crosswords/game/daily/2022/05/28

And clearly is not happening on desktop.

**Comment by jonalmeida** [comment]
I can reproduce this bug as well.

The debugger shows a white screen because the tab process is crashing. I was able to attach a debugger before it crashed, but it eventually shows the same white screen too.

In the main process, the debugger shows these errors:
```
Uncaught TypeError: can't access property "sendAsyncMessage", this._manager.messageManager is null
    _updateContentModuleState chrome://geckoview/content/geckoview.js:497
    set enabled chrome://geckoview/content/geckoview.js:472
    init chrome://geckoview/content/geckoview.js:115
    forEach chrome://geckoview/content/geckoview.js:150
    init chrome://geckoview/content/geckoview.js:114
    init chrome://geckoview/content/geckoview.js:113
    startup chrome://geckoview/content/geckoview.js:543
    EventListener.handleEvent* chrome://geckoview/content/geckoview.xhtml:12
```

This trace doesn't seem useful to me though, looks like it's just confirming the process we tried to send a message to has crashed.

I tried the page with Tracking Protection disabled - same crash.

This is on Nightly 105. I was able to reproduce and report the crash from Reference Browser though.

On Beta 104, it's not crashing for me.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813766

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
