### ISSUE TITLE
Picture-in-picture to custom tab has the app blocked in landscape

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25413]
STRs:
- Have Fenix set as the default browser
- Start playing a fullscreen video in landscape
- Tap the home button to enter in picture-in-picture  mode
- Ensure the device is now held in portrait
- Tap on a link from another app to open it in a Fenix custom tab

Expected result:
- Fenix open a custom tab and shows it using device orientation (portrait).

Actual result:
- The picture-in-picture mode is still on and the player is shown over the custom tab.
- Orientation is locked to landscape making webpage interactions cumbersome.
- Even after closing the small pip window orientation is locked to landscape.

Not that testing the same scenario on Chrome I see that the video continue playing in pip mode but the app orientation when showing the custom tab will be portrait as expected.

https://user-images.githubusercontent.com/11428869/170698688-19cc8042-5e0b-445b-8509-92ccbd83abb3.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20578)

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by Mugurell** [comment]
Saw that if the pip player is closed when opening the app afterwards it will be shown in landscape.
Seems like we should try having one solution for all scenarios for opening the app after pip.

**Comment by indurs** [comment]
@Mugurell , I've changed the MediaSessionFullscreenFeature to work for all scenarios. Currently working on test cases.

**Comment by indurs** [comment]
Will create a draft PR today

**Comment by indurs** [comment]
> Saw that if the pip player is closed when opening the app afterwards it will be shown in landscape. 

@Mugurell , the change is working for the above scenario as well.

**Comment by indurs** [comment]
@Mugurell , I've created a PR . https://github.com/mozilla-mobile/android-components/pull/12288

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 103.0a1 2022-06-09 and the app in no longer locked in landscape mode after performing the steps mentioned in https://github.com/mozilla-mobile/fenix/issues/25413#issue-1250713027.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
