### ISSUE TITLE
FNX3-16398 ⁃ [Bug] More redirects need to be removed from history suggestions

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/fenix#2542]
## Steps to reproduce
Type "mozilla firefox" into the search field

### Expected behavior
I should see history entries for https://www.mozilla.org/en-US/firefox and 
https://www.mozilla.org/en-US/firefox/new

### Actual behavior
I get four history entries:
https://www.mozilla.org/firefox
https://www.mozilla.org/en-US/firefox
https://www.mozilla.org/firefox/new
https://www.mozilla.org/en-US/firefox/new

### Device information
* Android device: Nokia 3.2
* Fenix version: 1.0.1920 build#11351814

**Comment by Verdi** [comment]
In issue #1332 @grigoryk said this was handled by #1395

**Comment by ekager** [comment]
#1332 and #1395 were about the History UI. I opened https://github.com/mozilla-mobile/android-components/issues/3027 specifically about the history suggestions in the awesome bar.

**Comment by thomcc** [comment]
Huh, that's a bug if those are showing up.

**Comment by sv-ohorvath** [comment]
@pocmo Nightly 10/23: Still seeing multiple redirects in suggestions, even though they don't appear in history: 
![Screenshot_20191023-113153_Firefox Nightly](https://user-images.githubusercontent.com/4037709/67373822-f10c8e00-f588-11e9-906f-b95dc917650a.jpg)

**Comment by abodea** [comment]
I re-checked this issue on the latest **Nightly build 11/26 with Google Pixel 3a XL(Android 10).**
Note that with a clean profile when I typed `Mozilla` or `Mozilla Firefox` I got the following results:

![Screenshot_20191126-181100](https://user-images.githubusercontent.com/42831109/69652477-5ff27080-107a-11ea-9d9b-316506fd3442.png)
@mcarare @athomasmoz can you please confirm that this is the behavior we expect?
I will not delete the `eng:qa:needed` until further notice and after that, if this is the intended behavior I will verify this issue as fixed.

**Comment by mcarare** [comment]
@abodea  LGTM: The only suggestions that appear are engine suggestions

**Comment by abodea** [comment]
Thx @mcarare.
Based on my comment above and Mihai's comment I will mark this issue verified as fixed.
