### ISSUE TITLE
[Bug]: Only first attempt opens link in external app in a page with multiple links 

### ISSUE THREAD

**Issue by Blaze-Thunder** [mozilla-mobile/fenix#25426]
### Steps to reproduce

1. Do a search with reddit links
2. Click the first reddit link and it opens in external app
3. Then come back to firefox search results and click on next reddit link
4. It opens in firefox instead of opening in external app.
5. If we have to open in external app on the subsequent links, it should be selected from context menu to open in external app

### Expected behaviour

Every click on external app links should open in external app

### Actual behaviour

Only first link opens in external app and subsequent links open in firefox browser.

### Device name

OnePlus 7 pro

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

102.a1Build #2015883051

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20586)

**Comment by Mugurell** [comment]
I see the same as @indurs on both the current release and nightly.
Tested with the official apps for reddit and wikipedia, both apps are opened everytime for every click. 
But indeed Fenix is left to show an empty page and this seems like a bug.

@Blaze-Thunder Can you offer more details about your setup? With which external applications have you seen this bug? Can you also post a video showcasing the issue?

**Comment by indurs** [comment]
@Mugurell , will work on this issue this week.

**Comment by Blaze-Thunder** [comment]
Hi @indurs @Mugurell ,
My issue is that only the first link in search results open in the respective app. 
I am using Latest firefox release version

**Comment by indurs** [comment]
@Blaze-Thunder , Thank you for providing us the scenarios causing the issue.

**Comment by indurs** [comment]
@Mugurell , https://github.com/mozilla-mobile/android-components/pull/12382 by @RotBolt will fix this issue. 

But the empty page is not fixed yet. This happens only for Google search results. The links in the search results from Google and Duckduckgo ( and also other web pages) are different.

* Google
https://www.google.com/url?q=https://www.reddit.com/r/Android/&sa=U&ved=2ahUKEwjRm7CH4NH4AhXpS2wGHUoyBzQQFnoECAAQAg&usg=AOvVaw3jqU3Npsbs3wuXBn40lrE9

I'm not sure how Gecko handles this link. I think it redirects to "https://www.reddit.com/r/Android/" and AppLinksInterceptor identifies as an app link and the app is launched. But Gecko again sends the https://www.google.com/url?q=https://www.reddit.com/r/Android/&sa=U&ved=2ahUKEwjRm7CH4NH4AhXpS2wGHUoyBzQQFnoECAAQAg&usg=AOvVaw3jqU3Npsbs3wuXBn40lrE9 which result in 302 moved page. 

* Duckduckgo
https://www.reddit.com/r/Android/
There is no such issue here and also in other web pages which have app links (as far as I explored)

@Mugurell , Do to time constraints, I think it might take few days to start working on this issue. Is that Ok?
