### ISSUE TITLE
[Bug]: when i delete something from my history its wipes it away from the entire history

### ISSUE THREAD

**Issue by honnybee7** [mozilla-mobile/fenix#25427]
### Steps to reproduce

1) go on a site one day
2) next day go on site
3) delete one of the site links
4) it deletes both 

### Expected behaviour

I'm not sure if this is a expected behavior but it's really inconvenient it should only delete what you deleted nothing more 

### Actual behaviour

Deletes everything related to it 

### Device name

Galaxy a6

### Android version

Unsure 

### Firefox release type

Firefox

### Firefox version

100.3.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20587)

**Comment by honnybee7** [comment]
Hello can I get a response to this.

**Comment by amocirean** [comment]
Hello @honnybee7 , thank you for submitting the issue.
I was able to reproduce it on the latest RC and Nightly.


Device Used: Huawei P40 Lite
Android Version: 10

**Comment by honnybee7** [comment]
> Hello @honnybee7 , thank you for submitting the issue. I was able to reproduce it on the latest RC and Nightly.
> 
> Device Used: Huawei P40 Lite Android Version: 10

So is it a bug?

**Comment by honnybee7** [comment]
Hello can you please respond.

**Comment by honnybee7** [comment]
I'm not sure if you gave me a dislike or someone else but can you please tell me if this is a bug

**Comment by honnybee7** [comment]
Hello can someone please answer me.

**Comment by kbrosnan** [comment]
What exact steps are you using to delete data? Can you provide screenshots using something like https://wikipedia.org? There are a few places in the UI that deletion is an action.

**Comment by kbrosnan** [comment]
Which specific screen or element are you long pressing.

**Comment by honnybee7** [comment]
![Screenshot_20220621-202142_Firefox](https://user-images.githubusercontent.com/36801964/174923375-ad052072-4965-4db2-85b4-4dba94eaaf67.jpg)
I long press the things history remove it says select and gives option to delete

**Comment by honnybee7** [comment]
Hello you still there?

**Comment by honnybee7** [comment]
> Which specific screen or element are you long pressing.

Hello you still there?

**Comment by honnybee7** [comment]
Can someone please respond
