### ISSUE TITLE
Support easier testing of composables

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25431]
Issue raised by @sv-ohorvath when adding tests for the newly refactored homescreen collections where she saw the need for more information allowing to easily and confidently identify a certain composable on screen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20588)

**Comment by sv-ohorvath** [comment]
A part of this work was done in https://github.com/mozilla-mobile/fenix/issues/26826

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807292

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
