### ISSUE TITLE
Don't exit "Logins and passwords" menu when switching apps to enter password

### ISSUE THREAD

**Issue by DaddyAG** [mozilla-mobile/fenix#25456]
Hello,

Steps:
1. Open "Settings"
2. Open "Logins and passwords"
3. Search for website login and copy one entry (username for example).
4. Switch to another app to paste the username
5. Switch back to Firefox for Android to copy the password

What will happen:
You will be returned to "Settings" where you need to enter "Logins and passwords" again, authenticate, search for website/app and then copy the password.

How it should work:
You should be returned to the screen which you left open when you went to paste the username to a different app. I understand you wanted to increase security, but this is just bad UI. A good option (workaround) would be to set a timeout, one to five minutes, in which FF will not ask the user for authentification for "Logins and passwords" again (and will return user to screen he left open).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20606)

**Comment by alittlebitofit** [comment]
I too, want this.

**Comment by alittlebitofit** [comment]
Don't close.

**Comment by alittlebitofit** [comment]
Reopen this please.
