### ISSUE TITLE
[Bug] Play Store rederict

### ISSUE THREAD

**Issue by nikoloskid** [mozilla-mobile/fenix#2546]
## Steps to reproduce
1. Open tab for example [Instagram](https://instagram.com)
1. Click icon "GET IT ON Google Play"
1. It redericts to Instagram on the[Google Play's website](https://play.google.com/)

### Expected behavior
* When clicking the icon of Google Play, it should rederict you and open the Play Store app.

### Device information
* Android device: Huawei P20 Lite
* Fenix version: 1.0.1920

**Comment by ekager** [comment]
Dupe of #1570

**Comment by nikoloskii** [comment]
> Dupe of #1570

It's an easy fix.

**Comment by ekager** [comment]
There are people working on it in our Android-Component library see https://github.com/mozilla-mobile/android-components/issues/1132
