### ISSUE TITLE
I want to disable Secret Settings on Firefox Mobile

### ISSUE THREAD

**Issue by sami155** [mozilla-mobile/fenix#25465]
I accidentally activated it and now i cant find anything on the internet on how to disable it.

How can I disable the Secret Settings/Debug mode on Firefox Android

OS: Android 12, Samsung s21, Firefox Beta from Google Play Store

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20612)

**Comment by cadeyrn** [comment]
> How can I disable the Secret Settings/Debug mode on Firefox Android

Just exit Firefox (via the Android recent apps screen) and start Firefox again.
