### ISSUE TITLE
[Bug]: Add a shortcut to open private tabs tooltip doesn't work

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#25461]
### Steps to reproduce

1. Open a private tab
2. See the "Add a shortcut to the home screen" tooltip.
3. Try to dismiss it (or add it)

### Expected behaviour

Something happens 

### Actual behaviour

The popup just stays there 

### Device name

OnePlus 9

### Android version

12

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1 (Build #2015883435), 5ea4c6533+ AC: 102.0.20220529143103, 89506cd9c7 GV: 102.0a1-20220529090310 AS: 93.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20609)

**Comment by amocirean** [comment]
Hello @emilio , I was not able to reproduce the issue on the latest RC or Nightly. I did test it with a clean profile. 
Could you please try to reproduce it on the latest RC or latest Nightly? Thanks!

Device used: Huawei P40 Lite
Android Version: 10

**Comment by emilio** [comment]
I haven't seen this popup again, I only saw it once.
