### ISSUE TITLE
[Bug]: Saved password insecure in FF on chromebook

### ISSUE THREAD

**Issue by amitrgholap** [mozilla-mobile/fenix#25463]
### Steps to reproduce

1. Buy lenovo ideapad. Set PIN login.
2. Install latest FF
3. Login with FF account
4. Now all the username and passwords are synched from other devices.
5. Go to FF settings > login and check login credentials of some saved website.

### Expected behaviour

Expected : User is 1st asked for PIN before showing password.

### Actual behaviour

Issue: Username and password is directly shown. 

### Device name

Lenovo Ideapad Chromebook Duet

### Android version

Latest ChromeOS

### Firefox release type

Firefox

### Firefox version

Latest 91.something release

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20610)

**Comment by kbrosnan** [comment]
This seems like a Chromebook issue with their Android emulation. We call into the Android APIs to use the account security. I'm not sure what options we have to resolve this.

**Comment by amitrgholap** [comment]
Ok. But what do you expect end users to do? 
Perhaps, Start asking for master password similar to Windows or Linux.
