### ISSUE TITLE
[Bug] Pop-up windows

### ISSUE THREAD

**Issue by nikoloskid** [mozilla-mobile/fenix#2547]
## Steps to reproduce
1. Tested it on on [Google Plays developer page](https://play.google.com/store/apps/dev?id=6169333749249604352)
1. There is certain links when you click and you are asked "Prevent this site from opening pop-up windows?
1. If you click allow or deny, the results are same, it opens a new blank page.

### Expected behavior
* When clicking on the links for example **Developer** [Visit website](https://wikimediafoundation.org/) in the Additional information on bottom of the page, it should open new tab.

### Actual behavior
* Opens blank page

### Device information
* Android device: Huawei P20 Lite / 8.0
* Fenix version: 1.0.1920

**Comment by karlcow** [comment]
There's a similar issue maybe where a tap on an item open a blank new tab but not the content.
See for the details 
https://github.com/webcompat/web-bugs/issues/53276#issuecomment-633755289
