### ISSUE TITLE
[Bug]: setTimeout callback not executing

### ISSUE THREAD

**Issue by dstein64** [mozilla-mobile/fenix#25485]
### Steps to reproduce

Create a page with a button that uses `setTimeout` to change the background color (this was not the actual use case, but rather a minimal reproducible example).

```html
<html>    
  <head>                                
    <meta name="viewport" content="width=device-width, initial-scale=1">    
  </head>                                                       
  <button id="button">Click</button>                            
  <script>                                                      
    document.getElementById('button').onclick = function() {     
      setTimeout(function() {                                   
        document.body.style.backgroundColor = 'green';     
      }, 0);                           
    };          
  </script>    
</html>
```

Navigate to the page on Firefox mobile and click the button.

### Expected behaviour

Clicking the button would change the background color. This is the behavior on desktop Firefox and mobile/desktop Chrome.

### Actual behaviour

Clicking the button does not result in the background color changing.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

100.3.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20627)

**Comment by Alexandru2909** [comment]
Could not reproduce on Fenix, nor on GV Example.

**Comment by dstein64** [comment]
This was an issue with my environment. Sorry for the erroneous bug report. Thanks for investigating @Alexandru2909!
