### ISSUE TITLE
[Bug]: Selecting certain text on news.ycombinator.com causes crash

### ISSUE THREAD

**Issue by hkrutzer** [mozilla-mobile/fenix#25480]
### Steps to reproduce

1. Go to https://news.ycombinator.com/item?id=31547876
2. Select text of a post
3. Add the header of the post to the selection

### Expected behaviour

Text should be selected

### Actual behaviour

Application crashes

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

102.0a1

### Device logs

https://crash-stats.mozilla.org/report/index/496aeab6-28cf-4c7c-853a-f3d790220531
https://crash-stats.mozilla.org/report/index/9f6712c7-9b07-42ac-8517-bf3470220531

### Additional information

https://user-images.githubusercontent.com/3464899/171258626-03de310e-29f2-4348-bdf6-9ed04c611b65.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20624)

**Comment by kbrosnan** [comment]
Going to close this as I have moved the report to our upstream Bugzilla tracker for Gecko work. You can follow bz-1772170 for updates.

**Comment by hkrutzer** [comment]
Much appreciated!
