### ISSUE TITLE
[Bug]: "Report site issue" button does not work

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#25495]
### Steps to reproduce

1. Open the browser.
2. Tap on the kebap menu (3 vertical lines) of the browser.
3. Tap on the "Report Site Issue..." button.
4. Observe the result.

### Expected behaviour

A new page opens.

### Actual behaviour

Nothing happens.

### Device name

Google Pixel 3

### Android version

Android 12 -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 103.0a1 (2015883915-🦎103.0a1-20220531065724🦎)

### Additional information

1. The button is not present in the Release and Beta versions.
2. Screenshot attached:
![Screenshot_1](https://user-images.githubusercontent.com/75027050/171570256-d38f19aa-0ddf-4402-a724-d4dd0c47d910.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20634)

**Comment by sflorean** [comment]
@softvision-raul-bucata I wasn't able to reproduce this issue on latest Nightly with 
- Pixel 4XL (Android 12)
- Samsung A 32 (Android 11). 
Can you check with a clear data?

**Comment by softvision-raul-bucata** [comment]
@sflorean With a clean profile, the issue does not reproduce, and the button works as expected.


**Tested with:**

Browser / Version: Firefox Nightly 103.0a1 (2015883915-🦎103.0a1-20220531065724🦎)
Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
Operating System: Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)

**Comment by sflorean** [comment]
Thank you for testing! Closing based on the comment above.
