### ISSUE TITLE
Show statistics, eg ads blocked (like Brave) like Desktop Firefox about:protections

### ISSUE THREAD

**Issue by SpitFire-666** [mozilla-mobile/fenix#2550]
### Why/User Benefit/User Problem
On Firefox Desktop, we have an about:protections page that shows ETP stats.

![](https://user-images.githubusercontent.com/1082253/71632138-e0a50f00-2bda-11ea-8bc3-98344582604b.png)

This is something that other browsers (like Brave) already have.
(This is a nice to have). Brave browser for Android has some nice stats when you open a new tab:
![image](https://user-images.githubusercontent.com/38451588/57827978-0537ac80-77ed-11e9-8667-20bfc3652f52.png)

Brave will also show the number of ads blocked, HTTPS upgrades, trackers blocked etc for each tab by tapping the Brave logo (lion head). Thanks!

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11501)

**Comment by NotWoods** [comment]
We should surface Tracking Protection stats, similar to the "Show Report" option on Desktop.

**Comment by liuche** [comment]
@gabrielluong I know you were talking about this - do you know if this could easily exposed in Fenix bc we use Gecko/GV, or is there a lot more work that would need to be done? I'm really looking at if this is something quick and easy that already exists, or if we'd need to do a lot more work.

@vesta0 wondering if this is something that we'd like to do, if it's cheap to expose through Gecko?

**Comment by vesta0** [comment]
@liuche yes I've been chatting with desktop privacy folks and this is something we are considering on mobile for both Android and iOS.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807565

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
