### ISSUE TITLE
Password from Bitwarden gets inserted fully visible for a short time

### ISSUE THREAD

**Issue by mariusangelmann** [mozilla-mobile/fenix#25502]
### Steps to reproduce

1. Have a tab open with login form
2. Insert password using Bitwarden Android App

### Expected behaviour

Password should be inserted hidden

### Actual behaviour

Password gets inserted fully visible, becomes hidden after 1-2 seconds putting users at risk because the entire password can be seen on the screen

### Device name

OnePlus 8 Pro

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

100.3.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20638)

**Comment by mariusangelmann** [comment]
Maybe I should note that I am not sure if this only applies to Bitwarden or other password managers too.

**Comment by amocirean** [comment]
Hello @mariusangelmann , thank you for submitting the issue.
I was able to reproduce it on the latest RC and Nightly


Device Used: Huawei P40 Lite
Android Version: 10

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813767

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
