### ISSUE TITLE
Shortcuts put on home screen do not work for data-URLs

### ISSUE THREAD

**Issue by 40105** [mozilla-mobile/fenix#25504]
### Steps to reproduce

1. Open a data-Url in Firefox. eg.:  data:text/html,test
2. Add a page shortcut to this URL to the android-home screen
3. Click on the shortcut

### Expected behaviour

The Firefox should open the desired URL.

### Actual behaviour

You'll get a text pop up by android, telling you that the app isn't installed.

### Android version

Android 11 and Android 12

### Firefox release type

Firefox

### Firefox version

100.3.0 and 101.0.0-beta.6 and 107.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20639)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813768

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by debojyoti452** [comment]
@40105 Didn't able to reproduce on Android 12 Pixel 3XL Device.
