### ISSUE TITLE
scan should allow zooming

### ISSUE THREAD

**Issue by xucaen** [mozilla-mobile/fenix#25518]
Scan feature doesn't allow zooming which makes it impossible to use while watching TV. 

It is now common for tv and streaming programs to display a code for accessing content. But the scanner needs to be able to zoom in on the code to recognize it. 

Attached screenshot shows the scanner is unable to zoom in to the code on my TV.

In the past I was able to scan using Opera browser because they allow zooming in their scanner 
![Screenshot_20220603-123340](https://user-images.githubusercontent.com/17462261/171908388-c906567c-3f54-4bdd-8bcd-1369b86b21b5.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20644)

**Comment by kbrosnan** [comment]
duplicate https://github.com/mozilla-mobile/fenix/issues/13771
