### ISSUE TITLE
FNX3-16404 ⁃ Media control notification

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#2551]
## User Story
* As a user playing audio/video in my browser, I want to see a persistent media notification when backgrounding the browser allowing me to pause/play playback at any time, so I have a visual indication of where audio is coming from and a way to control playback.

Also Note: Without a notification android will start de-prioritizing the browser causing sounds artifacts.

### Acceptance Criteria
* I can see a persistent media notification when I background my browser
* I can see the title of the media playing in the notification
* I can use the notification to pause/play playback

**Comment by pocmo** [comment]
https://github.com/orgs/mozilla-mobile/projects/26

**Comment by pocmo** [comment]
A first iteration landed in RB and can be tested there. The notification does not contain any controls yet.

**Comment by vesta0** [comment]
@pocmo I just tested it in RB and it works great with most sites but when I test it with Soundcloud I don't see a notification. Thoughts?

**Comment by pocmo** [comment]
@vesta0 Yeah, that's a known issue; unfortunately we do not get any media updates reported by GeckoView for that page:
https://bugzilla.mozilla.org/show_bug.cgi?id=1554297

**Comment by vesta0** [comment]
Gotcha @pocmo thanks for confirming.

**Comment by lime124** [comment]
removed ux label -it's on our radar already as it's part of the Q3 plan

**Comment by mcomella** [comment]
FYI: media playback notifications should not be shown in private browsing mode because they leak browsing information to the system. I filed https://github.com/mozilla-mobile/fenix/issues/4759

**Comment by pocmo** [comment]
Adding QA needed: This is enabled in Nightly builds now. Starting QA process already before enabling it for all builds.

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet. 
No notifications were displayed. Pages tested: soundcloud.com, katai.ro, leparisien.fr, frombelowpodcast.com, on the latest Nightly 190821 (#12330640) with HTC Desire 820 (Android 6.0.1), OnePlus 5T (Android 9), and Sony Xperia Z2 Tablet (Android 6.0.1).

**Comment by pocmo** [comment]
Soundcloud is a known issue tracked here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1554297

**Comment by pocmo** [comment]
katai.ro should be fixed with AC 10.0.0 (https://github.com/mozilla-mobile/android-components/pull/4169)

**Comment by pocmo** [comment]
leparisien.fr is also fixed with the latest snapshot.

frombelowpodcast.com needs more investigation.

**Comment by topotropic** [comment]
is it possible to send people to the tab where the audio/video is coming from when they tap on the notification? atm we just open the latest tab people where on.

**Comment by pocmo** [comment]
@topotropic I'll file an AC issue for that. We can add the tab id to the `Intent` that opens the app and then we can add some code in Fenix that will switch to the right tab.

**Comment by colintheshots** [comment]
@vesta0 Why was this moved back to In Progress? It seems the only remaining items for this feature are GV issues and feature requests. We should count it for the milestone, since the feature is in the release.

**Comment by sv-ohorvath** [comment]
> This is not fixed yet.
> No notifications were displayed. Pages tested: soundcloud.com, katai.ro, leparisien.fr, frombelowpodcast.com, on the latest Nightly 190821 (#12330640) with HTC Desire 820 (Android 6.0.1), OnePlus 5T (Android 9), and Sony Xperia Z2 Tablet (Android 6.0.1).

@colintheshots It looks like Mira found some issues here, but mistakenly added the "qa verified' label. Is this fixed, I can help and retest if needed.

**Comment by pocmo** [comment]
My recommendation is to close this issue, do another QA round to find new issues and verify the fixes, and then file bugs if we find new things (since this is shipping and not blocked).

Regarding the things that were already mentioned:
* Feature request "tab switching" -> Filed #5148
* soundcloud.com -> GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1554297 - Also tracked on the media project board.
* katai.ro  -> Fixed. Media notification is showing up now.
* leparisien.fr -> Fixed. Media notification is showing up now.
* frombelowpodcast.com -> Same GV issue as soundcloud (https://bugzilla.mozilla.org/show_bug.cgi?id=1554297). Adding this to the Bugzilla bug and media project board.

**Comment by pocmo** [comment]
> * frombelowpodcast.com -> Same GV issue as soundcloud

I debugged this a bit more and noticed some differences so I filed a separate GV bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1579390

**Comment by sv-ohorvath** [comment]
Verified again on nightly 9/6 build. The issues mentioned above are fixed.
These are the new issues I've found:
https://github.com/mozilla-mobile/fenix/issues/5151
https://github.com/mozilla-mobile/fenix/issues/5154
Closing this bug as verified.

**Comment by pocmo** [comment]
Thank you, @sv-ohorvath! I'll look at those issues. :)
