### ISSUE TITLE
Buggy inconsistent loading of reactivated tabs

### ISSUE THREAD

**Issue by firefoxlover** [mozilla-mobile/fenix#25528]
## What happens

When there are multiple tabs already open, seemingly randomly some tabs just dont show up. The URL changes using the "swipe to change tab" feature, but the site stays the same. The same when using the normal tab switching.

Its always only one tab, when I swipe twice the next sites opens, but one tab is dead.

[***Here is a screen recording of it***](https://cloud.uol.de/s/nffYyBWXGnFzbgw) 
## Steps to reproduce

1. Load a few tabs
2. Open one or two other apps so firefox is in the background (although battery saver is off, another bug)
3. Open FF to the foreground again, move to a dead tab
4. Try to reload the tab using the swipe gesture, the button, or the reload gesture

## Version
```
101.1.1 (Build #21011120), 8092b4e74+
AC: 101.0.10, db7e8a692a
GV: 101.0-20220527190143
AS: 91.1.2

Android 12 LineageOS 19.1
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20648)

**Comment by amocirean** [comment]
Hello @firefoxlover  , thank you for submitting the issue.
I was not able to reproduce it on the latest RC or Nightly
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

Device Used: Huawei P40 Lite
Android Version: 10
