### ISSUE TITLE
Telemetry: Wallpaper Usage

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25538]
#### Description

As a Product Manager, I want to understand how much the wallpapers feature is being used. We have tracking for the number of times a user changes their wallpaper, but that only helps me to understand initial interest. The goal here is to understand how many users currently have a wallpaper set.

#### Acceptance Criteria
Being able to count how many users have a wallpaper set other than default in a given day.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20380)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 104 from 07/18 with Google Pixel 6 (Android 12). Generated metrics: 
![1](https://user-images.githubusercontent.com/89388888/179522606-d7fee04e-d7bd-440d-9195-a3594a78430e.JPG)
