### ISSUE TITLE
[Bug]: Firefox crashes when opening "Settings" in the addon I've developed

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla-mobile/fenix#25546]
### Steps to reproduce

1. using Firefox Nightly, install Auto Highlight: https://addons.mozilla.org/addon/auto_highlight/
2. open any web-page
3. click the main menu / Add-ons / Auto Highlight
4. click "Settings" in the left part of the page

Firefox will crash with this crash report:
https://crash-stats.mozilla.org/report/index/31dcc3c8-e7ef-4603-8233-e91b10220605#tab-details

Thanks!

### Expected behaviour

Should not crash :)

### Actual behaviour

Crash.

### Device name

motorola moto g200 5G

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1

### Device logs

https://crash-stats.mozilla.org/report/index/31dcc3c8-e7ef-4603-8233-e91b10220605#tab-details

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20663)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1772900

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
