### ISSUE TITLE
.bin file is downloaded instead of .pdf

### ISSUE THREAD

**Issue by fowzan** [mozilla-mobile/fenix#25568]
### Steps to reproduce

1. go to link http://healerkart.com/api/219405270ac5e3e4fb8f355f421ffcbc

### Expected behaviour

a pdf file should download / open

### Actual behaviour

a .bin file is downloaded

### Device name

Xiaomi mi 11x

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

101.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20675)

**Comment by mcarare** [comment]
In this case, we do not receive any `content-type` in the headers from the `GeckoSession`'s `WebResponse` and we end up assigning a `.bin `extension for the `null` content mimeType.

**Comment by errhammr** [comment]
I have observed Firefox on my Android device sometimes assigning extensions to downloaded files. Sometimes it assigned a wrong one. What is the reasoning behind assigning an extension that differs from the one given in the URL?

**Comment by wisniewskit** [comment]
It seems like whatever is causing this might also be causing the renaming of a `.img` file to `.txt` on Android as well, in this webcompat report: https://github.com/webcompat/web-bugs/issues/106064 . Basically the server claims that the file is `text/plain`, and the offer to save the file is therefore made with a `.txt` extension. Whereas on desktop Firefox it does not seem to change the extension.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812785

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
