### ISSUE TITLE
[Bug]: Crashes on startup, white screen then back to homescreen

### ISSUE THREAD

**Issue by FoxTrotte** [mozilla-mobile/fenix#25562]
### Steps to reproduce

1. Open Firefox
2. It crashes

### Expected behaviour

The app should launch

### Actual behaviour

It doesn't launch, a window animation starts, shows a white screen for half a second and then I'm sent back to my phone's launcher, with a crash notification from Firefox. Clearing cache doesn't solve anything.
It happened as I was browsing the web yesterday

### Device name

OnePlus 6

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

101.1.1

### Device logs

[mozilla-crash.txt](https://github.com/mozilla-mobile/fenix/files/8863081/mozilla-crash.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20671)

**Comment by Mugurell** [comment]
Regarding this issue, it is happening in the scenario of having many "recently closed tabs" or many such tabs with very long titles / urls. Probably a mix.

Unfortunately the only user fix on user side is to clear app data which would dump the data about the recently closed tabs but also about anything in the app, effectively getting it into a fresh install state.

On the app side the fastest (definitely not the best) solution would be to suppress such errors and then not actually present to the user the recently closed tabs. Maybe this would work as a temporary solution but would still take a few days to get into a release build update.

**Comment by FoxTrotte** [comment]
That sounds very coherent with what I was doing, as I was using the "reverse image search" add-on and spamming the hell out of it because it didn't seem to want to search for the image I tapped on. That was a few minutes before the crash, and this add-on  does use very long URLs

**Comment by Mugurell** [comment]
A "fix" for this landed. We will not crash anymore but for this the history about recently closed tabs will have to be purged to avoid "corrupted" data.
This may not be easy to test so I'll close the ticket based on the just landed PR.
If there are any new reports this can be reopened.
