### ISSUE TITLE
[Bug]: Custom link selection in address bar is not possible

### ISSUE THREAD

**Issue by alittlebitofit** [mozilla-mobile/fenix#25576]
### Steps to reproduce

1. Open any website.
2. Tap on address bar for link selection.
For example: `https://example.com/somethingRandom1/somethingRandom2/somethingRandom3`
3. Try to scroll horizontally on the link.

### Expected behaviour

I want to select only `https://example.com/somethingRandom1` part of the link, there's no way to scroll horizontally to get to the beginning of the link while the link is selected.

### Actual behaviour

Link gets unselected.

### Android version

12

### Firefox release type

Firefox

### Firefox version

101.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20678)

**Comment by kbrosnan** [comment]
Long press to get the selection UI. Once in the selection UI I can select any part of the URL.

Nightly 103.0a1 on a Pixel 6 Pro

**Comment by alittlebitofit** [comment]
Interesting, it works.
Although, it would be quite cumbersome if the link is big and you need only first one or two parts of the url.

**Comment by kbrosnan** [comment]
Then this is as designed.

**Comment by alittlebitofit** [comment]
I still can't select only `somethingRandom3`.

**Comment by alittlebitofit** [comment]
@kbrosnan Open the issue.
