### ISSUE TITLE
[Bug]: No way to add site permissions exception for autoplay

### ISSUE THREAD

**Issue by wfaulk** [mozilla-mobile/fenix#25572]
### Steps to reproduce

1. Try to add an exception for autoplay to a site that doesn't attempt to use any other permissions
    https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_autoplay for example

### Expected behaviour

There should be some way to do this.

Other exceptions can be added when a site tries to use a permission and the browser asks if you want to allow it. But there is no "ask" action for autoplay. If the site doesn't also try to use other permissions, the browser will never ask about permissions. And there is no user interface to manually add a site to the permissions list.

On sites that do ask for other permissions, you can then find that site in the exceptions list and change the autoplay permission, and the exception works correctly, but, again, if the site doesn't ask for another permission, there is no way to make that site appear in the exceptions list.

### Actual behaviour

There is no user interface to allow a site exception for autoplay.

### Device name

Google Pixel 3

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

101.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20677)

**Comment by LaurentiuApahideanSV** [comment]
@wfaulk You can manually add an autoplay permission by tapping the lock button and selecting the appropriate permission from the autoplay drop down menu, see video for further information.

https://user-images.githubusercontent.com/50983519/178975805-d6dd8e33-700b-4a32-8382-eedad19a1e26.mp4
