### ISSUE TITLE
[Bug]: Passwords visible in Android 13 clipboard preview when copied from "Saved logins"

### ISSUE THREAD

**Issue by marcin-kozinski** [mozilla-mobile/fenix#25588]
### Steps to reproduce

On Android 13:
1. Open Settings.
2. Go to Logins and passwords.
3. Go to Saved logins.
4. Open a saved login.
5. Click the copy button next to the password.

### Expected behaviour

Password is masked in the clipboard preview, like this
![image](https://user-images.githubusercontent.com/2088582/173089380-40041d14-763a-4b5b-864e-5ccd00842cae.png)

### Actual behaviour

Password is not masked and visible in plain text in clipboard preview, like this
![image](https://user-images.githubusercontent.com/2088582/173089451-5845ce31-4eab-4e15-8ae3-24397a7d5907.png)

### Device name

Google Pixel 4

### Android version

Android 13

### Firefox release type

Firefox Beta

### Firefox version

102.0.0-beta.2

### Additional information

Here's a link to the section in Android 13 docs on how to handle this: https://developer.android.com/about/versions/13/features/copy-paste#sensitive-content

It's a matter of adding an extra to the clip description before setting the clip in the clipboard manager.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20688)

**Comment by marcin-kozinski** [comment]
There's an open pull request that just received some code review comments this week or last. The requested/suggested changes aren't too big, so I feel like this is sooo close to being fixed. Can we keep the issue open for a bit more and remove `wontfix`?

**Comment by onemahon** [comment]
@cschanaj are you still pursuing #25594? Looks like @boek left some comments for you to resolve if you'd like to revisit this to land it. Thanks!

**Comment by cschanaj** [comment]
Yes. I am going to work on it over the weekend.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814454

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 111.0a1 from 02/02 with Google Pixel 6 (Android 13). 

![1675324862179](https://user-images.githubusercontent.com/89388888/216266339-8203620f-58df-4992-acb0-b8923ef628b0.JPEG)
