### ISSUE TITLE
Update sumo link for the https-only setting

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25586]
As a followup to https://github.com/mozilla-mobile/fenix/issues/23337 based on https://bugzilla.mozilla.org/show_bug.cgi?id=1758066#c1 we have a new, custom link to use:
>  https://support.mozilla.org/en-US/kb/https-only-mode-firefox-android

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20687)

**Comment by TyDraniu** [comment]
Why is it en-US only? Shouldn't it be language dependent?

**Comment by Mugurell** [comment]
> Why is it en-US only? Shouldn't it be language dependent?

Good point. The article is not yet translated but can be in the future. Will update to allow for this.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 6/15 with OnePlus 9 (Android 12).

**Comment by Mugurell** [comment]
Support for localized documentation should be available in the next Nightly.

**Comment by TyDraniu** [comment]
Yes, it's OK now. Thanks.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly (2022-06-16T23:13:41.026448) using a Google Pixel 4 (Android 12).
