### ISSUE TITLE
[Bug] Glean not working to test telemetry

### ISSUE THREAD

**Issue by bsurd** [mozilla-mobile/fenix#2559]
## Steps to reproduce
1. Install Fenix.
1. Start it using glean services.

### Expected behavior
You are able to start the app using Glean.

### Actual behavior
Getting a not found error.

### Device information
* Android device: any
* Fenix version: tested with 5/16 and 5/14

![image](https://user-images.githubusercontent.com/17178945/57852603-3a8fca80-77ec-11e9-9663-8439ba87b337.png)

**Comment by dector** [comment]
Hi @bsurd! I think that you should use "adb shell am". [Take a look](https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/src/main/java/mozilla/components/service/glean/debug/GleanDebugActivity.kt#L17).

**Comment by rpappalax** [comment]
> Hi @bsurd! I think that `adb shell am ...` is what you need. [Take a look](https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/src/main/java/mozilla/components/service/glean/debug/GleanDebugActivity.kt#L17).

@bsurd sorry, Bogdan.  my mistake.  I omitted that from the testplan.  It's working now, so I'll close the issue
