### ISSUE TITLE
[Bug]: Overscroll effect not gone if finger is released outside of the window

### ISSUE THREAD

**Issue by Daniikk1012** [mozilla-mobile/fenix#25592]
### Steps to reproduce

1. Go to the bottom of a scrollable page
2. Swipe up and only release when outside the webpage (At the status bar)

### Expected behaviour

The overscroll effect should be gone after I release the finger

### Actual behaviour

The overscroll effect stays even though I released the finger. It only resets on the next overscroll

### Device name

Xiaomi Redmi Note 10 Pro

### Android version

Android 12 SKQ1.210908.001

### Firefox release type

Firefox

### Firefox version

101.2.0

### Additional information

This is probably not a MIUI issue, Firefox is the only application where I have found this bug. Additionally, if this is somehow related, sometimes the overscroll effect is fully gone (Don't know how to reproduce) and there is no way to cause it until I restart Firefox.

https://user-images.githubusercontent.com/49123959/173177943-ec600bb8-2959-4bb1-af9b-17b7e0c5e505.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20690)

**Comment by kbrosnan** [comment]
This is bz-1710708 via 1738691
