### ISSUE TITLE
regression in v100: bookmarks should open into a new tab

### ISSUE THREAD

**Issue by michel34** [mozilla-mobile/fenix#25599]
Before version 100 of Firefox for Android, opening a bookmark into a new tab was straight-forward:
- 3 dots menu
- bookmarks

Since version 100, it is far more difficult:
- 3 dots menu
- open new tab
- tap "back" to close keyboard
- 3 dots menu
- bookmarks

The new default behavior will open bookmark in the current tab, which in my experience is seldom useful.

Before version 100, opening a new tab was the default behavior and it was far more convenient. When this behavior was not expected, it was easy to close the current tab in the tab manager.

Since many people use bookmarks and tabs, I think that this request is useful for most users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20693)

**Comment by marcel263** [comment]
You may search the address bar for bookmarks. Also, you may tap "show all" next to "recent bookmarks".

**Comment by michel34** [comment]
I do not see what you are talking about. I have Firefox for Android 101.2.0.
Further, there is a hierarchical menu for the bookmarks, and my point is just that this menu should be easy to use, even when this is already an active tab.

**Comment by marcel263** [comment]
In your bug report you are stating "Since version 100," hence it was apparent that you were familiar with beta and nightly versions of Firefox for Android (Fenix).

On 103 at least, both options mentioned are available to attain your goal, though it could be made more clear visually, rightly so.

**Comment by michel34** [comment]
I just tried Nightly 103.0a1, and I think I understand your point, but even after enabling the "Recent bookmarks" in the homepage configuration, the recent bookmarks do not appear, neither does the "show all" option. What appear are the recent pages and "show all" is the full history.

Even if this would work, my request would still be relevant: there is a menu for the bookmarks, and I believe that most times, what is needed is opening the bookmark in a new tab. At least, there should be an easy way to do it.

**Comment by marcel263** [comment]
Obviously, you will need to stock the bookmarks first, at least one is needed to make it appear.

Bookmarks can be opened in new tabs via the three-dot-menu, although that could be better made into a changeable preference (despite it being a separate and much-requested issue)

**Comment by michel34** [comment]
I do have a full tree of bookmarks, and "Recent bookmarks" is enabled for the homepage, but still the recent bookmarks do not appear.

And yes, bookmarks can be opened from three-dots, but my request is that it is not easy to open a bookmark in a new tab.

See attached images (red circles indicate the tapped icon to reach the next screen):

1) using your solution: it fails, although "Recent bookmarks" is enabled
![home_page](https://user-images.githubusercontent.com/22117382/173366671-004b47d4-72b8-4927-b88f-c75f3d12f7e7.png)

2) the simplest solution I found to open a bookmark into a new tab: awful!
![new_tab_with_bookmark](https://user-images.githubusercontent.com/22117382/173366723-69acfa01-0988-4b69-aa3b-9fde9da917c2.png)

Is that clear?

**Comment by michel34** [comment]
1) "Recent bookmarks": absent in Firefox 101 and in Firefox Nightly 103, see my first set of screenshots.

2) "Open in new tab": OK, found, I had no idea this function could be there. Thank you, this does answer my request (although I would suggest to make it the default behavior, as it was before v100).

**Comment by michel34** [comment]
Using "open in new tab" in the bookmarks contextual menu, may I suggest that it should lead to the new tab. What I get is the tab list, with the new tab selected, which requires one more tap to effectively open it, and does not make sense to me.

**Comment by czlucius** [comment]
Related to #13336, but whether opening in the current tab or a new tab may be debatable.
Opening it in the current tab does make bookmarklets feasible though (and there is already a new tab in the 3 dot menu, so opening in current tab makes more sense)

**Comment by michel34** [comment]
I understand that some people find it more convenient to open bookmarks in the current tab by default.
What I still find not convenient is that:
1. it cannot be configured
2. when the bookmarks are organized in a tree, I must tap the name of the folders (not the 3-dot menu), and then the 3-dot menu of the bookmark item (not the name)
3. when the new tab is open, it is not displayed at once, instead the tab list is displayed and I have to tap on the new tab to display it. I suggest to remove this screen, as exemplified below, since I cannot think of any case in which it has any use:
![open_in_new_tab](https://user-images.githubusercontent.com/22117382/174447744-453536fd-04a5-4650-a556-a33e8d7a98af.png)

**Comment by DavidJCobb** [comment]
> I like that bookmarks are opened in the same tab. And apparently I'm not the only one: just search for issues in this repository.

Indeed. It makes far more sense that bookmarks open in a current tab, and is consistent with Fennec and desktop.

It sounds like a big usability issue here is the keyboard opening up automatically on the new tab page (which causes other jank as well; see #19099). If that didn't happen, it'd cut out two of the five steps OP has to take to open a bookmark in a new tab.

**Comment by marcel263** [comment]
> > I like that bookmarks are opened in the same tab. And apparently I'm not the only one: just search for issues in this repository.
> 
> Indeed. It makes far more sense that bookmarks open in a current tab, and is consistent with Fennec and desktop.
> 
> It sounds like a big usability issue here is the keyboard opening up automatically on the new tab page (which causes other jank as well; see #19099). If that didn't happen, it'd cut out two of the five steps OP has to take to open a bookmark in a new tab.

as stated above, the "show all" near the "recent bookmarks" section is likely the intended experience as it is explicitly put there in the front. It requires one swipe  down at most, no need to close the keyboard and access the menu that got hidden away.

**Comment by michel34** [comment]
> as stated above, the "show all" near the "recent bookmarks" section is likely the intended experience as it is explicitly put there in the front. It requires one swipe down at most, no need to close the keyboard and access the menu that got hidden away.

Sorry again, but as already explained, the "Recent bookmarks" do not appear on my smartphone (tried Firefox v101, Firefox Nightly v103), although they are enabled in the "Homepage" options. Besides, it would needs a lot of taps. See my screenshots:

![no_recent_bookmarks](https://user-images.githubusercontent.com/22117382/174566158-5c149474-4729-422a-b9bf-1c4ae2659249.png)

**Comment by michel34** [comment]
And yes, I can skip several screens by tapping on the "Home" icon. But this does not bring the “Recent bookmarks” block either.

**Comment by marcel263** [comment]
If you are unwilling to collaborate as suggested and file a bug report then you may repeat yourself but things are likely to remain the same. This place is for solving bugs first. The missing feature of recebt bookmarks should be there, and it is missing by mistake on your device.

**Comment by michel34** [comment]
I don't understand what you are expecting from me. I complained it is not easy to open a bookmark in a new tab, you told me how to do it, but it does not work.

**Comment by marcel263** [comment]
> I don't understand what you are expecting from me. I complained it is not easy to open a bookmark in a new tab, you told me how to do it, but it does not work.

The "show all" button missing is a bug. It deserves a separate bug report. This is not a support forum but a place to gather evidence for bugs. Please refer to the previous instructions on this page that may inspire you how to do it properly.

**Comment by michel34** [comment]
I tried to add a brand-new bookmark, and still no “Recent bookmarks”, it might be a bug, but I never wanted to use this, nor do I know what it is supposed to do, and which is a rational for displaying bookmarks added in the last 10 days. If the idea is to give access to the bookmarks from the homepage, a button or icon "bookmarks" on the homepage should do it.

**Comment by marcel263** [comment]
> I tried to add a brand-new bookmark, and still no “Recent bookmarks”, it might be a bug, but I never wanted to use this, nor do I know what it is supposed to do, and which is a rational for displaying bookmarks added in the last 10 days. If the idea is to give access to the bookmarks from the homepage, a button or icon "bookmarks" on the homepage should do it.

If you want to contribute then report the bug of the "recent bookmarks" feature missing. If you want to change the user experience, then suggest an improvement as was outlined above. If you need any help, then you may ask for it, naturally, or look through the Community Guidelines. This will all be more productive than repeating the same point to satisfaction.

**Comment by marcel263** [comment]
> The "recent bookmarks on the home screen" feature [appears](https://github.com/mozilla-mobile/fenix/blob/6f9e725ec58f0658bb6cde057782991395bc3485/app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt) to only show bookmarks added within the last ten days, _not_ your most recently added bookmarks. If you haven't actually added new bookmarks within the last ten days, you shouldn't see anything.
> 
> If I'm understanding the arguments being made here, though? Regardless of how it works, having to clutter the home screen with "recent bookmarks" in order to gain access to a "show all" button which presumably opens bookmarks in a new tab, is... not the most intuitive way to remedy this use case.

It is not to be taken literally, because the "recent bookmarks" is mentioned for its "show all" button. It is the fastest way to accomplish the task of opening the bookmarks menu from the start page.

The design was made like this, you can of course file an improvement suggestion as mentioned.

The "freshness" of 10 days gives room for improvement, this is a separate issue. It is not well communicated that it only shows up for 10 days. It would explain why the section may be missing 


A simple solution for this issue would be to have the keyboard be dismissed when swiping the start page instead of just hiding.

**Comment by alittlebitofit** [comment]
Tapping on a bookmark (from the saved bookmarks list) opens it in a current tab, which overrides whatever page is already loaded.

Default behavior should open it in a new tab.

**Comment by sonora** [comment]
I know of no other browser where opening bookmarks is intrinsically connected to opening new tabs. Such an unconventional behavior in Firefox alienates many potential users...

**Comment by alittlebitofit** [comment]
If I have to open a bookmark, I don't want to open a new tab first and then let that bookmarked page be opened inside that new tab.
That's one too many extra step.

**Comment by sonora** [comment]
I am simply talking about convention,  i.e. what a majority of users is familiar with.

Your assumption is that a bookmark should always open in a new tab. But when you think about it,  this has no more justification than it opening in the current tab?

(The extra tap needed you quote is in the other case needed to close the new tab again.)

**Comment by michel34** [comment]
Although I filled this bug report, I agree that this is not really a bug, just the way to open a bookmark in a new tab is not obvious to a naive user:
1) click on "Home" (top left icon) before selecting the bookmark. Probably obvious to the active developers, but not to the users
  OR
2) select the bookmarks, click on the bookmark folders (if any), do not click on the bookmark itself but on its 3-dot icon and select "open in a new tab" (well, in French the space is short so it looks like "Open in a new bo...").

Obviously, the developers assume using the Home page. But its purpose is not so obviously without an explanation.

I close this bug, I think it is not relevant.

**Comment by michel34** [comment]
Not a bug: best method is using the Home icon, alternative method is using 3-dot and "open in new tab"
