### ISSUE TITLE
Increased error rate for `metrics.search_count` and `browser.search.in_content` metrics due to invalid label

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/fenix#25602]
We see a spike in errors for the [`metrics.search_count`](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/metrics_search_count) metric ([Our monitoring dashboard](https://mozilla.cloud.looker.com/dashboards/382?Channel=mozdata.fenix.metrics&Submission%20Date=14%20day%20ago%20for%2014%20day), see the "Invalid Label" graph on the top right).

Channel: release.
The relevant code: https://github.com/mozilla-mobile/fenix/blob/01be73255ed18538412c47de5b7304d4aa4115b3/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt#L48

Labels are restricted to lowercase alphanumerics, underscores, dashes and dots ([see also our docs](https://mozilla.github.io/glean/book/reference/metrics/index.html#label-format)).
Maybe the identifier or source contains other characters? or the identifier is not always lowercased?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20695)

**Comment by cpeterso** [comment]
Looks like we're still seeing "Invalid Label" errors for the `metrics.search_count` and `browser.search.in_content` metrics, about 400 and 300 errors per day, respectively:

https://mozilla.cloud.looker.com/explore/fenix/metrics?qid=y2mXoHm29rnZSzSbpnfiPi&origin_space=746&toggle=vis

![image](https://user-images.githubusercontent.com/629193/183520293-efd450b5-a154-4e83-b9ad-6ea73bcc32f6.png)

**Comment by Mugurell** [comment]
The `source` can only take some values and it is always lowercased: https://github.com/mozilla-mobile/fenix/blob/f356df785c6b179953ddb1a35907f1224c4377d3/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt#L30-L46

&nbsp;

The identifier of bundled search engines is not lowercased before recording the telemetry and seems like we have some search engines which do use uppercase letters, eg: [`wikipedia-zh-CN`](https://github.com/mozilla-mobile/android-components/blob/086f7f8326e93d21d4bbfd78ef55fbd0916a5f48/components/feature/search/src/main/assets/search/list.json#L908).

Seems like lowercasing the search engine ids in Fenix/Focus before recording the telemetry is the best approach which would also ensure no newer search engines could cause this issue even if they are set to use uppercase letters.

**Comment by Mugurell** [comment]
Looking in Nightly it seems like the occurences went down a bit but might be too early to tell.
https://mozilla.cloud.looker.com/dashboards/382?Channel=mozdata.org%5E_mozilla%5E_fenix.metrics&Submission+Date=14+day+ago+for+14+day

**Comment by SoftVision-LorandJanos** [comment]
For the past 14 days:
On Nightly metrics.search_count was between 0 and 4.
![image](https://user-images.githubusercontent.com/48829350/190379688-12410830-0539-40d4-95cf-d930a4f29b3a.png)
On Nightly browser.search.in_content was between 0 and 7.
![image](https://user-images.githubusercontent.com/48829350/190379930-bcf9a762-3094-4b7b-b8af-464f5a849733.png)

On Beta metrics.search_count was between 0 and 2.
![image](https://user-images.githubusercontent.com/48829350/190380084-6c7b2d28-b6f7-431c-827d-447f333a4d71.png)
On Beta browser.search.in_content was between 2 and 28.
![image](https://user-images.githubusercontent.com/48829350/190380318-9cc06b05-5cba-4fcf-a68d-f0bfce31ee80.png)

Closing the ticket as verified.
