### ISSUE TITLE
FNX3-16410 ⁃ Changes to close private browsing

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2560]
## Steps to reproduce
Go to private browsing mode, no tabs open, read placeholder text.

### Expected behavior
Placeholder text should say: Firefox Preview clears your search and browsing history when you quit the app or close all private tabs.

### Actual behavior
First sentence is "Firefox clears your search and browsing history when you close your private session" --> That's misleading, people might assume that "close" == switch to normal mode in which case we keep the private tabs. We delete them once a user kills the app or all tabs are closed.

**Comment by mheubusch** [comment]
This wording  isn't wrong but I understand your concern that it is not precise enough.  After MVP launch, we can modify the first sentence to: Firefox Preview clears your search and browsing history when you quit the app or close all private tabs.

**Comment by mheubusch** [comment]
@vesta0 I moved this to the Post-MVP Milestone and  it is ready for dev. Can you prioritize and put in the appropriate sprint?

**Comment by vesta0** [comment]
Thanks @mheubusch will do

**Comment by vesta0** [comment]
@mheubusch and @topotropic do we want to consider re-introducing a button or a new way for users to quickly close private tabs?

**Comment by topotropic** [comment]
yes, that's part of the collections / multi-tasking review.

**Comment by nahuhh** [comment]
@vesta0 
I think the best implementation is simply to show a notification w

**Comment by mheubusch** [comment]
@vesta0 String updates were already provided for this issue:  
Firefox Preview clears your search and browsing history when you quit the app or close all private tabs.
I can address any string needs for quickly close all tabs in the multitasking designs.  I will remove the needs:strings label
