### ISSUE TITLE
[Bug]: In Javascript, HTMLInputElement.focus({ preventScroll: true }); still scrolls to centre the input

### ISSUE THREAD

**Issue by JohnAtPheasantVille** [mozilla-mobile/fenix#25606]
### Steps to reproduce

1. Referring to https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
2. Use the source provided in the 'Focus with option' section
3. Works as expected, specifically, the button is not scrolled into view with the "button without scrolling"
4. Use an <input> element instead of <button> element and repeat
5. The "Click me to focus on the button without scrolling!" still scrolls down and focuses on the input.
6. Works fine on desktop Firefox and on the DevTools emulator
7. Sample HTML page to illustrate attached as a .txt file
[test.txt](https://github.com/mozilla-mobile/fenix/files/8894231/test.txt)
.

### Expected behaviour

The <input> element should not be scrolled into view

### Actual behaviour

The <input> element is still scrolled to and positioned in the centre of the viewport.

### Device name

Samsung Galaxy S9+

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

101.2.0 (Build #2015885215)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20697)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1774639

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
