### ISSUE TITLE
FNX3-16411 ⁃ [Bug] Floating content on custom tab bottom

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2561]
## Steps to reproduce
1. Open [this site](https://www.droid-life.com/2019/04/18/amazon-and-google-are-friends-for-now-youtube-and-prime-video-everywhere/) in custom tab.

### Expected behavior
The content is floating 

### Actual behavior
The content shouldn't be floating 

![Screenshot](https://user-images.githubusercontent.com/773158/57854550-832c9100-77b6-11e9-8708-b8d56cd6e410.png)UNITO-UNDERSCORE!20190516-071952!

### Device information
* Android device: Pixel 3

**Comment by Amejia481** [comment]
After [this commit](https://github.com/mozilla-mobile/fenix/commit/d894ea6702030cd4fe23f1afbfb0e94661fd9a91), we added dynamically additional space between the bottom toolbar and content in normal browsing but is affecting the custom tab.

**Comment by vesta0** [comment]
@ekager let's hold off on this one for now

**Comment by ekager** [comment]
@vesta0 it's already been fixed :)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1920 (#11391807), with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9).
