### ISSUE TITLE
Unresponsive black/grey page in page preview after changing to another application for a bit

### ISSUE THREAD

**Issue by Jaakkonen** [mozilla-mobile/fenix#25611]
### Steps to reproduce

1. Open link from an application, for instance Telegram
2. Interact with the page for a bit
3. Change to another application via the app switcher menu (immediate 10s back and forth won't trigger the issue but being away for 1min and hopping through more applications makes the issue happen more often)
4. Change the app back to the firefox page preview application
5. Page is now black/grey and unresponsive to scroll, reload button doesn't work and the entire tab is unresponsive (switching to desktop mode does nothing. However find option opens the search bar but writing to it does nothing. Opening the preview page in application (moves the tab to the main app) keeps the tab unresponsive and refresh (or long press force refresh) don't do anything. Typing a new address into the address bar does nothing. The only way to recover is to open the address bar, copy the address, create a new tab and paste the address there. That obviously loses the info that was entered onto the web page.

### Expected behaviour

Tab doesn't crash. Reloading works

### Actual behaviour

Tab seems to crash.

### Device name

Samsung Galaxy S20 FE

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

101.0.0-beta.4

### Additional information

Battery saving mode is active. 4.4GB/6GB memory is used (doesn't seem to be OOM problem). Listing of Firefox crashes doesn't contain these unresponsive tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20704)

**Comment by jonalmeida** [comment]
Thanks for filing this! It's a bug with Custom Tabs (clicking a link from another app) as well as PWAs, another feature we also have. Since you filed this helpful bug report, I'd like to use this issue to track that work.

**Comment by kudlav** [comment]
Can confirm this with installed PWA. Only black screen after switching back to the PWA app.
 - Firefox 103 as default browser
 - Device: SM-A405FN
 - OS: Android 11

**Comment by kudlav** [comment]
Similar to: https://github.com/mozilla-mobile/fenix/issues/19157

**Comment by tiago-pontomais** [comment]
i'm having the same problem

**Comment by UlyssesZh** [comment]
Reproduced on my Samsung Galaxy S20 (Android 11).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807413

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
