### ISSUE TITLE
Make the Fenix about page copy-able 🤞

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2562]
### Why/User Benefit/User Problem
It makes reporting a bug much easier because when a user supplies the Fenix version and build version the user has to type it by hand.

![Screenshot](https://user-images.githubusercontent.com/773158/57855723-59c13480-77b9-11e9-9663-efa733ab104d.png)UNITO-UNDERSCORE!20190516-085126!

### What/Requirements.
Make the Fenix about page copy-able

### Acceptance Criteria (how do I know when I’m done?)
Long click on the text in the about Fenix page will trigger the copy pop-up menu.

**Comment by NotWoods** [comment]
Closed by #3081
