### ISSUE TITLE
FNX3-16413 ⁃ [Bug] Floating bottom content is partially covered by the quick action bar in normal browsing

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2563]
## Steps to reproduce
1. Open [this site](https://www.droid-life.com/2019/04/18/amazon-and-google-are-friends-for-now-youtube-and-prime-video-everywhere/) in Fenix.

### Expected behavior
The content should be on top of the quick action bar.
![Screenshot](https://user-images.githubusercontent.com/773158/57856609-6777b980-77bb-11e9-86a4-a924ecbfeb58.png)UNITO-UNDERSCORE!20190516-091310!

### Actual behavior
The content is partially covered by the quick action bar.
![Screenshot](https://user-images.githubusercontent.com/773158/57856506-39927500-77bb-11e9-8ca8-86bde22876fe.png)UNITO-UNDERSCORE!20190516-091232!

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1920 GeckoView 68.0a1

**Comment by pocmo** [comment]
Our behavior currently only cares about the toolbar. In this case it needs to take that additional view into account.

**Comment by pocmo** [comment]
@vesta0 I added this to the A-C triage list.

**Comment by vesta0** [comment]
Thank you @pocmo !

**Comment by reinhart1010** [comment]
Duplicate: https://groups.google.com/forum/m/#!topic/fenix-nightly/OCxossdeTQE

**Comment by pocmo** [comment]
Unassigning myself because of decision in #2689

**Comment by Amejia481** [comment]
No reproducible anymore, as we fixed the toolbar.

**Comment by bifleming** [comment]
Per Vesta/Emily, we are looking to do the dynamic toolbar still :)

**Comment by cpeterso** [comment]
I am told that @snorp is drafting an engineering plan for the GV and Gecko work to support the dynamic toolbar.

**Comment by ekager** [comment]
@bifleming if we want to investigate this as part of reintroducing the dynamic toolbar we shouldn't have QA look at it yet?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly 190821(#12330640) with OnePlus 5T (Android 9), Huawei P9 Lite (Android 6.0.1), and Sony Xperia Z5 Premium (Android 7.1.1), on several pages: droid-life.com, volkskant.nl, robafaves.cat.
