### ISSUE TITLE
[Bug]: [Fission] When Fission is set to true, the Tabs View Media State is not shown when the tab is opened for the first time.

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#25639]
### Steps to reproduce

1. Go to **about:config**.
2. Search for **fission.autostart** and set it to **true**.
3. Go to a website that can play media _(e.g. youtube.com)_.
4. Play a video.
5. Open the **Tabs Tray**.
6. Observe.

### Expected behaviour

A play/pause icon should be visible in the right corner of the tab that the media is playing on.

### Actual behaviour

The icon is not present.

### Device name

Huawei P40 Lite

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1 (Build #2015886507)

### Additional information

After re-opening the tab, the icon appears and it is working. The issue occurs on every new site that plays media.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20722)

**Comment by cpeterso** [comment]
Moved to Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1776927
