### ISSUE TITLE
[Bug]: [Fission] When Fission is active, the Media Notification Player is not displayed.

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#25640]
### Steps to reproduce

1. Go to *about:config*.
2. Search for *fission.autostart* and set it to *true*.
3. Go to a website that can play media _(e.g. youtube.com, soundcloud.com)_.
4. Play a video.
5. Invoke the Android notification bar and observe.
6. Lock the device and observe the lock screen.

### Expected behaviour

The Media Notification is active/displayed on the Android Notification bar and lock screen, and the user can play/pause/skip the playing media.

### Actual behaviour

The Media Notification is not displayed on the Android Notification bar and lock screen.

### Device name

Huawei P40 Lite

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 103.0a1 (Build #2015886507)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20723)

**Comment by cpeterso** [comment]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1776926
