### ISSUE TITLE
[Bug]: [Fission] When Fission is activated, changing the device orientation makes tabs tray go into a wrong position

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#25646]
### Steps to reproduce

1. Go to **about:config**.
2. Search for **fission:autostart**.
3. Set the option to **true**.
4. _Restart the app._
5. Open some tabs.
6. Open the **Tabs Tray**.
7. Tap on the _3 dot_ menu.
8. Rotate the device to _Landscape_ Mode.
9. Rotate the device back to _Portrait_ Mode.
10. Observe.

### Expected behaviour

The menu should maintain its initial position while rotating to the portrait mode.

### Actual behaviour

The menu changes its position.

### Device name

Huawei P40 Lite

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1 (Build #2015886507)

### Additional information

Related to #12585. Fission has to be set to true for this issue to happen.

https://user-images.githubusercontent.com/103257761/174067869-71b556cc-73ff-4f83-bf0c-d52f2e933e18.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20728)

**Comment by hkaancaliskan** [comment]
https://user-images.githubusercontent.com/17825767/174124670-ab405707-576a-4df1-b212-dfb1d8e6403b.mp4

No problem on A52 with Android 12. Fission enabled.

**Comment by hkaancaliskan** [comment]
@amocirean you opened #25783 so we can say that this issue is not related to fission? Maybe be related to huawei?
