### ISSUE TITLE
[Bug]: Killing PWA Process will pause the media content from the main browser's opened tab.

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#25644]
### Steps to reproduce

1. Go to a site that supports **PWA Creation** _(e.g SoundCloud.com, Instagram, Twitter)_.
2. When prompted, **install** the PWA.
3. Play some media in the **main** Fenix Browser _(e.g Soundcloud.com, RockFM sites)_.
4. **Minimize** the app, so the playback of the media file won't stop.
5. Open a PWA.
6. Scroll through the PWA.
7. Kill the PWA Process.
8. Observe.

### Expected behaviour

The media from the main Fenix Browser continues playing even after closing the PWA.

### Actual behaviour

The media playback stops when closing the PWA. 

### Device name

Huawei P40 Lite

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

102.0.0-Beta.5 (Build #2014886715)

### Additional information

I was able to reproduce this on Beta 5 and latest RC.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20727)

**Comment by marcel263** [comment]
#20444

**Comment by kbrosnan** [comment]
tracked as bz-1772837
