### ISSUE TITLE
FNX3-16414 ⁃ [Bug] top content covered by custom tab toolbar

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2564]
## Steps to reproduce
1. Open [this site](https://www.droid-life.com/2019/04/18/amazon-and-google-are-friends-for-now-youtube-and-prime-video-everywhere/) in a custom tab.

### Expected behavior
The top content shouldn't be covered by the toolbar

### Actual behavior
The top content is covered by the toolbar [video demo](https://drive.google.com/file/d/1c39nXe1W-ayrF0IPwmMWrIahJRhnv-Ku/view?usp=sharing)

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1920 GeckoView 68.0a1

**Comment by cadeyrn** [comment]
See #1727 and #2052.
