### ISSUE TITLE
QR code not scanning at full size

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-mobile/fenix#2565]
## Steps to reproduce
1. Try to pair a Fenix device with desktop
1. Fit the QR code to the reticle

### Expected behavior
* QR code scans when it fits the reticle

### Actual behavior
* QR code only scans when the camera is pulled out far away from the QR code

### Device information
* Android device: Nexus 5
* Fenix version: Latest

**Comment by vladikoff** [comment]
cc @csadilek @vladikoff

**Comment by ryanfeeley** [comment]
For example, here is the reticle lined up perfectly with the code.
![Screenshot_20190524-124602](https://user-images.githubusercontent.com/68213/58347818-d9d84180-7e2c-11e9-8b68-813ef0d53989.png)

**Comment by bifleming** [comment]
@vesta0 blocker?

**Comment by ryanfeeley** [comment]
Yes, pairing does not appear to work unless you pull the camera back. We should fix the camera and not scale the reticle down.

**Comment by csadilek** [comment]
Fix for this is up in A-C: https://github.com/mozilla-mobile/android-components/pull/3251
