### ISSUE TITLE
Tab title missing after history back

### ISSUE THREAD

**Issue by lilydjwg** [mozilla-mobile/fenix#25659]
### Steps to reproduce

1. open a site, e.g. https://github.com/
2. click any link to navigate to another page in the same tab
3. press Back key (or long press and select one)
4. view the tab tray

### Expected behaviour

The tab should have the page title "GitHub".

### Actual behaviour

The tab has the page url displayed instead.

This also affects adding a bookmark: if you add a history page as a bookmark, it won't have a title.

### Device name

Sony Xperia XZ2 Compact

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1 (Build #2015886603)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20736)

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Nightly 103.0a1 2022-06-24, but was unable to. @lilydjwg Could you please upload a short video illustrating the problem?
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 13)

**Comment by lilydjwg** [comment]
GitHub says my video is too large so I've uploaded here:

https://ttm.sh/w3u.mp4

**Comment by lilydjwg** [comment]
It still occurs and makes some of my history entries with titles.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812856

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
