### ISSUE TITLE
Track when a permission prompt is shown and what action user chooses

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25658]
Follow-up to https://github.com/mozilla-mobile/android-components/issues/12345

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20735)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly 104.0a1 (2022-07-05) build.
Example of result:
![image](https://user-images.githubusercontent.com/48829350/177332685-537df430-2be8-4add-b04c-40569129ee5f.png)
Closing the ticket as verified.
