### ISSUE TITLE
Add back printing on Android

### ISSUE THREAD

**Issue by aaronwi** [mozilla-mobile/fenix#25665]
still missing for 2+ years now

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20741)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/3709

Print to PDF is planned work and should be available in a few releases.

**Comment by aaronwi** [comment]
> Duplicate #3709
> 
> Print to PDF is planned work and should be available in a few releases.

why were both even ever removed?

**Comment by aaronwi** [comment]
still....
