### ISSUE TITLE
[Bug]: about:addons redirects to about:blank from about:about page

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#25660]
### Steps to reproduce

1. Go to about:about.
2. Tap on about:addons.
3. Tap on back button (With Fission activated).

### Expected behaviour

The about addons page is displayed.
Tapping on back returns to the about:about page.

### Actual behaviour

The about:addons redirects to about:blank.
Tapping once on back with Fission activated sometimes only removes the icon (see video).

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1 (2022-06-17)

### Additional information
This behaviour is also encountered on Focus Nightly 103 (although addons are not supported). With Fission enabled, if the about:addons is accessed from the about:about page, the icon disappears when tapping the back button.

Focus With Fission activated:

https://user-images.githubusercontent.com/89388888/174288874-1c2e7bd1-d24d-4f18-a574-ec128ea4561f.mp4

Fenix: Without fission activated:

https://user-images.githubusercontent.com/48829350/174282982-0794623b-6807-40bc-9613-2414344e7c39.mp4

Fenix With Fission activated:

https://user-images.githubusercontent.com/48829350/174283037-d2aaca8e-c13c-487f-9107-4d4d0dadad39.mp4

- Going directly to about:addons works as expected in the latest builds: Nightly (2022-06-17), 102.0.0-beta5 and 101.2.0RC.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20737)

**Comment by cpeterso** [comment]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1776924

**Comment by cpeterso** [comment]
Moved to Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1776924
