### ISSUE TITLE
[Bug][Fission]: Tab back button history is empty

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#25666]
### Steps to reproduce

1- Enable fission.
2- Open a tab and navigate to some sites
3- long press to back button to open history

### Expected behaviour

History shown

### Actual behaviour

It's empty

### Device name

Galaxy A52

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

759f0bd80+

### Additional information

https://user-images.githubusercontent.com/17825767/174403135-523b162c-f42d-4bea-a066-2237ac54678c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20742)

**Comment by hkaancaliskan** [comment]
Idk if related but when i swipe to go back, Firefox goes back for 3-4 times, maybe it can't save the history properly?

**Comment by hkaancaliskan** [comment]
There is some weirdness, i tracked the history and it's inconsistent.
Exact order of websites i visited is:
1- GitHub.com
2- Google ziraat
3- GitHub.com
4- GitHub Fenix
5- GitHub Fenix issues

![Screenshot_20220618-004738_Firefox Nightly](https://user-images.githubusercontent.com/17825767/174405422-71ab18e8-b240-4078-aa73-50b36eee2a1f.png)

**Comment by delia-pop** [comment]
Hi, @hkaancaliskan , I was able to reproduce your issue as described with Fission enabled, on Google Pixel 6 (Android 12). 
However, I cannot reproduce the behavior with the incorrect search entries displayed in History. Could you log in a separate issue for that, with steps to reproduce? Thank you!
