### ISSUE TITLE
[Bug]: Images reached through meta http-equiv Refresh don't get downloaded properly

### ISSUE THREAD

**Issue by ldeaddr** [mozilla-mobile/fenix#25668]
### Steps to reproduce

1. Open a tab
2. Go to a URL containing the following HTML (example): 
```html
<html>
    <head>
        <meta http-equiv="Refresh" content="0; url=https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/263px-Wikipedia-logo-v2.svg.png">
    </head>
</html>
```
3. Wait for the redirect and subsequent image loading to finish.
4. Long-press on the image.
5. Tap "Save image".

### Expected behaviour

Image file should be downloaded.

### Actual behaviour

The redirect page is downloaded.

### Device name

Motorola moto g(6) play

### Android version

9

### Firefox release type

Firefox

### Firefox version

101.2.0

### Additional information

This bug is also present in Nightly.
For convenience, the previously shown HTML can be reached as a web page [here](https://binmen.s3.eu-central-1.amazonaws.com/ff/redir.html).

https://user-images.githubusercontent.com/54293288/174409862-cb190520-ff7a-455b-a725-d10d25a76013.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20744)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 103.0a1 2022-06-23.
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 13)
