### ISSUE TITLE
FNX3-16416 ⁃ [Bug] javascript / wasm x10 slower on some devices

### ISSUE THREAD

**Issue by kscm** [mozilla-mobile/fenix#2566]
## Steps to reproduce
Website: https://kinoseed.com/
Steps:

1. Load any image in "Load Image"
1. Move a slider to modify image

### Expected behavior
Perform calculations and changes in less than 0.5 seconds

### Actual behavior
Fenix performs the calculations 10 times slower.

Situation is even worse, when adjusting in the tab for correcting light properties of the image, like "brightness", part of the calculations are performed in WASM. 
In this case, Firefox 66 makes the changes almost instantly, but Fenix does it in ~7 seconds.

### Device information
NOTE that this happens only on some devices, and is probably related to aarch optimizations.
Bug-reported to WebView component: [bug 1552132](https://bugzilla.mozilla.org/show_bug.cgi?id=1552132)

* Android device: 

affected:
Android 8, Snapdragon 625
Android 9, Snapdragon 835

NOT affected:
 Android 9, Snapdragon 632

* Fenix version: 1.0.1920 / 68.0a1

**Comment by vesta0** [comment]
@vickychin FYI

**Comment by kscm** [comment]
Using Firefox Preview Version 1.0.1922 build: arm64-v8a

After loading an image in kinoseed.com:

    Turning the phone to landscape
    Pressing [ ] to enter full-screen (btw, there's a separate new bug, which cuts the view up to the notification for "full-screen")
    Adjust "Brightness"

Time for brightness adjustment calculation on:

Android 8, Snapdragon 625, 2Ghz, 4GB RAM
~ 2 seconds

Android 9, Snapdragon 632, 1.8Ghz, 3GB RAM
~ 1 second

For comparison:
Using Firefox 67.0 on Android 8, Snapdragon 625, 2Ghz, 4GB RAM
~ 0.2 seconds

https://bugzilla.mozilla.org/show_bug.cgi?id=1552132

**Comment by bifleming** [comment]
@vesta0 priority?

**Comment by vesta0** [comment]
This is a performance bug and on the team's radar. Vicky gave it a p3. We will keep it open and track it.

**Comment by cpeterso** [comment]
This bug will require some deep performance work in Gecko's JavaScript JIT. It's on the JavaScript team's radar, but it's probably a lower priority than other work.

**Comment by kbrosnan** [comment]
closing as the bugzilla bug was closed works for me

**Comment by kscm** [comment]
unfortunately I spoke too soon.

The problem persists, however it doesn't seem to be device dependent as first thought !

Two almost identical images from camera roll (same settings taken seconds apart), and after one is loaded it produces 10x lag, and when the other is loaded - it works well.

Without restarting the app, loading the different images produces consistent (undesirable) results - the code runs fast when one of them is loaded, and lags when the other is loaded, which is really weird.

Again only happens with GV native platform arm64-v8a, and loading some images produce the problem.
I'll post a new bug report when I narrow the problem.
