### ISSUE TITLE
Approve Translate Web Pages addon

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/fenix#25672]
### What is the user problem or growth opportunity you want to see solved?

Allow users an easy way to translate from one language to another.  The existing [Translate Web Pages addon](https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/) is the obvious way to do this.  [Bergamot](https://browser.mt/) may be a future alternative but it has limited language support, particularly for APAC languages.

### How do you know that this problem exists today? Why is this important?

TWP has 600,000 installs on desktop and this feature existing in Chrome.

### Who will benefit from it?

Everyone visiting a foreign country and foreigners living in countries where they do not speak the native language well.

References FilipePS/Traduzir-paginas-web#67.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20745)

**Comment by kbrosnan** [comment]
We don't keep individual extension requests open.

**Comment by gaul** [comment]
https://connect.mozilla.org/t5/ideas/translation-add-on-firefox-for-android/idi-p/286 is the correct place to give feedback.
