### ISSUE TITLE
Blank/unexpected icon when adding some websites to home screen

### ISSUE THREAD

**Issue by czlucius** [mozilla-mobile/fenix#25673]
### Steps to reproduce

1. Go to one of these websites:
- https://raw.githubusercontent.com/mozilla-mobile/fenix/main/settings.gradle (GitHub Raw)
- https://accounts.firefox.com/ (Firefox Accounts)
2. Add them to device Home Screen

### Actual behaviour

A blank icon appears, which after some time/restarting, turns into an Android icon
![Screenshot_20220618-223744_One UI Home](https://user-images.githubusercontent.com/58442255/174443431-c39744ac-3b15-4218-af04-1d8ac4faa8f6.jpg)
![Screenshot_20220618-224220_One UI Home](https://user-images.githubusercontent.com/58442255/174443444-a9ca3d50-ec37-4cdf-8727-46e764110a5e.jpg)

### Expected behaviour

A placeholder icon is displayed for these websites.
E.g.
![Screenshot_20220618-224348_One UI Home](https://user-images.githubusercontent.com/58442255/174443504-9a7b0592-ad89-4fe3-ad13-db1fd0780ef7.jpg)

### Device name

Samsung Galaxy S20 FE 5G

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1 (Build #2015886507)

### Additional information

A placeholder icon for websites with no icons is displayed for some websites, but some websites do not have the icon and end up using a blank icon.

**Comment by SoftVision-LorandJanos** [comment]
Hi @czlucius. Thanks for your report.
I was able to reproduce the issue you described, on the latest Nightly 103.0a1 (2022-06-20).
Device used: Google Pixel 4 (Android 12).

**Comment by czlucius** [comment]
I mixed up Actual and Expected behaviour

**Comment by czlucius** [comment]
This issue still persists.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807412

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
