### ISSUE TITLE
Tab favicons disappear from tab grid view sometimes 

### ISSUE THREAD

**Issue by willfs84** [mozilla-mobile/fenix#25675]
### Steps to reproduce

Make sure the "Tab view" setting is set to "Grid".  Now, open some tabs and actually go to a few websites in those tabs. Then tap the tab view button, observe the favicons are there as expected. Now, force close Firefox. Now open Firefox and observe the favicons are gone! 

### Expected behaviour

Tabs should always have favicons present

### Actual behaviour

Favicons are not present sometimes. Screenshot attached. The screenshot on the right is what this issue looks like (I added red arrows)
![fenix favicon tabs](https://user-images.githubusercontent.com/47801466/174450274-914f5646-17a6-4205-a0f2-a1ce0f6855be.png)

### Device name

Google Pixel 3a XL

### Android version

12.1

### Firefox release type

Firefox

### Firefox version

101

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20747)

**Comment by SoftVision-LorandJanos** [comment]
Hi @willfs84. Thank you for your report!
I was able to reproduce the issue you described, on the latest Nightly 103.0a1 (2022-06-20).
Device used: Google Pixel 4 (Android 12).

**Comment by willfs84** [comment]
I can still repro this issue, please reopen. 

And btw, the stale bot is being way too aggressive. I filed this on June 18th! Please make the stale bot less aggressive

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812855

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
