### ISSUE TITLE
For Recent bookmarks, always display them instead of just for 10 days

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/fenix#25689]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)
As [mentioned](https://github.com/mozilla-mobile/fenix/issues/25599#issuecomment-1160580385_)  by @DavidJCobb

### What is the user problem or growth opportunity you want to see solved?
Right now, the Recent Bookmarks feature [shows bookmarks for 10 days](https://github.com/mozilla-mobile/fenix/blob/6f9e725ec58f0658bb6cde057782991395bc3485/app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt). This causes the Recent Bookmarks section to disappear if there is no new bookmark added in 10 days. Along with it, the "show all" button would disappear.

Have the Recent bookmarks always show x latest bookmarks, not just within  a period of time.
### How do you know that this problem exists today? Why is this important?
Frustrates the user experience of quickly opening Bookmarks menu right from the "home" page
Disadvantages users who only untermittantly add bookmarks, because the whole section is programmed to disappear after 10 days.
### Who will benefit from it?

Users who do not regularly make bookmarks but still want to access them quickly
Users who always want to access the bookmarks menu with a single tap

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20757)

**Comment by litLizard69** [comment]
Agreed, I don't even know why somebody thought that "only recent bookmarks shown" is a good idea. Just change it back to how it was on v68 where it was a seperate menu in the new tab page..

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809820

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
