### ISSUE TITLE
Fenix using a small caps font on certain websites

### ISSUE THREAD

**Issue by ChaosNicro** [mozilla-mobile/fenix#25682]
## Site with issue and any steps to reproduce
- Stackoverflow.com
- Github.com

As the title suggests, Fenix uses a non-standard font on websites like Stackoverflow or Github. In my case this font is "Carrois Gothic SC". I am not sure which font-family is being invoked (maybe monospace) or what specific font it is falling through. I 
would like to know how to find that though, maybe in the remote debug-console?

### Expected behavior

Chromium for comparison:
<details>
<summary>Click to expand</summary>

![Screenshot_Ungoogled Chromium](https://user-images.githubusercontent.com/5428578/174496254-70de1af0-f6a5-4796-9827-b179329121f5.png)
</details>

### Actual behavior

Fenix:
<details>
 <summary>Click to expand</summary>

![Screenshot_Fenix](https://user-images.githubusercontent.com/5428578/174496008-fe170e65-d6a9-4ee1-a279-8920001b77c0.png)
</details>

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
- No, The used font stays the same

### Can you reproduce in Chrome (or other non-Mozilla browser)?
- see picture above

### Device information

* Android device: Xiaomi Mi 11 Lite 5G (Renoir) running LineageOS 19.1
* Fenix version: 101.2.0 2022-06-09

### Additional Info

/system/fonts/:
<details>
  <summary>Click to expand</summary>

- AndroidClock.ttf
- CarroisGothicSC-Regular.ttf
- ComingSoon.ttf
- CutiveMono.ttf
- DancingScript-Bold.ttf
- DancingScript-Regular.ttf
- DroidSans-Bold.ttf
- DroidSansMono.ttf
- DroidSans.ttf
- NotoColorEmojiFlags.ttf
- NotoColorEmoji.ttf
- NotoNaskhArabic-Bold.ttf
- NotoNaskhArabic-Regular.ttf
- NotoNaskhArabicUI-Bold.ttf
- NotoNaskhArabicUI-Regular.ttf
- NotoSansAdlam-VF.ttf
- NotoSansAhom-Regular.otf
- NotoSansAnatolianHieroglyphs-Regular.otf
- NotoSansArmenian-VF.ttf
- NotoSansAvestan-Regular.ttf
- NotoSansBalinese-Regular.ttf
- NotoSansBamum-Regular.ttf
- NotoSansBassaVah-Regular.otf
- NotoSansBatak-Regular.ttf
- NotoSansBengaliUI-VF.ttf
- NotoSansBengali-VF.ttf
- NotoSansBhaiksuki-Regular.otf
- NotoSansBrahmi-Regular.ttf
- NotoSansBuginese-Regular.ttf
- NotoSansBuhid-Regular.ttf
- NotoSansCanadianAboriginal-Regular.ttf
- NotoSansCarian-Regular.ttf
- NotoSansChakma-Regular.otf
- NotoSansCham-Bold.ttf
- NotoSansCham-Regular.ttf
- NotoSansCherokee-Regular.ttf
- NotoSansCJK-Regular.ttc
- NotoSansCoptic-Regular.ttf
- NotoSansCuneiform-Regular.ttf
- NotoSansCypriot-Regular.ttf
- NotoSansDeseret-Regular.ttf
- NotoSansDevanagariUI-VF.ttf
- NotoSansDevanagari-VF.ttf
- NotoSansEgyptianHieroglyphs-Regular.ttf
- NotoSansElbasan-Regular.otf
- NotoSansEthiopic-VF.ttf
- NotoSansGeorgian-VF.ttf
- NotoSansGlagolitic-Regular.ttf
- NotoSansGothic-Regular.ttf
- NotoSansGrantha-Regular.ttf
- NotoSansGujarati-Bold.ttf
- NotoSansGujarati-Regular.ttf
- NotoSansGujaratiUI-Bold.ttf
- NotoSansGujaratiUI-Regular.ttf
- NotoSansGunjalaGondi-Regular.otf
- NotoSansGurmukhiUI-VF.ttf
- NotoSansGurmukhi-VF.ttf
- NotoSansHanifiRohingya-Regular.otf
- NotoSansHanunoo-Regular.ttf
- NotoSansHatran-Regular.otf
- NotoSansHebrew-Bold.ttf
- NotoSansHebrew-Regular.ttf
- NotoSansImperialAramaic-Regular.ttf
- NotoSansInscriptionalPahlavi-Regular.ttf
- NotoSansInscriptionalParthian-Regular.ttf
- NotoSansJavanese-Regular.otf
- NotoSansKaithi-Regular.ttf
- NotoSansKannadaUI-VF.ttf
- NotoSansKannada-VF.ttf
- NotoSansKayahLi-Regular.ttf
- NotoSansKharoshthi-Regular.ttf
- NotoSansKhmerUI-Bold.ttf
- NotoSansKhmerUI-Regular.ttf
- NotoSansKhmer-VF.ttf
- NotoSansKhojki-Regular.otf
- NotoSansLao-Bold.ttf
- NotoSansLao-Regular.ttf
- NotoSansLaoUI-Bold.ttf
- NotoSansLaoUI-Regular.ttf
- NotoSansLepcha-Regular.ttf
- NotoSansLimbu-Regular.ttf
- NotoSansLinearA-Regular.otf
- NotoSansLinearB-Regular.ttf
- NotoSansLisu-Regular.ttf
- NotoSansLycian-Regular.ttf
- NotoSansLydian-Regular.ttf
- NotoSansMalayalamUI-VF.ttf
- NotoSansMalayalam-VF.ttf
- NotoSansMandaic-Regular.ttf
- NotoSansManichaean-Regular.otf
- NotoSansMarchen-Regular.otf
- NotoSansMasaramGondi-Regular.otf
- NotoSansMedefaidrin-VF.ttf
- NotoSansMeeteiMayek-Regular.ttf
- NotoSansMeroitic-Regular.otf
- NotoSansMiao-Regular.otf
- NotoSansModi-Regular.ttf
- NotoSansMongolian-Regular.ttf
- NotoSansMro-Regular.otf
- NotoSansMultani-Regular.otf
- NotoSansMyanmar-Bold.otf
- NotoSansMyanmar-Medium.otf
- NotoSansMyanmar-Regular.otf
- NotoSansMyanmarUI-Bold.otf
- NotoSansMyanmarUI-Medium.otf
- NotoSansMyanmarUI-Regular.otf
- NotoSansNabataean-Regular.otf
- NotoSansNewa-Regular.otf
- NotoSansNewTaiLue-Regular.ttf
- NotoSansNKo-Regular.ttf
- NotoSansOgham-Regular.ttf
- NotoSansOlChiki-Regular.ttf
- NotoSansOldItalic-Regular.ttf
- NotoSansOldNorthArabian-Regular.otf
- NotoSansOldPermic-Regular.otf
- NotoSansOldPersian-Regular.ttf
- NotoSansOldSouthArabian-Regular.ttf
- NotoSansOldTurkic-Regular.ttf
- NotoSansOriya-Bold.ttf
- NotoSansOriya-Regular.ttf
- NotoSansOriyaUI-Bold.ttf
- NotoSansOriyaUI-Regular.ttf
- NotoSansOsage-Regular.ttf
- NotoSansOsmanya-Regular.ttf
- NotoSansPahawhHmong-Regular.otf
- NotoSansPalmyrene-Regular.otf
- NotoSansPauCinHau-Regular.otf
- NotoSansPhagsPa-Regular.ttf
- NotoSansPhoenician-Regular.ttf
- NotoSansRejang-Regular.ttf
- NotoSansRunic-Regular.ttf
- NotoSansSamaritan-Regular.ttf
- NotoSansSaurashtra-Regular.ttf
- NotoSansSharada-Regular.otf
- NotoSansShavian-Regular.ttf
- NotoSansSinhalaUI-VF.ttf
- NotoSansSinhala-VF.ttf
- NotoSansSoraSompeng-Regular.otf
- NotoSansSoyombo-VF.ttf
- NotoSansSundanese-Regular.ttf
- NotoSansSylotiNagri-Regular.ttf
- NotoSansSymbols-Regular-Subsetted2.ttf
- NotoSansSymbols-Regular-Subsetted.ttf
- NotoSansSyriacEastern-Regular.ttf
- NotoSansSyriacEstrangela-Regular.ttf
- NotoSansSyriacWestern-Regular.ttf
- NotoSansTagalog-Regular.ttf
- NotoSansTagbanwa-Regular.ttf
- NotoSansTaiLe-Regular.ttf
- NotoSansTaiTham-Regular.ttf
- NotoSansTaiViet-Regular.ttf
- NotoSansTakri-VF.ttf
- NotoSansTamilUI-VF.ttf
- NotoSansTamil-VF.ttf
- NotoSansTeluguUI-VF.ttf
- NotoSansTelugu-VF.ttf
- NotoSansThaana-Bold.ttf
- NotoSansThaana-Regular.ttf
- NotoSansThai-Bold.ttf
- NotoSansThai-Regular.ttf
- NotoSansThaiUI-Bold.ttf
- NotoSansThaiUI-Regular.ttf
- NotoSansTifinagh-Regular.otf
- NotoSansUgaritic-Regular.ttf
- NotoSansVai-Regular.ttf
- NotoSansWancho-Regular.otf
- NotoSansWarangCiti-Regular.otf
- NotoSansYi-Regular.ttf
- NotoSerifArmenian-VF.ttf
- NotoSerifBengali-VF.ttf
- NotoSerif-BoldItalic.ttf
- NotoSerif-Bold.ttf
- NotoSerifCJK-Regular.ttc
- NotoSerifDevanagari-VF.ttf
- NotoSerifDogra-Regular.ttf
- NotoSerifEthiopic-VF.ttf
- NotoSerifGeorgian-VF.ttf
- NotoSerifGujarati-VF.ttf
- NotoSerifGurmukhi-VF.ttf
- NotoSerifHebrew-Bold.ttf
- NotoSerifHebrew-Regular.ttf
- NotoSerif-Italic.ttf
- NotoSerifKannada-VF.ttf
- NotoSerifKhmer-Bold.otf
- NotoSerifKhmer-Regular.otf
- NotoSerifLao-Bold.ttf
- NotoSerifLao-Regular.ttf
- NotoSerifMalayalam-VF.ttf
- NotoSerifMyanmar-Bold.otf
- NotoSerifMyanmar-Regular.otf
- NotoSerifNyiakengPuachueHmong-VF.ttf
- NotoSerif-Regular.ttf
- NotoSerifSinhala-VF.ttf
- NotoSerifTamil-VF.ttf
- NotoSerifTelugu-VF.ttf
- NotoSerifThai-Bold.ttf
- NotoSerifThai-Regular.ttf
- NotoSerifTibetan-VF.ttf
- NotoSerifYezidi-VF.ttf
- Roboto-Regular.ttf
- RobotoStatic-Regular.ttf
- SourceSansPro-BoldItalic.ttf
- SourceSansPro-Bold.ttf
- SourceSansPro-Italic.ttf
- SourceSansPro-Regular.ttf
- SourceSansPro-SemiBoldItalic.ttf
- SourceSansPro-SemiBold.ttf
</details>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20751)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1776739

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by kbrosnan** [comment]
To further understand what is going on with this we would need to look at the installed fonts on your device.

* download and install the Android Platform tools for your operating system
https://developer.android.com/studio/releases/platform-tools
* Enable developer options for your device and enable USB debugging
* Run the command "adb devices" and make sure your device is authorized
* Create a folder "Android-fonts" and in that folder run the following
* "adb pull /system/fonts"
* Zip up the Android-fonts folder
* Attach it to the Bugzilla bug or if that is a bother add it here and I can copy it over

If you get stuck on a step ask here or email me. Headings 1, 2, 3, and 5 of https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information go into a little more detail about getting adb setup.
