### ISSUE TITLE
[Bug] Wikipedia pages are not displayed fully when Desktop site is checked

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#2568]
## Steps to reproduce
1. Open any Wikipedia page.
1. Request Desktop site.

### Expected behavior
The page is fully displayed.

### Actual behavior
The page is zoomed out - please see the attached video.

### Device information
* Android devices: Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8.0)
* Fenix version: 1.0.1920 (#11360657)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3187533/logcat.txt)

![2019](https://user-images.githubusercontent.com/40694158/57862099-7c2a7080-7800-11e9-8f78-a98ebe18531c.gif)UNITO-UNDERSCORE!05!UNITO-UNDERSCORE!16!

**Comment by cpeterso** [comment]
Can you reproduce this bug in R-B or Fennec?

I'm not able to reproduce this bug on my Moto G5 Plus in Fenix 1.0.1922 (#11511805), R-B, Focus+GV, or Fennec 67. Maybe it has something to do with screen size?

**Comment by softvision-miralobontiu** [comment]
I reproduce on the latest build of Reference Browser 6/3, but not on the latest Nightly (2019-06-03).
Tested with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by cpeterso** [comment]
@softvision-miralobontiu I asked a GV engineer to test this bug and they can't reproduce it either. (I'm using a Moto G5 and they're using a Google Pixel 2, I think.) I see the full desktop web page, shrunk to fit the screen width.

Are there any other steps or setting changes needed besides loading a Wikipedia article and then enabling Fenix's "Desktop site" setting? Does this zoom problem affect sites other than Wikipedia? What does Chrome's desktop mode do on your Sony Xperia Z5 Premium and HTC 10?

**Comment by softvision-miralobontiu** [comment]
@cpeterso I cannot reproduce this issue anymore.
Tested with 1.0.1924 (#11650657) build with HTC 10 (Android 8), and Sony Xperia Z5 Premium (Android 7.1.1).
I will close this issue.
