### ISSUE TITLE
[Bug]: When editing text in a textbox, Firefox makes it absurdly difficult to place the cursor on a blank line

### ISSUE THREAD

**Issue by DavidJCobb** [mozilla-mobile/fenix#25687]
### Steps to reproduce

1. Go to a site that lets you edit text. I went with https://editpad.org/tool/diff-checker.
2. Copy and paste the following block of text in.
3. Attempt to place the cursor on a blank line in the input. Attempt this at varying horizontal positions, and try zooming in to different levels, too.

> There's one more important aspect of this that we need to cover, and that's the idea of scale or dimension that's at work here. The further away you get from the individual, the less detailed the mental object becomes. A simple way of explaining this is to think of a crowd of people. Your brain doesn't see a collection of individuals; it just sees, well, a crowd, and treats them all like a giant, singular object. It's like this army [pictured] here: you don't think, "Oh, that's a lot of individuals;" you think, "That's a really big army."
> 
> So no matter what, in everyday life and in narrative, some level of objectification is inevitable. You're going to end up with disposable, interchangeable characters simply because less important characters are less important. The further you get from the main characters, the more object-like the characters get; that's just the reality of it.
> 
> 
> […]
> 
> The Immortals [from 300] are the example I love the most. They're built up as this super exotic fighting force, they're identified only as a collective group, and they all wear identical dehumanizing masks... but that's not all: once the masks are off, they're grotesque, with inhuman eyes, noses, and teeth. The Immortals are basically a checklist of objectifying features:
> 
> Instrumentality: They're a tool, both for the plot and for Xerxes; in the story, their only purpose is to demonstrate that the 300 are mortal by killing a few of them off.
> 
> Agency: They do what Xerxes commands without question and act as a swarm.
> 
> Ownership: They're Xerxes' property.
> 
> Fungibility: They're interchangeable and visually identical.
> 
> Violability: There's no moral ambiguity in killing them.
> 
> Subjectivity: Their feelings, motivations, and emotions are unimportant.
> 
> There you go. Really, you only need one of those for a character to be considered an object, and these guys hit all six.

I don't know if, like, _attribution_ is required, but that's a partial transcript of a Folding Ideas video on the film 300.

### Expected behaviour

It should be easy and painless to place the text editing cursor on a blank line, e.g. to begin typing a new paragraph in the middle of the input.

### Actual behaviour

It is absurdly difficult to place the text editing cursor on a blank line in most cases. The only way to do it consistently is to do so near the right edge of the textbox, or more specifically, well past the ends of the text for the lines above and below. Otherwise, Firefox _insists_ on forcing the cursor into the text above or below the gap you're trying to hit. You can literally start tapping from the right edge, see you hit the gap as desired, and then begin gently moving your fingertip leftward as you tap and see Firefox start snapping the cursor to the text on either line (sometimes even alternating which line it snaps to). Eventually, zooming in makes the font size, and thus the gap, large enough for Firefox to stop trying to "correct" your aim, but you have to zoom in pretty far.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

101.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20754)

**Comment by DavidJCobb** [comment]
Two more things:

1. Firefox may indent the text (to match the blockquote I've put it in here). I've been testing with unindented text. I can't edit this into my Op because GitHub or Firefox are buggy and are giving false-positive error messages (along the lines of "my post has been edited; refresh to see the changes").
2. I ran this test on Google Chrome and never once failed to place the text editing cursor on a blank line, even at half the font size needed to have a decent chance of it working in Firefox.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1775144

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
