### ISSUE TITLE
Grapics artifacts using Bluestacks

### ISSUE THREAD

**Issue by mailor33** [mozilla-mobile/fenix#25686]
### Steps to reproduce

Test Environment :

Host Environment :

Lenovo G7080
Intel i5-5200U / 8 GB RAM / 256 GB Kingston SSD
NVidia GeForce 920M

Windows 21H1 10 x64 19043.1766

Virtual Environment:
BlueStacks 5 / Nougat 32 bit with DirectX / Graphics Engine mode: Compatibility mode / 1 GB VirtualRAM / 2 Virtual Core

Pixel Density : 160 DPI selected
960x540 Landscape mode

Latest Firefox Android Stable (101.2.0) 

### Expected behaviour

Major misrendering of the entire screen...

### Actual behaviour

Major misrendering of the entire screen...

### Device name

BlueStacks5

### Android version

Android7.1.1

### Firefox release type

Firefox

### Firefox version

101.2.0

### Additional information

![Screenshot_2022 06 20_15 18 37 217](https://user-images.githubusercontent.com/65355324/174616402-906fd266-9ae1-45ef-96ca-d11f15e713e4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20755)

**Comment by hkaancaliskan** [comment]
I think it's better to report this issue to https://github.com/webcompat/web-bugs/issues

**Comment by jamienicol** [comment]
This is certainly a bug in bluestacks or the host environment. @mailor33 Have you tried reporting the issue to bluestacks?

My hunch would be that they're incorrectly limiting the size of PBO uploads not taking in to account the stride.
