### ISSUE TITLE
[Bug]: Select a text to search doesn't work the second time.

### ISSUE THREAD

**Issue by alittlebitofit** [mozilla-mobile/fenix#25696]
### Steps to reproduce

1. Open any website.
2. Select a text. A quick menu pops up, which helps you Copy, Search, Select all and Share.
3. Select Search. A new tab opens and a search engine (Google or DDG or others) searches the selected text.
4. Press back. The tab gets closed. The selected text is still selected.
5. Long press the already selected text for the options menu to popup.
6. Press Search.

### Expected behaviour

A new tab should open up and search the selected text.

### Actual behaviour

Nothing happens.

### Android version

12

### Firefox release type

Firefox

### Firefox version

101.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20762)

**Comment by marcel263** [comment]
Dear, your report seems to be a duplicate issue of #18565 is that correct? thank you for your report

**Comment by alittlebitofit** [comment]
Oh yes, thank you, that issue covers even more scenarios.

**Comment by SoftVision-LorandJanos** [comment]
As mentioned above, this issue is already covered in #18565.
I will close this one as duplicate.

**Comment by alittlebitofit** [comment]
@SoftVision-LorandJanos Why did you close this as "not planned" instead of "duplicate"?
