### ISSUE TITLE
[Bug]: Cannot visit sites with self-signed certs.  Missing UI option to add exception.

### ISSUE THREAD

**Issue by DanielVukelich** [mozilla-mobile/fenix#25691]
### Steps to reproduce

Visit any website with a self-signed cert. Eg: https://self-signed.badssl.com/

### Expected behaviour

I should get a warning page saying that the site is insecure.  That page should have an option to add an exception for the self-signed cert and continue to the website.

### Actual behaviour

I get a different page saying "Secure Connection Failed" with no option to add an exception or continue to the site.

This behavior broke some time in the last few days for me.  Firefox Android is the only browser on my phone that exhibits this behavior, as the others still allow me to create an exception.

### Device name

Galaxy S10

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1 (Build #2015887467), 2e0f44507+ AC: 103.0.20220619143131, 7b520d2b80 GV: 103.0a1-20220619065701 AS: 93.5.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20759)

**Comment by czlucius** [comment]
Probably related to this commit: https://github.com/mozilla-mobile/fenix/commit/d595e199c9eb2cd7f8f12aab1c9086bc083217b2

**Comment by clowncracker** [comment]
I'm still having this issue, even after the update.

**Comment by mcarare** [comment]
@clowncracker Unless you tested it with the github main branch code, you would have to wait for the next Nightly from the store to get the fix. The code was merged today.

**Comment by DanielVukelich** [comment]
I can confirm that this issue is resolved for me after updating to 103.0a1 (Build #2015888043), 8794cdb1e+
AC: 103.0.20220622143041, 74047eecb6
GV: 103.0a1-20220622094342
AS: 93.5.0
