### ISSUE TITLE
[Bug]: Login / Register not working. A "Cannot Complete Request" page is shown.

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#25701]
### Steps to reproduce

1. Open Firefox.
2. From the _3-dot_ menu, go to **Sign in to synchronise**.
3. Scan a **Desktop login QR Code** or tap on **Use email instead**. Issue also occurs on trying to create a new account.
4. Observe.

### Expected behaviour

The user is able to sign in / sign up without issues encountered.

### Actual behaviour

A "Cannot Complete Request" page is shown after scanning the QR Code or tapping on E-mail login method.

### Device name

Huawei P40 Lite

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

102.1.0

### Additional information

Here's a video of the issue reproduction:
https://user-images.githubusercontent.com/103257761/174820616-490a80a2-8c06-470c-bce6-b20f305c43f3.mp4

The issue occurs as well on Sony Xperia running Android 6.0.1
Tested as well on Google Pixel 6 (Android 12) and Huawei MediaPad M3 (Android 7),  but wasn't able to reproduce the issue.

The issue is reproducible on Beta 102.0.0-beta.5 (Build #2014886715). On the the Nightly 103.0a1 (Build #2015887659) build, a different message is shown:
<img src = https://user-images.githubusercontent.com/103257761/174820310-c877c367-b0af-498f-8fe1-3aebf13cac10.jpg width = 45%>

Logs: 
[logs.txt](https://github.com/mozilla-mobile/fenix/files/8949842/logs.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20766)

**Comment by mcarare** [comment]
I cannot reproduce this on any device on the latest main. 
@amocirean  On the devices you can reproduce this, do you have any security software that intercepts connections?
Can you load other secure pages on those devices?

**Comment by Amejia481** [comment]
> I cannot reproduce this on any device on the latest main. @amocirean On the devices you can reproduce this, do you have any security software that intercepts connections? Can you load other secure pages on those devices?

I wasn't able to reproduce on nightly, using pixel 3 with Android 12.

**Comment by amocirean** [comment]
The issue was caused by the wrong date & time on the device. After setting it right, the issue no longer occurs. This issue will be closed.
