### ISSUE TITLE
Remove "Daylight" from the "About Firefox" screen

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25721]
The product name is "Firefox", not "Firefox Daylight".

https://github.com/mozilla-mobile/fenix/search?q=Daylight&type=code

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20780)

**Comment by Alexandru2909** [comment]
Issue can only be tested on the release build.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest RC 103.1.0 build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.
