### ISSUE TITLE
[Bug]: Only shortcuts also shows history

### ISSUE THREAD

**Issue by Juan-132** [mozilla-mobile/fenix#25739]
### Steps to reproduce

1. Setup settings as below

### Expected behaviour

The new tab page should only show shortcuts

### Actual behaviour

The new tab page shows shortcuts and history
![Screenshot_20220623-234443_Firefox](https://user-images.githubusercontent.com/59505296/175408657-c7722317-546a-423b-bfef-35e302da1625.jpg)
![Screenshot_20220623-234522_Firefox](https://user-images.githubusercontent.com/59505296/175408679-b0117f93-bde8-4133-b183-337090362346.jpg)

### Device name

Galaxy A50

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

101.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20793)

**Comment by kbrosnan** [comment]
This was an intentional change.

**Comment by jawz101** [comment]
You guys don't see how duplicitous it is to the Recently Visited section?

Now I'm obsessively clearing my History as to clear up the junk on my homescreen.  I just want to see my Pinned Sites and that's it.

**Comment by Juan-132** [comment]
Don't know how to reopen this bug.
If anybody could do that...

**Comment by klcb2010** [comment]
> This was an intentional change. You can pin 8 sites to control what is displayed.
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥 This design is too stupid
