### ISSUE TITLE
FNX3-16420 ⁃ "Save to collection" from browser then back press should go to browser

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2573]
If you press "save to collection" in the browser fragment menu it puts you to the right collection fragment creation screen, but a back press doesn't land you back in the browser.

We should do a "FromBrowser" direction like we do for `openAndLoad` to properly route the back press.

mock: https://mozilla.invisionapp.com/d/main#/console/16853870/359019534/preview

**Comment by softvision-miralobontiu** [comment]
Verified as fixed with the latest build 1.0.1923 (#11560607), with Google Pixel (Android 9), and Xiaomi Mi 8 Lite (Android 8.1).
