### ISSUE TITLE
FNX3-16421 ⁃ [Bug] you can't press buttons on bottom content (unless the Fenix toolbar is hidden)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2574]
### Steps to reproduce
1. open a website with fixed content and links/buttons on the bottom of the website
1. press one of the links/buttons

Examples are the cookie bars on sozone.de, soeren-hentzschel.at, tympanus.net, …

### Expected behavior
The link/button works.

### Actual behavior
Nothing happens. You have to scroll until the Fenix toolbar is hidden, then the link/button on the website works.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 43843b0fb3921ca662f6ac3d40c69a3a5a91ee6f

**Comment by TitanNano** [comment]
I took a screencast of this:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4500858/57914339-b8a4ad80-788e-11e9-91f4-9ecb2ab6f8f0.gif)

**Comment by ekager** [comment]
Thanks for the detailed report! Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1552608

**Comment by bogas04** [comment]
Screencasts of the behavior as well as how Chrome handles it.

https://github.com/mozilla/firefox-preview-bughunting-campaign/issues/73#issuecomment-494248018

**Comment by cadeyrn** [comment]
This was fixed by disabling the dynamic toolbar. Should this issue be closed or kept open for post-MVP work?

**Comment by cpeterso** [comment]
A fix for the GV bug landed and should be available in tomorrow's GV 71 Nightly.

https://bugzilla.mozilla.org/show_bug.cgi?id=1552608#c47

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **Nightly Build #13640626 from 12/30** using the following devices:

• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191230_115458](https://user-images.githubusercontent.com/51314259/71577202-e4159900-2afb-11ea-967c-c645bc2457d7.gif)

**Comment by cadeyrn** [comment]
The issue was only present with the dynamic toolbar and never with the fixed toolbar. This should be retested once the dynamic toolbar lands again. ;-)

**Comment by AndiAJ** [comment]
I've just re-checked his matter setting the toolbar on TOP, which makes it dynamic and didn't encounter any issues.

► Video
![20191230_122255](https://user-images.githubusercontent.com/51314259/71578172-b894ad80-2aff-11ea-8cd0-30c5e893cc62.gif)

**Comment by cadeyrn** [comment]
Well, I guess with the top toolbar the top content has to be tested, not the bottom content. But I don't know if the problem ever existed for the top toolbar implementation because it was never a problem with the old Firefox which always had a top toolbar. ;-)

I will test once the dynamic bottom toolbar lands again. I hope it will happen soon. :)
