### ISSUE TITLE
[Bug]: Accessing hostname on local network requires prepending the protocol

### ISSUE THREAD

**Issue by AlexVGalvin** [mozilla-mobile/fenix#25757]
### Steps to reproduce

1. Have a webserver on your local network that is accessible via its hostname
2. Type "hostname:port" into the address bar

### Expected behaviour

Nothing loads, the screen remains blank.

### Actual behaviour

The webpage at that hostname and port should load

### Device name

Samsung S20 FE

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

101.2.0

### Additional information

This is a screen recording of me trying to access a service installed on my local network's NAS. 

https://user-images.githubusercontent.com/32237198/175784453-b72ea00d-7640-4188-8e6e-0b0dd8d29422.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20808)

**Comment by amocirean** [comment]
Hello @AlexVGalvin , thank you for submitting the issue.
I was able to reproduce it on the latest RC and Nightly


Device Used: Google Pixel 4
Android Version: 12
