### ISSUE TITLE
After switching search engine, search suggestions appear even when turned off in settings

### ISSUE THREAD

**Issue by mattmccutchen** [mozilla-mobile/fenix#25753]
### Steps to reproduce

1. Go to "Settings" -> "Search" and ensure that "Show search suggestions" is turned off.  Exit the Settings.
2. Start typing in the address bar.
3. Click the "Search engine" button, and then click on a different search engine in the menu.
4. Continue typing in the address bar.

### Expected behaviour

Search suggestions _should not_ appear because they are turned off in the settings.

### Actual behaviour

Search suggestions _do_ appear during step 4.

### Device name

Google Pixel 3a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.1.1

### Device logs

(I saved the logcat on my computer, but before sharing it, I'd need to review it for sensitive information, and I don't want to spend the time to do that unless/until the developers actually need the logcat, since the issue seems to be so easy to reproduce.)

### Additional information

[Screen recording](https://mattmccutchen.net/private/firefox-search-suggestions-bug-20220624-recording.mp4) (hosted on my own web server because the file is too big for GitHub).

The problem does not occur with Firefox 101.2.0, so this seems to be a regression.  I consider it a privacy problem, so I plan to stay on Firefox 101.2.0 until it's fixed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20806)

**Comment by SoftVision-LorandJanos** [comment]
Hi @mattmccutchen. Thank you for your report!
I could reproduce the issue you described on the latest Nightly 103.0a1 (2022-06-27) build.
Device used: Google Pixel 4 (Android 12).

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807594

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
