### ISSUE TITLE
FNX3-16422 ⁃ [Bug] Fenix cannot open shortened Google Form links (full length links work)

### ISSUE THREAD

**Issue by vrudesai** [mozilla-mobile/fenix#2576]
## Steps to reproduce
1. Open this sample Google Form link via Fenix: https://forms.gle/rCg3diu7NUQo7QQq9
1. Fenix populates the address bar with link but user sees nothing

### Expected behavior
1. Open this sample Google Form link via Fenix: https://forms.gle/rCg3diu7NUQo7QQq9
1. Google Form opens

### Actual behavior
Fenix populates the address bar with link but user sees nothing

### Device information
* Android device: ONEPLUS A6003 [Android Version 9] / Reproduced on Sony Xperia XZ1
* Fenix version: 1.0.1920

**Comment by bifleming** [comment]
@vesta0 priority?  don't think we'll get to investigation if we don't prioritize it. would it be a blocker?

**Comment by kbrosnan** [comment]
This works for me with a build from master but not on the build from June 6th. Commit 054635735a007cdb8851e45992930c9d6cf41c30 is what I built master from.

**Comment by kbrosnan** [comment]
PR #3191 likely fixed this

**Comment by kbrosnan** [comment]
@vrudesai Would you check an up to date build. This still works for me using a build with the fix I mentioned.

**Comment by sv-ohorvath** [comment]
I can reproduce this on Samsung Note 8 (Android 9) and Nexus 5 (Android 6.0.1), on the 6/12 nightly build.

**Comment by vrudesai** [comment]
@kbrosnan The link still does not load on an up to date build.

**Comment by kbrosnan** [comment]
The suspected fix was backed out. I expect if you were to use a build from May 30th to June 11th it would work. #1570 was the fix. #3358 was the disabling.

**Comment by npark-mozilla** [comment]
Just to be clear, it seems like the problem exists for all shortened urls, not just Google forms.

**Comment by sblatz** [comment]
Looks like this is actually broken in Reference Browser & Sample Browser.
Filing an [ac issue]() to track this.

**Comment by sblatz** [comment]
This is blocked on us enabling android intent URL handling. (in #3223).

**Comment by rocketsroger** [comment]
For testing:
https://goo.gl/maps/nKsAVkJcGmTTMQ7a9

**Comment by rocketsroger** [comment]
Testing results from various browsers:
https://docs.google.com/spreadsheets/d/1XDvIJbWsmXk1JL5oM-znKPEWwcfEwnyXtXGiKB7hHjU

**Comment by rocketsroger** [comment]
A-C issue created https://github.com/mozilla-mobile/android-components/issues/4573

**Comment by rocketsroger** [comment]
Bug opened for GeckoView
https://bugzilla.mozilla.org/show_bug.cgi?id=1600704

**Comment by rocketsroger** [comment]
Confirmed on nightly that this issue is fixed.  (with `open links in apps` on or off)

**Comment by rocketsroger** [comment]
Please confirm fixed.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 200303 (Build #20630608) GV: 75.0a1-20200301094802 using a Samsung Galaxy S8+ (Android 8.0.0) and Huawei MediaPad M3 Lite 10 (Android 7.0). When tapping on a shortened link the google form opens.

**Comment by rocketsroger** [comment]
Thanks for verification.  Confirmed fixed, closing.
