### ISSUE TITLE
[Bug]: Other apps were opened instead of Firefox when clicking it from "Share via"

### ISSUE THREAD

**Issue by gh-supersudo** [mozilla-mobile/fenix#25778]
### Steps to reproduce

1. Press share
2. Select Firefox
3. Other app gets opened

### Expected behaviour

It should open Firefox

### Actual behaviour

It opens other apps when Firefox is selected

### Device name

Redmi Note 5 Pro

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

Firefox 101.2.0

### Additional information

This bug is rare, but once it happened, it happens for like a few consecutive times. It's kind of frustrating.

~~[Here is an example. Fennec was selected but a notepad was opened instead](https://streamable.com/s2cogb)~~

~~[Here is an another example. Fennec was selected but Discord was opened](https://streamable.com/6qqwcb)~~

I have "Open links in a private tab" and "Allow screenshots in private browsing" enabled, I don't know if that information is going to be useful but that's there.

Edit: 
[Here's another example where the error occurred but on Firefox v101.2.0](https://streamable.com/ny2n49)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20819)

**Comment by marcel263** [comment]
Dear, Fennec is a third-party build, please either make sure this bug reproduces in official build, or file the bug to its corresponding maintainer accordingly

**Comment by gh-supersudo** [comment]
Fennec F-Droid's issue tracker links to this repo so this is where I posted it.

https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

**Comment by marcel263** [comment]
> Fennec F-Droid's issue tracker links to this repo so this is where I posted it.
> 
> https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

That is understandable.

Regardless, neither with Fennec F-Droid nor with Nightly could this be reproduced.

OneUI 3.1 Android 11

**Comment by gh-supersudo** [comment]
> > Fennec F-Droid's issue tracker links to this repo so this is where I posted it.
> > https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/
> 
> That is understandable.
> 
> Regardless, neither with Fennec F-Droid nor with Nightly could this be reproduced.
> 
> OneUI 3.1 Android 11

The thing is, it only happens rarely. 

Is there a way to log the events every time the browser was opened?

**Comment by ale82to** [comment]
unfortunately the bug you are describing has nothing to do with fenix itself ,it's due to android 11 there 's also a bug report in Google but has not solved yet and I doubt it will ever be

**Comment by gh-supersudo** [comment]
> unfortunately the bug you are describing has nothing to do with fenix itself ,it's due to android 11 there 's also a bug report in Google but has not solved yet and I doubt it will ever be

Is it okay if you link the bug report?

**Comment by gh-supersudo** [comment]
Changed Fennec to Firefox because the bug also occurred there.

**Comment by gh-supersudo** [comment]
[This also occurred on 103.0.0-beta.3 of Firefox Beta on Android where it just copied the link instead of opening the link in the browser.
](https://streamable.com/ykbzpe)
