### ISSUE TITLE
FNX3-16423 ⁃ [Bug] save to collection: tabs flicker when selecting / unselecting

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2577]
### Steps to reproduce
1. open one or more tabs
1. go to home screen and press "save to collection" button
1. select / unselect tabs

### Expected behavior
no flickering.

### Actual behavior
When select / unselect a tab the tab disappers for a short moment.

![20190516](https://user-images.githubusercontent.com/1100614/57881817-82314900-7822-11e9-9e86-9bb57199d0c0.gif)UNITO-UNDERSCORE!212150!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 43843b0fb3921ca662f6ac3d40c69a3a5a91ee6f

**Comment by sv-ohorvath** [comment]
Verified as fixed on the 6/5 build.
