### ISSUE TITLE
[Bug] Long press - no paste option

### ISSUE THREAD

**Issue by nikoloskid** [mozilla-mobile/fenix#2578]
## Steps to reproduce
![60699281](https://user-images.githubusercontent.com/12738743/57883208-db4eac00-7825-11e9-967f-8b6faf28e9e3.jpg)UNITO-UNDERSCORE!584242731985684!UNITO-UNDERSCORE!8319928792877367296!UNITO-UNDERSCORE!n!

1. I copy my account number saved on my cloud
1. I go to the download page on a [vpn provider ](https://mullvad.net/en/download/wireguard-config/)
1. I long press account number, and cannot paste the account number.

### Expected behavior
* Copied the account number, long pressed it on the field and should have option to paste.

### Actual behavior
* No paste option

### Device information
* Android device: Huawei P20 Lite / 8.0
* Fenix version: 1.0.1920

**Comment by nikoloskii** [comment]
After restarting the browser, I got a delay but the long gave me "paste" and "select all" options.
