### ISSUE TITLE
"Add to shortcuts" menu entry should be hidden if Shortcuts are disabled on the Homepage

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#25792]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Overall consistency. If I change something in one area of the app, I'd like to see that the rest of the application respond appropriately. 

### How do you know that this problem exists today? Why is this important?

1. Go to Settings > Homepage
2. Disable "Shortcuts"
3. Go to any webpage
4. tap meatball menu

What happens: "Add to shortcuts" is shown in the menu. 

People have posted about [this](https://www.reddit.com/r/firefox/comments/vdgb2a/is_there_a_way_to_get_rid_of_these_menu_items_the/ickgwmb/). It is easier to find what you are looking for if erroneous menu options aren't present in the menus. This menu option is erroneous and not useful because the user will never see the added shortcut. 

### Who will benefit from it?

Any user who disables shortcuts on the home page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20832)

**Comment by DavidJCobb** [comment]
The Fenix development team has already flat-out rejected the idea of letting users customize the three-dot menu in any way, per #25647.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813787

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
