### ISSUE TITLE
Tapping on search engine icon should not enter input mode

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25809]
When user tap on the search engine icon in the toolbar, we should allow search engine selection menu popup without entering input mode. (No virtual keyboard should show)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20847)

**Comment by rocketsroger** [comment]
Menu and the caret should be shown the same way in display mode and edit mode of the toolbar.

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Nightly 109.0a1 (2022-11-22) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
