### ISSUE TITLE
Build with SDK for Android 13 / API 33

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#25808]
See A-C: https://github.com/mozilla-mobile/android-components/issues/12378

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20845)

**Comment by cpeterso** [comment]
GeckoView bug to target Android API 33 (Android 13): https://bugzilla.mozilla.org/show_bug.cgi?id=1771343

**Comment by cpeterso** [comment]
Corresponding Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1796353
