### ISSUE TITLE
Remove "Show search engines" toggle when unified search is enabled

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25814]
Remove "Show search engines" toggle in search settings when unified search is enabled

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20849)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly 108.0a1 (2022-11-07).
The "Show search engines" toggle is no longer displayed in Search settings when Unified search is enabled.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
