### ISSUE TITLE
Unified search search suggestions should based on which search engine is being used

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25816]
Update what search suggestions are being shown by following the table below

![Screen Shot 2022-06-29 at 12 55 26 PM](https://user-images.githubusercontent.com/6579541/176493340-d9a5abc9-c354-4082-a1c2-1679d5ff29b1.png)

&nbsp;
**Petru: Confirmed with @Verdi that the "Ads" suggestions shown the table are not applicable.**
&nbsp;
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20854)

**Comment by rocketsroger** [comment]
For search engines that are not listed on the table, show history, bookmark and tabs only if the domain matches the search engine.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 111.0a1 (2023-02-06) build.
Device used: Google Pixel 7 (Android 13).
Closing the ticket as verified.
