### ISSUE TITLE
Add header to unified search engine menu

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25811]
Add header in the unified search engine menu.  The header should say "This time search:"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20848)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 108.0a1 (2022-11-03) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
