### ISSUE TITLE
Send and share videos to TV

### ISSUE THREAD

**Issue by nikoloskid** [mozilla-mobile/fenix#2581]
### Why/User Benefit/User Problem
* There is browsers that you can send videos with to Samsung TV, LG TV, etc. The feature to share and send videos to your connected TV, is pretty dope, I would like it to see on Firefox.

### What/Requirements
It requires a connected TV to same wifi as your phone, so you can send videos easily to your TV with your phone.

### Acceptance Criteria (how do I know when I’m done?)
* Connected TV on same network

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11524)

**Comment by ekager** [comment]
CC @liuche 
> we have plans to make this possible on Fire TV via Firefox Accounts, and also rough plans to make this happen on Android TV next year (also via Firefox Accounts).

**Comment by nikoloskii** [comment]
> CC @liuche
> 
> > we have plans to make this possible on Fire TV via Firefox Accounts, and also rough plans to make this happen on Android TV next year (also via Firefox Accounts).

Great news, can't wait for Android TV feautre.

**Comment by Lululalu** [comment]
@ekager great news, but unfortunately it still excludes the TVs made by the two main manufacturers, Samsung, and LG. They use Tizen OS and Web OS, respectively.

**Comment by Mugurell** [comment]
I think you're referring to the cast option for which we also have https://github.com/mozilla-mobile/fenix/issues/3068

**Comment by boek** [comment]
Closing as a dup of #3068
