### ISSUE TITLE
Split deleting site data from browsing history

### ISSUE THREAD

**Issue by robmv** [mozilla-mobile/fenix#25818]
### What is the user problem or growth opportunity you want to see solved?

On the privacy section of the settings, Delete browsing data, the only way to delete site data is to remove the entire browsing history. Spitting the two kind of data (history and site data) makes sense when the user wished is to cleanup any kind of tracking data from all sites, like when clearing cookies, but without losing the browsing history.

### How do you know that this problem exists today? Why is this important?

Site data, like _localStorage_ can be used to track user visits to a site much like cookies, It would be an advantage to do it without losing the browsing history. 

#### Other implementations:

- Firefox desktop on _Clear recent history_ has a separate data section from browsing history.
- Firefox desktop on _Settings - Clear Data_ merge the cookies and site data options.
- Chrome Android merge the cookies and site data options too.

### Who will benefit from it?

Privacy conscious users that like to clear data with some frequency or at application exit, can take advantage of removing potential identifying information without losing the browsing history.

Note: I searched for another issue and found a recent one locked and generated by a ghost user for obvious rules violations), so I decided to open a new one as a fresh start for discussion.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20856)

**Comment by mortyobnoxious** [comment]
Same thing exist on "delete browsing data on quit".

These two definitely needs to be split.

![image](https://user-images.githubusercontent.com/42044258/208264341-1a751e5a-40ca-4368-be21-af9e55d6af84.png)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813788

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
