### ISSUE TITLE
Unified search engine menu popup should give hints to the user that more selection is available by scrolling

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25810]
If the unified search engine menu popup does not fit completely, always show hint (by cutting off the end entry) that there are more selection available by scrolling.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20846)

**Comment by t-p-white** [comment]
Would a scrollbar achieve the desired affect here?

https://user-images.githubusercontent.com/1833156/199737291-02d6ce36-e2cb-4080-8233-159355a51c8e.mp4
