### ISSUE TITLE
Unified search should use specific hint

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#25813]
When the user is searching for history, bookmarks or tabs, the hint should say "Search history", "Search bookmarks" and "Search  tabs".

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20850)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 108.0a1 (2022-11-03) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
