### ISSUE TITLE
Low-reproducibility home screen performance regression in COLD MAIN first frame

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#25821]
#25545 saw a large bimodal performance regression. https://github.com/mozilla-mobile/fenix/pull/25738 reduced the regularity of the regression. Due to difficulty debugging (limited access to a low-end device that could reproduce), the call was made to ship that patch and keep an eye on future performance. Additionally, it was thought that improvements to our profiling process in #25259 as well as general Compose upgrades could make the issue easier to improve in the future. This issue is intended to track the performance over time. 

The underlying issue was thought to be an increase in number of elements being rendered. Specifically, it appeared that Pocket content was rendered during the first frame more reliably.  #25738 addressed this by forcing Pocket to wait to render until after the first frame. 

This is the result of those changes, benchmarks captured on a nightly build on a Moto G5:
![image](https://user-images.githubusercontent.com/10427470/176559782-3469a3f0-819a-427b-b5b8-ed6290cd3b48.png)
![image (1)](https://user-images.githubusercontent.com/10427470/176559785-35b4927a-35f9-44d5-9502-e651fcaf2387.png)

There were a couple suggestions about further improvements down the line:
- a skeleton UI to be rendered first, and then populated after first frame with real data as it arrived
- a priority system that loaded low-intensity elements first

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20858)

**Comment by mcomella** [comment]
Triage: We filed #25919 to track down the increased bimodal occurrences. This bug was meant to track a low occurrence count of this bimodal so this bug isn't really needed anymore, given the higher rate. Let's dupe #25919.
