### ISSUE TITLE
Add an option to edit/delete bookmarks when you search them in the bookmarks menu

### ISSUE THREAD

**Issue by officiallor** [mozilla-mobile/fenix#25822]
### What is the user problem or growth opportunity you want to see solved?

When you search for a bookmark, user should be able to edit/delete the bookmark by either long tapping or like the normal list menu, by using the 3 dots.

### How do you know that this problem exists today? Why is this important?

I tried finding and deleting or editing some bookmarks and I wasn't able to. I had to scroll down, find the bookmark and then delete it. This makes bookmark search kinda useless because you already can type on the URL bar keywords of your bookmark and visit it.

### Who will benefit from it?
Everyone and the app itself that will get such a useful feature 😃

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20859)

**Comment by amocirean** [comment]
Hello @officiallor , thank you for submitting the issue
Based on the following situation, the correct label (Feature Request) will be assigned.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812701

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
