### ISSUE TITLE
[Bug]: Twitter video playing in upside down

### ISSUE THREAD

**Issue by zputnyq** [mozilla-mobile/fenix#25827]
### Steps to reproduce

1. Login to twitter.
2. Play a video on any of the followed account.
3. The video is playing in upside down

### Expected behaviour

Twitter video plays normally

### Actual behaviour

Twitter video playing in upside down

### Device name

Xperia M4 E2306

### Android version

6.0.1 stock

### Firefox release type

Firefox

### Firefox version

101.2.0 & 101.1.1

### Additional information

![_20220630_165245](https://user-images.githubusercontent.com/31039796/176650950-f319c800-8d99-4cbd-88c4-2a6ab3f85454.JPG)

Device Screen
Density: xhdpi (320 DPI)
Scaling factor: 2.0
Size: 720px × 1280px
Window size: 720px × 1184px
Refresh rate: 60.0 Hz

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20863)

**Comment by jamienicol** [comment]
@zputnyq could you please go to about:support, click on "copy text to clipboard", and attach the information to this bug. Thanks.

**Comment by zputnyq** [comment]
<h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" id="app-basics" data-l10n-id="app-basics-title">Application Basics</h2>

      

Name | Firefox
-- | --
101.0.1
20220608170832
 
Mozilla/5.0 (Android 6.0.1; Mobile; rv:101.0) Gecko/101.0 Firefox/101.0
Linux 23 #1 SMP PREEMPT Mon Sep 26 05:24:44 CST 2016
0/0
0/0               Disabled by default
1
Found
Found
Found
false
1.8 GB
5.4 GB




    Application Basics
------------------

Name: Firefox
Version: 101.0.1
Build ID: 20220608170832
Distribution ID:
User Agent: Mozilla/5.0 (Android 6.0.1; Mobile; rv:101.0) Gecko/101.0 Firefox/101.0
OS: Linux 23 #1 SMP PREEMPT Mon Sep 26 05:24:44 CST 2016
Multiprocess Windows: 0/0
Fission Windows: 0/0 Disabled by default
Remote Processes: [1](https://github.com/mozilla-mobile/fenix/issues/25827#remote-processes)
Google Location Service Key: Found
Google Safebrowsing Key: Found
Mozilla Location Service Key: Found
Safe Mode: false
Memory Size (RAM): 1.8 GB
Disk Space Available: 5.4 GB

Crash Reports for the Last 3 Days
---------------------------------

Nightly Features
----------------

Remote Processes
----------------

Type: Web Content
Count: 1 / 2

Add-ons
-------

Name: Mozilla Android Components - Ads Telemetry
Type: extension
Version: 101.0.11.0608213518
Enabled: true
ID: ads@mozac.org

Name: Mozilla Android Components - Browser Icons
Type: extension
Version: 101.0.11.0608213055
Enabled: true
ID: icons@mozac.org

Name: Mozilla Android Components - Firefox Accounts WebChannel
Type: extension
Version: 101.0.11.0608213525
Enabled: true
ID: fxa@mozac.org

Name: Mozilla Android Components - ReaderView
Type: extension
Version: 101.0.11.0608213347
Enabled: true
ID: readerview@mozac.org

Name: Mozilla Android Components - Search Telemetry
Type: extension
Version: 101.0.11.0608213518
Enabled: true
ID: cookies@mozac.org

Name: Mozilla Android Components - Web Compatibility Interventions
Type: extension
Version: 101.0.0
Enabled: true
ID: webcompat@mozilla.org

Graphics
--------

Features
Compositing: WebRender
Asynchronous Pan/Zoom: touch input enabled; autoscroll enabled; smooth pinch-zoom enabled
WebGL 1 Driver WSI Info: EGL_VENDOR: Qualcomm Inc. EGL_VERSION: 1.4 EGL_EXTENSIONS: EGL_QUALCOMM_shared_image EGL_KHR_image EGL_KHR_image_base EGL_QCOM_create_image EGL_QCOM_gpu_perf EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_KHR_lock_surface3 EGL_KHR_fence_sync EGL_KHR_wait_sync EGL_KHR_cl_event EGL_KHR_cl_event2 EGL_KHR_reusable_sync EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_renderbuffer_image EGL_EXT_create_context_robustness EGL_EXT_yuv_surface EGL_ANDROID_blob_cache EGL_KHR_create_context EGL_KHR_gl_colorspace EGL_KHR_surfaceless_context EGL_KHR_create_context_no_error EGL_KHR_get_all_proc_addresses EGL_QCOM_lock_image2 EGL_KHR_partial_update EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_framebuffer_target EGL_ANDROID_image_crop EGL_IMG_image_plane_attribs IsWebglOutOfProcessEnabled: 0
WebGL 1 Driver Renderer: Qualcomm -- Adreno (TM) 405
WebGL 1 Driver Version: OpenGL ES 3.1 V@140.0 (GIT@Ia10634f51b)
WebGL 1 Driver Extensions: GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_blit_framebuffer_params
WebGL 1 Extensions: ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_sRGB EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context
WebGL 2 Driver WSI Info: EGL_VENDOR: Qualcomm Inc. EGL_VERSION: 1.4 EGL_EXTENSIONS: EGL_QUALCOMM_shared_image EGL_KHR_image EGL_KHR_image_base EGL_QCOM_create_image EGL_QCOM_gpu_perf EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_KHR_lock_surface3 EGL_KHR_fence_sync EGL_KHR_wait_sync EGL_KHR_cl_event EGL_KHR_cl_event2 EGL_KHR_reusable_sync EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_renderbuffer_image EGL_EXT_create_context_robustness EGL_EXT_yuv_surface EGL_ANDROID_blob_cache EGL_KHR_create_context EGL_KHR_gl_colorspace EGL_KHR_surfaceless_context EGL_KHR_create_context_no_error EGL_KHR_get_all_proc_addresses EGL_QCOM_lock_image2 EGL_KHR_partial_update EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_framebuffer_target EGL_ANDROID_image_crop EGL_IMG_image_plane_attribs IsWebglOutOfProcessEnabled: 0
WebGL 2 Driver Renderer: Qualcomm -- Adreno (TM) 405
WebGL 2 Driver Version: OpenGL ES 3.1 V@140.0 (GIT@Ia10634f51b)
WebGL 2 Driver Extensions: GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_blit_framebuffer_params
WebGL 2 Extensions: EXT_color_buffer_float EXT_texture_filter_anisotropic MOZ_debug OES_texture_float_linear OVR_multiview2 WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context
Target Frame Rate: 60
GPU #1
Active: Yes
Description: Model: E2306, Product: E2306, Manufacturer: Sony, Hardware: qcom, OpenGL: Qualcomm -- Adreno (TM) 405 -- OpenGL ES 3.1 V@140.0 (GIT@Ia10634f51b)
Vendor ID: Qualcomm
Device ID: Adreno (TM) 405
Driver Version: OpenGL ES 3.1 V@140.0 (GIT@Ia10634f51b)
RAM: 0

Diagnostics
AzureCanvasBackend: skia
AzureContentBackend: skia
AzureFallbackCanvasBackend: skia
CMSOutputProfile: Empty profile data
Display0: 720x1280
DisplayCount: 1
Decision Log
HW_COMPOSITING:
available by default
force_enabled by user: Force-enabled by pref
OPENGL_COMPOSITING:
available by default
force_enabled by user: Force-enabled by pref
WEBRENDER:
available by default
WEBRENDER_QUALIFIED:
available by default
WEBRENDER_COMPOSITOR:
disabled by default: Disabled by default
WEBRENDER_PARTIAL:
available by default
WEBRENDER_SHADER_CACHE:
available by default
WEBRENDER_OPTIMIZED_SHADERS:
available by default
WEBRENDER_ANGLE:
available by default
unavailable by env: OS not supported
WEBRENDER_DCOMP_PRESENT:
available by default
disabled by user: User disabled via pref
unavailable by env: Requires Windows 10 or later
unavailable by runtime: Requires ANGLE
WEBRENDER_SOFTWARE:
available by default
WEBGPU:
disabled by default: Disabled by default
blocked by runtime: WebGPU cannot be enabled in release or beta
VP8_HW_DECODE:
available by default
VP9_HW_DECODE:
available by default




Media
-----

Audio Backend: opensl
Max Channels: 2
Preferred Sample Rate: 48000
Roundtrip latency (standard deviation): ...
Output Devices
Name: Group
Default audio output device:
Input Devices
Name: Group
Default audio input device:

Enumerate database

Environment Variables
---------------------

Important Modified Preferences
------------------------------

browser.search.region: ID
extensions.lastAppVersion: 101.0.1
media.gmp.storage.version.observed: 1
security.remote_settings.crlite_filters.checked: 1656688212
security.remote_settings.intermediates.checked: 1656688212

Important Locked Preferences
----------------------------

fission.autostart.session: false

Accessibility
-------------

Activated: false
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.33
Version in use: 4.33

NSS
Expected minimum version: 3.78.1
Version in use: 3.78.1

NSSSMIME
Expected minimum version: 3.78.1
Version in use: 3.78.1

NSSSSL
Expected minimum version: 3.78.1
Version in use: 3.78.1

NSSUTIL
Expected minimum version: 3.78.1
Version in use: 3.78.1

Startup Cache
-------------

Disk Cache Path: /data/user/0/org.mozilla.firefox/files/mozilla/abqq5o0r.default/startupCache/startupCache.8.little
Ignore Disk Cache: false
Found Disk Cache on Init: true
Wrote to Disk Cache: false

Internationalization & Localization
-----------------------------------

Application Settings
Requested Locales: ["en-US"]
Available Locales: ["an","ar","ast","az","be","bg","bn","br","bs","ca","cak","cs","cy","da","de","dsb","el","en-CA","en-GB","en-US","eo","es-AR","es-CL","es-ES","es-MX","et","eu","fa","ff","fi","fr","fy-NL","ga-IE","gd","gl","gn","gu-IN","he","hi-IN","hr","hsb","hu","hy-AM","id","is","it","ja","ka","kab","kk","kn","ko","lij","lo","lt","lv","ml","mr","ms","my","nb-NO","ne-NP","nl","nn-NO","oc","pa-IN","pl","pt-BR","pt-PT","rm","ro","ru","sk","sl","son","sq","sr","sv-SE","ta","te","th","tr","trs","uk","ur","uz","vi","wo","xh","zam","zh-CN","zh-TW"]
App Locales: ["en-US","en-CA","en-GB"]
Regional Preferences: ["en-US"]
Default Locale: "en-US"
Operating System
System Locales: ["en-US"]
Regional Preferences: ["en-US"]

Remote Debugging (Chromium Protocol)
------------------------------------

Accepting Connections: false
URL:

**Comment by AdinaPetridean** [comment]
The issue is still reproducible on: Firefox 102.1.1 and Firefox Nightly 104.0a1- 7/5 with Tab: Sony Xperia (Android 6.0.1).

**Comment by zputnyq** [comment]
> The issue is still reproducible on: Firefox 102.1.1 and Firefox Nightly 104.0a1- 7/5 with Tab: Sony Xperia (Android 6.0.1). Not reproduced on Google Chrome.

I confirm this. This issue still happens

**Comment by jamienicol** [comment]
Do you know whether this used to occur in a previous version of firefox? We fixed [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1731980) previously where videos were playing at the wrong size, and it feels like this could be related.

**Comment by jamienicol** [comment]
And do you see this on other websites too, or just twitter? How about youtube?

**Comment by zputnyq** [comment]
> Do you know whether this used to occur in a previous version of firefox? We fixed [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1731980) previously where videos were playing at the wrong size, and it feels like this could be related.
I'm not really sure since I only use stable release but I think It has started to happen since v101.1.1.


> And do you see this on other websites too, or just twitter? How about youtube?

Youtube is fine. Haven't tried other websites

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1778150

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by pcercuei** [comment]
> Would it be possible to capture a logcat whilst using [this apk](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/AAFDSdooTmK7RfIMaNVrhQ/runs/0/artifacts/public/build/geckoview_example.apk) to reproduce the bug? Thanks

Attached here: [firefox_logcat.txt.gz](https://github.com/mozilla-mobile/fenix/files/9053627/firefox_logcat.txt.gz)

**Comment by jamienicol** [comment]
Thank you that's incredibly helpful. I understand what the problem is now. Now I just need to figure out how to solve it

**Comment by zputnyq** [comment]
It's no longer happen on nightly 104.0a1.
Thank you, I really appreciate it. 🙏
