### ISSUE TITLE
Let Facebook chat be usable

### ISSUE THREAD

**Issue by suoko** [mozilla-mobile/fenix#2583]
### Why/User Benefit/User Problem
No need for fb app
Now it says to install the app

**Comment by Lululalu** [comment]
You can use the chat by going to to m.basic.facebook.com, but anyway, I agree with you. Kiwi already has this feature implemented.

**Comment by kbrosnan** [comment]
We don't have any control over the website Facebook sends Firefox. You can give Facebook feedback at https://www.facebook.com/help/1126628984024935?helpref=hc_global_nav

**Comment by suoko** [comment]
How is kiwi overriding Facebook chat rules?
