### ISSUE TITLE
[Bug][L10N]: "Undo" button from snackbar is not translated in Punjabi

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#25839]
### Steps to reproduce

1. Open the Android "Language and Input" settings. Set the Language to Punjabi.
2. Open Fenix and go to History.
3. Delete one item and observe the snackbar.
4. Go to Bookmarks.
5. Delete one item and observe the snackbar.

### Expected behaviour

The "Undo" button is translated in Punjabi.

https://pontoon.mozilla.org/pa-IN/firefox/browser/browser/customizeMode.ftl/?search=customize-mode-undo-cmd&string=197740

### Actual behaviour

The "Undo" button is not translated in Punjabi.

### Device name

Google Pixel 4

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

103.0.0-beta1

### Additional information

![Screenshot_20220630-175205](https://user-images.githubusercontent.com/48829350/176709250-6f8d13e7-7e69-44eb-bbe7-3e104d50abf2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20872)

**Comment by bcolsson** [comment]
The correct string for Firefox Android can be found here (the link under Expected is to the desktop version):  https://pontoon.mozilla.org/pa-IN/firefox-for-android/all-resources/?search=undo&string=198013
It appears the translated string is also using EN for this locale.

**Comment by bcolsson** [comment]
@SoftVision-LorandJanos - I've notified the localizer about the use of English here and asked whether it's intentional. They may or may not change the string, but I think we're okay to close this issue.

**Comment by SoftVision-LorandJanos** [comment]
Based on the comment above, I will close this ticket as not planned.
