### ISSUE TITLE
FNX3-16428 ⁃ Open a tab collection

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2584]
### Why/User Benefit/User Problem
* I want to be able to restore a collection I've created to my current session

### Acceptance Criteria (Added by PM. For EPM to track when a Meta feature is done)
* When I open the overflow menu, I see an "open tabs" option
* When I select the open tabs button my current session is populated with the collection's tabs

**We need UX for this!**

**Comment by sblatz** [comment]
@topotropic Are you able to provide ux for this?

**Comment by topotropic** [comment]
https://mozilla.invisionapp.com/share/WGS31ICCSQK#/364064023_Open_Tabs_From_Collection

- when someone opens a single tab from a Collection the page opens and the tab is displayed as first item in Open tabs on start screen
- when someone opens the whole collection, the first tab in the Collection opens and all tabs are listed in the same order as they were listed in the Collection at the top of Open tabs on start screen

**Comment by mheubusch** [comment]
@topotropic Question from dev: How do we trigger restoring  a single tab in the collection?

**Comment by topotropic** [comment]
> @topotropic Question from dev: How do we trigger restoring a single tab in the collection?

when someone opens a single tab from a Collection the  selected page opens and the tab is displayed as first item in Open tabs on start screen --> does that answer the question?

**Comment by sblatz** [comment]
@topotropic How does someone "open a single tab from a collection"?

The only way we have to "open tabs" right now is when someone goes through the overflow menu and presses "open tabs" which would restore the whole collection.

**Comment by topotropic** [comment]
Ok, here's how to open a single tab from a Collection:
1. Tap on single tab
2. Site opens
3. When you go back to start screen, new tab is first in list

**Comment by sblatz** [comment]
> when someone opens the whole collection, the first tab in the Collection opens and all tabs are listed in the same order as they were listed in the Collection at the top of Open tabs on start screen

@topotropic I feel like this behavior is a bit confusing. Is it possible we could just move the tabs from the collection into the current session and allow the user to select which tab they want to open? I feel like opening the first tab in the collection could be disorienting since it has no greater importance over tabs in the rest of the collection.

**Comment by topotropic** [comment]
> Is it possible we could just move the tabs from the collection into the current session and allow the user to select which tab they want to open?

yes, sounds good, let's do that.

**Comment by sv-ohorvath** [comment]
Verified on the 5/22 build.
devices: Galaxy Note 8 (Android 9), P9 lite (Android 6)
