### ISSUE TITLE
Fenix and Focus auto-grant or auto-deny storage access without showing a Storage Access prompt

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25848]
### Steps to reproduce

1. Set `dom.storage_access.auto_grants` pref = false in Fenix and Focus 104 Nightly.
1. Loaded the test site https://senglehardt.com/test/dfpi/storage_access_api.html.
1. Click the "requestStorageAccess()" buttons in column 1 or 2.

### Expected result:

Fenix and Focus should show a Storage Access prompt like Firefox desktop does.

### Actual result:

Fenix and Focus auto-grant storage access without showing a Storage Access prompt. (Click the "requestStorageAccess()" buttons in column 3 or 4 auto-denies storage access in Fenix and Focus, but shows a prompt on desktop.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20880)

**Comment by Amejia481** [comment]
I think I found what it the issue.

I was missing an additional step, enabling TCP (Total cookie protection)  `network.cookie.cookieBehavior` to `5`
`network.cookies.cookieBehavior.pbmode` to `5`. Here the full [STR](https://github.com/mozilla-mobile/fenix/issues/22852#issuecomment-998990236).  be aware of [Bug #1746031](https://bugzilla.mozilla.org/show_bug.cgi?id=1746031) that it is an outstanding bug.

In Focus , that already has [TCP](https://github.com/mozilla-mobile/focus-android/pull/7310) enabled it should be showing  but we have a regression, I put a [PR](https://github.com/mozilla-mobile/focus-android/pull/7310) for addressing the issue.

Sorry about the missing step, it was a long time ago when we implemented the feature :sweat_smile:, luckily  you discovered the [Focus regression](https://github.com/mozilla-mobile/focus-android/pull/7310).

Please feel free to re-open if needed

![image](https://user-images.githubusercontent.com/773158/176760521-11c06cc6-f803-4b75-b718-208d296b3e92.png)
![image](https://user-images.githubusercontent.com/773158/176760540-5a8da32a-7d1a-4c91-a717-dff5cbec969c.png)
![image](https://user-images.githubusercontent.com/773158/176760562-e6152cb8-60d4-4716-a28c-c68a310827dd.png)
