### ISSUE TITLE
An empty address can be saved

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25845]
### Steps to reproduce

1. Go to Settings -> Autofill and tap on the (+) "Add address" button.
2. Leave the form empty and attempt to save the address.

### Expected behaviour

The use is not allowed to save an empty address, since the "First Name", "Last Name", "Street Address", "Zip Code" and "Country/Region" (filled in by default) fields are mandatory. An error message is displayed informing the user about the required fields.

### Actual behaviour

The empty address can be saved, without displaying any error message.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly 104.0a1 from 06/29

### Additional information
![EmptyAddress](https://user-images.githubusercontent.com/89388888/176730117-10822070-9d23-4611-ac01-675fca11eebf.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20875)

**Comment by mcarare** [comment]
Technically, the address fields are not all empty, because the state field is selected by the default with the first value (should it? cc: @MatthewTighe )
At the moment we do not have specs for required fields, so this should be revisited only after we get some.

**Comment by MatthewTighe** [comment]
It looks like Desktop defaults to only filling the country field. It would take some investigation to determine whether that is done based on locale or some other method. Personally I think that this behavior is probably fine for now, but I'm tagging product in case they have interest in defining the correct behavior for mobile and prioritizing this.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814164

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
