### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by alekseiryndenko** [mozilla-mobile/fenix#25851]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20882)

**Comment by delia-pop** [comment]
Closing as invalid. 
@alekseiryndenko if you attempt to report an issue, please consult the [Contributing guide](https://github.com/mozilla-mobile/shared-docs/blob/main/android/CONTRIBUTING.md#filing-issues).
