### ISSUE TITLE
Show tab bar on devices with larger screens.

### ISSUE THREAD

**Issue by Andereoo** [mozilla-mobile/fenix#25858]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I just installed firefox on an android tablet today, expecting to see a behaviour somewhat similar to firefox on ipads. Instead, I found that it is identical to firefox on android phones, with no tab bar. The tab tray is great for devices with small screens, but for devices with bigger screens, such as tablets, it is a real nuisance - simply clicking a tab on the top as you would on desktop firefox is a lot quicker and easier. Seeing as some other web browsers (eg. chrome) have this, and seeing as firefox on ipads does this, it would make sense that firefox on tablets would also show a tab bar. I think a tab bar, or at least an option to enable one, would make firefox a lot easier to use on android tablets.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20886)

**Comment by sflorean** [comment]
Closing as a duplicate based on the comment above, and please follow the discussions there.
