### ISSUE TITLE
[Bug]: Link to donate money to Fennec/Fenix/Firefox on Android is broken on F-Droid

### ISSUE THREAD

**Issue by vn971** [mozilla-mobile/fenix#25860]
### Steps to reproduce

1. Go to https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/
2. Click on the "Donate" link, which directs to https://sendto.mozilla.org/page/contribute/openwebfund
3. Observe a 404 page

### Expected behaviour

See a page that allows donating to Fennec/Fenix/Firefox.

### Actual behaviour

The page is broken with 404, I can't donate.

### Device name

N/A

### Android version

N/A

### Firefox release type

Firefox

### Firefox version

101.1.1

### Device logs

N/A

### Additional information

"Fennec F-Droid" is an open-source build of Fenix (Firefox on Android).
I want to donate some money to this cause, however, I've found out that the referenced "donations" link does not work.

I know that formally Fennec is not the same as Fenix or Firefox. However, obviously Fennec tries to direct all donations to Fenix rather than to the shim that builds the fully open-source version for F-Droid. (I think so because the donation link is within mozilla.org.) I don't actually know what link is correct for donations either, so I can't just go to F-Droid and ask them to have that fixed.

Thoughts?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20887)

**Comment by kbrosnan** [comment]
We don't build the F-Droid APK. Please report it to the F-Droid forums.
