### ISSUE TITLE
Needs serious work on known basic funcionality.

### ISSUE THREAD

**Issue by cdenigris** [mozilla-mobile/fenix#25869]
Amazing how the nightly features never make it to this. Why is there no pull down to refresh?!?

Why is there no casting option? This is available on apps let alone other browsers

Why is there no print option?  

Why does scrolling pause briefly and require you to lift your finger and reapply. Not an issue in Chrome or other apps.

Mozilla we want to love you but you will never be mainstream again if you don't start taking this seriously. 

Please start to address the issues. I want to get family on this and away from Chrome and these things are so basic.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20895)

**Comment by Whatever11223** [comment]
I like the sound of that auto scrolling feature you mentioned.

**Comment by mueenulit** [comment]
I like 👍 all the features you mentioned... 😏 
I really want to love ❤ Mozilla ...

**Comment by mueenulit** [comment]
I'm gonna post this on Mozilla Connect..

**Comment by cadeyrn** [comment]
Please open one issue per feature request and/or bug report and make sure that no issue already exists. For pull to refresh and print there are definitively already open issues.

**Comment by kbrosnan** [comment]
Closing due to multiple requests in a single report.

**Comment by cdenigris** [comment]
You gotta be kidding Kevin. How about getting stuff done instead of ignoring it. Giving you quality stuff here when the Mozilla fan base is dwindling and you have a solid member here giving you solid feedback.

**Comment by aaronwi** [comment]
firefox android is dead
