### ISSUE TITLE
Remove the search string (URL) validation in "Add search engine"

### ISSUE THREAD

**Issue by MasterInQuestion** [mozilla-mobile/fenix#25867]
&#xA0;&#xA0;&#xA0;&#xA0;It's in general pretty much useless and in some cases counter-productive: preventing useful things like "https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=%s" being added.
&#xA0;&#xA0;&#xA0;&#xA0;Related: #9831, #10605, #11332

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20894)

**Comment by prg318** [comment]
This is a very annoying bug - it prevents certain searxng instances from being added.  In some cases (judging from the search engine server access logs), firefox mobile doesn't even make a request to the server.

There should at the very least be an option to disable this pointless validation.  Ideally firefox mobile should support OpenSearch like chrome-based browsers for android and desktop firefox, but in the short term, disabling this broken URL validation code would allow for all custom search engines to be used.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813776

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
