### ISSUE TITLE
[Bug]: importing logins/passwords

### ISSUE THREAD

**Issue by guillaumeportails** [mozilla-mobile/fenix#25862]
### Steps to reproduce

Open Firefox for Android
Try to import a CSV file exported from Firefox for Windows
You can't

### Expected behaviour

A menu for importing CSV passwords files should exists.
This way is totally offline so much more secure than sync and all others web based scenarios.

### Actual behaviour

No menu found

### Device name

Samsung S20 FE

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20889)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/12832
