### ISSUE TITLE
[Bug]: Weird behavior in floating window mode

### ISSUE THREAD

**Issue by Sonotoki-da** [mozilla-mobile/fenix#25864]
### Steps to reproduce

1. Open the browser in floating window mode.
2. Google something.
3. Try to tap to one of the results.

### Expected behaviour

The tap should behave properly...

### Actual behaviour

The tap is somehow applied to the upper side of the expected position of the displayed web-content.

### Device name

POCO X4 Pro

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

102.1.1

### Additional information

![ezgif-1-64b3c0a68b](https://user-images.githubusercontent.com/34913890/177024738-977ce42f-c713-45e2-ae9a-219eb10b2274.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20891)

**Comment by amocirean** [comment]
Hello @Sonotoki-da  , thank you for submitting the issue.
I was not able to reproduce it on Nightly 105.0a1.
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

Device Used: Huawei P40 Lite
Android Version: 10

**Comment by ercansam** [comment]
I am facing exactly the same issue with latest nightly 105.0a1.

Device Used: Redmi Note 8 Pro
Android Version: 11
MIUI Version: 12.5.8 Global

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812226

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
