### ISSUE TITLE
about:config removed

### ISSUE THREAD

**Issue by Whatever11223** [mozilla-mobile/fenix#25863]
### Steps to reproduce

Install Firefox

### Expected behaviour

Work

### Actual behaviour

Mozilla deludes themselves with their hippie 'privacy advocate' propaganda in the circumstance of about:config being broken. With it broken:

There is no way of turning off OCSP server certificate revocation checking, which gets sent in clear text over HTTP, meaning ISP's, governments can spy on users.

There is no way to turn off disk caching meaning browsing history can be recovered from page file, even from private browsing sessions.

There iw no way to turn off HTTP referer, so hosts can see where I have come from and profile, track users.

There is no way to use TLS 1.3 only, meaning SNI leaks.

I see Mozilla soyboys say they broke about:config because users can break their browser. What? 0.0001 of users who that are tinkering? Only tinkers know what about:config is, not 'normal users'. 'Normal users' don't even user Firefox anymore.

I also keep seeing Mozilla soyboys tell users to install a developer version. What a retarded thing to say.

What's Firefox's market share down to now? 3%? That's less than Microsoft Edge. That's humiliating for the current developers and total validation that they have no idea what they are doing.

Deleting my posts won't cure Mozilla's identity crisis.

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

100.1.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20890)

**Comment by marcel263** [comment]
You can install the developer's version.

**Comment by Whatever11223** [comment]
That won't fix the problem.

**Comment by Whatever11223** [comment]
I am not a developer, I am a user.

**Comment by marcel263** [comment]
> I am not a developer, I am a user.
You can install the beta version.

**Comment by Whatever11223** [comment]
As I said, I am not a developer, I am a user.

**Comment by mueenulit** [comment]
Mozilla is not Mozilla anymore..  It's owned and running by Google's Money ..

**Comment by mueenulit** [comment]
Thank you for sharing this ... But Mozilla won't see 😕 this issue ..

**Comment by marcel263** [comment]
This place is for reporting issues, not for low-hanging fruit of tech support. Please visit the support forums if you need help using the beta or developer's versions.

As for the criticism tageted towards about:config being disabled, this issue has long been discussed, see issue #7865.

Of course you can continue filling up the bug tracker and spending your time arguing but this is not the place and it has been long been past due time.

As stated, the feature is available to you when using the beta or developer release channels. If you are not willing to use those (otherwise pretty stable and fine for daily usage), then perhaps it is not that important to you?

To petition for this feature, [Mozilla Connect](https://connect.mozilla.org/)  is recommended where you may campaign for a feature to be added.

**Comment by Whatever11223** [comment]
**mueenulit**

I agree with you, Mozilla is not what it use to be and I too believe they have become sell out servants to Google.

I do believe Mozilla see's the issues. The security and privacy problems are too obvious but Mozilla has its orders from their boss to destroy the product.

**Comment by Whatever11223** [comment]
Every website a user visits that uses HTTP when using Firefox for Android gets sent to OCSP servers over HTTP, in plain text. Nearly every website uses HTTPS mow, so that means ISP's and Governments can see every website you visit. There is no way to turn this off in Firefox for Android anymore.

Mozilla is a joke. It has become a fan club for woke people with green hair.

**Comment by Whatever11223** [comment]
Every website a user visits that uses HTTPs when using Firefox for Android gets sent to OCSP servers over HTTP, in plain text. Nearly every website uses HTTPS mow, so that means ISP's and Governments can see every website you visit. There is no way to turn this off in Firefox for Android anymore.

Apparently changing settings in Firefox for Android is now only for debugging purposes only. lol

Mozilla has become such a joke. It is now mainly a fan club for woke people with green hair that don't actually understand web technologies or how the internet works.

**Comment by Whatever11223** [comment]
Every website a user visits that uses HTTPS when using Firefox for Android gets sent to OCSP servers over HTTP, in plain text. Nearly every website uses HTTPS mow, so that means ISP's and Governments can see every website you visit. There is no way to turn this off in Firefox for Android anymore.

Apparently changing settings in Firefox for Android is now only for debugging purposes only. lol

Mozilla has become such a joke. It is now mainly a fan club for woke people with green hair that don't actually understand web technologies or how the internet works.

**Comment by marcel263** [comment]
> Every website a user visits that uses HTTPS when using Firefox for Android gets sent to OCSP servers over HTTP, in plain text. Nearly every website uses HTTPS now, so that means ISP's and Governments can see nearly every website you visit. Now there is no way to turn this off in Firefox for Android.
> 
> Apparently changing settings in Firefox for Android is now for debugging purposes only. lol
> 
> Mozilla has become such a joke. It is now mainly a fan club for woke people with green hair that don't actually understand web technologies or how the internet works.

Your DNS provider and your ISP can tell the domains that you request over your connection.

**Comment by Whatever11223** [comment]
My DNS provider does not know my identity so its not a problem for me.

My ISP can only tell which websites I visit if I am using Firefox for Android because of all the information it leaks out. They cannot tell which websites I view in Firefox on my computer since Mozilla has yet to break Firefox and I can turn off OCSP checking in preferences and set the minimum TLS level to TLS 1.3 from about:config which encrypts ENI.

I am not after support, Firefox for Android is simple broken. And it seems most people around here these days lack the technical knowledge to understand the matter anyway.

**Comment by sflorean** [comment]
thank you for report @Whatever11223! This issue is already filed here #21276, and this will be closed as duplicate.
