### ISSUE TITLE
[Bug]: Youtube videos do not play over the entire screen

### ISSUE THREAD

**Issue by rightman28** [mozilla-mobile/fenix#25872]
### Steps to reproduce

1. Open a video in youtube.com (i have used: https://m.youtube.com/watch?v=wHBBoUtJHhA )
2. Go fullscreen

### Expected behaviour

The video should be playing over the entire screen.
![Screenshot_2022-07-04-13-42-28-40_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/108657179/177111792-52eff0eb-7f9a-43cc-971d-21e9f4cd5bc7.jpg)

https://user-images.githubusercontent.com/108657179/177261806-5d5e9a75-886c-49b0-8aeb-6575405ef3ab.mp4
Stats for nerds look at the viewport settings
![Screenshot_2022-08-12-09-22-42-46_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/108657179/184283052-b8ee7c4b-dd73-4fc4-9895-9c99f8873ace.jpg)

This is what a 16:9 video is supposed to look like in fullscreen.
![Screenshot_2022-07-08-19-12-10-13_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/108657179/178005137-d64ae97f-684a-44b2-8558-70190d256fe4.jpg)

### Actual behaviour

The part where front camera is on the screen a vertical grey bar appears. For 16:9 aspect ratio video its does not interfere its just a grey bar one side but it is annoying as this was not an issue and is not an issue in chrome. But for ultrawide aspect ratio videos the video gets cropped.
In simpler words the video does not play over the entire screen.
![Screenshot_2022-07-04-13-31-34-32_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/108657179/177111899-56ed020c-bec0-4392-b765-6a8fbe9a2776.jpg)
* Look at the left edge

https://user-images.githubusercontent.com/108657179/177261923-6c31a8eb-54e9-4fb0-b8df-385ed8e17e7c.mp4
Stats for nerds:
![Screenshot_2022-08-12-09-22-07-43_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/108657179/184283120-388b2e01-2c29-4668-8064-ca773c9242c1.jpg)

In firefox nightly:
![Screenshot_2022-07-08-19-12-54-40_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/108657179/178005280-4e35a388-d0c4-4d06-88f0-ed307ea31c99.jpg)

### Device name

OPPO A74 5G

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1 (Build #2015890059)

### Additional information

This problem is not present in firefox version 68.11.0 (before the quantum update) or chrome. All the apps have been selected to "Show front camera" in the phone settings.
This means the video is to be played from edge to edge.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20897)

**Comment by SoftVision-LorandJanos** [comment]
Hi @rightman28. Thank you for your report!
Using your example, I tried to reproduce your issue on the latest Nightly 104.0a1 (2022-07-04T17:46:56.722989) and I didn't find anything out of the ordinary on the sides. I didn't find any difference in appearence between FF, Youtube app and on Chrome.
Please see if you still reproduce the issue with the latest Nightly build, perhaps try with other videos as well, or maybe, if you can, clear your data before to see if some setting might have interfered with how the image appears. Thank you!

**Comment by rightman28** [comment]
I have added screen recordings in the original post. Please see. Thank you!

**Comment by rightman28** [comment]
I think the problem might be related with the os. I have tried playing the same video in a one plus nord 2 and a xiaomi redmi 8A.
In the one plus nord 2 the same behavior is seen as my phone. Coloros 12 and oxygen os 12 are basically the same so not surprised.
I even installed the firefox version 68.11.0 and it plays the video edge to edge.

In the redmi 8a even chrome won't play the video edge to edge.

The problem isn't with a specific video. The thing is that in any video a gray bar appears on the edge where the front camera is.

**Comment by Mikaka27** [comment]
I can reproduce on [this](https://m.youtube.com/watch?v=2LQuu22oMQI) video on my device. I get strange grey bar on top of the phone.

**Comment by Erithax** [comment]
I think I am experiencing the same issue. It occurs on every website with a video player that I have found (Youtube, Twitch, Odyssee, Mozilla, etc.), both in and not in fullscreen mode.  However, I don't see a grey bar as mentioned by @Mikaka27 and @rightman28 and I don't have a notch/hole punch display and am on Motorala e4 plus with Android 7. The issue also started a couple of weeks ago.

**Comment by ris58h** [comment]
I have a similar issue with Samsung s10e.
![Screenshot_20220812-095621_Firefox](https://user-images.githubusercontent.com/511242/184277937-132e7c6a-1c82-497d-b00a-a151bb10d6e7.jpg)
https://m.youtube.com/watch?v=cjdsNYDNobA

I understand that it's because there is a front camera hole, but could it be black instead? In Crome it's black (I can't take the screenshot due to security policy).

**Comment by rightman28** [comment]
> 

It is exactly the same issue

**Comment by ris58h** [comment]
@rightman28 Do you want the gray stripe to be black or do you want it to dissappear (stretch the video to entire screen)?

**Comment by rightman28** [comment]
@ris58h The grey stripe should not be there. In your screenshot the video is 16:9 so its not a problem. But if a higher aspect ratio (21:9) video is played the where the video is supposed to cover the whole screen the grey bar remains and does not play over the entire screen. Look at the screen capture of the expected behaviour it should make it clear.

**Comment by ris58h** [comment]
@rightman28 I get it. Thank you.
Anyway, should we create a separate issue for painting the stripe in black? For 16x9 video for example.

**Comment by rightman28** [comment]
@ris58h in my phone there is an option to "hide front camera" for any app that you want this makes the gray stripe black.

**Comment by ris58h** [comment]
@rightman28 in OneUI it's `Show camera cutout`. It solved the issue for 16x9 video. Thank you!

**Comment by rightman28** [comment]
> @rightman28 in OneUI it's `Show camera cutout`. It solved the issue for 16x9 video. Thank you!
👍

**Comment by jonalmeida** [comment]
Marking this bug as resolved as posted by the OP.

**Comment by rightman28** [comment]
The problem still persists for ultrawide (21:9) videos.
