### ISSUE TITLE
Fenix's file picker should offer Camera app in addition to the Files app

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#2587]
### Why/User Benefit/User Problem
Fenix's file picker should offer users the option to upload a picture or video from the Camera app.

### What/Requirements
Chrome's file picker offers the Files, Camera, and Camera Video apps. Fennec offers Files and Camera. Fenix should offer Files, Camera, and maybe Camera Video (Product decision), but currently just opens the Files app.

This is a Fenix bug, not a GV bug. Fenix is responsible for opening the file picker. GV just asks the app for a file.

### Acceptance Criteria (how do I know when I’m done?)
Choose files for a file input that only accepts images on Android.
Fenix should offer Files, Camera, and maybe Camera Video.

@NotWoods originally reported this bug in Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1552019

@NotWoods - Do you have a link to an `<input type="file" accept="image/*">` test case that demonstrates this UX issue?

**Comment by NotWoods** [comment]
https://rumbling-pan.glitch.me/ has various file inputs that can be tested with

**Comment by NotWoods** [comment]
Fixed in Android Components 3.0.0
