### ISSUE TITLE
[Bug] (Fennec): App icon not visible in F-Droid

### ISSUE THREAD

**Issue by hamishmb** [mozilla-mobile/fenix#25878]
### Steps to reproduce

N/A

### Expected behaviour

F-Droid should have the app icon visible, instead of the default icon. This makes it easier to find Fennec, and makes it easier to see that this is an official build.

### Actual behaviour

App icon not available.

### Device name

Moto G8 Power

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

102.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20900)

**Comment by kbrosnan** [comment]
We don't build the F-Droid APK. Please report it to the F-Droid forums.

**Comment by hamishmb** [comment]
Ah, my apologies, and thanks.
