### ISSUE TITLE
The "Select address" prompt should be displayed again after clearing the field and tapping it

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25885]
### Steps to reproduce

1. From the "Select address" prompt, select a saved address.
2. Tap on a form field and delete de content.
3. Tap on a form field again.
4. Observe if the "Select address" prompt is displayed.

### Expected behaviour

After autofilling the form and clearing a field, the "Select address" prompt should be displayed again after tapping the field and:
- 1. either all the saved addressed are displayed so that different address ca be selected to replace the address selected in Step 1;
- 2. or the address selected in Step 1 is displayed and after selecting it again, the field cleared  in Step 2 is autofilled again;

### Actual behaviour

After autofilling the form and clearing a field, the prompt is not displayed again after taping on the empty field. 

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly 104.0a1 from 07/04

### Additional information

Note that on Chrome, the 2nd behavior is present (This is also the case for Credit Card prompt on fenix). Additionally, on Chrome the "Empty form" option is also displayed. 

https://user-images.githubusercontent.com/89388888/177338817-13d10d55-5831-424b-81b9-6c57da124265.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20906)

**Comment by jonalmeida** [comment]
As part of investigating this ticket, we should check if we are indeed completing the previous prompt request, and probably then we can see if this is a GV bug where the next prompt request is not coming through.

Compare this to desktop as well.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814165

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
