### ISSUE TITLE
[Bug]:  The "Select address" prompt should be displayed on the first tap on the form fields

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25884]
### Steps to reproduce

1. Make sure to have at least one address saved.
2. Access a website with an address form (e.g. https://www.instant-gaming.com/en/payment,  https://www.amazon.com/a/addresses/add ).
3. Tap on one of the address fields.
4. Observe if the "Select address" prompt is displayed.

### Expected behaviour

The "Select address" prompt is displayed above the keyboard after the first tap on the form fields.

### Actual behaviour

The "Select address" prompt is not displayed right after the first tap on the form fields every time.

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly 104.0a1 from 07/04

### Additional information

https://user-images.githubusercontent.com/89388888/177332156-d77dd079-f292-4d95-9aad-041f3e49dede.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20907)

**Comment by sv-amocirean** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1816869

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
