### ISSUE TITLE
[Bug]: The saved address is not autofilled on Amazon if a different Country/Region is already selected 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#25886]
### Steps to reproduce

1. Make sure to have at least one address saved for Canada and one for US.
2. Go to https://www.amazon.com/a/addresses/add to add a new address.
3. While the "Country/Region" field is already filled with the "Unites States" option, attempt to autofill the form with the saved address for Canada.
4. Observe if the form is autofilled.

### Expected behaviour

While attempting to autofill a form that already has an option selected for the "Country/Region" field, after selecting the saved address for a different region from the prompt, all the data is imported correctly on all the designated fields. 

### Actual behaviour

After selecting the saved address for Canada from the prompt, (the saved address has a different region compared to the region selected on the form), the form appears autofilled for a split second, then remains empty. Only the Country/Region field is changed from "United States" to "Canada". 
Only after tapping again on the form fields and selecting the Canada address, the data will be autofilled. 

### Device name

Google Pixel 6 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Latest Nightly 104.0a1 from 07/04

### Additional information

Note that this issue is not encountered on Chrome, where only a flicker is displayed after autofilling the form with a different region address.
This issue also occurs on Firefox Nightly for Desktop 104.0a1 (2022-07-04).
Fenix: 
https://user-images.githubusercontent.com/89388888/177348903-6e4fa92d-ddf1-4616-a982-c9a5cf31e0b5.mp4

Chrome: 
https://user-images.githubusercontent.com/89388888/177348923-facce068-a546-40e3-b02a-7741c3fb66c8.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20905)

**Comment by sv-amocirean** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1816871

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
