### ISSUE TITLE
[Bug] Can't change Google's region

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2588]
## Steps to reproduce
Go to Google.com
Touch settings
Under "region for search results", choose a new region

### Expected behavior
The region is changed

### Actual behavior
The region is not changed

### Device information
* Android device: Galaxy A5 2017
* Fenix version: 1.0.1920

**Comment by kbrosnan** [comment]
Likely an issue with the Google website.

**Comment by AndiAJ** [comment]
Hi, this is **still reproducible** latest Nightly Build #12400613 28/8 using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

It seems that the **save button isn't displayed** in Fenix making it impossible to save any new settings.

<details>
    <summary>Fenix VS Chrome</summary>

► Fenix
![20190828_133533](https://user-images.githubusercontent.com/51314259/63849166-25553b00-c99a-11e9-9602-c2f248f6b768.gif)

► Chrome
![20190828_133335](https://user-images.githubusercontent.com/51314259/63849116-00f95e80-c99a-11e9-937d-34eb45c55658.gif)


</details>

**Comment by rocketsroger** [comment]
Reproduced this issue on both fennec and fenix.

**Comment by rocketsroger** [comment]
cc: @bifleming

**Comment by rocketsroger** [comment]
cc: @miketaylr

**Comment by miketaylr** [comment]
> cc: @miketaylr

Sorry for the delay here -- this is a known issue, that Google is allegedly tracking internally: https://github.com/webcompat/web-bugs/issues/19384#issuecomment-437186956

**Comment by kbrosnan** [comment]
Closing in favor of the webcompat issue.
