### ISSUE TITLE
Move Tabs Tray to compose: Individual tab viewholders: GridViewHolder

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#25891]
Related ticket https://github.com/mozilla-mobile/fenix/issues/21894

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20909)

**Comment by Alexandru2909** [comment]
Closing this as it is not ready to be tested by QA for the following reasons: 
 - Composed tabs tray is only available in debug builds.
 - We don't have support for tabs re-ordering in compose yet.
