### ISSUE TITLE
Firefox Suggest header for library suggestion section of URL bar

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#25894]
## User Story
Adding the 'Firefox Suggest' branded term to URL bar suggestions pulled from library data is intended to:

    Emphasize to users that library data suggestions are being generated by Firefox, and are distinct from default search suggestions

    Lay the groundwork for Firefox Suggest, which is intended to further increase the value users derive from Firefox suggested results for partial query strings

Link to [spec](https://docs.google.com/document/d/1HkD1WkpbGhH1mVTtn16Ako8-tCWV1XSEY58rvUa8jYY/edit?usp=sharing), and design [mockup](https://www.figma.com/file/epu0Sj6mCPk7K282sNpHgI/Site?node-id=3248%3A50053) for reference.

Please disregard the “Sponsored” components of the design mockup, including sponsored suggestions and related settings options. Those items will be addressed in a separate issue.

## Dependencies
- List dependencies on other issues/teams etc.

### Acceptance Criteria
The branded term of “Firefox Suggest” is included as a header for the section of Fenix URL bar suggestions pulled from user library data (i.e. suggested bookmarks, history, open tabs).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20913)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 104 from 07/22 with Google Pixel 6 (Android 12). 
![FirefoxSuggest](https://user-images.githubusercontent.com/89388888/180442536-c39746d2-da87-4866-9553-777a0002b27b.jpg)
