### ISSUE TITLE
[Bug] Search bar suggestions don't match the default search engine region.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2589]
## Steps to reproduce
Set Bing as default search engine
Type something on the address bar
Go to bing.com
Change the region to any other
Type it again on the browser's search/address bar.

### Expected behavior
The suggestions match the new region. It's specially good for people like immigrants using their native language in a foreign country.

### Actual behavior
The suggestion are still shown based on the default region (of de device? I don't know).

### Device information
* Android device: Galaxy A5 2017
* Fenix version: 1.0.1920

**Comment by bifleming** [comment]
@vesta0 we dont save the region for search engines right now. We should address this when we have custom search engines. already have an issue to cover this: 1437
