### ISSUE TITLE
[Bug]: Crash on opening tab tray when Tab view is set to list

### ISSUE THREAD

**Issue by NxOne14** [mozilla-mobile/fenix#25893]
### Steps to reproduce

1. Go to the tab settings and set the Tab view to List
2. Open the Tabs tray

### Expected behaviour

The tray should open normally 

### Actual behaviour

Whole app crashes 

### Device name

Samsung galaxy s8 

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

AC: 104.0.20220627211706 

### Device logs

[Socorro](https://crash-stats.mozilla.org/report/index/4ad09c28-278c-4042-8103-847c90220705)
[LeakCanary trace](https://pastebin.com/hQXfMVg5)
[LeakCanary heap dump](https://drive.google.com/drive/folders/1LaZ_SLN3q4PjzZ8cdI5sfpr0RkGfn3Hx )

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20912)

**Comment by kbrosnan** [comment]
The crash report says it is from Fenix 1.0.2228 which is ancient.

**Comment by SoftVision-LorandJanos** [comment]
Hi @NxOne14! Thanks for your report!
I couldn't reproduce this on the latest builds.
Please check this behavior after updating to a more recent version!
Thank you!

**Comment by NxOne14** [comment]
The build number is 1 because it's a local debug build. The bug was probably caused by something unrelated on my end and I don't get it anymore so I think I should close this.
But I have some questions, could you tell me what AC, GV and AS mean? and if I see a bug in development how should I report it?

**Comment by kbrosnan** [comment]
AC: [Android Components](https://github.com/mozilla-mobile/android-components/)
GV: [Geckoview](https://geckoview.dev)
AS: [Application Services](https://github.com/mozilla/application-services/)

**Comment by NxOne14** [comment]
Thanks!
