### ISSUE TITLE
Remove the hard coded default browser message

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#25915]
https://mozilla-hub.atlassian.net/browse/FNXV2-20703

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20928)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 105 from 07/27 and Beta 104.0b1. The messaging banner is  launched using the messaging framework and expires after 20 views, as expected.

**Comment by Amejia481** [comment]
Thanks for verifying!
