### ISSUE TITLE
[Bug]: 10-bit videos won't play on Fenix

### ISSUE THREAD

**Issue by Zipdox** [mozilla-mobile/fenix#25917]
### Steps to reproduce

Open a 10 bit video (yuv420p10le pixel format). I tried several codecs.

### VP9
https://files.catbox.moe/fzdr2r.webm

### H.264
https://files.catbox.moe/ivry4j.mp4

### Expected behaviour

The videos play.

### Actual behaviour

Both VP9 and H.264 show a "Video can't be played because the file is corrupt" image and show the following in the console.
![Screenshot_20220706-215700_Fennec](https://user-images.githubusercontent.com/42157341/177632709-97f3eb4b-710c-47a1-a0b0-d062ef66bf89.jpg)

### VP9

```
Media resource https://files.catbox.moe/fzdr2r.webm could not be decoded.
Media resource https://files.catbox.moe/fzdr2r.webm could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_DECODE_ERR (0x806e0004)
Details: RefPtr<MediaDataDecoder::DecodePromise> mozilla::VPXDecoder::ProcessDecode(mozilla::MediaRawData *): VPX error: Bitstream not supported by this decoder
```

### H.264

```
Media resource https://files.catbox.moe/ivry4j.mp4 could not be decoded.
Media resource https://files.catbox.moe/ivry4j.mp4 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: Error no decoder found for video/avc
```

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

102.1.1

### Additional information

An interesting observation is that AV1 videos (example: https://files.catbox.moe/mfml1c.webm) don't fail to play, but instead just show a dark green screen. The audio plays fine.
![Screenshot_20220706-215559_Fennec](https://user-images.githubusercontent.com/42157341/177632376-750a7c18-73f0-42fe-bdf3-ceaac09ad429.jpg)
Of course `media.av1.enabled `was enabled in `about:config`.

I don't know if this is the same bug, or if it belongs to another bug.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20929)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1778393

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
