### ISSUE TITLE
Intermittent UI test failure - < SmokeTest.openMainMenuSettingsItemTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25923]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.SmokeTest.openMainMenuSettingsItemTest(SmokeTest.kt:301)
    
❗ There was also an ANR
07-06 14:16:02.129: I/WindowManager(477): Input event dispatching timed out sending to Application Not Responding: system.  Reason: e5a2687 Application Not Responding: system (server) is not responding. Waited 5006ms for FocusEvent(hasFocus=true)
07-06 14:16:02.003: W/Conscrypt(16460): Could not set socket write timeout: java.net.SocketException: Socket closed
07-06 14:16:02.131: W/Conscrypt(16460): 	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@222413040@22.24.13 (150700-455379205):2)
07-06 14:16:02.131: W/Conscrypt(16460): 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@222413040@22.24.13 (150700-455379205):0)
07-06 14:16:02.157: I/Icing(16460): Indexing com.google.android.gms-internal.3p:MobileApplication from com.google.android.gms using seqno 86
07-06 14:16:02.243: W/ActivityManager(477): Slow operation: 90ms so far, now at getContentProviderImpl: after updateLruProcess
07-06 14:16:02.243: W/ActivityManager(477): Slow operation: 90ms so far, now at getContentProviderImpl: before updateOomAdj
07-06 14:16:02.243: W/ActivityManager(477): Slow operation: 91ms so far, now at getContentProviderImpl: after updateOomAdj
07-06 14:16:02.243: W/ActivityManager(477): Slow operation: 91ms so far, now at getContentProviderImpl: done!
07-06 14:16:02.264: D/WindowManager(477): notifyANR took 141ms
### Build: 7/7 Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20935)

**Comment by sv-ohorvath** [comment]
Since it's still an ANR, even without a crash, closing this in favor of https://github.com/mozilla-mobile/fenix/issues/25926
