### ISSUE TITLE
FNX3-16435 ⁃ FxA Auto Sign-in

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#2593]
### Why/User Benefit/User Problem
As a user I want the option for Fenix to automatically sign me in my Firefox account if I am currently signed in FxA on Fennec on the same device. 

### Acceptance Criteria
-I see a prompt during Fenix onboarding, asking me if I want to sign into my Firefox Account (if I am already signed into FxA on Fennec on my device)
-I can tap on the prompt, and be automatically signed into FxA 
-Once signed in, I will be taken to the Sync page. 

### What / Requirements
-UX Designs ==> https://mozilla.invisionapp.com/share/XBRNF6MJVUY
~~Application Services dependency (Verify the a~~s PR for session token migration works with the a-c PR for account state machine, review, and merge)

**Comment by apbitner** [comment]
Onboarding screens have been updated to give the user the option to stay signed in, or to sign out - https://mozilla.invisionapp.com/share/XBRNF6MJVUY

**Comment by vesta0** [comment]
Thank you so much @apbitner for the quick turnaround!

**Comment by apbitner** [comment]
No problem. Updated again this morning with minor copy edits from legal.

**Comment by boek** [comment]
This is blocked on A-S and Fennec 67

**Comment by vesta0** [comment]
@apbitner do you think "stay signed in" implies that the user has already been signed in (and had some data synced) prior to making a selection? If so we may want to change the wording to indicate that nothing is synced until they make an informed decision. Let me know what you think :)

**Comment by apbitner** [comment]
@vesta0 I thought we did want to sign them in automatically, and I was informed the syncing process would've already begun by the time they reached this screen, so we hadn't planned on adding an additional step prompting them to start their sync. Let me know if this is incorrect and we need to revisit.

**Comment by vesta0** [comment]
@apbitner yes I think that was the original thinking but feedback from the security team indicates that we ensure user consent before we start syncing the data. 

@grigoryk please describe the revised behaviour.

**Comment by vesta0** [comment]
I spoke to @jdragojevic and sounds like we can make our approach opt-in (not opt-out as the current mocks suggest) so @apbitner let's revisit this please :)

**Comment by apbitner** [comment]
@vesta0 InVision has been updated - https://mozilla.invisionapp.com/share/XBRNF6MJVUY#/361470683_Onboarding_Flow. I'll have Michelle take a look at copy.

**Comment by bifleming** [comment]
@grigoryk @pocmo I assume there is some a-c work to be done for this?

**Comment by grigoryk** [comment]
A-C dependency: mozilla-mobile/android-components#2775

**Comment by softvision-miralobontiu** [comment]
This is not merged yet.
I've tested on the latest Nightly build 190731 (#12120612) with Google Pixel 3 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1). The onboarding is not updated yet, and I am signed in Fennec on the same device.
