### ISSUE TITLE
More visible and distinguishable progress indicator for loading the page

### ISSUE THREAD

**Issue by opk12** [mozilla-mobile/fenix#25930]
### What is the user problem or growth opportunity you want to see solved?
While a page is loading, a progress bar is displayed. But it is hard to see it, because it is very thin. Moreover, in Private Browsing mode, its orange color makes it even harder to distinguish from the purple background and toolbar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20942)

**Comment by amocirean** [comment]
Hello @opk12  , thank you for submitting the issue!
Based on the following situation, the correct label will be assigned.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812224

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
