### ISSUE TITLE
Update history item design

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#25937]
Update history item UI.
Jira ticket: [link](https://mozilla-hub.atlassian.net/browse/FNXV2-19087)
Design: [link](https://www.figma.com/file/SO8Cd5lnmgNqJQY9KpORc9/History%2C-Bookmarks%2C-Downloads?node-id=879%3A41209)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20946)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Beta 104.0b1 and the buttons and prompts from the history section are according to the [Figma designs](https://www.figma.com/file/SO8Cd5lnmgNqJQY9KpORc9/History%2C-Bookmarks%2C-Downloads?node-id=879%3A41209).
![1658920634872](https://user-images.githubusercontent.com/50983519/181234666-3bd77938-aec5-4388-b7a9-1d8f4eef6743.JPEG)
![1658920635032](https://user-images.githubusercontent.com/50983519/181234670-3b6b24e0-13d9-4b32-94e3-516cfd366ca1.JPEG)
### Devices used:
- Huawei MediaPad M3 (Android 7)
- OnePlus 6T (Android 9)
