### ISSUE TITLE
Compose MessageCard text not adapting to dark theme

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#25938]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/773158/177870519-6c402381-57d8-4ae9-85a7-42c44c9a191c.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20947)

**Comment by delia-pop** [comment]
Verified as fixed on Beta 103.0.0.-beta.5 with Google Pixel 6(Android 12). The message card updates accordingly after changing the theme.
![1657891122925](https://user-images.githubusercontent.com/89388888/179232079-4cccceba-ac16-4a27-90f0-84fc836c32fe.JPEG)

**Comment by Amejia481** [comment]
Thanks for verifying @delia-pop  🎉
