### ISSUE TITLE
For #25935 - Catch NimbusFeatureException from calling FxNimbus value getter

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#25935]
In FxNimbus.features.homescreen.value(), value() can throw an error https://searchfox.org/mozilla-mobile/source/application-services/components/nimbus/android/src/main/java/org/mozilla/experiments/nimbus/internal/FeatureHolder.kt#43

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20945)

**Comment by jhugman** [comment]
I think `NimbusFeatureException` should be renamed an `Error`, since it is only thrown in theoretical situations.
