### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BlitW0** [mozilla-mobile/fenix#25932]
### Steps to reproduce

1. Set inactive tabs to false.
2. Keep many tabs open and then close firefox.
3. Reopen firefox.

### Expected behaviour

Clipboard should not be overwritten.

### Actual behaviour

Clipboard is overwritten by `privacy.resistFingerprinting`.

### Device name

Google Pixel 4a

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

103.0.0-beta.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20943)

**Comment by kbrosnan** [comment]
`privacy.resistFingerprinting` is not supported on mobile.

**Comment by BlitW0** [comment]
@kbrosnan Can you not read? **The issue is about the clipboard being overwritten** not about the `privacy.resistFingerprinting` feature.

**Comment by BlitW0** [comment]
Sorry, my mistake. Changed the phrasing to make it clearer.
