### ISSUE TITLE
Address bar's Scan button shows a black screen instead of opening the QR code scanner

### ISSUE THREAD

**Issue by roni2201** [mozilla-mobile/fenix#25944]
<h3>Steps to reproduce</h3>
<p>1. Open browser</p>
<p>2. Click on address bar</p>
<p>3. Click on Scan</p>

<h3>Expected behaviour</h3>
Open a screen to read Qr Code

<h3>Actual behaviour</h3>
Black screen

<h3>Device name</h3>
Samsung S4 value edition

<h3>Android version</h3>
5.0.1

<h3>Firefox release type</h3>
Firefox Nightly

<h3>Firefox version</h3>
Latest Nightly 104.0a1 from 07/04

<h3>Device logs</h3>
No response

<h3>Additional information<h3>

https://user-images.githubusercontent.com/105252197/177912234-23f8410b-818a-4901-b66f-e752e15fcf9c.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20950)

**Comment by delia-pop** [comment]
Hi, @roni2201, thank you for reporting. I was not able to reproduce your issue on the latest Nightly from 07/18, with Huawei MediaPad M2 (Android 5.1.1). 
Is this still reproducible on your side with the latest Nightly build?

**Comment by roni2201** [comment]
@delia-pop That problem still occurs in newer versions, I updated on Play Store and that bug still persists

**Comment by muziofg** [comment]
I have a similar issue, however isn't a black screen but a darker image, such as less sensitivity to light
I have discovered it by framing  a brighter object like a lamp, the monitor of a PC or an object illuminated by the sun

**Comment by roni2201** [comment]
That bug still persists in Nightly 106.0a1 from 27/08. @muziofg ohh! I thought that bug only was caused by old Android version, but I was mistaken.

**Comment by muziofg** [comment]
@roni2201 Can you confirm that your problem isn't a black screen but a darker image captured ? Otherwise we are experienced different bugs

**Comment by roni2201** [comment]
@muziofgI I tested here, and the bug is really different. I pointed to the lamp, and it is a black screen. Different Bugs. I hadn't tested it before I commented.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807593

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
