### ISSUE TITLE
Intermittent UI test failure - BookmarksTest.multipleBookmarkDeletionsTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#25949]
### Firebase Test Run:
Flaky on 7/7 main
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8441413973017473693/executions/bs.ae6a374c2d3e76d2/testcases/1/logs
### Stacktrace:
`07-07 02:34:23.465: E/ExceptionHandler(12395): Uncaught exception handled: 
07-07 02:34:23.465: E/ExceptionHandler(12395): java.lang.NullPointerException
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at org.mozilla.fenix.library.bookmarks.BookmarkFragment.getBookmarkInteractor(BookmarkFragment.kt:70)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at org.mozilla.fenix.library.bookmarks.BookmarkFragment.refreshBookmarks(BookmarkFragment.kt:291)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at org.mozilla.fenix.library.bookmarks.BookmarkFragment.access$refreshBookmarks(BookmarkFragment.kt:63)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at org.mozilla.fenix.library.bookmarks.BookmarkFragment$refreshBookmarks$1.invokeSuspend(Unknown Source:14)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at android.os.Handler.handleCallback(Handler.java:938)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:7)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.action.Tap.access$100(Tap.java:1)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:3)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:6)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:22)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at android.os.Handler.handleCallback(Handler.java:938)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at android.os.Looper.loop(Looper.java:223)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at java.lang.reflect.Method.invoke(Native Method)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-07 02:34:23.465: E/ExceptionHandler(12395): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2d3d331, Dispatchers.Main]
07-07 02:34:23.471: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:23.486: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:23.498: I/mozac/CrashReporter(12395): Received crash: UncaughtExceptionCrash(timestamp=1657186463466, throwable=java.lang.NullPointerException, breadcrumbs=[Breadcrumb(message=onCreate(), data={recreated=false, intent=android.intent.action.MAIN, instance=264923923}, category=HomeActivity, level=INFO, type=DEFAULT, date=Thu Jul 07 02:33:55 PDT 2022), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:33:55 PDT 2022), Breadcrumb(message=onStart(), data={instance=264923923}, category=HomeActivity, level=INFO, type=DEFAULT, date=Thu Jul 07 02:33:56 PDT 2022), Breadcrumb(message=onResume(), data={instance=264923923}, category=HomeActivity, level=INFO, type=DEFAULT, date=Thu Jul 07 02:33:56 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:34:07 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkAddFolderFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:34:09 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:34:10 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkAddFolderFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:34:12 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:34:13 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkAddFolderFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:34:14 PDT 2022), Breadcrumb(message=Changing to fragment bookmarkFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:34:15 PDT 2022), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jul 07 02:34:22 PDT 2022)], uuid=08b5254f-4aed-4ea9-a947-0b9f613a61d5)
07-07 02:34:23.501: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:23.816: I/chatty(1859): uid=1041(audioserver) writer identical 21 lines
07-07 02:34:23.831: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:23.836: I/lla.fenix.debu(12395): Background concurrent copying GC freed 138205(7374KB) AllocSpace objects, 22(1212KB) LOS objects, 49% free, 12MB/24MB, paused 642us total 1.213s
07-07 02:34:23.846: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:23.906: I/chatty(1859): uid=1041(audioserver) writer identical 4 lines
07-07 02:34:23.921: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:23.926: I/Process(12395): Sending signal. PID: 12395 SIG: 9
07-07 02:34:23.936: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:24.101: I/chatty(1859): uid=1041(audioserver) writer identical 11 lines
07-07 02:34:24.116: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:24.121: W/InputDispatcher(480): channel '3a42d3c org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-07 02:34:24.122: E/InputDispatcher(480): channel '3a42d3c org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-07 02:34:24.129: I/ActivityManager(480): Process org.mozilla.fenix.debug (pid 12395) has died: fg  TOP 
07-07 02:34:24.130: W/WindowManager(480): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@7242195
07-07 02:34:24.131: I/WindowManager(480): WIN DEATH: Window{3a42d3c u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}
07-07 02:34:24.131: W/audio_hw_generic(1859): Hardware backing HAL too slow, could only write 0 of 661 frames
07-07 02:34:24.132: W/InputDispatcher(480): Attempted to unregister already unregistered input channel '3a42d3c org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)'
07-07 02:34:24.141: I/ServiceChildProcess(13101): Destroying GeckoServiceChildProcess
07-07 02:34:24.143: W/ActivityTaskManager(480): Force removing ActivityRecord{99478e u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9}: app died, no saved state
07-07 02:34:24.145: W/ActivityManager(480): Crash of app org.mozilla.fenix.debug running instrumentation ComponentInfo{org.mozilla.fenix.debug.test/androidx.test.runner.AndroidJUnitRunner}`
### Build: 
7/7/2022

Bug logged at https://github.com/mozilla-mobile/fenix/issues/25220

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20953)

**Comment by AndiAJ** [comment]
Closing, didn't fail for a month.
