### ISSUE TITLE
[Meta] Tracking Protection Expanded

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#2594]
### Why/User Benefit/User Problem
-As a user, I want my browser to protect my right to privacy. 

### Acceptance Criteria (Added by PM. For EPM to track when a Meta feature is done)
-UX completed
-User stories completed
-Strings written and approved
-QA completed
-Localization done

**Comment by cpeterso** [comment]
The Firefox Security team recommends that Fenix and Fennec use the same "Standard"/"Strict" Tracking Protection terminology as Firefox desktop:

Option|Regular Browsing|Private Browsing
--|--|--
"Standard" (default)|Block tracking cookies|Block tracking cookies and trackers
"Strict"|Block tracking cookies and trackers|Block tracking cookies and trackers
Disabled|No blocking|No blocking

* Tracking cookie blocking is Enhanced Tracking Protection (aka ETP).
* Tracker (third-party subresources, e.g. JavaScript or images) blocking is regular Tracking Protection.
