### ISSUE TITLE
[Bug]: Recent synced tab should be shown when there are no local tabs

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#25953]
To reproduce:
- Use a nightly/debug build
- Sign in to a Sync account with tabs on another device
- Remove all tabs open locally

Following these steps, the Jump Back In section of the home screen will not be available.

Desired behavior:
Even if there is no recent tab on the device, Jump Back In should still be shown for a recent synced tab.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20956)

**Comment by MatthewTighe** [comment]
Should be fixed by https://github.com/mozilla-mobile/fenix/pull/26083

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 104.0a1 2022-07-21 and the synced tab is shown in the Jump back in section if there are no open tabs.
![1658410700249](https://user-images.githubusercontent.com/50983519/180227838-1e4a465c-a033-4c17-b41e-8ec612c198c8.JPEG)
Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)
