### ISSUE TITLE
Create a new dialog window for removing time range

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#25954]
Currently, the bin button on a history screen suggests user to remove all of the history. Create a new dialog that would offer removing a specific time range, like last hour, today and yesterday, everything/

Jira ticket: [link](https://mozilla-hub.atlassian.net/browse/FNXV2-19087)
Design: [link](https://www.figma.com/file/SO8Cd5lnmgNqJQY9KpORc9/History%2C-Bookmarks%2C-Downloads?node-id=879%3A41209)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20957)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 104.0a1 (2022-07-21) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed.
![Screenshot_20220721-112841](https://user-images.githubusercontent.com/48829350/180168116-b5bd81bc-c144-41c2-8dff-3bc6de282c89.png)
