### ISSUE TITLE
Update the close icon to latest mobile icon

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#25952]
we can replace the smaller close icon with the bigger one (16x16) across the app

_Originally posted by @topotropic in https://github.com/mozilla-mobile/fenix/issues/25941#issuecomment-1179017880_

We'll want to replace ic_close with the latest mobile icon in https://www.figma.com/file/Kv7wWr8vH6AQrGhu9vmjdE/Mobile-Icons?node-id=221%3A1164. We should also inspect that this bigger close icon does not affect existing dialogs or component that should be using the smaller close icon

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20954)

**Comment by sunilk9211** [comment]
hey @gabrielluong let me know if i can do this?

**Comment by gabrielluong** [comment]
@sunilk9211 I believe @mavduevskiy is already working with UX on this.

**Comment by sunilk9211** [comment]
That's great. Thanks.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Beta 104.0b1 and the following buttons have increased in size:
close button from downloads manager
close button from sites in a collection
close button from tabs that are in the inactive section
close button from tabs in list view
close button from history
close button from Recently closed tabs
close button from the save to collection screen
close button from sharing screen after sharing a collection
close button from ETP exceptions list
### Devices used:
- Huawei MediaPad M3 (Android 7)
- OnePlus 6T (Android 9)
