### ISSUE TITLE
Refactor History screen to contain multiple ViewHolder types

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#25967]
Currently, there is just one `HistoryListItemViewHolder`, that contains `Header`, `Synced` and `Recently closed` nav button.
The list has also an `empty state`, and synced history will add a `SignInView`. Separating a single `ViewHolder` into multiple entities will be a cleaner solution, as well as making implementation of `collapsing_header` and `sticky_header` much easier.

Jira ticket: [link](https://mozilla-hub.atlassian.net/browse/FNXV2-19087)
Design: [link](https://www.figma.com/file/SO8Cd5lnmgNqJQY9KpORc9/History%2C-Bookmarks%2C-Downloads?node-id=879%3A41209)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20961)

**Comment by sv-ohorvath** [comment]
@mavduevskiy does this need qa?

**Comment by mavduevskiy** [comment]
@sv-ohorvath 
Sorry for replying late. It actually doesn't, files were added but not used.
