### ISSUE TITLE
[Bug]: Pull to refresh option bug using specific websites

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#25964]
### Steps to reproduce

1. install google search fixer addon
2. search for anything with google
3. scoll down to middle of the page for example
4. try to scroll up 
5. it won't scroll up from the first time but will scroll up on the second time
6. disable pull to refresh option from settings-customise
7. repeat now step 3-4 it now will scroll up from the first time

### Expected behaviour

when trying to pull up on google search page it should be done from the first scroll not from the second

### Actual behaviour

firefox scroll up from the second scroll up and disabling pull to refresh option fix it and i can scroll up from the first time and the same thing happens on "about:config" page too

### Device name

Huawei y7 prime / Poco m3

### Android version

Android 8 / Android 11

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20960)

**Comment by AdinaPetridean** [comment]
@mohamedsalaheig Thank you for your report! I was able to reproduce your issue with Firefox Nightly 104.0a1- 7/11. Device used: One Plus 9 Pro (Android 12).
