### ISSUE TITLE
Awesomebar search results have no context menu

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2596]
If I enter some something in the URL bar, the resulting search results coming from my history and bookmarks should have a context menu with the usual options (open in new tab, copy, share, edit (if bookmark), delete, etc.) available.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11536)

**Comment by buttercookie42** [comment]
And this is already a major annoyance in Fennec, where the context menu for search results only has the "Delete" option. I often find that the search results contain multiple pages that I'd like to open, in which case I'd like to open each result I'm interested in in a new tab instead of opening one result, redoing my search, opening the next result, and so on.

**Comment by yoasif** [comment]
Users noticing a regression from Fennec: https://www.reddit.com/r/firefox/comments/ijvcg1/new_updated_on_android_is_there_a_faster_way_to/g3iui0c/

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807755

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
