### ISSUE TITLE
[Bug]: Clicking on shortcuts from home screen always opens new tab

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#25979]
### Steps to reproduce

1. Have a tab open
2. Click address
3. Click some website in shortcuts

### Expected behaviour

Since I never clicked "new tab" button, but only address field, I expect clicking on shortcut to open it in current tab.

### Actual behaviour

Shortcut always opens new tab.
See video:

https://user-images.githubusercontent.com/9214100/178277989-e1f3c2a1-fbe8-4653-baba-d84529489a87.mp4

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.0

### Device logs

Not a crash

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20974)

**Comment by sunilk9211** [comment]
Maybe this issue is same as these:
Check these:
https://github.com/mozilla-mobile/fenix/issues/23630, 
https://github.com/mozilla-mobile/fenix/issues/20012
https://github.com/mozilla-mobile/fenix/issues/19930

**Comment by Mikaka27** [comment]
I think first one is something different, but it could be considered duplicate of the other two.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/19930
