### ISSUE TITLE
[Bug]: Dynamic toolbar is shown when opening modal dialog

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#25978]
### Steps to reproduce

1. Have dynamic toolbar enabled
2. Go to [this website](https://mui.com/material-ui/react-dialog/)
3. Scroll to button which opens dialog
4. Keep dynamic toolbar hidden
5. Click on button to open dialog

### Expected behaviour

Dynamic toolbar should stay hidden, since current website url is not changed

### Actual behaviour

Dynamic toolbar is shown, when dialog is opened.
See video:

https://user-images.githubusercontent.com/9214100/178259844-4324849c-f46b-486c-ac81-6438ffe23111.mp4

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.0

### Device logs

Not a crash

### Additional information

Also happens on nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20973)

**Comment by AdinaPetridean** [comment]
@Mikaka27 thank you for your report! I was able to reproduce your issue with Firefox 102.2.1 and Firefox Nightly 104.0a1- 7/11. Device used: One Plus 9 Pro (Android 12).

**Comment by Mikaka27** [comment]
As per recommendation given here: https://github.com/mozilla-mobile/fenix/discussions/26566 I've filed [bz-1787620](https://bugzilla.mozilla.org/show_bug.cgi?id=1787620) for this.
