### ISSUE TITLE
[Bug]: Graphical artifacts when element is near bottom of screen

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#25975]
### Steps to reproduce

1. Have dynamic toolbar enabled
2. Open [this website](https://mui.com/material-ui/react-snackbar/)
3. Scroll to button which opens snackbar (and keep dynamic toolbar hidden at this point)
4. Click open snackbar
5. Observe problem

### Expected behaviour

Snackbar should open without graphical artifacts

### Actual behaviour

Snackbar blinks after opening if it's opened when dynamic toolbar is hidden.

See videos:

https://user-images.githubusercontent.com/9214100/178254371-e1e7a0a7-55c2-45e3-a921-18b0900f5be9.mp4

https://user-images.githubusercontent.com/9214100/178254451-abf9f91f-5249-4f53-83ad-b9ac3fe13f0b.mp4

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.0

### Device logs

Not a crash

### Additional information

Also happens on nightly, I'am mentioning @jamienicol since he's working with gfx team.
Possibly related to this issue: #25974

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20970)

**Comment by SoftVision-LorandJanos** [comment]
Hi @Mikaka27. Thanks for your report!
I was able to reproduce your issue with the latest Nightly 104.0a1 (2022-07-11T17...) build.
Device used: Google Pixel 4 (Android 12).

**Comment by Mikaka27** [comment]
As per recommendation given here: https://github.com/mozilla-mobile/fenix/discussions/26566 I've filed [bz-1787618](https://bugzilla.mozilla.org/show_bug.cgi?id=1787618) for this.
