### ISSUE TITLE
[Bug]: User avatars/images not loading if tab is started in background

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#25977]
### Steps to reproduce

1. Go to wykop.pl (polish equivalent of reddit.com)
2. Scroll to some link
3. Hold finger on it
4. Open it in new tab
5. Wait a few seconds on current tab
6. Switch to new tab

### Expected behaviour

User avatars and images in comments are not loaded (ads are excluded from this behaviour)

### Actual behaviour

See video:
https://www.dropbox.com/s/ulpwtswj7965r4c/2020_12_13_19_09_19.mp4?dl=0

I move a finger on the left of "saviola7" user where avatar should be visible. After I reload the page (and I stay on tab until it reloads), everything is fine.
I saw this problem on fenix preview, it's not happening on fennec android.
Desktop firefox is also fine, no issue there.

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.0

### Device logs

Not a crash

### Additional information

This is a reopen of #17009 since it's still happening.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20971)

**Comment by SoftVision-LorandJanos** [comment]
Hi @Mikaka27. Thanks for your report!
I was able to reproduce your issue with the latest Nightly 104.0a1 (2022-07-11T17...) build.
Device used: Google Pixel 4 (Android 12).

**Comment by Mikaka27** [comment]
Still an issue

**Comment by Mikaka27** [comment]
Website's layout was changed and the issue is no longer reproducible
