### ISSUE TITLE
3 dot menu on individual history items does not have same options as bookmark item - ie cannot open in new tab

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2597]
It seems that library items open in the current tab by default, which is fine, but whereas the menu for bookmarks items also has an option to open the item in a new tab instead, for history entries the menu only contains the option to delete them.
Since it's not possible to create empty tabs, either, that leaves no nice way to open history items in anything other than an already open tab, overwriting the current page.

**Comment by buttercookie42** [comment]
See also #2435.

**Comment by sv-ohorvath** [comment]
There is an option to open in new & private tabs if you long tap the item(s), then tap the 3 dot menu on the multi-selection toolbar.
We can probably keep this bug for fixing: #2435 - 2a).

**Comment by buttercookie42** [comment]
Thanks for the info, but yes, it not necessarily easily discoverable, especially given the seemingly arbitrary differences between the two.

**Comment by ekager** [comment]
I'm going to close this for https://github.com/mozilla-mobile/fenix/issues/2435 2a. Thanks!
