### ISSUE TITLE
[Bug]: Impossible to know receiver of shared tab in polish

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#25976]
### Steps to reproduce

1. Have firefox sync enabled on atleast 2 PCs and atleast one smartphone
2. Have firefox language set to polish
3. Try to share tab

### Expected behaviour

2 PCs should be distinguishable

### Actual behaviour

Both PCs show as 'Firefox użytkownika ...' which translates to 'Firefox of user ...'
Since this name is not scrollable in any way, you cannot know to which PC a tab would be sent.

Similar problem is with mobile devices. I have one and in my case it shows as: 'Firefox na urządzeniu sa...' which translates to 'Firefox on device sa...'. In my case I know I have a samsung so it's a little bit better than PCs case.

See screenshot:
![Screenshot_20220711-133518_Firefox](https://user-images.githubusercontent.com/9214100/178256191-dbd834cb-0107-4636-a193-ba987914455b.jpg)

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.0

### Device logs

Not a crash

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20972)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/15170

See my comment about how sync device names are generated. You can edit them in your sync setting for the device. https://github.com/mozilla-mobile/fenix/issues/15170#issuecomment-863497684
