### ISSUE TITLE
[Bug]: Choppy animations when animated element is near bottom of the screen

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#25974]
### Steps to reproduce

1. Have dynamic toolbar enabled
2. Open [this website](https://mui.com/material-ui/react-progress/)
3. Position website so that animated progress icon is near bottom of the screen (and dynamic toolbar has is now hidden)
4. Stop scrolling the website (lift finger from screen)
5. Observer choppy animation

### Expected behaviour

Animation should be smooth

### Actual behaviour

Animation is choppy, but only when both of those are true:
1. User stopped scrolling the website
2. Dynamic toolbar is hidden

See video:

https://user-images.githubusercontent.com/9214100/178253449-6af0073e-fe45-4908-8eb3-5bb4048446d9.mp4

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.0

### Device logs

Not a crash

### Additional information

Also happens on nightly, I'am mentioning @jamienicol since he's working with gfx team.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20969)

**Comment by SoftVision-LorandJanos** [comment]
Hi @Mikaka27. Thanks for your report!
I was able to reproduce your issue with the latest Nightly 104.0a1 (2022-07-11T17...) build.
Device used: Google Pixel 4 (Android 12).

**Comment by Mikaka27** [comment]
As per recommendation given here: https://github.com/mozilla-mobile/fenix/discussions/26566 I've filed [bz-1787617](https://bugzilla.mozilla.org/show_bug.cgi?id=1787617) for this.
