### ISSUE TITLE
Remove ability to toggle wallpapers by tapping Firefox logo

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#25985]
The ability to toggle the selected wallpaper by tapping the Firefox logo introduces additional constraints on the freedom to choose different wallpaper download strategies. It is also a feature that can be activated accidentally pretty easily, leading to unexpected results. It should be removed for now.

Acceptance criteria:
- Logo can no longer be tapped to switch wallpaper
- Logo no longer animates
- Settings data and preference keys used to determine if logo should animate are removed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20978)

**Comment by sunilk9211** [comment]
hi @MatthewTighe can i do this?

**Comment by MatthewTighe** [comment]
@sunilk9211 Sure, this seems like a good issue for a community contributor to pick up! I added some more explicit acceptance criteria to the OP to try and help guide you through it. I would start by looking at the following functions:

[WallpaperManager::switchToNextWallpaper](https://searchfox.org/mozilla-mobile/rev/22f697fb68894c09dec5d3c164bcec92b0c2fbe1/fenix/app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt#91)
[WallpaperManager::animateLogoIfNeeded](https://searchfox.org/mozilla-mobile/rev/22f697fb68894c09dec5d3c164bcec92b0c2fbe1/fenix/app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperManager.kt#215)

Let me know if I can help with anything else 🙂 Thank you!

**Comment by sunilk9211** [comment]
Thanks @MatthewTighe. 😊
I have one question. Do we want to remove all the code related to this feature?
I can see in code, this feature is also used for some promotion related stuff.

**Comment by MasterInQuestion** [comment]
Is not it optional: "Settings" -> "Homepage" -> "Wallpapers" -> "Change wallpaper by tapping Firefox homepage logo"?

**Comment by MatthewTighe** [comment]
@MasterInQuestion It is optional, but the decision has still been made to remove it based on the reasons quoted in the original issue, in addition to the fact that it had low discoverability.

**Comment by MasterInQuestion** [comment]
Rather than removing the function completely, would not it be less destructive to just override the user config value before the version?

**Comment by MatthewTighe** [comment]
@MasterInQuestion We aren't really interested in continuing to maintain the feature, and its existence is having an impact on our ability to plan improvements and additions to the wallpaper feature in general. Normally I would completely agree that we don't want remove existing features, but data has shown that this one has low awareness and usage as is, especially since it's on the newer side.

@sunilk9211 Are you still planning to submit a patch for this issue? I'm working through some refactoring of the underlying implementation of this feature, and will need to touch some of same code. I thought I'd check in beforehand and warn you that you may need to keep an eye on this space in order to keep your branch up-to-date if you're still working through it.

**Comment by sunilk9211** [comment]
Yes @MatthewTighe i am keeping my branch upto with the latest changes for this features.

**Comment by MasterInQuestion** [comment]
Way too insignificant to worth further serious considerations.
    For this specific case, proceed at will. None should be really bothered anyway.

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 105.0a1 from 08/16 with Xiaomi 12 Pro (Android 12):
- the FF logo has no functionality;
- the "Change wallpaper by tapping Firefox homepage logo" option is no longer available in the Wallpapers menu;
- the FF logo is no longer animated; 

https://user-images.githubusercontent.com/89388888/185168755-802cf9fb-be17-45da-b90e-9701a1f73532.mp4
Note that in the attached video, a delay in loading the wallpaper on homepage can be observed and the issue was reported in https://github.com/mozilla-mobile/fenix/issues/26511 .

**Comment by delia-pop** [comment]
Verified as fixed on Firefox Beta 105.0b1 as well, with Lenovo Yoga Tab 11 (Android 11).
