### ISSUE TITLE
[Bug] Can't authenticate an app

### ISSUE THREAD

**Issue by lhirlimann** [mozilla-mobile/fenix#2598]
## Steps to reproduce
* Install the android app Street complete
* In the app's setting choose authoriez in OSM
* get redirected to osm's login page
* enter user + password
* press the grant button

### Expected behavior
I return to the app and I can edit data

### Actual behavior
I'm kept on openstreetmap's grant page.

### Device information
* Android device: Redmi Note 7 /version of android 9 PKQ1.180904.001 + MIUI 10.3.5.0(PFGMIXM)
* Fenix version: 1.0.1920 (Build #11360658 68.0a1-20190508111321)

If I switch to fennec this works.

**Comment by callahad** [comment]
I ran into the same.

MoCo folks: You can repro by attempting to sign into our Slack workspace while Fenix is set as the default browser. It don't work.

**Comment by vesta0** [comment]
Dup of #1213 and will be addressed by this [A-C issue.](https://github.com/mozilla-mobile/android-components/issues/1132)
