### ISSUE TITLE
Wrong behaviour when selecting normal tabs in private mode

### ISSUE THREAD

**Issue by sunilk9211** [mozilla-mobile/fenix#25987]
### Steps to reproduce

1. Switch to private mode, and open tabs bottom sheet dialog
2. Switch to normal tabs and select at least one tab
3. Put the app in background and reopen again
At this point it should reproduce.

### Expected behaviour

Don't switch to private tabs, if normal tabs were selected.

### Actual behaviour

Normal tabs are still selected but it switches to private tabs.

### Device name

Xiaomi 9A

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

91.1.2

### Device logs

Somehow screenrecording is not working on my device.
I will update here once i could record this issue.

### Additional information

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20980)

**Comment by SoftVision-LorandJanos** [comment]
Hi @sunilk9211. Thanks for your report!
I wasn't able to reproduce your issue as I understood, using the latest Nightly 104.0a1 (2022-07-11T17...) build.
Device used: Google Pixel 4 (Android 12).
Please make a video about it. Thank you!

**Comment by sunilk9211** [comment]
Hi @SoftVision-LorandJanos, in private mode it doesn't allow screenrecording, so i have uploaded some images above as Additional information. Please check.

**Comment by MasterInQuestion** [comment]
"Settings" -> "Private browsing" -> "Allow screenshots in private browsing".

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807533

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
