### ISSUE TITLE
[Bug]: Three dot menu opens extended when website is installable

### ISSUE THREAD

**Issue by Mikaka27** [mozilla-mobile/fenix#25994]
### Steps to reproduce

1. Open new tab
2. Go to website which is ~~not scrollable~~ installable, for example: tiktok.com
3. Click three dots to open menu
4. Observe issue

### Expected behaviour

A menu should open, but it should be retracted to most used options

### Actual behaviour

A menu is open, but is already fully extended.
See comparison screenshots from google.com and tiktok.com:
<img src = https://user-images.githubusercontent.com/9214100/178445506-bdd21179-ac49-4d0b-9fd0-51e26abcb23b.jpg width = 45%> <img src = https://user-images.githubusercontent.com/9214100/178445555-02d0b750-93b7-4af8-902e-c48f7bef45ac.jpg width = 45%>

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20985)

**Comment by AdinaPetridean** [comment]
@mohamedsalaheig Thank you for your report! I reproduced your issue with Firefox Nightly 104.0a1- 7/11. Device used: One Plus 9 Pro (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 104.0a1 (2022-07-14) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as Verified.
