### ISSUE TITLE
[webcontent] intend:// urls don't load

### ISSUE THREAD

**Issue by mb** [mozilla-mobile/fenix#25998]
## Site with issue and any steps to reproduce

See also: webcompat/web-bugs/issues/107291

1. *edit:* Enable `Settings -> Advanced -> Open links in apps`
2. Try to load https://forms.gle/T2Lyzpjfy4hgPgZS7 in Firefox Android

### Expected behavior

Form gets redirected to https://docs.google.com/forms/d/e/1FAIpQLSeoxArje8hslSD-4zcuK3cEk3YtpXWaAJQfK42U_SvhIKhqBg/viewform

### Actual behavior

Page doesn't load.

```
> curl -I 'https://forms.gle/T2Lyzpjfy4hgPgZS7' -H 'User-Agent: Mozilla/5.0 (Android 12; Mobile; rv:102.0) Gecko/102.0 Firefox/102.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US' -H 'Accept-Encoding: gzip, deflate, br' -H 'Alt-Used: forms.gle' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: cross-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'
HTTP/2 302 
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
accept-ch: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-security-policy: require-trusted-types-for 'script';report-uri /_/DurableDeepLinkUi/cspreport,script-src 'nonce-B7wR0UUftFkmjip0-lyqzA' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/DurableDeepLinkUi/cspreport;worker-src 'self',script-src 'nonce-B7wR0UUftFkmjip0-lyqzA' 'self' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com https://www.google-analytics.com https://www.googleapis.com/appsmarket/v2/installedApps/;report-uri /_/DurableDeepLinkUi/cspreport
content-type: application/binary
cross-origin-opener-policy: unsafe-none
cross-origin-resource-policy: same-site
expires: Mon, 01 Jan 1990 00:00:00 GMT
location: intent://forms.gle/T2Lyzpjfy4hgPgZS7#Intent;package=com.google.android.gms;action=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK;scheme=https;S.browser_fallback_url=https://docs.google.com/forms/d/e/1FAIpQLSeoxArje8hslSD-4zcuK3cEk3YtpXWaAJQfK42U_SvhIKhqBg/viewform%3Fusp%3Dsend_form;end;
permissions-policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-platform=*, ch-ua-platform-version=*
pragma: no-cache
server: ESF
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
accept-ranges: bytes
date: Tue, 12 Jul 2022 15:55:39 GMT
x-served-by: cache-hhn4043-HHN
x-cache: MISS
x-cache-hits: 0
x-timer: S1657641340.707961,VS0,VE145
vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site, x-fh-requested-host, accept-encoding
content-length: 0

```

probably because the location-uri starts with indend://

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No
### Can you reproduce in Chrome (or other non-Mozilla browser)?
In the default browser I get the unkown URI schema error
<details>
<summary>view the screenshot with the error message</summary>
<img alt="Screenshot" src="https://user-images.githubusercontent.com/36711370/178546014-391f67b9-8e95-40b5-9872-c2e778831ce0.png">
</details>
### Device information

* Android device: LineageOS 19 (Android 12)
* Fenix version: 102

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20986)

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox RC 102.2.1 and Nightly 104.0a1 2022-07-13, but was unable to, after clicking on the link the correct google form is opened.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by mb** [comment]
I can confirm, that it seems to work in stock android (using android studio + . It opens the default browser with the long docs.google.com/...-url. When the default browser is set to chrome, it opens the website in chrome. But when setting the default browser to Firefox, it opens in Firefox. It might be a LineageOS bug then.

**Comment by mb** [comment]
Opened bug report there: https://gitlab.com/LineageOS/issues/android/-/issues/4924

**Comment by csadilek** [comment]
Closing for upstream issue, as this not appear to be Fenix bug.
