### ISSUE TITLE
Download failed when attempting to download an image at cerber.re

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#26009]
### Steps to reproduce

1. Navigate to: https://www.cerber.re/
2. Scroll the page towards the end.
3. Long tap on the icon image.
4. From the newly opened menu, tap on "Save image".
5. Observe the result.

### Expected behaviour

The image is downloaded.

### Actual behaviour

The download of the image failed.

### Android version

Android 11, Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 104.0a1 (2015891787-🦎104.0a1-20220711094852🦎)

### Additional information

1. Originally reported here: https://github.com/webcompat/web-bugs/issues/107301
2. Reproducible regardless of the status of ETP.
3. Reproducible on the latest build of Firefox Nightly and Release.
4. Screenshot is attached:
![Screenshot_7](https://user-images.githubusercontent.com/75027050/178688971-db7ea113-c188-4dc6-a633-52606a4b6f59.jpg)

5. Works as expected using Chrome:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20995)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-20995

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox RC 102.2.1 and Nightly 104.0a1 2022-07-13.

### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by amocirean** [comment]
The issue is still reproducible on the latest Firefox Beta (110.0b1).
Tested on: Samsung Galaxy S22 Ultra (Android 13)
Google Pixel 6 (Android 13)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812784

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
