### ISSUE TITLE
zhihu.com is able to override don't open links in app

### ISSUE THREAD

**Issue by gzqx** [mozilla-mobile/fenix#26001]
### Steps to reproduce

1. Disable open links in app option
2. Install zhihu app, (Google play version https://play.google.com/store/apps/details?id=com.zhihu.android)
3. Open an arbitrarty zhihu.com page, say https://www.zhihu.com/question/542916291/answer/2571174147
4. It forces open the app.

### Expected behaviour

Do not open the app.

### Actual behaviour

It opens the app.

### Device name

Xperia 5

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

99.2.0 (Build #2015874211),

### Additional information

No other app show this behavior.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20993)

**Comment by SoftVision-LorandJanos** [comment]
Hi @gzqx. Thank you for your report!
I was able to reproduce the issue you described. The page was opened in the installed app.
Device used: Google Pixel 4 (Android 12).

**Comment by Lanchon** [comment]
the same happens with tinder app:

- share a profile as a link
- open link in firefox
- firefox invokes app (unless in desktop mode) even if "open links in app" is disabled

btw, this has been happening for years i believe.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807411

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
