### ISSUE TITLE
Favicon is not shown in history at cerber.re

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#26008]
### Steps to reproduce

1. Navigate to: https://www.cerber.re/
2. Tap on the kebap menu of the browser (three vertical dots in the toolbar).
3. Open the "History" menu.
4. Observe the result.

### Expected behaviour

The correct favicon is displayed (logo of the page).

### Actual behaviour

A "C" letter is displayed inside the favicon.

### Device name

Operating System: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density) Operating System: Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)

### Android version

Android 11, Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 104.0a1 (2015891787-🦎104.0a1-20220711094852🦎)

### Additional information

1. Originally reported here: https://github.com/webcompat/web-bugs/issues/107301
2. Reproducible regardless of the status of ETP.
3. Reproducible on the latest build of Firefox Nightly and Release.
4. Screenshot is attached:
![Screenshot_5](https://user-images.githubusercontent.com/75027050/178685220-25fc63c4-2836-4c09-9598-339fa803b12d.jpg)

5. Works as expected using Chrome:

![Screenshot_6](https://user-images.githubusercontent.com/75027050/178685155-a4662cfe-b74f-4abd-86c5-d9c7c8d73760.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20994)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-20994

**Comment by SoftVision-LorandJanos** [comment]
Hi @softvision-raul-bucata!
I can confirm, the issue is reproducible on the latest Nightly 104.0a1 (2022-07-14) build.
Device used: Google Pixel 4 (Android 12).

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible with the latest Nightly 110.0a1 (2023-01-11) build.
Device used: Oppo Find X5 (Android 12).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813087

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
