### ISSUE TITLE
[Bug]: Can't pull to refresh on act.hoyolab.com, but can in Chrome

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#26018]
### Steps to reproduce

1. Visit https://act.hoyolab.com/ys/event/signin-sea-v3/index.html?act_id=e202102251931481&utm_source=link
2. Attempt to pull-to-refresh

### Expected behaviour

Pull to refresh should work

### Actual behaviour

Pull to refresh does not work (it does on Chrome).

### Device name

Galaxy S20 FE 5G

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1

### Additional information

(Issue originally reported at [webcompat.com](https://github.com/webcompat/web-bugs/issues/106881))

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21001)

**Comment by SoftVision-LorandJanos** [comment]
Hi @wisniewskit. Thank you for your report!
I was able to reproduce your issue.
Device used: Google Pixel 4 (Android 12).

**Comment by wisniewskit** [comment]
Just a comment to keep this bug open.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811570

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
