### ISSUE TITLE
Simpifly the parameters passed-in for DefaultTabsTrayController

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#26017]
Per https://github.com/mozilla-mobile/fenix/pull/25895#discussion_r918213733, since an `activity` is now being passed into `DefaultTabsTrayController`, the large parameter list could be condensed by obtaining several of them directly from the `activity` reference.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21000)

**Comment by MozillaNoah** [comment]
Requires #25895 to land first

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814206

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
