### ISSUE TITLE
Consider making the Automatic clickable larger 

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26014]
### Preconditions:
 Have a freshly installed Fenix build or a clean profile.

### Steps to reproduce

1.Have the Accessibility scanner app installed and opened.
2.Launch Fenix.
3.Use the Accessibility Scanner scan the Onboarding page.

### Expected behaviour

No suggestions are made.

### Actual behaviour

Consider making the Automatic clickable  item larger, from 38 dp, to 48 dp or larger.

### Device name

One Plus 9 Pro 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

103.0.0-beta.4

### Additional information

![Automatic](https://user-images.githubusercontent.com/108326843/178755808-f0150a21-c13c-456a-acb7-e354fec154c6.JPEG )
</div>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20998)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812471

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
