### ISSUE TITLE
[Bug] Footer alignment in in-app-browser breaks

### ISSUE THREAD

**Issue by cmitz** [mozilla-mobile/fenix#2601]
## Steps to reproduce
Go to an app that opens web-links within the app, like Telegram. Get yourself a URL to click on (like https://debalie.nl/agenda/techpodcastfestival-2-0/). This website has a footer locked on the bottom of the viewport when on mobile.

### Expected behavior
No URL-bar is shown. The footer is aligned to the bottom of the screen.

### Actual behavior
No URL-bar is shown. The footer still has a margin for the URL-bar.

### Device information
* Android device: OnePlus 3, Android 9
* Fenix version: `1.0.1920`

### Screenshots
Fenix in-app-browser:
![](https://user-images.githubusercontent.com/5594436/57917971-26a0a300-7896-11e9-9977-0037814f9717.jpg)

Brave in-app-browser:
![](https://user-images.githubusercontent.com/5594436/57917972-26a0a300-7896-11e9-9215-acab1b03853d.jpg)

Fenix normal:
![](https://user-images.githubusercontent.com/5594436/57917973-27393980-7896-11e9-809f-2999675a8c87.jpg)

**Comment by ekager** [comment]
Do you see an update in GP? This should have been fixed by #2569

**Comment by cmitz** [comment]
Yes, I do. It got fixed!

(Should **I** close this now?)

**Comment by ekager** [comment]
Thanks for the update! I'll close :)
