### ISSUE TITLE
Add a download option to videos, as Chrome offers

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/fenix#26019]
As requested at https://webcompat.com/issues/106313, Chrome offers a download option for videos, while Fenix does not (for instance on [this video](https://www.videofk.com/videofk-video-download/search?url=https%3A%2F%2Fv.kuaishou.com%2FoSRVlU+%E8%80%81%E9%93%81%E7%82%B9%E7%9A%84%E8%98%B8%E9%85%B8%E5%A5%B6%EF%BC%8C%F0%9F%98%8120%3A00%E4%B8%8D%E8%A7%81%E4%B8%8D%E6%95%A3%E5%93%A6%F0%9F%98%98+%22%E5%A3%B0%E6%8E%A7%E5%90%83%E5%86%B0+Copy+this+message+and+open+%E3%80%90Kwai%E3%80%91to+view%21&select=videofk)). It would be nice to have this in Fenix as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21002)

**Comment by kbrosnan** [comment]
This works for me using a [Wikimedia video ](https://upload.wikimedia.org/wikipedia/commons/transcoded/8/87/Schlossbergbahn.webm/Schlossbergbahn.webm.1080p.vp9.webm)

**Comment by Dunexus** [comment]
I tried with the videos given as exemple and it seems to be working correctly, see screenshot.![Screenshot_20220714-091951__01.jpg](https://user-images.githubusercontent.com/13906248/178925346-706b7186-3a9d-473c-9113-2c23f03a4f57.jpg)

**Comment by kbrosnan** [comment]
Closing this as it is possible to download video files.
