### ISSUE TITLE
[Bug]: autoplay blocking does not work / media.autoplay.blocking_policy automatically resets to 1

### ISSUE THREAD

**Issue by vinc17fr** [mozilla-mobile/fenix#26027]
### Steps to reproduce

1. In about:config, set
```
media.autoplay.allow-extension-background-pages = false
media.autoplay.block-event.enabled = true
media.autoplay.blocking_policy = 2
media.autoplay.default = 5
```
as suggested on https://support.mozilla.org/en-US/questions/1278114
2. Open https://www.leprogres.fr/culture-loisirs/2022/07/14/lyon-joie-et-emotion-explosent-en-mille-couleurs-au-dessus-de-la-ville
3. Scroll down until the video frame is fully visible.

### Expected behaviour

The video should still be blocked.

### Actual behaviour

After 2, the video is blocked, but after 3, the video autoplays.

### Device name

Samsung Galaxy Note10+

### Android version

12

### Firefox release type

Firefox Beta

### Firefox version

103.0.0-beta.4

### Additional information

When reopening about:config and searching for "autoplay", I can see that media.autoplay.blocking_policy is reset to 1, while I had set it to 2. This seems always reproducible.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21012)

**Comment by kbrosnan** [comment]
Autoplay is controlled by the Geckoview API. This is expected behavior. You should be able to use the settings to get the behavior you want.
