### ISSUE TITLE
Refactor the FenixTabCounterMenu creation from HomeFragment to TabCounterBuilder

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#26026]
Related to https://github.com/mozilla-mobile/fenix/pull/24772#discussion_r855550965, we want to refactor out common functionality that will be needed between the Onboarding and Home fragment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21011)

**Comment by gabrielluong** [comment]
For QA, we should simply check that there is no change in functionality with the tab counter menu. This is the menu that contains the tab count and opens the tab tray. There are some functionality involving long press.

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest Nightly 105.0a1 (2022-07-28) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.
