### ISSUE TITLE
[Bug]: reader view breaks after restart of app

### ISSUE THREAD

**Issue by christophgrander** [mozilla-mobile/fenix#26025]
### Steps to reproduce

1. Open a tab and open any website (that displays text)
2. Go to reader view
3. Close firefox by going to tab switcher and closing it there
4. Open firefox again
5. You will be on the same page as before and the reader view button will be colored as if reader view was active but the website will be displayed without reader view.
6. Tapping the reader view button wont change anything, reader view will not work anymore

### Expected behaviour

Reader view should still be open after restarting firefox

### Actual behaviour

Reader view is not displayed after reopening and will not work anymore in this tab. The only way to view the active website in reader view again is to copy the url and open it in a new tab.

### Device name

Samsung Galaxy S9

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

102.2.1

### Additional information

Same behaviour occurs when you open reader view, switch to another app until firefox is put to sleep by android and then open firefox again. Also the same happens when you open reader view in one tab and switch to another tab. When the first tab is then deleted from memory by firefox before you switch back reader view will break.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21009)

**Comment by kbrosnan** [comment]
duplicate https://github.com/mozilla-mobile/fenix/issues/18933
