### ISSUE TITLE
Current wallpaper storage should be abstracted away from `Settings`

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26033]
There should be an abstraction layer implemented to cover the usage of `Settings` to track the current wallpaper. This is with the goal of eventually porting the bulk of the Wallpaper implementation to A-C, where it can't be guaranteed that the storage layer is the same as it is in Fenix.

Create an interface that can define current wallpaper storage and add an implementation of that interface that uses settings under the hood as is currently done. 

Note that this may require code to handle migrations to a different storage implementation down the line.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21016)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809807

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
