### ISSUE TITLE
[Bug]: Shared Firefox Tab is opened in other browser if it's set as default browsing app.

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#26037]
### Steps to reproduce

1. Have another browser _set as default_.
2. Send a tab from another device.
3. Click the **notification**.
4. Observe.

### Expected behaviour

The tab is opened in **Firefox**.

### Actual behaviour

The tab is opened in the **default browser** of the device _instead of Firefox_.

### Device name

Huawei P40 Lite

### Android version

Android 10

### Firefox release type

Firefox Beta

### Firefox version

103.0.0-beta.5

### Additional information

I was also able to reproduce the issue on the latest RC (102.2.1 Build #2015891003) and Nightly (104.0a1 Build #2015892267).

I've attached a video regarding the issue.

https://user-images.githubusercontent.com/103257761/179165196-f2d5e319-f649-4bda-be56-e8e6fec8b211.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21018)

**Comment by indurs** [comment]
@mcarare , @Mugurell can I work on this issue? I think we can just add a category for the intent in 
https://github.com/mozilla-mobile/fenix/blob/1a2b3571197f74d842154ab93db992160c93479b/app/src/main/java/org/mozilla/fenix/components/NotificationManager.kt#L63 so that Fenix can process the tab.

**Comment by Mugurell** [comment]
Adding a new intent filter with `category android:name="mozilla.components.browser.SENDTAB"` would probably work but to increase security and be 100% sure that Intent will be passed to us we could also just use an explicit intent.

**Comment by indurs** [comment]
Great point!

**Comment by indurs** [comment]
Just a clarification. When a tab is received from another device, a new tab is created and the content is loaded. When I go back from that tab, it takes to the device's home screen. Is it intended to be that way or do we've to take the user to the home screen?

**Comment by Mugurell** [comment]
@indurs Since we normally bring the user back to app's homescreen when there is no history left this scenario does warrant more investigation and feedback from UX but in a separate ticket since it's a preexistent behavior separate than the issue described here. Would you open a new ticket for it?

**Comment by indurs** [comment]
@Mugurell , Thank you. Will open a new ticket.

**Comment by Alexandru2909** [comment]
Reopening for QA to verify.

**Comment by amocirean** [comment]
Hello,
The issue no longer occurs on Firefox Nightly 105.0a1.
Tested on both Samsung A32 5G (Android 11) and Huawei P40 Lite (Android 10).
