### ISSUE TITLE
[Bug] Custom scheme urls don't work

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2603]
## Steps to reproduce
1. Go to reddit.com. Tap Continue in browser, or Open the app, on the bottom banner.
1. Go to rpappalax.github.io/testapp. Tap the telephone & email links.
    1. Expected behavior
The linked apps should open, or the google store (if the apps are not installed).
    1. Actual behavior
Nothing happens. 
    1. Device information

* Android device: P9 lite (Android 6), Note 8 (Android 9)
* Fenix version: 5/17 build

**Comment by ekager** [comment]
Same as #1570
