### ISSUE TITLE
[Bug]: [Firefox Android] URL autocomplete have some issue

### ISSUE THREAD

**Issue by foxhelps** [mozilla-mobile/fenix#26038]
### Steps to reproduce

1. Have a tab open, 
2. click on address bar
3. type something on address bar

### Expected behaviour

I used to be able to see alot of different suggestions (even if they are not bookmarked links) for thr address bar.

### Actual behaviour

Firefox addressbar now would now only display two suggestions(that isnt bookmarked), I have checked the search settings already and turned everything on, but my issue is that Firefox seems to have problem displaying aurocomplete suggestions from my browsing history that I havent bookmarked.

### Device name

Samsung Galaxy A715F/DS

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.1

### Additional information

To reiterate my issue: Recently I have an issue with the autocomplete. Firefox addressbar would now only display two suggestions(that isnt bookmarked), but I used to br able to see alot of different suggestions (even if they are not bookmarked links) for thr address bar.

I have checked the search settings already and turned everything on, but my issue is that Firefox seems to have problem displaying aurocomplete suggestions from my browsing history that I havent bookmarked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21019)

**Comment by lindongbin** [comment]
#25913

**Comment by Mugurell** [comment]
@foxhelps I see you reported the issue on the current release version.
Can you also test and report back on how the current Nightly behaves for you?
There have been some recent changes included in Nightly which should improve things.

**Comment by foxhelps** [comment]
@tried that but unfortunately its the same behavior.

**Comment by lindongbin** [comment]
https://www.reddit.com/r/firefox/comments/wao92a/firefox_mobile_no_longer_shows_history_in_search/

**Comment by csadilek** [comment]
See https://github.com/mozilla-mobile/fenix/issues/25913.
