### ISSUE TITLE
Create a WallpaperMiddleware for the AppStore

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26030]
A WallpaperMiddleware should be added to the AppStore that can initiate side effects. This should take the place of any direct interactions with the `WallpaperManager` and instead react automatically to `Action`s intercepted that update the `WallpaperState` added in https://github.com/mozilla-mobile/fenix/issues/26029.

This may be dependent or cause conflicts with https://github.com/mozilla-mobile/fenix/issues/25985

This should include an action to refresh the current wallpaper bitmap when configuration changes occur.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21014)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809806

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
