### ISSUE TITLE
Add animation when clicking the address bar to open up the keyboard 

### ISSUE THREAD

**Issue by proletarius101** [mozilla-mobile/fenix#26031]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

When clicking the address bar (by default at the bottom), unlike what Android system apps do, there is no animation as the keyboard is up. It feels chunky.

We should, instead, use https://developer.android.com/training/system-ui/sw-keyboard to provide a swift experience.

Previously there are https://github.com/mozilla-mobile/fenix/issues/7158 https://github.com/mozilla-mobile/fenix/issues/7381. However, they don't apply today due to the different final address bar locations in the input screen.

### How do you know that this problem exists today? Why is this important?

Opening up the keyboard from address bar is one of the most frequent actions. The chunky feeling gives user an strong impression that Firefox is slow.

### Who will benefit from it?

Users who
- open up the address bar
- have the address bar at the bottom

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21017)

**Comment by rokejulianlockhart** [comment]
Fuck you, @stale.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813772

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
