### ISSUE TITLE
Refactor Synced Tabs in the tabs tray to rely on `SyncStore` instead of implementing `SyncedTabsView`

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#26049]
As a follow-up to https://github.com/mozilla-mobile/fenix/issues/25955, the Synced Tabs in the tabs tray can now also leverage `SyncStore` to drive the UI and simplify the business logic contract.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21027)

**Comment by MozillaNoah** [comment]
Related ticket: https://github.com/mozilla-mobile/android-components/issues/11552

**Comment by jonalmeida** [comment]
I think the flow would be something like:
1. Observe SyncStore for SyncState changes (logged in/logged out).
2. On logged in, fetch synced tabs from `SyncedTabsStorage.getSyncedDeviceTabs`.
3. Display contents from the result in a LazyColumn.
4. On logged out (or other bad states), show appropriate error UI.

If that does make sense, then we can consider removing the SyncedTabsFeature class, but the AC layer is still useful.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810773

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
