### ISSUE TITLE
Show Insecure password warning

### ISSUE THREAD

**Issue by mimi89999** [mozilla-mobile/fenix#26056]
Firefox Desktop shows a warning when clicking on a password field on a HTTP website and attempting to enter a password as described in https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox. Fenix does not do that. I think that it is important that Fenix displays such a warning as well since mobile users might use open WiFi networks that are intercepting passwords or even performing sslstrip attacks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21031)

**Comment by amocirean** [comment]
Hello @mimi89999 , thank you for submitting the issue.
This is a feature request. The according labels will be assigned.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813790

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
