### ISSUE TITLE
[Bug]: does not block all trackers twitter

### ISSUE THREAD

**Issue by holequantum** [mozilla-mobile/fenix#26059]
### Steps to reproduce

1. turn on enhanced protection from settings for standard to strict to custom what ever you choose bug is always there.
2. open twitter.com and check you will see google-analytics has been allowed in all circumstances from standard to strict to custom whatever you select it remains allowed even in incognito mode.

### Expected behaviour

it should block google-analytics in twitter.
as i have tested with Fennec F-Droid f-droid.org that does not have any issues it was good at blocking block google-analytics in twitter.

### Actual behaviour

i have attach the screenshots for better understanding.
![rvtv](https://user-images.githubusercontent.com/108695843/179387563-f17dd63c-8a5f-4018-99b7-aba29ffa28ee.jpeg)
![fg](https://user-images.githubusercontent.com/108695843/179387569-683f1e7a-eef4-4835-be14-1a612af35017.png)

hopefully it get fixed as issue is not there in f-droid firefox(fe)

### Device name

google pixel 4, moto edge 20, xiaomi device also

### Android version

android 12,android11

### Firefox release type

Firefox

### Firefox version

102.2.1

### Additional information

i have installed firefox from playstore beta one that also have the same isssue.
but fdroid one does not have issues and i have tried this one 4devices all running android 12 and 11.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21032)

**Comment by kbrosnan** [comment]
This may be the tracking protection JS stubs which prevents tracking but allows essential website functions. Will reach out to the tracking protection team.

**Comment by holequantum** [comment]
no that is not the issue because fdroid compiled firefox and named fennec which actually block google analytics i have seen that even in my dns.
it is a bug or maybe internal by someone this need to be looked and fix this.

**Comment by Amejia481** [comment]
cc @wisniewskit

**Comment by wisniewskit** [comment]
@Amejia481, Yes, since tracking content is being blocked, the Google Analytics Smartblock shim should be taking over here, so no actual tracking should be happening. That can be confirmed by checking the web console in the remote devtools to see if a "Google Analytics is being shimmed by Firefox" message appears. I'm not sure why it wouldn't be annotated as such in the UI, though.

**Comment by holequantum** [comment]
i see this is not an issue in desktop x86-64 mac and linux variant of firefox and fdroid https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/ version of firefox also does not have this issue i have confirmed that on my 3 devices.
it is only in mozilla firefox downloaded from  playstore.

**Comment by kbrosnan** [comment]
This got disconnected from the fix. It ended up being a platform change. BZ-1781936 the fix is currently on v105 we are evaluating it for 104. It does seem a bit risky so it might not get uplifted.

**Comment by holequantum** [comment]
thank you i through it was fixed and got 103 update and it does not work so created a new bug report thanks.
