### ISSUE TITLE
FNX3-16447 ⁃ [Bug] Font scaling inconsistent einthusan.tv

### ISSUE THREAD

**Issue by denschub** [mozilla-mobile/fenix#2606]
## Steps to reproduce
1. Open https://einthusan.tv/movie/browse/?lang=hindi
1. Observe font sizes, especially in the header and the genre labels in the slider

### Expected behavior
Font sizes probably should be rendered consistently in relation to each other.

### Actual behavior
The fonts in the main slider section, especially the genre labels, are enlarged to a point that actually breaks the layout.

Now, this page has no `<meta name="viewport">`, and adding one to enforce a consistent scaling resolves those layout issues, but neither Fennec nor Chrome have issues here, so maybe it's something to improve? :grinning:

See also, https://github.com/webcompat/web-bugs/issues/31242

### Device information
* Android device: Fully updated Pixel 2
* Fenix version: 1.0.1920

**Comment by buttercookie42** [comment]
> neither Fennec

Fennec would, too, if you enable font size scaling from the accessibility options.

Opened [bug 1552781](https://bugzilla.mozilla.org/show_bug.cgi?id=1552781) - I'll try looking at it in the near future, though can't promise any definitive time scale.

**Comment by bifleming** [comment]
@vesta0 priority?

**Comment by kbrosnan** [comment]
This is expected behavior for font inflation for desktop sites. See #577

**Comment by buttercookie42** [comment]
Yes and no - in this particular case there is some scope for improvement in our font inflation logic, as per bug 1552781.

**Comment by buttercookie42** [comment]
[Bug 1552781](https://bugzilla.mozilla.org/show_bug.cgi?id=1552781) has been fixed in Gecko(View).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** in both portrait mode as well as in landscape view on **Nightly Build #12112106 from 30/7** using the following devices:
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

<details>
    <summary>Pics</summary>

![Screenshot_20190731-121359](https://user-images.githubusercontent.com/51314259/62200108-6a7f5080-b38d-11e9-82e7-9e4dddf1b14f.png)

![Screenshot_20190731-121647](https://user-images.githubusercontent.com/51314259/62200130-75d27c00-b38d-11e9-80d2-f7c2a6656235.png)


</details>
