### ISSUE TITLE
[Bug]: text selection magnifier missing

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26066]
### Steps to reproduce

I remember text selection magnifier was added few months ago but since last few weeks I am observing this is not May I know why the feature removed?

### Expected behaviour

On selecting text magnifier should show

### Actual behaviour

Magnifier no longer showing 

### Device name

asus rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21036)

**Comment by SoftVision-LorandJanos** [comment]
Hi @sheikh-azharuddin! Thank you for your report!
I was able to reproduce your issue on the latest Nightly 104.0a1 (2022-07-18) build.
Device used: Google Pixel 4 (Android 12).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1780093

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
