### ISSUE TITLE
[Bug]:  long press text selection menu showing bing search

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26068]
### Steps to reproduce

Set Google as your default search engine
Long press any text, it will show a menu which has bing search but not Google search

Any reason?

### Expected behaviour

Long press text selection menu should show default search engine

### Actual behaviour

Showing bing search 

### Device name

rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Additional information

![Screenshot_20220718-122749027 (1)](https://user-images.githubusercontent.com/58127841/179459096-2c80423e-78bd-4712-bbac-5763414d8c31.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21038)

**Comment by SoftVision-LorandJanos** [comment]
Hi @sheikh-azharuddin! Thank you for your report!
I wasn't able to reproduce your issue on the latest Nightly 104.0a1 (2022-07-18) build.
As Google is set as default search engine, the selected word is searched with Google.
Can you try reproducing it after a clear data? Thank you!

**Comment by sheikh-azharuddin** [comment]
Issue is still there..from reddit I found this is expected if outlook app is installed.hence closing it
Thanks
