### ISSUE TITLE
Swiping back to homescreen doesn't close the tab. 

### ISSUE THREAD

**Issue by Spinnekop** [mozilla-mobile/fenix#26076]
### Steps to reproduce

1. From homescreen click on pinned shortcut. eg. bbc.co.uk/news 
2. Read various articles
3. Swipe back to Firefox homescreen.
4. Click on another shortcut, opens an additional tab
5. bbc.co.uk/news remains open on a tab.

### Expected behaviour

When returning to homescreen tab should close with last swipe back. 

### Actual behaviour

Tab remains open. Firefox has done this for as long as I can remember. 

### Device name

Xiaomi Redmi Note 8T 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21043)

**Comment by amocirean** [comment]
Hello @Spinnekop , thanks for submitting this issue.
This is a feature request, the expected behaviour is the one you've described in the reproduction steps.
The Feature Request label will be added to this issue.

**Comment by Spinnekop** [comment]
Maybe the feature request could be to make the behaviour switchable if this
is something Firefox users want. I have tried several other browsers and
each behave as I would expect. But, I prefer ff for its security features.

**Comment by tbertels** [comment]
This looks like #19888 but with steps to reproduce etc.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813786

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
