### ISSUE TITLE
[Bug]: Firefox Nightly crashes on open or (if open) switch to tab

### ISSUE THREAD

**Issue by shamelesslymkp** [mozilla-mobile/fenix#26077]
### Steps to reproduce

1. Open Firefox Nightly

### Expected behaviour

Browser should load and allow you to switch tabs and access sites

### Actual behaviour

The app closes unexpectedly. 

### Device name

Moto G Stylus 2021

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21044)

**Comment by shamelesslymkp** [comment]
Update: already a ticket; apologies. most likely the ubo bug reported elsewhere.

**Comment by shamelesslymkp** [comment]
Bug was rolled back? but app is still crashing on open.

**Comment by moody31415** [comment]
Also hitting this issue, started this morning. 
Samsung S8, Android 9, Firefox Nightly 104.0a1.
If I leave my device idle long enough, then I can get into the Firefox "start page" with "jump back in", "recently visited", "collections" - but any page I try to visit - wikipedia.org, arstechnica.com, etc. then nightly crashes before the page starts rendering.
