### ISSUE TITLE
[Telemetry] Record metrics for save credit card prompt shown fact

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#26089]
Fenix counterpart of [12524](https://github.com/mozilla-mobile/android-components/pull/12524).

Record metrics for the facts emmited when the save credit card prompt is shown.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21054)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed with the latest Nightly 104.0a1 (2022-07-25) build.
Device used: Google Pixel 4 (Android 12).
Cosing the ticket as verified.
![image](https://user-images.githubusercontent.com/48829350/180786597-908436b7-560b-4051-9afc-c96fa8df48dc.png)
