### ISSUE TITLE
Show "Sorry" crash reporter dialog instead of a notification icon if Fenix crashes when the app is foregrounded

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26080]
On Android versions < 10, `about:crashparent` will show a "Sorry" crash reporter dialog with an option to submit a crash report. On Android versions >= 10, 'about:crashparent` will just show a crash notification icon in the status bar instead of a "Sorry" dialog. This behavior on Android >= 10 can confuse users because Fenix will just disappear with no explanation and they might not see the crash notification icon in the status bar.

We should change the crash reporter so we show the "Sorry" dialog (and not a notification) if Fenix is foregrounded when the parent process crashes, like we do on Android < 10.

Expected behavior:

* If the app is backgrounded when the parent process crashes, show a notification. (Though clicking the notification may show the "Sorry" dialog, which is OK.)
* If the app is foregrounded when the parent process crashes (or we can't determine the foreground/background state), show the "Sorry" dialog and no notifications.

This issue is a spin-off from #25223.

![image](https://user-images.githubusercontent.com/629193/179600264-f7c2cac7-ceea-4718-814a-510443c9798c.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21047)

**Comment by rocketsroger** [comment]
Unable to consistently show crash prompt dialog when the app crashes on Android O or above.  Falling back to showing the notification but always shows crash prompt when the user taps on the notification or the action button in the notification.

**Comment by rocketsroger** [comment]
Change landed in A-C.  Should be available for tomorrow's nightly.  Please verify that crash reporting still working on Android 9, 10, 11 and 12.  Thanks

**Comment by delia-pop** [comment]
Verified as partially fixed on the latest Nightly 105 from 08/07. 
- For devices with Android 10, 11, 12: When about:crashparent is entered in the URL bar, the browser closes, the crash notification appears in the system status bar, but no dialog box is displayed. After tapping the notification, the "Sorry" dialog box is displayed.
- For device with Android 9 (Xiaomi Redmi Note 8T): When about:crashparent is entered in the URL bar for the first time, the browser closes, no notification appears in the system status bar, but no dialog box is displayed either. After going about:crashparent a second time, the "Sorry" dialog box is displayed. This behavior is also reproduced on the latest Beta 104.0b5.
Also tested on LG G7 fit (Android 8.1.0) where the "Sorry" dialog is displayed from the first attempt.

@cpeterso Should we report a separate issue for the behavior on Android 9 device? 

Devices used:
- Xiaomi Redmi Note 8T (Android 9) 
- Huawei P40 Lite (Android 10)/OPPO A15s (Android 10)
- Samsung Galaxy A32 5g (Android 11)/Lenovo Yoga Tab 11 (Android 11)
- Google Pixel 6 (Android 12)/Xiaomi 12 Pro (Android 12)

Xiaomi Redmi Note 8T (Android 9) : https://user-images.githubusercontent.com/89388888/183460160-76e04fd3-ea61-4f00-979a-a82ff90fe03b.mp4

**Comment by cpeterso** [comment]
>     * For device with Android 9 (Xiaomi Redmi Note 8T): When about:crashparent is entered in the URL bar for the first time, the browser closes, no notification appears in the system status bar, but no dialog box is displayed either. After going about:crashparent a second time, the "Sorry" dialog box is displayed. This behavior is also reproduced on the latest Beta 104.0b5.
>       Also tested on LG G7 fit (Android 8.1.0) where the "Sorry" dialog is displayed from the first attempt.
> 
> 
> @cpeterso Should we report a separate issue for the behavior on Android 9 device?

Thanks for testing. Yes, please file a separate issue for the Android 9 issue about the crash notification not appearing in the system status bar. I'll close this issue as fixed.

Bummer that Android prevents use from showing the "Sorry" dialog box when the browser crashes and we have to instead use the crash notification.. 😞
