### ISSUE TITLE
[UITests] Track ignored tests from when migrating tabs tray to compose

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#26087]
QA recommended having one ticket tracking all changes which resulted in disabled tests following the compose migration of the tabs tray:

Tests which cannot easily be updated to support compose can be `@Ignore`d with the following comment:
> "Failing after compose migration. See: https://github.com/mozilla-mobile/fenix/issues/26087"

&nbsp;
-----

- [ ] https://github.com/mozilla-mobile/fenix/pull/25996 migrated the grid layout. Some tests are now failing because [TabDrawerRobot](https://github.com/mozilla-mobile/fenix/blob/23796286df770e6b7814e7a4f19fff3c8e08cc71/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt#L442 ) used ids from `tab_tray_grid_item.xml` which are not available anymore.

cc @sv-ohorvath @AndiAJ

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21051)

**Comment by AndiAJ** [comment]
Thanks @Alexandru2909 ! ☺️ 

Just for a better overview, these UI tests were disabled:
► MenuScreenShotTest

-  `tabMenuTest`

► BookmarksTest

- `openSelectionInNewTabTest`
- `openSelectionInPrivateTabTest`


► CollectionTest

- `createFirstCollectionTest`
- `verifyExpandedCollectionItemsTest`
- `openAllTabsInCollectionTest`
- `shareCollectionTest`
- `deleteCollectionTest`
- `mainMenuSaveToExistingCollection`
- `verifyAddTabButtonOfCollectionMenu`
- `renameCollectionTest`
- `createSecondCollectionTest`
- `removeTabFromCollectionTest`
- `swipeLeftToRemoveTabFromCollectionTest`
- `swipeRightToRemoveTabFromCollectionTest`
- `selectTabOnLongTapTest`
- `navigateBackInCollectionFlowTest`
- `undoDeleteCollectionTest`

► ContextMenusTest

- `verifyContextOpenLinkNewTab`
- `verifyContextOpenLinkPrivateTab`

► CrashReportingTest

- `privateBrowsingUseAppWhileTabIsCrashedTest`


► HistoryTest

- `openHistoryInNewTabTest`
- `openHistoryInPrivateTabTest`
- `verifyRecentlyClosedTabsListTest`


► SearchTest

- `noRecentlyVisitedSearchGroupInPrivateBrowsingTest`

► SettingsPrivacyTest

- `launchPageShortcutInPrivateModeTest`

► SettingsSearchTest

- `toggleSearchBookmarksAndHistoryTest`

► SmokeTest

- `verifyBasicNavigationToolbarFunctionality`
- `openRecentlyClosedItemTest`
- `deleteRecentlyClosedTabsItemTest`
- `shareTabsFromTabsTrayTest`
- `privateTabsTrayWithOpenedTabTest`
- `tabMediaControlButtonTest`

► StrictEnhancedTrackingProtectionTest

- `testStrictVisitProtectionSheet`
- `testStrictVisitSheetDetails`

► TabbedBrowsingTest

- `openNewTabTest`
- `openNewPrivateTabTest`
- `closeAllTabsTest`
- `closeTabTest`
- `verifyUndoSnackBarTest`
- `closePrivateTabTest`
- `verifyPrivateTabUndoSnackBarTest`
- `verifyOpenTabDetails`

cc @sv-ohorvath

**Comment by sv-ohorvath** [comment]
I started fixing the tests, but some are blocked and failing, and the reason seems to be that the work on the tabs tray is incomplete and certain transitions don't work so well in UI tests. Testing manually, there's no visible issue.
After discussing with the team, I've decided to leave the tests disabled on Debug until the refactoring work is complete.
Tracking for the dev work done is here https://github.com/mozilla-mobile/fenix/issues/21318
We will continue to run these tests on Beta/RC builds, but not on debug.

**Comment by Mugurell** [comment]
Talked with Oana about using this ticket as some sort of a meta for tracking all disabled tests following the compose migration of the tabs tray.
Will update the ticket description and add this to the meta ticket for the migration.

**Comment by sv-ohorvath** [comment]
Confirmed with Alexandru and Petru that there is still more refactorization work to be done on the tabs tray which would affect the tests, so we'll leave them disabled until they're fully done.

**Comment by AndiAJ** [comment]
openAllInTabsTest and openAllInPrivateTabsTest got disabled in #21212

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807270

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
