### ISSUE TITLE
Maybe -28ms regression to cold view nav start (7/11)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#26084]
On the 7/10 Nightly we see 2.189s to 2.217s on the 7/11 Nightly:

![image](https://user-images.githubusercontent.com/759372/179629398-c08d00eb-c011-4eef-a192-356150029450.png)

However, there is a lot of noise now (20-40ms of variance) so it's hard for me to feel fully confident this is a regression.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21049)

**Comment by mcomella** [comment]
Triage: let's get more results from the next few nightlies to better determine if it's a regression or not.

**Comment by mcomella** [comment]
Triage: we're still not sure if this is a regression so we'll wait another week to see the data. Here is the graph, this maybe regression is the annotation on the right.

![image](https://user-images.githubusercontent.com/759372/181633235-88a8cf3c-e396-4e97-a46a-8fdc67a2958f.png)

**Comment by MarcLeclair** [comment]
Close: Today we see a similar time as of 7/10 (2.189s vs 2.187s). The 28ms might be a regression but it seems to either have been fix or could've just been noise.
