### ISSUE TITLE
Group known trackers in the tracking content UI

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#26081]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
As a user I would like to understand the companies that are tracking web usage. Being displayed the raw list of domains that are trackers is not easy to understand. As an example compare the list of trackers shown on https://abcnews.go.com on Android vs Desktop.

![Screenshot_20220718-131509](https://user-images.githubusercontent.com/250273/179614619-a4742903-25e1-4aeb-98fc-40792328b27b.png)

![Screenshot 2022-07-18 134943](https://user-images.githubusercontent.com/250273/179614879-81a57670-65ac-4a52-b822-cf36f8c14601.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21048)

**Comment by Trikolon** [comment]
It would be nice if we could show entities rather than tracking origins by default. We could do this on both desktop and mobile. We can get the entity-list from Disconnect. There should still be a way to look at the origins if needed though.
