### ISSUE TITLE
FNX3-16448 ⁃ [Bug] Scrolling to the bottom on phoronix.com locks up scrolling

### ISSUE THREAD

**Issue by denschub** [mozilla-mobile/fenix#2609]
## Steps to reproduce
1. Open https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1099221-hands-on-with-the-atomic-pi-as-a-35-intel-atom-alternative-to-the-raspberry-pi
1. Scroll to the bottom
1. Attempt to scroll back up

### Expected behavior
Scrolling back up works.

### Actual behavior
Scrolling up is not possible. It works fine in Fennec, and Chrome. I looked at the markup and CSS and honestly do not have an idea what's going on here.

### Device information
* Android device: Pixel 2
* Fenix version: 1.0.1920

**Comment by yoasif** [comment]
This works in reference browser and Focus, so it seems to be Fenix specific.

**Comment by vesta0** [comment]
This is a strange one, it works with quick scroll but not when scrolling slowly.

**Comment by ekager** [comment]
It's freezing for me on RB as well. I think it may be a GV issue because we shouldn't be doing anything to interfere with the page scrolling. It only works with a faster fling in both as @vesta0 mentioned above.

**Comment by vesta0** [comment]
@cpeterso @vickychin Is there a GV/Performance bug we are tracking related to this?

**Comment by cpeterso** [comment]
I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1561450

**Comment by cpeterso** [comment]
@denschub Can you still reproduce this scroll hang in Fenix? If so, can you please try testing in the Reference Browser app? It uses GeckoView 70 Nightly, which fixed some scrolling bugs.

https://play.google.com/store/apps/details?id=org.mozilla.reference.browser

**Comment by ekager** [comment]
I'm still seeing it freeze up with slower scrolling @cpeterso . If you fling to the bottom and then slowly scroll up, it doesn't scroll.

**Comment by denschub** [comment]
Eh, sorry. I accidentally ignored the ping. I can confirm, the issue is still there.

**Comment by AndiAJ** [comment]
Him **verified as fixed** on the latest Nightly Build #12520610 from 9/9 using the following devices: 
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
► Video
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/51314259/64537717-0785bf80-d324-11e9-90d8-d0be5645330f.gif)
