### ISSUE TITLE
Scrollshot of a web page

### ISSUE THREAD

**Issue by opk12** [mozilla-mobile/fenix#26090]
### What is the user problem or growth opportunity you want to see solved?
It would be nice if Fennec supported this as a builtin feature.

### How do you know that this problem exists today? Why is this important?
This app takes a screenshot of a web page, by indicating start point and end point. https://play.google.com/store/apps/details?id=com.leavjenn.longshot 
However it uses the system WebView (which is outdated on older phones) and de-googled users don't have an alternative in F-droid.

### Who will benefit from it?
Privacy-aware people who need to do a long screenshot

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21055)

**Comment by onemahon** [comment]
I believe this is technically possible as of Android 12; Chrome [implemented it last year](https://www.xda-developers.com/google-chrome-support-android-12-scrolling-screenshots/). But I couldn't find a ton of documentation about it with a brief glance around. I think the approach would be to implement the newly-introduced Android 12 API, [`dispatchScrollCaptureSearch`](https://developer.android.com/reference/android/view/View#dispatchScrollCaptureSearch(android.graphics.Rect,%20android.graphics.Point,%20java.util.function.Consumer%3Candroid.view.ScrollCaptureTarget%3E)). Or at least that may be a starting point. 

I believe this would require low-level support from GeckoView, first, which may make it harder to implement. [Here's](https://chromium-review.googlesource.com/c/chromium/src/+/3089805) the introduction of the Scroll Capture API in chromium, in case that's a breadcrumb trail worth learning from.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813792

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
