### ISSUE TITLE
When navigating back from a saved login your search results should be saved.

### ISSUE THREAD

**Issue by lle-git** [mozilla-mobile/fenix#26094]
Hi,

To sum up :
While browsing through the different results of your search in "Logins and passwords", you should not have to type your search again and again.

In details:
-Go to "Logins and passwords"and then "Saved logins"
-Search for a specific login or website.-->Let's say there are many results and you are not sure or want to edit multiple results
-First, display the details from one result
-Then you want to go back to the other results
-But, no..., the results are gone, you will have to do the same search again !

How it should work:
It should go back to the screen with the results of your search.

Thanks !

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21058)

**Comment by lle-git** [comment]
Hi,
Any news ?
This problem makes the Firefox Password manager so inconvenient.
Thanks

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813794

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
