### ISSUE TITLE
[Bug]: HTTP Basic Auth connections hang forever with no input dialog for credentials on first load of site

### ISSUE THREAD

**Issue by quinndiggity** [mozilla-mobile/fenix#26104]
### Steps to reproduce

1. Load site secured with basic auth
2. Web server logs show proper 401 response was returned
3. Firefox hangs forever with no auth dialog; stuck in loading state
4. Try switching back and forth from private browsing mode
5. Rare chance happens to display dialog
6. Switch applications to copy password
7. Stuck in previous state, unable to get dialog (which previously was randomly displayed after about a dozen or so attempts) to reappear
8. Be rather upset, as Firefox is on a tragic trajectory
9. Wonder if DNS over HTTPS is breaking *another* basic functionality of the web
10. `about:config` is disabled, all documentation on DoH is completely invalid for fenix https://support.mozilla.org/en-US/kb/firefox-dns-over-https#w_opt-out
11. _Sigh_, Mozilla, you are the last hope for the web, and you are not upholding your duty
12. Contemplate throwing your phone off the balcony; mobile is hopeless already, and getting worse every day, so we might as well all become ceramists sans any form of connectivity, as pottery won't ever let you down like Mozilla tends to
13. Wish for the golden period of the web, from ~2002-2014, to come back...

### Expected behaviour

filled above

### Actual behaviour

filled above

### Android version

latest 

### Firefox release type

Firefox

### Firefox version

latest

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21065)

**Comment by kbrosnan** [comment]
I can reach a Mozilla http auth page and the second button on https://authenticationtest.com/ triggers the auth dialog. In Firefox 102-104
