### ISSUE TITLE
Allow downloading to standard external sdcard Download folder

### ISSUE THREAD

**Issue by TheGoddessInari** [mozilla-mobile/fenix#2610]
### Why/User Benefit/User Problem
On Firefox Mobile and Fenix, downloads are restricted to the internal storage. Like other browsers, it should at least offer a choice whether to download to the standard internal storage Download folder, or the standard sdcard/external storage folder.

### What/Requirements
Option to download to external storage.

### Acceptance Criteria (how do I know when I’m done?)
When Fenix can download to external storage's default Download folder properly without deleting files on uninstall.

**Comment by kbrosnan** [comment]
Closing as a dupe of #5764
