### ISSUE TITLE
Swipe to delete is buggy for the tabs tray - list view composable

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26109]
Seems like the composable version is still using `TouchCallback` which is not the optimal approach for composable and seems to also have issues for the scenario in which the selected tab is swiped.

https://user-images.githubusercontent.com/11428869/180004007-2594ee7d-6f7f-4726-8a13-c0070728ba60.mp4

We should ensure the previous approach based on `TouchCallback` is not used for composables.
Instead we can use the official [`SwipeToDismiss` composable](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#SwipeToDismiss(androidx.compose.material.DismissState,androidx.compose.ui.Modifier,kotlin.collections.Set,kotlin.Function1,kotlin.Function1,kotlin.Function1)) to get the same behavior.
An example for using this is available in https://github.com/mozilla-mobile/fenix/pull/24682

cc @Alexandru2909

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21069)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813795

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
