### ISSUE TITLE
[Bug]: [Tabs Tray] Application crashes after switching from private to normal tab tray and vice versa

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26100]
### Preconditions:
Make sure you have some open tabs in both Normal and Private Browsing.

### Steps to reproduce

**Please note his issue is intermittent** 

1. While in Private Browsing tap "Tabs counter" button
2. From the Tabs Tray, tap the Normal Browsing Open tabs icon 
3. From the Tabs Tray, tap the Private Browsing Open tabs icon
4. Tap the "New PRIVATE tab" button
5. Tap the upper right PB icon
6. Tap "Tabs counter" button. During this steps the crash occurs.

### Expected behaviour

The app is stable and the user can switch between the normal and private tabs tray.

### Actual behaviour

 Application crashes after switching from private to normal tab tray and vice versa

### Device name

Tablet Sony Xperia

### Android version

Android 6.0.1

### Firefox release type

Firefox Nightly

### Firefox version

Debug Build: 1.0.2229

### Device logs

Please check the following [link.](https://crash-stats.mozilla.org/report/index/228cbf53-86c6-4eb9-b3e6-8cfaa0220719)

### Additional information

Link debug build: https://firefox-ci-tc.services.mozilla.com/tasks/UCQAnJ1cSVG5_mUcjOUuxA
 
QA request: https://mozilla-hub.atlassian.net/browse/QA-1561

Please note this issue occurs only on Debug Build: 1.0.2229

![Crash](https://user-images.githubusercontent.com/108326843/179787324-f41e6ab9-9470-494f-a6d6-53227bbe76a2.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21060)

**Comment by AdinaPetridean** [comment]
@kbrosnan the Socorro URL is in Device logs field. I'll put it [here](https://crash-stats.mozilla.org/report/index/228cbf53-86c6-4eb9-b3e6-8cfaa0220719) also.

**Comment by kbrosnan** [comment]
Ah I thought that was a logcat link so I did not look at it. As this seems to be an IME crash I opened a bug for it in Bugzilla.

bz-1780745
