### ISSUE TITLE
Telemetry for the new deleteAll history prompt

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26101]
Relates to [this](https://github.com/mozilla-mobile/fenix/issues/25954).

We have a new `deleteAll` [dialog](https://www.figma.com/file/SO8Cd5lnmgNqJQY9KpORc9/History%2C-Bookmarks%2C-Downloads?node-id=867%3A28274), that instead of removing all items at once, allows user to choose a time range of items to delete.

Currently, we are tracking `removedAll` event. Do we want to track other time frames as well?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21062)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly from 07/28. The events generated:

<img src="https://user-images.githubusercontent.com/89388888/181453998-a66fbf40-f2ff-41a9-8364-3077848260d1.jpg" width="40%" />

**Comment by mavduevskiy** [comment]
@Mergifyio backport releases_v104.0.0
