### ISSUE TITLE
[Bug]: Details for a saved credit card are displayed after an interruption, followed by touching the "Recent" Android button 

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26107]
### Prerequisites: 
Make sure you have at least one credit card saved.

### Steps to reproduce

1. Go to Settings -> Autofill -> Manage saved cards->Saved cards
2. Tap on one saved credit card.
3. While in Edit card mode perform a home button interrupt.
4. Tap on Recent button from Android for resuming the Firefox app. 
5. Observe the edit card screen displayed. 

### Expected behaviour

The Autofill screen is displayed without information about saved credit card details.

### Actual behaviour

Details for a saved credit card are displayed after an interruption, followed by touching the "Recent" Android button. 

### Device name

One Plus 9 Pro

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1 20/07

### Additional information
This issue is also reproducible in Firefox RC 103.1.0. 
Please note the user can take screenshots of the credit card details.

https://user-images.githubusercontent.com/108326843/179997210-55b6efee-e02a-45de-9bd7-f8be0a8a2c82.mov

![bug](https://user-images.githubusercontent.com/108326843/179998399-8d0d64e7-20f2-4d14-8ef0-18731e068f72.JPEG)

**Comment by delia-pop** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1817014

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
