### ISSUE TITLE
Larger Minimum Scrollbar Size

### ISSUE THREAD

**Issue by thedward** [mozilla-mobile/fenix#2611]
### Why/User Benefit/User Problem
On very long pages (frex <https://www.metafilter.com/180757/To-be-or-not-to-be-ay-theres-the-point>) the  ephemeral scrollbar that appears when scrolling the page and shows the current scroll position on the page is so small that it's almost Invisible.

### What/Requirements
The scrollbar should be scaled based on the length of the page—matching current behavior—with the exception that it never be scaled below some predefined clearly visible size.

### Acceptance Criteria (how do I know when I’m done?)
When, while scrolling through even a very long page, you can tell at a glance the current scroll position.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11548)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809980

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
