### ISSUE TITLE
Recent synced tab should retrieve hero image URL from synced history

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26124]
Currently, a centered favicon is being displayed in the recent synced tab on the homescreen. A better image can be retrieved by looking up the `previewImageUrl` for the Places history entry (which is Sync'd), and using that instead of the `iconUrl` attached to tabs.

See [the bookmark implementation](https://searchfox.org/mozilla-mobile/rev/198e453c187b93d0e2e52776f99fb1c0061ca1aa/fenix/app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt#83) for how this can be done.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21076)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 105.0a1 (2022-08-18) and for many websites the favicon do not not sync. I've attached a screenshot illustrating the issue, on the left are the favicons loaded on the original device and on the right is what these favicons look when synced to another device.
![sync](https://user-images.githubusercontent.com/50983519/185400707-7af4567a-aaa8-4df9-9f44-a66449654ede.png)
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 (Android 12)

**Comment by MatthewTighe** [comment]
@LaurentiuApahideanSV I don't believe we can display favicons or hero images until a site has been loaded locally. Had the tabs above been visited on the device that they are only displaying letters on?

**Comment by MatthewTighe** [comment]
I'm now seeing that we may be missing preview image URLs from our history object. I filed https://github.com/mozilla-mobile/fenix/issues/26591 to investigate further

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813797

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
