### ISSUE TITLE
[Bug]: Auto locking the device is inhibited

### ISSUE THREAD

**Issue by franky01gg** [mozilla-mobile/fenix#26122]
### Steps to reproduce

1 Open youtube
2 Play a video
3 Disable auto play next on youtube (the point is that the video has to stop)
4 Enter full screen mode
5 Play the video till the end.
6 Leave the device on that last screen (its a button to play the video again)

### Expected behaviour

The device will lock after the time specified in the system settings of that device.

### Actual behaviour

The device doesn't lock. It stays on that last screen, no matter how much time has passed.

### Device name

Huawei mate 20 pro 

### Android version

Huawei's EMUI 12.0

### Firefox release type

Firefox

### Firefox version

102.2.1

### Additional information

The expected behavior works in chromium based browsers like Brave.

It can be tested on other online video players, that can enter full screen mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21075)

**Comment by amocirean** [comment]
comm added

Hello [name], thank you for submitting the issue.
I was able to reproduce it on the latest RC and Nightly


Device Used: Google Pixel 4
Android Version: 12

**Comment by amocirean** [comment]
Hello @franky01gg , thank you for submitting the issue.
I was able to reproduce it on the latest RC and Nightly


Device Used: Huawei P40 Lite
Android Version: 10

**Comment by LaurentiuApahideanSV** [comment]
This issue has been fixed by https://github.com/mozilla-mobile/fenix/issues/26236, @franky01gg Could you please install the latest Firefox Nightly and check if the issue still occurs?

**Comment by franky01gg** [comment]
> This issue has been fixed by #26236, @franky01gg Could you please install the latest Firefox Nightly and check if the issue still occurs?

Yes, the issue is now fixed.

**Comment by opusforlife2** [comment]
@LaurentiuApahideanSV ^

**Comment by jonalmeida** [comment]
Closing as fixed as reported by the OP.
