### ISSUE TITLE
[Bug]: The device name in the account menu is not updated right away

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/fenix#26138]
### Steps to reproduce

1. Open the setting menu in fenix
2. Make sure you are signed into a firefox account
3. tap on your email to get to the account settings
4. tap on the device name to rename the device
5. enter a new name
6. quickly go back outside the menu, then repeat steps 3 - 5

### Expected behaviour

The new name should always be reflected

### Actual behaviour

The old name would be displayed on the `Device Name` menu.

https://user-images.githubusercontent.com/5303520/180305158-277001ca-fe68-497c-a054-1966506a3ae8.mp4

### Device name

Samsung S8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

102.2.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21087)

**Comment by delia-pop** [comment]
Hi, @tarikeshaq, the issue you describe was previously reported in ticket https://github.com/mozilla-mobile/fenix/issues/17100. 
I will close this as duplicate.
