### ISSUE TITLE
Move Tabs Tray to compose: TabsTrayFragment to use ModalBottomSheetLayout

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26131]
[TabsTrayFragment](https://github.com/mozilla-mobile/fenix/blob/f58f1541ce5085a060015fee00c8cab3bf85210b/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt) currently uses a `ContraintLayout` with a `BottomSheetBehavior`.

To composify it our options now are either
- [BottomSheetScaffold](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#BottomSheetScaffold(kotlin.Function1,androidx.compose.ui.Modifier,androidx.compose.material.BottomSheetScaffoldState,kotlin.Function0,kotlin.Function1,kotlin.Function0,androidx.compose.material.FabPosition,kotlin.Boolean,androidx.compose.ui.graphics.Shape,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.unit.Dp,kotlin.Function1,kotlin.Boolean,androidx.compose.ui.graphics.Shape,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,kotlin.Function1)) which doesn't block the interaction behind or
- [ModalBottomSheetLayout](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#ModalBottomSheetLayout(kotlin.Function1,androidx.compose.ui.Modifier,androidx.compose.material.ModalBottomSheetState,androidx.compose.ui.graphics.Shape,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,kotlin.Function0)) which will autoclose the bottom sheet for outside touches.

So to keep the current behavior `ModalBottomSheetLayout` seems like a better choice.

&nbsp;
The migration will also need to ensure all previous functionality is kept:
- supporting screen rotation and bottom sheet rotation
- support two stages for expanding
- support for custom tips and CTA
- support for snackbars
- support for a FAB

Work for supporting the above can be broken off and added separately.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21082)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810779

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
