### ISSUE TITLE
Intermittent debug(T) test failure - Execution failed for task ':app:nimbusExperimenter'.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#26133]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=384977759&repo=fenix
### Stacktrace:
```
> Task :app:assembleNimbusTools
Checking fml binaries in /builds/worker/checkouts/vcs/app/build/bin/nimbus/nimbus-fml
Downloading archive to /builds/worker/checkouts/vcs/app/build/bin/nimbus/nimbus-fml.zip
OS and architecture detected as linux on amd64
Unzipping binary, looking for x86_64-unknown-linux-musl/nimbus-fml

> Task :app:nimbusExperimenter FAILED
Nimbus FML generating JSON
manifest   /builds/worker/checkouts/vcs/nimbus.fml.yaml

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:nimbusExperimenter'.
> A problem occurred starting process 'command '/builds/worker/checkouts/vcs/app/build/bin/nimbus/nimbus-fml''
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/6a14c89e7f7d33e3d2070079f32a4f089ea34a14

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21083)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813799

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
