### ISSUE TITLE
[UI test automation] Improve coverage of the UI smoke test suite

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26144]
### Summary

Improve coverage of the [UI smoke test suite](https://testrail.stage.mozaws.net/index.php?/suites/view/3192&group_by=cases:section_id&group_order=asc&group_id=45740):
• Create new UI tests
• Add missing steps

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21090)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807279

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
