### ISSUE TITLE
[Bug] Constant Crashes in MIUI V10/Android Pie

### ISSUE THREAD

**Issue by Leofravega** [mozilla-mobile/fenix#2614]
## Steps to reproduce
Install APK From PlayStore
Open Fenix.
Crash.

### Expected behavior
Install APK From Playstore
Open Fenix.
App Launches

### Actual behavior
Crash to homescreen

### Device information
Redmi Note 7 Global
CPU: Snapdragon 660
RAM: 4GB
ROM: 64GB

* Android version: 9 PKQ1 with MIUI Global 10.3 (stable) on top
* Fenix version: 1.0.1920
[MIUI REPORT.txt](https://github.com/mozilla-mobile/fenix/files/3192859/MIUI.REPORT.txt)

**Comment by drbluetongue** [comment]
I also get this on Redmi Note 5 AI MIUI with Android Pie.

**Comment by borivojek** [comment]
I'm also having this issue on Redmi Note 7 Global 4/64
Android version 9 PKQ1.180904.001, 2019-04-05 security patch
MIUI version 10.3.5.0
Fenix version 1.0.1920

**Comment by ekager** [comment]
Closing as dupe. This issue has been fixed with #2617 and you will get an update soon
