### ISSUE TITLE
Allow third-party apps to open a private tab

### ISSUE THREAD

**Issue by yawkat** [mozilla-mobile/fenix#26158]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

There should be a way for third-party apps to signal that they want to open a link (ACTION_VIEW intent) in a private tab. e.g. when doing the equivalent of private browsing in another app, that app should have the ability to open browser links in a firefox private tab as well.

fennec had this feature as described here: https://bugzilla.mozilla.org/show_bug.cgi?id=1347583 however apparently it was not implemented in fenix.

### How do you know that this problem exists today? Why is this important?

I've looked at the latest fenix source code. Private mode seems to be communicated using the 'private_browsing_mode' extra, however it is overwritten by the `IntentReceiverActivity`. 

### Who will benefit from it?

Probably not very many people, since it still requires explicit support by third-party apps. However the possibility of adding support would be a nice addition.

---

As the change seems fairly easy, I can work on a PR for this issue. However I'm not sure if this project requires CLA approval by the employer. If it does, I probably won't be able to get that approval easily enough to make it worth it. If no CLA is required, I can contribute.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21100)

**Comment by delia-pop** [comment]
Hi @yawkat, thanks for reporting. I will mark this as feature request.
However, please note that this topic was previously discussed in https://github.com/mozilla-mobile/fenix/issues/14499.

**Comment by yawkat** [comment]
@delia-pop thanks for the reference. Since this is such a simple change, I could prepare a PR. Is a CLA required for contributing here?

**Comment by kwyntes** [comment]
Any updates on this?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807531

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
> @delia-pop thanks for the reference. Since this is such a simple change, I could prepare a PR. Is a CLA required for contributing here?

@yawkat: I moved this GitHub issue to a Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1807531 because Mozilla is consolidating our Firefox and Focus Android GitHub repos. For more info, see https://github.com/mozilla-mobile/fenix/issues/26855.

No CLA is required to contribute to Firefox. I'm not a code reviewer, but if this functionality was previously available in Fennec, we would likely accept a patch to add it to Fenix.
