### ISSUE TITLE
[Bug]: If tabs are not being Sync'd for an account, the recent synced tab card should not appear

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26150]
Currently, if a user is logged in to an FxA account but has opted out of syncing tabs, the recent synced tab card appears to load indefinitely on the home screen. Instead, it should just not be displayed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21094)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 105.0a1 (2022-07-28) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.

**Comment by cpeterso** [comment]
@MatthewTighe - Did you intend to reopen this issue? Is this bug still a problem?

**Comment by MatthewTighe** [comment]
Yes, there hasn't been a patch landed for it yet. I will mark as QA needed and clarify reproduction steps once I have a fix available.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 105.0a1 (2022-08-18) and the issue no longer occurs, after the Open tabs option is switched off the sync tab card will disappear from the device where it was turned off and all other synced devices:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
