### ISSUE TITLE
Browser crashes when closing custom tab

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#2615]
## Steps to reproduce
-Open a custom tab in Fenix (from Gmail or Slack)
-Close custom tab (using the custom tab back arrow, not the phone back button) to go back to the 3rd party app

### Expected behavior
-No crash

### Actual behavior
-There is Fenix crashed dialogue

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1920

**Comment by kbrosnan** [comment]
This is likely fixed by #2617 which reverts the GV update which caused a startup crash.

**Comment by vesta0** [comment]
More info here #2414

**Comment by Seqularise** [comment]
@kbrosnan I'm on a latest build from gps, still crashes

**Comment by boek** [comment]
dup of #2414
