### ISSUE TITLE
Google business search results broken

### ISSUE THREAD

**Issue by rickthepick** [mozilla-mobile/fenix#26157]
On Firefox Google search results for businesses are missing much of the content that is available in Chrome.  For example, there is no way to access the Google reviews for a business in Firefox.  Please compare the following two screenshots.  The Firefox results are missing the buttons for "Menus", "Reviews", "Photos"...

Firefox
![Screenshot_20220724-010459](https://user-images.githubusercontent.com/328585/180633099-64101f51-3221-4c56-be32-abfc595d63ec.png)

Chrome
![Screenshot_20220724-010554](https://user-images.githubusercontent.com/328585/180633113-94fd6893-a23a-4814-b745-27d35f78f67b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21099)

**Comment by Mikaka27** [comment]
Google is doing that, not firefox, you can fix this with that extension: https://addons.mozilla.org/pl/firefox/addon/google-search-fixer/

**Comment by rickthepick** [comment]
Thanks.  That workaround extension was created in 2017 and requires access to browsing data for all websites: https://addons.mozilla.org/en-US/firefox/addon/google-search-fixer/versions/

Is it possible for Firefox to fix the issues that apparently led Google to give a degraded search experience for Firefox users?

**Comment by kbrosnan** [comment]
This is Google 's choice. bz-975444
