### ISSUE TITLE
[Bug]: laggy and pixelated vidio playback

### ISSUE THREAD

**Issue by holequantum** [mozilla-mobile/fenix#26162]
### Steps to reproduce

open my link and watch a video you will find a choppy video playback

### Expected behaviour

it should play smoothly i have reinstall twice but same issue even in the beta one here is one link
https://www.hotstar.com/in/tv/godhuli-alap/1260089293/noloks-ultimatum-to-rohini/1000278455

### Actual behaviour

![Screenshot_20220725-110845~2](https://user-images.githubusercontent.com/108695843/180706672-256461d8-6568-493d-aa2d-8841817578dd.png)
it should not be like this you cant play videos in hotstar it only happens in some shows which is not an issue in  chrome or chromium or bromite. this was not the case in last 1month or so it was started

https://user-images.githubusercontent.com/108695843/180708743-99021f3d-a1ec-4de1-9b56-a35f247d10cb.mp4

### Device name

realme and moto one, pixel 5

### Android version

android 12 ,android 11, android 9, android 10

### Firefox release type

Firefox

### Firefox version

102.2.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21102)

**Comment by Mugurell** [comment]
Thank you for the report @holequantum!
Moving to Bugzilla for more investigations. 
Please help with posting the data from `about:support` and follow the developments there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1781013

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment]
@holequantum As a followup to https://bugzilla.mozilla.org/show_bug.cgi?id=1781013#c2 can you please try on the latest versions (Release 103 and Nightly 105) and report back if the issue still reproduces?
If it does still reproduce posting in Bugzilla the info from `about:support` might help troubleshooting this issue .

**Comment by holequantum** [comment]
issue does not appear if ublock is disabled but else issue is present.
https://cryptpad.fr/code/#/2/code/edit/Ll2-OwJk8I3PBjed2GMArJDN/

**Comment by jamienicol** [comment]
@holequantum does the website give you any technical information about the video, like youtube's "stats for nerds". ie which codec it's using, etc? If so, could you provide that information for both the "ublock disabled: working" case and the "ublock enabled: buggy" case?

Could you also in Firefox beta or Nightly set `gfx.webrender.software` to `true` in about:config, restart the browser, and see if that makes a difference? Thanks!

**Comment by holequantum** [comment]
you can check yourself i have shared a link and install firefox and add ublock and open that link yoi will see whats wrong

**Comment by jamienicol** [comment]
Unfortunately I cannot play videos on that site as I'm not in the right country, and a VPN didn't work either.

**Comment by holequantum** [comment]
> Unfortunately I cannot play videos on that site as I'm not in the right country, and a VPN didn't work either.

i think connecting to a indian server will work. can you try with a vpn and connect to indian server. windscribe provide a 10gb free vpn you can try i have not chnage anything on ublock just installed and play i also only have ublock nothing else as extension.
