### ISSUE TITLE
Unable to stop activity {org.mozilla.fenix/org.mozilla.fenix.customtabs.CustomTabActivity}: java.lang.IllegalArgumentException: Required value was null

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#2616]
Details at https://sentry.prod.mozaws.net/operations/fenix/issues/5713056/events/30178467/

```
java.lang.IllegalArgumentException: Required value was null.
    at org.mozilla.fenix.browser.BrowserFragment.getSessionById(BrowserFragment.kt:5)
    at org.mozilla.fenix.browser.BrowserFragment.onStop(BrowserFragment.kt:3)
    at androidx.fragment.app.Fragment.performStop(Fragment.java:10)
    ...
```

@jhugman this looks related to https://github.com/mozilla-mobile/android-components/pull/2954/files which landed in Fenix (via A-C) on the 14th, which the date this crash became a top crasher in Fenix.

**Comment by agi90** [comment]
Sentry issue: [FENIX-Y9](https://sentry.prod.mozaws.net/operations/fenix/issues/5713056/)

**Comment by Amejia481** [comment]
No any occurrences in new versions
