### ISSUE TITLE
"Download Link" doesn't work

### ISSUE THREAD

**Issue by aidinzolghadr** [mozilla-mobile/fenix#26176]
### Steps to reproduce

1. Go to [this website ](https://en.wikipedia.org/wiki/File:Boulevard_du_Temple_by_Daguerre.jpg)
2. Press and hold on the first image to save it's target with"Download Link" option.

### Expected behaviour

What it should do, as it does in Desktop version, is to save the link the thumbnail is pointing to, NOT the thumbnail itself, which is [this](https://upload.wikimedia.org/wikipedia/commons/d/d3/Boulevard_du_Temple_by_Daguerre.jpg)

### Actual behaviour

What it currently does is to save the thumbnail instead, which is [this](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Boulevard_du_Temple_by_Daguerre.jpg/1200px-Boulevard_du_Temple_by_Daguerre.jpg).

### Device name

Huawei Mate 10

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

102.2.1 (Build #2015891003)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21108)

**Comment by delia-pop** [comment]
Hi, @aidinzolghadr, thanks for reporting. 
I can reproduce this issue on the latest Fenix versions.
Device used: Google Pixel 6 (Android 12).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812782

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
