### ISSUE TITLE
Investigate adding All type to RemoveTimeFrame

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26179]
Relates to this [discussion](https://github.com/mozilla-mobile/fenix/pull/26153#discussion_r928851395). 

I have concerns of not using the `All` type `LongRange` parameters, since the provider doesn't need any parameters to remove all items. But adding `All` type would make the code more readable.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21109)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813801

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
