### ISSUE TITLE
Add Telemetry to Synced History Screen

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26185]
Relates to [this](https://github.com/mozilla-mobile/fenix/pull/25943)

The required telemetry would be:
– How often does someone open the synced history view;
– How often does someone open a synced history item.

The ideal telemetry for synced history would copy the history events
https://dictionary.telemetry.mozilla.org/apps/fenix?page=1&search=history

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21113)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813802

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by SoftVision-LorandJanos** [comment]
This ticket will be tracked and verified when ready in bugzilla.
Closing and removing the QA needed label here.
