### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JoshuaChory** [mozilla-mobile/fenix#26181]
Attempting to view a pdf from a website (like trying to view a resturaunt menu) while on Firefox Android will only prompt users to download the pdf instead of viewing it. Does Firefox just not have the capability to view pdf files? There seems to be no workaround except using a seperate browser and that is not a working solution

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21111)

**Comment by kbrosnan** [comment]
It does not. Duplicate https://github.com/mozilla-mobile/fenix/issues/4337

**Comment by JoshuaChory** [comment]
Thanks for at least letting me know...seems like this should be a common feature but I'm no web developer. Would be nice if I didnt have to switch to Chrome just to look at resturaunt menus, but at least it's been talked about already. Thanks again!

**Comment by kbrosnan** [comment]
PDF.js adds several MB to the final size to the app, needs some UX review to make sure the UI works well on mobile and some performance evaluation to check how it performs on low spec phones from several years ago. It is something we are looking at but are not sure it is the most important current need of Fenix users.
