### ISSUE TITLE
Update jump back in onboarding message logic and message

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#26190]
A Jump Back In pop up message will be displayed on the homepage under the following the conditions:

- users from v105 or earlier should never see it
- should only ever be shown to a user once
- should not be shown if the synced tab pickup message is already showing or if the has already seen the synced tab pickup message

If the user clicks on the X to close the message or clicks elsewhere on the homepage, then the message will close.

The pop up message matches the [attached designs](https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?node-id=2063%3A56599).

The changes are behind the MR Onboarding feature flag.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21117)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest debug build (GV: 106.0a1-20220904093956).
Will be re-tested on Nightly when available.
Device used: Oppo Find X5 (Android 12).
The last synced tab message was verified here: #26489 .
Closing the ticket as verified.
![Screenshot_20220906-094233](https://user-images.githubusercontent.com/48829350/188566414-d4768562-b1a0-4eb2-a4be-53772f901de6.png)
