### ISSUE TITLE
Add telemetry for jump back in onboarding message

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#26191]
The following telemetry should be captured:
- Impression counts 

- Click counts on the X

- Clicks elsewhere on the screen that close the message are counted

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21116)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Fenix Debug build 1.0.2237 (2022-09-06) by interacting with the Jump back in onboarding message and observing the results.
When the Jump back in onboarding message is shown:
{
          "timestamp": 13864,
          "category": "recent_tabs",
          "name": "jump_back_in_cfr_shown"
        },

When the the user taps the close button from the Jump back in onboarding message:
        {
          "timestamp": 16830,
          "category": "recent_tabs",
          "name": "jump_back_in_cfr_dismissed"
        }

When the the user taps outside the Jump back in onboarding message and closes the message:
{
          "timestamp": 9817,
          "category": "recent_tabs",
          "name": "jump_back_in_cfr_cancelled"
        }

[Glean link](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-0609)
### Device used:
- Samsung Galaxy S22 Ultra (Android 12)
