### ISSUE TITLE
[Bug]: Crash on my website

### ISSUE THREAD

**Issue by deepakumar8** [mozilla-mobile/fenix#26193]
### Steps to reproduce

Open the tab
Try to Login Enter Username and password , Tap on Login

### Expected behaviour

Application Should not be crashed

### Actual behaviour

Crashing on Login Screen

### Device name

Samsung galaxy fold 2

### Android version

12

### Firefox release type

Firefox Beta

### Firefox version

67

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21118)

**Comment by kbrosnan** [comment]
Firefox 67 is not supported. If you can reproduce this in [modern Firefox](https://github.com/mozilla-mobile/fenix/wiki#download) please provide [crash ID URLs](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information)
