### ISSUE TITLE
Control characters shouldn't be considered part of the URL when filling link from clipboard

### ISSUE THREAD

**Issue by yedayak** [mozilla-mobile/fenix#26194]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
When I have text in my clipboard that has a link followed by a control character - for example \u200E - Firefox offers to "fill link from clipboard" with the link. When you accept the offer the actual link that gets filled includes the control character, url encoded at the end. 
Example: `https://t.co/0qWwlrKXtm‎` Turns to `https://t.co/0qWwlrKXtm%E2%80%8E`. This behavior kind of makes sense when directly pasting the link directly, but I think the selection of links from text should be smart enough to not include those types of control characters when detecting links in text.

### How do you know that this problem exists today? Why is this important?
I experience this issue when copying text in right to left languages (Hebrew) that include \u200E and \u200F, and selecting links from that text does not work without manually editing the url.

### Who will benefit from it?
Anyone who uses the "fill link from clipboard" with text that has control characters, such as hebrew or arabic text.

The code that deals with this is here: https://github.com/mozilla-mobile/android-components/blob/9a56645ca01d7ee9bb40aa49c848cadce652b528/components/support/utils/src/main/java/mozilla/components/support/utils/WebURLFinder.kt#L78 and here: https://github.com/mozilla-mobile/fenix/blob/0127b39faddc461365b17b87556f01a3b8d6cfa8/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt#L59

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21119)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813804

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
