### ISSUE TITLE
FNX3-16456 ⁃ Need full screen functionality and "Entering full screen" transition message

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#262]
Entering full screen does not work in Fenix. This demo page of full screen API correctly goes full screen in the Reference Browser, but not in Fenix:

https://www.davidwalsh.name/demo/fullscreen.php

Also, Fenix needs an "Entering full screen" transition message. This is a security feature to prevent malicious websites from pretending to a different website (e.g. posing as your bank website to steal your bank password).

Showing the message is the responsibility of the app embedding GV, not GV itself:

https://bugzilla.mozilla.org/show_bug.cgi?id=1517809#c12

**Comment by bbinto** [comment]
Seems like something that we should do sooner than later, please size today and move to milestone 2 backlog. Any UX needed?

**Comment by pocmo** [comment]
The `feature-session` component contains `FullScreenFeature` that can help with implementing the fullscreen transition. See Reference Browser for an example of the usage. The message may be something we want to add to the component.
