### ISSUE TITLE
Java.langOutOfMemoryError: Failed to allocate a ## byte allocation with X free bytes and Y KB until OOM

### ISSUE THREAD

**Issue by Beyonderforce** [mozilla-mobile/fenix#26201]
See how ridiculous this has gotten?

When are we getting a fix for this?

![Screenshot_20220727-133843_Firefox](https://user-images.githubusercontent.com/56373152/181170096-7e316e98-41ec-466e-8154-4d3eb95f0a37.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21126)

**Comment by kbrosnan** [comment]
Your phone is telling Firefox there is no free memory to run applications. Firefox is asking for a very small amount of memory and the OS is saying there is none. Generally this is a sign that the phone needs to be rebooted and or space freed up on the  device. If this persists past a reboot then if you are willing to get some troubleshooting data then we can look into it.

**Comment by cpeterso** [comment]
Moved to Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1722924
