### ISSUE TITLE
Chrome-like tab groups

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#26208]
### What is the user problem or growth opportunity you want to see solved?

Users with a bunch of open tabs can get overwhelmed with managing and navigating them.

### How do you know that this problem exists today? Why is this important?

When you have a lot of tabs open you very frequently use (e.g. traffic alerts, public transport schedules) and then open some more temporarily (e.g. news articles), the amount of tabs makes it hard to navigate between them comfortably and requires a lot of scrolling to find the right one. Adding a Chrome-like tab groups feature would allow users to group their tabs based on their preference (e.g. frequently used tabs into their own group and temporarily needed tabs into another or even simply leaving them ungrouped).

This would be different from the search groups feature that was present in Firefox for Android, as these groups would be created manually by the user.

Example of a tab group and an ungrouped tab in Chrome:

![Screenshot_20220727_202544.jpg](https://user-images.githubusercontent.com/20287690/181345440-bb0fd1eb-6ea4-498d-b7d8-4efb29e715f9.jpg)

### Who will benefit from it?
Power-users and "tab hoarders".

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21129)

**Comment by rahaaatul** [comment]
I second this! This is a must have feature!

**Comment by bbhtt** [comment]
This is probably the same as this https://github.com/mozilla-mobile/fenix/issues/5967 feature request.

**Comment by boek** [comment]
Closing as a dup of #5967
