### ISSUE TITLE
Create the wallpaper selection onboarding dialog. 

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26216]
Create a dialog that appears over the home screen allowing users to preview and test out new wallpapers. It should be hidden behind the feature flag defined in [this JIRA ticket](https://mozilla-hub.atlassian.net/browse/FNXV2-21025). There is more behavior defined in the original ticket defining this work [here](https://mozilla-hub.atlassian.net/browse/FNXV2-20989). Some of the underlying behavior has been broken into separate tickets, listed below. The telemetry will be handled in a follow-up.

AC:
- A wallpaper selection tool will be displayed on the homepage under the following the conditions:
  - Tab Pickup and Jump Back In CFRs are not currently being displayed
  - Wallpaper thumbnails have been downloaded
  - The user has not seen the wallpaper selection tool before

- The wallpaper selection tool includes the following wallpaper options:
  - The first 3 classic wallpapers
  - The first 2 seasonal wallpapers (or additional 2 classic wallpapers if there are no seasonal)
  - A no wallpaper option

- When a user clicks on one of the wallpaper thumbnails in the wallpaper selection tool, it will change their homepage background right away, so that they can see it

   - If the full wallpaper has not been downloaded, then they will see a loading indicator & the thumbnail should go 50% less in its opacity until loading is completed

- If the user clicks on the homepage or clicks the X, then the selection tool will close

- If the user clicks on the button to explore wallpapers, they will be taken to the wallpapers setting in the menu
- The wallpaper selection tool matches the [attached design](https://www.figma.com/file/d7l1iGabQYqnLcnQbHDGzM/Wallpaper-2.0?node-id=5410%3A178252)

Dependent on:

1. https://github.com/mozilla-mobile/fenix/issues/26423
2. https://github.com/mozilla-mobile/fenix/issues/26211
3. https://github.com/mozilla-mobile/fenix/issues/26212
4. https://github.com/mozilla-mobile/fenix/issues/26213
5. https://github.com/mozilla-mobile/fenix/issues/26214
6. https://github.com/mozilla-mobile/fenix/issues/26424

Telemetry:

- https://github.com/mozilla-mobile/fenix/issues/26215

All of this work would likely be better served if it was saved until after the refactor work being tracked here: 

- https://github.com/mozilla-mobile/fenix/issues/26034

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21134)

**Comment by delia-pop** [comment]
This is Verified as fixed on Nightly 107.0a1 from 09/29 with Google Pixel 6 (Android 13) and Xiaomi 12 Pro (Android 12). The wallpaper selection tool is displayed on the 3rd homepage visit. 
![1664280960797](https://user-images.githubusercontent.com/89388888/193031744-de128fe8-56d6-4f03-9e75-ad42df40cb63.JPEG)
