### ISSUE TITLE
Automatic Reader View

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2621]
### Why/User Benefit/User Problem
As a user, I would like to automatically open sites in reader view, to provide a more pleasant reading experience, automatically. 

### What/Requirements
* option to automatically open a site in reader view in QAB
* option to stop automatically opening site in reader view in QAB
* Provide a way to remove preference to open site in reader view without visiting site in settings

See https://www.macrumors.com/how-to/enable-automatic-reader-view-in-safari/ for how Safari on iOS does it. 

### Acceptance Criteria (how do I know when I’m done?)
User can visit a site supported by reader view and never see the original page styling on a supported article page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11555)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812062

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
