### ISSUE TITLE
Clicking wallpaper thumbnails should download the full version.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26212]
If a wallpaper thumbnail isn't downloaded when clicked, it should be downloaded. 

- When a wallpaper is clicked a loading indicator should be shown and the thumbnail opacity should be set to 50% while the wallpaper downloads.
- When a wallpaper is finished downloading it should be shown normally

Note: this is specifically for the settings page but should be done such that it can be easily copied into the upcoming wallpaper onboarding card. This means exposing a click handler or something similar so that the home screen can update its view with the newly selected wallpaper. This is dependent on https://github.com/mozilla-mobile/fenix/issues/26211

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21130)

**Comment by MatthewTighe** [comment]
Note that the underlying functionality to download a wallpaper on click will be added in https://github.com/mozilla-mobile/fenix/pull/26562/files

This ticket is about responding to changes in `wallpaper.assetsFileState` appropriately to show the loading indicator and opacity.

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/20 with Google Pixel 6 (Android 13). When tapping on the wallpaper thumbnails, a loading indication is displayed and the thumbnail opacity changes during the download. The wallpaper is correctly displayed after download.

https://user-images.githubusercontent.com/89388888/191442907-eddda913-7706-4e4b-8dee-1d89a25be9bc.mp4
