### ISSUE TITLE
Add a method of retrieving a thumbnail for a wallpaper

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26213]
Given a wallpaper, there should be a way to retrieve the thumbnail for it. This should probably be exposed from a `WallpaperUseCase` that can be created during the refactoring tracked by https://github.com/mozilla-mobile/fenix/issues/26034, but could be added to `WallpaperManager` if necessary.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21133)

**Comment by delia-pop** [comment]
Tested with the latest Debug build updated from main and latest Nightly from 09/02 with Google Pixel 6 (Android 13). After installing and launching the application, the wallpaper thumbnails were displayed in the Wallpapers menu in Settings.

https://user-images.githubusercontent.com/89388888/188175203-516fb47d-31b4-4267-a90c-1ef74484b75f.mp4
