### ISSUE TITLE
Wallpaper thumbnails should be downloaded at app startup.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26214]
Instead of downloading full images at app startup, we should download wallpaper thumbnails. This saves user's network costs and storage space until they download the full images. A property should be added to the `Wallpaper` type that tracks whether the thumbnail is downloaded or not, so that we know when it's safe to show the new Wallpaper onboarding card. 

I would suggest adding this functionality to a `WallpaperUseCase` after the refactoring being tracked by https://github.com/mozilla-mobile/fenix/issues/26034.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21132)

**Comment by delia-pop** [comment]
Tested with the latest Debug build updated from main and latest Nightly from 09/02 with Google Pixel 6 (Android 13). After installing and launching the application, the wallpaper thumbnails were displayed in the Wallpapers menu in Settings.

https://user-images.githubusercontent.com/89388888/188175431-167c1247-6ede-46fd-89cf-8cf50f3ce415.mp4
