### ISSUE TITLE
Add telemetry for the wallpaper selection onboarding tool. 

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26215]
See the [original JIRA ticket](https://mozilla-hub.atlassian.net/browse/FNXV2-20989) for more details. We are interested in measuring the following:

- When a user changes their wallpaper 
  - which wallpaper did they change it to
  - indication that it’s being changed from this tool, rather than settings
- A user closes the wallpaper selection tool
  - Whether or not they have chosen a wallpaper when they close the tool
- Impressions of the wallpaper selection tool
- Count of clicks on the button to explore more wallpapers

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21135)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/22 with Google Pixel 6 (Android 13). The following events were generated:

- The wallpaper onboarding dialog has been displayed:
{
          "timestamp": 12116,
          "category": "wallpapers",
          "name": "onboarding_opened"
        },
        
- A wallpaper is selected from the settings screen or onboarding dialog:
        {
          "timestamp": 14744,
          "category": "wallpapers",
          "name": "wallpaper_selected",
          "extra": {
            "name": "activist",
            "source": "onboarding",
            "theme_collection": "independent-voices"
          }
          {
          "timestamp": 20359,
          "category": "wallpapers",
          "name": "wallpaper_selected",
          "extra": {
            "theme_collection": "classic-firefox",
            "name": "amethyst",
            "source": "onboarding"
          }
          
 - The wallpaper onboarding learn more button was clicked:
          {
          "timestamp": 27771,
          "category": "wallpapers",
          "name": "onboarding_closed",
          "extra": {
            "is_selected": "true"
          }
        },
        {
          "timestamp": 27772,
          "category": "wallpapers",
          "name": "onboarding_explore_more_click"
        },
        {
          "timestamp": 27774,
          "category": "wallpapers",
          "name": "wallpaper_settings_opened"
        },
- The wallpaper onboarding dialog has been closed by tapping the "X" button:
        {
          "timestamp": 13792,
          "category": "wallpapers",
          "name": "onboarding_closed",
          "extra": {
            "is_selected": "false"
          }
