### ISSUE TITLE
TCP CFR

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26224]
https://mozilla-hub.atlassian.net/browse/FNXV2-20991

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21138)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Fenix debug build 1.0.2236 (2022-08-30) the TCP CFR is displayed once when visiting a website after a fresh install.
![Screenshot_20220830-150359~3](https://user-images.githubusercontent.com/50983519/187452375-61823108-ad5b-4ade-a7ce-6e5e318942e4.jpg)
### Devices used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 13)
