### ISSUE TITLE
Support for content blockers

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2622]
### Why/User Benefit/User Problem
Currently blocking content like ads, share banners, and comment sections, is not possible (completely) on Fenix. This may be fixed in the future by web extensions, but content blockers have advantages over extensions. They are lighter and faster, specially in weak mobile devices (I suppose). There are services made specially for mobile web already available that work with multiple browsers (Samsuns Internet, Yandex Browser, and Safari on iOS). They are easily manageable. I believe that, it may be worth considering.

### What/Requirements
Content blocker support

### Acceptance Criteria (how do I know when I’m done?)
It's possible to enable content blockers on Fenix, the same ones that can already be enabled in SI and Yandex; AdGuard for example (once the app is installed on the device).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11556)

**Comment by krystian3w** [comment]
`Content blocker` API have many restrictions e.g. no allow inject CSS or scriptlets (to defend anti-adblock wall).

**Comment by kbrosnan** [comment]
There are ad blockers that provide this on Fenix.
