### ISSUE TITLE
[Bug]: :active pseudo-class doesn't get added when element is in shadow DOM

### ISSUE THREAD

**Issue by jngbsn** [mozilla-mobile/fenix#26229]
### Steps to reproduce

Minimal example: https://jsfiddle.net/jngbsn/6pjy8qvx/9/

### Expected behaviour

Both buttons should turn red when pressed.

### Actual behaviour

The bottom button does not apply its :active CSS rule when pressed. If the site is viewed with the desktop version of Firefox in Responsive Design Mode with touch simulation enabled, the result is the same, the bottom button does nothing.

The :active CSS rule works if you apply it manually in devtools, and the element responds to pointer and touch events. Initially the bug was found with button elements, but seems to do the same with anchor and even div elements (from what I tested). However I did not test any other pseudo-classes.

Works as expected in desktop Firefox, as well as mobile and desktop Chrome.

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

102.2.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21141)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1782142

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
