### ISSUE TITLE
Website Timer Stops If Tabs Changed Or App Minimized

### ISSUE THREAD

**Issue by shawon2901** [mozilla-mobile/fenix#26220]
### Steps to reproduce

1.Many Websites Have Timer/Countdown To Download Files Or To Go To Next Page If I Minimize FireFox While That Countdown Is Running Then That Timer Gets Stuck But In Other Browsers The Timer Works In Background Too... Please Fix This...I Am Not Supposed To Look At A Trash Website Countdown Timer For 30Sec/60 Second

### Expected behaviour

The Timer Should Not Stop

### Actual behaviour

The Countdown Stops

### Device name

Poco X3 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21136)

**Comment by amocirean** [comment]
Hello @shawon2901  , thank you for submitting the issue.
I was not able to reproduce it on Nightly 105.0a1.
This behaviour could be caused by the website's back-end that would stop users from even changing from one page to another in order to skip the waiting time. Could you please tell me some websites that you encountered the issue on?

Device Used: Huawei P40 Lite
Android Version: 10

**Comment by shawon2901** [comment]
> Hello @shawon2901 , thank you for submitting the issue. I was not able to reproduce it on Nightly 105.0a1. This behaviour could be caused by the website's back-end that would stop users from even changing from one page to another in order to skip the waiting time. Could you please tell me some websites that you encountered the issue on?
> 
> Device Used: Huawei P40 Lite Android Version: 10

Strange You Cant Reproduce? It Literally Happens In Any Website That Has A Timer...

https://shareus.in/?i=CzTZ47

There Is 10 Second Timer There..Minimize FireFox Or Change Tabs For 10 Second Goto The App Again And You Would The Timer Didn't Move Or It Moved 2 SECOND Only Instead Of Finishing The 10 Second

**Comment by shawon2901** [comment]
Any ETA When Will This Be Fixed ?

**Comment by amocirean** [comment]
Hello @shawon2901 , sorry for the late reply. Did you manage to reproduce it on more websites? As I've said before, it could be linked with how the specific website is created, many websites have a protection for this specific issue you're encountering, so the users could not bypass the timer by exiting the app or even switching to another tab. Other browsers seem to act the same, as it does not depend on the app itself. I will investigate the problem further.

**Comment by shawon2901** [comment]
What Should Happen -
https://user-images.githubusercontent.com/40642163/186111642-26258725-95d3-47d4-a32b-8883f90333f8.mp4

What Happens -
https://user-images.githubusercontent.com/40642163/186112242-20f5c373-de46-475e-8ecb-492ee762c7a0.mp4

Its Not Website Problem It Happens In Any Website That Has A Countdown Timer..Either Timer Wont Move Or Move By 2 Second While I Had Waited 10 Second

**Comment by shawon2901** [comment]
Can Anyone Just Say That Its Noted And Will Be Fixed In Next Release Or Week

Asked Another Browser Dev To Fix Same Bug 4 Days Ago & He Released Fix Today..Its Really A Problem For People Dealing With Websites That Has Timers😪

![Screenshot_2022-09-02-00-23-43-211_ir ilmili telegraph](https://user-images.githubusercontent.com/40642163/187986156-afa060ab-4bf0-4367-934f-d05376f76660.jpg)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812781

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
