### ISSUE TITLE
[Bug]: "Jump back in" section displays tab groups but tabs tray no longer supports them

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#26227]
### Steps to reproduce

1. Trigger a search
2. Open a few search results in tabs
3. Go to home screen

### Expected behaviour

Jump back in should display last tab, but no tab group

### Actual behaviour

Jump back in shows tab group. Tapping on it opens the tabs tray which no longer supports groups and therefore doesn't highlight the group. It also may, depending on the previously selected tab, highlight an unrelated tab.

### Device name

Pixel 6a

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

### Additional information

Tab groups were removed as part of https://github.com/mozilla-mobile/fenix/issues/21898 in https://github.com/mozilla-mobile/fenix/commit/7e59a644d5890c1ce083b9435e27acd58d04fb1f. However, the "Jump back in" section wasn't addressed as part of this work, leaving this in an inconsistent state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21139)

**Comment by csadilek** [comment]
Reverting patch because it by mistake also removed history groups in "Recently Visited".

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 105.0a1 (2022-08-05) build.
After switching to the last tab opened from the search, that lastly viewed tab is displayed in the "Jump back in" section.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as fixed.
