### ISSUE TITLE
Fix breaking change from AC regarding `exitImmersiveModeIfNeeded`

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26236]
Based on the development from https://github.com/mozilla-mobile/android-components/pull/12560 AC will introduce a breaking change that needs to be handled in clients.
This ticket is to address the needed changes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21143)

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 105.0a1 2022-08-08 on several video sites such as https://www.youtube.com/, https://www.twitch.tv/, https://www.dailymotion.com/. I watched videos in full screen mode and pause them or wait until de video finished, in both cases the screen would lock after the screen timeout duration was met.
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
