### ISSUE TITLE
[Bug]tagline grammar: " parent's " should be " parents' "

### ISSUE THREAD

**Issue by fiver22** [mozilla-mobile/fenix#2623]
## Steps to reproduce
go to https://github.com/mozilla-mobile/fenix

### Expected behavior
should read " Fenix is not your parents' Android browser. "

### Actual behavior
reads " Fenix is not your parent's Android browser. "

### Device information
n/a

* Android device: n/a
* Fenix version: n/a

**Comment by vrudesai** [comment]
Hey fiver22, thanks so much for filing this issue! After careful consideration, we've decided to leave it as "parent's". This phrasing would also include individuals who may not have a pair of "parents" and those who do have a pair of parents.
