### ISSUE TITLE
[Bug]: Duplicate items in the Downloads list when a deleted file is saved again

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#26239]
### Steps to reproduce

1. Save a file (an image or pdf for example).
2. Go to the Files manager app and delete the file from the device.
3. Check that the file is no longer in the app's Downloads list.
4. Download again the same file.
5. Go to Downloads and check the list again.

### Expected behaviour

The saved file is displayed once, reflecting the app's files in the Files manager.

### Actual behaviour

The saved file is now displayed twice, though there's only one on the device.
Repeating these steps will create more duplicates every time.

### Device name

Pixel 2, Pixel 3

### Android version

Android 9, 11

### Firefox release type

Firefox

### Firefox version

103.1.0, 104.b2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21145)

**Comment by Alexandru2909** [comment]
This is a particular case we are not currently handling. What we do instead is [filter](https://github.com/mozilla-mobile/fenix/blob/602f55b5d29851cb58175a82b3f11a976fbb175b/app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt#L107) the files that do not exist when displaying the downloads list.

A solution that could work is searching for duplicates (downloads that differ only by the created time/id) of a download when it completes. This way we avoid storing multiple `DownloadState` instances for the same file.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 105.0a1 (2022-08-04T17:46:59.912999) build.
After deleting and downloading the same file, it is displayed only once in the Downloads list.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
