### ISSUE TITLE
[Bug]: tabs.create({}) behaviour different than on desktop

### ISSUE THREAD

**Issue by artisticfox8** [mozilla-mobile/fenix#26242]
### Steps to reproduce

1. Download tabs tabs tabs example addon from https://github.com/mdn/webextensions-examples/tree/master/tabs-tabs-tabs 
2. Modify the code in tabs.js from

```
  else if (e.target.id === "tabs-create") {
    browser.tabs.create({url: "https://developer.mozilla.org/en-US/Add-ons/WebExtensions"});
  }
```
to 
```
  else if (e.target.id === "tabs-create") {
    browser.tabs.create({});
  }
```

3.  Load the addon in about:debugging in Firefox Nightly on Windows 10
4. Open the addon popup and click create a tab
5. The  `browser.tabs.create({});` line opens the same tab the ctrl t does, the new tab page
6. Now load the addon in Firefox Nightly on Android
7.  Open the addon popup and click create a tab
8. Here is the bug:  `browser.tabs.create({});` line opens about:blank

In my opinion, Firefox Android should be consistent with the desktop Firefox. 
Desktop Firefox adheres to the spec: 

> url string. The URL to navigate the tab to initially. Defaults to the New Tab Page.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

### Expected behaviour

The  `browser.tabs.create({});` line opens the same tab the ctrl t does, the new tab page

### Actual behaviour

Here is the bug:  `browser.tabs.create({});` line opens about:blank

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

105

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21148)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1782389

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
