### ISSUE TITLE
Opening links in a new tab breaks new and original tab

### ISSUE THREAD

**Issue by patrickSpaceSurfer** [mozilla-mobile/fenix#26241]
### Steps to reproduce

1. Open a tab for https://www.theguardian.com/
2. Once the page has loaded, long press on any article (any link on the same website) and open the link a new new tab

The new tab will just remain blank. The old tab will not allow any new links to be opened (either in the same tab or in a new tab). However, the old tab may eventually recover or just become very slow at responding to opening links. The old tab will work fine in terms of reading the web page, only actions on the web page stop working.

This problem happens the vast majority of the time and has been happening for months. Tested on:
Zenfone 8, with latest firefox. I even cleared all data and reinstalled, still happens. It also happens on the latest firefox beta
Oneplus 3 (android 9?) with the latest firefox. I used this device for years with firefox and it started happening on this device a pretty long time ago.

It happens on Wifi networks and/or mobile data.

### Expected behaviour

I can browse https://www.theguardian.com/ in multiple tabs

### Actual behaviour

I can't browse https://www.theguardian.com/ in multiple tabs

### Device name

ZenFone 8

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

103.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21147)

**Comment by lm1baker** [comment]
I can also reproduce this, although switching between tabs a few times sometimes restores both tabs to working order.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813807

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
