### ISSUE TITLE
[Bug] Fingerprinting and cryptomining preferences reset on app update

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/fenix#2624]
## Steps to reproduce
1) Go to about:config.
2) Search for trackingprotection.
3) Toggle the values "privacy.trackingprotection.cryptomining.enabled" and "privacy.trackingprotection.fingerprinting.enabled" to true.
4) Update Fenix.

### Expected behavior
Cryptomining and fingerprinting protection settings persist across upgrade.

### Actual behavior
Both values are reset to false.

### Device information
* Android device: Pixel 3 XL with May 2019 build of Pie.
* Fenix version: 1.0.1920

**Comment by mcl21014** [comment]
And also the preference "privacy.trackingprotection.enabled" is reset to false even though tracking protection is set to enabled. I checked other about:config entries and they don't appear to reset like this.

**Comment by vesta0** [comment]
About:config is not supported in Fenix yet.

**Comment by kbrosnan** [comment]
This is not a bug that the release population can hit. `about:config` is not accessible by builds that we ship to the Play store.
