### ISSUE TITLE
Investigate using `layer2` as ThumbnailCard background color

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#26240]
This could also be made into a follow investigation issue so we aren't blocking this from landing, but I mostly want to verify what we are doing in the xml currently based on your current findings, and whether or not if we used layer2 if that would affect the other component usages of `ThumbnailCard` such as in `RecentBookmarks` - this might involve a UX discussion and will need to be tested in both light and dark theme.

The main concern would be that the current usage of the default (photonGrey20) card background color `ThumbnailCard` outside of the tab trays could appear wrong for the various themes because it is photonGrey20 for both light/dark, and this might be okay, but there is an off chance that this should also be updated for the other components and we just simply haven't seen this photonGrey20 background being an issue because we don't often see the favicon between the light/dark theme.

_Originally posted by @gabrielluong in https://github.com/mozilla-mobile/fenix/pull/26222#discussion_r932408748_
After changing the background color used in `ThumbnailCard` to a parameter with the default `photonGrey20` in https://github.com/mozilla-mobile/fenix/issues/26221, we should check if using `layer2` would affect other components.

The components that are currently using `ThumbnailCard` are `RecentTab` and `RecentSyncedTab`:

| Current dark theme | Current light theme |
| ------------------- | -------------------- |
| ![dark](https://user-images.githubusercontent.com/35462038/181753793-611950ad-d6c7-4dcf-a6f3-d72f58ac3a80.png) | ![light](https://user-images.githubusercontent.com/35462038/181753809-fe005f86-e081-476a-86fb-c96110bb9f7b.png) |
| `layer2` dark theme | `layer2` light theme |
| ------------------- | --------------------- |
| ![dark2](https://user-images.githubusercontent.com/35462038/181754232-bd80ae01-a471-47c1-a8ae-d8ba348ccaaa.png) | ![light2](https://user-images.githubusercontent.com/35462038/181755410-d158db49-7c92-4501-8525-ca90e8cd4911.png) |

Although this is not a common case (to see the favicon in place of recent tabs thumbnail), we should check if this is an update we want or if we should respect the designs used in https://github.com/mozilla-mobile/fenix/pull/21581. Tagging UX for that.

cc
@gabrielluong 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21146)

**Comment by gabrielluong** [comment]
Hm... I guess it doesn't look quite right for both cases. I will ping @topotropic.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810912

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
