### ISSUE TITLE
Ask to save passwords on all apps

### ISSUE THREAD

**Issue by abda11ah** [mozilla-mobile/fenix#26246]
Hi,
From Firefox beta 104.0b1 the firefox password manager can now autofill forms inside all apps (Android autofill API) but can not currently ask to save a new ID/password.

It would be great to see this feature implemented, just like Google smartlock does :

![alt text](https://i.aveshack.com/02b08834a233cbda.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21150)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/21379
