### ISSUE TITLE
Refresh Fenix - reset add-ons and settings

### ISSUE THREAD

**Issue by Djfe** [mozilla-mobile/fenix#26248]
### What is the user problem or growth opportunity you want to see solved?
It would be nice if there was a way to refresh Fenix like it's possible on desktop (reset everything except open tabs, bookmarks, passwords and collections or something like that)

[support.mozilla.org](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings)

### How do you know that this problem exists today? Why is this important?
I tried searching for this feature, it doesn't exist, yet.
I tried looking through issues on github but searching for refresh (and related search terms) I get hundreds of issues.
Pls point me to an existing issue, if this has been reported in the past.

Fenix has been crashing regularly for me since february. I would like to try resetting everything.
Firefox Sync and deleting appdata is not an option since it doesn't sync collections.

### Who will benefit from it?
People like me who have been using Firefox on Android since before Fenix.
I looked at the data. There is still lots of data from the old browser which hasn't been deleted on migration. (like open tabs in a json file)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21151)

**Comment by TrianguloY** [comment]
Open android settings and delete the app storage (the exact steps vary between android versions). The app should behave as a fresh install.
Note that if you log into Firefox sync data may reappear.

**Comment by Djfe** [comment]
This is a feature request for a feature present on Firefox Desktop to be implemented on Fenix.
The topmost button on "about:support" on Firefox Desktop "Refresh Firefox…".

Thanks for trying to help, but as I said:
> Firefox Sync and deleting appdata is not an option since it doesn't sync collections.

Regards
Djfe

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813808

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
