### ISSUE TITLE
Refactor the `WallpaperManager` as a `WallpaperUseCase`.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26245]
`WallpaperUseCase` seems to fit well with existing components in the app, as well as communicating more clearly what the intent is. A client of `WallpaperUseCase` will generally be a user-facing feature that needs to use wallpapers. This can be an opportunity to streamline the public API as well. Here are some key parts:

- fetch wallpaper metadata
- download a full-size wallpaper image
- download wallpaper thumbnails
- load the currently set wallpaper (or a wallpaper, more generally. may depend on decisions made around caching the current wallpaper in the usecase)
- load a wallpaper thumbnail

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21149)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 105.0a1 from 08/15 with Google Pixel 6 (Android 12). The wallpaper feature works as expected, no issues were encountered.
