### ISSUE TITLE
Support sorting of bookmarks

### ISSUE THREAD

**Issue by 12sunflowers** [mozilla-mobile/fenix#26257]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
when is backwards sorting for bookmarks will be relesed? last at top, old at down.
### How do you know that this problem exists today? Why is this important?
i think that to be comfortable make default sorting of bookmarks make backward oposite now sorting, i mean, at top of boolmarks list - recently new added bookmarks and at end is older booklmarks
### Who will benefit from it?
all users of Firefox

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21157)

**Comment by DavidJCobb** [comment]
> **Who will benefit from it?**
> 
> all users of Firefox

Not really. New content at the top isn't intuitive to everyone; in fact, as far as I know, it's the exact opposite of the order used on pretty much every mainstream desktop browser, if not every mainstream mobile browser as well. The last time Mozilla broke this convention, it was with tabs. Users hated it, there was no option to turn it off, and it took Mozilla forever to revert it.

If this must exist, it should be as an option. Unfortunately, the Fenix team don't seem keen on adding very many of those.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812404

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
