### ISSUE TITLE
[Bug]: synced tab's title not show completely when switching tab from private to synced

### ISSUE THREAD

**Issue by jackyzy823** [mozilla-mobile/fenix#26253]
### Steps to reproduce

1. Sign in into your fxa account.
2. Switch To Private Tab Tray
3. Then switch to Synced Tab Tray
4. Click "Sync" button

### Expected behaviour

Titles are displayed completely and correctly.

### Actual behaviour

Only emojis will show. the other text in title is not showed.
![Screenshot_20220730-004105__01__01](https://user-images.githubusercontent.com/2900871/181870571-d1122e44-5e15-4bdc-bed6-fc9d5cb198a2.jpg)

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

103.0.0-beta.5

### Additional information

To prove my synced tabs have titles.
Here's the screenshot that switch from normal tab to synced tab. It displays correctly and completely.
![Screenshot_20220730-105322__01__01](https://user-images.githubusercontent.com/2900871/181870597-9d2f00d7-71a9-47fd-ac0f-20d7a9882af8.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21154)

**Comment by jackyzy823** [comment]
Update: Dark Theme do not have this bug. Only happens on LightTheme.

**Comment by jackyzy823** [comment]
Ok , I might figure out why.

The background of SyncedTabsList  have only two options (maybe because there's no Modifier of background here or maybe based on the logic of getTheme. I'm not familiar with Compose stuff)
https://github.com/mozilla-mobile/fenix/blob/b6f140a76f00fa1b1cac657bca3fc67e4cade934/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/SyncedTabsPageViewHolder.kt#L34-L40
the text of title have three options Light/Dark/Private. may be based on the logic of :https://github.com/mozilla-mobile/fenix/blob/06488cdabeaea614df7b910f1cded00d529575ea/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt#L40-L47.

So It would be invisible if text is Private (textPrimary = LightGrey05 `0xFFFBFBFE`  , `#FBFBFE`  )  https://github.com/mozilla-mobile/fenix/blob/06488cdabeaea614df7b910f1cded00d529575ea/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt#L108 and backgroud is Light (PhotonColors.LightGrey10 `0xFFF9F9FB` , `#F9F9FB`)
https://github.com/mozilla-mobile/fenix/blob/06488cdabeaea614df7b910f1cded00d529575ea/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt#L216


So 1) either make background  have three options ( which will make user **confused**  why synced tabs are displayed in Purple background (Private Mode) ) , or 2) make the text in Private do not conflict with background in Light.

Could anyone helps on this issue ? @gabrielluong @Alexandru2909  

Thanks.

**Comment by gabrielluong** [comment]
I believe @MozillaNoah is working on a fix for the private theme colors showing up in the tabs tray in https://github.com/mozilla-mobile/fenix/issues/22558. Basically, the tabs tray only shows the dark/light theme, but in the synced tabs we have started to use the design system color tokens which will show the private theme colors when the design of the tabs tray wasn't suppose to.

**Comment by MozillaNoah** [comment]
hey, @jackyzy823, thanks for filing this issue! As @gabrielluong pointed out, I'm actually in the middle of working on fix for this right now! I'm going to go ahead and close this, but a fix will be out soon!
