### ISSUE TITLE
Removing browsing-data, when closing firefox via the "open-apps"-overview

### ISSUE THREAD

**Issue by c-mahn** [mozilla-mobile/fenix#26267]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

When I'm on my phone and I want to close multiple apps, I normally close them via the "open-apps"-overview, because I can just swipe the unused apps away. But for firefox I always have to close it via the dropdown-menu in the top right corner or my browsing-data won't be deleted.

### How do you know that this problem exists today? Why is this important?

From a privacy perspective I want each browsing session to be on their own and not be linked to each other. No suggested pages, no browsing-history, no saved cookies, ...
I just want everything from the "delete, when I close the browser"-section to also occur, when I close the app via the "open-apps"-overview.

### Who will benefit from it?

Everyone, who want's more privacy and convenience.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21160)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813810

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
