### ISSUE TITLE
Status bar color is not updated for PWAs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26269]
STRs:
- Access https://daleharvey.github.io/testapp/
- Press `Install` in the 3dot menu
- Open the newly installed PWA from device's homescreen

Expected result
- The status bar has a pinkish color (see result on Chome)

Actual result
- The status bar color is not updated

Details
- Happens on both the current 105 Nightly and 103 Release
- Tested on a OnePlus 7 running Android 11
- Might be device specific

Video showing the UX on Fenix Nightly - 105 / Fenix Release 103 / Chrome Release 103:

https://user-images.githubusercontent.com/11428869/182168099-b9334bde-5f4a-4279-87f9-f2e36c89c468.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21162)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807410

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
