### ISSUE TITLE
FNX3-16462 ⁃ [Bug] When selecting a tab to save to collection, Fenix scrolls to bottom of tab list instead of focusing on selected tab

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2627]
## Steps to reproduce
1. Open many tabs 
1. Long press to select a tab to save to collection near the top of the list

### Expected behavior
Selected tab should be front and centre 

### Actual behavior
Fenix scrolls to the bottom, leaving the user confused and bewildered as to what's happened. 

### Device information
* Android device: LG G6, Android 8
* Fenix version: 1.0.1920

**Comment by yoasif** [comment]
Feels like a dupe of https://github.com/mozilla-mobile/fenix/issues/2633

**Comment by pwd-github** [comment]
I honestly wouldn't know, it's possible. But this was about the tab list, that seems to be about the behaviour within specific tabs.

**Comment by yoasif** [comment]
Then I guess I don't understand the issue (what happens/actual behavior). This doesn't happen for me.

**Comment by pwd-github** [comment]
Open 20 tabs, attempt to select the top tab in the tab list, Fenix scrolls to the bottom of the tab list in selection view.

**Comment by ekager** [comment]
Hi @pwd-github thanks for filing! Is this still an issue for you?

**Comment by pwd-github** [comment]
@ekager very much so.

**Comment by ekager** [comment]
Could you possibly take a screenrecord video? I'm not sure I understand exactly what's going on.

**Comment by pwd-github** [comment]
@ekager sure thing: https://send.firefox.com/download/6511c243418bb25b/#1abGKtr7TGu2naXZRWxOAg

**Comment by ekager** [comment]
Ah okay! I understand now! Thanks for the video :) Updating the issue description

**Comment by pwd-github** [comment]
No problem, sorry I wasn't clearer.

**Comment by vesta0** [comment]
Clarifying the ask from UX: where should the scroll position be when selecting a tab to be added to a collection?

**Comment by vesta0** [comment]
Looks like UX already provided feedback/directions in #3161 

We will fix this issue as per #3161
