### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by 772602825** [mozilla-mobile/fenix#26276]
The shortcuts on the homepage of firefox Android version are inconvenient to use. There are only two lines of icons. If you want to fix too many website icons on the homepage, you can only swipe right, which is very inconvenient. And the space at the bottom of the home page is not well utilized. The homepage URL icon needs to place the desired URL instead of the commonly used URL, which can be like other browsers.
![IMG_20220802_155907_1](https://user-images.githubusercontent.com/103982328/182323357-d315be9a-d858-4081-b3e4-2b90df8c83bd.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21176)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/16414
