### ISSUE TITLE
FNX3-16463 ⁃ Offer to remove tabs that are added to a collection from the tab strip

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2628]
### Why/User Benefit/User Problem
Given that there's no need to have duplicate tabs, as a user, I would expect Fenix to offer to remove tabs from the tab list when I add them to a collection. 

### What/Requirements
Upon adding tabs to a collection, show a dialog that offers to remove the tabs from the tab list as they are now safe within the new collection

### Acceptance Criteria (how do I know when I’m done?)
Coded the mechanism to remove tabs upon user consent. 
Created dialog to get user consent. 
Settled upon the optimal text.

**Comment by yoasif** [comment]
The only issue I see with this is that the current page in two tabs may be the same, but the tab stack (history) in each tab may differ. That may make the tabs not the "same". 

It would be bad to lose the tab stack if the tabs aren't exactly the same, imo.

**Comment by pwd-github** [comment]
You could inform users of that with the dialog.

Text: _Remove tabs from tab list? Beware that you will lose the tab history if you click yes._

**Comment by AmyYLee** [comment]
The expected behavior here is that once tabs are saved to a collection that it's removed from the "open tabs" section @sblatz

**Comment by NotWoods** [comment]
Fixed in #3723
