### ISSUE TITLE
Remove search term tab groups setting and metrics

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#26289]
Follow-up from https://github.com/mozilla-mobile/fenix/pull/26003#issuecomment-1185724932

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21182)

**Comment by Dakkaron** [comment]
This broke tab reordering.

**Comment by MozillaNoah** [comment]
> This broke tab reordering.

Hi @Dakkaron, this issue only removed the telemetry and the option in Settings for search term tab groups; it didn't touch any logic with tab re-ordering. We've been doing some work in the Tabs Tray recently though, so if you make a new issue to track this bug, it will have better visibility and someone will start investigating it.

**Comment by Dakkaron** [comment]
@MozillaNoah Hi Noah,
I reset the app's data and cache and now it's working again. Could it be that the "tab grouping is enabled" setting could have persisted and thus the tab ordering was still disabled?

**Comment by Dakkaron** [comment]
Thanks a lot!

Do you know if there are any plans to push tab ordering to the regular Firefox version? It's the biggest missing feature for me.

**Comment by MozillaNoah** [comment]
> Thanks a lot!
> 
> Do you know if there are any plans to push tab ordering to the regular Firefox version? It's the biggest missing feature for me.

@athomasmoz or @kbrosnan might have some more context as far as business priority. With the Tabs Tray in the process of being rewritten to the new UI framework, Compose, I think re-ordering won't be live until at least the Tabs Tray is 100% converted. To that end, I just added an issue to specifically track rewriting re-ordering into Compose.

- https://github.com/mozilla-mobile/fenix/issues/26476

**Comment by Dakkaron** [comment]
Thanks for opening that issue! Manual tab reordering is essential for any use case where comparing content in different tabs is necessary, e.g. comparing different products. This kind of use case is currently hardly possible in Firefox on Android.
