### ISSUE TITLE
Ensure addresses aren't synced between desktop and Fenix

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#26287]
We want to QA verify that addresses aren't currently syncing between desktop and Fenix. Specifically, if I added an address in either desktop or Fenix, neither of those should sync to the other device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21181)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nighty 105.0a1 from 08/02 and Beta 104.0b3 with Xiaomi 12 Pro (Android 12) and Lenovo Yoga Tab 11 (Android 11). The saved addresses are not synced between Fenix and Desktop, or other devices.
