### ISSUE TITLE
Fix or adjust release branch expression in kind.yml

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#26293]
https://github.com/mozilla-mobile/fenix/blob/cedb040e8400211c983d7e3bbff3cb3a391f9c9f/taskcluster/ci/ui-test/kind.yml#L107

Shouldn't this be `^releases[/_].+$` ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21183)

**Comment by csadilek** [comment]
@AaronMT As we're moving tickets to Bugzilla, I am curious if you want to keep this?
