### ISSUE TITLE
[Bug] can't share images to my texting apps

### ISSUE THREAD

**Issue by taracdia** [mozilla-mobile/fenix#26298]
I've clicked share image on websites like Tumblr and when it offers a texting app to share it with i click it and it dismisses the share overlay instead of opening the app i requested. If i try again it tells me that the app in question has stopped working. I've had this happen with Google messages, messages plus, and textra

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21185)

**Comment by kbrosnan** [comment]
Pretty sure this is us including the URL https://github.com/mozilla-mobile/fenix/issues/17910

**Comment by taracdia** [comment]
@kbrosnan I'm a bit confused by your labeling. This has nothing to do with including the url. The problem is that the feature doesn't work

**Comment by kbrosnan** [comment]
The other apps expect just an image, we send more than that which some apps cannot handle.
