### ISSUE TITLE
Consider using bottom sheet rather than dialog for contextual menus

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2630]
### Why/User Benefit/User Problem
The current dialogs are kinda ugly. Though they could just not be styled. But as they grow and add more options, they'll become inconsistent in terms of size. As a user, having items consistently placed is a huge bonus and bottom sheets enable that.

https://www.material.io/design/components/sheets-bottom.html

### Acceptance Criteria (how do I know when I’m done?)
UX approval
Contextual page menus have been migrated to use bottom sheets.

**Comment by pwd-github** [comment]
Just to clarify, I'm referring to the link and image contextual menus.  Text has a different UX design.

**Comment by yoasif** [comment]
Could you provide an example of which menus are ugly? I may be dumb, but I am just not seeing it. :)

**Comment by pwd-github** [comment]
> Could you provide an example of which menus are ugly? I may be dumb, but I am just not seeing it. :)

Sure thing.

![Screenshot_2019-05-18-16-23-45](https://user-images.githubusercontent.com/203217/57975435-04577400-79c1-11e9-8f7a-b485065ce84c.png)

**Comment by pwd-github** [comment]
The grey is very dreary. Granted, I'm on dark mode, but nonetheless.

**Comment by yoasif** [comment]
Looks cool, I wonder how UX will react. :smile:

**Comment by lime124** [comment]
@topotropic @AmyYLee can you provide your thoughts please? thanks!

**Comment by topotropic** [comment]
We have quite a few things coming from the bottom (quick action bar, site info panel) so I'd be hesitant to add the contextual menu there as well. We also don't anticipate to add more items to the menu, so I'd say let's revisit once we want to add more menu items and close for now.

**Comment by pwd-github** [comment]
Hi @topotronic 

First of all, you're definitely adding more stuff, basic things are missing from the context menus still. Not to mention that anything that extensions add. 

Secondly, with the bottom navigation and being designed for one handed use, surely it doesn't make sense to then have all of the contextual menus out of reach. 

Thirdly, bottom sheets are much nicer than what's being used.
