### ISSUE TITLE
[Bug]: Improper grey highlight displayed on certain strings when opening the Add address form 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26302]
### Steps to reproduce

1. Go to Settings -> Autofill and tap on the (+) "Add address" button.
2. Observe the First Name, Middle Name and Last Name strings.

### Expected behaviour

The Add address field is displayed without visual issues.

### Actual behaviour

An improper grey highlight displayed on the last letter "e" in the First Name, Middle Name and Last Name strings when opening the Add address form. The highlight disappears along with the scroll bar displayed on the right side of the screen.
 

### Device name

Xiaomi 12 Pro

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 105.0a1 from 08/02

### Additional information
This also occurs on the edit Credit Card view.
Could be also reproduced with: Lenovo Yoga Tab 11 (Android 11), Google Pixel 6 (Android 12), Samsung Galaxy note 10 (Android 10).
Could not be reproduced with OPPO A15s (Android 10). 
The issue does not occur on Beta 104.0b3.

https://user-images.githubusercontent.com/89388888/182615494-f81eebcb-3bcf-40be-a224-41f2dc82b57b.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21188)

**Comment by Alexandru2909** [comment]
This seems to occur after the Metropolis font removal, only for `TextView`s with `height` less or equal to `16dp`. Layouts containing such views are login, address and credit card add/editor screens. Changing their `layout_height` to `wrap_content` will fix the issue.

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 105.0a1 from 08/08 with Lenovo Yoga Tab 11 (Android 11).
