### ISSUE TITLE
4:3 YouTube videos not correctly displayed

### ISSUE THREAD

**Issue by Joshua2005777** [mozilla-mobile/fenix#26306]
When you rotate 4:3 youtube videos to full screen in the Android Beta browser, almost half of the screen is cut off at the bottom.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21190)

**Comment by kbrosnan** [comment]
Please provide an example video.

**Comment by ris58h** [comment]
I have the same issue with Samsung s10e.
![Screenshot_20220812-104229_Firefox](https://user-images.githubusercontent.com/511242/184281175-42d40df9-8d8e-4f01-a242-77415a6019fa.jpg)
https://m.youtube.com/watch?v=fuDmJUXOmdU

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813812

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
