### ISSUE TITLE
[Bug]: Search Engine Cover.info (de) can't be added

### ISSUE THREAD

**Issue by blueicehaller** [mozilla-mobile/fenix#26305]
### Steps to reproduce

https://cover.info/de/search/?q=%s

### Expected behaviour

The Search Engine has been added.

### Actual behaviour

It shows an Message that it can't connect.

### Device name

Samsung Galaxy S5 LTE+

### Android version

Android 6.0.1

### Firefox release type

Firefox Beta

### Firefox version

104.0b2

### Additional information

104.0b2 (Build #2015894913), c7a2ab0d0+
AC: 104.0.1, 7a313eb579
GV: 104.0-20220728185815
AS: 93.7.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21189)

**Comment by blueicehaller** [comment]
![Screenshot_2022-08-03-17-41-28](https://user-images.githubusercontent.com/24243683/182654661-5f9a9f76-24c9-48e5-a365-927267f9b9f8.png)

**Comment by kbrosnan** [comment]
This looks like a website bug the page responds with a http 301 error for https://cover.info/de/search/?q=%s with no forwarding location. It seems that removing `search/` allows searching to function.

Using https://cover.info/de/?q=%s works.

**Comment by blueicehaller** [comment]
Steps to reproduce:
1. Open https://cover.info/
2. In the top right field "Suche" enter any term like Test
3. Result: https://cover.info/de/search/?q=Test

**Comment by blueicehaller** [comment]
I have the issue with Firefox Beta (109.0b6), that it redirects to the page instead that it searches.
Follow the steps from [Search with a different search engine - Searching with Firefox for Android | Firefox for Android Help](https://support.mozilla.org/en-US/kb/searching-firefox-android#w_search-with-a-different-search-engine)
1. Begin entering `Test` as search term in the address bar.
2. Tap `Search engine` and tap a different search engine. In my case `Cover.info (de)`
3. Complete your search and tap Go.
4. It redirects to https://cover.info instead of https://cover.info/de/search/?q=Test
