### ISSUE TITLE
Cannot enable push notification for reddit or tinder

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#26307]
### Steps to reproduce

can please someone explain me why with both stable /beta nighlty fenix I'm not able to enable push notication for both tinder and reddit ????
other websites like webtelegram , Twitter or YouTube hopefully work as expected .
since I ve got root i look into push.sqlite file in profile folder and under push record there is no entry for reddit for example .

### Expected behaviour

push notification are supposed to work for whatever websites not just some !

### Actual behaviour

push notification for both tinder and reddit are not working 

### Device name

pixel 6

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

105

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21191)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813813

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
