### ISSUE TITLE
SyncedHistory cleaning up

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26312]
During the development of [synced history](https://mozilla-hub.atlassian.net/browse/FNXV2-19087) a few unused things came up, like `HistoryFragmentState.items` or `History.position`. Removing those would make code more straightforward and easy to read.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21194)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813814

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
