### ISSUE TITLE
The button of a messaging feature experiment is using the wrong string

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#26318]
**[Affected Versions]:**
- Firefox Release 103.2.0 (Build #2015895963), e0d3c03af+, AC: 103.0.10, ab756c4b5 GV: 103.0.2-20220802163236, AS: 93.5.1
- Firefox Release 103.1.0 (Build #2015892987), 346356a60+, AC: 103.0.9, 8031ffeaf2 GV: 103.0-20220718155818, AS: 93.5.0
- Firefox Beta 104.0b3 (Build #2015895515), 6acedcdd1+, AC: 104.0.2, 53097Gdc479 GV: 104.0-20220731190208, AS: 93.7.1
- Firefox Nightly 105.0a1 (Build #2015895987), acf9206fe+, AC: 105.0.20220801222259, 2d1f4fd1e1 GV: 105.0a1-20220801153341, AS: 93.8.0

**[Note]:**
- The issue is no longer reproducible with Firefox Nightly 105.0a1 (Build #2015896139), dd563b19f+, AC: 105.0.20220803135114, 97f0f24018 GV: 105.0a1-20220803094413, AS: 93.8.0

**[Affected Platforms]:**
- Android 9 - Samsung Galaxy S8
- Android 11 - Motorola One Vision

**[Prerequisites]:**
- Have a Firefox build set up to point to Stage:
     - Have the following lines added to local.properties:
     `nimbus.remote-settings.url = https://settings.stage.mozaws.net//`
     `debuggable = true`
     - A new “.nimbus” file (in the same location as local.properties) containing the following line:
     `https://settings.stage.mozaws.net`
- Have an experiment with the same configuration as [Viewpoint Survey (2022 July, Android)](https://experimenter.services.mozilla.com/nimbus/viewpoint-survey-2022-july-android) set up to enroll you automatically.

**[Steps to reproduce]:**
1. Open Firefox.
2. Close Firefox.
3. Open Firefox again.
4. Tap “Start browsing”.
5. Observe the button of the message displayed.

**[Expected result]:**
- The button displayed reads “Take survey”.

**[Actual result]:**
- The button displayed reads “Set as default browser”.

**[Notes]:**
- The button opens the Survey set up by the experiment.
- The issue is not reproducible on  Firefox Nightly 102.0a1 (Build #2015879483), 98455c01e+, AC: 102.0.20220508143159, bd 9d194237 GV: 102.0a1-20220508065845, AS: 91.1.2.
- This issue is also reproducible with the Production experiment if you use the secret menu to enroll in the experiment between steps 3 and 4.
- Attached are a recording and screenshot of the issue.
![final gif](https://user-images.githubusercontent.com/53752296/182838012-6b365108-4371-4993-ae65-de44507acfb1.gif) ![screenshot 344](https://user-images.githubusercontent.com/53752296/182836003-5cbe99fc-c4cf-458d-8f55-6121f114d37a.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21198)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813815

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
