### ISSUE TITLE
Refactor the search widget to use the A-C common behaviour

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/fenix#26329]
This task should contain the implementation of search widget the Fenix part. I moved and refactored  the search widget from Fenix in AC . 
This has appear based on this https://github.com/mozilla-mobile/focus-android/issues/7249#issuecomment-1195533956
This is the task from AC https://github.com/mozilla-mobile/android-components/issues/12565 .
This is the task from Focus https://github.com/mozilla-mobile/focus-android/issues/7249

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21203)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813191

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by delia-pop** [comment]
Removing the QA needed label and adding QA not Needed here instead.

**Comment by iorgamgabriel** [comment]
https://github.com/mozilla-mobile/fenix/pull/26331#issuecomment-1219710654 based on this comment this is not needed any more.
