### ISSUE TITLE
[Bug] Try Again hidden by address bar on Address Not Found page

### ISSUE THREAD

**Issue by galexite** [mozilla-mobile/fenix#2632]
## Steps to reproduce
1. Turn off Wi-Fi.
1. Try to access a webpage.

### Expected behavior
The Address Not Found page shows a visible Try Again button on a tablet.

### Actual behavior
As in this screenshot, the Try Again button is mostly obscured by the address bar, despite there being enough space available on the screen.

![Screenshot](https://user-images.githubusercontent.com/6300838/57973961-956e2100-79a8-11e9-851f-df16b3f94257.jpg)UNITO-UNDERSCORE!20190518-200206!

### Device information
* Android device: ASUS ZenPad S 8.0 (Z580C), Android 6.0
* Fenix version: 1.0.1920

**Comment by bifleming** [comment]
Fixed by static bar
