### ISSUE TITLE
FNX3-16469 ⁃ [Bug] If page is zoomed in, reader view is also zoomed in and cannot be zoomed out

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#2633]
Also reported on mailing list: https://groups.google.com/forum/#!msg/fenix-nightly/v_wb7P-QoiI/tHk1HaJrBQAJ

## Steps to reproduce
1. Navigate to a page that supports reader view like: https://www.foxnews.com/us/new-hampshire-cafeteria-student-free-meal-job-offer.amp
1. pinch to zoom in
1. tap Read in QAB

### Expected behavior
Reader view appears, zoomed at 100%

### Actual behavior
Reader view is zoomed in. User cannot zoom out using pinch. 

### Device information
* Android device: Pixel 2
* Fenix version: latest from play store

**Comment by csadilek** [comment]
This will be fixed by https://github.com/mozilla-mobile/android-components/issues/2985 which should land next week.

**Comment by cpeterso** [comment]
> This will be fixed by mozilla-mobile/android-components#2985 which should land next week.

@csadilek, is this bug fixed? You said mozilla-mobile/android-components#2985 would be fixed back in May, but it is still open.

Is there more work needed from GV? Can we remove the `needs:gv` and `waiting` labels?

**Comment by kbrosnan** [comment]
This is still an issue for Fenix.

Using a Pixel 3 - 190813 06:05 build 12250615 
a-c 8.0
gv 69.0

**Comment by csadilek** [comment]
@cpeterso no, this isn't fixed, as we need https://bugzilla.mozilla.org/show_bug.cgi?id=1554302 in GV to land reader view as an extension page solving this and related problems (see https://github.com/mozilla-mobile/android-components/issues/2985).

**Comment by yoasif** [comment]
Noticed very quickly by a new user on Fenix: https://www.reddit.com/r/firefox/comments/eqsxt8/do_you_tell_your_friends_about_firefox_what_do/fezy8av/

Given that reader mode is a core feature, it'd be nice to have the AC bug fixed sooner rather than later. :smile:

**Comment by sblatz** [comment]
This will be fixed by the overarching issue of mozilla-mobile/android-components#2985 which Christian linked above which takes quite a bit of work. Putting this back in "waiting" for now so that can be scheduled as a larger block of work :)

**Comment by AndiAJ** [comment]
Hi, **still reproducible** on my **Fenix debug build  from master** **`Build #21000923
39.0.20200408130125, 356eb1e87 GV: 77.0a1-20200407093520 AS: 0.55.0`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200409-094859](https://user-images.githubusercontent.com/51314259/78866563-47db2680-7a48-11ea-9924-c3e8dfd0181f.gif)

**I'll remove the QA needed label.**

**Comment by csadilek** [comment]
This is fixed now as of Nightly 200506 06:01. @AndiAJ can you take another look to verify, please?

**Comment by AndiAJ** [comment]
Hi @csadilek , **verified as fixed** on **`Nightly Build 200506 from 5/6`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200506-175903](https://user-images.githubusercontent.com/51314259/81193497-2415ec80-8fc4-11ea-92f8-9d304b5c17fb.gif)
