### ISSUE TITLE
Icons created by PWA are not properly shaped

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26338]
### Steps to reproduce

Open dreamdth.com/community
Install it as pwa
Observe the icon , there is white border to fill the icon shape

Whereas pwa icon created by brave are shaped properly

### Expected behaviour

Icon should be shaped properly

### Actual behaviour

Icons not shaped or maybe firefox picking up low resolution favicon and launcher is filling with white space 

### Device name

rog3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Additional information

Check the pwa icon of flipkart and dreamdth site

![Screenshot_20220805-234414768 (1)](https://user-images.githubusercontent.com/58127841/183137170-3a3d3fa9-5539-4705-a2bf-c8f75a3e7ad9.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21208)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807438

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
