### ISSUE TITLE
[Bug]: Higher refreshrates does not work on Firefox Nightly

### ISSUE THREAD

**Issue by blennster** [mozilla-mobile/fenix#26337]
### Steps to reproduce

Navigate to any website and check reported refresh rate from system. The refresh rate reporting can be found in android developer settings. [Here](https://thenextweb.com/news/how-to-check-any-apps-refresh-rate-on-android) is a guide.

### Expected behaviour

Refresh rate should be higher than 60.

### Actual behaviour

Locked 60 Hz when scrolling in websites but not when entering settings menu.

### Device name

One Plus 8

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 Build #2015896299

### Device logs

N/A

### Additional information

Firefox stable and Beta works fine with the same device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21207)

**Comment by amocirean** [comment]
Hello @blennster, thank you for submitting the issue.
I was not able to reproduce it on Nightly 107.0a1 nor Release 105.2.0. The refresh rate on the Pixel 6 I've used for testing is 90hz. This applies while using the Firefox app too.
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

Devices Used: Google Pixel 6 (Android 13).

**Comment by blennster** [comment]
Hi!

Yes this is stil present in nightly 107.0a1. This issue is not present in stable 105.2.0. Have you tried navigating to a website? Because the only time it is 60Hz is when a website is rendered. The startpage, tab overview and settings are all 90Hz.

Still using the same device and android version.

**Comment by BitGrub** [comment]
Issue still exists in Nightly, now present in Beta as well

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811569

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
