### ISSUE TITLE
Save and Update credit card prompts are displayed floating when there is a expended menu on the payment webpage

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26333]
### Steps to reproduce

1. Have a credit card saved in Fenix.
2. Go to https://checkout.stripe.dev/ .
3. Fill in the form with the data of the saved credit card or enter a new card data.
4. Make sure the "TEST CARDS" menu from on the right bottom side on the page is expended.
5.Tap on "Pay" and observe the prompt.

### Expected behaviour

The  "Update card expiration date?" /   "Securely save this card?" prompt is displayed on the bottom on the page.

### Actual behaviour

The  "Update card expiration date?" /   "Securely save this card?" prompt is displayed floating in the middle of the screen since the page specific menu was expended.

### Device name

Lenovo Yoga Tab 11 

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

Beta 104.0b4

### Additional information

Note that the issue cannot be reproduced on a different website with real credit card, however it is possible that such a rreal website with an expandable build in menu exist.

https://user-images.githubusercontent.com/89388888/183100157-c8bd8174-56c3-49e5-bf64-cee341d170e8.mp4

https://user-images.githubusercontent.com/89388888/183100375-89174bf9-2312-4070-b524-805ecc601d42.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21204)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813816

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
