### ISSUE TITLE
Enable Sponsored Shortcuts by default

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#26335]
Jira ticket: https://mozilla-hub.atlassian.net/browse/FNXV2-20230

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21206)

**Comment by AaronMT** [comment]
This seems to fail `verifyRunBlockingAndStrictModeSuppresionCount` w/`StartupExcessiveResourceUse` [matrix](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8699151312555088192/details?stepId=bs.3dc042a3fdf0a1e1&testCaseId=1)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 105.0a1 (2022-08-18) build.
The sponsored shortcuts feature is enabled by default.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
