### ISSUE TITLE
[Bug]: splash screen not showing for PWA

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26339]
### Steps to reproduce

Starting with android 12, Google introduced a splash screen i.e
 Whenever you open any app it shows an animation of a white screen and app icon

For pwa created by brave browser in android 12, this design is consistent i.e. it is showing a splash screen whereas pwa created by firefox are missing the same

### Expected behaviour

Should show a splash screen

### Actual behaviour

Not showing splash screen in any app

### Device name

Rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

Example flipkart lite splash screen of brave browser
Test site: www.flipkart.com

![Screenshot_20220805-235310052](https://user-images.githubusercontent.com/58127841/183138501-14b05e6d-c78b-427c-862b-f35928739289.jpg)

### Additional information

More details about this feature
https://developer.android.com/guide/topics/ui/splash-screen

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21209)

**Comment by jonalmeida** [comment]
The current PWA implementation does not have support for splash screens - see https://github.com/mozilla-mobile/fenix/issues/10582.

Closing as duplicate.
