### ISSUE TITLE
Update credit card prompt is incorrectly displayed again when attempting to return to the payment webpage

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26334]
### Steps to reproduce

1. Have a credit card saved in Fenix.
2. Go to https://checkout.stripe.dev/ .
3. Fill in the form with the data of the saved credit card.
4. Modify the data in any field.
5. Tap on "Pay".
6. Tap the back button to return to the payment page from the confirmation page.
7. Observe the prompt.

### Expected behaviour

The user is returned on the page in Step 2, the form is cleared.

### Actual behaviour

After step 7, the "Update card expiration date" prompt is displayed again when tapping the back button from the confirmation page. Another tap on the back button is required to return on the page in step 1. 

### Device name

Lenovo Yoga Tab 11, Google Pixel 6 

### Android version

Android 11, Android 13)

### Firefox release type

Firefox Beta

### Firefox version

Beta 104.0b4

### Additional information

https://user-images.githubusercontent.com/89388888/183102624-63d42fcb-f9d2-4aae-8f99-fb6ac538c853.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21205)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813817

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
