### ISSUE TITLE
add inbuilt video player

### ISSUE THREAD

**Issue by BigDogg99** [mozilla-mobile/fenix#26343]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Current video player is not optimized for mobile. for example if I want to change brightness of video i have to change from notification manu same with volume . add swipe control to chage brightness and volume. and some video with long aspect ratio show in a black box 
![Screenshot_20220806-150854_Mull](https://user-images.githubusercontent.com/109841554/183243587-b175cbca-7f03-4441-a1ae-b1d5645df463.png) add option to change aspect ratio (like mx player or vlc player)

### How do you know that this problem exists today? Why is this important?
becouse it will help us watch videos ( i will delete youtube app) 

### Who will benefit from it?
everyone who watch video in browser

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21211)

**Comment by sheikh-azharuddin** [comment]
Samsung browser and banana browser have inbuilt video controls

On a side note for aspect ratio, you can try ultrawideo add on in nightly

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813818

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
