### ISSUE TITLE
Add the ability to use custom stylesheets

### ISSUE THREAD

**Issue by SoniEx2** [mozilla-mobile/fenix#26340]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Accessibility.

### How do you know that this problem exists today? Why is this important?

Because you can't set page style.

### Who will benefit from it?

Everyone.

Calling it an accessibility setting makes it an accessibility setting and allows litigators to sue over lack of it. It'd be a huge win for accessibility to call page styles/alternative style sheets an accessibility setting.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21210)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814166

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
