### ISSUE TITLE
YouTube Kids website not loading correctly

### ISSUE THREAD

**Issue by ShintoPlasm** [mozilla-mobile/fenix#26357]
## Site with issue and any steps to reproduce
YouTube Kids (https://www.youtubekids.com) does not load correctly - as a mobile website - in Fenix. Instead of loading the contents, it forwards you to the download page for the YouTube Kids apps (https://www.youtube.com/kids).

Steps:
1. Ensure 'mobile version' is selected in Fenix; the desktop version of the site loads correctly (even though unsuitable for mobile use).
2. Go to https://www.youtubekids.com

### Expected behavior
The YouTube Kids web version loads as expected.

### Actual behavior
The YouTube Kids web version does not load at all. Instead, the browser is forwarded to the YouTube Kids apps' download page.

### Does toggling Tracking Protection fix the issue?
No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No. Brave and Bromite (on the same Amazon tablet) load the web version of YT Kids correctly.

### Device information

* Android device: Amazon Fire HD 8 (8th Generation) tablet / FireOS 7.3.2.3
* Fenix version: 103.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21216)

**Comment by kbrosnan** [comment]
I get the same website in both Chrome and Firefox directing users to the app.

**Comment by ShintoPlasm** [comment]
> I get the same website in both Chrome and Firefox directing users to the app.

Okay, I've rechecked the behaviour and you're right - it does that on my normal Google Pixel 5 too. However, the behaviour I described appears on our son's Amazon Fire tablet. I've updated my description to reflect this.

**Comment by kbrosnan** [comment]
This requires the kid to be logged in? I don't have YT kids set up.

**Comment by ShintoPlasm** [comment]
Login is not required, though possible.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813942

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
