### ISSUE TITLE
[Bug]: firefox for android don't block google-analytics on twitter

### ISSUE THREAD

**Issue by holequantum** [mozilla-mobile/fenix#26351]
### Steps to reproduce

1. open twitter.com
2. then open lock sign
3. then details of enhanced tracking protection
4. and see google-analytics is allowed whatever you do it can't be blocked.

### Expected behaviour

it should have blocked that google-analytics but it does not i have tried fenix by fdroid and mull by divestos that also and those does block google-analytics by default with strict and normal mode.
*i think there is a bug need to be addressed*

### Actual behaviour

google-analytics allowed in firefox android(playstore) in twitter.com

### Device name

googlepixel 5a, moto edge 20.

### Android version

android 12, android 13beta

### Firefox release type

Firefox

### Firefox version

103.2.0 (Build #2015895963)

### Device logs

none

### Additional information

i have tried with beta and nighty but same issue but it is not the case in firefox from fdroid.
i have tried this apps and those apps does block gpogle-analytics and twitter does open perfectly fine in both hence there is a issue downloaded from playstore.
link of fdroid firefox fork
https://f-droid.org/en/packages/org.mozilla.fennec_fdroid
https://f-droid.org/en/packages/us.spotco.fennec_dos

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21214)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/26059
