### ISSUE TITLE
Cleanup linters baseline files

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26358]
We currently have two baseline files used by the static analysis tools:
- [for Android lint](https://github.com/mozilla-mobile/fenix/blob/1a2b3571197f74d842154ab93db992160c93479b/app/lint-baseline.xml)
- [for detekt](https://github.com/mozilla-mobile/fenix/blob/1a2b3571197f74d842154ab93db992160c93479b/detekt-baseline.xml)

which are used to ignore even new lint issues instead of them only serving as the list of initially caught issues when the static analysis tools were first integrated.
Since ignoring issues caught in static analysis defeats the purpose and adding the ignores in the baseline files allow to forget about such issues we should look into resolving the issues and clearing the baseline files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21217)

Follow-ups:
- [x] https://github.com/mozilla-mobile/fenix/issues/26362

**Comment by rudmannn** [comment]
I noticed the lint-baseline.xml for several times, and I can reproduce the issues induced by android:lineHeight.
https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/settings_https_only.xml#L34

https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/custom_search_engine.xml#L59

https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/fragment_onboarding_home_dialog.xml#L101

https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/fragment_onboarding_home_dialog.xml#L150

https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/fragment_onboarding_home_dialog.xml#L199

You can see the differences in below.

onboarding dialog
API Level 29
![2731659954434_ pic](https://user-images.githubusercontent.com/109571086/183399474-34e6e0d3-ba15-42b9-8134-89c913ad7d17.jpg)

API Level 27

![2761659954682_ pic](https://user-images.githubusercontent.com/109571086/183399514-8c95bcbf-7b98-4067-a2ee-352859bd21bb.jpg)

https only

API Level 29
![2741659954450_ pic](https://user-images.githubusercontent.com/109571086/183399566-f05c44a0-d5e6-4f44-9796-c8bc2a3fe714.jpg)

API Level 27
![2771659954698_ pic](https://user-images.githubusercontent.com/109571086/183399603-ac0ae61e-a454-4b07-b179-34b14d21649c.jpg)

search engine

API Level 29
![2751659954471_ pic](https://user-images.githubusercontent.com/109571086/183399638-227b7aae-3da3-4e30-8ce1-625a484e81e0.jpg)

API Level 27

![2781659954728_ pic](https://user-images.githubusercontent.com/109571086/183399883-b35253a6-b014-4d61-a83d-d02515bb24d2.jpg)

Note that you can simply change ``android:lineHeight`` to ``app:lineHeight`` and it works for API Level <= 27. I confirm that the issues have gone on my side.

**Comment by Mugurell** [comment]
Thank you for helping with this @rudmannn!
I just hidden your comment since it took a lot of UI space and opened a new ticket for the described issue https://github.com/mozilla-mobile/fenix/issues/26362 which is free to work on by you or others.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813820

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
