### ISSUE TITLE
[Bug]: Qualcomm QM215 SOC , text randomly missing or missing portions of letters/characters.

### ISSUE THREAD

**Issue by andrewpacific** [mozilla-mobile/fenix#26355]
### Steps to reproduce

Qualcomm QM215 SOC , text randomly missing or missing portions of letters/characters.

Happens seemingly randomly , on perhaps 5 -20% of pages.

**I've also used the beta and nightly versions** to access about:config and force and disable hardware acceleration etc and no difference was seen.

Also used android developer options to change opengl and hardware acceleration options with no difference seen.

### Expected behaviour

Text to display normally , as it does in other browsers on QM215 devices.

### Actual behaviour

Text is missing or the top or bottom half of text is missing. Happens seemingly randomly.

### Device name

Vodafone P11 aka Alcatel 5002x , Qualcomm QM215

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

103.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21215)

**Comment by andrewpacific** [comment]
![Screenshot_2022-08-08-16-44-07-146](https://user-images.githubusercontent.com/84649434/183341008-bff8b83d-577f-4180-b606-5ebe0e873d22.jpg)

It's actually doing it to this exact GitHub page, screenshot attached.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1783599

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by Mugurell** [comment]
Thank you for the report!
Moved the ticket to Bugzilla for more investigations. Please follow the progress there.
