### ISSUE TITLE
[Bug]: firefox does not protect from fingerprinting can be detected that it is in incognito

### ISSUE THREAD

**Issue by holequantum** [mozilla-mobile/fenix#26360]
### Steps to reproduce

1.   open firefox incognito mode
2.    go to the site fingerprint.com
3.    and see it is showing you that you are in incognito mode this need to be fix asap. this can fingerprint you that you are in incognito.

### Expected behaviour

everytime i have tried on desktop mac and linux in both is https://fingerprint.com/ does detect
you that you are in incognito even if you are in a vpn tor or mull.

### Actual behaviour

does not block fingerprint about if i am in incognito or not in incognito.

### Device name

google pixel 5a, moto edge 20

### Android version

android 13beta, android 12

### Firefox release type

Firefox

### Firefox version

103.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21219)

**Comment by Mugurell** [comment]
Moving the ticket to Bugzilla for more investigations, please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1783617

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by holequantum** [comment]
> Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1783617
> 
> Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

can you just change tag from android to all platform in desktop firefox is also included
