### ISSUE TITLE
android:lineHeight issues on API Level <= 27

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26362]
From @rudmannn:

I noticed the lint-baseline.xml for several times, and I can reproduce the issues induced by android:lineHeight.
https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/settings_https_only.xml#L34

https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/custom_search_engine.xml#L59

https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/fragment_onboarding_home_dialog.xml#L101

https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/fragment_onboarding_home_dialog.xml#L150

https://github.com/mozilla-mobile/fenix/blob/df702a2694c87a61da54b557fe7a1deca6405ee6/app/src/main/res/layout/fragment_onboarding_home_dialog.xml#L199

You can see the differences in below.

onboarding dialog
API Level 29
![2731659954434_ pic](https://user-images.githubusercontent.com/109571086/183399474-34e6e0d3-ba15-42b9-8134-89c913ad7d17.jpg)

API Level 27

![2761659954682_ pic](https://user-images.githubusercontent.com/109571086/183399514-8c95bcbf-7b98-4067-a2ee-352859bd21bb.jpg)

https only

API Level 29
![2741659954450_ pic](https://user-images.githubusercontent.com/109571086/183399566-f05c44a0-d5e6-4f44-9796-c8bc2a3fe714.jpg)

API Level 27
![2771659954698_ pic](https://user-images.githubusercontent.com/109571086/183399603-ac0ae61e-a454-4b07-b179-34b14d21649c.jpg)

search engine

API Level 29
![2751659954471_ pic](https://user-images.githubusercontent.com/109571086/183399638-227b7aae-3da3-4e30-8ce1-625a484e81e0.jpg)

API Level 27

![2781659954728_ pic](https://user-images.githubusercontent.com/109571086/183399883-b35253a6-b014-4d61-a83d-d02515bb24d2.jpg)

Note that you can simply change ``android:lineHeight`` to ``app:lineHeight`` and it works for API Level <= 27. I confirm that the issues have gone on my side.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21221)

**Comment by rudmannn** [comment]
Filed a pull request in #26364
