### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by robsmith11** [mozilla-mobile/fenix#2637]
### Why/User Benefit/User Problem
Speel checking is a common feature in other browsers (e.g., Firefox on Desktop and Chrome on both Desktop and Android).

It would be useful especially when using a bluetooth keyboard, when there are no typing completions. 

### What/Requirements
Draw a red squiggly line under misspelled words.  Suggest corrections in a context menu. At least an English dictionary should be included, possibly other languages could be downloaded. 

### Acceptance Criteria (how do I know when I’m done?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11570)

**Comment by makotokato** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1541697

**Comment by cpeterso** [comment]
Tentatively adding the `Feature:FennecTransition` label because Fennec has a spell checker for text input.

@vesta0 - Is spell checking a blocker for the Fennec/Fenix transition?

**Comment by kbrosnan** [comment]
Fennec Android never used the spell checker code in Core/Toolkit. XUL Fennec < v10 might have.

**Comment by vesta0** [comment]
That's good to know @kbrosnan thanks

**Comment by prahladyeri** [comment]
August 2020 is dawning upon us tommorrow and this very basic feature is still missing from mobile firefox. I hope this gets fixed soon.

**Comment by WesleyAC** [comment]
What's the status of this? Is spellchecking on the roadmap?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809979

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
