### ISSUE TITLE
Increase in `recent_synced_tabs.recent_synced_tab_time_to_load` metric's "Invalid State" error rate

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26372]
https://github.com/mozilla-mobile/fenix/issues/24549 added a new `recent_synced_tabs.recent_synced_tab_time_to_load` metric.

The `recent_synced_tabs.recent_synced_tab_time_to_load` metric's "Invalid State" errors first appeared on  2022-05-29 and then steadily increased starting around 2022-07-16 according to this Looker dashboard:

https://mozilla.cloud.looker.com/explore/fenix/metrics?qid=71BIZZESHAIYQrE5ZzOR2f&origin_space=746&toggle=fil,vis

![image](https://user-images.githubusercontent.com/629193/183507365-60281f83-7fd6-4885-92c3-53f798d28bee.png)

![image](https://user-images.githubusercontent.com/629193/183507390-ae117573-5037-4fea-bec9-df349601ad23.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21226)

**Comment by cpeterso** [comment]
We should probably prioritize this bug. This regression is now on Release, generating about 1.5M "Invalid State" Glean errors per day for the `recent_synced_tab_time_to_load metric` metric:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/629193/199914720-8cba4f6f-92b2-42cf-b376-d3bdb7c1bc28.png">

https://mozilla.cloud.looker.com/explore/fenix/metrics?qid=aeQaAQQgwFPdZrqX9XcH7Z&origin_space=746&toggle=fil,vis

**Comment by cpeterso** [comment]
An engineer will investigate the cause of the invalid state errors and whether it affects users. TBD whether we fix this bug in Fenix 109.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813823

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
