### ISSUE TITLE
[Bug]: Task Continuity feature is always off in Secret Settings (in Nightly)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#26370]
### Steps to reproduce

1. Install a fresh build (or clear app data).
2. Enable Secret Settings (10 taps in about).
3. Go to Secret Settings.
4. Observe.
5. Enable Task Continunity feature.
6. Leave the Secret Settings screen.
7. Return back to it again.
8. Observe.

### Expected behaviour

- At step 4, you should see the feature on by default.
- At step 8, you should see the feature enabled.

### Actual behaviour

- At step 4, the feature is not enabled by default.
- At step 8, the feature is disabled.

### Device name

Pixel 3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

103.a1 (Build #2015891547) (ed2857bbe0+)

### Additional information

https://user-images.githubusercontent.com/1370580/183493989-82a477a6-a1aa-4d7c-9db6-8e48fa80395d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21224)

**Comment by jonalmeida** [comment]
QA: would it be possible to see if this bug is reproducible? We would need this fixed soon if we want to get good coverage of the feature before it rolls out.

**Comment by jonalmeida** [comment]
Choosing this as invalid. I think I had an old build while testing a different feature.

**Comment by binarynoise** [comment]
In Firefox (release) Version 105.1.0 this still is an issue
