### ISSUE TITLE
High number of "Invalid Value" errors from `logins_store.migration_num_processed` and ` logins_store.migration_num_failed` Glean metrics

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26375]
This Looker dashboard shows about 9000 "Invalid Value" errors per day for the `logins_store.migration_num_processed` metric and 15,000 errors per day for the ` logins_store.migration_num_failed` metric:

https://mozilla.cloud.looker.com/explore/fenix/metrics?qid=uN26PMq3JjzlU74QqVRYEY&origin_space=746&toggle=fil,vis

These are the most common "Invalid Value" errors on Fenix's Release channel. The errors aren't recent regressions: these errors have been around for at least 180 days. The good news is that the error rate has slowly decreasing (from 35,000 + 65,000 errors per day a year ago):

![image](https://user-images.githubusercontent.com/629193/183519053-64bca2ed-db05-4c40-a5c5-30fb8f0e2b8f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21229)

**Comment by mcarare** [comment]
These metrics are defined and registered in a-s. They were removed last month: https://github.com/mozilla/application-services/pull/5019.

**Comment by cpeterso** [comment]
Thanks. In that case, I'll close this bug.
