### ISSUE TITLE
High number of "Invalid Value" errors from `power.wakeups_per_process_type` and `power.total_thread_wakeups` Glean metrics

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26374]
This Looker dashboard shows about 2500 "Invalid Value" errors per day for the `power.wakeups_per_process_type` metric and 2500 for the `power.total_thread_wakeups` metric:

https://mozilla.cloud.looker.com/explore/fenix/metrics?qid=FFG7PKqqkZiXbs35vwokbp&origin_space=746&toggle=fil,vis

![image](https://user-images.githubusercontent.com/629193/183518727-eee5e20f-6c41-4d17-bcf8-c9a08126c662.png)

These are the most common "Invalid Value" errors on Fenix's Beta and Nightly channels, but don't seem to show up in the Release channel. The errors aren't recent regressions: the error rate has been steady for at least 180 days.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21228)

**Comment by Mugurell** [comment]
`Invalid value` for a labeled counter is reported if `if the counter is incremented by 0 or a negative value.` - https://mozilla.github.io/glean/book/reference/metrics/labeled_counters.html

[This telemetry](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/power_wakeups_per_process_type) is from Gecko and seem like @fqueze is the owner.

**Comment by fqueze** [comment]
This is recorded at https://searchfox.org/mozilla-central/rev/f655bdf6b4bf01b42609750ab94fc37635397260/tools/profiler/core/platform.cpp#6579-6584 and the code there ensure we don't record values that are <= 0 or >= max(int32), so I don't see how we could record invalid values.

Are the values invalid for everybody or only for some users? (I don't have a sense of how many Fenix users we have reporting Glean telemetry on the nightly and beta channels, so I don't know whether 2500 per day is almost all users or just a small subset)

**Comment by cpeterso** [comment]
I'm going to close this issue as invalid. This was an issue with the chart. Sorry!

> This is recorded at https://searchfox.org/mozilla-central/rev/f655bdf6b4bf01b42609750ab94fc37635397260/tools/profiler/core/platform.cpp#6579-6584 and the code there ensure we don't record values that are <= 0 or >= max(int32), so I don't see how we could record invalid values.

I see the code to guard against non-positive values was added in Nightly 101.0a1 in April 2022:

https://searchfox.org/mozilla-central/diff/a62a18fff637783825b6e18637f333f939b33284/tools/profiler/core/platform.cpp#6461

Since this chart is graphing metrics by submission date, not build date, I thought maybe the errors we're seeing now are from old builds that don't have your April fix. And indeed, when I filter the chart to only show telemetry from Nightly builds >= 102.0a1, there are zero errors from the wakeup metrics.

I'll ask the team that built that chart to filter the telemetry by build date.
