### ISSUE TITLE
[Bug]: Recent synced tab should re-open tab if open

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26377]
### Steps to reproduce

1. Have a recent synced tab on the home screen
2. Click it
3. Return to home
4. Click it again
5. A second new tab is opened

### Expected behaviour

Previously opened tab should be opened

### Actual behaviour

A second new tab is opened

### Android version

10

### Firefox release type

Firefox Nightly

### Firefox version

Current

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21230)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 105.0a1 2022-08-10 and the issue no longer occurs. After clicking on a recent synced tab on the home screen that is already opened, it will open the existing tab and not a new one.
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
