### ISSUE TITLE
FNX3-16473 ⁃ [Bug] Cant press signin button on github.com

### ISSUE THREAD

**Issue by Kriskras99** [mozilla-mobile/fenix#2638]
## Steps to reproduce
Go to https://github.com
Open the hamburger menu.
Press signin button.

### Expected behavior
Go to signin page.

### Actual behavior
Nothing happens

### Device information
* Android device: Nexus 5X (8.1-20180911 AOSiP)
* Fenix version: 1.0.1920

**Comment by cadeyrn** [comment]
The mobile menu on Github is completely broken in Fenix. It's not only the signin button, also the signup button and the search field. And all menu items with a submenu does not open the submenu on click but open a link instead. And the top of the menu with the close button is cut off.

But in Firefox (Fennec) all of this works as expected.

**Comment by cadeyrn** [comment]
could be related to #2574. Once you scroll a bit down and the Fenix toolbar is hidden all of these issues are gone.

**Comment by alexa-v2** [comment]
I found the only way to resolve was to use desktop version of GitHub

**Comment by cadeyrn** [comment]
You don't have to use the desktop version. You only have to scroll a bit down until the Fenix toolbar is hidden, then it works.

**Comment by bifleming** [comment]
fixed with static bar

**Comment by Kriskras99** [comment]
Why was this reopened? This issue was fixed a year ago.
Also has not resurfaced on current nightly or stable.

**Comment by cadeyrn** [comment]
> Why was this reopened?

It was accidentally reopened by the data-sync-user bot, as many other issues as well.
