### ISSUE TITLE
The crash prompt UI should be revised 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26384]
### Steps to reproduce

1. Open a few tabs on Fenix.
2. Tap the URL bar and access about:crashparent.
3. Tap the crash notification from the android notification bar.
4. Observe the prompt UI.

### Expected behaviour

No figma design or specs could be found, therefor pending UX feedback. 

### Actual behaviour

Depending on the device, the prompt can be wrongly displayed: there is a wide blank space after the strings, and the buttons seem uncentered.  

### Device name

Lenovo Yoga Tab 11 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 105.0a1

### Additional information

Also observed on Fenix Beta/RC and Focus.
![dialog_options](https://user-images.githubusercontent.com/89388888/183643617-81609b9c-3e5d-4aa0-b368-62463485e599.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21236)

**Comment by lime124** [comment]
The crash dialogue should appear the same as other dialogues on the device. I don't have access to this device so I'm not able to verify what if anything is different from the other ones. Thanks delia!

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812769

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
