### ISSUE TITLE
[Bug]: Title of settings doesn't localize

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#26389]
### Steps to reproduce

1. I updated to 103.2 (Firefox Release)
2. Firefox opened in Breton, can't remember I switched it (who knows, maybe I did)
3. Changed the language to German

### Expected behaviour

Setting should have localized German header

### Actual behaviour

Settings still has title in Breton (see screenshot)
![Screenshot (Aug 9, 2022 4 59 37 PM)](https://user-images.githubusercontent.com/353960/183687670-935811e2-fb55-4b41-b66b-cb141e2b7bbd.png)

### Device name

Pixel 3

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

103.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21239)

**Comment by csadilek** [comment]
I tried in latest Nightly 110 and Release 108. This doesn't seem to reproduce anymore.
