### ISSUE TITLE
Intermittent UI test failure - java.lang.SecurityException: Package com.google.android.gms is currently frozen!

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26385]
❗ [Related explanation ](https://stackoverflow.com/questions/47643030/android-security-exception-package-is-frozen/48066659#48066659)

#### • `verifyContextShareLink ` [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8637804910995947453/executions/bs.32b797f66b580570/test-cases)

8-01 18:57:11.971: E/ActivityManager(478): Failure starting process com.google.android.gms.persistent
08-01 18:57:11.971: E/ActivityManager(478): java.lang.SecurityException: Package com.google.android.gms is currently frozen!
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.pm.PackageManagerService.checkPackageStartable(PackageManagerService.java:4463)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:1757)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2319)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2441)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3170)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2946)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2062)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:15184)
08-01 18:57:11.971: E/ActivityManager(478): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1833)
08-01 18:57:11.971: E/ActivityManager(478): 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1783)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.ServiceWatcher.rebind(ServiceWatcher.java:339)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.ServiceWatcher.onBestServiceChanged(ServiceWatcher.java:310)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.ServiceWatcher.onBindingDied(ServiceWatcher.java:391)
08-01 18:57:11.971: E/ActivityManager(478): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1950)
08-01 18:57:11.971: E/ActivityManager(478): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1986)
08-01 18:57:11.971: E/ActivityManager(478): 	at android.os.Handler.handleCallback(Handler.java:938)
08-01 18:57:11.971: E/ActivityManager(478): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-01 18:57:11.971: E/ActivityManager(478): 	at android.os.Looper.loop(Looper.java:223)
08-01 18:57:11.971: E/ActivityManager(478): 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-01 18:57:11.971: E/ActivityManager(478): 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
08-01 18:57:11.971: I/ActivityManager(478): Force stopping com.google.android.gms appid=10097 user=0: start failure
08-01 18:57:11.971: I/ActivityManager(478):   Force stopping service ServiceRecord{1103d90 u0 com.google.android.gms/com.google.android.location.internal.server.HardwareArProviderService}
08-01 18:57:11.972: W/ActivityManager(478): Slow operation: 103ms so far, now at startProcess: done starting proc!
08-01 18:57:11.972: W/ActivityManager(478): Unable to launch app com.google.android.gms/10097 for service Intent { act=com.android.location.service.ActivityRecognitionProvider cmp=com.google.android.gms/com.google.android.location.internal.server.HardwareArProviderService }: process is bad
08-01 18:57:11.972: W/Looper(478): Slow dispatch took 436ms android.fg h=android.os.Handler c=android.app.LoadedApk$ServiceDispatcher$RunConnection@40c4689 m=0

#### • `customTabCopyToolbarUrlTest ` [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8924622104845739441/executions/bs.2559b28312d4bba6/test-cases)

08-08 07:47:41.503: E/ActivityManager(477): Failure starting process com.google.android.gms
08-08 07:47:41.503: E/ActivityManager(477): java.lang.SecurityException: Package com.google.android.gms is currently frozen!
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.pm.PackageManagerService.checkPackageStartable(PackageManagerService.java:4463)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:1757)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2319)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2441)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3170)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2946)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2062)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:15184)
08-08 07:47:41.503: E/ActivityManager(477): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1833)
08-08 07:47:41.503: E/ActivityManager(477): 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1773)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.media.MediaRoute2ProviderServiceProxy.bind(MediaRoute2ProviderServiceProxy.java:224)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.media.MediaRoute2ProviderServiceProxy.onBindingDied(MediaRoute2ProviderServiceProxy.java:290)
08-08 07:47:41.503: E/ActivityManager(477): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1950)
08-08 07:47:41.503: E/ActivityManager(477): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1986)
08-08 07:47:41.503: E/ActivityManager(477): 	at android.os.Handler.handleCallback(Handler.java:938)
08-08 07:47:41.503: E/ActivityManager(477): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-08 07:47:41.503: E/ActivityManager(477): 	at android.os.Looper.loop(Looper.java:223)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.SystemServer.run(SystemServer.java:622)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.server.SystemServer.main(SystemServer.java:408)
08-08 07:47:41.503: E/ActivityManager(477): 	at java.lang.reflect.Method.invoke(Native Method)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-08 07:47:41.503: E/ActivityManager(477): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
08-08 07:47:41.503: I/ActivityManager(477): Force stopping com.google.android.gms appid=10097 user=0: start failure
08-08 07:47:41.505: I/ActivityManager(477):   Force stopping service ServiceRecord{8e08238 u0 com.google.android.gms/.cast.media.CastMediaRouteProviderService}
08-08 07:47:41.506: W/ActivityManager(477): Slow operation: 124ms so far, now at startProcess: done starting proc!
08-08 07:47:41.506: W/ActivityManager(477): Unable to launch app com.google.android.gms/10097 for service Intent { act=android.media.MediaRoute2ProviderService cmp=com.google.android.gms/.cast.media.CastMediaRouteProviderService }: process is bad
08-08 07:47:41.506: W/Looper(477): Slow dispatch took 389ms main h=android.app.ActivityThread$H c=android.app.LoadedApk$ServiceDispatcher$RunConnection@e94b211 m=0
08-08 07:47:41.506: W/Looper(477): Slow delivery took 389ms main h=com.android.server.media.MediaRouter2ServiceImpl$UserHandler c=<recycled PooledLambda@db72f76> m=0
08-08 07:47:41.506: W/system_server(477): Long monitor contention with owner main (477) at int com.android.server.am.ActivityManagerService.bindIsolatedService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, java.lang.String, int)(ActivityManagerService.java:15184) waiters=1 in int com.android.server.am.ActivityManagerService.getUidProcessState(int, java.lang.String) for 350ms
08-08 07:47:41.507: W/system_server(477): Long monitor contention with owner main (477) at int com.android.server.am.ActivityManagerService.bindIsolatedService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, java.lang.String, int)(ActivityManagerService.java:15184) waiters=2 in int com.android.server.am.ActivityManagerService.getUidProcessState(int, java.lang.String) for 337ms
08-08 07:47:41.507: W/ActivityManager(477): setHasOverlayUi called on unknown pid: 6054

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21237)

**Comment by Mugurell** [comment]
Looking at the rendering times of Firefox - Release in `Google Play Console -> Android vitals -> Overview` it does seem like we have quite a few frozen frames:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/11428869/184108821-22ba2668-40ca-43fd-92f3-5a2969b9d2d1.png">

---
- `slow frames` - A frame is slow if it missed the device's drawing deadline
- `frozen frames` - A frame is frozen if it had a frame time longer than 700ms.

cc @mcomella

**Comment by AndiAJ** [comment]
### ► 8/12 Main 
#### • `goToHomeScreenTopToolbarTest ` [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4662051732447706368/executions/bs.754f192bb357da48/test-cases)

08-12 00:05:22.131: E/ActivityManager(478): Failure starting process com.google.android.gms
08-12 00:05:22.131: E/ActivityManager(478): java.lang.SecurityException: Package com.google.android.gms is currently frozen!
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.pm.PackageManagerService.checkPackageStartable(PackageManagerService.java:4463)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:1757)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2319)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2441)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3170)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2946)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2062)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:15184)
08-12 00:05:22.131: E/ActivityManager(478): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1833)
08-12 00:05:22.131: E/ActivityManager(478): 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1773)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.media.MediaRoute2ProviderServiceProxy.bind(MediaRoute2ProviderServiceProxy.java:224)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.media.MediaRoute2ProviderServiceProxy.onBindingDied(MediaRoute2ProviderServiceProxy.java:290)
08-12 00:05:22.131: E/ActivityManager(478): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1950)
08-12 00:05:22.131: E/ActivityManager(478): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1986)
08-12 00:05:22.131: E/ActivityManager(478): 	at android.os.Handler.handleCallback(Handler.java:938)
08-12 00:05:22.131: E/ActivityManager(478): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-12 00:05:22.131: E/ActivityManager(478): 	at android.os.Looper.loop(Looper.java:223)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.SystemServer.run(SystemServer.java:622)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.server.SystemServer.main(SystemServer.java:408)
08-12 00:05:22.131: E/ActivityManager(478): 	at java.lang.reflect.Method.invoke(Native Method)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-12 00:05:22.131: E/ActivityManager(478): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
08-12 00:05:22.131: I/ActivityManager(478): Force stopping com.google.android.gms appid=10097 user=0: start failure
08-12 00:05:22.135: I/ActivityManager(478):   Force stopping service ServiceRecord{1d43441 u0 com.google.android.gms/.cast.media.CastMediaRouteProviderService}
08-12 00:05:22.142: W/audio_hw_generic(1908): Hardware backing HAL too slow, could only write 0 of 661 frames
08-12 00:05:22.145: W/ActivityManager(478): Slow operation: 92ms so far, now at startProcess: done starting proc!
08-12 00:05:22.145: W/ActivityManager(478): Unable to launch app com.google.android.gms/10097 for service Intent { act=android.media.MediaRoute2ProviderService cmp=com.google.android.gms/.cast.media.CastMediaRouteProviderService }: process is bad
08-12 00:05:22.146: W/Looper(478): Slow dispatch took 395ms main h=android.app.ActivityThread$H c=android.app.LoadedApk$ServiceDispatcher$RunConnection@a8c3de6 m=0
08-12 00:05:22.146: I/ActivityManager(478): Exiting empty application process 0:com.google.android.gms/u0a97 (null)
08-12 00:05:22.146: W/Looper(478): Slow delivery took 395ms main h=com.android.server.media.MediaRouter2ServiceImpl$UserHandler c=<recycled PooledLambda@e769f27> m=0
08-12 00:05:22.147: W/system_server(478): Long monitor contention with owner main (478) at int com.android.server.am.ActivityManagerService.bindIsolatedService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, java.lang.String, int)(ActivityManagerService.java:15184) waiters=2 in void com.android.server.am.ActivityManagerService.serviceDoneExecuting(android.os.IBinder, int, int, int) for 391ms
08-12 00:05:22.150: W/ActivityManager(478): Service done with onDestroy, but not inDestroying: ServiceRecord{84f315e u0 com.google.android.gms/.icing.service.AppIndexingService}, app=ProcessRecord{cfdfa69 0:com.google.android.gms/u0a97}
08-12 00:05:22.151: W/Looper(478): Slow dispatch took 398ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=31
08-12 00:05:22.152: W/Looper(478): Slow delivery took 396ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=53
08-12 00:05:22.152: W/Looper(478): Drained

**Comment by AndiAJ** [comment]
`closeTabCrashedReporterTest` flaky 1x on 8/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7394489398509596383/executions/bs.8f54652064f0ccd2/test-cases)

08-18 14:03:20.580: I/ActivityManager(480): Force stopping org.mozilla.fenix.debug appid=10152 user=0: clear data
08-18 14:03:20.581: I/ActivityManager(480): Exiting empty application process 0:com.google.android.gms/u0a97 (null)
08-18 14:03:20.582: E/ActivityManager(480): Failure starting process com.google.android.gms.persistent
08-18 14:03:20.582: E/ActivityManager(480): java.lang.SecurityException: Package com.google.android.gms is currently frozen!
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.pm.PackageManagerService.checkPackageStartable(PackageManagerService.java:4463)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:1757)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2319)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2441)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3170)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2946)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2062)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:15184)
08-18 14:03:20.582: E/ActivityManager(480): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1833)
08-18 14:03:20.582: E/ActivityManager(480): 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1783)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.ServiceWatcher.rebind(ServiceWatcher.java:339)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.ServiceWatcher.onBestServiceChanged(ServiceWatcher.java:310)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.ServiceWatcher.onBindingDied(ServiceWatcher.java:391)
08-18 14:03:20.582: E/ActivityManager(480): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1950)
08-18 14:03:20.582: E/ActivityManager(480): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1986)
08-18 14:03:20.582: E/ActivityManager(480): 	at android.os.Handler.handleCallback(Handler.java:938)
08-18 14:03:20.582: E/ActivityManager(480): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-18 14:03:20.582: E/ActivityManager(480): 	at android.os.Looper.loop(Looper.java:223)
08-18 14:03:20.582: E/ActivityManager(480): 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-18 14:03:20.582: E/ActivityManager(480): 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
08-18 14:03:20.582: I/ActivityManager(480): Force stopping com.google.android.gms appid=10097 user=0: start failure
08-18 14:03:20.582: I/ActivityManager(480):   Force stopping service ServiceRecord{2613ecb u0 com.google.android.gms/.location.geocode.GeocodeService}
08-18 14:03:20.582: W/ActivityManager(480): Unable to launch app com.google.android.gms/10097 for service Intent { act=com.android.location.service.GeocodeProvider cmp=com.google.android.gms/.location.geocode.GeocodeService }: process is bad
08-18 14:03:20.582: I/ActivityManager(480): Exiting empty application process 0:com.google.android.gms.persistent/u0a97 (null)
08-18 14:03:20.584: E/ActivityManager(480): Failure starting process com.google.android.gms

**Comment by AndiAJ** [comment]
💥 `visitURLTest` Failed 1x on 8/21 Nightly [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/7705001991667649775/executions/bs.d28b522c9969af3e)

08-21 13:28:22.231: E/ActivityManager(463): Failure starting process com.android.vending
08-21 13:28:22.231: E/ActivityManager(463): java.lang.SecurityException: Package com.android.vending is currently frozen!
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.pm.PackageManagerService.checkPackageStartable(PackageManagerService.java:4463)
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:1757)
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2319)
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2441)
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3170)
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2946)
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2062)
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:15184)
08-21 13:28:22.231: E/ActivityManager(463): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2547)
08-21 13:28:22.231: E/ActivityManager(463): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2883)
08-21 13:28:22.231: E/ActivityManager(463): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
08-21 13:28:22.231: E/ActivityManager(463): 	at android.os.Binder.execTransact(Binder.java:1123)
08-21 13:28:22.231: I/ActivityManager(463): Force stopping com.android.vending appid=10091 user=0: start failure
08-21 13:28:22.232: I/ActivityManager(463):   Force stopping service ServiceRecord{b02f6c8 u0 com.android.vending/com.google.android.finsky.zapp.PlayModuleService}

**Comment by AndiAJ** [comment]
💥 `openMainMenuSettingsItemTest` Failed 1x on 8/22 Nightly [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/7705001991667649775/executions/bs.d28b522c9969af3e)

08-22 07:50:22.996: E/ActivityManager(482): Failure starting process com.google.android.gms
08-22 07:50:22.996: E/ActivityManager(482): java.lang.SecurityException: Package com.google.android.gms is currently frozen!
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.pm.PackageManagerService.checkPackageStartable(PackageManagerService.java:4463)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:1757)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2319)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2441)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3170)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2946)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2062)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:15184)
08-22 07:50:22.996: E/ActivityManager(482): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1833)
08-22 07:50:22.996: E/ActivityManager(482): 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1773)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.media.MediaRoute2ProviderServiceProxy.bind(MediaRoute2ProviderServiceProxy.java:224)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.media.MediaRoute2ProviderServiceProxy.onBindingDied(MediaRoute2ProviderServiceProxy.java:290)
08-22 07:50:22.996: E/ActivityManager(482): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1950)
08-22 07:50:22.996: E/ActivityManager(482): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1986)
08-22 07:50:22.996: E/ActivityManager(482): 	at android.os.Handler.handleCallback(Handler.java:938)
08-22 07:50:22.996: E/ActivityManager(482): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-22 07:50:22.996: E/ActivityManager(482): 	at android.os.Looper.loop(Looper.java:223)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.SystemServer.run(SystemServer.java:622)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.server.SystemServer.main(SystemServer.java:408)
08-22 07:50:22.996: E/ActivityManager(482): 	at java.lang.reflect.Method.invoke(Native Method)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-22 07:50:22.996: E/ActivityManager(482): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
08-22 07:50:22.996: I/ActivityManager(482): Force stopping com.google.android.gms appid=10097 user=0: start failure
08-22 07:50:22.996: I/ActivityManager(482):   Force stopping service ServiceRecord{fe97574 u0 com.google.android.gms/.cast.media.CastMediaRouteProviderService}
08-22 07:50:22.996: W/ActivityManager(482): Unable to launch app com.google.android.gms/10097 for service Intent { act=android.media.MediaRoute2ProviderService cmp=com.google.android.gms/.cast.media.CastMediaRouteProviderService }: process is bad
08-22 07:50:22

**Comment by AndiAJ** [comment]
`findInPageTest` flaky 1x on 8/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4924685067081025544/executions/bs.cdd9f757d98084e0/test-cases)

08-23 09:20:29.760: E/ActivityManager(470): java.lang.SecurityException: Package com.google.android.gms is currently frozen!
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.pm.PackageManagerService.checkPackageStartable(PackageManagerService.java:4463)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:1757)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2319)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2441)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3170)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2946)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2062)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:15184)
08-23 09:20:29.760: E/ActivityManager(470): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1833)
08-23 09:20:29.760: E/ActivityManager(470): 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1783)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.ServiceWatcher.rebind(ServiceWatcher.java:339)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.ServiceWatcher.onBestServiceChanged(ServiceWatcher.java:310)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.ServiceWatcher.onBindingDied(ServiceWatcher.java:391)
08-23 09:20:29.760: E/ActivityManager(470): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1950)
08-23 09:20:29.760: E/ActivityManager(470): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1986)
08-23 09:20:29.760: E/ActivityManager(470): 	at android.os.Handler.handleCallback(Handler.java:938)
08-23 09:20:29.760: E/ActivityManager(470): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-23 09:20:29.760: E/ActivityManager(470): 	at android.os.Looper.loop(Looper.java:223)
08-23 09:20:29.760: E/ActivityManager(470): 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-23 09:20:29.760: E/ActivityManager(470): 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
08-23 09:20:29.760: I/ActivityManager(470): Force stopping com.google.android.gms appid=10097 user=0: start failure
08-23 09:20:29.762: I/ActivityManager(470):   Force stopping service ServiceRecord{f939cf7 u0 com.google.android.gms/com.google.android.location.fused.FusedLocationService}
08-23 09:20:29.763: W/ActivityManager(470): Slow operation: 138ms so far, now at startProcess: done starting proc!
08-23 09:20:29.763: W/ActivityManager(470): Unable to launch app com.google.android.gms/10097 for service Intent { act=com.android.location.service.FusedLocationProvider cmp=com.google.android.gms/com.google.android.location.fused.FusedLocationService }: process is bad

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807301

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
