### ISSUE TITLE
Intermittent black box on bottom of the screen

### ISSUE THREAD

**Issue by nijave** [mozilla-mobile/fenix#26394]
For the last week or so with Firefox Nightly, I'll occasionally get a black box on the bottom portion of the screen. Switching out of the app and back displays the correct content

I think this may be triggered when Gboard is minimized (sometimes but not every time) but not positive if this is the only trigger. I haven't noticed this behavior on any other apps.

Phone is OnePlus 6T with LineageOS 11
Firefox 105.0a1 (Build #2015896491)

Images show the black box and the screen after switching to the home screen and back to Firefox
![Screenshot_20220809-164908_Firefox_Nightly](https://user-images.githubusercontent.com/384474/183759524-3868e2a5-e456-4054-9ef9-017cb43e6436.png)
![Screenshot_20220809-164914_Firefox_Nightly](https://user-images.githubusercontent.com/384474/183759542-3da16fbe-766f-4714-83c0-86e23c3288f4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21243)

**Comment by nijave** [comment]
Maybe https://github.com/mozilla-mobile/fenix/issues/26327

**Comment by ale82to** [comment]
exact same issue with lineage OS 18 ,latest nighlty 105 and swiftkey

**Comment by robog-two** [comment]
Not sure if this helps, but I've only seen the box appear when "starting" a new tab, as in, opening a fresh tab or searching in the current tab. The box disappears if the tab is closed, and (usually) does not reappear even if the same tab is opened.

Here is a screenshot ^ ^
![black box pictured at bottom of duck duck go search on a new tab](https://user-images.githubusercontent.com/77205106/184523499-96a174e4-52e4-4072-8285-794aa57d0edd.jpg)

**Comment by robog-two** [comment]
Not sure if this helps, but I've only seen the box appear when "starting" a new tab, as in, opening a fresh tab or searching in the current tab. The box disappears if the tab is closed, and (usually) does not reappear even if the same tab is opened.

Here is a screenshot ^ ^
![black box pictured at bottom of duck duck go search on a new tab](https://user-images.githubusercontent.com/77205106/184523499-96a174e4-52e4-4072-8285-794aa57d0edd.jpg)

Edit: further testing, scrolling does not affect it, and unfocusing and refocusing the app seems to clear it.

My black box disappeared again so I suppose I'll do some more investigating next time I see it. It's a fairly elusive occurence.

**Comment by CodingWatchCollector** [comment]
Same problem for more than a week. Latest Firefox nightly 105.0a1 , phone: oppo find x2 (cph2023_11_a_50) android 10, colorOS v.7.1

**Comment by kbrosnan** [comment]
duplicate bz-1783542

**Comment by clientenq** [comment]
Issue still exists in 105.0a1 (Build #2015899475), 77b959ec9+
AC: 105.0.20220821161547, 2706649f84
GV: 105.0a1-20220821091424
AS: 94.1.0

It appears when typing and submitting forms.
Sometimes very frequently, sometimes hard to repoduce.

**Comment by caugner** [comment]
@clientenq A fix has landed and should be in the next Nightly release., see: https://bugzilla.mozilla.org/show_bug.cgi?id=1783542
