### ISSUE TITLE
Tab pickup should respect the home screen blocklist.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26398]
The tab pickup section of Jump Back In (the recent synced tab) should make use of the home screen blocklist and prevent rendering tabs that have been blocked. This should be done by intercepting `AppAction.RecentSyncedTabStateChange` in `BlocklistMiddleware` and filtering the results based on the blocklist. 

In addition, the tab pickup section should then switch to using the next non-blocked tab from the recent synced tab list.

Dependent on: https://github.com/mozilla-mobile/fenix/issues/26399

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21245)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue by performing the following steps:
1. On the first device login with a Firefox account;
2. On the first device access any website;
3. From the Jump back in, Recent bookmarks and Recently visited sections long tap the website and select the remove option;
4. On a second device log in the same Firefox account from the first device;
5. Access same website from step 2;
6. Perform a sync on the second device;
7. Perform a sync on the first device;

After performing these steps the blocklist website did not appear in the sync tab tray, but the next non blocklist site.
### Devices used:
- Google Pixel 6 (Android 13
- Samsung Galaxy S22 (Android 12)
