### ISSUE TITLE
Recent synced tabs success states should include a list of tabs.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26399]
In order to achieve the behavior required in https://github.com/mozilla-mobile/fenix/issues/26398, the `RecentSyncedTabFeature` should be changed to update the AppStore with a list of recent tabs. This list should be ordered by the [lastUsed](https://searchfox.org/mozilla-mobile/rev/a7d1e928df75a76af53846f8bd90e1ce726dcbae/android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt#111) property of the tab. 

Note: there appears to be a bug in the current implementation when choosing the most recent tab. `device.lastAccessTime` does not seem to get regularly updated during long-running sessions. This is an issue, for example, with desktop devices where the browser is not often closed. 

Ordering this list as suggested above should resolve that issue as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21246)

**Comment by Alexandru2909** [comment]
@ QA: We should ensure that the after this refactoring the Recent synced tabs feature functions the same.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 2022-08-30 and the recent synced tabs feature works as intended.
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
