### ISSUE TITLE
[a11y] Consider making "Customise homepage" button from home screen, item larger

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26404]
### Steps to reproduce

1.Have the Accessibility scanner app installed and opened.
2.Launch Fenix.
3.Use the Accessibility Scanner and scan the Homepage. Observe the suggestion.

### Expected behaviour

Consider making this clickable item larger.  Consider making the height of this touch target 48 dp or larger.

### Actual behaviour

This item's height is 42dp.

### Device name

Sony Xperia 10 III 5G 

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

Firefox Beta 104.0b5  

### Additional information

![Screenshot_20220810-120258](https://user-images.githubusercontent.com/108326843/183861651-7a2d8b48-231e-45d6-a0f2-4bdd962e3a58.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21249)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809819

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
