### ISSUE TITLE
[Bug]: The latest synced tab is displayed in the Jump Back In section after signing out from another device

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#26407]
### Steps to reproduce

1. On a mobile device login in with a Firefox account and open a few tabs;
2. On a second device login with the same account and observe the homepage;
3. On the first device go to Settings->Account and Sign out;
4. Observe the home screen of the second device.

### Expected behaviour

At step 2 the last accessed tab from the first device should be displayed on the home screen but at step 4 it should disappear since the user logout from the other device.

### Actual behaviour

At step 4 the last accessed tab from the first device is displayed in the Jump back in section on the second device even though a sign out was performed on the first device.

### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 2022-08-10

### Additional information

https://user-images.githubusercontent.com/50983519/183890048-27b5fe5d-82f8-403d-a19f-24fad9c952c2.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21252)

**Comment by mcarare** [comment]
@LaurentiuApahideanSV Does this bug show up intermittently or every time for you?
I tried to reproduce it, but as soon as the sync is done and the tab disappears from the tabs tray list it also disappears from the home screen.
Can you check this again? Thank you!

**Comment by LaurentiuApahideanSV** [comment]
I retested the issue on Fenix Nightly 105.0a1 (2022-08-18) and the issue no longer occurs. After disconnecting from a device the sync card tab will disappear from all devices.
https://user-images.githubusercontent.com/50983519/185433623-313cc28e-854d-42e5-9a55-b48631dcebf1.mp4
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)

**Comment by mcarare** [comment]
Closing this, as per the comment above.
