### ISSUE TITLE
Remove metrics related to wallpaper toggling feature.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26401]
Once https://github.com/mozilla-mobile/fenix/issues/25985 is completed, the `wallpaper_switched` and `change_wallpaper_logo_toggled` metrics should be removed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21248)

**Comment by mcarare** [comment]
Fixed in https://github.com/mozilla-mobile/fenix/pull/26595.
