### ISSUE TITLE
Capture a telemetry event to understand how the Nimbus initialization correlated with the first page load

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#26411]
To guide the direction of https://github.com/mozilla-mobile/fenix/issues/26320, we will need to collect some telemetry data to understand, how the Nimbus initialization could influence the first page load, as we will want to experiment on features that need to be ready before the first page load.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21256)

**Comment by Amejia481** [comment]
We would like to capture how long it takes to load experiments relative to first page load.

For that we would need to capture three data point as one metric, on startup only this time.

1. When we starting the app (we already have it [here](https://github.com/mozilla-mobile/fenix/blob/fe25aa8e14fb6ded21f946e909d9d2ac63e1c4f2/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L119)))
2. When we load experiments experiments [here](https://github.com/mozilla-mobile/fenix/blob/fe25aa8e14fb6ded21f946e909d9d2ac63e1c4f2/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L441).
3. When we the first page start to load, for that we can use [AppRequestInterceptor](https://github.com/mozilla-mobile/fenix/blob/fe25aa8e14fb6ded21f946e909d9d2ac63e1c4f2/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt#L40) or create a new interceptor.

All this three events we will need to capture them as one metric.

**Comment by jonalmeida** [comment]
Filed [EXP-2941](https://mozilla-hub.atlassian.net/browse/EXP-2941) to add telemetry on the nimbus side so we get to see the measurements for only Nimbus initialization in fenix and focus.
