### ISSUE TITLE
Hide Sync button on synced tabs panel when users's not logged in

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#26410]
Please hide the sync FAB on the synced tabs panel when a user is not logged in. Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21255)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813826

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
