### ISSUE TITLE
Have the Pocket sponsored feature be part of the homescreen experiments

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26414]
Currently the Pocket sponsored feature is a Nimbus feature on it's own - https://github.com/mozilla-mobile/fenix/blob/main/.experimenter.yaml#L61.

It would make more sense to have the feature be part of the other homescreen sections already controllable through Nimbus - https://github.com/mozilla-mobile/fenix/blob/f356df785c6b179953ddb1a35907f1224c4377d3/.experimenter.yaml#L18-L20

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21258)

**Comment by Mugurell** [comment]
@ QA: For the moment we could test that the feature functions as before in debug. (it should still only be available in debug)

**Comment by SoftVision-LorandJanos** [comment]
Tested with the latest debug build (GV: 105.0a1-20220817091029).
Device used: Google Pixel 4 (Android 12).
Closing the ticket as fixed, and marking it as verified.
