### ISSUE TITLE
[Bug] Get location doesn't work on Android 6

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2641]
## Steps to reproduce
1. Turn on location on the device.
1. In Fenix, go to permission.site/ mapquest.com.
1. Tap to get the location. Allow permissions.
    1. Expected behavior
The location button turns green / Your location is detected.
    1. Actual behavior
The location is not detected. 
Checking the "don't ask again" checkbox doesn't stick until the system permission dialog is displayed.
The system permission dialog is displayed only the 2n or 3rd time after you tap Allow on the app doorhanger.

### Device information
* Android device: Nexus 5 & P9 lite (both Android 6), Xiaomi Mi4i (Android 5)
* Fenix version: 5/20

**Comment by Amejia481** [comment]
@sv-ohorvath 
I'm not able to simulate the same issue. I tested on a Nexus 5 (Emulator and physical phone) Android 6.
permission.site([video](https://drive.google.com/file/d/1LuLOQDjL_Ap1E91f-ciLiyaGnLqVoh_x/view?usp=sharing)) / mapquest.com([video](https://drive.google.com/file/d/1xB69TeGJIOKGmEjoGGXhkV-dw98bvBkj/view?usp=sharing))

**Comment by sv-ohorvath** [comment]
@Amejia481 I see it's working now, but it's buggy,  as described in #3207. We can close this one.
Verified on Galaxy Tab A 6 (Android 5.1.1), Nexus 5 (Android 6.0.1), HTC Desire 820 (Android 6.0.1)
