### ISSUE TITLE
Can't vsync at testufo.com

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#26418]
## Steps to reproduce
Go to testufo.com
Wait the phone to vsync

### Expected behavior
Phone with 90hz display locks the framerate to 90 and stays as is

### Actual behavior
**Can't lock the framerate to 90 and fluctuate around 85-88 while Brave can succesfully lock the framerate**
Interestingly **when i set phone to 60hz, it can't keep the framerate at 60fps either.**

### Device information
* Android device: Galaxy A52, Android 12
* Fenix version: Nightly a77375a36

### Profile
https://profiler.firefox.com/public/f5rarm267pef6x4vamtws5n9fvqrha4cq8k1b18

### Screenshots
90hz Firefox Nightly:
<img src="https://user-images.githubusercontent.com/17825767/183991335-2bb7b78f-a323-4cae-8e63-3c5f27dd4e14.png" width="250">
90hz Brave:
<img src="https://user-images.githubusercontent.com/17825767/183991342-61d609d2-478f-4b22-8169-a15da681846b.png" width="250">
60hz Firefox Nightly:
<img src="https://user-images.githubusercontent.com/17825767/183993487-66da03fd-d1c3-48df-ad61-4737590e740e.png" width="250">

Results from vsynctester.com:
Firefox
<img src="https://user-images.githubusercontent.com/17825767/183995614-a6657af4-5fa5-49da-961e-ffa61f60dfca.png" width="250">
Brave
<img src="https://user-images.githubusercontent.com/17825767/183995625-b40e5b7c-09a3-4ae1-90ba-b3336a8bdad5.png" width="250">

Note: I have fission enabled but disabling it not improves the situation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21261)

**Comment by hkaancaliskan** [comment]
As a side note: vsync works perfectly on Firefox windows (even better than chrome)

**Comment by MarcLeclair** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1788315

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by MarcLeclair** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1788316

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by mdrejhon** [comment]
View https://www.testufo.com/animation-time-graph 

TestUFO will decide VSYNC is unreliable if jitters is more than half a refresh interval away from the flat line.
