### ISSUE TITLE
Extract homescreen synced tabs into its own viewholder

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#26421]
As of now, recent synced tabs come under the same view holder as recent tabs (jump back in).
Separating into it's own view holder will help with easier use of it

Design : https://www.figma.com/file/hJfV1KGZuOK7OYr29pooL5/Synced-tabs?node-id=69%3A6540

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21265)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly and the synced tab is into it's own viewholder.
![Screenshot_20220817-175746](https://user-images.githubusercontent.com/50983519/185193157-008d617f-f962-4dbe-afdb-2e504c60d7e0.png)
![Screenshot_20220817-175936_Firefox Nightly~2](https://user-images.githubusercontent.com/50983519/185193160-19a95866-afbe-432e-b38d-0954fdb6f405.jpg)
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
