### ISSUE TITLE
[Bug]Search engine logo disappears from search bar

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/fenix#2642]
## Steps to reproduce
1. Open fenix.
1. Switch between the normal to private browsing and private to normal browsing.
    1. Expected behavior
Easy transition between both the modes. 
    1. Actual behavior
The search engine logo disappears for a second and then reappears. 
    1. Device information

* Android device: 8.0.0
* Fenix version: 1.0.1921 (Build#11400616 68.0a1-20190508111321)
    1. ScreenRecording
[fenixcast.zip](https://github.com/mozilla-mobile/fenix/files/3198049/fenixcast.zip)

**Comment by TitanNano** [comment]
To be specific, the search engine logo disappears for a moment.

**Comment by Scripterr** [comment]
Thanks for the correction i have edited the issue.

**Comment by abodea** [comment]
Note that I was able to reproduce this issue to on **`Samsung Galaxy Note 9 (Android 8.1.0)`** but somehow the text displayed over the search bar was more highlighted see the [Video](https://drive.google.com/file/d/19WnuHb5aqQFLYDhUuknPKhntTHeQCbXP/view?usp=sharing).

**Comment by sblatz** [comment]
This is likely far more noticeable on devices that have animations disabled, as we usually do a nice cross fade here 


The exact transition frame where it's gone:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/4400286/61327658-4b4dc400-a7ce-11e9-98f7-a802419d66b3.png">

**Comment by ekager** [comment]
Since we've redesigned the homescreen a bit is this still as noticeable/an issue to you all? I believe the issue is when we switch themes, we recreate and have to load the search icon. We could possibly cache it or have a placeholder so that it is less noticeable?

**Comment by sblatz** [comment]
Unfortunately this is still happening and noticeable IMO.

**Comment by s-ankur** [comment]
I am not seeing this anymore after the new search experience design
