### ISSUE TITLE
[Bug] Firefox Preview doesn't split a line of Thai string

### ISSUE THREAD

**Issue by veer66** [mozilla-mobile/fenix#2643]
## Steps to reproduce
1. Open https://file.veer66.rocks/servo_test/thai_line_break.html

### Expected behavior
The Thai string is split into 3 lines.

![ภาพ](https://user-images.githubusercontent.com/370688/58025683-2d057800-7b3f-11e9-85d2-5243c786e599.png)

### Actual behavior
Firefox Preview did _not_ break the Thai string into 3 lines.

![Screenshot](https://user-images.githubusercontent.com/370688/58025920-aa30ed00-7b3f-11e9-94d5-79a9e7792e45.png)UNITO-UNDERSCORE!2019-05-20-14-40-58-950!UNITO-UNDERSCORE!org mozilla fenix!

### Device information
* Android device: ?
Redmi Note 7
* Fenix version: ?
1.0.1921 (Build #11400616
68.0a1-20190508111321)

**Comment by kbrosnan** [comment]
As I mentioned in https://github.com/mozilla-mobile/reference-browser/issues/756 this is a Gecko bug and a bug needs to be opened in Bugzilla. If you don't get to it in a few days I will open one.

**Comment by makotokato** [comment]
> 
> 
> As I mentioned in [mozilla-mobile/reference-browser#756](https://github.com/mozilla-mobile/reference-browser/issues/756) this is a Gecko bug and a bug needs to be opened in Bugzilla. If you don't get to it in a few days I will open one.

Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1553725

**Comment by makotokato** [comment]
@kbrosnan could you close this since we move this issue to BMO?

**Comment by kbrosnan** [comment]
Thanks for the alert. Yes we can close this as it will be tracked in Bugzilla.
