### ISSUE TITLE
Problem with tables displayed on a website

### ISSUE THREAD

**Issue by redfox20236** [mozilla-mobile/fenix#26432]
### Steps to reproduce

Hi,
I've published through Wordpress a page with a comparator table at the top of it (see here : https://hellosafe.ca/investissement/crypto-monnaie/defi), designed to be both fitted for desktop and mobile.

### Expected behaviour

Actually, the page shows well on desktop, but the table looks very narrow on mobile, which is obviously terrible in terms of UX.

### Actual behaviour

The table should be well displayed on mobile version, and appear large with interference with the design

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

103.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21271)

**Comment by kbrosnan** [comment]
I don't see any obvious difference between this website in Chrome or in Firefox. Please provide screenshots showing the difference.

**Comment by kbrosnan** [comment]
Closing as incomplete.
