### ISSUE TITLE
Swiping back from a shared FireFox tab takes to the device home screen

### ISSUE THREAD

**Issue by indurs** [mozilla-mobile/fenix#26430]
@indurs Since we normally bring the user back to app's homescreen when there is no history left this scenario does warrant more investigation and feedback from UX but in a separate ticket since it's a preexistent behavior separate than the issue described here. Would you open a new ticket for it?

_Originally posted by @Mugurell in https://github.com/mozilla-mobile/fenix/issues/26037#issuecomment-1210824259_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21270)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812118

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
