### ISSUE TITLE
Cloudflare SSL certificate's Organization shows escaped comma

### ISSUE THREAD

**Issue by denschub** [mozilla-mobile/fenix#26438]
### Steps to reproduce

1. Open https://cloudflare.com
2. Click the Lock icon
3. Click the "Connection is secure" item to view the certificate's details

### Expected behaviour

"Verified by" should show `Cloudflare, Inc.`

### Actual behaviour

"Verified by" shows `Cloudflare\, Inc.`

### Android version

12

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 (2022-08-11)

### Additional information

I'm not entirely sure if this dialog is created via Fenix, or if this is an a-c issue upstream. I'll just file it here for now.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21274)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813827

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
