### ISSUE TITLE
Ability to use a different app for file uploads

### ISSUE THREAD

**Issue by glodomorrapl** [mozilla-mobile/fenix#26433]
right now, Fennec seems to forcibly use the Documents app (com.android.documentsui), which usually works fine, until it doesn't. this app can become very slow to start in certain unexplained situations, and the app itself is basic, which can be a hinderance. other file managers have more useful options, like access to more kinds of remote storage, as well as basic file operations (like renaming, which tends to get useful if the file's name causes the site, or Fennec itself, to use the file)
if this is already a feature, then I can't find it anywhere.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21272)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812117

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
