### ISSUE TITLE
FNX3-16480 ⁃ [Bug] The pairing instructions dialog UI doesn't match the general design

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2644]
## Steps to reproduce
1. Go to Settings>Sign in>Scan code
1. Observe the dialog. Compare with the permissions dialogs for e.g.
    1. Expected behavior
The design should match the general UI.
    1. Actual behavior
The buttons don't match the general UI.
    1. Device information

* Android device: Note 8 (android 9)
* Fenix version: 5/20
![Screenshot](https://user-images.githubusercontent.com/4037709/58026181-8f9a4c00-7b1e-11e9-9f9b-e39fca8cfe88.jpg)UNITO-UNDERSCORE!20190520-153841!UNITO-UNDERSCORE!Firefox Preview!

**Comment by sblatz** [comment]
We should polish this design to look like this: https://github.com/mozilla-mobile/fenix/issues/2324#issuecomment-490270825

**Comment by ekager** [comment]
Invision Mock for this dialog:
<img width="360" alt="Screen Shot 2019-05-21 at 11 23 03 AM" src="https://user-images.githubusercontent.com/25442310/58120820-dd649200-7bba-11e9-9822-dff4d10e33e5.png">

**Comment by sv-ohorvath** [comment]
The current UI is close but not the same, also different from the permissions dialog:
- needs a space between the text and buttons
- the "open camera" button looks much bigger than the Allow/Allways button
![Screenshot_20190606-120314](https://user-images.githubusercontent.com/4037709/59021000-b7461f80-8853-11e9-8d2f-d0b99347e7b5.png)

**Comment by ekager** [comment]
Will be outdated by implementing #3237

**Comment by softvision-miralobontiu** [comment]
On the latest Nightly build 190718 (#11990608), the Invision Mock for this dialog is not displayed at all.
<img width="360" alt="58120820-dd649200-7bba-11e9-9822-dff4d10e33e5" src="https://user-images.githubusercontent.com/40694158/61444967-1cae2580-a955-11e9-8cea-462fce2f6021.png">

The app only requires this allowance:

![Screenshot_20190718-121223](https://user-images.githubusercontent.com/40694158/61445222-a3fb9900-a955-11e9-8e14-78bf18e18967.png)

On permission.site, the instruction dialog is displayed like this:
![Screenshot_20190718-120248](https://user-images.githubusercontent.com/40694158/61445232-ab22a700-a955-11e9-8d4d-2a67ec422d70.png)

Tested with Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8), Google Pixel 3 (Android 9).
