### ISSUE TITLE
Feature Flag for Wallpapers V2 Onboarding

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26446]
As a Product Manager, I want the new wallpaper selection tool behind a Nimbus pref, so that I can run an A/B test to determine the impact it makes to wallpaper usage

### Acceptance Criteria
- Feature flag in place for Wallpapers v2 onboarding that can be controlled through Nimbus
- Default setting is off

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21278)

**Comment by delia-pop** [comment]
Hi, @mavduevskiy, is this something QA should check, given a similar ticket, https://github.com/mozilla-mobile/fenix/issues/26308, in which the QA Needed label was not added? Thanks!

**Comment by Alexandru2909** [comment]
With the context given by @delia-pop's comment I believe we can close this with the qa:not-needed label.
