### ISSUE TITLE
Home screen text should use values associated with wallpapers

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26444]
In https://github.com/mozilla-mobile/fenix/pull/26281 we added the ability for the home screen header and link text to react to whether a wallpaper was set. 

After https://github.com/mozilla-mobile/fenix/issues/26423 is resolved, there should be metadata available for each individual wallpaper describing whether light text or dark text should be used to overlay the wallpaper. The implementation should be updated to:

- access the text color property available on the current wallpaper and apply it when the current wallpaper is updated

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21277)

**Comment by delia-pop** [comment]
Verified as fixed with latest Debug build updated from main. We will re-test this on Nightly when available.
Tagging UX to confirm this is the expected design.

![Debug WAllpaper](https://user-images.githubusercontent.com/89388888/187941053-3b3721f4-2529-4eef-8046-016f2edd81ff.jpg)
