### ISSUE TITLE
Remove the star icon from Pocket sponsored stories

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26450]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21199)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on a Fenix Debug build 1.0.2236 (2022-09-01). I installed Windscribe on the device and set the location to Las Vegas USA. The star is not present for Pocket sponsored stories. I will leave the qa:needed label until the issue can be verified on Nightly.
![Pocket_Sponsored](https://user-images.githubusercontent.com/50983519/187918423-37af583b-6469-4065-84a1-bf3385617eb5.jpeg)

### Devices used:
- Samsung Galaxy S22 Ultra (Android 12)
- Google Pixel 6 (Android 13)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807371

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by SoftVision-LorandJanos** [comment]
As this is moved to bugzilla, I will remove the QA-needed label from this ticket.
