### ISSUE TITLE
Exit private mode when last private tab is closed

### ISSUE THREAD

**Issue by Mel34** [mozilla-mobile/fenix#26458]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently the browser remains in private browsing mode after the last private tab was closed. It would be nice if the browser behaved like chrome or heck, even desktop firefox, and went into standard browsing mode when the last private tab is closed.
### How do you know that this problem exists today? Why is this important?
Since the browser stays in private mode without any tabs, user has to either open a new private tab or switch to non-private mode. Typical use case is wanting to go back to non-private mode after the last private tab is closed, which is exactly how desktop firefox behaves.
### Who will benefit from it?
If private mode ends with last private tab being closed, users of chrome(like) browsers and users of desktop firefox would feel more at home.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21294)

**Comment by topotropic** [comment]
Thanks for the feedback! 

Mobile has different use cases compared to desktop and the assumption that people want to go back to non-PBM once they closed the last private tab should be validated first. We’ll make sure to consider it. Thanks again!

**Comment by fice-t** [comment]
@topotropic Should this be closed? Leaving it opening seems appropriate if the feature will be under consideration.

Alternatively, what about making this behaviour optional? That way there won't have to be a hard assumption made about what the user wants.
