### ISSUE TITLE
Immediately close a tab after sending it to another device

### ISSUE THREAD

**Issue by tidoni** [mozilla-mobile/fenix#26461]
## User Story
- As a user, I want want to immediately close a tab after i have send it to another device

### Acceptance Criteria
- I can close a tab immediately after sending it, instead of having to wait for the "Tab send" message to disappear

Video shows the current behavior, where the "tab overview" is not accessible until the "Tab send" message disappears

https://user-images.githubusercontent.com/24697188/184495950-4e99cea6-ba3c-462d-afd2-c802f87f8378.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21297)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810846

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
