### ISSUE TITLE
[Bug]: firefox android left black space in keyboard place after typing

### ISSUE THREAD

**Issue by meanssaddles** [mozilla-mobile/fenix#26460]
### Steps to reproduce

with firefox android nightly 105.0a1 (Build #2015897547), 33406ac24+

and Gboard (google kayboard) app

1. go to any page to input text

2. type something then press  -> button on keyboard or back button to close keyboard 

3. the keyboard doesn't closed as it should but left a black space in its place

### Expected behaviour

keyboard closed normally 

### Actual behaviour

firefox left black space in keyboard place 

image: https://media.discordapp.net/attachments/813042041739149363/1007936004948230184/Screenshot_2022-08-13-15-44-22-297_org.mozilla.fenix.jpg

https://media.discordapp.net/attachments/813042041739149363/1007936004633677905/Screenshot_2022-08-13-15-43-33-941_org.mozilla.fenix.jpg

### Android version

android 11

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21296)

**Comment by kbrosnan** [comment]
Duplicate bz-1783542
