### ISSUE TITLE
[Bug]:1/3 Of Screen Goes Black 

### ISSUE THREAD

**Issue by shawon2901** [mozilla-mobile/fenix#26467]
### Steps to reproduce

Its Random But Switching From FireFox Browser To Other Apps,Vice-Versa Or Going To My Launcher To Then Going To FireFox Again...

Although Again Switching Apps Fixes It

Another Way - Keyboard Minimizing Related Actions Also Cause It

### Expected behaviour

The Browser Screen Shouldn't Go Black

### Actual behaviour

1/3 Of Browser Screen Goes Black

### Device name

poco x3 pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

### Additional information

![Screenshot_2022-08-12-02-49-49-516_org mozilla fenix](https://user-images.githubusercontent.com/40642163/184545172-36e87950-227c-4325-aa9f-c33775ddf2c5.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21299)

**Comment by kbrosnan** [comment]
Duplicate bz-1783542. Will be fixed in v105
