### ISSUE TITLE
Open Tab won't load or load new url if left open

### ISSUE THREAD

**Issue by Midnitte** [mozilla-mobile/fenix#26468]
### Steps to reproduce

1. Open a tab
2. Leave the app and do something else on your phone
3. Open the app again
4. Try to enter a new url

### Expected behaviour

The tab should load the original website, and then load any new url entered

### Actual behaviour

The tab just stays blank

### Device name

Samsung Galacy S22 Ultra

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

103.2.0 (Build #2015895963), e0d3c03af+ AC: 103.0.10, 4ab756c4b5 GV: 103.0.2-20220802163236 AS: 93.5.1

### Device logs

https://crash-stats.mozilla.org/report/index/eecf7ec6-2552-4f21-b0f3-ba1610220725

### Additional information

I have recorded a video of the behavior [here](https://drive.google.com/file/d/1Nzv0ogsMzIuvRCX0rWvd_E9ChWPhwzYP/view?usp=drivesdk).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21300)

**Comment by kbrosnan** [comment]
The crash you linked was from v102 and was fixed in v103 (bz-1772839). I suspect it is unrelated to what you are describing. 

Logcat while reproducing the problem may print something to the error log. To set up logcat see https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information#using-adb-logcat-to-get-crash-information

**Comment by Midnitte** [comment]
Gotcha, will see of I can capture the behavior/logs. It does seem to be intermittent.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812127

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
