### ISSUE TITLE
"Autofill in Firefox" toggle doesn't actually seem to do anything

### ISSUE THREAD

**Issue by KWierso** [mozilla-mobile/fenix#26465]
### Steps to reproduce

Go to Settings > Logins, then toggle off "Autofill in Firefox"

Visit some site with a login form.

Focus on the username/email field in that form. 

### Expected behaviour

When the keyboard pops up, there should not be a "suggested logins"  component above the keyboard. 

### Actual behaviour

The "suggested logins" component is still shown. 

### Device name

Galaxy s22

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

105.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21298)

**Comment by mrbiglyshoes** [comment]
Reporting same issue on all 3 versions.  Autofill not prompting after enabled.  Tested on

https://www.roboform.com/filling-test-all-fields

Galaxy S21
Using Bitwarden

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813828

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
