### ISSUE TITLE
Clarify the differences between recently visited or jumped in

### ISSUE THREAD

**Issue by Swastinaik** [mozilla-mobile/fenix#26473]
It's seems bit confused why there are two different ways for same result.
Please make it clear or integrate both of them. as anyone from non tech background for whom chrome and Firefox are alike mozilla should make it more simple and aesthetics.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21304)

**Comment by amocirean** [comment]
Hello @Swastinaik  ,
Thank you for your suggestion. We will add the Feature Request label to this issue.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813829

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
