### ISSUE TITLE
[Bug]: Sync take too long

### ISSUE THREAD

**Issue by maxso-216** [mozilla-mobile/fenix#26471]
### Steps to reproduce

1. Set up your firefox sync account
2. Have a lots of tab open on other device and sync (I'm not sure if you need a lots of tabs opened to reproduce this issue)
3. Login to your firefox account and sync
4. If the device successfully sync in few seconds, force stop firefox and reopen account setting 
5. Click sync now 
6. Sometimes, it's very lucky it's successfully synced, then repeat step 4.

### Expected behaviour

It should be sync in seconds

### Actual behaviour

It take a lot of time (from minutes to even an hour) to sync

### Device name

Xpedia XZ1

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

### Device logs

This is a successful log that sync in seconds
https://gist.github.com/maxso-216/2cd19c3bd50b76202091c7272a295549
This is a log for sync that takes ~2 minutes to sync. I think I click sync now around at line 8000 and have to wait few minutes to let it sync
https://gist.github.com/maxso-216/1d4b193566188319afba84a189767839

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21302)

**Comment by kbrosnan** [comment]
Talked with the Sync team and they believe this is an instance of https://github.com/mozilla/application-services/issues/3176
