### ISSUE TITLE
Move Tabs Tray to Compose: Tab Reordering

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#26476]
Blocked by:

- https://github.com/mozilla-mobile/fenix/issues/21899
- https://github.com/mozilla-mobile/fenix/issues/21901
- https://github.com/mozilla-mobile/fenix/issues/21896

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21306)

**Comment by Dakkaron** [comment]
Thanks a lot for opening this issue. Manual tab reordering is essential for e.g. comparing products. I currently have to use Vivaldi for online shopping. Would be good if I could go back to a single mobile browser.

**Comment by marcel263** [comment]
> Thanks a lot for opening this issue. Manual tab reordering is essential for e.g. comparing products. I currently have to use Vivaldi for online shopping. Would be good if I could go back to a single mobile browser.

dear,
tab reordering is right now present in firefox nightly. this issue ticket is about rewriting the code for their improved browser component, which is mostly for technical reasons.
So if you need tab reordering and you are willing to try it, you can try the nightly build.

**Comment by Dakkaron** [comment]
@marcel263 
Please see the linked issue here: https://github.com/mozilla-mobile/fenix/issues/26289

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810780

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
