### ISSUE TITLE
FNX3-16483 ⁃ [Bug] Match desktop trimming of url hostname

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2648]
We should trim the host url's like we do on desktop. Currently we're just trimming the first and last dots from the hostname, but that doesn't match our desktop implementation and could lead to confusing url's. 

Example of mana.mozilla.org:
![image](https://user-images.githubusercontent.com/4400286/58031759-efb8d000-7ad5-11e9-96c1-2a1c5021a2de.png)

## STR:
1. On the home view, the url host names of the tabs should match what is displayed on desktop.

**Comment by sblatz** [comment]
See desktop code: https://searchfox.org/mozilla-central/source/browser/components/newtab/lib/ShortURL.jsm#44-68

**Comment by pocmo** [comment]
FYI: `getETLD()` and others are provided by `lib-publicsuffixlist`

**Comment by sblatz** [comment]
Also helpful: https://github.com/mozilla-mobile/android-components/blob/1a98ef0ddd3d99b170a4dab4c529e096f2bf6f47/components/lib/publicsuffixlist/src/test/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListTest.kt#L15

**Comment by myakura** [comment]
Could it just show an origin (possibly sans `www.` or `m.`)? Dropping top-level domain sometimes shows really confusing or meaningless strings for URLs like:

* [`www.yahoo.co.jp`](https://www.yahoo.co.jp/) ― becomes `yahoo.co` but there's the `.co` TLD so it's misleading
* new company-related TLDs ([`blog.google`](https://blog.google/) or [`jp.sharp`](https://jp.sharp/)) ― become `blog` or `jp` which are really useless
* `example.co.jp` ― becomes `co`... ouch.

**Comment by sarentz** [comment]
@sblatz for IP addresses `a.b.c.d` we should not do any trimming at all.

**Comment by cpeterso** [comment]
Related Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1554984

**Comment by sblatz** [comment]
@csadilek and I paired on this for a bit. We're going to move forward with using `stripPublicSuffix` from the PublicSuffixList, and also trimming the "www" portion like desktop does.

Note this is done asynchronously, but URLRenderer actually [runs this job on the main thread](https://github.com/mozilla-mobile/android-components/blob/51ef74db39a20fc76d62775db0f2039a6d0959bd/components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/internal/URLRenderer.kt#L36-L42)... should I just pattern match that, @pocmo?

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1923 (#11590615), with Samsung Galaxy Tab A6 (Android 5.1.1), and Motorola Nexus 6 (Android 7.1.1).
