### ISSUE TITLE
form data save and fill 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26485]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Unlike desktop browser or other chromium browsers, firefox android is not saving form data . For example in any courier tracking site after entering the AwB number it is not saving it , so next time it is not showing the AwB number

### How do you know that this problem exists today? Why is this important?
Firefox android should save form data like other browsers or even like firefox desktop

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21308)

**Comment by jonalmeida** [comment]
We do save form data, so this sounds like a bug report but there isn't much information to work on from here. Closing for now until we can get reliable STR.
