### ISSUE TITLE
[a11y] "Connection is secure" option isn't selected along with the icon

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26487]
### Steps to reproduce

1. Enable voice assistant or talkback.
2. Using TB gestures, open a page, and tap on the "lock" icon from the navigation bar.
3. Observe the selection of the "Connection is secure" option.

### Expected behaviour

All the options are selected along with the icon.

### Actual behaviour

The "Connection is secure" option is selected without the icon - see the screenshot below.

### Device name

Xiaomi Pad5 

### Android version

Android 11

### Firefox release type

Firefox Beta

### Firefox version

Firefox Beta 104.0b5

### Additional information

![1660636272828](https://user-images.githubusercontent.com/108326843/184829190-c5ee737b-cc5b-4f35-963a-bc2dd5b6d28f.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21309)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807592

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
