### ISSUE TITLE
Synced Tab Pickup Onboarding Message

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#26489]
## Description
When I open the homepage after leaving a tab open on another device, I see a message pointing out that tab, so that I understand where the tab is coming from and that I’m able to easily move between devices using this feature

## Dependencies
- List dependencies on other issues/teams etc.

### Acceptance Criteria

- A Synced Tab Pickup pop up message will be displayed on the homepage under the following the conditions:
        
        The user has an open tab from a synced device in Jump Back In

        They have not seen the Synced Tab Pickup message before (unless they reinstall the app)

-     If the user clicks on the X to close the message or clicks elsewhere on the homepage, then the message will close

-     The pop up message matches the [attached designs](https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?node-id=1950%3A64966)

-     The message is behind the MR Onboarding Nimbus feature flag

-     The following telemetry is captured:

        Impression counts 

        Click counts on the X

        Clicks elsewhere on the screen that close the message are counted

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21310)

**Comment by delia-pop** [comment]
Verified as fixed with latest Debug build updated from main locally with Google Pixel 6 (Android 13). We will re-test this on Nightly when available.

<img src="https://user-images.githubusercontent.com/89388888/188493170-10078590-42dc-40be-8c72-926c2dcc9e7d.jpg" width="40%" />
