### ISSUE TITLE
Move Huawei device check from HomeActivity to ManufacturerCodes

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#26495]
This bit of code should live in the same place that all the other manufacturer checks are currently happening.

https://github.com/mozilla-mobile/fenix/blob/ab306f0ab9a1fce6dbf5d94f6c47d2828dac73f7/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L620

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21312)

**Comment by Alexandru2909** [comment]
Small, straightforward refactoring, removing the QA flag and adding qa:not-needed.
