### ISSUE TITLE
When an item is removed from home, it should also be removed from tab pickup

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26492]
If an item is removed from any of:
- Jump Back In
- Recent bookmarks
- Recent history

then it should also be removed from tab pickup (recent synced tab) if it is present there. This can be easily reproduced by:
1. have a tab available in tab pickup
2. open the tab
3. tab should be available in jump back in
4. remove tab from jump back in

Current behavior: the tab will remain in tab pickup. 
Expected behavior: the tab is removed.

See comment https://github.com/mozilla-mobile/fenix/pull/26486#pullrequestreview-1074495017 for additional context

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21311)

**Comment by Alexandru2909** [comment]
The scope of this issue will be handled in https://github.com/mozilla-mobile/fenix/pull/26509.

**Comment by Alexandru2909** [comment]
Since #26509 has been marked closed, we can verifiy this ticket too. Adding QA:needed label.

**Comment by Alexandru2909** [comment]
Additional details for QA: 
We want to check that whenever a site is present in both:
 - the `Jump back in` section from the homescreen as a synced tab;
 - the `Recently saved`, top sites, jump back in non-synced tabs sections from the homescreen;

and it is removed from the one of these sections (added to the homescreen blocklist), then it should also be removed from the `Jump back in` synced tabs section.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 106.0a1 (2022-08-29) build.
The recently synced tab from the jump back in section that was also recently saved, is removed from all the above mentioned sections.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
