### ISSUE TITLE
[Bug] "stop load" icon does not switch to "reload" icon when 3 dot menu is open

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#2649]
open 3 dot menu
hit reload
3 dot menu disappears
while the page is loading hit 3 dot menu again to re-open it
watch the "stop load" X button
it doesn't change to a "reload" button when the page load completes
I have to close the 3 dot menu and re-open it to see the reload icon

expected behavior:- "stop load" changes to "reload" when page load completes, even if 3 dot menu is open.

* Android device: Galaxy S7, Android 8.0
* Fenix version: today's

**Comment by boek** [comment]
Dup of #654, feature request in A-C mozilla-mobile/android-components#170
