### ISSUE TITLE
[Bug] "stop" icon does not revert to "reload" icon after page load is stopped

### ISSUE THREAD

**Issue by Cheap-Skate** [mozilla-mobile/fenix#2650]
See also #2649, might be same bug

open 3 dot menu
hit reload
3 dot menu disappears
while page is still loading:-
re-open 3 dot menu and hit "stop load" X button
"stop load" X button does not revert to "reload" button even if I close & re-open 3 dot menu, it stays at X indefinitely

Expected behavior:- "stop load" should revert to "reload" after page load is stopped

* Android device: Galaxy S7, Android 8.0.0
* Fenix version:  today's

**Comment by bifleming** [comment]
Dup of an a/c issue:

**Comment by sblatz** [comment]
Dup of #654, feature request in A-C mozilla-mobile/android-components#170
