### ISSUE TITLE
Telemetry: Open History Item

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26502]
Questions to answer:

- How often is a local history item opened
- How often is a synced history item opened

Proposed metrics:

- Add a label to the existing history.open_item that identifies what type of history item it was

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21315)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 105.0a1 2022-08-21 by opening local and synced history items and observing the result.
When a local history website is accessed
{
          "timestamp": 35426,
          "category": "history",
          "name": "opened_item",
          "extra": {
            "is_remote": "false"
          }
When a synced history website is accessed
{
          "timestamp": 11760,
          "category": "history",
          "name": "opened_item",
          "extra": {
            "is_remote": "true"
          }
### Device used:
-OnePlus 6T (Android 9)
