### ISSUE TITLE
[Bug]: Order of devices in 'Send to device' changes randomly

### ISSUE THREAD

**Issue by Frederick888** [mozilla-mobile/fenix#26500]
### Steps to reproduce

1. Register more than one devices of the same type in Firefox account (two desktops in my case)
2. Have a tab open in Firefox Android
3. Click on kebab menu
4. Click on share button
5. Order of the devices changes from time to time

### Expected behaviour

Order of devices stays stable, e.g. alphabetical order.

### Actual behaviour

Order of devices changes from time to time.

This started recently so it's probably a regression or something new.

### Device name

Sony Xperia 1 iii

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

103.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21314)

**Comment by mcarare** [comment]
AFAIK the devices in that list are ordered according to the last time they were accessed.

**Comment by kbrosnan** [comment]
The devices are ordered by activity. We don't plan on ordering it alphabetically.

**Comment by Frederick888** [comment]
@kbrosnan May I know if this is something new?
