### ISSUE TITLE
[Bug]: "Add to Home screen" icon is blurry 

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#26505]
### Steps to reproduce

1. Navigate to https://www.smn.gob.ar/
2. Open browser settings.
3. Tap "Add to Home screen" option.
4. After the popup is displayed, tap "Add" button.
5. Observe the site icon. 

### Expected behaviour

The icon is displayed in full resolution.

### Actual behaviour

The issue is blurry.

### Device name

Google Pixel 5, Samsung Galaxy S8

### Android version

Android 12, Android 9

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 (🦎 105.0a1-20220816095503)

### Additional information

1. The issue is not reproducible on Opera.
2. The issue i also reproducible on Firefox Release 103.2.0 (🦎 103.0.2-20220802163236)
3. This was previously reported here https://github.com/webcompat/web-bugs/issues/109157
4. Screenshot attached.
![BlurryIcon](https://user-images.githubusercontent.com/12184325/185085757-520610f4-340d-40a1-8e1c-dbdd3ce13f02.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21317)

**Comment by SoftVision-LorandJanos** [comment]
I can confirm this issue is reproducible on the latest Nightly 105.0a1 (2022-08-18) build.
Device used: Oppo Find X5 (Android 12).

**Comment by Arbakato** [comment]
The website seems to be pushing [favicon.ico](https://www.smn.gob.ar/favicon.ico) instead of [icono.ico](https://www.smn.gob.ar/sites/all/themes/smn/images/icono.ico) for some reason?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807103

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
