### ISSUE TITLE
[Bug]: Wallpaper loading on launch is delayed

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26511]
### Steps to reproduce

1. Install the latest Nightly 105.0a1 from 08/17 or Update the app to the latest version and perform a clear data.
2. From Settings > Homepage > Opening screen select "Homepage".
3. From Settings > Homepage > Wallpapers select any wallpaper.
4. Close and Re-open Fenix. 
5. On start-up, observe the wallpaper on the homepage.

### Expected behaviour

The wallpaper loads without visual issues or significant delay, given a good and stable network connection. 

### Actual behaviour

The wallpaper loading on homepage is delayed with 1-3 seconds when launching the app, even with a good and stable network connection.
The issue occurs after every restart, not only the first launch. 

### Device name

Xiaomi 12 Pro

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest Nightly 105.0a1 from 08/17 

### Additional information

Also reproduced with: Samsung Galaxy A32 (Android 11), Samsung Galaxy S22 Ultra (Android 12), Lenovo Yoga Tab 11 (Android 11).

https://user-images.githubusercontent.com/89388888/185162020-4c023311-7032-4a2c-836b-d7ae3b0ac62a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21318)

**Comment by SoftVision-LorandJanos** [comment]
I've tried to verify this issue, and I was blocked by a crash: #26723.
Tested on the latest Nightly 106.0a1 (2022-08-31).
Device used: Oppo Find X5 (Android 12).
Removing the QA:needed label until the crash will be fixed.

**Comment by delia-pop** [comment]
https://github.com/mozilla-mobile/fenix/issues/26723 is verified as fixed on the latest Nightly 106 updated from main locally. The app no longer crashes on startup when a wallpaper is selected.

However, in the locally updated Nightly build, this issue is still reproducible: after launching the app, the wallpaper is still displayed with a short delay. Talked to @Mugurell and we will wait for the official Nightly build containing the fix for the #26723  crash to become available on PlayStore of task index, and re-test this.

**Comment by Mugurell** [comment]
Running on an IO thread and then switching to Main with a simple
> Handler(Looper.getMainLooper()).postAtFrontOfQueue 

[here](https://github.com/mozilla-mobile/fenix/blob/93859d8560331a2f69ef0980bef0605ea9b917a9/app/src/main/java/org/mozilla/fenix/home/WallpapersObserver.kt#L92-L93) does show a 50-100ms delay for just starting the runnable execution while if remaining with IO it's basically instant. But of course we should not update Views from other threads (curious that is works).

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/20 with Google Pixel 6 (Android 13). The wallpaper set is displayed on homepage as soon as the app is opened, and the user does not notice a delay any more. 

https://user-images.githubusercontent.com/89388888/191443395-9bacdb5d-e666-44b3-878f-fcf3d6b04999.mp4
