### ISSUE TITLE
Consider Importing Firefox OS/B2G UX to Fenix

### ISSUE THREAD

**Issue by reinhart1010** [mozilla-mobile/fenix#2651]
Here are some FxOS UX and features I requested to be available in Fenix:

1. Site icon shown in address bar.
![screenshot](https://i.imgur.com/YaY2jJk.jpg)
1. Minimized Collections (in Fenix) show an array of site icons, so users can quickly locate Collections based on icon arrangement. In Firefox OS this is shown for minimized section of app drawer.
![screenshot](https://i.imgur.com/c3KhFJ4.jpg)

1. Interactive site previews, possibly implemented in Fenix main screen or as a homescreen widget.
![screenshot](https://i.imgur.com/YmOmxdS.jpg)

The latter one can be potentially used as:

* favorites/bookmarks list
* low-priority web notification center
* shared tabs list from Sync
* RSS/Atom reader (though this has been removed from Firefox desktop)
* integration with other Firefox products, e.g. pinned notes from Firefox Notes and sent file widget from Firefox Send

**Comment by sarentz** [comment]
These are great suggestions. We are going to close this bug but keep it on file.
