### ISSUE TITLE
Enable users to toggle feature flags

### ISSUE THREAD

**Issue by Dakkaron** [mozilla-mobile/fenix#26514]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Currently, some features are only available in the Nightly version. Running the nightly version as a daily-driver might have some downsides though.

It would be really cool if I, as a user, could enable specific feature flags on the main version, using a hidden page, like about:config.

### How do you know that this problem exists today? Why is this important?

I could decide for myself which mix of experimental features I'd like to run. Right now that would e.g. enable me to enable manual tab sorting on the release version. This feature has been Nightly-only for about a year, and it's really important to me.

### Who will benefit from it?

Any power user who wants to try experimental features without running Nightly as a daily driver.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21320)

**Comment by amocirean** [comment]
Hello @Dakkaron ,
Thank you for your suggestion. We will add the Feature Request label to this issue.

**Comment by cadeyrn** [comment]
There is already a secret settings screen for features that are stable enough to be tested by the Non-Nightly population. I would argue that if Mozilla restricts a feature to Nightly-only, there are reasons for that (= not yet ready to be tested by a wider audience).

**Comment by Dakkaron** [comment]
> There is already a secret settings screen for features that are stable enough to be tested by the Non-Nightly population. I would argue that if Mozilla restricts a feature to Nightly-only, there are reasons for that (= not yet ready to be tested by a wider audience).

I understand what you mean. On the other hand, the tab reordering feature has been done and available in nightly for almost a year now. From the discussions in a few issues here on Github, there are quite a few people who are using Nightly as a daily-driver browser, even though it might be instable, just to get this one feature.

Wouldn't it be better to allow users to chose the amount of instability they need? As in, a user might really want to use feature X and would accept the risk that comes with using this experimental feature. But they might not want to take the risk of all the other things on Nightly, that could break their user experience.

**Comment by kbrosnan** [comment]
There were some complications around tab reordering. Tab search grouping which was disabled about a month ago conflicted with reordering. Second we wanted to do some code cleanup and modernizing in that area. 

We would not use the secret settings to pre-release a feature, that is what beta and nightly are for.
