### ISSUE TITLE
Wallpapers: Apply Wallpaper.cardColorLight and Wallpaper.cardColorDark to Homepage backplating 

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#26520]
**Dependencies** 
- https://github.com/mozilla-mobile/fenix/issues/26423
- https://github.com/mozilla-mobile/fenix/issues/26519
- https://github.com/mozilla-mobile/fenix/issues/26796
- https://github.com/mozilla-mobile/fenix/issues/26797
- https://github.com/mozilla-mobile/fenix/issues/27094
- https://github.com/mozilla-mobile/fenix/issues/27095
- https://github.com/mozilla-mobile/fenix/issues/27388
- https://github.com/mozilla-mobile/fenix/issues/27396

The backplates on the homepage should be driven by the colors returned from the wallpaper metadata JSON. There will be a color to be used for the light theme and a color for the dark theme.

**The following components will have their background colors adapted**
- Top Sites
- Jump Back In / Recent Tab
- Recent synced tab
- Recently visited
- Recent bookmarks
- Pocket stories
- Pocket categories
- Customize homepage button

**There is special logic for the following components**
- Customize homepage button receives the same card color treatment when a wallpaper is selected
- Pocket category cards
  -  Dark (device theme)
      - Selected is dark
      - Unselected is light
  -  Light (device theme)
        - Selected is light
        - Unselected is dark
- Pocket category text
  -  Dark (device theme)
      - Selected is textActionPrimary
      - Unselected is textActionSecondary 
  -  Light (device theme)
        - Selected is textActionSecondary 
        - Unselected is textActionPrimary 
- Recent synced tab button
  - If there is a wallpaper, use Layer1. If there isn't a wallpaper, use the default color.

If either card color color does not exist for a wallpaper (null from the metadata), the default colors will be used.

[Figma](https://www.figma.com/file/d7l1iGabQYqnLcnQbHDGzM/Wallpaper-2.0-%2B-Onboarding-v106?node-id=7220%3A202486)

Note: Turning Red legacy wallpapers will be covered in:
- https://github.com/mozilla-mobile/fenix/issues/27331

Further follow-up
- https://github.com/mozilla-mobile/fenix/issues/27468
- https://github.com/mozilla-mobile/fenix/issues/27469

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21323)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 108.0a1 from 11/02 with Samsung Galaxy Note10 (Android 12). Except for the Collections placeholder button and the messaging banner which were not yet changed, the backplates on the homepage assets are displayed accordingly.

![wallpapers](https://user-images.githubusercontent.com/89388888/199498465-d2659cd6-13f0-4cf6-abea-af6047be0e47.png)

**Comment by delia-pop** [comment]
This is also verified as fixed on Beta 109.0b1 with Motorola Moto G30 (Android 12).
