### ISSUE TITLE
Please add F5 support to mobile; everyone has had wireless keyboards for decades. no text

### ISSUE THREAD

**Issue by ETERNALBLUEbullrun** [mozilla-mobile/fenix#26522]
https://www.lifehack.org/561663/wen-shan-how-not-using-keyboard-shortcut-make-you-lose-64-hours-every-year

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21327)

**Comment by ETERNALBLUEbullrun** [comment]
Can I submit a pull request and expect it to be merged -- or would I be wasting my time?

**Comment by cadeyrn** [comment]
> everyone has had wireless keyboards for decades

Nope.

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/3729

I believe we would take a PR for adding keyboard shortcuts.
