### ISSUE TITLE
sync pinned sites and collection using bookmark 

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26525]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Currently pinned sites and collections are not synced probably because Mozilla thinks it requires new sync features. Vivaldi has top sites as speed dials features but those are stored in a dedicated bookmark folder called speed dials

Similarly I feel Mozilla can have 1 dedicated folder under bookmarks for top sites and 1 dedicated folder called collection which will have subfolder depending on multiple collection.

These special folders under bookmarks can be synced as per current sync architecture only without requiring any major change.

What do you think?

### How do you know that this problem exists today? Why is this important?
Difficult make collection again..too frustrating 

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21328)

**Comment by LaurentiuApahideanSV** [comment]
The issues have already been reported here https://github.com/mozilla-mobile/fenix/issues/17890 and https://github.com/mozilla-mobile/fenix/issues/4446, I will mark this issue as closed as they will be handled there.
