### ISSUE TITLE
Remove workaround to update home menu account name

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#26526]
Currently to make sure we update on the user account name in home menu when it's available, it causes the home menu to close.  Investigate for a better solution so the account name can be updated without causing this issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21329)

**Comment by mcarare** [comment]
My 2 cents: We should show a "loading" intermediary state for the menu item when sync-related stuff is in progress. That or hide the menu item in that state.

**Comment by rocketsroger** [comment]
> My 2 cents: We should show a "loading" intermediary state for the menu item when sync-related stuff is in progress. That or hide the menu item in that state.

This could be a solution.  Hide it until we know account manager is ready.

**Comment by rocketsroger** [comment]
Taking @mcarare 's recommendation for the fix, closing this.
