### ISSUE TITLE
Make Slider on full screen video bigger.

### ISSUE THREAD

**Issue by MicroBeast** [mozilla-mobile/fenix#26533]
![Screenshot_20220818_210629](https://user-images.githubusercontent.com/19607487/185468545-14cceb9b-2f88-4c59-9e8b-f2f538dc2128.jpg)

### What is the user problem or growth opportunity you want to see solved?
Please make that Red Slider bigger. 

### How do you know that this problem exists today? Why is this important?
On fullscreen video and small screen device, trying to drag that slider occasionally will trigger the "Swipe toolbar sideways to switch tabs" setting (which is weird in first place). That Gray Bar on left, is just sample this fullscreen video is move able.

If not swiped to other tab, it interestingly also could make the Video switch to Previous/Next Video. Not reproduceable easily.

### Who will benefit from it?
Not sure. At least only me (with big fingers) for now.

- Firefox: Nightly GPlay 105.0a1 (Build #2015897545), 33406ac24+ and previous versions.
- Devices: Samsung SM-M20g, Vivo Y15s and Redmi 4A.

Thank you.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21331)

**Comment by kbrosnan** [comment]
This is the YouTube UI we don't control their video player. You can see an example of the default Mozilla video player at https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c0/Big_Buck_Bunny_4K.webm/Big_Buck_Bunny_4K.webm.1080p.webm
