### ISSUE TITLE
Element is selected on YouTube when double tapping to jump forward

### ISSUE THREAD

**Issue by W0lfDev** [mozilla-mobile/fenix#26537]
When using youtube.com and double tap to skip 10 seconds of a video, if i tap more than 3 times it for some reason decides to ask me if i want to fopy the text of the "30 seconds" for example 

This doesn't happen on other browsers, i have checked

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21334)

**Comment by LaurentiuApahideanSV** [comment]
I can confirm the issue is reproducible on Firefox Nightly 105.0a1 (2022-08-19).
### Devices used:
- Samsung Galaxy S22 Ultra (Android 12)
- Google Pixel 6 (Android 13)

**Comment by boydaihungst** [comment]
I have the same issue.

Firefox nightly version: 106.0a1 (Build #2015903019)

Devices used:
   Nubia redmagic 6s pro (Android 11)
![PvXoBHT - Imgur](https://user-images.githubusercontent.com/38396158/189330571-48418016-410c-4bcc-9fbc-6aa1e4d3c93b.gif)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813614

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
