### ISSUE TITLE
[Bug]: Firefox Android renames SSH signatures to OpenPGP signatures (.sig to .pgp)

### ISSUE THREAD

**Issue by Mikaela** [mozilla-mobile/fenix#26543]
### Steps to reproduce

1. Download the [SSH signature](https://www.aminda.eu/txt/matrix.txt.sig) of my [Matrix account list](https://www.aminda.eu/txt/matrix.txt) by [clicking here](https://www.aminda.eu/txt/matrix.txt.sig)
  * The page this was observed on was https://aminda.eu/matrix/
3. Observe Firefox Android renaming the file from matrix.txt.sig to matrix.txt.pgp

### Expected behaviour

Firefox Android asks me to save `matrix.txt.sig`.

### Actual behaviour

Firefox Android asks me to save `matrix.txt.pgp`.

### Device name

SONY Xperia 10 II

### Android version

Android 10 (actually SailfishOS 4.4.0.68)

### Firefox release type

Firefox Nightly

### Firefox version

105-0a1

### Device logs

N/A

### Additional information

* [Andrew Ayer on November 12, 2021: It's Now Possible To Sign Arbitrary Data With Your SSH Keys](https://www.agwa.name/blog/post/ssh_signatures)

This issue has been reproduced by at least two other people using hardware and software versions that I don't know.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21337)

**Comment by errhammr** [comment]
I can confirm this.

Browser: Fennec F-Droid
Version: 103.1.0 (Build #1031020)
Device: Shift6mq running ShiftOS 3.7 L (Android 10)

Out of curiosity, I recreated the request using curl on my laptop:

```
$ curl -i \
    -H 'Accept: text/html,application/xhtml+xml;application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
    -H 'Accept-Encoding: gzip, deflate, br' \
    -H 'Accept-Language: de-DE,en-US;q=0.5' \
    -H 'User-Agent: Mozilla/5.0 (Android 10; Mobile; rv:103.0) Gecko/103.0 Firefox/103.0' \
    https://www.aminda.eu/txt/matrix.txt.sig
HTTP/2 200 
server: GitHub.com
content-type: application/pgp-signature
last-modified: Fri, 19 Aug 2022 10:54:01 GMT
access-control-allow-origin: *
etag: "62ff6bc9-4bb"
expires: Fri, 19 Aug 2022 12:34:08 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: 53AC:13131:F7E80:10098F:62FF80E8
accept-ranges: bytes
date: Fri, 19 Aug 2022 13:33:41 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-fra19129-FRA
x-cache: HIT
x-cache-hits: 1
x-timer: S1660916022.669165,VS0,VE98
vary: Accept-Encoding
x-fastly-request-id: 1b31d0a823b90211fab57cb1d3715f345589d934
content-length: 1211

-----BEGIN SSH SIGNATURE-----
[... redacted for brevity ...]
-----END SSH SIGNATURE-----
```

What stands out to me is the `content-type: application/pgp-signature` header which Github wrongly assignes here. Also notice the missing `content-disposition` header that does not override the filename that is part of the URL. I see no valid reason why the browser should change the filename in this case because even if the file was `application/pgp-signature`, the `*.sig` filename extension would still be valid.

**Comment by Mikaela** [comment]
Content-type reported to GitHub at https://github.com/orgs/community/discussions/30084

Reproduced on Nightly (`105.0a1 (Build #2015896977), db0162465+ AC: 105.0.20220808143406, dc028b54ef GV: 105.0a1-20220808092108 AS: 93.8.0`) on Android 10 Go Edition using Nokia 1 (TA-1047), so it cannot be SailfishOS Android Support doing something wrong.

However I am unable to reproduce this on *desktop* (Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0 ID:20220816095503) and I don't understand why would only Android perform renaming if it was supposed to be renamed.

**Comment by errhammr** [comment]
Firefox version 100.0.2 (64-bit) on my OpenBSD 7.1 laptop downloads the file correctly as `matrix.txt.sig`, too. Not sure why the mobile browser behaves differently.

**Comment by kbrosnan** [comment]
I expect this is the same root problem as https://github.com/mozilla-mobile/fenix/issues/25568
