### ISSUE TITLE
[Bug]: No redirect on Gitlab

### ISSUE THREAD

**Issue by maxkraft7** [mozilla-mobile/fenix#26540]
### Steps to reproduce

1. Try to sign in to Gitlab via an OAuth Provider on the Firefox-App
2. Wait forever

### Expected behaviour

Get redirected after a couple of seconds. Just as in the Chrome app

### Actual behaviour

Does not redirect 

### Device name

Oneplus nord 

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21335)

**Comment by SoftVision-LorandJanos** [comment]
Hi @maxkraft7. thanks for your report!
I wasn't able to reproduce your issue. I was redirected as expected.
Could you make a video of your issue?
Maybe try the same on a clean profile. Thank you!

**Comment by boek** [comment]
Hey @maxkraft7,

Please open an new issue if you're still able to reproduce. Going to close this for now as we don't have a reproduction case.
