### ISSUE TITLE
[Bug]: Scroll up by swiping may not respond on some websites

### ISSUE THREAD

**Issue by tesmite** [mozilla-mobile/fenix#26541]
### Steps to reproduce

1. Open the website where the problem occurs (I have checked with Yahoo! Japan, pixiv, and Google Search with Google Search Fixer installed).
2. Scroll down the page once.
3. Try to scroll up the page by swiping down.

### Expected behaviour

The website scrolls by tracking the movement of your finger.

### Actual behaviour

It does not respond at all the first time and responds the second time.
It recurs after an interval.
In rare cases, the reload gesture by swiping down is responsive. Also, if the toolbar is hidden, only scrolling is performed for the display of the toolbar.
In addition, when scrolling continuously at short intervals, it does not always respond the third time.
If you scroll down once and then scroll up without releasing your finger, it will scroll without any problem.

### Device name

Samsung Galaxy Note8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 (Build #2015898795)

### Additional information

The stable versions of Firefox 103.2.0 and Fennec 103.1.0 did not have this problem.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21336)

**Comment by amocirean** [comment]
Hello @testomy  , thank you for submitting the issue.
I was not able to reproduce it on Nightly 105.0a1 from 19th of August 2022.
Could you provide a video regarding the issue?

Device Used: Huawei P40 Lite
Android Version: 10

**Comment by testomy** [comment]
Hello @amocirean , thank you for your response.
Here is a video of this bug on Firefox Nightly 105.0a1 (Build #2015898987) on Galaxy Note8 (Android 9).
The video uses private tabs, but I have confirmed that it also occurs in normal tabs, and that it also occurs in a freshly installed environment, regardless of add-ons or other settings.
I have also seen this bug on Sony Xperia Z3 (Android 6.0), OPPO A5 2020 (Android 10), Sharp AQUOS R3 (Android 11), etc., so it is not a device-specific issue.

https://user-images.githubusercontent.com/111569199/185634958-7f598ea0-5d65-419f-9659-622b07ba6fa3.mp4

**Comment by tesmite** [comment]
After some time of testing, I found that this bug had been present prior to Nightly v103 (i.e., an original implementation that was not reflected in the stable version).
I also found that it occurs in about:config, which is a more familiar place.

**Comment by tesmite** [comment]
#25964 is more detailed.
