### ISSUE TITLE
UI updates to the CFR composable

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26545]
From @gabrielluong :
> - the indicator arrow being too big (versus the previous xml implementation)
> - the close button needs to use the correct ic, it should be `mozac_ic_close_20`

![image](https://user-images.githubusercontent.com/11428869/185552849-82bf1a78-185a-4113-b148-04ae2a86d1b1.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21338)

**Comment by Mugurell** [comment]
Removing the QA flag as QA cannot test this now.

**Comment by Mugurell** [comment]
Reopening to add here also the needed updates to support multiple anchoring modes.

Saw in https://github.com/mozilla-mobile/fenix/pull/26507 that using the CFR composable in it's current state would lead to a different design than expected (different than in Figma) with no easy way to reconcile the UX.

Initially the CFR composable was meant to help with pointing to exactly the middle of an anchor.
The new usage indicated the need to support anchoring the popup body inside a wider anchor.

**Comment by Mugurell** [comment]
Based on a separate discussion started by @gabrielluong and agreed by Crystal 
>I think we should keep the 9dp padding in case certain anchors do not have padding applied, cause the arrow on the CFR should not touch the element directly.

**Comment by gabrielluong** [comment]
> Based on a separate discussion started by @gabrielluong and agreed by Crystal
> 
> > I think we should keep the 9dp padding in case certain anchors do not have padding applied, cause the arrow on the CFR should not touch the element directly.

Could you file a new issue for this change?

**Comment by Mugurell** [comment]
Created https://github.com/mozilla-mobile/fenix/issues/26584.
