### ISSUE TITLE
Add top spacing to header in history list

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26557]
We paused the synced history feature implementation and reverted related code. Although some of it affects the UI and has been in production since April. It would be better to keep the UI changes already in production, namely spacing above headers.

The direction the UI is heading is [here](https://www.figma.com/file/SO8Cd5lnmgNqJQY9KpORc9/History%2C-Bookmarks%2C-Downloads?node-id=877%3A40228).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21343)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 105.0a1 (2022-08-21T18:58:54.350364) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
![Screenshot_2022-08-25-13-36-16-63_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/48829350/185902884-12f157ad-cfaf-4462-a4c5-2fe31ba6630d.jpg)
