### ISSUE TITLE
[Bug]: Missing locale names for skr and tok locales

### ISSUE THREAD

**Issue by bcolsson** [mozilla-mobile/fenix#26556]
### Steps to reproduce

1. Open settings in Nightly
2. Select Language
3. Observe Saraiki and Toki Pona being displayed with just their locale codes (skr / tok)

### Expected behaviour

Language settings should display the language name in its native language and English:
**skr**
 سرائیکی
 Saraiki

**tok**
Toki Pona
Toki Pona

### Actual behaviour

Locale code displayed with initial caps:

Skr
Tok

### Android version

Chrome OS

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21344)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 106.0a1 (2022-09-01) and the Saraiki and Toki Pona are displayed in native language and English.
![Screenshot_20220901-122059](https://user-images.githubusercontent.com/50983519/187890752-fcb991a3-bac2-4c3a-b23f-068f6cedc4fb.png)
![Screenshot_20220901-122143](https://user-images.githubusercontent.com/50983519/187890757-c26f66c6-3437-4549-869c-2a583090dd29.png)
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
