### ISSUE TITLE
Add Telemetry for MR Home Onboarding Dialog for upgrading users

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#26551]
This can be built on top of https://github.com/mozilla-mobile/fenix/pull/26548

The following telemetry is captured:
-Impressions for each card
- Clicks on each X and button for each card

https://mozilla-hub.atlassian.net/browse/FNXV2-20990

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21340)

**Comment by delia-pop** [comment]
Verified as fixed on a custom Debug build provided by @Alexandru2909 with Lenovo Yoga Tab 11 (Android 11). We will re-test this in Nightly when available.
The events were correctly generated:

<img src="https://user-images.githubusercontent.com/89388888/188591291-0e4b6331-9724-4166-9b8c-b46f01bf3a49.jpg" width="50%" />
