### ISSUE TITLE
Intermittent UI test failure - SettingsHomepageTest.setWallpaperTest

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26559]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4734384499620083243/executions/bs.fa69ba052284f3a7/testcases/1/errors
### Stacktrace:
```
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[DESCRIPTION=Wallpaper Item: amethyst]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuHomepageRobot.selectWallpaper(SettingsSubMenuHomepageRobot.kt:58)
	at org.mozilla.fenix.ui.SettingsHomepageTest$setWallpaperTest$3.invoke(SettingsHomepageTest.kt:158)
	at org.mozilla.fenix.ui.SettingsHomepageTest$setWallpaperTest$3.invoke(SettingsHomepageTest.kt:156)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openCustomizeHome(ThreeDotMenuMainRobot.kt:229)
	at org.mozilla.fenix.ui.SettingsHomepageTest.setWallpaperTest(SettingsHomepageTest.kt:156)
```
### Build: 
12038 

This was caused and ignored in https://github.com/mozilla-mobile/fenix/pull/26532
The patch updates the wallpapers workflow to download all the wallpapers from a remote server. Because of that, sometimes the download doesn't finish in time to check the user flow of navigating to the settings page and selecting a wallpaper.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21345)

**Comment by MatthewTighe** [comment]
I thought that this could resolved by doing something like the following in the future, but I wanted to unblock wallpapers progress for now for the MR. Note that if action is taken on this before a patch is landed for https://github.com/mozilla-mobile/fenix/issues/26214, then the `thumbnail` file name should be changed to `portrait`.

```
class FilesExistIdlingResource(private val files: List<File>) : IdlingResource {
    private var resourceCallback: IdlingResource.ResourceCallback? = null

    override fun getName(): String {
        return this::javaClass.name
    }

    override fun isIdleNow(): Boolean {
        return files.all { it.exists() }
    }

    override fun registerIdleTransitionCallback(callback: IdlingResource.ResourceCallback?) {
        if (callback != null) {
            resourceCallback = callback
        }
    }
}
```

```
    @SmokeTest
    @Test
    fun setWallpaperTest() {
        val wallpapers = listOf(
            "Wallpaper Item: amethyst",
            "Wallpaper Item: cerulean",
            "Wallpaper Item: sunrise"
        )

        val wallpaperFiles = listOf(
            File(appContext.filesDir, "wallpapers/amethyst/thumbnail.png"),
            File(appContext.filesDir, "wallpapers/cerulean/thumbnail.png"),
            File(appContext.filesDir, "wallpapers/sunrise/thumbnail.png"),
        )
        val filesExistIdlingResource = FilesExistIdlingResource(wallpaperFiles)
```

**Comment by sv-ohorvath** [comment]
@MatthewTighe As I understood, using the real server where wallpapers are, in UI tests, might be costly. They aren't available on the debug builds anyway, at the moment. I wonder if it's worth it to have a few samples hosted in a different place for testing purposes and what would that involve.

**Comment by MatthewTighe** [comment]
Circling back on this: I've been investigating what the future will look like for wallpaper hosting. No answers yet, but having a better implementation for testing is top of our priority list. That said, I'm not sure that will come with improvements to automated tests, as the wallpapers will all still be hosted remotely.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807291

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
