### ISSUE TITLE
FNX3-16489 ⁃ Use undo snackbar when "closing all tabs"

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2655]
Currently we have an undo snackbar when removing individual tabs, but don't have one when a user takes an action that's even hard to recover from (closing all tabs).

This should be fairly easy to implement given that we already have undo set up for collections and tabs.

**Very very low engineering effort**

## Acceptance Criteria
* When I press the overflow menu for tabs on the home screen, then press "close all tabs" I have a snackbar to undo this action

**Comment by bifleming** [comment]
@vesta0 Priority?

**Comment by sv-ohorvath** [comment]
Verified this on the 5/24 (#11440149) build, found a crash: #2823
