### ISSUE TITLE
Can't resize TEXTAREA

### ISSUE THREAD

**Issue by grmblgrmbl** [mozilla-mobile/fenix#26571]
### Steps to reproduce

1. Open page with TEXTAREA
2. Try to grab resize corner of TEXTAREA

### Expected behaviour

Corner can be grabbed and TEXTAREA can be resized.

### Actual behaviour

Can't grab corner, neither with touch, nor with stylus, nor with mouse. Can't resize TEXTAREA.

### Device name

Galaxy Tab S4

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

103.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21348)

**Comment by LaurentiuApahideanSV** [comment]
@grmblgrmbl Could you provide with a few examples of websites where you encountered this issues?

**Comment by grmblgrmbl** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813912

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
