### ISSUE TITLE
CustomTab Toolbar: default navigation icon color is not accessible in light mode

### ISSUE THREAD

**Issue by floschu** [mozilla-mobile/fenix#26578]
### Steps to reproduce

1. Set device design to light mode in system settings
2. Create CustomTab intent without `CustomTabColorSchemeParams` set for specific `Toolbar` color (see code at the bottom)
3. Launch CustomTab intent

### Expected behaviour

Toolbar navigation icon is visible on light toolbar.

### Actual behaviour

Toolbar navigation icon is not visible on light toolbar.

### Device name

Google Pixel 3a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

103.2.0

### Additional information

code sample:
``` kotlin
CustomTabsIntent.Builder().apply {
    setShowTitle(true)
}.build().launchUrl(context, Uri.parse(url))

```

screenshot where navigation icon is currently being clicked, to see that it is tinted white above a light Toolbar (content crossed out in red):
<img width="438" alt="Screenshot 2022-08-18 at 15 41 57" src="https://user-images.githubusercontent.com/2580292/185917608-97dc6e00-4125-4ee4-8783-dcddad4f8f25.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21354)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813833

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
