### ISSUE TITLE
[Bug]: Keyboard is show over the QR Scanner on the first launch

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#26577]
### Steps to reproduce

1. Install Firefox Nightly.
2. Use a fresh profile.
3. Go to the search bar and tap on QR Scanner.
4. Click "While using the app" when camera access prompt is shown.
5. Observe.

### Expected behaviour

The Keyboard should not be present when scanning a QR Code.

### Actual behaviour

The keyboard is shown over the QR Scanner screen.

### Device name

Huawei P40 Lite

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

### Additional information

The keyboard is also working and the user can write in the Search Bar while in QR Scanner Screen.

https://user-images.githubusercontent.com/103257761/185905436-149a863c-93e5-4dd9-aa9d-cfdfc6600e97.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21353)

**Comment by kbrosnan** [comment]
Talked with Tif and there is no need for UX here. Someone should review this PR as it appears to fix a problem.

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 108.0a1 from 10/25 with Xperia 10 (Android 12). The Keyboard is not present when scanning a QR Code.

https://user-images.githubusercontent.com/108326843/197694869-413c4004-10fc-493e-bd84-bcf0aeb44cdf.mp4

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Beta 108.0b1.
Devices used:
- Oppo Find X5 (Android 12).
- Google Pixel 4 (Android 13).
