### ISSUE TITLE
Intermittent Unit Test failure - SmokeTest.openMainMenuSettingsItemTest 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#26574]
### Test Run:
https://treeherder.mozilla.org/logviewer?job_id=388024359&repo=fenix
### Stacktrace:
```
Test instrumentation process crashed. Check org.mozilla.fenix.ui.SmokeTest#openMainMenuSettingsItemTest.txt for details
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/e2f1c5fc9c35284aa7a9803d7c2317290bb5a0f7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21350)

**Comment by sv-ohorvath** [comment]
The crash that I'm seeing in these logs matches the ones logged in https://github.com/mozilla-mobile/fenix/issues/26385. closing as duplicate and I'll move this report.
