### ISSUE TITLE
Allow (encrypted) app backups e.g. via SeedVault

### ISSUE THREAD

**Issue by Diapolo** [mozilla-mobile/fenix#26572]
### What is the user problem or growth opportunity you want to see solved?
Current Firefox doesn't allow encrypted backups via SeedVault (backup App for Android, integrated in LineageOS or CalyxOS, see https://calyxinstitute.org/projects/seedvault-encrypted-backup-for-android).

You could easily allow encrypted app backups :).
See https://github.com/seedvault-app/seedvault/wiki/FAQ#why-do-some-apps-not-allow-to-get-backed-up for a description of the problem and see this sample how Transport (Android app for public travel) implemented it: https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71

### How do you know that this problem exists today? Why is this important?
I tried to backup via SeedVault, which doesn't work.

### Who will benefit from it?
All Android users relying on SeedVault (or other encrypting backup apps).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21349)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813831

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
