### ISSUE TITLE
UI updates to the CFR composable 2

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26584]
Saw in https://github.com/mozilla-mobile/fenix/pull/26507 that using the CFR composable in it's current state would lead to a different design than expected (different than in Figma) with no easy way to reconcile the UX.

Initially the CFR composable was meant to help with pointing to exactly the middle of an anchor.
The new usage indicated the need to support anchoring the popup body inside a wider anchor.

---- 

Based on a separate discussion started by @gabrielluong and agreed by Crystal 
>I think we should keep the 9dp padding in case certain anchors do not have padding applied, cause the arrow on the CFR should not touch the element directly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21357)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 107.0a1 (2022-09-22) on the following CFR's:
- Sync tab CFR;
- Jump back in CFR;
- Total Cookie Protection CFR;
For all of these the length of the CFR's arrow is 7dp or 20px.
### Device used:
- Samsung Galaxy S22 Ultra (Android 12)
