### ISSUE TITLE
Skip "Select collection" step when I don't have Collections

### ISSUE THREAD

**Issue by topotropic** [mozilla-mobile/fenix#2658]
### Why/User Benefit/User Problem
When I don't have any Collections and I save a new one, I want to immediately go to the "Name Collection" step instead of having to go to "Select collection" to add a new one, so that I save time. 

### Acceptance Criteria (how do I know when I’m done?)
* skip the "Select collection" step when there is no Collection available

**Comment by NotWoods** [comment]
This has been implemented.
