### ISSUE TITLE
[Bug] Tab collection animation issue

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2660]
When pressing "add new collection" and then "back" if a user has at least 6 collections, the last few row items animate weirdly. I wonder if this

is a bug with Google's automatic animation drawing with RecyclerViews as this only happens if the user has 6 or more rows here.

## Demo
![demo 2019-05-20 14](https://user-images.githubusercontent.com/4400286/58052864-cebea200-7b0a-11e9-890e-300593e30984.gif)UNITO-UNDERSCORE!23!UNITO-UNDERSCORE!08!

**Comment by sblatz** [comment]
This will be closed after redesign of collections.

**Comment by topotropic** [comment]
I can't reproduce this, is it still relevant @sblatz?
