### ISSUE TITLE
[Bug]:  PiP Video contains the suggested similar videos from YouTube.

### ISSUE THREAD

**Issue by sv-amocirean** [mozilla-mobile/fenix#26626]
### Steps to reproduce

1. Visit youtube.com
2. Play a video.
3. Turn the video to fullscreen.
4. Swipe up in the youtube screen, and observe that similar videos are shown.
5. Return to device's homescreen.
6. Observe

### Expected behaviour

The video plays in PiP mode, without any visual interruptions.

### Actual behaviour

The video plays in PiP mode, but the similar recommended clips overlap the currently playing video.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Beta

### Firefox version

105.0b1

### Additional information
Also reproducible on Firefox Focus.

https://user-images.githubusercontent.com/103257761/186392966-ae178e4e-7d22-4382-915e-998870f8ceff.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21380)

**Comment by kbrosnan** [comment]
Does this happen on other versions of Android?

**Comment by amocirean** [comment]
@kbrosnan we were able to reproduce the issue on the following devices: Xiaomi 12 Pro (Android 12), Lenovo Yoga Tab 11 (Android 11), Huawei P40 Lite (Android 10).

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813586

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
