### ISSUE TITLE
plantage  et à blocage du tel hier 

### ISSUE THREAD

**Issue by fabnuss** [mozilla-mobile/fenix#26621]
Bonjour, 
Voici le rapport. Vous devriez faire un système d'envoi depuis firefox ça serait plus simple. 
Hier, firefox a planté monumentalement avec la version private page blanche tout était bloqué j'ai cru à un virus mais non car lantivirus n'a pas détecté quoique ce soit ? 
Et en plus il est de plus en plus lent ? 
Bref ças était cool de me dire pourquoi et s'il faut faire quelque chose. Merci 

https://crash-stats.mozilla.org/report/index/51b3879c-32b6-4129-b4bc-d121b0220610#tab-bugzilla

    [Privacy Policy](https://www.mozilla.org/privacy/websites/) [Community Participation Guidelines](https://github.com/mozilla-services/socorro/blob/main/CODE_OF_CONDUCT.md)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21376)

**Comment by kbrosnan** [comment]
Duplicate bz-1772839. Fixed in v104.

**Comment by fabnuss** [comment]
Bonjour, J'ai rien compris ! En français svp merciCordialement --Envoyé à partir d’un Smartphone Android avec GMX Mail.Le 24/08/2022, 16:21 Kevin Brosnan ***@***.***> a écrit:

   
  Closed #26621 as not planned.

**Comment by kbrosnan** [comment]
Mise à jour vers v104. La v104 sera disponible le 24 août à 12h00, heure du Pacifique.

traduit de l'anglais via Google traduction

**Comment by fabnuss** [comment]
Merci 😁Javaus traduit mais on comprenait pas la traduction désolé Belle journée Fabian --Envoyé à partir d’un Smartphone Android avec GMX Mail.Le 24/08/2022, 19:18 Kevin Brosnan ***@***.***> a écrit:

   
  Mise à jour vers v104. La v104 sera disponible le 24 août à 12h00, heure du Pacifique. 
  traduit de l'anglais via Google traduction
