### ISSUE TITLE
[Bug]:  YouTube video turns unresponsive when putting the app in background while having the "Similar Videos" carousel.

### ISSUE THREAD

**Issue by amocirean** [mozilla-mobile/fenix#26627]
### Steps to reproduce

1. Visit youtube.com
2. Play a video.
3. Enter fullscreen mode;
4. Swipe up on the video screen in order to bring up the recommended videos carousel;
6. Return to the Device's homescreen
7. Open Firefox again on the YouTube video.
8. Try to pause the video or interact with it in any other way.

### Expected behaviour

The video is responsive after returning to the app.

### Actual behaviour

The video is unresponsive and the user can't use youtube's video controls.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Beta

### Firefox version

Beta 105.0b1, RC 104.0.1, Nightly106.0a1 (2022-08-24)

### Additional information

https://user-images.githubusercontent.com/103257761/186469813-93be45df-43fe-42e1-8190-c921e3532249.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21381)

**Comment by kbrosnan** [comment]
Does this happen on other versions of Android?

**Comment by LaurentiuApahideanSV** [comment]
No, we tested the issue on several devices with different firmware and only managed to reproduce it on Android 13.
### Devices used:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3 XL (Android 9)
- Oppo Find X3 Neo (Android 11)
- Samsung Galaxy S22 Ultra (Android 12)
- Google Pixel 6 (Android 13)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1806212

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
