### ISSUE TITLE
Wallpapers may take a long time to download and be applied

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26625]
In the investigation about applying wallpapers an interesting implementation detail was raised by Matt - https://github.com/mozilla-mobile/fenix/issues/26555#issuecomment-1224296559

> The current implementation waits until this networking is finished before setting the current wallpaper. This is in order to check whether the current wallpaper is part of an expired promotion or not. It also allows us to construct the fully qualified data type of the current wallpaper using the remote metadata. 
> 
> Thinking about it more now, I don't think there's any good reason for for this because:
>- we let users keep expired wallpapers that are currently selected
>- we can cache the other metadata required for general use. this would be things like the `textColor` and `cardColor` properties, but we don't really need to care about the `collection` for the purposes of actually showing the wallpaper on the home screen.
>
> I had planned to improve storage for wallpapers generally as part of https://github.com/mozilla-mobile/fenix/issues/26033, but it slipped the time constraints of the MR. I think a more robust Room or DataStore implementation would be good now that the data is growing in complexity, but I'm also not sure it's worth doing until the shape of the data has stabilized. I'm not convinced that's happened yet.
>
> For now, we could also cache the other properties I mentioned in settings and construct a useful `Wallpaper` instance during `wallpapersUseCases.initialize` rather than waiting for the network, if there are cases where it is not available to us when we need it. I'm also concerned that users with slower network connections may experience the problem more frequently.

Opened the ticket just to have this on our radar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21379)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809804

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
