### ISSUE TITLE
Rotating the screen shows half of the wallpaper

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26638]
STRs:
- Have a wallpaper set
- From portrait rotate the screen to landscape

Expected:
- The wallpaper automatically conforms to the new configuration

Actual:
- There are cases in which the wallpaper is only shown on ~half of the screen now in landscape

Notes:
- This is not reproducing in 100% of the cases.
- This issue affects other widgets on the homescreen also.
- I cannot reproduce the issue in 104 - Release but can reproduce it on 105 - Beta and 106 - Nightly.

https://user-images.githubusercontent.com/11428869/186588084-8c4c7e0a-68c1-4ec8-b5bf-19b5b0bf4af2.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21388)

**Comment by Mugurell** [comment]
Issue is addressed in https://github.com/mozilla-mobile/fenix/pull/26515 with https://github.com/mozilla-mobile/fenix/blob/5d03d1378afa42488ed266f162836fb3cd02285e/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L944-L946

**Comment by Mugurell** [comment]
This should now be fixed by https://github.com/mozilla-mobile/fenix/pull/26949

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/20 with Google Pixel 6 (Android 13). The wallpaper set is properly displayed on homepage when the orientation is changed.

https://user-images.githubusercontent.com/89388888/191444950-f8703e4f-cb2c-4841-aa0e-80146c95fdaa.mp4
