### ISSUE TITLE
[Bug][L10N]: "Add to shortcuts" and "Remove from shortcuts" are not translated in Hindi 

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#26641]
### Steps to reproduce

1. Open the Android "Language and Input" settings. Set the Language to Punjabi.
2. Check the 3 dot menu after accessing a page pinned to the home screen.
3. Check the 3 dot menu after accessing a page not pinned to the home screen.

### Expected behaviour

2. "Remove from shortcuts" is translated in Hindi.
3. "Add to shortcuts" is translated in Hindi.

### Actual behaviour

The above mentioned strings are not translated in Hindi.

### Device name

Oppo Find X5

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

105.0b1

### Additional information

![image](https://user-images.githubusercontent.com/48829350/186666592-bfca63a9-fbfb-46b0-aa33-83c939fcdd36.png)
![image](https://user-images.githubusercontent.com/48829350/186666666-78f859f0-b93e-41db-be7c-356531b361d8.png)
![Screenshot_2022-08-25-15-07-39-24_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/48829350/186666863-b9734cce-6c88-41d6-8bb7-688510e66989.jpg)
![Screenshot_2022-08-25-15-07-58-82_ffb2f5e1b976ff98cfc94f359fbce8de](https://user-images.githubusercontent.com/48829350/186666871-6c199b3f-de8e-4cdb-8fef-a70be37be1f0.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21390)

**Comment by flodolo** [comment]
This is not really a bug, since there is no SLA associated to community localization.

Hindi is only partially localized, and that specific string is not (so it falls back to English for now)
https://pontoon.mozilla.org/hi-IN/firefox-for-android/all-resources/?search=Remove+from+shortcuts&string=243553

**Comment by SoftVision-LorandJanos** [comment]
Closing the ticket based on the above comment.
