### ISSUE TITLE
Add a new lint rule for checking against quotes in newly added string resources

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26645]
Based on https://github.com/mozilla-l10n/android-l10n/pull/494#discussion_r954802211 instead of escaped quotes we should use (unescaped) [typographic apostrophes](https://mana.mozilla.org/wiki/display/FIREFOX/Punctuation).
A new lint rule to check for this would help keep the strings import process running smoothly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21393)

**Comment by flodolo** [comment]
Ideally the linter should check for:
- `'` (should be `’`)
- `""` (should be `“”`)
- `...` (should be `…`)

You might need to support exceptions, if you need to support HTML markup in strings.

**Comment by flodolo** [comment]
There's also a dupe on file already from 2019
https://github.com/mozilla-mobile/fenix/issues/7210

**Comment by Delphine** [comment]
@Mugurell Hello, checking in about this since I'm back on mobile now. Thank you!

**Comment by Mugurell** [comment]
@gabrielluong wanted to work on this. Can help otherwise.

**Comment by gabrielluong** [comment]
Ya, I am looking to take a stab at this.

**Comment by boek** [comment]
Going to close this as a dup of #7210
