### ISSUE TITLE
Cropped/zoomed videos

### ISSUE THREAD

**Issue by soup94john** [mozilla-mobile/fenix#26640]
### Steps to reproduce

Go to https://m.youtube.com/ in Firefox.

Search for any video and click play. All videos seem to be affected but thumbnails appear to load fine. No issues with audio.

![Screenshot_20220825-113011](https://user-images.githubusercontent.com/112079190/186642506-4e1fbef7-a9ca-44c0-9f9d-86f9d52753ff.png)

After clicking the top search result, this is what Firefox displays. The video is zoomed/cropped somehow and it can't be changed.

![Screenshot_20220825-113032](https://user-images.githubusercontent.com/112079190/186642529-6e89123c-54dc-4aaf-832e-e9e51685359a.png)

This is the same video in full screen/landscape mode.

![Screenshot_20220825-113115](https://user-images.githubusercontent.com/112079190/186642536-4e911b64-0bf9-487e-92e0-08a69cba2068.png)

### Expected behaviour

Video should play normally and scale accordingly. The same videos/website works perfectly in Google Chrome.

### Actual behaviour

Videos appear very zoomed in/cropped or have the entirely wrong aspect ratio. Video window appears to show the very top left of the thumbnail image, shown in the first screenshot

### Device name

Nokia 3 (TA-1020)

### Android version

9

### Firefox release type

Firefox

### Firefox version

104.1.0

### Device logs

https://crash-stats.mozilla.org/report/index/742adf5c-d99d-474a-a9b0-d17cf0220811

### Additional information

I've so far tried;

1. Force-stop Firefox, delete cache, reboot
2. Disable all add-ons
3. Try desktop site
4. Update Firefox to latest version on the play store
5. Change portrait/landscape and video quality e.g. 360p, 480p etc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21389)

**Comment by Mugurell** [comment]
Seems like a media issue, will move the ticket to Bugzilla for more investigation.
What would help there is you could attach your "about:support" information.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1787459

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by soup94john** [comment]
<h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" id="app-basics" data-l10n-id="app-basics-title">Application Basics</h2>

      

Name | Firefox
-- | --
104.0
20220816115024
 
Mozilla/5.0 (Android 9; Mobile; rv:104.0) Gecko/104.0 Firefox/104.0
Linux 28 #1 SMP PREEMPT Thu Aug 27 18:42:34 CST 2020
0/0
0/0               Disabled by default
2
Found
Found
Found
false
1.8 GB
2.6 GB




    Application Basics
------------------

Name: Firefox
Version: 104.0
Build ID: 20220816115024
Distribution ID:
User Agent: Mozilla/5.0 (Android 9; Mobile; rv:104.0) Gecko/104.0 Firefox/104.0
OS: Linux 28 #1 SMP PREEMPT Thu Aug 27 18:42:34 CST 2020
Multiprocess Windows: 0/0
Fission Windows: 0/0 Disabled by default
Remote Processes: [2](https://github.com/mozilla-mobile/fenix/issues/26640#remote-processes)
Google Location Service Key: Found
Google Safebrowsing Key: Found
Mozilla Location Service Key: Found
Safe Mode: false
Memory Size (RAM): 1.8 GB
Disk Space Available: 2.6 GB

Crash Reports for the Last 3 Days
---------------------------------

Nightly Features
----------------

Remote Processes
----------------

Type: Web Content
Count: 1 / 2

Type: GPU
Count: 1

Add-ons
-------

Name: Dark Reader
Type: extension
Version: 4.9.57
Enabled: true
ID: addon@darkreader.org

Name: Mozilla Android Components - Ads Telemetry
Type: extension
Version: 104.0.8.0816163700
Enabled: true
ID: ads@mozac.org

Name: Mozilla Android Components - Browser Icons
Type: extension
Version: 104.0.8.0816163832
Enabled: true
ID: icons@mozac.org

Name: Mozilla Android Components - Firefox Accounts WebChannel
Type: extension
Version: 104.0.8.0816163701
Enabled: true
ID: fxa@mozac.org

Name: Mozilla Android Components - ReaderView
Type: extension
Version: 104.0.8.0816163920
Enabled: true
ID: readerview@mozac.org

Name: Mozilla Android Components - Search Telemetry
Type: extension
Version: 104.0.8.0816163700
Enabled: true
ID: cookies@mozac.org

Name: Mozilla Android Components - Web Compatibility Interventions
Type: extension
Version: 104.0.0
Enabled: true
ID: webcompat@mozilla.org

Name: uBlock Origin
Type: extension
Version: 1.44.0
Enabled: true
ID: uBlock0@raymondhill.net

Name: Video Background Play Fix
Type: extension
Version: 1.6.0
Enabled: true
ID: video-bg-play@timdream.org

Name: YouTube High Definition
Type: extension
Version: 100.0.0
Enabled: true
ID: {7b1bf0b6-a1b9-42b0-b75d-252036438bdc}

Graphics
--------

Features
Compositing: WebRender
Asynchronous Pan/Zoom: touch input enabled; autoscroll enabled; smooth pinch-zoom enabled
WebGL 1 Driver WSI Info: EGL_VENDOR: Android EGL_VERSION: 1.4 Android META-EGL EGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_KHR_mutable_render_buffer EGL_IMG_context_priority EGL_KHR_no_config_context IsWebglOutOfProcessEnabled: 0
WebGL 1 Driver Renderer: ARM -- Mali-T720
WebGL 1 Driver Version: OpenGL ES 3.1 v1.r26p0-01rel0.526d936ea9da20486773a9aaceecd920
WebGL 1 Driver Extensions: GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_buffer_storage GL_EXT_EGL_image_array
WebGL 1 Extensions: ANGLE_instanced_arrays EXT_blend_minmax EXT_sRGB MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context
WebGL 2 Driver WSI Info: EGL_VENDOR: Android EGL_VERSION: 1.4 Android META-EGL EGL_EXTENSIONS: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_KHR_mutable_render_buffer EGL_IMG_context_priority EGL_KHR_no_config_context IsWebglOutOfProcessEnabled: 0
WebGL 2 Driver Renderer: ARM -- Mali-T720
WebGL 2 Driver Version: OpenGL ES 3.1 v1.r26p0-01rel0.526d936ea9da20486773a9aaceecd920
WebGL 2 Driver Extensions: GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_buffer_storage GL_EXT_EGL_image_array
WebGL 2 Extensions: MOZ_debug WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context
Target Frame Rate: 62
GPU #1
Active: Yes
Description: Model: TA-1020, Product: TA-1020_00WW, Manufacturer: HMD Global, Hardware: mt6735, OpenGL: ARM -- Mali-T720 -- OpenGL ES 3.1 v1.r26p0-01rel0.526d936ea9da20486773a9aaceecd920
Vendor ID: ARM
Device ID: Mali-T720
Driver Version: OpenGL ES 3.1 v1.r26p0-01rel0.526d936ea9da20486773a9aaceecd920
RAM: 0

Diagnostics
AzureCanvasBackend: skia
AzureCanvasBackend (UI Process): skia
AzureContentBackend: skia
AzureContentBackend (UI Process): skia
AzureFallbackCanvasBackend (UI Process): skia
CMSOutputProfile: Empty profile data
Display0: 720x1280@0Hz scales:2.000000|1.000000
DisplayCount: 1
GPUProcessPid: 10439
Decision Log
HW_COMPOSITING:
available by default
force_enabled by user: Force-enabled by pref
OPENGL_COMPOSITING:
available by default
force_enabled by user: Force-enabled by pref
GPU_PROCESS:
available by default
WEBRENDER:
available by default
WEBRENDER_QUALIFIED:
available by default
WEBRENDER_COMPOSITOR:
disabled by default: Disabled by default
WEBRENDER_PARTIAL:
available by default
blocklisted by env: Blocklisted by gfxInfo
WEBRENDER_SHADER_CACHE:
available by default
WEBRENDER_OPTIMIZED_SHADERS:
available by default
blocklisted by env: Blocklisted by gfxInfo
WEBRENDER_ANGLE:
available by default
unavailable by env: OS not supported
WEBRENDER_DCOMP_PRESENT:
available by default
disabled by user: User disabled via pref
unavailable by env: Requires Windows 10 or later
unavailable by runtime: Requires ANGLE
WEBRENDER_SOFTWARE:
available by default
WEBGPU:
disabled by default: Disabled by default
blocked by runtime: WebGPU cannot be enabled in release or beta
VP8_HW_DECODE:
available by default
VP9_HW_DECODE:
available by default




Media
-----

Audio Backend: opensl
Max Channels: 2
Preferred Sample Rate: 48000
Roundtrip latency (standard deviation): ...
Output Devices
Name: Group
Default audio output device:
Input Devices
Name: Group
Default audio input device:

Enumerate database

Environment Variables
---------------------

Important Modified Preferences
------------------------------

browser.search.region: GB
extensions.formautofill.creditCards.used: 2
extensions.lastAppVersion: 104.0
idle.lastDailyNotification: 1661541358
media.gmp.storage.version.observed: 1
network.dns.disablePrefetch: true
network.http.speculative-parallel-limit: 0
network.predictor.enabled: false
network.prefetch-next: false
privacy.purge_trackers.date_in_cookie_database: 0
privacy.purge_trackers.last_purge: 1661541358319
storage.vacuum.last.index: 0

Important Locked Preferences
----------------------------

fission.autostart.session: false

Accessibility
-------------

Activated: true
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.34.1
Version in use: 4.34.1

NSS
Expected minimum version: 3.81
Version in use: 3.81

NSSSMIME
Expected minimum version: 3.81
Version in use: 3.81

NSSSSL
Expected minimum version: 3.81
Version in use: 3.81

NSSUTIL
Expected minimum version: 3.81
Version in use: 3.81

Startup Cache
-------------

Disk Cache Path: /data/user/0/org.mozilla.firefox/files/mozilla/10i24ym9.default/startupCache/startupCache.8.little
Ignore Disk Cache: false
Found Disk Cache on Init: false
Wrote to Disk Cache: true

Internationalization & Localization
-----------------------------------

Application Settings
Requested Locales: ["en-GB"]
Available Locales: ["an","ar","ast","az","be","bg","bn","br","bs","ca","cak","cs","cy","da","de","dsb","el","en-CA","en-GB","en-US","eo","es-AR","es-CL","es-ES","es-MX","et","eu","fa","ff","fi","fr","fy-NL","ga-IE","gd","gl","gn","gu-IN","he","hi-IN","hr","hsb","hu","hy-AM","id","is","it","ja","ka","kab","kk","kn","ko","lij","lo","lt","lv","ml","mr","ms","my","nb-NO","ne-NP","nl","nn-NO","oc","pa-IN","pl","pt-BR","pt-PT","rm","ro","ru","sk","sl","son","sq","sr","sv-SE","ta","te","th","tr","trs","uk","ur","uz","vi","wo","xh","zam","zh-CN","zh-TW"]
App Locales: ["en-GB","en-US","en-CA"]
Regional Preferences: ["en-GB"]
Default Locale: "en-US"
Operating System
System Locales: ["en-GB"]
Regional Preferences: ["en-GB"]

Remote Debugging (Chromium Protocol)
------------------------------------

Accepting Connections: false
URL:

**Comment by soup94john** [comment]
Can I ask how this could be a media issue if the same videos/websites work in Chrome?

Thanks.

**Comment by Mugurell** [comment]
> Can I ask how this could be a media issue if the same videos/websites work in Chrome?
> 
> Thanks.

I was referring at the fact that media playback issues can be better investigated by other teams and that's I why I moved the ticket to Bugzilla. Please follow the progress there.
