### ISSUE TITLE
[Bug]: The latest synced tab is displayed in the Jump Back In section until a restart is performed

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#26642]
### Steps to reproduce

Steps to reproduce
1. On a mobile device login in with a Firefox account and open a few tabs;
2. On a second device login with the same account and observe the homepage;
3. On the first device delete all open tabs and wait for or perform a manual sync;
4. Observe the home screen of the second device.
5. Restart Firefox;
6. Observe the home screen of the second device.

### Expected behaviour

At step 4 the last accessed tab from the first should disappear since there are no other open tabs on other synced devices.

### Actual behaviour

A restart of Firefox is required for the synced tab to disappear. 

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 2022-08-25

### Additional information
This issue did not occur on Nightly 106.0a1 2022-08-18, in this build the synced tab would disappear without the need for a restart.

https://user-images.githubusercontent.com/50983519/186696943-1249dc78-2661-4e23-bc34-1efa530bfeca.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21391)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810664

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
