### ISSUE TITLE
Recent tab thumbnail and icon not using correct content scale

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#26666]
Currently we're not using the correct content scale in thumbnail and icon.  This could be an issue when the image or icon doesn't have the right ratio or size.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21402)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 106.0a1 (2022-09-01) using the step provided here https://github.com/mozilla-mobile/fenix/pull/26653#issue-1351473655. After loading the https://www.apple.com/ website and restarting Fenix the thumbnail and icon are displayed correctly.

![1662132208875](https://user-images.githubusercontent.com/50983519/188182776-dcde051c-413d-4b2a-ad82-92fe44ac3d52.JPEG)
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
- OnePlus 6T (Android 9)
