### ISSUE TITLE
The "Jump back in" Contextual Hint is not displayed in Firefox Beta 105.0b2 

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26660]
### Steps to reproduce

1. Perform a fresh install of Fenix;
2. Launch Fenix app;
3. Open a webpage;
4. Navigate to homepage

### Expected behaviour

The "Jump back in" Contextual Hint should be displayed the 1st time users start on home after a new install.

### Actual behaviour

The "Jump back in" Contextual Hint is not displayed.

### Device name

Poco M4 Pro 

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

Firefox Beta 105.0b2

### Additional information

Thing seems to be caused by:  https://github.com/mozilla-mobile/fenix/blob/da677dd650ee83569bd4257b723503cf5f0ba83b/nimbus.fml.yaml#L196

cc: @gabrielluong 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21398)

**Comment by AndiAJ** [comment]
Reproducible on the latest Nightly build as well.

**Comment by AdinaPetridean** [comment]
Reproducible also on Firefox RC 105.0.2.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809818

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
