### ISSUE TITLE
When there is text in search bar at the top, click on the desired search engine to start the search again

### ISSUE THREAD

**Issue by 772602825** [mozilla-mobile/fenix#26677]
When there is text in search bar at the top, click on the desired search engine to start the search directly, instead of clicking the enter key to search again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21407)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807591

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
