### ISSUE TITLE
Too easy to delete a Collection entry

### ISSUE THREAD

**Issue by andyross63** [mozilla-mobile/fenix#26678]
Currently, it is WAY too easy to delete an entry from a Collection on Firefox Android. Not only is there an "X", you can also swipe left, and even more bizarrely, swipe RIGHT. There is no verification of the delete, and no undo. All too often I have deleted an entry by mistake by bumping the screen. If I'm not looking close, I may not even remember what it was.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21408)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/2725
