### ISSUE TITLE
[Bug]: Status bar icons are difficult to see on some devices

### ISSUE THREAD

**Issue by tesmite** [mozilla-mobile/fenix#26674]
### Steps to reproduce

1. Open Firefox Nightly.
2. Set the theme to Light
3. Open one of the sites or settings, etc.

### Expected behaviour

Status bar icons should be gray.

### Actual behaviour

Status bar icons are white and difficult to see.
![Screenshot_20220827-142027~2](https://user-images.githubusercontent.com/111569199/187016212-feb68ae0-19eb-40b5-9df4-b320346956e7.png)

### Device name

Sharp AQUOS R3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 (Build #2015900331)

### Additional information

This bug occurred in an update within the last few days.
Not occurring on Samsung Galaxy Note8 (Android 9) in the same version.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21404)

**Comment by baturayp** [comment]
Same here.
Firefox Nightly. Android 11. Using "Follow device theme" setting, with light system theme.
![Screenshot_20220828-150902](https://user-images.githubusercontent.com/4487018/187073707-fc5a27f4-2169-4181-80c9-350dfe1fb9ed.png)

**Comment by Matth7878** [comment]
Can also confirm : one plus 7, android 11, nightly 106.0a1 (Build #2015901003)

Switching theme and choosing follow device or light themefix it until you move from customize settings.

**Comment by tesmite** [comment]
Fixed in 107.0a1 (Build #2015909259).

**Comment by SoftVision-LorandJanos** [comment]
I've managed to reproduce this issue with the Nightly build from 2022-08-27, using a Xiaomi Mi11 Lite (Android 11).
Verified as fixed on the latest Nightly build (107.0a1 - 2022-10-13T17...)
Marking the ticket as verified.

Before:

![Screenshot_2022-10-14-07-29-38-458_org mozilla fenix](https://user-images.githubusercontent.com/48829350/195763879-74d0124b-992f-4df8-910f-20428b0e0714.jpg)

After:

![Screenshot_2022-10-14-07-31-11-031_org mozilla fenix](https://user-images.githubusercontent.com/48829350/195763904-15b9cc52-44a0-4e96-81c1-ae6a89099fdf.jpg)
