### ISSUE TITLE
[Bug] about:about lists some non-functional about: pages

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/fenix#2667]
## Steps to reproduce
Navigate to "about:about" and try clicking on things.

### Expected behavior
Each link present in about:about should go to somewhere functional.

### Actual behavior
* Clicking "about:addons" gives a "File not Found" error page.
* Clicking "about:debugging-new" gives a "File not Found" error page.
* Clicking "about:logo" shows me the Firefox Nightly logo, which seemed odd.

All the other ones seemed to do something sensible though, which was :+1: :grin: 

### Device information
I'm running a local build of `b54628210bd72ea7ecee20e088e084453d4c8795` in an emulator.

**Comment by makotokato** [comment]
> Clicking "about:debugging-new" gives a "File not Found" error page.

This is https://bugzilla.mozilla.org/show_bug.cgi?id=1550651

**Comment by Anty0** [comment]
Also about:config doesn't work.
You can click on it, but nothing happens...
(Cannot even navigate there.)

**Comment by makotokato** [comment]
> 
> 
> Also about:config doesn't work.
> You can click on it, but nothing happens...
> (Cannot even navigate there.)

This is https://github.com/mozilla-mobile/fenix/issues/2778

**Comment by eliserichards** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/43795363/81114491-c14f2300-8ee7-11ea-84de-4924c9068de3.png">

Invalid/broken `about` links:
* addons
* certificate
* config

Are there any additional `about`s that we should add to the `about:about` list @vesta0?

**Comment by vesta0** [comment]
about:logins?

**Comment by eliserichards** [comment]
Related to #3552

**Comment by pbhj** [comment]
> <img alt="image" width="360" src="https://user-images.githubusercontent.com/43795363/81114491-c14f2300-8ee7-11ea-84de-4924c9068de3.png">
> 
> Invalid/broken `about` links:
> 
>     * addons
> 
>     * certificate
> 
>     * config
> 
> 
> Are there any additional `about`s that we should add to the `about:about` list @vesta0?

about:addons and about:config still don't work?

Bug #2778 (noted above) for about:config notes "this is expected behaviour". Shouldn't you remove the link, or at least comment ("does not work on Firefox mobile"). 

It seems bad UX to have links that don't work.
