### ISSUE TITLE
Sometimes when there is no Internet connection page that was loading becomes blank and refresh button doesn't work

### ISSUE THREAD

**Issue by ris58h** [mozilla-mobile/fenix#26688]
### Steps to reproduce

I don't know how to reproduce the issue. I usually get it while commuting underground when my phone lose network connection.

### Expected behaviour

The page shouldn't be blank anyway and refresh button should work.

### Actual behaviour

The page that was loading becomes blank and refresh button doesn't work.

### Device name

samsung galaxy s10e

### Android version

android 12

### Firefox release type

Firefox

### Firefox version

104.1.0

### Additional information

https://user-images.githubusercontent.com/511242/187211822-e398b5f0-d66b-47db-b6f8-a6c32ec0f074.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21412)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813835

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
