### ISSUE TITLE
Utilize native iconography.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [mozilla-mobile/fenix#26680]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

I want Fenix to utilize iconography native to the operating-system that it is installed to. For Android, this would be Material Icons.

### How do you know that this problem exists today? Why is this important?

This is important because custom iconography negates the advantageousness of iconography as opposed to text, because any additional parsal necessary increases the mental load necessary to ascertain what the iconography respresents.

Additionally, it would improve visual consistency, which is always pleasant.

### Who will benefit from it?

Users of Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21409)

**Comment by kbrosnan** [comment]
We use icons that are consistent across Firefox on various operating systems. We don't have any plans to use material icons.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@kbrosnan, why? If everyone were to do that, every application-ecosystem would suffer from the disadvantages that I have previously described. I believe that they are important to accessibility and ease of use.

If you decide despite this to continue to dismiss this proposition, please at least explain why. This request is not a selfish one, so I would at least like the recompense of such a response.

**Comment by kbrosnan** [comment]
As I said we want people that use Firefox cross platform to have consistent iconography. Using material icons would require a complete overhaul of the icons cross Windows, MacOS, Linux, Android and iOS. This is not something that the Android team would decide. If you want to submit it as a cross platform you could add it to https://connect.mozilla.org/

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@kbrosnan, I am unable to. Whenever I ask for an e-mail to login, nothing appears, and I appear to be unable to utilize my password too, because no option appears to allow me.
