### ISSUE TITLE
[Bug]: "Remove" button from the last synced tab from jump back in doesn't work when the cursor in the search bar is active

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#26690]
### Steps to reproduce

1. On a mobile device login in with a Firefox account.
2. On a second device login with the same account and open at least 1 tab.
3. Perform a sync.
4. On the mobile homescreen go to the jump back in section and long tap on the last synced tab while the cursor from the search bar is active.
5. Tap on "Remove".

### Expected behaviour

The tab is removed. The remove button is no longer displayed.

### Actual behaviour

The "Remove" button doesn't work.

### Device name

Oppo Find X5

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

### Additional information

https://user-images.githubusercontent.com/48829350/187222042-e7ff3c5a-f780-40a9-8f7b-892017d202c0.mp4

The button works as expected when the cursor is not active.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21413)

**Comment by Alexandru2909** [comment]
There seems to be a problem with [dispatching](https://github.com/mozilla-mobile/fenix/blob/46d73673ec233d2aca0679f126dbccb647a893dc/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt#L260) the touch event to the `Popup` elements from `SearchDialogFragment` to `HomeFragment`. This makes the user unable to interact with any of the popups from the homescreen.

**Comment by Alexandru2909** [comment]
The issue is still persistent for other elements of the homescreen (Recent tabs, Recently visited, Recently saved). Filed #26790 for this.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest Nightly 106.0a1 (2022-09-14T17...) build.
The cursor is dismissed when popup is displayed.
Device used: google Pixel 4 (Android 12).
Closing the ticket as verified.
