### ISSUE TITLE
Intermittent UI test failure - <TopSitesTest.verifySponsoredShortcutsListTest>

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#26698]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5437897129523145347

### Stacktrace:

> androidx.test.espresso.AmbiguousViewMatcherException: 
'(an instance of android.widget.TextView and view.getText() equals string from resource id: <2131888090> [top_sites_sponsored_label] value: Sponsored and view.getParent() (view.getParent() is an instance of android.view.ViewGroup and is at child index <1>))' matches multiple views in the hierarchy.

### Build: 8/29 Main

This was caused and ignored in https://github.com/mozilla-mobile/fenix/pull/26614.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21416)

**Comment by AndiAJ** [comment]
Fixed in #26639
