### ISSUE TITLE
FNX3-16497 ⁃ Position the context menu of non-text elements at the bottom of the interface.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2670]
### Why/User Benefit/User Problem
A context menu at the bottom is easier to use with only one-hand.

### What/Requirements
Context menu at the bottom

### Acceptance Criteria (how do I know when I’m done?)
Holding links and images shows the context menu at the bottom, similarly to what Opera Mobile does.
![Screenshot](https://user-images.githubusercontent.com/32398857/58065030-aeb6cf00-7b5a-11e9-9f57-ef18e32e171d.jpg)UNITO-UNDERSCORE!20190520-234608!UNITO-UNDERSCORE!Opera!

**Comment by topotropic** [comment]
this is a dup of https://github.com/mozilla-mobile/fenix/issues/2630
