### ISSUE TITLE
[Telemetry] Send existing URI counter in Baseline ping

### ISSUE THREAD

**Issue by perrymcmanis144** [mozilla-mobile/fenix#26700]
## Description & Product Manager / Data Scientist User Story
DS would like to evaluate the potential of having next year's CDOU measurement be built on top of qualifiers. As the current CDOU count is Baseline-based and that would need to be continued, and there are some inherent challenges with joining pings due to their designs, we will send this existing value in Baseline.

DS jira ticket: https://mozilla-hub.atlassian.net/browse/DS-1878

## What questions will you answer with this data?
Would QCDOU built on top of the baseline ping give valid results

## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [X] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [X] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

Data reviews covering this measure in metrics:
      - https://github.com/mozilla-mobile/fenix/pull/17935
      - https://github.com/mozilla-mobile/fenix/pull/19924#issuecomment-861423789
      - https://github.com/mozilla-mobile/fenix/pull/21038#issuecomment-906757301

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21418)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 107.0a1 2022-09-28 and the URL counter is sent as a baseline ping.
 },
"counter": {
"events.normal_and_private_uri_count": 9
}
[Glead Dashboard](https://debug-ping-preview.firebaseapp.com/pings/Laurentiu-2809)
### Device used:
- OnePlus 6T (Android 9)
