### ISSUE TITLE
Deduplication of sponsored shortcut URLs in "Recently Visited" and Jump Back In sections

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#26706]
Sponsored shortcuts are shown to users as shortcuts on the homepage in the second and third tile position by default, and include a “Sponsored” label. We want to prevent sponsored URLs from being displayed in the `Jump back in` and `Recently visited` in the homescreen.

More details in the [Jira ticket](https://mozilla-hub.atlassian.net/browse/FNXV2-21384).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21419)

**Comment by LaurentiuApahideanSV** [comment]
I retested the issue on Fenix RC 105.2.0. After visiting sponsored shortcuts and closing the tabs I can confirm that they don not appear in the Jump back in and Recently visited sections on the homescreen.

### Devices used:
- Samsung Galaxy S22 Ultra (Android 12)
- Huawei MediaPad M3 (Android 7)
