### ISSUE TITLE
Form Validations not Displaying Pop-ups

### ISSUE THREAD

**Issue by tinnickels** [mozilla-mobile/fenix#26713]
Basic HTML5 form validation should display pop-up and autofocus to the field when a field criteria is not met. This is not happening on Android Firefox v104.1.0 (full app or Firefox Focus). The page here demos the issue. This page has no CSS or Javascript. https://tln.rqa-services.com/test.html

Hitting the submit button does not submit (as expected) but the user gets no indication why.

Behavior works on iOS Firefox and Desktop. Also works on Android Chrome.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21424)

**Comment by Mugurell** [comment]
Thank you for the report!
Will move the issue to Bugzilla for more investigations. Please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1788064

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
