### ISSUE TITLE
Enhanced Tracking Protection (ETP) ON by default

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#2671]
## User Story
To be filled out

## Dependencies
GV storage API

### Acceptance Criteria
To be filled out

**Comment by cpeterso** [comment]
The Firefox Security team recommends that Fenix and Fennec use the same Tracking Protection terminology as Firefox desktop:

Option|Regular Browsing|Private Browsing
--|--|--
"Standard" (default)|Block tracking cookies|Block tracking cookies and trackers
"Strict"|Block tracking cookies and trackers|Block tracking cookies and trackers
Disabled|No blocking|No blocking

Tracking cookie blocking is Enhanced Tracking Protection (aka ETP). Tracker (third-party subresources, e.g. JavaScript or images) blocking is regular Tracking Protection.

**Comment by vesta0** [comment]
Dup of #1749
