### ISSUE TITLE
[Bug] Can't upload files to Github

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2672]
## Steps to reproduce
Try to upload an image on a new issue

### Expected behavior
Image is upload successfully

### Actual behavior
After opening the files app, no file is shown and I can't upload anything to github, although I can do it on other websites.

### Device information
* Android device: Galaxy A5 2017 (8.0)
* Fenix version: 1.0.1921

**Comment by kbrosnan** [comment]
Closing as a dupe #2673

**Comment by Lululalu** [comment]
@kbrosnan I am not sure it's a dupe. I cannot upload files to GitHub, although I can upload files to Post Images normally. On Post Images I can't upload files using third party apps, only using the Files App. The issues are slightly different.

**Comment by Lululalu** [comment]
#2673 was fixed and I still can't upload fileso Github using Fenix, so I reopening the issue.

**Comment by Amejia481** [comment]
I'm pretty surprised 😞 . [I'm able to do so](https://drive.google.com/file/d/1KYsLh3MhnjP3_sooCbzcfhhLMEQcnP8i/view?usp=sharing) on my Pixel 3, and also in an emulator using [Android 8.0 and 8.0](https://drive.google.com/file/d/1es_H1-Sa7hXRwcwgcsgBXi8lf-0AQsnS/view?usp=sharing). Maybe is a devices specific issue.  Are you using the latest Fenix version? Are you using a Galaxy A5 2017 (8.0)?

**Comment by Lululalu** [comment]
@Ameija481 yes, I am using the latest Fenix version downloaded from the Play Store on a Galaxy A5 2017 with Android 8.0 and the latest updates. When I try to upload files to Github (and some other websites too) the result is the Files app saying "no files". Actually I now can upload files using a third party app, but that's a workaround.

**Comment by yoasif** [comment]
I can upload files to Github in a standalone Fenix session, but I can't in a custom tab. Should I open a new bug for this? 

On a Pixel 2.

**Comment by Amejia481** [comment]
@Lululalu thanks for the report :), you were right I noticed that we weren't handling [sites that filter file uploads by file extensions ](https://github.com/mozilla-mobile/android-components/issues/3227). I opened an issue for that https://github.com/mozilla-mobile/fenix/issues/3097 and a fix is coming https://github.com/mozilla-mobile/android-components/issues/3227

@yoasif thanks I opened an issue for that https://github.com/mozilla-mobile/fenix/issues/3098 also a fix is coming https://github.com/mozilla-mobile/android-components/issues/3227
