### ISSUE TITLE
Unable to download images from HTTP web sites (Android, Nightly).

### ISSUE THREAD

**Issue by nulltab** [mozilla-mobile/fenix#26722]
### Steps to reproduce

1. Attempt to save any link (image) from an HTTP web site. (especially images)
2. Get a download failure. With weird message like "download failed".  (obviously there is no good reason why should it fail, my connection is perfect, 300mbit is more that enough and it works just fine in other browsers). No option to override it, no explanation. No way to download an image. Workflow failed. No fun at all. 
3. Fix: **download ANY other browser**, e.g. Google Chrome, Safari, Etc...

Could you please provide details about WHO an WHY decided to disable HTTP in Firefox. We will thank that person a lot. Please d on't tell him/her what there is TCP and MAC... otherwise we will have really fun times.

### Expected behaviour

Able to download images or ANY other links from all web sites. REGARDLESS of TLS/SSL usage.

### Actual behaviour

Not able to download HTTP links. Especially images. It is unacceptable for a web browser. At least please add an option to disable this **WEIRD** behavior.

### Device name

Galaxy A53 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 106.0a1

### Device logs

None

### Additional information

None

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21427)

**Comment by nulltab** [comment]
Easy way to reproduce - Go to http://toastytech.com/evil/ and to download http://toastytech.com/evil/burnieani.gif.
There is no way to download it on Firefox Nightly on Android... - always results in an error message.

**Comment by nulltab** [comment]
You can just add an option or prompt to allow downloading images. Similar to that prompt for when you open non-http sites. 
I just really need to download my documents (but there is NO WAY TO currently). Don't force me to go back to w3m and curl... or Chrome.

I hope you figure it out. Thanks.

**Comment by MicroBeast** [comment]
Turn off HTTPS only mode in settings

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812779

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
