### ISSUE TITLE
Rendering Bugs (flickering, chunks of pixels) with JS Light Boxes

### ISSUE THREAD

**Issue by el-ef** [mozilla-mobile/fenix#26726]
## Site with issue and any steps to reproduce
https://www.lightgalleryjs.com/
https://xenforo.com/community/threads/media-gallery-2-2-lightbox-navigation-attachment-mirroring-and-more.183044/

### Expected behavior
Lightbox galleries should render without artifacts.

### Actual behavior
Opening, closing and swiping through the galleries creates pixelated artifacts.
Example: https://www.youtube.com/watch?v=vVAMH0qDWa0

### Does toggling Tracking Protection fix the issue? (Press the shield icon in the toolbar while on the site to see toggle)
No.

### Can you reproduce in Chrome (or other non-Mozilla browser)?
No.

### Device information

* Android device: Google Pixel 6 Pro, Android 13
* Fenix version: 104.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21430)

**Comment by kbrosnan** [comment]
Duplicate bz-1787520
