### ISSUE TITLE
Intermittent UI test failure - SettingsBasicsTest.frenchSystemLocaleTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#26729]
While writing the UI test: SettingsBasicsTest.frenchSystemLocaleTest, I came across an issue where the app doesn't update immediately after you change the system language so it made this test fail consistently. 
I'll land the code changes but leave it disabled. Waiting for https://github.com/mozilla-mobile/fenix/issues/26728 to be fixed before re-enabling the test.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21432)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807290

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
