### ISSUE TITLE
[Bug]: A manual login cannot be added without the username after typing in the username field

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#26736]
### Steps to reproduce

1. Launch Fenix;
2. Go to Settings->Logins and passwords->Saved logins;
3. Tap the Add login button;
4. In the URL field type a valid web address and enter any password;
5. In the Username field type a few characters and then delete them; 

### Expected behaviour

A user should be able to manually add a login without a username.

### Actual behaviour

At step 4 the login can be saved without entering a username. At step 5 the login cannot be added without adding a username.

### Devices used
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 (Android 12)

### Firefox release type

Firefox Nightly 106.0a1 (2022-08-31), Firefox RC 104.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21436)

**Comment by oyeraghib** [comment]
I would like to work on this issue.

**Comment by delia-pop** [comment]
Verified as fixed in Nightly 109.0a1 from 12/03 with Google Pixel 6 (Android 13). The manual login can now be saved with empty "Username" field after deleting the previously typed characters.

**Comment by delia-pop** [comment]
Also verified fixed on Beta 109.0b1 with Lenovo Yoga Tab 11 (Android 11).
