### ISSUE TITLE
Update typography for the Pocket section

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26737]
Following a recent discussion from https://github.com/mozilla-mobile/fenix/pull/26451#pullrequestreview-1073013007 @Kate-Galetski helped standardize the typography used for the Pocket section also.

The new design is available at https://www.figma.com/file/d7l1iGabQYqnLcnQbHDGzM/Wallpaper-2.0-%2B-Onboarding-v106?node-id=5572%3A197382

Typography details:
- [ ] All texts will use the `caption` style
- [x] The main is colored in: `textPrimary`
- [x] The secondary line is colored in: `textSecondary`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21438)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/20 with Google Pixel 6 (Android 13). The Pocket section matches the design.

![1663692939773](https://user-images.githubusercontent.com/89388888/191445363-9aa43fc5-77c0-4fcc-bd36-b480884af3f7.JPEG)
