### ISSUE TITLE
[Bug]: Language search doesn't reset to full list view anymore

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#26733]
### Steps to reproduce

1. Go to Settings>Language
2. Tap the search button, and type a language name (e.x. French)
3. From the search results, select the new language.

### Expected behaviour

When a selection is made, the search results are dismissed and the full languages list is shown. This is the last known expected behavior.

### Actual behaviour
Not sure if intentional, I couldn't find an issue: the search results remain displayed after a language is set. You can exit the Language list and come back again if you need to make another selection.

### Device name

Pixel 2

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

106, 104.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21435)

**Comment by jmora13** [comment]
Is anybody working on this issue? Can I take it?

**Comment by delia-pop** [comment]
Verified as fixed in Nightly 110.0a1 from 12/19 with Google Pixel 6 (Android 13). The full list is now displayed after searching and  selecting a language. 

https://user-images.githubusercontent.com/89388888/208445517-577c457f-0dcf-48ee-86d0-3c98a3906249.mp4
