### ISSUE TITLE
[Bug]: Issue with showing address suggestions from my history(ANDROID)

### ISSUE THREAD

**Issue by Flying-Miko** [mozilla-mobile/fenix#26730]
### Steps to reproduce

1.Have a browser history 
2. write something in address bar

### Expected behaviour

Now, since I have enabled everything except for "show search engines" and "show voice search" in settings->search->addressbar, I should be able to get multiple different suggesstions based on my browser history, including multiple different sites I have visited before (in other words, in my browser history) but are not bookmarked.

### Actual behaviour

Instead of getting a number of different suggestions, I now only at best get 2 suggestions from my browser history.

Suggestion from bookmarks are fine though, I get a bunch of diffrent suggestions from my bookmarks. The problem is I can only get 2 suggestions based on the sites in my history that are not bookmarked

### Device name

Samsung Galaxy A71

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

104.1.0 (Build #2015898515), 99759dd72+ AC: 104.0.8, 3dc0ff00e7 GV: 104.0-20220816115024 AS: 93.7.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21433)

**Comment by lindongbin** [comment]
#25913
I think it's a very big bug that affects normal usage, but the Firefox devs don't use Firefox, so maybe it will be a long time before it will be fixed or never will be fixed

**Comment by Imerion** [comment]
Can confirm this bug still exists. Worst of all is that writing an extra letter often remove the previous suggestions completely and display two new - despite all still being relevant and containing the letters I have written.

**Comment by boek** [comment]
Closing as a dup of #25913
