### ISSUE TITLE
Update the Pocket powered by section design

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#26743]
Figma link  / Screenshot of design to be added.

<details><summary>Screenshot</summary><img width="901" alt="Screen Shot 2022-09-06 at 12 34 57 PM" src="https://user-images.githubusercontent.com/48995920/188874781-307d3831-d222-4ba7-9539-c41fe7b25970.png"></details>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21440)

**Comment by SoftVision-LorandJanos** [comment]
Verified in the latest Nightly 106.0a1 (2022-09-14) build.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.
