### ISSUE TITLE
[Bug] Bing AMP headers are covered by the system notification bar.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2674]
## Steps to reproduce
Go to bing.com
Search for something that is on the news, like The UK
Touch an AMP article

### Expected behavior
The article header is not covered by anything.

### Actual behavior
The header is covered by the system notification bar.
![Screenshot](https://user-images.githubusercontent.com/32398857/58066742-ff312b00-7b60-11e9-8e59-c56e6bc47e83.jpg)UNITO-UNDERSCORE!20190517-110030!UNITO-UNDERSCORE!Firefox Preview!

### Device information
* Android device: Galaxy A5 2017 8.0
* Fenix version: 1.0.1921

**Comment by sv-ohorvath** [comment]
I'm not seeing that part above the Reuters logo on any device.
![Screenshot_20190523-162311_Firefox Preview](https://user-images.githubusercontent.com/4037709/58256186-42fd7d80-7d77-11e9-9ad5-7f28a1c6b653.jpg)

**Comment by Lululalu** [comment]
@sv-ohorvath Yes, I still have this issue, however the amp bar doesn't show up on every article. It's a Bing's thing. I made a video to show what's happening.

https://streamable.com/uaelz

I hope it's helpful.

**Comment by NotWoods** [comment]
I don't see this happen anymore for AMP articles, can QA verify?

**Comment by sflorean** [comment]
I wasn't able to reproduce this on Nightly 6/4 with Samsung Galaxy Note10(Android 10), and Nokia 6(Android 7.1.1). 
@Lululalu could you please confirm that this is fixed for you? Thank you!

**Comment by Lululalu** [comment]
I don't own the same device I did before, but using another device, the problem didn't reproduced anymore.
