### ISSUE TITLE
Don't show Jump Back In CFR if the synced tab CFR is shown

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#26756]
Based on https://mozilla-hub.atlassian.net/browse/FNXV2-20988:
A Jump Back In pop up message will be displayed on the homepage under the following the conditions:
- Should not be shown if the synced tab pickup message is already showing or if the user has already seen the synced tab pickup message

We currently show the Jump back in CFR if the synced tab CFR is shown.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21443)

**Comment by mavduevskiy** [comment]
noticed that we added [behavior](https://github.com/mozilla-mobile/fenix/commit/ca0cfd79e8d4514112da8e4b6abb250092ee41e1#r82835558) that wasn't in the requirements
