### ISSUE TITLE
Suggest actual URLs in the search/address bar.

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2675]
### Why/User Benefit/User Problem
Suggesting URLs allows a faster web browsing experience by bypassing the search engine result page.

### What/Requirements
Actual URLs among the search suggestions.

### Acceptance Criteria (how do I know when I’m done?)
Searching the name of a website shows a URL that takes me right there.

This may not sound like much, but it's a little default that makes a big difference. Chrome does this 
![Screenshot](https://user-images.githubusercontent.com/32398857/58067246-078a6580-7b63-11e9-8325-916b5e6fff0f.jpg)UNITO-UNDERSCORE!20190521-005427!UNITO-UNDERSCORE!Chrome!

**Comment by vesta0** [comment]
Thanks for the idea! Will re-open once we have validated this use case through user testing.
