### ISSUE TITLE
Create a simple wallpaper dialog

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26750]
Breaking down [this](https://github.com/mozilla-mobile/fenix/issues/26216) task, while the different dependencies are being cleared up.

Create a wallpaper selector, that follows these conditions:
-         Tab Pickup and Jump Back In CFRs are not currently being displayed
-         The user has not seen the wallpaper selection tool before

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21441)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/22 with Google Pixel 6 (Android 13). The Wallpaper Selection Tool is displayed on the 3rd homepage visit. Wallpapers can be selected and viewed on homepage, the tool can be dismiss by tapping the "X" button, and will also be automatically dismissed after tapping on the "Explore more wallpapers" link and returning to homepage.
The dialog is also locked on Portrait mode. 

![WallpaperSelectionTool](https://user-images.githubusercontent.com/89388888/191711708-929959f1-866d-4bd0-9615-872bd2c11cb5.jpg)
