### ISSUE TITLE
Enable "Android Default Browser Card Variations" first-run experiment

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26768]
We want to run this Android first-run experiment in v107, so we will need to enable the first-run experiment in code (and Nimbus):

https://mozilla-hub.atlassian.net/browse/MOBEX-26

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21448)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813837

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
