### ISSUE TITLE
[Bug] Can't Install PWA on Android

### ISSUE THREAD

**Issue by alxandruu** [mozilla-mobile/fenix#26765]
Hello everyone,

I'm trying to install a PWA with the Firefox Android Browser. But when you click on Install button nothing happens. 

Thanks for the help.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21446)

**Comment by cadeyrn** [comment]
Works for me. Why did you not use the [bug reporting template](https://github.com/mozilla-mobile/fenix/issues/new?assignees=&labels=%F0%9F%90%9E+bug%2Cneeds%3Atriage&template=---bug-report.yml&title=%5BBug%5D%3A+) to provide more information?
