### ISSUE TITLE
Crash: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#26767]
https://sentry.io/organizations/mozilla/issues/3550364045/?project=6295546

> java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
>     at android.net.Uri.getQueryParameterNames(Uri.java:1590)
>     at org.mozilla.fenix.ext.UriKt.containsQueryParameters(Uri.kt:4)
>     at org.mozilla.fenix.home.blocklist.BlocklistHandler.filterContileRecentlyVisited(BlocklistHandler.kt:6)
>     at org.mozilla.fenix.home.blocklist.BlocklistMiddleware.invoke(BlocklistMiddleware.kt:30)
>     at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
>     at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:10)
>     at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
>     at mozilla.components.lib.state.Store$dispatch$1.invokeSuspend(Store.kt:4)
>     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
>     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>     at java.lang.Thread.run(Thread.java:764)
> 
> mozilla.components.lib.state.StoreException: Exception while reducing state
>     at mozilla.components.lib.state.Store$exceptionHandler$1$1.run(Store.kt:1)
>     at android.os.Handler.handleCallback(Handler.java:873)
>     at android.os.Handler.dispatchMessage(Handler.java:99)
>     at android.os.Looper.loop(Looper.java:216)
>     at android.app.ActivityThread.main(ActivityThread.java:7258)
>     at java.lang.reflect.Method.invoke(Method.java)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
> 
> java.lang.reflect.InvocationTargetException: null
>     at java.lang.reflect.Method.invoke(Method.java)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
> 
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21447)

**Comment by Mugurell** [comment]
Seems like a dupe of https://github.com/mozilla-mobile/fenix/issues/26767 which also contains some STRs.

**Comment by MozillaNoah** [comment]
> Seems like a dupe of #26759 which also contains some STRs.

Thanks, closing this issue in favor of that one
