### ISSUE TITLE
[Bug]Unable to set

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#2676]
## Steps to reproduce
1.about:config
2.https://wiki.mozilla.org/Electrolysis
3.Same as the first question.
4.DOH

### Expected behavior
1.There is always a flashing hard to use setting.
2.Does this setting have any effect? Because he doesn't work!
3."about:config" has no paste function?
4.The replacement of "DOH" into another server is suspected to be inoperable.

### Device information
* Android device: Android 8.0
* Fenix version: 1.0.1921 beta

**Comment by kbrosnan** [comment]
This bug report makes no sense. Please provide clear individual steps to reproduce what you are seeing.
