### ISSUE TITLE
FNX3-16504 ⁃ [Bug] transparent background of favicons not supported

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2677]
### Steps to reproduce
1. open a website with a transparent favicon, for example https://www.soeren-hentzschel.at
1. go to history

### Expected behavior
Transparent background behind the favicon (I _don't_ mean the circle behind the favicon).

### Actual behavior
The transparent background is white.

![Screenshot](https://user-images.githubusercontent.com/1100614/58070773-9c5c8580-7b9a-11e9-9549-760ac3cfe2df.png)UNITO-UNDERSCORE!20190521-072143!

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision cfca683a14ddc06bd09ea320bb5710cdcf001c80

**Comment by pocmo** [comment]
For this website we pick one of the apple touch icons and they do have a white background:
https://www.soeren-hentzschel.at/wp-content/themes/agenedia-mozblog/assets/images/favicons/apple-touch-icon-180x180.png

I can see the same behavior in Fennec (e.g. in the tabs tray).

**Comment by bifleming** [comment]
@vesta0 can you confirm we can close this?

**Comment by cadeyrn** [comment]
@pocmo Is the logic which icon is chosen documented somewhere? Or can you point me to the code?

**Comment by vesta0** [comment]
We can close this since the current behaviour is intentional, and revisit the logic later on if we come across UX issues in future.
