### ISSUE TITLE
Centre Jump Back In CFR

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#26777]
This was feedback that came from the MR onboarding demo with Product+UX. We want to center the Jump Back in CFR similar to the Synced Tab CFR.

<img width="465" alt="Screen Shot 2022-09-01 at 7 04 04 PM" src="https://user-images.githubusercontent.com/1190888/188027066-ed7695be-05f9-440a-aef4-6802765044de.png">

<img width="465" alt="Screen Shot 2022-09-01 at 10 19 04 PM" src="https://user-images.githubusercontent.com/1190888/188045895-d8880457-fba5-4327-b7c8-b0103aa8b9e7.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21452)

**Comment by delia-pop** [comment]
Verified as fixed on latest Debug build updated from main 1.0.2237 with Google Pixel 6 (android 13). We will re-test this on Nightly when available.

![JumpBackInCFR](https://user-images.githubusercontent.com/89388888/189165154-34f3ed15-b4f6-454c-97af-a5422a4c6190.png)
