### ISSUE TITLE
Sign in to sync toolbar menu doesn't unhide quickly enough

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/fenix#26788]
#26072 was fixed by #26494 - but now, when you visit the menu, there's no sync mention at all. It remains hidden until a sync or visiting "settings", which might confuse users about whether they are signed in or not - see comments in #26072.

We can almost certainly grab the fxa state when first showing that menu so it updates almost immediately instead of waiting for some other sync operation.

And does this work OK when not signed in? I can't test that ATM.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21460)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809254

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
