### ISSUE TITLE
[Bug]: Inconsistencies between the snackbars displayed on tablets and phone devices 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26787]
### Steps to reproduce

1. On a tablet device, long tap a link.
2. Select "Open link in new tab" or "Open link in a private tab" and observe the snackbars.
3. Go to Settings > Search and add a new custom engine and abserve the snackbar.
4. Create a collection of tabs and observe the snackbar.

### Expected behaviour

All shackbars displayed throughout the application on a tablet device should be displayed similar to the ones on phone devices: a long snackbar proportional with the screen length.

### Actual behaviour

Some of the shackbars displayed throughout the application on a tablet device are displayed as a short snackbar in the middle of the screen. 
Note that the  "Wallpaper Updated! VIEW" snackbar is displayed accordingly.

### Device name

Lenovo Yoga Tab 11

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

### Additional information

Also reproducible on Fenix Beta 105.0b4 and RC 104.1.0.

![Snackbars](https://user-images.githubusercontent.com/89388888/188128017-d2641380-bb88-4e8c-9bcb-98f5d25e4624.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21459)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807138

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
