### ISSUE TITLE
Hold action does not dimiss URL context menu on Android 10+

### ISSUE THREAD

**Issue by issue-dispenser** [mozilla-mobile/fenix#26782]
### Steps to reproduce

1. Hold a URL to open the context menu
2. Hold (and do not release) part of the page outside of the menu.

### Expected behaviour

The context menu is dismissed.

### Actual behaviour

The context menu is not dismissed.

### Device name

Samsung Galaxy S21 FE

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

### Additional information

I was previously using a Galaxy S7 on Android 8.0 which produced the desired behaviour (dismissed the menu). The only difference I know of is the newer Android version.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21454)

**Comment by issue-dispenser** [comment]
In case this is somehow intentional, both Chrome and Samsung Internet on Android 12 dismiss their analogous menus with an outside hold action.

**Comment by issue-dispenser** [comment]
I tested with the default Android Studio emulators and found it behaving as expected on Android 9/P and failing since Android 10/Q.

**Comment by issue-dispenser** [comment]
I found the issue: Fenix uses the Android Components' 'Context Menu' feature, which uses an [AlertDialog ](https://github.com/mozilla-mobile/android-components/blob/1c2f7a441745b6fd201e573cbf71dd59856d2d54/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFragment.kt#L63)that internally uses a `Window`. This `Window` had its `shouldCloseOnTouch` method changed in [this commit between Android P/Q](https://cs.android.com/android/_/android/platform/frameworks/base/+/45385e2ac3ee7b723fe14f10becd169f175bb419), after which it closes on releasing the touch instead of the beginning of the touch.

I'm not familiar with all the different Android UI components, but according to this [official guide](https://developer.android.com/develop/ui/views/components/dialogs#AlertDialog) it doesn't seem like the appropriate component for a context menu.

Therefore, I think this should be moved to the Android Components repo as a sub-issue of a greater rewrite (or new AC 'feature') of the supplied context menu. I've seen some issues here about using Jetpack Compose, so perhaps using a Compose [DropDownMenu](https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#DropdownMenu(kotlin.Boolean,kotlin.Function0,androidx.compose.ui.Modifier,androidx.compose.ui.unit.DpOffset,androidx.compose.ui.window.PopupProperties,kotlin.Function1))?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813838

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
