### ISSUE TITLE
[Bug] e10s

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/fenix#2678]
## Steps to reproduce
After opening "about:config", click "browser.tabs.remote.autostart". This parameter is not available.
At the same time, the browser screen will be blinking without interruption.

### Expected behavior
He needs to be able to be used.

### Device information
Android device: Android 8.0
Fenix version: 1.0.1921 beta

**Comment by kbrosnan** [comment]
e10s is not supported at this time.
