### ISSUE TITLE
[Foxfooding]: "See all synchronised tabs" page is empty

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/fenix#26795]
### Steps to reproduce

**Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
**Window Size (inner width and height):** 1638x1127
**GitHub Username:** @Vinnl

1) Have Firefox Nightly on Android, and Firefox Nightly on desktop, both synced.
2) On Android, under "Jump back in", see a synced tab listed, with a button "See all synchronised tabs" underneath it - click that button.

### Expected behaviour

The drawer that appears includes at least the tab listed under "Jump back in", and ideally other desktop tabs as well. If it's still loading, it displays an indicator that it's doing so.

### Actual behaviour

There's an empty list. (After hitting sync, closing the drawer, seeing a new "Jump back in" tab listed, hitting the button again, then waiting a while, at some point I did see other tabs appear, so maybe it was just loading. I'm on a Fairphone 2, so not a terribly fast device, but not the worst either.)

## Attachment
![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/1e4adee8-224a-4358-85b5-a3182fe3c720.jpg)
[Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/1e4adee8-224a-4358-85b5-a3182fe3c720.jpg)

### Device name

Fairphone 2

### Android version

(unknown)

### Firefox release type

Firefox Nightly

### Firefox version

106

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21463)

**Comment by kbrosnan** [comment]
This device ships without Google Play Services. This makes instant Sync not possible. Did this eventually populate the Sync tabs?

**Comment by jonalmeida** [comment]
> hitting the button again, then waiting a while, at some point I did see other tabs appear, so maybe it was just loading. I'm on a Fairphone 2, so not a terribly fast device, but not the worst either.

This isn't specific to a slow phone. I see this as well on my Pixel 3. I believe we're waiting for a sync to finish before we fetch the sync tabs, but we no longer need to do this since we have a local storage for synced tabs in app services, so we can still display what we have a fetch the latest tabs in parallel.

**Comment by jonalmeida** [comment]
This is worth prioritizing because it make the feature feel unpolished.

**Comment by pdehaan** [comment]
> _"This device ships without Google Play Services. This makes instant Sync not possible. **Did this eventually populate the Sync tabs?**"_

@vinnl Did this ever start syncing for you?

**Comment by Vinnl** [comment]
> Did this eventually populate the Sync tabs?

Yes:

> (After hitting sync, closing the drawer, seeing a new "Jump back in" tab listed, hitting the button again, then waiting a while, at some point I did see other tabs appear, so maybe it was just loading.

I am running /e/OS, so there's no Play Services, but MicroG is available. It might be that it's caused by that, but my hunch is that it was just loading slowly and that there's no loading state.

**Comment by jonalmeida** [comment]
There used to be a "synchronizing" state that told the user something was happening, but this seems to have been removed (intentionally?).

**Comment by jonalmeida** [comment]
Removed "(slow tab sync without Google Play Services)" because the slowness is related to syncing _while_ the tabs tray is opening and is not related to Google Play Services. We schedule periodic syncs using an on-device scheduler (WorkManager) that are set to ~5 mins. Do we have reason to believe that it's because of GPS?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813841

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
