### ISSUE TITLE
Dismiss search dialog when interacting with popups from homescreen

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/fenix#26790]
In https://github.com/mozilla-mobile/fenix/issues/26690 we noticed that the user could not interact with the `remove` dropdown for recent synced tabs from the homescreen when `SearchDialog` was displayed. This is still an issue with other homescreen sections which support popups or dropdown menus: Recent tabs, Recently visited, Recently saved.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21461)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 106.0a1 (2022-09-14T17...) build.
Device used: google Pixel 4 (Android 12).
Closing the ticket as verified.
