### ISSUE TITLE
FNX3-16506 ⁃ Integrate feature-intent component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#268]
This component provides the ability to process intents (e.g. links from third-party apps) and automatically create tabs for them.

**Comment by jonalmeida** [comment]
We briefly talked about this in the channel about getting an IntentReceiverActivity in, but where would it re-direct to for share intents and custom tabs.

In r-b, we have Browser and CustomTab activites that launch based on the intent data although I'm not sure if we wanted to go this route with the HomeActivity and (future) CustomTabsActivity?

cc: @ekager @boek
