### ISSUE TITLE
[Bug]: Visiting https://slickdeals.net results in "Firefox Nightly cannot load that page"

### ISSUE THREAD

**Issue by arcasinky** [mozilla-mobile/fenix#26804]
### Steps to reproduce

1. Go to https://slickdeals.net

### Expected behaviour

The page seems to render fine using the official Android Firefox app.

### Actual behaviour

Using Firefox Nightly, the page appears to render but is quickly replaced by a dialog stating "Sorry.  Firefox Nightly can't load that page."

### Device name

Google Pixel 3

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 (Build #2015901675)

### Additional information

This is relatively new behavior (within the last 2-3 days) as this is my normal web browser and I've visited that site before earlier this week.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21470)

**Comment by marcel263** [comment]
bug report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1788597

it is already fixed. please wait a while and it will be included in the nightly update

**Comment by boek** [comment]
I was no longer able to reproduce. @arcasinky if you experience this behavior again please file a new issue in Bugzilla.
