### ISSUE TITLE
[Bug]: Can't zoom even when accessibility "always allow zoom" set. 

### ISSUE THREAD

**Issue by pettijohn** [mozilla-mobile/fenix#26805]
### Steps to reproduce

1. Settings / Accessibility / Zoom on all websites set to Enabled. 
2. Go to [washingtonian.com ](https://www.washingtonian.com)
3. Try to zoom with two fingers 

### Expected behaviour

Zoom should work

### Actual behaviour

Zoom does not work 

### Device name

Samsung S21 Ultra 

### Android version

12

### Firefox release type

Firefox

### Firefox version

104.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21471)

**Comment by deasytrisnawati** [comment]
i also, tried to zoom our online website please check again for [bprentcar.com](https://bprentcar.com)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811899

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
