### ISSUE TITLE
[Bug] Can no longer share images

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#2680]
## Steps to reproduce
1. Go to a page with an image
1. Long press image

### Expected behavior
Options to open image in new tab, copy location and share image. 

### Actual behavior
Share image is missing. This seems like a minor thing, but it's one of the things that set Fennec apart from the rest. 

### Device information
* Android device: Android 8, LG G6
* Fenix version: 1.0.1920

**Comment by NotWoods** [comment]
Moving this issue to the [Android Components](https://github.com/mozilla-mobile/android-components/) repository, where the context menu code lives.

mozilla-mobile/android-components#3648
