### ISSUE TITLE
Add link to add bug and feature request to menu

### ISSUE THREAD

**Issue by ssssamstrup** [mozilla-mobile/fenix#26817]
### Steps to reproduce

I wanted to add feature request and ended up posting it in the Firefox forums, because I was guided there by the current menu in Fenix.

1. Open «Menu»
2. Open «Settings»
3. Look for report bug/feature request -> Open «About Firefox»
4. Open «Help» -> Opens [Support Forum](https://support.mozilla.org/en-US/) in browser
5. Search for "submit idea", "ideas", "add feature" and find nothing relevant.
6. Click the «Didn't find a solution, post in the forums ->» button and post in the Forums
7. Get told to go to [Help article - File a bug report or feature request for Mozilla products](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla) and look in the proper place.

### Expected behaviour

It would be really nice if there was a link in the «About» section that links to the Help page.

1. Open «Menu»
2. Open «Settings»
3. Look for report bug/feature request -> Open «About Firefox»
4. Open «Report bug/feature request» -> Get send to [Help article - File a bug report or feature request for Mozilla products](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla) and find the right place to post my bug/feature request.

Or add separate options for "report bug" and "feature request" in «Help».

### Actual behaviour

See "Steps to reproduce".

### Device name

Sony XZ2 Compact

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

104.1.0

**Comment by boek** [comment]
Dup of #5168
