### ISSUE TITLE
Firefox app name in Persian

### ISSUE THREAD

**Issue by xmha97** [mozilla-mobile/fenix#26811]
I need the Firefox name to appear in Persian language when the language of my phone is Persian. (Like Samsung Internet app)

![IMG_۲۰۲۲۰۹۰۴_۱۶۴۸۴۸.jpg](https://user-images.githubusercontent.com/23485114/188313089-7124b12a-e020-4b53-a9d0-896afe6289a0.jpg)

Firefox's name in Persian is:
"فایرفاکس"

Please implement my request.

Note: If you want to serve the people of the world, you need to pay attention to their language.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21475)

**Comment by Mugurell** [comment]
The app name is not currently translated (or translatable) in other languages it being part of the [static strings](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/res/values/static_strings.xml#L7).
@flodolo to confirm if this should be allowed.

**Comment by flodolo** [comment]
@Delphine is the person in charge of mobile projects and she's back, so localization questions should be redirected to her at this point ;-) 

We have branding guidelines that don't allow for transliteration for these cases (provided by legal, not our team).
https://mozilla-l10n.github.io/styleguides/mozilla_general/#brands-copyright-and-trademark

**Comment by Mugurell** [comment]
Closing per the above comment.
