### ISSUE TITLE
FNX3-16508 ⁃ Ability to force-refresh a tab

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/fenix#2681]
Long pressing the reload button in Fennec triggers a [forced refresh](https://xkcd.com/1854/) that bypasses the cache. Likely needs some additional GeckoView-support, because while it seems possible to pass `LOAD_FLAGS_BYPASS_CACHE` when loading an URL, there are currently no options possible for _re_loading the current page.

**Comment by buttercookie42** [comment]
Bugs [1618958](https://bugzilla.mozilla.org/show_bug.cgi?id=1618958) and [1623712](https://bugzilla.mozilla.org/show_bug.cgi?id=1623712) have been fixed, so it should be possible to implement this now, shouldn't it?

**Comment by issue-dispenser** [comment]
@boek
Would it be within UX guidelines to handle both this feature and #9956 at the same time by using a menu on long-pressing the refresh button (similar to how long-pressing the tab counter button opens a menu with 3 items)? In this case there would be two items: Refresh Bypassing Cache and Refresh In New Tab.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 200810 (Build #2015757107) GV 81.0a1 from 8/10 with the following devices:
- Pixel 2 (Android 9);
- Huawei P9 Lite (Android 7);
- Samsung Galaxy Tab S3 (Android 8);
- Nexus 5 (Android 6.0.1).

Verified this issue in normal browsing, private browsing, custom tab, homescreen shortcuts, PWA and the page is force-refreshed when long tapping the Reload button.
I will remove the qa:needed label for now.

**Comment by madb1lly** [comment]
Hooray! 😃
