### ISSUE TITLE
[Bug]: Prohibit immediate GuuuuuuuugelPray opening

### ISSUE THREAD

**Issue by powerbroker** [mozilla-mobile/fenix#26812]
### Steps to reproduce

Invoke "Open link" for "https://trk.mail.ru/c/phjpd1?id=630f952040d23432192afca3" in any application. Select  "...with Firefox"

### Expected behaviour

Firefox window appears and stays on. Web page is rendered in it.

In case the crap-o-sute can offer only piece of crapware but no HTML(XML/PDF/etc. Firefox is made to render), FF must ask user for permission to proceed with crapware(e.g. to open GuuuuuuugelPray).

### Actual behaviour

Firefox window blinks and GuuuuuugelPray begging for installing some crapware pops up. No questions, no warnings(e.g. web site tries to redirect to crapware installation, allow?) - FF just collapses and opens GuuuuuuuugelPray.

### Device name

Caterpillar S61

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

104.1.0

### Additional information

This looks like FF fails and some abnormal unpermitted activity starts in it. Please avoid such unprofessional behavior! 
All operations must occur on the user's command, and deviations from the course user set - only with his/her permission.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21476)

**Comment by marcel263** [comment]
Dear,when writing the report please use precise descriptions.

" GuuuuuuuugelPray" What does this mean?

**Comment by powerbroker** [comment]
" GuuuuuuuugelPray" - that's how people call GooglePlay))))

Enabling "Open links in apps" doesn't change described behavior unfortunatelly. Would be great, if on such pages things go *normal* way - manually 'open in app'. This is what i expect from FF.
