### ISSUE TITLE
Closed tabs should be reopened in their original position

### ISSUE THREAD

**Issue by tbertels** [mozilla-mobile/fenix#26810]
### Steps to reproduce

1. Close a tab
2. Open recently closed tabs
3. Select a tab to reopen

### Expected behaviour

The tab should reopen in its original position.

### Actual behaviour

The tab reopens at the top of the tabs.
That's even worse than just reopening the tab at the bottom like the most recent tabs.

### Device name

Samsung S10e

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

104.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21474)

**Comment by tbertels** [comment]
Note that since #10986 reopening the last closed tabs with the snackbar reopens it in its original position.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812113

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
