### ISSUE TITLE
[Bug]: [Debug build] Tab Pickup CFR is only displayed for a split second sometimes

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26825]
### Steps to reproduce

1. Install the latest Debug build updated from main.
2. Launch the app and complete the sign in flow.
3. Wait for the synced tabs section to be displayed on homepage.
4. Observe the Tab Pickup CFR.

### Expected behaviour

The Tab Pickup CFR is properly displayed.

### Actual behaviour

The Tab Pickup CFR is only displayed for a split second, then it is dismissed. 

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Debug build updated from main 1.0.2237

### Additional information

Notes:
- this issue has a low repro rate;
- the issue occurs regardless of orientation;
- the issue also occurs when firstly the user visits a website and returns to homepage so that the "Jump back in" section is displayed. 

https://user-images.githubusercontent.com/89388888/188481067-c9990a20-c420-4504-af45-e625067c2d38.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21481)

**Comment by SoftVision-LorandJanos** [comment]
I couldn't reproduce this issue on the latest official builds.
Tested on the latest Nightly 107.0a1 (2022-10-10) and on the latest Beta 106.0b5.
Devices used: Oppo Find X5 and Google Pixel 4 (Android 12).
@delia-pop could you check if you can still reproduce this on the latest builds?

**Comment by delia-pop** [comment]
I can no longer reproduce this issue on the latest Nightly 107.0a1 from 10/10 or Beta 106.0b5 with Google Pixel 6 (Android 12). I will close this ticket as CNR.
