### ISSUE TITLE
[Bug]: [Debug build] TCP CFR is dismissed when rotating the device 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26823]
### Steps to reproduce

1. Install the latest Debug build updated from main.
2. Launch the app and access a webpage.
3. Once the TCP CFR is displayed, rotate the device to change orientation.
4. Observe if the TCP CFR is still displayed.

### Expected behaviour

The TCP CFR is still displayed when changing the device orientation, until the user dismisses it.

### Actual behaviour

The TCP CFR is incorrectly dismissed when changing the device orientation.

### Device name

Google Pixel 6

### Android version

 Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Debug build updated from main 1.0.2237

### Additional information

Also reproducible when changing the orientation from Landscape to Portrait.
https://user-images.githubusercontent.com/89388888/188475154-bf7a01da-eed9-4901-a7a7-7d1b0f416327.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21480)

**Comment by Mugurell** [comment]
This is expected and will happen with most of our popups or menus.
It's to prevent issues with invalid anchorings upon rotating the screen.
