### ISSUE TITLE
Support UI testing composables by using testTag

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26826]
After discussing with the QA team it was apparent that testing is currently hindered by the inability / inefficiency of identifying composables on the screen.
`testTag`s are the approach recommended by the Compose team to help with that - https://developer.android.com/jetpack/compose/testing and we are already using them in A-C - https://searchfox.org/mozilla-mobile/search?q=testTag&path=&case=true&regexp=false

I propose starting to add (even retroactively for the scenarios raised by QA) `testTag`s to the composables used on Fenix with the following naming scheme:
```kotlin
<feature>.<composable>(.<optional other sub composables>)
```

Compose v1.2 will also allow better interoperability with UIAutomator by allowing the `testTag`s to be used in already common calls in the form of
> findObject(By.res(<`testTag`>)).

An update to this newer version is prepared in https://github.com/mozilla-mobile/fenix/pull/26763.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21482)

**Comment by Mugurell** [comment]
@sv-ohorvath / @AndiAJ to confirm that the new `testTag`s do help automation testing.

**Comment by AndiAJ** [comment]
Thanks @Mugurell for helping us out ! ❤️ 

I'll remove the label, and if problems occur while trying query and to interact with the items will ping you.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807300

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
