### ISSUE TITLE
[Bug]: [Debug build] Tab Pickup CFR is dismissed when rotating the device 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26824]
### Steps to reproduce

1. Install the latest Debug build updated from main.
2. Launch the app and complete the sign in flow.
3. Once the Tab Pickup CFR is displayed, rotate the device to change orientation.
4. Observe if the Tab Pickup CFR is still displayed.

### Expected behaviour

The Tab Pickup CFR is still displayed when changing the device orientation, until the user dismisses it.

### Actual behaviour

The Tab Pickup CFR is incorrectly dismissed when changing the device orientation.

### Device name

Google Pixel 6

### Android version

 Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Debug build updated from main 1.0.2237

### Additional information

Also reproducible when changing the orientation from Portrait to Landscape.

https://user-images.githubusercontent.com/89388888/188477660-23927c9c-4303-4cd8-9a13-d06b44346f98.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21479)

**Comment by Mugurell** [comment]
This is expected and will happen with most of our popups or menus.
It's to prevent issues with invalid anchorings upon rotating the screen.
