### ISSUE TITLE
[Bug] Crash in history & bookmarks menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#2682]
## Steps to reproduce
1. Open a few webpages.
1. Go to History.
    1. Expected behavior
History menu opened.
    1. Actual behavior
Crash.
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3202248/logcat.txt)
    1. Device information

* Android device: Galaxy S8, Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: 5/21 build

**Comment by ekager** [comment]
Related to #2688 @sblatz is fixing

**Comment by sblatz** [comment]
Closing as dup of #2688.
