### ISSUE TITLE
Firefox flicker sometimes when minimized

### ISSUE THREAD

**Issue by AndRo-Marian** [mozilla-mobile/fenix#26831]
https://user-images.githubusercontent.com/48178307/188564382-0ddf330d-049d-46f7-81e6-dfce2d241523.mp4

Same thing when opening it from minimized.
It's shows the desktop in flicker.

https://user-images.githubusercontent.com/48178307/188566319-3bc2d2b4-42aa-4066-8297-3e10f2011f1a.mp4

Huawei p10 lite, Android 8
Nova Launcher 6.2.19

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21484)

**Comment by marcel263** [comment]
reproducible 

Qualcomm -- Adreno (TM) 618

OpenGL ES 3.2 V@0502.0 (GIT@e1ac91e, I2b3b5fbd00, 1605636002) (Date:11/17/20)

Android 11 Samsung OneUI 3.1

**Comment by AndRo-Marian** [comment]
O notice a performance lost when having the Tabs menu opened. And doing this problem and appears weird artefacts. Same low animation performance when opening the Tabs menu.
