### ISSUE TITLE
[a11y] Can't click on "Show all" from homescreen with Talkback

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26833]
### Steps to reproduce
- Activate Talkback or other accessibility service
- Navigate on homescreen to a section header with a "Show all" button.

### Expected behavior
- A double tap gesture would trigger the "Show all" action.
- The content description read explicitly states that the gesture contains a button (when appropriately)

### Actual behavior
- A double tab gesture anywhere on the screen does not activate the "Show all" button.
- The content description read explicitly mentions a button only for the "Jump back in section" but not also for the "Recently visited section" 

### App versions affected
All 104 and later. Issue may be older than from just 104.

https://user-images.githubusercontent.com/11428869/188592129-6a8e5f04-b14a-4030-998c-a198517a8bdd.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21485)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809817

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by SoftVision-LorandJanos** [comment]
Tested with the latest Nightly 110.0a1 (2023-01-12) build.
The "Show all" buttons are selectable and clickable on homescreen.
Closing the ticket as verified.
