### ISSUE TITLE
Investigate if per-app language preferences works with Fenix language chooser

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#26839]
As Android 13 introduces the functionality of allowing users to choose the language of the app as part of the OS settings, we need to make sure our language chooser still works. 

https://developer.android.com/guide/topics/resources/app-languages

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21488)

**Comment by mcarare** [comment]
AFAIK this is optional, and we can keep our current flow. That would obviously mean our app would not be in the list of apps you can set app language for from the OS settings menu.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813857

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
