### ISSUE TITLE
[Bug]: Pocket stories are clipped horizontally

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26830]
### Steps to reproduce

Scroll the Pocket stories horizontally.

### Expected behaviour

Pocket stories (and other sections which are horizontally scrollable) shouldn't be clipped and allow to occupy the entire width of the screen. See https://github.com/mozilla-mobile/fenix/issues/21621

### Actual behaviour

Pocket stories are clipped horizontally. 
Functionality regressed seemingly following https://github.com/mozilla-mobile/fenix/issues/26444.

### Firefox version

106

https://user-images.githubusercontent.com/11428869/188562685-d41d157b-532a-47a9-acbc-9e5acebc4757.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21483)

**Comment by SoftVision-LorandJanos** [comment]
Managed to reproduce this issue with an earlier Nightly 106.0a1 (2022-09-05) build.
Verified as fixed on the latest Nightly 106.0a1 (2022-09-07) build.
Device used: Xiaomi Mi11 (Android 11).
Closing the ticket as verified.
![Screenshot_2022-09-07-10-11-53-007_org mozilla fenix](https://user-images.githubusercontent.com/48829350/188813223-5ec5b5e6-6807-47e8-a946-d19a8afdd689.jpg)
![Screenshot_2022-09-07-10-12-21-809_org mozilla fenix](https://user-images.githubusercontent.com/48829350/188813230-64ff0446-fe7f-4ecb-9260-d18d969e8137.jpg)
