### ISSUE TITLE
[Bug] Top shadows are clipped for Top Sites

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26834]
### Steps to reproduce
- Open the homescreen which contains some Top Sites

### Expected behavior
- The Top Sites show shadows on all 4 sides

### Actual behavior
- The top shadow is clipped

### App versions affected
All 104 and later. Issue may be older than from just 104.

![image](https://user-images.githubusercontent.com/11428869/188635021-9449dd56-9595-4ca0-b9be-f5947e92a5b4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21486)

**Comment by gabrielluong** [comment]
This should be fixed with https://github.com/mozilla-mobile/fenix/issues/26606

**Comment by Mugurell** [comment]
> This should be fixed with #26606

With https://github.com/mozilla-mobile/fenix/issues/26606 being ready for QA I'll also reopen this for QA to verify.
Saw recently another case in which a ticket for a bug was preemptively closed but it was never fixed or verified - https://github.com/mozilla-mobile/fenix/issues/23570
