### ISSUE TITLE
Extension sync

### ISSUE THREAD

**Issue by Gersonzao** [mozilla-mobile/fenix#26845]
**### What is the user problem or growth opportunity you want to see solved?**
I wish it was possible to sync all the extensions the user previously had installed.

**### How do you know that this problem exists today? Why is this important?**
It can save people's time.

**### Who will benefit from it?**
1: Users who constantly change their extensions.
2: Users who are trying Fenix for the first time and want everything they have in desktop (including the extensions that are available for Android), spending less time to set up things again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21493)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813859

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
