### ISSUE TITLE
FNX3-16511 ⁃ Clean up usage of map from sessions to tabs

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2684]
We have many places in the code we're mapping Sessions to Tabs individually. We should break this out into a function that can be called on sessions themselves rather than having the code duplication we have now.

**Comment by jonalmeida** [comment]
@sblatz do you have examples where this happens? :)

**Comment by gabrielluong** [comment]
Hello, I am interested on working this issue!

**Comment by jonalmeida** [comment]
Usage examples:
 - https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L666-L667
 - https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/collections/CollectionCreationUIView.kt#L263-L268

Finding the others is a good first bug too. 😄
