### ISSUE TITLE
Selecting text with mouse is impossible in Firefox for Android, it selects the entire bottom half of the page instead of where I select.

### ISSUE THREAD

**Issue by ETERNALBLUEbullrun** [mozilla-mobile/fenix#26840]
### Steps to reproduce

Goto https://duckduckgo.com/search?q=test
Try to select the title of the first result using a wired or wireless mouse. I tested with a trackball mouse and a traditional mouse that you have to move around on a pad.

### Expected behaviour

It should select the result title text when I leftclick on the beginning of the title and drag the cursor the end of the title.

### Actual behaviour

It selects the entire page.

### Device name

Google Pixel 5

### Android version

12

### Firefox release type

Firefox Beta

### Firefox version

105.0b3 (Build #2015900883), e314c25f1+

### Additional information

Much gratitude for any workarounds
If no workarounds are possible please tell me which files are responsible for this and how to submit a pull request and I will fix it myself.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22295)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814184

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
