### ISSUE TITLE
[Bug]: Improper grey highlight displayed on the "Sponsored" string on Top Sites

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26854]
### Steps to reproduce

1. Have the Sponsored shortcuts feature enabled.
2. Go to homepage and observe the Sponsored Shortcuts.

### Expected behaviour

The sponsored tiles are correctly displayed without visual defects.

### Actual behaviour

An improper grey highlight displayed on the last letter "d" in the "Sponsored" string.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version
Latest Nightly from 09/06.
Debug build updated from main 1.0.2237.

### Additional information

Observed while verifying https://github.com/mozilla-mobile/fenix/issues/26606.
This issue was previously reported and fixed in https://github.com/mozilla-mobile/fenix/issues/26302.

https://user-images.githubusercontent.com/89388888/188896731-d3460e7d-7796-42c2-b704-62a2c5442698.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21496)

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 107.0a1 (2022-09-21) build.
Device used: Oppo Find X5 (Android 12).
Closing the ticket as verified.
