### ISSUE TITLE
Steam discussions page

### ISSUE THREAD

**Issue by cybbro** [mozilla-mobile/fenix#26862]
Steam, any game page, go to discussions, its formatting is messed up.

Behavior:

![Screenshot_20220907](https://user-images.githubusercontent.com/10908092/188935816-6bc36521-e348-4252-a9e1-4342c31e9a6d.png)

How it should look:

![Screenshot_20220907-194945](https://user-images.githubusercontent.com/10908092/188935893-e8f334bc-e858-4448-93b2-e303218c9272.png)

* Android device: Xiaomi mi a3 / Android 11
Now, device doesn't seem to matter, as this issue persists on my TecLast tablet (Android 10), too. This issue has been here for months now, not just the latest version of Firefox.
* Fenix version: latest: 104.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21500)

**Comment by amocirean** [comment]
Hello @cybbro , thank you for submitting the issue.
I was not able to reproduce it on Nightly 107.0a1 nor Release 105.2.0. The topics and text alignment are correct, just like in your 2nd screenshot.
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

Devices Used: Huawei P40 Lite (Android 10), Google Pixel 6 (Android 13).

**Comment by cybbro** [comment]
> Hello @cybbro , thank you for submitting the issue. I was not able to reproduce it on Nightly 107.0a1 nor Release 105.2.0. The topics and text alignment are correct, just like in your 2nd screenshot. Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?
> 
> Devices Used: Huawei P40 Lite (Android 10), Google Pixel 6 (Android 13).

Hey, 107.0a1 on same mi a3 device works well! Layout is perfectly fine! I had this issue on my tablet, too but Nightly seems to work well there, too! So, I guess fix is already upcoming, and there is no need to keep this open, thanks!
