### ISSUE TITLE
Crash when webauthn invoked while permissions restricted on Google Play Services

### ISSUE THREAD

**Issue by charlesstrange2** [mozilla-mobile/fenix#26860]
### Steps to reproduce

1. Deny Google Play Services the "files and media" permission.
2. Open firefox
3. Visit a page that tries to invoke webauthn (eg github.com/signin)
4. See crash page. 

### Expected behaviour

On older versions, eg v102.2.1, a notification appears which indicates "Firefox is having trouble with Google Play Services" and the user is invited to fix that (or, as I do, add it to the list of notifications to silence)

The page remains otherwise usable. 

### Actual behaviour

Page is very briefly displayed before firefox gives a "firefox could not load that page" sad-emoji error page and offers options to close the tab.

### Device name

Asus Zenfone 8 (ASUS_I006D)

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

### Device logs

https://crash-stats.mozilla.org/report/index/971d7310-58b5-4206-946f-ea8790220907

### Additional information

Issue appears to have begun at the transition of 102 to 103

In Firefox Nightly v106.0a1 , using the about:config to flip "security.webauth.webauthn" to false permits the page to load without crash.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21499)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813860

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
