### ISSUE TITLE
[Bug]: Tabs send from desktop are received only after "Sync now" is clicked

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla-mobile/fenix#26866]
### Steps to reproduce

1. open Firefox for Android
2. open desktop Firefox (both synced to the same account)
3. send tab from desktop to Android

### Expected behaviour

- tabs should be received using push notification right away
- if not, tabs should be received upon opening Firefox for Android

### Actual behaviour

Tabs are not received until the "Sync now" button is manually clicked.
In the video below you can even see Firefox performing the sync when opened but the tab won't arrive.

Video (0:55):
https://mega.nz/file/ZKxXkApS#FaEDT1-tX-RYEKwwoTSd5-plPSeGfsI4S877ulfe3vU

See also:
https://github.com/mozilla-mobile/fenix/issues/16721

This has been broken for a very long time. I'm sending tabs to my Android Phone and Android Tablet and they never arrive unless I click "Sync now", no matter how long I use Firefox on the phone/tablet.

### Device name

motorola moto g200 5G

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21502)

**Comment by SoftVision-LorandJanos** [comment]
Hi @Juraj-Masiar! Thanks for the report!
I was able to reproduce the issue you described, using the latest Nightly 106.0a1 (2022-09-14).
Device used: Oppo Find X5 (Android 12).

**Comment by AdinaPetridean** [comment]
Verified on Firefox RC 107.1.0 build2 and Nightly 108.0a1 from 11/11 with Xiaomi Pad5 (Android 12). The tab is received via push notification right away. This issue was fixed by https://github.com/mozilla-mobile/fenix/pull/27767. 
@Juraj-Masiar, @derDiesel can you please retest? Feel free to reopen the ticket if this is still reproducible for you.

**Comment by Juraj-Masiar** [comment]
Using Beta 107 on my tablet and phone, I have to say I've noticed for the past few days it has been working quite nicely, giving me notification soon after starting Firefox, so it seems to be OK.

**Thank you very much for fixing this! :)**

**Comment by SoftVision-LorandJanos** [comment]
Closing this issue as verified.
