### ISSUE TITLE
Make the Nimbus MR Onboarding features true by default

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#26865]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21501)

**Comment by cpeterso** [comment]
We can enable the `tcp-feature` feature flag any time, but we don't want to enable the MR Onboarding flags by default before 2022-09-12!

```
"home-onboarding-dialog-new-users": true,
"home-onboarding-dialog-existing-users": true,
"sync-cfr": true,
"wallpapers-selection-tool": true,
"jump-back-in-cfr": true,
"tcp-cfr": true,
```

**Comment by cpeterso** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/26869 to enable the `tcp-feature` flag.
