### ISSUE TITLE
[Bug]: Synced tab is still not displayed in the Jump back in section after 1 minute

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla-mobile/fenix#26878]
### Steps to reproduce

1. On a mobile device login in with a Firefox account and open a few tabs.
2. On a second device login with the same account and observe the homepage.
3. On the second device open a few tabs and wait for or perform a manual sync.
4. Observe the home screen of the mobile device (Wait 15 seconds if needed).

### Expected behaviour

The last accessed tab from the second device is displayed in the Jump back in section in maximum 15 seconds.

### Actual behaviour

Sometimes the last accessed tab is displayed after a restart or after a manual re-sync.

### Device name

Huawei P20

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

Nightly (2022-09-08)

### Additional information

According to a comment in https://mozilla-hub.atlassian.net/browse/QA-1563 : 
"In general, once another device has successfully synced it should be available on Android in no more 5 more additional seconds (plus any time it takes to retrieve it from the network). A rule-of-thumb could be about 15 seconds from any one device to any other."

The internet speed was around 43,86Mbps.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21511)

**Comment by MatthewTighe** [comment]
For step 4: was the home screen open the whole time and left idle? Similar to https://github.com/mozilla-mobile/fenix/issues/26883, we only expect the home screen to update when it is navigated to. It is not expected to automatically update if it is left in an open and idle state.

**Comment by SoftVision-LorandJanos** [comment]
Yes, the screen was open the whole time and it was idle, but sometimes the card was updated without closing the app, resyncing or even navigating away and back to homescreen. But if it is not expected to update automatically, I think we can close these two issues as invalid.

**Comment by MatthewTighe** [comment]
>  but sometimes the card was updated without closing the app, resyncing or even navigating away and back to homescreen.

That's interesting. Was that something that was seen frequently? It could happen if another part of the app did a sync while the screen was open. For example, we have an automatic background sync that happens every 4 hours. I would not expect this to be happening regularly, however.

In any case, I believe it is not the expectation. I'll double-check with product and close these two issues upon confirmation.

**Comment by SoftVision-LorandJanos** [comment]
It wasn't very frequent, it happened every time is when the phone screen was getting to a stand-by state, but before it locked, and when I brought the screen back, it did make the switch, but I don't know what exactly happened with the app in the background.
We'll wait for you to double check, so these can be closed, and the test cases updated with more details about when exactly the card is updated, or left open if it's the expected result. Thank you!

**Comment by delia-pop** [comment]
Hi, this behavior is also encountered on the latest Nightly 106.0a1 from 09/13 with Lenovo Yoga Tab 11 (Android 11).

While testing the MR Onboarding flow, after signing in on Fenix by scanning the QR code from Desktop a sync is performed and if the user awaits on the homepage, usually in less than 15 seconds the Synced Tab section is displayed automatically.

On one occurrence the section was not displayed automatically and after ~35s a manual sync was performed, after which the section and CFR were displayed.  

https://user-images.githubusercontent.com/89388888/189940538-26786194-e03a-47e2-a084-8401900ed980.mp4

**Comment by MatthewTighe** [comment]
> Hi, this behavior is also encountered on the latest Nightly 106.0a1 from 09/13 with Lenovo Yoga Tab 11 (Android 11).
> 
> While testing the MR Onboarding flow, after signing in on Fenix by scanning the QR code from Desktop a sync is performed and if the user awaits on the homepage, usually in less than 15 seconds the Synced Tab section is displayed automatically.
> 
> On one occurrence the section was not displayed automatically and after ~35s a manual sync was performed, after which the section and CFR were displayed.
> screen-20220913-145956_Trim.mp4

@delia-pop  Is this a reproducible issue when interacting with onboarding? I would prefer to file a separate issue with the focus around onboarding in that case. If the user has signed in before dismissing onboarding I would expect the synced tab to show up in the usual amount of time.

> It wasn't very frequent, it happened every time is when the phone screen was getting to a stand-by state, but before it locked, and when I brought the screen back, it did make the switch, but I don't know what exactly happened with the app in the background.

@SoftVision-LorandJanos This seems like it may just be triggering the usual lifecycle events that happen when the home screen is navigated too. 

I also did confirm that we would not expect an idle home screen to receive updates from a remote device, so I will close these two issues.
