### ISSUE TITLE
Inconsistencies between Figma and Firefox Nightly for "Privacy protection by default" icon 

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26879]
### Steps to reproduce

1. Install Firefox and launch it. 
2. Verify the "Privacy protection by default" icon.

### Expected behaviour

The "Privacy protection by default" icon is same as in Figma.

### Actual behaviour

There are inconsistencies between Figma and Firefox Nightly for "Privacy protection by default" icon 

### Device name

Xiaomi Pad5 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.a1 (08.09.2022)

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/189128717-97cf51e8-24f8-406e-a9b4-2c66e552c985.png" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21512)

**Comment by AdinaPetridean** [comment]
This issue is also reproducible on Firefox Beta 106.0b4 with Sony Xperia (Android 6.0.1).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812470

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
