### ISSUE TITLE
Consider increasing the text under "HTTPS-Only Mode"

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#26877]
### Steps to reproduce

1. Have Google Accessibility Scanner installed.
2. Go to Settings - Privacy & Security - HTTPS-Only Mode.
3. Scan the HTTPS-Only Mode page.

### Expected behaviour

No suggestions are made.

### Actual behaviour

The following is a list of opportunities to improve the accessibility of Firefox Beta. Each item corresponds to an outlined area on the attached screenshot.

Touch target
org.mozilla.firefox_beta:id/https_only_summary
This item's height is 32dp. Consider making the height of this touch target 48dp or larger.

Link text
org.mozilla.firefox_beta:id/https_only_summary
The link text "Learn more" may not independently convey the link's purpose.

![Screenshot_20220908-151124_Accessibility Scanner](https://user-images.githubusercontent.com/40694158/189119221-af2f71ac-326c-43b3-bfd9-dac4726de0ed.jpg)

### Device name

Samsung Galaxy Note 8 

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

105.0b5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21510)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813194

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
