### ISSUE TITLE
Consider increasing the "x" close button from the tabs' tray opened tab

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#26876]
### Steps to reproduce

1. Have Google Accessibility Scanner installed.
2. Have an opened tab, at least.
3. Open the tabs tray.
4. Scan the tabs tray view.

### Expected behaviour

No suggestions are made from the Accessibility scanner.

### Actual behaviour

The following is a list of opportunities to improve the accessibility of Firefox Beta. Each item corresponds to an outlined area on the attached screenshot.

Touch target
org.mozilla.firefox_beta:id/mozac_browser_tabstray_close
This item's size is 24dp x 24dp. Consider making this touch target 48dp wide and 48dp high or larger. A parent container may be handling touch events for this item. If selecting the larger container performs the same action as selecting this item, consider defining this item as not clickable. If a different action is performed, consider increasing the size of this item.

![screenshot_Firefox Beta_org mozilla firefox_beta id-mozac_browser_tabstray_close_8589934624_2022-09-08-14 32 04](https://user-images.githubusercontent.com/40694158/189112658-08e107f8-4cfd-478f-ac55-bdee3cb6f459.png)

### Device name

Samsung Galaxy Note 8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

105.0b5

### Additional information

Also reproducible for the private tabs.
Also reproducible on the latest Firefox Nightly 106.0a1.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21509)

**Comment by AdinaPetridean** [comment]
This issue is still reproducible on the latest Nightly 111.0a1 from 20/01/2023 and Firefox 110.0b2 with Nokia 6 (Android 7.1.1).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813193

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
