### ISSUE TITLE
Remove the layer behind the wallpaper thumbnails in the wallpaper settings screen. 

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26870]
Now that the wallpapers setting screen does not include additional configuration options besides selecting wallpapers, we can remove the unnecessary background layer behind the thumbnails. Instead, it should be the same color as the rest of the settings pages.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21505)

**Comment by delia-pop** [comment]
Verified as fixed on latest Nightly 106.0a1 from 09/07 with Google Pixel 6 (android 13).

![WallpapersMenu](https://user-images.githubusercontent.com/89388888/189163747-1fb853ab-7f6a-4d52-8fac-e6917104dc51.png)
