### ISSUE TITLE
[Bug]: The latest synced tab is displayed in the Jump Back In section until a restart is performed

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#26883]
### Steps to reproduce

1. On a mobile device login in with a Firefox account and open a few tabs;
2. On a second device login with the same account and observe the homepage;
3. On the first device go to Settings -> Account setting and log out or disable Open tabs sync;
4. Observe the home screen of the second device.
5. Restart Firefox;
6. Observe the home screen of the second device.

### Expected behaviour

At step 4 the last accessed tab from the first device should disappear since the user signed out or disabled tab sync.

### Actual behaviour

A restart of Firefox is required for the synced tab to disappear.

### Device name

Google Pixel 6

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 2022-09-08

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21515)

**Comment by MatthewTighe** [comment]
For step 4: was any navigation performed at all? I would expect the card to disappear if, for example, a tab was opened and then the home screen was returned to. 

Having a home screen that is open and idle react to changes on another device would require a level of consistent network polling that we probably want to avoid.

**Comment by LaurentiuApahideanSV** [comment]
I retested the issue and if navigation is performed at step 4 the sync tab card will disappear. I will close this issue as per Matthew's comment.
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
