### ISSUE TITLE
The color for "Read privacy notice" and "Sign in" buttons is not visible in dark mode on Xiaomi Pad 5

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26880]
### Prerequisites:
Change to the dark theme on your Android device.

### Steps to reproduce
1. Install Firefox and launch it.
2. Verify the "Read privacy notice" and "Sign in" buttons.

### Expected behaviour

Color is adjusted to provide a good contrast ratio.

### Actual behaviour

The color for "Read privacy notice" and "Sign in" buttons is not visible in dark mode on Xiaomi Pad 5

### Device name

Xiaomi Pad5 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.a1 (08.09.2022)

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/189133246-b111829d-a488-42f7-a9da-373c2a7d1839.JPEG " width="50%" />
<img src="https://user-images.githubusercontent.com/108326843/189132970-dbdf126b-ff88-4dec-9ac7-01448ab36248.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21513)

**Comment by AdinaPetridean** [comment]
This issue is also reproducible on Firefox Nightly 106.0a1 09/13 with Xiaomi Pad5 (Android 11) device.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812469

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
