### ISSUE TITLE
Change Home Section Headers to use Headline6

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#26888]
Got a request from @Kate-Galetski to change the Home Section Headers to use Headline6 from Headline7. 

This is illustrated in https://www.figma.com/file/d7l1iGabQYqnLcnQbHDGzM/Wallpaper-2.0-%2B-Onboarding-v106?node-id=5536%3A189429

<img width="816" alt="Screen Shot 2022-09-08 at 12 17 43 PM" src="https://user-images.githubusercontent.com/1190888/189173599-90de33c9-f2e5-4328-91cd-1228382fe475.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21517)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 106.0a1 2022-15-09 and the headers are according to the Figma specifications.
![1663253147366](https://user-images.githubusercontent.com/50983519/190446262-71e21d18-2d23-4da9-9e59-5896b753466f.JPEG)
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
