### ISSUE TITLE
[Bug]: No "manage account" option for signed in Sync users

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/fenix#26899]
### Steps to reproduce

1. Sign in to sync
2. Go to settings
3. Look for a way to manage your account or change your password

### Expected behaviour

You should be able to change your password

### Actual behaviour

You can't

### Android version

11

### Firefox release type

Firefox Nightly

### Firefox version

today

### Additional information

This seems more than an inconvenience - if you lost another connected device and want to protect your account by changing the passoword, there's no obvious way to do that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21519)

**Comment by SoftVision-LorandJanos** [comment]
Hi @mhammond! Thanks for your report!
As far as I know this functionality wasn't implemented.
I can change the label to "feature request" since it's not considered a bug.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810630

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
