### ISSUE TITLE
Add preview to PocketStoriesComposables that validates Modifier.onShown

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/fenix#26891]
As per this [comment thread](https://github.com/mozilla-mobile/fenix/pull/26847#discussion_r965087486), we should use `inComposePreview` sparingly and only when it's necessary and the short-circuited functionality isn't needed for _any_ previewing.

To that end, the usage of `inComposePreview` inside `Modifier.onShown` should be removed, and the Modifier extension function should instead be refactored to not break local previews. I believe the line of code that breaks the existing preview is:

> val isToolbarPlacedAtBottom = context.settings().shouldUseBottomToolbar

The boolean could be refactored to instead to be a parameter in `Modifier.onShown`  and `PocketStories`.

Once `isToolbarPlacedAtBottom` has been refactored, a preview should be made (without using the Pocket composables) that allows for validation of `Modifier.onShown`. Since the Modifier extension has a lambda, a simple toast/snackbar/log print should suffice for testing the `onVisible` callback.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21518)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813185

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
