### ISSUE TITLE
[Bug]: Light theme and app UI is altered on OPPO A15s when Dark mode is enabled

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26903]
### Steps to reproduce

1. Enable Dark mode from device settings.
2. Launch the latest RC build 104.2.0.
3. From the onboarding tour or Settings > Customize select the Light theme.
4. Observe the UI throughout the application.

### Expected behaviour

Light theme is set and no visual defects are displayed. 

### Actual behaviour

When selecting the Light theme form Fenix, a dark shade of black is displayed instead and the entire app UI is altered.

### Device name

OPPO A15s

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

104.2.0 build1/build2

### Additional information

This is not reproducible on other devices, and is not encountered on Firefox Nightly or Beta on the affected device.

https://user-images.githubusercontent.com/89388888/189367103-99e9906e-6961-47f5-b803-9a2ecfe257d8.mp4

https://user-images.githubusercontent.com/89388888/189367140-f00a052d-173a-431d-bdec-00fc4e5f4932.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21522)

https://user-images.githubusercontent.com/108326843/191708885-9f28e42d-9bc4-496a-9736-bbf7cf8fd593.mp4

**Comment by AdinaPetridean** [comment]
Hello,
Please notice I was able to reproduce this issue on Xiaomi Pad5 (Android 11) with Firefox Nightly 107.0a1 09/21. Please check the new video attached.
