### ISSUE TITLE
Updated Wallpapers Settings Page Design

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#26908]
Wallpaper settings page is updated to new [attached design](https://www.figma.com/file/d7l1iGabQYqnLcnQbHDGzM/Wallpaper-2.0?node-id=5551%3A191299)

    Wallpaper options are split into classic and seasonal

    Up to 6 wallpapers (including null) can be included in classic section

    Up to 6 wallpapers can be included in the seasonal section

    There is a heading for classic wallpapers (use string from Figma)

    There is a heading, description, and learn more link for seasonal wallpapers (use strings from Figma)

        There is also a backup description string that’s landed & localized

        Learn more link points to TBD

Selecting a wallpaper in the settings menu will set your homepage background to that wallpaper. You can exit the settings by clicking the back button

Selecting a wallpaper that has not been downloaded will show a loading indicator while the wallpaper downloads, similar to the wallpaper selection tool:

     

    There is a learn more button for seasonal wallpapers that takes users to a SUMO article (link TBD)

    If the wallpaper thumbnails are not downloaded when a user navigates to the settings page, then only the classic wallpapers will be shown

    Changes are behind the wallpapers v2 feature flag

    Telemetry captured

        Clicks on each wallpaper (indicator of which one)

        How many users have a wallpaper set (existing)

        How many users have each wallpaper set (existing)

        Clicks on link to learn more

Success Metrics

    More users select a wallpaper

    More users have a wallpaper set

    (Learning) Indication of which wallpapers users are most interested in

    (Learning) How many users click to learn more, as an indication of interest in the feature

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21525)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/20 with Google Pixel 6 (Android 13). The Wallpapers settings screen is displayed according to the specification and design, except for the "Learn more" link from the seasonal collection which will only be displayed then the URL will be available, as explained by Sarah in https://github.com/mozilla-mobile/fenix/issues/27024. 
I will leave the ticket opened and the qa:needed label until the "Learn more" link  will also be displayed. 

![1663693153436](https://user-images.githubusercontent.com/89388888/191445782-4e4e9591-7503-4c5a-a877-71efbf531d1b.JPEG)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/22 with Google Pixel 6 (Android 13). 
![1663837636771](https://user-images.githubusercontent.com/89388888/191709427-0c9fd4c5-e849-45fb-8eff-403117aaa337.JPEG)
