### ISSUE TITLE
Reevaluate view model for collection creation flow

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2690]
[In this PR](https://github.com/mozilla-mobile/fenix/pull/2652/files), @boek and I decided to land with the given implementation, but to come back and reevaluate how we handle the view model when transitioning between the fragments, and passing data to the many adapters used in the complicated view. 

Either the UI should use the view model as its source of truth, OR we should be using action emitting for everything.

**Comment by sblatz** [comment]
We should also look at the usage of `cachedTabCollections`.

**Comment by NotWoods** [comment]
Possibly covered by #4731?

**Comment by sblatz** [comment]
Agreed, @NotWoods can you please reference this issue in that commit? 😄
