### ISSUE TITLE
[Bug]: home not working after update / wallpaper not set

### ISSUE THREAD

**Issue by Matth7878** [mozilla-mobile/fenix#26918]
### Steps to reproduce

Update Nightly from one previous to Saturday 10
Try to tap on address bar or to add a tab

### Expected behaviour

Home should be displayed

### Actual behaviour

Fenix freeze

### Device name

OnePlus 7

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 (Build #2015903211)

### Additional information

Going to settings and applying a wallpaper solved it for me.
I think freezing occur because Fenix had no information about which wallpaper to apply and so was stuck.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21531)

**Comment by porcospino44** [comment]
Confirming the freezing behaviour. Setting a wallpaper seemingly fixed it for me as well.

Device is Samsung Galaxy A32 with Android 12.

**Comment by LiberaVeritas** [comment]
Confirming on Samsung Galaxy A5(2017) with Android 8. Toggling the wallpaper setting to a different one and back fixed it.

**Comment by kuba2k2** [comment]
Also confirming, additionally it froze right after opening (trying to load previous page), started working after opening a link from other app. Changing homepage wallpaper fixed the address bar and new tabs. 

Resurrection Remix, Android 10, Redmi Note 6 Pro

**Comment by csadilek** [comment]
Thanks for filing, I will dupe this to https://github.com/mozilla-mobile/fenix/issues/26918. The team is working on it.
