### ISSUE TITLE
Remove code that re-enables old Fennec extensions when they are re-supported in Fenix

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26911]
For Fenix users that have a migrated Fennec profile, we have some code that will try re-enable old extension if the extensions are "re-supported" in a new Fenix version. We don't want old, untested Fennec 68 extensions to be automatically re-enabled in Fenix.

When we "re-support" an old extension for Fenix, we want the extension to reappear in Fenix's Add-ons UI, but stay disabled until the user manually re-enables it in the Add-ons UI.

TBD: Do we need to force an AMO update check when re-supporting an extension? Fenix has not been updating unsupported Fennec extensions, so users will have a very old version. Fenix checks AMO for new extension updates every 12 hours, so maybe that's frequent enough we don't need to force an update? What is the likelihood that an old extension would be re-supported and the user notices it in their Add-ons UI and manually re-enables it before the 12-hour extension update check?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21527)

**Comment by Amejia481** [comment]
To add more details:


- [Here](https://github.com/mozilla-mobile/android-components/blob/d51ae58a736cf7de66ee1085708bf9f17de26173/components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt#L154-L163)  is where we check and enable migrated add-ons, at the moment we would like to remove the [notification](https://github.com/mozilla-mobile/android-components/blob/d51ae58a736cf7de66ee1085708bf9f17de26173/components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt#L168) and the [enabling](https://github.com/mozilla-mobile/android-components/blob/d51ae58a736cf7de66ee1085708bf9f17de26173/components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt#L155-L162) part, instead we would like to [update](https://github.com/mozilla-mobile/android-components/blob/d51ae58a736cf7de66ee1085708bf9f17de26173/components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt#L165) any migrated add-on.

- For users to be able to enable back the add-ons, they will need to go to the UI and manually re-enable, but we will need to update Fenix to support that use case, on the installed add-on screen every time user hit enable, we will need [enable](https://github.com/mozilla-mobile/fenix/blob/2ee00374dd4320f0d5511e5c8d08e121d0af80e4/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt#L127-L148) twice for those add-ons, one with the   flag `source: EnableSource = EnableSource.APP_SUPPORT` and another with  `source: EnableSource = EnableSource.USER`, hints on how to detect if the add-on was [migrated](https://github.com/mozilla-mobile/android-components/blob/d51ae58a736cf7de66ee1085708bf9f17de26173/components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt#L151).

**Comment by delia-pop** [comment]
@cpeterso We attempted to test this using a Fennec build from [here](http://archive.mozilla.org/pub/mobile/nightly/2019/). The thought process was to sign in with a valid Firefox account > install several extensions > update to Fenix and sign in with the same account. 
However: 
- we were not able to access the "Sign in" page from Fennec;
- updating Fennec to Fenix does not work, as Fenix is not overwriting Fenix, instead is installed individually. 

Without syncing the account we are not able to verify this issue. Is there a workaround or a better option?

![1667402049534](https://user-images.githubusercontent.com/89388888/199539999-740cc244-43af-4325-87b0-9dc7e5abfd3f.JPEG)

**Comment by cpeterso** [comment]
@delia-pop Summarizing a conversation from Slack: given these Fennec issues, I don't think testing this would not be a good use of your time.

This code change was made to protect Fenix users from ancient versions of Fennec add-ons that might be reactivated before Fenix has a chance to install the add-ons' latest version from AMO. This is expected to be a tiny corner case, so I think you can close this issue.

**Comment by delia-pop** [comment]
Understood, thank you for further inquiring. I will close this ticket and remove the QA needed label.
