### ISSUE TITLE
[Bug]: Fenix home screen freezing, only showing background

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#26914]
### Steps to reproduce

Since today fenix nighlty compiled from github when opened just show nothing but a dark background .
to be sure nothing of my setting was interfering I ve just compiled fenix nighlty from github as it's provided and bug still persist
screenshot :
https://i.imgur.com/XFefn8c.png
can please someone confirm this ?

### Expected behaviour

Fenix just just work 

### Actual behaviour

once app is launched nothing happens 

### Device name

poco f3

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21528)

**Comment by cpeterso** [comment]
@ale82to Do you see this problem with the official Fenix Nightly builds? Or just the local build you compiled?

The latest official Nightly (106.0a1 build 2015903211) works fine for me (on a Samsung Galaxy A32), so I wonder if this is a problem with your local build or something unique about your device.

**Comment by ale82to** [comment]
problem happened for both official and my compiled nighlty build ,luckily I ve root just deleting 2 files under shared_pref in fenix nighlty cleared the issue (org.mozilla.fenix_preferences.xml and fenix_preferences.xml),now with same exactly setting as before everything is still fine .

**Comment by jandem** [comment]
I ran into this too today with the official Nightly build (build 2015903211). A reinstall of the app fixed it.

I could still load pages through the web view in other applications and select "open in Firefox Nightly". Attempting to use the browser UI then resulted in freezes.

**Comment by ale82to** [comment]
> I ran into this too today with the official Nightly build (build 2015903211). A reinstall of the app fixed it.
> 
> I could still load pages through the web view in other applications and select "open in Firefox Nightly". Attempting to use the browser UI then resulted in freezes.

if you have root deleting fenix prefs as described above is enough without reinstalling .

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1388998

**Comment by quadriflax** [comment]
Just downloaded the following version from Play store and it seems to have resolved the issues for me:

106.0a1 (Build #2015903505), 9cae449e0+
AC: 106.0.20220911143157, b4b2b4a186
GV: 106.0a1-20220911091736
AS: 94.1.0

**Comment by cpeterso** [comment]
> Just downloaded the following version from Play store and it seems to have resolved the issues for me:

Thanks for verifying. I think we can close this bug now that #26922 and #26923 have been reverted. Those patches will need to be fixed before they land again.
