### ISSUE TITLE
Enable TCP by default in ETP Standard, Strict, and Custom modes

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#26910]
The TCP setting ("Isolate cross-site cookies") was added to ETP's custom settings in #26869, but now we would like to enable TCP by default in ETP Standard, Strict, and Custom modes. Also, TCP should be disabled when ETP is disabled.

Assigning to @Mugurell because he fixed #26869.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21526)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Fenix Nightly 106.0a1 2022-09-13 and the Total cookie protection feature is enable by default in all modes.
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
