### ISSUE TITLE
[Bug]: open in app not working for flipkart app

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#26917]
### Steps to reproduce

Open the click https://www.desidime.com/deals/loot-happilo-masterlink?utm_source=internal&utm_campaign=telegram&utm_medium=c_tg_auto

Click the flipkart link
It should open in app but instead in the browser itself some referrer link opening ad.adminad.com

Even. I tried in fresh installation same issue
Whereas in other chromium browsers working fine

### Expected behaviour

Site should open in app 

Note: if open in app is disabled in both firefox and chrome, the link is not working but when enabled somehow chromium browse is able to resolve and open in the respective app

### Actual behaviour

Site not redirecting to app

### Device name

asus rog3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

https://user-images.githubusercontent.com/58127841/189508395-4ca0e905-a3d4-41e9-abde-c73adefc38f6.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21530)

**Comment by SoftVision-LorandJanos** [comment]
Hi @sheikh-azharuddin! Thanks for your report!
I couldn't reproduce your issue, as it did in Chrome, on the latest Nightly the page was opened in the app.
Please see if you still reproduce it with the latest Nightly.

https://user-images.githubusercontent.com/48829350/190148830-89a50238-760f-410b-8ffe-185040485c00.mp4
