### ISSUE TITLE
UBlock My Filter Page Buggy

### ISSUE THREAD

**Issue by iSmokeMid69** [mozilla-mobile/fenix#26924]
### Steps to reproduce

Ubo>My Filters

Using UBO On FireFox Android For 3-4 Months Now...Have Over 1000+ Custom Rules In My Filters...But The Real Pain Is The My Filters Page Feels Like Super Buggy Or Glitchy...It Wont Let Me Select Lines,After Trying Hard To Select The Line The Page Moves Up Or Down By 100 Lines,Copy & Paste Is Also Very Problematic & Automatically Creates A Empty Extra Line After A Paste & Sometimes The Filter List Line Number Gets Copied With The Filter Itself..Had To Use 3rd Party Editors To Modify It With Peace & After That I Try To Import That File And Filters Wont Update Or Change..Have To Reset UBO Then The Changes Appear..If UBO Lets Every Copy,Paste,Select Action To Be Done By Android System,KeyBoard Itself Rather Than UBO's Own Selector I Think This Would Be Solved?..I Am Not Sure If UBO Has Its Own Selector Or Something

### Expected behaviour

My Filter Page Copy,Paste Should Work Like A Normal Text Editor

### Actual behaviour

Mentioned In Steps To Reproduce

### Device name

Poco X3 Pro

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21535)

**Comment by Timshel** [comment]
Had a quick look, with no content it initially appear to work but it starts to break with pasting content in a middle line then deleting it it multiple times.

The field rely on [codemirror](https://github.com/codemirror/codemirror5), quickly tried to reproduce using https://codemirror.net/try but it's configured differently and probably running the latest version as opposed to the one included in UBlock Origin:  5.59.2 from 03/2021 (https://github.com/gorhill/uBlock/blob/master/src/lib/codemirror/lib/codemirror.js)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813861

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
