### ISSUE TITLE
[Bug]: Latest nightly does not load on tablet; blank screen

### ISSUE THREAD

**Issue by quadriflax** [mozilla-mobile/fenix#26921]
### Steps to reproduce

1. Launch Firefox Nightly app.

### Expected behaviour

App should load.

### Actual behaviour

App doesn't load anything but blank screen. No menus or anything visible. App stops responding.

### Device name

Samsung Tab A 10.1 (2019)

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

### Device logs

Unable to obtain logs as app does not load anything except a blank screen.

### Additional information

Previous Nightly version from Play store did not have any issues. Only after updating to release from 10 September 2022 did this start. Beta and release versions are working fine.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21534)

**Comment by teakvinyl** [comment]
I'm also having the same issue with the latest update to Firefox Nightly on my Samsung S20+, Android 12

**Comment by quadriflax** [comment]
Im noticing that if I launch the browser from another app, it seems to load the page fine. If I close the tab and try to go back to home screen, that's when it will freeze up again and display a blank screen. It appears to be related to whatever it's trying to load for that home page. Are you seeing the same?

**Comment by quadriflax** [comment]
EDIT 3: tapping on the address bar causes it to freeze. The link from external app loads fine, but attempting in anyway to navigate elsewhere will cause the freeze.

**Comment by csadilek** [comment]
Thanks for filing, we're tracking in https://github.com/mozilla-mobile/fenix/issues/26914.
