### ISSUE TITLE
[Bug]: New tab in nightly hangs Firefox

### ISSUE THREAD

**Issue by moody31415** [mozilla-mobile/fenix#26927]
### Steps to reproduce

1. Have a tab open
2. open your list of open tabs
3. click the purple "plus" to create a new tab

### Expected behaviour

New tab opens

### Actual behaviour

App returns to open tab, and is hung - cannot scroll, cannot tap on the ... menu or the list of tabs. Firefox is hung. If you wait long enough, you get the Android hung dialog.

### Device name

Samsung S8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1

### Device logs

This doesn't generate a crash.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21536)

**Comment by csadilek** [comment]
This is due to https://github.com/mozilla-mobile/fenix/issues/26927. There should be a new update in the Play Store with the fix.

```
106.0a1 (Build #2015903505), https://github.com/mozilla-mobile/fenix/commit/9cae449e0664b4b236a02608be912325457d2b61+
AC: 106.0.20220911143157, b4b2b4a186
GV: 106.0a1-20220911091736
AS: 94.1.0
```
