### ISSUE TITLE
[Bug]: (ANDROID)Issue with showing address suggestions from my history

### ISSUE THREAD

**Issue by Flying-Miko** [mozilla-mobile/fenix#26920]
### Steps to reproduce

1.Have a browser history

2. write something in address bar

### Expected behaviour

Since I have enabled everything except for "show search engines" and "show voice search" in settings->search->addressbar, I should be able to get multiple different suggesstions based on my browser history, including multiple different sites I have visited before (in other words, in my browser history) but are not bookmarked.

### Actual behaviour

Instead of getting a number of different suggestions, I now only at best get 2 suggestions from my browser history.

Suggestion from bookmarks are fine though, I get a bunch of diffrent suggestions from my bookmarks. The problem is I can only get 2 suggestions based on the sites in my history that are not bookmarked

### Device name

Samsung Galaxy A71

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

104.2.0 (Build #2015902899), 0f9ad767a+ AC: 104.0.10, 7b0499725d GV: 104.0.2-20220902153754 AS: 93.7.2

### Additional information

This issue seems to presist after updates.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21533)

**Comment by lindongbin** [comment]
#25913
