### ISSUE TITLE
The 2 dots icon is displayed for a split second on the Welcome card for an already signed in user

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26938]
### Steps to reproduce

1. Have an older Fenix version installed and sign in with a valid account.
2. Update Fenix to the latest version in which the new onboarding screen for upgrading users is enabled (debug build).
3. Launch Fenix and observe the Welcome card.

### Expected behaviour

The Two dots icon is not displayed for an already signed in user. Tapping the "Get started" button will dismiss the onboarding and display the homepage.

### Actual behaviour

The 2 dots icon is displayed for a split second on the Welcome card for an already signed in user. 
Note that before the icon disappears, if the user taps the "Get started" button, the Sync card is displayed. Tapping the "Sign in" button will dismiss the onboarding and display the homepage.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Debug build updated from main 1.0.2238

### Additional information

https://user-images.githubusercontent.com/89388888/189672292-9d1eff22-be11-4975-8994-6aefd5b5823e.mp4

https://user-images.githubusercontent.com/89388888/189672003-20841c92-5ae2-4838-a234-9460bc1625e3.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21544)

**Comment by gabrielluong** [comment]
Discussed this with @MatthewTighe. Currently, we observe the `SyncStore` to check if the user is signed into sync. It seems like we are displaying the Onboarding before the `SyncStore` is fully ready. 

We could investigate increasing the timing of the `SyncStore` to get the account information available sooner, but the fact might just be that we don't have account information available immediately on app startup. 

Given the timing of things, I think we're doing the best we can do given the technical limitations, and it is probably not investing much more effort here before the MR given the screen will be shown only once. 

Some alternative solutions would be to introduce a cache to store the account status. However, it was noted that there was some pushback against this idea. If we intend to show the onboarding cards in future releases, it might be worthwhile to investigate further into either ensuring the SyncStore is ready when the app is started or introducing the cache as described.

**Comment by MatthewTighe** [comment]
@gabrielluong I discovered that we look to be caching whether a user has signed in [in this observer](https://searchfox.org/mozilla-mobile/rev/89f662c413b63fa69c4660bc1a09b2614cb73bcc/fenix/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt#224) so we could potentially reuse that to fix this bug.

**Comment by delia-pop** [comment]
This is also reproducible on RC 108.1.0 with Xiaomi Redmi Note 8T (Android 9).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812467

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
