### ISSUE TITLE
Some Pocket articles are displayed without title and picture 

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26935]
### Steps to reproduce

1. Navigate to the homepage.
2. Scroll down to the "Thought-provoking stories" section.
3. Select different topics and observe the suggested articles. 

### Expected behaviour

Title and photo should be displayed for all articles. 

### Actual behaviour

The title and phone are not displayed for some pocket articles. 

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 from 09/12

### Additional information

Note that for the article from glamour.com, the image is also not displayed in the "Jump back in" section. 
Might relate https://github.com/mozilla-mobile/fenix/issues/24362.

<img src="https://user-images.githubusercontent.com/89388888/189659951-44bddcef-9ac1-4303-a57f-1af21c8f0908.jpg" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21542)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807370

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
