### ISSUE TITLE
Consider increasing the "Standard"  and "Strict" options  in "Privacy protection by default" on tablets

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26933]
### Steps to reproduce

1. Have Google Accessibility Scanner installed.
2. Perform a "clear data" and launch the Fenix application. 
3. Scan the "Onboarding" page. Observe the "Privacy protection by default" section.

### Expected behaviour

No suggestions are made from the Accessibility scanner.

### Actual behaviour

Consider making this clickable item larger. This item's hight is 38 dp. Consider making the height of this touch target 48 dp or larger.

### Device name

Sony Xperia (Android 6.0.1)

### Android version

Android 6

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 09/11

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/189636882-d75f2fa7-101c-474b-a6f8-e750d7a645a4.png" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21540)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812468

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
