### ISSUE TITLE
Permanent UI test failure - showDefaultHomeScreen - org.mozilla.fenix.screenshots.DefaultHomeScreenTest 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#26934]
This is from #26286 

### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4796425285251768883/executions/bs.11f0a22cb1de0162/testcases/1/errors
### Stacktrace: 
```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId()'s resource name should match is "fxa_sign_in_button"

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f13034f
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@b89a014, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+-->ViewStub{id=16908719, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@bd770bd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+-->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@e42c6b2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=66.0, child-count=1} 
|
+--->FitWindowsLinearLayout{id=2131296340, res-name=action_bar_root, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@96aa980, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+---->ViewStubCompat{id=2131296409, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b0f5bb9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d929bfe, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+----->HomeActivityRootLinearLayout{id=2131297345, res-name=rootContainer, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@990ddac, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+------>ViewStub{id=2131297197, res-name=navigationToolbarStub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@540fa75, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+------>FragmentContainerView{id=2131296693, res-name=container, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4787a0a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+------->FragmentContainerView{id=2131296693, res-name=container, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@a37327b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+-------->CoordinatorLayout{id=2131296939, res-name=homeLayout, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@1042898, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4} 
|
+--------->AppCompatImageView{id=2131297667, res-name=wallpaperImageView, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@b3c8f1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+--------->AppBarLayout{id=2131296936, res-name=homeAppBar, visibility=VISIBLE, width=1080, height=248, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@f2c2cd6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=-248.0, child-count=1} 
|
+---------->CollapsingToolbarLayout{id=-1, visibility=VISIBLE, width=1080, height=248, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.AppBarLayout$LayoutParams@efc7b57, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+----------->AppCompatImageButton{id=2131297289, res-name=privateBrowsingButton, desc=Enable private browsing, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.CollapsingToolbarLayout$LayoutParams@b5f3644, tag=null, root-is-layout-requested=false, has-input-connection=false, x=915.0, y=80.0} 
|
+----------->AppCompatImageView{id=2131297683, res-name=wordmark, desc=Firefox Fenix, visibility=VISIBLE, width=581, height=110, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.CollapsingToolbarLayout$LayoutParams@6ab032d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=75.0} 
|
+--------->RecyclerView{id=2131297426, res-name=sessionControlRecyclerView, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@3964062, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4} 
|
+---------->ConstraintLayout{id=2131297230, res-name=onboarding_card, visibility=VISIBLE, width=992, height=736, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@c6375f3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=-244.0, child-count=4} 
|
+----------->AppCompatTextView{id=2131296916, res-name=header_text, visibility=VISIBLE, width=904, height=88, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@13b72b0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=44.0, text=Privacy protection by default, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=2131296770, res-name=description_text, visibility=VISIBLE, width=904, height=99, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@761a529, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=165.0, text=Featuring Total Cookie Protection to stop trackers from using cookies to stalk you across sites., input-type=0, ime-target=false, has-links=false} 
|
+----------->OnboardingRadioButton{id=2131297626, res-name=tracking_protection_standard_option, visibility=VISIBLE, width=860, height=148, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@e357e4f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=88.0, y=308.0, text=Standard (default)
Balanced for privacy and performance. Pages load normally., input-type=0, ime-target=false, has-links=false, is-checked=true} 
|
+----------->OnboardingRadioButton{id=2131297627, res-name=tracking_protection_strict_default, visibility=VISIBLE, width=860, height=148, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@95d09dc, tag=null, root-is-layout-requested=false, has-input-connection=false, x=88.0, y=500.0, text=Strict
Blocks more trackers so pages load faster, but some on-page functionality may break., input-type=0, ime-target=false, has-links=false, is-checked=false} 
|
+---------->ConstraintLayout{id=2131297230, res-name=onboarding_card, visibility=VISIBLE, width=992, height=453, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@1c66ae5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=536.0, child-count=3} 
|
+----------->AppCompatTextView{id=2131296916, res-name=header_text, visibility=VISIBLE, width=904, height=67, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@82b79ba, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=44.0, text=You control your data, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=2131296770, res-name=description_text, visibility=VISIBLE, width=904, height=99, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@975b06b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=150.0, text=Firefox gives you control over what you share online and what you share with us., input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatButton{id=2131297312, res-name=read_button, visibility=VISIBLE, width=904, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@9ee7c8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=277.0, text=Read our privacy notice, input-type=0, ime-target=false, has-links=false} 
|
+---------->ConstraintLayout{id=2131296685, res-name=conclusion, visibility=VISIBLE, width=992, height=314, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@af7d061, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=1121.0, child-count=2} 
|
+----------->AppCompatTextView{id=2131296916, res-name=header_text, visibility=VISIBLE, width=992, height=138, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@9077786, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Ready to open up an amazing internet?, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatButton{id=2131296892, res-name=finish_button, visibility=VISIBLE, width=992, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@63ce847, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=182.0, text=Start browsing, input-type=0, ime-target=false, has-links=false} 
|
+---------->View{id=-1, visibility=VISIBLE, width=1080, height=243, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@49eb874, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1435.0} 
|
+--------->ConstraintLayout{id=2131297592, res-name=toolbarLayout, visibility=VISIBLE, width=1080, height=157, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@180119d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1565.0, child-count=6} 
|
+---------->View{id=2131296588, res-name=bottom_bar, visibility=VISIBLE, width=1080, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=fa
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/aef6c0a5e404556ad7ff1b1f58c3d8eda7c3d4d1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21541)

**Comment by AndiAJ** [comment]
Failed 1x on 10/31 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5237905420324421538/executions/bs.911fffdc4d07f5c1/testcases/7/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5237905420324421538/executions/bs.34a2f13545d6d6d2/testcases/7/test-cases)

androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId()'s resource name should match is "fxa_sign_in_button"

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f13036d
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1794, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@ace9f1a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+-->ViewStub{id=16908719, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@68fda4b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+-->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=1731, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c4fc28, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=63.0, child-count=1} 
|
+--->FitWindowsLinearLayout{id=2131296340, res-name=action_bar_root, visibility=VISIBLE, width=1080, height=1731, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@5a792e6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+---->ViewStubCompat{id=2131296410, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@affd027, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1731, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@581b2d4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+----->HomeActivityRootLinearLayout{id=2131297383, res-name=rootContainer, visibility=VISIBLE, width=1080, height=1731, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@dc9f772, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+------>ViewStub{id=2131297229, res-name=navigationToolbarStub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c8f47c3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+------>FragmentContainerView{id=2131296698, res-name=container, visibility=VISIBLE, width=1080, height=1731, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4b12840, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+------->FragmentContainerView{id=2131296698, res-name=container, visibility=VISIBLE, width=1080, height=1731, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@b31d379, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+-------->CoordinatorLayout{id=2131296950, res-name=homeLayout, visibility=VISIBLE, width=1080, height=1731, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@b3c18be, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4} 
|
+--------->AppCompatImageView{id=2131297714, res-name=wallpaperImageView, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@9149d1f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+--------->AppBarLayout{id=2131296947, res-name=homeAppBar, visibility=VISIBLE, width=1080, height=236, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@aa0886c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=-236.0, child-count=1} 
|
+---------->CollapsingToolbarLayout{id=-1, visibility=VISIBLE, width=1080, height=236, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.AppBarLayout$LayoutParams@f732e35, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+----------->AppCompatImageButton{id=2131297326, res-name=privateBrowsingButton, desc=Enable private browsing, visibility=VISIBLE, width=126, height=126, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.CollapsingToolbarLayout$LayoutParams@e1d02ca, tag=null, root-is-layout-requested=false, has-input-connection=false, x=922.0, y=76.0} 
|
+----------->LinearLayout{id=2131297731, res-name=wordmark, visibility=VISIBLE, width=570, height=105, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.CollapsingToolbarLayout$LayoutParams@b6fec3b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=71.0, child-count=2} 
|
+------------>AppCompatImageView{id=2131297732, res-name=wordmarkLogo, visibility=VISIBLE, width=105, height=105, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@943bf58, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+------------>AppCompatImageView{id=2131297733, res-name=wordmarkText, visibility=VISIBLE, width=439, height=47, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c3578b1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=131.0, y=26.0} 
|
+--------->RecyclerView{id=2131297467, res-name=sessionControlRecyclerView, visibility=VISIBLE, width=1080, height=1731, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@7708196, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4} 
|
+---------->ConstraintLayout{id=2131297266, res-name=onboarding_card, visibility=VISIBLE, width=996, height=700, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@2671117, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=-79.0, child-count=4} 
|
+----------->AppCompatTextView{id=2131296927, res-name=header_text, visibility=VISIBLE, width=912, height=84, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@be17904, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=42.0, text=Privacy protection by default, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=2131296777, res-name=description_text, visibility=VISIBLE, width=912, height=94, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@ef7eeed, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=158.0, text=Featuring Total Cookie Protection to stop trackers from using cookies to stalk you across sites., input-type=0, ime-target=false, has-links=false} 
|
+----------->OnboardingRadioButton{id=2131297672, res-name=tracking_protection_standard_option, visibility=VISIBLE, width=870, height=140, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@941a7b3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=84.0, y=294.0, text=Standard (default)
Balanced for privacy and performance. Pages load normally., input-type=0, ime-target=false, has-links=false, is-checked=true} 
|
+----------->OnboardingRadioButton{id=2131297673, res-name=tracking_protection_strict_default, visibility=VISIBLE, width=870, height=140, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@97f2170, tag=null, root-is-layout-requested=false, has-input-connection=false, x=84.0, y=476.0, text=Strict
Blocks more trackers so pages load faster, but some on-page functionality may break., input-type=0, ime-target=false, has-links=false, is-checked=false} 
|
+---------->ConstraintLayout{id=2131297266, res-name=onboarding_card, visibility=VISIBLE, width=996, height=430, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@3f18ce9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=663.0, child-count=3} 
|
+----------->AppCompatTextView{id=2131296927, res-name=header_text, visibility=VISIBLE, width=912, height=63, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@bfe2d6e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=42.0, text=You control your data, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=2131296777, res-name=description_text, visibility=VISIBLE, width=912, height=94, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@e250c0f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=142.0, text=Firefox gives you control over what you share online and what you share with us., input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatButton{id=2131297349, res-name=read_button, visibility=VISIBLE, width=912, height=126, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@20ce49c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=262.0, text=Read our privacy notice, input-type=0, ime-target=false, has-links=false} 
|
+---------->ConstraintLayout{id=2131296690, res-name=conclusion, visibility=VISIBLE, width=996, height=239, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@9cd0ea5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=42.0, y=1219.0, child-count=2} 
|
+----------->AppCompatTextView{id=2131296927, res-name=header_text, visibility=VISIBLE, width=996, height=71, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@f63b27a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Ready to open up an amazing internet?, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatButton{id=2131296903, res-name=finish_button, visibility=VISIBLE, width=996, height=126, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@2305a2b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=113.0, text=Start browsing, input-type=0, ime-target=false, has-links=false} 
|
+---------->View{id=-1, visibility=VISIBLE, width=1080, height=231, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.r
