### ISSUE TITLE
Add final telemetry for wallpaper v2

### ISSUE THREAD

**Issue by onemahon** [mozilla-mobile/fenix#26945]
Update telemetry with metrics required for wallpapers V2 as defined in #26908

Metrics should include:
- adding a `source` extra to wallpaper selections from the wallpaper settings page (see https://github.com/mozilla-mobile/fenix/pull/26893)
- clicks on link to learn more, including which wallpaper collection and link are being clicked

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21546)

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 107.0a1 from 09/23 with Xperia 10 (Android 12). The following events were generated:

1. The "Wallpapers" settings screen is displayed.
   {
          "timestamp": 6970,
          "category": "wallpapers",
          "name": "wallpaper_settings_opened"
        }

2. A wallpaper is selected from the settings screen.
   {
          "timestamp": 8142,
          "category": "wallpapers",
          "name": "wallpaper_selected",
          "extra": {
            "source": "settings",
            "theme_collection": "classic-firefox",
            "name": "twilight-hills"
          }

3. "Learn more" link is clicked.
   {
          "timestamp": 2280,
          "category": "wallpapers",
          "name": "learn_more_link_click",
          "extra": {
            "collection_name": "independent-voices",
            "url": "https://mozilla.com/stories/joy-of-color"
          }
