### ISSUE TITLE
update Ecosia and Qwant search engines with new logos

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#26951]
In [BZ-1774819](https://bugzilla.mozilla.org/show_bug.cgi?id=1774819) the logo of the Ecosia search engine was updated for the desktop version of Firefox 102. I guess the same should happen for Firefox and Focus on Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21549)

**Comment by SoftVision-LorandJanos** [comment]
Tested it on the latest Nightly 106.0a1 (2022-09-15) by manually adding the mentioned search engines with the following result:
![Screenshot_2022-09-15-12-37-04-10_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/48829350/190371433-efbdff11-442e-4b65-9048-37fd82fc8a1b.jpg)
![Screenshot_2022-09-15-12-37-22-69_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/48829350/190371454-30f7443c-d9dc-4192-92e9-e977c14c72e0.jpg)
![Screenshot_2022-09-15-12-37-43-71_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/48829350/190371456-c8b66e4c-561c-452a-8093-b60f36a0f0bd.jpg)

The logos don't appear updated. Please correct me if I made a mistake somewhere. Thank you!

Devices used:
- Oppo Find X5 (Android 12).
- Google Pixel 4 (Android 12).

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox RC 105.2.0, 106.0b4 and Nightly 107.0a1 (2022-10-05) by setting the language of the device to German before launching Firefox after a fresh install and the Ecosia and Qwant search engine logos are updated.
![Screenshot_20221006-110635~2](https://user-images.githubusercontent.com/50983519/194280236-a7693f5e-a4fe-40a9-bb84-a66a50aa32ec.png)
### Devices used:
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)
