### ISSUE TITLE
[Experiment] The TCP CFR is displayed for the Control branch for all users

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#26959]
**[Affected Versions]:**
- Firefox Nightly 106.0a1 (Build #2015903787), 67ba299f7+, AC: 106.0.20220912143111, 54c57f88d7, GV: 106.0a1-20220912094615, AS: 94.1.0

**[Affected Platforms]:**
- Android 9 - Samsung Galaxy S8

**[Prerequisites]:**
- Have a Firefox build set to have the [[QA] Firefox Android Nightly MR New User Onboarding](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-new-user-onboarding/details#recipe-json) recipe added to the main initial_experiments.json file.
- Have a way to observe logcat.

**[Steps to reproduce]:**
1. Open Firefox with a [telemetry command](https://mozilla.github.io/glean/book/user/debugging/android.html) and observe events to make sure you are enrolled into the Control branch.
2. Navigate to a webpage.
3. Observe the toolbar.

**[Expected result]:**
- The TCP CFR is not displayed.

**[Actual result]:**
- The TCP CFR is displayed.

**[Notes]:**
- This issue is also reproducible for existing users - [[QA] Firefox Android Nightly MR Existing User Onboarding](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-existing-user-onboarding).
- Attached is a recording of the issue.

![control cfr](https://user-images.githubusercontent.com/53752296/189919477-96bb807f-dd26-44e9-b67f-23eab20f23fd.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21555)

**Comment by Mugurell** [comment]
@heres-maria Can you help with what should we look for in logcat to identify the used branch?

**Comment by heres-maria** [comment]
But in this case you could also access the Secret Settings > Nimbus Experiments > [name of the experiment] screen to see the branch (for the Light theme the checkmark will be difficult to see, but it is there).

**Comment by Mugurell** [comment]
I was asking because I see the `enrollment` logs only appearing for the debug version while the recipe from https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-new-user-onboarding/details is for nightly so if testing on debug it will need to be updated.

**Comment by Mugurell** [comment]
If testing on Nightly and checking programatically the branch with
> < NimbusApi >.getExperimentBranch("mr2022")

and then the `tcp-cfr` status with 
> FxNimbus.features.mr2022.value().sectionsEnabled[Mr2022Section.TCP_CFR]

I always see the value from [nimbus.fml.yaml](https://github.com/mozilla-mobile/fenix/blob/3aff74b40ab5535cd8efe798f1bf44bac67df01f/nimbus.fml.yaml#L196).

So at this time I don't think the `initial_experiments.json` overrides `nimbus.fml.yaml`.
@jhugman Do you have more context about this?

**Comment by heres-maria** [comment]
- Related to the enrollment logs, I was looking for [this event](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/nimbus_events_enrollment) (using this command: org.mozilla.fenix/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es sendPing events --es debugViewTag MH-1). 
  - I do have ```debuggable = true``` set in local properties, if that makes a difference. 
- And related to the build used I also have the ```nimbus.remote-settings.url = https://firefox.settings.services.mozilla.com``` line added to local properties and a new ".nimbus" file created in the main project file (.../fenix/.nimbus , where local.properties is also located) containing the ```https://firefox.settings.services.mozilla.com``` line.

**Comment by Amejia481** [comment]
@Mugurell when you tested did you 

When you were testing did you alter the `targeting` field in the `initial_experiments.json` to be `true` instead of 
`  "targeting": "(app_version|versionCompare('106.*') <= 0) && ((is_already_enrolled) || ((days_since_install < 7) && (app_version|versionCompare('106.!') >= 0)))"`. As I think this controls when you are enrolled into the experiment ?  :)

**Comment by Amejia481** [comment]
I'm seeing the same as @Mugurell described on https://github.com/mozilla-mobile/fenix/issues/26959#issuecomment-1245610567

**Comment by Mugurell** [comment]
Thank you @Amejia481 !
Confirming that if I am to hardcode `true` for `targetting` then the configuration from `initial_experiments.json` does apply.
Would that mean then that there's an issue with [the experiment configuration](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-new-user-onboarding/details#recipe-json) - with defaults being applied instead of the Nimbus configuration?
Not sure if the experiments (at least initially) would have different values than the default set in app but might worth checking the config to ensure new users would be immediately enrolled and follow the Nimbus configuration.
@cpeterso

**Comment by cpeterso** [comment]
> Would that mean then that there's an issue with [the experiment configuration](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-new-user-onboarding/details#recipe-json) which results in the defaults being applied instead of the Nimbus configuration?
> Not sure if the experiments (at least initially) would have different values than the default set in app but might worth checking the config to ensure new users would be immediately enrolled and follow the Nimbus configuration.

We don't want to see the TCP CFR in the control branch.

IIUC, the MR feature flags are all enabled by default in Fenix Nightly code. So the control branch will flip the flags to `false` (a non-default value) while the treatment branches want (some of) the flags to be true (their default values).

**Comment by Mugurell** [comment]
It seems like the `initial_experiments.json` does apply but how the targetting is set prevents new installs of 106 to be enrolled.
> "targeting": "(app_version|versionCompare('106.*') <= 0) && ((is_already_enrolled) || ((days_since_install < 7) && (app_version|versionCompare('106.!') >= 0)))"

Looks like these conditions should be double checked on whether we want that or not and I’d think this targetting can be configured when setting the experiment but not sure how it works.

**Comment by heres-maria** [comment]
The issue can also be more easily reproduced for the existing users experiment by the following STR:
1. Download http://ftp.mozilla.org/pub/fenix/nightly/2022/09/2022-09-20-05-01-25-fenix-107.0b1-android-arm64-v8a/
2. Install the apk.
3. Enable debug menu by tapping 5 times on the Firefox icon in Settings > About Firefox Nightly
4. Enable Settings > Secret Settings > Use Nimbus Preview Collection
5. Close and reopen the app 3 times.
6. Enable the debug menu again.
7. Go to Settings > Nimbus Experiments > [QA] Firefox Android Nightly MR Existing User Onboarding and you should have been automatically enrolled in a branch.
8. If you have been enrolled in Control, restart the browser.
9. If you have been enrolled in another branch, tap the Control branch and restart the browser.
10. Navigate to a webpage

It does not seem specific to first run experiments.

**Comment by heres-maria** [comment]
Based on new requirements, the TCP CFR is no longer part of the experiment. The two remaining branches of the experiments should display the same behavior. As a result I will mark this issue as verified fixed.
