### ISSUE TITLE
Remove `wallpaperV2Enabled` flag, legacy wallpaper code, and file migration code.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26968]
Remove the following:

- wallpaperV2Enabled flag
- legacy use cases
- legacy file manager
- legacy downloader
- wallpaper file migration code
- legacy wallpaper assets in `/res`

This should be done after sufficient time has passed to ensure users in each release channel have received an update that includes the migration code. I would tentatively suggest targeting no earlier than v109.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21560)

**Comment by mcarare** [comment]
DS might be able to provide info that would help decide the timing.

**Comment by MatthewTighe** [comment]
> DS might be able to provide info that would help decide the timing.

That's a good suggestion. One way they might be able to determine "old" wallpaper users is that we are adding a `source` extra to the wallpaper selected metric which determines whether it's been selected through onboarding or the settings page. That extra would not be present in versions before 106

**Comment by joc-a** [comment]
I can pick this up

**Comment by MatthewTighe** [comment]
@joc-a We are not ready for this to be actionable yet. We will need to verify through our metrics that the migration path is no longer necessary before we can remove it. Generally speaking, the `eng:ready` label will be applied once an issue is ready for a patch.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809803

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
