### ISSUE TITLE
Search widget has height of 2 cells on Sony Xperia phone(s?)

### ISSUE THREAD

**Issue by Bryneth** [mozilla-mobile/fenix#26965]
### Steps to reproduce

Place search widget on home screen.

### Expected behaviour

Height should be 1 cell

### Actual behaviour

Height is 2 cells

### Device name

 Sony Xperia 10 IV

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

104.2.0

### Additional information

![image](https://user-images.githubusercontent.com/60485777/189980496-dbee7bb8-0e54-4ee8-8bc8-145a293352d9.png)

This is occurring on my new  Sony Xperia 10 IV, from looking at Reddit comments etc I suspect the issue is common to all Sony Xperia phones with a 21:9 aspect ratio. It's possible to resize horizontally to as small as 1 cell wide, but there's no ability to resize vertically - presumably because the widget is expected to be 1 cell high.

Previously listed as an issue here: https://github.com/mozilla-mobile/fenix/issues/25384 but closed as it was phrased as a request for the ability to vertically resize the widget!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21558)

**Comment by AdinaPetridean** [comment]
Hi @Bryneth .Thank you for your report!
I tried to reproduce this issue on the latest Nightly 106.0a1 (2022-09-19) and Firefox RC 104.2.0 with Xperia 10 (Android 12)  and I couldn't reproduce it.
Please see if you still reproduce the issue if you clear your data before to see if some setting might have interfered with how the widget appears. Thank you!

**Comment by Bryneth** [comment]
Hi @AdinaPetridean, I cleared data (from settings/Delete browsing data). That didn't do anything so I also cleared app cache and data, uninstalled and reinstalled. The widget is still default 5x2 and not vertically resizable.
I installed Nightly 106.0a1, and as you can see below I get the same issue. :( 
![0220919-143809](https://user-images.githubusercontent.com/60485777/191031363-6ac6cfee-110a-4ae5-a628-b1001f07224c.png)

**Comment by AdinaPetridean** [comment]
Hi @Bryneth 
Thanks for your quick reply. I will look further into this issue on multiple devices and come back with my feedback.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807575

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
