### ISSUE TITLE
Enable wallpapers v2 flag

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26966]
The `wallpaperV2Enabled` FeatureFlag should be enabled in time for 106

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21559)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/22 with Google Pixel 6 (Android 13). The Wallpapers 2.0 are available and can be set. 
![1663837636771](https://user-images.githubusercontent.com/89388888/191712413-36eed2c7-6641-46a4-8a7a-1e6f363152f5.JPEG)

**Comment by delia-pop** [comment]
Verified as fixed on Beta 106.0b3 as well, with Lenovo Yoga Tab 11 (Android 11).
