### ISSUE TITLE
[Experiment] The non-MR homescreen CFR is not displayed for the Control or Treatment B branches

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/fenix#26960]
**[Affected Versions]:**
- Firefox Nightly 106.0a1 (Build #2015903787), 67ba299f7+, AC: 106.0.20220912143111, 54c57f88d7, GV: 106.0a1-20220912094615, AS: 94.1.0

**[Affected Platforms]:**
- Android 9 - Samsung Galaxy S8

**[Prerequisites]:**
- Have a Firefox build set to have the [[QA] Firefox Android Nightly MR New User Onboarding](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-new-user-onboarding/details#recipe-json) recipe added to the main initial_experiments.json file.
- Have a way to observe logcat.

**[Steps to reproduce]:**
1. Open Firefox with a [telemetry command](https://mozilla.github.io/glean/book/user/debugging/android.html) and observe events to make sure you are enrolled into the Control or Treatment B branch.
2. Navigate to a webpage.
3. Go to the homepage and observe it.

**[Expected result]:**
- The “Your personalized Firefox homepage now makes it easier to pick up where you left off. Find your recent tabs, bookmarks and search results.” CFR is displayed for the Control and Treatment B branches.

**[Actual result]:**
- The “Your personalized Firefox homepage now makes it easier to pick up where you left off. Find your recent tabs, bookmarks and search results.” CFR is not displayed for the Control and Treatment B branches.

**[Notes]:**
- This issue is also reproducible for existing users - [[QA] Firefox Android Nightly MR Existing User Onboarding](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-existing-user-onboarding).
- Attached is a recording of the issue.

![initial jump back in cfr](https://user-images.githubusercontent.com/53752296/189922821-8781ec20-1248-49ee-89ad-5e79d1c55f78.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21554)

**Comment by Amejia481** [comment]
Thanks for the information @heres-maria !

1. Would you mind sharing which version on Fenix are you building locally (Nightly, Beta, Release or debug)?
2. Could you share the `initial_experiments.json` file that you are using for testing? And in which path it's located as we have two at the moment.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/773158/189967659-af222a93-1a71-4d7e-ae97-ea1a6acbfbba.png">

**Comment by Amejia481** [comment]
Looking at the [json recipe](https://experimenter.services.mozilla.com/nimbus/qa-firefox-android-nightly-mr-new-user-onboarding/details#recipe-json), it looks like both should not show, based on what the branch indicate to do ("`jump-back-in-cfr": false)`.


### Treatment b
```json
        {
          "feature": {
            "enabled": true,
            "featureId": "mr2022",
            "value": {
              "sections-enabled": {
                "home-onboarding-dialog-existing-users": false,
                "home-onboarding-dialog-new-users": false,
                "jump-back-in-cfr": false,
                "sync-cfr": false,
                "tcp-cfr": true,
                "wallpapers-selection-tool": false
              }
            }
          },
          "ratio": 1,
          "slug": "treatment-b"
        }
```

### Control branch
 ```json
     {
          "feature": {
            "enabled": true,
            "featureId": "mr2022",
            "value": {
              "sections-enabled": {
                "home-onboarding-dialog-existing-users": false,
                "home-onboarding-dialog-new-users": false,
                "jump-back-in-cfr": false,
                "sync-cfr": false,
                "tcp-cfr": false,
                "wallpapers-selection-tool": false
              }
            }
          },
          "ratio": 1,
          "slug": "control"
        }
```

**Comment by gabrielluong** [comment]
Is it possible that you have already seen the Jump Back In CFR? This CFR is only ever displayed once. If you were an existing user and saw the CFR prior to this build, the CFR will not show up.

**Comment by heres-maria** [comment]
- The CFR I was expecting to see was the one found in [this slide](https://docs.google.com/presentation/d/1RNDZ0QmBujjuSLg6GIkX3Yrh-YHvQKLpei58glukPDA/edit#slide=id.g143a8918bba_4_76). 
- The build used is Nightly built from main, with 
```
nimbus.remote-settings.url = https://firefox.settings.services.mozilla.com
debuggable = true
```

set in local.properties and a new ".nimbus" file created in the main project file (.../fenix/.nimbus , where local.properties is also located) containing the ```https://firefox.settings.services.mozilla.com``` line.
- This is [the initial_experiments.json](https://drive.google.com/file/d/1OvnsIm_R6O9WkgX8XDOw7N4OnTebbd39/view?usp=sharing) file I am using and it is the one at ".../app/src/main/res/raw/initial_experiments.json". I have not modified the other one.

I apologize for the unclear details.

**Comment by heres-maria** [comment]
And I can also confirm that I had not already seen the CFR in the Existing Users case. The exact STR I used in that case are:
1. Install a random Fenix Nightly 105.
2. Change the collection to Preview from the Debug menu (displayed after 5 taps on the Firefox icon in About Firefox Nightly) > Secret Settings > Use Nimbus Preview Collection (enable).
3. Close and reopen the app 3 times (without navigating to any webpage).
4. Check in Debug menu > Nimbus Experiments > [QA] Firefox Android Nightly MR Existing User Onboarding that you are in the right branch.
5. Close the app and install the Fenix Nightly 106 build over the first one.
6. Open the app again.
7. Navigate to a webpage.
8. Tap the home button.

**Comment by heres-maria** [comment]
@Amejia481 I am building the Nightly build variant.

**Comment by Amejia481** [comment]
Based on [the control and treatment b branches](https://github.com/mozilla-mobile/fenix/issues/26960#issuecomment-1245728222) we are indicating that the Jump Back In CFR should not show `"jump-back-in-cfr": false`.

Only in the branch treatment a, it's where we are indicating that it should show.

  ```json
      {
          "feature": {
            "enabled": true,
            "featureId": "mr2022",
            "value": {
              "sections-enabled": {
                "home-onboarding-dialog-existing-users": true,
                "home-onboarding-dialog-new-users": true,
                "jump-back-in-cfr": true,
                "sync-cfr": true,
                "tcp-cfr": true,
                "wallpapers-selection-tool": true
              }
            }
          },
          "ratio": 1,
          "slug": "treatment-a"
        }
```

**Comment by heres-maria** [comment]
I see why the CFR in its latest form would not be displayed on those branches based on the branch configuration. 
That being said, based on the design presented in [the plan outlined here](https://docs.google.com/presentation/d/1RNDZ0QmBujjuSLg6GIkX3Yrh-YHvQKLpei58glukPDA/edit#slide=id.g143a8918bba_4_76), my understanding was that the Treatment A branch should display the updated CFR, while the Control and Treatment B branches should display an older version of the same CFR. 
As I am unsure of this interpretation and the latest design changes, I will refer the experiment owner for the expected behavior. @athomasmoz, could you please take a look?

**Comment by athomasmoz** [comment]
Thanks for the callout @heres-maria ! You're correct, the initial intent was to compare 2 versions of the card. The implementation of the flag shows on/off for the CFR instead, so that is a bug. However, I discussed with engineering and  we have decided not to fix that. So the experiment will instead test the new jump back in CFR versus no Jump Back In CFR. I will update the plan

**Comment by cpeterso** [comment]
Since we don't plan to fix this bug for the MR v106 experiment, I will close this bug.
