### ISSUE TITLE
Remove long press action from tabs

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#2696]
When long pressing a tab on the home screen ,we present the user with the menu to create a tab collection. Unfortunately there's no indication that the user is creating a tab collection if they're unfamiliar with this menu. We should consider making this more clear or removing it altogether.

**Comment by lime124** [comment]
removing ux label and adding it with other issues regarding collections for a bigger ux effort.

**Comment by ekager** [comment]
Closing because made redundant by tabs tray
