### ISSUE TITLE
Disable DNT requests

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#2697]
### Why/User Benefit/User Problem
If we can choose to enable or disable DNT requests on Firefox for Desktop, it should be an option on Android too. 

### What/Requirements
A toggle to disable DNT requests

### Acceptance Criteria (how do I know when I’m done?)
It's possible to disable DNT requests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11617)

**Comment by KrasnayaPloshchad** [comment]
This problem may will cause some website administrators to take actions to ingore any DNT request from Firefox.

**Comment by dabat** [comment]
I vote for this option, however, I do not see an option in Firefox desktop to turn the Do-Not-Track function off.

I only see options for `Always` (send the DNT request) and `Only when Firefox is set to block known trackers`.

Am I missing something?
![image](https://user-images.githubusercontent.com/37282138/151675943-47db92d3-9d22-45d0-910a-646b94332fc5.png)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807459

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
