### ISSUE TITLE
Tabs Tray is incorrectly opened when attempting to close the Tab Pickup CFR while the search bar is active 

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#26977]
### Steps to reproduce

Preconditions: 
Make sure the user has an account.
On Desktop or another mobile device visit some webpages making sure you are signed in with the same account.

1. Perform a clear data. Launch the Firefox application.
2. From the "Pick up where you left" section tap on Sign in button and sign in with the same account.
3. Dismiss the Onboarding. 
4. While the search bar is active, scroll up. 
5. When the Tab Pick up CFR is displayed, tap the "X" button.
6. Observe the result.

### Expected behaviour

The CFR is dismissed when tapping the "X" button.

### Actual behaviour

Tabs Tray is incorrectly opened when attempting to close the Tab Pickup CFR while the search bar is active. 
Please note that sometimes due to issue https://github.com/mozilla-mobile/fenix/issues/26690 the CFR cannot be dismissed at all.

### Device name

One Plus 9 PRO 

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 106.0a1 09/14

### Additional information

Please note this issue is reproducible on all devices.

https://user-images.githubusercontent.com/108326843/190133293-0dd551ac-06a8-45a1-9086-f13eff797171.mp4

https://user-images.githubusercontent.com/108326843/190133341-ca3bc0bc-736f-4e8e-ba5a-20f9dff43372.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21564)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812466

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
