### ISSUE TITLE
bug: wallpaper onboarding is not shown if any of the thumbnails can not be loaded

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26971]
Changed logic while [refactoring](https://github.com/mozilla-mobile/fenix/pull/26758#discussion_r964257663), want to check if there are enough available wallpapers to show the wallpaper onboarding.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21561)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/23 with Google Pixel 6 (Android 13). The wallpaper selection tool is not displayed if the app was launched without network connection and the thumbnails could not be downloaded. After restoring the network connection and restarting the app, the tool will be displayed on homepage.
