### ISSUE TITLE
adjust wallpaper onboarding design

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26973]
Had a review round with @Ekaterina Galetski, agreed on these changes:
– change horizontal spacing to 32, keeping vertical as 16;
– remove extra spacing below the bottom button;
– rounded corner should be 8 dp;
– raise background dimming to 0.04;
– check if there is an easy fix for now shadow situation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21562)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/23. 

![1663915985303](https://user-images.githubusercontent.com/89388888/191907055-f9543e17-d8c7-40a0-8d05-c3e63e66cc14.JPEG)
