### ISSUE TITLE
Instrument the automation pipeline via Amplitude

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#2698]
Main assumption behind this effort (and issues like #1273) is that poor performance of the automation pipeline is a source of friction in the day-to-day life of developers. Our CI systems should aid developers, not hinder them. Given that we're dealing with a fairly complex system that involves many different moving parts and a wide configuration space, instrumenting it becomes necessary to succeed in both _making_ and _keeping_ it fast and reliable.

One way to approach this is to schedule an additional task as part of our PR/whatever pushes that will run once all tasks in the group are resolved. This task will gather runtime statistics for all of the scheduled tasks (module tasks, decision task, etc), annotate them with relevant meta data (which worker-type task ran on, what kind of task it is, result type, etc), and send that off to Amplitutde.

Once the data is in Amplitude, we should be able to create dashboards, deep dive into data, create alerts, graphs, etc. Amplitude is a powerful analytics tool that is getting a wide adoption at Mozilla. It should be a really good fit here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-11618)

**Comment by kbrosnan** [comment]
As part of https://github.com/mozilla-mobile/fenix/issues/26855 this report is closed. We should integrate Fenix build tools with the desktop/Gecko build reporting if that is not already implemented but that seems like a separate bug.
