### ISSUE TITLE
Onboarding "Welcome to an Independent Internet" dialog feels a bit like a speed-bump when you launch Firefox by clicking a link in another app

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#26985]
I got the onboarding dialog today ("Welcome to an Independent Internet") when starting Nightly for the first time, and it felt a bit off, so I wanted to file a bug documenting the experience in case there's any polishing/rethinking we want to do.

My steps/experience:
1. I saw an interesting news article elsewhere on my phone (on my "off-the-left-side-of-home" Android news-feed) that I want to quickly read in a few moments. I tapped the link.
2. Firefox Nightly launched (it's my default browser).
3. ...BUT, instead of the news article, I see a full-page "Welcome to an Independent Internet" splash screen, with a "Get Started" button.
4. I tapped "Get Started".
5. Now I'm looking at my news article.

I'm left feeling a bit puzzled and wondering why Firefox felt the need to insert that "welcome" splash screen into the flow.  It felt a bit like it was just an interruption with no clear benefit/information.[1]

(This seems to have been the splash screen from #26548, which seems to have been enabled in Nightly ~2 weeks ago in #26739, though it only showed up on my phone today.)

[1] Looking at the graphics mockups of this splash screen on #26548 , it looks like perhaps there was a bit of information "Pick up where you left off with tabs from other devices now on your homepage".  I didn't notice this when I actually got this dialog -- perhaps because the text is small and I wanted to click through to my article.  I wonder if this flow-interrupting full-screen onboarding dialog is really the best way to highlight this, at a moment where users aren't even looking at the home screen?  If we want to highlight that behavioral change, perhaps it'd be better to do so in in a contextual callout/bubble when the user is looking at the home screen.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21568)

**Comment by jonalmeida** [comment]
This is a bug - you shouldn't see any onboarding when using an in-app browser experience (aka Custom Tab).

**Comment by dholbert** [comment]
Thanks @jonalmeida - to clarify, I did initially describe this as being an in-app browser experience when I mentioned this in Slack, but after retracing my steps I think I was mistaken, and I did in fact fully launch Firefox (via clicking a link in an external app).

For me at least, the news articles on my Android "swipe-left newsfeed" all seem to launch the full Firefox app rather than an in-app browser.

(The user experience/expectation is largely the same, though.  When I tap a link in an external app, I expect Firefox to open that link for me one way or another, and not necessarily to funnel me into any Firefox tour/announcement.)

**Comment by jonalmeida** [comment]
> For me at least, the news articles on my Android "swipe-left newsfeed" all seem to launch the full Firefox app rather than an in-app browser.

Ah, thanks for clarifying. Then yes, this is a different scenario, that maybe we want to consider: entering from an external non-custom tab intent.

Opinion: maybe we can show the onboarding only when the user visits the new tab page?

**Comment by dholbert** [comment]
> after retracing my steps [...] I did in fact fully launch Firefox (though I did so via clicking a link in an external app).

Having said that, we should of course double-check to be sure that this behaves as-expected when the user opens an "app tab" aka Custom Tab.  (Presumably we don't want to show the dialog in that case; not sure if we actually do or not.)  Including if the user "breaks out" of the in-app browser by using three-dot-menu and choosing "Open in Firefox Nightly" -- that point would also be an awkward spot for an interruption.

I don't know how to get back into the "tour pending" state, so I don't know how to test these scenarios myself, but we should be sure they're tested & behave as-expected.

**Comment by delia-pop** [comment]
We tested both scenarios on the latest Nightly from 09/15 with Google Pixel 6 (Android 13). 
The Onboarding card is displayed when sharing a tab to Fenix from an extern intent and when a custom tab is opened from an external app as well. 

https://user-images.githubusercontent.com/89388888/190449995-b119b0d6-374e-4754-ada5-480696512674.mp4

https://user-images.githubusercontent.com/89388888/190450155-9274c9b1-9a8f-4f40-a4d3-6ae501c05622.mp4
