### ISSUE TITLE
Task continuity flag should be enabled for all channels

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#26980]
As part of the MR, we should turn on the `taskContinuityFeature` feature flag for all channels

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21566)

**Comment by SoftVision-LorandJanos** [comment]
Verified on the latest builds:
- latest Nightly 106.0a1 (2022-09-16).
- latest Beta GV: 106.0a1-20220915171049 (2022-09-16T13:48:16.394676).
- latest Release GV: 106.0a1-20220915171049 (2022-09-16T14:12:08.594911).

Task Continuity is enabled for all channels.
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.
