### ISSUE TITLE
Update MR Onboarding strings for existing users

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#26987]
It appears the strings got updated for the MR onboarding for existing users since it was landed. Got the request from @Kate-Galetski to update them to the strings seem in https://www.figma.com/file/d7l1iGabQYqnLcnQbHDGzM/Wallpaper-2.0-%2B-Onboarding-v106?node-id=6615%3A200457

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21570)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 106 from 09/15 with Google Pixel 6 (Android 13). The onboarding cards match the Figma design.

![Onboarding](https://user-images.githubusercontent.com/89388888/190458027-fef50120-6667-4796-83a1-dc5667561253.png)
