### ISSUE TITLE
wallpapers onboarding filtering

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#26995]
Follow up for [issues/26750](https://github.com/mozilla-mobile/fenix/issues/26750)

Currently only classic wallpapers are shown. We want to have 3 seasonal first, if available, the rest – classic.

[design](https://www.figma.com/file/d7l1iGabQYqnLcnQbHDGzM/Wallpaper-2.0-%2B-Onboarding-v106?node-id=7946%3A223536)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21573)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/23. The Wallpaper selection tool displays the non-wallpaper option, 3 seasonal wallpapers and 2 classic wallpapers.

![1663838503908](https://user-images.githubusercontent.com/89388888/191903859-6ce8d501-56a9-4488-8ffa-0ddf36d6b9fd.JPEG)
