### ISSUE TITLE
[Bug]: The Wallpapers Settings screen is empty

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#26997]
### Steps to reproduce

1. Install the latest Nightly 106.0a1 from 09/15.
2. Go to Settings > Homepage > Wallpapers.
3. Observe if the wallpaper options are displayed.

### Expected behaviour

The wallpaper thumbnails are displayed.

### Actual behaviour

The section is completely empty.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 

### Additional information

<img src="https://user-images.githubusercontent.com/89388888/190338906-36f0a837-a4e3-4026-bb78-0fe7d1690693.JPEG" width="40%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21574)

**Comment by Mugurell** [comment]
I'm seeing 404 when the download is tried.
@MatthewTighe

**Comment by mcarare** [comment]
@MatthewTighe While investigating this, I've also seen [this](https://github.com/mozilla-mobile/fenix/pull/26909#issuecomment-1245988183) comment.  From what I understand, If no wallpaper thumbnails are downloaded, the default wallpaper should still show up. 

Is there a specific group that it should belong to? In tests (and code) I have seen it is added to the classic collection. But what if that collection does not exist and an existing one has no thumbnails downloaded? 


On a related note, if `mapOf(Wallpaper.DefaultCollection to listOf(Wallpaper.Default))` is supposed to replace a map with collections that do not have available wallpaper thumbnails, the check should be if the wallpaper list (the resulting filtered by thumbnails download state) is empty, not the map itself. 

`.takeIf { map ->
    map.values.any { it.isNotEmpty() }
} ?: mapOf(Wallpaper.DefaultCollection to listOf(Wallpaper.Default))`

**Comment by MatthewTighe** [comment]
For v1 wallpapers, only `beach-vibe` (note this name has also been corrected for v2 to `beach-vibes` and `twilight-hills` are available remotely. The `amethyst` wallpaper will only be available under the update paths. 

This looks to be a side effect of updating the settings page. I will open a patch to fix this, but it also shouldn't occur after https://github.com/mozilla-mobile/fenix/pull/26967 lands

**Comment by delia-pop** [comment]
Verified as fixed on latest Nightly 107.0a1 from 09/19 with Lenovo Yoga Tab 11 (Android 11). The wallpapers from both Classic and Limited Edition collections are displayed and can be properly downloaded and set. 

![Screenshot_2022-09-20-10-41-58-854](https://user-images.githubusercontent.com/89388888/191200292-1d1c6026-6f00-4989-a85f-01137408daab.jpeg)

**Comment by SoftVision-LorandJanos** [comment]
This issue is still reproducible on the latest Beta (106.0b1).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Oppo Find X5 (Android 12).
- Google Pixel 6 (Android 13).

**Comment by MatthewTighe** [comment]
This should also be improved by https://github.com/mozilla-mobile/fenix/pull/26967, as we won't be hitting the v1 code path that caused this bug and will instead be showing all the wallpapers including the MR ones. We are letting that patch bake in nightly for a few days before uplifting, as it effects quite a lot of the internal implementations so we'd like to be assured it won't surface new issues.
