### ISSUE TITLE
When only "default" wallpaper available, heading still shows "Limited Edition" on wallpaper settings screen

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#26994]
On Wallpaper Settings screen, when no wallpaper thumbnails are available (try in an emulator) , only the default one gets fetched locally. 
Expected : Heading to only default wallpaper should be "Classic Firefox"
Actual : Heading shows "Limited Edition"

<img width="297" alt="image" src="https://user-images.githubusercontent.com/29518411/190309522-a12dd336-862b-4469-ad1b-224e7b54b800.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21572)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813864

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
