### ISSUE TITLE
Push notifications from device are not displayed on facebook.com

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/fenix#26998]
### Preconditions
Account login is performed.
Push notifications are enabled from the device and the page.

### Steps to reproduce

1. Navigate to facebook.com .
2. Leave the browser in the background.
3. Receive a notification (friend request, comment).
4. Observe the result.

### Expected behavior

Push notification is received,

### Actual behavior

Nothing happens.

### Device name

Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density),  Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)

### Android version

Android 12, Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 106.0a1 (2015904075-🦎106.0a1-20220913213020🦎)

### Additional information

In order to reproduce the issue, 2 accounts will be needed, one to send notifications, and one to receive notifications.
Originally reported here: https://github.com/webcompat/web-bugs/issues/110399

**Comment by SoftVision-LorandJanos** [comment]
Hi @softvision-raul-bucata! I can confirm, notifications are not sent through.
Facebook app and on Chrome the notifications are received as expected.
Devices used:
- Oppo Find X5 (Android 12).
- Google Pixel 6 (Android 13).

Tested on the latest Nightly 106.0a1 (2022-09-19) build.

**Comment by kbrosnan** [comment]
My understanding from previous webcompat investigations of this is that Firefox gets a significantly different website from Chrome. Facebook does not send Firefox Android a website that asks for push notifications.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809286

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
