### ISSUE TITLE
Tab Pickup CFR and Synced tabs section are not displayed for existing user until a manual sync is performed

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27001]
### Preconditions:
Make sure the user has an account and is logged in on an older version using "Ready to scan" option.
On Desktop or another mobile device visit some webpages making sure you are signed in with the same account.

### Steps to reproduce
1. Update the app and launch the Firefox application.
2. Tap on Get Started button.
3. On homepage wait approximately 15 seconds. 
4. Perform some navigation and return to homepage.
5. Observe the result.
6. Go to Settings and perform a manual sync.

### Expected behaviour

After step 4, "Your tabs are syncing! Pick up where you left off on your other device." CFR and Synced tabs section are displayed on homepage.

### Actual behaviour

Tab Pickup CFR  and Synced tabs section are not displayed on homepage until a manual sync is performed.

### Device name

One Plus 9 PRO

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 106.0a1 09/15

### Additional information

Please note that this issue is also intermittent on Poco M4 Pro (Android 12), Lenovo Yoga Tab 11 (Android 11).
Please note that although this issue might look similar to https://github.com/mozilla-mobile/fenix/issues/26878, in this case the user did not remain on homepage without performing some navigation.

https://user-images.githubusercontent.com/108326843/190365760-ebd9f829-8029-460d-9355-00870f57a2a8.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21579)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812463

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
