### ISSUE TITLE
[Bug]: [a11y] The Top Sites are not announced or selected with Talkback

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27004]
### Steps to reproduce

1. Have several Top Sites available on the homepage.
2. Activate Talkback or other accessibility service.
3. Tap on the Top Site tiles and observe if they are selected and announced.

### Expected behaviour

When tapping on a Top Site, the shortcut is selected with a green highlight.
The screen reader announces its title, the location on screen and the available actions (double tap to activate, double tap and hold to long press).

### Actual behaviour

The Top Sites are not announced or selected with Talkback. 
Note that Talkback only announces "Page 1 of 2" and "Page 2 of 2" when navigate through all the Top Site icons (when more than 8 are available) using the Talkback swipe gestures.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 106.0a1 from 09/14 and 09/15

### Additional information

https://user-images.githubusercontent.com/89388888/190383047-8f0d8967-8838-4fff-b24c-dcedafaf6f32.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21580)

**Comment by SoftVision-LorandJanos** [comment]
Reproduced the issue on an earlier version of Nightly and on the latest Beta (106.0b1).
Verified as fixed on the latest Nightly 107.0a1 (2022-09-21T17:07:51.921501).
Device used: Google Pixel 4 (Android 12).
Closing the ticket as verified.
