### ISSUE TITLE
[Bug] can not install add ons, I need your help sir.

### ISSUE THREAD

**Issue by HirumaDaichi** [mozilla-mobile/fenix#27000]
Failed to install add ons buster captcha for humans..

This notification show up when I am try to install that add ons on my firefox nightly android, can you help me?

https://imgur.com/a/szdfKmX

**Comment by Juraj-Masiar** [comment]
**Are you using AdGuard app?**
There is a strange bug that breaks installation AND updates of all addons.
To fix it you need to:
1) disable Adguard (the main switch in the app)
2) open Firefox Settings page
3) click "Delete browsing data"
4) check "Cached images and files", all other can be unchecked
5) click "Delete browsing data"
That will fix the broken installation/update of addons.

**Comment by HirumaDaichi** [comment]
> **Apakah Anda menggunakan aplikasi AdGuard? ** Ada bug aneh yang merusak instalasi DAN pembaruan semua add-on. Untuk memperbaikinya, Anda perlu:
> 
> 1. nonaktifkan Adguard (saklar utama di aplikasi)
> 2. buka halaman Pengaturan Firefox
> 3. buka bagian "Hapus data penjelajahan"
> 4. centang "Gambar dan file yang di-cache", semua yang lain tidak dapat dicentang
> 5. klik "Hapus data penjelajahan"
> 
> Itu akan memperbaiki instalasi/pembaruan add-on yang rusak.
> 
> Saya tidak tahu apakah ini bug Firefox atau bug AdGuard, tetapi seseorang harus menyelidiki dan memperbaikinya, terima kasih :)

The result still same sir, cannot install.

**Comment by kbrosnan** [comment]
This is a support request. https://github.com/mozilla-mobile/fenix/wiki#communication
