### ISSUE TITLE
[Bug]: After dismissing the onboarding, a shared tab from external apps is displayed on homepage instead of being opened in new tab

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/fenix#27016]
### Steps to reproduce

1. Have an older Fenix version installed and Fenix set as default browser.
2. Update Fenix to the latest version, but don't open the app yet.
3. Go to an external app and share a tab/article with Fenix.
4. Once Fenix is opened, dismiss the Onboarding cards.
5. Observe if the tab shared in Step 3 is opened properly.

### Expected behaviour

The shared article should be opened directly in a new tab.

### Actual behaviour

The shared article is displayed in the "Jump back in" section on Homepage.

### Device name

Google Pixel 6 

### Android version

Android 13

### Firefox release type

Firefox Nightly

### Firefox version

Nightly 106.0a1 from 09/15

### Additional information

Observed while testing the scenario in https://github.com/mozilla-mobile/fenix/issues/26985 .
Note that this issue does not occur for a new user. When opening a link directly in Fenix, it is opened as a new tab.

https://user-images.githubusercontent.com/89388888/190452682-8c24877f-1c16-434f-94bb-8541f8157769.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21586)

**Comment by Mugurell** [comment]
We probably shouldn't show the new onboarding when the app is launched from an external url - issue discussed here - https://github.com/mozilla-mobile/fenix/issues/26985#issuecomment-1248293525 so when that's fixed the scenario for this bug would not exist anymore.

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 107.0a1 from 10/11 with Google Pixel 6 (Android 13). After sharing an article with Fenix/opening a link from another app, Fenix is launched and the Onboarding is displayed. Once the cards are dismissed, the page is correctly opened in a new tab or custom tab. 

https://user-images.githubusercontent.com/89388888/195119311-1407d506-6726-4b1f-945d-6bca9790b9b9.mp4


https://user-images.githubusercontent.com/89388888/195119343-32411099-817f-42f2-87ab-7859a7b107bf.mp4


https://user-images.githubusercontent.com/89388888/195119359-2fa04105-a6b6-4920-a9e0-f11c208869bb.mp4
