### ISSUE TITLE
Consider increasing the "Sign in" button on the "Switching screen is easier than ever" page

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27011]
### Steps to reproduce

1. Update the app and launch the Firefox application.
2. Tap on Get Started button.
3. Use the Accessibility Scanner scan the "Switching screen is easier than ever" page.

Actual behaviour
Consider making the Automatic clickable item larger, from 38 dp, to 48 dp or larger.

### Expected behaviour

No suggestions are made.

### Actual behaviour

Consider making this clickable item larger. This item's height is 44 dp. Consider making the height of this touch target 48 dp or larger.

### Device name

One Plus 9 Pro

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 106.0a1 09/15

### Additional information

<img src="https://user-images.githubusercontent.com/108326843/190425925-3f5db530-fbaf-423f-ace6-ef8cf123ab49.JPEG" width="50%" />

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21585)

**Comment by AdinaPetridean** [comment]
Still reproducible on Firefox 108.0b1 with OnePlus 9 Pro (Android 12).

**Comment by AdinaPetridean** [comment]
Still reproducible on Firefox 109.0b2 with Motorola Moto G9 plus (Android 11).

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812462

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
