### ISSUE TITLE
Add capability to override telemetry URL

### ISSUE THREAD

**Issue by jrbenny35** [mozilla-mobile/fenix#27023]
### What is the user problem or growth opportunity you want to see solved?

Collecting telemetry from Fenix now is a bit involved to do locally. The steps are outlined [here](https://docs.google.com/document/d/1WqG9YnVnMJ3hk7vcym-kmxT2bsx92HqDagtl3nMG9wM/edit#heading=h.pazw2yi5ih1r). Allowing for a URL to be specified to send telemetry too, would help simplify this use case.

### How do you know that this problem exists today? Why is this important?

This isn't necessarily a problem but more of an enhancement to aid in testing/QA work.

### Who will benefit from it?

Softvision QA Team, Nimbus Engineering Team

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21589)

**Comment by jrbenny35** [comment]
What would be the best practice to allow this field to be changed based on build types? The default field is specified here, https://mozilla.github.io/glean/book/reference/general/initializing.html#gleaninitializeconfiguration

**Comment by kbrosnan** [comment]
This sounds like something we could add to secret settings.

**Comment by jonalmeida** [comment]
We can surface `serverUrl` setting [here](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L159) in the debug UI for the android app.

Since it's set during app initialization, it'll have to be a flag that is set _after_ the first run so the new serverUrl is set in the UI and then the next app restart will use the newly set URL.

That might affect QA's ability to test first run glean events or Nimbus experiments. Does that work @jrbenny35 ? We can find alternatives to solving this, but it'll require some new work to add the ability to do similar things to GeckoView with reading a config file during first init.

**Comment by jrbenny35** [comment]
> 
> That might affect QA's ability to test first run glean events or Nimbus experiments. Does that work @jrbenny35 ? We can find alternatives to solving this, but it'll require some new work to add the ability to do similar things to GeckoView with reading a config file during first init.

You're saying the way you proposed will affect QA's ability to run first run testing? Or if they set the URL, it would affect their ability since they have to do the restart.

**Comment by jonalmeida** [comment]
> You're saying the way you proposed will affect QA's ability to run first run testing? Or if they set the URL, it would affect their ability since they have to do the restart.

It will affect QA ability to run first run testing. 👍

**Comment by jrbenny35** [comment]
I think that is a good solution for now until we can get something into GeckView like you mentioned earlier. Thanks @jonalmeida

**Comment by jonalmeida** [comment]
> I think that is a good solution for now until we can get something into GeckView like you mentioned earlier. Thanks jonalmeida

Just to clarify, I didn't mean put something _into_ GeckoView, but rather doing something like this [configuration file](https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/automation.html#configuration-file-format).

We can work on the serverUrlOverride in that case for now.

**Comment by rocketsroger** [comment]
As agreed with @jrbenny35.  This will only be supported on Nightly and debug builds.

**Comment by delia-pop** [comment]
Hi, @jrbenny35, is this something the Manual QA team should check? If so, we can reach out to the Ecosystem QA team to help us. We verified that the option to set a custom Glean server URL is displayed in Secret Settings in Nightly 108.0a1 from 11/06 .

![1667834884262](https://user-images.githubusercontent.com/89388888/200349492-c3d68f55-163a-47e4-8b37-d312be1f6e33.JPEG)

**Comment by delia-pop** [comment]
Great, thank you. I will close this ticket and remove the QA needed label then.

**Comment by rocketsroger** [comment]
Reopen as request from @jrbenny35 to add local properties as another way of injecting the custom Glean server URL.

**Comment by Dexterp37** [comment]
Hey folks, can I get a better understanding of why this is needed?
We'd love to improve our ecosystem and if the current debug tooling have problems (logs, debug view), we'd rather like to fix them consistently instead of having custom solutions for each product and pave the way for custom workflows.

@jrbenny35 , @rocketsroger or @jonalmeida  What is/are the current workflow for which sending telemetry to a custom endpoint is needed?

Thanks!

**Comment by jrbenny35** [comment]
> Hey folks, can I get a better understanding of why this is needed? We'd love to improve our ecosystem and if the current debug tooling have problems (logs, debug view), we'd rather like to fix them consistently instead of having custom solutions for each product and pave the way for custom workflows.
> 
> @jrbenny35 , @rocketsroger or @jonalmeida What is/are the current workflow for which sending telemetry to a custom endpoint is needed?
> 
> Thanks!

Hi Alessio, this specifically was for me wanting to create automation around testing a local nimbus server and getting the app to read from it.

@rocketsroger has implemented a solution for setting a custom telemetry URL. This change will potentially help our QA folks to specify a nimbus server and to be able to test experiments from it, without having to rebuild the app.

Also, sorry for the late reply

**Comment by Dexterp37** [comment]
@jrbenny35 thanks for the clarification! Let us know if there's something we can do to make your / QA life easier.
