### ISSUE TITLE
Add error message to the the wallpaper onboarding

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/fenix#27021]
Follow up for [this](https://github.com/mozilla-mobile/fenix/pull/26944), was blocked by [this](https://github.com/mozilla-mobile/fenix/pull/26671)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21588)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/23 with Google Pixel 6 (Android 13). An error snackbar is displayed when attempting to download the full size wallpapers without network connection.

![1663871350541](https://user-images.githubusercontent.com/89388888/191904129-397218e4-97ce-472c-8c84-73c7ad7c7131.JPEG)
