### ISSUE TITLE
Address bar suggestions needs to utilise horizontal tablet screen better

### ISSUE THREAD

**Issue by HubKing** [mozilla-mobile/fenix#27027]
### What is the user problem or growth opportunity you want to see solved?
I am using a 10.5-inch tablet in landscape mode. When I type something in the address bar, I want to see matches in history, but currently, FireFox Suggest is not visible, because the 4 suggestions from the search engine takes up the entire visible area. I can scroll down, but methinks that I would not have to, if FireFox utilised the tablet screen better. I mean, as you see, there is a lot of empty space. 

How about making the entries flow (not one item per line, but continuously displayed after another), or make the items multi column (have 2 or 3 columns so that 2 or 3 items can be displayed in one row)

![screen](https://user-images.githubusercontent.com/10900489/190501477-ce141b89-476d-4c90-bbfb-07bd22e23524.jpg)

### How do you know that this problem exists today? Why is this important?
It should be a problem for people who use tablets in landscape mode, which I think is common.

### Who will benefit from it?
Tablet users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21592)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807590

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
