### ISSUE TITLE
Correct Padding between heading and wallpaper on Wallpaper Settings screen

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#27020]
In line wallpaper heading and the wallpaper so they both have the same 16dp padding from start.
Current behavior : 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/29518411/190471851-637076ea-49a5-4cb0-be5c-11da6b0dd800.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21587)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/23. 
![1663915956083](https://user-images.githubusercontent.com/89388888/191907349-5446b5c4-a0a3-473e-b0f2-8b4bf61c2952.JPEG)
