### ISSUE TITLE
Use the wallpaper adapted text color for the Collections placeholder

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/fenix#27026]
<img width="465" alt="Screen Shot 2022-09-15 at 4 24 49 PM" src="https://user-images.githubusercontent.com/1190888/190501868-758dec6a-efce-4c79-acf1-a7fa3190a49b.png">

This was identified in a UX review. We want to use the wallpaper adapted text color for the Collections placeholder

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21591)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 107.0a1 from 09/23 with Google Pixel 6 (Android 13). The Collections placeholder adapts to the text color.

![collections](https://user-images.githubusercontent.com/89388888/191995991-f3ca9e48-340e-4c7a-9916-d0a6bd6a631d.jpg)

**Comment by delia-pop** [comment]
Verified as fixed on Beta 106.0b3 as well, with Lenovo Yoga Tab 11 (Android 11).
