### ISSUE TITLE
Use placeholder inplace of app name for @string/wallpaper_classic_title

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#27029]
Coming from Use placeholder in place of app name for @string/wallpaper_classic_title"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21593)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/22. The placeholder "%s" is used.
