### ISSUE TITLE
Use textAccent instead of textSecondary for Learn more in wallpaper settings

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#27024]
UX agreed to use textAccent for _Learn More_ in the description of wallpapers on Wallpaper Settings screen instead of textSecondary

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21590)

**Comment by delia-pop** [comment]
Hi, @sarah541. I tested this on Nightly 107.0a1 from 09/20 with Google Pixel 6 (Android 13), but in the current version the "Learn more" link for seasonal wallpapers is not displayed.

<img src="https://user-images.githubusercontent.com/89388888/191322571-f0187165-4539-4d6c-9b9a-c25f815ce500.JPEG" width="40%" />

**Comment by sarah541** [comment]
Hi @delia-pop The Learn More link only shows up when the learn more url is available. As to when the url will be available, @Kate-Galetski @MatthewTighe will be a better person to reach out.

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/22 with Google Pixel 6 (Android 13). The "Learn more" link is displayed as required and tapping on it opens the following SUMO page: https://www.mozilla.org/en-US/stories/joy-of-color

![LearnMore](https://user-images.githubusercontent.com/89388888/191708779-70957b0b-ecf4-429e-b021-898e6a5553a5.jpg)
