### ISSUE TITLE
[Spike] Investigate whether and which CFR popups should be sticky unless explicitly dismissed

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#27033]
## Title
During our investigations in Focus and planning, UX observed that our CFRs were not sticky and can therefore be dismissed unintentionally when trying to (for example) interact with web content and then miss important information.

## Description
The CFRPopup has the flag [`dismissOnClickOutside`](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopup.kt#39) (defaulted to true) which we can flip to ensure the popup is not mistakenly dismissed.

## Deliverables
List all the CFR pops we have and investigate with UX which ones need to sticky or not.

cc: @jeffreygee

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21595)

**Comment by Mugurell** [comment]
Seems like we have only two other CFRs that don't use the new composable.
- the "Private Browsing Shortcuts" CFR [implemented as a PopupWindow](https://github.com/mozilla-mobile/fenix/blob/9822a2d65bdc29ec69a6918f77d229d097f39d9c/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L820=L860) which 
    - is automatically dismissed with an outside click but
    - is not dismissed when the screen is rotated.
- the "Inactive Tabs CFR" [implemented as a Dialog](https://github.com/mozilla-mobile/fenix/blob/c7ebec360227c70ce2ba0243b88321eac39eee89/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInactiveTabsOnboardingBinding.kt#L67-L123) which
    - is not dismissed with an outside click
    - is not dismissed when the screen is rotated
    
The rest of the CFRs seem to use the new [CFRPopup](https://github.com/mozilla-mobile/fenix/blob/c7ebec360227c70ce2ba0243b88321eac39eee89/app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopup.kt) which:
    - is automatically dismissed by a back button press / a click outside
    - is automatically dismissed when the screen is rotated.
    
Preventing a back button press / outside CFR touch dismissing it is easily controllable through [CFRPopupProperties](https://github.com/mozilla-mobile/fenix/blob/c7ebec360227c70ce2ba0243b88321eac39eee89/app/src/main/java/org/mozilla/fenix/compose/cfr/CFRPopup.kt#L38-L39).
Preventing the screen rotation from dismissing it is a bit more complex. In the current implementation an effort is made to dismiss it in this scenario to prevent anchoring issues upon rotation.
One approach we could try is still dismissing the CFR when the screen rotates but maybe after a small delay show it again.

---- 
(For a background on the anchoring issues and the decision to dismiss all menus and popups the following tickets can be checked:
- [[Bug][Tablet] Main menu is not displayed correctly after rotating the device from landscape to portrait](https://github.com/mozilla-mobile/fenix/issues/15344)
- [BrowserMenu incorrectly positioned on Android <=23](https://github.com/mozilla-mobile/android-components/issues/9101)
- [[Bug]Improperly displayed Tabs Tray, Top Sites, and search engine "More options" overlay](https://github.com/mozilla-mobile/fenix/issues/17092)
- [PR - Dismiss toolbar menu when configuration change occurs](https://github.com/mozilla-mobile/fenix/pull/17682)
- Similar issues with the Compose menu were seen and fixed also by dismissing them when the screen is rotated - [[Bug]: "Recently visited section" - Switching between portrait and landscape mode, the Remove menu is overlapping the URL bar](https://github.com/mozilla-mobile/fenix/issues/23138)

**Comment by Mugurell** [comment]
@jonalmeida Not sure what the next steps are here? 🤔

**Comment by jonalmeida** [comment]
Sorry for the slow response, I think I missed this notification.

We were waiting to hear back from @jeffreygee who wanted to bring this up in a UX meeting to see how we could align on this behaviour. Will bring this up in our next Focus weekly check-in.

**Comment by jeffreygee** [comment]
Apologies, I updated a different ticket.

After discussing with the team, here's our intended CFR behavior: 
- is **dismissed** when user hits close button (X) or action on CFR (i.e. href) 
- is **not dismissed** with an outside click
- is **not dismissed** when the screen is rotated. @jonalmeida's proposal (_One approach we could try is still dismissing the CFR when the screen rotates but maybe after a small delay show it again._) seems like a good option to mediate this.
- has no scrim behind it so the user isn't taken out of the experience
- close button (X) has a touch target that follows accessibility guidelines (48x48dp on android, 44x44px on iOS)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812461

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
