### ISSUE TITLE
[Bug]: open link in apps doesn't work

### ISSUE THREAD

**Issue by dylantrevor87** [mozilla-mobile/fenix#27038]
### Steps to reproduce

1. enable "open links in apps" option
2. load https://www.androidworld.it/app/offerte-play-store-14-settembre.html/amp
3. click on some link to apps, like "Paranormal Territory GRATIS"

### Expected behaviour

the play store app should be opened

### Actual behaviour

the app page is opened in fenix

### Device name

samsung galaxy a42 5g

### Android version

android 12

### Firefox release type

Firefox

### Firefox version

104.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21598)

**Comment by mcarare** [comment]
@dylantrevor87 are you visiting the AMP version of that website? In the  normal version tapping on a link opens the play store app.

**Comment by SoftVision-LorandJanos** [comment]
Hi @dylantrevor87 ! Thanks for your report!
I wasn't able to reproduce the issue you described. From the link you have in step 2, tapping on your "Paranormal Territory GRATIS" opened it in the Playstore app.
Device used: Oppo Find X5 (Android 12).

**Comment by csadilek** [comment]
Closing as we were not able to reproduce the problem. Please re-open if you can still reproduce this.
