### ISSUE TITLE
[Bug]: [foxfooding] Little padding around the "Get started" button

### ISSUE THREAD

**Issue by pdehaan** [mozilla-mobile/fenix#27035]
### Steps to reproduce

1) Upgrade Firefox Nightly
2) Open Firefox Nightly
3) See the "Welcome to an independent internet" screen

### Expected behaviour

The "Get started" button stands on its own.

### Actual behaviour

The "Get started" button is flush with the text "More colours. Better privacy. Same commitment to people over profits."

### Android version

na

### Firefox release type

Firefox Nightly

### Firefox version

106

### Additional information

**Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
**Window Size (inner width and height):** 1638x1127
**GitHub Username:** @Vinnl

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21596)

**Comment by pdehaan** [comment]
![issue-55](https://user-images.githubusercontent.com/557895/190522992-4f4ad6cc-1de1-4a22-8250-c8f695615a08.png)

**Comment by Mugurell** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/26929.
Not sure whether we should allow the hero image to get smaller to support the other content fit the screen or ensure all the elements (including paddings) are static and just allow scrolling when they don't fit the screen.

**Comment by Vinnl** [comment]
Oh yeah, I didn't even realise the three dots were there if I'd scrolled down, so there's that too.

**Comment by pdehaan** [comment]
@Vinnl What mobile device are you using?
Bonus points if you know the resolution: http://whatismyscreenresolution.net/

**Comment by Vinnl** [comment]
@pdehaan I'm on a Fairphone 2, 396x704 according to https://whatismyscreenresolution.org (.net didn't load).

**Comment by AdinaPetridean** [comment]
Also reproducible with Nokia 6 (A 7.1.1) on Nightly 107.0a1 from 10/12 and RC 106.1.0. The resolution is 360x640.

**Comment by kbrosnan** [comment]
Adding a spacer seems fine. I don't think that this is high priority given that this was designed for the 106 release. We don't have any current plans to reuse this design.

**Comment by AdinaPetridean** [comment]
Verified as fixed on Nightly 110.0a1 from 01/05 with Nokia 6 (A 7.1.1). Added padding around the boarding and content buttons.
