### ISSUE TITLE
Downloading files fails when in a password protected folder

### ISSUE THREAD

**Issue by MaxJalon** [mozilla-mobile/fenix#27043]
### Steps to reproduce

Visit a folder on a website that is password protected but not secured "https:"
Enter username and password 
Folder is "browsing enabled"
Long tap on a file chose "Download Link"
Answer is: "Download failed"

but: If I chose "Copy link"
and then paste the direct link in FF address bar 
it downloads the file normally

### Expected behaviour

It should download the file directly

### Actual behaviour

Doesn't download

### Device name

Alcatel S1 Fairphone 2 and others

### Android version

Android 9 and Android 10

### Firefox release type

Firefox

### Firefox version

104.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21603)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810196

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
