### ISSUE TITLE
[Bug]: Firefox display recent visited website even when the option is off

### ISSUE THREAD

**Issue by kud** [mozilla-mobile/fenix#27048]
### Steps to reproduce

1. Go to settings
2. Customise
3. Disable all options regarding the homepage except shortcuts
4. Go to your homepage

![Screenshot_20220917-112344](https://user-images.githubusercontent.com/655838/190850063-0246569c-cca1-44ba-834c-864fe7405905.jpg)

### Expected behaviour

I see my history.

### Actual behaviour

I should see only the bookmarks I've pinned.

### Device name

OnePlus 6T

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 (Build #2015904459)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21606)

**Comment by kbrosnan** [comment]
This was changed to align with desktop Firefox. The preference was renamed and now toggles the whole Shortcuts section like all the other preferences in that list. We are aware that some people liked the old behavior and considering ways to bring something similar to Firefox. Currently the collections feature will allow you to control exactly what is on the list.

**Comment by kud** [comment]
Hey @kbrosnan , thanks for the reply.

Collection feature isn't what I'd like exaxctly because I don't want a group of websites/tabs. But it does the job for the moment, yes. 

But I also see that I can't sort myself the tabs in the collection. 😬
