### ISSUE TITLE
[Bug]: Browser width/height are not updated when orientation changes

### ISSUE THREAD

**Issue by wwwouaiebe** [mozilla-mobile/fenix#27052]
### Steps to reproduce

1. activate 'Scroll to hide toolbar' in the settings ( settings -> customize -> scroll to hide toolbar )
2. open an html file and scroll to hide the toolbar
3. set your device in 'portrait' orientation
4. look the values of height and width in window. visualViewport. The height is greater than the width (ok it's portait)
5. set your device in 'landscape' orientation 
6. look the values of height and width in window. visualViewport. The height remains greater than the width ( not ok )
7. scroll to show the toolbar and do the same tests. Height and width are now correct and adapted to the device rotation
8. see in the device logs the html file used for tests (renamed index.txt...)

### Expected behaviour

The width and height have to be adapted  with the device orientation.

### Actual behaviour

width and height are not changed when the toolbar is hidden with a scroll

### Device name

Samsung Galaxy tab A7 lite SM-T225

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

104.2.0

### Device logs

[index.txt](https://github.com/mozilla-mobile/fenix/files/9594222/index.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21608)

**Comment by Mugurell** [comment]
Moving the ticket to Bugzilla for more investigation.
Please follow the progress there.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1791342

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
