### ISSUE TITLE
Profiles with more than one first_run_date in the first session ping

### ISSUE THREAD

**Issue by lucia-vargas-a** [mozilla-mobile/fenix#27061]
### Steps to reproduce

Querying the number of first_run_date per client_id in the first session ping returns more than one value.

```
WITH first_runs AS
(
  SELECT
    client_info.client_id, COUNT(1) AS dates
  FROM
    `moz-fx-data-shared-prod.org_mozilla_firefox_stable.first_session_v1`
  WHERE
  DATE(submission_timestamp) >= '2021-01-01'
  AND DATE(submission_timestamp) = SAFE.PARSE_DATE('%F', SUBSTR(client_info.first_run_date, 1, 10))
  AND ping_info.seq = 0
  GROUP BY 1
)
SELECT
  COUNT(client_id) clients,
  COUNT(IF(dates>1, client_id, NULL)) AS clients_with_many_first_run_date
FROM first_runs
WHERE dates>1
```

### Expected behaviour

Each client_id has a single first_run_date in `moz-fx-data-shared-prod.org_mozilla_firefox_stable.first_session_v1` and a unique seq.
The code will only [send the ping if it hasn't been sent yet.](https://github.com/mozilla-mobile/fenix/blob/1164703571c8a1dd135481134b76df7b4f74c428/app/src/main/java/org/mozilla/fenix/components/metrics/FirstSessionPing.kt#L44)

### Actual behaviour

There are 226 profiles with more than one first_session date and same seq between 2021 and 2022. (see query above)

### Device name

NA

### Android version

NA

### Firefox release type

Firefox

### Firefox version

NA

### Device logs

NA

### Additional information

This is related to a [Glean first session ping](https://github.com/mozilla-mobile/fenix/issues/7295).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21612)

**Comment by kbrosnan** [comment]
I expect this is people that override our blocking of [Android backup](https://developer.android.com/guide/topics/data/backup). This requires root.

**Comment by chutten** [comment]
Seems plausible, as the proportions we're seeing aren't inconsistent with such a niche population. Is there a way we could confirm by detecting their override, @kbrosnan ?

**Comment by kbrosnan** [comment]
We don't have data on if the user is [rooted](https://dictionary.telemetry.mozilla.org/apps/fenix?page=1&search=root).

**Comment by kbrosnan** [comment]
Yes it is possible. Opened the above issue to look into collecting that data. It would be a few months before this hits release users.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1809326

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
