### ISSUE TITLE
Add a build task on a Windows CI machine

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#27085]
Build failures on Windows happen from time to time because we do not have any environment that builds on this system until a contributor mentions it. Most of our team's build environments are *NIX based so we tend to isolate Windows dev build setups.

We can evade this problem by adding a CI build task that only tries to run `./gradlew buildDebug` to ensure that the setup is always work and avoid bugs like https://github.com/mozilla-mobile/fenix/issues/27053.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21620)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1811661

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
