### ISSUE TITLE
Jittery graphics rendering

### ISSUE THREAD

**Issue by TwoFourTwentyFour** [mozilla-mobile/fenix#27086]
## Steps to reproduce

1. Go to any website which has animations. For example [apple.com](https://www.apple.com/).

2. Scroll down till you see moving cards.

3. Just observe.

### Expected behavior
Smooth transitions/animations.

### Actual behavior
Jittery/laggy animations. See it here in [this screen recording](https://mega.nz/file/SsxixQJB#3HHckc82rxzm9Q7cF0H9Ee8qlsLtVOzWxtWtFLVqBWg). 

### Device information
Motorola Moto G71 5G
* Android device: Android 12
* Fenix version: 105.1.0 (Build #2015904299)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21621)

**Comment by kbrosnan** [comment]
What you are reporting is not clear to me. Can you explain in more detail what parts of the animation is the problem? Collecting a perf profile https://profiler.firefox.com/docs/#/./guide-remote-profiling would be useful.

**Comment by TwoFourTwentyFour** [comment]
I mean the frames per second. For example [here](https://mega.nz/file/qs5VGLRa#19V61Obr0qTaatz8j573HEUx3cpASbhBZgWRX2cfkd0) is the preview of same animation on [Decentr Browser](https://play.google.com/store/apps/details?id=net.decentr.browser&hl=en_IN&gl=US), which is nothing but a Firefox knock-off. But animations are smooth on Decentr.

**Comment by MarcLeclair** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796249

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
