### ISSUE TITLE
Remove expired entries from the network cache

### ISSUE THREAD

**Issue by issue-dispenser** [mozilla-mobile/fenix#27087]
## Overview
The below seems like it could be significantly trimmed down periodically without user intervention (pressing `Clear Cache` stripped Data/Cache to 96MB/0MB):
<img src="https://user-images.githubusercontent.com/13922417/191421373-c60fd393-690c-4557-a027-92a623bdf269.jpg" width="500" />

The number of entries in `about:cache` is significantly larger than on my desktop (below 2000 entries at a third of the size). Also, it might be worth noting that the "Storage in use" is significantly smaller than the Cache size above (even without all the cache under `Data`):

![Screenshot_20220907-054127_Firefox Nightly](https://user-images.githubusercontent.com/13922417/191425721-d60fb5b3-a180-4a9a-9d62-f87970093c14.jpg)

## Examples
Unfortunately I had to swap devices shortly after recording this info, but I managed to get some useful data.

There seemed to be many "expired" entries, such as over 4 months old:

![Screenshot_20220907-054837_Firefox Nightly](https://user-images.githubusercontent.com/13922417/191426992-5260391e-e828-4633-bd4d-3c93f47e02d0.jpg)

Almost a year expired (also it was fetched after expired, is this a UI bug?):

![Screenshot_20220907-054934_Firefox Nightly](https://user-images.githubusercontent.com/13922417/191427124-270b44d8-7b76-423f-93f1-06a9b87d0627.jpg)

There were also a **LOT** of these (possibly related to #26420?):
<img src="https://user-images.githubusercontent.com/13922417/191429056-b8e2a437-266e-4b5f-b491-44354d629405.jpg" width="500" />

Also quite a few from `sync.services.mozilla.com`, though the ones I looked at were small in size (<200B). 

There were many other items that were only fetched a single time and were several months to a year old which could also be reasonably pruned.

## Device information
* Android 8.0
* Fenix version: 106.0a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21622)

**Comment by mcomella** [comment]
See also https://github.com/mozilla-mobile/fenix/issues/14646

**Comment by mcomella** [comment]
Triage: thank you for investigating the network cache – that was very helpful!

**The main action item from this bug** is to expire old network cache entries because it doesn't seem to be happening: I updated the title appropriately.

Outside of that, while FF taking 1.93 GB seems large to me personally, we saw that A) Chrome uses (marginally) more storage space for our triage members who use both browsers and B) in our telemetry, most users don't seem to use an unreasonable amount of storage. As such, we don't see another specific action item to take at this time – let us know if we're missing something.

**Comment by valenting** [comment]
Presumably, for the HTTP cache on android the max limit should be [512 Mb](https://searchfox.org/mozilla-central/rev/6f77213807eb5359c8afe458ac5628f973e92a25/netwerk/cache2/CacheFileIOManager.cpp#59).
As we can see in the screen capture from about:cache, it's correctly set. **I assume the cache reported by Android includes other things stored in the profile: other caches, databases, etc**

The cache entries are expired when we hit the cache limit based on [frecency](https://en.wikipedia.org/wiki/Frecency). The fact that the user still has very old entries in their cache is a bit odd. I think it's worth looking into this. Unfortunately I don't seem to have any such old entries on my local device.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807351

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
