### ISSUE TITLE
Enable wallpaper onboarding flag

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/fenix#27081]
Enable `wallpaperOnboardingEnabled` feature flag so that it is available for all channels.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21619)

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 09/22.

**Comment by AdinaPetridean** [comment]
Also verified on Firefox Beta 106.0b3 with Xperia 10 (Android 12).
