### ISSUE TITLE
Collections with empty name can be created

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27089]
### Steps to reproduce

1. Launch the FIrefox application.
2. Open a few tabsand from the tabs tray, tap the "Select tabs" button.
3. Select one/more tabs. Tap the save to collection icon.
4. Delete the "Collection 1" name and tap on OK button.
5. Check the name of the new collection.

### Expected behaviour

Collections with empty name can be created

### Actual behaviour

Collections with empty name cannot be created. An error message is displayed.

### Device name

One Plus 9 PRO

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 107.0a1 09/21

### Additional information

[Related bug](https://github.com/mozilla-mobile/fenix/issues/3489) that was previously fixed 
This issue is also reproducible on  Firefox Beta 106.0b1 and RC 105.1.0
Please note a collection also can be created by pressing on space, with emoji or using invalid characters (. ,   * , < , > , ? , \ , , : ).
This issue is also repro on Nightly 107.0a1 - 09/21.

![Collection](https://user-images.githubusercontent.com/108326843/191519057-e3fcecfa-5a9b-4da3-9c44-0aa99b7da341.JPEG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21623)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812730

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
