### ISSUE TITLE
[Bug]: The wallpaper selection tool cannot be dismissed by tapping outside the window

### ISSUE THREAD

**Issue by AdinaPetridean** [mozilla-mobile/fenix#27101]
### Prerequisites: 
The user has just installed the Firefox app for the first time.
The Tab Pickup and Jump Back In CFRs are not currently being displayed.
The user has not seen the wallpaper selection tool before.

### Steps to reproduce

1. Launch the Firefox application.
2. Visit a webpage and then return to Homepage. Repeat this step 3 times.
3. Tap outside the wallpaper selection tool. Observe the behaviour.

### Expected behaviour

The wallpaper selection tool is dismissed by tapping outside the window

### Actual behaviour

The wallpaper selection tool cannot be dismissed by tapping outside the window

### Device name

Xiaomi Pad5 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Firefox Nightly 107.0a1 09/21

### Additional information

https://user-images.githubusercontent.com/108326843/191682106-f73c3455-812f-441a-b4b3-c0e2c3ded510.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21629)

**Comment by cpeterso** [comment]
Nice to have for MR v106. 2022-09-30 is the last day will can uplift non-critical bugs to Beta v106.

**Comment by delia-pop** [comment]
Verified as fixed on Nightly 107.0a1 from 10/13 with Google Pixel 6 (Android 13) and Huawei MediaPad M2 (Android 5.1.1). The Wallpaper Selection Tool is dismissed when tapping outside the window.

https://user-images.githubusercontent.com/89388888/195527832-fb7c086a-b75a-4667-83c9-7a1060c93dab.mp4
